### ISSUE TITLE
Issue with k8s.io//docs/concepts/policy/pod-security-policy/ [File: /content/en/docs/concepts/policy/pod-security-policy.md]

### ISSUE THREAD

**Issue by achalk14** [kubernetes/website#10039]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Hi,
I am trying to learn about PodSecurityPolicy from this page https://kubernetes.io/docs/concepts/policy/pod-security-policy/ and tried my hands on "Example" section. After creating a new namespace, serviceaccount and rolebinding.

I tried executing this which was supposed to throw error and not create a pod but on my machine, it worked and pod 'pause' was created.
kubectl-user create -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name:      pause
spec:
  containers:
    - name:  pause
      image: k8s.gcr.io/pause
EOF

Although, I got this output for:
kubectl-user auth can-i use podsecuritypolicy/example
no

**Proposed Solution:**
No solution as such. I am just confused by the behavior and trying to understand why this happened.

**Page to Update:**
https://kubernetes.io/...

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by makocchi-git** [comment]
I think that your cluster needs to enable `PodSecurityPolicy` by an admission controller.
Please see [admission-controllers#podsecuritypolicy](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podsecuritypolicy).

**Comment by achalk14** [comment]
@CaoShuFeng Hi,
Seems to be working as expected now.
