### ISSUE TITLE
Fixing kubectl generated docs links

### ISSUE THREAD

**Issue by tfogo** [kubernetes/website#10081]
I've been looking into fixing the broken links on [this page](https://kubernetes.io/docs/reference/kubectl/kubectl/) that have been mentioned in a few issues.

Looks like the cause of this is that [`update-imported-docs/reference.yml`](https://github.com/kubernetes/website/blob/master/update-imported-docs/reference.yml) doesn't import all the files generated from [`hack/generate-docs.sh`](https://github.com/kubernetes/kubernetes/blob/master/hack/generate-docs.sh) in k/k. So one possible fix is just adding those files to `reference.yml`.

However, all of that information is also generated and imported by https://github.com/kubernetes-incubator/reference-docs and is available here: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

We probably don't want to kubectl docs duplicated like that. Should we just replace the https://kubernetes.io/docs/reference/kubectl/kubectl/ page with a static md file that links to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands? Or totally replace that page?

Would love to hear your thoughts/suggestions for the best way to fix this.

**Comment by tfogo** [comment]
Thanks for your input @zacharysarah!

My understanding is that `/docs/reference/kubectl/kubectl/` is generated from cobra using `k/k/hack/generate-docs.sh` and imported using [this script](https://github.com/kubernetes/website/blob/master/update-imported-docs/update-imported-docs.go). Following [Generating Reference Pages for Kubernetes Components and Tools](https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/) would overwrite `/docs/reference/kubectl/kubectl/`. 

I just want to make sure we're on the same page that this change would require removing it from the doc generation process  (specifically by removing these lines here: https://github.com/kubernetes/website/blob/master/update-imported-docs/reference.yml#L19-L20)

@steveperry-53 I'm particularly interested in your thoughts since I found a discussion on the mailing list where you suggested something else: https://groups.google.com/forum/#!topic/kubernetes-sig-docs/ZMVVNBu2TD8

**Comment by tengqm** [comment]
A related effort can be found at #9081 . The reference docs are generated using kubernetes-incubator/reference-docs. When compared this to the docs generated using `k/k/hack/generate-docs.sh`, we have a nice table view to show the command options. The [script](https://github.com/kubernetes/website/blob/master/update-imported-docs/update-imported-docs.go) is outdated. We need to fix it.

**Comment by Hartmarken348** [comment]
10081
