### ISSUE TITLE
All links from 'See Also' section at the kubectl-cli reference page links are broken

### ISSUE THREAD

**Issue by fsilveir** [kubernetes/website#10080]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:** All links at the **See Also** section of the **kubectl CLI** page are broken. Noticed that the problem was fixed before in [5789c87](https://github.com/kubernetes/website/commit/5789c874285dd261a5d3afc7333a55900de41df8), however I couldn't find the files on the repository and that seems to be the cause for the 404 errors on the page. 

As for instance related to `kubectl top` which points to https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_top.md, but there's no such reference of this file in the website repository.

**Proposed Solution:** Generate missing .md files with the same description as found on `kubectl`  utility with `--help`

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/kubectl/

**Comment by AlexStasko** [comment]
Hi,
Are there any news on this issue?

Thanks,
Alex

**Comment by warmchang** [comment]
fixed by https://github.com/kubernetes/website/pull/10550
/close
