### ISSUE TITLE
Issue with k8s.io//docs/tutorials/kubernetes-basics/update/update-interactive/ [File: /content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html]

### ISSUE THREAD

**Issue by archcra** [kubernetes/website#10082]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
I think 'v10' should be 'v1'.

```
Let’s perform another update, and deploy image tagged as v10 :

kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=gcr.io/google-samples/kubernetes-bootcamp:v10
```

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by jimangel** [comment]
The module is walking through how to set versions and rollback using tagging, by using v10 it simulates a failure ("There is no image called v10 in the repository. Let’s roll back to our previously working version. We’ll use the rollout undo command:")

Also, the examples are managed outside of kubernetes/website (https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios) if you still need to open an issue.

Thanks!
/close
