### ISSUE TITLE
wrong links

### ISSUE THREAD

**Issue by b10s** [kubernetes/website#10104]
Sorry for short description but it's pretty easy to check or I'm wrong : )

Links in main page in section "Case Studies" are wrong. One of them is 404.

![screenshot from 2018-08-28 09-22-30](https://user-images.githubusercontent.com/4618288/44693634-498aed00-aaa4-11e8-943e-5d153b9855b7.png)
![screenshot from 2018-08-28 09-22-19](https://user-images.githubusercontent.com/4618288/44693635-498aed00-aaa4-11e8-852f-ad8afa04767a.png)

**Comment by shubheksha** [comment]
@b10s, could you please specify which link is broken?

**Comment by daminisatya** [comment]
@b10s workiva has been removed from the case studies, and a PR for that has been merged on Aug 14, 2018. 

https://github.com/kubernetes/website/pull/9826/files

I think this issue is good to close.  @nikhita

**Comment by nikhita** [comment]
Fixed in https://github.com/kubernetes/website/pull/9826. Thanks for pointing that out, @daminisatya! :)

/close
