### ISSUE TITLE
Incomplete guidance for Kubectl run shell command on pod

### ISSUE THREAD

**Issue by SebGX** [kubernetes/website#10108]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
Kubectl won't find a pod to run a command unless you include the `--namespace=<namespace>` argument. Super obvious once you realize, not so obvious when the docs say you only need to specify the pod name. Incomplete docs are quite a time waster because you think that you're doing something wrong whereas the guidance given is the problem.

**Proposed Solution:**
I'm happy to help out as I go. If you'll give me access, I'll add what's missing as I work. It's the least I can do given the benefits I'm getting from Kubernetes.

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

**Comment by tengqm** [comment]
@SebGX Feel free to propose a PR (https://kubernetes.io/docs/contribute/start/#improve-existing-content). You don't need approvals to do so other than the CLA agreement. :)
