### ISSUE TITLE
Redspread link 

### ISSUE THREAD

**Issue by stormmore** [kubernetes/website#10103]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
`https://redspread.com` fails with a "Secure Connection Failed" error, removing the `https://` has it redirect to `https://coreos.com`

**Proposed Solution:**
should probably just go to `https://coreos.com` at this point

**Page to Update:**
https://kubernetes.io/...

**Comment by zembutsu** [comment]
I signed CLA.
