### ISSUE TITLE
Issue with k8s.io//docs/tasks/debug-application-cluster/audit/ [File: /content/en/docs/tasks/debug-application-cluster/audit.md]

### ISSUE THREAD

**Issue by davidvanlaatum** [kubernetes/website#10115]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
html escaping is wrong for logstash section step 4 is unusable

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by CaoShuFeng** [comment]
See: https://github.com/kubernetes/website/pull/9970
