### ISSUE TITLE
Issue with k8s.io//docs/tasks/tls/ [File: /content/en/docs/tasks/tls/_index.md]

### ISSUE THREAD

**Issue by ChristopherHanson** [kubernetes/website#10120]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Kubelet certificate rotation link (https://kubernetes.io/docs/tasks/administer-cluster/certificate-rotation/) on this page results in a 404

**Proposed Solution:**
Direct the link to the correct page or remove?

**Page to Update:**
https://kubernetes.io/docs/tasks/tls/

Kubernetes Version: 1.11

**Comment by Hartmarken348** [comment]
10120
