### ISSUE TITLE
Markdown is not rendered in headings

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#10137]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
markdown is not working in page headings - e.g. here:
https://kubernetes.io/docs/setup/independent/kubelet-integration/#workflow-when-using-kubeadm-init

related to:
https://github.com/kubernetes/website/issues/10106
it seems that the headings also don't support `>`

**Proposed Solution:**

either 
- support markdown in headings

or

- apply PRs that fix these and do not accept headings with special formatting in the future.

**Page to Update:**
https://kubernetes.io/*

/assign @zacharysarah 
/assign @Bradamant3 
to delegate to the right folks.

**Comment by lucperkins** [comment]
As far as I can tell this was fixed in #10155. Please feel free to re-open if this was closed in error.
