### ISSUE TITLE
Issue with k8s.io//docs/setup/independent/install-kubeadm/ [File: /content/en/docs/setup/independent/install-kubeadm.md]

### ISSUE THREAD

**Issue by siw36** [kubernetes/website#10135]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The very last command `systemctl restart kubelet` on [Installing kubeadm](https://kubernetes.io/docs/setup/independent/install-kubeadm/) leads to an error because kubelet cant find a configuration file.
Output of `systemctl status kubelet.service`:
```bash
error: open /var/lib/kubelet/config.yaml no such file or directory
```

**Proposed Solution:**
The following command fixes the error:
```bash
kubeadm init
```
I've seen that the initialization is the first step on the [following page](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/).
Nevertheless its confusing if you want to verify the completed steps and get promted with an error message.
Maybe mentioning that the kubelet service is yet not functional because of the missing init (which will be done in the following steps) would help to avoid troubleshooting when its not needed.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by neolit123** [comment]
> Nevertheless its confusing if you want to verify the completed steps and get promted with an error message

thank you for the report. i agree that this is bit confusing.
the kubelet on it's own is not functioning with that systemd-droping file and without the pre-setup kubeadm does anyway. after setting a cgroup driver the restart is needed, but we shouldn't really explain more if it fails there.

this is already outlined here:
https://kubernetes.io/docs/setup/independent/kubelet-integration/#workflow-when-using-kubeadm-init

/sig cluster-lifecycle
/close
