### ISSUE TITLE
I wish /docs/admin/daemons/ had a complete example.  

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/website#1014]
I wish /docs/admin/daemons/ had a complete example of how to craft and create a DaemonSet.

**Comment by jaredbhatti** [comment]
Jeff, is there an example of DaemonSets I can link to?

**Comment by jeffmendoza** [comment]
https://github.com/kubernetes/kubernetes/tree/master/examples/newrelic
https://github.com/kubernetes/kubernetes/tree/master/examples/storage/cassandra#step-8-use-a-daemonset-instead-of-a-replication-controller

Are good links to link out to.
