### ISSUE TITLE
Issue with k8s.io//docs/concepts/workloads/controllers/cron-jobs/ [File: /content/en/docs/concepts/workloads/controllers/cron-jobs.md]

### ISSUE THREAD

**Issue by MNF** [kubernetes/website#10170]
**This is a...** 

- [ x] Feature Request

**Problem:**
The documentation refers that  “schedule written in Cron format”, but from https://en.m.wikipedia.org/wiki/Cron
> In some uses of the CRON format there is also a seconds field at the beginning of the pattern. In that case, the CRON expression is a string comprising 6 or 7 fields.

It is not clear do CronJobs support seconds.

**Proposed Solution:**
Clarify do CronJobs support seconds.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by poothia** [comment]
CronJob does not support seconds. 

I think you are referring to "startingDeadlineSeconds" which is a different concept.

"the CronJob controller checks if the time now is not after the time of its scheduledTime + startingDeadlineSeconds, i.e. that it's not too late to start the job (passed the deadline). If it wasn't too late, the job will continue to be attempted to be started by the CronJob Controller. However, If it is already too late, then it doesn't start the job and records the event"

Can you clarify more on this issue?

**Comment by MNF** [comment]
We want to pull often changing data every 10 sec.  Cron format in general may support seconds. You informed me, that CronJob does not support seconds, which make it not useful for our purpose.
I still suggest to specify in documentation that “schedule written in Cron format (**_without support of seconds)”_**

**Comment by MNF** [comment]
@fejta /remove-lifecycle stale.
Please note that instructions are not clear. Where in GitHub could I specify /remove-lifecycle stale or /close ?

**Comment by MNF** [comment]
@fejta,
 I’ve added /remove-lifecycle stale comment 12 dec. Why I got the same message after 30, not 90 days? 
Is it because you’ve changed a term and now it  /remove-lifecycle rotten ?
Cc @fejta-bot

**Comment by fejta** [comment]
This is an open source project. If you think it is important that the documentation clarifies that it does not support seconds, please send the kubernetes/website maintainers a PR with that change.
