### ISSUE TITLE
I wish /docs/user-guide/replication-controller/ desribed a process for migrating from RC

### ISSUE THREAD

**Issue by analytik** [kubernetes/website#1019]
I wish /docs/user-guide/replication-controller/ described a process for migrating from RC to Replica Sets and Deployments. Some simple chart of the differences would also be handy, although probably not as important.

**Comment by jaredbhatti** [comment]
Jeff, any feedback on how feasible this is or the work required?

**Comment by jeffmendoza** [comment]
This would be fine, happy to accept any content like this.
