### ISSUE TITLE
YouTube channel should be linked from k8s.io

### ISSUE THREAD

**Issue by castrojo** [kubernetes/website#10226]
**This is a...** 

- [x ] Feature Request
- [ ] Bug Report

**Problem:**

We have a youtube channel with over 9k subscribers, but we don't link to it from the website! 

**Proposed Solution:**

Link to youtube.com/kubernetescommunity from the kubernetes.io website. Probably at the bottom with a little icon like we do our other properties? 

**Page to Update:**
https://kubernetes.io/

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by hvaara** [comment]
I think this is a great idea too! I'd love to take a look
/assign
