### ISSUE TITLE
Issue with k8s.io//docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ [File: /content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html]

### ISSUE THREAD

**Issue by walkthrough** [kubernetes/website#10225]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
tutorials module 1 sumary is lost

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@walkthrough, could you elaborate a little on what you mean by the summary being lost?
The summary seems to be accessible using this URL: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/#summary
