### ISSUE TITLE
kubernetes.io serving invalid cert

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/website#10239]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
https://Kubernetes.io is serving an invalid cert

**Proposed Solution:**
It shouldn't. 😢

**Page to Update:**
https://kubernetes.io/...

**Comment by zmerlynn** [comment]
cc @thockin (I think you were messing with both Kubernetes.io and k8s.io yesterday)
cc @lavalamp - I remember a while ago you had enough access to change this?

**Comment by zmerlynn** [comment]
Seems to be back working now, probably a hosting issue?

**Comment by tengqm** [comment]
/close

looks like it has been fixed.
