### ISSUE TITLE
CSI volume type is missing in Persistent Volume page 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/website#10231]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
In Kubernetes Persistent Volume page, CSI volume type is missing.

**Proposed Solution:**
Add CSI volume type information.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by warmchang** [comment]
ref: https://kubernetes.io/docs/concepts/storage/volumes/#csi
