### ISSUE TITLE
Issue with k8s.io//docs/tutorials/kubernetes-basics/explore/explore-interactive/ [File: /content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html]

### ISSUE THREAD

**Issue by KiraResari** [kubernetes/website#10247]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

The following interactive tutorial is not working properly:
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

The  terminal is stuck at "Starting Kubernetes..." (for over 15 minutes now), and I can't execute any commands. There  is no "$" command prompt. I can still type in the terminal, but nothing I type gets executed.

I got through the first two tutorials just fine. Then this started happening, and now  I can't even get the first two  tutorials to run again.

I've also tried reloading the page several times, as well as opening the tutorial on a different browser, but the problem remains the same.

**Comment by shubheksha** [comment]
Could you try again? @KiraResari 
If it still doesn't work, could you share your browser version and a screenshot?
Thanks!

**Comment by KiraResari** [comment]
Okay now it works again. It must have been a temporary interruption.

**Comment by shubheksha** [comment]
Awesome, glad it works now! Closing this issue 😃 
/close
