### ISSUE TITLE
Issue with k8s.io//docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ [File: /content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html]

### ISSUE THREAD

**Issue by JadeRing** [kubernetes/website#10249]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Interactive Tutorial  shows nothing.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@JadeRing, could you update the bug with the details of what browser you're using and possibly a screenshot?

**Comment by shubheksha** [comment]
Thank you, @JadeRing!
cc: @BenHall

**Comment by BenHall** [comment]
Thanks @shubheksha 

Thanks @JadeRing for alerting us. The 403 indicates that Cloudflare may have blocked your IP. Which country are you visiting coming?

In the meantime, we'll need to add a message which detects these errors and displays a more friendly message.

**Comment by JadeRing** [comment]
thanks @BenHall  for handling this,  i was visiting from China.

**Comment by BenHall** [comment]
@JadeRing Could you tell me what happens when you go to the course directly on https://katacoda.com/kubernetes-bootcamp ?

**Comment by JadeRing** [comment]
https://katacoda.com/kubernetes-bootcamp ?  
this website works fine for me

![p1](https://user-images.githubusercontent.com/38696086/45413047-c7f1ac80-b6aa-11e8-897c-a2130e20cff1.png)
![p2](https://user-images.githubusercontent.com/38696086/45413048-c7f1ac80-b6aa-11e8-9e25-ba2503712d2b.png)

**Comment by JadeRing** [comment]
@BenHall   It seems the problem is my proxy(shadowsocks), I turned its mode from PAC to Global, then the problem is gone.

![p3](https://user-images.githubusercontent.com/38696086/45414141-4c452f00-b6ad-11e8-9aea-f56a21025dbf.png)

I‘m sorry to waste your time, and thanks a lot.

**Comment by BenHall** [comment]
Thanks for letting us know! I'm not familiar with shadowsocks, is there anything we can do to get it to work in PAC mode? Or it is just because it's a 3rd party script being loaded into the domain?

**Comment by JadeRing** [comment]
As far as I know, When I use Pac mode, the domain name will use the proxy in the pac.txt file, and the domain name not in the pac.txt file will not go through the proxy.
Global mode, all the traffice go through the proxy.
Attachment  is my pac.txt  file.

[pac.txt](https://github.com/kubernetes/website/files/2374702/pac.txt)

**Comment by JadeRing** [comment]
And if you still want get it to work in PAC mode, I'm very happy to cooperate with you.
