### ISSUE TITLE
The documentation for all the Kubectl commands are missing on the website

### ISSUE THREAD

**Issue by soroush-karimi** [kubernetes/website#10241]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
Example: https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_create.md
This is referenced from https://kubernetes.io/docs/reference/kubectl/kubectl/

**Comment by DStorck** [comment]
if the goal of the page is to link to the reference docs, I can do this 
( should broken kubectl_create link to  https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#create)

**Comment by DStorck** [comment]
fixed by https://github.com/kubernetes/website/pull/10145

**Comment by shubheksha** [comment]
/triage duplicate 
Ref #10080

**Comment by shubheksha** [comment]
Closing this as a duplicate.
/close
