### ISSUE TITLE
Documentation should not mention ingress controller specific annotations [File: /content/en/docs/concepts/services-networking/ingress.md]

### ISSUE THREAD

**Issue by onitake** [kubernetes/website#10272]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The ingress resource documentation describes examples that contain an annotation that will not work with other ingress controllers besides nginx: `nginx.ingress.kubernetes.io/rewrite-target`

**Proposed Solution:**
While this may help some users, there is also a generic rewrite-target annotation called `ingress.kubernetes.io/rewrite-target`. This annotation will also work with traefik and other ingress controllers.

The documentation should be kept as implementation-agnostic as possible, so the reference to nginx should be dropped.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by anlunas** [comment]
Working on it

**Comment by onitake** [comment]
Cool, thank you.

I did a little bit of research, and it seems that behaviour differs a bit between different ingress controllers, but at least ingress-nginx and Træfik have supported the generic annotation for a while.
I don't know about others.

**Comment by onitake** [comment]
Apparently, what I said is not quite true, as can be seen in this comment: https://github.com/kubernetes/ingress-nginx/issues/3109#issuecomment-422802472

But there's a somewhat more pragmatic discussion for Træfik: https://github.com/containous/traefik/pull/1723

However, I think it would make a lot of sense to have a common syntax for different ingress controllers. The `ingress.kubernetes.io/rewrite-target` annotation seems to work well in many cases, but a controller-specific prefix may be needed. The documentation should reflect this, or a design decision may be needed (well out of scope for this bug report).

Here is the documentation for Træfik: https://docs.traefik.io/configuration/backends/kubernetes/#general-annotations
And for nginx: https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md
