### ISSUE TITLE
Error: lstat /var/log/apps:no such file or directory

### ISSUE THREAD

**Issue by kumarsanu1993** [kubernetes/website#10277]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by kumarsanu1993** [comment]
Hi 
Today i have upgraded my cluster  following worker node to latest version 1.10.7. After the upgrade i have observed that my Analytics pod is giving **"CreateContainerConfigError"** and then i checked for the logs of Analytics pod and got error  
"Error: lstat /var/log/apps:no such file or directory" . 

Please suggest the solution to fix this error ASAP.

**Comment by shubheksha** [comment]
@kumarsanu1993, this doesn't look like an issue related to docs. Please consider asking in the appropriate support channels like Stackoverflow/slack.
/close
