### ISSUE TITLE
Dead Link on kubectl docs

### ISSUE THREAD

**Issue by kwiesmueller** [kubernetes/website#10317]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
There is a dead link in the kubectl docs for `kubectl set`:
https://kubernetes.io/docs/reference/kubectl/kubectl/
-> https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_set.md

**Proposed Solution:**
Remove or fix the link.

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/kubectl/
https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_set.md

**Kubernetes Version:** v1.11

**Comment by kwiesmueller** [comment]
Seems related (more specific) to: https://github.com/kubernetes/website/issues/10131

**Comment by shubheksha** [comment]
/triage duplicate
Ref #10080

**Comment by shubheksha** [comment]
Closing this as a duplicate.
/close
