### ISSUE TITLE
Looping error for CNI 

### ISSUE THREAD

**Issue by jclin829** [kubernetes/website#10323]
I encountered following errors. It is going in infinite loop and I found no practical way to fix this.

**Problem:**

Sep 17 18:11:02 master kubelet: W0917 18:11:02.157872     721 cni.go:126] Error loading CNI config file /etc/cni/net.d/10-flannel.conf: error parsing configuration: unexpected end of JSON input
Sep 17 18:11:02 master kubelet: W0917 18:11:02.157890     721 cni.go:172] Unable to update cni config: No valid networks found in /etc/cni/net.d
Sep 17 18:11:02 master kubelet: E0917 18:11:02.158006     721 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Sep 17 18:11:07 master kubelet: W0917 18:11:07.159896     721 cni.go:126] Error loading CNI config file /etc/cni/net.d/10-flannel.conf: error parsing configuration: unexpected end of JSON input

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@premkumar403, not sure if this is a docs issue. Have you tried asking in any of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md)?
