### ISSUE TITLE
 creating token timed out waiting for the condition

### ISSUE THREAD

**Issue by jclin829** [kubernetes/website#10322]
**

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
When I issued

kubeadm token create --print-join-command --ttl=0 -v 4

I got following:

I0917 18:04:29.284414   20721 token.go:225] [token] creating token
timed out waiting for the condition
?
Can anyone explain what and where the condition is and how to free it?

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
this can happen if you don't have a cluster running.
you first have to `kubeadm init ...` your cluster and then you can create a new token.

if you are still experiencing an issue please file an issue in the `kubernetes/kubeadm` repo, but please fill the whole issue template.

thanks.

/close
