### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by premkumar403** [kubernetes/website#10328]
The --record does not work when trying to undo the deployment
kubectl rollout undo deployment/nginx-deployment. I understand that --record helps to know the changes made to the deployment and to see in rollout history. But, Even when we are undo -ing the deployment to the old version is also changing or updating the deployment right ?  why that is not recorded using --record.

**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

--record doesn't work when undo the deployment. 

**Proposed Solution:**
is it possible to use the versioning like git, capturing/tracking all the changes ...?
<img width="1588" alt="screen shot 2018-09-18 at 6 11 06 am" src="https://user-images.githubusercontent.com/23728504/45683586-af99eb80-bb09-11e8-9b29-aeed83b5adb0.png">

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@premkumar403, not sure if this is a docs issue. Have you tried any of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md)?

**Comment by premkumar403** [comment]
@shubheksha, I haven't tried the support channels. Thanks for helping. Will try the support channels.

**Comment by shubheksha** [comment]
No problem! Closing this for the time being, feel free to re-open or file another issue :)
/close
