### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by Trending-Day** [kubernetes/website#10349]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
when i kubeadmin init，the following problems arose。
  This error is likely caused by:
                        - The kubelet is not running
                        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
                        - No internet connection is available so the kubelet cannot pull or find the following control plane images:
                                - k8s.gcr.io/kube-apiserver-amd64:v1.11.0
                                - k8s.gcr.io/kube-controller-manager-amd64:v1.11.0
                                - k8s.gcr.io/kube-scheduler-amd64:v1.11.0
                                - k8s.gcr.io/etcd-amd64:3.2.18
                                - You can check or miligate this in beforehand with "kubeadm config images pull" to make sure the images
                                  are downloaded locally and cached.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

v1.11.0

                                - k8s.gcr.io/etcd-amd64:3.2.18
                                - You can check or miligate this in beforehand with "kubeadm config images pull" to make sure the images
                                  are downloaded locally and cached.

**Comment by shubheksha** [comment]
/triage support
@Trending-Day, this doesn't seem like an issue with the docs. Have you tried asking in any of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures)?

**Comment by neolit123** [comment]
this can be caused by a lot of things and common stage that trips the users.

here is a user that has the same issue:
https://github.com/kubernetes/kubernetes/issues/68671#issuecomment-423194561

have a look at the discussion there.
either your images cannot be pulled or the kubelet has an error.

/close
