### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/

### ISSUE THREAD

**Issue by sammit20** [kubernetes/website#10350]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sammit20** [comment]
We have a kubernetes cluster for the entire organisation. And there are namespaces for individual teams to host their projects in that cluster. The problem seems to be monitoring. Since we have only access to our namespace we can't setup any monitoring for the PODs, containers, or the nodes on which our pods are residing. Is there any way to accomplish monitoring of only the namespace without bothering the kubernetes cluster.

**Comment by shubheksha** [comment]
/triage support
@sammit20, this doesn't seem like a docs issue. Have you tried asking in any of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures)?

**Comment by sammit20** [comment]
Sorry about that, just went in the wrong window. Will close this one.
