### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/coarse-parallel-processing-work-queue/

### ISSUE THREAD

**Issue by setjet** [kubernetes/website#10367]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Following the steps in this example does not seem to work. I suspect the guide is out of date. 
In particular, running a test message through RabbitMQ breaks. Please see below the terminal when attempting to run a test message:

root@temp-78748cf9df-k6h9k:/# nslookup rabbitmq-service
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	rabbitmq-service.default.svc.cluster.local
Address: 10.96.101.198

root@temp-78748cf9df-k6h9k:/# env | grep RABBIT | grep HOST
RABBITMQ_SERVICE_SERVICE_HOST=10.96.101.198
root@temp-78748cf9df-k6h9k:/# export BROKER_URL=amqp://guest:guest@rabbitmq-service:5672
root@temp-78748cf9df-k6h9k:/# /usr/bin/amqp-declare-queue --url=$BROKER_URL -q foo -d
opening socket to rabbitmq-service:5672
root@temp-78748cf9df-k6h9k:/# /usr/bin/amqp-publish --url=$BROKER_URL -r foo -p -b Hello
opening socket to rabbitmq-service:5672
root@temp-78748cf9df-k6h9k:/# /usr/bin/amqp-consume --url=$BROKER_URL -q foo -c 1 cat && echo
logging in to AMQP server: a socket error occurred
 

**Proposed Solution:**
Update the example

**Page to Update:**
https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/

**Comment by srinivasrk** [comment]
Do you know how to fix this issue ?

**Comment by setjet** [comment]
Yes I figured it out: you have to use a newer version of ubuntu. The guide uses 14.04, when I updated it to 18.04 it worked :)
