### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by tolidano** [kubernetes/website#10362]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I cannot find the dockerfile or source code to the node.js application at the github link provided

**Proposed Solution:**
correct the github link

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by daminisatya** [comment]
This is fixed already. 

/close
