### ISSUE TITLE
Error in minikube  documentation

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [kubernetes/website#10369]
**This is a...** 

- [x] Bug Report

**Problem:**
`minikube start --vm-driver hyperkit` produces following error -  **Error starting host: Error creating new host: Driver "hyperkit" not found. Do you have the plugin binary "docker-machine-driver-hyperkit" accessible in your PATH?.**

**Proposed Solution:**
Before starting minikube, docker-machine-driver-hyperkit needs to be installed in path. 
```
curl -Lo docker-machine-driver-hyperkit https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \
&& chmod +x docker-machine-driver-hyperkit \
&& sudo cp docker-machine-driver-hyperkit /usr/local/bin/ \
&& rm docker-machine-driver-hyperkit \
&& sudo chown root:wheel /usr/local/bin/docker-machine-driver-hyperkit \
&& sudo chmod u+s /usr/local/bin/docker-machine-driver-hyperkit
```
**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

1.10.3

**Comment by kevinsimper** [comment]
Hi @roychowdhuryrohit-dev 

I don't see the page using hyperkit, I think it belongs on the minikube hyperkit documentation 😄 Glad you got it solved!

I think it can be closed

/close
