### ISSUE TITLE
 NetworkPlugin cni failed to set up pod "podname_default" network: open /run/flannel/subnet.env: no such file or directory

### ISSUE THREAD

**Issue by jclin829** [kubernetes/website#10377]
**Problem:**

After deploying docker image to the pod. I got:

  Warning  FailedCreatePodSandBox  1d                 kubelet, node2     Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "99e30671c80ab8fe5cedd54fb4edd2ce99ebc45ed120e912d2c7e51f2cab350a" network for pod "node1-6777d4468-d6tvq": NetworkPlugin cni failed to set up pod "node1-6777d4468-d6tvq_default" network: open /run/flannel/subnet.env: no such file or directory

I found solution on internet:

kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

First line provides 404 and second said it is already applied.

Any solution?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
This is not a documentation issue. Please try stackoverflow or kubernetes users slack channel. You can even check with the flannel repo and developers.
