### ISSUE TITLE
Issue with in k8s.io/docs/concepts/cluster-administration/cloud-providers/ -- openstack section

### ISSUE THREAD

**Issue by yyhiro** [kubernetes/website#10389]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

In configuring k8s v1.11 for the OpenStack with kubenet network plugin, when using `[Router]` section of the cloud provider config file, then an error occurs in kubelet such as:

`can't store data at section "Router"`.

**Proposed Solution:**

This problem can be resolved by using follow:

```
[Route]
router-id=<router-id>
```

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

**Comment by Hartmarken348** [comment]
11389
