### ISSUE TITLE
new post proposal "Upgrading a existing single master cluster created with kubeadm to a HA master smoothly"

### ISSUE THREAD

**Issue by lentil1016** [kubernetes/website#10384]
**This is a Feature propose** 

- [x] Feature Request
- [ ] Bug Report

**Problem:** I'm intend to contribute a guide that helping "Upgrading a existing single master cluster created with kubeadm to a HA master smoothly", but I'm not sure where should I put it to. Also the post name I should use in URL.

**Proposed Solution:** My best guess is  `content/en/docs/setup/independent/into-high-availability.md` and `https://kubernetes.io/docs/setup/independent/into-high-availability/`, is that cool?

**Page to Update:**
https://kubernetes.io/docs/setup/independent/into-high-availability/

For those who put a single master kubernetes cluster created with kubeadm into used, they might not likely to recreate their cluster. this post will help them to make their single master HA without recreate it. They will only need to:

- delete old `KubeConfig` `manifest/etcd` `pki/etcd-server` `pki/etcd-peer` `pki/apiserver`
- recreate them using `kubeadm alpha phase` command with HA configure
- restart `apiserver`/`controller`/`scheduler`/`etcd` containers
- change old ETCD master's PeerUrl from https://127.0.0.1:2380 to https://{CP0_IP}:2380

then this single master will be able to joined by other master, and upgrade to a HA master

**Comment by neolit123** [comment]
@Lentil1016 
thanks for the proposed idea.
my initial feedback here would be that this is probably not necessary given we have the other guide, but i would leave it to others to comment further and make the decision!

/cc @kubernetes/sig-cluster-lifecycle 
/assign @chuckha @liztio

**Comment by Lentil1016** [comment]
@neolit123 
♥ Thanks for feedback.
Actually, the procedures of "upgrading old cluster" is only a little different from "creating a new one". So I'm also thinking insert it into this post [Creating Highly Available Clusters with kubeadm](https://kubernetes.io/docs/setup/independent/high-availability/). But I'm not sure if that will make this post not easy to be searched by the user, for it meets two needs.

Expecting for further feedback.
