### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by badalk** [kubernetes/website#10398]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Is it possible to pictorially show how the communication is established from Node -> Service -> Pod -> Container? and what is usually does not need to be configured.
In addition, clear definitions of containerPort, Port, targetPort, nodePort would be greatly appreciated.
I had big issues getting my service working when the dockerfile had exposed port something of sort EXPOSE 3000 80 and it was not clear from the documentation how do I set this up to access my service from within and outside the cluster.

**Proposed Solution:**
Update the documentation

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by badalk** [comment]
> /remove-lifecycle stale

**Comment by Hartmarken348** [comment]
10398
