### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/garbage-collection/

### ISSUE THREAD

**Issue by mjlangan** [kubernetes/website#10391]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation states:
```
In Kubernetes 1.9, for all kinds in the apps/v1 group version, dependent objects are deleted by default.
```
In practice, on a GKE cluster running Kubernetes 1.10, I've found that the dependent objects are _not_ deleted unless I specify "PropagationPolicy: Background". When I delete Jobs on our cluster without setting the policy, the Job gets removed but its associated Pod remains running. Setting the policy results in the Pod being removed as well.

**Proposed Solution:**
Assuming the behavior I'm seeing is the intended behavior of K8S 1.10, update the documentation to say that `PropagationPolicy: Background` is still required if the caller wishes to remove the dependents as well.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

**Comment by CaoShuFeng** [comment]
> When I delete Jobs on our cluster without setting the policy, the Job gets removed but its associated Pod remains running

Job is not in apps/v1 group version.
Job is in batch/v1 group version

**Comment by Hartmarken348** [comment]
10310
