### ISSUE TITLE
/docs/home taking too long to load (due to use.fontawesome.com asset)

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#10394]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/home/ is taking 30-90 seconds to load (show anything meaningful on my browser). Something's clearly wrong.

Static assets like images are for some reason delaying the load by at least 20 seconds. 

Here's a waterfall chart:

![image](https://user-images.githubusercontent.com/159209/46115746-39eaeb00-c1ad-11e8-9ef7-d58feb9c52e9.png)

It seems like it's caused by timeout on a static asset from use.fontawesome.com:

![image](https://user-images.githubusercontent.com/159209/46115760-58e97d00-c1ad-11e8-8866-9130fbec2a11.png)

I've been able to repro this on multiple machines.

**Comment by ahmetb** [comment]
Doesn’t repro anymore. 

Can we load this .js async please?

**Comment by pmallory** [comment]
I did a bit of investigation, here's my notes:

* Many of our markdown files refer to this .js file in their front matter, here's [a random example](https://raw.githubusercontent.com/kubernetes/website/1b5ff98a4473be60d94d35e330d9801640d6f58d/content/en/docs/home/_index.md).
* [This template (line 41)](https://github.com/kubernetes/website/blob/4a8f9e8fd5dcdad3a08d8c1c0e21d5262f62675e/layouts/partials/head.html#L41), creates a \<script\> tag in the page's \<head\> tag.

We could add `async=true` to the head.html template. I'm not sure how that would affect other .js files we're including though. I'll defer to someone who's more familiar with our page templates.

**Comment by Hartmarken348** [comment]
11394
