### ISSUE TITLE
/docs/user-guide/configmap need more details on ConfigMap updates

### ISSUE THREAD

**Issue by Dnefedkin** [kubernetes/website#1040]
ConfigMap design doc (https://github.com/kubernetes/kubernetes/blob/master/docs/design/configmap.md) has a section "Consuming ConfigMap Updates" that describes if pods see changed ConfigMap values depending on how ConfigMap is consumed (via volume plugin or via environment variable).  
I believe such information is valuable in the ConfigMap user guide as well.

**Comment by jaredbhatti** [comment]
Agreed.  It's pretty easy to add this section in.  Jeff, any advice?

Also, this document needs a top to bottom rewrite to conform to our templates.

**Comment by jeffmendoza** [comment]
No advice, looks like a useful addition.

**Comment by DanyC97** [comment]
/language en

@tengqm is this something you planning on working on ?

**Comment by sftim** [comment]
Also see #1817

**Comment by sftim** [comment]
/priority backlog
#16085 should have an nice high priority though

**Comment by sftim** [comment]
Also see #1911

**Comment by sftim** [comment]
In my opinion: fixed in #21452
/close
