### ISSUE TITLE
Broken link (Refer to the CRI installation instructions for more information)

### ISSUE THREAD

**Issue by ocofaigh** [kubernetes/website#10415]
Link is broken on this page: https://kubernetes.io/docs/setup/independent/install-kubeadm/

for the text: `Refer to the CRI installation instructions for more information`

Brings you to: https://kubernetes.io/docs/setup/cri.md (404 not found)

**Comment by ocofaigh** [comment]
It should link to this page I guess? https://kubernetes.io/docs/setup/cri/

**Comment by shubheksha** [comment]
Fixed in #10435 
/close
