### ISSUE TITLE
Add a Section for sig sub-projects

### ISSUE THREAD

**Issue by ant31** [kubernetes/website#10420]
- [x] Feature Request
- [ ] Bug Report

**Problem:**
Each Sig sponsored project should provide documentation but has nothing to help them publish it.
It would be nice to be able to integrate the individual sub-project (the ones sponsored by a sig only) doc in k8s.io.

As a side effect, it could help the community to discover what the sigs are working on and projects they sponsor, and some details about the Sig (description / meetings / goals). It would be more friendly and engaging than a link to https://github.com/kubernetes/community/blob/master/sig-list.md

**Proposed Solution:**
I would add a Tab 'Sub-Projects' :
```Concepts - Tasks - Tutorials - Sub-Projects```
Then organize the page by sig or theme:

``` 
- sig-apps (Apps)
|--> Application CRD
|--> Kompose
|--> Kustomize 

- sig-cluster-lifecycle (Kubernetes Installers)
|--> Kops
|--> Kubeadm
|--> Kubespray
|--> ...

- sig-instrumentation (Monitoring)
|--> kube-state-metric
|--> Prometheus-operator
|--> ...```
```

**Comment by tengqm** [comment]
Not a big fan of this proposal. As a user, I don't care and I should not care how SIGs are organized. IMHO, we should never request the users to understand how the development is organized (projects, communities, SIGs, ...).

**Comment by ant31** [comment]
It's not about how sig development is organized, but the projects' documentation. This why I proposed to group projects by topic instead of sig: 
 Monitoring, Installers, Application Managers....

**Comment by justinsb** [comment]
I like the idea of a list of all projects, with jumping off points to their documentation.  I think we could probably build it from https://github.com/kubernetes/community/blob/master/sigs.yaml - currently that builds per-sig pages, e.g. https://github.com/kubernetes/community/tree/master/sig-aws, and those do have the subprojects.

I think @tengqm is right that it doesn't make sense to group by sigs per se, but I think you're right @ant31 that we're using it as a proxy for categorization.

I say if you want to try it, it sounds worthwhile.  Then we can see if sigs don't map to areas that well - which itself is a good discussion topic!
