### ISSUE TITLE
Expired release note in master branch

### ISSUE THREAD

**Issue by warmchang** [kubernetes/website#10432]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The release note include expired version info (v1.12.0-rc.2) in main & release-1.12 branches.

![image](https://user-images.githubusercontent.com/13084624/46243960-e6c2a380-c40b-11e8-8e41-75ba550a386a.png)

**Proposed Solution:**
Upgrade to the laster CHANGELOG-1.12.md from the [kubernetes repo](https://github.com/kubernetes/kubernetes/tree/release-1.12).

**Comment by jimangel** [comment]
We are looking into this, obviously the quick fix is a manual merge but we're exploring ways to automate the fix for future releases.

**Comment by Hartmarken348** [comment]
Expired

**Comment by DanyC97** [comment]
@jimangel i suspect is safe to close this issue, is that correct?

**Comment by warmchang** [comment]
It's been repaired, thanks.
/close
