### ISSUE TITLE
Refactor Setup into Getting Started

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#10468]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

## Problem

The organization of content in [Setup](https://kubernetes.io/docs/setup/) doesn't make sense, and currently forms a hodgepodge of vendor-specific walkthroughs. These walkthroughs are often outdated and needlessly duplicated on kubernetes.io. 

## Proposed Solution

- [ ] Rename the section from Setup to Getting Started
- [ ] Refactor content to form a sequential, sensible journey through how to get started with Kubernetes, rather than vendor-specific configuration information.
- [ ] Rename section headings to focus on tasks specific to getting started

## Page to update

 https://kubernetes.io/docs/setup/

**Comment by Hartmarken348** [comment]
10468
