### ISSUE TITLE
Layout broken on Case Study detail

### ISSUE THREAD

**Issue by tnir** [kubernetes/website#10462]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

Layout is broken on Case Study detail.

**Proposed Solution:**

Fix CSS.

**Page to Update:**
(e.g.) https://kubernetes.io/case-studies/openai/ (vs https://v1-11.docs.kubernetes.io/case-studies/openai/ )

**All Pages to Update:**

- https://kubernetes.io/case-studies/adform/
- https://kubernetes.io/case-studies/capital-one/
- https://kubernetes.io/case-studies/ibm/
- https://kubernetes.io/case-studies/ing/
- https://kubernetes.io/case-studies/naic/
- https://kubernetes.io/case-studies/newyorktimes/
- https://kubernetes.io/case-studies/nordstrom/
- https://kubernetes.io/case-studies/northwestern-mutual/
- https://kubernetes.io/case-studies/ocado/
- https://kubernetes.io/case-studies/openAI/
- https://kubernetes.io/case-studies/pearson/
- https://kubernetes.io/case-studies/pinterest/
- https://kubernetes.io/case-studies/slingtv/
- https://kubernetes.io/case-studies/squarespace/
- https://kubernetes.io/case-studies/workiva/
- https://kubernetes.io/case-studies/ygrene/

**Comment by tnir** [comment]
## v1.12 (broken)
![case-study-openai-v1-12](https://user-images.githubusercontent.com/10229505/46363406-e34e4700-c6ad-11e8-9299-0eceec7b5229.png)
## v1.11 (not broken yet)
![case-study-openai-v1-11](https://user-images.githubusercontent.com/10229505/46363407-e34e4700-c6ad-11e8-8ac2-e65d5e58e234.png)

**Comment by tnir** [comment]
Seems CSS was not actually migrated to SASS in #10373. The relevant CSS was initially introduced in #8215.

**Comment by lucperkins** [comment]
@tnir I see the issue. i can take care of it.
