### ISSUE TITLE
Apply style guide and editorial consistency for top 20 site pages

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#10469]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

## Problem

The most-visited pages on the site have content of inconsistent quality and varying levels of adherence to the [K8s style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

## Proposed solution

- [ ] Using Google Analytics, determine which pages receive the most page views per month. 

   For example: 
   <img width="975" alt="screen shot 2018-10-02 at 4 42 35 pm" src="https://user-images.githubusercontent.com/3210446/46382891-369aa800-c662-11e8-9ea8-d73ad512a23e.png">

- [ ] Apply the Kubernetes style guide and review each page for editorial quality.

**Comment by Hartmarken348** [comment]
10469
