### ISSUE TITLE
Edit This Page button redundant/links to incorrect URL

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [kubernetes/website#10477]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The `Edit This Page` button on the bottom of pages point to `/docs/editdocs` rather than `/editdocs` (which redirects to `/docs/contribute/`) See https://github.com/kubernetes/website/blob/master/layouts/docs/baseof.html#L40

There already exists an edit button which makes this potentially redundant.

**Proposed Solution:**
1) Link to `/docs/contribute/` to remove unnecessary redirect and possibly logic to use `/docs/contribute/localization/` where appropriate.

2) Link directly to Github editing page

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
> There already exists an edit button which makes this potentially redundant.

What do you mean by the existing edit button. Do you mean the Edit button when you are browsing the raw docs from github.com like [this page](https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/cluster-administration/networking.md)?

The intent of providing the Edit This Page button is not for readers who are browsing the raw pages. They are there for users who are browsing the docs as pre-processed HTML pages.
