### ISSUE TITLE
Layout broken on several Case Study pages (with customized layout)

### ISSUE THREAD

**Issue by tnir** [kubernetes/website#10486]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

There are several case studies with custom (not general) CSS.

The full list of such case studies are following:

- https://kubernetes.io/case-studies/amadeus/
- https://kubernetes.io/case-studies/ancestry/
- https://kubernetes.io/case-studies/blablacar/
- https://kubernetes.io/case-studies/blackrock/
- https://kubernetes.io/case-studies/buffer/
- https://kubernetes.io/case-studies/golfnow/
- https://kubernetes.io/case-studies/peardeck/
- https://kubernetes.io/case-studies/wink/

/cc @kbhawkey 

**Proposed Solution:**

Fix customized CSS.

**Page to Update:**

The list are shown as above.

cf. #10462 (PR: #10463)

**Comment by kbhawkey** [comment]
@tnir, do you plan on fixing the shared page layout problems, such as the footer->nav->a,  in the sass files?

**Comment by tnir** [comment]
@kbhawkey No, at least during addressing this issue. Why did you ask me that in this issue?

**Comment by kbhawkey** [comment]
@tnir, I asked because I am wondering if this issue covered the general cases of fixing the paragraph formatting (to look like 1.11), as well as fixing the footer for all the case-study pages. I will look at your PRs instead.

**Comment by tnir** [comment]
@kbhawkey With #10531 merged, the footer at generic and specific case study pages will be fixed. Thanks for reviewing my PR (#10531).
