### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/feature-gates/

### ISSUE THREAD

**Issue by kmkramer** [kubernetes/website#10493]
**This is a...** 

- [X] Feature Request

**Problem:**
add column to show which components a feature-gate is related to and/or needs to be set on

**Proposed Solution:**
add column showing relationships

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by tengqm** [comment]
ref: https://github.com/kubernetes/website/pull/6364#issuecomment-358805912
