### ISSUE TITLE
Problem with https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/ after Hugo conversion

### ISSUE THREAD

**Issue by mistyhacks** [kubernetes/website#10502]
1. Most of the page content is truncated, as you can see when you view the source. I couldn't immediately figure out what's wrong, but I suspect it's with the Hugo short tags.

2. The button at the bottom of the page to create a new issue results in a 404 instead of actually going to the Github issue-creation screen. Maybe also related to the first point.

Setting this to P1 because most of the topic isn't readable.

/assign @zparnold

**Comment by zparnold** [comment]
@mistyhacks It seems to work for me? Could it be a temporary CDN issue? Both the topic renders and the button opens up a new GH issue properly.

**Comment by mistyhacks** [comment]
Weird, it works for me again. I must have caught Netlify mid-deploy.
