### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/kubelet-integration/

### ISSUE THREAD

**Issue by sujithbhaskaran** [kubernetes/website#10528]
Need update on Documentation
Doc says to use kubeadm config print-default --api-objects KubeletConfiguration to find default kubelet config. But 
 kubeadm config print-default --api-objects KubeletConfiguration
--api-object needs to be one of [MasterConfiguration NodeConfiguration]
it seems like an invalid option

**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

Doc says to use kubeadm config print-default --api-objects KubeletConfiguration to find default kubelet config. But 
 kubeadm config print-default --api-objects KubeletConfiguration
--api-object needs to be one of [MasterConfiguration NodeConfiguration]
it seems like an invalid option

**Proposed Solution:**
Update doc

**Page to Update:**
https://kubernetes.io/docs/setup/independent/kubelet-integration/

**Comment by neolit123** [comment]
what version of kubeadm are you running?
KubeletConfiguration is a valid object in 1.12.

/priority needs-more-evidence
