### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/cluster-management/

### ISSUE THREAD

**Issue by surajssd** [kubernetes/website#10520]
**This is a...** 

- [x] Bug Report

**Problem:**

The last line in the document which says

> For more options, please refer to the usage of kubectl convert command.

The link to `kubectl convert` is dead. Right now it points to 
https://kubernetes.io/docs/user-guide/kubectl/%7B%7Bpage.version%7D%7D/#convert

**Proposed Solution:**

Point to right place.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/

On docs of k8s `v1.12`.

**Comment by warmchang** [comment]
/kind bug

Wrong hyperlink.
"https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_convert.md" should be "https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#convert".

And all the kubectl subcommands have the same issue.

**Comment by warmchang** [comment]
/assign @warmchang 

I'll fix this.

**Comment by warmchang** [comment]
Fixed by https://github.com/kubernetes/website/pull/10554
/close
