### ISSUE TITLE
this version of kubeadm only supports deploying clusters with the control plane version >= 1.11.0. Current version: v1.10.0

### ISSUE THREAD

**Issue by scarllin** [kubernetes/website#10551]
**This is a...** 

- [*] Feature Request
- [ ] Bug Report

**Problem:**
i can't deploy the cluster with this version.

**Proposed Solution:**
just help me!

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
Please consider file an issue in the kubernetes/kubeadm repo.
