### ISSUE TITLE
Issue with k8s.io/docs/home/supported-doc-versions/

### ISSUE THREAD

**Issue by vadimAnte** [kubernetes/website#10577]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I could not either browse or download Documentation 1.10 version.

**Proposed Solution:**
Please provide link to Documentation 1.10 version

**Page to Update:**
https://kubernetes.io/docs/home/supported-doc-versions/#previous-versions

Kubernetes Version: 1.10

**Comment by tengqm** [comment]
I cannot reproduce the issue. Could you please paste the errors you got?

**Comment by vadimAnte** [comment]
Hi,

Please open any recent document -> select 1.10 version on right top corner.
Could you see either documentation or documentation TOC without scrolling?

Best regards,
Vadim Zenin
vadim.z@antetechnologies.com

**Comment by tengqm** [comment]
@vadimAnte Yes. I can see the doc.

1) click the dropdown menu from k8s.io/docs and select 1.10;
2) click the 'documentation' button in the navigation bar.

Everything looks fine to me.

**Comment by vadimAnte** [comment]
Hello,

1. Please open
https://www.postgresql.org/docs/current/static/sql-createindex.html
2. Click on 9.4 on top left corner. Confirm that you on the same topic(!)
on documentation version 9.4 .
3. Click on 9.2 on top right corner. Confirm that you on the same topic(!)
on documentation version 9.2 .
4. Click on current or 10 on top. Confirm that you on the same topic(!) on
documentation version 10 .
5. Create feature request to provide documentation versions in good way.

P.S. I am working on AWSElastic Container Service for Kubernetes (Amazon
EKS)  and have no idea how to find the same topic in previos documentation
version.

Best regards,
Vadim Zenin
