### ISSUE TITLE
Link to developer documentation broken

### ISSUE THREAD

**Issue by Monkeyanator** [kubernetes/website#10578]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**

[Link to developer guide on this page](https://kubernetes.io/docs/home/?path=contributors&persona=code-contributor&level=foundational) broken. 

**Proposed Solution:**

Update link to point to existent documentation.

**Page to Update:**
https://kubernetes.io/docs/community/devel/

**Comment by shubheksha** [comment]
I'll fix this!
