### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/ return of "kubectl rollout history" is not right for k8s v1.11.3

### ISSUE THREAD

**Issue by KevinTHU** [kubernetes/website#10582]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In the page.
```
$ kubectl rollout history deployment/nginx-deployment
deployments "nginx-deployment"
REVISION    CHANGE-CAUSE
1           kubectl create --filename=https://k8s.io/examples/controllers/nginx-deployment.yaml --record=true
2           kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1 --record=true
3           kubectl set image deployment/nginx-deployment nginx=nginx:1.91 --record=true
```
the **3** part is not right, in real return, the 3 part is also `kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1 --record=true`, I think it is a kind of bug for k8s v1.11.3 if the doc is right. The k8s v1.11.3 doesn't record the last wrong command for kubernetes.io/change-cause annotations.

**Proposed Solution:**
need to fix k8s v1.11.3 code I think.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#checking-rollout-history-of-a-deployment

v1.11.3

**Comment by charrywanganthony** [comment]
It seems fixed in latest version.
