### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/  Rolling Back a Deployment not right for k8s v1.11.3

### ISSUE THREAD

**Issue by KevinTHU** [kubernetes/website#10581]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
in **"Rolling Back a Deployment"** section, the number of new failed replicas has been to 1 but not 2 for k8s v1.11.3, I think the issue which **"note"** mentioned has been amended, the default maxUnavailable has been to 25%, not 1, so the new failed replicas not 2 but 1 as well.

**Proposed Solution:**
I think we need to fix the doc place between `$ kubectl rollout status deployments nginx-deployment` and `To fix this, you need to rollback to a previous revision of Deployment that is stable.`
also:
```
The Deployment is now rolled back to a previous stable revision. As you can see, a DeploymentRollback event for rolling back to revision 2 is generated from Deployment controller........
```
need to fix for rollback return.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment

v.1.11.3

**Comment by charrywanganthony** [comment]
:+1:  I will fix this.
