### ISSUE TITLE
Getting started with k/website for Korean l10n work

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#10602]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Getting started with k/website for Korean l10n work 

**Proposed Solution:**
- [x] Add i18n/ko.toml - In progress by #10611 

After master including #10485 is merged to dev-1.13 branch
- [x] Open a PR to create `dev-1.13-ko.1` branch forked from `dev-1.13` and create an Issue if there's any out-dated files in the `content/ko` directory.

**Comment by zacharysarah** [comment]
@gochist 👋 @ClaudiaJKang left some feedback about `README-**.md` in https://github.com/kubernetes/website/pull/10485/#discussion_r224713797. Maybe leave that piece for last until we can finalize what we're doing with READMEs? 😅

**Comment by gochist** [comment]
I recently noticed that the next long running branch is not `release-1.13` but it is `dev-1.13`. So I updated the proposed solution. @zacharysarah :wave: Do I understand the intention of [updated l10n guide](https://kubernetes.io/docs/contribute/localization/) correctly?

**Comment by zacharysarah** [comment]
@gochist 👋 

> Do I understand the intention of updated l10n guide correctly?
...
> Open a PR to create dev-1.13-ko.1 branch forked from dev-1.13 

Yes, that looks correct. 👍
