### ISSUE TITLE
Link more clearly to localized READMEs

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#10622]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

## Problem

We can make it easier for localization teams to find `README-**.md` files (where `**` is a [two-letter language code](https://www.loc.gov/standards/iso639-2/php/code_list.php)) by linking to them from the main README and/or from the localization guidelines.

Continuing https://github.com/kubernetes/website/pull/10485#discussion_r224713797 as a separate issue:

@ClaudiaJKang 👋

> I'm sorry but I think you've miss understood my fourth review.

I apologize! 🙇 To make sure I understand, here are the specific actions I see proposed in your feedback. Are these correct? 👇 

## Proposed Solution

1. Update `/content/en/docs/contribute/localization.md` to include links to various `README-**.md` files.

> Another idea to suggest is adding README-**.md example url in localization.md after this PR.
> If so, localization team would be easier to create README-**.md configuration.

2. Add a link to various `README-**.md` files from the main English `README.md` file.

> After you create the localized README, add a link to the file from the main English file, [README.md] 

3. Require `README-**.md` files to include contact information in English.

> and include contact information in English.

@ClaudiaJKang Do I understand your proposal correctly? ☝️

If so, then:

> So, how about adding README-**.md link in README.md like above?

A. I think updating the main README.md is an excellent idea. 👍 

B. I'm ambivalent about adding `README-**.md` links to `localization.md`. 😐  

Ideally contributors with a `README-**` available in their language would be reading `localization.md` in that language as well, in which case the links would be circular. That's not inherently bad; I'm just not convinced that it's good. 

### Page to Update:

- https://github.com/kubernetes/website/blob/master/README.md
- https://github.com/kubernetes/website/blob/master/content/en/docs/contribute/localization.md

/cc @tnir @idealhack

**Comment by ClaudiaJKang** [comment]
Sorry for not replying sooner.

And I think you've exactly understood my proposal!

> A. I think updating the main README.md is an excellent idea. 👍

In case of A, Thank you for your opinion, I appreciate it!

> B. I'm ambivalent about adding README-**.md links to localization.md. 😐

In case of B, I agree with your opinion. 

But what do you think of adding a link process about the file `README-**.md` in [`localication.md`](https://github.com/kubernetes/website/blob/master/content/en/docs/contribute/localization.md#add-a-localized-readme)? 

For example, it replace [`README.md`] to [`README.md`'s Localizing Kubernetes Documentation] in [`localication.md`](https://github.com/kubernetes/website/blob/master/content/en/docs/contribute/localization.md#add-a-localized-readme).

> After you create the localized README, add a link to the file from the main English file, **[`README.md`'s Localizing Kubernetes Documentation]** and include contact information in English. You can provide a GitHub ID, email address, [Slack channel](https://slack.com/), or other method of contact.

If so, localization team would be easier to add link `README-**.md`!

**Comment by ClaudiaJKang** [comment]
@zacharysarah Thank you! I created #10669 PR about this issue. :smile:
