### ISSUE TITLE
align or add left margin for pre-footer buttons, page last modified info

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#10638]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The `Create an issue button`, `Edit this page buttons`, `Page last modified banner` in the pre-footer for most pages, except the home doc page, could be better aligned on the page and with the page footer.

**Proposed Solution:**
Add margin or align the pre-footer section (two buttons + page modified banner).
Could make the page modified banner text smaller.

**Page to Update:**
Most content pages.
ex: https://kubernetes.io/docs/reference/

**Comment by jamesgeorge007** [comment]
@kbhawkey I would take this up :+1:

**Comment by jamesgeorge007** [comment]
Initial workarounds made out. What do you think?
Old version:-

![Uploading old_kubernetes.png…]()


Now:-

![kubernetes](https://user-images.githubusercontent.com/25279263/47209040-0155c000-d3ad-11e8-8d64-494416cdcffa.png)
