### ISSUE TITLE
missing title on Downloading Kubernetes, browse, docs home page

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#10634]
- [ ] Feature Request
- [x] Bug Report

**Problem:**
There is a missing item title under browse docs->Downloading Kubernetes
Currently the title is:
`01-`

**Proposed Solution:**
Add the link for the 1.12 release notes.

**Page to Update:**
https://kubernetes.io/docs/home/?path=browse

**Comment by charrywanganthony** [comment]
fixed in #11012
