### ISSUE TITLE
Issue when trying to access to the tutorial

### ISSUE THREAD

**Issue by chortels** [kubernetes/website#10648]
Hi, 

When trying to access to the tutorial https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/, the Linux terminal is returning this error: 

`Sorry, we encountered a problem. Support has been alerted.

This is potentially due to a HTTP Proxy blocking Websockets.

Websocket Error - Connection Failed. Reload the page to try again.
`

Yesterday I was able to access to the tutorial with no problems, and my proxy configuration hasn't changed. Could you help me?

Regards.

**Comment by warmchang** [comment]
Maybe cause by your network, I can access the page normally.

**Comment by DanyC97** [comment]
there is no problem with accessing the tutorial docs.

/close
