### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/networking/

### ISSUE THREAD

**Issue by RnRoger** [kubernetes/website#10650]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Duplicated header and sentence on a website page:

> Jaguar
> Jaguar is an open source solution for Kubernetes’s network based on OpenDaylight. Jaguar provides overlay network using vxlan and Jaguar CNIPlugin provides one IP address per pod.

The first occurrence is in the right location, but a duplication has been added at the bottom of the list.

**Proposed Solution:**
Delete second, misplaced header and sentence.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/networking/

Kubernetes Version: 1.12

**Comment by yuexiao-wang** [comment]
Yes, it is a redundant header and sentences for Jaguar.
I submit a PR to fix it.
