### ISSUE TITLE
Issue with k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

### ISSUE THREAD

**Issue by abizake** [kubernetes/website#10652]
How to set the node-name using kubeadm config file

When using custom kubeadm config , using --node-name with kubeadm init throws the following error :- can not mix '--config' with arguments [node-name]

Can we please add the necessary information also here.

**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Can not figure out how to provide node-name in the kubeadm config. 

**Proposed Solution:**
Please add the necessary content to provide node-name in the config.

**Page to Update:**
k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

**Comment by neolit123** [comment]
thanks for the report.

this is outlined in our documentation already:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3

if you want to pass the node name you have to do:
```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  name: "some-node-name"
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
```

if you you have further issues, log an issue in the kubernetes/kubeadm repository.
/close
