### ISSUE TITLE
UI Bug: Nav items in header disappear

### ISSUE THREAD

**Issue by tfogo** [kubernetes/website#10656]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

To reproduce:
- Scroll down so that flip-nav is active (the white nav bar)
- When the viewport is small (but not small enough for the hamburger menu to appear), there isn't enough space for the nav buttons in the header, making them overflow and thus impossible to see.

**Comment by jamesgeorge007** [comment]
Anybody already on this?

**Comment by tnir** [comment]
@tfogo Though I can't fully get your full report, do you mean this is the same bug report with #10685?

**Comment by jamesgeorge007** [comment]
#10688

**Comment by tfogo** [comment]
No, looks like the bug is still there. I'm going to add some screenshots screenshots and look into solutions.

/remove-lifecycle stale
