### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

### ISSUE THREAD

**Issue by erganzi** [kubernetes/website#10655]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

> 3. Create a Service object that exposes the deployment:
`kubectl expose deployment <your-deployment-name> --type=NodePort --name=example-service`

This command shows that the service is of type NodePort, but its contradictory to the following output:

```
   NAME             TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
   example-service  ClusterIP  10.0.0.160   <pending>     8080/TCP   40s
```

1.  The output says type ClusterIP.
2.  For a NodePort service, the external ip should be <none>
3.  For a NodePort service, there should be a NodePort under PORT(S) column.

For example, this is a NodePort service created in our environment:
![image](https://user-images.githubusercontent.com/41982810/47091522-98a8ff00-d257-11e8-9b98-2f5ee0ea983c.png)

**Proposed Solution:**
Fix the document.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

**Comment by charrywanganthony** [comment]
fixed(this file removed) https://github.com/kubernetes/website/issues/11431#issuecomment-443305900
