### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by markmercer** [kubernetes/website#10671]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Passphrase is wrong. This one won’t give you any extra lives.

**Proposed Solution:**
Change to UUDDLRLRBAS

**Page to Update:**
https://kubernetes.io/...

**Comment by warmchang** [comment]
Could you share more details about your env?
