### ISSUE TITLE
Website scales poorly

### ISSUE THREAD

**Issue by Tiedye** [kubernetes/website#10675]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The use of percentage padding and margins causes the website to have unsightly proportions at various scales, becoming much more pronounced at larger scales.  This also makes zooming in and out have an affect on font size only, which is not good.

**Proposed Solution:**
Use absolute units (px) or font relative units (rem, em) with media queries to ensure the site is proportional at all scales.

**Page to Update:**
https://kubernetes.io/docs/*

![image](https://user-images.githubusercontent.com/6187173/47183413-f724ba80-d2f5-11e8-8074-969a28b84186.png)

**Comment by jamesgeorge007** [comment]
Anybody working on this?

**Comment by Tiedye** [comment]
Well it seems nobody cares.
