### ISSUE TITLE
Desktop UI broken by overflow-x: scroll;

### ISSUE THREAD

**Issue by chenopis** [kubernetes/website#10685]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
There is an extra gray bar underneath the secondary nav and search box when using Chrome desktop. I'm seeing this:

<img width="1261" alt="screen shot 2018-10-19 at 3 52 30 pm" src="https://user-images.githubusercontent.com/24798125/47247196-0c155280-d3b7-11e8-9b98-e14df1eb7956.png">

If you compare the two deploy previews:
* https://deploy-preview-10071--kubernetes-io-master-staging.netlify.com/docs/home/?path=users&persona=app-developer&level=foundational
* https://deploy-preview-10072--kubernetes-io-master-staging.netlify.com/docs/home/?path=users&persona=app-developer&level=foundational

It seems to change in PR #10072 .

**Proposed Solution:**

If it turns out to be a desktop vs mobile issue, then target `overflow-x: scroll;` to just mobile devices.

**Page to Update:**
https://kubernetes.io/docs/home/?path=users&persona=app-developer&level=foundational

**Comment by zacharysarah** [comment]
/assign @tnir

https://github.com/kubernetes/website/pull/10072#issuecomment-431521375

**Comment by jamesgeorge007** [comment]
In fact, I would love to take this up :smile:

**Comment by zacharysarah** [comment]
@jamesgeorge007 Go for it! 🚀

**Comment by tnir** [comment]
@chenopis Thanks. With Chrome on Windows, you might see it. With Chrome, Firefox, and Safari on Mac, I don't see any bar there.

**Comment by chenopis** [comment]
> @chenopis Thanks. With Chrome on Windows, you might see it. With Chrome, Firefox, and Safari on Mac, I don't see any bar there.

Just for clarification, I'm using Chrome on a Mac and I do see it.

**Comment by chenopis** [comment]
After the conflicts were resolved in PR #10688, the fix no longer worked in the preview build. Consequently, even though that PR was merged, I still see the problem on the website.

<img width="1328" alt="screen shot 2018-10-24 at 10 05 06 am" src="https://user-images.githubusercontent.com/24798125/47448338-a210fa80-d774-11e8-9ac6-a52676a750bd.png">

**Comment by jamesgeorge007** [comment]
@chenopis The change doesn't seem to have reflected within the website on using chrome developer tool.
How to tackle this issue?

**Comment by jamesgeorge007** [comment]
@chenopis I used node-sass to compile down sass to css which didn't work as intended. I had submitted another PR resolving the issue :+1: 
Sorry for the trouble
