### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/

### ISSUE THREAD

**Issue by elliottb303** [kubernetes/website#10698]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
command appears incorrect, and has messed up quotes that break json parser:

Where is <your pv name>?

docs section:
......
kubectl patch pv -p ‘{“spec”:{“persistentVolumeReclaimPolicy”:“Retain”}}’

where <your-pv-name> is the name of your chosen PersistentVolume.
.....

**Proposed Solution:**

1) fix the command to show where pv name is actually inserted, appears to be right after 'pv'

2) make the command useable by giving it highlight, and replacing `quotation marks with quotes like "hello", 'hi'

**Page to Update:**
https://kubernetes.io/...

**Comment by charrywanganthony** [comment]
fixed in #10727
