### ISSUE TITLE
786d314 accidentally reverted doc updates?

### ISSUE THREAD

**Issue by schu** [kubernetes/website#10691]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

786d314da5351a0f18aebf5f65814dec321ead3f appears to have reverted an update to `content/en/docs/reference/command-line-tools-reference/kube-apiserver.md`. The updated warning for the `--requestheader-client-ca-file` flag from https://github.com/kubernetes/website/pull/10093 was changed back to the previous version.

```
-      <td></td><td style="line-height: 130%; word-wrap: break-word;">Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: do **not** reuse a CA that is used in a different context (for example with --client-ca-file) unless you understand the risks and the mechanisms to protect the CA's usage. Generally it is recommended to not depend on authorization being already done for incoming requests.</td>
+      <td></td><td style="line-height: 130%; word-wrap: break-word;">Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.</td>
```

**Comment by schu** [comment]
cc @jimangel

**Comment by jimangel** [comment]
@schu those files are automagically generated (see: https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/). I will need to do some reverse engineering in https://github.com/kubernetes-incubator/reference-docs to see if we can dig up how this misses "--requestheader-client-ca-file"

Is it possible the docs were generated before the command line flag was merged with master? It might be as simple as regenerating the docs.

**Comment by schu** [comment]
> Is it possible the docs were generated before the command line flag was merged with master? It might be as simple as regenerating the docs.

I would guess no since the [PR](#10093) was merged September 6th and 786d314 is from September 28th (but I'm not familiar with the workflow regarding docs).

**Comment by schu** [comment]
Something still seems to be off:

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ shows the old version from before https://github.com/kubernetes/website/pull/10093

https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/ and
https://kubernetes.io/docs/reference/access-authn-authz/authentication/ show the updated version as done with https://github.com/kubernetes/website/pull/10093

**Comment by schu** [comment]
> https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ shows the old version from before #10093

That's still the case.

**Comment by kbhawkey** [comment]
Hello @schu .
The kube-apiserver docs component page is auto-generated using the
kube-apiserver from the `kubernetes/kubernetes` repository.
If the text for the flag `requestheader-client-ca-file` is not correct, 
would you open a pull request in kubernetes/kubernetes.
Here is a snippet from v1.18, `https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/`

```
<tr>
<td colspan="2">--requestheader-client-ca-file string</td>
</tr>
<tr>
<td></td><td style="line-height: 130%; word-wrap: break-word;">Root certificate bundle to use to verify client certificates on incoming requests before trusting usernames in headers specified by --requestheader-username-headers. WARNING: generally do not depend on authorization being already done for incoming requests.</td>
</tr>
```
I am closing this issue as the text for the flag description should be changed in `kubernetes/kubernetes`.

/close
