### ISSUE TITLE
Translate README.md in Korean

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#10715]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No README.md in Korean

**Proposed Solution:**
Translate README.md in Korean and place it in a proper path.

**Page to Update:**
N/A

**Comment by ianychoi** [comment]
Acknowledged - on `dev-1.13-ko.1` branch

**Comment by ianychoi** [comment]
@gochist I have just made a pull request to `dev-1.13-ko-4` branch. Please review https://github.com/kubernetes/website/pull/11786 . Thanks a lot.

**Comment by gochist** [comment]
@ianychoi 감사합니다! 위치가 `content/ko`가 아니므로 브랜치는 `master`로 수정 부탁드립니다. 번거롭게 해드려 죄송합니다.
