### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by psinghsp** [kubernetes/website#10756]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Online tutorial is not working. It gives an error about being unable to connect to "localhost:8080".

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@psinghsp - could you share more details about your environment?
cc: @BenHall
