### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by jasonchristopher61** [kubernetes/website#10763]
Im getting this issue whenever I use kubectl even if I check for kubectl version

Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

**Comment by shubheksha** [comment]
@jasonchristopher61, this isn't the right place for support requests unfortunately, please try one of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures).
