### ISSUE TITLE
Issue with k8s.io/docs/contribute/start/

### ISSUE THREAD

**Issue by rmrakowski** [kubernetes/website#10784]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The "Sign the CLA" section of this page contains links to [the community guide](https://kubernetes.io/docs/community/guide/) and [sign the CLA](https://kubernetes.io/docs/community/guide/#sign-the-cla), which (as of 10/30/2018) lead to 404 errors.

**Proposed Solution:**
* Remove the link to the community guide, which currently does not exist.
* Rewrite the section to avoid referencing the community guide.
* Update the URL for the CLA to https://identity.linuxfoundation.org/projects/cncf

**Page to Update:**
https://kubernetes.io/docs/contribute/start/

**Comment by zacharysarah** [comment]
@rmrakowski 👋 Welcome to Kubernetes!

From [Slack](https://kubernetes.slack.com/archives/C1J0BPD2M/p1540936916026800?thread_ts=1540933755.024700&cid=C1J0BPD2M):
> `Before you can contribute code or documentation to Kubernetes, you *must* read the Contributor guide and sign the Contributor License Agreement (CLA).` Given how firm the page is about the need to read the community guide, is there any similar page that new contributors need to look at which should replace it?

Yes, it looks like the guide has moved: https://github.com/kubernetes/community/blob/master/contributors/guide/README.md

So has the URL for the CLA: https://identity.linuxfoundation.org/projects/cncf

**Comment by rmrakowski** [comment]
> Yes, it looks like the guide has moved: https://github.com/kubernetes/community/blob/master/contributors/guide/README.md

Okay, thanks. Given that the contributor's guide has a link to the CLA right at the top, should the CLA still be referenced in the start page (especially since the guide uses a different link for the CLA, albeit one that ends up in the same place)?

**Comment by zacharysarah** [comment]
@rmrakowski 

> Or, alternately, should the start page use the same CLA link as the contributor's guide?

👍

**Comment by jaredbhatti** [comment]
Thanks for submitting this issue and the PR to fix it!
