### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by scals44** [kubernetes/website#10780]
- [ ] Feature Request
- [ X] Bug Report

**Problem:**
Installing kubectl via PowerShell gallery fails TLS handshake:

The install-kubectl.ps1 doesn't declare invoke-webrequest to use TLS1.2 and https://kubernetes.io/ doesn't accept TLS1.0 so the process fails. I got around this by editing the script and forcing TLS protocol to 1.2 with the following line. 

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Proposed Solution:**
Adjust the script to use TLS1.2 since the endpoint doesn't accept anything lower. 

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-with-powershell-from-psgallery

**Comment by it-praktyk** [comment]
The script install-kubectl.ps1 was updated to v. 1.7 by @bottkars yesterday. I've tested it, works correctly on W2K8 R2 and PowerShell 3.0.

IMHO, the issue can be closed now.
