### ISSUE TITLE
Is kube-apiserver's "--runtime-config" should be used in webhook mode?

### ISSUE THREAD

**Issue by sunlintong** [kubernetes/website#10803]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I want to open apiserver's webhook mode,and the [website docs](https://kubernetes.io/docs/reference/access-authn-authz/webhook/) says I should set `--runtime-config=authorization.k8s.io/v1beta1=true`.
But when I run `kube-apiserver --help | grep runtime`,It seems that this config will remove in the future:
```console
$ kube-apiserver --help | grep runtime
      --runtime-config mapStringString   A set of key=value pairs that describe runtime configuration that may be passed to apiserver. <group>/<version> (or <version> for the core group) key can be used to turn on/off specific api versions. api/all is special key to control all api versions, be careful setting it false, unless you know what you do. api/legacy is deprecated, we will remove it in the future, so stop using it.
```
So,Should I use this or not?
And which runtime-config is opened default?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/webhook/

v1.12

centos 7.5

**Comment by Pingan2017** [comment]
just `api/legacy ` group will be removed not  `runtime-config`

**Comment by sunlintong** [comment]
> just `api/legacy ` group will be removed not `runtime-config`
（⊙ｏ⊙）哦

**Comment by sunlintong** [comment]
@Pingan2017 （⊙ｏ⊙）哦

**Comment by Pingan2017** [comment]
可以用curl {master ip}:port 来查看哪些api是打开的

**Comment by sunlintong** [comment]
> 可以用curl {master ip}:port 来查看哪些api是打开的

哦哦，谢谢大佬，原来这个玩意儿就是启用或关闭api资源组的
