### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by christennant** [kubernetes/website#10818]
This is a:

- [ ] Feature Request
- [x] Bug Report

**Problem:**
for this page: https://kubernetes.io/docs/setup/independent/high-availability/

as written, the instructions almost work on 12.2.2, with one exception.  I get this error:

didn't recognize types with GroupVersionKind: [kubeadm.k8s.io/v1alpha3, Kind=ClusterConfiguration]

in response to:
kubeadm alpha phase kubelet write-env-file --config kubeadm-config.yaml

And things just got worse from there on.
  
**Proposed Solution:**

The problem is also reported here: https://github.com/kubernetes/kubeadm/issues/1171

But the exact solution wasn't immediately clear to a n00b.

To get the instructions to work, I needed to add an empty InitConfiguration block to the top of the kubeadm-config.yaml on the second and third control plane nodes.  Specifically, I added this:

```
  ---
  apiVersion: kubeadm.k8s.io/v1alpha3
  kind: InitConfiguration
  kubernetesVersion: stable
  
  ---
  (remainder of kubedm-config.yaml from page goes here)
```

Recommendation, update the kubeadm-config.yaml examples on the page to include these empty blocks.

Otherwise, the documentation is terrific - thank you!

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by neolit123** [comment]
hi, let's keep kubernetes/kubeadm#1171
as the tracking issue for this please.

too many issues in different repos are hard to track.
i will add a comment about updating this page.

/close
