### ISSUE TITLE
Translate TopPage in Japanese

### ISSUE THREAD

**Issue by cstoku** [kubernetes/website#10825]
**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No TopPage in Japanese.

**Proposed Solution:**
Translate TopPage in Japanese.
Copy from en content and Update `content/ja/_index.html`.

**Page to Update:**
https://kubernetes.io/ja/

**Comment by tnir** [comment]
@cstoku Thank 🎉 I prefer using `Close #10825` on description of PR #11585 than closing each issue after merged.

**Comment by cstoku** [comment]
Oh sorry, I'll be careful next time! :+1:
