### ISSUE TITLE
Translate home/supported-doc-versions/ in Japanese

### ISSUE THREAD

**Issue by cstoku** [kubernetes/website#10826]
**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No home/supported-doc-versions/ in Japanese.

**Proposed Solution:**
Translate home/supported-doc-versions/ in Japanese.
Copy from en content and Update `content/ja/docs/home/supported-doc-versions.md`.

**Page to Update:**
https://kubernetes.io/ja/home/supported-doc-versions/

**Comment by inductor** [comment]
done

**Comment by inductor** [comment]
https://github.com/kubernetes/website/pull/12068

**Comment by cstoku** [comment]
thanks!
/close
