### ISSUE TITLE
Translate heading and subheading of setup/turnkey/azure/ in Japanese

### ISSUE THREAD

**Issue by cstoku** [kubernetes/website#10854]
**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No heading and subheading of setup/turnkey/azure/ in Japanese.

**Proposed Solution:**
Translate heading and subheading of setup/turnkey/azure/ in Japanese.
Copy from en content and Update `content/ja/docs/setup/turnkey/azure.md`.

**Page to Update:**
https://kubernetes.io/ja/setup/turnkey/azure/

**Comment by inductor** [comment]
@dzeyelid sup

**Comment by dzeyelid** [comment]
@inductor I'm sorry for a long time I can't respond to this. I'll do that this Saturday.
