### ISSUE TITLE
Translate heading and subheading of setup/turnkey/stackpoint/ in Japanese

### ISSUE THREAD

**Issue by cstoku** [kubernetes/website#10857]
**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No heading and subheading of setup/turnkey/stackpoint/ in Japanese.

**Proposed Solution:**
Translate heading and subheading of setup/turnkey/stackpoint/ in Japanese.
Copy from en content and Update `content/ja/docs/setup/turnkey/stackpoint.md`.

**Page to Update:**
https://kubernetes.io/ja/setup/turnkey/stackpoint/

**Comment by auifzysr** [comment]
これやってます
