### ISSUE TITLE
Translate tutorials/kubernetes-basics/ in Japanese

### ISSUE THREAD

**Issue by cstoku** [kubernetes/website#10860]
**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No tutorials/kubernetes-basics/ in Japanese.

**Proposed Solution:**
Translate tutorials/kubernetes-basics/ in Japanese.
Copy from en content and Update `content/ja/docs/tutorials/kubernetes-basics/_index.html`.

**Page to Update:**
https://kubernetes.io/ja/tutorials/kubernetes-basics/

**Comment by hhiroshell** [comment]
これやります。
