### ISSUE TITLE
Translate tutorials/kubernetes-basics/create-cluster/cluster-intro/ in Japanese

### ISSUE THREAD

**Issue by cstoku** [kubernetes/website#10862]
**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No tutorials/kubernetes-basics/create-cluster/cluster-intro/ in Japanese.

**Proposed Solution:**
Translate tutorials/kubernetes-basics/create-cluster/cluster-intro/ in Japanese.
Copy from en content and Update `content/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html`.

**Page to Update:**
https://kubernetes.io/ja/tutorials/kubernetes-basics/create-cluster/cluster-intro/

**Comment by lkougi** [comment]
I'd like to translate this page!
