### ISSUE TITLE
Issue with k8s.io/docs/user-journeys/users/application-developer/foundational/

### ISSUE THREAD

**Issue by hackinteach** [kubernetes/website#10894]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Kubernetes 101 and Kubernetes 201 pages give me 404

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/k8s101/+&cd=3&hl=en&ct=clnk&gl=sg
https://kubernetes.io/docs/tutorials/k8s201/+&cd=1&hl=en&ct=clnk&gl=sg

**Comment by charrywanganthony** [comment]
fixed in #11008
