### ISSUE TITLE
Kubernetes 101, Kubernetes 201 links under Tutorials sections are broken 

### ISSUE THREAD

**Issue by RamYadlapalli** [kubernetes/website#10896]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubernetes 101, Kubernetes 201 links under Tutorials sections are broken and redirects to 404 page.

**Proposed Solution:**
Please fix the links with valid URLs

**Page to Update:**
https://kubernetes.io/docs/user-journeys/users/application-developer/foundational/

**Comment by charrywanganthony** [comment]
fixed in #11008
