### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by SamBroner** [kubernetes/website#10890]
**This is a...** 

- [ ] Feature Request
- [ x ] Bug Report

**Problem:**
`kubectl api-resources --namespaced=true` is not a valid command

**Proposed Solution:**

Identify a working command and replace it.

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T20:49:12Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:11:51Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tengqm** [comment]
The command you are trying is only available after v1.11. You are reading docs for the "current version" (1.12) and you are trying the command on 1.9.

See: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md
