### ISSUE TITLE
Missing left plane buttons on Safari 12.x

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#10922]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
a colleague of mine sent me this recording:
https://www.dropbox.com/s/rnym1t5enqcb9p7/kubernetes-docs.gif?dl=0

**click (download). it's an animated GIF you can drag it in a browser to view.**

seems to me that the elements on the left plane are just blank.

**Proposed Solution:**
fix missing buttons on the left plane.

**Page to Update:**
affects all pages.

the recording tests:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

MacOS
Safari 12.x

works fine for me on Windows / Chrome.

@kubernetes/sig-docs-maintainers

**Comment by zacharysarah** [comment]
@neolit123 👋 The GIF is behind a login. Are you able to save and upload it? 

I'm on MacOS/Chrome and see no problem.

**Comment by neolit123** [comment]
@zacharysarah sorry, updated the link.

https://www.dropbox.com/s/rnym1t5enqcb9p7/kubernetes-docs.gif?dl=0
the animated GIF file has to be downloaded and then dropped in to a browser to view.
