### ISSUE TITLE
kubeadm 1.13 - GA docs tracking issue.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/website#10937]
@kubernetes/sig-cluster-lifecycle  - For updates to docs please cross-ref your PRs against this issue per @tfogo 's request 

/cc @Bradamant3

**Comment by neolit123** [comment]
we need to shuffle the kubeadm reference docs and make some small kubeadm config related changes.
2 PRs might be sufficient for this.

**Comment by neolit123** [comment]
this PR merged yesterday:
https://github.com/kubernetes/website/pull/10959

this PR should update before (docs deadline - 19th nov):
https://github.com/kubernetes/website/pull/10960

i don't think we have anything else.

**Comment by neolit123** [comment]
added small PR with bugfixes related to v1beta1:
https://github.com/kubernetes/website/pull/10988

**Comment by neolit123** [comment]
added k/k update for our example godocs:
https://github.com/kubernetes/kubernetes/pull/71008

**Comment by neolit123** [comment]
1.13 docs are done.
/close
