### ISSUE TITLE
Issue with k8s.io/docs/setup/minikube/

### ISSUE THREAD

**Issue by filippog** [kubernetes/website#10956]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The page mentions `kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080` though when running the command with `kubectl` 1.12.2 a warning is emitted:

```
$ kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
kubectl run --generator=deployment/apps.v1beta1 is DEPRECATED and will be removed in a future version. Use kubectl create instead.
deployment.apps/hello-minikube created
```

**Proposed Solution:**
Update `kubectl` syntax.

**Page to Update:**
https://kubernetes.io/k8s.io/docs/setup/minikube/

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sluetze** [comment]
correct command seems to be:

```shell
cat << EOF | kubectl create -f -
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-minikube
spec:
  template:
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
      - name: hello-minikube
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
EOF
```

Other possibilities:
1. Create deployment.yaml as file and read it with `kubectl create -f deployment.yaml`
2. specify json/yaml in line (not readable)
3. read from stdin (not userfriendly)

if ok i will file a PR

**Comment by DanyC97** [comment]
/remove-lifecycle rotten
/assign @DanyC97 


is related to https://github.com/kubernetes/website/issues/12090
