### ISSUE TITLE
Downloading Kubernetes on docs/setup broken

### ISSUE THREAD

**Issue by bradhoekstra** [kubernetes/website#10968]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The "Downloading Kubernetes" item on the docs/setup page expands but doesn't show any sub-items.
![image](https://user-images.githubusercontent.com/1126869/48361167-ed7d4100-e66e-11e8-8712-961b41b506d9.png)

**Proposed Solution:**
Fix it to add whatever items are supposed to show there.

**Page to Update:**
https://kubernetes.io/docs/setup/

Possibly related to #10634

**Comment by charrywanganthony** [comment]
fixed in #11012

**Comment by bradhoekstra** [comment]
/close

Thanks @charrywanganthony!
