### ISSUE TITLE
Issue with k8s.io/docs/setup/node-conformance/

### ISSUE THREAD

**Issue by dshamanthreddy** [kubernetes/website#10969]
I don't understand how to test it on , Not very clear docs.

**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Node Conformance Test, How to test it. is it using kubectl or kubelet

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by charrywanganthony** [comment]
Use docker to run. https://kubernetes.io/docs/setup/node-conformance/#running-node-conformance-test
