### ISSUE TITLE
container-lifecycle-hooks do not execute on image update

### ISSUE THREAD

**Issue by joshshn** [kubernetes/website#10962]
**This is a...** 

- [ X] Feature Request
- [ ] Bug Report

**Problem:**
Kubernetes 1.12 provides container-lifecycle-hooks: PostStart and PreStop. PreStop hook is called when a container is terminated. However when updating the image of a container via the command 
'kubectl set image pod pod-name pod=imagename:v2' does not invoke the PreStop hook for cleaning up of pod data.

**Proposed Solution:**
PreStop hook execution is performed on image update via kubectl set image command.

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@joshshn, this doesn't seem like an issue with the docs. Would you find [filing a bug](https://github.com/kubernetes/kubernetes/issues/new?template=bug-report.md) in the main repo?
