### ISSUE TITLE
Issue with k8s.io/podsubnet

### ISSUE THREAD

**Issue by weekndchina** [kubernetes/website#10989]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
After "kubeadm init --config kubeadm-config.yaml",with kubeadm, master02 and master03's pod ip goes to docker0 instead of podsubnet.master01 is normal.

k8s version list:
kubelet-1.12.2-0.x86_64
kubernetes-cni-0.6.0-0.x86_64
kubeadm-1.12.2-0.x86_64
kubectl-1.12.2-0.x86_64

cluster images:
kubeadm config images pulled

**Proposed Solution:**
reset coredns,it didn't work

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by DanyC97** [comment]
/remove-lifecycle rotten

@neolit123 any chance you might know the answer and if so let me know if there is anything which needs to be done from docs side ? thanks in advance

**Comment by neolit123** [comment]
>> After "kubeadm init --config kubeadm-config.yaml",with kubeadm, master02 and master03's pod ip goes to docker0 instead of podsubnet.master01 is normal.

> @neolit123 any chance you might know the answer and if so let me know if there is anything which needs to be done from docs side ? thanks in advance

hard to say what may cause that...

possibly related to:
https://github.com/kubernetes/kubeadm/issues/1329

as recommended above the user should try a different CNI plugin - e.g. weave net.

i'm going to have to close this ticket as it's a networking problem and we can't possibly document all networking problems in the troubleshooting guide for kubeadm.

thanks.
/close
