### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/assign-cpu-resource/

### ISSUE THREAD

**Issue by svennela** [kubernetes/website#11019]
**This is a...** 

- [ X] Bug Report

**Problem:**
kubectl top pod memory-demo

**Proposed Solution:**

kubectl top pod cpu-demo 

**Page to Update:**
https://kubernetes.io/...
1.11

**Comment by sluetze** [comment]
Hi svennela,

The v1.11 Doc (https://v1-11.docs.kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/) shows:

> Documentation for Kubernetes v1.11 is no longer actively maintained. The version you are currently viewing is a static snapshot. For up-to-date documentation, see the latest version.

The current v1.12 Doc (https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/) doesnt have the issue?

Has been fixed with PR #9376

**Comment by tengqm** [comment]
@sluetze is correct. Closing.
