### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

### ISSUE THREAD

**Issue by enozero** [kubernetes/website#11018]
I can't, for the life of me, figure out why I would need to set `periodSeconds` on a `readinessProbe`. It seems like it should be an unused field for the readiness side as a one-time only check.

**Comment by lbrictson** [comment]
The `periodSeconds` is the delay between checks, while you can have the readinessProbe pass after just one successful check you can also make it require several, which is where the `periodSeconds` comes into play.

If you want your readiness probe to pass three times before becoming ready then the `periodSeconds` would be the time between each of those checks
