### ISSUE TITLE
[Proposal] Adding a editorconfig

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#11070]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Based on my experience, editorconfig would help to organize the coding style (things like removing the trailing space) across the editors. 

**Proposed Solution:**
By `.editconfig` in the top level directory.
Also, we can have different styles for different file extensions.

**Comment by liggitt** [comment]
does gofmt not handle this already?

**Comment by zhangxiaoyu-zidif** [comment]
@chenrui333 you are doing this?

**Comment by chenrui333** [comment]
yeah, I think I can do it. But I want to get everyone's attention on this first. 😄

**Comment by chenrui333** [comment]
Close via https://github.com/kubernetes/website/pull/11551
