### ISSUE TITLE
Gathering common user pain points

### ISSUE THREAD

**Issue by aronchick** [kubernetes/website#1108]
Great idea by @justinsb - someone (a doc writer) should sit in Kubernetes users for <n> hours. They should try to answer every question _only_ by linking to an external doc, rather than ever typing a question. If there is no doc, they should write the answer (in a wiki?) and link to that.

It'd be a great way to collect what people actually need.

**Comment by MHBauer** [comment]
This is a great way to add to the docs or find new features to go implement. It can require a rather deep understanding of the system. Further, just because the information is written down, does not mean it is discoverable. I see questions all the time; I cannot answer most.

**Comment by justinsb** [comment]
@hubt has started a FAQ here: https://github.com/hubt/kubernetes-faq

We should just contribute to that, or just create a repo and start without worrying about how we eventually will display things?  (Maybe just one file per Q & A, markdown format, and then we make it pretty later)

@hubt how would you feel about contributing some of your content to an "official" k8s repo - presuming we can figure one out?

**Comment by hubt** [comment]
That'd be great. Happy to help contribute. Go ahead copy anything I've done already in my repo and find an appropriate place in the official k8s repo. Then for updates, I'll submit PRs into the official repo.

**Comment by justinsb** [comment]
That is wonderful @hubt - thank you so much!

I will also join the volunteer list to answer questions only through links for a few mornings.  Sign me up :-)

@aronchick shall we create a new repo or just put it into an area of the docs site?  I propose a new repo, and we can always incorporate it into docs later.  I am thinking we just have a single file per Q & A, and then we find a ~victim~ volunteer that can convert it into a pretty looking static(?) site later.  But can you please figure out / delegate where to create the repo @aronchick (or if we should be using this repo)?

**Comment by jaredbhatti** [comment]
I haven't seen any movement on this for 6 months, but I see that an FAQ has already been written.  Is this something that we should port into kubernetes.io?

**Comment by hubt** [comment]
If you want to take what I've already written and put it into kubernetes.io that's fine, or if it needs a cleaner start you can take whatever is appropriate and pull it in.
