### ISSUE TITLE
Issue with k8s.io/docs/editdocs/

### ISSUE THREAD

**Issue by nsvijay04b1** [kubernetes/website#11208]
kubeam upgrade steps is not provided in case of upgrade from 1.9.x to 1.10.x in official site or whatever given in this link is nothing but description of the kubeadm upgrade command but not detailed steps for upgrade.

https://v1-10.docs.kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/

documentation for each other minor upgrade process individually is available , for example all below options available. Thank you for that.

- 1.6 to 1.7 upgrades
- 1.7.x to 1.7.y upgrades
- 1.7 to 1.8 upgrades
- 1.8.x to 1.8.y upgrades
- 1.8.x to 1.9.x upgrades
- 1.9.x to 1.9.y upgrades
- 1.9.x to 1.9.y HA cluster upgrades
- 1.10 to 1.11 upgrades
- 1.11 to 1.12 upgrades

**This is a bug in documentation.** 

**Problem:**
Only 1.9.x to 1.10.x kubeadm upgrade steps is missing or whatever available in below link is generic reference to upgrade command but not detailed steps for upgrade.

**Proposed Solution:**
update documentation with clear steps of kubeadm upgrade from 1.9.x to 1.10.x

**Page to Update:**
https://v1-10.docs.kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/
https://v1-9.docs.kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/#kubeadm-upgrade-guidance

**Comment by DanyC97** [comment]
hi @nsvijay04b1 , thank you for raising the issue. Since v1.10 docs version is no longer maintained and since soon we'll move to 1.14 i'm going to close this issue.

Should you find any problem with the upgrade process from 1.13 -> 1.14 then please open a new issue.
