### ISSUE TITLE
Include a formal definition of "Workloads" in k8s.io/docs/concepts/workloads/

### ISSUE THREAD

**Issue by red8888** [kubernetes/website#11285]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Im considering this a sort of bug. Could we have a more formal definition of what a k8s workload is? Maybe on the Workloads page? The k8s and gcp documentation seems kind of ambiguous here and the gcp console has an actual "Workloads" section, but im not 100% sure all the stuff i will see in that UI pane. "Workloads" arent an actual k8s construct i guess, there is no workloads class or anything but its like a way of categorizing specific k8s objects? This isnt clear from the docs

**Proposed Solution:**
In the workloads page have a paragraph or two that starts with "Kubernetes workloads are...". This will be helpful for new users trying to wrap their head around k8s.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/

**Comment by tengqm** [comment]
Sure, feel free the propose a glossary entry for this page: https://kubernetes.io/docs/reference/glossary/?workload=true
