### ISSUE TITLE
KubeCon Seattle 2018 - quarterly planning & yearly retrospective

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#11331]
Where: [KubeCon/CloudNativeCon Seattle 2018](https://sched.co/GyDy), Seattle, WA USA 
When: Monday, 10 December 2018, 10am-3pm PST

Agenda and notes: https://docs.google.com/document/d/12lgT9usnk2vEKb9Fvnz2stXBZ35xvx8yEPTJDhwicic/edit?usp=sharing

**Comment by DanyC97** [comment]
i think this can be closed ?

**Comment by DanyC97** [comment]
the planning was done, closing it

/close

_reopen it should you think it shouldn't have been closed_

**Comment by DanyC97** [comment]
/reopen

to early to close, wait until next planning coming up and then close it
