### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/logging/

### ISSUE THREAD

**Issue by gulnadaf** [kubernetes/website#11362]
Hi,

I have deployed node.JS application docker image on Kubernetes cluster.  Exposed LoadBalancer service on deployment. I am able to see the "LoadBalancer" external IP and port (public/private). But when accessing the same using "curl" command with the ip & port. getting below exception 

"curl: (7) Failed to connect to <IP>port <port number>: Connection refused"

Please suggest the resolution/ additional information/ logging information to resolve the same.

NOTE : 1) Corresponding POD is in running state, more than a 2 hours now...

**Comment by DanyC97** [comment]
@gulnadaf is this a problem with the docs? if so please provide all the information as per the github issue template.
