### ISSUE TITLE
Menus don't pop over content in Safari

### ISSUE THREAD

**Issue by desertmonkey** [kubernetes/website#11367]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In Safari, the menus pop under the content frame below. They don't display above the content. See the screen shot. The site looks fine in Firefox.
![screen shot 2018-11-26 at 9 00 31 pm](https://user-images.githubusercontent.com/149453/49122882-32a69300-f26b-11e8-955f-0ba5c5ec1f75.png)

**Proposed Solution:**
Fix the Z axis layering? Not sure of the underlying cause, other than Safari is picky.

**Page to Update:**
https://kubernetes.io/... — universal since it's the menus at the top.

**Comment by desertmonkey** [comment]
/remove-lifecycle stale

--
Pete Bratach | manager, docs & community | outdoor cat | Cumulus Networks

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by desertmonkey** [comment]
/remove-lifecycle rotten.

Sure, backlog is fine. Not a huge deal. Thanks!
