### ISSUE TITLE
Rework high level cloud provider docs

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#11382]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
PR #10953 fixes a broken link, but also inadvertently identifies a larger underlying problem, which is that the cloud provider dev model is changing and we don't have a clear or obvious place to link any longer. 

**Proposed Solution:**
Content audit of all high level cloud provider docs, rewrite based on current state of dev. Current state appears to be in flux, so this is a high maintenance area, but we can and should keep it up to date.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/
and related pages

Assigning to myself to track; hope to reassign to better resource. @chrisnegus might this be you?

/assign

**Comment by sftim** [comment]
This still seems like a valid concern
/reopen
