### ISSUE TITLE
Assess content in Provide Load-Balanced Access to an Application in a Cluster

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#11431]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
In spite of various small fixes to this topic over the last year and a half, it seems still to have some fairly major problems. See (closed) PR #11395 

**Proposed Solution:**
A complete content audit of this and related topics to make sure we're documenting application access and load balancing appropriately across content pages.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

AND ANY RELATED PAGES

**Comment by pyaillet** [comment]
I may be missing something, but I don't see any added value in [Provide Load-Balanced Access to an Application in a Cluster](https://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/) compared to [Use a Service to Access an Application in a Cluster](https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/).

I'd simply remove [Provide Load-Balanced Access to an Application in a Cluster](https://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/), I have not spotted any problem in the other tasks.

If that's ok for you, I'll make a PR.

**Comment by Bradamant3** [comment]
I'm willing to take the PR to remove this topic, but for ease of content audit just in case there's something we might want to use down the road, here's the path to the built doc in an earlier version:
https://v1-12.docs.kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/
and to the file in the repo: https://github.com/kubernetes/website/blob/release-1.12/content/en/docs/tasks/access-application-cluster/load-balance-access-application-cluster.md
