### ISSUE TITLE
Issue with k8s.io/docs/tasks/example-task-template/

### ISSUE THREAD

**Issue by Sudharma** [kubernetes/website#11434]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The Link to related explanation is not working.

**Proposed Solution:**
Fix the broken link

**Page to Update:**
https://kubernetes.io/...

Documentation changes only

**Comment by charrywanganthony** [comment]
This is a demo which shows how to write a task doc, so it's not a real link. But i will try to improve this sentence in some way.
