### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by be-rock** [kubernetes/website#11445]
**This is a...** 
- [X] Feature Request
- [] Bug Report

**Problem:**
$ kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node --port=8080
Error: unknown flag: --port

**Proposed Solution:**
Update documentation

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

Kubernetes Version:
minikube version: v0.28.2

OS Version:
Mac OS 10.12.6

**Comment by ramineni** [comment]
@be-rock I'll work on this

**Comment by yaooluu** [comment]
I was following the tutorial and also faced same issue.

After removing `--port` from command:
> kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

The following command now requires `--port` to be specified:

> kubectl expose deployment hello-node --type=LoadBalancer --port=8080

Otherwise I'll see another error:

> error: couldn't find port via --port flag or introspection

**Comment by ramineni** [comment]
@yaooluu Right!! , I got the same error, Ill update the documentation for this command also.
Thanks.

**Comment by be-rock** [comment]
Thanks all.

**Comment by lusson-luo** [comment]
this page also has $ kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node --port=8080
Error: unknown flag: --port 
web：https://kubernetes.io/docs/tasks/extend-kubernetes/http-proxy-access-api/ 
![image](https://user-images.githubusercontent.com/19859400/174018111-dd4382ff-f29d-4658-80a3-c8d468160593.png)
