### ISSUE TITLE
Flesh out contributor guide with content that we no longer support

### ISSUE THREAD

**Issue by jaredbhatti** [kubernetes/website#11522]
We no longer maintain content on our blog that is older than a year. It would be good to create a page in our docs contributor guide about content that is out of scope to support. I'll start off that PR with some feedback from Jennifer Rondeau.

**Comment by DanyC97** [comment]
@jaredbhatti  was any PR open for this issue ?

**Comment by tengqm** [comment]
@DanyC97 We do have a [guide for this](https://kubernetes.io/docs/contribute/intermediate/#blog-issues), however, as you can see, it is there as a guidance for people *who triage and categorize issues*. One improvement I can think of is to copy this notice to the contributor's guidance, e.g.

- https://kubernetes.io/docs/contribute/start/#file-actionable-issues , and
- https://kubernetes.io/docs/contribute/start/#improve-existing-content

**Comment by sftim** [comment]
/priority backlog
Is that OK?
