### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/fedora/fedora_manual_config/

### ISSUE THREAD

**Issue by dmast-harmonyhit** [kubernetes/website#11521]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Missing information from the kubelet config on node.

**Proposed Solution:**
The following line needs to be added to the default kubelet config on the page:
KUBELET_API_SERVER="--api-servers=http://fed-master:8080"

**Page to Update:**
https://kubernetes.io/...

**Comment by charrywanganthony** [comment]
In `master-kubeconfig.yaml` already has `server: http://fed-master:8080`. It seems enough to me.

**Comment by charrywanganthony** [comment]
In this event we would check it soon, but for now we recommend kubeadm to set k8s up.
