### ISSUE TITLE
docs/setup/minikube.md is outdated in the dev-1.13-ko.4 branch

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#11531]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

- [ ]  docs/setup/minikube.md 1 file changed, 51 insertions(+), 41 deletions(-)

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually to the `content/ko` of `dev-1.13-ko.4` branch.

For example:
```
# checkout `k/website:dev-1.13-ko.4`
...
# check what is updated in the upstream 
git diff dev-1.13-ko.3 dev-1.13-ko.4 -- content/en/docs/setup/minikube.md
# apply changes to content/ko
vi content/ko/docs/setup/minikube.md
...
# commit and push
...
# make PR to `k/website:dev-1.13-ko.4`
```

**Page to Update:**
https://kubernetes.io/...

/language ko

**Comment by kychool** [comment]
Please let me handle this issue. :)

**Comment by gochist** [comment]
@kychool It's already assigned to other contributor on the slack. And I heard he is almost done with this. I'm sorry. I should leave this information in a comment.

**Comment by kychool** [comment]
@gochist No worries. :) Will look for another one.

**Comment by gochist** [comment]
in progress by #12273
