### ISSUE TITLE
maintenance of https://kubernetes.io/docs/setup/

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#11536]
during the SIG Cluster Lifecycle meeting of 05.12.2018 @luxas proposed that the SIG should probably own the whole https://kubernetes.io/docs/setup/ path of the docs.

in this case "own" means that we should maintain it and clean it up, while sig-docs still holds the final approve on PRs. any objections to this (e.g. by sig-docs) should be stated.

tasks at hand:
- add OWNER files so that we get pinged for changes in this path
- remove reviewers from individual files
- remove outdated pages that nobody maintains
- rename the setup/independent folder to setup/kubeadm
- re-organize other folders
- [apply redirects where needed](https://github.com/kubernetes/website/blob/master/static/_redirects)

also @timothysc mentioned that there is something related to the CNCF and volunteers that can help with this kind of work. i don't have more context on this.

/kind documentation
/priority backlog
@kubernetes/sig-docs-maintainers 
@kubernetes/sig-cluster-lifecycle 
/sig docs
/sig cluster-lifecycle

/assign

comments are welcome.

**Comment by roberthbailey** [comment]
@errordeveloper had started looking into cleaning up the getting started guides a few releases ago and we should definitely continue that effort. 

I would love to see the flowchart for "getting started" greatly simplified from the current state (https://kubernetes.io/docs/setup/pick-right-solution/). We should piggyback on the conformance program and only link to conformant installers, and ideally we could keep that list up to date via some sort of automation tied into the conformance process.

**Comment by fabriziopandini** [comment]
+1 on using conformance as a guiding criteria  
If something doesn't reach conformance in v1.x, it should be removed/makes as deprecated in v1.x+1

**Comment by Bradamant3** [comment]
The setup content is on the roadmap for sig-docs for Q1 2019. We already have several related projects in flight or partly implemented.

**Comment by hogepodge** [comment]
SIG-Cloud-Provider also has interest and expertise in these docs, especially in the context of configuring specific implementations of the cloud controller manager interface.

**Comment by neolit123** [comment]
going back to this topic.
a good number of pages there should be owned by SIG-CP, so i definitely agree with @hogepodge
