### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by Skeeve** [kubernetes/website#11542]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

$ kubectl api-resources --namespaced=true
Error: unknown command "api-resources" for "kubectl"

**Proposed Solution:**

No idea

**Page to Update:**
https://kubernetes.io/...

Kubernetes Version:

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by nikhita** [comment]
> Client Version: version.Info{Major:"1", Minor:"10", 

This feature was added in 1.11 in https://github.com/kubernetes/kubernetes/pull/42873. You'll need to be on a v1.11+ cluster for this to work.

Fwiw I can verify that it works on a 1.11+ cluster.
/close

**Comment by Skeeve** [comment]
Thanks! Didn't notice.
