### ISSUE TITLE
 Waiting for deployment spec update to be observed...

### ISSUE THREAD

**Issue by Sreelalithavankam** [kubernetes/website#11560]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
During deployment I am getting error  "Waiting for deployment spec update to be observed..." Pods are neither created nor terminated. 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

 I am maintiain revisionhistorylimit as 10. deleted desired 0 replicas. But still facing the issue

**Comment by charrywanganthony** [comment]
Can you plz give a specific way to reproduce it?

**Comment by Sreelalithavankam** [comment]
it is reproducable every time when i am doing deployment (kubectl apply -f deployment.yaml)

**Comment by DanyC97** [comment]
@Sreelalithavankam which docs page is this issue being seen ? 

if there is no issue related to the K8s docs then i'd suggest to seek help on maybe https://discuss.kubernetes.io/

**Comment by DanyC97** [comment]
in absence of any url pointing to the K8s docs i'm going to close this issue

/close
