### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by The-Judge** [kubernetes/website#11586]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The mentioned doc states:

> You must use a kubectl version that is within one minor version difference of your cluster.

I followed the guide to install kubectl for Ubuntu. This makes me end up with kubectl 1.13.0 .
I followed https://kubernetes.io/docs/tasks/tools/install-minikube/ to install `minikube`, which basically tells me to download the latest version of it, which is v0.30.0 .
Having started minikube, executing `kubectl version` brings:

> Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

1.13.0 and 1.10.0 are more than that "one minor version difference", mentioned before. So: Even when someone is following the officially guides closely, that person is ending up with an unsupported version combination.

**Proposed Solution:**
The guides should be aligned to match their own version requirements.

**Comment by DanyC97** [comment]
in the recent [minikube install](https://kubernetes.io/docs/tasks/tools/install-minikube/) it says _Install kubectl according to the instructions in [Install and Set Up kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)_ and as such i think we no longer have this issue hence candidate to be closed

**Comment by The-Judge** [comment]
I do not get how that is supposed to remove the issue I described.
