### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by 375gnu** [kubernetes/website#11612]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Incorrect secret type in TLS example.

**Proposed Solution:**
`type: Opaque` -> `type: kubernetes.io/tls`

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by sftim** [comment]
Is this OK to close?
