### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/assign-cpu-resource/

### ISSUE THREAD

**Issue by abhiramani-iptiq** [kubernetes/website#11617]
Args section which can assign CPU at startup is not working and give error:

Error: failed to start container "helloworldaks-container": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"-cpus\": executable file not found in $PATH": unknown

if we remove args section pod works fine.here is my yaml file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldaks-app
  labels:
    app: helloworldaks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworldaks-app
  template:
    metadata:
      labels:
        app: helloworldaks-app
    spec:
      containers:
      - name: helloworldaks-container
        image: <registryname>/helloworldaks:latest
        resources:
          limits:
            cpu: "100m"
            memory: "512Mi"
        args:
        - -cpus
        - "1"            
        ports:
        - containerPort: 80

**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sluetze** [comment]
Hi,

the "args" section delivers args for the container (thus, the image that is running in your container) the argument -cpus works with the "vish/stress" image, which is used in the docs but not with the "helloworldaks" image you used.

please swap the image 
```
- name: helloworldaks-container
  image: /helloworldaks:latest
```
to
```
- name: helloworldaks-container
  image: vish/stress
```

and try again

**Comment by abhiramani-iptiq** [comment]
it does work with vish/stress.
so what is the criteria for args section to allocate CPU at bootup to work?
because i have so many custom images with java code and alpine

**Comment by sluetze** [comment]
you don't need the args section.

you can limit the ressources for the container with `resources:limit`. Think of this as a maximum for anything running in that container

```
    resources:
      limits:
        cpu: "1"
```

and you can require kubernetes to request CPU by using `resources:requests`. Think of this as a "minimum" of resources assigned to this container.
```
    resources:
      requests:
        cpu: "0.5"
```

I guess the last part is what you want to do.

in args sections you provide arguments for your application. when using java you can limit resources at the java side - please consult the java docs for guidance
