### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/expose-external-ip-address/

### ISSUE THREAD

**Issue by menzellu** [kubernetes/website#11616]
not getting the external ip

**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
waited a few minutes, still not getting the external ip address

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

1.13 cluster with 3 nodes

**Comment by sluetze** [comment]
Hi,

which cloud provider are you using?

> Use a cloud provider like Google Kubernetes Engine or Amazon Web Services to create a Kubernetes cluster. This tutorial creates an external load balancer, which requires a cloud provider.
