### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by TomHutter** [kubernetes/website#11632]
**This is a** 

- [ ] Feature Request
- [ ] Bug Report
- [x] Change Request

**Problem:**
When using other names than infra0 .. infra2, the initial-cluster: statement is wrong.

**Proposed Solution:**

`initial-cluster: ${NAMES[0]}=https://${ETCDHOSTS[0]}:2380,${NAMES[1]}=https://${ETCDHOSTS[1]}:2380,${NAMES[2]}=https://${ETCDHOSTS[2]}:2380`

**Page to Update:**
https://k8s.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/

**Comment by neolit123** [comment]
thanks for the report @TomHutter 

/kind bug
/sig-cluster-lifecycle
@kubernetes/sig-cluster-lifecycle
