### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by libnux** [kubernetes/website#11715]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Where is the official setup guide for kube-router CNI addon? I checked the doc on kube-router site, the setup guide is linked to this page. 

"For information on setting up Kubernetes cluster, with Kube-router using kubeadm, please **see official setup guide.**", 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
so it appears the link is there, it's just that it does not highlight on mouse over.
all i can do for now is make it bold / underlined and create another issue for tracking the CSS bug.

**Comment by neolit123** [comment]
reported separate issue:
https://github.com/kubernetes/website/issues/11724

thanks.
/close
