### ISSUE TITLE
BUG: links inside tabs do not have the proper CSS

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#11724]
if you go to this page:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network
- under the "Kube-router" tab there is the following text "....Kube-router using kubeadm, please see official setup guide."
- in that sentence `setup guide` is a markdown link except it's missing the regular CSS color / mouse over highlight.

reported by @libnux here:
https://github.com/kubernetes/website/issues/11715

/kind bug
/sig docs
@kubernetes/sig-docs-maintainers

**Comment by xiangpengzhao** [comment]
/close
as https://github.com/kubernetes/website/pull/11845 fixed this.
