### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by michaellady** [kubernetes/website#11754]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
This page is ranked at the top when I google "install minikube", but provides no information for how to actually install it.

**Proposed Solution:** 
Provide code snippets or a link to them for how to install minikube

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
There is a link in that subsection pointing you to https://github.com/kubernetes/minikube/releases, where you can find the installation instruction.
