### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update/update-interactive/

### ISSUE THREAD

**Issue by sh3llf1sh** [kubernetes/website#11756]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

Wrong image number in the built-in command.

Authentication required to pull down kubernetes-bootcamp:v10 image. 

Warning  Failed                 7s    kubelet, minikube  Failed to pull image "gcr.io/google-samples/kubernetes-bootcamp:v10": rpc error: code = Unknown desc = unauthorized: authentication required
  Warning  Failed                 7s    kubelet, minikube  Error: ErrImagePull

**Proposed Solution:**

Change command to be pull down v1 instead of v10. 

**Page to Update:**
https://kubernetes.io/...

**Comment by hong823** [comment]
@sh3llf1sh i believe you're referring to the command in https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-interactive/

`
kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=gcr.io/google-samples/kubernetes-bootcamp:v10
`

If that's the case, i believe it was intended to pull a non existence docker image as it's trying to demonstrate  how `kubectl rollout` would help in case of deployment issue with docker image.
