### ISSUE TITLE
Deployment documentation incorrectly describes how ReplicaSets are named.

### ISSUE THREAD

**Issue by darkmane** [kubernetes/website#11763]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
[Deployment documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment) incorrectly describes how ReplicaSets are named.

ReplicaSets created by Deployments are no longer named [Deployment Name]-[Pod-template-hash] 

**Proposed Solution:**
Correct how names are generated. I will try and comment with the process once I find it in source code.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

1.9+

**Comment by zacharysarah** [comment]
@juandiegopalomino This may make sense as a follow-up to #12409--what do you think?

**Comment by juandiegopalomino** [comment]
@zacharysarah alrighty. It seems like a 1-2 sentence fix (or am I missing something), correct?

**Comment by zacharysarah** [comment]
@juandiegopalomino It looks pretty straightforward, just removing deprecated content. I recommend tagging @darkmane for review on the PR.

**Comment by juandiegopalomino** [comment]
cool, on it

**Comment by DanyC97** [comment]
@juandiegopalomino you still on it ? if not let me know and i might have spare cycle to help

**Comment by juandiegopalomino** [comment]
https://github.com/kubernetes/website/pull/12712

**Comment by juandiegopalomino** [comment]
@DanyC97 ^

**Comment by DanyC97** [comment]
cool, thank you @juandiegopalomino . in which case i guess current issue can be closed ?

**Comment by juandiegopalomino** [comment]
I believe so
