### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by farrukh90** [kubernetes/website#11764]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Would be really nice if we had some type of shortcut for resourcequota  like "rq" maybe. It is going to be easier to edit it with kubectl edit rq

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
Please propose to kubernetes/kubernetes project.
