### ISSUE TITLE
Embed examples of https://github.com/ahmetb/kubernetes-network-policy-recipes to the official docs

### ISSUE THREAD

**Issue by abdennour** [kubernetes/website#11769]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The official website (k8s.io) does not include enough examples/recipes about NetworkPolicy usage.

**Proposed Solution:**
Integrate with the content of the Github repository https://github.com/ahmetb/kubernetes-network-policy-recipes

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by tengqm** [comment]
@ahmetb what do you think?
