### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

### ISSUE THREAD

**Issue by xiaotuanyu120** [kubernetes/website#11774]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I am a newcomer for k8s. I want to know the kubectl's configuration, so I googled it and found the docs easily:
=> https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/
here, I know some basic config of kubectl. Its good.

BUT, there is one thing I have to googled a lot and spent much time on it, its about the base64 encode data of cert file content (such as `certificate-authority-data`) instead of put the file path there in the configuration. 

[here](https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/), also the doc in your website I found the `certificate-authority-data` configuration. So I wandered why you don't mention it in the [previous doc - configure-access-multiple-clusters](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)?

**Proposed Solution:**
add the information of the configuration below to https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

- `certificate-authority-data`
- `client-certificate-data`
- `client-key-data`

**Comment by tengqm** [comment]
@xiaotuanyu120 Thanks for filing this issue. Do you mind propose a PR to fix it?

**Comment by xiaotuanyu120** [comment]
okay, I will do a PR tonight
