### ISSUE TITLE
The format of upgrade way of v1.13 seems mess

### ISSUE THREAD

**Issue by oomichi** [kubernetes/website#11806]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13/#upgrade-master-and-node-packages should show upgrade ways for each distribution like ubuntu and Red Hat, but now the format is broken and the ways are mess.

**Proposed Solution:**

The tab name should be named independently.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13/#upgrade-master-and-node-packages

v1.13

**Comment by neolit123** [comment]
PR that should fix the same issue:
https://github.com/kubernetes/website/pull/11629
