### ISSUE TITLE
Issue with k8s.io/docs/reference/

### ISSUE THREAD

**Issue by lipmanp** [kubernetes/website#11826]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/ 
api doc reference not working properly due to jquery-2.2.0.min.js and bootstrap.min.js not found.

https://kubernetes.io/js/jquery-2.2.0.min.js 404 (Not Found)
https://kubernetes.io/js/bootstrap.min.js 404 (Not Found)

**Proposed Solution:**
put back the missing JS file

**Page to Update:**
https://kubernetes.io/...

1.11
1.12
1.13

**Comment by tengqm** [comment]
1.12 works. 1.11 and 1.13 doesn't work.
