### ISSUE TITLE
Dead link to dashboard deployment file

### ISSUE THREAD

**Issue by siw36** [kubernetes/website#11837]
**This is a...** 
- [x] Bug Report

**Problem:**
The link `https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml` is dead.

I think the latest commit to the kubernetes/dashboard repo caused this issue.  
(https://github.com/kubernetes/dashboard/commit/7c73bacd64d5fc1e80561d355a4e0dd3c33f984b)  
Also:
In this commit the architecture changed from amd64 to arm:  
Line 126: `image: k8s.gcr.io/kubernetes-dashboard-arm:v1.10.1`  
(https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/kubernetes-dashboard.yaml)  

Now both files `kubernetes-dashboard.yaml` and `kubernetes-dashboard-arm.yaml` are using the arm image.

**Proposed Solution:**
Change the file `kubernetes-dashboard.yaml` to use the amd64 image and update the link on this page.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by liuyanjie** [comment]
ref #https://github.com/kubernetes/dashboard/issues/3447
