### ISSUE TITLE
Translate concepts/workloads/pods/pod in Korean

### ISSUE THREAD

**Issue by nowjean** [kubernetes/website#11854]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No concepts/workloads/pods/pod in Korean

**Proposed Solution:**
Translate concepts/workloads/pods/pod in Korean

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod/

/language ko

**Comment by gochist** [comment]
This issue is in progress by #13927 
/remove-lifecycle rotten
