### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/daemonset/

### ISSUE THREAD

**Issue by openstacker** [kubernetes/website#11866]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

The sentence "DNS: Create a headless service with the same pod selector, and then discover DaemonSets using the endpoints resource or retrieve multiple A records from DNS.", there is a 'A' between 'multiple' and 'records', is it a typo?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by chentao1596** [comment]
I don't think so, "A record" is the most basic type of DNS record.

**Comment by openstacker** [comment]
Thanks for the clarification. I did more research and just realized it's correct. Thanks.

**Comment by Hartmarken348** [comment]
11886
