### ISSUE TITLE
No Reference Docs for new API groups

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#1186]
On the left nav for http://kubernetes.io/docs/reference/ I see:
-  Kubernetes API
- Autoscaling API
- Batch API
- Extensions API

The following API groups are missing:
- Apps API
- Certificates API
- Policy API
- Storage API
- Authorization API 

These groups should have auto-generated documentation.

**Comment by bluecmd** [comment]
Right now it seems like at least apps has: http://kubernetes.io/docs/api-reference/apps/v1beta1/definitions/

It is not linked into the navigation ("Support" is what it reports).

**Comment by tengqm** [comment]
Looks like all API groups/resources are documented now.
