### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by fsando** [kubernetes/website#11885]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When trying to resize the terminal (placing the mouse pointer at the top border of the terminal) it jumps to fill the whole browser window except for the menu at the top and it's impossible to resize it back, forcing one to reload the page and restart the terminal.

This is in Firefox 64.0 (64-bit) on ubuntu 18.04

**Proposed Solution:**
None

**Page to Update:**
https://kubernetes.io/...

**Comment by Hartmarken348** [comment]
11855
