### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/replicaset/

### ISSUE THREAD

**Issue by nomadicsun** [kubernetes/website#11906]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
kubectl autoscale rs frontend

missing max flag

**Proposed Solution:**
kubectl autoscale rs frontend --max=10

**Page to Update:**
https://kubernetes.io/...

**Comment by tuanvcw** [comment]
Hi, I'll take this

**Comment by tengqm** [comment]
@tuanvcw You can leave a comment "/assign", then the issue will be assigned to you.

**Comment by tuanvcw** [comment]
Thank you very much @tengqm :)
/assign
