### ISSUE TITLE
Clarify --config and --kubeconfig

### ISSUE THREAD

**Issue by justicezyx** [kubernetes/website#11954]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ states to use --config with a config file following KubeletConfiguration schema, but the texts did not clarify its relationship with --kubeconfig.

**Proposed Solution:**
- Please consider expand the texts, or link to another page with more details.
- If these cannot be done immediately, I suggest to leave a TODO to ask readers to follow a certain known typical practice, in order to prevent random chasing.
- Something else is more reasonable. Please advise.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file

Future work:
- As K8s' popularity grows, the amount of newcomers are significantly growing, please make sure the documentations are written with a clear targeted audience to avoid writing documents that are not meaningful for expert, but also at the same time is lacking too many details to be useful for novices.

PS:
- The reporter is new to k8s, and has no knowledge to implement the possible solutions.

**Comment by DanyC97** [comment]
/language en

there is info in the docs we just need to link it

**Comment by justicezyx** [comment]
If you have pointers to the docs, and where should they be linked in addition to the reported places, I'll be happy to create a PR.

**Comment by DanyC97** [comment]
will look it up @justicezyx and will be very happy to review your PR. thank you for your help
