### ISSUE TITLE
Translate concepts/architecture/cloud-controller in Korean

### ISSUE THREAD

**Issue by zer0big** [kubernetes/website#11964]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No concepts/architecture/cloud-controller in Korean

**Proposed Solution:**
Translate concepts/architecture/cloud-controller in Korean

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/cloud-controller/

/language ko

**Comment by Hartmarken348** [comment]
Treyneeyatedseded Korean
