### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by Beny406** [kubernetes/website#11975]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
![image](https://user-images.githubusercontent.com/17677796/50541235-8cb7b280-0ba1-11e9-9997-a3edb034caa5.png)
It says "This specification will create a Service which targets TCP port 80 on any Pod with the run: my-nginx label" but no `targetPort` is defined in the example. It is missleading.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by Hartmarken348** [comment]
K8s
