### ISSUE TITLE
Kubernetes API docs section index autoscroll only goes down as far as `CONFIG AND STORAGE APIS > Volume Attachment v1beta1 storage.k8s.io`

### ISSUE THREAD

**Issue by tjimsk** [kubernetes/website#11987]
To reproduce:

1. Go to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/
2. Click on any section index item below `CONFIG AND STORAGE APIS > VolumeAttachment v1beta1 storage.k8s.io` (for example, `CLUSTER APIS > Namespace v1 core`)
3. The index view automatically scrolls to and focuses on `CONFIG AND STORAGE APIS > VolumeAttachment v1beta1 storage.k8s.io > Read Operations > Watch List`

For step 2, any section index before will trigger the expected autoscroll result (for example, click on `WORKLOADS APIS > ReplicaSet v1 apps`).

**Comment by Hartmarken348** [comment]
11987

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by sftim** [comment]
This seems to be fixed. Have I got that right?
