### ISSUE TITLE
Table issue with /docs/reference/federation/extensions/v1beta1/definitions/#_v1_execaction

### ISSUE THREAD

**Issue by yardensachs** [kubernetes/website#11986]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
A table body row is miss-aligned with its head row under: https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1_execaction

Code:
https://github.com/kubernetes/website/blob/4eb78ea11a92b9c4c349345ffc4224dd76b70def/content/en/docs/reference/federation/extensions/v1beta1/definitions.html#L1859

Image:
![image 2018-12-31 at 6 54 36 pm](https://user-images.githubusercontent.com/2768400/50564455-a7b72d80-0d2d-11e9-91ec-bcca0792ef61.png)

**Proposed Solution:**
Move the content to the correct cell.

**Page to Update:**
https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1_execaction

**Comment by Hartmarken348** [comment]
11986

**Comment by yardensachs** [comment]
@Hartmarken348 
@Shubhanshu88 Thank you!
But the table is 5 columns, IMHO it might be good HTML to add a 5th column.

**Comment by yardensachs** [comment]
This is still an issue
