### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by darkdragn** [kubernetes/website#11993]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:** It's undocumented that Volume Type of Local is required to follow block device naming conventions. I attempted the following folder names: /mnt/disks/minio, /mnt/disks/nginx, /mnt/disks/nginx-1. Each was met with a failed mount, however the following folder names resulted in successful mounts: /mnt/disks/mini1, /mnt/disks/tmp1, /mnt/disks/along1, /mnt/disks/long01. (Filesystem mode of course, implied by the reference to folder names)

I haven't had the time to look through the code, and I've mostly been doing the testing from ssh on my cell phone, since I'm traveling, but the only conclusion that I could draw is that even when using Filesystem mode for local volume it's requiring that the folder name adhere to block device naming conventions (3-4 lowercase letters, end in a number, no special characters)

**Proposed Solution:** If this is desired, no coding change necessary, but I would recommend that a note be added mentioning this on the docs/concepts/storage/volumes#local section, to save some others that would like to use this feature a little bit of a headache.

(Side note, I would like to file this under Documentation update instead of Bug Report, since this may be a desired restriction. Sorry, I just didn't want to edit the template, in case it triggers assignees.)

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/#local

**Kubernetes Version:** v1.13.1

**Additional Information:**  Running on Raspbian, RPI 3 A+ with kernel version 4.14.90-v7+.

**Comment by DanyC97** [comment]
thank you @darkdragn for suggestion, we shall try to work on something

/language en
