### ISSUE TITLE
URLs in API reference documents should be links instead of plain text

### ISSUE THREAD

**Issue by ajaygm** [kubernetes/website#12002]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The URLs in API reference documents at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/ should be links instead of plain text.

**Proposed Solution:**
**Example...**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#job-v1-batch

**Current...**

Field | Description
-- | --
apiVersion string | APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: h ttps://git.k8s.io/community/contributors/devel/api-conventions.md#resources

_Note: The example above has a broken URL text (i.e. there's a space in "http") to prevent the text being represented as link._

**Proposed...**

Field | Description
-- | --
apiVersion string | APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources

**Page to Update:**
All generated pages at... 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/

**Comment by tengqm** [comment]
Although cannot reproduce the problem caused by "extra spaces", there is still a possibility to improve the handler of http/https links.
