### ISSUE TITLE
Unscheduleable isn't the possible value of type field

### ISSUE THREAD

**Issue by tkanng** [kubernetes/website#12051]
**This is a Bug Report** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
  Hi,  when I read [Pod Conditions](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions), I found that  the `type` field of  `PodCondition` is a string, which might be `PodScheduled`,`Ready`,`Initialized`,`Unschedulable`,`ContainersReady`. 

  Then I checked the [code](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2353), I got this, showing that the type of `Unschedulable` isn't `PodConditionType` ( just `string` ), which means that  **`Unscheduleable` isn't the possible value of `type` field.** 
``` go
const (
	// PodScheduled represents status of the scheduling process for this pod.
	PodScheduled PodConditionType = "PodScheduled"
	// PodReady means the pod is able to service requests and should be added to the
	// load balancing pools of all matching services.
	PodReady PodConditionType = "Ready"
	// PodInitialized means that all init containers in the pod have started successfully.
	PodInitialized PodConditionType = "Initialized"
	// PodReasonUnschedulable reason in PodScheduled PodCondition means that the scheduler
	// can't schedule the pod right now, for example due to insufficient resources in the cluster.
	PodReasonUnschedulable = "Unschedulable"
	// ContainersReady indicates whether all containers in the pod are ready.
	ContainersReady PodConditionType = "ContainersReady"
)

// PodCondition contains details for the current condition of this pod.
type PodCondition struct {
	// Type is the type of the condition.
	// More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
	Type PodConditionType `json:"type" protobuf:"bytes,1,opt,name=type,casttype=PodConditionType"`
	// Status is the status of the condition.
	// Can be True, False, Unknown.
	// More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#pod-conditions
	Status ConditionStatus `json:"status" protobuf:"bytes,2,opt,name=status,casttype=ConditionStatus"`
	// Last time we probed the condition.
	// +optional
	LastProbeTime metav1.Time `json:"lastProbeTime,omitempty" protobuf:"bytes,3,opt,name=lastProbeTime"`
	// Last time the condition transitioned from one status to another.
	// +optional
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty" protobuf:"bytes,4,opt,name=lastTransitionTime"`
	// Unique, one-word, CamelCase reason for the condition's last transition.
	// +optional
	Reason string `json:"reason,omitempty" protobuf:"bytes,5,opt,name=reason"`
	// Human-readable message indicating details about last transition.
	// +optional
	Message string `json:"message,omitempty" protobuf:"bytes,6,opt,name=message"`
}
```

**Proposed Solution:**
1. Delete `Unschedulable` as the possible value of `type` field. 
2. Add  some comments about `Unschedulable`:
> Reason in PodScheduled PodCondition means that the scheduler can't schedule the pod right now, for example due to insufficient resources in the cluster.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions

**Comment by tengqm** [comment]
Looks like a code bug?
@kubernetes/sig-scheduling-bugs

**Comment by bsalamat** [comment]
`PodReasonUnschedulable` is not a `PodConditionType`. It is a string literal used as a `Reason` in `PodCondition` for Pods which are not schedulable. `Type` of `PodCondition` in those cases is `PodScheduled` and `Status` is `ConditionFalse`.
See here: https://github.com/kubernetes/kubernetes/blob/2c8b571d573d434687316c606fb5e20e63008345/pkg/scheduler/scheduler.go#L280

/close

**Comment by tengqm** [comment]
@bsalamat Thanks for the explanation. If `PodReasonUnschedulable` doesn't belong to the pod condition type group, we may want to move it out to a separate `const {}` statement. The current code is confusing.

**Comment by tkanng** [comment]
If `PodReasonUnschedulable` doesn't belong to the pod condition, we should delete it on [Pod Conditions document](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions) ?
