### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port? 

### ISSUE THREAD

**Issue by ariamore** [kubernetes/website#12075]
I just finished to install kubectl via Ubuntu 64 (Linux). I followed the online Kubernetes guide, but I've had an error with the host.
This is the message:

root@ubuntu:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Someone has the same mistake? How can i fix it?

**Comment by thecrudge** [comment]
/close

Issue is without reference, and looking at OPs github, they've obviously made it past whatever issue they were experiencing.
