### ISSUE TITLE
Broken download url in k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by Grovespaz** [kubernetes/website#12097]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The minikube-windows-amd64.exe link is broken, it 404's.

**Proposed Solution:**
Replace the url with https://github.com/kubernetes/minikube/releases/download/v0.32.0/minikube-windows-amd64 or with a url that will always point to latest.

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by tuanvcw** [comment]
Hi, I would like to take this as my first issue :)
I'm creating a pull request at this moment.
