### ISSUE TITLE
Issue generators listing with k8s.io/docs/reference/kubectl/conventions/

### ISSUE THREAD

**Issue by ryandawsonuk** [kubernetes/website#12090]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation at https://kubernetes.io/docs/reference/kubectl/conventions/#generators suggests that I should be able to use the generator `extensions/v1beta1` much as `deployment/v1beta1` as it lists `kubectl run --generator=extensions/v1beta1` right next to `kubectl run --generator=deployment/v1beta1`, with the latter being recommended. 

But is the difference really that one is recommended and the other not?  `kubectl run --generator=deployment/v1beta1 foobar --image=nginx -o yaml --dry-run` works but with `extensions/v1beta1` you get `error: generator "apps/v1beta1" not found` (e.g. when running via the interactive environment in https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/).

**Proposed Solution:**
Either remove the non-recommended options or clarify how or when they can be used.

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/conventions/#generators

**Comment by tengqm** [comment]
Looks like we need both code patches and doc patches for this.
@janetkuo

**Comment by DanyC97** [comment]
i think we need to also understand when the deprecation of the generators is coming in - see https://stackoverflow.com/questions/52890718/kubectl-run-is-deprecated-looking-for-alternative

@soltysh any insights when this might be targeted ? maybe we can remove the entire section from the docs

**Comment by soltysh** [comment]
> @soltysh any insights when this might be targeted ? maybe we can remove the entire section from the docs

Generator were deprecated in 1.12, so we'll need to wait to 1.15 at least to get that removed. We should update the docs but clearly state it's deprecated functionality. Also we need to fix code where needed.

**Comment by DanyC97** [comment]
thank you for taking the time to respond.
I'll go over each of the generator and then post here which one works, which one doesn't and then update the docs.
