### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by ranjeet-floyd** [kubernetes/website#12091]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
## In a namespace command
$ kubectl api-resources --namespaced=true
$ kubectl api-resources --namespaced=false
Error: unknown command "api-resources" for "kubectl"

❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
please read docs that match your kubernetes version: https://v1-10.docs.kubernetes.io/
