### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/service/ : Remove the AWS cloud provider bias

### ISSUE THREAD

**Issue by dbsanfte** [kubernetes/website#12108]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
There are AWS examples in these docs, but no Azure/etc examples.

**Proposed Solution:**
Add some Azure/etc examples. AWS isn't the only cloud out there by far. There's no reason to be biased towards it when Azure has its own managed Kube service offering, for example.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by sftim** [comment]
This links to the wider cleanup / reorganisation from #3735
