### ISSUE TITLE
Issue with /docs/admin/multiple-zones - how to configure without kube-up?

### ISSUE THREAD

**Issue by jonmoter** [kubernetes/website#1210]
That document explains how to enable that ability by running `kube-up` with `MULTIZONE=true`. However, it doesn't explain what that's doing under the hood.

I am building a production cluster manually using my own provisioning scripts (for reasons of security, compliance, high availability, etc.) I'd like to know what the underlying mechanism is for this feature, so I can enable it.  Is it just a matter of adding labels to the node of this form?

```
failure-domain.beta.kubernetes.io/region=us-central1
failure-domain.beta.kubernetes.io/zone=us-central1-a
```

Do I have to set additional flags when invoking kubelet or kubernetes-scheduler?

In general, it would be helpful to have this sort of thing documented in the admin guide, for people who don't want to (or can't) rely on kube-up.

**Comment by jeffmendoza** [comment]
Need a cluster federation SME to enhance docs.
