### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by harikkolla** [kubernetes/website#12109]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
While creating the service using Minikube, unable to access the service using browser. After opening the url in browser and entered the port 8080 and click Display Port, 

Below is the error message displayed, same message was displayed after multiple retries
Connecting to Port 8080
We're currently trying to connect to a HTTP service running on 8080. Services can sometimes take a few moments to start, even upto five minutes.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

URL uses to open the service in Browser: https://2886795298-8080-cykoria02.environments.katacoda.com/
![image](https://user-images.githubusercontent.com/46442298/50761706-aa6dd180-129d-11e9-928f-168711c1bbd5.png)

**Comment by matt-shuler** [comment]
+1

Service has been pending for 15 minutes

**Comment by shubheksha** [comment]
@BenHall - could you take a look?

**Comment by BenHall** [comment]
@shubheksha Thanks! Will investigate
