### ISSUE TITLE
Missing table legend in k8s.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by gazoo4** [kubernetes/website#12112]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
It's not clear how to read the [table](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) mapping the compatibility between the storage drivers and PV access modes (e.g. supported/not-supported, recommended/not-recommended,...?). Came to the surface while having a dispute in the team how this table should be understood.

**Proposed Solution:**
I'd like to ask to add a legend to the table listing the supported storage drivers and access modes.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

1.13, going back at least to 1.10

**Comment by tengqm** [comment]
Not sure what kind of specific action can be taken. The access modes columns are all about the supported status, not *recommended* options, IIUC.

**Comment by gazoo4** [comment]
Thanks for your reply. This is exactly the information I found missing in the docs. For your consideration.
