### ISSUE TITLE
Issue with k8s.io/docs/setup/minikube/

### ISSUE THREAD

**Issue by adamgit** [kubernetes/website#12149]
**This is a...** 

- [ x] Feature Request
- [ ] Bug Report

**Problem:**

HyperV isn't listed as a valid driver, and the link through to the Drivers/Plugins page does not include a flag for launching with HyperV

NB: googling around suggests there is an extra, unlisted, driver called simply "hyperv" - e.g. here: https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c

**Proposed Solution:**

1. Make it explicit that HyperV is supported (by which driver? I really don't know. Could be HyperKit? Or xhyve? Or something else - I have no idea, docs don't make this clear)
2. On the plugins page, call-out whichever driver uses HyperV

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
/close 

This issue is resolved
