### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by aario** [kubernetes/website#12148]
**This is a...** 

- [ x ] Feature Request
- [ ] Bug Report

**Problem:**
It is mentioned how to replace a part of configuration by doing
kubectl replace
It's not mentioned anywhere how to view current configuration.

**Proposed Solution:**
Write on how to view current configuration.

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/

**Comment by thecrudge** [comment]
/close 

The reference to kubectl config view is already there
