### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/troubleshooting/

### ISSUE THREAD

**Issue by viswanathredd** [kubernetes/website#12175]
i am getting this error  in kubelet service status 
journalctl -fu kube-kubelet

E0111 12:20:06.867715   11077 kubelet_node_status.go:302] Error updating node status, will retry: Operation cannot be fulfilled on nodes "10.xx.x.xx": the object has been modified; please apply your changes to the latest version and try again

Below data is grabbed from pod with. 
kubectl describe po security-1689152837-xvjjv

spec.containers{security}       Normal  Killing         Killing container with docker id 41a703d5ae76: pod "security-1689152837-xvjjv_default(6cd707d2-158f-11e9-961d-005056a6318e)" container "security" is unhealthy, it will be killed and re-created.
  1m    <invalid>       7       {kubelet xx.xx.xx.xxx}                                   Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "security" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=security pod=security-1689152837-xvjjv_default(6cd707d2-158f-11e9-961d-005056a6318e)"

  6m            <invalid>       5       {kubelet xx.xx.xx.xxx}   spec.containers{security}       Normal  Pulled          Container image "xx.xx.xx.xxx:5000/foundation/security-server:1.8.10-SNAPSHOT.1171" already present on machine
  <invalid>     <invalid>       1       {kubelet xx.xx.xx.xxx}   spec.containers{security}       Normal  Started         Started container with docker id c41b1c82c73d
  <invalid>     <invalid>       1       {kubelet xx.xx.xx.xxx}   spec.containers{security}       Normal  Created         Created container with docker id c41b1c82c73d; Security:[seccomp=unconfined]
  5m            <invalid>       7       {kubelet xx.xx.xx.xxx}   spec.containers{security}       Warning Unhealthy       Liveness probe failed: Get http://xx.xx.xx.xxx:80/health: dial tcp xx.xx.xx.xxx:80: getsockopt: connection refused
  5m            <invalid>       17      {kubelet xx.xx.xx.xxx}   spec.containers{security}       Warning Unhealthy       Readiness probe failed: Get http://xx.xx.xx.xxx:80/health: dial tcp xx.xx.xx.xxx:80 getsockopt: connection refused
  <invalid>     <invalid>       1       {kubelet xx.xx.xx.xxx}   spec.containers{security}       Normal  Killing         Killing container with docker id c41b1c82c73d: pod "security-1689152837-xvjjv_default(6cd707d2-158f-11e9-961d-005056a6318e)" container "security" is unhealthy, it will be killed and re-created.
  1m            <invalid>       15      {kubelet xx.xx.xx.xxx }   spec.containers{security}       Warning BackOff         Back-off restarting failed docker container
  <invalid>     <invalid>       8       {kubelet xx.xx.xx.xxx}                                   Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "security" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=security pod=security-1689152837-xvjjv_default(6cd707d2-158f-11e9-961d-005056a6318e)"

We are using only one container in pod. We are getting 0/1 when we are creating it. Please provide the solution for this.

**Comment by shubheksha** [comment]
@viswanathredd, this repo contains Kubernetes documentation and isn't the best place to ask for support regarding the operation of Kubernetes. Please try one of the [support channels](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#support-structures) listed instead.
