### ISSUE TITLE
Broken link in k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by viane** [kubernetes/website#12179]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
`ingress-class` link is no longer valid in the Ingress controllers [secion](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-controllers)

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress

**Comment by rlenferink** [comment]
Fixed.

/close
