### ISSUE TITLE
Issue with k8s.io/zh/docs/tasks/inject-data-application/define-environment-variable-container/

### ISSUE THREAD

**Issue by daohu527** [kubernetes/website#12172]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The command not work, it's "--", not "–".
```
进入该Pod下的容器并打开一个命令终端:

kubectl exec -it envar-demo – /bin/bash
```
I see the [define-environment-variable-container.md](https://github.com/kubernetes/website/blob/release-1.13/content/zh/docs/tasks/inject-data-application/define-environment-variable-container.md) in github.The file is right,I think it's the problem by web editor.

**Proposed Solution:**
Need to check the problem.

**Page to Update:**
https://kubernetes.io/zh/docs/tasks/inject-data-application/define-environment-variable-container/

**Comment by rlenferink** [comment]
@tengqm can you close this one as the issue has been solved?
