### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/binary_release/

### ISSUE THREAD

**Issue by xiaoluo1314** [kubernetes/website#12186]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Sai-Adarsh** [comment]
@xiaoluo1314 could i work on this?

**Comment by thecrudge** [comment]
/close

Not only is there absolutely no information on this issue, it looks like whatever issue (possibly broken link?) has been corrected and merged to master.
