### ISSUE TITLE
Several broken links in files in reference/setup-tools/kubefed/

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#12207]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
There are several broken links in reference/setup-tools/kubefed/.
- kubefed_init.md  
- kubefed_join.md  
- kubefed_options.md  
- kubefed_unjoin.md  
- kubefed_version.md

The following link in each file causes 404 error.
```
### SEE ALSO
* [kubefed](kubefed.md)	 - kubefed controls a Kubernetes Cluster Federation
```

**Proposed Solution:**
Fix the link address for each file.
```
### SEE ALSO
* [kubefed](/docs/reference/setup-tools/kubefed/kubefed)	 - kubefed controls a Kubernetes Cluster Federation
```

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_options/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_init/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_join/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_unjoin/
https://kubernetes.io/docs/reference/setup-tools/kubefed/kubefed_version/

**Comment by nepomucen** [comment]
@seokho-son could you please re-open this issue (I have no appropriate rights to do so).
The problem of broken links still persists in latest Kubernetes documentation (v.1.17).

**Example:**
From page:
https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/#deploying-a-federation-control-plane
try to follow "kubefed_init" hyperlink
Outcome:
404 Page not found
