### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by shaktiprasadrath** [kubernetes/website#12216]
Ii I have an already created POD, is it possible to link that in deployment YML file rather then writing the template section(which is similar to POD yml)?? If Yes, please specify the documentation/reference link.

**Comment by sftim** [comment]
@ shaktiprasadrath - you want to know if you can have an existing Pod stay running and become adopted into a Deployment that you're about to create?
/triage support
