### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

### ISSUE THREAD

**Issue by regmilton** [kubernetes/website#12217]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The provided YAML for the custom metrics auto scaler is inconsistent with the mentioned version (autoscaling/v2beta1) which looks quite different, at least for the Object type of metric (the one I looked into). For example, the API specification does not include targetAverageValue (only targetValue), and target is used to described the so-called "describedObject" and on and on.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the report
/language en
