### ISSUE TITLE
Add etcd version information in k8s.io/docs/setup/version-skew-policy/

### ISSUE THREAD

**Issue by wenjiaswe** [kubernetes/website#12233]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Thanks to @liggitt who points to me in https://github.com/kubernetes/kubernetes/issues/71572#issuecomment-443010697, that this is the right place for k8s apiserver - etcd version documentation. 

**Proposed Solution:**

**Page to Update:**
https://deploy-preview-11060--kubernetes-io-master-staging.netlify.com/docs/setup/version-skew-policy/#supported-component-upgrade-order

xref: 
https://github.com/kubernetes/kubernetes/issues/45506
https://github.com/kubernetes/website/pull/11060

/assign @wenjiaswe 
/cc @liggitt @imkin @gyuho @jpbetz

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by wenjiaswe** [comment]
@sftim sure.
