### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by arvindeybram** [kubernetes/website#12256]
**This is a request to add some more syntactical information about kubernetes namespaces** 

- [x ] Feature Request
- [ ] Bug Report

**Problem:**
How to delete namespaces?

**Proposed Solution:**
kubectl delete ns <namespace-name>

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by paralika** [comment]
It looks like namespaces creation and deletion information is available in another page, and it is already mentioned in this page. Please search for:

`Creation and deletion of namespaces are described in the Admin Guide documentation for namespaces.`
