### ISSUE TITLE
cann't access The web

### ISSUE THREAD

**Issue by qiyongxiao** [kubernetes/website#12259]
/remove-lifecycle stale
`
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
`
I create dashboard, and it is Running. while access the proxy I get the error
`
Error: 'Internal Privoxy Error'
Trying to reach: 'https://10.244.0.17:8443/'
`
How to do?

**Comment by sftim** [comment]
Is there a page on https://kubernetes.io/ that isn't right? If so, which page is that?

/triage needs-information
