### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/service-access-application-cluster/

### ISSUE THREAD

**Issue by anadon** [kubernetes/website#12278]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Ran into the following while following the tutorial:
```
$ kubectl run hello-world --replicas=2 --labels="run=load-ballancer-example" --image=gcr.io/google-samples/node-hello:1.0 --port=8080
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/hello-world created
```

**Proposed Solution:**
I'm just starting, so I don't know.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/

**Comment by DanyC97** [comment]
related to #12090 

/assign @DanyC97
