### ISSUE TITLE
Issue with k8s.io/docs/setup/on-premises-metal/krib/

### ISSUE THREAD

**Issue by svallebro** [kubernetes/website#12291]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
Link to digtialrebar/provision issue page is miss wrong. 

**Proposed Solution:**
Update link to:
https://github.com/digitalrebar/provision/issues

**Page to Update:**
https://kubernetes.io/docs/setup/on-premises-metal/krib/

**Comment by oussemos** [comment]
Fixed with #12292 
/close
