### ISSUE TITLE
clarify kubelet upgrade process

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#12326]
Follow up from https://github.com/kubernetes/website/pull/11060, tracked in https://github.com/kubernetes/website/issues/12329

Upgrade process for `kubelet` is not sufficiently clear in user-facing documentation:
- [ ] add details to kubelet upgrade procedure (whether drain is required, whether skip-level kubelet upgrades are supported, etc) @kubernetes/sig-node-pr-reviews @kubernetes/sig-storage-pr-reviews 

**Page to Update:**
https://kubernetes.io/docs/setup/version-skew-policy/

**Comment by liggitt** [comment]
> Is this about in-place updates of the kubelet?

Yes

> Do the kubeadm upgrade tests cover that scenario?

I don't know. @kubernetes/sig-cluster-lifecycle, @kubernetes/sig-testing?

**Comment by neolit123** [comment]
> Do the kubeadm upgrade tests cover that scenario?

yes, but our tests are failing due to problems with the upgrade framework in k/k (e.g. ginkgo skipping); possibly some other reasons too. the current tests are pretty much unmaintained and there are plans to replace them with something else next cycle, hopefully.

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-13/#drain-control-plane-and-worker-nodes

we do recommend draining in our 12 -> 13 upgrade process.
skipping minor versions is not claimed as unsupported.

**Comment by liggitt** [comment]
`cordon -> drain -> upgrade kubelet -> uncordon` is the informal guidance I've seen until now. There may be other deployment-specific reasons to destroy and rebuild nodes (node-level improvements that only take effect for new nodes), but from the kubelet's perspective, drain has been sufficient, as far as I know.

**Comment by bowei** [comment]
cc: @freehan

**Comment by liggitt** [comment]
There is evidence of users upgrading kubelets between minor versions without draining pods (https://github.com/kubernetes/kubernetes/issues/84443). If that is required, the kubelet upgrade docs need to be made explicit.

**Comment by BenTheElder** [comment]
Is it required? Do we have a formal decision on that?

**Comment by dlipovetsky** [comment]
Please, let also us address whether drain is required when upgrading between _patch_ versions, e.g., 1.17.0 to 1.17.1. These upgrades are, arguably, more frequent than upgrades between _minor_ versions, and therefore users have a greater incentive to skip drain.

**Comment by neolit123** [comment]
WRT workload stability, the process is the same for PATCH iterations, so a drain would be required there too. one potential difference with MINOR updates is the CPU checkpoint format of the kubelet is not supposed to change on PATCH iterations.

**Comment by liggitt** [comment]
/assign @derekwaynecarr 

routing to sig-node leads

**Comment by sjenning** [comment]
My opinion, a cordon -> drain -> upgrade -> uncordon path is the safest thing to document for all situations.   We _should_ be able to do patch level upgrades (z-stream, in x.y.z) without draining but, imho, there is no point in complicating the guidance.

**Comment by dchen1107** [comment]
cordon -> drain -> upgrade kubelet -> uncordon is the only path supported by SIG Node today. In the past, there were efforts to do in-place upgrade kubelet, including containerized kubelet by CoreOS team to simplify the upgrading flow, but none of them are officially supported by the community. 

Let's make the upgrade flow explicit in the doc for now, but open for the enhancement.

**Comment by dlipovetsky** [comment]
Now that it's official, I'll work up a docs PR :slightly_smiling_face:

**Comment by liggitt** [comment]
> cordon -> drain -> upgrade kubelet -> uncordon is the only path supported by SIG Node today

Opened https://github.com/kubernetes/website/pull/26098 to update the doc.

The cluster-upgrade doc already included this information

> For each node in your cluster, [drain](/docs/tasks/administer-cluster/safely-drain-node/)
> that node and then either replace it with a new node that uses the {{< skew latestVersion >}}
> kubelet, or upgrade the kubelet on that node and bring the node back into service.
