### ISSUE TITLE
clarify kube-controller-manager/kube-scheduler skew support and upgrade order

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#12323]
Follow up from https://github.com/kubernetes/website/pull/11060, tracked in https://github.com/kubernetes/website/issues/12329

Supported skew and upgrade order for kube-controller-manager/kube-scheduler is not clear in user-facing documentation:
- [ ] is a specific upgrade order between `kube-controller-manager` and `kube-scheduler` required? @kubernetes/sig-api-machinery-pr-reviews, @kubernetes/sig-scheduling-pr-reviews

**Page to Update:**
https://kubernetes.io/docs/setup/version-skew-policy/

**Comment by lavalamp** [comment]
The scheduler is a controller. There should not be an ordering requirement; it's easy to imagine ways of getting an ordering requirement, but I consider them all to be bugs (e.g., scheduler depends on semantics of a particular controller at the same version).

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by shannonxtreme** [comment]
Reached out in #sig-scheduling chat to potentially get some movement on this and determine what update is needed (either clarify that upgrade order of `kube-controller-manager` and `kube-scheduler` doesn't matter, or clarify what the order should be)

/assign

**Comment by lavalamp** [comment]
Answer: there *must not* be a specific ordering needed between those two components. In practice, they get locks independently and the most common way of upgrading them (a VM at a time) means all four combinations of versions are possible, and a single upgrade could even see splits both ways.

**Comment by shannonxtreme** [comment]
Thanks @lavalamp!
