### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/assign-pod-node/

### ISSUE THREAD

**Issue by yogamayapatra** [kubernetes/website#12339]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi. Is there a part of the page at https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ that you think we can improve?
