### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by elnemesisdivina** [kubernetes/website#12335]
**Problem:**
root@photon-machine [ /etc/yum.repos.d ]# cat kubernetes.repo 
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
root@photon-machine [ /etc/yum.repos.d ]# yum install -y kubectl

Installing:
kubectl                  x86_64       1.13.2-0         kubernetes    37.43M 39252360

Total installed size:  37.43M 39252360

Downloading:
Error(1508) : GpgKey Url schemes other than file are not supported

**Comment by thecrudge** [comment]
Not an issue with the documentation. I just literally copy and pasted the commands -

result:

Installed:
  kubectl.x86_64 0:1.14.1-0

/close

**Comment by thecrudge** [comment]
/assign @jimangel 

Please review and close
