### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by mr007** [kubernetes/website#12330]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
kubectl proxy just sits after stating starting proxy on port 8001

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by rmarcum** [comment]
It seems to be missing a step where you open a new terminal window to run the proxy command in.

**Comment by BenHall** [comment]
Thanks @tddorgtfo. Indeed it is expected but can be confusing. We've added a echo statement beforehand which will hopefully help.

![Screenshot 2019-06-24 09 23 14](https://user-images.githubusercontent.com/82614/60003048-cc97b800-9661-11e9-9218-38f14ef90a0e.png)

However if anyone has any other suggestions or ideas then please send us a PR. The commit was https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/9533b7b7d7e72063742d8a08c2c0bb0c32ab62d5

**Comment by thecrudge** [comment]
This issue has been addressed and is safe to close

/close
