### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/service/

### ISSUE THREAD

**Issue by kevingimbel** [kubernetes/website#12341]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I believe the text is wrong at https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws, it reads

> The first specifies the ARN of the certificate to use. It can be either a certificate from a third party issuer that was **uploaded to IAM** or one created within AWS Certificate Manager.

As far as I know the third party certificates are uploaded / imported to AWS Certificate Manager and not to AWS IAM. 

Please also see the AWS docs at https://docs.aws.amazon.com/acm/latest/userguide/import-certificate.html as reference.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/#ssl-support-on-aws

**Comment by sftim** [comment]
AWS [supports](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html#upload-server-certificate) uploading certificates to IAM.

AWS does recommend using ACM; however, both methods work.

**Comment by kevingimbel** [comment]
Oh i see! I didn't know you could upload certificates to IAM.

> AWS does recommend using ACM; however, both methods work.

If AWS recommends using ACM why would you recoomend AMI? Is there any benefit of using AMI over ACM? As far as I could see the required files are the same.

**Comment by sftim** [comment]
This might be a good one to take to the AWS forums? [I believe that] Kubernetes as a project doesn't have strong opinions on different AWS technologies.
