### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by SalimGangji** [kubernetes/website#12366]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
minor documentation bug in the install notes for CentOS/RHEL/Fedora
you need to load the br_netfilter module into the kernel before the two kernel parameters can be set by sysctl on centos
- net.bridge.bridge-nf-call-ip6tables
- net.bridge.bridge-nf-call-iptables

**Proposed Solution:**
one extra step, running:  
`modprobe br_netfilter`
is needed
before writing parameters into `/etc/sysctl.d/k8s.conf` and running `sysctl --system`

**Page to Update:**
https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by SalimGangji** [comment]
Hi Lubomir!

Sorry for the long delay before my reply!

Regarding your question about release and version, I am running CentOS 7.6
based on the CentOS-7-x86_64-GenericCloud-1809.qcow2
<https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1809.qcow2>
 image

[centos@instance00009 ~]$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

[centos@instance00009 ~]$ uname --kernel-version
#1 SMP Thu Nov 29 14:49:43 UTC 2018

[centos@instance00009 ~]$ uname --kernel-release
3.10.0-957.1.3.el7.x86_64

Unfortunately I do not know what kernel modules are pre-loaded into the
kernel based on distribution but after doing some googling I have
discovered that the kmod utility can be used to determine if a particular
module is loaded or not.

Perhaps including a kmod list | grep "br_netfilter" check as the first step
to determine if the module is already loaded would be an appropriate
addition to the document, if you feel the document needs to be changed at
all?

If not I can close the documentation bug if you feel it's not necessary to
add this check into the document. Please let me know your thoughts :)

check to see if module is present - below we can see it is not
[root@instance00009 ~]# kmod list | grep "br_netfilter"

loading the module
[root@instance00009 ~]# modprobe br_netfilter

check again to see if module is present - this time it is
[root@instance00009 ~]# kmod list | grep "br_netfilter"
br_netfilter           22256  0
bridge                151336  1 br_netfilter

**Comment by neolit123** [comment]
i think modules vary a lot by distro.

so i think we can add a note about `kmod list ...` or `modproble` in the docs, yes.
will add this to my TODO.

**Comment by SalimGangji** [comment]
Fantastic, do I need to update anything in git on my end? Such as adding
the kmod list command to the proposed solution, or has this email thread
captured all the relevant details already?

**Comment by SalimGangji** [comment]
Sure thing, I can try to do a pull request, do you think it would be appropriate to surround your line above in a {{< note >}}...{{< /note >}} block?

**Comment by neolit123** [comment]
i don't think the extra `/note` is need.

saw the commit you created in your fork, please :
- make sure there is a `.` at the end of the sentence.
- don't include references in the commit to this issue (in title and PR body)
just add `Fixes #12366` in the PR body.

thanks.

**Comment by SalimGangji** [comment]
Will delete my repo and re-fork the main repo and make the changes as you
have suggested then submit a pull request

Thank-you!!

**Comment by SalimGangji** [comment]
Hi Lubomir,

I've submitted PR #12419 for this, thank you!

Cheers,

Salim
