### ISSUE TITLE
Pod status document

### ISSUE THREAD

**Issue by paralika** [kubernetes/website#12389]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
There are a couple of pod status, I think, haven't documented. If you see the below example for `nginx` pod which runs for 10 seconds and terminates. 

```
$ kubectl get pods --watch -o wide
NAME      READY     STATUS             RESTARTS   AGE       IP            NODE      NOMINATED NODE
nginx     0/1       CrashLoopBackOff   12         43m       192.168.2.5   node03    <none>
nginx     1/1       Running   13        44m       192.168.2.5   node03    <none>
nginx     0/1       Completed   13        44m       192.168.2.5   node03    <none>
nginx     0/1       CrashLoopBackOff   13        45m       192.168.2.5   node03    <none>
```

**Proposed Solution:**
Please document `CrashLoopBackOff` and `Completed` pod status. 

**Page to Update:**
It should be somewhere here:
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

**Comment by MAKOSCAFEE** [comment]
@paralika I think #12397 fixed this issue ... can this be closed?

**Comment by paralika** [comment]
@MAKOSCAFEE thank you for a fix. I have one query regarding:

`CrashLoopBackOff | This means that one of the containers in the pod has exited unexpectedly, and perhaps with a non-zero error code even after restarting due to restart policy.`

Event though the pod is completed without any error it is going into `CrashLoopBackOff` state.
