### ISSUE TITLE
Formalize docs release strategy with the different localization owners.

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#12396]
Hey 👋 - I'm Jim Angel, the sig-docs release lead for v1.14. I'm opening this issue to find the best way to coordinate the actual docs release (scheduled tentatively for March 25th) with the different localization owners.

A couple Questions:

1. Who would be a good primary contact for the following repos?
- [X] Chinese: rui (Slack)
- [X] Japanese: cstoku (Slack)
- [X] Korean: june.yi (Slack)

2. Is there anything we could have done better last release (v1.13)?

3. I am working on a guide to document the responsibilities of the sig-docs lead (me), do we have the localization release process documented anywhere for your repository? If not, will someone please coordinate with me on creating one?

I look forward to working with everyone! Let me know if you have any questions! Thanks!

cc: @kubernetes/sig-docs-zh-owners @kubernetes/sig-docs-ko-owners @kubernetes/sig-docs-ja-owners @ClaudiaJKang @bradtopol @chenopis @chenrui333 @cstoku @dchen1107 @gochist @haibinxie @hanjiayao @ianychoi @lichuqiang @lucperkins @markthink @nasa9084 @tengqm @tnir @xiangpengzhao @zacharysarah @zhangxiaoyu-zidif 

cc: @tfogo @zparnold

**Comment by gochist** [comment]
Hi! :wave: my answers for the questions:

1. For Korean l10n, please contact me, june.yi on the Slack. 
2. For the last release(v1.13), we merged our working branches(`dev-1.13-ko.1` ~ `dev-1.13-ko.3`) to `dev-1.13` branch. And it caused multiple language changes in a single commit when it merged to the `master`. So we, Korean l10n team will not touch the upstream's next branch(currently `dev-1.14`).
3. I think we are following the [Localizing Kubernetes Documentation](https://kubernetes.io/docs/contribute/localization/). For the additional details, we usually set new team milestone every two weeks. The 14 days of cycle includes 3 days of code freezing. When we move forward to the next milestone, we merge the current development branch(currently `dev-1.13-ko.5`) to the master branch which will be eventually merged to the current release branch(currently `release-1.13`). And then we find out outdated contents using a [script](https://gist.github.com/gochist/8654460717b4bbb4ac490dda79a547fa) and create an issue to update them.

**Comment by cstoku** [comment]
Hi :wave:  - My answers about the questions

1. Please contact me for Japanese l10n. cstoku on the slack.
2. Nothing particularly since we are in the process of the first translation work. ([dev-1.13-ja.1](https://github.com/kubernetes/website/milestone/27))
3. We are following the [Localizing Kubernetes Documentation](https://kubernetes.io/docs/contribute/localization/) too. So currently we don't document the release process of Japanese l10n team.

**Comment by jimangel** [comment]
/close

I will reach out on slack as we near the end of the release. Thank you for the prompt feedback!
