### ISSUE TITLE
Clarify documentation for kubectl completion for Bash and macOS

### ISSUE THREAD

**Issue by weibeld** [kubernetes/website#12405]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The documentation [here](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion) does not clearly reflect the situation about Bash completion and macOS. It leads to issues like [here](https://github.com/kubernetes/kubectl/issues/37) and [here](https://github.com/kubernetes/kubernetes/issues/27876) that have been closed without resolution.

Similar requests for improvement are #11022 or #8221, but got no attention.

There are several points that should be stated more clearly:

1. macOS by default includes Bash 3.2 and the `kubectl` completion script does **not** work properly with Bash 3.2 (tabbing in a `kubectl` command always only outputs the top-level sub-commands, no matter what has been typed so far). The `kubectl` completion script requires Bash 4.1+. So, if you really want to use `kubectl` Bash completion, you have to upgrade Bash to 4.1+ (as for example described [here](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)).
2. The `kubectl` completion script depends on functions defined in the [bash-completion](https://github.com/scop/bash-completion) project, which can be installed with Homebrew. But it has two versions, `bash-completion` for Bash 3.2 and `bash_completion@2` for Bash 4.1+.
3. The `kubernetes-cli` Homebrew formula installs the `kubectl` completion script to `/usr/local/etc/bash_completion.d`. This worked well with the `bash-completion` Homebrew formula on Bash 3.2  since it sources all files in this directory. So, if you installed both, `bash-completion` and `kubectl` with Homebrew, you didn't need to take any further actions for `kubectl` completion to work. However, `bash-completion@2` does not source files in that directory anymore (discussion [here](https://github.com/Homebrew/homebrew-core/issues/36377)), so you have to source the `kubectl` completion script yourself in your `~/.bashrc` file (either the one from `/usr/local/etc/bash_completion.d` or the output of `kubectl completion bash`). 

These two cases (Bash 3.2 vs. Bash 4.1+ and `bash-completion` vs. `bash-completion@2`) are not clearly described in the documentation. Furthermore, since `kubectl` completion doesn't work with Bash 3.2, the first case (Bash 3.2 and `bash-completion`) is a non-solution anyway, and only the second case (Bash 4.1+ and `bash-completion@2`) really works.

**Proposed Solution:**

Structure the documentation as follows:

`kubectl` Bash completion depends on two things:

- Bash 4.1+
- [`bash-completion@2`](https://github.com/scop/bash-completion)

Setup:

1. Upgrade to Bash 4.1+
    - Link to some instructions
2. Install *bash-completion*
    - With Homebrew:
        - `brew install bash-completion@2`
        - Add snippet shown in the "Caveats" section of the output of `brew install` to your `~/.bash_profile` or `~/.bashrc`\* file (setting `BASH_COMPLETION_COMPAT_DIR` variable to `/usr/local/etc/bash_completion.d` and sourcing `bash_completion.sh` script).
    - Or install it in any other way
3. Make sure the `kubectl` completion script gets sourced
    - If you installed both `bash-completion` and `kubectl` with Homebrew *and* you set the `BASH_COMPLETION_COMPAT_DIR` variable (see above), then everything should be already fine. The `kubectl` Homebrew formula put the `kubectl` completion script in `/usr/local/etc/bash_completion.d` and all files in this directory are sourced by `bash-completion` (because you set the `BASH_COMPLETION_COMPAT_DIR` variable to this directory).
    - Otherwise, to source the `kubectl` completion script explicitly, you can just add the following to your `~/.bashrc`:
        ~~~bash
        source <(kubectl completion bash)
        ~~~

The other option with Bash 3.2 and `bash-completion` should be marked as obsolete.

\* Note: the output of `brew install` says to add the code snippet to your `~/.bash_profile` (not `~/.bashrc`). That's possible too, but then `bash-completion` will not be available in sub-shells (i.e. a shell that you start within another shell by typing `bash`). On the other hand, if you add the snippet to `~/.bashrc`, then `bash-completion` will be available in all sub-shells, but you have to make sure that you source your `~/.bashrc` from your `~/.bash_profile` file, so that `bash-completion` is also available in login shells (i.e. the shells that you *don't* start within another shell). 

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion

**Comment by xilopaint** [comment]
Thanks for this issue. It helped me to understand why bash-completion wasn't working to me.

> * Add snippet for sourcing `bash_completion.sh` to your `~/.bashrc`, as indicated in the output of the `brew install` command

The output of the `brew install` command mentions `~/.bash_profile`, not `~/.bashrc`.

> * Or, if you want, you can have a snippet like the following in your `~/.bashrc` to automatically source all the files in `$(brew --prefix)/etc/bash_completion.d`:
>   ```shell
>   for f in $(brew prefix)/etc/bash_completion.d/*; do
>       source "$f"
>   done
>   ```

Please, edit the snippet with `--prefix` instead of `prefix`.

**Comment by weibeld** [comment]
Good that it helped you!

You could source the file in `~/.bash_profile`, but then `bash-completion` probably won't be available in a sub-shell (that is, when you start a new shell by typing `bash`). This is because `~/.bash_profile` is sourced only by login shells (i.e. the first shell you start), but not by shells that you start within this shell. On the other hand, `~/.bashrc` is sourced by all interactive shells (i.e. shells that you start within another shell).

So, if you source it in `~/.bashrc`, and you source your `~/.bashrc` in your `~/.bash_profile` (which most people do), then it will be available in all shells.

But it's up to everybody how to manage these files.

I fixed the typo, thanks.

**Comment by xilopaint** [comment]
Sorry, I had deleted my comment before your last one as I realised that I can get the scripts in `$(brew --prefix)/etc/bash_completion.d/` sourced just by adding `export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"` to `~/.bash_profile` so your snippet wasn't necessary.

**Comment by weibeld** [comment]
That's true, and this seems to be the right way to do it at the moment. So, I adapted my initial post.

The note about that in the output of `brew install` is new, it has been added in [this commit](https://github.com/Homebrew/homebrew-core/commit/c08cf79e21a1df6b1c211755e5ec7a2aad4b6ca0) from 30 Jan 2019. The author probably added this following a discussion about this that we had [here](https://github.com/Homebrew/homebrew-core/issues/36377#issuecomment-457765302).

**Comment by DanyC97** [comment]
@weibeld are you planning to put your proposed solution in a PR ? 

_also thank you for revive this topic_

**Comment by weibeld** [comment]
@DanyC97 if a PR is appreciated, then I can do it, yes 👍

**Comment by DanyC97** [comment]
💯 is appreciated, we welcome everyone to come forward and help out

**Comment by weibeld** [comment]
Fixed in merged PR #13060.
