### ISSUE TITLE
Docs for Running Windows Containers in Kubernetes

### ISSUE THREAD

**Issue by craiglpeters** [kubernetes/website#12426]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The ability to run Windows Containers in Kubernetes is moving towards GA in 1.14 (or possibly 1.15). Windows Containers aren't identical to Linux containers. They have their own limitations and require Windows nodes. The GA release will not run all Kubernetes services on Windows, so mixed Operating System clusters are required with Kubernetes Master running Linux. The documentation implications are significant since running mixed Operating System clusters is not currently covered.

This issue exists to discuss the best approach to addressing the potentially very broad impact on documentation.

**Proposed Solution:**
At least two major use cases need to be addressed:
1. New K8s operators creating clusters to run Windows Containers they've been running in some other way
Those new to K8s need to understand how to stand up a mixed operating system cluster from scratch, and how to get their Windows Containers scheduled on the right nodes.

1. K8s operators with an existing K8s cluster who want to run both Linux and Windows containers
Experienced K8s operators need to be educated about the limitations of Windows Containers, the variants on the user experience, how to add Windows nodes to their clusters, and how to get Linux and Windows containers to run on the right nodes and communicate with each other.

The proposal is to start by writing monolithic documentation addressing these two use cases first, and then to determine how to land it in the documentation. The alternative is to assess which existing docs need updates, and then plan those.

**Page to Update:**
https://kubernetes.io/... too many to list

Kubernetes Version:1.14

Additional Information:

- [KEP For Windows Nodes in Kubernetes](https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190103-windows-node-support.md) which includes some bullet points about topics to include in documentation
- [Enhancement Issue](https://github.com/kubernetes/enhancements/issues/116)
- [PR for Documentation of Windows in Kubernetes for 1.13](https://github.com/kubernetes/website/pull/10875)
 - [Kubernetes Windows Walkthrough](https://github.com/Azure/aks-engine/blob/master/docs/topics/windows.md)
- [Windows Containers Workshop](https://github.com/vyta/windows-containers-workshop/tree/kubernetes/labs)

**Comment by jimangel** [comment]
My suggestion from the meeting today: It would be preferred to create a one or two page document that covers the "bulk" of your solutions. We would merge it in with our dev-1.14 branch upon release. I would recommend against touching a ton of minor docs until the k8s release has landed and those updates could be done in master.

The reasoning behind this is because we merge master periodically into dev-v1.14 and, with that, we need to resolve any conflicts. If your windows docs touch a ton of pages it will make the process more prone to merge conflicts / resolutions.

The minor updates (many pages) could be identified and made in master (hours) after we merge dev-1.14 w/ release (tentative 3/25).

**Comment by jfrappsdocs** [comment]
Do we want to continue to hide the Windows docs from the TOC? Or should we think of new information architecture for them based partly on finding the right place for them in a visible tree? (Assuming a standalone doc or docset at least for 1.14/1.15)

**Comment by craiglpeters** [comment]
Please take a look at the [draft outline](https://docs.google.com/document/d/1a2bRd7PZXygIEm4cEcCeLXpEqJ7opakP_j4Pc6AJVYA/edit?usp=sharing) (also circulated via the mailing list)

**Comment by craiglpeters** [comment]
[Here is placeholder PR](https://github.com/kubernetes/website/pull/12929) for the changes to docs

**Comment by michmike** [comment]
documentation is now up and running.
You can view it in staging under https://5c914f680410ed000aeebc2e--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/add-windows-nodes/
/close
