### ISSUE TITLE
ZH-Need a live update?

### ISSUE THREAD

**Issue by xichengliudui** [kubernetes/website#12442]
**This is a...** 
- [x] Feature Request

**Problem:**
https://github.com/kubernetes/website/pull/12438/files  the docker version has been updated, 
Do we need to update? https://github.com/kubernetes/website/blob/release-1.12/content/zh/docs/setup/cri.md

**Proposed Solution:**

**Page to Update:**
https://github.com/kubernetes/website/blob/release-1.12/content/zh/docs/setup/cri.md

**Comment by xichengliudui** [comment]
@tengqm

**Comment by tengqm** [comment]
@xichengliudui need to check whether the version changes was to 1.13 or 1.12 and then decide to which branch this should go.

**Comment by xichengliudui** [comment]
thanks
