### ISSUE TITLE
ko: Translate docs/home/_index.md in Korean

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#12447]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
[docs/home/_index.md](https://github.com/kubernetes/website/blob/dev-1.13-ko.6/content/ko/docs/home/_index.md) not translated to Korean.

**Proposed Solution:**
Translate [docs/home/_index.md](https://github.com/kubernetes/website/blob/dev-1.13-ko.6/content/ko/docs/home/_index.md) in Korean.

**Page to Update:**
https://kubernetes.io/...

**Comment by gochist** [comment]
@ClaudiaJKang Will you just translate `/content/ko/docs/home/_index.md`in Korean or make i18n support version of  `layouts/docs/docsportal_home.html` for this issue?

**Comment by ClaudiaJKang** [comment]
@gochist I just translate `/content/ko/docs/home/_index.md` in Korean.
