### ISSUE TITLE
Translate tutorials/stateful-application/mysql-wordpress-persistent-volume in Korean

### ISSUE THREAD

**Issue by yoonian** [kubernetes/website#12451]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
no tutorials/stateful-application/mysql-wordpress-persistent-volume.md in Korean

**Proposed Solution:**
Translate tutorials/stateful-application/mysql-wordpress-persistent-volume.md in Korean

**Page to Update:**
https://kubernetes.io/ko/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume

/language ko

**Comment by yoonian** [comment]
제가 작업하겠습니다 :)

**Comment by gochist** [comment]
fixed by #13516
/close
