### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/static-pod/

### ISSUE THREAD

**Issue by AlexDiamanti** [kubernetes/website#12467]
Needed more info in the docs.

**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
What happens and how it is different when you create a pod from kubectl create -f POD_FILE.yaml

It's not static. Seems like it's different from pods controlled by the services in terms of how psp gets applied.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
If this page explained that static pods would be created regardless of all admission controllers (and gave `PodSecurityPolicy` as an example), would that resolve this issue?

**Comment by AlexDiamanti** [comment]
My understanding that kubelet also needs to restart static pod if somehow was an issue with the scheduling (node was not ready, psp was not allowing, etc).  It's just could be broken in the current versions according to that:  https://github.com/kubernetes/kubernetes/pull/73309

Would be nice to have more details there...

**Comment by sftim** [comment]
Would it make sense to log an issue that calls for more detail, and hyperlink to the page with the extra detail once it exists?

**Comment by AlexDiamanti** [comment]
Sure
