### ISSUE TITLE
ko: Translate concepts/overview/working-with-objects/labels.md in Korean

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#12472]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
[concepts/overview/working-with-objects/labels.md](https://github.com/kubernetes/website/blob/dev-1.13-ko.7/content/en/docs/concepts/overview/working-with-objects/labels.md) not translated to Korean.

**Proposed Solution:**
Translate [concepts/overview/working-with-objects/labels.md](https://github.com/kubernetes/website/blob/dev-1.13-ko.7/content/en/docs/concepts/overview/working-with-objects/labels.md) in Korean.

**Page to Update:**
[https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
)

**Comment by dangen-effy** [comment]
[Task list]

* [ ] translations for [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) section
* [ ] translations for [Motivation](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#motivation) section
* [ ] translations for [Syntax and character set](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) section
* [ ] translations for [Label selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors) section
* [ ] translations for [API](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api) section
