### ISSUE TITLE
Issue with k8s.io/docs/home/

### ISSUE THREAD

**Issue by RaviSaraswathi** [kubernetes/website#12482]
**This is a...** 

- [ ] Feature Request
- [ yes] Bug Report

**Problem:**
Search is showing up few results after few searches - using search text box located in kubernetes.io documentations. 

How to recreate?
- Search a word in search text box , Example: command tasks
initial search results shows more than 1000 results. After few times repeating the same search , the results shows only 6 results !. 

**Proposed Solution:**

> 

**Page to Update:**
https://kubernetes.io/docs/home/ - search box and results.

**Comment by oguzzkilic** [comment]
This is not a bug. [click here](https://developers.google.com/custom-search/docs/xml_results#automaticFiltering) for details.

**Comment by RaviSaraswathi** [comment]
Thanks. I have closed this.
