### ISSUE TITLE
Streamline and simplify SASS/CSS for the website.

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#12496]
### This is a...

- [x] Feature Request
- [ ] Bug Report

### Problem

The SASS and CSS for the website is haphazardly organized and implemented. It's not clear which files and/or attributes control site characteristics. 

For example, changing base font size for the website is prohibitively complex: https://github.com/kubernetes/website/pull/12368)

### Proposed Solution

We need straightforward, easily discoverable SASS for the website and its various areas.

1. Streamline and simplify SASS in:
   - https://github.com/kubernetes/website/tree/master/sass
   - https://github.com/kubernetes/website/tree/master/static/css
   - Anywhere else SASS or CSS is hiding in k/website

2. Work with stakeholders, especially @alexcontini and @kbarnard10 to make sure that changes make sense and have buy-in from folks affected by SASS changes.

/ref
- https://github.com/kubernetes/website/issues/10643
- https://github.com/kubernetes/website/issues/10644
- https://github.com/kubernetes/website/pull/12368

**Comment by Infi-Knight** [comment]
Hi, my name is Ravi Soni. I have experience in frontend technologies and would love implementing the proposed solution under gsoc this year.  How do I get started getting comfortable with the task mentioned?

**Comment by Sai-Adarsh** [comment]
Hey @zacharysarah , I'm [Sai Adarsh S](http://sai-adarsh.github.io) interested in working with [Streamline and simplify SASS for the Kubernetes website](https://github.com/cncf/soc#streamline-and-simplify-sass-for-the-kubernetes-website) as a part of **GSoC 2019**. I'm a Full-stack developer proficient in HTML, CSS, JS, Django, Python, Node.js & containers. Having said that I’m looking forward to contributing, Any pointers on what should I work on or how should I be proceeding next?
