### ISSUE TITLE
reference documentation automation updates

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#12503]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The reference section of kubernetes.io/docs is generated using a number of scripts and tools. The reference guides generation task is separate from the main k8s/docs generation workflow. Code and scripts for the reference process can be found under the following repos : 
 - https://github.com/kubernetes/website/tree/master/update-imported-docs
 - `kubernetes-incubator/reference-docs`
 - `kubernetes/kubernetes`

`Key technologies used in the processes`:
OpenAPI, Go, Python, YAML, Markdown, Hugo templates, HTML
 
Currently, most of reference guides are generated once per release and typically there is post-processing where needed. The rendering process is not straightforward and the rendered output is varied. There are navigation and layout issues with a number of the reference guides and each guide is styled differently. 

**Proposed Solution:**
It would be a big improvement to fully automate the generation of the reference sections in a universal, extensible way. All tool component references and reference guides would use the same tools/scripts to generate the content. The generation scripts would incorporate coding best practices and define reusable templates to render the reference content. The reference guides generation task could be created as a sub-job in the overall docs workflow. The generated content would follow the k8s docs style guide and theme. New page layouts, as part of `kubernetes/website`, would be produced for the reference guides. The generation of the reference docs would be more closely coordinated with ks8/k8s component source updates.

- Update and create parsing and generation scripts to automatically produce k8s reference documentation
- Create custom templates, layouts for different reference guides
- Refresh organization of reference content where needed
- Other: automate feature gate options per component, option flags. Automate rendering of documentation for feature gates.

Overview of the current reference docs generation process:
https://kubernetes.io/docs/contribute/generate-ref-docs/

**Page to Update:**
https://kubernetes.io/docs/reference

**Comment by kbhawkey** [comment]
@zacharysarah

**Comment by zacharysarah** [comment]
**Note:** Code for API refdocs generation resides in https://github.com/kubernetes-incubator/reference-docs.

**Comment by Abhik1998** [comment]
I want to take up this task.

**Comment by Abhik1998** [comment]
All the reference scripts should be converted to a single segment.
The UI should be improved and I will go systematically by initially providing the UI then proceeding with API refdocs.

**Comment by siddsuresh97** [comment]
I am interested in taking up this task

**Comment by kbhawkey** [comment]
Closing this issue until further investigation.
