### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/names/

### ISSUE THREAD

**Issue by filmil** [kubernetes/website#12500]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
The description of an UID is kind of skimpy at https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids

**Proposed Solution:**
Would be nice to know when the object gets its UID, and what its lifecycle looks like.

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids

**Comment by sftim** [comment]
Thanks for the feedback
/language en
