### ISSUE TITLE
Confusion about Pod Security Policy ordering

### ISSUE THREAD

**Issue by tammersaleh** [kubernetes/website#12501]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order Says:

> In addition to restricting pod creation and update, pod security policies can also be used to provide default values for many of the fields that it controls. When multiple policies are available, the pod security policy controller selects policies in the following order:
>
> 1. If any policies successfully validate the pod without altering it, they are used.
> 1. If it is a pod creation request, then the first valid policy in alphabetical order is used.
> 1. Otherwise, if it is a pod update request, an error is returned, because pod mutations are disallowed during update operations.

I'm having trouble parsing this.  I could read this to mean either:

### Option A

> 1. If any policies successfully validate **an existing** pod without altering it, they are used.
> 1. **Otherwise**, if it is a pod creation request, then the first valid policy in alphabetical order is used.
> 1. Otherwise, if it is a pod update request, an error is returned, because pod mutations are disallowed during update operations.

...or...

### Option B

> 1. If any policies successfully validate the pod without altering it, they are used.
> 1. **However**, if it is a pod creation request, then the first valid policy in alphabetical order is used.
> 1. Otherwise, if it is a pod update request, an error is returned, because pod mutations are disallowed during update operations.

#6033 states it a bit differently:

> 1. PSPs which allow the pod as-is (no defaulting/mutating) are preferred
> 1. If the pod must be defaulted/mutated to be allowed, the first PSP (ordered by name) to allow the pod is selected
> 1. During update operations, when mutations to pod specs are disallowed, only non-mutating PSPs are used to validate the pod

Which is a bit more clear to me (implies option A)

Also, the third point "if it is a pod update request, an error is returned, because pod mutations are disallowed during update operations" is also confusing to me.  It implies that all update requests would be mutated by the PSP.  Maybe reword to "if it is a pod update request, and the PSP would mutate the pod, an error is returned, because pod mutations are disallowed during update operations"?

**Proposed Solution:**

Clarify the language like so:

> 1. PSPs which allow the pod as-is, without changing default or mutating the pod, are preferred.
> 1. If the pod must be defaulted or mutated, the first PSP (ordered by name) to allow the pod is selected.
> 1. During update operations (during which, mutations to pod specs are disallowed) only non-mutating PSPs are used to validate the pod.

(which is almost verbatim the language from #6033)

**Page to Update:**

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order

**Comment by php-coder** [comment]
/sig auth

CC @liggitt @tallclair

**Comment by SupriyaSirbi** [comment]
I am interested to work on this issue. Shall i submit a pull request for the same?

Thanks
