### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

### ISSUE THREAD

**Issue by priyesh16** [kubernetes/website#12528]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In file: https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

That said, each Pod in a Kubernetes cluster has a unique IP address, even Pods on the same Node, so there needs to be a way of automatically reconciling changes among Pods so that your applications continue to function.

**Proposed Solution:**
change
even Pods on the same node <to>
even amongst* Pods on the same node..

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@priyesh16 The original wording reads fine to me.
/language en
