### ISSUE TITLE
Issue with k8s.io/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by zerda** [kubernetes/website#12533]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
> If the client pod and server pod are in the same node, the client_address is the client pod’s IP address. However, if the client pod and server pod are in different nodes, the client_address is the client pod’s node flannel IP address.

From [Cluster Networking](https://kubernetes.io/docs/concepts/cluster-administration/networking/#kubernetes-model), all containers can communicate with all other containers without NAT. 

In this respect, the client_address should be always client pod's IP address, not the node flannel IP address, even the client pod and server pod are in different nodes.

I have tested in On-Premises Cluster (flannel / weave net), AKS and aliyun with 1.12. All backed my conclusion.

**Proposed Solution:**
The client_address is the client pod's IP address, whether the client pod and server pod are in the same node or not.

**Page to Update:**
https://kubernetes.io/docs/tutorials/services/source-ip/

1.12

**Comment by SupriyaSirbi** [comment]
I am interested to work on this issue. Shall i submit a pull request for the same?


Thanks

**Comment by zerda** [comment]
Close issue because PR has been merged.
