### ISSUE TITLE
HA etcd question

### ISSUE THREAD

**Issue by kostiley** [kubernetes/website#12547]
Hello!
I've configured 3 baremetal machines HA cluster as described in https://kubernetes.io/docs/setup/independent/high-availability/ 
"Stacked control plane and etcd nodes"

Now i have:
#kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
t-k8s-50   Ready    master   21m   v1.13.2
t-k8s-51   Ready    master   17m   v1.13.2
t-k8s-52   Ready    master   15m   v1.13.2

#kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok
controller-manager   Healthy   ok
etcd-0               Healthy   {"health": "true"}

So, i have a question - is it right, that i see only one etcd instance? 

Thx for help!

**Comment by neolit123** [comment]
if you do `kubectl get po --all-namespaces` do you see 3 etcd pods?

**Comment by kostiley** [comment]
Yes, there's 3 etcd pods

kube-system   etcd-t-k8s-50                      1/1     Running   1          3h34m
kube-system   etcd-t-k8s-51                      1/1     Running   0          3h30m
kube-system   etcd-t-k8s-52                      1/1     Running   1          3h28m

**Comment by neolit123** [comment]
the cluster seems healthy.

**Comment by kostiley** [comment]
In this case, how to view etcd status? Is it possible at all?

**Comment by neolit123** [comment]
yes it is. please read here:
https://coreos.com/etcd/docs/latest/v2/admin_guide.html

if you don't want to use `etcdctl` you can simply `curl -L <member-ip>:<port>/health` to get the status of each member.
if the health status is not `true` on any of your member, please bring down the cluster and try our guide again.

thank you
/close
