### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by ssunka** [kubernetes/website#12540]
Create container config error

**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
While creating this pod, I'm facing a create container config error
![screen shot 2019-02-07 at 7 59 42 pm](https://user-images.githubusercontent.com/2323921/52417923-ef8e5900-2b12-11e9-9817-59819b4bbbaa.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by daminisatya** [comment]
@ssunka Since this is a support request, you might get immediate help from the slack channel 

https://kubernetes.slack.com/messages/C09NXKJKA/
