### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by kaushikCanada** [kubernetes/website#12556]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
pods/storage/pv-pod.yaml has an extra indent under ports for containerport. 

**Proposed Solution:**
 i think - containerPort: 80 should start just below ports.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by iamneha** [comment]
I think indentation is correct here.
I check this on yaml checker as well and it is correct.

Have you faced any issue while creating pods using this yaml file?

**Comment by kaushikCanada** [comment]
I think u can close this.

Thanks,
Roy

**Comment by iamneha** [comment]
@Rajakavitha1 can you please close this issue

**Comment by Rajakavitha1** [comment]
Thanks for your update @imaneha
 /close
