### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by codeliger** [kubernetes/website#12554]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**

The documentation doesn't link to any of the deployment.yaml documentation and expects users to copy and paste something without knowing what it does.

**Proposed Solution:**
Link directly to the documentation on how to create a deployment.yml that specify what all the commands do in the script.

Even https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment does not give you a complete rundown of a deployment.

Where do i find the api? Where do i find the specification for how to create a deployment beyond the scope of an introductary deployment?

**Page to Update:**
k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

**Comment by DanyC97** [comment]
@codeliger you agree this is no longer an issue since yo uhave few options:

* backend deployment - `kubectl create -f https://k8s.io/examples/service/access/hello.yaml`
* frontend deployment - `kubectl create -f https://k8s.io/examples/service/access/frontend.yaml`

In addition you can also now do a wget on the files itself by copy the link from the table top corner

* `https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/service/access/frontend.yaml`

hth, if so pls close this issue otherwise let me know what else is missing

**Comment by codeliger** [comment]
This didnt solve the problem. Updated the proposed solution.

A good example is in the popular python framework called django:
https://docs.djangoproject.com/en/2.1/intro/tutorial01/#creating-a-project
The creating a project docuementation page links to the django settings page so people can learn more about django settings:
https://docs.djangoproject.com/en/2.1/topics/settings/#available-settings
The end of the settings page links to a page showing every avaliable setting, what it does and how to use it.

I have still not found documentation every keyword i can use in a deployment.yaml 
Linking to this documentation (if it exists) would be useful for people trying understand deployments in more detail.

**Comment by DanyC97** [comment]
i guess you are asking for https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#deployment-v1-apps?  if so then all this info can be accessed from https://kubernetes.io/docs/reference/kubernetes-api/

Are you saying that you would prefer to have a way to get from https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ to the more _advanced_ spec ?

**Comment by codeliger** [comment]
Yes that would make sense. I ended up looking for the kubernetes api but never found it. Its not clear the kubernetes api is the deployment api.
