### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/reconfigure-kubelet/

### ISSUE THREAD

**Issue by twosatnams** [kubernetes/website#12558]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation does not reflect the correct output to the following command 

```
kubectl get no ${NODE_NAME} -o json | jq '.status.config'
```

The documentation assumes that the output would contain the field `Node.Status.Config`. But `Node.Status` doesn't contain the `Config` field and only contains `addresses`, `allocatable`, `capacity` and `conditions`

**Proposed Solution:**
Update the documentation such it points to the locations where I can inspect `Config` of a Node.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/

**Comment by daminisatya** [comment]
@twosatnams 

The document shows the correct output if the Dynamic configuration has been setup as per the document. The Node.Status.Config object shows details via the ConfigMap saved in Kubernetes Control Plane and referenced by the node. 

If the node does not refer to a ConfigMap or does not have dynamic-config-dir configured, the Node.Status will not have a config object. @zacharysarah

**Comment by twosatnams** [comment]
Thanks @daminisatya you're right I figured it out - it was related to an issue with the cloud provider.
