### ISSUE TITLE
Add k8s youtube channel to the footer section of community page

### ISSUE THREAD

**Issue by daminisatya** [kubernetes/website#12560]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

Good to have k8s youtube channel linked in the footer section along with other community logos. 

<img width="837" alt="screen shot 1940-11-20 at 3 34 09 pm" src="https://user-images.githubusercontent.com/6227784/52519365-33eb3780-2c80-11e9-8ca9-126aeb671127.png">

**Proposed Solution:**

Necessary CSS and HTML changes have to be done to include the youtube icon in the footer section. Please make sure to attach screenshots of the footer section in 

- [ ] Mobile view
- [ ] Desktop view
- [ ] Tablet view 

To ensure proper testing of responsiveness. 

How to compile sass to css ?

Run the command ```scripts/sass.sh build``` within the website folder and make sure to include the generate css (compressed) files in the commit. 

How to test on different device views? 

Checkout this blog 😄 https://developers.google.com/web/tools/chrome-devtools/device-mode/

**Page to Update:**
https://github.com/kubernetes/website/blob/master/sass/_base.sass#L485
https://github.com/kubernetes/website/blob/master/sass/_desktop.sass#L212v
https://github.com/kubernetes/website/blob/master/layouts/partials/footer.html#L10
Update the social_sprite.png image to include youtube icon. 
https://github.com/kubernetes/website/blob/master/static/images/social_sprite.png

https://github.com/kubernetes/website/blob/master/sass/_tablet.sass#L221

**Comment by daminisatya** [comment]
This is a /good-first-issue 😄

**Comment by parispittman** [comment]
this is actually coming with the new community site design - will land within the next few weeks

**Comment by daminisatya** [comment]
@parispittman That's amazing! I joined the community a week back and I'm new. Where can I follow more on this change?

**Comment by daminisatya** [comment]
closing, since it will be resolved in the new community page design
