### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by NicolasRouquette** [kubernetes/website#12588]
How to cleanup kubectl

- [x] Feature Request
- [ ] Bug Report

**Problem:**

Someone may have installed kubectl before; however, there may be errors in `kubectl cluster-info`.
How can one cleanup everything to start fresh?

**Proposed Solution:**

Add instructions to cleanup existing configuration files:

`/bin/rm -rf ~/.kube`
`/bin/rm -rf ~/.minikube`

Check that `kubectl` can start:

`kubectl cluster-info`

should result in the following:

```
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sftim** [comment]
Would it be safer to move `~/.kube` and contents aside, rather than wiping it?

**Comment by iamneha** [comment]
I also faced the same issue and simply wiping minikube machine work for me
`rm -rf ~/.minikube/machines`

**Comment by iamneha** [comment]
Inside the kubectl configuration section, it is mentioned what to do when `kubectl is not correctly configured or not able to connect to a Kubernetes cluster`
I don't think we need to remove `~/.kube`

To connect to the k8s cluster we need a tool like minikube to be installed first and then re-run the commands.
If you have installed minikube before and when running `minikube start` is throwing an error `machine does not exist` then simply wipe existing configuration files for minikube.

@sftim what is your thought on this?

**Comment by sftim** [comment]
This task is about installing `kubectl`, and that doesn't have much bearing on Minikube or a similar thing that sets up a test cluster. The person reading this document might want to install `kubectl` so that they can deploy to a namespace, maybe even to access a production environment.

If we want to explain how to clean up after using minikube, and start afresh, that is also a task document. I think it makes sense for that to be an entirely separate document. The page on setting up `kubectl` is welcome to link there.
