### ISSUE TITLE
Improvement for k8s.io/docs/reference/access-authn-authz/abac/

### ISSUE THREAD

**Issue by poul22** [kubernetes/website#12587]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @poul22 
What improvement to this page did you have in mind?

**Comment by poul22** [comment]
no save change looking for day furste web traning
