### ISSUE TITLE
Glossary entry for lifecycle hooks somehow collides with container entry

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#12608]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
To see the symptoms, visit https://kubernetes.io/docs/reference/glossary/?all=true and mouse over the word “container” when it's used as a glossary reference.

You'll see that the tooltip in fact comes up with the text from the _container-lifecycle-hook_ entry. I replicated this in Firefox and in Brave, to rule out this being a browser-specific behaviour.

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?all=true

I looked at [`container-lifecycle-hooks.md`](https://github.com/kubernetes/website/blob/e986ee4cbc22d48d2169d7e920a77e45dc2eae65/content/en/docs/reference/glossary/container-lifecycle-hooks.md) and didn't see anything that looked wrong with it. However, renaming that file to `x-container-lifecycle-hooks.md` makes the symptoms disappear.

**Comment by daminisatya** [comment]
This is an interesting issue. I observed this for other terms as well. For example, Pod getting linked to Pod Priority. 

@zacharysarah

**Comment by lieut-data** [comment]
I ran into this as well. I believe the issue partially stems from the glob on the `term_id` in the corresponding shortcode:
https://github.com/kubernetes/website/blob/b1c288926b00198840ddd1a560845c29f04d4ef9/layouts/shortcodes/glossary_tooltip.html#L8

This allows `container*` to match `container-lifecycle-hooks` (similarly for `pod*`). `GetMatch` returns the first match, but I suspect the order of the glossary items may not put the desired `container` as the first defined term. It's unclear to me why the glob is specified with a `*` at all, unless in an attempt to allow `pod` to match `pods` (but that's an English-specific thing and wouldn't necessarily help other languages.)

I also note that something causes the inverse problem for pod lifecycle, which links back to `pod` instead. This may be related to the above.

![image](https://user-images.githubusercontent.com/1023171/54574023-19198a80-49c5-11e9-82f6-720f22d5daed.png)

**Comment by seokho-son** [comment]
@sftim, I opened a PR #14227 which is related with this issue.
The PR was merged already. So you can check this issue have been resolved.

**Comment by sftim** [comment]
This is fixed. Nice!
