### ISSUE TITLE
No kube-scheduler documentation

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/website#12609]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The standard kube-scheduler [docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/) and its [example](https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/) on how to specify your own are very out-of-date and lacking.

Since March 2018 (I believe that was 1.10?), the kube-scheduler has deprecated configuring it with flags/configmaps in favor of using a config file. Moreover, the algorithm provider (which determined the scheduling strategy: spreading pods out or stacking pods high in a few nodes) was replaced in favor of a policy file (e.g. https://github.com/kubernetes/examples/blob/master/staging/scheduler-policy-config.json) where a user would specify the filters and node priorities to use when determining where to place a pod. To the best of my knowledge, there is no documentation on what this config and policy files are, how they're written, what they hold, or examples of using/creating them. The current documentation just mentions the deprecated flag and the fact that there's a new config file where the old flags would go. The best my team could do was look at the source code, and examples provided by users in the github issues. The example is also a bit out-dated as I found that the demo needs additional rbac (ability to read storage classes) to function.

**Proposed Solution:**

It looks like we're going to need to write the documentation and examples for the new kube-scheduler from the ground up. I'd happily volunteer, but I honestly know very little of the inner workings of the scheduler or the full extent of the config and policy files. If we could get someone from the scheduling SIG pitch in, that would be amazing.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

1.11+

cc: @zacharysarah 
/sig scheduling

**Comment by zacharysarah** [comment]
@kubernetes/sig-scheduling-feature-requests 👋 It would be great to get input from you here. Thanks in advance!

**Comment by sftim** [comment]
#14637 is my crack at reworking an older PR on this

**Comment by sftim** [comment]
The report was that there was no documentation for kube-scheduler. #14637 added some, so this is now Done.
/close
