### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dns-pod-service/

### ISSUE THREAD

**Issue by sbrohi-att** [kubernetes/website#12631]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Currently, dnsPolicy can only be configured on a pod by pod basis. There needs to be a configuration where the DNS policy can be configured cluster-wide. For example, right now I am specifying that my pod dnsPolicy: Default, I'd like to see if there is a configuration available where I can apply that cluster-wide, so that when new pods get scheduled, they automatically obtain that configuration from the cluster instead of putting it in the pod spec on a pod-by-pod basis.

**Proposed Solution:**
Please allow dnsPolicy to also be applied cluster-wide.

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It sounds like you want to have a new feature in Kubernetes? If that's right, you can [raise an issue](https://github.com/kubernetes/kubernetes/issues/new/choose) against the Kubernetes repo.

For this case, I think you're asking for someone to implement an admission controller that adds the behaviour you have in mind.

**Comment by tengqm** [comment]
Right. This is not a doc issue.
