### ISSUE TITLE
The links of "codenew file=" in pages are error.

### ISSUE THREAD

**Issue by ping035627** [kubernetes/website#12639]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The links of "codenew file=" in pages are error. For example,
1) https://%!s()/blob/master/content/en/docs/tutorials/clusters/deny-write.profile
  error code: 404 (not found), linked from page(s):
  https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/
2) https://%!s()/master/content/en/examples/pods/security/hello-apparmor.yaml
  error code: 404 (not found), linked from page(s):
  https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/

**Proposed Solution:**
The pages can link normally.

**Page to Update:**
All links of "codenew file=" and "code language="text" file=".

**Comment by ping035627** [comment]
@Rajakavitha1

**Comment by sftim** [comment]
To see the fault, you can visit https://deploy-preview-12593--kubernetes-io-master-staging.netlify.com/docs/tutorials/clusters/apparmor/#example and either hover over or follow the link to the source code of the first YAML file: `deny-write.profile`

This should link to that profile so that you can download it; however, the link is broken.

**Comment by DanyC97** [comment]
i know how to fix it, i'm just waiting for an answer in sig-docs slack w.r.t some shortcodes files history

**Comment by tengqm** [comment]
I'm not sure we should ensure the links are correct during preview stage. However, any improvements to the code are welcomed.

**Comment by DanyC97** [comment]
> are correct during preview stage

sorry being novice here, what you mean by preview stage? the issue is present in the live docs as far as i can see, guess i'm missing something

**Comment by tengqm** [comment]
@DanyC97 The fix looks good anyway.
