### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by sgmacdougall** [kubernetes/website#12661]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The script contained in this document didn't work for me. Then I realised the certs I was creating 
all seemed to be for the same IP addresses, so they didn't work after copying them to the other hosts.
After running the 'kubeadm init phase certs' command in verbose mode I saw the following:

I0215 14:44:49.388535   12960 initconfiguration.go:169] loading configuration from the given file
I0215 14:44:49.389823   12960 interface.go:384] Looking for default routes with IPv4 addresses
I0215 14:44:49.389951   12960 interface.go:389] Default route transits interface "ens160"
I0215 14:44:49.390149   12960 interface.go:196] Interface ens160 is up
I0215 14:44:49.390273   12960 interface.go:244] Interface "ens160" has 1 addresses :[10.10.1.138/24].
I0215 14:44:49.390354   12960 interface.go:211] Checking addr  10.10.1.138/24.
I0215 14:44:49.390414   12960 interface.go:218] IP found 10.10.1.138
I0215 14:44:49.390477   12960 interface.go:250] Found valid IPv4 address 10.10.1.138 for interface "ens160".
I0215 14:44:49.390535   12960 interface.go:395] Found active IP 10.10.1.138 
I0215 14:44:49.390635   12960 version.go:163] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
I0215 14:44:49.881018   12960 feature_gate.go:206] feature gates: &{map[]}
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [markham-kube-etcd1 localhost hammer-kube-etcd1.xxxxxxx.xxx] and IPs [10.10.1.138 127.0.0.1 ::1]

So it looked like it was generating certs based on the interface IP. Since all the certs on are being created on the same host, the interface IP was always the same, so the certs were identical.

**Proposed Solution:**

I moved the kubeadm.cfg files I created of to the other hosts, then I created /etc/kubernetes/pki/etcd directories on the other hosts and copied over the ca.key and ca.crt files. Then I ran the 'kubeadm init phase certs' commands on each hosts.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/

Additional Information:

kubeadm version 1.13.3

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle 
/sig cluster-lifecycle

hello, this is the first report we are getting about this and this setup hasn't changed much between 1.13 and 1.12.
please double check if you are following the steps correctly.
