### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/access-cluster-api/

### ISSUE THREAD

**Issue by jvmirdel** [kubernetes/website#12662]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
This line is ambiguous
To get the library, run the following command: go get k8s.io/client-go/<version number>/kubernetes See https://github.com/kubernetes/client-go to see which versions are supported.
It is not clear what version number can be used.
Based on the matrics, trying things like 7.0 or 1.10 does not work and it is not clear how to figure out what should work, for the novice

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
This seems like a useful improvement to make
/kind feature
/language en
