### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by jerryduren** [kubernetes/website#12675]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
when I add the third control plane node, I always meet the following issue, It seems that there is no startup kubelet and etcd at all. I don't find kubelet process in linux

[certs] valid certificates and keys now exist in "/etc/kubernetes/pki"
[certs] Using the existing "sa" key
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[kubeconfig] Using existing up-to-date kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[etcd] Checking etcd cluster health
etcd cluster is not healthy: context deadline exceeded

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/priority awaiting-more-evidence

hello,

what kubeadm version are you using?

this document includes two methods: 1) stacked etcd 2) external etcd
k8s.io/docs/setup/independent/high-availability/

i'm going to assume you are doing 1).

> when I add the third control plane node, I always meet the following issue, It seems that there is no startup kubelet and etcd at all. I don't find kubelet process in linux

what is the output of `systemctl status kubelet`?

try waiting 2 minutes before calling `kubeadm join --experimental-control-plane` on the 2nd and then 3rd control planes.

> [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address

side note: you seem to be passing both bindPort and controlPlaneEndpoint. controlPlaneEndpoint is of the form `host:ip` and already includes a port.
