### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by sgmacdougall** [kubernetes/website#12709]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

The certs to copy need to be updated.

**Proposed Solution:**

It seems that the following need to be included in the certs to move to the other control plane nodes:

scp /etc/kubernetes/pki/apiserver-etcd-client.key "${USER}"@host:
scp /etc/kubernetes/pki/apiserver-etcd-client.key "${USER}"@host:

mv /etc/kubernetes/pki/apiserver-etcd-client.key "${USER}"@host:
mv /etc/kubernetes/pki/apiserver-etcd-client.key "${USER}"@host:

Also, 
scp /etc/kubernetes/pki/etcd/ca.key "${USER}"@$host:etcd-ca.key
and
mv /home/${USER}/etcd-ca.crt /etc/kubernetes/pki/etcd/ca.key 

can be removed because they don't exist.

**Page to Update:**
https://kubernetes.io/...

https://kubernetes.io/docs/setup/independent/high-availability/

1.13.3

**Comment by neolit123** [comment]
hello, what setup are you trying - stacked etcd or external etcd?
/sig cluster-lifecycle
/priority awaiting-more-evidence
