### ISSUE TITLE
Task topic - consistency around having full url to examples

### ISSUE THREAD

**Issue by DanyC97** [kubernetes/website#12740]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
There is inconsistency in the docs around the examples K8s manifest yaml files.

**Proposed Solution:**

In order to divide and conquer this issue will be used as a master tracking list for the [TASK](https://kubernetes.io/docs/tasks/) topic only.

#### Configure pods and containers
- [x] https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
- [x] https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

#### Administer a Cluster
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/ - split the kubectl get from create
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/ => move "more docs sentence under agent guide"
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/ => move to yaml instead of json
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/namespaces/ => move yo yaml vs json
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/static-pod/ => wget the spec file rather than EOF
- [ ] https://kubernetes.io/docs/tasks/administer-cluster/storage-object-in-use-protection/

#### Inject Data Into Application
- [ ] https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
- [ ] https://kubernetes.io/docs/tasks/inject-data-application/podpreset/

#### Run Applications
- [ ] https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/  => move the kubectl after the spec

change 

> In addition, the controller assigns each Pod a unique, stable name of the form <statefulset-name>-<ordinal-index>. In this case, that results in Pods named mysql-0, mysql-1, and mysql-2.

to 

> In addition, the controller assigns each Pod a unique, stable name of the form <statefulset-name>-<ordinal-index> which results in Pods named mysql-0, mysql-1, and mysql-2.

- [ ] https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/
- [ ] https://kubernetes.io/docs/tasks/run-application/configure-pdb/

#### Run Jobs
- [x] https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
- [x] https://kubernetes.io/docs/tasks/job/parallel-processing-expansion/
- [ ] https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/
- [x] https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/

remove the section about
> If you are working from the website source tree, you can go to the following directory and start a temporary Pod running Redis and a service so we can find it.

End user doesn't work from git repo

#### Access Applications in a Cluster
- [ ] ~https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/  => add full url to nginx.conf same like https://github.com/kubernetes/website/issues/12554~
- [ ] https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/ => change it to yaml definition
- [ ] https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/
- [ ] https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#yaml  => fix this page, there are few things in 

#### Monitor, Log, and debug  => ~fix the title, remove the comma before and~ -> *done*
- [ ] https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
- [x] https://kubernetes.io/docs/tasks/debug-application-cluster/debug-pod-replication-controller/
change 
> kubectl get nodes -o yaml | grep '\sname\|cpu\|memory'

to
> kubectl get nodes -o yaml | egrep '\sname:|cpu:|memory:'

- [x] https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/  => add note header. Fix the convention by removing `If` and turn it into a bullet box 

also turn each q on its own line
> Is the port you are trying to access in spec.ports[]? Is the targetPort correct for your Pods (many Pods choose to use a different port than the Service)? If you meant it to be a numeric port, is it a number (9376) or a string “9376”? If you meant it to be a named port, do your Pods expose a port with the same name? Is the port’s protocol the same as the Pod’s?

- [x] https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/ => can we move to yaml spec rather than json ? 
- [x] https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/  => add the log file path inside `` to improve visibility

#### Extend K8
- [ ] https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/  => add urls/ move files into examples dir etc
- [ ] https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

#### TLS
- [ ] https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/ -> moves files into examples dir

**Comment by sftim** [comment]
After reading this issue, I'm not sure what I could do to PR a fix / set of fixes.
Where docs are listed as with no specific comment, are changes needed?

**Comment by DanyC97** [comment]
yes, every chapter in the topic with the url provided does need fixes. 
I'll try to add more info on each of them. If you fancy helping can you also join sig-docs on slack and i can braindump more thoughts ?

**Comment by sftim** [comment]
_gets to sorting out a Slack invitation_

**Comment by DanyC97** [comment]
also we need to fix https://github.com/kubernetes/website/issues/12639 so will keep an eye on it and fix it as we get on 

@sftim if you fancy helping, you want to go over every single Task topic doc file and fix the above issue ? same issue across the entire doc code base

**Comment by sftim** [comment]
@DanyC97: if you want to nominate a few of these for me to work on, I'll do that (can make issues for the subtasks too). Then when I've got through those I can pick up new work.

**Comment by DanyC97** [comment]
cool, please go and pick a chapter @sftim , i'm now on _Monitor, Log, and debug_

**Comment by sftim** [comment]
I'll pick **Run Applications** then, so I start with a fairly small one.

**Comment by sftim** [comment]
I propose making this one `frozen` because it's worth doing, eventually.
