### ISSUE TITLE
Issue with k8s.io/docs/tasks/

### ISSUE THREAD

**Issue by jan-warchol** [kubernetes/website#12746]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
It seems this page was meant to be a table of contents, but there are no links to the actual content. It's also not aligned with what's in menu on the left.

**Proposed Solution:**
Add links to appropriate subpages.

**Page to Update:**
https://kubernetes.io/docs/tasks/

**Comment by DanyC97** [comment]
@jan-warchol regarding

>It's also not aligned with what's in menu on the left

are you referring to:
* the Tasks page headers are not in sync with the vertical left hand side list AND
* is not ordered in same way left hand side is ?
