### ISSUE TITLE
Issue with k8s.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

### ISSUE THREAD

**Issue by oksana664** [kubernetes/website#12756]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by DanyC97** [comment]
what is the problem here @oksana664 ?

**Comment by DanyC97** [comment]
@oksana664 due to lack of problem description i'm going to close the issue. Please open a new issue with full description as per the issue template so we understand what the problem is
