### ISSUE TITLE
Duplicated images across languages

### ISSUE THREAD

**Issue by bep** [kubernetes/website#12769]
Ref. the Italian version:

https://github.com/kubernetes/website/tree/master/content/it/_common-resources/images

Assuming that these images exist in the English version, they only need to be in the translated version if they somehow need to be changed per language. Doing a "copy-and-paste all" for every new language will create unneeded work if you for some reason want to change these graphics.

**Comment by kbhawkey** [comment]
@bep, can we close this issue? Thanks!
