### ISSUE TITLE
Improvement for k8s.io/docs/setup/independent/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by 4563453** [kubernetes/website#12764]
**This is a...** 

- [ X] Feature Request
- [ ] Bug Report

**Problem:**
missing command for fixing

**Proposed Solution:**
please add missing command fixing issue "TLS certificate errors"
export KUBECONFIG=/etc/kubernetes/admin.conf

**Page to Update:**
https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/#tls-certificate-errors

**Comment by neolit123** [comment]
the command is not exactly missing, as `$HOME/.kube/config` is also a search path, but if you set KUBECONFIG it will take precedence.

the troubleshooting tutorial assumes that you have not set KUBECONFIG, but if you have, you might
as well update it to another location.

free free to send a PR for this clarification if you want

/help
/kind cleanup
/priority backlog
/sig cluster-lifecycle
