### ISSUE TITLE
Move away from encouraging Deployment for additional schedulers

### ISSUE THREAD

**Issue by Adirio** [kubernetes/website#12785]
**This is a...** 
/sig scheduling
/kind feature

**Problem:**
Currently it is suggested in [Tasks/Administer a Cluster/Configure multiple schedulers](https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/#define-a-kubernetes-deployment-for-the-scheduler) ([source](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/administer-cluster/configure-multiple-schedulers.md#define-a-kubernetes-deployment-for-the-scheduler)) to deploy schedulers with a `Deployment` and disabling leader election.

Rolling updates of `Deployment`s may imply that multiple replicas of the scheduler are running concurrently and thus they can interfere each other as leader election was turned off.

**Proposed Solution:**
`StatefulSet`s or `Deployment`s with `Recreate` deployment strategy type would solve this issue. I personally prefer a `StatefulSet` as it:

1. Doesn't allow to swap the deployment strategy type afterwards.
2. Avoids creating an additional abstraction layer (`ReplicaSet`).
3. Enforces to use persistent volumes in case some volume wants to be used, which I think should be encouraged.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/#define-a-kubernetes-deployment-for-the-scheduler

**Comment by sftim** [comment]
If this guide were to recommend enabling leader election enabled, and explained why, would that make using a Deployment suitable / acceptable?

**Comment by Adirio** [comment]
In my opinion, leader election being false with a single replica is the right approach as the other way round would only mean additional overhead without any gain. In this case I don't see a Deployment fitting.

On the other hand if multiple replicas were to be deployed of the scheduler, leader election should be set to true. Leader election would mean the `Recreate` strategy argument is no longer valid. The second and third argument are not that important and thus the difference from a StatefulSet and a Deployment would be greatly reduced.

So in a HA scheduler with multiple replicas both StatefulSet and Deployment would be valid while in single instance schedulers without leader election StatefulSet should be prefered. I would also like to mention that for a HA replicated scheduler, a PodAntiAffinity to itself should be set in order to avoid collocating multiple replicas.

**Comment by sftim** [comment]
It sounds like we could decide between:
- illustrating using multiple schedulers, leaving aside topics such as HA so as to keep the page simple
   - and maybe signpost the reader to the HA topic for further reading
- demonstrating a recommended / good practise approach: multiple replicas for each controller type, leader elections, PodAntiAffinity, etc

and then tweak the document based on which approach we favor. Does that sound reasonable?

**Comment by Adirio** [comment]
I was sticking to the simple approach as that document is usually the starting point to extra-scheduler setups. In the simplest case a single instance with leader election disabled as it is now is enough. But with leader election turned off deployment's default rolling updates are dangerous and thats why I suggested to change to StatefulSet.

We could actually also add a comment at the end mentioning that to achieve scheduler resillience multiple replicas with leader election turned on and pod anti affinity to itself. In this complex case StatefulSets do not offer a lot over Deployemnts but they are also a nice fit so I would not mention switching to Deployment in this case (KIS).
