### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by dornah** [kubernetes/website#12811]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Following the Hello Minikube tutorial, at the Create a Minikube Cluster section (using Katacoda environment) I encounter these issues:

Step 2) When trying to launch the Kubernetes dashboard I see this error:

<img width="1235" alt="screen shot 2019-02-24 at 8 50 31 pm" src="https://user-images.githubusercontent.com/12002605/53297672-e2dd6500-3875-11e9-8f91-a75f43a03717.png">

Step 4) When entering the port 30000 I see this message:
<img width="1202" alt="screen shot 2019-02-24 at 9 16 36 pm" src="https://user-images.githubusercontent.com/12002605/53297904-83815400-3879-11e9-8799-ffb582678c9c.png">

**Comment by tengqm** [comment]
dup of #12968
