### ISSUE TITLE
Missing docs for ingress setup on minikube

### ISSUE THREAD

**Issue by franpog859** [kubernetes/website#12810]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

There is a `404 NotFound` page after clicking the last link in the [ingress documentation file](https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/services-networking/ingress.md). I mean this one - `Set up Ingress on Minikube with the NGINX Controller`. 

There is no such file as `https://github.com/kubernetes/website/blob/master/docs/tasks/access-application-cluster/ingress-minikube.md`.

**Proposed Solution:**

Create the file with ingress setup on minikube.

**Page to Update:**

https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by daminisatya** [comment]
Thank you @franpog859 for pointing the issue. I opened a PR, this fix will resolve it!

**Comment by sftim** [comment]
This looks resolved. Is that right?

**Comment by daminisatya** [comment]
Yes true!! Let me close it! 

/close
