### ISSUE TITLE
Issue with the header nav under Documentation tab

### ISSUE THREAD

**Issue by daminisatya** [kubernetes/website#12826]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Navigate from the home page of the website to Documentation which will land you over here. 

<img width="1631" alt="screen shot 1940-12-06 at 8 03 16 pm" src="https://user-images.githubusercontent.com/6227784/53344425-ac1c5300-3938-11e9-9f90-f8bc1f0dd534.png">

One can observe extra padding under the navigation tabs. But it's the not same when you navigate to the Setup/ any other tab other than Home. Refer the below screenshot. 

<img width="1541" alt="screen shot 1940-12-06 at 8 03 34 pm" src="https://user-images.githubusercontent.com/6227784/53344484-cd7d3f00-3938-11e9-8e88-43757c35d29e.png">

**Proposed Solution:**

Navbar padding (Home tab) must be consistent with other tabs. 

**Page to Update:**
https://kubernetes.io/docs/home/

**Comment by daminisatya** [comment]
https://kubernetes.io/docs/home/

**Comment by Abhik1998** [comment]
I wanted to show a sample of how you wanted it to be.
![image](https://user-images.githubusercontent.com/31558638/53395368-ad489100-39c7-11e9-8f44-71c702df7c34.png)

**Comment by Abhik1998** [comment]
Is this ok??
