### ISSUE TITLE
Inconsistency with footer navigation tabs

### ISSUE THREAD

**Issue by daminisatya** [kubernetes/website#12823]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The footer nav tabs in the blog are in blue whereas in the rest of the document they are in white. 

**Proposed Solution:**
The color should be consistent across the pages in the white.

Footer in Blog 
<img width="1513" alt="screen shot 1940-12-06 at 5 49 30 pm" src="https://user-images.githubusercontent.com/6227784/53337009-20013000-3926-11e9-93fd-2a91a5b4b763.png">

Expected

<img width="1295" alt="screen shot 1940-12-06 at 5 49 40 pm" src="https://user-images.githubusercontent.com/6227784/53337032-2f807900-3926-11e9-835a-f622a00aa1a6.png">

**Page to Update:**
https://kubernetes.io/blog/

**Comment by Sai-Adarsh** [comment]
I shall work on this, Any more pointers @balajismaniam @daminisatya ?

**Comment by daminisatya** [comment]
@Sai-Adarsh Feel free to open a PR. We have a fix from @Abhik1998. I left some comments on his PR. If you can address those it would be great! Thank you ✨

**Comment by daminisatya** [comment]
https://github.com/kubernetes/website/pull/12842#discussion_r260169836
