### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by ibrahimkais** [kubernetes/website#12827]
**This is a...** 

- [x] Bug Report

**Problem:**
**Module 2 - Step 3**

in tutorial I created the proxy 

```
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```
but when trying to run the command as stated in the tutorial 

`curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/`

and the result is

```
Error: 'dial tcp 172.18.0.4:8080: connect: connection refused'
Trying to reach: 'http://172.18.0.4:8080/'
```

**Page to Update:**
https://kubernetes.io/...

**Comment by oussemos** [comment]
Hey @ibrahimkais 

I just tested, the tutorial worked fine for me, maybe you have missed some steps ?

**Comment by ynwd** [comment]
Same here:
```
Error trying to reach service: 'dial tcp 172.17.0.6:80: connect: connection refused'
```

**Comment by stavalfi** [comment]
any update? fix the tutorial?

**Comment by moni-pandey** [comment]
any update ?

**Comment by trickert76** [comment]
Please have a look at https://github.com/kubernetes/website/issues/18079 - I think, it's the same issue. The bootcamp container isn't exposing its port 8080 by default. I don't understand, why this works in the tutorial. Maybe it works on a Minikube
