### ISSUE TITLE
Translate concepts/overview/object-management-kubectl/declarative-config in Korean

### ISSUE THREAD

**Issue by zer0big** [kubernetes/website#12839]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No concepts/overview/object-management-kubectl/declarative-config in Korean

**Proposed Solution:**
Translate concepts/overview/object-management-kubectl/declarative-config in Korean

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/

/language ko

**Comment by gochist** [comment]
resolved by #14285
/close
