### ISSUE TITLE
Broken link from https://kubernetes.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#12852]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://kubernetes.io/docs/tasks/tools/install-minikube/#linux links to a section
> …[Other Ways to Install](https://github.com/kubernetes/minikube#other-ways-to-install) in the official Minikube GitHub repository.

and that's a broken hyperlink.

**Proposed Solution:**
Replace the broken hyperlink with a set of install instructions, in tabs, per Linux distribution.
(Check approach with minikube project)

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/#linux

Kubernetes Version: [v1.13](https://v1-13.docs.kubernetes.io/docs/setup/release/notes/)
Minikube release at time of writing: [v0.34](https://github.com/kubernetes/minikube/releases/tag/v0.34.1)

**Comment by DanyC97** [comment]
are you planning to follow with minikube folks on their slack channel @sftim  ?

**Comment by sftim** [comment]
On this one, I'm logging this more like a customer than a committer. I don't have plans to pick this task up as yet.

I do think it'd be a good idea to liaise with the minikube people before picking my proposed solution.

**Comment by cincodenada** [comment]
Was about to submit a PR for this. In the meantime, the note should just be removed - it's totally useless, as the Minikube README now just has a TL;DR with a link back to these docs for full information.

**Comment by sftim** [comment]
Dealt with
