### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by okezieokpara** [kubernetes/website#12880]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:** Having tried the steps written on this guide on various fresh machines, I am still unable to install kubeadm, kubelet and kubectl packages on ubuntu 16.04 xenial machine:
On runnning
`apt-get install -y kubelet kubeadm kubectl`
 I get the following output:
`Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl` 

And I have been stuck for days
**Proposed Solution:** Correct the article to reflect the working installation steps.

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
the steps here work fine on 16.04:
https://kubernetes.io/docs/setup/independent/install-kubeadm/

also, we have automated tests that verify that installing the packages on 16.04 works

did you perform all of them:
```
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl
apt-mark hold kubelet kubeadm kubectl
```

/priority awaiting-more-evidence

**Comment by okezieokpara** [comment]
This won't work after many trials. Are there alternative ways to install? I could use that

**Comment by neolit123** [comment]
something must be broken on the distro side for this not to work.
the message suggests that the kuberenetes repo was not added to the list of souces.

please try in a clean install of 16.04.

**Comment by okezieokpara** [comment]
Thanks @neolit123 So I have been trying this on a Virtualbox VM with the following:
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"`

Now I tried it on a fresh AWS instance and it worked just fine:
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"`
I suppose this has something to do with Virtualbox VMs.

**Comment by neolit123** [comment]
i'm a VirtualBox VM user and i don't see this problem.
possibly try installing a fresh 16.04 instance?

**Comment by okezieokpara** [comment]
Thanks a lot, @neolit123. This issue has been resolved.
Turns out I was using a 32bit image. Sorry for the mixup

**Comment by neolit123** [comment]
got it.
thanks for the reply.

/close
