### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by Madhav1217** [kubernetes/website#12881]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi. Is there some improvement we should make to https://k8s.io/docs/tasks/run-application/run-stateless-application-deployment/?

**Comment by sftim** [comment]
I'm afraid I'm not sure I understand what you're saying. Was the documentation easy to understand?

**Comment by DanyC97** [comment]
@Madhav1217 can you please clarify what is the problem with the docs you mentioned ?

the documentation is not trying to solve / provide any example using a particular configuration management/ infrastructure as a code tool
