### ISSUE TITLE
Issue with kube-proxy-pod not started on scale up 

### ISSUE THREAD

**Issue by sajlx** [kubernetes/website#12897]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
i have a massive scale up for create some job,
sometimes don't create kube-proxy pod on the new machine
often when the sum of resource requests by the job are near 100% of the node 

thanks

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It sounds like this is a problem with a particular Kubernetes cluster. Is that right?
If the documentation is wrong, we'd like to know more so that we can propose changes to correct it.
