### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by moby04** [kubernetes/website#12942]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I am trying to follow tutorial of Kubernetes but I am kinda lost on first steps when trying to use Katacoda... When I just try to open minikube dashboard I encounter error failed to open browser: exec: "xdg-open": executable file not found in $PATH and dashboard itself remains unavailable when I try to open it through host 1.

Later steps like running hello-world work fine and I am able to run it locally using my own minikube instance but I am a bit confused with this issue. Can I debug it somehow to access dashboard during course? This is particularly confusing because I am a bit afraid that I might encounter same or similar issue during potential exam that also runs online...

**Proposed Solution:**
Donno
![yyf1b](https://user-images.githubusercontent.com/493028/53680570-b2fee900-3cdd-11e9-880e-f8bd1ac054dc.png)

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by etipton** [comment]
+1

**Comment by Sukhoversha** [comment]
go with  `install xdg-utils` before `minikube dashboard`

**Comment by pixelshaded** [comment]
I've done what Sukhoversha suggested and running minikube dashboard opens the Lynx browser. Is this the expected behavior?

**Comment by fabian-milea** [comment]
I get the same error. Run on firefox and chromium. Installed xdg-utils...

**Comment by unitto1** [comment]
The same =( even with xdg-utils in google chrome

**Comment by tengqm** [comment]
dup of #12968

**Comment by controllinghand** [comment]
Found a work around.

Step 1:
^C

Step 2:
$ sudo apt-get update

Step 3:
$ apt install xdg-utils

Step 4: continue with Tutorial :-).
