### ISSUE TITLE
kube-apiserver not starting for ubuntu

### ISSUE THREAD

**Issue by ryansavino** [kubernetes/website#1294]
3 node cluster all ubuntu

when calling kube-up.sh on master, the ending self checks that use the kubectl control command fail because the kube-apiserver service is not running.

when checking the apiserver log (/var/log/upstart/kube-apiserver.log) a fatal error is occuring:
I0921 14:53:20.553277    4929 genericapiserver.go:606] Will report 10.1.70.40 as public IP address.
F0921 14:53:20.556451    4929 plugins.go:143] Unknown admission plugin: DefaultStorageClass

modified cluster/ubuntu/config-default.sh to remove "DefaultStorageClass" from ADMISSION_CONTROL variable, and the kube-apiserver service now starts up, but not sure if there is any loss of functionality.

**Comment by tengqm** [comment]
is this still an issue, @ryansavino ?

**Comment by tengqm** [comment]
Closing this because it is not a documentation issue. Please feel free to raise an issue against kubernetes/kubernetes project if the issue is still not solved.
