### ISSUE TITLE
Issue with k8s.io/docs/setup/release/building-from-source/

### ISSUE THREAD

**Issue by galenballew** [kubernetes/website#12959]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
I believe that the Markdown document _building-from-source.md_ is not being rendered properly on the webpage. I can view the document in version control and it has all of the contents, but nothing is showing on the page in my browser at https://kubernetes.io/docs/setup/release/building-from-source/

I've tested this with multiple browsers and the problem is consistent. Screenshot from Chrome:
![screenshot from 2019-03-03 12-08-14](https://user-images.githubusercontent.com/7023349/53699376-3afff400-3dad-11e9-8bd3-350f6b9c1171.png)

Also, a hyperlink included in _building-from-source.md_ is not an absolute path - `[Release Notes](/docs/setup/release/notes/)`  

**Proposed Solution:**
I am not sure. I double checked _data/setup.yml_ and _static/_redirects_ and both appear to be in order. This could be a local issue, but I wanted to raise an issue just in case. Thank you. 

**Page to Update:**
https://kubernetes.io/...

**Comment by rlenferink** [comment]
This has been solved and is deployed

/close
