### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by hibikutek** [kubernetes/website#12968]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Error when running `minikube dashboard`

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

Stacktrace:
$ minikube dashboard
-   Enabling dashboard ...
-   Verifying dashboard health ...
-   Launching proxy ...
-   Verifying proxy health ...
-   Opening http://127.0.0.1:36962/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
X   failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Comment by rapude** [comment]
Hi, are there any news about this?

**Comment by controllinghand** [comment]
Any status when this will be fixed?  or any work around?

**Comment by BenHall** [comment]
Thanks for the issue with `xdg-open`. As we can't open the link directly on your browser via xdg-open given the sandbox nature and as a workaround the documentation indicates to load the link by selecting the port. 

Last week we added a direct to the Dashboard which will hopefully make this easier. However I didn't realise the number of issues related to people clicking the link. Sorry for not actioning this sooner.

Today we added an override for `xdg-open` that displays a friendly error message to users. They'll now be prompted to use the Preview Port link provided. The output is now:

```
$ minikube dashboard
* Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
* Opening %s in your default browser...
Minikube Dashboard is not supported via the interactive terminal experience.

Please click the 'Preview Port 30000' link above to access the dashboard.
This will now exit. Please continue with the rest of the tutorial.
X failed to open browser: exit status 1
```

We are also investigating how we can make `xdg-open` open the link as expected, but will take some more development time.

In the meantime, we believe this issue can now be closed.

**Comment by sftim** [comment]
/close
based on https://github.com/kubernetes/website/issues/12968#issuecomment-520759769

**Comment by jmichalik** [comment]
This still seems to be an issue. When using the **Select port to view on Host 1** from the tab and inputting 30000, the KataKoda display in the browser is stuck on **Connecting to Port 30000**. Am I missing something?

**Comment by BenHall** [comment]
Thanks for letting us know @jmichalik - With 1.17 the namespace was changed so it's introduced a timing issue. 

We have a fix in place and it will be rolled out later today.

**Comment by Colstuwjx** [comment]
@BenHall Could you please confirm about this issue? I still meet this issue in our website, see the result below:

![image](https://user-images.githubusercontent.com/3972545/73812900-5d01c200-4819-11ea-81cb-f217753496b9.png)

![image](https://user-images.githubusercontent.com/3972545/73812907-61c67600-4819-11ea-81be-fdddfd4ce268.png)
