### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by letavia** [kubernetes/website#12973]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Failed to run `kubectl api-resources --namespaced=<true/false>`

**Proposed Solution:**
Please check if this command is still valid.
My kubernetes version:
Client: v1.10.7
Server: v1.11.7-gke.4 

**Page to Update:**
https://kubernetes.io/...

**Comment by hpandeycodeit** [comment]
@letavia Yes this command still works 
Client version: 1.11.1
Server version: 1.11.5

**Comment by letavia** [comment]
I upgraded the client version and it works now. Thanks!
