### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by diederichm** [kubernetes/website#12985]
calico/cni is not available on s390x architecture - though docs say so

**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Docs say "Note that Calico works on amd64, arm64, ppc64le and s390x only."
but s390x is not present - and installation of calico fails with ImagePullBackOff

the docker manifest reveals that s390x is not included :

 docker manifest inspect  calico/cni
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1155,
         "digest": "sha256:6b82b7dc43864ccaa5723afbff918ad01126e81dd8ab7287f9bdd9ce47ef6ece",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1362,
         "digest": "sha256:a8ce143717800356633180365741a39c6a85b6971b138a11f37ccc79114cab18",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1362,
         "digest": "sha256:42ffe10434c679eaadd2a7e71459e7a106d9f574bb57bd374aa04ef6678d88a7",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      }
   ]
}

**Proposed Solution:**
Add s390x images. that would be most preferred.

**Page to Update:**
https://kubernetes.io/...

1.12-5

s390x

**Comment by neolit123** [comment]
^ i've a sent PR to fix this.
thank you for noticing.

**Comment by diederichm** [comment]
Guys, I dont understand why you dont build for s390 ?

**Comment by neolit123** [comment]
hi @diederichm , i do not know. this is a question for the calico maintainers.

so you can create an issue in this repo and as the question:
https://github.com/projectcalico/cni-plugin

but search for `s390x`, reveals that the architecture is unstable:
https://github.com/projectcalico/cni-plugin/blob/a7af24a4e3cde1e16476925009b5d1f69b53495f/Makefile#L115-L118
