### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by CSLLCUser** [kubernetes/website#12990]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Launching minikube dashboard encountered the following error and unable to continue tutorial:
demo failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

Open a 'Web Preview' to render the response from a running web server.

virtual terminal session:

minikube version; minikube start
$
$ minikube version; minikube start
minikube version: v0.34.1
o   minikube v0.34.1 on linux (amd64)
>   Configuring local host environment ...
>   Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 172.17.0.47
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.13.3
@   Downloading kubelet v1.13.3
-   Pulling images required by Kubernetes v1.13.3 ...
-   Launching Kubernetes v1.13.3 using kubeadm ...
-   Configuring cluster permissions ...
-   Verifying component health .....
+   kubectl is now configured to use "minikube"
=   Done! Thank you for using minikube!
$ minikube dashboard
-   Enabling dashboard ...
-   Verifying dashboard health ...
-   Launching proxy ...
-   Verifying proxy health ...
-   Opening http://127.0.0.1:40646/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
X   failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Comment by tengqm** [comment]
dup of #12968
