### ISSUE TITLE
"Install Service Catalog using SC" is Google specific

### ISSUE THREAD

**Issue by randomvariable** [kubernetes/website#13017]
The page [Install Service Catalog using SC](https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-sc/) isn't clear up front that this tool is specific to Google Cloud.

**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
If naively following this document, you get quite far before realising the tool is geared around linking Google Projects to a Kubernetes cluster.

**Proposed Solution:**
Cloud provider specific tooling should at least be flagged as such up front or removed for the cloud provider to host in their own documentation.

**Page to Update:**
https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-sc/

/sig service-catalog

**Comment by sftim** [comment]
Similar to #16981

**Comment by randomvariable** [comment]
Not sure if that PR is enough to address the issues. The entire page is about installing the service catalog using GCP binaries with automated integration to Google Cloud. It's additionally deprecated, so the version it deploys is out of date.

Probably better to remove completely or link to https://github.com/kubernetes-sigs/service-catalog/blob/master/docs/install.md which covers the cloud-provider agnostic svcat tool.
