### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod/

### ISSUE THREAD

**Issue by ecout** [kubernetes/website#13028]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
There is a kubernetes.io blog post linked directly from the kubernetes docs in multiple instances. The post is linking to expired/missing architectural diagram images. The post talks about Deployment best practices, which is relevant.

**Proposed Solution:**
Please either incorporate the best practices into the document or update the post links to reflect the architectural diagrams.

**Page to Update:**
Post:
https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/

Sample documentation page referencing blog post(there is more):
I https://kubernetes.io/docs/concepts/workloads/pods/pod/

Sample image file link from original blog post:
https://4.bp.blogspot.com/-yEmqGZ86mNQ/WRnPYG1m3jI/AAAAAAAABJo/94DlN54LA-oTsORjEBHfHS_UQTIbNPvcgCEw/s1600/Example%2B%25232-%2BAmbassador%2Bcontainers.png

**Comment by sftim** [comment]
Good spot, that needs fixing.
/language en
