### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by Erically** [kubernetes/website#13035]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
the page:
https://kubernetes.io/docs/setup/independent/high-availability/
the question:
is 192.168.0.200 the load balancer ip or one of the masters ip ?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It looks like this page could use some tidying so it's clear to users and also a little more agnostic about Linux distribution, CNI etc.

**Comment by neolit123** [comment]
> is 192.168.0.200 the load balancer ip or one of the masters ip ?

it's the load balancer IP (but also called "controlPlaneEndpoint" in kubeadm terms).
the page is being updated for 1.14.

/close
