### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by krichter722** [kubernetes/website#13036]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
Describing statefulness with an nginx service serving "Hello world!" dynamically or other static content is a bad choice because it's not stateful. It demonstrates the use of the configuration files, but provides no additional examples.

This seems to be widespread in the k8s docs and probably has a cause like sponsoring by Nginx which is fine, but having a good overview of different use cases is a quality feature of good documentation. So far, I got a good overview of the concepts and specifications of parts of k8s, however feel like I've only seen nginx being deployed in the most absurd setups for someone getting started with k8s while it takes me hours and days to find examples of real world use cases.

I think that everybody getting started on statefulness in k8s (e.g. in https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) is way more concerned about getting a clustered database accessible by a replicated set of stateless pods rather than clustering their nginx.

**Proposed Solution:**
Review examples in terms of coverage of real-world cases in order to make the example intuitive and useful rather than just provide the base to search for and depend on examples on unreliable third-party sources, like outdated blogs and horrible forums.

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It sounds like https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/ is closer to what you had in mind.

If https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/ linked there, how close would that get us towards addressing this issue?

**Comment by krichter722** [comment]
@sftim That'd be a good solution, thank you.

**Comment by adityabhatia02** [comment]
@sftim I would like to contribute to this issue. So as I understand, the solution is to link https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/ in the what's next section of statefulset doc:https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#what-s-next. I hope I am on the right track here?

**Comment by sftim** [comment]
@adityabhatia02 :white_check_mark: adding that hyperlink is the improvement I had in mind
