### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by moby04** [kubernetes/website#13057]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Unlike other tasks in documentation this site presents pod definitions but doesn't contain file urls for creation which makes following a bit frustrating/time consuming.

**Proposed Solution:**
Replace pod creation YAMLs with files available through public URL so that `kubectl create -f <URL> --edit` could be used.

**Page to Update:**
https://k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

**Comment by leileijia** [comment]
豆腐干夹具

**Comment by DanyC97** [comment]
@moby04 thanks for raising it, i've already tagged it in https://github.com/kubernetes/website/issues/12740 , will work on it soon
