### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/pods/disruptions/

### ISSUE THREAD

**Issue by mcneiljt** [kubernetes/website#13050]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Kubernetes documentation does not delineate what will happen to a pod in the event of an involuntary disruption. The disruption page focuses heavily on voluntary disruption mitigation. While the page does describe the differences between the two types of disruption, I was not able to determine if Kubernetes will reschedule disrupted pods (on a new node for example) or if it will simply leave them as dead.

**Proposed Solution:**
Please include information on how Kubernetes behaves when a pod is impacted by an involuntary disruption. It would be good as a prospective user or admin to know whether manual intervention is required after a voluntary disruption or if the pod will be rescheduled on new or alternative hardware. Thank you for the otherwise fantastic documentation!

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

**Comment by sftim** [comment]
Would it help to have the section on involuntary disruptions a hyperlink to https://kubernetes.io/docs/concepts/workloads/pods/pod/#durability-of-pods-or-lack-thereof ?
I'm hoping we can make this improvement by signposting to existing pages about how pod failures get handled.
