### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by sueyaping** [kubernetes/website#13069]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Module 2 not working

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi. Can you tell us what wasn't working for you?

**Comment by thecrudge** [comment]
Safe to close, no response

/close
