### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by diederichm** [kubernetes/website#13127]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
the linked yaml for the dashboard seems to have amd64 hardcoded as architecture

**Proposed Solution:**
I guess the image could be specified without architecture ?

**Page to Update:**

https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by sftim** [comment]
Specifying images in an architecture-independent way doesn't seem as easy as you might think
(or I have missed out on how to do just that).

**Comment by diederichm** [comment]
Hello Tim, I revisited this and it appears the images now have a manifest for the different architectures.
I was able to run the apply command, the containers started w/o exec format error.
