### ISSUE TITLE
Issue with k8s.io/docs/setup/custom-cloud/coreos/

### ISSUE THREAD

**Issue by cmanania** [kubernetes/website#13125]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Multi-node cluster using cloud-config, CoreOS and VMware ESXi is no longer valid.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by DanyC97** [comment]
https://github.com/kubernetes/website/pull/13162 fixed the CoreOS.

not sure about the others, maybe members of cluster-lifecycle sig can chime in ?

cc /sig cluster-lifecycle
