### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by 747823** [kubernetes/website#13138]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The interactive terminal command in the deploying an app tutorial is deprecated in module 2, step 2. 
This is the command and its result in the interactive terminal:
```
$ kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
error: no matches for kind "Deployment" in version "apps/v1"
$
```

**Proposed Solution:**
Update command to something that does not cause an error

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by DanyC97** [comment]
thank you for raising it @747823 !!

cross link to #12090
