### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by janscott525** [kubernetes/website#13169]
Versions?????

**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by janscott525** [comment]
No such thing as versions in your world? WTF?

**Comment by sftim** [comment]
Hi @janscott525 
What improvement to this page would help solve the issue?
/triage needs-information
