### ISSUE TITLE
add Kind to local-machine solutions

### ISSUE THREAD

**Issue by tao12345666333** [kubernetes/website#13176]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

[kind](https://github.com/kubernetes-sigs/kind) is a tool for running local Kubernetes clusters using Docker container "nodes".
We can use it to create multi-control-plane or multi-node Kubernetes cluster.

**Page to Update:**
https://kubernetes.io/docs/setup/pick-right-solution/

**Comment by karthequian** [comment]
It's already there under `ecosystem tools` https://kubernetes.io/docs/setup/pick-right-solution/#ecosystem-tools?

**Comment by karthequian** [comment]
Oh! I see what you mean- perhaps delete it from `Ecosystem Tools` section if we're adding to the community supported tools. Will comment in the PR.

**Comment by tao12345666333** [comment]
I seem to have ignored it before. :upside_down_face:  
Thank you for pointing out. :+1:

**Comment by karthequian** [comment]
haha. no worries! I totally agree with your PR though- it should probably be in the 1st section, so just remove the 2nd occurrence :)

**Comment by tao12345666333** [comment]
OK, Thanks.
