### ISSUE TITLE
Issue with k8s.io/zh/docs/reference/kubectl/kubectl/     unintelligible text. 

### ISSUE THREAD

**Issue by joyliu329** [kubernetes/website#13199]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by joyliu329** [comment]
chinese unintelligible text. 
![image](https://user-images.githubusercontent.com/11437703/54408272-35df6500-471c-11e9-9204-fd9e1ddf9821.png)

**Comment by xichengliudui** [comment]
@joyliu329  Sorry for delaying your use. Could you please tell me the specific link? I'll fix it.
