### ISSUE TITLE
Running the site locally using Hugo failed

### ISSUE THREAD

**Issue by qinlj** [kubernetes/website#13206]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Hi,I want to running the site locally using Hugo. I followed the instructions on the page of"https://github.com/kubernetes/website",then  I was given an error when I performed this step. What should I do?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

![error](https://user-images.githubusercontent.com/18457974/54417336-d5145480-473c-11e9-8778-a1197267624d.png)

**Comment by Sai-Adarsh** [comment]
Hugo version? Try installing `Hugo 0.53` You could find the supported HUGO_VERSION in [Makefile](https://github.com/kubernetes/website/blob/master/Makefile)

**Comment by qinlj** [comment]
> Hugo version? Try installing `Hugo 0.53` You could find the supported _HUGO_VERSION_ in [Makefile](https://github.com/kubernetes/website/blob/master/Makefile)

The Hugo version is 0.53.

**Comment by DanyC97** [comment]
as an alternative you could run `make docker-serve` , that is what i'm doing it

**Comment by qinlj** [comment]
> as an alternative you could run `make docker-serve` , that is what i'm doing it

Thanks. I solved this problem，because I downloaded the ZIP,then I clone the code and run `make serve`, it's OK now.

**Comment by DanyC97** [comment]
/close

as per @qinlj 's feedback
