### ISSUE TITLE
Issue with k8s.io/docs/home/

### ISSUE THREAD

**Issue by ipchaube** [kubernetes/website#13212]
indu.chaube@INDUW88 /e/abss/src/orchestrator (master)
$ go get k8s.io/client-go/...
package k8s.io/client-go/...: unrecognized import path "k8s.io/client-go" (https fetch: Get https://k8s.io/client-go?go-get=1: dial tcp 23.236.58.218:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

indu.chaube@INDUW7 MINGW64 /e/abss/src/orchestrator (master)

**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
indu.chaube@INDUW88/e/abss/src/orchestrator (master)
On My window PC
$ go get k8s.io/client-go/...
package k8s.io/client-go/...: unrecognized import path "k8s.io/client-go" (https fetch: Get https://k8s.io/client-go?go-get=1: dial tcp 23.236.58.218:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

indu.chaube@INDUW88 /e/abss/src/orchestrator (master)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi. This doesn't seem like a defect in the Kubernetes documentation.

Is there an improvement that you'd recommend we make, or a shortcoming in the documentation that we can help fix?
