### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/admission-controllers/

### ISSUE THREAD

**Issue by ivalexm** [kubernetes/website#13213]
To see which admission plugins are enabled:

kube-apiserver -h | grep enable-admission-plugins

**This is a...** 

- Bug Report

**Problem:**
kube-apiserver -h 
is the HELP of "kube-apiserver" and grep enable-admission-plugins gives you nothing about the enabled admission plugins

**Proposed Solution:**
I am not sure. I just wanted to see the enabled admission plugins.

**Page to Update:**
https://kubernetes.io/...

1.13

Kubernetes is installed by the latest document

**Comment by Aggie101** [comment]
add a jumpstart the reboot jksfhuow
