### ISSUE TITLE
Issue with k8s.io/ko/docs/concepts/overview/working-with-objects/kubernetes-objects/

### ISSUE THREAD

**Issue by ujuc** [kubernetes/website#13248]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
missing word...

**Proposed Solution:**
Add missing word

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/kubernetes-objects/#%EC%98%A4%EB%B8%8C%EC%A0%9D%ED%8A%B8-spec-%EA%B3%BC-%EC%83%81%ED%83%9C-status

**Comment by gochist** [comment]
@ujuc 참고로, Issue 등록이 필수는 아니고 PR만 올리셔도 됩니다.

**Comment by ujuc** [comment]
네
