### ISSUE TITLE
Issue with k8s.io/docs/reference/setup-tools/kubeadm/kubeadm/

### ISSUE THREAD

**Issue by hickey** [kubernetes/website#13259]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
It hard as heck to track down the specification for what can be placed in the YAML file for configuring Kubernetes when a `kubeadm init` is executed. 

**Proposed Solution:**
I found the pages discussing the YAML format once several months ago, but I have just spent 45 mins looking for the information again (it should not be this difficult to locate information). Where ever this documentation is needs to be linked into spots that it would be used (such as where `kubeadm init` is discussed  and probably for `kubeadm config`). I am sure it is not a purposeful hiding of the data, but it definitely needs to be promoted in a few spots so it can be found. 

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/

**Comment by neolit123** [comment]
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file
> For more details on each field in the v1beta1 configuration you can navigate to our API reference pages

/close

**Comment by hickey** [comment]
Ah, now I understand why I was having such a hard time finding the
config file information. The visited link style is atrocious! Since I
had visited the page months ago the link did not look like a link.
Please see the image below which is a screen shot of the page that has
the link. I only caught it again by happenstance. I further tested with
the kube-proxy link and got the same result.

Clearly the IPVS is a link, but the visited link style changes the link
color to nearly the same color as the text next to it. Why are the
visited links trying to be hidden?



-- 
Gerard Hickey | Smartsheet
Principal Systems Engineer
D: +1 425-326-3691
M: +1 425-395-4554
E: Gerard.Hickey@smartsheet.com <mailto:Gerard.Hickey@smartsheet.com>

www.smartsheet.com <https://www.smartsheet.com/>
