### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/pod-priority-preemption/

### ISSUE THREAD

**Issue by vllry** [kubernetes/website#13253]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Docs are old (for 1.11), and should be updated to 1.14/1.15. Notably, the feature is now GA.

**Proposed Solution:**
Do a content sweep for correctness (EG beta->GA).

**Page to Update:**
k8s.io/docs/concepts/configuration/pod-priority-preemption/

**Comment by bsalamat** [comment]
Thanks, @vllry! Docs and website are updated already: https://github.com/kubernetes/website/pull/12428.
New website content will be released with the release of 1.14.
