### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by eliot1785** [kubernetes/website#13260]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I wanted to give some feedback on this page from the perspective of a new Kubernetes user. I've read the whole thing, and on the whole I think it's a great page.

I found one thing strange, though: --from-env-file is the only option shown which actually parses the file to convert it to a structured YAML representation (i.e. the resulting data is not an exact string copy of the file). In every case using --from-file, the file contents are just converted to a string.

I haven't used ConfigMaps yet, but I think I would probably prefer the following combination for various reasons: 1) read from a file, 2) the file is not an env file (it would be YAML or JSON), and 3) the result in the ConfigMap is a parsed value, not a string. The reason for 3) is that I assume it will then be easier for the consumers of the ConfigMap since they don't need to parse the value themselves.

Right now, the documentation doesn't cover how to do that, and if it's possible I think it would be a good addition.

**Proposed Solution:**

See above.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

**Comment by sftim** [comment]
Seems like a good suggestion!
/language en
