### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by dgkoris** [kubernetes/website#13275]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The command 'minikube dashboard' generates the following error:

-   Enabling dashboard ...
-   Verifying dashboard health ...
-   Launching proxy ...
-   Verifying proxy health ...
-   Opening http://127.0.0.1:46711/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
X   failed to open browser: exec: "xdg-open": executable file not found in $PATH

We tried on a different computer too.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
dup of #12968
