### ISSUE TITLE
k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/ uses deprecated command

### ISSUE THREAD

**Issue by bgiddings** [kubernetes/website#13291]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
The instructions say to run:

    kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080

That results in a warning in the console:

    kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by DanyC97** [comment]
thank you for raising the issue, this is related to https://github.com/kubernetes/website/issues/12090
