### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/automated-tasks-with-cron-jobs/

### ISSUE THREAD

**Issue by mustufa5689** [kubernetes/website#13295]
`# kubect run` command, should work for creating the `cronjobs` in the latest version of 1.13.
It shows an deprecated error message.
"kubectl run --generator=batch/v1beta1" is DEPRECATED and will be removed in future version.

As per the documentation, it should run successfully , like for Pods.

**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
`# kubect run` command, should work for creating the `cronjobs` in the latest version of 1.13.
It shows an deprecated error msg.
As per the documentation, it should run successfully , like for Pods.

**Proposed Solution:**
kubectl run hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh -c "date; echo Hello from the Kubernetes cluster"

**Page to Update:**
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/

1.13

**Comment by DanyC97** [comment]
thanks for raising the issue @mustufa5689 .

This is related to https://github.com/kubernetes/website/issues/12090
