### ISSUE TITLE
In k8s.io/docs/tutorials/hello-minikube/ "minikube dashboard" using Katacoda environment never responds on 30000

### ISSUE THREAD

**Issue by bgiddings** [kubernetes/website#13292]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
Using the in-browser Katacoda environment, The docs for hello-minikube say to run "minikube dashboard".

Running that results in:

    $ minikube dashboard
    -   Enabling dashboard ...
    -   Verifying dashboard health ...
    -   Launching proxy ...
    -   Verifying proxy health ...
    -   Opening http://127.0.0.1:38793/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
    X   failed to open browser: exec: "xdg-open": executable file not found in $PATH

This command never finishes, but it's not clear if it's supposed to, or if it's like kubectl proxy and needs to be running while the dashboard runs.

Next, the instructions say:

> Katacoda environment only: At the top of the terminal pane, click the plus sign, and then click Select port to view on Host 1.

> Katacoda environment only: Type 30000, and then click Display Port.

The Katacoda web page shows:

    We're currently trying to connect to a HTTP service running on 30000. Services can sometimes take a few moments to start, even upto five minutes.

However even 20 minutes later there's no response.

In the browser JS console:

    GET https://2886795285-30000-elsy02.environments.katacoda.com/katacoda/_health 500
    /katacoda/_health:1 Failed to load resource: the server responded with a status of 500 ()

It seems to be polling that URL every second or so, and always getting a 500.

It isn't clear if the problem is with the "minikube dashboard" command, or something else.  The instructions say to run other commands after "minikube dashboard", which suggests it should eventually exit, however it never does.

**Proposed Solution:**

??

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

Additional Information:

Whatever the issue here is, the tools make it very difficult to diagnose.  If a program is supposed to run until you kill it, like "kubectl proxy", it would be good if the program indicated that it runs in the foreground and you're expected to kill it when you're done with it.  This could be done by including a message like "Press Ctrl-C to stop the proxy when you are done with it".  If that were absent, it might indicate that the program is not supposed to sit in the foreground constantly.

If a program is supposed to run then exit, it would be good if it eventually timed out, or at least emitted periodic messages to indicate that it is still waiting for something.

**Comment by rlenferink** [comment]
Hi @bgiddings . Thanks for clearly describing your issue 🎉

However, it may be better suited to create a ticket at [kubernetes/minikube](https://github.com/kubernetes/minikube/issues/new) as you may get a faster reply and a possible solution for your problem over there.

But please keep us in the loop and please reference this ticket as we have to update our documentation as well in case something must be better described.

**Comment by tengqm** [comment]
dup of #12968
