### ISSUE TITLE
E_FAIL (0x80004005) while starting m

### ISSUE THREAD

**Issue by AGtechm** [kubernetes/website#13316]
**This is a...
- [ x] Bug Report

**Problem:**
Not able to start the minikube 0.35 on virtualbox 6.0.4. Keeps giving following error. Tried to uninstall completely and reinstall (removed .minikube and .virtualbox directories) but still the same. This is on Windows 10 Home.
[restart issue.txt](https://github.com/kubernetes/website/files/2989680/restart.issue.txt)
Any help to get it started would be appreciated.

[restart issue - vboxhardenlog.txt](https://github.com/kubernetes/website/files/2989681/restart.issue.-.vboxhardenlog.txt)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by AGtechm** [comment]
Attaching the logs
[VBoxHardening.log](https://github.com/kubernetes/website/files/2996696/VBoxHardening.log)

**Comment by rlenferink** [comment]
Hi @AGtechm. Thanks for finding this issue and creating a ticket 🎉 

However, it may be better to create a ticket at [kubernetes/minikube](https://github.com/kubernetes/minikube/issues/new) as you may get a faster reply and a possible solution for your problem over there.

**Comment by rlenferink** [comment]
I noticed you already did that, oops 🙈 

ref: https://github.com/kubernetes/minikube/issues/3910

**Comment by DanyC97** [comment]
@AGtechm i'm going to close this issue as is not related to docs. should you think otherwise please open a new issue with a PR description and the url pointing to the docs which needs to be corrected, thank you
