### ISSUE TITLE
Issue with "note" snippet and numbered lists

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#13314]
When working with @michmike on the windows docs, it was brought to my attention that when a numbered list has a "note" snippet in the middle, it will break the sequence of numbers.

If the note snippet is indented over to match the list, the note gets formatted as a single line code block. This ultimately results in none of the markdown working (like URLs).

If the note is at the beginning of the list or the end, it is 100% fine.

For today, we will deal with the correct numbers and mangled notes snippet but it would be nice to fix. I'm thinking it might have to do with the list CSS - but need some help from someone more familiar with this.

Example: https://github.com/kubernetes/website/commit/d06922552b76536142ab65ddeeb865dfde3ddd8d#diff-2b903255e1cc87bd31083e5081f0be4a
Website build example (middle of section, see note format): https://deploy-preview-13279--kubernetes-io-vnext-staging.netlify.com/docs/setup/windows/user-guide-windows-nodes/#getting-started-adding-a-windows-node-to-your-cluster

**Comment by kbhawkey** [comment]
@jimangel. I played with the rendering of the `note` shortcode in a list. I applied a short term fix to the windows-node setup page.
The CSS is different based upon whether the initial note shortcode markup is on a line by itself. Does not seem to matter about the closing note shortcode. Here are my findings:
- The CSS is `<blockquote><div>`, and the link works
 {{< note >}}The VNI must be set to 4096 and port 4789 for Flannel on Linux to interoperate with Flannel on Windows. Support for other VNIs is coming soon. See the [VXLAN documentation](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#vxlan) for an explanation of these fields.
{{< /note >}}

- The CSS is `<blockquote><div><pre><code>`, no links
{{< note >}}
The VNI must be set to 4096 and port 4789 for Flannel on Linux to interoperate with Flannel on Windows. Support for other VNIs is coming soon. See the [VXLAN documentation](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#vxlan) for an explanation of these fields.
{{< /note >}}

**Comment by kbhawkey** [comment]
@jimangel, upon further investigation 😃,
I believe this explains the note rendering:
1) In the case where the note shortcode opening tag is on a single line:
{{< note >}}
The VNI must be set to 4096 and port 4789 for Flannel ...
{{< /note >}}

We define a note shortcode which adds the `Note**` prefix followed by *all* of the text (.Inner) between the shortcode note markup. The text is then processed through the hugo *markdownify* function (black friday markdown processor?). The text that is slurped up and processed happens to contain the indentation from the list which causes the extra `<pre><code>` tags to surround the text. These extra HTML tags then triggers the k8s/website CSS for `<pre><code>` which lacks the correct highlighting for links.
Ideally, I think, we only want to capture the text for the note and not the list indentation. So, to fix, it could be possible to clean-up all spaces, tabs before the first alpha-numeric character.

**Comment by jimangel** [comment]
Thank you @kbhawkey for your diligence on this issue including adding examples in our docs!
/close
