### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/init-containers/

### ISSUE THREAD

**Issue by agnf** [kubernetes/website#13327]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In the latest version of busybox (at least since July 2019 and as of March 2019), nslookup doesn't work as expected. It won't exit with status 1 after the lookup. Hence, both InitContainers will exit immediately, defeating the whole purpose of the init process. See https://github.com/docker-library/busybox/issues/48

**Proposed Solution:**
Instead of "image: busybox" use "image: busybox:1.28" in your example

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by agnf** [comment]
Duplicate of #12050

**Comment by DanyC97** [comment]
/close

as being duplicate as per @agnf 's comment
