### ISSUE TITLE
Issue with k8s.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/

### ISSUE THREAD

**Issue by xuhz** [kubernetes/website#13333]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
There is a Xilinx FPGA k8s device plugin available. A link to the plugin should also be provided here so that users can easily find it.

**Proposed Solution:**
Link to xilinx FPGA k8s device plugin:

https://github.com/Xilinx/FPGA_as_a_Service/tree/master/k8s-fpga-device-plugin/trunk

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the suggestion @xuhz 
/language en
/kind feature

**Comment by sftim** [comment]
This wouldn't fit with the [content guidelines](https://kubernetes.io/docs/contribute/style/content-guide/) that arrived recently.

With that in mind:
/close
