### ISSUE TITLE
No diagram on /concepts/overview/components/

### ISSUE THREAD

**Issue by oxddr** [kubernetes/website#13332]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
On the page describing components there is no diagram presenting, how they are tied together. There is such diagram on https://kubernetes.io/docs/concepts/architecture/cloud-controller/, but it's not obvious that one should look for one there.

**Proposed Solution:**
Add diagram from https://kubernetes.io/docs/concepts/architecture/cloud-controller/ to https://kubernetes.io/docs/concepts/overview/components/

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/components/

**Comment by SupriyaSirbi** [comment]
hello oxddr,

I am interested in working on this issue. can i submit the PR for the the same.

Thanks

**Comment by sftim** [comment]
@SupriyaSirbi did you make a start on the diagram that you mentioned?

**Comment by SupriyaSirbi** [comment]
Hello @sftim I shall submit a PR by end of this week. I have starting making the diagram and will soon submit the PR. Thanks

**Comment by sftim** [comment]
There's a diagram now!
/close
