### ISSUE TITLE
Not-ready rationale on  k8s.io/docs/concepts/workloads/controllers/daemonset/?

### ISSUE THREAD

**Issue by paulgmiller** [kubernetes/website#13342]
**This is a...** 

- [ x] Feature Request
- [ ] Bug Report

**Problem:**
Not clear why daemonsets schedule on notready/unreachable nodes

**Proposed Solution:**
Put some rationale?  @gmarek might be a good source. Since I at least found he added this comment in the source. 
https://github.com/kubernetes/kubernetes/commit/f371c1431483ff7fb5a1a3bb0f13a7890fabfd9

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

1.12

**Comment by paulgmiller** [comment]
I was debating proposing a change to status so you could tell that your daemonset had at least scheduled on all the ready nodes  but want to understand more why before I go down that hole.

**Comment by sftim** [comment]
@paulgmiller I think you have in mind some text that explain how DaemonSets are often used as part of the set of steps to make a Node become ready, and that's why the scheduling is special.

Have I got that right?

**Comment by paulgmiller** [comment]
That would be interesting. I am coming at it form the perspective of deploying daemonsets onto clusters with large numbers of nodes and it's hard to track a daemonset rollout succes if there's a decent probablity of an unready node. So I care more about why daemonsets are scheduled on unready nodes but maybe that is explained by the inverse of why daemonset scheduling affects node readiness.

**Comment by sftim** [comment]
Cool, that's a reasonable improvement to make then.
/language en
