### ISSUE TITLE
Issue with k8s.io/docs/contribute/start/

### ISSUE THREAD

**Issue by bagoole** [kubernetes/website#13346]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by DanyC97** [comment]
@bagoole thank you for raising the issue, could you please add a description on what the issue is ?

**Comment by DanyC97** [comment]
@bagoole in absence of any response i'm going to close this issue. Please open a new one with a full description as per the github issue template and we'll look into it
