### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-controller-manager/

### ISSUE THREAD

**Issue by walterdolce** [kubernetes/website#13362]
**This is a...** 
- [x] Bug Report

**Problem:**
Documentation does not mention the `--address` parameter, yet the `kube-controller-manager` process running specifies it.

```
vagrant@k8s-master:~$ps aux | grep controller
root      2512  6.0  6.4 205384 65264 ?        Ssl  11:23   0:34 kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=192.168.0.0/16 --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=true --node-cidr-mask-size=24 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --use-service-account-credentials=true
vagrant  18794  0.0  0.0  14224   960 pts/0    S+   11:32   0:00 grep --color=auto controller
```

PS: local cluster setup is based on [this](https://github.com/walterdolce/localkube) which is, in turn, based on [the original blog post on the Kubernetes blog](https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/) (the code showcased in the blog post does not work, by the way)

**Proposed Solution:**
Document the `--address` flag

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

Kubernetes version: 1.13

**Comment by sftim** [comment]
Seems like this still wants looking at
/remove-lifecycle rotten

**Comment by tengqm** [comment]
Double checked this. We currently only generate options for non-deprecated and non-hidden commands, which sounds the right strategy going forward.
