### ISSUE TITLE
Translate /docs/concepts/workloads/pods/pod-lifecycle/ in Japanese

### ISSUE THREAD

**Issue by sakajunquality** [kubernetes/website#13377]
# Translate /docs/concepts/workloads/pods/pod-lifecycle/ in Japanese

**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No /docs/concepts/workloads/pods/pod-lifecycle/ in Japanese.

**Proposed Solution:**
Translate /docs/concepts/workloads/pods/pod-lifecycle/ in Japanese.
Copy from en content and Update `/content/en/docs/concepts/workloads/pods/pod-lifecycle.md`.

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by cstoku** [comment]
@sakajunquality こちらの翻訳、着手済みでしょうか？
未着手であれば  `1.15` のマイルストーンに移そうかと思うのですがいかがでしょう？
（リリースでも大丈夫です）

**Comment by sakajunquality** [comment]
@cstoku 未着手なので移していただいて大丈夫です。

**Comment by cstoku** [comment]
@sakajunquality こちら作業いかがでしょうか？

**Comment by sakajunquality** [comment]
@cstoku 途中なのですが来週休みなので時間取れると思いますー！

**Comment by cstoku** [comment]
/remove-lifecycle stale
@sakajunquality あと1週間くらいで出して頂けるとたすかります:pray:
