### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by Dabbeeru** [kubernetes/website#13370]
**This is a...** 

- [x] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Dabbeeru** [comment]
-bash: /etc/bash_completion.d/kubectl: Permission denied
--

can you please help me on this error

**Comment by tengqm** [comment]
Probably you need to do `sudo`. Out of doc scope. Closing.

**Comment by addis144** [comment]
@Dabbeeru  - and anyone that may run into this.  Use this command instead. 
`kubectl completion bash |sudo tee /etc/bash_completion.d/kubectl
`

**Comment by Gre8t** [comment]
This solved the issue for me
