### ISSUE TITLE
ko: nav-menu is not synced with translation.

### ISSUE THREAD

**Issue by yoonian** [kubernetes/website#13374]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
`Statefulset Basic` in `Stateful Application` is not synchronized with its translation `스테이트풀셋 기본` in left menu navigation.

**Proposed Solution:**
Fix `content/ko/docs/tutorials/_index.md`.
Add `content/ko/docs/tutorials/stateful-application/_index.md`.

**Page to Update:**
https://kubernetes.io/ko/docs/tutorials/

**Comment by gochist** [comment]
@yoonian `dev-1.13-ko.9`과 ` dev-1.14-ko.1`에 각각 PR 부탁드립니다.

**Comment by yoonian** [comment]
@gochist 확인 부탁드립니다.

**Comment by gochist** [comment]
resolved by #13469 and #13474
/close
