### ISSUE TITLE
API reference wrongly displays `extensions/PodSecurityPolicy` as new and `policy/PodSecurityPolicy` as old

### ISSUE THREAD

**Issue by ymmt2005** [kubernetes/website#13394]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

`PodSecurityPolicy` was moved from `extensions` API group to `policy`.
However, API reference document wrongly displays `policy/v1beta1 PodSecurityPolicy` in "OLD API VERSIONS" section:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/

Moreover, deprecation warning for `extensions/v1beta1 PodSecurityPolicy` is not displayed in that document
although swagger.json has the warning:
https://github.com/kubernetes/kubernetes/blob/release-1.13/api/openapi-spec/swagger.json

**Proposed Solution:**

Show deprecation warning for `extension/v1beta1 PodSecurityPolicy` and move it to "OLD API VERSIONS" section.
Move `policy/v1beta1 PodSecurityPolicy` to "METADATA APIS" section.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/

**Comment by tengqm** [comment]
Okay, this was caused by defects in the API generator which is now fixed (https://github.com/kubernetes-incubator/reference-docs/pull/72). Will regenerate the API ref and commit.

**Comment by ymmt2005** [comment]
Great!  Thank you very much.

**Comment by daminisatya** [comment]
@tengqm Is this issue good to close?

**Comment by sftim** [comment]
I think this is OK to
/close
