### ISSUE TITLE
Translate /docs/contribute/_index.md in Japanese

### ISSUE THREAD

**Issue by silverskyvicto** [kubernetes/website#13395]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No /docs/contribute/_index.md in Japanese.

**Proposed Solution:**
Translate /docs/contribute/_index.md in Japanese.
Copy from en content and Update `/content/en/docs/contribute/_index.md`.

**Page to Update:**
https://kubernetes.io/ja/docs/contribute/_index.md

**Comment by cstoku** [comment]
@silverskyvicto こちらの翻訳、着手済みでしょうか？
未着手であれば  `1.15` のマイルストーンに移そうかと思うのですがいかがでしょう？
（リリースでも大丈夫です）

**Comment by silverskyvicto** [comment]
@cstoku 着手して一通り訳してあります。
