### ISSUE TITLE
Tracking issues with generating reference docs v1.14

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#13396]
Opening up this issue tracking the problems generating for v1.14: https://kubernetes.io/docs/contribute/generate-ref-docs/

Federation docs, these might not even be needed, but they generated nothing new (except undoing the relative link work):
https://kubernetes.io/docs/contribute/generate-ref-docs/federation-api/
https://github.com/kubernetes/website/pull/13363

kubectl, API, and components are all failing for various reasons when following the instructions. Working with @tengqm and @kubernetes/sig-docs-en-owners to review / fix / improve the documentation.

cc/ @zacharysarah @spiffxp @steveperry-53

**Comment by DanyC97** [comment]
@jimangel i suspect https://github.com/kubernetes/website/issues/13426 has the same root cause ?

**Comment by jimangel** [comment]
I'd like to close this before 1.15 drops, but there's still some work left to be done, such as figuring out direction on fedv1 docs and some other minor PRs I've seen come in correcting the ref-gen docs. I'm going to help where I can, but I'll look for @MAKOSCAFEE to help complete this.
/assign @MAKOSCAFEE

**Comment by jimangel** [comment]
@makoscafee after you successfully generate the reference docs for 1.15 (and ensure documentation is exact), feel free to ping me to close.

**Comment by makoscafee** [comment]
Sure, I will ping you when is done ...

**Comment by makoscafee** [comment]
Planning on closing milestone 1.15, reference docs were generated. But not clear of the process as I was able to only generate API reference while components reference page generation is a problem still. I think I will need to work with @kbhawkey and @tengqm to update documentation of the process.

**Comment by tengqm** [comment]
Please feel free to file issues at kubernetes-incubator/reference-docs .

**Comment by makoscafee** [comment]
There is already work in progress for this at  https://github.com/kubernetes/website/issues/14111
/milestone clear

**Comment by jimangel** [comment]
/close

moving discussion to #14111
