### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/labels/

### ISSUE THREAD

**Issue by OmarLatrach** [kubernetes/website#13391]
I can't select pods using:
$ kubectl get pods -l 'env in (prod, qa)'
Instead, I get: **error: name cannot be provided when a selector is specified**

**Comment by palnabarun** [comment]
I think you are specifying both `name` and `label selector`. `kubectl` does not allow you to get resources while specifying both name and a selector string.

Let's take an example, by creating a deployment with image `nginx` and labels `app=nginx,env=dev`

```
$ kubectl run nginx --labels='app=nginx,env=dev' --image=nginx
deployment.apps/nginx created

$ kubectl get pods -l 'app=nginx'
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6d47d55fd8-sfj7r   1/1     Running   0          15s

$ kubectl get pods nginx-6d47d55fd8-sfj7r
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6d47d55fd8-sfj7r   1/1     Running   0          20s

$ kubectl get pods -l 'app=nginx' nginx-6d47d55fd8-sfj7r
error: name cannot be provided when a selector is specified
```

I hope this clears your doubt.
