### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/nodes/

### ISSUE THREAD

**Issue by steedzuo** [kubernetes/website#13415]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#node-v1-core

**Proposed Solution:**
change the link

**Page to Update:**
https://kubernetes.io/...

1.14

**Comment by tengqm** [comment]
Fixed.
