### ISSUE TITLE
Link to metrics-server is 404

### ISSUE THREAD

**Issue by pmcfadden** [kubernetes/website#13445]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
linking to metrics server from https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/ is a 404

**Proposed Solution:**
change the link from core-metrics-pipeline to resource-metrics-pipeline

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by tengqm** [comment]
Solved.
