### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

### ISSUE THREAD

**Issue by vikramsp** [kubernetes/website#13458]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
The links to the spec format for pod and deployment are not working. Clicking on them returns a 404. Here is the culprit line:

> For example, the spec format for a Pod object can be found here, and the spec format for a Deployment object can be found here.

**Proposed Solution:**
Correct the links to point to valid pages.

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
This was caused by API reference not generated. Being fixed. Feel free to reopen if the problem persists.
