### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

### ISSUE THREAD

**Issue by enGMzizo** [kubernetes/website#13452]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
[The Kubernetes API Reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/) url is not working

**Proposed Solution:**
Generate the new Documentation 

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

**Comment by tengqm** [comment]
Fixed by #13442
