### ISSUE TITLE
Typo in the deprecation warning

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#13460]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

There's a typo in the deprecation warning:

<img width="1035" alt="Screen Shot 2019-03-26 at 12 49 16 PM" src="https://user-images.githubusercontent.com/3210446/55028789-d7d93a00-4fc5-11e9-839a-36deaaf403d6.png">

**Proposed Solution:**

1. Update the deprecation warning text so that it ends, `"see the "`.
    - Fix this line: https://github.com/kubernetes/website/blob/master/i18n/en.toml#L4
2. Notify localization stakeholders in the PR.
    - In the initial PR description, add mentions to `sig-docs-**-owners` for every current localization.

**Page to Update:**

https://github.com/kubernetes/website/blob/master/i18n/en.toml#L4

**Comment by bhuvnesh13396** [comment]
Hi @zacharysarah ,
I would like to work on this. I am a newbie to opensource community.

**Comment by rahulkrishnanfs** [comment]
Shall I fix this issue?

**Comment by rahulkrishnanfs** [comment]
kind/bug

**Comment by rahulkrishnanfs** [comment]
I am working on this issue

**Comment by rahulkrishnanfs** [comment]
fixed this issue

**Comment by rahulkrishnanfs** [comment]
close
