### ISSUE TITLE
Issue with k8s.io/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by vsoutherner** [kubernetes/website#13506]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
During pod creation if a pod is bound to a role granting use of a "default" pod security policy that it will fail under but is also bound to a role whose name is alphabetically after default it will still assign default. 

**Proposed Solution:**
change 'selects policies in the following order' to 'selects policies according to the following criteria' or alter to code to follow the order. 

**Page to Update:**
https://kubernetes.io/...

1.13.4

Successfully tested by first binding the trident service account in the trident namespace to a clusterrole trident-psp that granted use to the trident-psp that allows 'RunAsAny'(root). The trident pod is created. Then bound the system:serviceaccounts group to the default-psp clusterrole allowing use of the default pod security policy. After trident pod deletion the pod state is Waiting due to CreateContainerConfigError, the error being 'Error: container has runAsNonRoot and image will run as root'. If I then recreate the 'trident-psp' pod security policy as 'a-trident-psp' and delete the pod it will be assigned the a-trident-psp podsecuritypolicy and run.  In theory since the 'trident-psp' PSP would allow the pod to be created without altering it and 'default' wouldn't then trident-psp should be chosen regardless of name if the first rule is truly first, 'If any policies successfully validate the pod without altering it, they are used.'

**Comment by SupriyaSirbi** [comment]
Submitted PR for the same. Thanks
