### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/docker-cli-to-kubectl/

### ISSUE THREAD

**Issue by napcs** [kubernetes/website#13502]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The command

```
kubectl run --image=nginx nginx-app --port=80 --env="DOMAIN=cluster"
```
results in a deprecation warning:

```
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
```

**Proposed Solution:**

Update documentation to recommend the most appropriate Docker equivalent. The previous version suggested it would create a Deployment, but the suggested approach from the deprecation notice seems to indicate it will create a Pod.

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/docker-cli-to-kubectl/

**Comment by DanyC97** [comment]
thank you for raising the issue @napcs .

this issue fits under the umbrella of https://github.com/kubernetes/website/issues/12090 which is a wider effort where it touch on the docs as well as the code
