### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/kubectl/

### ISSUE THREAD

**Issue by vic-son** [kubernetes/website#13510]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The "SEE ALSO" links are not working. i.e. https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_run.md produces a 404 error

**Proposed Solution:**
The links need fixing to point to the correct pages

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/kubectl/

**Comment by manyatripathi** [comment]
I am working on this to fix it

**Comment by rlenferink** [comment]
Just noticed this issue existed as well. 
Thanks for noticing 🎉

This is fixed in https://github.com/kubernetes/website/pull/13579
