### ISSUE TITLE
Translate tasks/job/ in Japanese

### ISSUE THREAD

**Issue by skikkh** [kubernetes/website#13532]
# Translate tasks/job/ in Japanese

**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No tasks/job/ in Japanese.

**Proposed Solution:**
Translate tasks/job/ in Japanese.
Copy from en content and Update `content/ja/docs/tasks/job/automated-tasks-with-cron-jobs.md`.

**Page to Update:**
https://kubernetes.io/ja/docs/tasks/job/automated-tasks-with-cron-jobs/

**Comment by cstoku** [comment]
@skikkh こちらの翻訳、着手済みでしょうか？
未着手であれば  `1.15` のマイルストーンに移そうかと思うのですがいかがでしょう？
（リリースでも大丈夫です）

**Comment by skikkh** [comment]
@cstoku すいません、近日時間が取れなく着手できていませんでした。
移す形でお願いしていただければと思います。お手数おかけして申し訳ありません。

**Comment by cstoku** [comment]
@skikkh こちら作業いかがでしょうか？

**Comment by cstoku** [comment]
@jkkitakita こちら後1週間でPRが作成できない場合はCloseとさせてください。それより早く無理そうという判断であればその旨こちらに投稿、またはCloseしていただければと思います。
またCloseになった後、再度着手する場合は最新のマイルストーンのコンテンツを元に翻訳作業を進めていただければと思います！

**Comment by cstoku** [comment]
@skikkh こちら後1週間でPRが作成できない場合はCloseとさせてください。それより早く無理そうという判断であればその旨こちらに投稿、またはCloseしていただければと思います。
またCloseになった後、再度着手する場合は最新のマイルストーンのコンテンツを元に翻訳作業を進めていただければと思います！

**Comment by skikkh** [comment]
@cstoku 中々時間が取れなくこちら一旦Closeさせていただきたいです。
何度もお手数をおかけしてしまい申し訳ないです。
また、時間ができた際にはよろしくおねがいします。

**Comment by cstoku** [comment]
それではCloseさせていただきます。
機会がある際にはぜひお願いします！:smile:

/close
