### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by yggdrasildy** [kubernetes/website#13544]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Run tutorial on my iPad. Was not Able to fill in the questionaire at the end: could not scroll past først question.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
Unfortunately this is a limitation of katacoda and not the documentation

/triage support
/close
