### ISSUE TITLE
Missing "Manifest" from glossary k8s.io/docs/reference/glossary/

### ISSUE THREAD

**Issue by moltar** [kubernetes/website#13546]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

Glossary is missing the term "Manifest".

I am not 100% sure if this is a core term, but I do see it used a lot.

**Proposed Solution:**

Add "Manifest" as a glossary term.

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/

**Comment by moltar** [comment]
Usage examples:

 * Process the directory used in `-f`, `--filename` recursively. Useful when you want to manage related manifests organized within the same directory. 

 * `kubectl apply --prune -f manifest.yaml -l app=nginx`

 * For instance, assume there is a directory project/k8s/development that holds all of the manifests needed for the development environment, organized by resource type. ([source](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/))

**Comment by sftim** [comment]
That's a good suggestion @moltar 
/language en
/help
