### ISSUE TITLE
Add documentation snip about PLEG

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#13555]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I recently came across this kubelet error: ` skipping pod synchronization - [PLEG is not healthy: pleg was last seen active 6m11.84971921s ago; threshold is 3m0s]` and it was the first time I've **ever** heard of "PLEG" (Pod Lifecycle Event Generator) in my k8s journey.

After searching, I found an [issue](https://github.com/kubernetes/kubernetes/issues/45419), old [blog post](https://kubernetes.io/blog/2016/03/1000-nodes-and-beyond-updates-to-kubernetes-performance-and-scalability-in-12/) announcing it in 1.2, and a [community proposal](https://github.com/kubernetes/kubernetes/blob/release-1.3/docs/proposals/pod-lifecycle-event-generator.md) that outlined (very well) exactly what is is / does. However, nothing in the main kubernetes.io site.

**Proposed Solution:**
I think a snippet about what PLEG is/does under either container lifecycle or kubelet related concepts would be appropriate.

This could be added to our Q2 milestone if not a quick fix for a good `first issue`

**Page to Update:**
https://kubernetes.io/docs/concepts/

**Comment by Guaris** [comment]
I would like to take this.

**Comment by jimangel** [comment]
Great! It's all you @Guaris!

I can't assign you to the issue since you're not a Kubernetes org [member](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements), but that doesn't stop you from submitting the PR!

**Comment by zacharysarah** [comment]
Just a note--anyone can submit a PR while an issue is still open!

**Comment by thecrudge** [comment]
PR #13805

**Comment by jimangel** [comment]
Thanks @thecrudge!
/close
