### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by serdec** [kubernetes/website#13566]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When trying to connect to Cassandra, the datastax driver launches a warning saying that it cannot reach the Cassandra nodes and therefore create the pool.
This is because the Cassandra cluster is made of nodes (kubernetes pods) with private IPs, hence every connection from outside the cluster is not able to create the pool (it connects to just one node). 

How do you cope with that? Is running the application that needs to connect to Cassandra inside a Kubernetes cluster the only solution?

Thanks

Kubernetes Version: 1.11

**Comment by tengqm** [comment]
@serdec If you want to connect to the app from outside a cluster, you may want to consider creating a [Service](https://kubernetes.io/docs/concepts/services-networking/service/) for it and exposing that service.
