### ISSUE TITLE
No Korean translation for docs/contribute/generate-ref-docs/ in Korean

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#13576]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No Korean translation for 
https://kubernetes.io/docs/contribute/generate-ref-docs/ 

**Proposed Solution:**
Translate the page in Korean.

1) Copy _index.md file in content/en/docs/contribute/generate-ref-docs/ to content/ko/docs/contribute/generate-ref-docs/
2) Translate English contents in the _index.md file in Korean 
> title: **Reference docs overview** (translation in Korean)
> main_menu: true
> weight: 80
> 
> **Much of the Kubernetes reference documentation is generated from Kubernetes
> source code, using scripts. The topics in this section document how to generate
> this type of content.** (translation in Korean)
3) Make a PR and resolve comments from reviewers

**Page to Update:**
https://kubernetes.io/ko/docs/contribute/generate-ref-docs/

### This issue is to promote a new contributor for Korean localization.

Please leave a comment if you wish to make a first contribution on Korean localization.
A Korean localization team member will assign this issue to a new contributor. (Please don't start in advance)

You can get additional information on Korean localization from following links.

(1) 한글화 팀 Slack 채널: Kubernetes Slack 가입 후, #kubernetes-docs-ko 채널 참여하여 문의
(2) 한글화 팀 회의: 매주 화요일 22시 ~ 23시. Zoom(#kubernetes-docs-ko에 링크 공유). (회의록: https://goo.gl/1gZ45u)
(3) 문서 기여 방법: https://github.com/kubernetes/website/blob/master/README-ko.md
(4) 한글화 스타일 가이드: https://kubernetes.io/ko/docs/contribute/localization_ko/

/language ko
/good-first-issue
/help

**Comment by lapee79** [comment]
Hello @seokho-son 
I want to contribute Korean localization.
I made PR #13565 
Please tell me how I process this.

**Comment by seokho-son** [comment]
@lapee79 Sorry for the late reply. Sure you can take this issue. Please start to work and make a PR. You can use guides(links) provided in this issue. If you have any questions regarding Korean localization contribution, you can make comments in this issue or come to slack #kubernetes-docs-ko channel as well. Thank you for your contribution!!
