### ISSUE TITLE
Clean up install-kubectl page

### ISSUE THREAD

**Issue by cody-clark** [kubernetes/website#13577]
**Problem:**
This page is kind of a mess. Since each method of installation is a the same heading level as the Configuring section, it's easy to overlook. **PR in progress**

**Proposed Solution:**
1. Group installation methods by OS
2. Make OS types h2s and their methods h3s to clean up the toc and provide better hierarchical differentiation
3. Add heading to make clear that kubectl autocompletion is optional / provide a section for other optional configurations

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by daminisatya** [comment]
@cody-clark Is this issue still in progress?
