### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by cmanania** [kubernetes/website#13585]
**This is a Bug Report**

**Problem:**
I followed these directions to setup an ECTD HA cluster, using CoreOS, but the ETCD cluster will not start. What am I doing wrong? I am using CoreOS and all the commands worked except for the last one checking the cluster health. Please help

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
are you getting any errors. also what version of kubeadm / kubernetes are you using?
/priority awaiting-more-evidence

**Comment by cmanania** [comment]
Thank you for responding

Kubeadm/K8 = v1.14.0
ETCD_TAG = v3.3.10

Error:
core@k8-etcd00 ~ $ docker run --rm -it \
> --net host \
> -v /etc/kubernetes:/etc/kubernetes quay.io/coreos/etcd:${ETCD_TAG} etcdctl \
> --cert-file /etc/kubernetes/pki/etcd/peer.crt \
> --key-file /etc/kubernetes/pki/etcd/peer.key \
> --ca-file /etc/kubernetes/pki/etcd/ca.crt \
> --endpoints https://${HOST0}:2379 cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.140.26.2:2379: connect: connection refused

error #0: dial tcp 10.140.26.2:2379: connect: connection refused

Environment:

  *   3 CoreOS VMs running on VMware
  *   All nodes pingable from each other and have access to Internet
  *   CNI, CRI, kubeadm, kubelet all installed with no errors.
  *   Configured according to (https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/)
  *   The only deviation was IPs and ETCD names NAMES=("k8-etcd00" "k8-etcd01" "k8-etcd02")

Chris Anania
IT Manager, Hosting Services
P: 800.772.2260 ext:4350

www.tylertech.com<https://www.tylertech.com>

**Comment by tengqm** [comment]
> dial tcp 10.140.26.2:2379: connect: connection refused

looks like a firewall issue?

**Comment by cmanania** [comment]
nope

Chris Anania
IT Manager, Hosting Services
P: 800.772.2260 ext:4350

www.tylertech.com<https://www.tylertech.com>
