### ISSUE TITLE
Delete kubernetes.github.io site

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#13583]
It still seems like there's a website out there called https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/ serving very old content.

Can we please wipe this site out?

**Comment by ahmetb** [comment]
My bad, it's coming from github.com/kubernetes/nginx-ingress repo! It really looked like kubernetes documentation.

Looks like nginx-ingress repo hosts its own documentation site. Feel  free to close.

**Comment by rlenferink** [comment]
Thanks for noticing and clarifying 🎉 
I'll close this one as it is correct behavior.

/close
