### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/

### ISSUE THREAD

**Issue by mrandi** [kubernetes/website#13611]
Please describe what are workloads and if are a real resource or just a concept.

**Comment by rahulkrishnanfs** [comment]
@mrandi Could you please describe what improvement you are looking for ?

**Comment by mrandi** [comment]
@rahulkrishnanfs of course! I hope this will clarify a bit.
I'm interested in building an application thats create an overview of the workloads currently running on the cluster. 
My assumptions are the following.
As far I understood, workloads doesn't really exists, in the sense that they are not queryable.
Workload seems to be more a logical aggregation of resources. But workload itself, are not really visible in the cluster as resource.

Ideally I would like to create a report for any workload creation, update and deletion but I'm not sure if the workloads concept can help me here.

Therefore I would like to get some more clarification of the concept behind and how I could work with this. I'm not really sure how are workloads implemented in k8s, if at all.

**Comment by sftim** [comment]
>  Workload seems to be more a logical aggregation of resources. But workload itself, are not really visible in the cluster as resource.

That's about right. There's maybe a place to explain how, for humans, there are labels that let people group resources together, ie signposting the reader to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels
/priority backlog
