### ISSUE TITLE
Add rebalancing details to federation replicaset doc

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/website#1362]
As discussed with @quinton-hoole We need to add more details to http://kubernetes.io/docs/user-guide/federation/replicasets/ especially regarding the replica-set-preferences annotation.

I hadnt added them last time since I still wasnt sure how they work. Ref: https://github.com/kubernetes/kubernetes/issues/33312.

cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Assigning to @mwielgus since he knows it best

**Comment by nikhiljindal** [comment]
Ping @mwielgus

**Comment by jaredbhatti** [comment]
Ping.  Is this still in progress?  Ignored?  If I don't see any movement on this issue in two weeks I will close.

**Comment by quinton-hoole** [comment]
The details @nikhiljindal requires are in the rescheduling section of:

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/federated-replicasets.md

Please don't close this until it's complete.

**Comment by tengqm** [comment]
/close

Federation docs doesn't belong here in kubernetes/website now.
