### ISSUE TITLE
Subscribing to the newsletter opens tons of spam popups

### ISSUE THREAD

**Issue by mysticaltech** [kubernetes/website#13630]
**What happened**:

While visiting https://kubernetes.io, I decided to subscribe to the newsletter, using the subscription field at the bottom. All good.

It took me to the typical Mailchimp list-manage.com page to confirm subscription. All good. 

**What you expected to happen**:

Then clicking on the "return to website" button, I was taken to http://kubeweekly.com which opened many spammy ads, including the typical "your mac is infected with a virus" one.

**How to reproduce it (as minimally and precisely as possible)**:

Subscribe to the newsletter with a new email and click the "return to website" button.

**Anything else we need to know?**:

Maybe this domain was yours before and expired?

**Comment by kbarnard10** [comment]
Return to website button is now updated to return to Kubernetes.io
