### ISSUE TITLE
[WIP] Translate /docs/concepts/containers/images/ in Japanese

### ISSUE THREAD

**Issue by kaedemalu** [kubernetes/website#13646]
# Translate /docs/concepts/containers/images/ in Japanese

**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No /docs/concepts/containers/images/ in Japanese.

**Proposed Solution:**
Translate /docs/concepts/containers/images/ in Japanese.
Copy from en content and Update `website/content/ja/docs/concepts/containers/images.html`.

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/containers/images/

**Comment by cstoku** [comment]
@kaedemalu こちらの翻訳、着手済みでしょうか？
未着手であれば  `1.15` のマイルストーンに移そうかと思うのですがいかがでしょう？
（リリースでも大丈夫です）

**Comment by kaedemalu** [comment]
@cstoku 
こちらはまだ翻訳中で時間かかるかもしれないので、マイルストーン移していただければと思います！

gitで少し不明点あるので、こちらと合わせてslackさせていただきます↓
https://github.com/kubernetes/website/issues/13379

**Comment by cstoku** [comment]
@kaedemalu こちら作業いかがでしょうか？

**Comment by cstoku** [comment]
@kaedemalu こちらのコンテンツについては翻訳作業自体は着手している感じでしょうか？

**Comment by cstoku** [comment]
着手中、PRをWIPつけて作成してもらう。

**Comment by nasa9084** [comment]
/retitle [WIP] Translate /docs/concepts/containers/images/ in Japanese

**Comment by cstoku** [comment]
こちら、一旦単にMilestoneから外すだけにします。
/milestone clear

**Comment by sftim** [comment]
/priority backlog
/kind feature

NB the issue isn't WIP; the pull request might be.

**Comment by inductor** [comment]
@kaedemalu どうすか
