### ISSUE TITLE
Debug Services page suggests buggy version of Busybox

### ISSUE THREAD

**Issue by NickWilton** [kubernetes/website#13651]
**This is a Bug Report**

**Problem:**
The ["Debug Services"](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/) page suggests running an interactive Busybox image as follows:
```
kubectl run -it --rm --restart=Never busybox --image=busybox sh
```

However, due to an [upstream regression](https://bugs.busybox.net/show_bug.cgi?id=11161) with Busybox version 1.29 the **nslookup** commands will fail on a healthy kubernetes cluster; leading the reader to erroneously conclude the DNS is broken in their cluster.

**Proposed Solution:**

Change the suggestion to an Alpine image, instead of Busybox.
```
kubectl run -it --rm --restart=Never alpine --image=alpine sh
```

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by SupriyaSirbi** [comment]
Submitted above PR for the same. Thanks

**Comment by rahulkrishnanfs** [comment]
I am looking into this issue

**Comment by daminisatya** [comment]
@SupriyaSirbi Is this good to close?

**Comment by NickWilton** [comment]
Yes. Good to close.

-Nick
