### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by cixuuz** [kubernetes/website#13650]
**This is a Bug Report**

**Problem:**
By following the tutorial, I tried to use ```cqlsh```. It shows the following error:

```
>  kubectl exec -it cassandra-0 cqlsh
> No appropriate python interpreter found.
> command terminated with exit code 1
```

**Proposed Solution:**
I replaced the docker image to latest one in docker hub and removed ```Readiness probe``` in stateful yaml file.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/cassandra/

**Comment by sftim** [comment]
Thanks for the feedback
/language en
