### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/logging/

### ISSUE THREAD

**Issue by aritro90** [kubernetes/website#13656]
**This is a Bug Report**

**Problem:**
https://github.com/samsung-cnct/logrotate (which is referenced in this site) is throwing 404 error

**Proposed Solution:**
Need to remove the hyperlink from "An example" in the below statement:
_An example of this approach is a small container running logrotate periodically. However, it’s recommended to use stdout and stderr directly and leave rotation and retention policies to the kubelet._

**Page to Update:**
k8s.io/docs/concepts/cluster-administration/logging/

**Comment by rahulkrishnanfs** [comment]
I am looking into the issue

**Comment by Vageesha17** [comment]
i am working on this issue..as it would be a good start.

**Comment by daminisatya** [comment]
@Vageesha17 Can you close the issue if this is fixed?

**Comment by Vageesha17** [comment]
close #13764
