### ISSUE TITLE
link to the latest docs will be broker when deprecated = false in config.toml

### ISSUE THREAD

**Issue by rahulkrishnanfs** [kubernetes/website#13660]
**This is a Bug Report**

**Problem:**
Link to the latest docs will be broken when deprecated = false in config.toml [https://github.com/kubernetes/website/blob/release-1.14/config.toml#L73]

This  issue is resolved in the #13649 

**Proposed Solution:**
```
<a href="{{ .Site.Params.currentUrl }}">{{ T "latest_version" }}</a>
```
Use .Site.Params 

**Page to Update:**
https://github.com/kubernetes/website/blob/release-1.14/layouts/shortcodes/deprecationwarning.html#L8

**Comment by rahulkrishnanfs** [comment]
I am working on this issue

**Comment by daminisatya** [comment]
@rahulkrishnanfs Can you close the issue if this is fixed?
