### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tls/certificate-rotation/

### ISSUE THREAD

**Issue by timstoop** [kubernetes/website#13667]
This page says the following:

```
... If the certificate signing requests meets specific criteria, it will be auto approved by the controller manager, then it will have a status of Approved. ...
```

But it doesn't provide any information on what those criteria are or where to find them. Some additional guidance here would be appreciated.

**Comment by sftim** [comment]
Thanks for the suggestion @timstoop. In the future, revised [pages on Controllers](https://github.com/kubernetes/website/issues/4135) might have something to add (and link to) once done.

/language en
