### ISSUE TITLE
Subscribe button on the home page is not aligned.

### ISSUE THREAD

**Issue by Gaurav-Punjabi** [kubernetes/website#13672]
**This is a bug report.**

**Problem**
The subscribe button at the bottom of the home page is not aligned properly.

**Screenshot** 
![image](https://user-images.githubusercontent.com/36587580/55702024-d6ab0280-59f2-11e9-854d-313a9d7a79cc.png)

**Expected Output**
![image](https://user-images.githubusercontent.com/36587580/55702228-94ce8c00-59f3-11e9-9b16-06e565d99a18.png)

**Proposed Solution**
The button should be vertically aligned with the input field with a left margin.

**Comment by daminisatya** [comment]
@Gaurav-Punjabi Thank you for finding the bug ✨ Would you like to open a PR for this?

**Comment by Gaurav-Punjabi** [comment]
> @Gaurav-Punjabi Thank you for finding the bug  Would you like to open a PR for this?

Yeah sure. I'll fix the issue.

**Comment by SupriyaSirbi** [comment]
Hello All,

I am working on this issue.

Thanks

**Comment by sftim** [comment]
Fixed via #14175
/close
