### ISSUE TITLE
Need definitive example of audit policy use 

### ISSUE THREAD

**Issue by gamename** [kubernetes/website#13673]
**This is a Feature Request**

**What would you like to be added**

In the "Audit Policy" section on this page: 
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

...there needs to be an explicit example of how to implement the audit policy.  In other words, there should be an example showing how to pass the file to correctly create a policy.   

**Why is this needed**

If the user simply copies the file "audit/audit-policy.yaml" to a file and then tries to pass it to a `create`, you get the following error:

```
$ kubectl create -f ./audit.yaml
error: unable to recognize "./audit.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1"
```

This does not appear to be a functionality bug, but rather an error in proper use.  Therefore, the documentation should spell out exactly how this policy file should be used.  

**Comments**

**Comment by dev1983** [comment]
i am also facing it
