### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

### ISSUE THREAD

**Issue by garystafford** [kubernetes/website#13683]
**This is a Bug Report**

**Problem:**
The 'kubectl autoscale' link to GitHub in the sentence is bad: 'Now that the server is running, we will create the autoscaler using [kubectl autoscale](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_autoscale.md).'

**Proposed Solution:**
Update to correct link.

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by manyatripathi** [comment]
I am lookinginto this..... As I am new so this feels a goot start point.
