### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by esharmony** [kubernetes/website#13711]
**This is a Bug Report**

**Problem:**
Just editing the ingress in way proposed seems to overwrite the rules of the second.
You end up losing the first path

**Proposed Solution:**
Create a ingress with a modified name

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
/close

This issue has been addressed
