### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by niklasholm** [kubernetes/website#13722]
**This is a Bug Report**

**Problem:**
The table under the heading *Install a Hypervisor* says you need VirtualBox **or** Hyper-V on Windows, but under the heading *Windows* it says you need Hyper-V. This is inconsistent, is VirtualBox supported or not?

**Proposed Solution:**
Clarify if VirtualBox is supported (without Hyper-V).

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube

**Comment by kbhawkey** [comment]
Hello @niklasholm. Yes, minikube is supported with VirtualBox (verified Windows 10)!
