### ISSUE TITLE
https://dl.k8s.io/v1.14.0/kubernetes-src.tar.gz is a tarbomb

### ISSUE THREAD

**Issue by jhammond-indeed** [kubernetes/website#13728]
**This is a Bug Report**

**Problem:** The kubernetes-src tar archive (https://dl.k8s.io/v1.14.0/kubernetes-src.tar.gz) linked from https://kubernetes.io/docs/setup/release/notes/#downloads-for-v1-14-0 is a tarbomb:
```
$ tar -tzf kubernetes-src.tar.gz | head
.bazelrc
.generated_files
.gitattributes
.github/
.github/ISSUE_TEMPLATE/
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/failing-test.md
.github/ISSUE_TEMPLATE/support.md
.github/OWNERS
```

tarbombs are unexpected behavior and may have unfortunate side-effects for users who don't look before they leap.

**Proposed Solution:** Please create a tar archive that expands to a single directory matching the basename of the archive (`kubernetes-src`).

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@jhammond-indeed I suspect that you'll need to request that improvement against a different repo.
This GitHub repo tracks https://kubernetes.io/ and pages on there, whereas you're asking for the Kubernetes source code artifact to have different contents.

I'm happy to signpost you to the [project](https://github.com/kubernetes) and its list of repos. https://github.com/kubernetes/kubernetes is where I'd look first.

/triage support

**Comment by jhammond-indeed** [comment]
> whereas you're asking for the Kubernetes source code artifact to have different contents.

Well, that's not exactly what I was asking, but whatever.

**Comment by dims** [comment]
the bazel based kubernetes-src.tar.gz seems to have the prefix. will check the other location where we build the same kubernetes-src.tar.gz

```
dims@bigbox:~/go/src/k8s.io/kubernetes$ make bazel-release
dims@bigbox:~/go/src/k8s.io/kubernetes$ tar -tvzf bazel-bin/build/release-tars/kubernetes-src.tar.gz | more
drwxr-xr-x 0/0               0 1999-12-31 19:00 kubernetes/
-rw-r--r-- 0/0            3572 1999-12-31 19:00 kubernetes/.bazelrc
-rw-r--r-- 0/0             785 1999-12-31 19:00 kubernetes/.generated_files
-rw-r--r-- 0/0             381 1999-12-31 19:00 kubernetes/.gitattributes
```

**Comment by dims** [comment]
@jhammond-indeed sorry this indeed was something we had to deal with in kubernetes/kubernetes repo as @sftim mentioned, i've filed a PR. thanks for the issue.

**Comment by BenTheElder** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/78667, future releases should have this.
