### ISSUE TITLE
typo in pod disruption page

### ISSUE THREAD

**Issue by shub-asa1** [kubernetes/website#13741]
**This is a Bug Report**

**Problem:**
There is a punctuation error in this line of kubernetes docs
No downtime, but may be costly both for the duplicated nodes, and for human effort to orchestrate the switchover.
**Proposed Solution:**
removing unnecessary commas or restructure whole sentence.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/disruptions/

**Comment by shub-asa1** [comment]
Hi,
I am new to k8 community and just trying to do some contribution .I can fix this issue.

**Comment by daminisatya** [comment]
Please feel free to open a PR and reference it to the issue.

Also, welcome to Kubernetes @shub-asa1 ✨
