### ISSUE TITLE
Propose to merge release-1.12 into master

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13745]
sig-docs-zh team has worked on release-1.12 for quite a long time, we should seriously think about merge the branch to master and work on the release-1.13 (release-1.14 was out recently).

This issue is created to address the effort of doing the merge and serve as place to discuss it.

/cc @zacharysarah @kubernetes/sig-docs-zh-owners 
/cc @xichengliudui @SataQiu @tengqm

**Comment by zacharysarah** [comment]
Looking at the list of [open Chinese language PRs](https://github.com/kubernetes/website/pulls?q=is%3Aopen+is%3Apr+label%3Alanguage%2Fzh), I see PRs against `release-1.12` (#13234, #13500) and `master` (#13298, #13251). Have you been monitoring PRs to ensure that they're merged to the same branch?

**Comment by xichengliudui** [comment]
Agree with, about open Chinese PRs.

* Merge the currently mergable PRs
* Turn off PRs that have not responded for a long time

**Comment by SataQiu** [comment]
I agree with @chenrui333 .
But as @zacharysarah said, there may be some problems in this process, such as conflicts. 
Is there a good way to deal with these problems?

**Comment by chenrui333** [comment]
Certainly, we definitely need to address the opening PRs (especially the ones with base branch as release-1.12). I do monitor the open PRs. :)

This issue can be a place that we can track down the process as it goes.

Regarding the merge conflicts, we can fix as it goes (think about the sig-docs release, it would be like that). But I do think we should consider the contributors' activities, in the sense of Github's approach of counting the contributions would be against the master branch. My preference would be merge commit instead of `prow`'s `squash-and-merge` way.

Let me know if that makes sense.

**Comment by xichengliudui** [comment]
+1

**Comment by chenrui333** [comment]
Kicking off a slack discussion on this: https://kubernetes.slack.com/archives/CA1MMM1HU/p1555973690018400

**Comment by chenrui333** [comment]
checkin

**Comment by chenrui333** [comment]
This work has been done, so close this.

/close
