### ISSUE TITLE
security-context.yaml files are not equal

### ISSUE THREAD

**Issue by hmlkao** [kubernetes/website#13740]
**Problem:**
Content of files https://k8s.io/examples/pods/security/security-context.yaml and https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/security/security-context.yaml are not equal.

So commands mentioned after pod creation return different results.

**Page to Update:**
k8s.io/docs/tasks/configure-pod-container/security-context/

**Comment by rajeshdeshpande02** [comment]
@hmlkao I don't see any difference between GitHub file and example code given on doc page. Also, there should not be the difference as document refers to github code for display.

**Comment by hmlkao** [comment]
My fault, I checked it twice and always wrong... I have probably started `pods/security/security-context-2.yaml` which is based on image `gcr.io/google-samples/node-hello` and was confused that commands return different results.
