### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by Ragzputin** [kubernetes/website#13746]
**This is a Bug Report**

**Problem:**
This is not a bug, more of an English language issue. The explanations in this page (like many others) are hard to understand.

**Proposed Solution:**
I have simplified the explanations under the "Kubernetes Cluster" section. Here are my proposed changes. Feel free to improve.

---Proposed Solution Starts Here---
"Kubernetes coordinates clusters of computers. These computers work as a single unit. Kubernetes allows you to deploy applications in containers to a cluster. It does this without tying them to a single machine. To use this deployment model, we first disconnect applications from their individual hosts. In other words, we put them in containers. Such applications are more flexible and available. In past deployment models, we would install applications onto specific machines as packages. These apps would be integrated into the host. Kubernetes distributes and schedules these containers. Kubernetes is open-source and ready to go live.

A Kubernetes cluster consists of two types of resources:
The Master coordinates the cluster
Nodes are the workers that run applications

Summary:

Kubernetes cluster
Minikube

Kubernetes is a production-grade, open-source platform that schedules and executes container clusters."
---Proposed Solution Ends Here---

Keep it simple!

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
Ill take it

**Comment by thecrudge** [comment]
#13831
