### ISSUE TITLE
Want to the understand the algorithm or logic behind pods consuming the nodes

### ISSUE THREAD

**Issue by MBalasubramanian** [kubernetes/website#13748]
We would like to know the algorithm or logic behind the pods getting shuffled between different worker nodes, is there any known threshold for each worker nodes to move a pod from itself(assume a worker node is at 90% usage) to another worker node which is found to be having comparatively more space on it, we have noticed that in our setup(3 master with 30 worker nodes), few of the nodes are frequently hitting 90% and above, where as there are many worker nodes still with less than 40% usage on it, so want to know on which criteria a pod is moved from one to another and is there anyway to set custom threshold say beyond 75% a worker nodes should not be overwhelmed, please provide suggestions at the earliest as we get hiccups now and then in our production environment.

**Comment by rahulkrishnanfs** [comment]
@MBalasubramanian I would suggest you to post in the slack channel

**Comment by MBalasubramanian** [comment]
> @MBalasubramanian I would suggest you to post in the slack channel

Sure Rahul, can you please ping the slack channel detail, will post there.

**Comment by MBalasubramanian** [comment]
Rahul / Team, please suggest on this question, also recently we deleted pods from a specific node since it was running at 85% plus on CPU side, but the pods going to new nodes does not make any difference and also found istio, few other devops tool sets are running on it which is causing the nodes to be hot all the time, please suggest as node-selector could not be enabled for now.

**Comment by DanyC97** [comment]
@MBalasubramanian as been mentioned by @rahulkrishnanfs there are multiple places where you can ask this type of questions: either on https://discuss.kubernetes.io/ or on K8s slack channels (maybe start with kubernetes-novice channel first)

with that said i'm going to close this issue as is not related to the docs.
/close
