### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/security-context/

### ISSUE THREAD

**Issue by endform** [kubernetes/website#13753]
**This is a Bug Report**

**Problem:**
The discussion of setting linux capabilities doesn't reference that the default-docker apparmor configuration may deny operations such as mount even when the container is granted the SYS_ADMIN capability. This is a possible point of confusion/dead for users.

For me in this case I am new to docker/kubernetes so I was unaware of this default configuration as none of the other quickstart pages I was reading was referencing apparmor or the default config. This lead me to spend more time than necessary researching the issue I had (unable to mount a fuse mount).

**Proposed Solution:**
Link to a discussion page or otherwise call out that users should investigate the apparmor default-docker and how it relates to capabilities.

**Page to Update:**
https://k8s.io/docs/tasks/configure-pod-container/security-context/

**Comment by sftim** [comment]
Thanks for the suggestion @endform 
/language en

I wonder if that page (https://k8s.io/docs/tasks/configure-pod-container/security-context/) should mention AppArmor in its pre-requisites. Would that have helped?
