### ISSUE TITLE
Issue with k8 docs  invalid link referred by "one function" in  k8s.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

### ISSUE THREAD

**Issue by shub-asa1** [kubernetes/website#13760]
**This is a Bug Report**

**Problem:**
Invalid link referred by "One function" in "Most of the common code are located in the framework file that leaves only one function to be implemented for different conversions."
It was supposed to redirect to github page but invalid link reference of "one function" leads to error 404 page not found.

**Proposed Solution:**
Linking "one function" in "Most of the common code are located in the framework file that leaves only one function to be implemented for different conversions." to a valid link that fulfill the context.

**Page to Update:**
k8s.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

**Kubernetes version**
v1.14

**Comment by Shifali-Srivastava** [comment]
I'm working on this issue.
