### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by davidnmbond** [kubernetes/website#13772]
**This is a Bug Report**

**Problem:**
In module 3, step 1, the tutorial gives no indication of how long it will take before the pods are running.  This led to confusion for me.  Why does the command not output the expected result?

**Proposed Solution:**
Indicate the amount of time the student can expect to wait (e.g. "up to 2 minutes").

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

**Comment by palnabarun** [comment]
@daminisatya Can I take this up?

I see that the source code for the page mentioned above is present [here](https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html), but on further investigation I figured that what we need to change here is the Katacoda scenario itself.

Please let me know where can I find the source for the Katacoda scenarios.

**Comment by daminisatya** [comment]
@palnabarun Sure! 😄 Feel free to open a PR!

**Comment by daminisatya** [comment]
Let me check!

**Comment by palnabarun** [comment]
@daminisatya Any luck with that? :)

**Comment by BenHall** [comment]
We've added some improvements in this area that will hopefully provide the users with more insight.

We believe this issue can be closed.
