### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/

### ISSUE THREAD

**Issue by Tonterias** [kubernetes/website#13788]
Hi,

I had problems in the process:

https://stackoverflow.com/questions/55637769/why-am-i-getting-a-crashloopbackoff-on-this-kubernetes-example

And it looks like I'm not the only one, but his solutions does not work for me: https://discuss.kubernetes.io/t/running-tutorial-mysql-example-gives-me-read-only-file-system-error/3197/2

Thanks

**Comment by sftim** [comment]
@Tonterias was there anything that needs changing in https://k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/?
/triage needs-information
