### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/annotations/

### ISSUE THREAD

**Issue by phs** [kubernetes/website#13792]
Hello,

I've been looking for information about the possibility of controlling changes to annotations through authorization such as RBAC.

My use case is a custom controller driven by a CRD. I would like to allow my end-users to create/update/delete CRD instances, but still provide a means for a separate set of empowered users to somehow modify the CRD instance to further unlock sensitive functionality in the controller.  Annotations on the CRD instances writable only by the empowered users might fill that need.

The `kubectl` CLI exposes a separate `annotate` verb, which gives me hope that a separate verb for annotation also exists in the API, where I might bind an RBAC rule.

However it seems I can find nothing in either the RBAC or annotation documentation confirming or denying this.  Are annotations treated separately in the security model?  What are the relevant verbs?

**Comment by DanyC97** [comment]
hi @phs i'd suggest you try to find an answer by asking on https://discuss.kubernetes.io/ or on K8s slack channels 

with that said i'm going to close this issue as is not related to the docs. 
/close

**Comment by DanyC97** [comment]
/reopen

on closer read i think there is some value in clarifying few aspects of the annotation
