### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/kubernetes-api/

### ISSUE THREAD

**Issue by shahamit2** [kubernetes/website#13807]
Is it possible to include one/more example for which utilities(e.g.: kubectl or kubeadm or something else) can take "--runtime-config" parameter?

**Comment by thecrudge** [comment]
Hi @shahamit2 , have you looked at the below documentation:

https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/#advanced-topics

Do you think we should include this in the kubernetes-api page?
