### ISSUE TITLE
Issue with /docs/user-guide/ingress/ regarding `kubectl get ing` output

### ISSUE THREAD

**Issue by miend** [kubernetes/website#1381]
In /docs/user-guide/ingress, `kubectl get ing` is shown to have the following format of output:

```
$ kubectl get ing
NAME                RULE          BACKEND        ADDRESS
test-ingress        -             testsvc:80     107.178.254.228
```

This it out of date. The Rules output with Backend columns are only to be found (to my knowledge) in a `kubectl describe` on the ingress resource. All examples on this page should be updated to reflect up-to-date output.

**Comment by tengqm** [comment]
/remove-lifecycle rotten

Issue is still there.

**Comment by shubheksha** [comment]
Issue still persists. /remove-lifecycle stale

**Comment by SamuelDavidBrown** [comment]
Issue still persists. /remove-lifecycle stale

**Comment by SamuelDavidBrown** [comment]
/remove-lifecycle rotten

Issue still persists.
