### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by pankaj-mymail1** [kubernetes/website#13814]
**This is a Bug Report**
kubectl apply -k ./  -->This command is not working,any specific reason or is there any dependency ?
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by surajsunrays** [comment]
Can be solved
[kustomization .txt](https://github.com/kubernetes/website/files/3084629/kustomization.txt)

 using separating the files for installation. 
Created files are 
1. kustomization.yaml (For Secrets )
2. mysql-depl..... (Same as Provided)
3. wordpress.... (Same as provided)
Applied as :
kubeclt create -f kustomization.yaml      # will Creates the secrets and do same for other 2 files as well.

**Comment by kbhawkey** [comment]
@pankaj-mymail1 , have you tried with kubectl 1.14?

**Comment by surajsunrays** [comment]
Yes. and its working fine for me.

**Comment by pankaj-mymail1** [comment]
> 
> 
> @pankaj-mymail1 , have you tried with kubectl 1.14?

I am running kubernetes 1.13 and kubectl 1.13,can I start using 1.14 it the kubernetes version is 1.13 ?

**Comment by surajsunrays** [comment]
Yeah. you can start using it. for these bug, you can refer this repository. https://github.com/IBM/scalable-wordpress-deployment-on-kubernetes
I tried it my side and everything like PV , PVC all are working fine.
