### ISSUE TITLE
Ask for help! Kubelet always gives an error when starting

### ISSUE THREAD

**Issue by elknode96** [kubernetes/website#13819]
Apr 15 16:32:35 kubernetets-node1 kubelet: I0415 16:32:35.965981   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:32:45 kubernetets-node1 kubelet: I0415 16:32:45.990378   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:32:56 kubernetets-node1 kubelet: I0415 16:32:56.018951   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:33:06 kubernetets-node1 kubelet: I0415 16:33:06.043963   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:33:16 kubernetets-node1 kubelet: I0415 16:33:16.068485   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:33:26 kubernetets-node1 kubelet: I0415 16:33:26.096620   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:33:36 kubernetets-node1 kubelet: I0415 16:33:36.122745   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:33:46 kubernetets-node1 kubelet: I0415 16:33:46.148707   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:33:56 kubernetets-node1 kubelet: I0415 16:33:56.172923   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:34:06 kubernetets-node1 kubelet: I0415 16:34:06.198919   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:34:16 kubernetets-node1 kubelet: I0415 16:34:16.228333   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
Apr 15 16:34:26 kubernetets-node1 kubelet: I0415 16:34:26.253900   18574 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach

**Comment by DanyC97** [comment]
@elknode96 i'm afraid this is not the best place to ask for help, i'd suggest you ask on https://discuss.kubernetes.io/ or slack

**Comment by DanyC97** [comment]
i'll close this issue since is not docs related
