### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/rolling-update-replication-controller/

### ISSUE THREAD

**Issue by mide22** [kubernetes/website#13824]
What stands "NAME" for? Name of deployment? container?

**Comment by hpandeycodeit** [comment]
@mide22 ```NAME``` stands for ```OLD_CONTROLLER_NAME```

Refer to this doc. 
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#rolling-update
