### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/ubuntu/

### ISSUE THREAD

**Issue by tedmoyses** [kubernetes/website#13820]
**This is a Bug Report**

The CDK link to docs 404s

Fix link to CDK docs for K8s installation

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/ubuntu/

**Comment by tedmoyses** [comment]
That shoudl be th elinked with the text 'official documentation'

**Comment by Vageesha17** [comment]
i am wokring on this issue..as it would be a good start.

**Comment by DanyC97** [comment]
/good-first-issue

thank you @Vageesha17 for looking into it, let us know once you have a PR up

**Comment by DanyC97** [comment]
@Vageesha17 thank you for the fix
/close
