### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by zeyaoo-mz** [kubernetes/website#13833]
**This is a Bug Report**

**Problem:**
Comments on these two lines are reversed.
kubectl exec my-pod -- ls /                         # Run command in existing pod (1 container case)
kubectl exec my-pod -c my-container -- ls /         # Run command in existing pod (multi-container case)

It should be:
kubectl exec my-pod -- ls /                           # Run command in existing pod (multi-container case)
kubectl exec my-pod -c my-container -- ls /        # Run command in existing pod (1 container case)

**Proposed Solution:**
It should be:
kubectl exec my-pod -- ls /                           # Run command in existing pod (multi-container case)
kubectl exec my-pod -c my-container -- ls /        # Run command in existing pod (1 container case)

**Page to Update:**
https://kubernetes.io/...

**Comment by rajeshdeshpande02** [comment]
@zeyaoo-mz I do not think the exisitng example is incorrect. '-c' option is generally used with the multi-container pod to specify the container to work on.  So here also '-c' used for multi-container pod which is correct.

**Comment by DanyC97** [comment]
@zeyaoo-mz what @rajeshdeshpande02 said is correct. Let us know if you disagree if not then i'll close the issue
