### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [kubernetes/website#13847]
**This is a Bug Report**

**Problem:**

Command on documentation is incorrect:

_kubectl apply -k ./_

Error: **unknown shorthand flag: 'k' in -k**

**Proposed Solution:**

_kubectl apply -f ./_

**Page to Update:**
k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

**Comment by kbhawkey** [comment]
@AdamSharif-MSFT, see issue #13664. Have you tried v1.14?

**Comment by AdamSharif-MSFT** [comment]
Apologies for the delay, I have a feeling I was using an old version of the client perhaps, but now I can correctly use the _kubectl apply -k_ command, so this issue can be closed. Thanks for your help!
