### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/

### ISSUE THREAD

**Issue by Tonterias** [kubernetes/website#13856]
**This is a Bug Report**

**Problem:** Your example does not work (at least in the GCP current kubernetes version)

**Proposed Solution:**
Delete the PV and use the Storage Class and it works

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none

**Page to Update:**
https://kubernetes.io/...

**Comment by rajeshdeshpande02** [comment]
@Tonterias Thanks for raising the issue. But this documentation is general and not specific to any cloud. So adding a cloud provider specific things here is not good idea. Can you please share errors you are getting so that we can analyze further.
