### ISSUE TITLE
Translate Kubernetes Contribution's Code of Conduct in Bahasa Indonesia

### ISSUE THREAD

**Issue by irvifa** [kubernetes/website#13858]
**This is a Feature Request**

**What would you like to be added**
code-of-conduct.md

**Why is this needed**
Contributions code of conduct is important to be understood before someone contribute to Bahasa Indonesia localization.

**Comments**

**Comment by irvifa** [comment]
/remove-lifecycle stale
do we still need to do this @girikuncoro

**Comment by girikuncoro** [comment]
@irvifa This is part of localization that is less interesting, I guess this doesn't block us from doing things? if so, let's just close it

**Comment by irvifa** [comment]
Okay closed then..

**Comment by sftim** [comment]
https://kubernetes.io/id/community/code-of-conduct/ is still a missing page. This page is important because it provides the CNCF code of conduct, and that is an important element of an inclusive community.

/priority important-longterm

**Comment by girikuncoro** [comment]
sure thanks @sftim for chiming in, we'll pick this in our backlog

**Comment by sftim** [comment]
[Done](https://kubernetes.io/id/community/code-of-conduct/) in #18828
/close
