### ISSUE TITLE
Add PR wrangler process to contributor docs 

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#13864]
## Feature request

**What to add**

1. Identify process-related content from the wiki page for [PR wranglers](https://github.com/kubernetes/website/wiki/PR-Wranglers).
2. Extract process content from the wiki and add it to the [K8s contributor guidelines](https://kubernetes.io/docs/contribute/).
3. Clean up schedule-related content in the wiki.

**Why is this needed?**

We need to add PR wrangler process content to contributor docs, and make the website's contribution guidelines a single source of truth.

We need to make it easy to update the PR wrangler schedule, and to add schedules for similar roles (new contributor ambassadors, chair shadows, issue triage lead).

**Comments**

Talk with @zacharysarah for clarification as needed.

**Comment by DanyC97** [comment]
@shavidissa just a quick note to mention that there is already some info in the [contributor section](https://kubernetes.io/docs/contribute/advanced/#be-the-pr-wrangler-for-a-week) so maybe you want to create its own page to be visible once you merge with the points @zacharysarah made.
