### ISSUE TITLE
Issue with k8s invalid link referred by "this guide" in  docs k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by shub-asa1** [kubernetes/website#13869]
**This is a Bug Report**

**Problem:**
Invalid link referred by "this guide" in "In Kubernetes v1.11.0 and later, you can use kubeadm upgrade diff to see the changes that would be applied to static pod manifests.
To use kube-dns with upgrades in Kubernetes v1.13.0 and later please follow this guide"
It was supposed to redirect to k8's docs page but invalid link reference of " this guide" leads to error 404 page not found.

**Proposed Solution:**
Linking "this guide" in "In Kubernetes v1.11.0 and later, you can use kubeadm upgrade diff to see the changes that would be applied to static pod manifests.
To use kube-dns with upgrades in Kubernetes v1.13.0 and later please follow this guide." to a valid link that fulfill the context.

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
thanks for the PR to fix this!
/close
