### ISSUE TITLE
Define writing style guide for Indonesian translated docs

### ISSUE THREAD

**Issue by girikuncoro** [kubernetes/website#13860]
**This is a Feature Request**

**What would you like to be added**
Translate https://kubernetes.io/docs/contribute/style/style-guide/ and define our own writing style guide

**Why is this needed**
Writing Indonesian docs for technical stuffs is not an easy task, because of the nature of the language and the way we import various English words. We need to standardize the way Indonesian translated docs are written (personas, standardized glossary) with our own opinion. 

**Comments**
This will help onboarding more and more contributors from Indonesian community.

/language id

**Comment by irvifa** [comment]
@girikuncoro how about this issue?

**Comment by girikuncoro** [comment]
This should be owned by @qbl along with the glossary thing. Let's keep on
tracking it.
