### ISSUE TITLE
Update to Hugo 0.55.2

### ISSUE THREAD

**Issue by bep** [kubernetes/website#13873]
I would strongly recommend that you update to the latest Hugo 0.55.2 -- it fixes some relevant issues for this repo.

**Comment by DanyC97** [comment]
curious @bep do you have few examples around relevant issues ? 
/cc @lucperkins

**Comment by bep** [comment]
The main issue I thinking about is in the merging of content for the translated languages, where there now are some duplicated menu items etc. in the non-English language versions.
