### ISSUE TITLE
Issue with k8s invalid link referred by "kubefed unjoin" in docs  k8s.io/docs/tasks/federation/set-up-cluster-federation-kubefed/

### ISSUE THREAD

**Issue by shub-asa1** [kubernetes/website#13871]
**This is a Bug Report**

**Problem:**
Invalid link referred by "kubefed unjoin" in "To remove a cluster from a federation, run the kubefed unjoin command with the cluster name and the federation’s."
It was supposed to redirect to k8's docs but invalid link reference of "kubefed unjoin" leads to error 404 page not found.

**Proposed Solution:**
Linking "kubefed unjoin" in "To remove a cluster from a federation, run the kubefed unjoin command with the cluster name and the federation’s" to a valid link that fulfill the context.

**Page to Update:**
https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/

**Comment by tengqm** [comment]
Fixed by #13871
