### ISSUE TITLE
Tracking the deprecation of Fedv1 API

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#13905]
Federation v1 has been deprecated in favor of Federation v2. I have worked with #sig-multicluster to come up with a plan to phase out the old and bring in the new.

I'm opening this issue to track deprecating the Federation v1 generation docs

- [ x ] Delete all pages generated for Fedv1 (https://kubernetes.io/docs/reference/federation/)
- [ x ] Remove generated Fedv1 docs:
    - https://kubernetes.io/docs/reference/command-line-tools-reference/federation-apiserver/
    - https://kubernetes.io/docs/reference/command-line-tools-reference/federation-controller-manager/
    - https://kubernetes.io/docs/reference/setup-tools/kubefed/
- [ x ] Remove instructions to generate Fedv1 (https://kubernetes.io/docs/contribute/generate-ref-docs/federation-api/)

Out of scope, to be left alone and updated by #sig-multicluster before EOY 2019

- https://kubernetes.io/docs/concepts/cluster-administration/federation/
- https://kubernetes.io/docs/tasks/federation/

Background (from #sig-multicluster slack):

>irfanurrehman   [3 days ago]
https://kubernetes.io/docs/concepts/cluster-administration/federation/
and pages at https://kubernetes.io/docs/tasks/federation/ can be retained until we are up with new placeholder page(s) (positively before kubecon)
>
>jimangel   [2 days ago]
>@marun @irfanurrehman let me know if there's lazy consensus after today's meeting and I will work to remove to generated docs / document. It will be up to someone in #sig-multicluster to work on the fedv2 content. If there's any questions on the style guide or placement - there's always tons of people willing to help in #sig-docs.
>
>irfanurrehman   [2 days ago]
>Hi @jimangel there seems to be consensus on the steps we talked about, in today's meeting. However few stakeholders were absent. As far as I understand this is targeted towards 1.15 release so we seem to have time.
>
>irfanurrehman   [2 days ago]
>Lets delay going ahead with removing the api-docs by 1 more week and I will report back to you next week if you can go ahead with it.

**Wait until after Friday 4/26/19** before taking any action, but I could use some help cleaning this up if anyone is interested!

**Comment by thecrudge** [comment]
Submitted PR #14109

Takes care of most of the first check box. Still need to address tooling and generate instructions.

**Comment by irfanurrehman** [comment]
@jimangel There is consensus on the steps that you mentioned. Thanks for taking this up.

**Comment by irfanurrehman** [comment]
cc @kubernetes/sig-multicluster-misc

**Comment by thecrudge** [comment]
Updated PR #14140

**Comment by claurence** [comment]
@jimangel - this PR has the 1.15 milestone on it - is it expected to merge or this release?  The docs last call milestone is today

**Comment by jimangel** [comment]
lgtm from a `#sig-multicluster` 6/10/2019:
>jimangel  [3 hours ago]
>Can I get a /LGTM on this if it looks good? https://github.com/kubernetes/website/pull/14140
>
>marun  [2 hours ago]
>LGTM

/lgtm
/approve

**Comment by jimangel** [comment]
Just merged the federation changes, thanks @thecrudge! Great work!
/close
