### ISSUE TITLE
Relocate reference generation tooling from Kubernetes Incubator

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#13904]
@mrbobbytables brought to my attention during the 1.14 cycle that the Kubernetes Incubator repo is sort of "[pre-retirement.](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#faq)"

Given that our reference-docs tooling lives there, we should consider moving it out to a SIG or Core repository described in the above link.

Also, since we rely heavily on those tools for the release process this might be a slightly larger undertaking to migrate. I don't see any need to make this an urgent priority, but wanted to open an issue for tracking.

TODO:
- [x]  PR fixes for: https://github.com/kubernetes/website/search?q=kubernetes-incubator%2Freference-docs&type=Code
- [x] PR fixes for:  https://github.com/kubernetes/community/tree/master/sig-docs#reference-docs
- [x] We'll need to merge or hold: https://github.com/kubernetes-incubator/reference-docs/pull/82
- [ ] Update reg-gen codebase to reflect repo move. (https://github.com/kubernetes-sigs/reference-docs/search?q=kubernetes-incubator%2Freference-docs&unscoped_q=kubernetes-incubator%2Freference-docs)

/cc @tengqm @zacharysarah @MAKOSCAFEE

**Comment by mrbobbytables** [comment]
/remove-lifecycle rotten
ref: https://github.com/kubernetes/community/issues/1922#issuecomment-516974448
