### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/ip-masq-agent/

### ISSUE THREAD

**Issue by sekannia** [kubernetes/website#13917]
**This is a Bug Report**

The IP address in the example diagram needs to represent correct ip4 address.  The PodA,PodB are given 10.1.1.1.2. 

**Problem:**
The IP address in the example diagram needs to represent correct ip4 address.  The PodA,PodB are given 10.1.1.1.2. Four dots in address space.
**Proposed Solution:**
Change to correct ip address format
**Page to Update:**
k8s.io/docs/tasks/administer-cluster/ip-masq-agent/ diagram

**Comment by Vageesha17** [comment]
hey  @sekannia , the page you provided to update is showing 404 error.Kindly provide the correct url so that this issue can be resolved.

**Comment by sekannia** [comment]
@Vageesha17 here is the url: https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/

**Comment by DanyC97** [comment]
thank you @sekannia for opening this issue.
/language en
/good-first-issue

**Comment by judavi** [comment]
Looks like this already been fixed on the latest version of the diagram 
![Captura de pantalla 2019-05-22 a la(s) 10 39 12 a  m](https://user-images.githubusercontent.com/1766933/58159997-de122c80-7c7d-11e9-83f4-b705b80152aa.png)

**Comment by palnabarun** [comment]
@judavi The IP addresses are still wrong in the diagram.

@sftim Any idea how the diagram was generated? Or, is there any guideline for the diagrams so that I can recreate one myself. I want to work on this.

**Comment by sftim** [comment]
Not sure how the diagram was generated, sorry.

A tip: if you use https://www.draw.io/ to generate a diagram, you can export it as a PNG with the editable diagram embedded. That's kind of neat.

_extra credit: have the Hugo site generation optimize the PNG before publishing, to save bandwidth_

**Comment by palnabarun** [comment]
Thank you @sftim for the insights.

I had draw.io in my mind to create the diagram.

I will give it a shot to optimize the PNG.

**Comment by sftim** [comment]
To me, PNG optimization is very much a nice-to-have. If an up to date diagram with the source embedded isn't much bigger than the optimized version, I think it's fine to have the full-fat version in source control and leave optimization for a separate PR.

**Comment by palnabarun** [comment]
@sftim 

I have filed a PR (#14789) which fixes the issue with Pod IP address in the diagram.

I tried compressing the image using two methods - [PNGout](https://aur.archlinux.org/packages/pngout/) and [zopfliPNG](https://github.com/google/zopfli).

While `zopfliPNG` fails to compress the Image with the embedded diagram, it compresses the image without the diagram by `41%`.

`PNGout` was able to compress the image with the embedded diagram but after compression `draw.io` wasn't able to load the diagram. It could compress the image without embedded diagram by only `26%.`

These were the two tools that I analyzed but there could be many which do the job. We can take this discussion to a separate issue which involves compressing images in a broader context. I have an idea related to compression and deployment of those images.

Please let me know what you think about this.

**Comment by sftim** [comment]
When I suggested PNG optimization, I think I made things look too complex. PNG is already compressed anyway. It's fine to have the pull request as it stands without adding PNG optimization to the Hugo build.
