### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/

### ISSUE THREAD

**Issue by dannyman** [kubernetes/website#1391]
**This is a...** 

- [X] Feature Request

**Problem:**

Most of this doc is missing. It is worse than useless.

For example, the steps are
1.  `git clone`
2.  set some environment variables
3.  `sudo service kube-controller-manager start`

Somewhere between steps 1 and 3 should be a part where the software gets installed.

**Proposed Solution:**

This doc is a blind alley that delays efforts at deploying/understanding kubernetes. Please remove this doc.

Actually useful is http://kubernetes.io/docs/getting-started-guides/kubeadm/

I would really appreciate a bare-metal install for an HA cluster on ubuntu. The first step there would probably be the package installations detailed in the kubeadm doc.

**Page to Remove:**

http://kubernetes.io/docs/getting-started-guides/ubuntu/

**Comment by errordeveloper** [comment]
@dannyman thanks for reporting this! I've opened https://github.com/kubernetes/kubernetes.github.io/issues/1659 to cover all of the outdated pages we have. Help would be really welcome, by the way!

**Comment by steveperry-53** [comment]
Closed https://github.com/kubernetes/kubernetes.github.io/issues/703 in an effort to consolidate.
703 want k8s to work on Ubuntu 16.04.

**Comment by zacharysarah** [comment]
@steveperry-53 Can we close this issue?

**Comment by errordeveloper** [comment]
/close

Let's close, this is very old.
