### ISSUE TITLE
Translate docs/contribute/localization to Hindi

### ISSUE THREAD

**Issue by Amanchouhan192** [kubernetes/website#13913]
**what would you like to be added**
I am translating **Localizing Kubernetes Documentation** in Hindi, for Hindi contributors and it will help them to understand how can they start.

**Comment by mittalyashu** [comment]
About which directory or file this issue is for? @Amanchouhan192

**Comment by Amanchouhan192** [comment]
this one https://kubernetes.io/docs/contribute/localization/ @mittalyashu

**Comment by mittalyashu** [comment]
Okay.

Can you change the title, just to make it more understandable, like: "Translate docs/contribute/localization to Hindi"

**Comment by Amanchouhan192** [comment]
@mittalyashu  done!!

**Comment by mittalyashu** [comment]
@Amanchouhan192 Any updates on this issue? Have you created a PR for the same?
