### ISSUE TITLE
Localising Stateless applications sub-section to Hindi

### ISSUE THREAD

**Issue by avidLearnerInProgress** [kubernetes/website#13926]
**What would you like to be added**

Markdown to be translated:-
- https://github.com/kubernetes/website/edit/master/content/en/docs/tutorials/stateless-application/expose-external-ip-address.md
- https://github.com/kubernetes/website/edit/master/content/en/docs/tutorials/stateless-application/guestbook.md

**Comment by mittalyashu** [comment]
@avidLearnerInProgress Have you created any PR for this?
