### ISSUE TITLE
Localization of Concepts section to Hindi

### ISSUE THREAD

**Issue by jidroid404** [kubernetes/website#13922]
Original documentation page hosted : https://kubernetes.io/docs/concepts/

Markdown file to be translated : https://github.com/kubernetes/website/edit/master/content/en/docs/concepts/_index.md

**Comment by mittalyashu** [comment]
@avidLearnerInProgress Should we close this issue, since it is targeting big chunk of a folder, we need to break down the process of creating issues, especially for big size folders.

Also, we already have a lot of issues and PR to review.

**Comment by sftim** [comment]
(I recommend closing the issue)
