### ISSUE TITLE
Translate Kubernetes contribution guide to Hindi

### ISSUE THREAD

**Issue by avidLearnerInProgress** [kubernetes/website#13923]
**What would you like to be added**
Hindi translation for the Kubernetes contribution guide: 
https://github.com/kubernetes/community/tree/master/contributors/guide

**Why is this needed**
 This will help the Hindi contributors understand the contribution guide

**Comment by avidLearnerInProgress** [comment]
This has been done already.!

**Comment by mittalyashu** [comment]
In which PR this is done?
