### ISSUE TITLE
Tracking Portuguese Translation Progress (M1) 

### ISSUE THREAD

**Issue by femrtnz** [kubernetes/website#13939]
## Maintainers
* @femrtnz  
* @jcjesus  
* @devlware 
* @jhonmike 

## For New Contributors
To translate a page:
1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. Take only one page at a time.
3. Fork this repo, make your localisations, and submit a pull request following the name convention `[Add/Update/Fix] [content/pt/file/full/path]`, for example: 

- `Add content/pt/docs/concepts/architecture/nodes.md`
- `Update content/pt/setup/release/building-from-source.md`

For more detailed instruction, consult with this [website README](https://git.kubernetes.io/website/README-pt.md) and the [contributors cheatsheet](https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-pt.md). Before contributing to docs, read the [Community Documentation Style Guide](https://git.kubernetes.io/community/contributors/guide/style-guide.md) and the [Kubernetes Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/). (If you're still not sure about something, please don't hesitate to ask in [Slack channel](https://kubernetes.slack.com/messages/CJ21AS0NA), we won't bite 😄)

Please commit to your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For maintainers
We are starting a spreadsheet to keep track of the pages we would like to deliver on this M1, please check it out in Portuguese [here](https://docs.google.com/spreadsheets/d/1HiaVFJ7nRZo1MPNNYyq1u-L_N9xrJvzuUzkZ3GuJGNU/edit)

This is our first milestone (M1) that we aim to complete during the lifespan of Kubernetes v1.20.

Since the 1.15 release cycle is short, we will do a cut, move leftovers to the next milestone, and perform a technical review when needed.

# Priorities 
We are trying to follow the priority order from the list of the most viewed pages and you can find more details on the spreadsheet above.

**Comment by pragmaticivan** [comment]
Pode me adicionar em `Architecture (content/id/docs/concepts/architecture)` - Nodes?

**Comment by femrtnz** [comment]
@pragmaticivan Sure

**Comment by devlware** [comment]
Hi @femrtnz! I'd like to work on __Cluster Administration Overview__ (content/id/docs/concepts/cluster-administration). Can you assign me?

**Comment by femrtnz** [comment]
Hey @devlware,  sure! thank for help! Feel free to open a PR with (WIP) so I can put it here =)

**Comment by RafaelMassoniSS** [comment]
Hi @femrtnz ! I'd like to translate **Overview** ("content/id/docs/concepts/overview/working-with-objects/names.md"). Can you assign me?

**Comment by rafaelrubbioli** [comment]
Hi! I would like to translate the `Contribute landing` to portuguese

**Comment by jcjesus** [comment]
Hi Rafael, please, can you do the steps in the **For New Contributors** topic?
Thanks

**Comment by jhonmike** [comment]
Hi I would like to get to translate the "**Kubelet Garbage Collection**" page, I like to contribute in translations to improve my learning with the tool, an example of this, I helped to translate the React documentation into Portuguese: 
- Site and Doc: https://github.com/reactjs/pt-BR.reactjs.org/issues/1
- Blog: https://github.com/reactjs/pt-BR.reactjs.org/issues/151

**Comment by jhonmike** [comment]
About the pages that were missing or outdated in the first comment:

### Concepts

#### Architecture:

- Controllers

#### Cluster Administration:

- Controller Metrics **changed the name to Monitoring**

#### Configuration

- Pod Overhead
- Resource Bin Packing
- Scheduling Framework
- Scheduler Perf Tuning **Moved to folder Scheduling**

#### Extend Kubernetes

- Operator

#### Overview

- Declarative Config **Do not exist anymore**
- Imperative Command **Do not exist anymore**
- Imperative Config **Do not exist anymore**
- Kustomization **Do not exist anymore**
- Overview **Do not exist anymore**
- Object management

#### Policy

- Limit Range

#### Scheduling **New Directory**

- Kube Scheduler
- Scheduler Perf Tuning

#### Security **New Directory**

- Overview

#### Service Networking

- Dual Stack
- Endpoint Slices
- Service Topology

#### Storage

- Volume PVC Datasource

#### Workloads

- Ephemeral Containers
- Pod Topology Spread Constraints

**Comment by jhonmike** [comment]
Pending review on PR #19434 I will start translating the page _Cluster Administration > **Logging**_

**Comment by femrtnz** [comment]
> About the pages that were missing or outdated in the first comment:
> 
> ### Concepts
> #### Architecture:
> * Controllers
> 
> #### Cluster Administration:
> * Controller Metrics **changed the name to Monitoring**
> 
> #### Configuration
> * Pod Overhead
> * Resource Bin Packing
> * Scheduling Framework
> * Scheduler Perf Tuning **Moved to folder Scheduling**
> 
> #### Extend Kubernetes
> * Operator
> 
> #### Overview
> * Declarative Config **Do not exist anymore**
> * Imperative Command **Do not exist anymore**
> * Imperative Config **Do not exist anymore**
> * Kustomization **Do not exist anymore**
> * Overview **Do not exist anymore**
> * Object management
> 
> #### Policy
> * Limit Range
> 
> #### Scheduling **New Directory**
> * Kube Scheduler
> * Scheduler Perf Tuning
> 
> #### Security **New Directory**
> * Overview
> 
> #### Service Networking
> * Dual Stack
> * Endpoint Slices
> * Service Topology
> 
> #### Storage
> * Volume PVC Datasource
> 
> #### Workloads
> * Ephemeral Containers
> * Pod Topology Spread Constraints

Thanks a lot! I just updated the issue.

**Comment by remyleone** [comment]
In case you are interested, here is the list of the 100 most visited pages on the whole Kubernetes website: https://github.com/kubernetes/website/issues/17598 
Putting the localization effort priority on the pages that are ranked high on this list will probably output high visitor rates in your localization. :)

**Comment by femrtnz** [comment]
> In case you are interested, here is the list of the 100 most visited pages on the whole Kubernetes website: #17598
> Putting the localization effort priority on the pages that are ranked high on this list will probably output high visitor rates in your localization. :) Feel free to adapt this list if you think it is useful for the Portuguese language.

 @remyleone Really nice! I will update the issue following this lit :)

**Comment by jhonmike** [comment]
PR with the translation of the page _Cluster Administration > **Logging_** >> #19573

**Comment by pasimoes** [comment]
Hi @femrtnz I'd like to trasnslate 
/docs/concepts/overview/what-is-kubernetes/
Can you assign to me?

**Comment by viniciusbds** [comment]
Hi @femrtnz ! I'd like to translate **Kubernetes Scheduler** topic
at "docs/concepts/scheduling/kube-scheduler.md".
Can you assign to me?

**Comment by jhonmike** [comment]
I was reading about Cron Jobs and I took and translated this little page >> #20117

**Comment by viniciusbds** [comment]
Hi @femrtnz @jcjesus @devlware @jhonmike!
 I'd like to translate  `Scheduler Perf Tuning` topic
at "docs/concepts/scheduling-eviction/scheduler-perf-tuning.md".
Can someone assign it to me ?

**Comment by jailton** [comment]
Hi Folks!

I've been working on the translation of Concept/Overview topic.

Overview (content/id/docs/concepts/overview):
- [ ] Components
- [ ] Kubernetes API
- [ ] What is Kubernetes 

Can someone assign it to me?

**Comment by ehvs** [comment]
Hi @femrtnz @jcjesus @devlware @jhonmike!
I'd like to translate **Install kubectl*
at "docs/tasks/tools/install-kubectl.md".
Can someone assign it to me ?

**Comment by rikatz** [comment]
@femrtnz sorry for not checking this first :D

So per the original issue + what we've been discussing on telegram, I'm wondering about if we manage the translation through google sheets instead of issue description, in this case (and as we can see on some other bigger efforts) wouldn't be better.

I've asked folks to map and split the effort in two:

* Pages that does not exists
* Pages that already exists but need some bigger review

Also, I guess keeping the docs always up to date is really (really!) hard, so maybe if we have some way of track the official english docs and trigger some alert so someone can verify if this needs attention, would be great.

Sounds good?

Thanks for the huge effort you've made so far!

**Comment by kbhawkey** [comment]
:wave:  I logged an issue with the theme after I noticed `pt` localization string warnings when building the documentation.
The theme includes `/website/themes/docsy/i18n/pt-br.toml` but the k8s website adds `/website/themes/docsy/i18n/pt.toml`.
Some of the localized strings (from the theme) are not resolved in the documentation.
I am wondering if the site should use `pt-br` instead of `pt`?
Here is a sample of the build warnings:
```
WARN 2021/02/19 17:06:51 Failed to get translated string for language "pt" and ID "post_last_mod": %!s(<nil>)
WARN 2021/02/19 17:06:51 Failed to get translated string for language "pt" and ID "post_edit_this": %!s(<nil>)
WARN 2021/02/19 17:06:51 Failed to get translated string for language "pt" and ID "post_create_issue": %!s(<nil>)
```

**Comment by rikatz** [comment]
I'm OK with migrating to pt-br instead of pt, but if we do this, we're assuming this docs are not appliable to Portugal folks :)

There are some minor differences between them, maybe create a symlink for now?

I can take a look into this @kbhawkey  :)

**Comment by kbhawkey** [comment]
Hi. The theme is investigating the i18n library that handles the language data.
The site should be able to read and use the strings in `pt-br.toml` and `pt.toml`. The theme provides common strings in `pt-br`.
If needed, the team could create a `pt-br.toml` file in `website/i18n`?

**Comment by rikatz** [comment]
Yes we can! If this is OK for sig-docs, we can actually migrate everything from pt/ to pt-br (as everything there is in brazilian portuguese) and once there's a desire to other portuguese localizations, this can be done :)

**Comment by guizanelato** [comment]
Hi @femrtnz , My first time contributing :) I would like to translate docs/concepts/configuration/organize-cluster-access-kubeconfig.md, could anyone assign it to me? thanks in advance.

**Comment by sftim** [comment]
> If this is OK for sig-docs, we can actually migrate everything from pt/ to pt-br

If that's the intention, please open a GitHub issue to track the introduction of country-specific localizations. We might need to do some general work to make sure this works out OK.

(Another option might be to work on upstream Docsy to add in the missing upstream translations for `pt`, if there's an acceptable version that works for the generic language code).

**Comment by rikatz** [comment]
So, as we've spoke with @sftim, we will follow the current approach now, of dealing directly with 'pt' content and translation, and not specializing in a pt-br and pt-pt translation.

As someone wants to create a Portuguese from Portugal translation, we will check this localization issue again.

Let's move forward :)

**Comment by bryanasdev000** [comment]
Guys I am really interessed in Networking part (Services Networking).

For now I plan to translate: https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/services-networking/ingress.md .

**Comment by rikatz** [comment]
@guizanelato added you to the kubeconfig translation
@bryanasdev000 added you to ingress translation

https://docs.google.com/spreadsheets/d/1HiaVFJ7nRZo1MPNNYyq1u-L_N9xrJvzuUzkZ3GuJGNU/edit?usp=sharing

**Comment by rikatz** [comment]
OK, so so far about the spreadsheet, I've almost mapped everything from concepts and others that need to be reviewed OR translated.

I'm still missing the tasks and the tutorials (which IMO are really important as well).

I would like to make some zoom meeting with whoever from the localization team wants to, so we can maybe prioritize things :)

**Comment by rikatz** [comment]
/help
/good-first-issue

Good first issue for Brazilian Portuguese speakers :)

**Comment by bryanasdev000** [comment]
> OK, so so far about the spreadsheet, I've almost mapped everything from concepts and others that need to be reviewed OR translated.
> 
> I'm still missing the tasks and the tutorials (which IMO are really important as well).
> 
> I would like to make some zoom meeting with whoever from the localization team wants to, so we can maybe prioritize things :)
> 
> /help
> /good-first-issue
> 
> Good first issue for Brazilian Portuguese speakers :)

Nice work! I think that we have a few posts from blog that we should give some attention too, specially the docker one (https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/).

I will spread the word too, see if we can have more people working on that.

**Comment by rikatz** [comment]
Yeap, one thing I want to discuss in our kickoff meeting is the priorities, and we can include some important blog posts into that.

**Comment by pasimoes** [comment]
@rikatz when is planned the kickoff meeting?

**Comment by rikatz** [comment]
We're still voting -> https://doodle.com/poll/k2bpczscth8vduah?utm_source=poll&utm_medium=link

**Comment by rikatz** [comment]
Per doodle, happening today at 9:00 :) (sorry, I announced on slack and completely forgot github)

https://meet.jit.si/KubernetesDocPT-BR

**Comment by emanuelhaine** [comment]
Hello guys,

I'd like to start translating this topic about Persistent Storage: https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/storage/persistent-volumes.md

**Comment by bryanasdev000** [comment]
> Hello guys,
> 
> I'd like to start translating this topic about Persistent Storage: https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/storage/persistent-volumes.md

Hello @emanuelhaine!

I added you to our spreadsheet!

Any problem, just leave a message on Slack.

**Comment by rikatz** [comment]
@emanuelhaine once you finish, let us know so someone from the group can review this :)

**Comment by jralmaraz** [comment]
Hi,

I would like to start translating the Authentication topic:

https://github.com/kubernetes/website/blob/master/content/en/docs/reference/access-authn-authz/authentication.md

Cheers!

**Comment by bryanasdev000** [comment]
> Authentication

Added 

> Hi,
> 
> I would like to start translating the Authentication topic:
> 
> https://github.com/kubernetes/website/blob/master/content/en/docs/reference/access-authn-authz/authentication.md
> 
> Cheers!

Added to our spreadsheet!

**Comment by duboc** [comment]
Hey everyone! 

I’m hoping to be of service and help translate some topics. 

I’m keen to work on the Daemonset, Deployment and Garbage Collection rendition.

**Comment by edsoncelio** [comment]
Hi everyone,

I'll start to work on the containers concepts:
https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/containers/

**Comment by AlexDamiao86** [comment]
Hello, 
I'd like to translate this page: 
https://github.com/kubernetes/website/edit/master/content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html

**Comment by rikatz** [comment]
Go ahead :D

I'll add you to the translation sheet here!

**Comment by devlware** [comment]
Hi @sftim! Hope you are doing fine.
A few years ago you provided a link to a list of the most accessed website pages, it was
the top 100. IIRC it was from Google Analitycs, could you provide the most up to date top
list for us to prioriteze on the PT-BR translation?

**Comment by AlexDamiao86** [comment]
> Go ahead :D
> 
> I'll add you to the translation sheet here!

Waiting for review: 
https://github.com/kubernetes/website/pull/27076

**Comment by AlexDamiao86** [comment]
Let me take one more page! I would like to translate:
https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/

**Comment by AlexDamiao86** [comment]
> Let me take one more page! I would like to translate:
> https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/

Waiting for review: 
https://github.com/kubernetes/website/pull/27105

**Comment by gabrielcmarinho** [comment]
> In case you are interested, here is the list of the 100 most visited pages on the whole Kubernetes website: #17598
> Putting the localization effort priority on the pages that are ranked high on this list will probably output high visitor rates in your localization. :) Feel free to adapt this list if you think it is useful for the Portuguese language.

That's great! @femrtnz! @jhonmike, @devlware starting translating [pod lifecycle](https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/workloads/pods/pod-lifecycle.md) page. By the way, I just already updated the spreadsheet.

**Comment by stormqueen1990** [comment]
Hello there!
I would like to update the `CronJob` documentation page in Portuguese: https://kubernetes.io/pt-br/docs/concepts/workloads/controllers/cron-jobs/

**Comment by rikatz** [comment]
Thanks @stormqueen1990 and go for it. Just make sure you add your GH handler in the spreadsheet

**Comment by stormqueen1990** [comment]
Hello there!

I'd like to review and update the Addons page, under Cluster Administration concepts: https://kubernetes.io/pt-br/docs/concepts/cluster-administration/addons/

**Comment by rikatz** [comment]
@MarcosNBJ @stormqueen1990 go for it, just make sure you put your github handler on the control spreadsheet: https://docs.google.com/spreadsheets/d/1HiaVFJ7nRZo1MPNNYyq1u-L_N9xrJvzuUzkZ3GuJGNU/edit

If it's ready for review, ping us on Slack -> kubernetes.slack.com // #kubernetes-docs-pt

Thanks!

**Comment by MarcosNBJ** [comment]
Alright, control spreadsheet updated. Thank you!

**Comment by stormqueen1990** [comment]
Hello!

I would like to start translating the page for [`ConfigMaps`](https://kubernetes.io/docs/concepts/configuration/configmap/) (`/docs/concepts/configuration/configmap`) next.

Thanks in advance!

**Comment by rikatz** [comment]
Hey folks,

As a suggestion so you wont need to wait others, let's follow the process of check in spreadsheet if someone is translating that page, otherwise it's yours :D

**Comment by gabrielalbino** [comment]
I'm taking "Docs/Concepts" / Services & Networking / Ingress Controllers, it was unassigned on the spreadsheet.

**Comment by edsoncelio** [comment]
Great @gabrielalbino If you need any help, just ping us on slack (channel #kubernetes-docs-pt) :D

**Comment by morallito** [comment]
Hello, I would like to start translating the page [Proxies in Kubernetes](https://kubernetes.io/docs/concepts/cluster-administration/proxies/) located in `docs/concepts/cluster-administration/proxies.md`

I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by brbernardo** [comment]
Hi,  I would like to start translating the page Best Practices in Kubernetes located in docs/setup/best-practices

I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by stormqueen1990** [comment]
Hello there!

I will start translating `docs/concepts/configuration/manage-resources-containers`. Already assigned it to me in the spreadsheet.

**Comment by ThiagoGMF** [comment]
Hello, I would like to start translating the page [System metrics](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/) located in docs/concepts/cluster-administration/system-metrics.md

I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by brendavsantos** [comment]
Hi everyone! 
I'm taking the [System Metrics](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/) page in pairs with @ThiagoGMF (we arrenged). I also assigned the spreadsheet and marked it as in progress.

**Comment by edsoncelio** [comment]
Thanks, great @ThiagoGMF @brendavsantos! Any help or question, just ping us on slack (Portuguese channel `#kubernetes-docs-pt`)

**Comment by morallito** [comment]
Hello, I would like to start translating the page [Pod Priority and Preemption](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) located in docs/concepts/scheduling-eviction/pod-priority-preemption.md

I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by ThiagoGMF** [comment]
Hello, I would like to start translating the page [Manage Deployment](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/) located in docs/concepts/cluster-administration/manage-deployment.md

I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by devlware** [comment]
I'm going to work on [service-catalog](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/).

**Comment by brendavsantos** [comment]
Hello everyone! I will start working on the page that talks about [Limit Ranges](https://kubernetes.io/docs/concepts/policy/limit-range/), I've assigned myself in the spreadsheet and marked it as in progress!

**Comment by tamarabarbosa** [comment]
Hello, I will translate /docs/concepts/overview/working-with-objects/common-labels.md. I assigned me in the sheet.

**Comment by marcelomansur** [comment]
Hi! I will work on [dockershim-faq](https://kubernetes.io/blog/2022/02/17/dockershim-faq/). I've assigned me in the sheet.

**Comment by PinheiroLG** [comment]
Hello everyone !!! I will translate /docs/concepts/workloads.md
I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by brendavsantos** [comment]
Hi! I will start working on the page that talks about [Resource Quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/) continuing the translation of the policy session, I've assigned myself in the spreadsheet and marked it as in progress!

**Comment by rikatz** [comment]
Hi folks,

As soon as you finish translating or need some help or PR review please remember to let us know on Kubernetes Slack channel #kubernetes-docs-pt

I will plan myself to do a batch of reviews next monday, feel free to assign to me.

**Comment by Matheusafonsouza** [comment]
Hi! me and @matgomes21 are working at [Endpoint Slices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/) page, already assigned it and put in progress.

**Comment by ThiagoGMF** [comment]
Hello, I would like to start translating the page [Flow Control](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/).

I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by tamarabarbosa** [comment]
Hey everyone,  I would like to start translating the page [Kubernetes Object Management](https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/). I already joined the spreadsheet.

**Comment by matgomes21** [comment]
Hey! I would like to start translating the page [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) with @Matheusafonsouza. I already assigned us in the spreadsheet and set the status as In Progress.

**Comment by stormqueen1990** [comment]
I am going to start updating the Secrets page with the latest changes from the English version. Already assigned it to me in the spreadsheet.

**Comment by Sampaiolc** [comment]
Hey everyone, I would like to start translating the page [Turnkey Cloud Solutions](https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/). Already assigned it to me in the spreadsheet.

**Comment by EzzioMoreira** [comment]
Hello guys!
How are you?
I will start translating `/docs/tasks/access-application-cluster/ingress-minikube.md`. Already assigned it to me in the spreadsheet. :metal:

**Comment by Sampaiolc** [comment]
Hey everyone, I would like to start translating the page [Validate node setup](https://kubernetes.io/docs/setup/best-practices/node-conformance/). Already assigned it to me in the spreadsheet.

**Comment by MrErlison** [comment]
Hi. I am working on /docs/concepts/architecture/nodes.md

**Comment by wellsud** [comment]
Greetins! I'm going to translate [Volumes](https://kubernetes.io/docs/concepts/storage/volumes/]). Already assigned it to me in the spreadsheet.

**Comment by MrErlison** [comment]
Hi. I am working on /docs/reference/glossary/*

**Comment by joaoceragioli** [comment]
Hello I'm going to translate [ReplicaSet](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/), already assigned it to me on the spreadsheet.

**Comment by stormqueen1990** [comment]
I will update the [concepts/overview/working-with-objects/names](https://kubernetes.io/pt-br/docs/concepts/overview/working-with-objects/names/) page next. Assigned on the spreadsheet.

**Comment by jralmaraz** [comment]
I have picked up docs/reference/access-authn-authz/authorization.md and assigned on the spreadsheet too.

**Comment by DonatoHorn** [comment]
Hi. I am Donato, and  working on /docs/reference/tasks/configure-pod-container/*.

**Comment by DanielViniciusAlves** [comment]
Hi. I'm working in the [Access Cluster](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/) translation, and already assigned myself in the spreadsheet.

**Comment by DonatoHorn** [comment]
Hi, nice to meet you, are you @jailton, that is assigned on the spreadsheet?
It's assigned
https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/,
but I translated https://kubernetes.io/docs/tasks/configure-pod-container/*.
Are our tasks in conflict?
I'm so sorry.

Em dom., 17 de jul. de 2022 às 22:27, DanielViniciusAlves <
***@***.***> escreveu:

**Comment by fernandes-natanael** [comment]
Hi guys, I'm worked in the translation of `/docs/setup/production-environment/container-runtimes.md` with @lorranyoliveira.

Here is the [PR](https://github.com/kubernetes/website/pull/35178).

**Comment by sftim** [comment]
This is an umbrella issue
/remove-good-first-issue

It's OK to create good-first-issues that reference this issue as their overarching issue.

**Comment by juliafmorgado** [comment]
Hey everyone, I would like to start translating the page [Kops](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/production-environment/tools/kops.md). 

I've assigned myself to the spreadsheet and marked it as in progress.

**Comment by juliafmorgado** [comment]
Hey, I'll start translating the page [kubespray](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/production-environment/tools/kubespray.md).

**Comment by juliafmorgado** [comment]
Hey, I'll start translating the page [open-a-pr](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/new-content/open-a-pr.md).

**Comment by castroricardo1** [comment]
Hello, I would like to start translating the page [Node Resources Managers](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/policy/node-resource-managers.md).

I've assigned myself in the spreadsheet and marked it as in progress.

**Comment by EuricoAbreu** [comment]
Hi everyone, I would like to start translating the page [Scheduling, Preemption and Eviction](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/scheduling-eviction/_index.md).
I have assigned myself in the spreedsheet, and market it as "In progress"

**Comment by AnaCarolinaRodriguesLeite** [comment]
Hi everyone, I would like to start translating the [Container Runtime Interface page](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/architecture/cri.md).

I assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by b-freitas** [comment]
Hello, I would like to start translating the page [cgroup](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/architecture/cgroups.md). 

I have assigned myself in the spreadsheet and marked it as in progress.

**Comment by italofernandes13** [comment]
Hi everyone, I would like to start translating the [Kubernetes Issues and Security](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/issues-security/_index.md).

I have assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by daniso123** [comment]
Hi, I would like to start translating the cluster administration page.

I assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by DaviMatheus** [comment]
Hello everyone , I would like to start translating the [Architecturecontroller concept  doc](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/architecture/controller.md).

I assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by edsondearaujo** [comment]
Hi everyone, I would like to start translating the page [pod-security-policy](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/security/pod-security-policy.md).
I have assigned myself in the spreedsheet, and market it as "In progress"

**Comment by italofernandes13** [comment]
Hi, I would like to start translating the [Kubernetes Security and Disclosure Information](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/issues-security/security.md).

I have assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by PauloGoncalvesLima** [comment]
Hi everyone, I would like to start translating the page [Access Applications in a Cluster_index](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/_index.md).

I have assigned myself in the spreedsheet, and market it as "In progress"

**Comment by PauloGoncalvesLima** [comment]
Hi everyone, I would like to start translating the page [Configure DNS for a Cluster](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/configure-dns-cluster.md).

I have assigned myself in the spreedsheet, and market it as "In progress"

**Comment by PauloGoncalvesLima** [comment]
Hi everyone, I would like to start translating the page [Customizing DNS Service](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md).

I have assigned myself in the spreedsheet, and market it as "In progress"

**Comment by italofernandes13** [comment]
Hi, I would like to start translating the [Official CVE Feed](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/issues-security/official-cve-feed.md).

I have assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by italofernandes13** [comment]
Hi, I would like to start translating the [Node Reference Information](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/node/_index.md).

I have assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by AnaCarolinaRodriguesLeite** [comment]
Hi everyone, I would like to start translating the [Windows-resource-management](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/configuration/windows-resource-management.md).

I assigned myself on the spreadsheet and marketed it as "In progress"

**Comment by sftim** [comment]
Not currently triaged as accepted
/remove-help

**Comment by seokho-son** [comment]
Hi @femrtnz, @jcjesus, @devlware, @jhonmike,
As a sig-docs localization subproject lead, I would like to check if this issue remains useful and if there's a general willingness to keep it open as is. (sig-docs is endeavoring to manage the quantity of open issues.)

**Comment by edsoncelio** [comment]
> Hi @femrtnz, @jcjesus, @devlware, @jhonmike, As a sig-docs localization subproject lead, I would like to check if this issue remains useful and if there's a general willingness to keep it open as is. (sig-docs is endeavoring to manage the quantity of open issues.)

Adding @stormqueen1990 to this discussion because she has been more active in the project in recent months :)

**Comment by stormqueen1990** [comment]
> > Hi @femrtnz, @jcjesus, @devlware, @jhonmike, As a sig-docs localization subproject lead, I would like to check if this issue remains useful and if there's a general willingness to keep it open as is. (sig-docs is endeavoring to manage the quantity of open issues.)
> 
> Adding @stormqueen1990 to this discussion because she has been more active in the project in recent months :)

Hi there, @seokho-son and @edsoncelio! 👋

Personally, I'd be OK with closing this issue. I see it was originally created to address the first pass of translation. At this point I think we could benefit from having a separate issue to track progress, perhaps in relation to a more recent Kubernetes release (this mentions v1.20 specifically).

**Comment by natalisucks** [comment]
@stormqueen1990 Thanks for responding! I want to echo @seokho-son's call-out and support the closing of this issue with perhaps opening new issues per Kubernetes release, as you mentioned. Thank you ❤️

**Comment by edsoncelio** [comment]
Just giving my +1 to close this issue :)

**Comment by seokho-son** [comment]
Thanks @stormqueen1990 @edsoncelio @natalisucks !

Let me close this issue. :)

/close
