### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by shahamit2** [kubernetes/website#13964]
**This is a Bug Report**

**Incorrect output of kubectl get deploy is shown in documentation:**
Actual Output: -
kubectl get deploy
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
nginx-deploy   5/5     5            5           13m

Output in documentation: -
NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
nginx-deployment   3         3         3            3           18s

**Proposed Solution:**
Kindly update the document

**Page to Update:**
https://kubernetes.io/...

kubectl version --short
Client Version: v1.14.0
Server Version: v1.14.0

**Comment by Vageesha17** [comment]
I would like to solve this issue as it would be a good start but @shahamit2 can you please provide the exact URL of the page where the changed are required.

**Comment by nelvadas** [comment]
hi @Vageesha17  the page to edit is 
content/en/docs/concepts/workloads/controllers/deployment.md
Thanks for your contribution

**Comment by judavi** [comment]
Hi, @shahamit2 I was thinking about starting working on this but I reviewed the document and the [YAML file](https://github.com/kubernetes/website/blob/master/content/zh/docs/concepts/workloads/controllers/nginx-deployment.yaml) being used for the example is configuring 3 replicas which seem is the actual output exposed in the documentation. Please, kindly advice.
