### ISSUE TITLE
Improvement for k8s.io/docs/setup/independent/control-plane-flags/

### ISSUE THREAD

**Issue by flucrezia** [kubernetes/website#13973]
How and when to use the ClusterConfiguration object when setting up a k8s cluster with kubeadm init ?

**Comment by neolit123** [comment]
the documentation in question is about the control plane components specifically.
the kubeadm init page:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file

already links to this page:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1
where you can find details on how to use ClusterConfiguration from a file.

/close
