### ISSUE TITLE
Translate /concepts/workloads/controllers/replicaset/ in korean

### ISSUE THREAD

**Issue by nowjean** [kubernetes/website#13974]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**

**Comments**

**Comment by gochist** [comment]
refs  #16070

**Comment by seokho-son** [comment]
@nowjean 혹시 작업 중에 계신지요?
#16070 에서 관련 번역 문서가 머지되었습니다. 혹시 작업 중이신 내용이 있으면 머지된 문서를 기반으로 업데이트 부탁드립니다. 해당 이슈는 우선 close 하도록 하겠습니다 ~~
/close
