### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod-overview/

### ISSUE THREAD

**Issue by Chloe-H** [kubernetes/website#13980]
Last paragraph in ["Pod Templates"](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates), under the sample pod template: "This is in deliberate contrast to pods" seems like a typo, since the previous sentence was discussing pods, and it doesn't make sense to me to talk about how pods differ from themselves.

**Comment by palnabarun** [comment]
> Similarly, pods created by a replication controller may subsequently be updated directly. This is in deliberate contrast to pods, which do specify the current desired state of all containers belonging to the pod.

I think the comparison is being drawn between "Pods created by Replication Controllers" and "Pods created by Pod Templates". But, I do believe that the explanation is slightly confusing and can be improved upon.
