### ISSUE TITLE
Issue with /docs/admin/kubelet/

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/website#1398]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Latest kubelet documentation is missing the api-servers parameters

**Proposed Solution:**
Readd the documentation for the api-servers param

**Page to Update:**
http://kubernetes.io/...

**Comment by liggitt** [comment]
--api-servers is deprecated, --kubeconfig should be used instead

**Comment by tengqm** [comment]
The deprecated flag is now removed. There is no need to fix it.
