### ISSUE TITLE
[Epic] Contributor cheatsheet localization

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13989]
Per today's SIG-Docs meeting, we want to localize the contributor cheatsheet.

The actual content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

The translated content would be put into `community` repo as well.

**Comment by daminisatya** [comment]
+1

**Comment by chenrui333** [comment]
Per-language task issues were created:
- Chinese: #13990 
- Korean: #13991
- Japanese: #13992
- German: #13993
- Spanish: #13994
- French: #13995
- Indonesian: #13996
- Portuguese: #13997 
- Italian: #13998

/cc @zacharysarah

**Comment by mrbobbytables** [comment]
Wonderful, thank you so much! \o/

**Comment by idvoretskyi** [comment]
+1

**Comment by bigfootlviv** [comment]
+1

**Comment by remyleone** [comment]
How is localization managed inside the community repository? It is not a hugo website so I am not sure about how the different languages are managed there.

**Comment by mrbobbytables** [comment]
For this specifically it would probably be best to mimic the format used in the root of the website repo. Within the contributor-cheatsheet directory add a `README-<ISO 639-1 lang code>.md`. We can then update the welcome message bot to include links to the translated copies 😄

**Comment by zacharysarah** [comment]
@chenrui333 👋 Thanks for opening this. 

For English, I'd like this issue to include adding a section to [this page](https://kubernetes.io/docs/contribute/#ways-to-contribute), below Ways to Contribute:

```md
## Feature development

You can also contribute to Kubernetes feature development. The [contributor cheatsheet](https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet) can help you get started.
```

Other localizations can include that section with a link to their localization-specific cheatsheet.

**Comment by chenrui333** [comment]
@zacharysarah 
I see your point, I will file a PR now.

**Comment by remyleone** [comment]
Taking the lead for the French translation https://github.com/kubernetes/community/pull/3658

**Comment by ClaudiaJKang** [comment]
Translation of the localize contributor cheatsheet in Korean is done. (ref : kubernetes/community#3660)

**Comment by bigfootlviv** [comment]
I'm working on Ukrainian uk localization.

**Comment by mrbobbytables** [comment]
/reopen

accidentally closed by https://github.com/kubernetes/community/pull/3660

**Comment by chenrui333** [comment]
checkin 
/remove-lifecycle stale

**Comment by inductor** [comment]
Current state as of 15th Aug 2019(Feel free to edit when it has to be changed)
- [x] Chinese: #13990
- [x] Korean: #13991
- [x] Japanese: #13992
- [ ] German: #13993
- [ ] Spanish: #13994
- [x] French: #13995
- [x] Indonesian: #13996
- [x] Portuguese: #13997
- [ ] Italian: #13998
- [ ] Hindi: #14001

**Comment by anastyakulyk** [comment]
> I'm working on Ukrainian uk localization.
@bigfootlviv any progress so far? Would be glad to join forces)

**Comment by tengqm** [comment]
All ten tasks are completed and merged.
Closing this epic.
Feel free to file a new issue/epic if there are other localization efforts to be covered.
/close
