### ISSUE TITLE
Localize contributor cheatsheet in Indonesian

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13996]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Translation result will needs to be put into the `community` repo as well.

/kind feature
/language id
/cc @kubernetes/sig-docs-id-owners

**Comment by irvifa** [comment]
@chenrui333 Is this also implemented in other localization as well?

**Comment by chenrui333** [comment]
Yeah, currently it seems only korean got translated:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

**Comment by irvifa** [comment]
@chenrui333 got some error regarding service account hmm
