### ISSUE TITLE
Localize contributor cheatsheet in French

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13995]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Translation result will needs to be put into the `community` repo as well.

/kind feature
/language fr
/cc @kubernetes/sig-docs-fr-owners

**Comment by remyleone** [comment]
How should it work? Where should we put the content. It doesn't seem like the community repository is a hugo website so I'm not sure about where to put the files.

**Comment by chenrui333** [comment]
@remyleone any update on this issue?

**Comment by remyleone** [comment]
I think it got merged for the French part, https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README-fr.md we can close this issue.
