### ISSUE TITLE
Localize contributor cheatsheet in Spanish

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13994]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Translation result will needs to be put into the `community` repo as well.

/kind feature
/language es
/cc @kubernetes/sig-docs-es-owners

**Comment by chenrui333** [comment]
checkin
/remove-lifecycle stale

**Comment by chenrui333** [comment]
@raelga any update on this issue?

**Comment by jesuslerma** [comment]
Hi! Can I take this one?
