### ISSUE TITLE
Localize contributor cheatsheet in Korean

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13991]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Translation result will needs to be put into the `community` repo as well.

/kind feature
/language ko

**Comment by mrbobbytables** [comment]
@ClaudiaJKang I think this can be closed now that https://github.com/kubernetes/community/pull/3660 has been merged 🎉 

Thank you again for working on it :)
