### ISSUE TITLE
Localize contributor cheatsheet in Chinese

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13990]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

**Comment by zhangqx2010** [comment]
I will do the zh trans for this.

**Comment by chenrui333** [comment]
The file would be in the `community` repo.

**Comment by zhangqx2010** [comment]
Or we just create a simple page links to the community page? Thus we don't need to update the both page later.

**Comment by idealhack** [comment]
Given this issue has been inactive for more than a month, I will work on this.

/assign
