### ISSUE TITLE
Localize contributor cheatsheet in Portuguese

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13997]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Translation result will needs to be put into the `community` repo as well.

/kind feature
/language pt
/cc @kubernetes/sig-docs-pt-owners

**Comment by femrtnz** [comment]
Hi @chenrui333 
Does the translation needs to be in the same folder?
e.g:  https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet/README-pt.md

Thanks

**Comment by chenrui333** [comment]
@femrtnz 
Sorry to reply late. 

Yeah, it should be in the same folder as the other docs.
https://github.com/kubernetes/website/issues/13989#issuecomment-486762515

**Comment by femrtnz** [comment]
Hi @chenrui333 do we need to add this cheatsheet on the website repo as well? If yes, could you tell me which folder?

thanks

**Comment by chenrui333** [comment]
No, we dont need to put into website repo, only cheatsheet repo is enough.

**Comment by femrtnz** [comment]
great! 

/assign @chenrui333

**Comment by chenrui333** [comment]
Thanks @femrtnz for the hard work!! 💯 

/close
