### ISSUE TITLE
Localize contributor cheatsheet in Japanese

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#13992]
Contributor cheatsheet content in the below link:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

Translation result will needs to be put into the `community` repo as well.

/kind feature
/language ja
/cc @kubernetes/sig-docs-ja-owners

**Comment by cstoku** [comment]
#3877

**Comment by chenrui333** [comment]
Once the PR got merged, I will close this issue. :)
