### ISSUE TITLE
Localize contributor cheatsheet in Hindi

### ISSUE THREAD

**Issue by avidLearnerInProgress** [kubernetes/website#14001]
**What would you like to be added**
Contributor cheatsheet content:
https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet

**Comments**
Working on PR #14001

**Comment by chenrui333** [comment]
`@kubernetes/sig-docs-it-owners` it is the Italian team, somehow I did not see the Hindi team.

**Comment by avidLearnerInProgress** [comment]
We will form one soon!

**Comment by mittalyashu** [comment]
Hey @avidLearnerInProgress,

What's the process of adding cheatsheet? I can also tag along.

**Comment by avidLearnerInProgress** [comment]
> 
> 
> Hey @avidLearnerInProgress,
> 
> What's the process of adding cheatsheet? I can also tag along.


Sure why not. Lets collaborate!

**Comment by avidLearnerInProgress** [comment]
Sure, why not. I have already started localising the cheatsheet. But you can surely hop in.!

**Comment by mittalyashu** [comment]
> Sure, why not. I have already started localizing the cheatsheet. But you can surely hop in.! 

Have you created any PR for the same?

> Can you look into creating the Hindi team? Didn't find quality time to look into that aspect.

Will start work on that.

**Comment by chenrui333** [comment]
checkin?
/remove-lifecycle stale

**Comment by mittalyashu** [comment]
@avidLearnerInProgress Have you opened the PR for contributor cheatsheet?

**Comment by mittalyashu** [comment]
@avidLearnerInProgress Shouldn't this issue be the part of **Kubernetes/community** repository?
