### ISSUE TITLE
Approval permission to l10n teams for specific files at root level/outside content path

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#14008]
**This is a Feature Request**
**What would you like to be added**
Add approval permission to localization teams for specific files at root level, outside content path:
- i18n/\<LANG>.toml
- README-\<LANG>.md

**Why is this needed**
Those files (for example, `README-ko.md` and `i18n/ko.toml`) are hard to get reviewed or approved by `sig-docs-en-owners`.

Related PRs: #12875 #12878 #13951

**Comments**

/cc @zacharysarah

**Comment by zacharysarah** [comment]
@gochist Sorry I missed this issue—I opened #14048 too.

**Comment by gochist** [comment]
@zacharysarah No problem. `README-<LANG>.md` is remaining. I'm not sure that the prow supports file level filtering.
