### ISSUE TITLE
core-dns pod going in crashloopbackoff status ubuntu 18.04

### ISSUE THREAD

**Issue by tripathideepesh** [kubernetes/website#14010]
**This is a Bug Report**

core-dns pod is going in CrashloopBackOff status after kubeadm init

**Problem:**
core-dns pod is going in CrashloopBackOff status after kubeadm init

I have created k8s cluster using below command
sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.56.102 --service-cidr=10.244.240.0/20 

post that created flannet virtual pod network
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

when i list pod status of all pods in kube-system namespace. core-dns pods are showing crashloopbackoff.

test-vm@kubernetes-master:~$ sudo kubectl get pods --all-namespaces
NAMESPACE     NAME                                        READY   STATUS             RESTARTS   AGE
kube-system   coredns-fb8b8dccf-c4c9x                     0/1     CrashLoopBackOff   2          89s
kube-system   coredns-fb8b8dccf-rn28t                     0/1     CrashLoopBackOff   2          89s
kube-system   etcd-kubernetes-master                      1/1     Running            0          41s
kube-system   kube-apiserver-kubernetes-master            1/1     Running            0          36s
kube-system   kube-controller-manager-kubernetes-master   1/1     Running            0          31s
kube-system   kube-flannel-ds-amd64-vhvv7                 1/1     Running            0          43s
kube-system   kube-proxy-f6zh4                            1/1     Running            0          89s
kube-system   kube-scheduler-kubernetes-master            1/1     Running            0          33s

test-vm@kubernetes-master:~$ sudo kubectl logs coredns-fb8b8dccf-c4c9x -n=kube-system
.:53
2019-04-24T10:16:39.573Z [INFO] CoreDNS-1.3.1
2019-04-24T10:16:39.573Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2019-04-24T10:16:39.573Z [INFO] plugin/reload: Running configuration MD5 = 599b9eb76b8c147408aed6a0bbe0f669
[INFO] SIGTERM: Shutting down servers then terminating

**Proposed Solution:**
test-vm@kubernetes-master:~$ sudo kubectl get pods --all-namespaces
NAMESPACE     NAME                                        READY   STATUS             RESTARTS    AGE
kube-system   coredns-fb8b8dccf-c4c9x                     1/1     Running               0                   89s
kube-system   coredns-fb8b8dccf-rn28t                     1/1     Running               0          89s
kube-system   etcd-kubernetes-master                      1/1     Running            0          41s
kube-system   kube-apiserver-kubernetes-master            1/1     Running            0          36s
kube-system   kube-controller-manager-kubernetes-master   1/1     Running            0          31s
kube-system   kube-flannel-ds-amd64-vhvv7                 1/1     Running            0          43s
kube-system   kube-proxy-f6zh4                            1/1     Running            0          89s
kube-system   kube-scheduler-kubernetes-master            1/1     Running            0          33s

Also, what is the meaning of 0/1 and 1/1 for READY header can you please tell ?

**Page to Update:**
https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/#coredns-pods-have-crashloopbackoff-or-error-state

I have tried all troubleshooting steps given in above page but could not resolve issue with above information.

selinux is disabled
have made entries of nameserver in /etc/resolv.conf as 8.8.8.8 but did not help
--resolv-conf=/run/systemd/resolve/resolv.conf tried changing this file as well did not help.

est-vm@kubernetes-master:~$ ps auxww | grep kubelet 
test-vm   1292  0.0  0.0  21536  1036 pts/0    S+   15:44   0:00 grep --color=auto kubelet
root      7135  7.3  1.7 1374484 104860 ?      Ssl  15:39   0:24 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1 --resolv-conf=/run/systemd/resolve/resolv.conf --resolv-conf=/run/systemd/resolve/resolv.conf
root      7560  7.8  4.0 405788 250548 ?       Ssl  15:39   0:25 kube-apiserver --advertise-address=192.168.56.102 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-cafile=/etc/kubernetes/pki/etcd/ca.crt --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.244.240.0/20 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
test-vm@kubernetes-master:~$ cat /run/systemd/resolve/resolv.conf
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 192.168.43.150

test-vm@kubernetes-master:~$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

test-vm@kubernetes-master:~$ sudo docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:52:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Wed Feb 13 00:24:14 2019
  OS/Arch:          linux/amd64
  Experimental:     false

est-vm@kubernetes-master:~$ uname -a
Linux kubernetes-master 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 18.04

**Comment by neolit123** [comment]
> https://kubernetes.io/docs/setup/independent/troubleshooting-kubeadm/#coredns-pods-have-crashloopbackoff-or-error-state
> I have tried all troubleshooting steps given in above page but could not resolve issue with above information.

if you have tried this already i don't have other suggestions for now.
that usually fixes it for users.

/sig cluster-lifecycle

**Comment by chrisohaver** [comment]
This issue should probably not be in `kubernetes/website`... anyways...

What does your CoreDNS Corefile look like?

The CoreDNS log ...
```
2019-04-24T10:16:39.573Z [INFO] plugin/reload: Running configuration MD5 = 599b9eb76b8c147408aed6a0bbe0f669
[INFO] SIGTERM: Shutting down servers then terminating
```

... says that CoreDNS is getting shut down by something (kubernetes).  So next step is to find out why k8s is doing that.  This can happen when the Deployment fails health probes to CoreDNS.

Can you show us output of `kubectl describe pod coredns-fb8b8dccf-c4c9x` ?

> Also, what is the meaning of 0/1 and 1/1 for READY header can you please tell ?

0/1 means that zero containers are ready, of a total of 1 container (iow one container is unready).  1/1 means 1 container is ready, of a total of 1 container (iow zero containers are unready).

**Comment by tripathideepesh** [comment]
@chrisohaver

Below is the o/p of command sudo kubectl describe pods coredns-fb8b8dccf-82xzz -n=kube-system
============================================================
test-vm@kubernetes-master:~$ sudo kubectl describe pods coredns-fb8b8dccf-82xzz -n=kube-system
Name:               coredns-fb8b8dccf-82xzz
Namespace:          kube-system
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               kubernetes-master/192.168.56.102
Start Time:         Thu, 25 Apr 2019 11:27:10 +0530
Labels:             k8s-app=kube-dns
                    pod-template-hash=fb8b8dccf
Annotations:        <none>
Status:             Running
IP:                 
Controlled By:      ReplicaSet/coredns-fb8b8dccf
Containers:
  coredns:
    Container ID:  docker://510e3d0476e22b23bc2e23cf9bb87007f2675dd556a8585fc7df2ec220e4b3b4
    Image:         k8s.gcr.io/coredns:1.3.1
    Image ID:      docker-pullable://k8s.gcr.io/coredns@sha256:02382353821b12c21b062c59184e227e001079bb13ebd01f9d3270ba0fcbf1e4
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 25 Apr 2019 11:32:58 +0530
      Finished:     Thu, 25 Apr 2019 11:33:00 +0530
    Ready:          False
    Restart Count:  7
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8080/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-d6dqm (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-d6dqm:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-d6dqm
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                    From                        Message
  ----     ------            ----                   ----                        -------
  Warning  FailedScheduling  8m46s (x25 over 10m)   default-scheduler           0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Normal   Killing           7m10s (x3 over 7m19s)  kubelet, kubernetes-master  Stopping container coredns
  Normal   Pulled            6m57s (x4 over 7m22s)  kubelet, kubernetes-master  Container image "k8s.gcr.io/coredns:1.3.1" already present on machine
  Normal   Created           6m55s (x4 over 7m21s)  kubelet, kubernetes-master  Created container coredns
  Normal   Started           6m55s (x4 over 7m21s)  kubelet, kubernetes-master  Started container coredns
  Normal   SandboxChanged    6m53s (x7 over 7m19s)  kubelet, kubernetes-master  Pod sandbox changed, it will be killed and re-created.
  Warning  BackOff           2m20s (x62 over 7m7s)  kubelet, kubernetes-master  Back-off restarting failed container
============================================================

Small observation in the above output corefile is expected to be available at /etc/coredns/corefile ? if i am not wrong.

I could not see any such file in my machine ... i had created the cluster using kubeadm ...did i need to create corefile ? or how can i see content of corefile... issue is still not fixed for me :(

**Comment by tripathideepesh** [comment]
> @chrisohaver
> 
> # Below is the o/p of command sudo kubectl describe pods coredns-fb8b8dccf-82xzz -n=kube-system
> "test-vm@kubernetes-master:~$ sudo kubectl describe pods coredns-fb8b8dccf-82xzz -n=kube-system
> Name: coredns-fb8b8dccf-82xzz
> Namespace: kube-system
> Priority: 2000000000
> PriorityClassName: system-cluster-critical
> Node: kubernetes-master/192.168.56.102
> Start Time: Thu, 25 Apr 2019 11:27:10 +0530
> Labels: k8s-app=kube-dns
> pod-template-hash=fb8b8dccf
> Annotations: 
> Status: Running
> IP:
> Controlled By: ReplicaSet/coredns-fb8b8dccf
> Containers:
> coredns:
> Container ID: docker://510e3d0476e22b23bc2e23cf9bb87007f2675dd556a8585fc7df2ec220e4b3b4
> Image: k8s.gcr.io/coredns:1.3.1
> Image ID: docker-pullable://k8s.gcr.io/coredns@sha256:02382353821b12c21b062c59184e227e001079bb13ebd01f9d3270ba0fcbf1e4
> Ports: 53/UDP, 53/TCP, 9153/TCP
> Host Ports: 0/UDP, 0/TCP, 0/TCP
> Args:
> -conf
> /etc/coredns/Corefile
> State: Waiting
> Reason: CrashLoopBackOff
> Last State: Terminated
> Reason: Completed
> Exit Code: 0
> Started: Thu, 25 Apr 2019 11:32:58 +0530
> Finished: Thu, 25 Apr 2019 11:33:00 +0530
> Ready: False
> Restart Count: 7
> Limits:
> memory: 170Mi
> Requests:
> cpu: 100m
> memory: 70Mi
> Liveness: http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
> Readiness: http-get http://:8080/health delay=0s timeout=1s period=10s #success=1 #failure=3
> Environment: 
> Mounts:
> /etc/coredns from config-volume (ro)
> /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-d6dqm (ro)
> Conditions:
> Type Status
> Initialized True
> Ready False
> ContainersReady False
> PodScheduled True
> Volumes:
> config-volume:
> Type: ConfigMap (a volume populated by a ConfigMap)
> Name: coredns
> Optional: false
> coredns-token-d6dqm:
> Type: Secret (a volume populated by a Secret)
> SecretName: coredns-token-d6dqm
> Optional: false
> QoS Class: Burstable
> Node-Selectors: beta.kubernetes.io/os=linux
> Tolerations: CriticalAddonsOnly
> node-role.kubernetes.io/master:NoSchedule
> node.kubernetes.io/not-ready:NoExecute for 300s
> node.kubernetes.io/unreachable:NoExecute for 300s
> Events:
> Type Reason Age From Message
> 
> # Warning FailedScheduling 8m46s (x25 over 10m) default-scheduler 0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
> Normal Killing 7m10s (x3 over 7m19s) kubelet, kubernetes-master Stopping container coredns
> Normal Pulled 6m57s (x4 over 7m22s) kubelet, kubernetes-master Container image "k8s.gcr.io/coredns:1.3.1" already present on machine
> Normal Created 6m55s (x4 over 7m21s) kubelet, kubernetes-master Created container coredns
> Normal Started 6m55s (x4 over 7m21s) kubelet, kubernetes-master Started container coredns
> Normal SandboxChanged 6m53s (x7 over 7m19s) kubelet, kubernetes-master Pod sandbox changed, it will be killed and re-created.
> Warning BackOff 2m20s (x62 over 7m7s) kubelet, kubernetes-master Back-off restarting failed container"
> Small observation in the above output corefile is expected to be available at /etc/coredns/corefile ? if i am not wrong.
> 
> I could not see any such file in my machine ... i had created the cluster using kubeadm ...did i need to create corefile ? or how can i see content of corefile... issue is still not fixed for me :(

**Comment by tripathideepesh** [comment]
I also found that kubelet is not using /etc/resolv.conf but ubutu's systemd-resolved /run/systemd/resolve/resolv.conf file --due to this problem can happen ?

if yes how to start kubelet with /etc/resolv.conf?. I tried changing /var/lib/kubelet/kubeadm.env file with ---resolv.conf to /etc/resolv.conf but that too did not help..?

how can we start kubelet with --resolv-conf = /etc/resolv.conf settings, I could not get any procedure if anyone has done this before and it is doable please post the procedure.

**Comment by chrisohaver** [comment]
@tripathideepesh, your comments are very hard to read...  looks like you are just pasting raw output from a command line into github, and github is interpreting it as markdown markup, and the output of the command line is running together with your questions.  Please enclose log output and command lien output in 3 backticks (```) or 3 tildes (~~~) ...

**Comment by rajansandeep** [comment]
@tripathideepesh 

> Warning FailedScheduling 8m46s (x25 over 10m) default-scheduler 0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.

From your logs above, it seems like your node is tainted. Follow the steps [here](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#control-plane-node-isolation) and CoreDNS pods should be deployed.

If you have further questions, please open another issue in the kubernetes/kubeadm repo. (This is the wrong repo to open this issue)

/close
