### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by asif-malek** [kubernetes/website#14016]
**This is a Bug Report**

minikube dashboard command is not working propertly.
Output of execution of the command:
$ minikube dashboard
-   Enabling dashboard ...
-   Verifying dashboard health ...
-   Launching proxy ...
-   Verifying proxy health ...
-   Opening http://127.0.0.1:42279/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
X   failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Page to Update:**
https://kubernetes.io/...

**Comment by dbirks** [comment]
It looks like your Linux distribution doesn't have the `xdg-open` utility installed. 

It's not required to use minikube though. You can copy and paste the URL into your browser.

**Comment by tfogo** [comment]
dup of #12968
