### ISSUE TITLE
Issue with k8s.io/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by qoricode** [kubernetes/website#14012]
**This is a Bug Report**

**Problem:**

The method described to get the cluster node(s) IP addresses didn't work on my k8s setup which is minikube:

```
NODES=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="ExternalIP")].address }')
```

It worked when I modified it to: 
```
NODES=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="InternalIP")].address }')
```

**Proposed Solution:**

Advise to use "InternalIP" in jsonpath expression if using minikube

**Page to Update:**
https://kubernetes.io/...

**Comment by SupriyaSirbi** [comment]
Created pull request for the same. Thanks

**Comment by DanyC97** [comment]
/close 

thanks @SupriyaSirbi for your contribution
