### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by gjanders** [kubernetes/website#14031]
On this particular page the `kubectl apply -k .` does not work, should it be `kubectl apply -f .` ?

Even when using this the validation fails and nothing is created...

**Comment by gjanders** [comment]
I later found that minikube has kubernetes version 1.14 but kubectl 1.13 which is causing this confusion.
The current online playgrounds both appear to have this issue...

Therefore it is a little bit confusing but not technically an issue, the documentation

**Comment by prankul88** [comment]
@gjanders I am facing the same issue.
I am using kubernetes v1.14.0 and minikube v0.35

Do you know a workaround for this?

**Comment by gjanders** [comment]
The online versions are not yet running v1.14.0 or newer so you either need to install minikube locally or you have to work around the instructions...
