### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update/update-interactive/

### ISSUE THREAD

**Issue by domq** [kubernetes/website#14038]
On Module 6, Step 2 of the KataKoda exercise, `curl $(minikube ip):$NODE_PORT` does not work because the service is deployed on a different IP than `minikube ip`. Please replace with

```
curl $(kubectl get service -o json kubernetes-bootcamp | jq -r '.spec.clusterIP + ":"+ (.spec.ports[0].port|tostring)')
```

**Comment by palnabarun** [comment]
Can I take this up?

@zhangqx2010 Can you please point me to the source code of the katacoda scenarios?

**Comment by zhangqx2010** [comment]
/remove-good-first-issue
@palnabarun Thanks for you help.
Sorry for the wrong information. This is out of scope. My bad. I am trying to contact relative person to fix it.

**Comment by zhangqx2010** [comment]
@domq 
I retried on the lab but it seems work. Output like:
```
$ echo NODE_PORT=$NODE_PORT
NODE_PORT=30757
$ curl $(minikube ip):$NODE_PORT
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-5bf4d5689b-qkdwd | v=2
$
```
Could you please provide more detail how to reproduce the issue?

**Comment by BenHall** [comment]
As @zhangqx2010 pointed out, recent changes to Minikube meant this has been resolved.

We believe this issue can be closed.
