### ISSUE TITLE
which mode of cgroup is we recommend? cgroupfs or systemd?

### ISSUE THREAD

**Issue by zgfh** [kubernetes/website#14053]
**This is a Bug Report**

The following two documents make me confused.
 https://kubernetes.io/docs/setup/cri/

![image](https://user-images.githubusercontent.com/11729624/56789923-b45c1600-6835-11e9-8b5b-cc81c6ffd339.png)

https://kubernetes.io/docs/setup/independent/install-kubeadm/
![image](https://user-images.githubusercontent.com/11729624/56790002-ea999580-6835-11e9-8397-c80fa8b3e869.png)

which mode is we recommend?

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
please use `systemd` as recommended in the CRI installation steps.
thanks

/close
