### ISSUE TITLE
Show iptables -L output

### ISSUE THREAD

**Issue by JonathanWilbur** [kubernetes/website#14057]
**This is a Feature Request**

**What would you like to be added**

Add the output of the `iptables -L` command as run on nodes throughout parts of the documentation that explain networking.

**Why is this needed**

It was very difficult to understand how services work from the documentation alone; I had to look at `iptables -L` myself to get it.

**Comment by DanyC97** [comment]
you have any pages in mind which should add this info @JonathanWilbur ?

**Comment by JonathanWilbur** [comment]
[This page](https://kubernetes.io/docs/concepts/services-networking/service/) is the critical one, or, more specifically, [this section](https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies). 

Examples would be less important, but still useful [here](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types).

I don't see where this could be gracefully inserted, but it could also be useful [here](https://kubernetes.io/docs/concepts/cluster-administration/networking/).

**Comment by sftim** [comment]
I'd be wary of putting in Linux-specific assumptions into concept level documentation. Nodes typically run Linux and have `iptables` available, but that's not guaranteed generally.

How about: a task page about troubleshooting network issues, that the Service concept page links to? That page could have tabs for common OSs that Nodes run.

**Comment by JonathanWilbur** [comment]
> Nodes typically run Linux and have iptables available, but that's not guaranteed generally.

Okay, fair point. Still, why not just say "if this were running on a Linux node with iptables, the entries would look like this..." and so on for whatever other firewall / IP tools kube-proxy works with. I still stand by putting something that visibly demonstrates what happens behind the scenes.

**Comment by sftim** [comment]
> if this were running on a Linux node with iptables, the entries would look like this…

I like that phrasing.
_Aside_ I'd personally use `iptables-save` because `iptables -L` hides some details. Either is fine to get a point across, and I suspect `iptables -L` is more widely known.
