### ISSUE TITLE
Fix KRIB Docs with updated software install links.

### ISSUE THREAD

**Issue by sygibson** [kubernetes/website#14062]
**This is a Bug Report**
**Problem:**

Documentation for `on-premsis-metal/krib` refers to out of date components in the install guide.  

**Proposed Solution:**

Update documentation to reference processes that don't have changing versions that may be stale quickly.  An example, instead of referencing the currently outdated Certs plugin as such:

https://s3-us-west-2.amazonaws.com/rebar-catalog/certs/v2.4.0-0-02301d35f9f664d6c81d904c92a9c81d3fd41d2c/amd64/linux/certs

Use the newly updated Catalog references like:

  drpcli plugin_providers upload catalog:certs-stable

**Page to Update:**

https://kubernetes.io/docs/setup/on-premises-metal/krib/

**Comment by zehicle** [comment]
I have an update that addresses this question using a new DRP feature.  Thank you for submitting it.
