### ISSUE TITLE
Issue with /docs/admin/cluster-management/ - automatic downscaling is underspecified

### ISSUE THREAD

**Issue by ekuefler** [kubernetes/website#1408]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

This page doesn't describe how decisions are made regarding scaling down clusters automatically. It says:

> Cluster autoscaler also scales down the cluster if it notices that some node is not needed anymore for an extended period of time (10min but it may change in the future).

How does it decide a node is "not needed"? Will it automatically kill a node's pods and drain it if it determines they can fit elsewhere? Does it only kill nodes that happen to have no pods on then? Does it require the node to be cordoned manually? The distinction is important for users to decide how clusters should be managed.

**Proposed Solution:**

Add a more complete definition of the scaling down procedure.

**Page to Update:**
http://kubernetes.io/docs/admin/cluster-management/

**Comment by tengqm** [comment]
@ekuefler Have you checked the cluster autoscaler project [here](https://github.com/kubernetes/autoscaler)? It looks like the FAQ has answered most of your questions. 
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md
Is it acceptable to simply add a link from website to the FAQ?

**Comment by ekuefler** [comment]
Yes, that FAQ answers all of my questions. I think linking to it would be reasonable.
