### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/audit/

### ISSUE THREAD

**Issue by deepakdk13** [kubernetes/website#14094]
what syntax should is used for fetching project logs from users, i am using ldap, right now my syntax is.

apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
  - level: Metadata
    userGroups: ["system:authenticated"]
    verbs: ["create", "update", "patch", "delete"]
    resources:
      - group: "project.openshift.io"
        resources: ["projectrequests", "projects"]
    omitStages:
      - RequestReceived

but i am not getting any logs

**Comment by thecrudge** [comment]
Hi @deepakdk13 

This issue would be better resolved by joining the kubernetes Slack channel, as this doesnt seem to be an issue with the page itself and rather an issue with your implementation. Please pose your problem at kubernetes.slack.com in #kubernetes 

/close
