### ISSUE TITLE
Improvement for k8s.io/docs/tasks/

### ISSUE THREAD

**Issue by vikas027** [kubernetes/website#14095]
Hey Guys,

It would be great if we can have a toggle to expand (and undo) the menu items on the left pane. 
It will make finding stuff on the page so much easier.

My recommendation is for all such pages, not just this one.

Cheers,
Vikas

**Comment by DanyC97** [comment]
Hi @vikas027 

thanks for raising this issue. 
As a note we are trying to use _folks_ as is gender neutral.

Your ask is having (un)collapse on ToC and not sure if Hugo does support that, will bring to experts attention.

**Comment by lucperkins** [comment]
@vikas027 Could you explain what you're asking for? At the moment, the menu items in the left panel *do* expand and contract.

**Comment by vikas027** [comment]
Hey @lucperkins / @DanyC97 ,

I am looking to have an option to expand and collapse (or contract) all items in the left pane with one click, something similar to what is shown [here](https://youtu.be/Ah10F3co83o?t=35) or what I have recorded in this GIF.
![2019-05-02_21-11-37 (1)](https://user-images.githubusercontent.com/6998650/57072391-e0d5cd80-6d20-11e9-880c-2a56a26fcc0a.gif)

It is just a nice to have feature, pls disregard this request if this a limitation in Hugo.

**Comment by vikas027** [comment]
anyone else thinks that this is a good idea?

**Comment by vikas027** [comment]
@lucperkins @DanyC97
