### ISSUE TITLE
Update docs style guide with community style guide

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#14101]
### What would you like to be added?

The [K8s community style guide](https://github.com/kubernetes/community/blob/master/contributors/guide/style-guide.md#markdown-formatting) grew out of the [SIG Docs style guide](https://kubernetes.io/docs/contribute/style/style-guide/). The community guide has since added guidelines that would make excellent additions to the SIG Docs style guide. For example: the K8s community has excellent guidelines for link formatting.

### Why is this needed?

It's important to keep our style guide fresh, accurate, and synchronized with best practices in the K8s community.

### Comments

Because style guides have a large impact, the PR author should expect lengthy and extensive review with multiple rounds of feedback.

A PR that resolves this issue should:

- [ ] Determine which guidelines from the K8s community style guide will improve the SIG Docs style guide.
- [ ] Invite review from stakeholders across the community, including @kubernetes/community-maintainers and @kubernetes/sig-docs-en-owners. 

/good-first-issue
/sig docs
/cc @parispittman @nikhita @mrbobbytables

**Comment by DanRoscigno** [comment]
I would like to work on this issue.

**Comment by zacharysarah** [comment]
@DanRoscigno Feel free to open a PR, even just a placeholder to get started. 

One tip: if you include the words `Fixes #14101` or `closes #14101` in the original description, GitHub automatically closes this issue when the PR merges.

**Comment by DanRoscigno** [comment]
List of topics in the community guide:
- [ ] Contact info
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by DanRoscigno** [comment]
As I dig in deeper to the templates, content organization, and Hugo shortcode pages I expect to find some of the unchecked items.  More in a bit.

**Comment by zacharysarah** [comment]
@aimeeu Another good place to start

**Comment by DanRoscigno** [comment]
@aimeeu I did a little research, ping me here and I can catch you up.  I have been out of town for a few weeks on an assignment and not looked at this in a while!

**Comment by aimeeu** [comment]
@DanRoscigno thanks! I’m on vacation until Monday, 5 August. I’ll ping you next week.

**Comment by jaypipes** [comment]
@zacharysarah hey, so are there specific PRs for this Issue that you'd like reviewed? or are you just looking for feedback on the overall list of tasks you want to get done?

**Comment by zacharysarah** [comment]
@jaypipes This issue is probably more complicated than can be reasonably accomplished in a sprint. 

This issue will probably require a series of iterative PRs. Feedback is also welcome!
