### ISSUE TITLE
Glossary term “workloads” should be singular

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14107]
**This is a Bug Report**

**Problem:** Most glossary terms are singular, any exceptions have a good reason to be. “Workloads” is plural though and I don't see a good reason for that.

(not important; it's a nit the project might want to fix)

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?all=true#term-workloads

**Comment by geass** [comment]
`Workloads` is the main category on the concepts doc that contains pods and controllers. That's why it's plural.

There are some other plurals like `Container Environment Variables` or `Resource Quotas` as they should be.

**Comment by sftim** [comment]
I wonder if we can use a singular in the glossary, keeping a plural in the concepts section.

The other two I think fit better, because we apply a _set_ of environment variables and a _set_ of quotas. Conversely, deploying just one workload to a cluster is absolutely a thing that people might do.

**Comment by sftim** [comment]
Done
