### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by malathit** [kubernetes/website#14104]
**This is a Bug Report**

**Problem: The image kubernetes/redis:v1 is not available**

**Proposed Solution: The image has to be available so that the documentation might work**

**Page to Update:**
https://k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

**Comment by thecrudge** [comment]
Hi @malathit90 

This is due to the community removing the kubernetes images from docker hub because of the recent security breach. I have submitted PR #14106 to address this issue. If you see anything else, please let us know.

**Comment by sftim** [comment]
I think this was solved by https://github.com/kubernetes/website/pull/14177; is that right?

**Comment by thecrudge** [comment]
resolved by #14177

/close
