### ISSUE TITLE
Improvement for k8s.io/docs/tasks/debug-application-cluster/audit/

### ISSUE THREAD

**Issue by dev1983** [kubernetes/website#14105]
The document is having very less information. As while applying audit facing below issue under version v1.14.1. 

--audit-policy-file=/etc/kubernetes/audit-policy.yaml

[root@kube-master kubernetes]# kubectl apply -f sample-audit-policy.yaml
error: unable to recognize "sample-audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1" or audit.k8s.io/v1beta1 or alpha1

Supported versions are below; did not find any audit.k8s.io? Please provide how I can get it.

[root@kube-master ~]# kubectl api-versions
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
coordination.k8s.io/v1
coordination.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
networking.k8s.io/v1
networking.k8s.io/v1beta1
node.k8s.io/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1

**Comment by tengqm** [comment]
this one? https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#policy-v1alpha1-auditregistration-k8s-io

**Comment by dev1983** [comment]
[root@kube-master manifests]# grep -i apive /etc/kubernetes/policies/audit-policy.yaml
#apiVersion: audit.k8s.io/v1 # This is required.
apiVersion: auditregistration.k8s.io/v1alpha1 # This is required.

[root@kube-master manifests]# kubectl apply -f /etc/kubernetes/policies/audit-policy.yaml
error: unable to recognize "/etc/kubernetes/policies/audit-policy.yaml": no matches for kind "Policy" in version "auditregistration.k8s.io/v1alpha1"

you can try with policy : https://kubernetes.io/docs/tasks/debug-application-cluster/audit/?utm_campaign=Aqua%20Digest&utm_source=hs_email&utm_medium=email&utm_content=67053398&_hsenc=p2ANqtz-8D_uT7XGtsJuA4qM811kfn-PdMglbbIOxwTohICb3LGyfe-Wpfbh-0n1n82TkM3KCgGsWB5d8XGbelyP6IdxYfmPoLFIu06ArA3uCEdqazef0eRr8&_hsmi=67053398
