### ISSUE TITLE
Box not alligned with text in k8s.io/docs/tutorials

### ISSUE THREAD

**Issue by prankul88** [kubernetes/website#14114]
**This is a Bug Report**

**Problem:**
Under "Learn Kubernetes Basics" in provided URL, all sub topics have a "Summary" box.
When I open the URL with default zoom "125%" , the box is not alligned with the text inside it.
Note: I tried altering zoom value, this bug only occured at 125%; I am using Google Chrome

**Proposed Solution:**
The box must be alligned with the text inside it

![Screenshot from 2019-05-01 11-25-13](https://user-images.githubusercontent.com/40868849/57007386-dd99ef00-6c05-11e9-9158-d19a95f5a1c9.jpg)

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/#summary

**Comment by geass** [comment]
When I tested, it seems okay to me.

Tested on chrome, firefox and safari with %100 - %250 zoom ranges.

<img width="1425" alt="Screen Shot 2019-05-01 at 12 26 45" src="https://user-images.githubusercontent.com/1788968/57013590-7fbcd580-6c0c-11e9-9528-baa826a51705.png">

Can you say what is the version of your chrome?

**Comment by prankul88** [comment]
@geass I am using 73.0.3683.86 (Official Build)

**Comment by adisky** [comment]
getting the same issue on chrome!!

**Comment by prankul88** [comment]
Closing since the issue is ambiguous and seems to be fixed when I open the same URL now.
