### ISSUE TITLE
Update /docs/contribute/generate-ref-docs

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#14111]
**This is a Feature Request**

Review https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/ and https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/ for technical accuracy. At it's current state it's currently not usable. 

**What would you like to be added**
- [ ] Any references to software versions (like docker / etcd) should be pinned to ensure success
- [ ] Review active steps to generate docs (removing incorrect or irrelevant info)

**Why is this needed**
To make it easier for the sig-docs release lead to generate ref docs content.

**Comments**

- Here's a shorthand cheat of how I generated the API docs: https://github.com/kubernetes/website/pull/13462#issuecomment-476944536
- Shorthand cheat of how I generated the components: https://github.com/kubernetes/website/pull/13465#issuecomment-476959426

I can own this, but have some backlog to clear out first before I can get to it. If there's someone who's available now to tackle this sooner, I'm happy to work with you!

/cc @MAKOSCAFEE @tengqm

**Comment by tengqm** [comment]
Ping me if anything I can help.

**Comment by SupriyaSirbi** [comment]
Hello Jim and Tengqm,

I am interested to work on this issue.

Thanks

**Comment by claurence** [comment]
@jimangel - this issue is open on the 1.15 milestone - is this planning to happen in the 1.15 release?

**Comment by jimangel** [comment]
@claurence - detaching from the milestone to not affect the Docs deadline. I will add to the 1.16 milestone; if not resolved before then. Thanks!

**Comment by kbhawkey** [comment]
Hello. I will update the documentation for generating the API reference and sync up with @jimangel 's cheatsheet. Which format is easier to follow? I am somewhat in favor of the less verbose, task-oriented instructions. Let me know what you think. I will temporarily assign this issue to myself.
/assign @kbhawkey

**Comment by jimangel** [comment]
@kbhawkey @tengqm @makoscafee - It sounds like there is work underway to improve process and surrounding documentation, thanks!

@simplytunde - This has been a major issue for the past 2 releases. Please keep up with this discussion and I would strongly encourage you trying to generate the 1.15 docs again (for testing when 1.16 is ready).

**Comment by kbhawkey** [comment]
Hi @jimangel . Just letting you know that I am working on #18567.
