### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by farzadmf** [kubernetes/website#14122]
I tried to follow the tutorial, but the docker image `kubernetes/redis:v1` doesn't seem to exist :(

**Comment by prankul88** [comment]
Thank you for reporting this issue.
The image doesnot exist and must be replaced with simply `redis`

**Comment by sftim** [comment]
Is this OK to close?

**Comment by farzadmf** [comment]
Yes, sorry for the late reply, with the suggested changes for that tutorial, I'm going to close this
