### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by EdinCitaku** [kubernetes/website#14127]
**This is a Bug Report**

**Problem:**
When following this Tutorial:
https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/
and using the file pods/config/redis-pod.yaml to create a pod
you get as pod Status "ErrImagePull". When using 

`kubectl describe pods redis`
you can see the following error:
`pull access denied for kubernetes/redis, repository does not exist or may require 'docker login'`

**Proposed Solution:**
Update pods/config/redis-pod.yaml so it uses a valid image
**Page to Update:**
https://kubernetes.io/...

**Comment by dims** [comment]
@EdinCitaku please edit the `redis-pod.yaml` as shown below:
https://github.com/kubernetes/website/pull/14123/files

/close
