### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/master-node-communication/

### ISSUE THREAD

**Issue by sveryovka** [kubernetes/website#14130]
**This is a Documentation Update Request**

**Problem:**
https://kubernetes.io/docs/concepts/architecture/master-node-communication/#master-to-cluster defines two primary communication paths from the master (apiserver) to the cluster - apiserver to kubelet and apiserver to nodes, pods, and services
Documentation says that "apiserver to nodes, pods, and services" is not surecure. However it is hard to understand severity of this since it is not explained in which cases and for what purposes there culd be apiserver to nodes, pods, and services communication. Can you pleas explain this and also explan what data in exchanged between components in case of apiserver to nodes, pods, and services communication.

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/master-node-communication/#apiserver-to-nodes-pods-and-services

**Comment by sftim** [comment]
Thanks for reporting this. It sounds like this is an area where we could improve on existing documentation.
