### ISSUE TITLE
Ineffective preStop example in Working with Containers in Production document

### ISSUE THREAD

**Issue by dominikh** [kubernetes/website#1414]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The _Working with Containers in Production_ document includes a preStop hook to terminate nginx gracefully by sending it the SIGQUIT signal (nginx exits gracefully on SIGQUIT and immediately on SIGTERM).

Based on my understanding of the preStop hook and nginx, this hook is ineffective. As per http://kubernetes.io/docs/user-guide/container-environment/#container-hooks after preStop returns, the process is still sent SIGTERM. Since `nginx -s` only sends a signal and returns immediately, and since nginx will not ignore the following SIGTERM, nginx will still exit almost immediately and not shut down gracefully.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/user-guide/production-pods/#lifecycle-hooks-and-termination-notice

**Comment by jeffmendoza** [comment]
Hi @dominikh what is the proposed solution? thanks

**Comment by dominikh** [comment]
I do not have a proposed solution, sorry. I went to the documentation to find a solution in the first place.

**Comment by jeffmendoza** [comment]
I see, thank you. Let's leave this here in case we get some help.
