### ISSUE TITLE
Issue with k8s.io/docs/concepts/

### ISSUE THREAD

**Issue by ricksevans** [kubernetes/website#14151]
It seems to me the "Concepts" page should define the concept of a Cluster.
The current Concepts page just assumes the reader knows what a Cluster is. 
Is a cluster a set of Pods?
Is a cluster a set of tightly coupled Pods?
Is a cluster a set of Worker Nodes (Pod Hosts)? 
Is a cluster a single Master Node and it set of minion Worker Nodes directly managed by the Master? 
Is a cluster a set of Master Nodes in an HA configuration plus ALL the minion Worker Nodes?
Is a cluster all the Master Nodes and Worker Nodes used to host the pods that make up an application, regardless of the physical locallity of those Nodes? 
Is a cluster another name for an application?
Is a cluster another name for a web service?
Is a cluster whatever the Developer thinks it is?
Is a cluster whatever the Operator thinks it is?

**Comment by tengqm** [comment]
Is this what you are looking for?

https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-cluster

**Comment by ricksevans** [comment]
@tengqm, yes, Adding something like the two lines from that simple definition you referred to, to the _Concept_ page would suffice.

**Comment by sftim** [comment]
This looks straightforward to work on. I would tweak the [existing glossary definition](https://kubernetes.io/docs/reference/glossary/?all=true#term-cluster), then include that revised definition into the [Concepts](https://kubernetes.io/docs/concepts/) page with a Hugo [shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/):
```markdown
{{< glossary_definition term_id="kube-scheduler" length="all" >}}
```

If you're a new contributor picking this up, have a look at [Improve existing content](https://kubernetes.io/docs/contribute/start/#improve-existing-content). The easiest way to submit a pull request that changes more than one file is to use Git and a local text editor to propose changes; GitHub's web interface is too simplistic (in my opinion).

Add a comment here if you're keen to contribute but would like more advice.

/good-first-issue

**Comment by sftim** [comment]
The two [commits](https://github.com/kubernetes/website/pull/14537/commits) in PR 14537 are similar to what I'd do to fix this issue. For this issue, it's about tweaking an existing glossary entry and then using the _definition_ (not the tooltip) in the concept page.

**Comment by jhbiggs** [comment]
Hello, would like to contribute.  Confirming: you'd like an addition to the current definition, and the inclusion of that definition in the concept page via Hugo shortcode.

**Comment by sftim** [comment]
@jhbiggs: what you summarized matches what I have in mind. If you'd favored a different approach, that could be OK too!

**Comment by sftim** [comment]
Done
/close
