### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-service/

### ISSUE THREAD

**Issue by zrml** [kubernetes/website#14167]
**This is an Enhancement Request**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

I'd like to have a section on StatefulSet and services. 
Thanks

**Comment by DanyC97** [comment]
@zrml are you looking after https://kubernetes.io/docs/tasks/debug-application-cluster/debug-stateful-set/ and https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ ?

**Comment by zrml** [comment]
@DanyC97 No I'm not.

**Comment by DanyC97** [comment]
@zrml okay then would you mind providing more info as to  what you would like to have in addition to the above pages i've mentioned ? 

/triage needs-information

**Comment by DanyC97** [comment]
gentle reminder @zrml

**Comment by zrml** [comment]
@DanyC97 thanks for the reminder... too many flights and lounges. I misunderstood your comments above. I'm OK with the links you provided for now. I'm hoping to progress my K8s work this week. I may get back to you. Close this for now. Thanks a million and apologies.

**Comment by DanyC97** [comment]
no need to apologies @zrml , thank you for feedback.
/close
