### ISSUE TITLE
Got an error "crashloopbackoff" when run redis slave in Guestbook example app

### ISSUE THREAD

**Issue by manthang** [kubernetes/website#14160]
**Problem:**
Got an error "crashloopbackoff" when run this step "Apply the Redis Slave Deployment from the redis-slave-deployment.yaml file".

**Proposed Solution:**
Problem resolved when I change the image version to v3:
gcr.io/google_samples/gb-redisslave:v3

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#start-up-the-redis-slaves

**Kubernetes Version:**
v1.14.0

**Comment by sftim** [comment]
If anyone's picking this up as a first issue:
- [sign](https://kubernetes.io/docs/contribute/start/#sign-the-cla) the contributor license agreement (if you haven't already)
- Follow our [guide](https://kubernetes.io/docs/contribute/start/) to [create and submit a pull request](https://kubernetes.io/docs/contribute/start/#submit-a-pull-request)

**Comment by rajvaibhavdubey** [comment]
@sftim I would like to work on this.
ThankYou.

**Comment by sftim** [comment]
Thanks for offering, @rajvaibhavdubey !
