### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/components/

### ISSUE THREAD

**Issue by scifihotchoc** [kubernetes/website#14162]
**This is a Bug Report**

**Problem:**
There are many mentions of a kubernetes "pod" but there is no explanation or a link to an explanation of what a pod is.

**Proposed Solution:**
Provide a link to the documentation section on pods and add a line to say "learn more about pods".

**Page to Update:**
https://kubernetes.io/...
The page listed in this issue.

**Comment by DanyC97** [comment]
@scifihotchoc will having https://kubernetes.io/docs/reference/glossary/?fundamental=true `Pod` glossary definition do the job ?

**Comment by sftim** [comment]
For this overview page in particular, I suggest that _everything_ that has a glossary entry be replaced by a use of that glossary term (via Hugo shortcode), at least on the first use on the page. Possibly subsequent uses too where that looks relevant.

How does that sound?
