### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/admission-controllers/ - kube-apiserver -h 

### ISSUE THREAD

**Issue by ensonic** [kubernetes/website#14179]
**This is a Bug Report**
**Problem:**
The page suggests to run `kube-apiserver -h` where the binary is actually located inside a container.

**Proposed Solution:**
```
kubectl exec $(kubectl get --no-headers=true pods -l component=kube-apiserver -n kube-system -o custom-columns=:metadata.name) -n kube-system -- kube-apiserver -h
```

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#which-plugins-are-enabled-by-default

If the change sounds good I'll send a PR

**Comment by tengqm** [comment]
It actually depends on how kube-apiserver is deployed, right? There doesn't seem to be a way to work on all deployments IIUC.

**Comment by ensonic** [comment]
Right, this was on a kubeadm instance. On GKE I can't see the kube-apiserver at all. to me ` kube-apiserver -h` is the least likely way to check this. That said, my proposal is not generic enough either. 

It would be nice if `kubectl cluster-info dump` would contain such information.
