### ISSUE TITLE
Create a publish date on the reference docs

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#14180]
**This is a Feature Request**
Add publish date or commit ID to references.
Update generated references post-processing or update the generation process.

**What would you like to be added**
The reference guides are published each release without a published date on the page, making it difficult to know if the page corresponds to the release. 
Rationale: If content, task, tutorial pages have been updated, a commit message is added to the page on the footer.
Some ideas for adding the publish version to the references:
- Add a footer with the publish date and commit ID.
- Update the reference TOC with the release version.

**Why is this needed**
Boost confidence level of published reference docs.

**Comments**
See issue #13396.

**Comment by kbhawkey** [comment]
Great, @tengqm. I am interested in reviewing your proposal.

**Comment by tengqm** [comment]
@kbhawkey I just took a quick look at the docs we are serving. There are cases where the generated docs are wrapped into some contents. For example: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

I don't have a good idea where to insert the "generated at: <DATETIME>" string for such cases. Any thoughts?

**Comment by tengqm** [comment]
Alright, we can do API reference and the HTML style kubectl reference first.

**Comment by tengqm** [comment]
For API reference, done: https://github.com/kubernetes-incubator/reference-docs/pull/78
For HTML style kubectl reference, need to decide *again* which route to go. If you take a look at the generators, there is `gen-kubectldocs` for HTML output and `kubectl` docs can be generated as other command line tools as well.

**Comment by sftim** [comment]
For the `kubectl` docs, how about adding the generated date just after:
```html
<div class="copyright"><a href="https://github.com/kubernetes/kubernetes">Copyright 2019 The Kubernetes Authors.</a></div>
```

**Comment by sftim** [comment]
Feels useful but not vital
/remove-lifecycle rotten

**Comment by kbhawkey** [comment]
- I plan on closing this issue. I believe @tengqm added a publish date to the API reference.
Something similar could be added to the kubectl command reference, if there is an interest.
- A publish date (or commit id) on a content page is an effective way of establishing when the content was changed/updated. Just displaying the page as part of a particular release set does not guarantee that the page was actually updated.
/close
