### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

### ISSUE THREAD

**Issue by sachet94** [kubernetes/website#14181]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

the mentioned thing in the deployment files 
are enough orelse is there anything else we cam mention ??

**Comment by sftim** [comment]
Hi @sachet94 
Can you explain more about the shortcoming you're reporting here?
