### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by QHose** [kubernetes/website#14196]
**This is a Bug Report**

**Cannot connect to host error in tutorial, using the predefined commands
**Proposed Solution:**
Update capacity of demo server
**Page to Update:**
https://kubernetes.io/...

**Comment by zhangqx2010** [comment]
@QHose  In which step did the error occur? The initialization may take a little time.
