### ISSUE TITLE
Add sig-docs contributor guide to Community project

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14201]
**This is a Feature Request** _that targets https://github.com/kubernetes/community/_

Kubernetes as a project has an overall [guide](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md) for contributors, and a section:
https://github.com/kubernetes/community/blob/master/contributors/guide/README.md#sig-specific-contributing-guidelines
about SIG-specific contributions.

How about we represent sig-docs there as well?
At the moment several SIGs are represented, but not documentation.

**What would you like to be added**

Eg, we add a page at https://github.com/kubernetes/community/blob/master/sig-docs/CONTRIBUTING.md that signposts people to the website repo, as that's where the main part of sig-docs effort goes.
and we get the main contributor guide to link to this (maybe it's automatic, I haven't checked).

We might also need to make small tweaks to other pages in this ([website](https://github.com/kubernetes/website/)) repo, moving things round for a smoother experience.

**Why is this needed**
I'm logging this here so that it's visible as an issue in the repo that sig-docs contributors are most likely to look at.

**Comments**
This is a low-priority change aimed at smoothing the experience for potential and actual new contributors.

**Comment by zhangqx2010** [comment]
How about this page?
https://kubernetes.io/docs/contribute/

**Comment by sftim** [comment]
This is about signposting. We can link to all those pages to make them more discoverable.

**Comment by sftim** [comment]
/help
(if anyone would like to - it's a very low priority)

**Comment by sftim** [comment]
Since this was logged, we gained https://www.kubernetes.dev/
