### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/

### ISSUE THREAD

**Issue by Ramin2c** [kubernetes/website#14204]
**This is a Bug Report**

According to the instruction, the user should be able to see the desired and current status by running the get deployments command.
The command "kubectl get deployments" does not show the replica set and by that the upcoming statement is wrong:
_"The DESIRED state is showing the configured number of replicas
The CURRENT state show how many replicas are running now"_

**Proposed Solution:**
Proposed text is as follows:
-------------------
To list your deployments use the get deployments command: kubectl get deployments
We should have 1 Pod. If not, run the command again.

To list the replica set use the get rs command: kubectl get rs
This shows:

The DESIRED state is showing the configured number of replicas
The CURRENT state show how many replicas are running now
-------------------
the rest of the instruction is OK.

**Page to Update:**
https://kubernetes.io/...

**Comment by zhangqx2010** [comment]
@BenHall
