### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by JensHaley** [kubernetes/website#14205]
**This reports an issue with the documentation**

**Problem:**
Set up Ingress on Minikube with the NGINX Ingress Controller
-> Create an Ingress resource ([direct link](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource)) -> Step 4.

says that you should add the **ingress IP** to your `/etc/hosts` file. 

This does not seem to work. It would be interesting to get a qualified answer why.

In other sources ([ingress-nginx](https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/opentracing/#jaeger) repository; issue [#2922](https://github.com/kubernetes/minikube/issues/2922)) the solution seems to be to use the `minikube ip`.

**Proposed Solution:**
Replace step 4 by:

```bash
echo "$(minikube ip) example.com" | sudo tee -a /etc/hosts
```

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource

**Kubernetes Version:**
1.14

**Comment by DanyC97** [comment]
/language en
/sig cluster-lifecycle

@tstromberg @afbjorklund any chance you can chime in case there is a known issue ?

**Comment by JensHaley** [comment]
I saw a note was added - thank you.

Closing this issue
