### ISSUE TITLE
Pod exec endpoint missing from API reference

### ISSUE THREAD

**Issue by lbogdan** [kubernetes/website#14210]
In what seems like a strange bug in generating the API reference, the pod exec endpoint is missing, although it's there in the [OpenAPI spec](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json), which I assume is the source.

It also seems it's been missing since the current version of the API reference starting with `1.10`.

**Comment by tengqm** [comment]
Triaged. It looks like the OpenAPI parser has some hard coded path patterns. Need some research.

**Comment by tengqm** [comment]
filed an issue: https://github.com/kubernetes-sigs/reference-docs/issues/96
