### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/overview/

### ISSUE THREAD

**Issue by renich** [kubernetes/website#14211]
**This is a Bug Report**

**Problem:**
In the kubectl documentation, you provide examples of short options using and equals sign right after. For example: `-o=wide`. 

This isn't the posix or gnu convention. See at the bottom: https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

**Proposed Solution:**
Adhere to the posix or gnu conventions. Use either:

```
-o yaml
```

or

```
--output=yaml
```

**Page to Update:**
k8s.io/docs/reference/kubectl/overview/

**Comment by zhangqx2010** [comment]
It's not good format though the doc stills works.
If you like, you are welcomed to create PR to fix this. I can help if you have any problem during the process.

/good-first-issue

**Comment by sftim** [comment]
I'm going to run through this with @abuango as an example

**Comment by sftim** [comment]
Done
/close
