### ISSUE TITLE
Document Service Account Key Rotation 

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#1421]
Document the flags and procedure described in the first comment of https://github.com/kubernetes/kubernetes/pull/34029

Additional content for the doc:
- service accounts have creds that allow them to access the API server.
- service account creds are signed with a service account signing key.
- If you want to revoke a single service account key, delete it's secret.  The deleted secret should not be recognized the next time you use it.
- If you think a signing key was compromised (e.g. employee with access to it left), or just want to be thorough, then you can rotate signing keys using the procedure mentioned above.

**Comment by erictune** [comment]
@cjcullen @alex-mohr @roberthbailey

**Comment by krmayankk** [comment]
@tengqm @kubernetes/sig-docs-en-owners FYI

**Comment by zacharysarah** [comment]
@krmayankk 👋 In the meantime, consider asking for help in [Kubernetes Slack](https://kubernetes.slack.com/messages/C0X2V69D0/details/) if you haven't already.
