### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by vanrein** [kubernetes/website#14223]
The complaint about the URL also occurs when simply running `kubectl version`.  At that position in the manual, the message has not been explained yet.  Better move it up then.

**Comment by sftim** [comment]
@vanrein: can you clarify which message you're referring to, so that it's clear what needs explaining better?

**Comment by prankul88** [comment]
Hi @vanrein ,I feel verification must be after all the installation guides, which is just what is done in the documents . So rather than moving it up, a "note" referring to the verification section might be helpful. 

Would appreciate your thoughts on this!

**Comment by vanrein** [comment]
Hi Prankul,

> Hi @vanrein ,I feel verification must be after all the installation guides, which is just what is done in the documents . So rather than moving it up, a "note" referring to the verification section might be helpful. 
>
> Would appreciate your thoughts on this!

Sounds good to me :)

-Rick
