### ISSUE TITLE
Issue with katacoda bash terminal

### ISSUE THREAD

**Issue by prankul88** [kubernetes/website#14244]
**This is a Bug Report**

**Problem:**
"In browser katacoda terminal" is incosistent. In the first image attached, when the minikube setup is completed, the terminal does not show the space to write commands. Rather the user is forced to scale up the terminal.

![s1](https://user-images.githubusercontent.com/40868849/57432952-cdf95680-7254-11e9-9514-4a5c674790b1.jpg)
 
Also when we scale up the terminal, there is no option to scale it back to the original ratio.(image attached below)

![s2](https://user-images.githubusercontent.com/40868849/57433126-46601780-7255-11e9-8c58-457f64c53b77.jpg) 

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by zhangqx2010** [comment]
The first issue doesn't appear by my try.
While the second one is really a problem. It will cover the almost whole page and I found no way to scale the window.
@BenHall Not sure whether I should @ you or not.

**Comment by poothia** [comment]
@prankul88 I think the first part of the issue is due to the browser, It's working fine with firefox but with chrome it's giving this issue. what browser are you using?

**Comment by prankul88** [comment]
Hi @zhangqx2010 , I am not sure whether the first issue exists only for me.  The second one must be addressed. I will look to create a PR for the same once I confirm the first issue.

**Comment by prankul88** [comment]
Hi @poothia , I can confirm that the first issue exists in both chrome and firefox browser. I am using Ubuntu 18. 
Which operating system are you using?

**Comment by poothia** [comment]
@prankul88 I am using ubuntu 16.

**Comment by adisky** [comment]
verified on windows!! its is valid

**Comment by BenHall** [comment]
Thanks for the feedback! We'll get this fixed ASAP.

**Comment by prankul88** [comment]
Closing, the issue is rightly conveyed to the concerned person.

**Comment by poothia** [comment]
@prankul88 is this issue fixed?

**Comment by prankul88** [comment]
@poothia Ya it is still there. Not sure if there is a need to keep this issue open. Thoughts?

**Comment by poothia** [comment]
@prankul88 I think you should reopen the issue so that it can be tracked.
