### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by nk-gears** [kubernetes/website#14262]
**This is a Bug Report**

**Problem:**

Web UI is scattered for the yaml file contents.  But, the Git preview of the yaml file looks good.

![Screen Shot 2019-05-10 at 2 30 14 PM](https://user-images.githubusercontent.com/897323/57515445-4da82380-7330-11e9-8989-93e9743f806b.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
This was corrected in #14447 and #14449 

/close
