### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/coarse-parallel-processing-work-queue/

### ISSUE THREAD

**Issue by trevorackerman-wk** [kubernetes/website#14275]
**This is a Bug Report**

**Problem:**
Dockerfile https://kubernetes.io/examples/application/job/rabbitmq/Dockerfile has old version of Ubuntu which doesn't work correctly with the rabbitmq controller

I kept getting a socket error in the logs of the jobs about connecting to amq

Meanwhile in the rabbitmq controller logs I finally noticed
`2019-05-10 21:50:53.512 [error] <0.688.0> closing AMQP connection <0.688.0> (172.17.0.7:55148 -> 172.17.0.5:5672):
failed to negotiate connection parameters: negotiated channel_max = 0 (no limit) is higher than the maximum allowed value (2047)`

I was confused because running the temp pod had no trouble pulling messages from the queue.

I finally noticed that the temp pod was running from Ubuntu 18.04 but the example Dockerfile is running from 14.04

I updated my local dockerfile to 18.04 and the example worked as advertised.

**Proposed Solution:**
Bump the base ubuntu image in https://kubernetes.io/examples/application/job/rabbitmq/Dockerfile from 14.04 to 18.04

**Page to Update:**
https://kubernetes.io/...

`Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by sftim** [comment]
Thanks for filing this report. Looks like something worth fixing!

/kind bug

**Comment by trevorackerman-wk** [comment]
Does using a work queue for doing "coarse grained parallelism" require
using queuing service that implements amqp? What other options are
available?

Thanks
