### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by noxon73** [kubernetes/website#1427]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

---

http://yum.kubernetes.io/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://yum.kubernetes.io/repos/kubernetes-el7-x86_6
4/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')

**Proposed Solution:**
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

**Page to Update:**
http://kubernetes.io/...

1.4.0

**Comment by luxas** [comment]
@dgoodwin @errordeveloper

**Comment by errordeveloper** [comment]
@mikedanese any news on getting HTTPS enabled for our repo?

**Comment by dgoodwin** [comment]
I think this was a transient bug, the above link is working fine for me, anything we can do @mikedanese or should we close this?

**Comment by errordeveloper** [comment]
@dgoodwin I think the user is behind a firewall that only allows HTTPS traffic...
