### ISSUE TITLE
Issue with k8s.io/docs/concepts/

### ISSUE THREAD

**Issue by KrishnaKotari** [kubernetes/website#14271]
**This is a Bug Report**

**Problem:**
Navigation of docs is pretty difficult. Once I go through the entire doc, I have to scroll back again to the top and click on the next topic from the left pane. It's cumbersome and looses the flow

**Proposed Solution:**
Solution involves two parts, 

- Have a pane at the bottom and top of the docs pane with "**Next**" and "**Previous**" buttons

- The list of contents pane on the left of the document pane should be visible at all times. It would be easy to jump in to the topic right from the point I'm reading rather than scrolling to the top and then clicking on the topic of interest

**Page to Update:**
https://kubernetes.io/docs/

**Kubernetes Version:**
1.14

**Comment by sftim** [comment]
Thanks for this suggestion @KrishnaKotari 
This is similar to #14261 so I'll mention that issue here too.

/kind feature

**Comment by sftim** [comment]
If the documentation gains a concept of “next” and “previous” documents, there's potential to add HTTP `Link:` headers or HTML `<link>` elements to add the same information as metadata. (That could be a separate issue if there's interest in the idea).
