### ISSUE TITLE
Formatting for YAML code of Create an Ingress is not correct

### ISSUE THREAD

**Issue by nitishkumar71** [kubernetes/website#14284]
**This is a Bug Report**

**Problem:**
In Task page for the given [URL](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource), formatting of YAML code to create an ingress is not correct. Although on checking the [content/en/docs/tasks/access-application-cluster/ingress-minkube.md](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/access-application-cluster/ingress-minikube.md), I found it correct.
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource

**Comment by kbhawkey** [comment]
Duplicate with #14293?

**Comment by Vageesha17** [comment]
working on this issue as it would be good start.

**Comment by thecrudge** [comment]
api version, and formatting have been corrected in #14449 and #14447 

/close
