### ISSUE TITLE
Issue with /docs/getting-started-guides/docker-multinode/

### ISSUE THREAD

**Issue by beravelli** [kubernetes/website#1429]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:** etcd container fails to start..

+++ [1011 10:49:00] K8S_VERSION is set to: v1.4.1
+++ [1011 10:49:00] ETCD_VERSION is set to: 3.0.4
+++ [1011 10:49:00] FLANNEL_VERSION is set to: v0.6.1
+++ [1011 10:49:00] FLANNEL_IPMASQ is set to: true
+++ [1011 10:49:00] FLANNEL_NETWORK is set to: 10.1.0.0/16
+++ [1011 10:49:00] FLANNEL_BACKEND is set to: udp
+++ [1011 10:49:01] RESTART_POLICY is set to: unless-stopped
+++ [1011 10:49:01] MASTER_IP is set to: localhost
+++ [1011 10:49:01] ARCH is set to: amd64
+++ [1011 10:49:01] IP_ADDRESS is set to: 10.96.51.238
+++ [1011 10:49:01] USE_CNI is set to: false
+++ [1011 10:49:01] USE_CONTAINERIZED is set to: false
+++ [1011 10:49:01] --------------------------------------------
+++ [1011 10:49:01] Killing docker bootstrap...
+++ [1011 10:49:01] Killing all kubernetes containers...
Do you want to clean /var/lib/kubelet? [Y/n] Y
+++ [1011 10:49:04] Launching docker bootstrap...
+++ [1011 10:49:05] Launching etcd...
c4f24b9db3bd4674f8fb68727df24839f2e9830e65f9d524bdaae72250a30b14
!!! [1011 10:49:26] etcd failed to start. Exiting...

**Proposed Solution:**
I tried to launch the "gcr.io/google_containers/etcd-amd64:3.0.4" container manually and it was launched with out issues.

**Page to Update:**
http://kubernetes.io/...

v1.4.1

+++ [1011 10:49:00] K8S_VERSION is set to: v1.4.1
+++ [1011 10:49:00] ETCD_VERSION is set to: 3.0.4
+++ [1011 10:49:00] FLANNEL_VERSION is set to: v0.6.1
+++ [1011 10:49:00] FLANNEL_IPMASQ is set to: true
+++ [1011 10:49:00] FLANNEL_NETWORK is set to: 10.1.0.0/16
+++ [1011 10:49:00] FLANNEL_BACKEND is set to: udp
+++ [1011 10:49:01] RESTART_POLICY is set to: unless-stopped
+++ [1011 10:49:01] MASTER_IP is set to: localhost
+++ [1011 10:49:01] ARCH is set to: amd64
+++ [1011 10:49:01] IP_ADDRESS is set to: 10.96.51.238
+++ [1011 10:49:01] USE_CNI is set to: false
+++ [1011 10:49:01] USE_CONTAINERIZED is set to: false

**Comment by tengqm** [comment]
hehe, ther "rotten" label is funny...

@beravelli Can we close this because it doesn't look like a documentation issue, the report is about k8s v1.4.1 and many things changed ?
