### ISSUE TITLE
Update the What is Kubernetes Page

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/website#14306]
**This is a Feature Request**

I know @chenopis  already has issue #12333 opened, but more can be done to improve the page in giving a good intro for new users. The current one seems to go all over the place and is a bit distracting at the moment.

**What would you like to be added**

1) I was under the impression that K8s is not a PaaS and the documentation desired to steer clear of that labelling. The comparison also requires the clarifications on how Kubernetes is _not_ a PaaS, which makes the introduction more confusing. If so, one would need to rewrite most of the page.
2) I believe that it is too early to mention topics such as labels and annotations, and it'd be best to keep it in broad terms.
3) A FAQ section explaining some of the terminology, choices, and limitations would be ideal.

**Why is this needed**

This is the first page of the documentation-- I believe that the documentation should give a concise first impression that doesn't lie to children or open up cans of worm that loses focus.

**Comments**

cc: @steveperry-53 @zacharysarah

**Comment by juandiegopalomino** [comment]
if someone could add it to project https://github.com/kubernetes/website/projects/3 that'd be awesome

**Comment by DanyC97** [comment]
since this falls under the Q2 priorities i'll set the priority of this issue as needed

/priority important-soon
/language en
