### ISSUE TITLE
The instructions for installing Cilium omit the `--pod-network-cidr` argument, create mesh that doesnt work

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/website#14323]
**This is a Bug Report**

**Problem:**

When following the instructions to install `cilium` with `kubeadm`, the instructions omit the inclusion of the `--pod-network-cidr` argument.

This appears to create a condition in which the `kube-proxy` does not SNAT traffic correctly on its return path for containers using the host network -- including those critical for cilium, such as the cilium agent.

This means the install fails.

See https://cilium.io/blog/2018/09/26/bionic-beaver/

**Proposed Solution:**

Update:

https://cilium.io/blog/2018/09/26/bionic-beaver/

To include the pod CIDR. I just used the one supplied on that page, and it sems to work allright. Better run it past the Cilium authors though.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

Kubernetes version 1.14

**Comment by neolit123** [comment]
@andrewhowdencom thanks for catching this.
> the instructions omit the inclusion of the --pod-network-cidr argument.

yes, this is true.
are you willing to help by submitting a PR for this repository to fix the problem?

/sig cluster-lifecycle
