### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/

### ISSUE THREAD

**Issue by szuecs** [kubernetes/website#14330]
**This is a request for better documentation**

**Problem:**

The text in https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/ is quite hard. For example: why kubelet needs to have `--authentication-token-webhook` is not clear enough to understand the request flow.

**Proposed Solution:**

There should be a statechart diagram or a request flow picture to make the process of authentication and authorization more clear.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/

**Comment by sftim** [comment]
Thanks for the suggestion @szuecs 
/language en
