### ISSUE TITLE
Syntax highlight of commands example

### ISSUE THREAD

**Issue by FranklinYu** [kubernetes/website#14336]
**This is a Feature Request**

**What would you like to be added**
In the code, separate command and output.

**Why is this needed**
For example in [Minikube quickstart](https://kubernetes.io/docs/setup/minikube/#quickstart) I see several consecutive code blocks. It’s difficult to visually tell which one is output at first glance. Currently it’s like

> ```shell
> minikube start
> ```
> ```
> Starting local Kubernetes cluster...
> Running pre-create checks...
> Creating machine...
> Starting local Kubernetes cluster...
> ```
> ```shell
> kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
> ```
> ```
> deployment.apps/hello-minikube created
> ```
> 
> ```shell
> kubectl expose deployment hello-minikube --type=NodePort
> ```
> ```
> service/hello-minikube exposed
> ```

We have rectangles around code blocks in GitHub, but not in the documentation site, so it got worse there.

**Comments**
A better way to present this is like the “Shell Session” section of [Highlight.js demo page](https://highlightjs.org/static/demo/). Screenshot:

![image](https://user-images.githubusercontent.com/3153452/57795997-51172280-7715-11e9-8eec-c7d68f656eca.png)

This is only one solution. The ultimate idea is to separate command and output. Another possible solution is [command-line plugin of Prism.js](https://prismjs.com/plugins/command-line/) but I have no idea how to properly Markdown it.

**Comment by rajeshdeshpande02** [comment]
@FranklinYu  Thanks for your valuable suggestions and reporting this issue. Here https://kubernetes.io/docs/contribute/style/style-guide/#separate-commands-from-output are well defined style guidelines which makes it easy to separate command from its output. Now i have corrected those steps using PR #14355 and tried to follow set guidelines.

**Comment by FranklinYu** [comment]
Closed in favor of #14355.
