### ISSUE TITLE
Improvement for k8s.io/docs/reference/setup-tools/kubeadm/kubeadm/

### ISSUE THREAD

**Issue by adic26** [kubernetes/website#14337]
No instructions or link on how to install Kubeadm for newbies

**Comment by sftim** [comment]
Thanks for the suggestion @adic26

/kind feature
/language en

**Comment by neolit123** [comment]
PRs welcome to link from that page to: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
thanks

/sig cluster-lifecycle
