### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by alanghartJC** [kubernetes/website#14344]
**This is a Bug Report**

**Problem:**
Formatting of example-ingress.yaml is messed up
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource

**Comment by ariebrainware** [comment]
Which page?

**Comment by alanghartJC** [comment]
Woops, fixed my comment

**Comment by thecrudge** [comment]
PR 14449

Issue is not with the formatting, but the apiVersion

**Comment by thecrudge** [comment]
/close 

resolved
