### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by jbindinga-nice** [kubernetes/website#14349]
**This is a Bug Report**

**Problem:**
The terminal in the Interactive Tutorial is not responding, error:

> The content owner's account has reached capacity. Please try again in 10 minutes

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by abuango** [comment]
This probably was a one time error with katacoda, I tried to reproduce the error but couldn't.  Are you still experiencing the error?

**Comment by BenHall** [comment]
Sorry you encountered a capacity error. We've added more capacity so hopefully users won't encounter this. If users do, then capacity normally comes available again within 5 minutes.

We feel this issue can now be closed.

**Comment by jbindinga-nice** [comment]
Thanks for checking, all is working fine now.
