### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/replicaset/

### ISSUE THREAD

**Issue by xtayfjpk** [kubernetes/website#14342]
**This is a Bug Report**

**Problem:**
Rolling update section is missing.
**Proposed Solution:**
Add rolling update section.
**Page to Update:**
https://kubernetes.io/...
https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

v1.14

**Comment by sethmccombs** [comment]
PR - #14462, there's a couple options to fix this.

**Comment by sftim** [comment]
Looks like signposting readers to Deployment is enough to explain how to get rolling updates.

/language en
/close
