### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/overview/

### ISSUE THREAD

**Issue by c5253458** [kubernetes/website#14352]
Unclear which of LOCAL_PORT and REMOTE_PORT is pod-port.

**Comment by rajeshdeshpande02** [comment]
REMOTE_PORT is pod port. i will update document to remove ambiguity

**Comment by sftim** [comment]
@rajeshdeshpande02 did you get time to work on this?

**Comment by c5253458** [comment]
Are you serious ?

If such a trivial change swamps your development processes, you should change these !

It is a change of ONE WORD  !

The discussion along here, took effort, as well as the trials or even errors countless users of kubectl port-forward encounter, because of the unprecise documentation.

Kind regards

**Comment by c5253458** [comment]
Correct lines are:
In https://kubernetes.io/docs/reference/kubectl/overview/index.html:
port-forward | kubectl port-forward POD [LOCAL_PORT:]POD_PORT [...[LOCAL_PORT_N:]POD_PORT_N] [flags] | Forward one or more local ports to a pod.
-- | -- | --

In help text (kubectl port-forward -h):
  kubectl port-forward TYPE/NAME [options] [LOCAL_PORT:]POD_PORT
[...[LOCAL_PORT_N:]POD_PORT_N]
