### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

### ISSUE THREAD

**Issue by c5253458** [kubernetes/website#14351]
Direction of port forwarding is unclear, because 6379 is used as port of pod and port of host-interface.

**Comment by rajeshdeshpande02** [comment]
@c5253458  I am agree with you on this . First time reader will get confused with same local and pod port number. I will fix this to have different port number so that people will understand concept easily.  Thanks for this issue.

**Comment by sftim** [comment]
Port 6379 is the port that Redis normally uses

I'm not sure there is anything that needs fixing.

**Comment by c5253458** [comment]
> Port 6379 is the port that Redis normally uses

The proposed change of documentation is not about default behaviour (which might change),
but on how to define well defined port forwarding.
