### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/kubernetes-api/

### ISSUE THREAD

**Issue by rk186009** [kubernetes/website#14376]
Most of this discussion (changes, groups & versioning) is advanced, not required for a conceptual / basic understanding. It can be moved elsewhere.

**Comment by sftim** [comment]
That seems like a good suggestion @rk186009 
/language en

**Comment by sftim** [comment]
I'd leave at least a few sentences about API Groups in this page. A lot of the more detailed stuff could move into the reference section.
