### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/labels/

### ISSUE THREAD

**Issue by rk186009** [kubernetes/website#14377]
I am new to Kubernetes and this is my impression upon reading the first few pages of documentation:

We are teaching the entire grammar in one go - what are nouns, adjectives, adverbs, proverbs; what are the rules of constructing complex sentences, and so on. A child needs to learn the basics first - mama, dada, give me, come here, etc. We need to have a 'Getting Started' chapter with the basics - what is Kubernetes, its components (no more than one sentence per component), basic objects (pods, deployments, etc.), basic control structures/mechanisms etc. This 'Getting Started' should be just enough to let a newbie build a small project in Kubernetes.

**Comment by rajeshdeshpande02** [comment]
@rk186009 Thanks for raising your doubt. From your description i understood that you are looking to build small application in k8s as newbie. These things are documented here https://kubernetes.io/docs/tutorials/.
And the concept section which you are referring to follow some logic sequence which starts from its basics. The basic things which you are suggesting is not really basic things (example deployment,controllers etc) but these are advanced topics which is covered in subsequent steps.

**Comment by rk186009** [comment]
@rajeshdeshpande02 - Thanks. The tutorial 'Learn Kubernetes Basics' https://kubernetes.io/docs/tutorials/kubernetes-basics has what I need.
