### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dns-pod-service/ - cluster.local

### ISSUE THREAD

**Issue by cdjohnson** [kubernetes/website#14386]
**This is a Bug Report**

**Problem:**
There are several examples that use the `cluster.local` zone as though it's not a configurable zone.  In reality, it's overridable using the `--cluster-domain` kubelet parameter.  This creates problems for application developers when they try to write portable applications that use the DNS for Service name resolution since they will incorrectly assume that `cluster.local` is always the local cluster zone.

**Proposed Solution:**
Change all occurrences that are not examples:
from:
`cluster.local` 
to 
`my-cluster-domain`.

For example: 
“Normal” (not headless) Services are assigned a DNS A record for a name of the form my-svc.my-namespace.svc.my-cluster-domain. This resolves to the cluster IP of the Service.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by sftim** [comment]
I like that idea @cdjohnson, thanks for the suggestion!

Marking this
/help
(because this seems like a well-defined and approachable task)

**Comment by sftim** [comment]
Depending on space, I'd be tempted to use `cluster-domain.example` rather than `my-cluster-domain`, so that it's clear you can have a dot in it.

**Comment by tddorgtfo** [comment]
fixed #14386

**Comment by cdjohnson** [comment]
Reviewed.  Looks good.
/close
