### ISSUE TITLE
Issues with ScheduledJob docs

### ISSUE THREAD

**Issue by soltysh** [kubernetes/website#1439]
Moved from [here](https://github.com/kubernetes/kubernetes/pull/11980#issuecomment-253026648), which was originally issued by @wernight:

Looks like documentation on http://kubernetes.io/docs/user-guide/jobs/#future-work didn't get updated (still pointing here). Should probably contain some of http://kubernetes.io/docs/user-guide/scheduled-jobs/

Also the reference documentation seems outdated http://kubernetes.io/docs/api-reference/batch/v1/definitions/

Last, but not least, the example on http://kubernetes.io/docs/user-guide/scheduled-jobs/#writing-a-scheduled-job-spec uses two non-standard notations: `?` and `0/1` (not `*/1`) which are not explained.

**Comment by wernight** [comment]
My last point I saw from the source code that it supports standard crontab spec like: `*/5` or `1-5/3`. The `?` seems to be equivalent to `*` in our implementation. `0/1` is actually valid, just weird compared to `*/1` or simply `*`.

**Comment by soltysh** [comment]
Personally, I prefer `*/1` and that's covered on [wiki](https://en.wikipedia.org/wiki/Cron#Non-Standard_Characters) so I'll fix that. As for `?` (question mark) that is a standard replacement for `*` (asterisk) on some fields, see [here](https://en.wikipedia.org/wiki/Cron#CRON_expression).

**Comment by soltysh** [comment]
I've submitted #1506 to address the problems with jobs.md and scheduled-jobs.md files. The api-reference part requires changes in k8s 1.4 release and then update in the docs. I'll try o handle that separately.

**Comment by wernight** [comment]
On Wikipedia the ? is said to have two possible meanings:

- replaces * (which IMO is a bag design)
- gets replaced by crond start time timestamp of that field.

That's why I say it could be clarified about its meaning.

Le mer. 19 oct. 2016 à 10:52, Maciej Szulik <notifications@github.com> a
écrit :

**Comment by soltysh** [comment]
I see your point now, I must have missed the latter part of that sentence. Anyway, thanks I'll update my PR accordingly. In our case `?` means `*` basically, just [checked in the library code we use](https://github.com/kubernetes/kubernetes/blob/c07c73efbb741b3c3e9064556188d64bea59fea8/vendor/github.com/robfig/cron/parser.go#L145).

**Comment by tengqm** [comment]
Closing this ancient issue.
