### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by chiplux** [kubernetes/website#14399]
**This is a Bug Report**

**Problem:**
katacoda problem cannot access minikube dashboard via browser port 30000 "error 502 bad gateway"
**Proposed Solution:**
fixing Katacoda port connection
**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by sftim** [comment]
I can replicate this.

Once you get as far as:

> Run the following command:
> ```shell
> minikube service hello-node
> ```
>
> Katacoda environment only: Click the plus sign, and then click _Select port to view on Host 1_.

then you get a new window / tab opening that shows a Bad Gateway error, and you don't get as far as
> Katacoda environment only: Type 30369 (see port opposite to 8080 in services output), and then click
> This opens up a browser window that serves your app and shows the “Hello World” message.

If you instead choose _View HTTP port 80 on Host 1_, that opens OK, and you can change the port to match what the Service is using. So, there's a bug.

/kind bug
/language en

**Comment by BenHall** [comment]
@chiplux Thanks for letting us know. We fixed the issue shortly after you raised the ticket and we have also added a direct link to the dashboard to make it easier for people.

If you continue to have problems please let us know otherwise we believe this issue can be closed.
