### ISSUE TITLE
Vendor links for Cloud Controller Manager are brokend

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/website#14406]
**This is a Bug Report**

**Problem:**
The links to aws, gce, and azure cloud controller implementations in https://kubernetes.io/docs/concepts/architecture/cloud-controller/#vendor-implementations are broken

**Proposed Solution:**
Update the doc to point to the correct links

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/cloud-controller/#vendor-implementations

**Comment by sethmccombs** [comment]
Hey @juandiegopalomino those links work for me

AWS points to https://github.com/kubernetes/cloud-provider-aws
GCP to https://github.com/kubernetes/cloud-provider-gcp
Azure to https://github.com/kubernetes/cloud-provider-azure

Are you still seeing issues?

**Comment by ialidzhikov** [comment]
I think it is fixed with #14400.
I also proposed #15205 for release-1.13 and #15206 for release-1.12. Once they are merge, we can close the issue.

**Comment by juandiegopalomino** [comment]
It's fixed, thank you!
