### ISSUE TITLE
Update the Kubernetes Components page

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/website#14407]
**This is a Feature Request**

Following sig-docs tasks to revamp the concept documentation, there's some work to be done for the components page: https://kubernetes.io/docs/concepts/overview/components/

**What would you like to be added**

* Make sure to follow the style guide: https://kubernetes.io/docs/contribute/style/style-guide/ (there's a couple of place missing capitalization) 
* cloud controller is in alpha, and it seems to me a bit confusing to have the same controllers 
* There are some subjects that don't have links for their in-depth documentation (e.g. kubelet) which might be useful
* The metrics and logging examples of the cluster add-ons feels a bit misleading as you can have several such systems running in the same cluster simultaneously (although there can also be cluster level setup w/ logging agents, etc...). A clarification would be useful
* Following clarification on addons, we should write a sentence or two about how addons are trying to be accomplished via operators:

> @J.D. Palomino Those docs appear to describe the value of addons and point to specific applications for users to understand.
This effort is not changing what we're installing, just how we're installing and managing them.
If we update docs at this time, we should make clear we are still experimenting and validating the CRD/operator approach is desirable and maintainable.
-- cluster-addons slack channel May 16, 2019

**Why is this needed**

Err... the better documentation goals?

**Comments**

**Comment by sftim** [comment]
I've [started out](https://github.com/kubernetes/website/issues/4135#issuecomment-495938831) a sketch of some changes that will touch on this.
