### ISSUE TITLE
Add a new concepts page for Operators

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/website#14409]
**This is a Feature Request**

I know Operators are considered still in the experimental stage by many, but they have grown to be a significant portion of the community and are the de facto form of deploying important resources (such as prometheus metrics). Till now, however, there's no official page in the documentation for operators (most references to them are to the coreos docs), which makes the kubernetes docs feel incomplete.

**What would you like to be added**

A page under the https://kubernetes.io/docs/concepts/extend-kubernetes/ dedicated to operators. Perhaps describe their purpose, the framework, some examples, etc...

**Why is this needed**

Operators are too significant to not be mentioned with some detail

**Comments**

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/extend-kubernetes/extend-cluster/#combining-new-apis-with-automation describes Operators very briefly. I agree that the concept is useful enough to merit its own page.

**Comment by sftim** [comment]
Done in #14458
/close
