### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/cloud-controller/

### ISSUE THREAD

**Issue by SakirSoft** [kubernetes/website#14404]
**This is a Bug Report**

**Problem:**
In both diagrams the term "Kubernetes Minions" is used but the term "node" should be used.

**Proposed Solution:**
Use the term "node" instead of "Kubernetes Minions" 

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/cloud-controller/

**Comment by jonasrosland** [comment]
Here are the files that needs to be updated:
https://github.com/kubernetes/website/blob/master/static/images/docs/pre-ccm-arch.png
https://github.com/kubernetes/website/blob/master/static/images/docs/post-ccm-arch.png

**Comment by sftim** [comment]
Good spot @SahinVardar 
/kind cleanup
/language en

**Comment by blueelvis** [comment]
@sftim - I was not able to locate the SVG files. Is there a separate folder which contains the SVG files or visio files for these diagrams?

**Comment by sftim** [comment]
It's possible the vector source images are missing.
Maybe `git annotate` would show who the original committer was, and they might have vector artwork.

**Comment by professor** [comment]
I found the original commit. I asked the authors if they still had the original graphic file: https://github.com/kubernetes/website/commit/f084d11d3289f3e9d55025e5cbcdab447303ef69
