### ISSUE TITLE
Working with Kubernetes Objects -- Namespaces update

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/website#14410]
**This is a Feature Request**
The namespaces docs under the Working with Kubernetes Objects section, https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ needs updates.

**What would you like to be added**

The documentation makes no mention of the rbac capabilities possible via namespaces. As the rbac manipulations are strongly tied to namespace scoping (normally they're either cluster or namespaced-scoped), the documentation of namespaces should make mention of it (although an in-depth explanation should still be in a separate document, like https://kubernetes.io/docs/reference/access-authn-authz/rbac/).

On a smaller note, showing the `-n` flag of kubectl to scope commands to namespaces might be good in the same document.

**Why is this needed**

Just more updates to the concepts documentation, as requested.

**Comments**

**Comment by sftim** [comment]
This would be a good issue for a newish contributor to pick up
/help
