### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by Gyeah11** [kubernetes/website#14428]
**Problem:**

They code that is shown in website from page : 
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/config/redis-pod.yaml

Is different if I type the below commands from tutorial : 

curl -OL **https://k8s.io/examples/pods/config/redis-pod.yaml**
cat <<EOF >>./kustomization.yaml
resources:
- redis-pod.yaml
EOF

Actually the problem is that content of the file at URL on https://k8s.io/.... is buggy , fails because "image: kubernetes/redis:v1" does not exist .

**Proposed Solution:**

Modify the curl command as below in order to get the correct yaml file.

curl -OL https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/config/redis-pod.yaml

**Page to Update:**
https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/

 N/A

If you need additional information I can be contacted at lucianstan1900@gmail.com .
Thanks

**Comment by sethmccombs** [comment]
PR - https://github.com/kubernetes/website/pull/14448

**Comment by thecrudge** [comment]
/close

This issue is fixed with the above PR
