### ISSUE TITLE
Update Labels/Selectors and Annotations docs

### ISSUE THREAD

**Issue by juandiegopalomino** [kubernetes/website#14433]
**This is a Feature Request**

The "Labels and Selectors" and "Annotation" concept docs, https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ and https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/ need some updates

**What would you like to be added**

They should include some pod yamls demonstrating how these fields look like in a regular manifest (currently only show json examples w/o the full object description), as the users would greatly benefit from a simple example.

**Why is this needed**

Part of the concept documentation updates that were requested.

**Comments**

**Comment by rajeshdeshpande02** [comment]
@juandiegopalomino Thanks for raising this issue. I am agree with you on this. We should have label and annotation examples documented on these pages to show how it looks like in YAML. I will work on this to add examples on both the pages. Please let me know if anyone has different thoughts on this.

**Comment by sftim** [comment]
Looks like this has been addressed via #14439
/close

(but reopen it by all means if I am wrong about it being fixed)
