### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by anik-chakravorty** [kubernetes/website#14436]
**This is a Bug Report**

Was trying to run the tutorial : https://kubernetes.io/docs/tutorials/hello-minikube/
The tutorial is a part of the coursera course: https://www.coursera.org/learn/deploy-micro-kube-ibm-cloud/home/welcome
While trying to run the aforementioned tutorial faced the following error while trying to execute "minikube dashboard":

$ minikube dashboard

-   Enabling dashboard ...
-   Verifying dashboard health ...
-   Launching proxy ...
-   Verifying proxy health ...
-   Opening http://127.0.0.1:45602/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
X   failed to open browser: exec: "xdg-open": executable file not found in $PATH

Please suggest a way forward. I am trying this on MacBook Pro with High Sierra and chrome is set as the default browser.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

complete log:
$
$ minikube version; minikube start
minikube version: v0.34.1
o   minikube v0.34.1 on linux (amd64)
>   Configuring local host environment ...
>   Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 172.17.0.80
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.13.3
@   Downloading kubelet v1.13.3
-   Pulling images required by Kubernetes v1.13.3 ...
-   Launching Kubernetes v1.13.3 using kubeadm ...
-   Configuring cluster permissions ...
-   Verifying component health .....
+   kubectl is now configured to use "minikube"
=   Done! Thank you for using minikube!
$ minikube dashboard
-   Enabling dashboard ...
-   Verifying dashboard health ...
-   Launching proxy ...
-   Verifying proxy health ...
-   Opening http://127.0.0.1:45602/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
X   failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Comment by prankul88** [comment]
Thanks for reporting this bug.
But seems like it has been addressed in patch https://github.com/kubernetes/website/pull/14240

**Comment by sftim** [comment]
PR #14240 recommends running `apt install xdg-utils`; that seems specific to readers running Debian and its derivatives.

https://github.com/kubernetes/minikube/issues/3558#issuecomment-455859436 has a suggestion about getting the URL out of `minikube` instead of having it open a browser. Maybe that would work?

**Comment by sftim** [comment]
It seems that overall this is more a bug about using Minikube on macOS and less a bug in the Kubernetes documentation. @anik-chakravorty what do you think?

**Comment by tengqm** [comment]
dup of #12968
