### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by atshakil** [kubernetes/website#14435]
*federation documentation* link in [Failing across availability zones](https://kubernetes.io/docs/concepts/services-networking/ingress/#failing-across-availability-zones) section still refers to the deprecated `Federation v1` documentation.

**Suggested improvement**: Update *federation documentation* link to [v2](https://github.com/kubernetes-sigs/federation-v2).

**Comment by sethmccombs** [comment]
I'd love to work on this unless someone else has picked it up?

**Comment by thecrudge** [comment]
@sethmccombs That would be really helpful thanks. There is a remediation project underway to get rid of the deprecated Federation v1 documentation. You can actually just remove the v1 docs.

**Comment by sftim** [comment]
The old docs are deprecated and should go away

/priority important-longterm
/kind feature

**Comment by tengqm** [comment]
/remove-lifecycle stale

I believe there are still some work to do for this.
