### ISSUE TITLE
Translate concepts/architecture/nodes.md into Japanese

### ISSUE THREAD

**Issue by hasebe** [kubernetes/website#14444]
**This is a...**
- [x] Feature Request
- [ ] Bug Report

**Problem:**
No `concepts/architecture/nodes.md` in Japanese.

**Proposed Solution:**
Copy a file from en contents to `concepts/architecture/nodes.md` and translate it into Japanese.

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/architecture/nodes/

**Comment by inductor** [comment]
@cstoku I will work on it based on 1.15 branch. Is that ok?

**Comment by hasebe** [comment]
@cstoku @inductor My apologies for not updating this issue for a long time. Yes, please take this.
