### ISSUE TITLE
Translate concepts/architecture/master-node-communication.md into Japanese

### ISSUE THREAD

**Issue by hasebe** [kubernetes/website#14445]
**This is a...**
- [x] Feature Request
- [ ] Bug Report

**Problem:**
No `concepts/architecture/master-node-communication.md` in Japanese.

**Proposed Solution:**
Copy a file from en contents to `content/ja/docs/concepts/architecture/master-node-communication.md` and translate it into Japanese.

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/architecture/master-node-communication/

**Comment by inductor** [comment]
on 1.15 milestone @cstoku

**Comment by nasa9084** [comment]
merged #15638, close
