### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by vsadikov** [kubernetes/website#14450]
**This is a Bug Report**

The content owner's account has reached capacity.

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It looks like this is working (at least right now).

**Comment by abuango** [comment]
It was also reported at https://github.com/kubernetes/website/issues/14349

**Comment by BenHall** [comment]
Sorry you encountered a capacity error. We've added more capacity so hopefully users won't encounter this. If users do, then capacity normally comes available again within 5 minutes.

We feel this issue can now be closed.
