### ISSUE TITLE
Issue in k8s.io/docs/tasks/administer-cluster/dns-custom-nameservers/

### ISSUE THREAD

**Issue by prankul88** [kubernetes/website#14454]
**This is a Bug Report**

**Problem:** "Customizing DNS Service" page have link to "Configuring CoreDNS"  (https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#config-coredns). But the page doesnot have any section config-coredns

**Proposed Solution:** The link must be updated to [https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options](url)

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

**Comment by sftim** [comment]
/close
Fixed in #14455
