### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-kubernetes-objects/declarative-config/

### ISSUE THREAD

**Issue by Steven0351** [kubernetes/website#14453]
**This is a Bug Report**

**Problem:**
The [Kubernetes Object Management](https://kubernetes.io/docs/concepts/overview/object-management-kubectl/overview/) hyperlink under the [Trade-offs](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#trade-offs) section returns a 404
**Proposed Solution:**
Fix the link or remove the reference to it
**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#trade-offs

**Comment by Steven0351** [comment]
I perused the source and this looks like the likely candidate: https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/#imperative-object-configuration

If this is a low priority I can probably make the updates and open a PR

**Comment by prankul88** [comment]
@Steven0351 Sure you can open a PR for this.

**Comment by Steven0351** [comment]
Addressed by #14481
