### ISSUE TITLE
You shouldn't disable SELinux

### ISSUE THREAD

**Issue by rmetzler** [kubernetes/website#14457]
**This is a Feature Request**

**What would you like to be added**

**current state**

The docs tell the admin to disable SELinux / set it into permissive mode.

E.g this example from the kubeadm installation.
```
# Set SELinux in permissive mode (effectively disabling it)
setenforce 0
sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
```

**what I would like to see**

I'm not an SELinux Expert, but I recognized the OpenShift Installer just enables the `container_manage_cgroup` and that's it.

https://github.com/openshift/openshift-ansible/blob/f80916276cbe932c8155c2ac084b68dc7225cb44/roles/openshift_node/tasks/config.yml#L18-L22

**Why is this needed**

I think that's a much better approach to security than the current state.

**Comment by sftim** [comment]
Looks like the bit that needs fixing is https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl - the tab for “CentOS, RHEL, or Fedora”

Currently there's an aside:
> Setting SELinux in permissive mode by running setenforce 0 and sed ... effectively disables it. This is  required to allow containers to access the host filesystem, which is needed by pod networks for example. You have to do this until SELinux support is improved in the kubelet.

Maybe that's true. I haven't yet looked for an [issue against kubelet](https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+label%3Aarea%2Fkubelet) that would track that.

**Comment by neolit123** [comment]
@rmetzler 
a PR with a better solution is welcome but until then this is the only reliable solution that we know of.
original PR (has linked bug reports):
https://github.com/kubernetes/website/pull/10150

file that has to be changed:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/independent/install-kubeadm.md

/sig cluster-lifecycle
/help

cc @rosti

**Comment by VanagaS** [comment]
Needed for hardening server profiles.

/remove-lifecycle stale

**Comment by jfcgaspar** [comment]
Anyone tried running kubernetes by enabling seboolean container_manage_cgroup yet with good results ?
What's preventing the documentation from being updated to just enable this selinux boolean rather than disabling selinux alltogether ?

/remove-lifecycle stale

**Comment by neolit123** [comment]
@jfcgaspar i don't think `container_manage_cgroup` is sufficient.
see https://github.com/kubernetes/kubeadm/issues/279

security contexts on Linux are a mess and i don't think we have the capacity to handle all that in the kubeadm docs.

instead of saying:
> Set SELinux in permissive mode (effectively disabling it)

we can add a note for users that know what they are doing to not disable it but to be aware that it might require a set of changes that kubeadm does not provide support for..

**Comment by neolit123** [comment]
given this note here merged https://github.com/kubernetes/website/pull/20503/files

> You can leave SELinux enabled if you know how to configure it but it may require settings that are not supported by kubeadm.

i'm going to go ahead and close this ticket.

thanks
/close
