### ISSUE TITLE
Pick the Right Solution page is missing? Removed? 

### ISSUE THREAD

**Issue by sethmccombs** [kubernetes/website#14466]
**This is a Bug Report**
**Problem:**
The link from "Cluster Administration Overview" to " Picking the Right Solution" is a 404. 
`docs/setup/pick-right-solution/` does not exist, searching the repo seems like it's referenced in a few places. 

It was removed by #14442  

**Proposed Solution:**
Update the stale links to point to Setup page

**Page to Update:**
https://kubernetes.io/docs/setup/pick-right-solution

**Comment by sethmccombs** [comment]
For example - this page - https://kubernetes.io/docs/concepts/cluster-administration/cluster-administration-overview/#planning-a-cluster is pointing to that link (pick-right-solution) but it doesn't exist.

**Comment by sethmccombs** [comment]
```
grep -rnw '.' -e 'pick-right-solution' | wc -l
      56
```
Looks like roughly 50 places are referencing it. Unless I'm missing something.

**Comment by sethmccombs** [comment]
I'll start working on this

**Comment by Rajakavitha1** [comment]
> ```
> grep -rnw '.' -e 'pick-right-solution' | wc -l
>       56
> ```
> 
> Looks like roughly 50 places are referencing it. Unless I'm missing something.

Here are the list of pages where there are references to pick-right-solution)

content\en\docs\concepts\cluster-administration\cluster-administration-overview.md
content\en\docs\tasks\federation\administer-federation\cluster.md
content\en\docs\tasks\federation\administer-federation\configmap.md
content\en\docs\tasks\federation\administer-federation\daemonset.md
content\en\docs\tasks\federation\administer-federation\deployment.md
content\en\docs\tasks\federation\administer-federation\namespaces.md
content\en\docs\tutorials\stateful-application\cassandra.md

**Comment by sethmccombs** [comment]
No worries @Rajakavitha1! PR is in!

**Comment by sftim** [comment]
Related issues for other localizations:
- #14473 
- #14474 
- #14475 
- #14476
- #14477 
- #14478
- #14479 
- #14480
