### ISSUE TITLE
Dangling "pick-right-solution" references -  Korean

### ISSUE THREAD

**Issue by sethmccombs** [kubernetes/website#14479]
This is a Bug Report
Problem:

The link from "Cluster Administration Overview" to " Picking the Right Solution" is a 404.
docs/setup/pick-right-solution/ does not exist, as it was removed as a redundant page.

Proposed Solution:
Update the stale links to point to Setup page not the "Picking the Right Solution" page
The references on this page point both too the root of the pick-right-solution page, but also to various IDs that no longer exist, there may be better pages to point those links to.

Page to Update:
https://kubernetes.io/ko/docs/setup/
https://kubernetes.io/ko/docs/tutorials/stateful-application/cassandra/

**Comment by seokho-son** [comment]
Hello, @sethmccombs !
I am one of the reviewers for Korean localization contents.
Thank you for issuing the problem.
In case of Korean localization team, we periodically (2 or 3 weeks) create a working branch and apply translated documents by merging the working branch. 
So, in general, we don't immediately reflect changes in English contents in Master branch to Korean contents in Master branch. 
I think Korean localization team can handle this issue by taking care of outdated files when we change our working branch from dev-1.14-ko.4 (current) to dev-1.14-ko.5 (next).

@gochist 
A merged [PR](https://github.com/kubernetes/website/pull/14442) in the master (English) branch removed "Picking the Right Solution" page.
Do you think this issue can be handled by taking care of outdated files in dev-1.14-ko.5 ?

**Comment by sethmccombs** [comment]
Hey @seokho-son, sounds like this one will get taken care of when you change working branches. The removed page impacted most translations, and I figured the editing the links was a good first issue, so I logged one for all languages, so feel free to take care of this one in any way you see fit!

**Comment by gochist** [comment]
@sethmccombs @seokho-son Thank you! I think this is a good first issue too. Korean l10n team do not use GitHub milestone, however the milestone of this issue will be dev-1.14-ko.5.

**Comment by gochist** [comment]
This issue is included in #15001 and #15029 .
