### ISSUE TITLE
Improvement for k8s.io/docs/concepts/containers/images/

### ISSUE THREAD

**Issue by eshicks4** [kubernetes/website#14470]
Need a imagePullPolicy option that attempts to pull 1st but, if unsuccessful, resorts to an existing image if one is found.  This would be 1 more thing you could add to high importance containers that just can't afford to be down.

**Comment by sftim** [comment]
@eshicks4 It sounds like you want to request an improvement to Kubernetes? If I've understood right, it's not that the feature you want exists but with little documentation, it's that Kubernetes itself doesn't yet behave how you'd like.

If that's right, you can [log an issue against Kubernetes](https://github.com/kubernetes/kubernetes/issues/new/choose); if you do, it would be useful for you to update this issue as well so it's clear where things stand.

/triage information-needed
