### ISSUE TITLE
Dangling "pick-right-solution" references - Italian

### ISSUE THREAD

**Issue by sethmccombs** [kubernetes/website#14477]
This is a Bug Report
Problem:

The link from "Cluster Administration Overview" to " Picking the Right Solution" is a 404.
docs/setup/pick-right-solution/ does not exist, as it was removed as a redundant page.

Proposed Solution:
Update the stale links to point to Setup page not the "Picking the Right Solution" page
The references on this page point both too the root of the pick-right-solution page, but also to various IDs that no longer exist, there may be better pages to point those links to.

Page to Update:
https://kubernetes.io/it/docs/concepts/cluster-administration/cluster-administration-overview/

**Comment by medmedchiheb** [comment]
Can i take this issue, as i am looking for an issue to make my first PR.

**Comment by sethmccombs** [comment]
Hey @medmedchiheb! It doesn't look like anyone has taken it! Feel free to submit a PR

**Comment by medmedchiheb** [comment]
Yes @sethmccombs , i need some help. do we need to change the title of the link 'Scelta della soluzione giusta` and also withing language/it there are no setup section.
