### ISSUE TITLE
Broken image top right of /docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14484]
**This is a Bug Report**

**Problem:** There's an image shown top-right in the kubeadm docs, and that image is missing.
The missing image's URI is https://raw.githubusercontent.com/cncf/artwork/master/kubernetes/certified-kubernetes/versionless/color/certified-kubernetes-color.png

**Proposed Solution:** Diagnose and fix

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

Kubernetes Docs Version: v1.14

https://kubernetes.io/docs/setup/independent/install-kubeadm/ is also affected

/language en

**Comment by SupriyaSirbi** [comment]
I have created the PR for the same.
Thanks for the issue

**Comment by palnabarun** [comment]
@sftim Are you talking about the `Certified Kubernetes Image`?

I am able to see them in both the aforementioned pages.

https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
![image](https://user-images.githubusercontent.com/10010419/58530355-14125c00-81fc-11e9-8c17-3904ba496373.png)

https://kubernetes.io/docs/setup/independent/install-kubeadm/
![image](https://user-images.githubusercontent.com/10010419/58530389-33a98480-81fc-11e9-844b-68cecce4d45e.png)

**Comment by sftim** [comment]
Fixed via #14511
