### ISSUE TITLE
Add HTTP Redirect for "pick-right-solution"

### ISSUE THREAD

**Issue by lisa** [kubernetes/website#14509]
**This is a Feature Request**

**What would you like to be added**
Add a redirect from the old "pick-right-solution" URI to the page which has replaced it.

**Why is this needed**

With #14442, the "pick-right-solution" page was replaced by the "setup page." Several places on the web link directly to `/docs/setup/pick-right-solution` (and their translated equivalents), and those links are now broken with an unhelpful 404 page. Providing the redirect will provide a better user experience, especially for those new to Kubernetes, who would otherwise encounter an unfavourable user experience.

**Comments**

**Comment by zhangqx2010** [comment]
fixed by #14468
/close
