### ISSUE TITLE
Document Pod eviction

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14507]
**This is a Feature Request**

**What would you like to be added**
Describe the concept of eviction:
- what this means in Kubernetes terminology
- API objects used to trigger an eviction (link to the reference docs?)
- document that eviction can be requested manually or it can be triggered by a controller.
  - mention some of the ways that automated eviction can happen

**Why is this needed**
I wanted to link to the documentation for eviction, only I couldn't really find a place to link to.

**Comments**
It's relevant to #4322 as well.

**Comment by sftim** [comment]
I still want this
/remove-lifecycle rotten

**Comment by sftim** [comment]
Also see #20728 

/remove-lifecycle stale

**Comment by kbhawkey** [comment]
Leave open or close?

**Comment by sftim** [comment]
I'd definitely keep https://github.com/kubernetes/website/issues/20728

It does still seem useful to document the concept of eviction. @kbhawkey what do you think?

**Comment by kbhawkey** [comment]
:+1: 
/remove-lifecycle stale

**Comment by tengqm** [comment]
/remove-lifecycle rotten

We do need some docs about the eviction feature and its API. There are some API specifics that needs attention.

**Comment by tomkivlin** [comment]
I will prepare a PR. Current thinking of structure is along the lines of:

```
Explanation of what eviction means (or should this go in the Glossary?)

Section on automated eviction, the mechanisms that drive / effect this (e.g. PDB, pre-emption, QoS, resource starvation, etc.), and links to relevant APIs etc.

Section on manual eviction, the mechanisms that drive this (e.g. drain, cordon, etc.), and links to relevant APIs etc.
```

**Comment by sftim** [comment]
If you want, you can write a glossary entry and then use the `glossary_definition` shortcode to include the same text at a suitable point in a longer page.

**Comment by tomkivlin** [comment]
Thanks @sftim I'll give that a go, looks good.

**Comment by sftim** [comment]
/close

Done in #27739
