### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by cabiad** [kubernetes/website#14516]
It would have helped me if these docs could reconcile with the installation instructions found at https://kubernetes.github.io/ingress-nginx/deploy/

In particular this page describes the following as a "Mandatory Command" for all deployments:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/mandatory.yaml
```

But these docs do not include this command.

**Comment by prankul88** [comment]
Hi @cabiad, I am not sure if the above command can be made mandatory in docs of this repo.
The above link corresponds to specifically nginx controller which is present in repo https://github.com/kubernetes/ingress-nginx/

**Comment by cabiad** [comment]
Hi @prankul88, thanks for the reply!

The `minikube addons enable ingress` command in the tutorial document referred to by my issue title does seem to specifically install the NGINX Ingress controller, as shown in the screen capture below:

![image](https://user-images.githubusercontent.com/840172/58563694-9a796e80-81f9-11e9-9df0-44ea758115ef.png)

That said, I've done some more investigation since filing this issue and no longer believe that this command needs to be run on Minikube with the ingress add-on enabled. The https://kubernetes.github.io/ingress-nginx/deploy/ document, which suggests that the "Mandatory Command" is necessary with minikube along with enabling the minikube ingress addon, is the one that seems to be incorrect. Closing this issue.
