### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by ejez** [kubernetes/website#14524]
https://kubernetes.io/ is down
(looks like TLS issue)

**Comment by ejez** [comment]
Note: accessing site from some geographical locations is ok, and from other locations shows:
with curl/wget:
`Connection reset by peer`

in firefox:

> Secure Connection Failed
> The connection to kubernetes.io was interrupted while the page was loading.

Was trying with tor browser

**Comment by khacminh** [comment]
I get the same issue in Asia. My partner in the US cannot access also.

**Comment by ejez** [comment]
If someone really needs to access the site now you can use [tor browser](https://github.com/TheTorProject/gettorbrowser), and try with different tor circuits:

![tor](https://user-images.githubusercontent.com/48388358/58369599-58081700-7f05-11e9-9de1-12f441a0d946.png)

**Comment by sftim** [comment]
It'd be great to have details of locations (IP address ranges, perhaps?) from where the site can't be reached.
/triage needs-information

**Comment by khacminh** [comment]
the site was down on Saturday at 11 a.m (UTC) and it was down in about 3 hours. This issue can be closed now.
