### ISSUE TITLE
Translate concepts/workloads/pods/disruptions/ in Japanese

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#14545]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/workloads/pods/disruptions/ in Japanese.  

**Why is this needed**
This document is not translated in Japanese. 
**Comments**

Copy a file from en contents to content/ja/docs/concepts/workloads/pods/disruptions.md and translate it into Japanese.

**Comment by inductor** [comment]
@kakts Are you working on it?
Is it fine if we move the milestone to 1.15-ja.1?

**Comment by kakts** [comment]
@inductor 
I'm now working on it. But it'll take a long time.
So it's okay to move the milestone to 1.15-ja

**Comment by cstoku** [comment]
@kakts こちら着手中でしょうか？

**Comment by kakts** [comment]
@cstoku すいません　こちら着手できていないです。
マイルストーンから除外していただいて構いません

**Comment by cstoku** [comment]
外した上でCloseしてしまっても大丈夫でしょうか？
それとも翻訳予定がありますか？

**Comment by kakts** [comment]
こちら着手未定なので、Closeして問題ありませんm(_ _)m

**Comment by sftim** [comment]
/priority backlog
/kind feature

If this is OK to /close, please feel free.
