### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by miroslav31077** [kubernetes/website#14580]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @miroslav31077 

Thanks for getting in touch.
Can you let us know what bug you found in the page at https://k8s.io/docs/tutorials/hello-minikube/?

/triage needs-information
