### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/taint-and-toleration/

### ISSUE THREAD

**Issue by shrdlu68** [kubernetes/website#14609]
**This is a Bug Report**

**Problem:**
In this section: "Normally, if a taint with effect NoExecute is added to a node, then any pods that do not tolerate the taint will be evicted immediately, and any pods that do tolerate the taint will never be evicted.", I think what is meant is that pods that do not tolerate the taint will never be scheduled.
**Proposed Solution:**
Reword to:
"Normally, if a taint with effect NoExecute is added to a node, then any pods that do not tolerate the taint will be evicted immediately, and any pods that do tolerate the taint will never be scheduled."
**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

**Comment by sftim** [comment]
So it's the last bit of the current wording that's wrong?
> "Normally, if a taint with effect NoExecute is added to a node, then any pods that do not tolerate the taint will be evicted immediately, and any pods that do tolerate the taint will never be **evicted**.

/triage bug
/good-first-issue

**Comment by shrdlu68** [comment]
@sftim Yes.

**Comment by rmarcum** [comment]
@rajeshdeshpande02   Looks like we hit this at the same time.  I'll remove my PR.

**Comment by sftim** [comment]
Just wondering if this still needs fixing?
