### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by agemooij** [kubernetes/website#14615]
**Problem:**
The "Pull an Image from a Private Registry" page does not mention the fact that image pull secrets can be specified through a service account. This has lead many of my colleagues to the conclusion that the only way to use custom image pull credentials is through direct modification of all pods being deployed. 

Searching Google on image pull secrets only brings up this page but almost never brings up the page that contains the relevant documentation, e.g. the page on how to [how to add image pull secrets to a service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account).

**Proposed Solution:**
The "Pull an Image from a Private Registry" page should have an extra section at the bottom of this page that either copies or references the documentation on [how to add image pull secrets to a service account](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account). A simple reference to the possibility and a link to the relevant doc would already help a great deal.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Kubernetes Version:**
All current versions

**Comment by sftim** [comment]
@agemooij - thanks for this suggestion. Sounds like a good idea!

**Comment by sftim** [comment]
Did PR #14669 cover this by providing a helpful link?

**Comment by agemooij** [comment]
@sftim  yes, that's great. Thanks!
