### ISSUE TITLE
Issue with k8s.io/docs/setup/minikube/

### ISSUE THREAD

**Issue by andreleoni** [kubernetes/website#14623]
**Problem:** The link to `Interacting with Your Cluster.` of step 2 of Quickstart of https://kubernetes.io/docs/setup/minikube/ are returning a 404 error.

He sends me to https://kubernetes.io/docs/setup/minikube/docs/setup/minikube/#interacting-with-your-cluster

**Proposed Solution:** Updates this link to a existent location.

**Comment by poothia** [comment]
just adding to above solution.
Updated link: https://kubernetes.io/docs/setup/minikube/#starting-a-cluster
thanks

**Comment by sftim** [comment]
Well defined and relatively easy to fix
/help

**Comment by hpandeycodeit** [comment]
> just adding to above solution.
> Updated link: https://kubernetes.io/docs/setup/minikube/#starting-a-cluster
> thanks

The relative path is wrong here. It shoult point to "Interacting with your Cluster" section on the same page. Check out the PR #14656

**Comment by poothia** [comment]
@hpandeycodeit  on it... let me check.

**Comment by sftim** [comment]
Fixed by #14662
/close
