### ISSUE TITLE
Make “Contributing to the Upstream Kubernetes Code” more discoverable

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14639]
**This is a Feature Request**

:information_source: since this issue was recorded, https://k8s.dev/ came into existence.

**What would you like to be added**
I'd like someone who visits https://kubernetes.io/docs/contribute/ to be able to discover [Contributing to the Upstream Kubernetes Code](https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/) without clicking anywhere on the page (scrolling is allowed!)

**Why is this needed**
I hadn't seen https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/ and only found this when [someone told me](https://kubernetes.slack.com/archives/C1J0BPD2M/p1559229148015900?thread_ts=1559205602.009600&cid=C1J0BPD2M) about the cherry-picking process it describes _and_ I then used Google.

It's much easier to find how to contribute to docs than it is to find the equivalent page about contributing code to Kubernetes.

**Comment by abuango** [comment]
@sftim Can I pick this up? we can change the paragraph introducing the style guide as follows:

> For information on the Kubernetes documentation style guide, see the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/) and you can also learn how to contribute to the to the [Upstream Kubernetes Code here.](https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/)

**Comment by sftim** [comment]
@abuango anyone who's [signed the CLA](https://kubernetes.io/docs/contribute/start/#sign-the-cla) can contribute here! Feel free.

**Comment by sftim** [comment]
I also recommend changing the title for https://kubernetes.io/docs/contribute/

Here's one possible way to make an improvement:
- change the title for https://kubernetes.io/docs/contribute/
- signpost readers for how to contribute to Kubernetes code etc (ie, everything but docs)
- log a new backlog issue to track further cleanup
  - eg restructure the Contribute section to show code, docs, and other contributions in one place. All are valid ways to help.
- close this issue, referencing the new issue

As this feels well-enough defined to merit it, I will mark this
/help
