### ISSUE TITLE
Refactor :Highly Available Topology and Creating Highly Available Clusters topics

### ISSUE THREAD

**Issue by Rajakavitha1** [kubernetes/website#14638]
Refactor :Highly Available Topology and Creating Highly Available Clusters topics

The page: https://kubernetes.io/docs/setup/independent/ha-topology/ gives the concepts/options for Stacked etcd topology and External etcd topology the page https://kubernetes.io/docs/setup/independent/high-availability/ gives details  the steps/task to create a HA cluster with Kubeadm for both the topologies 
 
Proposed Solution:

Refactor the two pages as:
- Highly Available Clusters topology (page that lists the available topology and details about the decision matrix to choose one over the other )
- Creating Highly Available Clusters with kubeadm - Stacked etcd topology (page that provides the how to)
- Creating Highly Available Clusters with kubeadm - External etcd topology (page that provides the how to)

**Why is this needed**
The users interested in creating a HA cluster using Stacked etcd topology need not wade through the information related to  External etcd topology  when creating the HA cluster.

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle 
@Rajakavitha1 i must say that i prefer the current file layout better in terms of maintenance.

the external ETCD page (https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/) does not see a lot of changes during release cycles, while this page https://kubernetes.io/docs/setup/independent/high-availability/
sees more updates because HA is still being developed.

if we have a separate full guide about `External etcd topology` it will possibly duplicate a lot of information from https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by sftim** [comment]
Some thoughts. I'm not particularly familiar with this part of the docs or with `kubeadm` though.

I wonder if the two different options on https://kubernetes.io/docs/setup/independent/ha-topology/ could fit into two tabs.

It looks as if the etcd step on https://kubernetes.io/docs/setup/independent/high-availability/ would work with the stacked / not stack choice as 2 tabs, I'm not sure though.

Maybe if https://kubernetes.io/docs/setup/independent/high-availability/#common-tasks-after-bootstrapping-control-plane was in a separate document and there was a clear link to it, that would make the overall kubeadm page easier to digest?

**Comment by neolit123** [comment]
> I wonder if the two different options on https://kubernetes.io/docs/setup/independent/ha-topology/ could fit into two tabs.

the separate document for the topologies was suggested by SIG docs.

**Comment by Rajakavitha1** [comment]
> > I wonder if the two different options on https://kubernetes.io/docs/setup/independent/ha-topology/ could fit into two tabs.
> 
> the separate document for the topologies was suggested by SIG docs.

Is it worth discussing in SIG docs channel to make the kubeadm page easier to digest? As far as maintenance and reuse of the content we can create a common task and include it in the tasks that require the common steps to eliminate redundancy. Something similar to: {{< include "task-tutorial-prereqs.md" >}} {{< version-check >}} in https://kubernetes.io/docs/contribute/style/page-templates/#task-template

**Comment by fabriziopandini** [comment]
My two cents
With HA getting more and more mature in kubeadm, the steps for stacked etcd/external etcd are getting more and more the same.
In fact as of today the only difference are
- prerequisites (in one case you need an external etcd)
- the content of the kubeadm file (in one case it contains the external etcd section)

Considering this, I'm in favour of preserving a single page with tabs where difference exist

**Comment by Rajakavitha1** [comment]
> My two cents
> With HA getting more and more mature in kubeadm, the steps for stacked etcd/external etcd are getting more and more the same.
> In fact as of today the only difference are
> 
> * prerequisites (in one case you need an external etcd)
> * the content of the kubeadm file (in one case it contains the external etcd section)
> 
> Considering this, I'm in favour of preserving a single page with tabs where difference exist

Yes, that is the plan single page with two tabs.

**Comment by sftim** [comment]
Issue #11536 looks relevant: it talks about ownership of /docs/setup/
