### ISSUE TITLE
Cloud Native Security page discussion continuation

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#14646]
Open issue / tracker for `#sig-docs-security` to continue discussion on https://github.com/kubernetes/website/pull/14495

/cc @sftim @kbhawkey 
/assign @zparnold

**Comment by Rajakavitha1** [comment]
Hi, How about adding the security docs info here:  https://kubernetes.io/docs/user-journeys/users/cluster-operator/intermediate/#section-2?

**Comment by kbhawkey** [comment]
I am not sure where this issue stands. It may be helpful to keep an open issue about improving/increasing the visibility of security related content (container, data, network, ...) in the k8s docs.
