### ISSUE TITLE
Pages using real IPv4 addresses for examples

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14664]
**This is a Bug Report**

**Problem:** Various documentation pages use real IPv4 addresses (that are assigned to real individuals and organizations) in examples

**Proposed Solution:**
Replace those with [documentation IP addresses](https://tools.ietf.org/html/rfc3849) instead; that is, addresses from inside `192.0.2.0/24`

/kind cleanup
/priority backlog

**Comment by icheikhrouhou** [comment]
Can I work on this ?

**Comment by sftim** [comment]
@icheikhrouhou sure - see https://kubernetes.io/docs/contribute/start/#improve-existing-content

**Comment by icheikhrouhou** [comment]
Should I also change 130.211.204.1 ?  in https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/

**Comment by sftim** [comment]
@icheikhrouhou there will be several places where it's worth fixing these things. You could fix them in one bigger pull request or lots of smaller ones.

If you use several PRs that's a little more effort to review but also less likely to need a rebase due to other changes getting merged. I'd probably do one big PR with several commits.

**Comment by icheikhrouhou** [comment]
@sftim Alright then, I'll do one single PR with the all of the changes

**Comment by sftim** [comment]
Think this is done now.
/close

(if I'm wrong, it's OK to reopen the issue)
