### ISSUE TITLE
Issue with k8s.io/zh/docs/tasks/access-application-cluster/create-external-load-balancer/

### ISSUE THREAD

**Issue by zenglian** [kubernetes/website#14660]
**This is a Bug Report**

**Problem:**
`123.45.678.9` is an illegal IP.

**Proposed Solution:**
`123.45.67.89`

**Page to Update:**
https://k8s.io/zh/docs/tasks/access-application-cluster/create-external-load-balancer/

**Comment by sftim** [comment]
Fixed via #14677
/close
