### ISSUE TITLE
Document graceful termination

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14713]
**This is a Feature Request**

**What would you like to be added**
Add a concept-level guide that explain the motivation and effect of graceful termination in Kubernetes.

https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods talks about termination specifically from a Pod perspective, but what about for Endpoints and Services that reference the terminating Pod? The concept of a graceful cleanup covers more than just containers.

**Why is this needed**
Cluster operators want to provide a smooth experience for their end users and to understand the design elements and trade-offs that are involved in delivering that.

**Comments**
A couple of external pages that cover this:
- https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace
- https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/

**Comment by SupriyaSirbi** [comment]
Hello @sftim 

I will work on this issue and submit the PR for the same

**Comment by embano1** [comment]
Perfect timing, there was just a lengthy [debate](https://twitter.com/embano1/status/1155870615590584320?s=20) on Twitter on the subject and I was about to file a PR as well.

Happy to review if @SupriyaSirbi is already working on it.

**Comment by sftim** [comment]
Related: issue #22391

**Comment by sftim** [comment]
I think https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination covers this.
