### ISSUE TITLE
Document storage encryption

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14727]
**This is a Feature Request**

**What would you like to be added**
Explain how to make sure that data stored and used in your cluster are encrypted at rest.

**Why is this needed**
Cluster operators may want to make sure that storage, whether [ephemeral](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage) or [persistent](https://kubernetes.io/docs/concepts/storage/persistent-volumes/), is encrypted at rest.

The current documentation covers ensuring that control plane persistent data (ie, `etcd` for a mainstream Kubernetes cluster) are [encrypted at rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/). This is a good idea but it is not the whole story.

**Comments**
#14725 is kind of similar; it's more narrowly focused on a technology (TLS) ahead of the general concept of encryption in transit.

**Comment by sftim** [comment]
If someone is running Pods on a system with swap enabled, they should also encrypt that swap storage (and the page should explain why).

**Comment by sftim** [comment]
/remove-priority important-longterm
I'll let SIG Security decide on that

**Comment by Aut0R3V** [comment]
@sftim can you explain what you mean by making sure?

**Comment by sftim** [comment]
“Make sure” is like “[ensure](https://en.wiktionary.org/wiki/ensure)”. The cluster operator wants to be confident that the secrets are not stored in the clear.
