### ISSUE TITLE
Explain that Pods provide isolation

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14724]
**This is a Feature Request**

**What would you like to be added**
Change https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/ to emphasize that Pods are, at least in theory, isolated from one another. A Pod in a cluster doesn't have any inherent ability to observe an arbitrary other Pod in the same cluster.

**Why is this needed**

Whilst drafting changes to https://kubernetes.io/docs/concepts/security/overview/ I decided to link to the section of https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/ that explains how Pods provide isolation and that this is useful for information security.

I realized that the page I was reading did not make that point.

**Comments**
Possibly: hint at that in the what-is-kubernetes page and then direct any curious readers to a new page inside https://kubernetes.io/docs/concepts/workloads/pods/ for more details.

**Comment by sftim** [comment]
Might be relevant to #14657

**Comment by bgrant0607** [comment]
Why not link directly to pod documention instead?

**Comment by sftim** [comment]
> hint at that in the what-is-kubernetes page and then direct any curious readers to a new page inside https://kubernetes.io/docs/concepts/workloads/pods/ for more details.

This approach? Also valid.
