### ISSUE TITLE
StorageClass documentation for aws-ebs provisioner incorrectly documents fsType parameter

### ISSUE THREAD

**Issue by dan-j** [kubernetes/website#14722]
**This is a Bug Report**

**Problem:**

The AWS EBS documentation on available `parameters` doesn't document the actual behaviour.

I have been trying to provision a XFS formatted EBS volume from a StorageClass with the parameter `fsType: xfs`.

What actually happens, is the value is ignored and an EXT4 volume is actually provisioned. Verified using `kubectl describe pv <pv-name>` and mounting the disk into an ubuntu pod and running `df -T`

Changing `fsType` to `fstype` and everything works as expected.

**Proposed Solution:**

Identify the correct behaviour. Are the docs wrong, or is the provisioner not following best/common practices? Other provisioners also use `fsType` (although I haven't confirmed whether or not this is correct)

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs

Kubernetes Version: 1.12 eks.2

**Comment by dan-j** [comment]
Reported to AWS are investigating the issue. Will report back any progress

**Comment by Jeffwan** [comment]
This is actually a code problem but not documentation problem. The interface is `fsType` here.
Check here for details. https://github.com/kubernetes/kubernetes/issues/75941
1.12 and 1.13 have been patched.
