### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by Nigel-Vickerstaff** [kubernetes/website#14733]
**This is a Bug Report**

**Problem:**
Running the tutorial on https://kubernetes.io/docs/tutorials/hello-minikube/
encountered the following (three times, pop-up blocker disabled on last attempt):-
Opening http://127.0.0.1:41689/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/in your default browser
failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by palnabarun** [comment]
Duplicate of #12968
