### ISSUE TITLE
Issue with /docs/user-guide/connecting-to-applications-proxy/

### ISSUE THREAD

**Issue by agsola** [kubernetes/website#1473]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This user guide doesn't apply for k8s 1.4

**Proposed Solution:**
Change it.

**Page to Update:**
http://kubernetes.io/docs/user-guide/connecting-to-applications-proxy/

1.4

**Comment by tengqm** [comment]
v1.4 is not maintained any more.
/close
