### ISSUE TITLE
Issue with /docs/user-guide/ui/

### ISSUE THREAD

**Issue by agsola** [kubernetes/website#1474]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This user guide doesn't apply for k8s 1.4

**Proposed Solution:**
Change it.

**Page to Update:**
http://kubernetes.io/docs/user-guide/ui/

**Comment by tengqm** [comment]
Closing. Docs for v1.4 is too old for team to maintain. Fixing and backporting for old versions are carefully screened and managed today.
