### ISSUE TITLE
Adopt official kubeadm logo

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14741]
**This is a Feature Request**

![kubeadm logo](https://user-images.githubusercontent.com/22591623/59856252-74656b00-936e-11e9-8dd9-d6092845981b.png)

**What would you like to be added**
Change https://kubernetes.io/docs/setup/independent/install-kubeadm/ and https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/ to use the [official kubeadm logo](https://github.com/kubernetes/kubeadm/issues/1588).

**Why is this needed**
Glitz and flair
/priority backlog

**Comments**

**Comment by icheikhrouhou** [comment]
I'll work on this once logo is selected.

**Comment by RA489** [comment]
https://github.com/kubernetes/kubeadm/issues/1588

**Comment by sftim** [comment]
Logo is selected, waiting on PR for official artwork.

**Comment by sftim** [comment]
[New logo](https://github.com/cncf/landscape/blob/f140b0292a9a86f4ec0d0be0a1905258ca040c6a/hosted_logos/kubeadm.svg) is available in draft.

**Comment by icheikhrouhou** [comment]
I'll update it once merged to master

**Comment by sftim** [comment]
kubeadm logo now [adopted](https://github.com/kubernetes/kubeadm/pull/1628).

**Comment by sftim** [comment]
Done
/close
