### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod-overview/

### ISSUE THREAD

**Issue by earizon** [kubernetes/website#14746]
**This is a Bug Report**

The phrase "A Pod is the basic building block of Kubernetes" is completely misleading. (API objects are the basic building blocks of k8s)

**Proposed Solution:**
Replace with "A Pod is the basic execution unit of a Kubernetes application "

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/

**Comment by Vageesha17** [comment]
raised a PR #14758 for this issue.
