### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

### ISSUE THREAD

**Issue by snoodleboot** [kubernetes/website#14752]
**This is a Bug Report**

**Problem:**

Misspelling of Elasticsearch as Elasticseach

**Proposed Solution:**

Fix spelling to Elasticsearch

**Page to Update:**
https://kubernetes.io/...

**Comment by SupriyaSirbi** [comment]
Corrected the mistake. Thanks for the issue

**Comment by SupriyaSirbi** [comment]
#14755 Submitted PR for the same

**Comment by sftim** [comment]
Fixed via #14755 
/language en
/close
