### ISSUE TITLE
Document --show-labels

### ISSUE THREAD

**Issue by dpandhi-git** [kubernetes/website#14778]
**What would you like to be added**
Add --show-labels options as part of [kubectl cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/)
Currently documentation has length way to find it out 
`# Show labels for all pods (or any other Kubernetes object that supports labelling) is # Also uses "jq"
for item in $( kubectl get pod --output=name); do printf "Labels for %s\n" "$item" | grep --color -E '[^/]+$' && kubectl get "$item" --output=json | jq -r -S '.metadata.labels | to_entries | .[] | " \(.key)=\(.value)"' 2>/dev/null; printf "\n"; done
`

**Why is this needed**
Quick reference to get to the Kubernetes object labels

**Comment by sftim** [comment]
Maybe remove the long version:
```

**Comment by dpandhi-git** [comment]
Thanks @sftim , have removed the longer version in PR

**Comment by sftim** [comment]
/close
Fixed in #16268
