### ISSUE TITLE
docs/concepts/services-networking/service/ needs overhaul

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/website#14770]
**This is a Feature Request**

**What would you like to be added**

Overhaul https://kubernetes.io/docs/concepts/services-networking/service/. From a high level, I guess it would be great to do:
- Make it really talk about concept. e.g. what does service do, what is its relationship with label/endpoint/pod, what are the service types and other essential API surface, etc.
- Split the kube-proxy implementation details / history to somewhere else.
- Remove the cloud specific tutorials / notes.

**Why is this needed**
The service doc page contains too much unnecessary information. It brings lots of confusion to people who just wants to learn the concept of a kubernete service. The kube-proxy implementation doesn't really matter as they all serve the same service API. It would be more clear to extract those nuances to another place for folks that are willing to dig deeper.

The doc also contains too much cloud provider specific content that really should be served on provider's own place. e.g. how to configure X load balancer feature on Y cloudprovider.

**Comments**

**Comment by sftim** [comment]
Hi @MrHohn 

Is this a duplicate of #3735?

**Comment by MrHohn** [comment]
Hi @sftim, #3735 focuses more about mentioning Ingress from the Service page so folks can get the right direction while this issue cares more about how Service page is constructed in general. So I don't think it is a duplicate.

**Comment by sftim** [comment]
The Service page certainly wants more work done on it.

**Comment by sftim** [comment]
Slightly relevant: #12410 talks about kube-proxy examples.

**Comment by sftim** [comment]
Discussed in SIG Docs weekly meeting.
/priority important-longterm
cc @cody-clark

**Comment by sftim** [comment]
Also relevant to #11382 because the current page is heavy on AWS-specific detail.

**Comment by sftim** [comment]
Also see #18085

**Comment by sftim** [comment]
Also see #19176

**Comment by sftim** [comment]
/reopen
/lifecycle frozen

We still need to do this

**Comment by sftim** [comment]
Closed issue https://github.com/kubernetes/website/issues/9122 is apposite too
/sig network
/triage accepted

**Comment by sftim** [comment]
Also relevant: issue #29107 (about the very first sentence)

**Comment by sftim** [comment]
Also see issue #29827

**Comment by sftim** [comment]
Also relevant: #32243

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/pull/38542

**Comment by sftim** [comment]
This is mostly Done. We can open smaller issues - such as https://github.com/kubernetes/website/issues/41173 - to track specifics.

/close
