### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by leo-gan** [kubernetes/website#14781]
**This is a Bug Report**

**Problem:**
Please, see the output of shell:
leo@cloudshell:~ (skyhive-ml)$ kubectl exec -it task-pv-pod -- /bin/bash
error: unable to upgrade connection: container not found ("task-pv-container")

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by rajeshdeshpande02** [comment]
I tried executing this task and the command you mentioned in description is working perfectly fine. Please check container is running before executing this command.
