### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dns-pod-service/

### ISSUE THREAD

**Issue by VicYP** [kubernetes/website#14800]
**This is a Bug Report**

Hi K8 Team,
    I realize that DNS chapter in English and Chinese are different. As I mix them up with english words to understand the A record for a pod. But actually the Pod dns name is complete different with Service.
   I guess the Pod DNS explanation could be corrected accordingly.
   I am standing on the 1.14 K8 page.

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @VicYP 

Can you tell us more about what part of https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ doesn't look right? For example, what's the heading of the section that you found misleading?

Alternatively, if it's the page in Chinese that's wrong, tell us about that.

**Comment by VicYP** [comment]
Hi Tim.
     What I mean is I assume the same concept explanation is not kept on both language pages. The FQND for Pods in English is “foo.bar.my-namespace.svc.cluster.local”.  In contrast, Chinese page shows FQDN is pod-ip-address.my-namespace.pod.cluster.local.

     When I look into dns-pod-service instruction page in English. It shows as below.

[cid:image001.png@01D51FBF.9F066A30]


  Instead,  When I take a look the same content in Chinese. It shows as below.

     [cid:image002.png@01D51FBF.9F066A30]
