### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update/update-intro/

### ISSUE THREAD

**Issue by thomasvs** [kubernetes/website#14809]
**This is a Bug Report**

**Problem:**

The carousel to explain updates is not working.  Clicking on the forward arrow doesn't do anything.  No errors are visible on the console when clicking on it.

![Screenshot from 2019-06-10 14-28-08](https://user-images.githubusercontent.com/248196/59217469-0067dd80-8b8c-11e9-83bc-46eafa444544.png)

**Proposed Solution:**

**Page to Update:**
k8s.io/docs/tutorials/kubernetes-basics/update/update-intro/

**Comment by sftim** [comment]
Thanks for the report.
/language en
/triage bug

**Comment by medmedchiheb** [comment]
#14895
