### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/dns-debugging-resolution/

### ISSUE THREAD

**Issue by yvzsrt** [kubernetes/website#14814]
**This is a Bug Report**

**Problem:**
`kubectl get pods --namespace=kube-system -l k8s-app=coredns `
command does not give the output as it is seen in the documentation because coredns pod has still the label " k8s-app=kube-dns"

**Proposed Solution:**
Command should be fixed. I'm not sure why coredns has still a label " k8s-app=kube-dns".
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by sftim** [comment]
Thanks for the report
/language en
/kind bug
