### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by thomasvs** [kubernetes/website#14810]
**This is a Bug Report**

**Problem:**

copy and paste from instructions does not work due to extra leading spaces

**Proposed Solution:**

remove leading spaces
![Screenshot from 2019-06-10 14-47-16](https://user-images.githubusercontent.com/248196/59218623-aa486980-8b8e-11e9-8a08-4b0fd1e3e6f0.png)

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the report.
I favour making the YAML file downloadable (via a `codenew` shortcode), which should also fix that.

/language en

**Comment by iaoiui** [comment]
I guess following section should be also modified because "Create a kustomization.yaml" section is a little confusing.
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#create-a-kustomization-yaml

**Comment by ebcarty** [comment]
Not sure if this belongs here, but I also ran into an issue with the Secret generated not being referenced properly by `mysql.yaml` since it was looking for a Secret named `mysql-pass` but the generated one had random characters appended in its name.

As such, I recommend adding the following two lines to the `secretGenerator:`
```
generatorOptions:
 disableNameSuffixHash: true
```

**Comment by ebcarty** [comment]
after discussing with Hugues Alary in #kustomize it seems that the issue stems from the version difference with `kubectl` which uses [kustomize version v2.0.3](https://github.com/kubernetes-sigs/kustomize#kubectl-integration) and it's kustomize version v3.2.0 that updates Secrets and ConfigMaps with the correct name in the referenced yaml files.

As such, after installing kustomize and confirm the version using `kustomize version` - I was able to successfully deploy the wordpress example app using `kustomize build | kubectl apply -f -`

**Comment by sftim** [comment]
Removing the leading spaces (whilst preserving Markdown formatting) should help.
