### ISSUE TITLE
Improvement for k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by adobo76** [kubernetes/website#14828]
Give a command that I can execute to validate the installation was successful.

**Comment by neolit123** [comment]
please provide more details about your OS/distribution version and what setup step you wish to verify.

**Comment by prankul88** [comment]
Hi @adobo76 , simply running `kubeadm` command shows a help page which signifies a successful installation. Not sure If you wish to verify just kubeadm or other packages too.

**Comment by adobo76** [comment]
There needs to be some sort of self test that validates the install.

**Comment by neolit123** [comment]
the install validation is already part of the DEBs and RPMs on the package managers side.
if the package failed to install tools like `apt-get` and `rpm` will fail.

/close

**Comment by adobo76** [comment]
That only works in the case of when you use a package manager though.
In this case I followed the linux container tab.

**Comment by neolit123** [comment]
xref https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

well that's why i asked about the OS/distro.

```
curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}.md5

md5sum -c <<< "$(cat kubeadm.md5) kubeadm"
md5sum -c <<< "$(cat kubelet.md5) kubelet"
md5sum -c <<< "$(cat kubectl.md5) kubectl"
```

a PR to add this verification is welcome.

/sig cluster-lifecycle

**Comment by adobo76** [comment]
I did manage to get beyond these steps yesterday.
Certainly checking the md5sums is a good first step, however, having a
network addon seems to be a requirement, there are several ports that need
to be available and I remember it complaining about my docker version as
well.
Doesn't kubernetes require docker to run?  A check for that would be a good
step as well.

Aaron

**Comment by neolit123** [comment]
> however, having a network addon seems to be a requirement, there are several ports that need
to be available and I remember it complaining about my docker version as
well. Doesn't kubernetes require docker to run?  A check for that would be a good
step as well.

installing a container runtime (CR) is right before installing the kubeadm binaries in the above link.
kubeadm will perform network and CR checks on `init` and `join` runtime (they are called "preflight checks") to verify if your nodes are k8s ready.

this is the kubeadm "create a cluster" guide:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

the #kubeadm channel on the k8s slack should be a good starting point if want help with your setup.
https://slack.k8s.io/
