### ISSUE TITLE
Issue with k8s.io/docs/reference/glossary/

### ISSUE THREAD

**Issue by gfcameron** [kubernetes/website#14823]
**This is a Bug Report**

No description of Kubernetes Ingress or Federation in Glosssary of Terms

**Proposed Solution:**
Add description of Ingress, Federation and related terms

**Page to Update:**
https://kubernetes.io/...

Current

**Comment by sftim** [comment]
Thanks for the suggestion
/language en
/kind feature

**Comment by sftim** [comment]
Ingress is already in the glossary: https://kubernetes.io/docs/reference/glossary/?all=true#term-ingress
