### ISSUE TITLE
Add KIND as the options for spinning up a test kubernetes environment for the "Tasks" section examples

### ISSUE THREAD

**Issue by opowbow** [kubernetes/website#14829]
**This is a Feature Request**

**What would you like to be added**
Under the Tasks sections, could we add KIND to the ways of setting up a kubernetes cluster ? Currently the section called : **Before you begin**, instructs the user as follows: " You need to have a k8s cluster " and it references minikube; then katacoda and https://labs.play-with-k8s.com

**Why is this needed**

KIND is another sound option for spinning up a kubernetes environment for the purpose of running through these task items

**Comments**
I am keen to work on this. Referencing @munnerz as I spoke to him about this before raising this issue

**Comment by sftim** [comment]
Thanks for the suggestion @opowbow 
/kind feature
/language en

**Comment by Rajakavitha1** [comment]
Thanks for taking on this @opowbow!!! It would be great if you could add the content for KIND here: https://kubernetes.io/docs/setup/learning-environment/

**Comment by opowbow** [comment]
No problem. So this is creating the content for KIND so that it can be referenced throughout the website...? mainly from the "Tasks" sections...?

**Comment by Rajakavitha1** [comment]
> No problem. So this is creating the content for KIND so that it can be referenced throughout the website...? mainly from the "Tasks" sections...?

It was more in terms of Getting Started with Kubernetes with KIND. Just like the one we now have for Getting Started for Kubernetes with Minkube: https://kubernetes.io/docs/setup/learning-environment/minikube/

**Comment by opowbow** [comment]
Yes sure. As I say , this content then is referenced in the task section. OK great . thanks

**Comment by Rajakavitha1** [comment]
> Yes sure. As I say , this content then is referenced in the task section. OK great . thanks

Yes, works either ways :)

**Comment by zacharysarah** [comment]
I like making this information available to folks. I'd rather see us add a link to this information in KinD source rather than dual-source this info in k/website.
