### ISSUE TITLE
Interactive Tutorial - Deploying an App Module 3: Proxycall blocks

### ISSUE THREAD

**Issue by Valansch** [kubernetes/website#14821]
**This is a Bug Report**

**Problem:**
On step 3 it is recommented to call `kubectl proxy`. This call blocks and the user is no longer able to continue with the tutorial.

**Proposed Solution:**
Replace the call with `kubectl proxy &`

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by sftim** [comment]
Thanks for the suggestion @Valansch 

/language en

**Comment by sftim** [comment]
The tutorial recommends running `kubectl proxy` in a second tab, so you don't need to use `&` to put it into the background:
> We will open a second terminal window to run the proxy.

That seems reasonable to me. I don't think the katacoda tutorial needs to change.

**Comment by Valansch** [comment]
Sorry you are right. I missed that part about the new tab
