### ISSUE TITLE
Improvement for k8s.io/docs/reference/using-api/api-concepts/

### ISSUE THREAD

**Issue by jearls** [kubernetes/website#14834]
The Kubernetes REST API documentation does not describe any of the "special" `Content-Type` values which are used.

For example, the `PATCH` operation does not work with a standard `Content-Type: application/json`.

The only place that even _vaguely_ mentions these "special" content types is the documentation for the *alpha* feature called "server-side-apply",  https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply, where a single special `Content-Type` of `application/apply-patch+yaml` is listed.  From debugging logs, this is _not_ the same `Content-Type` that `kubectl` uses during a patch operation, which apparently is `application/strategic-merge-patch+json`.

Where are these special `Content-Type` values documented?  How do I know when to use them, why I would use them, what their semantics are, etc?

**Comment by sftim** [comment]
Thanks for the suggestion @jearls 
/language en
/kind feature
/sig api-machinery

**Comment by darkfoxprime** [comment]
Has there been, or will there be, any movement on this issue?
/remove-lifecycle stale

**Comment by sftim** [comment]
> Has there been, or will there be, any movement on this issue?
This issue is ready for someone (a volunteer contributor) to pick it up. I'll add a priority.

/priority important-longterm
/help
/remove-lifecycle rotten

**Comment by sftim** [comment]
I'm afraid I added /help in error; I think this is actually a bit much for a newish contributor.
/remove-help

**Comment by tengqm** [comment]
Maybe we should mention this in the API reference guide as well.
Filed an issue in kubernetes-sigs/reference-docs#121
