### ISSUE TITLE
IPv6 enablement

### ISSUE THREAD

**Issue by jpds** [kubernetes/website#14833]
**This is a Feature Request**

**What would you like to be added**

kubernetes.io should also be served from an IPv6 enabled endpoint.

**Comment by jpds** [comment]
@thockin I remember you told me to file this one a while ago. :)

**Comment by sftim** [comment]
/kind feature
Thanks for the suggestion @jpds !

**Comment by sftim** [comment]
I like this one.
/remove-lifecycle stale
