### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-volume-storage/

### ISSUE THREAD

**Issue by abheyogy** [kubernetes/website#14838]
**This is a Bug Report**

**Problem:** Missing information about Volumes.

**Proposed Solution:** Missing information, especially that the lifecycle of a Volume is limited to the lifecycle of the Pod. Also, it would be nice to mention some contrast with Persistent Volumes here.

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the suggestion @abheyogy 
/kind feature
/language en

**Comment by sftim** [comment]
I think this is worth covering / emphasizing.
/remove-lifecycle rotten
/priority backlog
