### ISSUE TITLE
No content on /zh/docs/home/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14830]
**This is a Feature Request**

**What would you like to be added**
https://kubernetes.io/zh/docs/home/ (docs home page for 中文 / Chinese localization) is essentially blank.

**Why is this needed**
Visitors to this page would expect substantially more information.

**Comments**
This page has recently been showing a low score for visitor satisfaction (via feedback buttons on the page).
/language zh

**Comment by sftim** [comment]
I'd like to track this with a P2 or P1 label; is that reasonable / OK?

**Comment by jimangel** [comment]
Yea, I think a P2 is ok. I wouldn't be opposed to P1 with justification.

**Comment by sftim** [comment]
Thanks @jimangel; I'm not sure how issue triage and prioritization is supposed to happen.
/priority important-soon

**Comment by zhangqx2010** [comment]
Don't know what happening, but I will make a PR trying to fix.

**Comment by chenrui333** [comment]
Thanks @zhangqx2010 for taking the lead on this!!
