### ISSUE TITLE
Translate concepts/workloads/controllers/deployment/ in Japanese

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#14848]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/workloads/controllers/deployment/  in Japanese.  

**Why is this needed**
This document is not translated in Japanese. 
**Comments**

Copy a file from en contents to content/ja/docs/ concepts/workloads/controllers/deployment.md and translate it into Japanese.

**Comment by kakts** [comment]
WIP

**Comment by inductor** [comment]
@kakts How far are you working on it?
Is it fine if we move the milestone to 1.15-ja.1?

**Comment by kakts** [comment]
@inductor 
I'm now working on it. But it'll take a long time.
So it's okay to move the milestone to 1.15-ja

**Comment by cstoku** [comment]
@kakts こちら着手中でしょうか？

**Comment by kakts** [comment]
@cstoku こちら着手中です　来週にはPR出せそうです

**Comment by kakts** [comment]
Sorry I still work in progress.

**Comment by cstoku** [comment]
@kakts 作業いかがでしょうか？

**Comment by inductor** [comment]
Oops

**Comment by inductor** [comment]
@kakts 夜分すみません（KubeCon参加中なのでへんな時間にコメントしてます）
そろそろマスターに新しいバージョンをMergeしたいので、今週の水曜くらいまでに対応いただくか、1.15-ja.2のブランチを新しく切るのでそちらにマイルストーンを移していただくかのどちらかをお願いしたいです:bow:

マイルストーン移すっていうのはこちらでやる作業になるので、とりあえず同意いただければ大丈夫で、ブランチを新しくこちらで切った後に該当PRのベースブランチを変更して頂く形になります。

**Comment by kakts** [comment]
@cstoku @inductor すいませんこちらも今取り掛かってますが、進捗よくなく、、、
1.15-ja.2で対応を進めたいと思います。

マイルストーンを移して問題ありません。よろしくお願いします。
