### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

### ISSUE THREAD

**Issue by EricVanCaenenberghe** [kubernetes/website#14842]
**This is a Bug Report**

**Problem:**
Module 3, 4 and 5 of the interactive tour are broken. 
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by mhamdisemah** [comment]
if i am understanding well you mean this modules :
[https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/](url)
[https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/](url)
[https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/](url)
if you mean this module so they work well they are not broken

**Comment by sftim** [comment]
@EricVanCaenenberghe can you tell us more about the trouble you've experienced?

/triage needs-information

**Comment by EricVanCaenenberghe** [comment]
by executing the interactive tour and executing the step by step actions requested by the tour. They fail due  The connection to the server localhost:8080 was refused - did you specify the right host or port?
At my knowledge all the setup is done by the module, correct?

**Comment by mhamdisemah** [comment]
at my knowledge the setup is done by katakoda

**Comment by EricVanCaenenberghe** [comment]
some additional information: I started another tutorial on IBM Cloud concerning kubernetes.
After downloading all the stuff via the IBM Cloud command line on a RHEL 7.6. I have a similar error:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Stackoverfow indicates something about the kubectl config file
so 
$ kubectl --kubeconfig .kube/config  get nodes
error: stat .kube/config: no such file or directory

**Comment by mhamdisemah** [comment]
so i think you could open a new issue in kubernetes repo because it is out of the website context
