### ISSUE TITLE
Document search is blocked by the Great Wall Firewall?

### ISSUE THREAD

**Issue by willzhang** [kubernetes/website#14853]
**what happend?**
I need to prepare for the CKA examination in the near future.But I found that I couldn't use the search function of official documents to get anything.
The serch results have always been Fetching results..,nothing get.
I had to configure shadowsocks in global mode so that VPN could proxy all requests to use the search function.
**what i want？**
can you provide a search for china? thanks!

**Comment by sftim** [comment]
The search behavior relies on being able to access Google Custom search. If your internet provider blocks access to Google, you will not be able to use that feature of the Kubernetes documentation.

/triage support

**Comment by willzhang** [comment]
oh,shit the GFW!
