### ISSUE TITLE
Outdated terminology: “kubernetes-minion-group”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14854]
**This is a Bug Report**

**Problem:** Various pages have Nodes named `kubernetes-minion-group-<something>`.
Current Kubernetes doesn't name anything a minion; this is legacy terminology and might confuse some readers.

**Proposed Solution:**
Update affected pages

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application
https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/
https://kubernetes.io/docs/tutorials/services/source-ip

**Kubernetes Version:** v1.14

**Comments**:
The term “node pool” seems like a good replacement for “minion group”, as per https://cloud.google.com/kubernetes-engine/docs/concepts/node-pools

When dealing with individual nodes, they don't need to be in any pool.

**Comment by sftim** [comment]
I think this is a reasonable candidate for
/help

**Comment by dpandhi-git** [comment]
Would like to work on it.
