### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/controlling-access/

### ISSUE THREAD

**Issue by Jurlind** [kubernetes/website#14855]
**This is a Typo Report**

**Problem:**
[Here](https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#transport-security) is stated that the API serves on 443.

[Here](https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#api-server-ports-and-ips) is stated that API serves on two ports, one insecure default on 8080, and one secure default on 6443.

Shouldn't the secure port in this case match the one stated above, i.e. the standard 443?
**Proposed Solution:**
If this is really a typo, not influenced by my limited knowledge about Kubernetes, the solution is to remove the number 6 in 6443.
**Page to Update:**
https://kubernetes.io/...

**Comment by medmedchiheb** [comment]
kube-apiserver running on port 6443, that means missing 6 in the case of 443 . who can confirm!

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#api-server-ports-and-ips also says:
> …on Google Compute Engine (GCE), and on several other cloud providers, the API server serves on port 443

This doesn't look like a typo to me. Maybe https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#transport-security should mention that you might be running a cluster where the apiserver is accessible via port 6443. It's not clear from this one page why that discrepancy exists.

**Comment by Jurlind** [comment]
In my opinion it is still not clear which is the default secure port the cluster serves, 443 or 6443?

Obviously, both can be used as default, but from the documentation is not clearly distinguished in which context the 443 is default, and in which 6443. It is also not clear if the clusters serves a secure connection on both ports at the same time.

Thank you for your clarification. Cheers!

**Comment by sftim** [comment]
> If this is really a typo, not influenced by my limited knowledge about Kubernetes, the solution is to remove the number 6 in 6443.

In the documentation it seems reasonable to describe services on port 443 by default, and only cover the 443 / 6443 discrepancy in pages that are willing to cover why there is a difference.
/priority backlog
