### ISSUE TITLE
Confusing explanation of "subject" in https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#14858]
**This is a Bug Report**

**Problem:**
(1) The identification of subjects as "users, groups, or service accounts" suggests that service accounts are not users.  But https://kubernetes.io/docs/reference/access-authn-authz/authentication/#users-in-kubernetes clearly says that service accounts _are_ users (one of the two categories of users).

(2) The identification of subjects as users (service account or "normal") or groups fails to explain the complexity of what one subject looks like.  My understanding is that a subject is intended to be the union of general API object reference with username and group.  It is the intent to allow references to other kinds of objects in the future the explains why a subject is as complicated as it is.

**Proposed Solution:**
Reword, to something like the following.

> A role binding grants the permissions defined in a role to a set of users.  The users are identified by a list of API object references, and we define special forms of object reference to refer to a single username or a user group.  A role binding also has a reference to the role being granted. Permissions can be granted within a namespace with a `RoleBinding`, or cluster-wide with a `ClusterRoleBinding`.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

The problem exists in `master` and is not new.

Similar problems exist in the golang comments.

**Comment by sftim** [comment]
It seems to me that https://kubernetes.io/docs/reference/access-authn-authz/authentication/#users-in-kubernetes needs rewording. It's not helping the reader to say that service accounts are one kind of user and that the other kind of user is called a normal user.

Same kind of issue with https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/

**Comment by sftim** [comment]
/remove-lifecycle rotten
It _is_ a confusing page.

**Comment by Divya063** [comment]
I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
@sftim : I see two choices: either
(A) we say that "users" are divided between "normal users" and "service acounts", or
(B) we say that "users" and "service accounts" are different things and invent yet another term that means "user or service account" (because we will find ourselves wanting to talk about whatever identity is issuing a request without having stipulate one or the other or write that whole disjunction).

I think (A) may be the best choice.

@Divya063 : be my guest!

/remove-lifecycle stale

**Comment by MikeSpreitzer** [comment]
Actually, the code clearly follows (A) --- so I think the user-facing doc must too (unless or until the code changes).

**Comment by sftim** [comment]
I think it's OK for the code to frame things one way and for the documentation to explain things another way. That's because the audiences for the two are different.

For example, most pages don't mention implementation details such as informers (and don't need to) but the code certainly does describe things in these terms.

All the same, option (A) looks better. I don't know that “normal” is the right term, that's something we can discuss in the PR.

**Comment by MikeSpreitzer** [comment]
I am not convinced that the user-facing documentation is irrelevant to developers.  I am a developer myself, but I do not know everything; when I start to get into a new area, I start by reading the user-facing documentation for that area.  I do not expect the user-facing documentation to reveal implementation details.  But if it defines terms differently than the code, that gives me a headache.

**Comment by sftim** [comment]
> I am not convinced that the user-facing documentation is irrelevant to developers. I am a developer myself, but I do not know everything; when I start to get into a new area, I start by reading the user-facing documentation for that area. I do not expect the user-facing documentation to reveal implementation details. But if it defines terms differently than the code, that gives me a headache.

Ah, that's a good point.
