### ISSUE TITLE
Translate concepts/services-networking/ingress-controllers/ in Japanese

### ISSUE THREAD

**Issue by jkkitakita** [kubernetes/website#14886]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/services-networking/ingress-controllers/ in Japanese.

**Why is this needed**

This document is not translated in Japanese.

**Comments**

Copy a file from en contents to content/ja/docs/concepts/storage/volume-snapshot-classes.md and translate it into Japanese.

**Comment by cstoku** [comment]
@jkkitakita CLAの署名、できそうでしょうか？

**Comment by cstoku** [comment]
@jkkitakita こちら後1週間でPRが作成できない場合はCloseとさせてください。それより早く無理そうという判断であればその旨こちらに投稿、またはCloseしていただければと思います。
またCloseになった後、再度着手する場合は最新のマイルストーンのコンテンツを元に翻訳作業を進めていただければと思います！

**Comment by cstoku** [comment]
こちらのIssueはCloseとさせてください。
またの機会があった際にはぜひお願い致します！

/close
