### ISSUE TITLE
Translate /docs/contribute/ in Japanese

### ISSUE THREAD

**Issue by wakazooo** [kubernetes/website#14888]
**This is a Feature Request**

**What would you like to be added**
Translate docs/contribute/ in Japanese.

**Why is this needed**
This document is not translated in Japanese.

**Comments**

**Comment by inductor** [comment]
@wakazooo Are you working on it?
Is it fine if we move the milestone to 1.15-ja.1?

**Comment by wakazooo** [comment]
@inductor 
Sorry for late reply...
Please move the milestone to 1.15-ja !!

**Comment by inductor** [comment]
@cstoku	ping
