### ISSUE TITLE
Issue with /docs/admin/authorization/

### ISSUE THREAD

**Issue by veerendramw** [kubernetes/website#1489]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

*_Problem:_ Unable to understand how to create new user and attach access policies to that user.*

*_Proposed Solution:_If multiple user creation feature is available, please provide a document to create an user(with an example).*

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
/remove-lifecycle rotten

I believe the same questions have been asked many times.

**Comment by liggitt** [comment]
> Unable to understand how to create new user

https://kubernetes.io/docs/admin/authentication/#users-in-kubernetes

> attach access policies to that user

that varies by configuration authorization method

https://kubernetes.io/docs/admin/authorization/#authorization-modules

when using RBAC (which is the only method that can dynamically grant permissions), there are examples of granting permissions:

https://kubernetes.io/docs/admin/authorization/rbac/#command-line-utilities
