### ISSUE TITLE
Issue with k8s.io/de/docs/setup/

### ISSUE THREAD

**Issue by sicbb** [kubernetes/website#14891]
**This is a Bug Report**

**Problem:**
Page: https://kubernetes.io/de/docs/setup/#l%C3%B6sungen-f%C3%BCr-lokale-maschinen...

Link to https://kubernetes.io/docs/setup/pick-right-solution/#local-machine-solutions leads to 404 not found.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Danke
/language de

**Comment by rlenferink** [comment]
Hi @sicbb thanks for creating this issue. This got fixed yesterday in #14685

/close
