### ISSUE TITLE
add kind (Kubernetes IN Docker) to the list of learning environment

### ISSUE THREAD

**Issue by mhamdisemah** [kubernetes/website#14893]
**This is a Feature Request**

**What would you like to be added**
Add kind project to the list of Docker-based solutions when in learning environment

**Why is this needed**
This document should be updated as always there is new docker based solutions to run kubernetes 

**Page to Update:**
https://kubernetes.io/docs/setup/#learning-environment

**Comment by medmedchiheb** [comment]
thanks @mhamdisemah  usefull, 
i will take care of this issue 

/language en

**Comment by mhamdisemah** [comment]
> i will take care of this issue

Hey @medmedchiheb! For sure Feel free to submit a PR

**Comment by sftim** [comment]
When I look (revision c0612aed8de782f385b69d2b7ecb03c9a190a033), https://kubernetes.io/docs/setup/#learning-environment lists kind, labelled as “Kubernetes IN Docker”

**Comment by mhamdisemah** [comment]
yes you are right ,I have not seen it as i am always used to read it kind :sweat_smile: not “Kubernetes IN Docker”
