### ISSUE TITLE
Docs are not mobile friendly

### ISSUE THREAD

**Issue by steren** [kubernetes/website#14904]
**This is a Bug Report**

**Problem:**

Docs are unusable on mobile:

![Screenshot_20190614-230600](https://user-images.githubusercontent.com/360895/59547800-4230b500-8ef9-11e9-812c-5bdbbcd49a91.png)

**Proposed Solution:**

Docs are usable on mobile.

This will mostly involve CSS work via media queries to set the correct content width, font size.

For the menu, there right be the need to make it collapsible via a bit of JS.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

**Comment by raelga** [comment]
Just to add more information, the reference documentation is generated with:

https://github.com/kubernetes-incubator/reference-docs

The CSS cames from https://github.com/kubernetes-incubator/reference-docs/tree/master/gen-apidocs/generators.

And the Kubernetes site imports it with:

https://github.com/raelga/kubernetes-website/blob/master/update-imported-docs/reference.yml

**Comment by tengqm** [comment]
/remove-lifecycle stale

Maybe we switch to the markdown format docs for kubectl.

**Comment by brianpursley** [comment]
Changes were made in 1.18 to improve mobile friendliness.
Can this issue be closed now?

**Comment by tengqm** [comment]
/close
Let's see if there are still complaints on this.
