### ISSUE TITLE
Issue with k8s.io/docs/reference/issues-security/issues/

### ISSUE THREAD

**Issue by aekinkjet30** [kubernetes/website#14905]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by zhangqx2010** [comment]
@aekinkjet30 Could please describe the details of your problems? 
/triage needs-information

**Comment by nikhita** [comment]
Not a valid issue, closing

/close
