### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/

### ISSUE THREAD

**Issue by sachitale** [kubernetes/website#14910]
**This is a Bug Report**

**Problem:**
I'm using latest etcd.
Problem 1:
The commands for etcdctl:
etcdctl set ..
are from old version it seems.

Problem 2:
Even after setting up key in etcd: 
/coreos.com/network/config the flannel service wont start. It says no key starting with /coreos.com found.
If I run command:
etcdctl get /coreos.com/network/config

I can see the value that was set in the previous step.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the feedback
/language en
