### ISSUE TITLE
Document CRIContainerLogRotation feature

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14956]
**This is a Feature Request**

**What would you like to be added**
You can make kubelet responsible for rotating container logs for CRI container runtime. This has limitations; for example, [`kubectl logs` doesn't access data from old log rotations](https://github.com/kubernetes/kubernetes/issues/59902).

**Why is this needed**
Cluster operators might want to start using this log rotation feature or to understand its shortcomings and choose an alternative.

**Comments**

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

PR proposing promoting the feature gate: https://github.com/kubernetes/enhancements/pull/2418

**Comment by SergeyKanzhelev** [comment]
From [CHANGELOG-1.10](https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/CHANGELOG/CHANGELOG-1.10.md)

> Kubelet now supports container log rotation for container runtimes implementing CRI (container runtime interface). The feature can be enabled with feature gate CRIContainerLogRotation. The flags --container-log-max-size and --container-log-max-files can be used to configure the rotation behavior. (#59898, @Random-Liu)

**Comment by tengqm** [comment]
Just for clarification ... the feature gate `CRIContainerLogRotation` has been documented. What is missing is some more detailed task like user docs for this feature. The KEP2418 is about graduating this feature to GA, which mandates another change to the feature gate doc. Am I understanding the situation correctly?

**Comment by SergeyKanzhelev** [comment]
Yes, documenting flags controlling the file size and how to access logs would be desirable in documentation on GA.

**Comment by umohnani8** [comment]
Docs update PR https://github.com/kubernetes/website/pull/26799

**Comment by umohnani8** [comment]
The docs PR was merged, this issue can be closed now.
