### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by Mythobeast** [kubernetes/website#14953]
**This is a Bug Report**

** The Problem **
Page of instructions is incomplete. When Wordpress is deployed, the yaml file needs to have WORDPRESS_DB_HOST and WORDPRESS_DB_PASSWORD populated. the instructions don't describe how these values are acquired, and if they can be pulled from the deployed Mysql container in some way.

**Suggested solution**
Describe how those values are generated or retrieved. Does the MySQL deployment automatically generate a Wordpress account and database? This should also be detailed.

**Page to Update:**
https://kubernetes.io/...

**Comment by Coderhypo** [comment]
@Mythobeast 
Helllo, I create a PR and add describe about wordpress deployment. Can this solve your doubts?
