### ISSUE TITLE
Bring https://kubernetes.io/docs/setup/best-practices/multiple-zones/ up to date

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14964]
**This is a Feature Request**

**What would you like to be added**
Revise and restructure the page about running in multiple failure zones.
- create a new task page about building a cluster that spans at least 2 failure zones
- optionally create a follow-on task page to demonstrate additional concepts, such as Volume affinity to zones.
- revise https://kubernetes.io/docs/setup/best-practices/multiple-zones/ to explain what approach cluster operators should take and why they should follow it.
  - failure zones should be geographically& separate
  - consider using a managed control plane where appropriate
  - if deploying your own control plane, run that (including etcd) across multiple zones
  - also make sure nodes are available in multiple zones
  - CNI considerations for running in multiple zones
  - as good practice, cluster autoscaling should also be zone aware (run enough nodes to spread ReplicaSets etc across zones as required)

**Why is this needed**
https://kubernetes.io/docs/setup/best-practices/multiple-zones/ is out of date: it talks about Kubernetes v1.2, minions, and the v1 Federation design. The page recommends using [`kube-up`](https://github.com/kubernetes/kubernetes/blob/master/cluster/kube-up.sh) to bring up a cluster. As I understand it, `kube-up` _and_ the whole folder it lives in are deprecated.

**Comments**
Relevant to #11536 as SIG Cluster Lifecycle has expressed an intent to maintain this section of the documentation.
/language en

**Comment by sftim** [comment]
This covers some of the same ground as #14638

**Comment by sftim** [comment]
I noticed that https://kubernetes.io/docs/setup/best-practices/ doesn't really cover the benefits of a multi-master control plane. That'd be worth explaining too.

**Comment by neolit123** [comment]
i'm not familiar with the authorship of this page, but it seems to fall under SIG Cloud Provider.
potentially Node / Storage too.

/remove-sig cluster-lifecycle
/sig cluster-lifecycle

**Comment by sftim** [comment]
I'm planning to remove the cloud-provider stuff as it's both outdated and not really in line with the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).

/remove-lifecycle stale
