### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by atibdialpad** [kubernetes/website#14968]
**This is a Bug Report**

**Problem:**
IP whitelisted by networkPolicy are not able to connect to the POD because the Node IPtable is dropping that IP
**Proposed Solution:**
This IP needs to be allowed in the IPTABLE of the NODE also
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It sounds like the concept page about network policies should call out more clearly that https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ through this topic as a walk-through task.

Would that signposting help?

**Comment by atibdialpad** [comment]
I did some experiments and had these observations. Please correct me if I am wrong. 
The network Policy creates FORWARD chain IPTALBLE rules on the Kube Node whitelisting the IP mentioned in the netpol obj. Now, packets coming to the NODE destined to the service IP will hit the FORWARD chain and will get accepted/rejected as per the netpol obj. [Exactly as per netpol functionality]

However if I am running a pod with say NETADMIN access, it shares the hostNetwork and packets destined to the pod will come with destination IP as the NODE IP. In this case it hits INPUT chain  of the NODE IPTABLE. So if the source IP of these packets are not whitelisted in the NODES'S IPTABLE, these will be dropped.

**Comment by Coderhypo** [comment]
In fact, the behavior of network policies depends on the network plugin，
Can see the demo here https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ 
and sorry, I don't know what help about docs I can provide. I guess you may need to go to network plugin to create issue for this  if it doesn't meet your expectations.

**Comment by atibdialpad** [comment]
yeah, just went thru the kuberouter's network policy code and it seems they do create only FORWARD chain iptable rules.
