### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by yvzsrt** [kubernetes/website#14973]
**This is a Bug Report**

**Problem:**
In the "Configure a Pod to Use a PersistentVolume for Storage" example, a storageClass named "manual" is used but there is no comment to warn user that there must be a storageclass in the cluster named "manual". If we follow the steps written in this page we got "storageclass.storage.k8s.io "manual" not found" error.

**Proposed Solution:**
User should be warned to have a storageclass named "manual". It might be very good to add sample yaml for that storageclass onject:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by yvzsrt** [comment]
When i try this, i notice storageclass is missing but it didn't work after i create sc. I tried to delete pv and recreate it, then it worked. 
I tried same scneraio to open a bug to Kubernetes but even i deleted the sc "manual" it worked as it described in page.

**Comment by bugzyz** [comment]
@yvzsrt 
Hey, just got the same confusion here. Very curious about what the "manual" storage class is...

**Comment by bugzyz** [comment]
@yvzsrt 
Hey, just got the same confusion here. Very curious about what the "manual" storage class is...

**Comment by Manu10744** [comment]
Same problem here. Why is this not mentioned in the docs?
Sometimes it works without creating StorageClass `manual`, sometimes not. Absolutely confusing.

**Comment by winkee01** [comment]
I think someone should make manual here more clearer, as it is indeed very confusing. But to my understanding, this is a way to statically bind a PVC to a PV, by simply specifying a "virtual" StorageClass, PVC can bind to PV.
