### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/

### ISSUE THREAD

**Issue by clementlesne** [kubernetes/website#14981]
**This is a Bug Report**

**Problem:** Elasticsearch (Kibana/Metricbeat) do monitoring for Kubernetes. Elasticsearch is not referenced in the page.

**Proposed Solution:** Reference Elasticsearch (Kibana/Metricbeat) as solutions to do monitoring for Kubernetes.

**Page to Update:**
k8s.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/

**Comment by sftim** [comment]
@clementlesne there are lots of ways to monitor a cluster. Do you recommend specifically adding Elasticsearch & Metricbeats? An alternative there could be to list each of the many monitoring options that exist.
