### ISSUE TITLE
Typo in /docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14985]
**This is a Bug Report**

**Problem:**
There's a typo in https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ (“healtcheck”)

**Proposed Solution:**
Fix typo (it occurs more than once)

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Additional Information:**
/language en

**Comment by ialidzhikov** [comment]
I think now we can close this one.
