### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/service/

### ISSUE THREAD

**Issue by romgripper** [kubernetes/website#14996]
**This is a Bug Report**

**Problem:**
Unexpected characters ":wqa" in the second paragraph.
**Proposed Solution:**
Remove ":wqa" in the second paragraph.
No need to modify your application to use an unfamiliar service discovery mechanism. Kubernetes gives pods their own IP addresses and a single DNS name for a set of pods, **:wqa**and can load-balance across them.
**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/

I guess the editor was using vim:)

**Comment by Coderhypo** [comment]
haha, as vim lover, so sad to see this typo
