### ISSUE TITLE
Display left-nav when JavaScript not enabled

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#14992]
**This is a Feature Request**

**What would you like to be added**
If I disable JavaScript and access the documentation, the left-hand navigation isn't there. I'd like the static site generation to put this in place so that it's visible with or without JavaScript enabled.

**Why is this needed**
Some people, and also some web crawlers, view the web without JavaScript enabled.

**Comments**

**Comment by kbhawkey** [comment]
@sftim, I accidentally gave a "thumbs up" on this issue. I am still not sure why you need to disable JavaScript to view the docs or if your intention is to re-render the pages.

**Comment by sftim** [comment]
Some readers _never_ enable JavaScript by default. Rarely, people use user agents that just plain don't have it available.
Let's consider how to furnish documentation to that portion of people.

Also: some web crawlers either don't enable JavaScript, or penalize page rankings if the page only works properly when they do.

**Comment by sftim** [comment]
This is a very low priority improvement.
