### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by Sanjary** [kubernetes/website#14999]
**This is a Bug Report**

**Problem:**
The link to defining pull secret in pod spec is broken.
**Proposed Solution:**
Fix it to the correct link
**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by Coderhypo** [comment]
the link `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podspec-v1-core` is broken, 
but `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podspec-v1-core` is ok, 
I guess the 1.15 documentation is not completely ready.

**Comment by sftim** [comment]
Relevant to v1.15 release (PR #14984 / https://github.com/kubernetes/website/commit/f04d0cf4721c51ba918f2648bca5f40eb12584da#diff-618063036395fe9ee107f22b46c9eade)

**Comment by sftim** [comment]
Fixed by #15018 
/close
