### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

### ISSUE THREAD

**Issue by indigo423** [kubernetes/website#15020]
The link "HTTP Probes" in section "Configure Probes" with the target https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#httpgetaction-v1-core ends up in a "404 Page not found".

**Comment by sftim** [comment]
Looks like the docs don't yet have v1.15 reference information.
/kind bug

**Comment by Coderhypo** [comment]
same problem like: https://github.com/kubernetes/website/issues/14999

**Comment by sftim** [comment]
Fixed by #15018 
/close
