### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateless-application/expose-external-ip-address/

### ISSUE THREAD

**Issue by xpat** [kubernetes/website#15035]
This and the other tutorials need to include exposing the ip for https and not http, right?  As they are written, they have very limited usefulness.  Or am I missing the introductory tutorial on how to use kubernetes and do all that it does over ssl/https?

**Comment by sftim** [comment]
@xpat if this tutorial page mentioned TLS & HTTPS in its “[what's next](https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/#what-s-next)” section, would that cover it?

Right now there isn't a good page for it to link to (IMO).
Something like https://kubernetes.io/docs/tasks/security/securing-services-with-tls/ would be great but needs writing.
(see #14725 for an issue to track that work)

**Comment by xpat** [comment]
@sftim yes, that sounds good.  In specific, when I got to section 7, with curl http://<external ip>, I would want to see https://...

Thanks for the links.  I am now watching your feature request #14725 .  If I were able to contribute anything, I would.

**Comment by sftim** [comment]
@xpat is there anything the Kubernetes community can do to help you make a contribution, either to this or to another part of Kubernetes?

(if you use Slack, you can check out Kubernetes' [SIG Docs](https://kubernetes.slack.com/messages/C1J0BPD2M/) channel too).
