### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/extensible-admission-controllers/

### ISSUE THREAD

**Issue by leodotcloud** [kubernetes/website#15040]
**This is a Bug Report**

**Problem:**
The formatting is all messed up on this page. See screenshot.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

<img width="1664" alt="Screen Shot 2019-06-20 at 2 10 19 PM" src="https://user-images.githubusercontent.com/19392926/59881774-40d21300-9365-11e9-9fb5-9840eb1e04c8.png">

**Comment by mhamdisemah** [comment]
@leodotcloud i will work on it 
/assign
