### ISSUE TITLE
Missing link to API Reference for release 1.15

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#15043]
**This is a Bug Report**

**Problem:**
Release 1.15 is out now, and this section includes a link to each of several releases --- but release 1.15 is not included.

**Proposed Solution:**
Add a link to the API reference for release 1.15

**Page to Update:**
https://kubernetes.io/docs/reference/#api-reference

**Comment by MikeSpreitzer** [comment]
<img width="1038" alt="Screen Shot 2019-06-20 at 5 57 54 PM" src="https://user-images.githubusercontent.com/14296719/59884039-00828d00-9385-11e9-94ce-7de65a424135.png">

**Comment by kbhawkey** [comment]
Thanks, see #15042

**Comment by sftim** [comment]
/language en

OK to close this?

**Comment by MikeSpreitzer** [comment]
Fixed now.  Thanks!
