### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by realGoldenAce** [kubernetes/website#15053]
**This is a Bug Report**

The kubectl run kubernetes-bootcamp command is not working.

**Proposed Solution:**
I don't have one.

**Page to Update:**
k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by BenHall** [comment]
Sorry you encountered an issue. Could you please confirm if Kubernetes had started?

We can't reproduce the issue. If you continue to have problems then please let us know. Otherwise we believe this issue can now be closed.
