### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

### ISSUE THREAD

**Issue by lentzi90** [kubernetes/website#15072]
**This is a Bug Report**

**Problem:**
The example output from draining a node is broken. Code fences are visible, the output shows errors and appear to have come from the another command than the one in the example (missing flag).
A nit pick: the section header is "Cordon the node" but the action taken is actually to drain the node.

**Proposed Solution:**
The syntax should be fixed so that code fences are not visible and the output should come from the correct command and not contain errors.
The section header could be changed to "Drain the node".

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/kind bug
/assign

thanks for the report.
i though we fixed that in https://github.com/kubernetes/website/pull/13900
will send another fix shortly.
