### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by saber-Railgun** [kubernetes/website#15081]
**This is a Bug Report**

I am an user in China, with the firewall, I can't run the command minikube start

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Coderhypo** [comment]
Hello, Im Chinese too, We really can't access the image on grc.io，But fortunately you can find a lot mirror.

If you use minikube, you can try:

```
minikube start --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
```

I hope this can help you
