### ISSUE TITLE
Improvement for k8s.io/docs/concepts/configuration/secret/

### ISSUE THREAD

**Issue by waryak** [kubernetes/website#15086]
Please, add more information considering, what each field is, escpeciallyб what `name` on each level means or what `key` is? 
Also, how to describe environment variables from secret in the `deployment.yaml` file?

**Comment by sftim** [comment]
/language en
/kind feature

@waryak, thank you for the feedback.

It sounds to me as if the concept page about secret should hyperlink to https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/

Possibly, https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets should be a shorter example that refers to a new task page based on [that section](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets).
