### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/dns-debugging-resolution/

### ISSUE THREAD

**Issue by enzoTrevisan** [kubernetes/website#15097]
**This is a Bug Report**

**Problem:**

k8s-app=coreos    isn't the label for coreos, to preserve compatibility  with kube-dns coreos didn't change the label  

**Proposed Solution:**
change the document,  replace k8s-app=coreos with k8s-app=kube-dns
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the report
/language en

#14816 should fix this

**Comment by sftim** [comment]
/close
Fixed via #14816
