### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by bcdady** [kubernetes/website#15098]
**This is a Bug Report**

**Problem:**

From the [Create a Minikube cluster](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-minikube-cluster) section of the **Hello Minikube** tutorial, complete steps 1 and 2, using the Katacoda environment option.

For step 3, click the plus sign at the top of the Katacoda terminal pane, and then [Select port to view on Host 1].

Browser opens a new tab to a  https://[random_number]-cykoria04.environments.katacoda.com/ URL, and displays the following error text:

502 Bad Gateway
nginx/1.15.5

**Proposed Solution:**

Either work with Katacoda to resolve expected behavior to match the tutorial instructions, or update the tutorial instructions to use the [View HTTP port 80 on Host 1] selection option in the the Katacoda pane list (instead of the "Select port" option). This, for me, successfully opened a new browser tab to a functional URL, similar to: https://[random_number]-80-cykoria04.environments.katacoda.com/.

From this page, I was able to use the "Display a different port" form field.

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-minikube-cluster

**Comment by SupriyaSirbi** [comment]
Thanks for the issue

**Comment by BenHall** [comment]
@bcdady Thanks for raising the issue. This has since been resolved and also improved the panel to have a direct link to port 30000.

If you continue to have any problems, please let us know otherwise we think this issue can be resolved.
