### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by timothysc** [kubernetes/website#1510]
**This is a Bug Report**
**Problem:**
Instructions do not specify version matrices of components.  

**Proposed Solution:**
Include version matrix of stack components as a prereq section to getting started.

**Comment by errordeveloper** [comment]
@timothysc we have versions loosely defined in plain text, I think there aren't that many version to to have a tabular format... may be I'm missing something, what exactly are you thinking of?

**Comment by timothysc** [comment]
@errordeveloper this is a docs bug.  So if we're going to release documentation we should list the pre-requisite version(s) in the docs.  e.g. flannel, docker versions.

**Comment by errordeveloper** [comment]
@timothysc should we keep this open?
