### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by rarufocus** [kubernetes/website#15100]
kubectl version:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: proxyconnect tcp: EOF

kubectl cluster-info:
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: proxyconnect tcp: EOF

kubectl cluster-info dump:
Unable to connect to the server: proxyconnect tcp: EOF

kubectl get pod:
Unable to connect to the server: proxyconnect tcp: EOF

i have no idea about the command output.

**Comment by Coderhypo** [comment]
Hello, kubectl is only a cli for kubernetes,  and this command output mean you can't access the kube api server.

You can check you kubeconfig(`~/.kube/config`), and make sure the cluster config is correct

**Comment by sftim** [comment]
`kubectl version` output is a bit surprising if you aren't expecting the tool to connect to a cluster. Maybe.
