### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/  No package kubeadm available.

### ISSUE THREAD

**Issue by cobalt293** [kubernetes/website#15107]
**This is a Bug Report**

When trying to install Kubernetes on CENTOS 7 I get the following error
yum install -y kubeadm kubectl kubelet
Loaded plugins: langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
**No package kubeadm available.
No package kubectl available.
No package kubelet available.**

**Problem:**
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
**exclude=kube***
EOF

**Proposed Solution:**
Remove the "exclude=kube*" in Installing kubeadm, kubelet and kubectl section for Centos

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
Remove the "exclude=kube*" in Installing kubeadm, kubelet and kubectl section for Centos

 1.15

**Comment by vitality1987** [comment]
Why has "exclude=kube*" been removed? The yum install command still uses "--disableexcludes=kubernetes" and this would auto update kubectl, kubelet and kubeadm which is undesirable in a production environment. Please revert.
