### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/expose-interactive/

### ISSUE THREAD

**Issue by hlship** [kubernetes/website#1511]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

Tutorial includes `curl host01:$NODE_PORT`.  This works fine in-tutorial, but following along on my own machine, host01 is not defined.

**Proposed Solution:**

Identify where `host01` comes from and add a note about what the equivalent is when running minikube locally (on OS X, in my case).

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/expose-interactive/

module 4 step 1

**Comment by BenHall** [comment]
Thank you for the feedback. Host01 is the name of the Docker Host. We'll look at a way to make this clearer for running locally

**Comment by tcltien** [comment]
Hi BenHall , 

How can i get name of docker host when i use minikube . 

Thanks

**Comment by yuanfeiz** [comment]
If the cluster is on minikube, it provides a handy way to direct to the exposed service:
```
❯ minikube service kubernetes-bootcamp
Opening kubernetes service default/kubernetes-bootcamp in default browser...
```

**Comment by Manjunath-Bhavi** [comment]
This will work
$ kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:8443
kubernetes-dashboard is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

**Comment by hperperidis** [comment]
I have found this to work also (after having followed all the steps of the tutorial successfully) issue on terminal: 

`curl http://$(minikube ip):$NODE_PORT`

You should see:
`Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-390780338-h3wfb | v=1`

**Comment by thedug** [comment]
`minikube ip` works for me but takes 20 seconds to respond. Any idea why it would take so long?

**Comment by derberg** [comment]
`minikube ip` works perfectly and for me it takes 1-2 seconds to work. I'm surprised that this issue is closed with no solution provided. I bet there are many people out there that do not want to complete tutorials in a browser but on their local on their own

**Comment by ExplodingCabbage** [comment]
@steveperry-53, why'd you close this? https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-interactive/ still uses `host01` with no explanation of where or why it's defined, and you've not posted any explanation of why you closed it immediately after being assigned.

**Comment by BenHall** [comment]
@ExplodingCabbage Host01 is the name of the machine running.

If you run `hostname` you will see how it's been assigned.

```
$ hostname
host01
```

**Comment by steveperry-53** [comment]
@ExplodingCabbage, Sorry about closing this. I don't remember why. I think I probably hit Close by mistake.

**Comment by BenHall** [comment]
@steveperry-53 I've made some changes to help here - katacoda-scenarios/kubernetes-bootcamp-scenarios@42b95d9

**Comment by ExplodingCabbage** [comment]
@BenHall 

> I've made some changes to help here

... except that if I follow the tutorial locally on my Mac, I *can't* connect to the service on `$(hostname):$NODE_PORT`, but rather have to connect on `$(minikube ip):$NODE_PORT`. *Both* work in the interactive tutorial, but I don't know why.

**Comment by BenHall** [comment]
@ExplodingCabbage Oh, I see your point! Yes, that's much better. Updated the content to use minikube ip. Thanks!

https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/f33bbbd53a34bdb61a725b09010dcda6dbd0fab6
https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/55f969d9bdd801edd270360e25c1e3f1b9ed892f

I believe the reason `$(hostname):$NODE_PORT` doesn't work on your mac is because Minikube is running within VirtualBox (or similar VM) where as the interactive scenario is running on Linux so doesn't need a separate VM.

**Comment by ExplodingCabbage** [comment]
LGTM @BenHall. I figure this issue can now be closed.
