### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/configuration/

### ISSUE THREAD

**Issue by zilber-ran** [kubernetes/website#15122]
Probably I'm missing the right doc, however I'm looking for a reference guide for k8s config like [Dockerfile has](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwij7dPQu4bjAhWB-KQKHd-ZAuoQFjAAegQIAhAB&url=https%3A%2F%2Fdocs.docker.com%2Fengine%2Freference%2Fbuilder%2F&usg=AOvVaw38unpVI_-IPb1xDbYUr5jD) 
So far ... couldn't find it

**Comment by Coderhypo** [comment]
Does this suit your wishes?
https://kubernetes.io/docs/reference/kubectl/overview/

**Comment by zhangqx2010** [comment]
/close
Close as not valid issue.
But still you can comment below and I may offer some help.
You mean you need to find the configmap or something else?
