### ISSUE TITLE
Specify that machine translations are insufficient for localizations

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#15132]
# This is a Bug Report

## Problem

The contrib docs for localization don't specify a minimum standard of quality. We need to clarify that machine-generated translations are insufficient for minimum standards of quality.

Context: [sig-docs Slack](https://kubernetes.slack.com/archives/C1J0BPD2M/p1561571907154900)

## Proposed Solution:

Add language to [L10n contrib guidelines](https://kubernetes.io/docs/contribute/localization/) specifying that localizations must meet a minimum standard of quality, and that machine-generated translations require extensive human review before they can meet that standard.

## Page to Update:

https://kubernetes.io/docs/contribute/localization/

**Comment by lnmei** [comment]
Hello, would like to contribute on this! To clarify, are we to define the minimum standard of quality in the guidelines such as a specified level of fluency for human reviewers and/or contributors, or just clarify a process of human review for machine-generated translation?

**Comment by zacharysarah** [comment]
@lnmei 👋 Thanks for your interest!

> just clarify a process of human review for machine-generated translation

This is a great place to start. 👍

**Comment by aimeeu** [comment]
The page already has a "caution" note about this in the [Translating content](https://kubernetes.io/docs/contribute/localization/#translating-content) section.

/close
