### ISSUE TITLE
Find long term fix for `test-examples` in Makefile

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#15138]
**Cascading Problems:**
When Netlify builds **any** non-`master` branch, such as all of the n-1 release branches, a special build command (in `netlify.toml`) is used to prevent SEO robots from indexing. This makes sense because we only want to index the `master` website for SEO. Inherently, this is not a problem, but has lead to more issues.

All build commands use a `Makefile` that references BASH scripts (`test-examples` and others) to run specific tests. Once again, inherently, not an issue.  `test-examples` was used to validate short codes before building and saved time. It also had a hard dependency Travis CI.

On April 3rd 2019, @lucperkins removed Travis CI from all build processes because it was inconsistent, flaky, and not really providing clean signal. With https://github.com/kubernetes/website/pull/13598. Context for removal: https://github.com/kubernetes/website/issues/13140

On May 9th 2019, we discovered the conclusion that you are most likely arriving at: https://kubernetes.slack.com/archives/CA1MMM1HU/p1557414470032800

**Conclusion:**

Removing Travis CI, broke the test-examples, which failed builds in `master` 5/9/19 and later we discovered failing builds in `release-` 6/26/19.

Why the delay? We fixed `master` with https://github.com/kubernetes/website/pull/14252, however once we cut `release-1.14,` it began using the non-`master` build that reintroduced the problem.

**Proposed Solution:**

- Fix `test-examples` to not have Travis CI dependency and reintroduce
- Set build command in `one-source-of-truth` (ex: all in Netlify GUI or all in `netlify.toml`).
    - I discovered some were set in 2 places, Netlify uses `netlify.toml` as the winner in a conflict, it just makes debugging challenging.
    - Setting them all in Netlify GUI would allow only admins change build arguments (double edged)
- Leave `test-examples` deprecated, close this out, and move on.

Related PRs:
- https://github.com/kubernetes/website/pull/15133
- https://github.com/kubernetes/website/pull/15137

/cc @zacharysarah @tengqm @lucperkins

**Comment by jimangel** [comment]
/remove-lifecycle stale
@lucperkins would you have any cycles to take a peek at this?

**Comment by lucperkins** [comment]
I vote for (a) removing this from the CI path completely but (b) leaving the scripts in place for people to run ad hoc manual tests if they wish. It’s a nice idea but, in my opinion, not sufficiently beneficial or central to our core mission to warrant even the bandwidth we’ve already expended on it. If someone would like to step up and act as a steward of the examples, running the tests on their own and making fixes when needed, I’m all for that. So in sum, I think we should applaud the ingenuity behind it but not let it detain us further.
