### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by c00** [kubernetes/website#15166]
In the section "Login to docker" there's a note saying:

> Note: If you use a Docker credentials store, you won’t see that auth entry but a credsStore entry with the name of the store as value.

What it doesn't say, is that when the credsStore is used, the `kubectl create secret` command in the next section won't save the credentials to the secret. It also doesn't say how to get around it.

**Comment by sftim** [comment]
/language en
/kind feature

Thanks for pointing this out.

**Comment by faucherb94** [comment]
I've been running into this issue as well.

**Comment by faucherb94** [comment]
So apparently `credsStore`s [officially not supported](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry).

**Comment by sftim** [comment]
@faucherb94 are you saying in your last update that this is well documented enough to not need changes, or that it's hard to uncover that detail and so it's worth tweaking the current documentation?

**Comment by bleggett** [comment]
@sftim As someone who just hit this, I'd like some indication in the docs as to how I can get the credentials if my docker config looks like this, rather than an observation stating that "your docker config may not look like this"

**Comment by sftim** [comment]
Thanks
/priority backlog
/remove-lifecycle stale

**Comment by c00** [comment]
@bleggett In case you are still looking for a solution, check out [this documentation](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line) on creating docker creds from the command line.

```bash
kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
```
