### ISSUE TITLE
Suggestion for k8s.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15171]
**This is a Suggestion**

**Problem:**
The page describes something that looks like a Kubernetes resource that you might try to use with `kubectl apply -f`, but actually this configuration is for `kubeadm --config`.

**Suggestion:**
Mention `kubeadm --config` at the start of the page, maybe with a link to relevant information.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

**Kubernetes Version:**
v1.15

**Comment by sftim** [comment]
If anyone starts work on this, also take a look at issue #14337.

**Comment by Coderhypo** [comment]
And I meet some strange things.

I use the yaml in this [docs](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#apiserver-flags) and run `kubeadm init`, then get message as follows:

```
# kubeadm init --config kubeadm-config.yml
W0628 13:19:15.022862   30951 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta2", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal bool into Go struct field APIServer.extraArgs of type string
v1beta2.ClusterConfiguration.APIServer: v1beta2.APIServer.ControlPlaneComponent: ExtraArgs: ReadString: expects " or n, but found f, error found in #10 byte of ...|us-auth":false,"audi|..., bigger context ...|ertise-address":"192.168.0.103","anonymous-auth":false,"audit-log-path":"/home/johndoe/audit.log","e|...
```

Kubeadm Version

```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:41Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Coderhypo** [comment]
I have two discoveries.

1. The key: value pairs in `extraArgs` field must be str: str
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go#L119

2. `ClusterConfiguration` does not have a field named metadata:
https://github.com/kubernetes/kubernetes/blob/v1.13.0/cmd/kubeadm/app/apis/kubeadm/types.go#L61
https://github.com/kubernetes/apimachinery/blob/release-1.13/pkg/apis/meta/v1/types.go#L41

I don't make sure this is correct, I can only come up here（But if this is correct, the documentation needs to be updated）

**Comment by neolit123** [comment]
1. this is already covered in godocs:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#ControlPlaneComponent

2. yes, it does not and it's OK to be removed from this page because ClusterConfiguration does not embed ObjectMeta. https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta

**Comment by Coderhypo** [comment]
@neolit123 Thanks for your reply, Then I can make sure that the yaml in the document needs to be updated.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#apiserver-flags
