### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by kubconvert** [kubernetes/website#15225]
**This is a Bug Report**

**Problem:**
Installation on ubuntu 18.04.2 failed
apt-get does not work with kubeadm, kubectl and kubelet
**Proposed Solution:**
Change from apt-get install  to snap add
Additional instruction will be required as csgroup is failing and I am sure there will be further issues.
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by neolit123** [comment]
hi, what errors are you getting for `apt-get install`?
/triage support
/sig cluster-lifecycle

**Comment by neolit123** [comment]
> I’m getting not available use snap add

i have not seen such a message before.

**Comment by kubconvert** [comment]
I ran through again using the utube example https://www.youtube.com/watch?v=oyBwkkRn7XM this appeared to take me beyond my previous issue and I am no longer getting the error.

**Comment by neolit123** [comment]
thanks for testing.
/close
