### ISSUE TITLE
Translation for content/ja/case-studies/appdirect in Japanese

### ISSUE THREAD

**Issue by maabou512** [kubernetes/website#15222]
**This is a Feature Request**

**What would you like to be added**
Translation for case study of AppDirect
https://kubernetes.io/case-studies/appdirect/

**Why is this needed**
No translation exists in Japanese.
And this case study is so useful for Japanese readers (not only for developers)

**Comments**
Copy a file from en contents to content/ja/case-studies/appdirect/index.html and  content/ja/case-studies/appdirect_featured_logo.png  and translate it into Japanese.

/language ja
/assign

**Comment by inductor** [comment]
@maabou512 Are you working on it?
Is it fine if we move the milestone to 1.15-ja.1?

**Comment by cstoku** [comment]
@jkkitakita こちら後1週間でPRが作成できない場合はCloseとさせてください。それより早く無理そうという判断であればその旨こちらに投稿、またはCloseしていただければと思います。
またCloseになった後、再度着手する場合は最新のマイルストーンのコンテンツを元に翻訳作業を進めていただければと思います！

**Comment by cstoku** [comment]
@maabou512  こちら後1週間でPRが作成できない場合はCloseとさせてください。それより早く無理そうという判断であればその旨こちらに投稿、またはCloseしていただければと思います。
またCloseになった後、再度着手する場合は最新のマイルストーンのコンテンツを元に翻訳作業を進めていただければと思います！
