### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by connor4312** [kubernetes/website#15230]
**This is a Bug Report**

**Problem:** Following the minikube guide using Hyper-V on Windows, `minikube start` fails

```
C:\WINDOWS\system32>minikube start
* minikube v1.2.0 on windows (amd64)
* Downloading Minikube ISO ...
 129.33 MB / 129.33 MB [============================================] 100.00% 0s
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0701 13:28:09.084688   24924 start.go:559] StartHost: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

X Unable to start VM
* Error:         [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
* Advice:        Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
* Documentation: https://www.virtualbox.org/wiki/Downloads
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3784
  - https://github.com/kubernetes/minikube/issues/3776

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new
```

My PC is running Windows 10 Enterprise, OS build 17763.557 (1809)

**Proposed Solution:**  I found [another guide](https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c) which got me through the installation process. I think the page should either make note of the additional steps required for Hyper-V users, or (larger change) perhaps update `minikube` to automatically detect/confirm the hypervisor to use.

**Page to Update:** https://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by RA489** [comment]
@connor4312 Please follow this hyperv guide: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/
