### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by chanont-poon** [kubernetes/website#15258]
**This is a Bug Report**

**Problem:** Running the command `minikube addons disable heapster` failed on Windows 10 Home via Git Bash command line. It printed out the following error message:
```
X disable failed: [disabling addon deploy/addons/heapster/influx-grafana-rc.yaml.tmpl: Process exited with status 1]

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

**Kubernetes Version:** 1.15

**Comment by RA489** [comment]
@thecrudge Heapster has been depcrecated from minikube addons.

**Comment by RA489** [comment]
FYR https://minikube.sigs.k8s.io/docs/tasks/addons/
