### ISSUE TITLE
"Google Cloud Monitoring" now called "Stackdriver Monitoring"

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/website#15259]
**This is a Bug Report**

**Problem:**

https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#google-cloud-monitoring

1. Google Cloud Monitoring was renamed (some time ago) to [Stackdriver Monitoring](https://cloud.google.com/monitoring/).
2. Improvements have been made to Stackdriver Monitoring's Kubernetes dashboards.
3. References to outdated service names increase user complexity (finding relevant content) and increase concern about general content quality.

**Proposed Solution:**

1. Revise references to "Google Cloud Monitoring" to "Stackdriver Monitoring".
2. Revise video and images to show current service functionality
3. Grep site for other outdated references to this service.

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#google-cloud-monitoring

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#google-cloud-monitoring has gone
/close
