### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/turnkey/stackpoint/

### ISSUE THREAD

**Issue by mwmahlberg** [kubernetes/website#15262]
**This is a Bug Report**

**Problem:**

The documentation refers to stackpoint.io, which is retired.

![Bildschirmfoto 2019-07-03 um 08 06 51](https://user-images.githubusercontent.com/138420/60567361-0b1c2980-9d6a-11e9-98b0-be31a8640cae.png)

**Proposed Solution:**

Remove said page from documentation.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/turnkey/stackpoint/

**Comment by sftim** [comment]
Good spot
/priority important-longterm

**Comment by furukawa3** [comment]
Hi, I'd like to fix this issue.  Plz tell me a little bit.  I just checked [stackpoint.io](https://stackpoint.io/) and also saw "retired".  I think nobody can try this page.  So, should we remove this page [Running Kubernetes on Multiple Clouds with Stackpoint.io](https://kubernetes.io/docs/setup/production-environment/turnkey/stackpoint/) ??

**Comment by sftim** [comment]
>  should we remove this page Running Kubernetes on Multiple Clouds with Stackpoint.io

That seems the best approach. Are you happy to submit a pull request @furukawa3 ?

**Comment by furukawa3** [comment]
> > should we remove this page Running Kubernetes on Multiple Clouds with Stackpoint.io
> 
> That seems the best approach. Are you happy to submit a pull request @furukawa3 ?

Will do !! Thanks @sftim for your kindness.
