### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/high-availability/

### ISSUE THREAD

**Issue by rcythr** [kubernetes/website#15284]
**This is a Bug Report**

**Problem:**
The section describing the load balancer was clearly written with a cloud deployment in mind, and glosses over some details for bare metal deployments which less-experienced users may miss during setup. In particular it suggests that HAProxy can be used, but glosses over the fact that if you use HAProxy and want high availability you need to use a VIP to handle load balancer failure. Otherwise your HAProxy load balancer node is a single point of failure in your HA cluster. 

**Proposed Solution:**
Update the docs to suggest that:

In a cloud environment, use the load balancer infrastructure provided by the cloud provider. This gives you HA for your load balancer out-of-the-box.

In an environment without a built-in load balancer (i.e. bare metal), you can use a TCP forwarding proxy, such as HAProxy, however you need to take steps to make that load balancer highly available. Otherwise your load balancer becomes a single point of failure. I feel like you could possibly also create a VIP for the master nodes directly and skip HAProxy entirely.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#create-load-balancer-for-kube-apiserver

Additional Information:

I'm willing to make this change to the documentation and submit a PR for it; however, I want to make sure others agree that (1) this is a problem, and (2) my proposed solution sounds reasonable.

**Comment by neolit123** [comment]
> The section describing the load balancer was clearly written with a cloud deployment in mind, and glosses over some details for bare metal deployments which less-experienced users may miss during setup. In particular it suggests that HAProxy can be used, but glosses over the fact that if you use HAProxy and want high availability you need to use a VIP to handle load balancer failure. Otherwise your HAProxy load balancer node is a single point of failure in your HA cluster.

a couple of points:
- i don't think our documents have cloud providers in mind. but possibly the wording can be adjusted.
- kubeadm is LB agnostic and HAProxy is just an example.

> In a cloud environment, use the load balancer infrastructure provided by the cloud provider. This gives you HA for your load balancer out-of-the-box.

it really depends on the cloud provider. the CP *might* give you an HA LB or not. so possibly we should be clear about that.

> In an environment without a built-in load balancer (i.e. bare metal), you can use a TCP forwarding proxy, such as HAProxy, however you need to take steps to make that load balancer highly available. Otherwise your load balancer becomes a single point of failure. I feel like you could possibly also create a VIP for the master nodes directly and skip HAProxy entirely.

+1, i like extending the docs with something like this but will defer to @fabriziopandini for more comments. i think we should make it clear that a VIP LB can be a single point of failure and such a cluster is not really HA.

/assign @fabriziopandini @neolit123 
/sig cluster-lifecycle

**Comment by fabriziopandini** [comment]
@rcythr @neolit123 I'm ok with the proposed wording improvement

On top of  @neolit123 comments, I suggest to remove the "I feel like you could possibly also create a VIP for the master nodes directly and skip HAProxy entirely." bit, so we can avoid getting into the details of all the possible alternatives to achieve an HA load balancer on bare metal ("you need to take steps to make that load balancer highly available." is enough IMO)

@rcythr looking forward to your PR!

**Comment by sftim** [comment]
/priority backlog

/kind feature
(I think)
