### ISSUE TITLE
Translate tasks/run-application/force-delete-stateful-set-pod/ in Japanese

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#15294]
**This is a Feature Request**

**What would you like to be added**

Translate tasks/run-application/force-delete-stateful-set-pod/ in Japanese.

**Why is this needed**

This document is not translated in Japanese.

**Comments**

Copy a file from en contents to content/ja/docs/tasks/run-application/force-delete-stateful-set-pod.md  and translate it into Japanese.

/language ja

**Comment by inductor** [comment]
@oke-py Are you working on it?
Is it fine if we move the milestone to 1.15-ja.1?

**Comment by oke-py** [comment]
@inductor I've translated about 1/3 page.
It's OK to move the milestone. Thanks.

**Comment by inductor** [comment]
Thanks!

Please note that you might have to make some modifications on what you’ve translated as it will be a different version
