### ISSUE TITLE
Translate docs/concepts/configuration/overview.md in Japanese

### ISSUE THREAD

**Issue by 0Delta** [kubernetes/website#15300]
**This is a Feature Request**

**What would you like to be added**

Translate docs/concepts/configuration/overview.md in Japanese

**Why is this needed**

This document is not translated in Japanese.

**Comments**

Copy a file from en contents to content/ja/docs/concepts/configuration/overview.md and translate it into Japanese.

/language ja

**Comment by inductor** [comment]
I'll do it. Will be based on 1.15 as well since nobody seems working on it.

**Comment by 0Delta** [comment]
Sorry to late action. and thanks for kind work by @inductor .
