### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by keiyasssss** [kubernetes/website#15306]
**This is a Bug Report**

**Problem:**
error: unable to read URL "https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml", server reported 404 Not Found, status code=404
**Proposed Solution:**
upload it again
**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by hkhatri241** [comment]
Fixed by https://github.com/kubernetes/website/pull/15290
/close

**Comment by vishakhanihore** [comment]
@thecrudge Its good to be closed

**Comment by aimeeu** [comment]
#15290 has been merged

/close
