### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by srslafazan** [kubernetes/website#15312]
**This is a Bug Report**

**Problem:**

The documentation says Kubernetes supports Ubuntu 16.04+, but Kuberentes barely runs on Ubuntu 18.04 LTS, and only with precise single-node configurations. The documentation fails to mention that Kubernetes configurations frequently fail, and many of its components (like kubelet itself, kube-dns, coredns, etc.) crash, and it is incompatible with systemd-resolved on Ubuntu 18.04+.

**Proposed Solution:**

Update the documentation to advise that Kubernetes only supports up to Ubuntu 16.04, until it runs stably on newer versions of Ubuntu.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

And any other documentation relating to Ubuntu versions

**Comment by dims** [comment]
@srslafazan Are there bugs logged for the issues you mention? (with logs etc?)

**Comment by neolit123** [comment]
the official documentation contains information about systemd-resolved.

see:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#providing-instance-specific-configuration-details
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues

also kubeadm already manages the systemd-resolved situation for you. it passes this to the kubelet if systemd-resolved is enabled:
https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/phases/kubelet/flags.go#L104

version of Ubuntu newer than 16.04 are supported and i haven't seen reports about this for a while.

/priority awaiting-more-evidence
/sig cluster-lifecycle

**Comment by srslafazan** [comment]
I've seen this in Ubuntu 18.04 only -- Centos7 does not have this issue, for example.

Kubeadm breaks systemd-resolved settings and destroys ARP settings. I haven't yet found a way to fix the ARP configuration without blasting the OS and re-installing (clearing the cache is not enough, ipv4 network neighbors are unresolvable after running kubeadm join). Perhaps there is a way to disable the arp protocol -- but this workaround is so broken that Ubuntu 18.04 shouldn't be advertised as "supported". If k8s requires you to manually fix kernel level settings on every node whenever you join a new node, it's unreasonable to advertise it as supported for that OS.

Keep in mind this is for clusters with multiple nodes -- single-node clusters don't run into this issue because they don't need to resolve other nodes -- anyway there should be a disclaimer for this.
