### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by russellrobinson** [kubernetes/website#15351]
**This is a Bug Report**

'minikube --vm-driver=none start' reports the following error:
StartHost: create: precreate: exec: "docker": executable file not found in $PATH
Unable to start VM: create: precreate: exec: "docker": executable file not found in $PATH

**Proposed Solution:**
The page should mention that docker is required to be installed.

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
docker is listed as a prereq for minikube:

```Note: Minikube also supports a --vm-driver=none option that runs the Kubernetes components on the host and not in a VM. **Using this driver requires Docker and a Linux environment but not a hypervisor**. It is recommended to use the apt installation of docker from (Docker, when using the none driver. The snap installation of docker does not work with minikube.```

/close
