### ISSUE TITLE
Improvement for k8s.io/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/

### ISSUE THREAD

**Issue by ejmarten** [kubernetes/website#15358]
No platform specific documentation! 

instructions that include platform specific utilities are useless to majority populations of the community:

kube-up.sh - not used in my on-prem cluster
kops - not used in my on-prem cluster

These are great, and I can usually translate the docs into something useful, but these utilities shouldn't be in the CNCF k8s docs unless they're in a section specific to the provider where they are used.

**Comment by QuantumADK** [comment]
Aaron Daniel Kaatz

**Comment by sftim** [comment]
This seems like a legitimate concern
/remove-lifecycle stale
/priority important-longterm
