### ISSUE TITLE
Missing "_index.md" files

### ISSUE THREAD

**Issue by bep** [kubernetes/website#15353]
So, I rebuild this website to watch for diffes when I do some structural changes in Hugo, because this seems to be a good indicator to whether I have made any changes to the section logic ...

What I do see, however, are some inter-language "mismatches" in section configuration. I have thought about making this more automatic/robust on the Hugo side, but it's hard to do without breaking stuff.

But this site uses the section tree heavily when building navigation and also to fill in with missing translations, so it's a little bit important that it is ... mostly correct.

The Hugo section rules summarized:

* The top level content folder is a section, e.g. "docs", "blog".
* Every folder down to the bottom-most "_index.*" file (e.g. "_index.md", "_index.html")

One example of what I consider to be wrong and give unexpected result:

```bash
▶ ls -ltr content/en/docs/tutorials/stateful-application/_index*
-rwxr-xr-x  1 bep  staff  51 May 17  2018 content/en/docs/tutorials/stateful-application/_index.md
▶ ls -ltr content/zh/docs/tutorials/stateful-application/_index*
zsh: no matches found: content/zh/docs/tutorials/stateful-application/_index*
▶ ls -ltr content/zh/docs/tutorials/kubernetes-basics/_index.*
-rw-r--r--  1 bep  staff  4634 Mar 14 20:58 content/zh/docs/tutorials/kubernetes-basics/_index.html
```

The `stateful-application` folder will in English end up in its own section (`stateful-application`), but in Chinese it ends up in the Tutorials section.

In the particular example I would guess that Chines should add an "index.md" file.

/cc @zacharysarah

**Comment by sftim** [comment]
/language zh
(and possibly others)

**Comment by tengqm** [comment]
This need to be revisited.
/remove-lifecycle stale

**Comment by ydcool** [comment]
resolved since https://github.com/kubernetes/website/pull/18217
/lifecycle rotten
