### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by pinterl** [kubernetes/website#15362]
**This is a Bug Report**

**Problem:**
When I typed ````minikube dashboard```` into the terminal I got the following error message:

Open a 'Web Preview' to render the response from a running web server.
minikube version; minikube start
$
$ minikube version; minikube start
minikube version: v1.2.0
* minikube v1.2.0 on linux (amd64)
* Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.5
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
* Pulling images ...
* Launching Kubernetes ...
* Configuring local host environment ...
* Verifying: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"

$ minikube dashboard
* Enabling dashboard ...
* Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
* Opening http://127.0.0.1:37613/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
* failed to open browser: exec: "xdg-open": executable file not found in $PATH

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

v1.15.0

**Comment by tengqm** [comment]
dup of #12968
