### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by DavidODonovan** [kubernetes/website#15370]
Hi this interactive tutorial did not work for me - I could not connect to localhost:8001
********************************
$ curl http://localhost:8001/version
curl: (7) Failed to connect to localhost port 8001: Connection refused
********************************

**Comment by thecrudge** [comment]
/triage support

This is likely because you did not start the proxy in another terminal

/close
