### ISSUE TITLE
Version selection not working on macOS Safari

### ISSUE THREAD

**Issue by kidlj** [kubernetes/website#15387]
with Safari 12.1.1 (14607.2.6.1.1) on macOS 10.14.5.

<img width="293" alt="k8s_io_version_selection" src="https://user-images.githubusercontent.com/300616/61100863-3dc8cf00-a49a-11e9-9d12-8360b6ec1c35.png">

**Comment by thecrudge** [comment]
/kind bug

I am seeing the same issue

**Comment by kidlj** [comment]
It was fixed. This case is closed.
