### ISSUE TITLE
Hugepages in non-privileged context

### ISSUE THREAD

**Issue by e-ago** [kubernetes/website#15395]
Hello. Is it possible to run an application which requires hugepages in a Pod without having a privileged security context?

**Comment by thecrudge** [comment]
Hi @e-ago 

This would be more of a support question, and not a question for the website. Please direct your question for stackoverflow, or another site better suited to answer this question. 

Also see: 

https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/

/close
