### ISSUE TITLE
Hugo glossary tooltips in l10n content are broken

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#15390]
**This is a Bug Report**

**Problem:**

For all the glossary tooltips in l10n content, HTML are exposed in a code block.

![image](https://user-images.githubusercontent.com/282159/61134797-5ae1ba00-a4fb-11e9-8345-79058450d237.png)

**Proposed Solution:**

**Page to Update:**
* https://kubernetes.io/ko/docs/setup/
* https://kubernetes.io/ko/docs/concepts/workloads/pods/pod-overview/
* https://kubernetes.io/id/docs/concepts/services-networking/service/

/cc @lucperkins

**Comment by sftim** [comment]
I think this might be fixed now. Is that right?

**Comment by gochist** [comment]
@sftim Thank you for letting me know. But it still has unexpected line breaks.

![image](https://user-images.githubusercontent.com/282159/61257770-6825cf80-a7ad-11e9-80a9-f0aeeab8f72e.png)

![image](https://user-images.githubusercontent.com/282159/61257755-56dcc300-a7ad-11e9-99d3-68b30407ee96.png)

**Comment by sftim** [comment]
Think this is _fixed_ fixed.
/close
