### ISSUE TITLE
Translate /docs/tutorials/configuration/configure-redis-using-configmap.md in Japanese

### ISSUE THREAD

**Issue by silverskyvicto** [kubernetes/website#15428]
**This is a Feature Request**

**What would you like to be added**

Translate /docs/tutorials/configuration/configure-redis-using-configmap.md in Japanese.

**Why is this needed**

No /docs/tutorials/configuration/configure-redis-using-configmap.md in Japanese.

**Comments**

Copy from en content and Update content/en/docs/tutorials/configuration/configure-redis-using-configmap.md.

**Comment by inductor** [comment]
@cstoku I'll start working on it on 1.15 branch
