### ISSUE TITLE
Issue with k8s.io/docs/home/

### ISSUE THREAD

**Issue by Ishan0075** [kubernetes/website#15422]
I am running K8es on Centos of GCP. Able to create nodes but unable to run any kubectl commands showing the below error message
"bash: kubectl: command not found"
Any help is mostly appreciated.

**Comment by poothia** [comment]
I think there is an issue with $PATH. Can you verify if correct PATH is set?

**Comment by thecrudge** [comment]
This would be considered more of a support issue. This issue would be better suited for stackoverflow, or some a place of that nature. I have been through the kubectl docs, and there is nothing currently wrong with them. 

Please continue to open issues if you see anything wrong with the documentation. 

/close
