### ISSUE TITLE
Fix previous/next buttons in blog

### ISSUE THREAD

**Issue by vharsh** [kubernetes/website#15438]
**This is a Bug Report**

**Problem:**
The Previous/Next navigation buttons have the same text.

![Screenshot from 2019-07-12 12-23-20](https://user-images.githubusercontent.com/9304050/61211360-061d8980-a71d-11e9-8667-9c2110afb105.png)

**Proposed Solution:**
The Previous/Next navigation buttons shouldn't have the same text.

**Page to Update:**
All pages matching
```
https://kubernetes.io/blog/<yyyy>/<mm>/<dd>/<topic>
```

**Comment by sftim** [comment]
Thanks for spotting that.
/kind bug
