### ISSUE TITLE
Issue with k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-token/

### ISSUE THREAD

**Issue by kaushikr93** [kubernetes/website#15437]
**This is a Bug Report**

**Problem:**
"kubeadm token create" and "kubeadm token generate" are contradictory . I was trying to stand up a 1 master and 3 worker cluster . So token was expired in master , i used "kubeadm token generate" command it generated me a token and then i was trying to used "kubeadm join"" command . It started failing then used -v=6 in order to get more information , so in logs there was a message to use "kubeadm token create" command . After using this it worked like charm.

**Proposed Solution:**
The synopsis under Kubdeadm token generate is mis leading telling that the token generated with this command is used for "kubeadm init" or "kubeadm join" , which of now is not working.

This section has to be reviewed as to retain or to remove . 

**Page to Update:**
https://kubernetes.io/...

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

CentOS Linux release 7.6.1810 (Core)

Linux Kube-Master 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by RA489** [comment]
@kaushikr93 `Kubeadm Token generate` command is not used to generate a token. This command is provided for convenience to generate tokens in the given format.

**Comment by RA489** [comment]
`Kubeadm Token create ` command create a bootstrap token for you.
