### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tls/certificate-rotation/

### ISSUE THREAD

**Issue by Cisien** [kubernetes/website#15444]
this document does not describe how to manually rotate the cluster's TLS certificates.

**Comment by sftim** [comment]
At a minimum, it feels to me that this page https://kubernetes.io/docs/tasks/tls/certificate-rotation/ should signpost readers to a page that tells them how to get their cluster to be using newer certificates.

/kind feature
/language en

**Comment by sftim** [comment]
Still valid
/remove-lifecycle stale

**Comment by sftim** [comment]
Also see issue #18199

**Comment by sftim** [comment]
@abhiTamrakar would you be interested in working on this documentation? You mentioned in #19165 that you have already done the rotation manually.

**Comment by sftim** [comment]
If anyone would like help drafting page text, checking its technical accuracy, or understanding how to contribute, please reply here. I'm watching this issue and can try to make time available to help other contributors.

**Comment by abhiTamrakar** [comment]
@sftim I can do that, any pointers where to put the draft or I have to traverse through the docs to find a place.

**Comment by abhiTamrakar** [comment]
@sftim please assign to me, I am trying it E2E manually, once tested properly, will create the doc and update with PR link.

**Comment by sftim** [comment]
Please feel free to open a draft (work-in-progress) PR, or even one that is ready for review.

**Comment by sftim** [comment]
I think you can only assign to people who have joined the Kubernetes organization on GitHub

/assign @abhiTamrakar

**Comment by neolit123** [comment]
the document merged

https://github.com/kubernetes/website/pull/19351
https://github.com/kubernetes/website/pull/21651

/close
