### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by LinziWang** [kubernetes/website#15457]
**This is a Bug Report**

**Problem:**
IT CAN NOT WORK.
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
Hi @LinziWang Can you please provide details in the issue you are seeing?

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
