### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/cloud-controller/

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/website#15467]
**This is a Bug Report**

**Problem:**
The diagrams still refer to `Minions`. They should be changed to `Nodes`
**Proposed Solution:**
Edit the diagrams to change the terminology.
**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/cloud-controller/

**Comment by sftim** [comment]
This looks like a duplicate of issue #14404

**Comment by blueelvis** [comment]
Closing this.
