### ISSUE TITLE
Node Local DNS is not something you can install in a sandbox playground

### ISSUE THREAD

**Issue by craigbox** [kubernetes/website#15461]
https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/ starts with "You need a cluster!  Try one of these playgrounds" and gives the default links to Katacoda and Play With Kubernetes.

The page refers to an Alpha node feature which has to be installed manually into a cluster, and as such the advice to use a playground isn't helpful.

I wonder if that same problem exists on other pages where this snippet is included?

**Comment by sftim** [comment]
Good point
/language en
