### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/podpreset/

### ISSUE THREAD

**Issue by manishbansal8843** [kubernetes/website#15478]
**This is a Bug Report**

**Problem:**
Documentation says 

>Note: A Pod Preset is capable of modifying the following fields in a Pod spec when appropriate: - The .spec.containers field. - The initContainers field (requires Kubernetes version 1.14.0 or later).

**Proposed Solution:**
It should clearly mention what all fields can be modified. As per the proposal, it can only modify `Env` and `Volume`. Also, i cannot see any reference of `initContainers` in the proposal. Not sure if that is even valid.
**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/podpreset/

**Comment by sftim** [comment]
That sounds worth fixing.
/language en
