### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by kpooja20** [kubernetes/website#15477]
**This is a Bug Report**
"error starting host,error creating new host,missing adress"

"error starting host,error creating new host,missing adress"

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@kpooja20 could you please provide some more details.

**Comment by RA489** [comment]
priority/awaiting-more-evidence

**Comment by thecrudge** [comment]
This seems more like a support request rather than an issue with the documentation. @kpooja20 please help clarify what you are stating.
