### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by ponessa** [kubernetes/website#15484]
**This is a Bug Report**

**Problem:**. `kubectl version` returns `Unable to connect to the server: dial tcp 192.168.99.100:8443: i/o timeout`.  

**Proposed Solution:** Learning k8 and installing `kubectl` and `minikube` are part of the lessen.  The Coursera course directed me to https://kubernetes.io/docs/tasks/tools/install-kubectl/ which does not seem to work.

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by sftim** [comment]
@ponessa: it sounds like you were able to install `kubectl` but then weren't able to connect to a particular cluster.
Have I got that right?
