### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by zimmerab** [kubernetes/website#15482]
**This is a Bug Report**

**Problem:**
![image](https://user-images.githubusercontent.com/15383326/61560064-d928e980-aa30-11e9-9c6d-4476679dcb03.png)
I am unsure how to edit the kube-apiserver. If I go to the description of the kube-apiserver it only shows commands. How do I edit my cluster in azure aks?

**Proposed Solution:**
 Show how to edit the kube-apiserver. Also for multiple cloud provider likes azure, google, and amazon.

**Page to Update:**
https://kubernetes.io/...
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**Comment by sftim** [comment]
#15864 looks like a close match / duplicate

**Comment by sftim** [comment]
I reckon:
/priority important-longterm
