### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/turnkey/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15499]
**This is a Bug Report**, ish

**Problem:**
From its URI https://kubernetes.io/docs/setup/production-environment/turnkey/ looks like it should be an overview of turn-key cloud solutions, but in fact describes a specific vendor.

**Proposed Solution:**
Add an overview page for turn-key cloud solutions

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/turnkey/

**Additional Information:**
/priority backlog

**Comment by prankul88** [comment]
Thanks for bringing this. To add on to, the other turnkey solutions must also be documented Eg. AKS and GKE.

**Comment by sftim** [comment]
Since I logged this, PR #15892 is (almost) in place to clarify the project's position on 3rd party content.
