### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by c00** [kubernetes/website#15492]
This is general feedback on installing minikube: 

Preface: Devs will want to install minikube to test or develop locally. For many devs, this will be their first encounter with k8s, so having documentation that is as clear and straight forward as possible is really helpful. (Consider Dockers documentation, that gets you up and running in a few simple foolproof steps.) I understand that the below are not all Kubernetes' responsibility, however these improvements would really help lower the bar to start using minikube and k8s.

Consider having hypervisor specific install steps and basic troubleshooting. Starting minikube with kvm requires a different flag than with virtualbox. These flags aren't documented on the install page.

When using KVM, there should be some mention about docker-machine and the corresponding kvm driver being needed. I couldn't figure out how to get those installed, so I gave up on kvm. Links to guides on how to get KVM working on specific distros would be helpful.

A link to a proper guide to install virtualbox on common distros such as Ubuntu would be very useful. (I could not get virtualbox to work and gave up on this too.)

Finally I gave the `--vm-driver=none` flag a go, but this needs sudo rights (as it attempts to create or edit binaries in `/usr/bin`). A mention of the need for sudo rights and a justification (i.e. what is added or updated) would be helpful. 

The `--vm-driver=none` flag can use more general documentation, like what the components are that are being run on the host.

**Comment by sftim** [comment]
Valid and relevant feedback.
/language en
