### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by Prodian0013** [kubernetes/website#15503]
**This is a Bug Report**

Incorrect CRIO yum repository for Centos/RHEL

**Problem:**
CRI-O section for Centos/RHEL 7.4+ tab has incorrect yum repository to match Kubernetes 1.15 version.

**Proposed Solution:**
Update the Centos/RHEL 7.4+ tab under the CRI-O section with the correct yum repository with a supported & working version of CRIO 1.15 rpms for Kubernetes 1.15 version.

**Page to Update:**
https://kubernetes.io/...

1.15

**Comment by sftim** [comment]
Thanks for noting this @Prodian0013
/language en

**Comment by sftim** [comment]
Fixed in #15708
/close
