### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by amanfrinati** [kubernetes/website#15502]
When I tried from `zsh` the step1 of Linux manual installation:

```curl -LO https://storage.googleapis.com/kubernetes-release/release/$\(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt\)/bin/linux/amd64/kubectl```

I get this error

> <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl</Details></Error>

I fixed the command with `curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl`

Probably, it's a problem with copy/paste

**Comment by amanfrinati** [comment]
Or this command `curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl`

**Comment by sftim** [comment]
That looks like something that needs fixing, right enough.
/language en

**Comment by thecrudge** [comment]
Not sure who corrected it, but its been corrected.

/close
