### ISSUE TITLE
Issue with k8s.io/docs/setup/learning-environment/minikube/

### ISSUE THREAD

**Issue by oswee** [kubernetes/website#15517]
**Problem:**
In Minikube Quickstart section step No.2 sample command is

```sh
kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
```
but in console it returns bit newbie confusing error:

```sh
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
```

**Proposed Solution:**
I think example command should be updated to:

```sh
kubectl run --generator=run-pod/v1 hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
```

**Page to Update:**
https://kubernetes.io/docs/setup/learning-environment/minikube/

**Comment by RA489** [comment]
@oswee Thanks for filing this issue.

**Comment by RA489** [comment]
@oswee 

> kubectl run --generator=run-pod/v1 hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
This command creates the pods directly rather than creating the deployments. wdyt?

>

**Comment by RA489** [comment]
duplicate of https://github.com/kubernetes/website/issues/15728
