### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by rlaferla** [kubernetes/website#15512]
**This is a Bug Report**

**Problem:**

 kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/kubernetes-bootcamp created

**Proposed Solution:**

N/A

**Page to Update:**
https://kubernetes.io/...

<Kubernetes Version:>
1.15.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sftim** [comment]
It's the _DEPRECATED_ that's the problem, right?
/language en

**Comment by BenHall** [comment]
Sorry for the delay on this. We thought it had a larger impact than it did.

The fix was applied in https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/839fc4c2160f821194418d16bf14c1cde9512cb5

**Comment by sftim** [comment]
I'm happy to 
/close
