### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/events-stackdriver/

### ISSUE THREAD

**Issue by nroose** [kubernetes/website#15511]
**This is a Bug Report**

**This page has hidden text about scaling but nothing that is visible about scaling:**

**Proposed Solution:**
Please either make that text visible or take it off the page so that this page won't show up when I search for scaling.
**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver/

**Comment by sftim** [comment]
Seems reasonable. I don't suppose you'd have the time to submit a pull request that fixes the issue you spotted, @nroose? (It looks like an easyish fix).

/language en

**Comment by thecrudge** [comment]
@nroose I have gone over the stackdriver page and do not see any hidden text in the markdown, can you please point it out directly.

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
