### ISSUE TITLE
Markdown translation to html formatting is off when markdown blockquote used

### ISSUE THREAD

**Issue by JasonHaley** [kubernetes/website#15526]
**This is a Bug Report**

**Problem:**
It looks like the markdown translation to html is not closing the blockquote when the markdown blockquote is used instead of the shortcode.

The formatting is off from the markdown:
[https://github.com/kubernetes/website/blob/master/content/en/blog/_posts/2019-07-23-get-started-with-kubernetes-using-python.md](https://github.com/kubernetes/website/blob/master/content/en/blog/_posts/2019-07-23-get-started-with-kubernetes-using-python.md)

and the html:
[https://kubernetes.io/blog/2019/07/23/get-started-with-kubernetes-using-python/](https://kubernetes.io/blog/2019/07/23/get-started-with-kubernetes-using-python/)

**Proposed Solution:**
I can modify the blog post to use the note shortcode instead of the blockquote. 

Does someone more experienced with the markdown used in the blog think that is the problem?

**Page to Update:**
https://kubernetes.io/blog/2019/07/23/get-started-with-kubernetes-using-python/

**Comment by thecrudge** [comment]
@JasonHaley Could this potentially be a browser issue? Im unable to replicate, looks good

**Comment by JasonHaley** [comment]
This looks fixed now, it can be closed.

**Comment by thecrudge** [comment]
Thanks @JasonHaley 

/close
