### ISSUE TITLE
Documentation should explicitly mention which values are required/optional

### ISSUE THREAD

**Issue by llamasoft** [kubernetes/website#15536]
**This is a Feature Request**

Currently the generated API documentation doesn't clearly state which values are required and which values are optional.

For example, every field in [Deployment](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#deployment-v1-apps) is required but almost every field in [PodSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podspec-v1-core) is optional.  Neither of these are explicitly stated.

**Why is this needed**

The Kubernetes API is complicated enough as is.  If you're creating a Kubernetes object from scratch it's nearly impossible to tell what's required and what's not.

**Comments**

Which fields are required and which are optional [can be definitively determined](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required).  It should be possible to percolate the "+optional" tag from the [api source code](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api) to the documentation.

**Comment by thecrudge** [comment]
/assign @thecrudge 

Thanks for the issue @llamasoft . I tend to agree with your judgement. Let me see what I can do to get the discussion going.

**Comment by tengqm** [comment]
There is no clear path to get this solved in the short/middle term. Consider the metadata.name field as an example. Is it required or not? It is required when 1) generateName is not specified; 2) you are creating a new resource. It is optional when you are doing a PUT or PATCH on the same resource. It is always there when you are doing a GET. The sad thing is that this field is implemented as a shared, nested struct for all resources as an object metadata. Simply adding a `+optional` in the source code would not be feasible. Put it differently, generating the swagger spec out of source code is a wrong approach for Go.
