### ISSUE TITLE
k8s.io/docs/concepts/workloads/ essentially blank

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15539]
**This is a Bug Report**

**Problem:** The page at https://kubernetes.io/docs/concepts/workloads/ is pretty much blank in terms of actual page content.

**Proposed Solution:**
Reorganise [/docs/concepts/workloads/](https://kubernetes.io/docs/concepts/workloads/)

#15373 includes a sketch of what changes I think are right here (that's just my opinion of course).

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/

/language en

**Comment by sftim** [comment]
Also see #18599 and #19697

**Comment by gavinfish** [comment]
I think this problem is not only for `workloads`. Other page like https://kubernetes.io/docs/concepts/storage/ just show the content of https://kubernetes.io/docs/concepts/storage/volumes/. Some categories do not have overview pages at all.

**Comment by sftim** [comment]
Duplicated by #20714

**Comment by prasadkatti** [comment]
This seems to happen when the first item in a section/list page is itself a list.

**Comment by sftim** [comment]
#20874 is likely to fix this, BTW

**Comment by sftim** [comment]
Fixed by #20874 
/close
