### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by GauravAjaySingh** [kubernetes/website#15553]
**Page to be fixed:** https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Problem:**
Interactive terminal is not working. the  error message being displayed since yesterday is:

The content owner's account has reached capacity. Please try again in 10 minutes

<img width="985" alt="Screen Shot 2019-07-27 at 7 51 16 PM" src="https://user-images.githubusercontent.com/48844734/62001548-efc1e700-b0a7-11e9-9b7f-05d375f644d8.png">

**Comment by thecrudge** [comment]
Hi @GauravAjaySingh, can you please verify that this is still an issue? When I visit the link, everything loads correctly
