### ISSUE TITLE
Can not access the application running (Kubernetes boot-camp)

### ISSUE THREAD

**Issue by taibc** [kubernetes/website#15554]
**This is a Bug Report**

**Error request http to application running (boot-camp)**

When I access the link: http://localhost:8001/api/v1/namespaces/default/pods/kubernetes-bootcamp-5b48cfdcbd-jzvk8/proxy/. I got below error

> Error: 'dial tcp 10.40.0.2:8080: connect: no route to host'
> Trying to reach: 'http://10.40.0.2:8080/'

The pod/deployment is running, if I try the link: http://localhost:8001/api/v1/namespaces/default/pods/kubernetes-bootcamp-5b48cfdcbd-jzvk8

There is no error:

> kind	"Pod"
apiVersion	"v1"
metadata	
name	"kubernetes-bootcamp-5b48cfdcbd-jzvk8"
generateName	"kubernetes-bootcamp-5b48cfdcbd-"
namespace	"default"
selfLink	"/api/v1/namespaces/default/pods/kubernetes-bootcamp-5b48cfdcbd-jzvk8"
uid	"6b43b47f-b179-4b89-a75f-9246144bc69b"
resourceVersion	"76467"
creationTimestamp	"2019-07-28T03:02:09Z"
labels	
pod-template-hash	"5b48cfdcbd"
run	"kubernetes-bootcamp"
ownerReferences	
0	
apiVersion	"apps/v1"
kind	"ReplicaSet"
name	"kubernetes-bootcamp-5b48cfdcbd"
uid	"ff17f2a2-e528-4afd-a240-4b12bb4636e6"
controller	true
blockOwnerDeletion	true
spec	
volumes	
0	
name	"default-token-vtphv"
secret	
secretName	"default-token-vtphv"
defaultMode	420
containers	
0	
name	"kubernetes-bootcamp"
image	"gcr.io/google-samples/kubernetes-bootcamp:v1"
ports	
0	
containerPort	8080
protocol	"TCP"
resources	{}
volumeMounts	
0	
name	"default-token-vtphv"
readOnly	true
mountPath	"/var/run/secrets/kubernetes.io/serviceaccount"
terminationMessagePath	"/dev/termination-log"
terminationMessagePolicy	"File"
imagePullPolicy	"IfNotPresent"
restartPolicy	"Always"
terminationGracePeriodSeconds	30
dnsPolicy	"ClusterFirst"
serviceAccountName	"default"
serviceAccount	"default"
nodeName	"worker-node1"
securityContext	{}
schedulerName	"default-scheduler"
tolerations	
0	
key	"node.kubernetes.io/not-ready"
operator	"Exists"
effect	"NoExecute"
tolerationSeconds	300
1	
key	"node.kubernetes.io/unreachable"
operator	"Exists"
effect	"NoExecute"
tolerationSeconds	300
priority	0
enableServiceLinks	true
status	
phase	"Running"
conditions	
0	
type	"Initialized"
status	"True"
lastProbeTime	null
lastTransitionTime	"2019-07-28T03:02:11Z"
1	
type	"Ready"
status	"True"
lastProbeTime	null
lastTransitionTime	"2019-07-28T03:24:02Z"
2	
type	"ContainersReady"
status	"True"
lastProbeTime	null
lastTransitionTime	"2019-07-28T03:24:02Z"
3	
type	"PodScheduled"
status	"True"
lastProbeTime	null
lastTransitionTime	"2019-07-28T03:02:09Z"
hostIP	"192.168.142.130"
podIP	"10.40.0.2"
startTime	"2019-07-28T03:02:11Z"
containerStatuses	
0	
name	"kubernetes-bootcamp"
state	
running	
startedAt	"2019-07-28T03:24:02Z"
lastState	
terminated	
exitCode	137
reason	"Error"
startedAt	"2019-07-28T03:03:00Z"
finishedAt	"2019-07-28T03:21:37Z"
containerID	"docker://8421c448557d4157f9f39df238a43da19c0c3d32eccf049b72446aab00280db8"
ready	true
restartCount	1
image	"gcr.io/google-samples/kubernetes-bootcamp:v1"
imageID	"docker-pullable://gcr.io/google-samples/kubernetes-bootcamp@sha256:0d6b8ee63bb57c5f5b6156f446b3bc3b3c143d233037f3a2f00e279c8fcc64af"
containerID	"docker://dd9cd073eb3dbc4e8cb0a7aa5d50e55e26f271e588322e1b21df36b85220324e"
qosClass	"BestEffort"

**Proposed Solution:**

**Kubernetes version**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by thecrudge** [comment]
@taibc Can you provide specifics about the documentation you are working from? 

/triage support
/assign @thecrudge

**Comment by taibc** [comment]
@thecrudge : I worked as the guide: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by thecrudge** [comment]
@taibc 

I do not see an issue here. The module correctly describes how to deploy an application without error. Keep in mind that you need to start the proxy, in another window. 

$ echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"; kubectl proxy
Starting Proxy. After starting it will not output a response. Please click the first Terminal Tab
Starting to serve on 127.0.0.1:8001

Once you do that, you can then curl the endpoint without issue:

$ curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-5b48cfdcbd-pr89q | v=1 

/close
