### ISSUE TITLE
Adding --cgroup-driver flag to etcd documentation

### ISSUE THREAD

**Issue by CorfitzMe** [kubernetes/website#15557]
**This is a Feature Request**
Update on website request. 

**What would you like to be added**
When settings up a cluster for etcd following this part: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster It would be worth noting, that if one installs Docker following this documentation: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker, a cgroup-driver flag should be added to the `20-etcd-service-manager.conf` file.

```
cat << EOF > /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
[Service]
ExecStart=
ExecStart=/usr/bin/kubelet --address=127.0.0.1 --pod-manifest-path=/etc/kubernetes/manifests  --cgroup-driver=systemd
Restart=always
EOF
```

**Why is this needed**
In the documentation for installing Docker, it is clearly stated that cgroup driver `systemd` should be specified, but since kubelet defaults to `cgroupfs`, the flag should be added to avoid common errors of kubelet and docker not using same cgroup driver.

```
Changing the settings such that your container runtime and kubelet use systemd as the cgroup driver stabilized the system. Please note the [native.cgroupdriver=systemd] option in the Docker setup below.
```

**Comments**
I am aware of the deprecation warning. If the flag should be omitted from the doc, I would suggest some info on how to set up the config file for kubelet to use `systemd` according to future requirements.

**Comment by neolit123** [comment]
/sig cluster-lifecycle
@CorfitzMe thanks for logging the ticket.
given we are skipping the kubeadm init "kubelet-start" phase, we don't detect the docker cgroup driver.

PRs welcome to update the document in question.
