### ISSUE TITLE
Document publishNotReadyAddresses in Service spec

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/website#1556]
currently it's only documented through petset examples: 
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/petset/zookeeper/service.yaml#L6

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/25283

**Comment by jaredbhatti** [comment]
Where should this content live and what should it look like?

**Comment by spicysomtam** [comment]
The original posters link is now dead. I found it referred to [here](https://github.com/kubernetes/contrib/tree/master/peer-finder).

However, I find annotation documentation a little hard to find anyway. Any help/tips? Suppose I am saying can it better docuemented?

**Comment by enisoc** [comment]
With 1.8, we are promoting this from an alpha annotation to a beta field. That should help, since it will be documented in the auto-generated API reference:

https://github.com/kubernetes/kubernetes/pull/49061/files

/assign @kow3ns

**Comment by tengqm** [comment]
/close

The field is now documented as a field: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#servicespec-v1-core
