### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/turnkey/tencent/

### ISSUE THREAD

**Issue by yunxji** [kubernetes/website#15565]
**This is a Bug Report**

**Problem:The format of this article is wrong, but I don't know how to fix it.**

**Proposed Solution:Please give some suggestions or modify directly**

**Page to Update:https://kubernetes.io/docs/setup/production-environment/turnkey/tencent/**

Can you pay attention to this issue? @tengqm

**Comment by sftim** [comment]
Think this is fixed now.
/close
