### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/storage-classes/

### ISSUE THREAD

**Issue by DraganBocevski** [kubernetes/website#15587]
**This is a Bug Report**

**Problem:**
Missing information about allowVolumeExpansion option.

**Proposed Solution:**
At least include a reference to this page https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

You can also add this option to the corresponding vendors that support it.

**Page to Update:**
k8s.io/docs/concepts/storage/storage-classes/

**Comment by sNathan13** [comment]
I can take this.

**Comment by thecrudge** [comment]
thanks @sNathan13
