### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by tapialuism** [kubernetes/website#15586]
**This is a Bug Report**

I receive the message failed to connect to localhost........

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

![image](https://user-images.githubusercontent.com/43013736/62153208-ebb8e380-b2b8-11e9-90fa-8de6063dba69.png)

**Comment by BenHall** [comment]
Being unable to connect to 8001 happens when kubectl proxy hasn't been started.

@tapialuism Can you remember if you started the proxy?
