### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by AdelinGhanaem** [kubernetes/website#15580]
**This is a Bug Report**

After waiting for more than 5 minutes, the command-line starts but not pods or other resources available to continue with the tutorial

**Problem: After waiting for more than 5 minutes, the command-line starts but not pods or other resources available to continue with the tutorial**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Very sorry about the issue. We've made some changes and upgraded to v1.13 of Minikube which will hopefully improve performance.

**Comment by sftim** [comment]
@AdelinGhanaem does this seem to be fixed?
