### ISSUE TITLE
Insufficient documentation for cluster autoscaler

### ISSUE THREAD

**Issue by jaypipes** [kubernetes/website#15585]
**This is a Feature Request**

The cluster autoscaler subproject is not covered very well in the official Kubernetes documentation. In fact, besides a couple mentions in blog articles, really the only mention of cluster autoscaler in the official docs seems to be here:

https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/

**What would you like to be added**

Documentation should be added that covers the overall design of the cluster autoscaler, how it works, what its current limitations are and any constraints that it puts on a deployment, etc.

In addition, this documentation should explain the difference between internal concepts to the cluster autoscaler like a "NodeGroup" and similar concepts in cloud providers (Managed Instance Group in GCE, AutoScaleGroup in EC2, MachineSet in cluster-api, etc..)

**Why is this needed**

The cluster autoscaler source project has little documentation besides an FAQ here:

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

We should have some non-cloud-provider-specific documentation that describes how to use cluster autoscaler and how it fits into the overall autoscaling universe.

**Comment by jaypipes** [comment]
I'd like to work on this documentation, fwiw. I'm not a member of kubernetes, though, so cannot self-assign.

**Comment by sftim** [comment]
/priority backlog

Is this also relevant to SIG Cluster Lifecycle?

**Comment by jaypipes** [comment]
> /priority backlog
> 
> Is this also relevant to SIG Cluster Lifecycle?

Nah, not too much. Mostly it was a placeholder for me to remind me to clean up the docs referencing autoscaler :)
