### ISSUE TITLE
make section (headlines) easily linkable

### ISSUE THREAD

**Issue by thkoch2001** [kubernetes/website#1559]
This is a Feature Request.

User Story: Colleague asks questions on IRC. I found the right doc and section to answer the question. I want to quickly have a link to the exact section to paste into IRC.

Solution Proposal:
- Make all headlines links to themselves.
- Alternatively show a link icon next to every headline that links to the headline.
- Alternatively show the link icon only on mouse hover.

**Comment by sftim** [comment]
@thkoch2001 it seems easy enough to link to sections on the current docs

Do you feel this is fixed?
