### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by guludo** [kubernetes/website#15599]
**This is a Bug Report**

**Problem:**

The second paragraph of https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ contains the following:

> In order for Docker containers to communicate across nodes, there must be allocated ports on the machine’s own IP address, which are then forwarded or proxied to the containers. This obviously means that containers must either coordinate which ports they use very carefully or ports must be allocated dynamically.

However, that's not an issue if we use docker swarm mode is it?

**Proposed Solution:**
Not sure if that information should stay as is in the documentation.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by juandiegopalomino** [comment]
/triage support
/sig cluster-lifecycle
I don't think that Kubernetes can work in harmony with docker swarm as a general principal as K8s attempts to orchestrate the containers itself. I don't know enough about the internals to give a definite answer, but I think @kubernetes/sig-cluster-lifecycle can help.

**Comment by guludo** [comment]
@juandiegopalomino Hi! Thanks your input on this :-)

I'm not really interested in making k8s work with docker swarm. I'm rather concerned whether the quoted information is accurate regarding the current version of Docker.

**Comment by neolit123** [comment]
/remove-sig cluster-lifecycle
/sig network node

try asking at the #sig-network or #sig-node slack channels.
