### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/ -- "minikube login"

### ISSUE THREAD

**Issue by wwilliams-ea** [kubernetes/website#15603]
**This is a Bug Report**

C:\WINDOWS\system32>minikube start
* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing virtualbox VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
* Relaunching Kubernetes v1.15.0 using kubeadm ...
* Verifying: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"

**Problem:**
The VirtualBox minikube console displays:
Welcome to minikube
minikube login:

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@wwilliams-ea can you copy paste the exact commands you executed.

**Comment by RA489** [comment]
It will be great if could provide a bit more detail about the issue you are facing.

**Comment by wwilliams-ea** [comment]
I already had VirtualBox installed.
I ran:
**choco install minikube kubernetes-cli**

and then
**minikube start**

The command window showed:
**
* minikube v1.2.0 on windows (amd64)
* Downloading Minikube ISO ...
 129.33 MB / 129.33 MB [============================================] 100.00% 0s
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
* Downloading kubeadm v1.15.0
* Downloading kubelet v1.15.0
* Pulling images ...
* Launching Kubernetes ...
* Verifying: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"
**

... while the Vbox-minikube console shows:
**Welcome to minikube
minikube login:** 

What login?  Is there a default login and password?  I am looking at the documentation and haven't found any info on this yet.

Someone posted the same issue on stackoverflow...
https://stackoverflow.com/questions/52633267/minikube-on-windows-and-hyperv-stuck-on-prompt-minikube-login)
