### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by oldmanyoung** [kubernetes/website#1561]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubernetes Interactive Tutorial, 2: Deploying an App, Step 3
Supposed to create a proxy with **kubectl proxy** command. I type the command and the CLI just hangs at "Starting to serve on 127.0.0.1:8001", never returns prompt.

**Proposed Solution:**
?

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by steveperry-53** [comment]
I will update the docs to say that after starting the proxy server, you have to click + to open a new terminal.

**Comment by BenHall** [comment]
@steveperry-53 Please let me know if you need help with that. I'm not sure if you have access to the Katacoda scenarios.

**Comment by steveperry-53** [comment]
@BenHall, Yes, I'll need help with this. I don't know how to edit the text in the Katacoda scenarios.

**Comment by steveperry-53** [comment]
@pwittrock, I've had several requests to change the text in the interactive sessions. Can you help me figure out how to do that?

**Comment by BenHall** [comment]
@pwittrock @steveperry-53 Sorry, I've had this on my TODO for a while. 

Two ways:
  1) We could create https://github.com/kubernetes/labs which would store the labs markdown files
  2) I can commit the files to the repository root

The first way would mean that the Katacoda labs can automatically be synced when changes are made to master.

**Comment by pwittrock** [comment]
1. Sounds good to me

**Comment by BenHall** [comment]
@pwittrock If you could create the repo, or let me know how to organise it, and give me access then I can configure the webhooks, and commit the content. Thanks for your help

**Comment by pwittrock** [comment]
Good idea Ben.

@jaredbhatti do you have permissions to create repos?

**Comment by jaredbhatti** [comment]
Sorry for the late reply.  I don't have permission to create a repo.  I think Brian Grant would be the right person to ask.

**Comment by vhosakot** [comment]
I also saw this issue today and observed that `kubectl proxy` blocks and runs in the foreground and we cannot continue with the tutorial.  Hence, I used `&` and ran it in the background, and then, I was able to run all the subsequent commands successfully.

`kubectl proxy &`

Let me know if can I submit a PR to add `&` for the command `kubectl proxy` in https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/.

**Comment by heckj** [comment]
@BenHall pointed me at the repo with the content, and I've made a PR to put in additional content to help explain the expectation around and usage of `kubectl proxy`: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/2

**Comment by BenHall** [comment]
The PR has now been merged and is live on the site.

**Comment by heckj** [comment]
Thanks @BenHall - I'll run through it and see how it looks played out...

**Comment by heckj** [comment]
2nd PR up make the tutorial flow more smoothly and consistently across modules: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/3

**Comment by tengqm** [comment]
pls feel free to reopen is there are further actions needed.
