### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ exclude=kube* removed

### ISSUE THREAD

**Issue by vitality1987** [kubernetes/website#15618]
**This is a Bug Report**

**Problem:**
https://github.com/kubernetes/website/pull/15111 removed "exclude=kube*" from the CentOS kubernetes.repo file. But in the documentation the yum install command still uses "--disableexcludes=kubernetes".

I think this PR has to be reverted as with this change kubectl, kubelet and kubeadm would be updated automatically during OS update which is undesirable in a production environment. 

**Proposed Solution:**
Revert PR https://github.com/kubernetes/website/pull/15111

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by juandiegopalomino** [comment]
@mhamdisemah 
/sig docs
/kind bug

**Comment by neolit123** [comment]
@cobalt293 
^ please see this request for revert of https://github.com/kubernetes/website/pull/15111
which fixed an issue your reported.

cc @mhamdisemah

**Comment by vitality1987** [comment]
@cobalt293
your _yum install_ command lacked the _--disableexcludes=kubernetes_ option

cc @mhamdisemah

**Comment by sftim** [comment]
This seems like a valid report and one that could land cluster operators in trouble.
/priority important-soon
