### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by TeejIBM** [kubernetes/website#15636]
**This is a Bug Report**

Local host:8001 is not accessible.

Tried with Safari on macOS and iPad, both keep switching to terminal 1 and entering command.  Typing out command does not work on either terminal.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by juandiegopalomino** [comment]
@TeejIBM I think I figured out your issue: please try to execute `kubectl proxy` on one of the terminals, and continue w/ the commands on the other. It does not seem to do all the steps by itself naturally.

**Comment by TeejIBM** [comment]
Ah, you're right, it did not accept the second command, and I did not realize that when I reported this.  

Perhaps the instruction needs to split the two commands?

**Comment by TeejIBM** [comment]
/close
 
                                                                                                                                                                                         T.J. Griesenbrock                        Solution Provider
                        Phone: +1 (480) 336-9806                        SMS: +1 (602) 377-7673                        teej@ibm.com                                                                                                                        
 
 
 
----- Original message -----From: fejta-bot <notifications@github.com>To: kubernetes/website <website@noreply.github.com>Cc: "T.J." <teej@ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [kubernetes/website] Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/ (#15636)Date: Mon, Nov 4, 2019 12:54 
Issues go stale after 90d of inactivity.Mark the issue as fresh with /remove-lifecycle stale.Stale issues rot after an additional 30d of inactivity and eventually close.
If this issue is safe to close now please do so with /close.
Send feedback to sig-testing, kubernetes/test-infra and/or fejta./lifecycle stale
