### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by kpaschen** [kubernetes/website#15646]
I went through scenario 2 but the pod status is stuck in ImagePullBackOff. I stopped after about 8 minutes. Perhaps the image name needs a fix?

Also, clicking on the blue "open an issue" button at the bottom takes me back to the beginning of the tutorial and throws away all my progress, and it does not even open an issue.

**Comment by juandiegopalomino** [comment]
/triage support
/triage not-reproducible
I'm unable to replicate your first issue, but it sounds like it could be a copy/paste issue with the name of the image as the original image is fine, but you'll get the error you mentioned if you place the wrong image.
I'm not certain about how to fix the button though

**Comment by kpaschen** [comment]
Thanks for looking! I did get it to work and then I couldn't find this issue again to update it.
