### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by patrocinio** [kubernetes/website#15647]
**This is a Bug Report**

**Problem:**
This task should not refere to Katacoda or Play with Kubernetes, as it is describing how to configure Ingress on a Minikube environment, and these environments don't run minikube.

**Proposed Solution:**
Remove the reference to Katacoda and Play with Kubernetes

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@patrocinio can you please provide a bit more detail on issue you getting?

**Comment by patrocinio** [comment]
Hello @RA489 This task is intended to run on a minikube environment, including some steps that are exclusive to minikube:

``
minikube addons enable ingress
``

The introduction ('Before you begin' section) is the generic one, saying to run it either in minikube or one of the playground environment (Katacoda or Play with Kubernetes). However, this task can't be run in the playground environment, as the minikube commands are not available.

Thank you

**Comment by RA489** [comment]
@patrocinio IIUC Playground also has minikube environment so you can easily use minikube commands over there. when you launch the playground terminal it gonna set up minikube environment for you by executing `minikube start` command
