### ISSUE TITLE
No obvious use cases for static pods instead of daemonsets.

### ISSUE THREAD

**Issue by rossigee** [kubernetes/website#15650]
**Problem:**
The 'static pods' page does not explain what static pods are for specifically. It simply explains how to use them.

Right at the top of the page it points out that for most cases you should be using Daemonsets to run certain pods on all nodes, and the Daemonsets page itself has a decent list of common use cases for daemonsets, but i can't find anywhere that explains where static pods would be a better idea.

I'm sure there must be a reason for static pods to exist, as it constitutes part of the CKA exam 'Scheduling' section, but I have yet to find (by googling) any real-world examples of people using it or good reasons to use it instead of a daemonset, and it would just be great to know why it's there at all :)

**Proposed Solution:**
Please explain what static pods are there for, and where you'd want to use static pods instead of a daemonset.

I'm happy to try wording it concisely into a PR to enlighten future readers if someone can explain it to me briefly in this ticket, or point me in the right direction :)

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/static-pod/

**Comment by sftim** [comment]
Good point!

One thing you can use static pods for is to have kubelet run your control plane inside a set of pods.
Have a look at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/ to see some diagrams that aim to illustrate this.
