### ISSUE TITLE
Issue with k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/

### ISSUE THREAD

**Issue by liys87x** [kubernetes/website#15668]
**This is a Bug Report**

**Problem:**
The *certificate management documentation* link is 404.
Current is "https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/docs/tasks/administer-cluster/kubeadm/kubeadm-certs"
It should be "https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs"

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/

**Comment by sftim** [comment]
Good spot @liys87x 
/kind bug
