### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod/

### ISSUE THREAD

**Issue by mf-lit** [kubernetes/website#15669]
The pods documentation states the following in regards to pod termination:

```
The container is sent the TERM signal. Note that not all containers in the Pod will receive the TERM signal at the same time and may each require a preStop hook if the order in which they shut down matters.
```

This isn't actually true, at least it isn't with docker. A `docker stop` is sent to the container and it's up to docker to decide what to do, which by default is send a TERM but can be changed if STOPSIGNAL is set in the Dockerfile. This difference is important.

I'd edit the documentation directly, but I've no idea how kubernetes behaves with container runtime backends other than docker.

**Comment by sftim** [comment]
Good spot @mf-lit 
/kind bug
