### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

### ISSUE THREAD

**Issue by lucaspinto** [kubernetes/website#15671]
My expectations may have been wrong, but I was expecting to find a configuration example or an example file or a list of configurable variables on this page.

**Comment by thecrudge** [comment]
/assign

Can you explain more exactly what you were expecting? Maybe we can be a bit more clear in how we link to the Configuring Access to Multiple Clusters that goes more in depth to the kubeconfig. 

See this link: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

**Comment by sftim** [comment]
Also, I think:
/sig cli

**Comment by sftim** [comment]
I took a look at https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

This is filed in a Concept section. The page has conceptual information as well as some text which, to me, feels much more like Task text.
Both [Define clusters, users, and contexts](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts) and [Merging kubeconfig files](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#merging-kubeconfig-files) have a Task feel to them.

To help readers encountering this page, how about the following structure:
- overview, page outline
- recap of what `kubectl` is, mention that other applications also use this file
- show an example configuration
- signpost readers to a (new) Task page about making a kubectl file for a single cluster, single context situation.
  - Base this on [Define clusters, users, and contexts](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts).
- briefly explain `KUBECONFIG` environment variable
- further reading
  - `kubectl` / [`kubectl config`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config).
  - kubeconfig format reference (new page)
  - Task page about configuring for multiple clusters
  - (new) Task page about configuring for multiple contexts, eg a privileged role and a normal one

**Comment by lucaspinto** [comment]
@thecrudge the page you linked me to indeed contained the information I was looking for. I guess I did not land on it because "in my head" I was not trying to access multiple clusters but just one. Now, I realize that having already a running cluster locally, technically, I was using multiple clusters. Thank you for your support.

To give more context about my expectations: I've used a service that launched a kubernetes cluster for me and I wanted to use kubeclt to communicate with it and I knew I could use a kubeconfig file. The title of the page seemed to indicate that I could found a template for a kubeconfig file.

I hope that I could help you improve the doc.

**Comment by thecrudge** [comment]
@lucaspinto Absolutely, glad I could help and we really appreciate your input. Would you be interested and taking a shot at the issue that @sftim opened to address your issue?

**Comment by lucaspinto** [comment]
@thecrudge I am sorry I haven't responded sooner. I'll try when time allows!

**Comment by sftim** [comment]
I'm going to reopen this as it's still worth fixing. Issue #20967 reminded me that this is not yet fixed.
/remove-lifecycle rotten
