### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

### ISSUE THREAD

**Issue by pariminaresh** [kubernetes/website#15673]
**This is a Bug Report**

I want to verify the validity for all of my kube cluster certificates. I see `kubeadm alpha certs check-expiration` is a way to do that from kube docs. But thats really not working for me. RIght now I'm trying to use something `openssl x509 -enddate -noout -in ../apiserver.crt` but definitely would like to use `kubeadm` for all sorts of my cluster details. 

**Problem:**
```
$kubeadm alpha certs check-expiration
Commands related to handling kubernetes certificates

Usage:
  kubeadm alpha certs [command]

Aliases:
  certs, certificates

Available Commands:
  renew       Renews certificates for a Kubernetes cluster

Flags:
  -h, --help   help for certs

Global Flags:
      --log-file string   If non-empty, use this log file
      --rootfs string     [EXPERIMENTAL] The path to the 'real' host root filesystem.
      --skip-headers      If true, avoid header prefixes in the log messages
  -v, --v Level           number for the log level verbosity

Use "kubeadm alpha certs [command] --help" for more information about a command.
```

I don't see `check-expiration` in the available commands. Does this work for certain kubeadm versions? If so, listing the versions could be helpful. if not please let me know if there is anything I'm missing here to get this working.

**Proposed Solution:**
 - Possibly update the docs with more information on how exactly this `check-expiration` can be used if the existing docs miss anything here.
 - if this command is no longer supported, please suggest the alternative ways that can used.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/

 
```
$kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

Sorry if this is a spam and thanks in advance for your inputs.

**Comment by thecrudge** [comment]
This is a feature of 1.15, your kubeadm version is 1.14, please update and try again.

/close

**Comment by pariminaresh** [comment]
Thank you @thecrudge
