### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by dkumbhar** [kubernetes/website#15686]
**This is a Bug Report**
Unable to start minikube on Windows 10

**Problem:**
minikube start     * minikube v1.2.0 on windows (amd64)
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0805 21:45:37.280907   22032 start.go:559] StartHost: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

X Unable to start VM
* Error:         [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
* Advice:        Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
* Documentation: https://www.virtualbox.org/wiki/Downloads
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3784
  - https://github.com/kubernetes/minikube/issues/3776

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new
PS C:\Program Files\Git\mingw64\bin> minikube start --vm-driver=VirtualBox                                              * minikube v1.2.0 on windows (amd64)
* Creating VirtualBox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
* unsupported driver: VirtualBox

**Proposed Solution:**
Go to "Hyper-V Manager" in Windows. (Search from TaskBar)
Once in Hyper-V Manager go to "Virtual Switch Manager" on right panel
Select "New Virtual Network switch"
Select "External" for Network Type
Select Create Virtual Switch (name the switch "Primary Virtual Switch")
Click Apply the OK

After that open Powershell as admin (I got error with cmd) and run command:

minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"

After that you just run: minikube start

To check that all is in order run:
minikube status
minikube ip

Main Reference: https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/

v1.2.0

Update the Document to help windows 10 users install minikube correctly

**Comment by RA489** [comment]
@dkumbhar IIUC are trying to install minikube with hyperv as vm-driver without virtualbox right?
