### ISSUE TITLE
Discover the scope and requirements for implementing the Docsy Hugo template

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#15683]
- Start research in the [Docsy template](https://opensource.googleblog.com/2019/07/announcing-docsy-website-theme-for.html?m=1)

- Create a new GitHub issue describing the requirements and scope of work required to implement the template. (Make it easy for other stakeholders to understand the extent of the challenge and what's required to implement the template.)

- Get stakeholder input, then implement a solution. (Get everyone on board, then fix the problem. The template should be uniformly applied across the site with expected results.)

/sig docs
/priority important-soon
Assign to @aimeeu

**Comment by aimeeu** [comment]
/unassign
Zach is looking for a contractor to do the template change.

**Comment by aimeeu** [comment]
Would be nice to have a collapsible left menu, as requested in issue #16120
