### ISSUE TITLE
Link to logging conventions in /docs/reference/kubectl/cheatsheet.md broken

### ISSUE THREAD

**Issue by lyveng** [kubernetes/website#15701]
**This is a Bug Report**

**Problem:**
The link to logging conventions in [kubectl cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging) is broken.

**Proposed Solution:**
Update the links. Here is the PR - #15699 

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging

**Comment by RA489** [comment]
@lyveng Thanks! for raising this issue.
