### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

### ISSUE THREAD

**Issue by guludo** [kubernetes/website#15704]
**This is a Bug Report**

**Problem:**

It looks like the legend of the figure under `Services and Labels` is wrong - the purple cubes are representing containers whereas the legend refers to them as pods.

**Proposed Solution:**

My proposal the the legend:

- `<circle>` Pod
- `<purple cube>` Container
- `<hexagon>` Node

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

**Comment by thecrudge** [comment]
Hi @guludo , I think you make a good argument 

/sig docs
/help 
/assign
/priority awaiting-more-evidence

**Comment by sftim** [comment]
I had a look at this. To me it's clear the purple cubes represent Pods.

How can SIG Docs best make it clear to all readers that:
- these are indeed Pods
- it does not matter whether the Pods for `app=B` (or indeed `app=A`) consist of one or several containers
- Kubernetes manages Pods as the principal resource, not containers

?

**Comment by guludo** [comment]
I think keeping the purple cubes as Pods in that figure makes it inconsistent with the previous figures, where circles represent pods and the cubes represent containers ([here](https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/#pods-overview) for example). Additionally, note that, in the figure, the IP addresses are "attached" to the circles (which makes sense if one thinks of them as pods).

IMHO, consistency is important for a better reading experience...

**Comment by thecrudge** [comment]
In the example you provided it is explaining what a pod is with regards to containers (teal cube). In this context, Im inclined to agree with Tim that as far as kubernetes is concerned, a pod is the smallest unit of that kubernetes controls, not a container. Which is what the tutorial is concerned with. In this example, you're exposing a service on the pod. If the layer of abstraction you're suggesting were to be added to the tutorial, it may take away from tutorial itself, or cause confusion.

**Comment by sftim** [comment]
It sounds like it'd be a good idea to talk about Pods and, ideally, use a different symbol for Pods vs containers (not just a different color).

**Comment by guludo** [comment]
Hm. I think I get your point now, guys.

A reader that is following the tutorials from the beginning is very likely to associate the purple cube with a container, since cubes were used for containers in previous pages. As @sftim suggested, it would be better to use a different symbol for Pods. As a matter of fact, that symbol already exists - the circle.

Thus, one option, to keep the abstraction at the level of Pods, would be removing the cubes from the picture so as to avoid accidental association with containers.
