### ISSUE TITLE
Issue with /docs/admin/limitrange/

### ISSUE THREAD

**Issue by gjcarneiro** [kubernetes/website#1571]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

In the command `kubectl create -f docs/admin/limitrange/limits.yaml --namespace=limit-example`, I don't have this `docs/admin/limitrange/limits.yaml` file.

**Proposed Solution:**

Provide the contents of the file, or a valid link to download it.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
The referenced doc has been fixed. A quick search of all 'limits.yaml' file referenced in the text are properly fixed with a valid url.
