### ISSUE TITLE
Improvement for k8s.io/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/

### ISSUE THREAD

**Issue by yahoon** [kubernetes/website#15719]
Still need the doc about how to do this on a cluster installed by kubeadm

**Comment by thecrudge** [comment]
Hi @yahoon 

Unfortunately this is not a problem with the documentation itself, but that the documentation that exists is for a specific vendor platform. This is something that needs to be discussed. 

/sig docs

**Comment by aimeeu** [comment]
@yahoon 
The SIG Docs team decided to remove vendor-specific content from the Kubernetes documentation. See issue #15774 and #15576. This ElasticStack content is going to be removed as part of #15748.
