### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by ZamanOof** [kubernetes/website#15720]
Hello,
I'm not sure if it's can Called Bug,
when running the command on GIT
`kubectl exec -ti $POD_NAME bash
`Result:
`Unable to use a TTY - input is not a terminal or the right kind of file
`The solution : 
run it on **PowerShell**
On:
Windows env (10,7)
References:
https://github.com/microsoft/WSL/issues/2271
https://github.com/kubernetes/kubernetes/issues/37471
Best Regards

**Comment by thecrudge** [comment]
/sig windows

@kubernetes/sig-windows-misc can someone look at this?

@ZamanOof This brings up a good question as to whether or not we should have both powershell and gitbash represented. If so, then where does it end?

**Comment by sftim** [comment]
@ZamanOof do you have an idea about what should change about this webpage to make it work better for readers with Windows systems?

(I wonder if the simplest explanation is that these commands assume you're using Linux)
