### ISSUE TITLE
Contribute,Start Contributing page: Enhance 'Find something to work on' and 'Review docs pull requests' sections 

### ISSUE THREAD

**Issue by aimeeu** [kubernetes/website#15723]
**This is a Bug Report**

**Problem:**
People new to issues and pull requests in GitHub may need additional guidance on how to search, filter, and sort issues and PRs. Additionally, there is nothing on how to resolve conversations in a PR.

**Proposed Solution:**
(Check Intermediate and Advanced pages to prevent content duplication.)

- Perhaps create a new paragraph in _Improve existing content/Find something to work on_ that gives an example of how to search (move the info from the _Review docs pull request_ section). Link to relevant GitHub Help page for further info. In _Review docs pull request_ section, link back to search/filter/sort instructions.
     - https://help.github.com/en/articles/about-searching-on-github
     - https://github.com/kubernetes/website/labels
     - https://go.k8s.io/github-labels

-  _Find something to work on_ section - **add how to assign issues to yourself** (https://github.com/kubernetes/community/blob/master/contributors/guide/README.md#issue-assignment-in-github). "Leave a comment saying that you would like to work on the issue." - Emphasize using /assign so that GitHub knows the issue is assigned - this helps with searching, filtering, sorting etc.

-  _Submit a pull request_ add content addressing how to respond to reviewer change request on your PR https://help.github.com/en/articles/about-pull-request-reviews
    - add info on 3 conditions needed for merging (/approve, /lgtm, no blockers)

- _Intermediate_ page: enhance Work from a local clone with info on how to squash commits 

**Page to Update:**
https://kubernetes.io/docs/contribute/start/#review-docs-pull-requests
https://kubernetes.io/docs/contribute/intermediate/#work-from-a-local-clone

**Comment by thecrudge** [comment]
Im not sure if this should have the good first issue tag. The nature of the problem seems to require experience on resolving issues in Github.
