### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

### ISSUE THREAD

**Issue by verult** [kubernetes/website#15726]
**This is a Bug Report**

**Problem:**
The code snippet here limits `system-node-critical` and `system-cluster-critical` from being used outside `kube-system` namespace, but the documentation implies these priority classes can be used in *any* namespace:

"...and pod in any namespace can be configed as a critical pod by the following either way:..."

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by thecrudge** [comment]
Good catch, @verult , would like to submit a PR?
