### ISSUE TITLE
RBAC docs for "edit" default cluster role do not accurately represent its permissions

### ISSUE THREAD

**Issue by iloveicedgreentea** [kubernetes/website#15722]
**This is a Feature Request**

I am more than happy to make a PR if someone can point me in the right direction.

**What would you like to be added**
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles

The `edit` role states ```Allows read/write access to most objects in a namespace. It does not allow viewing or modifying roles or rolebindings.```

This is a little misleading because it suggests the user is prevented from privilege escalation. However, it is trivial for a user to just use this role to grab a SA token and pivot from there. The docs should clearly and accurately reflect the scope of this role, or even better, this role should disallow reading secrets.

**Comment by thecrudge** [comment]
Good catch
