### ISSUE TITLE
Issue with k8s.io/docs/home/supported-doc-versions/

### ISSUE THREAD

**Issue by nkoranova** [kubernetes/website#15739]
Hi! :sun_with_face: I have a question - do you gradually remove the old docs versions (or their static versions) as you move forward? We have a bunch of links in our docs, which point to your v1.10 docs that are now broken and I wonder if to simply change them to v1.11 links and how much of a temporary solution this would be. Thanks!

**Comment by thecrudge** [comment]
Yes, we do. I think we support the current version plus -4. So 1.15, 14, 13, 12, 11

@zacharysarah can keep me honest here.

**Comment by sftim** [comment]
Relevant to issue #15088
