### ISSUE TITLE
Add Helm course to the list of Kubernetes course

### ISSUE THREAD

**Issue by phcollignon** [kubernetes/website#15736]
**This is a Feature Request**
**What would you like to be added**

Please could you add this Helm course to the list of Kubernetes courses : 
[Packaging applications with Helm for Kubernetes] (Pluralsight)](https://www.pluralsight.com/courses/packaging-applications-helm-kubernetes)

**Why is this needed**
Useful to learn to use Helm and Kubernetes.

**Comment by sftim** [comment]
I'm not sure about this. Helm is a CNCF project but it's not itself part of Kubernetes, and this 3rd-party course seems to focus on Helm more than Kubernetes.

**Comment by phcollignon** [comment]
Well there is already an Helm course in the list ... "Helm Deep Dive with Hands-On Labs (Linux Academy)"  so why not this one ?

**Comment by thecrudge** [comment]
Hi @phcollignon 

We have updated the style guide recently. I believe this would fall under that umbrella, but only in a manner that links to the docs (possibly embeds them) from the website:

https://github.com/kubernetes/website/issues/15576

^^ See the new style guidelines
