### ISSUE TITLE
AzureDisk storage class parameters are incomplete

### ISSUE THREAD

**Issue by easimon** [kubernetes/website#15741]
**This is a Feature Request**

On https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk, the list of configuration properties for Azure Disks is incomplete. I found https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md for the new CSI driver and found the parameter `resourceGroup` documented there -- which was exactly what I was searching for. 

It seems that the "old" built-in AzureDisk provider supports this as well. I added that parameter to my storage class, and it created disks connected to that storage class in the specified resource group automatically. So the parameter is working, just not documented.

**What would you like to be added**

Something like this, in the existing AzureDisk section.

* resourceGroup:  specify the resource group in which azure disk will be created.Must be an existing resource group name. If unspecified, disk will be placed in the the same resource group as current k8s cluster

**Why is this needed**

Completeness of documentation

**Comment by mcurtiscmu** [comment]
I would like to work on this issue.

**Comment by sftim** [comment]
/priority backlog
@mcurtiscmu did you want to propose a fix for this?
