### ISSUE TITLE
Issue with patching 

### ISSUE THREAD

**Issue by RandySheriffH** [kubernetes/website#15757]
None of your examples seems to work:

kubectl patch deployment patch-demo --patch "$(cat patch-file.yaml)"
kubectl patch deployment patch-demo --patch 'spec:\n template:\n  spec:\n   containers:\n   - name: patch-demo-ctr-2\n     image: redis'

kubectl patch deployment patch-demo --patch "$(cat patch-file.json)"
kubectl patch deployment patch-demo --patch '{"spec": {"template": {"spec": {"containers": [{"name": "patch-demo-ctr-2","image": "redis"}]}}}}'

**Comment by RandySheriffH** [comment]
I could provide more details for sure ... but u ever tested patching with latest release?

**Comment by thecrudge** [comment]
Hi @RandySheriffH 

Please provide the page you are working from, the links to the tutorials, etc. What you have posted about gives us no context. 

Thanks,

Cody

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
