### ISSUE TITLE
Issue : steps to trouble shoot alert "KubeStatefulSetReplicasMismatch"

### ISSUE THREAD

**Issue by Malkar1492** [kubernetes/website#15767]
**This is a Bug Report**
I want a troubleshoot solution for openshift prometheus and grafana alert :
KubeStatefulSetReplicasMismatch - StatefulSet Namespace/StatefulSet replica mismatch

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by thecrudge** [comment]
Hi @Malkar1492 

That is more of a support or feature request and not an issue with the documentation itself. 

Please propose a solution and submit a PR. 

Thanks - C

/triage support
/kind feature
