### ISSUE TITLE
misleading annotation for aws internal load balancer 

### ISSUE THREAD

**Issue by fbreckle** [kubernetes/website#15771]
**Problem:**
The annotation for internal load balancers on AWS has the value 0.0.0.0/0 for no apparent reason. A cidr range is not required nor supported as a value in this annotation. This is quite confusing.

The implementation at [aws.go](https://github.com/kubernetes/cloud-provider-aws/blob/master/pkg/cloudprovider/providers/aws/aws.go#L3324) makes internal load balancers for every value except "false", so "true" has the same effect as 0.0.0.0/0 but is much more intuitive.

**Proposed Solution:**
Change
`service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` to `service.beta.kubernetes.io/aws-load-balancer-internal: "true"`

Due to the CLA, I cannot create a merge request myself.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer

**Comment by thecrudge** [comment]
/good-first-issue

Ref #15576
