### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/

### ISSUE THREAD

**Issue by dwimsey** [kubernetes/website#15770]
**This is a Bug Report**

**Problem:**

Page seems to advertise for New Relic

**Proposed Solution:**

Remove paragraphs referencing New Relic and links to its website.

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/#cronjob-monitoring

**Comment by thecrudge** [comment]
/good-first-issue

Thanks @dwimsey

**Comment by aimeeu** [comment]
This is a duplicate of issue #15711 - Remove vendor-specific info from resource usage monitoring

**Comment by HYngHwang** [comment]
★help wanted and good first issue to identify issues.

★The good first issue label is a subset of help wanted label.

★https://github.com/kubernetes/

**Comment by sftim** [comment]
Addressed via #15827
/close
