### ISSUE TITLE
Remove vendor specific content from online training overview

### ISSUE THREAD

**Issue by thecrudge** [kubernetes/website#15788]
**Problem:**
Keeping in line with the updated style guide (see #15576), we should also remove the vendor specific references on the online training overview page

**Proposed Solution:**
Remove the links

**Page to Update:**
https://kubernetes.io/docs/tutorials/online-training/overview/

/good-first-issue

**Comment by thecrudge** [comment]
Linked wrong Issue, #15748

**Comment by thecrudge** [comment]
/assign @loqutus 

Assigned, just keep in mind that issues are first come first serve. If someone submits a PR first, its theres to claim. When you do submit your PR, make sure to add in the comments this issue #.

**Comment by jhbiggs** [comment]
Not sure if it's what you meant, but committed above for pull request.

**Comment by sftim** [comment]
/hold cancel
(it's already closed)
