### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/nodes/

### ISSUE THREAD

**Issue by billsmithaustin** [kubernetes/website#15786]
**This is a Bug Report**

**Problem:** The What’s Next section goes away after you provide feedback.

**Proposed Solution:** Keep the What’s Next section after accepting feedback.

**Page to Update**
https://kubernetes.io/docs/concepts/architecture/nodes/

**Comment by sftim** [comment]
I tried adding feedback and found that the What's Next section remained. Is there still an issue?
/triage awaiting-evidence
