### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

### ISSUE THREAD

**Issue by SrikrishnaBingi** [kubernetes/website#15792]
Hello,

The mount path of container 'nginx-container' is '/usr/share/nginx/html' but the container 'debian-container' is writing data into '/pod-data'. 

But, you mentioned that the second container writes the index.html file in the root directory of the nginx server.  How is this possible when the mount paths are different? Please help me understand.

**Comment by thecrudge** [comment]
Hi @SrikrishnaBingi 

The way you have worded your statement makes me think that this is an issue that would be more suited for support, or an online help community like stackoverflow. 

If I am mistaken, and there is an issue with the documentation, then please fill out the bug report as instructed. 

/assign

/triage support

**Comment by SrikrishnaBingi** [comment]
Hello,

I think there is an issue with the code itself as the first container is pointing to a different shared folder location. Kindly check and let me know otherwise.

Thanks,
Srikrishna Bingi
