### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod-lifecycle/

### ISSUE THREAD

**Issue by usvgmani** [kubernetes/website#15797]
I am not sure if this is a bug. Please update documentation on conditionType for readinessGate.

**Problem:**
The readiness gate explanation for conditionType is not clear as to what does conditionType mean, it just says that conditionType: "www.example.com/feature-1", is that a hard coded value, and how does this work.

The readiness gate requires one or  two lines explanation on conditionType as to how the value can be used or changed.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

1.14

**Comment by sftim** [comment]
@usvgmani this is useful feedback!

It seems to me that it'd be worth dedicating a new page to PodReady++ and then summarising that page in https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/, along with a link.

/kind feature
