### ISSUE TITLE
SIG-Docs: Documentation User Survey 2019

### ISSUE THREAD

**Issue by aimeeu** [kubernetes/website#15828]
**This is a Feature Request**

**What would you like to be added**

Put together a survey asking (random) site visitors for their pain points.

The CNCF has a Survey Monkey account.  We could work with the owner to create a survey, which then could be linked to from the Docs home page. The link could also go out via social media and Google groups. We would have to be very careful how we word the questions and what the answer choices are so we collect meaningful data. What if we get 5K responses? Nobody is going to slog through 5K free form answers.

**Why is this needed**
Results would be useful for the Sept 13 board meeting and for project planning.

**Comments**
The questions below are a simple starting point. Please add your ideas.

1. How often do you access the Kubernetes documentation? (single select)
    - Every day
    - Once a week…
2. How do you usually access the Kubernetes documentation site? (single select)
    - Mobile phone
    - Tablet
    - Desktop web browser
3. Which sections do you access most often? (multi-select)
    - Getting Started
    - Concepts
    - Tasks
    - Tutorials
    - Reference
    - Contribute
4. Which sections need more detailed content?
    - Getting Started
    - Concepts
    - Tasks
    - Tutorials
    - Reference
    - Contribute

Question 4 could be broken down into several questions, with each question focusing on a section. That would be quite detailed and we might at that point lose end users taking the survey. We could focus on sections perceived as lacking detailed content: concepts, tasks, contributor guides

Also take a look at Brad's [StackOverflow](https://stackoverflow.com/search?tab=newest&q=kubernetes%20answers%3a3%20views%3a1000) filter

**Comment by sftim** [comment]
I would ask people to score a list of topics by how well the documentation explains them.
Eg:
- Deploying a cluster for learning
- Deploying a cluster for production use
- Securing your cluster
- Kubernetes architecture
- Running workloads on Kubernetes
- Container networking
- Services & load balancing
- Stateful workloads & storage
- Observability & logging
- Kubernetes terminology

If doing this, it might be an idea to take the topic list as the union of the topics for the CKA and CKAD exams(?)

**Comment by aimeeu** [comment]
CKA/CKAD curriculum [here](https://github.com/cncf/curriculum)

**Comment by aimeeu** [comment]
@zacharysarah do we have page hit stats for the k8s docs? I'd like to know which docs pages have the highest hits in a week. Then we can narrow our focus.

**Comment by zacharysarah** [comment]
@sftim The more I consider it, the less on board I am with asking site visitors to rank a list of topics.

1. It's a steep cognitive load/time investment to ask from a random site visitor.

2. We need to [measure only what we intend to act on](https://docsbydesign.com/2017/08/24/measuring-your-technical-content-part-1/#introduction-topics).

@aimeeu, I think your original proposal is solid and encourage you to proceed with it.

**Comment by sftim** [comment]
OK, cool. That makes a lot of sense.

**Comment by aimeeu** [comment]
@zacharysarah thanks for the "measure" article link. One actionable item I see already is modifying the Docs home page to include links to top pages so users don't have to dig. I will ping Jared about getting stats for more than just the top 10 pages.

**Comment by aimeeu** [comment]
Some feedback for next year: it might be a good idea to add a question that's related to something like "how often do you use the docs (daily/weekly/monthly)" & "whens the last time you used the docs" in case there was a big doc push that more experienced people might not be aware of that could skew the answers

**Comment by sftim** [comment]
/priority important-soon

Is this OK to close?
