### ISSUE TITLE
Missing altenative for Jobs in docs - pipelines

### ISSUE THREAD

**Issue by mik-laj** [kubernetes/website#15821]
Hey.
I miss information about one alternative - pipeline. 
They can be made by external tools.
https://github.com/knative/build
https://github.com/tektoncd/pipeline

This information will help you get to know Kubernetes better.

Thanks

**Comment by sftim** [comment]
Would linking to those solutions fit in with the (very recent) guidelines about 3rd party content?

See #15576

**Comment by sftim** [comment]
Perhaps a blog post about the different options could work instead?

**Comment by mik-laj** [comment]
Now I understand the rules. I'm afraid these designs are not suitable here.
