### ISSUE TITLE
Autoscaling low and up targets.

### ISSUE THREAD

**Issue by astateofmind01** [kubernetes/website#15847]
**This is a Feature Request**

Add a lower target resource for horizontal auto-scaler.  

**What would you like to be added**

The number of pods should be constant and not changing when the resource consumption is between the min and the max accepted values. Eg: while we have a cpu load between 20 and 60 the number of pods in the replica set should be x.

If the utilization drops below 20% then scale down, if the utilization grows about 60% scale up.

**Why is this needed**

Stabilize the number of pods in use and keep them from thrashing. Could be used in conjunction with --horizontal-pod-autoscaler-downscale-stabilization.

**Comments**

**Comment by sftim** [comment]
This sounds like a feature request for the HorizontalPodAutoscaler itself, rather than for the documentation.
@astateofmind01 &ndash; have I got that right?

**Comment by astateofmind01** [comment]
Yes, sorry if i didn't add it in the right place :)

**Comment by sftim** [comment]
This should be an issue against https://github.com/kubernetes/kubernetes/
/close
