### ISSUE TITLE
Add Kube Forwarder to the port-forwarding section

### ISSUE THREAD

**Issue by lnikell** [kubernetes/website#15841]
We developed an open-source GUI for Kubernetes port-forwarding functionality – [Kube Forwarder](https://kube-forwarder.pixelpoint.io/) and I would like to add it as a part of this [page](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod). 

Our app could improve the experience of using port-forwarding. We made it with a focus for new Kubernetes users to make the process as smooth as possible. The app supports auto-reconnect, autocomplete, configuration import/export functionality, multiple cluster support. So forwarding something is really simple and require just a few clicks, and could make you more productive if you use it constantly.

![kube-forwarder-1-ef6ec2c0-ef96-4c13-b0f6-486953a00f5a](https://user-images.githubusercontent.com/2697570/62887647-f0ac7700-bd3d-11e9-9c19-a18d628363e2.gif)

If you don't mind, let me know in which format you would be able to accept it:
- should it be just a link at the end to GUI alternative?
- should it be a separate section/page with a full guide with using GUI?

**Comment by thecrudge** [comment]
Hi @lnikell 

We no longer allow 3rd party documentation into the site, unless you are a CNCF Project or a Kubernetes sub-project. Please see the new style guide: 

https://github.com/kubernetes/website/issues/15576

/assign
/close
