### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by bobogege** [kubernetes/website#15869]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by bobogege** [comment]
![image](https://user-images.githubusercontent.com/32702026/63082661-64869380-bf79-11e9-9a44-e5edc973c492.png)
k8s节点加入集群的时候出现这个报错是怎么回事呢
![image](https://user-images.githubusercontent.com/32702026/63082727-91d34180-bf79-11e9-8cb4-546d4bffad99.png)

**Comment by neolit123** [comment]
hi, please log an issue in the kubernetes/kubernetes repository and follow the issue template.
the version of the kubelet has to be specified and also *all the details* about your setup!

thanks.
/close
