### ISSUE TITLE
Feature Request with k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by burkeazbill** [kubernetes/website#15864]
**This is a Bug Report**

**Problem:**
A step in the task says: "Set the --encryption-provider-config flag on the kube-apiserver to point to the location of the config file." Unfortunately, it does not specify (or link to) the solution or guidance on how to do that for a cluster that already exists. (perhaps this is dupe of 15482)?
**Proposed Solution:**
Provide a link in that step that points to documentation on **HOW** to set that flag on the kube-apiserver ver a cluster that has already been initialized. If it's a simple one-line command, provide it right under that text.
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#encrypting-your-data (step 3)

Kubernetes Version: 1.15.2

**Comment by burkeazbill** [comment]
Aside from a typo early in the article for the secrets.yaml filename, the best step-by-step instructions that actually worked for me was: https://www.serverlab.ca/tutorials/containers/kubernetes/kubernetes-secrets-and-encrypting-at-rest/

**Comment by sftim** [comment]
Thanks for the suggestion @burkeazbill 
/kind feature
