### ISSUE TITLE
Update language/zh base branch from release-1.14 to release-1.15

### ISSUE THREAD

**Issue by chenrui333** [kubernetes/website#15861]
Similar to what we did with release-1.12 to release-1.14. I would like that we can do something similar after release-1.15 rollout.

Relates to #13745 

/cc @kubernetes/sig-docs-zh-owners @kubernetes/sig-docs-zh-reviews 
/cc @zacharysarah

**Comment by idealhack** [comment]
```
/s/release-1.15/release-1.16
/s/release-1.14/release-1.15
```

**Comment by idealhack** [comment]
looks like it's time to stop using `release-x.y` branches as the base branch.

```
tengqm 11:59 AM
during 1.17 release window, the Chinese localization has been a headache for the release team.
we had a lot of commits directly merged into release-1.16 and only release-1.16 branch
when the release team rebase things back to release-1.16 branch, they saw a lot of conflicts
going forward, maybe we should commit things to master directly since we are kinda catching up with the master branch

idealhack 1:40 PM
agreed, PR to master or a -dev branch
```

https://kubernetes.slack.com/archives/CE3LNFYJ1/p1575946765043800

**Comment by jimangel** [comment]
Since we're changing the process a little, @chenrui333 or @tengqm can you please add `/cc @kubernetes/sig-docs-en-owners` on the next switch to `master` or `dev-x.xx`? It will help keep everyone in sync!

Thanks @idealhack and @tengqm!

**Comment by tengqm** [comment]
Sure, @jimangel, will keep an eye on it.

**Comment by idealhack** [comment]
cc @kubernetes/sig-docs-zh-owners @kubernetes/sig-docs-zh-reviews ^^^^

**Comment by tanjunchen** [comment]
this issue is old . can we close this? 
/cc @chenrui333

**Comment by tengqm** [comment]
pretty old issue. irrelevant now.
/close

**Comment by chenrui333** [comment]
Thanks @tengqm!
