### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/admission-controllers/

### ISSUE THREAD

**Issue by gilles17** [kubernetes/website#15879]
**This is a Bug Report**

**Problem:**
Serveral parts in this documentation use the "kube-apiserver" command, but with a kubernetes cluster setup by kubeadm, I don't have the "kube-apiserver" command and I cannot find any documentation in which explained how to setup "kube-apiserver" service.

**Proposed Solution:**
Add a reference to the page in which explained how to setup "kube-apiserver" service or create one if it does not exist.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/

**Comment by sftim** [comment]
If anyone's picking this issue up:
There's a [glossary entry](https://kubernetes.io/docs/reference/glossary/?all=true#term-kube-apiserver) that might help clarify what the API server is, perhaps via a tooltip [shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary).
