### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/field-selectors/

### ISSUE THREAD

**Issue by premkumar403** [kubernetes/website#15875]
need more real examples on how to use the field selectors. whats the best way for me to check the status of a pod /container which is in COMPLETED state.  I used to check the current status of pods which are in Running ( --field-selector=status.phase!=Running), but how to list the pods which are in terminating state ( Terminating state.) using field selectors or how to list then with the Reason of terminating …?

**Comment by sftim** [comment]
Thanks for the suggestion
/priority backlog

**Comment by tengqm** [comment]
/remove-lifecycle rotten
/lifecycle-freeze

We have got many complaints on this:
#9807 #15197 #15214 #15459 #19775 #20041 #20046

**Comment by tomkivlin** [comment]
I would like to provide some more examples and am happy to do the PR. Any preferences whether I add the extra examples in this page, or as a new page under `/Tasks/` (e.g. /tasks/manage-kubernetes-objects/field-selectors or something similar)?

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/40701

**Comment by natalisucks** [comment]
With the many issues raised as linked to this, plus the above-mentioned #40701 by @sftim, it's worth us noting what the acceptance criteria for this issue would be for us to be satisfied with the outcome, on top of it being helpful to users

**Comment by sftim** [comment]
Closing in favor of https://github.com/kubernetes/website/issues/47642

/close not-planned
