### ISSUE TITLE
Run link checker via Prow continuous integration

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15893]
**This is a Feature Request**

**What would you like to be added**
- when the website is built, run an automatic link checker on the built website
eg https://github.com/raviqqe/muffet

**Why is this needed**
- it becomes easier to spot broken hyperlinks
- it enables future work to fail a build that introduces a broken link 
- it helps reviewers check PRs (if they wish to)

**Comment by sftim** [comment]
Previously suggested: #734, #4004

**Comment by sftim** [comment]
This also helps spot hyperlinking issues between localizations, that reviewers might other really struggle to spot.

**Comment by sethmccombs** [comment]
`muffet` was the one I was poking around with, along with `liche`, from the same dev.

**Comment by sftim** [comment]
/priority important-longterm
(I guess)

**Comment by butuzov** [comment]
I started to experiment with different CI and related checks, I really hope I can spend a bit more time for that, but it's not my case. I hope till the end of the month I can come back with a more or less nice solution.

Currently, I am using deadlinks to find issues with a links in the Kubernetes website. But I don't really see any other CI platform then netlify. (i will check it out, and maybe there is a way to implement the additional command to check content)

**Comment by tanjunchen** [comment]
@butuzov  good job!Thanks

**Comment by butuzov** [comment]
update on my tool: deadlinks 0.2.1 can now perform faster checks on a directory of static files. and respect `_redirects`. What I am thinking now on how can deadlinks be useful for kubernetes website. Like we have a lot of deadlinks, with no way we can eliminate all of them quickly. Because of this reason `deadlinks` can't be used at the moment. 

I will back when i find out answers of some of my questions, and having a clear vision on how deadlinks can be integrated into the CI process of the website.

**Comment by sftim** [comment]
Mainly mentioning this for people with a docs background rather than a CI tooling background:
The usual story is to track known problems (maybe in a file in the repo). With that in place, warn for or block proposed changes that introduce a new regression.
For example, generate a list of deadlinks, diff with the existing. If the PR adds any new broken links, warn the reviewer.

**Comment by butuzov** [comment]
Yeap, that is what I am thinking on right now, however i can't come up with nice solution atm. I am already starting talking with a different docs teams. Hope anything useful can be gotten as result of this.

**Comment by sftim** [comment]
This is a fine thing to have at some point.
/remove-lifecycle rotten
