### ISSUE TITLE
Headers should be linkable

### ISSUE THREAD

**Issue by colemickens** [kubernetes/website#1589]
Markdown pages on Github have anchors that can be used to hotlink directly to a specific section of the document.

kubernetes.io lacks this. It lacks the anchors and the helpful icon to retrieve the hash-ed url without having to inspect the source. But even if I look in the source, there are no such anchors tags to use.

So, I have to tell people "Go to this page and Ctrl-f for [some] heading to get to the right place".

**Comment by colemickens** [comment]
Well, I couldn't see them in source, but I guess they still work somehow?

http://kubernetes.io/docs/admin/authorization/#rbac-mode

Is it possible to render a link next to the heading as is done on Github?

**Comment by chenopis** [comment]
@colemickens could you provide a specific example, screenshot if possible, of what you mean by "render a link next to the heading as is done on Github"?

**Comment by colemickens** [comment]
![2017-01-12](https://cloud.githubusercontent.com/assets/327028/21905425/3d9645c8-d8bc-11e6-9a69-bf5cb38b2246.png)

**Comment by chenopis** [comment]
Great, thanks for the quick reply @colemickens

**Comment by colemickens** [comment]
Not sure how to reopen this with the bot...

**Comment by tengqm** [comment]
Well, this has been fixed. Closing.
