### ISSUE TITLE
Document a from-scratch cluster build

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15909]
**This is a Feature Request**

**What would you like to be added**
Previously, https://kubernetes.io/docs/getting-started-guides/scratch/ documented how to take Kubernetes project's artefacts and use those to deploy a working cluster.

None of the links from https://kubernetes.io/docs/setup/ are to a page about a from-scratch, production-ready build.

**Why is this needed**
Some readers (perhaps not the majority though) would like to understand what this involves. Perhaps they are writing a new tool to deploy Kubernetes, or perhaps this information is useful for learning.

**Comment by sftim** [comment]
/reopen

Worth having, I think.
/remove-lifecycle rotten

**Comment by shannonxtreme** [comment]
Is the [original from-scratch page](http://web.archive.org/web/20190227062309/https://kubernetes.io/docs/setup/scratch/) a good starting point to gather content for a newer one?

**Comment by sftim** [comment]
> Is the [original from-scratch page](http://web.archive.org/web/20190227062309/https://kubernetes.io/docs/setup/scratch/) a good starting point to gather content for a newer one? 

I'd say it at least gives us a structure to work from and try to improve.

We should bear in mind the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/) which has changed since that build-from-scratch page was written.

**Comment by sftim** [comment]
/remove-lifecycle rotten
pending discussion about whether to close this issue or freeze this issue

**Comment by sftim** [comment]
/close
based on https://github.com/kubernetes/website/pull/27788#issuecomment-839980423

We can reopen this if the drive to document this changes

**Comment by sftim** [comment]
A related issue: #29913
