### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-gmsa/

### ISSUE THREAD

**Issue by aaronsssya** [kubernetes/website#15905]
**This is a Issue Report**

The doc https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/ is good.

**Problem:**
I applied with-cred deployment. I would like to know how to verify gMSA is working.

**Proposed Solution:**
gMSA working verification

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It sounds like you'd like https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/ to explain how to verify what you've configured.
Assuming I've got that right:
/kind feature

**Comment by aaronsssya** [comment]
Hi @sftim,
yes, correct. My windows node can use gMSA. I tried Docker run a windows container with CredentialSpec, It is good as well.

For the Kubernetes, I have build K8S cluster with a Windows worker node. I can deploy windows pod on Windows pod and it shows running. IIS is working as well.

I tried "klist get krbtgt" and "nltest /sc_verify:xxx.xxx", but all failed. Therefore, I would like to know how to verify the gMSA of Kubernetes. e.g. check gmsa-webhook pod? is there any log I can check.

**Comment by aaronsssya** [comment]
I tried to compare the container windows security event log.

Docker run
```text
MachineName = gMSA machine name
```

Kubernetes demployed
```text
MachineName = Pod name
```

According to gMSA design, machine name needs to match "gMSA machine name". I think my Pod does not get CredentialSpec.
