### ISSUE TITLE
Mention critical priority classes in https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15908]
**This is a Feature Request**

**What would you like to be added**
https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/ should mention that there are critical priority classes (`system-cluster-critical` and `system-node-critical`) and why these are relevant.

**Why is this needed**
Cluster operators want a way to make sure that their cluster stays working after scaling or failure events. If the wrong Pod dies and these mitigations aren't in place, a cluster could end up unable to heal itself.
This issue is about making sure cluster operators understand how to do that.

**Comments**
Might be worth hyperlinking to https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

**Comment by Luciowl** [comment]
Hey @sftim, Can I be assigned to this issue?

**Comment by sftim** [comment]
@Luciowl it sounds like you'd like to work on this and to make it clear to other people that you're making a start.

You can reply to say so and that's usually as much clarity as website contributors need. You're absolutely welcome to open a pull request with a proposed fix. You'll also need to sign a contributor license agreement if you haven't done that already.

(To be clear: you can work on an issue even if GitHub doesn't have it marked as assigned to anyone).

**Comment by alexzimmer96** [comment]
Has been fixed through #18979

**Comment by sftim** [comment]
/close

Thanks @alexzimmer96
