### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by PatrickXYS** [kubernetes/website#15910]
**This is a Bug Report**

**Problem:**
While I was going through the interactive tutorial,  `localhost:8001/version` can't be accessed without port mapping. Thus, it may require fix-up. 
**Proposed Solution:**
To modify Proxy services. 
**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Hi @PatrickXYS 

Port 8001 is used by the `kubectl proxy` as a way to make the Kubernetes API accessible from the instance but not the outside world. If this proxy is not running, then 8001 wouldn't be accessible. Can you remember if you started this?

We've added a not to the content to make this clearer - https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/02a1d75e887267fa7131e299d5ea4cea486c5454

I hope this helps.

Ben

**Comment by PatrickXYS** [comment]
Hi @BenHall 

I re-tried a couple of times and still the same error here. I copied all the commands and outputs below.

>kubectl proxy
Starting to serve on 127.0.0.1:8001

From the screen output, it should start to serve on `127.0.0.1:8001`, which is also `localhost:8001`,
then I opened `localhost:8001` on my browser. I still can't reach to the URL.

**Comment by BenHall** [comment]
@PatrickXYS I see the confusion. The interactive environment is running within a sandbox within your browser, meaning the ports are now bound to your local instance. As a result, the port is available from within the sandbox, but not from your local machine. 

We've removed the link at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/7402746d569396b63824b09327e3df418cbff60e

Thank you for the additional information. It was very helpful

**Comment by sftim** [comment]
Sounds like this might be fixed. @PatrickXYS do you agree?

**Comment by PatrickXYS** [comment]
It has already been fixed. Thanks!
