### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/update-api-object-kubectl-patch/

### ISSUE THREAD

**Issue by praveen-kg** [kubernetes/website#15922]
**This is a Bug Report**

**Problem:**
In the documentation page- https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/
the file name for patch example is patch-file.json.
But in the commands provided  for patch, file name is referred as  patch-file.yaml
kubectl patch deployment patch-demo --patch "$(cat patch-file.yaml)"
we we execute the command, we see below error:
cloud_user@praveen01111c:~$ kubectl patch deployment nginx --patch "$(cat patch-file.yaml)"
cat: patch-file.yaml: No such file or directory

**Proposed Solution:**
kubectl patch deployment patch-demo --patch "$(cat patch-file.json)"

**Page to Update:**
 https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/

v1.15

**Comment by sftim** [comment]
The text on the page says:
> The following commands are equivalent:
> 
> ```shell
> kubectl patch deployment patch-demo --patch "$(cat patch-file.yaml)"
> kubectl patch deployment patch-demo --patch 'spec:\n template:\n  spec:\n   containers:\n   - name: patch-demo-ctr-2\n     image: redis'
> 
> kubectl patch deployment patch-demo --patch "$(cat patch-file.json)"
> kubectl patch deployment patch-demo --patch '{"spec": {"template": {"spec": {"containers": [{"name": "patch-demo-ctr-2","image": "redis"}]}}}}'
> ```

So the name `patch-file.yaml` refers to a fictional file. It sounds like the current text isn't making that clear enough though.

**Comment by praveen-kg** [comment]
Document has been updated to reflect right file name
