### ISSUE TITLE
Wrong punctuation in QoS Class glossary entry

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#15924]
**This is a Bug Report**

**Problem:**
There are too many closing brackets in
> QoS Class (Quality of Service Class)) provides a way for Kubernetes to classify Pods within the cluster into several classes and make decisions about scheduling and eviction.

**Proposed Solution:**
Remove the extra closing bracket.

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?all=true#term-qos-class

/good-first-issue

**Comment by kbhawkey** [comment]
@sftim Can this issue be closed?

**Comment by sftim** [comment]
Sure
/close
