### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by Ch-sriram** [kubernetes/website#15938]
Make it simpler to understand. Cut the Jargon/Clutter, and make it easier to for the person who's reading the documentation, because that's the whole point of documentation.

**Comment by hpandeycodeit** [comment]
@Ch-sriram Can you provide more details In which section you are seeing the Jargons or where you are facing understanding the documentation?

**Comment by Ch-sriram** [comment]
Read the paragraph [here](https://kubernetes.io/docs/tutorials/kubernetes-basics/#what-can-kubernetes-do-for-you). Do you really think a person who is just beginning to understand what kubernetes is, will he/she able to understand what you wrote there? 
Especially this excerpt: 
> Kubernetes helps you make sure those containerized applications run where and when you want, and helps them find the resources and tools they need to work.

And also, look at the website's design [here](https://kubernetes.io/docs/tutorials/kubernetes-basics/#kubernetes-basics-modules), it looks so wrong & awkward. Please answer the following questions for yourself: 
1. Why would you put a sub-heading below an image? 
2. Why are those images so big and the sub-headings so small? 
3. Why would you assume that the people coming to read the documentation would know what "containerization" is? -- Explain the bare basic terms you use there, or at least link them to the concept(s) that we should know, before going through with this, or else people would just be confused by reading the doc.

What I'm trying to say is, make the doc so good, that whoever comes to read for the first time, should get it in the first go. Think from the perspective of a developer who's just trying to read/learn/know about kubernetes for the first time.

I've made a proposal to the code change [here](https://github.com/kubernetes/website/compare/master...Ch-sriram:patch-1)

**Comment by sftim** [comment]
Oops. Wrong place.
/priority awaiting-more-evidence
