### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/high-availability/

### ISSUE THREAD

**Issue by HankTheCrank** [kubernetes/website#15932]
**This is a Bug Report**

Setting does not produce the correct file

**Problem:**
On the page, the kubeadm-config.yaml file needs the line:
caFile: /etc/kubernetes/pki/etcd/ca.crt

The problem is that when you process the file through kubeadm, the resulting etcd.conf file does not get the setting. The lines that should be set are:

#[Security]
ETCD_TRUSTED_CA_FILE="/etc/kubernetes/pki/etcd/ca.crt"
ETCD_PEER_TRUSTED_CA_FILE="/etc/kubernetes/pki/etcd/ca.crt"

Add to this that there is a bug in etcdctl for the --endpoints flag (needed for https), and it's the perfect storm for us noobs.

**Proposed Solution:**
Not sure if it's a process issue, a documentation issue, or a problem with kubeadm.

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
hi, could you please qualify this part:
> The problem is that when you process the file through kubeadm, the resulting etcd.conf file does not get the setting. The lines that should be set are:

kubeadm does not process the kubeadm-config.yaml  file in a way that it outputs an etcd.conf.
we don't have a etcd.conf file in your guides.

> #[Security]
ETCD_TRUSTED_CA_FILE="/etc/kubernetes/pki/etcd/ca.crt"
ETCD_PEER_TRUSTED_CA_FILE="/etc/kubernetes/pki/etcd/ca.crt"

external etcd is managed as local etcd by kubeadm:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

which means that etcd is run as a static pod using a kubelet in the above guide and the CA flags are still passed to the binary. perhaps you mean something else?

/triage support
/sig cluster-lifecycle
