### ISSUE TITLE
Improve PKI certificates and requirements page

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/website#15937]
**This is a Feature Request**
Some small improvements to https://kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-manually page

**What would you like to be added**
- Add a note about requirements for service-account management private/public key pair
- For the `kube-apiserver` certificate, it might be useful to add a `<load balancer ip/dns>` entry in the list of certificates SAN; might be also useful to quote that it is possible to add additional SAN on all the server certificates
-  check / complete certificate usage map, e.g.:
   - `sa.pub` goes to the `service-account-key` flag of the `kube-apiserver`
   - `sa.key` goes to the `service-account-private` key flag of the `kube-controller-manager`
   - `ca.crt` goes to the `client-ca-file`, `root-ca-file`, `cluster-signing-cert-file` of the `kube-controller-manager`
   - `ca.key` goes to the cluster-signing-key-file of the `kube-controller-manager`
   - `front-proxy-ca.crt` goes to the requestheader-client-ca-file of the `kube-controller-manager`
   - `apiserver-kubelet-client.key` goes to the `kubelet-client-key` flag of the `kube-apiserver`

For sake of documentation, kubeadm support other variants:
  - external etcd, where the etcd cluster and the etcd certificates are not managed by kubeadm but should be provided beforehand by the user/external tools.
  - external CA, where an externally generated certificate authority is provided without its key; in this scenario, the user should take care of several tasks that depend on the CA key e.g. generating kubeconfig files, rotating certificates ...

**Why is this needed**
For clarity/completeness of the documentation

/cc @neolit123

**Comment by neolit123** [comment]
thanks for logging this issue @fabriziopandini . i agree that our docs related to PKI can be extended.

IMO we should be always using k/kubeadm for all of our tickets. k/webiste is super noisy and i don't wish us to groom the SIG tickets in this repo too.
