### ISSUE TITLE
Empty page /docs/concepts/workloads

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#15952]
See: https://kubernetes.io/docs/concepts/workloads/
Probably should be removed.

**Comment by thecrudge** [comment]
Hi @ahmetb , Netify wont allow it, as far as I tested. I tried, and failed. Maybe you have the special netify sauce though..

see PR #15753

**Comment by sftim** [comment]
I've got some bigger-scope ideas about fixing that, drafted in PR #15373

**Comment by sftim** [comment]
I think this is a duplicate of #15539
/remove-priority important-longterm

**Comment by sftim** [comment]
Is it OK to close this issue?
