### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by cvgaviao** [kubernetes/website#15950]
While starting a minikube I saw this message "minikube 1.3.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.3.1"
So I went to this page in order to learn how to update minikube to a new version and I was not able to find. 
Then I'm creating this issue in order to suggest to add instructions for how to update and to delete an installed minikube.

**Comment by RA489** [comment]
@cvgaviao could you please provide the page link where you got this?

**Comment by RA489** [comment]
@cvgaviao correct link is https://github.com/kubernetes/minikube/releases/tag/v1.3.1

**Comment by cvgaviao** [comment]
> @cvgaviao could you please provide the page link where you got this?

@RA489 , this is a message printed in the console after I enter: "minikube start"

**Comment by cvgaviao** [comment]
> @cvgaviao correct link is https://github.com/kubernetes/minikube/releases/tag/v1.3.1

Ok, but my point is: If I already a instance of minikube installed, how to upgrade? I need to remove everything and then install the new version?

**Comment by RA489** [comment]
> Ok, but my point is: If I already a instance of minikube installed, how to upgrade? I need to remove everything and then install the new version?
Please see the link to upgrade minikube. I have opened a PR to update the same on website. PTAL.
https://minikube.sigs.k8s.io/docs/start/macos/
