### ISSUE TITLE
Remove rkt references from Installing Kubernetes with Minikube page

### ISSUE THREAD

**Issue by aimeeu** [kubernetes/website#15966]
**This is a Bug Report**

**Problem:**
rkt is no longer a valid container option (the project is being archived). However, rkt is mentioned in two sections.

**Proposed Solution:**
Remove references to rkt as a container runtime. It is no longer supported by minikube.
https://minikube.sigs.k8s.io/docs/reference/runtimes/

**Page to Update:**
 k8s.io/docs/setup/learning-environment/minikube/
https://kubernetes.io/docs/setup/learning-environment/minikube/#minikube-features
https://kubernetes.io/docs/setup/learning-environment/minikube/#starting-a-cluster-on-alternative-container-runtimes

**Comment by sftim** [comment]
Final cleanup done in #24531
