### ISSUE TITLE
Create blog post on new contributor to k8s and SIG Docs experience

### ISSUE THREAD

**Issue by aimeeu** [kubernetes/website#15965]
**This is a Feature Request**

**What would you like to be added**
Chris Anisczyk would like me to write a blog post on my experience as new contributor to SIG Docs. 

**Why is this needed**
My supervisor's supervisor requested it.

**Comments**

**Comment by sftim** [comment]
and also, I think:
/sig contributor-experience

**Comment by sftim** [comment]
@aimeeu did you want to make a pull request to follow on from this issue?

**Comment by hvaara** [comment]
@sftim I think #16414 is the PR

/lifecycle active
