### ISSUE TITLE
Examine Minikube pages for dual-hosted content and content that should move to minikube docs site

### ISSUE THREAD

**Issue by aimeeu** [kubernetes/website#15969]
**This is a Feature Request**

**What would you like to be added**
Examine minikube pages to determine what should be hosted by minikube [docs](https://minikube.sigs.k8s.io/docs/) and what should be hosted by k8s docs.

Following the discussion on dual-hosted content (#15576), I think guides for installing minikube should be in the minikube project's docs, and then the k8s docs link to those installation guides.  State that the prerequisite for the Installing Kubernetes with Minikube page is successful installation of minikube and point to minkube docs. 
Already the k8s docs are stale with regard to container runtimes that minikube supports. 

k8s-specific how-to pages should remain in k8s docs.

Candidates to be removed from k8s docs and/or moved to minikube docs:

- [Install Minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/) this page is similar to https://minikube.sigs.k8s.io/docs/start/linux/
- [Installing Kubernetes with Minikube](https://kubernetes.io/docs/setup/learning-environment/minikube/)
  - this whole page needs to be examined and reworked
  - [minikube features](https://kubernetes.io/docs/setup/learning-environment/minikube/#minikube-features) section duplicates (and omits) content in https://minikube.sigs.k8s.io/docs/overview/
  - [Starting a Cluster](https://kubernetes.io/docs/setup/learning-environment/minikube/#starting-a-cluster)  specifying the k8s version, specifying a VM driver, starting the cluster on alternate container runtimes, and use local images by re-using the Docker daemon sections are candidates to move to minikube docs (if not already there)
  - [Add-ons](https://kubernetes.io/docs/setup/learning-environment/minikube/#add-ons) section
  - [Additional Links](https://kubernetes.io/docs/setup/learning-environment/minikube/#additional-links) section
  - [Community](https://kubernetes.io/docs/setup/learning-environment/minikube/#community) section
  - [Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) references this page

**Why is this needed**
Dual-hosted content places undo burden on maintainers to ensure content is up-to-date in both places.

With all minikube installation configuration instructions on the minikube site, hopefully all minikube environment errors will be directed to the minikube team. 

**Comments**
Relates to #15576 Clarify style guide: eliminate third-party content
Relates to #15748 Umbrella Issue: Remove Third-Party Content
Also see closed issue #6339 [Restructure and Rewrite Minikube docs](https://github.com/kubernetes/website/issues/6339)

**Comment by sftim** [comment]
Will this work eventually mean filing docs issues against the Minikube repo?

**Comment by aimeeu** [comment]
It may - really depends on what @RA489 finds. In my quick review yesterday, I found duplicate content that was outdated in kubernetes/website when compared to the minikube website and [docs](https://minikube.sigs.k8s.io/docs/).

**Comment by RA489** [comment]
I think as most of the doc has been to moved to minikube site we can remove the duplicate content.
@tstromberg wdyt?

**Comment by tstromberg** [comment]
@RA489 - thanks for working on this. Anything I can help out with?

**Comment by tstromberg** [comment]
Are we able to move on this issue yet? I'd really like to begin dismantling the duplicate and outdated reference information on the Kubernetes website related to minikube - though keep the great "Hello Minikube" tutorial that isn't duplicated elsewhere.

**Comment by zacharysarah** [comment]
@dims 👋 Given that this issue is reasonably isolated from larger policy questions (i.e., this issue involves re-homing content specific to Minikube with the consent of its contributors), are you OK with lifting the hold?

**Comment by zacharysarah** [comment]
@dims Thanks! 🙏 

@tstromberg Go for it!
