### ISSUE TITLE
Remove getting-started-guides/

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#15971]
### Description

The content in `content/en/docs/getting-started-guides/` has been deprecated for ~2 years. As shown in [the blame for `/static/_redirects`](https://github.com/kubernetes/website/blame/master/static/_redirects), 301 redirects have successfully pointed to `/docs/setup/`. At this point, the content in `getting-started-guides/` is thoroughly deprecated and needs to be removed.

### Proposed solution

1. `rm -rf /content/en/docs/getting-started-guides/`

2. Change `/static/_redirects#L164` to read:
```
/docs/getting-started-guides/*     /docs/setup/ 301
```

3. Remove the following from `/static/_redirects`: 

- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L165-L204
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L208
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L347-L353
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L421
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L504
- [ ] https://github.com/kubernetes/website/blob/master/static/_redirects#L518

### Files to change

https://github.com/kubernetes/website/tree/master/content/en/docs/getting-started-guides
https://github.com/kubernetes/website/blob/master/static/_redirects

/sig docs
/priority important-soon

**Comment by zacharysarah** [comment]
It might be a little nerve-wracking to delete stuff as a first-time PR, but technically this issue is self-contained and straightforward.

/good-first-issue

**Comment by digantajash** [comment]
Is this issue closed?or i can work on it?
I am new in GitHub :)

**Comment by praveensastry** [comment]
@digantajash I already opened a PR for the same.
