### ISSUE TITLE
Improve wording for StatefulSet limitations around storage

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#15979]
**This is a Bug Report**

**Problem:**
Third bullet in the "limitations" section says "Deleting and/or scaling a StatefulSet down will not delete the volumes associated with the StatefulSet".
It is not wrong, but not totally right. I think it should better refer to the PVCs created from the statefulset's volumeClaimTemplate than to the pre-provisioned or dynamically created PVs boudn to those PVCs (note also that removing/not removing those PVs is really related to the PV/StorageClass set reclaimPolicy .. once PVC and PV are unbound, of course)

**Proposed Solution:**
Following text proposed for that third bullet in the "statefulset - limitations" subsection (changed text remarked with bold letters)

- Deleting and/or scaling a StatefulSet down will not delete the **persitent volumes claim objects created from any volumeClaimTemplates included in the StatefulSet**. This is done to ensure data safety, which is generally more valuable than an automatic purge of all related StatefulSet resources. 

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations

**Comment by sftim** [comment]
Thanks for the suggestion!

**Comment by sftim** [comment]
/remove-lifecycle stale
/help
(_almost_ a good-first-issue, too, IMO)

**Comment by sftim** [comment]
/retitle Improve wording for StatefulSet limitations around storage
