### ISSUE TITLE
Translate tasks/debug-application-cluster/debug-service/ in Japanese

### ISSUE THREAD

**Issue by sotoiwa** [kubernetes/website#15980]
# Translate tasks/debug-application-cluster/debug-service/ in Japanese

**This is a...**

* [x]  Feature Request
* [ ]  Bug Report

**Problem:**
No tasks/debug-application-cluster/debug-service/ in Japanese.

**Proposed Solution:**
Translate tasks/debug-application-cluster/debug-service/ in Japanese.
Copy from en content and Update `/content/en/docs/tasks/debug-application-cluster/debug-service.md`.

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by cstoku** [comment]
@sotoiwa 作業いかがでしょうか？

**Comment by sotoiwa** [comment]
@cstoku すみません、やる気はあるのですが作業が止まってました。週末を目標にやります。

**Comment by inductor** [comment]
@sotoiwa 特に急いでるってわけでもないですが、どんなかんじでしょうか〜（念の為確認です）👀

**Comment by sotoiwa** [comment]
すみません、なかなか時間がとれず、かつ結構ボリュームがあってまだ終わってません。年内にはやります。
