### ISSUE TITLE
Link audit profile used by GCE references wrong line of code

### ISSUE THREAD

**Issue by dsbrng25b** [kubernetes/website#15998]
**This is a Bug Report**

**Problem:**
Link [audit profile used by GCE](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L735) references wrong line of code.

**Proposed Solution:**
Update line to 961 or maybe it would be event better to copy the audit policy into the documentation.

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy

**Comment by aimeeu** [comment]
Thanks for reporting this @dsbrng25b . This issue was fixed in PR #16570 so I'm closing this issue. Thanks.

/close
