### ISSUE TITLE
Error in Documentation (kubernetes on centos)

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/website#1600]
```shell 
# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd-servers=http://centos-master:2379"
```

this lines should be edited in /etc/kubernetes/apiserver
not in /etc/kubernetes/config

**Comment by a-mccarthy** [comment]
page to update: https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

**Comment by xsgordon** [comment]
I checked this locally and KUBE_ETCD_SERVERS is indeed in /etc/kubernetes/apiserver, **not** /etc/kubernetes/config as suggested in the document.

The other four settings mentioned in this same block (KUBE_LOGTOSTDERR, KUBE_LOG_LEVEL, KUBE_ALLOW_PRIV, KUBE_MASTER) are in /etc/kubernetes/config as listed.

**Comment by xsgordon** [comment]
PR merged, this issue can be closed.
