### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by mgedmin** [kubernetes/website#16000]
**This is a Bug Report**

**Problem:**

The description of a deployment spec, which is

> The .spec.template is a Pod template. It has exactly the same schema as a Pod, except it is nested and does not have an apiVersion or kind.

contains links to "Pod template" and "Pod" that are generic information pages that **do not describe the schema of a pod template**.  At best you get one example, but no list of fields or a description of their values.

**Proposed Solution:**

I'm sure there's a page somewhere in your docs that actually describes the pod template schema.  I'm quite sure I've read it in the past.  I just cannot find it right now.  Please link to it.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#writing-a-deployment-spec

**Comment by mgedmin** [comment]
Perhaps https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#podspec-v1-core is the right link?

**Comment by medmedchiheb** [comment]
@sftim what's better!  mentions PodSpec Api in `writing-a-deployment-spec` section  or  in `Pod Templates` at `pod-overview` page ?

**Comment by sftim** [comment]
Somewhat :man_shrugging: on that one @medmedchiheb 

My gut feeling is https://kubernetes.io/docs/concepts/workloads/pods/ should have a YAML example of a bare Pod as well as for a Pod template, and other pages should hyperlink to those.

**Comment by sftim** [comment]
Somewhat :man_shrugging: on that one @medmedchiheb 

My gut feeling is https://kubernetes.io/docs/concepts/workloads/pods/ should have a YAML example of a bare Pod as well as for a Pod template, and other pages should hyperlink to those.

_Maybe_ PodSpec is common enough to merit a glossary entry. What do you think?

**Comment by medmedchiheb** [comment]
I agree
