### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

### ISSUE THREAD

**Issue by shankatna** [kubernetes/website#16032]
**This is a Bug Report**

k8s.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
Starting of above page, namespace **default-mem-example** was created to isolate the limit range and pods from others, however created namespace **default-mem-example** never used in examples. Hence, limit range and other pods were created in default namespace and not newly created **default-mem-example** and being applied to all newly created pods. 

**Problem:**
Limtrange  is being applied to all newly created pods in default namespace
 
<img width="949" alt="default namespace" src="https://user-images.githubusercontent.com/47888973/63589438-8b4b5800-c57f-11e9-8e89-667b49ed0df2.png">

**Proposed Solution:**
Modify yaml files in this page to reflect newly created namespace and respective commands
<img width="936" alt="added newly created namespac" src="https://user-images.githubusercontent.com/47888973/63589434-88e8fe00-c57f-11e9-9108-efeeeb5864b6.png">

**Page to Update:**
k8s.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

Kubernetes  version 1.14.6

**Comment by sftim** [comment]
Thanks for reporting this.
/kind bug
/language en

**Comment by shankatna** [comment]
Used at the time of creation of the pod. which was misleading to me and raise an issue. my bad
