### ISSUE TITLE
Broken command in flannel_multi_node_cluster instructions.

### ISSUE THREAD

**Issue by mightybigcar** [kubernetes/website#16041]
**This is a Bug Report**

**Problem:**
Command to add the .json file to etcdctl fails.

**Proposed Solution:**
I think the line
   etcdctl set /coreos.com/network/config < flannel-config.json
should be
   etcdctl **put** /coreos.com/network/config < flannel-config.json

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/

**Comment by sftim** [comment]
https://kubernetes.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/ has gone
Based on that, I intend to:
/close
