### ISSUE TITLE
Issue with /docs/admin/federation/

### ISSUE THREAD

**Issue by tiagoalves83** [kubernetes/website#1604]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubernetes Federation Setup does not work outside GCE or GKE.

**Proposed Solution:**
Make compatible with other Providers, and make a NOTE at the documentation saying which providers are supported.

**Page to Update:**
http://kubernetes.io/docs/admin/federation/#setting-up-a-federation-control-plane

1.4.5

**Comment by tengqm** [comment]
This issue is too old to fix. Lots of things changed in the area of federation.
