### ISSUE TITLE
Links within https://kubernetes.io/docs/tasks/ overview not very useful

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16067]
**This is a Bug Report**

**Problem:**
The overview for https://kubernetes.io/docs/tasks/ shows a list of sections:

<ul>
<li><a href="https://k8s.io/docs/tasks/#web-ui-dashboard">Web UI (Dashboard)</a></li>
<li><a href="https://k8s.io/docs/tasks/#using-the-kubectl-command-line">Using the kubectl Command-line</a></li>
<li><a href="https://k8s.io/docs/tasks/#configuring-pods-and-containers">Configuring Pods and Containers</a></li>
<li><a href="https://k8s.io/docs/tasks/#running-applications">Running Applications</a></li>
<li><a href="https://k8s.io/docs/tasks/#running-jobs">Running Jobs</a></li>
<li><a href="https://k8s.io/docs/tasks/#accessing-applications-in-a-cluster">Accessing Applications in a Cluster</a></li>
<li><a href="https://k8s.io/docs/tasks/#monitoring-logging-and-debugging">Monitoring, Logging, and Debugging</a></li>
<li><a href="https://k8s.io/docs/tasks/#accessing-the-kubernetes-api">Accessing the Kubernetes API</a></li>
<li><a href="https://k8s.io/docs/tasks/#using-tls">Using TLS</a></li>
<li><a href="https://k8s.io/docs/tasks/#administering-a-cluster">Administering a Cluster</a></li>
<li><a href="https://k8s.io/docs/tasks/#administering-federation">Administering Federation</a></li>
<li><a href="https://k8s.io/docs/tasks/#managing-stateful-applications">Managing Stateful Applications</a></li>
<li><a href="https://k8s.io/docs/tasks/#cluster-daemons">Cluster Daemons</a></li>
<li><a href="https://k8s.io/docs/tasks/#managing-gpus">Managing GPUs</a></li>
<li><a href="https://k8s.io/docs/tasks/#managing-hugepages">Managing HugePages</a></li>
<li><a href="https://k8s.io/docs/tasks/#what-s-next">What's next</a></li>
</ul>

Nearly all of these hyperlink to near-empty sections on that page with no link to take the reader to useful content.

**Proposed Solution:**

Edit [content/en/docs/tasks/_index.md](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/_index.md)

Curate a link of task _sections_ (eg “Run Applications”) and, for each section, summarise the kind of task that readers can find there.

Consider adding an overview page (eg, at https://kubernetes.io/docs/tasks/run-application/) for each section, so that using the left-hand navigation becomes optional.

**Page to Update:**
https://kubernetes.io/docs/tasks/

**Comment by sftim** [comment]
IMO, this should have:
/priority important-longterm

**Comment by rashmi43** [comment]
I would like to take this up
