### ISSUE TITLE
https://kubernetes.io/docs/ broken for previous releases

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16065]
**This is a Bug Report**

**Problem:**
https://v1-14.docs.kubernetes.io/docs/ does not look like an archived version of https://kubernetes.io/docs/ (instead, it looks like what I see when I run Hugo locally):
![Screenshot](https://user-images.githubusercontent.com/22591623/63649246-37817000-c733-11e9-8172-e199cf27d8a2.png)

I assume this will be the same for all archived versions; I have not done much investigation.

**Proposed Solution:**
I'm not sure of a fix.
Investigate the way that archived sites are generated and diagnose this, I guess.

**Page to Update:**
https://kubernetes.io/docs/

**Comment by prasadkatti** [comment]
I think this issue might have been resolved. If I go to v1.14 docs and look at the release notes, I get release notes for v1.14.

**Comment by prasadkatti** [comment]
> I think this issue might have been resolved. If I go to v1.14 docs and look at the release notes, I get release notes for v1.14.

Actually, that isn't the case for the v1.15 site. So yes, the site is broken for older versions.

**Comment by sftim** [comment]
Looks fixed
/close
