### ISSUE TITLE
Broken link to latest Kubernetes documentation

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16066]
**This is a Bug Report**

**Problem:**
https://v1-15.docs.kubernetes.io/docs/ hyperlinks to the latest documentation, except that the link is actually to https://v1-14.docs.kubernetes.io/docs/ (because the `href` is null).

(oops!)
Here's the markup:
```html
<div class="content deprecation-warning">
      <h3>
	 Kubernetes v1.15
	  documentation is no longer actively maintained. The version you are currently viewing is a static snapshot. For up-to-date documentation, see the 
	 <a href="">latest version.</a>
      </h3>
    </div>
```

**Proposed Solution:**
Fix the link so that it takes readers to https://kubernetes.io/docs/

**Pages to Update:**
https://v1-15.docs.kubernetes.io/docs/
https://v1-14.docs.kubernetes.io/docs/
https://v1-13.docs.kubernetes.io/docs/

**Comment by Bradamant3** [comment]
@sftim I can't reproduce -- Chrome on Mac Mojave. Markup on the site looks OK too (no null `href`):

```
<div class="content deprecation-warning">
        <h3>
            Kubernetes v1.14 
            documentation is no longer actively maintained. The version you are currently viewing is a 
            static snapshot. For up-to-date documentation, see the
            <a href="https://kubernetes.io/docs/home/">latest version.</a>
        </h3>
     </div>
```

**Comment by Bradamant3** [comment]
Leaving my previous comment in place, but correcting it. Yup, reproduced. Given it's the latest version minus only one, seems a fairly high priority -- also bc seems likely that if we don't fix it'll repro for the next released version.

**Comment by sftim** [comment]
Revised the issue description as v1.16 is now out.
