### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by madankumar-t** [kubernetes/website#16064]
i have most of the people is showing up the dash board from mac only , why not a simple VM , because in industry we have to deploy the dash board in VM , i tried this dash board did not work for me , i got stuck.

**Comment by sftim** [comment]
Hi @madankumar-t 

Can you explain what isn't right about the page you mentioned?
/triage information-needed

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
