### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by elelbe** [kubernetes/website#16084]
tutorial not working
$
$ foreground.sh
foreground.sh: command not found

**Comment by BenHall** [comment]
Very sorry about this. We added in some additional processing but it had a problem due to the content being an older API version.

It's fixed now and we've added in a fix so the API version is correct.

This can be closed.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/ is working again
/close
