### ISSUE TITLE
SIG Docs co-chair update

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#16106]
## SIG Docs co-chair transition

@jaredbhatti has announced that he is stepping down as SIG Docs co-chair, effective 15 September 2019, and will become a chair emeritus.

For role transitions, SIG Docs follows our [community charter](https://github.com/kubernetes/community/blob/master/sig-docs/charter.md): 

> This charter adheres to the conventions described in the Kubernetes Charter README and adheres to the Roles and Organization Management specified in sig-governance.

From [sig-governance](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#notes-on-roles):

> Within this section "member" refers to a member of a Chair, Tech Lead or Subproject Owner Role. (this different from a SIG or Organization Member).
> Members MAY decide to step down at anytime and propose a replacement. Use lazy consensus amongst other members with fallback on majority vote to accept proposal. The candidate SHOULD be supported by a majority of SIG Members or Subproject Contributors (as applicable).

This issue establishes lazy consensus for @jimangel to replace @jaredbhatti as SIG Docs co-chair with consensus from fellow co-chairs and feedback from SIG members.

## Lazy consensus

To establish a lazy consensus, this issue needs:

- [x] A statement from @jaredbhatti, by issue comment, weekly meeting, or email to kubernetes-sig-docs@googlegroups.com, that he intends to step down as SIG Docs co-chair
- [x] For @jimangel to accept the nomination as chair: in an issue comment, weekly meeting, or email to kubernetes-sig-docs@googlegroups.com

When these two conditions are met, and without clear consensus from members (as defined in sig-governance) on a different path, on 15 September 2019:

- [x] @jaredbhatti steps down as co-chair of SIG Docs
- [x] @jimangel becomes a co-chair of SIG Docs

### Chairs can also just vote 

If two thirds of current chairs (@bradamant3, @jaredbhatti, @zacharysarah) vote to accept:
1. @jaredbhatti stepping down; and
2. @jimangel's nomination

The change passes.

## Thank you

@jaredbhatti is one of the original Kubernetes docs contributors, beginning in July 2016. Jared's first PR was #887, a two-character fix to a JSON file, followed shortly by #932, the 1.3 docs release. In a repo where issues and PRs have passed the 16,000 mark, @jaredbhatti's contributions are lengthy and enduring.

Jared, this SIG is where it is because of your leadership. You coordinated its first contributors, and oversaw the transition from a Google project to an open source community. You expanded the vision of this team beyond its origins and laid a foundation for this community's growth and success. Your contributions have been invaluable, and we are better for your work and insight.

As the first release lead and co-chair from outside of Google, it's my pleasure to thank you, @jaredbhatti for your leadership and to wish you every success in whatever comes next. We know that wherever you go, they'll be extraordinarily lucky to have you.

@jimangel, you've established community trust through friendly reviews and guidance, good judgment, and gentle mentorship. We're excited and honored for you to serve as a leader of our community. We're grateful for your support and we're here to support you in turn. Thank you for everything you've done so far, and thanks for investing in our SIG's future.

**Comment by zacharysarah** [comment]
From @jaredbhatti to [`kubernetes-sig-docs@googlegroups.com`](https://groups.google.com/forum/#!topic/kubernetes-sig-docs/o73I4QJNdBE):
```
Folks,

It's been an absolute pleasure working as a SIG-Docs chair for Kubernetes these past 3 years. When I started, we didn't have templates, we didn't translate into multiple languages - heck, we weren't even part of the CNCF yet. I dimly remember Paris Pittman explaining to me what a SIG is when I first started on this project and thinking "Oh, I should put one of these SIG group things together" :)

We've come so far in so short a time, and it's because of the work of every contributor here. It's been an honor working with you. Thank you.

Jim Angel will be taking my place and ramping up into the SIG-Docs chair role. I'm going to continue on as an approver on Kubernetes docs as I ramp up on a new and exciting project at Google. You're welcome to reach out to me on Slack, or at jaredb@google.com.

Jared
SIG-Docs Chair Emeritus
```

**Comment by zacharysarah** [comment]
That's unanimous assent to both motions, so it's official. So long, @jaredbhatti! Welcome, @jimangel!

**Comment by sftim** [comment]
Looks like this is OK to close?
