### ISSUE TITLE
Translate concepts/workloads/controllers/replicaset in Korean

### ISSUE THREAD

**Issue by lkaybob** [kubernetes/website#16109]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/workloads/controllers/replicaset.md in Korea

**Why is this needed**
No translation with concepts/workloads/controllers/replicaset.md in Korea

**Comments**

Page to update: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

**Comment by seokho-son** [comment]
@lkaybob 안녕하세요. 이슈 제안 감사드립니다.
확인해보니 해당 이슈는 중복된 이슈인 것 같습니다. 
(이슈를 올리시기 전에 중복된 Open/Closed 이슈 및 PR이 있는지 확인이 필요합니다. 예를 들면, 이슈 검색 필터에서 is:issue language/ko replicaset , PR 검색 필터에서 is:pr language/ko replicaset ) 

관련 해서는 이슈 #15955 가 먼저 올라와있었고,
PR #16070 를 통해 번역 문서가 dev-1.15-ko.5 에 머지가 완료되었습니다. 

운영진에서도 컨트리뷰터 분들의 중복된 작업을 최소화하고자 이슈를 주기적으로 확인을 하는데, 
이번에 확인이 늦었습니다. 양해 부탁드립니다.

혹시 작업 중이신 내용이 있다면, 
dev-1.15-ko.5 가 master에 머지되고 난 이후(아마도, dev-1.16-ko.1)에서 현재 번역된 controllers/replicaset.md 를 기준으로 반영해주시길 부탁드립니다.

따라서 해당 이슈는 Close하도록 하겠습니다.
/unassign @lkaybob
/close

**Comment by lkaybob** [comment]
@seokho-son 님 확인 감사합니다. 보아하니 제가 이슈 등록하기 전에 기 등록되었던 이슈를 제대로 확인 못했던 것 같네요 😅 다행히(?) 이슈 등록 후 바빠져서 시작을 못하고 있어서 따로 작업한 것은 없어서 해당 문서에 대한 추가 반영은 없을 것 같습니다. 참고 부탁드립니다 :)
