### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/annotations/

### ISSUE THREAD

**Issue by bollerman** [kubernetes/website#16103]
**This is a Bug Report**

**Problem:**
Missing specification of the "value" part of an annotation

**Proposed Solution:**
Document the length and character set restrictions of annotation values.

**Page to Update:**
https://kubernetes.io/...

**Comment by aimeeu** [comment]
Hi @bollerman - thanks for you feedback! Would you consider creating a pull request to fix this issue?

If you've never contributed to kubernetes/website, please take a look at the [Contribute to Kubernetes docs](https://kubernetes.io/docs/contribute/) section of the Kubernetes docs. Feel free to ping the [Kubernetes slack](http://slack.k8s.io/) #sig-docs channel if you have questions on creating a pull request.

**Comment by bollerman** [comment]
I would, except that I do not have the information to be documented. That was why I was looking for it in the first place

**Comment by aimeeu** [comment]
/sig docs
/priority backlog

Enchance https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#attaching-metadata-to-objects
