### ISSUE TITLE
Collapsible table of contents on full size screen

### ISSUE THREAD

**Issue by Tejeev** [kubernetes/website#16120]
**This is a Feature Request**

**What would you like to be added**
It would be preferable to be able to collapse or resize the table of contents on the left side of the screen so they don't waste so much space when not needed.  With my current configuration it takes up more than a 3rd of the screen when I'm just trying to focus on reading the docs.
![image](https://user-images.githubusercontent.com/8906089/63859075-93036600-c99e-11e9-8914-419fe2b34a92.png)

**Why is this needed**
If trying to focus on reading the docs, it's much preferable to have the option to simplify the layout and make use of the screen real estate.

**Comments**
The TOC collapses if you size the screen smaller, so might be simple to just add a button to do the same at other screen sizes?  Maybe allow for resizing of the bar (there's LOTS of wasted whitespace in that menu..)?

**Comment by celestehorgan** [comment]
Addressed in https://github.com/kubernetes/website/pull/20874. 

Can we close this? (cc: @sftim – I don't have permissions yet)
