### ISSUE TITLE
kubernetes.io broken links in generated docs (404 error)

### ISSUE THREAD

**Issue by abrennan89** [kubernetes/website#16124]
**This is a Bug Report**

**Problem:** Link to api-conventions.md from the generated docs at https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#deployment-v1beta1-apps is not working.

**Proposed Solution:** Update the link to the actual docs, I think it's here:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#deployment-v1beta1-apps

**Comment by jaypipes** [comment]
Yeah, this is actually a bug in kubernetes/kubernetes. The API documentation is generated from the `api/openapi-spec/swagger.json` file in that repository. kubernetes/kubernetes#81526 covers this issue and kubernetes/kubernetes#74245 is a PR that attempts to address the problem. Ashleigh, I think you can safely close this issue.
