### ISSUE TITLE
Update link hrefs in /ja/docs/ from English contents to Japanese contents

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#16133]
**This is a Feature Request**

**What would you like to be added**

I'd like to update link hrefs in /ja/docs/ from English contents to Japanese contents.

**Why is this needed**

Many pages have been translated into Japanese, but some links in these pages still navigate to English content, even if the link target pages have also been translated into Japanese.

**Comments**

e.g.

- `コンテナライフサイクルフック` and `コンテナライフサイクルイベントへのハンドラー紐付け` in https://kubernetes.io/ja/docs/concepts/containers/container-environment-variables/
- `コンテナ環境` and `コンテナライフサイクルイベントへのハンドラー紐付け` in https://kubernetes.io/ja/docs/concepts/containers/container-lifecycle-hooks/
- `コンテナライフサイクルフック` in https://kubernetes.io/ja/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

/language ja
/assign

**Comment by oke-py** [comment]
対象ページは他にもありそうなのでどこまでやるかも考える。というか、スクリプトでぱぱっとできるようにしたいが、できるかわからない。

**Comment by sftim** [comment]
/kind feature
/priority backlog

Is this done @oke-py?

**Comment by oke-py** [comment]
@sftim This is done for /ja/docs/tasks/ directory.
I'll close this issue and open another issue when I start to update other directories.
