### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by priyankur06** [kubernetes/website#16138]
**This is a Bug Report**

**Problem:**
/usr/bin/launch.sh shows syntax error

**Proposed Solution:**
No error

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Hi @priyankur06 

Sorry you had a problem. Do you know what the syntax error was?

Ben

**Comment by BenHall** [comment]
Hi @priyankur06

While we couldn't reproduce the issue, we've made some improvements to the script in case of any timing issues in future.

Thanks for your feedback.

**Comment by sftim** [comment]
Sounds OK to close
/triage awaiting-evidence
/close
