### ISSUE TITLE
k8s.io/docs/concepts/configuration/taint-and-toleration/ needs better contextual examples

### ISSUE THREAD

**Issue by Benjamintf1** [kubernetes/website#16147]
**Problem:**
In the tolerations section it does not show the tolerations in context of where it fits into the podspec. 
**Proposed Solution:**
show an entire podspec with the "tolerations" key at the same level of containers so users know where to place this data in their pod spec. 
**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

**Comment by aimeeu** [comment]
Hi @Benjamintf1 (love the pic of the PWC puppy!) -
Would you be willing to put the changes in as a pull request? If you're not 100% confident about the technical accuracy of changes, mention it in the PR description, and possibly ask for tech review.
Thanks for your feedback!

**Comment by Benjamintf1** [comment]
Should be fixed in https://github.com/kubernetes/website/pull/16157

**Comment by Benjamintf1** [comment]
Oh wow, this should have been closed a while ago. It's been merged in.
