### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by jrmlhermitte** [kubernetes/website#16149]
**This is a Documentation Request**
This is a documentation request.

It is not clear to me from that page what `concurrencyPolicy` means.
I have a feeling it's something like this:

concurrencyPolicy determines what to do in the event that when the next job is scheduled, the previous job is still running.
If `concurrencyPolicy` is set to `Replace`, the current running job will be deleted before the next one is scheduled.
If `concurrencyPolicy` is set to `Always`, the next job will run alongside the previous.
If `concurrencyPolicy` is set to forbid, then the next job will not be scheduled, and will be counted as missed.

These are my words. Can someone please add this?
I think you'll have much better wording. Please elaborate if I missed an extra term.

If you need me to do anything/submit this as PR let me know, thanks!

**Comment by sftim** [comment]
If you're willing to put this in as a pull request, @jrmlhermitte, please do.

I think the wording you've got looks fine. If / when you're not confident about the technical accuracy of changes, mention it in the PR description, and possibly ask for tech review.

**Comment by jrmlhermitte** [comment]
Actually, I found it [here](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy):
>The .spec.concurrencyPolicy field is also optional. It specifies how to treat concurrent executions of a job that is created by this cron job. The spec may specify only one of the following concurrency policies:

Allow (default): The cron job allows concurrently running jobs
Forbid: The cron job does not allow concurrent runs; if it is time for a new job run and the previous job run hasn’t finished yet, the cron job skips the new job run
Replace: If it is time for a new job run and the previous job run hasn’t finished yet, the cron job replaces the currently running job run with a new job run
Note that concurrency policy only applies to the jobs created by the same cron job. If there are multiple cron jobs, their respective jobs are always allowed to run concurrently.



It would be nice either to copy that text or link to it in that document. Sure, I can make a PR tomorrow. I think I will just link this page (and we can discuss).
Do I have to fill out some copyright form if I do so? If so, I think it might be simpler to leave it to someone else. Thanks!

**Comment by sftim** [comment]
To submit a PR you would need to [sign the contributor license agreement](https://kubernetes.io/docs/contribute/start/#sign-the-cla).

Thanks for the pointers!

**Comment by jrmlhermitte** [comment]
I took a look and I think the page looks fine to me. There is a clear link to the detailed cronjob documentation on [this line](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/):
> For instructions on creating and working with cron jobs, and for an example of a spec file for a cron job, see Running automated tasks with cron jobs

So I'm going to close this without submitting a PR. Thanks for the feedback!
