### ISSUE TITLE
The repo of cri-o for CentOS is empty

### ISSUE THREAD

**Issue by cody1996** [kubernetes/website#16150]
**This is a Bug Report**

**Problem:**
The repo of cri-o for CentOS in this page is empty.
I do not know which version of repo should I use.

**Proposed Solution:**
Can you tell me which repo is available? or fix this repo?

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#tab-cri-cri-o-installation-1

Kubernetes Version: v1.15

**Comment by aimeeu** [comment]
Hi @cody1996 - 
This issue sounds more like a request for support and less
like an issue specifically for docs. I encourage you to bring
your question to the cri-o community:
IRC: FreeNode, #cri-o channel
Slack: [Kubernetes](http://slack.k8s.io/) #crio
https://cri-o.io/
https://github.com/cri-o/cri-o

Please note that in the near future, we will be removing container runtime installation instructions from the Kubernetes documentation, instead adding text to point people to cri-o, Docker, etc. docs.

If this is a documentation issue, please re-open this issue.

/close

**Comment by cody1996** [comment]
@aimeeu 
First of all, thank you for your answer.
I understand that it may be removed soon so maintaining it is worthless.
And I am already looking for a solution from other sources.
Of course, there is no need to reopen this issue.
However, I just can't agree that it is "less like an issue specifically for docs" to have an unusable guide in the official documentation.
