### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubelet-config-file/

### ISSUE THREAD

**Issue by nickb937** [kubernetes/website#16161]
**This is a Bug Report**

**Problem:**

Pointing people at types.go for a configuration reference is a fairly useless way to describe a configuration file since it requires people to be basically familiar with reading Go and understanding the structure.  It's unclear how to generate the correct structured YAML from that source file.

**Proposed Solution:**

Add an example config.yaml to the page that somebody can use to derive their own.  The docs as they exist assume that all users are going to run `kubeadm init`.

**Page to Update:**
https://kubernetes.io/...

**Comment by aimeeu** [comment]
page https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

/kind feature
