### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/static-pod/

### ISSUE THREAD

**Issue by shizgchina** [kubernetes/website#16175]
**This is a Bug Report**

**Problem:**
kubelet --pod-manifest-path=<the directory> to start the kubelet

this description is NOT correct when using k8s 1.15. It says:
Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.

**Proposed Solution:**
We should find the kubelet config file : /var/lib/kubelet/config.yaml , and then edit the item directly: staticPodPath: /etc/kubernetes/manifests 

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Valid issue
/priority backlog
/lifecycle active
