### ISSUE TITLE
cluster broke

### ISSUE THREAD

**Issue by rajeshwer** [kubernetes/website#1618]
Failed to watch *api.Node: Get http://192.168.9.16:8080/api/v1/watch/nodes?fieldSelector=meta
621 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Get http://192.168.9.16:8080/api/v1/watch/pods?fieldSelecto
621 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: Get http://192.168.9.16:8080/api/v1/watch/services?resourceVers
621 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: Get http://192.168.9.16:8080/api/v1/watch/nodes?fieldSelector=meta
621 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: Get http://192.168.9.16:8080/api/v1/watch/services?resourceVers
621 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Get http://192.168.9.16:8080/api/v1/watch/pods?fieldSelecto
621 reflector.go:271] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Get http://192.168.9.16:8080/api/v1/watch/pods?fieldSelecto
621 reflector.go:271] pkg/kubelet/kubelet.go:240: Failed to watch *api.Service: Get http://192.168.9.16:8080/api/v1/watch/services?resourceVers
621 reflector.go:271] pkg/kubelet/kubelet.go:259: Failed to watch *api.Node: Get http://192.168.9.16:8080/api/v1/watch/nodes?fieldSelector=meta

**Comment by nVitius** [comment]
The issues tracker on this repository is for problems directly related to the Kubernetes documentation website [kubernetes.io](kubernetes.io/docs). For general support regarding Kubernetes, please read through [this doc](http://kubernetes.io/docs/troubleshooting/) or visit the official Kubernetes [Slack channel](https://kubernetes.slack.com/)

**Comment by rajeshwer** [comment]
I was getting this errors after following the steps in documentation 
kubernetes on centos
http://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/
I think there are lot of misleading steps in this doc

**Comment by rajeshwer** [comment]
Like for example 
/etc/kubernetes/config doesnt have any KUBE_ETCD_SERVERS
Its in /etc/kubernetes/apiserver

**Comment by a-mccarthy** [comment]
this issue is related to #1600, but there may be more problems with this page
