### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/events-stackdriver/

### ISSUE THREAD

**Issue by kribor** [kubernetes/website#16184]
Using the provided yaml results in (GKE v1.12.9-gke.7): 

`E0902 08:12:44.409083       1 reflector.go:190] github.com/GoogleCloudPlatform/k8s-stackdriver/event-exporter/watchers/watcher.go:50: Failed to list *v1.Event: events is forbidden: User "system:serviceaccount:devops:event-exporter-sa" cannot list resource "events" in API group "" at the cluster scope`

After modifying the clusterrolebinding to: 

```
...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
...
```

it apparently work but these permission might be too wide.

**Comment by kribor** [comment]
Looking a bit deeper this whole guide is moot because the exporter is already installed in the kube-system namespace! Stackdriver instructions are out of date however and events appear in:
GKE Cluster Operations
NOT:
GKE Cluster

**Comment by aimeeu** [comment]
@kribor Thank you for reporting this issue! We are in the process of removing third-party content, which includes this Stackdriver page. See PRs #15748 and  #16203.  So I'm closing this Issue. Thanks.
/close
