### ISSUE TITLE
Issue with k8s.io/docs/reference/glossary/

### ISSUE THREAD

**Issue by zimmnik** [kubernetes/website#16199]
**This is a Bug Report**

**Problem:**
Glossary didn't have EndPoint entry.
**Proposed Solution:**
To add description of EndPoint
**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?fundamental=true

**Comment by sftim** [comment]
/remove-lifecycle rotten

The entry should mention EndpointSlice too.
/help

**Comment by Vageesha17** [comment]
hi i am working on this issue
