### ISSUE TITLE
Make milestones match the kubernetes repo

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#16201]
**This is a Feature Request**

The milestones currently in use do not match the ones used in other kubernetes repos (they are missing a leading `v`). That means that org-wide github queries to find docs/issues/prs targeting a given release are not possible.

Making the docs milestones match the other repos would ease tracking of work in progress for a given release in github queries, dashboards, etc.

**Comment by sftim** [comment]
Good idea!
/kind feature
