### ISSUE TITLE
Improvement for k8s.io/docs/concepts/

### ISSUE THREAD

**Issue by mvensky** [kubernetes/website#16219]
Your documents are well written. Perhaps I am old school and just accustomed to textbooks, but I would like to see a more linear flow to the overall narrative with less distracting links.

Yes, the links are informative, but they are disruptive to the reading flow. I someone needs to define something they could either google it or perhaps you could offer footnotes. Either way it seems that a more fluid narrative and learning experience could be achieved using a more textbook like style.

**Comment by aimeeu** [comment]
priority/backlog
kind/feature
