### ISSUE TITLE
Translate concepts/configuration/taint-and-toleration into Japanese

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#16212]
**This is a Feature Request**

**What would you like to be added**
Translate concepts/configuration/taint-and-toleration into Japanese

**Why is this needed**
This document is not translated for Japanese yet.

**Comments**
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

/language ja
/assign

**Comment by sftim** [comment]
Still needed, right?
/remove-lifecycle rotten
