### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/turnkey/aws/

### ISSUE THREAD

**Issue by morganrconnolly** [kubernetes/website#16233]
**This is a Bug Report**

**Problem:**
conjure-up link links to k8s documentation
**Proposed Solution:**
update link to appropriate conjure-up documentation
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/turnkey/aws/

**Comment by aimeeu** [comment]
@morganrconnolly - thank you for bringing this to our attention! The Docs team is in the process of removing vendor-specific content, as well as links to vendor-specific content, from the Kubernetes documentation (see Issue #15748  and the [Content Guide](https://kubernetes.io/docs/contribute/style/content-guide/)). I've added the Turnkey section to #15748, so I'm going to close this issue.

/close

**Comment by morganrconnolly** [comment]
@aimeeu sweet. I had also opened a PR https://github.com/kubernetes/website/pull/16234#issuecomment-528565050 for this issue, which I closed. I referenced #15748 in a comment. Let me know if your organizational system prefers I did not. c:
