### ISSUE TITLE
Issue with k8s.io/docs/tasks/

### ISSUE THREAD

**Issue by MRDO5** [kubernetes/website#16259]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

Where is information or tasks ?

**Comment by sftim** [comment]
This sounds like a duplicate of issue #16067

@MRDO5 was that what you wanted to see fixed?
/triage needs-information

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
