### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/stateful-application/basic-stateful-set/

### ISSUE THREAD

**Issue by ULTRAKID** [kubernetes/website#16279]
where can i find the usage details of volumeClaimTemplates ?

**Comment by sftim** [comment]
If you're looking for English-language documentation, is https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components what you wanted?

/triage support

**Comment by RA489** [comment]
GitHub is not the right place for support requests.

For help, try https://stackoverflow.com/questions/tagged/kubernetes, the http://slack.k8s.io/, or the https://discuss.kubernetes.io/ forum.
