### ISSUE TITLE
Translate docs/tasks/administer-cluster/running-cloud-controller/ in Japanese

### ISSUE THREAD

**Issue by bells17** [kubernetes/website#16283]
**This is a Feature Request**

**What would you like to be added**

Translate docs/tasks/administer-cluster/running-cloud-controller/ in Japanese

**Why is this needed**

This document is not translated in Japanese.

**Comments**

Original:
https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

/language ja
/assign

**Comment by sftim** [comment]
Seems to be done via #16284 
/close

**Comment by bells17** [comment]
thank you
