### ISSUE TITLE
Issue with k8s.io/docs/concepts/

### ISSUE THREAD

**Issue by TiagoDapper** [kubernetes/website#16287]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @TiagoDapper 

Can you explain what isn't right with https://kubernetes.io/docs/concepts/?

/triage needs-information

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
