### ISSUE TITLE
Add sortable, filterable tables

### ISSUE THREAD

**Issue by RobertKielty** [kubernetes/website#16281]
**This is a Feature Request**

**What would you like to be added**

- Site-wide, add the capability to have tables that can be sorted by column
- Site-wide, add the capability to filter the rows that are presented in a table via a keyword search

**Why is this needed**
When a table contains a large number of rows, the information presented becomes unwieldy

A specific example can be found here : 
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

At present, the there are over 150 feature gates, sorted alphabetically by feature name.

The table presents lots useful information that I think would be easier to consume if we could sort that data by any column present in the table and filter the rows by keyword search.

**Comments**
@sftim suggested I log this as a issue based on a conversation in k8s Slack

**Comment by sftim** [comment]
/kind feature
/priority backlog
(but feel free to tweak that priority)

**Comment by RobertKielty** [comment]
/remove-lifecycle stale

I'll take a look again at implementing this over the holidays

**Comment by sftim** [comment]
It's a nice idea; however:
/remove-priority backlog
/priority awaiting-more-evidence

**Comment by sftim** [comment]
/remove-lifecycle stale
all the same

**Comment by zacharysarah** [comment]
@RobertKielty 

> At present, the there are over 150 feature gates, sorted alphabetically by feature name.

Yeah, that's a beast of a table. Sorting would definitely be nice to have!

**Comment by sftim** [comment]
Revising priority based on discussion
/remove-priority important-longterm
/priority backlog
