### ISSUE TITLE
Clarify what a preStop-Hook may and may not do

### ISSUE THREAD

**Issue by UlrichEckhardt** [kubernetes/website#16288]
**This is a Feature Request**

**What would you like to be added**

I'd like clearer wording on these two pages describing shutdown hooks:
https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

One example for the use of these hooks given is to store state prior to terminating the container. Another use is to perform an ordered (graceful) shutdown of a service. For e.g. a webserver, this means telling it to stop accepting new connections but still serve pending requests.

What we have found is that there are things that you may not do though, in particular you may not terminate the container as part of the preStop hook. However, this happens when performing a graceful shutdown of a service and that (directly or indirectly) terminates PID 1 of the container. We have seen a Kubernetes cluster considering the container as "broken" when it shuts down during the preStop execution and restarting it, which is exactly not what is intended.

**Why is this needed**

The obvious solution to gracefully stop a service seems to be wrong and instead it leads to fragile systems. Trying to sidestep this pitfall with better documentation would be helpful.

**Comments**

I'm not sure if this behaviour by Kubernetes is intended. Maybe Kubernetes should instead treat the preStop hook like it treats SIGTERM, expect the container to shut down in response. If it doesn't terminate the container, fine, just move on and try the next shutdown method. I also don't rule out that I'm misinterpreting what I saw and that everything's okay.

**Comment by sftim** [comment]
@UlrichEckhardt you'd like a sentence or two that explains that the preStop hook should ready the container for shutdown but leave at least its PID 1 process running.
Have I got that right?

**Comment by UlrichEckhardt** [comment]
Yes, that's a good way to say it, @sftim!

In addition, I'm asking if that is actually the intention. I don't rule out that we're doing something wrong here and that shutting it down during preStop should work when done correctly.
