### ISSUE TITLE
Translate concepts/services-networking/connect-applications-service/ into Japanese

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#16297]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/services-networking/connect-applications-service/ into Japanese.

**Why is this needed**
This document is not translated into Japanese.

**Comments**

Original:
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

/language ja
/assign

**Comment by cstoku** [comment]
@oke-py  作業いかがでしょうか？

**Comment by oke-py** [comment]
@cstoku すみません、ほとんど進んでいません。ちょうどそろそろやろうかなと考えていたところでした。次のリリースにまわしていただいて構いません。
