### ISSUE TITLE
Issue with content/en/docs/user-journeys/users/cluster-operator/_advanced.md

### ISSUE THREAD

**Issue by yuxiaobo96** [kubernetes/website#16326]
**This is a Bug Report**

**Problem:**
This document cannot be translated into Chinese. 
**Proposed Solution:**
Maybe it doesn't belong to the en folder.
**Page to Update:**
https://github.com/kubernetes/website/blob/release-1.14/content/en/docs/user-journeys/users/cluster-operator/_advanced.md

**Comment by sftim** [comment]
That page is “lorem ipsum” content. I expect it's OK to delete it.

/kind bug
/priority backlog

**Comment by sftim** [comment]
It's already [gone](https://github.com/kubernetes/website/blob/master/content/en/docs/user-journeys/users/cluster-operator/_advanced.md) in the master branch.

**Comment by yuxiaobo96** [comment]
Ok, I will submit the PR to delete this document.

**Comment by hvaara** [comment]
Looks to me like this was fixed in #16398 🙌
