### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-scheduler/

### ISSUE THREAD

**Issue by christian-2** [kubernetes/website#16327]
**This is a Bug Report**

Yes.

**Problem / Proposed Solution:**

Feature gate `PodPriority` is no longer BETA (but by now GA) according to [this](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) reference. The description of `kube-scheduler --help` should be updated.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

**Comment by christian-2** [comment]
Also applies to [https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/), [https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/),  [https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/), and [https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/).

**Comment by SupriyaSirbi** [comment]
Thanks for the issue

**Comment by sftim** [comment]
I think this is fixed. Is that right @SupriyaSirbi ?

I'll also 
/remove-good-first-issue
/remove-help
/triage needs-information

**Comment by SupriyaSirbi** [comment]
Yes this issue is fixed
