### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by Balfa** [kubernetes/website#16334]
**This is a Bug Report**

**Problem:**
Number of types of volumes is overwhelming. As a newcomer, I can tell that new volume types have been added over time without too much consideration to how this flows to a reader trying to understand. The list of volume types now extends well beyond a single page at 1920x1080, and is not well suited to a bullet list. Since I get just the name for most of these types, I invariably need to wade deep through the details of the volume types to learn anything useful. I get that this is in the concepts section and not the tasks section, but for someone looking for a more gentle introduction it can be hard to find the volume type I need.

**Proposed Solution:**
A table of types might be a better alternative than a bullet list, with a more detailed description included with the name. In my opinion, an even better solution would be to split the types into two categories; First, present a handful of "mainstream" types and then a litany of "extended" types can be covered in a later section. Again, I get this isn't a how-to quickstart page, but I still think the information would be more consumable if we introduce some of the more esoteric types after the fundamentals have been grokked.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/

**Comment by sftim** [comment]
Thanks for the suggestion

/priority backlog

**Comment by sftim** [comment]
The list of volume types would work better in the Reference section.

Just that move alone would help. I actually think that migrating part of the content to a new page is (just barely) a
/good-first-issue

/remove-lifecycle rotten

**Comment by zerefwayne** [comment]
@sftim Is work required on this one?

**Comment by sftim** [comment]
@zerefwayne anyone is free to work on an issue and propose a pull request towards fixing it. Please feel free to do that.

Do you want to tackle just a part of the work? That's often a good way to contribute. For example, you could create the new reference page and have the existing page link to it.
Please also (anyone!) feel free to reply to this issue with questions or requests for advice.

**Comment by Krishan-Sharma** [comment]
I am thinking that an accordion would work nicely here. See some spatial benefits straight away. (https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_accordion). WDYT @sftim, others?

**Comment by sftim** [comment]
Sounds like this would be a (set of) HTML lists, then, plus styling to make it render nicely as suggested in https://github.com/kubernetes/website/issues/16334#issuecomment-620608341

I think that sounds fine.

**Comment by tengqm** [comment]
@Krishan-Sharma I'm afraid migrating the content to HTML (so that you can use accordions ...) may not be the direction to go. As we are upgrading Hugo inevitably, new Hugo versions do not like embedded HTML contents.

So back to the volumes improvement. One thing we can do is to move out-of-tree volume types into separate files. The list is really too long.
