### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/nodes/

### ISSUE THREAD

**Issue by mkambham-c** [kubernetes/website#16348]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by savitharaghunathan** [comment]
@mkambham-c, can you explain a little bit more about the issue?

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
