### ISSUE TITLE
Issue with k8s.io/docs/concepts/containers/container-lifecycle-hooks/

### ISSUE THREAD

**Issue by voron** [kubernetes/website#16341]
**This is a Bug Report**

**Problem:**
`PostStart` and `PreStop` start from capital letter. I get an error like following
```unknown field "PostStart" in io.k8s.api.core.v1.Lifecycle```

**Proposed Solution:**
Use `postStart` and `preStop`

**Page to Update:**
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

**Comment by medmedchiheb** [comment]
@voron note that `PostStart ` , `PreStop `  start with capital letter because they are the names of Container hooks.
they are not the fields in `lifecycle` spec, as you thought.

**Comment by voron** [comment]
Got it, correct manual page is [here](https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#define-poststart-and-prestop-handlers)
