### ISSUE TITLE
ResourceQuota enhancement to allow network resources.

### ISSUE THREAD

**Issue by sb1975** [kubernetes/website#16356]
**This is a Feature Request**
ResourceQuota does not allow any limit towards the fundamental network resource - Limit Total Number of IP address allowed in each namespace and ability to specify a particular VLAN subnet for a namespace.  This is critical for a Multi-tenant environment where a single Kubernetes Cluster is shared by multiple tenants.
When I as a Infrastructure Provider plan to host the tenants, they will provide some of the following details(there would be more) and I should have an ability to do the same in my cluster :
List of requirements from the Tenant in their own namespace :
1. Total number of Pods
2. Total amount of Compute resource
3. Total amount of Storage resource
4. Total number of IP needed and a specific IP subnet for a specific namespace.

How can the number 4 above be achieved in present Kubernetes Architecture please.

**What would you like to be added**
Total number of IP needed and a specific IP subnet for a specific namespace.

**Why is this needed**
This is critical for a Multi-tenant environment where a single Kubernetes Cluster is shared by multiple tenants.
**Comments**

**Comment by sftim** [comment]
This looks like a feature request for enhancing https://github.com/kubernetes/kubernetes, rather than the documentation. Have I got that right?

**Comment by sftim** [comment]
I'll assume I've guessed right, and:
/remove-priority important-soon
/remove-kind feature
/triage needs-information

**Comment by aimeeu** [comment]
@sftim I bow to your experience! Yes, rereading, this does sound like a request to enhance Kubernetes. Thanks for double-checking and correcting this.

**Comment by sftim** [comment]
@sb1975 You can request a new Kubernetes feature by making an [enhancement proposal](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps)
/close

**Comment by sb1975** [comment]
I found out that this is possible via the CNI using Annotations :
https://docs.projectcalico.org/v3.9/reference/cni-plugin/configuration#specifying-ip-pools-on-a-per-namespace-or-per-pod-basis
