### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/create-external-load-balancer/

### ISSUE THREAD

**Issue by rong0312** [kubernetes/website#16367]
In my opinion, there is a need to expand more regards the outside-LB integration..
I couldn't find a normal way to configure it.

**Comment by aimeeu** [comment]
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

@rong0312 - thank your for opening this Issue!  Would you provide more details so we have an idea how to improve the page? What information is missing? What problems did you have? Thanks!

/triage needs-information

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
