### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/jsonpath/

### ISSUE THREAD

**Issue by andy-b-84** [kubernetes/website#16374]
Hi,
Thanks for this documentation, it is really helpful.

That being said, we use a syntax which is not documented here : 
```
kubectl get ingress -o jsonpath="{range .items[?(@.metadata.annotations.some.domain/some.annotation==\"our-ingress-class\")]}"
```
And I'm trying this one out :
```
kubectl get ingress -o jsonpath="{range .items[?(@.metadata.annotations.some.domain/some.annotation=~/our-ingress-class.*/)]}"
```
I would have liked to know if this syntax is supported before trying it (and don't have the answer right now).

Thanks again for the awesome docs :)

**Comment by andy-b-84** [comment]
It doesn't work, nor does `~=`, it fails with the message
```
error: error parsing jsonpath {range .items[?(@.metadata.annotations.some.domain/some.annotation=~/our-ingress-class.*/)]}, unrecognized character in action: U+002F '/'
```

**Comment by andy-b-84** [comment]
Got something by writing the regex as a `"` escaped string, but I cannot get this regex to match anything:
```
kubectl get ingress -o jsonpath="{range .items[?(@.metadata.annotations.some\.domain/some\.annotation~=\"/our-ing.*/\")]}{.spec.rules[*].host}{end}"

```

**Comment by sftim** [comment]
This page could signpost readers to an external resource about using jsonpath.
