### ISSUE TITLE
Issue with /docs/getting-started-guides/kops/

### ISSUE THREAD

**Issue by wymedia** [kubernetes/website#1637]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Following [this](http://kubernetes.io/docs/getting-started-guides/kops/) guide. In step 5, an error occurs that api.<clustername> (example: api.dev.example.com) is not available.

Unable to connect to the server: dial tcp: lookup api.<clustername>: no such host

It seems kops did not create a record for this. Should it be done manually and if yes, where (on the registrar or on AWS Route 53)?

**Comment by sandcastle** [comment]
I had also had exactly the same issue. I checked route 53 and the `api` record was not there, gave it about a minute, then re-ran the update command and the records appeared.

**Comment by chrislovecnm** [comment]
I apologize but this got into this repo and not kops repo.  Do we still have open issues?
