### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by jayapalreddy18** [kubernetes/website#16393]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @jayapalreddy18 

Did you see a problem with the page at https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/? If so, what was the problem?

/triage needs-information

**Comment by jayapalreddy18** [comment]
HI 

i have followed same link. but i am unable to access below link

 http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

**Comment by sftim** [comment]
It seems to me that https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ could better signpost readers to learn about how `kubectl proxy` works.

/remove-triage needs-information
/priority backlog
