### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/addons/

### ISSUE THREAD

**Issue by ankitchadha** [kubernetes/website#16397]
**This is a Bug Report**

**Contrail/Tungsten installation steps are missing:**

**Add Contrail/Tungsten installation steps as a hyperlink (just like a hyperlink is present for Nuage/Flannel/Weave CNIs). This is the link that needs to be referenced for Contrail https://github.com/Juniper/contrail-controller/wiki/Installing-Contrail-CNI-on-Kubernetes:**

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/addons/

**Comment by sftim** [comment]
@ankitchadha would you recommend that this page should have links to install guides for all the network plugins?

**Comment by aimeeu** [comment]
https://kubernetes.io/docs/concepts/cluster-administration/addons/  is a page that needs to be reviewed as part of the Remove Third-Party Content initiative (#15748), which is currently on hold.

**Comment by ankitchadha** [comment]
@sftim : The page should be consistent. Either include the deployment guide hyperlinks fro all plugins, or for none.

As of today: it includes hyperlinks to the installation guides of many network plugins (Nuage/Flannel/Weave etc). Hence requesting that we add the right hyperlink for Contrail/TF as well.

**Comment by sftim** [comment]
Seems like valid issue

/remove-lifecycle stale
/kind cleanup
/remove-priority important-soon
/priority backlog
