### ISSUE TITLE
k8s data plane?

### ISSUE THREAD

**Issue by NMFR** [kubernetes/website#16394]
On the [k8s glossary](https://kubernetes.io/docs/reference/glossary/?all=true#term-data-plane) it mentions a `data plane`.

https://github.com/kubernetes/website/blob/d21ffb4c633567321575eb9bf8b19a3ef69e3986/content/en/docs/reference/glossary/data-plane.md

Maybe it is my definition of `data plane` that is too related to "data" or the service mesh definition for that term but should this plane be called something else? 
Like `application(s) plane`?
Or am i missing any concept here?

**Comment by aimeeu** [comment]
Hi @NMFR - thanks for asking your questions!

A better place for you to ask your questions is the `#kubernetes-users` or `#kubernetes-novice` channels in the [Kubernetes slack](http://slack.k8s.io/) instance. 

If you receive an answer that is different than the glossary definition, please add a comment to this Issue so we can update the docs. If not, you can close this issue by leaving a ```/close``` comment. Thanks!!

/triage support

**Comment by NMFR** [comment]
Piggy backed on a thread started about the same issue.

https://kubernetes.slack.com/archives/C09NXKJKA/p1568741965005200

But only got one response.

Guess its a `close`, although i think the current name (`data plane`) is misleading.
