### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by itsecforu** [kubernetes/website#16429]
This page does not open:

https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

**Comment by aimeeu** [comment]
HI @itsecforu - thanks for reporting this issue! Could you let us know where in the documentation you found the link?

/triage needs-information

**Comment by itsecforu** [comment]
@aimeeu  hey! I dont remember :-(

**Comment by tengqm** [comment]
Looks like the mentioned link is no longer there.
pls feel free to open with actionable issue details or file a new one.
