### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by tuxfux-hlp** [kubernetes/website#16426]
**This is a Bug Report**

**Problem:**
There is a pre-requisite for docker installation .
**Proposed Solution:**
Need to be updated in the document to install the docker.
**Page to Update:**
https://kubernetes.io/...
https://kubernetes.io/docs/tasks/tools/install-minikube/

devops@devops-learning:~$ uname -a
Linux devops-learning 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
devops@devops-learning:~$ sudo minikube start --vm-driver=none
* minikube v1.3.1 on Ubuntu 18.04 (vbox/amd64)
* Running on localhost (CPUs=1, Memory=2347MB, Disk=19061MB) ...
E0918 14:28:59.056725    4426 start.go:723] StartHost: create: precreate: exec: "docker": executable file not found in $PATH
*
X Unable to start VM: create: precreate: exec: "docker": executable file not found in $PATH
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
devops@devops-learning:~$

**Comment by sftim** [comment]
It seems like the page about Minikube already states:
> Minikube also supports a `--vm-driver=none` option that runs the Kubernetes components on the host and not in a VM. Using this driver requires Docker …

and to me that seems like the information about needing Docker is already there (for `--vm-driver=none` only AIUI).

@tuxfux-hlp can you clarify what needs fixing?

/triage needs-information

**Comment by RA489** [comment]
@tuxfux-hlp you need to install docker beforehand if you are using `--vm-driver=none` option.

**Comment by tuxfux-hlp** [comment]
Ya got it. Thank you.

**Comment by RA489** [comment]
@tuxfux-hlp we can close this issue now?
