### ISSUE TITLE
Add task page describing scheduler configuration

### ISSUE THREAD

**Issue by timstoop** [kubernetes/website#16423]
**This is a Bug Report**

**Problem:** This page mentions a lot of options, but nowhere does it state how to actually change those configurations. There's generally no information available about the KubeSchedulerConfiguration object type anywhere in the docs that I could find, including no description of where to set it (should it be a resource in the cluster? a file on disk?).

**Proposed Solution:** Someone who actually knows how this is done correctly should write that down.

**Page to Update:**
k8s.io/docs/concepts/scheduling/kube-scheduler/ but there might be others as well.

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/scheduling/kube-scheduler/#what-s-next links to https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/ and that documents how to customise the scheduler's behavior.

If any part of the docs covered `KubeSchedulerConfiguration`, I'd expect that would be the reference section.

I'm not sure I can see a bug that needs fixing. I'm sure though that there's room to tweak the docs in this area, and any pull request would be welcome.

**Comment by timstoop** [comment]
Honestly, the reference is even worse, it contains a huge amount of deprecated options without any explanation on how to get the behaviour in the proper way instead. I just like somewhere to explain how to do it, because I still don't know :) I just keep using the deprecated options, because there's no explanation anywhere how to do it in a non-deprecated way.

I would expect the regular docs that already explain the different options and how to add additional schedulers and the like would also spend some words on how exactly to apply those configuration directives. I think it's a bug because it explains the different behaviours, but not how one would configure them. At least, I'm unable to find an explanation how to do it without using deprecated parameters. Feel free to point me in the right direction! (I'm honestly still looking for it.)

**Comment by sftim** [comment]
How about making this issue be a request for a new Task page that covers how to:
1. configure components of the Kubernetes control plane
2. configure the scheduler

(or even 2 new Task pages, where the first one signposts readers to the second one).

@timstoop do you think that the work I've outlined, if done, would help address the shortcomings you're reporting?

**Comment by timstoop** [comment]
Yes indeed, that would work very well.

**Comment by sftim** [comment]
/retitle Add task page describing scheduler configuration
/remove-lifecycle stale
