### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by bennythejudge** [kubernetes/website#16434]
**This is a Bug Report**

**Problem:**
In the `Package the scheduler` section (https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/#package-the-scheduler), the instructions are not adequately complete and clear. If executed as-is on a MacOS computer, they will produce a `darwin` binary which is of no use for the exercise.

```
find ./_output -name 'kube-scheduler'
./_output/local/go/bin/kube-scheduler
./_output/local/bin/darwin/amd64/kube-scheduler
```

Also note that the directory indicated in next step in the doc, would not exist:

```
ls -l ./_output/dockerized/bin/linux/amd64/kube-scheduler
ls: ./_output/dockerized/bin/linux/amd64/kube-scheduler: No such file or directory
```

**Proposed Solution:**
Specify in the page that the instructions are applicable only to Linux computers.
For MacOS users, the instructions are to execute the following command (I have omitted most of the (very verbose) output).

```
build/run.sh make kube-scheduler
[...]
+++ [0918 23:23:12] Placing binaries
+++ [0918 23:23:15] Syncing out of container
+++ [0918 23:23:15] Stopping any currently running rsyncd container
+++ [0918 23:23:15] Starting rsyncd container
+++ [0918 23:23:17] Running rsync
+++ [0918 23:23:20] Stopping any currently running rsyncd container

ls -l ./_output/local/bin/darwin/amd64/kube-scheduler
-rwxr-xr-x  1 neo  staff  51506808 Sep 18 22:54 ./_output/local/bin/darwin/amd64/kube-scheduler
```

Now we have a Linux binary in the location indicated by the page.

Please note that I am giving for granted that the requirements for a container build are available on the computer. Instructions on the dockerized build can be found at https://github.com/kubernetes/kubernetes/tree/master/build

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/

**Comment by sftim** [comment]
Thanks for the suggestion
/priority backlog

**Comment by bennythejudge** [comment]
> Thanks for the suggestion
> /priority backlog

@sftim Thanks for the reply. Could I try to propose the change via a PR?

**Comment by sftim** [comment]
@bennythejudge absolutely!
See https://kubernetes.io/docs/contribute/ (if you haven't already) for tips.
