### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by CosmicSage** [kubernetes/website#16456]
In Kubernetes website/content/en/docs/concepts/services-networking/ingress.md 
Line No. 322 term "CN" is not explained 
Please explain the meaning of CN in context

**Comment by sftim** [comment]
If anyone is picking this issue up and isn't sure what _CN_ stands for in this context, it means “common name“. See https://knowledge.digicert.com/solution/SO7239.html for a longer explanation.

**Comment by sftim** [comment]
Think this is done.
@CosmicSage do you agree?

**Comment by CosmicSage** [comment]
@sftim Yes Okay
