### ISSUE TITLE
Improve link from “Helm chart” glossary entry to Helm docs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16463]
**This is a Feature Request**

**What would you like to be added**
The glossary entry for [Helm chart](https://kubernetes.io/docs/reference/glossary/?all=true#term-helm-chart) has a full link to https://github.com/kubernetes/helm/blob/master/docs/charts.md in the metadata for that entry.
There is official Helm documentation and it would be better to link there, specifically to https://helm.sh/docs/developing_charts/

To see the part of this glossary entry that I'm talking about, visit https://github.com/kubernetes/website/blame/master/content/en/docs/reference/glossary/helm-chart.md#L5

**Why is this needed**
This is a minor improvement. If any page uses a [Hugo shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/) to include that glossary entry, and a reader clicks on that glossary entry, the reader will follow a hyperlink that is helpful but could be better.

**Comments**
If anyone would like help getting started with this issue, mention me (`@sftim`) and I will try to provide pointers. See [Participating in SIG Docs](https://kubernetes.io/docs/contribute/start/#participating-in-sig-docs) to learn more about how to get help if needed.

/language en
/kind feature
/priority backlog
/good-first-issue

**Comment by sftim** [comment]
This feature request is suitable for new contributors. It's a low priority; if you have already made SIG Docs contributions, consider leaving this one so that another person can find it.

**Comment by conwaychriscosmo** [comment]
I want to confirm that the task is to change website/content/en/docs/reference/glossary/helm-chart.md line 5 from ```full_link: https://github.com/kubernetes/helm/blob/master/docs/charts.md``` to ```full_link:https://helm.sh/docs/developing_charts/```  Is there anything I am missing?

**Comment by sftim** [comment]
@conwaychriscosmo you haven't missed anything; this one is a simple fix

**Comment by vishakhanihore** [comment]
@sftim Please close the issue as its already resolved
