### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/website#16482]
**This is a Bug Report**

**Problem:**
'creating a sample user' link in https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui points to a wrong URL

**Proposed Solution:**
Update the link to point to the right wiki or example location. 

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui

**Comment by aimeeu** [comment]
Hi @savitharaghunathan - the 1.16 version of the documentation no longer contains a _creating a sample user_ link in that section. 
1.15 [page](https://v1-15.docs.kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui)
1.16 [page](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui) 

If you need help creating a sample user, you could ask in the #sig-ui channel in the [Kubernetes slack](http://slack.k8s.io/) instance.

/sig ui

**Comment by savitharaghunathan** [comment]
@aimeeu, In that case, I think the link should be removed instead of pointing to a different page. What are your thoughts on that?

**Comment by savitharaghunathan** [comment]
@aimeeu, Thanks for the clarification. 

/close
