### ISSUE TITLE
Issue with /docs/user-guide/thirdpartyresources/

### ISSUE THREAD

**Issue by msiebuhr** [kubernetes/website#1648]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The section **Creating ThirdParty resources** doesn't mention the name `CronTab` (except in the resulting URL for the resource).

Yet it is oft referenced in the following section, **Creating Custom Objects**. Where does the name come from?

**Proposed Solution:**

Wrong `metadata.name`, perhaps? Or is it parsed from that?

**Page to Update:**
http://kubernetes.io/docs/user-guide/thirdpartyresources/

**Comment by msiebuhr** [comment]
Ah. Re-reading the page, it is sort-of-explained in **Structure of a ThirdPartyResource**, but it refers to the `kind`-property, which is set to `ThirdPartyResource` in the example that follows...

**Comment by tengqm** [comment]
The TPR resource is gone.
