### ISSUE TITLE
There's a merge conflict on the website

### ISSUE THREAD

**Issue by OJFord** [kubernetes/website#16492]
**Problem:**

Merge conflict visible here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node

**Proposed Solution:**
Resolve the conflict.

It seems this has happened before - #13941 - perhaps consider `pre-commit` ([`check-merge-conflict`](https://pre-commit.com/hooks.html)) or similar tooling to prevent it in future?

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node

**Comment by sftim** [comment]
/kind bug
/close
Fixed in #16497 (I think)
