### ISSUE TITLE
Minor doc Issue with k8s.io/docs/setup/learning-environment/minikube/

### ISSUE THREAD

**Issue by f-ruta** [kubernetes/website#16506]
**This is a Bug Report**

**Problem:**
Step2 reads :
    
    Let’s create a Kubernetes Deployment using an existing image named echoserver, which is a 
    simple HTTP server and expose it on port 8080 using --port.

    
    kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
    
When executing the command listed above, the following error is returned:
    
    kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080
    kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future 
    version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.   
    deployment.apps/hello-minikube created
    
**Proposed Solution:**
Update the document to avoid using a deprecated option.

**Page to Update:**
https://kubernetes.io/docs/setup/learning-environment/minikube/

**Comment by aimeeu** [comment]
Hi @f-ruta - thanks for bringing this to our attention.

/priority important-soon
