### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by iMerica** [kubernetes/website#16507]
When Googling "Hello World k8s", this article is among the top 5 articles in the search results. 

Unfortunately the article doesn't actually "Hello World" at all.  It doesn't actually let the reader see the results of their work.

I suggest completing the tutorial with steps to see something in a browser from an nginx deployment (the fruit of the labor). Otherwise the tutorial is like video of a craftsman building something and never displaying the final result.

**Comment by sftim** [comment]
When I search Google for “Hello World k8s”, this article isn't in the top 5 results for me.

The [page](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/) could do with mentioning in a _what's next_ section about how to expose that Deployment to the internet. If the reader wants to see something, exposing the Deployment is a good way to make that happen.

/priority backlog
