### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by npf** [kubernetes/website#16505]
**This is a Bug Report**

**Problem:** 
Module 2 - Deploy an app talks about deployments, and then about pods without explaining the relation between them.

**Proposed Solution:**
Explain.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by npf** [comment]
May be sufficient to just say that the relation is explained in the next section

**Comment by sftim** [comment]
Thanks for the suggestion
/triage backlog

**Comment by sftim** [comment]
Oops
/priority backlog
