### ISSUE TITLE
The tool of markdown maybe have a bug.

### ISSUE THREAD

**Issue by diguage** [kubernetes/website#16510]
I sent a PR for fixing a document style bug:  [fix markdown syntax by diguage · Pull Request #16452 · kubernetes/website](https://github.com/kubernetes/website/pull/16452)

I review the render result, and I found the tool of Markdown maybe have a bug.

## Before I fix the error:

```
    On Fedora, edit `/etc/kubernetes/kubelet` to include this line:

    ```
    KUBELET_ARGS="--cluster-dns=10.254.0.10 --cluster-domain=kube.local --manifest-url=<manifest-url>`
    ```

Now, restart the kubelet. On Fedora, you would run:

    ```shell
    # Run this command on the node where the kubelet is running
    systemctl restart kubelet
    ```
```

<https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/>

![image](https://user-images.githubusercontent.com/2121467/65403972-1fbc0b00-de09-11e9-9889-b2b40f8706a0.png)

**The four spaces shoud be render as the source code block. So the source code blocks in the four spacke block do not be render as the source code.**

The blockquote tag should be used in the case.

### After:

```
> On Fedora, edit `/etc/kubernetes/kubelet` to include this line:
>
> ```
> KUBELET_ARGS="--cluster-dns=10.254.0.10 --cluster-domain=kube.local --manifest-url=<manifest-url>`
> ```
>
> Now, restart the kubelet. On Fedora, you would run:
>
> ```shell
> # Run this command on the node where the kubelet is running
> systemctl restart kubelet
> ```
```

<https://deploy-preview-16452--kubernetes-io-master-staging.netlify.com/docs/tasks/configure-pod-container/static-pod/>


![image](https://user-images.githubusercontent.com/2121467/65404774-80007c00-de0c-11e9-9af1-f5f7c9cf91c3.png)


**But the blockquote tag does not be render in the right way.**

### Right render

But it should render like as following (Preview on VS Code):

![image](https://user-images.githubusercontent.com/2121467/65404383-d1a80700-de0a-11e9-8004-8e09872055e9.png)

**Comment by sftim** [comment]
The way I see it, the rendering via Hugo is canonical. Visual Studio Code's preview is a hint at how the source might get rendered.

Would you agree with 
/triage support
@diguage?

**Comment by diguage** [comment]
@sftim 

> Visual Studio Code's preview is a hint at how the source might get rendered.

Sorry, I don't agress with the statement. 

The `>` tags are a blockquote tag of Markdown.

There are two guides for Markdown which explains the syntax.

* [Basic Syntax | Markdown Guide](https://www.markdownguide.org/basic-syntax/#blockquotes-1)
* [Mastering Markdown · GitHub Guides](https://guides.github.com/features/mastering-markdown/)

**Comment by sftim** [comment]
/remove-triage support
Sounds like there's more to discuss.

**Comment by aimeeu** [comment]
Hi @diguage - I think Hugo is rendering the Markdown correctly.

Repeating part of the comment I left on your PR #16452: 

Thanks for all the detail! Using blockquote '>' syntax: markdownguide.org's [blockquotes with other elements](https://www.markdownguide.org/basic-syntax/#blockquotes-with-other-elements) section says "Blockquotes can contain other Markdown formatted elements. Not all elements can be used — you’ll need to experiment to see which ones work."    So nesting code block syntax inside of blockquote syntax doesn't work.

---------------------------------------------------------------------------
For everyone reading this Issue: regarding the 4 spaces (or 1 tab) at the beginning of L135-139: if you want some text to show up exactly as you write it, without Markdown doing anything to it, indent every line by at least 4 spaces (or 1 tab). 
Rendered:
![issue16510](https://user-images.githubusercontent.com/26799583/65458813-0b314000-de14-11e9-96a6-e5e955546a93.png)

Code:
![issue16510-code](https://user-images.githubusercontent.com/26799583/65459049-94e10d80-de14-11e9-9692-2cbe3c774c1a.png)


Looking at the [source code file](https://github.com/kubernetes/website/blame/master/content/en/docs/tasks/configure-pod-container/static-pod.md#L135), _the 4 spaces (or 1 tab) at the beginning of each line 135-139 is a mistake._  Those spaces should be removed - those lines should not be a blockquote.


If you install [Hugo](https://gohugo.io/), you can [test your changes locally](https://kubernetes.io/docs/contribute/intermediate/#view-your-changes-locally). Hugo uses the [BlackFriday](https://github.com/russross/blackfriday) Markdown processor.

**Comment by diguage** [comment]
I used to use the GitHub Format Markdown. 
Markdown has too many dialects. There are many differences amount the dialects. 
Let me learn the BlackFriday Markdown processor. 😆

**Comment by sftim** [comment]
@diguage are you OK to close this issue?
