### ISSUE TITLE
Broken link in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by ipuustin** [kubernetes/website#16515]
**This is a Bug Report**

**Problem:**
Halfway down https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ there's a link "special attention to upgrade" pointing to https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-14/ . That link is broken (404).

**Proposed Solution:**
Find out why the target page was removed, then either fix the link or remove it.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by sftim** [comment]
Hmm. I thought that there would be a page https://v1-15.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

(equivalent to https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/)
but there isn't.

Anyway, it's a valid issue.
/priority backlog
/kind bug

**Comment by RA489** [comment]
@ipuustin The broken link seems to be fixed. Can you recheck so that we can close this issue?

**Comment by ipuustin** [comment]
Works now! Closing.
