### ISSUE TITLE
Image Pull Secret on SA is not properly documented anywhere

### ISSUE THREAD

**Issue by colemickens** [kubernetes/website#1652]
http://kubernetes.io/docs/user-guide/images/#specifying-imagepullsecrets-on-a-pod

>However, setting of this field can be automated by setting the imagePullSecrets in a serviceAccount resource.

No mention of how to do so or pointers at additional docs.

Worse yet:

http://kubernetes.io/docs/user-guide/kubectl/kubectl_create_secret_docker-registry/

> When creating applications, you may have a Docker registry that requires authentication. In order for the nodes to pull images on your behalf, they have to have the credentials. You can provide this information by creating a dockercfg secret and attaching it to your service account.

And then the example that follows doesn't actually do the "attach it to your service account" part...

**Comment by derfred** [comment]
FWIW you can find the answer here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Comment by sftim** [comment]
Similar to #20910
