### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by drejmar** [kubernetes/website#16544]
**This is a Bug Report**

**Problem:**
Formatting of example-ingress.yaml is messed up

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress-resource

**Comment by drejmar** [comment]
https://github.com/kubernetes/website/pull/16545

**Comment by aimeeu** [comment]
@drejmar thanks for submitting a PR to fix this issue!
