### ISSUE TITLE
Issue with k8s.io/docs/home/ Example buttons do not work

### ISSUE THREAD

**Issue by rschooley** [kubernetes/website#16542]
**This is a Bug Report**

**Problem:**
The "kubectl example" and "curl example" buttons do not currently work.  

Bootstrap fails to load and I'm guessing the toggle for the details panel is handled by that.

**Proposed Solution:**
Make sure the file is deployed: https://kubernetes.io/js/bootstrap-3.3.7.min.js
or just use a CDN

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16

**Additional Information**
![Screen Shot 2019-09-24 at 11 41 54 PM](https://user-images.githubusercontent.com/473595/65567982-31470500-df26-11e9-8c65-038c17dae5d2.png)

**Comment by savitharaghunathan** [comment]
1.16 is pointing to 3.3.7. Updating it to point to v4.3.1 (https://kubernetes.io/js/bootstrap-4.3.1.min.js )should make these buttons work.

**Comment by medmedchiheb** [comment]
Yes should work but the change must be made in the [api reference generator](https://github.com/kubernetes-incubator/reference-docs)

**Comment by aimeeu** [comment]
@medmedchiheb Thanks for assigning this to yourself! I'm not very familiar with the kubernetes-incubator/reference-docs.  Is it possible to point to a CDN instead of updating bootstrap.min.js ?

**Comment by medmedchiheb** [comment]
It's just a quick fix, as you can see from the template.
And then you can test by executing update-reference-docs.

https://github.com/kubernetes-incubator/reference-docs/blob/88f6483855ac68ee6041cd8e90169f7f5268dc2b/gen-apidocs/generators/html.go#L604

**Comment by aimeeu** [comment]
this is two-fold: 1) update the code in the kubernetes-incubutor/reference-docs project (longterm fix); and 2) update kubernetes/website/static.....     See Slack [thread](https://kubernetes.slack.com/archives/C1J0BPD2M/p1569439245104900)

**Comment by medmedchiheb** [comment]
already fixed bootstrap version

https://github.com/kubernetes-incubator/reference-docs/blob/6c1496ba33b6aed9ab6af886412e8487f534194e/gen-apidocs/generators/html.go#L604

**Comment by aimeeu** [comment]
/remove-priority backlog
/priority critical-urgent

Updating the current generated API doc index.html is critical because the buttons don't work (see #16263 for v1.15). Long-term fix has already been added to kubernetes-incubator/reference-docs.
