### ISSUE TITLE
StatefulSet 1.5 umbrella 

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#1655]
I've written a detailed docs plan for StatefulSet for 1.5.  There is a lot to do between now and the Docs freeze.  

It was too dynamic to use a github issue or markdown.  I used a Google doc:

https://docs.google.com/document/d/1F5UHlYLDmS2V-J4xPDwFiLAujOk-kt03qKK3Wgthsnc/edit#

I made it world viewable and commentable for anyone in Sig-Apps which should cover most interested people, but DM me (erictune) on slack if you need an invite or whatever.

If you are interested in helping identify missing topic or writing docs, take a look.  Warning: it is a long doc.

**Comment by chrislovecnm** [comment]
When is the date for doc freeze? Will review when I can

**Comment by enisoc** [comment]
Nov 25: Docs PRs out for review.
Dec 2: Docs PRs merged.

https://github.com/kubernetes/features/blob/master/release-1.5/release-1.5.md#november-18-2016---december-8-2016

**Comment by jimmycuadra** [comment]
Eric, will you make the "rename plan" linked from that Google Doc world readable, please? Thanks for putting this together!

**Comment by enisoc** [comment]
I've changed the link to point to the published version: https://github.com/kubernetes/kubernetes/issues/35534

**Comment by bluecmd** [comment]
FWIW, http://kubernetes.io/docs/api-reference/apps/v1beta1/definitions/ is not linked into the navigation tree (reports "Support").

**Comment by enisoc** [comment]
@bluecmd Thanks for reporting. I think I found where someone is trying to fix it, although the PR appears to be stuck: https://github.com/kubernetes/kubernetes.github.io/pull/1947
