### ISSUE TITLE
Need sync: Kubernetes case study content on kubernetes.io with that on cncf.io 

### ISSUE THREAD

**Issue by MieSato** [kubernetes/website#16567]
**This is a Bug Report**

**Problem:**
- JP's contributors have translated some of K8s case studies on cncf.io site.
- We are going to publish those JP content here: 
https://kubernetes.io/ja/case-studies/
- However, we found that the English content on K8s site are little bit different from that on CNCF site.  

ex.) Amadeus' "Challenge", "Solution", "Impact", etc. on these two site are not identical.
https://www.cncf.io/case-study/amadeus/
https://kubernetes.io/case-studies/amadeus/
  
Translated case studies are:
Amadeus, Ant financial, City of Montriol, Nordstorm, and SOS International.
  
**Proposed Solution:**
Sync each content on both site.

**Page to Update:**
All of case studies under https://kubernetes.io/case-studies/ , 
but for now, these 5 pages;
https://kubernetes.io/case-studies/amadeus/
https://kubernetes.io/case-studies/ant-financial/
https://kubernetes.io/case-studies/city-of-montreal/
https://kubernetes.io/case-studies/nordstrom/
https://kubernetes.io/case-studies/sos/

**Additional Information:**
According to CNCF staff, they published those case studies on CNCF site first, and then created those HTML files to add them to K8s site.

**Comment by sftim** [comment]
I think:
/kind cleanup
/priority backlog

**Comment by dankohn** [comment]
I think SIG-Docs would be happy to accept pull requests to make the English version match CNCF.

**Comment by MieSato** [comment]
(Hi Dan, thank you for your help.) 
According to SIG-Dogs, the k8s case studies are different from the ones on the CNCF site to help maintain the SEO of the Kubernetes site, instead of having exact duplicates.
So, I will close this issue. You (K8s site) do not need to sync the content with those on cncf site. 
I will ask our contributors to check out k8s site and update their translation. 
Thank you so much.
