### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/topology-manager/

### ISSUE THREAD

**Issue by MJayakumar** [kubernetes/website#16561]
**This is a Bug Report**
just a simple spelling.  It says "Topology Manager polices preform". It should say "policies perform"

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/priority backlog
/good-first-issue
Thanks for mentioning this @MJayakumar

**Comment by manyatripathi** [comment]
I would like to update this.

**Comment by furukawa3** [comment]
This issue seems to be fixed[1].  I'll try to close it.
[1]https://github.com/kubernetes/website/search?q=polices&unscoped_q=polices

**Comment by furukawa3** [comment]
Oops. sorry.

**Comment by sftim** [comment]
Dealt with in PR #16580.
/close
