### ISSUE TITLE
Feature request: I would like to know the version of the original file for a translated file 

### ISSUE THREAD

**Issue by feloy** [kubernetes/website#16571]
**This is a Feature Request**

**What would you like to be added**

As a translator of documentation pages, it is difficult for me to know on which version of the original file is based a translation.

I would like to know precisely on which version of the original file is based a translation, so I can update the translation with all the updates made in the original file since the last translation of this file.

A solution would be to indicate the hash of the git commit containing the version of the file used as reference for the translation.

**Example**

***I want to translate in French the file content/en/docs/reference/kubectl/docker-cli-to-kubectl.md which is not yet translated***

```
$ git checkout -b translate-docker-cli-to-kubectl
$ git rev-parse HEAD
d4d55a70394f8389d72c7a2052c62fcb99505de0
mkdir -p content/fr/docs/reference/kubectl
cp content/en/docs/reference/kubectl/docker-cli-to-kubectl.md content/fr/docs/reference/kubectl/docker-cli-to-kubectl.md
```
Then I edit the `content/fr/docs/reference/kubectl/docker-cli-to-kubectl.md` to insert the variable `original` on top of the document:

```
---
title: kubectl for Docker Users
content_template: templates/concept
reviewers:
- brendandburns
- thockin
original: d4d55a70394f8389d72c7a2052c62fcb99505de0
---
```

***Later, I want to know if there have been changes in the file since the latest translation***
```
git diff  d4d55a70394f8389d72c7a2052c62fcb99505de0...master -- content/en/docs/reference/kubectl/docker-cli-to-kubectl.md 
```

**Comment by ebcarty** [comment]
Perhaps we can bring this up in the next [SIG-Docs call](https://github.com/kubernetes/community/tree/master/sig-docs#meetings) to agree upon the best method to ensure translations have a reference to their original English version and determine when they should/can be updated.

**Comment by zacharysarah** [comment]
@feloy Existing scripts may be able to help you. Have you looked at https://github.com/kubernetes/website/tree/master/scripts, specifically https://github.com/kubernetes/website/blob/master/scripts/upstream_changes.py? 

@remyleone 👋 Any input?

**Comment by feloy** [comment]
Hi @zacharysarah yes I tried these scripts and discussed with @remyleone . The problem is that these scripts consider that the original document of reference is the corresponding document at the date of the last update of the translated version.

This is not true in several cases:
- if the translated doc is committed long after the original doc is taken as reference. During this time, the original doc can be modified, and these modifications will be lost
- if a translated document is updated to correct some mistakes but do not sync all the differences appeared in the original doc, this date will be get as reference, which is also problematic

**Comment by gochist** [comment]
Hi @feloy ! You may know that Korean l10n team is taking a little different approach. The team is running team milestone branches and does not move forward to the next branch with any outdated content left in the current milestone branch which is managed by issues. Those issues are generated by [helper script](https://raw.githubusercontent.com/kubernetes/website/master/scripts/diff_l10n_branches.py). This branching model makes the team know that which version of the original file is based on, even if the file is renamed. And it helps to control the version of a whole contents not a single page. But it is true that the model is hard to understand and it requires very collaborative efforts.

**Comment by jygastaud** [comment]
I like the @feloy idea.
It doesn't change almost anything for current workflow and give translator the ability to have better / advanced workflow.

Also, it can also be an important information for newcomer to be able to upgrade outdated doc.

/remove-lifecycle rotten

**Comment by tengqm** [comment]
/remove-lifecycle stale

This is still relevant.

When I was going through the Chinese localization contents and resyncing big changes, one possible improvement that came to my brain was something like [pseudo-versions in Go modules](https://golang.org/cmd/go/#hdr-Pseudo_versions). For example, if I'm now creating or updating `/docs/foo/bar.md` from English to Chinese, I will need to add the following line to the localized version

```
<!-- docsync: vX.Y.0-yyyymmddhhmmss-abcdefabcdef  -->
```
where,

- `X.Y` should be `1.18` because I'm working on the master today, 
- `yyyymmddhhmmss` is a timestamp string for formatting date like what you'll get from `date "+%Y%m%d%H%M%S"` shell command,
- `abcdefabcdef` is the current master commit ID.

The above comment line can be automatically generated using a short script, then next time when you want to check what have been updated, you get a baseline. You know when the page was last synced. You can then come up with new tools to enumerate PRs that touched a specific file, or even the changes made since the last time the page was updated.

**Comment by zacharysarah** [comment]
@tengqm I'm intrigued by the approach. @seokho-son @irvifa 👋 Any input on [this idea](https://github.com/kubernetes/website/issues/16571#issuecomment-678072606)?

**Comment by sftim** [comment]
@feloy there's now a related tool: `scripts/lsync.sh`

Might be useful?

**Comment by sftim** [comment]
I propose to:
/remove-priority important-soon
/priority important-longterm
/triage accepted
