### ISSUE TITLE
Issue with k8s.io/docs/reference/glossary/ Typo in 'Container runtime interface (CRI)'

### ISSUE THREAD

**Issue by shirishk** [kubernetes/website#16588]
**This is a Bug Report**

**Container runtime interface (CRI)**
The container runtime interface (CRI) is an an API for container runtimes to integrate with kubelet on a node.[-]
For more information, see the CRI API and specifications.

**Problem:**
Typo "an an API"

**Proposed Solution:**
Should be  "an API"

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?fundamental=true

Kubernetes Version: v1.16

**Comment by sftim** [comment]
Thanks for spotting this @shirishk 

/priority backlog
/language en
/good-first-issue

**Comment by Vageesha17** [comment]
I would like to solve this issue.

**Comment by sftim** [comment]
Anyone who'd like to submit a pull request is welcome. It looks like @jammerful has already made a start.

**Comment by hvaara** [comment]
This has been fixed in #16612
