### ISSUE TITLE
Document (or improve) “Autoscale your kubernetes cluster”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16583]
**This is a Feature Request**

I searched DuckDuckGo, Bing, and Google for “Autoscale your kubernetes cluster”. None of these showed results from sites that SIG Docs look after.

**What would you like to be added**
Add a new Task page that covers how to deploy the cluster autoscaler and why you might want to do so.
Signpost readers to other kinds of autoscaling (eg HorizontalPodAutoscaler).

**Why is this needed**
Cluster operators want to manage an elastic pool of Nodes so that they can meet demand for Pod resources (CPU, memory), whilst managing costs and maintaining availability.
Documentation helps them know how to do that.

**Comments**
Part of / related to #4493

**Comment by sftim** [comment]
Still want this
/remove-lifecycle stale

**Comment by sftim** [comment]
Somewhat related: #19207

**Comment by tengqm** [comment]
This is not a documentation issue, honestly speaking.

- You will rely on your cloud provider to support this feature.
- You will need a standby pool of Nodes, which will introduce additional mgmt/financial costs.
- You will need a solution/framework (i.e. a cluster auto-scaler) to trigger the scaling. In which,
   * you will need to tune many knobs to get things work
   * you will want the solution works the moment it is deployed
   * you will need node-level monitoring and eventing facililty
   * you will need cool down period
   * you will need to deal with nodes that are removed from the cluster, i.e. put them back into the pool; wipe out all data before reusing them for other purposes ...

**Comment by sftim** [comment]
I agree that it's not straightforward. However at a minimum I would like the reader to learn that https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler exists, even if they don't get to understand all the moving parts from reading one page.

Good news: “Autoscale your kubernetes cluster” now has a search result from the blog as top match on Google, the most popular search engine on the web.
Bad news: it's for Kubernetes v1.3 which is now a bit dated.

/remove-lifecycle rotten
/remove-priority important-longterm
/priority awaiting-more-evidence

**Comment by tengqm** [comment]
Thanks for the info, @sftim 

Just checked the cluster-autoscaler project you mentioned and happy to see two facts:

- It is still alive and active!
- It has support to quite a few cloud vendors (GCE, AWS, Azure, OpenStack, DigitalOcean ...)

So ... I agree to add some general texts for this topic, with pointers to the cluster-autoscaler project.

**Comment by kbhawkey** [comment]
Related to PR #24415
