### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by dblees** [kubernetes/website#16589]
**This is a Bug Report**

 Hi. this is in regards to the tutorial having 'kubectl run' .. says it is deprecated.

**Problem:**
This is the second page after continue in the tutorial ..
kubectl run kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080

**Proposed Solution:**
Convert this to use kubectl apply or kubectl create .. whatever is appropriate here.
I assume apply overwrites an existing where as create expects the state to be clean.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
Step 2 of 3

Kubernetes Version: v1.16

My apologies if this is not the appropriate means to report this feature deprecation. I just think the intention here is to have the tutorial match the version without deprecation warnings. thanks for listening.

**Comment by sftim** [comment]
@dblees thanks for reporting this!
/priority backlog

**Comment by BenHall** [comment]
@dblees Thanks for letting us know! We are working on this and being tracked at #15512

**Comment by BenHall** [comment]
Sorry for the delay on this. We thought it had a larger impact than it did.

The fix was applied in https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/839fc4c2160f821194418d16bf14c1cde9512cb5

**Comment by sftim** [comment]
I'm happy to 
/close
