### ISSUE TITLE
Determine which turn-up guides can be replaced with kubeadm

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#1659]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

There are many outdated pages that do various flavours of cluster turnup.

**Proposed Solution:**

Redirect to kubeadm http://kubernetes.io/docs/getting-started-guides/kubeadm/.

**Comment by errordeveloper** [comment]
Rather obvious targets would be:

[ ] http://kubernetes.io/docs/getting-started-guides/ubuntu/
[ ] http://kubernetes.io/docs/getting-started-guides/ubuntu-calico/
[ ] http://kubernetes.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/
[ ] http://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/
[ ] http://kubernetes.io/docs/getting-started-guides/fedora/fedora_ansible_config/

What is the best way to go about this?

**Comment by errordeveloper** [comment]
cc @pwittrock

**Comment by pwittrock** [comment]
Woot

**Comment by errordeveloper** [comment]
@pwittrock do you wanna discuss this?

**Comment by pwittrock** [comment]
@errordeveloper Yeah.  Slack?  Zoom?

**Comment by a-mccarthy** [comment]
@pwittrock, was there any decisions made about this issue?

**Comment by pwittrock** [comment]
@kubernetes/sig-cluster-lifecycle-misc Ideas?

**Comment by colemickens** [comment]
`kubeadm` directly (with manual IaaS provisioning?) or something like `kubernetes-anywhere` with a single `kubeadm`-powered stage?

**Comment by luxas** [comment]
/remove-lifecycle stale

SIG Cluster Lifecycle is looking into reprioritizing this in 2018

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by chrislovecnm** [comment]
You added the stale label btw

**Comment by luxas** [comment]
@chrislovecnm Sorry, I don't understand your comment?

**Comment by errordeveloper** [comment]
I've just cross posted on the mailing lists about this: https://groups.google.com/d/msg/kubernetes-sig-docs/GFnX8DRw7iY/8y3feBK5AAAJ.

cc @roberthbailey

**Comment by roberthbailey** [comment]
Thanks IIya. It would be great if we could reach out to owners directly for any getting started guides (where we know them) in case folks are filtering the mailing lists in their email. Also, it might be nice to provide a link in the email to the list of guides that we are talking about culling.

**Comment by errordeveloper** [comment]
Now tracked in https://github.com/kubernetes/website/issues/7278.
