### ISSUE TITLE
Need Chinese edition of https://kubernetes.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by plutonji** [kubernetes/website#16606]
**This is a Feature Request**

This page <https://kubernetes.io/docs/concepts/storage/persistent-volumes/> only have editions of English and Bahasa Indonesia.

**What would you like to be added**

Chinese edition of this document.

**Why is this needed**

Persistent volume is a basic and important concept of Kubernetes. We should have common languages' editions of this page and for me, it's Chinese.

**Comments**
I have translated this page and posted at [Gitbook](https://plutonji.gitbook.io/kubernetes/). Anyone could refer to my translation.

**Comment by ydcool** [comment]
WIP https://github.com/k8smeetup/website-tasks/issues/3501
