### ISSUE TITLE
Issue with /docs/user-guide/kubectl/kubectl_get/

### ISSUE THREAD

**Issue by jbauerrfid** [kubernetes/website#1662]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
`kubectl get pods -n <namespace>` does not work, because the flag `-n` is not recognized (at least not on Linux platform, see version info below). Response is "Error: unknown shorthand flag: 'n' in -n".

The -n flag is valid as documented on http://kubernetes.io/docs/user-guide/kubectl/kubectl_get/ . It seems other kubectl commands are affected as well.

**Proposed Solution:**
Workaround: `kubectl get pods --namespace <namespace>` works, but is more stuff to type.

**Page to Update:**
http://kubernetes.io/docs/user-guide/kubectl/kubectl_get/

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.10", GitCommit:"c3e367ec9eae7338ac4e2a57f293634891319b7c", GitTreeState:"clean", BuildDate:"2016-10-31T21:25:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tengqm** [comment]
This is no longer an issue. Please feel free to reopen it if the problem persists.
