### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by chillbilly79** [kubernetes/website#16624]
I am trying to follow this documentation to learn how to configure and use a persistent volume for a nfs share.  I realize this specific document says it is for a cluster with only one node.  I am suggesting to add another example that uses a cluster with multiple nodes,  The concepts that are not obvious to me from this documentation are how to set up the roles and cluster role binding.  A complete hello world type of example that uses a persistent volume on a cluster with multiple nodes would be great.

**Comment by sftim** [comment]
Thanks for the suggestion and feedback @chillbilly79 
/kind feature
/priority backlog
