### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-init-containers/

### ISSUE THREAD

**Issue by jpmolinamatute** [kubernetes/website#16623]
**This is a Bug Report**
**Problem:** the title of the page is debug init containers, but it doesn't say how to debug a container when it failed this is actually when we need to debug it

**Proposed Solution:** explain what other steps we can take to debug a failed container/pod

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-init-containers/.

**Comment by sftim** [comment]
It sounds like the improvement you want is for https://kubernetes.io/docs/tasks/debug-application-cluster/debug-init-containers/ to clearly tell readers what it's _not_ about. If readers want to learn about debugging Pod failure, using emphemeral containers, reading logs etc then this revised page can link to those other pages from its front matter.

Have I got that right @jpmolinamatute ?

**Comment by jpmolinamatute** [comment]
Hi! @sftim 

sure, that's one way to put it, the confusion that I was having is that the title talks about debugging, but there are not steps to do so. The article talks about how to get information of a container ( assuming that container is not in a failed state) and we need to debug when a container IS in a failed state. So my suggestion is either add steps to debug container is a failed state or change the title to something else.

**Comment by sftim** [comment]
Just to check, then: @jpmolinamatute you have a Pod (or several Pods) with an init container defined, and there is a problem with Pod startup. You wanted to learn about how to troubleshoot that issue and didn't find this page helpful. Have I understood?

Maybe there should be a Task page about “Debug Pod startup issues”, that can cover init container problems as well as other reasons for Pods failing to start cleanly.

**Comment by jpmolinamatute** [comment]
Correct! I thinks those two ideas plus the one from your first post

>  to clearly tell readers what it's _not_ about. If readers want to learn about debugging Pod failure, using emphemeral containers, reading logs etc then this revised page can link to those other pages from its front matter.

would be an excellent improvement to the documentation

**Comment by jpmolinamatute** [comment]
I missed this line in the documentation

`kubectl logs <pod-name> -c <init-container-2>`

I think that line should be the main core of the page (according to the title) I think more discussion around it should be made. Talk about when your init-container is in a failed state this is the commande that people should start looking
