### ISSUE TITLE
More explanation about shared storage between pods

### ISSUE THREAD

**Issue by lukos** [kubernetes/website#16635]
**This is a Feature Request**

**What would you like to be added**
Currently, the documentation around persistent volumes only covers some very specific use-cases, mainly around concepts that might work as an introduction to the topic or in development but not for production use-cases.

Currently, I am trying to understand how to implement PVs in production for pods so that all pods in a single service share some storage and other pods in another service get a separate PV for theirs.

Obviously, we could create PVs manually and add annotations but the docs seem to imply that in cloud scenarios, dynamic provisioning using PVCs is preferred so it is not clear how this should work. As I understand it, if two different types of pod requested the same type of storage, they might well be given the same PV to mount, which means all data would be visible to all services.

**Why is this needed**

This is needed because if the docs only cover introductory topics and not common production scenarios, it will either be harder or will lead people to implementing their own architectures which might lead to poor feedback for using K8S in production scenarios.

**Comment by savitharaghunathan** [comment]
/language en
/kind feature
/priority backlog

@lukos Are you looking for a specific volume type or in general?

Should this be added to https://github.com/kubernetes/examples/tree/master/volumes ?

**Comment by jimangel** [comment]
This sounds like good fit for https://kubernetes.io/docs/tasks/

**Comment by msau42** [comment]
For your use case, I would recommend using a shared storage backend like NFS.  All the pods in your service can share the same PVC pointing to the same NFS share.  And each service will have its own sharable PVC.

**Comment by lukos** [comment]
Thanks @msau42 I have found a solution doing exactly what you have said although it would be cool to be more explicit about this in the docs since it is a very common use-case that is not clearly discussed. I am happy to create a PR if that is desirable?

**Comment by savitharaghunathan** [comment]
Thank you @msau42 for the input. @lukos, please feel free to create a PR. If you would like to collaborate on creating a task page, let me know. Otherwise I will Unassign myself.

**Comment by savitharaghunathan** [comment]
@lukos, Are you still interested to work on this issue?
