### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by fritz-c** [kubernetes/website#16659]
**This is a Bug Report**

**Problem:**
The suggested method for applying bash completion to an alias does not work with the builtin version of bash on macOS. `source <(kubectl completion bash)` will not leave the `__start_kubectl` function defined in the shell that calls it, so `complete -F __start_kubectl k` will fail.

**Proposed Solution:**
Add a troubleshooting note that mentions that it might be necessary to put the completion script into a file first, as demonstrated in the following snippet from my personal solution:
```sh
if command -v kubectl > /dev/null; then
  # Put the completion code into a file, execute and delete it
  # We have to call it this way in order for __start_kubectl to be persisted
  # in the shell
  KUBECTL_COMPLETION_PATH="/tmp/.kubectl-completion-bash"
  kubectl completion bash > "$KUBECTL_COMPLETION_PATH"
  source "$KUBECTL_COMPLETION_PATH"
  rm "$KUBECTL_COMPLETION_PATH"

  alias k=kubectl
  
  # Completion for the alias
  complete -F __start_kubectl k
fi
```

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/

**Comment by sftim** [comment]
Thanks for the suggestion
/priority backlog
