### ISSUE TITLE
Issue with k8s.io/pt/docs/concepts/

### ISSUE THREAD

**Issue by fxpires** [kubernetes/website#16665]
**This is a Bug Report**

**Problem:** Blank page for pt_BR lang (i.e.: no content).

**Proposed Solution:** Add content / Translate content from en lang.

**Page to Update:**
k8s.io/pt/docs/concepts/

**Comment by hvaara** [comment]
Thanks for the report!
Tracked in #13939

/language pt
/sig docs
/priority backlog
