### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-service-account/

### ISSUE THREAD

**Issue by vivisquirrel** [kubernetes/website#16671]
**This is a Bug Report**

The hyperlink in 'automatically set' is unavailable. after click it, '404 Page not found' is shown in browser. 

**Problem:**
hyperlink in doc is unavailable.  the hyperlink content is https://kubernetes.io/docs/user-guide/working-with-resources/#resources-are-automatically-modified. 
**Proposed Solution:**
update the hyperlink to correct URL.
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the report
/priority backlog
/kind cleanup

**Comment by hvaara** [comment]
Page linked to prior to being removed: https://github.com/kubernetes/website/blob/bfa604351ff04bd35c4d5af5cb24adae59ef2bf3/docs/user-guide/working-with-resources.md
