### ISSUE TITLE
Init container use case document clarification

### ISSUE THREAD

**Issue by shouichi** [kubernetes/website#16686]
The current "Using init containers" section makes the following statement. Is this correct? Shouldn't it be something like "less vulnerable"?

> Init containers can securely run utilities that would make an app container image less secure.

https://github.com/kubernetes/website/blob/c156ef8c3d0a496d4b028c8ba8acbab3996fe07d/content/en/docs/concepts/workloads/pods/init-containers.md

**Comment by sftim** [comment]
Maybe the language can be clearer.
If the app container had access to imaginary DangerousToolX, then this creates a risk affecting information security.
If the init container has that access but the app container does not, then the init container can securely run the utility. Allowing the _app container_ to run that utility, would (in this thought experiment) make that app container [image] less secure.

I think the meaning is accurate but perhaps hard to follow. Does that make sense @shouichi ?

**Comment by shouichi** [comment]
By running the imaginary DangerousToolX in init container (not in app container), it makes app container more secure?

(I'm not native, sorry if the above doesn't make sense.)

**Comment by sftim** [comment]
> By running the imaginary DangerousToolX in init container (not in app container), it makes app container more secure?
Yes, that's what the page is saying.

In theory https://kubernetes.io/ja/docs/concepts/workloads/pods/init-containers/ has a similar explanation in Japanese; maybe that's useful?

**Comment by shouichi** [comment]
Japanese version states the same thing quite differently (it is like, "Init container can run utility tools that you don't want to run in app container for security reasons.").

Maybe just my English problem but "less secure" sounds strange. It would be great if it clarifies what it means.

Thanks!

**Comment by sftim** [comment]
It sounds like there's room to tweak the wording here.
/priority backlog

**Comment by oke-py** [comment]
Japanese version might be outdated. The change below is not reflected.
https://github.com/kubernetes/website/commit/e1ec9a62462b142a3d0a9a1e7246a4bfef7a739b#diff-6a517c74ebea4dd5397bcefb913fc043

**Comment by christophercarney** [comment]
Perhaps tweak the wording to include something to the effect of separation of duties? The goal is to explain that the init container concept is more secure because once the init container runs its "DangerousToolX" and successfully bootstraps the pod the init container dies, thus limiting the attack surface (i.e. scripts or other tools) that you don't want lying around in one monolith pod.
