### ISSUE TITLE
Translate concepts/extend-kubernetes/api-extension/custom-resources/ into Japanese

### ISSUE THREAD

**Issue by hasebe** [kubernetes/website#16685]
**This is a...**
- [x] Feature Request
- [ ] Bug Report

**Problem:**
No `concepts/extend-kubernetes/api-extension/custom-resources.md` in Japanese.

**Proposed Solution:**
Copy a file from en contents to `content/ja/docs/concepts/extend-kubernetes/api-extension/custom-resources.md` and translate it into Japanese.

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/extend-kubernetes/api-extension/custom-resources/

**Comment by cstoku** [comment]
@hasebe 作業いかがでしょうか？

**Comment by hasebe** [comment]
@cstoku 作業が遅れておりまして、申し訳ございません。
今週末くらいに完了する予定で進めております。

**Comment by inductor** [comment]
@hasebe 特に急いでるってわけでもないですが、どんなかんじでしょうか〜（念の為確認）:eyes:

**Comment by hasebe** [comment]
@inductor 遅くなってしまい大変申し訳ございません＞＜
今8割方できているので、今日中にあげます！

**Comment by inductor** [comment]
close
