### ISSUE TITLE
Security Vulnerabilities found in kubectl v1.12.0

### ISSUE THREAD

**Issue by SrishT** [kubernetes/website#16719]
I work for a product which uses libraries from k8s.io. As part of a static code analysis we performed on our code using Checkmarx, we found a few high risk security vulnerabilities in the libraries that we are using from k8s.io. The kubectl version we are currently working with is `v1.12.0`.
 
We found 2 occurrences of `Reflected XSS` in the following files :-

- File Name : `k8s.io/apimachinery/pkg/util/httpstream/httpstream.go`
Method : `func Handshake(req *http.Request, w http.ResponseWriter, serverProtocols[]string) (string, error) {`
Code Snippet
```
....
124. clientProtocols :=req.Header[http.CanonicalHeaderKey(HeaderProtocolVersion)]
....
143. fmt.Fprintf(w, "unable to upgrade: unable to negotiate protocol: client supports %v, server accepts %v", clientProtocols, serverProtocols)
```

- File Name : `k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go`
Method : `func (u responseUpgrader) UpgradeResponse(w http.ResponseWriter, req *http.Request, newStreamHandler httpstream.NewStreamHandler)
httpstream.Connection {`
Code Snippet
```
....
78. fmt.Fprintf(w, "unable to upgrade: missing upgrade headers in request: %#v", req.Header)
```

I would  like to know whether these vulnerabilities have been addressed in any subsequent release or whether you plan to fix them sometime in the near future?

**Comment by sftim** [comment]
Hi @SrishT 

You can look at https://github.com/kubernetes/kubernetes/ project (this repository holds the website)
The most recent release of v1.12.x seems to be [v1.12.10](https://github.com/kubernetes/kubernetes/releases/tag/v1.12.10)
