### ISSUE TITLE
Accessibility Updates - Alt Text for images

### ISSUE THREAD

**Issue by ChaitanyaKaranam** [kubernetes/website#16713]
**This is a Feature Request**

**What would you like to be added**
Change ``alt`` text tags for images under [/case-studies](https://kubernetes.io/case-studies/)

**Why is this needed**
All the images under the case-studies page have logo names as alternate text.
Ex: ``chinaunicom_featured_logo.png``
This has to be changed to a readable format. This change is required for better accessibility to [images](https://www.w3.org/WAI/tutorials/images/functional/)

**Comments**
We need to change alt text from logo names to link titles.
This is related to [Umbrella issue](https://github.com/kubernetes/website/issues/16675)

**Comment by sftim** [comment]
Valid issue indeed
/kind cleanup
/priority active

**Comment by PawanKolhe** [comment]
I would like to work on this.
