### ISSUE TITLE
Within Server-side apply, document map and list merging behaviors.

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#16725]
**This is a Feature Request**

**What would you like to be added**

Add this content to the page https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply

----

For Kubernetes version 1.16, CRDs support the following annotations:
 - `x-kubernetes-list-map-key`
 - `x-kubernetes-list-map-type`
These tags, and the type of a field in the CRD's validation section (`type: object` or `type: array`) affect how Server-Side Apply operates.

Maps and lists are merged differently.

* Type:  Map
  1. map key(s) used to consider one item at a time.
  1. applier-owned keys not mentioned in an apply operation are deleted 
  1. non-existing keys mentioned in apply operation are inserted
  1. existing not-owned-by-applier keys, not mentioned in the apply operation, are left along.
  1. keys mentioned and not-owned by applier with differing values will trigger conflict.
* Type:  lists with the `x-kubernetes-list-map-type`.  
  * Same as Map
  * `x-kubernetes-list-map-keys` determines the key or key-tuple.
  * otherwise, `name` used as key if it is a property
  * otherwise (what happens?)
* Normal List a.k.a Atomic List
  1.  whole list is owned by one owner.
  1.  if not-owned by applier, raise conflict
  1. if owned by applier, replaced with content in apply body.

**Why is this needed**
Server-Side apply does not explain list or map merging.

**Comments**

I suggest @apelisse or @jennybuckley as Eng reviewer for the website content resulting form this issue.

**Comment by sftim** [comment]
It's a valid improvement
/kind feature
/priority backlog

**Comment by erictune** [comment]
@apelisse @jennybuckley

**Comment by TBBle** [comment]
This does appear to be documented at https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy now.

**Comment by apelisse** [comment]
Correct, I think it's done now.

**Comment by apelisse** [comment]
> applier-owned keys not mentioned in an apply operation are deleted

I suspect this could be better documented.
