### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/conventions/

### ISSUE THREAD

**Issue by mkokabi** [kubernetes/website#16721]
**This is a typo Report**

**Problem:**
In this sentence:

> To check the final resource that was created, use the --dry-run flag, which provides the object to be submitted to the cluster.

The word 

> provides

 should be 

> prevents

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/conventions/

**Comment by savitharaghunathan** [comment]
IMO, I think the sentence needs to be rephrased.  --dry-run flag provides the detailed definition of the object that would be created when the command is run, but at the same time it does not create an actual object. 

/language en
/good-first-issue

**Comment by sshukun** [comment]
Hi, I want to work on this

**Comment by vishakhanihore** [comment]
Its good to be closed
