### ISSUE TITLE
Search box on docs should return results for selected version and language

### ISSUE THREAD

**Issue by abstrask** [kubernetes/website#16741]
When using the search box on the English documentation site for the current Kubernetes version (1.16), I get results for other languages and other versions of Kubernetes.

E.g. "ingress" yields results:
- In Indonesian
- In French
- for version 1.12 in Chinese

Would it be possible/sensible to restrict the search results to the currently selected language and Kubernetes version?

**Comment by sftim** [comment]
/kind feature
Good idea!

/priority important-longterm

**Comment by LiamDobbelaere** [comment]
I don't understand how this is not the default, it's annoying when the first result is some other language

**Comment by speedythesnailnpg** [comment]
> /kind feature Good idea!
> 
> /priority important-longterm

This should be reopened, whenever I search the docs I get back a lot of results in Chinese, I do not speak Chinese. The search results should definitely at the very least return only results in the expected language of the site.

Thanks!

**Comment by rich-day** [comment]
Looks like this is covered by https://github.com/kubernetes/website/issues/43817 now, for anyone looking here :)
