### ISSUE TITLE
Links on snapshot versions of /docs/home/ point to current version of docs

### ISSUE THREAD

**Issue by abstrask** [kubernetes/website#16740]
All links on the "Home" tab of archived versions of the documentation, point to the current documentation:

- https://v1-13.docs.kubernetes.io/docs/home/
- https://v1-14.docs.kubernetes.io/docs/home/
- https://v1-15.docs.kubernetes.io/docs/home/

Links on other tabs (e.g. "Setup", "Concepts" etc.) point to pages within the selected version of the docs, which is what I would expect browsing documentation for a specific Kubernetes version.

**Comment by aimeeu** [comment]
Thanks @abstrask for bringing this to our attention!

I also noticed that the "latest version" link in the "Kubernetes v1.13 documentation is no longer actively maintained. The version you are currently viewing is a static snapshot. For up-to-date documentation, see the latest version." message doesn't point to the latest version.

**Comment by zacharysarah** [comment]
To save time on discovery: the Home page behavior may be a function of how paths work in the [docsportal_home](https://github.com/kubernetes/website/blob/master/layouts/docs/docsportal_home.html#L22-L49) layout, which [`/content/en/docs/home/_index.md`](https://github.com/kubernetes/website/blob/master/content/en/docs/home/_index.md) applies.

**Comment by abstrask** [comment]
> I also noticed that the "latest version" link in the "Kubernetes v1.13 documentation is no longer actively maintained. The version you are currently viewing is a static snapshot. For up-to-date documentation, see the latest version." message doesn't point to the latest version.

Yes, and I think this is covered by #16066.

**Comment by sftim** [comment]
/priority important-longterm
(I think)
