### ISSUE TITLE
Pods metric setting not consistent in HPA walkthrough

### ISSUE THREAD

**Issue by HYChou0515** [kubernetes/website#16759]
**This is a Bug Report**
**Problem:**

In the [HPA walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/),

> ...
> For example, if you had your monitoring system collecting metrics about network traffic, you could update the definition above using kubectl edit to look like this:
> ```
> apiVersion: autoscaling/v2beta2
> ...
>   - type: Pods
>     pods:
>       metric:
>         name: packets-per-second
>       targetAverageValue: 1k
> ...
> ```
Following this would have an error
```
error: error validating "hpa.yaml": error validating data: [ValidationError(HorizontalPodAutoscaler.spec.metrics[0].pods): unknown field "targetAverageValue" in io.k8s.api.autoscaling.v2beta2.PodsMetricSource, ValidationError(HorizontalPodAutoscaler.spec.metrics[0].pods): missing required field "target" in io.k8s.api.autoscaling.v2beta2.PodsMetricSource]; if you choose to ignore these errors, turn validation off with --validate=false
```
I guess this `Pod` section probably follows from the older `autoscaling/v2beta1` as 
using this setting in `autoscaling/v2beta1` is fine.

**Proposed Solution:**

I think it could be consistent as what mentioned in the previous paragraph

> Pod metrics are specified using a metric block like this:
> ```
> type: Pods
> pods:
>   metric:
>     name: packets-per-second
>   target:
>     type: AverageValue
>     averageValue: 1k
> ```

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by sftim** [comment]
Looks like a useful and valid report.

/kind bug
/priority backlog
Thanks for reporting this @HYChou0515
