### ISSUE TITLE
Use tabs for “view your changes locally” in contributor guide

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16771]
**This is a Feature Request**

**What would you like to be added**
Rewrite https://kubernetes.io/docs/contribute/intermediate/#view-your-changes-locally to put the two options (Hugo in a container / Hugo locally) in [tabs](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs).

**Why is this needed**
Low-priority enhancement to make the documentation easier to read.

/kind feature

**Comment by philipliberato** [comment]
Hi, I would like to work on this issue.

**Comment by sftim** [comment]
> Hi, I would like to work on this issue.

@philipliberato sure, please feel free. Do you have any questions?

**Comment by r4zorgeek** [comment]
@sftim Hey I am new to open-source I would like to work on this issue.

**Comment by r4zorgeek** [comment]
@sftim I have added the features as requested and opened a pr request please review it.
