### ISSUE TITLE
Issue with k8s.io/es/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by lupa18** [kubernetes/website#16773]
conection 8080 refused

**Comment by raelga** [comment]
Hello @lupa18,

Thanks for your issue and welcome to kubernetes! 🎉 

Can you provide more information about the issue you are facing and how to reproduce it?

I just test the lab myself and didn't face had any error while completing the tutorial:

![Screen Shot 2019-10-10 at 08 34 18](https://user-images.githubusercontent.com/795289/66544562-c8bc7280-eb38-11e9-88cd-ead5382a4d30.png)

Don't hesitate to ping us at `#kubernetes-docs-es` slack channel!

**Comment by lupa18** [comment]
I repeated the procedure and now it works.
