### ISSUE TITLE
“Case studies” logos clash with page's gray background

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16772]
**This is a Bug Report**

**Problem:**
The logos on https://kubernetes.io/case-studies/ have gray backgrounds. Depending on your user agent and how it handles sRGB / color spaces, that might not be the same gray as the page background.

**Proposed Solution:**
~Recreate these logos using PNG format and a transparency (alpha) channel.~
One of:
- Use an image for the page background, so that the images don't match
- Migrate to use SVG logos

**Page to Update:**
https://kubernetes.io/case-studies/

**Additional Information:**
Also potentially relevant: https://css-tricks.com/color-rendering-difference-firefox-vs-safari/

/kind cleanup

**Comment by sftim** [comment]
(we should also check if that different gray is deliberate)

**Comment by sftim** [comment]
It's also OK to use SVG logos with a transparent background, if that is feasible.

**Comment by sftim** [comment]
I noticed that there are actually SVG logo images available, so we could / should convert the site to use these.

**Comment by shuuji3** [comment]
I found how to make the background transparent so I can replace current gray-background images with ones with transparent backgrounds.

How can we check if the gray background is deliberate or not? 🤔

**Comment by sftim** [comment]
> I'm not sure how to check if the gray background is deliberate.

I'm pretty sure that some browers (Safari) render the page with a uniform gray - or did when I last checked.. https://css-tricks.com/color-rendering-difference-firefox-vs-safari/ explains a bit about why Firefox doesn't do that.
Switching to transparent sounds good to me!
