### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/reconfigure-kubelet/

### ISSUE THREAD

**Issue by ivalexm** [kubernetes/website#16799]
**This is a Bug Report**
Article suggests running `bash kubectl proxy --port=8001 &`
**Problem:**
However, kubectl is a binary.
**Proposed Solution:**
Either you run `bash -c "kubectl proxy --port=8001" &` or simply
`kubectl proxy --port=8001 &`
**Page to Update:**
https://k8s.io/docs/tasks/administer-cluster/reconfigure-kubelet/

**Comment by savitharaghunathan** [comment]
@ivalexm , Thank you for reporting this issue.

/language en
/kind bug
/good-first-issue
/priority backlog
