### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by bhaskarrao1** [kubernetes/website#16800]
root@k8s-master:~# kubeadm init --ignore-preflight-errors=cpu --apiserver-advertise-address 10.128.0.2 --pod-network-cidr=10.128.1.1/24
[init] Using Kubernetes version: v1.16.1
[preflight] Running pre-flight checks
[preflight] WARNING: Couldn't create the interface used for talking to the container runtime: docker is required for container runtime: exec: "docker": executable file not found in $PATH
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by neolit123** [comment]
please see the installing kubeadm doc:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin

kubeadm requires 2 CPU cores at the minimum.

/close
