### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by ericramos1980** [kubernetes/website#16811]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by rajeshdeshpande02** [comment]
@ericramos1980 Can you please provide descriptions about this issue

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
