### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by slashmo** [kubernetes/website#16810]
Step 5 of the *Create a Service* section tells me to visit port `30369` but for me the LoadBalancer was exposed at port `30764`. If that's generally the case the documentation should be updated accordingly.

**Comment by rajeshdeshpande02** [comment]
@slashmo Thanks for raising this.
This 5 digit port generated randomly and it is different for everyone.  Instruction is given for this in a bracket in the same step number 5, but I think this is not sufficient for first-time readers so I will improve it and make it more clear.
