### ISSUE TITLE
Fix form allignment in mobile view.

### ISSUE THREAD

**Issue by plxity** [kubernetes/website#16817]
**This is a Bug Report**

**Problem:**
The alignment of the form is not proper.
![Screenshot from 2019-10-11 09-00-42](https://user-images.githubusercontent.com/28510494/66622789-b0b32480-ec06-11e9-9bdb-3576742af52c.png)

**Proposed Solution:**
The alignment of the form should be proper.
**Page to Update:**
https://kubernetes.io/...

**Comment by shrey-sachdeva2000** [comment]
Fixed the issue.
