### ISSUE TITLE
Deprecated default solution in tutorial

### ISSUE THREAD

**Issue by tomfrenken** [kubernetes/website#16829]
**This is a Bug Report**

**Problem:** 
When using 
```
kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080
```
I get the following warning: 
```
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
```

**Proposed Solution:**
Update the deprecated default solution.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by BenHall** [comment]
Thanks. A new version will be live shortly with updated commands and flow to reflect the current practices.

**Comment by sftim** [comment]
#15512 is tracking this

**Comment by BenHall** [comment]
Sorry for the delay on this. We thought it had a larger impact than it did.

The fix was applied in https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/839fc4c2160f821194418d16bf14c1cde9512cb5

**Comment by tomfrenken** [comment]
Neat
