### ISSUE TITLE
Blog typo: “San Deigo” (in “Contributor Summit San Diego Schedule Announced!”)

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16828]
**This is a Bug Report**

**Problem:** In _Contributor Summit San Diego Schedule Announced!_ there is a typo: “San Deigo”.

**Proposed Solution:**
Correct the typo

**Page to Update:**
https://kubernetes.io/blog/2019/10/10/contributor-summit-san-diego-schedule/

**Additional Information:**
/area blog
/help
/kind cleanup
/priority important-soon
(I set that priority because KubeCon is imminent, feel free to lower priority)

**Comment by raelga** [comment]
Hello @sftim, I opened a PR this morning to fix the issue:
 https://github.com/kubernetes/website/pull/16822

**Comment by sftim** [comment]
Thanks @raelga 
/close
