### ISSUE TITLE
Explain how to upgrade minikube

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16866]
**This is a Feature Request**

**What would you like to be added**
Add a page that either:
- tells the reader how to upgrade an existing minikube deployment to be at the latest supported minikube release
- signposts the reader to external documentation on how to achieve the same thing

**Why is this needed**
If use the build-in docs search for “upgrade minikube”, I don't find anything. I think I should find _something_.

**Comments**
Noted after reading #15950

**Comment by aimeeu** [comment]
@sftim - minikube has its own external [docs](https://minikube.sigs.k8s.io/docs/); the minikube folks were cleaning up dual-source content (https://github.com/kubernetes/website/issues/15969) until it was put on hold because of the KEP.  So rather than adding a page, how about just pointing to the minikube docs?

**Comment by sftim** [comment]
> how about just pointing to the minikube docs?

Yep, that fits what I had in mind for “signposts the reader to external documentation on how to achieve the same thing”

**Comment by prasadkatti** [comment]
FWIW, you can upgrade minikube clusters by providing kubernetes version to the start command, like so -
`minikube start --kubernetes-version=latest`

https://minikube.sigs.k8s.io/docs/handbook/controls/
Link to minikube issue - [Document upgrading a cluster](https://github.com/kubernetes/minikube/issues/6122)

**Comment by Surya2709** [comment]
Make sure that you have brew updated:

    brew update

    Make sure that you already have cask installed:

    brew cask install minikube --verbose

Finally, execute the following command in the same directory you've installed minikube previously (usually /usr/local/bin/):

brew cask reinstall minikube

If you see an output similar to this:

Error: It seems there is already a Binary at '/usr/local/bin/minikube'; not linking.

    Remove the existing binary:

    rm /usr/local/bin/minikube

Now, you should able to reinstall (upgrade) minikube. :)

**Comment by life5ign** [comment]
Where is this in the docs? I can't find it.
