### ISSUE TITLE
Issue with docs/concepts/architecture/controller.md URL links are mixed in the document.

### ISSUE THREAD

**Issue by ysyukr** [kubernetes/website#16877]
**This is a Bug Report**

**Problem:**
Unlike other documents, links in the document are listed as full URLs.
ex)
Cluster autoscaling - https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/#cluster-autoscaling
Kubernetes control plane - https://kubernetes.io/docs/concepts/#kubernetes-control-plane
Kubernetes objects - https://kubernetes.io/docs/concepts/#kubernetes-objects

**Proposed Solution:**
Change the link above to the following:
Cluster autoscaling - /docs/tasks/administer-cluster/cluster-management/#cluster-autoscaling
Kubernetes control plane - /docs/concepts/#kubernetes-control-plane
Kubernetes objects - /docs/concepts/#kubernetes-objects

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/controller/

/language en

**Comment by sftim** [comment]
Good spot
/kind cleanup
/priority backlog
