### ISSUE TITLE
Access Clusters Using the Kubernetes API has outdate list of official client libraries

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#16906]
**This is a Bug Report**

**Problem:** [Access Clusters Using the Kubernetes API](https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/) lists 2 official client libraries: Python and Go[lang]. The trouble is, there are actually [6](https://kubernetes.io/docs/reference/using-api/client-libraries/#officially-supported-kubernetes-client-libraries) (at the time of writing).

**Proposed Solution:**
Revise the page. Either of:
- list all 6 client libraries in that page
- summarise the 6 client libraries and signpost readers to find more about the official client library that they prefer

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

**Additional Information:**
Some people might favor documenting Go and giving that client library special treatment, because lots of Kubernetes clients are written in Go. I recommend not giving Go special treatment, precisely _because_ the ecosystem is currently so skewed towards one language. It's useful to facilitate diversity of client code.

**Comment by shub-asa1** [comment]
@sftim It will be good if this page have examples of all six libraries with basic explanation.
I would like to add more details . Pls assign me this issue.

**Comment by sftim** [comment]
@shub-asa1 it's great to hear that you'd like to sort this out.

If you propose a pull request, and you've [signed the CLA](https://kubernetes.io/docs/contribute/start/#sign-the-cla), that's all that's needed for a review and, I hope, a fix.
