### ISSUE TITLE
Wanted Doc: Task: Backup and Restore my PVC

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#1691]
For all users of PVCs, they would like to know how to backup the data in their PVC.
StatefulSets users in particular will be interested in this.

I envision that the StatefulSet documentation will include advice on how to "pause" your database, and then point to generic PVC documentation which describes how to backup or restore.

This issue is a request for the latter: generic PVC-related documentation.

I imagine that the steps are something like this for backup:

1. Prereq: you know the name of the PVC that you want to backup.
1. Prereq: your application is "paused" and not mutating the storage
   1. for RWO, need to actually terminate the app pods.  No need to document how to do that here.  It is a prereq.
   1. For RWX, can just ensure app is paused as a pre-req.
1. Find the PV that backs this PVC. 
1. For GCE PDs
   1. find the GCE PD name that backs this PV
   1. gcloud command to snapshot that GCE PD
1. For AWS EBS
   1. same deal

Restore would be:

1. Prereq: you know the name of the PVC that you want to backup.
1. Prereq: you know the name of the snapshot you want to restore to.
1. Prereq: your application is stopped and ready for the storage to change under it.  
1. Verifying Prereqs: how to check that no pod is attached to the PVC currently
1. Find the PV that backs this PVC. 
1. For GCE PDs
   1. find the GCE PD name that backs this PV
   1. gcloud command to snapshot that GCE PD
1. For other clouds... etc.

For all steps, give example kubectl command, preferably with machine readable output (via grep, -o jsonpath, or whatever).

**Comment by erictune** [comment]
I'd like to be able to refer to these in the StatefulSet docs that come out in 1.5.

**Comment by erictune** [comment]
This can use the Task template: https://github.com/kubernetes/kubernetes.github.io/blob/master/_includes/templates/task.md

**Comment by erictune** [comment]
@matchstick Do you if there is someone in storage area who could write this doc for 1.5?  I'd like to reference it from StatefulSet docs.

**Comment by ekozan** [comment]
any new about this one ?

**Comment by matchstick** [comment]
I am not sure of the priority of this but @jingxu97 would be a good candidate to write this up as she has been looking into both AWS and snapshots.

matchstick

**Comment by jingxu97** [comment]
The snapshot proposal is https://github.com/kubernetes-incubator/external-storage/pull/197
In the proposal we add new API objects VolumeSnapshot to create snapshots and restore/recreate volumes from snapshot. Please let me know if you have any comments or questions. Thanks!

**Comment by erictune** [comment]
Searching on kubernetes.io for the term [snapshot], I don't find anything that tells me that there is even a possibility to snapshot a volume.  Seems like the concept could be mentioned on https://kubernetes.io/docs/concepts/storage/persistent-volumes/

I don't know if you want to provide the manual snapshotting steps, as listed above, or link to out to kubernetes-incubator/external-storage with a caveat that it is incubating.  But suggest at least giving people pointers to what is possible.

There is this: https://blog.jetstack.io/blog/volume-snapshotting/

**Comment by jingxu97** [comment]
@erictune Thank you for your comments. We are working on this feature now. As you suggested, we should also update the doc to mention how it could be done for now.

**Comment by vistalba** [comment]
Is there a solution for now? Any docs?

**Comment by farcaller** [comment]
[Stash](https://appscode.com/products/stash/) is one option now, external from k8s.

**Comment by farcaller** [comment]
Now that it's closed and there are people still interested in the subject; could it be re-opened and actually fixed?
