### ISSUE TITLE
Broken link in content/en/docs/reference/access-authn-authz/authentication.md 

### ISSUE THREAD

**Issue by rarean** [kubernetes/website#16916]
**This is a Bug Report**

**Problem:**
Broken link to UAA setup instructions http://apigee.com/about/blog/engineering/kubernetes-authentication-enterprise 
according to wayback machine this was removed circa 2017

**Proposed Solution:**
remove link or change link to UAA github site https://github.com/cloudfoundry/uaa
Also propose updating Dex setup instructions to 2018 New Stack article by Joel Speed https://thenewstack.io/single-sign-kubernetes-command-line-experience/

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/authentication

**Comment by aimeeu** [comment]
Thanks @rarean for reporting this issue!

/priority important-soon

/assign
