### ISSUE TITLE
Issue with /docs/getting-started-guides/aws/

### ISSUE THREAD

**Issue by JensRantil** [kubernetes/website#1696]
http://kubernetes.io/docs/getting-started-guides/aws/#kube-up-bash-script states

> kube-up.sh is a legacy tool that is an easy way to spin up a cluster. This tool is being deprecated, and does not create a production ready environment.

I propose adding a link to what to use instead (`kubeadm`?).

**Comment by chenopis** [comment]
Good suggestion

**Comment by tengqm** [comment]
@chenopis I assume this suggestion is still as good as it was?
