### ISSUE TITLE
Start contributing page: Add section on how to create a good commit message and PR description

### ISSUE THREAD

**Issue by aimeeu** [kubernetes/website#16977]
**This is a Feature Request**

**What would you like to be added**
Add section to Contributing docs on how to create a good commit message and PR description

**Why is this needed**
Good commit messages and PR descriptions are essential for 1) reviewers and approvers to understand the PR; 2) historical discovery when something goes wrong; and 3) when someone wants to see the history of a file. I see a lot of PR descriptions that are blank or just say "Fixes <issue-number>" instead of specifying actual changes to content or source code.

**Comments**
I wrote  [how to create a good commit message](https://wiki.acumos.org/display/AC/Your+First+Patch#YourFirstPatch-WritingYourCommitMessage) for another project. Adapt for K8s docs.

**Comment by SupriyaSirbi** [comment]
Hello @aimeeu I am interested in working on this issue. I shall submit a PR for the same. Thanks

**Comment by vishakhanihore** [comment]
PR will be ready in a day. @aimeeu
