### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by ravening** [kubernetes/website#17003]
**This is a Bug Report**

**Unable to access the frontend service from master node using curl**

**After deploying the frontend service using the type load balancer, I got the public IP from my cloud provider but I am unable to access the port using the external IP from the master node. However, I can only fetch the data from worker nodes

From master node

$ curl http://{EXTERNAL-IP}
curl: (52) Empty reply from server

If I do a curl from worker node, I do get the response

$ curl http://{<EXTERNAL-IP}
{"message":"Hello"}
**

```
$ kubectl get all
NAME                            READY   STATUS    RESTARTS   AGE
pod/frontend-57f986c949-qgjlz   1/1     Running   0          31m
pod/greetings                   1/1     Running   0          158m
pod/hello-5b8b87fb88-5h9vz      1/1     Running   0          39m
pod/hello-5b8b87fb88-6c6hf      1/1     Running   0          39m
pod/hello-5b8b87fb88-lz8jv      1/1     Running   0          39m
pod/hello-5b8b87fb88-rjk9p      1/1     Running   0          39m
pod/hello-5b8b87fb88-wl66s      1/1     Running   0          39m
pod/my-nginx                    1/1     Running   0          3h

NAME                         TYPE                 CLUSTER-IP      EXTERNAL-IP      PORT(S)                  AGE
service/frontend             LoadBalancer         10.0.132.74     {EXTERNAL-IP}    80:30259/TCP   31m
service/hello                ClusterIP            10.0.60.136      <none>          80/TCP               34m
service/kubernetes           ClusterIP            10.0.0.1         <none>          443/TCP            4h17m

NAME                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/frontend   1         1         1            1           31m
deployment.apps/hello      5         5         5            5           39m

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/frontend-57f986c949   1         1         1       31m
replicaset.apps/hello-5b8b87fb88      5         5         5       39m
```

I have enabled all the firewalls to access the master node from the outside world as well the load balancer is applied to all worked nodes and the master node.

So I don't suspect any issue with the firewall as I can ping the master node from the outside world.

**Page to Update:**
https://kubernetes.io/...

Kubectl version

```
{
  "clientVersion": {
    "major": "1",
    "minor": "12",
    "gitVersion": "v1.12.3",
    "gitCommit": "435f92c719f279a3a67808c80521ea17d5715c66",
    "gitTreeState": "clean",
    "buildDate": "2018-11-26T12:57:14Z",
    "goVersion": "go1.10.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "12",
    "gitVersion": "v1.12.3",
    "gitCommit": "435f92c719f279a3a67808c80521ea17d5715c66",
    "gitTreeState": "clean",
    "buildDate": "2018-11-26T12:46:57Z",
    "goVersion": "go1.10.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

Running the kubernetes cluster on CoreOS
```
$ uname -a
Linux master-1 4.19.68-coreos #1 SMP Wed Sep 4 02:59:18 -00 2019 x86_64 Intel Xeon E312xx (Sandy Bridge) GenuineIntel GNU/Linux
```

**Comment by sftim** [comment]
@rakgenius I'd assume that `curl http://{<EXTERNAL-IP}` works from your PC as well? If the service is accessible on the internet but not on the control plane host (aka master), that might be a special situation that's more nuanced than the documentation can reasonably cover.

**Comment by rakgenius** [comment]
No.. It's not reachable from my PC as well

**Comment by sftim** [comment]
This sounds like an issue that will be specific to the cloud provider that you're using.
For that reason @rakgenius I'm going to characterize this as a request for support, rather than a report of a shortcoming in the documentation.

However, if you can identify what's not right about that page, and especially if it's a shortcoming that's generic across different utility computing vendors, then please do add that detail here.

/triage support

**Comment by rakgenius** [comment]
Thanks for the help
