### ISSUE TITLE
Review “Resource metrics” pipeline

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#17015]
**Page to review**
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/ mentions Kubernetes v1.8
Review this page, removing references to Kubernetes versions that are earlier than what's [supported](https://kubernetes.io/docs/setup/release/version-skew-policy/#supported-versions), and revising wording to suit.

**Why is this needed**
The documentation usually can and should assume that the reader is running a version of Kubernetes that is at least as new as the oldest version still supported.

**Comments**
/kind cleanup

**Comment by miteshskj** [comment]
@sftim - Is the intent to remove all references to versions (eg: feature foo was introduced in 1.x) or just where it's a requirement (eg: feature foo works with 1.+ or minimum version required is 1.x)? where 1.x is an unsupported version.

**Comment by sftim** [comment]
@miteshskj All references to unsupported versions. Anyone interested in history would, I think, be more likely to look at release notes or Git commit logs anyway.

Imagine that all pages start with “_The following text assumes your cluster is running Kubernetes v1.12 or newer_” (v1.12 because right now v1.12 is the oldest supported version), and that's why you can omit information about older versions.

_However_ one possible exception, feature state. Ingress is in beta and has been since **v1.1**
The feature-state shortcode for Ingress correctly lists v1.1 as the version it went beta in. That'll be true forever, no matter how many later releases come out.
If / when Ingress goes GA then the feature-state on that page will update, of course.
