### ISSUE TITLE
Unable to marshal archetypes/default.md into YAML

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/website#17029]
Getting an error in Prow when trying to marshal YAML:

jsonPayload: {
  base: "master"   
  client: "repoowners"   
  component: "hook"   
  error: "error converting YAML to JSON: yaml: line 1: did not find expected key"   
  file: "prow/repoowners/repoowners.go:415"   
  func: "k8s.io/test-infra/prow/repoowners.(*RepoOwners).walkFunc"   
  level: "error"   
  msg: "Error decoding OWNERS config from '*.md' file."   
  org: "kubernetes"   
  path: "/tmp/git180514263/archetypes/default.md"   
  repo: "website"   
 }

Seems like YAML marshalling doesn't like https://github.com/kubernetes/website/blob/master/archetypes/default.md; it doesn't appear to be valid (probably because of the '{{' and '}}' brackets?). Renaming the file extension from '.md' to something else, if possible, should solve this.

**Comment by kbhawkey** [comment]
hello @michelle192837 . Can you provide more details about the problem? The file, `default.md` is an archetype file:
https://gohugo.io/content-management/archetypes/#what-are-archetypes

**Comment by michelle192837** [comment]
Ah, suspected that. :( So the issue appears to be that Prow parses '.md' files with YAML headers to see if there are per-file OWNERS specified, but it can't parse the YAML header here because it's invalid YAML, and marshalling it just errors. But yeah, this does look like a valid file for your use case.

I'm not 100% sure what the YAML marshalling error is, aside from the error above? Sounds like quoting may help valid parsing.

**Comment by kbhawkey** [comment]
@michelle192837 , The file is using templating. Can you skip this file?

**Comment by michelle192837** [comment]
Not really, but I think for this kind of case we can downgrade the severity. I'll fix it on our side, thanks for the clarifications!
