### ISSUE TITLE
Document TLS bootstrapping authorization requirements

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/website#1703]
Per comment in https://github.com/kubernetes/kubernetes.github.io/pull/1684#issuecomment-260532484 we currently recommend users give the TLS bootstrapping token the following user info:

```
02b50b05283e98dd0fd71db496ef01e8,kubelet-bootstrap,10001,"system:kubelet-bootstrap"
```

We need to document the authorization rule to associate with that group.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/40034 added a `system:node-bootstrapper` role

**Comment by liggitt** [comment]
also, `"system:kubelet-bootstrap"` is an example, not a specific group name recommendation

**Comment by ericchiang** [comment]
Awesome. Do we sync those default roles to kubernetes.io yet?

**Comment by liggitt** [comment]
we're trying (c.f. https://github.com/kubernetes/kubernetes.github.io/pull/2169), but there's apparently not a good way to merge pulls for work in master that hasn't hit a release yet (e.g. a release-1.6 doc branch)

**Comment by ericchiang** [comment]
We don't have a 1.6 branch? :(

Okay I'll keep my eye on that PR. Thanks.
