### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/ip-masq-agent/

### ISSUE THREAD

**Issue by aido123** [kubernetes/website#17044]
**This is a Bug Report**

In the diagram, bridge cbr0 and pod1 will NOT have the same ip address right?

**Proposed Solution:**
Change to another address in the block, i.e. 10.1.1.5

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/

na

na

**Comment by aimeeu** [comment]
Thanks @aido123 for your feedback!
@rramkumar1 or @jingax10 - can you answer the question? and do we need to update the diagram?

/sig network
