### ISSUE TITLE
Remove insensitive wordings from the docs like just - easy or - simple

### ISSUE THREAD

**Issue by fokusferit** [kubernetes/website#17070]
**This is a Feature Request**

My feature request is about leveling up the documentation text and wording to be less insensitive and inconsiderate language.

There are great tools out there these days, like [alexjs](https://alexjs.com/) which makes it possible to catch phrases like "Just", "easy" or "simple".

Using alexjs also shows certain words which are common to kubernetes domain, e.g. `host`.

It allows us to challenge certain narratives which are used to be normal, also accepted terminology but should be challenged in order to increase inclusivity. When I started learning kubernetes (or any other technology) often reading "just simple do X" when I didn't know what that simple task means, created a barrier in my mind that I don't understand the topic.

An example is the `contribute/start.md" page, where alexjs returns this:

``` 
start.md
      42:28-42:35  warning  `Special` may be insensitive, use `Has a disability`, `Person with a disability`, `People with disabilities` instead  special       retext-equality
     126:3-126:10  warning  `Clearly` may be insensitive, try not to use it                                                                       clearly       retext-equality
    135:68-135:72  warning  Reconsider using `suck`, it may be profane                                                                            suck          retext-profanities
    180:50-180:54  warning  `just` may be insensitive, try not to use it                                                                          just          retext-equality
    298:47-298:53  warning  `fellow` may be insensitive, use `person`, `friend`, `pal`, `folk`, `individual` instead                              gal-guy       retext-equality
    301:14-301:20  warning  `simple` may be insensitive, try not to use it                                                                        simple 
```

**What would you like to be added**

I would like to improve all these wordings, step by step, starting with english and contribute folder or the concepts folder first.

Removing in particular words like:

- "Just"
- "Easy / Easily / Simple" 
- "Obviously / Clearly / Clear " 
... 

I'm aware that alexjs (or retext-js) warns about more words, yet changing "deep-dive" or "host" isn't possible without reducing clearness. 

**Why is this needed**

Some blogs to make a point:

- https://css-tricks.com/words-avoid-educational-writing/
- https://spin.atomicobject.com/2014/09/09/never-use-the-word-obviously/

**Comments**

**Comment by aimeeu** [comment]
@fokusferit  - thanks for your excellent feedback! I have to find out if SIG Docs can add a tool like this. In the meantime, would you like to open a PR to update the start.md page?

/sig docs
/kind feature
/priority backlog

**Comment by christophercarney** [comment]
I'm seeing a lot of these words like "basically", "obviously", "simply", etc. in mainly two places: blog posts and case studies. 

I'm mostly sure editing these words out of blog posts makes sense and actually generally increases readability. I'm under the general impression that adverbs usually serve no purpose but to fill space anyways.

Case studies, on the other hand, are a bit more nuanced because many of these words come in the form of direct quotes. In these cases I believe editing these words out would be inappropriate. Thoughts?

**Comment by fokusferit** [comment]
As I didn't had time to really start working on this, the best way is like how we do it in software development:

- Incrementally. Starting with one subfolder of the docs, fixing step-by-step.

Also updating existing Guidelines for new Documentation.

**Comment by zacharysarah** [comment]
This issue has renewed importance with https://github.com/kubernetes/community/pull/4884. 

/remove-lifecycle rotten 
/assign @celestehorgan

**Comment by zacharysarah** [comment]
After review from WG Naming, this issue is actionable and ready for contributor help.

From a SIG Docs standpoint, this would also make a good first issue (albeit a large one). 

/triage important-long-term
/good-first-issue
/help-wanted

**Comment by geoffcline** [comment]
I'm working on a draft addition to the kubernetes style guide that encourages reviewing drafts for inclusive language before submitting a PR, and includes instructions on running alexjs.

**Comment by celestehorgan** [comment]
@kbhawkey – are you intending to do any more work on this, or can we close the issue?

**Comment by kbhawkey** [comment]
Hi @celestehorgan .
No, I think I covered most of the cases mentioned in this issue.
Thanks!

**Comment by kbhawkey** [comment]
I plan to close this issue.
If there is more work to do, you can reopen.
Thanks!
/close
