### ISSUE TITLE
unclear wording about kubectl cluster-info k8s.io/docs/tasks/access-application-cluster/access-cluster/

### ISSUE THREAD

**Issue by dsbos** [kubernetes/website#17086]
**This is a Bug Report**

**Problem:**
The text says:

"As mentioned above, you use the `kubectl cluster-info` command to retrieve the service’s proxy URL."

That wording sounds like you can use the `kubectl cluster-info` command to get the proxy URL for a given (specified) service.

However, `kubectl cluster-info` (seemingly) doesn't take any parameter to specify a service, and (seemingly) retrieves proxy URLs _only_ for built-in services.

Was that text meant to say something about using the `kubectl cluster-info` command to see the _form_ of proxy URLs (in order to know how to construct a proxy URL (manually) for your own service)?

**Proposed Solution:**

Probably adjust wording to no longer imply that `kubectl cluster-info` gets the proxy URL for an arbitrary given service, maybe re-working to mention seeing _form_ of proxy URLs in `kubectl cluster-info`'s output.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/

**Comment by aimeeu** [comment]
@dsbos thank you for your feedback!

The [kubctl Cheat Sheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-nodes-and-cluster) states that `kubectl cluster-info` displays addresses of the master and services. The SIG CLI is responsible for kubectl, so I've assigned this issue to them.

/sig cli
