### ISSUE TITLE
Issue with /docs/admin/federation/

### ISSUE THREAD

**Issue by nalink** [kubernetes/website#1711]
Can you please provide complete setup details on brining Federated cluster on AWS EC2?
./deploy.sh does *not* accept AWS as a valid provider.
./federation-up.sh has issues while bringing cluster on AWS.

**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
There is clearly a new tool kubefed for this job now.
