### ISSUE TITLE
Improvement for k8s.io/docs/concepts/cluster-administration/addons/

### ISSUE THREAD

**Issue by delormej** [kubernetes/website#17114]
As this is a page in the "concepts" section, it would be helpful to understand the concept of an addon, rather than just listing a bunch of addons.  I came to the page hoping to understand exactly where addons fit, and why use an addon vs. just deploying a daemonset or an operator with CRDs and custom controllers.  What is the scope of an addon, what can it do? How exactly do you build an addon, etc... At the conceptual level, I'm not certain I understand Addons from this page.  Thank you.

**Comment by SupriyaSirbi** [comment]
Thanks for the issue. I shall submit the PR for the same.
