### ISSUE TITLE
Issue with k8s.io/zh/docs/

### ISSUE THREAD

**Issue by GYCocoa** [kubernetes/website#17112]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by aimeeu** [comment]
@GYCocoa Would you please add more information to this bug report?

/triage needs-information
/language zh

**Comment by tengqm** [comment]
pls feel free to open with actionable issue details or file a new one.
