### ISSUE TITLE
Document global options in kubectl reference documentation

### ISSUE THREAD

**Issue by jruales** [kubernetes/website#17178]
**This is a Bug Report**

**Problem:**
Global kubectl command-line options (such as --namespace) aren't included in the kubectl command reference

**Proposed Solution:**
Would it be possible to include global command-line options in the kubectl command reference?

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

N/A

**Comment by christophercarney** [comment]
All the global command line options are presented in `kubectl options` on the CLI and are documented in `kubectl help` pretty clearly. The documentation mentions this https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#options as well, so not sure this requires additional documentation. Since this list of commands is probably more likely to grow/change than the others, I'd imagine they were more hesitant about adding all of the global CLI options.

**Comment by jruales** [comment]
Yep, the options are available in `kubectl options` and I agree that they're great when using the commandline interface. But wouldn't following this line of reasoning lead you to conclude that the web-based kubectl command reference is completely unnecessary? I personally like having the online command reference. I think it has its own purpose outside of the CLI help/option pages, which is to be a user-friendly, searchable resource that anyone can browse or reference without needing to use the terminal.

Given this, I think it makes sense to include the global options in the online documentation to match the documentation already available for the options of the current commands.

You've mentioned that the documentation already mentions about the "kubectl options" command. That's true, but it misses the usecase that I'm trying to solve. I was just starting to learn Kubernetes and I saw a command being used. I wanted to disect this command to understand what it was doing so I went to the documentation. I looked at the relevant command, but the option wasn't there. I did a Ctrl+F to try to find documentation for the option somewhere else in the page, but it wasn't there. Basically, the problem is one of discoverability. How does a beginner know that there are global options if they are not mentioned anywere in the docs (especially when one assumes that the documentation is complete?).

**Comment by jruales** [comment]
I agree that maybe the creators of the documentation excluded this information on purpose for a good reason, and if so that's fine. But in case it wasn't a premeditated choice, the purpose of this Issue is simply to make the case for including it.

**Comment by sftim** [comment]
/retitle Document global options in kubectl reference documentation
