### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-scheduler/

### ISSUE THREAD

**Issue by b-shchuko** [kubernetes/website#17170]
The doc doesn't state what the scheduler is for.

**Comment by sftim** [comment]
Ideally, that reference page would link to https://kubernetes.io/docs/concepts/scheduling/

**Comment by sftim** [comment]
Seems like a valid improvement
/priority backlog

**Comment by hase1128** [comment]
@sftim 
How about adding the following sentence to the end of synopsis(https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/#synopsis)?

```
Refer to the following link for detail information about kube-scheduler(https://kubernetes.io/docs/concepts/scheduling/).
```

if this change is acceptable for you, I will issue PR.

**Comment by sftim** [comment]
The trouble here is that https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/#synopsis is [_generated_](https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/) documentation, so that update either needs to go upstream or somehow get merged in during the automated step that generates it.

Also, one hint about the wording.
> Refer to the following link for detail information about kube-scheduler(https://kubernetes.io/docs/concepts/scheduling/).

Could that be worded:
```markdown
See [scheduling](https://kubernetes.io/docs/concepts/scheduling/) for more information about scheduling and the kube-scheduler component.
```
?

**Comment by hase1128** [comment]
@sftim 
I think the original document is here and we should modify this. Is that right?
https://github.com/kubernetes/website/blob/master/content/en/docs/reference/command-line-tools-reference/kube-scheduler.md

Your suggestion word is better for me.

**Comment by sftim** [comment]
https://github.com/kubernetes/kubernetes/tree/master/cmd/kube-scheduler is where the code for kube-scheduler lives, and that's where the references docs (for this tool) originate.

**Comment by sftim** [comment]
(I think there's a lot of work involved in addressing this issue - it's not as easy as making one Markdown change)

**Comment by hase1128** [comment]
Hmm, I consider whether I can handle this issue quickly.

**Comment by tengqm** [comment]
@hase1128 If you feel compelling to add this. The upstream code is here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/server.go#L78

**Comment by hase1128** [comment]
@tengqm 
thank you. I think it is better to add a simple reference link.
this adding make the document into more polite.

however, I don't understand the flow of modification yet...
this modification task is only adding additional description into "https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/server.go#L78"?

I think there seems to be a task about generating document from the above source code...

**Comment by hase1128** [comment]
I will fix the upstream code and issue PR.
I will address generating document if generation process is requested to me.

**Comment by tengqm** [comment]
@hase1128 To get it "fixed", you will need to:

- propose change to upstream code, by following this: https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/
- regenerate the reference doc, by following this: https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/
- propose the regenerated doc to kubernetes/website with pointer where the upstream change is merged

**Comment by hase1128** [comment]
@tengqm 
Understood, thank you for the information.
I will try.

**Comment by hase1128** [comment]
@tengqm 

I try to do the following procedure.

https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/#generating-the-openapi-spec-and-related-files

```
hack/update-generated-swagger-docs.sh
hack/update-openapi-spec.sh
hack/update-generated-protobuf.sh
hack/update-api-reference-docs.sh
```

however, I couldn't find update-api-reference-dock.sh.
do you know where is the file?

**Comment by tengqm** [comment]
Looks like the script was removed: https://github.com/kubernetes/kubernetes/pull/72924

**Comment by hase1128** [comment]
@tengqm 
My understanding is here. Is this right?
1. I modify upstream source code.
2. I Issue PR to kubernetes/kubernetes without gererating OpenAPI spec and related which described in https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/
3. After the above PR is merged, I generate reference pages(https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/)
4. I issue PR to kubernetes/website

**Comment by tengqm** [comment]
@hase1128 Sounds right, but for step 2 it is up to the upstream reviewers to decide how your PRs should be organized there. The old convention I know of is that you will submit one PR with at least two separate commits: one for the changes you want to make; the other is about the changes that will happen to the generated files.

**Comment by hase1128** [comment]
@tengqm 
OK, I issue PR to upstream at first, and after that I will follow the instructions of reviewer.
