### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dns-pod-service/

### ISSUE THREAD

**Issue by armanzor** [kubernetes/website#17173]
**This is a Bug Report**

On subject page in section Pod’s DNS Policy there's note:

> Note: “Default” is not the default DNS policy. If dnsPolicy is not explicitly specified, then “ClusterFirst” is used.

Looks like it isn't truth. I created deployment without dnsPolicy in pod's template and couldn't get access to URL outside the cluster with error in name resolution. But when I created deployment with 
`dnsPolicy: ClusterFirst` explicitly in pod's template, new pod gave access to outside URL

**Proposed Solution:**
Just remove this note from the page, because "Default" dnsPolicy is really default

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

Kubernetes Version: 1.15.3

**Comment by sftim** [comment]
Is that also true in the current Kubernetes release (v1.16.3)?

@armanzor if you're not sure, it's OK to say so.
