### ISSUE TITLE
Issue with https://kubernetes.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by dsbos** [kubernetes/website#17174]
**This is a Bug Report**

**Problem:**

The page at 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/ currently starts off saying:

  Managing storage is a distinct problem from managing compute.

("Compute" is a verb, and is not really a noun, so that introductory sentence is a bit jarring.)

**Proposed Solution:**

It should say something like:

  Managing storage is a distinct problem from managing computation.

or:

  Managing storage is a distinct problem from managing computing resources.

 **Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by christophercarney** [comment]
I believe this is just a typo from "computers" but you're right.
