### ISSUE TITLE
No Recommendation Around Command Example in Doc Which Requires Root Privilege

### ISSUE THREAD

**Issue by vanou** [kubernetes/website#17181]
**This is a Bug Report**

**Problem:**
In K8s doc, there are command examples which require root privilege. But there is inconsistency of use of `sudo` command in example (e.g. [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/)&[here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/) with sudo but [here](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) without).

However there are pros&cons:
  * Command example with `sudo`
      * **Pro:**
          1. Clear indication where root privilege is required
      * **Con:**
          1. dependency on tool (`sudo`)
  * Command example without `sudo`
      * **Pro:**
          1. concise look of doc
          1. no dependency on tool
      * **Con:**
          1. reader who is relatively new to *nix should run commands with try&error
          1. addition of indication where root privilege is required to doc

**Proposed Solution:**
To add official recommendation around this to [style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

**Page to Update:**
Too many pages, cannot specify here.

**Comment by sftim** [comment]
What do other projects do for this?

**Comment by neolit123** [comment]
i think the best option is to include notes in relevant locations that "these commands need to be run as root".

**Comment by vanou** [comment]
In terms of *code snippet*, it's better to include `sudo`. However simple look of *no sudo* is also nice.

**Comment by vanou** [comment]
I think this problem is related to [style guide](https://kubernetes.io/docs/contribute/style/style-guide/). And according to [*Style guideline* on this section](https://kubernetes.io/docs/contribute/start/#the-basics-about-our-docs), topics around style guide should be discussed at SIG Docs meeting.

I'll talk about this at next meeting.

**Comment by vishakhanihore** [comment]
@vanou @aimeeu  Can I work on this issue, if the issue has been already discussed in the meeting?

**Comment by vanou** [comment]
@vishakhanihore 
Sorry. I haven't yet discussed it on meeting. However I'll do on next meeting (10th Dec).

**Comment by vanou** [comment]
I talked about this at today's meeting(2019/12/10). And I have a role to update *Document Style Guide* to add a guide around this issue. Discussion around this should be held at PR I'll create.

**Comment by vanou** [comment]
@vishakhanihore Sorry. I have no time to work on this issue. So, if possible, please take over this issue.

In brief, to tackle this issue
 1. Determine whether to use `root` or not in doc by yourself
 1. Claim your idea & discuss at community
 1. Make consensus
 1. Modify doc according to consensus

See meeting video at 2019/12/10 for what was discussed.

/remove-lifecycle stale
