### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/components/

### ISSUE THREAD

**Issue by Maheshkumar-Kakade** [kubernetes/website#17215]
**This is a Bug Report**

**Problem:**
In cloud-controller-manager documentation section, version number is incorrect it says release 1.6 but latest release is 1.16, below it text from that section

cloud-controller-manager runs controllers that interact with the underlying cloud providers. The cloud-controller-manager binary is an alpha feature introduced in Kubernetes **release 1.6.**

**Proposed Solution:**
I think, it should be release 1.16 

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/components/#cloud-controller-manager

1.16

**Comment by lojies** [comment]
The  cloud-controller-manager binary is introduced in Kubernetes release 1.6.
It has existed for a long time and isn't a new feature in 1.16.
So this page is ok and no need to update.
