### ISSUE TITLE
Document “container runtime” concept

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#17232]
**This is a Feature Request**

**What would you like to be added**
- Add a new page to the Concepts section that explains container runtimes
- Make the _container runtime_ glossary page reference the new concept page

**Why is this needed**
Kubernetes supports multiple container runtimes. Readers can expect to find a page that explains the concept.

**Comments**
The existing glossary entry has a broken link to `/docs/reference/generated/container-runtime`

/priority important-longterm

**Comment by lojies** [comment]
Container Runtime is considered as one of Kubernetes terminology and is explaned in page docs/reference/glossary.
It has a link [https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-container-runtime](https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-container-runtime)
with explanation like below:
```
The container runtime is the software that is responsible for running containers.[-]
Kubernetes supports several container runtimes: Docker, containerd, cri-o, rktlet and any implementation of the Kubernetes CRI (Container Runtime Interface).
```

Is the new page like [https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md)?

**Comment by sftim** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md explains what CRI is, rather than what a container runtime is. There's overlap between the two and it would be OK to copy from [container-runtime-interface.md]9https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/container-runtime-interface.md) when writing the new concept page.

I'd expect that a new concept page on container runtimes would also hyperlink to other relevant docs such as https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Comment by sftim** [comment]
Still worth documenting
/remove-lifecycle stale
