### ISSUE TITLE
"/content/en/docs/reference/kubernetes-api" have both index.* and _index.* files, pick one.

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#17261]
When building the k8s site in Netlify it contains the following error: "WARN 2019/10/27 18:38:58 Content directory "/opt/build/repo/content/en/docs/reference/kubernetes-api" have both index.* and _index.* files, pick one."

It looks like @kbhawkey tried to fix it in #16947 - however, i'm not sure why we're still seeing it. Potentially the error doesn't like the word index to be within any other file than index.

**Comment by kbhawkey** [comment]
@jimangel , that is interesting. Do you have the full log? The error message seems odd as the *new* file does not start with `_index`. How is the cache cleared? Or perhaps there is a bug.

**Comment by jimangel** [comment]
I agree completely :)

I'll do some testing on my personal Netlify, we might need to clear the cache and rebuild as you mentioned. That's only done in the Netlify GUI as far as I know.
