### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/networking/

### ISSUE THREAD

**Issue by vovcia** [kubernetes/website#17317]
**This is a Bug Report**

**Problem:**
Contiv is listed as cluster networking solution. It seems Contiv is not supported anymore on recent K8s versions, look https://github.com/contiv/install/issues

**Proposed Solution:**
Remove Contiv from list till supported on recent K8s.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/networking/

**Comment by RA489** [comment]
@vovcia can you copy paste exact command executed to debug this more?
