### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by LuckySB** [kubernetes/website#17337]
**This is a Bug Report**

**Problem:**
yaml indent broken on https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components

source .md id fine https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/workloads/controllers/statefulset.md

**Comment by sftim** [comment]
This seems like a Hugo bug, rather than a website bug. Still something that is worth fixing.

/kind bug

**Comment by tengqm** [comment]
Dup of ##17792, which is being fixed by #17891.
