### ISSUE TITLE
Improvement for k8s.io/zh/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#17333]
This chinese version is not updated.

allowPrivilegeEscalation is not mentioned, and there are no examples for default psp

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#privilege-escalation
https://kubernetes.io/zh/docs/concepts/policy/pod-security-policy/

**Comment by ydcool** [comment]
WIP https://github.com/k8smeetup/website-tasks/issues/3496

**Comment by tanjunchen** [comment]
@ydcool  
any progress?

**Comment by ydcool** [comment]
@tanjunchen Sorry for the long delay... finally pushed.
