### ISSUE TITLE
Issue with k8s.io/zh/docs/home/ translation

### ISSUE THREAD

**Issue by anorek** [kubernetes/website#17365]
**This is a Bug Report**

**Problem:**
lack of punctuation mark by the end of 参考 card

**Proposed Solution:**
addmissing 。for coherence.

**Page to Update:**
https://k8s.io/zh/docs/home/

**Comment by tengqm** [comment]
would you like propose a fix?

**Comment by anorek** [comment]
yes! 
https://github.com/kubernetes/website/pull/17398
