### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

### ISSUE THREAD

**Issue by dyllandry** [kubernetes/website#17386]
**This is a Bug Report**

**Problem:** I cannot highlight the page's objectives properly, instead the title "Overview of Kubernetes Services" is highlighted.

**Proposed Solution:**
Remove the "Overview of Kubernetes Services" title `::before` pseudo-selector which is styled with `height: 100px` and `margin-top: -100px`. It's that `::before` pseudo-selector which is intercepting the click when I try to highlight the objectives above it.
**Page to Update:**
[k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/](k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/)

**Comment by sftim** [comment]
Thanks for reporting this @dyllandry 
/priority backlog
