### ISSUE TITLE
Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by veera2019** [kubernetes/website#17396]
i am running the below command i am getting error
helm install --name nfs-server-provisioner stable/nfs-server-provisioner --set persistence.enabled=true,persistence.size=8Gi
 i am getting this error **Error: validation failed: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"**
 
So how to reslove this issue and how to change apps/v1beta2 to apps/v1beta1

**Comment by lojies** [comment]
What's your kubernetes version?It seems like StatefulSet has been removed from your version.I think you need to change apps/v1beta2 to apps/v1.

**Comment by veera2019** [comment]
i am using 1.16.1 version 
how to change **apps/v1beta2 to apps/v1**
where i need to change can you give me command or procedure

**Comment by veera2019** [comment]
> What's your kubernetes version?It seems like StatefulSet has been removed from apps/v1beta2 in your version.I think you need change apps/v1beta2 to apps/v1.

i am using 1.16.1 version
how to change apps/v1beta2 to apps/v1
where i need to change can you give me command or procedure

**Comment by lojies** [comment]
It seem like this file：
[https://github.com/helm/charts/blob/master/stable/nfs-server-provisioner/templates/statefulset.yaml](https://github.com/helm/charts/blob/master/stable/nfs-server-provisioner/templates/statefulset.yaml)
But i don't know how to change this local if not create a pr to helm.

**Comment by lojies** [comment]
Maybe you can try follow this:
```shell
cd ~/.helm/cache/archive
tar -xvf nfs-server-provisioner-0.3.1.tgz
vi nfs-server-provisioner/templates/statefulset.yaml
#change apiversion apps/v1
helm package nfs-server-provisioner
helm serve &
helm repo add local http://127.0.0.1:8879
helm repo update
helm install local/nfs-server-provisioner --name my-nfs\
```
if this is not ok, do this:
```shell 
cd ~/.helm/repository/local
tar -xvf nfs-server-provisioner-0.3.1.tgz
vi nfs-server-provisioner/templates/statefulset.yaml
helm package nfs-server-provisioner
Successfully packaged chart and saved it to: /root/.helm/repository/local/nfs-server-provisioner-0.3.1.tgz
# helm install local/nfs-server-provisioner --name my-nfs
NAME:   my-nfs
LAST DEPLOYED: Tue Nov  5 02:32:23 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                           AGE
my-nfs-nfs-server-provisioner  0s

==> v1/ClusterRoleBinding
NAME                           AGE
my-nfs-nfs-server-provisioner  0s

==> v1/Pod(related)
NAME                             READY  STATUS             RESTARTS  AGE
my-nfs-nfs-server-provisioner-0  0/1    ContainerCreating  0         0s

==> v1/Service
NAME                           TYPE       CLUSTER-IP      EXTERNAL-IP  PORT(S)                                 AGE
my-nfs-nfs-server-provisioner  ClusterIP  10.104.223.176  <none>       2049/TCP,20048/TCP,51413/TCP,51413/UDP  0s

==> v1/ServiceAccount
NAME                           SECRETS  AGE
my-nfs-nfs-server-provisioner  1        0s

==> v1/StatefulSet
NAME                           READY  AGE
my-nfs-nfs-server-provisioner  0/1    0s

==> v1/StorageClass
NAME  PROVISIONER                                  AGE
nfs   cluster.local/my-nfs-nfs-server-provisioner  0s


NOTES:
The NFS Provisioner service has now been installed.

A storage class named 'nfs' has now been created
and is available to provision dynamic volumes.

You can use this storageclass by creating a `PersistentVolumeClaim` with the
correct storageClassName attribute. For example:

    ---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: test-dynamic-volume-claim
    spec:
      storageClassName: "nfs"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi

```

I tried and this was ok.

**Comment by veera2019** [comment]
> StatefulSet is only in apps/v1 in 1.16.1.
> It seem like this file：
> https://github.com/helm/charts/blob/master/stable/nfs-server-provisioner/templates/statefulset.yaml
> But i don't know how to change this local if not create a pr to helm.

Hi i have installed kubernetes 1.14.6 version 
I am installing mongodb using helm command in aws instance i am using below command but mongodb pod and pvc pod status showing pending

**helm install --set mongodbRootPassword=hello,mongodbUsername=mongo,mongodbDatabase=mydata --set volumePermissions.enabled=true --name mongo stable/mongodb**

in PVC pod logs showing **no persistent volumes available for this claim and no storage class is set
error**
in mongodb pod logs showing **pod has unbound immediate PersistentVolumeClaims error**

So can you please suggest me how to resolve this issue.

**Comment by RA489** [comment]
@veera2019 Try using this command to change apps/v1beta2 to apps/v1
`
kubectl convert -f <file> --output-version apps/v1.`

**Comment by snowsky** [comment]
@RA489 convert is deprecated:

> kubectl convert is DEPRECATED and will be removed in a future version.
In order to convert, kubectl apply the object to the cluster, then kubectl get at the desired version.
error: error parsing stable/ipfs/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 6: did not find expected key
