### ISSUE TITLE
Explicitly document that there is no "or" in label filtering

### ISSUE THREAD

**Issue by squillace** [kubernetes/website#17391]
**This is a Bug Report**

Documentation on Recommended Labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
![image](https://user-images.githubusercontent.com/1422718/68087625-92f36c80-fe0c-11e9-8fea-1c7ed31b9cd9.png)

Suggests using several fully ns-scoped labels, each of which involve a '/' char, for example, `app.kubernetes.io/name`. 

The labels documentation https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ indicates that you can/should use comma-separation when using labels. For example, `kubectl get pods -l environment=production,tier=frontend`. This works when NOT using a `/` char in your labels -- that is, ignoring the suggestions in Recommended Labels (https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/).

Given two different resources with labels that are recommended, using the labels and filtering on both in kubectl 1.16 and against server version 1.15.4 results in:

```
🔋 100% $ kubectl get crds,po -l app.kubernetes.io/name=rudr,app.kubernetes.io/part-of=core.oam.dev      
$
No resources found in default namespace.
```

though individually, each label does properly return the resource.

**Proposed Solution:**
It's not clear to me that this isn't a project bug. ns-scoped values should be supported; there's no particular reason why once in a label the char '/' is a problem. Other than lack of intent to support it, that is. Note that https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set specifically says that '/' is supported.

BUT: if there's a reason, then the recommendations for labeling should change. They should eschew the '/' character, and test whether selecting on multiple labels _across resource types_ is supported at all. Even using short labels with no '/' returns nothing for the k8s version above.

In fact, this sequence makes no sense at all if I'm reading the docs correctly. Even selecting more than one short labels across resources does not currently seem to work. I'm probably either reading something incorrectly, or doing something incorrectly, but I can't see what it is.

![image](https://user-images.githubusercontent.com/1422718/68088011-d26f8800-fe0f-11e9-87dd-3f1244ecc7b5.png)

**Page to Update:**
At a minimum https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/, but potentially also https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set and https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by squillace** [comment]
UPDATE: Per a number of helpful peeps on the internet, this is working correctly, but not clearly documented for the following reason: there is no "or" functionality for filtering. The result is that using ',' means "and", in which context the above is correct behavior. NOW I'm doing to request merely that the docs be updated to explicitly state that there is no "or" behavior in either equals or set conditions. Instead, ensure that your approach installs the proper scope-labels so that you can have simpler filter statements -- rather than expecting "or" just wasn't documented yet.

**Comment by sftim** [comment]
Seems like a valid thing to clearly document
/priority important-longterm
