### ISSUE TITLE
Issue with kubeadm downgrade

### ISSUE THREAD

**Issue by BeneaAlinAndrei** [kubernetes/website#17401]
Hello,

I tried to downgrade from Kubeadm 16 to Kubeadm 14. After the downgrade i receive the following error `couldn't create a Kubernetes client from file "/etc/kubernetes/admin.conf": failed to load admin kubeconfig: open /etc/kubernetes/admin.conf: no such file or director`. 
This error is keeping me from initializing any cluster, or to uninstall Kubernetes for a fresh installation. 

If anyone knows how to resolve this matter, thank you very much!

**Comment by neolit123** [comment]
kubeadm doesn't really support downgrade.
