### ISSUE TITLE
Issue with /docs/getting-started-guides/fedora/fedora_ansible_config/

### ISSUE THREAD

**Issue by scottmf** [kubernetes/website#1744]
Page has some good info but it is out of date.

I had to go to https://github.com/kubernetes/contrib/tree/master/ansible for up to date instructions

**Comment by chenopis** [comment]
@scottmf thanks for the suggestion.

Perhaps the page content should be stripped down but with a link to https://github.com/kubernetes/contrib/tree/master/ansible so that there isn't duplicate content that has to be updated.

**Comment by tengqm** [comment]
fwiw, there is a discussion on this here: https://groups.google.com/forum/#!topic/kubernetes-sig-docs/GFnX8DRw7iY
