### ISSUE TITLE
Document how to install latest kubectl for given minor release

### ISSUE THREAD

**Issue by flfr-ibm** [kubernetes/website#17454]
**This is a Bug Report**

**Problem:**
I was looking at the documentation page below for a solution to install the latest version of a specific kubectl release. (e.g latest 1.14 version). However it is not documented there.
**Proposed Solution:**
By searching through github I was able to find a solution similar to downloading the latest release. It would be helpful if this was put into the documentation as well:
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable-1.14.txt)/bin/linux/amd64/kubectl

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by sftim** [comment]
> To download a specific version, replace the `$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)` portion of the command with the specific version.

I think the advice on how to download a specific version is already there. @flfr-ibm do you agree?
/triage support

**Comment by sftim** [comment]
Ah, I think I get it. You want to have a page on how to install the latest version for a specific minor release.

/retitle Document how to install latest kubectl for given minor release
/remove-triage support
/priority backlog
