### ISSUE TITLE
Feature: Website redesign proposal

### ISSUE THREAD

**Issue by lnikell** [kubernetes/website#17458]
Hello, 

I'm very like Kubernetes and we use it with our team on an everyday basis. It's amazing technology that deserves to have a great looking website. Our team wants to do a full redesign(with implementation) of the website for free. We want to make sure that the work will not be meaningless, so we need communication with decision-makers responsible for maintaining the website. Let me know who should I communicate with about it.

We already did a great job for open source projects: [Drone CI](https://www.behance.net/gallery/78532715/Droneio-website-with-cool-HTML-animations), [K6](https://www.behance.net/gallery/87572655/K6-UIUX-for-an-open-source-performance-testing-tool).

My apologies that the issue does not follow guidelines since it's a bit different topic.

**Comment by sftim** [comment]
@lnikell the [documention special interest group](https://github.com/kubernetes/community/tree/master/sig-docs/) leads on the website activity.
See https://kubernetes.io/docs/contribute/ for more information on how to contribute; that has hyperlinks to SIG Docs communications channels such as [Slack](https://kubernetes.slack.com/messages/C1J0BPD2M/).

**Comment by sftim** [comment]
Changing my mind. This is a combined support request (“how do I contribute?”) and feature request (“I want to help redesign the website”). The redesign is the main topic.
/remove-triage support

**Comment by lnikell** [comment]
Thank you @sftim, messaged slack group.
