### ISSUE TITLE
Issue with kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

### ISSUE THREAD

**Issue by Joseph94m** [kubernetes/website#17453]
**This is a Bug Report**
More of an enhancement than a bug report tbh

**Problem:**
As discussed with @neolit123  in kubernetes/kubeadm [1886](https://github.com/kubernetes/kubeadm/issues/1886):  
Running the
`kubeadm join my-url-com:5443 --token <token> --discovery-token-ca-cert-hash sha256:<hash> --control-plane --certificate-key <new-token>`  
returns the following error:
`error execution phase control-plane-prepare/download-certs: error downloading certs: the Secret does not include the required certificate or key - name: external-etcd-ca.crt, path: /etc/kubernetes/pki/etcd/ca.crt`
After discussion it turns out that we need to use the `--config` flag with the phase command that uploads certs to the external etcd, as follows: 
`kubeadm init phase upload-certs --upload-certs --config kubeadm-config.yaml`
**Proposed Solution:**
Update the documentation to show the need to use the `--config` flag with an appropriate yaml config file.

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#uploading-control-plane-certificates-to-the-cluster

**Pull Request:** #17455

**Comment by neolit123** [comment]
thanks
/sig cluster-lifecycle
/kind cleanup
