### ISSUE TITLE
Outdated files in the dev-1.16-ko.5

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#17488]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.16-ko.5 branch.

### 19 files to be modified
1. [ ] content/en/docs/concepts/architecture/nodes.md 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/containers/container-lifecycle-hooks.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/overview/working-with-objects/names.md 1 file changed, 1 insertion(+), 2 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/daemonset.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/workloads/controllers/deployment.md 1 file changed, 22 insertions(+), 22 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/replicationcontroller.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/workloads/controllers/statefulset.md 1 file changed, 1 insertion(+)
1. [ ] content/en/docs/concepts/workloads/pods/init-containers.md 1 file changed, 4 insertions(+), 27 deletions(-)
1. [ ] content/en/docs/concepts/workloads/pods/pod-lifecycle.md 1 file changed, 5 insertions(+), 4 deletions(-)
1. [ ] content/en/docs/reference/_index.md 1 file changed, 2 deletions(-)
1. [ ] content/en/docs/setup/production-environment/container-runtimes.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/administer-cluster/cluster-management.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md 1 file changed, 6 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/tasks/tools/install-minikube.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/hello-minikube.md 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/_index.html 1 file changed, 2 insertions(+)
1. [ ] content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/update/update-intro.html 1 file changed, 2 insertions(+), 2 deletions(-)

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually
to the `content/ko` of `upstream/dev-1.16-ko.5` branch.

For example:
```
# checkout `upstream/dev-1.16-ko.5`
...
# check what is updated in the upstream
git diff upstream/dev-1.16-ko.4 upstream/dev-1.16-ko.5 -- content/en/docs/concepts/architecture/nodes.md
# apply changes to content/ko
vi content/ko/docs/concepts/architecture/nodes.md
...
# commit and push
...
# make PR to `upstream/dev-1.16-ko.5`
```

**Comment by gochist** [comment]
@seokho-son 실수로 `1.15`과 비교하신 것 같아요.

**Comment by seokho-son** [comment]
> @seokho-son 실수로 `1.15`과 비교하신 것 같아요.

감사합니다. 미리 확인해보지 못했네요ㅠㅠ 다시 메시지 정정하였습니다.

**Comment by seokho-son** [comment]
@ysyukr 님. slack, Kubernetes-docs-ko 채널에서, novice 님 께서 해당 이슈를 처리해보 싶다는 의견을 주셨습니다. 먼저 assign 해주셨는데, 이번에는 novice 님께 PR 처리를 부탁드려도 될까요?

**Comment by seokho-son** [comment]
This Issue has been assigned to a contributor who has Id: novice in the slack channel. Thank you !

**Comment by novice81** [comment]
제가 빠르게 assign 하지 않아서 혼란을 드린것 같아 죄송합니다. 작업 진행해볼 수 있게 배려해주셔서 감사합니다!
@ysyukr @seokho-son

**Comment by ysyukr** [comment]
머지가 되었으므로 /close 처리 하겠습니다 :)
