### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by vkkothawale** [kubernetes/website#17497]
Hi Team
I am new to kubernetes and I have install minikube on my local linux box (i.e virtual box) and os is centos 7.5. I am facing following issue while trying to start minikube 
* Requested cpu count 1 is less than the minimum allowed of 2
minikube version is 
minikube v1.5.2
I am running following command 
minikube start --vm-driver=none
Can someone please help me understand what is wrong and resolve this issue ?
Thanks :)

**Comment by lojies** [comment]
@vkkothawale, is the cpu count of your vm is 1?

**Comment by vkkothawale** [comment]
@lojies  yes cpu count of my vm is 1

**Comment by GerkinDev** [comment]
I had this error, and it is discussed in https://github.com/kubernetes/minikube/issues/5010. You can bypass the error message using

```sh
minikube start --extra-config=kubeadm.ignore-preflight-errors=NumCPU --force --cpus 1
```

But the best would still be to increase your CPU count in your VM.

**Comment by RA489** [comment]
@vkkothawale you can either increase your CPU count or can simply ignore the preflight errors NumCPU

**Comment by RA489** [comment]
@vkkothawale Is your issue resolved so that we can close this issue?

**Comment by vkkothawale** [comment]
@GerkinDev I will try the command that you have mentioned and close this issue once that worked. 

Thanks

**Comment by RA489** [comment]
@vkkothawale Sure

**Comment by vkkothawale** [comment]
@RA489 It worked Thanks I will close this issue now
