### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by caihongxu** [kubernetes/website#17501]
**This is a Bug Report**

**Problem:**
The "Deploy our app" section talks about kubectl run command but the example code actually uses kubectl create command. This is confusing.
**Proposed Solution:**
Stick to kubectl create command to be consistent

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by sftim** [comment]
I can (try to) guide anyone who would like to work on this issue.

**Comment by KobayashiD27** [comment]
I would like to work on this issue.
However, I cannot find the inconsistent point about kubectl create command.
Could you guide me?
Has this issue been solved already?

**Comment by sftim** [comment]
@KobayashiD27, I think you're right: I can't see anything to fix either.
/close
