### ISSUE TITLE
Dated content in “Running Kubernetes on CenturyLink Cloud”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#17514]
**Problem:**
[Running Kubernetes on CenturyLink Cloud](https://kubernetes.io/docs/setup/production-environment/turnkey/clc/) is very dated; it talks about “minions” rather than nodes, which means that Kubernetes has moved on quite a lot since that page was last accurate.

**Proposed Solution:**
Either:
- delete the page, and justify that deletion
- review the page and update it to be current.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/turnkey/clc/

**Notes:**
[KEP #1327](https://github.com/kubernetes/enhancements/pull/1327) “3rd party content in documentation” may be relevant here.

/kind cleanup
/language en
/priority backlog

**Comment by SupriyaSirbi** [comment]
Hello @sftim I shall work on this issue and submit the PR for the same. Thanks

**Comment by sftim** [comment]
:ok_hand:

**Comment by sftim** [comment]
Still needs fixing.
/remove-lifecycle stale

**Comment by sftim** [comment]
Let's remove https://kubernetes.io/docs/setup/production-environment/turnkey/clc/
based on https://kubernetes.io/docs/contribute/style/content-guide/
