### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by jongio** [kubernetes/website#17512]
**This is a Bug Report**

**Problem:**
I had to click the echo -e ... command twice in order to start the proxy.
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
@jongio Thanks for letting us know. Could you tell us your OS/browser please so we can investigate?

**Comment by jongio** [comment]
Windows 10/Edgeium Dev

**Comment by BenHall** [comment]
Thanks @jongio. We've made some improvements to ensure the timing issues are taken into account. Users shouldn't need to click twice now.

Thanks for your help.

**Comment by sftim** [comment]
/priority backlog
@jongio Is this fixed?

**Comment by jongio** [comment]
Yes, resolved. Closing.
