### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by HerrKauwer** [kubernetes/website#17511]
**This is a Bug Report**

**Problem:**
In the chapter 'Simulating Pod and Node downtime' it is proposed to move the mysql bin so the readiness command will fail. Doing this will not result in the documented behavior. Instead it will log 'Readiness probe errored' and won't set the pod to not ready. Apparently this is normal (?): https://stackoverflow.com/a/54907712.

**Proposed Solution:**
Instead of moving the mysql bin I stopped the service by running 'service mysql stop'. Resulting in the container being restarted. This will also make server_id 102 disappear from the mysql loop for a short while. The logs message will now turn into a warning instead of an error and the container will restart, fixing the issue.

I don't know how to permanently make the readiness command fail as is described in the docs.

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/

**Comment by sftim** [comment]
Thanks for the report @HerrKauwer 

/kind bug
/priority important-longterm
/language en

**Comment by sftim** [comment]
If the MySQL container image has `nftables` or `iptables` available then a command to block port TCP 3306 might simulate failure as intended.
