### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/coarse-parallel-processing-work-queue/

### ISSUE THREAD

**Issue by Andriy-dev** [kubernetes/website#17534]
**This is a Bug Report**

**Problem:**
Example from the doc is not working

# Create a temporary interactive container
kubectl run -i --tty temp --image ubuntu:18.04
**Proposed Solution:**
# Create a temporary interactive container
kubectl run temp -it --image ubuntu:18.04
**Page to Update:**
https://kubernetes.io/...

**Comment by lojies** [comment]
@Andriy-dev, this seems like no difference between these two command. --tty is equal to -t. And deployment name:temp located at both position is ok.
