### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/assign-pod-node/ https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity

### ISSUE THREAD

**Issue by sagarvelankar** [kubernetes/website#17556]
**This is a Bug Report**

**Problem:**

Below Lines are incorrect

If you specify multiple nodeSelectorTerms associated with nodeAffinity types, then the pod can be scheduled onto a node if one of the nodeSelectorTerms is satisfied.

If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node only if all matchExpressions can be satisfied.

**Proposed Solution:**

They need to be corrected to below

If you specify multiple nodeSelectorTerms associated with nodeAffinity types, then the pod can be scheduled onto a node only if all nodeSelectorTerms can be satisfied.

If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node if one of the matchExpressions is satisfied.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/assign-pod-node

Kubernetes Version: 1.16

**Comment by gm2211** [comment]
There's another related issue in these docs:

https://github.com/kubernetes/website/pull/13906

Made it so that 
```
If the topologyKey *were* failure-domain.beta.kubernetes.io/zone then it would mean that the pod cannot be scheduled onto a node if that node is in the same zone as a pod with label having key "security" and value "S2".)
```
is now misleading, since the `topologyKey` has been changed to be `failure-domain.beta.kubernetes.io/zone`.
