### ISSUE TITLE
The URL of `Resource QoS` is unreachable

### ISSUE THREAD

**Issue by youngdou** [kubernetes/website#17553]
**This is a Bug Report**

**Problem:**
The URL of `Resource QoS`  in `https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/configuration/manage-compute-resources-container.md` is unreachable

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

**Comment by lojies** [comment]
@youngdou, can you post the unreachable url of `Resource QoS`? It's reachable for me.

**Comment by youngdou** [comment]
> @youngdou, can you post the unreachable url of `Resource QoS`? It's reachable for me.

it's `https://git.k8s.io/community/contributors/design-proposals/node/resource-qos.md`

**Comment by lojies** [comment]
@youngdou, it works well.Maybe you can try a vpn?

**Comment by RA489** [comment]
> https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md

This is accessible. may be it is restricted in your country.
