### ISSUE TITLE
Incorrect translation in website/content/zh/docs/concepts/overview/components.md

### ISSUE THREAD

**Issue by phan-pivotal** [kubernetes/website#17552]
**This is a Bug Report**

**Problem:**
Too many content missing and incorrect translation while marked as the latest 1.16 version documents in Chinese.

For example: 
"However, for simplicity, set up scripts typically start all master components on the same machine"

"the same machine" in English has been translated to "the same virtual machine" in Chinese.

**Proposed Solution:**
Have some body review the Chinese version translation or mark it as a outdate version translation
**Page to Update:**
https://kubernetes.io/zh/docs/concepts/overview/components/

**Comment by ydcool** [comment]
WIP
/assign @ydcool

**Comment by tanjunchen** [comment]
@ydcool  
any progress?

**Comment by ydcool** [comment]
@tanjunchen Sorry for the delay. Update has been pushed.
