### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/authorization/

### ISSUE THREAD

**Issue by shadih** [kubernetes/website#17565]
**This is a Bug Report**

**Problem: kubernetes api server not using custom flags for authentication/authorization webhook based

I'm trying to configured the kube apiserver to use webhooks for authentication/authorization and made following changes:

# pwd
/etc/kubernetes/manifests
# diff kube-apiserver.yaml kube-apiserver.yaml_orig
18c18
<     - --authorization-mode=Node,RBAC,Webhook
---
>     - --authorization-mode=Node,RBAC
48,50d47
<     - --authentication-token-webhook-config-file=/etc/kubernetes/auth/authn_webhook
<     - --authorization-webhook-config-file=/etc/kubernetes/auth/authz_webhook
<     - --authorization-webhook-cache-authorized-ttl=2m0s
#

I then restart the kube-api server via: "systemctl restart kubelet"; ps -eaf|grep apiverser shows process was restarted but it doesn't show these new custom flags to use the webhooks.

My question, after making changes to kube-apiserver.yaml to add these custom flags; is there anything else i need to do to get the apiserver to use them?

this is on "Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)"; and install was done using kubespray 2.7.6 and kubernetes version is v1.13.2

Any help is greatly appreciated. Thanks.

# hostnamectl
   Static hostname: alpd1004
   Pretty hostname: alpd1004.aldc.att.com
         Icon name: computer-server
           Chassis: server
        Machine ID: d3d19c7d7dfe476d89b4a1a71f157522
           Boot ID: 1c7225665f3242eb9215e106f4c6abb4
  Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.6:GA:server
            Kernel: Linux 3.10.0-957.10.1.el7.x86_64
      Architecture: x86-64
#

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by lojies** [comment]
@shadih, you restart kube-apiserver or kubelet actually?

**Comment by shadih** [comment]
Hello @lojies , After I made the changes below in  kube-apiserver.yaml, right i restared kubelet.
I thought that's how we get kube-apiserver to restart; is there another way to restart it?

I also removed the apiserver docker containers and re-started kubelet with no success:
  # docker rm -f `docker ps | grep apiserver | awk '{print $1}'`
  50d330fb4a00
  303ce3c0fb0d
  # systemctl restart kubelet

So now I have the kube-apiserver.yaml with the updated custom flags but still not able to get the kube-apiserver to run w/ these updated flags.

Thanks!




# pwd
/etc/kubernetes/manifests
# diff kube-apiserver.yaml_orig kube-apiserver.yaml
18c18
<     - --authorization-mode=Node,RBAC
---
>     - --authorization-mode=Node,RBAC,Webhook
47a48,50
>     - --authentication-token-webhook-config-file=/etc/kubernetes/auth/authn_webhook
>     - --authorization-webhook-config-file=/etc/kubernetes/auth/authz_webhook
>     - --authorization-webhook-cache-authorized-ttl=2m0s
#

**Comment by shadih** [comment]
I removed kube-apiserver.yaml_orig from /etc/kubernetes/manifests since it might have been causing kubelet to start the original apiserver; now issue i'm having is that the apiserver is not coming up; I only see 1 docker container:

#  docker ps|grep -i api
4db4d8b45ea8        gcr.io/google_containers/pause-amd64:3.1   "/pause"                 About an hour ago   Up About an hour                        k8s_POD_kube-apiserver-alpd1004.aldc.att.com_kube-system_cd4283f54a4f1f6475f1ef3cdb788663_0
#

I think I'm missing the main apiserver container: k8s_kube-apiserver_kube-apiserver
but not sure why it's not coming up. Any logs I can look at?

**Comment by shadih** [comment]
Issue resolved; I had to remove the kube-apiserver.yaml_orig from /etc/kubernetes/manifests
