### ISSUE TITLE
DNS cluster addon service name incorrectly mentioned as "CoreDNS" instead of "Kube-dns"

### ISSUE THREAD

**Issue by gireeshp** [kubernetes/website#17562]
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#dns , the DNS cluster addon service's name incorrectly mentioned as "CoreDNS" instead of "Kube-dns".

**Proposed Solution:**
Change the line
"The rest of this section will assume you have a Service with a long lived IP (my-nginx), and a DNS server that has assigned a name to that IP (the CoreDNS cluster addon), so you can talk to the Service from any pod in your cluster using standard methods (e.g. gethostbyname)" 
-to-
"The rest of this section will assume you have a Service with a long lived IP (my-nginx), and a DNS server that has assigned a name to that IP (the Kube-dns cluster addon), so you can talk to the Service from any pod in your cluster using standard methods (e.g. gethostbyname)"

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#dns

Additional Information:
Same change to be made in languages - EN, ID & ZH (these are the languages where this section is documented)

**Comment by sftim** [comment]
CoreDNS is the project and kube-dns is the internal app name. It's important to clarify so that readers aren't left confused.

/priority backlog

**Comment by sftim** [comment]
Closing because the original bug description is not valid
