### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

### ISSUE THREAD

**Issue by pggp** [kubernetes/website#17560]
**This is a Bug Report**

**Problem:**
Example shown on this page does not work out of the box (for me at least)

**Proposed Solution:**

Update procedure to make it work again :-D

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

I'm not using kubernetes but minikube as page recommends

$ minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

$ docker version 
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:09:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by RA489** [comment]
@pggp can you please copy paste the exact command you executed to debug this more.
