### ISSUE TITLE
Wrong port used when accessing pod proxy in tutorial

### ISSUE THREAD

**Issue by JPMoresmau** [kubernetes/website#17575]
**This is a Bug Report**

**Problem:** 
When redoing the interactive tutorial on a local install of Minikube, the command:
```
curl http://localhost:8001/api/v1/namespaces/defaulds/$POD_NAME/proxy/
```
Failed with  `Connection refused`

**Proposed Solution:**
The node server actually listens on port 8080 (you see it later when you run a bash session in the container), so I used the command
```
curl http://localhost:8001/api/v1/namespaces/defaulds/$POD_NAME:8080/proxy/
```

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

**Comment by sftim** [comment]
Make sure to use `kubectl proxy`, which does listen on port 8081

/triage support

**Comment by sftim** [comment]
@JPMoresmau I think the existing interactive tutorial is correct

**Comment by JPMoresmau** [comment]
Yes the proxy is correct, it does listen on 8001:
```
# kubectl proxy
Starting to serve on 127.0.0.1:8001
```
, and it's not the localhost:8001 that's failing, it's the underlying call to the pod. It tries to access the pod on port 80 while the pod listens on 8080. It works on the tutorial, yes, but if you redo the tutorial steps on your own machine it doesn't.

**Comment by sftim** [comment]
OK, that makes sense.
/priority important-longterm
/remove-triage support

**Comment by all43** [comment]
Run into this issue when trying to reproduce tutorial on local machine. Due to inconsistency between tutorial modules 2 and 3, it's not possible to fully reproduce the sequence. In the module three deployment runs with containerPort already set to 8080, and in the previous module we create deployment without setting any port, which defaults to 80.

**Comment by euyuil** [comment]
I'm having exactly the same issue and could unblock myself by following the "**Proposed Solution**". Perhaps the issue should be 
/reopen

**Comment by powellchristoph** [comment]
Ran into this issue attempting to follow along with my own k8s.
