### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/nodelocaldns/

### ISSUE THREAD

**Issue by rooftop90** [kubernetes/website#17583]
**This is a Bug Report**

**Problem:** Update the Website to show feature availability nodelocaldns for Kubernetes Version 1.16. Currently it doesn't show the feature availability for the latest k8s version. Consulting the documentation should show the feature status for v.1.16

**Proposed Solution:**
Update the section feature availability for k8s version 1.16
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

**Comment by sftim** [comment]
That page should use a [feature-state shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#feature-state) in the overview, rather that describing the state at the foot of the page in a table.

This seems like a
/good-first-issue
