### ISSUE TITLE
Document kubeadm upgrade to v1.17

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#17582]
**This is a Feature Request**

**What would you like to be added**
Describe how to update a cluster from v1.16 to v1.17, using `kubeadm`

**Why is this needed**
The v1.17 release is imminent.

**Comments**
https://k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by sftim** [comment]
@daminisatya is this the right way to track this work?

**Comment by neolit123** [comment]
i was wondering what we are missing. looks like we forgot about this this cycle
cc @fabriziopandini 

i will send a PR later today.

**Comment by sftim** [comment]
Done
/close
