### ISSUE TITLE
Localize strap line for https://kubernetes.io/de/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#17593]
**This is a Bug Report**

**Problem:**
“Production-grade container orchestration” is untranslated on https://kubernetes.io/de/

**Proposed Solution:**
Translate “Production-grade container orchestration” into German

**Page to Update:**
https://kubernetes.io/de/

**Additional Information:**
On the same page, the following are also untranslated:
- “Planet Scale”
- “Never Outgrow”
- “Run Anywhere”

- “Kubernetes Features”

/language de
/kind cleanup

**Comment by sftim** [comment]
Related to #14137

**Comment by sftim** [comment]
/good-first-issue
(vorausgesetzt sprechen Sie Deutsch)

**Comment by kanhaiyaagrawal01** [comment]
Hey @sftim, I would like to take this up

**Comment by sftim** [comment]
@kanhaiyaagrawal01 please feel free! Would you like any guidance?

**Comment by pogo-lang** [comment]
Hey @sftim , is anybody working on this ? If not I would like to take this up.

**Comment by sftim** [comment]
@pogo-lang please feel free to work on this. You can liaise with @kanhaiyaagrawal01 and it's also OK to submit a pull request separately.

([Slack](https://kubernetes.slack.com/messages/C1J0BPD2M/) is a handy way to chat in more detail if several people do decide to collaborate, or if you want to ask for advice).

**Comment by sftim** [comment]
I've submitted a PR (#18263) that fixes just the strapline, not the remaining text.

**Comment by sftim** [comment]
This is done
/close

I'll open a follow up issue
