### ISSUE TITLE
 Localize strap line for https://kubernetes.io/ja/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#17595]
**This is a Bug Report**

**Problem:**
“Production-grade container orchestration” is untranslated on https://kubernetes.io/ja/

**Proposed Solution:**
Translate “Production-grade container orchestration” into Japanese

**Page to Update:**
https://kubernetes.io/ja/

**Additional Information:**
/language ja
/kind cleanup

**Comment by inductor** [comment]
It's merged in the Japanese branch and will be applied once it goes on the upstream
