### ISSUE TITLE
mysql-wordpress-persistent-volume article creates an invalid Service object

### ISSUE THREAD

**Issue by kenmccann** [kubernetes/website#17612]
**This is a Bug Report**

**Problem:**
The Service definition in the wordpress-deployment.yaml has a selector matching the "wordpress" label.  Then the Deployment definition in the mysql-deployment.yaml defines the *mysql* Deployment as "`app: wordpress`" in the metadata.  This causes the wordpress service definition to match *both* the wordpress pod and the mysql pod.  So when routing http traffic to the wordpress Service, there's an attempt to serve wordpress requests from wordpress and also mysql.  

**Proposed Solution:**
Change all labels and selectors to use "wordpress-mysql" in mysql-deployment. 

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#add-resource-configs-for-mysql-and-wordpress

**Comment by sftim** [comment]
I'm not sure that the issue description is recommending the right fix.
I'd expect to narrow the selector that the Service uses, so that all of the Wordpress Pods can keep `app: wordpress`.

For example, the web Pods could be labelled `app.kubernetes.io/instance=wordpress-foobar` and `app.kubernetes.io/component=web` and then the selector matches on both.

**Comment by sftim** [comment]
Does that make sense @kenmccann ? See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ for the reference behind my thinking here.

**Comment by kenmccann** [comment]
I've realized my own mistake @sftim - thanks for pointing out the recommended concepts.  
At some point during my own deployment, I had commented out `tier: frontend` in the Service definition for Wordpress. 
This caused the mysql pod to be selected into the Service as well.  

User error.  Let's cancel this.
