### ISSUE TITLE
CoreDNS addon needs a README about how to enable it

### ISSUE THREAD

**Issue by gireeshp** [kubernetes/website#17620]
**This is a Feature Request**

**What would you like to be added**
[CoreDNS](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/coredns) cluster add-on needs a README similar to the [kube-dns](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/kube-dns) cluster add-on.

**Why is this needed**
In order to explain to the users how to enable the add-on.
And as per issue #17563 and the discussion thread in this [PR](https://github.com/kubernetes/website/pull/17563)

**Comment by sftim** [comment]
Seems like a good idea
/priority important-longterm
/language en
/kind feature
