### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by Feixu2015** [kubernetes/website#17621]
**This is a Bug Report**

**Problem:**
The right learn window is too small.
**Proposed Solution:**
Can make the left catalog tree to be  folded by a button ?
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the suggestion
/kind feature
/priority backlog
