### ISSUE TITLE
Patch PowerShell example does not work on Windows

### ISSUE THREAD

**Issue by lfshr** [kubernetes/website#17630]
**This is a Bug Report**

kubectl PowerShell example does not work in Windows. `cat` is an alias for Get-Content, which by default parses a file line-by-line.

**Proposed Solution:**
Change PowerShell example to use the -Raw flag in Get-Content cmdlet (and change `cat` to `Get-Content` to avoid ambiguity between the Windows `Get-Command` alias and Unix `cat` command).

```
kubectl patch deployment patch-demo --patch $(Get-Content patch-file.yaml -Raw)
```

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/

**Comment by sftim** [comment]
Seems like a valid fix
/priority backlog
/good-first-issue

**Comment by rashmi43** [comment]
I would like to take this up.

**Comment by unyilmelenoyska** [comment]
[Subscribe] ( https://www.youtube.com/watch?v=m-9fXtTEwDE )
