### ISSUE TITLE
Add Antrea as a CNI option in create-cluster-kubeadm

### ISSUE THREAD

**Issue by yasensim** [kubernetes/website#17634]
**This is a Feature Request**

**What would you like to be added**
Add Antrea as a CNI option.
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Why is this needed**
Project Antrea is a new CNI project that integrates easily with clusters provisioned using kubeadm.
**Comments**
https://github.com/vmware-tanzu/antrea

**Comment by neolit123** [comment]
hello, there is a plan to prune all CNI plugins outside of those not endorsed by the CNCF or higher popularity.

see https://github.com/kubernetes/enhancements/pull/1327

/assign @sftim 
/sig cluster-lifeceycle

**Comment by yasensim** [comment]
@neolit123 thanks for your comment. Could you please merge it until there is proper placeholder for all cni plugins so we can move all together?

**Comment by sftim** [comment]
There isn't yet consensus on kubernetes/enhancements#1327 so I think it is OK to mention Antrea in a list of CNI plugins (possibly, pending later changes).

What's the case for shortlisting Antrea on the page about using kubeadm for creating a new cluster?

**Comment by neolit123** [comment]
@yasensim have you run conformance tests on the new CNI plugin?
https://github.com/cncf/k8s-conformance/blob/master/instructions.md

we had this as a requirement before adding new CNI plugins to the kubeadm page - i.e. seeing the conformance result logs.

**Comment by salv-orlando** [comment]
good morning @neolit123  - what should be the preferred way of sharing conformance tests?

@sftim imho the case would be mostly adding another CNI option (OSS and actively maintained - albeit very young). kubernetes/enhancements#1327 is about removing vendor pitches, which I completely understand. I don't think the Antrea CNI option falls in this category though.

On the other hand I noticed https://github.com/kubernetes/website/pull/17694 handles removal of unmaintained CNIs, and therefore is a bit unrelated to this one?

**Comment by dims** [comment]
fyi, we now have a public kind based CI for Antrea - https://github.com/vmware-tanzu/antrea/pull/151

**Comment by antoninbas** [comment]
We have also run the conformance tests on the master branch of Antrea a couple days ago (not automated yet). I uploaded the logs there: https://antrea.s3-us-west-2.amazonaws.com/conformance/201911250311_sonobuoy_9cc75991-3b60-4c9f-8f9c-65d4b40b8e53.tar.gz

**Comment by dims** [comment]
@neolit123 @sftim we now have 
- fully open source CNI implementation
- fully public CI (using kind)
- private test bed running conformance tests (we could consider adding the logs to test grid or something)
- at least one set of public logs

is this enough for https://github.com/kubernetes/website/pull/17635 ? what else needs to be done? please guide @antoninbas and others. we now have #antrea channel on k8s slack as well for quick conversations if needed.

**Comment by neolit123** [comment]
the following last minute criteria was put together for a CNI plugin to be added to the kubeadm guide:

- pass the conformance suite using Sonobuy
- be part of the CNCF CNN landscape:
https://landscape.cncf.io/category=cloud-native-network&format=card-mode&grouping=category
https://github.com/cncf/landscape
- be somewhat popular (this is arbitrary)

please note this criteria was not put together to block Antrea specifically but rather to block the addition of unknown CNI plugins. we get requests like this quite often.

the kubeadm setup guide is not an advertisement platform or a platform for debug signal.
thank you.

/assign @timothysc 
(for visibility)

**Comment by neolit123** [comment]
existing plugins that do not match this criteria are being removed: https://github.com/kubernetes/website/pull/17694

**Comment by dims** [comment]
@neolit123 ack. can you please make sure this criteria is listed in the doc updated in https://github.com/kubernetes/website/pull/17694 ?

**Comment by neolit123** [comment]
not if this is appropriate. will defer to sig-docs whether we want to include the criteria as part of the website pages. @zacharysarah @sftim

**Comment by sftim** [comment]
I'll leave policy to the [related KEP](https://github.com/kubernetes/enhancements/pull/1327); for this change specifically, I agree that it's not a good fit for the page being changed.

**Comment by zacharysarah** [comment]
Thanks for the feedback, all. Closing this PR based on reviewer responses.

/close
