### ISSUE TITLE
Translate /docs/contribute/style/index.md into Korean

### ISSUE THREAD

**Issue by reung37** [kubernetes/website#17656]
This is a Feature Request

What would you like to be added
Translate docs/contribute/style/index.md in Korea in Korean

Why is this needed
The following files are not translated into Korean.
/en/ docs/contribute/style/index.md in Korean

Comments
Page to update : https://kubernetes.io/docs/contribute/style/

I am working on translating this document.
This document translation will be submitted to the next branch(dev-1.16-ko.4).

/language ko

**Comment by sftim** [comment]
/retitle  Translate /docs/contribute/style/index.md into Korean
/priority backlog

**Comment by sftim** [comment]
@reung37 thanks for stepping forward
