### ISSUE TITLE
Improvement for k8s.io/docs/setup/

### ISSUE THREAD

**Issue by usergithubfor** [kubernetes/website#17650]
The Kubernetes technology is best in the containerization , their is no doubt about its ability .
But , Kubernetes must improve its documentation and need an urgent attention on its documents .
Because , the present documents are very hard to find the installation section , and their are no section where a person can find the installation steps.
So , its a humble request to the community , please look after the installation documentation as well .

**Comment by sftim** [comment]
@usergithubfor if you could pick one improvement to that area, what would you prioritize?

**Comment by tengqm** [comment]
@usergithubfor Have you checked the https://kubernetes.io/docs/setup/ page where many ways of installation have been documented? Feel free to reopen this if that is what you need.
