### ISSUE TITLE
Update /ja/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#17669]
**This is a Feature Request**

**What would you like to be added**
Update /ja/docs/tasks/tools/install-minikube/

**Why is this needed**
This document is outdated.

**Comments**

https://kubernetes.io/docs/tasks/tools/install-minikube/
https://kubernetes.io/ja/docs/tasks/tools/install-minikube/

/language ja
/assign
/kind feature
/priority backlog

**Comment by RA489** [comment]
This document has been moved here https://minikube.sigs.k8s.io/docs/start/linux/

**Comment by oke-py** [comment]
Oh, thanks for information.
