### ISSUE TITLE
タスク is missing in menu

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#17712]
**This is a Bug Report**

**Problem:**

タスク is missing.
![ss_ 2019-11-21 16 28 42](https://user-images.githubusercontent.com/4710215/69316438-2dacd180-0c7c-11ea-8918-aa287069bf20.png)

ref:
![ss_ 2019-11-21 16 28 53](https://user-images.githubusercontent.com/4710215/69316492-4a490980-0c7c-11ea-8b85-5022c6975690.png)

**Proposed Solution:**

タスク should be there between コンセプト and チュートリアル.

**Page to Update:**
all of https://kubernetes.io/ja/

/language ja

**Comment by inductor** [comment]
FYI タスク = task in Japanese
