### ISSUE TITLE
deployment page: error format 

### ISSUE THREAD

**Issue by zgfh** [kubernetes/website#17724]
**This is a Bug Report**

**Problem:**

error yaml format
![image](https://user-images.githubusercontent.com/11729624/69356101-dfb8bd80-0cbd-11ea-821f-c74718d8ef84.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

1.16

**Comment by sftim** [comment]
That's valid YAML, but not a valid manifest for a Service
`app: nginx` should be indented (both occurrences)
Good spot @zgfh 
/kind bug
/help

If someone is fixing this, consider migrating to a `{{ codenew }}` block - see https://kubernetes.io/docs/contribute/style/write-new-topic/#embedding-code-in-your-topic for details.

**Comment by kbhawkey** [comment]
@zgfh , There is a known issue with formatting YAML that follow a list item.
This issue seems to be the same as, https://github.com/kubernetes/website/pull/17340?

**Comment by tengqm** [comment]
Dup of ##17792, which is being fixed by #17891.
