### ISSUE TITLE
Improvement for k8s.io/docs/concepts/: hard to get to reference doc from concepts doc

### ISSUE THREAD

**Issue by farrellit** [kubernetes/website#17725]
I have the hardest time getting to the reference material for something covered by a concept.  The concept is a fine intro, but once I actually start using it, the concept does not help me author a yaml file.

**Comment by RA489** [comment]
@farrellit can you please help us elaborate your issue so that we can help?

**Comment by tengqm** [comment]
Concept pages are always general introductions to something. If you want more detailed information, with examples, continue reading the tasks section. We cannot cover all details in concepts.
