### ISSUE TITLE
docs/reference/access-authn-authz/rbac leads to top page when switching a language

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#17738]
**This is a Bug Report**

Switching language doesn't properly work on https://kubernetes.io/docs/reference/access-authn-authz/rbac/

It leads to top page which is not the expected behavior.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by sftim** [comment]
Also see #17737

**Comment by tengqm** [comment]
This is because those pages are not yet localized.

**Comment by inductor** [comment]
@tengqm Why does it have "Japanese" in the list? 🤔

**Comment by tengqm** [comment]
The list of language is from global configuration. We do have "Japanese" in localization. However, there are translation work going on which fall behind the English main site.

**Comment by sftim** [comment]
:thought_balloon: I'm wondering if it's feasible to mark a localization as available in general but missing for the current page.

(if I take this idea further, it belongs in its own issue)

**Comment by tengqm** [comment]
This is solved.
/close
