### ISSUE TITLE
Federation page is out-of-date

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#17736]
**This is a Bug Report**

**Problem:**
Some links from [setup-cluster-federation-with-kubefed page](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/federation/set-up-cluster-federation-kubefed.md) ( website url is https://kubernetes.io/docs/tasks/federation/  ) are invalid and out-of-date.

for instance, link for `kubefed` https://github.com/kubernetes/website/blob/master/docs/admin/kubefed is invalid and now it shows `page not found`. link for `kubefed init`https://kubernetes.io/docs/admin/kubefed_init/ is also not found now.

**Proposed Solution:**
update these links or content

**Page to Update:**
https://kubernetes.io/docs/tasks/federation/

**Comment by RA489** [comment]
`federation-v1` has been officially deprecated and releacement is` federation-v2 `https://github.com/kubernetes-sigs/kubefed

**Comment by Colstuwjx** [comment]
Yes, @RA489  The page title is already been `Set up Cluster Federation with Kubefed
`, but some links in this page is out-of-date, see also #16776 as @sftim  referenced.

**Comment by RA489** [comment]
@Colstuwjx Agreed. some of the contents and links needs to be updated. Thanks for pointing out!

**Comment by sftim** [comment]
/priority important-longterm

so as not to mislead readers

**Comment by Colstuwjx** [comment]
Closing this issue since federation v1 for en pages has been cleared.
