### ISSUE TITLE
docs/tasks/configure-pod-container/configure-pod-configmap leads to top page when switching a language

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#17737]
**This is a Bug Report**

Switching language doesn't properly work on https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

It leads to top page which is not the expected behavior.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

**Comment by sftim** [comment]
I think I have seen this behavior on other pages too (and did not realise it was a bug)
/kind bug
/priority important-longterm

**Comment by tengqm** [comment]
Same here. The mentioned pages are not yet localized. So switching languages will redirect you back to the English version -- the correct behavior.
