### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by strbean** [kubernetes/website#17752]
**This is a Bug Report**

**Problem:**

Page makes no reference to the claimRef property, or bi-directional binding.

claimRef property is only documented in the
[api reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#persistentvolumespec-v1-core), and includes the following in the description:

> More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#binding

It is discouraging to click through and find no additional information!

**Proposed Solution:**

Add documentation describing bi-directional binding of PVs and PVCs.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding

**Comment by danpopSD** [comment]
#17914
