### ISSUE TITLE
Missing usage docs for kind: PodTemplate

### ISSUE THREAD

**Issue by jwietelmann** [kubernetes/website#17750]
I know that there is a PodTemplate resource available, but none of the docs seem to mention it or say how it could be used. Can I reference a named PodTemplate from a Deployment or Job spec? If so, how?

**Comment by sftim** [comment]
Is https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates the documentation you were looking for @jwietelmann ?

**Comment by jwietelmann** [comment]
@sftim No, I am not talking about embedding pod template specs in other resources. There is a first-order resource named `PodTemplate` with a full CRUD API: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#-strong-write-operations-podtemplate-v1-core-strong-

Its utility and usage is not documented anywhere.

**Comment by sftim** [comment]
I _think_ this is an error in the generated documentation. If you try to create a PodTemplate using `kubectl` / the API, you'll get an error, eg:
```
no matches for kind "PodTemplate" in version "core/v1"
```

My understanding:
PodTemplate is like Container; you can only create it as part of a resource that uses this object type. If you implemented the entire Kubernetes API in another language and generated docs from that other implementation, you might not have PodTemplate and Container show up at all in those generated docs.

**Comment by tengqm** [comment]
> Can I reference a named PodTemplate from a Deployment or Job spec?

No. It is always embedded.

> I know that there is a PodTemplate resource available, but none of the docs seem to mention it or say how it could be used.

According to the swagger API spec, PodTemplates can only be created from other top-level API resources. However, you can list or inspect them at `/api/v1/watch/namespaces/{namespace}/podtemplates/{name}`, `/api/v1/watch/namespaces/{namespace}/podtemplates` etc.
