### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by andreaskring** [kubernetes/website#17779]
**This is a Bug Report**

**Problem:**
Misleading explanation in the text compared to the command stated in the command line box. The test says to use the command `kubectl run`, but the command in the command line box uses `kubectl create deployment`

**Proposed Solution:**
Align the explanation in the text with the command to be executed.

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks! I must have missed this when updating the example. 

Alternatively, you can raise a PR at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

**Comment by sftim** [comment]
Think it's appropriate to flag this as a
/good-first-issue

Mention me (@sftim) if you are looking at this and are not sure where to start.

**Comment by amalts** [comment]
PR katacoda-scenarios/kubernetes-bootcamp-scenarios#16 will fix this.

**Comment by BenHall** [comment]
@amalts Sorry for the delay, I didn't see the notification until now. This has been merged.

**Comment by amalts** [comment]
Thanks @BenHall. 
This can be closed @andreaskring
