### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by arnav300** [kubernetes/website#17786]
**This is a Bug Report**

**Problem:**

As soon as i run the kubectl apply -k ./ get below error :
"error converting YAML to JSON: yaml: line 23: mapping values are not allowed in this context"
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@arnav300 Can you please elaborate what is the issue?

**Comment by RA489** [comment]
triage/needs-information

**Comment by tengqm** [comment]
Looks like the issue has been resolved. Feel free to reopen if not.
/close
