### ISSUE TITLE
Translate concepts/storage/volumes into Japanese

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#17784]
**This is a Feature Request**

**What would you like to be added**
Translate concepts/storage/volumes into Japanese

**Why is this needed**
This document is not translated in Japanese.

**Comments**

/language ja
/assign

**Comment by oke-py** [comment]
2週間経ちましたが未着手です。
アドベントカレンダー落ち着いたらやるつもりです。

**Comment by inductor** [comment]
@oke-py どーしましょ

**Comment by oke-py** [comment]
@inductor 年末年始に着手したものの分量が多くてあまり進んでいません。
（まとまった時間がとれそうなら再度トライしますが）いったんごめんなさいさせてください。

/unassign
どなたか着手いただけるなら歓迎です！

**Comment by af12066** [comment]
たしかに分量が多いですね。。レビューも大変になりそうな予感がします
部分的に（ある程度分割して個別にtranslateしていく感じ）でよければやってみようと思いますがいかがでしょうか？

**Comment by oke-py** [comment]
@af12066 ありがとうございます！よろしくお願いいたします。

**Comment by af12066** [comment]
いま着手中のが完了次第、こちらを着手してcopyして区切りの良いところまでtranslateしようと思います。
