### ISSUE TITLE
Repo has a branch protection policy, but protect: false

### ISSUE THREAD

**Issue by michelle192837** [kubernetes/website#17798]
jsonPayload: {
  component: "image"   
  controller: "sync"   
  file: "prow/config/branch_protection.go:346"   
  func: "k8s.io/test-infra/prow/config.(*Config).BranchProtectionWarnings"   
  level: "warning"   
  msg: "The following repos define a policy, but have protect: false: kubernetes/website"   
 }

Probably want to double-check the current branch protection settings.

**Comment by RA489** [comment]
@michelle192837 can you please provide bit more detail about this issue?

**Comment by michelle192837** [comment]
In https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L238, kubernetes/website has branch protection enabled for particular branches, but not overall. I think in this case it's not an urgent error, but it may be useful to enable branch protection in general. If not, feel free to close this and I'll ignore the warning in our logs going forward.

**Comment by sftim** [comment]
That makes sense
/remove-triage needs-information
/priority important-longterm

**Comment by sftim** [comment]
I'm going to make this instantly frozen too, so it doesn't get overlooked
/lifecycle frozen

**Comment by sftim** [comment]
We use branches for localizations and I think branch protection might not be helpful there.

We should confirm what the right answer is.

**Comment by sftim** [comment]
I think we fixed this in https://github.com/kubernetes/test-infra/pull/28789

/close
Please reopen if I was wrong.
