### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by thestupendous** [kubernetes/website#17837]
regarding the interface of the page (html, css etc.)
when some text is selected on the page, including some portion of the text that is inside the command box (in which the command to download and install minikube is given). After the text selection, when I try to scroll horizontally using the scroller provided, it won't scroll, instead, the selected text would move along the pointer, as if I was dragging the selected text.

**Comment by tengqm** [comment]
Cannot reproduce. Looks like a browser issue. Feel free to reopen.
