### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/safely-drain-node/

### ISSUE THREAD

**Issue by nekrkris** [kubernetes/website#17846]
This is a Bug Report

Problem:
Nowhere in the whole document the node status is mentioned as "Ready,SchedulingDisabled". 

Proposed Solution:
Update both https://kubernetes.io/docs/concepts/architecture/nodes/#manual-node-administration and k8s.io/docs/tasks/administer-cluster/safely-drain-node/ to describe correct node status

Page to Update:
https://kubernetes.io/docs/concepts/architecture/nodes/#manual-node-administration
k8s.io/docs/tasks/administer-cluster/safely-drain-node/ to describe correct node status

**Comment by sftim** [comment]
I think you're suggesting, @nekrkris, to add an explanation about how to check whether a Node has started draining. Have I got that right?

**Comment by nekrkris** [comment]
Yes and also the word "SchedulingDisabled" is missing

**Comment by sftim** [comment]
Ah! Maybe https://kubernetes.io/docs/concepts/architecture/nodes/#condition should be a full list of built-in Node conditions?

**Comment by nekrkris** [comment]
Yes and also the page referred should show the transition in state
