### ISSUE TITLE
improve documentation around headlessService and also Statefulsets

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes/website#17842]
**This is a Bug Report**

**Problem:**
- [ ] Add documentation for [**headless-services**](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) specifying that exposing ports is only needed if another service discovery mechanism is used, otherwise dns will forward directly to whatever container port.
- [ ] Clarify that a StatefulSet is allowed without a service [k/k issue here](https://github.com/kubernetes/kubernetes/issues/69608)

Right now, it says [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#statefulset-v1-apps) "serviceName is the name of the service that governs this StatefulSet. This service must exist before the StatefulSet, and is responsible for the network identity of the set. Pods get DNS/hostnames that follow the pattern: pod-specific-string.serviceName.default.svc.cluster.local where "pod-specific-string" is managed by the StatefulSet controller."

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by sftim** [comment]
Seems like a valid issue

/priority backlog

**Comment by kfox1111** [comment]
error: error validating "test.yaml": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec; if you choose to ignore these errors, turn validation off with --validate=false

Looks like StatefulSet without a service is no longer valid. :(

**Comment by sftim** [comment]
A similar issue: #24146
