### ISSUE TITLE
Issue with k8s.io/docs/tasks/tls/managing-tls-in-a-cluster/

### ISSUE THREAD

**Issue by chuck-confluent** [kubernetes/website#17848]
**This is a Bug Report**

**Problem:**

The information presented [here](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators) is vague.

**Proposed Solution:**

Flesh out an example that illustrates what is described.

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@chuck-confluent can you please clarify what is wrong here you faced?

**Comment by chuck-confluent** [comment]
The text says:

> This tutorial assumes that a signer is setup to serve the certificates API. The Kubernetes controller manager provides a default implementation of a signer. To enable it, pass the --cluster-signing-cert-file and --cluster-signing-key-file parameters to the controller manager with paths to your Certificate Authority’s keypair.

This is a bit vague and unfriendly to learners. A quick, illustrative example of what this note describes would be better than the description alone. This example is like vaguely describing how to solve an equation rather than actually solving the equation. E.g. "Integrating both sides reveals that there are infinitely many solutions." Integrating with respect to what? Are there countably many solutions? What do the solutions look like? Why not actually solve the equation and describe what's going on precisely?
