### ISSUE TITLE
Bug: Broken Links at k8s.io/docs/setup/

### ISSUE THREAD

**Issue by daniel-wtd** [kubernetes/website#17859]
The overview table presents some links, which are broken and do not lead anywhere:

- https://kubernetes.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/
- https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/

Furthermore, in the overview, there is still a section "Bare Metal" which cannot be found in the current document version (Kubernetes 1.16).

It seems like some content was removed over time and the overview page does not reflect the current status. Furthermore, a section "Best Practice" with one or 2 reference setups for cloud providers or on premise setups will be a very nice addition.

**Comment by Vageesha17** [comment]
fixing the broken link issue
