### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/certificates/

### ISSUE THREAD

**Issue by vprasady266** [kubernetes/website#17864]
How do we replace existing ssl certificates while the cluster is running? For example we need to include a new SAN name to the api server, how do we replace the certificate. Creating a new certificate using openssl and replacing the existing apiserver.crt doesn't make kubernetes pickup the new certificate. Worker nodes don't seem to recognize the new certificate.

**Comment by savitharaghunathan** [comment]
@vprasady266, did you replace the certs in both master and worker nodes?

**Comment by vprasady266** [comment]
I installed it only in the master under /etc/kubemaster/pki directory. I think the container for apiserver needs to pick this up and it is not happening. I was wondering there needs to be a procedure to update these SSL certificates for the different components in the cluster. I am not able to find the right documentation.

**Comment by savitharaghunathan** [comment]
Is there any error after running the following commands to update new certs?-  https://kubernetes.io/docs/concepts/cluster-administration/certificates/#distributing-self-signed-ca-certificate ?

**Comment by abhiTamrakar** [comment]
@vprasady266 if you CA is intact and in the same directory, you can use ```kubeadm alpha renew certs <cert name>``` to renew your certs, just that you might need to run it on all nodes those have that particular certificate as long as kubeadm alpha renew supports it.

**Comment by neolit123** [comment]
> How do we replace existing ssl certificates while the cluster is running? For example we need to include a new SAN name to the api server, how do we replace the certificate.

kubeadm supports certificate renewal as @abhiTamrakar pointed out above:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal

also you can specify extra SANs using kubeadm's configuration file:
https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#APIServer

> Creating a new certificate using openssl and replacing the existing apiserver.crt doesn't make kubernetes pickup the new certificate. Worker nodes don't seem to recognize the new certificate.

this could happen if your are not using the same CA.
manually renewing the certificates is supported and documented here:
https://kubernetes.io/docs/concepts/cluster-administration/certificates/#openssl

/triage support

i'm going to close this ticket as solutions were provided.
