### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/website#17862]
**Problem:**
The documentation doesn't not provide any information about installing/initializing the `kube-apiserver`.
Also, there are no usage-examples.

**Proposed Solution:**
Please add installation-info and examples.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

Kubernetes Version: 1.16

**Comment by tengqm** [comment]
The setup procedure is documented [here](https://kubernetes.io/docs/setup/). We are not repeating the content in the reference section.

**Comment by LSmyrnaios** [comment]
@tengqm I don't see any instructions for the `kube-apiserver` in the link you provided.
Also, please check this issue [(#85608)](https://github.com/kubernetes/kubernetes/issues/85608) to get a better understanding of the problem I am dealing with.
