### ISSUE TITLE
Master joining to HA cluster requires RBAC to access cluster-info config-map

### ISSUE THREAD

**Issue by fg78nc** [kubernetes/website#17869]
Environment : Ubuntu 18.04 (GKE)
Docker : 18.06.2-ce
Kubernetes (kubeadm, kubelet, kubectl) : 1.16.3

Going through : https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

Trying to join second(third..) master node with : 
```
kubeadm join --token ... --discovery-token-ca-cert-hash ... --control-plane-certificate-key ... 
```

and node is stuck with the pre-flight check. Increased verbosity (--v 2) and : 

```
[preflight] Running pre-flight checks
I1129 03:11:16.998706    8271 preflight.go:90] [preflight] Running general checks
...
I1129 03:11:17.421283    8271 join.go:433] [preflight] Discovering cluster-info
I1129 03:11:17.421394    8271 token.go:199] [discovery] Trying to connect to API Server "34.74.158.255:6443"
I1129 03:11:17.422000    8271 token.go:74] [discovery] Created cluster-info discovery client, requesting info from "https://34.74.158.255:6443"
I1129 03:11:17.422424    8271 token.go:82] [discovery] Failed to request cluster info, will try again: [Get https://34.74.158.255:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 34.74.158.255:6443: connect: connection refused]
I1129 03:11:22.423325    8271 token.go:82] [discovery] Failed to request cluster info, will try again: [Get https://34.74.158.255:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 34.74.158.255:6443: connect: connection refused]
```

Trying to troubleshoot and accessing manually  

```
https://34.74.158.255:6443/api/v1/namespaces/kube-public/configmaps/cluster-info
```

Response:

```
configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public
```

Was able to join cluster as a second master only after creating respective role and rolebinding to allow node to fetch "cluster-info" configmap.

```
kubectl create role sysano --resource configmaps --namespace kube-public --verb get,list,watch
kubectl create rolebinding sarb --user system:anonymous --namespace kube-public --role sysano
```

I assume another way to resolve this would be to allow anonymous access to kube-public namespace during kubeadm bootstrap by passing flag/configfile.

Problem is that official documentation does not mention this step.

**Comment by neolit123** [comment]
> I assume another way to resolve this would be to allow anonymous access to kube-public namespace during kubeadm bootstrap by passing flag/configfile

the RBAC for accessing the cluster-info ConfigMap is created by kubeadm init and yes, ConfigMaps in kube-public still require role bindings.

if this RBAC is missing you might have skipped the bootstrap-token phase of kubeadm init?
or maybe something deleted the RBAC?

in any case this is required.

> Problem is that official documentation does not mention this step.

this is an implementation detail that most users don't need to know about.
there are some outdated docs here:
https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.10.md#discovery-cluster-info

/close

if you are still having issues please re-open this in the kubernetes/kubeadm repository.
