### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by Mazorius** [kubernetes/website#17874]
**This is a Bug Report**

**Problem:**

In the interactive description the `run` command is mentioned but in the code block `create` is used.

**Proposed Solution:**

Think run should be replaced by the new create command.

**Page to Update:**

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by lojies** [comment]
This seems like the same as #17779.

**Comment by Mazorius** [comment]
Closed due to dublicates: #17779
