### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by 99887710** [kubernetes/website#17912]
**This is a Bug Report**

**Problem:**
The connection to the server localhost:8080 was refused - did you specify the right host or port?
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@99887710 what is the exact command line executed when you got this error?
