### ISSUE TITLE
kubectl installation instructions for macOS are incomplete

### ISSUE THREAD

**Issue by hansifer** [kubernetes/website#17913]
**Problem:**

Installation instructions here are incomplete:
https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-with-curl-on-macos

**Proposed Solution:**

see: https://github.com/kubernetes/kubernetes/issues/85816#issuecomment-560507373

**Page to Update:**

https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by RA489** [comment]
@hansifer Can you please elaborate what issue you got while installation to debug?

**Comment by hansifer** [comment]
> @hansifer Can you please elaborate what issue you got while installation to debug?

The issue I linked tells the whole story: https://github.com/kubernetes/kubernetes/issues/85816#issuecomment-560507373
