### ISSUE TITLE
securityContext.readOnlyRootFilesystem parameter isn't documented

### ISSUE THREAD

**Issue by php-coder** [kubernetes/website#17927]
**This is a Bug Report**
/sig auth

**Problem:**
I found that the `securityConext.readOnlyRootFilesystem` parameter isn't documented. It's mentioned a couple of times on the site in a context of PSP but not as a container's parameter.

**Proposed Solution:**
The page describing `readOnlyRootFilesystem` can mention that it exists and explain what it does and why it's actually a good idea to use it when possible.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by php-coder** [comment]
The example of description: https://kubesec.io/basics/containers-securitycontext-readonlyrootfilesystem-true/

**Comment by JayBeale** [comment]
I've submitted up a pull request to add read-only root filesystem to the list, clarify that the list on this page isn't comprehensive, and direct the reader to the API documentation for the more comprehensive list.
