### ISSUE TITLE
Improve the secret documentation

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#17933]
**This is a Feature Request**

**What would you like to be added**
More detailed documentation about Secret, in addition to the current lengthy Secret concept.

**Why is this needed**
We have many secrets about Secret which should be documented. For example, the securet type can be one of:

- `Opaque`
- `kubernetes.io/service-account-token`
- `kubernetes.io/dockercfg`
- `kubernetes.io/dockerconfigjson`
- `kubernetes.io/basic-auth`
- `kubernetes.io/ssh-auth`
- `kubernetes.io/tls`
- `bootstrap.kubernetes.io/token`

Some secret types needs special annotation or data keys. For example, for service account tokens, the following two annotations are required:

- `kubernetes.io/service-account.name`
- `kubernetes.io/service-account.id`

AND, the following key is required in the data property:

- `token`

**Comments**
In addition to the new contents to be added, we should consider moving some of the task-alike content out of the concept introduction at https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by vishakhanihore** [comment]
@sftim Can you please point me where can I read more about `secret`, Also which could help in add & improving the following?
Thanks

**Comment by tengqm** [comment]
This information is in the upstream source code. There is no convenient way for dumping them as swagger/openapi specs which are used for generating the API reference documentation. I would even suspect there could be one in future given the complexity of the semantics and nesting of struct definitions in Go lang.
You have to read the source code to understand the many constraints for resources like this. For the `Secret` resource type, the validation logic is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L4922

**Comment by tomoe** [comment]
+1
Especially, 
- is the token inside a secret periodically roated?
- Expiration of `ca.crt` seems to be set to 5 years. Is it going to be renewed automatically, or do you have to renew manually (and how)? What's the impact to already running workloads that hit the expiration?

**Comment by mark-jordanovic-lewis** [comment]
+1
Additionally:
- Document that secrets whose keys are removed from secrets files remain in the deployed secrets as empty strings, meaning the secrets resource must be deleted to remove that key and rebuilt on next deploy.

**Comment by sftim** [comment]
Immutable Secrets are also relevant (https://blog.alcide.io/kubernetes-1.18-introduces-immutable-configmaps-and-secretes has some details)

**Comment by tengqm** [comment]
Given the mentioned gap from the issue description and the various comments received, I'd like to propose a freeze of lifecycle for this issue.
/lifecycle frozen

**Comment by tengqm** [comment]
Put this on my TODO list.
/assign
