### ISSUE TITLE
Improve the LimitRange docs.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#17951]
**This is a Feature Request**
The LimitRange resource documentation should be revised.

**What would you like to be added**

- The current concept page (https://kubernetes.io/docs/concepts/policy/limit-range/) contains too many examples that can be refactored into tasks.
- The design documentation is outdated (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-management/admission_control_limit_range.md)
- The API docs for limit range item (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#limitrangeitem-v1-core) is somehow useless due to missing content from the swagger spec.

**Why is this needed**

As a user, I want to know what values I can use for `type`. What keys can be set for a `Pod`, or `Container` type. This kind of knowledge, currently, can be obtained only by reading the source code (Source readability is another topic). So ... I don't think anyone can get a comprehensive understanding about the `LimitRange` resource.

For example, the resource name constraint is not documented. If the `type` is set to `Pod` or `Container`, we can only use `cpu`, `memory` or `ephemeral-storage` or hugepage resources (prefixed with `hugepages-`) as resources. Resource name prefixed with `kubernetes.io/` is okay because it is treated as "native resource'. If the resource name is not prefixed with `kubernetes.io/` then the following criteria have to be met:

- the resource name doesn't have `requests.` prefix;
- the resource name can form a qualified name after prefixing with `requests.`.

**Comments**

**Comment by sftim** [comment]
PR #18961 helped a bit
/remove-lifecycle stale

**Comment by sftim** [comment]
BTW, which is the owning SIG for the LimitRange API?

**Comment by sftim** [comment]
I think this is done (well, done enough). @tengqm do you agree?
