### ISSUE TITLE
Add documentation for qualified name

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#17969]
**This is a Feature Request**

**What would you like to be added**
Kubernetes has an internal definition/consensus of what 'qualified name' means. For example, when specifying a label for a resource, the label name must be a 'qualified name'. There are code to validate these names when a new resource definition is posted to the API server. However, I found no definition of this when greping the website repo.

**Why is this needed**
We may want to add a concept of qualified name and a glossary entry for it. We can then refer to the glossary and concept page when describing the input requirements for a resource, when appropriate.

**Comments**
In addition to 'qualified name', there is 'fully qualified name' which may need formal docs as well.

**Comment by tengqm** [comment]
The corresponding upstream code can be found at https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L42

**Comment by sftim** [comment]
/remove-lifecycle stale
@tengqm is there any more to do?

**Comment by tengqm** [comment]
@sftim Thanks for asking. I think we can close this one after the patch (5) is in.

**Comment by tengqm** [comment]
This is done.
/close
