### ISSUE TITLE
Warn about external tool risk for base64 encoding a Secret

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#17984]
**This is a security-related issue**

**Problem:**
[Distribute Credentials Securely Using Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/) suggests using a web tool for encoding a Secret.
Although I have no reason to believe that the tool being recommended is a risk, I would not use a web tool to encode important secrets. So far as I know, there's no connection between the CNCF and the people who run that encoding service.

**Proposed Solution:**
In my view, this deserves calling out with a _caution_ [shortcode](https://kubernetes.io/docs/contribute/style/style-guide/#caution) that mentions using a local tool, trusted by your OS, as an alternative.

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/ 

/priority important-longterm

and, I think:
/sig usability
/good-first-issue

**Comment by vishakhanihore** [comment]
@sftim I would be handling this. /assign

**Comment by sftim** [comment]
Thanks @vishakhanihore !
