### ISSUE TITLE
Highlight deprecated options in generated reference docs

### ISSUE THREAD

**Issue by reveliotis** [kubernetes/website#17981]
DEPRECATED settings could be highlighted using a different color (e.g. orange) to make the review of long lists of settings much easier.

**Comment by sftim** [comment]
Thanks for the suggestion!

/kind feature
/priority backlog

**Comment by sftim** [comment]
As a first step for this, the code that generates HTML from the source code should change to add extra `class` information to the relevant table rows and / or cells, then add `<span>` elements that wrap the word DEPRECATED and the text that follows.

If anyone is picking this up, also consider logging related issue(s) about adding extra styling for other aspects, eg alpha & beta features.

**Comment by sftim** [comment]
/retitle Highlight deprecated options in generated reference docs

**Comment by sftim** [comment]
For the tooling, see https://github.com/kubernetes-sigs/reference-docs#kubernetes-reference-docs

**Comment by tengqm** [comment]
Closing this as a mission impossible.

The reference is generated using the raw swagger JSON from the upstream (kubernetes/kubernetes) repository. The swagger spec was generated from the source code comments. The implication , if there are things we are unhappy with, we have to change the source code. We have to persuade all SIGs to make sure that "DEPRECATED" or "Alpha" or "Beta" API versions or fields should be somehow highlighted. For example, when we say a field is deprecated, always use "DEPRECATED". Do NOT say "this will be deprecated", or "this field was deprecated in version 1.xx". None of these is accurate. The reference generator is not smart enough to figure out what these comments means. Similarly, the "Alpha" stage should be highlighted by spelling "Alpha", not "alpha". The generator is capable of scanning and highlighting these fields only when the syntax in the comments are consistent and accurate.

As a side note, if you are really into an accurate and detailed API reference, you may want to try out `docker run -p 8000:8000 tengqm/kab:latest`, and then point your browser to http://localhost:8000. The API specs in that tool were manually polished for all these kinds of inaccuracies.

/close

**Comment by sftim** [comment]
Just one tweak
/reopen
