### ISSUE TITLE
Issue with k8s.io/docs/contribute/

### ISSUE THREAD

**Issue by deepakkhetwal** [kubernetes/website#17989]
**This is a Bug Report**

**Problem:**
DNS name or IP name we had to hard code to communicate with other micro service. what's the alternative you have?
**Proposed Solution:**
Should be stored in the form of registry
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @deepakkhetwal 

I'm not sure I understand the issue you're reporting. Can you explain more?

If you wanted to learn about how Kubernetes lets you discover its services, look at [Discovering Services](https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services), [Publishing Services](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types), and [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).

/triage needs-information

**Comment by deepakkhetwal** [comment]
I have requirement. I have to call one http micro service, products http://products/v1 from another micro service catalog, to call products micro service, If I use kubernetes dns naming, I am assuming, I would have to hardcode http://products/V1 with in catalog micro service. Is there a better way like having a registry of these urls at common place?
