### ISSUE TITLE
Navigation bar dropdown Contents are hidden with Safari browser

### ISSUE THREAD

**Issue by vishakhanihore** [kubernetes/website#18003]
**This is a Bug Report**

**Problem:**

The Navigation Bar has several options that contain some dropdowns like version and details about those dropdowns are hidden underway.

**Proposed Solution:**

Make the dropdown not bounded by the Nav-Bar Container

**Screenshot**
<img width="1337" alt="Screenshot 2019-12-09 at 5 04 51 AM" src="https://user-images.githubusercontent.com/54327666/70398461-c9428e00-1a41-11ea-8574-2f2a06bcad51.png">

**Comment by vishakhanihore** [comment]
@parispittman @bobbytables Please provide labels.

**Comment by bobbytables** [comment]
Wrong @mrbobbytables I believe

**Comment by vishakhanihore** [comment]
> Wrong @mrbobbytables I believe

Updated, Sorry for this ping!

**Comment by mrbobbytables** [comment]
@vishakhanihore can you provide a bit more info? like which page / browser you're using?
It's working for me under chrome/osx on several pages
<img width="1400" alt="Screen Shot 2019-12-08 at 7 10 02 PM" src="https://user-images.githubusercontent.com/6500863/70399015-9b802980-19ee-11ea-93a7-8c2cf290f640.png">

**Comment by vishakhanihore** [comment]
I was on the index page.

**Comment by vishakhanihore** [comment]
Also I was using Safari/MacOs-Catalina

**Comment by mrbobbytables** [comment]
It looks to be a Safari specific bug, both chrome and firefox render it correctly.
/kind bug

**Comment by vishakhanihore** [comment]
Is it ok for me to look into `bugs label` too?

**Comment by mrbobbytables** [comment]
Yup. It's used as a triaging tool to help sort issues :)

**Comment by sftim** [comment]
/retitle Navigation bar dropdown Contents are hidden with Safari browser

/priority backlog
(I think)

**Comment by crhntr** [comment]
/remove-lifecycle stale

I am still getting a similar issue.
- Using Safari version 13.1

**Comment by tengqm** [comment]
/remove-lifecycle rotten

afaict, this issue is not resolved yet.
