### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by oliversalzburg** [kubernetes/website#18012]
**This is a Bug Report**

**Problem:**
The page states "Swap disabled. You MUST disable swap in order for the kubelet to work properly."

**Proposed Solution:**
Explain why swap **MUST** be disabled.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by neolit123** [comment]
hi, this is something that should be expanded in detail in the kubelet documentation and not the kubeadm docs (kubeadm/install-kubeadm/), feel free to send PRs if you'd like.

links:
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
https://discuss.kubernetes.io/t/swap-off-why-is-it-necessary/6879

/sig node
/help wanted

**Comment by oliversalzburg** [comment]
Gonna close this right away. Appears pointless
