### ISSUE TITLE
MutatingWebhookConfiguration for webhook implementation.

### ISSUE THREAD

**Issue by chainhead** [kubernetes/website#18022]
**This is a Feature Request**

**What would you like to be added**
The `MutatingWebhookConfiguration` for the webhook server (https://github.com/kubernetes/kubernetes/blob/v1.13.0/test/images/webhook/main.go) referred to here - https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#deploy-the-admission-webhook-service

**Why is this needed**
The webhook server goes hand-in-hand with the configuration. For example, how are we communicating to `kube-apiserver` the paths described in the `main` function?

**Comments**
None.

**Comment by sftim** [comment]
@chainhead, can you explain this issue? I'm not sure what feature you'd like added.

/triage needs-information
