### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by iamtodor** [kubernetes/website#18024]
**This is a Bug Report**

I've got some warning while starting minikube with google cloud's kubectl. To be honest, I didn't noticed it's a warning cause of ⚠️sign, I thought it doesn't start.

**Problem:**
```
minikube start
>>>😄  minikube v1.5.2 on Darwin 10.14.6
>>>💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
>>>🏃  Using the running hyperkit "minikube" VM ...
>>>⌛  Waiting for the host to be provisioned ...
>>>🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
>>>🔄  Relaunching Kubernetes using kubeadm ...
>>>⌛  Waiting for: apiserver
>>>🏄  Done! kubectl is now configured to use "minikube"
>>>⚠️  /Users/iamtodor/Downloads/google-cloud-sdk/bin/kubectl is version 1.13.11-dispatcher, and is incompatible with Kubernetes 1.16.2. You will need to update /Users/iamtodor/Downloads/google-cloud-sdk/bin/kubectl or use 'minikube kubectl' to connect with this cluster

gcloud components update
>>>All components are up to date.
```

**Proposed Solution:**
Add implicit warning with a word message; realize how to prevent to get this warning.
**Page to Update:**
https://kubernetes.io/docs/setup/learning-environment/minikube/

Google cloud information:
```
gcloud --version
>>>Google Cloud SDK 272.0.0
>>>bq 2.0.50
>>>core 2019.11.16
>>>gsutil 4.46
>>>kubectl 2019.11.04
```

Kubectl information:
```
kubectl version
>>>Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
>>>Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
```
kubectl cluster-info
>>>Kubernetes master is running at https://192.168.64.2:8443
>>>KubeDNS is running at https://192.168.64.2:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

>>>To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```
minikube version and hash commit
```
minikube version
>>>minikube version: v1.5.2
>>>commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad
```

**Comment by neolit123** [comment]
hi

on a quick look:
> >>>Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
>>>Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

this is not good because your server and client versions have a big difference (skew). they should be one MINOR apart, at most. or better - the client and server version matching.

try downloading a different version of kubectl.
/close
/triage support

**Comment by iamtodor** [comment]
@neolit123 From my point of view, it misleads. It tells you to update `You will need to update /Users/iamtodor/Downloads/google-cloud-sdk/bin/kubectl `, when I try to update I see I have the latest version

**Comment by neolit123** [comment]
you should update your kubectl binary and then type `kubectl version` to make sure the update worked.
cc @tstromberg
