### ISSUE TITLE
Broken link on https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18053]
**This is a Bug Report**

**Problem:** https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/ hyperlinks to https://kubernetes.io/docs/tasks/administer-cluster/enabling-endpoint-slices/ but there is no such page.

**Proposed Solution:**
~Add the task page based on https://github.com/kubernetes/website/pull/17480~
Remove the broken link

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/

/priority important-soon
/kind cleanup
/language en

**Comment by kbhawkey** [comment]
@sftim , Is this issue safe to close? For reference, see
https://github.com/kubernetes/website/pull/18093 .

**Comment by sftim** [comment]
Happy this is done
/close
