### ISSUE TITLE
--show-hidden-metrics-for-version flag missing from documentation

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18052]
**This is a Bug Report**

**Problem:**
@RainbowMango [reported](https://github.com/kubernetes/website/pull/17471#issuecomment-563605423):
> v1.17 has been released and seems no update about the new-added flag.
> https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Proposed Solution:**
Identify issue with generated content.
Amend generated content with update pull request?

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Additional Information**:
My guess is that other new features are also missing from the generated documentation. I saw hints of that when reviewing pull requests for the v1.17 release.

/priority important-soon

**Comment by lojies** [comment]
@sftim, can this page keep this same as `kube-apiserver -h`.I think it's hard to maintain this by the current form.Is there any suggertion for this?

**Comment by sftim** [comment]
@lojies I'm not sure what you're saying here.

If you're saying that the current process for incorporating generated reference documentation is a hard to use, I agree.

**Comment by tengqm** [comment]
The reference docs are not generated correctly. I suspect that the generator didn't update the MINOR_VERSION in the Makefile before running `make comp`.

**Comment by kbhawkey** [comment]
Currently, the Makefile requires updating as part of the generation process. This has always been the case and is probably documented.
One way to address that issue would be to update the Makefile after the `getting` the reference repo. Could simply add a sed call to the `generate-command` and modify the Makefile.

**Comment by RainbowMango** [comment]
The flag is on board now.
