### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by chenxuc** [kubernetes/website#18055]
**This is a Bug Report**

**Problem:**
Some command ouputs are out-of-date (from an old version minikube). We need to update the command outputs with current version minikube (v1.5.2) to avoid confusion.

1. The output for "minikube addons list" is outdated. e.g. "coredns" is not a default addon in current version minikube.

2. The output for "kubectl get pod,svc -n kube-system" is incorrect.
"service/kubernetes-dashboard" is no longer in kube-system namespace. It's in its own namespace kubernetes-dashboard and should not be listed in this output.

**Proposed Solution:**
Update the command output example with current version minikube.
I can assign this issue to myself and update this page with my new minikube environment. 

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by sftim** [comment]
Thanks @chenxuc 
/kind cleanup

**Comment by chenxuc** [comment]
update is merged.
