### ISSUE TITLE
release 1.17, component tool build failure

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#18061]
**This is a Bug Report**

**Problem:**
Using the updated script (python3 update-imported-docs.py reference.yml) for the v1.17 release, the script fails to build the components (several issues).

**Proposed Solution:**
[x] Modify script config to update the reference Makefile, MINOR_VERSION.
[?] There appears to be a problem with the go version and building certain component dependencies. Still investigating.

**Page to Update:**
Still investigating.

v1.17

**Comment by kbhawkey** [comment]
With go version go1.13.5 linux/amd64

   ./vendor/github.com/go-bindata/go-bindata/go-bindata
src/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/envelope.go:31:2: use of vendored package not allowed
src/vendor/golang.org/x/crypto/ssh/kex.go:19:2: use of vendored package not allowed
src/vendor/golang.org/x/crypto/ssh/cipher.go:21:2: use of internal package vendor/golang.org/x/crypto/internal/chacha20 not allowed
src/vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go:38:2: use of internal package vendor/golang.org/x/crypto/internal/subtle not allowed
src/vendor/golang.org/x/crypto/ssh/cipher.go:22:2: use of vendored package not allowed
src/vendor/golang.org/x/net/http2/frame.go:17:2: use of vendored package not allowed
src/vendor/golang.org/x/net/http2/frame.go:18:2: use of vendored package not allowed
/usr/local/go/src/net/http/h2_bundle.go:50:2: use of vendored package not allowed
rm -rf /tmp/tmpohv8j7xt/src/github.com/kubernetes-sigs/reference-docs/gen-compdocs/build
mkdir -p gen-compdocs/build
go run gen-compdocs/main.go gen-compdocs/build kube-apiserver
../../../vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/envelope.go:31:2: use of vendored package not allowed
../../../vendor/golang.org/x/crypto/ssh/kex.go:19:2: use of vendored package not allowed
../../../vendor/golang.org/x/crypto/ssh/cipher.go:21:2: use of internal package vendor/golang.org/x/crypto/internal/chacha20 not allowed
../../../vendor/golang.org/x/crypto/nacl/secretbox/secretbox.go:38:2: use of internal package vendor/golang.org/x/crypto/internal/subtle not allowed
../../../vendor/golang.org/x/crypto/ssh/cipher.go:22:2: use of vendored package not allowed
../../../vendor/golang.org/x/net/http2/frame.go:17:2: use of vendored package not allowed
../../../vendor/golang.org/x/net/http2/frame.go:18:2: use of vendored package not allowed
../../../vendor/golang.org/x/net/http2/transport.go:36:2: use of vendored package not allowed
../../../vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:31:2: use of vendored package not allowed
../../../vendor/github.com/spf13/afero/util.go:29:2: use of vendored package not allowed
Makefile:46: recipe for target 'comp' failed
make: *** [comp] Error 1

**Comment by kbhawkey** [comment]
# k8s.io/kubernetes/cmd/kube-apiserver/app
../../../k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:427:70: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions
Makefile:46: recipe for target 'comp' failed

**Comment by tengqm** [comment]
Yes. I noticed this failure as well.

**Comment by hase1128** [comment]
I also notice same issue.

**Comment by kbhawkey** [comment]
Completed.
/close
