### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by douwilliam** [kubernetes/website#18068]
**This is a Bug Report**

> IP addresses in the ranges 172.17.0.0–172.17.0.255 and 172.17.2.0–172.17.255.255 (ie, all of 172.17.0.0/16 except 172.17.1.0/24)
I think this sample is not correct, should except sample be 172.17.1.0/8?
if except 172.17.1.0/24, the subnet will be 255.0.0.0, all 172.17.0.0/16 will be excepted 

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@douwilliam I think your network address calculations are off.
An exception `172.17.1.0/24` means the mask for the exception is 24 bits of `1` and then the rest is `0` ie `1111111111111111111100000000` or `255.255.255.0`

/triage support
