### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/

### ISSUE THREAD

**Issue by mikaelmendoza21** [kubernetes/website#18066]
**This is a Bug Report**

**Problem:** Documentation refers to _READY_ column on "Interactive Tutorial - Scaling Your App" module; however, no READY column appears on terminal after running `kubectl get deployments`

**Proposed Solution:** Update docs.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/

Kubernetes Version:
kubectl v1.11.0

**Comment by sftim** [comment]
```
$ kubectl get deployments
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
kubernetes-bootcamp   0/1     0            0           3s
```

I see a `READY` column, using the interactive tutorial and the cluster it provides. That's with a more recent version of Kubernetes; v1.11 is now out of official support. Maybe `kubectl` worked differently a few releases ago?

**Comment by mikaelmendoza21** [comment]
Ok, I retried the tutorial page and it now runs kubectl v1.15.2.
The `READY` column is there.
