### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dns-pod-service/

### ISSUE THREAD

**Issue by rockmenjack** [kubernetes/website#18074]
**This is a Bug Report**

**Problem:**
in real k8s cluster Pod resolved to ```foo.bar.my-namespace.svc.cluster-domain.local``` instead of 
```foo.bar.my-namespace.svc.cluster-domain.example```.
**Proposed Solution:**
Update document to ```foo.bar.my-namespace.svc.cluster-domain.local```
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
`foo.bar.my-namespace.svc.cluster-domain.example` is an example. If you have a real cluster, the domain for your cluster might be different.

I don't see that there's anything to fix @rockmenjack.
