### ISSUE TITLE
Explain “add-ons” in Hello Minikube

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18078]
**This is a suggestion**

**Idea:**
People reading Hello Minikube might not know what an add-on is. They can use the site search. TO be extra informative, the Hello Minikube page can signpost readers to find more information.

**Proposed Solution:**
Explain “add-ons” in Hello Minikube by either:
- add a hyperlink to https://kubernetes.io/docs/concepts/cluster-administration/addons/
- add a [glossary](https://kubernetes.io/docs/reference/glossary/) entry for add-on, and then use a [glossary shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) in the Hello Minikube page

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

/good-first-issue
/language en

**Comment by sftim** [comment]
If you're new to SIG Docs and would like advice on picking this up, reply to this comment with your question.
You can also ask via [Slack](https://kubernetes.slack.com/messages/C1J0BPD2M/) - get an invitation from https://slack.k8s.io/

**Comment by habibridho** [comment]
I'll try to pick this one.

/assign

**Comment by habibridho** [comment]
@sftim Hi, I'm adding new glossary for add-on and wonder the appropriate tag for it. I'm thinking to tag it as "Tool". What do you think?

**Comment by sftim** [comment]
I'm not sure @habibridho ! `tool` seems like a reasonable choice to me.
