### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/components/

### ISSUE THREAD

**Issue by noambenami** [kubernetes/website#18084]
This is  second page of the docs, but already talks about pods and services, which have not been explained yet.

This is probably the most common of all technical documentation failures: Discussing technical concepts that have not yet been explained.

And it's one of the most frustrating because as a reader, I cannot gronk the sputties without understanding what gronks or sputties mean.

**Comment by sftim** [comment]
A valid point @noambenami - thanks for pointing that out.
/priority important-longterm
/language en

**Comment by noambenami** [comment]
Thanks for the response @sftim - any update on this? Cheers!

**Comment by sftim** [comment]
It's still a valid issue. @noambenami there's an open pull request: #18089 
If you're willing to, you can provide feedback on that PR (anyone can review).

/remove-lifecycle stale

**Comment by noambenami** [comment]
Thanks @sftim ! Reviewed and added comment.

**Comment by tengqm** [comment]
/remove-lifecycle rotten
Looks like the PR addressing this is still being cooked.
