### ISSUE TITLE
Translate concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md in Korean

### ISSUE THREAD

**Issue by KimMJ** [kubernetes/website#18080]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md in Korean

**Why is this needed**
No translation with concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md in Korean

**Comments**

Page to Update:
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

**Comment by ysyukr** [comment]
안녕하세요.
@KimMJ 님께서 올려주신 이슈는 #17790 에 먼저 올라온걸로 확인이 되고 있습니다.
이에 다른 문서 선택을 요청드립니다.

**Comment by KimMJ** [comment]
@ysyukr 
넵. 제가 확인을 잘못했네요.
다른 문서 찾아보겠습니다!
