### ISSUE TITLE
Outdated release notes

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18116]
**This is a Bug Report**

**Problem:** The current [release notes](https://kubernetes.io/docs/setup/release/notes/) are for v1.16 but the latest release is v1.17

**Proposed Solution:** 
Update release notes

**Page to Update:**
https://kubernetes.io/docs/setup/release/notes/

**Additional Information:**
Similar to #11141

/kind bug
/priority important-soon

**Comment by saschagrunert** [comment]
This might have been missed, but it is officially part of the docs handbook:
https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/docs#release-day
