### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by conseque** [kubernetes/website#18119]
**This is a Bug Report**

**Problem:**
link 'Upgrading kubeadm cluster from 1.15 to 1.16'
leads to 'Upgrading kubeadm cluster from 1.16 to 1.17'

**Proposed Solution:**
working link

**Page to Update:**
https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by sftim** [comment]
Thanks for the report @conseque 
/priority important-longterm
/kind bug
/assign
/language en
