### ISSUE TITLE
SIG Docs co-chair transition: Bradamant3 and kbarnard10

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#18117]
## SIG Docs co-chair transition

In the [10 December 2019 SIG Docs weekly meeting](https://docs.google.com/document/d/1zg6By77SGg90EVUrhDIhopjZlSDg2jCebU-Ks9cYx0w/edit), @Bradamant3 announced that she is stepping down as SIG Docs co-chair and will become a chair emeritus.
 
@Bradamant3 nominated @kbarnard10 to replace her; @kbarnard10 accepted during the same meeting.

### Transition date

Without further input, lazy consensus is to transition on January 15, 2020.

## Procedures for changing co-chairs

SIG Docs follows the procedure for transitions in our [community charter](https://github.com/kubernetes/community/blob/master/sig-docs/charter.md): 

> This charter adheres to the conventions described in the Kubernetes Charter README and adheres to the Roles and Organization Management specified in sig-governance.

From [sig-governance](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#notes-on-roles):

> Within this section "member" refers to a member of a Chair, Tech Lead or Subproject Owner Role. (this different from a SIG or Organization Member).
> Members MAY decide to step down at anytime and propose a replacement. Use lazy consensus amongst other members with fallback on majority vote to accept proposal. The candidate SHOULD be supported by a majority of SIG Members or Subproject Contributors (as applicable).

### Lazy consensus

This issue proposes lazy consensus for @kbarnard10 to replace @Bradamant3 on 15 January 2020 as SIG Docs co-chair, giving time for feedback from SIG members.

For lazy consensus, this issue needs:

- [x] A statement from @Bradamant3 that she intends to step down as SIG Docs co-chair: by comment on this issue, in a weekly meeting, or in an email to kubernetes-sig-docs@googlegroups.com
- [x] A statement from @kbarnard10 accepting the nomination as SIG Docs co-chair: by comment on this issue, in a weekly meeting, or in an email to kubernetes-sig-docs@googlegroups.com
- [x] A vote from the current co-chairs (@Bradamant3, @jimangel, @zacharysarah) to confirm the nomination of @kbarnard10. 

When these two conditions are met, and without clear consensus on a different path, on 15 January 2020:

- [x] @Bradamant3 becomes a chair emeritus of SIG Docs
- [x] @kbarnard10 becomes a co-chair of SIG Docs

## Required changes

Co-chair transitions require some updates.

Repo | file | Complete?
---|---|---
k/community | [OWNERS_ALIASES](https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES) | ✔️ 
k/community | [sig-docs/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/README.md) | ✔️ 
k/community | [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md) | ✔️ 
k/community | [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1185-L1198) | ✔️ 
k/enhancements | [OWNERS_ALIASES](https://github.com/kubernetes/enhancements/blob/master/OWNERS_ALIASES#L40) | ✔️ 
k/org | [OWNERS_ALIASES](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES#L39) | ✔️ 
k/website | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L141) | ✔️ 
k/website | [SECURITY_CONTACTS](https://github.com/kubernetes/website/blob/master/SECURITY_CONTACTS) | ✔️ 

### From @zacharysarah:

@Bradamant3 joined Kubernetes SIG docs in June 2017. She understood the whole of SIG Docs almost immediately, and saw better how SIG Docs interrelated with everything else in the Kubernetes project. She translated her own personal understanding into deep technical knowledge and community understanding, built relationships, improved feature docs, and changed the world. She improved everything her leadership touched--notably kubeadm docs, the release notes, and every feature she worked on. SIG Docs benefited mightily from her keen insight and gregarious humor. 

Jennifer, thank you for two and a half years (and counting!) of excellence in SIG Docs. I'm so glad you said yes when I asked. You connected SIG Docs with the rest of the Kubernetes project and kept us aware of things we would otherwise have missed.

@kbarnard10, I'm excited for you to evolve your role. You've shown effective leadership in launching and managing the Kubernetes blog, and your Hugo knowledge makes you a valuable addition to the technical team. Thanks for stepping up!

/sig docs

**Comment by sftim** [comment]
A thank you from me as well, to both!

**Comment by kbhawkey** [comment]
Thanks, @Bradamant3 for your leadership!
Congrats, @kbarnard10!

**Comment by zacharysarah** [comment]
@Bradamant3 @kbarnard10 👋 In order for this PR to move forward, please comment with your assent.

**Comment by kbarnard10** [comment]
I accept the nomination for co-chair 🎉

A huge thank you to @Bradamant3 for all the leadership and, especially, mentorship that she's provided throughout my journey with SIG-Docs ❤️

**Comment by jrondeau-stripe** [comment]
And with regret because I'll miss you all, but knowing that @kbarnard10 is the right person now, when I am no longer in a position to help this amazing community, I'm commenting to say yes, let's move forward with the transition as I formally step down. Thanks to all of you for all you've taught me and shared with me ❤️

**Comment by sftim** [comment]
:wave:

**Comment by zacharysarah** [comment]
The vote to promote @Bradamant3 to chair emeritus and promote @kbarnard10 to co-chair passed in today's [SIG Docs weekly meeting](https://docs.google.com/document/d/1ddHwLK3kUMX1wVFIwlksjTk0MsqitBnWPe1LRa1Rx5A/edit#).

Thanks, @Bradamant3! Welcome, @kbarnard10! 🎉

**Comment by justaugustus** [comment]
Just dropping by to say this is a really beautifully written issue that we should probably formalize for Chair/TL transitions. :)
cc: @parispittman 

Thanks for your work, @Bradamant3!
And congrats, @kbarnard10!

**Comment by sftim** [comment]
Let's not autoclose this.
/remove-lifecycle stale

**Comment by zacharysarah** [comment]
@sftim Fair, and with no remaining tasks, it's time to close. 

/close
