### ISSUE TITLE
k8s.io/security short link is now redirecting to the Security page in Korean

### ISSUE THREAD

**Issue by IanColdwater** [kubernetes/website#18129]
**What happened**: The short link [https://k8s.io/security](https://k8s.io/security) is now redirecting to the Kubernetes Security and Disclosure Information page in Korean at [https://kubernetes.io/ko/docs/reference/issues-security/security/](https://kubernetes.io/ko/docs/reference/issues-security/security/) by default

**What you expected to happen**: It used to redirect to the page in English at [https://kubernetes.io/docs/reference/issues-security/security/](https://kubernetes.io/docs/reference/issues-security/security/)

**How to reproduce it (as minimally and precisely as possible)**: Click on [https://k8s.io/security](https://k8s.io/security)

**Anything else we need to know?**: I hadn't checked the link since August and I'm not sure how long it's been doing that.

**Environment**: It is doing this in Chrome, Firefox and Safari on a Mac.

**Comment by cblecker** [comment]
/sig docs

✨Magical Issue Migration to kubernetes/website✨

cc: @zacharysarah

**Comment by guineveresaenger** [comment]
Paging @gochist maybe?

/meow

**Comment by zacharysarah** [comment]
Verified on mobile.

@kubernetes/sig-docs-ko-owners 

/kind bug
/priority important-soon

**Comment by cblecker** [comment]
I think I know the cause: https://github.com/kubernetes/website/pull/18132

Looks like an alias was copied when the security disclosure process was translated. That alias is taking precedence over the /en/ one.
