### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/fine-parallel-processing-work-queue/

### ISSUE THREAD

**Issue by devopsdymyr** [kubernetes/website#18126]
**This is a Bug Report**

Once queue is completed then pod is still running.

**Problem:**
Looking for Parallel Jobs with a Work Queue : Parallelism: 8
tried to follow this reference doc: https://medium.com/@Alibaba_Cloud/kubernetes-batch-jobs-6d2d3d272a10

I have tried with  below yaml error.

error: error validating "myWorkqueue-Job.yaml": error validating data: [ValidationError(Job.spec): unknown field "restartPolicy" in io.k8s.api.batch.v1.JobSpec, ValidationError(Job.spec.template): unknown field "volumeMounts" in io.k8s.api.core.v1.PodTemplateSpec, ValidationError(Job.spec): unknown field "terminationGracePeriodSeconds" in io.k8s.api.batch.v1.JobSpec, ValidationError(Job.spec): unknown field "volumes" in io.k8s.api.batch.v1.JobSpec]; if you choose to ignore these errors, turn validation off with --validate=false

**Proposed Solution:**
Fine parallel processing using a work queue some real example usecase

**Page to Update:**
https://kubernetes.io/...

Kubernetes Version:
1.14.8-gke.17

**Comment by sftim** [comment]
@devopsdymyr I had a look at the code that the Job from https://k8s.io/docs/tasks/job/fine-parallel-processing-work-queue/ runs inside its Pods, and it looks correct to me.
Can you provide some diagnostics showing the issue?

/triage needs-information
/sig apps

**Comment by devopsdymyr** [comment]
That is working fine.

Can you guild me how to make this in production system.
Should i implement redis and slave?
there is not more issue on this document once job is send to redis give gives that details to worker and worker is doing that task.but once task completed still my pod is running 

if again i am passing some some task to queue which not taking from worker
