### ISSUE TITLE
Need doc on using ConfigMap updates

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#1817]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
I want to point a user at documentation about config map updates but I can't find any.

**Proposed Solution:**
Write a doc, and link from http://kubernetes.io/docs/user-guide/configmap/

**Page to Update:**
http://kubernetes.io/docs/user-guide/configmap/

**Comment by sftim** [comment]
/priority backlog
#16085 should have an nice high priority though

**Comment by sftim** [comment]
Documented in #21452 - see https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically 
/close


Issue #1911 remains relevant
