### ISSUE TITLE
Issue with k8s.io/id/docs/concepts/configuration/overview/ for Bahasa Indonesia

### ISSUE THREAD

**Issue by girikuncoro** [kubernetes/website#18174]
Some sentences remain in English, we have to translate and clean up the format on this page.
![image](https://user-images.githubusercontent.com/3192347/70959791-b702c880-20af-11ea-8fb7-7bd132ce0b0f.png)

Ref: https://kubernetes.io/id/docs/concepts/configuration/overview/ (select Bahasa Indonesia)

/language id

**Comment by irvifa** [comment]
Hi @girikuncoro do we still have this problem?

**Comment by girikuncoro** [comment]
Most likely yes, we can generate specific issue for this and keep the easy ones open for docs contributor workshops
