### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by sww** [kubernetes/website#18187]
**This is a Bug Report**

**Problem:**
The command for allowing pods to run on the control-plane node  (`kubectl taint nodes --all node-role.kubernetes.io/master-`) does not work for v1.17.

**Proposed Solution:**
The command `kubectl taint nodes --all node.kubernetes.io/not-ready:NoSchedule-` seems to  allow pods to be scheduled on the control-pane node.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation

**Kubernetes Version:**
v1.17

**Comment by neolit123** [comment]
> The command for allowing pods to run on the control-plane node (kubectl taint nodes --all node-role.kubernetes.io/master-) does not work for v1.17.

it should work. the "master" taint blocks scheduling on control-plane nodes.

> The command kubectl taint nodes --all node.kubernetes.io/not-ready:NoSchedule- seems to allow pods to be scheduled on the control-pane node.

is your control-plane node not-ready?

/priority awaiting-more-evidence

**Comment by sww** [comment]
I just tried the command on a new instance, and removing the taint does work. But when I try to create a deployment, the pod fails to schedule. Here's the describe output:

```
$ kubectl create deployment test --image=hello-world
deployment.apps/test created

$ kubectl describe deployment test
Name: test
Namespace: default
CreationTimestamp: Thu, 19 Dec 2019 04:38:58 0000
Labels: app: test
Annotations: deployment.kubernetes.io/revision: 1
Selector: app=test
Replicas: 1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType: RollingUpdate
MinReadySeconds: 0
RollingUpdateStrategy: 25% max unavailable, 25% max surge
Pod Template:
 Labels: app=test
 Containers:
 hello-world:
 Image: hello-world
 Port: <none>
 Host Port: <none>
 Environment: <none>
 Mounts: <none>
 Volumes: <none>
Conditions:
 Type Status Reason
 ---- ------ ------
 Available False MinimumReplicasUnavailable
 Progressing False ProgressDeadlineExceeded
OldReplicaSets: <none>
NewReplicaSet: test-75b9c9cd45 (1/1 replicas created)
Events:
 Type Reason Age From Message
 ---- ------ ---- ---- -------
 Normal ScalingReplicaSet 15m deployment-controller Scaled up replica set test-75b9c9cd45 to 1

$ kubectl describe pods test-75b9c9cd45-vn5dq
Name: test-75b9c9cd45-vn5dq
Namespace: default
Priority: 0
Node: <none>
Labels: app: test
 pod-template-hash=75b9c9cd45
Annotations: <none>
Status: Pending
IP:
IPs: <none>
Controlled By: ReplicaSet/test-75b9c9cd45
Containers:
 hello-world:
 Image: hello-world
 Port: <none>
 Host Port: <none>
 Environment: <none>
 Mounts:
 /var/run/secrets/kubernetes.io/serviceaccount from default-token-6mg2q (ro)
Conditions:
 Type Status
 PodScheduled False
Volumes:
 default-token-6mg2q:
 Type: Secret (a volume populated by a Secret)
 SecretName: default-token-6mg2q
 Optional: false
QoS Class: BestEffort
Node-Selectors: <none>
Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
 Type Reason Age From Message
 ---- ------ ---- ---- -------
 Warning FailedScheduling 50s (x30 over 43m) default-scheduler 0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
```
So it's a different issue than the command not working, but it seems like something changed in v1.17 that requires an extra step to allow scheduling on the control plane.

**Comment by neolit123** [comment]
> So it's a different issue than the command not working, but it seems like something changed in v1.17 that requires an extra step to allow scheduling on the control plane.

i don't think that's the case. if it was we should have catch this in our e2e test signal.

**Comment by neolit123** [comment]
/close
please reopen if needed.
