### ISSUE TITLE
Issue with k8s.io/docs/tasks/tls/certificate-rotation/

### ISSUE THREAD

**Issue by wu105** [kubernetes/website#18199]
**This is a Bug Report**

**Problem:**
We are running kubernetes v1.12.7 and kubelet runs with `--config=/var/lib/kubelet/config.yaml` ,and the config.yaml contains this line: `rotateCertificates: true`

We seems to  get a confirmation from kubelet that the certificate rotation is in effect by temporarily adding 
```
featureGates:
  RotateKubeletClientCertificate: false
```
to /var/lib/kubelet/config.yaml, restarting kubelet and seeing it logs `invalid configuration: RotateCertificates true requires feature gate RotateKubeletClientCertificate`

On the other hand we have `/var/lib/kubelet/pki/kubelet-client.crt` that expired on 2019-9-27, some 3 months ago,  The kubelet has not restarted since before that and seems working.  Is this certificate supposed to be updated by kubelet already?  
**Proposed Solution:**
The document should link the certificate files to the kubelet configuration options that would cause them to be automatically updated, and provide information that would answer the above question, and provide more timing, e.g., whether the certificates are updated 1 day before expiration or one week.  Documenting the log entries related to the certificates under management would help, so do diagnose steps, and the equivalent spelling of the same configuration options on kubelet command line and in the config.yaml file.

**Page to Update:**
https://kubernetes.io/docs/tasks/tls/certificate-rotation/

1.12 .7

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/tls/certificate-rotation/ is for Kubernetes v1.17
As v1.12 is out of support, documentation for that release is archived.

You can look at https://v1-13.docs.kubernetes.io/docs/tasks/tls/certificate-rotation/ or try the [Internet Archive](https://web.archive.org/web/*/https://v1-12.docs.kubernetes.io/docs/tasks/tls/certificate-rotation/)

/triage support

**Comment by wu105** [comment]
Thanks for the information.
  
Can we have the document explicitly marked as to which version it applies?

https://kubernetes.io/docs/tasks/tls/certificate-rotation/ includes this statement: "Kubernetes version 1.8.0 or later is required", which should be replaced with something like this: "This document applies to Kubernetes v1.17".  A link to the archived and newer versions would be also helpful.

**Comment by wu105** [comment]
Thanks for the information.

The document include the following statement: 'Kubernetes version 1.8.0 or later is required", which may be more informative to say: "Kubernetes version 1.8.0 or later supports certificate rotation.  This document applies to v1.17."  Adding links to archived or future versions would be helpful.

By the way, the "Internet Archive" link provided does not have the v1.12 archive.  The document probably should be versioned just like the source code instead of using external archiving.

**Comment by sftim** [comment]
If you're really keen to see the v1.12 documentation that _is_ possible: see https://github.com/kubernetes/website/tree/release-1.12

#12303 tracks the behavior for no-longer-supported releases. If you want different behavior @wu105 you can log a new issue and request that.


I reviewed the sentence:
>     Kubernetes version 1.8.0 or later is required

I feel this is an accurate if dated description of prerequisites.

**Comment by wu105** [comment]
"Kubernetes version 1.8.0 or later is required" implies that this document applies for all kubernetes or kubelet v1.8.0 and above, but in reality it is for v1.17 as indicated in your initial reply.  This information should be add to the document itself.  Reading docs of the wrong versions wastes every ones' time.  Identifying the versions of the docs should be part of the docs.

**Comment by sftim** [comment]
The current page shows it's for v1.17: 
![Version number in Kubernetes documentation](https://user-images.githubusercontent.com/22591623/71322115-b86f2f00-24bb-11ea-8b13-c1af581fd5bd.png). This identifies the version of Kubernetes that the documentation is for.

It does make sense to switch to using a feature-state shortcode to reveal which Kubernetes version is in use, except that in fact it's better to drop the prerequisite entirely as v1.13 is the oldest supported version. That change will help readers who don't notice the version in the top right and avoid the risk of confusion.
/kind cleanup
/priority backlog

**Comment by wu105** [comment]
I actually tried to use that version dropdown to get to one of the supported versions so that I would get to a "Certificate Rotation" page that would have v1.13 on the top.  I could not.  Therefore, as currently it stands, that version dropdown won't even work for older versions.

I think it would be instructive to take out the design document for this "https://kubernetes.io/docs" site and verify how it matches the implementation in terms of finding the desired versions of document.  If there is a way, that would be a very useful instruction to add before version navigation is improved.

By they way, we are using down stream kubernetes from Oracle, and as of today, v1.12 is the latest release.  Therefore, this "https://kubernetes.io/docs" may want to support a couple of more older versions.

**Comment by sftim** [comment]
Also see issue #18199
