### ISSUE TITLE
Update minikube and kubectl version 1.17 0r 1.16 - interactive cluster

### ISSUE THREAD

**Issue by samudralavamshi54** [kubernetes/website#18197]
**This is a Feature Request**

Update minikube to latest stable 1.5/1.6, kubectl version to 1.16 or 1.17  in interactive cluster 
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**What would you like to be added**
 minikube cluster upgrade and kubectl upgrade

**Why is this needed**
To keep up with the latest upgrades and user experience

**Comments**

/ sig-docs

**Comment by BenHall** [comment]
Thanks for the feedback. We're currently testing the release and will be live shortly.

**Comment by sftim** [comment]
Also see issue #19305

**Comment by BenHall** [comment]
To provide an update, all the environments are now running `v1.8.1`.

This can be closed.

**Comment by tengqm** [comment]
Thanks for the feedback, @BenHall 
/close
