### ISSUE TITLE
Incorrect version number in Limitations section

### ISSUE THREAD

**Issue by JPPintoDotCom** [kubernetes/website#18207]
**This is a Bug Report**

**Problem:**
Under the limitations section, it says: "In Kubernetes version 1.5" 

**Proposed Solution:**
Correct version number

**Page to Update:**
https://kubernetes.io/docs/setup/best-practices/node-conformance/

**Comment by sftim** [comment]
Is that incorrect, or simply dated?

/kind cleanup

**Comment by sftim** [comment]
Let's remove the Limitations section entirely unless there's evidence that it remains accurate.
/remove-lifecycle rotten
/help
/language en

**Comment by sftim** [comment]
BTW https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md#node-end-to-end-tests also documents Node end-to-end tests
