### ISSUE TITLE
Remove content/en/examples/admin/dns/busybox.yaml

### ISSUE THREAD

**Issue by aojea** [kubernetes/website#18202]
**This is a Feature Request**

**What would you like to be added**

Remove the busybox example because it was confusing users and have known issues with Kubernetes DNS

**Why is this needed**

This is no longer linked from the documentation since https://github.com/kubernetes/website/pull/18001

**Comments**

xref: https://github.com/kubernetes/website/pull/18001#pullrequestreview-333436862

**Comment by sftim** [comment]
I suggest removing `content/en/examples/admin/dns/busybox.yaml` after v1.18 is released (not necessarily immediately afterwards)
