### ISSUE TITLE
Add tool to check/clean white noise and check spell

### ISSUE THREAD

**Issue by daixiang0** [kubernetes/website#18210]
**This is a Feature Request**

**What would you like to be added**

A tool to check/clean white noise and check spell.

**Why is this needed**

For docs, correct spell is basic. For most case, white noise can not be seen, but when call git, they are so dazzling.

They both need to check which would spend too much time for people, but for tool, only some seconds.

**Comment by daixiang0** [comment]
ping @sftim

**Comment by sftim** [comment]
/priority backlog
(feel free to revise)

**Comment by daixiang0** [comment]
update
