### ISSUE TITLE
Issue with k8s.io/de/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by leifwenzel** [kubernetes/website#18213]
**This is a Bug Report**

**Problem:**
The command "brew cask install minikube" does not work anymore. 

**Proposed Solution:**
Now it is only possible to install minikube with this command: "brew install minikube"
**Page to Update:**
https://kubernetes.io/de/docs/tasks/tools/install-minikube/

**Comment by sftim** [comment]
Thank you for reporting this @leifwenzel. Die deutsche Lokalisierung ist nicht aktuell / the German localization is outdated.
/language de
/kind cleanup
/priority backlog
