### ISSUE TITLE
Make snippets copy/pastable for wordpress on k8s

### ISSUE THREAD

**Issue by anshprat** [kubernetes/website#18239]
**This is a Bug Report**

**Problem:** 
In https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/
 - the section `Add them to kustomization.yaml file.` is not copy pastable as it is due to extra tabs which break EOF due to extra tab/space. Same space breaks the yaml as well.

**Proposed Solution:**

Remove extra space and make it copy / pastable.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

**Comment by anshprat** [comment]
Related Bug reports:

#17786
#14810

**Comment by sftim** [comment]
(This does also look like a duplicate)
