### ISSUE TITLE
Describe `{{< codenew >}}` shortcode in style guide

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18231]
**This is a Feature Request**

**What would you like to be added**
In the [style guide](https://kubernetes.io/docs/contribute/style/style-guide/), explain when to make code samples (eg manifests) downloadable, and how to do that.

**Why is this needed**
https://kubernetes.io/docs/contribute/style/style-guide/ does not mention how to style downloadable code blocks.
If you know what to search for I think it's easy to work out the convention. Essentially, pages that provide ready-to-run sample manifests should put them in (eg) `content/en/examples/debug/counter-pod.yaml` (for English localization) and reference the downloadable code sample directly, using the 
`{{< codenew >}}` shortcode.

**Comments**

For example: https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/#creating-and-exploring-an-nginx-deployment

Consider also mentioning code samples in a [localization](https://kubernetes.io/docs/contribute/localization/) context. Typically, code samples copy over unchanged _but_ natural-language comments might want translating. For example: https://github.com/kubernetes/website/blob/master/content/ko/examples/application/deployment.yaml

/help

**Comment by sftim** [comment]
If the existing mechanism isn't clear, and you'd like to help, I'll be happy to explain my understanding of it.

**Comment by sftim** [comment]
Oops, wrong click.

**Comment by sftim** [comment]
I just noticed that https://kubernetes.io/docs/contribute/style/write-new-topic/#including-code-from-another-file does mention this shortcode.

**Comment by mehabhalodiya** [comment]
@anshprat I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @anshprat

**Comment by dipesh-rawat** [comment]
I'm happy to make the required changes and get this issue moving forward.

/assign

**Comment by dipesh-rawat** [comment]
Changes to addressed this issue have been merged as part of PR #39764

**Comment by dipesh-rawat** [comment]
Completed via #39764

/close
