### ISSUE TITLE
strange character found from cpu manager blog post

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#18249]
**This is a Bug Report**

**Problem:**
When I was reading the [blogpost](https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/) for explaining the cpu manager feature, I have seen a strange char from the `How to use` section, see below:

![image](https://user-images.githubusercontent.com/3972545/71344000-5cc8a280-259c-11ea-855b-e1f84b7b7101.png)

**Proposed Solution:**
Need to clarify whether it is a typo or sth meaningfulness. 

**Page to Update:**
https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/

**Comment by wawa0210** [comment]
I think this should be a typo

i fix this #18257

**Comment by sftim** [comment]
[voilà](https://en.wiktionary.org/wiki/voil%C3%A0) is borrowed into English from French. It's OK to leave that as is.
/area blog

**Comment by Colstuwjx** [comment]
OK, since it's a valid word, I'd like to close this issue.
