### ISSUE TITLE
Ingress page does not document rule precedence

### ISSUE THREAD

**Issue by glasser** [kubernetes/website#18265]
**This is a Bug Report**

**Problem:**

The Ingress docs (eg, content/en/docs/concepts/services-networking/ingress.md as well as the auto-generated API Reference docs) do not explain what happens if multiple `paths` entries match an URL or if multiple `rules` match an URL.

**Proposed Solution:**

Somebody tells me what the order of precedence is (first match? last match? multiple matches are undefined behavior that may be treated differently by different controllers? URLs matching multiple rules or paths are redirected to rickrolls?) and I send in a docs PR explaining it.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by glasser** [comment]
Or maybe the answer is "most specific matches"?

Another confusing thing is that the reference docs (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#httpingresspath-v1beta1-networking-k8s-io) claim that `path` is a regex, but e.g. the [GKE ingress docs](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress) claim that a trailing `*` wildcard works with that controller in a non-regex way (just meaning "any string" rather than "repeat previous character).

**Comment by sftim** [comment]
Does https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#paths-proposal cover this?

(if not, @glasser, maybe what should happen next is you raise an issue about that KEP, to highlight the gap).
/sig network

**Comment by glasser** [comment]
@sftim I'll take a look. At first glance I don't understand how to tell the status of this KEP — is it proposed or finished? I think Ingress is already in networking.v1beta1 so that means finished, right?

**Comment by sftim** [comment]
I had a look at the KEP and I couldn't be sure about the status either.
Ingress is definitely _beta_ and “Graduate Ingress to GA” seems like the best documentation there is for its current behavior.

To my mind, one thing that should happen before GA is preparing a clear specification and getting some documentation drafted that matches it.

**Comment by glasser** [comment]
OK, the paths proposal covers most of my question, and it seems that the answer for now is "it's implementation-specific" so there is no simple answer to add to the k8s docs today (other than perhaps being explicit that it is implementation-specific).

I commented on https://github.com/kubernetes/enhancements/issues/758 asking to clarify the behavior of multiple matching rules (perhaps "you should not have multiple `rules` entries with the same hostname).

**Comment by sftim** [comment]
> being explicit that it is implementation-specific
That sounds like the way forward.
