### ISSUE TITLE
Fix simple typos in feature gates document

### ISSUE THREAD

**Issue by hase1128** [kubernetes/website#18275]
**This is a Bug Report**

**Problem:**
There are some typos in "https://github.com/kubernetes/website/blob/master/content/en/docs/reference/command-line-tools-reference/feature-gates.md"

1: This feature is superceded by the VolumeScheduling feature completely in v1.12.
2: Enable setting Pod affinity or anti-affinitys.

**Proposed Solution:**
1: superseded
2: anti-affinity

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by php-coder** [comment]
The fix (#18276) seems to be merged, could we close this issue then?

**Comment by hase1128** [comment]
sure, I close.
