### ISSUE TITLE
Issue with k8s.io/docs/reference/glossary/

### ISSUE THREAD

**Issue by openaphid** [kubernetes/website#18294]
**This is a Bug Report**

**Problem:**
`cluster infrastructure` and `cluster operations` are not included in glossary while there are references to them in https://kubernetes.io/docs/setup/#production-environment

**Proposed Solution:**
Add two terms

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?all=true

**Comment by sftim** [comment]
/kind bug
/priority backlog
Those documents exist in the glossary but aren't being listed. I think I can fix that.

**Comment by sftim** [comment]
Thanks for spotting this @openaphid
