### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

### ISSUE THREAD

**Issue by godlessendeavor** [kubernetes/website#18302]
**This is a Bug Report**

**Problem:**
The picture module_04_services.svg is showing in naming in the legend the cube shape as Pod while in reality (and consistently with previous modules pictures) it is a container. At the same time  the real shape of the Pod (the circle) is missing in the legend. 

**Proposed Solution:**
Change the Pod in the legend to Container and add the Pod shape, the circle, to the legend as well.

**Page to Update:**
k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

**Comment by sftim** [comment]
That seems valid
/priority important-longterm
