### ISSUE TITLE
kubectl: oidc configuration

### ISSUE THREAD

**Issue by philips** [kubernetes/website#1831]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**

The OIDC parameters for kubectl configuration aren't documented as far as I can find. These fields include: client-id, client-secret, idp-certificate-authority-data, idp-issuer-url, and refresh-token.

**Proposed Solution:**

Document. @ericchiang or @rithujohn191 could you take a swing?

**Page to Update:**
http://kubernetes.io/docs/user-guide/kubeconfig-file/

**Comment by spnzig** [comment]
Is this already added? Even i seem to be confused with the right value for these parameters while configuring K8S with oidc.

**Comment by ericchiang** [comment]
@spnzig the docs were added to the authentication section https://kubernetes.io/docs/admin/authentication/#using-kubectl

**Comment by spnzig** [comment]
@ericchiang But it doesnt mention how one can get values for id_token, refresh-token.

**Comment by ericchiang** [comment]
@spnzig that's out of scope for kubernetes. You should consult your identity provider's docs.

https://github.com/coreos/dex/blob/master/Documentation/using-dex.md
https://developers.google.com/identity/protocols/OpenIDConnect

**Comment by spnzig** [comment]
Thanks for that @ericchiang . I was confused with this because i came across another issue which told me that i can use **k8s-oidc-helper package** to get these details. I was facing errors with its install too. So could not proceed

**Comment by tengqm** [comment]
The topic is out of scope. Closing.
