### ISSUE TITLE
Localize https://k8s.io/docs/contribute/ to Bahasa Indonesia

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18336]
**This is a localization request**

**What would you like to be added**
Localize https://k8s.io/docs/contribute/ into Bahasa Indonesia

**Why is this needed**
Readers who are looking at the Indonesian (Bahasa Indonesia) documentation, and who might want to contribute (for example, by reviewing changes) should see pages about how to contribute.

**Comments**
This issue is resolved once https://k8s.io/id/docs/contribute/ exists and contains at least stub pages.
/language id
/priority backlog

**Comment by phanama** [comment]
I'll kickstart the index page.
Let's put these pages into our backlog and discuss it in our next meeting @girikuncoro @irvifa @danninov @wahyuoi

**Comment by irvifa** [comment]
Understood, let’s discuss this in the next meeting.

**Comment by irvifa** [comment]
Understood, we will discuss this in our next meeting. Thank you @sftim for raising this issue.

**Comment by sftim** [comment]
/remove-lifecycle stale
Done
/close
