### ISSUE TITLE
Localize https://k8s.io/docs/contribute/ to Russian | Русский

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18332]
**This is a localization request**

**What would you like to be added**
Localize https://k8s.io/docs/contribute/ into Russian | перевести https://k8s.io/docs/contribute/ на Русский.

**Why is this needed**
Readers who are looking at the Russian documentation, and who might want to contribute (for example, by reviewing changes) should see pages about how to contribute.

**Comments**
This issue is resolved once https://k8s.io/ru/docs/contribute/ exists and contains at least stub pages.
/language ru
/priority backlog

Connected to #16005

**Comment by php-coder** [comment]
This issue has been fixed by #19022 and requested page is now exist: https://kubernetes.io/ru/docs/contribute/

/close
