### ISSUE TITLE
Localize https://k8s.io/docs/contribute/ to Portuguese

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18333]
**This is a localization request**

**What would you like to be added**
Localize https://k8s.io/docs/contribute/ into Portuguese

**Why is this needed**
Readers who are looking at the Portuguese documentation, and who might want to contribute (for example, by reviewing changes) should see pages about how to contribute.

**Comments**
This issue is resolved once https://k8s.io/pt/docs/contribute/ exists and contains at least stub pages.
/language pt
/priority backlog

**Comment by femrtnz** [comment]
Hi @sftim 

I think we can close this, right?

Thanks

**Comment by sftim** [comment]
Looks done to me.
