### ISSUE TITLE
Improvement for k8s.io/docs/concepts/architecture/nodes/

### ISSUE THREAD

**Issue by danibavr** [kubernetes/website#18365]
Dear authors,
On "Reliability" section:
 is written 

> "A key reason for spreading your nodes across availability zones is so that the workload can be shifted to healthy zones when one entire zone goes down. Therefore, if all nodes in a **zone are unhealthy then node controller evicts at the normal rate --node-eviction-rate.** "

  but before is mentioned 

> " If the fraction of unhealthy nodes is at least --unhealthy-zone-threshold (default 0.55) then the eviction rate is reduced: **if the cluster is small (i.e. has less than or equal to --large-cluster-size-threshold nodes - default 50) then evictions are stopped, otherwise the eviction rate is reduced to --secondary-node-eviction-rate (default 0.01) per second**."

The behavior described is a bit confusing.

In "Heartbeats" section: 
is written 
> "The default interval for NodeStatus updates is 5 minutes (much longer than the 40 second default timeout for unreachable nodes)."

Here is not very clear how the node controller update status to "Unknown" if the timeout is 40s but the check is made in a greater interval.

Thank you,
  Daniele

**Comment by sftim** [comment]
This wording could be more clear. I hope we can reword.
/sig node
/priority backlog
