### ISSUE TITLE
no workaround for  minikube start up on win 10 home

### ISSUE THREAD

**Issue by atanu2531** [kubernetes/website#18364]
Error: [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

C:\>minikube start
* minikube v1.6.2 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Selecting 'virtualbox' driver from existing profile (alternates: [])
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible
* Error: [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--vm-driver=none'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by sftim** [comment]
It sounds like you need a computer with hardware virtualization enabled @atanu2531 
Are you able to try enabling that and see if it helps?

/triage support

**Comment by erchauhannitin** [comment]
Facing same issue and i don't have access to BIOS password. 
I disabled it by mistake by running one command( though it still shows Virtualization enabled in Task Manager, Performance Tab). Now minikube start is giving errors in win 10 and does not see any work around.
