### ISSUE TITLE
Issue with k8s.io/zh/docs/concepts/configuration/assign-pod-node/

### ISSUE THREAD

**Issue by tonkon** [kubernetes/website#18377]
**This is a Bug Report**

**Problem:** Translation error in Chinese at section **Node affinity**

The description about multiple matchExpressions associated with nodeSelectorTerms in English is:

_If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node **only if all** matchExpressions can be satisfied._

But in Chinese here, it translates into opposite logic:

_如果你指定了多个与 nodeSelectorTerms 关联的 matchExpressions，则**如果其中一个** matchExpressions 满足的话，pod 才可以调度到节点上。_

**Proposed Solution:**

The correct translation should be:

_如果你指定了多个与 nodeSelectorTerms 关联的 matchExpressions，则**只有当所有** matchExpressions 满足，pod 才可以调度到节点上。_

**Page to Update:**
https://kubernetes.io/zh/docs/concepts/configuration/assign-pod-node/

**Comment by pigletfly** [comment]
the translation is fixed. /close
