### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by yuva13** [kubernetes/website#18375]
**This is a Bug Report**
bb

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by savitharaghunathan** [comment]
Hi @yuva13 , could you brief a little bit more about the problem that you are seeing?

/triage needs-information
