### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/manage-compute-resources-container/

### ISSUE THREAD

**Issue by sureshgunturi** [kubernetes/website#18379]
optional monitoring  hyper link didnt work ,it showing 404

**Comment by sftim** [comment]
The broken hyperlink is to http://releases.k8s.io/master/cluster/addons/cluster-monitoring/README.md

/priority backlog
/kind bug

**Comment by butuzov** [comment]
Shouldn't be this link to be updated to metrics server as successor of hipster?

**Comment by tengqm** [comment]
Resolved.
/close
