### ISSUE TITLE
Documentation for Container

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#18381]
**This is a Feature Request**

**What would you like to be added**
A comprehensive page for the Container concept.

**Why is this needed**
We are currently assuming the the readers know what Containers are. However, this may not be true. For example, when composing a Pod, one has to provide the container configuration. There are many settings pertaining to a container not documented anywhere today. For example:

- The `image` field MUST be specified, but an empty string has a different meaning.
- Each port in the `ports` of the container may have a name specified, but that name must be of particular format:
  - its value must be unique in the scope of a Pod;
  - no more than 15 characters;
  - only contains `[-a-z0-0]`;
  - cannot begin or end withs `-`;
  - cannot have two adjacent hyphens, i.e. `--` is not allowed.
- ...

**Comments**

**Comment by sftim** [comment]
These details sound to me like they are worth introducing when Pods are introduced. If the reader has not seen containers as a concept, telling them about `ports` in a PodSpec is going into a lot of detail.

I mean: place a new page in https://kubernetes.io/docs/concepts/workloads/pods/ and have the Container concept page suggest different routes for readers based on their own assessment of how comfortable the reader is with those concepts.

How does that sound?

**Comment by tengqm** [comment]
See the current TOC for container and pod, we can choose either location for these details.
![image](https://user-images.githubusercontent.com/5094756/71619590-08f33480-2c00-11ea-99b6-e6f90a5a7df0.png)

**Comment by sftim** [comment]
It's definitely important to help readers who are new to containers overall. At least some people will read through the Concepts section, pretty much in order, until they're confident enough to try a Task or their heads are full (whichever comes first).

Whichever location we pick, the overview for the other concept (Pod / Container) can link to the new page.

**Comment by sftim** [comment]
I wonder if it makes sense to move Init Containers and Ephemeral Containers into the Containers section?

The way I see that working is that at some point inside the Container concept section, the reader is told that there's a thing called a Pod and that there's more to read up on that detail _later_, and that there's a link if they want to go and do that now.

After that point it's fair game to talk about container configuration in a manifest, init containers, ephemeral containers, etc.

**Comment by sftim** [comment]
> I wonder if it makes sense to move Init Containers and Ephemeral Containers into the Containers section?

No, I don't think so. However, a better overview for the Containers concept can _link_ there.

The context has also changed a little, since https://github.com/kubernetes/website/pull/22603 was merged.

**Comment by sftim** [comment]
@tengqm how well does https://kubernetes.io/docs/concepts/containers/ match what you wanted, now it's been revised a bit?

(can you list what is still missing?)

**Comment by tengqm** [comment]
@sftim see the original issue report. Those are some of the gaps I found when studying the container validation code.

**Comment by sftim** [comment]
I'm thinking about a what's next: “To learn how to specify containers in Pod definitions, see _Specifying containers_”
(and also someone writes that page).

(Specifying rather than configuring so it doesn't get confused with ConfigMap, Secret, etc)

**Comment by sftim** [comment]
Hope this is OK to:
/reopen
/remove-lifecycle rotten
