### ISSUE TITLE
Incorrect comment format display

### ISSUE THREAD

**Issue by rainingmaster** [kubernetes/website#18406]
**This is a Bug Report**

**Problem:**
The page incorrect with the comment, such as: `https://kubernetes.io/zh/docs/concepts/services-networking/ingress/#%E4%B8%93%E7%94%A8%E6%9C%AF%E8%AF%AD`. It was correct in my mac, and the version of hugo is `Hugo Static Site Generator v0.62.1/extended darwin/amd64`.

**Proposed Solution:**
Update hugo in server.

**Page to Update:**
https://kubernetes.io/zh/docs/concepts/services-networking/ingress/#%E4%B8%93%E7%94%A8%E6%9C%AF%E8%AF%AD.

**Comment by sftim** [comment]
/kind bug
/priority important-soon

I think.

**Comment by sftim** [comment]
I think this is fixed. @rainingmaster can you confirm?
