### ISSUE TITLE
Use localization friendly links in English main site.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#18403]
**This is a Feature Request**

**What would you like to be added**

The intra-site links in the English documents are currently plain markdown links, as shown below:

```
* Learn about [Controllers](/docs/concepts/architecture/controller/)
```

When pages containing such links are translated into another language, the localization team has to take extra care to handle them or else the links will be missing or pointing to an incorrect location. For example, in the Chinese localization, the above line has to be revised to something like:

```
* 进一步了解 [控制器](/zh/docs/concepts/architecture/controller/)
```

We need to revise this links to one of the following formats so that the links can be automatically converted to the correct target:

```
* Learn about [Controllers]({{< relref "docs/concepts/architecture/controller.md" >}})
* Learn about [Controllers]({{< ref "/docs/concepts/architecture/controller.md" >}})
```

For English main site and all localization sites, the above links can be correctly converted.

**Why is this needed**

Taking care of so many links for so many localization, across so many teams is error-prone and boring. Once we have the links on the English main site refactored. All localization teams can simply skip updating the link  target.

As a bonus, if a link target doesn't exist in a particular language, Hugo can detect the missing link and report errors during build. So we can detect missing links as early as possible.

**Comments**

For related experiments, see #18374

**Comment by sftim** [comment]
:100: this

To be honest, when I started contributing I saw that there were localizations and I assumed that a mechanism similar to this already existed. I was genuinely surprised when I realized that localization teams needed to manually track this kind of detail.

**Comment by sftim** [comment]
/kind feature
Does /priority important-longterm feel right?

**Comment by tengqm** [comment]
No objections wrt priority. :)

**Comment by kbhawkey** [comment]
This is interesting!
Looking at the Hugo docs,
https://gohugo.io/content-management/cross-references/

How does this workk?
```
{{< relref path="document.md" lang="ja" >}}
```

**Comment by tengqm** [comment]
Right, if you explicitly provide a `lang` param, hugo will try redirect you to the specified localization. One use case, in k8s/website could be that for some content, we want to redirect all anchors to the same language, say English.

**Comment by tanjunchen** [comment]
@tengqm  
Is it appropriate to add /zh directly in front of it right now?
/cc @yuxiaobo96 
thanks your job!

**Comment by tanjunchen** [comment]
@sftim @tengqm 
Is there any progress on this matter?

**Comment by yuxiaobo96** [comment]
I think the modification proposed by tengqm is better.

**Comment by tengqm** [comment]
@tanjunchen No progress yet. If the proposed approach makes sense, we may need to revise the English site as early as possible.

**Comment by tanjunchen** [comment]
> @tanjunchen No progress yet. If the proposed approach makes sense, we may need to revise the English site as early as possible.

done

**Comment by Colstuwjx** [comment]
Inspired by @tengqm PR #18374 experiment, I have been proposed another PR #18678 for solving this issue.

For `ref` and `relref`, I did some research, see [hugo 2637](https://github.com/gohugoio/hugo/issues/2637#issuecomment-256933811), there is no builtin function **do check existence ONLY**, and I found [lang.Merge](https://gohugo.io/functions/lang.merge/), but it seems not addressing this issue, see [hugo 5612](https://github.com/gohugoio/hugo/issues/5612).

For these reasons, I think customized shortcode should be better, and PR #18678 is my answer.
Many thanks to @tengqm great job.

**Comment by sftim** [comment]
Sort of related: PR #18871.

**Comment by remyleone** [comment]
@feloy @rekcah78

**Comment by tanjunchen** [comment]
How about this issue now ? see https://github.com/kubernetes/website/issues/18929 
They add `ja` in front of the path. 
Is it currently possible to implement similar functionality directly by modifying the hugo code. 
/cc @tengqm
/cc @Colstuwjx

**Comment by tengqm** [comment]
@tanjunchen It is not gonna be a trivial change. I'm not a big fan of adding/modifying hugo code in this repo.

**Comment by Colstuwjx** [comment]
@tengqm Do you have any idea about solving this issue?

I think it should be a common issue for multilingual site, and we may need to make a conclusion about how to fix this issue at first, and then try to propose a PR for fixing it, here are some considerations in my mind:

We already have multilingual [configurations](https://github.com/kubernetes/website/blob/master/config.toml#L134), such as supported languages and their weight, content dir, [language alternatives](https://github.com/kubernetes/website/blob/master/config.toml#L151) etc, if we could add something for configuring this link convert, for example like adding configuration `makeRefAddLangPrefixByDefault=true`.

If it's been set true, we could make hugo adding the language prefix by current dir language and its alternative language, therefore, we didn't need to handle this job by manually anymore...

If someone didn't prepare the translation placeholder for the ref, hugo should try to make the ref link fallback to the alternative language, and if it still fails, hugo should panic and throw errors, just like the shortcode `ref` and `relref` did.

What do you think about this solution? Or it's welcome if you have another better and workable solution. If we could make a conclusion, and it needs do some job with hugo upstream, I'm ready to do this.

Thanks.

**Comment by tengqm** [comment]
The `makeRefAddLangPrefixByDefault=true` suggestion sounds good at fist glance. However, from Hugo developer's perspective, it may not be a priority since there are already existing facility to achieve the same goal. We may even conclude that our current way of codifying intra-site links are wrong. We SHOULD have used the localization friendly way to do this.

**Comment by Colstuwjx** [comment]
> We SHOULD have used the localization friendly way to do this.
Yes, I was also wondering about this. I don't have any idea about which is the right way to do this, so I leave a [comment](https://github.com/gohugoio/hugo/issues/6747#issuecomment-596056597) on hugo repo, maybe hugo dev could give us some suggestions.

**Comment by tanjunchen** [comment]
We SHOULD have used the localization friendly way to do this.

+1
@Colstuwjx  I have no good idea.

**Comment by tengqm** [comment]
still relevant.
/remove-lifecycle rotten

**Comment by irvifa** [comment]
@tengqm would you like to help us for this issue? I was wondering what else needed besides the config itself.

**Comment by tengqm** [comment]
@irvifa Please check PR #19526 for the proposed changes.

**Comment by sftim** [comment]
My #1 favorite approach would be for a localization team to write something like:
```markdown
* 进一步了解 [控制器](/docs/concepts/architecture/controller/)
```

and for the generated HTML to link to https://kubernetes.io/zh/docs/concepts/architecture/controller/ (or whatever language code is appropriate.

If Hugo can't yet do this, it might even be feasible to look into tweaking Hugo itself.

**Comment by sftim** [comment]
/reopen

Oops. Misclick.

**Comment by Andygol** [comment]
I would like to /reopen this ticket in light of Hugo's ability to render links via https://gohugo.io/render-hooks/links/. This option can be used to implicitly add a language prefix to links. Thus, all valid Markdown links `[text](/docs/…)` in the text can receive a language prefix if there is a localized document.

Any advice and suggestions are welcome 🙏 

PS. My WIP is here https://github.com/Andygol/k8s-website/pull/160 🚧

**Comment by Andygol** [comment]
@sftim 🛎️ ☝️

**Comment by sftim** [comment]
Ack. I've seen the message @Andygol.
