### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/cloud-providers/

### ISSUE THREAD

**Issue by jessie123jiang** [kubernetes/website#18410]
Add a New cloud Provider of Alibaba Cloud 

## Alibaba Cloud
 If you wish to use the external cloud provider, its repository is kubernetes/cloud-provider-alibaba-cloud(link:https://github.com/kubernetes/cloud-provider-alibaba-cloud)

### Node Name
The AlibabaCloudProvider use ${region-id}.${instance-id} as the name of the Kubernetes Node object which is determined by the kubelet overridden with `--hostname-override=${region-id}.${instance-id} --provider-id=${region-id}.${instance-id}`

**Comment by zhangxiaoyu-zidif** [comment]
sig/cloud

**Comment by sftim** [comment]
See PR #18255

**Comment by ialidzhikov** [comment]
Alibaba cloud is now part of the cloud providers page - ref https://github.com/kubernetes/website/pull/20858.

**Comment by ialidzhikov** [comment]
cc @sftim for `/close`
