### ISSUE TITLE
SEE ALSO section under content/zh/docs/reference/setup-tools/kubeadm/generated/ need to be deleted

### ISSUE THREAD

**Issue by ydcool** [kubernetes/website#18411]
**This is a Bug Report**

**Problem:**
Since the SEE ALSO section was removed in https://github.com/kubernetes/website/pull/17123, those files for zh translation should be updated as the same. 

**Proposed Solution:**
List of all files should be updated:

- [x] 1. [kubeadm.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm.md)
- [x] 2. [kubeadm_alpha.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha.md)
- [x] 3. [kubeadm_alpha_certs_certificate-key.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_certificate-key.md)
- [x] 4. [kubeadm_alpha_certs_renew.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew.md)
- [x] 5. [kubeadm_alpha_certs_renew_admin.conf.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_admin.conf.md)
- [x] 6. [kubeadm_alpha_certs_renew_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_all.md)
- [x] 7. [kubeadm_alpha_certs_renew_apiserver-etcd-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_apiserver-etcd-client.md)
- [x] 8. [kubeadm_alpha_certs_renew_apiserver-kubelet-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_apiserver-kubelet-client.md)
- [x] 9. [kubeadm_alpha_certs_renew_apiserver.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_apiserver.md)
- [x] 10. [kubeadm_alpha_certs_renew_controller-manager.conf.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_controller-manager.conf.md)
- [x] 11. [kubeadm_alpha_certs_renew_etcd-healthcheck-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_etcd-healthcheck-client.md)
- [x] 12. [kubeadm_alpha_certs_renew_etcd-peer.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_etcd-peer.md)
- [x] 13. [kubeadm_alpha_certs_renew_etcd-server.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_etcd-server.md)
- [x] 14. [kubeadm_alpha_certs_renew_front-proxy-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_front-proxy-client.md)
- [x] 15. [kubeadm_alpha_certs_renew_scheduler.conf.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_renew_scheduler.conf.md)
- [x] 16. [kubeadm_alpha_kubeconfig.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubeconfig.md)
- [x] 17. [kubeadm_alpha_kubeconfig_user.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubeconfig_user.md)
- [x] 18. [kubeadm_alpha_kubelet.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubelet.md)
- [x] 19. [kubeadm_alpha_kubelet_config.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubelet_config.md)
- [x] 20. [kubeadm_alpha_kubelet_config_download.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubelet_config_download.md)
- [x] 21. [kubeadm_alpha_kubelet_config_enable-dynamic.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_kubelet_config_enable-dynamic.md)
- [x] 22. [kubeadm_alpha_selfhosting.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_selfhosting.md)
- [x] 23. [kubeadm_alpha_selfhosting_pivot.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_selfhosting_pivot.md)
- [x] 24. [kubeadm_completion.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_completion.md)
- [x] 25. [kubeadm_config.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config.md)
- [x] 26. [kubeadm_config_images.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images.md)
- [x] 27. [kubeadm_config_images_list.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md)
- [x] 28. [kubeadm_config_images_pull.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md)
- [x] 29. [kubeadm_config_migrate.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_migrate.md)
- [x] 30. [kubeadm_config_print.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print.md)
- [ ] 31. [kubeadm_config_print_init-defaults.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_init-defaults.md)
- [ ] 32. [kubeadm_config_print_join-defaults.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md)
- [ ] 33. [kubeadm_config_view.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_view.md)
- [ ] 34. [kubeadm_init.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md)
- [ ] 35. [kubeadm_init_phase.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase.md)
- [ ] 36. [kubeadm_init_phase_addon.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon.md)
- [ ] 37. [kubeadm_init_phase_addon_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_all.md)
- [ ] 38. [kubeadm_init_phase_addon_coredns.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_coredns.md)
- [ ] 39. [kubeadm_init_phase_addon_kube-proxy.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_addon_kube-proxy.md)
- [ ] 40. [kubeadm_init_phase_bootstrap-token.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_bootstrap-token.md)
- [x] 41. [kubeadm_init_phase_certs.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs.md)
- [x] 42. [kubeadm_init_phase_certs_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_all.md)
- [x] 43. [kubeadm_init_phase_certs_apiserver-etcd-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md)
- [x] 44. [kubeadm_init_phase_certs_apiserver-kubelet-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md)
- [x] 45. [kubeadm_init_phase_certs_apiserver.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md)
- [x] 46. [kubeadm_init_phase_certs_ca.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_ca.md)
- [x] 47. [kubeadm_init_phase_certs_etcd-ca.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-ca.md)
- [x] 48. [kubeadm_init_phase_certs_etcd-healthcheck-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md)
- [x] 49. [kubeadm_init_phase_certs_etcd-peer.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md)
- [x] 50. [kubeadm_init_phase_certs_etcd-server.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md)
- [x] 51. [kubeadm_init_phase_certs_front-proxy-ca.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-ca.md)
- [x] 52. [kubeadm_init_phase_certs_front-proxy-client.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md)
- [x] 53. [kubeadm_init_phase_certs_sa.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_sa.md)
- [x] 54. [kubeadm_init_phase_control-plane.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane.md)
- [ ] 55. [kubeadm_init_phase_control-plane_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md)
- [ ] 56. [kubeadm_init_phase_control-plane_apiserver.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md)
- [ ] 57. [kubeadm_init_phase_control-plane_controller-manager.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md)
- [x] 58. [kubeadm_init_phase_etcd.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd.md)
- [x] 59. [kubeadm_init_phase_etcd_local.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd_local.md)
- [ ] 60. [kubeadm_init_phase_kubeconfig.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig.md)
- [ ] 61. [kubeadm_init_phase_kubeconfig_admin.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_admin.md)
- [ ] 62. [kubeadm_init_phase_kubeconfig_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_all.md)
- [ ] 63. [kubeadm_init_phase_kubeconfig_controller-manager.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_controller-manager.md)
- [ ] 64. [kubeadm_init_phase_kubeconfig_kubelet.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_kubelet.md)
- [ ] 65. [kubeadm_init_phase_kubeconfig_scheduler.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubeconfig_scheduler.md)
- [ ] 66. [kubeadm_init_phase_kubelet-start.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-start.md)
- [ ] 67. [kubeadm_init_phase_mark-control-plane.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_mark-control-plane.md)
- [ ] 68. [kubeadm_init_phase_preflight.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_preflight.md)
- [ ] 69. [kubeadm_init_phase_upload-certs.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-certs.md)
- [ ] 70. [kubeadm_init_phase_upload-config.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config.md)
- [x] 71. [kubeadm_init_phase_upload-config_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_all.md)
- [x] 72. [kubeadm_init_phase_upload-config_kubeadm.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_upload-config_kubeadm.md)
- [x] 73. [kubeadm_join.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md)
- [x] 74. [kubeadm_join_phase.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase.md)
- [x] 75. [kubeadm_join_phase_control-plane-join.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join.md)
- [x] 76. [kubeadm_join_phase_control-plane-join_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_all.md)
- [x] 77. [kubeadm_join_phase_control-plane-join_etcd.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md)
- [x] 78. [kubeadm_join_phase_control-plane-join_mark-control-plane.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_mark-control-plane.md)
- [x] 79. [kubeadm_join_phase_control-plane-join_update-status.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_update-status.md)
- [x] 80. [kubeadm_join_phase_control-plane-prepare.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare.md)
- [ ] 81. [kubeadm_join_phase_control-plane-prepare_all.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md)
- [ ] 82. [kubeadm_join_phase_control-plane-prepare_certs.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_certs.md)
- [ ] 83. [kubeadm_join_phase_control-plane-prepare_control-plane.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_control-plane.md)
- [ ] 84. [kubeadm_join_phase_control-plane-prepare_download-certs.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_download-certs.md)
- [ ] 85. [kubeadm_join_phase_control-plane-prepare_kubeconfig.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_kubeconfig.md)
- [x] 86. [kubeadm_join_phase_kubelet-start.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_kubelet-start.md)
- [x] 87. [kubeadm_join_phase_preflight.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_preflight.md)
- [x] 88. [kubeadm_reset.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset.md)
- [x] 89. [kubeadm_reset_phase.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase.md)
- [x] 90. [kubeadm_reset_phase_cleanup-node.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node.md)
- [ ] 91. [kubeadm_reset_phase_preflight.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_preflight.md)
- [ ] 92. [kubeadm_reset_phase_remove-etcd-member.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_remove-etcd-member.md)
- [ ] 93. [kubeadm_reset_phase_update-cluster-status.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_update-cluster-status.md)
- [ ] 94. [kubeadm_token.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_token.md)
- [ ] 95. [kubeadm_token_create.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_create.md)
- [ ] 96. [kubeadm_token_delete.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_delete.md)
- [ ] 97. [kubeadm_token_generate.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_generate.md)
- [ ] 98. [kubeadm_token_list.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md)
- [ ] 99. [kubeadm_upgrade.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade.md)
- [ ] 100. [kubeadm_upgrade_apply.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md)
- [ ] 101. [kubeadm_upgrade_diff.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_diff.md)
- [ ] 102. [kubeadm_upgrade_node.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md)
- [ ] 103. [kubeadm_upgrade_node_phase.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase.md)
- [ ] 104. [kubeadm_upgrade_node_phase_control-plane.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md)
- [ ] 105. [kubeadm_upgrade_node_phase_kubelet-config.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_kubelet-config.md)
- [ ] 106. [kubeadm_upgrade_plan.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_plan.md)
- [x] 107. [kubeadm_version.md](https://github.com/kubernetes/website/blob/release-1.17/content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_version.md)

**Page to Update:**
https://kubernetes.io/...

**Comment by ydcool** [comment]
If any one want help to fix these files, please comment below with which files you want to fix so that we won't get confict. thanks.

**Comment by huchengze** [comment]
I will fix the 1~10 files.

**Comment by LinshanYu** [comment]
I will fix the 11~20 files，love you！

**Comment by gaoguangze111** [comment]
21~30 for me, thx Dongchao @ydcool

**Comment by lovebaby979** [comment]
31-40

**Comment by CriaHu** [comment]
leave 41-50 to me

**Comment by wyyxd2017** [comment]
51-60，love and peace

**Comment by timyinshi** [comment]
I will fix the 70~80 files

**Comment by cwocwo** [comment]
81~90

**Comment by zhanw15** [comment]
I will fix the 61~70 files

**Comment by wwgfhf** [comment]
91~100

**Comment by npu21** [comment]
it's my turn 101-107

**Comment by tanjunchen** [comment]
good job
/helped
/good-first-issue

**Comment by tanjunchen** [comment]
it is time to close this issue,right?
@ydcool

**Comment by ydcool** [comment]
@tanjunchen  thank you for your works! 
/close
