### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by jmichalik** [kubernetes/website#18420]
Heapster is not available in the add on list. Maybe it needs to be added to the docker image.

**Comment by sftim** [comment]
@jmichalik would you be willing to capture some diagnostic information about the version of `minikube` that you're using?
Was this using the terminal-version on the website, or Minikube locally? If locally, what version of minikube and how is it set up?

**Comment by BenHall** [comment]
Thanks. It looks like Heapster is no longer a Minikube addon and has been replaced by metrics-server - https://minikube.sigs.k8s.io/docs/tasks/addons/

When Katacoda moved to 1.17 it's highlighted the out-dated docs.

I will raise a PR to update

**Comment by jmichalik** [comment]
@sftim I am using the terminal-version on the website.

**Comment by php-coder** [comment]
In #18611 I applied Russian-related changes from #18422 Thank you, @BenHall

**Comment by php-coder** [comment]
The issue was fixed by #18673
/close
