### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by hepaestus** [kubernetes/website#18423]
How do I set up the KUBECTL config file? I got it to work somehow but now my cluster has changed and I cannot get it to work wot the new setup. How do I tell it what my cluster is etc... Thanks

**Comment by sftim** [comment]
Issue #15671 already exists to track that https://k8s.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/ is not very clear.

I think it would help if https://k8s.io/docs/tasks/tools/install-kubectl/ linked to https://k8s.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

@hepaestus do you agree about that suggestion?
