### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by zarkzheng** [kubernetes/website#18434]
**This is a Bug Report**

**Problem:**
> 如果客户端 pod 和 服务端 pod 在相同的节点上，client_address 就是客户端 pod 的 IP 地址。但是，如果它们在不同的节点上， client_address 将会是客户端 pod 所在节点的 flannel IP 地址。

**Proposed Solution:**
> 无论客户端 pod 和 服务端 pod 是否在相同的节点上，client_address 始终是客户端 pod 的 IP 地址。

Packets sent to ClusterIP from within the cluster are never source NAT’d if running kube-proxy in iptables mode, so the client_address is always the client pod’s IP address, whether the client pod and server pod are in the same node or in different nodes.

**Page to Update:**
https://kubernetes.io/zh/docs/tutorials/services/source-ip/

**Comment by sftim** [comment]
I presume that 
https://kubernetes.io/docs/tutorials/services/source-ip/ also needs fixing?

**Comment by ydcool** [comment]
Duplicated with https://github.com/kubernetes/website/issues/12533 , and en docs was fixed since https://github.com/kubernetes/website/pull/12701, but zh docs did not updated yet.

/language zh
/assign

**Comment by tanjunchen** [comment]
@zarkzheng  
thanks your job! if it is dupicated , we should close this
