### ISSUE TITLE
Issue with kubectl-commands.html

### ISSUE THREAD

**Issue by butuzov** [kubernetes/website#18444]
**This is a Bug Report**

This issue appeared recently within kubernetes/website#18067.

Links in  `kubectl-commands.html` follow the next pattern `[<a href="link]">text</a>]`, see a square bracket inside of the `href`. 

I tried to follow https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/ in order to find a source of the issue, but wasn't able to do so.

my best guesses:
- Source for generation for 1_17 branch was corrupted.
- Backend `pwittrock/brodocs` was replaced by something else but not commited (i don't believe in this).

This can be temporary content (on ein PR) as toolset for kubernetes-sigs/reference-docs .

**Comment by butuzov** [comment]
ping @kbhawkey @tengqm

**Comment by kbhawkey** [comment]
I am looking now

**Comment by kbhawkey** [comment]
@butuzov , you are referring to a link problem in the reference?
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-strong-getting-started-strong-

Can you provide an example of a command that has a link issue? Thanks!

**Comment by kbhawkey** [comment]
I plan on updating the build instructions and README.

**Comment by butuzov** [comment]
@kbhawkey any link that follow pattern `[<a href="link]">text</a>]`. If we ware talking about kubectl.yaml from the root of the kubernetes-sigs/reference-docs, it would be any link in usage block. Almost all of them are anchor links, so problem isn't visible at first. 

P.S. Is it worth time to update build instructions now? Isn't @tengqm going to change generator backend to htmlwriter?

**Comment by kbhawkey** [comment]
@butuzov , I have a feeling there is a mis-communication. I am not sure what you are referring to. I thought you are logging an issue specifically to the kubectl reference. Please provide a specific example.

**Comment by butuzov** [comment]
ok. 
1. open `https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands`
2. search for `http://kubernetes.io/docs/user-guide`
3. click on link 
4. back to `https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands`
5. search for `http://golang.org/pkg/text/template/#pkg-overview`
6. click on link
7. ask yourself why `]` is in link.
8. check diff for kubernetes/website@bcfbd1e8f39dc73 (kubectl-commands.html) and see how links are formed.
  * `[link]` -> become `[<a href="link]">link</a>]` right bracket in the href attribute.

**Comment by kbhawkey** [comment]
> I see a link that appears incorrectly formatted, such as the `template` flag in the `patch` command,
> https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#patch.
> Though, the link does work for me.

I see. I think we are referring to the same problem -- the right bracket.

**Comment by butuzov** [comment]
@kbhawkey Should I close issue or you prefer to have it opened untill kubernetes-sigs/reference-docs#124 is opened?

**Comment by kbhawkey** [comment]
@butuzov , I would leave this issue open as a reminder for next release. Thanks!
NOTE: The links were manually fixed for the 1.17 release (search/replace).

**Comment by butuzov** [comment]
got it!
