### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/access-cluster/

### ISSUE THREAD

**Issue by Vaccano** [kubernetes/website#18441]
This page is the first hit when googling terms such as: _kubectl connect to remote cluster_

The first section pushes the user to other pages to find that syntax.  Those pages (getting started and kubectl reference) either do not have the syntax or do not make it easy to find.

I am still looking for this command, so it may not be just a simple command to connect.  If it is not, then ignore this issue.  But if it is something like `kubectl connect <url>` it would be nice to at least mention it on this page so that googlers at least know to the name of the command they are looking for.

**Comment by sftim** [comment]
It makes sense to me that this page has clear links to pages that help people get started with `kubectl`
/priority important-longterm
/help
