### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

### ISSUE THREAD

**Issue by moulishanmuhavelu** [kubernetes/website#18471]
**This is a Bug Report**

**Problem:**
While upgrading the worker node, we need to run the command "sudo kubeadm upgrade node" . But this command should be run with options else it will throw error.

**Proposed Solution:**
Please add the sample command with config options.

**Page to Update:**
https://v1-15.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

**Comment by neolit123** [comment]
/sig cluster-lifecycle

> But this command should be run with options else it will throw error.

could you clarify what options?

**Comment by moulishanmuhavelu** [comment]
Hi,
If we just run the command "sudo kubeadm upgrade node", it will give an error as "missing subcommand; 'node' is not meant to be run on its own".
It should be given with config options as below:
sudo kubeadm upgrade node config --kubelet-version=v1.1x.x

**Comment by neolit123** [comment]
@moulishanmuhavelu it seems you are running an older version of kubeadm.

> https://v1-15.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

checking the source code of 1.15:
https://github.com/kubernetes/kubernetes/blob/release-1.15/cmd/kubeadm/app/cmd/upgrade/node.go#L71

you should be able to run just `kubeadm upgrade node` if you have the 1.15 version of kubeadm - to upgrade from 1.14 to 1.15.

/triage support

**Comment by neolit123** [comment]
/close
please reopen if needed.
