### ISSUE TITLE
Need example setup/use information in ephemeral containers documentation

### ISSUE THREAD

**Issue by mjbright** [kubernetes/website#18470]
**This is a Bug Report**

**Problem:**
There is no example setup/use information in ephemeral containers documentation at k8s.io/docs/concepts/workloads/pods/ephemeral-containers/

**Proposed Solution:**
Add a *"getting started"* section

**Page to Update:**
https://k8s.io/docs/concepts/workloads/pods/ephemeral-containers/

1.17

As a minimum a pointer to a blog post on configuring/using "kubectl debug" would be useful.

**Comment by sftim** [comment]
I recommend creating a _task_ page to cover this, and making the concept page link to the task page.
/priority backlog
