### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by satva** [kubernetes/website#18485]
**Hyper link to "Kubernetes API"  to get to the insights of it instantly.**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by yuxiaobo96** [comment]
@satva 
Can you elaborate on the problem of this page?
Thanks.

**Comment by gavinfish** [comment]
I think @satva wants to add a hyper link for the `Kubernetes API` item in the article.

**Comment by satva** [comment]
Yes Please . Will be of help to  k8s layman. Thnx.

**Comment by Kipruhwez** [comment]
someone to help me with the online loan application code

**Comment by Kipruhwez** [comment]
sample code
