### ISSUE TITLE
kubectl response example should use apps/v1 for Deployment

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#18491]
**This is a Bug Report**

**Problem:**
`app/v1beta1` is a typo of `apps/v1beta1`?
`apps/v1beta1` has already been deprecated.

![list-deployment](https://user-images.githubusercontent.com/4710215/71806330-e05db580-30ab-11ea-9a76-80748aba5f50.png)

**Proposed Solution:**
`app/v1beta1` should be replaced with `apps/v1`.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#list-deployment-v1-apps

**Comment by sftim** [comment]
/kind bug
/priority backlog

I think this needs fixing [upstream](https://github.com/kubernetes/kubernetes)

**Comment by oke-py** [comment]
This needs fixing [this file](https://github.com/kubernetes-sigs/reference-docs/blob/master/gen-apidocs/config/examples/deployment/list.yaml) and regenerate docs following [this page](https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/).
