### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

### ISSUE THREAD

**Issue by jean-passos** [kubernetes/website#18503]
**This is a Bug Report**

**Problem:**
The current page create two clusters, two users, and three contexts with a file setted in --kubeconfig, but the note to delete user doesn't mention need to set a --kubeconfig when it's generated from that file. Submitting the command as is kubectl try to unset the user on default config file $HOME/.kube/config

**Proposed Solution:**
Mention the need to add --kubeconfig to delete when it's generated from a different default config, not only for users, but also to clusters and contexts

Current

> **Note:** To delete a user you can run kubectl config unset users.\<name>

Proposed

> **Note:** To delete a user you can run kubectl --kubeconfig=config-demo config unset users.\<name>, to remove clusters and/or contexts run the same command, but change users.\<name> to clusters.\<name> and contexts.\<name>, respectively

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

**Comment by Kartik494** [comment]
@jean-passos Hi, i done a PR for the same https://github.com/kubernetes/website/pull/18560, if you are ok with this could we close this issue?
