### ISSUE TITLE
Deployment/DaemonSet in v1.16 API reference should use apps/v1

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#18510]
**This is a Bug Report**

**Problem:**
#18475, #18477 apply to v1.16 API reference.

**Proposed Solution:**
- regenerate docs?
- directly (manually) edit index.html?
- this document is frozen?

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#daemonset-v1-apps
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#deployment-v1-apps

**Comment by tengqm** [comment]
both fixed, close? @oke-py

**Comment by oke-py** [comment]
@tengqm If I understand correctly, they will be fixed when the v1.17 doc is regenerated (maybe when v1.17.1 is released), but the v1.16 doc will not be regenerated ( = not fixed).

**Comment by oke-py** [comment]
Oh, v1.17 docs has already been updated. Thanks!
