### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-kubernetes-objects/declarative-config/

### ISSUE THREAD

**Issue by kibernick** [kubernetes/website#18511]
**This is a Bug Report**

**Problem:**

Cannot print the live configuration using `kubectl get`. 
```
$ kubectl get -f https://k8s.io/examples/application/simple_deployment.yaml -o yaml

Error from server (NotFound): deployments.apps "nginx-deployment" not found
```

**Proposed Solution:**
Perhaps a link has changed, or the dependency `nginx-deployment` that's part of `simple_deployment.yaml` is missing.

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/

**Comment by sftim** [comment]
@kibernick Did you run `kubectl apply -f https://k8s.io/examples/application/simple_deployment.yaml` and _then_ `kubectl get -f https://k8s.io/examples/application/simple_deployment.yaml -o yaml` ?

(if you did, that should work)

/triage support

**Comment by kibernick** [comment]
Thank you @sftim it works now. I guess something went wrong in my previous attempt :)
