### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by mrPsycho** [kubernetes/website#18515]
In section https://kubernetes.io/docs/concepts/services-networking/ingress/#updating-an-ingress it is not obvious how to update configuration. 

`kubectl replace -f` asks for a file, but there is no any path to file which was modified.

would be cool, if there will be added way to find this updated file.

**Comment by mrPsycho** [comment]
also, if i try to find this filename in editor, it shows something like "/tmp/kubectl-edit-hlq9d.yaml" which is expected. 
But when editor closes, there is no such file.

**Comment by sftim** [comment]
It sounds like the documentation that's missing is about how to use `kubectl replace`. Have I got that right?

**Comment by Kartik494** [comment]
@mrPsycho How would like this to be updated. Because what I see is `kubectl` commands are used previously too in the same doc without mentioning the file name. 

I can either add the file name in front of `kubectl replace -f` (like `kubectl replace -f ingress.yaml`) or just add more clarification on which file must be updated in order to update ingress configuration.

**Comment by mrPsycho** [comment]
yes, but previously there is example, for example: https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/service/networking/ingress.yaml

but soon, it is been said to edit it in place: `kubectl edit ingress test`
and: `After you save your changes, kubectl updates the resource in the API server`.... but it didn't updated configuration...
so here i was stuck, and then found, that i can save from editor as another file and use 'kubectl replace -f`.... 

but yes, i'll recheck it.

thanks for pointing it!

**Comment by Kartik494** [comment]
@mrPsycho should we close this issue.As i think it is clear now here we have either option to replace the ingress.yaml (kubectl replace -f ingress.yaml) or we could modify if using (kubectl edit ingress test)

**Comment by mrPsycho** [comment]
yes, sorry for disturbing.
