### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by loyin62688** [kubernetes/website#18527]
**This is a Bug Report**
link in this page is invalid

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by chandankumar4** [comment]
Can I work on this issue?

**Comment by sftim** [comment]
@chandankumar4 please feel free, _but_ it's a very good idea to liaise with @gavinfish who also expressed a clear interest in working on a fix.

**Comment by gavinfish** [comment]
@loyin62688 This issue has been mitigated. You can have a try and close this issue if everything goes fine with you, thanks.

@chandankumar4 Thanks for your passion!

**Comment by tanjunchen** [comment]
@gavinfish 
how  about this  issue  now ?

**Comment by gavinfish** [comment]
I think this can be closed now.
