### ISSUE TITLE
Localize “Read about …” for Chinese

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18540]
**This is a Bug Report**

**Problem**:
https://github.com/kubernetes/website/blob/2c417069d03d838d7b5df0b164a2d089a242d34f/i18n/zh.toml currently [lacks](https://github.com/kubernetes/website/blob/2c417069d03d838d7b5df0b164a2d089a242d34f/i18n/zh.toml#L158) a translation for “Read about …”.

You can see the problem at https://kubernetes.io/zh/case-studies/

**Proposed Solution**:
Localize remaining string in that file:
- [ ] `main_read_about`

**Additional Information**:
/language zh
/kind bug
/priority backlog

**Comment by ydcool** [comment]
@sftim thanks, we'll fix this

**Comment by ydcool** [comment]
PR merged, maybe you can close this issue now ; )

**Comment by sftim** [comment]
@ydcool you can add /close (on a line by itself) in a comment when you're confident it's OK to close an issue.

/close

**Comment by ydcool** [comment]
@sftim  I'm not authorized to use that prow command : (
> Closes an issue or PR. Authors and collaborators on the repository can trigger this command.

**Comment by sftim** [comment]
I'd test that @ydcool - it looks to me like you'd be authorized.
