### ISSUE TITLE
issue with website\content\zh\docs\tutorials\services\source-ip.md

### ISSUE THREAD

**Issue by CriaHu** [kubernetes/website#18552]
**This is enhancement**

**Problem:**
``
然而，如果你的集群运行在 Google Kubernetes Engine/GCE 上，设置 service.spec.externalTrafficPolicy 字段值为 Local 可以强制使没有 endpoints 的节点把他们自己从负载均衡流量的可选节点名单中删除。这是通过故意使它们健康检查失败达到的
``
**Proposed Solution:**
``
然而，如果你的集群运行在 Google Kubernetes Engine/GCE 上，可以通过设置 service.spec.externalTrafficPolicy 字段值为 Local ，故意导致健康检查失败来强制使没有 endpoints 的节点把自己从负载均衡流量的可选节点列表中删除。
``
**Page to Update:**
https://kubernetes.io/zh/docs/tutorials/services/source-ip/

The translation of this passage is not smooth

**Comment by tanjunchen** [comment]
@CriaHu  
thanks your job!
could you open a pr to fix it ? Thanks

**Comment by CriaHu** [comment]
@tanjunchen  ok

**Comment by tanjunchen** [comment]
@CriaHu 
any progress?

**Comment by CriaHu** [comment]
@tanjunchen  It's fixed

**Comment by CriaHu** [comment]
Let me confirm

**Comment by CriaHu** [comment]
https://github.com/kubernetes/website/pull/19562
