### ISSUE TITLE
zh: kubeadm documentation translates subcommands

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18565]
**This is a Bug Report**

**Problem:** 
Headings in https://kubernetes.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-reset-phase/ are for actual subcommands
The translated documentation looks hard to use because the subcommands are translated without showing the original text, which is what readers need to type.

**Proposed Solution:**
Up to the localization team; I think this is an issue but I don't know what works best as a fix. For contrast, https://kubernetes.io/fr/docs/reference/setup-tools/kubeadm/kubeadm/ does not translate any subcommands.

**Page to Update:**
https://kubernetes.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-reset-phase/

/language zh

**Comment by yuxiaobo96** [comment]
I think the original subcommands should be kept without translation.
I can help

**Comment by tanjunchen** [comment]
@yuxiaobo96  
any update?

**Comment by tanjunchen** [comment]
@sftim 
how about this issue?  it seems that it has been resolved.

**Comment by sftim** [comment]
Fixed in #18564
/close
