### ISSUE TITLE
Issue with k8s.io/de/docs/setup/

### ISSUE THREAD

**Issue by Trackhe** [kubernetes/website#18573]
**This is a Bug Report**

**Problem:**
Links not working
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by gavinfish** [comment]
/assign

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gavinfish** [comment]
@Trackhe could you please specify the links?

**Comment by Trackhe** [comment]
@gavinfish I thought I had the correct link here with Reported.

I'm sorry it was already some 100 pages ago. if it comes up to me again I report and report it conscientiously this time.
