### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by miguel-orange** [kubernetes/website#18579]
It seems that this note is inaccurate by saying it's based on timezone. In fact messaging is alluding that timezone will not be supported and it's based on UTC.
> All CronJob schedule: times are based on the timezone of the master where the job is initiated.

https://github.com/kubernetes/kubernetes/issues/78795#issuecomment-501081078
https://github.com/kubernetes/kubernetes/issues/47202#issuecomment-360820586

**Comment by miguel-orange** [comment]
Here's the change for posterity. https://github.com/kubernetes/website/pull/12073/files#diff-42024a68142dd5489c24fa0c4a44d32dR19

**Comment by sftim** [comment]
Thanks for reporting this @miguel-orange 
/kind bug
/priority important-longterm
/good-first-issue

**Comment by panditb** [comment]
Hello Team Is there any deadline when this issue will be fixed ? 
 can we get the the Timezone functionality also with thes CronJob Just want to know

**Comment by sftim** [comment]
Kubernetes is an open-source, volunteer led project. There aren't _deadlines_ per se.

If you're keen to see the documentation changed, for this or any issue, anyone can [contribute](https://kubernetes.io/docs/contribute).

**Comment by sftim** [comment]
(If anyone would like to help here but is not sure how to get started, please reply&mdash;advice is available).

**Comment by soltysh** [comment]
The change is wrong, the time IS taken from the master node the controller is running on, or from within the container controller-manager is running. It's not hardcoded to be UTC. Why are you claiming otherwise, have you checked?

**Comment by sftim** [comment]
Ah, so this issue is invalid and #18715 needs reverting?

**Comment by sftim** [comment]
(alternative fix: revert, then revise `cronjob_controller.go` so that all times _are_ in UTC)

**Comment by sftim** [comment]
I looked at the code:
- https://github.com/robfig/cron/blob/v1/doc.go
- https://github.com/kubernetes/kubernetes/blob/27e5971c11cfcda703a39ed670a565f0f3564713/pkg/controller/cronjob/utils.go#L124

and it looks to me that this issue is invalid. I propose to close it if there's no update in the next fortnight.
/remove-good-first-issue
/remove-help
/remove-kind bug
/remove-priority important-longterm

**Comment by panditb** [comment]
Is this issue  not valid ? , In our instance , we have 2 master node and it configured as EST timezone and 4 worker node and configured as EST timezone , but still cron job runs on the UTC Timezone

**Comment by sftim** [comment]
Is the advice at https://deploy-preview-19269--kubernetes-io-master-staging.netlify.com/docs/concepts/workloads/controllers/cron-jobs/ accurate?

**Comment by panditb** [comment]
Okay thanks!! Now document looks aligned thanks we can close!!
