### ISSUE TITLE
Issue with k8s.io/zh/docs/setup/production-environment/tools/kubeadm/high-availability/

### ISSUE THREAD

**Issue by liyinda246** [kubernetes/website#18585]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by gavinfish** [comment]
Hi @liyinda246 ,
Would you be willing to explain what's not right about that page? The information you provide will help the project understand how to go about a fix.

**Comment by gavinfish** [comment]
@xichengliudui
I have noticed one possible issue for this page. Part of `kubeadm` docs have been translated into Chinese, but the links in this article still point to English ones.
What is the preferred practice here, change the links to Chinese version or wait for all the related translation work done?

**Comment by liyinda246** [comment]
Hi @gavinfish ,
I found that there are some typesetting problems on this page, some Chinese translation errors and English inclusion, as a Chinese, this page is not helpful, thanks

**Comment by tanjunchen** [comment]
language/zh
