### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [kubernetes/website#18599]
**This is a Bug Report**

**Problem:**
The term "Workload" is not defined on the concepts page. 

Googling for "kubernetes workload" returns https://kubernetes.io/docs/concepts/workloads/ as the first result, but the page is completely empty (only has a confusing "Pods" section title).

**Proposed Solution:**
Describe the concept of a workload (at least in a few sentences).

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/

**Comment by sftim** [comment]
Good point. I think it's OK not to prioritize this as there _is_ a glossary entry. Still a nice idea to fix this.
