### ISSUE TITLE
Russian localization is missing code of conduct

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18598]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/ru/community/code-of-conduct/ is a missing page. This page is important because it provides the CNCF code of conduct.

**Proposed Solution:**
- Localize CNCF code of conduct if necessary
- Add Russian code of conduct page to website

**Page to Update:**
https://kubernetes.io/ru/community/code-of-conduct/

/priority important-soon
/language ru
/kind bug

**Comment by vitalyzhakov** [comment]
@sftim , hello!
Russian translation exists https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/ru.md
Maybe we must create link to original document?

**Comment by sftim** [comment]
You can _copy_ the text from https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/ru.md to https://kubernetes.io/ru/community/code-of-conduct/

/good-first-issue

**Comment by madetara** [comment]
Hello. I'd like to work on that issue since #18606 seems abandoned

**Comment by madetara** [comment]
I went ahead and translated community and CoC pages, might as well

/remove-lifecycle stale
/assign

**Comment by madetara** [comment]
I think we can close this now. Forgot to add `Fixes` to #24116 

/close
