### ISSUE TITLE
Vietnamese localization is missing code of conduct

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18597]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/vi/community/code-of-conduct/ is a missing page. This page is important because it provides the CNCF code of conduct.

**Proposed Solution:**
- Localize CNCF code of conduct if necessary
- Add Vietnamese code of conduct page to website

**Page to Update:**
https://kubernetes.io/vi/community/code-of-conduct/

/priority important-soon
/language vi
/kind bug

**Comment by truongnh1992** [comment]
Thank @sftim for reporting this bug. We have already solved it.

**Comment by sftim** [comment]
Once #19020 merges, this can close.

**Comment by truongnh1992** [comment]
Thank you @sftim for reporting this bug. The PR #19020 already fixed it,
