### ISSUE TITLE
Russian glossary

### ISSUE THREAD

**Issue by Potapy4** [kubernetes/website#18591]
Думаю, самое время завести глоссарий. На данный момент, я сотавил небольшой список (дополняйте свои идеи в комментах 😉):

| Оригинал | Перевод | Описание |
| ------------- |:-------------:| -----:|
| Addon | расширение / дополнение | В зависимости от контекста
| CLI | CLI | без перевода |
| Deployment | Развёртывание (Deployment) | Перевод + оригинальное название. Возможно стоит транслитерировать и перевести как - **деплоймент** |
| Dockerfile | Dockerfile | без перевода |
| Google Compute Engine | Google Compute Engine | без перевода |
| kube-proxy | kube-proxy | без перевода |
| Kubelet | Kubelet | без перевода |
| Kubernetes | Kubernetes |  без перевода|
| Minikube | Minikube | без перевода |
| Node | узел | Перевод. Возможно стоит транслитерировать и перевести как - **нода** |
| Pod | Под  | транслитерация |
| PodDisruptionBudget | PodDisruptionBudget | без перевода |
| YAML | YAML | без перевода |

/cc @kubernetes/sig-docs-ru-owners @kubernetes/sig-docs-ru-reviews

**Comment by php-coder** [comment]
Code of conduct - Кодекс поведения

(или может быть "правила поведения"?)

**Comment by php-coder** [comment]
addon -- аддон

**Comment by php-coder** [comment]
> addon -- аддон

Есть предложение от @lex111 чтобы переводить addon как "дополнение": 
https://github.com/kubernetes/website/pull/18611#discussion_r365460547

**Comment by lex111** [comment]
Транслитерацию тут точно не нужно использовать - либо "расширение", либо "дополнение". Хотя мне больше нравится первый раз, тем более ведь нет разницы в данном случае?

**Comment by Potapy4** [comment]
> Транслитерацию тут точно не нужно использовать - либо "расширение", либо "дополнение". Хотя мне больше нравится первый раз, тем более ведь нет разницы в данном случае?

мне кажется, тут зависит от контекста, но в целом ОК использовать расширение/дополнение

**Comment by lex111** [comment]
А почему в зависимости от контекста? Лучше выбрать что-то одно.
