### ISSUE TITLE
zh-1.17:There are some problems in document translation on the official website of kubernetes.

### ISSUE THREAD

**Issue by yuxiaobo96** [kubernetes/website#18593]
**This is a Bug Report**

**Problem:**
1. There are two identical documents in the **scheduling** drop-down bar in the left navigation bar of the **concept**, the links are:
https://kubernetes.io/zh/docs/concepts/scheduling/
2. The link in the `kube-scheduler.md` document should add `zh` to make it jump to the Chinese translation page. This document links to:
https://github.com/kubernetes/website/edit/master/content/zh/docs/concepts/scheduling/kube-scheduler.md

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tanjunchen** [comment]
@yuxiaobo96  
maybe you can focus con https://github.com/kubernetes/website/issues/18403
