### ISSUE TITLE
German localization is missing code of conduct

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18601]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/de/community/code-of-conduct/ is a missing page. This page is important because it provides the CNCF code of conduct, and that is an important element of an inclusive community.

**Proposed Solution:**
- Add German code of conduct page to website

**Page to Update:**
https://kubernetes.io/de/community/code-of-conduct/

**Additional Information:**
/priority important-soon
/language de
/kind bug

**Comment by alexzimmer96** [comment]
Has been fixed with #18981

**Comment by sftim** [comment]
Thanks for the update @alexzimmer96 
/close
