### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by dwschulze** [kubernetes/website#18612]
I installed kubectl and minikube as shown on https://kubernetes.io/docs/tasks/tools/install-minikube/.  When I start minikube with --vm-driver=none (I'm running on a virtual machine) I get this error:

$ sudo minikube start --vm-driver=none 
😄  minikube v1.6.2 on Ubuntu 19.10
✨  Selecting 'none' driver from user configuration (alternates: [])
⚠️  Specified Kubernetes version 1.10.0 is less than the oldest supported version: v1.11.10
💣  Sorry, Kubernetes 1.10.0 is not supported by this release of minikube

Is this a problem with Ubuntu 19.10, or with running minikube on a virtual machine?

**Comment by dwschulze** [comment]
It looks like the problem was that I had an old /root/.minikube directory.  Once I removed that directory minikube tried but failed to start with this error:

Error starting cluster: running cmd: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": exit status 1
stdout:
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk

stderr:
W0110 13:53:06.531592    6051 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0110 13:53:06.532094    6051 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0110 13:53:06.533419    6051 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0110 13:53:06.533440    6051 validation.go:28] Cannot validate kubelet config - no validator is available
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error
To see the stack trace of this error execute with --v=5 or higher


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-addon-manager ["c7ccb7eb00cc"]:
    error: You must be logged in to the server (error when retrieving current configuration of:
    error: You must be logged in to the server (the server has asked for the client to provide credentials)
    error: You must be logged in to the server (the server has asked for the client to provide credentials)
❌  Problems detected in kube-apiserver ["c91043e54554"]:
    I0110 20:52:44.283421       1 log.go:172] http: TLS handshake error from 127.0.0.1:47838: remote error: tls: bad certificate
    I0110 20:52:44.483603       1 log.go:172] http: TLS handshake error from 127.0.0.1:47846: remote error: tls: bad certificate
    I0110 20:52:44.549909       1 log.go:172] http: TLS handshake error from 127.0.0.1:47848: remote error: tls: bad certificate

**Comment by RA489** [comment]
@dwschulze can you please provide these details to replicate the issue further.
The exact minikube start command line used
The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.
The full output of minikube logs
