### ISSUE TITLE
Something broken with netlify preview?

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#18619]
**This is a Bug Report**

**Problem:**
Not each PR shown netlify.

**Proposed Solution:**
I don't know.

**Page to Update:**
For example, PR https://github.com/kubernetes/website/pull/18613 did not show.

**Comment by sftim** [comment]
I see a preview at https://deploy-preview-18613--kubernetes-io-master-staging.netlify.com/

Maybe either GitHub or Netlify experienced a glitch?

I believe you @Colstuwjx that this was missing; now the preview has turned up I will add:
/triage not-reproducible

**Comment by Colstuwjx** [comment]
Nope, I mean the netlify bot didn't add comment in PRs, like this PR #18594, it did:

![image](https://user-images.githubusercontent.com/3972545/72212408-63509700-3516-11ea-9f7a-f0c3717b3bec.png)

so I wonder if there is something made netlify bot unhappy, and didn't leave comment anymore.

**Comment by Colstuwjx** [comment]
I found that the bot settings should be configured by github settings, see: https://docs.netlify.com/site-deploys/notifications/#github-pull-request-comments.

I'm not sure whether there is github netlify app logs for this, maybe we could trace why it didn't send comments for some PRs, it should be netlify issue.

As it's low priority thing, I just leave this comment, and let it go, since we still could get the preview url from the last CI step.

Thanks.

**Comment by zacharysarah** [comment]
Looking at netlify, the build configuration should be adding comments with build previews:

<img width="50%" alt="Screen Shot 2020-01-18 at 6 30 47 PM" src="https://user-images.githubusercontent.com/3210446/72673550-e5faba00-3a20-11ea-9b52-7ab167b444d1.png">

I've done the simplest thing possible to remedy the error: removed the setting and re-added it. 

Please comment on whether subsequent PRs feature comments following successful netlify builds.

**Comment by Colstuwjx** [comment]
Hi @zacharysarah ,

I have been checked some new coming PRs, now the new pushing commit will trigger adding or editing a comment from netlify bot, see #18772 , #18773  , #18774 , #18775 .

I still could NOT find out the root cause, but it seems fixed!
