### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by aslam711** [kubernetes/website#18616]
**This is a Bug Report**

**Problem:**
`$ minikube addons enable heapster
*
X enable failed: property name "heapster" not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose`
**Proposed Solution:**
Change to a different add in option

**Page to Update:**
https://kubernetes.io/...

**Comment by php-coder** [comment]
It seems like the same issue as https://github.com/kubernetes/website/issues/18420#issuecomment-570246522
