### ISSUE TITLE
EndpointSlice concept prioritised ahead of Service

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18628]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/services-networking/ lists the EndpointSlice concept before Service.

Although the [Service page needs work](https://github.com/kubernetes/website/issues/14770), the current page about Service should come before the page about EndpointSlice, which is still beta and only partly activated by default.

**Proposed Solution:**
Revise the EndpointSlice page to have a `weight` that is higher than the Service page. See https://github.com/kubernetes/website/blame/55ee59477ec2b82df778b16e4293ecc89bdacdb3/content/en/docs/concepts/services-networking/endpoint-slices.md#L11 for the line that needs tweaking.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/

**Kubernetes Version:**
v1.18

**Additional Information:**
/language en

**Comment by sftim** [comment]
This _is_ a good first issue; if you've already had a pull request or two merged, I recommend leaving this one so that it's saved for a new contributor.

**Comment by zacharysarah** [comment]
@sftim Thanks for triaging with an eye for new contributors! 🌟

**Comment by makiw** [comment]
@sftim I'd like to work on this issue.

**Comment by sftim** [comment]
@makiw it'll be great to have your input
Have you already seen https://k8s.io/docs/contribute/?

**Comment by makiw** [comment]
Yes, I've read the docs and signed CLA already.

**Comment by makiw** [comment]
> @sftim I'd like to work on this issue, as a new contributor.

Retract my application as it seem I haven't meet some of requirements described in https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by rahulrai-in** [comment]
If it is okay, I would like to take this up. Thanks.

**Comment by omkensey** [comment]
This also looks like maybe it affects the rendering of the main Kubernetes web page at https://kubernetes.io/ also, actually -- under Features, EndpointSlices is listed before Service Topology (in fact EndpointSlices is the very first feature listed).

**Comment by rahulrai-in** [comment]
Thanks for pointing that out @omkensey. I will put that list in the same sequence as documentation. I am planning to work on it this weekend.

**Comment by ashishsingh2k8** [comment]
@rahulrai-in are you working on this issue? if not I would like to take this.

Please let me know

**Comment by rahulrai-in** [comment]
@ashishsingh2k8 I planned to work on it during my break but couldn't find much time to tend to it. Please feel free to take this up. I will circle back to this issue on March 1 when I have some capacity to spare. Thanks.

**Comment by rahulrai-in** [comment]
Hi, @ashishsingh2k8 I am back from my holidays. Are you still working on this issue or would you like me to take it forward? Thanks.

**Comment by ashishsingh2k8** [comment]
You please take it,

**Comment by sftim** [comment]
@prasadkatti I noticed you were just working in this area - would you like to pick this issue up as well?

**Comment by prasadkatti** [comment]
Sure. :)
