### ISSUE TITLE
Issue with k8s.io/zh/docs/reference/access-authn-authz/admission-controllers/

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/website#18623]
**This is a Bug Report**

**Problem:**

This page is outdated. There have been lots of updates in the English version.

**Proposed Solution:**

Update it with the latest version.

**Page to Update:**
https://kubernetes.io/...

**Comment by ydcool** [comment]
ref: https://github.com/k8smeetup/website-tasks/issues/3531

**Comment by tanjunchen** [comment]
@gavinfish
any progress?

**Comment by gavinfish** [comment]
@tanjunchen 
No, do you want to  take this up?

**Comment by tanjunchen** [comment]
No, I have take another one.

**Comment by gorda** [comment]
I updated this doc in [pr#19595](https://github.com/kubernetes/website/pull/19595)

**Comment by tanjunchen** [comment]
@gorda thanks
you can close this issue once  19595 is merged

**Comment by tengqm** [comment]
/close
done.
