### ISSUE TITLE
Issue with k8s.io/docs/tutorials/online-training/overview/

### ISSUE THREAD

**Issue by ravvas** [kubernetes/website#18636]
**This is a Bug Report**

Request to add AWS EKS detailed workshop URL

**Problem:**
Recently I came across a public online self paced AWS EKS workshop available. It is really good.
URL : https://eksworkshop.com/
**Proposed Solution:**
Can we add the URL to list of kuberenetes trainings available. 
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Seems reasonable (although it's also relevant to https://github.com/kubernetes/enhancements/pull/1327)
/priority backlog

**Comment by Cynthia1981** [comment]
double Dupliquer de #
