### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by shacharSilbert** [kubernetes/website#18655]
**This is a Bug Report**

**Problem:**
According to the "Cron Job Limitations" section:
"A cron job creates a job object about once per execution time of its schedule. We say “about” because there are certain circumstances where two jobs might be created, or no job might be created. We attempt to make these rare, but do not completely prevent them. Therefore, jobs should be idempotent."

It is not exactly understandable whether if I set my concurrencyPolicy to "Forbid" - Whether I will still maybe get concurrency runs.
i.e. I do not understand whether the "...two jobs might be created..." above is due to:
1. Cron scheduling twice at the same exact moment, disregarding parallelism and concurrencyPolicy.
Or
2. Cron scheduling more than once in the CronTab schedule set, but still including the concurrencyPolicy, and therefore just missing one slot, if it is set to "Forbid"

**Proposed Solution:**
Add explanation about what happens with this "about" issue in the cases of Forbid or Replace concurrencyPolicy

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by sftim** [comment]
Makes sense
/priority backlog

**Comment by shacharSilbert** [comment]
@sftim I should add that I still haven't found a proper solution for this question in my many questions posted online, do you have any idea if #1 or #2 is the correct answer?

**Comment by sftim** [comment]
@shacharSilbert I haven't looked into how the cronjob controller works into that level of detail.

**Comment by sftim** [comment]
Relevant to #4500
