### ISSUE TITLE
Improvement for k8s.io/zh/docs/tasks/debug-application-cluster/audit/

### ISSUE THREAD

**Issue by jsonpang** [kubernetes/website#18672]
don‘t know how to do 
how to setup audit as newbe

**Comment by sftim** [comment]
The English page at https://kubernetes.io/docs/tasks/debug-application-cluster/audit/ looks more like a concept document with a [task](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#log-collector-examples) at the end.

I think it'd be worth splitting this page up into a concept page and a (new) task page.

**Comment by sftim** [comment]
New concept page could be, eg, https://k8s.io/docs/concepts/security/audit/

**Comment by jsonpang** [comment]
close
