### ISSUE TITLE
https://k8s.io/pl/docs/ does not redirect to https://kubernetes.io/pl/docs/home/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18686]
**This is a Bug Report**

**Problem:**
https://k8s.io/pl/docs/ does not redirect to https://kubernetes.io/pl/docs/home/

Try this with other localizations and you often get redirected (not all localizations have that redirect configured).

**Proposed Solution:**
Initially: investigate. Maybe there is a step missing to check new localizations?

**Page to Update:**
https://kubernetes.io/pl/docs/

**Additional Information:**
/language pl
/priority backlog

**Comment by gavinfish** [comment]
It seems that https://k8s.io/zh/docs/ also does not redirect.

**Comment by zacharysarah** [comment]
As it turns out, each localization requires a redirect: 
- https://github.com/kubernetes/website/commit/f44c14927bcc232aaa6e2a8aa990d1c0408af02a
- https://github.com/kubernetes/website/pull/14586

That's definitely worth documenting in how to initialize a localization.
