### ISSUE TITLE
https://k8s.io/pl/ looks incomplete

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18680]
**This is a Bug Report**

**Problem:**
~https://k8s.io/pl/ doesn't look right~
~I'd thought that the [preview](https://deploy-preview-18659--kubernetes-io-master-staging.netlify.com/pl/) for #18659 looked OK but in fact it doesn't and neither does the live site.~
https://k8s.io/pl/ is not yet complete.

**Proposed Solution:**
Complete localization work for https://k8s.io/pl/

**Page to Update:**
https://kubernetes.io/pl/

/language pl
/priority important-longterm

**Comment by sftim** [comment]
I think this is intended and that future work will add to the index page.

**Comment by mfilocha** [comment]
https://kubernetes.io/pl/ is ready.

**Comment by sftim** [comment]
:tada:
/close
