### ISSUE TITLE
kubernetes.io/security forwards to the chinese security policy

### ISSUE THREAD

**Issue by tallclair** [kubernetes/website#18691]
**This is a Bug Report**

**Problem:**
kubernetes.io/security redirects to https://kubernetes.io/zh/docs/reference/issues-security/security/, but should redirect to https://kubernetes.io/docs/reference/issues-security/security/

**Comment by zacharysarah** [comment]
I seem to recall we’ve seen this before. @kubernetes/sig-docs-zh-owners Can we please make sure this doesn’t propagate to future versions?

**Comment by kbhawkey** [comment]
https://kubenetes.io/security -> https://kubernetes.io/zh/docs/reference/issues-security/security/
https://kubernetes.io/cve -> https://kubernetes.io/zh/docs/reference/issues-security/issues/

**Comment by tanjunchen** [comment]
@gavinfish  @tengqm 
see  https://github.com/kubernetes/website/pull/18727#discussion_r372039637
this seems that it has been resolved . Agree?

**Comment by gavinfish** [comment]
@tanjunchen  I think so. 
@kbhawkey do you have any concern to close it?

**Comment by kbhawkey** [comment]
Hi. Thanks for checking. The links look good. Feel free to close.
