### ISSUE TITLE
CSS colors: both fg & bg must be explicitly defined

### ISSUE THREAD

**Issue by 532910** [kubernetes/website#18697]
**This is a Bug Report**

**Problem:**
![image](https://user-images.githubusercontent.com/14617699/72408773-e5d69200-3774-11ea-936b-3584e0da219b.png)
![image](https://user-images.githubusercontent.com/14617699/72408781-e7a05580-3774-11ea-82ad-555f9b6664d5.png)

**Proposed Solution:**
Both fg & bg must be explicitly defined

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
For clarity:
/retitle CSS colors: both fg & bg must be explicitly defined

**Comment by ydcool** [comment]
Could you provide some more details about how to repeat this problem? like what's your OS/Browser or any browser plugins you're using? thanks

**Comment by 532910** [comment]
Why does it matter? Just swap the default black foreground and white background color.
My setup is firefox with `$GTK_THEME=Adwaita:dark` and ``browser.display.use_system_colors=true`
But you can achieve this with  
```css
* {
	color: gray;
	background-color: black;
}
```
in `userContent.css`

**Comment by 532910** [comment]
Is any update there?

**Comment by sftim** [comment]
I'll mark this as
/area web-development

@532910 nearly all contributions to Kubernetes are from volunteers. So progress here pretty much depends on someone looking for an issue to pick up and then contributing a fix

That label might help make it a bit more discoverable.

**Comment by 532910** [comment]
Looks fine now.
