### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by yangatgithub** [kubernetes/website#18714]
**This is a Bug Report**

**Problem:**

Are below statements correct? There are some discussions in the Internet that the "node" should be the "pod", i.e. ReadWriteOnce only allows a volume be mounted as read-write by a single pod. 

ReadWriteOnce – the volume can be mounted as read-write by a single node
ReadOnlyMany – the volume can be mounted read-only by many nodes
ReadWriteMany – the volume can be mounted as read-write by many nodes

https://github.com/kubernetes/kubernetes/issues/60903

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by ydcool** [comment]
It's more likely kind of bug, IMO

**Comment by Colstuwjx** [comment]
Like @msau42 [said](https://github.com/kubernetes/kubernetes/issues/60903#issuecomment-377086770), the `mount` by node is a semantic for `node attach`, not pod mount.

TBH, I also get confused when I read our [PV page](https://kubernetes.io/docs/concepts/storage/persistent-volumes), the lifecycle of PV is really not well documented, we have been used `Provisioning -> Binding -> Using` for describing [PV lifecycle](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim), and even describe accessMode with `mount` such terminology. So how it works is still a question for our users...

Fortunately, we are moving to [CSI](https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/), and CSI is well designed for volume lifecycle, features, how it integrated for each provider, how to write plugins.

I think it's reasonable to change this part, make it more clear for explaining the PV lifecycle, how it works, and when pod bind to volume etc. The target page of this issue should be https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes. 

/sig docs
/kind documentation
/language en

**Comment by Colstuwjx** [comment]
sorry, should be
/sig storage
