### ISSUE TITLE
Use monospace for filesystem paths in Minikube setup guide

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18710]
**This is an enhancement request**

**What would you like to be added**
I'd like https://kubernetes.io/docs/setup/learning-environment/minikube/#mounted-host-folders to use monospace (`like this`) text for the paths in the two rightmost columns in the table:
- HostFolder
- VM

**Why is this needed**
Improved styling. It's a minor thing that's nice to have.

**Comments**
/kind cleanup
/language en

**Comment by sftim** [comment]
If anyone would like to work on this, please feel free to open a pull request.

**Comment by imbhuvnesh** [comment]
Hey @sftim, I would like to work on this.

**Comment by sftim** [comment]
Anyone who'd like to open a PR that addresses this issue is welcome to. Dive in!

**Comment by JubayerJoy** [comment]
I am working on this, will submit a PR shortly. 🚀
