### ISSUE TITLE
Issue with k8s.io/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/website#18718]
This is more of a issue in general. Docs about things like pod-security-policy should have a link to the api reference for that object type. Its hard to go find the actual api reference from the document.

**Comment by Colstuwjx** [comment]
Yes, you are right, inside this page, we didn't link the [reference page](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podsecuritypolicy-v1beta1-policy), it should be.

/assign
/sig docs
/kind documentation
/language en
