### ISSUE TITLE
Shall we link ephemeral container within pod troubleshooting pages

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#18720]
**This is a Feature Request**

**What would you like to be added**
add more content with introducing ephemeral container within https://kubernetes.io/docs/tasks/debug-application-cluster/debug-pod-replication-controller/#my-pod-is-crashing-or-otherwise-unhealthy.

**Why is this needed**
It's really hard to trigger the root cause with a crash-backoff container, and I have seen our page about this part, see https://kubernetes.io/docs/tasks/debug-application-cluster/debug-pod-replication-controller/#my-pod-is-crashing-or-otherwise-unhealthy. But it may missed ephemeral container, which is a new **alpha** feature introduced in k8s 1.16. With the help of ephemeral container, we could dive into crash-backoff container, and find out the root cause. So I'd like to add this part inside our pod troubleshooting page.

**Comments**

I'm not sure whether it's the time to do this, since ephemeral container is alpha state, we may change it or deprecate it.

**Comment by sftim** [comment]
I don't see a big problem with adding that hyperlink.
/priority backlog
/language en
