### ISSUE TITLE
docs/reference/generated/kubernetes-api group names truncated

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/website#18731]
**This is a Bug Report**

**Problem:**

When developing a new library that consumes kubernetes apis, I don't want to guess what the fully qualified API group is.  For example, "Secrets".  That is in the group "core.k8s.io/v1" (as far as I know, that might not even be right).  Most items in that reference are missing the fully qualified group name for no good reason.

Good example: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#csinode-v1-storage-k8s-io

Bad example: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#secret-v1-core

Is it just k8s.io/v1 for secrets, or is it core.k8s.io/v1 for Secrets.  I've dug all through the code looking for a concrete answer, there is none to be found.

**Proposed Solution:**

Document the fully qualified API groups.

**Page to Update:**

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/

**Comment by tengqm** [comment]
Does this help? https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups

The "core" group IS SPECIAL.
