### ISSUE TITLE
Link for mail list inside contribute localization looks odd

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#18738]
**This is a Bug Report**

**Problem:**
See https://kubernetes.io/zh/docs/contribute/intermediate/#%E6%9C%AC%E5%9C%B0%E5%8C%96%E5%86%85%E5%AE%B9 :

```
并在 [kubernetes-sig-docs 邮件列表]kubernetes-sig-docs mailing list #sig-docs 上询问
```

**Proposed Solution:**
Correct the link.

**Page to Update:**
https://kubernetes.io/zh/docs/contribute/intermediate/#%E6%9C%AC%E5%9C%B0%E5%8C%96%E5%86%85%E5%AE%B9

/language zh
/good-first-issue

**Comment by ydcool** [comment]
Yes that might be a mistake, I'll help to fix this, thank you for pointing this out.
/assign
