### ISSUE TITLE
Outdated release notes

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18730]
**This is a cleanup issue**

**Problem:**
[Release notes](https://kubernetes.io/docs/setup/release/notes/) are at v1.17.0
whereas [v1.17.1](https://github.com/kubernetes/kubernetes/releases/tag/v1.17.1) is out.

**Proposed Solution:**
Publish updated release notes.

**Page to Update:**
https://kubernetes.io/docs/setup/release/notes/

**Kubernetes Version:**
v1.17.1

**Additional Information:**
/kind cleanup
/sig release

**Comment by prankul88** [comment]
@sftim As I see in the previous release documentation [(v1.16)](https://v1-16.docs.kubernetes.io/docs/setup/release/notes/), it hasn't covered the minor releases.
So was curious is it necessary ?

**Comment by sftim** [comment]
I don't see an update as essential. Having current release notes is certainly nice to have.
Perhaps the website build process could automatically fetch the latest release notes? I think that would help.

**Comment by prankul88** [comment]
>Perhaps the website build process could automatically fetch the latest release notes? 
@sftim Ya that would be ideal.

**Comment by sftim** [comment]
Fixed
/close
