### ISSUE TITLE
About the description accuracy of the object name.

### ISSUE THREAD

**Issue by llamerada-jp** [kubernetes/website#18746]
**This is a Feature Request**

**What would you like to be added**

In the following pages, I thought about describing the actual restrictions for the name of each object.
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names

For example, How about you that the following contents described in `Note`.

> For example, even basic objects have the following restrictions.
> 
> `Pod`, `Deployment` etc:
> 
> * Begin and terminate with digits or lower case letters.
> * Do not use `.` continuously.
> 
> `Service`, `ClusterName`:
> 
> * Begin with lower case letters.
> * Terminate with digits or lower case letters.
> * `.` is not allowed.
> * Up to 63 characters.
> 
> `Namespace`:
> 
> * Begin and terminate with digits or lower case letters.
> * `.` is not allowed.
> * Up to 63 characters.

**Why is this needed**

When I was developing a function to create objects (Persistent Volumes), I referred to the content on the document to check the restrictions of names. But I noticed that it was different from the actual restrictions while testing it. I could not found the document about actual restrictions of names. And I know about it from error messages and source codes.

**Comments**

I don't know the context of the current document, so I'm wondering if that fix is ​​needed.
It is difficult to track changes to the program, so do we need to avoid describing details?

**Comment by tengqm** [comment]
There are different constraints to object names. Because of the way resources are defined and implemented and also way the API spec is generated ... constraints on `metadata.name` are very difficult to capture.

**Comment by sftim** [comment]
It sounds like this is a request to enhance https://k8s.io/docs/concepts/overview/working-with-objects/names/ and perhaps also to have more pages link to that.

@llamerada-jp does that sound like I have got that right?

**Comment by sftim** [comment]
https://k8s.io/docs/concepts/overview/working-with-objects/names/ doesn't really make it clear that you can have different objects with the same name, so long as those objects are in a different namespace.

**Comment by sftim** [comment]
What priority should this issue have? The current page looks outright incorrect.
/kind bug

**Comment by llamerada-jp** [comment]
@tengqm @sftim 
Thank you for your reply.

> It sounds like this is a request to enhance https://k8s.io/docs/concepts/overview/working-with-objects/names/ and perhaps also to have more pages link to that.
That's right. But I convinced that it is difficult because of my guess and tengqm's reply.
So I'm going to withdraw.

I didn't consider namespace.
It is explained on the page of namespace. I think it is enough.
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#when-to-use-multiple-namespaces
