### ISSUE TITLE
horizontal scroll for navigation 

### ISSUE THREAD

**Issue by 532910** [kubernetes/website#18759]
navigation doesn't width-fit:

![image](https://user-images.githubusercontent.com/14617699/72660446-423cea00-39df-11ea-933d-cd928d8796f1.png)

**Comment by sftim** [comment]
That's true, and it's something we should fix
/priority backlog

**Comment by Arhell** [comment]
resolve
/close

**Comment by 532910** [comment]
Really horizontal scroll doesn't go away but it looks significant better.
Possibly some arrows will help to understand that it's scrollable?

**Comment by Arhell** [comment]
I think not, as an example https://getbootstrap.com/ is implemented similarly

**Comment by 532910** [comment]
> getbootstrap.com is implemented similarly

Why does it matter?


To be clear: I mean left and right arrow or some markers that help to understand that menu is scrollable. For example:
https://asmyshlyaev177.github.io/react-horizontal-scrolling-menu/
https://reactjsexample.com/horizontal-scrolling-menu-component-for-react/
https://www.jqueryscript.net/menu/Responsive-Scrolling-Navigation-Menu-With-jQuery-jQuery-UI.html

**Comment by celestehorgan** [comment]
addressed in https://github.com/kubernetes/website/pull/20874.

@sftim can we close this?
