### ISSUE TITLE
unreadable gapless navigation in mobile view

### ISSUE THREAD

**Issue by 532910** [kubernetes/website#18758]
https://kubernetes.io/docs/concepts/

![image](https://user-images.githubusercontent.com/14617699/72660429-d5c1eb00-39de-11ea-86cc-a972cb330dc5.png)
![image](https://user-images.githubusercontent.com/14617699/72660432-deb2bc80-39de-11ea-9470-a43fc1c21fe0.png)

**Comment by sftim** [comment]
Thanks @532910
/kind bug

**Comment by 532910** [comment]
Fixed now!
