### ISSUE TITLE
Tasks catalog is not aligned with its index page TOC

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#18755]
**This is a Bug Report**

**Problem:**
When I visit the tasks index page, I have seen a catalog for navigation:

![image](https://user-images.githubusercontent.com/3972545/72656708-36015e80-39d8-11ea-9710-895ca1938879.png)

and the tasks index page also show me TOC which indicates the indexes and offers basic knowledge about what do we learn from this part:

![image](https://user-images.githubusercontent.com/3972545/72656724-5cbf9500-39d8-11ea-803a-98674dae42b2.png)

the question is these two things are NOT well aligned, I'm wondering whether we need to maintain the TOC of the tasks page by manually or just generates it from each detail catalog index's title and description.

**Proposed Solution:**
Maybe we could generate the toc from each catalog index's title and description, and on the foot, just adding the what's next by manually.

**Page to Update:**
https://kubernetes.io/docs/tasks/

/language en

**Comment by sftim** [comment]
Issue #21149 is similar

/remove-lifecycle rotten

**Comment by tengqm** [comment]
Let's track the issue using #8402 
/close
