### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/

### ISSUE THREAD

**Issue by mykevinjung** [kubernetes/website#18766]
**This is a Bug Report**

**Problem:**
I see the following message in the course.
> The READY column shows the ratio of CURRENT to DESIRED replicas

However, I do not see READY column.  This is what I see
```
$ kubectl get deployments
NAME                  DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kubernetes-bootcamp   1         1         1            1           1m
```

**Proposed Solution:**
Update the description accordingly based on the version of `kubectl`

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/

**Comment by ydcool** [comment]
Because the version of the kubectl you're using is too old ( see `kubectl version` )

**Comment by mykevinjung** [comment]
This is about online interactive page, not my local.

**Comment by ydcool** [comment]
Yes that page hasn't been updated for three years, and the interactive command line embedded with katacoda was outdated too. I'ill dig into it for some more information and possible solutions.


 
---Original---

**Comment by sftim** [comment]
/kind bug
/priority backlog
(but only barely; I think this is on the cusp of being /priority important-longterm)

**Comment by gsoria** [comment]
I've sent a [PR](https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/17) to update the step 1 of the [scenario](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/)

**Comment by BenHall** [comment]
Thanks @gsoria, this has been merged.

**Comment by sftim** [comment]
Fixed - thanks @mykevinjung, @BenHall & @gsoria 
/close
