### ISSUE TITLE
Issue with k8s.io/docs/reference/glossary/

### ISSUE THREAD

**Issue by mda-jobs** [kubernetes/website#18763]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by mda-jobs** [comment]
The glossary does not contain a definition for Kubernetes object, or Kubernetes master.

**Comment by sftim** [comment]
Good point @mda-jobs 
/priority backlog
/language en

We could possibly add a “master” for a synonym for “control plane”, and then in the entry for “control plane” explain the similarities and differences between the two terms.

**Comment by davivcgarcia** [comment]
I'll work on that!

/remove-help
/assign

**Comment by davivcgarcia** [comment]
@sftim and @mda-jobs: What about creating a `Node Role` entry explaining the concept and listing `master` and `worker` as most common values used on it?

**Comment by sftim** [comment]
Hmm. That term “master” has nuances (it's not as controversial as “slave”, but the implication is still there). Newer thinking seems to favor “control plane” rather than “master”.

So you can have nodes that also run the control plane.

Does that help guide how to approach this?

**Comment by davivcgarcia** [comment]
@sftim I understand your point, but may tools still uses `master` and `worker` for the `kubernetes.io/role` label (ex. `kubeadm`). Also, looks like we already have `Control Plane` covered in the glossary (https://kubernetes.io/docs/reference/glossary/?all=true#term-control-plane).

What about to refactor `Node` entry, explaining that nodes can also have a role label, and these are the most common values (and linking `master` to `control-plane`)?

**Comment by neolit123** [comment]
> I understand your point, but may tools still uses master and worker for the kubernetes.io/role label (ex. kubeadm)

the "master" node role is exclusive to deployers like kubeadm (+some others) and has been excluded from core k8s.
