### ISSUE TITLE
Issue with k8s.io/zh/docs/concepts/architecture/

### ISSUE THREAD

**Issue by Okabe-Kurisu** [kubernetes/website#18771]
**This is a Bug Report**

**Problem:**
it a copy of https://kubernetes.io/zh/docs/concepts/architecture/nodes/
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by gavinfish** [comment]
I think this is duplicated with #18737.

/language zh

**Comment by Okabe-Kurisu** [comment]
oh。。
