### ISSUE TITLE
PV status did not match previous introduction in https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection

### ISSUE THREAD

**Issue by duanwei33** [kubernetes/website#18789]
**This is a Bug Report**

**Problem:**

You can see that a PV is protected when the PV’s status is Terminating and the Finalizers list includes kubernetes.io/pv-protection too:

kubectl describe pv task-pv-volume
Name:            task-pv-volume
Labels:          type=local
Annotations:     <none>
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    standard
Status:          Available
Claim:
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        1Gi
Message:
Source:
    Type:          HostPath (bare host directory volume)
    Path:          /tmp/data
    HostPathType:
Events:            <none>

**Proposed Solution:**
I guess a PV with Terminating status(not Available) should be posted here to avoid confusion. 

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection

**Comment by Colstuwjx** [comment]
Yes, I think you are right, it should be a mistake.

/kind documentation
/language en
/assign
