### ISSUE TITLE
Issue with /docs/getting-started-guides/kops/

### ISSUE THREAD

**Issue by ofyaniv** [kubernetes/website#1878]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Incomplete documentation.

==============================
I1207 10:52:16.980411    5574 aws_cloud.go:510] Resolved image "ami-4bb3e05c"
I1207 10:52:16.991701    5574 launchconfiguration.go:276] Waiting for IAM to replicate
I1207 10:52:16.991810    5574 launchconfiguration.go:277] IAM error was ValidationError: Invalid IamInstanceProfile: masters.dev.continuousdelivery.io
        status code: 400, request id: 0e4c5053-bc95-11e6-9de9-0b765d4198a3
I1207 10:52:16.999078    5574 launchconfiguration.go:276] Waiting for IAM to replicate
I1207 10:52:16.999107    5574 launchconfiguration.go:277] IAM error was ValidationError: Invalid IamInstanceProfile: nodes.dev.continuousdelivery.io
        status code: 400, request id: 0e4dfd81-bc95-11e6-83ab-9b848675d14b
I1207 10:52:27.342301    5574 executor.go:68] Tasks: 49 done / 51 total; 2 can run
==============================

**Proposed Solution:**
**Ensure the user have the IAMFullAccess policy attached otherwise kops will fail to create the cluster.**

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/kops/

Ensure the user have the IAMFullAccess policy attached otherwise kops will fail to create the cluster.

**Comment by ofyaniv** [comment]
Ensure the user have the IAMFullAccess policy attached otherwise kops will fail to create the cluster.

**Comment by idvoretskyi** [comment]
ping @justinsb @kubernetes/sig-aws

**Comment by ofyaniv** [comment]
Hi Justin

It seems that the kops documentation is missing some prerequisite.

Thanks
 Ofer

**Comment by chrislovecnm** [comment]
Just noticed this.  Is this still an open issue?
