### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-scheduler/

### ISSUE THREAD

**Issue by tomklino** [kubernetes/website#18797]
**This is a Bug Report**

**Problem:**
All the flags regarding policy configuration (`--policy-config-file`, `--policy-configmap`, `--policy-configmap-namespace`, `--use-legacy-policy-config`) are marked as "DEPRECATED" but no alternative is documented, nor an explanation as to why they have been deprecated.

Also, I could not find in the docs a non-depreciated way to configure the scheduler policy.

There is no explanation as to why the mentioned flags have been deprecated 
**Proposed Solution:**
Document the reason and an alternative next to the deprecated policy flags, possibly add a flag to replace them.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler

**kubernetes version**
1.13 to 1.17 (at least)

**Comment by sftim** [comment]
The reference documentation is built automatically from code inside https://github.com/kubernetes/kubernetes/tree/master/cmd/kube-scheduler/app

I think it would make sense to track this issue in [kubernetes/kubernetes]https://github.com/kubernetes/kubernetes).
