### ISSUE TITLE
Add dark mode for docs

### ISSUE THREAD

**Issue by vivekjainx86** [kubernetes/website#18798]
Please add dark mode for docs

**Comment by gavinfish** [comment]
Ref #7724

/help

**Comment by gavinfish** [comment]
@vivekjainx86 thanks for sharing your idea here. I also prefer to enable dark mode at night.

Please update the title here since it is really confusing.

**Comment by meysam81** [comment]
+1 for this :+1: 

/reopen

**Comment by sftim** [comment]
Let's track this via https://github.com/kubernetes/website/issues/25061
/close not-planned

**Comment by Koshiz** [comment]
Quick fix is that to install Dark Reader extension https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?pli=1 and turn it on on the k8s docs. Given link is to the chrome extension. Hope they will add a cool dark mode to the documentations. Till then enjoy the extension

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/46844
