### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by alexcpn** [kubernetes/website#18792]
**Problem:**
I upgraded to  the latest minikube in Ubunutu ; However, I am not able to find the latest stable Kubernetes (https://storage.googleapis.com/kubernetes-release/release/stable.txt)  in it.
```
minikube start  --kubernetes-version v1.17.0
Invalid Kubernetes version.
The following Kubernetes versions are available when using the localkube bootstrapper: 
	- v1.10.0
	- v1.9.4
	- v1.9.0
	- v1.8.0
	- v1.7.5
	- v1.7.4
	- v1.7.3
	- v1.7.2
	- v1.7.0
	- v1.7.0-rc.1
	- v1.7.0-alpha.2
	- v1.6.4
	- v1.6.3
	- v1.6.0
	- v1.6.0-rc.1
	- v1.6.0-beta.4
	- v1.6.0-beta.3
	- v1.6.0-beta.2
	- v1.6.0-alpha.1
	- v1.6.0-alpha.0
	- v1.5.3
	- v1.5.2
	- v1.5.1
	- v1.4.5
	- v1.4.3
	- v1.4.2
	- v1.4.1
	- v1.4.0
	- v1.3.7
	- v1.3.6
	- v1.3.5
	- v1.3.4
	- v1.3.3
	- v1.3.0
```

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

Kuberenets v1.17 is not present
Client
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by alexcpn** [comment]
If I unistall /remove the old minikube and install fresh  it is working. Please add that as a suggestion (minikube upgrade page is in a worse state)

**Comment by sftim** [comment]
@alexcpn if there were an “upgrade Kubernetes in Minikube” page, and https://k8s.io/docs/tasks/tools/install-minikube/ linked there, do you think that would be viable solution?

**Comment by alexcpn** [comment]
Yes; that would be fine. Since this is for experimental work, no one really minds deleting the existing and installing things anew; ( for users who need their old k8s vms working with new minikube etc, if upgrade supports that great, but I believe with new  kubectl, they will  have compatibility problems with the old vms or vice versa)
