### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/service-access-application-cluster/

### ISSUE THREAD

**Issue by daleangus** [kubernetes/website#18802]
Is the documentation correct? Just noticed that this doesn't work.

`curl http://public-node-ip:node-port
Connection refused

But this does 

curl http://public-node-ip:8080.

**Comment by gavinfish** [comment]
@daleangus the `node-port` is just a placeholder here, you need to update it with your own value like 8080.

**Comment by daleangus** [comment]
The instructions are confusing. 
From step 5.

Name:                   example-service
Namespace:              default
Labels:                 run=load-balancer-example
Annotations:            <none>
Selector:               run=load-balancer-example
Type:                   NodePort
IP:                     10.32.0.16
Port:                   < unset > 8080/TCP
TargetPort:             8080/TCP
**NodePort:               < unset > 31496/TCP**
Endpoints:              10.200.1.4:8080,10.200.2.5:8080
Session Affinity:       None
Events:                 < none >
**Make a note of the NodePort value for the service. For example, in the preceding output, the NodePort value is 31496.**

Then on step 9
**Use the node address and node port** to access the Hello World application:
curl http://< public-node-ip >:< node-port >


The instructions should refer to TargetPort for the example to work.

**Comment by Kartik494** [comment]
@daleangus in my environment i got the result as expected by curl service using `curl http://< public-node-ip >:< node-port >` as i have multinode cluster and my pod is deploying in worker node so when i hit service from my worker node, i got the expected result i.e Hello Kubernetes!
Thanks

**Comment by daleangus** [comment]
Thanks @Kartik494 . 
I'll just share my notes here. Please let me know if you find anything wrong.

angus@ubuntu18-k8s-master:$ kubectl describe services example-service
Name:                     example-service
Namespace:                default
Labels:                   < none >
Annotations:              < none >
Selector:                 run=load-balancer-example
Type:                     NodePort
IP:                       10.109.230.128
Port:                     < unset >  8080/TCP
TargetPort:               8080/TCP
NodePort:                 < unset >  31156/TCP
Endpoints:                10.107.200.195:8080,10.107.39.130:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   < none >

angus@ubuntu18-k8s-master:$ kubectl get pods --selector="run=load-balancer-example" --output=wide
NAME                           READY   STATUS    RESTARTS   AGE   IP               NODE                 NOMINATED NODE   READINESS GATES
hello-world-77b74d7cc8-2nd48   1/1     Running   0          69s   10.107.39.130    ubuntu18-k8s-node1   < none >           < none >
hello-world-77b74d7cc8-ws2sn   1/1     Running   0          69s   10.107.200.195   ubuntu18-k8s-node2   < none >           < none >

angus@ubuntu18-k8s-master:$ curl http://10.107.39.130:31156
**curl: (7) Failed to connect to 10.107.39.130 port 31156: Connection refused**

angus@ubuntu18-k8s-master:$ curl http://10.107.39.130:8080
Hello Kubernetes!

angus@ubuntu18-k8s-master:$ curl http://10.109.230.128:8080
Hello Kubernetes!

angus@ubuntu18-k8s-master:$ curl http://10.109.230.128:31156
**curl: (7) Failed to connect to 10.109.230.128 port 31156: Connection timed out**

angus@ubuntu18-k8s-master:$ kubectl get nodes
NAME                  STATUS   ROLES    AGE   VERSION
ubuntu18-k8s-master   Ready    master   27h   v1.17.1
ubuntu18-k8s-node1    Ready    < none >   26h   v1.17.1
ubuntu18-k8s-node2    Ready    < none >   26h   v1.17.1

angus@ubuntu18-k8s-master:$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                          READY   STATUS    RESTARTS   AGE
default       hello-world-77b74d7cc8-2nd48                  1/1     Running   0          10m
default       hello-world-77b74d7cc8-ws2sn                  1/1     Running   0          10m
kube-system   calico-kube-controllers-5b644bc49c-lrqrg      1/1     Running   0          26h
kube-system   calico-node-fm6k6                             1/1     Running   0          26h
kube-system   calico-node-gsq8t                             1/1     Running   0          26h
kube-system   calico-node-p86zh                             1/1     Running   0          26h
kube-system   coredns-6955765f44-7n9mn                      1/1     Running   0          27h
kube-system   coredns-6955765f44-w8xkp                      1/1     Running   0          27h
kube-system   etcd-ubuntu18-k8s-master                      1/1     Running   1          27h
kube-system   kube-apiserver-ubuntu18-k8s-master            1/1     Running   1          27h
kube-system   kube-controller-manager-ubuntu18-k8s-master   1/1     Running   9          27h
kube-system   kube-proxy-dn9zz                              1/1     Running   0          26h
kube-system   kube-proxy-khtvs                              1/1     Running   0          27h
kube-system   kube-proxy-pfjtg                              1/1     Running   0          26h
kube-system   kube-scheduler-ubuntu18-k8s-master            1/1     Running   7          27h

**Comment by Kartik494** [comment]
@daleangus in curl http://< public-node-ip >:< node-port >,the public-node-ip is here refrenced to the ip of your node,so do give a try using your node-public-ip:31156.You are providing here Endpoints here rather than node-ip.
Example of my scenraio:-
root@kworker:/home/vagrant# kubectl describe svc example-service
Name:                     example-service
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 run=load-balancer-example
Type:                     NodePort
IP:                       10.96.204.209
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30760/TCP
Endpoints:                10.32.0.4:8080,10.32.0.5:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
root@kworker:/home/vagrant# ifconfig
.......
enp0s8    Link encap:Ethernet  HWaddr 08:00:27:cf:1b:6d  
          inet addr:172.30.64.10  Bcast:172.30.64.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fecf:1b6d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:129192 errors:0 dropped:0 overruns:0 frame:0
          TX packets:105326 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:55408096 (55.4 MB)  TX bytes:11273241 (11.2 MB)
........
root@kworker:/home/vagrant# curl http://172.30.64.10:30760
Hello Kubernetes!root@kworker:/home/vagrant# 
Thanks
