### ISSUE TITLE
Delete extensions/v1beta1 in docs

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#18809]
**This is a Feature Request**

Since v1.16, extensions/v1beta1 has been deleted and it should not be used in docs

**What would you like to be added**
The following pages should be edited due to this deletion.
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/overview/kubernetes-api.md
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/workloads/controllers/deployment.md
- [x] https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/workloads/controllers/replicaset.md
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/reference/access-authn-authz/admission-controllers.md
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/reference/kubectl/conventions.md
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/reference/using-api/api-overview.md
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/access-application-cluster/ingress-minikube.md
- [x] https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/manage-kubernetes-objects/declarative-config.md
- [x] https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/manage-kubernetes-objects/imperative-config.md

**Why is this needed**
extensions/v1beta1 is deleted in 1.16

**Comments**

**Comment by sftim** [comment]
/kind cleanup

/priority important-soon
(I think)

**Comment by sftim** [comment]
If you are looking at this as potentially something to contribute to, it's OK to suggest a PR that fixes only one page, or only some pages.
If you do that please mention “Partial fix for issue #18809” in the description of your PR.

**Comment by gavinfish** [comment]
@makocchi-git thanks for contribution here. 
Could you please share which pages would you take? Let us make the assignment more clear and help other contributors easily start their work.

**Comment by makocchi-git** [comment]
@gavinfish Thank you for your comments.
I wrote the target file into PR titles.
And I will write to the comment about netlify demo pages and original pages to enable checking the diff easily.
