### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by ryan-g2** [kubernetes/website#18824]
The setup guide for Weave Net does not specify to supply a CIDR command to the kubeadm init command when launching a cluster.

I am on ubuntu 19.10 running 3 VMs of Ubuntu 18.04.  Without the CIDR command the weave-net pod would always crash and keep my node in a NotReady state.  After supplying `--pod-network-cidr=10.32.0.0/12` to kubeadm init all my pods and nodes could create as expected.

NOTE:  I also set my iptables, ip6tables, arptables, and ebtables on my 19.10 OS to use legacy after reading this (https://github.com/weaveworks/weave/issues/3465).    Not sure if this had anything to do with the fix after supplying the CIDR (This did not work when switching to legacy alone).

I found this solution here (https://github.com/weaveworks/weave/issues/3420#issuecomment-437960093).  A commenter says this info is supplied in the WeaveNet docs, but I did not find any reference to them.

Suggested Fix:  In the Weave pod network section, add an instruction to include --pod-network-cidr=10.32.0.0/12 when running the init command.

**Comment by ryan-g2** [comment]
`kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:27:49Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}`

I am not passing any of those arguments - this is the command I am using to setup the cluster  ` kubeadm init --pod-network-cidr=10.32.0.0/12 --apiserver-advertise-address=192.168.1.31`

When I was setting up my cluster initially (without the CIDR cmd), I did not see a failing weave-net pod until I added one node.  Following the docs, adding a node to the cluster would create 2 containers in the weave-net pod - in my pod, one would work and the 2nd one would never become fully ready.  This 2nd one is the one that would eventually start crashing.  The logs would only say `Failed to get peers`.

> kubemaster@kubemaster:$ kubectl get pods --all-namespaces
> NAMESPACE     NAME                                 READY   STATUS    RESTARTS   AGE
> kube-system   coredns-6955765f44-6vqsv             1/1     Running   0          4m56s
> kube-system   coredns-6955765f44-cx2zt             1/1     Running   0          4m56s
> kube-system   etcd-kubemaster                      1/1     Running   0          5m41s
> kube-system   kube-apiserver-kubemaster            1/1     Running   0          5m40s
> kube-system   kube-controller-manager-kubemaster   1/1     Running   0          5m40s
> kube-system   kube-proxy-bwk4q                     1/1     Running   0          4m56s
> kube-system   kube-proxy-gxlj4                     1/1     Running   0          86s
> kube-system   kube-scheduler-kubemaster            1/1     Running   0          5m41s
> kube-system   weave-net-lcw56                      1/2     Error   1          86s
> kube-system   weave-net-xx8hq                      2/2     Running   0          3m40s
>
> kubemaster@kubemaster:$ kubectl logs -n kube-system weave-net-lcw56 weave
> FATA: 2020/01/23 06:49:01.179329 [kube-peers] Could not get peers: Get https://10.96.0.1:443/api/v1/nodes: dial tcp 10.96.0.1:443: i/o timeout
> Failed to get peers

I recreated this issue by tearing down my working cluster, removing the `/etc/cni/net.d` and `$HOME/.kube/config` directories.  I then recreated a cluster with `kubeadm init --apiserver-advertise-address=192.168.1.31`.  I installed weave with `kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"`.  My first attempt didn't see the crashing pod, but my second attempt at making the cluster did - so not 100% reproducable maybe.

**Comment by Kartik494** [comment]
@ryan-g2 i faced the similar issue when i used kubeadm init without mentioning --pod-network-cidr=10.32.0.0/12,i think for user's to create pod --pod-network-cidr is necessary.
and in my environment i don't get my  coredns pod up and running and after applying weavenet plugin i got my coredns pod running.
kube-system   weave-net-6bsdp                             2/2     Running   14         10d
kube-system   weave-net-7k9h8                             2/2     Running   14         10d

Thanks

**Comment by neolit123** [comment]
@ryan-g2 

i would like to point out this is the first time i hear that weavenet requires the Pod network CIDR in some cases. this seems like a bug in weavenet to me.

> I am not passing any of those arguments - this is the command I am using to setup the cluster kubeadm init --pod-network-cidr=10.32.0.0/12 --apiserver-advertise-address=192.168.1.31

once `init` finishes what is the output of `kubectl get cm kube-proxy -o yaml -n kube-system`?

> When I was setting up my cluster initially (without the CIDR cmd), I did not see a failing weave-net pod until I added one node. Following the docs, adding a node to the cluster would create 2 containers in the weave-net pod - in my pod, one would work and the 2nd one would never become fully ready. This 2nd one is the one that would eventually start crashing. The logs would only say Failed to get peers.

this seems like a weavenet problem and not a kubeadm one. please try logging an issue in the weavenet issue tracker.

> My first attempt didn't see the crashing pod, but my second attempt at making the cluster did - so not 100% reproducable maybe.

strange.

**Comment by neolit123** [comment]
@Kartik494 
> i faced the similar issue when i used kubeadm init without mentioning --pod-network-cidr=10.32.0.0/12,i think for user's to create pod --pod-network-cidr is necessary.
and in my environment i don't get my coredns pod up and running and after applying weavenet plugin i got my coredns pod running.

like i've mentioned earlier weavenet does not require --pod-network-cidr unless the users is applying non-default values to kube-proxy.

but yes, a CNI plugin is required for the coredns pods to start.

**Comment by ryan-g2** [comment]
@neolit123 

This is the first I have heard of Weave needing a CIDR as well.  I also stumbled across this on my first attempt setting up a cluster.  Both docs, Kubernetes and Weave, didn't mention did mention needing this.  I spent a few hours trying to debug my cluster to figure out why the pods were not communicating.

I did try one attempt, that failed, of getting a Calico net setup for the cluster.  That attempt left me with 2 crashing network pods.  That is why I tried Weave.  For the Calico set up, I did use a CIDR command, but for the 192.168 address block and not 10.32.

I'll look into the kube-poxy output once I get some time to set my cluster up again today.

**Comment by ryan-g2** [comment]
RE: The kube-proxy output once I have setup the master (before adding the node that has the crashing net pod):

> apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 0
      contentType: ""
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 0
    clusterCIDR: ""
    configSyncPeriod: 0s
    conntrack:
      maxPerCore: null
      min: null
      tcpCloseWaitTimeout: null
      tcpEstablishedTimeout: null
    enableProfiling: false
    healthzBindAddress: ""
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: null
      minSyncPeriod: 0s
      syncPeriod: 0s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: false
      syncPeriod: 0s
    kind: KubeProxyConfiguration
    metricsBindAddress: ""
    mode: ""
    nodePortAddresses: null
    oomScoreAdj: null
    portRange: ""
    udpIdleTimeout: 0s
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://192.168.1.31:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-24T01:15:43Z"
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "238"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-proxy
  uid: f12e3e4b-73b2-439e-8be9-7289d2bce49a


And the output once I added the one node and started seeing the crashing net pod:

> apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 0
      contentType: ""
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 0
    clusterCIDR: ""
    configSyncPeriod: 0s
    conntrack:
      maxPerCore: null
      min: null
      tcpCloseWaitTimeout: null
      tcpEstablishedTimeout: null
    enableProfiling: false
    healthzBindAddress: ""
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: null
      minSyncPeriod: 0s
      syncPeriod: 0s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: false
      syncPeriod: 0s
    kind: KubeProxyConfiguration
    metricsBindAddress: ""
    mode: ""
    nodePortAddresses: null
    oomScoreAdj: null
    portRange: ""
    udpIdleTimeout: 0s
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://192.168.1.31:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-24T01:15:43Z"
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "238"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-proxy
  uid: f12e3e4b-73b2-439e-8be9-7289d2bce49a

And for a compare, here is the output after I add the one node when I supply the CIDR in the init command:

> apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 0
      contentType: ""
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 0
    clusterCIDR: 10.32.0.0/12
    configSyncPeriod: 0s
    conntrack:
      maxPerCore: null
      min: null
      tcpCloseWaitTimeout: null
      tcpEstablishedTimeout: null
    enableProfiling: false
    healthzBindAddress: ""
    hostnameOverride: ""
    iptables:
      masqueradeAll: false
      masqueradeBit: null
      minSyncPeriod: 0s
      syncPeriod: 0s
    ipvs:
      excludeCIDRs: null
      minSyncPeriod: 0s
      scheduler: ""
      strictARP: false
      syncPeriod: 0s
    kind: KubeProxyConfiguration
    metricsBindAddress: ""
    mode: ""
    nodePortAddresses: null
    oomScoreAdj: null
    portRange: ""
    udpIdleTimeout: 0s
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://192.168.1.31:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-24T01:27:20Z"
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "242"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-proxy
  uid: 10ce9974-f193-4b5c-9efb-78c0317746d2

**Comment by neolit123** [comment]
> clusterCIDR: ""

given this field is empty i'm inclined to believe this is some sort of a weavenet issue.

**Comment by neolit123** [comment]
/close
let's follow up on https://github.com/weaveworks/weave/issues/3758
