### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by mmiara** [kubernetes/website#18832]
**This is a Bug Report**

**Problem:**
Does not give any information on operations after the cluster is formed. Following documentation only supports single etcd node (how is the documentation for production recommended cluster not included?)

**Proposed Solution:**

Add documentation on how to manage this cluster when changes need to be made.

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
> Does not give any information on operations after the cluster is formed

this is not the responsibility of the kubeadm docs.
for external etcd - upgrades, restarts and maintenance are the responsibility of the operator using commands such as etcdctl:
https://github.com/etcd-io/etcd/tree/master/etcdctl

> Following documentation only supports single etcd node (how is the documentation for production recommended cluster not included?)

the purpose of https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ is to document a multi-node etcd setup.

i do not see an issue here.

/close
