### ISSUE TITLE
All links are broken in https://kubernetes.io/docs/tasks/

### ISSUE THREAD

**Issue by ahmedatgithub** [kubernetes/website#18833]
**This is a Bug Report**
**Problem:**
All links are broken in k8s.io/docs/tasks/
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/

**Comment by ahmedatgithub** [comment]
the links take you to subsections within the same page instead of the intended pages.

**Comment by gavinfish** [comment]
The above links are just the toc of the page, so it makes sense to take you to subsections within the same page.

**Comment by bdwill** [comment]
I agree, @gavinfish. Unfortunately, @ahmedatgithub it just appears that there's no documentation for Tasks.

**Comment by gavinfish** [comment]
More discussions about the navigation and TOC for tasks page at #18755.

**Comment by tengqm** [comment]
Thanks @k8s-ci-robot, this is no longer an issue.
