### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/service-topology/

### ISSUE THREAD

**Issue by jberkus** [kubernetes/website#18831]
**This is a Bug Report**

**Problem:** 
Broken Link.

Page has link to https://kubernetes.io/docs/tasks/administer-cluster/enabling-service-topology at the bottom, a page which does not exist.

**Proposed Solution:** 

**Page to Update:**
k8s.io/docs/concepts/services-networking/service-topology/

**Comment by gavinfish** [comment]
This broken link should be fixed after #18712 is merged.
