### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by junjo255** [kubernetes/website#18835]
**This is a Bug Report**

**Problem:** When I click on 'continue' button that's on the last step, the section of the page responds with "docs.google.com took too long to respond." 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks for letting us know. Unfortunately that is outside of our control but we'll look into alternate ways for managing this.

**Comment by sftim** [comment]
@junjo255 you're still seeing the issue? It might be due to network-level filtering.
