### ISSUE TITLE
Use markdown instead of html escape chars

### ISSUE THREAD

**Issue by anshprat** [kubernetes/website#18857]
**This is a Bug Report**

**Problem:**
The code in https://github.com/kubernetes/website/blob/master/content/en/docs/contribute/style/write-new-topic.md uses escaped HTML chars to display. The following

`{{< codenew file="<RELPATH>/my-example-yaml>" >}}`

is displayed using

`<pre>&#123;&#123;&lt; codenew file="&lt;RELPATH&gt;/my-example-yaml&gt;" &gt;&#125;&#125;</pre>
`
The code can be much better than the existing escaped HTML by using markdown properly which will help in easier maintenance and reference.

Found this issue while working on https://github.com/kubernetes/website/pull/18245

**Proposed Solution:**
Use markdown instead of escaped chars.

**Page to Update:**
https://kubernetes.io/docs/contribute/style/write-new-topic/#including-code-from-another-file

**Comment by bdwill** [comment]
This appears to be fixed in PR #18858
