### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by AdimUser** [kubernetes/website#18872]
**This is a Bug Report**

**Problem:**
Could you please update, how to see the available(already set) flags
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Kartik494** [comment]
The given options after  kubelet [flags] are actually the flags available.When i enter the command kubelet --options in my enviorment i receive the output as

root@kmaster:/# kubelet --options
Usage:
  kubelet [flags]

Flags:
      --add-dir-header                                                                                            If true, adds the file directory to the header
      --address 0.0.0.0                                                                                           The IP address for the Kubelet to serve on (set to 0.0.0.0 for all IPv4 interfaces and `::` for all IPv6 interfaces) (default 0.0.0.0) (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)
..........
Thanks

**Comment by Kartik494** [comment]
@AdimUser  Hi , you can close this issue if you find solution for kubelet flags

**Comment by tengqm** [comment]
Let's close it. Feel free to open if the suggested command doesn't work.
/close
