### ISSUE TITLE
Two blog posts from early 2016 are corrupted

### ISSUE THREAD

**Issue by bboreham** [kubernetes/website#18889]
**This is a Bug Report**

**Problem:**
This post comes up in Chinese: https://kubernetes.io/blog/2016/01/why-kubernetes-doesnt-use-libnetwork/
This post shows with every character interspersed with "https://github.com/kubernetes/kubernetes/pull/18215": https://kubernetes.io/blog/2016/01/kubernetes-community-meeting-notes_28/

**Proposed Solution:**
Make the posts readable in English.

**Page to Update:**
I imagine this needs to be fixed in transformation; the source looks ok.

**Comment by kbhawkey** [comment]
Also,
https://kubernetes.io/blog/2016/01/why-kubernetes-doesnt-use-libnetwork/

**Comment by sftim** [comment]
/kind bug
Thanks @bboreham

**Comment by bboreham** [comment]
The first one now seems fixed; second one is still bad.

**Comment by celestehorgan** [comment]
https://kubernetes.io/blog/2016/01/why-kubernetes-doesnt-use-libnetwork/ seems to be working now, but https://kubernetes.io/blog/2016/01/kubernetes-community-meeting-notes_28/ is still corrupted. Note that [the underlying markdown](https://github.com/kubernetes/website/blob/master/content/en/blog/_posts/2016-01-00-Kubernetes-Community-Meeting-Notes_28.md) seems to have been in a wonky state for about 2 years now 😅 

This is actually a pretty good first issue, for someone patient.
