### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by Lumikkode** [kubernetes/website#18891]
**This is a Bug Report**

**Problem:** the commands about getting the services are wrong, previous commands display the service as "kubernetes" but following commands refers to "kubernetes-bootcamp"

**Proposed Solution:** replace "kubernetes-bootcamp" with "kubernetes"

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

**Comment by sftim** [comment]
There is a Service called `kubernetes` and it is not the same Service as `kubernetes-bootcamp`.
The Service called `kubernetes` represent's the cluster's Kubernetes API.

I think the current page is correct.

**Comment by Kartik494** [comment]
@Lumikkode agreed with @sftim as they both are different service types.
kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080
by using this command it is creating a service name kubernetes-bootcamp of nodePort service type
I also think there is not  an issue regardiung this page 
Thanks
