### ISSUE TITLE
enhance k8s.io/docs/setup/production-environment/container-runtimes

### ISSUE THREAD

**Issue by avhvr** [kubernetes/website#18892]
**This is a Feature Request**

All of the packages that are required to set up the Kubernetes are installed without requiring any prompts through the package manager( like apt or yum) except for the container runtimes.

**What would you like to be added**

Install container runtime without prompts from the package manager(apt or yum)

**Why is this needed**

Just an enhancement with respect to the other package installations as mentioned in the Kubernetes docs

**Comments**

`apt-get install -y <package>`
`yum install -y <package>`

**Comment by sftim** [comment]
Thanks
@avhvr 

/priority backlog

**Comment by sftim** [comment]
Addressed in #18893
/close
