### ISSUE TITLE
Lint for Hugo aliases with absolute paths

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#18898]
**This is a Feature Request**

**What would you like to be added**

Create a new lint, applied to new pull requests, that checks for front matter that adds a Hugo alias with a leading `/`.

For example, reject this:
```
---
title: Some Kubernetes page
weight: 10
aliases: [/some-page/,/some-other-thing/]
---
```

**Why is this needed**
Based on experience from the fix in PR #18895 and some other stuff I wasn't involved in, it seems like this site never has a use for Hugo aliases that have a leading `/`.
If that's the case, how about linting for that? It can be a local check and also happen in CI.

**Comments**
/kind feature
/priority backlog

**Comment by Colstuwjx** [comment]
How about adding this lint inside makefile and ensure it happens before executing netlify site build ?

**Comment by sftim** [comment]
@Colstuwjx if you have the appetite for a pull request to add this, I'm all for it.
