### ISSUE TITLE
Bug Bounty Program

### ISSUE THREAD

**Issue by zestrells** [kubernetes/website#18890]
**This is a Feature Request**

**What would you like to be added**
We are looking for more information in the documentation around the new [Bug Bounty Program](https://kubernetes.io/blog/2020/01/14/kubernetes-bug-bounty-announcement/) that was announced earlier this month. Some questions that would be nice to answer:
- What king of bugs can be reported?
- Is there anything off limits?
- Where should someone report a bug?

**Why is this needed**
This would give security researchers the ability to find documentation on the Kubernetes website about the bug bounty program that was just announced.

**Comments**
This is an effort that was brought up by the /sig-docs-security group in collaboration with @sethmccombs. 

Looks like we can bring the information from [Hackerone](https://hackerone.com/kubernetes).

**Comment by sftim** [comment]
/committee product-security
(I think - feel free to remove the label if that's wrong)

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/issues-security/security/ already has something on this
see PR #18690

**Comment by sftim** [comment]
Done enough!
/close
