### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by salotaibistc** [kubernetes/website#18894]
In the Kubernetes interactive tutorial "Module 2 - Deploy an app"  step 3 0f 3, we can see the word "Pods" for the first time. I think it will be extremely helpful for people following the tutorial if you guys describe what a "Pod" is before actually using it. I know that Module 3 explains what Kubernetes Pods are but, I believe it will be way clearer if an explanation (could be a brief one) is written in Module 2.

**Comment by Colstuwjx** [comment]
Yes, adding a link for jumping to Explore section should be better. Target page should be: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/ .

Feel free to take PR!
/language en
/kind documentation

**Comment by sftim** [comment]
I agree
/help
/priority important-longterm

**Comment by Dean-Coakley** [comment]
I'm happy to pick this up.

What should be required? 

I'm thinking a link to https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/#kubernetes-pods on https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/ uhhh just **before** the interactive content?

**Comment by sftim** [comment]
Possibly, borrow the text from https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#understanding-pods
Maybe also provide a link to that page, worded to make it clear that this is for readers who are particularly keen on background reading before they move on.

What do you think @Dean-Coakley ?

**Comment by Dean-Coakley** [comment]
Yeah, that sounds good.

Maybe something like:

> A Pod is the basic execution unit of a Kubernetes application–the smallest and simplest unit in the Kubernetes object model that you create or deploy. A Pod represents processes running on your Cluster. [Learn more about pods](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#understanding-pods)

This should be placed above the interactive content?

**Comment by sftim** [comment]
Sounds good to me - go for it!
