### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/dns-debugging-resolution/

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/website#18900]
**Problem:**
In this page in the "known issues"-section it says that the "3 DNS nameserver records" is a known bug from 2005, but recently, (08/01/2020), it seems that it was [updated](https://bugzilla.redhat.com/show_bug.cgi?id=168253).
In the "bugzilla"-page, in the "Links"-section, there are 3 "resolved" related bugs.

**Proposed Solution:**
Could you investigate further and update the documentation?

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by Colstuwjx** [comment]
Thanks @LSmyrnaios , I did some researches, starting with RHEL7.5, 6 search domain limit has bee removed, see [ref](https://access.redhat.com/solutions/58028), and the limit of `3 DNS nameservers` should be configured by `MAXNS`, see [manual page](https://www.systutorials.com/docs/linux/man/5-resolv.conf/).

As a result, I think the search domain limit part should be updated.

/language en
/kind documentation
