### ISSUE TITLE
Need documentation on CrashLoopBackOff

### ISSUE THREAD

**Issue by vllry** [kubernetes/website#18903]
**This is a Feature Request**

**What would you like to be added**
Documentation explaining what a CrashLoopBackOff is, what it implies, and behavioral details (EG backoff time).

**Why is this needed**
Crashing containers is an extremely frequent problem, and this appears to be largely undocumented in Kubernetes documentation itself. When trying to explain this behavior, it would be great to be able to link an authoritative kubernetes.io doc, rather than a StackOverflow post or similar.

**Comment by Colstuwjx** [comment]
This issue target should be https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ .

In the [pod restartPolicy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) section, it explained how kubelet restart the crash containers with back-off delay.

As you said, it didn't tell the pod reasons and behaviors in details. I suggest adding Reason field expansion for telling the enum of cases and its behavior, like the `type` field [did](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions).

Feel free to take PR, IMO, I think it's good to have this.
/kind documentation
/language en

**Comment by sftim** [comment]
IMO
/priority important-longterm

**Comment by amolmote** [comment]
is  any one is working on this ??..as a beginner can proceed to do this

**Comment by sftim** [comment]
I haven't seen a hint that anyone has started work on this.

**Comment by FavourDaniel** [comment]
@sftim Can I be assigned to this issue?

**Comment by KhushPatibandha** [comment]
this still open? I would like to work on this.

**Comment by KhushPatibandha** [comment]
I have opened a PR for this issue do review it and provide your feedback.

**Comment by sftim** [comment]
/help

@KhushPatibandha what are your intentions regarding the PR you opened a few months ago?

**Comment by vaibhav2107** [comment]
@KhushPatibandha Are you still working on this issue ?

**Comment by sftim** [comment]
Help is welcome; we'd love to have a page about this, or an evergreen (maintained) blog article.

**Comment by sanaasy** [comment]
@sftim I'll have a PR up by Saturday!

**Comment by ricardoamaro** [comment]
This is very interesting that it would be missing... 
I see a reference in https://kubernetes.io/docs/tasks/debug/debug-application/debug-init-containers/ and a discussion https://discuss.kubernetes.io/t/crashloopbackoff-error/27717

**Comment by sftim** [comment]
Done in https://github.com/kubernetes/website/pull/45928

Thanks @ricardoamaro

**Comment by ricardoamaro** [comment]
Yay!

**Comment by sftim** [comment]
/close

Done in #45928
