### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/expose-external-ip-address/

### ISSUE THREAD

**Issue by pparihar** [kubernetes/website#18904]
LoadBalancer service is created but without Ingress controller. Can you please update your deployment yam l or service command to include the Ingress.

Use the external IP address (LoadBalancer Ingress) to access the Hello World is still in pending state only...please explain without mention of Ingress how could External IP address is created

**Comment by Colstuwjx** [comment]
The `type=LoadBalancer` service is implemented by external cloud provider, see [doc](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer).

For you suggested [page](https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/), I think expanding content about how to set cloud provider for `type=LoadBalancer` service is out-of-scope, but adding notice about this `type=LoadBalancer` should be fine.

/language en
/kind documentation
