### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/basic-stateful-set/

### ISSUE THREAD

**Issue by davidgfolch** [kubernetes/website#18927]
**This is a Bug Report**

**Problem:**
This command doesn't work as described in documentation:

`kubectl run -i --tty --image busybox:1.28 dns-test --restart=Never --rm`

The output I get is: 

```
If you don't see a command prompt, try pressing enter.
/ # 
```

**Proposed Solution:**
No idea at all.
**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#using-stable-network-identities

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

😄  minikube v1.6.2 on Ubuntu 18.04
✨  Selecting 'kvm2' driver from existing profile (alternates: [virtualbox none])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing kvm2 VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
🚀  Launching Kubernetes ... 
🏄  Done! kubectl is now configured to use "minikube"

**Comment by Colstuwjx** [comment]
I think it works as expect, you could see the following two commands in the page:

```
nslookup web-0.nginx
nslookup web-1.nginx
```

/language en
/triage support

**Comment by davidgfolch** [comment]
ok, thanks, I didn't understand it was a command,  it seemed the output to me.

Maybe it would be nice for dummies like me, give a bit more detail like this:

```
$ kubectl run -i --tty --image busybox:1.28 dns-test --restart=Never --rm  
If you don't see a command prompt, try pressing enter.
/ # nslookup web-0.nginx
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      web-0.nginx
Address 1: 172.17.0.13 web-0.nginx.default.svc.cluster.local
/ # nslookup web-1.nginx
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      web-1.nginx
Address 1: 172.17.0.14 web-1.nginx.default.svc.cluster.local
/ # 

```
