### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dual-stack/

### ISSUE THREAD

**Issue by neiljerram** [kubernetes/website#18923]
**This is a Bug Report**

**Problem:**
Page should not say that Kubenet is required.

**Proposed Solution:**
Instead it should say that a networking plugin is required that supports dual stack, such as Calico or Kubenet.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/dual-stack/

**Comment by sftim** [comment]
/kind bug
/sig networking

and IMO, because dual-stack is alpha:
/priority backlog
