### ISSUE TITLE
Kubernetes installation tutorial

### ISSUE THREAD

**Issue by alexk345** [kubernetes/website#18933]
I want practical installation of kubernetes tutorial and video for me to test load balancer. Its  a load balancer at best . Instead of i hear all kinda nonsense terms. why humans make things complex? yes it may do other things but at its heart its a load balancer.

**Comment by sftim** [comment]
Kubernetes is an open-source platform that automates container operations for application deployment.

Some people use Kubernetes with load balancers, and that's quite common.

Perhaps https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/ was what you had in mind @alexk345 ?

/triage needs-information
