### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/jsonpath/

### ISSUE THREAD

**Issue by base698** [kubernetes/website#18938]
**This is a Bug Report**

**Problem:**

No examples of how to use jsonpath to retrieve keys with dots, ie `{.data.ca.crt}`  

**Proposed Solution:**

A working example of keys with dots.

**Page to Update:**
https://kubernetes.io/...

**Comment by base698** [comment]
`-o jsonpath="{.data.ca\.crt}"`

**Comment by sftim** [comment]
Good suggested enhancement; thanks @base698.

If you wanted to [propose a fix](https://kubernetes.io/docs/contribute/start/), please go ahead.
/priority backlog
/sig cli
