### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/overview/

### ISSUE THREAD

**Issue by 170031571** [kubernetes/website#18934]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by 170031571** [comment]
9595-333925

**Comment by sftim** [comment]
Hi @170031571 
What isn't right about https://k8s.io/docs/reference/kubectl/overview/?

/triage needs-information
