### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/authentication/

### ISSUE THREAD

**Issue by base698** [kubernetes/website#18948]
**This is a Bug Report**

**Problem:**

Would be nice to have a working example start to finish of having no kubeconfig to having a working kubectl get deploy comment.  I see mentions of `kubectl --token`, but no examples on how to get it to work.  using `kubectl --token` it requests I be logged in...  I'm trying to use kubectl in a ci/cd job with a service account and other than using an existing config and keeping that as a var in the ci tool, I can't get the token to work with service accounts.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Does https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-for-the-first-time-with-kubectl signpost you to enough information to help?

(my guess is: it might not)
/sig cli
