### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by Vivek-kkaushik** [kubernetes/website#18945]
Whileinitializing mast command ,,I am getting this error-
kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=192.168.9.2

W0201 17:48:59.774024   14370 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0201 17:48:59.774111   14370 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.2
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Swap]: running with swap on is not supported. Please disable swap
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
root@kubemaster:/home/osboxes#

**Comment by neolit123** [comment]
k8s does not support Linux OS with swap enabled.
to disable swap you can try this guide:
https://www.tecmint.com/disable-swap-partition-in-centos-ubuntu/

or use:
`kubeadm init ... --ignore-preflight-errors=Swap...`

/triage support
/close

**Comment by Vivek-kkaushik** [comment]
> Whileinitializing mast command ,,I am getting this error-
> kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=192.168.9.2
> W0201 17:48:59.774024   14370 validation.go:28] Cannot validate kube-proxy config - no validator is available
> W0201 17:48:59.774111   14370 validation.go:28] Cannot validate kubelet config - no validator is available
> [init] Using Kubernetes version: v1.17.2
> [preflight] Running pre-flight checks
> [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
> error execution phase preflight: [preflight] Some fatal errors occurred:
> [ERROR Swap]: running with swap on is not supported. Please disable swap
> [preflight] If you know what you are doing, you can make a check non-fatal with --ignore-preflight-errors=...
> To see the stack trace of this error execute with --v=5 or higher
> root@kubemaster:/home/osboxes#

Thanks @neolit123 ..for your solution ..my issue fixed ..also I got to know about swap space:)
