### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by rajattrt** [kubernetes/website#18943]
**This is a Bug Report**

**I think this information comes from Katakoda. Not sure if this is the right place to report the issue.**

**Problem:**
[In Tutorial - Interactive Tutorial - Creating a Cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/), step 3, command kubectl cluster-info gives the output -
```
$ kubectl cluster-info
Kubernetes master is running at https://172.17.0.37:8443
KubeDNS is running at https://172.17.0.37:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
Which does not go very well with the explanation for this command which goes like - _We have a running master and a dashboard. The Kubernetes dashboard allows you to view your applications in a UI._ 

The output of the command mentions Kubernetes master and KubeDNS (not dashboard).

**Proposed Solution:**
Add an explanation as per the output for the aforementioned command.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by sftim** [comment]
Thanks @rajattrt, that's a fair point.

@BenHall - is there a label that this kind of issue should have, to indicate that it applies to tutorials?

/priority backlog

**Comment by BenHall** [comment]
Thanks for the suggestion. This has been updated and can now be closed.
