### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-kubernetes-objects/declarative-config/

### ISSUE THREAD

**Issue by bennythejudge** [kubernetes/website#18953]
**This is a Bug Report**

**Problem:**
The section titled "Merge individual elements of a list of complex elements:" at link https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merge-individual-elements-of-a-list-of-complex-elements, suggests an `apply` to update the `containers` field of a PodSpec. Unless I have misunderstood the example, such change is not supported:

```
The Pod "nginx-declarative" is invalid: spec.containers: Forbidden: pod updates may not add or remove containers
```

**Proposed Solution:**
Use a working example that can be reproduced

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#merge-individual-elements-of-a-list-of-complex-elements

Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sftim** [comment]
That looks correct; it needs fixing.

/kind bug
/language en
/priority backlog
