### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/automated-tasks-with-cron-jobs/

### ISSUE THREAD

**Issue by otma2000** [kubernetes/website#18967]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by otma2000** [comment]
Alternatively, you can use kubectl run to create a cron job without writing a full config:

kubectl run --generator=run-pod/v1 hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh -c "date; echo Hello from the Kubernetes cluster"

Running does not create not create any cron jobs. 

ole@ole-HP-ProBook-430-G2:~$ kubectl run --generator=run-pod/v1 hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh
-c "date; echo Hello from the Kubernetes cluster"
pod/hello created
ole@ole-HP-ProBook-430-G2:~$ kubectl get cronjob hello

**Comment by Colstuwjx** [comment]
I have been tried this command `kubectl run --generator=run-pod/v1 hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh -c "date; echo Hello from the Kubernetes cluster"`, it **ONLY** creates a Pod, rather than CronJob.

I also did some research, it seems that [`kubectl run` is NOT a suggest way](https://github.com/kubernetes/kubernetes/pull/68132#issuecomment-433420823), I think it should be changed.

/kind bug
/language en

**Comment by Colstuwjx** [comment]
@rajibmitra  Feel free to take PR for this! I suggest that removing this alternative case should be fine.

**Comment by otma2000** [comment]
it works without --generator=run-pod/v1
 kubectl run hello  --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh -c "date; echo Hello from the Kubernetes cluster"
kubectl run --generator=cronjob/v1beta1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
cronjob.batch/hello created
ole@ole-HP-ProBook-430-G2:~$ kubectl get cronjobs.batch 
NAME    SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
hello   */1 * * * *   False     0        <none>          6s

**Comment by Colstuwjx** [comment]
Yes, I could also confirm about this, but I still think that removing this case should be better, since it marked as **DEPRECATED** .

**Comment by rajibmitra** [comment]
Done, #19043  , please let me know if I need to make any changes in the doc.

**Comment by rajibmitra** [comment]
Fix has been merged to master. #19043

**Comment by sftim** [comment]
/close
Fixed in #19043
