### ISSUE TITLE
Confusion over whether time is allowed in managedFields with operation is Apply

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#18964]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply contains an example of the new `managedFields` metadata, with `operation: Apply` and a value for `time`. But https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#managedfieldsentry-v1-meta says the `time` must be omitted when the operation is Apply. 

**Proposed Solution:**
Fix whichever doc is wrong.

**Page to Update:**
One of the two cited above.

**Comment by kbhawkey** [comment]
Hello @MikeSpreitzer . 
The current docs (https://kubernetes.io/docs/) are version 1.17. Does this issue only apply to version 1.16?
API Reference v1.17, time field description:
```
Time is timestamp of when these fields were set. It should always be empty if Operation is 'Apply'
```

**Comment by MikeSpreitzer** [comment]
Oh, I did not notice that my second URL was specific to release 1.16.  But your quote shows that it is the same in 1.17.
