### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by ffisk-gm-com** [kubernetes/website#18966]
**This is a Bug Report**

**Problem:**
How to update the ingress components plus does ingress have a version?
**Proposed Solution:**
Update the concepts page to describe how an ingress version relates to a k8s version. Also, are they 'tied' and you can't update one without the other?
**Page to Update:**
 k8s.io/docs/concepts/services-networking/ingress/

**Comment by Colstuwjx** [comment]
I don't think ingress is 'tied' to k8s version, instead, it's a kind of k8s resource, and it has its own api version.

Could you please share your case with details? It could help us to determine whether we should do some changes in our doc.

/triage support
/language en

**Comment by tengqm** [comment]
Before 1.13, Ingress is a resource from extensions/v1beta1 group. 1.14 added the networking.k8s.io/v1beta1 API group, with Ingress moved over to this new API group. The Ingress in extensions/v1beta1 has since been marked as DEPRECATED.

**Comment by tengqm** [comment]
1.19 has a major rewrite of the docs: #21590
