### ISSUE TITLE
Navigation menu disappears when collapsed under the hamburger menu

### ISSUE THREAD

**Issue by palsivertsen** [kubernetes/website#18972]
Apologies if this is the wrong place to post this issue.

Browsing kubernetes.io today and I noticed that the navigation menu disappears when it is collapsed into a hamburger menu.

![image](https://user-images.githubusercontent.com/11890143/73729979-4d5d7d00-4736-11ea-9bb3-ec70679b91e5.png)

**Comment by mrbobbytables** [comment]
@palsivertsen I've transferred the issue to the [kubernetes/website](https://github.com/kubernetes/website) repo. Any site related issues should be opened there.

**Comment by bismitaguha** [comment]
I am working on this issue.

**Comment by brianpursley** [comment]
+1 on this problem.  For me, it happens on iPad using safari or chrome.
When you click on the hamburger, the gray box is displayed but it is empty, no menu items are displayed.

**Comment by brianpursley** [comment]
I think this is a regression in 1.17.  It works find in v1.16 and earlier.

**Comment by brianpursley** [comment]
@bismitaguha are you still working on this?
Reverting [this commit](https://github.com/kubernetes/website/commit/ccef43197ec76a646d371bddf5b6fa8704eed885#diff-27b983ab62ddff504e715d29f5003d57) fixes the problem for me locally.

**Comment by kbhawkey** [comment]
@palsivertsen , I have created a PR #19477 to address the display of the nav bar on smaller screens (tested on a smaller laptop, chrome and firefox browsers). Interested in feedback and testing on other browsers.

**Comment by celestehorgan** [comment]
This is an issue with the old layout. Can we close this? (cc: @sftim)

**Comment by brianpursley** [comment]
If it is fixed by a new layout, that is fine with me. I just wanted to make sure it was tracked somewhere. Thanks!

**Comment by sftim** [comment]
/retitle Navigation menu disappears when collapsed under the hamburger menu
/kind bug

@celestehorgan I'm happy to 
/close
this
