### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/

### ISSUE THREAD

**Issue by eyeman666** [kubernetes/website#18978]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@eyeman666, could you provide some more information about what isn't right with https://k8s.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/?

**Comment by rajibmitra** [comment]
@sftim Tim, I am getting this 
![image](https://user-images.githubusercontent.com/1690251/74108195-aea1a800-4b9d-11ea-8c59-5ccf9d314402.png)

**Comment by sftim** [comment]
I think you're concerned about the deprecation warning @eyeman666. Have I got that right?

/triage needs-information
