### ISSUE TITLE
Pod Quality of Service doc doesn't explain what each QoS class does

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/website#18982]
**This is a Bug Report**

**Problem:**

The Pod Quality of Service docs under "Tasks" does not clearly explain what each QoS class means - it merely states how a desired class can be assigned to a pod based on the specified resource requests and limits.

**Proposed Solution:**

Each class in "QoS Classes" section should have a short sentence or paragraph describing what the class represents. For example:

```
* Guaranteed - pods are guaranteed to have the requested resources when they are scheduled, and the least likely to be evicted if the node running the pod is overcommitted.
* Burstable - pods are guaranteed to have the requested resources, but are not guaranteed to have the full resources specified in the resource `limits` when scheduled. If a node is overcommitted, Burstable pods will be evicted before Guaranteed pods are evicted.
* BestEffort - pods are not given any guarantees with respect to allocated resources when scheduled. If a node is overcommitted, BestEffort pods are the first ones considered for eviction.
```

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

v1.17.0

Proposed solution is based on my interpretation of https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md - though this document may be outdated with respect to how the scheduler is currently implemented.

**Comment by Colstuwjx** [comment]
The implement details are fragmented in our website.

As you said, for how the default scheduler handles these three qos classes pod scheduling, it was missing in our website.

For eviction policy about these three qos classes, see [this page](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods).

For how these qos classes works with CPU manager, see [this page](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy).

I wonder whether we need to add a new page inside [concepts configuration catalog](https://kubernetes.io/docs/concepts/configuration/), like `Pod Qos`, and in this page, we could talk the details of qos usage.

/language en
/kind documentation

**Comment by adambkaplan** [comment]
@Colstuwjx taking a look at the fragmentation you've identified, I feel that the notions around resources, priority, scheduling, and eviction are too focused on implementation and are not written with a developer or administrator in mind.

It's my opinion that end users want start with the basics:

1. How is my pod assigned to a node?
2. What does kubernetes do with my pod spec's priority and resources?
3. How can my pod be kicked out of a node?

Many of the nuances (converting CPU requests to specific cloud providers, kubelet flags) can be moved to advanced topics so that the core behavior shines through. I'll discuss some of my ideas in the next SIG Docs meeting.

**Comment by adambkaplan** [comment]
@Colstuwjx ideas have now been combined into feature proposal #19081
