### ISSUE TITLE
Issue with the Page History link in localized versions

### ISSUE THREAD

**Issue by remyleone** [kubernetes/website#19012]
**This is a Bug Report**

**Problem:**

When I click at the bottom of the page on the page history  (historique in French) button link I expect to find the commit history of the French localized page, instead, I find English history.

**Proposed Solution:**

Having the Page History button target a given localized version of a given page.

**Page to Update:**

All localized page will change but the Page History button needs to be updated only once.

**Comment by gavinfish** [comment]
Duplicated with #18403, I think.

**Comment by sftim** [comment]
@gavinfish it looks to me as if this is not the same as issue #18403 

@remyleone thank you very much for reporting this defect
/kind bug
and, reluctantly, I think the most appropriate prioritization is:
/priority backlog
