### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by chanonroy** [kubernetes/website#19015]
**This is a Bug Report**

**Problem:**
- Google form feedback embed within Katakoda iframe is very collapsed due to not height property being `auto`, which makes for a less desirable user experience.

<img width="1216" alt="Screenshot 2020-02-06 at 4 37 14 pm" src="https://user-images.githubusercontent.com/16366896/73958040-3322cb00-48ff-11ea-9d31-16a983e0f279.png">

**Proposed Solution:**

- Give the iframe's height property `100%` to give the following desired effect:
<img width="690" alt="Screenshot 2020-02-06 at 4 40 13 pm" src="https://user-images.githubusercontent.com/16366896/73958149-649b9680-48ff-11ea-8fb4-814e726192ba.png">
<img width="1286" alt="Screenshot 2020-02-06 at 4 37 49 pm" src="https://user-images.githubusercontent.com/16366896/73958075-433aaa80-48ff-11ea-88b5-2ac22b073444.png">

Note: That this might have to do with the Katakoda embed rather than something that we can control.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by sftim** [comment]
Thanks for identifying this!
/kind bug

**Comment by BenHall** [comment]
Thanks! We'll get this fixed.

/cc @gsoria

**Comment by sftim** [comment]
/priority backlog
?
