### ISSUE TITLE
DaemonSet concept page, list of daemons

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#19026]
**This is a Feature Request**

Should the DaemonSet _concept_ page maintain a list of open source (or third party?) daemons for:
- cluster storage
- logging collection
- node monitoring

For information, see https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

```
Some typical uses of a DaemonSet are:

    running a cluster storage daemon, such as glusterd, ceph, on each node.
    running a logs collection daemon on every node, such as fluentd or logstash.
    running a node monitoring daemon on every node, such as Prometheus Node Exporter, Flowmill, Sysdig Agent, collectd, Dynatrace OneAgent, AppDynamics Agent, Datadog agent, New Relic agent, Ganglia gmond or Instana Agent
```

**Why is this needed**
The list of monitoring daemons is increasing.

**Comment by sftim** [comment]
Very much a valid concern, I think.

/priority backlog
/kind valid

**Comment by sftim** [comment]
> Should the DaemonSet concept page maintain a list of open source (or third party?) daemons

No, because https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content

/close
(but feel free to reopen)
