### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by AhostiOfficial** [kubernetes/website#19029]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@lahbabidev it sounds like you were looking at https://k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/ and you thought that something wasn't right about that page.

What did you see that didn't seem right?

**Comment by lahbabidev** [comment]
Frankly he finds some difficulties in kubernetes especially Deploying WordPress is not easy, it is complicated

**Comment by tengqm** [comment]
No response from the reporter for a long time.
/close
