### ISSUE TITLE
Issue with /docs/user-guide/pods/multi-container/

### ISSUE THREAD

**Issue by luukhoai** [kubernetes/website#1903]
How can I set container's dependency in a pod.

**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
I have a pod with 2 container (app, nginx).
inside app, I have a file *nginx.conf*. nginx(pull from hub.docker.io) will use this file to config.
However, sometime container *nginx* start first -> not get file config -> error 

**Proposed Solution:**
I want a settings that config nginx must run after container *app* run

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
can you make the `app` container an initContainer ?
