### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-controller-manager/

### ISSUE THREAD

**Issue by fleeto** [kubernetes/website#19033]
**This is a Bug Report**

**Problem:**

`--authentication-kubeconfig`:  kubeconfig file pointing at the 'core' kubernetes server with enough rights to create **tokenaccessreviews.authentication.k8s.io**. This is optional. If empty, all token requests are considered to be anonymous and no client CA is looked up in the cluster.

There is no resource type named `tokenaccessreviews` 

**Proposed Solution:**

Should it be `tokenreviews.authentication.k8s.io` ?

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
The object is called [TokenReview](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#tokenreview-v1-authentication-k8s-io) and, as far as I can see, it's GA.

The place to fix this is [`…/k8s.io/apiserver/pkg/server/options/authentication.go`](https://github.com/kubernetes/kubernetes/blob/acd97b42f3acb09ffa30c60690637e815ef28b0a/staging/src/k8s.io/apiserver/pkg/server/options/authentication.go#L214-L216) in [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes).

Good spot @fleeto.
