### ISSUE TITLE
Inconsistent handling of glossary entries acronyms

### ISSUE THREAD

**Issue by gedimitr** [kubernetes/website#19045]
**This is a Bug Report**

**Problem:**
The acronyms of the various glossary entries are provided inconsistently. Specifically
* The acronym may be provided parenthesized in the title, or provided in the entry body.
* The entry may use the full term as title, or use the acronym for it.
* The acronym may appear in the 'Also known as:' (aka) field.

**Proposed Solution:**
Decide on how acronyms should be provided and adapt glossary entries to follow the same approach. One approach could be to have in the title the full term, followed by the acronym within parentheses.

**Page to Update:**
Multiple pages in https://kubernetes.io/docs/reference/glossary/

**Comment by sftim** [comment]
Good idea @gedimitr 
/kind cleanup
/priority backlog
