### ISSUE TITLE
Issue with `/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/`

### ISSUE THREAD

**Issue by msh1562** [kubernetes/website#1904]
**This is a...** 

- [x] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

**Comment by sftim** [comment]
/triage needs-information
/language en

We don't know what's wrong here, so I assume we won't be able to fix it.
