### ISSUE TITLE
Left menu doesn't work in firefox mobile

### ISSUE THREAD

**Issue by 532910** [kubernetes/website#19040]
https://kubernetes.io/docs/home/

Both firefox are affected: fennec & fenix.
Pressing the left hamburger button just outlines it:

![image](https://user-images.githubusercontent.com/14617699/74099422-b1b47e00-4b34-11ea-974c-aa77b2870e1e.png)
![image](https://user-images.githubusercontent.com/14617699/74099446-ea545780-4b34-11ea-85df-da554e2fb931.png)

**Comment by sftim** [comment]
I think the longer-term work to switch to the [Docsy theme](https://www.docsy.dev/) might help fix that. Anyway:
/kind bug

**Comment by 532910** [comment]
Is it stalled?

**Comment by 532910** [comment]
Is it stalled?

**Comment by sftim** [comment]
Fixed - we're using Docsy now and there is no left menu.
