### ISSUE TITLE
Language ES: Minikube installation fails using "brew cask" (OS X)

### ISSUE THREAD

**Issue by jaruizes** [kubernetes/website#19048]
The command to install minikube in OS X shown in the documentation page (https://kubernetes.io/es/docs/tasks/tools/install-minikube/) is:

`brew cask install minikube`

But this command isn't valid. The command, like in english version is, should be:

`brew install minikube`

Thanks

**Comment by gavinfish** [comment]
I have drafted a PR #18281 to fix this, bu there is no es owners to approve it.

**Comment by raelga** [comment]
Thanks @gavinfish for the PR, has been approved!

**Comment by raelga** [comment]
@jaruizes The fixed documentation has been published, thanks for the PR and welcome to the amazing Kubernetes community!

Feel free to close this issue if you are happy with the fix.

**Comment by jaruizes** [comment]
Thank you!
