### ISSUE TITLE
cpu manager: Cannot allocate all cores to static policy, contradictory documentation

### ISSUE THREAD

**Issue by yanniszark** [kubernetes/website#19051]
**This is a Bug Report**

**Problem:**
The docs in CPU Manager mention:

> Note: System services such as the container runtime and the kubelet itself can continue to run on these exclusive CPUs.  The exclusivity only extends to other pods.

But after that they impose the constraint:

> Note: The kubelet requires a CPU reservation greater than zero be made using either --kube-reserved and/or --system-reserved or --reserved-cpus when the static policy is enabled. This is because zero CPU reservation would allow the shared pool to become empty.

This doesn't seem to make sense.
If the kube and system related resources run in the same exclusive cores as the Guaranteed Pods, then why is it necessary to reserve seperate CPU for them? 

**Proposed Solution:**

Document why the `kube-reserved` option is needed.
The provided explanation doesn't seem to answer that. Quoting:

> This is because zero CPU reservation would allow the shared pool to become empty.

Why do we care if the shared pool becomes empty? 
The kube and system related components should still be able to run.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy

**Comment by sftim** [comment]
I think the page is saying that if Pods use all the CPU in the cgroup that also contains the kubelet, this can starve the kubelet of CPU resource so that it never gets scheduled.

From reading the page, `--reserved-cpus` is making whole-core reservations, of _specific_ cores whereas `--kube-reserved` and `--system-reserved` both reserve fractions of the total CPU resources on a node.

Have I read the page right?

**Comment by sftim** [comment]
It does seem like it's worth improving the wording here.

**Comment by luc99hen** [comment]
I had the same problem understanding this part @sftim

> I think the page is saying that if Pods use all the CPU in the cgroup that also contains the kubelet, this can starve the kubelet of CPU resource so that it never gets scheduled.

According to your explanation, I think the document can be changed to make it more clear
> This is because zero CPU reservation would allow the shared pool to become empty and  can starve the kubelet of CPU resource.
