### ISSUE TITLE
Kubernetes Cluster IP performs Source NAT, contradicting docs: k8s.io/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by rjw245** [kubernetes/website#19053]
**This is a Bug Report**

**Problem:**

The documentation of when Kubernetes performs source NATing contradicts what I see in my deployment.
Here is a description of my issue:
I am having a networking issue in Kubernetes.
I am trying to preserve the source IP of incoming requests to a clusterIP service, but I find that the requests appear to be source NAT'd. That is, they carry the IP address of the node as the source IP rather than the IP of the pod making the request. I am following the example for cluster IPs here: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-clusterip
but I find that the behavior of Kubernetes is totally different for me.
The above example has me deploy an echo server which reports the source IP. This is deployed behind a clusterIP service which I request from a separate pod running busybox. The response from the echo server is below:
```
CLIENT VALUES:
client_address=10.1.36.1
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.152.183.99:8080/
SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001
HEADERS RECEIVED:
connection=close
host=10.152.183.99
user-agent=Wget
BODY
```
The source IP 10.1.36.1 belongs to the node. I expected to see the address of busybox which is 10.1.36.168.
Does anyone know why SNAT would be enabled for a clusterIP? It's really strange to me that this directly contradicts the official documentation. (edited) 

All of this is running on the same node. The node is running in iptables mode. I am using microk8s.

My microk8s version:
```
Client:
  Version:  v1.2.5
  Revision: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
Server:
  Version:  v1.2.5
  Revision: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
```

**Proposed Solution:**

Either correct the documentation and properly describe how to disable source NAT for cluster IPs, or alter Kubernetes behavior to match the documentation

**Page to Update:**
k8s.io/docs/tutorials/services/source-ip/

microk8s 1.2.5

**Comment by sftim** [comment]
@rjw245 I'd like to understand the steps I'd follow to replicate this. If you provide sample command lines, eg `curl http://thing/`, mention where to run each of these.

Would you be willing to add that detail?

**Comment by rjw245** [comment]
You can just follow the steps on the kubernetes documentation page I linked

https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-clusterip

First set up the source-ip-app deployment as shown at the top of the page. Then follow the instructions under the section for ClusterIP, starting with exposing the deployment with a ClusterIP service. It also describes how to test with BusyBox.

**Comment by rjw245** [comment]
I've confirmed this does not happen with minikube. So make sure to use microk8s when testing.

**Comment by rjw245** [comment]
I've submitted an issue to microk8s here:

https://github.com/ubuntu/microk8s/issues/956

**Comment by sftim** [comment]
It sounds like the documentation is correct and that Microk8s isn't behaving as expected. I've not checked that though.

**Comment by rjw245** [comment]
I agree, perhaps this can be closed and we can investigate further in the microk8s bug

**Comment by tengqm** [comment]
/close
Free free to reopen if we still see it a documentation issue.
