### ISSUE TITLE
Short aliases for security content

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#19064]
Hey @sethmccombs @pbnj 👋 (and security sig-docs group).

I'm opening this issue to track a change I made in https://github.com/kubernetes/website/pull/18834 with hopes to improve / simplify security related content. If this is something you'd like to further explore, you can feel free to use this issue to track.

Otherwise, you can also feel free to close this and we will have this as historical reference to the chance / thought behind it.

More context if needed: https://youtu.be/DRNJ4KddfPI?t=1155

**Comment by zacharysarah** [comment]
Heads up that #19068 is relevant to this discussion.

**Comment by jimangel** [comment]
Also adding in https://github.com/kubernetes/website/pull/19077 - the TL;DR is:

`aliases: ["/rbac/","/docs/rbac"]`

for front matter.

**Comment by zacharysarah** [comment]
See #19077 for how to structure aliases

**Comment by pbnj** [comment]
@jimangel - I love the idea of tracking alias in the respective pages' front-matter. I recall trying to visit something similar (`k8s.io/psp` IIRC) previously. Should I go ahead an send in a patch for that?

Thanks for the heads up. I have added it to the agenda for our upcoming sig-docs-security this Thursday, 02/20/2020

**Comment by jimangel** [comment]
> @jimangel - I love the idea of tracking alias in the respective pages' front-matter. I recall trying to visit something similar (`k8s.io/psp` IIRC) previously. Should I go ahead an send in a patch for that?

Yes! Go ahead and open up the PR, ping me if you need an extra set of eyes for review.

**Comment by jimangel** [comment]
Closing with no clear path of what "resolved" looks like. I still support the general idea.

/close
