### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volume-pvc-datasource/

### ISSUE THREAD

**Issue by duanwei33** [kubernetes/website#19073]
**This is a Bug Report**

**Problem:**
It is an enhancement request, suggest adding a note for pvc.spec.resources.requests.storage, like "this capacity must be specified and must be >= the capacity of the source volume", which is well indicated in https://kubernetes.io/blog/2019/06/21/introducing-volume-cloning-alpha-for-kubernetes/ 
It will avoid unnecessary issue. 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/

**Comment by sftim** [comment]
Thanks for the suggestion @duanwei33 

Would you like to contribute the documentation change as well? That process is fairly easy; signing the license agreement is usually the most involved step.
/kind feature
/priority backlog
/sig storage

**Comment by sujaypillai** [comment]
I would like to take this up.

**Comment by huchengze** [comment]
This pr update the note for Chinese.
I hope that I have done this right.

**Comment by duanwei33** [comment]
@sftim @sujaypillai 
I'd like to contribute but sorry it seems I missed the notification after back from holiday. I hope I can do it next time.
And thanks a lot for the update.
