### ISSUE TITLE
Missing option --register-schedulable

### ISSUE THREAD

**Issue by payall4u** [kubernetes/website#19075]
**This is a Bug Report**

**Problem:**
Missing option **--register-schedulable**
**Proposed Solution:**
Add the option and descriptions
**Page to Update:**
https://v1-14.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by bismitaguha** [comment]
@payall4u It is a deprecated flag.

**Comment by sftim** [comment]
@payall4u are you specifically concerned about the docs for Kubernetes v1.14?

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ lists the flag you mention.
