### ISSUE TITLE
Improve configuration concept page: container image pull policies

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#19076]
**This is a Feature Request**

**What would you like to be added**
The container images section in the configuration overview concept page needs clarification.

For reference, see pull request:
https://github.com/kubernetes/website/pull/17141

From the pull request: Update overview.md to reflect imagePullPolicy behavior

**Why is this needed**
Improve the container images section in the configuration concept page.
https://kubernetes.io/docs/concepts/configuration/overview/#container-images

**Comment by tengqm** [comment]
still an unresolved issue.
/reopen

**Comment by sftim** [comment]
I'd move this documentation into https://kubernetes.io/docs/concepts/containers/images/
