### ISSUE TITLE
Issue with /docs/api/

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/website#1908]
**This is a...** 
- [ ] Feature Request
- [ X] Bug Report

**Problem:**

This link [http://kubernetes.io/kubernetes/third_party/swagger-ui/](http://kubernetes.io/kubernetes/third_party/swagger-ui/) in the API Swagger Definitions gives a 404 and seems to keep on trying to reload.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/docs/api/

**Comment by chenopis** [comment]
The link now redirects without a 404; however, the page it arrives at seems incorrect.

![screen shot 2017-01-11 at 3 18 33 pm](https://cloud.githubusercontent.com/assets/24798125/21870449/3f85ef42-d811-11e6-889a-a5a3cc9fb5b2.png)

**Comment by chenopis** [comment]
The link now redirects without a 404; however, the result is not what we want.

![screen shot 2017-01-11 at 3 23 34 pm](https://cloud.githubusercontent.com/assets/24798125/21870607/0cb17324-d812-11e6-9f4f-719523794f86.png)

**Comment by tengqm** [comment]
This has been fixed long time ago.
