### ISSUE TITLE
StartupProbe feature gate default is invalid 

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/website#19080]
**This is a Bug Report**

**Problem:** 
The feature gates page lists `StartupProbe` with a default of `True` in version v1.17. 

However, the feature gate's default is `False`:
https://github.com/kubernetes/kubernetes/blob/v1.17.2/pkg/features/kube_features.go#L632

It looks like it was promoted in v1.18:
https://github.com/kubernetes/kubernetes/commit/6603f41a1307ca69c033204fe3a534e64b387325

**Proposed Solution:**
Update the feature gates lists to set the correct default value.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by alexbrand** [comment]
It seems like the startup probe documentation could also include a note about Startup Probes being behind a feature flag.

**Comment by sftim** [comment]
Fixed in PR #19098 - right?
/kind bug
/close
