### ISSUE TITLE
Add a subsection dedicated to quickly find snippets of object definition in YAML ready to be copy and paste

### ISSUE THREAD

**Issue by remyleone** [kubernetes/website#19096]
**This is a Feature Request**

**What would you like to be added**

I would like to have a section of the website optimized to quickly find commented snippets of code for all major object. Typically a page that contains different snippets/examples of object definition ready to be copy and paste.

**Why is this needed**

When someone wants to find a snippet to create an object, the typical way of doing it is to go through tasks and tutorials to find an example and copy and paste it. This requires a user to know in which tutorial/example to look in to find the right snippet.

This is particularly true during certification when a candidate can only use the kubernetes.io website to find this information. Maybe a snippet section optimized to quickly find a template could help them save some time during the exam.

**Comment by tengqm** [comment]
Actually we can add examples to the kubernetes reference page. 
For example, if you check https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#deployment-v1-apps, you will find that there is an example button.
To move forward with this, we can add more examples to [this directory](https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-apidocs/config/examples), then new API reference generated will automatically pick them up.
