### ISSUE TITLE
Issue with /docs/user-guide/liveness/

### ISSUE THREAD

**Issue by timstoop** [kubernetes/website#1909]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I'm trying to find an example of using the tcp socket action as a liveness probe. This page only describes http and exec types of checks.

**Proposed Solution:**
Please provide an example for the tcp socket request as well.

**Page to Update:**
http://kubernetes.io/docs/user-guide/liveness/

**Comment by tengqm** [comment]
This issue has been solved properly in #3494.
