### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/names/

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/website#19099]
**This is a Bug Report**

**Problem:** Could you please add the resource types which have additional naming restrictions?

**Proposed Solution:** Add the types of resources having additional naming restrictions

**Page to Update:**
k8s.io/docs/concepts/overview/working-with-objects/names/

Thanks!

**Comment by tengqm** [comment]
Working on this.

**Comment by tengqm** [comment]
This is done.
/close
