### ISSUE TITLE
Add information to style guide version shortcodes

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#19095]
**This is a Feature Request**

Update the _Style guide_ with instructions and scenarios for using the `latest-version` and `release-branch` shortcodes. 

**What would you like to be added**

A new section in the Style guide documenting the `latest-version` and `release-branch` shortcodes; explan how to use the shortcodes and when to use the shortcodes.

**Why is this needed**

These version related shortcodes help prevent hard coded release versions in the documentation.

**Comments**
If you require further information, ping @kbhawkey .

**Comment by sftim** [comment]
Is this a /help wanted issue @kbhawkey ?

**Comment by kbhawkey** [comment]
@sftim, probably? I will temporarily (several days) assign myself as there may be more version related shortcodes created/modified.
/assign

**Comment by jimangel** [comment]
Does https://github.com/kubernetes/website/pull/18173 change anything for this?

**Comment by kbhawkey** [comment]
Hi. I logged this issue to document or update the documentation related to version shortcodes.
Authors can lookup descriptions about the version shortcodes and use these shortcodes to author version numbers in the content.
Recently the contribute section has been updated (and soon new skew/version policies (@jimangel)).
I am in favor of using meaningful version shortcodes in the content instead of generic shortcodes such as ```{{< param "version" >}}```.
I wonder if  a short description for each version shortcode or a table with all version shortcodes would be helpful.

Here is the list of the docs version-related shortcodes (not including the new skew shortcode):

```
latest-semver
latest-version
latest-release-notes
param
release-branch
versions-check
versions-other
config.toml has two equivalent variables (version and latest) at the global level.
```

**Comment by kbhawkey** [comment]
📢 Help wanted:
I suggest to add a brief description and example of how to use the most basic (custom) version shortcodes (pick one or two): `param`, `latest-version`, `latest-semver`.
Review the [contribute section](https://kubernetes.io/docs/contribute/) and decide where this content should be added.
I am happy to assist and review.
/help

**Comment by sftim** [comment]
I would probably add that guidance to https://kubernetes.io/docs/contribute/style/hugo-shortcodes/
/triage accepted
