### ISSUE TITLE
Rename "getting-started guides" to "cluster creation guides"

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/website#191]
The so-called "getting-started guides" are misnamed. They're about cluster creation and porting Kubernetes (getting-started from scratch). We should change the names to reflect that. 

Of course, we'll need to magically forward all the links.

Getting started should really just require executing one command, to create a single-node cluster.

cc @pwittrock @janetkuo @dlorenc

**Comment by johndmulhausen** [comment]
When you say "Rename" do you mean changing the URL of everything under getting-started-guides?

**Comment by jaredbhatti** [comment]
yeah, I agree with this statement.  I think we need to figure out what we're going to do with the getting started guides long term with the new site structure.
