### ISSUE TITLE
kubernetes on arm64 platform support 

### ISSUE THREAD

**Issue by harsh151028** [kubernetes/website#19102]
i want to setup kubernetes and minkube   in my arm64 debian qemu vm  but  i'm unable to do this 
because in the official site there is no any link is given to arm64 platform kubernetes and minikube setup ,
can you plz provide any blog or resource by which i can setup kubernetes and minikube on arm64 debian platform

**Comment by sftim** [comment]
Documenting Kubernetes specifically for the ARM64 /AArch64 platform would be a bit of a stretch. You're very welcome to _contribute_ documentation @harsh151028. Also, I have a PR about using kubeadm that should be a bit clearer once I tidy it up.

/kind feature
/priority awaiting-more-evidence
