### ISSUE TITLE
Highlight Kubernetes Training: CKA/CKAD and Intro to Kubernetes edX.org

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/website#19112]
This is a response to @timstclair:
https://twitter.com/cra/status/1227977913393438721

We highlight KTPs on the partners page but for individuals, we should find a way to highlight the free Intro to Kubernetes course on edX.org + the CKA/CKAD courses. Anything we can do to highlight education options for the Kubernetes ecosystem is a win.

**Comment by tallclair** [comment]
@timothysc

**Comment by celestehorgan** [comment]
👋  @zacharysarah asked me to look at this.

If I understand correctly, the things we want to highlight are:
- The free edX courses here: https://www.edx.org/learn/kubernetes
- The different training programs provided by the companies here: https://kubernetes.io/partners/#ktp
- k8s training and certs here: https://training.linuxfoundation.org/

Is there anything else that comes to mind?

In terms of execution: I think the best option (also suggested by Zach) would be to add a "Training" menu item to the top nav. As smart as pointing people to relevant training in sections of the documentation might be, I think it would leak vendor/company-specific content into the documentation, which is a no-no.

**Comment by zacharysarah** [comment]
@celestehorgan Sounds good! ➕
