### ISSUE TITLE
kubectl exec wget fails with ssl_client: app-svc: certificate verification failed

### ISSUE THREAD

**Issue by Newbie112222** [kubernetes/website#19125]
HI,
I am trying to run a request via wget by using the following kubectl command:
I am able to SSH into the pod by using this:
kubectl exec -it podname sh

When running wget i see this issue: 
ssl_client: app-svc: certificate verification failed: unable to get local issuer certificate
wget: error getting response: Connection reset by peer

Any ideas how to fix this issue?
*
*This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
For questions not related to the documentation, please try stackoverflow, e.g. [search for kubectl exec](https://stackoverflow.com/search?q=kubectl+exec), or ask questions on the [slack channel](https://kubernetes.slack.com/archives/C09NXKJKA).

In your case, obviously 'kubectl exec -it ...' worked, you have got some troubles running 'wget'. That is not something related to k8s.

/close
