### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy/

### ISSUE THREAD

**Issue by fjammes** [kubernetes/website#19146]
**This is a Bug Report**
**Problem:**
Documentation should tell which weave versions support egress/ingress NetworkPolicies
**Proposed Solution:**
Add this information inside the documentation
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy/

**Comment by sftim** [comment]
Hi @fjammes 

Documentation for Weave Net is at https://www.weave.works/docs/net/latest/

As a policy choice, Kubernetes (and specifically SIG Docs) doesn't usually track version compatibility for external projects. If there is a page in the Weave Net documentation, it would be OK for 
https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy/ to link there.

**Comment by fjammes** [comment]
Hi @sftim 

Thanks.
I had a look inside documentation for Weave Net, but it seems it does not say currently if both egress and ingress NetworkPolicies are supported.

**Comment by sftim** [comment]
Kubernetes documentation does not cover out-of-project components such as Weave Net.
For help with Weave Net (including when used with Kubernetes), the best place to look is the documentation for Weave Net itself.

/close
