### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/feature-gates/

### ISSUE THREAD

**Issue by rdicroce** [kubernetes/website#19153]
**This is a Bug Report**

**Problem:**
The Feature Gates page does not adequately explain how to toggle feature gates. All it says is

> To set feature gates for a component, such as kubelet, use the --feature-gates flag assigned to a list of feature pairs

which is not very specific. What command(s) do I execute (or what file(s) do I modify) to make that happen? Do I need to do this on control nodes, worker nodes, or both?

**Proposed Solution:**
The Feature Gates page should answer the above questions.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by tengqm** [comment]
The --feature-gates flag exists for many kube components, e.g. `kube-apiserver`, `kube-controller-manager`, etc. Given that there are many ways Kubernetes are deployed, it is difficult to "adequately explain" how to specify this flag. You have to figure out how other command line flags are specified for your installation. The `--feature-gates` flag is not an exception.
It is not appropriate to answer this question. 
Feel free to reopen this issue if you have got any suggestions to improve the doc. Thanks.
/close
