### ISSUE TITLE
Issue with k8s.io/docs/concepts/containers/images/

### ISSUE THREAD

**Issue by TiloGit** [kubernetes/website#19156]
**This is a Document issue Report**

**Problem:**
Please clarify how existing image is identified. By Name only or compare SHA?

**text states:** 

> The default pull policy is IfNotPresent which causes the Kubelet to skip pulling an image if it already exists. 

**Page to Update:**
https://kubernetes.io/docs/concepts/containers/images/

Please clarify documentation

**Comment by sftim** [comment]
Thanks for the suggestion @TiloGit 

With IfNotPresent, the kubelet considers an image present if there is at least one pulled image that matches the `image` specification for that container.

So, if a Pod specifies an image by a hash, and there's no container with that specific hash present, the kubelet triggers a pull. If a Pod specifies an image by name, and there's a container with that name present, the kubelet does not trigger a pull. If a Pod specifies an image by name combined the `latest` tag and there's a local container image but it doesn't match the registry's idea of `latest`, the kubelet pulls the image. If a Pod specifies an image by name combined some other tag, eg `example:2020-02-17`, tag and there's a local container image that matches the image name but not the `2020-02-17` tag, the kubelet pulls `example:2020-02-17`.

With Always, the kubelet always pulls the image.

I'll add
/help
too: if someone wants to improve https://kubernetes.io/docs/concepts/containers/images/ then please go ahead.
