### ISSUE TITLE
Consistent slowness in website with static resources

### ISSUE THREAD

**Issue by artisticcheese** [kubernetes/website#19154]
**This is a Bug Report**

**Problem:**
Random static files on Kubernetes.io introduce 6s delay. Sample powershell oneliner below showcasing the issue

```
PS /home/gregory> 1..10 | foreach-object { measure-command {Invoke-WebRequest https://kubernetes.io/css/style.ce36324c2d8bc083b7ea1e9b3e3b1c05228556e6cc00e5a2606f9f252871c32e.css} | select Seconds}
Seconds
-------
      6
      0
      6
      0
      0
      6
      6
      0
      6
      0
```
**Proposed Solution:**
Fix website
**Page to Update:**
Entire website is affected

**Comment by sftim** [comment]
That's unexpected.
Here's a script to try the same thing out on a more Unixy platform
```bash
( seq 1 200 | while read seq; do time curl -s -I https://kubernetes.io/css/style.ce36324c2d8bc083b7ea1e9b3e3b1c05228556e6cc00e5a2606f9f252871c32e.css > /dev/null ; sleep 0.25; done ) 2>&1 | awk '/^real/ { print $2}'
```
```console
0m6.431s
0m6.388s
0m0.073s
0m6.399s
0m6.236s
0m0.070s
0m0.073s
0m0.074s
0m0.069s
0m6.240s
0m0.073s
0m0.073s
0m0.070s
0m0.073s
0m0.073s
0m6.320s
0m0.071s
0m0.073s
```

**Comment by artisticcheese** [comment]
I run it on UNIX too, just in powershell core. Just FYI.

**Comment by sftim** [comment]
The response headers show that the CSS isn't cacheable (`max-age=0`). Maybe Netlify is having a bad day and a fraction of requests are taking a while to serve - 6 second timeout somewhere perhaps?

```
HTTP/2 200 
accept-ranges: bytes
cache-control: public, max-age=0, must-revalidate
content-length: 41494
content-type: text/css; charset=UTF-8
date: Mon, 17 Feb 2020 21:45:39 GMT
etag: "b356342c27e3849dd8281dc69ac21894-ssl"
strict-transport-security: max-age=31536000
age: 0
server: Netlify
x-nf-request-id: 2fa912eb-4eb8-47fc-8fa6-37e8814b4784-9939259

**Comment by artisticcheese** [comment]
This issue has been persistent for at least couple of weeks.

**Comment by sftim** [comment]
@artisticcheese do you think this sounds like a Netlify issue? I don't know how much you've already investigated.

**Comment by artisticcheese** [comment]
I did not do any sort of investigation obviously since I don't control web servers. All I know that there is  issue ongoing for couple of weeks where random resources are being served with 6s delay and based on response headers they seemed to be coming from different servers

**Comment by sftim** [comment]
The Kubernetes website is served via a SaaS platform, [Netlify](https://www.netlify.com/)

So far I've made only cursory investigations.

**Comment by zacharysarah** [comment]
That's really weird behavior. @sftim Let's talk about this in tomorrow's weekly meeting.

**Comment by artisticcheese** [comment]
Was anything done to fix the issue. Every single page I load takes 6 seconds to fully load as result. I understand people don't feel 6s delay in webpage is not considered loss of functionality but going quickly through documentation with tons of links between page becomes a real problem

**Comment by zacharysarah** [comment]
@artisticcheese Please be patient. We have limited resources and are working as quickly as we can.

**Comment by jimangel** [comment]
Partially related, I noticed that the `kub_video_banner_homepage.jpg` is HUGE (at `1.8MB`) and takes ~2-3 seconds to load for me. Optimizing that to hundreds of KB or less would help (not fix) the load time.

![image](https://user-images.githubusercontent.com/4601051/75292227-6a431880-57e9-11ea-9113-b79f3306613f.png)
