### ISSUE TITLE
Tutorials feedback form does not use available space

### ISSUE THREAD

**Issue by engrjislam** [kubernetes/website#19163]
**Problem:**
It's neither a bug nor a actual issue. The problem is actually the window size of a for feedback for each interactive tutorial. It has a scroll which is not much visible (at least to me!). 

[Google feedback form for interactive tutorial](https://ibb.co/K602WYg)

**Comment by sftim** [comment]
That link is to a picture:
![kubernetes-katacoda-google-form-feedback-2](https://user-images.githubusercontent.com/22591623/74791609-d6d28a80-52b2-11ea-9b9c-8cecd6f11a96.jpeg)

**Comment by sftim** [comment]
/retitle Tutorials feedback form does not use available space
/priority important-longterm
/cc @BenHall

**Comment by BenHall** [comment]
Thanks, a fix for this will be live later today.

**Comment by BenHall** [comment]
This has been resolved and the ticket can be closed.
