### ISSUE TITLE
kubeadm init --pod-network-cidr=10.240.0.0/16

### ISSUE THREAD

**Issue by ravivp** [kubernetes/website#19167]
W0218 15:06:04.281225   14762 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0218 15:06:04.281418   14762 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.3
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by neolit123** [comment]
> [ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
[preflight] If you know what you are doing, you can make a check non-fatal with --ignore-preflight-errors=...

your VM / machine (or Kubernetes Node) needs to have at least 2 CPU cores.

/triage support
/sig cluster-lifeecycle

**Comment by RA489** [comment]
@ravivp As a workaround If you want you can skip preflight error using `--ignore-preflight-errors=NumCPU`

**Comment by neolit123** [comment]
no comments for a few months.
/close
