### ISSUE TITLE
Request to provide a clear documentation for CA rotation for those who want to do it

### ISSUE THREAD

**Issue by abhiTamrakar** [kubernetes/website#19165]
**This is a Bug Report**

**Problem:** There is no documentation for CA rotation, kubernetes does not supports it through kubeadm and it is also not documented anywhere.
Issue link: https://github.com/kubernetes/kubeadm/issues/2027

**Proposed Solution:**
I tried and successfully rotated the CA manually, there are some issues with kubelet which I am working but otherwise I was able to rotate the CA.
Steps recorded in https://github.com/kubernetes/kubeadm/issues/2027. If this is not the right way, I would say help me and other people who would want to do it.
For example, my organization has a mandate to rotate CA every year and if this is documented somewhere, it would be a big help for people me and everybody using kubernetes.

**Page to Update:**
https://kubernetes.io/docs/tasks/tls/certificate-rotation/

Kubernetes Version: v1.16.x and v1.15.3

Additional Information: 
The documentation should be a separate page references in https://kubernetes.io/docs/tasks/tls/certificate-rotation/ somewhere, so that people can actually make use of it.

This issue https://github.com/kubernetes/website/issues/18169 has some information but it is not very much related to CA rotation.

**Comment by neolit123** [comment]
@abhiTamrakar as pointed out earlier, it would be best to notify SIG Auth on their slack channel or zoom meeting about this ticket.

**Comment by abhiTamrakar** [comment]
@neolit123 Yes sure, will do that.

**Comment by sftim** [comment]
Is this also /sig cluster-lifecycle?

**Comment by neolit123** [comment]
> Is this also /sig cluster-lifecycle?

ideally the documentation for CA rotation should be deployer agnostic (e.g. not being a guide for kubeadm).

**Comment by sftim** [comment]
I was thinking about cluster lifecycle in general per https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/charter.md#sig-cluster-lifecycle-charter rather than specifically about `kubeadm`.

**Comment by abhiTamrakar** [comment]
@sftim It should be a part of cluster lifecycle as certificates would anyways be a part of it, irrespective of the individual segregation of entities.

**Comment by neolit123** [comment]
> I was thinking about cluster lifecycle in general per https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/charter.md#sig-cluster-lifecycle-charter rather than specifically about kubeadm.

it's certainly not in the SIG Cluster Lifecycle charter to own this space or to document it.
so it's up to SIG Auth to drive this and CL can give feedback.

/sig cluster-lifecycle

**Comment by ch-yogya** [comment]
I'd like make a PR documenting how to do this.

**Comment by abhiTamrakar** [comment]
preventing it from rotting, since the PR is WIP

/remove-lifecycle stale

**Comment by neolit123** [comment]
the document merged

https://github.com/kubernetes/website/pull/19351
https://github.com/kubernetes/website/pull/21651

/close
