### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/

### ISSUE THREAD

**Issue by hyeagle** [kubernetes/website#19164]
**This is a Bug Report**

**Problem:**
Following these operations, the error is return:
ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (110)
The error shows that the server host is not exist.
In "-h mysql", it means "mysql" is server host, but where is it defined?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

1.17

**Comment by rajeshdeshpande02** [comment]
Hi @hyeagle ,

Thanks for raising the issue. This example is working perfectly fine. Before running MySQL client, you need to deploy MySQL server using steps given on the same page. 

Also, in '-h mysql ', mysql is a name of service(type ClusterIP) which exposes MySQL server.

**Comment by hyeagle** [comment]
> Hi @hyeagle ,
> 
> Thanks for
 raising the issue. This example is working perfectly fine. Before running MySQL client, you need to deploy MySQL server using steps given on the same page.
> Also, in '-h mysql ', mysql is a name of service(type ClusterIP) which exposes MySQL server.

**Comment by hyeagle** [comment]
Hi @rajeshdeshpande02 ,

Thank you for your kind response.

I run these following command:
`kubectl apply -f https://k8s.io/examples/application/mysql/mysql-pv.yaml`,
`kubectl apply -f https://k8s.io/examples/application/mysql/mysql-deployment.yaml`.

So, I think that I have deployed MySQL server. But after I run this command:
`kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql -ppassword`, the error still exists.

In addition, if I run this command `kubectl exec -it <mysql-pod-name> -- mysql -h mysql -ppassword`, the error also exists. But if I remove "-h mysql", the error disappears. 

So, may be DNS related services, like Headless service, do not work. Do I need to make extra settings?

Best wishes.
