### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/namespaces/

### ISSUE THREAD

**Issue by ingnil** [kubernetes/website#19161]
**This is a Bug Report**

**Problem:**

Without explanation, the text suddenly starts referring to contexts while talking about namespaces. But they are completely different, as contexts refer to entire clusters, while namespaces are a subdivision of a specific cluster.

While I know how contexts and namespaces differ, I could understand how this could confuse new users.

**Proposed Solution:**

Remove the parts about checking and changing contexts. Put it in a separate page, if such a page doesn't already exist.

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Better separation of those concepts sounds like a good idea.
/help
/priority backlog

**Comment by tengqm** [comment]
/close
Looks like #19334 has fixed this.
