### ISSUE TITLE
“Managing Service Account” uses Latin abbreviation in heading

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19179]
_This is a_ good first issue. _If you have already contributed a pull request to Kubernetes documentation, please consider leaving this fix for someone who is getting started._

**Problem:**
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#user-accounts-vs-service-accounts uses Latin text in a heading.
In the documentation style guide, SIG Docs recommends [avoiding Latin phrases](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-latin-phrases). That recommendation is particularly relevant for headings because heading text is more visible.

**Proposed Solution:**
Edit https://github.com/kubernetes/website/blob/master/content/en/docs/reference/access-authn-authz/service-accounts-admin.md to use a new heading. For example, use the word “compare”, or the full word “versus”.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/

**Additional Information:**
/good-first-issue
/language en
/priority backlog
/kind cleanup

**Comment by sftim** [comment]
Typically, if someone changes a heading in a page, we consider the impact on links to that heading's fragment identifier. In this case it's a change to the first heading of the main content, so the user experience isn't much affected even if inbound links become broken.

**Comment by aallbrig** [comment]
@sftim I can pick this up :)
