### ISSUE TITLE
Invalid link in readme section

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#19177]
**This is a Bug Report**

**Invalid link in readme section:**

**Proposed Solution:**

**Page to Update:**
https://github.com/kubernetes/website/blob/master/README-ru.md

**Now:**
https://github.com/kubernetes/website/blob/master/README-ru.md#running-the-site-locally-using-hugo

**To**
https://github.com/kubernetes/website/blob/master/README-ru.md#%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D1%81%D0%B0%D0%B9%D1%82%D0%B0-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-hugo

**Comment by php-coder** [comment]
It has been fixed by #19178

/close
