### ISSUE TITLE
Update contributor guide to enable reviewers/approvers to indicate willingness to mentor

### ISSUE THREAD

**Issue by bradtopol** [kubernetes/website#19175]
**This is a Feature Request**

The contributor guide should be updated to suggest/encourage that reviewers and approvers should indicate their willingness to serve as a mentor. This can and should be done in a general fashion or even on specific issues that would be "good first issues" or "good second issues" . 

The motivation for this is that by being more proactive about providing mentors, we will have a greater likelihood of expanding the number of contributors to kubernetes/website.

/cc @sftim @zacharysarah

**Comment by sftim** [comment]
I'm going to mark this one as:
/sig contribex

**Comment by sftim** [comment]
/sig contributor-experience
?
