### ISSUE TITLE
{{ .Summary }} is empty -> Description tag is empty -> SEO going down 

### ISSUE THREAD

**Issue by remyleone** [kubernetes/website#19188]
**This is a Bug Report**

**Problem:**

If you take a page that does not have a `summary` hugo parameter the HTML meta tag for description is empty. If this tag is empty SEO is suboptimal. :chart_with_downwards_trend:  

https://github.com/kubernetes/website/blob/470f932dd8649592152b0388c653d114e81ee74d/layouts/partials/head.html#L20-L25

**Proposed Solution:**

Either we make the `{{ .Summary }}` work or we replace it with something different for default.

**Page to Update:**

All the pages that have not a description. (A lot of them are like that)

**Comment by remyleone** [comment]
https://discourse.gohugo.io/t/summary-empty/23528/2

**Comment by sftim** [comment]
I think I'm -0 (soft negative) to adding a default description - the tools that crawl websites have enough machine learning chops to spot this technique and not to fall for it.

On the other hand, I am a :+1: to making sure that at least the N most popular pages have a description set in their metadata.

**Comment by remyleone** [comment]
I want to add a default because it not a good idea to have an empty description that is frown upon by all tools that perform SEO audits that I know. In parallel, we can add better-written descriptions for the most popular pages. We can have both. But this is not related to this issue of `{{ .Summary }}` hugo tag not working.

**Comment by kbhawkey** [comment]
I am guessing that the .Summary page variable is just not accessible based upon the way the pages are constructed. When the docs acquire a new theme, I would expect that this variable would be accessible.
