### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/common-labels/

### ISSUE THREAD

**Issue by mig4** [kubernetes/website#19199]
**This is a Bug Report**

**Problem:**

Is it me or is the wordpress example not quite right? Specifically it seems it's not easy to tell which wordpress instance are the mysql objects are part of. I'd have expected either `app.kubernetes.io/part-of` to include instance suffix or `app.kubernetes.io/instance` to be `wordpress-abcxzy`?

**Proposed Solution:**

As above, probably `app.kubernetes.io/part-of` should be `wordpress-abcxzy`, but the meaning of `app` is not clear (is it a more complete _solution_ hiding details like it's built on `mysql`, or is it more an individual component), so it could be that `app.kubernetes.io/instance` for _mysql_ should also be `wordpress-abcxzy`. Or perhaps a new label like `app.kubernetes.io/solution-instance` (I didn't want to use `app-instance` as this seems more confusing, but something along those lines)?

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by mig4** [comment]
I think this is still a valid question, I'm happy to sumbit a PR once somebody checks my reasoning and we can come up with a clearer example.

**Comment by sftim** [comment]
I agree with the example labeling in https://k8s.io/docs/concepts/overview/working-with-objects/common-labels/

Let's say you have a namespace called "billing-dev" and in that namespace there are some resources labelled     `app.kubernetes.io/name: mysql`. That seems enough to identify that those resources are all there to deliver an app called _mysql_.

The resources will also have `name` and `uid` attributes in their `.spec` and `.status` respectively, but those aren't enough to tell someone querying the cluster what those Pods, PersistentVolumes, StatefulSets, ConfigMaps etc are _for_. That's where the recommended labels come in.

If anyone's keen to revise the page to explain that, please go ahead. I'd leave the actual labels as-is.

**Comment by sftim** [comment]
(If you have more than one mysql in the namespace, you could give each of them a more human-friendly name like `mysql-billing-records` or `mysql-userauth`).

**Comment by mig4** [comment]
> (If you have more than one mysql in the namespace, you could give each of them a more human-friendly name like `mysql-billing-records` or `mysql-userauth`).

Yes, this was my assumption, sorry I should've been more explicit. But so which attribute do you think should hold that human-friendly name, just the resource `Name`? or app name, or app instance labels?
