### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-initialization/

### ISSUE THREAD

**Issue by gitsilos** [kubernetes/website#19210]
K run <podName> --image=nginx --generator=run-pod/v1 should be deprecated.

k create pod <PodName> --image=nginx                      should be next wave

High end of confusion that deployment is created if we generator. Very easy to deprecate and create new methods.

**Comment by Kartik494** [comment]
kubectl run image work fine
root@master:/home/vagrant# kubectl run nginx --image=nginx --generator=run-pod/v1
pod/nginx created
