### ISSUE TITLE
Issue with k8s.io/docs/tutorials/online-training/overview/

### ISSUE THREAD

**Issue by liuyl2022** [kubernetes/website#19229]
**This is a Bug Report**

**Problem:**
The [IBM Cloud: Deploying Microservices with Kubernetes](https://www.coursera.org/learn/deploy-micro-kube-ibm-cloud) on Coursera is gone.
**Proposed Solution:**
Replace it with the correct link or delete it.
**Page to Update:**
https://kubernetes.io/...

**Comment by gavinfish** [comment]
This will be fixed by #18836.

**Comment by Dean-Coakley** [comment]
This can be closed then? 
Resolved by: https://github.com/kubernetes/website/pull/18836
