### ISSUE TITLE
error: the path "dashboard.yaml" does not exist

### ISSUE THREAD

**Issue by engrjislam** [kubernetes/website#19225]
**Problem:**
It seems there is no **dashboard.yaml** file exists in [Getting Started With CRI-O and Kubeadm](https://www.katacoda.com/courses/kubernetes/getting-started-with-kubeadm-crio) tutorial environment (at _**Step 6 fo 6**_). For sure 

    ls -al

command executed to get all files into the tutorial environment. Unfortunately the file also neither exists at the [link](https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml) as described at the last.

**Comment by neolit123** [comment]
Hi, this is not a k/website issue thought? Please try reporting it to
Katacoda.

/close
