### ISSUE TITLE
Post 1.18 follow-up: netlify configuration for kubernetes-io-vnext-staging

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#19238]
In working with netlify previews in the 1.18 release, @jimangel and I noticed that PRs on the netlify staging branch (`kubernetes-io-vnext-staging`) do not invoke the same CI checks as PRs on `master`. 

This is probably due entirely to a difference in netlify configuration. It's worth investigating after 1.18 releases and making sure that the dev branch invokes all CI checks.

/milestone 1.18

**Comment by sftim** [comment]
/triage accepted

Also cc: @annajung

**Comment by kbhawkey** [comment]
Hi. I started to dig into the netlify deploy contexts for the branches.
Is the `kubernetes-io-vnext-staging` branch using the `deploy-preview` or `production` context?
Which build command is used for this branch, `make deploy-preview`?
The Build&Deploy variable "Deploy log visibility" is public, however, the Deploy Summary for this branch
lacks the netlify page metadata. I see that the information is available, just not in the summary in the PR.
The publish directory is not set for the staging branch. I am guessing that it defaults to "public".
Other ideas?
