### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by lvishank** [kubernetes/website#19242]
The Interactive terminal is unresponsive.
++++++++++++++++++++++++++++++++++++++++++++
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
This was due to a (fixed) server-side fault.
/close
