### ISSUE TITLE
Translate tasks/access-application-cluster/configure-access-multiple-clusters/ into Japanese

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#19248]
**This is a Feature Request**

**What would you like to be added**
Translate tasks/access-application-cluster/configure-access-multiple-clusters/ into Japanese.

**Why is this needed**
This page has not been translated.

**Comments**
/language ja

**Comment by joekamibeppu** [comment]
I've opened a PR for this issue [here](https://github.com/kubernetes/website/pull/19563).
