### ISSUE TITLE
The labels should be changed in the `Expose Your App Publicly` section

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/website#19264]
**This is a Bug Report**

**Problem:** The labels in the following commands are wrong -
```
kubectl get pods -l run=kubernetes-bootcamp
kubectl get services -l run=kubernetes-bootcamp
```

**Proposed Solution:**
The labels should be changed and the commands on the page should be -
```
kubectl get pods -l app=kubernetes-bootcamp
kubectl get services -l app=kubernetes-bootcamp
kubectl label pod $POD_NAME version=v1
kubectl get pods -l version=v1
```

Similarly, on the Step 3 of the tutorial, the command should change to the following -
```
kubectl delete service -l app=kubernetes-bootcamp
```

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

I am using the latest version of minikube on Windows 10 -
```
PS C:\> minikube version
minikube version: v1.7.3
commit: 436667c819c324e35d7e839f8116b968a2d0a3ff
```

On a side note, is it possible to update the minikube version inside katacoda?

**Comment by sftim** [comment]
Possibly also relevant: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by sftim** [comment]
@blueelvis, can you explain why you'd like that change to happen? I think I can guess, but it'd be good to be sure.

**Comment by blueelvis** [comment]
@sftim - Sorry for not being clear in my original post. With the labels which are mentioned in the tutorial, the command to get the pods with label filtering doesn't work. I tried with the latest image. Instead, they are set as below -

![image](https://user-images.githubusercontent.com/6985763/75284698-4c9e9f00-583b-11ea-9a2f-2f5db9b6568d.png)

The label which is set is not `run` but instead `app`.

**Comment by sftim** [comment]
`kubectl get pods -l run=kubernetes-bootcamp` works for me when I try it @blueelvis

Why do you feel that the existing labels aren't right?

**Comment by celestehorgan** [comment]
Hi @blueelvis,

Why do you feel the labels are incorrect, per @sftim 's earlier question? 

If we receive no response we will close this issue.

**Comment by sftim** [comment]
> On a side note, is it possible to update the minikube version inside katacoda?

I think this is the nub of it actually. If you use the latest Kubernetes version locally, these steps are not correct.

/kind bug
/triage accepted
/remove-lifecycle rotten
/language en
/priority important-longterm

**Comment by jai** [comment]
This has been fixed. The latest/current version of the tutorial uses `app=`:

> Let’s use this label to query our list of Pods. We’ll use the kubectl get pods command with -l as a parameter, followed by the label values:
> 
> kubectl get pods -l app=kubernetes-bootcamp
> 
> You can do the same to list the existing services:
> 
> kubectl get services -l app=kubernetes-bootcamp

Looks like it was fixed in [this commit](https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/commit/345ec781866d7a93d32f85381bc18916dea09700)

/close

**Comment by jai** [comment]
@sftim I think this issue can be closed, can you confirm?
