### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by shu8hamrajput** [kubernetes/website#19274]
interactive console is not working.
How do i make it to work?
![Screenshot from 2020-02-24 11-26-10](https://user-images.githubusercontent.com/42935066/75131341-a64a8080-56f8-11ea-92a0-a006cbbf27eb.png)

**Comment by BenHall** [comment]
Thanks for reporting. We had an issue with some of the servers. This has been fixed.
