### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by rexagod** [kubernetes/website#19275]
Terminal fails to start with the message, `Error Details: Environment not starting correctly. Please contact Support@Katacoda.com`.

I've also reported this to Katacoda.

**Comment by BenHall** [comment]
Thanks for reporting. We had an issue with some of the servers. This has been fixed.

**Comment by rexagod** [comment]
No problem, and thank you for the quick response!
