### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by abid-mumtaz** [kubernetes/website#19288]
**This is a Bug Report**

**Problem:**

At the start of this tutorial in section "Create a Minikube cluster" after step 1 clicking the "Launch Terminal" button the following steps 2, 3 and 4 don't seem to work: - 

> 2. Open the Kubernetes dashboard in a browser:
> minikube dashboard

Actual Result: - "
```
* Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
http://127.0.0.1:44535/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/"
```
**Problem:** The command prompt never returns to allow the user to type in anymore commands and continue with the tutorial. 

Step 3 works but step 4 does not: - 
> 3. Katacoda environment only: At the top of the terminal pane, click the plus sign, and then click Select port to view on Host 1.
> 4. Katacoda environment only: Type 30000, and then click Display Port.

**the problem:** 
After typing in the port in the new browser tab and clicking the button
Nothing happens on the tab expect that 
all it says is (and nothing changes after that): - 
> Connecting to Port 30000
> We're currently trying to connect to a HTTP service running on 30000. Services can sometimes take a few moments to start, even upto five minutes.
> 

Steps 2, 3 and 4 on this page at the start do just leave the user hanging and nothing appears to happen on the terminal nor on the browser tab. I maybe just me, but I tried a few times hoping that something would happen, then gave up and carried on by trying to other steps. The expected output is not mentioned for these steps (this is important for a novice , to make sure they are doing the right thing on each step) 
Note: Tutorials and good for a K8s novice like me and good to follow (and TRY in a browser) ..so like it (Thanks!!!), so please take the above as constructive criticism to help other Novices, including myself.   I hope this makes sense. 
**Proposed Solution:**
Add a fews lines on what is expected to be seen and if there is a delay then worth mentioning to wait until user sees the change. I realised after a few failed attempts that nothing would happen so I just did unscripted steps to skip ahead which seem to work, like openning a new terminal and starting the rest of the tutorial in a new terminal window , as the 
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@abid-mumtaz can you clarify whether you were trying this on your own PC or inside the Katacoda learning environment? That information will help people understand the issue you're reporting.

**Comment by abid-mumtaz** [comment]
Apologies.....yes inside Katacoda

**Comment by RA489** [comment]
https://github.com/kubernetes/website/issues/18984

**Comment by sftim** [comment]
I think this is fixed.
@abid-mumtaz is this now working OK for you?
