### ISSUE TITLE
Translate concepts/cluster-administration/manage-deployment.md into Japanese 

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#19280]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**
This document is not translated in Japanese.
**Comments**

Copy a file from en contents to content/ja/docs/concepts/cluster-administration/manage-deployment.md and translate it into Japanese.

**Comment by inductor** [comment]
@kakts これってどうなりました？

**Comment by kakts** [comment]
すいませんこれ全然進めれてなかったです
今月中にはPR出せるように進めます

**Comment by inductor** [comment]
@kakts masterベースでやってもらっても問題ないですか？（新しいルールで行こうかなと）

**Comment by kakts** [comment]
@inductor 承知しました！
