### ISSUE TITLE
Docsy template: not-yet-localized pages missing

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19309]
**This is a Bug Report**

**Problem:**
~With the (draft) Docsy version of the Kubernetes website,~ pages and sections that are only partially localized have fallback hyperlinks to the English localization originals, but only in

Compare the main section of https://kubernetes.io/it/docs/concepts/architecture/ to the left navigation on the same page - there are more links in the left nav than in the page body.

**Proposed Solution:**
Improve localization for page body. _This may mean working with upstream Docsy_.

**Comments**
Issue description adjusted; the left nav links were previously also missing.

/priority backlog

**Comment by shuuji3** [comment]
/remove-lifecycle rotten

This is an important fix to prevent readers of the localized page from missing the untranslated pages.

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/27572

**Comment by sftim** [comment]
This is fixed.
/close
