### ISSUE TITLE
Inconsitent k8s version in interactive tutorial modules

### ISSUE THREAD

**Issue by rajeshdeshpande02** [kubernetes/website#19305]
**Problem:**
Interactive tutorials available on k8s site have an inconsistent version of Kubernetes. Module 1- 'Create a Kubernetes cluster' uses 1.17 version but Module 2- 'Deploy an app' uses 1.15 version.

**Proposed Solution:**
The interactive tutorial should have a consistent Kubernetes version for all modules and that should be aligned with the documentation version. 

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

Kubernetes Version: 1.17

**Comment by sftim** [comment]
@rajeshdeshpande02 this looks similar to #18197; do you think it's a duplicate?

**Comment by BenHall** [comment]
Thanks for the feedback. We are testing 1.17. It should be cluster wide shortly.

**Comment by BenHall** [comment]
To provide an update, all the environments are now running `v1.8.1`.

This can be closed.

**Comment by sftim** [comment]
v1.18.1 perhaps?

/close

**Comment by BenHall** [comment]
Sorry, Minikube v1.8.1 which is 1.17 at the moment
