### ISSUE TITLE
Docsy template: feature-state shortcode broken

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19310]
**This is a Bug Report**

**Problem:**
With the draft Docsy version of the Kubernetes website, documentation that uses a feature-state shortcode doesn't have the right user interface.

For example, visit https://kubernetes-hugo-staging.netlify.com/docs/concepts/policy/pod-security-policy/ and click on _beta_.
Here's what I see:
![Docsy messed up feature state shortcode](https://user-images.githubusercontent.com/22591623/75278236-691de580-5801-11ea-8b76-c57c1804450f.png)

**Proposed Solution:**
Fix the draft Docsy templating

**Comment by kbhawkey** [comment]
Thanks for the link to the draft docsy version. I had no idea!

**Comment by sftim** [comment]
Looks like this is sorted.
/close
