### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by brentcklein** [kubernetes/website#19312]
**This is a Bug Report**

**Problem:**
There's either a typo in the [first paragraph in this section](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/#kubernetes-deployments) of Module 2 of the tutorial, or the sentence is very awkwardly worded. The sentence:
>Once you've created a Deployment, the Kubernetes master schedules mentioned application instances onto individual Nodes in the cluster.

doesn't appear to make any sense. Is the Kubernetes master scheduling the "mentioned application instances"? What application instances were mentioned? What does "scheduling" in this context mean?

**Proposed Solution:**
If this sentence is written as intended, it could use clarification. However it seems like there might be one or more typos, where words have been accidentally substituted. Those substitutions should be corrected if that's the case.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/#kubernetes-deployments

**Comment by sftim** [comment]
> Once you've created a Deployment, the Kubernetes master schedules mentioned application instances onto individual Nodes in the cluster.

I think the sentence is **true**. It looks like there is room to clarify and improve the wording.
https://kubernetes.io/docs/concepts/scheduling/kube-scheduler/ explains _scheduling_ in a Kubernetes context.

<hr />

Does this wording work better @brentcklein:
> Once you've created a Deployment, the Kubernetes control plane creates application Pods for that Deployment and then _schedules_ those Pods: the control plane picks nodes with capacity to run more work, and tries to run all the new Pods on nodes where they best fit.

?

**Comment by brentcklein** [comment]
I think that's an improvement @sftim, and I believe I understand the sentence as intended now. I think my confusion largely stemmed from the word "mentioned." My understanding now is that "mentioned application instances" in this context means "the application instances mentioned in the Deployment you've created," right?  So maybe:

> Once you've created a Deployment, the Kubernetes master schedules the application instances included in that Deployment onto individual Nodes in the cluster.

I think "scheduling" might be another point of confusion, just because it's only been mentioned in the tutorial once before: [third paragraph after this diagram](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/#cluster-diagram). It might not be necessary to give an expanded definition of scheduling here, but I do think the phrasing used in that previous mention of scheduling is more accessible: "schedules ... **to run on** the cluster's nodes" rather than "schedules ... **onto** individual Nodes". "Scheduling something" is a familiar phrase, but "scheduling something onto something" is a little less clear at first.

So then maybe: 

> Once you've created a Deployment, the Kubernetes master schedules the application instances included in that Deployment to run on individual Nodes in the cluster.

?

**Comment by sftim** [comment]
@brentcklein - would you also be interesting in proposing that fix as a pull request?

**Comment by brentcklein** [comment]
@sftim Done! https://github.com/kubernetes/website/pull/19352
