### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/cpu-management-policies/

### ISSUE THREAD

**Issue by kvp-cs** [kubernetes/website#19325]
How can a process running inside the container come to know its "allocated CPU list"? This information is not available in env variable, "describe pod -o wide".

**Comment by sftim** [comment]
I understand this question a: inside a Pod, how can processes discover their CPU affinity?

I _think_ the answer is the same as you would check it if you were not inside a Pod.
For example, search the web for “linux show cpu affinity” and pick one of those approaches.

@kvp-cs, is that what you wanted to ask?

**Comment by kvp-cs** [comment]
Thank you for the reply... I was looking for a way to identify the actual CPUIds associated to my Container (by CPUManager) so that I use the pthread-setaffinity calls to pin my app-threads to these CPU ids. "linux show cpu affinity" didnt help me here - am I missing something?

**Comment by sftim** [comment]
@kvp-cs I'd expect that the output from `taskset` would show CPU affinity. I haven't tried this. Does that utility work if you run it in a container that has the tool installed?

**Comment by kvp-cs** [comment]
**taskset** shows affinity for an already running thread/process. Whereas I am looking for an answer to the question "which CPU-ID can be used to set affinity for my thread". For example, the host may have 24 cores: 0-23.
Using CPUManager feature, my POD asked for 4 cores. How do I know whether the cores given to my container are {0,1,2,3} or {4,5,6,7} or {20,21,22,23} ?? I need this information to be able to call pthread_setaffinity() on my application thread that will be running inside the container.

**Comment by sftim** [comment]
This sounds like a support question.
/triage support

As far as I know, nothing on the page at https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/ describes narrowing the set of CPU cores that container's processes could be scheduled onto.

However, https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/ may be relevant.

**Comment by sftim** [comment]
After rereading the page I still think that `taskset` would display the information needed.

**Comment by kvp-cs** [comment]
Can you help me with an example: 
From the manpage of taskset: 
     **taskset [options] mask command**
       taskset is used to set or retrieve the CPU affinity of a running process given its PID or _to launch a new COMMAND with a **given CPU affinity**_.  CPU affinity is a scheduler property that "bonds"  a  process to  a given set of CPUs on the system.

If my command name (new process to be started inside the container) is "kvpWebServer", what is the taskset command I can use to launch it? To be precise, what is the value of "mask" I may use in
  - _taskset **mask** kvpWebServer_

**Comment by sftim** [comment]
> taskset is used to set or **retrieve** the CPU affinity of a running process given its PID or to launch a new COMMAND with a given CPU affinity.

I'm talking about the **retrieval** part. I assume that you want to narrow the set of CPUs so that some processes / threads are run on a subset of the container's CPU affinity set.
If `taskset` shows you the set of CPUs that the process is allowed to use, then you can use that set of allowed CPUs and write code to choose a subset.

**Comment by kvp-cs** [comment]
"If taskset shows you the set of CPUs that the process is allowed to use, then you can use that set of allowed CPUs and write code to choose a subset." -- I would first have to start a process and this process to be able to retrieve. 
A machine has 4 CPUs of which 3 are running time-sensitive jobs that cannot be interrupted by some random debug/profiling commands. When I login to the machine to debug something (say view CPU utilization with "top" command), the debug commands **must run on the 4th non-time-sensitive core**. If I just ran "top" without first assigning it a particular CPU  command and it came up on  one of the 3 time-sensitive CPUs, it will break the system. So when launching top command, I would do "taskset <mask> top" such that top is launched on the 4th non-time sensitive CPU. You cannot first let "top" come up on any of the 4 CPUs and later move it to the non-time critical core - the damage is already done!!
Is this a very new concept?? We have been doing this in PNFs and I thought we should be able to do similar things on CNFs too.

**Comment by sftim** [comment]
Thanks for clarifying.

From the page:
> This policy manages a shared pool of CPUs that initially contains all CPUs in the node. The amount of exclusively allocatable CPUs is equal to the total number of CPUs in the node minus any CPU reservations by the kubelet `--kube-reserved` or `--system-reserved` options. From 1.17, the CPU reservation list can be specified explicitly by kubelet `--reserved-cpus` option. The explicit CPU list specified by `--reserved-cpus` takes precedence over the CPU reservation specified by `--kube-reserved and `--system-reserved`. 

If you reserve a CPU for the system using `--reserved-cpus`, and you want to run a debug process that must only be scheduled onto the system reserved CPU, you can do that. Specify an affinity mask for the debug process (or even, for example, for the SSH service) that matches the `--reserved-cpus` affinity.

If you want to run an ephemeral container for debugging inside a real-time critical Pod and not have that debug container impact the real-time process, that sounds like something that's more about adding a feature to Kubernetes itself.
