### ISSUE TITLE
Cannot switch between some versions in documentation.

### ISSUE THREAD

**Issue by LSmyrnaios** [kubernetes/website#19340]
**This is a Bug Report**

**Problem:**
Cannot switch between some versions in documentation.
Currently, when opening a documentation page, like this the most recent version appears and there's an option in the menu-bar to switch between Kubernetes versions.
So, If I click on "v1.16", in this page it seems to work, but then (while being on the v1.16 page) if I click on the "v.1.15" it doesn't work and redirects me to the following page, just if the documentation doesn't exist "https://v1-15.docs.kubernetes.io/"
Whereas if I initially click on the "v.1.15", it redirects to the correct page for v.1.15
https://v1-15.docs.kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
This occurs also in any other documentation page.

**Proposed Solution:**
Fix the switching between documentation versions.

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
The above and any other documentation page that has this bug.

**Comment by sftim** [comment]
Seems like a valid report and worth fixing at some point
/priority backlog

**Comment by LSmyrnaios** [comment]
Thank you

/kind bug

**Comment by brianpursley** [comment]
Looks like this was fixed starting in v1.17 and going forward...
https://github.com/kubernetes/website/blob/c04ffcdce813a764aa5354fec2bba2cf742c4ac6/layouts/partials/header.html#L31

In order to fix for previous versions, I think you would need to branch from each previous version and change `{{ .url }}` to `{{ .url }}{{ $.RelPermalink }}` and merge a PR for each version.

**Comment by sftim** [comment]
@brianpursley would you like to propose pull requests for that / would you like help with doing that?

**Comment by brianpursley** [comment]
Sure

/assign

**Comment by sftim** [comment]
:ok_hand: Reply if you'd like help.

**Comment by brianpursley** [comment]
PRs created.  I wasn't 100% sure which branch it will merge into, but assumed it would be Release-1.1X.  Let me know if it is otherwise.

**Comment by brianpursley** [comment]
All PRs have been merged.

/close

**Comment by LSmyrnaios** [comment]
Thank you
