### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dual-stack/

### ISSUE THREAD

**Issue by PeterQiao** [kubernetes/website#19350]
**This is a Bug Report**

**Problem:**
kube-proxy:
--proxy-mode=ipvs
--cluster-cidrs=<IPv4 CIDR>,<IPv6 CIDR>

There is no such parameter "--cluster-cidrs" in kube-proxy, it should be "--cluster-cidr"

**Proposed Solution:**
Fix it.

**Page to Update:**
https://kubernetes.io/...

1.16, 1.17

**Comment by Colstuwjx** [comment]
Confirmed, will be fixed soon.
/assign
/language en
/kind documentation
