### ISSUE TITLE
check svg images on home page, firefox

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#19363]
**This is a Bug Report**

Viewed with **Firefox** browser,
svg images are not displaying on kubernetes.io, versions 1.16 and 1.17.

Viewed with Chrome, images display.

**Problem:**
Images are not displaying (issue with width) on https://kubernetes.io:
scalable.svg
blocks.svg
suitcase.svg

**Proposed Solution:**
Fix the width for the svg images (accessible from _index.html)
The image width appears to be zero.
Changing the width for the image (original CSS sets width = 100% and max-width=160px) to
something like, width=160px, displays the image.

**Page to Update:**
Fix the CSS for the images.

**Comment by Arhell** [comment]
resolve
/close

**Comment by sftim** [comment]
/close
Fixed in #19421
