### ISSUE TITLE
Add support for HowTo JSON+LD

### ISSUE THREAD

**Issue by remyleone** [kubernetes/website#19381]
**This is a Feature Request**

It would be a good idea to add support for HowTo description format to some page especially the tutorial ones.

**What would you like to be added**

We would need to add JSON+LD on the most visited tutorial to make it easy for search engines to understand the different steps of those tutorials. 

**Why is this needed**

- This could help new users to have a visualization directly into their search results of the different steps they need to perform to do a specific task. 

**Comments**

https://developers.google.com/search/docs/data-types/how-to

**Comment by sftim** [comment]
Nice idea.
