### ISSUE TITLE
Check & revise version requirements for “Configure Liveness, Readiness and Startup Probes”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19405]
**This is a clean up issue**

**What would you like to be changed**
Look at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ 

Make sure that all the version constraints in the page make sense and related to the list of Kubernetes versions that are [supported](https://kubernetes.io/docs/home/supported-doc-versions/) for documentation.

There is a `{{< version-check >}}` shortcode in the page that expects a `min-kubernetes-server-version: ` value in the page front matter. ~Replace that shortcode with English text that explains in words what versions the reader should have.
(to save you having to check: you can only configure a startup probe if you have Kubernetes v1.16 or later and if you have enabled the `StartupProbe` [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/))~
Remove that shortcode.

**Why is this needed**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ doesn't clearly tell readers about the version of Kubernetes they need to be running and the feature gate(s) they might need to enable.

**Comments**
/help
/kind cleanup

If you're looking at this, you might also want to tackle issue #16629

**Comment by jai** [comment]
/assign

@sftim I'll probably be back with questions - where's better to post/ask, here on the issue, or in Slack?

**Comment by jai** [comment]
Should I just add the info for Startup probes? I see that they came last with the feature gate in 1.16 onwards, checking now re: Liveness and Readiness but I guess they're earlier than the supported doc versions. 

Still would be nice to mention though - as a reader with maybe a bit less context I would get confused if the page title mentions 3 kinds of probes and the docs only talk about version requirements for one type of probe.

**Comment by jai** [comment]
Also at this point for the `StartupProbe` feature flag since it went beta in 1.18 and GA in 1.20 the text would be something like:

Kubernetes v1.16 and v1.17 require the `StartupProbe` [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) to be set. Startup probes are enabled by default in Kubernetes v1.18 onwards.

**Comment by sftim** [comment]
IMO it's OK to focus on documenting for v1.21, the current documentation version. If we want to backport the equivalent change to the older documentation, that's an option too.

For example, if you want to revise https://v1-17.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes to explain the feature gate, that's OK (but also _not a priority_).

**Comment by jai** [comment]
@sftim how do I go about editing the old version of the docs? Or is there a how-to/readme somewhere?

I've submitted a PR for the current version/file with the text I suggested: https://github.com/kubernetes/website/pull/27750

Do you know btw when Liveness and Readiness probes went alpha/beta/GA? I found Liveness probes introduced [here](https://github.com/kubernetes/kubernetes/pull/365/files) but haven't found Readiness probes yet. Anyways given that it's all the way in 2014 I think it's safe to omit specific versions.

I updated the text to read:
```yaml
Kubernetes v1.16 and v1.17 require the `StartupProbe` [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) to be set. Startup probes (as well as liveness and readiness probes) are enabled by default in Kubernetes v1.18 onwards.
```

lmk what you think

**Comment by sftim** [comment]
Since I opened this issue, several Kubernetes releases have come out and I didn't update the issue text to clarify it. I have now.

**Comment by jai** [comment]
If all PRs were this simple 😂 

Actually it turns out some of them really are :)
