### ISSUE TITLE
Remove kubectl rolling-update

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/website#19439]
**What would you like to be added**

Remove `kubectl rolling-update` from the website.

It has been deprecated and hidden since April 2018 in v1.11 and removed in v1.18.

**Why is this needed**

`kubectl rolling-update` has been deprecated and hidden since April 2018 in v1.11, and has been removed for v1.18.

**Comments**

Related issue: https://github.com/kubernetes/kubernetes/issues/88051

**Comment by rajeshdeshpande02** [comment]
@julianvmodesto I am working on this

**Comment by julianvmodesto** [comment]
Thanks Rajesh!

/assign @rajeshdeshpande02

**Comment by sftim** [comment]
Pull requests that are linked to the v1.18 release should target branch _dev-1.18_; pull requests that are general tidying up should target _master_ (but possibly also need linking to the v1.18 release milestone)

/priority important-soon
