### ISSUE TITLE
Clarify well known Toleration Keys' affect on DaemonSet

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/website#19435]
**This is a Bug Report**

**Problem:**

The descriptions of the [Toleration Keys]( https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations) need to be updated for DaemonSet.

**Proposed Solution:**

Add missing descriptions and clarify the difference for the first and second ones.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations

**Comment by sftim** [comment]
Hi @gavinfish 

What is missing? Are you perhaps thinking that 
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations should link to https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/?

**Comment by gavinfish** [comment]
@sftim I think the description for Toleration Keys need to be updated.
<img width="686" alt="Screen Shot 2020-03-03 at 9 58 51 AM" src="https://user-images.githubusercontent.com/6169722/75735481-bafcc900-5d35-11ea-8909-95280e8b692f.png">

**Comment by tengqm** [comment]
`node.kubernetes.io/not-ready` is attached to a Node when NodeReady condition is False; while `node.kubernetes.io/unreachable` is attached to a Node when NodeReady condition is Unknown.

Is the above information you want to appear in the table?
