### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by js8080** [kubernetes/website#19454]
**This is a Bug Report**

**Problem:**
In the [Securing the Service section](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#securing-the-service) the [service/networking/nginx-secure-app.yaml](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/service/networking/nginx-secure-app.yaml) references an image named "bprashanth/nginxhttps:1.0" with no explanation of what this image really contains, who owns it, etc.

I don't know if this image is safe to use. Why isn't it using the normal "nginx" image?

**Proposed Solution:**
Use a proper widely known image or provide more details on the image used.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by excalq** [comment]
I have the same concern.

**Comment by tengqm** [comment]
/reopen
Fixing this sounds trivial. Please someone help confirm if the "official" nginx image works for this example.
/help
