### ISSUE TITLE
Kustomize not highlighted in Kubectl Reference Docs sidebar

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/website#19478]
**Steps to reproduce:**
Navigate to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#kustomize

`kustomize` should be highlighted blue on the left sidebar, but instead `explain` is highlighted.

If you click on kustomize, it still won't highlight.

When you scroll the main content area, the tracking highlight skips over kustomize.

Problem does not occur in v1.16 or earlier:
https://v1-16.docs.kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#kustomize

![kustomize-doc](https://user-images.githubusercontent.com/4977542/75925907-896c2680-5e37-11ea-8a66-27bddfe1dbd2.png)

**Comment by kbhawkey** [comment]
Thanks for logging this issue @brianpursley .
Let's see how things stand in the next release.
/assign @kbhawkey

**Comment by brianpursley** [comment]
This has been fixed in 1.18 docs
