### ISSUE TITLE
Volume snapshot restore feature still marked as alpha

### ISSUE THREAD

**Issue by misterikkit** [kubernetes/website#19480]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-snapshot-and-restore-volume-from-snapshot-support

This page lists the "restore from volume snapshot" feature as alpha, but it should be beta in k8s 1.17.

**Proposed Solution:**
Update section to mark feature as beta. And make sure that the beta API is used in the example.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-snapshot-and-restore-volume-from-snapshot-support

The volume snapshot stuff went beta in k8s 1.17

**Comment by xing-yang** [comment]
Looks like this one fell through the cracks.  I think this is because we don't need to change the example so I forgot to update this page.  I'll update it.
