### ISSUE TITLE
Preview / Slack Image Shrink

### ISSUE THREAD

**Issue by sfxworks** [kubernetes/website#19498]
**This is a Feature Request**

**What would you like to be added**
Hey uh, I love the docs, and this is a small/low priority request for sure. Every time I link k8s docs in slack, it takes up an entire sum of an area for the k8s icon. While this is cool, can it be smaller or replaced with something relevant to the doc linked if there is an image already in there? 

**Why is this needed**

> Are you sure you wish to remove this attachment from the message?

Is what I see in slack when I link this to coworkers since I have to remove it, so they're forced to read the link. 

It provides no meaningful content other than the icon. 

**Comments**
https://api.slack.com/robots
Looks like they use Twitter Meta / OpenGraph, but other standards like Google's [Structured Data](https://developers.google.com/search/docs/guides/intro-structured-data) could be followed and reference a smaller image.

**Comment by sftim** [comment]
It seems to me that if Slack could find a precis of the page, it might use that instead of the image. It seems like something that is worth investigating further.
/priority awaiting-more-evidence

**Comment by AndrewSav** [comment]
@sftim sorry, what does "awaiting-more-evidence" mean? Is there any doubt, that what's described above is actually happening?

**Comment by sftim** [comment]
@AndrewSav you can find the [definitions](https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#define-priority) online.

How important is this to fix? With more details about the impact,  this issue could potentially be triaged onto the backlog.

**Comment by sfxworks** [comment]
I guess it would be priority/backlog based on that list. I wouldn't mind adding some meta to k8s's site (looks like Hugo? long as I can find the right place in the theme I could get it done later)

**Comment by alanjcastonguay** [comment]
I think slack is using the `twitter:image` set by #13261 to https://kubernetes.io/images/favicon.png, a 512x512?

**Comment by alanjcastonguay** [comment]
Priority order: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

> Like mathematics, there’s an order of operations to this, and it goes in the order described below. When you paste a URL into a Slack message and press return, Slack’s servers fetch the URL, cache it, and then start going through the headers of the page. Slack reads them in this order:
>* oEmbed server
>* Twitter card tags/Facebook Open Graph tags
>* HTML meta tags

**Comment by alanjcastonguay** [comment]
@kbarnard10 @lucperkins  A giant image seems suitable for blogposts (`{{ if $isBlogPost }}` plus the `img` regex). But I don't see the same giant image for every page of the docs _ever_ being useful, in the twitter or slack contexts. What was the reasoning here?

**Comment by lucperkins** [comment]
No particular “reasoning” at work. If you’d like a different image size, feel free to change.

**Comment by alanjcastonguay** [comment]
I am ignorant: Is the current size optimized for some other consumer/workflow? The commit history suggests this was done primarily for Twitter.

**Comment by lucperkins** [comment]
Again, there’s no specific rhyme or reason here. Feel free to change.

**Comment by sftim** [comment]
It seems like Slack is now sizing the image better. Does that match your experience @sfxworks?
