### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-kubernetes-objects/declarative-config/ matchLabels with slashes

### ISSUE THREAD

**Issue by onlynone** [kubernetes/website#19494]
This page recommends users use a match label like `"apps/v1/deployment/nginx"`. However, slashes are not currently allowed in label values. I opened a PR to address this in the code: https://github.com/kubernetes/kubernetes/pull/88817 . But I don't know if or when it will be accepted. Is there another form we should be using? We could use periods to separate components of the value, but then the `apiVersion` still wouldn't be allowed, just `"deployment.nginx"`.

**Comment by sftim** [comment]
I wonder if it make sense to remove the section at https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#defining-controller-selectors-and-podtemplate-labels entirely?

**Comment by onlynone** [comment]
I think it would be better to revise it to be correct. I think the advice to use a single label selector that unambiguously identifies the controller without any other semantic meaning makes sense. Especially in light of the recent changes to make `matchLabels` immutable.

**Comment by sftim** [comment]
The wording is anachronistic too; newer documentation doesn't call, eg, ReplicaSet a controller; the control plane runs a replicaset controller and you also have ReplicaSets (not ReplicaSet controllers) in your namespaces that you can see via the API.

**Comment by sftim** [comment]
If we want to keep a revised version of https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#defining-controller-selectors-and-podtemplate-labels, I'd want the reviewer to be confident that https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/ is the right home for that explanation.

**Comment by liggitt** [comment]
I don't think the selector/template section belongs on that page (the rest of that page is about generic declarative config).

I would recommend:
* make a corrected section:
  * use a valid label for the selector and template
  * strengthen the "Updating selectors on controllers is strongly discouraged." warning... it is completely disallowed in apps/v1 versions of workload APIs
* place that section into the various pages oriented at the specific workload APIs (e.g. [Deployment](https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/), [StatefulSet](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/))

**Comment by lavalamp** [comment]
The example documentation is super confusing, there's no need to mention the "controller", that's done automatically via owner reference. I feel like this piece of documentation is a holdover from 6 years ago or something?

**Comment by sftim** [comment]
I traced this back to https://github.com/kubernetes/website/pull/2317/files#diff-ad7c0d08681c47b085f3ec4092485271R111-R117

(Kubernetes 1.5)

I don't understand why the problem section is there on the page. If it were removed, who would lose out?

**Comment by onlynone** [comment]
@sftim 

I'm confused when you say, "The wording is anachronistic too; newer documentation doesn't call, eg, ReplicaSet a controller;"

I didn't see anywhere in that section where it called a ReplicaSet a controller. It seemed to be about Deployments. This is the current content:

> # Defining controller selectors and PodTemplate labels
> 
>     Warning: Updating selectors on controllers is strongly discouraged.
> 
> The recommended approach is to define a single, immutable PodTemplate label used only by the controller selector with no other semantic meaning.
> 
> ## Example:
> 
> ```
> selector:
>   matchLabels:
>       controller-selector: "apps/v1/deployment/nginx"
> template:
>   metadata:
>     labels:
>       controller-selector: "apps/v1/deployment/nginx"
> ```

**Comment by onlynone** [comment]
@sftim 

I'm confused when you say, "The wording is anachronistic too; newer documentation doesn't call, eg, ReplicaSet a controller;"

I didn't see anywhere in that section where it called a ReplicaSet a controller. It seemed to be about Deployments. This is the current content:

> # Defining controller selectors and PodTemplate labels
> 
>     Warning: Updating selectors on controllers is strongly discouraged.
> 
> The recommended approach is to define a single, immutable PodTemplate label used only by the controller selector with no other semantic meaning.
> 
> ## Example:
> 
> ```
> selector:
>   matchLabels:
>       controller-selector: "apps/v1/deployment/nginx"
> template:
>   metadata:
>     labels:
>       controller-selector: "apps/v1/deployment/nginx"
> ```

**Comment by sftim** [comment]
To be clear, newer documentation also doesn't call a Deployment a controller. There definitely is a deployment controller in your cluster (or something needs fixing), but a while ago people realized that the resource and its control loop are different things.

I'm yet to be convinced that https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#defining-controller-selectors-and-podtemplate-labels is worth keeping.

**Comment by sftim** [comment]
A similar question came up in issue #24107
