### ISSUE TITLE
Create a Tasks doc for Service Account Issuer Discovery

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/website#19496]
**This is a Feature Request**

**What would you like to be added**
Add a Tasks doc for configuring Service Account Issuer Discovery before the feature goes to beta.

**Why is this needed**
To help users understand how to configure the feature correctly.

**Comments**
@sftim recommended we make this a beta requirement https://github.com/kubernetes/website/pull/19328#pullrequestreview-365664336

/assign @mtaufen 
/cc @sftim @mikedanese

**Comment by sftim** [comment]
Thanks @mtaufen !

/kind feature
/priority backlog

**Comment by divya-mohan0209** [comment]
@mtaufen do we still need this issue to be open? I see this feature is stable currently and wanted to check in if we still plan on including more documentation around this?

**Comment by mtaufen** [comment]
We can close this.
