### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/

### ISSUE THREAD

**Issue by khalilgharbaoui** [kubernetes/website#19509]
**This is a Bug Report**

**Problem:**
Link to `release notes` results in a 404
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md
**Proposed Solution:**
Point the link on the website to an actual changelog!

**Comment by sftim** [comment]
@khalilgharbaoui, what's the URL of the page you were on that has the broken link?

https://k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-15/ looks like a redirect.
