### ISSUE TITLE
“Intermediate contributing” gives wrong advice about removing graduated feature gates

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19506]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/contribute/intermediate/#sig-members-documenting-new-features tells contributors to remove items from the feature gates list when those features graduate to GA. However, that's not right. Graduated features move to the [table of graduated and deprecated features](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features).

**Proposed Solution:**
Replace “_If your feature is moving out of Alpha, make sure to remove it from that file._” with “_If your feature is moving to Beta or to General Availability, update the feature gates file._”

**Page to Update:**
https://kubernetes.io/docs/contribute/intermediate/

**Additional Information:**
/kind bug
/good-first-issue

**Comment by kbhawkey** [comment]
Note: I would check this existing pull request (PR #19576) before working on this issue. The content is changing.

**Comment by sftim** [comment]
/remove-good-first-issue

It's fine to work on this, but the potential for having to synchronize with other contributors makes me want to stop highlighting this to brand new contributors.

**Comment by divya-mohan0209** [comment]
@sftim Are we  good to close this issue since the related PR was approved by you and merged successfully?

**Comment by sftim** [comment]
https://kubernetes.io/docs/contribute/#sig-members-documenting-new-features has gone entirely, I think

/close
