### ISSUE TITLE
Ingress documentation uses an assigned IPv4 address in an example

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19507]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/services-networking/ingress/ gives an example of an Ingress and mentions 107.178.254.228; that's a real IPv4 address, currently allocated to Google.
It'd be better to use an IP address that isn't allocated, the same way that movies set in the USA use numbers in the 555 area code rather than real, dialable numbers.

**Proposed Solution:**
Replace 107.178.254.228 with a [documentation IP address](https://tools.ietf.org/html/rfc5737), such as 203.0.113.123

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Additional Information:**
/kind cleanup
/good-first-issue
/language en
/priority backlog

**Comment by sftim** [comment]
Anyone with a [signed CLA](https://kubernetes.io/docs/contribute/start/#sign-the-cla) is welcome to propose a pull request with a suggested fix.

@divya-mohan0209 do you have any questions about this issue?

**Comment by divya-mohan0209** [comment]
@sftim I have submitted my [pull request](https://github.com/kubernetes/website/pull/19522). I'm new around here, which is why I have followed the instructions and assigned to @xiangpengzhao per the bot's instructions. Please could you review?

**Comment by davivcgarcia** [comment]
@sftim is this fixed by PR #19522?

**Comment by sftim** [comment]
Looks fixed to me.
/close
