### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by remyleone** [kubernetes/website#19513]
**This is a Bug Report**

Here are some pages with broken links (saved as a CSV format)

**Problem:**

Some links on the website are broken

**Proposed Solution:**

Fix the link to valid ones

**Page to Update:**

https://github.com/kubernetes/website/files/4262612/kubernetes.io_internal_broken_links_20200227.txt

**Comment by sftim** [comment]
https://github.com/kubernetes/website/files/4262612/kubernetes.io_internal_broken_links_20200227.txt is comma-separated, so you can open it in a tool like Microsoft Excel, Google Sheets, or OpenOffice Calc.

**Comment by sftim** [comment]
Fixing every broken link there is a lot of work @remyleone 
Is this task the right side for the “good first issue” label?

**Comment by tanjunchen** [comment]
I think it is ok label “good first issue”
+1

**Comment by kbhawkey** [comment]
Is it essential to include links from previous versions of the docs (snapshots)?
How about focusing only on link errors in 1.17?
Note: Do you want to correct links before (or during) a release?

**Comment by IanColdwater** [comment]
yeah sure, why not

/assign

**Comment by sftim** [comment]
> How about focusing only on link errors in 1.17?

That sounds like a good place to start. Thinking about how I might handle a similar challenge in a work context, I would consider splitting the issue once the link errors in _master_ had been dealt with.
