### ISSUE TITLE
Flowchart for debugging cluster incidents 

### ISSUE THREAD

**Issue by remyleone** [kubernetes/website#19518]
**This is a Feature Request**

**What would you like to be added**

A flowchart that is similar to this would be nice on the official documentation 
https://learnk8s.io/troubleshooting-deployments

**Why is this needed**

It is sometimes difficult for a beginner to have a methodical approach about how to debug and pass from one diagnostic to the next. A flowchart is nice because you can follow visually a track that tells you where to go

**Comments**

Huge kudos to learnk8s.io for making this one

**Comment by sftim** [comment]
:+1:
/kind feature
/priority important-longterm

**Comment by sftim** [comment]
/remove-priority important-longterm
(sorry)
/priority backlog

**Comment by sftim** [comment]
This'd be a nice thing to have
/remove-lifecycle rotten
