### ISSUE TITLE
Kubectl command reference middle column tables overflow into third column on narrow displays

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/website#19519]
**This is a Bug Report**

**Problem:**
When viewing kubectl reference docs page on a narrow display, middle column flag tables overflow into the third column.

**Proposed Solution:**
Fix CSS for narrow displays so that tables do not exceed the middle column width

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

![kubectl-ref](https://user-images.githubusercontent.com/4977542/76103100-1b427380-5f9f-11ea-97e5-19652e15c89b.png)

**Comment by sftim** [comment]
That's a valid issue. Thanks @brianpursley 
/kind bug
/priority backlog

**Comment by brianpursley** [comment]
This was fixed in the 1.18 release
