### ISSUE TITLE
README-pl link bug

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#19527]
**This is a Bug Report**
README-pl link bug

**Problem:**
Broken link

**Proposed Solution:**
Fix link

**Page to Update:**

https://github.com/kubernetes/website/blob/master/README-pl.md
![870d5382cc](https://user-images.githubusercontent.com/26163841/76143688-3639e400-6082-11ea-918c-64752c3d6d58.jpg)

/assign
/language pl

**Comment by sftim** [comment]
/priority backlog
/kind bug

Thanks @Arhell

**Comment by Arhell** [comment]
resolve
/close
