### ISSUE TITLE
Add a curated checklist of best practices designed for application

### ISSUE THREAD

**Issue by remyleone** [kubernetes/website#19520]
**This is a Feature Request**

**What would you like to be added**

A checklist about what to do to make an application work well inside Kubernetes.
Inspiration from https://learnk8s.io/production-best-practices

An application checklist that can tell visually what should be added to an application.

**Why is this needed**

It is not obvious for an application developer to know what are the things they are supposed to do to make their application work well inside Kubernetes.

**Comments**

Kudos to learnk8s.io to make this checklist

**Comment by sftim** [comment]
If you're working on this, consider where to put it. Inside https://kubernetes.io/docs/setup/best-practices/ or somewhere else?

You might even want to bring that question to a weekly [meeting of SIG Docs](https://kubernetes.io/docs/contribute/start/#participating-in-sig-docs).
