### ISSUE TITLE
Dated glossary entry for cloud controller manager

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19535]
**This is a Bug Report**

**Problem:**
https://k8s.io/docs/reference/glossary/?all=true#term-cloud-controller-manager is out of date; it talks about Kubernetes releases v1.6 and v1.8

**Proposed Solution:**
At a minimum, remove the reference to releases v1.6 and v1.8 from the glossary entry.
It's OK to revise further as well.

**Page to Update:**
https://k8s.io/docs/reference/glossary/

**Additional Information:**
/kind cleanup
/help
/language en
/priority important-longterm

Also see issue #18086

**Comment by davivcgarcia** [comment]
I'll work on that!

/remove-help
/assign
