### ISSUE TITLE
Wrong formatting in “Persistent Volumes” concept

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19542]
**This is a Bug Report**

**Problem:**
The “Persistent Volumes” page puts Kubernetes resources (eg “PersistentVolume”) in code blocks. In Markdown, that means backticks around the resource names.
However, the Style Guide [recommends](https://kubernetes.io/docs/contribute/style/style-guide/#use-camel-case-for-api-objects) writing resources in PascalCase, _without_ backticks.

**Proposed Solution:**
Edit the page to find all occurrences of PersistentVolume, PersistentVolumeClaim and StorageClass, and take those out of backticks. Also replace instances of “Persistent Volume Claim” with PersistentVolumeClaim.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Additional Information:**
/kind cleanup
/good-first-issue

**Comment by sujaypillai** [comment]
Can we update the pages referenced in this with the same solution?
e.g. [#L30](https://github.com/kubernetes/website/edit/master/content/en/docs/concepts/storage/persistent-volumes.md#L30)  if we navigate to [Storage Class](https://kubernetes.io/docs/concepts/storage/storage-classes/)  page it too has resources in code blocks.

**Comment by sftim** [comment]
@sujaypillai that sounds fine.
