### ISSUE TITLE
Wrong legend for “Using a Service to Expose Your App”

### ISSUE THREAD

**Issue by HattiMaTimTim** [kubernetes/website#19556]
**This is a Bug Report**

In "Services and Labels, in the legend, the pink cube should be labeled as container. The blue octagon is correctly identified as Node. Pods should be shown as green (or variants of it) circles.

**Comment by sftim** [comment]
/retitle Wrong legend for “Using a Service to Expose Your App”

**Comment by sftim** [comment]
https://k8s.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

**Comment by sftim** [comment]
@HattiMaTimTim I think you're right. The blue shape representing a node is a hexagon though.

/kind bug
/priority important-longterm

**Comment by HattiMaTimTim** [comment]
Y, the blue shape is correct. The filled purple cube says “pod” - should instead say “container”.. :-)
