### ISSUE TITLE
Signpost readers from /docs/home/ to /training/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19554]
**This is a Feature Request**

**What would you like to be added**
https://kubernetes.io/docs/home/ has a heading “Learn how to use Kubernetes” and text
> Look up common tasks and how to perform them using a short sequence of steps.

Add another sentence to tell readers that training is available, and include a hyperlink to [`/training/`](https://kubernetes.io/training/).

**Why is this needed**
This change will help readers see that training is available.

**Comments**
/language en
/kind feature
/help

**Comment by divya-mohan0209** [comment]
Hello @sftim , can this issue be closed now?

**Comment by sftim** [comment]
/close
Thanks
