### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/kubernetes-basics/update/

### ISSUE THREAD

**Issue by lsyarn** [kubernetes/website#19558]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

Diagram in this page can not switch。

**Comment by sftim** [comment]
Hello @lsyarn 

Could you describe what isn't right about https://k8s.io/zh/docs/tutorials/kubernetes-basics/update/ ?

/triage needs-information

**Comment by lsyarn** [comment]
Click next can not switch between fours images in section **Rolling updates overview** 。Seems like the four `div`s missed a style class `carousel-item` in line [100](https://github.com/kubernetes/website/blob/16ff8f55a0bd3b815967f82f29eb6c85c86b708e/content/zh/docs/tutorials/kubernetes-basics/update/update-intro.html#L100) and 104, 108, 102。

**Comment by sftim** [comment]
Thanks for clarifying
/remove-triage needs-information

**Comment by tengqm** [comment]
Fixed.
/close
