### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by scubakiz** [kubernetes/website#19579]
What is hello?  Is it the backend service name, it is the frontend service, is it the frontend pod!

Could someone please write a demo that makes sense?!?!?!

**Comment by Colstuwjx** [comment]
Do you mean the word `hello` in Service\Upstream\Backend is different thing, and should take another naming?

/language en
/triage support
