### ISSUE TITLE
markdown fix in readme vi

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#19577]
**This is a Bug Report**

markdown bug

**Problem:**
![1](https://user-images.githubusercontent.com/26163841/76256038-f0367900-6257-11ea-9c82-20358084bc56.jpg)

**Proposed Solution:**

markdown fix

**Page to Update:**

https://github.com/kubernetes/website/blob/master/README-vi.md

/assign
/language vi

**Comment by sftim** [comment]
Thanks @Arhell
/kind bug
/priority backlog

**Comment by Arhell** [comment]
resolve
/close
