### ISSUE TITLE
Outdated docs on anonymous-requests

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/website#1958]
http://kubernetes.io/docs/admin/authentication/#anonymous-requests

Please update documentation now that anonymous-requests are NOT enabled by default.

**Comment by liggitt** [comment]
Anonymous requests remain enabled by default in 1.6.

The RBAC and ABAC authorizers have been updated to prevent accidentally authorizing anonymous requests, and using the AlwaysAllow authorizer disables anonymous auth.
