### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by sbland** [kubernetes/website#19588]
The `Congratulations on completing the module` for module 1 form does not fill screen vertically.

Viewed on Chrome

**Comment by Colstuwjx** [comment]
I have been checked, it looks like wasn't a big problem:

![image](https://user-images.githubusercontent.com/3972545/76593589-c029f700-6531-11ea-9e39-2e2ceccceb96.png)

BTW, I have been checked the frontend code on Chrome, the interactive terminal is a iframe, see [this line code](https://github.com/kubernetes/website/blob/master/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html#L28), and the width was set by css class `freebirdFormviewerViewCenteredContent`:

```
.freebirdFormviewerViewCenteredContent {
    margin: auto;
    max-width: 90vw;
    width: 640px;
}
```

it seems to be a fixed size set by katacoda.

/language en
/triage support

**Comment by BenHall** [comment]
I believe this might have been related to an issue which has since been fixed. 

I believe this can now be closed.

**Comment by tengqm** [comment]
Feel free to reopen if the issue persists.
/close
