### ISSUE TITLE
Need to maintain `examples_test.go`

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#19582]
**This is a Bug Report**
Something inside [examples_test.go](https://github.com/kubernetes/website/blob/dff2f7b9601470dc8383d883b23188ed450d89c2/content/en/examples/examples_test.go#L36) is outdated, the main repo don't have `k8s.io/kubernetes/pkg/api/testapi` such package anymore..

**Problem:**
examples_test.go not synced with main repo and felt little tricky to run test (I think).

**Proposed Solution:**
update as required.

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
The tool has been disable for quite a while after we dropped support to travis. Hopefully it can be resurrected so that we can ensure all the example manifests are valid.

**Comment by Colstuwjx** [comment]
The `test-examples` has been removed from build within [PR #15137](https://github.com/kubernetes/website/pull/15137) , the relative remove travis CI PR should be #13598 .

In my opinion, I think maintaining the tests inside website repo is dirty and easily to be outdated with the main repo, it should be one of the test-infra job, even though it maybe website private test job.

/language en
/sig testing

**Comment by tengqm** [comment]
We were not able to figure out how to feed the tool with necessary input on netlify. The tool was used to validate all YAML files under the examples subdirectory always work under a given version number. For example, in 1.16, we found that a lot of examples were broken due to the stricter requirement on Deployment labels. With that said, the tool was part of the test job.

**Comment by Colstuwjx** [comment]
I totally agree that we need this test job to validate whether the given version is working as our expect, and also running job inside netlify is very limited.

I suggest that we could add this job into test-infra job set, just like [release](https://github.com/kubernetes/test-infra/blob/2c8702645f217e63140acc4525881a978c322d03/config/jobs/kubernetes/release/release-config.yaml) and [kustomize](https://github.com/kubernetes/test-infra/blob/2c8702645f217e63140acc4525881a978c322d03/config/jobs/kubernetes-sigs/kustomize/kustomize-config.yaml) did, test-infra could give us many features support, for example, pre-submit hook, periodic job,  e2e test infra etc.

And test-infra could also set which jobs would be run according the PR changes, so we don't need to check whether test-examples should be run via [script check](https://github.com/kubernetes/website/blob/master/scripts/test_examples.sh#L12).

On the other hand, introduce test-infra jobs would make things little complicated, but... until now, I still could not run the tests on my mbp, so I wonder whether we need to change the test way.

**Comment by tengqm** [comment]
This is fixed. Getting it automated in CI gate is another issue.
/close
