### ISSUE TITLE
Issue with page css of markdown heading :before

### ISSUE THREAD

**Issue by yurenchen000** [kubernetes/website#19591]
**This is a Bug Report**

**Problem:**

seems page css `#docsContent h3:before`  `display: block` cause `chrome 80` 
can't select text near (top) content section title.
( `firefox 74` seems same )

```css
#docsContent h1:before, #docsContent h2:before, #docsContent h3:before, #docsContent h4:before, #docsContent h5:before, #docsContent h6:before {
    /* display: block; */
```

![image](https://user-images.githubusercontent.com/8458213/76346930-c016d500-6340-11ea-8e73-4364379566ff.png)

**Proposed Solution:**

remove `display: block` seems ok for `chrome 80`, `firefox 74`

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for the report @yurenchen000 

Did you also want to propose a fix? (if so, help is available to get you started).

**Comment by yurenchen000** [comment]
> Thanks for the report @yurenchen000
> 
> Did you also want to propose a fix? (if so, help is available to get you started).

I just remove `display: block` of 
```css
#docsContent h1:before, #docsContent h2:before, #docsContent h3:before, #docsContent h4:before, #docsContent h5:before, #docsContent h6:before
```

I only test with `chrome 80`, `firefox 74`, not sure other browsers effect, 

I don't have a deep understanding of `CSS / SCSS`,  

So I hope professionals can handle it properly.

**Comment by Arhell** [comment]
@sftim 
I found several solutions to this bug:
1) Remove it, but then it will enter an anchor a little higher, will be hiding behind a fixed header.
2) Add one property, but the tag with the link will not work, more precisely it will, but there is no hover and focus
3) Add all tags ol p ul relative and h negative to before but this will not remove the problem as a whole

**Comment by celestehorgan** [comment]
@sftim I think we can close this one too :)
