### ISSUE TITLE
Kubernetes User Guide shows RCs but not Deployments

### ISSUE THREAD

**Issue by waprin** [kubernetes/website#1960]
**This is a...** 
- [ X] Bug Report

**Problem:**
Kubernetes User Guide shows RCs but not Deployments.

**Proposed Solution:**

Update the user guide to show deployments.

**Page to Update:**
http://kubernetes.io/docs/user-guide/

**Comment by tengqm** [comment]
Closing because this issue is not pointing us to a specific section of the website to fix. After a quick 'grep' over the website, I'm unable to identify sections where we are using RC while Deployment is more appropriate. Please feel free to reopen this if there is a case we are missing.
