### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by joefradley** [kubernetes/website#19629]
**This is a Bug Report**

**Problem:**
The diagram images are nice. But they're too small to actually read the text on them and there is no easy way to zoom in.

**Proposed Solution:**
 * Use higher resolution images. 
 * Have images open a modal when clicked.

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@jfradley can you please provide the link to that page?

**Comment by tengqm** [comment]
Right. The image is not good. https://d33wubrfki0l68.cloudfront.net/99d9808dcbf2880a996ed50d308a186b5900cec9/40b94/docs/tutorials/kubernetes-basics/public/images/module_01_cluster.svg

**Comment by jfradley** [comment]
@RA489 sorry for the delay. I thought the page would have been automatically associated when I hit the `Create an Issue` button on it.

I think a number of pages are effected, but here's a specific one (contains image linked by @tengqm):
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

**Comment by sftim** [comment]
So this is a feature request to allow zooming into diagrams (not relying on browser UI).

/area web-development
/remove-lifecycle rotten
/kind feature
/priority backlog

**Comment by sftim** [comment]
@joefradley feel free to reopen this if you're still keen to get the improvement made
