### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by jayantredhat** [kubernetes/website#19638]
**This is a Bug Report**

When I try to login with exec/logs through kubectl then bellow error in terms of pod or container...
Error from server: error dialing backend: dial tcp XX.XX.XX.XX:10250: connect: connection refused

**Problem:**
Error from server: error dialing backend: dial tcp XX.XX.XX.XX:10250: connect: connection refused
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

clientVersion:
  buildDate: "2020-02-11T18:12:12Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.6
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-02-11T18:07:13Z"
  compiler: gc
  gitCommit: 06ad960bfd03b39c8310aaf92d1e7c12ce618213
  gitTreeState: clean
  gitVersion: v1.17.3
  goVersion: go1.13.6
  major: "1"
  minor: "17"
  platform: linux/amd64
And Docker version
Docker version 19.03.8, build afacb8b

I suffered because again and again modify in yaml and verify through describe command So please resolve it ASAP....

**Comment by neolit123** [comment]
please use the support channels for questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
/triage support
