### ISSUE TITLE
Issue with k8s.io/docs/setup/best-practices/node-conformance/

### ISSUE THREAD

**Issue by lordofgore** [kubernetes/website#19644]
Inability to run test containers

**Problem:**
As per https://kubernetes.io/docs/setup/best-practices/node-conformance/
docker run -it --rm --privileged --net=host -v /:/rootfs -v $CONFIG_DIR:$CONFIG_DIR -v $LOG_DIR:/var/result k8s.gcr.io/node-test:0.2

** Expected result **
Validation tests running

** Actual result **
Tests are not running because of incompatibility with overlay2:
system validation failed: unsupported graph driver: overlay2

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/best-practices/node-conformance/

Kubernetes v1.17.4
Docker version 1.13.1

**Comment by tengqm** [comment]
/remove-lifecycle stale

We should either fix the doc or remove it.
