### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/windows/user-guide-windows-nodes/

### ISSUE THREAD

**Issue by marbortechie** [kubernetes/website#19656]
**This is a Bug Report**

**Problem:**
cni-conf.json example missing cniVersion 
**Proposed Solution:**
add "cniVersion": "0.3.1"
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-nodes/

**Comment by tengqm** [comment]
Looks like the cni-conf.json file is not there anymore
Feel free to reopen if the issue is still there.

/close
