### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by scott-jiang** [kubernetes/website#19654]
Version 1.6.0-beta.0 - 2019-11-15

Remove heapster addon #5243

if you run minikube version: v1.8.2 or later
minikube addons enable heapster

will get error message 

enable failed: heapster is not a valid addon

**Comment by Kartik494** [comment]
@scott-jiang Heapster addon is deprectaed and is no longer used.You can find this https://github.com/kubernetes/website/pull/18673

**Comment by RA489** [comment]
@scott-jiang Minikube no longer support heapster addons.
