### ISSUE TITLE
Optimize update-imported-docs scripts

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#19663]
**This is a Feature Request**
From now, we need to git clone the whole k/k repo while exec ref docs generate, see the [reference.yml](https://github.com/kubernetes/website/blob/694815d4547b485797381e755067ce7300c6811b/update-imported-docs/reference.yml#L9).

**What would you like to be added**
Make the `git clone` with a single specific branch, thus, we don't need to clone the whole repo (the k/k main repo is so big and even will be bigger over time).

**Why is this needed**
wait the git clone operation is so boring and valueless, and I checked the correctness, it seems all good.

**Comments**

**Comment by kbhawkey** [comment]
@Colstuwjx , The comment under `Why is this needed` does not add much value.

**Comment by Colstuwjx** [comment]
@kbhawkey Yes, it's an optimization, and it may also be risky, since we didn't clone the k/k repo anymore.

If you think this proposal is valueless, I'm ok to close it.
