### ISSUE TITLE
Netlify redirects: master branch

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#19670]
**This is a bug report.**

/kind bug

This PR is under the #19624 umbrella. ☂️ 

This PR lists affected redirects in the `master` branch.

**Note:** Unless these redirects are resolved quickly, at the 1.18 release the contents of `master` will become `release-1.18` and `dev-1.19` while `master` continues. This means that instead of one branch needing resolution, two new branches will have the same problems and require the same attention, for a total of three branches.

/priority critical-important

**Proposed Solution:**

1. Verify which links need to be [forced or remain shadowed](https://community.netlify.com/t/changed-behavior-in-redirects/10084)
2. Update [`static/_redirects`](https://github.com/kubernetes/website/blob/master/static/_redirects) as needed.

## List of affected redirects in `master`

/api-ref/ ... https://github.com/kubernetes/kubernetes/milestones/ 301 ...
/concepts/containers/container-lifecycle-hooks/ ... /docs/concepts/containers/container-lifecycle-hooks/ 301 ...
/docs/ ... /docs/home/ 301 ...
/de/docs/ ... /de/docs/home/ 301 ...
/es/docs/ ... /es/docs/home/ 301 ...
/fr/docs/ ... /fr/docs/home/ 301 ...
/id/docs/ ... /id/docs/home/ 301 ...
/ja/docs/ ... /ja/docs/home/ 301 ...
/ko/docs/ ... /ko/docs/home/ 301 ...
/no/docs/ ... /no/docs/home/ 301 ...
/pl/docs/ ... /pl/docs/home/ 301 ...
/pt/docs/ ... /pt/docs/home/ 301 ...
/ru/docs/ ... /ru/docs/home/ 301 ...
/vi/docs/ ... /vi/docs/home/ 301 ...
/zh/docs/ ... /zh/docs/home/ 301 ...
/blog/2018/03/kubernetes-1.10-stabilizing-storage-security-networking/ ... /blog/2018/03/27/kubernetes-1.10-stabilizing-storage-security-networking/ 301 ...
/docs/admin/ ... /docs/concepts/cluster-administration/cluster-administration-overview/ 301 ...
/docs/admin/add-ons/ ... /docs/concepts/cluster-administration/addons/ 301 ...
/docs/admin/addons/ ... /docs/concepts/cluster-administration/addons/ 301 ...
/docs/admin/apparmor/ ... /docs/tutorials/clusters/apparmor/ 301 ...
/docs/admin/audit/ ... /docs/tasks/debug-application-cluster/audit/ 301 ...
/docs/admin/authorization/rbac.md ... /docs/admin/authorization/rbac/ 301 ...
/docs/admin/cluster-components/ ... /docs/concepts/overview/components/ 301 ...
/docs/admin/cluster-management/ ... /docs/tasks/administer-cluster/cluster-management/ 301 ...
/docs/admin/cluster-troubleshooting/ ... /docs/tasks/debug-application-cluster/debug-cluster/ 301 ...
/docs/admin/daemons/ ... /docs/concepts/workloads/controllers/daemonset/ 301 ...
/docs/admin/disruptions/ ... /docs/concepts/workloads/pods/disruptions/ 301 ...
/docs/admin/dns/ ... /docs/concepts/services-networking/dns-pod-service/ 301 ...
/docs/admin/etcd/ ... /docs/tasks/administer-cluster/configure-upgrade-etcd/ 301 ...
/docs/admin/etcd_upgrade/ ... /docs/tasks/administer-cluster/configure-upgrade-etcd/ 301 ...
/docs/admin/extensible-admission-controllers.md ... /docs/admin/extensible-admission-controllers/ 301 ...
/docs/admin/garbage-collection/ ... /docs/concepts/cluster-administration/kubelet-garbage-collection/ 301 ...
/docs/admin/ha-master-gce/ ... /docs/tasks/administer-cluster/highly-available-master/ 301 ...
/docs/admin/ha-master-gce.md/ ... /docs/tasks/administer-cluster/highly-available-master/ 301 ...
/docs/admin/high-availability/ ... /docs/admin/high-availability/building/ 301 ...
/docs/admin/kubeadm-upgrade-1-7/ ... /docs/tasks/administer-cluster/upgrade-downgrade/kubeadm-upgrade-1-7/ 301 ...
/docs/admin/kubelet-authentication-authorization/ ... /docs/reference/command-line-tools-reference/kubelet-authentication-authorization/ 301 ...
/docs/admin/kubelet-tls-bootstrapping/ ... /docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/ 301 ...
/docs/admin/limitrange/ ... /docs/tasks/administer-cluster/cpu-memory-limit/ 301 ...
/docs/admin/limitrange/Limits/ ... /docs/tasks/administer-cluster/limit-storage-consumption/#limitrange-to-limit-requests-for-storage/ 301 ...
/docs/admin/master-node-communication/ ... /docs/concepts/architecture/master-node-communication/ 301 ...
/docs/admin/multiple-schedulers/ ... /docs/tasks/administer-cluster/configure-multiple-schedulers/ 301 ...
/docs/admin/namespaces/ ... /docs/tasks/administer-cluster/namespaces/ 301 ...
/docs/admin/namespaces/walkthrough/ ... /docs/tasks/administer-cluster/namespaces-walkthrough/ 301 ...
/docs/admin/network-plugins/ ... /docs/concepts/cluster-administration/network-plugins/ 301 ...
/docs/admin/networking/ ... /docs/concepts/cluster-administration/networking/ 301 ...
/docs/admin/node/ ... /docs/concepts/architecture/nodes/ 301 ...
/docs/admin/node-allocatable/ ... /docs/tasks/administer-cluster/reserve-compute-resources/ 301 ...
/docs/admin/node-allocatable.md ... /docs/tasks/administer-cluster/reserve-compute-resources/ 301 ...
/docs/admin/node-conformance.md ... /docs/admin/node-conformance/ 301 ...
/docs/admin/node-problem/ ... /docs/tasks/debug-application-cluster/monitor-node-health/ 301 ...

**Comment by kbhawkey** [comment]
I have time to do this. Temporarily assigning myself unless someone has already started to create the changes.
/assign @kbhawkey

**Comment by zacharysarah** [comment]
Fixed by #19695. Thank you @kbhawkey! ⭐️ 

/close
