### ISSUE TITLE
Docs page on mobile renders poorly

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#19671]
**This is a Bug Report**
Update styles

**Problem:**
![a37d9a6435](https://user-images.githubusercontent.com/26163841/76800688-dc04f580-67dc-11ea-94e6-6dffd95fdd48.jpg)

**Proposed Solution:**
Add media for this page

**Page to Update:**

https://kubernetes.io/docs/home/

/assign

**Comment by sftim** [comment]
@Arhell can I suggest another title tweak?
“Docs page on mobile renders poorly”

**Comment by Arhell** [comment]
resolve
/close
