### ISSUE TITLE
Improve print stylesheet

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19703]
**This is a Feature Request**

**What would you like to be added**
Add a stylesheet for printing out the documentation. Remove interactive elements and change styles to suit printing.

**Why is this needed**
This is a low-priority suggestion. Some people (maybe not many, in 2020) like to print out documentation or read it in paged form on e-readers etc.
For that niche of readers, this change will improve the experience.

**Comments**
/priority awaiting-more-evidence

**Comment by sftim** [comment]
[Example: Deploying PHP Guestbook application with Redis](https://github.com/kubernetes/website/files/4346237/guestbook.pdf)) rendered using [Prince](https://www.princexml.com/) 13.

*Pretty good* but with room to improve; see the last page for example.

**Comment by sftim** [comment]
Issue #20110 is slightly related.

**Comment by sftim** [comment]
> /language en

It's also OK to tackle this site-wide

**Comment by tengqm** [comment]
@sftim agree. Labelling `language/en` is only for facilitating issue search. Also, such a change would likely to happen in the English site first and then propagate to other localizations.

**Comment by sftim** [comment]
How about adding a label: area/css or similar?
