### ISSUE TITLE
Glossary correction required for kube-scheduler.

### ISSUE THREAD

**Issue by ysyukr** [kubernetes/website#19707]
**This is a Bug Report**
**Problem:**
The definition of kube-scheduler has changed in  #18092 .

However, kube-scheduler detects new pods and places pods on unassigned nodes, rather than placing nodes on unassigned nodes.
https://kubernetes.io/docs/concepts/scheduling/kube-scheduler/

**Proposed Solution:**
Need a kube-scheduler's glossary change.

***before***
Control plane component that watches for newly created Node with no assigned node, and selects a node for them to run on.

***after***
Control plane component that watches for newly created Pod with no assigned node, and selects a node for them to run on.

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?all=true#term-kube-scheduler

**Comment by sftim** [comment]
> Control plane component that watches for newly created Pod with no assigned node, and selects a node for them to run on.

I'd word this:
Control plane component that watches for newly created *Pods* with no assigned node, and selects a node for them to run on.

**Comment by sftim** [comment]
Fixed in #19708
