### ISSUE TITLE
Translate training/_index.html in Korean.

### ISSUE THREAD

**Issue by ysyukr** [kubernetes/website#19713]
**This is a Feature Request**

**What would you like to be added**
Translate training/_index.html in Korean.

**Why is this needed**
The following files are not translated into Korean.
- [ ] /en/docs/training/_index.html

**Comments**
Page to update: https://kubernetes.io/docs/training/

I am translating this document.
The translated document will be submitted to dev-1.17-ko.7 branch.

/language ko

**Comment by gochist** [comment]
@ysyukr Only bug fix will be accepted in dev-1.17-ko.7.

**Comment by ysyukr** [comment]
@gochist I know that the purpose of the dev-1.17-ko.7 branch is bugfixes and current updates.
During the update of dev-1.17-ko.7(#19712 ), the training added to docs/home was reflected as /training based on the URL, but when checking the preview, it was changed to /ko/training and it was judged that translation of the traning document is necessary.

https://deploy-preview-19712--k8s-dev-ko.netlify.com/ko/docs/home/

**Comment by gochist** [comment]
@ysyukr That's right. Thank you!
