### ISSUE TITLE
API Reference wraps field names across many lines

### ISSUE THREAD

**Issue by briantkennedy** [kubernetes/website#19757]
**Problem:**
On Chrome 80.0.3987.149 (Official Build) (64-bit) Linux the "Field" column in the API reference is too narrow to accommodate the field names in the API's structures, so the field names are wrapped across multiple lines.  This makes it hard to scan the field names for a specific subject of interest.

![docs-formatting](https://user-images.githubusercontent.com/3261986/77195221-83647f80-6a9e-11ea-87b9-c46092d12083.png)

**Proposed Solution:**
Adjust the table so field names fit on one line.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/

Kubernetes Version:
This appears to have started for the kubernetes 1.17 docs.  The 1.16 docs look fine.

**Comment by Arhell** [comment]
Hello, please see the solution
kubernetes/website#19771

**Comment by tengqm** [comment]
Fixed upstream.
/close
