### ISSUE TITLE
White stripe after footer

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#19755]
**This is a Bug Report**
White stripe after footer

**Problem:**
White stripe after footer

**Proposed Solution:**
Remove padding in this button

**Page to Update:**
https://kubernetes.io/

![2](https://user-images.githubusercontent.com/26163841/77189047-a1060900-6adf-11ea-938d-1e175cd3492b.jpg)
/assign

**Comment by tengqm** [comment]
/close

due to the proposed fix has been rejected.
Let's see switching over to docsy would fix this.
