### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/field-selectors/

### ISSUE THREAD

**Issue by f-ruta** [kubernetes/website#19775]
In the 'Supported fields' section of the 'Field Selectors', text reads "Supported field selectors vary by Kubernetes resource type. " This is a pretty useless statement, with just an example telling us that if you do not put a valid one an error is returned.  

Kindly clarify where the various field-selector for the different resource types are documented.

##Supported fields
Supported field selectors vary by Kubernetes resource type. All resource types support the metadata.name and metadata.namespace fields. Using unsupported field selectors produces an error. For example:

kubectl get ingress --field-selector foo.bar=baz
Error from server (BadRequest): Unable to find "ingresses" that match label selector "", field sele

**Comment by tengqm** [comment]
/close 
as a dup.
