### ISSUE TITLE
Show failed Netlify builds as CI failures in GitHub

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19789]
**This is a Feature Request**

**What would you like to be added**
When a pull requests fails to preview, show that in GitHub either as a failed build or as a failed [check](https://developer.github.com/v3/checks/).

**Why is this needed**
- At the moment, someone submitting a pull request might not be aware that their code isn't OK to merge.
- At the moment, Prow might be willing to merge a broken PR.

**Comments**
I saw this symptom on PR #19760

**Comment by sftim** [comment]
Here's an example of what shouldn't happen:
![Failed Netlify preview](https://user-images.githubusercontent.com/22591623/77255958-ffa7c000-6c62-11ea-933d-00db748890bc.png)

**Comment by gavinfish** [comment]
Totally agree. But I think only administrators have the permission to do this work 🤔 ?

**Comment by Colstuwjx** [comment]
My question is how to determine such failure?

The preview message was automatically sent by netlify bot, and it's hard to check if there is a fail, I filed an issue about this, and see [18619 #comment](https://github.com/kubernetes/website/issues/18619#issuecomment-576068647), we finally workaround by re-adding the netlify setting.

We've removed the travis CI check in [PR #13598](https://github.com/kubernetes/website/pull/13598), do we need to re-import the travis CI again? Or there is another better solution to solve this problem?

**Comment by sftim** [comment]
GitHub lets you mark certain checks as required, separate from how Prow sees the world. Maybe that's an option?

**Comment by Colstuwjx** [comment]
You mean build sth like [this](https://github.com/apps/reviewdog) with the GitHub checks? But it may needs a GitHub app for receiving GitHub check hook? Do we need to re-implement another GitHub app?

How about re-enable travisCI job and just run some check scripts?

**Comment by sftim** [comment]
https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks covers what I have in mind.

**Comment by tengqm** [comment]
/language en

any follow up on this? @sftim

**Comment by sftim** [comment]
I've filed the issue but haven't made any start on work in this area.

BTW it's not really language/en as I see it - this applies to all localizations

**Comment by tengqm** [comment]
See my comment to another issue. Adding 'en' lang is only to serve issue search. We all know fixing this will benefit all localizations.

**Comment by sftim** [comment]
/retitle Show failed Netlify builds as CI failures in GitHub

**Comment by sftim** [comment]
I think this is implemented now - thanks Netlify.
/close
