### ISSUE TITLE
kubernetes 1.17 docs cause a horizontal scrollbar or at least 1440px width

### ISSUE THREAD

**Issue by tedder** [kubernetes/website#19795]
**This is a Bug Report**
**Problem:**

I noticed that as of 1.17, [the kubernetes API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/) need a horizontal scrollbar at what I consider a "normal" browser width. 

[browsersize.com](https://browsersize.com) says my width is 1228px (with 100% text zoom, BTW). In the screenshots below you'll see how the main section needs a scrollbar, and it's especially annoying when clicking an anchor link, which anchors to the "right" of the window, requiring scrolling left every time.

**Proposed Solution:**

I suspect it's the `pre` tags used for the `kubectl`/`curl` dropdowns that is causing it, as those appear to be new in this version. Probably needs some CSS in there.

If I experiment with my browser width, the scrollbar goes away at 1440px. Obviously it's up to you what you consider the minimum viable width; even if it is 1440px, the anchor tags should be moved to the left side. They are driven by an `id` of the `<h1>` tag, I'm not entirely sure what is causing them to go to the right.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/

**Additional Information:**

I mostly use Chrome (v80.something) on Ubuntu. I confirmed the same (or nearly the same) behavior on Firefox/Ubuntu and Chrome/MacOS. With MacOS I could only get the window to 1439px, and the scroll bar was still there.

I'll attach screenshots as a comment on this bug report.

**Comment by tedder** [comment]
scroll bars:
![Screenshot from 2020-03-22 12-51-14](https://user-images.githubusercontent.com/97914/77259415-80a09080-6c3e-11ea-9f85-829ff3073175.png)

anchor navigation behavior:
![Screenshot from 2020-03-22 12-51-24](https://user-images.githubusercontent.com/97914/77259414-8007fa00-6c3e-11ea-8858-7478c2ab931d.png)

**Comment by sftim** [comment]
Thanks for reporting this @tedder 
/kind bug
/priority backlog

**Comment by tedder** [comment]
/remove-lifecycle stale

Bumping this just so it doesn't get closed.
