### ISSUE TITLE
Freeze kubernetes/website to support easy 1.18 Kubernetes release

### ISSUE THREAD

**Issue by VineethReddy02** [kubernetes/website#19809]
As Kubernetes 1.18 release is on 24th March. Freezing k/website to stop all upcoming merges for easy release.

**Comment by sftim** [comment]
PRs manually marked held during release:
https://github.com/kubernetes/website/pull/14792
https://github.com/kubernetes/website/pull/19689
https://github.com/kubernetes/website/pull/19740
https://github.com/kubernetes/website/pull/19759
https://github.com/kubernetes/website/pull/19808

**Comment by sftim** [comment]
and:
https://github.com/kubernetes/website/pull/19756
https://github.com/kubernetes/website/pull/19692
https://github.com/kubernetes/website/pull/19685
https://github.com/kubernetes/website/pull/19550
https://github.com/kubernetes/website/pull/19265
https://github.com/kubernetes/website/pull/18046

**Comment by VineethReddy02** [comment]
and:
#19773
#19631

**Comment by sftim** [comment]
and:
https://github.com/kubernetes/website/pull/19829

**Comment by sftim** [comment]
@VineethReddy02, is it OK to `/hold cancel` the held PRs?

**Comment by tengqm** [comment]
Looks like removing the `tide/merge-blocker` label is not resurrecting those PRs. May be we can try close this issue?

**Comment by VineethReddy02** [comment]
/hold cancel
v1.18 release is out.
