### ISSUE TITLE
Standardizing Kubernetes Architectural Diagrams  - a.k.a Diagram Creation Guide

### ISSUE THREAD

**Issue by dkypuros** [kubernetes/website#19811]
**Summary of Feature Request**
Kubernetes documentation needs better diagrams. We need a standard set of Kubernetes icons and clear guidelines for content creators to make their own architectural diagrams.

**Brief Overview of Project**
During a K8s SIG-Docs meeting (November 2019), several SIG Docs members commented on the lack of consistency between Kubernetes icons and diagrams on the official Kubernetes Docs website (see [“What is Kubernetes”](https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/), and [“Kubernetes Components”](https://kubernetes.io/docs/concepts/overview/components/)). 

**Do you want to help?**
Are you interested in helping? Can you join a Zoom call to talk through the effort and help build some icons? Feel free to message me on slack @david.kypuros. We're not ready for a PR, just looking for people to assist with this mini-project.

**Please Review for more background** 

- [Kubernetes SIG-DOCS SoW - Kubernetes Architecture Diagrams & Icons](https://docs.google.com/document/d/19XY2PkkAB489sM-56lJ9auNcLOd3RV63t_dql8XB_PQ/edit?usp=sharing)

- [Istio Example for good direction](https://istio.io/about/contribute/diagrams/)

**Comment by dkypuros** [comment]
Artwork Reference (commenting enabled):

[Kubernetes Architectural Diagram Guide](https://docs.google.com/drawings/d/11P-yXzso7zapqyqP3ulnIsQ1UE7IbzEi-7kp5jNebLM/edit?usp=sharing)

[Icons Kubernetes Architectural Diagram Guide](https://docs.google.com/drawings/d/12qn4y9OYsareFsa2zV1MVqLBapetFCdXyJKU1oaVqe8/edit?usp=sharing)

[Istio-Diagram-Guide](https://docs.google.com/drawings/d/14eM3aPdmRtsCR2zcibVicomApaW7x11fdE_uwLG4ZXA/edit) - Inspiration from CNCF Friends

**Comment by Fale** [comment]
Hi,
This is a very interesting topic for me, so thanks for your work!

0. The kube-controller-manager icon is not very clear for me.
1. There are 2 different icons for kube-controller-manager, but I think one of the two should be called clud-controller-manager. I think that both icons are not very clear, as for 0.
2. In `Icons Kubernetes Architectural Diagram Guide` there alignment problems in the bottom right area
3. The istio-diagram-guide seems to have some access restrictions. Can those be lifted?

Thanks again for the great work :-)

**Comment by dkypuros** [comment]
> Hi,
> This is a very interesting topic for me, so thanks for your work!
> 
> 1. The kube-controller-manager icon is not very clear for me.
> 2. There are c for kube-controller-manager, but I think one of the two should be called clud-controller-manager. I think that both icons are not very clear, as for 0.
> 3. In `Icons Kubernetes Architectural Diagram Guide` there alignment problems in the bottom right area
> 4. The istio-diagram-guide seems to have some access restrictions. Can those be lifted?
> 
> Thanks again for the great work :-)

Awesome feedback! 

1. Fixed it. Still not 100% happy with my funky "controller" icons though :-) I welcome any graphical help. All I could think of was "Atari Controllers" ;-)

2. Fixed the "2 different icons". Agree, those two icons aren't clear.

3. Fixed.

4. To get access requires a few steps. I just copied the google draw file, and dropped it here [docs.google.com/drawings...](https://docs.google.com/drawings/d/1ohUo65ifi4sBbTNV5hRBg-n5Frab3Z6qgz6GDnO6Fp4/edit?usp=sharing)

PS
Fale: Ping me on slack if you want edit access. I hang out in the SIG-DOCS channel.

**Comment by celestehorgan** [comment]
I don't have real feedback for you yet, but wanted to bring up that [this section](https://github.com/kubernetes/community/tree/master/icons) exists in the k8s community repo.

**Comment by dkypuros** [comment]
> I don't have real feedback for you yet, but wanted to bring up that [this section](https://github.com/kubernetes/community/tree/master/icons) exists in the k8s community repo.

Taking a closer look at this section...

**Comment by sftim** [comment]
A similar issue: #21763

**Comment by sftim** [comment]
Still very valuable IMO
/remove-lifecycle stale

**Comment by sftim** [comment]
If we add this, let's have https://www.kubernetes.dev/docs/ link to it.

**Comment by mehabhalodiya** [comment]
@dkypuros I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @dkypuros

**Comment by dkypuros** [comment]
Thanks. I'll consider it.

**Comment by divya-mohan0209** [comment]
This is still relevant IMO
/triage accepted

**Comment by sftim** [comment]
We have a [diagram guide](https://kubernetes.io/docs/contribute/style/diagram-guide/)

/close
as complete
