### ISSUE TITLE
Issue with /docs/concepts/abstractions/controllers/statefulsets/

### ISSUE THREAD

**Issue by necro351** [kubernetes/website#1981]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
It is very restrictive that members of a stateful set have to be deleted in reverse ordinal order. Is it possible to allow members to be deleted in any order? It is also restrictive that all members have to be up and active before new members can be added, can this restriction and other ordinal-number related restrictions be removed?

**Proposed Solution:**
The document does not state whey these restrictions are imposed, so I am not sure what has to be fixed or worked around to enable these restrictions on stateful sets to be lifted.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
This restriction is mostly due to implementation. With Parallel management policy introduced since v1.7, there is no such restriction.
