### ISSUE TITLE
‘Whats next’ section is missing from  https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

### ISSUE THREAD

**Issue by rohitanair** [kubernetes/website#19819]
**Problem:**
Page: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
Issues:
1.	‘What next’ section is missing from this page.
2.	The title of this page should be only ‘Jobs’ like DaemonSet, Deployment, etc. 

**Proposed Solution:**
1. 'What next' section should be added with references to relevant documents. 
2. Title of the page should be 'Jobs' and NOT 'Jobs - Run to Completion'

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

**Comment by sftim** [comment]
What should the _What's next_ section list, @rohitanair ?

(it's OK to outline this rather than provide exact detail)
