### ISSUE TITLE
Bad style for old version deprecate warning

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/website#19817]
**This is a Bug Report**

**Problem:**
When I select an old version doc, e.g. v1.15, I see:

![image](https://user-images.githubusercontent.com/3972545/77410597-12063300-6df6-11ea-84ab-6bdf28c744e3.png)

It seems that no proper css style applied, and looks odd. 

**Proposed Solution:**
Correct the style, and make it looks fine.

**Page to Update:**
https://kubernetes.io/...

**Comment by Colstuwjx** [comment]
![image](https://user-images.githubusercontent.com/3972545/85489625-d7818180-b602-11ea-81b8-7393127f0c03.png)

After we switched to docsy theme, however, this issue still exists.
/remove-lifecycle stale

**Comment by celestehorgan** [comment]
:/ I thought I merged a PR that fixed this recently, but apparently not.

/assign @celestehorgan

**Comment by celestehorgan** [comment]
@sftim Is that feasible for us to fix though? I was under the impression that old docs were snapshots and thus not updated.

**Comment by sftim** [comment]
@celestehorgan our default policy is not to backport changes or fixes; however, it's fine to make exceptions when there is a good reason to.

(I'm fine with the decision going either way on this one).

**Comment by celestehorgan** [comment]
@sftim I personally don't think we should backport changes on this one. It might be better to save that level for breaking changes only, lest we get into a scenario where we're back-porting All The Things.

**Comment by sftim** [comment]
The one counter I'd offer is that the deprecation warning is _never_ rendered on the live site.

**Comment by sftim** [comment]
/triage accepted
_but_ this is a very low priority item
