### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by jasvantsingh** [kubernetes/website#19810]
**This is a Bug Report**

**Problem:**
Examples provided on the page does not work. Following yaml does not work:
```yaml
configMapGenerator:
- name: example-redis-config
  files:
  - redis-config
resources:
- redis-pod.yaml
```
The command **kubectl apply -f kustomization.yaml** gives the following error
```text
error: error validating "kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false
```

apiVersion and kind are mandatory but example does not provide appropriate values. 

**Proposed Solution:**
The page needs to be updated with correct examples.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/.

```text
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tengqm** [comment]
@sujaypillai where are we now?

**Comment by sujaypillai** [comment]
@tengqm Sorry for being late in updating here. I tested it out and below is screenshot for the same error if the user tries to create a ConfigMap without adding the pod resource config in `kustomization.yaml` 
<img width="1713" alt="Screenshot 2020-06-16 at 1 19 17 AM" src="https://user-images.githubusercontent.com/3936714/84688646-43644a00-af72-11ea-8235-2b7c983b92bb.png">

**Comment by tengqm** [comment]
Thanks for the confirmation, @sujaypillai 
/close
