### ISSUE TITLE
Inconsistency regarding multiple authorization modules

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#19828]
**This is a Bug Report**

**Problem:**
I found inconsistent information regarding how a multiplicity of authorization modules is handled.  https://kubernetes.io/docs/reference/access-authn-authz/authorization/#determine-whether-a-request-is-allowed-or-denied says the first one to make a decision wins.  https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#authorization says the request is allowed if any authorization module allows it.

**Proposed Solution:**
Consistently document the truth.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/
https://kubernetes.io/docs/reference/access-authn-authz/authorization/

1.17

**Comment by Colstuwjx** [comment]
> says the first one to make a decision wins

Which line told this? I don't see this meaning in that page.

/language en
/triage support

**Comment by MikeSpreitzer** [comment]
@Colstuwjx : "When multiple authorization modules are configured, each is checked in sequence. If any authorizer approves or denies a request, that decision is immediately returned and no other authorizer is consulted."

**Comment by MikeSpreitzer** [comment]
Looking at the code, it appears to me that the truth of the matter is as follows.  Each Authorizer has an Authorize method that inspects a request's Attributes and returns a Decision --- which can be DecisionDeny, DecisionAllow, or DecisionNoOpinion.  If all the configured Authorizers return DecisionNoOpinion then the request is rejected.  Most Authorizers eschew DecisionDeny, choosing between only DecisionAllow and DecisionNoOpinion.  The lone exception is the one for webhooks; it relays whatever the remote server decided.

**Comment by MikeSpreitzer** [comment]
Here is another related doc bug: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#parallel-authorizers says that RBAC decides to deny in some cases.  But that is not true.  RBAC only returns DecisionAllow or DecisionNoOpinion.

**Comment by Colstuwjx** [comment]
> When multiple authorization modules are configured, each is checked in sequence. If any authorizer approves or denies a request, that decision is immediately returned and no other authorizer is consulted. If all modules have no opinion on the request, then the request is denied. A deny returns an HTTP status code 403.


>  If more than one authorization modules are configured, Kubernetes checks each module, and if any module authorizes the request, then the request can proceed. If all of the modules deny the request, then the request is denied (HTTP status code 403).

I think these two expresses the same meaning, for multiple authorization modules, it checks each module, and if one of them denied or approved, it would immediately returned, otherwise, if all modules no opinion, it also return 403. I don't think there is an inconsistency.

**Comment by MikeSpreitzer** [comment]
There is an inconsistency because an authorization module returns one of three decisions: DecisionAllow, DecisionDeny, or DecisionNoOpinion.  With that in mind, those two passages describe different behavior.

In other news, nowhere does it clearly say that an authorization module makes one of three decisions.

**Comment by MikeSpreitzer** [comment]
Also, the text in https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#authorization is a bit awkward and outdated.  The second paragraph says

> The request is authorized if an existing policy declares that the user has permissions to complete the requested action.

At this point the reader has not been told that there are policies.  Even more to the point, "policy" is redolent of ABAC --- which is no longer the only option.  This introductory text continues with ABAC specific content, and does not even identify it as such.  Only in the last paragraph is it mentioned that there are other options besides ABAC.

**Comment by MikeSpreitzer** [comment]
Also: https://kubernetes.io/docs/reference/access-authn-authz/authorization/#authorization-modules lists some of the available "modes" but not all of them.
