### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by johnsmartco** [kubernetes/website#19835]
I really like the tutorials (awesome) but suggest adding inter-module navigation. For example, when I completed Module 1, I went into a survey and answered it. But then I couldn't find an obvious way to proceed to Module 2. Can you add that navigation? I had to backtrack to https://kubernetes.io/docs/tutorials/, and then starting the next modules after figuring out the left sidebar had direct links.  Adding better inter-module Prev / Next / Home navigation would help a lot of users.  Perhaps after each completed module survey page, and/or globally in each module's page UI. Thanks for considering this request!

**Comment by Philipsty** [comment]
Hello team, I am reviewing this as a first issue

**Comment by Philipsty** [comment]
@sftim @spzala @tengqm 
Hello all, I have worked on this as my first issue. I added navigation buttons to allow the user to return to the previous Kubernetes basics module and the Kubernetes basics home screen.

eg. Module 2 will have the following buttons at the end of the interactive tutorial

{Return to Module 1}  {Home} {Continue to Module 3}

I have updated the modules and made a PR,
https://github.com/kubernetes/website/pull/28292

Please let me know if this looks good to you and if this issue can be assigned to me? Thank you

**Comment by bradtopol** [comment]
Done! Thanks @Philipsty

**Comment by Philipsty** [comment]
Thank you @bradtopol

**Comment by mehabhalodiya** [comment]
Closing this as it's been addressed in https://github.com/kubernetes/website/pull/28292

/close
