### ISSUE TITLE
Update version selector for supported previous versions

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#19841]
Now that #19116 has merged, 1.18 docs are live! 🎉 

## What's broken?

Once you select a previous version, the selector doesn't allow you to return to 1.18.

## How to fix it

The release branch for each supported version needs [updates like this](https://github.com/kubernetes/website/commit/73b9853fcbf66d16c7e5682897e5950c63603714#diff-618063036395fe9ee107f22b46c9eade) to [`config.toml`](https://github.com/kubernetes/website/blob/master/config.toml#L69-L131):

- [release-1.17](https://github.com/kubernetes/website/blob/release-1.17/config.toml)
- [release-1.16](https://github.com/kubernetes/website/blob/release-1.16/config.toml)
- [release-1.15](https://github.com/kubernetes/website/blob/release-1.15/config.toml)
- [release-1.14](https://github.com/kubernetes/website/blob/release-1.14/config.toml)

@irvifa 👋 This is a good thing to be aware of during the 1.19 release.

/assign @VineethReddy02 
/cc @jimangel 
/sig docs

**Comment by tengqm** [comment]
This has been fixed by the four related PRs.
/close
