### ISSUE TITLE
ZSH Completion setup instructions assumes bash-completion

### ISSUE THREAD

**Issue by MikaelSmith** [kubernetes/website#19844]
**This is a Bug Report**

**Problem:**

The instructions for setting up shell autocompletion for zsh refer to `complete`, which doesn't exist in a default installation. They also appear to be unnecessary for making autocompletion of an alias work.

There was a lot of discussion around calling similar commands causing the `source <(kubectl completion zsh)` to return exit code 127 in https://github.com/kubernetes/kubectl/issues/125. The solution removed those calls as unnecessary.

**Proposed Solution:**

Note that autocompletion for an alias will probably work. If not, you can install the `bash-completion` package and then run the suggested `complete` command.

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by sftim** [comment]
> Note that autocompletion for an alias will probably work. If not, you can install the bash-completion package and then run the suggested complete command.

@MikaelSmith, would you be willing to describe the changes to the page that someone should make so that this issue is fixed?

**Comment by MikaelSmith** [comment]
I think the only thing I'd add is that I found I needed to install a bash-completion package. Instructions are OS-specific.
