### ISSUE TITLE
Improve diagram for scheduling framework extension points

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#19846]
**This is an enhancement request**

**Problem:**
The diagram at https://kubernetes.io/docs/concepts/scheduling/scheduling-framework/#extension-points does not match up to the text on that page. Also the diagram is a little hard to read on fixed / large displays - the reader might want to turn their head.

**Suggested Approach:**
How do _you_ want to improve this?

You might consider one or several pieces from the following ideas:
- convert the drawing to [SVG](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics)
- change the text in the drawing to match the text of the page
- redraw the diagram to help readers understand the way plugins run in sequence
- redraw the diagram to emphasize that extension points let you use plugins

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling/scheduling-framework/#extension-points

**Comment by prasadkatti** [comment]
Another idea would be to look using mermaid.js to create the diagram. That would make updates to the diagram rather easy.
