### ISSUE TITLE
Configure a Pod to Use a PersistentVolume for Storage - 403 Forbidden error

### ISSUE THREAD

**Issue by AnuRam123** [kubernetes/website#19870]
**This is a Bug Report**

description. -->

Following https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
**Problem:**
when i run the step from the pod 
curl http://localhost/
root@task-pv-pod:/# curl http://localhost/
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.17.9</center>
</body>
</html>

I followed the instructions and need to know why I am unable to use the persistent volume
**System**
kubectl version --short=true
Client Version: v1.14.1
Server Version: v1.16.8+IK
**Pod logs:**

127.0.0.1 - - [26/Mar/2020:21:33:41 +0000] "GET / HTTP/1.1" 403 153 "-" "curl/7.64.0" "-"
2020/03/26 21:33:41 [error] 8#8: *6 "/usr/share/nginx/html/index.html" is forbidden (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

I see this defect https://github.com/kubernetes/website/issues/9523 very similar to mine but it has been closed 
**Details
In response to this:

Rotten issues close after 30d of inactivity.
Reopen the issue with /reopen.
Mark the issue as fresh with /remove-lifecycle rotten.

Send feedback to sig-testing, kubernetes/test-infra and/or fejta.
/close**
The issue needs to be reopened, or we need to know why this is occurring.

When i do a cat **root@task-pv-pod:/# cat /usr/share/nginx/html/index.html
Hello from Kubernetes storage**
so it is working.

**Comment by themonks** [comment]
Check if you are creating the `sudomkdir /mnt/data` in your host machine or in the correct node.
Create this inside the minikube master node. 

```
themonk@mymachine: ~/kubernetes$ minikube ssh
docker@minikube:~$ sudo mkdir /mnt/data
docker@minikube:~$sudo sh -c "echo 'Hello from Kubernetes storage' > /mnt/data/index.html"
```

**Comment by Bhavesh-Joshi** [comment]
> Check if you are creating the `sudo mkdir /mnt/data` in your host machine or in the correct node.
> Create this inside the minikube master node.
> 
> ```
> themonk@mymachine: ~/kubernetes$ minikube ssh
> docker@minikube:~$ sudo mkdir /mnt/data
> docker@minikube:~$sudo sh -c "echo 'Hello from Kubernetes storage' > /mnt/data/index.html"
> ```

@themonks Thanks for the solution. It works while with minikube cluster, but now the problem is that I am using kind cluster. I am facing the same issue with kind Kubernetes cluster. Please help me to overcome from it.

Waiting for the reply!

Thanks

**Comment by chenjianfei1989** [comment]
The index.html file must be created on the node where the Pod task-pv-pod is located
