### ISSUE TITLE
Chinese version page "学习 Kubernetes 基础知识" layout bug

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#19910]
**This is a Bug Report**

**Problem:**
Responsive design bug in page "学习 Kubernetes 基础知识" of chinese version website. In specific page width, "Kubernetes 基础模块" part is not correctly displayed
![image](https://user-images.githubusercontent.com/16621880/77812210-cea01300-70da-11ea-9016-4b6072b99eaa.png)
![image](https://user-images.githubusercontent.com/16621880/77812214-d790e480-70da-11ea-9aaa-6b94633551e8.png)

**Proposed Solution:**
Check the codes of this page
**Page to Update:**
https://kubernetes.io/zh/docs/tutorials/kubernetes-basics/

v1.18

**Comment by chenrui333** [comment]
looks like I could not reproduce?

![image](https://user-images.githubusercontent.com/1580956/85195429-75dab380-b2a0-11ea-9555-f5cb8e17f400.png)

**Comment by tengqm** [comment]
Ya. Agreed. Tried with the new theme. It is no longer an issue.
/close
