### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/website#19937]
Windows node, not connecting after restarted.

Status is showing as NotReady even after so much time.

**Comment by neolit123** [comment]
for support requests try the #sig-windows channel on k8s slack.
alternatively log a ticket here:
https://github.com/kubernetes-sigs/sig-windows-tools
but provide better detail about your setup.

/close
