### ISSUE TITLE
Update container/containers-environment.md in Korean

### ISSUE THREAD

**Issue by bluefriday** [kubernetes/website#19964]
**This is a Feature Request**

**What would you like to be added**

Update concepts/containers/Container Environment view in Korean.

**Why is this needed**

There is an changes to concepts/containers/container-environment in Korean.

**Comments**

Page to Update:
https://kubernetes.io/docs/concepts/containers/container-environment/

**Comment by ysyukr** [comment]
안녕하세요.
container-environment.md 문서는 쿠버네티스 1.18 릴리스가 되며 container-environment-variables.md 문서의 이름이 변경된 이름입니다.

변경된 것에 대한 업데이트는 #19886 을 통해 반영될 예정에 있습니다.
참고 부탁드립니다.

**Comment by bluefriday** [comment]
Thanks. I'll close this issue. :D
