### ISSUE TITLE
Issue with k8s.io/ko/docs/reference/issues-security/issues/

### ISSUE THREAD

**Issue by guslcho** [kubernetes/website#19973]
**This is a Bug Report**

**Problem: Menu position is wrong 
I think it should be located at  [Kubernetes Issues and Security] > [쿠버네티스 이슈 트래커] 
but it is in this  [쿠버네티스 이슈 트래커]  

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/ko/docs/reference/issues-security/issues/

v1.18

**Comment by guslcho** [comment]
update issue

**Comment by gochist** [comment]
fixed by #21145
/close

**Comment by gochist** [comment]
@guslcho 감사합니다.
