### ISSUE TITLE
Improvement for k8s.io/docs/tasks/manage-kubernetes-objects/kustomization/

### ISSUE THREAD

**Issue by squaricdot** [kubernetes/website#19977]
List the version of kustomize that is integrated within kubectl

Updating kustomize in kubectl seems not easy implementable atm:

https://github.com/kubernetes/kubectl/issues/818

It was a bit confusing. I bet more people will have this struggle. I guess when this is listed clearly it saves time.

**Comment by sftim** [comment]
@squaricdot can you clarify: are you suggesting an improvement to kubectl, or a tweak to the page wording?

I read the issue text above and I wasn't sure.

(If you want to file an issue against `kubectl`, you can do that via [k/kubectl](https://github.com/kubernetes/kubectl/issues/new)).

**Comment by squaricdot** [comment]
What i mean is you can't run

`$ kubectl kustomize version`

to see which kustomize version is implemented in kubectl.

whereas `$ kustomize version` does give you that.

Back then I was struggling with some kustomization to eventually found out the incorporated kustomize did not support it.

By being able to verify this by running said command it can save some time.

**Comment by sftim** [comment]
@squaricdot I think you might be looking for https://github.com/kubernetes/kubectl/issues/new but I'm still not sure.

This repository is about the documentation for Kubernetes and that page you mentioned is about the documentation for `kubectl`.

Bear in mind that `kubectl kustomize` can be available to people who don't have any `kustomize` binary in their `$PATH`.
