### ISSUE TITLE
Issue with k8s.io/ko/docs/reference/issues-security/security/

### ISSUE THREAD

**Issue by guslcho** [kubernetes/website#19974]
**This is a Bug Report**

**Problem:**
I think it should be located at [Kubernetes Issues and Security] > [쿠버네티스 보안과 공개 정보]
but it is in this [쿠버네티스 보안과 공개 정보]

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/ko/docs/reference/issues-security/security/

v1.18

**Comment by gochist** [comment]
@guslcho 감사합니다!
fixed by #21145
/close
