### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by YanzhaoLi** [kubernetes/website#20003]
**This is a Bug Report**

**Problem:**
For the section of **Rotating a decryption key**,  would the first two steps be necessary?

1. Generate a new key and add it as the second key entry for the current provider on all servers
2. Restart all kube-apiserver processes to ensure each server can decrypt using the new key

**Proposed Solution:**
remove these two steps

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
It seems to me that key rotation inevitable involves creating new key material; that step is fundamental to the meaning of the term “key rotation”.

Can you clarify why you're asking that question @YanzhaoLi?

**Comment by YanzhaoLi** [comment]
> It seems to me that key rotation inevitable involves creating new key material; that step is fundamental to the meaning of the term “key rotation”.
> 
> Can you clarify why you're asking that question @YanzhaoLi?

@sfabel  Yes. but why should we add it as the second key entry and restart all kube-apiserver processes? By my limited knowledge, I think the following four steps are ok:

1. Make the new key the first entry in the keys array so that it is used for encryption in the config
2. Restart all kube-apiserver processes to ensure each server now encrypts using the new key
3. Run `kubectl get secrets --all-namespaces -o json` | `kubectl replace -f -` to encrypt all existing secrets with the new key
4. Remove the old decryption key from the config after you back up etcd with the new key in use and update all secrets

If so, for the step three: `kubectl get secrets --all-namespaces -o json` would do the decryption with the second key (As illustrated in the article: "Each provider supports multiple keys - the keys are tried in order for decryption"), while the `kubectl replace -f -` would do the new encryption with the first new key.

**Comment by sftim** [comment]
The existing page says:
> Changing the secret without incurring downtime requires a multi step operation, especially in the presence of a highly available deployment where multiple `kube-apiserver` processes are running.

I assume that the motivation for generating a new key and adding it as the second key entry is to _avoid downtime_.
If that's the case, I recommend leaving the existing documentation as-is.
