### ISSUE TITLE
Untidy prerequisites for “Set up Ingress on Minikube with the NGINX Ingress Controller”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20023]
**This is a Bug Report**

**Problem:**
The page [Set up Ingress on Minikube with the NGINX Ingress Controller](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) has a cautionary note about a prerequisite:
> **Caution**: For the Ingress resource to work, the cluster **must** also have an Ingress controller running.

this note belongs on the page, however the best place for it is in the Prerequisites section.

**Proposed Solution:**
Edit the page to move the caution note to be the very first thing inside the prerequisites section.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

/language en
/kind cleanup
/good-first-issue

**Comment by sftim** [comment]
If you are looking to work on this and would like help, please reply here. I'll watch for replies.

**Comment by prasadkatti** [comment]
Isn't there an effort underway to move minikube related pages onto the minikube site?
https://github.com/kubernetes/website/issues/15969 and https://github.com/kubernetes/minikube/issues/5686

**Comment by davivcgarcia** [comment]
I can work on this one! Should I?

**Comment by Heena-PyCloud** [comment]
> If you are looking to work on this and would like help, please reply here. I'll watch for replies.

I am looking to start contributing. looks like ..I can start with this.

**Comment by sftim** [comment]
Go for it! Contributions welcome.

Bear in mind https://www.redhat.com/en/blog/dont-lick-cookie when it comes to deciding if you want to work on this.

@prasadkatti I think this example only happens to use Minikube; a separate PR could rework it to explain how to try out Ingress with a different kind of learning environment.

**Comment by davivcgarcia** [comment]
@sftim I'm reviewing the content and looks like the tutorial is explaining how to deploy the Ingress Controller, which is exactly what the caution note is mentioning. IMHO, the caution node should be removed instead of moved to other section.

**Comment by davivcgarcia** [comment]
@sftim another good point is that `task-tutorial-prereqs.md` is saying the user could use Kubernetes playgrounds (Katacoda, play-with-k8s) which are not Minikube.

**Comment by sftim** [comment]
Sure, it's OK to remove the caution note.

https://github.com/kubernetes/website/issues/20023#issuecomment-607440989 sounds like it could be a new separate issue(?)
