### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/field-selectors/

### ISSUE THREAD

**Issue by ctxrag** [kubernetes/website#20046]
**This is a Bug Report**

**Problem:**
I want to list all pods except those NOT in Completed state.
field selector still outputs pods in Completed phase when Selected not Completed in kubectl command
**Proposed Solution:**
`kubectl get pods --all-namespaces --field-selector=spec.nodeName=node1,status.phase!=Completed --no-headers

``test-2d7dbabf-f8cc-4c0b-af3b-80db52d2257e   nightly-2020-04-01-13-00-tokyo-demo-route-gt-362603152                 0/2   Completed   0     7h34m
test-2d7dbabf-f8cc-4c0b-af3b-80db52d2257e   nightly-2020-04-01-13-00-tokyo-demo-route-gt-4245049053                2/2   Running     0     13m
test-2d7dbabf-f8cc-4c0b-af3b-80db52d2257e   nightly-2020-04-01-13-00-willows-405-a2a-1380625152                    0/2   Completed   0     3h31m
test-2d7dbabf-f8cc-4c0b-af3b-80db52d2257e   nightly-2020-04-01-13-00-willows-405-a2a-1464250510                    0/2   Completed   0     7h33m`
**Page to Update:**
https://kubernetes.io/...

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Colstuwjx** [comment]
I think it's not a good place to ask questions.

For your question, relative issue see [this](https://github.com/kubernetes/kubernetes/issues/49387#issuecomment-424548856).

/triage support

**Comment by tengqm** [comment]
Confirmed on 1.16. Maybe you want to file a bug in the upstream project, not here. It sounds more like a bug in kubectl.

**Comment by tengqm** [comment]
Em, after digging into this, I found that 'Completed' is not a 'phase'. The valid phase values are: `Pending`, `Running`, `Succeeded`, `Failed`, `Unknown`. 
/close

**Comment by tengqm** [comment]
ps. https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2208-L2229
