### ISSUE TITLE
Buggy HTML entity in content guidelines page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20045]
**This is a Bug Report**

**Problem:**
The rendered page includes the following incorrect text:
> Kubernetes documentation includes applied examples of projects in the Kubernetes project&emdash;projects that live in the [kubernetes](https://github.com/kubernetes) and [kubernetes-sigs](https://github.com/kubernetes-sigs) GitHub organizations.

“&emdash;” is wrong.

**Proposed Solution:**
Change `&emdash;` to `&mdash;` in that page.

**Page to Update:**
https://kubernetes.io/docs/contribute/style/content-guide/

/kind bug
/good-first-issue
/language en

**Comment by Heena-PyCloud** [comment]
working on this issue.

**Comment by sftim** [comment]
Fixed in PR #20063
