### ISSUE TITLE
PAAS CRI-O repo is missing

### ISSUE THREAD

**Issue by ramazanpolat** [kubernetes/website#20058]
**This is a Bug Report**

**Problem:**
The steps provided to install CRIO for CentOS/RHEL contains the following step but the provided URL is not found(404) therefore CRIO cannot be installed as instructed:
```
# Install prerequisites
yum-config-manager --add-repo=https://cbs.centos.org/repos/paas7-crio-115-release/x86_64/os/
```
So installation of cri-o is failed with:

`Failed to download metadata for repo 'cbs.centos.org_repos_paas7-crio-115-release_x86_64_os_'`

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o

**Comment by sysadm1989** [comment]
Hello. I think this is an initiative @lsm5. He took and deleted all repositories - https://github.com/cri-o/cri-o/pull/3512/commits/b698bb4f8111e69565e04e823a36fa11febfa9f2.

Go to https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo

Drop on, please @lsm5

**Comment by lsm5** [comment]
@sysadm1989 I only stopped building for CentOS CBS. I'm sending builds to OBS instead. I didn't delete any CBS repos. It's quite likely because of the new CBS signing process https://lists.centos.org/pipermail/centos-devel/2020-March/036693.html

**Comment by sysadm1989** [comment]
Thank you @lsm5.

This is some kind of loony bin.

**Comment by tengqm** [comment]
/close
Not a doc issue.
