### ISSUE TITLE
Broken links from k8s.io/docs/concepts/cluster-administration/flow-control/ to API references

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#20066]
**This is a Bug Report**

**Problem:**
I tried to follow the links to the API Reference pages for FlowSchema and PriorityLevelConfiguration and I got to the right web page but not the right place in the web page.  The URL's segment identifier is missing a bit of stuff at the end.

**Proposed Solution:**
Fix the URLs.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

**Comment by Heena-PyCloud** [comment]
I will work on this.

**Comment by Heena-PyCloud** [comment]
Updated line 167(PriorityLevelConfigurations) &170(FlowSchemas) for correct api reference. #20077

**Comment by MikeSpreitzer** [comment]
@Heena-PyCloud : thanks!
