### ISSUE TITLE
Inadequate introductory paragraph on k8s.io/docs/reference/access-authn-authz/webhook/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#20067]
**This is a Bug Report**

**Problem:**
The introductory paragraph of https://kubernetes.io/docs/reference/access-authn-authz/webhook/ does not say what the page is about --- which is using a webhook for authorization.  The introductory paragraph just defines the generic idea of a webhook.  A reader reading that gets no idea of the relevance of that page.

**Proposed Solution:**
Make the page start out by saying that the page is about using a webhook to do authorization.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/webhook/

**Comment by sftim** [comment]
A very good idea!
/priority backlog
