### ISSUE TITLE
Scattered and incomplete documentation of query parameters in the API

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#20075]
**This is a Bug Report**

**Problem:**
There is no easy-to-find (perhaps none exists) compilation of query parameters understood by the API.  I first looked in https://kubernetes.io/docs/reference/using-api/api-overview/ and found none.  I then looked in https://kubernetes.io/docs/reference/using-api/api-concepts/ and found a few, but not all.  That page did not discuss timeout or label selectors or field selectors.  https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api gives a couple of example usages of `labelSelector` --- but the remainder of that API section actually documents the CLI for label selectors.  The corresponding page about field selectors, https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/ , does not discuss the API.

**Proposed Solution:**
Put a comprehensive list of understood query parameters in https://kubernetes.io/docs/reference/using-api/api-concepts/ , with links to full documentation of each.

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/api-concepts/

1.18

**Comment by tengqm** [comment]
Hi, Mike, did you check the API reference?
For example, https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#list-deployment-v1-apps

**Comment by MikeSpreitzer** [comment]
No, I did not.  I see what you mean now.  I was expecting some generic documentation.

**Comment by sftim** [comment]
Sounds like there's a case for adding a What's Next link to https://kubernetes.io/docs/reference/using-api/api-concepts/

**Comment by sftim** [comment]
/triage accepted
/sig api-machinery

I think it would be good to document generically what, eg, the `watch` parameter does and why you might want to specify it.

**Comment by sftim** [comment]
The context has changed but this still needs addressing; https://kubernetes.io/docs/reference/kubernetes-api/ does not list all query parameters as clearly as it could.

/remove-lifecycle rotten

**Comment by sftim** [comment]
I think it'd be useful to document common query parameters. So for example there might be a page that lists `allowWatchBookmarks` and `watch` and `timeoutSeconds`, and another page that tells you about `pretty`, and yet another page that tells you about `fieldManager`.

@MikeSpreitzer would you have time to update the issue description given the changes to the API reference since you logged this?

**Comment by sftim** [comment]
/reopen
I think we should still work on this
/remove-lifecycle rotten

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/common-parameters/common-parameters/ helps with this, right?

It would be nice to have some introductory text on that page that explains that the reference refers to query strings.

**Comment by tengqm** [comment]
The generated reference now contains a page on this. No further work is needed.
https://kubernetes.io/docs/reference/kubernetes-api/common-parameters/common-parameters/.
/close
