### ISSUE TITLE
Translate concepts/storage/dynamic-provisioning in Korean

### ISSUE THREAD

**Issue by sunminjeon** [kubernetes/website#20076]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/storage/dynamic-provisioning in Korean

**Why is this needed**
No translation concepts/storage/dynamic-provisioning.md in Korean

**Comments**

Page to update : https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

**Comment by ysyukr** [comment]
안녕하세요.
해당 이슈는 #19620 와 중복되며, 번역된 결과물은 현재 dev-1.18-ko.1에 #19952 pr로 병합이 완료되었습니다.
이에 불편하시더라도 다른 문서의 번역을 부탁드리겠습니다.

**Comment by sunminjeon** [comment]
@ysyukr
네 알겠습니다, 해당 이슈는 닫도록 하겠습니다!
