### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by JonnyWaffles** [kubernetes/website#20084]
Hi friends, in the first part the documentation https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/#real-world-example-configuring-redis-using-a-configmap

the third paragraph says "Add the pod resource config to the kustomization.yaml" but I believe it is supposed to read "Add the pod resource config to the red-pod.yaml". I could be mistaken but this section confused me. Cheers.

**Comment by Kartik494** [comment]
Hi @JonnyWaffles i think the pod resources is added to kustomization.yaml itself after [curl](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/config/redis-pod.yaml) into redis-pod.

**Comment by tengqm** [comment]
The text is correct.
/close
