### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/authentication/

### ISSUE THREAD

**Issue by mcristina422** [kubernetes/website#20086]
**Problem:**
The json code block at the bottom of this section https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats is not properly indented as a pretty print. The source code is properly indented though 

**Proposed Solution:**
Update Hugo version. v0.68.3 seems to work. But it fails to build plain html files like `user-guide-migration-notice.md`, so adding a header to those files fixes the fail build

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats

**Comment by gavinfish** [comment]
Ref #19905 and #19907.

The upgrade of hugo is ongoing. This should also be fixed when it is ready.
/unassign

**Comment by tengqm** [comment]
The pages are good now.
/close
