### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/guestbook/

### ISSUE THREAD

**Issue by alimirjahani7** [kubernetes/website#20088]
**This is a Bug Report**

useless master slave

**Problem:**
if the master pod gets stopped and then be restarted by Kubernetes, after each slave connects to master again, it removes its data. so it's useless to have slaves 
**Proposed Solution:**
redis cluster
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/kind bug
/priority awaiting-more-evidence

Maybe it's OK to say that this tutorial is only an example and that more care is needed for a production setup. @alimirjahani7 what do you think?

**Comment by alimirjahani7** [comment]
yes but i thought it was good for having stable redis
with more master and slave
and i waster a day on it.
and after some tests i found out it's same with one redis pod.

**Comment by tengqm** [comment]
the problem is about storage, i.e. where your data is persisted.
since the tutorial is not a full featured one, maybe a fix could be adding a warning to that page?
