### ISSUE TITLE
Page title formatting wrong for Ikhtisar Keamanan _Cloud Native_

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20112]
**This is a Bug Report**

**Problem:** The page [Ikhtisar Keamanan _Cloud Native_](https://kubernetes.io/id/docs/concepts/security/overview/) has underscores in the title. (HTML does not let you write formatting in page titles).

**Proposed Solution:** Fix the page title to remove the underscores.

**Page to Update:**
https://kubernetes.io/id/docs/concepts/security/overview/

**Additional Information:**
/kind bug
/language id

**Comment by sftim** [comment]
/priority backlog
Relevant to #20111

**Comment by girikuncoro** [comment]
this issue has been fixed
/close
