### ISSUE TITLE
Left menu doesn't work in mobile (ko)

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#20129]
**This is a Bug Report**

main issue fixed #19040

**Problem:**
Left menu doesn't work in mobile
**Proposed Solution:**
need fix on pl lang
fix en lang #19646 PR

**Page to Update:**
https://kubernetes.io/ko/docs/home/

/assign
/language ko

**Comment by ysyukr** [comment]
don't worry.
upstream pr #19040 is applied as #19886 to the dev-1.18-ko.1 branch, and will be applied to the master branch on 4/9.

**Comment by Arhell** [comment]
Hello @ysyukr 
Got it, then I close this PR
/close
