### ISSUE TITLE
Example: Deploying Cassandra with Stateful Sets - Page (Missing Storage Instructions)

### ISSUE THREAD

**Issue by gerlt** [kubernetes/website#20125]
https://kubernetes.io/docs/tutorials/stateful-application/cassandra/

Hello,

Happy to assist in fixing this issue, but the example doesn't properly address the storage required to deploy the stateful set.  Example:

kubectl create -f cassandra-storage.yaml 

(example, cassandra-storage.yaml)
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4

Check with 
kubectl get pv

**Comment by tengqm** [comment]
Looks like we got a PR for this but ... 
/language en
