### ISSUE TITLE
Issue with /docs/reference/ : provide yaml file reference documentation

### ISSUE THREAD

**Issue by matthewadams** [kubernetes/website#2012]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Can't find kubernetes yaml file reference (like [docker-compose yaml file reference](https://docs.docker.com/compose/compose-file/))

**Proposed Solution:**
Provide an exhaustive reference for the kubernetes yaml file.

**Page to Update:**
http://kubernetes.io/docs/reference/

**Comment by natejlong** [comment]
any updates on this? is a canonical reference available anywhere?

**Comment by tengqm** [comment]
Isn't the API doc what you wanted? https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/ 

As you may know, Kubernetes provides several dozens of resources that all can be provided in YAML format. It is not practical to exhaustively document them as YAML references.

**Comment by matthewadams** [comment]
At the time this issue was entered, it was difficult to find the reference.  This issue has since been addressed.
