### ISSUE TITLE
Inconsistency between docs that mentions cloud-controller-manager

### ISSUE THREAD

**Issue by mikejoh** [kubernetes/website#20137]
**This is a Bug Report**

**Problem:**
Hi,

[This](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager) section says the following:

> `kube-apiserver` and `kube-controller-manager` MUST NOT specify the `--cloud-provider` flag. This ensures that it does not run any cloud specific loops that would be run by cloud controller manager. In the future, this flag will be deprecated and removed.

Then reading [this](https://kubernetes.io/docs/concepts/overview/components/#cloud-controller-manager) section on the same topic (`cloud-controller-manager`) it says:

> `cloud-controller-manager` runs cloud-provider-specific controller loops only. You must disable these controller loops in the `kube-controller-manager`. You can disable the controller loops by setting the `--cloud-provider` flag to `external` when starting the `kube-controller-manager`.

I'm reading this as: You must not specify the `--cloud-provider` flag. On the other hand you must specify the `--cloud-provider` flag with the `external` argument to achieve the same thing, to disable the cloud controller loops in `kube-controller-manager`.

With that said i've just started to read up on the `cloud-controller-manager` and haven't figured out the "correct" answer yet.

**Proposed Solution:**
Change one of the sections mentioned above so that the information is consistent between docs.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager and/or https://kubernetes.io/docs/concepts/overview/components/#cloud-controller-manager

**Comment by tengqm** [comment]
Done. Feel free to reopen if further actions are desired in addition to #19705.
/close
