### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

### ISSUE THREAD

**Issue by artisticcheese** [kubernetes/website#20130]
UI issues with page
![image](https://user-images.githubusercontent.com/13176884/78572201-c6d42300-77ec-11ea-83b9-e8c485a84afd.png)

**Comment by neolit123** [comment]
@artisticcheese 
would you like sending a PR to fix the formatting of the page?

/kind bug
/sig windows cluster-lifecycle
cc @benmoss

**Comment by artisticcheese** [comment]
Done but I never did it before so not sure if I did it correctly

**Comment by benmoss** [comment]
If you send a PR in it will have a netlify preview that you can verify with. We should have checked that on the last one.
