### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by stockersky** [kubernetes/website#20131]
**This is a Bug Report**

**Problem: Wrong `kubectl get svc my-nginx` output for LoadBalancer service type exemple.**

**Proposed Solution:**
This is the given output from the doc. `ClusterIP` type is wrong for this service. It should be `LoadBalancer`.
```
NAME       TYPE        CLUSTER-IP     EXTERNAL-IP        PORT(S)               AGE
my-nginx   ClusterIP   10.0.162.149   162.222.184.144    80/TCP,81/TCP,82/TCP  21s
```

 An appropriate output would be:

```
NAME       TYPE           CLUSTER-IP   EXTERNAL-IP      PORT(S)          AGE
my-nginx   LoadBalancer   10.0.0.216   xx.xxx.xxx.xxx    8080:30163/TCP   23m
```

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by Vageesha17** [comment]
I am working on this issue.

**Comment by tengqm** [comment]
Fixed.
/close
