### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/out-of-resource/

### ISSUE THREAD

**Issue by shacharSilbert** [kubernetes/website#20149]
It would really help if we had information on how to get notified of evictions (i.e. what gets logged where) and how we could simulate such things.

**Comment by tengqm** [comment]
Does this feature exists?
Or you are asking for the doc for an existing feature?
/language en

**Comment by shacharSilbert** [comment]
It's not exactly a feature, but you do get logs of eviction somewhere.
What I mean here is this - If a pod gets evicted, who gets notified? Where and how can I find out when it happened? How do I handle the situation, which is crucial?

**Comment by tengqm** [comment]
Got what you meant, @shacharSilbert 
This sounds a big topic.

/sig scheduling
