### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

### ISSUE THREAD

**Issue by olavt** [kubernetes/website#20153]
It looks like there are some formatting issues with the text after this "If you’re using a different interface rather than Ethernet (i.e. “Ethernet0 2”) on the Windows nodes, you have to modify the line:"

Then it becomes very unclear what are the commands needed to execute vs what is other text. Looks like some incorrect markup.

**Comment by neolit123** [comment]
please watch https://github.com/kubernetes/website/issues/20130
/close
/triage duplicate
/sig windows cluster-lifecycle
