### ISSUE TITLE
Move task, Set up Konnectivity service

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#20165]
**This is a Feature Request**

The `Set up Konnectivity service` task is a single task in a new directory,
`https://kubernetes.io/docs/tasks/setup-konnectivity/setup-konnectivity/`

Investigate whether this new task directory is needed (added in 1.18 release) or if there is
another directory where the task page could be placed.
 
**What would you like to be added**
Move the [Set up konnectivity service](https://kubernetes.io/docs/tasks/setup-konnectivity/setup-konnectivity/) file to another location.

**Why is this needed**
Since there is only one task, remove the directory and place the task in an existing
directory or add as a single file off the left nav.

**Comments**
Feel free to propose a different location or justify the current location.

**Comment by sftim** [comment]
/priority backlog
/kind cleanup

If moving the page, remember to add a redirect.

**Comment by tengqm** [comment]
done
/close
