### ISSUE TITLE
Issue with k8s.io/pt/docs/home/

### ISSUE THREAD

**Issue by diegoaraujopro** [kubernetes/website#20176]
**This is a Bug Report**

**Problem:**
Page not found!
**Proposed Solution:**
Fix the link to portuguese concepts.
**Page to Update:**
https://kubernetes.io/pt/docs/concepts

**Comment by viniciusbds** [comment]
Hi @diegoaraujopro 
Unfortunately, this page has not yet been translated, but we are in the process of translating it.
thanks
/close
