### ISSUE TITLE
kubeadm documentation v1.18.0 is broken

### ISSUE THREAD

**Issue by pschulten** [kubernetes/website#20179]
**This is a Bug Report**

**Problem:**
Current installation method for kubeadm (container linux flavour) is wrong. I says:
```
# ...
RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
# ...
curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
# ...
```
which results in a 404
```console
$ RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
$ curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service"
404: Not Found
```
**Proposed Solution:**
provide a link to the correct file

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl 

Kubernetes Version: v1.18.0

**Comment by neolit123** [comment]
> 404: Not Found

are you setting RELEASE_VERSION to e.g. "v0.2.7" as this page instructs:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

this is the k/release git tag

**Comment by pschulten** [comment]
@neolit123  thanks for answering, I just copied the instructions from the docs for my setup and updated today to v1.18.0 and my scripts started to fail. So the RELEASE_VERSION was v1.18.0

**Comment by neolit123** [comment]
this works fine:
```
RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"

mkdir -p /opt/bin
cd /opt/bin
curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}
chmod +x {kubeadm,kubelet,kubectl}

RELEASE_VERSION="v0.2.7"
curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service
mkdir -p /etc/systemd/system/kubelet.service.d
curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:/opt/bin:g" > /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
```

RELEASE_VERSION is the version of k/release and RELEASE is the version of the artifacts.
you should not modify RELEASE_VERSION

/close

**Comment by pschulten** [comment]
I think this is may be related to https://github.com/kubernetes/kubernetes/commit/baec6d4af55d1e75d371893b1950a2df079461f2

**Comment by neolit123** [comment]
> I think this is may be related to kubernetes/kubernetes@baec6d4

`https://dl.k8s.io/release/stable.txt` resolves to v1.18.0 fine.

also this downloads:
https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubeadm

**Comment by pschulten** [comment]
@neolit123  sorry for the interruption. I didn't read everything :(
I was killed by the change in https://github.com/kubernetes/website/commit/5cf0d1955d3b729218e52a545a5368e29710e358
the current docs are correct, but not backwards compatible to my interpretation ;)

**Comment by neolit123** [comment]
no problem, make sure the kubeadm script snippet has RELEASE_VERSION set to the k/release tag.
