### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dual-stack/

### ISSUE THREAD

**Issue by mukesh-dua** [kubernetes/website#20183]
**Problem:**
The state of dual stack is unclear. 

Two Items:
1. The document page is reflecting 1.16 alpha. Whereas K8s 1.18 states that the SIG Network is moving the functionality to beta. 
2. Also there is a mention of support for Iptables proxier (Kube-proxy: Added dual-stack IPv4/IPv6 support to the iptables proxier. (#82462, @vllry)). 
3. No feature gate is observed for IPv6 on feature gate page (https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)

**Proposed Solution:**
Can we update K8S documentation.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/dual-stack/
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

Kubernetes Version: v1.18

**Comment by sftim** [comment]
The dual-stack feature gate should be listed in https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by tengqm** [comment]
Indeed, the feature gate was added but ... no description for it.
/language en
