### ISSUE TITLE
Unclarity on Flannel preparation step

### ISSUE THREAD

**Issue by olavt** [kubernetes/website#20193]
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

I think there is some unclarity about which nodes to run the following command on:

 "sudo sysctl net.bridge.bridge-nf-call-iptables=1"

Should it be run on all the Linux nodes in the control plane? Or on just the master?

**Comment by neolit123** [comment]
it should be run on all Linux nodes only.
you can send a PR to clarify this if you want.

/sig windows cluster-lifecycle
/kind cleanup
/help

requested change is here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#configuring-flannel

**Comment by sftim** [comment]
D'oh!

**Comment by mikejoh** [comment]
Hi @olavt, the PR [#20523](https://github.com/kubernetes/website/pull/20523) added a clarification when to configure the following: `sudo sysctl net.bridge.bridge-nf-call-iptables=1`. Please close this issue if you're satisfied with the changes. 

Thanks!
