### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by yvesdeceuleners** [kubernetes/website#20191]
**This is a Bug Report**

**Problem:**
The link to the Release Notes is ending in a 404 error. The link to the release notes is located in the paragraph **Before you begin**

**Proposed Solution:**
Make sure the link is working. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md

**Page to Update:**
https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
we changed the kubernetes repository folder structure a little, which broke old changelog links.
but i don't think k/website accepts minor fixes to old docs branches (e.g. dev-1.16, dev-1.17).

/sig docs cluster-lifecycle
/kind bug
