### ISSUE TITLE
Missing text in k8s.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

### ISSUE THREAD

**Issue by frostmar** [kubernetes/website#20198]
**This is a Bug Report**

Cut-off sentence in the topic's "Advanced features and flexibility" table entry for "Custom storage":

https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility
> Custom Storage | If you need storage with a  different performance mode (for example, time-series database instead of  key-value store) or isolation for security (for example, encryption  secrets or different

**Proposed Solution:**
Finish the sentence :o)

**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility

**Comment by viniciusbds** [comment]
triage/duplicate

**Comment by tengqm** [comment]
Already solved by #20204.
/close
