### ISSUE TITLE
Issue about flannel and kube-dns with /docs/admin/addons/

### ISSUE THREAD

**Issue by zh168654** [kubernetes/website#2023]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I used `kubeadm init --pod-network-cidr=10.244.0.0/16` and `kubectl create -f kube-flannel.yml` to create my cluster and it worked well.But each time the cluster restarts,flannel can not work properly.Though all pods are in running status,containers on node1 could not ping the ip of container on node2.

I described pods kube-dns and found logs as follow:
`FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "kube-dns-1708726655-34xrq_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-dns-1708726655-34xrq_kube-system(970ed8b7-c80d-11e6-9f3c-000c29e697f8)\" using network plugins \"cni\": open /run/flannel/subnet.env: no such file or directory; Skipping pod"`

**Proposed Solution:**
Each time cluster restarts,I delete the kube-flannel daemonset and redeploy it.Then everything works fine!Is that flannel daemonset must run after all system pods started?But it is impossible to manually redeploy it every time.What caused this problem and how to solve this?

**Page to Update:**
http://kubernetes.io/docs/admin/addons/

**Comment by tengqm** [comment]
This is not a documentation issue. Please try report an issue to https://github.com/kubernetes/kubeadm/issues
