### ISSUE TITLE
Umbrella issue: third party content

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#20232]
This issue replaces #15704, with gratitude to @aimeeu for her work.

### Updates

**UPDATE 1:** Removal process updated for 1.20 and subsequent releases

### What is third party content?

From the related [KEP for third party content](https://github.com/kubernetes/enhancements/pull/1327): 

> Third party content is content by or about a third party provider.

Our goal is to minimize and eliminate third-party content except when necessary for Kubernetes 
to function in-project.

"In project" means software in the Kubernetes org, which includes the [kubernetes](https://github.com/kubernetes) and [kubernetes-sigs](https://github.com/kubernetes-sigs) repositories.

### Requirements for including third party content

With the [KEP for third party content](https://github.com/kubernetes/enhancements/pull/1327) merged, it's time to remove third party content from the docs unless it meets community guidelines.

Guidelines for third party content are published at https://k8s.io/docs/contribute/style/content-guide/#what-s-allowed. To summarize:

> Kubernetes requires some third party content to function. Examples include container runtimes (containerd, CRI-O, Docker), networking policy (CNI plugins), Ingress controllers, and logging.
> 
> Docs can link to third-party open source software (OSS) outside the Kubernetes project if it’s necessary for Kubernetes to function.

### Removing third party content in 1.20 and later releases

Follow these guidelines for PRs that remove third party content:

- Link to this issue in the PR description.

- Notify the relevant SIGs and stakeholders.

   - Use the relevant `kubernetes/sig-foo-pr-reviews` alias(es) to affected SIGs.
   - Notify other stakeholders where possible and practical.

**Comment by sftim** [comment]
Is https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/ also a candidate for removal?

**Comment by zacharysarah** [comment]
@sftim 
> Is https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/ also a candidate for removal?

Yes. 👍

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/22285

**Comment by sftim** [comment]
Also see PR #22600

**Comment by sftim** [comment]
Moved to v1.20 milestone as there is work remaining.

**Comment by celestehorgan** [comment]
@zacharysarah – please review the merged PRs in this issue's history and update the checklist in the description. Thanks!

**Comment by zacharysarah** [comment]
@celestehorgan I'll remove the checklist instead--too easy to stale out, with little to no predictive value and questionable retrospective value.

**Comment by kbhawkey** [comment]
Since the 1.20 release is approaching, what are the remaining bits to be cleaned up/removed?
Any thoughts on:
https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

**Comment by sftim** [comment]
> https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

I recommend 2 changes.
1) Remove the “with-elk” from the URL
2) Run the log and metric solution inside the cluster; no need to mention Elastic cloud or other 3rd party services.

If that sounds right, I can open a specific issue to make roughly those changes and link it back here.

**Comment by kbhawkey** [comment]
> 
> Since the 1.20 release is approaching, what are the remaining bits to be cleaned up/removed?

Hope this did not come across the wrong way.
I agree that this work is ongoing. Someday this issue could close and the cleanup will continue.
The [Content Guide](https://kubernetes.io/docs/contribute/style/content-guide/) supports future cleanup and maintenance of the content.

**Comment by sftim** [comment]
I guess we should be moving this to the v1.21 milestone? Or something.

**Comment by annajung** [comment]
>I guess we should be moving this to the v1.21 milestone? Or something.

It's on my to-do list to create the next milestone and I'll make sure to update the milestone for this issue when I do.

**Comment by DanRoscigno** [comment]
@sftim , when I wrote this originally Elastic's k8s operator was not GA, so I did not include running Elasticsearch / Kibana inside the k8s cluster.  I can update using the operator if you like and remove the Elastic Cloud instructions.

> > https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/
> 
> I recommend 2 changes.
> 
> 1. Remove the “with-elk” from the URL
> 2. Run the log and metric solution inside the cluster; no need to mention Elastic cloud or other 3rd party services.
> 
> If that sounds right, I can open a specific issue to make roughly those changes and link it back here.

@sftim , when I wrote the ELK log and metrics docs originally Elastic's k8s operator was not GA, so I did not include running Elasticsearch / Kibana inside the k8s cluster.  I can update using the operator if you like and remove the Elastic Cloud instructions.  Here are the docs on the operator: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html

**Comment by sftim** [comment]
ElasticSearch (and Kibana and Logstash) are third party software, whether deployed using an operator or consumed as a managed service.

**Comment by DanRoscigno** [comment]
> ElasticSearch (and Kibana and Logstash) are third party software, whether deployed using an operator or consumed as a managed service.

@sftim I misunderstood when I read:
> Run the log and metric solution inside the cluster; no need to mention Elastic cloud or other 3rd party services.

I also read the KEP, and I understand that there is a difference between advertising and presenting technical details on how to operate a cluster.  I am happy to update the docs with OSS containers running within k8s if that is what you want.

**Comment by sftim** [comment]
Overall I'd prefer to have the tutorial about logging & monitoring focus on Kubernetes skills. That's why I'd prefer to show logging & monitoring run in the cluster.

It's fine to say “use this operator to run Elasticsearch” (or some other product) if the focus of the tutorial is about understanding how to make your pods and / or nodes send observability information to one place for aggregation and storage.

**Comment by DanRoscigno** [comment]
Sounds good, I will open an issue for this work.  Thanks for the feedback.

**Comment by reylejano** [comment]
/remove-lifecycle stale

I'll move this issue to the 1.22 milestone when the milestone is created

**Comment by sftim** [comment]
(it's clear that we didn't staff any remaining work on this well enough to achieve it “soon”)

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/36983 is part of this issue.

**Comment by tengqm** [comment]
I'd suggest we close this one since the huge wave of this cleanup has long passed.
We still have some 3rd party contents floating around, but it is not big issue any more.
We can file individual issues & resolve them one by one.

Feel free to reopen if people still feel this one should persists.

/close
