### ISSUE TITLE
Page “Installing Kubernetes with KRIB” not suitable according to content guide

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20239]
**This is a Bug Report**

**Problem:**
The page [Installing Kubernetes with KRIB](https://kubernetes.io/docs/setup/production-environment/tools/krib/) does not fit with the website [content guide](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed) and the criteria for permitted content.

**Proposed Solution:**
Remove the page https://kubernetes.io/docs/setup/production-environment/tools/krib/
Netlify does not support 410 Gone as a response status, so remove the page outright (no redirect etc).

This removal should happen before the Kubernetes v1.19 release.

**Page to Remove:**
https://kubernetes.io/docs/setup/production-environment/tools/krib/

**Additional Information:**
Part of issue #20232
/kind cleanup

**Comment by Nishikoh** [comment]
I'm a beginner at programming.
Is this issue difficult for beginner?

**Comment by sftim** [comment]
@Nishikoh you can find beginner-friendly issues: https://github.com/kubernetes/website/contribute/
and you can also read https://kubernetes.io/docs/contribute/start/

You might need to learn [MarkDown](https://commonmark.org/) to work out how to make changes.

**Comment by Nishikoh** [comment]
@sftim Thank you for your reply.
I will try next chance :D

**Comment by zacharysarah** [comment]
This would make a good first issue, though.

/good-first-issue

**Comment by Nishikoh** [comment]
"good first issue"
In that case, I want to retry this issue.
Could I tackle this issue?

**Comment by zacharysarah** [comment]
@Nishikoh Absolutely!

**Comment by sftim** [comment]
/close

Addressed in #20515
