### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

### ISSUE THREAD

**Issue by bapata** [kubernetes/website#20254]
**This is a Bug Report**

**Problem:**
In the section: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#comparison-with-podaffinity-podantiaffinity
The link referred for "Motivation"  doesn't work (404 not found)
**Proposed Solution:**
Add correct link
**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#comparison-with-podaffinity-podantiaffinity

**Comment by tengqm** [comment]
Link fixed now.
/close
