### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/

### ISSUE THREAD

**Issue by ariksa** [kubernetes/website#20279]
**This is a Bug Report**

**Problem:**
The getting started guide doesn't work on CentOS 7.7.1908.
The section **_Installing kubeadm, kubelet and kubectl_** contains an error in this line:
`baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch`
Whereas `$basearch` is not defined.

**Proposed Solution:**
Replace `$basearch` with `$(uname -m)`

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm

**Comment by sftim** [comment]
/kind bug

So I think the line should change to
```
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-"$(uname -m)"
```
/good-first-issue
/priority important-longterm

Thanks for reporting this @ariksa

**Comment by sftim** [comment]
What's the error on CentOS 7.7.1908 @ariksa? YUM usually lets you use `$basearch` and other built-in variables in a repository configuration.

**Comment by ariksa** [comment]
The error is:
`https://packages.cloud.google.com/yum/repos/kubernetes-el7-/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found`
As it seems `$basearch` is evaluated to ""
BTW, `echo $basearch` returns empty as well.

**Comment by sftim** [comment]
Hmm. Try this:
```shell
python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
# might need to be:
python3 -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
```

What's the output?

**Comment by ariksa** [comment]
Loaded plugins: fastestmirror
{'arch': 'ia32e',
 'basearch': 'x86_64',
 'contentdir': 'centos',
 'infra': 'stock',
 'releasever': '7',
 'uuid': '49b6894a-e4c7-4444-9d2f-0387edb4bfbb'}

**Comment by sftim** [comment]
Looks like `$basearch` is set in YUM. The problem is that the page instructs the reader to use a “here document” to edit the YUM configuration.
/remove-triage support
/kind bug
/sig cluster-lifecycle
/priority important-soon

@ariksa thanks for clarifying.
