### ISSUE TITLE
URL of https://kubernetes.io/docs/contribute/new-content/new-content/ implies it's not for existing content

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20283]
**This is a Bug Report**

**Problem:**
If a reader sees a hyperlink https://kubernetes.io/docs/contribute/new-content/new-content/ they might conclude that the page is specifically about adding content and is not the right place to find advice about amending existing pages. 

**Proposed Solution:**
Consider how much this is an issue. I saw this when I wanted to link to https://kubernetes.io/docs/contribute/start/ and realized that the old URL was superseded. Maybe it's not the problem I think it might be.

If it is a problem, also consider what is the easiest way to provide a link to someone who is considering changing an existing page, so that they feel included and supported in that task.

**Page to Update:**
https://kubernetes.io/docs/contribute/#your-first-contribution
https://kubernetes.io/docs/contribute/new-content/new-content/

/sig contributor-experience

**Comment by kbhawkey** [comment]
I would add (flagged in initial PR) that the sub-directory and page file name should not be named identically.

**Comment by sftim** [comment]
/priority important-longterm

@celestehorgan this might be relevant to work you're shepherding, eg https://github.com/kubernetes/website/issues/21687
