### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by marcel-st** [kubernetes/website#20281]
Hi Guys,

the Interactive Terminal says it's out of diskspace, someone with admin privileges might need to have look at the backend.

Cheers,

Marcel

**Comment by sftim** [comment]
@BenHall you might want to know about this
/kind bug
/priority important-soon

**Comment by tengqm** [comment]
The problem is still there? @marcel-st

**Comment by BenHall** [comment]
On the Katacoda side we adjusted our infrastructure so this shouldn't happen in future.

**Comment by sftim** [comment]
@BenHall based on what you've written I'll close this.
@marcel-st please feel free to reopen the issue if symptoms recur

**Comment by irvifa** [comment]
/ close
