### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

### ISSUE THREAD

**Issue by madz0** [kubernetes/website#20286]
**This is a Bug Report**

**Problem:**
Doc says we can port forward using service/service_name instead of pod_name which does not work for me.

**Proposed Solution:**

**Page to Update:**
k8s.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Reproduce:
```
kubectl port-forward service/service_name 8383:8080
error: invalid resource name "service/service_name": [may not contain '/']
```

**Comment by Kartik494** [comment]
Hi @madz0 in my environment i got the expected output as 
 kubectl port-forward service/redis-master 7000:6379
Forwarding from 127.0.0.1:7000 -> 6379
Forwarding from [::1]:7000 -> 6379
It is working with service

**Comment by madz0** [comment]
Hi @Kartik494 thanks for the reply. Emm, so weird! Do you use the same version as mine? Any thoughts for my case?

**Comment by Kartik494** [comment]
@madz0  i m using version :
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

could you share details of error you got

**Comment by madz0** [comment]
@Kartik494 I see that my client version is some versions behind yours. I'll try to update it as well. BTW I've already shared the exact error message

**Comment by Kartik494** [comment]
@madz0  yes, seems like version may be an issue here.Can you try with 1.17!

**Comment by tengqm** [comment]
/close

Please feel free to reopen if 1.17 doesn't work.
