### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update/update-intro/

### ISSUE THREAD

**Issue by AndrewWPhillips** [kubernetes/website#20312]
**This is a Bug Report**

**Problem:**

I went to the page that supposedly says how to perform a rolling update, but it did not say how to do so.

**Proposed Solution:**

I'm pretty sure (to do it declaratively)  you just update the deployment's yaml somehow and run kubectl apply -f.  The page should explain that the following interactive tutorial shows how to do it manually (using kubectl set image) but it's better to do this declaratively.

**Page to Update:**
https://kubernetes.io/...

**Comment by suruaku** [comment]
You can edit the yaml with `kubectl edit deployment <name>`
The command will automatically apply the changes if there is no errors.

**Comment by AndrewWPhillips** [comment]
> You can edit the yaml with `kubectl edit deployment <name>`
> The command will automatically apply the changes if there is no errors.

Yes thanks I am aware of that.  I guess I should have been more explicit that I am reporting a bug in the documentation.
