### ISSUE TITLE
Issue with k8s.io/docs/tasks/tls/certificate-rotation/

### ISSUE THREAD

**Issue by mailhari** [kubernetes/website#20325]
We are using v1.16.3

Why do I see "Kubernetes version 1.8.0 or later is required" under 1.16 ? It is confusing if I should give certificate rotate flag in kubelet bring up or through kubelet config.

![image](https://user-images.githubusercontent.com/10446093/79227119-0f3eb100-7e7d-11ea-8706-4433804b1d69.png)

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by hariharanrbn** [comment]
Could someone confirm?

**Comment by mailhari** [comment]
Could someone confirm?

**Comment by tengqm** [comment]
it is a version requirement telling you that version before 1.8.0 doesn't have this feature.
/close
