### ISSUE TITLE
Translate concepts/configuration/secret.md

### ISSUE THREAD

**Issue by ysyukr** [kubernetes/website#20327]
**This is a Feature Request**

**What would you like to be added**
Translate configuration/secret.md in Korean.

**Why is this needed**
The following files are not translated into Korean.
- [ ] /en/docs/concepts/configuration/secret.md

**Comments**
Page to update: https://kubernetes.io/docs/concepts/configuration/secret/

I am translating this document.
The translated document will be submitted to dev-1.18-ko.3 branch.

/language ko

**Comment by sftim** [comment]
Once this lands, https://kubernetes.io/ko/docs/concepts/configuration/ will have all pages in the section translated!

**Comment by pjhwa** [comment]
@ysyukr 오랫동안 진행이 어려우신 것 같아서 제가 번역했습니다. (미리 말씀 못드려서 죄송합니다. 번역한 이후에 이 이슈가 올라와있다는 것을 알아서...)

**Comment by ysyukr** [comment]
> @ysyukr 미리 말씀 못드려서 죄송합니다. 대부분 번역한 이후에 이 이슈가 올라와있다는 것을 알아서... (오랫동안 진행이 어려우신 것 같아서 그냥 진행했습니다.)

저는 괜찮습니다. 😄 
제가 빠르게 하지 못한거니까요. 조만간 다시 리뷰도 하고, 번역도 참여하도록 하겠습니다.
코멘트 남겨주셔서 감사합니다.
