### ISSUE TITLE
Adding  Windows Server 2016 nodes to a v1.4.4 kops cluster on AWS - Error x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by khannag** [kubernetes/website#2033]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Adding  Windows Server 2016 nodes to a v1.4.4 kops cluster on AWS - Error x509: certificate signed by unknown authority

I am running into issues adding a Windows server 2016 node to a kubernetes cluster on AWS. Here are the steps that I have followed (per the instructions @ http://kubernetes.io/docs/getting-started-guides/windows/)

I used Kops version 1.4.4 to setup a kubernetes cluster on AWS. I was able to get a working cluster up and running.

root@ip-172-31-23-167:/home/ubuntu/kubernetes/cluster# kubectl cluster-info
Kubernetes master is running at https://api.kubernetes.gkkhanna.me
KubeDNS is running at https://api.kubernetes.gkkhanna.me/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://api.kubernetes.gkkhanna.me/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

root@ip-172-31-23-167:/home/ubuntu/kubernetes/cluster# kubectl get nodes
NAME                             STATUS    AGE
ip-172-20-113-98.ec2.internal    Ready     1d
ip-172-20-126-230.ec2.internal   Ready     1d
ip-172-20-36-169.ec2.internal    Ready     1d
ip-172-20-39-75.ec2.internal     Ready     1d

Then, I proceeded to add a Windows kubelet to this cluster. I built the kubelet and kube-proxy for windows. I ensured that I launched the Windows instance in the same VPC and as using the same security group settings as the existing Linux minions.

Then I ran the following commands.

$env:CONTAINER_NETWORK = "nat" (I am setting this to the default nat network created by docker. I havent created the transparent network yet since I was only trying to test addition of a Windows node to the cluster to start with).

.\kubelet.exe --hostname-override=ip-172-20-58-232.ec2.internal --pod-infra-container-image="apprenda/pause" --resolv-conf="" **--api_servers=https://api.internal.kubernetes.gkkhanna.me**

I am running into the following errors on my Windows instance.

1222 23:36:09.846648    3456 reflector.go:188] pkg/kubelet/config/apiserver.go:45: Failed to list *v1.Pod: Get https://api.internal.kubernetes.gkkhanna.me/api/v1/pods?fieldSelector=spec.nodeName%3Dip-172-20-58-232.ec2.internal&resourceVersion=0: x509: certificate signe
 by unknown authority
1222 23:36:09.849648    3456 event.go:208] Unable to write event: 'Post https://api.internal.kubernetes.gkkhanna.me/api/v1/namespaces/default/events: x509: certificate signed by unknown authority' (may retry after sleeping)
1222 23:36:09.850652    3456 reflector.go:188] pkg/kubelet/kubelet.go:387: Failed to list *v1.Node: Get https://api.internal.kubernetes.gkkhanna.me/api/v1/nodes?fieldSelector=metadata.name%3Dip-172-20-58-232.ec2.internal&resourceVersion=0: x509: certificate signed by u
known authority
1222 23:36:09.850652    3456 reflector.go:188] pkg/kubelet/kubelet.go:379: Failed to list *v1.Service: Get https://api.internal.kubernetes.gkkhanna.me/api/v1/services?resourceVersion=0: x509: certificate signed by unknown authority

1222 23:36:09.936651    3456 kubelet_node_status.go:77] Attempting to register node ip-172-20-58-232.ec2.internal
1222 23:36:09.938615    3456 kubelet_node_status.go:101] Unable to register node "ip-172-20-58-232.ec2.internal" with API server: Post https://api.internal.kubernetes.gkkhanna.me/api/v1/nodes: x509: certificate signed by unknown authority

I have gone through past similar issue sightings on github, but not sure if there is way to bypass the above cert check altogether or if there are alternate means to resolve it ? Would appreciate the help to see what I could be missing here ?

Kops release 1.4.4

**Comment by khannag** [comment]
I have worked around this issue by copying kubeconfig files for both the kubelet and kube-proxy from one of the linux worker nodes and copying them over to the windows host. The files were present inside /var/lib/kubelet and /var/lib/kube-proxy.

Then I specify the kubeconfig argument when running both the kubelet and the proxy on the windows side. With this workaround, I am able to get the Windows kubelet talk to the API server and get registered as part of the known kubelets the cluster has.

**Comment by chrislovecnm** [comment]
@khannag that sounds awesome! Are you still using Windows and kops?
