### ISSUE TITLE
Docsy theme bug tracker

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#20344]
This issue is a tracking thread for bugs with the application of the [Docsy Hugo theme](https://themes.gohugo.io/docsy/) to the website.

Preview URL: https://kubernetes-hugo-staging.netlify.com/docs/home/

UPDATE, 30 April 2020: All sections of the preview URL are ready for testing. 

- Before reporting a bug, please check to see if it's already reported.
- Please comment on this issue with any formatting or navigation bugs you discover.

**Comment by zacharysarah** [comment]
Language and version selectors don't work.

**Comment by gochist** [comment]
Currently on the master's website, if there is an unlocalized document, a link to the upstream document is provided in the menu on the left sidebar. But on the hugo staging website, it is not provided.

For example on master:
https://kubernetes.io/ko/docs/tasks/
![Screenshot_2020-04-15 태스크](https://user-images.githubusercontent.com/282159/79295040-ab66c780-7f12-11ea-8f96-f3c5a56ede47.png)

**Comment by pjhwa** [comment]
There is a typo for the youtube link like below:
https://youtbue.com/kubernetescommunity

**Comment by pjhwa** [comment]
There are broken links at the bottom of every documents like the below:

For example: https://kubernetes-hugo-staging.netlify.app/docs/setup/learning-environment/minikube/
At the bottom:
Last modified March 30, 2020: [content/en migrated from current master (36b21b7)](https://github.com/kubernetes/website/commit/36b21b7ed2fab42a385d3441c4fb6ce02b6788ed)

**Comment by zacharysarah** [comment]
Version selector is outdated.

**Comment by zacharysarah** [comment]
Language selector is outdated:

- Norwegian is enabled. (It [shouldn't be](https://github.com/kubernetes/website/blob/master/config.toml#L29).)
- Polish, Ukrainian are missing.

**Comment by zacharysarah** [comment]
Given how outdated the preview code appears, a merge PR is likely to generate a significant number of merge conflicts.

**Comment by sftim** [comment]
> Given how outdated the preview code appears

(from https://github.com/kubernetes/website/issues/20344#issuecomment-622221744)
I can help with a rebase, or even create my own PR that cherry-picks just the Docsy changes.

**Comment by sftim** [comment]
https://kubernetes-hugo-staging.netlify.app/docs/concepts/ seems harder to navigate on mobile than I'd expect. It turns out that's because there are 2 hamburger icons and one of them is hidden with a narrow viewport.

Examples (narrow viewport first; notice how the hamburger is actually extending right of the viewport)

|![300px viewport](https://user-images.githubusercontent.com/22591623/80802163-77dc9c00-8ba6-11ea-85dd-0948fc13b1f8.png)|![310px viewport](https://user-images.githubusercontent.com/22591623/80801966-d7867780-8ba5-11ea-98a3-04282dd818c7.png)|

**Comment by sftim** [comment]
The existing site has an icon you can click to copy a `{{< codenew >}}` block to the clipboard. The docsy site does not offer that behavior, AFAICT.

**Comment by sftim** [comment]
The version selector issue mentioned in https://github.com/kubernetes/website/issues/20344#issuecomment-622220569 looks partially fixed; however, the page at https://kubernetes-hugo-staging.netlify.app/case-studies/ does not have a working version selector.

**Comment by sftim** [comment]
Notes are blue in the existing docs but orange in the revised docs. I think it makes sense to have notes be blue and reserve orange for caution blocks. At the moment the Docsy site does not distinguish those blocks by color.

**Comment by sftim** [comment]
nit: The feature state shortcode renders the Kubernetes version as `<code>` and because of the revised styling also colors the text. I would render the “Kubernetes 1.18” (etc) part with black text.

**Comment by sftim** [comment]
nit: tab header styling looks odd (the skeumorphism of file tabs isn't as obvious compared to the existing site)
eg https://kubernetes-hugo-staging.netlify.app/docs/contribute/style/hugo-shortcodes/#tabs-demo-code-highlighting

**Comment by kbhawkey** [comment]
Looks like we are back to generating `.scss` files and committing the changes.
Docsy uses PostCSS (from the docsy docs),

`
To build or update your site’s CSS resources, you also need PostCSS to create the final assets. If you need to install it, you must have a recent version of NodeJS installed on your machine so you can use npm, the Node package manager. By default npm installs tools under the directory where you run npm install
`

**Comment by sftim** [comment]
_Following on from https://github.com/kubernetes/website/issues/20344#issuecomment-623548180_

Any way we can have the static site build do that generation?

It might mean that people contributing to docs have to add extra dependencies or switch to using a container-based local preview. (Given what Kubernetes is about, I'm fine with nudging people towards using containers).

**Comment by sftim** [comment]
The existing site offers readers the chance to subscribe by email to KubeWeekly. The Docsy equivalent doesn't seem to offer this anywhere.

**Comment by sftim** [comment]
not-yet-localized pages are missing (reported in #19309)

**Comment by sftim** [comment]
no placeholder text for search if viewport narrow (reported in #19308)

**Comment by kbhawkey** [comment]
> 
> 
> The existing site offers readers the chance to subscribe by email to KubeWeekly. The Docsy equivalent doesn't seem to offer this anywhere.

I see the option from the k8s home page. Would be nice if the `KubeWeekly` text provided a link to the newsletter (online)?

**Comment by sftim** [comment]
Case studies logo backgrounds don't match page body (reported in #20760)

**Comment by kbhawkey** [comment]
![code-block-yaml-docsy](https://user-images.githubusercontent.com/1696019/80993365-f2a4f180-8e08-11ea-8d7c-74148d15fb8c.PNG)

Page:
https://kubernetes-hugo-staging.netlify.app/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

Blend background color (no gray)?

**Comment by kbhawkey** [comment]
Some of the images are not displaying on https://kubernetes-hugo-staging.netlify.app/.
This is a former bug that may be fixed when the docs source/templates are updated.

**Comment by mrbobbytables** [comment]
I noticed a few things:
- The icons/menu on the right don't look quite right, I think the icons are suppose to be next to the names instead of above them  ([link](https://kubernetes-docsy-staging.netlify.app/blog/)):
![Screen Shot 2020-05-11 at 2 40 25 PM](https://user-images.githubusercontent.com/6500863/81598656-a8d28300-9395-11ea-8e33-dd288c4e2ca3.png)

- We may need to rethink how blog pages are organized / presented -- the view of the left hand menu is kind of messy ([link](https://kubernetes-docsy-staging.netlify.app/blog/2020/05/third-party-dual-sourced-content/)):
![Screen Shot 2020-05-11 at 2 44 05 PM](https://user-images.githubusercontent.com/6500863/81598932-0ff03780-9396-11ea-819a-070ad1e59ffc.png)


Low hanging fruit thing, but the [calendar](https://calendar.google.com/calendar/embed?src=nt2tcnbtbied3l6gi2h29slvc0%40group.calendar.google.com) that is linked to doesn't really contain much / pretty sparse, like it still has kubecon as last month. I don't know who manages it 😬

**Comment by zacharysarah** [comment]
@mrbobbytables The preview link is based on a seriously outdated branch. To test what it looks like right now, we need to merge #20874 and the PRs on which it depends. I'd hold off on further review until we merge #20874. Thanks for taking the time to review! 👍

**Comment by zacharysarah** [comment]
@sftim @gochist @kbhawkey @mrbobbytables and everyone:

As an update: we now have a PR (#20874) based on the current version of `master`. Much of the feedback here is either resolved by rebasing, or specific to Docsy as a theme rather than Gearbox's implementation of it. 

In order to keep feedback relevant and collected in a single source, I'm going to close this issue and recommend we give feedback on #20874. 

/close
