### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/assign-pod-node/

### ISSUE THREAD

**Issue by PatelRudra** [kubernetes/website#20348]
**This is a Bug Report**

**Problem:**
The description provide in the following section is somewhat missing out the details. It is not justifying the value of **weight** one should configure in the affinity section of a deployment.

> 
The weight field in preferredDuringSchedulingIgnoredDuringExecution is in the range 1-100. For each node that meets all of the scheduling requirements (resource request, RequiredDuringScheduling affinity expressions, etc.), the scheduler will compute a sum by iterating through the elements of this field and adding “weight” to the sum if the node matches the corresponding MatchExpressions. This score is then combined with the scores of other priority functions for the node. The node(s) with the highest total score are the most preferred.

**Proposed Solution:**

It would be best if this page can contain a legitimate example around the **weight** in Node affinity. 

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

v1.18

What is the significance of weight: 1 as compared to weight: 100 ?

Creating first issue in GIT, apologies if I have missed out something. Would be happy to hear from you.

**Comment by shannonxtreme** [comment]
From what I understand, the scheduler iterates through each `weight` field for each matched affinity term and computes a sum, then places pods in nodes that meet the scheduling requirements by order of highest weight sum. Is this correct?
