### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/on-premises-vm/dcos/

### ISSUE THREAD

**Issue by ivog1** [kubernetes/website#20359]
"Official Mesosphere Guide
The canonical source of getting started on DC/OS is located in the quickstart repo" !!!

HTTP 404 ?!?  Quickstart repo is missing !!

**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by viniciusbds** [comment]
The link is working perfectly. 
**page:** https://kubernetes.io/docs/setup/production-environment/on-premises-vm/dcos/#official-mesosphere-guide

**link:** https://github.com/mesosphere/dcos-kubernetes-quickstart

**Comment by viniciusbds** [comment]
@ivog1  you can test it again?

**Comment by tengqm** [comment]
yes. the link works.
/close
