### ISSUE TITLE
Issue with k8s.io/docs/concepts/security/overview/

### ISSUE THREAD

**Issue by magnologan** [kubernetes/website#20361]
**This is a Bug Report**

**Problem: 404 Error on OWASP Reference Links**
The OWASP links referenced on the General Code Security Guidance Table are outdated and giving 404 errors. https://kubernetes.io/docs/concepts/security/overview/#general-code-security-guidance-table

**Proposed Solution: Update links with new and correct ones:**

Old -> New
https://www.owasp.org/index.php/Source_Code_Analysis_Tools -> https://owasp.org/www-community/Source_Code_Analysis_Tools

https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project -> https://owasp.org/www-project-zap/

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
/close 
again
