### ISSUE TITLE
anchor doesn't work in ko/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by jmyung** [kubernetes/website#20368]
**This is a Bug Report**

**Problem:**
anchor doesn't work such as `https://kubernetes.io/ko/docs/concepts/policy/pod-security-policy/#privileged`

**Proposed Solution:**
Correct the link

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/policy/pod-security-policy/

**Comment by butuzov** [comment]
to any Korean localization team member issue only in local anchor in `content/ko/docs/concepts/policy/pod-security-policy.md` 
`#priveliged` sppose to be `#특권을-가진` as far as I understand.

**Comment by jmyung** [comment]
@butuzov Thanks, let me do this.
