### ISSUE TITLE
Content issue with 'hello-minikube' tutorial

### ISSUE THREAD

**Issue by techmaniack** [kubernetes/website#20378]
**This is a Bug Report**

**Problem:** The tutorial does not cover all the objectives.

- [x] Deploy a hello world application to Minikube.
- [x] Run the app.
- [ ] View application logs.

**Proposed Solution:** Add a sub-section in the tutorial that covers `View application logs` objective. 

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube

The [Enable addons](https://kubernetes.io/docs/tutorials/hello-minikube/#enable-addons) sub-section seems to be out of place, should it have been about the logviewer addon rather than metrics-server addon?

**Comment by Kartik494** [comment]
Hi @techmaniack Given is an example of how we can enable an add on like metrics-server.You can do the same for logviewer also if you want.
Thanks

**Comment by techmaniack** [comment]
Hi @Kartik494 

Thanks for replying. This issue is not about the addon example, I have edited the original issue with more details.

**Comment by RA489** [comment]
@techmaniack I recommend, trying our quick start guide https://minikube.sigs.k8s.io/docs/start/

**Comment by techmaniack** [comment]
@RA489 I have already gone through the material that you have shared. 
Is the minikube content on Kubernetes (kubernetes.io) website no longer being maintained or going to be deprecated?

**Comment by RA489** [comment]
@techmaniack Minikube has removed most of the dual hosted content from (kubernetes.io) and has its separate doc here https://minikube.sigs.k8s.io/docs/start/
