### ISSUE TITLE
Running locally error: plain HTML documents not supported

### ISSUE THREAD

**Issue by senique** [kubernetes/website#20370]
**This is a Bug Report**

Running the website locally using `make serve`

_~$make serve
hugo server --buildFuture
Built in 2309 ms  
Error: Error building site: ".../website/content/ja/includes/user-guide-migration-notice.md:1:1": plain HTML documents not supported
make: *** [serve] Error 255_  

**Problem:**
hugo does not support plain HTML documents.
**Proposed Solution:**
Convert  HTML content to Markdown in these documents:
- content/de/includes/user-guide-migration-notice.md
- content/en/includes/user-guide-migration-notice.md
- content/fr/includes/user-guide-migration-notice.md
- content/ja/includes/user-guide-migration-notice.md
- content/zh/includes/user-guide-migration-notice.md

**Page to Update:**

**Comment by tengqm** [comment]
No longer an issue since the related contents are removed.
/close
