### ISSUE TITLE
"Inheriting DNS from the node" section is missing in "Customizing DNS Service" page

### ISSUE THREAD

**Issue by jmlrt** [kubernetes/website#20384]
**This is a Bug Report**

**Problem:** `/docs/tasks/administer-cluster/dns-custom-nameservers/#inheriting-dns-from-the-node` link on [dns-pod-service.md](https://github.com/kubernetes/website/blame/master/content/en/docs/concepts/services-networking/dns-pod-service.md#L161) is broken.

"Inheriting DNS from the node" section is missing in [dns-custom-nameservers.md](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md) page.

It seems it was removed in https://github.com/kubernetes/website/commit/045cbb1f57fdf1c8039a7d419454a1844e21dd04

**Proposed Solution:**

**Page to Update:**
https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md

**Comment by sftim** [comment]
I think I'd fix this by removing or amending the page that links to https://k8s.io/docs/tasks/administer-cluster/dns-custom-nameservers/

/kind bug
/language en
/priority backlog

Thanks for reporting this @jmlrt
