### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

### ISSUE THREAD

**Issue by ariksa** [kubernetes/website#20414]
**This is a Bug Report**

**Problem:**
When executing:
`kubectl run --generator=run-pod/v1 -it --rm load-generator --image=busybox /bin/sh`
I get the following warning:
`Flag --generator has been deprecated, has no effect and will be removed in the future.`

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough

**Kubernetes Version:**
v1.18.1

**Comment by tengqm** [comment]
Done. Thanks. @viniciusbds 
/close
