### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by heigumjo** [kubernetes/website#20412]
**This is a Bug Report**

The command to link completions to the alias should be compinit and not complete

**Problem:**
The command
echo 'complete -F __start_kubectl k' >>\~/.zshrc
is not correct for macOS (at least)
**Proposed Solution:**
It should be
echo 'compinit -F __start_kubectl k' >>\~/.zshrc
**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sftim** [comment]
Thanks for reporting this. (I haven't validated the report as yet).
/sig cli
/language en

**Comment by tengqm** [comment]
No. The current instructions are correct.
/close
