### ISSUE TITLE
Add area/web-development label

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20428]
**This is a Feature Request**

**What would you like to be added**
If this sounds like a good idea: [add a new label](https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.md#how-do-i-add-a-new-label), `area/visual-style`, for [k/website](https://github.com/kubernetes/website). Use this new label to identify issues and PRs that are relevant to visual style.

For example:
- adding images to existing content
- CSS changes relating to visual rendering
- shortcode revisions that change how pages appear but not the content shown
- diagram styling work

**Why is this needed**
I think a label like this could help broaden the pool of people willing to contribute to SIG Docs and to the website: it helps people who want to do that kind of work more easily find the tasks they might like to do.

**Comments**
Please feel free to discuss!

**Comment by sftim** [comment]
An example of an issue I'd label (manually): https://github.com/kubernetes/website/issues/19474

**Comment by celestehorgan** [comment]
Would `kind/website` maybe be a better catch-all? (I say, as I create 10's of JS file cleanup issues)

**Comment by sftim** [comment]
@celestehorgan this whole _repository_ is for the website.

`area/web-development` perhaps?

I suggest _area_ because you can have a bug issue and a feature issue that both call for JavaScript skills (and aren't about Kubernetes knowledge).

**Comment by celestehorgan** [comment]
@sftim that sounds good to me. We'll have to do a mighty amount of re-categorizing issues when this comes in, but it'll be worth it. 

As a side note, something to bring up in our next weekly: do we need governance/OWNERs for layout/CSS/JS files going forward? (To prevent us from getting into deeper CSS tangles?)

**Comment by sftim** [comment]
OWNERS for layout and styles would be nice, even if it's only a partial improvement.

**Comment by celestehorgan** [comment]
eyyyyyyyyyyy!

/close
