### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by vijaygharge** [kubernetes/website#20421]
**This is a Bug Report**

Need to rectify comment wherein "cluster" is mentioned instead of "user"

**Problem:**
Comment section reads -
# add a new cluster to your kubeconf that supports basic auth; whereas command points to new user addition

**Proposed Solution:**

Comment shall be -

"# add a new user to your kubeconf that supports basic auth"

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration

**Comment by sftim** [comment]
Thanks for spotting this @vijaygharge 

The command you've mentioned lets you tell `kubectl` about new user identity (new to your `.kubeconfig` anyway), including details on how to authenticate as that user. As you say, it doesn't configure `kubectl` etc to know about a new cluster.

This looks worth fixing.
/help
/language en
/kind bug
/priority important-longterm

**Comment by davivcgarcia** [comment]
Sorry for jumping in, I'm gonna update the Issue labels to reflect the work on linked PR.

/remove-help
/assign @gosoon
