### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by vetbijaya** [kubernetes/website#20435]
**This is a Bug Report**

**Problem:**
user@user-VirtualBox:~$ sudo minikube start --vm-driver=virtualbox
! minikube v1.9.2 on Ubuntu 18.04
! Both driver=none and vm-driver=virtualbox have been set.
 Since vm-driver is deprecated, minikube will default to driver=none.
   If vm-driver is set in the global config, please run "minikube config unset vm-driver" to resolve this warning.

* Using the none driver based on user configuration
* Starting control plane node  in cluster minikube
* Running on localhost (CPUs=3, Memory=5841MB, Disk=15052MB) ...
* OS release is Ubuntu 18.04.4 LTS
* Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
! This bare metal machine is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

$ minikube version
minikube version: v1.9.2

$ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

OS: $ uname -a
Linuxuser-VirtualBox 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I am trying to install and configure kubectl and Minikube in a VPN and inside company proxy

**Comment by prasadkatti** [comment]
Hi @vetbijaya. I would suggest you move this issue to https://github.com/kubernetes/minikube. Additionally, look at the instructions at https://minikube.sigs.k8s.io/docs/start/ to install minikube.

The `--vm-driver` has been deprecated. Try -
`sudo minikube start --driver=virtualbox`

**Comment by prasadkatti** [comment]
Looks like you are not able to access https://k8s.gcr.io, you will need to configure a proxy mentioned in the output of `minikube start`.

**Comment by vetbijaya** [comment]
I was able to run minikube using sudo minikube start --driver=virtualbox now but it keeps on crashing the Ubuntu while trying to start. Can you help me how to resolve that? Is there any known issue with minikube configuration hosted on Ubuntu on Virtual Box?
Regarding the proxy configuration, I already have set that in environment variables.

**Comment by RA489** [comment]
@vetbijaya  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.

**Comment by vetbijaya** [comment]
@RA489 I already solved the above issue. Thank you!
