### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/kubernetes-basics/expose/expose-intro/

### ISSUE THREAD

**Issue by TomorJM** [kubernetes/website#20445]
**This is a Bug Report**

**Problem:**

not a Chinese version(It should be)

**Proposed Solution:**

translation

**Page to Update:**

https://kubernetes.io/zh/docs/tutorials/kubernetes-basics/expose/expose-intro/

**Comment by tengqm** [comment]
@TomorJM Still working on this?

**Comment by TomorJM** [comment]
> @TomorJM Still working on this?

yeah, and sorry for the delay
i will commit a PR this week

**Comment by tengqm** [comment]
/close
done.
