### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by HankTheCrank** [kubernetes/website#20447]
**This is a Bug Report**

The script for the Kubernetes repository seems to have an error in the repo URL

**Problem:**
I try and install the Kubernetes components for an etcd server, the install fails with:
[Errno 14] HTTPS Error 404 - Not Found

**Proposed Solution:**
In the script change:
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
to:
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

I got the replacement version from:
https://kubernetes.io/docs/tasks/tools/install-kubectl/

1.8

I tried "echo $basearch" and it comes back empty. I am using Centos 7.

**Comment by neolit123** [comment]
please see this existing issue:
https://github.com/kubernetes/website/issues/20279

and the PR to merge a fix:
https://github.com/kubernetes/website/pull/20291

/close
