### ISSUE TITLE
Website build turns plain "--" into "–" in paragraphs, and we use plain "--" in paragraphs when describing flags

### ISSUE THREAD

**Issue by gkop** [kubernetes/website#2045]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

(unfortunately I don't believe GitHub lets you link to a line of a markdown file)

Compare the third paragraph of the [source](https://github.com/kubernetes/kubernetes.github.io/blob/67be6311ee5b05a2935b82e5bb017ef760b62b3e/docs/user-guide/kubectl/kubectl_delete.md#synopsis) with the [built site](http://kubernetes.io/docs/user-guide/kubectl/kubectl_delete/) .

This stinks because you can copy and paste the flag and not immediately see why it doesn't work.

**Proposed Solution:**

We should either validate the absence of flag-like patterns in plain paragraph text in the markdown, or configure the website build process to preserve "--" in such patterns.

**Comment by tengqm** [comment]
Is this still an issue?

**Comment by gkop** [comment]
I could not replicate just now.
