### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/common-labels/

### ISSUE THREAD

**Issue by fjammes** [kubernetes/website#20456]
**This is a Bug Report**

**Problem:** Information about recommended labels for nodes is missing.

**Proposed Solution:** Add information about recommended label for nodes (labels starting with node.kubernetes.io/xxx)

**Page to Update:**
https://kubernetes.io/concepts/overview/working-with-objects/common-labels/

**Comment by tengqm** [comment]
/sig node

AFAICT, labels for nodes are usually used internally by kubernetes control plane, especially those `*.kubernetes.io/*` ones. I may be wrong though.
