### ISSUE TITLE
Add Hugo in a container info to website contributing guide

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#20467]
Add content to [k/website contribute](https://kubernetes.io/docs/contribute/) covering running Hugo in a container to serve docs like:

---

## Running the website locally using Docker

The recommended way to run the Kubernetes website locally is to run a specialized [Docker](https://docker.com) image that includes the [Hugo](https://gohugo.io) static website generator.

> If you are running on Windows, you'll need a few more tools which you can install with [Chocolatey](https://chocolatey.org). `choco install make`

> If you'd prefer to run the website locally without Docker, see [Running the website locally using Hugo](#running-the-website-locally-using-hugo) below.

If you have Docker [up and running](https://www.docker.com/get-started), build the `kubernetes-hugo` Docker image locally:

```bash
make docker-image
```

Once the image has been built, you can run the website locally:

```bash
make docker-serve
```

Open up your browser to http://localhost:1313 to view the website. As you make changes to the source files, Hugo updates the website and forces a browser refresh.

---

More info: https://github.com/kubernetes/website/pull/20446#discussion_r411227205
/cc @sftim 
/good-first-issue
/language en

**Comment by nevermyuk** [comment]
@jimangel Can I have some clarity on this? 
The instructions are repeated in
[Preview Locally](https://kubernetes.io/docs/contribute/new-content/new-content/#preview-locally)

**Comment by sftim** [comment]
The only shortcoming I see for https://kubernetes.io/docs/contribute/new-content/new-content/#preview-locally is that the URL and the section title imply that it's a guide for adding new pages, rather than (for example) if your contribution is to improve the docs by deleting something.

I think this issue is OK to close.
