### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by Deep-sys-star** [kubernetes/website#20469]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

after setup the wordpress on kubernetes it doesnt load on browser

**Comment by Kartik494** [comment]
@Deep-sys-star Hi could you elaborate more on this, which type of error in this

**Comment by tengqm** [comment]
No response from the author for more than 1 month. Closing.
/close
