### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by conradwt** [kubernetes/website#2046]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**

The interactive screen should be the width of the browsers viewport because it's hard to read command output.

**Proposed Solution:**

Make the interactive screen as wide as the browser's viewport or wide enough to properly layout the displayed content.

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thank you for your feedback on this. As recommended we updated the layout to give the terminal more space.

/close
