### ISSUE TITLE
Wrong title for “Topologi Service (_Service Topology_)” (bahasa Indonesia)

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20478]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/id/docs/concepts/services-networking/service-topology/ has the title
_Topologi Service (\_Service Topology\_)_.

HTML doesn't let you use formatting in titles, so Hugo / CommonMark also don't let you use Markdown formatting in page titles.

**Proposed Solution:**
Take out the underscores.

**Page to Update:**
https://kubernetes.io/id/docs/concepts/services-networking/service-topology/

/good-first-issue
(even if you don't speak bahasa Indonesia!)
/language id
/kind bug
/priority backlog

**Comment by ShivamGoyal1899** [comment]
#20504 fixed this. It should be closed.

**Comment by sftim** [comment]
/close
Fixed in #20504 
Thanks @ShivamGoyal1899
