### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by psingleton** [kubernetes/website#20476]
Hi,

Following the instructions on the page to install the dashboard I am getting the below 500 error:

error: unable to read URL "https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta8/aio/deploy/recommended.yaml", server reported 500 Internal Server Error, status code=500

**Comment by tengqm** [comment]
I believe it was cause by a bad weather that day. Pls try if things work now and reopen this if the server still says 500.
/close
