### ISSUE TITLE
Better formatting for multi-line field comments in API reference documentation

### ISSUE THREAD

**Issue by JamesLaverack** [kubernetes/website#20474]
**This is a Feature Request**

**What would you like to be added**

Some API fields have multi-line comments, some with formatting. For example the field `fsGroup` in `corev1.PodSecurityContext` has this comment in the [Go source](https://github.com/kubernetes/api/blob/kubernetes-1.18.1/core/v1/types.go#L3188):

```go
// A special supplemental group that applies to all containers in a pod.
// Some volume types allow the Kubelet to change the ownership of that volume
// to be owned by the pod:
//
// 1. The owning GID will be the FSGroup
// 2. The setgid bit is set (new files created in the volume will be owned by FSGroup)
// 3. The permission bits are OR'd with rw-rw----
//
// If unset, the Kubelet will not modify the ownership and permissions of any volume.
// +optional
FSGroup *int64 `json:"fsGroup,omitempty" protobuf:"varint,5,opt,name=fsGroup"`
```

In the [HTML reference documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podsecuritycontext-v1-core), this is rendered as a single-line:

```html
<tr>
  <td>
    <code>fsGroup</code>
    <br>
    <i>integer</i>
  </td>
  <td>A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to change the ownership of that volume to be owned by the pod:  1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR'd with rw-rw----  If unset, the Kubelet will not modify the ownership and permissions of any volume.</td>
</tr>
```

I would like to change the formatting of multi-line comments like this in the rendered documentation.

**Why is this needed**

Much of the author's original intent in this formatting is obfuscated in the HTML reference, and the resulting single line does not "scan" very well. Resulting in harder to understand documentation. Especially where a feature or side effect is complex enough to warrant a longer description.

**Comments**

- It was [suggested on Slack](https://kubernetes.slack.com/archives/C1J0BPD2M/p1587475302262700?thread_ts=1587410628.243500&cid=C1J0BPD2M) by Qiming Teng that newlines could be translated in HTML to `<br/>` tags to preserve the new lines.
- In cases like `fsGroup` in particular, the author has used an ordered list. *Ideally* this could be translated into a HTML ordered list for the best formatting. However I'm unsure of the implications of attempting to do this on text comments.

**Comment by sftim** [comment]
Does Golang support Markdown comments (like [in Rust](https://doc.rust-lang.org/stable/rust-by-example/meta/doc.html))?

**Comment by tengqm** [comment]
@sftim There are places where the comments are using inline markdown syntax such as links and backtiqs.

**Comment by sftim** [comment]
Sure; really I'm asking if that's a _de facto_ thing or documented and _de jure_. (If it's documented like in Rust then it's easy to put it through a machine and expect ~consistent~ documented results).

**Comment by JamesLaverack** [comment]
I don't believe there is any particular Go language policy about using Markdown in comments, although I could well be wrong. The [Go wiki](https://github.com/golang/go/wiki/Comments) is silent on it, and [GoDoc](https://godoc.org/k8s.io/api/core/v1) doesn't seem to render field comments at all.

**Comment by JamesLaverack** [comment]
I looked for other examples. It seems that where there is formatting it is, by accident or design, mostly Markdown. But I haven't searched exhaustively so I wouldn't be surprised if you could find counter-examples.

- `maxSkew` in `corev1.TopologySpreadConstraint` uses an unordered list and a table. Which renders about as well as you might expect:

  ```go
  // MaxSkew describes the degree to which pods may be unevenly distributed.
  // It's the maximum permitted difference between the number of matching pods in
  // any two topology domains of a given topology type.
  // For example, in a 3-zone cluster, MaxSkew is set to 1, and pods with the same
  // labelSelector spread as 1/1/0:
  // +-------+-------+-------+
  // | zone1 | zone2 | zone3 |
  // +-------+-------+-------+
  // |   P   |   P   |       |
  // +-------+-------+-------+
  // - if MaxSkew is 1, incoming pod can only be scheduled to zone3 to become 1/1/1;
  // scheduling it onto zone1(zone2) would make the ActualSkew(2-0) on zone1(zone2)
  // violate MaxSkew(1).
  // - if MaxSkew is 2, incoming pod can be scheduled onto any zone.
  // It's a required field. Default value is 1 and 0 is not allowed.
  MaxSkew int32 `json:"maxSkew" protobuf:"varint,1,opt,name=maxSkew"`
  ```
  
  > MaxSkew describes the degree to which pods may be unevenly distributed. It's the maximum permitted difference between the number of matching pods in any two topology domains of a given topology type. For example, in a 3-zone cluster, MaxSkew is set to 1, and pods with the same labelSelector spread as 1/1/0: | zone1 | zone2 | zone3 | |   P   |   P   |       | - if MaxSkew is 1, incoming pod can only be scheduled to zone3 to become 1/1/1; scheduling it onto zone1(zone2) would make the ActualSkew(2-0) on zone1(zone2) violate MaxSkew(1). - if MaxSkew is 2, incoming pod can be scheduled onto any zone. It's a required field. Default value is 1 and 0 is not allowed.

- `matchPolicy` in `admissionregistrationv1.MutatingWebhook` uses a definition list

  ```go
  // matchPolicy defines how the "rules" list is used to match incoming requests.
	// Allowed values are "Exact" or "Equivalent".
	//
	// - Exact: match a request only if it exactly matches a specified rule.
	// For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1,
	// but "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`,
	// a request to apps/v1beta1 or extensions/v1beta1 would not be sent to the webhook.
	//
	// - Equivalent: match a request if modifies a resource listed in rules, even via another API group or version.
	// For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1,
	// and "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`,
	// a request to apps/v1beta1 or extensions/v1beta1 would be converted to apps/v1 and sent to the webhook.
	//
	// Defaults to "Equivalent"
	// +optional
	MatchPolicy *MatchPolicyType `json:"matchPolicy,omitempty" protobuf:"bytes,9,opt,name=matchPolicy,casttype=MatchPolicyType"`
  ```
- `namespaceSelector`, also in `admissionregistrationv1.MutatingWebhook` uses a couple of code bloks for example JSON. Interestingly it doesn't use the triple-backtick code block syntax.
  
  ```go
  // NamespaceSelector decides whether to run the webhook on an object based
	// on whether the namespace for that object matches the selector. If the
	// object itself is a namespace, the matching is performed on
	// object.metadata.labels. If the object is another cluster scoped resource,
	// it never skips the webhook.
	//
	// For example, to run the webhook on any objects whose namespace is not
	// associated with "runlevel" of "0" or "1";  you will set the selector as
	// follows:
	// "namespaceSelector": {
	//   "matchExpressions": [
	//     {
	//       "key": "runlevel",
	//       "operator": "NotIn",
	//       "values": [
	//         "0",
	//         "1"
	//       ]
	//     }
	//   ]
	// }
	//
	// If instead you want to only run the webhook on any objects whose
	// namespace is associated with the "environment" of "prod" or "staging";
	// you will set the selector as follows:
	// "namespaceSelector": {
	//   "matchExpressions": [
	//     {
	//       "key": "environment",
	//       "operator": "In",
	//       "values": [
	//         "prod",
	//         "staging"
	//       ]
	//     }
	//   ]
	// }
	//
	// See
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
	// for more examples of label selectors.
	//
	// Default to the empty LabelSelector, which matches everything.
	// +optional
	NamespaceSelector *metav1.LabelSelector `json:"namespaceSelector,omitempty" protobuf:"bytes,5,opt,name=namespaceSelector"`
  ```
- Various types use single backticks for defined names (e.g., various fields in `admissionregistrationv1.ServiceReference`.

**Comment by tengqm** [comment]
@JamesLaverack Thanks for the detailed examples. I have filed [an issue](https://github.com/kubernetes-sigs/reference-docs/issues/151) for this. However, I don't think there is a smarter parser which can detect the code snippets in the sample comments above or the sample  table.
Yes, the comment looks like markdown syntax. But when you feed them into a markdown parser, you will not get the desired output, because the table is not good. It should be:

```
MaxSkew describes the degree to which pods may be unevenly distributed.
It's the maximum permitted difference between the number of matching pods in
any two topology domains of a given topology type.
For example, in a 3-zone cluster, MaxSkew is set to 1, and pods with the same
labelSelector spread as 1/1/0:

| zone1 | zone2 | zone3 |
|-------|-------|-------|
|   P   |   P   |       |

- if MaxSkew is 1, incoming pod can only be scheduled to zone3 to become 1/1/1;
  scheduling it onto zone1(zone2) would make the ActualSkew(2-0) on zone1(zone2)
  violate MaxSkew(1).
- if MaxSkew is 2, incoming pod can be scheduled onto any zone.
  It's a required field. Default value is 1 and 0 is not allowed.
```

Note how an empty line is inserted before the table and another line inserted after the table. Also note that the unordered list are properly indented to avoid breaking markdown.

For the code snippet to be "properly" rendered, the comment must be changed as well. E.g.

```
  // If instead you want to only run the webhook on any objects whose
  // namespace is associated with the "environment" of "prod" or "staging";
  // you will set the selector as follows:
  //
  // ```
  // "namespaceSelector": {
  //   "matchExpressions": [
  //     {
  //       "key": "environment",
  //       "operator": "In",
  //       "values": [
  //         "prod",
  //         "staging"
  //       ]
  //     }
  //   ]
  // }
  // ```
```

**Comment by JamesLaverack** [comment]
> Yes, the comment looks like markdown syntax. But when you feed them into a markdown parser, you will not get the desired output […]

Ah I see. So it's _kind of_ Markdown.

Looks like that "just" applying a Markdown parser isn't going to cut it. I took a look at [the issue](https://github.com/kubernetes-sigs/reference-docs/issues/151) you raised and at least parsing single-backtick content into a `<code>` block seems reasonable.

Instead of trying to figure out how to parse the not-quite-markdown, could we change the comments to be valid Markdown? There's a whole host of questions I can think of as a result of doing that though:

- Do we expect that future authors will use Markdown, and keep their comments, where they do use 'advanced' formatting, as valid Markdown?
- Is such a change big enough in scope it would require a wider community discussion?
- As @sftim mentioned above, is there any Go standard here?

Of course, for now just single backticks into `<code>` and preserving paragraphs is probably an improvement. Even if further thought about tables and multi-line code blocks is needed.

**Comment by tengqm** [comment]
@JamesLaverack I'd assume a change like we suggested is big enough that warrants a community wide discussion, but I'm not aware of any Go standard on this.

**Comment by tengqm** [comment]
Some further investigation into this ... The comment format has been lost when we got the API definition JSON file. Take the `maxSkew` in `corev1.TopologySpreadConstraint` as an example, the resulted OpenAPI JSON for it is something like this:

```json
"maxSkew": {
          "description": "MaxSkew describes the degree to which pods may be unevenly distributed. It's the maximum permitted difference between the number of matching pods in any two topology domains of a given topology type. For example, in a 3-zone cluster, MaxSkew is set to 1, and pods with the same labelSelector spread as 1/1/0: | zone1 | zone2 | zone3 | |   P   |   P   |       | - if MaxSkew is 1, incoming pod can only be scheduled to zone3 to become 1/1/1; scheduling it onto zone1(zone2) would make the ActualSkew(2-0) on zone1(zone2) violate MaxSkew(1). - if MaxSkew is 2, incoming pod can be scheduled onto any zone. It's a required field. Default value is 1 and 0 is not allowed.",
          "format": "int32",
          "type": "integer"
        }
```

The multi-lined comment has been been merged in the API spec (https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json).

Sigh ...

**Comment by JamesLaverack** [comment]
So the problem is in the OpenAPI generation code? To make sure I understand fully, the current process is:

1. An OpenAPI JSON file is generated from the Go source code
2. The website HTML is generated from the OpenAPI JSON file.

Are there other steps in there?

**Comment by tengqm** [comment]
@JamesLaverack No other steps.

**Comment by tengqm** [comment]
There is nothing left to do from website's perspective. Related enhancement request has been logged into the reference-tools project.
/close
