### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by smirnov-mi** [kubernetes/website#20497]
**This is a Bug Report for documentation page**

**Problem:**

Hi guys, I only see kubeadm-backup-manifests folders in the /etc/kubernetes/tmp
I don't use external etcd:

master-node# ls -la /var/lib/etcd/member/snap/
total 53944
drwx------ 2 root root     4096 Apr 22 10:55 .
drwx------ 4 root root     4096 Apr 20 16:35 ..
-rw-r--r-- 1 root root    23680 Apr 22 04:18 00000000000000b2-0000000006484b00.snap
-rw-r--r-- 1 root root    23680 Apr 22 05:57 00000000000000b2-000000000649d1a1.snap
-rw-r--r-- 1 root root    23680 Apr 22 07:36 00000000000000b2-00000000064b5842.snap
-rw-r--r-- 1 root root    23680 Apr 22 09:15 00000000000000b2-00000000064cdee3.snap
-rw-r--r-- 1 root root    23680 Apr 22 10:54 00000000000000b2-00000000064e6584.snap

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#recovering-from-a-failure-state

1.18.2 - updated from 1.17.2, 1.16.x, 

Just wondering if the documentation is not complete, or my setup is wrong.
Thanks

**Comment by neolit123** [comment]
> Hi guys, I only see kubeadm-backup-manifests folders in the /etc/kubernetes/tmp
I don't use external etcd:

hi, i don't understand your comment. can you please clarify?

> During upgrade kubeadm writes the following backup folders under /etc/kubernetes/tmp: - kubeadm-backup-etcd-<date>-<time> - kubeadm-backup-manifests-<date>-<time>

the etcd backup folder should be there if you it matches the docs explanation:

> kubeadm-backup-etcd contains a backup of the local etcd member data for this control-plane Node. In case of an etcd upgrade failure and if the automatic rollback does not work, the contents of this folder can be manually restored in /var/lib/etcd. In case external etcd is used this backup folder will be empty.

for the manifest backup folder:

> kubeadm-backup-manifests contains a backup of the static Pod manifest files for this control-plane Node. In case of a upgrade failure and if the automatic rollback does not work, the contents of this folder can be manually restored in /etc/kubernetes/manifests. If for some reason there is no difference between a pre-upgrade and post-upgrade manifest file for a certain component, a backup file for it will not be written

/sig cluster-lifecycle
/triage support

**Comment by smirnov-mi** [comment]
The document stays :  

> During upgrade kubeadm writes the following backup folders under /etc/kubernetes/tmp: - kubeadm-backup-etcd-<date>-<time> - kubeadm-backup-manifests-<date>-<time>


So I expected to see two types of folders in /etc/kubernetes/tmp :
kubeadm-backup-manifests* 
and 
kubeadm-backup-etcd*

I only see 
kubeadm-backup-manifests*

**Comment by neolit123** [comment]
i think we have a hidden detail where if you have a HA control plane (mutli-master) the etcd backup folder will be missing.

do you have HA?

**Comment by smirnov-mi** [comment]
Yes, I do. That's what I was thinking about.
A small hint in the documentation would be useful. Thank you!

**Comment by neolit123** [comment]
we planned to have this hint originally but though that users will get more confused if it was there.
/assign

**Comment by smirnov-mi** [comment]
ha ha., then you got exactly one person who decided to read (and read up to this part!) and had exactly this setup :-)

**Comment by neolit123** [comment]
@smirnov-mi 

> i think we have a hidden detail where if you have a HA control plane (mutli-master) the etcd backup folder will be missing.

i realized that we changed that for 1.18+:
https://github.com/kubernetes/kubernetes/commit/72559ec6933a54225f5116d016fd7927762c1878

so now all control-plane nodes in a stacked-etcd HA setup (not external etcd) would get etcd backup.

```
# on the first CP node
kubeadm upgrade apply -f v1.18.0
ls -l /etc/kuberentes/tmp
drwx------ 3 root root 4096 Apr 23 16:56 kubeadm-backup-etcd-2020-04-23-16-56-26
drwx------ 2 root root 4096 Apr 23 16:56 kubeadm-backup-manifests-2020-04-23-16-56-26

# on another CP node
kubeadm upgrade node
ls -l /etc/kuberentes/tmp
drwx------ 3 root root 4096 Apr 23 17:06 kubeadm-backup-etcd-2020-04-23-17-06-56
drwx------ 2 root root 4096 Apr 23 17:06 kubeadm-backup-manifests-2020-04-23-17-06-56

# check nodes
kubectl get no -A --kubeconfig=/etc/kubernetes/admin.conf 
NAME                   STATUS   ROLES    AGE     VERSION
kind-control-plane-1   Ready    master   15m     v1.18.0
kind-control-plane-2   Ready    master   12m     v1.18.0
kind-control-plane-3   Ready    master   9m32s   v1.18.0
```

as you can see the backup folder is created for me in a stacked-etcd HA setup.
also note that i checked the code and a backup should be created even if your etcd version between kubeadm upgrades is the same and the actual etcd.yaml manifest upgrade is skipped.

- can you provide more detail about the exact patch versions you are upgrading from-to?
- are you sure this happens with v1.18+?
- does this happen for both `upgrade apply` and `upgrade node` on CP nodes?
- do you have an external process that could have deleted the folder?

/priority awaiting-more-evidence

**Comment by tengqm** [comment]
@smirnov-mi Can we close this issue now?

**Comment by smirnov-mi** [comment]
sure, can be closed, if the documentation reflects the current state now.

**Comment by tengqm** [comment]
@smirnov-mi Thanks for the prompt reply.
/close
