### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/assign-pod-node/

### ISSUE THREAD

**Issue by robbiezhang** [kubernetes/website#20491]
The following terms are wrong

> If you specify multiple nodeSelectorTerms associated with nodeAffinity types, then the pod can be scheduled onto a node only if all nodeSelectorTerms can be satisfied.
> 
> If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node if one of the matchExpressions is satisfied.

It should be 

> If you specify multiple nodeSelectorTerms associated with nodeAffinity types, then the pod can be scheduled onto a node **if one of the** nodeSelectorTerms can be satisfied.
> 
> If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node **only if all** matchExpressions is satisfied.

**Comment by Colstuwjx** [comment]
After dive into code, it's implemented by a scheduler plugin, with func [nodeMatchesNodeSelectorTerms](https://github.com/kubernetes/kubernetes/blob/38173d586ac5cbc3e6fb83b704081574fb4d7022/pkg/scheduler/framework/plugins/helper/node_affinity.go#L65), and it called [MatchNodeSelectorTerms(https://github.com/kubernetes/kubernetes/blob/38173d586ac5cbc3e6fb83b704081574fb4d7022/pkg/apis/core/v1/helper/helpers.go#L275) to check the condition, and it's ORed.

And the matchExpressions associated with nodeSelectorTerms are composed by func [NodeSelectorRequirementsAsSelector](https://github.com/kubernetes/kubernetes/blob/38173d586ac5cbc3e6fb83b704081574fb4d7022/pkg/apis/core/v1/helper/helpers.go#L287) and finally checked as label selector.

As a result, I think you're right.

/kind documentation
/language en

**Comment by tengqm** [comment]
Done.
/close
