### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by GFRPIG** [kubernetes/website#20527]
hello！there is a possible mistake at "Joining your nodes" section：
![1](https://user-images.githubusercontent.com/49465580/80110964-deaff300-85b1-11ea-9a5a-7f83c414d726.PNG)
![2](https://user-images.githubusercontent.com/49465580/80111003-e7a0c480-85b1-11ea-84dc-f9bda3e5876f.PNG)
have you wrongly written "port" to "ip" ?

**Comment by neolit123** [comment]
hi, yes this seems wrong.
do you wish to send a PR to fix it?
/sig cluster-lifecycle
/help

**Comment by GFRPIG** [comment]
sorry…i just find this mistake during learning, but i don't know how to fix it...(i am a novice to github and k8s…)

**Comment by GFRPIG** [comment]
sorry…i just find this mistake during learning, but i don't know how to fix it...(i am a novice to github and k8s…) @neolit123

**Comment by prasadkatti** [comment]
@neolit123 - I would like to help with such doc issues for sig/cluster-lifecycle.

**Comment by neolit123** [comment]
thanks @prasadkatti i can ping on new tickets. you can also watch the sig/cluster-lifecycle label in this repo.
