### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/create-external-load-balancer/

### ISSUE THREAD

**Issue by Devang1991** [kubernetes/website#20536]
How to assign DNS mapping to loadbalancer in Kubernetes

**Comment by nevermyuk** [comment]
This is not the place to ask questions.
For your questions or relative issue please refer to [this](https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/#help-my-question-isn-t-covered-i-need-help-now)

/triage support

**Comment by tengqm** [comment]
There is no load balancer in Kubernetes. You have to check with your cloud vendor.

/close
