### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by GreenhazelStudio** [kubernetes/website#20540]
Under section header "Source IP for Services with Type=ClusterIP" (right about section header "Source IP for Services with Type=NodePort") there is comment that I believe is slightly misleading.  It reads...

> Replace 10.0.170.92 with the Pod's IPv4 address

...however I believe it should read...

> Replace 10.0.170.92 with the ClusterIP address

...provided I understood the material correctly, of course.

**Comment by tengqm** [comment]
No. `10.0.170.92` is already the ClusterIP. The Pod's IPv4 address, in that example, is `10.244.3.8`. The command comment wanted to be accurate so that users know they will use the Pod IP rather than what is given in the example.

/close
