### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/jsonpath/ documentation not accurate with jsonpath support

### ISSUE THREAD

**Issue by gokussx4** [kubernetes/website#20545]
**This is a Bug Report**

**Problem:**
The article states jsonpath support but does not indicate it is _limited_. For example, =~ does not work so there isn't regex support. 

**Proposed Solution:**
Please document what is and is not supported since it is not a full version of jsonpath. Also link github issue that states full support is desired for tracking purposes of those wanting the full jsonpath support.

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/jsonpath/

Kubernetes Version: 1.16.6

Additional Information:
https://github.com/kubernetes/kubernetes/issues/72220 states full jsonpath support is not available.

**Comment by liggitt** [comment]
Do you have a reference for the jsonpath standard that describes using =~ with regular expressions? I am unable to find one.

**Comment by tengqm** [comment]
close for now. We can always revisit this when we have a standard way of expressing regex support.
/close
