### ISSUE TITLE
Improvement for k8s.io/docs/tasks/manage-kubernetes-objects/imperative-command/

### ISSUE THREAD

**Issue by Kanshar** [kubernetes/website#20557]
The page could also mention how to create a pod using imperative commands.
```
kubectl run --generator=run-pod/v1 nginx-pod —image nginx:alpine
```

**Comment by tengqm** [comment]
the generators are all deprecated along with all flags unrelated to creating Pods. Let's refrain from confusing users at this stage.

/close
