### ISSUE TITLE
Issue with k8s.io/docs/setup/best-practices/cluster-large/

### ISSUE THREAD

**Issue by shay-berman** [kubernetes/website#20556]
**This is a Bug Report**

**Problem:**
Missing max limit of k8s servces object in the documentation.

**Proposed Solution:**
when specify number of nodes, also can you specify the limit (if any) on number of k8s services, deployment objects?

**Page to Update:**
https://kubernetes.io/...

**Comment by Surya2709** [comment]
/language en
/sig scalability
that solves the issue although Mr.tengqn mentioned it before
