### ISSUE TITLE
improve translation of https://kubernetes.io/zh/docs/concepts/workloads/pods/disruptions/

### ISSUE THREAD

**Issue by pigletfly** [kubernetes/website#20580]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/zh/docs/concepts/workloads/pods/disruptions/

disruption 翻译为干扰是否正确，是否需要要统一为中断？

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/zh/docs/concepts/workloads/pods/disruptions/

**Comment by tengqm** [comment]
disruption -> 干扰
interruption -> 中断

**Comment by pigletfly** [comment]
ok
