### ISSUE TITLE
startupProbe needs featureGate, Issue with k8s.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

### ISSUE THREAD

**Issue by SimonHeimberg** [kubernetes/website#20581]
**This is a Bug Report**

**Problem:** startup probe does not work when following the example on the page

Reason: according to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features StartupProbe is disabled by default and must be enabled by a feature gate.

**Proposed Solution:**
Mention in the page that the feature gate must be enabled.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Optional Information:**
Kubernetes Version: v1.17.4 (server and client)

**Comment by SimonHeimberg** [comment]
similar or duplicate: #19405

**Comment by tengqm** [comment]
Yup. This is a dup of #19405 
Let's track the issue there.
/close
