### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/high-availability/

### ISSUE THREAD

**Issue by alex-leonhardt** [kubernetes/website#20585]
There's a potentially missing step at the end of bootstrapping a HA cluster using kubeadm, the kube-apiserver, etc. do not get a updated manifest that points to all etcd nodes (using a stacked arch), so a `k get componentstatuses` may only display a single etcd node, the default `localhost` etcd.

I'd suggest to update the doc to explicitly state that kube-apiserver, etc. manifests need updating to point to _all_ etcd nodes provisioned so that `componentstatuses` actually retrieves and provides the correct status/es.

Example: 
```
NAME                 STATUS    MESSAGE             ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-0               Healthy   {"health":"true"}
```

vs

```
NAME                 STATUS      MESSAGE                                                                                                                                         ERROR
controller-manager   Healthy     ok
scheduler            Healthy     ok
etcd-1               Healthy     {"health":"true"}
etcd-0               Healthy     {"health":"true"}
etcd-2               Unhealthy   Get https://10.128.0.15:2379/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by neolit123** [comment]
> so a k get componentstatuses may only display a single etcd node, the default localhost etcd.

`componentstatuses` is being deprecated. there was an issue about that in the kubernetes/enhancements repository.

please use `etcdctl` to get the status of your etcd cluster.

> There's a potentially missing step at the end of bootstrapping a HA cluster using kubeadm, the kube-apiserver, etc. do not get a updated manifest that points to all etcd nodes

this step is not really required for the cluster to function and amending the manifests is a further complication post etcd bootstrap.

> I'd suggest to update the doc to explicitly state that kube-apiserver, etc. manifests need updating to point to all etcd nodes provisioned so that componentstatuses actually retrieves and provides the correct status/es.

i don't think the kubeadm docs should be updated to comply with componentstatuses (as it might get removed at some point).

/sig cluster-lifecycle
/priority awaiting-more-evidence

**Comment by alex-leonhardt** [comment]
It's true that the step isn't _required_ for a functioning cluster, but the page is about setting up a _production_ cluster so I thought it should be part of this doc? 

FWIW, there is https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#set-up-the-first-control-plane-node that creates an example `kubeadm-config.yaml` when one isn't using a stacked approach.

Either way, I thought it's worth mentioning as when that one configured local etcd node would stop functioning, then so would that kube-apiserver (instead of continuing to work using the other 2 or more etcd nodes).

**Comment by neolit123** [comment]
>It's true that the step isn't required for a functioning cluster, but the page is about setting up a production cluster so I thought it should be part of this doc?

i don't think we should mention componentstatus in the kubeadm docs.

one alternative is to move the contents of `8. Optional: Check the cluster health` from here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster

as a new item under common tasks here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#common-tasks-after-bootstrapping-control-plane

PRs are welcome!
/help

**Comment by alex-leonhardt** [comment]
> i don't think we should mention componentstatus in the kubeadm docs.
You're probably right, since it's being removed anyway, there's no point. 

Though moving the _8. Optional: Check the cluster health_ from the ha etcd setup won't actually tell admins they should update the `kube-apiserver.yaml` to point to the other etcd instances, if that makes sense? That was the original _"issue"_ and I believe that simply mentioning this in _ Common tasks after bootstrapping control plane_  with perhaps an example _"snippet"_ would do.

**Comment by neolit123** [comment]
no, we should not do that. for stacked, an api-server instance should only know about the etcd server instance that was deployed on this same host.

**Comment by alex-leonhardt** [comment]
> no, we should not do that. for stacked, an api-server instance should only know about the etcd server instance that was deployed on this same host.

Hmm, I'm curious, what's the reasoning behind this?

**Comment by neolit123** [comment]
this changes the topology defined here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/#stacked-etcd-topology

it now needs arrows from each api-server to individual etcd members.
by adding it to the docs we will also recommend it as a best practice and it's more of a workaround for a `componentstatus` issue (please don't use it). a stacked-etcd node should be self-contained and the etcd cluster is "stacked" on top of the kubernetes cluster.

**Comment by alex-leonhardt** [comment]
Actually, it's not a workaround for a `componentstatus` issue, I mentioned `componentstatuses` because that's what pointed me at the fact that the kube-apiservers aren't configured to use all etcd nodes.

However, you're right, based on that diagram, stacked topology seems to mean that the components on a host do not cross connect / only use the localhost etcd endpoint. 

FWIW - It still seems wrong to me that an issue (or maintenance, or whatever) on only the local `etcd` instance should effectively take out the `kube-apiserver` too.

**Comment by neolit123** [comment]
> FWIW - It still seems wrong to me that an issue (or maintenance, or whatever) on only the local etcd instance should effectively take out the kube-apiserver too.

that is a tradeoff for stacked, one component failing, fails the whole node.
and stacked nodes are considered self-contained and swappable - i.e. the LB *should* give you a new node if the current leader's storage layer fails.

what you are suggesting can be done on demand, but i still don't think we should include it in the docs as an optional step.

for something that is more HA, we suggest using external etcd where all api-servers know about all the etcd members.

**Comment by alex-leonhardt** [comment]
Fair enough I guess. Thanks!
