### ISSUE TITLE
Link to Information that can be Specified via a Pod Template

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/website#20587]
**What would you like to be added**

When viewing the [Pod template section](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#pod-templates) of the website, I would like to see information on all the properties I can define via a Pod template. It would be helpful to link to some information and provide context about possible properties that can be defined via a pod template. 

**Why is this needed**

People looking for information specifically about Pod templates will most likely come to this page. I would expect to find information about what I can use via a Pod template in this section as well.

**Comments**

It would probably be helpful to link to the Kubernetes API documentation on Pods:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#pod-v1-core

Also just making a note that there is a broken link for `workload`, which doesn't link to any meaningful information.

**Comment by tengqm** [comment]
The current logic is that the "pod overview" page will lead you to more details on the [pod](https://kubernetes.io/docs/concepts/workloads/pods/pod/) page, where you can find the link to the API doc you suggested. We simply cannot squeeze every detail to a single page.
Regarding the 'workload' link, ... it is not a link, just a glossary.
/close
