### ISSUE TITLE
kubectl run erroneously recommended to create deployments

### ISSUE THREAD

**Issue by jflamy** [kubernetes/website#20603]
**This is a Bug Report**

**Problem:**
`kubectl run` is wrongly recommended as a way to create a single-pod deployment, whereas it not longer does - it only creates a pod without a deployment.

**Proposed Solution:**
Provide the correct imperative commands to do the same (especially the port mappings).
Currently this appears to require creating a yaml file whereas previously simple use cases could be done imperatively.

**Page to Update:**
k8s.io/docs/concepts/configuration/overview/

Kubernetes Version: 1.18

**Comment by tengqm** [comment]
We are currently in an awkward situation where kubectl run is being deprecated while `kubectl create` equivalent is still catching up wrt specifying ports etc.
/language en
/kind feature
/sig cli

**Comment by sftim** [comment]
I think this is already addressed.
@jflamy do you agree?
