### ISSUE TITLE
Add/investigate a link checker for the k8s website

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#20607]
**This is a Feature Request**

In order to provide more accurate, useful content and to enable more resilient translation workflows, we need to first ensure that links are accurate and unbroken. The best way to do this is through automation (a link checker).

**What would you like to be added**

Add https://github.com/wjdp/htmltest as a Make command so that individuals can test locally. Eventually, this could scale up to deeper GitHub/Netlify integration.

**Comments**

At the SIG-Docs quarterly planning, we decided that link checking was a necessary prerequisite to  Improving intra-site linking for translation (https://github.com/kubernetes/website/pull/19526 or a similar effort).  There's no way to validate how successful re-implementing links might be unless we can validate that our existing links are correct.

**Comment by celestehorgan** [comment]
Based on where #20606 stands at the moment, I'd like to make the following recommendations:

1) Clean up the WIP PR, add some documentation to the Contribute section/README.md on using it, and merge it.
2) Open a second PR which corrects the initial set of links found by the link checker. This way when someone chooses to use the link checker, they get actual errors.

----

Some things to decide before we move forward:

1) What directory should we set as the scope of the linkchecker? We can scan all of the generated HTML (`/public`) but this would include translation links as well. 
2) Are we comfortable with the configuration settings, or are there things we'd ideally turn on? (i.e., checking external links for https). 

----

Some things we could potentially do as follow-up issues/PRs:

- Remove (one by one) content redirects from the `_redirects` file and correct them, cleaning up our redirects and making it easier for new contributors.
- Supercharging our linkchecker configuration so we can test each translation individually

**Comment by mikejoh** [comment]
I have one comment about how to run the `htmltest` tool locally. Would it make sense to add something like to the `Makefile`:

```make
docker-build-linkcheck:
	$(DOCKER_RUN) $(DOCKER_IMAGE) hugo --minify --config config.toml,linkcheck-config.toml

docker-check-all-links: docker-build-linkcheck link-checker-setup
	bin/htmltest --conf .htmltest.external.yml

docker-check-internal-links: docker-build-linkcheck link-checker-setup run-link-checker
```

I didn't have the `hugo` binary locally when i clone and tested a bit with your branch, it would be nice to have utility functions in the `Makefile` that runs everything through Docker.
