### ISSUE TITLE
Reference docs incorrect v1.18 kubectl run command

### ISSUE THREAD

**Issue by DragD** [kubernetes/website#20614]
**This is a Bug Report**

**Problem:**
The reference documentation for kubectl v1.18 does not match the implementation regarding `run` command and its options `--restart`  and `--replicas`.

**Proposed Solution:**
Update the reference docs.

**Pages to Update:**
- https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#run, the sections for options replicas and restart are incorrect. The `--replicas` option is depreciated and `run` always creates a pod regardless of the `--restart` value.

- https://kubernetes.io/docs/reference/kubectl/#operations, the following line:

> kubectl run NAME –image=image [–env=“key=value”] [–port=port] [–replicas=replicas] [–dry-run=server

The `--replicas` option is depreciated.

**Comment by viniciusbds** [comment]
Thanks for contributing @DragD
