### ISSUE TITLE
Where can I write docs on deprecated APIs

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/website#20617]
I was recently working on a project dealing with API depreciation (extensions, apps/v1beta1, etc). We found there was no place that documented the current APIs and what the depreciation's were. Is there a place in the docs we can document this? Or, maybe I just missed it. I'm willing to write docs around this.

**Comment by kbhawkey** [comment]
Is this relevant:
https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**Comment by tengqm** [comment]
In fact, this is not documented anywhere AFAICT. As @kbhawkey has pointed out, there is deprecation policy defined. However, that policy is NOT strictly followed for many reasons.

**Comment by kbhawkey** [comment]
Some previous discussion about deprecated APIs:
https://github.com/kubernetes/website/issues/18675
