### ISSUE TITLE
render reference docs with double dash

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#20623]
reference docs render with `–` (single UTF8 8211) instead of `--` (ANSI 45) even if a generated reference page contains the regular double dash `--`.

see
https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
vs
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

this makes users copy-pasting command line flags insert bogus flags in their setup.

**request:** please make the website render the double dash `--`.

/kind bug
/sig docs
/cc @tengqm @sftim

**Comment by neolit123** [comment]
reported here on slack:
https://kubernetes.slack.com/archives/C0EN96KUY/p1588093350150000

**Comment by sftim** [comment]
/priority important-longterm
(or higher)

**Comment by sftim** [comment]
Thanks for filing the issue @neolit123

**Comment by tengqm** [comment]
Emm. Hugo is again doing some conversion behind the scene.
If you check the reference page we generated: https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
you can see that the `--` is in the source. Hugo converted into `&ndash;`, for unknown reason.

**Comment by sftim** [comment]
I suspect we will find pages that have relied on the smart dashes behavior. For a different, lasting fix, maybe we change the docs generation to write HTML/Markdown that looks like:
```html
<span>--option-name=defaultValue</span>
```
**or**
maybe we switch to a newer Hugo that implements more of CommonMark and _that_ lets us re-enable smart dashes without breaking reference docs?

**Comment by crazytera** [comment]
Wow thanks for implementing the change so quickly after the report <3 you guys rock!!
