### ISSUE TITLE
K8s 1.19 - Formalize docs release strategy with the different localization owners

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/website#20624]
Hi All :)

This is Savitha Raghunathan, Docs lead for K8s 1.19 release. I'm opening this issue to find the best way to coordinate the actual docs release (scheduled tentatively for Aug 25th, 2020 ) with the different localization owners.

A couple Questions:

1. Who would be a good primary contact for the following localization content?

- [x] French - @remyleone 
- [x] German - @mkorbi 
- [ ] Hindi
- [x] Indonesian - @girikuncoro 
- [x] Japanese - @inductor 
- [ ] Russian
- [x] Polish - @mfilocha 
- [x] Korean - @seokho-son 
- [x] Portuguese - @jcjesus 
- [x] Spanish - @raelga 
- [x] Chinese - @tengqm 
- [ ] Vietnamese
- [x] Ukrainian - @butuzov 
- [x] Italian - @fabriziopandini 

2. Any process improvements in mind?

I look forward to working with everyone! Let me know if you have any questions! Thanks!

cc: @kubernetes/sig-docs-fr-owners @kubernetes/sig-docs-de-owners @kubernetes/sig-docs-hi-owners  @kubernetes/sig-docs-id-owners @kubernetes/sig-docs-ja-owners @kubernetes/sig-docs-ru-owners @kubernetes/sig-docs-pl-owners  @kubernetes/sig-docs-ko-owners @kubernetes/sig-docs-pt-owners @kubernetes/sig-docs-es-owners @kubernetes/sig-docs-zh-owners @kubernetes/sig-docs-vi-owners @kubernetes/sig-docs-uk-owners @kubernetes/sig-docs-it-owners

**Comment by girikuncoro** [comment]
Thanks @savitharaghunathan for this, for Indonesian localization I can be the primary contact (slack: onigiri) 

Regarding process improvement, especially for our localization project, I guess we are still at around 140 localized pages (mostly on concept and task, started from 1.16 release cycle), we havent revisited localized pages that possibly got changed because of later releases, would love to get suggestions on how to keep up with changed pages, this is slowly becoming pain for us, some pages have moved, some have gone, some are deprecated, etc. We haven't done release branches yet, because we want to focus on localizing as many pages

**Comment by mfilocha** [comment]
You can contact me for Polish localization related tasks.

**Comment by fabriziopandini** [comment]
@savitharaghunathan I can take Italian localisation

**Comment by gochist** [comment]
I'm leading Korean l10n. (slack: june.yi)

**Comment by inductor** [comment]
I am learning Japanese Docs. find me by inductor on Slack!

**Comment by mkorbi** [comment]
@savitharaghunathan I can be your contact for German

**Comment by remyleone** [comment]
You can contact me for questions related to French localization

**Comment by Rajakavitha1** [comment]
Hi @savitharaghunathan  I was only helping the Hindi Localization team in reviewing the translated guide. Not involved in the localization efforts any more.

**Comment by jcjesus** [comment]
Hi, for portuguese, can sent to me, please!
Thanks
jcjesus




Em ter., 28 de abr. de 2020 às 14:52, Savitha Raghunathan <
notifications@github.com> escreveu:

**Comment by tengqm** [comment]
I can serve the Chinese localization focal, at least for this release.

**Comment by seokho-son** [comment]
@savitharaghunathan  
Hello ~ Korean l10n Team leader has been changed. 
Currently, I am primary contact for Ko ( Github: @seokho-son / Slack: Seokho )

**Comment by raelga** [comment]
Count me in for questions related to Spanish localization!

**Comment by butuzov** [comment]
I am on the side of the Ukrainian team.

**Comment by savitharaghunathan** [comment]
Hi All, I have frozen the k/website to prepare for 1.19 release. The release is scheduled to happen tomorrow and no PRs are allowed to merge until the release PR successfully merges. Please let me know if you have any concerns or queries. Thanks to all your localization efforts and making the k8s community awesome 

Ref: https://github.com/kubernetes/website/issues/23399

**Comment by mittalyashu** [comment]
I can contribute on Hindi localisation.

> Was busy past months, will try to set more free time for Hindi localisation.

**Comment by savitharaghunathan** [comment]
Hi All, k/website repo is officiallt thawed :) Thank you for your patience and understanding
