### ISSUE TITLE
Left menu doesn't work in mobile (es)

### ISSUE THREAD

**Issue by npu21** [kubernetes/website#20636]
This is a Bug Report

main issue fixed https://github.com/kubernetes/website/issues/19040

Problem:
Left menu doesn't work in mobile

Proposed Solution:
fix en lang #19646 PR

Page to Update:
https://kubernetes.io/es/docs/home/

/assign
/language es

**Comment by raelga** [comment]
Issue solved in https://github.com/kubernetes/website/pull/20638

/close
