### ISSUE TITLE
Move Eviction Policy into Scheduling & Eviction section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20649]
**This is a Feature Request**

**What would you like to be added**
Migrate the content from https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-policy into somewhere inside https://kubernetes.io/docs/concepts/scheduling-eviction/

**Why is this needed**
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-policy is not task documentation; instead, it's conceptual background.

**Comments**
/language en
/kind cleanup

Initially, a straightforward cut-and-paste would be fine, so I'll mark this as:
/good-first-issue

**Comment by pranshu-s18** [comment]
@sftim do I need to move all the page content or only the eviction-policy section?

**Comment by sftim** [comment]
Just the _Eviction Policy_ section. Overall, https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-policy is a task page and can stay as a task page.

**Comment by ShivamGoyal1899** [comment]
@sftim 
Eviction Policy is a kind of a separate concept. I guess it should be an entirely new page in **Scheduling and Eviction** section, such that it adds an entry in accordion menu as well.

**Comment by sftim** [comment]
> entirely new page in **Scheduling and Eviction** section

There's more than one way to do this, and that's one of the viable approaches.

**Comment by sftim** [comment]
If anyone's ready to tackle this: feel free!

**Comment by gm7y8** [comment]
@sftim i am interested to do pick this up.. let me know if these changes are still required?

**Comment by sftim** [comment]
This work still needs doing. The changes in https://github.com/kubernetes/website/pull/20724/commits/032a7ea337978697dda435e0950fc53d83113695 looked like a good starting point.

**Comment by kbhawkey** [comment]
@sftim Is this issue ready to close?

**Comment by sftim** [comment]
Yep
/close
