### ISSUE TITLE
Scrambled grammaer on k8s.io/docs/concepts/cluster-administration/monitoring/

### ISSUE THREAD

**Issue by dsbos** [kubernetes/website#20652]
**This is a Bug Report**

**Problem:**
The text unclearly says:

"Deprecated metric signal that the metric will eventually be deleted; to find which version, you need to check annotation, which includes from which kubernetes version that metric will be considered deprecated."

(Note the problems, such as "Deprecated metric signal ...," "to check annotation," unclear references to versions (when metric will be gone, when declared deprecated, other?), etc.)

**Proposed Solution:**

Have a fluent English speaker (who knows Kubernetes) edit that.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/monitoring/

**Comment by nate-double-u** [comment]
I'd like to try a pass at this.
/assign

**Comment by nate-double-u** [comment]
Note https://kubernetes.io/docs/concepts/cluster-administration/monitoring/ redirects here: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/

**Comment by nate-double-u** [comment]
Not sure if I'm able to do this, but let's try:

/remove-lifecycle rotten
