### ISSUE TITLE
Contradictory specifications on k8s.io/docs/concepts/cluster-administration/monitoring/

### ISSUE THREAD

**Issue by dsbos** [kubernetes/website#20654]
**This is a Bug Report**

**Problem:**

In the page section at https://kubernetes.io/docs/concepts/cluster-administration/monitoring/#metric-lifecycle, the text says "... Stable metric → Deprecated metric → Hidden metric → Deletion" (that is, that a metric that is stable can become deprecated and eventually deleted, right?) but then contradictorily says:

"Stable metrics can be guaranteed to not change; Specifically, stability means:

    the metric itself will not be deleted ...

(That is, the documentation says that metrics that are stable _will not change or be deleted_, but then says that they _can be changed and deleted_.)

**Proposed Solution:**

Shouldn't the part about stable metrics and what's guaranteed about them say that they won't change **other than by going through deprecation**?

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/monitoring/

**Comment by tengqm** [comment]
dup of #20655 
/close
