### ISSUE TITLE
Issue with k8s.io/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by GodHaoNB** [kubernetes/website#20672]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@GodHaoNB can you please elaborate what is the issue with the page?

**Comment by tengqm** [comment]
Smells like an accidental click/report and the author is busy clicking other buttons. Feel free to reopen if there ARE issues to report.

/close
