### ISSUE TITLE
Admission Control doc fails to say it only applies to certain verbs

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#20673]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#admission-control gives an overview of admission control and how it fits into the overall request handling.  It does not mention the fact that admission control applies only to certain verbs.  But, looking at the code, it appears to me that admission control does indeed apply to only certain verbs.  For example, I went looking for calls to validating admission plugins.  I found four call sites:

- https://github.com/kubernetes/kubernetes/blob/863ce9726e0aa617f03332f42ff3cebb7abe8fc0/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L177
- https://github.com/kubernetes/kubernetes/blob/863ce9726e0aa617f03332f42ff3cebb7abe8fc0/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L190
- https://github.com/kubernetes/kubernetes/blob/863ce9726e0aa617f03332f42ff3cebb7abe8fc0/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go#L177
- https://github.com/kubernetes/kubernetes/blob/863ce9726e0aa617f03332f42ff3cebb7abe8fc0/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L277

**Proposed Solution:**
Document the fact that admission control applies only to certain verbs.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#admission-control
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/

This is a current and long-standing issue.

**Comment by ZhiFeng1993** [comment]
@MikeSpreitzer  I haven't found anything to update in https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/

Just confirm if I missed anything. Thanks

**Comment by MikeSpreitzer** [comment]
I seem to have overlooked a sentence that is already in https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#admission-control : "They act on objects being created, deleted, updated or connected (proxy), but not reads".  That is an exactly accurate statement when the word "updated" is taken in its plain English sense --- which is the most plausible sense in this context.

There is a potential for confusion about that word, because the generated typed clients have a method named "Update" plus other methods (e.g., "Patch") that also modify the object in question.  See `type ServiceInterface` at https://github.com/kubernetes/client-go/blob/6b7c68377979c821b73d98d1bd4c5a466034f491/kubernetes/typed/core/v1/service.go#L40-L48 for an example.  So it would not hurt to add a note making it clear that the plain English sense of "updated" is intended.

**Comment by ZhiFeng1993** [comment]
Both PRs have been merged. We can close this issue now. @MikeSpreitzer

**Comment by tengqm** [comment]
Feel free to reopen if there are more fixes expected.
/close
