### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by perret34** [kubernetes/website#20683]
Hello,
Excuse me for this way of contacting you, I don't think it was a coincidence that I contacted you. It is good after several days of intense prayer that I do it is that the Holy Spirit guided me towards you by the grace of God. I donate my goods to an honest and needy person of French origin and I live in France. I suffer from a serious illness which condemns me to certain death, it is throat cancer, and I have a sum of 700,000 euros which I would like to make a donation to a person of trust and honest so let him make good use of it in order to help his family and start a new life in happiness and peace. I donate these funds for free to change your life. I donate this because after all the love of neighbor is the basis of all my Christian life.
I would then like to know if you can benefit from this donation?
Contact by email for the procedures to obtain 700,000 euros for free.

Mail: Perretgerome@gmail.com

God bless you.

**Comment by sftim** [comment]
This is spam
/close
