### ISSUE TITLE
alphabetize readme localization links in project README

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#20693]
**This is a Feature Request**
The links in the README table should be listed alphabetically.
Over time, the entries were misordered.

**What would you like to be added**
Alphabetize the links in the two column table.
Complete the first column, listing alphabetically the localization names and 
then continue filling the second column.

**Why is this needed**
It is easier to locate alphabetized links. 

**File to update**
https://github.com/kubernetes/website#localization-readmemds

**Comment by sftim** [comment]
Fixed in #20693
/close
