### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/horizontal-pod-autoscale/

### ISSUE THREAD

**Issue by ao-picterra** [kubernetes/website#20702]
**This is a Bug Report**

**Problem:**
In the first scaling policies example "When the number of pods is more than 40 the second policy will be used for scaling down. ", where the 40 comes from is not clear
**Proposed Solution:**
Something like "when the number of replicas is 40, that is when the 10% 2nd policy target is over the first poicy one (4), the 2nd policy will be used" 
**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior

**Comment by sftim** [comment]
40 is 4 divided by 10%. I think the page is assuming that the reader can connect the details, whereas it does make sense to explain that clearly.

The point seems to be that the policies are merged by taking maximum of the different calculated values.

Thanks for reporting this @ao-picterra 
/priority backlog
/language en
/sig autoscaling
