### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/

### ISSUE THREAD

**Issue by slz250** [kubernetes/website#20714]
**This is a Bug Report**

**Problem:**
The link is supposed to be for documentation on k8s workload but instead links to an empty page titled "Pod"

**Proposed Solution:**
n/a

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/

**Comment by sftim** [comment]
@slz250 this duplicates #15539 

Are you OK to close this issue?

**Comment by slz250** [comment]
Ah, sure. Hopefully the page has useful content soon :)
