### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by blairwheadon** [kubernetes/website#20711]
Would love to see some docs on how to configure an ingress to only use https and redirect all http traffic to https (if possible).

Thanks!

**Comment by sftim** [comment]
@blairwheadon Kubernetes _itself_ doesn't provide any Ingress controllers. I think what you want to achieve might be more feasible once Ingress is stabilised. Until then, and as I understand it, each Ingress controller is allowed to implement its own way to make this happen.

If you're looking for advice relating to a specific Ingress implementation, I think you'd look at the documentation for that implementation.

If you're interested in writing this up, a blog post on the topic (covering several implementations) would be a nice thing to have I think.
