### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/service-access-application-cluster/

### ISSUE THREAD

**Issue by pallavimitra** [kubernetes/website#20737]
When trying to access the Hello World application using curl, I am getting "curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed" error. 
I hope it arose because of not creating a firewall rule that allows TCP traffic on your node port. 
Could anyone please help me how to create that firewall rule? 

Thanks in advance.

**Comment by mustufa5689** [comment]
Run this command on your Node with your exposed nodeport where your Firewall is running. # iptables -A INPUT -p tcp --dport <Node_Port> -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

Else, try to disable the firewall on your node and see if the traffic hits your application's target port.

**Comment by sftim** [comment]
/triage support
(I think)

**Comment by tengqm** [comment]
Sounds the workaround is working ...
Feel free to reopen this if there are doc side improvement to be done.
/close
