### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by Cariaga** [kubernetes/website#20730]
minikube dashboard command actually works
but the example is saying to use kubectl proxy its just stuck at starting

**Comment by sftim** [comment]
@Cariaga can you clarify the issue that you're reporting? If the documentation isn't right, I / we would like more information so we can work out how to improve it.

**Comment by tengqm** [comment]
/language en

We may need to explicitly state that `kubectl proxy` never returns. You will have to open a new terminal to perform any operations.
