### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha-1-12/

### ISSUE THREAD

**Issue by SandhyaNagarajan** [kubernetes/website#20732]
**This is a Bug Report**

**Problem:** The k8s upgrade procedure for older versions before 1.11 is not available in the official k8s website. But the same upgrade steps from 1.11 to 1.12 is applicable for 1.8.x to 1.9.x as well.

**Proposed Solution:** Best case, put the older version in the archive to be possible to people in older version to upgrade. Atleast, a mention on this page that the older version could also be upgraded using this method will be useful.

**Page to Update:**
https://kubernetes.io/...

 Any version < 1.11.x

**Comment by neolit123** [comment]
> Problem: The k8s upgrade procedure for older versions before 1.11 is not available in the official k8s website. But the same upgrade steps from 1.11 to 1.12 is applicable for 1.8.x to 1.9.x as well.

hi, everything < 1.16 is out of support and unmaintained. 1.16 will go out of support with the release of 1.19.

/triage support
/close
