### ISSUE TITLE
Docsy template: Case studies logo backgrounds don't match page body

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20760]
**This is a Bug Report**

**Problem:**
The logos on the case studies page are already composited onto a gray background. However, the Docsy template renders that page with a white body, and the logo backgrounds jar against it.

**Proposed Solution:**
Either:
- revise logos to use transparency (alpha channels)
- change background color of case studies page for Docsy site build

**Page to Update:**
https://kubernetes-hugo-staging.netlify.app/case-studies/ _(draft)_

Also see #16772

**Comment by sftim** [comment]
/priority awaiting-more-evidence

although I would _like_ this one fixed

**Comment by shuuji3** [comment]
Resolved by #16772?
