### ISSUE TITLE
main page Case Studies block

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#20779]
**This is a Bug Report**

main page Case Studies block logo to big

**Problem:**
![b5b897cf74](https://user-images.githubusercontent.com/26163841/81042893-d3b26800-8eb9-11ea-9a69-f1db02e04d07.jpg)

**Proposed Solution:**
add max-width 100%

**Page to Update:**
https://kubernetes.io/

**Comment by sftim** [comment]
I think what you're saying is that the logo for the **Babylon** case study is too large and makes the front page of the website render badly.

/priority important-soon
Thanks for filing this @Arhell

**Comment by Arhell** [comment]
resolve
/close
