### ISSUE TITLE
Tracking Ukrainian localization progress

### ISSUE THREAD

**Issue by MaxymVlasov** [kubernetes/website#20786]
Hey folks!

## Maintainers

@MaxymVlasov 

## For New Contributors:

1. Assign to one of [most wanted issues](https://github.com/kubernetes-i18n-ukrainian/website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+no%3Aassignee+label%3A%22most+wanted%22) or [any non-assigned issue](https://github.com/kubernetes-i18n-ukrainian/website/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+no%3Aassignee).<br><sup>If you have troubles with assign - just leave message in issue like "Work on this" and I send invite to org and assign this issue to you</sup>
2. Make fork of [k/website](https://github.com/kubernetes/website).
3. Read [Localization guidelines](https://kubernetes.io/uk/docs/contribute/localization_uk/).
4. Translate.
5. Create PR to [k/website](https://github.com/kubernetes/website).

### Help

If you need any help - join `#kubernetes-docs-uk` channel in [Kubernetes Slack](https://slack.k8s.io/) and feel free to ask.

### Existing localization problems/updates

If you found any issues with translated content - [create issue in k/website](https://github.com/kubernetes/website/issues/new/choose) with `/language uk`.

[kubernetes-i18n-ukrainian/website](https://github.com/kubernetes-i18n-ukrainian/website) should be used only for simplify localization progress.

/assign
/language uk
/kind feature
/priority backlog
/lifecycle frozen

**Comment by sftim** [comment]
🇺🇦:tada:

**Comment by Arhell** [comment]
Hi, check please
https://github.com/kubernetes/website/pull/20951

**Comment by MaxymVlasov** [comment]
Hi @seokho-son 
If you can suggest how to better point newcomers to what that should do - I'm all ears.

In theory, it could be moved to https://github.com/kubernetes/website/blob/main/README-uk.md, but I'm not sure that someone will go to it, as in repo README there are no mentions that in localization README could be something specific for localization, and "go check it first and only then general contribution guides"

**Comment by seokho-son** [comment]
Hi @MaxymVlasov :)
Thanks for the feedback. I think the Ukrainian team can create [language-specific-localization-guide](https://kubernetes.io/docs/contribute/localization/#language-specific-localization-guide) and share the guide to tentative contributors. And feel free to utilize README-uk.md for something specific for localization.

Also, you can keep this issue as well if you think it is still useful. We are just checking if there is not useful open issues.
