### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by yuanxuzhang** [kubernetes/website#20801]
**This is a Bug Report**

[**Problem:**]([url]([url](url)))
1.In the https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable，it said:The value cannot be 0 if .spec.strategy.rollingUpdate.maxSurge is 0. That is to say: MaxUnavailable is 0, and maxSurge is 0 is allowed?
2.But in the https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-surge,it said: The value cannot be 0 if MaxUnavailable is 0. That is to say: MaxUnavailable is 0, and maxSurge is 0 is not allowed?
1 and 2 seem a conflict.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@yuanxuzhang can you clarify the logic of what you're asking? I am not sure that I follow the wording 100% (sorry).

**Comment by yuanxuzhang** [comment]
sorry.I got it wrong.
