### ISSUE TITLE
white bar on the blog page

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#20809]
**This is a Bug Report**

white bar on the blog page

**Problem:**
To big white bar on the blog page

**Proposed Solution:**
Remove button after footer

**Page to Update:**
https://kubernetes.io/blog/

/assign

**Comment by sftim** [comment]
@Arhell can you provide an annotate screenshot or other description to clarify what isn't right with that page?

**Comment by Arhell** [comment]
![2](https://user-images.githubusercontent.com/26163841/81264704-89acbc00-904a-11ea-8d52-8a299398bec3.jpg)
White bar in all browsers, chrome, opera, firefox

**Comment by kbhawkey** [comment]
Ideally, only the pages (docs) that _require_ the partial footer-scripts.html would include this template.

**Comment by Arhell** [comment]
resolve
/close
