### ISSUE TITLE
Add branching strategy with mermaid diagram

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#20811]
It seems we are explaining our branching strategy quite often and it would be good to have a section in our contributor guide as opposed to my personal site (https://jimsurls.com/git-branching/).

Mermaid supports this type of documentation chart.

/cc @zacharysarah @kbarnard10 @sftim @kbhawkey @onlydole 
/assign

**Comment by onlydole** [comment]
I like this idea!!! Great use of Mermaid, too 😄

**Comment by jimangel** [comment]
After looking into this more, gitGraph is _experimental_ and I crashed https://hackmd.io when testing more than 3 branches 😄  https://mermaid-js.github.io/mermaid/#/?id=git-graph-exclamation-experimental

Maybe it will be worth revisiting later. For now:
/close

**Comment by sftim** [comment]
Note to future spelunkers: Mermaid also has some support for SVG export
