### ISSUE TITLE
Issue with k8s.io/docs/setup/best-practices/cluster-large/

### ISSUE THREAD

**Issue by KristianWindsor** [kubernetes/website#20813]
**This is a Bug Report**

**Problem:**
This page recommends using outdated instance types (on AWS). EC2 M3 instances are being phased out: https://aws.amazon.com/ec2/previous-generation/

**Proposed Solution:**
Update docs to use modern instance types (maybe M5 or T2).

**Page to Update:**
https://kubernetes.io/docs/setup/best-practices/cluster-large/#size-of-master-and-master-components

**Comment by sftim** [comment]
With https://kubernetes.io/docs/contribute/style/content-guide/ in mind, I think it makes sense to drop the recommendations about specific vendor services from that page.

**Comment by sftim** [comment]
Fixed by removing AWS references
/close
