### ISSUE TITLE
Document that PodDisruptionBudget is beta

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20821]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/tasks/run-application/configure-pdb/ does not mention that PodDisruptionBudget is beta.

**Proposed Solution:**
Add a [feature-state](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#feature-state) shortcode to 
https://kubernetes.io/docs/tasks/run-application/configure-pdb/

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/configure-pdb/
There may well be other pages that describe PodDisruptionBudget without mentioning its feature state.

**Kubernetes Version:**
v1.18

/help
/kind bug
/priority backlog

**Comment by prasadkatti** [comment]
I don't `PodDisruptionBudget ` see on this page - https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by prasadkatti** [comment]
Looks like it is `beta` since `v1.5`.
