### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

### ISSUE THREAD

**Issue by ElvinYangGo** [kubernetes/website#20834]
**This is a Bug Report**

**Problem:**
Could not start kube-state-metrics after executing "kubectl create -f examples/standard"

**Proposed Solution:**
After cloning kube-state-metrics, the yaml files used to create kube-state-metrics are in kube-state-metrics/examples/standard directory.
"kubectl create -f examples/standard" should be ""kubectl create -f kube-state-metrics/examples/standard".

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

**Comment by tengqm** [comment]
actually the command suggested is `kubectl apply -f kube-state-metrics/examples/standard`, i.e. the directory is there.

/close
