### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by rahulkadukar** [kubernetes/website#20837]
**This is a Bug Report**

**Problem:** Instructions for creating **configmap** are incomplete as they do not provide an example **default.conf** file

**Proposed Solution:** Provide the source for the file **default,cont**

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by Kartik494** [comment]
Hi @rahulkadukar yes default.conf file is missing here.
I think either we can implement this by imperative command 
`kubectl create configmap nginxconfigmap --from-literal="key"="value"`

**Comment by tengqm** [comment]
If you read and follow the steps carefully, you will find that the `default.conf` file is located at https://github.com/kubernetes/examples/tree/master/staging/https-nginx/ 
/close
