### ISSUE TITLE
Describe how to create a binaryData in a configMap

### ISSUE THREAD

**Issue by fml2** [kubernetes/website#20849]
**This is a Feature Request**

**What would you like to be added**
There does not seem to exist a description of how a configMap with binaryData can be created, e.g. via command line. https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-directories and the following sections describe how to create configMaps, but all examples create textual data.

**Why is this needed**

ConfigMaps can store binaryData, as [described in the API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#configmap-v1-core). But there is no information about how to create it.

This feature is a followup from #20738. When this feature is implemented, one should make the words "use binaryData" (in the notes about the encoding used to expose configMaps as files -- see #20738) links pointing to the description of how to create binaryData.

**Comment by tengqm** [comment]
The question is ... why do you want to create binary configmap from command line instead of from a file? How would you type in binary data from command line?

**Comment by fml2** [comment]
Of course nobody would type in the binary data. The config map would be created from command line using `--from-file`, but the examples show that the result has only the `Data` section is populated. So the question is: how can I force the binaryData field to be populated?

**Comment by tengqm** [comment]
@fml2 interesting question. Looks like `kubectl create configmap --from-file=...` can detect the file content. However, I'm not aware of any option one can use to force the population of `binaryData` rather than `data`.

**Comment by fml2** [comment]
Indeed, it seems that the file contents is checked for being a valid UTF-8, see https://github.com/kubernetes/kubernetes/blob/66e3c66eafdcecc49c20f21953b2b069fc17f645/staging/src/k8s.io/kubectl/pkg/generate/versioned/configmap.go#L262-L270.

Does this mean that the `binaryData` (and not `Data`) will be automatically populated if the file contains binary data (as in "not a valid UTF-8")?

**Comment by tengqm** [comment]
> Does this mean that the binaryData (and not Data) will be automatically populated if the file contains binary data (as in "not a valid UTF-8")?

Yes, I think so.

Maybe you want to raise an issue to kubectl in the upstream repo (kubernetes/kubernetes), requesting support to explicitly specify the field to populate?

**Comment by tengqm** [comment]
/close
This is resolved.
Please feel free to reopen if needed.

**Comment by wh81752** [comment]
Can we please reopen this -- rather important -- topic?

The doc about creating a configMap from a folder should very clearly mention that binary data -- identified by the absence of a valid UTF-8 character -- goes into 'binaryData' while non-binary data goes into 'data'.

In all honesty, this rule is very bizarre, not logical, intransparent and IMHO not necessary since it's probably best to store any data just B64 encoded.

Btw, If you just look at LENS 6's configMap (https://k8slens.dev/) , then LENs will just show you textual data and no binaryData at all. I guess they are not even aware about this distinction.

**Comment by fml2** [comment]
This was described in #25986 and is now in this section: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-files

**Comment by itsMarydan** [comment]
[support-bundle-results (2).txt](https://github.com/kubernetes/website/files/10177351/support-bundle-results.2.txt)
