### ISSUE TITLE
Issue Kubernetes Repo

### ISSUE THREAD

**Issue by vivekverma066** [kubernetes/website#20841]
Hi,

There are no packages available under "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/Packages" now.

Can you suggest how can we get these packages.

**Comment by prasadkatti** [comment]
This repo is for issues with the kubernetes website. Since you are asking about missing packages, I think you should move this to https://github.com/kubernetes/release repo.

**Comment by prasadkatti** [comment]
You can also trying asking on the #sig-release channel on [Slack](kubernetes.slack.com) maybe
