### ISSUE TITLE
Signpost users to related KubeCon talks

### ISSUE THREAD

**Issue by prasadkatti** [kubernetes/website#20866]
**This is a Feature Request**

**What would you like to be added**
We could add links to Kubecon talks in the 'What next' sections.

**Why is this needed**
Some people prefer learning via video as opposed to text.
These recorded talks often have diagrams and demos that are quite helpful when understanding concepts.

**Comments**

**Comment by sftim** [comment]
That's a great idea! Another way to benefit from the diagrams from a talk is to redraw it and add it to the page in question. Either kind of improvement is welcome.
