### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/troubleshooting/

### ISSUE THREAD

**Issue by Francesco1971** [kubernetes/website#20873]
I' m new in kubernetes , I ve installed traefik but I cannot access from external to its resource
I 've installed one master and one worker node
rlltmanfra01.interno.regione.lazio.it   Ready    master   4d7h   v1.18.2
rlltnodfra01.interno.regione.lazio.it   Ready    <none>   4d6h   v1.18.2
I ve installed traefik 
helm install traefik traefik/traefik --values traefik-values.yml 
here you are traefik-values 
dashboard:
  enabled: true
  domain: traefik.interno.regione.lazio.it
  auth:
    basic:
      admin: $2y$05$kpCJY2gJWlgG5CUs5tdPx.2xGJ4xyqhWtjiiM/NKfHmj3pfUPsap2
ssl:
  enabled: true
  enforced: true
  permanentRedirect: true
  generateTLS: true
  defaultCN: "*.interno.regione.lazio.it"
But it is impossible to access to dashboard of traefik
The cluster is installed in two vm centos 7 in mu datacenter 
This is the network interrface of master 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:50:56:86:9f:9c brd ff:ff:ff:ff:ff:ff
    inet 10.2.28.40/24 brd 10.2.28.255 scope global noprefixroute ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe86:9f9c/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:25:3d:60:af brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: cali867eee5cfba@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
5: cali071c528d278@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
6: cali4b9b0dda8f4@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
7: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1440 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 192.168.101.0/32 brd 192.168.101.0 scope global tunl0
       valid_lft forever preferred_lft forever
9: cali2682312c565@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever

This is the pods is running on
NAMESPACE              NAME                                                            READY   STATUS    RESTARTS   AGE    IP              NODE                                    NOMINATED NODE   READINESS GATES
default                alpine                                                          1/1     Running   0          24m    192.168.30.22   rlltnodfra01.interno.regione.lazio.it   <none>           <none>
default                hostnames                                                       1/1     Running   0          80m    192.168.30.19   rlltnodfra01.interno.regione.lazio.it   <none>           <none>
default                traefik-5956bc68cf-77sz4                                        1/1     Running   0          24m    192.168.30.21   rlltnodfra01.interno.regione.lazio.it   <none>           <none>
kube-system            calico-kube-controllers-75d56dfc47-p56k4                        1/1     Running   0          4d7h   192.168.101.2   rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            calico-node-tmvn4                                               1/1     Running   0          4d7h   10.2.28.40      rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            calico-node-vq4rt                                               1/1     Running   0          4d6h   10.2.28.41      rlltnodfra01.interno.regione.lazio.it   <none>           <none>
kube-system            coredns-66bff467f8-4b9t5                                        1/1     Running   0          4d7h   192.168.101.3   rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            coredns-66bff467f8-d5nz6                                        1/1     Running   0          4d7h   192.168.101.1   rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            etcd-rlltmanfra01.interno.regione.lazio.it                      1/1     Running   0          4d7h   10.2.28.40      rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            kube-apiserver-rlltmanfra01.interno.regione.lazio.it            1/1     Running   0          4d7h   10.2.28.40      rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            kube-controller-manager-rlltmanfra01.interno.regione.lazio.it   1/1     Running   10         4d7h   10.2.28.40      rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            kube-proxy-gntbs                                                1/1     Running   0          4d6h   10.2.28.41      rlltnodfra01.interno.regione.lazio.it   <none>           <none>
kube-system            kube-proxy-qjljv                                                1/1     Running   2          4d7h   10.2.28.40      rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kube-system            kube-scheduler-rlltmanfra01.interno.regione.lazio.it            1/1     Running   11         4d7h   10.2.28.40      rlltmanfra01.interno.regione.lazio.it   <none>           <none>
kubernetes-dashboard   dashboard-metrics-scraper-6b4884c9d5-lzzcd                      1/1     Running   0          3d3h   192.168.30.12   rlltnodfra01.interno.regione.lazio.it   <none>           <none>
kubernetes-dashboard   kubernetes-dashboard-7b544877d5-d9znl                           1/1     Running   0          3d3h   192.168.101.5   rlltmanfra01.interno.regione.lazio.it   <none>           <none>

kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP                      4d7h
traefik      LoadBalancer   10.101.195.101   <pending>     80:30378/TCP,443:30852/TCP   25m

I cannot access to kubernetes dashboard too. In the last days I ve installed haproxy and configured ingress , but nothing to do , from my laptop if I put in my hosts file ip address of master/worket that point to resource , I cannot access.
From alpine pod I ve this result
 nslookup traefik
Server:         10.96.0.10
Address:        10.96.0.10:53

Name:   traefik.default.svc.cluster.local
Address: 10.101.195.101

** server can't find traefik.svc.cluster.local: NXDOMAIN

** server can't find traefik.svc.cluster.local: NXDOMAIN

** server can't find traefik.cluster.local: NXDOMAIN

** server can't find traefik.cluster.local: NXDOMAIN

** server can't find traefik.interno.regione.lazio.it: NXDOMAIN

** server can't find traefik.interno.regione.lazio.it: NXDOMAIN
How can I point to that service from an extenal source (my laptop in this case) ??
Thank you again

**Comment by tengqm** [comment]
@Francesco1971 Please try raise your question on stackoverflow.com or [kubernetes-users](https://kubernetes.slack.com/archives/C09NXKJKA) slack channel. This issue doesn't sound like a documentation bug for us to fix.
/close

**Comment by Francesco1971** [comment]
Hi thank you very much for the answer, I ve used kubectl proxy and I 've copied .kube config on my pc too.
Then I 've executed kubectl proxy and then I was able to use dashboard with token of sa account.
Thank you very much

**Comment by tengqm** [comment]
@Francesco1971 Good to know you have learned the `kubectl proxy` tricks, :)

**Comment by Francesco1971** [comment]
yes very useful thank you again
