### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by datgeek** [kubernetes/website#20879]
**This is a Bug Report**

**Problem:**
500 error
<img width="788" alt="Screen Shot 2020-05-10 at 19 16 06" src="https://user-images.githubusercontent.com/36273288/81514107-c1d62800-92f2-11ea-9860-b6e7392eed4c.png">

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shuuji3** [comment]
@datgeek Thank you for reporting the problem.

Currently, I can access to https://labs.play-with-k8s.com/ without a problem. Maybe it was a temporary problem. Could you try it again?

It seems that the same 500 error has happened in the play-with-k8s several times: [Issues · play-with-docker/play-with-docker](https://github.com/play-with-docker/play-with-docker/issues?q=is%3Aissue+500+is%3Aclosed).

**Comment by datgeek** [comment]
It's ok now,
thank you

**Comment by shuuji3** [comment]
I’m glad to hear that.
