### ISSUE TITLE
update network policy docs on whitelisting

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#20897]
**This is a Bug Report**
 

**Problem:**
We need to clarify node network policies, because node local traffic is whitelisted https://github.com/kubernetes/api/blob/master/networking/v1/types.go#L64 .

**Proposed Solution:**

doc node whitelists 

**Page to Update:**

**Comment by jayunit100** [comment]
cc @kubernetes/sig-network-misc i can do this if nobody else wants it

**Comment by cmluciano** [comment]
Note: missing docs are for https://kubernetes.io/docs/concepts/services-networking/network-policies/
