### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

### ISSUE THREAD

**Issue by Grovespaz** [kubernetes/website#20898]
**This is a Bug Report**

**Problem:**
I've followed all the steps on this page but they don't seem to be up-to-date / correct.
The flannel and kube-proxy containers won't start on Windows.
The flannel container has the following error message:

>   Warning  FailedCreatePodSandBox  3m (x12 over 3m)     kubelet, win-tplojsb0jn5  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "kube-flannel-ds-windows-amd64-wc22r": Error response from daemon: network host not found

The kube-proxy container has the following error message:
>   Warning  FailedCreatePodSandBox  10m                  kubelet, win-tplojsb0jn5  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "76e22248a4c48eac683fad6f12c5d16077a1a1d0e58ffc499e12260e0ef87b85" network for pod "kube-proxy-windows-j2chr": networkPlugin cni failed to set up pod "kube-proxy-windows-j2chr_kube-system" network: error while GETHNSNewtorkByName(flannel.4096): Network flannel.4096 not found

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

Kubernetes Version:
v1.18.2

**Comment by neolit123** [comment]
hi, this is the issue tracker for the docs. please log an issue here instead:
https://github.com/kubernetes-sigs/sig-windows-tools

/sig windows cluster-lifecycle
/close
