### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by pivotal-yang-jiang** [kubernetes/website#20904]
**This is a Bug Report**

**Problem:**

hello colelagues,
please check the format of this page, when i use chrome to view it, the format is not properly laid out.

best wishes,
Yang
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
PR #20920 may provide a partial fix

**Comment by tengqm** [comment]
Should have been fixed. Feel free to reopen if there are still issues.
/close
