### ISSUE TITLE
Issue with https://kubernetes.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by ishandwivedi** [kubernetes/website#20918]
**This is a Bug Report**

**Problem:**
Markdown does not render correctly on https://kubernetes.io/docs/tasks/tools/install-kubectl/

Under the section “install using other package management” - https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-other-package-management

“snap install kubectl --classic
kubectl version –client“

The flag for client is rendered Incorrectly with a single dash.
Please see photos attached for additional info.

**Proposed Solution:**

The flag for client should be rendered with a double dash (--) 

**Page to Update:**

https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-other-package-management

![FA0B3B21-CF12-45B5-8492-955ACAC009DE](https://user-images.githubusercontent.com/4318603/81723185-63d44c80-947a-11ea-826b-51f3af468d6f.jpeg)
![718DFFEA-5374-4603-B615-DF465305443E](https://user-images.githubusercontent.com/4318603/81723186-646ce300-947a-11ea-839b-a94fe27c0716.jpeg)

**Comment by Kartik494** [comment]
@ishandwivedi  yes it should be (--) in version flag. i think this is problem with indentation.

**Comment by ishandwivedi** [comment]
Hmm I’m not sure about that.
Are you able to reproduce a fix with indentation?

Regards,
Ishan

**Comment by tengqm** [comment]
This issue was solved for both markdown engines we used. Looks like no longer an issue. Pls feel free to reopen if it resurface somewhere again.

/close
