### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by muratcabuk** [kubernetes/website#20914]
**Problem:** Page layout for k8s.io/docs/concepts/services-networking/ingress/ is broken

**Comment by fOO223Fr** [comment]
I have notice this I wanted to fix it but wondering whom to ask for assignee

**Comment by fOO223Fr** [comment]
Fix provided https://github.com/kubernetes/website/pull/20903
/close

**Comment by sftim** [comment]
/close
Fixed in #20903
