### ISSUE TITLE
display of flag, double hyphen, parser upgrade

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#20915]
**This is a Bug Report**
Double hyphen literal characters are not displaying correctly when embedded in `<code>` element.

**Problem:**
Previously, the docs site turned off the BlackFriday parser `smartDashes` setting (config.toml).

With the recent change to Hugo 0.70.0 (Goldmark parser), the dashes are no longer displaying
as dashes when the command string is embedded in the `<code>` element.

One affected page:
https://kubernetes.io/docs/reference/kubectl/overview/#operations

**Proposed Solution:**
Investigate whether the parser can be configured or determine how to display the dashes by removing the use of `<code>` elements.

For additional information, see pull requests #20848, #20909.

**Comment by sftim** [comment]
/kind bug
/priority important-soon

because people copy-and-paste from that page a lot.

**Comment by sftim** [comment]
Relates to #20335

**Comment by neolit123** [comment]
i think we got close to a dozen reports about this already.

**Comment by kbhawkey** [comment]
@neolit123 , Did you see/review PR #21272?

**Comment by neolit123** [comment]
i think i saw it, yes. is there a reason it's not merged yet?

**Comment by kbhawkey** [comment]
> 
> 
> i think i saw it, yes. is there a reason it's not merged yet?

Not that I know of

**Comment by tengqm** [comment]
Things all look good now. Closing this.
/close
