### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by malimccalla** [kubernetes/website#20910]
### Issue

This page does not describe how to use the generated secret to actually pull the private images. For example I have specified a private image in my Deployment but it is not using the credentials supplied as I am getting the following error even after creating my secret

```
Failed to pull image "org/name": rpc error: code = Unknown desc = Error response from daemon: pull access denied for org/name, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

see https://github.com/docker/for-mac/issues/4545 for more info

**Proposed Solution:**

Document how to use the secret in deployment files to pull private images (do i need to perform a `patch` on a service account?).

*edit:*

I believe adding documentation for `imagePullSecrets:` on this page would be beneficial 

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by tengqm** [comment]
Isn't [this section](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) helpful?

**Comment by malimccalla** [comment]
I didn't find that section helpful as I was working with a deployment not a pod. I'll close this as I've solved my problem but I just remember at the time having to join solutions together from different sources to get it working (the docs, blog posts, SO, etc..)

**Comment by tengqm** [comment]
Sad to know that image pull secret section wasn't helping. When you see places where the docs can be improved, pls do raise a PR. Thanks.
