### ISSUE TITLE
Pod assigning throws 404 for older k8s versions

### ISSUE THREAD

**Issue by zub0r** [kubernetes/website#20919]
Selecting older kubernetes version of **Assigning Pods to Nodes** section does not work for older versions - https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by sftim** [comment]
Hmm, a tricky one to solve. The older versions had that documentation at a different location.

One way to fix this is to backport a redirect from https://kubernetes.io/docs/concepts/scheduling-eviction/ to the old location of each page.

**Comment by zub0r** [comment]
Still an issue
/remove-lifecycle stale
