### ISSUE TITLE
Trouble using block style shortcodes when indented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#20921]
**This is a Bug Report**

**Problem:**
The existing content relies on the idea that you can indent a shortcode like `{{< note >}}` inside a list (orderered / unordered) and have the note be part of the HTML `<li></li>` element that gets rendered.

After the upgrade to Hugo 0.70.x pages that rely on this behavior don't always render as expected.

**Pages Affected:**
- https://k8s.io/docs/setup/production-environment/tools/kubeadm/high-availability/
- https://k8s.io/docs/concepts/workloads/controllers/deployment/
- https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
…and more?

**Additional Information:**
This showed after upgrading to use Hugo 0.70.x (PR #19907)

Seems similar to https://github.com/gohugoio/hugo/issues/4717

**Comment by celestehorgan** [comment]
@sftim I got curious about this so I tested it: https://github.com/kubernetes/website/pull/20965

Notes at all levels of indentation [seem to work fine](https://deploy-preview-20965--kubernetes-io-master-staging.netlify.app/docs/test/) on the smoketest. 

I think there's something else going on with these pages.

**Comment by sftim** [comment]
Thanks for investigating @celestehorgan

**Comment by sftim** [comment]
It looks like the `{{% capture …%}}` shortcode is what is giving us problems here. Outside of a `{{% capture …%}}` things work fine.

**Comment by irvifa** [comment]
@celestehorgan can you please rebase from master? would like to know if it's working just fine on your side. Let me know then..

**Comment by mfilocha** [comment]
Similar here: https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by sftim** [comment]
@mfilocha would you be willing to log an issue about https://kubernetes.io/docs/tutorials/hello-minikube/? You can link it to the tracking issue #20335

**Comment by celestehorgan** [comment]
@irvifa – Rebased just now.

**Comment by tengqm** [comment]
So far

- [x] https://kubernetes.io/docs/tutorials/hello-minikube/
- [x] https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
- [x] https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
- [ ] https://k8s.io/docs/setup/production-environment/tools/kubeadm/high-availability/, fix proposed #21722

Can we close this after #21722 is in?

**Comment by sftim** [comment]
/close

Feel free to reopen if that's wrong
