### ISSUE TITLE
document handling of label strings, style guide

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#20925]
**This is a Feature Request**
Provide recommendations for handling the style of label names in the docs.

**What would you like to be added**
Add content to the style guide about how to style _label_ names.

**Why is this needed**
A question came up about double quoting or emphasizing label names.
Namespace names are emphasized (code style).
https://kubernetes.io/docs/contribute/style/style-guide/#use-code-style-for-object-field-names-and-namespaces

**Comment by tengqm** [comment]
Yep. A related, pretty common issue is about the key and values in a YAML manifest. I'm more inclined to say this:

> create a Deployment named `nginx` with a label `app` set to "`frontend`", ...
