### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

### ISSUE THREAD

**Issue by lorna8899** [kubernetes/website#20937]
**This is a Bug Report**

**Problem:**
Wrong format on the page. 
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/kind bug
/priority important-soon
Relates to tracking issue #20335

**Comment by sftim** [comment]
Thanks for reporting this @lorna8899

**Comment by irvifa** [comment]
Do we use 0.70 or 0.60?

**Comment by sftim** [comment]
> Do we use 0.70 or 0.60?

Look for `HUGO_VERSION` in https://github.com/kubernetes/website/blob/master/netlify.toml (currently 0.70.0).

**Comment by irvifa** [comment]
I find the problem is located at:

> Save the CustomResourceDefinition to `resourcedefinition.yaml`:
> 
> {{< tabs name="CustomResourceDefinition_scale" >}}
> {{% tab name="apiextensions.k8s.io/v1" %}}
> ```yaml
> apiVersion: apiextensions.k8s.io/v1
> kind: CustomResourceDefinition
> metadata:
>   name: crontabs.stable.example.com
> spec:
>   group: stable.example.com
>   versions:
>     - name: v1
>       served: true
>       storage: true
>       schema:
>         openAPIV3Schema:
>           type: object
>           properties:
>             spec:
>               type: object
>               properties:
>                 cronSpec:
>                   type: string
>                 image:
>                   type: string
>                 replicas:
>                   type: integer
>             status:
>               type: object
>               properties:
>                 replicas:
>                   type: integer
>                 labelSelector:
>                   type: string
>       # subresources describes the subresources for custom resources.
>       subresources:
>         # status enables the status subresource.
>         status: {}
>         # scale enables the scale subresource.
>         scale:
>           # specReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Spec.Replicas.
>           specReplicasPath: .spec.replicas
>           # statusReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Replicas.
>           statusReplicasPath: .status.replicas
>           # labelSelectorPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Selector.
>           labelSelectorPath: .status.labelSelector
>   scope: Namespaced
>   names:
>     plural: crontabs
>     singular: crontab
>     kind: CronTab
>     shortNames:
>     - ct
> ```
> {{% /tab %}}
> {{% tab name="apiextensions.k8s.io/v1beta1" %}}
> ```yaml
> # Deprecated in v1.16 in favor of apiextensions.k8s.io/v1
> apiVersion: apiextensions.k8s.io/v1beta1
> kind: CustomResourceDefinition
> metadata:
>   name: crontabs.stable.example.com
> spec:
>   group: stable.example.com
>   versions:
>     - name: v1
>       served: true
>       storage: true
>   scope: Namespaced
>   names:
>     plural: crontabs
>     singular: crontab
>     kind: CronTab
>     shortNames:
>     - ct
>   validation:
>     openAPIV3Schema:
>       type: object
>       properties:
>         spec:
>           type: object
>           properties:
>             cronSpec:
>               type: string
>             image:
>               type: string
>             replicas:
>               type: integer
>         status:
>           type: object
>           properties:
>             replicas:
>               type: integer
>             labelSelector:
>               type: string
>   # subresources describes the subresources for custom resources.
>   subresources:
>     # status enables the status subresource.
>     status: {}
>     # scale enables the scale subresource.
>     scale:
>       # specReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Spec.Replicas.
>       specReplicasPath: .spec.replicas
>       # statusReplicasPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Replicas.
>       statusReplicasPath: .status.replicas
>       # labelSelectorPath defines the JSONPath inside of a custom resource that corresponds to Scale.Status.Selector.
>       labelSelectorPath: .status.labelSelector
> ```
> {{% /tab %}}
> {{< /tabs >}}

I'm not sure why this is only on this specific tabs part though
