### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

### ISSUE THREAD

**Issue by gbamqzkdyg** [kubernetes/website#20934]
**This is a Bug Report**

**Problem:**
The page https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/ does not display normally.
**Proposed Solution:**
Fix any HTML or CSS bugs.
**Page to Update:**
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

**Comment by prasadkatti** [comment]
#20937 is really a dup of this. But that issue has been added to the tracking issue. So this one should be closed as a DUP.

**Comment by tengqm** [comment]
confirmed. this is a dup of a closed issue.
pls feel free to reopen if that is not true.
/close
