### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by Kubelancer** [kubernetes/website#20940]
**This is a Bug Report**

Line continuation \ is not reflect on webpage

**Proposed Solution:**
Line continuation \ should reflect 

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

1.18

Please update the page  on  missing line continuation here

### Add Docker apt repository.
add-apt-repository 

  "deb [arch=amd64] https://download.docker.com/linux/ubuntu

  $(lsb_release -cs)

  stable"

## Install Docker CE.
apt-get update && apt-get install -y 

  containerd.io=1.2.13-1 

  docker-ce=5:19.03.8~3-0~ubuntu-$(lsb_release -cs) 

  docker-ce-cli=5:19.03.8~3-0~ubuntu-$(lsb_release -cs)

**Comment by prasadkatti** [comment]
It shows up properly for me -
![image](https://user-images.githubusercontent.com/7345249/81960939-8f644d80-95c6-11ea-8983-c6e770fe560f.png)

**Comment by tengqm** [comment]
Double checked and agree with @prasadkatti, all code snippets are properly rendered.
Please feel free to reopen this if the issue persists (e.g. you have just created your own non-standard browser). :)
/close
