### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/authentication/

### ISSUE THREAD

**Issue by Miss-you** [kubernetes/website#20948]
**This is a Bug Report**

**Problem:**

Hello, when I click "https://kubernetes.io/docs/reference/access-authn-authz/authentication/" to switch to the Chinese page in the upper right corner of the page, I automatically jump to the Chinese version home page instead of Chinese Version of this page

before jump. 

![image](https://user-images.githubusercontent.com/3816205/81839332-f871a400-9579-11ea-8c9e-a6e9c80940e8.png)

after jump.

![image](https://user-images.githubusercontent.com/3816205/81839478-2b1b9c80-957a-11ea-9c97-f2cc73481822.png)

**Proposed Solution:**

Jump to the Chinese version of the current page

I'm pleased to fix this if possible.

**Page to Update:**

https://kubernetes.io/docs/reference/access-authn-authz/authentication/

**Comment by tengqm** [comment]
The problem is that the Chinese version of the authentication page doesn't exists yet.
/close
