### ISSUE TITLE
page layout for https://kubernetes.io/fr/docs/concepts/workloads/controllers/deployment/ is broken

### ISSUE THREAD

**Issue by ArtemAlagizov** [kubernetes/website#20941]
**This is a Bug Report**

**Problem:**

page layout is broken for this page => https://kubernetes.io/fr/docs/concepts/workloads/controllers/deployment/

currently it looks like this:

![current-deployments-french](https://user-images.githubusercontent.com/15367507/81806223-74d59a00-951c-11ea-8262-cc5ca2ac012f.png)

tested in the following browsers: 
* Microsoft Edge 44.18362.449.0
* Google Chrome 81.0.4044.138

**Extra information:**

the reason is broken html: there is a bunch of elements that are on the same level with **\<div id="docsContent"\>\</div\>**, although they should be inside of it

----

good html (English version):

![good-html](https://user-images.githubusercontent.com/15367507/81806140-5a9bbc00-951c-11ea-9d91-31034b6fc11a.png)

----

broken html (French version):

![broken-html](https://user-images.githubusercontent.com/15367507/81806156-5f607000-951c-11ea-8ae8-53e7ddf86c24.png)

----

also, English version was broken yesterday, but today it is already fixed

**Page to Update:**

https://kubernetes.io/fr/docs/concepts/workloads/controllers/deployment/

/kind bug
/language fr

**Comment by irvifa** [comment]
Fixed in https://github.com/kubernetes/website/pull/20946
/close
