### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by Kubelancer** [kubernetes/website#20942]
**This is a Bug Report**

indentation issue

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

1.18

fix the page indentation

**Comment by neolit123** [comment]
/sig cluster-lifecycle docs

hi, can you show which section you think is wrong or maybe provide a screenshot?

**Comment by Kubelancer** [comment]
/sig cluster-lifecycle docs
Attached screenshots

**Comment by neolit123** [comment]
i don't see the attachments, possible because you replied via email.
try adding them using the GitHub web UI.

**Comment by Kubelancer** [comment]
![Capture-1](https://user-images.githubusercontent.com/64853410/81876513-83659500-95a0-11ea-9a31-c9ec8c5408b6.JPG)
![Capture-2](https://user-images.githubusercontent.com/64853410/81876516-852f5880-95a0-11ea-8809-f275f38d44de.JPG)
![Capture-3](https://user-images.githubusercontent.com/64853410/81876517-85c7ef00-95a0-11ea-9e98-184646cd76f4.JPG)
![Capture-4](https://user-images.githubusercontent.com/64853410/81876518-86608580-95a0-11ea-97be-c858c5cc6746.JPG)

**Comment by Kubelancer** [comment]
Page alignment or indentation not proper looks.

**Comment by neolit123** [comment]
ok, i can confirm this.

@sftim hi, was this broken by this PR, or maybe something on the hugo side changed recently?
https://github.com/kubernetes/website/pull/20496

**Comment by sftim** [comment]
> maybe something on the hugo side changed recently?
The Hugo upgrade was PR #19907

**Comment by sftim** [comment]
I've tried to make a work around for this. It looks like tabs shortcodes with code snippets inside them don't play well with `{{% capture …%}}` shortcodes (see issue #20780).

**Comment by jimangel** [comment]
@neolit123 @sftim I will take a stab at cleaning this up assuming work isn't currently being done. We might have to adjust the page slightly until capture is removed.
/assign

**Comment by sftim** [comment]
I can share some WIP in case it helps

**Comment by neolit123** [comment]
thanks for taking a look @sftim and @jimangel

**Comment by jimangel** [comment]
> I can share some WIP in case it helps

oof, sorry @sftim, I saw this after I opened the PR. That does help! I was scratching my head on some of these bugs. Let me know if you want me to modify my PR to incorporate some of your suggestions or vice versa.

I was poking fun of the page on twitter and felt obligated to _try_ to fix it :smile:

**Comment by sftim** [comment]
Busy at the moment I'm afraid. Feel free to snarf any bits that look useful.
