### ISSUE TITLE
page layout for https://kubernetes.io/ko/docs/concepts/workloads/controllers/deployment/ is broken

### ISSUE THREAD

**Issue by ArtemAlagizov** [kubernetes/website#20943]
**This is a Bug Report**

**Problem:**

page layout is broken for this page => https://kubernetes.io/ko/docs/concepts/workloads/controllers/deployment/

currently it looks like this:

![current-deployments-ko](https://user-images.githubusercontent.com/15367507/81807849-1c53cc00-951f-11ea-99b9-523dc4d9aa33.png)

tested in the following browsers: 
* Microsoft Edge 44.18362.449.0
* Google Chrome 81.0.4044.138

**Extra information:**

the reason is broken html: there is a bunch of elements that are on the same level with **\<div id="docsContent"\>\</div\>**, although they should be inside of it

----

good html (English version):

![good-html](https://user-images.githubusercontent.com/15367507/81806140-5a9bbc00-951c-11ea-9d91-31034b6fc11a.png)

----

broken html (Korean version):

![broken-html-ko](https://user-images.githubusercontent.com/15367507/81807935-45745c80-951f-11ea-8a52-c3aadb56abe1.png)

----

also, English version was broken yesterday, but today it is already fixed

**Page to Update:**

https://kubernetes.io/ko/docs/concepts/workloads/controllers/deployment/

/kind bug
/language ko

**Comment by irvifa** [comment]
Fixed in https://github.com/kubernetes/website/pull/20946
/close
