### ISSUE TITLE
page layout for https://kubernetes.io/id/docs/concepts/workloads/controllers/deployment/ is broken 

### ISSUE THREAD

**Issue by ArtemAlagizov** [kubernetes/website#20944]
**This is a Bug Report**

**Problem:**

page layout is broken for this page => https://kubernetes.io/id/docs/concepts/workloads/controllers/deployment/

currently it looks like this:

![current-deployments-id](https://user-images.githubusercontent.com/15367507/81813720-1f06ef00-9528-11ea-8d40-5caaab2985e1.png)

tested in the following browsers: 
* Microsoft Edge 44.18362.449.0
* Google Chrome 81.0.4044.138

**Extra information:**

the reason is broken html: there is a bunch of elements that are on the same level with **\<div id="docsContent"\>\</div\>**, although they should be inside of it

----

good html (English version):

![good-html](https://user-images.githubusercontent.com/15367507/81806140-5a9bbc00-951c-11ea-9d91-31034b6fc11a.png)

----

broken html (Bahasa Indonesia version):

![broken-html-id](https://user-images.githubusercontent.com/15367507/81813689-131b2d00-9528-11ea-8d4a-f5b47d66e545.png)

----

also, English version was broken yesterday, but today it is already fixed

**Page to Update:**

https://kubernetes.io/id/docs/concepts/workloads/controllers/deployment/

/kind bug
/language id

**Comment by irvifa** [comment]
This is solved already https://github.com/kubernetes/website/pull/20946
/close
