### ISSUE TITLE
Localize "Containers overview" page to Italian

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/website#20958]
I would like to have the "Containers overview" page to be translated into Italian
page https://kubernetes.io/docs/concepts/containers/overview/

/language it
/priority important-soon

**Comment by sftim** [comment]
/remove-priority important-soon
/priority important-longterm

The page has moved to https://kubernetes.io/docs/concepts/containers/ BTW

**Comment by fabriziopandini** [comment]
/close
PR already merged
