### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by outscale-nti** [kubernetes/website#20969]
**This is a Bug Report**

**Problem:**
Installation procedure needs to be updated for Centos/Redhat:
The following command does not work
`yum install -y kubelet kubeadm kubectl –disableexcludes=kubernetes`
**Proposed Solution:**
it has to be replaced with :
`yum install -y kubernetes-node` : on the worker nodes, and with
`yum install -y kubernetes-master` : on the master nodes
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by sftim** [comment]
Thanks for reporting this.

@outscale-nti can you confirm which RHEL / CentOS version(s) this revised command works on?

**Comment by outscale-nti** [comment]
Hello
I am sorry but this finally does not work.
I am closing the issue
best regards
