### ISSUE TITLE
Localize "Container Lifecycle Hooks" page to Italian

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes/website#20962]
I would like to have the "Container Lifecycle Hooks" page to be translated into Italian
page https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

/language it
/priority important-soon

**Comment by davideimola** [comment]
Hi @fabriziopandini, I am taking this issue! :smile: 

/assign
/lifecycle active

**Comment by fabriziopandini** [comment]
@davideimola this can help https://kubernetes.io/docs/contribute/ (you can find specific instructions for the web-site)
Ping me if you need help

**Comment by davideimola** [comment]
Hi @fabriziopandini, I have finished my issue!
PR #26740! 
Let me know!
