### ISSUE TITLE
broken link in concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#20970]
**This is a Bug Report**

There is a broken link in concepts/workloads/controllers/statefulset/

**Problem:**
This link is broken. The target page exists, but `#how-it-works` does not.
https://github.com/kubernetes/website/blob/991aadb64f986cc74d2f50d00d631fc430e567ea/content/en/docs/concepts/workloads/controllers/statefulset.md#L159

**Proposed Solution:**
Fix the broken link.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by sftim** [comment]
Looks like a bug alright
/kind bug
/priority backlog
/language en

**Comment by sftim** [comment]
/good-first-issue

Removing the `#how-it-works` should be enough of a fix, I think.

**Comment by divyabhushan** [comment]
Hi, @oke-py I would like to fix this bug. Could you assign this to me, please? Thanks

**Comment by sftim** [comment]
@divyabhushan please feel free to submit a PR with your proposed fix, assignment or no assignment. We'd welcome it!

**Comment by divyabhushan** [comment]
Thanks, @sftim. I will start working and submit PR.

**Comment by divyabhushan** [comment]
@sftim 
Problem: 
This link is broken. The target page exists, but #how-it-works does not.
Error in the page: /docs/concepts/workloads/controllers/statefulset.md
> https://github.com/kubernetes/website/blob/991aadb64f986cc74d2f50d00d631fc430e567ea/content/en/docs/concepts/workloads/controllers/statefulset.md#L159
> 

Solution: 
Removed the #how-it-works

Files modified:
content/en/docs/concepts/workloads/controllers/statefulset.md
content/es/docs/concepts/workloads/controllers/statefulset.md
content/id/docs/concepts/workloads/controllers/statefulset.md
content/ja/docs/concepts/workloads/controllers/statefulset.md
content/ko/docs/concepts/workloads/controllers/statefulset.md
content/zh/docs/concepts/workloads/controllers/statefulset.md
