### ISSUE TITLE
Broken layout on "kubeadm 클러스터 업그레이드" 

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#20991]
**This is a Bug Report**

**Problem:**
Broken layout on "kubeadm 클러스터 업그레이드" 

![image](https://user-images.githubusercontent.com/282159/82064529-dad24500-9707-11ea-9daf-dbcf83d1415c.png)

**Proposed Solution:**
Check and apply upstream changes.

**Page to Update:**
https://kubernetes.io/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

/language ko

**Comment by pjhwa** [comment]
/unassign

This issue already has assigned to @ysyukr .
