### ISSUE TITLE
Page layout docs/setup/production-environment/tools/kubeadm/high-availability/

### ISSUE THREAD

**Issue by lt-bbergen** [kubernetes/website#20992]
**This is a Bug Report**

Formatting is off (broken HTML rendering) on [this](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/) page since earlier this week (Wednesday sometime?) per my comment in #20912 - I'm adding as a separate ticket for tracking.

Some fixes to Hugo were made in #20946 and #20903 but the issues on this page are persisting.

**Problem:**
Seeing poor formatting and plaintext HTML due to some incorrect syntax on the page: 
![image](https://user-images.githubusercontent.com/65313036/82066334-e0427780-9694-11ea-89db-6b8c9f046d1e.png) - screenshot taken in FireFox, but replicated in Chromium (Brave) as well.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

Thank you!

[EDIT] heh - I switched GitHub accounts - the comments I was referring to were by my other account  @SudoBrendan

**Comment by neolit123** [comment]
thanks for the report.

cc @jimangel @sftim possibly caused by the hugo bump too?
/sig docs cluster-lifecycle
/kind bug

**Comment by prasadkatti** [comment]
Relates to tracking issue #20335

**Comment by tengqm** [comment]
This is almost fixed. There are some leftovers related to the ordered list.
/assign
