### ISSUE TITLE
Issue with k8s.io/fr/docs/setup/independent/control-plane-flags/

### ISSUE THREAD

**Issue by Cedric-2020** [kubernetes/website#20990]
Hello i would like to personalized my control point but it does not working : 
yaml : 
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
metadata:
  name: 1.13-sample
controllerManager:
  extraArgs:
    cluster-signing-key-file: /home/johndoe/keys/ca.key
    bind-address: 0.0.0.0
    deployment-controller-sync-period: 50

----
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:36:32Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Resultat : 
---
error: unable to recognize "kubeadm-config.yml": no matches for kind "ClusterConfiguration" in version "kubeadm.k8s.io/v1beta1"

What can i do ??

Thanks 
CEdric

**Comment by neolit123** [comment]
/triage support

hi,

> kubernetesVersion: v1.13.0

if you want to deploy a k8s version with kubeadm 1.18.1, then it must be 1.17 at minimum. kubeadm support deploying the same k8s version and one version older!

also <1.16 is out of support.

> error: unable to recognize "kubeadm-config.yml": no matches for kind "ClusterConfiguration" in version "kubeadm.k8s.io/v1beta1"

this is odd, 1.18.1 should not return this error. are you sure you are executing the 1.18.1 binary?

try this minimal config and see if it works.
```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.18.1
```

**Comment by sftim** [comment]
Let's update https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/ to make it clear what Kubernetes version you need to have to follow the page.

**Comment by neolit123** [comment]
IMO, it should link to:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#version-skew-policy

**Comment by sftim** [comment]
I'm not sure if we want to automate publishing the version number for latest Kubernetes into those YAML documents, or leave that for manual review. Both options are on the table.

**Comment by neolit123** [comment]
i think the version policy link should suffice. the `1.16` in the YAML is just a placeholder and i'm hoping users will know they have to pick the right version.

**Comment by MRostanski** [comment]
I have similar problem with v1.18.1

`$ cat minimal.yaml 
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.18.1
$ kubectl get nodes
NAME     STATUS   ROLES    AGE     VERSION
worker   Ready    <none>   6h35m   v1.18.1
$ kubectl apply -f minimal.yaml 
error: unable to recognize "minimal.yaml": no matches for kind "ClusterConfiguration" in version "kubeadm.k8s.io/v1beta1"`

**Comment by neolit123** [comment]
@MRostanski hi, you should not be applying the kubeadm "kind" called ClusterConfiguration with kubectl. it's a "kind" that should be fed to kubeadm using --config during the `kubeadm init` command.

https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1#hdr-Kubeadm_init_configuration_types
