### ISSUE TITLE
Translate /docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ into Japanese

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#21008]
**This is a Feature Request**

**What would you like to be added**
Translate /docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ into Japanese.

**Why is this needed**
This page has not been translated.

**Comments**
/language ja

**Comment by jlandowner** [comment]
Hi, can I try this issue?
