### ISSUE TITLE
Improvement for k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/

### ISSUE THREAD

**Issue by christbenhur** [kubernetes/website#21016]
Please add some example commands, if feasible.

I tried to renew the apiserver-etcd-client, with/without flags, but I see an error.
master $ kubeadm alpha certs renew apiserver-etcd-client
failed to renew certificate apiserver-etcd-client: unable to sign certificate: must specify at least one ExtKeyUsage
To see the stack trace of this error execute with --v=5 or higher

master $ kubeadm alpha certs renew apiserver-etcd-client --cert-dir "/etc/kubernetes/pki"
failed to renew certificate apiserver-etcd-client: unable to sign certificate: must specify at least one ExtKeyUsage
To see the stack trace of this error execute with --v=5 or higher

Thank you

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/priority awaiting-more-evidence

hi, this is an unexpected error.

please answer these questions:
- what are the contents of `sudo ls /etc/kubernetes/pki`?
- are there certificates in `/etc/kubernetes/pki` generated from an older kubeadm version, and which one? alternatively did you manually generate the `apiserver-etcd-client.crt`?
- what kubeadm version are you using to invoke renew?
- what is the output of:
`sudo openssl x509 -in /etc/kubernetes/pki/apiserver-etcd-client.crt -text`

**Comment by christbenhur** [comment]
Hi,
Please find the answers as following:
   
   - what are the contents of sudo ls /etc/kubernetes/pki?
            
            master $ sudo ls /etc/kubernetes/pki            apiserver.crt              apiserver-etcd-client.key     apiserver-kubelet-client.key  etcd                front-proxy-client.crt  sa.pub            apiserver-etcd-client.crt  apiserver.key                 ca.crt                        front-proxy-ca.crt  front-proxy-client.key            apiserver-etcd-client.csr  apiserver-kubelet-client.crt  ca.key                        front-proxy-ca.key  sa.key            
            
   
   - are there certificates in /etc/kubernetes/pki generated from an older kubeadm version, and which one? Ans: "No" alternatively did you manually generate the apiserver-etcd-client.crt? Ans: Seems to be "Yes", based on the file timestamp ("May 17 09:48") as shown below. Timestamp for the rest of the certificates was "May 17 09:20" . This is an automatically created practice environment. 
            
                    -rw-r--r-- 1 root root  948 May 17 09:48 apiserver-etcd-client.csr
                    drwxr-xr-x 2 root root 4096 May 17 09:48 etcd                    -rw-r--r-- 1 root root 1029 May 17 09:48 apiserver-etcd-client.crt      
       
   
   - what kubeadm version are you using to invoke renew?
             
            master $ kubeadm version -o yaml            clientVersion:              buildDate: "2019-09-18T14:34:01Z"              compiler: gc              gitCommit: 2bd9643cee5b3b3a5ecbd3af49d09018f0773c77              gitTreeState: clean              gitVersion: v1.16.0              goVersion: go1.12.9              major: "1"              minor: "16"              platform: linux/amd64

   
   - what is the output of:   
sudo openssl x509 -in /etc/kubernetes/pki/apiserver-etcd-client.crt -text

            master $ sudo openssl x509 -in /etc/kubernetes/pki/apiserver-etcd-client.crt -text            Certificate:                Data:                Version: 1 (0x0)                Serial Number: 12140484687171661295 (0xa87baa7ffbefadef)                Signature Algorithm: sha256WithRSAEncryption                    Issuer: CN=etcd-ca                    Validity                        Not Before: May 17 09:48:03 2020 GMT                        Not After : May  7 09:48:03 2020 GMT                    Subject: CN=kube-apiserver-etcd-client, O=system:masters                    Subject Public Key Info:                        Public Key Algorithm: rsaEncryption                            Public-Key: (2048 bit)                            Modulus:                                00:aa:3a:9f:4e:11:4a:13:d6:ed:69:94:7c:cb:60:                                3d:7d:a5:bd:66:6f:ac:ef:42:c5:50:47:e3:40:03:                                26:14:28:0d:dc:dc:af:45:d3:1b:60:90:f3:ba:64:                                79:10:0c:ed:bd:01:03:8e:f8:97:ae:15:08:39:b0:                                65:cd:8d:9c:0f:76:a6:e2:37:72:b3:ca:fc:a2:2b:                                2f:a8:1e:66:21:0d:97:c9:3a:bb:6c:a8:57:8b:01:                                89:00:e8:60:a5:95:29:7b:ba:a8:19:7d:8c:c2:9a:                                ae:16:70:40:99:ff:44:e8:10:c7:47:52:e5:4a:76:                                dc:0b:24:4a:c3:40:7e:41:a7:87:06:c3:11:39:39:                                e9:e3:bc:f8:76:ef:8d:91:8e:a9:c2:a0:94:c8:97:                                6b:d2:0d:d9:09:1a:6d:a5:92:84:3e:ad:75:a7:f6:                                97:22:c9:50:d6:6b:c7:a4:f7:a9:24:55:f4:4f:18:                                97:a3:62:cb:a3:e7:8d:aa:ab:7e:a1:fd:9f:81:70:                                fb:e8:de:09:36:0c:f7:aa:78:15:29:d4:07:20:8d:                                31:8c:1c:6e:81:3f:cc:5f:60:4a:2a:98:1f:b2:d4:                                73:e4:49:c1:52:f0:b9:c7:ba:27:f4:fd:c2:d6:63:                                76:9c:60:ef:bd:79:25:0f:c0:9b:5e:1a:65:9b:56:                                63:3f                            Exponent: 65537 (0x10001)                Signature Algorithm: sha256WithRSAEncryption                     7f:5f:1f:56:2d:62:1b:c7:81:9c:78:01:85:91:77:aa:0f:ab:                     f7:4a:c9:dd:d0:fa:08:be:e0:ba:2c:85:71:c6:97:d3:e1:18:                     42:ac:8e:71:6c:fa:0e:91:59:ba:4e:aa:7f:e1:38:20:6d:35:                     2d:52:7f:fa:f2:b7:f0:21:87:c1:20:cc:38:96:58:88:82:16:                     7a:dd:2c:fd:ec:48:09:7c:a9:cc:b0:1e:c4:45:b7:70:79:87:                     d8:16:3d:6e:09:24:90:de:94:67:c6:35:7b:69:03:23:60:b2:                     eb:b9:f8:49:01:14:94:ee:2a:a6:bd:3f:56:29:f8:18:ed:90:                     03:eb:c1:4f:54:f2:7d:12:a7:cc:59:fc:28:f3:cf:ca:ed:6a:                     a8:c6:e9:0c:d6:88:e3:6a:d7:36:56:b9:a5:c2:49:48:c1:a6:                     bc:e7:55:4e:61:30:79:ee:53:30:0a:9c:7a:e8:c3:b2:b2:ef:                     17:d1:c3:68:cd:03:46:81:0f:2d:87:ef:72:8b:64:b8:96:b2:                     43:66:bd:a4:a1:43:21:74:3e:0a:ad:9a:00:d3:02:c4:3f:53:                     ae:37:8d:3e:e6:6f:4f:7a:28:98:bd:c7:c4:96:dc:81:cc:04:                     46:b5:8d:a4:c0:b5:90:9b:4c:97:32:f3:f5:d8:ce:12:9b:40:                     7d:89:17:b3            -----BEGIN CERTIFICATE-----            MIICzDCCAbQCCQCoe6p/+++t7zANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDEwdl            dGNkLWNhMB4XDTIwMDUxNzA5NDgwM1oXDTIwMDUwNzA5NDgwM1owPjEjMCEGA1UE            Awwaa3ViZS1hcGlzZXJ2ZXItZXRjZC1jbGllbnQxFzAVBgNVBAoMDnN5c3RlbTpt            YXN0ZXJzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqjqfThFKE9bt            aZR8y2A9faW9Zm+s70LFUEfjQAMmFCgN3NyvRdMbYJDzumR5EAztvQEDjviXrhUI            ObBlzY2cD3am4jdys8r8oisvqB5mIQ2XyTq7bKhXiwGJAOhgpZUpe7qoGX2Mwpqu            FnBAmf9E6BDHR1LlSnbcCyRKw0B+QaeHBsMROTnp47z4du+NkY6pwqCUyJdr0g3Z            CRptpZKEPq11p/aXIslQ1mvHpPepJFX0TxiXo2LLo+eNqqt+of2fgXD76N4JNgz3            qngVKdQHII0xjBxugT/MX2BKKpgfstRz5EnBUvC5x7on9P3C1mN2nGDvvXklD8Cb            Xhplm1ZjPwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQB/Xx9WLWIbx4GceAGFkXeq            D6v3Ssnd0PoIvuC6LIVxxpfT4RhCrI5xbPoOkVm6Tqp/4TggbTUtUn/68rfwIYfB            IMw4lliIghZ63Sz97EgJfKnMsB7ERbdweYfYFj1uCSSQ3pRnxjV7aQMjYLLrufhJ            ARSU7iqmvT9WKfgY7ZAD68FPVPJ9EqfMWfwo88/K7WqoxukM1ojjatc2VrmlwklI            waa851VOYTB57lMwCpx66MOysu8X0cNozQNGgQ8th+9yi2S4lrJDZr2koUMhdD4K            rZoA0wLEP1OuN40+5m9PeiiYvcfEltyBzARGtY2kwLWQm0yXMvP12M4Sm0B9iRez            -----END CERTIFICATE-----

Additional information:

master $ kubeadm alpha certs check-expirationCERTIFICATE                EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGEDadmin.conf                 May 17, 2021 09:20 UTC   364d            noapiserver                  May 17, 2021 09:20 UTC   364d            noapiserver-etcd-client      May 07, 2020 09:48 UTC   <invalid>       noapiserver-kubelet-client   May 17, 2021 09:20 UTC   364d            nocontroller-manager.conf    May 17, 2021 09:20 UTC   364d            noetcd-healthcheck-client    May 17, 2021 09:20 UTC   364d            noetcd-peer                  May 17, 2021 09:20 UTC   364d            noetcd-server                May 17, 2021 09:20 UTC   364d            nofront-proxy-client         May 17, 2021 09:20 UTC   364d            noscheduler.conf             May 17, 2021 09:20 UTC   364d            no



master $ kubeadm alpha certs renew allcertificate embedded in the kubeconfig file for the admin to use and for kubeadm itself renewedcertificate for serving the Kubernetes API renewedfailed to renew certificate apiserver-etcd-client: unable to sign certificate: must specify at least one ExtKeyUsageTo see the stack trace of this error execute with --v=5 or higher
            
           
I issued renew commands for the rest of the certificates.
            

master $ kubeadm alpha certs renew apiserver-kubelet-clientcertificate for the API server to connect to kubelet renewedmaster $ kubeadm alpha certs renew controller-manager.confcertificate embedded in the kubeconfig file for the controller manager to use renewedmaster $ kubeadm alpha certs renew etcd-healthcheck-clientcertificate for liveness probes to healthcheck etcd renewedmaster $ kubeadm alpha certs renew etcd-peercertificate for etcd nodes to communicate with each other renewedmaster $ kubeadm alpha certs renew etcd-servercertificate for serving etcd renewedmaster $ kubeadm alpha certs renew front-proxy-clientcertificate for the front proxy client renewedmaster $ kubeadm alpha certs renew scheduler.confcertificate embedded in the kubeconfig file for the scheduler manager to use renewed


Thank you
    On Sunday, 17 May, 2020, 01:04:24 am IST, Lubomir I. Ivanov <notifications@github.com> wrote:  
 
 


/sig cluster-lifecycle
/priority awaiting-more-evidence

hi, this is an unexpected error.

please answer these questions:
   
   - what are the contents of sudo ls /etc/kubernetes/pki?
   - are there certificates in /etc/kubernetes/pki generated from an older kubeadm version, and which one? alternatively did you manually generate the apiserver-etcd-client.crt?
   - what kubeadm version are you using to invoke renew?
   - what is the output of:   
sudo openssl x509 -in /etc/kubernetes/pki/apiserver-etcd-client.crt -text

**Comment by neolit123** [comment]
> alternatively did you manually generate the apiserver-etcd-client.crt? Ans: Seems to be "Yes", based on the file timestamp ("May 17 09:48") as shown below. Timestamp for the rest of the certificates was "May 17 09:20" . This is an automatically created practice environment. 

that seems to cause for the problem.


> openssl x509 -in /etc/kubernetes/pki/apiserver-etcd-client.crt -

the formatting in your output is difficult to read, but the certificate must contain the following:

```
...
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Client Authentication
    Signature Algorithm: sha256WithRSAEncryption
...
```

i'm not seeing it in the output, so the error ("must specify at least one ExtKeyUsageTo") you are seeing is caused by a missing "TLS Web Client Authentication".

i recommend using the "kubeadm init phase certs..." command to generate certificates.

>  kubeadm version -o yaml 

it might be a good opportunity to move to a newer k8s version too.

thanks
/close

**Comment by christbenhur** [comment]
Thank you
