### ISSUE TITLE
Rendering issues on /docs/reference/access-authn-authz/rbac/#service-account-permissions

### ISSUE THREAD

**Issue by korney4eg** [kubernetes/website#21029]
**This is a Bug Report**

**Problem:**
[Page](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions) render has an error, here is a screenshot:
![image](https://user-images.githubusercontent.com/1872070/82153377-526ab600-9867-11ea-9b43-d436c4397ef9.png)

Source code seems to be fine :
https://github.com/kubernetes/website/blame/master/content/en/docs/reference/access-authn-authz/rbac.md#L1098-L1106
**Proposed Solution:**
N/A

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions

1.18

**Comment by korney4eg** [comment]
Hello @divyabhushan ,

As far as I can see the issue wasn't close.

Here is a link to preview.
https://deploy-preview-21033--kubernetes-io-master-staging.netlify.app/docs/reference/access-authn-authz/rbac/#service-account-permissions

**Comment by divyabhushan** [comment]
@korney4eg 
I am working on it.

**Comment by korney4eg** [comment]
@divyabhushan still reproducible on https://deploy-preview-21046--kubernetes-io-master-staging.netlify.app/docs/reference/access-authn-authz/rbac/#service-account-permissions

**Comment by divyabhushan** [comment]
> @divyabhushan still reproducible on https://deploy-preview-21046--kubernetes-io-master-staging.netlify.app/docs/reference/access-authn-authz/rbac/#service-account-permissions

@korney4eg thanks for your feedback.
Kindly refer to PR#21046 for the solution.

**Comment by korney4eg** [comment]
true, point (2) is fixed. Could you also please check out point (5) in the same paragraph?
![image](https://user-images.githubusercontent.com/1872070/82755142-06bd8c80-9dd2-11ea-9bab-8df3c9c55bdd.png)

**Comment by divyabhushan** [comment]
Hello @korney4eg 
Sure, I was waiting to make this change and was waiting for approval:
https://github.com/kubernetes/website/pull/21046
>Dear reviewers,
I would also like to edit/fix rendering issues in ->
point 5: Grant super-user access to all service accounts cluster-wide (strongly discouraged).
Should I merge the change in the same PR or create a separate PR?

Thanks.

**Comment by divyabhushan** [comment]
Hello @korney4eg , thanks for the review.

> Hello @divyabhushan ,
> true, point (2) is fixed. Could you also please check out point (5) in the same paragraph?
> ![image](https://user-images.githubusercontent.com/1872070/82755142-06bd8c80-9dd2-11ea-9bab-8df3c9c55bdd.png)

Done.
PR: [#21186](https://github.com/kubernetes/website/pull/21186)

/assign @korney4eg

**Comment by korney4eg** [comment]
looks great, @divyabhushan should I close this issue?

**Comment by divyabhushan** [comment]
@korney4eg yes, please. Thank you.

**Comment by korney4eg** [comment]
I see that PR closed it
