### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/

### ISSUE THREAD

**Issue by vtrippel** [kubernetes/website#21022]
**This is a Bug Report**

**Problem:** This page (https://kubernetes.io/docs/setup/production-environment/tools/) is blank. The title is "Bootstrapping clusters with kubeadm" but there is no text afterwards.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Aside / good news (everyone)! The switch to Docsy should help with this.

**Comment by tengqm** [comment]
Looks like Docsy did help in this space. Feel free to reopen if there other improvement requests.
/close
