### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by sbellan** [kubernetes/website#21040]
**This is a Bug Report**

**Problem:**
double hyphens being changed to –, causing commands to fail.
The commands are in the Installing section,
```
yum install -y kubelet kubeadm kubectl –disableexcludes=kubernetes

systemctl enable –now kubelet

```
**Proposed Solution:**
Not sure yet, in another place(sudo sysctl --system) in the same page it is working fine.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by neolit123** [comment]
confirmed, these flags use utf-8 8211 instead of `-`:

```
–disableexcludes
–now
```

@sbellan dod you want to send a PR to fix the problem.
/kind bug
/sig cluster-lifecycle

**Comment by neolit123** [comment]
this appears to be another case of Hugo converting `--` to unicode dashes?

the original source code has `--disableexcludes`
https://github.com/kubernetes/website/blame/master/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md#L208

but the render has:
`... –disableexcludes ...`
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

we had a couple of tickets logged for this in k/website and k/k:
https://github.com/kubernetes/kubernetes/issues/90158
https://github.com/kubernetes/website/issues/21071

/remove-help
/priority critical-urgent
/sig docs
cc @sftim @tengqm 
@kubernetes/sig-docs-en-owners 
please take a look.

**Comment by kbhawkey** [comment]
I previously logged, https://github.com/kubernetes/website/issues/20915.

**Comment by neolit123** [comment]
ack, let's close this ticket.
thanks

/close
