### ISSUE TITLE
Issue with k8s.io/docs/setup/learning-environment/minikube/

### ISSUE THREAD

**Issue by UlrichKnaack** [kubernetes/website#21049]
**This is a Bug Report**

**Problem:**
The link https://minikube.sigs.k8s.io/docs/start/macos/#upgrading-minikube isn't valid

**Proposed Solution:**
Supply valid link

**Page to Update:**  
https://kubernetes.io/docs/setup/learning-environment/minikube/

**Comment by sftim** [comment]
Thanks for reporting this
/kind bug
/language en
/priority backlog

**Comment by tengqm** [comment]
Solved.
/close
