### ISSUE TITLE
Issue with k8s.io/zh/docs/reference/command-line-tools-reference/kube-proxy/

### ISSUE THREAD

**Issue by JianmingXia** [kubernetes/website#21056]
markdown formatting：
![image](https://user-images.githubusercontent.com/9691577/82294592-f6c43800-99e0-11ea-8423-aa2dee9455bf.png)

**Comment by tengqm** [comment]
fix is on the way: https://github.com/kubernetes/website/pull/21011

**Comment by tengqm** [comment]
Done.
/close
