### ISSUE TITLE
Rendering issue on /docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node

### ISSUE THREAD

**Issue by korney4eg** [kubernetes/website#21052]
**This is a Bug Report**

**Problem:**
Page is not rendered properly
Here is screenshot:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/1872070/82260650-f46cca00-995d-11ea-9f50-48b6cf04957b.png">

**Proposed Solution:**
N/A
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node

1.18

**Comment by neolit123** [comment]
thanks for the report.

/sig docs cluster-lifecycle
cc @sftim @jimangel

**Comment by tengqm** [comment]
Yes, the page has too many "notes" callouts, but the rendering problem seems fixed. Please feel free to reopen if needed.
/close
