### ISSUE TITLE
how to see the .minikube file in linux Issue with k8s.io/docs/setup/learning-environment/minikube/

### ISSUE THREAD

**Issue by Vishal700-cmd** [kubernetes/website#21055]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @Vishal700-cmd 

Would you be willing to describe the bug you encountered?

**Comment by prasadkatti** [comment]
@Vishal700-cmd - `.minikube` is a directory, not a file. It should be located in your home directory. You can `cd` to it -
`$ cd ~/.minikube/`
/triage support
/close
