### ISSUE TITLE
Deprecated flags are recommended on k8s.io/docs/reference/scheduling/policies/

### ISSUE THREAD

**Issue by JoelColledge** [kubernetes/website#21051]
**This is a Bug Report**

**Problem:**

The documentation recommends configuring `kube-scheduler` with `--policy-config-file` or `--policy-configmap` which are [deprecated](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/).

> --policy-config-file string
>  DEPRECATED: file with scheduler policy configuration. This file is used if policy ConfigMap is not provided or --use-legacy-policy-config=true
> --policy-configmap string
>  DEPRECATED: name of the ConfigMap object that contains scheduler's policy configuration. It must exist in the system namespace before scheduler initialization if --use-legacy-policy-config=false. The config must be provided as the value of an element in 'Data' map with the key='policy.cfg'

**Proposed Solution:**

Replace the instructions with a solution which is not deprecated. I'm haven't yet been able to find out what the recommended solution is.

Alternative solution: If there is no viable recommended way to set the policy config, then open a ticket against `kube-scheduler` to remove the "DEPRECATED" marking.

**Page to Update:**
<https://kubernetes.io/docs/reference/scheduling/policies/>

**Comment by sftim** [comment]
It sounds like it might be OK to revise https://kubernetes.io/docs/reference/scheduling/policies/ to mark the whole topic as deprecated. That's appropriate if this kind of configuration is indeed deprecated; I have _not_ checked that.

**Comment by JoelColledge** [comment]
It looks like the topic isn't entirely deprecated, the way that the configuration is provided has just been changed radically. Something to do with a shift to "ComponentConfig".

See [here](https://stackoverflow.com/questions/47966440/how-to-create-a-config-file-for-kube-scheduler-to-use-by-the-config-argument?rq=1) for the new approach. And [here](https://gist.github.com/everpeace/3438a70b14cfd727b991541bceac5fcd) for an example config which shows how to set the policies via a file or ConfigMap, plus an example of how these policies are configured.

I haven't been able to find proper documentation for any of this yet. The `--config` format can be obtained with `--write-config-to` or by scraping it from [the go type](https://godoc.org/k8s.io/kubernetes/pkg/scheduler/apis/config#KubeSchedulerConfiguration). But this still doesn't show what format should be used for the policy. [This code](https://github.com/kubernetes/kubernetes/blob/7ba332a839c844ef4ba0191ddca2ce3601d283af/pkg/scheduler/algorithmprovider/registry.go#L77) seems to specify the default values for priority weights etc, but that doesn't seem to map to a format for the policy map.

Is there some general way of getting the cluster itself to tell me what format it expects and what plugins are available?

I haven't tried any of this out yet.

**Comment by JoelColledge** [comment]
> But this still doesn't show what format should be used for the policy.

Maybe the policy format is still [the one linked from the existing documentation](https://pkg.go.dev/k8s.io/kube-scheduler@v0.18.0/config/v1?tab=doc#Policy) and the available predicates and priorities are still the ones [documented](https://kubernetes.io/docs/reference/scheduling/policies/).

If that is the case, the only change needs to be adding documentation for how to refer to the policy config using `--config`.

**Comment by JoelColledge** [comment]
According to https://pkg.go.dev/k8s.io/kubernetes/pkg/scheduler/apis/config?tab=doc#KubeSchedulerConfiguration `AlgorithmSource` is being deprecated, and in a Slack conversation it was confirmed that the whole Predicates/Priorities approach is being deprecated in favor of the [Profiles/Plugins approach](https://kubernetes.io/docs/reference/scheduling/profiles/). So it seems that @sftim was right in suggesting that https://kubernetes.io/docs/reference/scheduling/policies/ as a whole should be marked deprecated.

That would resolve this issue. It still leaves me working on how to get the scheduler configured using the new approach.

**Comment by sftim** [comment]
So, it sounds like to resolve this issue it's enough to add a note to https://kubernetes.io/docs/reference/scheduling/policies/ to indicate that these policies are deprecated.

Have I got that right?

**Comment by gwohletz** [comment]
Likewise, all I really want to do is enable **MostRequestedPriority** but I'm at a loss on what the _right_ way to do this is without using these "deprecated" arguments/methods
