### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-service/

### ISSUE THREAD

**Issue by sharet-adl** [kubernetes/website#21066]
**This is a Bug Report**

**Problem:**
Sample with yaml code are not rendered properly.
Example:
- "Note: This is the same as if you had started the Deployment with the following YAML: ..."
![image](https://user-images.githubusercontent.com/57949742/82350211-b9bd6d00-9a03-11ea-81b1-d82bc1c5362e.png)
- "Note: As before, this is the same as if you had started the Service with YAML:"

Might be related to upgrade of the markdown parser - existing issue#20915 - https://github.com/kubernetes/website/issues/20915.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by sftim** [comment]
Relevant to issue #20335

**Comment by tengqm** [comment]
Fixed by #21390
/close
