### ISSUE TITLE
Issue with k8s.io/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by amitsaha** [kubernetes/website#21079]
**This is a Bug Report**

**Problem:**

Clarification on the wording related to the order of application of multiple matching policies. In the [section on policy order](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order), the first point is:

1. PodSecurityPolicies which allow the pod as-is, without changing defaults or mutating the pod, are preferred. The order of these non-mutating PodSecurityPolicies doesn’t matter.

**Proposed Solution:**

"The order of these non-mutating PodSecurityPolicies doesn’t matter." perhaps could be better
worded to imply "any of the non-mutated matching policies may be used" provided it satisfies
the permission checks.

**Page to Update:**

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order

**Comment by tengqm** [comment]
I do think the current text is more accurate.
