### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by shikha0208** [kubernetes/website#21095]
Issue description: 
While following all the steps in kubernetes document for connecting back-end to the front-end via service.

I get external IP as **localhost** instead of an IP.

Kindly clear me if anyone [knows.]

PFA
![image](https://user-images.githubusercontent.com/63613092/82509050-19e90780-9b07-11ea-9a5b-e48e85059d24.png)

**Comment by sftim** [comment]
This might be correct. Can you outline how you set up the cluster that you used to run through this task @shikha0208 ?

/triage needs-information

**Comment by shikha0208** [comment]
I was doing this in the local machine , not deployed in any cluster.I have to still deploy and i assumed i would get the external IP while port forwarding.
I will check after deployement.
