### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by chrisUsick** [kubernetes/website#21109]
**This is a Bug Report**

Hi, I couldn't find documentation for this anywhere. 

**Problem:**

There is no link to the KubletConfiguration type in the kubelet component documentation even though it states that all CLI flags are deprecated. 

**Proposed Solution:**

Add a link to the [goDoc type](https://godoc.org/k8s.io/kubelet/config/v1beta1#KubeletConfiguration) so that one can find the equivalent KubeletConfiguration options for the CLI options.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

Potentially KubeletConfiguration should also have documentation outside of goDocs as well.
Thanks,
Chris

**Comment by tengqm** [comment]
Yes. We'd like to have docs for kubelet config, scheduler config, etc, although the best we have at the moment is the goDocs.

**Comment by chrisUsick** [comment]
What do you think about adding 1 small paragraph to the synopsis of kubelet linking to the goDocs?

**Comment by tengqm** [comment]
@chrisUsick That is doable as a workaround.

**Comment by chrisUsick** [comment]
I see in the latest documentation update a link to [github](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go) was added to the docs. This is sufficient I think.
Thanks, closing issue.
