### ISSUE TITLE
cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory

### ISSUE THREAD

**Issue by anilkumarmd** [kubernetes/website#21105]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Kartik494** [comment]
i think this article should help https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by neolit123** [comment]
please use support channels for general help / questions, thanks.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/triage support
/close
