### ISSUE TITLE
Document workload controller revision resources

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#21129]
**This is a Feature Request**

**What would you like to be added?**
Add a concept page that documents [ControllerRevision](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#controllerrevision-v1-apps)

**Why is this needed?**
It's useful for readers to understand that resources like DaemonSet and StatefulSet support rollbacks using ControllerRevision, and that these revisions are actually represented as resources in the API.

**Kubernetes version:**
v1.18
/language en

**Comment by husnialhamdani** [comment]
This is not stale
