### ISSUE TITLE
Hyperlink issue on "Go to Certification" button on CKA course

### ISSUE THREAD

**Issue by bgopalakrishnan1986** [kubernetes/website#21126]
Hyperlink issue on "Go to Certification" button on CKA course

Page Link: https://kubernetes.io/training/

Github Link: https://github.com/kubernetes/website/blob/master/content/en/training/_index.html

We are missing a double quotes on the href value at the starting, due to that the link on the website has a unnecessary double quotes at the end, but it gets redirected correctly without any issues.

Wanted to mention, so that this small fix gets corrected before causing any trouble in future to anyone.

`  <div class="col-nav">
        <center>
          <h5>
            <b>Certified Kubernetes Administrator (CKA)</b>
          </h5>
          <p>The Certified Kubernetes Administrator (CKA) program provides assurance that CKAs have the skills, knowledge, and competency to perform the responsibilities of Kubernetes administrators.</p>
          <br>
          <a href=https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/" target="_blank" class="button">Go to Certification</a>
        </center>
      </div>`

Screenshot from the page with highlighted error part:
![image](https://user-images.githubusercontent.com/14248352/82640823-e2727c00-9c28-11ea-988d-a7f73f0c74d6.png)

**Comment by divyabhushan** [comment]
Hello @nikhita 
I would like to close this issue. Could you please mention the link to the issue transferred, as it doesn't show up in the Kubernetes/community 'issues' section.
Thanks.

**Comment by nikhita** [comment]
> I would like to close this issue.

@divyabhushan Has this issue been fixed or do you mean that you'd like to work on it? :)

> Could you please mention the link to the issue transferred, as it doesn't show up in the Kubernetes/community 'issues' section.

I transferred the issue using the [GitHub issue transfer feature](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository). This moves the issue from the kubernetes/community repo to the kuberntes/website repo directly, so it won't be visible in the issues list in the community repo. For a PR, referencing this issue directly would be sufficient.

**Comment by divyabhushan** [comment]
Thanks @nikhita 
/assign @divyabhushan

**Comment by sftim** [comment]
/close
Fixed in #21127

**Comment by bgopalakrishnan1986** [comment]
Thanks team, it was quick considering the issues and features, amazing.
