### ISSUE TITLE
Issue with k8s.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-reset/

### ISSUE THREAD

**Issue by MagikLau** [kubernetes/website#21138]
**This is a Bug Report**

**Problem:**
Web page elements look wrong.
![image](https://user-images.githubusercontent.com/22516902/82720440-48710900-9ce6-11ea-9db6-49f872df5201.png)

**Page to Update:**
https://kubernetes.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-reset/

**Comment by tengqm** [comment]
Fixed.
/close
