### ISSUE TITLE
Issue with k8s.io/docs/tasks/

### ISSUE THREAD

**Issue by neildcruz** [kubernetes/website#21149]
**This is a Bug Report**

**Problem:** The tasks page on the documentation site says _"This section of the Kubernetes documentation contains pages that show how to do individual tasks"_ But, none of the links lead to pages with any descriptions. They just have one-liners under the headers. I'm guessing there are some missing/broken links on this page.

**Comment by sftim** [comment]
Would it be OK to close this issue in favor of issue #8402?

**Comment by tengqm** [comment]
Let's track the problem using #8402.
/close
