### ISSUE TITLE
access control image not rendering on page

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#21147]
**This is a Bug Report**
The access control overview image on page, https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/, is not displaying.

```
https://d33wubrfki0l68.cloudfront.net/673dbafd771491a080c02c6de3fdd41b09623c90/50100/images/docs/admin/access-control-overview.svg
```

**Problem:**
Problem rendering image or missing image.

**Proposed Solution:**
Investigate if the image is available from remote site.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/

**Comment by sftim** [comment]
/kind bug

https://d33wubrfki0l68.cloudfront.net/673dbafd771491a080c02c6de3fdd41b09623c90/50100/images/docs/admin/access-control-overview.svg renders for me when I try to fetch it.

**Comment by sftim** [comment]
Also, https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/ renders OK.

Maybe this was a Netlify blip?

**Comment by kbhawkey** [comment]
Hi @sftim. Thanks for checking.
I tried again, but the image is not rendering for me.
Also tried to view the page from a mobile browser.

**Comment by prasadkatti** [comment]
Renders properly for me too on mobile.

**Comment by kbhawkey** [comment]
Here is how the image displays for me:

![access-auth-image-2](https://user-images.githubusercontent.com/1696019/83659332-61ed3d00-a591-11ea-9315-1db6ae49dd41.PNG)

**Comment by sftim** [comment]
Is that rendering wrong? What should we see?

**Comment by kbhawkey** [comment]
I am not familiar with the history of this image.
I guess this is what the image is supposed to look like?

**Comment by sftim** [comment]
I loaded it locally into an SVG editor and it looks almost the same there, very minor rendering differences only.
