### ISSUE TITLE
Review and tidy “Node-specific Volume Limits”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#21152]
**This is a clean up request**

**Problem:**
Node-specific volume limits are now implemented via dynamic volume limits; that is, or seems to be, the approach that all storage plugins should use in the future.

**Proposed Solution:**
- Revise this page to show dynamic volume limits as the stable and recommended implementation.
- Drop details of limits that are specific to cloud providers. If it's not feasible to drop those entirely, then rather than listing values hyperlink to a page with details (external to the Kubernetes website if feasible, in line with https://kubernetes.io/docs/contribute/style/content-guide/)

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/storage-limits/

**Additional Information:**
Relevant to #20232 (?)

/language en
/kind cleanup
/sig storage
/priority important-longterm

**Comment by riking** [comment]
The documentation should be rewritten from the viewpoint that the CSI driver's maximum volume count is the default / normal way for this to be handled, with in-tree cloud providers treated as an exception.
