### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/admission-controllers/

### ISSUE THREAD

**Issue by Leanneknott51** [kubernetes/website#21165]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @Leanneknott51 

Can you confirm what isn't right about https://k8s.io/docs/reference/access-authn-authz/admission-controllers/?

/triage needs-information
