### ISSUE TITLE
language selection menu in kubernetes.io is obscured

### ISSUE THREAD

**Issue by Ming9** [kubernetes/website#21171]
**This is a Bug Report**

**Problem: On the IE11, the language selection menu in kubenetes.io is obscured
- OS : Windows 10 Enterprise 64bit
-  IE version : 11,1488
![ie11_issue](https://user-images.githubusercontent.com/6326130/82770283-f4dff600-9e72-11ea-8d54-380304efa205.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Thanks for reporting this.
(I checked and Microsoft still [support Internet Explorer](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support) at version 11)

/priority backlog

**Comment by celestehorgan** [comment]
/close 

This is not an issue with the new layout.
