### ISSUE TITLE
Issue with --driver=none flag in k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by neilghosh** [kubernetes/website#21184]
**This is a Bug Report**

**Problem:**
The documentation for linux says 
--driver=none

**Proposed Solution:**
Correct command is (For Linux)
--vm-driver=none

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by sftim** [comment]
Hi @neilghosh 

Can you confirm what version of Minikube you're using? Older versions did use the command line option name `--vm-driver`.

**Comment by neilghosh** [comment]
I installed minikube from snap, version says
`minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278`

**Comment by sftim** [comment]
```
$ type minikube
minikube is /usr/bin/minikube
```
```
$ minikube start --driver=kvm2
😄  minikube v1.10.1 on Ubuntu 19.10
✨  Using the kvm2 driver based on user configuration
💿  Downloading VM boot image ...
    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.10.0.iso: 174.99 MiB / 174.99 MiB [] 100.00% 28.29 MiB p/s 6s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.2 preload ...
…
```

`--driver` works for me.

**Comment by RA489** [comment]
@neilghosh Minikube has deprecated `--vm-driver=none` option. You can now use `--driver=none` for your current minikube version. If you don't minikube can you please provide exact command line used.

**Comment by tengqm** [comment]
Sounds nothing needs a fix. Feel free to reopen if there IS an issue.
/close
