### ISSUE TITLE
Issue with k8s.io/docs/reference/using-api/api-overview/

### ISSUE THREAD

**Issue by sonogithub** [kubernetes/website#21180]
**This is a Bug Report**

Doc bug referring to https://kubernetes.io/docs/reference/using-api/api-overview/

The page at  about 1/2 way down has a note with a link to github:
_"Note: The API versioning and software versioning are indirectly related. The API and release versioning proposal describes the relationship between API versioning and software versioning."_

The link referenced in the note points to https://git.k8s.io/community/contributors/design-proposals/release/versioning.md

That page has nothing about the relationship between api versions and kubernetes versioning.
**Page to Update:**
https://kubernetes.io/docs/reference/using-api/api-overview/

**Comment by sftim** [comment]
That seems valid
/kind bug
/priority backlog

**Comment by KilimAnnejaro** [comment]
The same problem occurs on this page: https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-versioning
