### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by bartier** [kubernetes/website#21212]
**This is a Bug Report**

**Problem:**

Following the [hello-minikube tutorial](https://kubernetes.io/docs/tutorials/hello-minikube/) with Katacoda, I was not able to run the following command:

```
$ minikube addons disable metrics-server
*
X disable failed: running callbacks: [addon apply: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.17.3/kubectl delete -f /etc/kubernetes/addons/metrics-apiservice.yaml -f /etc/kubernetes/addons/metrics-server-deployment.yaml -f /etc/kubernetes/addons/metrics-server-service.yaml: exit status 1
stdout:

stderr:
the path "/etc/kubernetes/addons/metrics-apiservice.yaml" does not exist
the path "/etc/kubernetes/addons/metrics-server-deployment.yaml" does not exist
the path "/etc/kubernetes/addons/metrics-server-service.yaml" does not exist
]
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

I executed all the commands in the order presented on the page.

**Proposed Solution:** It looks like some files should be in `/etc/kubernetes/addons` to fix this.

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@BenHall this might be relevant to you

**Comment by RA489** [comment]
@bartier I executed for me successfully on KataKoda environment.

$ `minikube addons enable metrics-server`
* The 'metrics-server' addon is enabled
$ `minikube addons disable metrics-server`
* "The 'metrics-server' addon is disabled
$ `minikube addons list`
|-----------------------------|----------|--------------|
|         ADDON NAME          | PROFILE  |    STATUS    |
|-----------------------------|----------|--------------|
| dashboard                   | minikube | enabled ✅   |
| default-storageclass        | minikube | enabled ✅   |
| efk                         | minikube | disabled     |
| freshpod                    | minikube | disabled     |
| gvisor                      | minikube | disabled     |
| helm-tiller                 | minikube | disabled     |
| ingress                     | minikube | disabled     |
| ingress-dns                 | minikube | disabled     |
| istio                       | minikube | disabled     |
| istio-provisioner           | minikube | disabled     |
| logviewer                   | minikube | disabled     |
| metrics-server              | minikube | disabled     |
| nvidia-driver-installer     | minikube | disabled     |
| nvidia-gpu-device-plugin    | minikube | disabled     |
| registry                    | minikube | disabled     |
| registry-creds              | minikube | disabled     |
| storage-provisioner         | minikube | enabled ✅   |
| storage-provisioner-gluster | minikube | disabled     |
|-----------------------------|----------|--------------|

**Comment by RA489** [comment]
@bartier Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by bartier** [comment]
@RA489 I tested today again and got success. Guess They've updated the VM config or something else in this meantime. 

I'll close this issue since the scenario is not reproduceble anymore. 

Thanks!
