### ISSUE TITLE
clean up prior versions of api reference

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#21213]
**This is a Feature Request**
The docs maintains a number of copies of the API reference per version.
For instance, v1.18 has directories with API reference content for:
v1.10, v1.11, v1.12, v.1.13, v1.14, v1.15, v1.16, v1.17, v1.18

After removing this content, the docs should refer to any previous API references
by linking to the snapshot version of the reference.
This will help maintain the docs and keep the content current.

**What would you like to be added**
Clean up previous versions of the API reference docs in v.1.18.
Clean up any links to former API reference versions in the docs.
If a page needs to link to a previous version of the API reference, link to the
snapshot version of the reference.

**Why is this needed**
This will reduce the need to maintain the directories per version.
Only maintain one version of the API reference per version.

**Comments**
`\website\static\docs\reference\generated\kubernetes-api`

**Comment by tengqm** [comment]
Done.
/close
