### ISSUE TITLE
The page history site doesn't match the localization.

### ISSUE THREAD

**Issue by Lonor** [kubernetes/website#21230]
**This is a Bug Report**

**Problem:**
The page history link to GitHub doesn't match the localization language verison. All the links are linked to the en version.

**Proposed Solution:**
Update the [layouts/partials/git-info.html](https://github.com/kubernetes/website/blob/master/layouts/partials/git-info.html) by using `{{ site.Language.Lang }}` in the link of the page history.

**Page to Update:**
All pages contain this partial.

**Comment by sftim** [comment]
You're right about this
/kind cleanup
/priority important-longterm

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/21231
/close
