### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-gpus/scheduling-gpus/

### ISSUE THREAD

**Issue by dwschulze** [kubernetes/website#21246]
**This is a Bug Report**

Docs say "The version of the NVIDIA drivers must match the constraint ~= 361.93"

The NVidia legacy drivers go from 340.xx to 390.xx with nothing from the 360 family.  Will this device plugin work with 390.xx or later?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by tengqm** [comment]
Fixed by #21379 
/close
