### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/basic-stateful-set/

### ISSUE THREAD

**Issue by VikasBains** [kubernetes/website#21240]
Following the document under https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-statefulsets

Under **"Rolling Update"** section it is said to:
*Patch the `web` StatefulSet to apply the `RollingUpdate` update strategy.*
The snippet shows that statefulset has been patched. 
However, I do NOT see it to be modified to anything else earlier in the documentation. Therefore, `updateStrategy` should have been of default value, i.e. `RollingUpdate`

Now, when we change the container image in statefulset, it should update it and not be the previous container image.

*Before patching statefulset.*
```
GC02V81JZHTD6E:web vikasbains$ for p in 0 1 2; do kubectl get po web-$p --template '{{range $i, $c := .spec.containers}}{{$c.image}}{{end}}'; echo; done
k8s.gcr.io/nginx-slim:0.8
k8s.gcr.io/nginx-slim:0.8
k8s.gcr.io/nginx-slim:0.8
```
*Updating `updateStrategy` will not do anything, already set to default value.*
```
GC02V81JZHTD6E:web vikasbains$ kubectl patch statefulset web -p '{"spec":{"updateStrategy":{"type":"RollingUpdate"}}}'
statefulset.apps/web patched (no change)
```
*Updating the image. This will recreate the pods with new image we updated.*
```
GC02V81JZHTD6E:web vikasbains$ kubectl patch statefulset web --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"gcr.io/google_containers/nginx-slim:0.8"}]'
statefulset.apps/web patched
```
*Pods image has been updated (and is NOT the previous image).*
```
GC02V81JZHTD6E:web vikasbains$ for p in 0 1 2; do kubectl get po web-$p --template '{{range $i, $c := .spec.containers}}{{$c.image}}{{end}}'; echo; done
gcr.io/google_containers/nginx-slim:0.8
gcr.io/google_containers/nginx-slim:0.8
gcr.io/google_containers/nginx-slim:0.8
```

**Comment by VikasBains** [comment]
Please correct me if I am wrong.

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#statefulsetupdatestrategy-v1-apps confirms that the default update strategy is now `RollingUpdate`

I presume that long enough ago there was a different default.
/kind bug
/language en
/priority important-longterm

**Comment by tengqm** [comment]
Please check if [this PR](https://github.com/kubernetes/website/pull/21372) is what you wanted.
