### ISSUE TITLE
kubeadm reference pages Synopsis header not rendered correctly in v1.18 of reference docs

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/website#21250]
**This is a Bug Report**

**Problem:**
When viewing kubeadm pages in the v1.18 reference docs, the "Synopsis" heading is not generated and instead, the following is shown:
```
<h3 id="synopsis">Synopsis</h3>
```
![synopsis](https://user-images.githubusercontent.com/4977542/83076276-4048fe80-a043-11ea-8267-5ad63ac59974.png)

I think the synopsis text is rendering, just the header is not

**Proposed Solution:**
Fix page rendering

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/
...
etc (all of the kubeadm reference pages)

**Kubernetes Version**
1.18.  Earlier versions of the reference (1.17 and earlier) do not seem to have this problem.

**Comment by neolit123** [comment]
/sig cluster-lifecycle docs
/priority important-soon
cc @tengqm @sftim

**Comment by kbhawkey** [comment]
Hi @brianpursley .
Yes, this is a result of the recent Markdown parser switch.

**Comment by sftim** [comment]
Relevant to issue #20335 

I'd have put this one as priority important-longterm; the bug is only cosmetic.

**Comment by brianpursley** [comment]
Agreed, it is not a major issue. I was just reading the kubeadm docs and noticed it. Feel free to close if this is tracked elsewhere.

**Comment by sftim** [comment]
BTW #20335 is an umbrella issue

**Comment by tengqm** [comment]
I believe the mentioned pages are all fixed. Please feel free to reopen if there are still such issues.
/close
