### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/secret/

### ISSUE THREAD

**Issue by xocolatl-aficionado** [kubernetes/website#21255]
**This is a Bug Report**

**Problem:**
Are you sure [the Consuming Secret values from volumes section ](https://kubernetes.io/docs/concepts/configuration/secret/#consuming-secret-values-from-volumes) is correct? They said the secret values are stored as base64 encoded data within the files, but the kubectl exec + cat is shown to result in an actual string for username and a non-base64 encoded value for password.  
**Proposed Solution:**
I think they meant to write that the output expected is YWRtaW4= when `cat`ing into username
  and MWYyZDFlMmU2N2Rm when `cat`ing into password
**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/secret

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/configuration/secret/#consuming-secret-values-from-volumes looks correct to me.
Can you clarify the sentence where you think the text on the page is not correct @xocolatl-aficionado ?

**Comment by xocolatl-aficionado** [comment]
@sftim Upon looking into the contents of the password files username.txt and password.txt, don’t we expect to see base64 encoded strings like YWRtaW4=  and MWYyZDFlMmU2N2Rm? Instead the doc says its shows admin and an octal number, if i’m not wrong.

**Comment by sftim** [comment]
I don't expect to see base64 encoded strings in the files inside the container. The base64 encoding is a detail on the control plane side of things.
