### ISSUE TITLE
Change the words for limit/request on the glossary

### ISSUE THREAD

**Issue by pjhwa** [kubernetes/website#21266]
**This is a Bug Report**

**Problem:**
용어집에 등록되어있는 `limit` / `request` 의 번역에 대해 논의가 필요합니다.
- 문장 내에서 쓰일 때 번역된 '상한'과 '요청량'이 어색하다는 의견이 있습니다.

English | 한글
-- | -- 
Default Limit | 기본 상한
Default Request | 기본 요청량
max limit/request ratio | 최대 상한/요청량 비율
Resource Limit | 리소스 상한

**Proposed Solution:**
`limit` / `request` 는 각각 '제한' 과 '요청' 으로 번역하고,
독자의 이해를 돕기 위해 문서 내에서 처음 사용될 때 한영병기 하는 것을 권장하는 것이 좋을 것 같습니다.
- LimitRange 등의 API 오브젝트의 속성으로 쓰일 경우 yaml 파일 내의 표기를 참고하기 위함

English | 한글 | 비고
-- | -- | --
Default Limit | 기본 제한 |
Default Request | 기본 요청 |
max limit/request ratio | 최대 제한/요청 비율 |
Resource Limit | 리소스 제한 |
limit | 제한 | ResourceQuota, LimitRange 등의 오브젝트 속성으로 쓰이는 경우를 위해 한영병기를 권장
request | 요청 | ResourceQuota, LimitRange 등의 오브젝트 속성으로 쓰이는 경우를 위해 한영병기를 권장

**Page to Update:**
https://kubernetes.io/ko/docs/contribute/localization_ko/#한글화-용어집

/language ko

**Comment by jmyung** [comment]
의견 드립니다.

- before : LimitRange의 속성으로 쓰이는 등의 경우를 위해 한영병기를 권장
- after : ResourceQuota, LimitRange 등의 오브젝트 속성으로  쓰이는 경우를 위해 한영병기를 권장

참고로 LimitRange 외에 ResourceQuota 에도 사용되고 있습니다.
