### ISSUE TITLE
Issue with k8s.io/zh/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by hby07** [kubernetes/website#21263]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

Linux下载安装minikube步骤不完整，没有下载步骤。

**Comment by tengqm** [comment]
pls instead open an issue for English content. The Chinese page is only a translation.
/close

**Comment by tengqm** [comment]
btw, the following step is  the download step:

> curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
