### ISSUE TITLE
Issue with k8s.io/zh/docs/concepts/scheduling-eviction/scheduler-perf-tuning/

### ISSUE THREAD

**Issue by Vstural** [kubernetes/website#21285]
**This is a Bug Report**

**Problem:**
click link in page [调度器如何遍历节点](https://kubernetes.io/zh/docs/concepts/scheduling-eviction/scheduler-perf-tuning/#how-the-scheduler-iterates-over-nodes) not jump to target content

**Proposed Solution:**
simply change the url from
```
https://kubernetes.io/zh/docs/concepts/scheduling-eviction/scheduler-perf-tuning/#how-the-scheduler-iterates-over-nodes
```
to
```
https://kubernetes.io/zh/docs/concepts/scheduling-eviction/scheduler-perf-tuning/#%E8%B0%83%E5%BA%A6%E5%99%A8%E5%81%9A%E8%B0%83%E5%BA%A6%E9%80%89%E6%8B%A9%E7%9A%84%E6%97%B6%E5%80%99%E5%A6%82%E4%BD%95%E8%A6%86%E7%9B%96%E6%89%80%E6%9C%89%E7%9A%84-node
```
or jump to en version

**Page to Update:**
https://kubernetes.io/...

**Comment by zhiguo-lu** [comment]
this issue has  been fixed by @tengqm‘s  commit 8d7fd3f "[zh] Fix links in concepts section"
/close it
