### ISSUE TITLE
ja: Make glossary/kube-controller-manager.md follow v1.17 of the original text

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#21299]
**This is a Feature Request**

**What would you like to be added**
Update glossary/kube-controller-manager.md to follow v1.17 of the original (Englist) text.

**Why is this needed**
content/ja/docs/reference/glossary/kube-controller-manager.md it outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/reference/glossary/kube-controller-manager.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/reference/glossary/kube-controller-manager.md

diff between translated and v1.17
https://gist.github.com/oke-py/381275bef20a2d3b403f3edef7e8e57c

**Note**
Currently, we use `dev-1.17-ja.2` branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us here or slack.k8s.io #kubernetes-docs-ja channel.

**Comment by jlandowner** [comment]
Hi, can I pick this issue?

**Comment by oke-py** [comment]
Of cource. Thanks.
Please comment `/assign` to assign this issue to you.
