### ISSUE TITLE
Issue with k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by akanso** [kubernetes/website#21347]
**This is a Bug Report**

**Problem:**

showing an html header on the page: 

<h3 id="synopsis">Synopsis</h3>

**Comment by neolit123** [comment]
i think there was a fix for this in flight.

/sig docs cluster-lifecycle
/kind bug

**Comment by tengqm** [comment]
It's gone, I believe.
/close
