### ISSUE TITLE
Issue with k8s.io/fr/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by Dunoyer** [kubernetes/website#21343]
**This is a Bug Report**

**Problem:**
kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

don't work !

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Kartik494** [comment]
Hi @Dunoyer, can i know the error you got while performing this.I got expected output in my enviorment.
