### ISSUE TITLE
Wrong Feature Gate Name

### ISSUE THREAD

**Issue by WoodProgrammer** [kubernetes/website#21357]
Hello,
In secrets page of kubernetes, there is a wrong Feature Gate name written on the documentation.
I think it should be `ImmutableEphemeralVolumes` instead of `ImmutableEmphemeralVolumes`.

Because there is no feature gate with this name as mentioned on documentation.

Link of the documentation : https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by sftim** [comment]
I don't see a match for “Immutable EmphemeralVolumes” on the page https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by sftim** [comment]
Because of the confusion, I'm going to
/remove-good-first-issue
/triage needs-information
/remove-help

**Comment by WoodProgrammer** [comment]
@sftim, you should search by `ImmutableEmphemeralVolumes ` I think, remove the space between words.

thanks

**Comment by sftim** [comment]
If you look at https://github.com/kubernetes/website/blame/master/content/en/docs/concepts/configuration/secret.md @WoodProgrammer, can you identify the line that is wrong?

**Comment by prasadkatti** [comment]
@sftim - I think he is talking about https://github.com/kubernetes/website/blame/master/content/en/docs/concepts/configuration/secret.md#L728

**Comment by prasadkatti** [comment]
So this is really just about fixing a single typo. So it should be a good first issue, IMO.

**Comment by sftim** [comment]
I'm going to edit the issue description to take out some whitespace that was confusing me. @WoodProgrammer hope that's OK.

**Comment by WoodProgrammer** [comment]
Yes it is, I made a simple typo on my issue description.

**Comment by tengqm** [comment]
Fixed by #21592
/close
