### ISSUE TITLE
clarify the location of default.conf

### ISSUE THREAD

**Issue by mokua** [kubernetes/website#21360]
**This is a Feature Request**

**What would you like to be added**

In this command: kubectl create configmap nginxconfigmap --from-file=default.conf it is not very clear when following the manual steps that the file default.conf refers to nginx config file to be obtained from the repository https://github.com/kubernetes/examples/blob/master/staging/https-nginx/default.conf.

**Why is this needed**
When following the manual process, you might skip this step of creating the config map and the secure service will fail.

**Comments**

**Comment by prasadkatti** [comment]
Hi @mokua. Thanks for reporting the issue. Can you please add a link to the page the needs to be updated?

**Comment by mokua** [comment]
hi @prasadkatti. Here is the link https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
Then search for default.conf

**Comment by tengqm** [comment]
> You can acquire all these from the [nginx https example](https://github.com/kubernetes/examples/tree/master/staging/https-nginx/). 

If you have closely followed the manual, you will see where the `default.conf` file comes from.

/close
