### ISSUE TITLE
ja: Make tutorials/stateless-application/expose-external-ip-address.md follow v1.17 of the original text

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#21367]
**This is a Feature Request**

**What would you like to be added**
Update tutorials/stateless-application/expose-external-ip-address.md to follow v1.17 of the original (Englist) text.

**Why is this needed**
content/ja/docs/tutorials/stateless-application/expose-external-ip-address.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/tutorials/stateless-application/expose-external-ip-address.md

https://kubernetes.io/ja/docs/tutorials/stateless-application/expose-external-ip-address/

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/tutorials/stateless-application/expose-external-ip-address.md

https://v1-17.docs.kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

diff between translated and v1.17
https://gist.github.com/oke-py/d6592eae1a742bc61623eb94f0adc117

**Note**
Currently, we use `dev-1.17-ja.2` branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
来週1.17-ja.2ブランチをmasterに取り込む予定のため、今週末にPull Requestが出なさそうであれば一旦assignをはず扨せていただきます。
よろしくお願いしします！

**Comment by ryok-0319** [comment]
すみません、遅くなりましたがこちら今からやります

**Comment by ryok-0319** [comment]
PR作成完了しました

**Comment by inductor** [comment]
@ryok-0319 迅速な対応ありがとうございます！！
