### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-service/

### ISSUE THREAD

**Issue by tringuyen-yw** [kubernetes/website#21388]
**This is a Bug Report**

**Problem:**
**ISSUE 1**: There are two YAML outputs which are displayed as a continuous single line

```
apiVersion: apps/v1 kind: Deployment metadata: labels: app: hostnames name: hostnames spec: selector: matchLabels: app: hostnames replicas: 3 template: metadata: labels: app: hostnames spec: containers: - name: hostnames image: k8s.gcr.io/serve_hostname
```
and also
```
apiVersion: v1 kind: Service metadata: labels: app: hostnames name: hostnames spec: selector: app: hostnames ports: - name: default protocol: TCP port: 80 targetPort: 9376
```
**ISSUE 2**: The `alpine` image suggested in the page `kubectl run -it --rm --restart=Never alpine --image=alpine sh` seems to have some troubles with `nslookup`.  It succeeds to resolve `nslookup hostnames` and the fully qualified name `nslookup hostnames.default.svc.cluster.local`. Although with some unnecessary warning "server can't find xxx: NXDOMAIN"
 
```
/ # cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.152.183.10
options ndots:5

/ # nslookup hostnames
Server:		10.152.183.10
Address:	10.152.183.10:53
** server can't find hostnames.svc.cluster.local: NXDOMAIN
** server can't find hostnames.cluster.local: NXDOMAIN

Name:	hostnames.default.svc.cluster.local
Address: 10.152.183.195

** server can't find hostnames.svc.cluster.local: NXDOMAIN
** server can't find hostnames.cluster.local: NXDOMAIN

/ # nslookup hostnames.default.svc.cluster.local
Server:		10.152.183.10
Address:	10.152.183.10:53

Name:	hostnames.default.svc.cluster.local
Address: 10.152.183.195
``` 

However, it FAILS to resolve relative name `nslookup hostnames.default`
```
/ # nslookup hostnames.default
Server:		10.152.183.10
Address:	10.152.183.10:53

** server can't find hostnames.default: NXDOMAIN
** server can't find hostnames.default: NXDOMAIN
```

**Proposed Solution:**
1. Display the YAML in correct format

2. Replace the alpine image by this image to have better net tools (nslookup, curl is also available). All nslookup example works exactly as shown in the page. Including the clean output (without any "server can't find xxx: NXDOMAIN")
```
$ kubectl run -it --rm --restart=Never minibusy --image=radial/busyboxplus:curl
```
Please note the `radial/busyboxplus:curl` image suggested above is used in this Kubernetes doc page [Connecting Applications with Services](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/)

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by sftim** [comment]
I think the markup rendering bug was related to issue #20335

**Comment by sftim** [comment]
This issue was really 2 issues. I've split the remaining piece into #21436.
/close
