### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

### ISSUE THREAD

**Issue by mokua** [kubernetes/website#21383]
**This is a Bug Report**

**Problem:**
When the status of the pod is Completed, the command below does not work:

kubectl exec hostaliases-pod -- cat /etc/hosts

With the error : 
error: cannot exec into a container in a completed pod; current phase is Succeeded

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

v1.18.3

**Comment by Kartik494** [comment]
@mokua i am not certain about this but we can't exec into a pod which is completed.There is a [issue](https://github.com/kubernetes/kubernetes/issues/56841) regarding this feature to be implemented .But cant find any updates there.

**Comment by tengqm** [comment]
Fixed.
/close
