### ISSUE TITLE
The table on the Chinese page shows the source code

### ISSUE THREAD

**Issue by atlanmatrix** [kubernetes/website#21392]
**This is a Bug Report**

**Problem:**
The table on the Chinese page shows the source code

**Proposed Solution:**
I think that may be ~~an escaping issue~~ caused by illegal blank lines

**Page to Update:**
https://kubernetes.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-init/#%E9%80%89%E9%A1%B9

**Comment by tengqm** [comment]
This has nothing to do with blank lines. They are due to some issues with the markdown engine we use now.
The said problem is being fixed with #21234.
/close
