### ISSUE TITLE
Getting Started Kubernetes Page Links for Prod and Learning Environments Do Not Work

### ISSUE THREAD

**Issue by ParthSareen** [kubernetes/website#21409]
**This is a Bug Report**

**Problem:**
Getting Started Kubernetes Page Links for Prod and Learning Environments Do Not Work
**Proposed Solution:**
The link when clicked on is: https://kubernetes.io/docs/setup/#learning-environment
Same with https://kubernetes.io/docs/setup/#production-environment
![Screen Shot 2020-06-01 at 5 06 01 PM](https://user-images.githubusercontent.com/29360864/83454428-2d12a600-a42a-11ea-92bc-b22fb442d1e4.png)

it should not have the '#' symbol, and the issue will be resolved
**Page to Update:**
https://kubernetes.io/...

**Comment by prasadkatti** [comment]
I think this is working as expected. The `#` symbol can be used to link to a section within the page, so that the browser jumps down to that section after the page loads.

**Comment by sftim** [comment]
Some sites use a CSS animation to highlight the visited fragment. We could do that?
For example, set the heading text to Kubernetes blue and then fade it to black.

What do people think? (if selecting that, I'd start a new issue to track that work).

**Comment by ParthSareen** [comment]
> I think this is working as expected. The `#` symbol can be used to link to a section within the page, so that the browser jumps down to that section after the page loads.

That's what I thought at first, however, it doesn't jump down as these items are not on the same page

**Comment by sftim** [comment]
@ParthSareen does [on `:target`](https://css-tricks.com/on-target/) explain what is happening here? It also provides context for the tweak I suggested.

https://css-tricks.com/on-target/#article-header-id-2 is specifically about the jumping or lack of it.

**Comment by ParthSareen** [comment]
@sftim I think that makes sense.
