### ISSUE TITLE
Improvement for k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/

### ISSUE THREAD

**Issue by medined** [kubernetes/website#21404]
What is the range for the "number for the log level verbosity"?

**Comment by tengqm** [comment]
According to #21202 comments:

> there is no real limit. Currently in k/k/ codebase is between 0-12.
> Outside of guide https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md (which looks outdated) there is no other documented meaning between verbosity levels. Guide only accounts for 0-5, but there are still around 200 log calls with verbosity between 6-12.

So it is really difficult to precisely document this.

**Comment by medined** [comment]
Maybe a legitimate beginner task might be to standardize log level somehow?

**Comment by serathius** [comment]
Proposing and defining standard log levels is definitely not an easy task.

One of the designs of current V-levels is lack of semantics. It uses more relative importance (e.g. HTTP 403 is more important then HTTP 200) then global one (something is either ERROR,WARNING or INFO). This gives user a very fine grain control over log volume. 

Still we are definitely lacking in documentation of verbosity. We should make sure that users not familiar with klog, can easily understand our model and pick verbosity for themselfs.
/cc @thockin @DirectXMan12

**Comment by tengqm** [comment]
ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
