### ISSUE TITLE
Document container runtime setup for RHEL 8 / CentOS 8

### ISSUE THREAD

**Issue by yfstein** [kubernetes/website#21422]
**This is a Bug Report**

**Problem:**
Cant install containerd.io-1.2.13, docker-ce-19.03.8 and docker-ce-cli-19.03.8 on CentOS 8

**Proposed Solution:**
Compatibility check for the CentOS Docker setup commands for CentOS-8

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

Kubernetes Version:
-not installed yet

Additional Information:
A workaround/info which packages also supported for kubernetes and CentOS 8 until the page is updated would be nice

**Comment by sftim** [comment]
Hi @yfstein 

I'm not sure that I can see a bug in that page, exactly. Are you asking for someone to add documentation for how to set up a container runtime on RHEL 8 / CentOS 8?

This is tangentially
/sig cluster-lifecycle

but really the volunteer effort here is likely to come from the IBM / RHEL / CentOS world more than from the Kubernetes project itself.

If anyone would like to document those steps, that sounds fine by me.

**Comment by yfstein** [comment]
Hey @sftim,

i just have read and thought that its would be the same as for CentOS 8, cauz it was a "RHEL/CentOS 7.4 +" step-list.

But sure, it would be nice if someone could add the steps for CentOS 8 so you can see it as feature request. But for the first, we would use CRI-O.

**Comment by sftim** [comment]
Ah that makes sense. It's a bug because “RHEL/CentOS 7.4 +” isn't clear about what versions range tape applies to, and it's also a feature request because it would be great to document this for RHEL / CentOS 8.x

**Comment by sftim** [comment]
/retitle Document container runtime setup for RHEL 8 / CentOS 8

**Comment by neolit123** [comment]
in the most recent version of the container-runtime page we started linking to the external docker install page:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

it includes a matrix for different distributions:
https://docs.docker.com/engine/install/#server

this allows us to not maintain local documentation steps for installing docker or containerd.
/close
