### ISSUE TITLE
Improve tools for cluster debugging task

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#21436]
**This is a Bug Report**

Split from issue #21388

**Problem:**

The `alpine` image suggested in the page `kubectl run -it --rm --restart=Never alpine --image=alpine sh` seems to have some troubles with `nslookup`.  It succeeds to resolve `nslookup hostnames` and the fully qualified name `nslookup hostnames.default.svc.cluster.local`. Although with some unnecessary warning "server can't find xxx: NXDOMAIN"
 
```
/ # cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.152.183.10
options ndots:5

/ # nslookup hostnames
Server:		10.152.183.10
Address:	10.152.183.10:53
** server can't find hostnames.svc.cluster.local: NXDOMAIN
** server can't find hostnames.cluster.local: NXDOMAIN

Name:	hostnames.default.svc.cluster.local
Address: 10.152.183.195

** server can't find hostnames.svc.cluster.local: NXDOMAIN
** server can't find hostnames.cluster.local: NXDOMAIN

/ # nslookup hostnames.default.svc.cluster.local
Server:		10.152.183.10
Address:	10.152.183.10:53

Name:	hostnames.default.svc.cluster.local
Address: 10.152.183.195
``` 

However, it FAILS to resolve relative name `nslookup hostnames.default`
```
/ # nslookup hostnames.default
Server:		10.152.183.10
Address:	10.152.183.10:53

** server can't find hostnames.default: NXDOMAIN
** server can't find hostnames.default: NXDOMAIN
```

**Proposed Solution:**
Replace the alpine image by this image to have better net tools (`nslookup`, `curl` is also available). All `nslookup` example works exactly as shown in the page. Including the clean output (without any "server can't find xxx: NXDOMAIN")
```bash
kubectl run -it --rm --restart=Never minibusy --image=radial/busyboxplus:curl
```
Please note the `radial/busyboxplus:curl` image suggested above is used in this Kubernetes doc page [Connecting Applications with Services](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/)

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by sftim** [comment]
@tringuyen-yw I've split the remaining bit of #21388 into this new issue.

**Comment by tringuyen-yw** [comment]
Thanks, I thought the 2 issues I mentioned in #21388 could be fixed together by just editing the page source in one go. BTW, what is the procedure to join the contributors so that I can participate to make Pull requests?

**Comment by sftim** [comment]
I hope that https://kubernetes.io/docs/contribute/start/ covers what you need to know about contributing! Welcome!

**Comment by sftim** [comment]
Should we use `minibusy` / `busyboxplus`? Is it a good idea to recommend this third-party software?

**Comment by ljnaresh** [comment]
@sftim How about using the public image from google container registry? The busybox image `gcr.io/google-containers/busybox` behaves similar to  `radial/busyboxplus:curl` but lacks the curl utility.

**Comment by sftim** [comment]
`gcr.io/google-containers/busybox` sounds like a good suggestion.

**Comment by celestehorgan** [comment]
@sftim Taking a look at the PR linked to this and the discussion here, I'm going to go ahead and merge the PR.

Thanks for your patience with the process and your contributions, @ljnaresh!

**Comment by irvifa** [comment]
The PR is merged
/close
