### ISSUE TITLE
No descriptions about the namespace "kube-node-lease" 

### ISSUE THREAD

**Issue by johnlinp** [kubernetes/website#21443]
**This is a Bug Report**

**Problem:**

In the page https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/, when listing the namespaces, it shows:

> ```
> NAME              STATUS   AGE
> default           Active   1d
> kube-node-lease   Active   1d
> kube-public       Active   1d
> kube-system       Active   1d
> ```

There are 4 namespaces, but the description goes:

> Kubernetes starts with three initial namespaces:
> - default The default namespace for objects with no other namespace
> - kube-system The namespace for objects created by the Kubernetes system
> - kube-public This namespace is created automatically and is readable by all users (including those not authenticated). This namespace is mostly reserved for cluster usage, in case that some resources should be visible and readable publicly throughout the whole cluster. The public aspect of this namespace is only a convention, not a requirement.

where `kube-node-lease` is missing.

**Proposed Solution:**

Add some descriptions about the namespace `kube-node-lease`.

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by sftim** [comment]
Want to document this? https://stackoverflow.com/questions/59659966/what-is-the-kube-node-lease-namespace-for has pointers.

**Comment by johnlinp** [comment]
It seems that 6cf2449a2e065cac2d36aec58c1ac28e89c1168d already fixed this. Closing this issue.
