### ISSUE TITLE
Appreciation for k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by rexagod** [kubernetes/website#21458]
Hello.

I'm a student, currently 21. I was finishing up on a project for the past couple of days, but I was stuck, to say the least. The project involves making and deploying a simple CI platform. The internet has so much buffer content and "well actually" articles that would be enough to frustrate even the best of us. I do not know who came up with the idea of a Kubernetes cheatsheet, I do not know who were the folks behind this.

What I do know is that you all have the best concentration of resources out there, and are the best people ever.

Sorry if this bummed your issue tracker or workflow, just know that I was too hyped at this moment to stop myself from writing this.

THANK YOU!

**Comment by sftim** [comment]
/triage praise
:wink:

**Comment by sftim** [comment]
I went and looked it up: the following contributors got the cheat sheet to where it is today:
```markdown
- @ahmadbanijamali
- @anapsix
- @andjelx
- @apelisse
- @bgrant0607
- @Bradamant3
- @ccxex29
- @chendotjs
- @cloudmelon
- @devasat
- @dpandhi-git
- @gosoon
- @ialidzhikov
- @ismailyenigul
- @jimangel
- @KabirKwatra
- @laidan6000
- @lyveng
- @nashasha1
- @oke-py
- @pawelprazak
- @Pc6
- @petermikitsh
- @pierwill
- @prasadph
- @praveen-kg
- @rajeshdeshpande02
- @sftim
- @steveperry-53
- @sunlintong
- @tengqm
- @thecrudge
- @w3aman
- @wibobm
- @zacharysarah
- @zhouya0
```

**Comment by zacharysarah** [comment]
@rexagod Thank you so much for the feedback! 💛  I'm so glad you found what you needed. Thanks for letting us know! 🙇

**Comment by zacharysarah** [comment]
As lovely as this issue is, there's nothing actionable here (except to keep on doing what we're doing!), so--

/close
