### ISSUE TITLE
ja: Make docs/setup/best-practices/certificates.md follow v1.17 of the origina text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#21489]
**This is a Feature Request**

**What would you like to be added**

Update docs/setup/best-practices/certificates.md to follow v1.17 of the original (English) text.

**Why is this needed**
docs/setup/best-practices/certificates.md is outdated.  

**Comments**

/language ja
/good-first-issue

A file to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/setup/best-practices/certificates.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/setup/best-practices/certificates.md

**Note**
Currently, we use dev-1.17-ja.2 branch. Please open a PR targeting the branch.

ref
How To Contribute
翻訳スタイルガイド

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by hiyokotaisa** [comment]
diff: https://gist.github.com/hiyokotaisa/70bdc04f87dd022cbb571178df5f7490

**Comment by hikkie3110** [comment]
遅くてすみません、土曜にはPR出せるように進めております。

**Comment by inductor** [comment]
来週1.17-ja.2ブランチをmasterに取り込む予定のため、今週末にPull Requestが出なさそうであれば一旦assignを外させていただきます。
よろしくお願いしします！

**Comment by hikkie3110** [comment]
そうだったのですね。承知しました。
もうすぐ出しますーmm
