### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/expose-interactive/

### ISSUE THREAD

**Issue by natehart** [kubernetes/website#2148]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When completing the Kubernetes interactive tutorial, step 4 (Exposing your app publicly), you have a step where you `curl host01:$NODE_PORT`. While this works in your example, there is no information given about what 'host01' is, what it means, or how you obtained it. It just magically appears. You can't make the curl request with either the provided IP or Endpoints from the `kubectl describe services/kubernetes-bootcamp` command.

**Proposed Solution:**
Please clarify what host, node, or pod is receiving the curl request, and how we can obtain that information locally for our own deployments.

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
The command `kubectl get nodes` will now list host01 as the node. I'm hoping this will allow users to connect the dots. I'd love to hear your feedback if this makes it more straightforward.

**Comment by mappedinn** [comment]
I am having the same issue as @natehart 

I tried your solution @BenHall, and since I am using `minikube` on my local machine, there are nodes I do have:

```sh
$ kubectl get nodes
NAME       STATUS    AGE
minikube   Ready     1d
```

So, I tried directly that command:

```sh
$ curl minikube:32028
curl: (6) Could not resolve host: minikube
# 32028 is the external port of the service 
```

Any recommendations?

Thanks

**PS:**  I still new to kubernetes ;)

**Comment by BenHall** [comment]
Minikube runs as a virtual machine via Virtualbox. You'll need a hosts entry that maps minikube hostname to the IP of the machine.

I believe you can find the IP of the VM using `minikube ip`. 

This should allow you to do `curl IP:32028`.

Hope this helps.

**Comment by mappedinn** [comment]
thanks @BenHall

**Comment by tengqm** [comment]
Please feel free to reopen if the solution doesn't work.

**Comment by Kup3a** [comment]
For people who find this issue in search of resolving interactive tutorial problem.
For me `minicube ip` didn't work in tutorial (but fine locally). So u can run `kubectl describe nodes`, find there host01, take it ip-address from LegacyHostIP field and then finally run `curl LegacyHostIP_value:$NODE_PORT`.

**Comment by tengqm** [comment]
@Kup3a Thanks for sharing.

**Comment by BenHall** [comment]
Thanks for your feedback. We moved to using `curl $(minikube ip):$NODE_PORT` to be consistent with the rest of the Minikube documentation. We changed the hostname of the environment to `minikube` to also match how Minikube runs locally and how it appears in `get nodes`.
