### ISSUE TITLE
ja: Make docs/concepts/workloads/controllers/deployment.md follow v1.17 of the original text

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#21497]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/workloads/controllers/deployment.md to follow v1.17 of the original (Englist) text.

**Why is this needed**
content/ja/docs/concepts/workloads/controllers/deployment.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/concepts/workloads/controllers/deployment.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/concepts/workloads/controllers/deployment.md

diff between translated and v1.17
https://gist.github.com/60ee6ea4f45c5a6a839d32bd5582e091

v1.17対応とレイアウト崩れ修正の両方を取り込みたいです。
https://github.com/kubernetes/website/pull/21015/files

**Note**
Currently, we use dev-1.17-ja.2 branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by oke-py** [comment]
ちょっとややこしいかもしれません。遠慮なくSlackでご相談ください。

**Comment by inductor** [comment]
来週1.17-ja.2ブランチをmasterに取り込む予定のため、今週末にPull Requestが出なさそうであれば一旦assignを外させていただきます。
よろしくお願いしします！

**Comment by inductor** [comment]
@akitok ping

**Comment by inductor** [comment]
@akitok 月曜日になったのでアサインは一旦外します！
/assign

**Comment by akitok** [comment]
@inductor 
レスポンス滞ってて、すいません! 
ちょうどドキュメント修正していて、もうほぼ修正終わったんですが、
次のブランチで、対応した方が良いでしょうか？

**Comment by inductor** [comment]
@akitok 返事がなかったので私の方で対応終えてPR送ろうとしてました。既にできてるようであればアサインしなおします～

**Comment by akitok** [comment]
@inductor 
了解です！
1時間以内にはPR出せると思います。

**Comment by inductor** [comment]
既存の翻訳もいくつか修正したい点があるので、そこも含めてお願いすることになるかと思います。

よろしくお願いします！
