### ISSUE TITLE
ja: Make docs/setup/_index.md follow v1.17 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#21490]
**This is a Feature Request**

**What would you like to be added**

Update ja/docs/setup/_index.md to follow v1.17 of the original (English) text.
There's no need to translate _index.md into Japanese. But it's welcome to translate it.

**Why is this needed**
docs/setup/_index.md is outdated.

**Comments**

/language ja
/good-first-issue

The file to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.2/content/ja/docs/setup/_index.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/setup/_index.md

Currently, we use dev-1.17-ja.2 branch. Please open a PR targeting the branch.

ref
How To Contribute
翻訳スタイルガイド

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by hiyokotaisa** [comment]
diff: https://gist.github.com/hiyokotaisa/fd18db1ae45a7a81ed0ef052d08ddede
