### ISSUE TITLE
Translate tasks/configure-pod-container/static-pod (Create static pods) into Korean

### ISSUE THREAD

**Issue by bluefriday** [kubernetes/website#21518]
**This is a Feature Request**

**What would you like to be added**

Translate tasks/configure-pod-container/static-pod (Create static pods) into Korean

**Why is this needed**
There is no documents with Translate tasks/configure-pod-container/static-pod (Create static pods) into Korean.

**Comments**

https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

**Comment by gochist** [comment]
resolved by #21798 
/close
