### ISSUE TITLE
Issue with missing hello-application.yaml file under ja directory

### ISSUE THREAD

**Issue by yu-kasuya** [kubernetes/website#21523]
**This is a Bug Report**

**Problem:**
In dev-1.17-ja.2 branch, `make docker-serve` doesn't work after service-access-application-cluster.md was updated. Because "content/ja/examples/service/access/hello-application.yaml" is missing. Error message is below:

```
Error: Error building site: "/src/content/ja/docs/tasks/access-application-cluster/service-access-application-cluster.md:31:1": failed to render shortcode "capture": failed to process shortcode: "/src/layouts/shortcodes/codenew.html:14:16": execute of template failed: template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: file "content/ja/examples/service/access/hello-application.yaml" does not exist
```

**Proposed Solution:**
Add hello-application.yaml file

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/

**Comment by oke-py** [comment]
Good Catch! Thanks!
