### ISSUE TITLE
Note shortcode with html comment wont be parsed correctly

### ISSUE THREAD

**Issue by eleven26** [kubernetes/website#21529]
**Note shortcode with html comment wont be parsed correctly**

**Problem:**

After `layouts/shortcodes/note.html` has been updated since [Change notes templating to be able to comply with Hugo 0.70. ](https://github.com/kubernetes/website/pull/20946), the HTML comment inside `{{< node >}}` will result in markdownify not working correctly.

> English version is ok.

English version docs: [confirm-installation](https://kubernetes.io/docs/tasks/tools/install-minikube/#confirm-installation)

![en](https://user-images.githubusercontent.com/10000532/83876403-64a38a00-a76b-11ea-8b90-b50b337f8b57.png)

Chinese version docs: [confirm-installation](https://kubernetes.io/zh/docs/tasks/tools/install-minikube/#%E5%AE%89%E8%A3%85%E7%A1%AE%E8%AE%A4)

![zh](https://user-images.githubusercontent.com/10000532/83876430-6b320180-a76b-11ea-8d2a-fe2684045120.png)

**Proposed Solution:**

Move the HTML comment outside the `{{< node >}}` shortcode, it does work correctly. Just like this.

```
<!--
For setting the `--vm-driver` with `minikube start`, enter the name of the hypervisor you installed in lowercase letters where `<driver_name>` is mentioned below. A full list of `--vm-driver` values is available in [specifying the VM driver documentation](https://kubernetes.io/docs/setup/learning-environment/minikube/#specifying-the-vm-driver).
-->

{{< note >}}

通过 `minikube start` 设置 `--vm-driver`。在下面提到 `<driver_name>` 的地方，用小写字母，输入你安装的 hypervisor 的名称。
[指定 VM 驱动程序](https://kubernetes.io/docs/setup/learning-environment/minikube/#specifying-the-vm-driver) 列举了 `--vm-driver` 值的完整列表

{{< /note >}}
```

**Comment by sftim** [comment]
This partially duplicates issue #20335
