### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by rpcyn** [kubernetes/website#21547]
**This is a Bug Report**

**Problem:** Minikube unable to expose the service to external ip
**$ minikube service hello-node**

| NAMESPACE |    NAME    | TARGET PORT |           URL      

| default   | hello-node |        8089 | http://172.17.0.4:31019 |

🎉  Opening service default/hello-node in default browser...
rajendra@master:~$ Opening in existing browser session.
**[0606/234938.552552:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly**

**Proposed Solution:** Waiting for the inputs here

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by sftim** [comment]
@rpcyn can you describe the environment where you're running Minikube? It sounds like there might be some issue with the integration between Minikube and your preferred web browser.

/triage needs-information

**Comment by tengqm** [comment]
Please report the bug to the [minikube project](https://github.com/kubernetes/minikube/issues) because this doesn't look like a doc issue.
/close
