### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/jsonpath/

### ISSUE THREAD

**Issue by pctr362979** [kubernetes/website#21545]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @pctr362979 

It sounds like you wanted to report that something isn't right on https://k8s.io/docs/reference/kubectl/jsonpath/

What was the defect you noticed?

/triage needs-information

**Comment by tengqm** [comment]
/close
Feel free to reopen with details.
