### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by carlosadean** [kubernetes/website#21564]
**This is a Bug Report**

There is a problem when copy and paste the yum command line to install packages on centos/rhel.

The documentation is showing one long-dash instead of two dashes as you can see below.

`yum install -y kubelet kubeadm kubectl –disableexcludes=kubernetes`

It should be "--disableexcludes".

**Comment by carlosadean** [comment]
Looking at the documentation the command line is correct, so I understand this is display-only bug.

https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

**Comment by neolit123** [comment]
hi, this is tracked here:
https://github.com/kubernetes/website/issues/20915

thanks
/close
