### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by DmitryZayats** [kubernetes/website#21568]
**This is a Bug Report**

**Problem:**
Docker installation instructions are missing step for enabling service, so after host reboot docker is not running

**Proposed Solution:**
Add below command
`systemctl enable --now docker`
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Comment by sftim** [comment]
Thanks, good spot
/kind bug
/priority important-longterm
