### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by DmitryZayats** [kubernetes/website#21567]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

CentOS/RHEL instructions for installing kubeadm have this line when adding Kubernetes repo

`exclude=kubelet kubeadm kubectl`

And then a few lines below documentation instructs you to install 

`yum install -y kubelet kubeadm kubectl –disableexcludes=kubernetes`
 
However obviously since those packages are excluded when defining the repo - yum will return following 

```
No package kubelet available.
No package kubeadm available.
No package kubectl available.
Error: Nothing to do
```

**Proposed Solution:**
Remove exclude line when defining repo

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

![Kubernetes_documentation_issue](https://user-images.githubusercontent.com/37493923/83980793-211d5d00-a8de-11ea-9b8c-baaeb29c0676.png)

**Comment by neolit123** [comment]
the issue here is ` –disableexcludes=kubernetes`
notice the above has a `–` instead of `--`.

we are still pending a fix for this here:
https://github.com/kubernetes/website/issues/20915

/close
/sig docs
