### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by bartier** [kubernetes/website#21576]
**This is a Bug Report**

**Problem:**

After 'Add the following line to the bottom of the /etc/hosts file.', there is a blue quote indication with no text.
![image](https://user-images.githubusercontent.com/18057391/84020314-03410e00-a959-11ea-8559-00e7a2418780.png)

This happens in more locations in this page. Is this supposed to be like that? Thanks :)

**Proposed Solution:** The `notes` like `Note: If you are running Minikube locally, use minikube ip to get the external IP. The IP address displayed within the ingress list will be the internal IP.` should be inside the blue quote indication, right? :)

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
This is related to umbrella issue #20335
/kind bug
/priority backlog

**Comment by tengqm** [comment]
Looks like this is fixed. At least no longer an issue with Chrome or Firefox. Pls feel free to reopen this if the problem persists.
/close
