### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by jeffnai-github** [kubernetes/website#21585]
**This is a Bug Report**

**Problem:**
"kubectl edit ..." does not honor KUBE_EDITOR or EDITOR setting.
**Proposed Solution:**
"kubectl edit ..." should honor KUBE_EDITOR or EDITOR setting as documented in "kubectl edit --help": ... It will open
the editor defined by your KUBE_EDITOR, or EDITOR environment variables, or fall back to 'vi' for Linux ...

**Page to Update:**
https://kubernetes.io/...

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40",
 GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40",
 GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

How to reproduce:
$ uname -a
Linux instance-1 5.3.0-1020-gcp #22~18.04.1-Ubuntu SMP Mon May 11 18:45:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd

$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40",
 GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40",
 GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

$ minikube start --driver=none
$ kubectl apply -f cassandra-service.yaml 
$ kubectl apply -f cassandra-statefulset.yaml 

$ which emacs
/usr/bin/emacs

$ export KUBE_EDITOR=/usr/bin/emacs
$ kubectl edit statefulset cassandra 
[opens the yaml in vi]

**Comment by tengqm** [comment]
Tried this on a ubuntu box but cannot reproduce.
Also this doesn't look like an issue of the documentation.
Please try stackflow or slack channel or file an issue in kubernetes/kubernetes.
/close
