### ISSUE TITLE
API Reference for v1.16 404s

### ISSUE THREAD

**Issue by jalseth** [kubernetes/website#21583]
**This is a Bug Report**

**Problem:**

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/ which used to show the reference for v1.16, now 404s as do all versions of the page other than v1.18.

**Comment by KilimAnnejaro** [comment]
This is related to https://github.com/kubernetes/website/issues/21429.

**Comment by tengqm** [comment]
closing as a dup of #21429
