### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by janehojy** [kubernetes/website#21597]
**This is a Bug Report**

**Problem:**
etcd backup command is missing required flags: `--cacert=/etc/kubernetes/pki/etcd/ca.crt`, `--cert=/etc/kubernetes/pki/etcd/server.crt` and `--key=/etc/kubernetes/pki/etcd/server.key`

**Proposed Solution:**
Expected result: 
```
$ ETCDCTL_API=3 etcdctl --endpoints $ENDPOINT snapshot save snapshotdb
# exit 0
```

Actual result:
```
$ ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 snapshot save snapshotdb
Error: rpc error: code = Unavailable desc = transport is closing
```

Proposed Solution:
```
$ ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key snapshot save snapshotdb
```

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster

**Comment by sftim** [comment]
@janehojy are these extra flags always required, or does that depend on exactly how you're running `etcdctl`?

(it's OK to answer “I'm not sure”)

**Comment by makocchi-git** [comment]
I suppose it would be better to update the doc to use etcd with SSL/TLS.

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/security.md

**Comment by irvifa** [comment]
Hey can I close this or we left it as it is?
/remove-lifecycle rotten
