### ISSUE TITLE
Issue with k8s.io/zh/docs/concepts/configuration/configmap/

### ISSUE THREAD

**Issue by aixi** [kubernetes/website#21598]
**This is a Bug Report**

**Problem:**
apiVersion: v1
kind: ConfigMap
metadata:
  Name: game-demo
data:
  # 类属性键；每一个键都映射到一个简单的值
  player_initial_lives: 3
  ui_properties_file_name: "user-interface.properties"
  #
  # 类文件键
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true

  Name: game-demo. name should be lower case
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/kind bug
/priority backlog
/language zh

`Name: game-demo` is incorrect in the manifest on https://k8s.io/zh/docs/concepts/configuration/configmap/
it should be `name: game-demo`
