### ISSUE TITLE
Translation Issue with k8s.io/zh/docs/concepts/architecture/nodes/

### ISSUE THREAD

**Issue by goushuai** [kubernetes/website#21606]
**This is a Bug Report**

**Problem:**
MemoryPressure字段的描述有歧义：True 表示节点存在内存压力 – 即节点内存用量低
应该是：True 表示节点存在内存压力 – 即节点内存可用量低

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/zh/docs/concepts/architecture/nodes/

Kubernetes Version: v1.18

**Comment by tengqm** [comment]
would you like to propose a fix?
