### ISSUE TITLE
[IT] Remove announcement and deprecationwarning shortcodes

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#21611]
Umbrella issue: #21609

Remove the following from `/content/it/_index.html` L6-8:

```
{{< announcement >}}

{{< deprecationwarning >}}
```

**Comment by harik8** [comment]
https://github.com/kubernetes/website/pull/21667

**Comment by Fale** [comment]
The PR #21667 has been merged, so we can close this one as well, I think!
