### ISSUE TITLE
Update terminology to be racially neutral

### ISSUE THREAD

**Issue by scottstout** [kubernetes/website#21621]
**This is a Feature Request**

**What would you like to be added**
Terminology should be updated to be more racially neutral. 
whitelist --> allowlist
blacklist --> denylist

In many cases these words can be avoided all together. For example if the sentence is "the following IP addresses should be whitelisted" you can change it to "the following IP addresses should be allowed". This is probably more clear language.

master/slave --> director/worker? 

**Why is this needed**
Create a more inclusive environment in tech. 
Make the world slightly better.

**Comments**
There is a similar feature request in kubernetes/kubernetes here:
https://github.com/kubernetes/kubernetes/issues/90277
I have created a PR to fix the issues in the docs/website here:
https://github.com/kubernetes/website/pull/21591

**Comment by rlenferink** [comment]
Didn’t we already change `master` to `control plane` some time ago @sftim ?

**Comment by zacharysarah** [comment]
@scottstout Thanks for opening this! 

Partial fix (allow list/deny list) in https://github.com/kubernetes/website/pull/21591

**Comment by jboeshart** [comment]
Adding the following to the list as well. Updating this could help enable downstream services (AKS) to adopt more inclusive terminology without having to deviate from the source project terminology.

https://kubernetes.io/docs/concepts/#kubernetes-master

**Comment by sftim** [comment]
Relates to #21749 and to the new Naming working group.

**Comment by devurandom** [comment]
These two pages also make reference to "master" VMs or machines:

* https://kubernetes.io/docs/concepts/overview/components/
* https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

**Comment by neolit123** [comment]
> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

a PR to replace:

> "for the masters"

with:

> "for the control-planes Nodes"

is welcome.

**Comment by devurandom** [comment]
> > https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/
> 
> a PR [...] is welcome.

Thanks: #23847

**Comment by celestehorgan** [comment]
@kubernetes/wg-naming-leads – we've already done work around this for whitelist/blacklist but our recommendation on master/slave needs some work. Regardless I'd like to close this issue because I think it's too broad.

**Comment by marians** [comment]
Has a decision been made yet regarding the naming of the feature "High-Availability Kubernetes Masters"? See https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/

If yes, we'd like to apply the new term to [our documentation and communication](https://docs.giantswarm.io/advanced/high-availability/masters/).

**Comment by marians** [comment]
@kubernetes/wg-naming-leads @celestehorgan Is there any progress on this?

I'd like to suggest some options for renaming "High-Availability Kubernetes Masters":

- (a) High-availability control plane
- (b) Highly available control plane

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/highly-available-control-plane/ now replaces https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/
