### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/expose-external-ip-address/

### ISSUE THREAD

**Issue by Asherslab** [kubernetes/website#21623]
**This is a Bug Report**

**Problem:**
Page has random miscellaneous line of code (html?) in it:
`<blockquote class="note">`

**Proposed Solution:**
remove the misc line

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

**Comment by tengqm** [comment]
Looks like the problem is gone. Pls feel free to reopen if not.
