### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by dumlutimuralp** [kubernetes/website#21632]
**This is a Bug Report**

**Problem:** It is stated that "kubeadm will not install kubelet and kubectl" however it does (when performing install kubeadm in the respective Linux distro i.e. apt-get install kubeadm)

**Proposed Solution:** Update the doc

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

 K8S 1.18.x

**Comment by tengqm** [comment]
> "kubeadm will not install kubelet and kubectl"

This statement still holds true, right? So the issue here can be closed?

**Comment by dumlutimuralp** [comment]
I' d at least expect the additional info that @neolit123 mentioned above (about dependencies) to be added to the original K8S.io page. My 2 cents. Thanks.

**Comment by neolit123** [comment]
i think it's just misleading.

executing kubeadm does not download kubectl or kubelet from the internet for the user.
however, installing the kubeadm DEB/RPM package has kubelet and kubectl as dependencies, so they end up being installed.

**Comment by tengqm** [comment]
@dumlutimuralp Makes sense.
