### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by kubroid** [kubernetes/website#21633]
**This is a Bug Report**

Hey guys, please remove italic from yaml, because it turns pile symbol into slash...
game.properties: |

**Comment by kubroid** [comment]
@sftim, aha, sorry, didn't suppose this is github "feature".

**Comment by sftim** [comment]
It's actually a website behaviour and not a GitHub feature. @kubroid please feel free to reopen it as I think you have identified a valid concern.
