### ISSUE TITLE
Issue with k8s.io/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by gunboe** [kubernetes/website#21637]
**This is a Bug Report**

**Problem:**
I belive the command bellow is out of date:
```
NODEPORT=$(kubectl get -o jsonpath="{.spec.ports[0].nodePort}" services nodeport)
NODES=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="ExternalIP")].address }')
```
Only change "ExternalIP" to "InternalIP" to get NODES IP correctly.

**Proposed Solution:**
```
NODEPORT=$(kubectl get -o jsonpath="{.spec.ports[0].nodePort}" services nodeport)
NODES=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="InternalIP")].address }')
```

**Page to Update:**
https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

Tested with Kubeadm 1.18

**Comment by tengqm** [comment]
/language en
I agree that the existence of external IP is irrelevant in this context.
