### ISSUE TITLE
ja: Unify the transration of "Architecture"

### ISSUE THREAD

**Issue by nasa9084** [kubernetes/website#21649]
現状表記揺れの発生している `Architecture` の翻訳を `アーキテクチャ` とすることとしたため、 `アーキテクチャー`を `アーキテクチャ` に置き換える

context: https://github.com/kubernetes/website/pull/20880#discussion_r438194745

翻訳スタイルガイドの頻出単語には追加済み: https://kubernetes-docs-ja.kibe.la/notes/1

**Comment by inductor** [comment]
@chaspy 来週1.17-ja.2ブランチをmasterに取り込む予定のため、今週末にPull Requestが出なさそうであれば一旦assignを外させていただきます。
よろしくお願いしします！

**Comment by inductor** [comment]
@chaspy ping
