### ISSUE TITLE
Issue with k8s.io/docs/tasks/inject-data-application/define-command-argument-container/

### ISSUE THREAD

**Issue by hrsandhu** [kubernetes/website#21644]
**This is a Bug Report**

The example on this page does not work it returns:

/bin/bash: - : invalid option
Usage:  /bin/bash [GNU long option] [option] ...
        /bin/bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --protected
        --rcfile
        --rpm-requires
        --restricted
        --verbose
        --version
Shell options:
        -irsD or -c command or -O shopt_option          (invocation only)
        -abefhkmnptuvxBCHP or -o option

**Proposed Solution:**
Not Sure

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#run-a-command-in-a-shell

**Comment by tengqm** [comment]
Pls be specific about the example that fails and the image you used.

**Comment by hrsandhu** [comment]
Sorry please close this issue, upon further review everything is working correctly there was a problem with the container I was using.
