### ISSUE TITLE
Improve 'Release Notes' readability on home page

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#21643]
Per @kbhawkey feedback on #21096 it would be good to improve the readability.

>Hi! I reviewed the changes to the home page.
>The text says, "If you are installing ... or upgrading".
>By removing the Download Kubernetes text from the home page, the reader has to find the links to the installers within the release notes (not easy).
>
>https://deploy-preview-21096--kubernetes-io-master-staging.netlify.app/docs/setup/release/notes/#downloads-for-v1180?
>
>It would be helpful if the Release notes page was modified to include a generic section header to "Download Kubernetes". The current release notes page structure does not interface well with the docs.
>
>The card name change is OK. Another idea is: Install or Upgrade Kubernetes.

**Comment by sftim** [comment]
/priority important-longterm
/language en

I think it's important to help people find Kubernetes software artifacts to download.

**Comment by divyabhushan** [comment]
Hi @jimangel, @sftim 
I will fix this in the next 5 hours. Thanks for your patience.

**Comment by divyabhushan** [comment]
@sftim, My local hugo server deployment seems to be failing. Just received the latest commit. Going to try that. 
/WIP

**Comment by jimangel** [comment]
Thanks @divyabhushan sorry for my delay.
/close

**Comment by divyabhushan** [comment]
> Thanks @divyabhushan sorry for my delay.
> /close

Thanks @jimangel and @sftim
