### ISSUE TITLE
translate concepts/storage/persistent-volumes.md to Chinese

### ISSUE THREAD

**Issue by zbing0203** [kubernetes/website#21654]
Could you please clarify how to create PV that used by PVC

**Comment by sftim** [comment]
(if updating the _zh_ localization, amend the _en_ localization first and then localize that to _zh_)

**Comment by tengqm** [comment]
The https://kubernetes.io/docs/concepts/storage/persistent-volumes page is not yet translated.

**Comment by tengqm** [comment]
/retitle translate concepts/storage/persistent-volumes.md to Chinese
