### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/annotations/

### ISSUE THREAD

**Issue by sjmudd** [kubernetes/website#21661]
**Problem:**

I miss a better description with examples that more clearly distinguish between annotations and labels.

I see that you can not select/search on annotations but can on labels, but what I would find useful are a couple of life-like examples where both annotations and labels are used and the description confirms the reason for these choices.

I suspect this is obvious once someone has practical experience with kubernetes in a large/complex environment but it may not be obvious if you are initially testing it on something like minikube or microk8s.

**Proposed Solution:**

Please provide a couple of life-like examples where both annotations and labels are used and provide a description which clarifies the reason for these choices.

**Comment by sftim** [comment]
My gut feeling is that a new Task page could help here.
_or_ maybe there is already a task page, and what's missing is the hyperlink to it

**Comment by sjmudd** [comment]
Clearly this is not a big thing but if there's better other information which explains this better then I think it would be useful for people who are new to kubernetes.
