### ISSUE TITLE
error: Missing or incomplete configuration info

### ISSUE THREAD

**Issue by azeem2412** [kubernetes/website#21675]
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

please guide i want to create pod but this error appearing again n again.

**Comment by sftim** [comment]
@azeem2412 can you explain more about the documentation page that needs fixing? It sounds like something is not right, but from what we know at this point we can't tell which page is wrong.

/triage needs-information

**Comment by tengqm** [comment]
This looks like a support issue and we haven't heard from the author for 3 months.
/close
