### ISSUE TITLE
Umbrella issue: Reorganize Advanced Contributing, Participation in SIG Docs to reduce duplication

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#21687]
This is a belated follow-up to https://github.com/kubernetes/website/issues/18878. 

A proposal to do the following:
1) Make [Participate in SIG Docs](https://kubernetes.io/docs/contribute/participating/) its own subsection, similar to other sections under contribute.
2) Break out topics on https://kubernetes.io/docs/contribute/participating/ and https://kubernetes.io/docs/contribute/advanced/ into sub-pages and reduce repetition (both pages talk about being a SIG Chair, for example)
3) Do a deep edit of all content while doing it.

**Work to be done:** 

My last foray into this was too big to handle, so this time let's break it out into sub-issues :p

I plan to execute work by first moving each topic to its new location, and (once all topics are moved) deleting the Advanced & existing participation pages.

**Issue no.** | **Existing content location** | **Proposed new location**
--- | --- | --- 
~https://github.com/kubernetes/website/issues/21830~ | ~[Participating in SIG Docs > Roles & Responsibilities](https://kubernetes.io/docs/contribute/participating/#roles-and-responsibilities) (+ Anyone, Members, Reviewers, Approvers subtopics~) | ~**New Page** Participating in SIG Docs > Roles & Responsibilities~
~https://github.com/kubernetes/website/issues/22276~ | ~[Advanced Contributing > Be a PR Wrangler for a week](https://kubernetes.io/docs/contribute/advanced/#be-the-pr-wrangler-for-a-week)~ | ~**New page** Participating in SIG Docs > PR Wranglers~
https://github.com/kubernetes/website/issues/22462 | [Advanced > Coordinate docs for a k8s release](https://kubernetes.io/docs/contribute/advanced/#coordinate-docs-for-a-kubernetes-release) | **New page** Participating in SIG Docs > Release coordination 
#tbd | [Advanced > Serve as a new contributor ambassador + sponsor a new contributor](https://kubernetes.io/docs/contribute/advanced/#serve-as-a-new-contributor-ambassador) | **New page** Participating in SIG Docs > Help new contributors
#tbd | [Advanced > Serve as a SIG Co-chair](https://kubernetes.io/docs/contribute/advanced/#serve-as-a-sig-co-chair) + The stub at [Participating in SIG Docs > Roles & Responsibilities](http://localhost:1313/docs/contribute/participating/roles/#sig-docs-chairperson) | **New Page** Participating in SIG Docs > Be a SIG Co-chair 
#tbd | [Participating in SIG Docs > SIG Docs Teams & Automation + How Merging works](https://kubernetes.io/docs/contribute/participating/#sig-docs-teams-and-automation) | **New Page** Participating in SIG Docs > GitHub Teams & Automation 

This will lead us to a section menu that looks like this:

<img width="294" alt="Screenshot 2020-06-12 at 11 25 41" src="https://user-images.githubusercontent.com/17999517/84534840-83d87500-ac9f-11ea-9c50-15d2aab8d069.png">

**Follow-up tasks:**
- [ ] #tbd Delete https://kubernetes.io/docs/contribute/advanced/ once empty
- [ ] #tbd Delete https://kubernetes.io/docs/contribute/participating/ once empty

**Notes, concerns**:

I haven't found a home for [Advanced Contributing > Propose Improvements](https://kubernetes.io/docs/contribute/advanced/#propose-improvements) in this new world. I would argue that it's best to just remove this. Technically _anyone_ can propose improvements. I don't think we actually restrict this to just SIG Docs members. It might be worth noting elsewhere that SIG Docs has the final approval on any proposed changes, however.

**Comment by tengqm** [comment]
Sounds a good plan to me. +1

**Comment by kbhawkey** [comment]
Hi @celestehorgan . Here is a bunch of feedback :smile: .
It looks like you want to create a new directory/folder under contribute titled,
`Particpating in SIG Docs` and break up the content from the single pages (Advanced and Particpating) into single page topics.
I am not clear on the pages, `Github automation` as well as `Help new contributors`. I would think that the `Help` topic would be woven into all the roles. How does `Github ...` fit into participating?
To me, `Participating ...` seems to overlap with all of the `Contribute` topics (possibly change title to some text that includes `Roles`).
I'd like to see a direct link to the `docs release playbook` in the topic explaining the docs releases. The link may or may not be already part of the content.
I would make sure the titles of the main folders under the contribute tree help the reader navigate to the right content.

**Comment by celestehorgan** [comment]
Thanks for the feedback @kbhawkey ☺️ 

GitHub automation covers GitHub-related things that Approvers definitely need to know, but that are helpful for some other roles as well. I think it's a general topic directly under Participating, but I'll admit this wasn't the best name for it. 

Help new contributors is _also_ a bad name tbh. Maybe splitting off the topics into the following makes more sense:

- [Serve as a new contributor ambassador](https://kubernetes.io/docs/contribute/advanced/#serve-as-a-new-contributor-ambassador) > Participating > (page) Roles & Responsibilities > (topic) Approvers > (subtopic) Serve as a new contributor ambassador
- [Sponsor a new contributor](https://kubernetes.io/docs/contribute/advanced/#sponsor-a-new-contributor) >  Participating > (page) Roles & Responsibilities > (topic) Reviewers > (subtopic) Sponsor a new member

? 

Having done that little reshuffule, however... I wonder if it's best to split off all the Roles into their own pages. They're getting pretty long.

**Comment by zacharysarah** [comment]
@celestehorgan This looks good! Thank you for taking this on so thoughtfully. ✨ Let's talk this week about how best to support you in the work.

**Comment by sftim** [comment]
Fixing a typo:
/retitle Umbrella issue: Reorganize Advanced Contributing, Participation in SIG Docs to reduce duplication

**Comment by sftim** [comment]
> I haven't found a home for Advanced Contributing > Propose Improvements in this new world. I would argue that it's best to just remove this.

Sounds good.
