### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

### ISSUE THREAD

**Issue by AlexPSplunk** [kubernetes/website#21688]
**This is a Bug Report**

On the page: https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod
Under the section:  Forward a local port to a port on the Pod
This page suggests using kubectl port-forward to forward ports to your pod.  However, kubectl port-forward does not return, it is not daemonized by default.  The page does not note this fact

**Proposed Solution:**
Either:
* modify the page to indicate that kubectl port-forward will not return, and that the user needs to open another terminal window to continue with the exercises; 
OR
* modify the kubectl port-forward commands to include a & (ampersand) at the end of the line, so that the job will run in the background and return to the terminal prompt.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

**Comment by Cweiping** [comment]
Maybe adding a flag to ` kubectl port-forward` is a better way to solve this problem, such as `docker run --detach`?
