### ISSUE TITLE
Translate concepts/architecture/controller into Japanese

### ISSUE THREAD

**Issue by shuuji3** [kubernetes/website#21739]
**This is a Feature Request**

**What would you like to be added**

Translate [concepts/architecture/controller/](https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/architecture/controller.md) into Japanese.

**Why is this needed**

This page has not been translated.

**Comments**

/language ja
/assign

**Comment by inductor** [comment]
@chaspy いったん、作業まだやらないでください（masterに既存の翻訳を取り込む大きな作業があるので

**Comment by oke-py** [comment]
assigneeが2人いる！？

**Comment by inductor** [comment]
あ、ほんとだｗ

/unassign @chaspy

**Comment by inductor** [comment]
@shuuji3  これ 1.17-ja.3 でやってもらって大丈夫です！
