### ISSUE TITLE
Issue with k8s.io/zh/docs/setup/learning-environment/minikube/

### ISSUE THREAD

**Issue by chendf24** [kubernetes/website#21735]
**This is a Bug Report**

**Problem:**
Following command in section 2 is used to create a pod instead of creating a deployment.
_kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080_

**Proposed Solution:**
Change it to be same with English page:
kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10

This command does not have --port parameter, need to add --port in the command _kubectl expose deployment hello-minikube --type=NodePort_.

**Page to Update:**
https://kubernetes.io/...

**Comment by ZhiFeng1993** [comment]
PR merged. We can close this issue.
