### ISSUE TITLE
Issue with k8s.io/docs/contribute/localization/

### ISSUE THREAD

**Issue by shuuji3** [kubernetes/website#21733]
**This is a Bug Report**

**Problem:**
The link [@kubernetes/website-maintainers](https://github.com/orgs/kubernetes/teams/website-maintainers) in "Branching Strategy" section is 404 not found.

**Proposed Solution:**
I don't know the right page.

**Page to Update:**
https://kubernetes.io/docs/contribute/localization/#branching-strategy

**Comment by tengqm** [comment]
The link works. But the team may be not a public one ... so not everyone is able to see it.
/close

**Comment by shuuji3** [comment]
I see. Thank you.
