### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#21749]
**This is a Feature Request**

**What would you like to be added**
Rename the _master_ branch to _main_

**Why is this needed**
Our live website builds from the [master](https://github.com/kubernetes/website/tree/master) branch
I suggest serving the website from a (new) branch called [main](https://github.com/kubernetes/website/tree/main) instead.

This change avoids using  a term linked with controversy (especially in the United States of America).

/kind cleanup

**Comment by celestehorgan** [comment]
@sftim it's looking likely that we're going to wait to see what GitHub rolls out before making any moves ourselves, just fyi

**Comment by sftim** [comment]
Yep, I've intentionally set this to /priority awaiting-more-evidence

**Comment by sftim** [comment]
Duplicated by issue #22069

**Comment by nikhita** [comment]
/remove-lifecycle stale
xref https://github.com/kubernetes/org/issues/2222

**Comment by justaugustus** [comment]
Celeste to get more info:
/assign @celestehorgan

**Comment by celestehorgan** [comment]
Per our last SIG Docs meeting: @sftim is on board with the idea of renaming master branch to main instead.

/rename Rename "master" branch to "main"

**Comment by sftim** [comment]
@celestehorgan feel free to `/triage accepted` and adjust priority too.

**Comment by celestehorgan** [comment]
/triage accpeted 
/priority important-soon

From an implementation perspective, there are three major steps here. One is (to me) ambiguous:

1. Rename the branch
2. Ensure tooling (namely, Netlify) point to `main` and not `master` (this is easy)
3. Ensure extended tooling (autogenerated docs, mainly) are not affected. (this is hard)

**Comment by sftim** [comment]
BTW we can start by mirroring the master branch to the main branch. Branch mirroring makes transitions less painful.

**Comment by sftim** [comment]
What do we do about all the in-flight PRs? Does GitHub automatically update their base branch?

**Comment by celestehorgan** [comment]
@sftim I suspect we'll have to start by mirroring.

I tested this out on [an old repository](https://github.com/celestehorgan/learnapidoc) of mine:

1. created a branch `main`
2. Set it to the main branch for the repository
3. Observed what happened to an in-flight pull request opened against master.

The results were:

- `master` cannot be deleted because an open PR depends on it
- The open PR does not automatically switch to `main`

Ergo, we'd have to create `main`, switch Netlify over to it, encourage as many inflight PRs to merge against `main` as possible, and merge `master` into `main` regularly, like a release branch, for some period of time until no new PRs are open against it.

**Comment by sftim** [comment]
> merge `master` into `main` regularly

We could block merges to `master` and then automatically _mirror_ all new commits from `main` to `master`, until all open PRs are dealt with.

https://github.com/google/mirror-branch-action can help here.

**Comment by sftim** [comment]
(after that's set up, anyone who has a PR targeting `master` can switch the merge base of their PR to `main`)

**Comment by celestehorgan** [comment]
@justaugustus – Are individual repos in the org now free to go ahead and start renaming their main branches, or are we still investigating?

**Comment by nikhita** [comment]
> Are individual repos in the org now free to go ahead and start renaming their main branches, or are we still investigating?

Yes, individual repos can rename their branch if they are interested. https://k8s.dev/rename has more details. Having said that, we've only renamed low-volume repos until now.

@spiffxp do you know if the issue with webhooks getting triggered on all issues/PRs has been fixed? If yes, can we trial this on k/website?

cc @mrbobbytables @cblecker

**Comment by jimangel** [comment]
I think we have the ability to make this change ASAP. I will send something out to the mailing list and bring it up at this weeks SIG Docs meeting. If there's no objection, I can open the non-disruptive PRs and we can plan a date. Thanks!

**Comment by justaugustus** [comment]
Awesome to see!
Jim we're going to assign you.

/unassign @celestehorgan 
/assign @jimangel

**Comment by spiffxp** [comment]
> @spiffxp do you know if the issue with webhooks getting triggered on all issues/PRs has been fixed? If yes, can we trial this on k/website?

I believe so, yes. There is a relevant test-infra issue for this

**Comment by spiffxp** [comment]
https://github.com/kubernetes/test-infra/issues/20829 should be fixed as of two months ago

**Comment by mrbobbytables** [comment]
FYI - we have done the switch for another repo that was using netlify. It will throw an error if the `master` branch is gone if someone triggers a rebuild before it's config is updated. The good news is, updating is easy in the netlify UI and it takes effect immediately. 👍

**Comment by jimangel** [comment]
### Changes pre-rename
- [x] presubmit or postsubmit prowjob triggers **(N/A)**
- [x] milestone_applier prow config references the master branch **(only targets dev-x.xx)**
- [x] branch_protection prow config references the master branch **(only targets release-x.xx)**

### Just before rename
- [x] periodic prowjobs**(N/A)**
- [x] prowjob mentions master in its name **(N/A)**
- [x] prowjob calls scripts or code in your repo **(N/A)**
- [ ] repo has netlify configured **...can do at anytime**

I don't believe we have anything other then netlify to tweak.

### Approval
- [ ] Once all non-disruptive tasks have been completed and disruptive tasks have been identified, assign the GitHub Management team (@kubernetes/owners) for approval.

### Rename the default branch
- [ ] Rename the default branch from master to main using the GitHub UI by following the official instructions.

### Other
- [ ] docs reference the master branch, update to main (URLs will be automatically redirected).
- [ ] Ensure that CI and PR tests work fine.
- [ ] Trial the local development experience with a pre-rename clone.
- [ ] Send a notice about the branch rename to your SIG’s mailing list. Include the link to the GitHub instructions to rename your local branch.

After reviewing this checklist it seems like we are good to go, just need approval and to pick a date.

Can @mrbobbytables or anyone confirm? Thanks!

**Comment by mrbobbytables** [comment]
+1 as github admin 👍

**Comment by sftim** [comment]
Should we open an issue about the docs update, get a held PR open for that?

**Comment by jimangel** [comment]
> Should we open an issue about the docs update, get a held PR open for that?

As I understand it, it's changed through the GUI (https://k8s.dev/rename). I was planning on sending out emailed/slack 24h notice today. The idea being that I would have the weekend to clean up any issues (hopefully there are none).

**Comment by sftim** [comment]
I was thinking about pages like the guide to contributing and https://kubernetes.io/docs/contribute/new-content/_print/#choose-which-git-branch-to-use

**Comment by jimangel** [comment]
@sftim oh! Double misunderstood, heh. Yes, opening a tracking issue to resolve lingering docs would be fantastic!

**Comment by sftim** [comment]
Tracking issue: #28462

**Comment by kbhawkey** [comment]
:eyes:

**Comment by jimangel** [comment]
Renaming is complete. Ref: https://groups.google.com/g/kubernetes-sig-docs/c/s98sr2appP4/m/M-r7gANqAgAJ
/close

**Comment by chrisnegus** [comment]
Quick note: My open PRs seemed to transition properly to main. However, if there has not been a new commit to regenerate the Netlify build, the old Netlify link is listed at the bottom of the PR. I was able to see the new Netlify by simply changing `master` to `main` in the URL. For example, changing https://deploy-preview-28367--kubernetes-io-master-staging.netlify.app/ to https://deploy-preview-28367--kubernetes-io-main-staging.netlify.app/

**Comment by sftim** [comment]
Website admins can manually retrigger a build to fix that - I haven't looked into automating this though, as it's a one-off change.
