### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by jdetering** [kubernetes/website#21769]
**This is a Bug Report**

**Problem: Documentation contains an error:
URL: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/
chapter: kubeadm blocks when removing managed containers: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubeadm-blocks-when-removing-managed-containers
Text in doc: 
Inspecting the logs for docker may also be useful:
```journalctl -ul docker```
 

Error: This command runs into an error (on my ubuntu 18.04 distribution): 
```Failed to add match 'docker': Invalid argument```
**

**Proposed Solution:
Replace command with:
```journalctl -u docker```
**

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubeadm-blocks-when-removing-managed-containers

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/good-first-issue
/help
/kind bug

it should have been `-lu` or just `-u`

let's go with:
```
journalctl -u docker
```
