### ISSUE TITLE
Typo in k8s.io/docs/concepts/containers/images/#multi-architecture-images-with-manifests

### ISSUE THREAD

**Issue by nssachin** [kubernetes/website#21771]
**This is a Bug Report**

**Problem:**
There seems to be a wrong spelling in concepts/containers/images/#multi-architecture-images-with-manifests

**Proposed Solution:**

Correct the typo

**Before:**
A manifest can reference image manifests for **architecturew-specific** versions of an container

**After**
A manifest can reference image manifests for **architecture-specific** versions of an container

**Page to Update:**
https://kubernetes.io/docs/concepts/containers/images/#multi-architecture-images-with-manifests

Kubernetes Version: v1.18

**Comment by sftim** [comment]
Thanks @nssachin 
/help
/kind bug
/priority backlog
/language en
