### ISSUE TITLE
adjust integration of announcement banners 

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#21788]
**This is a Feature Request**
The HTML partials, announcements.html and frontpage-announcements.html, contain
a `main` element which duplicates the `main` element found in the body of the page.

This became an issue as the docsy theme updates page anchors in the script `anchors.js`.
https://github.com/google/docsy/blob/master/assets/js/anchor.js
This script depends upon the `main` element and failed to find the H1 - H6 level headings on
the page to udpate.

**What would you like to be added**
Investigate how to include the announcement banner on the docs pages (front page, docs, blog, and so on) without the `main` element. Investigate changes to the corresponding stylesheet.

**Why is this needed**
Clean up or adjust the preexisting, related code as well as the current templates and stylesheet.
Provide a flexible way to add and remove content such as announcement or banners on the pages.

**Comments**
For additional information, see PR #21780.

**Comment by sftim** [comment]
/reopen
There might be more to do here.

**Comment by celestehorgan** [comment]
I don't think there's any more work that needs doing here! you can close this off :)

**Comment by kbhawkey** [comment]
Good. The only thing noted is some different styling per main section (docs vs case studies).
/close
