### ISSUE TITLE
style release notes, docsy theme, table text overlap

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#21795]
**This is a Bug Report**
Since adding the docsy theme, the tables in the v1.18 release notes display with errors.

**Problem:**
The table data overflows into the right hand column (TOC).

**Proposed Solution:**
Investigate wrapping the table text.

**Page to Update:**
https://kubernetes.io/docs/setup/release/notes/#downloads-for-v1-18-0

**Comment by sftim** [comment]
Could we specially style the `<code>` elements for checksums to allow them to break inside the word for wrapping?

**Comment by tengqm** [comment]
That means we need some tricks to identify checksums?

**Comment by kbhawkey** [comment]
https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md

**Comment by tengqm** [comment]
@kbhawkey Suppose you are hacking the generation of release notes ... you will be generating an "annotated" markdown so that a special class is associated with the checksum string? I'd suggest we try tackle this by tweaking the CSS, given that pages like https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ are also suffering from this issue.

**Comment by sftim** [comment]
I _think_ I could make a (mainly) CSS change that doesn't require changes to release note generation, and is fairly robust.

**Comment by kbhawkey** [comment]
I am not proposing to modify the generation of the release notes. I simply added the link to the release notes tooling for some background information.

**Comment by celestehorgan** [comment]
@sftim Another option for display would be to have tables scroll horizontally once they hit their `max-width`, i.e. [like this](https://www.wealthsimple.com/en-ca/learn/investing-basics#types_of_investments). 

This would be a relatively simple fix and would serve us well for a number of scenarios.

**Comment by sftim** [comment]
@Arhell do you think any more work is needed here?

**Comment by Arhell** [comment]
@sftim no, tnxs.

**Comment by sftim** [comment]
/close

Done in #22167
