### ISSUE TITLE
reduce height of header (top navigation bar, banner, hero)

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#21797]
**This is a Feature Request**
With the new theme, the header components (navigation bar, announcement banner, header-hero) take up too much space on the page.

**What would you like to be added**
Reduce the height of the header. When you first view a page, most of the page content is not visible.

**Why is this needed**
Show more page content. Minimize the header to a height of about 1-1.5 inches.
Create a more pleasing background color for the header and footer.

**Comment by sftim** [comment]
Which PR seems better:   #21998 or #22043?

**Comment by sftim** [comment]
Voting on Slack strongly prefers https://github.com/kubernetes/website/pull/22043

**Comment by kbhawkey** [comment]
Looks like two PRs were merged to resize/remove the header.
/close
