### ISSUE TITLE
k8s.io/docs/concepts/: A Kubernetes "Master" (or Control Plane) doesn't just have to be on a single node

### ISSUE THREAD

**Issue by stefanlasiewski** [kubernetes/website#21800]
https://kubernetes.io/docs/concepts/#overview describes the "Kubernetes master" as being a single thing on a single node:

> ... The Kubernetes Control Plane consists of a collection of processes running on your cluster:
>
> The Kubernetes Master is a collection of three processes that run on a single node in your cluster, which is designated as the master node. 
> Those processes are: kube-apiserver, kube-controller-manager and kube-scheduler.

I believe this is incorrect. We may have more than one Kubernetes "master", and those masters can actually reside on more than a single node. Each of these processes may scale horizontally, and it, and it's common for there to be multiple copies of each of those processes. A common configuration for the control plane is to use 2-3 nodes for high availability.

Further down, at https://kubernetes.io/docs/concepts/#kubernetes-master, is a slightly different description. 

> Typically all these processes run on a single node in the cluster, and this node is also referred to as the master. The master can also be replicated for availability and redundancy

I'm trying to explain Kubernetes to colleagues, and this discrepancy has confused a couple of new users.

**Comment by sftim** [comment]
This is actually a bug. The best way to address that would be to cut out the use of the term “master”, which can be misleading as well as tinged with [concerns](https://en.wikipedia.org/wiki/Master/slave_(technology)#Terminology_concerns).

The control plane doesn't all have to run on one kind of host either. For example, it's OK to have _n_ hosts that run the kube-apiserver and another separate _m_ hosts that run etcd.

**Comment by stefanlasiewski** [comment]
I agree that "master" is an alienating and racist term and should be replaced (I stopped using it where possible in other projects a while ago), and I'm sure there's a Github issue somewhere that covers the replacement of "master" with another term throughout the k8s documentation so I won't duplicate that conversation here.

The term "master" should certainly be replaced, but what do we replace it with? Numerous sections in the documentation state that a "Kubernetes Master" is a piece of the "Kubernetes Control Plane", and so the term "Control Plane" cannot be a drop-in replacement for "Master".

**Comment by stefanlasiewski** [comment]
I'm still waiting for approval to sign the CLA, otherwise I would contribute a PR also.

**Comment by BenTheElder** [comment]
"control-plane node" is the replacement for discussing the machines, and "control-plane" for describing those components in general.

there are some threads about this on some of the maillinglists, and a workgroup being spun up to cleanup the language used broadly.

> Numerous sections in the documentation state that a "Kubernetes Master" is a piece of the "Kubernetes Control Plane", and so the term "Control Plane" cannot be a drop-in replacement for "Master".

IMHO that doesn't make sense. Unless they mean that the machine/vm is part of the overall control plane?

**Comment by stefanlasiewski** [comment]
>> Numerous sections in the documentation state that a "Kubernetes Master" is a piece of the "Kubernetes Control Plane", and so the term "Control Plane" cannot be a drop-in replacement for "Master".

> IMHO that doesn't make sense. Unless they mean that the machine/vm is part of the overall control plane?

Check out #21755, which describes this particular point better.

**Comment by BenTheElder** [comment]
regarding the previous discussions across sigs: https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/IjN_9n0KEUg

> The last resolution on this was simply control plane nodes and everything else was suggested to not overthink.  I don’t remember the exact issue but there was broad agreement at the time to go no further than “control plane” as the generic term for our brain and “control plane nodes” when referring to nodes that may host a control plane.

**Comment by stefanlasiewski** [comment]
It sounds like that discussion never quite reached a consensus.

I hope the newly formed WG is able to clean this up and improve the consistency of the terminology, while also removing terms like "master" which are offensive and also technically vague,

https://groups.google.com/g/kubernetes-dev/c/kry8QbIpxRs/discussion

**Comment by stefanlasiewski** [comment]
This was resolved, but I don't know when. 

The updated version of the page no longer mentions the concept of a single node:

> The worker node(s) host the Pods that are the components of the application workload. The control plane manages the worker nodes and the Pods in the cluster. In production environments, the control plane usually runs across multiple computers and a cluster usually runs multiple nodes, providing fault-tolerance and high availability.
