### ISSUE TITLE
Issue with k8s.io/docs/search/

### ISSUE THREAD

**Issue by kono-paku** [kubernetes/website#21808]
Searching keyword including space is not working.
If you search one keyword, for example, "command", it will work.
But, if "command and args" is input, the search result shows "Fetching results..." and
do not return the result.

**Comment by shuuji3** [comment]
Hello, kono-paku. Thank you for pointing out the issue!

I confirmed the same problem happens when searching the keyword "command and args" (https://kubernetes.io/docs/search/?q=command%20and%20args). And I'll investigate the cause of this problem.

/assign

**Comment by sftim** [comment]
BTW this applies to users using Bing search from China.

See PR #9845

**Comment by sftim** [comment]
@kono-paku are these symptoms still occurring? We're seeing different reports.

**Comment by kono-paku** [comment]
I have confirmed that this issue has dissapeared!
Thank you for dealing with!

**Comment by shuuji3** [comment]
@kono-paku I'm glad to hear that! 🙂

**Comment by leelax22** [comment]
I've had this problem now. But it disappeared because I used a different browser (chrome to Firefox).
