### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/basic-stateful-set/

### ISSUE THREAD

**Issue by bryanhuntesl** [kubernetes/website#21828]
The behaviour of stateless sets and headless services seems different in GKE in so far as querying the headless service (DNS SRV query) doesn't return the pod names/ip addresses. 

I have seen this behaviour in a number of books and online articles - wondering if it is a bug in google implementation or a change in the specification or an error on my part.

**Comment by sftim** [comment]
This documentation is for generic Kubernetes rather than GKE.

If you're seeing a bug that you can replicate with vanilla Kubernetes, please confirm that and we'll track the defect (we also take pull requests!)
