### ISSUE TITLE
ja: Make docs/setup/production-environment/container-runtimes.md follow v1.17 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#21853]
**This is a Feature Request**

**What would you like to be added**

Update content/ja/docs/setup/production-environment/container-runtimes.md to follow v1.17 of the original (English) text.

**Why is this needed**
content/ja/docs/setup/production-environment/container-runtimes.md is outdated

**Comments**

/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.3/content/ja/docs/setup/production-environment/container-runtimes.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/setup/production-environment/container-runtimes.md

diff
https://gist.github.com/kakts/1e7c163218270a2a1414b641d321aa11

Note
Currently, we use dev-1.17-ja.3 branch. Please open a PR targeting the branch.

**Comment by inductor** [comment]
@kakts 

お願いが2つあります

1. Captureとcontent_templateの差分は取り除いてください
2. diffのハイライトをGistに入れてください

**Comment by kakts** [comment]
@inductor   ありがとうございます。こちら修正しました
