### ISSUE TITLE
Add site search to main page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#21867]
**This is a Feature Request**

**What would you like to be added**
Add a facility to search the website to the main page, https://kubernetes.io/

**Why is this needed**
Let's say someone arrives at https://kubernetes.io/ and wants to find the download page. Well, the top 3 results on https://kubernetes.io/search/?q=downloads look pretty relevant.
The trouble is there's no form on https://k8s.io/ to do that search, and it's not obvious that navigating round the site will reveal that search.

**Comments**
Consider both desktop and mobile browser use cases. The main page is some readers' first impression of Kubernetes, so it's important to make a good one.

Most people known how to use Google _(other search products exist)_ so fixing this need not be a priority.

**Comment by celestehorgan** [comment]
I think this dovetails with https://github.com/kubernetes/website/issues/20895 as well.

From an implementation perspective (from what I can tell) the site uses a custom google search engine. 

First step would be identifying who the admin(s) of that are. 
Second step would be identifying what directories are scanned
Third step would be including the pages we now want to include.
Fourth step is _fairly_ easy – add `partials/search_input.html` to the layout template you want to see a search box on.

The third step requires some thought, however. If we put a search box on the homepage, is the expectation that it searches the _entire_ site or just the docs+blog? From a UX perspective, if I see a search box on the homepage I kind of expect it to search everything.

**Comment by sftim** [comment]
The site search already covers the whole site, so this is really about adding a form to the front page.

**Comment by sftim** [comment]
For an example of where to put a site search on the main page, see https://cloud.google.com/

(I'm not proposing to move the search UI there across for the whole site; that would be a separate issue).

**Comment by sftim** [comment]
Also relevant: issue #22020

**Comment by sftim** [comment]
/area web-development
(ish)

**Comment by dipesh-rawat** [comment]
I'm more than happy to work on it and get this moving forward.
 
 /assign
