### ISSUE TITLE
ja: Make docs/concepts/_index.md follow v1.17 of the original text

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#21894]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/_index.md to follow v1.17 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/_index.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.3/content/ja/docs/concepts/_index.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/concepts/_index.md

diff between translated and v1.17
https://gist.github.com/887e76303ced2c8ee49eab1354c91f77

**Note**
Currently, we use **dev-1.17-ja.3** branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by hiyokotaisa** [comment]
確認する限りでは、主に英語のtitle caseの修正ですので日本語版に修正するべき点がありませんでした。

**Comment by oke-py** [comment]
`Kubernetesオブジェクトについて知る`のリンク先に`#kubernetes-objects`がついていますね。

**Comment by hiyokotaisa** [comment]
@oke-py 現在の`dev1.17-ja.3`ブランチでは、日本語訳のバージョンには`#kubernetes-objects`タグはついていないようです
https://github.com/kubernetes/website/blob/dev-1.17-ja.3/content/ja/docs/concepts/overview/working-with-objects/kubernetes-objects.md
```
## Kubernetesオブジェクトを理解する
```

しかし、原文の方にはタグがついています。
```
## Understanding Kubernetes objects {#kubernetes-objects}
```

このようなケースでは、どう対応するのがよいでしょうか。一旦`docs/concepts/_index.md`側ではタグを指定しておいて、あらたにissueを切って`docs/concepts/overview/working-with-objects/kubernetes-objects.md`にタグを付与する対応をするほうがよいでしょうか。

**Comment by inductor** [comment]
必要ならばタグを付けてしまって大丈夫だと思います！

**Comment by oke-py** [comment]
1つのPRで大丈夫です！
- `docs/concepts/_index.md`でタグを指定する
- `docs/concepts/overview/working-with-objects/kubernetes-objects.md`でタグを付ける

**Comment by hiyokotaisa** [comment]
@inductor @oke-py ありがとうございます、そのように対応します！
