### ISSUE TITLE
Improper search result page number and commit message displays in docs

### ISSUE THREAD

**Issue by harik8** [kubernetes/website#21924]
In Kubernetes docs when you search, search results page number displays as "12345678910". There is no space between page numbers. 

```
a Kubernetes cluster, and the kubectl command-line tool must be configured to communicate with your cluster.
12345678910
```

The commit message appears at the bottom of the page which is irrelevant.

`Page last modified on May 05, 2018 at 6:00 PM PST by Convert site to Hugo (#8316) (Page History)`

Also, the hyperlink appears in each search results which is not needed.

```
Search Results
Configuring your kubernetes cluster to self-host the ...
https://v1-15.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/self...
```
eg: https://kubernetes.io/docs/search/?q=hostpath&page=10

**Expected Output.**

Search results in a proper way.

**Comment by tengqm** [comment]
/language en
Sounds like 3 different issues, :)

**Comment by sftim** [comment]
Can you clarify the issue(s) you're reporting @harik8? If you can include a screenshot that's helpful; if you can open a new issue for each separate defect that's even better.

**Comment by shuuji3** [comment]
> In Kubernetes docs when you search, search results page number displays as "12345678910". There is no space between page numbers.

This problem happens when using Bing search. Here is the screenshot:
![Screenshot from 2020-08-09 13-01-08](https://user-images.githubusercontent.com/1425259/89724640-b48b1f80-da40-11ea-80f0-adde5f9e4e77.png)

**Comment by sftim** [comment]
/area web-development

For context, the website uses Google Search unless corporate filtering / state-level censorship / similar restrictions prevent using Google, and for those readers there is a fallback to Bing search.

**Comment by shuuji3** [comment]
/remove-lifecycle rotten

I'm going to create a PR to fix this styling issue.

**Comment by shuuji3** [comment]
It took a long time but I made a PR to fix this issue.
