### ISSUE TITLE
investigate removal of jquery-ui-1.12.1.min.js, update tab component

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#21922]
**This is a Feature Request**
Investigate jquery-ui dependencies in the site (tab component) to determine if this library can be removed.
Look into content formatting issues in the tab panels (tab shortcode).

**What would you like to be added**
Investigate using bootstrap for the tab component to remove the dependency on jquery-ui.
Clean up reference to jquery-ui in the head partial and clean up any related CSS.

**Comments**
Previous tab component:
![tab_1 17](https://user-images.githubusercontent.com/1696019/85166831-da145d80-b235-11ea-939d-74d6adcf05de.PNG)

Current tab component:
![docsy_tabs](https://user-images.githubusercontent.com/1696019/85166612-886bd300-b235-11ea-98de-b56832664263.PNG)

**Comment by pigletfly** [comment]
I guess it's caused by the upgrade of jquery-ui,but we can modify the css styles.

**Comment by kbhawkey** [comment]
Related to issue #22024.

**Comment by kbhawkey** [comment]
Updated the tabs shortcode to use Bootstrap library.
/close
