### ISSUE TITLE
images not displaying on home page, firefox, docsy theme

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#21923]
**This is a Bug Report**
This is an old bug, resurfacing again.
https://github.com/kubernetes/website/issues/19363

**Problem:**
See previous issue for information.
https://kubernetes.io/

**Comment by sftim** [comment]
I tried to replicate this and didn't see symptoms. What are the steps to replicate it?

**Comment by kbhawkey** [comment]
With Firefox, viewing `kubernetes.io`, three svg images are not displayed. 
Inspect for `ocean-nodes .main-section .image-wrapper`. Add width: 100%.
Screen size min-width: 768px (tablet size?).
I am viewing with laptop.
Not evident w/Chrome.

**Comment by sftim** [comment]
I looked just now and the symptoms show up for me too. I could have sworn they were showing OK earlier (different monitor setup, same browser process).

Definitely a valid issue.
/priority important-longterm
/kind bug

**Comment by Arhell** [comment]
fixed, able to close
