### ISSUE TITLE
debug DNS resolution 404 not found

### ISSUE THREAD

**Issue by ran-huang** [kubernetes/website#21930]
This page returns 404 not found. 
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/.

**Comment by tengqm** [comment]
Yup. It was moved over to a different folder ...

**Comment by ran-huang** [comment]
@tengqm Thanks! Do you know what is the currently available link for the English doc? The search is not very helpful😕
btw, the Chinese link is still working though... https://kubernetes.io/zh/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by tengqm** [comment]
Well, I think we should move it back.
Proposing a fix now.
If it turns out that team doesn't want to move it back, we may need to add a redirect entry as an alternative.

**Comment by sftim** [comment]
@tengqm let's discuss the move back in this issue. Can you set out a case for reverting?

**Comment by tengqm** [comment]
@sftim Sure.
I'm assuming that there are audiences from different user groups reading the docs and even learn by doing. A long while ago, we (primarily chenopis) started an initiative to provider journeys for different group of users. Some of those efforts are still [here](https://github.com/kubernetes/website/tree/master/deprecated/content/en/docs/user-journeys/users), archived into a `deprecated` directory. The idea was to help users find the materials they need based on their roles in operating or using Kubernetes. This background is where I came from.

For cluster operators (or admins, or whatever you call them), they often times enjoy a higher privilege (aka more responsibilities) to keep the cluster running healthily. That means they need to ensure the following things work properly:

  - access control and admission control
  - storage provisioning and networking setup
  - auditing, logging and monitoring
  - upgrade cluster config
  - secure cluster data and backup them properly
  - ...

These are not concerns of an application developer. An application developer uses the cluster to deploy, scale their applications. For example, they rarely have a say regarding when to evict a Pod out of a node and they cannot decide whether and which upstream DNS server is used. Similarly, a cluster operator doesn't care that much how application Helm charts are composed, version controlled.

A production deployment is pretty different from the minikube one we use for learning and erring.

So ... DNS and related tasks is not an application level thing. It is a cluster administering job. That is the reason I'm proposing this (partial) revert.
