### ISSUE TITLE
Kubernetes documentation search is not working fine from last few days

### ISSUE THREAD

**Issue by msrinivascharan** [kubernetes/website#21954]
i observed a major cosmetic change happened to Kubernetes documentation recently, before to that search option was pretty good. Now, it’s not working fine

If I type “security context” or “resource requests” in the search box, in the results, it is showing “fetching results….”, no result even after 15 minutes waiting also.

It works with single words like “security” and “resources” like that, but results. its not working with spaces.

**Comment by sftim** [comment]
I think #21823 fixed this.

/close

Please feel free to reopen it if you still see symptoms @msrinivascharan
