### ISSUE TITLE
Tidy wording for “Authenticating” reference

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#21955]
**This is a Bug Report**

**Problem:**
Some of the wording in [Certificate Signing Requests](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) is not idiomatic English.
Example: “Few steps are required in order to get normal user to be able to authenticate and invoke API” where typical English usage has “_**A**_ few steps are required in order to get normal user to be able to authenticate and invoke API”

**Proposed Solution:**
Review the page _Certificate Signing Requests_. Open a pull request with any changes you want to make the page be more in line with the Kubernetes documentation [style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

Feel free to replace sentences as well as tweaking the wording.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/

**Additional Information:**
This follows on from https://github.com/kubernetes/website/pull/20443
/language en
/kind cleanup
/good-first-issue

This issue is a good choice for someone who is fluent in written English.

**Comment by vinu2003** [comment]
@sftim I am new here and would like to learn and contribute - would like to take this up.

**Comment by vinu2003** [comment]
@sftim I am tied up with another task and I am fully into it. 
Apologise. I shouldn't be blocked others from picking this up and progressing.
un-assigning here

**Comment by EmilyM1** [comment]
PR for this issue:
https://github.com/kubernetes/website/pull/22063

**Comment by sftim** [comment]
Fixed in PR #22063
Thanks @EmilyM1

**Comment by sftim** [comment]
/remove-lifecycle rotten

If anyone wants to work on this, please feel free to go ahead.

**Comment by soniasingla** [comment]
@sftim, just want to double check, isn't this has been fixed [here](https://github.com/kubernetes/website/pull/22063)

**Comment by sftim** [comment]
Ah yes. Fixed already.
/close
