### ISSUE TITLE
More clarification on the handler implementation and its usage for probe type

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#21967]
**This is a Bug Report**

**Problem:**
The documentation page https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ states that: `A Probe is a diagnostic performed periodically by the kubelet on a Container. To perform a diagnostic, the kubelet calls a Handler implemented by the Container`

Out of the 3 handlers, `ExecAction`, `TCPSocketAction` and `HTTPGetAction` which ones actually interact with the container itself and which ones actually deal with the application.
For example, the `ExecAction` and `HTTPGetAction` seem to be either executing an action in the application and the HTTPGetAction also gets its response from the application running inside the container from a specific path. 
Whereas the `TCPSocketAction` only checks for whether some ports are opened by the container without interacting with the application inside the container.

It will be better if we could be more specific in the documentation rather than just saying `implemented by container` it should be more detailed.

**Proposed Solution:**
Clearly mention which type of handler deals with container itself and which ones deal with the application running inside the container. Also it would be better to mention which type of Handler is a preferred one for which type of probe.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by tengqm** [comment]
The container is supposed to provide endpoints to all three probes, that is what `implemented by container` means. Even for TCP socket checks, you will need have something listen to the port being checked, right?
These probes are mechanisms provided by k8s as a convenience for developers, who then can decide which one(s) to support and how to support, based on the application hosted in the container.

**Comment by adityamandhare** [comment]
@tengqm when you say `The container is supposed to provide endpoints to all three probes`, do you mean the container is supposed to facilitate all three handlers?
My understanding is that kubelets use handlers to probe containers.

**Comment by tengqm** [comment]
Sorry for the confusion. I should say "All three kinds of probes are optional and it is the container's responsibility to implement them if supported".

There are three types of probes, for some probes, you can choose different handlers, based on the business problem you are solving.

**Comment by adityamandhare** [comment]
Thanks @tengqm for the clarification. This answers my question. I will close this issue.
