### ISSUE TITLE
Issue with Pod Conditions type field values: "Ready" and "ContainersReady"

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#21966]
**This is a Bug/Feature (TBD) Report**

**Problem:**
The Pod Condition's `type` field takes two values: `Ready` and `ContainersReady`. 
The `Ready` type states that the Pod is ready to serve request and that the Pod can be added to the load balancing pools for the matching service. 
The `ContainersReady` just states that all containers of the pod are ready. 

How is the Pod being ready different than the containers inside the pod being ready? What happens before the containers being ready that makes the Pod ready to serve requests?
How can a pod be ready to serve the requests without the containers inside being ready? Wouldn't the requests coming in to the pod fail of the containers inside it are not ready to process the request?

**Proposed Solution:**
Provide a better explanation of the Pod Conditions field values "Ready" and "ContainersReady"

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by Cweiping** [comment]
The page has described[ the difference between the two states](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-status), but it has not been explicitly emphasized.Need a clearer description.
This should be seen as a bug or feature? @tengqm @sftim

**Comment by sftim** [comment]
I wouldn't add a /kind label here TBH and if I did I'd lean towards /kind cleanup

I agree, this page could be better worded. A diagram showing states and transitions would help a lot.
/language en

and, I think:
/priority backlog
