### ISSUE TITLE
Link to the Handler document on the page does not work

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#21964]
**This is a Bug Report**

**Problem:**
The page https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ has a `Container probes` section. This section contains link to a Handler documentation. This link does not work: https://godoc.org/k8s.io/kubernetes/pkg/api/v1#Handler

**Proposed Solution:**
Update the link to the handler documentation on the page in the `Container probes` section of the page.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by shuuji3** [comment]
/assign

I'm going to fix the link to the correct one.
