### ISSUE TITLE
Explanation for "Pod Conditions" section is not clear.

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#21965]
**This is a Bug Report**

**Problem:**
This is an issue for better explanation for the `Pod Conditions` section on the page https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/.
There is a statement `A Pod has a PodStatus, which has an array of PodConditions through which the Pod has or has not passed.` Does this mean that the PodConditions array is an array of fixed length of pre-decided conditions? Does the array also include the conditions through which the Pod has not been through?

**About the status field**
`The status field is a string, with possible values "True", "False", and "Unknown".`
What kind of Truthy or Falsy values are we talking here. Is it supposed to tell whether a Pod has been in this condition (True) or not (False). What is `Unknown` then?

**About the "type" field**
It tales 4 values: `PodScheduled `, `Ready `, `Initialized ` and `ContainersReady `.
Are these supposed to occur in this order? Do these correspond to the PodConditions ie. does each one of it make an entry in the PodConditions array that is talked about in this section?

**Proposed Solution:**
Provide a better explanation of the Pod Condition section.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by sftim** [comment]
/priority backlog
/language en

It'd be great to see this page tidied up
