### ISSUE TITLE
Are all container probes by the kubelet optional?

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#21968]
**This is a Bug Report**

**Problem:**
The page https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ states that:
`The kubelet can optionally perform and react to three kinds of probes on running Containers.`
Are all the three probes `livenessProbe`, `readinessProbe` and `startupProbe` really optional? is a Kubelet not required to have at least one probe into the container to check its status? If not how will the kubelet know if the container is down?

**Proposed Solution:**
If at least on of the container probe is required, then it should be explicitly mentioned that although it is not required to have all of them but at least of of the probe must exist. Again this is only if the at least one of the probe is required.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by tengqm** [comment]
I think the current docs are correct. A `kubelet` does not rely on the probes for determining whether a container is alive or ready. The `kubelet` gets all its need from the underlying container runtime which manages the container's lifecycle.

**Comment by sftim** [comment]
The current documentation is accurate; all three kinds of probe are optional.

@adityamandhare I'll close this
/close
