### ISSUE TITLE
Issue with k8s.io/docs/tasks/service-catalog/install-service-catalog-using-sc/

### ISSUE THREAD

**Issue by ingenthr** [kubernetes/website#22008]
**This is a Bug Report**

**Problem:**

After getting "sc" tool, I then had to install `cfssl` and `cfssljson`.  Those dependencies aren't listed.  Chances are they were just already installed on the author's machine.  It will fail thusly:

```
$ sc check
Dependency check failed
Error: cfssl,cfssljson commands not found in the PATH
```

**Proposed Solution:**

**Page to Update:**
Update the page to include these dependencies and commands. 

```
$ go get -u github.com/cloudflare/cfssl/cmd/cfssl
$ go get -u github.com/cloudflare/cfssl/cmd/cfssljson
```

**Comment by sftim** [comment]
I'm not sure whether or not https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-sc/ should stay given that https://github.com/kubernetes/website/issues/20232 is cleaning up third party content, and `sc` is fairly closely tied to GCP.

My gut feeling based on https://github.com/kubernetes/website/issues/13017, the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/), and [_doc-policies-for-third-party-content_](https://github.com/kubernetes/enhancements/blob/master/keps/sig-docs/20191020-doc-policies-for-third-party-content.md) is that https://k8s.io/docs/tasks/service-catalog/install-service-catalog-using-sc/ should go.

It's OK to link from https://k8s.io/ to a page that explains how to use `sc` to set up the Service Catalog extensions, and it's fine to bring that target page up to date.

/language en

**Comment by sftim** [comment]
I'm decided. https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-sc/ should go.
@ingenthr this might not be quite what you'd hoped for - sorry!

**Comment by ingenthr** [comment]
Thanks for the update.  The only thing I'm confused by is you said "sc is fairly closely tied to GCP".  We've been using service brokers and service catalog as something neutral and I did come across [docs that indicate GCP has deprecated service catalog](https://github.com/googlearchive/k8s-service-catalog).

In any case, I respect your change/decision.  I'm just trying to fit Service Brokers and Service Catalog into whether or not it's something one should rely on.  I know you can't answer that question though.  :)

**Comment by sftim** [comment]
Installing Service Catalog? Fine. Installing it with `sc`? Problematic, because `sc` is fairly closely tied to GCP. See issue #13017.

**Comment by sftim** [comment]
I'd be happy to see a replacement page go up that doesn't mention `sc` at all but _does_ cover how to set up Service Catalog, talk OSBAPI, try it out, etc.

**Comment by ingenthr** [comment]
Oh, I see!  Thanks for the clarification.
