### ISSUE TITLE
Isolation of pods associated with a Replica Set

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#22006]
**This is a Bug Report**

**Problem:**
The page https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/ states that `It's through the Pods' metadata.ownerReferences field link that the ReplicaSet knows of the state of the Pods it is maintaining and plans accordingly.` From this it seems that this is how the Replica Set and Pods are linked. 

The ReplicaSet uses the labels only to acquire the existing pods right? as per `A ReplicaSet identifies new Pods to acquire by using its selector. If there is a Pod that has no OwnerReference or the OwnerReference is not a Controller and it matches a ReplicaSet's selector, it will be immediately acquired by said ReplicaSet.`

Now in order to isolate the pods from the ReplicaSet, the page says that we need to change the labels. However, if the `metadata.ownerReferences` pod field is the real link used by the ReplicaSet, then how can simply changing the labels of the pods isolate them from the Replica Set controller?

**Proposed Solution:**
Either update the statement which says the `metadata.ownerReferences` is the link used by ReplicaSet to know the state of the Pods it is maintaining OR change the way of isolation only if incorrect (I am not sure which one is correct.)

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

**Comment by sftim** [comment]
This is a general concept not just relevant to ReplicaSet:
_how do the labels and selectors that a controller uses interact with `ownerReferences`, finalizers, garbage collection and related topics_?

I'd favor covering it once and then having each workload controller hyperlink to a page that explains that detail.

**Comment by adityamandhare** [comment]
> This is a general concept not just relevant to ReplicaSet:
> _how do the labels and selectors that a controller uses interact with `ownerReferences`, finalizers, garbage collection and related topics_?
> 
> I'd favor covering it once and then having each workload controller hyperlink to a page that explains that detail.

@sftim does simply changing labels help isolate pods from the controller?

**Comment by sftim** [comment]
> does simply changing labels help isolate pods from the controller?

Sure. If you have a ReplicaSet that's managing 2 Pods _A_ and _B_, and you delete all the labels on Pod _A_ then Pod _A_ continues running but the ReplicaSet sees that there is now only 1 healthy Pod matching its selector. The ReplicaSet creates a new Pod. 

If you then delete the ReplicaSet, Pod _A_ stays running.

You can try this out.

**Comment by sftim** [comment]
@adityamandhare I think a good way forward here is if you open a new issue about having a page to clarify the detail you weren't sure on (about labels & selectors vs. ownerReferences)
and then close this issue referencing the new issue.

how does that sound to you?

**Comment by adityamandhare** [comment]
okay I can do that. Thanks!

**Comment by adityamandhare** [comment]
@sftim Created a new issue https://github.com/kubernetes/website/issues/22022 for clarification. Closing this one.
