### ISSUE TITLE
maintain a copy of API references from snapshot branches

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#22016]
**This is a Feature Request**
Investigate a way to maintain copies of the last four API references in 
the current website.The references were previously available, but never maintained; the content was outdated.
There are a number of readers as well as external documentation that depend on linking to the
previous API references from the `kubernetes.io` site.
Providing a link to the API reference in the snapshot version takes the reader to another version of the site.
Do readers want access to the API references from a single site?

**What would you like to be added**
Create a build (and clean) target to copy the four previous API references, using the "snapshot" branches,
to the current site. The reference directories will be copied to:
`/website/static/docs/reference/generated/kubernetes-api`

Along with this change, investigate the related links in the `static/_redirects` file.

**Why is this needed**
Provide an integrated interface from the k8s.io site to read the API references.

**Comments**
Ensure that at release time, the reference directories are updated to remove the previous API references and create a new set of references (from the snapshot branches).

**Comment by kbhawkey** [comment]
Temporarily assigning myself.
/assign

**Comment by kbhawkey** [comment]
Related PRs: #21931,#21929 .

**Comment by kbhawkey** [comment]
I am thinking about creating these directories:
website/static/docs/reference/generated/kubernetes-api/latest
website/static/docs/reference/generated/kubernetes-api/v1.17
website/static/docs/reference/generated/kubernetes-api/v1.16
website/static/docs/reference/generated/kubernetes-api/v1.15
website/static/docs/reference/generated/kubernetes-api/v1.14
Other ideas?

**Comment by kbhawkey** [comment]
@tengqm @joelsmith

**Comment by sftim** [comment]
I'm not really keen on a static `latest` in that list. The trouble is that it encourages people to link there, only for the thing they linked to to become out of date when the next release happens. I really think it's better to link to a specific API.

Ideally the API reference also lets you choose to view a different version, that's definitely a SIG Docs ambition.

I think we either want 
_all_ these URLs to all work:
https://v1-13.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/
https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/

_or_ all of these:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/

**Note** that I included v1.13 there.

Whichever of those 2 groups we pick, it is relatively straightforward to then have https://kubernetes.io/docs/reference/ hyperlink to the stable URI that we chose.

**Comment by kbhawkey** [comment]
I understand the concern about using `latest` and added that to the list as a compromise.
There is an "API overview" page that external sources could link to? 
The point of this issue is to provide a "real" integration of the references (similar to past behavior) -- not just links and redirects.
I don't think it is fair to link to the snapshot and have to navigate back and forth to the current site.
From the sample URLs, I_think_ the second set makes sense.

**Comment by sftim** [comment]
As a compromise, we could define that 
https://kubernetes.io/docs/reference/generated/kubernetes-api/latest/ is always a 307 redirect to the latest API documentation. How about that?

**Comment by sftim** [comment]
To move this forward, how about making `latest` be a 307 _for now_. And then, with that in place, we can have a separate discussion about when and whether to replace the 307 redirect with static content.
(In that future discussion we can cover topics like permalinks, `noindex`, URL durability, whatever).

**Comment by kbhawkey** [comment]
Another idea: Remove the version info
from the reference directory pages and URLs and instead use something like:
`kubernetes.io/docs/reference/kubernetes-api/` as a permanent URL for the latest or current version of the API reference.
Could remove the "api-index" page and move the "taints" reference page to another directory.
The API reference source could reside directly under `static/docs/reference/generated/kubernetes-api` which implies the current or latest version.

**Comment by sftim** [comment]
>  Remove the version info from the reference directory pages and URLs 

If we do that, how can someone find the API reference for a specific release, or find the URL for that to share with someone? Because releases change the API it seems important that readers can select the API version they want to read up about.

**Comment by kbhawkey** [comment]
Still thinking on this.
The snapshot versions maintain the version information in the URL.
The current docs (kubernetes.io) serve the "current or latest" version of the API reference as "kubernetes-api".
Readers know what version they are reading based upon the information provided on the page/site.
I _think_ we could do a better job of identifying the version number of the published docs.

**Comment by sftim** [comment]
Also, ultimately I'd like to publish API references for patch versions as well - or, at least, I'd prefer not to make that more difficult to add.

**Comment by kbhawkey** [comment]
There may be more to discuss about:
* Including previous API reference pages with the "latest" API reference pages and
* Providing a more permanent URL to access the "latest" API reference pages
As the API reference generator tool is changing, I plan to close this issue.
/close
