### ISSUE TITLE
Clarification over the use of metadata.ownerReferences Vs pod labels for link between Replica controller and Pods

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#22022]
**This is a Bug Report**

**Problem:**
The page https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/ states that `It's through the Pods' metadata.ownerReferences field link that the ReplicaSet knows of the state of the Pods it is maintaining and plans accordingly.` From this it seems that this is how the Replica Set and Pods are linked. 

The ReplicaSet uses the labels only to acquire the existing pods right? as per `A ReplicaSet identifies new Pods to acquire by using its selector. If there is a Pod that has no OwnerReference or the OwnerReference is not a Controller and it matches a ReplicaSet's selector, it will be immediately acquired by said ReplicaSet.`

Now in order to isolate the pods from the ReplicaSet, the page says that we need to change the labels. However, if the `metadata.ownerReferences` pod field is the real link used by the ReplicaSet, then how can simply changing the labels of the pods isolate them from the Replica Set controller?

There has been discussion on this in a separate issue https://github.com/kubernetes/website/issues/22006 

**Proposed Solution:**
Provide more clarification on the use of metadata.ownerReferences Vs pod labels for establishing link between controllers and pod. Refer issue https://github.com/kubernetes/website/issues/22006 for more details.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
And all other pages where the relationship needs to be clarified

**Comment by sftim** [comment]
In #22006 I recommended adding one page that compares selector and ownerReferences links between Pods and controllers (and, in fact, it goes beyond Pods, it's any resource that a controller manages based on labels).

&hellip;and I still recommend that. The other pages can link to the new page.
