### ISSUE TITLE
Search this site should be above the section

### ISSUE THREAD

**Issue by 532910** [kubernetes/website#22020]
The page on the screenshot is https://kubernetes.io/docs/home/

This site is `kubernetes.io`.

This form searches within documentation, not this site:

![image](https://user-images.githubusercontent.com/14617699/85473093-6bc7f600-b5bb-11ea-8335-8c632619b44e.png)

**Comment by sftim** [comment]
Hi @532910 

That search form searches the whole site. Can you give an example of how the search appears limited?

/triage needs-information

**Comment by 532910** [comment]
Yep, it's my fault. But I was confused by oder: `Search this site` should go **before** `Documentation` section.

**Comment by sftim** [comment]
If you can make a mockup or sketch of how you think the page should look instead, I think that'll really make it clear what you're not happy about with the existing page. Would you have time to do that?

(even a pencil sketch is fine!)

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/85532235-330a3a00-b618-11ea-8e57-fed76ccfdd8e.png)

**Comment by 532910** [comment]
is any update there?

**Comment by sftim** [comment]
@532910 thanks for the update. Can you briefly outline why you'd like this improvement made?

**Comment by 532910** [comment]
> Can you briefly outline why you'd like this improvement made?

As it's a search through the documentation and not the entire site.

1. The hamburger button right to the search field shows full site menu. They are both in the same line, but have different places in the hierarchy. The hamburger button is the root, search field belongs to Documentation section.

2. The search field is a part of Documentation. So it must be under Documentation title, not vice versa.

Clear?

**Comment by sftim** [comment]
Here's what I think could work:
- keep the search field where it is (it's part of [Docsy](https://www.docsy.dev/))
- add _another_ search field in the top nav, that's shown even when Docsy's built-in search input is shown
- add some code to sync things so that typing into either field changes the query in both

That feels like it'd achieve roughly what @532910 is asking for, without needing lots of deviation from upstream Docsy.

**Comment by 532910** [comment]
So what is the problem to hide Docsy's search field afterwards?

**Comment by sftim** [comment]
> So what is the problem to hide Docsy's search field afterwards?

I guess we could hide Docsy's search field. What does that add, though? Also, does it break any viewing experience (eg mobile)?

**Comment by 532910** [comment]
Two search field are confusing and eat up space that is expensive on mobile.
