### ISSUE TITLE
Announcement banner now in Google search snippets

### ISSUE THREAD

**Issue by craigbox** [kubernetes/website#22036]
The announcement banner text (merged in #21505) is being used as the Google search snippet for docs pages.  This may not have been your intention.

https://www.google.com/search?q=kubernetes+cluster+bootstrapping

![image](https://user-images.githubusercontent.com/132510/85593325-d706dc00-b63e-11ea-871d-7c67f7f9a292.png)

**Comment by sftim** [comment]
@craigbox SIG Docs doesn't have a good way to improve Google's indexing algorithm. The text is in an `<aside>` HTML element which _should_ mark it as an aside: content only indirectly related to the main content.

I'd characterize this as a Google bug. There _are_ a lot of Google people in the Kubernetes ecosystem but probably not from the web search side.

Do you agree with that characterization?
/triage awaiting-more-evidence

**Comment by craigbox** [comment]
I can't find anything suggesting Google has ever ignored `<aside>` elements, and I can find a comment from someone at Google saying they explicitly ignore them ([John Mueller](https://twitter.com/JohnMu/status/708300431777275904) via [seroundtable](https://www.seroundtable.com/google-aside-tag-seo-21774.html)).

The supported way to mark something not to go in a snippet is the `data-nosnippet` attribute: [Search](https://developers.google.com/search/reference/robots_meta_tag#data-nosnippet-attr), [Webmasters](https://support.google.com/webmasters/answer/79812?hl=en).

I can raise a feature request with the search team to ask them to treat `<aside>` like `data-nosnippet` but from a Kubernetes users perspective, changing the site will get to a better outcome quicker.

**Comment by sftim** [comment]
It sounds useful to add `data-nosnippet` to the announcements.

**Comment by kbhawkey** [comment]
I would adjust to "fix now" 😄

**Comment by celestehorgan** [comment]
Yikes, sorry guys! I would also mark as fix now
