### ISSUE TITLE
Heading text partially hidden by site's top-nav when visiting link with anchor

### ISSUE THREAD

**Issue by chalin** [kubernetes/website#22048]
For example, visit https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver
What I see is the heading text partially hidden by the site's top-nav:

> ![image](https://user-images.githubusercontent.com/4140793/85635945-26540900-b64d-11ea-9c3a-084a2866ced5.png)

Visiting most entries in that page's TOC will have a similar effect.

**Comment by sftim** [comment]
/kind bug

I think we might already have an issue open about this.

**Comment by Arhell** [comment]
@chalin fix

**Comment by sftim** [comment]
/close
Fixed in #22327
