### ISSUE TITLE
Investigate removing /static/js/search.js

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22045]
Umbrella issue: https://github.com/kubernetes/website/issues/22024

Investigate removing `/static/js/search.js`. This will potentially involve pointing this template https://github.com/kubernetes/website/blob/master/layouts/docs/search.html to Docsy's search.js. 

There's a reasonably large chance that this won't work in any way, shape or form. If so, comment what you tried and what happened, then close the issue.

**Comment by kbhawkey** [comment]
I investigated the possible removal of `static/js/search.js` and associated files in the site.
There are similar files provided by the Docsy theme, but the site makes use of a custom `k8s search`.
I found that these files work together to create the site search as follows:
`assets/js/search.js` -> `layouts/docs/search.html` -> `static/js/search.js` (custom k8s search)

**Comment by celestehorgan** [comment]
Perfect! Thanks for reporting back, @kbhawkey!
