### ISSUE TITLE
Remove /scripts/js/anchor-4.1.1-min.js

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22040]
Umbrella issue: https://github.com/kubernetes/website/issues/22024

Remove the `/scripts/js/anchor-4.1.1-min.js` and the corresponding call in [/layouts/partial/head.html#L77](https://github.com/kubernetes/website/blob/master/layouts/partials/head.html#L77).

_In theory_ we now use the anchor.js packaged with Docsy, however in practice this may not be the case 😅. You'll want to check the build carefully to ensure that anchor links are being generated for subheaders where we want them (on docs pages), and not where we don't (on index pages, i.e.). 

If for some reason we can't remove this file, leave a comment in this issue or in the umbrella explaining what happens and why we can't remove it, then close the issue.

**Comment by luckyvs1** [comment]
@sabazubair are you still planning to work on this issue?

**Comment by sabazubair** [comment]
@luckyvs1 Hey Lucky! I completed this issue and I am waiting for it to be reviewed.

**Comment by luckyvs1** [comment]
@sabazubair you closed your PR so it won't be able to be reviewed you probably need to reopen it https://github.com/kubernetes/website/pull/22311 so someone can review it

**Comment by sabazubair** [comment]
Oh! Oops. Thanks for letting me know. I'll reopen it now.
