### ISSUE TITLE
Issue with k8s.io/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by Jakub-B** [kubernetes/website#22055]
**This is a Bug Report**

**Problem:**
Over ten minute i have only black board. I work?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by sftim** [comment]
Hi @Jakub-B 

I wasn't able to replicate the symptoms. That page works for me.

If you try it on a different device does that help get it working?

/triage needs-information

**Comment by Jakub-B** [comment]
I used Chrome and it doesn't work. I changed to EDGE and it booted.

THX


czw., 25 cze 2020 o 18:18 Tim Bannister <notifications@github.com>
napisał(a):

**Comment by irvifa** [comment]
I’ll close this issue then
/close
