### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by meirzee** [kubernetes/website#22052]
**This is a Bug Report**

RollingUpdate and recreate strategy are well explained on the documents but when trying to implement I found it is not so Trivial 
and got some error

**Proposed Solution:**
It will be great  if the documentation will include an example of implementing these strategies.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

Thanks in advanced
Meir Zeevi

**Comment by tengqm** [comment]
Pasting your error message would be helpful for people to know whether it is the documentation to be fixed.
