### ISSUE TITLE
Investigate removing JQuery UI, re-implment pencil "edit" icon

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22059]
Umbrella issue: https://github.com/kubernetes/website/issues/22024 

Investigate removing `/scripts/js/jquery-ui-3.2.1.js`. 

This will involve the following:

1. Re-implementing the pencil in the "edit" button in [/assets/scss/_base.scss#L798](https://github.com/kubernetes/website/blob/master/assets/scss/_base.scss#L798)

<img width="941" alt="Screenshot 2020-06-25 at 10 03 42" src="https://user-images.githubusercontent.com/17999517/85765711-36123280-b6cb-11ea-9769-3fb48aaf699c.png">

Docsy comes bundled with FontAwesome (located in the submodule – `themes/docsy/static/webfonts`) – so I'd suggest trying a FontAwesome icon.

2. Remove the call in [/layouts/partials/head.html#L78](https://github.com/kubernetes/website/blob/master/layouts/partials/head.html#L78) to the JQuery UI

3. Remove the `/static/images/jquery-ui` directory 

4. Remove the folllowing in `/static/css`:
*  the `/static/css/images` directory
*  `/static/css/jquery-ui.min.css`
* `/static/css/jquery-ui.structure.min.css`
* `/static/css/jquery-ui.theme.min.css`

5. Remove the call in [/layouts/partials/css.html#L18](https://github.com/kubernetes/website/blob/master/layouts/partials/css.html#L18) to the CSS style sheet

**Comment by celestehorgan** [comment]
Upon further inspection, you might be able to remove JQuery UI _without_ redoing the pencil icon.

Regardless, it might be a nice opportunity to do that anyways. It would be good to switch to using an icon library :)

**Comment by shuuji3** [comment]
Hi, @celestehorgan

> Upon further inspection, you might be able to remove JQuery UI without redoing the pencil icon.

Then can I work on re-implementing the pencil in the "edit" button as a separate issue? Though I don't know well about JQuery UI, I often use the FontAwesome icon on my web development.

**Comment by celestehorgan** [comment]
Sorry this took me a month!! 🙇‍♀️ 

@shuuji3 To start, re-implement the pencil icon using fontawesome. And then we'll come back to this ^^;

**Comment by shuuji3** [comment]
@celestehorgan No worries! :slightly_smiling_face: 

Recently, in #23227, a new edit link was implemented and I think it fits the Docsy theme well. So it seems that we don't need to reimplement this icon anymore.

**Comment by celestehorgan** [comment]
@shuuji3 Agreed!

Per the [readme](https://github.com/kubernetes/website/tree/master/static/js) here, I think we need to leave Jquery as well for now.

Closing!
