### ISSUE TITLE
Issue with k8s.io/docs/concepts/scheduling-eviction/assign-pod-node/ in the namedNode section

### ISSUE THREAD

**Issue by adityamandhare** [kubernetes/website#22066]
**This is a Bug Report**

**Problem:**
The page has a section of **nodeName** which is used for node selection constraint. It says ` If it is non-empty, the scheduler ignores the pod and the kubelet running on the named node tries to run the pod.` This statement does not look right. The reason being, even if the pod has a `nodeName` field it still needs a scheduler to look for a node with a matching node name right? So how can a scheduler ignore a pod with `nodeName` field in its spec. 
Also from the part of the sentence `the kubelet running on the named node tries to run the pod.`, it seems as if kubelet is taking suo moto cognizance into searching for pods with matching `nodeName`. Is that correct?

**Proposed Solution:**
Change the sentence ` If it is non-empty, the scheduler ignores the pod and the kubelet running on the named node tries to run the pod.` to
` If it is non-empty, the scheduler ignores the pod if a named node if unavailable. Once a named node is available, the pod will be scheduled to the node and the kubelet running on the named node tries to run the pod.`

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by sftim** [comment]
/sig scheduling

What's the existing behavior? It sounds like what you're intending to document is that for a Pod with `nodeName` set, the scheduler's behavior depends on whether or not a Node matching that `nodeName` is healthy.
Is that true?

**Comment by sftim** [comment]
If a Pod is already assigned to a Node, the scheduler doesn't have any work to do.

**Comment by adityamandhare** [comment]
> /sig scheduling
> 
> What's the existing behavior? It sounds like what you're intending to document is that for a Pod with `nodeName` set, the scheduler's behavior depends on whether or not a Node matching that `nodeName` is healthy.
> Is that true?

@sftim that is correct. The paragraph which I have mentioned in the issue says that if the `nodeName` field in the podspec is non-empty, then the scheduler ignores the pod and the kubelet running on the named node tries to run the pod. There is no mention of the pod already being placed on the node. Also, I don't see any reason why scheduler ignoring the pod needs to be mentioned at all here.

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename looks correct to me.
/triage needs-information

**Comment by adityamandhare** [comment]
> https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename looks correct to me.
> /triage needs-information

okay consider this scenario: A new pod object is created with a non-empty `nodeName` field. Now this is currently not assigned to any node. If the scheduler ignores this pod simply bcoz it has a non-empty `nodeName` field, who will place this pod on the named node?

**Comment by sftim** [comment]
Got it.
> `nodeName` is a _request_ to schedule this pod onto a specific node. If it is non-empty, the scheduler simply schedules this pod onto that node, assuming that it fits resource requirements.

from the API definition. The scheduler is involved here and the existing text is not clear enough. Thank you for explaining @adityamandhare 

/remove-triage needs-information
/kind bug
/priority important-longterm
/language en

**Comment by sftim** [comment]
From the suggested text, “If it is non-empty, the scheduler ignores the pod if a named node if unavailable.”

I think that's not _quite_ right. I believe that the scheduler simply checks that there is currently a Node object with the correct name.

**Comment by adityamandhare** [comment]
> From the suggested text, “If it is non-empty, the scheduler ignores the pod if a named node if unavailable.”
> 
> I think that's not _quite_ right. I believe that the scheduler simply checks that there is currently a Node object with the correct name.

okay sounds good
