### ISSUE TITLE
Investigate removing JQuery 3.2.1

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22064]
Umbrella issue: https://github.com/kubernetes/website/issues/22024

Investigate removing `/static/js/jquery-3.2.1.min.js`. 

Remove the call to it in [/layouts/partials/head.html#L78](https://github.com/kubernetes/website/blob/master/layouts/partials/head.html#L78).

Note: While other scripts on this site use JQuery, as of Docsy we pull in version 3.3.1 so we should be fine. That said, this may cause issues and may not be possible.

**Comment by Cweiping** [comment]
@irvifa This problem has been fixed. Close the issue .
reference PR: https://github.com/kubernetes/website/pull/22357
/close
