### ISSUE TITLE
Document memory requirements for Minikube

### ISSUE THREAD

**Issue by sumangongali** [kubernetes/website#22065]
**This is a Bug Report**

**Problem:**
Minikube installation never tell us how much memory it requires, in any OS flavor

**Proposed Solution:**
Please provide the base memory limits to start a minikube 

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/kind feature

@sumangongali I'm going to update the issue title to match the request
/retitle Document memory requirements for Minikube
/language en
/priority awaiting-more-evidence

**Comment by RA489** [comment]
@sumangongali Minikube needs 

 

- 2 CPUs or more
- 2GB of free memory
- 20GB of free disk space
- Internet connection
- Container or virtual machine manager
