### ISSUE TITLE
Clean up case study images

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22086]
Umbrella issue: https://github.com/kubernetes/website/issues/22024

This is a **big** issue, but should be relatively easy to do using search-and-replace.

## Context

There are a number of images in the `/static/images/` directory that are used on case study pages. On the whole, these are prefixed with `CaseStudy_`, for example: `CaseStudy_adform_banner1.jpg`.

These images are then referenced in the individual case study pages. For example, `CaseStudy_adform_banner1.jpg` is referenced on `/content/en/adform/index.html`: 

```
<div class="banner1 desktop" style="background-image: url('/images/CaseStudy_adform_banner1.jpg')">
```

## What to do (for each image)

1. Move each set of case study images into their own directory under `/static/images/case-studies`. 
2. Change the referenced image URLs in the relevant case study pages to match the new locations.
3. Test test test!

For example: 

1. Move `/static/images/CaseStudy_adform_banner1.jpg` to `/static/images/case-studies/adforms/CaseStudy_adform_banner1.jpg`
2. Change the URL on `/content/en/adform/index.html`: 

```
<div class="banner1 desktop" style="background-image: url('`/static/images/case-studies/adforms/images/CaseStudy_adform_banner1.jpg')">
```

Note: there are case studies in the translation folders, but you should limit your changes to the `/en` translation. The TL teams will catch up soon enough, and it's best to let them manage those changes :)

**Comment by shuuji3** [comment]
/assign
@celestehorgan Hello, I'd like to take this issue.

One question: the name `/static/images/case-studies/adforms/CaseStudy_adform_banner1.jpg` seems a bit redundant to me. Can I rename it to `/static/images/case-studies/adforms/banner1.jpg`?

**Comment by shuuji3** [comment]
I just created a PR renaming to `/static/images/case-studies/adforms/banner1.jpg`. Feel free to tell me if the filename should remain the same.

**Comment by celestehorgan** [comment]
@shuuji3 That should be fine :)

**Comment by shuuji3** [comment]
Thanks :slightly_smiling_face:
