### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod-lifecycle/

### ISSUE THREAD

**Issue by Romanmc72** [kubernetes/website#22085]
**This is a Bug Report**

**Problem:**
This portion of the [documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime) states what eventually happens to pods that are `Succeeded` or `Failed`, but what happens to pods that are stuck in `Pending`? It says things need to be manually cleaned up or cleaned up by the controller, but what is the default behavior of a pod that is in a `Pending` state and shows no sign of coming out of that state? Will it be `Pending` until you kill it yourself? Does it eventually become `Failed` after some period of time? Can it be configured to fail after some time if it never reaches the `Running` state?

**Proposed Solution:**
Please add in a few sentences that describes what the pod lifecycle is for those types of pods who never actually end up running as well as what is required to fix the issue.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-lifetime

**Additional Information:**
I am using my cluster to accept incoming requests for very short lived pods/containers to run. Sometimes they don't end up running and that is okay for me. My question is, will they just live on as `Pending` in perpetuity or will they eventually fail? Do I need to intervene every so often and kill the ones that get stuck, or is there some recommended way to set the `Pending` pods to auto-fail after some time? This also applies to development and testing work wherein I may launch a pod that cannot get started for some reason or another. I would just like explicit instruction as to what the recommended way to fix this is if the container is certainly not going to run.

**Comment by tengqm** [comment]
/close
Feedback provided but no response for months. Assuming this is resolved.
Feel free to reopen.
