### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by tvkrishnaAWS** [kubernetes/website#22088]
**This is a Bug Report**

I was trying to install the minikube on Amzon Linuxv2 but it is not allowing me to install

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
@tvkrishnaAWS I'd like to learn more about the situation you've logged an issue about.
Have you spotted something that isn't right with the web page at https://k8s.io/docs/tasks/tools/install-minikube/ ?
