### ISSUE TITLE
Remove /static/images/community_logos

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22094]
Umbrella issue: #22024

Remove the `/static/images/community_logos` directory and files.

They aren't used anywhere, so this is a fairly easy change.

**Comment by Pihu1998** [comment]
Hi @celestehorgan . I would like to work on this issue.

**Comment by celestehorgan** [comment]
@Pihu1998 Great! 

/assign @Pihu1998

**Comment by celestehorgan** [comment]
@Pihu1998 are you still planning to work on this?

**Comment by morrme** [comment]
I am happy to submit this change today if the other person has abandoned it :)

**Comment by celestehorgan** [comment]
/unassign @Pihu1998 

/assign @morrme 

All yours, @morrme!
