### ISSUE TITLE
Investigate removing MaterialIcons

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22096]
Umbrella issue: https://github.com/kubernetes/website/issues/22024

Investigate removing variants of MaterialIcons in `/static/fonts`.

We don't appear to use or call these files anywhere but `static/css/style_user_journeys.css`. This stylesheet isn't used now either, so I'd suggest deleting it as well.

**Comment by ZhiFeng1993** [comment]
Code merged. We can close this issue.
