### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-kubernetes-objects/imperative-command/

### ISSUE THREAD

**Issue by aramarao27** [kubernetes/website#22098]
**This is a Bug Report**

**Problem:**
Following command does not create a service.
  >kubectl create service clusterip my-svc --clusterip="None" -o yaml --dry-run=client
When execute displays an error:
  Error: invalid argument "client" for "--dry-run" flag: strconv.ParseBool: parsing "client": invalid syntax
  See 'kubectl create service clusterip --help' for usage.

**Proposed Solution:**
kubectl create service clusterip my-svc --clusterip="None" -o yaml --dry-run=true

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/

1.18

Refer to section:
 "Using set commands to modify objects before creation"

**Comment by sftim** [comment]
Hi @aramarao27 

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#create documents a `--dry-run=client` option.

What version of kubectl are you seeing that with? Try `kubectl version --client` and paste in the output.
/triage needs-information

**Comment by aramarao27** [comment]
Hi sftim, 

Thank you for the link you have provided. I was able to find the root-cause. 

1) When tried to execute the below command in Katacoda, it was giving me an error.
 >kubectl create service clusterip my-svc --clusterip="None" -o yaml --dry-run=client
Checked for kubectl version on katacoda its "v1.17.3"

2) Again i tried on my local VM where Kubectl version=v1.18.4.
 >kubectl create service clusterip my-svc --clusterip="None" -o yaml --dry-run=client
Its working fine.

Apologies for raising this invalid issue. Please close this issue.

Regards,
RamaRao

**Comment by aramarao27** [comment]
Closing this issue as its invalid.
