### ISSUE TITLE
example-concept-template page in concepts section index

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#22110]
**This is a Bug Report**

The example-concept-template page is showing up in the `concepts` section index.

**Problem:**

https://kubernetes.io/docs/concepts/
https://kubernetes.io/docs/concepts/example-concept-template/

**Proposed Solution:**
Investigate whether this page should be removed or if there is way to prevent (change page metadata) the page
from publishing. Looks like this page has a parameter called `toc_hide`.

**Page to Update:**
https://kubernetes.io/docs/concepts/example-concept-template/

**Comment by kbhawkey** [comment]
Task template page too:
https://deploy-preview-22043--kubernetes-io-master-staging.netlify.app/docs/tasks/

**Comment by sftim** [comment]
/kind bug
Related to https://github.com/kubernetes/website/pull/20874

**Comment by sftim** [comment]
My gut feeling: replace these example pages with Hugo archetypes, and document using those.
