### ISSUE TITLE
Wrong link in Chinese page 

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#22133]
**This is a Bug Report**

Wrong link in Chinese page https://kubernetes.io/zh/docs/concepts/policy/resource-quotas/#viewing-and-setting-quotas for link "扩展资源". It directs to English version page but Chinese version page wanted

**Problem:**
Wrong link in Chinese page https://kubernetes.io/zh/docs/concepts/policy/resource-quotas/#viewing-and-setting-quotas

**Proposed Solution:**
Change to correct link

**Page to Update:**
https://kubernetes.io/zh/docs/concepts/policy/resource-quotas/#viewing-and-setting-quotas

**Comment by sftim** [comment]
/kind bug
/close

Fixed in #22154 (I think)
