### ISSUE TITLE
Promote guideline for blog related PRs 

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#22138]
While the guideline about blog related PRs is known to reviewers and approvers (https://kubernetes.io/docs/contribute/review/for-approvers/#blog-issues), we need to remind contributors that we don't accept fixes to blog entries more than 1 year old.

Proposed Fix:
- Add a few lines to https://kubernetes.io/docs/contribute/suggest-improvements/, saying that we don't treat issues in old blog entries as something to fix.
- Add some text to https://kubernetes.io/docs/contribute/new-content/new-content/, saying that PRs related to old blog entries will be closed.

**Comment by sftim** [comment]
That reminder could also be a job for automation, if anyone feels particularly inclined to implement it.
