### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by aaronaddleman** [kubernetes/website#22144]
**This is a Bug Report**

**Problem:**

Installation instructions for Ubuntu are for OpenSUSE

**Proposed Solution:**

Update the instructions for Ubuntu

**Page to Update:**

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#prerequisites

**Comment by sftim** [comment]
The issue is with https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o in the tab labelled “Ubuntu 18.04, 19.04 and 19.10”

/kind bug

As a related detail, it would be good to document setup for Ubuntu 20.04
