### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/disruptions/

### ISSUE THREAD

**Issue by saimakin** [kubernetes/website#22169]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @saimakin 

Can you explain more about what's not right on https://k8s.io/docs/concepts/workloads/pods/disruptions/ ?

/triage needs-information
