### ISSUE TITLE
Missing pages in the Spanish localised content

### ISSUE THREAD

**Issue by raelga** [kubernetes/website#22168]
**This is a Bug Report**

**Problem:**

Some Spanish pages are returning 404 but the pages are in the GitHub repo.

Example:
https://kubernetes.io/es/docs/concepts/workloads/controllers/replicaset/

![Screenshot 2020-06-29 at 16 33 40](https://user-images.githubusercontent.com/795289/86019007-5bce6d00-ba26-11ea-88a4-2ad2ab79f2cf.png)
![Screenshot 2020-06-29 at 16 31 59](https://user-images.githubusercontent.com/795289/86019025-5f61f400-ba26-11ea-8540-25c8601317be.png)

**Proposed Solution:**

Review the Spanish localised version and try to find what's causing the issue. 

**Page to Update:**

https://kubernetes.io/es/docs/concepts/workloads/controllers/

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/22175 will help fix this @raelga

**Comment by raelga** [comment]
Thanks @sftim, let's follow the conversation there then.

**Comment by raelga** [comment]
Solved by #22175
