### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/dns-custom-nameservers/

### ISSUE THREAD

**Issue by CvR42** [kubernetes/website#22173]
**This is a Bug Report**

**Problem:**

The link in: "What's next Read Debugging DNS Resolution" is broken.

**Proposed Solution:**

Fix the broken link.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

**Comment by sftim** [comment]
Backlog priority because the site search lets you work around this. It's not ideal obviously and a fix is welcome.

**Comment by CvR42** [comment]
https://kubernetes.io/docs/search/?q=debugging%20dns%20resolution results for me in a broken link as the first hit, and an outdated result as the second one. The third hit is https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/, which may be a quick fix, but I'm not enough of a K8s expert to judge that.

**Comment by Cweiping** [comment]
This link is back to work.

**Comment by Cweiping** [comment]
If there is no update recommended close, I test and find it works.
@sftim @CvR42 
/Close
