### ISSUE TITLE
update README with docsy submodule update md

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#22224]
**This is a Feature Request**
The docsy theme needs to be added to an existing website repository.
Authors are not aware of the command to update the theme.

**What would you like to be added**
Update the README.md to include the `git submodule update` command 

**Why is this needed**
Authors cannot find the command to update/install the docsy theme. When the
theme is not installed, the generated build errors are not intuitive.

**Comments**
website/README.md
`git submodule update --init --recursive --depth 1`

**Comment by sftim** [comment]
I also recommend updating https://kubernetes.io/docs/contribute/new-content/new-content/#preview-locally

**Comment by kbhawkey** [comment]
Sure, I will update.
