### ISSUE TITLE
Event list missing from community page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22227]
**This is a Bug Report**

**Problem:**
To work around https://github.com/kubernetes/website/issues/22222 we removed the event list from [_Community_](https://kubernetes.io/community/) in PR #22223 

**Proposed Solution:**
- find a way to reinstate the community page events list

**Page to Update:**
https://kubernetes.io/community/

**Additional Information:**
/kind bug
/priority important-longterm

**Comment by irvifa** [comment]
Another good idea is started using [environment variable](https://docs.netlify.com/configure-builds/environment-variables/#sensitive-variable-policy) for sensitive information. We can use it once we got the reason on why the access is suddenly revoked.

**Comment by mrbobbytables** [comment]
> I think we also can start using environment variable for sensitive information. We can use it once we got the reason on why the access is suddenly revoked.

Mostly as a general FYI, but the calendar API keys are often public but restricted to what domains they work from. It's not necessarily ideal, but javascript calendars for static sites have to use them this way and they're often embedded in the code itself.
ref: https://fullcalendar.io/docs/google-calendar

**Comment by irvifa** [comment]
I see, thanks for your explanation @bobbytables 🙂

**Comment by sftim** [comment]
Some background in issue #6724

**Comment by sftim** [comment]
I'm guessing we should make the API key be owned by WG Infra and not by a specific contributor / CNCF member organization. That's what I'd be working towards.

**Comment by sftim** [comment]
Also
/language en
