### ISSUE TITLE
Version, Language drop-downs non-functional on Case Study pages

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22221]
Expected behavior: https://v1-18.docs.kubernetes.io/case-studies/spotify/ (drop-downs work)
Actual behavior: https://kubernetes.io/case-studies/spotify/ (drop-downs do not work)

This may be a `z-index` issue or a result of non-translated pages not showing up in autogenerated navs. I'm unsure.

**Comment by shuuji3** [comment]
Hello, calestehorgan

I investigated this problem quickly and found that `div.dropdown` (this is and language box) seemed to remain `display: none` when the mouse cursor has hovered.

![add-display-block-into-style](https://user-images.githubusercontent.com/1425259/86159932-05f0e680-bb46-11ea-814b-c87495ac4eb5.png)

Adding the following style makes the problem disappeared:
```css
.dropdown:hover .dropdown-menu {
    display: block;
}
```

![show-dropdown](https://user-images.githubusercontent.com/1425259/86159933-06897d00-bb46-11ea-871a-da4bae7e7971.png)

Maybe some style is missing or something blocks a style applied.

**Comment by celestehorgan** [comment]
@shuuji3 Thank you for the help!! I'll try it out.

**Comment by shuuji3** [comment]
@celestehorgan I'm glad to help! 😊
