### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by racheruk** [kubernetes/website#22233]
The install doc prescribe to use "sudo install minikube /usr/local/bin/" but it is not appropriate.

The commands are very prescriptive in the sense that i.e.

1. download the binary
2. make it executable using chmod
3. create directory /usr/local/bin/
4. use install command to "copy" the binary to /usr/local/bin/

Step 2 is not necessary

**Proposed Solution:**
Couple of options that are sensible

Option 1 : 
  Remove Step 2
  Add Step 5 to delete downloaded file

Option 2 : 
  Step 4 : Please change "sudo install minikube /usr/local/bin/" to "sudo mv minikube /usr/local/bin/"

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by prasadkatti** [comment]
I think the command is valid. There is an `install` command that your machine may not have - https://linux.die.net/man/1/install

**Comment by racheruk** [comment]
@prasadkatti Apologies for having very short description of the issue. Updated it to include more context.
