### ISSUE TITLE
This link is broken. The src or href is an empty string.  

### ISSUE THREAD

**Issue by SDR0512** [kubernetes/website#22269]
href='' or src='' can cause unexpected effects such as traffic spikes or cookie corruption, and causes JavaScript error events to fire on Firefox.	
	
Link: Show More Posts... URL is empty.
         https://kubernetes.io/blog/

Line: 231, 367, 587, 879, 1103

**Comment by tengqm** [comment]
"Show More Posts..." link? There is no such link on the page you mentioned. 
/triage needs-information

**Comment by shuuji3** [comment]
By clicking a year link (for example "2020") on the left sidebar,  "Show More Posts..." link is shown on the bottom of the list of articles. Maybe this is the link.
