### ISSUE TITLE
Issue with k8s.io/zh/docs/concepts/cluster-administration/cluster-administration-overview/

### ISSUE THREAD

**Issue by Smlight** [kubernetes/website#22264]
**This is a Bug Report**

**Problem:**
**Borken link** in `如果你正在设计一个高可用集群，请了解在多个 zones 中配置集群。`
It just lead me to a 404 page.
**Proposed Solution:**
Update the link.
**Page to Update:**
As shown in the title,
https://k8s.io/zh/docs/concepts/cluster-administration/cluster-administration-overview/

**Comment by prasadkatti** [comment]
\language zh

**Comment by ydcool** [comment]
This page is out of date, let me update it.
/assign

**Comment by ydcool** [comment]
/meow

is ci robot still work?
