### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/control-plane-node-communication/

### ISSUE THREAD

**Issue by hieuteve** [kubernetes/website#22272]
**This is a Bug Report**

**Problem:**
Konnectivity or Connectivity?

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
Konnectivity is it. See

- https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/
- https://github.com/kubernetes-sigs/apiserver-network-proxy
