### ISSUE TITLE
PVC resource requirements hard to find

### ISSUE THREAD

**Issue by kreempuff** [kubernetes/website#22298]
**This is a Bug Report**

**Problem:**
I was looking for the keys to specify for the resource requirements in a PersistentVolumeClaim via the [API reference][api-ref-pvc]. After following the link to the [ResourceRequirements][resource-requirements] docs, the `.requests` key points to the [concepts][concepts] page for managing container resources. It makes no mention of Persistent Volume Claims or the fact that they take the key `.storage` key in their `.requests` field.

The way to find out the key is going to the [PersistentVolumeClaim][pvc-concepts] page and looking at one of the examples 
**Proposed Solution:**
Ideally, the reference page for [ResourceRequirements][resource-requirements] reference page includes all the keys that would satisfy a resource requirement 

e.g. from the concepts page:  
-   `.requests.cpu` (PodSpec)
-   `.requests.memory` (PodSpec)
-   `.requests.hugepages-<size>` (PodSpec)
with new PVC info
- `.requests.storage` (PersistentVolumeClaimSpec)

If this is not desired, updating the PVC concepts page to include a section on persistent volume claim resource requirements and updating the API reference page to link to the PVC page as well 
**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#resourcerequirements-v1-core

https://kubernetes.io/docs/concepts/storage/persistent-volumes/

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-types

`v1.18`

[api-ref-pvc]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#persistentvolumeclaimspec-v1-core
[resource-requirements]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#resourcerequirements-v1-core
[concepts]: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
[pvc-concepts]: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volume-claim-requesting-a-raw-block-volume

**Comment by sftim** [comment]
The API reference doesn't have awareness of all the kinds of resources that you can request (or set a limit for).

How about adding a new page https://kubernetes.io/docs/reference/resources/some-title/ that lists the kind of resources that are built in to Kubernetes? Then other pages can link there; for example, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-types

How does that sound?

**Comment by kreempuff** [comment]
Hmm, I like that idea. Is there a place where built-in resource types are defined that I can reference for the new page?

**Comment by sftim** [comment]
@kreempuff not yet! I think https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-types is the closest existing page. Beyond that there is https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-types and the Kubernetes source code.

/sig scheduling

**Comment by kreempuff** [comment]
Alright! I'll take this on

**Comment by sftim** [comment]
/sig storage
too
