### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SDR0512** [kubernetes/website#22297]
There is empty url in kubernetes site code
line: 2299

**Comment by tengqm** [comment]
file name?

**Comment by SDR0512** [comment]
In the CODE
Code line is 2299

**Comment by tengqm** [comment]
which code?

**Comment by SDR0512** [comment]
In the HTML code

**Comment by tengqm** [comment]
can you share the URL, the source file?
what do you mean by "kubernetes site"?
