### ISSUE TITLE
Activate CDN

### ISSUE THREAD

**Issue by SDR0512** [kubernetes/website#22299]
A Content Delivery Network (CDN) optimizes the delivery of the content of your website to your visitors. It is especially useful if you have visitors that view your website from a variety of geographic regions.

**Comment by sftim** [comment]
@SDR0512 I'm a technical lead for SIG Docs and I'm happy with the existing CDN.

Are you finding that https://kubernetes.io/ is slow or difficult to access?

/triage needs-information

**Comment by SDR0512** [comment]
Not only ensure a faster experience to https://kubernetes.io/, they also help to prevent site crashes in the event of traffic surges

**Comment by SDR0512** [comment]
> @SDR0512 I'm a technical lead for SIG Docs and I'm happy with the existing CDN.
> 
> Are you finding that https://kubernetes.io/ is slow or difficult to access?
> 
> /triage needs-information
Not only ensure a faster experience to your users, they also help to prevent site crashes in the event of traffic surges

**Comment by SDR0512** [comment]
> @SDR0512 I'm a technical lead for SIG Docs and I'm happy with the existing CDN.
> 
> Are you finding that https://kubernetes.io/ is slow or difficult to access?
> 
> /triage needs-information

not only ensure a faster experience to your users, but they also help to prevent site crashes in the event of traffic surges

**Comment by sftim** [comment]
The existing CDN does seem fine.

/priority awaiting-more-evidence
