### ISSUE TITLE
error message when creating a project on openshift via the CLI 

### ISSUE THREAD

**Issue by danoso10** [kubernetes/website#22302]
**Running the following command to create a project after logging into my cluster:**

$ oc new-project c0ab-openshift-tools --display-name="OpenShift Tools"

**and encountering the following error message:** 

error: Missing or incomplete configuration info.  Please login or point to an existing, complete config file:

  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.

**Anyone know why?**

**Comment by danoso10** [comment]
I even get this error message when simply running "oc get projects"

**Comment by tengqm** [comment]
pls raise the issue at https://github.com/openshift/oc/issues
This is not a k8s docs issue.
/close
