### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by michael1589** [kubernetes/website#22347]
**This is a Bug Report**

create mysql-deployment.yaml and wordpress-deployment.yaml fail, because pvc is in pending.
root@centos7-2 mysql-wordpress-pd]# kubectl apply -k ./
service/wordpress-mysql created
service/wordpress created
deployment.apps/wordpress-mysql created
deployment.apps/wordpress created
persistentvolumeclaim/mysql-pv-claim created
persistentvolumeclaim/wp-pv-claim created
[root@centos7-2 mysql-wordpress-pd]# kubectl get pvc
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mysql-pv-claim   Pending                                                     22s
wp-pv-claim      Pending                                                     22s
[root@centos7-2 mysql-wordpress-pd]# kubectl get pods
NAME                               READY   STATUS    RESTARTS   AGE
wordpress-6857459697-4fkwx         0/1     Pending   0          26s
wordpress-mysql-5f4b68ff8f-tqndw   0/1     Pending   0          26s
[root@centos7-2 mysql-wordpress-pd]# kubectl describe pgc mysql-pv-claim
error: the server doesn't have a resource type "pgc"
[root@centos7-2 mysql-wordpress-pd]# kubectl describe pvc mysql-pv-claim
Name:          mysql-pv-claim
Namespace:     default
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=wordpress
Annotations:   Finalizers:  [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    wordpress-mysql-5f4b68ff8f-tqndw
Events:
  Type    Reason         Age               From                         Message
  ----    ------         ----              ----                         -------
  Normal  FailedBinding  4s (x5 over 60s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

Kubernetes version is v1.18.4
The k8s cluster is in a windows Server 2012R2 Host, where I created 4 centos7 virtual guests through hyper-v.
Why PVC always fail?

**Comment by tengqm** [comment]
You will need to provision the PV volumes manually before running this example. The message is pretty clear on that: "no persistent volumes available for this claim and no storage class is set".
