### ISSUE TITLE
ja: Make docs/setup/production-environment/tools/kops.md follow v1.17 of the original text

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#22341]
**This is a Feature Request**

**What would you like to be added**
Update docs/setup/production-environment/tools/kops.md to follow v1.17 of the original (English) text.

英文のまま更新するだけで十分です。
翻訳は必須ではありませんが、歓迎します。翻訳用にIssueを作成する必要はありません。

**Why is this needed**
content/ja/docs/setup/production-environment/tools/kops.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.17-ja.3/content/ja/docs/setup/production-environment/tools/kops.md

Original
https://github.com/kubernetes/website/blob/release-1.17/content/en/docs/setup/production-environment/tools/kops.md

diff between translated and v1.17
https://gist.github.com/e3c43a857fd7eb7d70588552ba5ecdce

**Note**
Currently, we use **dev-1.17-ja.3** branch. Please open a PR targeting the branch.

ref
[How To Contribute](https://kubernetes-docs-ja.kibe.la/shared/entries/c5878aa5-ad1f-4f29-a5bb-25853cbc14ec)
[翻訳スタイルガイド](https://kubernetes-docs-ja.kibe.la/shared/entries/5efe4fa7-d2a1-4a1d-8bc3-ce7ccdc064a6)

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
@shuuji3 進捗どんなかんじですか～！

**Comment by shuuji3** [comment]
まだ手を付けていない状態です。ついでに翻訳しようと考えていましたが、先に英語のまま更新するPRだけ出そうと思います。

**Comment by shuuji3** [comment]
@inductor まだ手を付けていない状態です。ついでに翻訳しようと考えていましたが、先に英語のまま更新するPRだけ出そうと思います！

**Comment by inductor** [comment]
@shuuji3 了解です！
