### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-application-introspection/

### ISSUE THREAD

**Issue by riyafa** [kubernetes/website#22356]
**This is a Bug Report**

**Problem:**
The page is not updated for version 1.18
**Proposed Solution:**
Update the results of `kubectl describe` commands and `kubectl -o yaml` commands to reflect the latest version and the following discussions on them also to use content from latest version.
**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application-introspection/

1.18

**Comment by Kartik494** [comment]
Hi @riyafa could you let me know how these commands is not reflecting the expected behaviour against latest version

**Comment by riyafa** [comment]
In the section under events for the result of `kubectl describe pod nginx-deployment-1006230814-6winp` command does not have a section called `SubobjectPath`. It has the sections `Type`, `Reason`, `Age`, `From` and `Message` respectively in order

**Comment by Kartik494** [comment]
Hi @riyafa i am not sure on section "SubobjectPath" does this introduce in version 1.18?
