### ISSUE TITLE
Issue with 'Linux' and 'Windows' notation in Korean docs

### ISSUE THREAD

**Issue by pjhwa** [kubernetes/website#22360]
**This is a Bug Report**

**Problem:**
In some translated docs into Korean, 'Linux' and 'Windows' were not translated.

**Proposed Solution:**
Replace 'Linux' and 'Windows' with '리눅스' and '윈도우' in the following pages:
1. 'Linux':
- concepts/configuration/organize-cluster-access-kubeconfig.md
- concepts/services-networking/service.md
- concepts/workloads/pods/pod.md
- concepts/workloads/pods/init-containers.md
- concepts/policy/pod-security-policy.md
- concepts/cluster-administration/networking.md
- reference/glossary/docker.md
- setup/production-environment/tools/kops.md
- setup/production-environment/container-runtimes.md
- setup/learning-environment/minikube.md
- tasks/tools/install-minikube.md
- tasks/tools/install-kubectl.md
- tasks/access-application-cluster/configure-access-multiple-clusters.md

2. 'Windows':
- concepts/configuration/organize-cluster-access-kubeconfig.md
- concepts/services-networking/service.md
- setup/production-environment/windows/user-guide-windows-containers.md
- setup/learning-environment/minikube.md
- tasks/tools/install-minikube.md
- tasks/tools/install-kubectl.md
- tasks/administer-cluster/kubeadm/adding-windows-nodes.md
- tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- tasks/access-application-cluster/configure-access-multiple-clusters.md

**Page to Update:**
https://kubernetes.io/...

/language ko

**Comment by sftim** [comment]
Fixed in PR #22362

**Comment by pjhwa** [comment]
@sftim By any chances, do you know why this issue didn't close even though I added "Closes #22360" in the description of the PR?

https://kubernetes.io/docs/contribute/new-content/new-content/#open-a-pr
> If there is a related GitHub issue, include Fixes #12345 or Closes #12345 in the description. GitHub's automation closes the mentioned issue after merging the PR if used. If there are other related PRs, link those as well.

**Comment by sftim** [comment]
/shrug

The ways of GitHub are sometimes mysterious
