### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by memark** [kubernetes/website#22363]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic

This paragraph is a bit backwards. It would be more intuitive to start with the "Make sure that the br_netfilter module is loaded before this step..." phrases.

**Comment by sftim** [comment]
/language en
/kind cleanup
/priority backlog
/good-first-issue

Thanks @memark
