### ISSUE TITLE
Tidy reference section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22385]
**This is a clean-up request**

**Problem:**
The [reference pages](https://k8s.io/docs/reference/) already have a good overview, so the autogenerated list of pages that's at the foot of that overview is not really needed.

However, there are a few extra pages in the section that aren't listed in the overview.

**Proposed Solution:**
- make sure that every item in the left-hand navigation is referenced in the main text of the reference section (not counting the autogenerated list)
- set `no_list: true` in the front matter of [`content/en/docs/reference/_index.md`](https://github.com/kubernetes/website/blob/master/content/en/docs/reference/_index.md)

**Page to Update:**
https://kubernetes.io/docs/reference/

**Additional Information:**
/kind cleanup
/language en
/help
/priority backlog

**Comment by raghvenders** [comment]
@sftim  - I was able to make change in  - content/en/docs/reference/_index.md and auto-generated list is no more.

"make sure that every item in the left-hand navigation is referenced in the main text of the reference section (not counting the autogenerated list)"

For example  - kubeadm & kubectl are being referenced in main text but under different section(for its own reason) , rather minikube , dashboard and helm are not available in the main section but can be found under **Reference->Tools**.

Are you specific about such or kindly show an example.
