### ISSUE TITLE
/images/copycode.svg is a white outline and thus invisible

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22393]
`/static/images/copycode.svg` has a white fill-color which renders it non-visible in most cases. For example, see [this code block](https://kubernetes.io/docs/concepts/cluster-administration/logging/#basic-logging-in-kubernetes), and hover just to the right of the file name.

Change the `fill` color on this SVG to a more visible color, for example `#3371e3`. This should be as simple as changing the `fill` property on line 1 of the SVG file:

```
<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" viewBox="0 0 24 24" fill="#FFFFFF"> 
```

To do this, open the SVG file in a text/code editor rather than an image program.

**Comment by sftim** [comment]
This is a bug, I think.

/remove-kind cleanup
/kind bug
/priority backlog

**Comment by sftim** [comment]
(“backlog” doesn't mean “won't get done”; it's the right priority for most issues that we triage, and a lot of those get done)

**Comment by luckyvs1** [comment]
Can this issue be closed? It was fixed by [PR](https://github.com/kubernetes/website/pull/22396) the PR had it as `issue` and not a [valid keyword](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) to close out the issue.
