### ISSUE TITLE
Issue with k8s.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by pparihar** [kubernetes/website#22394]
Thanks for the explanation but commands and YAML files are deemed to lot of errors and hence understanding of multi-schedulers is not clear.
Appreciate if you validate the entire process and update documents so that millions of people refer and understand from official git repo and kubernetes.io portal and thanks.

**Comment by sftim** [comment]
@pparihar I'd like to understand what steps someone should take to resolve this issue

If you're willing to explain further you could use the text of (eg) issue 4491 as a guide, and revise the initial description of _this_ issue to explain the kind of work you had in mind.

/triage needs-information
/language en

**Comment by sftim** [comment]
Because it's not clear what is not right about that page, I propose closing this issue.

I recognize that https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/ does need a review and that issues including #22802 are tracking defects there.
