### ISSUE TITLE
Issue with /docs/getting-started-guides/dcos/

### ISSUE THREAD

**Issue by fpapleux** [kubernetes/website#2241]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
This page is significantly out of date. The very first dcos command is deprecated and has apparently no replacement.

**Proposed Solution:**
Updating the page? :)

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
Page to update: http://kubernetes.io/docs/getting-started-guides/dcos/
