### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by acscott** [kubernetes/website#22414]
Maybe mention that deployments require changing the api attribute when going from major version to major version.

**Comment by neolit123** [comment]
hello,

- do you mean "minor version" instead of "major version"?
- also what is an "api attribute"?

/priority awaiting-more-evidence
/sig cluster-lifecycle

**Comment by neolit123** [comment]
closing due to no reply, reopen if needed.
/close
