### ISSUE TITLE
Improvement for k8s.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by v4mpir0ck** [kubernetes/website#22413]
Hi,
in the part of enabling[ leader election](https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#enable-leader-election) , it would be helpfull to show what file and where it is.

¿ /etc/kubernetes/config/kube-scheduler.yaml ?

thank you

**Comment by sftim** [comment]
This seems valid
/language en
/priority backlog
/sig scheduling

**Comment by Cweiping** [comment]
Fixed: #22642
/close
