### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/names/

### ISSUE THREAD

**Issue by rrajaram** [kubernetes/website#22416]
**This is a Bug Report**

**Problem:**
DNS Subdomain Names is mentioned as name cannot be more than 253 characters.

**Proposed Solution:**
As per RFC 1123 mentioned in the same page, section 2.1 host names and numbers it mentions ' Host software MUST handle host names of up to 63 characters and SHOULD handle host names of up to 255 characters". So doesn't it mean we can have upto 255 characters instead of 253. 

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by sumodirjo** [comment]
I found the following code comment:

> // The max length of a resource name is 253 characters (DNS1123Subdomain max length)
>// We then add an additional 2 characters to account for the one '.' and one '/'.

https://github.com/kubernetes/kubernetes/blob/dbfc3aa877b5beda2ecdfb38911c311b250a4973/pkg/apis/certificates/validation/validation.go#L276

My understanding the actual limit is still 255. I'm not sure which or where is the one '.' and one '/' referred on the comment.

**Comment by sftim** [comment]
It sounds like the documentation is accurate about what Kubernetes requires, but not explicit that this is different from the DNS standard. Does that sound right?

/sig api-machinery

**Comment by rrajaram** [comment]
Understood Tim & Muhammad, since it referred the RFC I was confused as a newbie if the k8s documentation is accurate or not. I wish it was more explicit.
