### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/ tooltips

### ISSUE THREAD

**Issue by knappe** [kubernetes/website#22448]
**This is a Bug Report**

**Problem:** 
The z-index on the `tooltip-text` class is too small and doesn't not overlay things like the left navigation bar (screenshot attached)
![Annotation 2020-07-09 215017](https://user-images.githubusercontent.com/138048/87114599-3c0d2500-c22e-11ea-99e2-c41502b61c3f.png)

**Proposed Solution:**
The z-index on the `tooltip-text` class needs to be bumped to 10.
![z-index-10](https://user-images.githubusercontent.com/138048/87114812-c5245c00-c22e-11ea-91c4-42f0682bd308.png)

**Page to Update:**
All of them.

**Comment by Arhell** [comment]
duplicate #22398

**Comment by sftim** [comment]
@knappe as this is a duplicate report, are you willing to close it and track the defect in #22398?

**Comment by knappe** [comment]
@sftim Yeah, not a problem!  I'll go ahead and close this.
