### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/guestbook/

### ISSUE THREAD

**Issue by liushenf** [kubernetes/website#22451]
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#creating-the-redis-slave-deployment , the image gcr.io/google_samples/gb-redisslave no longer exist. Applying redis-slave-deployment.yaml will get ErrImagePull.

**Proposed Solution:**
Please update with new redis-slave image location, or a new sample.
Thanks!

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#creating-the-redis-slave-deployment

**Comment by tengqm** [comment]
It is still there ...  https://console.cloud.google.com/gcr/images/google-samples/GLOBAL/gb-redisslave?gcrImageListsize=30
If you cannot access it, it may mean you have some networking issues connecting to gcr.io.
Please feel free to reopen if it is still problem.
/close
