### ISSUE TITLE
Contradicting kubectl apply documentation

### ISSUE THREAD

**Issue by SebStrug** [kubernetes/website#22465]
**Contradicting kubectl apply documentation**

**Problem:**
The kubectl `apply` documentation here:
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply

Says that the `-k` flag should be used for a directory.

However the documentation here for the kubectl overview:
https://kubernetes.io/docs/concepts/configuration/overview/#using-kubectl

Suggests using the `-f` flag for a directory. Why is there a discrepancy?

**Proposed Solution:**
If `-f` is best practice for a limited use case this should be made clear in the documentation. Separately it should be clear that `-f` can be used for a directory, not just for a file.

**Pages to Update:**
One of the following pages should be updated or clarified:
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply
or
https://kubernetes.io/docs/concepts/configuration/overview/#using-kubectl

**Comment by sftim** [comment]
@SebStrug I recommend filing this issue against `kubectl` to clarify that `-f` can take a file, a manifest URL, or a local directory containing manifests. That change will cascade into the page at https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply

You can file that report using https://github.com/kubernetes/kubectl/issues/new?labels=kind%2Fbug&template=bug-report.md and then close this issue, referencing the URL of the replacement issue you logged.

**Comment by SebStrug** [comment]
Thank you @sftim 
I have filed the issue here: https://github.com/kubernetes/kubectl/issues/896 , and will close issue.
