### ISSUE TITLE
Issue with k8s.io/docs/home/.    cannont search

### ISSUE THREAD

**Issue by zhumo27** [kubernetes/website#22471]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Hi @zhumo27 

When you try to search, what happens? Can you describe what you searched for, what you expected to see, and the actual outcome? Please consider including a screen grab.

/triage needs-information

**Comment by zhumo27** [comment]
when I search in kubernetes.io/doc,the page show nothing,can you help me?

Best Regards！

在 2020年7月12日，01:14，Tim Bannister <notifications@github.com> 写道：

﻿

Hi @zhumo27<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fzhumo27&data=02%7C01%7Cmoz%40vmware.com%7C39ebbddf43824a87ca8208d825bde038%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C637300844733769188&sdata=9kNPLsJ8S%2FThWhKoIfsP%2FH8267wTiWqr3RFXMDve6Cc%3D&reserved=0>

When you try to search, what happens? Can you describe what you searched for, what you expected to see, and the actual outcome? Please consider including a screen grab.

/triage needs-information
