### ISSUE TITLE
Incorrectly formatted note in “Installing Kubernetes with Minikube”

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#22487]
**This is a Bug Report**

**Problem:**

Code blocks in notes cannot be rendered correctly with Docsy template.

v1.17 (an old template) works fine.
https://v1-17.docs.kubernetes.io/docs/setup/learning-environment/minikube/#starting-a-cluster
![v1 17](https://user-images.githubusercontent.com/4710215/87306517-16945a00-c553-11ea-9544-bf8fa939e077.png)

v1.18 (a new template) doesn't work fine.
![v1 18](https://user-images.githubusercontent.com/4710215/87306526-1a27e100-c553-11ea-92e6-d3455b1f2264.png)

**Proposed Solution:**

I don't know how to resolve this issue.

**Page to Update:**
https://kubernetes.io/docs/setup/learning-environment/minikube/

**Comment by sftim** [comment]
/kind bug

/retitle Incorrectly formatted note in “Installing Kubernetes with Minikube”
(hope that's OK)

**Comment by sftim** [comment]
Fixed in #22495 
/close
