### ISSUE TITLE
Current page is lost when switching between documentation versions

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/website#22497]
**This is a Bug Report**

**Problem:**
Current page is lost when switching between documentation versions. 

Steps to reproduce
1. Go to some page in the docs, for example [Install Kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)
2. Use the version selector at the top of the page to change to 1.17.
3. Notice that it it sends me to the [docs home](https://v1-17.docs.kubernetes.io/) instead of showing me the [1.17 version of the install-kubectl page](https://v1-17.docs.kubernetes.io/docs/tasks/tools/install-kubectl/).

**Proposed Solution:**
Keep the relative path when switching versions

**Page to Update:**
All

**Additional Information:**
Am I wrong that it used to preserve the page you are on when switching versions? I feel like it used to do that, but I'm not 100% sure.

**Comment by kbhawkey** [comment]
Yes, at some point the site kept the same page when switching between versions.

**Comment by sftim** [comment]
/kind bug
/priority backlog

(I think this is a low-priority-backlog sort of issue; it's a frustration, but we have other places where it makes sense to focus effort first).
