### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by sjmudd** [kubernetes/website#22519]
**This is a Bug Report**

Please upgrade MySQL images to 8.0 from 5.6.

**Problem:**

MySQL image provided is VERY old, suggesting using MySQL 5.6.

**Proposed Solution:**

Please consider upgrading to use the 8.0 images provided by Oracle/MySQL.

**Page to Update:**

https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

The MySQL recipe is likely to work with 8.0 unaltered or at least I would think so. If not adjust as necessary.

**Comment by sjmudd** [comment]
- MySQL 5.6 was announced GA (production ready) in 2013.
- MySQL 5.7 was announced GA in 2015.
- MySQL 8.0 (latest production release) was announced GA in 2018.

**Comment by sjmudd** [comment]
See: https://hub.docker.com/_/mysql for current / latest MySQL images for 5.6 / 5.7 / 8.0.

**Comment by sjmudd** [comment]
- I tested swapping 5.6 for 5.7 and that seemed to work fine.
- Testing swapping 5.6 to 8.0 did not. I haven't had a chance to see why or what might need fixing as not familiar with the kubernetes environment to debug this properly.

I was hoping someone would look at this and provide a fix. Perhaps that's not realistic.  Right now I'm not in a situation to be able to provide a PR to resolve my suggestion. Maybe someone else is able to help.

**Comment by madalinignisca** [comment]
I have another issue for same example:

If I have a fresh cluster, as the container images are not yet available, it will first download them. As mysql/mariadb container images are larger than wordpress, the mysql pod will be ready much later.

The result is, when creating everything for the first time, wordpress will respond with `Error establishing a database connection`, but if I exec in it, I can communicate with the database. Seems like the Apache process that uses php as a module (mod_php), will not be able to discover the mysql service ip as it started before it.

My wonder, is there any option to set to the wordpress pod or service, to wait for the mysql pod/service to be fully ready?

If I delete the resources and apply again to recreate, everytime wordpress will work as expected and be able to communicate with the database. But what should I expect when I am upgrading the database?

**Comment by madalinignisca** [comment]
I managed to overcome my above issue by using init container on the wordpress deployment to delay it until mysql service was available. this sorted the lookup for wordpress-mysql hostname for php.
