### ISSUE TITLE
Container image is missing requirements for docsy

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/website#22537]
**This is a Bug Report**

**Problem:**

To build docsy w/ hugo you need npm, postcss and autoprefixer, but the Dockerfile in this repo lacks them.

**Proposed Solution:**

Install these in the dockerfile so building the website in a container works.

**Page to Update:**
None

/assign

**Comment by BenTheElder** [comment]
fix: https://github.com/kubernetes/website/pull/22258
see also: https://github.com/kubernetes/website/issues/22515 https://github.com/kubernetes/website/pull/22518

**Comment by BenTheElder** [comment]
https://github.com/google/docsy#prerequisites

**Comment by kbhawkey** [comment]
Thanks @BenTheElder

**Comment by BenTheElder** [comment]
fixed in https://github.com/kubernetes/website/pull/22258
