### ISSUE TITLE
Update Resource Bin Packing docs to use Scheduling Profiles

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#22530]
**This is a Feature Request**

https://kubernetes.io/docs/concepts/configuration/resource-bin-packing/ should be migrated to use Scheduling Profiles https://kubernetes.io/docs/reference/scheduling/config/#profiles

**Why is this needed**

With Profiles graduating to beta in 1.19, there is no motivation to continue to promote the usage of Policies.

/sig scheduling
/help

**Comment by alculquicondor** [comment]
Docs freeze is Thursday July 16th

**Comment by sftim** [comment]
(It's also OK to submit a PR that merges into _master_ after the official v1.19 release - [k/website](https://github.com/kubernetes/website) uses a continuous deployment pipeline)
