### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by VGerris** [kubernetes/website#22542]
**This is a Bug Report**

**Problem:**
There is no information explaining where port 8080 comes from 

**Proposed Solution:**

Explain where port 8080 comes from in the configuration

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by VGerris** [comment]
page to update:
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by Kartik494** [comment]
@VGerris As far as i know 8080 , is the localhost port and it is by default there.you can find related information [here](https://kubernetes.io/docs/reference/access-authn-authz/controlling-access/#api-server-ports-and-ips)

**Comment by sftim** [comment]
I agree, it's not clear.
/sig network
/language en
/kind cleanup
/priority backlog
