### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-application/

### ISSUE THREAD

**Issue by mquisto8** [kubernetes/website#22566]
**This is a Bug Report**

**Problem:**
"Make sure that the endpoints match up with the **number of containers** that you expect to be a member of your service. "

A pod can have multiple containers; don't the service's endpoints correspond to pod IP's?

**Proposed Solution:**
change "containers" to "pods"

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Good spot
/kind cleanup
/priority backlog
/language en
/good-first-issue

**Comment by sftim** [comment]
The page to revise is https://k8s.io/docs/tasks/debug-application-cluster/debug-application/

**Comment by lparis** [comment]
Was going to do this but it appears to be fixed. https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application/

**Comment by sftim** [comment]
Fixed in #22653
/close
