### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by skchinna7** [kubernetes/website#22575]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

 I don't understand after reading the documentation please make something easy and understandable

**Comment by sftim** [comment]
/triage needs-information
/language en

@skchinna7, what question did you have? If you explain that, we can investigate improvements so that [Install and Set Up kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/) does answer it.
