### ISSUE TITLE
Japanese docs still use "master"

### ISSUE THREAD

**Issue by nownabe** [kubernetes/website#22580]
**This is a Feature Request**

**What would you like to be added**

Japanese docs should use "control plane" instead of "master" like English docs.

**Why is this needed**

Because using different words between English and Japanese makes confusion.

**Comments**

**Comment by inductor** [comment]
@nownabe We are updating our pages based a few minor version behind compared to the upstream. Please wait for a moment to evaluate the difference.

**Comment by celestehorgan** [comment]
Note: the german translation still uses master too, if I recall correctly.

**Comment by justaugustus** [comment]
> Note: the german translation still uses master too, if I recall correctly.

Yep! xref: https://github.com/kubernetes/community/issues/5043

**Comment by celestehorgan** [comment]
Hi All,

per [the recommendation](https://github.com/kubernetes/community/blob/master/wg-naming/recommendations/master-control-plane.md), please rename "master" to "control plane" when you are ready :)

**Comment by shuuji3** [comment]
It seems that the file was renamed: `master-control-plane.md` → `001-master-control-plane.md`

Current location: https://github.com/kubernetes/community/blob/master/wg-naming/recommendations/001-master-control-plane.md
