### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/jsonpath/

### ISSUE THREAD

**Issue by mick62** [kubernetes/website#22582]
**This is a Bug Report**

**Problem:**
There is no information about whether it is possible to use the value of a sub query in a filter.
Example: 
The output of command "kubectl config view" (my alias "kcv") has a top level property "current-context".

How/is it possible to use the value of property "current-context" in a filter like:
kcv -o=jsonpath="{.contexts[?(@.name==.current-context)].context.namespace}"

**Proposed Solution:**

The work-around seems to be:
CONTEXT=\\'$(kcv -o=jsonpath="{.current-context}")\\'
kcv -o=jsonpath="{.contexts[?(@.name==$CONTEXT)].context.namespace}"

Please clarify whether there is a way to use a sub query or whether the work-around is currently the only solution.

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by sftim** [comment]
:thought_balloon: If there is a website that documents JSONpath, https://kubernetes.io/docs/reference/kubectl/jsonpath/ can link there and then people who want to learn about JSONpath can follow the link.

That feels like a better approach. However, I'm not sure that there _is_ a JSONpath website.

**Comment by Cweiping** [comment]
According to the module author's documentation, [the site](http://goessner.net/articles/JsonPath/) does not have a good introduction to this feature. reference ：https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/jsonpath/doc.go#L18

**Comment by mick62** [comment]
I did some further research. According to <https://goessner.net/articles/JsonPath/> there is no support for jsonpath sub-expressions. I think that should be stated on the doc reference page.

 But thanks to shell sub-expressions it's possible to use a one-line work-around, e.g. 

`kcv -o=jsonpath="{.clusters[?(@.name=='$(kubectl config current-context)')].cluster.server}"`

Btw. for the specific use-case there is also a way to get the result without the need for a sub-expression:

`kubectl config view --minify -o=jsonpath={.clusters[0].cluster.server}`
