### ISSUE TITLE
Tidy styling of “Change the Reclaim Policy of a PersistentVolume”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22594]
**This is a Bug Report**

**Problem:**
[Change the Reclaim Policy of a PersistentVolume](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/) puts Kubernetes resource names such as PersistentVolume in backticks, for example:
```markdown
policy. With the "Retain" policy, if a user deletes a `PersistentVolumeClaim`,
the corresponding `PersistentVolume` is not be deleted. Instead, it is moved to the
```

The [style guide](https://kubernetes.io/docs/contribute/style/style-guide/) recommends writing resource names
in UpperCamelCase with no backticks.

**Proposed Solution:**
Find the Kubernetes resource namesin the Markdown source for [Change the Reclaim Policy of a PersistentVolume](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/): (`PersistentVolume` and `PersistentVolumeClaim`), and remove the backticks around them where these exist.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/

**Additional Information:**
/good-first-issue
/priority backlog
/language en

**Comment by soniasingla** [comment]
@sftim seems this bug has been already fixed (: We can close this issue.
