### ISSUE TITLE
(ja) kubeadm table not localized

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22593]
**This is a Bug Report**

**Problem:**

In the page [kubeadmのインストール](https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) there are tables inside the section **必須ポートの確認** with English text, that I think would make more sense if translated into Japanese.

**Proposed Solution:**
Translate that table. For example, replace _Self_ and _Control plane_ with appropriate Japanese terms (or loanwords in katakana).

**Page to Update:**
https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#%E5%BF%85%E9%A0%88%E3%83%9D%E3%83%BC%E3%83%88%E3%81%AE%E7%A2%BA%E8%AA%8D

**Additional Information:**
/language ja
/kind bug

**Comment by sftim** [comment]
If it's important to leave that text as English, add a note to this issue to record that, and then close it.

**Comment by inductor** [comment]
This is intentional as things like  "inbound" and "outbound" are not translated in Networking world anyway.
