### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by pgodfrin** [kubernetes/website#22591]
Greetings,Running CentOS 8...
This is what the docs say:
systemd
To use the systemd cgroup driver, set plugins.cri.systemd_cgroup = true in /etc/containerd/config.toml. When using kubeadm, manually configure the cgroup driver for kubelet

So this is what I did:

disabled_plugins = ["cri"]
# pgodfrin, per https://kubernetes.io/docs/setup/production-environment/container-runtimes/
plugins.cri.systemd_cgroup = true

This caused these errors:

-- Unit docker.service has begun starting up.
Jul 19 10:07:45 k8master.local containerd[14869]: containerd: Near line 2 (last key parsed ''): bare keys cannot contain '.'
Jul 19 10:07:45 k8master.local systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 10:07:45 k8master.local systemd[1]: containerd.service: Failed with result 'exit-code'.
Jul 19 10:07:45 k8master.local systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit docker.service has finished shutting down.

And:

-- Unit docker.service has begun starting up.
Jul 19 09:53:05 k8master.local containerd[13318]: containerd: Near line 2 (last key parsed ''): bare keys cannot contain '.'
Jul 19 09:53:05 k8master.local systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 09:53:05 k8master.local systemd[1]: containerd.service: Failed with result 'exit-code'.
Jul 19 09:53:05 k8master.local systemd[1]: Stopped Docker Application Container Engine.
-- Subject: Unit docker.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit docker.service has finished shutting down.

Changed the code to this:

# pgodfrin, per https://kubernetes.io/docs/setup/production-environment/container-runtimes/
[plugins.cri]
    systemd_cgroup = true

It now works!

**Comment by sftim** [comment]
@pgodfrin would you be willing to [open a pull request](https://kubernetes.io/docs/contribute/new-content/new-content/) with the fixes? It sounds like you have a good idea of what these would be.

**Comment by neolit123** [comment]
> [plugins.cri]
> systemd_cgroup = true

this change seems fine. PR welcome.
