### ISSUE TITLE
Issue with k8s.io/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by mridulgain** [kubernetes/website#22599]
**This is a Bug Report**

**Problem:**
This command is not storing any value in variable **NODES**,
```
NODES=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="ExternalIP")].address }')
```
Tried on both *Katakoda* & *Play with k8s*
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/services/source-ip/

**Comment by Cweiping** [comment]
Help me to close this issue, thank you. How can I close it synchronously when PR(https://github.com/kubernetes/website/pull/22725) merges?
@sftim
