### ISSUE TITLE
Localize 404 pages

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22601]
**This is a Feature Request**

**What would you like to be added**
Use Netlify's [custom 404 page handling](https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling) to localize the 404 Not Found page content.

**Why is this needed**
If we link to a page in a localization that is not present (for example, because it has been removed), the error page is in English and not in the language that other pages in that localization use.

**Comments**
Netlify does not support sending 410 Gone responses for pages that we have deliberately removed and that we know will not return, so we also use 404 to cover that case.

/kind feature
/area web-development

**Comment by sftim** [comment]
In https://github.com/kubernetes/website/pull/22536#issuecomment-659806989 @brianpursley pointed out that 404 pages are always in English.

**Comment by sftim** [comment]
Let's treat this a little bit as an umbrella issue. We can create one child issue for each localization that needs to happen.

**Comment by brianpursley** [comment]
Can [this](https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling) help?

> You can set up a custom 404 page for all paths that don't resolve to a static file. This doesn't require any redirect rules. If you add a 404.html page to your site, it will be picked up and displayed automatically for any failed paths.
> 
> You can also use this in combination with other features of our redirects by creating explicit entries for different paths:
> 
> ```
> /en/* /en/404.html 404
> /de/* /de/404.html 404
> ```
> 
> Due to the shadowing behavior in our redirects system, the 404 pages will only be returned for nonexistent assets under the above paths

**Comment by sftim** [comment]
@brianpursley yes it can! (I linked to that page in the issue description).

**Comment by brianpursley** [comment]
D'OH, how did I not see that?  I was looking at the other issue and saw this and thought A-Ha and didn't fully read your description I guess. Sorry!
