### ISSUE TITLE
Translate tasks/configure-pod-container/configure-persistent-volume-storage/ into Korean

### ISSUE THREAD

**Issue by bluefriday** [kubernetes/website#22609]
**This is a Feature Request**

**What would you like to be added**

Translate tasks/configure-pod-container/configure-persistent-volume-storage/ into Korean. 

**Why is this needed**

There is no documents with tasks/configure-pod-container/configure-persistent-volume-storage/ into Korean .

**Comments**

https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by bluefriday** [comment]
@seokho-son @jmyung  해당 문서의 번역 작업을 완료했는데, 현 브랜치(dev-1.18-ko.10)가 현재 freeze 상태인 것 같습니다.
merge 이후 다음 브랜치에 PR 을 올리도록 하겠습니다.

**Comment by seokho-son** [comment]
@bluefriday  감사합니다... 👍 

말씀하신대로, dev-1.18-ko.10 는 freeze 상태이고 8월 20일~21일 경에 master에 머지 예정입니다.
그리고 다음 작업 브랜치가 열리기까지 잠시 휴식시간이 있을 예정입니다.. ㅎㅎ

조만간 1.19가 릴리스(master에 머지)될 예정(8월 25일경)이라, 릴리스에 미치는 영향을 최소화하기 위해서
1.19가 릴리스될때까지, 신규 한글화 작업 브랜치를 생성하지 않습니다.

1.19가 릴리스(8월 25일 이후)되면,
기존 master는 release-1.18 브랜치를 만들어서 관리하고,
dev-1.19는 master에 머지됩니다.

여기서 한글화팀의 작업 브랜치도 2개가 만들어질 예정입니다.
1. release-1.18을 base로 하는 관리용 작업 브랜치 (dev-1.18-ko.11): outdated 된 컨텐츠만 정리합니다.
2. master (1.19)를 base로 하는 한글화 작업용 브랜치 (dev-1.19-ko.1): 한글화 작업이 진행됩니다.

따라서, 향후에 dev-1.19-ko.1 가 만들어지면 dev-1.19-ko.1 로 PR을 올려주시면 되겠습니다.
다만, 버전업이되는 경우, 문서 전반적으로 변화가 커서, 리베이스 작업이 필요하고
혹시 영문에 변경사항이 있다면, 작업하신 한글문서에도 반영이 필요합니다... ^^

**Comment by bluefriday** [comment]
@seokho-son 

네 자세하게 말씀해주셔서 감사합니다. dev-1.19-ko.1 이 생성되면, 현재 문서도 변경분을 고려하여 다시 한글화 해서 PR 을 올리겠습니다~
