### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/monitoring/#what-s-next

### ISSUE THREAD

**Issue by davidffrench** [kubernetes/website#22624]
**This is a Bug Report**

**Problem:**
The monitoring page on the Kubernetes website has a link to `stable Kubernetes metrics` in the What's Next section which links to an empty list in GitHub.

**Proposed Solution:**
I have been unable to find another list of stable metrics.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/monitoring/#what-s-next

**Comment by sftim** [comment]
Looks wrong to me.

/language en
/priority backlog
/kind bug

**Comment by sftim** [comment]
Duplicated by issue #22650

**Comment by Cweiping** [comment]
I tried to compile the generated content of the file locally, but I didn't get any results. It was generated using [this script](https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/update-stable-metrics.sh), but there are bugs and need to be fixed.
