### ISSUE TITLE
How to create the cluster in kube and whats the command

### ISSUE THREAD

**Issue by srsneedis** [kubernetes/website#22634]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Cweiping** [comment]
I don't understand your requirement. Can you describe it in detail? Add a page about creating a k8s cluster?

**Comment by sftim** [comment]
/close

This doesn't seem to be describing a defect nor requesting a feature.
