### ISSUE TITLE
Issue with k8s.io/docs/contribute/

### ISSUE THREAD

**Issue by sandhya816** [kubernetes/website#22658]
**This is a Bug Report**

**Problem:** unable to join worker node to cluster getting below issue.
 kubeadm join <masterIPaddress>:6443 --token ylwxlq.4zkw1oi0hyv64kvq \
>     --discovery-token-ca-cert-hash sha256:111ed20591d3221feea863bf3402b833467ced91bbdadd2640ac2969b3ff773f
W0723 07:28:46.251922    2628 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.18" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[kubelet-check] Initial timeout of 40s passed.
error execution phase kubelet-start: error uploading crisocket: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher
Please help tp provide any solution.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

 kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by neolit123** [comment]
hello,

reading your log it appears kubeadm join fails around the kubelet phase, which could be do a misconfigured kubelet.
you could look at its logs using `journalctl -xeu kubelet`.

but please, for support tickets use the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
or #kubeadm on k8s slack.

thanks
/triage support
/sig cluster-lifecycle
/close
