### ISSUE TITLE
Issue with kubectl not able to be removed from win10 

### ISSUE THREAD

**Issue by alhidalg** [kubernetes/website#22660]
**This is a Bug Report**

Can not remove kubectl from my local machine.
had installed ibmcloud and minikube as well, but have removed these 2 and dependencies without problem, but the kubectl doesn't get remove. 

kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}

**Comment by sftim** [comment]
@alhidalg you can report bugs in kubectl at https://github.com/kubernetes/kubectl/issues/new

This issue tracker is for deporting documentation defects. Did you see anything wrong with the documentation?

/sig cli

**Comment by alhidalg** [comment]
In a way, there is nothing documented to show how to manually remove/uninstall kubernetes in this kind of scenario.

**Comment by sftim** [comment]
If you'd like to log a feature request to document how to uninstall `kubectl` (either just for Windows, or for other platforms too) then go for it @alhidalg 

Anyone can request new documentation features!

**Comment by alhidalg** [comment]
sounds good . Thanks sftim
