### ISSUE TITLE
Formatting not right for “The Distributed System ToolKit: Patterns for Composite Containers”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22672]
**This is a Bug Report**

**Problem:**
The Markdown for [The Distributed System ToolKit: Patterns for Composite Containers](
https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/) (`content/en/blog/_posts/2015-06-00-The-Distributed-System-Toolkit-Patterns.md`) is not rendering correctly. There's an unordered list that, at first glance, just stops.

**Proposed Solution:**
Fix the Markdown

**Page to Update:**
https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/

**Additional Information:**
Usually we avoid fixing old blog articles because there's more valuable work to be done. However, I would make an exception because the Pod concept documentation directly links to this particular article.

/language en
/area blog
/kind cleanup
/help

**Comment by shuuji3** [comment]
@sftim I see other posts (about 15 posts) have the same rendering issues. Can I fix them at the same time? As you said, they are old blog articles but this rendering issue can be easily fixed, just deleting several newline characters.

**Comment by sftim** [comment]
That's fine @shuuji3 - great idea.

**Comment by shuuji3** [comment]
@sftim OK, I'll clean them up. 🧹
