### ISSUE TITLE
https://kubernetes.io/docs/admin/dns/ mentions 'pod.cluster.local'

### ISSUE THREAD

**Issue by ensonic** [kubernetes/website#2268]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The dns search path does not contain 'pod.cluster.local' only the variants for 'svc' (services), but the docs mention 'When enabled, pods are assigned a DNS A record in the form of pod-ip-address.my-namespace.pod.cluster.local.'

**Proposed Solution:**
Since there is no link for how to 'activate' this and instead several bug reports wrt. a libc limit of search entries, this part should probably replaced by a paragraph suggesting to use headless services for pods that needs to be resolved.

**Page to Update:**
https://kubernetes.io/docs/admin/dns/

**Comment by x1957** [comment]
I want to connect to pod vis kubedns,  is the document working now?

**Comment by steveperry-53** [comment]
@davidopp Do you have time to look at this? If not, could you suggest someone else? Thanks.

**Comment by ensonic** [comment]
I give up.

**Comment by sftim** [comment]
The current version of https://kubernetes.io/docs/admin/dns/ doesn't mention `pod.cluster.local`
I'm not sure, but: is this OK to close?
