### ISSUE TITLE
Outdated files in dev-1.18-ko.9 branch

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#22680]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.18-ko.9 branch.

### 42 files to be modified 
1. [ ] content/en/_index.html 1 file changed, 1 deletion(-)
1. [ ] content/en/case-studies/adform/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/capital-one/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/ibm/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/ing/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/naic/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/newyorktimes/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/nordstrom/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/northwestern-mutual/index.html 1 file changed, 5 insertions(+), 5 deletions(-)
1. [ ] content/en/case-studies/ocado/index.html 1 file changed, 4 insertions(+), 4 deletions(-)
1. [ ] content/en/case-studies/openAI/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/pearson/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/pinterest/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/slingtv/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/squarespace/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/case-studies/workiva/index.html 1 file changed, 8 insertions(+), 8 deletions(-)
1. [ ] content/en/case-studies/ygrene/index.html 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/logging.md 1 file changed, 3 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/concepts/containers/images.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/containers/runtime-class.md 1 file changed, 3 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/concepts/overview/working-with-objects/common-labels.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/concepts/overview/working-with-objects/namespaces.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/policy/pod-security-policy.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/services-networking/ingress.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/storage/storage-classes.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/deployment.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/workloads/controllers/job.md 1 file changed, 2 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/statefulset.md 1 file changed, 12 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/contribute/_index.md 1 file changed, 35 insertions(+), 14 deletions(-)
1. [ ] content/en/docs/contribute/advanced.md 1 file changed, 22 insertions(+), 17 deletions(-)
1. [ ] content/en/docs/contribute/new-content/open-a-pr.md 1 file changed, 1 deletion(-)
1. [ ] content/en/docs/contribute/new-content/overview.md 1 file changed, 6 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/contribute/participate/_index.md 1 file changed, 10 insertions(+), 9 deletions(-)
1. [ ] content/en/docs/contribute/review/for-approvers.md 1 file changed, 5 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/contribute/review/reviewing-prs.md 1 file changed, 4 insertions(+), 4 deletions(-)
1. [ ] content/en/docs/contribute/style/write-new-topic.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/reference/issues-security/security.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/reference/kubectl/cheatsheet.md 1 file changed, 4 insertions(+)
1. [ ] content/en/docs/setup/best-practices/certificates.md 1 file changed, 7 insertions(+), 9 deletions(-)
1. [ ] content/en/docs/setup/release/notes.md 1 file changed, 1 insertion(+), 3 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md 1 file changed, 20 insertions(+), 32 deletions(-)

### 1 files to be deleted 
1. [ ] content/en/docs/contribute/participate/roles-and-responsibilties.md

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.18-ko.9` branch.

For example:
```
# checkout `upstream/dev-1.18-ko.9`
...
# check what is updated in the upstream 
git diff upstream/dev-1.18-ko.8 upstream/dev-1.18-ko.9 -- content/en/_index.html
# apply changes to content/ko
vi content/ko/_index.html
...
# commit and push
...
# make PR to `upstream/dev-1.18-ko.9`
```

## Pages to Update

/language ko

**Comment by gochist** [comment]
현행화 작업은 항상 분량이 많기 때문에 분업이 가능하면 좋겠다는 의견이 있었습니다. 현행화 작업에 참여를 원하시는 분은 작업하실 범위를 코멘트로 공유해주시면 좋겠습니다.

**Comment by pjhwa** [comment]
29~42 까지 해보겠습니다. 그리고 마지막 파일 삭제까지.

-  content/en/docs/contribute/_index.md 1 file changed, 35 insertions(+), 14 deletions(-)
-  content/en/docs/contribute/advanced.md 1 file changed, 22 insertions(+), 17 deletions(-)
-  content/en/docs/contribute/new-content/open-a-pr.md 1 file changed, 1 deletion(-)
-  content/en/docs/contribute/new-content/overview.md 1 file changed, 6 insertions(+), 2 deletions(-)
-  content/en/docs/contribute/participate/_index.md 1 file changed, 10 insertions(+), 9 deletions(-)
-  content/en/docs/contribute/review/for-approvers.md 1 file changed, 5 insertions(+), 6 deletions(-)
-  content/en/docs/contribute/review/reviewing-prs.md 1 file changed, 4 insertions(+), 4 deletions(-)
-  content/en/docs/contribute/style/write-new-topic.md 1 file changed, 2 insertions(+), 2 deletions(-)
-  content/en/docs/reference/issues-security/security.md 1 file changed, 1 insertion(+), 1 deletion(-)
-  content/en/docs/reference/kubectl/cheatsheet.md 1 file changed, 4 insertions(+)
-  content/en/docs/setup/best-practices/certificates.md 1 file changed, 7 insertions(+), 9 deletions(-)
-  content/en/docs/setup/release/notes.md 1 file changed, 1 insertion(+), 3 deletions(-)
-  content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md 1 file changed, 1 insertion(+), 1 deletion(-)
-  content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md 1 file changed, 20 insertions(+), 32 deletions(-)

1 files to be deleted
-  content/en/docs/contribute/participate/roles-and-responsibilties.md

**Comment by pjhwa** [comment]
저 삭제될 파일이라고 표시된 roles-and-responsibilities.md 파일은 존재하는데 왜 삭제될 파일이라 나온걸까요?

> 1 files to be deleted
> * content/en/docs/contribute/participate/roles-and-responsibilties.md

**Comment by pjhwa** [comment]
나머지 부분도 제가 하겠습니다.

/assign @pjhwa
