### ISSUE TITLE
Improvement for k8s.io/zh/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by woshiqiuxiaoyan** [kubernetes/website#22719]
我想要知道怎么样创建一个minikube在我本地，然后这个页面给我导向怎么用minikube 创建集群交互去了

**Comment by tengqm** [comment]
That page is about creating cluster, not about downloading minikube.
You can install minikube by following instructions [here](https://kubernetes.io/docs/tasks/tools/install-minikube/).
