### ISSUE TITLE
Stale branches in k/website

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22729]
**This is a Bug Report**

**Problem:**
[k/website](https://github.com/kubernetes/website) includes stale branches:
- [`Case-nit-for-k8s`](https://github.com/kubernetes/website/tree/Case-nit-for-k8s)
- [`ingress-in-vi`](https://github.com/kubernetes/website/tree/ingress-in-vi)
- [`revert-18215-master-zh-fix-links`](https://github.com/kubernetes/website/tree/revert-18215-master-zh-fix-links)
- [`what-is-k8s`](https://github.com/kubernetes/website/tree/what-is-k8s)

**Proposed Solution:**
Prune the stale branches.

**Additional Information:**
/kind cleanup

Cc: tech leads: @kbhawkey, @onlydole - any concern or objection?

**Comment by onlydole** [comment]
I'm in favor of that, @sftim. I don't see that causing any issues.

**Comment by kbhawkey** [comment]
I agree. Good to clean up. Thanks!

**Comment by sftim** [comment]
Making it so.
