### ISSUE TITLE
Localize website into Arabic (ar)

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22726]
**This is a Feature Request**

**What would you like to be added**
Create an initial, at least minimum-viable Arabic (العربية) localization for https://k8s.io/

**Why is this needed**

Arabic is a widely-spoken language in the wider arabian region of the world with over 250 million total speakers. This change will help make Kubernetes available to a wider audience. 

**Comments**
> The CNCF believes that that everyone in the community that wants to participate feels welcome to do so regardless of gender, gender identity, sexual orientation, disability, race, ethnicity, age, religion or economic status.

/language ar

**Comment by sftim** [comment]
Related pull requests:
- #16894
- #16942
- #19758
- #20343
- #20459

/kind feature

**Comment by ijelliti** [comment]
@sftim I would assist on this

**Comment by sftim** [comment]
Also see [#kubernetes-docs-ar](https://kubernetes.slack.com/messages/CP9FKRD51/) (or visit https://slack.k8s.io/ for an invitation to Slack).

**Comment by sftim** [comment]
@mohamedsgap, @nofalx and others - is there any help that the SIG Docs team (who don't speak any Arabic) can do to help move things forward?

**Comment by mboukhalfa** [comment]
@sftim I'd like to request the reopening of the issue regarding the localization of the Kubernetes website into Arabic (العربية) - Issue #22726.

During my recent work on the Arabic (AR) localization efforts, I have made significant progress, including an [open pull request](https://github.com/kubernetes/website/pull/37547) and an [umbrella issue](https://github.com/kubernetes/website/issues/37546). I have also submitted a [membership request](https://github.com/kubernetes/org/issues/4288) to contribute to this important endeavor.

Based on the ongoing progress and the need for clear documentation and community feedback, I believe it would be beneficial to reopen the issue. to provide a clear overview of the localization efforts and track the related discussions and updates. By reopening the issue, we can document the progress and gather feedback from the community. It will also help in building a collaborative environment where multiple contributors can review and support each other's work.

I kindly request your consideration and support in reopening the issue. Please feel free to add any additional context or suggestions to further enhance the localization efforts.

**Comment by sftim** [comment]
/reopen

We can continue to track the work towards finding an Arabic localization team.

**Comment by ibrahimjelliti** [comment]
Thank you @mboukhalfa, definitely can contribute )

**Comment by sftim** [comment]
Do we have a team looking to work on this issue? If so, please introduce (or reintroduce) yourselves here.

**Comment by mboukhalfa** [comment]
> Do we have a team looking to work on this issue? If so, please introduce (or reintroduce) yourselves here.

Hi @sftim, I'm really interested in working on this Arabic localization issue! I've already reached out to @selaamimech who might be interested in contributing as well. Although things are progressing slowly, I'm determined to make this happen.

**Comment by selaamimech** [comment]
> > Do we have a team looking to work on this issue? If so, please introduce (or reintroduce) yourselves here.
> 
> Hi @sftim, I'm really interested in working on this Arabic localization issue! I've already reached out to @selaamimech who might be interested in contributing as well. Although things are progressing slowly, I'm determined to make this happen.

I am available also to contribute, I suggest to create a new target branch. Then I will create a new PR from my fork that contains the minimal required content as a first step.

**Comment by sftim** [comment]
Hi @mboukhalfa and @selaamimech 

A good way to get started is to open some **draft** PRs against _main_, as a sketch of what you'd like to do.

**Comment by sftim** [comment]
No progress

/close not-planned

**Comment by adowair** [comment]
Hello @sftim @mboukhalfa, joining the bandwagon! I'm happy to contribute and will go ahead and put together a set of draft PRs. I have read the [contribution guide](https://kubernetes.io/docs/contribute/localization/) and see that @mboukhalfa has created an umbrella issue #37546—do you have any guidance otherwise as to where I ca start?

**Comment by seokho-son** [comment]
> Hello @sftim @mboukhalfa, joining the bandwagon! I'm happy to contribute and will go ahead and put together a set of draft PRs. I have read the [contribution guide](https://kubernetes.io/docs/contribute/localization/) and see that @mboukhalfa has created an umbrella issue #37546—do you have any guidance otherwise as to where I ca start?

PTAL https://github.com/kubernetes/website/issues/44682 for the restart.
