### ISSUE TITLE
Translate tasks/service-catalog/install-service-catalog-using-sc.md into Korean

### ISSUE THREAD

**Issue by pjhwa** [kubernetes/website#22720]
**This is a Feature Request**

**What would you like to be added**

Translate tasks/service-catalog/install-service-catalog-using-sc.md into Korean.

**Why is this needed**

There is no document of tasks/service-catalog/install-service-catalog-using-sc/ which is translated into Korean.

**Comments**

Page to translate: https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-sc/

/language ko

**Comment by sftim** [comment]
BTW, the upstream English page page is liable to be [removed](https://github.com/kubernetes/website/issues/22008#issuecomment-648488669) so you might like to focus on other translations ahead of this one.

**Comment by pjhwa** [comment]
> BTW, the upstream English page page is liable to be [removed](https://github.com/kubernetes/website/issues/22008#issuecomment-648488669) so you might like to focus on other translations ahead of this one.

Oops. 
OK, I got it. I've already translated, but I think I don't need to get review from ko-reviewers.

**Comment by seokho-son** [comment]
The upstream English document (tasks/service-catalog/install-service-catalog-using-sc) will be removed. 
Forks, please don't translate this document.
This issue will be closed after the upstream English document has been removed.
