### ISSUE TITLE
https://kubernetes.io/zh/docs/concepts/ page not updated

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#22741]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/zh/docs/concepts/ this page is not updated. Chinese content not correspond to English version.
**Proposed Solution:**
Update Chinese version page
**Page to Update:**
https://kubernetes.io/zh/docs/concepts/

**Comment by sftim** [comment]
The existing Chinese page is different and (slightly) misleading.

/kind bug
/language zh
/priority backlog

**Comment by tengqm** [comment]
I've been working on it.
/assign

**Comment by tengqm** [comment]
Done.
/close
