### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by ismizelal** [kubernetes/website#22776]
**Missing tab "Installing a Pod network add-on" **

**Problem**
 Missing tab in "https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/"
On of the CKA exam requirement is to apply the following command, but it is not present in the above link 
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
**Proposed Solution:**
It needs to be in the kubernetes official website!

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
Hi. The CNI tabs were removed in #22600. For more details see that PR.

/close
