### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/addons/

### ISSUE THREAD

**Issue by Tej-Singh-Rana** [kubernetes/website#22777]
**Problem:**
I am looking for Networking Plugins anyhow i reached weave net addons in the kubernetes official docs.
Location is :- https://kubernetes.io/docs/concepts/cluster-administration/addons/
When i clicked on the "Weave Net". It redirected to me into the https://www.weave.works/docs/net/latest/kube-addon
At there i have seen only "Network Policy and Security".
I would like to know that It's trying to redirecting to me into this https://www.weave.works/docs/net/latest/kubernetes/kube-addon/  or other?
**Proposed Solution:**
If it's trying to redirect into the network plugin page then kindly update it URL link. May be in the weave official page has changed location.
https://www.weave.works/docs/net/latest/kubernetes/kube-addon/
**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/addons/

**Comment by Cweiping** [comment]
I agree with you and can submit PR to update it. Relationships are required for versions in different languages.
/ good-first-issue 
/ kind cleanup

**Comment by Tej-Singh-Rana** [comment]
https://github.com/kubernetes/website/pull/22789
I am not getting any response might be they are busy.

**Comment by blueabysm** [comment]
Hi @Cweiping , let me handle this if you do not mind :)

**Comment by blueabysm** [comment]
Hi @Cweiping , Maybe you are working with this issue now? Ignore my assign tag before. 😂

**Comment by Cweiping** [comment]
It doesn't matter. @Tej-Singh-Rana fixing it.

**Comment by zacharysarah** [comment]
Closed by #23287 
/close
