### ISSUE TITLE
Reorganize pages in Tasks section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#22788]
**This is a Feature Request**

**What would you like to be changed**
Update the tasks section to reorganize the existing pages within a better defined and more navigable layout, such as:
- Install Tools
  _(aside: I'd mention `kubeadm` here, future enhancement)_
- Run Applications
  - Run Jobs
- Inject Data Into Applications
- Access Applications in a Cluster
- Configure Pods and Containers
- Manage Kubernetes Objects
- Manage Resources
- Secure Your Workload
- Monitoring, Logging, and Debugging
- Administer a Cluster
  - `kubeadm`
  - Configure Networking
  - Cluster Security
- Extend Kubernetes
   - Use CustomResourceDefinitions

**Why is this needed**
The existing [Tasks](https://kubernetes.io/docs/tasks/) pages have a number of issues, including
- there are _many_ task categories (17) on the top level list
- deeper in, the number of tasks at other levels makes the task list a little hard to navigate
  For example there are 38 tasks in [Administer a cluster](https://kubernetes.io/docs/tasks/administer-cluster/)
- The ordering is unintuitive; for a good example see [Configure Pods and Containers](https://kubernetes.io/docs/tasks/configure-pod-container/) as of commit e16b0f7212f819f899e6d5bcee1d4a4d87ad3052.

**Comments**
Relevant to issue #22786

**Comment by sftim** [comment]
Here's a layout we could adopt:
- Install Tools
  _(aside: I'd mention `kubeadm` here, future enhancement)_
- Run Applications
  - Run Jobs
- Inject Data Into Applications
- Access Applications in a Cluster
- Configure Pods and Containers
- Manage Kubernetes Objects
- Manage Resources
- Secure your workload
- Monitoring, Logging, and Debugging
- Administer a Cluster
  - `kubeadm`
  - Configure Networking
  - Cluster security
- Extend Kubernetes
   - Use CustomResourceDefinitions

**Comment by sftim** [comment]
@tengqm, you had some reservations about making this change?

**Comment by tengqm** [comment]
@sftim No, I am not a big fan of this effort for several reasons. Most of the tasks are talking about different aspects of managing, accessing applications, or managing the cluster itself. I'm doubting there is any inherent logic between security and managing resource limit or quota. There are always a thousand ways to navigate the tasks or even the concepts, although we can somehow categorize things into different levels e.g. `basics`, `intermediate` or `advanced` etc.

Another factor we may want to consider is that our audiences are from different background. They may be using hosted clusters or just a single node setup... Not all of the tasks are useful for all users. That is something we cannot change no matter how we reorganize the tasks to make the topics flow. In other words, the topics will never flow, I'm afraid.

Yet another reason I'm against this is that we will be introducing a lot of chaos into the community. It is hard to track which paragraph/page was moved, when and where. If the reorg does improve user experience significantly, we can communicate that to the localization teams. However, if the reorg itself is something in question, something of limited value, we'd better think twice. It may seem not a big change when we restructure a paragraph. When you consider for a moment the big picture ... we have 15 localization teams today. That change must be propagated into 15 subdirectories eventually, after reworked by 15 other people who resynchronize the text line by line, and another 15 people to review it.

I do personally appreciate the intent and the effort to improve the docs in whatever way. What I'm trying to articulate is that we may be on the wrong track if we are going down this road.

If we are trying to make the site easier to navigate, we can still avoid doing it in a disruptive way like reorganizing the topics. We may instead want to design a navigating subsystem, in addition to the current directory structure and search engine. For example, if I'm an engineer trying to find documentations on improving the performance of the cluster, what kind of topic groups can we offer? If I'm instead a developer trying to diagnose some application availability issue, do we have a list of topics for him/her to read? If I'm a newbie in this cloud native space, where should I start: Managing Kubernetes objects or running applications or some tutorial about `kubectl`?

**Comment by kbhawkey** [comment]
Re: `what kind of topic groups can we offer`
Is there any interest in adding metadata to the task files -- to possibly use this data for searching and dynamic grouping of tasks, presenting different task views. Not sure if that would be confusing.

**Comment by sftim** [comment]
> adding metadata to the task files

That sounds like a great idea - maybe another issue inside the same umbrella issue?

**Comment by tengqm** [comment]
Indeed, tagging is a good idea. Not sure if hugo has some tag specific features to leverage.

**Comment by sftim** [comment]
> Not sure if hugo has some tag specific features to leverage.

There are various options. One that I like the idea of is creating [headless bundles](https://gohugo.io/content-management/page-bundles/#headless-bundle) that represent groups of tasks. Each bundle could be a Markdown list of links, and then we give Hugo and Sass the job of rendering those nicely.

That approach lets a task appear in more than one grouping.

**Comment by kbhawkey** [comment]
Headless "bundle" strikes again 👻 . Could work -- have not considered how or why.

When I originally mentioned looking into the `tasks` section, I was thinking more along the lines of
revitalizing the section. I would consider renaming this umbrella issue.
This could mean some reorganization, but that was not my main point.
I like the idea of tagging or providing more hints about what readers can get out of a task (what is the goal of the task).
However, some of the "revitalization" could be cleanup of the content and ensuring that the task content
is relevant to the concept content. Adding metadata would be helpful and then "bundles of tasks" could be 
created or featured. I have not looked into/used Hugo taxonomies.

**Comment by kbhawkey** [comment]
While cleaning up content in PR #24772, I thought it may be interesting to add metadata in the
task page front matter. The metadata could tag a task with a list of related APIs (add more data as needed).
This may help categorize the tasks.
Later on, the metadata could be used to connect up other pieces of content on the page or other places in the site.
