### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by cezane** [kubernetes/website#22803]
**This is a Bug Report**

**Problem:**
You say that we can use the labels to remove a service. But when I use the given label app=v1, the service is not removed and I receive the following message:

```
kubectl delete service -l app=v1    
No resources found
```

**Proposed Solution:**
Change the text to explaining why using the given label does not work.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/ (interactive tutorial)

**Comment by Cweiping** [comment]
Do you strictly follow the interactive command window? The command does not exist in the terminal of this page.
```shell
kubectl delete service -l run=kubernetes-bootcamp
```
/triage needs-information

**Comment by cezane** [comment]
Yes. I followed the suggested command and it worked as it should. But when I read that we could use also the labels, I tried with the label `app=v1` and it did not work. I think you can add some information regarding this, explaining that the labels will not work on that interactive window and we should only follow the suggested commands strictly as they are shown.

**Comment by Cweiping** [comment]
Interestingly, I add a label to an `svc`, and then view and delete resources through the label.
![企业微信截图_45cb0f02-185c-4330-abcd-ca89120e837a](https://user-images.githubusercontent.com/33973679/88870348-b63a3380-d247-11ea-95a8-0763cbbfa1af.png)

**Comment by Cweiping** [comment]
remove /triage needs-information

**Comment by cezane** [comment]
Strange... I tried again and same problem occurred:
```
$ kubectl get pods -l app=v1                                                         
NAME                                   READY   STATUS    RESTARTS   AGE              
kubernetes-bootcamp-765bf4c7b4-kx595   1/1     Running   0          9m17s            
$ kubectl delete service -l app=v1                                                   
No resources found  
```

**Comment by Cweiping** [comment]
`app=v1 ` belongs to pod, not service. You Can use `kubectl get service -o yaml` to check service labels.
/close

**Comment by Cweiping** [comment]
It can't be reproduced.
/close
