### ISSUE TITLE
Issue with k8s.io/docs/tasks/extend-kubernetes/http-proxy-access-api/

### ISSUE THREAD

**Issue by dfedorov-ciena** [kubernetes/website#22815]
**This is a Bug Report**

**Problem:**
kubectl create deployment node-hello --image=gcr.io/google-samples/node-hello:1.0 --port=8080
gives:
Error: unknown flag: --port
See 'kubectl create deployment --help' for usage.

**Proposed Solution:**
I cannot find anywhere when and who deleted that "--port" option, so I have no idea how to it properly.

**Page to Update:**
https://kubernetes.io/...

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Cweiping** [comment]
There is a problem with [this PR](https://github.com/kubernetes/website/pull/22433) change. We are still in version 1.18, and there is no `--port` flag. It is a feature introduced in 1.19.Do you need to fix this version? @tengqm

/language zh
/kind bug

**Comment by dfedorov-ciena** [comment]
No, thank you, it's good. Closing.

https://github.com/kubernetes/website/pull/22433/commits/621e5e72362184411ee9c0ad3f287f3cafa91419
