### ISSUE TITLE
clean up extra h1 heading in blog post

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#22817]
**This is a Bug Report**

There is an extra H1 level heading in the `sig-windows-spotlight-2020` blog post.

**Problem:**

https://kubernetes.io/blog/2020/06/30/sig-windows-spotlight-2020/

**Proposed Solution:**
Remove the H1 heading as the title is generated by the publishing tool.

**Page to Update:**
website/content/en/blog/_posts/2020-06-30-SIG-Windows-Spotlight

You can safely remove,
```
# SIG-Windows Spotlight
```

**Comment by jimangel** [comment]
fixed in #22825 thanks @npu21!
/close
