### ISSUE TITLE
prefooter, git-info.html, Analytics alt image src

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#22819]
**This is a Bug Report**
Analytics link on content pages.

**Problem:**
In the prefooter, there is an "Analytics" link that is displaying the alt text. Investigate if the query
for the image source is correct. I am not familiar with the functionality or history of the code in the prefooter.

```
 <div class="issue-button-container">
    <p>
      <a href=""><img alt="Analytics" src="https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/{{ .Path }}?pixel"/></a>
    </p>
```

**Proposed Solution:**
To be investigated.

**Page to Update:**
Investigate the query from the partial, `layouts/partials/git-info.html`

**Comment by nicolaiskogheim** [comment]
```sh
# In repo root
$ rg '\?pixel'

content/zh/docs/tutorials/stateful-application/cassandra.md
807:[!Analytics](https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/cassandra/README.md?pixel)]()

layouts/partials/git-info.html
7:      <a href=""><img alt="Analytics" src="https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/{{ .Path }}?pixel"/></a>
```

Point being, there's a reference in `content/zh/docs/tutorials/stateful-application/cassandra.md:807` as well.

---------------

Visiting one of these analytics links, i.e. [1], yields a page that displays

```
Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.
```

[1] https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/docs/concepts/services-networking/ingress.md?pixel

**Comment by kbhawkey** [comment]
Thanks @nicolaiskogheim . Yes, I agree.
