### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

### ISSUE THREAD

**Issue by wangkundo10** [kubernetes/website#22814]
systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-07-29 08:46:32 EDT; 919ms ago
     Docs: https://kubernetes.io/docs/
  Process: 9982 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255)
 Main PID: 9982 (code=exited, status=255)

Jul 29 08:46:32 node1 systemd[1]: Unit kubelet.service entered failed state.
Jul 29 08:46:32 node1 systemd[1]: kubelet.service failed.

**Comment by neolit123** [comment]
please try reporting this on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

note that the kubelet service will fail until you give it the file specified by --config (or call kubeadm init/join).

/close
/triage support
/sig cluster-lifecycle
