### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by molgor** [kubernetes/website#22872]
**This is a Bug Report**

**Problem:**
The image: gcr.io/google-samples/kubernetes-bootcamp:v1
Doesn't exist anymore.
Error: PullBackError

**Proposed Solution:**
Give an existing url

**Page to Update:**
https://kubernetes.io/...

🍻

**Comment by molgor** [comment]
The interactive example works in the Katacoda app. It doesn't work in a normal K8s installation. That is, the engine container platform does not have the image anymore.

**Comment by Cweiping** [comment]
When I use `docker pull gcr.io/google-samples/kubernetes-bootcamp:v1` locally, there is no situation you said. Can your environment access the repo ?

/triage needs-information
