### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-intro/

### ISSUE THREAD

**Issue by crw** [kubernetes/website#2288]
**This is a...** 

- [X] Feature Request
- [X] Bug Report

**Problem:**

The fonts on the Tutorials pages are atrocious. Small, tight kerning, difficult to read. It is like looking at a dark grey blob. The specific font and the page styles do not respond well to being upsized (CMD-+) either; it still looks pretty awful. 

**Proposed Solution:**

Just use a normal font like "Helvetica, Arial, sans-serif". Something legible with normal letter spacing. 

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
Thanks for the issue.

Looks like the existing Kubernetes Tutorial uses it's own CSS, separate from the site styles.  We need to either remove this CSS, or get it closer to the styles of our current site.

**Comment by crw** [comment]
:(
