### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by vmorris** [kubernetes/website#22897]
**This is a Bug Report**

**Problem:**
Tutorial states to use `kubectl apply -k .`

This fails with:

```
$ kubectl apply -k .
Error: unknown shorthand flag: 'k' in -k
```

**Proposed Solution:**
Fix the tutorial. To be honest it's pretty bad to begin with. There's not a good explanation of what's going on and nobody needs to run `cat` command with heredoc redirection (twice on the same file!!) in a beginner tutorial.

**Page to Update:**
https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/

**Comment by vmorris** [comment]
Thanks... I was on `v1.10+`. My mistake!

**Comment by blueabysm** [comment]
> Thanks... I was on `v1.10+`. My mistake!

No worries! Glad to be helpful to you.😃
