### ISSUE TITLE
Stateless example in docs should use be reviewed

### ISSUE THREAD

**Issue by castrojo** [kubernetes/website#22918]
So I'm in the middle of a workshop with students using K8s and the example workshop links to this tutorial:

- https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

I did some digging and this terminology still seems to be an issue that redis hasn't solved so I'm wondering if we should just find someone to redo this with a stateless example that just avoids redis altogether. Either way just wanted to get this on the radar as it's received complaints.

**Comment by cblecker** [comment]
/sig docs
/wg naming

cc @kubernetes/sig-docs-en-owners @kubernetes/wg-naming 

Yeah, this example could be re-done without the use of redis if need be.

**Comment by cblecker** [comment]
It looks like this example might also just be broken?

ref #19821 #20088

**Comment by castrojo** [comment]
/assign @paulczar 

Paul's agreed to look at the example and work on a PR.

**Comment by paulczar** [comment]
@castrojo PR made to both the website and the examples repos.  One followup is needed which is to upload the newly built example image to a suitable location that isn't my personal dockerhub repo.

**Comment by sftim** [comment]
Redis _has_ switched away from using the term “slave” so I'm wondering if this change is needed.
WG Naming - does this need fixing? Add `/priority xxx` if it's passed triage.

**Comment by kbhawkey** [comment]
I understand the rationale for changing this tutorial; however, is it worthwhile to investigate if it is possible to modify the terminology and naming of the example files, fields, and images.

**Comment by sftim** [comment]
@kbhawkey has put it better than I did in https://github.com/kubernetes/website/issues/22918#issuecomment-668228304

The existing page is wrong; I wonder if we need to change the product as well as fix the wording?

**Comment by kbhawkey** [comment]
Since this should be fixed soon,
/remove-lifecycle stale

**Comment by justaugustus** [comment]
PR opened here: https://github.com/kubernetes/examples/pull/410

**Comment by castrojo** [comment]
Woo hoo! Thanks Celeste!
