### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by tarunactivity** [kubernetes/website#22917]
**This is a Bug Report**

**Problem:**
There is a lot of wasted space on the page due to:
-  Top header frame
- Left side search links that cannot be minimized 
- Blank space on the right of the frame with no content
 - Centre of the page contains the quiz/questions,  and the terminal frame on the right.

When entering, and then returning from the full screen mode on the terminal, the quiz/content
has resized to occupy ~60% of the center frame, leaving less space for the terminal.

**Proposed Solution:**
- Allow the content frame to use the full width of the  page, to make better  use of the screen size.
- Allow hiding left links if required

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by sftim** [comment]
Thanks for the suggestion @tarunactivity
