### ISSUE TITLE
Home Page Improvements

### ISSUE THREAD

**Issue by jaredbhatti** [kubernetes/website#2293]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The sections "Planet Scale, Never Outgrow, and Run Anywhere" on the homepage add very little to the experience. 

**Proposed Solution:**
Remove these sections. 

**Page to Update:**
http://kubernetes.io/

**Comment by bobsky** [comment]
Also, replace generic photo of Seattle on homepage, with speaker from the video it references. Here are two photos from the CloudNativeCon/KubeCon talk featured in the video: 
https://www.flickr.com/photos/143247548@N03/25344270239/
https://www.flickr.com/photos/143247548@N03/30250363423/

**Comment by bobsky** [comment]
Postpone removing any content from home page. (Typos fixes are ok). Saving for a site holistic refresh in the future.

**Comment by steveperry-53** [comment]
@jaredbhatti @bobsky What's the status of this? Does it need to be P1? Is there a specific time in the future that someone is planning a holistic site refresh? Thanks.

I guess I also have this question: Who's in charge of the kubernetes.io page? I have some vague memory that it's not those of us on the writing team.

**Comment by steveperry-53** [comment]
In #3380 @pete-uc says, "we need to roll back #2293, since this will no longer be needed." Does that mean this issue is no longer needed? If so, let's close. If not, help me understand what needs to be done here. Thanks.
