### ISSUE TITLE
Container Spell check - Documentation

### ISSUE THREAD

**Issue by bjaneshwar** [kubernetes/website#22947]
Resource sharing and communication - https://kubernetes.io/docs/concepts/workloads/pods/#resource-sharing-and-communication

The text reads " Pods enable data sharing and communication among their constituent **containters**."

Suggested edit : "Pods enable data sharing and communication among their constituent **containers**. "

Comments: It could be a miss on spell check, please review.

Thanks,
Janeshwar

**Comment by Arhell** [comment]
Fixed, can be closed
