### ISSUE TITLE
yarn or npm? that's the problem!

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#22958]
**This is a Bug Report**

As discussed in the SIG-Docs meeting, the current steps for building doc website in README is incomplete in the following point of views.

- It requires yarn on top of npm, but yarn.lock is missing and package-lock.json is there.
  - `npm ci` did not work for me but I need further investigation on it.
- The build step is going to be equal in containerized and local in https://github.com/kubernetes/website/issues/22515 , but yarn installation or npm ci is currently missing in `make container-image`.

**Proposed Solution:**

1. Use `npm` and remove yarn from the dependency
2. Run the npm command inside of the container

**Page to Update:**

N/A

**Comment by inductor** [comment]
Here's my cat picture after the sig-doc meeting lol

![Image from iOS (4)](https://user-images.githubusercontent.com/20236173/89332078-be71f300-d6cd-11ea-87b1-cce865f5c6e1.jpg)

**Comment by sftim** [comment]
AIUI, the live website build (within Netlify) relies on `npm`, and does _not_ use Yarn.

**Comment by inductor** [comment]
@sftim Could you have a quick look if npm ci in local works just fine?

**Comment by kbhawkey** [comment]
> 
> 
> @sftim Could you have a quick look if npm ci in local works just fine?

Yes, I believe so.

**Comment by inductor** [comment]
`npm ci` worked in my local environment

**Comment by sftim** [comment]
/sig contributor-experience
I suppose
