### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by CptBorg** [kubernetes/website#22953]
It would be VERY helpful to know, that you have to download, extract, etc... the etcd binaries. Or that etcd will run as pods. The only point where this is mentioned is in the "optional" section...

thank you!

**Comment by neolit123** [comment]
hello, this is a valid request.
PRs are welcome.

this list here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#before-you-begin

could include something like:
```
- Have access to the Kubernetes container image registry (`k8s.gcr.io`) or list/pull the required etcd image using
`kubeadm config images list/pull`. This guide will setup etcd instances as
[static pods](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/ managed by a kubelet.
```

file to change:
https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md

/sig cluster-lifecycle
/kind feature
/priority backlog
/help
/good-first-issue

**Comment by Evalle** [comment]
I think I can help with this, thank you.
