### ISSUE TITLE
API links are broken; they use the kubernetes release version instead of the api version.

### ISSUE THREAD

**Issue by patricklundquist** [kubernetes/website#22964]
**This is a Bug Report**

**Problem:**
API links are using the wrong version, which breaks the link. See: "v1alpha1" and "v1alpha2" at https://kubernetes.io/docs/reference/scheduling/profiles/

**Proposed Solution:**
Use the correct version. It should be the api library version, which is v0.18.0 in this case, not the kubernetes release version (currently v1.18.0).

**Page to Update:**
https://kubernetes.io/docs/reference/scheduling/profiles/

**Comment by sftim** [comment]
I'm surprised to see a 0.18.0 version number there; what does this mean? Do releases of the ComponentConfig APIs happen at the same cadence as Kubernetes minor releases?

If there is a rule like “to work out the version of the ComponentConfig API, take the current minor version, subtract 1 from the major version† , and set patch version to 0” then I'd probably favor an automated solution, so it stays correct for future releases without toil.

Maybe there's also grounds for a feature request (separate GitHub issue) to document ComponentConfig within https://kubernetes.io/docs/

† in which case, watch out for Kubernetes 2.x.x

**Comment by sftim** [comment]
I looked, and I also noticed https://github.com/kubernetes/kube-scheduler/blob/release-1.18/config/v1/types.go which implies there's a v1 scheduler configuration API that was part of release v1.18 of Kubernetes.

**Comment by sftim** [comment]
Duplicated by issue #23239

**Comment by reylejano-rxm** [comment]
/assign @reylejano-rxm 

Opened PR #23288 to resolve this issue

**Comment by sftim** [comment]
/close

Addressed in PR #23288
