### ISSUE TITLE
Localization contributing and maintaining guide

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#22960]
**Issue**

> discussed in the SIG Docs weekly meeting on 8/4/2020

SIG Docs has a guide on getting **started** with localizing the docs for a new language: https://kubernetes.io/docs/contribute/localization/

However, the content covering how to **continue** contributions for each specific localization is lacking. For example, specific on boarding, strategy, process, approach, etc.

As a result, some localization teams have created their own guides (website forks, readme.md, etc) for their specific language.

**Resolution**

SIG Docs, in coordination with all localization teams, should define and document a process to create their own guide.

For SIG Docs (english), a reasonable outcome would be updating https://kubernetes.io/docs/contribute/localization/ with a process and framework to follow. For SIG Docs (localization), a reasonable outcome would be aligning with the process and providing input along the way.

**Optional**

Create generic scripts, automation, or tooling to assist with continued contribution efforts for all localization. Even if it's only a starting point.

For example, it would be nice if there was a generic script or automation to view recent English changes given a set of inputs to assist with localization efforts when a previously translated doc changes. I believe this exists for certain teams but it is not a generic utility.

**Questions / Comments?**

/cc @inductor @sftim @kbarnard10 @onlydole @kbhawkey @zacharysarah 

(**TODO:** share this issue with localization groups and raise awareness at APAC) 

language name | language code | assigned to
-- | -- | --
Arabic | ar | `sftim`
Belarusian| be | `sftim`
German | de | `sftim`
Indonesian | id | `inductor`
Japanese | ja | `inductor`
Korean | ko | `seokho-son`
Spanish | es | `a-mccarthy`
French | fr | `a-mccarthy`
Hindi | hi | `a-mccarthy`
Mandarin | zh |  `reylejano-rxm`
Portguese | pt | `divya-mohan0209`
Russian | ru |  `divya-mohan0209`
Italian | it |  `divya-mohan0209`
Vietnamese | vi |  `reylejano-rxm`
Ukrainian | uk |  `reylejano-rxm`
Persian | fa |  `reylejano-rxm`

**Comment by sftim** [comment]
OK, I'll share this with:
Arabic - `ar`
Belarussian (?) - `be`
German - `de`

and can pick up another group later if that's useful.

**Comment by inductor** [comment]
I shared this in Korean channel!

**Comment by seokho-son** [comment]
Korean l10n team is aware of this issue :) 
We are preparing a document to share workflow for Korean l10n to other l10n teams.

**Comment by a-mccarthy** [comment]
I'll share this with:
- [ ] Spanish - `es`
- [ ] French - `fr`
- [ ] Hindi - `hi`

I can help share with other groups as well if you need me too.

**Comment by sftim** [comment]
@inductor @jimangel  I copied the table from https://github.com/kubernetes/website/issues/22960#issuecomment-668981556 into the main issue description, hope that's OK.

**Comment by sftim** [comment]
@divya-mohan0209 & @reylejano-rxm you also mentioned you might pick up tasks here - mentioning it for visibility.

**Comment by divya-mohan0209** [comment]
I'd be happy to take it up for Portuguese, Italian, Russian.

**Comment by inductor** [comment]
@divya-mohan0209  feel free to edit the table for assignment. If you dont have the permission bump me on Slack so that I will do it for you :)

**Comment by reylejano-rxm** [comment]
I'll take

* [x]  Mandarin - `zh`
* [x]  Vietnamese - `vi`
* [x]  Ukrainian - `uk`
* [x]  Persian - `fa`

**Comment by MaxymVlasov** [comment]
Hi folks!

Here is flow that used Ukrainian translation team: https://github.com/kubernetes/website/issues/20786
It mostly same as other onboarding guides.

For creating translation issues from scratch I created [this script](https://github.com/kubernetes-i18n-ukrainian/utils/tree/master/website_100_popular_pages_issue_creator)
It can be helpful for coordination and focus on most wanted pages for new localization teams.

**Comment by inductor** [comment]
In the discussion, @jimangel mentioned that we could use GitHub wiki for sharing the localization tips from each localization team.

**Comment by inductor** [comment]
I found this page but it looks very old(2017 last edited)
https://github.com/kubernetes/website/wiki/Guidelines-for-Reviewing-and-Merging-PRs

**Comment by sattarfeizollahibarough** [comment]
> 
> 
> Hi folks!
> 
> Here is flow that used Ukrainian translation team: #20786
> It mostly same as other onboarding guides.
> 
> For creating translation issues from scratch I created [this script](https://github.com/kubernetes-i18n-ukrainian/utils/tree/master/website_100_popular_pages_issue_creator)
> It can be helpful for coordination and focus on most wanted pages for new localization teams.

Hi guys,
@MaxymVlasov the idea is totally fine, is that possible to consider the page hit instead of how it is popular?

**Comment by MaxymVlasov** [comment]
@sattarfeizollahibarough sure.
'Page popularity' is 'how many times page was open duiring period'

And you can provide any other 'popularity' list just replace [locations file](https://www.github.com/kubernetes-i18n-ukrainian/utils/tree/master/website_100_popular_pages_issue_creator%2Flocations).

Now `locations` file include data from https://github.com/kubernetes/website/issues/17598

**Comment by girikuncoro** [comment]
is it possible for us to get access to the Google analytics kubernetes website? I want to see how many visitors/readers visit e.g. kubernetes.io/id every month/week/day, to see the progress and motivate the localization team. What are the top visited localized pages, etc. Until know I always need to bug someone to get this data.

**Comment by sftim** [comment]
> is it possible for us to get access to the Google analytics kubernetes website

@girikuncoro could you log a GitHub issue to request that access, or put that suggestion the agenda for a SIG Docs weekly meeting? If you're not sure what I'm suggesting there, I can explain more in detail or I can pass on a request on your behalf.

**Comment by sftim** [comment]
/sig contributor-experience

I think

**Comment by mkorbi** [comment]
@jimangel happy to give some hands for DE

**Comment by jimangel** [comment]
@girikuncoro in https://groups.google.com/g/kubernetes-sig-docs look for an older email titled "Google Analytics: Pages" it will include a PDF of popular pages. On the PDF, in the top right corner, there's a link that says "Go To Report."

Clicking that link will take you to a page where you can request access and we will grant you read access after receiving the request.

Sorry this process is a bit strange and it's been awhile since I've tested it, so feel free to ping me if you run into any problems!

**Comment by seokho-son** [comment]
> @girikuncoro in https://groups.google.com/g/kubernetes-sig-docs look for an older email titled "Google Analytics: Pages" it will include a PDF of popular pages. On the PDF, in the top right corner, there's a link that says "Go To Report."
> 
> Clicking that link will take you to a page where you can request access and we will grant you read access after receiving the request.
> 
> Sorry this process is a bit strange and it's been awhile since I've tested it, so feel free to ping me if you run into any problems!

@jimangel I would like to get read permission to the Google analytics for K8s website. It would be useful for Korean l10n team !
By the way, I'v tried several times (clicking "Go To Report") to find a page to request permission. It turns out clicking "Go To Report" just makes an email request to administrators. So, I am sorry if you got multiple emails. :)

**Comment by jimangel** [comment]
@seokho-son @girikuncoro I don't know if that method is working. Feel free to send multiple requests 😄 but I do not see the requests on my end.

I will dig deeper into this as I believe view / read access to these analytics should be open to anyone who wants them.

Give me a few days to look into this and let me know @girikuncoro if you experience the same. Thanks!

**Comment by jimangel** [comment]
Discussion at 8/11/2020:
@sftim "this probably should be a working group"
@zacharysarah "Maybe a sub group would be better"

To do:

- [ ] boost localization sub group in channels / email / slack
- [ ] setup a slack channel
- [ ] add contributor ladder discussion into scope

**Comment by zacharysarah** [comment]
Slack channel requested: https://github.com/kubernetes/community/issues/5026

**Comment by irvifa** [comment]
[Slack channel](https://kubernetes.slack.com/archives/C0191RDKHU1)

**Comment by reylejano** [comment]
/remove-lifecycle stale
Removing lifecycle/rotten label in case there is more work or discussion needed on this issue. I'll bring it up to SIG Docs if this issue is ready to close.

**Comment by tahacodes** [comment]
hey @jimangel 
since I the time asked that is there anyone working on Persian/Farsi localization [here](https://kubernetes.slack.com/archives/C018HE5MA00/p1640439215003800
) no one answered and looks like this community is inactive
anyway, **I'll work on the Persian localization**, also it would be great to assign this one to me or any maintainer who wants to actively contribute with me.
