### ISSUE TITLE
Add reusable shortcode/standardized messaging re: Out of tree concerns & 3rd party content

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#22962]
Per our discussion in today's SIG Docs:

Sections of the site, like [How to implement the Kubernetes networking model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model) will _always_ have some degree of 3rd party content, due to the fact that a k8s developer must implement an external networking CNI. 

The majority of post-3rd party content KEP PR's we get that actually involve third party content are to pages like this one. A part of the reasons is that a change like the KEP requires _initial_ communication (which was well done) but also ongoing communication. 

This change proposes the following:
Create a reusable Note or similar shortcode for pages that fall under [this section of the KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-docs/20191020-doc-policies-for-third-party-content.md#implementation-detailsnotesconstraints).  The note should:

- Be translatable (use a `T` key)
- Warn people that they _must_ use a 3rd party plugin/software for this step
- Indicate that per the [CNCF website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) projects are listed alphabetically
- Indicate that additions to this list/page _must_ directly provide a solution for this step of an implementation (i.e. for the cluster networking page, projects listed must provide a networking solution – no 'nice to haves' that make networking easier or somehow nicer.)
- Link to the content guidelines for more info on acceptable additions to the page.

**Comment by celestehorgan** [comment]
Wording for review: This section contains links to third party projects which provide functionality required by Kubernetes. The Kubernetes project authors are not responsible for these projects. Projects are listed alphabetically, in accordance with [CNCF website guidelines]. To add a project to this list, read the <a href="/contribute/style/content-guide/#third-party-content">content guide</a> before submitting a change.

**Comment by jimangel** [comment]
Related: https://github.com/kubernetes/website/issues/22961

**Comment by zacharysarah** [comment]
@celestehorgan How about: 
> This section links to third party projects that provide functionality required by Kubernetes. The Kubernetes project authors aren't responsible for these projects. This page follows [CNCF website guidlines] by listing projects alphabetically. 
>
> To add a project to this list, read the [content guide](/docs/contribute/style/content-guide/) before submitting a change.

**Comment by celestehorgan** [comment]
@zacharysarah LGTM, I'll go ahead and implement. Thank you for the edit!

**Comment by kbhawkey** [comment]
Hello @celestehorgan , Some late feedback (sorry I missed the meeting):
- Since this is a "special" note, I think it warrants a different color on the left hand border.
Is there another shortcode besides note or warning that could be used to set off the text?
Could substitute the shortcode "Note" text with "Third party content"?
- The language in the third party content message is a bit obtuse.
- When this label is applied, can the reader assume that all content on the page falls under these guidelines?
- This sentence, "Kubernetes project authors are not responsible for these projects" seems repetitive. Third party implies an external source and outside of the project's domain.

**Comment by zacharysarah** [comment]
@kbhawkey 
> Since this is a "special" note, I think it warrants a different color on the left hand border.
Is there another shortcode besides note or warning that could be used to set off the text?
Could substitute the shortcode "Note" text with "Third party content"?

All good feedback. 👍 

> The language in the third party content message is a bit obtuse.

How would you phrase it differently?

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey
> 
> > Since this is a "special" note, I think it warrants a different color on the left hand border.
> > Is there another shortcode besides note or warning that could be used to set off the text?
> > Could substitute the shortcode "Note" text with "Third party content"?
> 
> All good feedback. 👍
> 
> > The language in the third party content message is a bit obtuse.
> 
> How would you phrase it differently?

Hi. I am not entirely sure. The text is okay, though, it may not be clear about what is "required for Kubernetes to function".
What do you want readers to do:
- determine if their project belongs in the section (read the content guide)
- read the content as third party content (Sig Docs is hosting the links but not responsible for the content on the page)?

[One idea:]
This section links to third party projects and follows [CNCF website guidelines] by listing projects alphabetically.

[Do you want to suggest adding content or not?]
If you are considering adding content in this section, read the [content guide](...) before submitting a change.

[Do you need a statement about content responsibility?]

**Comment by celestehorgan** [comment]
> Since this is a "special" note, I think it warrants a different color on the left hand border.
Is there another shortcode besides note or warning that could be used to set off the text?
Could substitute the shortcode "Note" text with "Third party content"?

I think this is a good suggestion. I'll update the PR.

> Hi. I am not entirely sure. The text is okay, though, it may not be clear about what is "required for Kubernetes to function".
What do you want readers to do:
>
>  *  determine if their project belongs in the section (read the content guide)
>  *  read the content as third party content (Sig Docs is hosting the links but not responsible for the content on the page)?
>
>[One idea:]
>This section links to third party projects and follows [CNCF website guidelines] by listing projects alphabetically.
>
>[Do you want to suggest adding content or not?]
>If you are considering adding content in this section, read the content guide before submitting a change.
>
>[Do you need a statement about content responsibility?]

Is this blocking for the PR? If we can't come up with a concrete alternative, I'd prefer to merge the PR, re-open this issue, and continue to work on the wording. Would that be okay, @kbhawkey?

**Comment by kbhawkey** [comment]
Sure @celestehorgan .
I think what you have is fine. As an aside, did you consider using the theme's `alert` shortcode (which
has a `title` parameter)? It may work as well as wrapping the "third party content" shortcode in a note/warning
shortcode. I think you can set the `color` attribute too.
`\website\themes\docsy\layouts\shortcodes\alert.html`

**Comment by sftim** [comment]
@celestehorgan I'm imagining a one-line shortcode that, when rendered, closely matches the styles of existing callouts. I'd rather _not_ use callouts from the Docsy theme because that's different from our existing callouts (something to handle in a separate issue, I feel).

Wording-wise I'm happy to see _something_ merged and leave room to iterate.

Would you be happy to implement that?

**Comment by kbhawkey** [comment]
> 
> 
> @celestehorgan I'm imagining a one-line shortcode that, when rendered, closely matches the styles of existing callouts. I'd rather _not_ use callouts from the Docsy theme because that's different from our existing callouts (something to handle in a separate issue, I feel).
> 
> Wording-wise I'm happy to see _something_ merged and leave room to iterate.

Hi. I agree, let's get this change moving forward with a single line shortcode with similar styling to the existing callouts.
The shortcode would use two template strings: one variable for the message title and another variable for the message body.
In the future, I could imagine a flexible interface or more generic shortcode that
accepts at least one argument: the name of the variable representing the message title.
