### ISSUE TITLE
Issue with /docs/api-reference/v1/definitions/

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/website#2299]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

The documentation on http probes does not specify whether the kubelet attempts to validate certificate paths if the liveness URL has scheme==https.  I have reason to believe from reading this code

https://github.com/kubernetes/kubernetes/blob/55bee3ad21f025b1416a4e1f10de753f484b66d3/pkg/probe/http/http.go#L34

that the kubelet does not try to validate the cert path.  But official documentation stating that would be helpful.

**Proposed Solution:**

Document if the kubelet skips cert path validation when probing an HTTPS liveness or readiness path.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
/close
No longer a issue.
