### ISSUE TITLE
Outdated files in dev-1.18-ko.10 branch

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#23005]
# This is a Bug Report
## Problem
Outdated files in the dev-1.18-ko.10 branch.

### 84 files to be modified 
1. [ ] content/en/docs/concepts/architecture/control-plane-node-communication.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/architecture/nodes.md 1 file changed, 2 insertions(+), 4 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/_index.md 1 file changed, 5 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/addons.md 1 file changed, 3 insertions(+), 8 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/cloud-providers.md 1 file changed, 7 insertions(+), 10 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/logging.md 1 file changed, 2 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/manage-deployment.md 1 file changed, 3 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/concepts/cluster-administration/networking.md 1 file changed, 15 insertions(+), 22 deletions(-)
1. [ ] content/en/docs/concepts/configuration/configmap.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/configuration/manage-resources-containers.md 1 file changed, 9 insertions(+), 14 deletions(-)
1. [ ] content/en/docs/concepts/configuration/overview.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/configuration/pod-priority-preemption.md 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/containers/container-environment.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/concepts/containers/container-lifecycle-hooks.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/containers/images.md 1 file changed, 1 insertion(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/extend-kubernetes/_index.md 1 file changed, 23 insertions(+), 30 deletions(-)
1. [ ] content/en/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md 1 file changed, 5 deletions(-)
1. [ ] content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md 1 file changed, 4 insertions(+), 4 deletions(-)
1. [ ] content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md 1 file changed, 1 insertion(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/extend-kubernetes/extend-cluster.md 1 file changed, 35 insertions(+), 39 deletions(-)
1. [ ] content/en/docs/concepts/extend-kubernetes/operator.md 1 file changed, 2 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/concepts/overview/kubernetes-api.md 1 file changed, 2 insertions(+), 13 deletions(-)
1. [ ] content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/overview/working-with-objects/labels.md 1 file changed, 13 insertions(+), 8 deletions(-)
1. [ ] content/en/docs/concepts/overview/working-with-objects/namespaces.md 1 file changed, 8 insertions(+), 12 deletions(-)
1. [ ] content/en/docs/concepts/overview/working-with-objects/object-management.md 1 file changed, 5 deletions(-)
1. [ ] content/en/docs/concepts/policy/limit-range.md 1 file changed, 2 insertions(+), 10 deletions(-)
1. [ ] content/en/docs/concepts/policy/pod-security-policy.md 1 file changed, 6 insertions(+), 12 deletions(-)
1. [ ] content/en/docs/concepts/policy/resource-quotas.md 1 file changed, 12 insertions(+), 13 deletions(-)
1. [ ] content/en/docs/concepts/scheduling-eviction/kube-scheduler.md 1 file changed, 1 insertion(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/services-networking/connect-applications-service.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/services-networking/dns-pod-service.md 1 file changed, 12 insertions(+), 4 deletions(-)
1. [ ] content/en/docs/concepts/services-networking/ingress-controllers.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/services-networking/ingress.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/services-networking/network-policies.md 1 file changed, 2 deletions(-)
1. [ ] content/en/docs/concepts/services-networking/service.md 1 file changed, 6 insertions(+), 8 deletions(-)
1. [ ] content/en/docs/concepts/storage/persistent-volumes.md 1 file changed, 5 insertions(+), 4 deletions(-)
1. [ ] content/en/docs/concepts/storage/storage-classes.md 1 file changed, 4 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/concepts/storage/volumes.md 1 file changed, 13 insertions(+), 15 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/daemonset.md 1 file changed, 6 insertions(+), 8 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/deployment.md 1 file changed, 5 insertions(+), 12 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/garbage-collection.md 1 file changed, 6 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/job.md 1 file changed, 3 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/replicationcontroller.md 1 file changed, 8 insertions(+), 11 deletions(-)
1. [ ] content/en/docs/concepts/workloads/controllers/statefulset.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/workloads/controllers/ttlafterfinished.md 1 file changed, 2 insertions(+), 10 deletions(-)
1. [ ] content/en/docs/concepts/workloads/pods/_index.md 1 file changed, 267 insertions(+), 1 deletion(-)
1. [ ] content/en/docs/concepts/workloads/pods/disruptions.md 1 file changed, 40 insertions(+), 41 deletions(-)
1. [ ] content/en/docs/concepts/workloads/pods/pod-lifecycle.md 1 file changed, 313 insertions(+), 277 deletions(-)
1. [ ] content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md 1 file changed, 3 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/concepts/workloads/pods/podpreset.md 1 file changed, 24 insertions(+), 27 deletions(-)
1. [ ] content/en/docs/contribute/_index.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/contribute/participate/_index.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/contribute/participate/pr-wranglers.md 1 file changed, 19 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/reference/glossary/pod.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/reference/using-api/api-overview.md 1 file changed, 1 insertion(+), 8 deletions(-)
1. [ ] content/en/docs/setup/best-practices/cluster-large.md 1 file changed, 12 insertions(+), 13 deletions(-)
1. [ ] content/en/docs/setup/best-practices/multiple-zones.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/setup/learning-environment/minikube.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/setup/production-environment/tools/kops.md 1 file changed, 2 insertions(+), 3 deletions(-)
1. [ ] content/en/docs/tasks/access-application-cluster/service-access-application-cluster.md 1 file changed, 6 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/change-pv-reclaim-policy.md 1 file changed, 6 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/extended-resource-node.md 1 file changed, 2 insertions(+), 2 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md 1 file changed, 6 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace.md 1 file changed, 5 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md 1 file changed, 6 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md 1 file changed, 5 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md 1 file changed, 6 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md 1 file changed, 5 insertions(+), 5 deletions(-)
1. [ ] content/en/docs/tasks/configure-pod-container/assign-memory-resource.md 1 file changed, 7 insertions(+), 7 deletions(-)
1. [ ] content/en/docs/tasks/configure-pod-container/quality-service-pod.md 1 file changed, 6 insertions(+), 6 deletions(-)
1. [ ] content/en/docs/tasks/configure-pod-container/static-pod.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/run-application/delete-stateful-set.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tasks/tools/_index.md 1 file changed, 35 insertions(+)
1. [ ] content/en/docs/tasks/tools/install-kubectl.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/hello-minikube.md 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html 1 file changed, 1 insertion(+), 1 deletion(-)
1. [ ] content/en/docs/tutorials/services/source-ip.md 1 file changed, 26 insertions(+), 34 deletions(-)
1. [ ] content/en/docs/tutorials/stateful-application/zookeeper.md 1 file changed, 60 insertions(+), 34 deletions(-)
1. [ ] content/en/docs/tutorials/stateless-application/expose-external-ip-address.md 1 file changed, 5 insertions(+), 5 deletions(-)

### 2 files to be deleted 
1. [ ] content/en/docs/concepts/workloads/pods/pod-overview.md
1. [ ] content/en/docs/concepts/workloads/pods/pod.md

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `dev-1.18-ko.10` branch.

For example:
```
# checkout `dev-1.18-ko.10`
...
# check what is updated in the upstream 
git diff dev-1.18-ko.9 dev-1.18-ko.10 -- content/en/docs/concepts/architecture/control-plane-node-communication.md
# apply changes to content/ko
vi content/ko/docs/concepts/architecture/control-plane-node-communication.md
...
# commit and push
...
# make PR to `dev-1.18-ko.10`
```

## Pages to Update
https://kubernetes.io/... Ko pages

/language ko

**Comment by seokho-son** [comment]
현행화 작업은 항상 분량이 많기 때문에 분업이 가능하면 좋겠다는 의견이 있었습니다. 
현행화 작업에 참여를 원하시는 분은 작업하실 범위를 코멘트로 공유해주시면 좋겠습니다.

**Comment by pjhwa** [comment]
아래 40개 파일 작업하겠습니다.

1.  content/en/docs/concepts/architecture/control-plane-node-communication.md 1 file changed, 1 insertion(+), 1 deletion(-)
2.  content/en/docs/concepts/architecture/nodes.md 1 file changed, 2 insertions(+), 4 deletions(-)
3.  content/en/docs/concepts/cluster-administration/_index.md 1 file changed, 5 insertions(+), 5 deletions(-)
4.  content/en/docs/concepts/cluster-administration/addons.md 1 file changed, 3 insertions(+), 8 deletions(-)
5.  content/en/docs/concepts/cluster-administration/cloud-providers.md 1 file changed, 7 insertions(+), 10 deletions(-)
6.  content/en/docs/concepts/cluster-administration/logging.md 1 file changed, 2 insertions(+), 5 deletions(-)
7.  content/en/docs/concepts/cluster-administration/manage-deployment.md 1 file changed, 3 insertions(+), 5 deletions(-)
8.  content/en/docs/concepts/cluster-administration/networking.md 1 file changed, 15 insertions(+), 22 deletions(-)
9.  content/en/docs/concepts/configuration/configmap.md 1 file changed, 1 insertion(+), 1 deletion(-)
10.  content/en/docs/concepts/configuration/manage-resources-containers.md 1 file changed, 9 insertions(+), 14 deletions(-)
11.  content/en/docs/concepts/configuration/overview.md 1 file changed, 1 insertion(+), 1 deletion(-)
12.  content/en/docs/concepts/configuration/pod-priority-preemption.md 1 file changed, 3 insertions(+), 3 deletions(-)
13.  content/en/docs/concepts/containers/container-environment.md 1 file changed, 2 insertions(+), 2 deletions(-)
14.  content/en/docs/concepts/containers/container-lifecycle-hooks.md 1 file changed, 1 insertion(+), 1 deletion(-)
15.  content/en/docs/concepts/containers/images.md 1 file changed, 1 insertion(+), 3 deletions(-)
16.  content/en/docs/concepts/extend-kubernetes/_index.md 1 file changed, 23 insertions(+), 30 deletions(-)
17.  content/en/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md 1 file changed, 5 deletions(-)
18.  content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md 1 file changed, 4 insertions(+), 4 deletions(-)
19.  content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md 1 file changed, 1 insertion(+), 3 deletions(-)
20.  content/en/docs/concepts/extend-kubernetes/extend-cluster.md 1 file changed, 35 insertions(+), 39 deletions(-)
21.  content/en/docs/concepts/extend-kubernetes/operator.md 1 file changed, 2 insertions(+), 5 deletions(-)
22.  content/en/docs/concepts/overview/kubernetes-api.md 1 file changed, 2 insertions(+), 13 deletions(-)
23.  content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md 1 file changed, 1 insertion(+), 1 deletion(-)
24.  content/en/docs/concepts/overview/working-with-objects/labels.md 1 file changed, 13 insertions(+), 8 deletions(-)
25.  content/en/docs/concepts/overview/working-with-objects/namespaces.md 1 file changed, 8 insertions(+), 12 deletions(-)
26.  content/en/docs/concepts/overview/working-with-objects/object-management.md 1 file changed, 5 deletions(-)
27.  content/en/docs/concepts/policy/limit-range.md 1 file changed, 2 insertions(+), 10 deletions(-)
28.  content/en/docs/concepts/policy/pod-security-policy.md 1 file changed, 6 insertions(+), 12 deletions(-)
29.  content/en/docs/concepts/policy/resource-quotas.md 1 file changed, 12 insertions(+), 13 deletions(-)
30.  content/en/docs/concepts/scheduling-eviction/kube-scheduler.md 1 file changed, 1 insertion(+), 3 deletions(-)
31.  content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md 1 file changed, 1 insertion(+), 1 deletion(-)
32.  content/en/docs/concepts/services-networking/connect-applications-service.md 1 file changed, 1 insertion(+), 1 deletion(-)
33.  content/en/docs/concepts/services-networking/dns-pod-service.md 1 file changed, 12 insertions(+), 4 deletions(-)
34.  content/en/docs/concepts/services-networking/ingress-controllers.md 1 file changed, 1 insertion(+), 1 deletion(-)
35.  content/en/docs/concepts/services-networking/ingress.md 1 file changed, 1 insertion(+), 1 deletion(-)
36.  content/en/docs/concepts/services-networking/network-policies.md 1 file changed, 2 deletions(-)
37.  content/en/docs/concepts/services-networking/service.md 1 file changed, 6 insertions(+), 8 deletions(-)
38.  content/en/docs/concepts/storage/persistent-volumes.md 1 file changed, 5 insertions(+), 4 deletions(-)
39.  content/en/docs/concepts/storage/storage-classes.md 1 file changed, 4 insertions(+), 6 deletions(-)
40.  content/en/docs/concepts/storage/volumes.md 1 file changed, 13 insertions(+), 15 deletions(-)

**Comment by pjhwa** [comment]
/assign

제가 나머지 파일들도 작업하겠습니다~
