### ISSUE TITLE
Unable to make and run website under WSL 

### ISSUE THREAD

**Issue by forvaidya** [kubernetes/website#23015]
**This is a Bug Report**

 make container-serve

Error: Unable to locate config file or config directory. Perhaps you need to create a new site.
       Run `hugo help new` for details.

Makefile:71: recipe for target 'container-serve' failed

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by forvaidya** [comment]
another question: is there a way to build it portably in windows. WSL is restrictive

**Comment by sftim** [comment]
/triage support

Did you run `make container-image` first @forvaidya ?

@forvaidya: on WSL, you might find that `make serve` works better. You'll need Hugo and NPM locally before that works.

**Comment by forvaidya** [comment]
> /triage support

I have done make container-image already. 

Is there a windows native build procedure

**Comment by forvaidya** [comment]
On wsl it did not work, I have adjusted values in netlify.toml and ran following 

hugo server --buildFuture 
and it worked http://localhost:1313/

I appreciate if container build is made available for Powershell

**Comment by sftim** [comment]
@forvaidya can you explain what changes to the README would make it clear how to run a local build within WSL?

**Comment by forvaidya** [comment]
I think for windows  **hugo command** is only viable way on windows, unless a rewrite makefile in ps1 script as make is not portable.  If I can write ps1 script as a replacememt I will send pull request for sure.

Can we add this note in README.

```
hugo server --buildFuture
and it worked http://localhost:1313/
```

**Comment by sftim** [comment]
@forvaidya If you'd be willing to document a local preview process that works on Windows, please feel free to submit a pull request.
