### ISSUE TITLE
modify layout of codenew shortcode

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#23020]
**This is a Feature Request**
The `codenew` shortcode uses an HTML table to contain the "copy" icon, filename text,
and code block. Since the Docsy theme addition, the codenew shortcode generates code blocks
that appear squashed on the page.

**What would you like to be added**
Investigate whether the `codenew` shortcode should keep the table element for laying out the code block with
updated table styling or create a new layout using HTML `div` elements and styling.

**Why is this needed**
 The copy-code-blocks should look like the other code blocks in the site.

**Comments**
Could test with page, https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/

**Comment by kbhawkey** [comment]
Temporarily assign myself.
/assign

**Comment by sftim** [comment]
/kind cleanup
/area web-development
/priority backlog

(I'd love to see this improved!)
