### ISSUE TITLE
issue with Task page scrolling horizontally when args code is too large

### ISSUE THREAD

**Issue by ibrahimjelliti** [kubernetes/website#23024]
**This is a Bug Report**
**Problem:**
the dependent-envars.yaml  file args is long by concatenating of all commands into a single command with **;** that cause the page to scroll horizontally.
![image](https://user-images.githubusercontent.com/9965888/89706365-c98e8280-d95c-11ea-994a-05c5bcc4c6ae.png)

**Proposed Solution:**
-  we can get true multi-line scripts using an heredoc to avoid concatenating all commands into a single command its also give better readability for script in the yaml file

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/#define-an-environment-dependent-variable-for-a-container

**Comment by Cweiping** [comment]
/language en
Thank you for your question, it seems to improve the problem. But I think there is not a root cause. Yaml display should not allow the text content to expand to the right, and the style should be adjusted to fix the size. 
cc  @sftim

**Comment by sftim** [comment]
@kbhawkey I imagine you'll have a good idea about the approach to take?

**Comment by ijelliti** [comment]
@sftim I think there is two options: we adjust the codenew layout style to fit the middle section or we switch the args commands concatenation to multi-line script.

**Comment by kbhawkey** [comment]
Related issue #23020

**Comment by kbhawkey** [comment]
I plan on closing this issue. If there is remaining work, feel free to reopen.
/close
