### ISSUE TITLE
Improve order of workload resources

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23030]
**This is an enhancement Request**

**What would you like to be added**
Change https://kubernetes.io/docs/concepts/workloads/controllers/ to list Deployment and ReplicaSet early (Deployment first), with ReplicationController at or near the end of the list.

It is also OK to replace this page with a hand-written overview that achieves the same effect.

**Why is this needed**
ReplicationController is deprecated.

**Comments**
You can make this change by editing the `weight` attribute in the [front matter](https://gohugo.io/content-management/front-matter/) of pages inside [`content/en/docs/concepts/workloads/controllers`](https://github.com/kubernetes/website/tree/master/content/en/docs/concepts/workloads/controllers).

/language en
/priority backlog
/good-first-issue
/kind cleanup

**Comment by saswatamcode** [comment]
Just the order of list needs to be changed to list Deployments and then ReplicaSet early and ReplicationController at the end in the [front matter](https://kubernetes.io/docs/concepts/workloads/controllers/), right?

**Comment by sftim** [comment]
@saswatamcode (and to anyone else) you can make the minimal change you described, or you can consider further tidying. Either approach is valid; if you like, there is a spectrum of thoroughness in how you deal with this.

**Comment by sftim** [comment]
Oh, I've fixed the link to _front matter_; it should be to https://gohugo.io/content-management/front-matter/

**Comment by Evalle** [comment]
Hey folks, I can take care of it if @saswatamcode OK with that.

**Comment by saswatamcode** [comment]
Sure you can go ahead!

**Comment by Evalle** [comment]
Thanks! 
/assign
