### ISSUE TITLE
Page mismatch between default current version and the correct version

### ISSUE THREAD

**Issue by Mais316** [kubernetes/website#23058]
As current version is 1.18 

so when I go to page https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

I dont see the Network pod add on options with taps like "Calico, Weave Net"

but when I go here, I see it

https://v1-18.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ 

So I am not sure if I can use link https://v1-18.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ in exam as link https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ doesnt provide the yaml files

**Comment by neolit123** [comment]
this was changed: https://github.com/kubernetes/website/issues/22961#issue-673047152
please use the 1.18 version in the exam.

/triage support
/sig cluster-lifecycle
/close
