### ISSUE TITLE
Issue with k8s.io/docs/concepts/containers/images/

### ISSUE THREAD

**Issue by masaeedu** [kubernetes/website#23055]
**This is a Bug Report**

**Problem:**

The docs at https://kubernetes.io/docs/concepts/containers/images/#multi-architecture-images-with-manifests read:

> As well as providing binary images, a container registry can also serve a [container image manifest](https://github.com/opencontainers/image-spec/blob/master/manifest.md). A manifest can reference image manifests for architecture-specific versions of an container.

AFAIU a manifest cannot reference other image manifests. Also, a manifest also refers to the content addresses of a fixed set of layers built for a particular platform, so it cannot be used to abstract over multiple architecture-specific builds.

**Proposed Solution:**

I suspect what is meant is an [image index](https://github.com/opencontainers/image-spec/blob/master/image-index.md), which can point to multiple concrete manifests (and does not refer to any fixed layers). Thus it can be used to indirect over e.g. builds of a software image for different platforms.

**Page to Update:**
 https://kubernetes.io/docs/concepts/containers/images

**Comment by sftim** [comment]
/kind bug
/language en
/priority backlog

Thanks for spotting this.
