### ISSUE TITLE
Translate docs/reference/setup-tools/kubeadm/* in Korean

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#23051]
**This is a Feature Request**

**What would you like to be added**

Translate docs/reference/setup-tools/kubeadm/* in Korean

**Why is this needed**
No translation with Translate docs/reference/setup-tools/kubeadm/* in Korean

**Comments**

Pages to update:
[ko] https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/
[en] https://kubernetes.io/docs/reference/setup-tools/kubeadm/
- [~~Overview of kubeadm~~](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/) (already [translated in Korean](https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/kubeadm/))
- [kubeadm init](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/)
- [kubeadm join](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/)
- [kubeadm upgrade](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/)
- [kubeadm config](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/)
- [kubeadm reset](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/)
- [kubeadm token](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-token/)
- [kubeadm version](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-version/)
- [kubeadm alpha](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-alpha/)
- [kubeadm init phase](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/)
- [kubeadm join phase](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join-phase/)
- [kubeadm reset phase](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset-phase/)
- [kubeadm upgrade phase](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase/)
- [Implementation details](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/)

/language ko

**Comment by seokho-son** [comment]
@jihoon-seo 혹시 해당 이슈에 대해서 작업 중이신가요? 아니라면, priority/backlog 레이블을 달면 좋을 것 같습니다. 
다른 방법은 해당 이슈에 대해서 다른 컨트리뷰터의 help를 요청하는 방법이 있겠습니다.. ^^

**Comment by jihoon-seo** [comment]
@seokho-son 
작업 중이 아닙니다.
해당 레이블을 달겠습니다.

/priority backlog
