### ISSUE TITLE
Modify text in Korean top page for KubeCon announcement

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#23050]
**This is a Bug Report**

**Problem:**

Issue #23009: "Modify text in top page for KubeCon announcement"

> KubeCon NA 2020 is now virtual
> 
> ![image](https://user-images.githubusercontent.com/20236173/89609429-c63ebc80-d8b2-11ea-9620-d798c4e06090.png)

**Proposed Solution:**

In `content/ko/_index.html`

As-is:
```HTML
        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccnceu20" button id="desktopKCButton">Attend KubeCon in Amsterdam on August 13-16, 2020</a>
        <br>
        <br>
        <br>
        <br>
        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccnceu20" button id="desktopKCButton">Attend KubeCon EU virtually on August 17-20, 2020</a>
```

To-be: (Make the same with [content/en/_index.html](https://github.com/kubernetes/website/blob/master/content/en/_index.html))
```HTML
        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccnceu20" button id="desktopKCButton">Attend KubeCon EU virtually on August 17-20, 2020</a>
        <br>
        <br>
        <br>
        <br>
        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna20" button id="desktopKCButton">Attend KubeCon NA virtually on November 17-20, 2020</a>
```

**Page to Update:**
https://kubernetes.io/ko/

**Comment by seokho-son** [comment]
@jihoon-seo Could you help us fix this issue ? 
If you can, you can self assign this issue and open a PR to master branch. 
(FYI, Korean l10n team guide contributors to use Korean working branch, such as dev-1.18-ko.10, for general localization contributions. But, we accept bug fix PR to master branch to sync with EN changes.)

**Comment by jihoon-seo** [comment]
@seokho-son 
Sure! I will handle it.
