### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by Mais316** [kubernetes/website#23059]
**This is a Bug Report**

**Problem:**

can not see section under "Installing a Pod network add-on" that has tabs of "Calico, cilium,conitv,kube-router" so I dont know the download links for 
calico.yaml "kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml" 

**Proposed Solution:**
please add missing section back 

correct contents are in https://v1-18.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Page to Update:**
https://kubernetes.io/...
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

latest 1.18

Issue is https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ is the one used in exam and not all people will find the correct missing info

**Comment by neolit123** [comment]
this was changed. see https://github.com/kubernetes/website/issues/22961#issue-673047152

/triage support
/sig cluster-lifecycle
/close
