### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/

### ISSUE THREAD

**Issue by rizekmWWT** [kubernetes/website#23065]
**This is a Bug Report**
setting Add --allow-privileged=true or --allow-privileged to the following 2 files
/var/snap/microk8s/current/args/kubelet
/var/snap/microk8s/current/args/kube-apiserver

Causes the following error:
Error from server: Get "https://appd-k8s-clusagent-1:10250/containerLogs/appdynamics/appdynamics-operator-5cb5b8b7d8-zkkwq/appdynamics-operator": dial tcp 192.168.2.113:10250: connect: connection refused.

If the above is NOT set --allow-privileged=true the Operator is not able to deploy Machine agent.

Thanks,
Mike

**Comment by sftim** [comment]
/triage support

@rizekmWWT it sounds like you're looking for advice on Kubernetes. This list of issues covers defects in the documentation and suggestions for improvement.

https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/ has some advice on where to go for troubleshooting (if _that_ page isn't helpful, please do feel free to log an issue about improving it).
