### ISSUE TITLE
Legend wrong on a diagram

### ISSUE THREAD

**Issue by pushkarv** [kubernetes/website#23082]
**This is a Bug Report**

**Problem:**
The following page has a purple cube labeled as a Pod, but should be a containerized app when remaining consistent with the website diagrams.

**Proposed Solution:**
Change diagram to label purpose cube as a "Containerized app".

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

![image](https://user-images.githubusercontent.com/7516546/89957133-ac7bdd00-dc04-11ea-8bc0-51753260e26f.png)

**Comment by shuuji3** [comment]
I'm going to fix this legend.
/remove-lifecycle stale
/assign

**Comment by sftim** [comment]
I think this is fixed.

**Comment by sftim** [comment]
@pushkarv I edited the description of this issue. The change was to record what I think is the right URL of the page you wanted fixed.

It all looks OK now.

/close
