### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by yakirch** [kubernetes/website#23095]
**This is a Bug Report**

**Problem:**
it seems that there is wrong  indentation example-ingress.yaml 

**Proposed Solution:**
change to:
  - path: /
    backend:
      serviceName: web
      servicePort: 8080

instead of:

  - path: /
backend:
  serviceName: web
  servicePort: 8080

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

Additional Information:
This is the error thrown:
$ kubectl apply -f example-ingress.yaml
error: error validating "example-ingress.yaml": error validating data: [ValidationError(Ingress.spec.rules[0]): unknown field "backend" in io.k8s.api.networking.v1beta1.IngressRule, ValidationError(Ingress.spec.rules[0].http.paths[0]): missing required field "backend" in io.k8s.api.networking.v1beta1.HTTPIngressPath]; if you choose to ignorethese errors, turn validation off with --validate=false
$

**Comment by Cweiping** [comment]
Thank you for your submission and have tried to fix it.

/kind bug
/language en
/assign
