### ISSUE TITLE
Document task “Update a ConfigMap”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23101]
**This is a Feature Request**

**What would you like to be added**
- Explain how to update the configuration of (a set of) Pods that use a ConfigMap
- Detail what to do if you want to affect the behavior of a workload that is already deployed and running
- Tell the reader how to make this work if they are using immutable ConfigMaps

**Why is this needed**
If you search on a typical web search engine for “how do I update a configmap” you don't find particularly relevant results. You should.

**Comments**
This could be part of a general “cheat sheet” type page, it could be a page on its own, or it could be part of a grouped set of tasks. All those approaches are valid.

This could be (almost) duplicated for a task about updating a Secret.

/kind feature
/language en

**Comment by sftim** [comment]
Also see  #23732

**Comment by sftim** [comment]
Actually, this is important.
/remove-lifecycle rotten
/reopen

**Comment by sftim** [comment]
/remove-lifecycle rotten
/lifecycle frozen

It's a common thing to want to do.

**Comment by steve-hardman** [comment]
I want to have a go at this fullfilling this feature request.
/assign

**Comment by steve-hardman** [comment]
Unable to get time to work on this. Unassigning myself for others to pick it up.

/unassign

**Comment by adityasamant25** [comment]
/assign

I will work on this.

**Comment by adityasamant25** [comment]
My idea is to create two new tutorial pages under https://kubernetes.io/docs/tutorials/configuration/ with a step-by-step explanation of how to update configmaps and secrets.
Then the new pages can be linked as footnotes in the What's next section of the other configmap and secret documentation.

**Comment by sftim** [comment]
> My idea is to create two new tutorial pages under https://kubernetes.io/docs/tutorials/configuration/ with a step-by-step explanation of how to update configmaps and secrets. Then the new pages can be linked as footnotes in the What's next section of the other configmap and secret documentation.

Yes, and: we can explain that the outcome you want to achieve is to change the configuration for some running application.
Some more context: the application is still available to its end users, and all its replicas are using the revised configuration.
