### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by josephdubeau** [kubernetes/website#23108]
**This is a Bug Report**

**Problem:**
It doesn't create the vm in hyperV.  I tried many times, minikube start, but it never finishes. Even if manually create both the vm and set up an external network.  It never finishes. 
**Proposed Solution:**
test it before offering to the public.
**Page to Update:**
https://kubernetes.io/...

**Comment by RA489** [comment]
@josephdubeau Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!
