### ISSUE TITLE
Sample yaml doesn't work k8s.io/docs/tasks/configure-pod-container/extended-resource/

### ISSUE THREAD

**Issue by OleksandrGavryliukTR** [kubernetes/website#23122]
**Problem:**
Using the following tutorial:
https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/
Run
`kubectl apply -f https://k8s.io/examples/pods/resource/extended-resource-pod.yaml`
The pod does not start due to:
`Insufficient example.com/dongle`

**Proposed Solution:**
I don't know

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/

Kubectl Version: 1.18.5
Minikube Version: 1.11.0

OS:
Ubuntu 18.04

**Comment by Cweiping** [comment]
Did you complete the precondition?
https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/

**Comment by OleksandrGavryliukTR** [comment]
> Did you complete the precondition?
> https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/

No

**Comment by Cweiping** [comment]
If there is no update, I will close it.
/close
