### ISSUE TITLE
doc page on metrics and debugging of conntrack, ipv6, ipv4

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#23144]
**This is a Feature Request**

**What would you like to be added**

We need a doc page on "Debugging networking using the Kubernetes end-to-end tests", for what  metrics to use to monitor and understand and ipvv6/ipv4/conttrack/iptables/kube-proxy datapath  debugging for different installation modes (dualstack, ipv6 only, ipv4 only). 

Seems like it also should give examples of how iptables rules for CNIs are written, and how to know if there are too many rules , or wether potential service bottlenecks are being hit (i.e. how to use ginkgo filters to test iperf, node polling and so on, i.e. the tests being updated in  https://github.com/kubernetes/kubernetes/issues/94005 ) leveraging things like   . 

**Why is this needed**
Right now about 3 or 4 issues a week can be easily self solved by going through the e2e tests in a diagnostic fashion, one step at a time.  PRobably if you add a few metrics heuristics to that, then you could solve even more issues, this can be used as a triage workflow for sig-network issues that will make it very easy for folks to quickly get to the bottom of problems.  it also might inspire some more test improvmenets.

**Comments**

**Comment by sftim** [comment]
Maybe also /sig usability

**Comment by jayunit100** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ <-- this one seems like its a good start.

Maybe go over it, and lets add new topics to it, including how to 
- use e2e test filter `intra-pod` with something like sonobuoy to quickly diagnose failures at a high level
- maybe also worth putting a high level series of `steps` at the top of the doc.  right now I think it might be a little tough for people to know "where" to start in the doc, as its got a lot of great info but is kinda long.
