### ISSUE TITLE
Issue with k8s.io/docs/setup/release/version-skew-policy/

### ISSUE THREAD

**Issue by lgypro** [kubernetes/website#23152]
**This is a Bug Report**

**Problem:**
The example used to verify the relationship between the version of kube-proxy and kube-apiserver is problematic
**Proposed Solution:**
The version of kube-proxy must be less than or euqual to the version of kube-apiserver, so if the version of kube-proxy is 1.18, the version of kube-apiserver can be 1.18, 1.19 and 1.20.
The setence should be "kube-apiserver version must be between 1.18 and 1.20, inclusive".
**Page to Update:**
https://kubernetes.io/docs/setup/release/version-skew-policy/#kube-proxy

/kind bug
/language en

**Comment by neolit123** [comment]
thanks for finding this problem.
PRs welcome!

/help
/good-first-issue
/sig docs architecture
/priority important-longterm
