### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by Sikiryl** [kubernetes/website#23156]
**This is a Bug Report**

**Problem:**
I cannot find how to install Pod Network Plugins such as Kube-Router, Calico, Weave-Net and so on 
in the past, I used that section for install weave-net 
```$ kubectl apply -f "https://cloud.weave.works/k8s/net?```
now, they have gone.

**Proposed Solution:**
Bring them back in #pod-network section

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
hi, the removal is intentional, see:
https://github.com/kubernetes/website/pull/22600
https://github.com/kubernetes/website/pull/22600#issuecomment-673288168
https://github.com/kubernetes/website/issues/22961

/triage support
/close
/sig cluster-lifecycle
