### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by notras** [kubernetes/website#23160]
**This is a Bug Report**

<img width="743" alt="previousadons" src="https://user-images.githubusercontent.com/43639563/90313238-9b3c1480-df13-11ea-925a-4278528c9ce3.png">
![actualCNI](https://user-images.githubusercontent.com/43639563/90313242-9ecf9b80-df13-11ea-9b1f-897b6bb8d10b.png)
Problem
Links for for deployment CNI plugins have been disappear from documentation:

**Proposed Solution:**
revert previous version with add-on's tabs which provide initial guidance for installation from one place

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

**Comment by neolit123** [comment]
hi, the removal is intentional, see:
#22600
#22600 (comment)
#22961

/triage support
/close
/sig cluster-lifecycle
