### ISSUE TITLE
Tutorials overview links to outdated CI/CD Pipeline pages

### ISSUE THREAD

**Issue by mpechner** [kubernetes/website#23167]
**This is a Bug Report**

CI/CD Pipeline utorials  horribly out of date.  Depends on kubernetes 1.6

**Proposed Solution:**
I wish I had the time to work on this.  Remove it or update it.

**Page to Update:**
https://kubernetes.io/...

https://kubernetes.io/docs/tutorials/
Links to out of date tutirial: CI/CD Pipeline

**Comment by sftim** [comment]
/kind cleanup
/priority important-longterm
/language en
/help

I recommend removing the https://kubernetes.io/docs/tutorials/#ci-cd-pipeline section entirely, it _is_ really out of date; also, even though the links are to external documentation the reference to Jenkins isn't really in the spirit of the [third party content](https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content) policy.

**Comment by sftim** [comment]
/retitle Tutorials overview links to outdated CI/CD Pipeline pages
