### ISSUE TITLE
Issue with k8s.io/fr/docs/setup/custom-cloud/kops/

### ISSUE THREAD

**Issue by jacques414** [kubernetes/website#23194]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
Y-a-t'il un problème là (https://k8s.io/fr/docs/setup/custom-cloud/kops/)?

S'il y a un problème et vous l'expliquez, on peut trier (faire _triage_ à) cet issue; ensuite, on peut essayer de le corriger.

/lang fr
