### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by PmcFizz** [kubernetes/website#23204]
not  find  image  k8s.gcr.io/echoserver:1.4

**Comment by sftim** [comment]
I checked if image `k8s.gcr.io/echoserver:1.4` is available.

```
$ podman image pull k8s.gcr.io/echoserver:1.4
Trying to pull k8s.gcr.io/echoserver:1.4...
Getting image source signatures
Copying blob a3ed95caeb02 done  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob d3c51dabc842 done  
Copying blob cd23f57692f8 done  
Copying blob dcd34d50d5ee done  
Copying blob b4241160ce0e done  
Copying blob 412c0feed608 done  
Copying blob 6d9e6e7d968b done  
Copying blob 7abee76f69c0 done  
Writing manifest to image destination
Storing signatures
a90209bb39e3d7b5fc9daf60c17044ea969aaca0333d672d8c7a34c7446e7ff7
```

@PmcFizz I think the page is correct, but maybe something about the way your cluster is set up stops you being able to pull images. Does that sound plausible?

**Comment by PmcFizz** [comment]
Hi  thank you repley my issue。 

I use docker pull `k8s.gcr.io/echoserver:1.4 `
will appear
```
docker pull k8s.gcr.io/echoserver:1.4

Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
![image](https://user-images.githubusercontent.com/13403284/90465385-d9b71680-e141-11ea-9adf-4d50c14e8e3c.png)

and I don‘t find this image on `hub.docker.com`

**Comment by sftim** [comment]
@PmcFizz are you in a country with state-level censorship, or connecting from behind a filtering security appliance? That might explain the symptoms. I think the documentation page is accurate.

/triage support
