### ISSUE TITLE
Creation of Resources tab to feature books

### ISSUE THREAD

**Issue by packtpartner** [kubernetes/website#2321]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No Resources section 

**Proposed Solution:**
Creation of a Resources tab under Documentation to feature books

**Page to Update:**
http://kubernetes.io/docs/

Packt has published a new book, [Kubernetes Cookbook](https://www.packtpub.com/virtualization-and-cloud/kubernetes-cookbook). I think it would be a good learning resource.

**Comment by jaredbhatti** [comment]
I actually think that "Community" would be a better place for this. I'm open to discussion, and I think links to purchase K8s books should be listed on the site somewhere, but I don't think creating a new tab under docs (of which there are too many already) is the right solution.

**Comment by packtpartner** [comment]
@jaredbhatti could you direct me to the right page to feature the book?

**Comment by packtpartner** [comment]
Hi @jaredbhatti , we have 2 more books published on Kubernetes. Can you direct me to the right place where these books can be featured? 
They would be a good learning resource for all those interested in learning Kubernetes
