### ISSUE TITLE
Revise full link target for kube-apiserver glossary term

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23240]
**This is a clean-up request**

**Problem:**
Pages such as [The Kubernetes API](https://kubernetes.io/docs/concepts/overview/kubernetes-api/) use the [glossary shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) for the term “_API Server_”. At the moment that shortcode hyperlinks to https://kubernetes.io/docs/reference/generated/kube-apiserver/ which then redirects to https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

This is reference documentation and quite a lot to take in, especially for someone who is new to Kubernetes. I recommend updating the glossary term for “API Server” to hyperlink to https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver

**Proposed Solution:**
Edit [`content/en/docs/reference/glossary/kube-apiserver.md`](https://github.com/kubernetes/website/blame/master/content/en/docs/reference/glossary/kube-apiserver.md) to change the `full_link` in the [front matter](/docs/concepts/overview/components/#kube-apiserver) to `/docs/concepts/overview/components/#kube-apiserver`.

**Additional Information:**
/kind cleanup
/language en
/priority backlog
/sig api-machinery
/good-first-issue

**Notes:**
We try to [limit pull requests to one language](https://kubernetes.io/docs/contribute/new-content/overview/#languages-per-pr). If you make this change to the English localization, feel free to suggest the equivalent change in other languages; it's a mechanical / repetitive update (a chore), but it also lets each localization team pick up approval tasks on their own cadence and using their own workflow. See [Contribute to Kubernetes docs](https://kubernetes.io/docs/contribute/) for general guidance.

**Comment by roshnaeem** [comment]
Hey @sftim , I have tried to work on this issue and opened a pull request. Kindly review it and suggest the necessary changes. 
https://github.com/kubernetes/website/pull/23255
