### ISSUE TITLE
ja: Translate docs/concepts/configuration/manage-resources-containers.md into Japanese

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23248]
**This is a Feature Request**

**What would you like to be added**
Translate docs/concepts/configuration/manage-resources-containers.md into Japanese.
**Why is this needed**
content/ja/docs/concepts/configuration/manage-resources-containers.md is not translated into Japanese.

**Comments**
/language ja
/good-first-issue

File to create
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/configuration/manage-resources-containers.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/configuration/manage-resources-containers.md

diff between translated and v1.18
https://gist.github.com/d42baaeda384ba5b91c1fd8c63c99524

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by translucens** [comment]
I found this document is already translated at the [master branch](https://github.com/kubernetes/website/blob/master/content/ja/docs/concepts/configuration/manage-resources-containers.md) and we can close this issue.
