### ISSUE TITLE
ja: Make docs/concepts/configuration/secret.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23245]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/configuration/secret.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/configuration/secret.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/configuration/secret.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/configuration/secret.md

diff between translated and v1.18
https://gist.github.com/257d74e8eb84bfcb169bba327be48472

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by translucens** [comment]
The current Japanese version #22662 is translated from https://github.com/kubernetes/website/blob/0ccefcd/content/en/docs/concepts/configuration/secret.md, and there is no difference between v.1.18 original text (https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/configuration/secret.md).
So we can close this issue without any updating document.

**Comment by kakts** [comment]
@translucens Thank you for reporting. As you mentioned,  this had been already translated. So I close this issue.
