### ISSUE TITLE
Highlight that some clusters run Web UI in a namespace other than kubernetes-dashboard

### ISSUE THREAD

**Issue by sorenbronsted** [kubernetes/website#23276]
**This is a Bug Report**

The url is wrong : http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

**Proposed Solution:**
It should be: http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by sftim** [comment]
I checked, and saw that https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml deploys into the namespace `kubernetes-dashboard`.

I think the existing documentation is correct @sorenbronsted.

Would it help to add a note that your setup might be different from what's recommended?
/triage needs-information

**Comment by sorenbronsted** [comment]
It is this page https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui which shows a wrong url. I just used the 'Create issue' on this page.

**Comment by sftim** [comment]
I still think the existing documentation is correct @sorenbronsted. Do you think the difference might be down to differences between the Kubernetes cluster you're using and the set up mentioned on that web page?


/remove-triage needs-information

**Comment by sorenbronsted** [comment]
Yes I think so. I am using microk8s. I was not aware of, that the implementations may vary.

**Comment by sftim** [comment]
There's room to clarify on the page that your dashboard deployment might not match the one this task recommends.

/language en
/priority backlog
/retitle Highlight that some clusters run Web UI in a namespace other than kubernetes-dashboard

**Comment by sftim** [comment]
I recommend adding a [note callout](https://kubernetes.io/docs/contribute/style/style-guide/#note) with the explanatory text in.
/help
