### ISSUE TITLE
Localize “Learn Kubernetes Basics” to Tiếng Việt

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23281]
**This is a Bug Report**

**Problem:**
The front page of the website has a button, “Learn Kubernetes Basics”. The Vietnamese localization is missing that button.

**Proposed Solution:**
Add the button / add the localized text that makes the button appear.

**Page to Update:**
https://kubernetes.io/vi/

/priority backlog
/language vi
/kind bug

**Comment by truongnh1992** [comment]
Thank @sftim I've just created a PR #24970 to fix this issue.

**Comment by truongnh1992** [comment]
The PR #24970 has been merged, so I close this issuse.
