### ISSUE TITLE
ja: Make docs/tutorials/configuration/configure-redis-using-configmap.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23309]
**This is a Feature Request**

**What would you like to be added**
Update docs/tutorials/configuration/configure-redis-using-configmap.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/tutorials/configuration/configure-redis-using-configmap.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/tutorials/configuration/configure-redis-using-configmap.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/tutorials/configuration/configure-redis-using-configmap.md

diff between translated and v1.18
https://gist.github.com/c278b1e33530ba4e98f9296881d538e2

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by shuzokato** [comment]
@kakts I think this issue is already merged.

**Comment by kakts** [comment]
@shuzokato Thank you for reporting. Let me check it.

**Comment by kakts** [comment]
@shuzokato As you mentioned, this issue is already merged.
So I close this issue.
Thank you for reporting.
