### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by marektoman** [kubernetes/website#23307]
**This is a Bug Report**

**Problem:**
The guide has misinformation because Docker is installed by snap these days.

**Proposed Solution:**
Either change `cat ~/.docker/config.json` to `cat ~/snap/docker/?/.docker/config.json` or even better, describe correctly all the variants.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by Kartik494** [comment]
Hi @marektoman is this mandatory behaviour for installing docker we are using snap or is just a standard procedure we are following for installing using snap, if possible can you provide link where i can take a look?
