### ISSUE TITLE
ja: Make docs/tutorials/stateful-application/basic-stateful-set.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23318]
**This is a Feature Request**

**What would you like to be added**
Update docs/tutorials/stateful-application/basic-stateful-set.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/tutorials/stateful-application/basic-stateful-set.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/tutorials/stateful-application/basic-stateful-set.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/tutorials/stateful-application/basic-stateful-set.md

diff between translated and v1.18
https://gist.github.com/edbe880dcde7f96b9207ba72e97b0074

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by arisgi** [comment]
@kakts 
https://github.com/kubernetes/website/pull/22329 で既にv1.18の翻訳をされていたようなので、このissueはクローズして大丈夫そうです。

**Comment by kakts** [comment]
@arisgi  ご連絡ありがとうございます！
たしかに、対応済みでしたのでこちらcloseいたします。

/close
