### ISSUE TITLE
ja: Make docs/tutorials/stateless-application/expose-external-ip-address.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23321]
**This is a Feature Request**

**What would you like to be added**
Update docs/tutorials/stateless-application/expose-external-ip-address.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/tutorials/stateless-application/expose-external-ip-address.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/tutorials/stateless-application/expose-external-ip-address.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/tutorials/stateless-application/expose-external-ip-address.md

diff between translated and v1.18
https://gist.github.com/734f5c99caf5623ae524f93e3a73dda9

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by yu-kasuya** [comment]
あれcloseできないのか
@inductor @kakts mergeしていただいたので、クローズお願いします
