### ISSUE TITLE
ja: Translate docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md into Japanese

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23322]
**This is a Feature Request**

**What would you like to be added**
Update docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md

diff between translated and v1.18
https://gist.github.com/feb886c24918f9c4223d26c2ca84b2e3

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by yu-kasuya** [comment]
ja/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.mdは1.18-ja.1には含まれていないようでした。

**Comment by kakts** [comment]
https://github.com/kubernetes/website/issues/23322#issuecomment-697116849
こちらの件確認いたします

**Comment by kakts** [comment]
https://github.com/kubernetes/website/issues/23322#issuecomment-697116849
すいませんこちらの件確認遅れました。
issueにしますね

**Comment by kakts** [comment]
@yu-kasuya 

すいません返信遅れました。
こちらの件ですが、既にmasterブランチに日本語訳とりこまれておりましたので、クローズします。
https://github.com/kubernetes/website/blob/0558f112375173b37b552ce09180fefd12fc079a/content/ja/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md

こちらの差分も反映されておりました
>diff between translated and v1.18
>https://gist.github.com/feb886c24918f9c4223d26c2ca84b2e3
