### ISSUE TITLE
ja: Make docs/reference/kubectl/overview.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23336]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/kubectl/overview.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/kubectl/overview.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/reference/kubectl/overview.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/reference/kubectl/overview.md

diff between translated and v1.18
https://gist.github.com/3978efc47a0337bd1941c546c554e18a

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
@takaf04 こちらいかがですかー（たまーにやってるIssueの整理なので、特に急がせているとかではありません。）

**Comment by takaf04** [comment]
すみません。
最近時間が取れなくて日数がかかっておりますが、今確認中なので、早ければ今日中に出しますね。
