### ISSUE TITLE
ja: Make docs/reference/glossary/node.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23341]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/glossary/node.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/glossary/node.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/reference/glossary/node.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/reference/glossary/node.md

diff between translated and v1.18
https://gist.github.com/88dbdf343643c76f80e5c4cb9aa2f5be

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
/close

@kakts これも
