### ISSUE TITLE
ja: Make docs/reference/glossary/configmap.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23344]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/glossary/configmap.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/glossary/configmap.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/reference/glossary/configmap.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/reference/glossary/configmap.md

diff between translated and v1.18
https://gist.github.com/fd3ad5bfc035f20d1e75321d36cd215d

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by yu-kasuya** [comment]
@kakts 対応済みのように見られます。

**Comment by kakts** [comment]
@yu-kasuya 
ご確認ありがとうございます。　こちら確認したところ確かに対応済みでした。
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/reference/glossary/configmap.md

こちらcloseいたします
