### ISSUE TITLE
ja: Make docs/contribute/localization.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23348]
**This is a Feature Request**

**What would you like to be added**
Update docs/contribute/localization.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/contribute/localization.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/contribute/localization.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/contribute/localization.md

diff between translated and v1.18
https://gist.github.com/61c62a50d0f7cfd4b2cac0f03b78dcec

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
@tkms0106 すみません、こちら対応不要なIssueです。（日本語と英語で内容が全く違うので
