### ISSUE TITLE
Update docs/tasks/tools/install-minikube

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#23354]
**This is a Feature Request**

[Install Minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/) doesn't follow the latest information where you no longer need a hypervisor in order to use the minikube cluster as the default driver is Docker now.

Ref. https://minikube.sigs.k8s.io/docs/drivers/

**What would you like to be added**

Update the doc

**Why is this needed**

It doesn't follow the latest information

**Comments**
/lang en
/good-first-issue

**Comment by rbrishabh** [comment]
Okay, got it! Will make a PR soon.
Thanks!

**Comment by sftim** [comment]
/priority important-longterm
/kind bug
/language en

However, as the work is not _clearly_ defined:
/remove-good-first-issue

**Comment by sftim** [comment]
I'd replace _Install a hypervisor_ with another section _Ensure you have what you need_ (or similar title).

**Comment by celestehorgan** [comment]
@rbrishabh doesn't appear to have updated this, and I need a good first issue to train up a new member of CNCF docs/dev advocacy staff, so I'm going to take this one 👍 

/assign @hackabletype 

(nb. Nate: **hold**. Do not action on this until we meet later this afternoon.)

**Comment by rbrishabh** [comment]
Sorry! I got busy with other work! Please feel free to work on this, thanks!

**Comment by hackabletype** [comment]
Hi @inductor, based on [another conversation](https://github.com/issues?page=2&q=is%3Aopen+is%3Aissue+author%3Atstromberg+archived%3Afalse+minikube), we may solve this issue by removing the minikube installation as dual sourced content, and replacing this page with a link to the [minikube installer documentation](https://minikube.sigs.k8s.io/docs/).

@tstromberg we are thinking of removing this page and replacing it with a link to [minikube installer documentation](https://minikube.sigs.k8s.io/docs/). Do you think this is appropriate y/n?

**Comment by celestehorgan** [comment]
@hackabletype 

As a part of this change, it might be worth making the links to Kind and Minikube a bit more visual/see-able. For example, using a button like here: https://kubernetes.io/docs/home/#understand-the-basics

**Comment by nate-double-u** [comment]
Karen B shared this PR in the Sig-Docs weekly meeting: https://github.com/kubernetes/website/pull/20717. It looks like it does the page trimming that we're looking at doing in this issue.

**Comment by sftim** [comment]
Should we also amend /remove https://k8s.io/docs/setup/learning-environment/minikube/ and https://k8s.io/docs/setup/learning-environment/kind/ ?

**Comment by nate-double-u** [comment]
> Should we also amend / remove https://k8s.io/docs/setup/learning-environment/minikube/ and https://k8s.io/docs/setup/learning-environment/kind/ ?

I think wherever we find content brought in from another site verbatim, we should probably just link out to those sites.

In the case of those two pages, I think that it's parent page, https://kubernetes.io/docs/setup/learning-environment/, can probably do more of the work and we should probably remove them.

If folks agree, should we do this work on this issue (and PR https://github.com/kubernetes/website/pull/24416), or create a new one?

**Comment by nate-double-u** [comment]
> Should we also amend / remove https://k8s.io/docs/setup/learning-environment/minikube/ and https://k8s.io/docs/setup/learning-environment/kind/ ?

Revising my previous comment, now removed: 
- I think that the https://k8s.io/docs/setup/learning-environment/kind/ page isn't doing very much, and can probably be combined with its parent page. Or, we can expand it to match the content style of the minikube page.
- The https://k8s.io/docs/setup/learning-environment/minikube/ page looks to be in good shape (I went through it recently as a part of an on-boarding process). I'm not seeing much duplication from the main minikube site (please correct me if I'm wrong on that). What amendments would you suggest @sftim?

**Comment by sftim** [comment]
The page at https://kubernetes.io/docs/tasks/tools/install-minikube/ is gone.
/close
