### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by dheeraj-dev1** [kubernetes/website#23360]
how to slove this error

error: error validating "one.yaml": error validating data: apiVersion not set; if you choose to ignore these errurn validation off with --validate=false

**Comment by neolit123** [comment]
hi, please try the support channels for general questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/triage support
/sig cluster-lifecycle
