### ISSUE TITLE
Test: Add tide merge blocker label

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/website#23379]
Test: Add tide merge blocker label

**Comment by savitharaghunathan** [comment]
tide/merge-blocker

**Comment by sftim** [comment]
@savitharaghunathan is this still a test? Do you want the label applied?

(if you want the label kept, consider retitling the issue)

**Comment by savitharaghunathan** [comment]
Hi @sftim, I am going to close this issue and create a new one for website freeze in a couple of hours. Closing should remove the label?
