### ISSUE TITLE
Specify the date of releases

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [kubernetes/website#23394]
Would like to know the date of the release (1.18).
 k8s.io/docs/setup/release/notes/

**Comment by sftim** [comment]
/remove-lifecycle rotten
It's still important to do this.

**Comment by jai** [comment]
@sftim just the date for the main release, or for the RCs as well?

Did you have an idea about where - do I just add it as text under the H1 version number, any special formatting needed? Or just propose something?

**Comment by jai** [comment]
Ah I just saw this PR: https://github.com/kubernetes/website/pull/22736 - would that PR cover this change, if so I'll unassign myself from this if there are people working on the PR.

**Comment by jai** [comment]
Closing this in favor of #27929

/close
