### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by waelmas** [kubernetes/website#23396]
**Problem:**
When deploying using the sample, it seems like the dashboard-metrics-scraper is problematic.

Upon running kubectl apply -f, I get the following error:

The Deployment "dashboard-metrics-scraper" is invalid: spec.template.annotations.seccomp.security.alpha.kubernetes.io/pod: Invalid value: "runtime/default": must be a valid seccomp profile

**Proposed Solution:**
Fix the dashboard-metrics-scraper in the sample so it deploys correctly please.

**Page to Update:**
k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

(I'm currently testing on minikube)

**Comment by Cweiping** [comment]
Thank you for your submission, please provide the relevant environment version information, I am testing the local version 1.18 to work normally.
/triage needs-information
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
```

**Comment by waelmas** [comment]
I've just upgraded to 1.17 (The latest available on AWS EKS). Now the deployment is fine, however I have multiple services, deployments and pods but none of them are showing.

**Comment by waelmas** [comment]
I noticed this in the notifications tho. Not sure if the issue is one and the same


clusterroles.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:kube-system:ttl-controller" cannot list resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope

**Comment by waelmas** [comment]
My bad I just figured it out.
