### ISSUE TITLE
Issue with k8s.io/docs/tasks/job/parallel-processing-expansion/

### ISSUE THREAD

**Issue by hydave25** [kubernetes/website#23397]
**This is a Bug Report**

**Problem:**
Getting following Error while executing the yaml file on latest version of kubectl

The Job "process-item-$ITEM" is invalid: 
* metadata.name: Invalid value: "process-item-$ITEM": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
* spec.template.labels: Invalid value: "process-item-$ITEM": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
That might be a bug. I think the line:
```bash
  cat job-tmpl.yaml | sed "s/\$ITEM/$i/" > ./jobs/job-$i.yaml
```

should change to 
```bash
  cat job-tmpl.yaml | sed "s/\\$ITEM/$i/" > ./jobs/job-"$i".yaml
```

/kind bug
/language en
/priority backlog

**Comment by Cweiping** [comment]
@hydave25 Do you execute scripts according to the page requirements? This page requires users to `https://k8s.io/examples/application/job/job-tmpl.yaml` Generate the available manifest.

`
The file you downloaded is not yet a valid Kubernetes manifest. Instead that template is a YAML representation of a Job object with some placeholders that need to be filled in before it can be used. The $ITEM syntax is not meaningful to Kubernetes.
`

The script for this page is then available to work. @sftim

**Comment by tengqm** [comment]
The existing command (script) is correct. I'd suspect that the user didn't faithfully run the following command:

```shell
mkdir ./jobs
for i in apple banana cherry
do
  cat job-tmpl.yaml | sed "s/\$ITEM/$i/" > ./jobs/job-$i.yaml
done
```

**Comment by sftim** [comment]
/remove-priority backlog
/priority awaiting-more-evidence
/close

@hydave25 if you have some more details about a shortcoming on that page, please feel free to reopen this issue.
