### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by djha736** [kubernetes/website#23393]
**This is a Bug Report**

**Problem:**

Pods network related options removed from documentation which was earlier there.

**Proposed Solution:**
kindly add back.

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
hi, the removal is intentional, see:
#22600
#22600 (comment)
#22961

/triage support
/close
/sig cluster-lifecycle
