### ISSUE TITLE
Jsonpath is not working if key is having special charaters

### ISSUE THREAD

**Issue by anupam587** [kubernetes/website#23392]
**This is a Bug Report**
Following command: "kubectl rollout history deployment/workspace-service -n workspace -o json"
Response:
{
    "kind": "Deployment",
    "apiVersion": "extensions/v1beta1",
    "metadata": {
        "name": "workspace-service",
        "namespace": "workspace",
        "selfLink": "/apis/extensions/v1beta1/namespaces/workspace/deployments/workspace-service",
        "uid": "a1ee0c03-88b8-479c-bb40-d56e3ac1bfbc",
        "resourceVersion": "60998402",
        "generation": 40,
        "creationTimestamp": "2020-08-24T07:36:32Z",
        "labels": {
            "app.kubernetes.io/instance": "workspace-platform-dev",
            "domain": "workspace",
            "env": "dev",
            "service": "workspace-service"
        },
        "annotations": {
            "deployment.kubernetes.io/revision": "14",
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/instance\":\"workspace-platform-dev\",\"domain\":\"workspace\",\"env\":\"dev\",\"service\":\"workspace-service\"},\"name\":\"workspace-service\",\"namespace\":\"workspace\"},\"spec\":{\"replicas\":1,\"revisionHistoryLimit\":50,\"selector\":{\"matchLabels\":{\"domain\":\"workspace\",\"env\":\"dev\",\"service\":\"workspace-service\"}},\"strategy\":{\"rollingUpdate\":{\"maxSurge\":\"50%\",\"maxUnavailable\":\"50%\"},\"type\":\"RollingUpdate\"},\"template\":{\"metadata\":{\"labels\":{\"domain\":\"workspace\",\"env\":\"dev\",\"service\":\"workspace-service\"}},\"spec\":{\"containers\":[{\"env\":[{\"name\":\"DBPASSWORD\",\"valueFrom\":{\"secretKeyRef\":{\"key\":\"DBPASSWORD\",\"name\":\"workspace\"}}}],\"envFrom\":[{\"configMapRef\":{\"name\":\"workspace-service-env-64k6f4mfdd\"}}],\"image\":\"176992832580.dkr.ecr.us-east-2.amazonaws.com/workspace/workspace-service:7f6f433.149\",\"livenessProbe\":{\"failureThreshold\":5,\"httpGet\":{\"path\":\"/health\",\"port\":80,\"scheme\":\"HTTP\"},\"initialDelaySeconds\":120,\"periodSeconds\":30,\"successThreshold\":1,\"timeoutSeconds\":10},\"name\":\"workspace-service\",\"ports\":[{\"containerPort\":80},{\"containerPort\":50051}],\"readinessProbe\":{\"failureThreshold\":5,\"httpGet\":{\"path\":\"/health\",\"port\":80,\"scheme\":\"HTTP\"},\"initialDelaySeconds\":120,\"periodSeconds\":30,\"successThreshold\":1,\"timeoutSeconds\":10},\"resources\":{\"limits\":{\"cpu\":\"2\",\"memory\":\"4Gi\"},\"requests\":{\"cpu\":\"1\",\"memory\":\"2Gi\"}}}],\"serviceAccountName\":\"workspace-service-account\"}}}}\n"
        }
    }
}

here i am unable to access the value of following key: 
"deployment.kubernetes.io/revision"

I am trying to access above key value using following command:
kubectl rollout history deployment/workspace-service -n workspace -o jsonpath={'.metadata.annotations'}{'.deployment.\kubernetes\.io\/revision'}

but I am not getting the desired result

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Kartik494** [comment]
Hi @anupam587 could you provide the deployment yaml file  which you are using in enviorment?  could you verfiy the syntax you are using [here](https://kubernetes.io/docs/reference/kubectl/jsonpath/)
