### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by mkbhanda** [kubernetes/website#23419]
**This is a Bug Report**

This documentation works just as well for a user who already has a Kubernetes cluster and wants to learn how to use it.
A few sentences to this effect such as export KUBECONFIG and how to launch a dashboard would do the trick (such as 
Kubectl apply -d https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deply/recommended.yaml).

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Cweiping** [comment]
Hi,thank you for your submission.Don't understand your question, can you express it more clearly?
Do you expect to add local installation commands to run the dashboard?
```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.3/aio/deploy/recommended.yaml
```
reference：https://github.com/kubernetes/dashboard

**Comment by sftim** [comment]
@mkbhanda would you have time to clarify the feature request you're making or the defect you're reporting?
