### ISSUE TITLE
Update StatefulSet tutorial to explain how to create volumes etc

### ISSUE THREAD

**Issue by mkbhanda** [kubernetes/website#23422]
**This is a Bug Report**

Would be nice to provide the user with a link on how to create storage class/volumes as opposed to the note "Assuming you have such volumes, else create 2 GB ..."

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

**Comment by sftim** [comment]
/retitle Update StatefulSet tutorial to explain how to create volumes etc

/kind feature
/language en
