### ISSUE TITLE
After 1.19 is released, create a redirect from /docs/reference/scheduling/profiles to /docs/reference/scheduling/config 

### ISSUE THREAD

**Issue by reylejano-rxm** [kubernetes/website#23433]
In the 1.19 release, KubeSchedulerConfiguration graduated to beta. The `/docs/reference/scheduling/config` page was created for the Scheduler Configuration which is a rework of `/docs/reference/scheduling/profiles`. Create a redirect from `/docs/reference/scheduling/profiles` to `/docs/reference/scheduling/config`

/cc @celestehorgan 
/language en

**Comment by reylejano-rxm** [comment]
Looks like this redirect is in place.
An attempt to go to `https://kubernetes.io/docs/reference/scheduling/profiles` redirects to `https://kubernetes.io/docs/reference/scheduling/config/#profiles`

@celestehorgan is this sufficient to close this issue?

**Comment by celestehorgan** [comment]
Yup!

/close
