### ISSUE TITLE
Issue with k8s.io/de/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by autopwn** [kubernetes/website#23445]
**This is a Bug Report**

**Problem:**
There is an issue in the German translation of https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration.
`kubectl config view -o jsonpath='{.users[].name}'    # eine Liste der Benutzer erhalten`
The comment indicates that a list of users is returned, but the command returns only the first user.
In the english version both variations are listed:
```
kubectl config view -o jsonpath='{.users[].name}'    # display the first user
kubectl config view -o jsonpath='{.users[*].name}'   # get a list of users
```

**Proposed Solution:**
```
kubectl config view -o jsonpath='{.users[].name}'    # den ersten Benutzer anzeigen
kubectl config view -o jsonpath='{.users[*].name}'    # eine Liste der Benutzer erhalten
```

**Page to Update:**
https://kubernetes.io/de/docs/reference/kubectl/cheatsheet/

**Comment by mkorbi** [comment]
thank you for reporting & fixing it
/close
