### ISSUE TITLE
ja: Make docs/concepts/workloads/pods/pod-lifecycle.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23450]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/workloads/pods/pod-lifecycle.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/workloads/pods/pod-lifecycle.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/pods/pod-lifecycle.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/workloads/pods/pod-lifecycle.md

diff between translated and v1.18
https://gist.github.com/ae3ce9b52ad136a32d2f3e9cd9b1c76e

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by oke-py** [comment]
@hase1128 https://github.com/kubernetes/website/pull/23284#issuecomment-683496387 を受けてレビュアー内で以下の話をしはじめたところでした。
まだassignつかないと思って今日後ほど考えるつもりでした。いかがでしょう？
> これまだIssue作成してないですよね？
> https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/pods/pod.md
> こっちのページに一部の内容が移動されているようです。
> https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/pods/pod-lifecycle.md
> 分量や複雑度によりますが、こちらのIssueで2ページ対応してもらうでもいいかもしれません？

**Comment by hase1128** [comment]
そうでしたか。
ついでにやろうと思ってましたが、いったんレビュアー内での方針が固まるまで待ちますね。
ひとまずassignは解除しておきます。

**Comment by kakts** [comment]
@hase1128 こちら pod.md pod-lifecycle.mdの変更内容確認中となります。
少々お待ちくださいませ。

**Comment by hase1128** [comment]
確認ありがとうございます。よろしくお願いします。

**Comment by kakts** [comment]
@hase1128  
返信遅れました。こちら pod.mdの分の対応もまとめてお願いできますでしょうか？

**Comment by hase1128** [comment]
@kakts 
承知しました。いくつか教えてください。
 - pod.md (実質削除するだけ)は、このIssueまとめて対応しますか？ (その場合は、PRはmdごとに分けますか？)
 - pod.mdの内容がpod-lifecycle以外にも移動しているか、把握していないのでそれも含めてやるでよいですか？
    (pod-lifecycle以外にも移動している場合は、それもこのIssueでまとめてやりますか？)

あと、明日から9/7まで夏休みを取るため、来週まとめてやろうと思いますがよろしいですか？

**Comment by oke-py** [comment]
@hase1128 
> pod.md (実質削除するだけ)は、このIssueまとめて対応しますか？ (その場合は、PRはmdごとに分けますか？)

このIssue、1つのPRでよいです。

> pod.mdの内容がpod-lifecycle以外にも移動しているか、把握していないのでそれも含めてやるでよいですか？

できそうならお願いしたいですが、必須ではありません。このIssueでよいです。

> 来週まとめてやろうと思いますがよろしいですか？

全然構いません。よろしくお願いいたします。

**Comment by hase1128** [comment]
@oke-py 
了解しました。まとめて(来週)着手します。

/assign
