### ISSUE TITLE
ja: Make docs/concepts/workloads/controllers/deployment.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23456]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/workloads/controllers/deployment.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/workloads/controllers/deployment.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/controllers/deployment.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/workloads/controllers/deployment.md

diff between translated and v1.18
https://gist.github.com/9709a696e01fa4ed8b15d8b9653b1e39

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
@hikkie3110 こちらいかがですかー（たまーにやってるIssueの整理なので、特に急がせているとかではありません。）

**Comment by hikkie3110** [comment]
@inductor あとは最終チェックくらいなので近日中に出せると思います。よろしくお願いします。

**Comment by hikkie3110** [comment]
今週時間取れておらず…明日までにPR出すようにしますmm
