### ISSUE TITLE
zh: Issue with k8s.io/zh/docs/tasks/tools/install-minikube/, Could update Aliyun image

### ISSUE THREAD

**Issue by Yiyiyimu** [kubernetes/website#23474]
**This is a Bug Report**

**Problem:**
minikube could not start in China due to GFW

**Proposed Solution:**
Improved from #21936, Aliyun fully supports the images needed to install minikube, as shown [here](https://github.com/AliyunContainerService/minikube/wiki).

Maybe we could provide link to that page, or update the information in https://kubernetes.io/zh/docs/tasks/tools/install-minikube/#%E5%AE%89%E8%A3%85%E7%A1%AE%E8%AE%A4

**Page to Update:**
https://kubernetes.io/zh/docs/tasks/tools/install-minikube/

**Comment by RA489** [comment]
@Yiyiyimu can you please try info on this PR https://github.com/kubernetes/minikube/pull/8555. if it solves your issue?

**Comment by Yiyiyimu** [comment]
@RA489 Sure I think our methods are the same. I'll close this issue.
