### ISSUE TITLE
ja: Make docs/tasks/tools/install-minikube.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#23471]
**This is a Feature Request**

**What would you like to be added**
Update docs/tasks/tools/install-minikube.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/tasks/tools/install-minikube.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/tasks/tools/install-minikube.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/tasks/tools/install-minikube.md

diff between translated and v1.18
https://gist.github.com/558d2d24fa80925864503e4275afd598

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by pururaj1908** [comment]
Hello @oke-py can I take this issue as my first contribution?

**Comment by oke-py** [comment]
Of cource.

**Comment by pururaj1908** [comment]
Alright thanks. I will ping you on Slack if I have some doubt as this would be my first contribution. You can assign this issue to me now.

**Comment by oke-py** [comment]
You can assign this to yourself by adding a comment `/assign`.

**Comment by inductor** [comment]
/close

@kakts マージされるタイミングなら、closeの面倒まで見てもらえると助かります～
