### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

### ISSUE THREAD

**Issue by Dipenduroy** [kubernetes/website#23483]
**This is a Bug Report**

**Problem:** 
Unable to deploy file beat
```
kubectl create -f filebeat-kubernetes.yaml
```
**Error :**
```
unable to recognize "filebeat-kubernetes.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
```

**Proposed Solution:** Had to follow [link](https://stackoverflow.com/questions/58252254/unable-to-recognize-filebeat-kubernetes-yaml-no-matches-for-kind-daemonset/58266192)

**Page to Update:**
https://kubernetes.io/...

**Kubernetes Version:**
Client Version: v1.18.8
Server Version: v1.18.3

**Comment by sftim** [comment]
Sounds like it needs tidying up (or possibly removing).

/kind cleanup
/language en

**Comment by Cweiping** [comment]
The latest version of kubernetes supported by [this project](https://github.com/kubernetes/kube-state-metrics) is v1.16, and the adaptation of v1.18 is far away. I agree with @sftim . I suggest that we remove some operation steps of the page and provide only functional support introduction and jump links to solve the problem of page update.
Reference: https://github.com/kubernetes/kube-state-metrics#compatibility-matrix

**Comment by sftim** [comment]
See https://github.com/kubernetes/website/issues/20232#issuecomment-728373191

**Comment by DanRoscigno** [comment]
Please assign to @DanRoscigno

**Comment by DanRoscigno** [comment]
I think this can be closed, the files are updated in the Elastic Examples repo:
```
https://github.com/elastic/examples/blob/master/beats-k8s-send-anywhere/filebeat-kubernetes.yaml
https://github.com/elastic/examples/blob/master/beats-k8s-send-anywhere/metricbeat-kubernetes.yaml
https://github.com/elastic/examples/blob/master/beats-k8s-send-anywhere/packetbeat-kubernetes.yaml
```
and have been tested.
