### ISSUE TITLE
Issue with k8s.io/docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by danc** [kubernetes/website#23494]
**This is a Bug Report**

**Problem:**
Cleaning Up section issue :
kubectl delete svc -l run=source-ip-app
No resources found
**Proposed Solution:**
kubectl delete svc -l app=source-ip-app
service "clusterip" deleted
service "loadbalancer" deleted
service "nodeport" deleted
**Page to Update:**
https://kubernetes.io/docs/tutorials/services/source-ip/

Kubernetes Version:
microk8s --classic --channel=1.18/stable

**Comment by sftim** [comment]
Hi @danc 

I'm not sure I understand how to implement the pages you're proposing for the page at 
https://kubernetes.io/docs/tutorials/services/source-ip/

Can you clarify what someone should do to improve that page?

/triage needs-information
/language en

**Comment by danc** [comment]
Hi, 
in fact when I ran the tutorial, I noticed that, with the current command proposed (`kubectl delete svc -l run=source-ip-app`)
the resources were not cleaned.
I tried instead the following : `kubectl delete svc -l app=source-ip-app` which cleaned the resources indeed.
But I'm not expert in k8s to be sure it is only an error in the tag usage (`app` instead of `run`)

**Comment by tengqm** [comment]
the proposed solution sounds reasonable to me.
