### ISSUE TITLE
Chinese translation error in page 应用故障排查

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#23507]
**This is a Bug Report**

**Problem:**
The following sentence is weird.

**Proposed Solution:**
![image](https://user-images.githubusercontent.com/16621880/91515660-38d41280-e91c-11ea-9bed-77fa52eb65e6.png)

**Page to Update:**
https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-application/

**Comment by tengqm** [comment]
closed by #23508
/close
