### ISSUE TITLE
link not displaying with link color in tab component

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#23504]
**This is a Bug Report**
Links within the tab component are not displaying using the site link color.

**Problem:**
The color of links within tab components is defaulting to `#222`.
The link is inheriting the color value from jquery-ui-min.css.

**Proposed Solution:**
Update the style for ui-widget-content -> a

**Page to Update:**
Start by looking at `website/assets/scss/_base.scss`.

Examples:

See link in Flatcar Container Linux tab in
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/
Look as the "vSphere" tab at the bottom of the page.

**Comment by kbhawkey** [comment]
Related to PR #23435.

**Comment by sftim** [comment]
/kind bug
/priority backlog
/area web-development

Feel free to reprioritize @kbhawkey
