### ISSUE TITLE
/docs/home/ links to current release docs even for older versions

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23502]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/home/ links to pages on https://kubernetes.io/

However:
- https://v1-18.docs.kubernetes.io/docs/home/ links to pages on https://kubernetes.io/ (and not https://v1-18.docs.kubernetes.io/)
- https://v1-17.docs.kubernetes.io/docs/home/ links to pages on https://kubernetes.io/
- https://v1-16.docs.kubernetes.io/docs/home/ links to pages on https://kubernetes.io/

you get the picture!

**Discussion**
[How] should we address this?

**Page to Update:**
https://kubernetes.io/docs/home/ _(and backports?)_

**Kubernetes Version:**
I originally logged this issue just after the v1.19 release.

/kind bug

/priority important-longterm
(because we want people to find useful documentation for older versions, and not to be misled)

**Comment by kushthedude** [comment]
@sftim I would like to solve this
/assign
