### ISSUE TITLE
404URL

### ISSUE THREAD

**Issue by ttonline6** [kubernetes/website#23506]
the url https://kubevirt.io/user-guide/docs/latest/administration/intro.html 
in  page https://github.com/kubevirt/containerized-data-importer/blob/master/doc/datavolumes.md return 404 code

**Comment by sftim** [comment]
Hi @ttonline6 

This repository is the right place to report defects in https://kubernetes.io/

Is there a page on https://kubernetes.io/ that isn't right?

/triage needs-information
