### ISSUE TITLE
Issue with v1-18.docs.kubernetes.io/docs/home/supported-doc-versions/

### ISSUE THREAD

**Issue by thebinary** [kubernetes/website#23512]
**This is a Bug Report**

**Problem:**
v1.18 documentation lists v1.19 under Previous versions

<img width="321" alt="Screen Shot 2020-08-28 at 11 09 22 AM" src="https://user-images.githubusercontent.com/14862656/91524457-00820380-e91f-11ea-8d62-b782019fe12d.png">

**Proposed Solution:**
Either remove v1.19 from v1.18 docs, or, add __Newer Versions__ sections and include v1.19 under that section.

**Page to Update:**
https://v1-18.docs.kubernetes.io/docs/home/supported-doc-versions/

**Comment by sftim** [comment]
/kind bug
/language en

Thanks @thebinary - good spot!
