### ISSUE TITLE
Kubefed Documentation: Should have more detailed instructions on Join command

### ISSUE THREAD

**Issue by LGRebel** [kubernetes/website#2353]
doc link: https://kubernetes.io/docs/admin/federation/kubefed/

**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Current instructions for joining a cluster to a federation isn't clear in terms of alias vs actual cluster context. 

"The cluster name you supply to kubefed join must be a valid RFC 1035 label."

kubefed join gondor --host-cluster-context=rivendell --cluster-context=gondor_needs-no_king

**Proposed Solution:**
Indicate that cluster-name is an alias that you're creating and not the cluster name in kubeconfig.

**Page to Update:**
https://kubernetes.io/docs/admin/federation/kubefed/

cc: @madhusudancs

**Comment by tengqm** [comment]
#2899 has addressed this issue.
