### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by kkkarthik** [kubernetes/website#23549]
**This is a Bug Report**
I have tried this interactive tutorial as to how we should expose an application as a service. 
I tried deploying a nginx application and eventually open a Nginx GUI. 

**Problem:**
[localhost nginx]$ kubectl describe services/mynginx
Name:                     mynginx
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=nginx
Type:                     NodePort
IP:                       10.103.45.205
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  32137/TCP
Endpoints:                172.18.0.3:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

[localhost nginx]$ export NODE_PORT=$(kubectl get services/mynginx -o go-template='{{(index .spec.ports 0).nodePort}}')
[localhost nginx]$ echo $NODE_PORT
32137
[localhost nginx]

Now I tried reaching the application using "curl" command:
 
[localhost nginx]$ curl $(minikube ip):$NODE_PORT
curl: (7) Failed connect to 172.17.0.2:32137; Connection refused

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Kartik494** [comment]
@kkkarthik Hi did you try at your own machine, when i tried it in interactive tutorial then curl command showed the expected output
