### ISSUE TITLE
Describe non-AMD64 / multiarch support

### ISSUE THREAD

**Issue by H-Kz** [kubernetes/website#23561]
On your install guiode , your CPU version like "AMD64" is not expressly shown anywhere.
Now I'm trying to use K8s in Raspberry Pi (Arm32bit), those information is very meeningful 4 me.
I'm glad if you are adding these.

thanks.

**Comment by Cweiping** [comment]
It's very interesting. Has k8s been cut? Have you considered resource constraints? As far as I know, k8s can't be transplanted completely. It needs to be trimmed and [k3s](https://github.com/rancher/k3s) or [KubeEdge](https://github.com/kubeedge/kubeedge) schemes should be used.I hope it can help you.
/triage support
/language ja

**Comment by H-Kz** [comment]
Hy,
Thanks for your reply.
The [offisial's guide](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) says Ubuntu16+ oor something is required, but doesn't says "x86" is required.
Also, some third-party documents like [this](https://qiita.com/reireias/items/0d87de18f43f27a8ed9b) (written in Japanese) shows us how to install "Kubernetes" to RasPi.
Then, I tried this, however it doesn't work with this error.

` -bash: /usr/local/bin/kubectl: cannot execute binary file: Exec format error`

Now I want to know like
- therer is some other ways for install to RasPi
or
- Kubernetes isnot/willnot support support RasPi.

**Comment by sftim** [comment]
/remove-kind support
/kind feature
I will also take the liberty to:
/retitle Describe non-AMD64 / multiarch support
/remove-language ja
(because documentation needs to land in the English pages first)

**Comment by yllekz** [comment]
The [kubectl install instructions](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/) fail to mention that it does not support the 32-bit Raspberry Pi OS. This should be addressed.
