### ISSUE TITLE
ja: Make docs/concepts/services-networking/service.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23596]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/services-networking/service.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/services-networking/service.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/services-networking/service.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/services-networking/service.md

diff between translated and v1.18
https://gist.github.com/731fa70c97c4eff0a82ac1d02fa41fa1

**Note**
Currently, we use **dev-1.18-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
@tkms0106 こちらいかがですかー（たまーにやってるIssueの整理なので、特に急がせているとかではありません。）

**Comment by tkms0106** [comment]
@inductor 現在着手中です。

**Comment by kakts** [comment]
https://github.com/kubernetes/website/pull/24002
↑でコメントされていたassign-pod-node.mdのページ移行とリンク修正のissue作成しました。
https://github.com/kubernetes/website/issues/24265
