### ISSUE TITLE
ja: Make docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23602]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.md

diff between translated and v1.18
https://gist.github.com/cb25b2f44c37242999da09cd0b2c7529

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by yu-kasuya** [comment]
@kakts dev-1.18-ja.1には、ja/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases.mdがないようでした。これも次のブランチですかね。

**Comment by inductor** [comment]
@yu-kasuya 遅くなりました。新しいブランチができました 🙇

**Comment by yu-kasuya** [comment]
@kakts @inductor こちらもdev-1.18-ja.2で差分は修正されていました。問題なければクローズお願いします。

**Comment by inductor** [comment]
確認ありがとうございます！
