### ISSUE TITLE
Search box is hard to see

### ISSUE THREAD

**Issue by jaredbhatti** [kubernetes/website#2361]
**This is a...** 

- [x ] Feature Request
- [ ] Bug Report

**Problem:**
The search box is hard to see, since it's white, and it sometimes is displayed on a white background. 

**Proposed Solution:**
Use CSS to add a grey outline around the search box.  (I'm open to other ideas as well, this is just the first thing that came to mind.)

**Page to Update:**
http://kubernetes.io/

**Comment by CreaturesInUnitards** [comment]
The better fix is to prevent the search box from wrapping down below the subnav strip.

Suggest reducing the default search box width from 320 to 250px, and re-building the media queries to shrink the subnav text size and the width of the search box between 1025 & 1300 px screen widths. This isn't an issue below 1025px.
