### ISSUE TITLE
How do you create a Persistent Volume - Issue with /docs/user-guide/ui/

### ISSUE THREAD

**Issue by naisanza** [kubernetes/website#2362]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I don't see where in the UI I can configure a new Persistent Volume to be used for a Deployment. And when creating a new Deployment I don't see where you enter in the options for a new PV or PVC.

After reading the documentation (https://kubernetes.io/docs/user-guide/persistent-volumes) I still don't know where in kubenetes/dashboard UI I can create a PV or PVC

**Page to Update:**
https://kubernetes.io/docs/user-guide/ui/

**Comment by jeffmendoza** [comment]
Hi @naisanza Is this a feature request for the UI?

**Comment by naisanza** [comment]
I believe it may be with the YAML/JSON file upload functionality when creating a new Deployment, but it's not stated anywhere in the documentation or the dashboard
