### ISSUE TITLE
Limited resource list enforcement for resource quota scoped for priority class.

### ISSUE THREAD

**Issue by kaushik229** [kubernetes/website#23626]
**Problem:**
When resource quota is created scoped for priority class, only subset of resource list are enforced and counted towards usage. We must make sure list and document all such resources so that users have better understanding of resource quota.
For details of which fields are supported, please refer.
https://github.com/kubernetes/kubernetes/blob/17aa60686ebe5fd04b4fe6f442dc36a8d70b6730/pkg/quota/v1/evaluator/core/pods.go#L44
**Proposed Solution:**
Please update resource quota document to reflect the same.

**Page to Update:**
https://kubernetes.io/docs/concepts/policy/resource-quotas/#resource-quota-per-priorityclass

All versions supporting resource quota for priority class.

**Comment by sftim** [comment]
/triage accepted
Fixed in PR #23795

Thanks @kaushik229 
/close
