### ISSUE TITLE
Issue with 'startingDeadlineSeconds' @ docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by juan-vg** [kubernetes/website#23622]
**This is a Bug Report**

**Problem:** `startingDeadlineSeconds` can be set to any value, but [the CronJob Controller checks things every 10s](https://github.com/kubernetes/kubernetes/blob/392bf0adef478175b9cf0226b02820eb1820f797/pkg/controller/cronjob/cronjob_controller.go#L95-L96). If it's set to any value less than 10s the CronJob will be never scheduled.

**Proposed Solution:** Force the value to be always greater than 10, or warn people there are non-working values

**Page to Update:**
https://kubernetes.io/es/docs/concepts/workloads/controllers/cron-jobs/

Kubernetes Version: 1.15.12

**Comment by sftim** [comment]
Thanks @juan-vg

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/4500

**Comment by sftim** [comment]
I recommend adding a warning. There is a v2 controller for CronJob arriving in Kubernetes v1.20 that may _eventually_ honor any setting for `startingDeadlineSettings`; however, we want to document the shortcoming right now.

Specifically I would add a [caution](https://kubernetes.io/docs/contribute/style/style-guide/#caution) callout, with text similar to:
> if `startingDeadlineSeconds` is set to a value less than 10 seconds then the CronJob may not be scheduled.

/good-first-issue
/sig apps
