### ISSUE TITLE
Removes IPVS prerequisites in "Validate IPv4/IPv6 dual-stack"

### ISSUE THREAD

**Issue by hobbytp** [kubernetes/website#23648]
**This is a Bug Report**

**Problem:**
In Dualstack doc updates for 1.18 #20694, it only removes IPVS prerequisites in https://kubernetes.io/docs/concepts/services-networking/dual-stack/ but not remove it in https://kubernetes.io/docs/tasks/network/validate-dual-stack/, you still can find "Kube-proxy running in mode IPVS" in the doc.

**Proposed Solution:**
remove "Kube-proxy running in mode IPVS" in https://kubernetes.io/docs/tasks/network/validate-dual-stack/

**Page to Update:**
https://kubernetes.io/docs/tasks/network/validate-dual-stack/

**Comment by celestehorgan** [comment]
/language en
/priority important-soon
/kind bug

@lachie83 – Can you verify the issue described is correct? If so we can tag it as a good first issue and have someone tackle it.

**Comment by lachie83** [comment]
Hi @celestehorgan and @hobbytp. Thank you very much for raising this. I can indeed validate that the issue is correct and that the proposed solution is correct and would be more than happy to review a PR if someone would be happy to contribute. Thanks again

**Comment by celestehorgan** [comment]
@lachie83 – no further action from you needed, this was a small fix. Thank you!
