### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/jsonpath/

### ISSUE THREAD

**Issue by MichalGuzieniuk** [kubernetes/website#23642]
I missing an example of JSON map where the key has a dot inside.

{
    "kind": "Secret",
    "apiVersion": "v1",
    "metadata": {
        "name": "rails"
    },
    "data": {
        "db.conf": "cmVkYWN0ZWQK",
        "dbdotconf": "cmVkYWN0ZWQK"
    },
    "type": "Opaque"
}

How to get value of db.conf with 
kubectl get pods -o=jsonpath='{.data[0]}'

**Comment by tengqm** [comment]
the object is not a pod, so `kubectl get pods` won't work.
On [kubectl cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/), there is a sample which may be helpful:

```
kubectl get secrets rails \
  -o jsonpath='{.data.db\.conf}'
```

**Comment by shekhar-rajak** [comment]
Isn't this can be closed ?
