### ISSUE TITLE
Issue with k8s.io/docs/setup/learning-environment/minikube/

### ISSUE THREAD

**Issue by RoSk0** [kubernetes/website#23650]
**This is a Bug Report**

**Problem:**
information on this page as well as on https://kubernetes.io/docs/tasks/tools/install-minikube/ is **out of date**.

**Proposed Solution:**
Remove /docs/tasks/tools/install-minikube/
Replace link destination from `docs/tasks/tools/install-minikube/` to `https://minikube.sigs.k8s.io/docs/start/`

**Page to Update:**
https://kubernetes.io/docs/setup/learning-environment/minikube/

**Comment by RA489** [comment]
+1 for this update.
