### ISSUE TITLE
"GKE" reference s/b removed/rewritten

### ISSUE THREAD

**Issue by bpaduch** [kubernetes/website#23659]
**This is a Bug Report**

**Problem:**
Content references "GKE" which is a Google product.

**Proposed Solution:**
Rewrite the sentence to pertain to Kubernetes, not Google.

**Page to Update:**
 k8s.io/docs/concepts/architecture/control-plane-node-communication/

**Comment by celestehorgan** [comment]
Also if this is the @bpaduch I think it is... hi! long time no see! :)

**Comment by Evalle** [comment]
Hi @celestehorgan. I think you're talking about the following sentence:

> For example, on a default GKE deployment, the client credentials provided to the kubelet are in the form of a client certificate. 

Should we change it to "On a Kubernetes deployment, the client credentials provided to the kubelet are in the form of a client certificate." ? Any better suggestions to rephrase it? Thank you.

**Comment by bpaduch** [comment]
@Evalle - As long as that statement is _technically_ accurate for Kubernetes.
