### ISSUE TITLE
The execution contexts of hook handlers with different action types are different

### ISSUE THREAD

**Issue by bryanchang15** [kubernetes/website#23670]
**This is a Bug Report**

**Problem:**

Description in `hook-handler-execution` says:

> When a Container lifecycle management hook is called, the Kubernetes management system executes the handler in the Container registered for that hook. 

But actually only the handler with a `ExecAction` would be ran in the container. The handler with a `HttpGetAction` would only be ran in the context of the kubelet process.

**Proposed Solution:**

Clarify this difference in the document.

**Page to Update:**
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution

**Comment by bryanchang15** [comment]
We encountered a DNS resolution failed when executing `preStop` hook with a `HTTPGetAction` to GET a `Service` in the cluster and our debugging leads to this document issue.

**Comment by sftim** [comment]
I think that's unclear enough to merit:
/kind bug
/language en

(also, being able to make HTTP requests as the kubelet could even count as a privilege escalation in some cases where people didn't realize that happens)

**Comment by Cweiping** [comment]
I tried to fix it.
At the same time, I think this action is not in line with expectations, related issues:https://github.com/kubernetes/kubernetes/issues/94558
/assign

**Comment by Cweiping** [comment]
its already fixed by #23699 . Help close it. Thx! 
By the way, how can I apply for this permission? Do you need to apply to be a member?

@sftim
