### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubernetes-api/labels-annotations-taints/

### ISSUE THREAD

**Issue by Vinigas** [kubernetes/website#23685]
"On the PersistentVolume: The PersistentVolumeLabel admission controller will automatically add zone labels to PersistentVolumes, on GCE and AWS."

What about other vendors ? This section could be compatibility table.

**Comment by sftim** [comment]
With the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/) in mind, it would be better to remove the example vendor names I think.

/language en
/kind cleanup
