### ISSUE TITLE
Object Names and IDs

### ISSUE THREAD

**Issue by Ilyes512** [kubernetes/website#23689]
I believe the correct RFC for [DNS Label names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) should be https://tools.ietf.org/html/rfc1035

**Comment by sftim** [comment]
RFC1035 allows underscores in names, whereas RFC 1123.
Kubernetes does not allow underscores in names.

I think the existing text is technically accurate. Does that sound right?
/language en
/triage needs-information

**Comment by tengqm** [comment]
Let's close this for lacking response for several months.
/close
