### ISSUE TITLE
Improvement for k8s.io/docs/setup/best-practices/certificates/

### ISSUE THREAD

**Issue by recentcoin** [kubernetes/website#23726]
Any hints on how to integrate this with an existing CA?  For example, our AD domain currently has a CA cluster for authentication between machines.  We'd like to expand that to handle the certs needed for kube containers so that its already trusted by our staff.

**Comment by sftim** [comment]
I think you're asking for something different from what https://k8s.io/docs/setup/best-practices/certificates/ is requesting - my guess is that what you have in mind is closer to https://github.com/kubernetes/website/issues/14725 (TLS for applications running in the cluster)

Have I got that right?
/language en
/triage needs-information

**Comment by sftim** [comment]
Will close this. Slightly relevant to issue https://github.com/kubernetes/website/issues/25833
/close
