### ISSUE TITLE
Where does static pods belong?

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#23729]
**This is a Bug Report**

**Problem:**

The static-pod page was moved from tasks/administer-cluster to tasks/configure-pod-container in dd6f88dfe78e4fb61c1c7cc81bccee20bb96481a.
This is a wrong movement because static pods are special pods to be managed by a cluster admin.
A side effect is that we have the following redirection path:

```
/docs/admin/static-pods/     /docs/tasks/administer-cluster/static-pod/ 301
/docs/concepts/cluster-administration/static-pod/     /docs/tasks/administer-cluster/static-pod/ 301
/docs/tasks/administer-cluster/static-pod/ /docs/tasks/configure-pod-container/static-pod/ 301
```

**Proposed Solution:**

Undo the movement.

**Page to Update:**

https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

**Comment by sftim** [comment]
I wonder, is there a way to let Docsy list that page twice, once in each place?

**Comment by sftim** [comment]
See https://github.com/kubernetes/website/issues/22788#issuecomment-712896348 for a possible mechanism to list pages more than once.
