### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by nomstradamus** [kubernetes/website#23732]
Should mention that env properties in POD cannot be reloaded . This would require a pod restart. However volume mount config maps can be reloaded.

**Comment by sftim** [comment]
/kind feature
/language en
/priority backlog

If picking this up, also consider mentioning this detail in https://kubernetes.io/docs/concepts/configuration/configmap/

**Comment by nomstradamus** [comment]
I signed it

**Comment by tengqm** [comment]
/close
done.
