### ISSUE TITLE
Error in “Using a Service to Expose Your App”

### ISSUE THREAD

**Issue by micktg** [kubernetes/website#23749]
I think, that the legend for the graphic under the headline "Services and Labels" contains an error. 
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/
The violet cube is not a pod but a container. The surrounding circle should be the pod and the violet cube within should the container.

**Comment by sftim** [comment]
/retitle Error in “Using a Service to Expose Your App”

Similar to issue #8679
