### ISSUE TITLE
ja: Move docs/concepts/workloads/pods/pod-overview.md to docs/concepts/workloads/pods/_index.md

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#23748]
**This is a Feature Request**

**What would you like to be added**

Please move ja/docs/concepts/workloads/pods/pod-overview.md to ja/docs/concepts/workloads/pods/_index.md and fix links about this page.
https://github.com/kubernetes/website/pull/23581#discussion_r479936059
https://github.com/kubernetes/website/commit/49eee8fd3d9eba5e7390c9014ac05d036ced3ca6#diff-7294f337fd4609fcb4b23001b4f1b82d

If any changes in the original document, please translate it into Japanese.
**Why is this needed**
Because the original English docs of docs/concepts/workloads/pods/pod-overview.md had been moved to docs/concepts/workloads/pods/_index.md.

Original
https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/workloads/pods/_index.md

Old pod-overview page.
https://github.com/kubernetes/website/blob/master/content/ja/docs/concepts/workloads/pods/pod-overview.md

**Comments**

/language ja

To the Japanese translation reviewers.
After fixing this, please merge https://github.com/kubernetes/website/pull/23581

**Comment by hase1128** [comment]
@kakts 

ご存知と思いますが、_index.mdは、pod-overview.mdだけでなくpod.mdからもいくつかの記事が移動してきますので、参考にしてください。

先ほど、pod-lifecycle.mdの更新[PR](https://github.com/kubernetes/website/pull/23786)を出しましたが、その中でpod.mdの削除もしているので、この_index.mdの更新PRとできるだけ同時にマージされる形が望ましいと考えています。

**Comment by kakts** [comment]
@hase1128  ご確認ありがとうございます!

https://github.com/kubernetes/website/pull/23786
pod-lifecyclePRの方も合わせてレビュー進めます。

**Comment by sftim** [comment]
/language ja
Does this need any more work?

**Comment by inductor** [comment]
@kakts これいかがですかー。
https://github.com/kubernetes/website/pull/24155

このへんのリンク先にもなってるので、状況合わせて対応内容は考えたい感じです
