### ISSUE TITLE
Update Chinese localization for v1.19

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23775]
**This is a Clean Up Request**

**What would you like to be added**
Update the Chinese localization for changes since v1.18

**Why is this needed**
The Chinese documentation is largely based on documentation for older versions of Kubernetes. Ideally, the master-branch documentation would include the changes that were made for the v1.19 release, including [feature gate status](https://kubernetes.io/zh/docs/reference/command-line-tools-reference/feature-gates/) and feature-state details within pages.

**Comments**
Maybe some tooling could help to detect which changes need making, perhaps even to recommend the replacement?
/language zh
/kind cleanup

**Comment by JornShen** [comment]
Agree with it.  which tools  you recommend? Or we can write some script to realize it ?

**Comment by ydcool** [comment]
It's hard to detect present changes, because the Chinese translation has no connection to en docs on pull request or commit, but maybe we can introduce some tools to track new changes from now on.

**Comment by sftim** [comment]
Try `scripts/lsync.sh`. With the version from https://github.com/kubernetes/website/pull/24419 you can:
```bash
find content/zh/docs -name '*.md' -type f -print0 | xargs -r -0 scripts/lsync.sh
```
to see what needs localizing.

**Comment by JornShen** [comment]
That would be a great and huge processes. Maybe we can add label `help` or `good-first-issue` to attract more people to join it. 

/help 
/good-first-issue

**Comment by sftim** [comment]
There is a lot of work here and the overall task is not simple enough for a new contributor to join in unaided.
/remove-good-first-issue

It is OK to create good-first-issue subtasks that reference back to this one.

**Comment by tengqm** [comment]
A summary of the current status for ZH localization.

- All pages in 1.19 have been translated except for some case studies.
- We have tried to synchronize all concepts changes to Chinese, PRs under review.
- We still need some synchronization for tasks.

Overall, I'm very proud of the ZH localization progress, which proves to be one of localizations with least gaps from English contents.
