### ISSUE TITLE
Add shortcode for marking deprecated sections of pages

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23777]
**This is a Feature Request**

**What would you like to be added**
Add a Hugo shortcode that contains Markdown for deprecated sections of pages.
The shortcode renders visually taking little space by default, but the reader can expand the page to reveal more.

**Why is this needed**
Pages such as:
- https://kubernetes.io/docs/concepts/storage/storage-classes/ 
- https://kubernetes.io/docs/concepts/workloads/controllers/
- https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

include deprecated information. To make reading easier on the reader, we can hide this information by default but allow a means to reveal it. That marker will also make it a little easier to audit it for cleanup.

**Comments**
/kind feature
/area web-development

**Comment by prankul88** [comment]
I too felt the need for this.
+1 for adding it.

**Comment by sftim** [comment]
I'll take that as a
/triage accepted
