### ISSUE TITLE
Update Japanese localization to v1.19

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#23773]
**This is a Clean Up Request**

**What would you like to be added**
Update the Japanese localization for changes since v1.18

**Why is this needed**
The Japanese documentation is largely based on documentation for older versions of Kubernetes. Ideally, the master-branch documentation would include the changes that were made for the v1.19 release, including [feature gate status](https://kubernetes.io/ja/docs/reference/command-line-tools-reference/feature-gates/) and feature-state details within pages.

**Comments**
Maybe some tooling could help to detect which changes need making, perhaps even to recommend the replacement?
/language ja
/kind cleanup

**Comment by inductor** [comment]
We work on our work branch based on our own milestones. We cannot track all the difference with the number of active contributors...

**Comment by inductor** [comment]
Anyways, we recognize this and we manage this so I shall close this now.

/close
