### ISSUE TITLE
Pod Lifecycle

### ISSUE THREAD

**Issue by Jeson515** [kubernetes/website#23781]
To the check state of a Pod's containers or
To check the state of a Pod's containers

**Comment by Kartik494** [comment]
Hi @Jeson515 could you elaborate more on which issue you are facing for pod [lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/) ?

**Comment by Kartik494** [comment]
Hi @Jeson515 Do you want to continue with this issue? if you are OK with it should we go for closing the issue
