### ISSUE TITLE
Co-chair transition

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#23797]
## SIG Docs co-chair transition

In the [15 September 2020 SIG Docs weekly meeting](https://docs.google.com/document/d/1Jio9rEtYxlBbntF8mRGmj6Q1JAdzZ9fTDo3ru1HK_LI/) I, @zacharysarah announced that I'm stepping down as SIG Docs co-chair and will become a chair emeritus.
 
I nominate @irvifa to replace me.

### Transition date

Without further input, lazy consensus is to transition on September 15, 2020.

## Procedures for changing co-chairs

SIG Docs follows the procedure for transitions in our [community charter](https://github.com/kubernetes/community/blob/master/sig-docs/charter.md): 

> This charter adheres to the conventions described in the Kubernetes Charter README and adheres to the Roles and Organization Management specified in sig-governance.

From [sig-governance](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md#notes-on-roles):

> Within this section "member" refers to a member of a Chair, Tech Lead or Subproject Owner Role. (this different from a SIG or Organization Member).
> Members MAY decide to step down at anytime and propose a replacement. Use lazy consensus amongst other members with fallback on majority vote to accept proposal. The candidate SHOULD be supported by a majority of SIG Members or Subproject Contributors (as applicable).

### Lazy consensus

This issue proposes lazy consensus for @irvifa to replace @zacharysarah on 15 September 2020 as SIG Docs co-chair, giving time for feedback from SIG members.

For lazy consensus, this issue needs:

- [x] A statement from @zacharysarah that he intends to step down as SIG Docs co-chair: by comment on this issue, in a weekly meeting, or in an email to kubernetes-sig-docs@googlegroups.com. (
- [x] A statement from @irvifa accepting the nomination as SIG Docs co-chair: by comment on this issue, in a weekly meeting, or in an email to kubernetes-sig-docs@googlegroups.com
- [x] A vote from the current co-chairs (@jimangel, @kbarnard10, @zacharysarah) to confirm the nomination of @irvifa . 

When these two conditions are met, and without clear consensus on a different path, on 15 September 2020:

- [x] @zacharysarah becomes a chair emeritus of SIG Docs
- [x] @irvifa becomes a co-chair of SIG Docs

## Required changes

Co-chair transitions require some updates.

Repo | file | PR
---|---|---
k/community | [OWNERS_ALIASES](https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/community/pull/5125
k/community | [sig-docs/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/README.md) | https://github.com/kubernetes/community/pull/5125
k/community | [sig-docs/blog-subproject/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/blog-subproject/README.md) | https://github.com/kubernetes/community/pull/5125
k/community | [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md) | https://github.com/kubernetes/community/pull/5125
k/community | [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) | https://github.com/kubernetes/community/pull/5125
k/enhancements | [OWNERS_ALIASES](https://github.com/kubernetes/enhancements/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/enhancements/pull/1978
k/org | [OWNERS_ALIASES](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/org/pull/2225
k/org | [config/kubernetes/sig-docs/teams.yaml](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml) | https://github.com/kubernetes/org/pull/2225
k/org | [config/kubernetes-sigs/sig-docs/teams.yaml](https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/sig-docs/teams.yaml) | https://github.com/kubernetes/org/pull/2225
k/website | [OWNERS](https://github.com/kubernetes/website/blob/master/OWNERS) | #23799 
k/website | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES) | #23799 
k/website | [SECURITY_CONTACTS](https://github.com/kubernetes/website/blob/master/SECURITY_CONTACTS) | #23799 
k/k | [OWNERS_ALIASES](https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/kubernetes/pull/95102
k/test-infra | [OWNERS_ALIASES](https://github.com/kubernetes/test-infra/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/test-infra/pull/19374
k-sigs/reference-docs | [OWNERS](https://github.com/kubernetes-sigs/reference-docs/blob/master/OWNERS) | https://github.com/kubernetes-sigs/reference-docs/pull/171
k-sigs/reference-docs | [SECURITY_CONTACTS](https://github.com/kubernetes-sigs/reference-docs/blob/master/SECURITY_CONTACTS) | https://github.com/kubernetes-sigs/reference-docs/pull/171
k/k8s.io | [OWNERS_ALIASES](https://github.com/kubernetes/k8s.io/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/k8s.io/pull/1283

/assign @irvifa @jimangel @kbarnard10 
/sig docs

**Comment by irvifa** [comment]
Thank you for the opportunity, I accept the nomination for co-chair. A huge thank you to @zacharysarah for all of the awesome leadership and contributions ❤️

**Comment by tengqm** [comment]
**xref: SIG Docs Co-Chair prerequisites and responsibilities:**
https://kubernetes.io/docs/contribute/advanced/#serve-as-a-sig-co-chair

**Comment by jimangel** [comment]
@zacharysarah it is not enough to say "thank you" for your contributions to SIG Docs, but thank you! The Kubernetes project has experienced unprecedented growth over the past 5 years and many folks, including myself, started by reading the docs. You've helped establish the ground work and foundation for a thriving community. When I started contributing a couple years ago, I was warmly welcomed as an "outsider" attending my first SIG Docs weekly meeting. Over the years, I've witnessed you continually providing a welcoming atmosphere in Slack, meetings, and KubeCon summits. Kubernetes documentation, and the SIG Docs community, would not be the same quality without your leadership and guidance to get us to where we are now. I look forward to your future adventures! Cheers 🎉 

@irvifa it has been great getting to know you and seeing your contributions advance. It will be great to have a Co-Chair that can help improve localization efforts as well. Let me know how I can support you and help your transition along the way!

**Comment by irvifa** [comment]
@jimangel Thanks Jim! definitely will need all of the folks help that I need during the transition 🙂

**Comment by sftim** [comment]
Holding for now as no current chairs in the September 15, 2020 weekly meeting and one lazy consensus prerequisite not met.

**Comment by jimangel** [comment]
Update for anyone following this issue: Lazy consensus was met on 9/22 at the SIG Docs weekly meeting.

**Comment by sftim** [comment]
/remove-lifecycle stale
/lifecycle frozen
Waiting for explicit closure

**Comment by celestehorgan** [comment]
@zacharysarah – can we close this? ;)

**Comment by zacharysarah** [comment]
Indeed we can.

/close

/meow
