### ISSUE TITLE
Copy to clipboard not copying yaml

### ISSUE THREAD

**Issue by morengab** [kubernetes/website#23817]
"Copy application/deployment.yaml to clipboard" copies the name of the yaml file but not the actual yaml itself. 
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/565634/92959455-78791f00-f431-11ea-8d28-d86a82012817.png">

**Comment by kbhawkey** [comment]
/retitle Copy to clipboard not copying yaml

**Comment by kbhawkey** [comment]
@morengab , I changed the title for this issue. Feel free to change is this is not correct.

**Comment by morengab** [comment]
@kbhawkey perfect! looks like the title was auto-generated from the page and I just left it that way.

**Comment by kbhawkey** [comment]
Do you plan on working on this? If not, I will.

**Comment by kbhawkey** [comment]
Temporarily assigning
/assign

**Comment by morengab** [comment]
> Do you plan on working on this? If not, I will.

Nope! You've got it 👍

**Comment by sftim** [comment]
/triage accepted
Fixed in #23966 
/close
