### ISSUE TITLE
Please consider leaving politics out of documentation websites

### ISSUE THREAD

**Issue by damusix** [kubernetes/website#23824]
**This is Support**

I would like to politely and respectfully propose we keep politics out of our work environments. I'm all for showing support for what you believe in, but it would be nice if we could keep code docs about code docs and not politics. Not everyone agrees with the principles or political views of BLM and it's a bit annoying / triggering / distracting to see my favorite tools constantly spamming me political messages while I am working. Please consider removing political messages from site's banner.

**Comment by B45man** [comment]
It's easily removed by adding a rule for **#announcement** to your adblocker. No more huge political banners taking up a third of the screen on entry.

**Comment by dims** [comment]
Please join the wg-naming and discuss there:
https://github.com/kubernetes/community/blob/master/wg-naming/README.md

/close
