### ISSUE TITLE
this will not work, no permissions

### ISSUE THREAD

**Issue by joey95033** [kubernetes/website#23859]
this will not work, no permissions
kubectl completion bash >/etc/bash_completion.d/kubectl

change to this

echo $(kubectl completion bash) | sudo tee /etc/bash_completion.d/kubectl

__Originally posted by @kursluzz in https://github.com/kubernetes/website/issues/23857__

**Comment by sftim** [comment]
/triage duplicate

This is a duplicate of issue #23857 
/close
