### ISSUE TITLE
1.19-specific release notes URL

### ISSUE THREAD

**Issue by bergerhoffer** [kubernetes/website#23855]
**This is a Feature Request**

**What would you like to be added**
A 1.19-specific URL for the Kubernetes 1.19 release notes. 

**Why is this needed**

Currently, I can only find the 1.19 release notes at https://kubernetes.io/docs/setup/release/notes/. I assume that page will eventually be updated to be for 1.20 once that is released. So it would be nice to have a page to link to that will be "guaranteed" to stay as is for the 1.19 release notes.

We currently link to https://v1-18.docs.kubernetes.io/docs/setup/release/notes/ for 1.18, (and have used this format for past releases), but it doesn't look like there is one for 1.19.

**Comments**
Thanks!

**Comment by sftim** [comment]
If https://v1-19.docs.kubernetes.io/docs/setup/release/notes/ were a redirect to https://kubernetes.io/docs/setup/release/notes/ until the next release happens, that might be good enough.

_Or_ we could make that a general redirect to the live site with an exemption for the release notes pages.

**Comment by bergerhoffer** [comment]
I do see that https://v1-19.docs.kubernetes.io/docs/setup/release/notes/ was added for 1.19 which is awesome.

However, since the generic link (https://kubernetes.io/docs/setup/release/notes/) was updated to 1.20, this means that our page that linked to 1.19 is now actually pointing to 1.20 release notes. This is the problem we foresaw when opening this issue. I'll go back and update our links, but it could be causing some confusion for readers in the meantime.

And I can see that we're going to keep running into the same problem for 1.20 (and further), which doesn't have a version-specific page yet. Would love to see the new release notes get their own version-specific page at the time it is released, like it used to. Then you could always have the generic link (https://kubernetes.io/docs/setup/release/notes/) redirect to the latest version's release notes.

**Comment by sftim** [comment]
@bergerhoffer I recommend tracking this as a part of issue #20293 - it's not specific to a particular release

**Comment by bergerhoffer** [comment]
Thanks @sftim I've added a comment to that issue.
