### ISSUE TITLE
Set up Ingress on Minikube with the NGINX Ingress Controller

### ISSUE THREAD

**Issue by jajalcoding** [kubernetes/website#23854]
Hi, I am having issue following this article

asiong@ubuntu:~$ kubectl get pods -n kube-system
NAME                                       READY   STATUS      RESTARTS   AGE
coredns-f9fd979d6-cclz9                    1/1     Running     1          31h
etcd-minikube                              1/1     Running     1          31h
ingress-nginx-admission-create-27s2h       0/1     Completed   0          65m
ingress-nginx-admission-patch-tcwgt        0/1     Completed   0          65m
ingress-nginx-controller-789d9c4dc-dhltd   1/1     Running     0          65m
kindnet-7svq2                              1/1     Running     1          28h
kindnet-phffp                              1/1     Running     1          25h
kindnet-xf574                              1/1     Running     1          28h
kube-apiserver-minikube                    1/1     Running     2          31h
kube-controller-manager-minikube           1/1     Running     0          28h
kube-proxy-92gr2                           1/1     Running     1          31h
kube-proxy-c9rfq                           1/1     Running     0          28h
kube-proxy-cx2q9                           1/1     Running     0          25h
kube-scheduler-minikube                    1/1     Running     1          31h
storage-provisioner                        1/1     Running     8          31h

asiong@ubuntu:~$ cat example-ingress.yaml 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: 8080

asiong@ubuntu:~$ kubectl apply -f example-ingress.yaml 
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Error from server (InternalError): error when creating "example-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.kube-system.svc:443/extensions/v1beta1/ingresses?timeout=30s": dial tcp 10.99.13.111:443: connect: connection refused

May I know why ?

Thanks

**Comment by RA489** [comment]
https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress-dns

**Comment by RA489** [comment]
> https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress-dns

@jajalcoding Any luck with above documentation.

**Comment by jajalcoding** [comment]
Hi @RA489 , thanks.. actually I found out the issue because i was running 2 node minikube, and somehow when the ingress is installed in the 2nd node, it never work. When I removed the 2nd node, it is working well. 
Thank you
