### ISSUE TITLE
remove command & args in the "kubectl create deployments" usage  

### ISSUE THREAD

**Issue by christomas1** [kubernetes/website#23869]
Ref: https://github.com/kubernetes/kubernetes/issues/94755#issuecomment-691707198

Remove `-- [COMMAND] [args...]` in:
https://github.com/kubernetes/website/blob/69033456ed57344b17e87ad8a348930c590fcd30/static/docs/reference/generated/kubectl/kubectl-commands.html#L580

**Comment by pacoxu** [comment]
fixed in  #94763

**Comment by christomas1** [comment]
close per #94755 (comment)
