### ISSUE TITLE
Scheduling Policies mis-named predicate for NodeSelector

### ISSUE THREAD

**Issue by jonathanheaden** [kubernetes/website#23862]
`PodMatchNodeSelector` is mislabelled, I believe it should be `MatchNodeSelector`
This is the name used in https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/legacy_registry.go#L93
The predicate was also named `MatchNodeSelector` in `predicates.go` before that file was removed in kubernetes/kubernetes#87091

**Comment by sftim** [comment]
/kind bug
/sig scheduling
/language en
/priority backlog

Thanks @jonathanheaden

**Comment by jonathanheaden** [comment]
this is resolved
