### ISSUE TITLE
Document ABAC policy configuration format

### ISSUE THREAD

**Issue by kennyk65** [kubernetes/website#23885]
No such apiVersion as abac.authorization.kubernetes.io/v1beta1 in the API reference.  No such object as "Policy" in the API reference.

**Comment by tengqm** [comment]
@liggitt Please help comment why we are not including the abac APIs in the API spec. Thanks.

**Comment by liggitt** [comment]
These objects are not served as REST APIs. The published openapi spec which the API docs are generated from only include served APIs

**Comment by tengqm** [comment]
@liggitt Thanks for the info. Although they are not "served as REST APIS", an admin who wants to use it still needs some reference to its spec. At the moment, we can only check the source code as reference. That is an area we need to improve. Am I understanding this correctly?

**Comment by liggitt** [comment]
Yes, something similar was requested in https://github.com/kubernetes/kubernetes/issues/84081
