### ISSUE TITLE
blog: typo in PodTopologySpread post

### ISSUE THREAD

**Issue by adtac** [kubernetes/website#23884]
https://github.com/kubernetes/website/blob/5632ae93ea209d0849d702f25e1a13e4f8842980/content/en/blog/_posts/2020-05-05-introducing-podtopologyspread.md#L89

The specs should say `key: env`, not `key: type`

/sig scheduling
/cc @Huang-Wei @alculquicondor

**Comment by Huang-Wei** [comment]
Thanks @adtac, that's a typo... Let me update the image.
