### ISSUE TITLE
Document that Federated Ingress only work with an HTTPS Ingress if there is no static IP created out-of-band

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/website#2391]
If a Federated Ingress specifies an HTTP Ingress, i.e. without a TLS section, it needs a static IP address already reserved in GCP and that address name specified via the `kubernetes.io/ingress.global-static-ip-name` annotation to make it work. Alternatively, HTTPS Ingress doesn't have this limitation. We need to document this as a known issue.

This issue is actually assigned to Allan. Since he is not in the assignees list, I am putting my name and cc'ing Allan on this issue.

cc @allannaim

**Comment by tengqm** [comment]
@csbell ping.
