### ISSUE TITLE
Poor alignment between tiles and buttons on home page for docs

### ISSUE THREAD

**Issue by raghvenders** [kubernetes/website#23914]
~**This is Support**~

In the https://kubernetes.io/docs/home/page , i am able to see under Kubernetes Documentation.

Respective tiled content buttons are aligned respective the content length or size.

As a user , i would like to see them aligned as a bordered tile content with buttons are aligned look like a row irrespective of tile content length.

This improves the user experience

Please let me know if drawings are needed to understand.So that i can take a capture of it and attach.

**Comment by sftim** [comment]
/area web-development
/kind cleanup

@raghvenders a mockup would be useful

**Comment by sftim** [comment]
/priority awaiting-more-evidence
(adjust this once the discussion has made it clear)

**Comment by raghvenders** [comment]
@sftim - PFA.It is screenshot of button aligned.I have added the tile border which is not the primary objective though(Just to border line the content)

![KubernetesHomePage1](https://user-images.githubusercontent.com/9973300/93594143-e5813d00-f97a-11ea-9fa9-c43c8742165c.jpg)

Hope this mockup helps.

**Comment by sftim** [comment]
/reopen
/lifecycle frozen
/retitle Poor alignment between tiles and buttons on home page for docs
