### ISSUE TITLE
Broken link (How to File an Issue)

### ISSUE THREAD

**Issue by stephenrwalli** [kubernetes/website#23964]
**This is a Bug Report**

**Problem:**
"How to file an issue" on the Community page (https://github.com/kubernetes/community/) points to a dead label/page. 

**Proposed Solution:**
Reset the link on the Community page to a useful page. 
(Either https://github.com/kubernetes/community/blob/master/contributors/guide/first-contribution.md#file-an-issue or the Triage page at https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md) 

**Page to Update:**
https://github.com/kubernetes/community/

**Comment by tengqm** [comment]
done.
/close
