### ISSUE TITLE
Nodes created manually never get to Ready Mode

### ISSUE THREAD

**Issue by admiyo** [kubernetes/website#2397]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Following the steps https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/
Node stayed in the NotReady status.

**Proposed Solution:**
Remove the manual node creation using the JSON file.  Nodes will self register and come up properly.

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/

**Comment by Spectrik** [comment]
Hello guys,

unfortunately, this guide [1] still does NOT work. The node never gets ready. I double checked several times. Still the same result. Any suggestions?

Cheers.

[1] https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/
