### ISSUE TITLE
Using Admission Controllers

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#23984]
In the subsection describing the DefaultTolerationSeconds admission controller (https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaulttolerationseconds) it is explained this controller set a 5min tolerationSeconds for each of those tolerations being added by default to a created pod (when not explicitly set).

Those 5 min really comes from the default value in "default-not-ready-toleration-seconds" and "default-unreachable-toleration-seconds" k8s-apiserver input parameters (see https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options).

I think it would be good to add a short comment in the Admission Controller - DefaultTolerationSeconds description saying those 5 min are a default value and that are really controlled by these two k8s-apiserver input params (in the same way the [node documentation](https://kubernetes.io/docs/concepts/architecture/nodes/)  refers to the k8s-controller-manager's pod-eviction-timeout input parameter when referring to the 5 minutes required (by default) for pods running in a faulty node to be evicted)

**Comment by tengqm** [comment]
fixed.
/close
