### ISSUE TITLE
update doc for certificate signing requests

### ISSUE THREAD

**Issue by gaurav517** [kubernetes/website#24008]
**This is a Bug Report**

**Problem:**
Doc is not aligned with latest kubernetes version 1.19.2:
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#create-certificate-request-kubernetes-object

With version 1.19.2, `signerName` is mandatory.
Also signer `kubernetes.io/legacy-unknown` is not supported in the list at: https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

**Proposed Solution:**
Specify `signerName` in yaml definition
Remove `kubernetes.io/legacy-unknown` section

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests

**Comment by tengqm** [comment]
Just checked, the `signerName` is a required field since 1.19.0 in `certificates.v1` group, but it is not required in the `v1beta1` group.
It makes sense to fix the example so that the YAML works.

/sig auth

**Comment by liggitt** [comment]
https://github.com/kubernetes/website/pull/23895 changed the apiVersion without actually updating required fields for v1

**Comment by liggitt** [comment]
cc @christomas1

**Comment by christomas1** [comment]
About proposal "Remove kubernetes.io/legacy-unknown section" of this issue, the v1.19 release notes indicates:

> The CertificateSigningRequest API is promoted to certificates.k8s.io/v1 with the following changes:
> spec.signerName is now required, and requests for **kubernetes.io/legacy-unknown are not allowed** to be created via the certificates.k8s.io/v1 API

Ref: https://kubernetes.io/docs/setup/release/notes/#api-change

@gaurav517 Can you create a PR for this?

**Comment by liggitt** [comment]
The `kubernetes.io/legacy-unknown` documentation should remain until v1beta1 is no longer supported

**Comment by gaurav517** [comment]
I am happy to create a PR, but I am not able to push a branch to this repo. I have already signed CLA but still get:
```
fix_csr_doc> git push
ERROR: Permission to kubernetes/website.git denied to gaurav517.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Any idea? Did I miss something in contribution doc? I will have a look at that again.

**Comment by tengqm** [comment]
push it to your own clone, then use github to raise a pull request.
[detailed guide](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#fork-the-repo)

**Comment by gaurav517** [comment]
Great thanks. PR on the way then. :)
