### ISSUE TITLE
K8s 1.20 - Formalize docs release strategy with the different localization owners

### ISSUE THREAD

**Issue by annajung** [kubernetes/website#24009]
Hello 👋,

I'm Anna Jung, the sig release docs lead for 1.20 release. I'm opening this issue to find the best way to coordinate the actual docs release ([scheduled tentatively for Dec 8th, 2020](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.20#timeline)) with the different localization owners.

A couple of questions:

1. Who would be a good primary contact for the following localization content?
- [X] French (@remyleone )
- [X] German (@mkorbi )
- [X] Hindi (@mittalyashu )
- [x] Indonesian (@irvifa)
- [X] Japanese (@inductor )
- [ ] Russian
- [x] Polish (@mfilocha)
- [X] Korean (@seokho-son )
- [X] Portuguese (@dougsland @jcjesus @femrtnz )
- [X] Spanish (@raelga )
- [x] Chinese (@tengqm)
- [x] Vietnamese (@truongnh1992 )
- [X] Ukrainian (@MaxymVlasov ) 
- [x] Italian (@fabriziopandini)

2. Is there anything we could have done better last release ~(v.1.18)~ (v.1.19)? Any process improvements in mind?

I look forward to working with everyone! Let me know if you have any questions!
Thank you! 🙏

cc: @kubernetes/sig-docs-fr-owners @kubernetes/sig-docs-de-owners @kubernetes/sig-docs-hi-owners @kubernetes/sig-docs-id-owners @kubernetes/sig-docs-ja-owners @kubernetes/sig-docs-ru-owners @kubernetes/sig-docs-pl-owners @kubernetes/sig-docs-ko-owners @kubernetes/sig-docs-pt-owners @kubernetes/sig-docs-es-owners @kubernetes/sig-docs-zh-owners @kubernetes/sig-docs-vi-owners @kubernetes/sig-docs-uk-owners @kubernetes/sig-docs-it-owners

/assign

**Comment by inductor** [comment]
Hey, Japanese owner here.

**Comment by annajung** [comment]
Hi @inductor, nice to meet you! I have added you as the main person to contact for Japanese. Thank you!

**Comment by seokho-son** [comment]
Hello @annajung, I am Korean l10n team leader. :)

**Comment by mkorbi** [comment]
Hey @annajung I can take the German part

**Comment by annajung** [comment]
Hi @seokho-son @mkorbi nice to meet you both! Adding both of your names as the main contact. Thank you!

**Comment by irvifa** [comment]
Hey @annajung you can contact me for ID localization, looking forward to work with you :)

**Comment by dougsland** [comment]
I would volunteer for Portuguese (Brazil) and english as reviewer. However, there is no split between pt-BR and pt-PT. Is this intensionally?

**Comment by irvifa** [comment]
@dougsland I think we’re using the same documentation for both of BR and PT for now, although I’m also aware it’s slightly different for grammar and spelling 🤔

**Comment by dougsland** [comment]
> @dougsland I think we’re using the same documentation for both of BR and PT for now

/me nods @irvifa 

> although I’m also aware it’s slightly different for grammar and spelling

Correct. I think people from pt_BR and pt_PT can understand each other but still there is a difference. If you guys merged the two to save resources (or lack) seems fine.

**Comment by irvifa** [comment]
@dougsland yes probably still can understand each other although the vocabularies can be different, in a way.

Also if we want to separate this I’m not sure if there’s abbreviation for both of that in ISO 639-1 http://www.mathguide.de/info/tools/languagecode.html.

I understand pt-PT and my friends also speak pt-BR as well, more or less I know how it feels 😅

**Comment by dougsland** [comment]
> @dougsland yes probably still can understand each other although the vocabularies can be different, in a way.
> 
> Also if we want to separate this I’m not sure if there’s abbreviation for both of that in ISO 639-1 
> http://www.mathguide.de/info/tools/languagecode.html.

Looks like pt contains a bunch of Portuguese variants.
https://www.localeplanet.com/icu/iso639.html

In others open-source projects, usually these variants has a separate dir, like pt-PT, pt-BR etc. 

> 
> I understand pt-PT and my friends also speak pt-BR as well, more or less I know how it feels

:)

**Comment by irvifa** [comment]
@dougsland you’re right, thanks for the information :)

**Comment by mfilocha** [comment]
@annajung I'm here for Polish team.

**Comment by jcjesus** [comment]
Hi Ana, I am a Portuguese I10n team lead.
Thanks
Best regard!
jcjesus

Em sáb, 19 de set de 2020 11:13, Anna <notifications@github.com> escreveu:

**Comment by tengqm** [comment]
Let me know if anything need to be done for the Chinese (zh) localization.

**Comment by mittalyashu** [comment]
@annajung I am here for Hindi.

**Comment by fabriziopandini** [comment]
@annajung I'm here for Italy

> Is there anything we could have done better last release (v.1.18)? Any process improvements in mind?

It will be great if there is some kind of automation providing signal that the original EN-version for a localized page is changed, so it is easier to keep our localization up to date.

**Comment by irvifa** [comment]
@fabriziopandini I'm and @bradtopol working on the localization subgroups, we can discuss ore about this on the slack channel :)

**Comment by mfilocha** [comment]
@fabriziopandini 
> It will be great if there is some kind of automation providing signal that the original EN-version for a localized page is changed, so it is easier to keep our localization up to date.

I use a simple one-liner from my localization root dir (e.g. _content/pl_):
`for i in $(find * -type f) ; do git diff commit_hash master -- ../en/$i ; done`
where _commit_hash_ is the hash of a commit when my previous sync was done.

But I agree with you it'd be good to have something more automated.

**Comment by annajung** [comment]
Hello @irvifa @dougsland @mfilocha @jcjesus @tengqm @mittalyashu @fabriziopandini ! Super nice to meet everyone here and I'm also looking forward to working with you all. Your names have been added as the main contact for corresponding localization!

-- 

>What kind of improvements?

@mittalyashu, using last release as an example, as a current release lead, I wanted to get your feedback on anything that could have gone better. So that if needed, we can improve our process for the current release and future releases 😀

-- 

> However, there is no split between pt-BR and pt-PT. Is this intensionally?

@dougsland @irvifa I'm not sure if any action is required here based on the discussion above? If there's anything I can do to help out, please let me know! 

-- 

> It will be great if there is some kind of automation providing signal that the original EN-version for a localized page is changed, so it is easier to keep our localization up to date.

@fabriziopandini @irvifa I think brining this up in the new localization subgroup is a great idea. I'll be happy to join the group to further discuss this problem and learn how we can make it easier to keep our localization up to date in the future!

**Comment by mfilocha** [comment]
@annajung I guess you are aware of https://github.com/kubernetes/website/issues/20624? Do you think we need to refresh contact list with every release?

**Comment by raelga** [comment]
Count me in for the Spanish team.

**Comment by annajung** [comment]
>@annajung I guess you are aware of #20624? Do you think we need to refresh contact list with every release?

Hi @mfilocha Yes, I am aware of the issue(s) that were opened for previous releases that collects the same contact list. This is actually a step described in the role handbook for the sig release docs lead (https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/docs#introduce-yourself). I'm happy to discuss modifying the role handbook if people don't see value in doing this for every release. 

I understand that the contact list will not drastically change. However, some do change and I'm actually not sure what the best way to keep everyone in sync for the release without this process. Do you have any suggestions? I'm happy to bring this up in Sig Docs meeting tomorrow as well to discuss if there an alternative way we can produce the same result. 😀

**Comment by annajung** [comment]
Hi @raelga, Thank you! nice to meet you! I have added you as the main person to contact for Spanish.

**Comment by annajung** [comment]
Hey @mfilocha, I was thinking about what you said a bit more. What do you think about modifying the role handbook to say, use the last release's contact sheet to confirm the main contact for each localization for the current release?

Instead of pinging all owners, then release docs lead can just ping individuals who have volunteered last release and asked them to confirm if they're the still main contact. 

I think having an issue to keep track of main contact is still valuable, but maybe we don't have to ping the whole group again every release? 

I guess this is question for everyone here! Which approach do you think we should use moving forward?
1. no change, create an issue, ping all localization owners for main contact info
2. reuse the last release's list of main contact, create an issue, ping all main contact from last release for confirmation
3. other? (If you have a better approach, I would love to hear from you!)

**Comment by seokho-son** [comment]
@annajung 
As the Korean l10n team leader, I prefer the first approach because the main contact may change periodically.
However, I think we don't need to survey the main contact list for every releases. We can reuse the previous contact list as a base contact list.

How about keep using the first approach (create an issue, ping all localization owners for main contact info). 
And reuse the previous contact list, when a sig release docs lead open the issue.
I think you can check weather the base contact list needs to be updated or not by pinging to all localization owners.

**Comment by mittalyashu** [comment]
@annajung I was checking the docs site for Hindi language, didn't see the language in the list, even visiting the page `https://kubernetes.io/hi/` shows 404.

<img width="217" alt="Screenshot 2020-09-24 at 8 26 38 AM" src="https://user-images.githubusercontent.com/29014463/94095721-f2e96c00-fe3f-11ea-929d-fe8c4f7f5b61.png">

Was it removing due to lack of active contributions or some other reason?

**Comment by annajung** [comment]
Hey @seokho-son that sounds great! That's what I was going trying to go for in the second option, but I clearly did not explain correctly. I think we can try that for the next release and see how that goes! I'll leave it for a few days to give everyone a chance to weigh in and then make changes

**Comment by annajung** [comment]
>@annajung I was checking the docs site for Hindi language, didn't see the language in the list, even visiting the page https://kubernetes.io/hi/ shows 404.

>Was it removing due to lack of active contributions or some other reason?

Hey @mittalyashu, I'm not sure why that's the case, I'm going to ask @zacharysarah @jimangel @sftim to chime in here

**Comment by dougsland** [comment]
Hi @annajung 

> @dougsland @irvifa I'm not sure if any action is required here based on the discussion above? If there's anything I can do to
> help out, please let me know!
 
I believe we are all set. In the slack people complain there is no much people helping in translation to have multiple teams.
Thanks!

**Comment by mfilocha** [comment]
>  What do you think about modifying the role handbook to say, use the last release's contact sheet to confirm the main contact for each localization for the current release?

@annajung More general question is - do we really need to refresh (no matter which way) contact list every release?
My understanding is that you, as the docs lead, may want to contact people involved in localization tasks mainly for two reasons:
- to communicate release steps important for docs contributors
- to gather feedback

Why not to use general mentions like you did in the beginning of this thread and/or recently created Slack channel (_sig-docs-localizations_)?

**Comment by jimangel** [comment]
> @annajung I was checking the docs site for Hindi language, didn't see the language in the list, even visiting the page https://kubernetes.io/hi/ shows 404.

@mittalyashu it appears many of the Hindi localization PRs / issues have closed without merging (example: [1](https://github.com/kubernetes/website/issues/13914), [2](https://github.com/kubernetes/website/pull/14069)) due to inactivity. If you feel this was done in error, please bring it up on the Kubernetes Slack or re-open the pull requests to address feedback. The Kubernetes SIG Docs Slack would be a great place to ask for feedback if needed.

> @annajung More general question is - do we really need to refresh (no matter which way) contact list every release?

This is good feedback @mfilocha. Prior to the 1.12 release or so, the localization teams were not included with each release and caused a lot of confusion for branching and updating docs each release. This is more of an informal effort to connect with each lead of the localization to introduce themselves and announce the new release.

The _sig-docs-localizations_ channel is a working group which will ultimately go away after completion. Do you, or anyone, have an alternative way to stay connected each release cycle?

**Comment by MaxymVlasov** [comment]
@annajung you can count on me in Ukrainian localization

**Comment by annajung** [comment]
Hi @MaxymVlasov nice to meet you! I have added you as the main person to contact for Ukrainian.

**Comment by femrtnz** [comment]
Hi @annajung, just added me as a contact for Portuguese as well 👍

**Comment by annajung** [comment]
Hi @inductor @seokho-son @mkorbi @irvifa @dougsland @mfilocha @jcjesus @tengqm @mittalyashu @fabriziopandini @raelga @MaxymVlasov @femrtnz @remyleone @truongnh1992 

1.20 release day is coming up in a few days: **Tue December 8th** (Exact time is still being discussed, my best guess would be early morning PST)

**24 hours before the release, Monday December 7th (Morning PST), I will freeze the repo.** This means, no PRs will be merged at all until the release PR has successfully merged

We're currently on track for the release, but in case anything happens to delay the release, I will update you all. 

If you have any concerns, please let me know! Thank you!

**Comment by annajung** [comment]
Hi All, Kubernetes v1.20.0 has been successfully released!
The website repo is officially THAWED!

Thank you for all your feedback about the process, I'll make a note of it in the [docs handbook](https://github.com/kubernetes/sig-release/tree/master/release-team/role-handbooks/docs) for the next release. 

If you have any feedback, Sig Docs and 1.20 docs release team are planning to have a short retro during the next SIg Docs meeting. If you can't make it, please leave your comment in the thread https://kubernetes.slack.com/archives/C1J0BPD2M/p1607456029085000

Thank you!
