### ISSUE TITLE
Installing Kubernetes with Minikube

### ISSUE THREAD

**Issue by TommyQuality** [kubernetes/website#24007]
Trying to get minikube running on Windows 10 Hyper-V 

When I run minikube starts it created the VM in hyper-v, but when it tries to connect using `kubectl get pod` it returns the following error

`Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.`

It looks like the config file in .kube\ is not being updated, as it contains no data.

I've tried setting the environment variables to different locations to see if it's a permissions issue. but still getting the same error.

**Comment by markyjackson-taulia** [comment]
@TommyQuality 5ths isu could be opened here https://github.com/kubernetes/minikube

**Comment by markyjackson-taulia** [comment]
kindly open issue here https://github.com/kubernetes/minikube

/close
