### ISSUE TITLE
Installing Addons

### ISSUE THREAD

**Issue by pgoyal01** [kubernetes/website#24029]
Under "Caution" section, the link " content guide (https://kubernetes.io/contribute/style/content-guide/#third-party-content)" is broken

**Comment by kbhawkey** [comment]
/kind bug

The correct link should be:
https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content

**Comment by Arhell** [comment]
@pgoyal01  done
can be closed

**Comment by pgoyal01** [comment]
Issue Fixed
