### ISSUE TITLE
Say bye to PodPreset

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#24038]
[PodPreset is gone](https://github.com/kubernetes/kubernetes/pull/94090)

Need change to doc:

- remove PodPreset pages
- provide alternatives where PodPreset was referenced

**Comment by sftim** [comment]
The PR to remove https://kubernetes.io/docs/concepts/workloads/pods/podpreset/ should target milestone (and Kubernetes release) *1.20*

**Comment by sftim** [comment]
/priority important-soon
/good-first-issue

This is mostly about deleting the page https://kubernetes.io/docs/concepts/workloads/pods/podpreset/ (from the English documentation only - localizations will cover the update in separate PRs).

In the pull request for this revision, mention that this change is for milestone 1.20

**Comment by sftim** [comment]
Actually, this is a _bit_ more fiddly than I'd anticipated - the documentation change needs to target the v1.20 release.
/remove-good-first-issue

**Comment by sftim** [comment]
[Goodbye!](https://github.com/kubernetes/website/pull/25238)
/close

Thanks @jlsong01
