### ISSUE TITLE
Chinese page https://kubernetes.io/zh/docs/tasks/extend-kubernetes/configure-aggregation-layer/ link error

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#24055]
**This is a Bug Report**

**Problem:**
Link in page https://kubernetes.io/zh/docs/tasks/extend-kubernetes/configure-aggregation-layer/ direct to English version page.

**Proposed Solution:**
Change link to chinese version page.

**Page to Update:**
https://kubernetes.io/zh/docs/tasks/extend-kubernetes/configure-aggregation-layer/

**Comment by tengqm** [comment]
This has been fixed.
/close
