### ISSUE TITLE
Clarify toleration timeouts for kube-apiserver

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#24053]
I understand the values to assign to "--default-not-ready-toleration-seconds" and "--default-unreachable-toleration-seconds" options in kube-apiserver should be equal or lower than the value assigned to "--pod-eviction-timeout" option in [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/), not making sense to add a greater value for those two kube-apiserver options
(note default value for all three is 5 min / 300 seconds)

If being right here I think it would be good to add this clarification in the section for each of these two kube-apiserver options (i.e. "--default-not-ready-toleration-seconds" and "--default-unreachable-toleration-seconds")

**Comment by antaloala** [comment]
As there are not comment related to this issue I wonder if it is because
- no one share my reasoning (about the relationship between these two kube-apiserver options ("--default-not-ready-toleration-seconds" and "--default-unreachable-toleration-seconds") and the "--pod-eviction-timeout" option in kube-controller)
- it is not clear enough
- others?

**Comment by sftim** [comment]
@antaloala could you explain which web page(s) you're discussing here? You didn't mention that yet.

**Comment by sftim** [comment]
It might be that you're asking about changes to the help text that is built in to Kubernetes components. If so, you should request that [upstream](https://github.com/kubernetes/kubernetes/).

**Comment by antaloala** [comment]
Sorry @sftim for the delay.
I am referring (ops, I did not realize I forgot to include it, sorry also about this) to the doc about the built-in  DefaultTolerationSeconds admission plugin: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaulttolerationseconds

**Comment by antaloala** [comment]
What do you think then on adding some clarification to explain that the values to set for these input parameters in kube-apiserver and kube-controller-manager must be properly related (i.e. values to assign to "--default-not-ready-toleration-seconds" and "--default-unreachable-toleration-seconds" options in kube-apiserver should be **equal or lower** than the value assigned to "--pod-eviction-timeout" option in kube-controller-manager) ?

**Comment by tengqm** [comment]
The upstream code is here: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/defaulttolerationseconds/admission.go#L35-L41

The reference doc are generated from the upstream source code, so please propose your fix to the upstream repo.
