### ISSUE TITLE
Document how to deprovision a kubeadm cluster

### ISSUE THREAD

**Issue by sakaia** [kubernetes/website#24067]
It is helpful to document the removing kubernetes cluster previously for scratch installation for kubeadm case.

**Comment by RA489** [comment]
@sakaia does `kubeadm reset` doesn't help?

**Comment by RA489** [comment]
Kubeadm doesn't  provisions machine for you.

**Comment by sakaia** [comment]
Thank you for commenting.

In my understanding, `kubeadm init/join` sets up  is reset by `kubeadm reset`.
For usual cases CNI  and other packages are deployed. Is this  also needed to remove previously?

**Comment by sftim** [comment]
BTW improvements to that page should be first made to https://k8s.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/ and then copied to downstream localizations such as Japanese.

/retitle Document how to deprovision a kubeadm cluster
/kind feature
/sig cluster-lifecycle
/priority awaiting-more-evidence

SIG Cluster Lifecycle, feel free to /triage accepted and prioritize based on relevance.

**Comment by neolit123** [comment]
i don't think an action here is required.
it is obvious that once you installed kubeadm on a node you can just, `kubeadm reset` and uninstall the installed files (either using `rm`, or the host package manager). this also applies to kubernetes-cni.

**Comment by sftim** [comment]
Agreed.

@sakaia I'm going to close this. The cloud-native approach to this is to wipe the machine or terminate it. `kubeadm reset` is also available and documented.
/close
