### ISSUE TITLE
“Install and Set Up kubectl” suggests installing from snap with classic confinement

### ISSUE THREAD

**Issue by tdsan** [kubernetes/website#24078]
snap install kubectl --classic

Per certain security requirements, the ubuntu system displayed an error message where it was not recommended doing it this way.

error: This revision of snap "kubectl" was published using classic confinement and thus may
       perform arbitrary system changes outside of the security sandbox that snaps are usually
       confined to, which may put your system at risk.

       If you understand and want to proceed repeat the command including --classic.

Please be advised, or at least per your instructions.

Todd

**Comment by Kartik494** [comment]
Hi @tdsan i think there is a link for installing kubectl on Linux [here](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux) , and you wanted to remove the installation from snap command or here you guide to not use  --classic while using snap command ?

**Comment by sftim** [comment]
Hi @tdsan 

I'm also not sure what you're asking for. Perhaps you wanted the page to mention that the command that's documented installs `kubectl` without Snap sandboxing, and to document that this is a current limitation of the official Snap package.
Does that sound right?
/triage needs-information
/sig cli
/language en

**Comment by tdsan** [comment]
snap install kubectl --classic

I think per the installation instructions, (it has been a while since I reviewed docs) but it was a reference to the issues found using the --classic flag (security concerns).

I think that is what I was referring to (the error message came directly from the system I was looking to install). 

Todd

**Comment by tdsan** [comment]
I was referring to the security issues found when installing kubectl with the --classic flag.

I gave the error from the computer system.

Todd

**Comment by sftim** [comment]
PR https://github.com/kubernetes/website/pull/7669 documents that you must run `snap` with `--classic`. If you do, the error:
```
error: This revision of snap "kubectl" was published using classic confinement and thus may
perform arbitrary system changes outside of the security sandbox that snaps are usually
confined to, which may put your system at risk.

If you understand and want to proceed repeat the command including --classic.
```
is *not* shown.

/triage not-reproducible
/remove-triage needs-information

**Comment by sftim** [comment]
@tdsan if you want to request that the Ubuntu project packages `kubectl` with proper (non legacy) snap confinement, you could visit https://forum.snapcraft.io/ and discuss logging a feature request for that.

**Comment by sftim** [comment]
/retitle “Install and Set Up kubectl” suggests installing from snap with classic confinement
