### ISSUE TITLE
shell-demo.yaml not suitable for general use?

### ISSUE THREAD

**Issue by carlpett** [kubernetes/website#24072]
**This is a Bug Report**

**Problem:**
#14892 made shell-demo.yaml, included in the ["how to get a shell in the cluster" doc](https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/), run with host networking.
This seems like an unwise first suggested configuration for someone who needs a shell in a cluster? In part because cluster-admins may have forbidden `hostNetwork: true` in many cases, and in part because if the cluster-admin _hasn't_, a lot of people will open up ports to the internet (default managed Kubernetes offerings tend to have public IPs on all nodes). 
Additionally, the configuration will lead to the pod being unable to resolve cluster.local names.

And finally, I believe the rationale for adding it in the first place was dependent on configuration errors on the user's side? Non-host networked pods should be able to resolve external DNS.

**Proposed Solution:**
Revert #14892

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

**Comment by sftim** [comment]
/sig security
(does this work?)
