### ISSUE TITLE
Translate docs\setup\release (k8s 1.19 release notes) into Korean

### ISSUE THREAD

**Issue by bluefriday** [kubernetes/website#24091]
**This is a Feature Request**

**What would you like to be added**

Translate docs\setup\release (k8s 1.19 release notes) into Korean
**Why is this needed**
There is no docs about docs\setup\release (k8s 1.19 release notes) in Korean
**Comments**

https://kubernetes.io/docs/setup/release/notes/

*v1.19.0-rc.x 파트의 번역을 제외한 v1.19.0 파트를 번역해보겠습니다.
(I'd like to translate the v1.19.0 part, excluding the translation of the v1.19.0-rc.x part.)

**Comment by viveksahu26** [comment]
hey @bluefriday , i don't know korean language but if you don't mind i will translate it with the help of Google translator, if you assign me..

**Comment by bluefriday** [comment]
@viveksahu26  The translation work is almost done.
I'll PR soon :D
