### ISSUE TITLE
Issue with https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by kngoyal** [kubernetes/website#24108]
**This is a Bug Report**

**Problem:**
I am following the above interactive tutorial on Exposing a deployed App outside the cluster on a minikube cluster hosted on my local machine running macOS. 

I am able to successfully create the deployment using the command `kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1`

```
➜  kubectl get deployments
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
kubernetes-bootcamp   1/1     1            1           2m
```

Also successfully expose the deployment as a `NodePort` service with the command `kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080`

```
 ➜  kubectl get services
NAME                  TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
kubernetes            ClusterIP   10.96.0.1    <none>        443/TCP          5m
kubernetes-bootcamp   NodePort    10.98.9.69   <none>        8080:31961/TCP   1m
```

However, running the command `curl $(minikube ip):$NODE_PORT` errors to `curl: (7) Failed to connect to 127.0.0.1 port 31961: Connection refused`

An observation:
- `minikube ip` on my local machine is `localhost (127.0.0.1)` while in the simulated environment on the webpage it is `172.17.0.25`.

**Possible Solution:**
Explicitly create a tunnel from host machine to the pod running the application by executing the following command.
```
➜  minikube service kubernetes-bootcamp
|-----------|---------------------|-------------|-------------------------|
| NAMESPACE |        NAME         | TARGET PORT |           URL           |
|-----------|---------------------|-------------|-------------------------|
| default   | kubernetes-bootcamp |        8080 | http://172.17.0.2:31961 |
|-----------|---------------------|-------------|-------------------------|
🏃  Starting tunnel for service kubernetes-bootcamp.
|-----------|---------------------|-------------|------------------------|
| NAMESPACE |        NAME         | TARGET PORT |          URL           |
|-----------|---------------------|-------------|------------------------|
| default   | kubernetes-bootcamp |             | http://127.0.0.1:51968 |
|-----------|---------------------|-------------|------------------------|
🎉  Opening service default/kubernetes-bootcamp in default browser...
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```
And now in a new terminal it successfully pings the service on the new exposed port 51968 instead of 31961
```
➜  curl $(minikube ip):51968
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-fb5c67579-cddf7 | v=1
```

Shouldn't the NodePort already have exposed the deployment on the port `31961` to the host machine ?

**Comment by sftim** [comment]
It sounds like https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/ should clearly let you know that you might need to run `minikube service` if you're following along at home.

@kngoyal is that the nub of this issue?
