### ISSUE TITLE
Content not related with main topic (Imperative Management of Objects Using Configuration Files)

### ISSUE THREAD

**Issue by andrescaroc** [kubernetes/website#24107]
Hello, 

I am learning about k8s object management and their differences:

1. Imperative commands
2. Imperative object configuration
3. Declarative object configuration

But I found that there is a **block of content that is not related** with those topics in two of these documentation pages.

**Title** of the block of content that is not related: **Defining controller selectors and PodTemplate labels**
**Image** of the block of content that is not related:
![Screen Shot 2020-09-24 at 12 41 22 PM](https://user-images.githubusercontent.com/38670654/94180288-618bf100-fe63-11ea-8065-a31c06d7c597.png)

[Link #1](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-config/#defining-controller-selectors-and-podtemplate-labels) of the block of content that is not related

[Link #2](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#defining-controller-selectors-and-podtemplate-labels) of the block of content that is not related

Suggested page to move the mentioned block of content: [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

**Comment by sftim** [comment]
/kind cleanup

I'm (still) not sure that this page is the right home for that text.
/triage accepted
/language en
/priority backlog
