### ISSUE TITLE
“Full screen” button not working as expected for katakoda tutorials

### ISSUE THREAD

**Issue by abhijeetnijampurkar** [kubernetes/website#24117]
I can't fullscreen the tutorial window and terminal as a whole. When I click on the maximize button on terminal window, the tutorial part should also show up along with the terminal.

**Comment by Kartik494** [comment]
Hi @abhijeetnijampurkar could you provide link  in which interactive tutorial you are facing this issue?

**Comment by sftim** [comment]
/retitle “Full screen” button not working as expected for katakoda tutorials

@BenHall this might be relevant to you
/kind bug
/priority backlog
/triage accepted

**Comment by BenHall** [comment]
Thanks for the feedback. This is expected behaviour, however I can see that when Katacoda is embedded there is a motivation to keep the step information at the side. 

I will share the feedback internally and see what can be done.

**Comment by sftim** [comment]
/label team/katacoda
/reopen

Maybe this does need work?
