### ISSUE TITLE
is there a step by step guide to override the max-endpoints-per-slice after kubernetes install

### ISSUE THREAD

**Issue by prabirkumardhar** [kubernetes/website#24123]
Hi Team
I need to change the max-endpoints-per-slice parameter of kube-controller-manager to 150 or 200 as it is needed for the app. Is there a way to change this value after the installation?

**Comment by sftim** [comment]
> is there a step by step guide to override the max-endpoints-per-slice after kubernetes install

At this point in time, there is no step by step guide to do this.

/kind support
