### ISSUE TITLE
No page content for https://k8s.io/docs/reference/kubectl/kubectl-cmds/

### ISSUE THREAD

**Issue by nagajagan** [kubernetes/website#24133]
A page just to provide a link another page? 
My be you are planning more links on this page. 
If not this page it self can point to target page.

**Comment by Kartik494** [comment]
Hi @nagajagan in this [Link](https://kubernetes.io/docs/reference/kubectl/kubectl-cmds/) there is another link reference to kubectl commands refrence , so far i am understanding is that you want to replace reference Link for kubectl command to be in this [page](https://kubernetes.io/docs/reference/kubectl/kubectl-cmds/) ?

**Comment by sftim** [comment]
To fix this, edit [`static/_redirects`](https://github.com/kubernetes/website/blob/master/static/_redirects) so that it redirects readers to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

/good-first-issue
/language en

**Comment by sftim** [comment]
/retitle No page content for https://k8s.io/docs/reference/kubectl/kubectl-cmds/

**Comment by jlsong01** [comment]
hi @sftim, could you help to review the PR? Thanks

**Comment by sftim** [comment]
@jlsong01 reviewers (who are mainly volunteers) pick up that task on a [rota](https://github.com/kubernetes/website/wiki/PR-Wranglers). I can take a look though.

**Comment by jai** [comment]
@sftim I added the redirect (https://github.com/kubernetes/website/pull/27904) but it doesn't seem to be working on the deploy preview or locally. Any advice would be appreciated:

```
/docs/reference/kubectl/kubectl-cmds/    https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands/ 301
```
