### ISSUE TITLE
Reference docs for "kubectl create deployment" command

### ISSUE THREAD

**Issue by andrescaroc** [kubernetes/website#24137]
**This is a Bug Report**

**Problem:**
The mentioned page (link bellow) contains flags that are not available for the following command:

$ kubectl create deployment NAME --image=image -- [COMMAND] [args...]

Flags that are not available for this command:
--replicas
--port

The same page, provides two examples using those flags that don't work either:

Example1:
> Create a deployment named my-dep that runs the nginx image with 3 replicas.
`kubectl create deployment my-dep --image=nginx --replicas=3`

Example 2:
> Create a deployment named my-dep that runs the busybox image and expose port 5701.
`kubectl create deployment my-dep --image=busybox --port=5701`

**Proposed Solution:**
Remove those flags for this command and remove those examples

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-deployment-em-

Additional Information:
Could someone give me home hints on how to edit those reference pages?

**Comment by sftim** [comment]
@andrescaroc can you check that you're looking at the right version of the documentation?

`kubectl version` shows you what version of Kubernetes you are using. The top-right of https://k8s.io/ has a selector to choose between different versions of the documentation.

/triage needs-information

**Comment by sftim** [comment]
No worries @andrescaroc 

/remove-triage needs-information
/triage support
/close
