### ISSUE TITLE
Add documentation for service.beta.kubernetes.io/aws-load-balancer-eip-allocations annotation (AWS NLB)

### ISSUE THREAD

**Issue by jicowan** [kubernetes/website#24135]
The issue is documented here, https://github.com/kubernetes/kubernetes/pull/69263.  
The annotation accepts an array of allocation IDs, 1 per subnet.  This allows you to associate a set of static IPs (EIPs) with a network load balancer (NLB).

**Comment by sftim** [comment]
This sounds like it wouldn't fit in with the spirit of the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/) @jicowan.

A better approach would be to document that annotation in AWS' documentation, and then _hyperlink_ to the cloud provider's own docs if appropriate. Does that approach seem valid?
/sig cloud-provider

**Comment by jicowan** [comment]
@sftim I'm not sure.  There are already several AWS specific annotations present in the k8s documentation, e.g. https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support.  I agree it should appear in the AWS's documentation, but I also think it's worth putting here while the NLB is still part of the cloud controller.

**Comment by sftim** [comment]
I would really like to slim down https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support _considerably_ - however, if the existing page is inaccurate then it's OK to PR a fix.
