### ISSUE TITLE
Creating a cluster with kubeadm

### ISSUE THREAD

**Issue by Ajay2307** [kubernetes/website#24134]
Hi Folks!

Not able to find the CNI deployment template in the documentation.
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

Please update. 

So that it will be easy for everyone to get a valid and supported network plugin.

**Comment by neolit123** [comment]
Hi. The CNI examples were removed intentionally and we will not add them back. The kubeadm page now links to the page with the list of CNIs.

/sig cluster-lifecycle
/triage support
/close
