### ISSUE TITLE
Translate docs/tasks/job/coarse-parallel-processing-work-queue.md into Korean

### ISSUE THREAD

**Issue by JonghunBok** [kubernetes/website#24150]
**This is a Feature Request**

**What would you like to be added**

Translate docs/tasks/job/coarse-parallel-processing-work-queue.md into Korean

**Why is this needed**
Cannot find docs/tasks/job/coarse-parallel-processing-work-queue.md in Korean
**Comments**

The page to update:
https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/

**Comment by gochist** [comment]
Fixed in #24218 
/close
