### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by mingwei-li** [kubernetes/website#24154]
What is `kustomization`? Why is there `volumeMounts` and `volumes`? What is all the config key, name, path, file all over `kustomization.yml` and `redis-pod.yml`? How do they refer to each other? What are the naming conventions? If I as a beginner following the tutorial and get to this page for the first time, I'm 1000% lost of all the configuration nuances all over the place. If you really want to write a good tutorial documentation, explain more and expect your readers know nothing other than the tutorial pages before this one.

**Comment by tengqm** [comment]
Thanks for filing an issue.
Any suggestions you can provide?
Any PRs you can help commit?

**Comment by sftim** [comment]
@mingwei-li you noticed several ways that someone could improve [Configure Redis using ConfigMap](https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/).

Would you be willing to open an issue about each of those? That would help other people to identify and act on your suggestions.
