### ISSUE TITLE
Cleaning up org teams / owners / owners_aliases permissions

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#24170]
This issue is to track a couple PRs that accomplish the following:

- From [`k/org/blob/master/config/kubernetes/sig-docs/teams.yaml`](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml)
  - Remove @xiangpengzhao as a reviewer or approver (welcome back at any time and may reference this issue)
  - Remove @bradamant3 as a reviewer or approver with write access (welcome back at any time and may reference this issue)
  - Remove @steveperry-53 as a reviewer or approver with write access (welcome back at any time and may reference this issue)
  - Remove @jaredbhatti as a reviewer (welcome back at any time and may reference this issue)
- From [`k/website/blob/master/OWNERS`](https://github.com/kubernetes/website/blob/master/OWNERS)
  - Add @steveperry-53 as commented out emeritus
- From [`k/website/blob/master/OWNERS_ALIASES`](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES)
  - Remove @xiangpengzhao as a reviewer or approver (welcome back at any time and may reference this issue)

**Comment by irvifa** [comment]
@jimangel I'm curious whether we do periodic check for this as part of clean up or this is possible?
