### ISSUE TITLE
Certificate Management with kubeadm

### ISSUE THREAD

**Issue by zgfh** [kubernetes/website#24189]
```
alpha certs renew uses the existing certificates as the authoritative source for attributes (Common Name, Organization, SAN, etc.) instead of the kubeadm-config ConfigMap. It is strongly recommended to keep them both in sync.
```
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#automatic-certificate-renewal

This confuses me,I thought I could not use this command, and I don't know how to keep them in sync.
should we add the method  how to keep them in sync ?

**Comment by neolit123** [comment]
the note says the properties of the certs on disk (such as SAN) will be used for generating the new certs.
to "keep them in sync" means that if you generated custom certs using your own process, make sure that e.g. kubeadm-config (ConfigMap) -> ClusterConfiguration -> apiServer -> extraSANs matches the SANs in the kube-apiserver certficate.

but IIRC, `kubeadm ... certs renew` fetches the kubeadm ClusterConfiguration before renewing if it can, so the above message seems false / out of date.

/assign @fabriziopandini 
to double check my understanding.

/triage support
/sig cluster-lifecycle

**Comment by fabriziopandini** [comment]
/remove-lifecycle stale

@neolit123 sorry for the late answer but this got somehow out of my radar. 

If I follow the code right, we are still reading certificates details from disk at 

https://github.com/kubernetes/kubernetes/blob/ff4234720d4ec390ca6f6aac4c19a21ba6661841/cmd/kubeadm/app/phases/certs/renewal/manager.go#L220

and then using that to build the certificate config at

https://github.com/kubernetes/kubernetes/blob/ff4234720d4ec390ca6f6aac4c19a21ba6661841/cmd/kubeadm/app/phases/certs/renewal/manager.go#L227

**Comment by neolit123** [comment]
I guess we can close this then.
The IIRC part of my message above is not correct.

/close
