### ISSUE TITLE
使用 PodPreset 将信息注入 Pod

### ISSUE THREAD

**Issue by gaosong030431207** [kubernetes/website#24192]
【环境变量】 连接点击失效

**Comment by howieyuen** [comment]
could you please be more specific? I cannot find the broken link...

**Comment by gaosong030431207** [comment]
> could you please be more specific? I cannot find the broken link...
if you enter [https://kubernetes.io/zh/docs/tasks/inject-data-application/podpreset/],  you can see next describtion:
本页展示如何在创建 Pod 时 使用 PodPreset 对象将类似 Secret、卷挂载和 **环境变量** 这类信息注入到 Pod 中.  
and you click  ‘环境变量’ ， the link is broken

**Comment by howieyuen** [comment]
thank you, I'm fixing it now ~
