### ISSUE TITLE
Translate  docs/tasks/extend-kubernetes/setup-konnectivity.md into Chinese

### ISSUE THREAD

**Issue by CriaHu** [kubernetes/website#24207]
This is a Feature Request

What would you like to be added

Translate docs/tasks/extend-kubernetes/setup-konnectivity.md into Chinese

Why is this needed
Cannot find docs/tasks/extend-kubernetes/setup-konnectivity.md in Chinese
Comments

The page to update:
https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

**Comment by tengqm** [comment]
Done. (31aa397284e4c777ade95c94ff7c3b89d0a280bd)
/close
