### ISSUE TITLE
Remove legacy site map

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24228]
**This is a cleanup request**

**What would you like to be added**
Remove the page https://kubernetes.io/docs/sitemap/

**Why is this needed**
- The site map at https://kubernetes.io/docs/sitemap/ does not work as expected. There are no dropdowns.
- This page is not linked from other pages.

Also: since the [switch to Docsy](https://github.com/kubernetes/website/pull/20874) the navigation provided by the theme seems good enough. There is also a [machine-readable sitemap](https://k8s.io/sitemap.xml) to help crawlers.

**Comments**
/kind cleanup
/language en
/priority backlog

**Comment by roshnaeem** [comment]
Hey @sftim , I want to work on this issue. Can you tell me how do I have to delete this page?

**Comment by roshnaeem** [comment]
I have forked the project. Do I have to run the project to get that delete icon?

**Comment by sftim** [comment]
@roshnaeem if you look at https://github.com/roshnaeem/website/blob/master/content/en/docs/sitemap.md I suspect you'll see that icon; here's a screenshot:
![GitHub web UI delete file icon](https://user-images.githubusercontent.com/22591623/94704436-d4034200-0337-11eb-9dbf-69aeda74f08f.png)

**Comment by roshnaeem** [comment]
oh yeah, i saw that. I thought maybe I have to delete it from a running project. Let me open a pull request.

**Comment by roshnaeem** [comment]
kindly check my PR @sftim  https://github.com/kubernetes/website/pull/24270
