### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by BrettPhilip** [kubernetes/website#24227]
Getting Connection error using Interactive tutorial

kubectl cluster-info dump
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by sftim** [comment]
Hi @BrettPhilip 

I think this issue is about the page at https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

Are those symptoms still occurring?

/priority awaiting-more-evidence
