### ISSUE TITLE
Web UI (Dashboard)

### ISSUE THREAD

**Issue by vipup** [kubernetes/website#24254]
After step: "Kubectl will make Dashboard available at"  :( What should I do FTW?
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 10.244.1.49:8443: i/o timeout",
  "code": 500
}

**Comment by celestehorgan** [comment]
Hi @vipup, could you please provide us the URL of page that this code snippet is on?

/priority awaiting-more-evidence
