### ISSUE TITLE
FIx link for operator framework document

### ISSUE THREAD

**Issue by seongpyoHong** [kubernetes/website#24266]
**This is a Bug Report**

**Problem:** In `docs/concepts/extend-kubernetes/operator`, link for Operator Framework is deprecated.  

**Proposed Solution:** 
Change URL https://github.com/operator-framework/getting-started to https://operatorframework.io
 
**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/

**Comment by sftim** [comment]
/language en
/kind cleanup
/priority backlog
/help

_Kubernetes is not taking part in Hacktoberfest_

**Comment by seongpyoHong** [comment]
Merged #24286
