### ISSUE TITLE
ja-trans: Move content/ja/docs/concepts/configuration/assign-pod-node.md to content/ja/docs/concepts/scheduling-eviction/assign-pod-node.md

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#24265]
**This is a Feature Request**

**What would you like to be added**

- Please move  the content/ja/docs/concepts/configuration/assign-pod-node.md document to content/ja/docs/concepts/scheduling-eviction/assign-pod-node.md

- Please fix link to this japanese assign-pod-node.md page.
https://github.com/kubernetes/website/commit/55e17b86f268366fc4654c594356c13b7cb94681#diff-65db3915b9b142dee8ed8cbc3306a5fb

**Why is this needed**
Because the original English document of docs/concepts/configuration/assign-pod-node.md was moved to  docs/concepts/scheduling-eviction/assign-pod-node.md

**Comments**

/language ja
/good-first-issue
## Note 
Please create branch from `dev-1.18-ja.1`

The file to move.
https://github.com/kubernetes/website/blob/a4dd5b91c56d8ebb9218b4dd4b473e156ae66a04/content/ja/docs/concepts/configuration/assign-pod-node.md

The original page of assign-pod-node.md
https://github.com/kubernetes/website/blob/55e17b86f268366fc4654c594356c13b7cb94681/content/en/docs/concepts/scheduling-eviction/assign-pod-node.md

**Comment by Evalle** [comment]
I think I can help with that /assign

**Comment by inductor** [comment]
@kakts 1.18ブランチで作って欲しい旨が抜けてます

**Comment by Evalle** [comment]
Closed in favor of https://github.com/kubernetes/website/pull/24314
