### ISSUE TITLE
Init Containers

### ISSUE THREAD

**Issue by sacgoel** [kubernetes/website#24318]
In 'Understanding init containers' section, document states the below:
_If a Pod's init container fails, Kubernetes repeatedly restarts the Pod until the init container succeeds. However, if the Pod has a restartPolicy of Never, Kubernetes does not restart the Pod._
But as I understand, it's not a Pod that can be restarted rather it's the container which will get restarted. Please review..

**Comment by sftim** [comment]
`restartPolicy` is indeed the _container_ restart policy for the Pod.

I suggest changing https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ to use this replacement text:
> If a Pod's init container fails, the kubelet repeatedly restarts that init container it container succeeds. However, if the Pod has a `restartPolicy` of Never, and an init container fails during startup of that Pod, Kubernetes treats the overall Pod as failed.

/language en
/sig node
/kind bug
/priority backlog
/good-first-issue

Thanks @sacgoel
