### ISSUE TITLE
Use Hugo attributions for blog articles

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24334]
**This is a Feature Request**

**What would you like to be added**
Set author information for blog articles in page front matter.

**Why is this needed**
Docsy supports using the front matter of an article to record the author information, and lets this be formatted into the final page.
This issue proposes using that support and revising the _existing_ articles to use that format too.

**Comments**
/kind cleanup
/priority awaiting-more-evidence
/area blog

**Comment by habibrosyad** [comment]
I think this post https://github.com/kubernetes/website/blob/master/content/en/blog/_posts/2020-10-01-contributing-to-the-development-guide/index.md is the best example which implement the feature.

Just curios, should the front matter also be improved to support author affiliation info (found lots of example there), e.g adding `Affiliation` field? Or just simply append the Author field with that info is enough (e.g. `Author: Bla Bla (Google)`)?

**Comment by sftim** [comment]
The tricky bit will be how to handle articles with multiple authors.

I suspect a good approach here is to update the Docsy theme with that new feature, and then revise once upstream has released the improvement. More involved but also easier to maintain.

**Comment by habibrosyad** [comment]
> The tricky bit will be how to handle articles with multiple authors.

I'm thinking something like:
```yaml
authors:
- Foo
- Bar
```
I suspect it would be weird when rendered if you put multiple names within `author`.

> I suspect a good approach here is to update the Docsy theme with that new feature, and then revise once upstream has released the improvement. More involved but also easier to maintain.

Agree.

**Comment by irvifa** [comment]
For long term it will be better to investigate Docsy support for multiple authors.
