### ISSUE TITLE
Trouble working through Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by adamdbenson** [kubernetes/website#24336]
In the interactive tutorial, Module 1, step 2, the command is 

`kubectl version`

the response is 

`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
**The connection to the server localhost:8080 was refused - did you specify the right host or port?**'

From this point on, the tutorial seems to fail.

**Comment by sftim** [comment]
/retitle Trouble working through Interactive Tutorial - Creating a Cluster

@adamdbenson thanks for reporting this. I tried it and it works - if you try again, are the symptoms still there?
/kind bug
/priority awaiting-more-evidence
