### ISSUE TITLE
Scheduled builds

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24351]
**This is a Feature Request**

**What would you like to be added**
Trigger a site build via the Netlify API every _n_ hours

**Why is this needed**
Scheduled builds enable other features, including:
- Automatic updates using data from external sources (eg release information)
- Future-dated blog articles that publish automatically

**Comments**
Based on an idea mentioned in https://github.com/kubernetes-sigs/contributor-site/issues/160 (which suggested triggering a build using a GitHub Action)
/kind feature

**Comment by sftim** [comment]
@kbhawkey @onlydole I would welcome your thoughts on this and whether we should prioritize it / deprioritize it.

**Comment by onlydole** [comment]
I'm in favor of this, both in creating and prioritizing. I see a lot of value in using this for link checking or other similar tooling.

**Comment by sftim** [comment]
Another thing scheduled builds ties into well: a shortcode to fetch from other repos (a bit like a Git submodule, but fetched at render time and tied specifically to GitHub).
See https://github.com/kubernetes-sigs/contributor-site/issues/93#issuecomment-583648843 for an example.

**Comment by irvifa** [comment]
I’m in favor of using this as well.

**Comment by kbhawkey** [comment]
Hi. Some things to think about:
- How would these periodic jobs be scheduled with/into the existing workflow?
- Do you want a way to trigger a new PR/update content when the release repo/site publishes updated information (patch updates)?
- Can you explain what you mean about `Future-dated blog articles that publish automatically`? How would this work?
- Creating a periodic job to check the site's links seems to be a different type of job. The site's content is not updated.
The job could run occasionally and report the results from running the current link checker. This seems lower priority because the link checker can be run locally and authors can update the content. There is no need to wait for a report or reminder of link problems.

**Comment by sftim** [comment]
> How would these periodic jobs be scheduled with/into the existing workflow?

After adding periodic triggers, either of the following would trigger deploying https://kubernetes.io/
- a push to _master_
- a timer

**Comment by sftim** [comment]
> Do you want a way to trigger a new PR/update content when the release repo/site publishes updated information (patch updates)?

That sounds like a different feature. Scheduled builds would reduce the window between a depended-on artifact changing and that being reflected on the live Kubernetes websites.

**Comment by sftim** [comment]
> Creating a periodic job to check the site's links seems to be a different type of job. The site's content is not updated.
The job could run occasionally and report the results from running the current link checker. This seems lower priority because the link checker can be run locally and authors can update the content. There is no need to wait for a report or reminder of link problems.

Yes, it's not as valuable as the blog publishing or the automatic updating based on external sources.

**Comment by sftim** [comment]
https://k8s.dev/ is an example of a site that publishes blog articles automatically.
There are 3 steps.
1. Someone submits a PR that adds a blog article. The blog article is future-dated. The preview includes the blog article.
1. Someone else merges the PR. https://k8s.dev/ rebuilds. The live site does not yet include the blog article.
1. Eventually, the article due date passes. The next time that the [timer GitHub Action](https://github.com/kubernetes-sigs/contributor-site/blob/2a3356e1db4f406c3a1282ad7f778f974401148d/.github/workflows/netlify-periodic-build.yml) for https://k8s.dev/ triggers a rebuild, the blog article goes live. Now, the live site includes the new blog article.

**Comment by sftim** [comment]
Based on https://github.com/kubernetes/website/issues/24351#issuecomment-703034919
/triage accepts
/priority important-longterm

**Comment by kbhawkey** [comment]
@sftim, Is there more work to do?

**Comment by sftim** [comment]
This is done
/close
