### ISSUE TITLE
[zh] translate /docs/tasks/manage-kubernetes-objects/declarative-config.md

### ISSUE THREAD

**Issue by zhiguo-lu** [kubernetes/website#24362]
**This is a Feature Request**

Translate "Declarative Management of Kubernetes Objects Using Configuration Files" into chinese.

**What would you like to be added**
content/zh/docs/tasks/manage-kubernetes-objects/declarative-config.md
/zh/docs/tasks/manage-kubernetes-objects/declarative-config/

**Comment by tengqm** [comment]
/close
dup of #23086
translation in #23557

**Comment by zhiguo-lu** [comment]
> /close
> dup of #23086
> translation in #23557

收到。
我看到你的提交了，确实厉害，学习了。
