### ISSUE TITLE
kubelet glossary term incorrectly marked as core object

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24361]
**This is a Bug Report**

**Problem:**
If you filter for just core objects in the glossary, you see a definition for kubelet.
The [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) is important but it's not a core object because it's not part of the API at all. (The API object is called Node).

**Proposed Solution:**
Edit the source Markdown file at https://github.com/kubernetes/website/blob/master/content/en/docs/reference/glossary/kubelet.md to remove the `core-object` tag from the front matter (just delete the whole line).

See [opening a pull request](https://kubernetes.io/docs/contribute/new-content/open-a-pr/) for details.

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?core-object=true

**Additional Information:**
/kind bug
/help
/language en
/priority backlog

**Comment by AjiArya** [comment]
I'd work on this, assign me please.

**Comment by AjiArya** [comment]
Here's the link to the PR #24363

**Comment by irvifa** [comment]
This is solved on #24363 
/close
