### ISSUE TITLE
Minikube installation , configuration and Deployment Dev experience

### ISSUE THREAD

**Issue by raghvenders** [kubernetes/website#24386]
Minikube installation and documentation is overall covering all env.
For better developer experience , anybody can test and validate the steps in documentation for all the env.

This will be really helpful as version changes.

Todo that , is it wise to have Qwiklabs kind of stuffs will help ?

We can prepare one such documentation and do that validated.(Minikube , Hypervisor , all components etc.)

**Comment by sftim** [comment]
I'm not sure @raghvenders if you're reporting a bug here? Maybe you're proposing an improvement?

If you can clarify, I think that'll help.

**Comment by raghvenders** [comment]
@sftim - it is for improvement.
Not all the env mentioned any developer will have chance to have it locally , he can be one of linux / macos/windows and other relevant combination.(Hypervisor)

If we can build a self tutorial lab for provision possible public cloud env and test all env comb with the steps already mentioned in the document.Would it be easy to test all the combination and steps?

**On a Side Note :** But when i am trying minikube in mac , it used hyperkit as  default driver automatically.(Looks like becasue I have docker desktop installed already - https://minikube.sigs.k8s.io/docs/drivers/hyperkit/).Let me check again if it is a bug , i will report it separate.

**Comment by sftim** [comment]
I'm sorry, I am not confident that I have understood what you're saying there @raghvenders

**Comment by raghvenders** [comment]
Ok , sure.Anyways it is not related to bug..
