### ISSUE TITLE
Remove/Update references to projects hosted in kubernetes-incubator

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/website#24380]
**This is a Bug Report**

**Problem:**
The [kubernetes-incubator org](http://github.com/kubernetes-incubator) has been [deprecated](https://github.com/kubernetes/community/issues/1922). All the repos in incubator have either been [archived](https://github.com/kubernetes-retired) or moved to [kubernetes-sigs](http://github.com/kubernetes-sigs). There are still [many references](https://cs.k8s.io/?q=kubernetes-incubator&i=fosho&files=&repos=kubernetes/website) to projects being hosted in incubator scattered throughout the docs.

**Proposed Solution:**
Update or remove links where appropriate. The blog posts can largely be ignored as they are historical in nature.

**Comment by irvifa** [comment]
@mrbobbytables so we have some mechanism to list which references that actually broken?

**Comment by mrbobbytables** [comment]
All of them would be at this point :x There are no repos under incubator anymore - BUT - GitHub does auto-redirect to the migrated location. There are no 404s :) Just 301s XD

**Comment by sftim** [comment]
/kind cleanup
/language en
(and then copied to downstream localizations)
/priority backlog

`git grep kubernetes-incubator` to find matches, then open the link in a web browser and see what the current link is
_or_
use a link checker. **Note** though that:
```bash
# does not check external links
make container-image
make link-checker-image-pull
make container-internal-linkcheck
```
is (currently) implemented for internal link checking only.
