### ISSUE TITLE
Not translated title in Korean on docs home

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#24388]
**This is a Bug Report**

**Problem:**

Not translated title, "Use the Web UI Dashboard" in Korean on docs home

![image](https://user-images.githubusercontent.com/282159/95145634-be1dd300-07b6-11eb-8321-cd24b1df775c.png)

**Proposed Solution:**

Translate `card.title` in front-matter of file `website/content/ko/docs/tasks/access-application-cluster/web-ui-dashboard.md` into Korean 

**Page to Update:**
https://kubernetes.io/ko/docs/home/

/language ko
/good-first-issue

**Comment by sushil97** [comment]
Hello, I would like to work on this

**Comment by gochist** [comment]
Thank you!!!
/assign @sushil97

**Comment by sushil97** [comment]
@gochist there are few more english words on the page which has to be translated. Should i change them as well ?
such as (selected text) : 
![image](https://user-images.githubusercontent.com/20190528/95195999-0360f580-07f5-11eb-9318-230cc2c6a378.png)
![image](https://user-images.githubusercontent.com/20190528/95196094-29869580-07f5-11eb-8259-07b8fa073dd1.png)

**Comment by gochist** [comment]
@sushil97 Yes, that would be better! But I remember that "Hello Minikube" was intentionally not translated because "Hello something" is a very familiar idiom even to Korean readers.

**Comment by sushil97** [comment]
> @sushil97 Yes, that would be better! But I remember that "Hello Minikube" was intentionally not translated because "Hello something" is a very familiar idiom even to Korean readers.

ohh okay!  about "Glossary"?

**Comment by gochist** [comment]
> ohh okay! about "Glossary"?
I think "용어집" will be fine.
