### ISSUE TITLE
Need to correct "DNS subdomain" translation for consistency

### ISSUE THREAD

**Issue by pjhwa** [kubernetes/website#24389]
**This is a Bug Report**

**Problem:**
"DNS subdomain" has translated to "DNS 서브도메인" in the most documentation.
But the following documents contain the different translation(DNS 하위 도메인) for this.
- ko/docs/concepts/overview/working-with-objects/annotations.md: at 66 line
  _어노테이션_ 은 키/값 쌍이다. 유효한 어노테이션 키에는 두 개의 세그먼트가 있다. 두 개의 세그먼트는 선택적인 접두사와 이름(name)이며, 슬래시(`/`)로 구분된다. 이름 세그먼트는 필수이며, 영문 숫자(`[a-z0-9A-Z]`)로 시작하고 끝나는 63자 이하이어야 하고, 사이에 대시(`-`), 밑줄(`_`), 점(`.`)이 들어갈 수 있다. 접두사는 선택적이다. 지정된 경우, 접두사는 DNS 하위 도메인이어야 한다. 점(`.`)으로 구분된 일련의 DNS 레이블은 총 253자를 넘지 않고, 뒤에 슬래시(`/`)가 붙는다.

- ko/docs/concepts/workloads/pods/_index.md: at 123 line
  [DNS 하위 도메인 이름](/ko/docs/concepts/overview/working-with-objects/names/#dns-서브도메인-이름)인지 확인한다.

**Proposed Solution:**
Update the translation for "DNS subdomain" as "DNS 서브도메인" in the above documents.

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/annotations/
https://kubernetes.io/ko/docs/concepts/workloads/pods/

**Comment by sushil97** [comment]
Will it require knowledge of korean language?

**Comment by pjhwa** [comment]
@sushil97 Not really. But you should change the Korean words as guided. :-)

**Comment by sushil97** [comment]
Will do. Assign me to this

**Comment by sushil97** [comment]
@pjhwa can you check my PR #24393

**Comment by sushil97** [comment]
@pjhwa we can close this issue now. right ?

**Comment by pjhwa** [comment]
@sushil97 Of course! Thank you.
