### ISSUE TITLE
Giving full access to all the resources except one(say pods).

### ISSUE THREAD

**Issue by Rittu21** [kubernetes/website#24381]
Allowing delete permissions for all the resources(inside a namespace) in a Role is giving the permission to delete the namespace as well.

`rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]`

we are supposed to have permissions to delete the resources like pods inside the namespace ("abc" say) , but we are getting the permission to delete the namespace as well.
How to exclude namespace from this?

**Comment by reylejano-rxm** [comment]
@Rittu21, you might want to try Kubernetes office hours for support related questions 
https://github.com/kubernetes/community/blob/master/events/office-hours.md
Slack: https://kubernetes.slack.com/archives/C6RFQ3T5H
Or the Kubernetes Users Slack channel: https://kubernetes.slack.com/archives/C09NXKJKA

Issues on this repo are intended for the Kubernetes website e.g. documentation and not support related issues
