### ISSUE TITLE
Troubleshoot Applications - POD Restart due to OOM

### ISSUE THREAD

**Issue by kkrhdd** [kubernetes/website#24390]
Hi Team,

I am facing an issue in one of the pod where the pod is being killed when the memory limit reached maximum and no heap dump is being generated even though the Heap dump parameters are configured. 
I understand that the pod is getting killed by kubernetes instead of its own. Can you please suggest a way to extract heap dump for such pods. So that it will be helpful for us to debug the issue.

Thanks in advance.

**Comment by irvifa** [comment]
Hmm I was wondering if the content is better addressed in the slack channel kubernetes-users or stackoverflow since this involves debugging applications instead of documentation related matter.

**Comment by kkrhdd** [comment]
ok. Closing the issue.

**Comment by sftim** [comment]
@kkrhdd if you can identify a gap in the documentation and can describe that, please do feel welcome to file an issue about that gap.
