### ISSUE TITLE
Improve diagram for “Reserve Compute Resources for System Daemons”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24398]
**This is a Feature Request**

**What would you like to be added**
Replace the diagram in [Reserve Compute Resources for System Daemons](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/) with a SVG-format vector equivalent.

_Consider_ switching from rows to columns - that will fit better into the available white space.

**Why is this needed**
There is an ASCII-art diagram in the page at https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

This gets the point across but looks a bit unpolished, and readers might think that the feature is also not finished.

**Comments**
/kind cleanup
/language en
/priority backlog

**Comment by JornShen** [comment]
![image](https://user-images.githubusercontent.com/18069202/95649483-239ff580-0b10-11eb-827f-74d9cdbd2dd0.png)


How about like this ?

**Comment by sftim** [comment]
@JornShen I like that look.
I would use the Kubernetes blue and gray colors - maybe blue for pods, gray for kube-reserved and system-reserved, no color (or white) for eviction-threshold.

**Comment by JornShen** [comment]
> @JornShen I like that look.
> I would use the Kubernetes blue and gray colors - maybe blue for pods, gray for kube-reserved and system-reserved, no color (or white) for eviction-threshold.

all right.
/assign
