### ISSUE TITLE
Pod Lifecycle page have incomplete sentense

### ISSUE THREAD

**Issue by RoSk0** [kubernetes/website#24399]
Second sentence of the second paragraph is obviously incomplete. It reads like this `Within a Pod, Kubernetes tracks different container states and handles`. 

![Selection_004](https://user-images.githubusercontent.com/119257/95283018-366bbd80-08b7-11eb-917e-ef33504e3dbf.png)

It would be good to restore missing bit.

**Comment by sftim** [comment]
Page is https://k8s.io/docs/concepts/workloads/pods/pod-lifecycle/

PR #22603 introduced the regression; I suggest the second “handles” should instead read “determines what action to take to make the Pod healthy again”.

/kind bug
/language en
/triage accepted
/priority backlog

Thanks @RoSk0
