### ISSUE TITLE
”make container-serve“ report permission denied 

### ISSUE THREAD

**Issue by zhiguo-lu** [kubernetes/website#24396]
**This is a Bug Report**

run :
```shell
make container-serve
```

output :
```
docker run --rm --interactive --tty --volume /Users/lenovo/workbench/website:/src --mount type=tmpfs,destination=/src/resources,tmpfs-mode=0777 -p 1313:1313 kubernetes-hugo:v0.74.3-9f93d97c7112 hugo server --buildFuture --bind 0.0.0.0
Error: add site dependencies: create deps: failed to create file caches from configuration: mkdir /src/resources/_gen: permission denied
make: *** [container-serve] Error 255
```

my environment:
- mac version：10.14.3 
- bash: 5.0.11
- docker engine：19.03.13

**Proposed Solution:**
I try to figure out what's the problem, and I got following clue:
1. In line 71 of Makefile:
   `--mount type=tmpfs,destination=/src/resources,tmpfs-mode=0777`

2. in container, list directory of /src/resources :
   ```
   drwxr-xr-x    2 root     root            40 Oct  6 15:07 resources/
   ```

3. In line 32 of Dockerfile:
   ```
   USER hugo:hugo
   ```

seems it is a permission problem，
 
 **I simply commented out  lines 32 of dockerfile ` USER hugo:hugo`, and the problem get solved。** 

**Page to Update:**
Makefile
Dockerfile

**Comment by sftim** [comment]
It seems like the challenge for compatibility is the Docker Desktop product on macOS. The symptoms don't seem to be present on Linux.
