### ISSUE TITLE
Sidebar on Volumes page missing entries

### ISSUE THREAD

**Issue by hottomato4** [kubernetes/website#24409]
**This is a Bug Report**

**Problem:**
On https://kubernetes.io/docs/concepts/storage/volumes the sidebar on the right of the page with links to the types of volumes does not match the full list given under https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes. for example, it is missing CSI, scaleIO and vsphereVolume.

**Proposed Solution:**
Update the list on the right to include the missing entries, and add a mechanism to keep it up to date.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes

**Comment by kbhawkey** [comment]
Related to PR #24077

**Comment by kbhawkey** [comment]
Hi @hottomato4 .
Can this issue be closed?
The update page looks like:
https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes
