### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/cluster-intro/

### ISSUE THREAD

**Issue by ChillarAnand** [kubernetes/website#2441]
**This is a...** 
- [x] Feature Request

**Problem:**

Its documented that node is a VM. Can you explain more about master?

**Comment by DanyC97** [comment]
/language en

@ChillarAnand in https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/ we say

> The Master is responsible for managing the cluster. The master coordinates all activities in your cluster, such as scheduling applications, maintaining applications' desired state, scaling applications, and rolling out new updates.

please help understand what else do you think we should add in addition to?
