### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/access-cluster-api/

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes/website#24430]
You mention go and python as official client library's that can access the api from within a pod. However you have an official JavaScript library but you don't make any mention of how that library works in this situation.  The docs for the library don't mention anything either.  Can the official JavaScript lib talk to the k8s api from within a pod?  and if so, how?

**Comment by ankita2910** [comment]
Hi @Daxcor69 ,
In access-cluster-api, in the documentation they have mentioned in Programmatic access to the API for 6 clients as follows:
1. Go client
2.Python client
3.Java client
4.dotnet client
5.JavaScript client
6.Haskell client

For Javascript client the documentation explains as follows:

JavaScript client
To install JavaScript client, run the following command: npm install @kubernetes/client-node. See https://github.com/kubernetes-client/javascript/releases to see which versions are supported.

The JavaScript client can use the same kubeconfig file as the kubectl CLI does to locate and authenticate to the API server. See this example:

const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

k8sApi.listNamespacedPod('default').then((res) => {
    console.log(res.body);
});

Thank you

**Comment by Daxcor69** [comment]
Yes, I saw that I documentation.  The kubeconfig has the information to connect to the k8s from OUTSIDE the cluster, correct?  Does it also contain the necessary information to connect to the api from INSIDE the cluster? One of my pods will need to contact the api to make changes.  Here is the documentation in question:

```
Accessing the API from within a Pod 
When accessing the API from within a Pod, locating and authenticating to the API server are slightly different to the external client case described above.

The easiest way to use the Kubernetes API from a Pod is to use one of the official client libraries. These libraries can automatically discover the API server and authenticate.

Using Official Client Libraries
From within a Pod, the recommended ways to connect to the Kubernetes API are:

For a Go client, use the official Go client library. The rest.InClusterConfig() function handles API host discovery and authentication automatically. See an example here.

For a Python client, use the official Python client library. The config.load_incluster_config() function handles API host discovery and authentication automatically. See an example here.

There are a number of other libraries available, please refer to the Client Libraries page.

In each case, the service account credentials of the Pod are used to communicate securely with the API server.
```

There is no mention of the javascript library.  Btw, thank you for the quick response.

**Comment by tengqm** [comment]
@Daxcor69 What you see today (the client libraries) are something we tried to eliminate from the website entirely. They are not contents about the core Kubernetes. Maintaining them and keeping them up to date is a heavy task, if possible at all. Some of the contents similar to these have been killed recently because they are dual-hosted.

I don't think we are gonna add more items to the list until we get a strong need on this. In your case, please talk to the client library team and see if they can provide more documentation.

**Comment by Daxcor69** [comment]
I agree totally with what you say. Having competing and different documentation is a real challenge in todays world.  Really makes it hard for us noobs to figure out how to do this stuff. Thank you for the work you and the group does. It is appreciated.
