### ISSUE TITLE
Link directly from concept pages to API reference

### ISSUE THREAD

**Issue by tschirmer** [kubernetes/website#24441]
Can we get a link to the actual api on each of these documentations pages? I come across the yaml api every now and again, but it'd be very convenient to just jump in to see what yaml we can actually configure.

**Comment by sftim** [comment]
/retitle Link directly from concept pages to API reference
/kind feature
/priority backlog
/triage accepted
/sig docs

**Comment by sftim** [comment]
Good idea @tschirmer

**Comment by mokua** [comment]
hi @sftim @tschirmer , more details on what do you have in mind on this?

**Comment by sftim** [comment]
There's some ideas in https://github.com/kubernetes/website/pull/23294 about how this might work.

**Comment by sftim** [comment]
Looks like PR #26151 would fix this

**Comment by sftim** [comment]
Partly done in:

- https://github.com/kubernetes/website/pull/29228
- https://github.com/kubernetes/website/pull/29230
- https://github.com/kubernetes/website/pull/29231
- https://github.com/kubernetes/website/pull/29232
- https://github.com/kubernetes/website/pull/29233

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/kubernetes/issues/19680

**Comment by sftim** [comment]
I'd like to get the shortcode right first time, rather than do it once and then make all the localization teams redo it once we change.

**Comment by sftim** [comment]
It will help if the right-hand (for LTR languages) sidebar highlights the link to the reference. The highlighting would make the reference link more discoverable.

**Comment by dipesh-rawat** [comment]
I'm more than happy to work on it and get this moving forward.

/assign
