### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/cpu-management-policies/

### ISSUE THREAD

**Issue by EdSchouten** [kubernetes/website#24443]
This page only discusses the semantics of single-container pods. When pods are scheduled that consist of multiple containers, all of them need to be Guaranteed QoS. Even init containers are taken into account.

(To be honest, I find these semantics a bit weird. Why couldn't cpusets be set up properly for individual containers, even when the pod as a whole isn't Guaranteed QoS?)

**Comment by sftim** [comment]
/kind feature
/language en
This issue seems to be about making clear that multi-container Pods must consist _only_ of containers where `requests` == `limits`, in order to be treated as Guaranteed.
/triage accepted
/priority backlog
