### ISSUE TITLE
[zh] kubeadm related pages to be translated.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#24486]
The following kubeadm related pages are not translated into Chinese.

- [ ] docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs.md
- [ ] docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_generate-csr.md
- [ ] docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize.md
- [ ] docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_all.md
- [ ] docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_experimental-cert-rotation.md
- [ ] docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_preflight.md

- [ ] docs/reference/setup-tools/kubeadm/implementation-details.md

/language zh
/help

**Comment by howieyuen** [comment]
/assign
I'd love to 👍

**Comment by tengqm** [comment]
/triage accepted
Resolved.
/close
