### ISSUE TITLE
Error following “Run a Single-Instance Stateful Application”

### ISSUE THREAD

**Issue by shrutip32** [kubernetes/website#24495]
Unable to Access the MySQL instance 
 i get the following error whenever i try to Run a MySQL client to connect to the server:

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'192.168.140.229' (using password: YES)
pod "mysql-client" deleted
pod default/mysql-client terminated (Error)

**Comment by sftim** [comment]
/retitle Error following “Run a Single-Instance Stateful Application”

**Comment by sftim** [comment]
Hi @shrutip32 

Can you explain the steps you followed before you saw that error? That information will help us to verify that there is an issue with the documentation, and also should help people to work out how to solve it.

**Comment by mokua** [comment]
hello @sftim 
I have tested the steps and the application deploys correctly.
