### ISSUE TITLE
Clarify “Object Names and IDs”

### ISSUE THREAD

**Issue by StingyJack** [kubernetes/website#24497]
This implies every object must have a name and UID, but it does not actually say this. Is this wording intentional because there are some cases where these two properties would not be required to have values for a kubernetes object, or would these values be required without exception?

**Comment by tengqm** [comment]
There are cases where an object doesn't require a name. For example, `LocalSubjectAccessReview` from the `authorization.k8s.io/v1` group. As for UID, most of the time it is not user provided. It is system generated.

**Comment by sftim** [comment]
Seems like there's an opportunity to clarify, similar to the wording @tengqm used in https://github.com/kubernetes/website/issues/24497#issuecomment-706804456.

/retitle Clarify “Object Names and IDs”
/language en
/triage accepted
/priority backlog

**Comment by sftim** [comment]
Page to revise is https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by StingyJack** [comment]
/remove-lifecycle rotten

.... stalebot is a cancer on the community
