### ISSUE TITLE
Issue with /docs/tutorials/stateless-application/hello-minikube/

### ISSUE THREAD

**Issue by vhosakot** [kubernetes/website#2450]
**This is a** 
- Bug Report

**Problem:**

In https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/#create-a-minikube-cluster, after `kubectl cluster-info`,  the command `minikube dashboard` that opens the kubernetes dashboard must be mentioned so that the user knows how to open the kubernetes dashboard when using minikube.

**Proposed Solution:**

After `kubectl cluster-info`, `minikube dashboard` must be mentioned.

**Page to Update:**

https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/#create-a-minikube-cluster

Kubernetes Version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

Additional Information:

When I access the `kubernetes-dashboard` link `https://192.168.64.2:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard` in the output of `kubectl cluster-info` in a browser, I see an `Unauthorized` error.

```
$ kubectl cluster-info
Kubernetes master is running at https://192.168.64.2:8443
KubeDNS is running at https://192.168.64.2:8443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://192.168.64.2:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

Hence, I used `minikube dashboard` to access the kubernetes dashboard.  `minikube dashboard` must be mentioned in the documentation so that users know how to open the kubernestes dashboard when using minikube.

**Comment by steveperry-53** [comment]
@waprin

**Comment by vhosakot** [comment]
Submitted PR https://github.com/kubernetes/website/pull/7375 to fix this in the documentation.
