### ISSUE TITLE
[zh] Umbrella issue - files that need translation into Chinese.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#24511]
There are two kinds of gaps between the English site and the Chinese localization:

- Files that are never translated. [Focus of this Issue]
- Files that were translated but out of sync due to English version changes.

A comparison of the directory content was performed by:

```
cd content/en; tree -i -f -o ~/tmp/entree .; cd -
cd content/zh; tree -i -f -o ~/tmp/zhtree .; cd -
diff ~/tmp/entree ~/tmp/zhtree
```

The output is a list of full paths of files that are out of sync. We have (by Oct 12, 2020) identified all missing pages in Chinese localization and filed issues for them, as listed below:

- [x] PR #24238, handles the following file
 ./docs/tutorials/clusters/seccomp.md
 ./examples/pods/security/seccomp/alpha/audit-pod.yaml
 ./examples/pods/security/seccomp/alpha/default-pod.yaml
 ./examples/pods/security/seccomp/alpha/fine-pod.yaml
 ./examples/pods/security/seccomp/alpha/violation-pod.yaml
 ./examples/pods/security/seccomp/ga/audit-pod.yaml
 ./examples/pods/security/seccomp/ga/default-pod.yaml
 ./examples/pods/security/seccomp/ga/fine-pod.yaml
 ./examples/pods/security/seccomp/ga/violation-pod.yaml
 ./examples/pods/security/seccomp/kind.yaml
 ./examples/pods/security/seccomp/profiles/audit.json
 ./examples/pods/security/seccomp/profiles/fine-grained.json
 ./examples/pods/security/seccomp/profiles/violation.json
- [x] Issue #24065, PR #24580
 ./docs/reference/access-authn-authz/certificate-signing-requests.md
- [x] Issue #24214, PR #24201
 ./docs/setup/production-environment/tools/kubespray.md
- [x] Issue #24486, PR #24543 
 ./docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs.md
 ./docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_certs_generate-csr.md
 ./docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize.md
 ./docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_all.md
 ./docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_experimental-cert-rotation.md
 ./docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_preflight.md
- [x] Issue #24486, PR #24600 
 ./docs/reference/setup-tools/kubeadm/implementation-details.md
- [x] Issue #24500, PR #24515
 ./docs/reference/using-api/health-checks.md
- [x] Issue #24501, PR #24630
 ./docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
- [x] Issue #24502, PR #24631
 ./docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- [x] Issue #24503, PR #24634
 ./docs/tasks/configure-pod-container/configure-gmsa.md
- [x] Issue #24504, PR #24719
 ./docs/test.md
- [x] Issue #24505, PR #24662
 ./docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk.md
- [x] Issue #24506, PR ##24707
 ./docs/setup/production-environment/turnkey/gce.md
- [x] Issue #24507, PR #24674
 ./docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
- [x] PR #24508
 -> ./docs/tasks/administer-cluster/memory-available.sh
 <- ./examples/admin/resource/memory-available.sh
- [x] PR #24509, #24510
 ./examples/ingress/example-ingress.yaml

**Comment by howieyuen** [comment]
PR https://github.com/kubernetes/website/pull/24515 fix  issue #24500

**Comment by sftim** [comment]
oops.
/language zh

**Comment by howieyuen** [comment]
combination of PR https://github.com/kubernetes/website/pull/24543 and https://github.com/kubernetes/website/pull/24600 fix issue #24486

**Comment by howieyuen** [comment]
issue can be closed now, all PRs are merged

**Comment by tengqm** [comment]
@howieyuen Thanks for checking and reminder.
/close
