### ISSUE TITLE
Add kubeadm to “Install Tools”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24532]
**This is a Feature Request**

**What would you like to be added**
Add `kubeadm` to https://kubernetes.io/docs/tasks/tools/

**Why is this needed**
`kubeadm` is an important and widely-used way to get Kubernetes running, and it definitely counts as a tool. It's also 100% in-project.
https://kubernetes.io/docs/tasks/tools/ should hyperlink to a page about installing kubeadm.

**Comments**
/kind feature
/priority backlog
/sig cluster-lifecycle
/language en

**Comment by JornShen** [comment]
solved it in https://github.com/kubernetes/website/pull/24585

**Comment by neolit123** [comment]
> solved it in #24585

thanks
/close
