### ISSUE TITLE
Issue with /docs/user-guide/horizontal-pod-autoscaling/walkthrough/

### ISSUE THREAD

**Issue by bytesandwich** [kubernetes/website#2453]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

Under 'Step One: Run & expose php-apache server'
link 'here' goes to https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/image/ which is a 404. 

**Proposed Solution:**
In https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/
What should this point to? There are https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/image/index.php
and
https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/image/Dockerfile
Was there ever an html page for this?

**Page to Update:**
https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/

**Comment by tengqm** [comment]
This has been fixed.
