### ISSUE TITLE
Установка Kubernetes с помощью Minikube

### ISSUE THREAD

**Issue by oleggalimov** [kubernetes/website#24548]
> Установк**е**
> Посмотрите страницу Установка Minikube

There is a grammatical error, should be "Установк**А**

**Comment by sftim** [comment]
/language ru
page is https://kubernetes.io/ru/docs/tasks/tools/install-minikube/

Thanks for reporting this @oleggalimov

**Comment by oleggalimov** [comment]
You are welcome)
But, the page, where i found it is here: https://kubernetes.io/ru/docs/setup/learning-environment/minikube/

**Comment by sftim** [comment]
Thanks for clarifying @oleggalimov
