### ISSUE TITLE
Documentation still uses words non inclusive terms like "slaves"

### ISSUE THREAD

**Issue by jimmy17x** [kubernetes/website#24540]
This ticket is for a suggestion that we should also identify and change non-inclusive terms in our documentation
eg : 
https://kubernetes.io/search/?q=slave

Alternative can be found here 
https://developers.google.com/style/word-list

**Comment by sftim** [comment]
This is a near exact duplicate of https://github.com/kubernetes/website/issues/21621 - let's track the work there.
/wg naming
/triage duplicate
/retitle Documentation still uses words non inclusive terms like "slaves" 
/kind bug
/close
