### ISSUE TITLE
Add some hints for CLA diagnosis

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#24577]
**This is a Feature Request**

**What would you like to be added**

Now and then we encounter PRs failing CLA checking. There must be some problems that are common across these cases. We need some guide in the contribute section for reference when such problems occur again.

**Why is this needed**

Saving reviewers/contributors time on debugging CLA issue, rather than commenting with `/check-cla` again and again.

**Comment by sftim** [comment]
/kind feature
/language en
/sig contributor-experience

@tengqm, could we add that to https://www.k8s.dev/ and then add a shorter paragraph that hyperlink to the detailed page?

**Comment by tengqm** [comment]
> @tengqm, could we add that to https://www.k8s.dev/ and then add a shorter paragraph that hyperlink to the detailed page?
@sftim That is acceptable too.
