### ISSUE TITLE
Network Policies documentation page- description of no policy types is unclear

### ISSUE THREAD

**Issue by sonogithub** [kubernetes/website#24582]
Referring to "If no policyTypes are specified on a NetworkPolicy then by default Ingress will always be set and Egress will be set if the NetworkPolicy has any egress rules."

1. What does "Ingress will always be set" actually mean and how does it impact selected pods ?
For example does it really mean "Ingress will be allowed for all selected pods in the namespace and  the policyTypes will include Ingress" or "ingress will not be allowed for all selected pods in the namespace and policyTypes will include ingress ?

2. "Egress will be set if the NetworkPolicy has any egress rules." - similar issue - 

so the issue here is that  both existing description uses the word "set" without explanation of the what that really means or how it impacts the behaviour

**Comment by sftim** [comment]
Sounds like there is room for improvement - thanks for highlighting this @sonogithub 
/language en
/sig network
/triage accepted

**Comment by jayunit100** [comment]
can help if needed also
