### ISSUE TITLE
Update out-dated README-ko.md

### ISSUE THREAD

**Issue by gochist** [kubernetes/website#24620]
**This is a Bug Report**

**Problem:**
Currently, `README-ko.md` is an old version and needs to be updated.

**Proposed Solution:**
Update out-dated README-ko.md

**Page to Update:**
https://github.com/kubernetes/website/blob/master/README-ko.md

/language ko

**Comment by pjhwa** [comment]
README-ko.md 파일에 대해서 업데이트한 PR을 올린 후에 해당 파일에 대한 권한을 요청하는 식으로 진행이 되는거겠죠?
일단 제가 업데이트 해보겠습니다.

/assign

**Comment by seokho-son** [comment]
> README-ko.md 파일에 대해서 업데이트한 PR을 올린 후에 해당 파일에 대한 권한을 요청하는 식으로 진행이 되는거겠죠?
> 일단 제가 업데이트 해보겠습니다.
> 
> /assign

@pjhwa README-ko.md 에 대한 권한 요청(?)이 필요할지는 모르겠습니다.. ^^ 자주 변경되는 사항은 아니기도 하고, 파일별 권한 부여에 대한 기술적인 이슈가 있기도 해서요 ^^ 그래도 *.toml 권한 관련 이슈도 있으니, 다음에 한꺼번에 이야기해보면 어떨까 싶네요 ^^ 
해당 이슈 해결(ko 업데이트)을 위한 PR에서 파일 권한에 대한 논의가 필요할지는 모르겠으나 ~~ @pjhwa 님이 필요하다고 생각하시면 추진하셔도 좋을 것 같습니다.. ^^

**Comment by pjhwa** [comment]
@seokho-son 
> 해당 이슈 해결(ko 업데이트)을 위한 PR에서 파일 권한에 대한 논의가 필요할지는 모르겠으나 ~~ @pjhwa 님이 필요하다고 생각하시면 추진하셔도 좋을 것 같습니다.. ^^

아, 앞으로 계속 권한을 달라고 요청하는게 아니라 본 건의 이슈해결에 한해서 말씀드렸어요. ^^
