### ISSUE TITLE
Mention network plugins in “Kubernetes Components”

### ISSUE THREAD

**Issue by marrem** [kubernetes/website#24627]
I was reading this page to learn about an addon that the installation page mentions as indispensable, i.e. the CNI addon. Strangely it isn't even mentioned on the page.

**Comment by sftim** [comment]
/retitle Mention network plugins in “Kubernetes Components”

It does make sense to mention network plugins as an example of an add-on.
/triage accepted
/language en
/priority backlog

**Comment by tengqm** [comment]
/reopen
This is still a valid issue.

**Comment by divya-mohan0209** [comment]
Page to be modified: https://kubernetes.io/docs/concepts/overview/components/
What needs to be added: A section about Network Plugins under Addons
Where can you find more information about Network Plugins on our docs:
- https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
- https://kubernetes.io/docs/concepts/cluster-administration/addons/

Does that sound right? If yes, we can open this up for contributions as a good-first-issue, I think.
