### ISSUE TITLE
Create a kops section on the website

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/website#2463]
kops project has a lot of documentation that is being reformated and needs to be added to the site.  We need to figure out a section first, and then add it.

cc: @sarahnovotny @justinsb @kris-nova

**Comment by jaredbhatti** [comment]
Perhaps under Tools?  Should be a larger question for docs.

**Comment by chrislovecnm** [comment]
BUMP - does anyone on the docs team have an opinion?  @janetkuo I know you have done a bunch of work lately in docs.

cc: @steveperry-53

**Comment by steveperry-53** [comment]
The short-term answer is under SETUP, maybe near
https://kubernetes.io/docs/getting-started-guides/kops/.

For the long term, we're discussing the overall plan for the topics under
SETUP. The big question is how much of this content belongs on kubernetes.io
and how much belongs on other sites. We're thinking, for example, that much
of the GKE and GCE setup content should be on cloud.google.com.

**Comment by chrislovecnm** [comment]
Well to add a bit more information - kops supports aws currently, and has GCE and vSphere support in alpha.

Also how are the new API docs generated? We have API spec code on our code base and would love to reuse that functionality.

We have done a big overhaul of our docs and I need to figure out when to start moving docs over here ever release.

Thanks!

**Comment by steveperry-53** [comment]
Sorry for the delay. Have you gotten the information you need about API doc
generation? Or would you like me to check into this now?
Steve

**Comment by DanyC97** [comment]
@chrislovecnm this issue been open for a while, can you please confirm if there is anything left we can help with ?

**Comment by chrislovecnm** [comment]
I do not think there is a kops section on the k8s website. That is the need.

**Comment by sftim** [comment]
As per the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/), some of this proposed documentation might belong in the kops project.

It's still important to have links there, and help readers understand what kops is.

/priority backlog

**Comment by sftim** [comment]
Apart from https://kubernetes.io/docs/setup/production-environment/tools/kops/ what else is needed?

**Comment by tengqm** [comment]
Let's close this one given that 1) there now IS a section for the `kops` tool; 2) this issue has been inactive for more than 9 months.
Feel free to reopen this or open a new one if there are still related requests.
/close
