### ISSUE TITLE
Fine Parallel Processing Using a Work Queue

### ISSUE THREAD

**Issue by dirtyearl** [kubernetes/website#24657]
Pods do not appear to succeed, or process job, as described in the documentation.

**Comment by sftim** [comment]
I think this is a bug report for https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/

That task page is quite involved. @dirtyearl, would you be willing to explain how far you got along that task and what happened when it went wrong? How was that different from what you expected?

/triage needs-information
/language en

**Comment by sftim** [comment]
Without more information it's difficult to accept this as a defect.
/close

@dirtyearl please feel free to reopen and reply with details.
