### ISSUE TITLE
Document security recommendation for component log levels

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24652]
**This is a Feature Request**

**What would you like to be added**

Add a paragraph or a new page inside https://k8s.io/docs/concepts/security/ that cautions readers about running production systems at verbose log level.
In particular, warn that secrets may be revealed either at Trace or Debug level (TODO: confirm which) and that therefore these secrets should either not be logged (by turning down the debug level) or the log records adequately protected - for example, with an extra filter that obscures secrets.

**Why is this needed**

In a [message](https://groups.google.com/d/msgid/kubernetes-dev/CAGDbWi8HKgDoUy%2ByUSi9cT8Q33EK2cXsU1ytmukXLDoqLEsmHQ%40mail.gmail.com) to the _kubernetes-dev_ mailing list, @neolit123 stated:
> everything above 3 is qualified as "debug level" verbosity as per the kubernetes klog "logging convention"
> https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md
> 
> and running loggers at "debug level" verbosity is not exactly a common practice in production (at least for other software).
>
> so i wonder if that document needs adjustments to say that secrets should never be printed at any level even for debugging purposes?

Let's also make that clear via the Kubernetes documentation.

**Comments**
/sig security
/language en
/kind feature

**Comment by tengqm** [comment]
Are we talking about this feature? https://github.com/kubernetes/kubernetes/pull/95316

**Comment by sftim** [comment]
This is related, but it's a different approach.
1. The code should not write security tokens into logs
2. Administrators should not enable trace logging in prod, because trace logging can reveal confidential details (also, for example, the contents of a Secret).

Combined, these measures make Kubernetes more secure.

**Comment by sftim** [comment]
Actually this might be better documented in https://k8s.dev/
