### ISSUE TITLE
Possible abuse of the note shortcode

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#24660]
**This is a Bug Report**

**Problem:**

As shown in the following screenshot, the [windows in kubernetes section](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/) has a subsection that consists of nothing other than notes!

![Screen Shot 2020-10-21 at 12 01 46 PM](https://user-images.githubusercontent.com/5094756/96671831-5dd18880-1395-11eb-938f-45f173563e07.png)

This is a suspected abuse of the `note` shortcode. We are not supposed to mark all texts as notes. To one extreme, the whole Kubernetes website is about about notes, something we want readers to know, to notice.

**Proposed Solution:**

- We should use the `note`, `warning` alike short code with caution.
- We may want to refrain from introducing more shortcode into Website unless there is a compelling need, i.e. something we really want to bundle together for the sole purpose of reuse. 

**Page to Update:**

the [windows in kubernetes section](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/)

**Comment by sftim** [comment]
These 4 things seem like details that someone wanted to call out to readers. I can see why you'd use a callout for that. There are a few other things that aren't quite in line with the style guide; I see statements about the future, and the text doesn't address the reader as “you”. A cleanup would be good.

This could work as a set of 4 bullet points instead, headed by a text along the lines of: “please bear in mind the following details”.
/sig windows
/priority backlog
/retitle Tidy page “Intro to Windows support in Kubernetes”
/triage accepted

**Comment by tengqm** [comment]
@sftim Thanks for the comments. Please don't change the topic of this issue. This issue is about the shortcode, not about other tidy up. The page was just mentioned as an example. Hope we are clear about this.

**Comment by sftim** [comment]
Thanks for clarifying your concern @tengqm
