### ISSUE TITLE
404 links

### ISSUE THREAD

**Issue by neha-viswanathan** [kubernetes/website#24661]
**Problem:**
There are several links that lead to non-existent pages (404s)

**Proposed Solution:**
Update the links or delete them

**Pages to Update:** To name a few

- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/overview/working-with-objects/names#dns-label-names
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/services-networking/connect-applications-service
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/services-networking/ingress
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/services-networking/endpoint-slices
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/services-networking/service/#internal-load-balancer
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
- [ ] https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/services-networking/service.md#services-without-selectors
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/overview/working-with-objects/names#dns-subdomain-names
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/services-networking/dns-pod-service
- [ ] https://github.com/kubernetes/website/blob/master/docs/concepts/cluster-administration/addons

**Comment by ngv-nexo** [comment]
I want to point out that some CSS is missing for me in the english version of the site: https://kubernetes.io/docs/home/ 

https://kubernetes.io/scss/main.min.f276b50d1c71711c70ef4fa9d4b796c7d32e4fdc489e65604766e35fe9f4958d.css

**Comment by sftim** [comment]
/triage needs-information
@neha-viswanathan it's not clear from that report what the URL of the broken hyperlink is. Can you explain what someone should search for in a page in order to find the broken hyperlink? [`linkchecker.py`](https://github.com/kubernetes/website/blob/master/scripts/linkchecker.py) may help.

@ngv-nexo I recmmend that you report a separate issue about missing CSS

**Comment by ben-foxmoore** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/ is a 404. It's the fourth result when [searching for labels](https://kubernetes.io/search/?q=labels)

**Comment by sftim** [comment]
@ben-foxmoore I recommend you report that in a new issue; the issue you've added to here is a bit unclear.
