### ISSUE TITLE
Configure a Pod to Use a ConfigMap

### ISSUE THREAD

**Issue by mahendran8655** [kubernetes/website#24665]
Hi Team,

Observed the spelling mistake for customization

Please check this line
"Apply the kustomization directory to create the ConfigMap object"

**Comment by sftim** [comment]
This _isn't_ a spelling mistake; it's documentation that assumes more reader knowledge than is justifier.

/triage invalid

@mahendran8655 The directory named `kustomization` is for use with [kustomize](https://github.com/kubernetes-sigs/kustomize).

**Comment by sftim** [comment]
@mahendran8655 are you OK if we close this issue?
