### ISSUE TITLE
Fix the link to Windows pause image dockerfile?

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#24673]
**This is a Bug Report**

**Problem:**

In https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#troubleshooting, the bulletin 16 is about the 'pause' image. There we have a DOCKERFILE link pointing to the `wincat` tool. This link makes no sense in the context. A reader would expect it to point to the Dockerfile used to build the `pause` image, not the `wincat` tool.

**Proposed Solution:**

Two options:

- remove the link, or
- correct the link, e.g. https://github.com/kubernetes-sigs/windows-testing/blob/master/images/pause/Dockerfile

**Page to Update:**

https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#troubleshooting

**Comment by sftim** [comment]
/sig windows
/triage accepted
(needs fixing either way)
/kind bug
/priority backlog
