### ISSUE TITLE
Debugging DNS Resolution

### ISSUE THREAD

**Issue by andrew-bolin** [kubernetes/website#24691]
From this page: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

The link "Inheriting DNS from the node" goes to a page that has no section with that title. It's not clear to me which part of the page relates to inheriting dns from the node...

 https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#inheriting-dns-from-the-node

**Comment by sftim** [comment]
/language dns
/kind bug
/triage accepted
/priority backlog

Thanks for reporting this @andrew-bolin

**Comment by sftim** [comment]
oops.
/language en
