### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by Syed-Saifulla** [kubernetes/website#24694]
NAME          READY   STATUS       RESTARTS   AGE     IP                   NOMINATED NODE   READINESS GATES
pod/mysql-0   2/2     Running      0          7m53s   10.42.4.38       <none>           <none>
pod/mysql-1   2/2     Running      0          6m46s   10.42.2.128     <none>           <none>
pod/mysql-2   0/2     Init:Error   4          2m25s   10.42.3.44        <none>           <none>

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE   SELECTOR
service/mysql        ClusterIP   None           <none>        3306/TCP   97m   app=mysql
service/mysql-read   ClusterIP   10.43.68.227   <none>        3306/TCP   97m   app=mysql

NAME                     READY   AGE     CONTAINERS         IMAGES
statefulset.apps/mysql   2/3     7m53s   mysql,xtrabackup   mysql:5.7,gcr.io/google-samples/xtrabackup:1.0

Failed container logs
=============

[root@worker-2 ~]# docker logs ef1
+ [[ -d /var/lib/mysql/mysql ]]
++ hostname
+ [[ mysql-2 =~ -([0-9]+)$ ]]
+ ordinal=2
+ [[ 2 -eq 0 ]]
+ ncat --recv-only mysql-1.mysql 3307
+ xbstream -x -C /var/lib/mysql
Ncat: Could not resolve hostname "mysql-1.mysql": Name or service not known. QUITTING.
+ xtrabackup --prepare --target-dir=/var/lib/mysql
xtrabackup version 2.4.4 based on MySQL server 5.7.13 Linux (x86_64) (revision id: df58cf2)
xtrabackup: cd to /var/lib/mysql
xtrabackup: Error: cannot open ./xtrabackup_checkpoints
xtrabackup: error: xtrabackup_read_metadata()
xtrabackup: This target seems not to have correct metadata...
InnoDB: Number of pools: 1
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
xtrabackup: Warning: cannot open ./xtrabackup_logfile. will try to find.
InnoDB: Operating system error number 2 in a file operation.
InnoDB: The error means the system cannot find the path specified.
  xtrabackup: Fatal error: cannot find ./xtrabackup_logfile.
xtrabackup: Error: xtrabackup_init_temp_log() failed.

**Comment by sftim** [comment]
Hi @Syed-Saifulla 

I can see that you have provided some diagnostics. I'm guessing that you want to report a bug, get help, or possibly ask for an improvement to the site. Can you explain more about what's on your mind?

/triage needs-information
