### ISSUE TITLE
Kubernetes Windows nodes

### ISSUE THREAD

**Issue by aaronsssya** [kubernetes/website#24717]
In our Cluster, we have a LoadBalancer to handle Control Plane API-Server. After Windows patch kb4570333, our self sign certification cannot support gMSA any more. our windows node cannot call gMSA-service to get AD authen work.

**Comment by sftim** [comment]
/kind support

@aaronsssya you will have to look elsewhere for help with Kubernetes. Given there's only one relevant vendor, how about starting from https://docs.microsoft.com/en-gb/virtualization/windowscontainers/communitylinks ?
