### ISSUE TITLE
404 Page not found for install minikube page

### ISSUE THREAD

**Issue by mrdulin** [kubernetes/website#24716]
Chinese doc Link: https://kubernetes.io/zh/docs/tasks/tools/install-minikube/

**Comment by sftim** [comment]
/language zh
@mrdulin where is the page that hyperlinks to https://kubernetes.io/zh/docs/tasks/tools/install-minikube/ ?

**Comment by sftim** [comment]
Chinese localization team: consider adding a redirect, based on the English localization's redirects for the equivalent page (the target may not be available other than in English though).

**Comment by mrdulin** [comment]
@sftim Sorry for late. Here is the section of the doc: https://kubernetes.io/zh/docs/setup/learning-environment/minikube/#%E5%AE%89%E8%A3%85, click "安装" link, it will navigate to the 404 page.

**Comment by RA489** [comment]
```
$ ./scripts/lsync.sh content/zh/docs/setup/learning-environment/minikube.md
content/en/docs/setup/learning-environment/minikube.md has been removed.
```

**Comment by tengqm** [comment]
the source page is now gone.
/close
