### ISSUE TITLE
Incorrect commands for adding PGP keys to APT configuration

### ISSUE THREAD

**Issue by arnovl-kul** [kubernetes/website#24723]
[UBUNTU 20.04]

[The tutorial for installing container environments](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker) specifies the following command:

`curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -`

This runs into the following error:

`gpg: keyblock resource '/etc/apt/trusted.gpg.d/docker.gpg': No such file or directory`

Update the command to: 

`sudo touch /etc/apt/trusted.gpg.d/docker.gpg`
`curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add --keyring /etc/apt/trusted.gpg.d/docker.gpg -`

Or... use the command which is also mentioned on the [official docker installation page](https://docs.docker.com/engine/install/ubuntu/)

`curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -`

**Comment by sftim** [comment]
Thanks for reporting this. I wonder if we should also recommend that readers `mkdir -p /etc/apt/trusted.gpg.d` ?

/kind bug
/triage accepted
/priority important-longterm
/language en
/sig node

**Comment by arnovl-kul** [comment]
That is a possibility. But I think it would be logical to take over the official documentation of docker.

**Comment by sftim** [comment]
Did PR #24770 help here?
/triage needs-information
/remove-triage accepted

**Comment by sftim** [comment]
/retitle Incorrect commands for adding PGP keys to APT configuration
