### ISSUE TITLE
PodTopologySpread feature is unrelated to its feature gate name

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#24729]
**This is a Bug Report**

**Problem:**

When PodTopologySpread graduated to GA, the reference to its feature gate was lost.
See how it was referred to in older versions https://v1-18.docs.kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#enable-feature-gate
This makes it hard for users to figure when the feature was enabled by default or graduated to GA, unless they explicitly go to an older version of the docs

**Proposed Solution:**

Either:

1. mention the old feature gate name `EvenPodsSpread` so users can refer to 
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ 
1. Add a header that says GA since 1.19? Although I think 1 is sill necessary.

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints

/sig-scheduling

**Comment by alculquicondor** [comment]
cc @Huang-Wei 
@sftim for guidance

**Comment by Huang-Wei** [comment]
Maybe it's fine to add a note to remind users its correlated feature on non-GA versions is `EvenPodsSpread`?

**Comment by sftim** [comment]
> remind users its correlated feature on non-GA versions is `EvenPodsSpread`

Sounds like a good idea.

**Comment by adtac** [comment]
/close
fixed in https://github.com/kubernetes/website/pull/24764
