### ISSUE TITLE
Create two umbrella sections (persistent, ephemeral) for volume concept page

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#24726]
**This is a Feature Request**

The volume concept page has a list of volume types. Break up the volume types into two groups:
* ephemeral
* persistent

From PR (#24077) review:
"The doc seems to be inconsistent about which volume types are persistent and which are ephemeral. Would it be more clear if we broke up this list of volume types into two sections, ephemeral and persistent?"

**What would you like to be added**

Break up the single list of volume types into two sections.

**Why is this needed**
There are many volume types described on the Volume concept page.
By categorizing the volume types, the page should be easier to read and navigate; the new
categories should help differentiate the volume types.

**Comments**
Before starting work, create the break down of volume types into the two categories.

**Comment by kbhawkey** [comment]
For more information , see PR #24077 .

**Comment by geoffcline** [comment]
I would like this issue assigned to me. I have a draft in progress that is related.

**Comment by kbhawkey** [comment]
Yes @geoffcline , you can assign yourself!

**Comment by geoffcline** [comment]
:D 

/assign

**Comment by sftim** [comment]
One option here: have the concept page _list_ the types of storage; move all or some of details for each volume type into new page(s) in the reference section.

**Comment by kbhawkey** [comment]
I suggest to read through the other pages in this section, especially,
`ephemeral-volumes.md` and `persistent-volumes.md`. There are links in these pages that
refer back to the volume types in `volumes.md`.
