### ISSUE TITLE
404 link in Chinese page '使用 Helm 安装 Service Catalog'

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#24733]
**This is a Bug Report**

**Problem:**
404 link in Chinese page '使用 Helm 安装 Service Catalog'.
Page : https://kubernetes.io/zh/docs/tasks/service-catalog/install-service-catalog-using-helm/
Link : 服务目录

**Proposed Solution:**
Change to right link

**Page to Update:**
https://kubernetes.io/zh/docs/tasks/service-catalog/install-service-catalog-using-helm/

**Comment by ydcool** [comment]
Seems solved in #24734 , close now
/close

@gaoguangze111 you can comment `closed: #<issue_id>` in your PR next time so the issue it solved will closed automatically as soon as your PR was merged.
