### ISSUE TITLE
.editorconfig causing white space to be stripped from the end of lines in .md files

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#24731]
**This is a Bug Report**

**Problem:**
`.editorconfig` is mis-configured for markdown files, and is stripping white space at the end of lines. Markdown uses these spaces for formatting in some casees.
Currently, if the .editorconfig file is being used (via plugin or whatnot), then these formatting cues can be removed on save.

**Proposed Solution:**
add the following after the `[*]` section in the `.editorconfig` file.

```
[*.md]
trim_trailing_whitespace = false
```

**dotfile to Update:**
.editorconfig

**Test environment**
MacOS 10.14.6

Both of:
* VS Code using [EditorConfig for VS Code](https://editorconfig.org/)
* neovim using [editorconfig-vim](https://github.com/editorconfig/editorconfig-vim)

**Comment by sftim** [comment]
Good spot
/kind bug
/triage accepted
/priority backlog
