### ISSUE TITLE
Clarify “Exposing Your App” tutorial

### ISSUE THREAD

**Issue by CLS-CLS** [kubernetes/website#24766]
after introducing the concept of service , creating a service on the deployment and not in the pod or the node was counter intuitive. It is not clear why we created the service using the deployment or if we could do it using the pod for example.

**Comment by sftim** [comment]
/retitle Clarify “Exposing Your App” tutorial

The aim is to explain why you create _one_ service for an application, rather than exposing each replica as its own Service.

**Comment by CLS-CLS** [comment]
> /retitle Clarify “Exposing Your App” tutorial
> 
> The aim is to explain why you create _one_ service for an application, rather than exposing each replica as its own Service.
Thank you for clarifying this,
I  believe your answer should be at that tutorial like "
To create a new service and expose it to external traffic we’ll use the expose command with NodePort as parameter (minikube does not support the LoadBalancer option yet). _In order to create one service for an application, rather than exposing each replica as its own Service we expose the deployment"_
