### ISSUE TITLE
Issue with k8s.io/de/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by wemiprog** [kubernetes/website#24762]
"Ander Installationsmethoden" here https://kubernetes.io/de/docs/tasks/tools/install-minikube/#linux should not be a link to github but to this link:
https://minikube.sigs.k8s.io/docs/start/

**Comment by sftim** [comment]
/language de
/kind cleanup
/priority backlog

Actually https://kubernetes.io/de/docs/tasks/tools/install-minikube/ should either redirect to the (English) page, https://minikube.sigs.k8s.io/docs/start/ or it should be a stub that links there and explains that the documentation for Minikube is not localized.
