### ISSUE TITLE
Multiple way to refer to Deployment resource confusing in Deployment concept page

### ISSUE THREAD

**Issue by EHJ-52n** [kubernetes/website#24815]
#### Context

I am following the minikube tutorial ([current section](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment)) and find two different ways to getting the roll-out status of an deployment:

`kubectl rollout status deployment/nginx-deployment`

vs.

`kubectl rollout status deployment.v1.apps/nginx-deployment`

I am using locally:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

```
minikube version
minikube version: v1.13.1
commit: 1fd1f67f338cbab4b3e5a6e4c71c551f522ca138-dirty
```

What is the difference between these two?

Might be a good idea to add a node to step number 3 which explains this.

**Comment by sftim** [comment]
I think that an appropriate improvement that's in line with your comment @EHJ-52n is to change https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ to run `kubectl rollout status deployment/nginx-deployment` instead.

That sounds reasonable to do.
/language en
/kind cleanup
/triage accepted
/help

**Comment by sftim** [comment]
/retitle Multiple way to refer to Deployment resource confusing in Deployment concept page
