### ISSUE TITLE
Container runtimes

### ISSUE THREAD

**Issue by rpiteira** [kubernetes/website#24814]
The command gives un error in ubuntu :
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add --keyring /etc/apt/trusted.gpg.d/docker.gpg -

**Comment by sftim** [comment]
@rpiteira I think this is a duplicate of issue #24723 
Would you have time to check that and confirm?

/language en

**Comment by sftim** [comment]
(if it's not a duplicate, please provide the error message and mention the version of Ubuntu that you were using when you saw that error)

**Comment by rpiteira** [comment]
Hi @sftim , It's a duplicate, the problem is the same ;)
