### ISSUE TITLE
[zh] README-zh.md has been outdate

### ISSUE THREAD

**Issue by zhanw15** [kubernetes/website#24834]
**This is Support**

README-zh.md has been outdate, need to be following with README.md.

**Comment by howieyuen** [comment]
I know there exists some differences on purpose for Chinese language,  could you be more specified?

**Comment by tengqm** [comment]
@howieyuen I think this is about PR #24837. However, the proposed PR is not complete. The Chinese page has quite some contents to be sync'ed from English.

**Comment by howieyuen** [comment]
> @howieyuen I think this is about PR #24837. However, the proposed PR is not complete. The Chinese page has quite some contents to be sync'ed from English.

thanks for reporting, I will take a look
