### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/pod-lifecycle/

### ISSUE THREAD

**Issue by rolandabt** [kubernetes/website#24844]
In https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination a new sub-phase Terminating (?) is mentioned without reference anywhere else in the article. Can we fix that?
One could incorrectly assume that terminating is equal to terminated. But from my understanding terminating is still considered Running. - Please correct me if I am wrong :-)

The article list five phases of a pod: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase with Pending, Running and Succeeded/Failed (both representing a Terminated state) as the main ones.
The description of phase Running explicitely mentions the start and restart of containers. This brings out the fact that not all containers are fully up and running, when the pod is considered up and running.
I suggest Terminating should be mentioned here as well.

**Comment by sftim** [comment]
AIUI the “Terminating” text isn't a Pod phase in the API; instead, it's how the `kubectl` tool renders a Pod that has a `terminationGracePeriodSeconds` set.

Let's clarify the page at https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ to clarify that
/language en
/triage accepted
/help

**Comment by Cweiping** [comment]
According to the definition of pod, terminating is not a stage in the pod life cycle.
I will add a note to it.

Reference: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2497
/assign
