### ISSUE TITLE
Improvement for k8s.io/docs/reference/issues-security/security/

### ISSUE THREAD

**Issue by daddy-joseph97** [kubernetes/website#24872]
Regarding the section [here](https://kubernetes.io/docs/reference/issues-security/security/#when-should-i-not-report-a-vulnerability).

```
When Should I NOT Report a Vulnerability?
You need help tuning Kubernetes components for security
You need help applying security related updates
Your issue is not security related
```

if there are authoritative or highly recommended areas and methods to link to, that would be helpful. There is a lot of information out there, sometimes not helpful or misleading. An official direction to where to start would help. I see this as the equivalent of ensuring you don't just announce a deprecation but clearly say what it is deprecated in favor of with link to more info if necessary. Thank you.

**Comment by sftim** [comment]
@daddy-joseph97 can you explain in a bit more detail what's not right with https://k8s.io/docs/reference/issues-security/security/?

I'm afraid I couldn't work out what to fix.
/triage needs-information
