### ISSUE TITLE
add code formatting to commands in expose-external-ip-address tutorial

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#24873]
**This is a Bug Report**
There are some commands in the `expose-external-ip-address` tutorial that are missing
code formatting. This is a request to update those commands and remove any
extra lines in the page.

**Problem:**

The tutorial has commands that are not formatted as code. For example,

kubectl get deployments hello-world

Add code formatting:
`kubectl get deployments hello-world`
 

**Proposed Solution:**
Identify the commands that are missing code formatting.
Add the code formatting to the commands.
Clean up any extra lines in the page.

**Page to Update:**

https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

This is a good issue for a first time contributor.
If you need more information, feel free to ask in this issue.
It is a good idea to build your changes locally.

**Comment by sftim** [comment]
/triage accepted
/language en

Thanks @kbhawkey - another good spot

**Comment by pwalters04** [comment]
Is PR currently being worked on?

**Comment by howieyuen** [comment]
it seems already formatted, right?

**Comment by Evalle** [comment]
@kbhawkey @sftim  I don't see any issues with the page as well, and it looks like it was last modified July 27, 2020 at 4:18. Are we missing something?

**Comment by kbhawkey** [comment]
Let me look. I'd like a first time contributor to work on this issue.

**Comment by kbhawkey** [comment]
The page renders correctly, however, it would be helpful to clean up the formatting of the page
such as extra lines and spaces. Also, the page should use code blocks around any commands (instead of indentation).
Let me know if you need more information. Thanks!

**Comment by frbimo** [comment]
i'm a first timer in kubernetes. But i saw nothing wrong in formatting code nor indentation. Only i think there is missing some instruction in creating `Hello World` apps.
Should be better to follow https://kubernetes.io/docs/tutorials/stateless-application/guestbook. Just my 2cent. 

@kbhawkey wdyt?
