### ISSUE TITLE
为系统守护进程预留计算资源

### ISSUE THREAD

**Issue by julyclyde** [kubernetes/website#24881]
English:
reserved-cpus is meant to define an explicit CPU set for OS system daemons and kubernetes system daemons

Chinese:
reserved-cpus 旨在为操作系统守护程序和 kubernetes 系统守护程序定义一个显式 cpuset

Actually, it does not create a directory in /sys/fs/cgroup/cpuset/ to keep the reserved CPUs in it. What CPU Manager do is to avoid allocating them to Pods.
So, it should be translated as 
reserved-cpus 旨在为操作系统守护程序和 kubernetes 系统守护程序预留一组明确指定编号的CPU

**Comment by tengqm** [comment]
/triage accepted
Would you like propose a patch?

**Comment by julyclyde** [comment]
Yes, I would create a PR later on.
-- 
Ren Xiaolei

**Comment by julyclyde** [comment]
I cannot find dev-<source version>-zh.<team milestone> branch, how can I create a pull request?
May any team member of @kubernetes/website-maintainers help on this?

**Comment by ydcool** [comment]
> I cannot find dev-<source version>-zh.<team milestone> branch, how can I create a pull request?
> May any team member of @kubernetes/website-maintainers help on this?

just fork this repo and create a new branch based on the main branch
