### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/events-stackdriver/

### ISSUE THREAD

**Issue by gennway** [kubernetes/website#24901]
**This is Support**

Hi, I followed the guide https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver/ and it seems like pod doesn't send events to stackdriver, and there are errors from container logs
"1 writer.go:94] Failed to send request to Stackdriver: googleapi: Error 403: The caller does not have permission, forbidden"
GKE's service account has enough permissions I guess "Monitoring Admin + Monitoring Metric Writer" so what am I doing wrong?
1.17.12-gke, and monitoring option on cluster is set to System and workload logging and monitoring

**Comment by kbhawkey** [comment]
Related to #24769
