### ISSUE TITLE
k8s.io/docs/concepts/cluster-administration/system-metrics/ links to empty list of stable metrics

### ISSUE THREAD

**Issue by davidxia** [kubernetes/website#24915]
The What's Next section [1] has a link for "See the list of stable Kubernetes metrics." But the link goes to a YAML file that's just an empty array. Is this intentional?

1: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#what-s-next

**Comment by sftim** [comment]
I'm not sure where the canonical list of metrics might be, but there are more than zero of them.

/kind bug
/triage accepted
/sig instrumentation

**Comment by ehashman** [comment]
@sftim There are currently not. We don't have any stable metrics yet.

/close

**Comment by davidxia** [comment]
Thanks for the info. Might be good to clarify in the docs here \[1\] then that if the list is empty, it's accurate. 🤷‍♂️ 

1: https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#what-s-next

**Comment by ehashman** [comment]
@davidxia they're targeted for 1.21, so next release.
