### ISSUE TITLE
How to setup dynamic service allocation in k8s

### ISSUE THREAD

**Issue by dhandma** [kubernetes/website#24953]
Hi team, 
I have a sitiation where , I am deploying war files on tomcat using k8s and exposing deployment as node port. All things are automated using cicd so that when new use comes with war file , he is getting tomcat based applciation ready but every time  node port is changing . I need an help so that when user is coming with some war file, I should ask him what is the service name he wants (eg http://example.com/context_root) and based on that, I should provide him ready to use service , instead of "http://worker-node-IP-Address:nodePort/context_root" as URL. Please suggest how can I achieve this?

**Comment by sftim** [comment]
Does https://kubernetes.io/docs/concepts/services-networking/ingress/ help you find the documentation you wanted, @dhandma ?

As you read that and if you still have questions, please note those down and share them.
/triage needs-information
