### ISSUE TITLE
Calico does not exist on Network modes section in Intro to Windows support in Kubernetes

### ISSUE THREAD

**Issue by sakaia** [kubernetes/website#24952]
Calico is not listed on network modes.
Is there any reason?

- [(k8s)network modes](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#network-modes)
- [Calico for Windows](https://docs.projectcalico.org/getting-started/windows-calico/)
- [Calico for Windows goes open source September 22, 2020](https://cloudblogs.microsoft.com/opensource/2020/09/22/calico-for-windows-goes-open-source/)

**Comment by sftim** [comment]
Hi @sakaia 

Can you confirm the page you're discussing and which section you're focusing this issue report on?
If what's documented there won't work without 3rd party software (such as Calico), we can track a defect to document what you need to make things work.

/triage needs-information

**Comment by sakaia** [comment]
Thank you for your comments.

I understand the document description area.
