### ISSUE TITLE
kube proxy userspace docs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#24950]
**This is a Bug Report**

**Problem:**

In general the userspace proxy isnt used much , we should note that in the docs 

The userspace for kube proxy has a couple of use cases worth mentioning:

- if people want to make their own proxy with custom behaviour (antrea, cilliim, calico?) , they can borrow from it, or look at a minimal reference implementation of a kube proxy
- The kube proxy is only configurable by confgimap even though it has several argument options, which can be used for GENERATING a config map.
  - edit the kube-proxy configmap
  - restart all kube proxy pods (i.e. delete them, and the ds will bounce em)
- The users-space proxy creates a new go routine for every service, this is rarely used, as kernel proxies (which use HNS, IPTables, IPVS, and so on) are much faster and scalable.

.............. 

```
I1108 18:11:18.887324       1 server_others.go:186] Using iptables Proxier.
I1108 18:11:18.887599       1 server.go:650] Version: v1.19.1
I1108 18:11:18.887958       1 conntrack.go:52] Setting nf_conntrack_max to 393216
```

And the userspace proxier:

```
1108 18:26:29.451576       1 server_others.go:111] kube-proxy node IP is an IPv4 address (172.18.0.4), assume IPv4 operation
I1108 18:26:29.472040       1 server_others.go:344] Using userspace Proxier.
I1108 18:26:29.489305       1 server.go:650] Version: v1.19.1
I1108 18:26:29.489557       1 conntrack.go:52] Setting nf_conntrack_max to 393216
```

If nothing else, at least mentioning that there are 4 different kube proxies, the newer ones are ipvs and iptables, and that some CNI providers are implementing kube proxy on their own, so you may not need to run kube proxy, that would be a good enough start i guess. 

**Proposed Solution:**

Add a quick description of the 4 kube proxy modes, (there are also some good external blog posts like https://rtfm.co.ua/en/kubernetes-service-load-balancing-kube-proxy-and-iptables/  which go over some of this stuff.

**Page to Update:**

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

**Comment by jayunit100** [comment]
@distributethe6ix

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/ is pretty much generated documentation and I'm fine with that.

IMO it'd be good to _hyperlink_ from there to https://kubernetes.io/docs/concepts/cluster-administration/proxies/
(which might actually belong in the Services & Networking grouping anyway).

@jayunit100 how does that sound?

**Comment by jayunit100** [comment]
Yeah I guess the issue is that there's very little docs about kube-proxy on the hyperlinked page, only like 4 lines :). So need to flesh that out

**Comment by sftim** [comment]
:+1: to expanding https://kubernetes.io/docs/concepts/cluster-administration/proxies/

**Comment by jayunit100** [comment]
@distributethe6ix

**Comment by tengqm** [comment]
A different idea would be fixing/splitting the concepts/services-networking/service.md file so that kube-proxy specific contents can be provided in a separate section. Currently the content is embedded in https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies

**Comment by sftim** [comment]
We could split some of the behind-the-scenes kube-proxy details into the reference section. After all, you could in theory deploy a compliant node (passing all tests) without running any of the existing kube-proxy code.

**Comment by sftim** [comment]
There is no userspace mode in kube-proxy any more.

/close
