### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/common-labels/

### ISSUE THREAD

**Issue by mapdegree** [kubernetes/website#24969]
I would appreciate, if you could set an example in the Kubernetes.io documentation on how to label specific **processor unit types** of K8S worker nodes. 

We have seen a lot of `nvidia` tags in examples on the Internet for describing K8S nodes which are vendor specific, so we want to avoid that.

For example, we have `kubernetes.io/os: windows` for the operating system and `kubernetes.io/arch: amd64` for architecture, we would appreciate, if you could introduce in the documentation an example for a **processing type** of worker nodes.

Here is a proposal as we are referring iy is a 'processing unit':

kubernetes.io/pu: gpu
kubernetes.io/pu: cpu
kubernetes.io/pu: vpu

Could you please review and add an example?

Many thanks,
Dejan

**Comment by sftim** [comment]
Hi @mapdegree 

There is no Kubernetes convention for the labelling you have in mind.
Perhaps you'd like to suggest adding convention? This would be best made as a feature request to [Kubernetes](https://github.com/kubernetes/kubernetes/issues/new/choose).

Remember, it's also OK if a bunch of vendors agree on a different label key, eg `vendorforum.example/processor-unit-type`.

**Comment by sftim** [comment]
Once there is a convention, either _de jure_ or _de facto_, we can document it.
