### ISSUE TITLE
Wrong branch name in “Choose which branch to use”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#24973]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/contribute/new-content/overview/#choose-which-git-branch-to-use lists the wrong branch for new features. It should say eg `dev-1.20` but it actually says `dev-release-1.20`.

**Proposed Solution:**
Fix that page to use the right `skew` shortcode.

**Page to Update:**
https://kubernetes.io/docs/contribute/new-content/overview/

**Additional Information:**
/language en
/help
/kind bug

**Comment by kbhawkey** [comment]
See related PR #24994 .
Close this issue?
