### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by prmis** [kubernetes/website#24987]
Why do support FQDN/DNS base egress rule support by Network policy? This is a critical feature in terms of dynamic ACL management for external traffic.

**Comment by tengqm** [comment]
/sig network

Is this a documentation issue?

**Comment by sftim** [comment]
@prmis if you wanted to request an improvement to the NetworkPolicy feature, take a look at https://github.com/kubernetes/kubernetes/issues/new/choose (and also https://www.kubernetes.dev/docs/guide/first-contribution/#file-an-issue)
