### ISSUE TITLE
Issue with /docs/tutorials/services/source-ip/

### ISSUE THREAD

**Issue by ztenat1211** [kubernetes/website#2499]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
run kubectl annotate service nodeport service.beta.kubernetes.io/external-traffic=OnlyLocal.when  there are local endpoints,packets sent to the node are also  dropped. I see the iptable as follow:
Chain KUBE-NODEPORTS (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 KUBE-XLB-XP7QDA4CRQ2QA33W  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/nodeport: */ tcp dpt:31449

Chain KUBE-XLB-XP7QDA4CRQ2QA33W (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 KUBE-MARK-DROP  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/nodeport: has no local endpoints */

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

1.5

**Comment by zacharysarah** [comment]
@ztenat1211 Thanks for opening this issue. Can you indicate a proposed solution?
