### ISSUE TITLE
Document feature gate CSIServiceAccountToken

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25014]
**This is a Bug Report**

**Problem:**
The v1.20 documentation mentions a feature gate named CSIServiceAccountToken but there is no documentation for this feature gate or for the behavior that it provides.

**Proposed Solution:**
Document the feature

**Kubernetes Version:**
v1.20

**Additional Information:**
/kind bug
Relevant to https://github.com/kubernetes/website/pull/24754#pullrequestreview-529635262 and https://github.com/kubernetes/website/pull/24138

**Comment by annajung** [comment]
PR created https://github.com/kubernetes/website/pull/25028

**Comment by annajung** [comment]
PR merged

/close
