### ISSUE TITLE
add new docs contributor videos 

### ISSUE THREAD

**Issue by geoffcline** [kubernetes/website#25043]
**This is a Feature Request**

**What would you like to be added**
A learning path for new docs contributors. Topics include: getting started with git, how the k8s community uses github, signing the CNCF agreement. 

The learning path would include existing external content where appropriate (github training), but further includes custom videos for project specific knowledge. 

The learning path may include a list of links, a youtube playlist, etc. 

**Why is this needed**
New contributors often take a bit to adjust to how the k8s docs community works. This learning path would help ease that transition. 

**Comments**

This was discussed at the quarterly planning meeting in October, and the group decided it was worth actioning.

**Comment by geoffcline** [comment]
related to

adding git tutorial content to k8s website https://github.com/kubernetes/website/issues/20485

concept of a skill tree https://github.com/kubernetes/website/issues/18887

**Comment by sftim** [comment]
@geoffcline I think this is a duplicate of https://github.com/kubernetes/community/issues/4953
Is this OK to close?

**Comment by geoffcline** [comment]
yep! I didn't think to search there.
