### ISSUE TITLE
Document how to validate kubectl binary against checksum / signature

### ISSUE THREAD

**Issue by tcarland** [kubernetes/website#25040]
There are no details or instructions on how to validate the binary downloaded from this page via some form of checksum, sha256 or otherwise. For automation purposes, eg. ansible playbook, being able to validate any binary downloads is a requirement of project stakeholders.

**Comment by tcarland** [comment]
the file is there as kubectl.sha256 afterall

**Comment by sftim** [comment]
/retitle Document how to validate kubectl binary against checksum / signature
/language en
/kind feature
/triage accepted

The page in question is https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by sftim** [comment]
To fix this:
- update https://kubernetes.io/docs/tasks/tools/install-kubectl/ to use download links from https://dl.k8s.io/
  for example https://dl.k8s.io/v1.19.0/bin/linux/amd64/kubectl
- also explain to readers that checksum files are available that they can use to compare binaries obtained from elsewhere
  for example https://dl.k8s.io/v1.19.0/bin/linux/amd64/kubectl.sha256

The `{{< skew … >}}` and `{{< param "fullversion" >}}` shortcodes are useful for automatically filling in the current Kubernetes version.

/help
/sig cli

**Comment by nate-double-u** [comment]
I may be able to help with this
/assign
