### ISSUE TITLE
对 kubeadm 进行故障排查

### ISSUE THREAD

**Issue by hejun126** [kubernetes/website#25054]
kubeadm init --kubernetes-version=1.19.1 --apiserver-advertise-address=192.168.15.231 --image-repository registry.aliyuncs.com/google_containers --service-cidr=10.1.0.0/16 --pod-network-cidr=10.244.0.0/16
[ERROR Port-10250]: Port 10250 is in use
use kubeadm reset; 
it is not used;

**Comment by ydcool** [comment]
Duplicate of #25055 , closed.
/close
