### ISSUE TITLE
对 kubeadm 进行故障排查

### ISSUE THREAD

**Issue by hejun126** [kubernetes/website#25055]
kubeadm init --kubernetes-version=1.19.1 --apiserver-advertise-address=192.168.15.231 --image-repository registry.aliyuncs.com/google_containers --service-cidr=10.1.0.0/16 --pod-network-cidr=10.244.0.0/16
result is:
[ERROR Port-10250]: Port 10250 is in use
use kubeadm reset command
it is not working

**Comment by ydcool** [comment]
Maybe you should check the usage of port 10250 on your host using `netstat`.
BTW, issues here are aimed for documentation, and you can go [kubeadm](https://github.com/kubernetes/kubeadm) for more technical help.

**Comment by hejun126** [comment]
This port is because the systemctl enable kubelet command is used. This process takes up four ports 10255 10250 10248 40062

**Comment by RA489** [comment]
@hejun126 The command `kubeadm reset` didn't worked out for you?

**Comment by hejun126** [comment]
@RA489 YES,it is not working。

**Comment by tengqm** [comment]
why don't you kubectl stop kubelet and retry?

**Comment by hejun126** [comment]
kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.15.231 --image-repository registry.aliyuncs.com/google_containers

**Comment by hejun126** [comment]
result is:
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
	
	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in docker:
		- 'docker ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'docker logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster

**Comment by hejun126** [comment]
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:15:05Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by hejun126** [comment]
kubelet --version
Kubernetes v1.19.4

**Comment by hejun126** [comment]
docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-162.git64e9980.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Wed Jul  1 14:56:42 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-162.git64e9980.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      64e9980/1.13.1
 Built:           Wed Jul  1 14:56:42 2020
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by tengqm** [comment]
@hejun126 Not sure if your docker version is supported. You may try ask questions on stackoverflow.com or on #kubernetes-users channel, because this doesn't look like a documentation error. If you find something to improve on the doc side (e.g. https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker) please file another issue.

/close

**Comment by hejun126** [comment]
add  --v=6   to command 
 kubeadm init --pod-network-cidr=10.244.0.0/16 --image-repository registry.aliyuncs.com/google_containers --v=6
result is:
I1118 10:13:22.541992   88868 round_trippers.go:443] GET https://192.168.15.231:6443/healthz?timeout=10s  in 0 milliseconds

**Comment by hejun126** [comment]
netstat -tlunp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      89368/kubelet       
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      36212/java          
tcp        0      0 0.0.0.0:9300            0.0.0.0:*               LISTEN      36212/java          
tcp        0      0 127.0.0.1:38882         0.0.0.0:*               LISTEN      89368/kubelet       
tcp        0      0 192.168.15.231:10050    0.0.0.0:*               LISTEN      28461/zabbix_agentd 
tcp        0      0 192.168.15.231:12358    0.0.0.0:*               LISTEN      19990/sshd          
tcp6       0      0 :::10250                :::*                    LISTEN      89368/kubelet
