### ISSUE TITLE
Kubernetes 组件

### ISSUE THREAD

**Issue by MasterLover** [kubernetes/website#25065]
zh docs the picture display error
`![Components of Kubernetes](/images/docs/components-of-kubernetes.svg) `

**Comment by tengqm** [comment]
cannot reproduce

**Comment by sftim** [comment]
@MasterLover what was the URL of the page that you visited where you saw a broken image?

/triage needs-information
/language zh

**Comment by MasterLover** [comment]
It has been fixed
