### ISSUE TITLE
[zh] typo : 云控制器管理器的基础概念 

### ISSUE THREAD

**Issue by yuandongx** [kubernetes/website#25060]
https://github.com/kubernetes/website/blame/master/content/zh/docs/concepts/architecture/cloud-controller.md#L22
![image](https://user-images.githubusercontent.com/35824522/99223061-be31d980-281e-11eb-8aa4-d243615d9f37.png)

**Comment by tengqm** [comment]
/triage accepted

Mind propose a PR?
