### ISSUE TITLE
Intro to Windows support in Kubernetes

### ISSUE THREAD

**Issue by brianharwell** [kubernetes/website#25069]
Why did Kubernetes v1.19 drop support for Windows 1809 which is a long term support release?

Switching to a semi annual release causes many support issues due to the constant need to upgrade due to Microsoft dropping support.

**Comment by tengqm** [comment]
@brianharwell It doesn't look to me like a doc issue. I have posted your question with link to this issue to the #sig-windows channel on slack. Hopefully you can get some support there.
/kind support
/sig windows

**Comment by tengqm** [comment]
From Tim Horlacher on slack:

> They dropped support for the SAC Release of Windows 1809. The LTS Version of Windows 1809 is still supported.

/close

**Comment by brianharwell** [comment]
Thanks @tengqm !
