### ISSUE TITLE
Dated content for “Force Delete StatefulSet Pods”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25066]
**This is a Bug Report**

**Problem:**
[Force Delete StatefulSet Pods](https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/) has some shortcomings:
- the page mentions old versions of Kubernetes, around the v1.5 release
- the page doesn't mention any steps for graceful deletion, which you might try first. eg `kubectl scale statefulset foo --replicas 0 && kubectl delete statefulset foo`

**Proposed Solution:**
- Check that the content is accurate
- If necessary, update it
- Link to the page about [owner references](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents) and to the [Pod termination](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) topic.

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/

**Additional Information:**
/language en

**Comment by prankul88** [comment]
triage/accepted

**Comment by sftim** [comment]
@prankul88 you might need to become a Kubernetes org member to be able to triage issues. If you're not, please do take that step!

**Comment by prankul88** [comment]
@sftim I am already a member of k8s org. Not sure why it didnt work :(
