### ISSUE TITLE
Extend the Kubernetes API with CustomResourceDefinitions

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#25064]
In the "[Field Pruning](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#field-pruning )" section there is a text box referring to the conversion from CRDs defined with apiVersion: apiextensions.k8s.io/v1beta1 to apiVersion: apiextensions.k8s.io/v1.
It says (second and final paragraph in that text box):

_For migrated CustomResourceDefinitions where spec.preserveUnknownFields is set, pruning is not enabled and you can store arbitrary data. For best compatibility, you should update your custom resources to meet an OpenAPI schema, and you should set spec.preserveUnknownFields to true for the CustomResourceDefinition itself._

I think it is wrong. As we aim for CRD objects defined according to apiextensions.k8s.io/v1beta1 to become RIGHT (as much as possible) CRD objects according to apiextensions.k8s.io/v1 (once converted) I think it should say instead (second sentence in that paragraph):

For best compatibility, you should update your custom objects to meet an structural OpenAPI schema, and you should set spec.preserveUnknownFields to false for the CustomResourceDefinition itself where to also specify that structural OpenAPI schema for each defined custom resource version.

**Comment by sftim** [comment]
Seems to me that we should write the page to help readers switch to `x-kubernetes-preserve-unknown-fields`, provided that they are happy that all the clients are accessing via `apiextensions.k8s.io/v1`.

Does that sound right?
/sig api-machinery

**Comment by antaloala** [comment]
To be honest, I do not know.
When reading that text box (I read it many times) I understand (but not 100% sure) that the writer is thinking on updating an existing CRD object that refers to "apiVersion: apiextensions.k8s.io/v1beta1" so the resulting updated CRD object can better match the expectations for a CRD object compliant to "apiextensions.k8s.io/v1beta1" (when conversion is applied). But the writer was not really thinking on anyone updating that existing apiextensions.k8s.io/v1beta CRD object so it now becomes an apiextensions.k8s.io/v1 CRD object
(some clarification on this would be really helpful as if both apiextensions.k8s.io/v1beta1 and apiextensions.k8s.io/v1 are supported in the target k8s API server the, if proposing to perform some update on existing CRD objects, why not to directly adapt them to new apiextensions.k8s.io/v1 ?)

I just checked (in a 1.19 k8s cluster) that it is possible to set "x-kubernetes-preserve-unknown-fields: true" inside the "validation" stanza of an "apiextensions.k8s.io/v1beta1" CRD object.
Is it possible/understood (by API server) in a pre 1.16 k8s cluster not supporting the newer "apiextensions.k8s.io/v1"?

**Comment by sftim** [comment]
@kubernetes/sig-api-machinery-misc what should we document here?

**Comment by apelisse** [comment]
I only partially understand this problem, and don't want to create additional confusion at that point :-)

I'll let Stefan answer, I think he authored that documentation. @sttts

**Comment by antaloala** [comment]
I realize now I made some mistakes in my first answer to @sftim making difficult to understand my comment.
First paragraph should say:


When reading that text box (I read it many times) I understand (but not 100% sure) that the writer is thinking on updating an existing CRD object that was originally created with "apiVersion: apiextensions.k8s.io/v1beta1" so the resulting updated CRD object can better match the expectations for a CRD object compliant to "apiextensions.k8s.io/v1" (once conversion to this second group-version is applied). And so also presuming (after those so many reads) the writer was not really thinking on anyone updating that existing "apiextensions.k8s.io/v1beta" CRD object so it sets "apiVersion: apiextensions.k8s.io/v1".
(some clarification on all this would be really helpful inside that text box); related question: if both "apiextensions.k8s.io/v1beta1" and "apiextensions.k8s.io/v1" are supported in the target k8s API server (i.e. k8s semver >= 1.16) why then not directly to propose to update the existing CRD objects to "apiVersion: apiextensions.k8s.io/v1" ?)

**Comment by sttts** [comment]
We should not encourage the use of `x-kubernetes-preserve-unknown-fields`. In by far most cases, it is not good idea, especially when it is used the root of a CRD schema.

In general, we want to encourage users of CRDs to get rid of unpruned semantics. In v1 CRDs this is enforced. But if you create a CRD as v1beta1 and then query the v1 conversion of that CRD (note that kube-apiserver will transparently convert back and force in the background) will have `preserveUnknownFields: true` although a new v1 CRD could not be created. In other words, the only way to get a v1 CRD with `preserveUnknownFields: true` is to create it as v1beta1 and then retrieve it as v1.

I agree the existing sentence is wrong:

> For migrated CustomResourceDefinitions where spec.preserveUnknownFields is set, pruning is not enabled and you can store arbitrary data. For best compatibility, you should update your custom resources to meet an OpenAPI schema, and you should set spec.preserveUnknownFields to true for the CustomResourceDefinition itself.

This should rather be this:

> For legacy CustomResourceDefinitions created as `apiextensions.k8s.io/v1beta1` where spec.preserveUnknownFields is set to true, pruning is not enabled and you can store arbitrary data. For compatibility with `apiextensions.k8s.io/v1`, you should update your custom resources definition to (1) have a structural OpenAPI schema, and (2) you should set spec.preserveUnknownFields to false. In Kubernetes 1.22 the `apiextensions.k8s.io/v1beta1` API will be removed, and every CustomResourceDefinition must be created via `apiextensions/v1`, and this enforces both (1) and (2).

**Comment by antaloala** [comment]
This proposed update would really help to the reader ;-)

**Comment by antaloala** [comment]
I just checked it was not solved in just released 1.20 documentation
