### ISSUE TITLE
sync video block (uk)

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#25117]
**This is a Feature Request**

add 
![1](https://user-images.githubusercontent.com/26163841/99699561-c007d100-2a9a-11eb-9b91-2cc43c08ee8e.jpg)

/language uk
/assign
/area web-development

**Comment by sftim** [comment]
This report is about https://k8s.io/uk/
To fix this, copy and translate the equivalent block from the English documentation.

/triage accepted

**Comment by sftim** [comment]
This is a content change though.
/remove-area web-development
