### ISSUE TITLE
typo in Install Tools docs

### ISSUE THREAD

**Issue by kosehy** [kubernetes/website#25148]
In the second sentence of the first paragraph under [kind](https://kubernetes.io/docs/tasks/tools/#kind):
"This tool it requires that you have Docker installed and configured."
Is it better to remove "it"?

My suggestion is remove "it"
"This tool requires that you have Docker installed and configured."

**Comment by sftim** [comment]
/triage accepted
/language en
/kind bug
/good-first-issue
/priority backlog

Thanks @kosehy - I agree with your suggested fix.
