### ISSUE TITLE
typo in authentication docs

### ISSUE THREAD

**Issue by nhomble** [kubernetes/website#25144]
https://kubernetes.io/docs/reference/access-authn-authz/authentication/

In the openid svg, there's a typo in ```access_token``` - the diagram has **acces_token**

**Comment by shuuji3** [comment]
Thank you for reporting the typo.🙂 I'd like to this fix.

/assign

**Comment by sftim** [comment]
/triage accepted
/kind bug
/priority backlog
/sig auth
/language en

Thanks!

**Comment by shuuji3** [comment]
Fixed by #25168.
