### ISSUE TITLE
Outdated info in https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by arjanvdberg** [kubernetes/website#25143]
**This is a Bug Report**

**Problem:** The tutorial states that "minikube does not support the LoadBalancer option yet". However, minikube currently does support this option, so the comment is not valid anymore. The tutorial could also be updated to use the LoadBalancer option.

**Proposed Solution:** At least remove the part stating that  the LoadBalancer option doesn't work in minikube. Optionally update the tutorial to use the LoadBalancer option.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

**Comment by prankul88** [comment]
+1 for updating this.

**Comment by rodrigobercini** [comment]
+1

It was rather confusing when I saw this text in the tutorial, especially because I used the loadbalancer service in another minikube tutorial.

Should be an easy fix (i.e. removing the last part)
