### ISSUE TITLE
Improve explanation about out-of-resource eviction signals for CPU resource.

### ISSUE THREAD

**Issue by bbgobie** [kubernetes/website#25149]
Either I'm misunderstanding something or the page is a bit confusing in regards to how evictions happen, the QOS classes and CPU.

Having a CPU request != cpu limit or cpu limit not defined makes the pod class automatically burstable or best effort.
https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/

However this doc seems to imply the QOS class is used to determine eviction which would imply a pod can be evicted for not defining cpu or going over cpu requests.
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods

I don't believe a pod can be evicted for CPU because the system can always continue to run and gain back CPU it needs, whereas memory disk are harder to reclaim.  Thus CPU does not provide an eviction signal

https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-signals

**Comment by sftim** [comment]
/retitle Improve explanation about out-of-resource eviction signals for CPU resource.

https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#node-conditions lists the conditions that can trigger eviction actions; these are specifically `MemoryPressure` and `DiskPressure`. As you have noted, `CPUPressure` is not a thing in Kubernetes.

https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-signals confirms this.

@bbgobie it is a complicated topic to explain; can you suggest a change that you feel would explain it better?

**Comment by Cweiping** [comment]
In my opinion, CPU is an elastic resource, and there is no need to trigger pod eviction when exceeding it; QoS scheduling only depends on `cpu.request` and `cpu.limit` Distribute.Unable to trigger eviction based on increased CPU usage.

**Comment by bbgobie** [comment]
> /retitle Improve explanation about out-of-resource eviction signals for CPU resource.
> 
> https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#node-conditions lists the conditions that can trigger eviction actions; these are specifically `MemoryPressure` and `DiskPressure`. As you have noted, `CPUPressure` is not a thing in Kubernetes.
> 
> https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-signals confirms this.
> 
> @bbgobie it is a complicated topic to explain; can you suggest a change that you feel would explain it better?

I think your post is actually pretty clear if anyone saw it, so what if the anchor for eviction signals was added to the evicting end user pods section.  Also perhaps there should be a page on compressible resources, I think an explanation would make it pretty clear for many users.

"If the kubelet is unable to reclaim sufficient resource on the node, kubelet begins evicting Pods."
"If the kubelet is unable to reclaim sufficient resources on the node, kublet begins evicting Pods based on [eviction signals](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-signals)"

**Comment by sftim** [comment]
This feels relevant to discussion in #19081

**Comment by sftim** [comment]
/reopen
Might be worth revisiting. If not picked up I would let it get closed by the bot though.
