### ISSUE TITLE
Interactive Tutorial not loading

### ISSUE THREAD

**Issue by birprav93** [kubernetes/website#25170]
Interactive tutorial is not loading even after waiting for long time

**Comment by sftim** [comment]
/retitle Interactive Tutorial not loading
/kind bug
/priority awaiting-more-evidence

Are these symptoms still showing for you @birprav93 ?

If so, could you paste in the URL of the problem page and also attach a screenshot of the “loading” view that you see when waiting?

**Comment by birprav93** [comment]
yes it keeps on showing "loading" and error at the end.

**Comment by birprav93** [comment]
![image](https://user-images.githubusercontent.com/60813228/99915851-876c2f80-2d06-11eb-9a36-edf6c3c3b42f.png)

**Comment by sftim** [comment]
@BenHall would you want to check this one out?

Please _/triage accepted_ if it's valid.

**Comment by BenHall** [comment]
Sorry for the problems. We had an issue over weekend that caused some unavailability. This was resolved and everyone should be able to access the scenarios again .

**Comment by sftim** [comment]
@birprav93 is it OK to close this issue as fixed?

**Comment by birprav93** [comment]
Hello Tim,

I can access now. You can set it to close.Thanks for your help.

Regards,
Praveen

**Comment by sftim** [comment]
Symptoms gone
/close
