### ISSUE TITLE
Mention hysteresis in docs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25172]
**This is a Feature Request**

**What would you like to be added**
- Change the text of https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#oscillation-of-node-conditions to mention “hysteresis”.
- ~Change the text of https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#stabilization-window to mention “hysteresis”.~

**Why is this needed**
The English term for system state being dependent on its prior state is “hysteresis”. It's jargon but it's jargon used inside and outside the field of information technology, and a reader might search the web for that word.

Mentioning the word in the actual documentation is the best form of SEO, so let's do that.

**Comments**
/help
/kind feature
/language en
/priority backlog
/sig node

**Comment by Cweiping** [comment]
Good idea!
/assign

**Comment by tengqm** [comment]
I don't think introducing a word which is not widely used is a good idea. I myself have never read any IT paper/documentation mentioning this term.

**Comment by Cweiping** [comment]
> I don't think introducing a word which is not widely used is a good idea. I myself have never read any IT paper/documentation mentioning this term.

use `delay`?  Example：`delay of node conditions change`.

**Comment by forresthopkinsa** [comment]
I for one would appreciate the specificity of that particular term in k8s documentation. I arrived on this thread trying to find hysteretic systems used in Kubernetes.

**Comment by sftim** [comment]
/remove-lifecycle stale
more discussion might be useful

**Comment by sftim** [comment]
/remove-lifecycle stale
more discussion might be useful (still)

**Comment by ehashman** [comment]
> I don't think introducing a word which is not widely used is a good idea. I myself have never read any IT paper/documentation mentioning this term.

:+1: 

I have never heard this word used before in technical documentation and I don't think it will improve clarity.

**Comment by forresthopkinsa** [comment]
It doesn't have to *replace* the current documentation. It would have helped me if it was only *appended* to the existing explanation of the hysteretic system. If it was included, it _would_ improve clarity for those familiar with the term, and I wouldn't expect it to affect anyone else.

**Comment by peterclauterbach** [comment]
More discussion would help here. I was wondering if or how k8s used hysteresis for controller behavior. There is certainly not a lot about it, and I landed on this issue.
Hysteresis is a room thermostat controlling the heat or air conditioning system.  Monitoring an analog temperature, and then turning the system ON or OFF.  If you trigger this at a single temperature, you get a lot of duty cycles, potentially ruining the equipment. So hysteresis is used to trigger ON and OFF at a temperature slightly above and below the desired set point. The best picture I can find at the moment is a "[noise gate](https://en.wikipedia.org/wiki/Noise_gate#Controls_and_parameters)"
This model has no concept of **time delay**, which is also part of the k8s decision making process. So a particular value has to be above a certain threshold, but also for a specific period of time, before it takes action. There's probably a better word than _hysteresis_.  If there are any visual or illustrated descriptions of k8s, that would clarify the concept.
Interested in hearing other's perspectives.

**Comment by sftim** [comment]
It's a bit of a shame that this feature request is where folks are landing when they search, and not the page we're considering whether to edit.
My take is (still) that even though not all tech folk will know the word, other people will think of it as their first choice of search term when trying to understand how Kubernetes incorporates prior state into controller behavior.

**Comment by sftim** [comment]
Also a strong +1 to visual depictions of controller behavior, especially ones with timelines.

**Comment by peterclauterbach** [comment]
Let’s find the appropriate k8s channel to kick some ideas about.

**Comment by sftim** [comment]
[`#sig-docs`](https://kubernetes.slack.com/messages/sig-docs) is the place for that.

**Comment by sftim** [comment]
/remove-lifecycle rotten

I think there's still debate about whether this is useful.
