### ISSUE TITLE
Ingress Controllers

### ISSUE THREAD

**Issue by ravanapel** [kubernetes/website#25191]
"AWS ALB Ingress Controller" is renamed to "AWS Load Balancer Controller". Name and link must be updated to "[AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller)".

**Comment by sarnickaa** [comment]
hello! first time contributor here!
Once this issue has been appropriately triaged - I'd be happy to work on it

/assign

**Comment by ravanapel** [comment]
This issue seems to be fixed already.
