### ISSUE TITLE
[zh] replace "(/docs)" to "(/zh/docs)"

### ISSUE THREAD

**Issue by zhaojizhuang** [kubernetes/website#25193]
**This is a Bug Report**
The doc link in zh content should be replaced from `/docs` to `/zh/docs`

**Proposed Solution:**

To find the file ,run the following  step:
```shell
cd website/content/zh
find ./ -type f -name "*.md" | xargs grep "(/docs"
```

**Comment by tengqm** [comment]
we have scripts/linkchecker.py, e.g.

```
./scripts/linkchecker.py -l zh -f /docs/concepts/overview/*.md
```

**Comment by zhaojizhuang** [comment]
![image](https://user-images.githubusercontent.com/3124692/99973940-4560ed80-2ddb-11eb-9c26-a68a5277b818.png)
@tengqm no matches found ,something wrong？

**Comment by tengqm** [comment]
Weird ...  not sure how wildcards work on zsh. Can you try:

```
$ ./scripts/linkchecker.py -l zh -f /docs/concepts/**/*.md
```

**Comment by zhaojizhuang** [comment]
> Weird ... not sure how wildcards work on zsh. Can you try:
> 
> ```
> $ ./scripts/linkchecker.py -l zh -f /docs/concepts/**/*.md
> ```
![image](https://user-images.githubusercontent.com/3124692/100039127-94d90500-2e3f-11eb-92d6-bea95bd94f35.png)

@tengqm not work either for zsh, but it works when i swtich `zsh` to `bash`
![image](https://user-images.githubusercontent.com/3124692/100039301-e7b2bc80-2e3f-11eb-8b0a-a14a55188b12.png)

**Comment by tengqm** [comment]
/close
Links are all localized for zh translation. Anything left should be treated as bugs.
