### ISSUE TITLE
ja: Make docs/concepts/architecture/controller.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#25204]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/architecture/controller.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/architecture/controller.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/concepts/architecture/controller.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/architecture/controller.md

diff between translated and v1.18
https://gist.github.com/0ed67084a6bc50a62de7c110af1c5f19

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by KobayashiD27** [comment]
/assign

If this `assign` have problems, please let me know.

**Comment by KobayashiD27** [comment]
This document looks already completed...
@inductor Could you check the document?

**Comment by inductor** [comment]
@KobayashiD27 It looks like so. Thank you for reporting!
/close
