### ISSUE TITLE
ja: Make docs/concepts/configuration/manage-resources-containers.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#25206]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/configuration/manage-resources-containers.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/configuration/manage-resources-containers.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/concepts/configuration/manage-resources-containers.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/configuration/manage-resources-containers.md

diff between translated and v1.18
https://gist.github.com/dad447f1ac6bd6b5f84849e064837fbc

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by makocchi-git** [comment]
**Note**

`manage-resources-containers.md` was renamed as `manage-resources-containers.md` at release 1.18.
Actual diff is [here](https://gist.github.com/makocchi-git/e60386b2e743f69dc921fb270b9c54b5).
