### ISSUE TITLE
ja: Make docs/concepts/containers/container-lifecycle-hooks.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#25208]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/containers/container-lifecycle-hooks.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/containers/container-lifecycle-hooks.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/concepts/containers/container-lifecycle-hooks.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/containers/container-lifecycle-hooks.md

diff between translated and v1.18
https://gist.github.com/20d1a90ec322cb0d2ce7d6951331faf7

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by bells17** [comment]
It seems already followed v1.18 of the original text.

/close
