### ISSUE TITLE
ja: Make docs/reference/kubectl/cheatsheet.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#25216]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/kubectl/cheatsheet.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/kubectl/cheatsheet.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/reference/kubectl/cheatsheet.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/reference/kubectl/cheatsheet.md

diff between translated and v1.18
https://gist.github.com/2aea8bce7dbbd8392e42016c14c7c94f

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by kakts** [comment]
@inductor 
I think docs/reference/kubectl/cheatsheet.md has followed the original text already.


https://github.com/kubernetes/website/commit/c85942837b2da18383bef425821bcccfaa03c66c#diff-d460f005546b3fbc9bd66c6b351666ff8c1f3cf7cebb1def57863854297ff8f9

**Comment by inductor** [comment]
@kakts Actually no. 

For example https://kubernetes.io/ja/docs/reference/kubectl/cheatsheet/#apply is still in the old format

```
-## Apply
+## Kubectl apply
```

**Comment by kakts** [comment]
@inductor 
Exactly. I missed that point you mentioned.
I checked that  #apply is still in the old format.

/triage accepted
