### ISSUE TITLE
ja: Make docs/concepts/extend-kubernetes/operator.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#25210]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/extend-kubernetes/operator.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/extend-kubernetes/operator.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/concepts/extend-kubernetes/operator.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/extend-kubernetes/operator.md

diff between translated and v1.18
https://gist.github.com/43f077a605fa5ecf233e5bb85c5ad034

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by bells17** [comment]
It seems already followed v1.18 of the original text
/close
