### ISSUE TITLE
ja: Make docs/reference/access-authn-authz/authentication.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#25214]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/access-authn-authz/authentication.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/access-authn-authz/authentication.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/reference/access-authn-authz/authentication.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/reference/access-authn-authz/authentication.md

diff between translated and v1.18
https://gist.github.com/ddee0a5001b279921256ae72749152fe

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by kakts** [comment]
@inductor 
Japanese document of docs/reference/access-authn-authz/authentication.md had already followed the original text.
https://github.com/kubernetes/website/commit/7617c96d531e52b4cd2fe9af73d721f8beec1b00#diff-084af2f59441bc80dfd911a624a41f0810dac433c51a2703a7e3f7d509450aab

**Comment by bells17** [comment]
agree.

/close
