### ISSUE TITLE
Improvement for the K8s Interactive Tutorial 

### ISSUE THREAD

**Issue by InvisibleRain** [kubernetes/website#25224]
Hello!
I've been learning the basics of Kubernetes on https://k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/ when stumbled upon a snippet on step 2:
```bash
echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"; kubectl proxy
```
IMO, this may look a bit complicated for a newbie, and also may be leading to just copy/pasting the command instead of understanding how it works. My suggestion would be to remove the extra newlines and the colors from the command so it would look like that:
```bash
echo -e "\nStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"\
kubectl proxy
```
Thank you in advance, and have a nice day!

**Comment by sftim** [comment]
/kind cleanup
/triage accepted

Good suggestion. The environment could also provide, eg, an alias that wraps `kubectl proxy` or a command snippet similar to:
```bash
show-warning kubectl-proxy-terminal-switch && \
kubectl proxy
```
