### ISSUE TITLE
ja: Make docs/tutorials/_index.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#25220]
**This is a Feature Request**

**What would you like to be added**
Update docs/tutorials/_index.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/tutorials/_index.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/tutorials/_index.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/tutorials/_index.md

diff between translated and v1.18
https://gist.github.com/234cb9f766481c67260135e5ddd566f9

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by KobayashiD27** [comment]
I've assigned this task to me, but this document looks already completed.
@inductor Could you check the document?

**Comment by inductor** [comment]
@KobayashiD27 You are right. Thank you very much!

/close
