### ISSUE TITLE
Authenticating - User Impersonation with Service Accounts

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [kubernetes/website#25232]
It would be useful to show the syntax for using impersonation with a Service Account, for example:

kubectl auth can-i --as system:serviceaccount:kube-system:kubernetes-dashboard --list

I didn't know that the system:serviceaccount portion was needed

**Comment by sftim** [comment]
Hi @AdamSharif-MSFT 

Is there a page that you recommend adding that advice to? It'd be useful to know which page you had in mind.
/language en
/kind feature

**Comment by AdamSharif-MSFT** [comment]
Hi @sftim ,
Apologies, yes this is the page I am referring to:

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation

Many thanks!

Adam
