### ISSUE TITLE
[zh] reference section out of sync for 1.19

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#25247]
**Problem:**

docs under `content/zh/reference` section are out of sync from English site.
See the following report:

```
$ ./scripts/lsync.sh content/zh/docs/reference/
22	39	content/en/docs/reference/kubernetes-api/labels-annotations-taints.md
1	4	content/en/docs/reference/scheduling/config.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md
1	1	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
10	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
3	3	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_control-plane.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
0	7	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
2	9	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd_local.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
2	2	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
0	14	content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
17	0	content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
0	2	content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
6	4	content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
0	2	content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
11	0	content/en/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
0	4	content/en/docs/reference/setup-tools/kubeadm/kubeadm-token.md
1	0	content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
41	35	content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
11	5	content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
0	3	content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md
0	1	content/en/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
36	33	content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
108	23	content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
10	9	content/en/docs/reference/command-line-tools-reference/kube-proxy.md
3	2	content/en/docs/reference/command-line-tools-reference/feature-gates.md
385	283	content/en/docs/reference/command-line-tools-reference/kubelet.md
33	25	content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
21	62	content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
2	2	content/en/docs/reference/glossary/platform-developer.md
3	4	content/en/docs/reference/glossary/customresourcedefinition.md
1	1	content/en/docs/reference/glossary/admission-controller.md
11	3	content/en/docs/reference/glossary/cluster-operations.md
1	1	content/en/docs/reference/glossary/configmap.md
1	1	content/en/docs/reference/glossary/preemption.md
1	1	content/en/docs/reference/glossary/container.md
1	1	content/en/docs/reference/glossary/cri-o.md
1	1	content/en/docs/reference/glossary/pod-priority.md
1	1	content/en/docs/reference/glossary/toleration.md
12	0	content/en/docs/reference/glossary/control-plane.md
1	1	content/en/docs/reference/glossary/quantity.md
3	3	content/en/docs/reference/glossary/node.md
11	5	content/en/docs/reference/glossary/replication-controller.md
1	1	content/en/docs/reference/glossary/kubeadm.md
3	4	content/en/docs/reference/glossary/kubelet.md
2	2	content/en/docs/reference/glossary/cluster-infrastructure.md
**removed**	content/en/docs/reference//glossary/rkt.md
3	3	content/en/docs/reference/glossary/taint.md
2	2	content/en/docs/reference/issues-security/security.md
1	1	content/en/docs/reference/kubectl/overview.md
12	0	content/en/docs/reference/kubectl/jsonpath.md
7	0	content/en/docs/reference/kubectl/cheatsheet.md
2	2	content/en/docs/reference/_index.md
27	1	content/en/docs/reference/access-authn-authz/authentication.md
3	3	content/en/docs/reference/access-authn-authz/bootstrap-tokens.md
3	3	content/en/docs/reference/access-authn-authz/authorization.md
72	60	content/en/docs/reference/access-authn-authz/service-accounts-admin.md
**removed**	content/en/docs/reference//access-authn-authz/controlling-access.md
4	4	content/en/docs/reference/access-authn-authz/admission-controllers.md
26	26	content/en/docs/reference/access-authn-authz/rbac.md
111	71	content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
24	2	content/en/docs/reference/access-authn-authz/_index.md
2	2	content/en/docs/reference/tools.md
**removed**	content/en/docs/reference//using-api/api-overview.md
8	438	content/en/docs/reference/using-api/api-concepts.md
4	4	content/en/docs/reference/using-api/deprecation-policy.md
7	4	content/en/docs/reference/using-api/client-libraries.md
1	1	content/en/docs/reference/using-api/server-side-apply.md
12	12	content/en/docs/reference/using-api/health-checks.md
123	2	content/en/docs/reference/using-api/_index.md
```

**Proposed Solution:**

Sync changes from English site.

**Page to Update:**

As listed above.

/help
/language zh

**Comment by howieyuen** [comment]
I am working on the syncing of kubeadm/generated part

**Comment by tengqm** [comment]
> I am working on the syncing of kubeadm/generated part

THANK YOU!

**Comment by tengqm** [comment]
Owner: @howieyuen 

- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_control-plane.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd_local.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-token.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
- [ ] content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md

**Comment by tengqm** [comment]
Owner: @zhaojizhuang, #25257

- [x] content/en/docs/reference//glossary/rkt.md
- [x] content/en/docs/reference//access-authn-authz/controlling-access.md
- [x] content/en/docs/reference//using-api/api-overview.md

**Comment by tengqm** [comment]
Owner: @jialaijun #25244
- [ ] content/en/docs/reference/glossary/platform-developer.md
- [ ] content/en/docs/reference/glossary/customresourcedefinition.md
- [ ] content/en/docs/reference/glossary/admission-controller.md
- [ ] content/en/docs/reference/glossary/cluster-operations.md
- [ ] content/en/docs/reference/glossary/configmap.md
- [ ] content/en/docs/reference/glossary/preemption.md
- [ ] content/en/docs/reference/glossary/container.md
- [ ] content/en/docs/reference/glossary/cri-o.md
- [ ] content/en/docs/reference/glossary/pod-priority.md
- [ ] content/en/docs/reference/glossary/toleration.md
- [ ] content/en/docs/reference/glossary/control-plane.md
- [ ] content/en/docs/reference/glossary/quantity.md
- [ ] content/en/docs/reference/glossary/node.md
- [ ] content/en/docs/reference/glossary/replication-controller.md
- [ ] content/en/docs/reference/glossary/kubeadm.md
- [ ] content/en/docs/reference/glossary/kubelet.md
- [ ] content/en/docs/reference/glossary/cluster-infrastructure.md
- [ ] content/en/docs/reference/glossary/taint.md

**Comment by tengqm** [comment]
Owner: ???

- [ ] content/en/docs/reference/using-api/api-concepts.md
- [ ] content/en/docs/reference/using-api/deprecation-policy.md
- [ ] content/en/docs/reference/using-api/client-libraries.md
- [ ] content/en/docs/reference/using-api/server-side-apply.md
- [ ] content/en/docs/reference/using-api/health-checks.md
- [ ] content/en/docs/reference/using-api/_index.md

**Comment by tengqm** [comment]
Owner: ???

- [ ] content/en/docs/reference/kubernetes-api/labels-annotations-taints.md
- [ ] content/en/docs/reference/scheduling/config.md
- [ ] content/en/docs/reference/issues-security/security.md
- [ ] content/en/docs/reference/kubectl/overview.md
- [ ] content/en/docs/reference/kubectl/jsonpath.md
- [ ] content/en/docs/reference/kubectl/cheatsheet.md
- [ ] content/en/docs/reference/_index.md
- [ ] content/en/docs/reference/tools.md

**Comment by tengqm** [comment]
Owner: ???

- [ ] content/en/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
- [ ] content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
- [ ] content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
- [ ] content/en/docs/reference/command-line-tools-reference/kube-proxy.md

**Comment by tengqm** [comment]
Owner: ???

- [ ] content/en/docs/reference/command-line-tools-reference/feature-gates.md
- [ ] content/en/docs/reference/command-line-tools-reference/kubelet.md
- [ ] content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
- [ ] content/en/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md

**Comment by tengqm** [comment]
Owner: ???
- [ ] content/en/docs/reference/access-authn-authz/authentication.md
- [ ] content/en/docs/reference/access-authn-authz/bootstrap-tokens.md
- [ ] content/en/docs/reference/access-authn-authz/authorization.md
- [ ] content/en/docs/reference/access-authn-authz/service-accounts-admin.md

**Comment by tengqm** [comment]
Owner: ???

- [ ] content/en/docs/reference/access-authn-authz/admission-controllers.md
- [ ] content/en/docs/reference/access-authn-authz/rbac.md
- [ ] content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
- [ ] content/en/docs/reference/access-authn-authz/_index.md

**Comment by tengqm** [comment]
**Hint**: If you are working on `content/en/docs/reference/access-authn-authz/_index.md`, you can check the upstream changes first using the following command. Note that the `en` is replaced by `zh` when running the script:

```shell
./scripts/lsync.sh content/zh/docs/reference/access-authn-authz/_index.md
```

**Comment by zhaojizhuang** [comment]
> Owner: ???
> 
> * [ ]  content/en/docs/reference/using-api/api-concepts.md
> * [ ]  content/en/docs/reference/using-api/deprecation-policy.md
> * [ ]  content/en/docs/reference/using-api/client-libraries.md
> * [ ]  content/en/docs/reference/using-api/server-side-apply.md
> * [ ]  content/en/docs/reference/using-api/health-checks.md
> * [ ]  content/en/docs/reference/using-api/_index.md

@tengqm  happy to sync these `using-api`

**Comment by howieyuen** [comment]
/triage accepted

> Owner: @howieyuen
> 
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_token_list.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-join_etcd.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_all.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-healthcheck-client.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_scheduler.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-kubelet-client.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_control-plane.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-peer.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_apiserver.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join_phase_control-plane-prepare_control-plane.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_controller-manager.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_apply.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_etcd_local.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_apiserver-etcd-client.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_front-proxy-client.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_join.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_certs_etcd-server.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-token.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
> * [ ]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md

https://github.com/kubernetes/website/pull/25267

**Comment by howieyuen** [comment]
https://github.com/kubernetes/website/pull/25275
> Owner: @howieyuen
> 
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-version.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-init-phase.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-token.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-upgrade-phase.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
> * [x]  content/en/docs/reference/setup-tools/kubeadm/kubeadm-reset.md

**Comment by yuandongx** [comment]
> Owner: ???
> 
> * [ ]  content/en/docs/reference/kubernetes-api/labels-annotations-taints.md
> * [ ]  content/en/docs/reference/scheduling/config.md
> * [ ]  content/en/docs/reference/issues-security/security.md
> * [ ]  content/en/docs/reference/kubectl/overview.md
> * [ ]  content/en/docs/reference/kubectl/jsonpath.md
> * [ ]  content/en/docs/reference/kubectl/cheatsheet.md
> * [ ]  content/en/docs/reference/_index.md
> * [ ]  content/en/docs/reference/tools.md

I am interested in these files, be happy to sync en!

**Comment by tengqm** [comment]
@yuandongx Thanks for signing up.

**Comment by howieyuen** [comment]
> Owner: ???
> 
> * [ ]  content/en/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> * [ ]  content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
> * [ ]  content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
> * [ ]  content/en/docs/reference/command-line-tools-reference/kube-proxy.md

let me do it

**Comment by tengqm** [comment]
/close
mostly done.
