### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/names/

### ISSUE THREAD

**Issue by akostadinov** [kubernetes/website#25252]
> By convention, the names of Kubernetes resources should be up to maximum length of 253 characters and consist of lower case alphanumeric characters, -, and ., but certain resources have more specific restrictions.

Please link to document listing objects with stricter name length limitations.

I see a link already [1]. But it is not listing any exceptions as far as i can tell.

[1] https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md

**Comment by tengqm** [comment]
It is not possible to exhaustively list all name conventions. Design proposal is always a proposal, we care more about the things that are landed.
For example, https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

> When creating the manifest for a CronJob resource, make sure the name you provide is a valid DNS subdomain name. The name must be no longer than 52 characters. This is because the CronJob controller will automatically append 11 characters to the job name provided and there is a constraint that the maximum length of a Job name is no more than 63 characters.
