### ISSUE TITLE
kube-apiserver always exit with error ''Time went backwards from"

### ISSUE THREAD

**Issue by soft-way** [kubernetes/website#25262]
The env is:
VM (CentOS 7.9.2009 4 CPU+12G Memory) on virtualbox(6.1) on PC windows 10 (16G Memory, CPU Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz   3.60 GHz) 
docker version: docker-ce-19.03.9-3.el7.x86_64

The procedue is:
run below command:
kubeadm init  --control-plane-endpoint 192.168.1.62:6443 --kubernetes-version v1.19.4 --image-repository registry.dev.xxx.com/k8s_gcr_io --apiserver-advertise-address 192.168.1.62  --service-dns-domain dev.xxx.com --pod-network-cidr 172.18.0.0/16   --apiserver-bind-port 6443   

Error log:
I1127 03:30:24.336751       1 crdregistration_controller.go:111] Starting crd-autoregister controller
I1127 03:30:24.336760       1 shared_informer.go:240] Waiting for caches to sync for crd-autoregister
F1127 03:30:24.369920       1 sample_and_watermark.go:182] Time went backwards from 2020-11-27T03:30:24.369922708Z to 2020-11-27T03:30:24.369901483Z for labelValues=[]string{"executing", "readOnly"}
goroutine 2433 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc00236be00, 0xc7, 0x133)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x71fe8c0, 0xc000000003, 0x0, 0x0, 0xc000135880, 0x70e3bb2, 0x17, 0xb6, 0x0)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x71fe8c0, 0x3, 0x0, 0x0, 0x491cdc8, 0x36, 0xc000e63588, 0x3, 0x3)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1456
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics.(*sampleAndWaterMarkHistograms).innerSet(0xc00013a3c0, 0xc00ad76618)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go:182 +0x62b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics.(*sampleAndWaterMarkHistograms).Set(0xc00013a3c0, 0x4000000000000000)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/sample_and_watermark.go:147 +0x6d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*requestWatermark).recordReadOnly(0x71d35c0, 0x2)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:74 +0x58
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func2(0x7ff2eca500a8, 0xc00ab963b8, 0xc00b0d5200)
	/workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:165 +0x467
net/http.HandlerFunc.ServeHTTP(0xc00537c2a0, 0x7ff2eca500a8, 0xc00ab963b8, 0xc00b0d5200)
	/usr/local/go/src/net/http/server.go:2042 +0x44

**Comment by sftim** [comment]
/kind support

@soft-way, I don't think there is any documentation defect here.

**Comment by soft-way** [comment]
> /kind support
> 
> @soft-way, I don't think there is any documentation defect here.

yes, I will close it, sorry about that.
