### ISSUE TITLE
Translate docs/setup/production-environment/windows/intro-windows-in-kubernetes.md into chinese

### ISSUE THREAD

**Issue by CriaHu** [kubernetes/website#25265]
This is a Feature Request

What would you like to be added

Translate docs/setup/production-environment/windows/intro-windows-in-kubernetes.md into chinese

Why is this needed
Cannot find docs/setup/production-environment/windows/intro-windows-in-kubernetes.md in Chinese
Comments

The page to update:
https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

**Comment by tengqm** [comment]
Done.
See: https://kubernetes.io/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

/close
