### ISSUE TITLE
[zh] Links in Chinese page docs/reference/setup-tools/kubeadm/kubeadm-init-phase not using localized page

### ISSUE THREAD

**Issue by gaoguangze111** [kubernetes/website#25274]
**This is a Bug Report**

**Problem:**
Links in Chinese page docs/reference/setup-tools/kubeadm/kubeadm-init-phase not using localized page

**Proposed Solution:**
Change to localized page link

**Page to Update:**
https://kubernetes.io/zh/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/

**Comment by tengqm** [comment]
/triage accepted
This is being resolved in a resync PR (#25275).
We don't need a separate issue for tracking this.
/close
