### ISSUE TITLE
【ZH】A lame sentence, the Chinese meaning is a little difficult to understand。

### ISSUE THREAD

**Issue by yuandongx** [kubernetes/website#25273]
**This is a Bug Report**

**Problem:**
EN: `This document serves both as a reference to the values and as a coordination point for assigning values.`
ZH: `本文既作为这些标签和注解的参考，也就这些标签和注解的赋值进行了说明。`
**Proposed Solution:**
建议ZH： `本文既可作为这些标签和注解的参考，也可作为赋值的协调点。`

## branch master

![image](https://user-images.githubusercontent.com/35824522/100429527-69207e00-30d0-11eb-8663-a44781828d94.png)

![image](https://user-images.githubusercontent.com/35824522/100429481-58700800-30d0-11eb-983d-babe0c19ac20.png)
language/zh

**Comment by yuandongx** [comment]
language/zh

**Comment by tengqm** [comment]
@yuandongx Thanks for filing this issue.

> 本文既可作为这些标签和注解的参考，也可作为赋值的协调点。

This revision is still not easy to parse. Do you have other suggestions to make the sentence easier to understand?

**Comment by yuandongx** [comment]
How about these?
- `本文既对这些标签和注解的值进行举例说明，也对它们的使用细节上进行阐述。`
or
-  `本文对这些标签和注解进行了使用参数示例，以及对它们的变更和使用技巧进行了说明。`
In fact, the document is only obout `Example`,  `use on`, `Note`, `sense`  for the labels,

**Comment by tengqm** [comment]
关键在于这里的 coordination point 怎么翻译。
我理解的是，如果你想应用一些 labels 或者 annotation，可以先参考以下这里的建议。
社区如果有一些建议，比如针对 hostname，zone 之类的建议，会更新此文档。
通过这个文档来协调大家对 label 和 annotation 的使用。
从这个角度说，现在的翻译： 本文既作为这些标签和注解的参考，也就这些标签和注解的赋值进行了说明。
问题不大。

**Comment by yuandongx** [comment]
I think this issues can be closed.
