### ISSUE TITLE
Korean Localization for dev-1.19-ko.6 branch

### ISSUE THREAD

**Issue by ianychoi** [kubernetes/website#25283]
## In English

**This is a Feature Request**

Korean Localization for `dev-1.19-ko.6` branch.

**What would you like to be added**

Any localization contributions for Korean. 

**Comments**

- This issue is to notify the schedule of Korean localization to contributors.
- `dev-1.19-ko.6` is the current work branch for Korean localization.
- Korean PR Wrangler: @pjhwa 

**Important dates**
- A Korean localization work branch is merged to `master` branch after we complete around ~2 weeks job.
- PR Freeze: **12/04** (PR opened after freeze will be requested to rebased to next work branch)
- Branch Merge: **12/07** (merge to master branch)

## In Korean

**기능 추가 요청 이슈**

`dev-1.19-ko.6` 브랜치에 대한 한글화 작업

**추가 필요 사항**

한글화에 관련된 모든 기여

**코멘트**

- 컨트리뷰터에게 쿠버네티스 문서 한글화에 대한 작업 스케줄 및 마일스톤을 공유하기 위한 이슈
- 현재 한글화 작업 브랜치는 `dev-1.19-ko.6` 
- 한글화 PR 랭글러: @pjhwa 

**주요 일정**

- 한글화 작업 브랜치는 약 ~2 주간 작업 후, master 브랜치에 머지 됨.
- PR 프리즈: **12/04** (작업 브랜치에 포함되는 PR을 확정, 이후의 PR은 차기 작업 브랜치로 리베이스 필요)
- 브랜치 머지: **12/07** (master 브랜치에 머지되며, k8s.io에 자동 반영)

/language ko
/help

**Comment by seokho-son** [comment]
K8s 1.20 릴리스 일정을 고려하여 (타겟: 2020-12-08)
dev-1.19-ko.6 의 일정을 조정하고자 합니다.
기존: Freeze: 12/07, Merge: 12/10
변경: Freeze: 12/04, Merge: 12/07
1.20 릴리스 리드를 통해, 한글화 작업 브랜치의 일정은 릴리스 작업에는 크게 영향이 없을 것으로 응답 받았습니다. 따라서 Merge: 12/07 로 해도 특별히 문제가 없을 것 같습니다. 일정 참고하셔서 기여 부탁드립니다
