### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by shanarvs** [kubernetes/website#25295]
The below sentence is there towards the end of this page: (If you didn't already try creating a Node.js application and deploying it using a container, you can do that first by following the instructions from the Hello Minikube tutorial).

But the "Hello Minkube" tutorial link has nothing about creating any Node.js application or deploying it.

**Comment by sftim** [comment]
This is indeed a documentation bug. The v1.4 echoserver uses NGINX without node.js
Good spot, @shanarvs 

/kind bug
/language en
/triage accepted
/priority backlog
