### ISSUE TITLE
Operating etcd clusters for Kubernetes

### ISSUE THREAD

**Issue by ravirajrk** [kubernetes/website#25298]
![image](https://user-images.githubusercontent.com/27999871/100547806-c19d7a00-328e-11eb-9e37-737d59b523b7.png)

Url link:- https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

in the etcd member list to ge the the member ID cmd,the endpoint details "member1=http://10.0.0.1" are not mentioned.

it is mentioned as below in Docs
=========================
etcdctl --endpoints=http://10.0.0.2,http://10.0.0.3 member list

it shoud be
==========
etcdctl --endpoints=http://10.0.0.1,http://10.0.0.2,http://10.0.0.3 member list

Can you please do the needful

**Comment by sftim** [comment]
`etcdctl --endpoints=http://10.0.0.2,http://10.0.0.3 member list` looks right to me if http://10.0.0.1 has failed. I do wonder though if the sample output:
```
8211f1d0f64f3269, started, member1, http://10.0.0.1:2380, http://10.0.0.1:2379
91bc3c398fb3c146, started, member2, http://10.0.0.2:2380, http://10.0.0.2:2379
fd422379fda50e48, started, member3, http://10.0.0.3:2380, http://10.0.0.3:2379
```
is correct?
