### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/quality-service-pod/

### ISSUE THREAD

**Issue by mraghu4** [kubernetes/website#25306]
Add documentation for applying qosClass for a pod brough up using Job.

**Comment by sftim** [comment]
Hi @mraghu4 

I'd like to understand the context for the improvement you're suggesting - why do you recommend making that change to the page?

/priority awaiting-more-evidence
/language en

**Comment by mraghu4** [comment]
The page explain about applying qosClass to a pod. If the pods is created using Pod definition the page has enough content. But say If the pod is created using a Job definition the can qosClass be applyed..? if yes, how ? missing in the page.
