### ISSUE TITLE
Retitle “Configuring kubelet Garbage Collection” and add incoming links

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25300]
**This is a Bug Report**

**Problem:**
[Configuring kubelet Garbage Collection](https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/) is a page about performing a particular task, but it lives in the Concepts section. Tasks should be in the tasks section.

**Proposed Solution:**
- Change the title of the page https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/ to “Garbage collection for container images”
- Hyperlink from within https://kubernetes.io/docs/concepts/containers/ to the page https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
(remember, this PR will just cover the English localization)

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/

**Additional Information:**
/kind cleanup
/language en
/sig node
/help

Relevant to issue #4510

It is OK to clean up the content of the page beyond what this issue describes.
- Check whether it makes sense to remove the [Deprecation](https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#deprecation) section. This could be because we [avoid statements about the future](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-statements-about-the-future) or because the information is out of date.

**Comment by tengqm** [comment]
No. I don't agree to this movement. The reason is that garbage collection is an administrator job. However, https://kubernetes.io/docs/concepts/containers/ is mostly about concepts an end user need to know. If needed, we can add links to make sure users can learn what's happening behind the scene. Page movement like this is harmful rather than helpful.

**Comment by sftim** [comment]
@tengqm I've revised the issue description

/retitle Retitle “Configuring kubelet Garbage Collection” and add incoming links

**Comment by kbhawkey** [comment]
To confirm, the goal of this issue is to:
* retitle the GC concept page (not move the page or retitle the file)?
* link from the containers concept page to the GC concept page

**Comment by kbhawkey** [comment]
Note: I found 2 Garbage Collection concept pages:
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

The "cluster-administration" GC concept page focuses on the kubelet flags.
This page is not listed in the "cluster-administration" index page. Could the index page list the GC page under the "Managing a Cluster" section?
A side note, where is `imageManager` defined?
