### ISSUE TITLE
Improvement for k8s.io/docs/ - collapsible navigation

### ISSUE THREAD

**Issue by RSwarnkar** [kubernetes/website#25319]
Hi, Can we please have fully collapsible navigation for documentation page. Current documentation navigation sidebar does not has a way to view the nested sub-topics without navigating to them.
Advantage of such navigation would make it easier to navigate in collapsible tree fashion.

**Comment by sftim** [comment]
/area web-development
/kind feature
/priority awaiting-more-evidence

@RSwarnkar this website uses the [Docsy](https://www.docsy.dev/) theme; it might make sense to request this as a Docsy feature rather than specifically as a Kubernetes customization to Docsy.
