### ISSUE TITLE
Understanding Kubernetes Objects and apiVersion

### ISSUE THREAD

**Issue by glyn** [kubernetes/website#25317]
[Understanding Kubernetes Objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/) contains the following:
```
Required Fields

In the .yaml file for the Kubernetes object you want to create, you'll need to set values for the following fields:

    apiVersion - Which version of the Kubernetes API you're using to create this object
```
I find the use of the term "Kubernetes API" vague and confusing since `apiVersion` is really the API Group and Version of the "resource type" of the object. 

I'm not sure what the best description would be. However, I feel that the notion of GVK as a resource type doesn’t come out clearly enough in the introductory docs, so maybe that's part of a solution, especially that, according to its title, the above section is about _understanding_.

**Comment by sftim** [comment]
/language en
/triage accepted

There's room to improve the explanation here.
