### ISSUE TITLE
Unable to change the permission and ownership of files mounted using configMap as volume

### ISSUE THREAD

**Issue by dhandma** [kubernetes/website#25320]
Hi All,
Can someone please help me to find out the solution, how we can control the files  mounted using configMap as volume. 
I am still seeing files inside cotinaer running as roo:root with 644 permission .
files inside container:
``-rw-r--r--. 1 root root 1812 Dec  1 03:42 nginx.conf
-rw-r--r--. 1 root root 2062 Dec  1 03:42 default.conf ``

Deployment.yaml :
``` spec:
      securityContext:
        runAsUser: 222
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /usr/instances/webserver/conf/nginx.conf
          readOnly: false
          subPath: nginx.conf
          name: nginx-conf-configmap
        - mountPath: /usr/instances/webserver/conf/default.conf
          readOnly: false
          subPath: default.conf
          name: nginx-default-conf-configmap
      volumes:
      - name: nginx-conf-configmap
        configMap:
          name: nginx-conf-configmap
      - name: nginx-default-conf-configmap
        configMap:
          name: nginx-default-conf-configmap```

**Comment by sftim** [comment]
This looks like a support request; it's also an insight into documenting how to use a ConfigMap via a volume mount.
