### ISSUE TITLE
Kubernetes Components - please define/explain "user containers"

### ISSUE THREAD

**Issue by MaartenW** [kubernetes/website#25327]
There's one single mention of "user containers" under https://kubernetes.io/docs/concepts/overview/components/#control-plane-components

This concept is not explained as a component nor otherwise.

Would it be possible to explain the concept as it's confusing for newbies like me. (Especially since it's the 2nd page in explaining what Kubernetes is)

Is a "user container" a "node" or a "kubelet" or something else?

**Comment by sftim** [comment]
I'd replace the text:
> Control plane components can be run on any machine in the cluster. However, for simplicity, set up scripts typically start all control plane components on the same machine, and do not run user containers on this machine. See Building High-Availability Clusters for an example multi-master-VM setup.

with:
```markdown
People who manage large clusters typically isolate the control plane
onto dedicated computers; that isolation offers a defined level of
performance, improves reliability, and also helps with information security.

For small clusters, you can run the control plane components on the
nodes. If your workload containers and control plane components are
sharing the same resources, this can sometimes cause issues.

[Creating Highly Available clusters with kubeadm](/docs/setup/production-environment/tools/kubeadm/high-availability/)
explains one way to set up a replicated control plane that runs
separate from the nodes.
```

However, as this is now more text, maybe it makes sense to move that detail into the page at https://kubernetes.io/docs/concepts/architecture/ (which is currently just a list of topics). Thoughts welcome.
