### ISSUE TITLE
Mark persistent volume types as deprecated where appropriate

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#25323]
For photon, the cloud provider has been removed, so it will not function at all. The API was left because we cannot remove fields from the v1 API.

The cloud plugins are deprecated as part of the csi migration features. There have been release notes about them in previous releases but is missing from the documentation. For example:
https://github.com/kubernetes/kubernetes/pull/90896
https://github.com/kubernetes/kubernetes/pull/85637
https://github.com/kubernetes/kubernetes/pull/85231
https://github.com/kubernetes/kubernetes/pull/85237

Also, on this page, flocker has been marked as deprecated: https://kubernetes.io/docs/concepts/storage/volumes/#flocker

_Originally posted by @msau42 in https://github.com/kubernetes/website/pull/25200#discussion_r533098429_

**Comment by sftim** [comment]
/triage accepted
/sig storage
/kind cleanup
/priority backlog

Thanks @tengqm
