### ISSUE TITLE
kubectl get pods --show-labels shows information error

### ISSUE THREAD

**Issue by developewang** [kubernetes/website#25332]
Create Deployment --> 6
kubectl get pods --show-labels
NAME                                READY     STATUS    RESTARTS   AGE       LABELS
nginx-deployment-75675f5897-7ci7o   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
nginx-deployment-75675f5897-kzszj   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
nginx-deployment-75675f5897-qqcnn   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453

pod-template-hash should same as the name's random string.

**Comment by sftim** [comment]
Hi @developewang 

It looks like you're trying to request a change in behavior for `kubectl`. Have I got that right?
/triage needs-information

If there's a web page you're reporting a defect in, remember to mention the URL of the web page.

**Comment by developewang** [comment]
@sftim ok!
The url is: https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#failed-deployment
