### ISSUE TITLE
配置最佳实践

### ISSUE THREAD

**Issue by davideuler** [kubernetes/website#25336]
"Deployment 会创建一个 ReplicaSet 以确保所需数量的 Pod 始终可用，并指定替换 Pod 的策略 （例如 RollingUpdate)， 除了一些显式的restartPolicy: Never 场景之外，几乎总是优先考虑直接创建 Pod。 Job 也可能是合适的。"

这一段的翻译不准确。 原文 “ is almost always preferable "， 应该翻译为： Deployment 几乎总是更合适的用作直接创建 Pods 的方式，除非对于一些需要显示指定 restartPolicy: Never 的场景 （不需要重启容器）。这种情况下 Job 可能是更好的选择。

附原文：
A Deployment, which both creates a ReplicaSet to ensure that the desired number of Pods is always available, and specifies a strategy to replace Pods (such as RollingUpdate), is almost always preferable to creating Pods directly, except for some explicit restartPolicy: Never scenarios. A Job may also be appropriate.

**Comment by helight** [comment]
是的，翻译有点生硬，我来提个pr

**Comment by helight** [comment]
@davideuler  this is fixed now，you can close this issue later.
