### ISSUE TITLE
Using a Service to Expose Your App - misleading documentation

### ISSUE THREAD

**Issue by dinurp** [kubernetes/website#25341]
In this document (https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/) service type External name is explained as follows:

**ExternalName** - _Exposes the Service using an arbitrary name (specified by externalName in the spec) by returning a CNAME record with the name. No proxy is used. This type requires v1.7 or higher of kube-dns._

This is misleading. The correct explanation could be (from https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) as follows:

**ExternalName**: _Maps the Service to the contents of the externalName field (e.g. foo.bar.example.com), by returning a CNAME record with its value. No proxying of any kind is set up. This type requires v1.7 or higher of kube-dns, or coreDNS version 0.0.8 or higher._

**Comment by sftim** [comment]
Thanks @dinurp - that's worth fixing
/priority backlog
