### ISSUE TITLE
Bad hyperlink in “Metrics For Kubernetes System Components”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25353]
**This is a Bug Report**

**Problem:**
[Metrics For Kubernetes System Components](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/) includes a bad hyperlink to a feature gate. That hyperlink is trying to use [text fragments](https://wicg.github.io/scroll-to-text-fragment/); I  recommend _not_ using text fragments as they are a draft feature and not yet widely adopted across the web.

**Proposed Solution:**
Simplify the hyperlink so the link target is `/docs/reference/command-line-tools-reference/feature-gates/`

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/

**Additional Information:**
/language en
/kind bug
/good-first-issue

**Comment by EmilyM1** [comment]
PR: https://github.com/kubernetes/website/pull/25357

**Comment by sftim** [comment]
Fixed in PR #25357
/close
