### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-proxy/

### ISSUE THREAD

**Issue by zhwhao** [kubernetes/website#25351]
I don't know why "masqueradeAll" is usless in kube-proxy, and when clustercidr was removed from configmap kube-proxy, all of these new pods can not be started with error 
networkPlugin cni failed to set up pod "nginx-5f6ddfdbd-g9w4p_default" network: Get https://[10.100.0.1]:443/api/v1/namespaces/default: dial tcp 10.100.0.1:443: i/o timeout

the following is the configmap for kube-proxy.
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    clientConnection:
      acceptContentTypes: ""
      burst: 10
      contentType: application/vnd.kubernetes.protobuf
      kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
      qps: 5
    configSyncPeriod: 15m0s
    conntrack:
      maxPerCore: 32768
      min: 131072
      tcpCloseWaitTimeout: 1h0m0s
      tcpEstablishedTimeout: 24h0m0s
    enableProfiling: true
    healthzBindAddress: 0.0.0.0:10256
    hostnameOverride: kaas-m-7ec67
    iptables:
      masqueradeAll: false
      masqueradeBit: 14
      minSyncPeriod: 0s
      syncPeriod: 30s
    ipvs:
      excludeCIDRs: []
      minSyncPeriod: 0s
      scheduler: rr
      strictARP: true
      syncPeriod: 30s
    kind: KubeProxyConfiguration
    metricsBindAddress: 127.0.0.1:10249
    mode: iptables
    nodePortAddresses: []
    oomScoreAdj: -999
    portRange: ""
    udpIdleTimeout: 250ms
    winkernel:
      enableDSR: false
      networkName: ""
      sourceVip: ""
  kubeconfig.conf: |-
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        server: https://127.0.0.1:6443
      name: default
    contexts:
    - context:
        cluster: default
        namespace: default
        user: default
      name: default
    current-context: default
    users:
    - name: default
      user:
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-30T06:31:08Z"
  labels:
    app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "522688"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-proxy
  uid: 959f20a4-7d19-48ad-a52a-f9426bf92110

K8S version:1.19

**Comment by sftim** [comment]
Hi @zhwhao 

I'm not sure if you're reporting a defect with https://k8s.io/docs/reference/command-line-tools-reference/kube-proxy/ or with the `kube-proxy` tool itself.

Can you confirm which is a closer match for the issue you wanted to report?

/triage needs-information

**Comment by zhwhao** [comment]
@sftim ,Thanks for your reply, my problem is for kube-proxy tool itself.
1."masqueradeAll:false" is usless in kube-proxy configmap, all of the external traffic has been SNAT by kube-proxy with this option set to false (in iptable section).
2. Can I remove "clustercidr" option from kube-proxy configmap? I'm not sure this is right, what  I want is all of the traffic can not be SNAT, and pods can get source ip from connections.
