### ISSUE TITLE
Improvement for k8s.io/docs/concepts/containers/

### ISSUE THREAD

**Issue by ChrisG0x20** [kubernetes/website#25354]
"The container runtime is the software that is responsible for running containers." says almost nothing. What does the container runtime actually run? Why is there a runtime?

**Comment by sftim** [comment]
/kind feature
/language en
/triage accepted

Let's explain what a container runtime is!

**Comment by sftim** [comment]
@inductor, are you able to provide a CLA-released version of the explanation from https://dev.to/inductor/wait-docker-is-deprecated-in-kubernetes-now-what-do-i-do-e4m?

It's very clear and would make a good basis for this improvement, but we do need the CLA dealt with.

**Comment by sftim** [comment]
Specifically, the section about OCI and CRI is really the kernel of what I would wish to borrow.
