### ISSUE TITLE
Pod 水平自动扩缩

### ISSUE THREAD

**Issue by standup-jb** [kubernetes/website#25362]
创建 HorizontalPodAutoscaler 对象时，需要确保所给的名称是一个合法的 DNS 子域名。 有关 API 对象的更多信息，请查阅 HorizontalPodAutoscaler 对象设计文档。 这里面的跳转文档链接404 。应该修复为 https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#horizontalpodautoscaler-v1-autoscaling

**Comment by sftim** [comment]
/language en
right?

**Comment by tengqm** [comment]
/close
Seems fixed.
