### ISSUE TITLE
Create guide to help cluster operators migrate away from Docker

### ISSUE THREAD

**Issue by makkes** [kubernetes/website#25371]
**This is a Feature Request**

**What would you like to be added**

This is a follow-up to https://github.com/kubernetes/community/issues/5344 (and more specifically https://github.com/kubernetes/community/issues/5344#issuecomment-737754144). There needs to be a guide helping cluster operators move away from Docker to containerd or CRI-O now that Docker is being deprecated with Kubernetes 1.20 and will be removed late next year.

**Why is this needed**
Exchanging the container runtime of a running Kubernetes cluster is not documented anywhere at the moment (supposedly because no one had the immediate need to do so). But now that Docker is being deprecated while it has been supported in earlier Kubernetes versions, the community should help Kubernetes users (i.e. cluster operators) move away from the once supported Docker.

The deprecation announcement has caused a lot of anxiety and fear around the impacts. Such a guide would help mitigate some of the fears.

**Comments**

**Comment by sftim** [comment]
/language en
/kind feature
/triage accepted
/priority important-soon

Thanks @makkes

**Comment by sftim** [comment]
We now have https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/
/close
