### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/

### ISSUE THREAD

**Issue by Pickacho** [kubernetes/website#25375]
Please add a Ansible guide to deploy Kubernetes on ubuntu 20.04 by play-book

**Comment by sftim** [comment]
This is quite a specific request @Pickacho 

Can you outline why this improvement would be worthwhile?

/kind feature
/language en
/priority awaiting-more-evidence

**Comment by Pickacho** [comment]
Hi
I will be happy to help.
I believe in writing a guide of this kind, or its equivalent under operating systems like Red Hat / Centos
Can greatly promote beginners in the process of familiarization and installation of Kubernetes

While giving beginners an understanding of the tools they will most likely use during their job - such as Ansible
