### ISSUE TITLE
Broken link in article https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/

### ISSUE THREAD

**Issue by vivekjhauipath** [kubernetes/website#25399]
Links are broken on this page:
https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/

**Comment by sftim** [comment]
/retitle Broken link in article https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/
/language en
/area blog

**Comment by bl-ue** [comment]
@vivekjhauipath will you please test the fix @ https://deploy-preview-25428--kubernetes-io-master-staging.netlify.app/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/?
