### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by pananix** [kubernetes/website#25409]
Would be nice if the page put something in the CRI-O section on if/how CRI-O could be installed on RHEL8 without having to purchase OpenShift.

Thanx,

David Bandel
david.bandel@rice.edu

**Comment by sftim** [comment]
/kind feature
/triage accepted
/language en
/priority backlog

Documenting container runtime deployment is valid; you need a container runtime to use Kubernetes.
