### ISSUE TITLE
Issue with k8s.io/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by islbie** [kubernetes/website#25416]
쿠버네티스는 서로 연결되어서 단일 유닛처럼 동작하는 고가용성의 컴퓨터 클러스터를 상호조정한다. 
ㅋㅋㅋㅋㅋ
알아 듣게 써놓고 읽으라고 해야지. 차라리 영어로 쓰던지. 기계가 번역한 건가. 그럼 기계는 아직 멀었군 ㅋㅋㅋㅋㅋ

**Comment by gochist** [comment]
@islbie Please read [the community code of conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/ko.md).
