### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource js/jquery-3.3.1.min.js with computed SHA-256 integrity

### ISSUE THREAD

**Issue by Anilople** [kubernetes/website#25414]
## Description

Run `hugo_extended_0.79.0_Windows-64bit` server on windows 10 platform(every dependencies have been resolved include git submodule)

```bash
hugo.exe server --buildFuture
```

and access the web through my chrome browser.

Found that language switch button not work.

![image](https://user-images.githubusercontent.com/15523186/101274673-0cf9e000-37db-11eb-9480-2c8ce424213f.png)

When I use `F12`, and refresh the page, there is a error message on the console

```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:1313/js/jquery-3.3.1.min.js' with computed SHA-256 integrity 'T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4='. The resource has been blocked.
```

## Expected behavior

Language switch button can work well, and there is no error `Failed to find a valid digest...` on the console.

## The reson of the problem

Line endings is different between windows and *nix system.

* All versions of Microsoft Windows represent line endings as CR followed by LF
* UNIX and UNIX-like operating systems (including Mac OS X) represent line endings as LF alone
> reference from [Converting from Windows-style to UNIX-style line endings](https://support.nesi.org.nz/hc/en-gb/articles/218032857-Converting-from-Windows-style-to-UNIX-style-line-endings)

The file `jquery-3.3.1.min.js` in the path `website/static/js` base on project.

Use followed command to get the hash digest.

```
shasum -b -a 256 jquery-3.3.1.min.js | awk '{ print $1 }' | xxd -r -p | base64
```
> reference from MDN web docs [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)

The result is different.
 
* `T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4=` on windows-style line endings, which calculates by hugo on runtime, but not matches.
* `FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=` on unix-style line endings, which matchs.

The related issue about hugo is xianmin/hugo-theme-jane/issues/269

## Some suggestion to solve it

1. Delete integrity in script label? Will cause some security problem.
2. Force the line endings of js file to unix-style? Like https://docs.github.com/en/free-pro-team@latest/github/using-git/configuring-git-to-handle-line-endings
3. Add multiple integrity value? i.e and windows-style line endings digest `T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4=` to the label `script` which use `jquery-3.3.1.min.js`.

The code 
```javascript
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
```
will change to 
```javascript
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8= sha256-T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4=" crossorigin="anonymous"></script>
```

**Comment by sftim** [comment]
> Force the line endings of js file to unix-style

That sounds like a good fix. Others could work as well.

Related: we can also mark that minified JavaScript [as generated](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-how-changed-files-appear-on-github).

/triage accepted
/area web-development

**Comment by muthumanikandan390** [comment]
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8= sha256-T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4=" crossorigin="anonymous"></script> this one fixed my issue
