### ISSUE TITLE
Resource metrics pipeline page language zh

### ISSUE THREAD

**Issue by hello2dj** [kubernetes/website#25442]
metrics server url is wrong.
"https://github.com/kubernetes-sings/metrics-server" => "https://github.com/kubernetes-sins/metrics-server".  
"kubernetes-sings" => "kubernetes-sigs"

**Comment by tengqm** [comment]
Please mention the page to fix.

**Comment by bl-ue** [comment]
@tengqm
It's https://kubernetes.io/zh/docs/tasks/debug-application-cluster/resource-metrics-pipeline/, search for `Metrics 服务器`.
The file is `content/zh/docs/tasks/debug-application-cluster/resource-metrics-pipeline.md:118`

**Comment by tengqm** [comment]
@bl-ue Thanks. Would you mind propose a fix?
/triage accepted
/kind bug
/language zh

**Comment by hello2dj** [comment]
yes

**Comment by bl-ue** [comment]
@hello2dj are you planning on opening a PR?  If not I will.

**Comment by hello2dj** [comment]
@bl-ue I'm not planing on it, thank your PR
/shoutout

**Comment by bl-ue** [comment]
@hello2dj Okay, then I will.  @tengqm

**Comment by tengqm** [comment]
closed by #29452

Link lost because the issue was mentioned in original commit rather than the PR.

/close
