### ISSUE TITLE
Add caution note to SSH-Auth Secrets for "man in the middle" susceptibility

### ISSUE THREAD

**Issue by adambkaplan** [kubernetes/website#25497]
**This is a Feature Request**

**What would you like to be added**

Add a caution note to the Concepts document article for `kubernetes.io/ssh-auth` Secrets, warning that SSH private keys do not establish fully trusted communication between clients and host servers.

**Why is this needed**

SSH key pairs provide a means of establishing authenticated communication between two parties, but not _trusted_ communication between two parties. Trust can only be established via a secondary means, like a `known_hosts` file.

Without establishing trust, applications which utilize SSH keys by themselves for authentication are susceptible to "man in the middle" attacks.

**Comments**

This item was discussed during the first SIG Docs Security subproject meeting.

**Comment by sftim** [comment]
/priority important-longterm

Thanks
