### ISSUE TITLE
Kubernetes Doc [Portuguese] - lateral menu (right)

### ISSUE THREAD

**Issue by luismaximozup** [kubernetes/website#25493]
**Problem:**
![image](https://user-images.githubusercontent.com/60019625/101498050-692f4200-394a-11eb-9985-883b03fadf77.png)

**locale:** portugues - lateral menu (right)
https://kubernetes.io/pt/docs/home/

**Seggestion:** 
* Editar essa pagina
* Criar uma pagina filho
* Reportar um bug

#close 25493

**Comment by sftim** [comment]
/language pt

Might be best fixed upstream in https://www.docsy.dev/

**Comment by femrtnz** [comment]
Hey @sftim I just opened a PR on `docsy` to fix this issue -> https://github.com/google/docsy/pull/401

So, I believe we should close this one as it is not related to this repo, right?

Thanks

**Comment by femrtnz** [comment]
Hey @sftim this was merged already. Not sure how the update works on K8s side though.
