### ISSUE TITLE
Introduce simple Pod manifest before Pod template concept

### ISSUE THREAD

**Issue by serewicz** [kubernetes/website#25495]
As a quick review of the page leads to confusion about the applicability of the YAML example I suggest the progression of concepts and examples is not optimal. My suggestion is:

Move the "Static Pods" section before the "Working with Pods" section.
Include a basic eight line YAML file for a pod.
By presenting the basic pod info first, the job spec would make more sense. As well when searching for pod yaml example, it brings up this page, which I realize is an issue with a sub-optimal search, but others may be finding the same information and becoming confused.

**Comment by sftim** [comment]
Hi @serewicz 

Which page?
/triage needs-information

**Comment by serewicz** [comment]
Oh, sorry. Thought that info carried over from the page I was on when I saw the error.  The page which has a job  instead of a pod is https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates

**Comment by reylejano** [comment]
@serewicz It looks like the Job manifest was the intention for that page. From the page:

> PodTemplates are specifications for creating Pods, and are included in workload resources such as Deployments, Jobs, and DaemonSets.
> 
> Each controller for a workload resource uses the PodTemplate inside the workload object to make actual Pods. The PodTemplate is part of the desired state of whatever workload resource you used to run your app.
> 
> The sample below is a manifest for a simple Job with a template that starts one container. The container in that Pod prints a message then pauses.

The page is pointing out that the Pod template (not Pod manifest) starts at .spec.template and that Pod templates are parts of other manifests for Deployments, jobs, DaemonSets, et al.

Since that is the concept page for Pods, maybe it will be better if an additional example of a simple Pod manifest is added.

**Comment by serewicz** [comment]
@reylejano I agree. I now get why there would be a job spec on the page, but following the progression of concepts there are two changes I would like to suggest:
1) Move the "Static Pods" section before the "Working with Pods" section.
2) Include a basic eight line YAML file for a pod.

By presenting the basic pod info first, the job spec would make more sense.   As well when searching for pod yaml example, it brings up this page, which I realize is an issue with a sub-optimal search, but others may be finding the same information and becoming confused.

**Comment by sftim** [comment]
/retitle Introduce simple Pod manifest before Pod template concept
/kind feature
/triage accepted

That's a good suggestion @serewicz . Would you be willing to revise the issue description to reframe around that improvement?

**Comment by serewicz** [comment]
Sure @sftim, what is the proper way to revise the issue description?

**Comment by sftim** [comment]
> what is the proper way to revise the issue description?

There's a &hellip; top right of the issue text. Click that and choose *Edit*.
