### ISSUE TITLE
Tidy list of generators for “kubectl create”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25501]
**This is a Feature Request**

**What would you like to be added**
Convert the monospaced [list](https://kubernetes.io/docs/reference/kubectl/conventions/#generators) of `kubectl create` generators into Markdown that renders as nice HTML.

**Why is this needed**
https://kubernetes.io/docs/reference/kubectl/conventions/#generators lists generators, as monospaced text.
This would render better as an unordered list.

**Comments**
/language en
/kind cleanup
/good-first-issue

**Comment by tomkivlin** [comment]
@sftim is there some automation to close an issue that has been resolved by PR, or do I just ask here? :)

**Comment by irvifa** [comment]
@tomkivlin you can use this https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue when creating a PR

**Comment by tomkivlin** [comment]
@irvifa sure, thanks.  I wasn't sure if this was discouraged in the [PR guidelines](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#do-not-use-github-keywords-or-mentions-within-your-commit-message) but will add to the PR level next time.

**Comment by tengqm** [comment]
Resolved.
/close
