### ISSUE TITLE
Storage Classes content error

### ISSUE THREAD

**Issue by lostsquirrel** [kubernetes/website#25528]
at line 634  storageaccounttype's discription seems not correct

>
* `storageaccounttype`: Azure storage account Sku tier. Default is empty.

**Comment by sftim** [comment]
Hi @lostsquirrel 

Can you point to the Markdown file or web page that doesn't seem right?
/language en
/triage needs-information

**Comment by lostsquirrel** [comment]
> Hi @lostsquirrel
> 
> Can you point to the Markdown file or web page that doesn't seem right?
> /language en
> /triage needs-information

at https://github.com/kubernetes/website/edit/master/content/en/docs/concepts/storage/storage-classes.md
line 634, the description content seems just copy from the preview section, and not match the storageaccounttype

**Comment by sftim** [comment]
I'm going to reopen this in case it does need fixing. Ok to close if it doesn't.
/reopen

@kubernetes/sig-storage-misc - does “`storageaccounttype`: Azure storage account Sku tier. Default is empty.” look right?
