### ISSUE TITLE
Debugging Kubernetes nodes with crictl - Starting pods/containers doesn't work with containerd runtime

### ISSUE THREAD

**Issue by joshiste** [kubernetes/website#25537]
When I use the containerd runtime (k8s v1.1.9.4) and following the steps to run a container, the created podsandbox will get stopped and removed by the kubelet and I'm not able to start a container.
Is that excpected to happen?

**Comment by joshiste** [comment]
also doesn't work for me using the docker-shim

**Comment by sftim** [comment]
_aside_ this issue is about the page at https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/
