### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by gayatri-maker** [kubernetes/website#25543]
Interactive tutorial is not responding after waiting so long.  I am even not able to access katacoda site. they blocked my IP. why they have blocked my IP?

**Comment by sftim** [comment]
/kind support
I think

@gayatri-maker maybe you are using the same public IPv4 address as a suspected miscreant? This can happen if you and a misbehaving user are behind the same NAT service.

**Comment by gayatri-maker** [comment]
> /kind support
> I think
> 
> @gayatri-maker maybe you are using the same public IPv4 address as a suspected miscreant? This can happen if you and a misbehaving user are behind the same NAT service.

@sftim Thank you for the response. how can I solve this issue? do they will remove my Ip from block list? I have no idea how to solve this. where should I request to access site again?
