### ISSUE TITLE
Kubernetes v1.19 - Doc Reference Page has mismatch links

### ISSUE THREAD

**Issue by raghvenders** [kubernetes/website#25548]
Problem :
In the v1.19 version of the Kubernetes site - https://v1-19.docs.kubernetes.io/docs/reference/, we are seeing the link for Kubernetes API - https://v1-19.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/

Steps to Reproduce  : 
1. Navigate to the URL: https://kubernetes.io/ and in the versions choose v1.19
2.It will be redirected to https://v1-19.docs.kubernetes.io/
3.Documentation -> reference, under API Reference section we are able to spot a wrong link for v1.20 _Kubernetes API Reference v1.20_

Solution : 
https://v1-19.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/ is the correct Kubernetes API Reference for v1.19 and the link has to be re-titled as **Kubernetes API Reference v1.19**

Note: As the further older doc versions  are not maintained, not sure if it has to be fixed in those as well.

**Comment by sftim** [comment]
/priority important-soon
@annajung FYI

**Comment by sftim** [comment]
This looks like a metadata bug, but I'm not exactly sure where the fix is (as I haven't yet investigated)

**Comment by sftim** [comment]
The behavior seen here (linking to the current API reference) has come from https://github.com/kubernetes/website/pull/18837

**Comment by kbhawkey** [comment]
👀

**Comment by kbhawkey** [comment]
The config.toml in the `release-1.19` branch should set latest to `1.19`.
The shortcode uses, ```{{ site.Params.latest }}``` and this variable is set to `1.20`.

**Comment by kbhawkey** [comment]
I can fix this.

**Comment by kbhawkey** [comment]
Are the 1.18, 1.17, 1.16 branches incorrect?

**Comment by kbhawkey** [comment]
Hi @raghvenders .
What do you think about closing this issue?

**Comment by tengqm** [comment]
Feel free to reopen if the issue is still there.
/close

**Comment by raghvenders** [comment]
@kbhawkey - Thanks for fixing the issue.
