### ISSUE TITLE
Configure a Pod to Use a ConfigMap :: updating configmap for volume is not updating kubectl logs

### ISSUE THREAD

**Issue by vishaal314** [kubernetes/website#25562]
-  My Question  : updating configmap for volume is not updating kubectl logs when doing tail  it updates internally when i check with kubectl exec -it  demo -n /bin/bash  
" i know  image will override commands "

Any suggestions/fix  will be helpful .

config.yaml   -   

apiVersion: v1
data:
  database-uri: http://someeeeeeecom.com
kind: ConfigMap
metadata:
  creationTimestamp: "2020-12-08T18:15:39Z"
  name: demo
  namespace: default

my deployment.yaml : 

apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - image: 175438534346.dkr.ecr.us-east-1.xxxxxxxxxxxxx/nginx-https:1.0
    name: cc
    imagePullPolicy: Always
    command: ["bin/sh" ]
    args: ["-c", "cat /mnt/database-uri;while true; do echo hello; sleep 10000;done"]
    volumeMounts:
    - name: configmap
      mountPath: /mnt
      readOnly: false
    ports:
    - containerPort: 8080
  volumes:
  - name: configmap
    configMap:
      name: demo
  restartPolicy: OnFailure

expected result : kubectl  logs demo should provide updated configmaps as those are updated inside kubeclet .

**Comment by sftim** [comment]
Hi @vishaal314 

I think you're reporting that the page at https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/ is not accurate. Is that right?

Can you explain what seems wrong?  I skimmed through [Configure a Pod to Use a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) and didn't see a mention of `kubectl logs`.
