### ISSUE TITLE
Kubernetes v1.20 documentation does not mention AuditSink.

### ISSUE THREAD

**Issue by d0x1g0x1** [kubernetes/website#25571]
Information about `AuditSink` is missing in [documentation](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) (Auditing -> Audit backends).

**Comment by sftim** [comment]
Hmm, there's also no AuditSink in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/

**Comment by sftim** [comment]
`AuditSink` is deprecated @d0x1g0x1 

Maybe https://v1-18.docs.kubernetes.io/docs/tasks/debug-application-cluster/audit/ is relevant?
/kind support

/retitle Kubernetes v1.20 documentation does not mention AuditSink.

**Comment by d0x1g0x1** [comment]
@sftim I don't see public information about deprecation of `AuditSink` feature and differences between 1.18 and 1.20 codebase.

**Comment by sftim** [comment]
https://v1-19.docs.kubernetes.io/docs/setup/release/notes/ mentions the deprecation of dynamic auditing and the auditregistration.k8s.io/v1alpha1 API group. As this was an alpha feature the deprecation was not listed as a major change.
