### ISSUE TITLE
Secret

### ISSUE THREAD

**Issue by fandongxiaokk** [kubernetes/website#25587]
calico-kube-controllers pod   v3.17.1  版本 ERROR:

2020-12-13 08:21:12.385 [FATAL][1] main.go 101: Failed to start error=failed to build Calico client: could not initialize etcdv3 client: open /calico-secrets/etcd-cert: permission denied

calico-etcd.yaml  配置文件 calico-kube-controllers 组件  v3.17.1  版本 ，最低权限是0040 而不是 400
1.镜像：calico/kube-controllers v3.17.1
vim calico-etcd.yaml  ( v3.17.1  版本)
volumes:
        # Mount in the etcd TLS secrets with mode 400.  **calico-kube-controllers 组件  最低权限是0040 而不是 400**
        # See https://kubernetes.io/docs/concepts/configuration/secret/
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets
            defaultMode: 0040

**Comment by zaf187** [comment]
Please can i upvote this issue, i am facing the same problem. After changing the defaultMode to 0040 it works fine.

**Comment by sftim** [comment]
Hi @zaf187 & @fandongxiaokk 

What summary / title would you recommend for this issue?

BTW https://youtu.be/o45vmed3Pcc?t=20 outlines how to upvote

**Comment by zaf187** [comment]
permissions related issue around accessing etcd-secrets from the calico controller node, i think that's a reasonable summary / title.

This should actually be in the calico github ... i was just googling for this issue and came across this post here in this github.

**Comment by sftim** [comment]
Ah OK - it's not a documentation issue?

**Comment by zaf187** [comment]
> Ah OK - it's not a documentation issue?

no it isn't. IMO you can close this but i actually don't understand the post from the OP.

**Comment by sftim** [comment]
This seems to be off topic
/close

**Comment by JESWINKNINAN** [comment]
@fandongxiaokk  This topic is probably in the Calico Github, but just for your info setting the permission with defaultmode : 440  in the volume  mount will fix the issue.
