### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by hillbilly-mark** [kubernetes/website#25601]
Sorry.  But, this seems to just fail. miserably.  I tried installing to Ubuntu Server 20.04.

<pre>
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   coredns-74ff55c5b-95csw                   0/1     ContainerCreating   0          20h
kube-system   coredns-74ff55c5b-hmhdx                   0/1     ContainerCreating   0          20h
kube-system   etcd-ubuntu-docker-2                      1/1     Running             0          20h
kube-system   kube-apiserver-ubuntu-docker-2            1/1     Running             0          20h
kube-system   kube-controller-manager-ubuntu-docker-2   1/1     Running             0          20h
kube-system   kube-flannel-ds-nmrzm                     0/1     CrashLoopBackOff    231        19h
kube-system   kube-proxy-dvb4z                          1/1     Running             0          20h
kube-system   kube-scheduler-ubuntu-docker-2            1/1     Running             0          20h
</pre>

I am unsure how long to wait is expected, really.  But, I have given up.  What can I do at this point?  Can I reverse this k8s failed installation or do I have to scrap the whole OS and start over?

**Comment by neolit123** [comment]
try a different container network plugin like Calico or Weave.
Flannel is not well maintained.

for more questions try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support

**Comment by hillbilly-mark** [comment]
I assume the betwwen the lines answer is i have to reformat scratch and start over from the very beginning? ---- On Mon, 14 Dec 2020 08:23:43 -0900  notifications@github.com  wrote ----
try a different container network plugin like Calico or Weave.
Flannel is not well maintained.
for more questions try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
/close
/kind support
