### ISSUE TITLE
[es] https://k8s.io/es/docs/concepts/services-networking/ is blank

### ISSUE THREAD

**Issue by MasterDev117** [kubernetes/website#25616]
Don't have info in Spanish

**Comment by sftim** [comment]
/retitle https://k8s.io/es/docs/concepts/services-networking/ is blank
/language es
/kind bug

(although this is _mainly_ a feature request, serving blank rather than localized content is a bug)
/triage accepted

**Comment by sftim** [comment]
The page at https://k8s.io/es/docs/concepts/services-networking/ is a placeholder that exists to make the site front page render correctly.
@kubernetes/sig-docs-es-owners any thoughts on how to address this?

**Comment by raelga** [comment]
Let me check it, because other pages are having like https://kubernetes.io/es/docs/concepts/storage/ the same issue.

**Comment by sftim** [comment]
https://kubernetes.io/es/docs/concepts/services-networking/ is not blank now

/close
