### ISSUE TITLE
add diagram that explains the user facing RBAC objects and their relations 

### ISSUE THREAD

**Issue by brennerm** [kubernetes/website#25620]
**What would you like to be added**
I'd like to see a diagram that informs the reader about the objects (Role, RoleBinding, ServiceAccount, ...) and their relations that are part of the Kubernetes RBAC system.

**Why is this needed**
IMO this would help users to understand how to handle RBAC objects themselves more easily.

**Comments**
Talked to @sftim in sig-docs Slack channel beforehand as I offered to contribute such diagram and he recommended me to start with creating an issue.

**My proposal**
![image](https://user-images.githubusercontent.com/5527832/102128047-9483c680-3e4d-11eb-9d00-3145df774df1.png)
Please wait with any detailed discussion about the diagram until the PR is created. Just added it to make clear what I'm looking for.

**Comment by CKchen0726** [comment]
RoleBinding and ClusterRoleBinding:
![image](https://user-images.githubusercontent.com/47560998/104316325-45e24e80-5517-11eb-976d-52b80a599a69.png)

**Comment by sftim** [comment]
A PR to add this diagram would still be useful.

Extra credit: use icons from https://github.com/kubernetes/community/tree/master/icons and a key, similar to the key in https://kubernetes.io/docs/concepts/overview/components/ (right hand side).
