### ISSUE TITLE
Generate feature gates list from data

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25645]
**This is a Feature Request**

**What would you like to be added**
Track a list of feature gates as, eg, YAML, and generate https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ from that data.

**Why is this needed**
- This improvement lets people update the feature state for a gate with a one line change, eg
   ```diff
   --- allow-ext-traffic-local-endpoints.md	2020-01-21 15:24:34.907668274 +0000
   +++ allow-ext-traffic-local-endpoints.md	2020-03-15 10:39:43.852042785 +0000

   @@ -16,6 +16,8 @@
  featureDetaills:
      name: AllowExtTrafficLocalEndpoints
      phases:
         - state: alpha
           enabled: false
           firstVersion: v1.4
   +       lastVersion: v1.26
   +     - state: beta
   +       enabled: false
   +       firstVersion: v1.27
   whatever: foo
   ---

   Text here
   ```
- This change enables future work to:
   - autogenerate the input data
   - improve the `feature-state` shortcode
- Combining this with other data could let the Kubernetes project have a single view of new features and deprecations for a release, generating that view automatically.

**Comments**
/kind feature

**Comment by sftim** [comment]
To clarify something: we need to localize the descriptions for each feature gate, so those descriptions would still be part of the content. The good thing about having this list as data is that we can lint to make sure that each added feature gate has a matching description.

**Comment by wilsonehusin** [comment]
I love this idea! On compiling major themes for 1.20, I had to go back and forth between k/k PR and k/website PR to see if the changes are in sync. Is this a step towards generating [from the actual code itself](https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go)?

**Comment by PI-Victor** [comment]
we missed more than a few of these in the past, i'd like to make this happen. 

/assign

i hope to be able to submit a PR soonish.

**Comment by sftim** [comment]
I've updated the PR I opened about this. I've left it as draft so that we can discuss the approach to take.

**Comment by sftim** [comment]
I also wrote up a [rationale](https://github.com/kubernetes/website/pull/28036#issuecomment-862284989).

**Comment by sftim** [comment]
> Is this a step towards generating from the actual code itself?

(yes, it is)

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/28036#issuecomment-883482828 mentions running this past SIG Architecture to check that folks are happy with the approach.

* _This_ issue is about switching the page to be driven by local data (in `/data` within the repo)
* a future change could build on that to switch to using remote data. Hugo can fetch and deserialize JSON data, via https, then render it.

**Comment by sftim** [comment]
Also see: https://github.com/kubernetes/website/issues/39963#issuecomment-1488103843

**Comment by sftim** [comment]
BTW I'd probably use a one-file-per-feature-gate approach now. That makes it much easier to avoid merge conflicts when different people have updates to make for an upcoming release.

**Comment by sftim** [comment]
@pacoxu would you have time to look at the revised approach in #41793?

**Comment by sftim** [comment]
In #41793, @tengqm wrote:

> &hellip;splitting the data into 290+ files, with each gate represented in a dedicated file, doesn't look the right thing to do for me.

and

> Please imagine future changes to the feature gates, we will need to find out which file to modify, and as you may be aware of, some features change their names! Damn it.

**Comment by sftim** [comment]
I'd imagined not supporting feature gate renames in any implementation, at least initially. We can still write text to explain how feature gates are related.

**Comment by sftim** [comment]
Done in https://github.com/kubernetes/website/pull/44478

/close
