### ISSUE TITLE
Link to #contributing-to-the-docs at top of repo README

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25646]
**This is a Feature Request**

**What would you like to be added**
In the first paragraph of running text for https://github.com/kubernetes/website/blob/master/README.md, add a hyperlink to [`#contributing-to-the-docs`](https://github.com/kubernetes/website#contributing-to-the-docs).

**Why is this needed**
People reading the README have to scroll down some way to see that there is a guide to contributing. Let's make that really easy to spot.

**Comments**
Also consider a similar hyperlink to [`#localization-readmemds`](https://github.com/kubernetes/website/blob/master/README.md#localization-readmemds)

/help
/language en
/kind feature

**Comment by philiplee13** [comment]
Hi @sftim I'm interested in taking this issue, is there anything that I need to do before hand to take this ticket?

**Comment by tengqm** [comment]
@philiplee13 Just go ahead and raise a PR, :)

**Comment by jailton** [comment]
PR #25777 has fixed the issue. Can it be closed?

**Comment by sftim** [comment]
/close

Thanks @philiplee13
