### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/components/

### ISSUE THREAD

**Issue by runningman84** [kubernetes/website#25658]
the deployment controller should be mentioned in addition to the replicaset controller

**Comment by sftim** [comment]
Hi @runningman84 

That list of controllers is not exhaustive (although in PR #16885 I did try to add a full list of built-in controllers).
I think it makes sense not to mention the ReplicationController controller there, for two reasons:
1. the resource is not well named
2. ReplicationController is deprecated

I _suggest_ removing the reference to the replication controller and instead mentioning the job controller. It's just an example, and Job is a very simple control loop.

To be clear: I don't really mind what the replacement controller is; it could be the deployment controller, the job controller, or any other built-in controller.

/language en
/good-first-issue
/kind cleanup
/triage accepted

**Comment by jai** [comment]
does this refer to the section in the screenshot? If so, Replica Controller is gone:

![CleanShot 2021-05-07 at 19 13 18@2x](https://user-images.githubusercontent.com/1943284/117447961-5441f380-af68-11eb-9aab-e14dd409ebba.png)

@sftim can you confirm if I'm looking at the correct section? If so, I think this issue can be closed?

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/25918
/close
