### ISSUE TITLE
Kubernetes 组件

### ISSUE THREAD

**Issue by decaMinCow** [kubernetes/website#25656]
kube-controller-manager
在主节点上运行 控制器 的组件。

从逻辑上讲，每个控制器都是一个单独的进程， 但是为了降低复杂性，它们都被编译到同一个可执行文件，并在一个进程中运行。

这些控制器包括:

节点控制器（Node Controller）: 负责在节点出现故障时进行通知和响应。
副本控制器（Replication Controller）: 负责为系统中的每个副本控制器对象维护正确数量的 Pod。
端点控制器（Endpoints Controller）: 填充端点(Endpoints)对象(即加入 Service 与 Pod)。
服务帐户和令牌控制器（Service Account & Token Controllers）: 为新的命名空间创建默认帐户和 API 访问令牌.

------------------------------------------------------------------------------------------------------------------------

这些列表后面应该都没有句号

**Comment by sftim** [comment]
This seems to be feedback about https://kubernetes.io/zh/docs/concepts/overview/components/

@decaMinCow would you be willing to revise the issue description with more detail of the shortcoming you have seen, or the improvement you'd like to suggest?
(I'd be grateful if someone could translate or rephrase this comment in Chinese).

**Comment by ydcool** [comment]
/language zh 
/triage accepted
/assign

@sftim  decalMinCow means there should no full stop `。` at the end of a list line.

**Comment by ydcool** [comment]
solved by #26696 

/close
