### ISSUE TITLE
Move details about API access from pods out of cluster administration section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25659]
**This is a Feature Request**

**What would you like to be added**
The detail about Pods and how they can verify the API server's identity should move to a reference or concept page about accessing the Kubernetes API.

**Why is this needed**
https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#directly-accessing-the-rest-api-1 includes handy tips about how to access the Kubernetes API, including that the default service account volume includes a CA bundle. However, this is as relevant for app developers as it is for cluster administrators.

**Comments**
/kind cleanup
/language en

**Comment by uhari03** [comment]
I would like to take this on, but I would suggest moving the entire page to another section.
In other words, moving this entire page: https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/
To something under Reference.

@sftim thoughts?

**Comment by sftim** [comment]
I would like to see _a_ page in the tasks section about accessing the Kubernetes API from client code. For me it's just https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#directly-accessing-the-rest-api-1 that ought to move.

**Comment by kbhawkey** [comment]
👋 Does this new task page belong in an existing task section? Or add as a standalone page?
You also mentioned possibly adding this new content to the `concepts` or `reference` sections.

**Comment by sftim** [comment]
I don't think “API access from Pods” is a concept people need to read up on separately from the Kubernetes API overall. We could add a section to https://kubernetes.io/docs/concepts/overview/kubernetes-api/ that links to the relevant task page (and if we do make a task page for it, I recommend adding exactly that link).

/remove-lifecycle stale
