### ISSUE TITLE
Improve documentation for IPv4/IPv6 dual-stack

### ISSUE THREAD

**Issue by aojea** [kubernetes/website#25661]
This feature has gone through a significant refactor during the 1.19 cycle, and current information is outdated.

We need to update the website to reflect these changes

**Comment by aojea** [comment]
ping @khenidak @bridgetkromhout @lachie83

**Comment by sftim** [comment]
/retitle Improve documentation for IPv4/IPv6 dual-stack
/kind cleanup
/sig network
/priority backlog
(because feature is alpha)

/triage accepted

**Comment by sftim** [comment]
I'm happy to give related PRs a once-over, including testing out any task pages to make sure you can follow them from start to finish OK.

**Comment by aojea** [comment]
my apologies, I think I wrongly saw an outdated page, current docs are up to date
https://github.com/kubernetes/website/commit/8a3244fdd1ab0c9b762b33d28b99f6fee8c1c9d6
