### ISSUE TITLE
ja: Translate reference/tools/ into Japanese

### ISSUE THREAD

**Issue by kosehy** [kubernetes/website#25689]
This is a Feature Request

What would you like to be added

Translate reference/tools/ into Japanese

Why is this needed
No translation reference/tools/ into Japanese

Comments

Page to Update:
https://kubernetes.io/docs/reference/tools/

/language ja
/assign

**Comment by task4233** [comment]
Hello, @kosehy.
If you have not translated, Could you give me a chance of this translation?
In fact, I have already translated this page without noticing this issue.
Thus, I would like to send a pull request for this issue.

I look forward to your reply.
Thanks in advance.

**Comment by kosehy** [comment]
> 
> 
> Hello, @kosehy.
> If you have not translated, Could you give me a chance of this translation?
> In fact, I have already translated this page without noticing this issue.
> Thus, I would like to send a pull request for this issue.
> 
> I look forward to your reply.
> Thanks in advance.

Hi @task4233,
You can send a pull request for this issue.
I hope you have a great day!
