### ISSUE TITLE
Typo in “Managing Resources for Containers”

### ISSUE THREAD

**Issue by pnosov** [kubernetes/website#25687]
"The kubelet performs regular, schedules checks that scan each emptyDir volume, container log directory, and writeable container layer." in https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-emphemeralstorage-consumption

Should be "regular, scheduled checks".

**Comment by sftim** [comment]
/retitle Typo in “Managing Resources for Containers”
/kind bug
/triage accepted
/language en
/good-first-issue

To fix this, open a pull request containing one commit. The commit should change the Markdown source of https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/ to use the correct spelling.

Thanks @pnosov

**Comment by pnosov** [comment]
PR: https://github.com/kubernetes/website/pull/25693
/close
