### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by sagarmujumale** [kubernetes/website#25705]
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

this command is showing below error,

gpg: no valid OpenPGP data found.

if gpg is no longer valid then we are unable to install any valis packages

**Comment by neolit123** [comment]
Does this happen all the time? These google sites are known to fail on rare
occasions.

But if you are behind a firewall there is not much we can do. You can try
using a proxy in that case.

**Comment by sftim** [comment]
```
$ curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048/0x6A030B21BA07F4FB 2018-04-01 [SCE] [expires: 2021-03-31]
      54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
uid                             Google Cloud Packages Automatic Signing Key <gc-team@google.com>
pub   rsa2048/0x8B57C5C2836F4BEB 2020-12-04 [SC] [expires: 2022-12-04]
      59FE0256827269DC81578F928B57C5C2836F4BEB
uid                             gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>
sub   rsa2048/0x48419E688DD52AC0 2020-12-04 [E]
```
That works for me. I wonder if packet filtering is the problem as https://github.com/kubernetes/website/issues/25705#issuecomment-748486064 suggests.

/priority awaiting-more-evidence
