### ISSUE TITLE
“Deploying PHP Guestbook application with Redis” tutorial not working

### ISSUE THREAD

**Issue by neethu-mohanan** [kubernetes/website#25704]
The images are not reachable and redis-master and redis-slave deployment creations fail due to ErrImagePull status

**Comment by sftim** [comment]
I haven't checked, but that sounds very plausible.
/kind bug
/priority important-longterm

**Comment by sftim** [comment]
/retitle “Deploying PHP Guestbook application with Redis” tutorial not working
