### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by FerminCastro** [kubernetes/website#25703]
Quote from the doc:

"If any API servers are running in your cluster, you should not attempt to restore instances of etcd. Instead, follow these steps to restore etcd:

    stop all kube-apiserver instances
    restore state in all etcd instances
    restart all kube-apiserver instances

We also recommend restarting any components (e.g. kube-scheduler, kube-controller-manager, kubelet) to ensure that they don't rely on some stale data. Note that in practice, the restore takes a bit of time. During the restoration, critical components will lose leader lock and restart themselves."

There is no "documented way" to perform such an operation as 1)stopping kube-apiserver 2)doing "something" and 3)starting kube-api server. For the default k8 topology with kube-api server running in pods, no single document describes how to stop it, do some maintenance and start it again...

**Comment by sftim** [comment]
/kind feature
/triage accepted
/priority backlog

Thanks for the suggestion!

**Comment by sftim** [comment]
These skills are also on the syllabus for the CKA and CKS qualifications.

**Comment by FerminCastro** [comment]
To be frank, no matter how many kubernettes docs you read, restoring etcd in a kubeadm-generated system with multiple masters is just incomprehensible :-)

**Comment by FerminCastro** [comment]
Ok, following this "request for doc improvement" we have conducted a number of tests to restore ETCD for a 3 node control plane with internal etcd. Basically the two tests threw the same results: render the cluster USELESS. In the first test we stopped the etcd and kube-apiserver pods in all three nodes (by the way, as I was indicating above, there is no documented procedure to do this, the only way we found was moving manifests), we restored THE SAME etcd snapshot in all three nodes. The result was that the three nodes were reported AS ETCD LEADERS and all using the SAME UID!:

-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|    ENDPOINT     |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 10.10.0.23:2379 | 8e9e05c52164694d |   3.4.3 |  8.0 MB |      true |      false |         2 |       1085 |               1085 |        |
| 10.10.0.24:2379 | 8e9e05c52164694d |   3.4.3 |  8.0 MB |      true |      false |         2 |       1085 |               1085 |        |
| 10.10.0.25:2379 | 8e9e05c52164694d |   3.4.3 |  8.0 MB |      true |      false |         2 |       8536 |               8536 |        |
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

Any queries to kube-apiserver (again this is a 3 node k8 control plane with a front end load balancer) would throw totally inconsistent results where one second pods would be shown as running and the next one they would be shown as pending (as if each query was being directed by the load balancer to a different leader and each one was reporting different information) 

We then rebuilt everything from scratch and tried again, but this time we restored each individual etcd pods’ snapshot in each one of the nodes. the result was similar only that now we got different IDS for the etcd member. But still all of them were reported as leaders.

IMO kubernetes documentation should address this use case in detail. This (internal etcd) is pretty specific to the kubernetes topology (not to ectd per se) and kubernetes management (again in an external etcd system I can control etcd process, in an internal one I cannot). So please make sure someone describes this in detail or people may end up with many broken systems  :-)

**Comment by FerminCastro** [comment]
I though that someone would grab this to provide the steps in detail (i.e. as part of the steps referencing etcd backup in the K8 documentation here: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/ 

The steps provided there are vague, imprecise and can cause that people ruin their Kubernetes clusters

**Comment by FerminCastro** [comment]
I think that the part that needs to be much more specific in the links above is this:
----------------------------------------------------------------------
    Note:

    If any API servers are running in your cluster, you should not attempt to restore instances of etcd. Instead, follow these steps to restore etcd:

        stop all API server instances
        restore state in all etcd instances
        restart all API server instances

    We also recommend restarting any components (e.g. kube-scheduler, kube-controller-manager, kubelet) to ensure that they don't rely on some stale data. Note that in practice, the restore takes a bit of time. During the restoration, critical components will lose leader lock and restart themselves.
----------------------------------------------------------------------

Specially for a kubeadm-generated system with stacked etcd. I can share how we do it.
