### ISSUE TITLE
Improvement for k8s.io/docs/reference/using-api/client-libraries/

### ISSUE THREAD

**Issue by collimarco** [kubernetes/website#25734]
There is a link to this Ruby library, but it is no longer maintained (last commit on Nov 2014 - 6 years ago!):
https://github.com/Ch00k/kubr

It should be probably removed, since there are other libraries in Ruby.

**Comment by sftim** [comment]
Hi @collimarco 

We (Kubernetes) don't really curate the list of third party client libraries; in fact there's an explicit warning that we do not. I think the existing approach would suggest keeping the link and letting readers form their own opinion about suitability - for example, by looking for recent commits.

Maybe there's a reason to specifically omit this one (for example, if using it at all is an information security concern)

/priority awaiting-more-evidence
