### ISSUE TITLE
Hello Minikube

### ISSUE THREAD

**Issue by surendra080196** [kubernetes/website#25730]
Getting this error in kubernetes 
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by sftim** [comment]
/kind support

It sounds like you're asking for help troubleshooting Kubernetes @surendra080196 
Have I got that right?

**Comment by Aut0R3V** [comment]
I feel like the following commands might solve the problem :
sudo mkdir ~/.kube
sudo cp /etc/kubernetes/admin.conf ~/.kube/

cd ~/.kube

sudo mv admin.conf config
sudo service kubelet restart

**Comment by surendra080196** [comment]
Hi,
kubernetes  showing this error after applying the this (sudo cp /etc/kubernetes/admin.conf ~/.kube/) command.

cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
/shoutout

how to generate the admin.conf

please tell me.

Thankyou.

**Comment by Aut0R3V** [comment]
Okay, It'll be great if you can go these two links, I'm pretty sure your problem might be resolved here. 
There's a detailed article on medium about this - https://medium.com/@texasdave2/troubleshoot-kubectl-connection-refused-6f5445a396ed
I feel like this is a potential solution. If however this doesn't work, then you can refer to this link :
https://discuss.kubernetes.io/t/the-connection-to-the-server-localhost-8080-was-refused-did-you-specify-the-right-host-or-port/1464/2
However ^ it recommends installing kubernetes from scratch. not sure if that's the best alternative. 
Hope you're able to resolve the issue.
