### ISSUE TITLE
Document how to find cluster domain name

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25758]
**This is a Feature Request**

**What would you like to be added**
By default the Kubernetes cluster domain is _cluster.local_ but it isn't always. Add documentation on how to find out what cluster domain is set for **your** cluster. 

**Why is this needed**
Readers might / would like to know how to check the cluster's domain, even if they don't have administrative access to the control plane / the `kube-system` namespace.

**Comments**
Ideally, this advice should not rely on the cluster using a particular add-on (eg CoreDNS).

/kind feature
/language en

**Comment by Aut0R3V** [comment]
/assign
@sftim where exactly do you think this can go?
I think this can go here - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by Aut0R3V** [comment]
Also I think the following details can be added :
The domain name for a cluster can be identified by adding the cli option --domain. In many of the cases, the default name is cluster.local. 
This can be added just below the A/AAAA records subsection in the Pods heading - 
https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/services-networking/dns-pod-service.md#aaaaa-records-1
Please tell if I'm wrong here.

**Comment by tengqm** [comment]
@Aut0R3V The issue is not about how to configure the domain name. It is instead about how to discover the domain name configured by your cluster's admin. So maybe the `/etc/resolv.conf` is a good starting point.

**Comment by sftim** [comment]
I think this would be a Task page. Maybe “Discover cluster settings” for a title (and cover other settings too?).

Maybe a specific page for each task - but then with very many task pages, each task page becomes harder to discover - unless we also improve the search / navigation. Better search would be nice but is far outside the scope of _this_ issue.

**Comment by sftim** [comment]
How does “Discover cluster settings” sound?

**Comment by Aut0R3V** [comment]
> @Aut0R3V The issue is not about how to configure the domain name. It is instead about how to discover the domain name configured by your cluster's admin. So maybe the `/etc/resolv.conf` is a good starting point.
Thanks for the clarification @tengqm. 

> How does “Discover cluster settings” sound?
"Discover cluster settings" sounds great. Can you specify all the details that should be included there? I think it'll be pretty interesting to work on this.

**Comment by jlpedrosa** [comment]
This is a very useful feature for the operators, specially if there would be a way to find it out through an API request.

**Comment by sftim** [comment]
If you have a cluster where the API server runs as Pods, and these pods are mirrored into the Kubernetes API, _and_ you have[ Service Account Token Volume Projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) enabled, then this might help because it usually shows the cluster domain name as part of the URL.
```bash
kubectl cluster-info dump --output=yaml | grep service-account-issuer
```

**Comment by jlpedrosa** [comment]
I'd say an universal solution through the API is interesting in any case. For instance your approach is not valid for Azure k8s service.

**Comment by sftim** [comment]
/remove-lifecycle rotten

We should document what's possible now. If we wanted an API mechanism (a successor to ComponentStatus perhaps?), that'd need as KEP.
