### ISSUE TITLE
Init-Container status describe fault 

### ISSUE THREAD

**Issue by mingyuanzhu** [kubernetes/website#25751]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

I think there is a typo in the below sentence, the Initialized should be set to **false**

A Pod cannot be Ready until all init containers have succeeded. The ports on an init container are not aggregated under a Service. A Pod that is initializing is in the Pending state but should have a condition Initialized set to **true**.

The screenshot is from my testing env. You can see the Initialized is **false**
![image](https://user-images.githubusercontent.com/6222056/102848316-84707600-444f-11eb-885e-df16f41dc7ff.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

**Comment by jai** [comment]
@mingyuanzhu @tengqm I think this issue can be closed.
