### ISSUE TITLE
Move away from dockershim instructions: create a new section under Tasks

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#25768]
**This is a Feature Request**

I want to ask a new documentation section under [Tasks](https://kubernetes.io/docs/tasks/) describing various aspects of moving away from Dockershim to other runtimes. One document I am working with is: https://docs.google.com/document/d/1ZFi4uKit63ga5sxEiZblfb-c23lFhvy6RXVPikS8wf0/edit#heading=h.zhgtsiu70nbk There are more sub-topics will be there.

Is there any concerns with creating this section? It will be relatively short-lived, but definitely beneficial for k8s users.

**What would you like to be added**

Section under [Tasks](https://kubernetes.io/docs/tasks/) regarding migrating away from Dockershim.

**Why is this needed**

Since this announcement: https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/ there are a still things needed clarification which raise questions.

/sig node

**Comment by sftim** [comment]
A Task page is the right kind of content to add.
Are you considering adding a section inside https://kubernetes.io/docs/tasks/administer-cluster/ @SergeyKanzhelev ? I would add that rather than one inside https://kubernetes.io/docs/tasks/ - the deeper structure can be OK so long as we make sure there are lots of links to it.

When that content _disappears_, where will we redirect to? I assume we'd want to add redirects

**Comment by SergeyKanzhelev** [comment]
@sftim what do you think of this: https://github.com/kubernetes/website/pull/25787? Is it the right structure?

**Comment by SergeyKanzhelev** [comment]
@kbhawkey this was my original idea of a location, but @sftim suggested to place it under the administer section. @sftim, looking at the content, should it be moved to it's own section? Some topics like monitoring agents is more of an application management than administering of a cluster.

**Comment by sftim** [comment]
My _concerns_ from before stand, but they're not hard don't-do-this objections.

**Comment by sftim** [comment]
/triage accepted
anyway

**Comment by kbhawkey** [comment]
> @kbhawkey this was my original idea of a location, but @sftim suggested to place it under the administer section. @sftim, looking at the content, should it be moved to it's own section? Some topics like monitoring agents is more of an application management than administering of a cluster.

Hi @SergeyKanzhelev .
I'll spend some time to read the PR and doc.
After a quick read, I think it probably make sense to separate the content from the `administer-cluster` tasks.
Again, it is a good idea to write an outline of the content. This may help to determine where
to put the content once the content is created.

**Comment by kbhawkey** [comment]
Hope this is okay:
/assign @SergeyKanzhelev
