### ISSUE TITLE
Remove or revise diagram for services and labels

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#25774]
This is a followup for #25169.

Diagram on https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

The problem is that the diagram is misleading. It is not correctly depicting the relationship between a Deployment and a Node, i.e. a Deployment can span multiple Node. The diagram is also "overloaded", i.e. trying to deliver too much information in a single view.

Maybe we should remove it, or better yet, revise it for clarity.

**Comment by shuuji3** [comment]
Many newcomers start from the tutorials and they tend to overwhelm by a lot of new concepts. Diagrams help the users to understand new concepts so I think it's preferable to replace better diagrams rather than remove them completely.

**Comment by mehmetefeumit** [comment]
It has not been long since I learned Kubernetes and I agree with @shuuji3 that diagrams play an important role in making the tools accessible. I'll happily work on a new diagram; it will be my first contribution to Kubernetes...

**Comment by sftim** [comment]
:+1: for revise

**Comment by sftim** [comment]
/triage accepted

If revising, and _even if_ the revised diagram looks different from other tutorials, I recommend using icons from https://github.com/kubernetes/community/tree/master/icons

See https://kubernetes.io/docs/concepts/overview/components/ for an example of visual style (it renders pretty much anywhere but IMO looks best in Chrome / Chromium).

**Comment by mehmetefeumit** [comment]
Made a replacement for the diagrams on https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/ . There is two very similar diagrams on the page and the only difference between the two is that the second one has labels. This might act as a replacement for both. Any suggestions and comments are greatly appreciated...

![replacement](https://user-images.githubusercontent.com/8224932/103086802-97717a80-45f6-11eb-9d55-d63b48c8cbfa.PNG)

**Comment by sftim** [comment]
- I'd use the blue color everywhere for the icons, but feel free to use a different color for the labels. The Pod labelled `app=B` should be blue not purple. I would make the _label_ for B be purpl;e.
- _aside_ The Kubernetes fonts are [Open Sans](https://fonts.google.com/specimen/Open+Sans) for main text and [Ubuntu](https://fonts.google.com/specimen/Ubuntu) for the logotype
- I'm not sure what that diagram is showing. It looks like there's a Deployment with 3 Pods (the ReplicaSet is not shown) and a bare Pod, and all 4 match the selector for the Service. There is also a bare Pod for app B. I don't see any Endpoints object, that might be useful to illustrate.
- for the Service, the selector is `app=A` but it's not clear that that's a selector. How about changing the labels for the Pods and for the Deployment to be `app: A` / `app: B`, that way the selector stands out? I would _also_ label the selector with the text “selector” or add a key to the diagram.
- in the Deployment, it's relevant that its Pods are labelled as app A. The label on the deployment is not relevant.

That's quite a lot of feedback - feel free to ask for more detail on any point @mehmetefeumit.

**Comment by mehmetefeumit** [comment]
@sftim Thank you for the feedback. I got rid of the purple pod and made the contrast between the labels and the selector more distinct. I added the ReplicaSet to make the diagram more accurate, and moved the label from the deployment to the pods. The latest version is below:
![replacement](https://user-images.githubusercontent.com/8224932/103090181-5763c500-4601-11eb-8e8d-3fce6c49f8f9.PNG)

The only part I am uncertain about is adding the endpoints. The main purpose of the text is to explain how selectors and labels are used to assign pods to services. Wouldn't adding endpoints make the diagram more complex than necessary?

**Comment by sftim** [comment]
That looks good - would you be willing to send in a pull request @mehmetefeumit ?

---

_The rest of this feedback describes future work._

_As well_ (maybe a second PR?) I think I'd like to see a diagram that shows the packet flow, so this would include a load balancer and the 4 selected Pods. Probably _not_ nodes, unless we think that's needed. We could make a more complex version of that diagram that also shows Endpoints / EndpointSlice objects, and add the complex diagram to https://k8s.io/docs/concepts/services-networking/service/ 

The ideal outcome for me is that someone looking at this tutorial sees a hyperlink to a related page, and the reader can go from the tutorial page to another page that expands on the explanation without being overwhelming.

**Comment by mehmetefeumit** [comment]
I'd love to send in a PR, but I have not been able to get Hugo working to test the dimensions of the image before committing. It keeps producing errors when I try to build the website in a container. I have all the dependencies installed and have no idea why this is happening.

```
Error: Error building site: "/src/content/vi/blog/_index.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
make: *** [container-serve] Error 255
```

**Comment by shuuji3** [comment]
@mehmetefeumit Awesome! Thank you for creating a new diagram. I think it's much better than the current one.

Here's some feedback:
- How about using the Labeled icons instead of Unlabeled ones from [community/icons](https://github.com/kubernetes/community/tree/master/icons)? I think adding hints is better especially for the Pod icons. It's difficult for readers who see the Kubernetes icon for the first time, to understand the meaning of icons without labels.
- I feel the label color (for example "Deployment") is a bit too light and the contrast is low. Maybe the current color is #999999? How about changing it to #666666? It's conformant with the accessibility standard. You can check the color contrast with [WebAIM: Contrast Checker](https://webaim.org/resources/contrastchecker/).

For the container build error, did you try to follow [the instructions on the README.md](https://github.com/kubernetes/website#using-this-repository)?

**Comment by mehmetefeumit** [comment]
Thank you for the feedback. I applied your suggestions and fixed a couple of inconsistencies with the font coloring etc. The most recent is below:

![replacement-svc-selector](https://user-images.githubusercontent.com/8224932/103129901-8171c180-46ab-11eb-8343-3d48d19e19f3.PNG)

I will try to solve the container build error today.

**Comment by mehmetefeumit** [comment]
Thank you for the feedback. I applied your suggestions and fixed some consistency errors with coloring, positioning etc. The latest version is below:

![svc-selector-replacement](https://user-images.githubusercontent.com/8224932/103130056-2a202100-46ac-11eb-803c-fb0eb5bd4b95.PNG)

I will try to fix the container build error today. Yes, I followed the instructions on the README.md (a couple of times) but no luck. Regardless, I'll send an update.

**Comment by shuuji3** [comment]
It looks good to me. Thank you @mehmetefeumit!

That's unfortunate...😢 But if you open a PR against the `master` branch on this repository, the preview build will be triggered by Netlify. So we can check what looks like the change of the page and diagram.

**Comment by tengqm** [comment]
This diagram looks good to me. One improvement I can think of is to change the service IP to a different subnet.
