### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by BunnyFiscuit** [kubernetes/website#25818]
Replace 'hello' with something else so it's easier to distinguish where which name is being used.. hard to follow the guide.
An example I can give is from the 'Creating the frontend' section, in particular the nginx configuration.

```
upstream hello {
    server hello;
}

server {
    listen 80;

    location / {
        proxy_pass http://hello;
    }
}
```
Since both the backend and frontend are named hello, it's unclear which 'hello' this refers to.

**Comment by sftim** [comment]
/kind cleanup
/language en
/help
/triage accepted

Thanks @BunnyFiscuit

**Comment by murillodigital** [comment]
Hi @sftim - looking for my first opportunity for contributing and I don't think it gets any safer than this ;) don't see a `good first issue` label on it though. Would this issue be assignable to a first timer?

**Comment by Aut0R3V** [comment]
I feel like to patch up things simply, we can refer it as "Hello" instead of hello at the required places where it affects the workflow. If I'm not wrong, @BunnyFiscuit is referring to the guide here : https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

**Comment by Aut0R3V** [comment]
@murillodigital you can go to the service/access/frontend.conf codenew file.  Also I think there would be some changes needed in the documentation also, this looks like a great work to get your feet wet.

**Comment by murillodigital** [comment]
@Aut0R3V thnx for feedback and we're on the same page ;) will work on changes - @sftim please confirm you're cool with this, not sure if I can assign the issue to myself or one of you will have to.

**Comment by Aut0R3V** [comment]
you can assign yourself with the /assign <name> command.
Anything I can do here?

**Comment by murillodigital** [comment]
all good @Aut0R3V appreciate the availability, have assigned and will issue a PR. Will reach out if I need any directions.
