### ISSUE TITLE
Improvement for k8s.io/zh/docs/concepts/services-networking/dual-stack/

### ISSUE THREAD

**Issue by Sebastien10115985** [kubernetes/website#25819]
ipFamily: IPv6 
should be
ipFamilies: ["IPv6"]
or you will get an error.

**Comment by sftim** [comment]
/kind bug
https://kubernetes.io/zh/docs/concepts/services-networking/dual-stack/ is out of date with the latest (alpha) implementation of dual-stack networking.
/language zh

I think this should have /priority backlog and /triage accepted; does that sound right?

**Comment by tengqm** [comment]
#25776 is coming in.

**Comment by howieyuen** [comment]
already fixed 
/close
