### ISSUE TITLE
Migrate https://kubernetes.io/docs/concepts/cluster-administration/certificates/ to tasks section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25833]
**This is a clean up request**

**What would you like to be added**

**Why is this needed**
https://kubernetes.io/docs/concepts/cluster-administration/certificates/ is a task page. A better home for it would be within https://kubernetes.io/docs/tasks/administer-cluster/

**Comments**
Be sure to add Netlify redirects (see `/static/_redirects`) from the old to the new page.

/language en
/kind cleanup

**Comment by sftim** [comment]
From https://github.com/kubernetes/website/pull/26119#issuecomment-773326471:
> Perhaps the current Certificates page could be split: leave the a certificates concept page and add a new task page?

(I agree)

**Comment by kbhawkey** [comment]
I left notes (PR #26119) about how to create a new task page from the `Certificates` page. Does this sound like a good approach?
