### ISSUE TITLE
Install Service Catalog using Helm returns 403

### ISSUE THREAD

**Issue by polskikiel** [kubernetes/website#25834]
Commands located under this [article](https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/#add-the-service-catalog-helm-repository ) and [here](https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/#install-service-catalog-in-your-kubernetes-cluster) are not working with the following reason:

```
$ helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
Error: looks like "https://svc-catalog-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://svc-catalog-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```
```
helm install catalog svc-cat/catalog --namespace catalog
Error: failed to download "svc-cat/catalog" (hint: running `helm repo update` may help)
```

running `helm repo update` didn't help

**Comment by polskikiel** [comment]
ok I see that issue for this was already created: https://github.com/kubernetes-sigs/service-catalog/issues/2869, closing as it should be resolved there

**Comment by devopsception** [comment]
i tried downloading the chart manually and installed locally; even that did not work.

**Comment by suneetk92** [comment]
Downloading the chart from https://github.com/kubernetes-sigs/service-catalog/tree/master/charts/catalog and installing it locally worked for me.
