### ISSUE TITLE
Using Admission Controllers: too old content (for v1.9 or earlier) could be removed

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#25853]
The paragraph below contains too old content.
"For Kubernetes version 1.10 and later, " and contents after "Notes" could be removed.
The shorter, the easier to understand.

https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#is-there-a-recommended-set-of-admission-controllers-to-use

**Comment by sftim** [comment]
/close 

Address in PR #25966
