### ISSUE TITLE
Container runtimes

### ISSUE THREAD

**Issue by kylejep** [kubernetes/website#25878]
**Problem:**
The documentation references loading the overlay and br_netfilter kernel modules at both of these locations:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- Modules do not persist reboots
- Documentation states that they will persist across reboots.
- Cluster will fail pre-flight if modules are not loaded

**Proposed Solution:** 
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
In installation prerequisites add:
cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
overlay
br_netfilter
EOF

This is correct in the containerd installation prerequisites but appears missing from CRI-O. Modules do not appear to persist across reboots unless /etc/modules-load.d has a config reference to load at boot.

In the example given at
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
add:
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF

**Comment by neolit123** [comment]
@kylejep 
a PR with the fix is welcome.

/sig node cluster-lifecycle
/triage accepted

**Comment by kylejep** [comment]
#25895 
#25896
Thank you PRs submitted.

**Comment by neolit123** [comment]
please close this once the PRs merge.
