### ISSUE TITLE
Create a doc to explain how to change the runtime (mostly moving away from dockershim)

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#25879]
**This is a Feature Request**

As part of https://github.com/kubernetes/website/pull/25787 

**What would you like to be added**

Have a `content_type: task` type of a documentation that describe the supported way to transition from one runtime to another. It may be a page under [Dockershim deprecation tasks]( https://github.com/kubernetes/website/pull/25787),  [upgrade doc](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/), or an alternative location under "runtimes".

**Why is this needed**

With the Dockershim deprecation, having a clear step by step documentation of replacing the runtime would be needed before moving to the next step of dockershim removal.

**Comments**

KEP: kubernetes/enhancements#2221

See discussions:
- https://github.com/kubernetes/website/pull/25787#issuecomment-752733581

/sig node
/cc @neolit123

**Comment by Aut0R3V** [comment]
Is anyone working on this? I'm interested for working on this issue.

**Comment by SergeyKanzhelev** [comment]
> Is anyone working on this? I'm interested for working on this issue.

nobody working on it right now. So please go ahead. Do you want to discuss the proper placement of this document in the issue of prefer to start with the draft of a document?

**Comment by Aut0R3V** [comment]
It'll be great to hear whatever you can recommend. I'll send in a draft then

**Comment by SergeyKanzhelev** [comment]
> It'll be great to hear whatever you can recommend. I'll send in a draft then

Sorry for delay. My suggestion would be to start with the document that replicates content from "Upgrade worker nodes" section here: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrade-worker-nodes 

And instead of kubelet update - provide instructions on changing from docker to containerd.

**Comment by msschl** [comment]
Any updates on this? Would be nice to have a migration guide as we plan to move our kubeadm cluster away from dockershim.

**Comment by neolit123** [comment]
i'm pretty sure the steps would be similar to this:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#migrating-to-the-systemd-driver

> ...
> Stop the container runtime
> ...
> Start the container runtime <-- here is where you start a different container runtime
> ...

but SIG node should confirm if this is actually the right way.

you could create a test cluster and try migrating it.

**Comment by Debanitrkl** [comment]
/remove-lifecycle stale
Working on this here https://github.com/kubernetes/kubernetes/issues/104878

**Comment by sftim** [comment]
/priority important-soon
Folks want to know how to migrate

**Comment by afbjorklund** [comment]
We are missing documentation on how to move `docker build` away from dockerd, over to buildkitd...

Moving away from Docker leaves users without any documented method of building container images.

Suggested migration approaches included `nerdctl`.

Or even writing your own wrapper, like minikube had to.

**Comment by afbjorklund** [comment]
I was specifically referring to the (questionable) practice of building container images directly on the nodes.

It is not possible to use `docker build`, if dockerd has been replaced with containerd. Need to add buildkitd.

**Comment by afbjorklund** [comment]
The FAQ has been updated, and has better info about building (after switching to containerd) now:

https://kubernetes.io/blog/2020/12/02/dockershim-faq/#what-should-i-look-out-for-when-changing-cri-implementations

> Another thing to look out for is anything expecting to run for system maintenance or nested inside a container when building images will no longer work. For the former, you can use the crictl tool as a drop-in replacement (see mapping from docker cli to crictl) and for the latter **you can use newer container build options like img, buildah, kaniko, or buildkit-cli-for-kubectl that don’t require Docker**.

We detailed the manual steps in minikube, such as installing and configuring `buildkitd` and `buildctl`:

https://minikube.sigs.k8s.io/docs/handbook/pushing/#6-pushing-directly-to-in-cluster-containerd-buildkitd

Using `kubectl build` is a more flexible, even if slightly more complicated, way of doing the same thing:

https://github.com/vmware-tanzu/buildkit-cli-for-kubectl/blob/main/docs/architecture.md

**Comment by KelvinAkpobome** [comment]
I will like to take on this

**Comment by chrisnegus** [comment]
I believe documentation is done to meet the intent of this issue, including [How to find out what container runtime is used on a Node](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use/), as well as instructions for migrating from using dockershim to:
* [containerd](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/)
* [cri-dockerd](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd/)
Beyond that, @afbjorklund asked for docs describing replacements for using `docker build` on nodes, then points to content covering that topic in [this comment](https://github.com/kubernetes/website/issues/25879#issuecomment-997200306). I will give everyone few day to comment on whether more is needed before I close this Issue.

**Comment by afbjorklund** [comment]
As far as I know, the information on how to build images is available in the container runtimes (outside k8s.io).

The main highlight was that it is not covered with `crictl`, so that you _need_ to use something outside of CRI ?

For containerd, that means installing and configuring [buildkit](https://github.com/moby/buildkit).

But it does **not** have to be addressed before closing this issue.

**Comment by chrisnegus** [comment]
@afbjorklund Thanks for your insight here. Would it be appropriate to open a separate issue for the k8s.io docs to cover the issue of building containers (that could be handled after 1.24) or it is okay to leave that to the runtime docs, outside of k8s.io?

**Comment by afbjorklund** [comment]
It is my understanding that kubernetes.io will not carry _any_ documentation for _any_ container runtime.

But please check with the SIG Docs members, I was just remotely following issues such as PR #32738.

**Comment by sftim** [comment]
If we wanted to explain how to build container images, that might be a topic better covered on the blog.

If someone wants to, that could either be a survey of existing articles that already cover it (there must be hundreds), or a new article that also explains how to get your built container running in Kubernetes.

I think that's a separate thing from what _this_ issue is about: explaining how to change which container runtime your cluster uses.

**Comment by afbjorklund** [comment]
We added `minikube image build` and `minikube image load`, to help users move away from using `docker`.

Some users might prefer to run two VMs, one for building images and one (or more) for running the cluster.
That works fine too (just slower), and then they can have dockerd in the first and containerd in the second.

The only thing we need to explain, is that if they change their runtime - our "docker-env" stops working.

`❌  Exiting due to MK_USAGE: The docker-env command is only compatible with the "docker" runtime, but this cluster was configured to use the "containerd" runtime.`

Hopefully the (minikube) error message is clear enough.

**Comment by chrisnegus** [comment]
> @chrisnegus I suggest marking this as done, and tracking a new issue (based on something I just spotted):
> 
> The [v1.24 docs](https://deploy-preview-31225--kubernetes-io-vnext-staging.netlify.app/docs/tasks/administer-cluster/migrating-from-dockershim/) recommend moving away from dockershim. I think we need to word it more strongly than that.
> 
> Do you agree?

I agree. I think we can close this issue, since the migration content has been addressed and we are well enough covered for image building documentation. I'll open a post-1.24 Issue to consider stronger wording to people for getting off of Dockershim.

**Comment by chrisnegus** [comment]
> > @chrisnegus I suggest marking this as done, and tracking a new issue (based on something I just spotted):
> > The [v1.24 docs](https://deploy-preview-31225--kubernetes-io-vnext-staging.netlify.app/docs/tasks/administer-cluster/migrating-from-dockershim/) recommend moving away from dockershim. I think we need to word it more strongly than that.
> > Do you agree?
> I agree. I think we can close this issue, since the migration content has been addressed and we are well enough covered for image building documentation. I'll open a post-1.24 Issue to consider stronger wording to people for getting off of Dockershim.
Done. I opened [Issue #32827](https://github.com/kubernetes/website/issues/32827). I think we should revisit it after 1.24.
