### ISSUE TITLE
No need to enable RuntimeClass feature gate since it is a GA feature

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#25875]
RuntimeClass feature gate is GA in 1.20. According to [feature gate document](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-stages), a GA feature cannot be disabled and the feature gate is no longer needed. The explanation below can be removed.

> Ensure the RuntimeClass feature gate is enabled (it is by default). See Feature Gates for an explanation of enabling feature gates. The RuntimeClass feature gate must be enabled on apiservers and kubelets.

https://kubernetes.io/docs/concepts/containers/runtime-class/#setup

**Comment by tengqm** [comment]
triage/accepted
