### ISSUE TITLE
Container runtimes - Cgroup drivers documentation conflicts with cautionary note in service file

### ISSUE THREAD

**Issue by rpschlak** [kubernetes/website#25898]
Per the docs: https://kubernetes.io/docs/setup/production-environment/container-runtimes/
To improve stability systemd is preferred:
"Changing the settings such that your container runtime and kubelet use systemd as the cgroup driver stabilized the system. To configure this for Docker, set native.cgroupdriver=systemd."

However, in reading a note left by the developer in: (/usr/lib/systemd/system/docker.service) this suggestion is emphatically cautioned against:
[Service]
Type=notify
  the default is not to use systemd for cgroups because the delegate issues still
  exists and systemd currently does not support the cgroup feature set required
  for containers run by docker

Am I mis-reading these? Or is the answer "It depends", if so, then on what?

**Comment by Aut0R3V** [comment]
Can any of the members comment on this? I feel like the documentation should be edited for this.

**Comment by keshy** [comment]
+1 This really needs to be updated.
