### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by surendrakrp08** [kubernetes/website#25894]
Not able to connect master and node  
(kubeadm join 172.31.7.49:6443 --token 911fn7.68zku6z3wq1p8v7k --discovery-token-ca-cert-hash sha256:639e8169f109bf06a132efb2b333d3be82c362968a9cf16cce0ef10f5fdf2df9) using this kubeadm join

P
![Screenshot (20)](https://user-images.githubusercontent.com/76788214/103413626-6c5fcb80-4ba0-11eb-8d02-78c5b70e3094.png)
lease help me.

**Comment by Aut0R3V** [comment]
@surendrakrp08 I feel like this has to do something related to the issues in the installation process. Can you please describe the installation details?
Also you can check for errors in the following meanwhile :
- Are the node VM time zones same? If not, you can correct that. 
- You can try stopping the Firewalld and then try to add the nodes.

**Comment by surendrakrp08** [comment]
Hi,

 I am checking the Vm time zones, firewalls.
vm time zones are the same and firewalls are stopped.

but same showing this error

kubernetes to see the stack trace of this error execute with --v=5 or higher
please help me.

**Comment by Aut0R3V** [comment]
Okay. Adding the error makes the overall problem easier to comprehend. Please try using “kubeadm token create” on the master node and try creating a new valid token. 
If this doesn't solve the problem, please refer to the solution referred by tony_dad here :https://discuss.kubernetes.io/t/not-able-to-join-node-to-master/7123/4
I hope this solves your problem!

**Comment by neolit123** [comment]
this discussion belongs in the support forums like https://discuss.kubernetes.io/

/close

**Comment by surendrakrp08** [comment]
Done.
