### ISSUE TITLE
名字空间

### ISSUE THREAD

**Issue by jikunbupt** [kubernetes/website#25908]
这边文档中描述“Kubernetes 会创建三个初始名字空间：”，事实上现在默认创建四个默认明明空间default、kube-node-lease、kube-public、kube-system。

**Comment by Cweiping** [comment]
Please clarify your issue and unexpected page. Thx!
/triage needs-information

**Comment by tengqm** [comment]
If I recall correctly, this has been fixed. Please reopen if the problem is still there.
/close
