### ISSUE TITLE
Create a Security guide

### ISSUE THREAD

**Issue by Aut0R3V** [kubernetes/website#25913]
**This is a Feature Request**

**What would you like to be added**

An official documentation about Kubernetes hacking and different threat scenarios that might render various components prone to vulnerabilities.

**Why is this needed**

This could be a great initiative to develop documentation about Kubernetes Security. There's great work going on in this field, but I strongly believe that much more can be achieved. 

**Comments**

I have a plan about this and I would like to personally volunteer to work on this project.

**Comment by Aut0R3V** [comment]
It'll be great to hear from members about this. @sftim any views on this?

**Comment by sftim** [comment]
/sig security
SIG Security: feel free to _/triage accepted_ and / or comment on this.

**Comment by Aut0R3V** [comment]
I just noticed this is quite similar to  #25119.  Should I close this issue and work on the already existing one? The first step I feel would be to mention the plan in detail followed by commits.

**Comment by sftim** [comment]
I would follow up issue #25119 @Aut0R3V (and close this one).

**Comment by sftim** [comment]
Also see issue #27515
