### ISSUE TITLE
Explain automatic field selection for "kubectl create configmap" via UTF-8 detection

### ISSUE THREAD

**Issue by schollii** [kubernetes/website#25921]
**This is a Bug Report**

**Problem:**

Binary data not shown in `kubectl describe configmap`

To reproduce: 
1. Create a config map from 2 files: one file is text, the other is a png. The text file will become a key in `data` field, whereas the png will become a key in `binaryData` field (this partially answers https://github.com/kubernetes/website/issues/20849).
Example: 
```
$ kubectl create cm test-bin --from-file vimrc=.vimrc --from-file binary.png=/var/lib/docker/.../screenshots/basic-usage-with-colors.png
configmap/test-bin created
$ kubectl get cm test-bin -o json | jq '.data | keys'
[
  "vimrc"
]
$ kubectl get cm test-bin -o json | jq '.binaryData | keys'
[
  "binary.png"
]
controlplane $ kubectl get cm test-bin -o json | jq '[.data, .binaryData] | keys'
```
2.  The `kubectl describe cm` only shows data, not `binaryData`:
```
$ kubectl describe cm test-bin
Name:         test-bin
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
vimrc:
----
set expandtab
...
set paste

Events:  <none>
$ 
```

**Proposed Solution:**

At very least, I could update the docs in https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object: 
- indicate that `describe` does not currently (as of 1.20) show `binaryData`
- clarify that configmap determines automatically which one to use (data or binaryData) based on whether the file is UTF-8 compatible (eg an ascii file that does not have the utf-8 marker would still go to data). 

I could also fix the `describe` command so it shows the `binaryData` section, at least with key names; as value, I could make it show the number of bytes for the value, as showing the actual bytes does not have much practical value.

**Page to Update:**

https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-object

1.20

**Comment by sftim** [comment]
What's actually going on behind the scenes is that Kubernetes definitely _does_ have a `binaryData` field in the API, but this details isn't reaching the output of `kubectl describe` because `binaryData` is an octet stream and kubectl has no idea how to print it.

If you want to have `kubectl` report the keys for binary data, you can file a feature request against [k/kubectl](https://github.com/kubernetes/kubectl/issues/new/choose).

For the

> clarify that configmap determines automatically which one to use (data or binaryData) based on whether the file is UTF-8 compatible (eg an ascii file that does not have the utf-8 marker would still go to data).

aspect of the issue:
/retitle Explain automatic field selection for "kubectl create configmap" via UTF-8 detection
/language en
/triage accepted
/sig cli
/kind feature

**Comment by schollii** [comment]
Thanks for the info. 

I submitted bug report https://github.com/kubernetes/kubectl/issues/997

For the retitle/triage, what's the process, is there another approval needed, or will someone somehow take this on, or should I?

**Comment by sftim** [comment]
I've accepted this issue, it's good to work on. Anyone can work on it.
/priority backlog

**Comment by schollii** [comment]
I looked at the contribution docs and could not see how to choose which branch to fork from.

**Comment by sftim** [comment]
No worries. As you already guessed @schollii: the merge base for your pull request, if working on this issue, is _master_.

**Comment by schollii** [comment]
/remove-lifecycle stale

Pretty sure I saw a PR about this

**Comment by sftim** [comment]
Was https://github.com/kubernetes/website/pull/25986 enough? I think this is good to close now.

**Comment by schollii** [comment]
Yes this issue can be closed
