### ISSUE TITLE
Set up a High Availability etcd cluster with kubeadm

### ISSUE THREAD

**Issue by roman-rs** [kubernetes/website#25923]
the document seems to be outdated.

Jan 03 08:38:02 k8-etcd1 kubelet[9699]: Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config
Jan 03 08:38:02 k8-etcd1 kubelet[9699]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kube

kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:07:13Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bl-ue** [comment]
@roman-rs random documents are that way.  Would you like to fix it yourself?

**Comment by bl-ue** [comment]
This is actually an issue with `kubectl`, but I'll link this issue in a PR on kubernete/kubernetes and it'll close this.
/assign

**Comment by bl-ue** [comment]
@roman-rs
Upon investigation, it looks like those links are broken because that's not the full warning message. The full message is:
```
This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```
Seems like your messages got cut off.
/close
