### ISSUE TITLE
Create static Pods

### ISSUE THREAD

**Issue by Leung83** [kubernetes/website#25926]
Hello I have a question on page:
https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

Create static pods Step 2
2. Choose a directory, say **/etc/kubelet.d** and place a web server Pod definition there, for example /etc/kubelet.d/static-web.yaml:

Shouldn't the default manifest path be used instead? 
**/etc/kubernetes/manifests/**

It's mentioned on these pages:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#constants-and-well-known-values-and-paths
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#init-workflow

**Comment by neolit123** [comment]
Its just and example. It can be any path as long as you configure it with
--pod-manifest-path (kubelet flag).

/etc/kubernetes is more of a kubeadm path.

/close
