### ISSUE TITLE
Inject Information into Pods Using a PodPreset

### ISSUE THREAD

**Issue by dkruyt** [kubernetes/website#25939]
The link to enable podpreset is broken eg 404

https://kubernetes.io/docs/concepts/workloads/pods/podpreset/#enable-pod-preset

**Comment by sftim** [comment]
Hi @dkruyt 

Kubernetes no longer has PodPresets (they never graduated from alpha). The way we serve the site, it's not easy to serve up a 410 Gone page to show what's been removed.

You could file a feature request to improve how we document removed features - otherwise, feel free to close this.
