### ISSUE TITLE
Document difference between "kind": "List" and concrete list types

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#25944]
**This is a Feature Request**

**What would you like to be added**
Explain how sometimes people see a list of items shown as, eg `kind: List`:
```json
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```
and other times as, eg, `PodList`:
```console
KIND:     PodList
VERSION:  v1

RESOURCE: items <[]Object>

DESCRIPTION:
     List of pods. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
```

**Why is this needed**
The two kinds of `kind` are liable to confuse people. Ideally, there would be several places in the Kubernetes documentation that highlight the differences and why they exist.
(it's also valid to change output, etc if any of these differences is actually down to a bug).

**Comments**
Related to https://github.com/kubernetes/kubectl/issues/984 and https://discuss.kubernetes.io/t/kind-list-what-is-it/5579

/sig api-machinery

**Comment by sftim** [comment]
Also relevant to https://github.com/kubernetes/kubectl/issues/837

**Comment by Aut0R3V** [comment]
I'd like to work on this.

**Comment by sobi3ch** [comment]
@Aut0R3V any progress? I get here after some search + reading about `kind: List`. Resolving this issue will be good for many people.

**Comment by eddiezane** [comment]
/sig cli
/remove-sig api-machinery
/triage accepted

This was discussed at a sig api-machinery call.

[Recording timestamp](https://youtu.be/saifLI8MAi8?t=338).

The TLDW: This is a convenience type used by kubectl for lists of mixed types. API Server won't send this type.

We could document that but where would it make sense?

**Comment by sftim** [comment]
> We could document that but where would it make sense?

https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/ ?
https://kubernetes.io/docs/concepts/overview/working-with-objects/ (erm, needs writing! - but a good place for it)

We could migrate https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/ to https://kubernetes.io/docs/concepts/overview/working-with-objects/ and mention that `kind: List` is a client-side convenience detail.

**Comment by sftim** [comment]
**note** that https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/ is generated content, so we'd need to find a way to add the note into the generator somehow. Not straightforward. But possible.

**Comment by chrisnegus** [comment]
I've been playing with `kind: List` and kind: `????List` over the past few days. I agree that the best place to document them is with kubectl. Specifically, I think `kubectl apply` and `kubectl delete` are most useful ways of using lists. I try adding a short section after "Creating objects" on the Kubectl Cheat Sheet called "Creating objects from Lists". Then I'll have short examples descriptions of those two types of lists. Unless I hear objections, I'll have a PR for you shortly and we can work from there.

**Comment by sftim** [comment]
The Kubernetes API uses lists too. The difference is that in the API, each list is served as its concrete type such as `PodList`.

Many Kubernetes components and clients use lists, not just `kubectl.`

Not sure what this means? I can explain further.

**Comment by sftim** [comment]
Also, the cheat sheet doesn't feel like the right place to mention this quite subtle distinction.

**Comment by chrisnegus** [comment]
Okay. I'll look for another place to put content that wouldn't be just example oriented. I'd be glad to hear if you have a suggestion for a good place to put this content.

**Comment by chrisnegus** [comment]
I went ahead and took a shot at a PR on this: [PR 28608](https://github.com/kubernetes/website/pull/28608). I'd be glad to consider other or additional ways to go about this. I also opened a different one the other day ([PR 28490](https://github.com/kubernetes/website/issues/28490)) to fix some incorrect list output, which I think was causing some confusion.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/24882

**Comment by chrisnegus** [comment]
For anyone interested, we believe that [PR #28608](https://github.com/kubernetes/website/pull/28608), which addresses this issue, is ready for technical review.

**Comment by chrisnegus** [comment]
@sftim Since [PR #28608](https://github.com/kubernetes/website/pull/28608) has been merged, I think we can close this Issue.

**Comment by chrisnegus** [comment]
On second thought, I'm going to do a small PR against the [api-conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds) page to note this issue. Descriptions of PodList and many others in the API point to that page.

**Comment by sftim** [comment]
Happy to close this
/close
