### ISSUE TITLE
Nitpick: unclear that .spec.type = Loadbalancer works locally

### ISSUE THREAD

**Issue by tavor** [kubernetes/website#25947]
Went through https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer. 

That `.spec.type = LoadBalancer` can be used locally wasn't clear.

**Comment by sftim** [comment]
“Locally”? I'm not sure what you mean there @tavor.

/triage needs-information

**Comment by tavor** [comment]
I realized this is a Docker Desktop specific feature. Closing
