### ISSUE TITLE
Operating etcd clusters for Kubernetes

### ISSUE THREAD

**Issue by CyberGremlin** [kubernetes/website#25957]
These instructions on this page are incorrect and will not work:

**ETCDCTL_API=3 etcdctl --endpoints $ENDPOINT snapshot save snapshotdb**

Instead the cacert, cert and key, also need inputing, eg:

ETCDCTL_API=3 etcdctl --endpoints=$ENDPOINT --cacert=/etc/kubernetes/pki/etcd/ca.crt \
     --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key \
     snapshot save /usr/backup/backup.db

**Comment by sftim** [comment]
It sounds like this is a request to update the page at https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/
/language en

**Comment by sftim** [comment]
You can find in-depth information about etcd in the [official documentation](https://etcd.io/docs/).

You don't necessarily need to supply those details on the command line; for example you might have
`ETCDCTL_CACERT` etc set. Maybe we could explain that or link to a page that tells you more about it.
