### ISSUE TITLE
Install Service Catalog using Helm end in a HTTP-403 response

### ISSUE THREAD

**Issue by freegroup** [kubernetes/website#25959]
Unable to add chart repo via 
```
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com
```

call ends in `403` forbidden.

```
looks like "https://svc-catalog-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://svc-catalog-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

**Comment by freegroup** [comment]
it seems that the URL ini your documentation is outdated. the URL should be
https://kubernetes-sigs.github.io/service-catalog/

**Comment by sftim** [comment]
Is there a page you're following @freegroup? I can't see that you have mentioned its URL.

/triage needs-information
/language en

**Comment by freegroup** [comment]
https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/

best regards

**Comment by freegroup** [comment]
It seems that the Serivce catalog is not a frequently installed component when this error was noticed only by me and has not received any attention since then.
