### ISSUE TITLE
Remove WIP and personal branches from official repository

### ISSUE THREAD

**Issue by kad** [kubernetes/website#2595]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
kubernetes/kubernetes.github.io repository contains obsolete/WIP/other unofficial branches.
Good practices with github repositories is to use personal forks for all WIP changes.

**Proposed Solution:**
Remove all branches except master and release-*.

**Page to Update:**
https://github.com/kubernetes/kubernetes.github.io/branches

**Comment by DanyC97** [comment]
@nikhita @jimangel @zacharysarah anyone of you able to delete the merged branches https://github.com/kubernetes/website/branches/all ? thank you

**Comment by nikhita** [comment]
> anyone of you able to delete the merged branches https://github.com/kubernetes/website/branches/all ?

I can, but will leave it to either @zacharysarah or @jimangel to do it since they are more familiar with the website repo. :)

**Comment by zacharysarah** [comment]
I've deleted some. When https://github.com/kubernetes/test-infra/pull/11984 merges, we can delete more. 😄

**Comment by zacharysarah** [comment]
Whether we remove `dev-*` branches is an open question, but all personal and WIP branches are now removed. https://github.com/kubernetes/website/branches/all

/close

**Comment by nikhita** [comment]
@DanyC97 Thanks for circling back on this btw :)
