### ISSUE TITLE
Document kubeadm for RHEL 8

### ISSUE THREAD

**Issue by quindar83** [kubernetes/website#25967]
**This is a Feature Request**

**What would you like to be added**
The site '[Installing kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/)' does not list RHEL 8 or CentOS 8 as a supported os. Only RHEL 7 / CentOS 7 is listed.
Both os versions released over a year ago and Google provides a lot of guides for how to install Kubernetes on CentOS 8. 

Please
a)  add RHEL 8 / CentOS 8 to the list of supported platforms
or
b) if there is a reason for this, explain it on the website.
 
**Why is this needed**
It is confusing when only an old os version ist supported without any further explanation.

**Comments**

**Comment by neolit123** [comment]
it's a matter of users testing and confirming these distros work fine.
if you have tested them feel free to send a pull request to update.

/sig cluster-lifecycle
/help

**Comment by ydFu** [comment]
@quindar83 
I had a look at it and sent in a pull request for this.
Add forward compatibility in RHEL / CentOS to the list of supported platforms.
