### ISSUE TITLE
通过文件将 Pod 信息呈现给容器

### ISSUE THREAD

**Issue by chenxin6** [kubernetes/website#25960]
the file labels and annotations should be in the directory /etc/podinfo not /etc
![image](https://user-images.githubusercontent.com/40751203/103647724-b547c380-4f96-11eb-975b-90bbd097789f.png)

**Comment by sftim** [comment]
Hi @chenxin6 

What's the URL of the web page that isn't right?

/triage needs-information

**Comment by chenxin6** [comment]
https://kubernetes.io/zh/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/
