### ISSUE TITLE
Issue with k8s.io/docs/setup/

### ISSUE THREAD

**Issue by j3pic** [kubernetes/website#25974]
I'm trying to find out how to set up a production environment for Kubernetes, but all the documentation wants to talk about is third-party providers. How do you actually install and run Kubernetes on a cluster?

**Comment by sftim** [comment]
Hi @j3pic 

Did you find https://kubernetes.io/docs/setup/production-environment/tools/ ?

It sounds like it would help to reword https://kubernetes.io/docs/setup/ and suppress the automatic index there, in favor of some more specific text.

Not tagging this as SIG Cluster Lifecycle, but that's roughly the right area.
/language en

**Comment by j3pic** [comment]
> Did you find https://kubernetes.io/docs/setup/production-environment/tools/ ?

I did now that you pointed it out to me. Thanks.

**Comment by chrisnegus** [comment]
@j3pic We created new content on the https://kubernetes.io/docs/setup/production-environment/ page, which used to just consist of a handful of links. There was a rather thorough review process that you can see in this [PR](https://github.com/kubernetes/website/pull/27466). Could you please review the content and see if it meets the need you are looking for in this issue?

**Comment by j3pic** [comment]
It looks detailed, but I won't be able to know if it would have met my needs unless I run into those needs again. This time around I resorted to using a third-party solution, since I saw no other option at the time.

**Comment by sftim** [comment]
@j3pic would you be happy to close this? We're very open to more feedback if you have it in the future.

**Comment by jimangel** [comment]
/close
@j3pic feel free to open a new issue if you have additional feedback! Thanks for starting this initiative!
