### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-service-account/

### ISSUE THREAD

**Issue by CTownsdin** [kubernetes/website#25981]
There is a section called "multiple service accounts".
There is no example yaml showcasing how to use multiple service accounts in one deployment.yaml.
Should that be added?

**Comment by Aut0R3V** [comment]
@CTownsdin can you please put in a link to the document you're referring to? I could find this particular documentation : https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
But it has the required information I feel.
