### ISSUE TITLE
Vague wording in “Use a Service to Access an Application in a Cluster”

### ISSUE THREAD

**Issue by Desync-o-tron** [kubernetes/website#26002]
Step 8. is vague.

> "On your chosen node, create a firewall rule that allows TCP traffic on your node port. For example, if your Service has a NodePort value of 31568, create a firewall rule that allows TCP traffic on port 31568. Different cloud providers offer different ways of configuring firewall rules."

I'm not sure what firewall is being referred to here.

**Comment by sftim** [comment]
/retitle Vague working in “Use a Service to Access an Application in a Cluster”

/sig network
/language en

(I think this is describing host-based or instance-level packet filtering; there are several different technologies that could be applicable).

**Comment by sftim** [comment]
Oops
/retitle Vague wording in “Use a Service to Access an Application in a Cluster”
