### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by dcaponi** [kubernetes/website#26019]
It would be pretty cool to have the diagrams from the introductory page on the same page as the hands-on tutorial itself so I have something to refer back to and connect with the steps in the tutorial 😄

**Comment by sftim** [comment]
/kind feature
/priority backlog
/language en
(and then copy this to the other localizations downstream once merged)

@dcaponi do you think you could sketch how you'd like this to look? (“No” or “Not really” is a valid answer! - but if you can, that would help make sure we're clear on a way forward)
