### ISSUE TITLE
Add names of OWNERS to OWNERS file

### ISSUE THREAD

**Issue by Aut0R3V** [kubernetes/website#26015]
**This is a Feature Request**

**What would you like to be added**

I think that the OWNERS section in the website can be edited and some more details can be added. 
**Why is this needed**

 Although a link was put in through #12427, I feel like some more changes might be needed here. These changes would be adding names of the owners.
**Comments**

I'll send in a PR once a member feels like it is important for this issue to be worked upon.

**Comment by sftim** [comment]
@Aut0R3V, I don't think I understand the issue you're reporting.

Would you be willing to revise the issue description so that any shortcoming is described? If you're suggesting an improvement, please detail what change you would like to see and why.

/triage needs-information

**Comment by Aut0R3V** [comment]
> @Aut0R3V, I don't think I understand the issue you're reporting.
> 
> Would you be willing to revise the issue description so that any shortcoming is described? If you're suggesting an improvement, please detail what change you would like to see and why.
> 
> /triage needs-information

Done

**Comment by sftim** [comment]
/retitle Add names of OWNERS to OWNERS file

/kind feature
/priority awaiting-more-evidence

Across the Kubernetes project, I believe that the convention is not to list people's names (and, in fact, if someone doesn't want to disclose their name via GitHub APIs etc, that's OK).

**Comment by Aut0R3V** [comment]
Oh apologies I wasn't aware of that. Should I close this down?
