### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by shameersheik** [kubernetes/website#26024]
Seems most ubuntu new kubernetes users come across this issue 

(https://github.com/justmeandopensource/kubernetes/issues/4)

My Solution that worked is :

sudo sudo kubeadm init
mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
kubectl cluster-info

this being in the page would help save a lot of time

**Comment by neolit123** [comment]
the output of the `kubeadm init` command prints this instruction already.

/close
