### ISSUE TITLE
Using Admission Controllers - missing API group/version referred in MutatingAdmissionWebhook and ValidatingAdmissionWebhook sections

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#26036]
In the [MutatingAdmissionWebhook ](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook) and [ValidatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook) sections it is mentioned that, in case these admissions controllers are not enabled, the related MutatingWebhookConfiguration and ValidatingWebhookConfiguration resources in admissionregistration.k8s.io/v1beta1 group/version must be also disabled in kube-apiserver via the --runtime-config flag.

From 1.16 these two built-in resources exist also in stable group/version admissionregistration.k8s.io/v1, so it should be mentioned they must be disabled for both API group/versions (i.e. admissionregistration.k8s.io/v1beta1 & admissionregistration.k8s.io/v1).

**Comment by sftim** [comment]
I think the advice should be to disable the relevant stable resources, and possibly to disable the equivalent beta APIs as as well.

Since these are enabled by default, another approach could be to create a Task page about how to disable admission webhooks, and have https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/ hyperlink there.

/language en
/sig auth

**Comment by liggitt** [comment]
The beta admissionregistration APIs will no longer be served in 1.22... I'd suggest leaving the doc as-is so it ages well.

It's doesn't actually harm anything for the registration APIs to be available when the admission plugins are disabled, the created objects are just inert.

/close

**Comment by antaloala** [comment]
@liggitt, @sftim when I created this issue the doc was only referring to ´´´admissionregistration.k8s.io/v1beta1´´´ (you can see it if reading [1.19 documentation](https://v1-19.docs.kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook)).
It looks some documentation update solved this in 1.20 (I just checked lastest accesible 1.20 and 1.21 refer now to ´´´admissionregistration.k8s.io/v1´´´) so solving this issue ... without I realized on that.
Anyway it is now all solved (I fully agree with @liggitt reasoning, not making sense to refer to v1beta1 as being deprecated in 1.21).
Thanks anyway to both for taking care of this issue ;-)
