### ISSUE TITLE
Configure Liveness, Readiness and Startup Probes

### ISSUE THREAD

**Issue by atul-mindmatch** [kubernetes/website#26052]
When implementing **Liveness probe**, getting error 
**ERROR:** invalid value for Integer(): "touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600".
Unable to figure out what's causing this. 
Please suggest.

**Comment by sftim** [comment]
/kind support

I think the page is correct - please reply if that's not the case.

**Comment by celestehorgan** [comment]
Hi @atul-mindmatch,

You haven't returned to this issue. Is it okay if we close this?
