### ISSUE TITLE
Set up a High Availability etcd cluster with kubeadm

### ISSUE THREAD

**Issue by syl-163** [kubernetes/website#26078]
[root@ks-3 hpa]# docker run --rm -it --net host -v /etc/kubernetes:/etc/kubernetes k8s.gcr.io/etcd:3.4.3-0 etcdctl --cert /etc/kubernetes/pki/etcd/peer.crt --key /etc/kubernetes/pki/etcd/peer.key --cacert /etc/kubernetes/pki/etcd/ca.crt --endpoints https://192.168.0.110:2379 endpoint health --cluster
{"level":"warn","ts":"2021-01-13T14:12:31.551Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-a22a1f43-7511-4a0f-9165-3f0a536f550d/192.168.0.110:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 192.168.0.110:2379: connect: connection refused\""}
Error: failed to fetch endpoints from etcd cluster member list: context deadline exceeded

**Comment by neolit123** [comment]
please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
