### ISSUE TITLE
K8s 1.21 - Formalize the Docs release strategy with the different localization owners

### ISSUE THREAD

**Issue by reylejano** [kubernetes/website#26084]
Hello 👋,

I'm Rey Lejano, the SIG Release Docs lead for the 1.21 release. I'm opening this issue to find the best way to coordinate the actual docs release (scheduled tentatively for April 8, 2021) with the different localization owners.

A couple of questions:

1. Who would be a good primary contact for the following localization content?

- [ ] Arabic
- [ ] Belarusian
- [x] French (@remyleone)
- [ ] German
- [ ] Hindi
- [x] Indonesian (@girikuncoro)
- [x] Italian (@fabriziopandini)
- [x] Japanese (@inductor)
- [x] Korean (@seokho-son)
- [ ] Mandarin
- [ ] Persian
- [x] Polish (@mfilocha)
- [x] Portuguese (@rikatz)
- [ ] Russian
- [x] Spanish (@raelga)
- [ ] Vietnamese
- [x] Ukrainian (@MaxymVlasov)

2. Is there anything we could have done better in the last release (v.1.20)? Do you have any process improvements in mind?

I look forward to working with everyone! Let me know if you have any questions!
Thank you! 🙏

cc: @kubernetes/sig-docs-fr-owners @kubernetes/sig-docs-de-owners @kubernetes/sig-docs-hi-owners @kubernetes/sig-docs-id-owners @kubernetes/sig-docs-ja-owners @kubernetes/sig-docs-ru-owners @kubernetes/sig-docs-pl-owners @kubernetes/sig-docs-ko-owners @kubernetes/sig-docs-pt-owners @kubernetes/sig-docs-es-owners @kubernetes/sig-docs-zh-owners @kubernetes/sig-docs-vi-owners @kubernetes/sig-docs-uk-owners @kubernetes/sig-docs-it-owners @kubernetes/sig-docs-ar-owners @kubernetes/sig-docs-fa-owners @kubernetes/sig-docs-be-owners

/assign
/sig release

**Comment by seokho-son** [comment]
Hello @reylejano  
I can be a primary contact for Korean l10n contents. (Currently, I am leading Korean 10n team)

**Comment by remyleone** [comment]
Hello,
I can be a primary contact for French content

**Comment by fabriziopandini** [comment]
I can be the primary contact for Italian

**Comment by girikuncoro** [comment]
I can be primary contact for Bahasa Indonesia

**Comment by mfilocha** [comment]
I'm for Polish localization.

**Comment by raelga** [comment]
@raelga for Spansih :D

**Comment by MaxymVlasov** [comment]
Hi
Count on me in Ukrainian localization

**Comment by shu-mutou** [comment]
Ref: #25806

**Comment by inductor** [comment]
Hello from Japanese localisation team

**Comment by reylejano** [comment]
Hi @inductor @MaxymVlasov @raelga @mfilocha @girikuncoro @fabriziopandini @remyleone @seokho-son and other localization leads, I wanted to let you know that we are on track for the 1.21 release on April 8, 2021. Next week, we will create the `release-1.20` branch, freeze the `k/website` repo on April 7, and unfreeze the `k/website` repo on the release day on April 8. I'll reach out again next week.

**Comment by reylejano** [comment]
Hi @inductor @MaxymVlasov @raelga @mfilocha @girikuncoro @fabriziopandini @remyleone @seokho-son and other localization leads. We are still on track for the 1.21 release on April 8, 2021. We will freeze the k/website repo on April 7. Here are additional steps that the release docs team will conduct for the release:

April 7 (day before release)
- Update Netlify (assistance from a SIG Docs chair)
- Create release-1.20 release branch
- Freeze the k/website repo
- Merge master branch into the dev-1.21 branch

April 8 (release day)
- Merge integration branch
- Publish the release blog post
- Create release with tag
- Unfreeze the k/website repo
- Finish generating reference docs
- Close the 1.21 milestone

**Comment by rikatz** [comment]
@reylejano you can assign me for the Portuguese localization

**Comment by reylejano** [comment]
Hi @inductor @MaxymVlasov @raelga @mfilocha @girikuncoro @fabriziopandini @remyleone @seokho-son @rikatz and other localization leads. 
1.21.0 has been released, the k/website 1.21 Integration Branch has merged and the 1.21 release blog is live.
The k/website repo is no longer frozen
Thank you all for your contributions
Closing issue
