### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

### ISSUE THREAD

**Issue by ganeshsagani** [kubernetes/website#26080]
For the beginners please  give a hint to get required data.....
For example: 
kubectl config --kubeconfig=config-demo set-cluster development --server=https://1.2.3.4 --certificate-authority=fake-ca-file
in above command execution where can get exactle "--server" detail and "--certificate-authority" details...

**Comment by Kartik494** [comment]
Hi @ganeshsagani details are given for this in defining [cluster](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts) , more information regarding --server and --certificate-authority you could find in `kubeconfig` file
