### ISSUE TITLE
Update structure of the "Install and Set Up kubectl" page to use tabs for the different Operating Systems described

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#26096]
**This is a Feature Request**

**What would you like to be added**

Update structure of the "[Install and Set Up kubectl](https://kubernetes.io/docs/tasks/tools/install-kubectl/)" page to use tabs to contain the install instructions of the different operating systems.

**Why is this needed**
This may help to shorten the page, and give people an opportunity to get directly to what they are looking for without a lot of scrolling.

This change may also help to de-duplicate some of the instructions being presented.

**Comments**

This suggestion comes out of the discussions around the _[Updating install-kubectl.md with instructions for validating kubectl binaries against checksum files](https://github.com/kubernetes/website/pull/25259)_ PR.
- https://github.com/kubernetes/website/pull/25259#issuecomment-735020297
- https://github.com/kubernetes/website/pull/25259#issuecomment-747066493
- https://github.com/kubernetes/website/pull/25259#pullrequestreview-554120404
- https://github.com/kubernetes/website/pull/25259#discussion_r546057027

**Comment by nate-double-u** [comment]
As per @sftim's [suggestion](https://github.com/kubernetes/website/pull/25259#pullrequestreview-554120404), as we go through this issue we may find we want to open another feature request to sync the tabs across the page so that a visitor only need make the OS selection once.

**Comment by sftim** [comment]
/triage accepted
/kind feature
/language en

And, because it's a popular page, but the existing documentation does work:
/priority important-longterm

**Comment by tomkivlin** [comment]
I would like to work on this, like the idea.

/assign
