### ISSUE TITLE
Simplify Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by iiian** [kubernetes/website#26105]
This tutorial is too complex to be delivered in a tiny little Katakoda window, you guys should simplify it when you get the chance

**Comment by sftim** [comment]
/retitle Simplify Interactive Tutorial - Configuring a Java Microservice
/kind feature
/language en

I think you're also able to follow this tutorial on your own cluster.
/priority awaiting-more-evidence
