### ISSUE TITLE
Horizontal Pod Autoscaler

### ISSUE THREAD

**Issue by natereid72** [kubernetes/website#26102]
Seems it would be better to use 'scaled out' and 'scaled in' in reference to HPA.

**Comment by Kartik494** [comment]
@natereid72 Just for confirmation are you asking for scaled up and scaled down for HPA , i couldn't find any policies related to scaled out in [docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-configurable-scaling-behavior)

**Comment by natereid72** [comment]
It's a semantics thought. The catch is that the actual policy setting for HPA is scale up/down. So in docs, it should match and it does as it is. Horizontal scaling in nature is an in/out pattern. Vertical scaling is up/down. but as the project is currently written with up/down for HPA, in retrospect, I think changing the docs to in/out would be confusing.

**Comment by celestehorgan** [comment]
@natereid72 It seems like you don't think this issue is valid anymore. Is that correct? If so, I'd like to close it.

**Comment by natereid72** [comment]
Sorry, yes, ok with me.

Sent from ProtonMail mobile

-------- Original Message --------
