### ISSUE TITLE
Proposal for Member Tag

### ISSUE THREAD

**Issue by Aut0R3V** [kubernetes/website#26116]
I've been contributing through various means - setting up PR's, interacting in issues and reviewing pull requests. Recently, I have  been a part of sig-security discussions. Furthermore, I am planning to contribute towards two projects in the upcoming weeks. These are translation of documents to Hindi and the sig-security documentation. It would be great if the community considers this proposal.

**Comment by Aut0R3V** [comment]
@tengqm 
 @sftim

**Comment by tengqm** [comment]
+1

**Comment by tengqm** [comment]
@Aut0R3V You may want to join the kubernetes org first. https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-member

**Comment by Aut0R3V** [comment]
Oh apologies, I'll put in a request there.  Closing this issue for now.
