### ISSUE TITLE
Issue with create serviceaccount rest operation

### ISSUE THREAD

**Issue by mrandhikpurwala** [kubernetes/website#2611]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
We are using the rest api for creating a service account. It creates an account even if a namespace doesnt exists.

URL - /api/v1/namespaces/defaults/serviceaccounts/yesss

We have seen this behavior with several create operation. Not sure if its an expected behaviour.

**Proposed Solution:**
Even if it creates an service account the response should indicate that the namespace provided didn't exists or the request should fail. 

**Page to Update:**
https://kubernetes.io/docs/api-reference/v1/operations/

kubectl version 1.4

**Comment by tengqm** [comment]
This smells more like an implementation/validation issue. Even the inaccurate documentation itself was generated from the upstream source code. Please raise an issue in kubernetes/kubernetes project.
