### ISSUE TITLE
Certificate Signing Requests documentation for signerName needs to explain application in-cluster TLS usage model

### ISSUE THREAD

**Issue by jimlindeman** [kubernetes/website#26111]
Each time I read through https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers, the first 3 values seem to be only for kubernetes infrastructure (kubelets and for callers to the kube api server).  What about for applications that want to do TLS between each other using the internal service-urls, like https://service-name.namespace ?   Currently, in our applications running on K8s 1.17 and before, we're able to give our application startup code logic to create a CSR using the service-url and approve it (the mounted apikey has the role to approve the CSRs).  The K8s infrastructure would then create the certs in the CSRs and applications would use that to configure their https-listening.  But from the documentation, I can't figure out which value we should use to maintain doing this in K8s 1.18+.

**Comment by jimlindeman** [comment]
We have found that what works is to re-use the 'kubernetes.io/kublet-serving' value for the signerName, and adjusting the CSR to then have kubelet-compatible values like:
```
   csr.setSubject([
      {
        name: 'commonName',
        value: `system:node:${serviceName}.${namespace}.svc.cluster.local`
      },
      {
        name: 'organizationName',
        value: 'system:nodes'
      },
      ...
```
and in the extensions:
```
           {
            name: 'subjectAltName',
            altNames: [
              {
                // type 2 is DNS
                type: 2,
                value: `${serviceName}.${namespace}`
              },              },
              {
                type: 2,
                value: `${serviceName}.${namespace}.svc.cluster.local`
              }
            ]
          }
```

Our application development team prefers this approach to a separate certificate-signer because it enables our applications to use the existing automounted ca.csr to validate peer traffic without having to setup an additional mount & ca.crt file.

**Comment by liggitt** [comment]
> What about for applications that want to do TLS between each other using the internal service-urls, like https://service-name.namespace ?

That use is not yet supported by built-in Kubernetes signers, but is requested at https://github.com/kubernetes/kubernetes/issues/63732

/close
