### ISSUE TITLE
Enhancing the Kubernetes guide in Hindi

### ISSUE THREAD

**Issue by Aut0R3V** [kubernetes/website#26112]
**This is a Feature Request**

**What would you like to be added**

The Hindi translation of the document needs some work. 

**Why is this needed**

Useful for contributors comfortable in working with a workflow involving content written in Hindi.

**Comments**

I went through the initial issues that were focused on improving the documentation, but some more work can be done for making the documentation better.

**Comment by Aut0R3V** [comment]
@Rajakavitha1
@nikhita 
It would be nice if you guys could pitch in your suggestions for the work done here :)

**Comment by nikhita** [comment]
/language hi

> The Hindi translation of the document needs some work.

@Aut0R3V can you add links to which document you are referring to here?

>  It would be nice if you guys could pitch in your suggestions for the work done here :)

I am not that comfortable with formal Hindi so I won't be able to contribute or review PRs. I'm also not sure if we have enough contributors or reviewers to help with Hindi localization...

@mittalyashu do you have enough bandwidth to localize all the outstanding work items in https://github.com/kubernetes/website/issues/13957 with @Aut0R3V?

**Comment by Aut0R3V** [comment]
Hey
I'll send in some PR's soon. Meanwhile I wanted to discuss - I had a look at  #13957 and looks like there's a lot of work that needs to be done. Should I simply select topics and go ahead with the translation work? Or would you recommend any specific workflow here? 
By workflow I mean - going through particular topics and completing the translation for that specific topic first.
For instance - first the translation for architecture and all the related content can be done and then a new topic can be chosen. 

Meanwhile if these members could also update about their availability, it would be great!
@Rajakavitha1
@daminisatya
@mittalyashu
@avidLearnerInProgress

**Comment by nikhita** [comment]
@Aut0R3V firstly, thank you for taking this up! :raised_hands: 

>  Or would you recommend any specific workflow here?

@irvifa @jimangel :wave: do you have suggestions for how to proceed with localization?

**Comment by irvifa** [comment]
We have several example of how localization for each language works. For example this conversation here in slack show how Korean team works for the [localization](https://kubernetes.slack.com/archives/C0191RDKHU1/p1604389887061900?thread_ts=1604374229.061800&channel=C0191RDKHU1&message_ts=1604389887.061900).

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue
