### ISSUE TITLE
Runtime Class

### ISSUE THREAD

**Issue by kaganmersin** [kubernetes/website#26125]
Hello,

In the kubernetes documentation with the given URL in below . It had been  written apiVersion: node.k8s.io/v1 for runtimeclass kind object. It should be  apiVersion: node.k8s.io/v1beta1 or  apiVersion: node.k8s.io/v1alpha1.  Can you check that 

URL: https://kubernetes.io/docs/concepts/containers/runtime-class/#2-create-the-corresponding-runtimeclass-resources

I am facing below error while using information that including official Kubernetes pages:
`no matches for kind "RuntimeClass" in version "node.k8s.io/v1"
`

**Comment by tengqm** [comment]
@kaganmersin The RuntimeClass resource graduated from Beta to GA in 1.20. If you are running a cluster 1.19 or earlier version, please check the documentation of that specific version. The master/main branch you are seeing is for 1.20.
/close
