### ISSUE TITLE
Improvements to the new v2 CronJob Controller

### ISSUE THREAD

**Issue by salva-gglez** [kubernetes/website#26124]
Hello, 

   There is a new v2 CronJob Controller that changes cronjobs behavior. We need to know if this new behaviour affects propertie `startingDeadlineSeconds`.

   It will be also great to know what are the new experimental performance improvements implemented.

   This issue it's related to Issue #25425

**Comment by sftim** [comment]
/triage accepted

The follow-on work as mentioned in PR #25425 is to make sure that any warnings about `startingDeadlineSeconds` make sense to readers who are trying the v2 controller.
