### ISSUE TITLE
Events in Stackdriver page - is outdated and third-party specific (Google)

### ISSUE THREAD

**Issue by bpaduch** [kubernetes/website#26136]
This page: https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver/ should be removed. Why?

- Out-dated information - screenshots are old, product name is old
- It's specific to a third-party, namely Google, and K8s docs should be agnostic.

**Comment by kbhawkey** [comment]
Related to PR #24769.

**Comment by sftim** [comment]
Ah no, #24769 is a PR.
/remove-triage duplicate

**Comment by sftim** [comment]
Part of issue #20232

/triage accepted

**Comment by kbhawkey** [comment]
PR #24769 has merged.
This issue can close. If there are additional questions, feel free to reopen this issue.
/close
