### ISSUE TITLE
Auditing

### ISSUE THREAD

**Issue by ABHISHARMAV** [kubernetes/website#26135]
I am facing issue, when deploying audit-profile.yaml
->kubectl version
Client Version: v1.17.0
Server Version:v1.16.15-gke
audit-profile.yaml:-
apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["pods"]
  - level: Metadata
    resources:
    - group: ""
      resources: ["pods/log", "pods/status"]
  - level: None
    resources:
    - group: ""
      resources: ["configmaps"]
      resourceNames: ["controller-leader"]
  - level: None
    users: ["system:kube-proxy"]
    verbs: ["watch"]
    resources:
    - group: "" # core API group
      resources: ["endpoints", "services"]

  - level: None
    userGroups: ["system:authenticated"]
    nonResourceURLs:
    - "/api*" # Wildcard matching.
    - "/version"

  - level: Request
    resources:
    - group: "" # core API group
      resources: ["configmaps"]
    namespaces: ["kube-system"]
  - level: Metadata
    resources:
    - group: "" # core API group
      resources: ["secrets", "configmaps"]

  - level: Request
    resources:
    - group: "" # core API group
    - group: "extensions" # Version of group should NOT be included.
  - level: Metadata
    omitStages:
      - "RequestReceived"

Issue: error: unable to recognize "audit-profile.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1"

After that I tried with audit.k8s.io/v1beta1 this version also but getting same issue, any one can help me for this issue.

Thank you...

**Comment by sftim** [comment]
Hi @ABHISHARMAV 

Can you confirm what version of Kubernetes you are using, and which web page inside https://kubernetes.io/ seems to need a tweak?

/triage needs-information
/language en

**Comment by sftim** [comment]
It's been a while with no update
/close
