### ISSUE TITLE
Doc assumes TLS termination at ingress endpoint but we can use passthrough

### ISSUE THREAD

**Issue by scoulomb** [kubernetes/website#26137]
**Problem**

[Ingress-nginx](https://kubernetes.io/docs/concepts/services-networking/ingress/#prerequisites) is an officially supported Ingress by Kubernetes

From here: https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/
> Kubernetes as a project supports and maintains AWS, GCE, and nginx ingress controller

Minikube uses Nginx Ingress controller by default
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#enable-the-ingress-controller

But it seems there is a contradiction in the doc related to SSL passthrough:

From here: https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
> You can secure an Ingress by specifying a Secret that contains a TLS private key and certificate. The Ingress resource only supports a single TLS port, 443, and **assumes TLS termination at the ingress point (traffic to the Service and its Pods is in plaintext).**

Whereas Nginx ingress (and others) offer SSL passthrough feature
From here https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#ssl-passthrough
> The annotation nginx.ingress.kubernetes.io/ssl-passthrough instructs the controller to send TLS connections directly to the backend instead of letting NGINX decrypt the communication. 

and https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough
> The `--enable-ssl-passthrough` flag enables the SSL Passthrough feature, which is disabled by default. This is required to enable passthrough backends in Ingress objects.

Is it a misunderstanding on my side? 

Or should we mention we can activate SSL passthrough feature, which is usually not activated by default? 

**Proposed Solution**

I propose to mention we can use passthrough termination in some ingress controller. Thus update this section:
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

**Some related links**

<details>
  <summary>Click to expand!</summary>

- https://docs.giantswarm.io/guides/advanced-ingress-configuration/#terminating-tls-in-ingress-controller
Passthrough does nor have tls.crt and tls.key!
-  https://avinetworks.com/glossary/ssl-passthrough/ : 
> SSL passthrough is the action of passing data through a load balancer to a server without decrypting it"
-  Similar to OpenShift route passthrough: https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#secured-routes
> With passthrough termination, encrypted traffic is sent straight to the destination without the router providing TLS termination. Therefore no key or certificate is required.

</details>

**Comment by sftim** [comment]
/sig network

@kubernetes/sig-network-misc what's the right thing to document here about the Ingress API in general? It sounds like the NGINX Ingress controller might do something a bit nonstandard with TLS, matching on the SNI details in the TLS session and _not_ following the typical mechanisms for Ingress and its `.spec.rules` field.
