### ISSUE TITLE
Deprecation warning on https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26156]
**This is a Bug Report**

**Problem:**
[Turnkey Cloud Solutions](https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/) lists Kubernetes certified solution providers. However, a warning appears:

> :warning: URL deprecated: https://landscape.cncf.io/category=certified-kubernetes-hosted&format=card-mode&grouping=category&embed=yes

**Proposed Solution:**
Investigate and find a non-deprecated Landscape URL. Alternatively, revise the page further.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/

**Additional Information:**
/language en
/kind bug
/priority important-soon

**Comment by sladyn98** [comment]
@sftim I heard this might not be beginner friendly... but I could take a stab at it and learn along the way :) 
My question would be how do I find a non depricated landscape URL

**Comment by jordinl83** [comment]
@sftim We've changed the routing on the landscape. The new URL should be https://landscape.cncf.io/card-mode?category=certified-kubernetes-hosted&grouping=category&embed=yes

**Comment by sftim** [comment]
@sladyn98 _-or anyone else-_ please feel free to revised based on the advice in https://github.com/kubernetes/website/issues/26156#issuecomment-766858941

**Comment by jordinl83** [comment]
@sftim I'll update the URLs

**Comment by sftim** [comment]
/close
Thanks @jordinl83 !
