### ISSUE TITLE
“Hello Minikube” tutorial runs dashboard subcommand in foreground

### ISSUE THREAD

**Issue by ksvanhorn** [kubernetes/website#26150]
After issuing the command "minikube dashboard" in the "Create a minikube cluster" section, I never get the command prompt back. How, then, am I supposed to issue the commands listed in the following section, "Create a deployment"?

**Comment by sftim** [comment]
/retitle “Hello Minikube” tutorial runs dashboard subcommand in foreground
/kind bug
/triage accepted

That's a good point. The tutorial doesn't explain what to do here.

/priority important-longterm
/language en

**Comment by CKchen0726** [comment]
![image](https://user-images.githubusercontent.com/47560998/105138804-5eaebd80-5b30-11eb-9abc-b4608d5d17ba.png)
