### ISSUE TITLE
使用 kubeadm 创建集群

### ISSUE THREAD

**Issue by springcomefromprogrammingtheworld** [kubernetes/website#26167]
an 20 17:42:25 master-node kubelet[14525]: I0120 17:42:25.081503   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 9ef29ff96c79a3c545037
Jan 20 17:42:25 master-node kubelet[14525]: I0120 17:42:25.081707   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: e15ca1e2a8a4796c104dd
Jan 20 17:42:25 master-node kubelet[14525]: E0120 17:42:25.082703   14525 pod_workers.go:191] Error syncing pod 288564bab0ba9be5505a47b5c9fa6314 ("kube-contro
Jan 20 17:42:26 master-node kubelet[14525]: I0120 17:42:26.093277   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 572bf5ae0f84b04399fa9
Jan 20 17:42:26 master-node kubelet[14525]: E0120 17:42:26.093706   14525 pod_workers.go:191] Error syncing pod 44e814b7ba3263e17425ba9280ae932a ("kube-schedu
Jan 20 17:42:26 master-node kubelet[14525]: I0120 17:42:26.101918   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: e15ca1e2a8a4796c104dd
Jan 20 17:42:26 master-node kubelet[14525]: E0120 17:42:26.102502   14525 pod_workers.go:191] Error syncing pod 288564bab0ba9be5505a47b5c9fa6314 ("kube-contro
Jan 20 17:42:27 master-node kubelet[14525]: I0120 17:42:27.115376   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 572bf5ae0f84b04399fa9
Jan 20 17:42:27 master-node kubelet[14525]: E0120 17:42:27.116446   14525 pod_workers.go:191] Error syncing pod 44e814b7ba3263e17425ba9280ae932a ("kube-schedu
Jan 20 17:42:27 master-node kubelet[14525]: W0120 17:42:27.299401   14525 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 20 17:42:27 master-node kubelet[14525]: E0120 17:42:27.903460   14525 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:Netw
Jan 20 17:42:31 master-node kubelet[14525]: I0120 17:42:31.369763   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 572bf5ae0f84b04399fa9
Jan 20 17:42:31 master-node kubelet[14525]: E0120 17:42:31.370961   14525 pod_workers.go:191] Error syncing pod 44e814b7ba3263e17425ba9280ae932a ("kube-schedu
Jan 20 17:42:32 master-node kubelet[14525]: W0120 17:42:32.299565   14525 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 20 17:42:32 master-node kubelet[14525]: E0120 17:42:32.922954   14525 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:Netw
Jan 20 17:42:33 master-node kubelet[14525]: I0120 17:42:33.849701   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: e15ca1e2a8a4796c104dd
Jan 20 17:42:33 master-node kubelet[14525]: E0120 17:42:33.850082   14525 pod_workers.go:191] Error syncing pod 288564bab0ba9be5505a47b5c9fa6314 ("kube-contro
Jan 20 17:42:37 master-node kubelet[14525]: W0120 17:42:37.300054   14525 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 20 17:42:37 master-node kubelet[14525]: E0120 17:42:37.946400   14525 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:Netw
Jan 20 17:42:42 master-node kubelet[14525]: W0120 17:42:42.300559   14525 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 20 17:42:42 master-node kubelet[14525]: E0120 17:42:42.968119   14525 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:Netw
Jan 20 17:42:45 master-node kubelet[14525]: I0120 17:42:45.745549   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 572bf5ae0f84b04399fa9
Jan 20 17:42:47 master-node kubelet[14525]: W0120 17:42:47.301389   14525 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 20 17:42:47 master-node kubelet[14525]: I0120 17:42:47.314133   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 572bf5ae0f84b04399fa9
Jan 20 17:42:47 master-node kubelet[14525]: I0120 17:42:47.314444   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: fdb4884a209288cec8e6e
Jan 20 17:42:47 master-node kubelet[14525]: E0120 17:42:47.314716   14525 pod_workers.go:191] Error syncing pod 44e814b7ba3263e17425ba9280ae932a ("kube-schedu
Jan 20 17:42:47 master-node kubelet[14525]: I0120 17:42:47.744728   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: e15ca1e2a8a4796c104dd
Jan 20 17:42:48 master-node kubelet[14525]: E0120 17:42:47.995414   14525 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:Netw
Jan 20 17:42:48 master-node kubelet[14525]: I0120 17:42:48.324204   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: e15ca1e2a8a4796c104dd
Jan 20 17:42:48 master-node kubelet[14525]: I0120 17:42:48.324472   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 275135a0bdc17b0b0377e
Jan 20 17:42:48 master-node kubelet[14525]: E0120 17:42:48.324926   14525 pod_workers.go:191] Error syncing pod 288564bab0ba9be5505a47b5c9fa6314 ("kube-contro
Jan 20 17:42:48 master-node kubelet[14525]: I0120 17:42:48.333341   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: fdb4884a209288cec8e6e
Jan 20 17:42:48 master-node kubelet[14525]: E0120 17:42:48.333690   14525 pod_workers.go:191] Error syncing pod 44e814b7ba3263e17425ba9280ae932a ("kube-schedu
Jan 20 17:42:51 master-node kubelet[14525]: I0120 17:42:51.369805   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: fdb4884a209288cec8e6e
Jan 20 17:42:51 master-node kubelet[14525]: E0120 17:42:51.370720   14525 pod_workers.go:191] Error syncing pod 44e814b7ba3263e17425ba9280ae932a ("kube-schedu
Jan 20 17:42:52 master-node kubelet[14525]: W0120 17:42:52.301701   14525 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 20 17:42:53 master-node kubelet[14525]: E0120 17:42:53.016574   14525 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:Netw
Jan 20 17:42:53 master-node kubelet[14525]: I0120 17:42:53.858618   14525 scope.go:95] [topologymanager] RemoveContainer - Container ID: 275135a0bdc17b0b0377e
Jan 20 17:42:53 master-node kubelet[14525]: E0120 17:42:53.860130   14525 pod_workers.go:191] Error syncing pod 288564bab0ba9be5505a47b5c9fa6314 ("kube-contro
Jan 20 17:42:57 master-node kubelet[14525]: W0120 17:42:57.301911   14525 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Jan 20 17:42:58 master-node kubelet[14525]: E0120 17:42:58.051024   14525 kubelet.go:2163] Container runtime network not ready: NetworkReady=false reason:Netw

**Comment by neolit123** [comment]
please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
