### ISSUE TITLE
中文文档翻译错误

### ISSUE THREAD

**Issue by liuzhenwubigboss** [kubernetes/website#26163]
hi，使用 RBAC 鉴权一页，中文文档有一处翻译错误
页面链接 https://kubernetes.io/zh/docs/reference/access-authn-authz/rbac/

> 这种限制有两个主要原因：
> 1. 针对不同角色的绑定是完全不一样的绑定。要求通过删除/重建绑定来更改 `roleRef`, 这样可以确保要赋予绑定的所有主体会被授予新的角色（而不是在允许修改 `roleRef` 的情况下导致所有现有主体胃镜验证即被授予新角色对应的权限）。
> 2. 将 `roleRef` 设置为不可以改变，这使得可以为用户授予对现有绑定对象的 `update` 权限， 这样可以让他们管理主体列表，同时不能更改被授予这些主体的角色。

`胃镜`应为`未经`

**Comment by ydFu** [comment]
@liuzhenwubigboss
I had a look at it and sent in a pull request for this.
Fix typo '胃镜' to '未经'.
Fixes #26165

/assign
