### ISSUE TITLE
Installer et configurer kubectl

### ISSUE THREAD

**Issue by thomasboussekey** [kubernetes/website#26172]
Les liens indiqués sur cette page ne sont plus à jour.

J'ai utilisé la version [US](https://kubernetes.io/docs/tasks/tools/install-kubectl/) qui fonctionne

**Comment by sftim** [comment]
Page: https://kubernetes.io/fr/docs/tasks/tools/install-kubectl/
/language fr

Page en EN / anglais: https://kubernetes.io/docs/tasks/tools/install-kubectl/
