### ISSUE TITLE
Configure a Pod to Use a ConfigMap - broken links

### ISSUE THREAD

**Issue by natereid72** [kubernetes/website#26187]
These links in the page are broken:

wget https://kubernetes.io/examples/configmap/game.properties -O configure-pod-container/configmap/game.properties
wget https://kubernetes.io/examples/configmap/ui.properties -O configure-pod-container/configmap/ui.properties

**Comment by sftim** [comment]
https://kubernetes.io/examples/configmap/game.properties exists for me. https://kubernetes.io/examples/configmap/ui.properties likewise. @natereid72 do you have an unusual networking configuration?

/triage needs-information

**Comment by natereid72** [comment]
weird, works now. I don't know what the issue was when I was on the doc earlier. Sorry for the ping on it.

**Comment by tengqm** [comment]
Thanks for reporting this although it turned out to be a false alarm.
/close
