### ISSUE TITLE
Auditing

### ISSUE THREAD

**Issue by JainaHarshaVardan** [kubernetes/website#26183]
hi I followed the kubernetes docs  link is --> https://kubernetes.io/docs/tasks/debug-application-cluster/audit/  then i make one audit-policy  file that is same example in docs after that I'm  trying to apply the file getting the error like  -->    error: unable to recognize "audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1"
and also I'm trying to pass that file using kube-apiserver pod but it is telling " Error: unknown flag: --audit-policy-file" please any one help me that would be great.
I'm using 1.20 version.

**Comment by sftim** [comment]
Let's make it clear that https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/audit/audit-policy.yaml is not a manifest you apply: it's a policy you configure in the API server.

/sig api-machinery
/language en

**Comment by JainaHarshaVardan** [comment]
> Let's make it clear that https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/audit/audit-policy.yaml is not a manifest you apply: it's a policy you configure in the API server.
> 
> /sig api-machinery
> /language en

Thank you for responding my query, may i know sir how to configure that please can you tell me that clearly

**Comment by tengqm** [comment]
Two clarifications to this issue:

- auditregistration.k8s.io never had a `v1` group version;
- the whole `auditregistration.k8s.io` API group has been dropped in 1.19.

**Comment by tengqm** [comment]
@JainaHarshaVardan The audit.k8s.io API is not a published API so it doesn't have an endpoint on the API server. If you read the audit page thoroughly, you will realize how that policy YAML is applied using the `--audit-policyfile=/etc/kubernetes/audit-policy.yaml` command line flag.
/close
