### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by ruday** [kubernetes/website#26197]
hi,
there is a issue
the repo RHEL/Centos/Fedora is empty
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

regards

**Comment by sftim** [comment]
/kind bug
Not sure if this is in fact a kubectl defect; if so we can try to transfer the issue to https://github.com/kubernetes/kubectl

/sig cli

@kubernetes/sig-cli-misc please triage this report

**Comment by Cweiping** [comment]
@ruday 
You can visit `packages.cloud.google. com`? I can work on CentOS(amd64), my environment:
```shell
$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```
Reference: https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management
