### ISSUE TITLE
Blog on PSP deprecation

### ISSUE THREAD

**Issue by mbbroberg** [kubernetes/website#26202]
The Comms team was requested to write up a pre-emptive look at this one. Here's the original request: https://kubernetes.slack.com/archives/C1TU9EB9S/p1611185981053300

It relates to this action taken: https://github.com/kubernetes/kubernetes/pull/97171#issue-535490768

Draft in progress is here: https://docs.google.com/document/d/1bFbHbWT2BR5Z_TWwZ11qmUcHQlWyxp7ul612DuuGhh8/edit#

Docs team is quite welcome to comment. Kaslin and Chris will get this in as a PR in the coming days: cc @bobbytables 

/sig contributor-experience
/area contributor-comms
/assign @kaslin @chris-short

**Comment by sftim** [comment]
Cc @IanColdwater & @tabbysable (this is the issue for the PSP deprecation blog article)

/sig auth
/sig security
/priority important-soon

**Comment by mbbroberg** [comment]
The PR is in for this at https://github.com/kubernetes/website/pull/27369, so this issue is all set from the contrib comms POV. Go team 🎉
