### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/certificate-signing-requests/

### ISSUE THREAD

**Issue by robarros** [kubernetes/website#26215]
it is necessary to include command to create john.crt

**Comment by sftim** [comment]
Hi @robarros 

Would you be willing to explain your suggestion? I wasn't clear about the improvement you had in mind.

/triage needs-information
/sig auth

**Comment by ritazh** [comment]
Per triage call, looks like `It is important to set CN and O attribute of the CSR` should be expanded in the doc. https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#create-private-key

/remove-lifecycle rotten
/triage accepted
/priority important-longterm

**Comment by sftim** [comment]
OK, but:
/remove-lifecycle stale

**Comment by sftim** [comment]
@ritazh do you have a suggestion for amending the description of this issue?
