### ISSUE TITLE
Learn Kubernetes Basics

### ISSUE THREAD

**Issue by CloudXli** [kubernetes/website#26234]
start kubectl ......

**Comment by Cweiping** [comment]
Do you need any help?
/triage needs-information

**Comment by ydFu** [comment]
please try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by celestehorgan** [comment]
Hi @CloudXli,

Can you provide more details? If not, I'd like to close this issue.

**Comment by ydFu** [comment]
Thank you for your issue.
Hope you can have more information next time you raise it.

/close
