### ISSUE TITLE
Translate a Docker Compose File to Kubernetes Resources - kompose up doesn't work

### ISSUE THREAD

**Issue by pabloli84** [kubernetes/website#26244]
Hi,

This command does not exist for kompose 

```kompose up```

I'm using version 1.22 and there is no such command.

**Comment by sftim** [comment]
This looks like a report for https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

The fix I recommend is to remove the list item, currently numbered 2 in the rendered page, that starts
> Run the kompose up command to deploy to Kubernetes directly, or skip to the next step instead to generate a file to use with kubectl.

/language en
/good-first-issue
/kind bug
/triage accepted
/priority backlog

Thanks @pabloli84

**Comment by nasirhm** [comment]
I would like to work on it.

**Comment by nasirhm** [comment]
+1 to remove the list item, I would like to work on it.

/assign @nasirhm

**Comment by kbhawkey** [comment]
If you have time, this task page could use some cleanup of the markup.
