### ISSUE TITLE
Changing replicas updates immediately during paused deployment, but It is not specified in Pausing and Resuming a Deployment

### ISSUE THREAD

**Issue by shahincsejnu** [kubernetes/website#26253]
while i was reading [Pausing and Resuming a Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment) this portion of kubernetes docs, here i found that i can apply multiple fixes in between pausing and resuming without triggering unnecessary rollouts. Now, when i only changed the image of the deployment then it works fine, but when i changed the number of replicas in the deployment manifest then the pod created/deleted immediately according to the replicas number. 
Now, my question is, why it is happening? doesn't it allowed to change the replicas during paused deployment? or only image changing is allowed? the doc did not specify it. Another thing is if i changed replicas and also the image then only the replicas get applied during paused deployments with the previous image not the current one.
I think it should be specified in the docs.

**Comment by sftim** [comment]
For clarity:
/retitle Changing replicas updates immediately during paused deployment, but It is not specified in Pausing and Resuming a Deployment
/language en
/sig apps
