### ISSUE TITLE
https://www.github.com/Shyndri/video-yfkaa-materials/tree/versions%2F2.0/10-modifying-the-ui%2Fstarter%2Fsetup_demo.py

### ISSUE THREAD

**Issue by takeoffnyc** [kubernetes/website#26254]
https://www.github.com/Shyndri/video-yfkaa-materials/tree/versions%2F2.0/10-modifying-the-ui%2Fstarter%2Fsetup_demo.py

**Comment by tengqm** [comment]
Looks like off topic. Feel free to reopen with actionable details.
/close
