### ISSUE TITLE
Search page rendering incorrectly

### ISSUE THREAD

**Issue by Ghost---Shadow** [kubernetes/website#26269]
**This is a Bug Report**

**Problem:** Navbar prevents search input field from being clicked on

Can reproduce on Firefox, Chrome on latest builds

**Proposed Solution:** Remove navbar from search page

**Page to Update:**
https://kubernetes.io/search/
![Screenshot 2021-01-28 110732](https://user-images.githubusercontent.com/7743925/106095138-40147c00-6159-11eb-972f-26a4e153c3dc.png)

**Comment by sftim** [comment]
https://kubernetes.io/search/ is not supposed to look like that screenshot

/kind bug
/priority critical-urgent
/area web-development

Thanks for reporting this.

**Comment by sftim** [comment]
/retitle Navbar prevents search inputfield from being clicked

**Comment by sftim** [comment]
Actually
/retitle Search page rendering incorrectly
