### ISSUE TITLE
Web UI (Dashboard) Deployment on Windows

### ISSUE THREAD

**Issue by RoozbehBandpey** [kubernetes/website#26275]
Hi,

I am trying to deploy kubernetes dashboard UI, with:
```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml
```
I get this:
```bash
Unable to connect to the server: dial tcp 127.0.0.1:8080: connectex: No connection could be made because
 the target machine actively refused it.
```

What could be possible reason for this error? How to fix it?

Please let me know what all information you need to help me on this. I searched for other similar issues but that did not help much.

Thank you in advance.

Roozbeh

**Comment by celestehorgan** [comment]
Hi @RoozbehBandpey,

Issues in this repository must be about the documentation – we cannot provide support here. 

Is there a particular page of documentation on kubernetes.io you followed that caused this error? If not, I suggest joining [Kubernetes Slack](https://slack.k8s.io/) and asking for help there.
