### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by ravisinha0506** [kubernetes/website#26293]
I couldn't find the options to pass etcd certificates in the etcdctl api from the doc. Could you append this example in the doc: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

```
ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 \
--cacert=/etc/kubernetes/pki/etcd/ca.crt \
--cert=/etc/kubernetes/pki/etcd/server.crt \ 
--key=/etc/kubernetes/pki/etcd/server.key member list
```

**Comment by sftim** [comment]
Rather than include this detail, I wonder if it makes sense to hyperlink to the etcd documentation on the same topic.

**Comment by ravisinha0506** [comment]
> Rather than include this detail, I wonder if it makes sense to hyperlink to the etcd documentation on the same topic.

I just added the link of the doc which I am referring to!!

**Comment by sftim** [comment]
@ravisinha0506 - when I mention the etcd documentation, I mean https://etcd.io/docs/

**Comment by tengqm** [comment]
/close
This has been fixed.
