### ISSUE TITLE
Issue with /docs/admin/kube-scheduler/

### ISSUE THREAD

**Issue by perfeyhe** [kubernetes/website#2630]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The new pod is not created to the extended node when the cluster is first extended by cloning the existing node (with the following code initializing the new node at startup), but the second time the extended command is run The node will receive the new pod.

`#/bin/bash
LOCALIP="ip a | grep 'global eth0' | awk '{print $2}' | awk -F '/' '{print $1}'"

sudo sed -i "s/LOCALIP/$LOCALIP/g" /etc/default/kubelet

sudo sed -i "s/LOCALIP/$LOCALIP/g" /etc/default/kube-proxy

sudo sed -i "s/LOCALIP/$LOCALIP/g" /etc/default/flanneld

sudo service kubelet restart

sudo service kube-proxy restart

sudo service flanneld restart

sleep 10

DOCKERIP="ip a | grep 'global flannel' | awk '{print $2}' | awk -F '/' '{print $1}' | awk -F '.' '{print $1"."$2"."$3}'"

sudo sed -i "s/DOCKERIP/$DOCKERIP/g" /etc/default/docker

sudo service docker restart`

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

1.2.0

**Comment by zacharysarah** [comment]
@perfeyhe Can you clarify the specific bug you're seeing in the docs, and how it relates to the docs for `kube-scheduler`?
