### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by ahsanrossi** [kubernetes/website#26317]
minicube not installed.  even I tried with apt install minicube.

**Comment by nasirhm** [comment]
It's minik*ube, Here's how you can install it on your Debian based machine (Ubuntu, Mint, etc): https://minikube.sigs.k8s.io/docs/start/#debian-package

Once installed, You can follow the following tutorial: https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by ahsanrossi** [comment]
Thanks:)

**Comment by nasirhm** [comment]
You're welcome.

I think, we're good to close this issue.

/close

**Comment by nasirhm** [comment]
Can you please close it @ahsanrossi ?
