### ISSUE TITLE
Improvement for k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by cottrell** [kubernetes/website#26311]
Create an example specifically for development in kubernetes (not of kubernetes) deploy a web-app running with live-reload pointing to a bind mounted (or whatever) local code base.

**Comment by irvifa** [comment]
I’m not sure if I follow, is this means to capture how to automatically loads local codebase to your deployment on the k8s cluster or?

**Comment by sftim** [comment]
Hi @cottrell

This sounds like it might work better as a blog article - https://k8s.io/blog/ - than as an addition to the Concepts section of the documentation.

What do you think? If you'd like to propose an article, folks'll be happy to help you get started.

Some existing pages that look related:
- https://www.telepresence.io/discussion/overview
- https://devblogs.microsoft.com/visualstudio/bridge-to-kubernetes-ga/
- https://kubernetes.io/docs/tasks/debug-application-cluster/local-debugging/
