### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/declare-network-policy/

### ISSUE THREAD

**Issue by iamatulsingh** [kubernetes/website#26312]
I was checking "Declare Network Policy" on Kubernetes documentation. I did the same task on Katacoda but instead of getting 
`Connecting to Nginx (10.100.0.16:80)`
`remote file exists`

I got 

`Connecting to Nginx (10.98.110.76:80)`
`remote file exists`

In the screenshot, you can see n.yaml which carries the same value i.e. copy-pasted from Kubernetes documentation. If you see in it, I was running Busybox image without using `--labels="access=true"`. It should not work but work fine. 

![image](https://user-images.githubusercontent.com/20820833/106363312-bb3e8380-634d-11eb-9d3c-75208df73e58.png)

**Comment by sftim** [comment]
The page in question says “Make sure you've configured a network provider with network policy support.”

Did you select a network provider with that support @iamatulsingh ? If you didn't set up your cluster to have network policy support, you won't be able to run through that task successfully.

/kind support

**Comment by sftim** [comment]
(perhaps the page should have a custom prerequisites section to highlight that Minikube does not come with NetworkPolicy support?)

**Comment by iamatulsingh** [comment]
Sorry I didn't check the network provider. I'm closing this issue for now. If I see this problem with network provider installed then I'll reopen this issue.
