### ISSUE TITLE
配置 Pod 初始化

### ISSUE THREAD

**Issue by startwallet** [kubernetes/website#26318]
贴出的配置文件中的
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://kubernetes.io
   应为:
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://info.cern.ch

**Comment by xichengliudui** [comment]
why?

**Comment by CaoDonghui123** [comment]
> why?

sync from en
