### ISSUE TITLE
Настройка

### ISSUE THREAD

**Issue by igorkichuk** [kubernetes/website#26325]
In [this paragraph](https://kubernetes.io/ru/docs/setup/#%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B4%D0%BB%D1%8F-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0-%D0%BD%D0%B0-%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B5) is not working link(404):
![Screenshot from 2021-01-31 17-25-55](https://user-images.githubusercontent.com/32131048/106388949-6c462c00-63e9-11eb-8aef-e54b5323d35b.png)

**Comment by sftim** [comment]
/language ru

I think when that page is updated, it should link to https://kubernetes.io/docs/setup/learning-environment/ (which is a redirect)
