### ISSUE TITLE
would like to add Ionir.com storage class to the documentation

### ISSUE THREAD

**Issue by rdxbarakn** [kubernetes/website#26328]
Hello, would like to add our storage class to the documentation
our platform (Ionir.com) has some very unique capabilities built-in to kubernetes and we wish to be listed here like portwx and storageOS

wondering what is the process for this?

**Comment by Cweiping** [comment]
/kind support
/language en
/sig storage
Are there any related cases? I don't think the website will provide such pages.

**Comment by rdxbarakn** [comment]
Hello

Not sure what you mean
There are examples in the website for 3rd party storage classes

I just want to add ours to it

Barak Nissim
Director Tech Solutions
P: +972-52-4705394

**Comment by Cweiping** [comment]
Like them: https://kubernetes-csi.github.io/docs/drivers.html

**Comment by Cweiping** [comment]
/retitle would like to add Ionir.com storage class to the documentation

**Comment by rdxbarakn** [comment]
Yes this is one place
Also in the kubernetes documentation itself
Here
https://kubernetes.io/docs/concepts/storage/storage-classes/

Barak Nissim
Director Tech Solutions
P: +972-52-4705394

**Comment by rdxbarakn** [comment]
Any news on this please?

Barak Nissim
Director Tech Solutions
P: +972-52-4705394

**Comment by ionir-cloud** [comment]
this is what we are looking for updating with our yamls as example 
https://kubernetes.io/docs/concepts/storage/persistent-volumes/
https://kubernetes.io/docs/concepts/storage/storage-classes/
@Cweiping

**Comment by rdxbarakn** [comment]
this is what we are looking to update with our yamls
https://kubernetes.io/docs/concepts/storage/persistent-volumes/
https://kubernetes.io/docs/concepts/storage/storage-classes/

@Cweiping
