### ISSUE TITLE
Configure a Pod to Use a ConfigMap

### ISSUE THREAD

**Issue by shaktixcool** [kubernetes/website#26327]
Is this correct?
envFrom:
      - configMapRef:
          name: special-config

Or it should be
- envFrom:
      - configMapRef:
          name: special-config

**Comment by celestehorgan** [comment]
Hi @shaktixcool, 

Are you following a specific page of documentation when encountering this error? If so, could you please link it?

**Comment by RA489** [comment]
@shaktixcool please check the link for correct yaml
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/pod-configmap-env-var-valueFrom.yaml
