### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by auticons0902** [kubernetes/website#26330]
It seems like this note is misplaced: 
"
Note: Check the top of the terminal. The proxy was run in a new tab (Terminal 2), and the recent commands were executed the original tab (Terminal 1). The proxy still runs in the second tab, and this allowed our curl command to work using localhost:8001.
"

I think it should have been located right under the "curl..." example snippet.

**Comment by sftim** [comment]
This report is related to https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/, I think.

It's a good suggestion

/kind cleanup
/language en
/priority backlog
/triage accepted
/help

**Comment by jai** [comment]
@sftim where do I find the content on the left pane to edit (screenshot attached)? I ran a search with `ack` but couldn't find it in the entire repo/folder. Did I miss it or not look well enough?

![CleanShot 2021-04-27 at 21 00 23@2x](https://user-images.githubusercontent.com/1943284/116254580-a8e0b400-a79b-11eb-8e4f-0486073e80d9.png)

**Comment by jai** [comment]
Ok so looks like it's here: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/blob/master/7/step3.md - do I just submit a PR there?
