### ISSUE TITLE
Improve documentation about cross-namespace references

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26346]
**This is a Feature Request**

**What would you like to be added**
CustomResourceDefinitions and new internal APIs might refer to objects across namespaces. However, there are risks / challenges.

Document these.

**Why is this needed**
1. People who are considering using a cross-namespace reference in the API they are designing will want an opportunity to read about these.
2. Someone else providing feedback on that API might like a stable URI for the page that warns about the risks.

**Comments**

@deads2k [suggested](https://kubernetes.slack.com/archives/C0EG7JC6T/p1612186078072600?thread_ts=1611967173.070000&cid=C0EG7JC6T) this list of risks / shortcomings / whatever:

Cross namespace references
- create issues with leaking information about one namespace into another namespace - (status messages for instance)
- [risk] potential invasions into other namespaces - "give me that one over there" that either require exceptional checks
- [can add] referential integrity issues that one party cannot solve - referencing a namespace doesn't imply the power to control the other namespace
- [have] unclear semantics on deletion - if a namespace is referenced by other namespaces, what should a delete do?  should it clean up or force the namespace to remain alive?
- [have]    unclear semantics on creation - if a namespaces is created after its reference, is it the one we're waiting for or is it a different one created in the same name

/kind feature
/sig api-machinery
/language en

**Comment by jai** [comment]
Looks like a list was typed up here: https://github.com/kubernetes/community/pull/5455/files - I guess we can re-use the same content?

@sftim where should this be documented?
