### ISSUE TITLE
Document how to verify system cgroup setup when installing container runtime

### ISSUE THREAD

**Issue by harridu** [kubernetes/website#26359]
Newer versions of systemd use cgroup2 exclusively (aka "unified hierarchy"), ignoring legacy cgroup. Apparently some container runtimes are not compatible to cgroup2-only. This document should mention how to verify the cgroup setup (legcay, unified or hybrid) and distinguish between these environments.

**Comment by sftim** [comment]
/retitle Document how to verify system cgroup setup when installing container runtime
/sig node
