### ISSUE TITLE
在 Minikube 环境中使用 NGINX Ingress 控制器配置 Ingress

### ISSUE THREAD

**Issue by guobinzhao** [kubernetes/website#26367]
https://kubernetes.io/zh/docs/tasks/access-application-cluster/ingress-minikube/
failed with the following:
![image](https://user-images.githubusercontent.com/35445187/106711221-262fd900-6632-11eb-9f04-1ee0172ae23c.png)

**Comment by RA489** [comment]
@guobinzhao can you please try this as a workaround https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/

**Comment by guobinzhao** [comment]
still failed with error 
![image](https://user-images.githubusercontent.com/35445187/120767557-dd3f5100-c54d-11eb-890e-8af15eed4f60.png)

**Comment by tengqm** [comment]
Ingress 是在最近版本中才进入 v1 版本的。如果你用的是老版本，你要去参考老版本的文档。
/close

**Comment by guobinzhao** [comment]
I am using the "Launch Terminal" in the web site https://kubernetes.io/zh/docs/tasks/access-application-cluster/ingress-minikube/ to start the minikube.  the issue still exist.
