### ISSUE TITLE
Incorrect name stated for Endpoints

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26360]
**This is a Bug Report**

**Problem:**
The [Service](https://kubernetes.io/docs/concepts/services-networking/service/) concept page currently states:

> ```markdown
> Because this Service has no selector, the corresponding Endpoint object is not
> created automatically. You can manually map the Service to the network address and port
> where it's running, by adding an Endpoint object manually:
> ```

however, the correct name for that resource is plural: “Endpoints”.

**Proposed Solution:**
Correct the pluralization.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/

Additional Information:
/sig network
/kind bug
/language en

Spotted from PR https://github.com/kubernetes/website/pull/26353

**Comment by Arhell** [comment]
@sftim can be closed
