### ISSUE TITLE
Use consistent pluralization for API groupings in reference

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26361]
**This is a Feature Request**

**What would you like to be added**
For the pages:
https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/
https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/
https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/
https://kubernetes.io/docs/reference/kubernetes-api/services-resources/
https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/

the part before `-resources` is sometimes a plural and sometimes not.
We should make this consistent.

**Why is this needed**
When we use language inconsistently, that language becomes harder for (some) localization teams to translate well. Additionally, readers might see the different pluralization and wonder (perhaps even believe) that it is significant, given the authority attached to the website where it appears.

**Comments**
/language en
/kind cleanup

**Comment by sftim** [comment]
@feloy you might want to know about this issue - I am sure you would have some tips for a person picking it up

**Comment by kbhawkey** [comment]
This change needs to happen in the generator, `gen-resourcesdocs`?
The idea is to make the resource type or category singular?

**Comment by sftim** [comment]
>  The idea is to make the resource type or category singular?

That's the approach I'd take.
