### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/audit/

### ISSUE THREAD

**Issue by amitbis** [kubernetes/website#26384]
when applying the "simple" audit policy example it doesn't work and show this error:
the error
error: unable to recognize "audit.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1"

the policy:
# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata

**Comment by sftim** [comment]
You can pass a file with the policy to kube-apiserver using the `--audit-policy-file` flag.

@amitbis / anyone: The page is accurate, but some people might not read every word. Feel free to add a [note](https://kubernetes.io/docs/contribute/style/style-guide/#note) callout to make it clear that you can't configure API server auditing by treating that file as a manifest.

/language en
