### ISSUE TITLE
Improvement for k8s.io/docs/reference/glossary/

### ISSUE THREAD

**Issue by MadDashMurphy** [kubernetes/website#26383]
Sounds stupid and obvious but "Microservice" is missing a definition in the Glossary.  It is referenced twice by other entries but not defined.

**Comment by sftim** [comment]
/kind feature
/priority awaiting-more-evidence

As “microservice” is not a Kubernetes term, we could infer that readers can use a web search engine to look it up. I'm also open to adding this term if anyone wants to open the PR for it.
/language en

**Comment by sftim** [comment]
I notice that on Google Search, the top three results for “microservice” look really relevant.

**Comment by MadDashMurphy** [comment]
> /kind feature
> /priority awaiting-more-evidence
> 
> As “microservice” is not a Kubernetes term, we could infer that readers can use a web search engine to look it up. I'm also open to adding this term if anyone wants to open the PR for it.
> /language en

Good point although Istio is not a Kubernetes term but is listed in the glossary so I think there is precedent.  I think it is an opportunity to help newbies (me) coalesce around a definition and understand how it relates to Kubernetes.

Thanks for looking at it.
