### ISSUE TITLE
Translate reference/glossary/storage-class.md in Korean

### ISSUE THREAD

**Issue by santachopa** [kubernetes/website#26393]
**This is a Feature Request**

**What would you like to be added**

Translate reference/glossary/storage-class.md in Korean

**Why is this needed**
No translation reference/glossary/storage-class.md in Korean

**Comments**

Page to update : https://kubernetes.io/ko/docs/reference/glossary/?core-object=true#term-storageclass

**Comment by seokho-son** [comment]
/triage accepted
Thank you!
