### ISSUE TITLE
correct Falco Chart  URL

### ISSUE THREAD

**Issue by Abdessamii85** [kubernetes/website#26406]
**This is a Feature Request**

**replace the link for the "Falco Helm Chart" from https://github.com/helm/charts/tree/master/stable/falco to https://github.com/falcosecurity/charts/tree/master/falco**

**the incubator/falco is deprecated in favor of the official Falco Helm Chart**

**Comments**

**Comment by sftim** [comment]
Hi @Abdessamii85 

Which page do you think is not right?
/triage needs-information

**Comment by Abdessamii85** [comment]
Hi @sftim  this page : https://v1-16.docs.kubernetes.io/docs/tasks/debug-application-cluster/falco/

**Comment by sftim** [comment]
@Abdessamii85 the appropriate action is actually to _remove_ that task page from the v1.16 documentation. This is because that page no longer fits in with our [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).

**Comment by Marusyk** [comment]
Hi @sftim
Well, the task is to remove this page : https://v1-16.docs.kubernetes.io/docs/tasks/debug-application-cluster/falco/ ?

**Comment by Marusyk** [comment]
@sftim Could you please suggest?

**Comment by sftim** [comment]
The link to Falco is no longer part of the Kubernetes documentation

/close
