### ISSUE TITLE
kompose task page (duplicate content and naming)

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#26416]
**This is a Bug Report**
The `kompose` tool has a dedicated website and github repository:
 `kompose.io` and `https://github.com/kubernetes/kompose`. Should the `kompose` task page exist on kubernetes.io?

**Problem:**
- The task page, `en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md` duplicates
content found in the site `kompose.io` and `https://github.com/kubernetes/kompose`.
- The example configuration, `https://raw.githubusercontent.com/kubernetes/kompose/master/examples/docker-compose.yaml`
   contains references to `master` and `slave`.

**Proposed Solution:**
Investigate whether the task page should be maintained in the `kubernetes.io` site.
Modify the example manifest by removing the references to redis `master` and `slave`.

**Page to Update:**
`en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md`

**Comment by kbhawkey** [comment]
Related to https://github.com/kubernetes/website/issues/20232

**Comment by pietervincken** [comment]
Note that the information on the page is outdated as well. Kompose up and down were removed in the latest version.
