### ISSUE TITLE
kubeadm config

### ISSUE THREAD

**Issue by shreemadaExploring** [kubernetes/website#26425]
when execute any kubectl command I get the following error in the worker nodes, 

```
 kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or p
ort?
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196
815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", Go
Version:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or p
ort?
```
how do we create admin.conf for worker nodes? 

It works fine in master system.

**Comment by neolit123** [comment]
on worker nodes you should not copy the admin.conf, it should be used only on control plane nodes by the admin.

you could use the kubelet.conf on workers but know that it's limited:
`KUBECONFIG=/etc/kubernetes/kubelet.conf sudo kubectl get no`

/kind support
/close

for other support questions please use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
