### ISSUE TITLE
Advice on task “Configure Service Accounts for Pods”

### ISSUE THREAD

**Issue by Jerry4013** [kubernetes/website#26434]
To use a non-default service account, simply set the spec.serviceAccountName field of a pod to the name of the service account you wish to use.

If using a minikube, how can I set spec.serviceAccountName of this pod? Thanks!

**Comment by sftim** [comment]
/retitle Advice on task “Configure Service Accounts for Pods”

/kind support
I think

We could explain how to edit the Pod, but that feels like it'd be better covered as signposting to a “how do I edit a Pod” task.
