### ISSUE TITLE
Use Port Forwarding to Access Applications in a Cluster

### ISSUE THREAD

**Issue by adthonb** [kubernetes/website#26457]
On Forward a local port to a port on the Pod section

this
`kubectl port-forward service/redis-master 7000:redis`

should be
`kubectl port-forward service/redis-master 7000:6379`

**Comment by irvifa** [comment]
Could you please link the page @adthonb

**Comment by adthonb** [comment]
@irvifa This page https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#forward-a-local-port-to-a-port-on-the-pod
