### ISSUE TITLE
Kubernetes Scheduler documentation does not mention deprecation of scheduling policies API

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/website#26450]
**This is a Bug Report**

**Problem:**
Scheduling Policies API was deprecated beginning 2018. Yet, [Kubernetes Scheduler documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/) does not mention the fact (it's been 3 years now). Worth mentioning there to inform users not aware of the fact to prepare for it and transition into Scheduling Profiles API instead.
Also, worth mentioning the same in https://kubernetes.io/docs/reference/scheduling/policies/.

**Proposed Solution:**
Mention keyword deprecated in docs for scheduling policies API.

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/ (search for "Scheduling Policies")
https://kubernetes.io/docs/reference/scheduling/policies/

**Comment by sftim** [comment]
Do we also need to update https://kubernetes.io/docs/concepts/scheduling/scheduling-framework/ ?

**Comment by ingvagabund** [comment]
I don't think we do. Though, we might update https://kubernetes.io/docs/reference/scheduling/policies/ and mention the Plugin API. The scheduling framework has nothing to do with the Policy API and there's no need for new users to know about the Policy API. Anyone who's still using the Policy API is probably aware it's deprecated and will be gone. Configuration of new plugins is available only through the Plugin API anyway.

Not sure what's the official policy for deprecating an API. Maybe to release a blog post alongside to summarize which bits can no longer be configured and what's the recommended migration for the rest to the new Plugin API.

@alculquicondor any thoughs?

**Comment by alculquicondor** [comment]
We do need to update it to stable since 1.19, but it's not directly related (it's part of the implementation of scheduler component config, which is the alternative to policies).

+1 on a blog. We plan to remove it 2 or 3 releases after scheduler component config reaches stable (planned for 1.23)

**Comment by alculquicondor** [comment]
/close

This was addressed during removal https://kubernetes.io/docs/reference/scheduling/policies/
