### ISSUE TITLE
unkown command Kompose up 

### ISSUE THREAD

**Issue by makuzaverite** [kubernetes/website#26462]
I have been going through the docs [configuring compose kubernates](https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/)

I have setup kompose but running kompose up command fails 

![image](https://user-images.githubusercontent.com/53856673/107612087-50693400-6bfa-11eb-9452-b94c70fd04f2.png)

How to Fix this

**Comment by sftim** [comment]
The fix for this would be similar to https://github.com/kubernetes/website/pull/26323

/triage accepted
/sig cli
/language en
/kind bug

**Comment by tengqm** [comment]
Closing this since the issue has been resolved in #26323. Feel free to reopen if there are still issues related to this.
/close
