### ISSUE TITLE
Configure Certificate Rotation for the Kubelet

### ISSUE THREAD

**Issue by felixPG** [kubernetes/website#26475]
Please, add the time that kubelet take in consideration to rotate the certificate  that is 70% to 90% is between 3.6 months before and 1.2 months before expiration.

**Comment by tengqm** [comment]
> Please, add the time that kubelet take in consideration to rotate the certificate that is 70% to 90% is between 3.6 months before and 1.2 months before expiration.

This is not clear. Please elaborate? The certificate expiration is not controlled by kubelet. It is determined by the certificate itself.

**Comment by felixPG** [comment]
"Kubernetes 1.8 contains kubelet certificate rotation, a beta feature that will automatically generate a new key and request a new certificate from the Kubernetes API as the current certificate approaches expiration. Once the new certificate is available, it will be used for authenticating connections to the Kubernetes API."

How much time in advance the certificate rotates before it expires??

**Comment by tengqm** [comment]
@felixPG is [this PR](https://github.com/kubernetes/website/pull/26496) the one that answers your question?

**Comment by felixPG** [comment]
yes!! thanks so much @tengqm
