### ISSUE TITLE
Helm Charts repository is obsolete. The link should be removed or targeted to the Artifact Hub

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#26470]
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#what-s-next

Helm Charts repository ( https://github.com/helm/charts ) is obsolete.
This sentence should be removed or updated.
https://artifacthub.io/ might be appropriate.
> Look in the Helm Charts repository for other stateful application examples.

**Comment by OmkarPh** [comment]
If this issue is validated, may I take this up?
