### ISSUE TITLE
Document Taints and Tolerations as an API

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/website#26485]
**This is a Feature Request**

**What would you like to be added**
Taints and tolerations form an API.  We should document this API in a single place with information where each one comes come.

**Why is this needed**

There are a variety of built-in system and "special" taints that are applied to nodes.

Taints and tolerations form an API.  We should document this API in a single place with information where each one comes from.

**Comments**

For example, `node.kubernetes.io/unschedulable` is specifically applied when a node is cordoned (currently, this implies spec.unschedulable==True).  The documentation doesn't call this out.  The documentation doesn't mention that if you attempt to add this taint by hand to a node (without setting spec.unschedulable=True), it will be removed.

The documentation would also serve a further purpose: it will help component developers use or not use the specific taints.  This will serve as a contract of behavior so we don't regress in the future.

**Comment by tengqm** [comment]
Do you mean this page? https://kubernetes.io/docs/reference/labels-annotations-taints/

**Comment by gregth** [comment]
> Do you mean this page? https://kubernetes.io/docs/reference/labels-annotations-taints/
> We have a PR flying in to improve that page btw.

@tengqm Which PR is the one mentioned? And what is its state? 

I agree with this issue that there are certain behavior details that need to be documented, such as the one mentioned:

> For example, node.kubernetes.io/unschedulable is specifically applied when a node is cordoned (currently, this implies spec.unschedulable==True). The documentation doesn't call this out. The documentation doesn't mention that if you attempt to add this taint by hand to a node (without setting spec.unschedulable=True), it will be removed.

In general, I was unable to find sufficient information in the docs wrt to `spec.unschedulable` field, who should use it, who sets it, etc.
