### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by matthew-howey-home** [kubernetes/website#26494]
This link "https://index.docker.io/v1/" appears to be broken in the line:
" <your-registry-server> is your Private Docker Registry FQDN. (https://index.docker.io/v1/ for DockerHub) "

**Comment by tengqm** [comment]
According to https://www.docker.com/blog/registry-v1-api-deprecation/, the V1 API has been deprecated.
