### ISSUE TITLE
[ja] Remove /content/ja/docs/tasks/tools/install-minikube.md page

### ISSUE THREAD

**Issue by bells17** [kubernetes/website#26504]
**This is a Feature Request**

Need to delete the old content.

**What would you like to be added**

The original content content/en/docs/tasks/tools/install-minikube.md was removed.
ja page is here: https://kubernetes.io/ja/docs/tasks/tools/install-minikube/

So we need to remove /content/ja/docs/tasks/tools/install-minikube.md page.

**Why is this needed**

To update the contents.

**Comments**

**Comment by ryokotmng** [comment]
@bells17 (cc: @inductor ) こちら、多分今の時点の `dev-1.18-ja.2` ブランチで既に完了している気がします。ご確認お願いします🙇🏻‍♂️

**Comment by bells17** [comment]
ありがとうございます
閉じますね

/close
