### ISSUE TITLE
ja: Make docs/setup/production-environment/turnkey/clc.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26518]
**This is a Feature Request**

**What would you like to be added**
Update docs/setup/production-environment/turnkey/clc.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/setup/production-environment/turnkey/clc.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.18-ja.2/content/ja/docs/setup/production-environment/turnkey/clc.md

Original
https://github.com/kubernetes/website/tree/release-1.18/content/en/docs/setup/production-environment/turnkey/clc.md

diff between translated and v1.18
https://gist.github.com/38797d234b49a7181f9939aefc3bd020

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
めも: ファイルごと消えてるので、削除するのか、他のドキュメントに移行するのかは確認が必要

**Comment by butterv** [comment]
@inductor 
Thank you for creating issues.
This issue expects to follow v1.18, so I will remove this ja file.
Okay?

**Comment by inductor** [comment]
@butterv as written in memo, please make sure if the content has been moved somewhere else or not at first

**Comment by butterv** [comment]
@inductor 
The issue is #17514.
This issue has been proposed to be removed or renewed, but it appears to have been removed.
