### ISSUE TITLE
ja: Make docs/setup/production-environment/tools/kubeadm/self-hosting.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26513]
**This is a Feature Request**

**What would you like to be added**
Update docs/setup/production-environment/tools/kubeadm/self-hosting.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/setup/production-environment/tools/kubeadm/self-hosting.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.18-ja.2/content/ja/docs/setup/production-environment/tools/kubeadm/self-hosting.md

Original
https://github.com/kubernetes/website/tree/release-1.18/content/en/docs/setup/production-environment/tools/kubeadm/self-hosting.md

diff between translated and v1.18
https://gist.github.com/2b3b6ec253a6b96ffeed2a911f382782

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
@yoichiro0217 こちら進捗いかがでしょうか？

**Comment by yoichiro0217** [comment]
@inductor すいません、着手が遅れました。ちょっと確認させて頂きたいのですが、この[ja版のページ](https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/setup/production-environment/tools/kubeadm/self-hosting.md)は全体が翻訳されてないのですが、こちらページ全体を翻訳するissueでしょうか？

**Comment by inductor** [comment]
@yoichiro0217 翻訳は必須ではないですが、やって頂いてる方もいらっしゃいますのでベストエフォートでと言う感じです。
もちろん英文だけアップデートしていただくのでも大歓迎です！

**Comment by yoichiro0217** [comment]
@inductor 承知しました、ご回答ありがとうございます。
