### ISSUE TITLE
ja: Make docs/setup/production-environment/tools/kubespray.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26516]
**This is a Feature Request**

**What would you like to be added**
Update docs/setup/production-environment/tools/kubespray.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/setup/production-environment/tools/kubespray.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.18-ja.2/content/ja/docs/setup/production-environment/tools/kubespray.md

Original
https://github.com/kubernetes/website/tree/release-1.18/content/en/docs/setup/production-environment/tools/kubespray.md

diff between translated and v1.18
https://gist.github.com/f2f7cd266b7db91e6dcd158ceff21db6

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by tengqm** [comment]
@inductor Is it more appropriate to consolidate this issue and the following ones into an umbrella one?
