### ISSUE TITLE
ja: Make docs/setup/production-environment/windows/user-guide-windows-nodes.md follow v1.18 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26526]
**This is a Feature Request**

**What would you like to be added**
Update docs/setup/production-environment/windows/user-guide-windows-nodes.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/setup/production-environment/windows/user-guide-windows-nodes.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.18-ja.2/content/ja/docs/setup/production-environment/windows/user-guide-windows-nodes.md

Original
https://github.com/kubernetes/website/tree/release-1.18/content/en/docs/setup/production-environment/windows/user-guide-windows-nodes.md

diff between translated and v1.18
https://gist.github.com/1dffbd91268449136e814ae6ed85866c

**Note**
Currently, we use **dev-1.18-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
めも: 削除扱いになってるけど、移動してるだけの可能性もあるのでファイルの所在確認が必要

**Comment by tanaka-takayoshi** [comment]
この[コミット](https://github.com/kubernetes/website/commit/615c7f619feabb614593276f7b6f421bf626987e#diff-b9b9ec884a517fc10bec7b2f9935b1c17aea1df7001bb53dc3a44f367736422f) にて [adding-windows-nodes.md](https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md)と[upgrading-windows-nodes.md](https://github.com/kubernetes/website/blob/dev-1.18-ja.2/content/ja/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md)に編集の上移動されており、移動後のページはすでに翻訳済みなので、このページを削除するPRを出せばよいでしょうか？

**Comment by inductor** [comment]
@tanaka-takayoshi 所在確認っていうのはその辺含めての確認という意味だったのでそれで問題ない認識です。ご確認ありがとうございます！
