### ISSUE TITLE
Kubernet.es domain not working

### ISSUE THREAD

**Issue by 0x2b3bfa0** [kubernetes/website#26537]
Follow-up of #91; is it supposed to work?

**Comment by sftim** [comment]
`kubernet.es` is registered to Google
/sig docs

Let's use this issue to track investigation about ownership and a possible transfer (Google willing) to the Cloud Native Computing Foundation.
/triage accepted

**Comment by thockin** [comment]
I think we decided to EOL that a long time ago, rather than make yet another alias in all the configs and manage another set of SANs on certs.

I hope we don't document it anywhere?  I don't think we really want it to work, do we?

**Comment by sftim** [comment]
I don't think https://kubernet.es/ needs to serve any content; however, I'm wondering about whether Google would transfer domain ownership to the CNCF.

**Comment by thockin** [comment]
I can seek an answer to that question but I'd prefer to argue that it's not something we use so we should just pretend it never existed

**Comment by sftim** [comment]
/wg k8s-infra 

Nothing to do here - thanks for checking @0x2b3bfa0 
/close
