### ISSUE TITLE
Yarn Debian key expiry date updated 

### ISSUE THREAD

**Issue by AaronLuo3296** [kubernetes/website#26539]
**This is a Bug Report**

**Problem:**

The Yarn Debian key has expired for the script in [Ubuntu, Debian or HypriotOS](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-0). I got the following error message when I ran `sudo apt-get update`:
```
The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
```

**Proposed Solution:** 

As mentioned in [yarnpkg/yarn](https://github.com/yarnpkg/yarn/issues/7866), to get the updated key, run this: 
```curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -``` 

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#k8s-install-0

**Comment by neolit123** [comment]
> As mentioned in yarnpkg/yarn, to get the updated key, run this:
> curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -

@kubernetes/release-engineering 

hello, the associated PR is making a change from the existing GPG @ google:
https://packages.cloud.google.com/apt/doc/apt-key.gpg

should we instead update the GPG key @ google?

**Comment by sftim** [comment]
I'm not sure I understand why this change makes sense. The issue description mentions Yarn even though the existing page makes no mention of Yarn.
/remove-good-first-issue

**Comment by sftim** [comment]
@AaronLuo3296 I think the existing page is correct. If you have an outdated Yarn key on your system, because you have used Yarn previously, then you should follow the Yarn documention about that. Kubernetes does not document how to ensure you have a current signing key for Yarn; these are different projects.

/remove-kind bug
/kind support

**Comment by justaugustus** [comment]
From RelEng:
Agreed with @sftim's assessment.
This is an issue with the user's local development environment and they should follow Yarn's documentation for adding/updating/removing package signing keys.

@kubernetes/build-admins -- FYI, but no action required.
/close

**Comment by neolit123** [comment]
thanks for having a look @sftim and @justaugustus
