### ISSUE TITLE
Ephemeral vs. persistent volumes wording

### ISSUE THREAD

**Issue by FrankAtHexagon** [kubernetes/website#26563]
Under the _Backgrounds_ section, there's this paragraph:
> Kubernetes supports many types of volumes. A Pod can use any number of volume types simultaneously. Ephemeral volume types have a lifetime of a pod, but persistent volumes exist beyond the lifetime of a pod. Consequently, a volume outlives any containers that run within the pod, and data is preserved across container restarts. When a pod ceases to exist, the volume is destroyed.

I'm wondering about the last sentence: 'When a pod ceases to exist, the volume is destroyed.' Is that correct? An ephemeral volume may be destroyed, but a persistent volume should exist beyond the lifetime of a pod by definition.

**Comment by tengqm** [comment]
/triage accepted

The description is inconsistent.

**Comment by FrankAtHexagon** [comment]
Thanks for fixing this! 🥳
