### ISSUE TITLE
dockershim alias points to localized version instead of the default

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/website#26597]
**This is a Bug Report**

**Problem:**
The dockershim alias (https://kubernetes.io/dockershim) now directs to the Chinese localized version (https://kubernetes.io/zh/blog/2020/12/02/dockershim-faq/) because the same alias exists in multiple files.

**Proposed Solution:**
Removal of the alias in the Chinese version of the blog post or updated to be `zh/dockershim`
https://github.com/kubernetes/website/blob/master/content/zh/blog/_posts/2020-12-02-dockershim-faq.md

A policy or linter might be worth putting in place for aliases as well to prevent future issues.

**Page to Update:**
https://github.com/kubernetes/website/blob/master/content/zh/blog/_posts/2020-12-02-dockershim-faq.md

**Comment by kbhawkey** [comment]
A similar problem occurred with a `security` alias.
Should add a note to the localization or `contribute` documentation about updating the `aliases` field.
