### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by atbk5** [kubernetes/website#26591]
Some of the references giving 404 now.
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide  - This directory is no longer available.

**Comment by tengqm** [comment]
See https://github.com/kubernetes/website/pull/26564

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/26564 I think
/close
