### ISSUE TITLE
Suggestion for kubectl cheat sheet

### ISSUE THREAD

**Issue by SebTardif** [kubernetes/website#26609]
I think -A instead of --all-namespaces would be appreciated to be known by the cheater.

**Comment by sftim** [comment]
/retitle Suggestion for kubectl cheat sheet
/language en

I think this suggestion is for https://kubernetes.io/docs/reference/kubectl/cheatsheet/#formatting-output - is that right?

**Comment by SebTardif** [comment]
I think "--all-namespaces" should not show-up in the cheat sheet because the goal is shortcut, only -A should shows up

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/26609#issuecomment-782719112 sounds inline with the “cheat sheet” concept.

**Comment by prankul88** [comment]
> However, I can also see the value of using long option names - they're self documenting.

+1
