### ISSUE TITLE
Add tutorial explaining how to deploy a Kubernetes cluster (without using kind / minikube / etc)

### ISSUE THREAD

**Issue by rich-pixley** [kubernetes/website#26618]
Doesn’t work.  Doesn’t explain anything.  What’s the point of this?

**Comment by sftim** [comment]
Hi @rich-pixley 

Would you be willing to explain your question a bit more? If you can provide context that's even better. For example, if there's a particular page or part of a web page that doesn't make sense, please provide it's URL and perhaps also the heading of the bit you're not following.

/language en
/triage needs-information

**Comment by rich-pixley** [comment]
It’s the overall that’s a problem. 

I’m brand new to kubernetes but not to OS concepts. I’m looking for a tutorial in the sense of introducing base concepts then branching out into variations and I’m not finding it.

The tutorials that exist walk me through using a bunch of tangential tools, I presume.  They don’t work so I didn’t bother to follow for long as they didn’t seem to be relevant and thus didn’t hold my attention.

Like, what do I need to do to create a kubernetes cluster and launch a job?  Using just kubernetes without 16 other super fragile and complex adjuncts that don’t work anyway and I can’t debug because I have no idea why they were even brought in.  Surely that should be easy by now, yes?

**Comment by sftim** [comment]
@rich-pixley if you'd be willing to write up the differences between your expectations and what you encountered, in issue format, then that'd be really valuable to Kubernetes. It sounds like you're looking for a few different things and haven't found what you were after. If you can communicate what those gaps are, [SIG Docs](https://github.com/kubernetes/community/tree/master/sig-docs#docs-special-interest-group) can work on closing them.

I recommend that you log a brand new issue (or multiple issues) to cover explaining how those gaps look to you. SIG Docs is super keen to make Kubernetes accessible to people who don't already have experience deploying and using it.

To make your point effectively, you might find some guidance useful. For example, have a look at [How to file great issues](https://kubernetes.io/docs/contribute/suggest-improvements/#how-to-file-great-issues) or Wiredcraft's [_How We Write Github Issues_](https://wiredcraft.com/blog/how-we-write-our-github-issues/).

**Comment by rich-pixley** [comment]
I could have sworn I'd just done that.  But I can do it again.

I don't need the pages of marketing.  I don't need the pages of OS 
background or the ci/cd cheerleading or the incessant looping pointers 
that force me to read the same marketing and cheerleading over and over 
and over again.

What I need and what I'm looking for is a description, step by step, of 
how to bring up a rudimentary or even degenerate kubernetes cluster and 
run a simple job using kubernetes alone. And then pointers to where to 
go to read/learn about any additional features that I might want to 
include like logging, monitoring, or whatever else you might offer in 
the way of debugging tools and stuff like minikube or whatever else 
offers commonly configurations.

If I have to learn about katacoda or minicube or any of the other 
adjuncts, then I'm going to turn off.  Those aren't what I'm looking for.

If I start with minikube and a simple 3 or 4 cut & paste commands to 
"hello world", that might be excellent marketing as it feels like an 
accomplishment, but it does absolutely zero with respect to skills 
transfer which is what I'm looking for.

While I understand that many of your readers may simply want to get to 
the point where they can run a job and that may be all they ever want to 
do, /I/ want to be able to understand the architecture enough to come up 
with new configurations and to debug existing ones that aren't doing 
what someone might expect. I expect that will happen to me initially and 
I absolutely need to be able to track it down.  So creating a simple 
cluster initially that works, and then understanding how to debug as I 
add features and complications, is what I need.

**Comment by sftim** [comment]
It sounds like what you want is a guide to deploying a more production-like cluster @rich-pixley 

How well does https://kubernetes.io/docs/setup/ match what you wanted to find?
If there's a gap, the more you can explain what's missing, the better we can look for ways to fill that.

**Comment by rich-pixley** [comment]
Sorta. That page has a lot of non-info pages linked. But if I’m reading it right, the only page with any actual kubernetes info is the page on container runtimes. 

So that’s all I need?  I install docker on all my machines and magically kubectl suddenly works?  I bet not. I bet there are some daemons that need to run somewhere but none of those pages talk about that. Probably, there’s something I need to do to make kubectl rendezvous with a particular kubernetes cluster as well.

Instead, there are pages upon pages of add-ones that, if one understood the architecture and specifically wanted the very narrow thing each add-on provides, might, possibly, be useful.  But without knowing what’s required they’re just unnecessary complications obscuring whatever.

Surely I don’t have to read through the source code of kind just to learn how to set up kubernetes. 

Isn’t there, like, an Ubuntu package, and a config file or two, and can’t I create a kubernetes cluster by installing one of those on each of a couple of machines and starting a service?  I understand that’s complicated and doesn’t scale to large installations as a manual process but obviously none of the add-ons do either.

**Comment by rich-pixley** [comment]
This link is pretty close to what I'm looking for with a number of 
exceptions.

https://thenewstack.io/how-to-deploy-a-kubernetes-cluster-with-ubuntu-server-18-04/ 
<https://thenewstack.io/how-to-deploy-a-kubernetes-cluster-with-ubuntu-server-18-04/>

  * It's stale and needs to be updated.
  * It's only for ubuntu and good instructions should cover most major
    distros.
  * This suggests that kubeadm is part of kubernetes which your pages
    seem to have denied.
  * it pulls in a "pod network" called "flannel".  I have no idea what
    that is nor why I'd want it and that bothers me greatly.  I stopped
    reading at that point.
  * I think it should end with a "hello world" trivial example just to
    demonstrate that a job was queued, gets run, where it gets run, and
    what the output is.  That is, either log introduction or monitoring
    or whatever is available at this point so that I can convince myself
    that it's actually installed and running.
  * There should be a brief discussion and explanation of the major
    demons involved at the beginning, before we install or start running
    them.
  * It needs to cover common trouble shooting and failure scenarios.
  * Also, it's completely acceptable to state that docker needs to be
    installed, point to the docker install pages on docker's site, and
    then pick up as though it were already installed. Those instructions
    don't need to be duplicated with stale, nonworking instructions.

Don't get me wrong.  Everyone who reads instructions like these will 
/immediately/ be thinking about ways to automate them, more extensive 
monitoring, and deployment scenarios.  That's /fine/. /Then/ is the time 
to talk about minikube, microK8, or whatever the other deployment upper 
levels and add-ons happen to be with pointers to their rough equivalents 
to these instructions.  But without this basic beginning config 
knowledge, I'm months away from being able to reverse engineer minkube 
or whatever down into kubernetes into wtf "flannel" is in order to 
figure out why things aren't working.  And at that point, I'm discarding 
kubernetes and looking for another solution because that sort of UX is 
absurd in this day and age.

Am I making any more sense yet?

**Comment by sftim** [comment]
/retitle Add tutorial explaining how to deploy a Kubernetes cluster

**Comment by sftim** [comment]
/retitle Add tutorial explaining how to deploy a Kubernetes cluster (without using kind / minikube / etc)

**Comment by sftim** [comment]
/kind feature
/language en
@rich-pixley would you be willing to revise the issue description (there's an edit button) to match your last comment?

**Comment by sftim** [comment]
Given the lack of response to https://github.com/kubernetes/website/issues/26618#issuecomment-807866891, I'm happy to close this.

/close

@rich-pixley you are welcome to open a new issue. If you do, please aim to write it as an actionable task. The guide at https://developers.google.com/blockly/guides/contribute/get-started/write_a_good_issue is a useful guide, even though it's for a different project.
