### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/

### ISSUE THREAD

**Issue by rich-pixley** [kubernetes/website#26617]
Katacoda doesn’t work.  Minikube doesn’t work. Is there a good, official, tutorial that does work?  Or that is “printed” only without requiring finicky interactive stuff that never works?

**Comment by sftim** [comment]
I tested https://k8s.io/docs/tutorials/hello-minikube/ following the instructions, using Katacoda to host the cluster.

I noticed a missing detail. Before you run `minikube dashboard`, you should open a _new_ terminal, start `minikube dashboard` there, and then switch back to the main terminal.

Alternatively, we could rely on shell process management and have the reader run `minikube dashboard &`. This doesn't work on Windows though.

Would you be willing to revise the issue description to include these details I discovered @rich-pixley?

**Comment by rich-pixley** [comment]
I didn't have any luck with it on any of several browsers I tried.  It 
failed out on all of them.
