### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by RakeshRam** [kubernetes/website#26614]
Ingress steps mentioned in the docs do not work on **_windows with minikube_**. 

Its works up to the Services step:
```
Path>minikube service web
|-----------|------|-------------|---------------------------|
| NAMESPACE | NAME | TARGET PORT |            URL            |
|-----------|------|-------------|---------------------------|
| default   | web  |        8080 | http://111.111.11.1:31849 |
|-----------|------|-------------|---------------------------|
* Starting tunnel for service web.
|-----------|------|-------------|------------------------|
| NAMESPACE | NAME | TARGET PORT |          URL           |
|-----------|------|-------------|------------------------|
| default   | web  |             | http://127.0.0.1:52495 |
|-----------|------|-------------|------------------------|
* Opening service default/web in default browser...
! Because you are using a Docker driver on windows, the terminal needs to be open to run it.
```

After that, the ingress steps fail. 

```
Path>kubectl get ingress --watch
NAME              CLASS    HOSTS   ADDRESS        PORTS   AGE
example-ingress   <none>   mydemo.demo       111.111.11.1   80      13s
```

Both accessing by domain name and IP times out. 

```
Path>curl -iv "111.111.11.1"
* Rebuilt URL to: 111.111.11.1/
*   Trying 111.111.11.1...
* TCP_NODELAY set
* connect to 111.111.11.1 port 80 failed: Timed out
* Failed to connect to 111.111.11.1 port 80: Timed out
* Closing connection 0
curl: (7) Failed to connect to 111.111.11.1 port 80: Timed out
```

```
Path>curl mydemo.demo       
curl: (7) Failed to connect to mydemo.info port 80: Timed out
```

```
Minikube Version
minikube version: v1.16.0
commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1
```

```
Kubectl
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
```

```
Windows 10 Home
64 Bit
```

**Comment by sftim** [comment]
@RakeshRam how did the IP address range that `111.111.11.1` falls within get assigned? Was that minikube's own choice or a customization made separately?

/triage support

**Comment by RakeshRam** [comment]
> @RakeshRam how did the IP address range that `111.111.11.1` falls within get assigned? Was that minikube's own choice or a customization made separately?
> 
> /triage support

That is the IP from minikube. I get that when I run `minikube tunnel`. And I used the above IP( `111.111.11.1` ) just as a representation.  In reality i get something like `192.168....`

**Comment by sftim** [comment]
I suspect that the tutorial is correct but that @RakeshRam's local cluster isn't set up how the tutorial expects.

@RakeshRam I notice that's quite an old minikube used with a newish kubectl. You might like to try the latest minikube and see if that helps.

**Comment by RakeshRam** [comment]
@sftim Thanks. I updated minikube version to `v1.17.1`. but that did not solve my problem. I believe it is something to do with the minikube IP. Because both ingress address and minikube ip are the same. 

**SideNote**: Also, I have the same issue while accessing the app using Istio gateway.

**Comment by RakeshRam** [comment]
The ingress, and ingress-dns addons are currently only supported on **Linux**.  Currently not supported on Windows. 
**[MoreInfo](https://minikube.sigs.k8s.io/docs/drivers/docker/#known-issues)**

![image](https://user-images.githubusercontent.com/1567074/109641679-fcf26200-7b77-11eb-92eb-203cbce9f490.png)

Not Supported on Windows:
- minikube version: v1.16.0
- minikube version: v1.17.1
