### ISSUE TITLE
"Use Port Forwarding to Access Applications in a Cluster" uses removed manifests

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#26628]
[This page](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/) uses manifests
- https://k8s.io/examples/application/guestbook/redis-master-deployment.yaml
- https://k8s.io/examples/application/guestbook/redis-master-service.yaml

However, these files were removed in 99029b97d7c93373cf20e9609782428f107654c2.
The new example is using mongodb instead of redis, and so, the document needs to be updated overall.

The page to update:
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

**Comment by sftim** [comment]
/kind bug
/language en
/priority backlog
/triage accepted

/help

Thanks @oke-py
