### ISSUE TITLE
Broken link in concept page about Operators

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26641]
**This is a Bug Report**

**Problem:**
In the [What's next](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#what-s-next) section of the _Operator pattern_ concept page there is a link to CoreOS' original article about the Operator pattern.

Following a series of acquisitions it _looks_ like that article is no longer published. I couldn't find a current URL for it.

**Proposed Solution:**
Update the link to point at https://web.archive.org/web/20170129131616/https://coreos.com/blog/introducing-operators.html and mention in the text that this is archived from the original.

**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ 

**Additional Information:**
To edit via GitHub web interface: _https://github.com/kubernetes/website/edit/master/content/en/docs/concepts/extend-kubernetes/operator.md_

/kind bug
/priority backlog
/language en
/triage accepted
/good-first-issue

**Comment by varenaggarwal** [comment]
I would like to take this one. This will be my first time contributing to repo, so I might take a while.

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/26651
/close
