### ISSUE TITLE
List operator tools in alphabetical order

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26642]
**This is a Cleanup Request**

**What would you like to be added**
- Revise https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ to move the list of libraries for writing operators out of the [What's next](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#what-s-next).
- Add a third party content warning ahead of that list - see https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model for an example
- Ensure that the list of 3rd party tools is sorted alphabetically

**Why is this needed**
per the Kubernetes [content guide](https://kubernetes.io/docs/contribute/style/content-guide/) and [CNCF website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md), when we link to 3rd party tools we prefer to list them in alphabetical order.

**Comments**
/language en
/priority backlog
/help
/language en
/triage accepted

**Comment by chenxuc** [comment]
I can help this issue in next several days.
/assign

**Comment by sftim** [comment]
Done in #26676
/close
