### ISSUE TITLE
Translate reference/glossary/persistent-volume-claim.md in Korean

### ISSUE THREAD

**Issue by santachopa** [kubernetes/website#26669]
**This is a Feature Request**

**What would you like to be added**

Translate reference/glossary/persistent-volume-claim.md in Korean

**Why is this needed**
No translation reference/glossary/persistent-volume-claim.md in Korean

**Comments**

Page to update : https://kubernetes.io/ko/docs/reference/glossary/?core-object=true#term-persistent-volume-claim

**Comment by seokho-son** [comment]
Thank you!
/triage accepted
