### ISSUE TITLE
Issue with /docs/user-guide/kubeconfig-file/

### ISSUE THREAD

**Issue by eugene-chow** [kubernetes/website#2666]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The paragraph ends abruptly
> ## Building your own kubeconfig file
> In the above scenario, green-user would have to log in by providing certificates, whereas blue-user would just provide the token. All this information would be handled for us by the

**Proposed Solution:**
Complete the para

**Page to Update:**
https://kubernetes.io/docs/user-guide/kubeconfig-file/

**Comment by heidecke** [comment]
This document has been deprecated and the new content (https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) does not contain this reported issue.

Closing.
