### ISSUE TITLE
特性门控

### ISSUE THREAD

**Issue by yang199** [kubernetes/website#26672]
Beta 特性代表：

默认禁用。

应该是启用状态才对。

**Comment by ydcool** [comment]
/triage needs-information

@yang199  Would you point out which page is wrong?

**Comment by lsq645599166** [comment]
@ydcool maybe it's this page

https://kubernetes.io/zh/docs/reference/command-line-tools-reference/feature-gates/#%E7%89%B9%E6%80%A7%E9%98%B6%E6%AE%B5 

![屏幕快照 2021-03-03 下午2 17 47](https://user-images.githubusercontent.com/7345199/109762518-ac3c4100-7c2b-11eb-8f4b-ccc123cd2081.png)

**Comment by lsq645599166** [comment]
content/zh/docs/reference/command-line-tools-reference/feature-gates.md is out of date, so sync the zh version with en version first

/unassign
