### ISSUE TITLE
Add docs on kubeconfig parameters like proxy-url

### ISSUE THREAD

**Issue by cblecker** [kubernetes/website#26687]
There do not appear to be public facing docs for kubeconfig parameters like `proxy-url`, introduced in https://github.com/kubernetes/kubernetes/pull/81443.

also ref https://github.com/kubernetes/client-go/issues/351

/sig api-machinery cli

**Comment by sftim** [comment]
/kind feature
/triage accepted

Also see https://github.com/kubernetes/website/issues/23889

**Comment by cblecker** [comment]
/remove-lifecycle stale

@sftim Do you think this would be a good candidate for help-wanted or good-first-issue?

**Comment by sftim** [comment]
/help

This isn't a good-first-issue for SIG Docs. It might be a good first issue for someone who knows `client-go` and is looking to get more involved with documentation.

The reference could go alongside generated documentation within https://kubernetes.io/docs/reference/config-api/

**Comment by sftim** [comment]
/reopen

Oh, and I wouldn't count this as a good-first-issue, at least not as the issue description stands.

**Comment by tengqm** [comment]
This is revolved with the config API (https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/).
