### ISSUE TITLE
Troubleshoot Applications

### ISSUE THREAD

**Issue by pacsikaz** [kubernetes/website#26681]
In the 'My Service Missing Endpoints' sub-chapter containerPort is mentioned as Service parameter but in fact this should be changed to targetPort:

"If your **service** has a **_containerPort_** specified, but the Pods that are selected don't have that port listed, then they won't be added to the endpoints list.

Verify that the pod's containerPort matches up with the Service's targetPort"

Since Service object does not have containerPort, this should be fixed to targetPort.

**Comment by sftim** [comment]
As I understand it, this issue is about https://k8s.io/docs/tasks/debug-application-cluster/debug-application/

/kind bug
/language en
/triage accepted
