### ISSUE TITLE
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt is deprecated and 403 Forbidden

### ISSUE THREAD

**Issue by Xunzhuo** [kubernetes/website#26693]
**This is a Bug Report**

**Problem:**

In https://kubernetes.io/zh/docs/tutorials/services/source-ip/ 

![企业微信截图_20210224124727](https://user-images.githubusercontent.com/48784001/108949010-87315680-769e-11eb-9796-9cee2a01afd9.png)

http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt is deprecated and 403 Forbidden

**Proposed Solution:**

change it to https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

**Page to Update:**
https://kubernetes.io/zh/docs/tutorials/services/source-ip/

**Comment by tengqm** [comment]
Is the English version correct? We should fix the English version first.

**Comment by Xunzhuo** [comment]
> Is the English version correct? We should fix the English version first.

Ok I give a PR to fix the English Version

**Comment by Xunzhuo** [comment]
@tengqm Sir I have Synced with English Version! and I give a complete PR #26692
