### ISSUE TITLE
Update toc shortcode to allow different header levels

### ISSUE THREAD

**Issue by tomkivlin** [kubernetes/website#26706]
**What would you like to be added**

Currently, the `toc` shortcode (https://github.com/kubernetes/website/blob/master/layouts/shortcodes/toc.html) assumes a full H1/H2/H3 structure, meaning if you use it part-way through a page (e.g. at the top of a tab section) you need to use H1/H2 headers throughout that tab section, which can look odd.

e.g. if we did the following, today:
```
{{% toc %}}

# H1

## H2.1

## H2.2
```

Then the following ToC would be created:

- H1
  - H2.1
  - H2.2

However if we do this, today - e.g. for navigation within a tab:
```
{{% toc %}}

### H3.1

### H3.2

### H3.3
```

the result is:

-    - H3.1
      - H3.2
      - H3.3

**Why is this needed**

To improve the automation of ToCs.

**Comments**

https://github.com/kubernetes/website/pull/26682#issuecomment-785241393.

**Comment by prankul88** [comment]
Seems to me a valid issue
