### ISSUE TITLE
Improvement for k8s.io/zh/docs/tasks/network/validate-dual-stack/

### ISSUE THREAD

**Issue by hicker-kin** [kubernetes/website#26718]
if k8s-cluster has been installed, the certificate should be updated，too.

**Comment by sftim** [comment]
Hi @hicker-kin 

Do you know if the upstream page https://k8s.io/docs/tasks/network/validate-dual-stack/ (in English) also shows the defect you mention? It doesn't seem to mention certificates.

/triage needs-information
