### ISSUE TITLE
Terms "network solution" and "network add-on" should be unified.

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/website#26722]
**This is a Bug Report**

**Problem:**

There are words should be unified in [Troubleshooting kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/) and [Installing Addons](https://kubernetes.io/docs/concepts/cluster-administration/addons/).

For the sake of clarity, the same words should be used for things that have the same meaning.

**Proposed Solution:**

We should use either the terms "network solution" or "network add-on".

**Page to Update:**

- Troubleshooting kubeadm: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/
- Installing Addons: https://kubernetes.io/docs/concepts/cluster-administration/addons/

**Comment by neolit123** [comment]
modifying the kubeadm troubleshooting page to use "addon" instead of "solution" seems fine to me.
PRs welcome!

/help
/sig cluster-lifecycle
/kind cleanup
/priority backlog
