### ISSUE TITLE
Example: Deploying PHP Guestbook application with MongoDB

### ISSUE THREAD

**Issue by lamri000** [kubernetes/website#26732]
Hi All,
I noticed that the port of the service mongo  in mongo-service.yaml  is 27017 
spec:
  ports:
  - port: 27017
and when we display services by the command kubectl get svc the port is 6379.
mongo          ClusterIP   10.0.0.151   <none>        6379/TCP   8s
It should be the same because the tupe of the service is clusterIP, correct me please if I am wrong.

**Comment by oke-py** [comment]
The Example used redis as a database, which listens on port 6379.
The commit https://github.com/kubernetes/website/commit/99029b97d7c93373cf20e9609782428f107654c2 replaced redis with mongodb, and so, the port displayed by `kubectl get svc` should be modified to 27017, which mongodb uses.

**Comment by lamri000** [comment]
Ok, Thank you
Tarek

**Comment by jailton** [comment]
PR #27009 address this issue. 
/close
