### ISSUE TITLE
Label mismatch in “Exposing your app” tutorial

### ISSUE THREAD

**Issue by simonc6372** [kubernetes/website#26774]
the deployment created in your online environment has 
```
Labels:                 run=kubernetes-bootcamp
```
However, the deployment created when working along at home (I'm using docker desktop + kubernetes under WSL) creates a different labelset
```
Labels:                 app=kubernetes-bootcamp
```

Here is my version info. 
```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
``` 

Online, you're running 1.17, so I guess the default label name may have changed ?

**Comment by simonc6372** [comment]
this then of course also means the part of this leason that labels the pod with an `app` label doesn't work either.

**Comment by sftim** [comment]
/retitle Label mismatch in “Exposing your app” tutorial

**Comment by sftim** [comment]
@BenHall would you be willing to triage this? (also, we can add a label for the family of issues that involve Katacoda - would that help?)

I think updating the tutorial to Kubernetes v1.20 would address this.

**Comment by BenHall** [comment]
A label would be amazing!! 

I will also take a look at this, hopefully today if not tomorrow

**Comment by sftim** [comment]
/team katacoda

Let's see if Prow does this.

**Comment by BenHall** [comment]
@sftim I've created a Minikube 1.20 environment and currently testing the content to make sure it works as expected.

**Comment by BenHall** [comment]
We've upgraded the content to 1.20 so this should now be resolved.

**Comment by sftim** [comment]
@simonc6372 can you confirm this looks fixed for you?

**Comment by simonc6372** [comment]
I'll be honest, I won't have time to go back and check this. I have no problem for you to call this done.
