### ISSUE TITLE
Docker deprecation should be added on install site

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/website#26780]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime

**Comment by neolit123** [comment]
docker support is not deprecated in kubernetes. the built-in support for docker in the kubelet is deprecated and dockershim is being moved to a standalone binary:
https://github.com/kubernetes/enhancements/blob/9f27c895a38fd87134fe0902785dead31ed655bb/keps/sig-node/2221-remove-dockershim/README.md

once that is done we can change the sentence:
```
By default, kubeadm uses {{< glossary_tooltip term_id="docker" >}} as the container runtime.
The kubelet integrates with Docker through the built-in `dockershim` CRI implementation.
```

but this will be done later.

/close
/sig cluster-lifecycle

**Comment by sftim** [comment]
/reopen

The standalone binary story is not yet settled.

**Comment by sftim** [comment]
I think we _should_ clearly mention that deprecation.

**Comment by chrisnegus** [comment]
With the merge of [PR #32761](https://github.com/kubernetes/website/pull/32761) I'm closing this issue.
/close
