### ISSUE TITLE
Change callout from warning to caution

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#26785]
## What's the problem?

The page for [configuring liveness readiness startup probes](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md) incorrectly calls out waiting behavior as a warning rather than a caution.

For more information, see https://github.com/kubernetes/website/pull/26387#discussion_r570465052. 

## How can I fix it?

Change the callout for [this text](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md) to a caution instead of a warning:

```md
{{< warning >}}
Liveness probes do not wait for readiness probes to succeed. If you want to wait before executing a liveness probe you should use initialDelaySeconds or a startupProbe.
{{< /warning >}}
```

/sig docs

**Comment by zacharysarah** [comment]
As a reminder, anyone can open a pull request on an open issue, whether it’s assigned or not.

**Comment by caleb15** [comment]
It would also be good to change the text of the caution slightly - see https://github.com/kubernetes/website/pull/26387/files#r570464275
