### ISSUE TITLE
“Configure GMSA for Windows Pods and containers” page does not mention CoreDNS

### ISSUE THREAD

**Issue by marciogmorales** [kubernetes/website#26784]
Hello,
The documentation doesn't cover the CoreDNS piece. 

It is a requirement to have a forward zone inside CoreDNS to the domain FQDN, otherwise nltest.exe tests and gMSA use will fail as the container won't be able to do the name resolution.

Run: `kubectl -n kube-system edit configmap coredns`

and add as an example of the forward zone:

`   
 }

    DOMAIN-NAME:53 {
        errors 
        cache 30
        forward . custom-dns-server-IP1 custom-dns-server-IP2
        reload

    }
`

**Comment by sftim** [comment]
/retitle “Configure GMSA for Windows Pods and containers” page does not mention CoreDNS
/sig windows
