### ISSUE TITLE
Add GitHub issue label for Katacoda / tutorial issues

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#26797]
**This is a Feature Request**

**What would you like to be added**
Add a new label to this repo ([k/website](https://github.com/kubernetes/website/)) 
Implement this change via a pull request against https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml

**Why is this needed**
Using this label will help identify work that's relevant for people who look after Katacoda as a means to make tutorials work.

**Comments**
Mentioned in https://github.com/kubernetes/website/issues/26774#issuecomment-788926232

**Comment by kbhawkey** [comment]
👋 @sftim .
There is the  "team/katacoda" label?

**Comment by sftim** [comment]
We have that label; let's hook it up to Prow

 /retitle Labelling (via Prow) for Katacoda / tutorial issues

**Comment by mbbroberg** [comment]
Hey @sftim, I'm reviewing contributor-comms requests and saw this one. Do you need our help getting this message out to people? If so, happy to do so. If not, I'm not sure we're the right area of contribex to help.

**Comment by sftim** [comment]
PR: https://github.com/kubernetes/test-infra/pull/21652

**Comment by sftim** [comment]
Done
/close
