### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by nigelainscoe** [kubernetes/website#26802]
The # Output decoded secrets without external tools command:
`kubectl get secret my-secret -o go-template='{{range $k,$v := .data}}{{"### "}}{{$k}}{{"\n"}}{{$v|base64decode}}{{"\n\n"}}{{end}}'`

returns "`The system cannot find the path specified.`" when executed on Windows. Works fine on WSL Ubuntu

**Comment by sftim** [comment]
That looks like it should “just work” providing the quoting is correct.

@nigelainscoe what output do you get from `kubectl get secret my-secret -o json`? (please redact anything confidential!)
Also, what shell are you using?

/triage needs-information
(possibly /triage support)

**Comment by nigelainscoe** [comment]
I get what I expected, i.e. 

```
apiVersion: v1
data:
  key: aGVCbG=====================EU0VyMWM=
kind: Secret
metadata:
  creationTimestamp: "2021-03-05T11:03:25Z"
  labels:
    velero.io/backup-name: test-xxxxxx
    velero.io/restore-name: test-xxxx
  name: xxxx-xxxxxxx-key
  namespace: test-xxxxxxx
  resourceVersion: "18681715"
  selfLink: /api/v1/namespaces/test-xxxxxxxx/secrets/xxxxx-xxxxxxx-key
  uid: dfa3c277-908b-4320-8ea2-b2a41f6e2dd5
type: Opaque
```
The shell I'm using is cmdr which is just a wrapper for Windows command prompt

I also tried it with a PowerShell prompt which gives yet another different error: 
`error: error parsing template {{range $k,$v := .data}}{{###, template: output:1: unexpected "#" in command`

And again with PowerShell issuing a simple `kubectl get secret my-secret -o json` returns the expected base64 encoded secret.

**Comment by DanielHabenicht** [comment]
Did you find a solution @nigelainscoe ?

I've got the exact same issue, albeit through a different tool: 

Using `kubectl get secrets dev-values --kubeconfig ./.kubeconfig -o go-template='{{range $k,$v := .data}}{{printf \"%s: \" $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{\"\\n\"}}{{end}}'` in an npm script yields the same error. (NPM executes the command in windows command line, as well as I know) 

Executing the command on the powershell works flawlessly.

**Comment by sftim** [comment]
This might be a shell quoting issue. Maybe the cheat sheet entry could caution readers that the example uses POSIX shell quoting.

**Comment by DanielHabenicht** [comment]
@sftim for my part you are absolutley right, escaping mania:

```
kubectl get secret dev-values --kubeconfig ./.kubeconfig -o go-template='{{range $k,$v := .data}}{{printf \\\"%s: \\\" $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{\\\"\\n\\\"}}{{end}}'
```

I had to set `npm config set script-shell powershell` npm to execute in the powershell instead of commandline. 
Then NPM seems to unescape for the first time, then powershell for the second time and then kubectl takes over. :D

For why it does not work in the commandline. IDK, but there are multiple stackoverflows having issues with double and single quotes in cmd.

**Comment by DanielHabenicht** [comment]
For using commandline you just have to get rid of the single quotes: 
For NPM with Commandline:
```
kubectl get secrets indicarus-dev-values -o go-template=\"{{range $k,$v := .data}}{{printf \\\"%s: \\\" $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{\\\"\\n\\\"}}{{end}}\"
```
Directly on commandline:
```cmd
get secrets dev-values  -o go-template="{{range $k,$v := .data}}{{printf \"%s: \" $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{\"\\n\"}}{{end}}"
```

**Comment by nigelainscoe** [comment]
That fixes it. Please update the docs and you can close this issue.
