### ISSUE TITLE
cannot login mysql after run deployment:mysql

### ISSUE THREAD

**Issue by salanhess** [kubernetes/website#26819]
After  I follow https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/ 
all the steps,but can't get in mysql. error as following:

[root@bogon ~]# kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql -ppassword
Warning: Using a password on the command line interface can be insecure.
ERROR 2005 (HY000): Unknown MySQL server host 'mysql' (111)
[root@bogon ~]# 
[root@bogon ~]# kubectl get pods 
NAME                     READY     STATUS    RESTARTS   AGE
mysql-7d7fdd478f-kqv24   1/1       Running   0          7m

----------------
my env is : 
[root@bogon ~]# cat /etc/system-release
CentOS Linux release 7.6.1810 (Core)

**Comment by sftim** [comment]
@salanhess, GitHub is not the right place for support requests. However, I hope we can find a way to explain why this didn't work how you expected.

I suspect that your cluster doesn't have a working `kube-dns` application such as CoreDNS. The bug is that the page https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/ doesn't list working cluster DNS as a requirement not does it explain how to check.

Do you have any information about how you set up your cluster that might help us to confirm what's wrong?

**Comment by Kartik494** [comment]
Hi @salanhess i have tried this on my environment i found the given example work fine for me .
Could you tell me some insights of your cluster?

**Comment by Kartik494** [comment]
` kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-example -- mysql -h mysql -ppassword
`

`If you don't see a command prompt, try pressing enter.
`
But i found that my pod named mysql-example is been created and currently showing error state . i will let you know if i found some reasons failing pod.

`kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
`
`
mysql-68579b78bb-vdgv8           1/1     Running   0          6m55s
mysql-example                    0/1     Error     0          2m8s
`

**Comment by salanhess** [comment]
Hi all,
  Thx for your kind reply, 
1. I will discuss support requests  in other place like BBS later
2. This issue is related with my local minikube ENV. Because when I retry same steps on "https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/" every things works as expected.

pls close this issue.
thx.

**Comment by Kartik494** [comment]
Hi @salanhess yes maybe that is the case that you could not get the expected output. Closing this issue as your Response towards the comment.

Thanks

**Comment by Kartik494** [comment]
Hi @salanhess if you are fine with the solutions, you can close this issue
