### ISSUE TITLE
Link from concept explanation docs to api reference for objects

### ISSUE THREAD

**Issue by tippl** [kubernetes/website#26825]
**This is a Feature Request**

**What would you like to be added**
The concept explanation page should directly link to api reference page that explans all parameters that can be used in the object. For example [Pod](https://kubernetes.io/docs/concepts/workloads/pods/) docs page would directly link to the [Pod](https://kubernetes.io/docs/reference/kubernetes-api/workloads-resources/pod-v1/) object reference for quick direct lookup of allowed values and their descriptions.

**Why is this needed**
The concept section explans basic concepts in k8s, how to use them and how they work. However it does not explan what values are allowed to be used nor allowed values to be used (nor should it explain them). The api reference is not really indexed by Google, or i haven't managed to find the correct keywords to use. This feature would ease locating object reference without having to navigate the doc tree structure (Reference -> Kubernetes API -> Workloads Resources -> Pod).

**Comment by kbhawkey** [comment]
Related to https://github.com/kubernetes/website/pull/26151.

**Comment by sftim** [comment]
Let's make this an umbrella (tracking) issue, and create sub issues if we want to track groups of items.
/triage accepted
/remove-lifecycle stale
/language en

/priority backlog
(it's a nice idea, but there are others that are more valuable)
