### ISSUE TITLE
Adjust widths of documentation layout

### ISSUE THREAD

**Issue by toashok7** [kubernetes/website#26829]
This is the feedback for whole Kubernetes.io. The website provides 3 panes on screen. The right hand pane which provides options to edit the page is not at all required here. Because of this the whole Kubernetes website is not user friendly and readable. The right hand section should be removed to Menu. The width of left hand section with search feature and the Table of Content should be increased. This will make overall site much more readable and easy to read/navigate. 
I am not an expert in front end and it may be possible to configure the above changes at my end locally. If possible, please let me know the steps.

**Comment by sftim** [comment]
Thanks for that feedback.

/retitle Adjust widths of documentation layout


@toashok7 perhaps a screenshot of how the site appears when you're viewing it would help give context?

/area web-development
/priority awaiting-more-evidence

**Comment by sftim** [comment]
@toashok7 this website uses the [Docsy](https://www.docsy.dev/) theme; it might make sense to request this as a Docsy feature rather than specifically as a Kubernetes customization to Docsy.
