### ISSUE TITLE
“Use Port Forwarding to Access Applications in a Cluster” refers to missing manifests

### ISSUE THREAD

**Issue by hot3eed** [kubernetes/website#26836]
[Deployment and Service](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#creating-redis-deployment-and-service) links are dead.

**Comment by sftim** [comment]
Thanks @hot3eed 

/kind bug
/priority important-longterm
/language en
/triage accepted

/retitle “Use Port Forwarding to Access Applications in a Cluster” refers to missing manifests
I think we should find the replacement example manifests and update the [task](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#creating-redis-deployment-and-service)

**Comment by RA489** [comment]
@hot3eed raised the PR #27024 please check if it works for you?

**Comment by hot3eed** [comment]
@RA489 Yes, the links are good now.
