### ISSUE TITLE
Tutorial module not rendering on "Interactive Tutorial - Creating a Cluster"

### ISSUE THREAD

**Issue by shelbyspees** [kubernetes/website#26844]
Interactive tutorial module not rendering
- Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)
- MacOS Version 11.1 (20C69)

![screenshot of Creating a Cluster page](https://user-images.githubusercontent.com/5217772/110011149-f4af3980-7cd3-11eb-8f9d-6cc663e90832.png)

I'm not a browser dev but I copied this out of the Chrome devtools console:

```console
www.googletagmanager.com/gtag/js?id=UA-36037335-10:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
embed.js:1 Failed to load resource: the server responded with a status of 403 ()
vendor.js:2 Failed to authenticate user, ingestitron will use last known user session
DevTools failed to load SourceMap: Could not load content for https://kubernetes.io/js/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://kubernetes.io/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Seems to be behaving the same way in other modules as well. Let me know if there's anything else you need from me to reproduce.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ works OK for me.

@shelbyspees are you still seeing these symptoms?
/priority awaiting-more-evidence

**Comment by shelbyspees** [comment]
@sftim Yep, reproduced in Chrome and Safari Version 14.0.2 (16610.3.7.1.9). I asked a friend to open the page and he has the same issue in Firefox 86.0 (64-bit) on macOS 11.2.1.

**Comment by shelbyspees** [comment]
It's working for me now so I'll go ahead and close this ticket.
