### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by aslom** [kubernetes/website#26846]
Replace dockerconfigjson with dockerconfig:

```
kubectl get secret regcred --output="jsonpath={.data.\.dockerconfig}" | base64 --decode
```

instead of

```
kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode
````

**Comment by sftim** [comment]
Hi @aslom 

To help people work on this issue, can you outline why we should make the change you suggest?

**Comment by aslom** [comment]
Somehow my setup had .dockerconfig and not .dockerconfigjson

I tried to reproduce it and when i create new secret docker-registry it is .dockerconfigjson

So closing it
