### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by softforte** [kubernetes/website#26845]
Interactive tutorial doesn't open up

**Comment by sftim** [comment]
I suspect this is fixed. @softforte are the symptoms still present?
/priority awaiting-more-evidence

**Comment by softforte** [comment]
I checked from different machines under the same public IP address last night - had the same problem. It all worked once I used a different public IP address. Will try again today.
Thank you.
-I.

**Comment by sftim** [comment]
/close
I'm assuming this is OK.
