### ISSUE TITLE
Access Clusters Using the Kubernetes API

### ISSUE THREAD

**Issue by iam-veeramalla** [kubernetes/website#26843]
Link broken or pointing to a wrong link.

Under section:
Programmatic access to the API.  The link provided in the below line seems to be broken to wrong.
```
If the application is deployed as a Pod in the cluster, see Accessing the API from within a Pod.
```

**Comment by sftim** [comment]
I think this report is about the page https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

@iam-veeramalla can you paste in the text (or HTML source) of the broken hyperlink


/triage needs-information
