### ISSUE TITLE
ja: Make docs/concepts/architecture/cloud-controller.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26853]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/architecture/cloud-controller.md to follow v1.18 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/architecture/cloud-controller.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/architecture/cloud-controller.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/architecture/cloud-controller.md

diff between translated and v1.18
https://gist.github.com/063645c1479175eb5844a885e836e8d0

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by kbhawkey** [comment]
Hi @inductor .
Just saw a number of issues opened for the `ja` localization team. What do you think about opening one issue or several issues that serve as an umbrella issue? How do other localization teams organize their work items?

**Comment by inductor** [comment]
It was based on automated scripts and we don't have regulations for creating umbrella issues yet. I guess we can bring this up at the next localization subgroup meeting as a topic.

**Comment by inductor** [comment]
Oh I just realised what you meant. We have milestones. So for managing items we have no problems with that.

**Comment by kbhawkey** [comment]
> 
> 
> @kbhawkey It was based on automated scripts and we don't have regulations for creating umbrella issues yet. I guess we can bring this up at the next localization subgroup meeting as a topic.

Hi @inductor .
I don't think it is a good idea to generate issues automatically per localization. This has the effect of spamming the issues lists.
Before doing this, did you run this process/idea by the SIG Docs group?
/cc @kubernetes/sig-docs-en-owners

**Comment by sftim** [comment]
If using automation to file issues, I agree, open an umbrella issue.

It'd also be OK to use automation to mark a specific item from that umbrella issue as _in progress_, because that is simply removing toil from an otherwise manual step.
