### ISSUE TITLE
ja: Make docs/concepts/containers/runtime-class.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26865]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/containers/runtime-class.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/containers/runtime-class.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/containers/runtime-class.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/containers/runtime-class.md

diff between translated and v1.19
https://gist.github.com/ec82eac56ea84abe575db1408ab0b4c1

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
@hase1128 こちらいかがでしょうか！

**Comment by hase1128** [comment]
これから対応しますね。
