### ISSUE TITLE
ja: Make docs/concepts/overview/working-with-objects/annotations.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26873]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/overview/working-with-objects/annotations.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/overview/working-with-objects/annotations.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/overview/working-with-objects/annotations.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/overview/working-with-objects/annotations.md

diff between translated and v1.19
https://gist.github.com/7dd41504319804755cc40dc0a1c2dada

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by s-ito-ts** [comment]
@inductor
> diff between translated and v1.19
> https://gist.github.com/7dd41504319804755cc40dc0a1c2dada

The diff is changing single quote (using ASCII single quote) and removing extra blank characters.
These are not included in the Japanese text.
The Japanese text is the same content as the original text.
So I think we can close this issue.

**Comment by inductor** [comment]
@s-ito-ts thanks
