### ISSUE TITLE
ja: Make docs/concepts/policy/resource-quotas.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26878]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/policy/resource-quotas.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/policy/resource-quotas.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/policy/resource-quotas.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/policy/resource-quotas.md

diff between translated and v1.19
https://gist.github.com/5c61b115c1eb0f8adda192435bb1b2a3

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
@s-kawamura-w664 こちらいかがでしょうか！

**Comment by s-kawamura-w664** [comment]
@inductor 最終確認中で今週中にはPRできる見込みです。

**Comment by s-kawamura-w664** [comment]
@inductor 
May I ask you a question?

resource-quotas.md has the link to following.:
  /docs/concepts/configuration/pod-priority-preemption

Master branch has Japanese translations (#26935), but not dev-1.19-ja.1 branch.
Is it OK that I change /ja/docs the link on resource-quotas.md in dev-1.19-ja.1 branch?

**Comment by inductor** [comment]
@s-kawamura-w664 You can ignore that translation for now, because we are also planning to merge this into 1.19 release branch.
We will take care of it later.
