### ISSUE TITLE
ja: Make docs/concepts/services-networking/endpoint-slices.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26888]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/services-networking/endpoint-slices.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/services-networking/endpoint-slices.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/services-networking/endpoint-slices.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/services-networking/endpoint-slices.md

diff between translated and v1.19
https://gist.github.com/829064d79af0839e4cb7e15036a07499

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by inductor** [comment]
@KobayashiD27 こちらいかがでしょうか！

**Comment by KobayashiD27** [comment]
@inductor  まだまだ途中の状態ですが、急いだほうがよろしいでしょうか？　締め切りなどありましたら教えてください。

**Comment by inductor** [comment]
急ぎというわけではないですが、そろそろマージできそうなくらいに他のPRも片付いてきたのと1週間くらい経過したのでPing慕って感じです！

**Comment by KobayashiD27** [comment]
了解しました。ご連絡ありがとうございます！

**Comment by atoato88** [comment]
/close
PR #27777 has merged.
I close this issue.
