### ISSUE TITLE
ja: Make docs/concepts/services-networking/connect-applications-service.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26885]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/services-networking/connect-applications-service.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/services-networking/connect-applications-service.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/services-networking/connect-applications-service.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/services-networking/connect-applications-service.md

diff between translated and v1.19
https://gist.github.com/8480dbb9b45996108af9f82e22ee5cd8

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by s-kawamura-w664** [comment]
@inductor @nasa9084
Hello,
I checked the modification in this issue.
In English, this was changed the code of apostrophe of "machine's".
I don't think it has any effect in Japanese and don't need to update.

Please check.
And if there is anything I can help, please contact me.

**Comment by inductor** [comment]
@s-kawamura-w664

That seems right! Thank you for your review.

/close
