### ISSUE TITLE
ja: Make docs/concepts/security/pod-security-standards.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26884]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/security/pod-security-standards.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/security/pod-security-standards.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/security/pod-security-standards.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/security/pod-security-standards.md

diff between translated and v1.19
https://gist.github.com/df3b235f34e342165b6fdfd2d4ac7ccd

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by shuuji3** [comment]
確認してみたのですが、すでにv1.19より新しいバージョンのドキュメントが #24961 で新規翻訳されていたため、この更新は必要なさそうでした。
/close

**Comment by shuuji3** [comment]
closeお願いします🙏
