### ISSUE TITLE
ja: Make docs/concepts/storage/dynamic-provisioning.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26893]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/storage/dynamic-provisioning.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/storage/dynamic-provisioning.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/storage/dynamic-provisioning.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/storage/dynamic-provisioning.md

diff between translated and v1.19
https://gist.github.com/8e565951460a72f9e9a4b6211ec8326b

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by KobayashiD27** [comment]
diffの上の部分は特に変更はないと思います。
diffの下の部分はすでに`PersistentVolumeClaim`になっていました。
