### ISSUE TITLE
ja: Make docs/concepts/services-networking/ingress.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26890]
**This is a Feature Request**

**What would you like to be added**
Update docs/concepts/services-networking/ingress.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/concepts/services-networking/ingress.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/services-networking/ingress.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/services-networking/ingress.md

diff between translated and v1.19
https://gist.github.com/496deaaf9c91fa3a2836e6409b17bcb1

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by sftim** [comment]
Duplicated by issue #27457
