### ISSUE TITLE
Debian/Ubuntu Apt installation instructions should install package signing keys to /usr/share/keychain

### ISSUE THREAD

**Issue by tmoschou** [kubernetes/website#26906]
The current installation instructions for installing the third party Kubernetes Apt repository on Debian/Ubuntu, goes against best security practice.

Currently the signing keys are added to `/etc/apt/trusted.gpg`.

The keychain should be downloaded to `/usr/share/keyrings/cloud.google.gpg` (file name to match the name used in https://cloud.google.com/sdk/docs/install#deb) using `curl` or `wget` (not `add-keys` as this is deprecated and will be last available in Debian 11 and Ubuntu 22.04) and referred to in `/etc/apt/sources.list.d/kubernetes.list` as such
```
deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
```

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

References:

- https://wiki.debian.org/DebianRepository/UseThirdParty
- https://github.com/docker/docker.github.io/issues/11625#issuecomment-751388087

**Comment by neolit123** [comment]
@tmoschou 
i read the linked pages and this change seems valid. thank you for bringing this up.
would you help us by sending a PR for that?

/sig cluster-lifecycle

**Comment by tmoschou** [comment]
@neolit123 Please see https://github.com/kubernetes/website/pull/26952
