### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by nkulinichev** [kubernetes/website#26909]
Interactive tutorial Katacoda doesn't work since 4 of March 2021
![image](https://user-images.githubusercontent.com/22022293/110089866-ab301e80-7da7-11eb-947f-0a0729622e3f.png)

https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

**Comment by sftim** [comment]
@BenHall There have been a few similar reports 

The page works fine for me.

**Comment by BenHall** [comment]
@sftim It looks like our security script had a false positive on the last couple of days. I've cleared the list and updated a script so everyone should be able to access the platform again.

@nkulinichev  Sorry for the problem. It should now be fixed but if you are still having issues please let me know.
