### ISSUE TITLE
ja: Make docs/contribute/suggesting-improvements.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26904]
**This is a Feature Request**

**What would you like to be added**
Update docs/contribute/suggesting-improvements.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/contribute/suggesting-improvements.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/contribute/suggesting-improvements.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/contribute/suggesting-improvements.md

diff between translated and v1.19
https://gist.github.com/437eaafe2d550efc8fd9a7369a2b8fa1

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by ffjlabo** [comment]
I'm sorry if I misunderstood but it seems that this diff has already been translated in https://github.com/kubernetes/website/pull/23891.

**Comment by inductor** [comment]
Oh yeah, it looks like it was already translated in the latest revision. Thank you for pointing it out! @ffjlabo

/close
