### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by sylvainlaurent** [kubernetes/website#2690]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
layout of the site is totally broken on iPad (and on Safari if window is not wide enough)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/

**Comment by zacharysarah** [comment]
@sylvainlaurent Thanks for opening this issue. I've tagged it for the UI team's investigation.

**Comment by BenHall** [comment]
Thanks for the feedback on this. We've made some UI layout changes to improve the tablet support. If you have any other suggestions then please let us know.

/close
