### ISSUE TITLE
ja: Make docs/contribute/_index.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#26903]
**This is a Feature Request**

**What would you like to be added**
Update docs/contribute/_index.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/contribute/_index.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/contribute/_index.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/contribute/_index.md

diff between translated and v1.19
https://gist.github.com/7a7f4f26df56b52b4cd65ece764700a5

**Note**
Currently, we use **dev-1.19-ja.1** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel.

**Comment by atoato88** [comment]
/close
PR #27081 which fixes this issue has merged now.
I close this issue.
