### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

### ISSUE THREAD

**Issue by ZillaG** [kubernetes/website#26914]
Cool article for newbies like me trying to learn HPA. One suggestion is to have a sample manifest file with ALL the possible metrics and behaviors that one can use for scale up and scale down.

**Comment by sftim** [comment]
It's a good suggestion

I think this is subsumed into issue #4493, to be honest. I'd prefer to track the work in #4493 @ZillaG
