### ISSUE TITLE
Clarify concept section: Updating a Deployment

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#26923]
**This is a Bug Report**

Investigate updating the concept section [Updating a Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment).
Specifically, the sub section on rolling over a Deployment.

**Problem:**
The section on `Rollover (aka multiple updates in-flight)` is confusing and should describe clearly the conditions required
to scale up or down. The section includes rollover rollouts, scaling, ReplicaSets, Pods, labels, and Deployments.

**Proposed Solution:**
Clarify the "Updating Deployment" section. Rewrite this section to clearly describe the labels and scaling.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

**Comment by sftim** [comment]
/sig apps
/kind cleanup
/triage accepted
/language en
/priority backlog

(feel free to raise this priority - this is just my guess)

**Comment by sftim** [comment]
I would be fine if that section moved into Tasks; it's also OK to leave it where it is.
