### ISSUE TITLE
i18n changes approvable by sig-localization teams

### ISSUE THREAD

**Issue by raelga** [kubernetes/website#26921]
**What would you like to be added**

Currently, i18n files live under [/i18n](https://github.com/kubernetes/website/tree/master/i18n) at the root folder and only sig-docs-en-owners can approve those files. Under the `i18n` folder resides the toml files containing localised strings for each language used across the site. It would be nice to add some mechanism to enable sig-docs-localisation approvers permission to approve changes on their language toml files.

**Why is this needed**

This will enable better handling of the i18n language files as will be owned by the corresponding localization team and instead of failing to the sig-docs-en team.

**Comments**

This was discussed on the last _sig-docs_ and _sig-docs-localization_ meetings.

/area web-development
/kind feature
/sig docs
/language en
/language es

**Comment by sftim** [comment]
/remove-language en
/remove-language ko
/remove-language es
as this would be a generic mechanism

**Comment by kbhawkey** [comment]
This seems like a good idea.

**Comment by sftim** [comment]
If #27408 merges, we can additionally configure `blockades` (a [Prow plugin](https://prow.k8s.io/plugins)) to restrict who is able to change the original `i18n` directory.
