### ISSUE TITLE
Pod in pending state. Unbound persistent volume claims

### ISSUE THREAD

**Issue by Yasaswini2105** [kubernetes/website#26943]
Hi,

I am using 3 t2.medium EC-2 instances(1 master and 2 worker nodes) My hub pod is in pending state.

**When I describe the pod it gives the following error**
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  55s (x11 over 11m)  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.  

**kubectl describe pvc hub-db-dir -n jhub** gives no persistent volumes available for this claim and no storage class is set

Name:          hub-db-dir
Namespace:     jhub
StorageClass:
Status:        Pending
Volume:
Labels:        app=jupyterhub
               app.kubernetes.io/managed-by=Helm
               chart=jupyterhub-0.10.6
               component=hub
               heritage=Helm
               release=jhub
Annotations:   meta.helm.sh/release-name: jhub
               meta.helm.sh/release-namespace: jhub
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    hub-5b8d96f64b-qk86l
Events:
  Type    Reason         Age                      From                         Message
  ----    ------         ----                     ----                         -------
  Normal  FailedBinding  3m23s (x782 over 3h18m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

My default storage class is gp-2. 

Can anyone please guide me with how to set storage class and volumes for hub-db-dir pvc

**Comment by RA489** [comment]
@Yasaswini2105 Did you checked your PV has sufficient resource the PVC has requested and access modes matched?

**Comment by Yasaswini2105** [comment]
> @Yasaswini2105 Did you checked your PV has sufficient resource the PVC has requested and access modes matched?
Thank you for the reply, I have checked them and they are matched. Can you please provide me proper documentation to set dynamic volume provisioning in bare metal if possible?

**Comment by RA489** [comment]
@Yasaswini2105 Please check here https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
