### ISSUE TITLE
No longer to install kubectl using powershell from PSGallery

### ISSUE THREAD

**Issue by svallier** [kubernetes/website#26956]
**This is a Bug Report**
Since 3/4 days, we are no longer able to deploy kubectl using the install-kubectl script from PSGallery as described in documentation --> https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-with-powershell-from-psgallery

**Problem:**

**script installation --> **### OK****
##[debug]Using the provider 'PowerShellGet' for searching packages.
##[debug]The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
##[debug]Getting the provider object for the PackageManagement Provider 'NuGet'.
##[debug]The specified Location is 'https://www.powershellgallery.com/api/v2/items/psscript' and PackageManagementProvider is 'NuGet'.
##[debug]Searching repository 'https://www.powershellgallery.com/api/v2/items/psscript/FindPackagesById()?id='install-kubectl'' for ''.
##[debug]Total package yield:'1' for the specified package 'install-kubectl'.
##[debug]The installation scope is specified to be 'CurrentUser'.
##[debug]The specified script will be installed in 'C:\Windows\ServiceProfiles\NetworkService\Documents\WindowsPowerShell\Scripts' and its dependent modules will be installed in 'C:\Windows\ServiceProfiles\NetworkService\Documents\WindowsPowerShell\Modules'.
##[debug]The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
##[debug]Downloading script 'install-kubectl' with version '1.7' from the repository 'https://www.powershellgallery.com/api/v2/items/psscript'.
##[debug]Searching repository 'https://www.powershellgallery.com/api/v2/items/psscript/FindPackagesById()?id='install-kubectl'' for ''.
##[debug]InstallPackage' - name='install-kubectl', version='1.7',destination='C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\1499304682'
##[debug]DownloadPackage' - name='install-kubectl', version='1.7',destination='C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\1499304682\install-kubectl\install-kubectl.nupkg', uri='https://www.powershellgallery.com/api/v2/package/install-kubectl/1.7.0'
##[debug]Downloading 'https://www.powershellgallery.com/api/v2/package/install-kubectl/1.7.0'.
##[debug]Completed downloading 'https://www.powershellgallery.com/api/v2/package/install-kubectl/1.7.0'.
##[debug]Completed downloading 'install-kubectl'.
 ##[debug]Hash for package 'install-kubectl' does not match hash provided from the server.
##[debug]Script 'install-kubectl' was installed successfully to path ****
install-Script -Name 'install-kubectl' -Scope CurrentUser -Force

**script execution** --> **### KO**
==>Getting download link from  https://kubernetes.io/docs/tasks/tools/install-kubectl/
==>analyzing Downloadlink
==>starting Download from  using Bitstransfer
Cannot validate argument on parameter 'Source'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

**detected issue** 
The content of the Uri _https://kubernetes.io/docs/tasks/tools/install-kubectl/_ seems modified few days ago. the script install-kubectl.ps1 is no longer able to get the download link because there is no href matching the executable

try
    {
        Write-Host -ForegroundColor White "==>analyzing Downloadlink"   
        $downloadlink = ($req.Links | **where href -Match "kubectl.exe"**).href
    }
catch
    {
    Write-Warning "Error Parsing Link"
    Break
    }

**Proposed Solution:**
Add the necessary href or change the match value 

ALL

**Comment by sftim** [comment]
Honestly, I think that's a bug in the PSGallery script.

We can fix this by removing the section https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-with-powershell-from-psgallery
The Kubernetes project does not maintain that script. We should remove the link to it.
/sig windows

**Comment by sftim** [comment]
Related, I think https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-on-windows-as-part-of-the-google-cloud-sdk is also not something we'd link to based on the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/).

**Comment by sftim** [comment]
@svallier, thanks for mentioning this!

**Comment by svallier** [comment]
I don't think removing the section https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-with-powershell-from-psgallery is the solution.

many customers already have automated kubectl installation using this method (including me ^^)

Can you put back the downloadLink ?
$downloadlink = ($req.Links | where href -Match "kubectl.exe").href

**Comment by sftim** [comment]
> Can you put back the "kubectl.exe" downloadLink ?

The documentation for Kubernetes is *not* a stable API and Kubernetes makes **no** guarantee about the format of documentation. 
It's OK if that tool wants to work out a better way to find a download link. In fact, I recommend it.
As the Kubernetes project does not maintain that script, we should remove the link to it - it's unhelpful to users to give the impression that that tool is considered secure.

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/27179

**Comment by DanielW10001** [comment]
Change Installation Script `install-kubectl.ps1` Line 29:
```ps1
$uri = "https://kubernetes.io/docs/tasks/tools/install-kubectl/"
```
To:
```ps1
$uri = "https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/"
```
Would resolve this issue.
Because download link to kubectl.exe is no longer at the previous page.

**Comment by eddiezane** [comment]
Package managers are considered out of scope as the Kubernetes org just provides binaries and relies on the community to handle distribution past that.

If the documentation here is out of date I think we should remove it to avoid confusion.

If someone fixes or creates a new installation script for PSGallery we could easily add it back.

@sftim I can open a PR - thoughts?

**Comment by eddiezane** [comment]
It looks like the [current PSGallery script](https://www.powershellgallery.com/packages/install-kubectl/1.7/Content/install-kubectl.ps1) was just grabbing a link with `kubectl.exe` from the docs. Definitely not a reliable way to handle installation.

If anyone wants to make a new script it should rely on something like https://downloadkubernetes.com/ or rely on https://storage.googleapis.com/kubernetes-release/release/stable.txt to grab https://storage.googleapis.com/kubernetes-release/release/v1.20.5/kubernetes-client-windows-amd64.tar.gz.

**Comment by sftim** [comment]
> If the documentation here is out of date I think we should remove it to avoid confusion.

:+1:
If, later, there's a replacement script, it'd be even better for that tool to live in-project. Inside https://github.com/kubernetes-sigs/ perhaps?

**Comment by jsturtevant** [comment]
Thanks for taking care of this.

> If, later, there's a replacement script, it'd be even better for that tool to live in-project. Inside https://github.com/kubernetes-sigs/ perhaps?

https://github.com/kubernetes-sigs/sig-windows-tools would be a good place so it can be updated by sig-windows members
