### ISSUE TITLE
Broken hyperlink in Feature Gates list

### ISSUE THREAD

**Issue by panyis** [kubernetes/website#26967]
**This is a Bug Report**

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ —>

SizeMemoryBackedVolumes: Enables kubelet support to size memory backed [volumes](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/docs/concepts/storage/volumes). See volumes for more details.

“https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/docs/concepts/storage/volumes”

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/docs/concepts/storage/volumes

**Problem:** 
death link

**Proposed Solution:**
update to new link

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by sftim** [comment]
I hope it's OK to:
/retitle Broken hyperlink in Feature Gates list
/language en
/kind bug

The link to `docs/concepts/storage/volumes` should instead link to `/docs/concepts/storage/volumes`
/triage accepted
/help

**Comment by PI-Victor** [comment]
thanks for tracking it @jai!
