### ISSUE TITLE
[zh] translate "feature gate - beta: Enabled by default instead of Disabled"

### ISSUE THREAD

**Issue by ShirleyFei** [kubernetes/website#26968]
Original English:
A Beta feature means:
Enabled by default.
⁣
Current wrong Chinese translation:
Beta 特性代表：
默认禁用。
⁣
⁣Supposed correct Chinese translation:
⁣Beta 特性代表：
默认启用。

**Comment by tengqm** [comment]
This is being fixed in #26319

**Comment by tengqm** [comment]
I'm closing this because it is no longer an outstanding issue to fix.
/close
