### ISSUE TITLE
Horizontal Pod Autoscaler: Describe metrics query frequency 

### ISSUE THREAD

**Issue by mcristina422** [kubernetes/website#26962]
**What would you like to be added**
An explanation on how frequently the metrics api is queried for an HPA. We use an external metrics adapter that has timeout errors with the external backend due to congestion 

I assume the metrics API is only queried at most every period and the default would be 15s https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior

The workqueue may be ran faster which is why I am uncertain 

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis

**Why is this needed**
This will clarify for cluster operators as well as external metrics provider maintainers best practices 

**Comments**

**Comment by sftim** [comment]
/language en

Thanks for the suggestion @mcristina422
