### ISSUE TITLE
K8s Secrets for .keytab file 

### ISSUE THREAD

**Issue by aushafy** [kubernetes/website#26971]
Hi everyone, I have an issue while storing .keytab file to Kuberntes secret or someone can explain which best practice to store keytab file for our application which is using kerberos authentication ?

**Comment by sftim** [comment]
I think the existing page at https://kubernetes.io/docs/concepts/configuration/secret/#overview-of-secrets does cover this fairly well. https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/ is also relevant.

We wouldn't add documentation specifically about how to integrate with Kerberos - but that might make a good blog article somewhere on the web! 

/kind support

**Comment by aushafy** [comment]
oh ya well thanks, i got this https://stackoverflow.com/questions/60034755/kubernetes-kerberos-and-kafka-secret-setup-using-helm
