### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by jimblizzard** [kubernetes/website#26972]
It would be extremely helpful if the course material were also available outside the interactive tutorial environment. This would make it much easier to review the material later. As it is now, returning to the material to review it requires going page by page through the tutorial once again, which is very clumsy for that purpose. Thanks!

**Comment by sftim** [comment]
/kind feature
Thanks for the suggestion @JimBlizzard 

I suspect it's not very particularly easy to make what you want happen, but I can see why you'd find it useful.
