### ISSUE TITLE
main build failing due to time out initializing value

### ISSUE THREAD

**Issue by annajung** [kubernetes/website#26974]
**This is a Bug Report**

**Problem:**
based on the netlify logs https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/60479d2ebad59b0008300815, main build started to fail after https://github.com/kubernetes/website/commit/8698adf5895feee319935273dfd753abf4802f6d merged

```
10:07:54 AM: ────────────────────────────────────────────────────────────────
10:07:54 AM:   1. build.command from netlify.toml                            
10:07:54 AM: ────────────────────────────────────────────────────────────────
10:07:54 AM: ​
10:07:54 AM: $ git submodule update --init --recursive --depth 1 && make production-build
10:07:54 AM: hugo --minify
10:07:55 AM: Start building sites …
10:08:10 AM: Total in 15907 ms
10:08:10 AM: Error: Error building site: "/opt/build/repo/content/en/blog/_posts/2021-03-09-The-Evolution-of-Kubernetes-Dashboard/index.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
10:08:10 AM: Makefile:27: recipe for target 'build' failed
10:08:10 AM: make: *** [build] Error 255
```

**Proposed Solution:**
see https://github.com/kubernetes/website/issues/26974#issuecomment-794619244

**Page to Update:**
https://kubernetes.io/...
Not sure if the build is failing due to `/opt/build/repo/content/en/blog/_posts/2021-03-09-The-Evolution-of-Kubernetes-Dashboard/index.md` but error from the build log seems to point to the page.

**Comment by annajung** [comment]
it looks like it's related to the images added in the blog, it's causing it to time out because the build is taking longer. 

possible solutions are 
- increase the timeout https://github.com/kubernetes/website/blob/fbff88f16a049484c5db9fccb6166bb2cd1e8296/config.toml#L18
- change the size of image(?) or how the image is being referenced https://github.com/kubernetes/website/blob/master/content/en/blog/_posts/2021-03-09-The-Evolution-of-Kubernetes-Dashboard/index.md
```
{{< imgproc first-ui Fit "1000x900" >}} The First Version of the User Interface {{< /imgproc >}}
```
maybe specifying 1000x900 is not the best way?

I think maybe someone with more experience with hugo can give feedback?

**Comment by kbhawkey** [comment]
👀

**Comment by kbhawkey** [comment]
@annajung . I removed the images in the blog page. I would not change the timeout without digging into the image processing.

**Comment by annajung** [comment]
Closing this issue 
- The main build failing has been resolved by removing the images from the blog https://github.com/kubernetes/website/pull/26975
- A new issue was also created to restore images https://github.com/kubernetes/website/issues/27004

/close
