### ISSUE TITLE
Improvement for k8s.io/docs/home/supported-doc-versions/

### ISSUE THREAD

**Issue by jiaoyan2017** [kubernetes/website#26984]
Where can I find the documents for upgrade from 1.12 to 1.13, and the later.

**Comment by Kartik494** [comment]
Hi @jiaoyan2017 if you are looking for k8s.io docs changes there is column ink8.io reagrding this . You could check on this  [versions](https://v1-19.docs.kubernetes.io/)

**Comment by Kartik494** [comment]
There is a kubernetes release cycle for the same if you want to take a look on that https://github.com/kubernetes/kubernetes/releases

**Comment by sftim** [comment]
Kubernetes documentation for v1.13 is no longer served.
/kind support
