### ISSUE TITLE
Recommended app labels missing from Well-Known Labels, Annotations and Taints

### ISSUE THREAD

**Issue by finkr** [kubernetes/website#26989]
The page [labels-annotations-taints.md](https://github.com/kubernetes/website/edit/master/content/en/docs/reference/labels-annotations-taints.md) does not mention `app.kubernetes.io` labels, listed on the page [concepts/overview/working-with-objects/common-labels/](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/).

**Comment by sftim** [comment]
The trivial (and still useful approach) is to have https://kubernetes.io/docs/reference/labels-annotations-taints/ hyperlink to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

We can do that and then later look at merging the two pages.

**Comment by sftim** [comment]
Thanks @finkr

/kind cleanup
/language en
/triage accepted
/priority backlog

**Comment by sftim** [comment]
/retitle Recommended app labels missing from Well-Known Labels, Annotations and Taints
/kind bug
/lifecycle frozen

**Comment by rajatgupta24** [comment]
Hey @sftim, should I change the hyperlink of https://kubernetes.io/docs/reference/labels-annotations-taints/ to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by sftim** [comment]
The page to change is [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/).

We should edit [that page](https://github.com/kubernetes/website/edit/main/content/en/docs/reference/labels-annotations-taints.md) so that it mentions the `app.kubernetes.io` labels that are already listed at https://docs.k8s.io/concepts/overview/working-with-objects/common-labels/#labels

**Comment by jai** [comment]
@sftim do you mean add new/additional sections for [the common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) in the [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) by adding sections/blocks for each of the common labels? 

[The common labels page](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels) has 7 labels, so we'd add 7 blocks?

![Google Chrome Well-Known Labels, Annotations and Taints | Kubernetes2021-11-30 at 22 03 28](https://user-images.githubusercontent.com/1943284/144072067-8ee83bdb-98b9-465a-ac83-75ec4df04da7.png)

**Comment by sftim** [comment]
> do you mean add new/additional sections for the common labels in the Well-Known Labels, Annotations and Taints by adding sections/blocks for each of the common labels?

That is what I mean, yes. There would be an extra heading and block for each of the 7 missing labels.

**Comment by jai** [comment]
Sorry it's been so long 😂

FYI @sftim 

Updated page: https://deploy-preview-32923--kubernetes-io-main-staging.netlify.app/docs/reference/labels-annotations-taints/
