### ISSUE TITLE
Link should be correct for v1.19 

### ISSUE THREAD

**Issue by Tej-Singh-Rana** [kubernetes/website#26987]
**This is a Request**

**Link:** https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#before-you-begin

**What would you like to be added**
In the 4th point of **before you begin** section, In release notes need correction, it should be for v1.19 instead of v1.20.   

**Why is this needed**
Because information available for v1.19. 

**Comments**
None

**Comment by neolit123** [comment]
/sig docs cluster-lifecycle

can we have some sort of a veriable that allows us to point to the release notes of the relevant release?
e.g. `$RELEASE_NOTES_LINK`

**Comment by rajpratyush** [comment]
> can we have some sort of a variable that allows us to point to the release notes of the relevant release?

> e.g. $RELEASE_NOTES_LINK

Can you provide guidance on this ? @neolit123

**Comment by neolit123** [comment]
the k/website maintainers would know what is best for such a variable / link.

**Comment by neolit123** [comment]
tracked here:
https://github.com/kubernetes/website/issues/26987

as an general problem for older release branches of k/website.

/close
