### ISSUE TITLE
Issue with k8s.io/ru/docs/setup/

### ISSUE THREAD

**Issue by NebeLShaman** [kubernetes/website#26988]
По ссылке https://kubernetes.io/docs/setup/pick-right-solution/#local-machine-solutions получаю страницу "404"

**Comment by Arhell** [comment]
@NebeLShaman
Доброве время суток.
А что вы стараетесь найти? Как вы туда попали?
https://kubernetes.io/docs/setup/
работает а дальше я ссылок не нашел

**Comment by Arhell** [comment]
@NebeLShaman
Страница на текущий момент не вся актуальна.
Используйте английскую версию.
