### ISSUE TITLE
blog: update old blog post to not user "none driver" for minikube

### ISSUE THREAD

**Issue by medyagh** [kubernetes/website#26998]
minikube has added docker driver since 2019 and "none driver" is not recommended and only meant to be used by CI or when there is no other option. which causes issues like this for users  https://github.com/kubernetes/minikube/issues/8568#issuecomment-675905663

we strongly suggest using other drivers. if u dont specify the --driver flag, minikube will choose the best driver for your environment.

I suggest updating this blog post to use minikube with either docker driver (or not set the --driver at all) to let minikube choose the best driver:

blog post: https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/#minikube-updating-the-host

@idvoretskyi

**Comment by idvoretskyi** [comment]
/assign

@medyagh thanks for catching this!

**Comment by nunix** [comment]
first, thanks a lot for your feedback @medyagh , really appreciated.

Concerning the driver, I think the timing is very good as WSL2 is now "live", so the Windows Insiders is no more needed and the default kernel used is the 5.4.x and is built with modules needed by Kubernetes and/or Docker.

I will go through the blog post and refresh it entirely, so we keep only one blog post, but this will could be seen as a V2

**Comment by sftim** [comment]
/sig windows
I think

@nunix we usually don't make substantial revisions to published blog articles. If you are planning a big revision, it might be better to propose a new article and then update the old article to start with a notice about reading the new article instead.
/area blog
/language en

**Comment by nunix** [comment]
thanks a lot @sftim, I was actually start thinking the same ... but I might then just remove the part of the none driver to address this issue and then concentrate on a new blog (might take more time due to my workload lately)

**Comment by medyagh** [comment]
@nunix I wonder was there a PR that made for this issue, is this still being worked on ?

**Comment by nunix** [comment]
hi @medyagh , sorry I have some delay here. I need to test the docker provider again, my first test didn't work, but I guess I did something wrong. I will amend the blog post asap.

**Comment by BioGeek** [comment]
/remove-lifecycle stale

@nunix Can you comment if this is something you're still working on?

@sharifelgamal  mentioned in issue #10343 that proper support for WSL with the docker and none drivers is in the roadmap for this year, so maybe you're waiting on that?
