### ISSUE TITLE
Diagram not rendering correctly on Ingress page with Chrome/Ubuntu

### ISSUE THREAD

**Issue by alexellis** [kubernetes/website#27008]
**This is a Bug Report**

**Problem:**

Diagram not rendering correctly on Ingress page with Chrome/Ubuntu

**Proposed Solution:**

Needs someone to look into it, who is knowledgeable about this page, or who may have updated it recently.

**Page to Update:**

https://kubernetes.io/docs/concepts/services-networking/ingress/

No explicit version 

I couldn't find a similar issue, but feel free to close if this has already been reported

![ingr](https://user-images.githubusercontent.com/6358735/110807319-d076ce00-827a-11eb-8bb2-9050ec442703.png)

System: 

```
Linux alex-nuc8 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Chrome Version 88.0.4324.182 (Official Build) (64-bit)

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
```

I'm using the default window manager / desktop.

**Comment by sftim** [comment]
That's a Mermaid diagram. If someone'd like to replace it with a similar SVG image, that'd help it render on more devices and more consistently.

**Comment by sftim** [comment]
/priority backlog
(the page is ugly but understandable)

**Comment by jimangel** [comment]
An alternate solution might be in updating Mermaid. We are running 8.5.0 and it appears 8.9.1 is out.

The JS is copied from a CDN but the source is called out here: https://github.com/kubernetes/website/blob/master/layouts/partials/head.html#L89-L92

To update:
- Navigate to the latest CDN (https://unpkg.com/mermaid@8.9.1/dist/mermaid.min.js)
- Copy contents and replace everything in [static/js/mermaid.min.js](https://github.com/kubernetes/website/blob/master/static/js/mermaid.min.js)
- Either locally or in a PR and evaluate changes for approval

It looks like it hasn't been changed in 11mo. This is a great first issue if anyone is interested in trying it out.

/good-first-issue

**Comment by sftim** [comment]
:+1: to the “update Mermaid” approach

**Comment by chrismetz09** [comment]
Hey Folks, I'll give this one a shot. tx.

**Comment by celestehorgan** [comment]
/triage accepted 

@chrismetz09, feel free to use `/assign` to assign this issue to yourself.

**Comment by chrismetz09** [comment]
@celestehorgan, assign is greyed out for me. I am logged on to github. How do I "assign yourself"?

**Comment by ShivamTyagi12345** [comment]
Hey @alexellis . Last update dates back a month from now, Is this issue still open to work? I would like to work on the same

**Comment by alexellis** [comment]
Sure

**Comment by sftim** [comment]
I have a feeling that this might have been addressed in https://github.com/kubernetes/website/pull/27129

/remove-good-first-issue
