### ISSUE TITLE
Mention scheduling profiles in Configure Multiple Schedulers

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#27011]
**This is a Feature Request**

**What would you like to be added**
https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/ should signpost readers to 
https://kubernetes.io/docs/reference/scheduling/config/#multiple-profiles as they

**Why is this needed**
Readers might want to use an additional scheduling profile rather than implement a fully custom scheduler.

**Comments**

You can also use a custom scheduler configuration, or custom container image, for the cluster's main scheduler by modifying its static pod manifest on the relevant control plane host.

/language en
/kind feature
/help
/sig scheduling

**Comment by vaibhav2107** [comment]
Fixed in PR #27027
