### ISSUE TITLE
Mentioned Scripts in following paragraph has different value for `CA` 

### ISSUE THREAD

**Issue by Mohitp98** [kubernetes/website#27034]
As mentioned in [this](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server:~:text=If%20you%20deploy%20your%20own%20identity,longer%20life%20and%20larger%20key%20size.) paragraph, while creating CA for your own Identity Provider's server, you must keep `CA: TRUE`.

But the mentioned links for generating CA has `CA: FALSE`

**Can someone please clarify that?**

**Comment by sftim** [comment]
> But the mentioned links for generating CA has CA: FALSE

Which link @Mohitp98 ? Can you clarify?

/triage needs-information

**Comment by Mohitp98** [comment]
Thanks for replying @sftim 
For the 3rd point mentioned under [For an identity provider to work with Kubernetes it must:](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server:~:text=For%20an%20identity%20provider%20to%20work%20with%20Kubernetes%20it%20must%3A)

![Screenshot from 2021-03-15 18-07-19](https://user-images.githubusercontent.com/30376735/111154757-929ae200-85b9-11eb-9afc-b32389862e6f.png)

This paragraph contains links to helper scripts to generate simple CA, signed certificate & key for Identity Provider's server
- Link - [this script](https://github.com/dexidp/dex/blob/83ad7bc4e3beaf21ac3a56a03dd4e223249215fe/examples/k8s/gencert.sh#L13)
- Link2 - [this similar script](https://raw.githubusercontent.com/TremoloSecurity/openunison-qs-kubernetes/master/src/main/bash/makessl.sh) 
Both the links has field 
`basicConstraints = CA:FALSE`

So My question is, As mentioned in 3rd point **`CA: TRUE` is required in the certificate,** whereas example scripts contain `CA: FALSE` 

Please clarify this!

Also, it will be better if we mention the location of the directory where we can place the Identity provider's CA certificate.

**Comment by sftim** [comment]
/kind bug

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server does look wrong.

I think it'd be useful to suggest a different tool. https://blog.cloudflare.com/how-to-build-your-own-public-key-infrastructure/ looks like a better starting point.

/sig auth
@kubernetes/sig-auth-bugs can you confirm triage on this?

**Comment by liggitt** [comment]
The linked script is correct, the configuration is indicating that the requested serving certificate may not be a CA.

I don't have an opinion about linking to different tools, but that seems more like a docs feature/enhancement, not a bug.

**Comment by sftim** [comment]
Thanks @liggitt, yes that does make sense.
/remove-kind bug
/kind cleanup
/priority backlog
/remove-triage needs-information
