### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

### ISSUE THREAD

**Issue by rahulchonkria** [kubernetes/website#27047]
I followed all steps of this except I have my own pod, and I still can't get it to work, it gives me this error when I run the last curl command

curl: (7) Failed to connect to localhost port 80: Connection refused

Here is the YAML of the webapp I have running on the pod:

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-03-13T01:26:01Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: ofbiz
  name: ofbiz
  namespace: default
  resourceVersion: "5601628"
  selfLink: /api/v1/namespaces/default/services/ofbiz
  uid: 0edcec18-0e26-4151-a86d-e5047f3fa250
spec:
  clusterIP: 10.56.9.172
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32249
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ofbiz
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: public IP
```

**Comment by sftim** [comment]
My guess is that the Pod you are running isn't listening on port 80. You say you're using a custom Pod @rahulchonkria ?

If you follow the task steps more closely, do things work OK?

**Comment by rahulchonkria** [comment]
I switched it to 80 and still the same result

**Comment by sftim** [comment]
@rahulchonkria to help us understand if the page is inaccurate, not clear enough, or something else, can you list the differences between the steps you've followed and what's written on that page?

Could you also run:
`kubectl get pod --namespace default --o yaml` and include that output in a comment? It'd be useful to understand what Pods are running in that cluster when you have got to the last step of the task, and the health of those Pods.

**Comment by rahulchonkria** [comment]
Thank you very much! I was able to deploy the pod, but the problem is, whenever I try to use curl localhost to access the HTML file that I create inside the pod, it gives me this:

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.19.8</center>
</body>
</html>

Regardless, you've been of great help.
