### ISSUE TITLE
Last command of "Interactive Tutorial - Exposing Your App" interactive lesson is deprecated

### ISSUE THREAD

**Issue by rodrigobercini** [kubernetes/website#27056]
After running `kubectl exec -ti $POD_NAME curl localhost:8080`, I'm getting the following message:

`kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.`

This should be fixed by adding -- to the command.

Current deprecated command:

`kubectl exec -ti $POD_NAME curl localhost:8080`

Expected non-deprecated command:

 `kubectl exec -ti $POD_NAME -- curl localhost:8080`

**Comment by sftim** [comment]
/kind cleanup
/language en
/priority important-longterm
/triage accepted

I agree with the suggested fix. We also need to match the Katacode tutorial to match it.

**Comment by Priyankasaggu11929** [comment]
@sftim , @rodrigobercini

It looks like the suggested updated ( `non-deprecated` ) command is fixed. I'm not able to figure which PR/commit has fixed this. But below is the screenshot (from the [tutorial page](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/)) that has the updated command:

![Screenshot from 2021-05-18 17-50-17](https://user-images.githubusercontent.com/30499743/118650177-ca184b80-b801-11eb-80af-3ff2bfb7663c.png)
