### ISSUE TITLE
Improvement for k8s.io/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by SvenMW** [kubernetes/website#27068]
Hi!

The docs leave it open to interpretation if the default pod security policy actually still processes all syscalls through the seccomp profile, even if no policy is applied.

So my question is: Does kubernetes apply an (empty) default profile, if seccomp is in "unconfined" state?

The docs read:

> unconfined - Seccomp is not applied to the container processes (this is the default in Kubernetes), if no alternative is provided.

I ask, because we were able to measure  a not negligible performance difference on certain workloads even if an empty seccomp profile is applied to a container (this was not measured in kubernetes but in lxc).

So it would be nice to clarify if "not applied" means an empty profile, which still tests every syscall against an empty list or if this means that really no checks are performed at all.

At least I was not able to find this information in the docs or elsewhere on the internet ( I didn't check the source yet).

Thanks for any pointers!

**Comment by SvenMW** [comment]
See also this blog post for documentation on the real overhead of this stuff:

https://talawah.io/blog/extreme-http-performance-tuning-one-point-two-million/#_3-syscall-auditing-blocking

**Comment by sftim** [comment]
My understanding is that _there is no default PodSecurityPolicy_. The PSP admission controller defaults to **disabled**.

Some managed cloud clusters such as GKE and EKS come with PodSecurityPolicy enabled; these have **vendor** defaults for the PSP. Kubernetes itself does not have any default PSP (if you enable PSP on vanilla Kubernetes then no Pods launch, precisely becase there is no default).

**Comment by sftim** [comment]
See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#enabling-pod-security-policies for details.

**Comment by sftim** [comment]
Thanks @enj!

**Comment by SvenMW** [comment]
> My understanding is that _there is no default PodSecurityPolicy_. The PSP admission controller defaults to **disabled**.

I'm terribly sorry, but it seems I was not clear enough.

I know there is no default PodSecurityPolicy. What I don't know, if the mechanism to scan for the content of enabled PodSecurityPolicys, e.g. forbidden syscalls still runs.

So the question is: If I have not defined any security policy for my pod, and as you say per default there is none, would syscalls from my pod still move through an, admittedly empty, filter, which costs performance? or does kubernetes recognize that there is no PodSecurityPolicy applied and does execute the syscall directly, without going through an empty filter?

I hope I could explain the question a little better.

Thanks for any input.

**Comment by sftim** [comment]
> If I have not defined any security policy for my pod, and as you say per default there is none, would syscalls from my pod still move through an, admittedly empty, filter, which costs performance? or does kubernetes recognize that there is no PodSecurityPolicy applied and does execute the syscall directly, without going through an empty filter?

In that case, this question is actually not about PodSecurityPolicy; it's about the [`securityContext`](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context-1) field. PodSecurityPolicy restricts what kinds of Pod objects can be admitted - enforcing constraints about details including `securityContext`. Syscall filtering is a node-level issue that follows the behavior defined by the Pod API (and not PodSecurityPolicy).

We could document that more. I think it's actually outside of the scope of what Kubernetes itself implements though: your container runtime is supposed to take care of system call filtering.

As I see it:
/kind support
/remove-kind documentation
/remove-sig auth
/sig node

**Comment by SvenMW** [comment]
Thanks for the pointers @sftim  ! much appreciated
