### ISSUE TITLE
[es] update `kubectl` installation docs

### ISSUE THREAD

**Issue by raelga** [kubernetes/website#27078]
**What would you like to be added**

The current documentation upstream documentation for `kubectl` installation is divided into a document per system (mac, linux, windows). The Spanish documentation still uses the old format, will a single page for all systems and is a bit outdated.

- en: https://kubernetes.io/docs/tasks/tools/#kubectl
- es: https://k8s.io/es/docs/tasks/tools/install-kubectl/

**Why is this needed**

`kubectl` installation is probably the first step when onboarding into the kubernetes ecosystem and the documentation should be up to date.

**Comments**

Discussed on https://github.com/kubernetes/website/issues/27048 .
Added to the #13948 .

---
/language es
/good-first-issue
/help

**Comment by SivaTharun** [comment]
@raelga is this issue still being tracked, if not i would like to give it a try.

**Comment by raelga** [comment]
> @raelga is this issue still being tracked, if not i would like to give it a try.

Hello @SivaTharun, I don't know if @rajpratyush started working on the issue. If not, is still open to collaboration! :)

**Comment by soniasingla** [comment]
@SivaTharun any updates here, let us know if you are facing any issues? :)

**Comment by anubha-v-ardhan** [comment]
@SivaTharun Any updates?

**Comment by SivaTharun** [comment]
@anubha-v-ardhan @soniasingla i have started working on this issue, i will have an PR ready in two to three days.

**Comment by abeltre1** [comment]
@raelga is this issue still opened ?  I noticed that @SivaTharun was assigned to it. No updates have been posted here.

**Comment by raelga** [comment]
Hey @abeltre1 we are reviewing @SivaTharun pull request.

**Comment by raelga** [comment]
We are troubleshooting some issues with @SivaTharun CLA.

**Comment by gouravmohanty7070** [comment]
Can I work on it?

**Comment by raelga** [comment]
Hello @gouravmohanty7070, the original PR has been closed. Feel free to take this issue. :)
