### ISSUE TITLE
Add content to https://kubernetes.io/docs/setup/production-environment/

### ISSUE THREAD

**Issue by chrisnegus** [kubernetes/website#27072]
**This is a Feature Request**

**What would you like to be added**

This page currently consists of four links to production environment topics. I'd like to do the following:

* Add text describing considerations for setting up a production-quality Kubernetes environment or having someone do it for you.
* Take the existing four links and merge them into the text.
* Since I believe the Best practices links relate to production environment and not learning environment configurations, I'd like to move links to that content into this section as well. See https://kubernetes.io/docs/setup/best-practices/. 

**Why is this needed**

Going from a Kubernetes learning environment to a production environment is a big step in both effort and costs. It is not the place of the Kubernetes project to recommend particular vendors or approaches. However, it could help readers for us to lay out the choices they need to make to get a production-quality Kubernetes that meets their needs.

**Comments**

I would like to write this myself, but I'm very open to suggestion on what should be covered. Topics could include high availability, scaling requirements, security and access management, and others.

**Comment by sftim** [comment]
Thanks @chrisnegus 

I'd be happy to see those changes proposed (anyone can open a pull request to help with this, BTW). Remember to configure Netlify redirects if moving pages.

/kind feature
/language en
/priority backlog
/triage accepted

**Comment by celestehorgan** [comment]
@chrisnegus

I'd also love to see this written. I think one of the best places you could go for comment/advice as to what should be covered is the CNCF Ambassadors group – you can find them on CNCF's slack instance.

**Comment by chrisnegus** [comment]
> @chrisnegus
> 
> I'd also love to see this written. I think one of the best places you could go for comment/advice as to what should be covered is the CNCF Ambassadors group – you can find them on CNCF's slack instance.

Thanks Celeste. I will check that out.

**Comment by jihoon-seo** [comment]
It seems that this issue is okay to close, since the PR #27466 is merged. :)

**Comment by chrisnegus** [comment]
> It seems that this issue is okay to close, since the PR #27466 is merged. :)

Thanks. I wasn't sure if I was able to do that.
