### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by dglauche** [kubernetes/website#27087]
During the tutorial within module 4 step 2 I noticed that the keyword 'pod' as well as 'pods' are used without an explanation. First it was a bit irritating but they function the same. I would suggest to use the same keyword to avoid confusion.

**Comment by su225** [comment]
Newcomer here. I'll give a try.

**Comment by viveksahu26** [comment]
Hey @k8s-ci-robot, This would be my first contribution to Kubernetes. So, can please assign this to me. And please elaborate on the issue.

**Comment by jxofficial** [comment]
Hi, can I take up this issue?

**Comment by irvifa** [comment]
Hi @jxofficial yes as long as the issue is unassigned you can take it :)

**Comment by tabhay563** [comment]
\assign
