### ISSUE TITLE
/hold

### ISSUE THREAD

**Issue by Bubba420G** [kubernetes/website#27116]
/hold
do not merge

_Originally posted by @sftim in https://github.com/kubernetes/website/issues/23294#issuecomment-678259244_

**Comment by Bubba420G** [comment]
How

???
??
?
.
.
.

**Comment by celestehorgan** [comment]
/close

This seems like an accidentally opened issue. 
If there's an actionable issue with documentation, @Bubba420G, feel free to open another issue describing the specific issue you're having and the page of documentation you think needs improvement.
