### ISSUE TITLE
[ja]Translate concepts/cluster-administration/flow-control/ into Japanese

### ISSUE THREAD

**Issue by kakts** [kubernetes/website#27125]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/cluster-administration/flow-control/ into Japanese.
https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

**Why is this needed**
This page has not been translated into Japanese.
**Comments**

For `dev-1.19-ja.1` branch

/language ja
/assign

**Comment by tengqm** [comment]
/retitle Translate concepts/cluster-administration/flow-control/ into Japanese

**Comment by tengqm** [comment]
/retitle [ja]Translate concepts/cluster-administration/flow-control/ into Japanese
