### ISSUE TITLE
Set Kubelet parameters via a config file

### ISSUE THREAD

**Issue by allinonedashboard** [kubernetes/website#27120]
Hi Team,

Can you please help on the below issue. We are trying to update the kubelet config for limiting pid's in POD.

error: unable to recognize "kubectl.yaml": no matches for kind "KubeletConfiguration" in version "kubelet.config.k8s.io/v1beta1"

**Comment by tengqm** [comment]
The kubelet config is not supposed to be used from kubectl command line.

**Comment by allinonedashboard** [comment]
Hi @tengqm it is just the name of the yaml file

**Comment by sftim** [comment]
@allinonedashboard I think you're trying to understand https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

Is there a part of this page that isn't clear when you read it?

**Comment by allinonedashboard** [comment]
@sftim Yeah you are correct. In the manifest file I am trying to limiting the pid's in POD

**Comment by sftim** [comment]
Maybe https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ should emphasize that a kubelet config file is _not_ a manifest.

**Comment by allinonedashboard** [comment]
@sftim i have created a manifest file name called **kubectl.yaml** where the content is below

apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
evictionHard:
    memory.available:  "200Mi"

Using the command to update  **kubectl apply -f kubectl.yaml -n kube-system**
correct me if i am wrong in my way.

**Comment by sftim** [comment]
I'm am afraid that you are wrong @allinonedashboard 

To tell the kubelet to use that configuration file, which is still **not a manifest**, read https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file and follow the steps explained there.

/kind support

**Comment by RA489** [comment]
>> Using the command to update kubectl apply -f kubectl.yaml -n kube-system
Namespace shouldn't be defined here. It should be written in yaml definition file.

**Comment by RA489** [comment]
PTAL over https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
