### ISSUE TITLE
[ko] Unnecessary item is displayed in left-side navigation menu

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27132]
**This is a Bug Report**

**Problem:**
[ko] 
In https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/,
unnecessary item is displayed in left-side navigation menu.

- [English version](https://kubernetes.io/docs/reference/setup-tools/kubeadm/)
![image](https://user-images.githubusercontent.com/46767780/111715825-10037280-8898-11eb-8d7d-2e21c7ff9b06.png)
- [Korean version](https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/)
![image](https://user-images.githubusercontent.com/46767780/111715884-332e2200-8898-11eb-9c58-f8b635cfa0bd.png)

**Proposed Solution:**
- ~Add `content/ko/docs/reference/setup-tools/kubeadm/generated/_index.md`~
```Markdown
---
title: "Kubeadm Generated"
weight: 10
toc_hide: true
---
```

**Page to Update:**
https://kubernetes.io/ko/docs/reference/setup-tools/kubeadm/

/language ko
/assign

**Comment by jihoon-seo** [comment]
Adding `content/ko/docs/reference/setup-tools/kubeadm/generated/_index.md` does not resolve this issue.
(PR #27134 adds that file, but the menu item remains in [the deploy preview](https://deploy-preview-27134--kubernetes-io-master-staging.netlify.app/ko/docs/reference/setup-tools/kubeadm/).

Is there anyone that has an idea?

**Comment by jihoon-seo** [comment]
Is there any possibility that adding `no_list: true` can resolve this issue?

(Ref for `no_list: true`: [here](https://github.com/kubernetes/website/blob/master/content/en/docs/reference/using-api/_index.md))

**Comment by seokho-son** [comment]
@jihoon-seo Thank you for the bug report.
In my perspective, this bug is related with layout of website. (toc_hide seems not applied for all localized contents)
Let me check where the bug is from.

I suspect~
this file. 
./layouts/partials/sidebar-tree.html

**Comment by seokho-son** [comment]
@jihoon-seo I found a way to resolve this. after some test I will make a PR. Thank you for the bug report!
