### ISSUE TITLE
kubeadm init phase typo

### ISSUE THREAD

**Issue by vd-rd** [kubernetes/website#27145]
Hello,

The documentation available at https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-certs states that the init phase is creating ca.cert and ca.key, the public key name has a typo. Instead it should be ca.crt.  
This makes the process of providing your own CA fail because kubeadm expects a different name.
```
Synopsis
Generate the self-signed Kubernetes CA to provision identities for other Kubernetes components, and save them into ca.cert and ca.key files.
```

**Comment by neolit123** [comment]
These docs are generated mostly. The bug is in
kubernetes/kubernetes/cmd/kubeadm.

/sig cluster-lifecycle
/triage accepted
