### ISSUE TITLE
Add Contiv-VPP CNI to Networking and Addons pages

### ISSUE THREAD

**Issue by chrismetz09** [kubernetes/website#27144]
**This is a Feature Request**

**What would you like to be added**

Kubernetes relies on CNI plugins to "bootstrap" cluster networks conforming to the K8s networking model. The ../cluster-administration/networking and ../cluster-administration/addons pages list CNI plugins. [Contiv-VPP](https://contivpp.io/) is not listed on these pages. 

Actions required:

- Add Contiv-VPP descriptive blurbs/reference links to the aforementioned pages.

**Why is this needed**

- CNI plugins provide networking policy so K8s can function per [Third party content](https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content).

- K8s docs should include this CNI plugin that is currently deployed in cloud native networks.

- Adheres to CNI specification. 

- Works with existing cloud native projects including K8s, etcd, gRPC, etc.

- Leverages multiple open source and cloud native project software including [FD.io/VPP](https://fd.io/) and [Ligato](https://ligato.io/).

- Clear up confusion surrounding [Contiv](https://github.com/contiv/netplugin) and Contiv-VPP. These are two completely different CNI plugins and share nothing other than the "contiv" character string in the name.

**Comments**

I would like to handle this as I contributed to the project including the UI design/function, website and documentation. Open to any/all community suggestions on how best to handle.

**Comment by sftim** [comment]
@chrismetz09 sure, this is a valid improvement.

I noticed that both Contiv and Contiv VPP are in the same GitHub organization; I don't believe it's right to say that they have _nothing_ in common.

/triage accepted
/language en
