### ISSUE TITLE
Unclear requirements for “Using Source IP” tutorial

### ISSUE THREAD

**Issue by dabing1986** [kubernetes/website#27162]
Source IP for Services with Type=ClusterIP 
Packets sent to ClusterIP from within the cluster are never source NAT'd if you're running kube-proxy in iptables mode, (the default). You can query the kube-proxy mode by fetching http://localhost:10249/proxyMode on the node where kube-proxy is running.

kubectl get nodes
The output is similar to this:

NAME                           STATUS     ROLES    AGE     VERSION
kubernetes-node-6jst   Ready      <none>   2h      v1.13.0
kubernetes-node-cx31   Ready      <none>   2h      v1.13.0
kubernetes-node-jj1t   Ready      <none>   2h      v1.13.0

When I use kubectl get nodes there is no nodes available except 
NAME       STATUS   ROLES                  AGE   VERSION
minikube   Ready    control-plane,master   38m   v1.20.2

**Comment by sftim** [comment]
Let's update https://kubernetes.io/docs/tutorials/services/source-ip/ to recommend running this tutorial on a cluster with at least two nodes that are not acting as control plane hosts.

/retitle Unclear requirements for “Using Source IP” tutorial

**Comment by Priyankasaggu11929** [comment]
#### Clarifying the ask

The [Using Source IP](https://kubernetes.io/docs/tutorials/services/source-ip/) tutorial uses a `3 node cluster` cluster as an example setup throughout the document.

*<sub>(The text in the screenshot below is the exactly the section mentioned in the issue description)</sub>*
![Screenshot from 2021-05-18 19-42-15](https://user-images.githubusercontent.com/30499743/118666987-3cdcf300-b811-11eb-9803-6a51ea9e5f9d.png)

But as pointed in the description of this issue:

- the [source-ip/#prerequisites](https://kubernetes.io/docs/tutorials/services/source-ip/#prerequisites) section doesn't clearly state that it requires a multi-node cluster to follow through the doc examples.
- also, it mentions to create a cluster using `minikube` which usually is taken as a single node (common) control-plane/worker-node setup.

---
#### Suggested solution

As suggested by @sftim, the fix/solution would be to update the `pre-requisites` section to mention that it is recommended to run this tutorial on a **cluster with at least two nodes that are not acting as control plane hosts**.

You could also update the `minikube` part by linking to this article talking about [how to start a multi-node cluster on minikube](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/).
