### ISSUE TITLE
Install and Set Up kubectl on Windows

### ISSUE THREAD

**Issue by MNashDev** [kubernetes/website#27179]
Install-Script -Name 'install-kubectl' -Scope CurrentUser -Force
install-kubectl.ps1 [-DownloadLocation <path>] 

Install via PSGallery not working. 

In the Install Script:
`$uri = "https://kubernetes.io/docs/tasks/tools/install-kubectl/"
Write-Host -ForegroundColor White "==>Getting download link from $uri"   
$req = Invoke-WebRequest -UseBasicParsing -Uri $uri
try
    {
        Write-Host -ForegroundColor White "==>analyzing Downloadlink"   
        $downloadlink = ($req.Links | where href -Match "kubectl.exe").href
    }
catch
    {
    Write-Warning "Error Parsing Link"
    Break
    }
Write-Host -ForegroundColor White "==>starting Download from $downloadlink using Bitstransfer"   
Start-BitsTransfer $downloadlink -DisplayName "Getting KubeCTL from $downloadlink" -Destination $Downloadlocation`

The $uri provided in the script does not provide any matches for "kubectl.exe", leaving the $downloadLink variable empty, causing Start-BitsTransfer to Error.

Using "https://dl.k8s.io/release/v1.20.0/bin/windows/amd64/kubectl.exe" as $downloadLink has worked on my own script.

**Comment by sftim** [comment]
/triage duplicate
This duplicates issue 26956.

**Comment by DanielW10001** [comment]
Change Installation Script `install-kubectl.ps1` Line 29:
```ps1
$uri = "https://kubernetes.io/docs/tasks/tools/install-kubectl/"
```
To:
```ps1
$uri = "https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/"
```
Would resolve this issue.
Because download link to kubectl.exe is no longer at the previous page.

**Comment by eddiezane** [comment]
Let's track this at https://github.com/kubernetes/website/issues/26956

/close
