### ISSUE TITLE
Example: Deploying WordPress and MySQL with Persistent Volumes

### ISSUE THREAD

**Issue by ffred1962** [kubernetes/website#27194]
How to create persisten volume in catacoda ?

**Comment by RA489** [comment]
@ffred1962 This https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/ doesn't help creating PV?

**Comment by ffred1962** [comment]
Hi!
Thank You very much!
And I also  found this lab: https://www.katacoda.com/mjboxboat/courses/kubernetes-fundamentals-2/persistent-volumes 

 

So this issue may be closed

 

Kind regards,
Fred

**Comment by ffred1962** [comment]
It seems that line

 

storageClassName: local-storage

 

was missing at resource definition files
