### ISSUE TITLE
Improvement for k8s.io/docs/reference/access-authn-authz/authentication/

### ISSUE THREAD

**Issue by markmorlino** [kubernetes/website#27193]
I went to the page because of this error from terraform plan:

```
Error: Get "https://blahblahblah.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth": getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
```

And there is no information on the page about how to resolve the error.

**Comment by sftim** [comment]
/kind support

https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins _does_ explain how to use these plugins, but doesn't cover using Terraform, EKS, the `aws` CLI tool in combination. Kubernetes doesn't provide that level of detail for third party software and services.
