### ISSUE TITLE
Contribute to K8s docs

### ISSUE THREAD

**Issue by CyprianFusi** [kubernetes/website#27190]
Is there any future plan to merge Docker and Kubernetes to form Dockernetes? There seems to be a lot of overlaps and integration already. Consolidating both would probably be powerful...

**Comment by sftim** [comment]
> Is there any future plan to merge Docker and Kubernetes to form Dockernetes?

No.

This question is not really about contributing to Kubernetes documentation @CyprianFusi. I'm going to close it.

/triage unresolved
/close
