### ISSUE TITLE
Usando kubectl para criar uma implantação

### ISSUE THREAD

**Issue by netodeolino** [kubernetes/website#27243]
In the section "Implantações do Kubernetes" in the Portuguese version there an error in the word "CLuster" which should be "Cluster"

**Comment by sftim** [comment]
Page: https://kubernetes.io/pt/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

/kind cleanup
/language pt
/good-first-issue
/priority backlog

If you speak Portuguese, or even if you don't and you'd like to help, you can open a pull request to fix this typo.

**Comment by sftim** [comment]
Fixed in #27245

/close

**Comment by sftim** [comment]
Also
/triage accepted
