### ISSUE TITLE
Wrong issue title when the page title includes `'` character

### ISSUE THREAD

**Issue by shuuji3** [kubernetes/website#27253]
**This is a Bug Report**

**Problem:**

When clicking "Create an issue" on this page [Restrict a Container's Access to Resources with AppArmor | Kubernetes](https://kubernetes.io/docs/tutorials/clusters/apparmor/), the title of the issue should be "Restrict a Container's Access to Resources with AppArmor" but it becomes "Restrict a Container".

**Proposed Solution:**

Fix the `href` attribute of the link when the page title includes `'` character.

**Page to Update:**
Somewhere on the Hugo related file

/area web-development

**Comment by sftim** [comment]
BTW, this might be a Docsy bug (and be best fixed [upstream](https://github.com/google/docsy/)).

**Comment by shuuji3** [comment]
Thanks for pointing it out. That's right! I confirmed to be able to reproduce the same issue on the official Docsy page.

**Comment by shuuji3** [comment]
Created an issue on the upstream: https://github.com/google/docsy/issues/510

**Comment by shuuji3** [comment]
This issue on the upstream has been fixed now. The future release of Hugo will fix this.

**Comment by sftim** [comment]
Thanks @shuuji3

**Comment by sftim** [comment]
The fix here is to bump to a more recent Docsy release.

**Comment by tengqm** [comment]
Is this already fixed?

**Comment by tengqm** [comment]
I believe this is fixed. The Docsy theme is currenty on 1c77bb2 which dates back to 2022-04-07, and the bug fix was merged on 2021-04-12.

I'm closing this one.
Feel free to reopen it if the issue persists.
/close
