### ISSUE TITLE
服务

### ISSUE THREAD

**Issue by troub1emaker0911** [kubernetes/website#27269]
HTTP 
如果你的云提供商支持它，则可以在 LoadBalancer 模式下使用服务来设置外部 HTTP/HTTPS 反向代理，并将其转发到该服务的 Endpoints。

说明： 你还可以使用 Ingres 代替 Service 来公开 HTTP/HTTPS 服务。

这里的Ingress少写了一个s.

**Comment by yichuan66** [comment]
There is a typo in the section below: 

**HTTP
如果你的云提供商支持它，则可以在 LoadBalancer 模式下使用服务来设置外部 HTTP/HTTPS 反向代理，并将其转发到该服务的 Endpoints。

说明： 你还可以使用 _Ingres 代替 Service_ 来公开 HTTP/HTTPS 服务。**

Ingres -> Ingress
