### ISSUE TITLE
[ko] Improve translation of tasks/access-application-cluster/access-cluster.md

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27280]
**This is a Bug Report**

- English version: https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/access-application-cluster/access-cluster.md
- Korean version: https://github.com/kubernetes/website/blob/master/content/ko/docs/tasks/access-application-cluster/access-cluster.md

**Problem:**
The Korean translation of `/docs/tasks/access-application-cluster/access-cluster.md` can be improved.

**Proposed Solution:**

- `많은 예제들에서 kubectl을 사용하는 것을 소개하고 있으며 완전한 문서는 kubectl 매뉴얼에서 찾아볼 수 있다.`
=> `여기에서 kubectl 사용 예시를 볼 수 있으며, 완전한 문서는 kubectl 매뉴얼에서 확인할 수 있다.`
- `쿠버네티스에서 노드들, 파드들, 서비스들은 모두 자신의 IP들을 가진다.`
=> `쿠버네티스에서 노드, 파드, 서비스는 모두 고유의 IP 주소를 가진다.`
- `클러스터 외부에서 노드들, 파드들, 서비스들에 접속하는 데는 몇 가지 선택지들이 있다.`
=> `클러스터 외부에서 노드, 파드, 서비스에 접속하는 데에는 몇 가지 선택지가 있다.`
- 전역 replace: `노드들, 파드들, 서비스들` => `노드, 파드, 서비스`
- 전역 replace: `IP들` => `IP (주소)`
- `파드를 Running시킨 다음 kubectl exec를 사용하여 해당 파드의 셸로 접속한다.`
=> `파드를 실행시킨 다음 kubectl exec를 사용하여 해당 파드의 셸로 접속한다.`
- ...

**Page to Update:**
https://kubernetes.io/ko/docs/tasks/access-application-cluster/access-cluster/

/language ko

**Comment by seokho-son** [comment]
https://github.com/kubernetes/website/issues/27147#issuecomment-812490553

**Comment by jihoon-seo** [comment]
Resolved by #27548
