### ISSUE TITLE
[ko] Translate reference/glossary/disruption.md in Korean

### ISSUE THREAD

**Issue by santachopa** [kubernetes/website#27307]
**This is a Feature Request**

Translate reference/glossary/disruption.md in Korean

**What would you like to be added**

No translation reference/glossary/disruption.md in Korean

**Why is this needed**

**Comments**

Page to update : https://kubernetes.io/ko/docs/reference/glossary/?fundamental=true#term-disruption

**Comment by seokho-son** [comment]
https://github.com/kubernetes/website/issues/27147#issuecomment-812490553
