### ISSUE TITLE
Edit the template files to serve an X-Frame-Options header to prevent clickjacking

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#27329]
**This is a Bug Report**

**Problem:**

The entire website is currently vunerable to clickjacking due to not having a proper `X-Frame-Options` header. This issue came to our attention via an email to the Code of Conduct Committee inbox. For more information on what a clickjacking attack is, see the following: https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html

**Proposed Solution(s):**

**Option 1: Easy, but not supported by all browsers** 

Add a[ Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) header to `layout/partials/head.html`

```
<meta http-equiv="Content-Security-Policy" content=" ... ">
```

I recommend we use [a generator](https://report-uri.com/home/generate) to do this, as that's simplest.

This has the advantage of being easy to implement on a static site, but isn't supported by all browsers (yet). I think we should implement it regardless, and assume that it will be supported by all browsers in the near future.

**Option 2: more complicated, but currently supported**

Set an `X-Frame-Options` header. We need to do this [via a Netlify configuration file](https://docs.netlify.com/routing/headers/): 

```
X-Frame-Options: ...
```

**What to allow:**

In both cases, we want to allow at least the following:

- Any CDN we pull javascript from
- Any CDN we pull CSS from 
- Youtube
- Google Analytics
- https://landscape.cncf.io/
- katacoda.com
- Discourse
- twitter
- Google Calendar

I suspect there's more and I'm just not remembering it though.

**Comment by jimangel** [comment]
/assign

I feel like this has come up before in another issue. Will do some looking...

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/100358

**Comment by sftim** [comment]
We could also set `X-Frame-Options:` to _allow_ frames; that feels like it would be OK.
