### ISSUE TITLE
Search engines indexing old releases

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#27338]
**Problem:**

Google search for "kubernetes secrets v2" returns:

![image](https://user-images.githubusercontent.com/4601051/113066191-bb0d0980-917f-11eb-9e5b-3271a8a69476.png)

(notice the URL subdomains)

**Proposed Solution:**

I need to do some more research but a few things come to mind:
- `enableRobotsTXT = true` is in [config.toml](https://github.com/kubernetes/website/blob/master/config.toml#L11) and set in the couple `release-1.xx` repos I checked.
- `X-Robots-Tag: noindex` is set in [layouts/index.headers](https://github.com/kubernetes/website/blob/master/layouts/index.headers#L37). I believe this is for non-prod sites that are running, however I believe even the old released sites are considered "production"

That is assuming robots tag is the culprit. What's also strange is that the above robot config is set in `release-1.19` but doesn't appear in the search results

I also think looking at [old robot TXT issues](https://github.com/kubernetes/website/search?q=robots.txt&type=issues) might help. It's possible this problem has been solved and phased out with future releases.

/priority important-soon
/triage accepted
/help
/cc @reylejano

**Comment by sftim** [comment]
In the v1.19 docs, `<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">` appears in the page head. That's wrong.

**Comment by sftim** [comment]
/retitle Search engines indexing old releases

Also, the _upcoming_ release is also being indexed and we don't actually want that. Same cause I think.

**Comment by sftim** [comment]
I've proposed a PR to fix this.
:crossed_fingers:

**Comment by sftim** [comment]
/reopen

We also need to merge 4 backport PRs.

**Comment by jihoon-seo** [comment]
[Backport PRs]
- [v1.19](https://github.com/kubernetes/website/pull/31375)
- [v1.20](https://github.com/kubernetes/website/pull/31376)
- [v1.21](https://github.com/kubernetes/website/pull/31377)
- [v1.22](https://github.com/kubernetes/website/pull/31378)

**Comment by sftim** [comment]
It's fixed. I checked.
/close
