### ISSUE TITLE
Add best practice guidelines to PSP documentation.

### ISSUE THREAD

**Issue by tabbysable** [kubernetes/website#27336]
While working on another doc, several of us realized that the PSP documentation could benefit from explicitly calling out the best practice of setting a cluster-default PSP by binding it to system:authenticated and then allowing certain namespaces to exceed that policy as-needed by binding a more-permissive policy to the serviceAccounts in those namespaces. Perhaps on https://kubernetes.io/docs/concepts/policy/pod-security-policy/#run-another-pod ?

Creating this issue so we don't forget.

**Comment by tabbysable** [comment]
@tallclair you'll like this.
/sig security auth

**Comment by sftim** [comment]
/priority important-longterm
(sic)

**Comment by sftim** [comment]
I'd mention good practice for PSP in https://kubernetes.io/docs/concepts/security/ or https://kubernetes.io/docs/concepts/security/pod-security-standards/
We could add a _task_ page about enforcing a minimum cluster level of pod security (ie, within https://kubernetes.io/docs/tasks/).

**Comment by sftim** [comment]
Also see: https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/#controlling-what-privileges-containers-run-with

**Comment by tallclair** [comment]
Thanks for following up on this! I'm happy to review anything you write - ping me on slack if I don't see the PR :)

**Comment by liggitt** [comment]
> allowing certain namespaces to exceed that policy as-needed by binding a more-permissive policy to the serviceAccounts in those namespaces

Specifically, binding to the group `system:serviceaccounts:$namespace`, to make it clear this is being done at namespace-level granularity. This will map well to the namespace-level `PodSecurity` admission plugin being developed in 1.22

Also, we should add notes to the mutating fields in PSP and indicate they should be avoided if planning to migrate to the `PodSecurity` admission plugin, since that plugin has no equivalent capability for mutating pods.

**Comment by savitharaghunathan** [comment]
/help-wanted 
Feel free to reach out to sig-security &/ sig-auth slack channel for guidance.

**Comment by hyakuhei** [comment]
> I'd mention good practice for PSP in https://kubernetes.io/docs/concepts/security/ or https://kubernetes.io/docs/concepts/security/pod-security-standards/

@sftim Are you suggesting editing these two _instead_ of the change in https://kubernetes.io/docs/concepts/policy/pod-security-policy/#run-another-pod that @tabbysable mentioned in the issue description ?

**Comment by hyakuhei** [comment]
Thanks for the clarification this is really helpful, I’ll get to work
drafting something!

**Comment by hyakuhei** [comment]
I've not been able to make time for this so taking my name off in-case others want to pick it up.

**Comment by sftim** [comment]
With PR #28587 open but also with the v1.22 release creeping up on us:
/remove-priority important/longterm
/priority important/soon

**Comment by sftim** [comment]
/remove-priority important-longterm
Sorry Prow
