### ISSUE TITLE
Create a google data studio report to show google analytic's data for kubernetes.io

### ISSUE THREAD

**Issue by a-mccarthy** [kubernetes/website#27360]
**What would you like to be added**

At a recent SIG docs meeting we talked about using a [Google Data studio](https://support.google.com/datastudio/answer/6283323?hl=en) to publish Google analytics data for the kubernetes.io site.

To do this we need
* A google account that can create and host the report
* Determine and document how community members can access this report 
* Determine and document how to request updates to this report 
* Figure out to manage permissions for maintaining this report, or making updates (should be very low overhead for maintenance)
* Create a publicly available url for the report

**Why is this needed**

This is an ask from the localization sub project to be able to access analytics so they can prioritize pages for translations. By making the reports available to everyone, we can also enable community members and maintainers to view how certain pages are being used.

**Comment by a-mccarthy** [comment]
cc @jimangel @irvifa and @sftim

**Comment by sftim** [comment]
![Party popper](https://user-images.githubusercontent.com/22591623/113162829-23ff8a80-922f-11eb-9399-2b8432f44af8.png)

Sounds good to me!

**Comment by a-mccarthy** [comment]
Is there more information on how to go about getting a URL for this?

**Comment by sftim** [comment]
https://github.com/kubernetes/community/tree/master/wg-k8s-infra are the folks to talk to _I think_

**Comment by kbhawkey** [comment]
👀

**Comment by a-mccarthy** [comment]
I did some more thinking on how to set this up.

This [support article](https://support.google.com/datastudio/answer/7459147?hl=en) had a bunch of info on sharing
* you can share google data studio reports with anyone to view, no google account required. 
* If you want edit access then you must have a google account (not necessarily a google email, but a google account).
* You can also share reports with just a google group, so if we didn't want to share this completely publicly, but rather to a smaller group of folks who join our mailing list, thats an option. I'm not sure that its worth adding the additional blocker to needing to be in the google group to view the report, but wanted to note it just in case

Is there a central SIG docs email we can use to host the report? Then we can share thee report from there. Or create the report from a personal account and share edit access with whoever we decide will be the maintainers of this.

For managing permissions and updating the report, are the sig leads ok with owning this? I'm not sure its worth it or enough work to justify making a working group, but i dont want to pile on to work the leads are already doing. Is there a more appropriate group that should own this?

Requesting updates or filing bugs in the report process (wip)
1.  file an issue
1.  Use github label to track/organize request
1.  SIG leads will evaluate the request/troubleshoot and update the reports as necessary. (or whoever we decide to own making updates)

**Comment by a-mccarthy** [comment]
@jimangel in the community call today you mentioned an sig docs email address that we might be able to use for this. Are you able to test seeing if you can get into data studio, i think you need have a [google account associated to the email](https://support.google.com/accounts/answer/176347) (if it doesn't have one already) and then try to go to [google data studio](https://datastudio.google.com/).

**Comment by jimangel** [comment]
From today's meeting: I think you should own the GDS page and share edit rights to "k8s-sig-docs-leads@googlegroups.com," if inheritance doesn't work we can directly add each lead as an editor.

**Comment by a-mccarthy** [comment]
@jimangel i've added that group to the dashboard, let me know if you are able to access/edit it.
