### ISSUE TITLE
Hello Minikube Command edit

### ISSUE THREAD

**Issue by rounaksarda** [kubernetes/website#27368]
Hello,

My Minikube Setup = windows->virtualbox->ubuntu->minikube.

Minikube itself provides the kubectl in it.

Simply writing "kubectl get pods" won't work instead we need to write "minikube kubectl get pods".

I we want to run the commands of kubectl then we need to write it e.g. "minikube kubectl -- [Command] [Options]"

**Comment by RA489** [comment]
@rounaksarda Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by rounaksarda** [comment]
Hello @RA489 elaborating the issue again:

open the link : https://kubernetes.io/docs/tutorials/hello-minikube/#open-dashboard-with-url
- The first command "minikube dashboard --url" will work fine.
- the second command "kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4" will give us the following error : 
![Screenshot (607)](https://user-images.githubusercontent.com/36100122/113471155-112bc680-9478-11eb-8a62-0df9d2c6792b.png)


In the above link we are talking about how to use the kubectl using minikube but the command will not work if we do not have the kubectl separately, though we have kubectl installed with minikube so to use kubectl(one inside the minikube) we need to write the command as starting with "minikube" eg. "minikube kubectl get pod". 

In the above picture we also seen that the command still won't work if we do not apply "--" which basically represent that we are gonna write kubectl command.

Hope this gives you little insight.

**Comment by sftim** [comment]
The existing page links to https://minikube.sigs.k8s.io/docs/start/ which clearly explains two options for interacting using `kubectl`. Either you _install_ it, or you use the copy bundled into `minikube`.

I think the existing page is clear enough. On the first mention of running `kubectl` we could remind readers to go and read https://minikube.sigs.k8s.io/docs/start/ if kubectl doesn't seem to work.

**Comment by rounaksarda** [comment]
@sftim ,  totally respecting to what you are saying but I was saying if you are telling to run the minikube(maybe for practice), the command should be written with respect to minikube. Right? As if you see the link[https://kubernetes.io/docs/tutorials/hello-minikube/#open-dashboard-with-url] , it is for minikube.
