### ISSUE TITLE
CronJob concept implies that CronJob can schedule one-shot tasks for a specific future date

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#27394]
**This is a Bug Report**

**Problem:**
The [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) concept page mentions:
> CronJobs can also schedule individual tasks for a specific time, such as scheduling a Job for when your cluster is likely to be idle.

This sounds like [`at`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/at.html), which can schedule one-shot tasks for a specific future date / datetime; however, that page strongly implies that CronJob does not in fact provide “run exactly once and never repeat” semantics.

Technically you could define a CronJob and a ServiceAccount and authnz rules that let the CronJob delete itself after it has successfully run once. I don't think we want to mention that bodge. I'd rather see an addon that gives you a OneShotScheduledJob CRD or similar.

**Proposed Solution:**

Remove or reword the text “CronJobs can also schedule individual tasks for a specific time, such as scheduling a Job for when your cluster is likely to be idle.”

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Additional Information:**
/kind bug
/sig apps

**Comment by sftim** [comment]
@kubernetes/sig-apps-misc could you confirm this and /triage accepted if you agree?

**Comment by sftim** [comment]
I logged this after adding feedback for the v1.21 release announcement: https://github.com/kubernetes/website/pull/27233#discussion_r606685195

**Comment by soltysh** [comment]
@sftim yeah, I like your proposed wording, are you going to open a PR?
/triage accepted

**Comment by sftim** [comment]
This issue is open for an interested contributor to work on. I already have some other PRs / work-in-progress that I'm going to focus on first.

**Comment by sftim** [comment]
The wording I suggested was:
> CronJobs are meant for performing regular scheduled actions such as backups, report generation, and so on. Each of those tasks should be configured to recur indefinitely (for example: once a day / week / month); you can define the point in time within that interval when the job should start.

**Comment by soltysh** [comment]
Lemme add that bit to https://github.com/kubernetes/website/pull/28229 where I'm updating CronJob related flag, in that case.

**Comment by soltysh** [comment]
This was fixed in https://github.com/kubernetes/website/pull/28229
/close
