### ISSUE TITLE
Mention Addon Resizer in “Considerations For Large Clusters”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#27409]
**This is a Feature Request**

**What would you like to be added**
Revise https://kubernetes.io/docs/setup/best-practices/cluster-large/ to mention the [addon resizer](https://github.com/kubernetes/autoscaler/tree/master/addon-resizer)

**Why is this needed**
You might not need need to manually resize addons as your cluster's scale changes: instead, you can let automation take care of that for you.

**Comments**
/kind feature
/language en

**Comment by sftim** [comment]
If we add this, I would mention it in the “What's next” section, as a hyperlink.

**Comment by sftim** [comment]
Possibly relevant to PR #27466

**Comment by vaibhav2107** [comment]
Fixed in PR #28458

**Comment by sftim** [comment]
Thanks!
/close
