### ISSUE TITLE
replace "hostPath" examples with "local" examples

### ISSUE THREAD

**Issue by geoffcline** [kubernetes/website#27439]
**This is a Feature Request**

**What would you like to be added**

Replace "hostPath" examples with "local" examples.

**Why is this needed**

This is a better practice for production, in terms of security and portability. 

**Comments**

Change the volumes page specifically. content/en/docs/concepts/storage/volumes.md

**Comment by sftim** [comment]
/sig storage
I guess

**Comment by sftim** [comment]
BTW the page @geoffcline wants to update is https://kubernetes.io/docs/concepts/storage/volumes/

**Comment by sftim** [comment]
@geoffcline could you explain a bit more about the change someone should make if they start work on this issue? I think I have an idea, but not everyone will have the same amount of context.

**Comment by Kartik494** [comment]
Hi @sftim rather removing hostpath example, we are having  local volumes [example](https://kubernetes.io/docs/concepts/storage/volumes/#local) here . So what else needs to be replace

**Comment by sftim** [comment]
/remove-lifecycle rotten

It'd be nice to explain the issue description more. Even so, someone can work on this already.
