### ISSUE TITLE
Extending Kubernetes

### ISSUE THREAD

**Issue by mason-liu** [kubernetes/website#27440]
Images which are located in docs.google.com are blocked by enterprise firewall, any plan to move the images to other places such as https://kubernetes.io/docs/?

**Comment by sftim** [comment]
Hi @mason-liu 

Can you identify the images that are blocked? For example, mention the URL of the documentation page that uses those images.

**Comment by mason-liu** [comment]
This page, https://kubernetes.io/docs/concepts/extend-kubernetes/, all images all blocked, such as https://docs.google.com/drawings/d/e/2PACX-1vQBRWyXLVUlQPlp7BvxvV9S1mxyXSM6rAc_cbLANvKlu6kCCf-kGTporTMIeG5GZtUdxXz1xowN7RmL/pub?w=960&h=720

**Comment by sftim** [comment]
This will affect all users behind a state-level censoring filter that blocks Google Docs.
/kind cleanup
/triage accepted
/language en
