### ISSUE TITLE
Improvement for k8s.io/ja/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by guitarrapc** [kubernetes/website#27457]
Ingress api version is still `apiVersion: networking.k8s.io/v1beta1`, while other langs are already `apiVersion: networking.k8s.io/v1`.

Old api version are on ...

* JP
* Indonesian

**Comment by sftim** [comment]
/language ja

@guitarrapc would you be willing to file a second issue about updating the bahasa Indonsia localization of the Ingress topic?

**Comment by shuuji3** [comment]
Thanks for filing the issue. This should be fixed by PR #27328 in the near future.

**Comment by sftim** [comment]
@shuuji3 I'm going to infer:
/triage duplicate

**Comment by guitarrapc** [comment]
@sftim sure, I've made an issue for Indonesia lang.

> https://github.com/kubernetes/website/issues/27465

**Comment by bells17** [comment]
It seems this issue was already resolved.
/close
