### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/events-stackdriver/

### ISSUE THREAD

**Issue by bahaa161** [kubernetes/website#27468]
**This is a Bug Report**

**Problem:**
The Stackdriver instructions on querying for events are outdated. 
As of now, the resource gke_cluster is deprecated, so these logs will show up under different resource types:
-  k8s_cluster
-  k8s_pod
-  k8s_node

**Proposed Solution:**
Update the page's "User Guide" section to use this filter instead:
```
(resource.type="k8s_cluster" OR resource.type="k8s_pod" OR resource.type="k8s_node")
logName:"logs/events"
```

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver#user-guide

**Comment by sftim** [comment]
@bahaa161 https://kubernetes.io/docs/tasks/debug-application-cluster/events-stackdriver doesn't exist. We removed it in PR #24769 which merged in February.
