### ISSUE TITLE
List All Container Images Running in a Cluster

### ISSUE THREAD

**Issue by BahmaniAlireza** [kubernetes/website#27475]
Hi,

I've tested this example :
```
      kubectl get pods --all-namespaces -o jsonpath="{..image}" |\
      tr -s '[[:space:]]' '\n' |\
      sort |\
      uniq -c
```

It returns image names double, because "{..image}" recursively search in the output of JSON, So at the first, it will find the "image" word in "spec.containers.image" and at the second time, it will find the "image" word in "containerStatuses.image".
It means you will see the image name two times for each pod at least.

Please change your example.

Best Regards,
Alireza Bahmani.

**Comment by sftim** [comment]
Hi @BahmaniAlireza 

What's the URL of the page where you've seen a problem?

**Comment by Priyankasaggu11929** [comment]
@sftim @BahmaniAlireza,

here are the links to the:
- kubernetes docs website page ~ https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/
- markdown file where it require changes ~ https://github.com/kubernetes/website/search?q=jsonpath%3D%22%7B..image%7D

**Comment by Priyankasaggu11929** [comment]
The issue is, the following command produces **2 times (the count of image in a single pod).**

As @BahmaniAlireza mentioned, it is because the command count both the occurrence from the `spec` & `status` sections from a single pod json manifest.

```
❯ kubectl get pods --all-namespaces -o jsonpath="{..image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c
      6 quay.io/app-sre/deployment-validation-operator:latest
      2 quay.io/openshift-release-dev/ocp-release@sha256:c7e8f18e8116356701bd23ae3a23fb9892dd5ea66c8300662ef30563d7104f39
      8 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:02cbb763ee20ba10a2eb54cc18e6cc5848b69ac991fd9b5a513d0c8a8ecdae91
      6 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:03cd77cc134a7bfcaa14c111b76234749b9b8cb0986ab25e2fb2afeb0ba7fb6b
      4 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:055d8e5c8a106134bf725bdd542e544285b5cd10a5e1c7e02d527c50f81ef0f5
      2 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:06633a70761c391052f3f5e482731a8fbbcf70df6aa082b8de916e04d0101f98
     10 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:249b4e56b532da7bf19c91ec620694d708743712dc028d9466fc236a5adcc54d
```

Ideally it should be:

```
❯ kubectl get pods --all-namespaces -o jsonpath="{..image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c
      3 quay.io/app-sre/deployment-validation-operator:latest
      1 quay.io/openshift-release-dev/ocp-release@sha256:c7e8f18e8116356701bd23ae3a23fb9892dd5ea66c8300662ef30563d7104f39
      4 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:02cbb763ee20ba10a2eb54cc18e6cc5848b69ac991fd9b5a513d0c8a8ecdae91
      3 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:03cd77cc134a7bfcaa14c111b76234749b9b8cb0986ab25e2fb2afeb0ba7fb6b
      2 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:055d8e5c8a106134bf725bdd542e544285b5cd10a5e1c7e02d527c50f81ef0f5
      1 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:06633a70761c391052f3f5e482731a8fbbcf70df6aa082b8de916e04d0101f98
     5 quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:249b4e56b532da7bf19c91ec620694d708743712dc028d9466fc236a5adcc54d
```

**Comment by Priyankasaggu11929** [comment]
Following could be one of the fix for it:

```
      kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}"  |\
      tr -s '[[:space:]]' '\n' |\
      sort |\
      uniq -c
```

**Comment by ms-choudhary** [comment]
@Priyankasaggu11929 There are other references [as well](https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/#list-container-images-filtering-by-pod-label). These would return duplicate images as well, right? I've updated those as well for now. 

```shell
kubectl get pods --namespace kube-system -o jsonpath="{..image}"
```

**Comment by Priyankasaggu11929** [comment]
Hi @ms-choudhary, 

yes, I feel those also need to be fixed. Let's wait for @sftim to provide their review. :)
