### ISSUE TITLE
Assign CPU Resources to Containers and Pods

### ISSUE THREAD

**Issue by chainhead** [kubernetes/website#27484]
Where can we get details of `vish/stress` image as referred to in examples on this page?

**Comment by sftim** [comment]
That's https://hub.docker.com/r/vish/stress/

Perhaps we should use a container image based on https://kernel.ubuntu.com/~cking/stress-ng/ instead? See https://github.com/ColinIanKing/stress-ng for source code, or look for another container image with clearly reputable provenance.

**Comment by chainhead** [comment]
@sftim I located the Docker Hub repo too ;) thanks! But, there is no source code, Git repo, etc. to it. So, there isn't much clarity on what it does.
