### ISSUE TITLE
Container runtimes - Bad URL for GnuPG Key?

### ISSUE THREAD

**Issue by fdamstra** [kubernetes/website#27498]
On the "Container Runtimes" page, under the instructions for Ubuntu, the second curl command errors out:

```
curl -L https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:$VERSION/$OS/Release.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg add -
```

Looks like that url is 404'd.

My variables are:
```
OS=xUbuntu_20.04
VERSION=1.21
```

It looks like maybe there isn't a 1.21 release of CRI-O? So I've also tried different formats for VERSION:
```
VERSION=1.21:1.21.0
VERSION=1.20
VERSION=1.20:1.20.2
```

**Comment by fdamstra** [comment]
Appears the correct line should maybe be:
```
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | sudo apt-key --keyring /etc/apt/trusted.gpg.d/libcontainers-cri-o.gpg add -
```

And that will work with:
```
VERSION=1.20
```

**Comment by sftim** [comment]
Aside: `apt-key add` is deprecated. Guides such as https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html explain how to use the new approach.
