### ISSUE TITLE
Unable to follow Ingress with NGINX task in Katacoda

### ISSUE THREAD

**Issue by HoustonPagtakhan1** [kubernetes/website#27493]
When I used the provided Terminal and run the command to apply the ingress file, it returns an error 
![image](https://user-images.githubusercontent.com/10050585/114235648-5434e080-9935-11eb-9d6b-d88619870956.png)
Do we need to update syntax of the ingress file?

Also, how does the port specified in the ingress (8080) correspond with the fact that the service gets a random port (in the 30000+) range assigned to it?

**Comment by sftim** [comment]
/team katacoda
/kind bug
The tutorial example doesn't yet support the GA version of Ingress

**Comment by sftim** [comment]
/retitle Unable to follow Ingress with NGINX task in Katacoda

**Comment by sftim** [comment]
/retitle Unable to follow Ingress with NGINX task in Katacoda

**Comment by sftim** [comment]
Similar to issue #24080

**Comment by sftim** [comment]
Fixed by #29616
