### ISSUE TITLE
I wish /docs/user-guide/kubectl/kubectl_create/ had a link to the reference page for creating a config file

### ISSUE THREAD

**Issue by rwillmer** [kubernetes/website#275]
I wish /docs/user-guide/kubectl/kubectl_create/ had a link to the reference page for creating a config file

It's great that the command documentation tells me that I can use a config file; it would be better if it linked directly to the reference page which told me how to write it.

**Comment by atbaker** [comment]
@rwillmer Do you feel this page would be the right one to link to? http://kubernetes.io/docs/user-guide/configuring-containers/

**Comment by rwillmer** [comment]
That looks good as an example of how to do it. A link to the reference page would also be good, either on the example page or on this page.

**Comment by jaredbhatti** [comment]
Good suggestion, however the docs are autogenerated so I need to look into a way of doing this without it being overwritten every time we generate docs.

**Comment by steveperry-53** [comment]
@rwillmer @atbaker @jaredbhatti Do we have a reference page for creating a config file? If so, can somebody point me to that page. We are going to be working on the ref docs soon, so we'll have an opportunity to do this.
