### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/common-labels/

### ISSUE THREAD

**Issue by ystoneman** [kubernetes/website#27505]
I've been following along with the Kubernetes Overview, in order. This page had the first somewhat confusing thing...why the example code for a "Service" always has the exact same code as its corresponding "Deployment" or "Stateful Set." 

Seems like blatant code duplication. I'm sure it will be explained later, and is probably obvious to people who are already familiar with K8, but it might be good to just acknowledge it here. Something like (my suggestion in bold):
> Consider the case for a simple stateless service deployed using Deployment and Service objects. The following two snippets represent how the labels could be used in their simplest form. **In the [Section Name] Section (with link), you'll learn why the following type of code duplication happens.**

I didn't make this a PR, because I don't know yet how to explain this myself.

**Comment by sftim** [comment]
For a Service and a Deployment that are used to declare a particular bit of a workload, the labels might be the same for no better reason than it's useful for the people who manage that workload if they're consistent.

If I have a database `mydb-sales1`, running MyDB, then I want to use that name everywhere.

It's that simple. Maybe the page needs to emphasize that we recommend making them match for the benefit of the _people_ looking after the components, ahead of having them match for other reasons (eg selectors).

**Comment by sftim** [comment]
/remove-lifecycle rotten
Let's go with the approach in https://github.com/kubernetes/website/issues/27505#issuecomment-818279397
/triage accepted
/priority backlog
