### ISSUE TITLE
container-runtime: migration guide points to a 404

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/website#27516]
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#migrating-to-the-systemd-driver-in-kubeadm-managed-clusters

includes the deadlink:

https://kubernetes.io/tasks/administer-cluster/kubeadm/configure-cgroup-driver

**Comment by neolit123** [comment]
/sig cluster-lifecycle node
i've added LGTM on the pending PR.

**Comment by neolit123** [comment]
/retitle container-runtime: migration guide point point to a 404

**Comment by neolit123** [comment]
this PR did not fix the problem:
https://github.com/kubernetes/website/pull/27518
because it lacks a leading `/`

i will send a new one.

**Comment by neolit123** [comment]
/retitle container-runtime: migration guide points to a 404

**Comment by neolit123** [comment]
new fix is here: https://github.com/kubernetes/website/pull/27619
