### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by mick62** [kubernetes/website#27521]
"When you inspect the Deployments in your cluster, the following fields are displayed:
    ...
    READY displays how many replicas of the application are available to your users. It follows the pattern ready/desired.
    AVAILABLE displays how many replicas of the application are available to your users."

The duplicated description "... displays how many replicas of the application are available to your users." for both fields raises the question about the subtle semantic differences. Please explain the semantic also by means of an example.

According to
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds there might be a short delay between the status Ready and Available.

**Comment by sftim** [comment]
Seems like a reasonable thing to explain more clearly.
/language en
/priority backlog
/triage accepted

**Comment by sftim** [comment]
Still a good idea
/remove-lifecycle rotten
