### ISSUE TITLE
Install and Set Up kubectl on macOS

### ISSUE THREAD

**Issue by janpeter123** [kubernetes/website#27522]
I can't UNINSTALL Kubectl from my computer

**Comment by sftim** [comment]
@janpeter123 we don't document how to uninstall `kubectl` but it is pretty much like how you uninstall any other tool.

On a POSIX-like system with uses package management, use the package manager to uninstall the package that provides `kubectl`. If you installed the executable file directly, `rm -i "$( type -p kubectl )"` removes it (bypassing any Trashcan-like mechanism).

For other operating systems, follow the instructions for your operating system. I don't think we'd document that level of detail.

**Comment by tengqm** [comment]
This topic is now covered by https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/
/close
