### ISSUE TITLE
K8s minor version expressions in release-1.xx branches

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27526]
**This is a Bug Report**

**Problem:**
For example,
in https://v1-19.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
> ## Version skew policy 
> The kubeadm tool of version v1.21 may deploy clusters with a control plane of version v1.21 or v1.20. kubeadm v1.21 can also upgrade an existing kubeadm-created cluster of version v1.20.
> 
> Due to that we can't see into the future, kubeadm CLI v1.21 may or may not be able to deploy v1.22 clusters.

Should we replace or not?
- `{{< skew latestVersion >}}` => `1.19` for branch `release-1.19`
- `{{< skew latestVersionAddMinor -1 >}}` => `1.18` for branch `release-1.19`
- ...

**Proposed Solution:**

**Pages to Update:**
- https://v1-19.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
- ...

**Files to Update:**

[Branch `release-1.18`]
1. content\en\docs\setup\production-environment\tools\kubeadm\create-cluster-kubeadm.md
1. content\en\docs\setup\release\version-skew-policy.md
1. content\id\docs\setup\production-environment\container-runtimes.md
1. content\id\docs\setup\production-environment\tools\kubeadm\create-cluster-kubeadm.md
1. ...

[Branch `release-1.19`]
1. content\en\docs\setup\production-environment\tools\kubeadm\create-cluster-kubeadm.md
1. content\en\docs\setup\release\version-skew-policy.md
1. content\en\docs\tasks\administer-cluster\cluster-upgrade.md
1. content\id\docs\setup\production-environment\container-runtimes.md
1. content\id\docs\setup\production-environment\tools\kubeadm\create-cluster-kubeadm.md
1. content\ja\docs\setup\production-environment\container-runtimes.md
1. content\ko\docs\setup\release\version-skew-policy.md
1. content\zh\docs\setup\production-environment\tools\kubeadm\create-cluster-kubeadm.md
1. content\zh\docs\setup\release\version-skew-policy.md
1. content\zh\docs\tasks\administer-cluster\cluster-upgrade.md
1. ...

[Branch `release-1.20`]
1. ...

**Comment by sftim** [comment]
I think we should fix the shortcode to use the _documented_ version, rather than the most recent release.
/sig cluster-lifecycle
/language en

**Comment by jihoon-seo** [comment]
- Related issue: #27525
- Related PR: #27542

**Comment by neolit123** [comment]
why do we have both https://github.com/kubernetes/website/issues/27525 and this issue.
can it be merged into a single one?

**Comment by jihoon-seo** [comment]
@neolit123 You are right!
I am closing this issue.
