### ISSUE TITLE
Need to fix K8s versions in release-1.20/kubeadm-upgrade.md

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27525]
**This is a Bug Report**

**Problem:**
The page https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
explains how to upgrade a Kubernetes cluster created with kubeadm from version 1.20.x to version 1.21.x, and from version 1.21.x to 1.21.y.
(Should be from version 1.19.x to version 1.20.x, and from version 1.20.x to 1.20.y.)

**Proposed Solution:**
In https://github.com/kubernetes/website/blob/release-1.20/content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- Replace
  - `{{< skew latestVersion >}}` => `1.20`
  - `{{< skew latestVersionAddMinor -1 >}}` => `1.19`
  - ...

**Page to Update:**
https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

/assign

**Comment by sftim** [comment]
I think we should fix the shortcode to use the _documented_ version, rather than the most recent release.
/sig cluster-lifecycle
/language en

**Comment by neolit123** [comment]
@sftim 

the intent behind `latestVersion` seems to be misleading if `site.Params.latest` is fed at build time pointing at the latest current k8s version. while extending the latestVersion shortcodes i expected `site.Params.latest` to be static and hardcoded per k/website release branch.

i can send PRs for this but i'd need to understand more about the "documented" version that you mentioned.

**Comment by neolit123** [comment]
^ @kubernetes/sig-docs-en-owners for additional opinions.

**Comment by sftim** [comment]
Despite a misleading name, `{{< skew latestVersion >}}` is supposed to use `site.Params.version` not `site.Params.latest`. AIUI.

**Comment by neolit123** [comment]
i can see `site.Params.latest` is being used in a few places:
https://github.com/kubernetes/website/search?q=%22site.Params.latest%22
should all of these be modified to use `site.Params.version` or only those in `layouts/shortcodes/skew.html`?

and for which branches - `master` and `dev-1.20`?

**Comment by sftim** [comment]
`site.Params.latest` is useful, it _does_ represent the most recent release.

**Comment by neolit123** [comment]
ok, i can PR the change for 1.20 and master since this is only a problem for the kubeadm upgrade docs.

`{{< skew latestVersion >}}` is also used here, but the versions there are just examples.
https://v1-20.docs.kubernetes.io/docs/setup/release/version-skew-policy/

**Comment by neolit123** [comment]
@sftim here are the PRs:
https://github.com/kubernetes/website/pull/27540
https://github.com/kubernetes/website/pull/27541
