### ISSUE TITLE
Interactive Tutorial - Exposing Your App

### ISSUE THREAD

**Issue by alghe-global** [kubernetes/website#27537]
_REF: https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

# Description

We're instructing students to expose a Service by way of `kubectl expose` using a label `type` of `NodePort`:

```
$ kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080
service/kubernetes-bootcamp exposed
```

We then instruct the student to list the services once again:

```
$ kubectl get services
NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes            ClusterIP   10.96.0.1      <none>        443/TCP          2m58s
kubernetes-bootcamp   NodePort    10.99.122.72   <none>        8080:31757/TCP   21s
```

# Expectation

In instruction notes, we're expecting from our students to read, understand and acknowledge that `expose` has assigned an external IP to the Service.

# Problem

However, in the output external-ip is `<none`> but rather you'd see a PORT NAT based assignment (which correlates to previous notes in the curriculum regarding `NodePort` exposure).

# Fix

We should rather point out at port NAT-ting omitting external IP (none is assigned).

**Comment by alghe-global** [comment]
# Debugging info

## `describe`

```
$ kubectl describe services/kubernetes-bootcamp
Name:                     kubernetes-bootcamp
Namespace:                default
Labels:                   run=kubernetes-bootcamp
Annotations:              <none>
Selector:                 run=kubernetes-bootcamp
Type:                     NodePort
IP:                       10.99.122.72
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  31757/TCP
Endpoints:                172.18.0.2:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

## `$NODE_PORT`

```
$ echo NODE_PORT=$NODE_PORT
NODE_PORT=31757
```

## `minikube ip`

```
$ curl $(minikube ip):$NODE_PORT
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-765bf4c7b4-fp5fr | v=1
```
```
$ echo $(minikube ip)
172.17.0.58
```

**Comment by sftim** [comment]
I think we should change
> We have now a running Service called `kubernetes-bootcamp`. Here we see that the Service received a unique cluster-IP, an internal port and an external-IP (the IP of the Node).

to explain that Minikube does _not_ assign an external IP here.

Would that fix be acceptable?

/language en

**Comment by alghe-global** [comment]
Yes.

--
; Alexandru Gheorghe
; <alghe.global [at] gmail [dot] com>
;
; Sent from mobile (please excuse any typos)

**Comment by alghe-global** [comment]
I'm unable to find the contents for this module that I can update in order to rephrase that section. Would someone point me to the right repo/dir so I can submit a request for code review on this issue?

Cloning `website` seems not to be enough in order to do these changes - unless I am missing something here.

**Comment by jxofficial** [comment]
Hi, I am working on a similar issue with updating the documentation, and I think you can make the related changes and pull request at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

Cheers!

**Comment by sftim** [comment]
@alghe-global would you be willing to revise the issue description based on https://github.com/kubernetes/website/issues/27537#issuecomment-818906495 ?

**Comment by sftim** [comment]
Also, if this is already fixed, let's close the issue.
