### ISSUE TITLE
Incorrect Stage values in FeatureGate documentation

### ISSUE THREAD

**Issue by brandond** [kubernetes/website#27539]
**Problem:**
Incorrect stage values in FeatureGate documentation

* LegacyNodeRoleBehavior has a stage of `True` as of 1.19, which is not a valid stage.
* WindowsEndpointSliceProxying has a stage of `beta` as of 1.21; all other stage values are capitalized.

Feature | Default | Stage | Since | Until
-- | -- | -- | -- | --
LegacyNodeRoleBehavior | true | True | 1.19
WindowsEndpointSliceProxying | true | beta | 1.21 |  

**Proposed Solution:**
Correct Stage text for listed FeatureGates

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by sftim** [comment]
That's not what I see on that page. Can you include a screenshot and confirm the URL you're viewing @brandond ?

If possible, it'd be useful to see the HTTP headers that go with the page you screenshotted.

**Comment by sftim** [comment]
Thanks @brandond

**Comment by shannonxtreme** [comment]
Is the change for `LegacyNodeRoleBehavior` from `True` to `Beta`, and add `1.21` to `Until`?

**Comment by sftim** [comment]
AIUI the change for `LegacyNodeRoleBehavior` is:
change the `Stage` column from `True` to `Beta`

and the change for `WindowsEndpointSliceProxying` is:
change the `Stage` column from `beta` to `Beta`

no other changes needed
