### ISSUE TITLE
Communicate Between Containers in the Same Pod Using a Shared Volume

### ISSUE THREAD

**Issue by vbeersma** [kubernetes/website#27531]
Hi,

I was wondering, on the page [Communicate Between Containers in the Same Pod Using a Shared Volume](https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/#:~:text=The%20primary%20reason%20that%20Pods,to%20communicate%20with%20each%20other.) it says 

> Notice that the second container writes the index.html file in the root directory of the nginx server.

with the code being

`echo Hello from the debian container > /pod-data/index.html`

However, the volumeMount for the nginx is 

    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html

For completion, the debian container config:

    - name: debian-container
      image: debian
      volumeMounts:
      - name: shared-data
        mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]

Am I getting it wrong or is the debian container not writing data in the nginx root directory?

**Comment by sftim** [comment]
@vbeersma the instructions should refer to the “website root” (sometimes called a “document root”) rather than the filesystem root.
I think with that clarification the page would be correct and not misleading.
/kind cleanup
/language en
