### ISSUE TITLE
Duplicate sections in 2 files

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27547]
**This is a Bug Report**

**Problem:**

There are duplicate sections in 2 files.
- (377 lines, Latest commit 2021-03-26) https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/access-application-cluster/access-cluster.md#accessing-services-running-on-the-cluster 
- (139 lines, Latest commit 2021-02-12) https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/administer-cluster/access-cluster-services.md 

**Proposed Solution:**

Remove duplicate part and
- Snippetize, or
- Make a link, or
- Something else

**Page to Update:**
- https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/
- https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/

**Comment by vaibhav2107** [comment]
I think a way is to remove the duplicate part from the https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/ and refer the link to https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/ in place of the removed part.
Please suggest if its the right way or how can be improved @jihoon-seo @sftim

**Comment by jihoon-seo** [comment]
- Resolved by #29078
