### ISSUE TITLE
Broken link in setup/production-environment/container-runtimes.md

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27550]
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/docs/setup/production-environment/container-runtimes/#migrating-to-the-systemd-driver-in-kubeadm-managed-clusters,
the link `Migration guide` is broken.

**Proposed Solution:**
In https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/container-runtimes.md

```diff
-Follow this [Migration guide](docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver)
+Follow this [Migration guide](/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/)
```

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#migrating-to-the-systemd-driver-in-kubeadm-managed-clusters

/assign

**Comment by neolit123** [comment]
already logged here:
https://github.com/kubernetes/website/issues/27516

/close
/sig cluster-lifecycle
