### ISSUE TITLE
Interactive Tutorial - Creating a Cluster Error

### ISSUE THREAD

**Issue by stewrad** [kubernetes/website#27556]
When running 'start' run into error below:

$ minikube start

W0414 17:03:21.074184    1208 main.go:170] Unable to make log dir /root/.minikube/logs: mkdir /root/.minikube/logs: input/output error
log: exiting because of error: log: cannot create log: open /tmp/minikube.minikube.root.log.WARNING.20210414-170321.1208: read-only file system

**Comment by sftim** [comment]
I think this report is about https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ and using the provided environment to try Minikube.

/kind bug
/team katacoda
