### ISSUE TITLE
Links to labels-annotations-taints are broken or outdated

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27565]
**This is a Bug Report**

**Problem:**
Links to labels-annotations-taints are broken
- In https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost ,
the link `controller.kubernetes.io/pod-deletion-cost` is broken.
- Some other links are outdated.

**Proposed Solution:**
- In `content/en/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md`
  - `https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#nodekubernetesioinstance-type`
  => `/docs/reference/labels-annotations-taints/#nodekubernetesioinstance-type`
  - `https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesioregion`
  => `/docs/reference/labels-annotations-taints/#topologykubernetesioregion`
  - `https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#topologykubernetesiozone`
  => `/docs/reference/labels-annotations-taints/#topologykubernetesiozone`
- In `content/en/blog/_posts/2020-09-03-warnings/index.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/#beta-kubernetes-io-arch-deprecated`
  => `/docs/reference/labels-annotations-taints/#beta-kubernetes-io-arch-deprecated`
- In `content/en/docs/concepts/scheduling-eviction/assign-pod-node.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/`
  => `/docs/reference/labels-annotations-taints/`
- In `content/en/docs/concepts/workloads/controllers/replicaset.md`
  - `/docs/reference/command-line-tools-reference/labels-annotations-taints/#pod-deletion-cost`
  => `/docs/reference/labels-annotations-taints/#pod-deletion-cost`
- In `content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/`
  => `/docs/reference/labels-annotations-taints/`
- In `content/en/docs/reference/_index.md`
  - `/docs/reference/kubernetes-api/labels-annotations-taints/`
  => `/docs/reference/labels-annotations-taints/`

[FYI: There exist redirect rules in `static/_redirects`]
```
/docs/api-reference/labels-annotations-taints/     /docs/reference/labels-annotations-taints/ 301
/docs/reference/kubernetes-api/labels-annotations-taints/ /docs/reference/labels-annotations-taints/ 301
```

[Optionally, add this line in `static/_redirects`]
```
/docs/reference/command-line-tools-reference/labels-annotations-taints/     /docs/reference/labels-annotations-taints/ 301
```

**Pages to Update:**
- https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost
- ...

/assign

**Comment by sftim** [comment]
/language en
/triage accepted

I agree with adding the new redirect.
