### ISSUE TITLE
Broken link to configure cgroup driver

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/website#27562]
**This is a Bug Report**

**Problem:**
There are two links to the configure cgroup driver task. one is working one is not:
* broken: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd ("Migration guide")
  * links to https://kubernetes.io/docs/setup/production-environment/container-runtimes/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver
* work: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ ("Configuring a cgroup driver")
  * links to https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

**Proposed Solution:**
Not sure what exactly is going wrong here. The task was initially linked the same way on both pages (`/tasks/administer-cluster/kubeadm/configure-cgroup-driver`) when it was introduced, but this got changed here: https://github.com/kubernetes/website/pull/27438/files (to `/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver`)

**Page to Update:**
https://kubernetes.io/...

We should probably check if this also affects other links

**Comment by franciosi** [comment]
Same at https://github.com/kubernetes/website/issues/27492

**Comment by franciosi** [comment]
I believe the right link for "Migration guide" should be https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

**Comment by sbueringer** [comment]
@franciosi Oh sorry my bad, didn't saw the other issue. I'll close mine
/close
