### ISSUE TITLE
Wrong command in "Pull an Image from a Private Registry" doc

### ISSUE THREAD

**Issue by ekuric** [kubernetes/website#27560]
I think `>` in below command should not be there and secret create fails 

```
kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=<path/to/.docker/config.json> \
    --type=kubernetes.io/dockerconfigjson
```

eg

``` 
kubectl create secret generic regcred --from-file=.dockerconfigjson=config.json> --type=kubernetes.io/dockerconfigjson
bash: --type=kubernetes.io/dockerconfigjson: No such file or directory
```
but also 

```
kubectl create secret generic regcred --from-file=.dockerconfigjson=confige.json --type=kubernetes.io/dockerconfigjson
```
creates secret without issue. 

Link to documentation: 
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by sftim** [comment]
> `<path/to/.docker/config.json>`

`<path/to/.docker/config.json>` is a sample. The Docker configuration is not really at `path/to/.docker/config.json`

We could emphasize in the docs that `<path/to/.docker/config.json>` is a sample.
