### ISSUE TITLE
Issue with /docs/user-guide/deployments/

### ISSUE THREAD

**Issue by sagarpatil23192** [kubernetes/website#2758]
The command mentioned below which is given to update the deployment doesn't work:
 kubectl set image deployment/nginx-deployment nginx=nginx:1.9.1

only the other command : kubectl edit deployment/nginx-deployment works fine. 
Please check and reply.

**Comment by Bregor** [comment]
Unexpected slash here.
Should be `kubectl set image deployment nginx-deployment nginx=nginx:1.9.1`

**Comment by ahmetb** [comment]
@sagarpatil23192 I just executed the tutorial and the `set image` command worked just fine. What error are you seeing? That said, I found a mistake that `apiVersion: apps/v1beta1` value should be in fact `extensions/v1beta1`.

@Bregor the slash syntax is valid and required (please refer to `kubectl set image --help`).

**Comment by Bregor** [comment]
@ahmetb yep, you are right. Sorry.

**Comment by ahmetb** [comment]
@sagarpatil23192 is this still valid?

**Comment by zacharysarah** [comment]
@ahmetb I'm adding a note here that the change you mentioned:

> `apiVersion: apps/v1beta1` value should be in fact `extensions/v1beta1`

...is actionable for docs. 👍 

@sagarpatil23192 If there's no further update, I recommend closing this issue after @ahmetb's note ☝️ is fixed.
