### ISSUE TITLE
Bugs in setup/release/notes.md

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27606]
**This is a Bug Report**

**Problem:**
There exist bugs in [setup/release/notes.md](https://github.com/kubernetes/website/blob/master/content/en/docs/setup/release/notes.md).

[Part number 1]
```Markdown
## Changelog since v1.20.0

# Release notes for v1.21.0-rc.0

[Documentation](https://docs.k8s.io/docs/home)

# Changelog since v1.20.0

## What's New (Major Themes)

### Deprecation of PodSecurityPolicy
```

[Part number 2]
```Markdown
## Dependencies

### Added
...

### Changed
...

### Removed
...

## Dependencies <!-- Duplicate -->

### Added <!-- Duplicate -->
...

### Changed <!-- Duplicate -->
...

### Removed <!-- Duplicate -->
...
```

**Proposed Solution:**
[Part number 1]
```Markdown
## Changelog since v1.20.0

## What's New (Major Themes)

### Deprecation of PodSecurityPolicy
```

[Part number 2]
```Markdown
## Dependencies

### Added
...

### Changed
...

### Removed
...
```

**Page to Update:**
https://kubernetes.io/docs/setup/release/notes/

/assign

**Comment by jihoon-seo** [comment]
[As-is]

```Markdown
## Downloads for v1.21.0

filename | sha512 hash
-------- | -----------
```

[To-be]

```Markdown
## Downloads for v1.21.0

### Source Code

filename | sha512 hash
-------- | -----------
```

**Comment by kbhawkey** [comment]
Hello @jihoon-seo .
Note: The release notes are auto-generated.
What do you think about logging an issue with the release team (release notes)?

**Comment by jihoon-seo** [comment]
Hi @kbhawkey.
Following your advice, I posted an [issue](https://github.com/kubernetes/sig-release/issues/1528) on [`kubernetes/sig-release`](https://github.com/kubernetes/sig-release).
Thank you!

**Comment by wilsonehusin** [comment]
👋🏼 release notes team here. yes this was autogenerated but we had to make manual fix to k/k (ref: https://github.com/kubernetes/kubernetes/pull/100968) a few days after the official release went out. i think it's the right move to fix it here as well 😄
