### ISSUE TITLE
Container-runtime : migration guide point point to a 404

### ISSUE THREAD

**Issue by survivant** [kubernetes/website#27618]
in the page : https://kubernetes.io/docs/setup/production-environment/container-runtimes/

the link (Migration guide) : 

````
Migrating to the systemd driver in kubeadm managed clusters
Follow this Migration guide if you wish to migrate to the systemd cgroup driver in existing kubeadm managed clusters
````

point to :  https://kubernetes.io/docs/setup/production-environment/container-runtimes/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver 

404 not found.

**Comment by neolit123** [comment]
duplicate here:
https://github.com/kubernetes/website/issues/27516

/close

**Comment by neolit123** [comment]
actually it was attempted as a fix here:
https://github.com/kubernetes/website/pull/27518/files
but that fix doesn't work due to a missing /

/reopen

**Comment by neolit123** [comment]
...never mind let's track it in the existing issue as it's still open
https://github.com/kubernetes/website/issues/27516
/close
