### ISSUE TITLE
Feature Gates list omits WatchBookmarks

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#27623]
**This is a Bug Report**

**Problem:**
(eg) https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#list-deployment-v1-apps mentions a feature gate `WatchBookmarks`. However, https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ does not. However, a feature gate named `WatchBookmark` (singular) _is_ listed.

**Proposed Solution:**
~Document `WatchBookmarks` in https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/~

Check whether the feature gate is named `WatchBookmark` or `WatchBookmarks` and update the code / documentation to match.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Kubernetes Version:**
v1.21

**Additional Information:**
/sig api-machinery
/language en
/kind bug

**Comment by tengqm** [comment]
The feature gate document is correct. The `WatchBookmark` gate is defined at https://github.com/kubernetes/apiserver/blob/master/pkg/features/kube_features.go#L122 .
The API reference is also generated from upstream source code. The incorrect reference of "WatchBookmarks" is located at https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L360. That is the thing we need to fix.

**Comment by sftim** [comment]
Let's log an upstream issue, link it to this report, and close this one.
