### ISSUE TITLE
Set up Ingress on Minikube with the NGINX Ingress Controller

### ISSUE THREAD

**Issue by zeev512** [kubernetes/website#27621]
Hello,
I try to follow the steps in the article and I fail on the installing of example-ingress.yaml step.
The error I get is as follows:
[zeev@localhost Kubernetes]$ kubectl apply -f example-ingress.yaml 
Error from server (InternalError): error when creating "example-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding

I use the following environment:
1. OS
[zeev@localhost Kubernetes]$ uname -a
Linux localhost.localdomain 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
2. minikube version
[zeev@localhost Kubernetes]$ minikube version
minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5
3. kubectl version
[zeev@localhost Kubernetes]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
4. The date of fresh installation of minikube and kubectl is half an hour before the date displayed on the terminal
[zeev@localhost Kubernetes]$ date
Tue Apr 20 09:42:42 IDT 2021

Regards.
Zeev Lazarev

**Comment by hcguersoy** [comment]
Observed same here with k8s in version 1.19.x.
Falling back to k8s 1.18.17, the error changes to `no matches for kind "Ingress" in version "networking.k8s.io/v1"`.

**Comment by Kartik494** [comment]
@zeev512  could you let me know the example yaml file so that it can be easy to test

**Comment by hcguersoy** [comment]
I run into the same issue then I follow the instructions in [Set up Ingress on Minikube with the NGINX Ingress Controller](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-a-minikube-cluster).
I'm configured k8s v1.20.6 to be used in minikube, inside hyperkit.

Starting up minikube with enabled ingress controller (sorry for some German comments inside):

```
😄  minikube v1.19.0 auf Darwin 11.3
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.20.6 preload ...
    > preloaded-images-k8s-v10-v1...: 492.29 MiB / 492.29 MiB  100.00% 10.96 Mi
🔥  Creating hyperkit VM (CPUs=4, Memory=4096MB, Disk=10240MB) ...
🐳  Vorbereiten von Kubernetes v1.20.6 auf Docker 20.10.4...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
minikube started
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
🔎  Verifying ingress addon...
🌟  The 'ingress' addon is enabled
```

The running pods:

```
kubectl get pods -n kube-system                                                     
NAME                               READY   STATUS    RESTARTS   AGE
coredns-74ff55c5b-9xnn7            1/1     Running   0          2m59s
etcd-minikube                      1/1     Running   0          3m16s
kube-apiserver-minikube            1/1     Running   0          3m16s
kube-controller-manager-minikube   1/1     Running   0          3m16s
kube-proxy-z947m                   1/1     Running   0          2m59s
kube-scheduler-minikube            1/1     Running   0          3m16s
storage-provisioner                1/1     Running   1          3m12s
```

Deployed and exposed the 'web' service:

```
kubectl get service web  
NAME   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
web    NodePort   10.107.196.240   <none>        8080:31315/TCP   10s

minikube service web --url
http://192.168.64.40:3131
```

Took the [example ingress definition](https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/service/networking/example-ingress.yaml) and saved it to a local file:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
```

Now trying to apply it:

```
kubectl apply -f example-ingress.yaml
Error from server (InternalError): error when creating "example-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding
```

Tried it with another, more minimalistic ingress definition:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress2
spec:
  defaultBackend:
    service:
      name: web
      port:
        number: 8080
```

But same result:

```
kubectl apply -f example-ingress2.yaml
Error from server (InternalError): error when creating "example-ingress.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding
```

**Comment by hcguersoy** [comment]
It works as described now with upgrade to the new minikube version `v1.20.0`, see https://github.com/kubernetes/minikube/issues/11115 and https://github.com/kubernetes/minikube/issues/11121

**Comment by sftim** [comment]
I think this is fixed now @zeev512 

Please re-open if I've misunderstood.
/close
