### ISSUE TITLE
示例：使用 MongoDB 部署 PHP 留言板应用程序

### ISSUE THREAD

**Issue by troub1emaker0911** [kubernetes/website#27620]
原文：
如果您希望访客能够访问您的留言板，您必须将前端服务配置为外部可见的，以便客户端可以从 Kubernetes 集群之外请求服务。然而即便使用了 ClusterIP Kubernets 用户仍可以通过 kubectl port-forwart 访问服务。

修改建议：
最后一句中应该为kubectl port-forward访问服务，单词拼错了。

**Comment by tengqm** [comment]
Fixed during last resync.
/close
