### ISSUE TITLE
kube-controller-manager --leader-elect-resource-lock default value in Chinese version page is not consistent with the English page

### ISSUE THREAD

**Issue by chenyahui** [kubernetes/website#27642]
kube-controller-manager --leader-elect-resource-lock default value in English page is 'leases'. As shown below:

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

<img width="862" alt="截屏2021-04-21 下午1 01 14" src="https://user-images.githubusercontent.com/6067594/115499233-a95fe300-a2a1-11eb-9c1b-dd5941d04c0b.png">

But in Chinese version page, this value is 'endpointsleases': 
https://kubernetes.io/zh/docs/reference/command-line-tools-reference/kube-controller-manager/

![image](https://user-images.githubusercontent.com/6067594/115499390-f2179c00-a2a1-11eb-8732-934030eb1691.png)

**Comment by tengqm** [comment]
The whole page has been resync'ed.  ( #28142)

/close
