### ISSUE TITLE
Some lines are too long in Markdown code

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#27657]
**This is a Bug Report**

**Problem:**
Some lines are too long in Markdown code.

- [intro-windows-in-kubernetes.md](https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md) ([raw](https://github.com/kubernetes/website/raw/master/content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md))
- [user-guide-windows-containers.md](https://github.com/kubernetes/website/blob/master/content/en/docs/setup/production-environment/windows/user-guide-windows-containers.md) ([raw](https://github.com/kubernetes/website/raw/master/content/en/docs/setup/production-environment/windows/user-guide-windows-containers.md))
- ...

It makes localization teams feel difficult to work.

For example,
`git diff upstream/dev-1.20-ko.7 upstream/dev-1.21-ko.1 -- content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md`
```diff
-Windows has strict compatibility rules, where the host OS version must match the container base image OS version. Only Windows containers with a container operating system of Windows Server 2019 are supported. Hyper-V isolation of containers, enabling some backward compatibility of Windows container image versions, is planned for a future release.
+##### Memory Reservations
+Windows does not have an out-of-memory process killer as Linux does. Windows always treats all user-mode memory allocations as virtual, and pagefiles are mandatory. The net effect is that Windows won't reach out of memory conditions the same way Linux does, and processes page to disk instead of being subject to out of memory (OOM) termination. If memory is over-provisioned and all physical memory is exhausted, then paging can slow down performance.
+
+Keeping memory usage within reasonable bounds is possible using the kubelet parameters `--kubelet-reserve` and/or `--system-reserve` to account for memory usage on the node (outside of containers). This reduces [NodeAllocatable](/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable). 
+
+{{< note >}}
+As you deploy workloads, use resource limits (must set only limits or limits must equal requests) on containers. This also subtracts from NodeAllocatable and prevents the scheduler from adding more pods once a node is full.
+{{< /note >}}
+
+A best practice to avoid over-provisioning is to configure the kubelet with a system reserved memory of at least 2GB to account for Windows, Docker, and Kubernetes processes.
+
+##### CPU Reservations
+To account for Windows, Docker and other Kubernetes host processes it is recommended to reserve a percentage of CPU so they are able to respond to events. This value needs to be scaled based on the number of CPU cores available on the Windows node.To determine this percentage a user should identify the maximum pod density for each of their nodes and monitor the CPU usage of the system services choosing a value that meets their workload needs.
```
![image](https://user-images.githubusercontent.com/46767780/115803068-18147c00-a41b-11eb-9295-f757ee2dbf77.png)

**Proposed Solution:**
Add some line breaks in Markdown code

**Page to Update:**
(All PRs which will be related to this issue should make no changes on k8s.io website pages.)

/language en
/assign

**Comment by sftim** [comment]
/priority awaiting-more-evidence

@jihoon-seo I think this could be a controversial policy change. We should discuss it and if adopting a policy, first we should document that within https://kubernetes.io/docs/contribute/ - then (maybe a 2nd commit in the same PR) we tweak the line endings.

My gut feeling is that different people will have different views on what we should do.

If we definitely don't like long lines, we could also add automation to warn when changes would add them.

**Comment by tengqm** [comment]
+1000 to break long lines!

**Comment by sftim** [comment]
I've added this to the agenda for the next SIG Docs weekly meeting.

**Comment by inductor** [comment]
Just one thing to note for putting new lines in a long sentence.
Japanese (and I believe Chinese too) does not have any blanks(" ") between each word in sentences. When you put a new line in Markdown it will be rendered as a blank. Even in Japanese team we have some discussion where we should put new line in a sentence or not but it basically brings unnecessary blank for us so it's not the "best".

So I would personally like more to ask if the long sentences can be split into a few sentences, then we can put new lines between them...

**Comment by tengqm** [comment]
My understanding of this issue is a little bit different. It looks to me that some contributors are not very familiar with Markdown syntax. The pain point is not about lines; it is about paragraphs. Maybe we, as members of the team, need to let the contributors know how Markdown paragraphs are processed. For example, the following one is not good because it puts all sentences into a single line for the version control system to parse.

```
Windows applications constitute a large portion of the services and applications that run in many organizations.  [Windows containers](https://aka.ms/windowscontainers) provide a modern way to encapsulate processes and package dependencies, making it easier to use DevOps practices and follow cloud native patterns for Windows applications.  Kubernetes has become the defacto standard container orchestrator, and the release of Kubernetes 1.14 includes production support for scheduling Windows containers on Windows nodes in a Kubernetes cluster, enabling a vast ecosystem of Windows applications to leverage the power of Kubernetes. Organizations with investments in Windows-based applications and Linux-based applications don't have to look for separate orchestrators to manage their workloads, leading to increased operational efficiencies across their deployments, regardless of operating system.
```

While the following revised version is a lot better:

```
Windows applications constitute a large portion of the services and
applications that run in many organizations.
[Windows containers](https://aka.ms/windowscontainers) provide a modern way to
encapsulate processes and package dependencies, making it easier to use DevOps
practices and follow cloud native patterns for Windows applications.
Kubernetes has become the defacto standard container orchestrator, and the
release of Kubernetes 1.14 includes production support for scheduling Windows
containers on Windows nodes in a Kubernetes cluster, enabling a vast ecosystem
of Windows applications to leverage the power of Kubernetes. Organizations
with investments in Windows-based applications and Linux-based applications
don't have to look for separate orchestrators to manage their workloads,
leading to increased operational efficiencies across their deployments,
regardless of operating system.
```

The outputs (i.e. the HTML snippets) generated from the above two formats are identical. There won't be any impact on performance or something else.

In some cases, the following format is acceptable too. In this example, the paragraph is organized into lines of different lengths. However, this organization might be easier for authors to organize the content. In other words, we do NOT have to impose hard constraints on how or where to insert line breaks. The key point is that we'd better break the long paragraphs somehow. It would benefit the reviewers for the English content and the translators for all other languages.

```
Windows applications constitute a large portion of the services and
applications that run in many organizations.
[Windows containers](https://aka.ms/windowscontainers) provide a modern way to
encapsulate processes and package dependencies, making it easier to use DevOps practices
and follow cloud native patterns for Windows applications.
Kubernetes has become the defacto standard container orchestrator,
and the release of Kubernetes 1.14 includes production support for scheduling Windows
containers on Windows nodes in a Kubernetes cluster,
enabling a vast ecosystem of Windows applications to leverage the power of Kubernetes.
Organizations with investments in Windows-based applications and
Linux-based applications don't have to look for separate orchestrators to manage their workloads,
leading to increased operational efficiencies across their deployments,
regardless of operating system.
```
