### ISSUE TITLE
cpu-default-namespace.md error

### ISSUE THREAD

**Issue by OrochW** [kubernetes/website#27665]
line 248 
kubectl create namespace default-cpu-example
kubectl delete namespace constraints-cpu-example

**Comment by Kartik494** [comment]
@OrochW could you provide example on which you find it incorrect so that it would be easy to resolve

**Comment by tengqm** [comment]
This issue is out of date. There is no line 248 in the page. There is no namespace named `constraints-cpu-example`.
/close
