### ISSUE TITLE
Add reference information for stable metrics

### ISSUE THREAD

**Issue by kbhawkey** [kubernetes/website#27682]
**This is a Feature Request**
Following on issue https://github.com/kubernetes/website/issues/24915, create reference information for
the list of stable metrics.

The list of stable metrics is mentioned in PR: https://github.com/kubernetes/website/pull/27421.

Investigate creating reference information in the docs for https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/testdata/stable-metrics-list.yaml.

**Comment by tengqm** [comment]
This one can be closed. Pls feel free to reopen if the issue still persists.
/close

**Comment by sftim** [comment]
Also see issue #32302
