### ISSUE TITLE
Persistent Volumes

### ISSUE THREAD

**Issue by awesomepras** [kubernetes/website#27681]
Link: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
Under the VolumePlugin - what does it mean by 'depends on the driver'.
It will be awesome if there is some hyperlink to describe some guide on how to setup the driver.

`CSI | depends on the driver`

**Comment by tengqm** [comment]
There is no single driver fo CSI volumes so such a link is impossible. CSI is a spec, not a driver implementation.
/close
