### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/field-selectors/

### ISSUE THREAD

**Issue by hobin2017** [kubernetes/website#27733]
Is it possible to use `metadata.annotations.field01=val01` to select objects? This confuse me since the `annotations` is a field of `metadata`. If it is possible, the field selector is more powerful than the label selector.

**Comment by sftim** [comment]
Field selectors only works with certain limited fields. See https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields

/kind support
