### ISSUE TITLE
Привіт Minikube not used local dokerfile

### ISSUE THREAD

**Issue by bm13kk** [kubernetes/website#27812]
This instruction used docker image from k8s repo, exactly `k8s.gcr.io/echoserver:1.4`.

But for clarity of tutorial, we should use an image, builded locally from `minikube/Dockerfile`

**Comment by sftim** [comment]
This is an issue about https://kubernetes.io/docs/tutorials/hello-minikube/ and, I think, specifically its Ukrainian localization.

**Comment by adamulacha** [comment]
@bm13kk - what do you mean that we should use an image builded locally from minikube/Dockerfile?
This step in a tutorial (https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-deployment) creates a deployment using an image on an external registry - k8s.gcr.io

**Comment by mtardy** [comment]
Since this issue is stale, has kind support, and never got more information, I will close it. Feel free to reopen it if you want to bring more information.

/triage needs-information
/close
