### ISSUE TITLE
Kubelet image credential provider docs should provide information on where to find exec plugin binaries

### ISSUE THREAD

**Issue by brandond** [kubernetes/website#27814]
**This is a Feature Request**

**What would you like to be added**
The [kubelet image credential provider](https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/) ([KEP-2133](https://github.com/kubernetes/enhancements/issues/2133)) documentation does not have any references as to where users can actually obtain the exec plugins. There is in fact only a single link provided, to the AWS ECR product page.

After conversation with @andrewsykim on Slack it appears there are at least two plugins available in the out-of-tree cloud provider repos (I have not personally validated that these implement the documented API):
AWS: https://github.com/kubernetes/cloud-provider-aws/tree/master/cmd/ecr-credential-provider
GCP: https://github.com/kubernetes/cloud-provider-gcp/tree/master/cmd/auth-provider-gcp
Azure: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/289

**Why is this needed**
Absent any more specific documentation, users are left trying existing image credential providers such as https://github.com/awslabs/amazon-ecr-credential-helper which are docker-specific and WILL NOT interoperate with the kubelet credential API.

**Comments**

**Comment by brandond** [comment]
Still an issue.

/remove-lifecycle rotten

**Comment by brandond** [comment]
Still waiting on this feature to see better use and documentation.

/remove-lifecycle stale

**Comment by tengqm** [comment]
@brandond Would you like propose a fix? It sounds to me the so called "credential provider" becomes something the kubernetes will need to function properly, once the feature is enabled, however, the kubernetes core doesn't provide a builtin implementation for this. We may add a short section on this as "third-party contents".

**Comment by brandond** [comment]
We've started maintaining a simple list of links to credential provider plugins in one of our projects: https://github.com/rancher/wharfie#image-credential-providers

It feels to me like the various cloud providers should own this - provide an official location for plugin binaries, and contribute docs to guide users to docs on how to install and use them - but in the mean time I could open a PR to add some basic links to the Kubernetes docs.

**Comment by andrewsykim** [comment]
A documented list of plugins sounds like a good idea, we can probably have a subsection in the existing kubelet credential provider docs as well
