### ISSUE TITLE
Create an annotated blog post template

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#27843]
**This is a Feature Request**

Blog post contributors have issues creating new blog posts. They sometimes miss basic formatting and style recommendations. 

Potential contributors might give up without trying if they have trouble finding or understanding our guidance.

Some contributors forge ahead without being aware of or following guidance. This wastes effort and goodwill during the review cycles.

Providing a template that embodies our best practices might encourage contributors, make their work easier, and produce better results. 

**What would you like to be added**

A hugo archetype to help contributors create a blog post.

**Why is this needed**

To improve the ease and initial quality of blog posts. To reduce review effort and queue-time. 

**Comments**

**Comment by rolfedh** [comment]
@sftim It's important to place this template where contributors are MOST likely to see it, even if they don't read the contributor guidelines. Does the blog tooling allow a directory like the one proposed without displaying the template as a blog post?

**Comment by sftim** [comment]
I would use an [archetype](https://gohugo.io/content-management/archetypes/) for this, and mention the archetype in the README etc.

**Comment by rolfedh** [comment]
> I would use an [archetype](https://gohugo.io/content-management/archetypes/) for this, and mention the archetype in the README etc.

Sounds like a good idea. I'll give it a try.

**Comment by cittizen-poey** [comment]
hi how I make a portfolio website
