### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by greijal18** [kubernetes/website#27868]
There is a rpm's pack issue with a install of redhat8 distr.
https://www.gitmemory.com/issue/kubernetes/kubernetes/95455/798812505

The same thing happend with a lot of people around the word

**Comment by neolit123** [comment]
I can reopen https://github.com/kubernetes/kubernetes/issues/95455

You can comment there.
/close
