### ISSUE TITLE
Broken anchor link

### ISSUE THREAD

**Issue by adriancuadrado** [kubernetes/website#27864]
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
Under **`ports.nodePort`** there is a link that points to https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport , but instead of `#type-nodeport` it should be `#nodeport`

**Comment by adriancuadrado** [comment]
I would do the change myself, but the damn cla doesn't allow me to do anything and no matter what I try it never works...
for instance here https://github.com/kubernetes/website/pull/27258 or here https://github.com/kubernetes/website/pull/26933

**Comment by sandipanpanda** [comment]
Hi @sftim this seems to be a good first issue which I am interested to fix. Should I make a new issue in https://github.com/kubernetes/kubernetes before making a PR?

/remove-lifecycle rotten

**Comment by sandipanpanda** [comment]
> This could actually be fixed [upstream](https://github.com/kubernetes/kubernetes/blob/8a70c48553d3e4420064b34de59aa8b3e748e12b/staging/src/k8s.io/api/core/v1/types.go#L4371-L4382)
> 
> @adriancuadrado You can visit https://github.com/kubernetes/kubernetes/issues/new/choose to log a bug report about that code, which includes the incorrect hyperlink (I'm afraid moving this issue there isn't particularly easy)

Can you please tell that whether I should make a PR in the master branch of K8s to fix this here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4364-L4375. Am I right?

**Comment by sandipanpanda** [comment]
I am interested to fix this issue.
/assign

**Comment by sandipanpanda** [comment]
Fixed in #30388 
/close
