### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by greijal18** [kubernetes/website#27867]
There is a rpm's pack issue with a install of redhat8 distr.
https://www.gitmemory.com/issue/kubernetes/kubernetes/95455/798812505

The same thing happend with a lot of people around the word

**Comment by sftim** [comment]
I'm afraid I didn't understand the issue description even after rereading it.

@greijal18 would you be willing to explain a bit more?

- which web page isn't right?
- what seems to be wrong?
- _optional_ the steps you think might help to improve that piece of documentation
  For example, you might be suggesting that we add a note to help people who are using RHEL 8 understand an error message that they are likely to see.


/triage needs-information

**Comment by neolit123** [comment]
closing until further details are provided.
please reopen at that point.

/close
