### ISSUE TITLE
concepts page for spanish links doesn't take to spanish pages

### ISSUE THREAD

**Issue by csantanapr** [kubernetes/website#27865]
**This is a Bug Report**

concepts page for spanish links doesn't take to spanish pages
https://kubernetes.io/es/docs/concepts/#objetos-de-kubernetes

**Problem:**
The page is the Spanish translation, the links on this page should take you to the Spanish version of the link when available, if not available then ok to leave it pointing to English

**Proposed Solution:**
Update the page links to point to Spanish version (ie. es)

**Page to Update:**
https://kubernetes.io/es/docs/concepts/#objetos-de-kubernetes

I intended to review and submit a PR

**Comment by raelga** [comment]
Thanks @csantanapr for the report, this is quite common as the translation is a work in progress and we don't have (yet) a way to easily detect where a page is referenced. Let me know if you have any issue working with the PR.

**Comment by csantanapr** [comment]
I will work on this page as one-off, and think about how can we automate the detection for all links that should point to the Spanish version.

**Comment by csantanapr** [comment]
Maybe something that can be done at build time? Don't know how is the site is build I guess Hugo but not how much pre-processing is done
