### ISSUE TITLE
Interactive Tutorial - Creating a Cluster - Cannot start minikube

### ISSUE THREAD

**Issue by madhusudhan-patha** [kubernetes/website#27907]

**Comment by madhusudhan-patha** [comment]
Getting below error while starting minikube
`
$ minikube start
W0507 15:04:10.444159    2324 main.go:173] Unable to create/truncate file /root/.minikube/logs/lastStart.txt: open /root/.minikube/logs/lastStart.txt: read-only file system
log: exiting because of error: log: cannot create log: open /tmp/minikube.minikube.root.log.WARNING.20210507-150410.2324: read-only file system`

**Comment by mtardy** [comment]
Same comment as here https://github.com/kubernetes/website/issues/27740#issuecomment-1252281698.

/close
