### ISSUE TITLE
Issue with /docs/admin/authorization/rbac/

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#2792]
This refers to the docs that are in preview at time of this issue:
https://kubernetes-io-vnext-staging.netlify.com/docs/admin/authorization/rbac/

**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
Docs should be split into Concept and Tasks.
Docs should explain simpler use cases first.

**Proposed Solution:**

Split into several docs:
- Task: assigning default roles. 
  -  For this task, say that it is assumed the user is a cluster administrator.
  - For this task, say it is assumed that cluster is already configured to use RBAC.  Point to "Setting up RBAC" Task for users missing this pre-req.
  - Explain what it means to bind a user or group to a cluster role.
  - No need to show the ClusterRole or Role object definition at this point.
  - steps to bind a user, a group, or an SA to a ClusterRole.
  - Explain different between cluster-wide and per-namespace 
  - steps to bind a user to a role within a namespace
- Task: create custom role
  - For this task, say that it is assumed the user is a cluster administrator.
  -  Explain rules and relation to REST paths.
  - Task to create a new ClusterRole.
  - Explain that all ClusterRoles can be used at cluster or namespace scope
- Task: editing a role
  - How to add a new permission to an existing Role
  - Move explanation of Auto-Reconciliation to this section as a warning about editing default roles.
- Task: delegating permission management to namespaces
  - Explain Privilege Escalation Prevention
  - Example: cluster admin creates namespace and grants admin to another user in that namespace.  Then second user can grant to third in that namespace, but not escalate.
- Explain how to setup on your cluster.
  - Have a "Task" called "enabling RBAC on your cluster".
  - Move "Bootstrapping" discussion to this Task. 
- Move Command-line utilities into individual tasks.
- Move explanation of Controller Roles, Core Component Roles,  and Discovery Roles to a separate Reference document on internals.

**Page to Update:**
http://kubernetes.io/docs/admin/authorization/rbac/

**Comment by tengqm** [comment]
Let's try keep this issue from rotten. We have seen many service requests on this topic.
/remove-lifecycle rotten
/lifecycle frozen

**Comment by sftim** [comment]
There are subtasks here would suit a contributor who already understands Kubernetes and is confident making a pull request to the English (main) localization. Maybe someone who has already picked up one issue and is looking for another.

I'll label this as help-wanted.
/help

**Comment by sftim** [comment]
As per the [content guide](https://kubernetes.io/docs/contribute/style/content-guide/), some of this proposed documentation might belong in the kops project.

/priority important-longterm

**Comment by sftim** [comment]
Closing in favor of issue #24414
/close
