### ISSUE TITLE
Document treatment of `$$` in container command/args and envvars

### ISSUE THREAD

**Issue by sbwsg** [kubernetes/website#27936]
**Problem:**

[Related Bug Report in Kubernetes project](https://github.com/kubernetes/kubernetes/issues/101137)
[Related Pull Request in Kubernetes project](https://github.com/kubernetes/kubernetes/pull/101254)

Several sections of Kubernetes' API reference (e.g. [Entrypoint](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#entrypoint), [Environment Variables](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables)) describe escaping variables of format `$$(VAR_NAME)` with the following:

> The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not.

What is not explicitly stated is that _any_ instance of the literal characters `$$` will be replaced with a single `$`, not just those paired with parens as a variable reference.  In other words, while `$$(` is replaced with `$(` so too is `$$` with `$`, `$$$$` with `$$`, and so on. This behaviour is [intentionally replicating the way the `make` command works](https://github.com/kubernetes/kubernetes/pull/101254#issuecomment-826943473) but again this is not explicitly stated as part of the API reference.

This was originally reported to Kubernetes [as a bug](https://github.com/kubernetes/kubernetes/issues/101137) with [an accompanying PR](https://github.com/kubernetes/kubernetes/pull/101254), but the proposed fix has been rejected since it breaks any existing users relying on the `$$` replacement.

**Proposed Solution:**

1. Clearly document that (for all the fields where escaping is performed) any occurrences of two dollar signs (literally `$$`) are always replaced with `$`, regardless of whether they're part of a variable reference or not.

Edit to add: apologies, the implemented behaviour is actually even more nuanced than this - if a string of format `$(eval echo \$$var1)` is passed then the two dollar signs are _not_ replaced, presumably because k8s interpreted `$(eval echo \$$var1)` as a reference to a variable named "eval echo \\$$var1".

2. Further, I'd like to suggest that the documentation capture the fact that the behaviour intentionally imitates `make`. I think this is useful context that is otherwise left to developers to intuit. As someone without much knowledge of `make` I wasn't able to reason my way to this inference and recognize why the behaviour is as it is ([evidence of which, in this thread](https://github.com/tektoncd/pipeline/issues/3871)).

**Page to Update:**

Ideally anywhere that the `$$(VAR_NAME)` escape syntax is documented. The locations I've been able to find so far are:
- https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#entrypoint
- https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables
- https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/ephemeral-containers-v1/#entrypoint
- https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/ephemeral-containers-v1/#environment-variables

Edit: Removed "This is a bug report" from the start of the description.

**Comment by sftim** [comment]
BTW, all the API documentation lives upstream - for example https://github.com/kubernetes/kubernetes/blob/2112bddae101b35934f1d66288449adf31243033/pkg/apis/core/types.go#L2103-L2107

We should however make the same thing clear for pages such as https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/#define-an-environment-dependent-variable-for-a-container
