### ISSUE TITLE
Kubernetes Documentation

### ISSUE THREAD

**Issue by 10raj** [kubernetes/website#27942]
kubectl get all                                                                                        

Error ::  Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

I am using it on windows 10 Edu 
version is latest 1.21

**Comment by sftim** [comment]
Is there a page where you're seeing access not working @10raj? If you want help for your own cluster, that wouldn't really be a documentation defect.

/triage needs-information
