### ISSUE TITLE
Switch Netlify to use Ubuntu Focal 20.04 build image

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#27948]
**This is a Feature Request**

**What would you like to be added**
Adjust Netlify to build https://kubernetes.io/ using a worker running Ubuntu 20.04 (currently: Ubuntu 16.04)

**Why is this needed**
The march of progress. 

**Comments**
This change happens in Netlify, not in Git.
Eventually Ubuntu 16.04 will go fully out of support.

**Comment by sftim** [comment]
How about we Just Do This, test a build, see if it works OK?

@kubernetes/sig-docs-leads how does that sound to folks?

**Comment by jimangel** [comment]
Strong +1 here! Thanks!

**Comment by kbhawkey** [comment]
Sure. I have not checked the Netlify docs. Are there any known issues?

**Comment by sftim** [comment]
Switched to 20.04 and triggered a [deploy](https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/60c002ad9c4e3000bf606992)

**Comment by sftim** [comment]
Looks good to me!

**Comment by kbhawkey** [comment]
OK. Saw this warning (unrelated to Ubuntu) in the deploy:
```
** WARNING **
7:52:43 PM: Using custom ruby version 2.7.1, this will slow down the build.
7:52:43 PM: To ensure fast builds, set the RUBY_VERSION environment variable, or .ruby-version file, to an included ruby version.
7:52:43 PM: Included versions: 2.6.2 2.7.2
```
Wondered if we need to bump up the ruby version again?

**Comment by bradtopol** [comment]
I am ok as well with bumping up the Ubuntu image. Progress!

**Comment by sftim** [comment]
Deploys including scheduled builds seem to be working OK.
/close

**Comment by sftim** [comment]
Reverted because builds were failing.

**Comment by sftim** [comment]
/reopen

Let's try again. The Xenial image is quite old.

**Comment by sftim** [comment]
/close
#28481 is the follow-up
