### ISSUE TITLE
RemainingItemCount feature gate incorrectly documented as alpha

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#27944]
[Feature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) lists RemainingItemCount as alpha but https://github.com/kubernetes/kubernetes/pull/81682 shows it went beta.

/kind bug
/language en
/sig api-machinery

**Comment by haardikdharma10** [comment]
What was the version when it was promoted to beta? (The PR seems quite old).
