### ISSUE TITLE
Adding Windows nodes

### ISSUE THREAD

**Issue by FalkWinkler** [kubernetes/website#27953]
Install containerd with powershell do not work with .\Install-Containerd.ps1 -ContainerDVersion v1.4.1.

The download url is 'https://github.com/containerd/containerd/releases/download/vv1.4.1/containerd-v1.4.1-windows-amd64.tar.gz'. 

 So ".\Install-Containerd.ps1 -ContainerDVersion 1.4.1." will work the command.

**Comment by sftim** [comment]
I think this might be a bug in https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/Install-Containerd.ps1 rather than in the Kubernetes documentation.

If so, you could report this via https://github.com/kubernetes-sigs/sig-windows-tools/issues/ @FalkWinkler

**Comment by sftim** [comment]
See https://github.com/kubernetes/website/issues/44248
