### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by ThomasWunderlich** [kubernetes/website#27974]
minikube version (and minikube start) fails because this is apparently running in a read-only version
I0513 04:10:50.086865   13742 out.go:229] Setting OutFile to fd 1 ...
log: exiting because of error: log: cannot create log: open /tmp/minikube.minikube.root.log.INFO.20210513-041050.13742: read-only file system

**Comment by sftim** [comment]
I don't think this is a support request - it sounds like a website bug. Albeit one that's intermittent and might have been fixed.
/remove-kind support

**Comment by ThomasWunderlich** [comment]
Closing this since I can't imagine this is debuggable at this point
