### ISSUE TITLE
Translate concepts/cluster-administration/system-logs in Korean

### ISSUE THREAD

**Issue by jm1223kim** [kubernetes/website#27976]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/cluster-administration/system-logs in Korean

**Why is this needed**
No Traslation concepts/cluster-administration/system-logs in Korean

**Comments**

Page to Update :
https://kubernetes.io/docs/concepts/cluster-administration/system-logs/

**Comment by ianychoi** [comment]
@jm1223kim: Looks like a great idea - would you kindly contribute for this part translation in Korean? While I understand that still many parts are not translated into Korean, it will be great if you clarify more demand/requirement why this module should be more prioritized in details, if you are unable to contribute translation on that part.

**Comment by seokho-son** [comment]
/triage accepted

@jm1223kim Hope to share schedule of Korean localization (dev) branch milestone :)
Current dev branch for Korean localization is dev-1.21-ko.2 (https://github.com/kubernetes/website/issues/27763)

Please note that Korean localization team will create dev-1.21-*ko.3* soon ~ ! (05/20~05/21)
I think dev-1.21-*ko.3* would be an appropriate work base for this issue :)

If you any question ~ please visit `kubernetes-docs-ko` slace channel.
https://kubernetes.slack.com/archives/CA1MMR86S

**Comment by seokho-son** [comment]
FYI: https://github.com/kubernetes/website/issues/28127
