### ISSUE TITLE
Installing Addons has outdated link to Flannel network plugin

### ISSUE THREAD

**Issue by jmorcar** [kubernetes/website#27979]
In kubernetes documentation page: https://kubernetes.io/docs/concepts/cluster-administration/addons/

There is an obsolete link to addon Flannel - > https://github.com/flannel-io/flannel/blob/master/Documentation/kubernetes.md (v1.15-16)

The latest documentation is in main README --> https://github.com/flannel-io/flannel#deploying-flannel-manually (v1.17+)

**Comment by sftim** [comment]
/retitle Installing Addons has outdated link to Flannel network plugin
/kind cleanup
/language en
/triage accepted
/good-first-issue

I agree with the fix that @jmorcar suggests
