### ISSUE TITLE
Non-existent script is being referenced

### ISSUE THREAD

**Issue by MartinKanters** [kubernetes/website#27982]
In the [contribute upstream guide](https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/#generating-the-openapi-spec-and-related-files) one of the steps is to run `hack/update-api-reference-docs.sh`, this file does not exist (anymore) in [kubernetes/hack](https://github.com/kubernetes/kubernetes/tree/master/hack). 
I'm not sure if it got renamed or removed, otherwise I would've made a PR.

**Comment by sftim** [comment]
/triage accepted

There might be an updated guide within https://k8s.dev/

**Comment by Priyankasaggu11929** [comment]
> I'm not sure if it got renamed or removed, otherwise I would've made a PR.

@MartinKanters, thanks for reporting. Below are links to the PR & the issue, that confirms for the script was removed:
- `PR`: [Remove swagger 1.2, swagger-ui #72924](https://github.com/kubernetes/kubernetes/pull/72924#issue-244844441)
- `issue`:  [Deprecating Swagger 1.2 in favor of OpenAPI (Move all internal tools to use OpenAPI) #38637 ](https://github.com/kubernetes/kubernetes/issues/38637#issue-195056333)

**Comment by tengqm** [comment]
Closing this since #28087 is being merged.
