### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by turanmehmet** [kubernetes/website#28000]
Documentation needs to be upgrade a Kubernetes cluster created with kubeadm from version 1.19.x to version 1.20.x 
https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
duplicate of:
https://github.com/kubernetes/website/issues/27525

/sig cluster-lifecycle
/close
