### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by couling** [kubernetes/website#28008]
The interactive tutorial seems to be missing a step.

> First we need to get the Pod name, and we'll store in the environment variable POD_NAME:

Okay so first we get the pod name, then what?  The tutorial seems to miss that completely.  The next thing it tells me is:

> In order for the new deployment to be accessible without using the Proxy, a Service is required which will be explained in the next modules.

... But it hasn't told me how to access the deployment using the proxy.

**Comment by sftim** [comment]
I think this issue is about https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by couling** [comment]
Apologies I should have added a link. Yes that's correct.

The information actually appears in a later module, but as a module in it's own right, this one is very confusing and left me spending 10+ minutes searching for what I'd missed before finally giving up and moving on.

**Comment by sftim** [comment]
That step is also in https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/ (step 2). Maybe the easiest change is to omit [the discussion of querying the Pod via the Kubernetes API's proxy to it] from https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
