### ISSUE TITLE
Kubernetes 组件

### ISSUE THREAD

**Issue by wy97** [kubernetes/website#28005]
On the page [https://kubernetes.io/zh/docs/concepts/overview/components/](url)
it seems that the comment of the term **service** mentioned in the part of **kube-proxy** is inappropriately shown considering the following html code.
_**data-original-title="将运行在一组 {{< glossary_tooltip text=&quot;Pods&quot; term_id=&quot;pod&quot; >}} 上的应用程序公开为网络服务的抽象方法。"**_
So basically the code here may be replaced with 
_**data-original-title="将运行在一组Pods上的应用程序公开为网络服务的抽象方法。"**_
according to the code above and the English version
_**data-original-title="A way to expose an application running on a set of Pods as a network service."**_.

**Comment by tengqm** [comment]
Looks like this has been fixed.
/close
