### ISSUE TITLE
Improvement for k8s.io/docs/concepts/cluster-administration/certificates/

### ISSUE THREAD

**Issue by trailstrider** [kubernetes/website#28009]
I've got a wildcard certificate on AWS that I can normally just use on a load balancer for TLS connections.  I'd really like to be able to just use that for my k8s cluster like I do for my other applications.  All of the doc pages that talk about certs and the ingress insist on using the lets encrypt setup, but our IT department doesn't allow that.  We have to use our own certs.

Its not clear how I set this up based upon the available documentation.  For existing applications, I just have all of the non-admin traffic cordoned off to the VPC so that the only way in and out for HTTP is through the load balancer where it is wrapped automatically with TLS.

**Comment by tengqm** [comment]
@trailstrider If I'm understanding this correctly, the question is about a vendor specific configuration option. Since the kubernetes website is not hosting such 3rd party contents, please check with the vendor about the details.
Feel free to reopen if I'm making mistakes.
/close
