### ISSUE TITLE
Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our [help wanted issues](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) :zap:

### ISSUE THREAD

**Issue by cleverndbest** [kubernetes/website#28019]
Thanks very much for contributing! Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. If you're looking for your next contribution, check out our [help wanted issues](https://github.com/github/docs/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) :zap:

_Originally posted by @github-actions in https://github.com/github/docs/pull/6414#issuecomment-842760515_

**Comment by shannonxtreme** [comment]
You may have clicked "reference in new issue" on the "Thank you for contributing" message in your original request :P
