### ISSUE TITLE
Patch Releases

### ISSUE THREAD

**Issue by ckulacoglu** [kubernetes/website#28012]
In https://kubernetes.io/releases/patch-releases/ the link for the "Release Managers" under Contact section leads to a 404 page

```
See the Release Managers page for full contact details on the Patch Release Team.
```
It links to https://kubernetes.io/release-managers.md which does not exist

**Comment by justaugustus** [comment]
Thanks for filing this, @ckulacoglu!
https://github.com/kubernetes/website/pull/27997 will resolve the issue. :)

/triage accepted
/sig release
/area release-eng
/assign
