### ISSUE TITLE
Unable to Set up High-Availability Kubernetes Multi Masters stack k8s cluster

### ISSUE THREAD

**Issue by a2z-ice** [kubernetes/website#28040]
I'm trying to setup HA cluster with stack topology my masters IPs are given below: 

k8-master01	172.17.9.141
k8-master02	172.17.10.25
k8-master03	172.17.9.13

**My HA proxy load balancer is 172.17.9.143**

Every IP is reachable with name from each other I have set the host name in /etc/hosts file :
[root@k8-master01 assad]# ping k8-master03
PING k8-master03 (172.17.9.13) 56(84) bytes of data.
64 bytes from k8-master03 (172.17.9.13): icmp_seq=1 ttl=63 time=0.688 ms
64 bytes from k8-master03 (172.17.9.13): icmp_seq=2 ttl=63 time=0.575 ms
64 bytes from k8-master03 (172.17.9.13): icmp_seq=3 ttl=63 time=0.474 ms
^C
--- k8-master03 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.474/0.579/0.688/0.087 ms
[root@k8-master01 assad]# ping k8-master02
PING k8-master02 (172.17.10.25) 56(84) bytes of data.
64 bytes from k8-master02 (172.17.10.25): icmp_seq=1 ttl=63 time=0.549 ms
64 bytes from k8-master02 (172.17.10.25): icmp_seq=2 ttl=63 time=0.469 ms
64 bytes from k8-master02 (172.17.10.25): icmp_seq=3 ttl=63 time=0.427 ms
^C
--- k8-master02 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.427/0.481/0.549/0.056 ms

My ip configuration for k8-master01 and k8-master02 are given below :
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 3a:af:65:0c:12:5d brd ff:ff:ff:ff:ff:ff
    inet 172.17.9.141/27 brd 172.17.9.159 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::7471:738d:2cbd:7d3c/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:f7:70:63:63 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global docker0
       valid_lft forever preferred_lft forever

---------------------------ip a----------k8s-master02-------------
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 4a:01:8a:79:70:d6 brd ff:ff:ff:ff:ff:ff
    inet 172.17.10.25/26 brd 172.17.10.63 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::af18:a903:7d05:d104/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:47:e2:73:d4 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global docker0
       valid_lft forever preferred_lft forever

After init command my configuration works fine on my k8-master01 and is also working as expected. However when I run the join command from second master (k8-master02) then my full cluster goes down and my etcd container from both k8-master01 and k8-master02 keep restarting 

The init command I use is as follow:
kubeadm init --control-plane-endpoint="172.17.9.143:6443" --upload-certs --apiserver-advertise-address=172.17.9.141 --pod-network-cidr=192.168.0.0/16

And it give me following output :

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of the control-plane node running the following command on each as root:

  kubeadm join 172.17.9.143:6443 --token jsnppo.i8jjr5t8pas0mw8y \
        --discovery-token-ca-cert-hash sha256:41c774913dd3d1b3ff1e8b4cb6049c1a6d9439e85a7f4c09d09891a546748e23 \
        --control-plane --certificate-key 78a6fe8f54f526572c2cfe3a494031681181a7bd20724032dd1f1e131ec2cde5

Please note that the certificate-key gives access to cluster sensitive data, keep it secret!
As a safeguard, uploaded-certs will be deleted in two hours; If necessary, you can use
"kubeadm init phase upload-certs --upload-certs" to reload certs afterward.

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 172.17.9.143:6443 --token jsnppo.i8jjr5t8pas0mw8y \
        --discovery-token-ca-cert-hash sha256:41c774913dd3d1b3ff1e8b4cb6049c1a6d9439e85a7f4c09d09891a546748e23

But when I run join command using following from k8-master02	 (172.17.10.25):

 kubeadm join 172.17.9.143:6443 --token jsnppo.i8jjr5t8pas0mw8y --apiserver-advertise-address=172.17.10.25 \
        --discovery-token-ca-cert-hash sha256:41c774913dd3d1b3ff1e8b4cb6049c1a6d9439e85a7f4c09d09891a546748e23 \
        --control-plane --certificate-key 78a6fe8f54f526572c2cfe3a494031681181a7bd20724032dd1f1e131ec2cde5

After that my etcd container in both k8-master01 and k8-master02 keep restarting. Need help:

The installation I followed is given below:
https://docs.google.com/document/d/e/2PACX-1vTOxeQFBmzqiNjz_sejBOxvs69em5sKCGpHeg7PjNAFv4eOrD8pyLIj3caG73gjfnoAbFIoNQOJSl-d/pub

**Comment by sftim** [comment]
/kind support

@a2x-ice this list of issues is for reporting defects in https://kubernetes.io/docs/ and related pages.

https://docs.google.com/document/d/e/2PACX-1vTOxeQFBmzqiNjz_sejBOxvs69em5sKCGpHeg7PjNAFv4eOrD8pyLIj3caG73gjfnoAbFIoNQOJSl-d/pub isn't a page that the Kubernetes project supports.

**Comment by neolit123** [comment]
you can try finding / contacting the author of the mentioned document.
for help you can try asking in the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
