### ISSUE TITLE
Link from https://k8s.io/ to download page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28054]
**This is a Feature Request**

**What would you like to be added**
https://kubernetes.io/ should hyperlink to https://kubernetes.io/releases/download/

**Why is this needed**
This change will make it easier for visitors to find the download page.

**Comments**
/kind feature

**Comment by rounaksarda** [comment]
@sftim Hi, for the issue, should we add a button on this link ("https://kubernetes.io/"), right after the text that says "Learn Kubernetes basics"

**Comment by sftim** [comment]
/language en
(other localizations will copy this approach)

**Comment by rounaksarda** [comment]
@sftim, got it. I will fork and make changes in a separate branch and will share its link after hosting on netlify

**Comment by sftim** [comment]
If you open a pull request, you get a Netlify preview for free!

**Comment by sftim** [comment]
> Since https://kubernetes.io/ should hyperlink to https://kubernetes.io/releases/download/ . Do we need to update every link in any text format on K8s website?

(a question that @NitishKumar06 asked)

I don't understand that question. We don't need to _update_ any links. Instead, we need to _add_ a link. The page we will update is https://kubernetes.io/ and we will add some new text that links to https://kubernetes.io/releases/download/

**Comment by sftim** [comment]
Although PR #37099 merged, _this_ issue still needs a fix.

**Comment by NitishKumar06** [comment]
@sftim I'm looking to carrying this forward. Could you provide a little context on which file the link is found? Do we have to change the link in a file wherever it's mentioned?

**Comment by sftim** [comment]
I'll let someone else answer where to find the source file for https://k8s.io/ - that's a good way for another person to contribute.
