### ISSUE TITLE
Tidy service availability for “DNS for Services and Pods”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28059]
**This is a Feature Request**

**What would you like to be added**
Remove the section https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#feature-availability

Add a [feature state shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#feature-state) to the start of the page, declaring that the feature is stable from v1.14

**Why is this needed**
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#feature-availability lists feature availability, but all listed versions are out of support. We can document the feature as unconditionally available.

**Comments**
/language en
/help

**Comment by chenxuc** [comment]
I can help this issue.
/assign
/triage accepted
