### ISSUE TITLE
Search UI result issue

### ISSUE THREAD

**Issue by calshankar** [kubernetes/website#28053]
**This is a UI Bug Report**

**Problem:**
When I search with some keywords, I see multiple lines (3-4) for each matched entry, making the search result awry, basically UX is bad. I see the font size too changed which makes the results look gaudy..

**Proposed Solution:**
Kindly revert to the previous version of the search UI where each entry has no more than 1 line description metadata..

**Comment by sftim** [comment]
/area web-development

I think the search UI is managed by Google (or, if you're behind a corporate / national firewall that blocks Google, Bing).
