### ISSUE TITLE
Not getting new ip on tiny proxy deployed on AKS

### ISSUE THREAD

**Issue by rrathord1885** [kubernetes/website#28058]
HI, I have deployed tiny proxy solution on AKS. its deployed successfully. Currently we are using 3 Nodes and 5 pods. so  we can say 5 services are running and also 1 public LB is attached. so all traffic will with this LB. if I am using whatmyip to check the what ip is returned from service. its returning only 1 ip. but i am expecting if 5 pods are running then its should return 5 ips.
Can you pls. some one look on this why its returning 1 ip?

**Comment by rrathord1885** [comment]
HI, Any updates on my query ?

**Comment by rrathord1885** [comment]
Guys , Any update  on this ?

**Comment by tengqm** [comment]
This issue is not relevant to kubernetes core, and it is not a documentation question. Please check with the Azure team/website for support.
/close
