### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by Ivo-Peterka** [kubernetes/website#28062]
I was looking for list of valid statuses for namespace. At least some link to such information on this page would be useful.

**Comment by sftim** [comment]
This page could link to https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/

/triage accepted
/language en
/priority backlog

**Comment by pacoxu** [comment]
> A namespace can be in one of two phases:
> 
> - Active the namespace is in use
> - Terminating the namespace is being deleted, and can not be used for new objects
> 
> See the [design doc](https://git.k8s.io/community/contributors/design-proposals/architecture/namespaces.md#phases) for more details.

A paragraph in https://kubernetes.io/docs/tasks/administer-cluster/namespaces/ 😄

**Comment by hardikshah197** [comment]
May I take up this task? @pacoxu @sftim if it is open.

**Comment by hardikshah197** [comment]
May I take up this task? @pacoxu @sftim if it is not resolved.

**Comment by hardikshah197** [comment]
I have attached the PR for this issue #28109

**Comment by sftim** [comment]
Also see [#28109 (comment)](https://github.com/kubernetes/website/pull/28109/files#r651153705)&mdash;about updating the upstream docs.

**Comment by hardikshah197** [comment]
I made the suggested changes, requested by you, [see here](https://github.com/kubernetes/website/pull/28109#discussion_r651174544)

**Comment by vaibhav2107** [comment]
Can close this issue, fixes in #28109
/close
