### ISSUE TITLE
Grammatically incorrect and ambiguous sentence in Interactive Tutorial

### ISSUE THREAD

**Issue by jxofficial** [kubernetes/website#28077]
**Grammatically incorrect and ambiguous sentence in Interactive Tutorial - Updating Your App (Step 2)**

**Problem:**
The problematic sentence is 

> We run now version 2 of the app (look at the Image field)

"We run now" is grammatically incorrect and ambiguous. It could mean "let's run the version 2 of the app" or "version 2 of the app is now running". In the context of the tutorial, the second one is correct. 

**Proposed Solution:**
Change the sentence to: "We are now running version 2 of the app (refer to the Image field)."

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-interactive/

**Comment by shannonxtreme** [comment]
It doesn't look like the interactive tutorials repo has had much activity for its PRs...is there anything I can do on my end to push it along?

**Comment by shannonxtreme** [comment]
Fixed in https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/37

**Comment by sftim** [comment]
This is OK to close, right? Anything more we need to do to fix it?

**Comment by shannonxtreme** [comment]
Nope, good to close!

**Comment by sftim** [comment]
Thanks @shannonxtreme 
/close
