### ISSUE TITLE
Azure AKS supports allocation of public IP dynamically, but allocation public IP per request is possible ?

### ISSUE THREAD

**Issue by rrathord1885** [kubernetes/website#28095]
Hi Team,
Azure AKS supports allocation of public IP dynamically in LB, but allocation public IP in LB per request is possible ?
Pls. advice on this ?
Thanks,
Sanjeev Singh

**Comment by rrathord1885** [comment]
Guys , Any update  on this ?

**Comment by tengqm** [comment]
/kind support
Please check with Azure team on this. The website project doesn't include vendor specific details which are treated as third party contents.
