### ISSUE TITLE
[ko] Translate docs/tasks/configure-pod-container/configure-gmsa in Korean

### ISSUE THREAD

**Issue by jmyung** [kubernetes/website#28101]
**This is a Feature Request**
Translate docs/tasks/configure-pod-container/configure-gmsa in Korean

**What would you like to be added**

Translate docs/tasks/configure-pod-container/configure-gmsa in Korean

**Why is this needed**
No Translation yet.

**Comments**

https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/

**Comment by minhduc19** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ] #28070

**Comment by jihoon-seo** [comment]
Translated page:
https://kubernetes.io/ko/docs/tasks/configure-pod-container/configure-gmsa/

Resolved by
- #30024
- #30412

/close
