### ISSUE TITLE
 pods scheduled on different node cannot communicate with each other on kubernetes cluster using calico network

### ISSUE THREAD

**Issue by irfansheikh777** [kubernetes/website#28132]
I am facing  this issue troubleshooting long time issue is  I have create Kubernetes cluster with calico network in my on premises server the **pods scheduled  on  different node on this Kubernetes cluster not able to communicate to each other **  . please chcek below scenarios. 
There are two worker node **server9** and **server10**
Two PODS are created on server 9 and  one pod created on server 10 as u can see below.
pods wit same node are bale to communicate with each other but pod on another node is not able to communicate with each other.
Can you please   help me to resolve this as there is no communication between this pods which is issue for application level cluster

![image](https://user-images.githubusercontent.com/29003677/119655281-75e11d00-be3a-11eb-94a1-e2158fbab2e5.png)
![image](https://user-images.githubusercontent.com/29003677/119655374-90b39180-be3a-11eb-9028-b0db73359875.png)

**Comment by tengqm** [comment]
/remove-kind bug
/kind support

This doesn't smell like a documentation issue. Please try other channels for tech support.

**Comment by HongjiangHuang** [comment]
Please use https://github.com/kubernetes/kubernetes.

/close
