### ISSUE TITLE
Fails: Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by erikv85** [kubernetes/website#28168]
Fails to load entirely. In Chrome Version 91.0.4472.77 (Official Build) (64-bit) this is what I see after pressing "Start scenario":

$ sleep 1; launch.sh
Starting Kubernetes. This is expected to take less than a minute....packet_write_wait: Connection to 172.17.0.10 port 22: Broken pipe

The environment has expired.

Please refresh to get a new environment.

**Comment by jihoon-seo** [comment]
As of today (2021-06-03):

```
Kubernetes Bootcamp Terminal

$ sleep 1; launch.sh
Starting Kubernetes. This is expected to take less than a minute......
Kubernetes Started

$
```
