### ISSUE TITLE
404 for the cherry-pick link url in "Kubernetes Release Cycle" page

### ISSUE THREAD

**Issue by llhuii** [kubernetes/website#28162]
In the ["Kubernetes Release Cycle" page](https://kubernetes.io/releases/release/), there are two places linking for cherry-pick https://kubernetes.io/contributors/devel/sig-release/cherry-picks.md which is 404.

It seems that it should be https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md.

snapshots:
1. 
![image](https://user-images.githubusercontent.com/419660/120056089-aa3c1f80-c06c-11eb-8b10-8c3a4305f2b6.png)
2. another one:
![image](https://user-images.githubusercontent.com/419660/120055989-0fdbdc00-c06c-11eb-9f0a-66c436a1e81b.png)

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue!
