### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by dimay2** [kubernetes/website#28170]
Katacoda terminal screen stuck. tried multiple times Google page reload, clear cache. doesnt help

**Comment by jihoon-seo** [comment]
As of today (2021-06-03):

```
Kubernetes Bootcamp Terminal

$ sleep 1; launch.sh
Starting Kubernetes. This is expected to take less than a minute......
Kubernetes Started

$
```

**Comment by sftim** [comment]
/label team/katacoda
/priority awaiting-more-evidence

@dimay2 have the symptoms disappeared?

**Comment by dimay2** [comment]
> /label team/katacoda
> /priority awaiting-more-evidence
> 
> @dimay2 have the symptoms disappeared?

all ok. 10x.

**Comment by jihoon-seo** [comment]
@dimay2 😊
/close
