### ISSUE TITLE
[ko] Bug in ko/docs/concepts/scheduling-eviction/assign-pod-node

### ISSUE THREAD

**Issue by sysnet4admin** [kubernetes/website#28217]
nodeName 은 가장 간단한 형태의 노트 선택 제약 조건이지만, 한계로 인해 일반적으로는 사용하지 않는다. nodeName 은 PodSpec의 필드이다. 만약 비어있지 않으면, 스케줄러는 파드를 무시하고 명명된 노드에서 실행 중인 kubelet이 파드를 실행하려고 한다. 따라서 만약 PodSpec에 nodeName 가 제공된 경우, 노드 선텍을 위해 위의 방법보다 우선한다.

'노드 선택을 위해'
로 수정해야 할 것 같습니다. 오타가 있네요

**Comment by jihoon-seo** [comment]
/retitle [ko] Bug in ko/docs/concepts/scheduling-eviction/assign-pod-node
/kind bug
/language ko
/assign

**This is a Bug Report**





**Problem:**
[ko] Bug in ko/docs/concepts/scheduling-eviction/assign-pod-node

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node/#nodename

**Comment by seokho-son** [comment]
@sysnet4admin 오번역 리포트 감사합니다!! ^^
혹시 이번 기회에 직접 PR로 기여를 해보고 싶으시다면 진행해주셔도 좋을 것 같습니다.
(@jihoon-seo 님~~ 혹시 작업 시작하신 것이 아니라면, @sysnet4admin 께서 혹시 기여하고 싶으신지 확인 후에 진행해도 될까요?^^)

**Comment by sysnet4admin** [comment]
안녕하세요.

그렇게하도록 권유주신다면, PR 넣도록 하겠습니다. (in 2days)

이것 말고도 여러개 보였는데 그냥 스치듯 지나갔었는데..
앞으로는 쿠버네티스 한글화에 도움이 되도록 contribution하는 방향으로 진행토록 하겠습니다. 감사합니다.

조훈 드림.
________________________________
보낸 사람: Seokho Son ***@***.***>
보낸 날짜: 2021년 6월 5일 토요일 오후 8:41
받는 사람: kubernetes/website ***@***.***>
참조: Hoon Jo ***@***.***>; Mention ***@***.***>
제목: Re: [kubernetes/website] [ko] Bug in ko/docs/concepts/scheduling-eviction/assign-pod-node (#28217)


@sysnet4admin<https://github.com/sysnet4admin> 오번역 리포트 감사합니다!! ^^
혹시 이번 기회에 직접 PR로 기여를 해보고 싶으시다면 진행해주셔도 좋을 것 같습니다.
***@***.***<https://github.com/jihoon-seo> 님~~ 혹시 작업 시작하신 것이 아니라면, @sysnet4admin<https://github.com/sysnet4admin> 께서 혹시 기여하고 싶으신지 확인 후에 진행해도 될까요?^^)

**Comment by seokho-son** [comment]
@sysnet4admin 감사합니다 !! ^^ 자발적인 기여에 의해 진행되고 있어서 아직 부족한 부분이 많이 있을 거예요. 함께 만들어나가면 좋을 것 같습니다. 혹시 작업 중에 궁금한 사항은 이슈나 슬랙 체널에 참여하셔서 편하게 문의 주시면 됩니다. (https://kubernetes.slack.com/archives/CA1MMR86S)
해당 PR은 https://github.com/kubernetes/website/issues/28287 를 참고하셔서, dev-1.21-ko.4 브랜치를 기준으로 작업해주시면 되겠습니다..^^

@jihoon-seo 님 ~~ 해당 이슈는 새로운 컨트리뷰터께 할당하면 좋을 것 같습니다! 감사합니다^^

/unassign @jihoon-seo 
/assign @sysnet4admin

**Comment by sysnet4admin** [comment]
@seokho-son 넵 도움에 감사드립니다. 
지금도 충분히 성숙되어 있지만, 더 좋아지는 쿠버네티스 한글화를 위해 열심히 기여하도록 하겠습니다. 감사합니다.

**Comment by seokho-son** [comment]
Fixed by #28297
/close
