### ISSUE TITLE
Error "413 Request Entity Too Large" while request goes between containers using service discovery.

### ISSUE THREAD

**Issue by kcgochar** [kubernetes/website#28231]
Hi,

We are getting error "413 Request Entity Too Large" when doing HTTP post with several mbs of data in the request body. The request goes between containers using service discovery. 

Based on the error, I first thought that maybe the problem is between browser and ui container and I need to add nginx.ingress.kubernetes.io/proxy-body-size annotation to the load balancer based on https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size . This did not work since the problem seems to be in the internal load balancer for the service discovery. 

We had this issue earlier from user's browser to web UI but that was fixed as we lifted the limitation of size  by changing limit to 50MB for main ingress load balancer. This problem is specific to internal container communications.

**Comment by HongjiangHuang** [comment]
Hello, @kcgochar. questions about `ingress-nginx`, please use https://github.com/kubernetes/ingress-nginx/issues/new/choose

**Comment by tengqm** [comment]
/kind support
This is not the right place to ask non-documentation questions.
/close

**Comment by kcgochar** [comment]
thank you.. @tengqm @hongchaodeng  for directing correct place of question..
