### ISSUE TITLE
Managing Service Accounts TOC omits "Bound Service Account Token Volume"

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#28233]
The section https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume appears to be at the same level as https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#serviceaccount-admission-controller and https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#token-controller but is missing from the TOC on the right, while the other two are present.

**Comment by tengqm** [comment]
"Bound Service Account Token Volume" is a H4, while the other two are H3. H4 are not captured into the TOC.
In fact, there are three mechanisms for service account automation, according to the text:

- A `ServiceAccount` admission controller
- A Token controller
- A `ServiceAccount` controller

The above three are all H3 headings, thus captured by the TOC.

/close
