### ISSUE TITLE
Upgrading kubeadm clusters

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/website#28253]
This page [link](https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrading-control-plane-nodes) says
on *first* control plane node, run "`sudo kubeadm upgrade apply v1.21.x`"
For *other* control plane nodes, run "`sudo kubeadm upgrade node`"

When applying a script for upgrade via some automation service, which will run this script one node at a time, how could the node distinguish itself as *first* node or not, so it can call "...upgrade apply" or "...upgrade node" ?

Thank you,
Renuka

**Comment by neolit123** [comment]
hi, the same page explains:
> Pick a control plane node that you wish to upgrade first. It must have the /etc/kubernetes/admin.conf file

this is considered the "first" CP node to run "plan / apply" on.

/close
/kind support

**Comment by renukamanavalan** [comment]
An automated service, picks any one control plane node at a time and run the script and move on to next node.
We would not know ahead of time, which node is first picked.

So the script should be able to programmatically identify, if this is the *first* node or *other*.
Every control plane node has "/etc/kubernetes/admin.conf".

Question: Programmatically how the script can identify *first* or *other* ?

per doc: "`Your cluster was upgraded to "v1.21.x`" upon apply in first node. How could this be detected programmatically ?
