### ISSUE TITLE
Upgrading kubeadm clusters

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/website#28258]
Related to [issue #28253](https://github.com/kubernetes/website/issues/28253)

Per doc [here ](https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrading-control-plane-nodes), we need to have the knowledge of first control plane node or not, as first control plane node does `sudo kubeadm upgrade apply ...`, where as other nodes do "`sudo kubeadm upgrade node`".

I plan to write a script and run the script in all control plane nodes by an automated service. 
I have a 5 master nodes control plane. This service will run the script as in one node at a time and it may pick any of the 5 nodes as first.

This implies that the script should be able to programmatically assess (_possibly via data in etcd_), if it is running in the *first* node or not.

**Question**: How the script could assess programmatically, if it is first node or not ?

**Comment by tengqm** [comment]
The "first" word may be confusing. Maybe revise it to "one of" would be better?

**Comment by neolit123** [comment]
If you have control plane host0...2 in an array in the bash script host0
can be the first CP host to upgrade. But you can also pick host2 and
iterate backward. As long as it has the admin.conf it would work.

**Comment by renukamanavalan** [comment]
Thank you neo! The word "first" is not an issue here, in fact that is the apt word. The point still here is, when you don't have control on "_which node will be picked first_", (_random pick among 5_) the *ideal* way is an ability to figure out, if this is the first node picked to run this script or not, at run time, programmatically.

Based on this statement from the doc "`Your cluster was upgraded to "v1.21.x". Enjoy`", upon first node calling "upgrade apply", I believe it would have created some entry in the etcd. If yes, this data could be used by the script to assess if this is the first node or not.

Said the above, these  upgrades only work within the minor release. For example, I cannot apply upgrade from 1.18.6 to 1.21.1 using this process, which limits the value of this upgrade feature. So please feel free to close this isssue.

**Comment by renukamanavalan** [comment]
Thank you Lubomir!
