### ISSUE TITLE
Translate concepts/services-networking/service-traffic-policy in Korean

### ISSUE THREAD

**Issue by mylovepooh** [kubernetes/website#28261]
**This is a Feature Request**

**What would you like to be added**

Translate concepts/services-networking/service-traffic-policy.md in Korean

**Why is this needed**
No Translation yet.

**Comments**
https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/

**Comment by seokho-son** [comment]
/triage accepted
감사합니다! ^^

현재 작업 브랜치는 dev-1.21-ko.4 입니다.
https://github.com/kubernetes/website/issues/28287 참고하셔서
dev-1.21-ko.4 를 기준으로 작업해주시면 될 것 같습니다. (약 2주간 진행되는 마일스톤)
