### ISSUE TITLE
kubectl Cheat Sheet updates required

### ISSUE THREAD

**Issue by hegdesandesh25** [kubernetes/website#28265]
The below section needs updates on cheat sheet page, most of these commands do not work without the generator=run-pod/v1 flag, updates might be needed as shown below.
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-running-pods

kubectl run generator=run-pod/v1 -i --tty busybox --image=busybox -- sh  # Run pod as interactive shell
kubectl run generator=run-pod/v1  nginx --image=nginx -n 
mynamespace                                         # Run pod nginx in a specific namespace
kubectl run generator=run-pod/v1  nginx --image=nginx                     # Run pod nginx and write its spec into a file called pod.yaml
--dry-run=client -o yaml > pod.yaml

**Comment by HongjiangHuang** [comment]
What version of Kubernetes?

**Comment by sftim** [comment]
/triage needs-information
/language en

I think the cheat sheet is accurate for Kubernetes v1.21

**Comment by hegdesandesh25** [comment]
> What version of Kubernetes?

1.18

**Comment by HongjiangHuang** [comment]
> > What version of Kubernetes? @HongjiangHuang
> 
> 1.18/1.19
> 
> @sftim
> I can close this if kubectl cheat sheet is meant for specific version but the document is quite helpful, lot of people refer it. Do we need a disclaimer of any sort to mention the version ?

https://v1-19.docs.kubernetes.io/

**Comment by HongjiangHuang** [comment]
https://github.com/kubernetes/kubernetes/pull/68132.

It does seem that the documentation is not updated.

**Comment by hegdesandesh25** [comment]
> > > What version of Kubernetes? @HongjiangHuang
> > 
> > 
> > 1.18/1.19
> > @sftim
> > I can close this if kubectl cheat sheet is meant for specific version but the document is quite helpful, lot of people refer it. Do we need a disclaimer of any sort to mention the version ?
> 
> https://v1-19.docs.kubernetes.io/

The site directs to the same kubectl cheatsheet documentation

**Comment by sftim** [comment]
@hegdesandesh25 I'm guessing that what you're saying is that when you search within https://v1-19.docs.kubernetes.io/ the search results are for the latest version of Kubernetes.

Have I got that right?

**Comment by hegdesandesh25** [comment]
> @hegdesandesh25 I'm guessing that what you're saying is that when you search within https://v1-19.docs.kubernetes.io/ the search results are for the latest version of Kubernetes.
> 
> Have I got that right?

@sftim 
To clarify, the run commands on the kubectl [cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-running-pods) do not work on kubernetes - (1.18/1.19/1.20) and it might need an update or state that it wont work on them.

please see this: https://github.com/kubernetes/kubernetes/pull/68132 as stated by @HongjiangHuang 

Commands will work with the below flag:
kubectl run **generator=run-pod/v1** -i --tty busybox --image=busybox -- sh # Run pod as interactive shell
kubectl run **generator=run-pod/v1** nginx --image=nginx -n
mynamespace # Run pod nginx in a specific namespace
kubectl run **generator=run-pod/v1** nginx --image=nginx # Run pod nginx and write its spec into a file called pod.yaml
--dry-run=client -o yaml > pod.yaml

**Comment by sftim** [comment]
The cheat sheet could borrow from https://kubernetes.io/docs/home/supported-doc-versions/ and explicitly link in the page body to the other available versions. This will be more clear than just putting the version selector in the top nav.

Maybe that would help?

**Comment by HongjiangHuang** [comment]
I think deleting the run command example. 

Because it has been deprecated

**Comment by sftim** [comment]
> `kubectl run -i --tty busybox --image=busybox -- sh  # Run pod as interactive shell` 

?
That's not deprecated, so I'd leave it in.

**Comment by hegdesandesh25** [comment]
> The cheat sheet could borrow from https://kubernetes.io/docs/home/supported-doc-versions/ and explicitly link in the page body to the other available versions. This will be more clear than just putting the version selector in the top nav.
> 
> Maybe that would help?



> > `kubectl run -i --tty busybox --image=busybox -- sh  # Run pod as interactive shell`
> 
> ?
> That's not deprecated, so I'd leave it in.
@sftim 
The run commands are not deprecated, the meaning of running the command has changed. In the latest versions, If you leave out the generators, run command is expected to create deployment by default. I would not suggest removing the commands itself from the documentation else how else would you create a simple pod(may be a rare scenario but) ?
