### ISSUE TITLE
ja: Make docs/contribute/_index.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28266]
**This is a Feature Request**

**What would you like to be added**
Update docs/contribute/_index.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/contribute/_index.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/contribute/_index.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/contribute/_index.md

diff between translated and v1.19
https://gist.github.com/0a10aaa88d31a89e67c2c9f3321819c1

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by atoato88** [comment]
Isn't target file for this PR already updated for v1.19 in #26903 ?

**Comment by inductor** [comment]
thanks
/close
