### ISSUE TITLE
ja: Make docs/reference/kubectl/cheatsheet.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28278]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/kubectl/cheatsheet.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/kubectl/cheatsheet.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/reference/kubectl/cheatsheet.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/reference/kubectl/cheatsheet.md

diff between translated and v1.19
https://gist.github.com/f0fc1ed12f6955f469c054ff0e532c1f

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by s-ito-ts** [comment]
/close
This issue has been fixed in PR #28465.
I close this issue.
