### ISSUE TITLE
ja: Make docs/reference/kubectl/jsonpath.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28279]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/kubectl/jsonpath.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/kubectl/jsonpath.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/reference/kubectl/jsonpath.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/reference/kubectl/jsonpath.md

diff between translated and v1.19
https://gist.github.com/9dfa10f6e1a690b77551e43dfb94511a

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by s-kawamura-w664** [comment]
@inductor 
I think this update is already included in the Japanese document.
This page was translated to Japanese at 2020/11/23 in #25183.
The latest update of English was at 2020/08/27.
Maybe, this translated page will be latest.
So, I think this issue will be able to close.

**Comment by inductor** [comment]
Thanks!
/close
