### ISSUE TITLE
ja: Make docs/reference/glossary/node.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28277]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/glossary/node.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/glossary/node.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/reference/glossary/node.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/reference/glossary/node.md

diff between translated and v1.19
https://gist.github.com/60a7401eaaf3f6c39edfbbaf62748c90

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
ちょっとした修飾子の変更のみなので日本語で対応が必要か要確認

**Comment by bells17** [comment]
実質差分なさそうなのでcloseで良さそう
