### ISSUE TITLE
ja: Make docs/reference/glossary/container.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28274]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/glossary/container.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/glossary/container.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/reference/glossary/container.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/reference/glossary/container.md

diff between translated and v1.19
https://gist.github.com/779ce162592f5e22f6c915f49a85ad19

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
Hugoシステム上の変更だけっぽいので日本語でも対応が必要がどうか確認

**Comment by bells17** [comment]
full_linkはjaの方にもありそうなので、とりあえず直しておいた方が無難なのでは？という感じです
