### ISSUE TITLE
ja: Make docs/reference/glossary/configmap.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28273]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/glossary/configmap.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/glossary/configmap.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/reference/glossary/configmap.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/reference/glossary/configmap.md

diff between translated and v1.19
https://gist.github.com/033973f9744561c3b16137e89525ba8a

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
fix typoなので日本語だと対応不要かも。要確認

**Comment by bells17** [comment]
typoなので対応不要な気がする
