### ISSUE TITLE
ja: Make docs/search.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28283]
**This is a Feature Request**

**What would you like to be added**
Update docs/search.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/search.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/search.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/search.md

diff between translated and v1.19
https://gist.github.com/277fdb77c0d2a2aa45f64886d7f426aa

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
多分削除だけど、他のところに移動してないかも合わせて確認

**Comment by t-inu** [comment]
>File to update
>https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/search.md

This file was deleted by the following PR.
#27508 Remove the link to the unused page in the side menu

I searched the file using find command for confirmation, then it was not to be found anywhere.
It seems this issue can be closed without any changes.
