### ISSUE TITLE
ja: Make docs/reference/setup-tools/kubeadm/_index.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28281]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/setup-tools/kubeadm/_index.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/setup-tools/kubeadm/_index.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/reference/setup-tools/kubeadm/_index.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/reference/setup-tools/kubeadm/_index.md

diff between translated and v1.19
https://gist.github.com/505d5ed7b47058cc0b2ab2a65d9cae14

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by bells17** [comment]
https://gist.github.com/505d5ed7b47058cc0b2ab2a65d9cae14
見る限り差分なさそう

**Comment by t-inu** [comment]
違いは、このダブルクォーテーションだけでした。
```
- ... as best-practice “fast paths” for creating Kubernetes clusters.
+ ... as best-practice "fast paths" for creating Kubernetes clusters.
```
日本語では、カギカッコで「近道」となっていて、特に修正する必要はなさそうです。
