### ISSUE TITLE
ja: Make docs/reference/tools.md follow v1.19 of the original text

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#28282]
**This is a Feature Request**

**What would you like to be added**
Update docs/reference/tools.md to follow v1.19 of the original (English) text.

**Why is this needed**
content/ja/docs/reference/tools.md is outdated.

**Comments**
/language ja
/good-first-issue

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.2/content/ja/docs/reference/tools.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/reference/tools.md

diff between translated and v1.19
https://gist.github.com/0bff1948a496c5eb07f0947d6df1f659

**Note**
Currently, we use **dev-1.19-ja.2** branch. Please open a PR targeting the branch.

ref
https://kubernetes.io/ja/docs/contribute/localization/

If you have a question, feel free to ask us at slack.k8s.io #kubernetes-docs-ja channel

**Comment by inductor** [comment]
@Itaachime ping

**Comment by t-inu** [comment]
Hi @sandeep1785 
How is this issue going?

**Comment by t-inu** [comment]
@inductor
I confirmed this issue.
```
-[`minikube`](/docs/tasks/tools/install-minikube/) is a tool that makes it
+[`minikube`](https://minikube.sigs.k8s.io/docs/) is a tool that makes it

-[`Kompose`](https://github.com/kubernetes-incubator/kompose) is a tool to help Docker Compose users move to Kubernetes.
+[`Kompose`](https://github.com/kubernetes/kompose) is a tool to help Docker Compose users move to Kubernetes.
```
These URLs were already modified when this document was translated.
ref: https://github.com/kubernetes/website/pull/26490
