### ISSUE TITLE
No findable description of bound service account tokens

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#28285]
No navigation panel says anything about bound service account tokens.

https://kubernetes.io/docs/reference/access-authn-authz/authentication/ describes service accounts and their non-bound tokens.

https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/ mentions them in a 4-th level subsection under automation in the admission controller (which omits the fact that the kubelet is also involved in automating bound tokens, see #28286 ), but that subsection is omitted from the TOC because it is 4th level.  Apparently that 3rd-level branch is only taking responsibility for describing service account automation in the admission controller.

Bound service account tokens are an aspect of the authentication functionality that should be described on their own right, in the page on authentication.

**Comment by sftim** [comment]
There isn't really a concept page on ServiceAccount. If there were, we could migrate the content to that concept page, and then hyperlink to that new section from its previous home.

**Comment by sftim** [comment]
In fact:
/lifecycle frozen

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/31845 is somewhat relevant

**Comment by sftim** [comment]
> There isn't really a concept page on ServiceAccount. If there were, we could migrate the content to that concept page, and then hyperlink to that new section from its previous home.

&hellip;until now: https://k8s.io/docs/concepts/security/service-accounts/

**Comment by sftim** [comment]
I reckon https://github.com/kubernetes/website/pull/39436 will close this issue.
