### ISSUE TITLE
Pods

### ISSUE THREAD

**Issue by marcelotab** [kubernetes/website#28284]
`https://kubernetes.io/es/docs/reference/generated/container-runtime` This link returns a 404

**Comment by wangyysde** [comment]
As if the target page is https://kubernetes.io/docs/setup/production-environment/container-runtimes/. Could you tell me which page are you link from?

**Comment by HongjiangHuang** [comment]
/assign
/triage/accepted
/bug

**Comment by sftim** [comment]
@HongjiangHuang The issue description is not yet clear on what needs fixing. Let's clarify.

/remove-triage accepted
/triage needs-information
/language es

**Comment by HongjiangHuang** [comment]
Hi, @marcelotab.

Can you check that the problem is solved?
