### ISSUE TITLE
Add content to https://kubernetes.io/docs/setup/best-practices/certificates/

### ISSUE THREAD

**Issue by chrisnegus** [kubernetes/website#28291]
**This is a Feature Request**

**What would you like to be added**

I'm in the process of creating several diagrams to add to the certificates page to illustrate where the certificates live and how they are used.

**Why is this needed**

The information on this page is very good, but I think could be enhanced with diagrams that highlight which files:

* Need to be replaced to use your own certificate authority.
* Are called by flags in each control plane service
* Are used for user authentication as opposed to authentication between services

**Comments**

As noted, I should have these diagrams ready to review in a PR soon. I'd be glad for input on whether or not these are the best features to highlight with diagrams on this page.

**Comment by sftim** [comment]
For the diagrams, I think it'd be useful to show the cluster components (etcd, API server, kubelet, etc) and indicate which of these has:
- the cluster CA private key
- the root CA key (which I think could be either: the API server, or none of these)
- the etcd private key(s)
- the private key for a given node

along with the certificates that rely on those private keys.

For example, the API servers will have a private key that identifies them as API servers, and these servers will publish the certificates (that rely on said private key) to TLS peers such as nodes.

We can have a similar diagram that shows an external client such as a user or CI/CD system that authenticates with a private key and signed certificate.

**Comment by chrisnegus** [comment]
> For the diagrams, I think it'd be useful to show the cluster components (etcd, API server, kubelet, etc) and indicate which of these has:
> 
> * the cluster CA private key
> * the root CA key (which I think could be either: the API server, or none of these)
> * the etcd private key(s)
> * the private key for a given node
> 
> along with the certificates that rely on those private keys.
> 
> For example, the API servers will have a private key that identifies them as API servers, and these servers will publish the certificates (that rely on said private key) to TLS peers such as nodes.
> 
> We can have a similar diagram that shows an external client such as a user or CI/CD system that authenticates with a private key and signed certificate.

I would very much like to take on the enhancements you are suggesting. Would it be possible for us to merge [PR 28367](https://github.com/kubernetes/website/pull/28367) first (which addresses a visual representation of the files in the tables), then take on a way of visual way of connecting keys and certificates to each kubernetes service?
