### ISSUE TITLE
Need better doc about alt addr in k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#28325]
In the "Initializing your control-plane node" section, point 4 begins by opening an important topic, what to do if the default address is not the one you want `kubeadm init` to use.  But it continues by talking about only a sliver of what has to be done about it, "set the advertise address for this particular control-plane node's API server".  BTW, even following the instructions given there, the certificate generated for the kube-apiserver does not include the configured address in its Subject Alternative Names.  Also, merely using `--apiserver-advertise-address` does not change the address that appears in the `kubeadm join` command that is printed at the end of `kubeadm init`.  Next comes a section entitled "Considerations about apiserver-advertise-address and ControlPlaneEndpoint" and it gives a tantalizing clue, using `--control-plane-endpoint` instead of `--apiserver-advertise-address`.  However, this section motivates that choice only as a matter of creating a multi-master configuration.  When I tried it for a single master, I discovered that setting `--control-plane-endpoint` _also_ got that address into the certificate generated for the kube-apiserver and the printed `kubeadm join` command.  And none of the above changes the InternalIP type of address in the kubelet's status.

In my case the default address --- the one that appears in the default route --- is not reachable from other nodes, and so has to be replaced everywhere.

**Comment by MikeSpreitzer** [comment]
And I just discovered that setting `--control-plane-endpoint` does NOT determine the address that the kube-apiserver writes into its Endpoints object.  This makes sense from the usage scenario of multiple masters, but is an additional gotcha to be noted for admins that need to exterminate the default address.

**Comment by neolit123** [comment]
> In my case the default address --- the one that appears in the default route --- is not reachable from other nodes, and so has to be replaced everywhere.

replied on https://github.com/kubernetes/kubernetes/issues/102693
your interface setup is not something k8s components understand very well and the topic of advertise-address vs bind-address is already confusing. that is not kubeadm's fault however.
https://stackoverflow.com/questions/65995056/kubernetes-api-server-bind-address-vs-advertise-address

the apiserver flags are underdocumented.

> And none of the above changes the InternalIP type of address in the kubelet's status.

why would kubeadm do that?

> And I just discovered that setting --control-plane-endpoint does NOT determine the address that the kube-apiserver writes into its Endpoints object. This makes sense from the usage scenario of multiple masters, but is an additional gotcha to be noted for admins that need to exterminate the default address.

the control-plane-endpoint is a topology construct of kubeadm, it is not something that you would see in an Endpoints object.

what can be done here is clarify how apiserver-advertise-address and control-plane endpoint are related and what values do they receive if they are not specified. also what would be in the output of the join command that init prints.

**Comment by MikeSpreitzer** [comment]
That response is taking a narrower view of kubeadm than I would like to see in the documentation.  With an outside-in perspective, kubeadm looks like a tool to create a cluster.  That is how it appears in the documentation.  That job includes configuring all the parts of the cluster, including kubelets.  Even if the kubeadm code takes the narrower view, I think the documentation of how to use kubeadm to create a cluster should take the broader view and explain the division of labor between the kubeadm tool itself and other things.

https://stackoverflow.com/questions/65995056/kubernetes-api-server-bind-address-vs-advertise-address is not on point because it is only about kube-apiserver command line flags.  My point is that `kubeadm init` is also responsible for more than that, including generating the kube-apiserver's certificate and the `kubeadm join` commands to be used later.

**Comment by MikeSpreitzer** [comment]
I submitted a blog post covering what I worked out for comprehensively overriding the default address.

**Comment by neolit123** [comment]
If you tell a kubeadm init command to use an advertise address foo it will
end up in both apiserver serving cert SAN and in the join command that is
printed at the end of init.

If you are not seeing the same I would like to know more because this is
not reproducible.

WRT kubelet node ip, you can configure that with the kubeadm
NodeRegistrationOptions.kubeletExtraArgs. The advertise address also
applying to the kubelet node ip does not make sense.

I can do a review of the blog post in the following days.

**Comment by neolit123** [comment]
Potential improvement mentioned here https://github.com/kubernetes/kubernetes/issues/102693#issuecomment-858608023

**Comment by MikeSpreitzer** [comment]
OK, I have learned some stuff and think I can articulate the problem better.   Let me try to start this over.

We have this documentation branch at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ .  It describes how to create a cluster using kubeadm.  As an operator, I come to this documentation branch with the whole problem of creating a cluster.  That includes installing and configuring the kubelets.  It is true that kubeadm itself does not install the kubelet, but that is beside the point.  The documentation needs to explain how to get the whole job done.  The page on "installing kubeadm" also mentions installing the kubelet, so there is already _some_ recognition of what is needed.

BTW, I have a bit of a terminology problem with the code and the doc.  They seem to treat "control plane" as meaning certain nodes.  I think the wider engineering community would also recognize the kubelet and kube-proxy as part of the control plane.  That is, we have some control plane agents that run on the worker nodes.  Does the Kubernetes project have established terminology that covers both those control plane nodes and also the control plane agents on the worker nodes?

In https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#initializing-your-control-plane-node, point 4 starts by raising a broad topic --- the possibility that the default address is not the one to use --- but immediately zeroes in on just one part of the problem.  At this point in the documentation what is needed is to address --- or give a pointer to a section that addresses --- the totality of the problem, including configuring the kubelets.  As far as I know now, there are four places where the desired address need to appear:
1. the IP address that the kube-apiserver puts in its Endpoints/EndpointSlice,
2. the Subject Alternative Name list of the kube-apiserver's X.509 certificate,
3. the IP address that appears in the `kubeadm join` command printed by `kubeadm`,
4. the `InternalIP` type of address of each Node.

The technique currently mentioned in point 4 (using the `--apiserver-advertise-address` command line flag of `kubeadm init`) affects the first three of those four places.

FYI, the reason I was making a cluster was to do an experiment that involves tweaking the kube-controller-manager's config in a way that can _not_ be done on the `kubeadm init` command line but _can_ be done via a config file.  Also, I am aware of a general preference to use config files instead of command line flags.  Those are the reasons why I did not even try the `--apisserver-advertise-address` command line flag, I went straight to a config file.

My eyes glazed over a bit while charging through the documentation.  So I did `kubeadm config print init-defaults` and looked for the simplest thing to do.  As reported in #28331, that appeared to be to use a simple ClusterConfiguration.  That was

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    advertise-address: 192.168.56.101
```

I have learned that this set me off on the wrong track.  Since then I have tried instead to use the following config file contents.

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.56.101
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.56.101
```

That got the whole job done for `kubeadm init` --- the desired address appeared in all four places.  I have not yet worked out the `kubeadm join` side of this, but I expect it to be pretty simple.  So I think it should be quite feasible to get the documentation to say what needs to be said, where it needs to be said.

**Comment by MikeSpreitzer** [comment]
FYI, a word on finding the relevant APIs (such as InitConfiguration).  The instructions on creating a cluster with kubeadm, https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/ , does not have a link to the APIs.  It _does_ have a link to [Using kubeadm init with a configuration file](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file).  That has a link to the list of versions of the APIs (https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm#section-directories).  When I pick the latest, I get to https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm#section-directories .  Bear in mind that I went there looking for an API.  I am looking for object type definitions.  The first several screenfuls of that page neither exhibit nor link to exhibits of object type definitions.  The section https://pkg.go.dev/k8s.io/kubernetes@v1.21.1/cmd/kubeadm/app/apis/kubeadm/v1beta2#hdr-Kubeadm_init_configuration_types has some brief abstracts of object type definitions, but not the actual definitions.  I did a lot of scrolling down that page without finding what I wanted.

Later I discovered that if I had scrolled even more, I would have found it.

It would be nice if it weren't that difficult.

**Comment by MikeSpreitzer** [comment]
Neither https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes nor the output from `kubeadm init` suggest that I can or should use a config file with `kubeadm join`.

**Comment by MikeSpreitzer** [comment]
So I never found an explanation of whether or how I can mix command line flags with config file contents, for `kubeadm join`.  So I tried making the minimal change.  I needed

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.56.127
```

so I tried just that --- and it was rejected:

```
root@join1:~# kubeadm join 192.168.56.130:6443 --token cc115j.4khfir8lxnj7zdrz --discovery-token-ca-cert-hash sha256:4afb915d5b7e902e7eed316a317a66e43d3fe63f19ea49e5b956086c28c275ff --config ka-join.conf
can not mix '--config' with arguments [discovery-token-ca-cert-hash token]
To see the stack trace of this error execute with --v=5 or higher
```

So I went full tilt in the other direction, and that worked.  I used the following config file contents.

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: 192.168.56.130:6443
    token: cc115j.4khfir8lxnj7zdrz
    caCertHashes: [ sha256:4afb915d5b7e902e7eed316a317a66e43d3fe63f19ea49e5b956086c28c275ff ]
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 192.168.56.127
```

and it was accepted:

```
root@join1:~# kubeadm join --v=5 --config ka-join.conf 
I0613 05:57:44.134425    8819 join.go:395] [preflight] found NodeName empty; using OS hostname as NodeName
...
This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.
```

**Comment by tengqm** [comment]
Actually, I did generated the reference doc for kubeadm in hope it can be published on the website. The files are still [there](https://github.com/kubernetes-sigs/reference-docs/blob/master/genref/output/md/kubeadm-config.v1beta2.md).

There had been a long debate on whether and how this should be published.

**Comment by neolit123** [comment]
Happy to have a look at PRs improving the docs.

**Comment by MikeSpreitzer** [comment]
Fact checking question first: does any intermediate position work for `kubeadm join`?  Can I supply some of the info on the command line, while specifying the rest in the config file?

**Comment by neolit123** [comment]
Config is always preffered. Some flags cannot be mixed with config due to
tech limitations. Long term flag options duplicated in config might be
deprecated. The k8s wide policy is sparse, so this kubeadm specific.

**Comment by MikeSpreitzer** [comment]
Yes, I can say that config is preferred.  I think that for documentation is it appropriate to also be clear on what is possible now.

**Comment by neolit123** [comment]
Forgot to mention that if kubeadm allows both flag and config for a certain
option, the flag value takes precendence.

**Comment by MikeSpreitzer** [comment]
We should document what combinations are allowed.
I do not know which combinations are allowed.

**Comment by neolit123** [comment]
It is better to not get into details and only say that flags are not
favorable. This has been an ongoing trend in kubeadm and kubelet for the
past 10+ releases.
