### ISSUE TITLE
Link from Labels concept page to list of well-known labels

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28323]
**This is a Feature Request**

**What would you like to be added**
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ should link to https://kubernetes.io/docs/reference/labels-annotations-taints/, and possibly also to https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ 

**Why is this needed**
These changes will help readers navigate the site.

**Comments**
/help
/language en

**Comment by hardikshah197** [comment]
Should I take up this issue? As I already know where it has to be fixed. @sftim

**Comment by sftim** [comment]
Fixed in PR #28738
/close
