### ISSUE TITLE
Add glossary tooltip to Pod Priority and Preemption page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28324]
**This is a feature request**

**What would you like to be added**
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/ should use a glossary tooltip for “affinity”

**Why is this needed**
Kubernetes uses the term “affinity” to mean a specific thing. A tooltip (and the hyperlink it implies) helps a reader learn more about this term if they are not sure.

**Comments**
/language en

**Comment by rohan-kulkarni-25** [comment]
Hey, I will like to work on this !! Please let me know how can I proceed with this !! @kbhawkey !!
