### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by dolimoon6000** [kubernetes/website#28340]
I tried following all the instructions on the Kubernetes tutorial Example: Deploying WordPress and MySQL with Persistent Volumes (https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#visit-your-new-wordpress-blog). I use minikube with 2 nodes. Also, I use NodePort type for the wordpress service. Everything seems to work fine (pods, services, deployments are all running). The only issue is that when I try to access the Wordpress installation after exposing services with `minikube service wordpress --url`, all I get is EOF. I've tried streaming the wordpress pod's logs but don't see any new output on visiting the minikube url. Any advice on fixing this issue would be greatly appreciated.

Note: If I run `kubectl port-forward svc/wordpress 8080:80`, I'm able to access the app at localhost:8080.

My OS is MacOS and I'm using docker driver.

**Comment by Kartik494** [comment]
Hi @dolimoon6000 can you check with pod state? i got an error for not getting secret configured to the pod. Even if its running fine

**Comment by Kartik494** [comment]
HI @dolimoon6000 any update on this?
