### ISSUE TITLE
Inaccurate node lease renewal interval in k8s.io/docs/reference/config-api/kubelet-config.v1beta1/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#28357]
The entry for nodeLeaseDurationSeconds says
> The lease is currently renewed every 10s, per KEP-0009. In the future, the lease renewal interval may be set based on the lease duration.

The future is now.  I am running release 1.21.1, and I have changed the nodeLeaseDuration to 100 seconds --- and the lease is being renewed every 25 seconds.

**Comment by MikeSpreitzer** [comment]
BTW, that description has other errors too.  It starts with an assertion that is not true (https://github.com/kubernetes/kubernetes/issues/102744).

**Comment by MikeSpreitzer** [comment]
Is there any rule for how to break lines in the source here?

**Comment by tengqm** [comment]
@MikeSpreitzer Please propose a change to the [upstream code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L349-L359) if the description is inaccurate. The docs are generated from the source code mentioned.

**Comment by jihoon-seo** [comment]
/remove-lifecycle stale
Because https://github.com/kubernetes/kubernetes/pull/103134 is ongoing.
