### ISSUE TITLE
Clarify behavior of Multiple Topology Spread constraints

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#28368]
**This is a Bug Report**

**Problem:**

We have examples of using more than one constraint, but we don't explicitly mention how those are treated.

**Proposed Solution:**

When describing the API, we should mention that multiple constraints are ANDed.

Also important to mention that there are no guarantees when removing pods (like when downscaling a replicaset).

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/

/sig scheduling

**Comment by chenxuc** [comment]
/assign
I can have a look for how to improve the doc

**Comment by chenxuc** [comment]
@alculquicondor I can see in the doc there's existing statement in one of its examples:
> then the results of 2 constraints are ANDed, so the only viable option is to place on "node4"

So I'm going to make the "ANDed" statement explicitly in the formal description for the contraints. And also mention the contrains does not apply when removing a pod. Please let me know if you have other suggestions. thanks!

**Comment by alculquicondor** [comment]
That sounds good. There is also confusion about what "global minimum" is:

The minimum number of pods in any topology domain. For example, the minimum number of matching pods in a zone.

This guarantees that pods are always schedulable in the topology domain with the least number of pods.

I also think there should be an explicit section to describe the behavior with node selectors/affinity (currently one bullet point in the "conventions" section).

**Comment by chenxuc** [comment]
I have made the improvement for the original suggestions in the doc. But the extra suggestion of "an explicit section to describe the behavior with node selectors/affinity" is beyond my knowledge for this area. We could work on it in another issue if that's necessary. thanks.

**Comment by alculquicondor** [comment]
I opened #28628 as follow up
