### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/controllers/replicaset/

### ISSUE THREAD

**Issue by DmitriGekhtman** [kubernetes/website#28375]
According to
https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost,
the pod deletion cost annotation "is honored on a best-effort basis, so it does not offer any guarantees on pod deletion order." It would help to add some context on when the annotation might not be honored. Otherwise, "no guarantees" could be construed as "doesn't work" which I'm sure isn't the case ;)

**Comment by sftim** [comment]
It's an alpha feature, so I think “might not work” could be about right. Documenting exactly what isn't finished is quite possibly more effort than fixing those limitations; my guess is we'll never document all the shortcomings of the v1.21 implementation.

That said, if anyone has that information and wants to add it, feel free to open a pull request.

**Comment by DmitriGekhtman** [comment]
It seems the best effort wording is not related to feature-readiness. Rather, it's intrinsic to the feature as explained by the implementer in https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2255-pod-cost#risks-and-mitigations
https://github.com/kubernetes/kubernetes/pull/101003#issuecomment-817978859
According to the last linked comment, the main issue is that "there could be race conditions between the time the annotation is set and the scale down request."

I'm interested in [User Story 1](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2255-pod-cost#story-1)
Specifically, I'd like to scale down specific pods identified as idle.

Say I 
- identify a pod in my deployment for scale-down
- set the podDeletionCost annotation
- read the pod's annotations to confirm podDeletionCost it has been set
- scale down by 1
- change nothing else, all other pods in the deployment are running without issue

How likely is it the pod I've identified will be scaled down? Is the attempted control too granular?
