### ISSUE TITLE
Types missing from k8s.io/docs/reference/config-api/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#28380]
There are a lot of configuration APIs not mentioned here.  Examples include:
- KubeletConfiguration
- InitConfiguration
- ClusterConfiguration

**Comment by MikeSpreitzer** [comment]
Actually KubeletConfiguration is there, don't know how I missed it.  But the kubeadm types are missing.

**Comment by tengqm** [comment]
kubeadm type reference was generated but not published.
There were not strong support for generating and publishing them.
You can check https://github.com/kubernetes-sigs/reference-docs/blob/master/genref/output/md/kubeadm-config.v1beta2.md for the output at the moment.

**Comment by neolit123** [comment]
Publishing the kubeadm types seems fine. One push back from me was around
changing field comments before doing that.

**Comment by sftim** [comment]
/kind feature
/language en

This would work better as one GitHub issue per missing page @MikeSpreitzer
