### ISSUE TITLE
鉴权概述的翻译问题（Chinese translation Issues of Authentication Overview）

### ISSUE THREAD

**Issue by NOWYOU** [kubernetes/website#28383]
authorization翻译成授权会不会更贴切一些？中国国内对3A的翻译，一般都是认证，授权和审计（authentication, authorization and auditing）。

Would it be more appropriate to translate authorization into [授权]? The translation of 3A in China is generally authentication(认证), authorization（授权）, and auditing（审计）.

**Comment by tengqm** [comment]
@NOWYOU Authorization 确实既可译为“授权”也可译为“鉴权”，具体翻译取决于上下文中，authorization 的含义。如果表达的是检查、判定权限的过程或组件，应该译为“鉴权”，强调尚未确定权限是否合理合法的状态，以及评估、鉴别的过程。反之，如果所周表达的是授予、赋予、给予某主体合适的权限这一动作或过程，可以翻译为“授权”。全部都翻译为“授权”不仅不准确，还容易引起误解。

**Comment by NOWYOU** [comment]
了解了这个两个词的差异，谢谢。但是照您所说，在这一页下文的表述中，很多Authorization应该翻译为授权，而不是全部为鉴权。
举一个例子。
----------------------------------------------------------------------------------------------------------------------------------------------
鉴权模块
Node - 一个专用鉴权组件，根据调度到 kubelet 上运行的 Pod 为 kubelet 授予权限。 了解有关使用节点鉴权模式的更多信息，请参阅节点鉴权。
----------------------------------------------------------------------------------------------------------------------------------------------
这里的Authorization应该翻译为授权模块比较合适吧？【为 kubelet 授予权限】这里的翻译已经说明了是授予权限的过程。

**Comment by tengqm** [comment]
authorization module 恰恰应该翻译为“鉴权模块”，因为它负责的是权限的鉴别判定过程，而不仅仅是授予。很有可能出现的情况是，requester 根本没有权限执行所请求的操作，这时何来权限可“授”呢？考虑这样一种表述，“The request is rejected by the authorization module”，如果翻译为“请求被授权模块拒绝”，是不是有点儿不严谨？“授权”模块怎么可以拒绝一个请求呢？

**Comment by NOWYOU** [comment]
谢谢您的解惑
