### ISSUE TITLE
apiVersion is outdated in examples/application/job/cronjob.yaml

### ISSUE THREAD

**Issue by Elevic** [kubernetes/website#28397]
In the following example:  https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#example
The apiVersion is: batch/v1, which is not recognized by current Minikube system.  Instead the following is accepted: apiVersion: batch/v1beta1.
Regards, Fabiola

**Comment by jihoon-seo** [comment]
/retitle apiVersion is outdated in examples/application/job/cronjob.yaml

**Comment by HongjiangHuang** [comment]
@Elevic The documentation version needs to be the same as the Kubernetes version.

You can run `minikube start --kubernetes-version=latest` or refer to the here https://v1-20.docs.kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by Shubham82** [comment]
Hi @Elevic 
JFI `batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+`
From v1.21  use batch/v1 for CronJob

**Comment by sftim** [comment]
/remove-kind bug
The current documentation is correct.

I will make a different suggestion in a separate issue.

**Comment by jihoon-seo** [comment]
Because
> The current documentation is correct.

and @sftim opened a separate issue,
this issue seems good to be closed.

/close
