### ISSUE TITLE
Correct minor oversights in Pod Security Standards

### ISSUE THREAD

**Issue by tabbysable** [kubernetes/website#28392]
**This is a Bug Report**

**Problem:**
In the Pod Security Standards document:
* Host Namespaces should be allowed to be undefined/nil in addition to false (these mean the same thing, but according to a strict reading of the document right now, specifying 'false' explicitly is required)
* Seccomp section has been incompletely and incorrectly updated for the GA of seccomp support in 1.19 (missing ".type" on one of the lines, and the correct value of the `type` attribute is `RuntimeDefault`, instead of the currently-listed `runtime/default`. Also, `undefined/ni` is not appropriate and should be removed.)

**Page to Update:**
https://kubernetes.io/docs/concepts/security/pod-security-standards/

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by tabbysable** [comment]
These changes were incorporated into the 1.22 release docs, resolved by https://github.com/kubernetes/website/pull/28903

/close
