### ISSUE TITLE
Install and Set Up kubectl on macOS

### ISSUE THREAD

**Issue by MyatNoeWai** [kubernetes/website#28404]
Hello,

I installed Kubernetes using this method "Install kubectl binary with curl on MacOS". In step 5, I get the error "kubectl: command not found". 
MacOS version: 10.12.6

Could you please give a solution?

Regards,
Myat

**Comment by HongjiangHuang** [comment]
Can you send me the reference document?

**Comment by jihoon-seo** [comment]
reference document: https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/

**Comment by HongjiangHuang** [comment]
You can run `export | grep PATH`.

Check if `/usr/local/bin` is in the PATH.

![image](https://user-images.githubusercontent.com/20190812/121866856-eb515680-cd31-11eb-9a41-d31b6018867e.png)

**Comment by sftim** [comment]
Let's mention that `/usr/local/bin` must be in your `$PATH`.

This was a support request, but it's also a hint about how to improve the docs
/remove-kind support
/language en

**Comment by HongjiangHuang** [comment]
Let me improve it.
