### ISSUE TITLE
[zh] Wrong custom heading ID in zh/docs/concepts/workloads/pods

### ISSUE THREAD

**Issue by Shuai-Xie** [kubernetes/website#28402]
Hi, the header url of **Privileged mode for containers** in Chinese version doc misses a `p`.

- https://kubernetes.io/zh/docs/concepts/workloads/pods/#rivileged-mode-for-containers

Best regards.

**Comment by jihoon-seo** [comment]
/assign
/retitle [zh] Wrong custom heading ID in zh/docs/concepts/workloads/pods
