### ISSUE TITLE
Daemonset pods don't run before other pods

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#28410]
**This is a Bug Report**

**Problem:**

The documentation for Daemonsets suggests that its pods start before other pods. This is not true and can lead to unmatched expectations.

**Proposed Solution:**

Remove `and when it needs to start before other Pods.`

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#deployments

/sig apps

**Comment by sftim** [comment]
The sense we want to convey is that if your Node isn't much use before some Pod (let's call it `calico` just for example) is scheduled there and healthy, you'd be wrong to consider other workload resources such as StatefulSet, Deployment, ReplicaSet etc to run that critical Pod.

There is an ordering implied by this even if none of the control plane components themselves look at that ordering. What matters here is that most Pods don't tolerate the sort of taints that a tool like a CNI plugin are there to help fix.

If we remove
> and when it needs to start before other Pods.

then let's replace it with other wording that helps readers understand how a DaemonSet can help deliver node- or cluster- critical components (in fact, even better: add a What's Next section that hyperlinks to pod priority, and with text that hints at why you might want to set a custom priority for your DaemonSets).

**Comment by sftim** [comment]
@alculquicondor does that make sense?

**Comment by alculquicondor** [comment]
I see. Maybe a better phrase would be something like:

`if the DaemonSet provides functionality that other Pods need to function correctly`

This gives a sense of pre-requisite, without implying any scheduling/startup guarantees.

+1 on `What's Next` section. Another useful resource is taints and tolerations, which can be used to restrict scheduling until something happens.

**Comment by sftim** [comment]
Maybe:
> if the DaemonSet provides node-level functionality that allows other Pods to run correctly on that particular node.
> For example, [network plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/) often include a component that runs as a DaemonSet. The DaemonSet component makes sure that the node where it's running has working cluster networking.

?

**Comment by alculquicondor** [comment]
lgtm

**Comment by vaibhav2107** [comment]
Fixed in PR #28609

**Comment by alculquicondor** [comment]
Thanks!

/close
