### ISSUE TITLE
Highlight feature state for recent stabilisations

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28411]
**This is a Feature Request**

**What would you like to be added**
If an API or other feature has gone **stable** in the current or previous minor release of Kubernetes, then add extra text to any [feature-state shortcode](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#feature-state). The extra text should hyperlink to https://kubernetes.io/docs/home/supported-doc-versions/ and should emphasize that readers need to check that the version of the docs they are reading matches their cluster.

**Why is this needed**
Prompted by https://github.com/kubernetes/website/issues/28397#issuecomment-860859610

**Comments**
Optional extra: tweak https://kubernetes.io/docs/home/supported-doc-versions/ to explain how to check what version of Kubernetes you're running. The `version-check` shortcode might be useful!

/kind feature

**Comment by sftim** [comment]
I'm suggesting this because some readers miss that they need to use a recent enough version of Kubernetes to use the GA version of a feature.

**Comment by HongjiangHuang** [comment]
That's a good idea.

**Comment by sftim** [comment]
/area web-development

(feel free to /triage accepted; it's my idea, so I won't do that)
