### ISSUE TITLE
Translate Documentation to Bengali

### ISSUE THREAD

**Issue by aindrila2412** [kubernetes/website#28426]
**This is a Feature Request**

**What would you like to be added**

Translate community/contributors/guide/first-contribution.md to Bengali

- https://github.com/kubernetes/community/blob/master/contributors/guide/first-contribution.md

**Why is this needed**
Because there is no Bengali translated version of this page.

**Comments**

/assign
/Bengali language

**Comment by sftim** [comment]
Hi @aindrila2412 

It'd be great to add a new localization team. If you're interested in starting to translate the Kubernetes documentation, https://kubernetes.io/docs/contribute/localization/ has some information about getting going.

You can also visit https://slack.k8s.io/ (for a robot-generated invitation) and join [#sig-docs-localizations](https://app.slack.com/client/T09NY5SBT/C0191RDKHU1) on Slack.
