### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by allenwashere** [kubernetes/website#28438]
这里有漏了配置文件，在PVC配置前面，没有配置对应的PV给到存储申领，会在执行后，pvc一直处于pending状态。必须补充符合调度条件存储类才可以。
pvc error log：
no persistent volumes available for this claim and no storage class is set

需要补充相应pv

**Comment by HongjiangHuang** [comment]
https://kubernetes.io/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#%E5%88%9B%E5%BB%BA-persistentvolumeclaims-%E5%92%8C-persistentvolumes.

/kind support

**Comment by HongjiangHuang** [comment]
文档已经说明关于 storage class。
