### ISSUE TITLE
Update documentation to match renamed primary branch

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28462]
**This is a Bug Report**

**Problem:**
This [k/website](https://github.com/kubernetes/website) repo is renaming its primary branch to `main`. However, existing documentation refers to the old name: `master`.

**Proposed Solution:**
Update the affected pages.

**Page to Update:**
https://kubernetes.io/

**Additional Information:**
This is a tracking issue.
/language en

**Comment by sftim** [comment]
@jimangel FYI

**Comment by jimangel** [comment]
Looks like everything is merged and completed. Thanks again for your help!
/close
