### ISSUE TITLE
[zh] Typo in docs/setup/production-environment/container-runtimes

### ISSUE THREAD

**Issue by freeysw** [kubernetes/website#28469]
![image](https://user-images.githubusercontent.com/26788279/122502392-1e912f80-d029-11eb-922e-f12b14f635bf.png)
启动命令缺少一个w

sudo systemctl enable crio --now

**Comment by jihoon-seo** [comment]
**This is a Bug Report**





**Problem:**
Typo in zh/docs/setup/production-environment/container-runtimes

**Proposed Solution:**
`sudo systemctl enable crio --no` -> `sudo systemctl enable crio --now`

**Page to Update:**
- zh: https://kubernetes.io/zh/docs/setup/production-environment/container-runtimes/#cri-o
- (en: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o )






/retitle [zh] Typo in docs/setup/production-environment/container-runtimes
/kind bug
/language zh

**Comment by tengqm** [comment]
Page is a little bit lagging behind. Will fix.
/assign
