### ISSUE TITLE
docs/tasks/extend-kubernetes/custom-resources example shows incorrect output

### ISSUE THREAD

**Issue by chrisnegus** [kubernetes/website#28490]
**Problem:**
Output from the `kubectl get ct -o yaml` example on this page is incorrect.

**Proposed Solution:**
Fix example to show the correct output.

**Page to Update:**
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-custom-objects

**Additional Information:**

There has been some confusion about how the `kind: List` works in Kubernetes. The output from this example is incorrect and it implies that the API server returns `kind: List` at the top of the output. In reality, the API server doesn't implement `kind: List`. It is kubectl that adds `kind: List` to the end of the output as a means of rendering it. Here is the output that returned when I ran the commands on this page:

```
$ kubectl get ct -o yaml
apiVersion: v1
items:
- apiVersion: stable.example.com/v1
  kind: CronTab
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"stable.example.com/v1","kind":"CronTab","metadata":{"annotations":{},"name":"my-new-cron-object","namespace":"default"},"spec":{"cronSpec":"* * * * */5","image":"my-awesome-cron-image"}}
    creationTimestamp: "2021-06-14T21:53:01Z"
    generation: 1
    name: my-new-cron-object
    namespace: default
    resourceVersion: "498192"
    uid: dce15875-fd2e-41be-bfee-3ef3396143ec
  spec:
    cronSpec: '* * * * */5'
    image: my-awesome-cron-image
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by chenxuc** [comment]
Thanks for the reporting the bug and clear explanation! I will fix the doc.
/triage accepted
/assign

**Comment by chrisnegus** [comment]
Thanks for taking that on, @chenxuc . For anyone working on a discussion of `kind: List` , I'm working on some larger writing to describe that and related list types (PodList, ServiceList, etc.).  See [Issue 25944](https://github.com/kubernetes/website/issues/25944).

**Comment by chenxuc** [comment]
Thanks @chrisnegus for writting the larger topic for the List. I close this issue since the larger topic is tracked in another issue. 
/close

**Comment by chrisnegus** [comment]
@chenxuc Thanks for taking care of this issue so quickly! I was happy to see that it had published when I looked at it today.
