### ISSUE TITLE
Example missing from Use Port Forwarding to Access Applications in a Cluster

### ISSUE THREAD

**Issue by MoHassn** [kubernetes/website#28500]
In the section of [Creating MongoDB deployment and service](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/#creating-mongodb-deployment-and-service)
`kubectl apply -f https://k8s.io/examples/application/guestbook/mongo-deployment.yaml` 
There is no file with the specified URL, and the output of running this command is:
`error: unable to read URL "https://k8s.io/examples/application/guestbook/mongo-deployment.yaml", server reported 404 Not Found, status code=404`

**Comment by chenxuc** [comment]
@jimangel In PR #28452 the https://k8s.io/examples/application/guestbook/mongo-deployment.yaml is deleted, which is used in the 'Creating MongoDB deployment and service' page.
/kind bug

**Comment by sftim** [comment]
/triage accepted
/retitle Example missing from Use Port Forwarding to Access Applications in a Cluster

**Comment by Shubham82** [comment]
/assign
will add these yaml's in the guestbook

**Comment by Shubham82** [comment]
Fix it here #28530
