### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by bodomic2** [kubernetes/website#28501]
Hi, just trying your tutorial here - https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ - and server is down, connection is refused on port 8080

**Comment by HongjiangHuang** [comment]
/need information

I hope you tell me,  in which step there is a problem?

**Comment by bodomic2** [comment]
oh my god, sorry, I've missed the `minicube start` in first screen! 
sorry for taking your time!

**Comment by HongjiangHuang** [comment]
> oh my god, sorry, I've missed the `minicube start` in first screen!
> sorry for taking your time!

It should be `minikube start`.
