### ISSUE TITLE
The PodSecurityPolicy section in "Using Admission Controllers" should be marked as deprecated

### ISSUE THREAD

**Issue by WilliamDenniss** [kubernetes/website#28502]
The PodSecurityPolicy section in this doc: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podsecuritypolicy is missing a "Feature state" flag. Since it's deprecated, I think it would be best to indicate this fact.

**Comment by chenxuc** [comment]
Thanks for the suggestion! I will make the improvement in the doc.
/triage accept 
/kind feature 
/assign

**Comment by sftim** [comment]
Fixed in #28511
/close
