### ISSUE TITLE
[ko] Translate docs/home/supported-doc-versions documentation.

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#28512]
**This is a Feature Request**
Translate part of [docs/home/supported-doc-versions.md](https://github.com/kubernetes/website/blob/dev-1.21-ko.5/content/en/docs/home/supported-doc-versions.md) in Korean

**What would you like to be added**

1. Git clones this website repository. 
2. Check out localization Korean team milestone branch.
> You can find the issue having titles such as `Korean Localization for dev-1.21-ko.5 branch`. 
> dev-1.21-ko.5 is a working branch base on 2021-06-20.
3. Edit the file([content/ko/docs/home/supported-doc-versions.md](https://github.com/kubernetes/website/blob/dev-1.21-ko.5/content/ko/docs/home/supported-doc-versions.md)).
4. Add the result of translation on the file. `This website contains documentation for the current version of Kubernetes and the four previous versions of Kubernetes.`
5. Open the Pull Request (base branch: Korean localization team working branch)

**Why is this needed**

Part of the documentation is not translated yet.

**Comments**

- en : [https://kubernetes.io/docs/home/supported-doc-versions/](https://kubernetes.io/docs/home/supported-doc-versions/)
- ko : [https://kubernetes.io/ko/docs/home/supported-doc-versions/](https://kubernetes.io/ko/docs/home/supported-doc-versions/)

**Comment by anubha-v-ardhan** [comment]
Hey, I would like to take this one. Please assign this to me

**Comment by anubha-v-ardhan** [comment]
Fixed this issue in PR https://github.com/kubernetes/website/pull/28516

**Comment by anubha-v-ardhan** [comment]
Solved issue in PR https://github.com/kubernetes/website/pull/28535
