### ISSUE TITLE
#how-to-achieve-this doesn't exist in /docs/concepts/cluster-administration/networking/

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#28529]
**This is a Bug Report**

**Problem:**
In this page, there is a "how we achieve this" link.
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#exposing-pods-to-the-cluster

However, #how-to-achieve-this doesn't exist in /docs/concepts/cluster-administration/networking/.

**Proposed Solution:**

The link would be `/docs/concepts/cluster-administration/networking/`.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

/language en

**Comment by sftim** [comment]
I would remove

> You can read more about how we achieve this if you're curious.

as the easy fix.

(I think the more involved fix is to tackle https://github.com/kubernetes/website/issues/25832)

**Comment by vaibhav2107** [comment]
Fixes in #30440.

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/31331 I think.
/close
