### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice - Wrong project repository in instructions

### ISSUE THREAD

**Issue by shaehnel** [kubernetes/website#28531]
It seems the directory used in the instructions does not match the directory used in the sample application.

Instructions:
cd guide-kubernetes-microprofile-config/start/

Shell:

```
$ ls
katacoda-finished  sample-kubernetes-config
$ pwd
/root
$ ls sample-kubernetes-config/
finish/      .git/        .gitignore   LICENSE      README.md    scripts/     start/       .travis.yml  
$ ls sample-kubernetes-config/start/
```

**Comment by jihoon-seo** [comment]
Related webpage: https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

**Comment by jihoon-seo** [comment]
This issue is resolved by https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/39 .
/close
