### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by jbecker44** [kubernetes/website#28536]
Looks like something changed with this interactive tutorial because the second command:
```bash
$ cd guide-kubernetes-microprofile-config/start/
```
fails now with the following error:
```
-bash: cd: guide-kubernetes-microprofile-config/start/: No such file or directory
```

**Comment by jihoon-seo** [comment]
This issue is dup with #28531.

Related webpage: https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

**Comment by jihoon-seo** [comment]
This issue is resolved by https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/39 .
/close
