### ISSUE TITLE
Issue with k8s.io/zh/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/

### ISSUE THREAD

**Issue by aliasmee** [kubernetes/website#28549]
CPU 误写成GPU。

`说明： 当创建 LimitRange 对象时，你也可以声明大页面和 GPU 的限制。 当这些资源同时声明了 'default' 和 'defaultRequest' 参数时，两个参数值必须相同。`

应更改为

`说明： 当创建 LimitRange 对象时，你也可以声明大页面和 CPU 的限制。 当这些资源同时声明了 'default' 和 'defaultRequest' 参数时，两个参数值必须相同。
`

**Comment by tengqm** [comment]
GPU is correct. Based on the upstream implementation, we have the following constraints:

> for GPU, hugepages and other resources that are not allowed to overcommit,
> the default value and defaultRequest value must match if both are specified

/close
