### ISSUE TITLE
“Developing and debugging services locally” documents out-of-project tooling

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28567]
**This is a Bug Report**

**Problem:** [“Developing and debugging services locally](https://kubernetes.io/docs/tasks/debug-application-cluster/local-debugging/) covers an out-of-project tool for working with Kubernetes

**Proposed Solution:**

Either:
- migrate https://kubernetes.io/docs/tasks/debug-application-cluster/local-debugging/ into https://www.telepresence.io/docs/
- remove https://kubernetes.io/docs/tasks/debug-application-cluster/local-debugging/ (no migration)

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/local-debugging/

Part of #20232

See https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/pull/28564#issuecomment-865983533

**Comment by lyzhang1999** [comment]
I think this page should be replace that lists of 3rd party tools for local development, this would help people know how to develop services under Kubernetes environment.

**Comment by shannonxtreme** [comment]
The following pages already contain more detailed versions of the information on this page so a migration might not be necessary. 

* https://www.telepresence.io/docs/v1/tutorials/kubernetes/ 
* https://www.telepresence.io/docs/v1/reference/connecting/

+1 to the list of third-party tools. Are there others, or are telepresence and nocalhost the only two we know of for now? 

Also @sftim, you mentioned a general task. Would that depend on them working in a similar way? May be better to give an overview of how these tools work and direct the reader to those tools' docs for actual detailed tasks.

**Comment by sftim** [comment]
I'm open to suggestions about how we document these tasks. I think they _are_ tasks because the phrase “Developing and debugging services locally” sounds much more like a task than a reference or concept.

Pretty much anything goes so long as the approach we pick:
- follows the content guide
- isn't far away from the recommendations in the style guide

**Comment by lyzhang1999** [comment]
it's anything I can help?

**Comment by sachinkumarsingh092** [comment]
@sftim this page documents telepresence v1, but as of now the [current default version is v2](https://www.telepresence.io/announcing-telepresence-2/) which is very different from the v1. So even if we move this page to a list of third-party tools, we still need to update it to the current version.

**Comment by sftim** [comment]
> So even if we move this page to a list of third-party tools, we still need to update it to the current version.

Seems fair.

**Comment by shannonxtreme** [comment]
We should add Telepresence to the tools at [Other Tools](https://kubernetes.io/docs/reference/tools/). 

If agreed, maybe we can turn add more guidance and turn this into a good-first-issue, WDYT @sftim ?
