### ISSUE TITLE
Wrong indentation for sidebar

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28568]
**This is a Bug Report**

**Problem:**
The sidebar is not indented the way that the Docsy theme intends it to be.

**Proposed Solution:**
Fix sidebar customization to account for latest upstream Docsy changes.

**Page to Update:**
https://kubernetes.io/docs/

PR #28521 should fix this.
/priority important-soon
/area web-development
/triage accepted

**Comment by jihoon-seo** [comment]
This issue was resolved by #28521.
![image](https://user-images.githubusercontent.com/46767780/123368184-4b5bbe80-d5b6-11eb-9422-6a164715acfc.png)
/close
