### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

### ISSUE THREAD

**Issue by dwgillies-bluescape** [kubernetes/website#28579]
Error on this page:

kubectl get hpa.v2beta2.autoscaling -o yaml > /tmp/hpa-v2.yaml

This command is incorrect.  The output shown after this command is actually from (corrected command):

kubectl get hpa php-apache -o yaml > /tmp/hpa-v2.yaml

**Comment by sftim** [comment]
HorizontalPodAutoscaler has graduated to stable.

We should correct the page at https://k8s.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

/kind bug
/language en
/triage accepted
/help

**Comment by sftim** [comment]
The fix is to change
`kubectl get hpa.v2beta2.autoscaling -o yaml > /tmp/hpa-v2.yaml`
to
`kubectl get hpa php-apache -o yaml > /tmp/hpa-v2.yaml`

**Comment by vaibhav2107** [comment]
Fixes in #28583
