### ISSUE TITLE
URL to 'pod-priority-preemption' is changed

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#28575]
**This is a Bug Report**

**Problem:**
URL to 'pod-priority-preemption' is changed.

There exists a redirection rule for
https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
to
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/ ,

but not for localized ones.

E.g.
https://kubernetes.io/ko/docs/concepts/configuration/pod-priority-preemption/ (which returns 404 not found)
does not redirects to
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/pod-priority-preemption/

**Proposed Solution:**

- For website codes, replace `docs/concepts/configuration/pod-priority-preemption` with 
`docs/concepts/scheduling-eviction/pod-priority-preemption`
- And optionally, create redirection rules for each language.

**Page to Update:**
(There can exist many pages to update.)

/assign

**Comment by jihoon-seo** [comment]
Same issue for:
`docs/reference/generated/kube-scheduler` (old)
-> `docs/reference/command-line-tools-reference/kube-scheduler` (new)

**Comment by tengqm** [comment]
I don't think we should add redirection entries for all languages. The correct fix should be avoid using old URIs when page are moved around.

**Comment by tengqm** [comment]
BTW, this kind of issue can be detected using the `linkchecker.py` tool.

```shell
./scripts/linkchecker.py -f /docs/tasks/**/*.md
./scripts/linkchecker.py -f /docs/reference/**/*.md
```

The output is about bad links to be fixed.

You can also run the tool agains a localization, e.g.

```
./scripts/linkchecker.py -l ko -f /docs/concepts/**/*.md
```

**Comment by sftim** [comment]
> I don't think we should add redirection entries for all languages. The correct fix should be avoid using old URIs when page are moved around.

My view:
We should avoid redirects, but when we can't avoid them / it feels better not to, then we should add redirects for all localizations and not just English. A script to make that copying easier would be useful.
