### ISSUE TITLE
Enhance the 'Create an issue' button

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#28572]
**This is a Feature Request**

**What would you like to be added**

For example, in https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/ ,
there exists an 'Create an issue' button.
![image](https://user-images.githubusercontent.com/46767780/123045612-132d7200-d436-11eb-8386-552329dddbe9.png)

The `href` of this link is
https://github.com/kubernetes/website/issues/new?title=Interactive%20Tutorial%20-%20Configuring%20a%20Java%20Microservice ,
and you can see that the 'Title' field of issue posting page is filled with the title of origin page.

![image](https://user-images.githubusercontent.com/46767780/123045370-ccd81300-d435-11eb-8567-170674b03bc5.png)

My suggestion is that
we add `body` param to the `href`, to indicate the URL of origin page.

For example,
https://github.com/kubernetes/website/issues/new?title=Interactive%20Tutorial%20-%20Configuring%20a%20Java%20Microservice&body=Related%20webpage:%20https%3A%2F%2Fkubernetes.io%2Fdocs%2Ftutorials%2Fconfiguration%2Fconfigure-java-microservice%2Fconfigure-java-microservice-interactive%2F
![image](https://user-images.githubusercontent.com/46767780/123045738-39eba880-d436-11eb-94aa-5cb973458664.png)

And, one can enhance this suggestion,
i.e. applying proper new issue template, etc.

**Why is this needed**
Some users post issue with that button,
but since the URL of origin page is not indicated,
someone interested should find the URL manually and on their own.

For example,
- #28531
- #28536
- ...

**Comments**

**Comment by hardikshah197** [comment]
Hey @sftim May I take up this issue if no one is working on it?
