### ISSUE TITLE
Mention wildcard for RBAC resources and names

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28580]
**This is a Feature Request**

**What would you like to be added**
In [Using RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac/), document that a wildcard `["*"]` value for a resource or a resource name means “any”.

**Why is this needed**
Although the use of `*` as a wildcard is common in Kubernetes, there are several mechanisms and readers might want to know which to use.

**Comments**
The API reference at https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1/ also doesn't mention that `*` is a wildcard here.

/sig auth
/language en

**Comment by sftim** [comment]
> You can also grant for `*/subresource` if you wanted to do like `*/scale`

&mdash;@enj

but you *can't* grant for all subresources, eg `pods/*`.

**Comment by sandeep1785** [comment]
@sftim Can u please elaborate what we have to do in this.

**Comment by chrismetz09** [comment]
@sandeep1785, I'll defer to you to handle. Otherwise I can take a crack at it.

**Comment by shannonxtreme** [comment]
@sftim please verify the following: 

## For the main doc:

Maybe in the [Referring to resources](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources) section, we could add something like: 

You can also use wildcards [`*`] in values you specify for `resources` or `resourceNames`. In Kubernetes, the wildcard character means "any". For example, you can use `pods/*/log` to allow a subject to access the `log` subresource for all pods.

## For the API:

Modify the upstream file at https://github.com/kubernetes/kubernetes/staging/src/k8s.io/api/rbac/v1/types.go

The API reference docs are generated from the upstream, so changes to the docs mean modifying the comments in the upstream file and creating a PR.

**Comment by mehabhalodiya** [comment]
@s-urbaniak @sandeeppainuly I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂
/unassign @s-urbaniak @sandeeppainuly

**Comment by tomkivlin** [comment]
Note the API reference was updated for v1.22 so I will just update the RBAC doc.
