### ISSUE TITLE
Use Port Forwarding to Access Applications in a Cluster

### ISSUE THREAD

**Issue by mohamed-ahmed** [kubernetes/website#28591]
https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

This guide using one of these playgrounds in place of having a real cluster

> If you do not already have a cluster, you can create one by using minikube or you can use one of these Kubernetes playgrounds:
> 
> [Katacoda](https://www.katacoda.com/courses/kubernetes/playground)
> [Play with Kubernetes](http://labs.play-with-k8s.com/)

Did those writing the guides try the sandboxes suggested and see that they are actually able to run the commands within the sandbox environment?

None of them work for these purposes

**Comment by chenxuc** [comment]
Thanks for reporting the bug. There's a change in progress for the examples. This issue might duplicate with #28500 , and will be fixed once the PR #28530 is merged.

**Comment by tengqm** [comment]
I believe this one has been resolved.
/close
