### ISSUE TITLE
Term `master` in docs/tasks/administer-cluster/highly-available-control-plane

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#28595]
**This is a Bug Report**

**Problem:**

I am not sure whether
the term `master` in https://kubernetes.io/docs/tasks/administer-cluster/highly-available-control-plane/ is intentionally preserved or not.

![image](https://user-images.githubusercontent.com/46767780/123226297-7db1e100-d50e-11eb-960a-a3ea70bef6c3.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/highly-available-control-plane/

**Comment by sftim** [comment]
We should amend that text
/wg naming

**Comment by jihoon-seo** [comment]
/assign

The [embedded image](https://github.com/kubernetes/website/blob/main/static/images/docs/ha-master-gce.png) should be updated too,
but I cannot update since that file is an binary file.
It would be nice if that figure is an Google Drawings object, like this:
https://docs.google.com/drawings/d/1muJ7Oxuj_7Gtv7HV9-2zJbOnkQJnjxq-v1ym_kZfB-4/edit?usp=sharing

It seems that @neolit123 you lastly updated that image file.
Could I get an pre-PNG file (e.g. PPT, Google Drawings object, etc.) of that PNG file? 😊

**Comment by neolit123** [comment]
> Could I get an pre-PNG file (e.g. PPT, Google Drawings object, etc.) of that PNG file? blush

i remember fixing the typo in the PNG using Photoshop by copying pixels / letters around.
i don't have the source file.

**Comment by sftim** [comment]
I suggest opening a separate issue that requests replacing that diagram with an SVG.

**Comment by jihoon-seo** [comment]
@sftim
> I suggest opening a separate issue that requests replacing that diagram with an SVG.

Done! (#28654)

**Comment by jihoon-seo** [comment]
This issue was resolved by #28622.
