### ISSUE TITLE
Issue with /docs/user-guide/replication-controller/

### ISSUE THREAD

**Issue by stephanwesten** [kubernetes/website#2859]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The page https://kubernetes.io/docs/user-guide/replication-controller/ states that readiness has not been implemented.

However according to https://github.com/kubernetes/kubernetes/issues/620, readiness has been implemented since 2015. So our k8s (1.4.7 & 1.5.2) support it.

**Proposed Solution:**
fix the page!

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
This looks like a valid issue report. I am not sure which component is responsible for health/readiness checks (kubelet?) or how these relate to ReplicationController. @stephanwesten please feel free to send a patch if you know the answer. Otherwise, I can contribute one if somebody answers.

**Comment by zacharysarah** [comment]
@stephanwesten Thanks for opening this issue.

@ahmetb Any updates here?

**Comment by ahmetb** [comment]
Looks like someone needs to send a patch fixing out of date statement.
