### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateless-application/expose-external-ip-address/

### ISSUE THREAD

**Issue by maoschanz** [kubernetes/website#28602]
>If the external IP address is shown as \<pending\>, wait for a minute and enter the same command again.

It's been 19 hours and it's still pending, maybe the doc should suggest some way to diagnose what's happening

**Comment by jihoon-seo** [comment]
@maoschanz 
Which cloud provider (e.g. AWS, GCP, Azure) are you using?
Did you build your K8s cluster on your own (e.g. using `kubeadm`), or got one via managed service (e.g. EKS, GKE, AKS) ?

**Comment by maoschanz** [comment]
the solution to my issue was to run "minikube tunnel"
