### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

### ISSUE THREAD

**Issue by neutralvibes** [kubernetes/website#28606]
### Unable to use tutorial

The tutorial instructs the user to perform the following:-

```bash
cd guide-kubernetes-microprofile-config/start/
```

Result

```
-bash: cd: guide-kubernetes-microprofile-config/start/: No such file or directory
```

Unless I am missing something (quite possibly) this prevents progressing any further. 
A `ls -al` confirms the folder is missing and the result has remained the same even after refreshing the page.

Thanks for reading

**Comment by jihoon-seo** [comment]
Hello @neutralvibes
This issue is dup with #28531 and #28536.

Related webpage: https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

**Comment by jihoon-seo** [comment]
This issue is resolved by https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/39 .
/close
