### ISSUE TITLE
Prohibition on ConfigMap and Secret volume in static pod is too obscure

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#28611]
**This is a Bug Report**

**Problem:**
I saw an out-of-tree product mention that static pods "can not use" ConfigMaps and Secrets.  I was unaware of such a prohibition.  I went looking in the k8s website.  I spent a lot of time not finding any mention of such a restriction.  For example:

- https://kubernetes.io/docs/concepts/workloads/pods/ mentions static pods but not the restriction;
- https://kubernetes.io/docs/concepts/storage/volumes/ describes ConfigMap and Secret type volumes but does not mention the restriction;
- the Go sources for the relevant API types do not mention the restriction (https://github.com/kubernetes/kubernetes/issues/103167).

I eventually found the restriction wrt ConfigMap mentioned in https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#restrictions , but I think it should not appear only there.

**Proposed Solution:**
- Update either or both of the first two pages I cited that currently lack the restriction.
- Update the API types to mention the restriction.

**Page to Update:**
Listed above.

**Comment by chenxuc** [comment]
I can work on this one. Thanks.
/assign

**Comment by MikeSpreitzer** [comment]
I just realized there is an additional --- and more severe --- restriction on static pods.  They do not get ServiceAccounts!  For example, using a static pod:
```
root@init1:~# kubectl exec test3-init1 -- ls /var
spool
www
```

... note that there is no `/var/run/secrets/kubernetes.io/serviceaccount` !

**Comment by MikeSpreitzer** [comment]
The prohibition is even broader and simpler: the definition of a static pod can not refer to any other API object.  For example, PersistentVolumeClaim is another thing that a static pod's definition can not reference.
