### ISSUE TITLE
Better explain the interactions of topology spread constraints and node affinity/selector

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#28628]
**Problem:**

The calculations for Topology spread constraints are affected by node affinity/selectors. This is currently described as a bullet point in a "conventions" section, making it easy to be missed.

/sig scheduling

**Proposed Solution:**

Create a section that describes the interactions of topology spread constraints and node affinity and node selectors. For example, we should describe more about the calculations, like how many pods match for each node and what is the global minimum.

The section can be named `### Interaction with node affinity and node selectors`, followed by `### Other conventions`.

An additional corollary that could be mentioned in conventions: since the topology domains are determined from the nodes that satisfy the node selector, topology domains that have zero nodes are excluded from calculations. This could be a problem when a node pool (or node group) is scaled to zero nodes and the user is expecting them to scale up. Those topology domains are not considered until there is at least one node in them.

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#conventions

**Comment by alculquicondor** [comment]
cc @Huang-Wei

**Comment by aliakbar-hemmati** [comment]
Hi,
I would like to work on this issue. How can I find better explanation for the interactions? Is it required to read source code?

**Comment by alculquicondor** [comment]
Most of the content is already in the website and in the issue description above. It needs to be put in the appropriate format.

You could read the initial design: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/895-pod-topology-spread and the code (but it's probably not necessary): https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go

**Comment by RinkiyaKeDad** [comment]
Hey @aliakbar-hemmati are you still working on this issue? If not, I'd like to take it up :)

**Comment by aliakbar-hemmati** [comment]
Hey @RinkiyaKeDad
No I'm not currently working on it
Go on and take it

**Comment by RinkiyaKeDad** [comment]
Thanks for confirming! :)

/assign
