### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by tvanbesi** [kubernetes/website#28627]

**Comment by chenxuc** [comment]
@tvanbesi Thanks for opening your first issue here! The description is empty. Please provide more information for the description.
/triage needs-information

**Comment by tvanbesi** [comment]
Hi I wasn't sure if it was the right place but the tutorial at https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/ doesn't seem to work. I used it as is copy pasting everything. I'm on Ubuntu

**Comment by Kartik494** [comment]
@tvanbesi I have tried it on my environment and got to know that my wordpress pod is still in `CreateContainerConfigError` state but  when i describe my pod i got an error stated ` Error: secret "mysql-pass" not found` but secret is already in my environment!

`kubectl get secret
NAME                                           TYPE                      DATA   AGE
mysql-pass-5m26tmdb5k             Opaque                    1      6m14s
`

**Comment by Kartik494** [comment]
I have running this on minikube  with latest version
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
`
But in your case i guess the pod is running fine, but not able to run wordpress on browser?
