### ISSUE TITLE
Add link from “Operator pattern” to CNCF operator white paper

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28621]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/concepts/extend-kubernetes/operator/ to have an extra link in it's What's Next section, pointing at https://github.com/cncf/tag-app-delivery/blob/eece8f7307f2970f46f100f51932db106db46968/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md

**Why is this needed**
The [operator white paper](https://github.com/cncf/tag-app-delivery/blob/eece8f7307f2970f46f100f51932db106db46968/operator-wg/whitepaper/Operator-WhitePaper_v1-0.md) is very relevant to people reading about the operator pattern.

**Comments**
/language en
/kind feature

**Comment by Shubham82** [comment]
/assign
I can work on this.

**Comment by Shubham82** [comment]
Fixed it here #28625
