### ISSUE TITLE
Container Lifecycle Hooks: PreStop hooks asynchronously or synchronous

### ISSUE THREAD

**Issue by duanyifei1937** [kubernetes/website#28633]
In [Container Lifecycle Hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/):
> PreStop hooks are not executed asynchronously from the signal to stop the Container; the hook must complete its execution before the TERM signal can be sent.

But In [Kubernetes best practices: terminating with grace](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace) 
> At this point, Kubernetes waits for a specified time called the termination grace period. By default, this is 30 seconds. It’s important to note that this happens in parallel to the preStop hook and the SIGTERM signal. Kubernetes does not wait for the preStop hook to finish.

If PreStop hooks action had a break change in new release?
or this blog is too old in 2018?

**Comment by chenxuc** [comment]
@duanyifei1937 Thanks for the first issue here!
From my understanding, the two sentences do not conflict. Both of them are correct:
- On one thread, PreStop hooks and TERM signal are executed synchronously. PreStop hooks must complete before TERM signal is sent.
- On the other thread, Termination grace period happens asynchronously with "PreStop hook and TERM signal" thread. If "PreStop hook and TERM signal" cannot get work done after grace period time, the Pod is killed forcely.

/triage support

**Comment by duanyifei1937** [comment]
@chenxuc thanks reply, i understand.
