### ISSUE TITLE
Migrate "Adding entries to Pod /etc/hosts with HostAliases" to Tasks

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#28630]
Affected page: https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

Move this page from Concepts to Tasks (potentially under Tasks > Networking).

Update `static/_redirects` to redirect the old URL to the new location (use a 301 code, similar to other entries in this file).

/sig docs
/language en

**Comment by chenxuc** [comment]
I'd like to work on this one to learn something new in website page organizing. Thanks.
/assign
