### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/overview/

### ISSUE THREAD

**Issue by sahsz123** [kubernetes/website#28649]
You need to add a list of custom columns or at least some examples to be run via the kubectl like:
kubectl get po nginx -o custom-columns=Name:metadata.name,ANNOTATIONS:metadata.annotations.description

**Comment by sftim** [comment]
Hi @sahsz123 

Thanks for the suggestion. Could you outline why that improvement would be helpful? That'll help us decide on how soon we should start work on it.

/priority awaiting-more-evidence
/language en
