### ISSUE TITLE
Replace `ha-master-gce.png` with SVG or something else

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#28654]
**This is a Bug Report**

**Problem:**
The image [ha-master-gce.png](https://github.com/kubernetes/website/blob/main/static/images/docs/ha-master-gce.png) in ["Set up a High-Availability Control Plane" page](https://kubernetes.io/docs/tasks/administer-cluster/highly-available-control-plane/)
is in PNG format,
which makes it hard for contributors to edit its content.

**Proposed Solution:**
Replace `ha-master-gce.png` with SVG or something else (e.g. Google Drawings object, etc.)
(Example of Google Drawings object: 
https://docs.google.com/drawings/d/1muJ7Oxuj_7Gtv7HV9-2zJbOnkQJnjxq-v1ym_kZfB-4/edit?usp=sharing )

**Page to Update:**
- https://kubernetes.io/docs/tasks/administer-cluster/highly-available-control-plane/
- https://github.com/kubernetes/website/blob/main/static/images/docs/ha-master-gce.png

/language en

**Comment by sftim** [comment]
/triage accepted

We'd prefer SVG images, ideally with the text converted to shapes. It's OK to save an editable version somewhere else - SVG lets you add a comment about where to find the editable version.

**Comment by anubha-v-ardhan** [comment]
I would like to work on this

**Comment by anubha-v-ardhan** [comment]
fixed issue in #28720
