### ISSUE TITLE
Issue with k8s.io/zh/docs/setup/production-environment/tools/kubeadm/ha-topology/

### ISSUE THREAD

**Issue by liuyanzhen34** [kubernetes/website#28661]
hello
every one.
I have a question on External etcd topology ,documentation describes that :
However, this topology requires twice the number of hosts as the stacked HA topology. A minimum of three hosts for control plane nodes and three hosts for etcd nodes are required for an HA cluster with this topology.

![image](https://user-images.githubusercontent.com/48582103/123604005-02616f80-d82d-11eb-93b0-95070012b0b3.png)

my question is:  2 hosts for control plane nodes and three hosts for etcd nodes  are ok ? why at least 3  control plane nodes ?

**Comment by tengqm** [comment]
Three nodes is the minimum for HA so that you can achieve a quorum when bad things (such as a network split) happen.
/kind support

**Comment by liuyanzhen34** [comment]
I'm sorry that I can't toally agree with you, load balancer is in front of apiservers,these apiservers don't need to  achieve a quorum.
while etcd does

**Comment by tengqm** [comment]
This is related to load-balancing but not relied upon it. The API servers need leader elections as other cluster components do. That is why at least three nodes are required for quorum.

**Comment by liuyanzhen34** [comment]
老师您好，感谢您的及时耐心的回复。关于k8s选举的问题，我查询了很多的资料，大部分都是如下的表述：在k8s的组件中，其中有kube-scheduler和kube-controller-manager两个组件是有leader选举的，这个选举机制是k8s对于这两个组件的高可用保障。需要–leader-elect=true启动参数。即正常情况下kube-scheduler或kube-manager-controller组件的多个副本只有一个是处于业务逻辑运行状态，其它副本则不断的尝试去获取锁，去竞争leader，直到自己成为leader。如果正在运行的leader因某种原因导致当前进程退出，或者锁丢失，则由其它副本去竞争新的leader，获取leader继而执行业务逻辑。
  对于上面的表述，那这么说明apiserver是不不需要选举的，只有kube-controlle-rmanager和kube-scheduler是需要选举的，而且这种选举还是抢占式的获取锁选举机制，那这样也不是您说的的符合法定半票以上的选举机制，那这样一来，即便2个master，也可以呀？期待专家老师的指导。谢谢
————————————————
版权声明：本文为CSDN博主「码农实战」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/ll837448792/article/details/93618470

**Comment by liuyanzhen34** [comment]
In order to get many replies from all over the world, I translate above chinse into english:
Dear teacher, thank you for your prompt and patient reply. As for the K8S election, I have inquired a lot of information, most of which are expressed as follows: Among the components of K8S, two components, Kube-scheduler and Kube-controller-manager, have leader election. This election mechanism is the guarantee of high availability of K8S for these two components. Requires -- leader-elect=true for the startup parameter. That is, under normal circumstances, only one copy of the Kube-Scheduler or Kube-Manager-Controller component is in the running state of the business logic, while the other copies keep trying to get the lock and compete for the leader until they become the leader themselves. If for some reason the running leader causes the current process to exit or the lock is lost, then other replicas compete for the new leader to obtain the leader and execute the business logic.

For the above statement, it means that apiserver does not need to be elected, only Kube-Controlle-Manager and Kube-Scheduler need to be elected, and this election is a preemptive lock acquisition election mechanism. In this way, even if there are two masters, it is also OK. Look forward to the guidance of expert teachers. thank you

**Comment by tengqm** [comment]
@liuyanzhen34 Double checked the configuration settings for kube-apiserver, it does seem that the API server doesn't need a leader election. So ... you are correct if you think about the setup from leader election perspective.

If you instead think about the cluster deployment topology, where would you place your API servers, kube-controller-manager and kube-scheduler instances? Suppose you have two API server instances but three kcm and three schedulers for quorum?

**Comment by liuyanzhen34** [comment]
@tengqm  firstly thank you , I think that  although  Kube-Controlle-Manager and Kube-Scheduler need to be elected, this election is a preemptive lock acquisition election mechanism,not for quorum,so not need 3 three masters
