### ISSUE TITLE
A newline is added to the end of Commands

### ISSUE THREAD

**Issue by devNajjary** [kubernetes/website#28660]
hi
I had a problem after copying and pasting  the command and Kubctl was not installed and show me error:

`/usr/local/bin/kubectl: 2: Syntax error: newline unexpected`

After that, i remove Kubctl and install again but removed newline from end of command  
Now everything is OK.

I suggest  make a copy button for each command

**Comment by sftim** [comment]
@devNajjary would you be able to let us know an example of a web page where you see these symptoms, and explain what steps we can take to see the problem as you experienced it?

**Comment by devNajjary** [comment]
if you triple click on command text  and copy/paste to Linux terminal show this:
 
![image](https://user-images.githubusercontent.com/17889773/124551811-efabf380-de47-11eb-93f8-86e95234c149.png)

**Comment by RA489** [comment]
> @devNajjary would you be able to let us know an example of a web page where you see these symptoms, and explain what steps we can take to see the problem as you experienced it?

I think @devNajjary is talking about this web page https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux

**Comment by RA489** [comment]
@devNajjary It works well for me with no errors

```
$curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    389      0 --:--:-- --:--:-- --:--:--   388
100 44.2M  100 44.2M    0     0  5672k      0  0:00:07  0:00:07 --:--:-- 6684k

```

**Comment by sftim** [comment]
@devNajjary if you can explain more about how to replicate the error (which shell, which OS, which web browser, and what error you see) that might help us to fix the page.

I suspect though that the existing web page is correct.
