### ISSUE TITLE
Issue with k8s.io/fr/docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by 4nass** [kubernetes/website#28689]
Typo in frensh Statefulset documentation:

Garanties de **_déploiment_** et de mise à l'échelle -> Garanties de **_déploiement_** et de mise à l'échelle

https://kubernetes.io/fr/docs/concepts/workloads/controllers/statefulset/#garanties-de-d%C3%A9ploiment-et-de-mise-%C3%A0-l-%C3%A9chelle

**Comment by anubha-v-ardhan** [comment]
I'm working on this
