### ISSUE TITLE
Issue with assign-cpu-resource and assign-mem-resource page titles

### ISSUE THREAD

**Issue by rajeshdeshpande02** [kubernetes/website#28706]
**Problem:**
Compute resources such as memory and CPU are assigned to the Container and not to the Pod.  But the tasks for these activities have titles that indicate resources are assigned to the pod also. For example, the task page for assigning memory to a container has the title 'Assign Memory Resources to Containers and Pods '.

**Proposed Solution:**
Change the title from 'Assign Memory Resources to Containers and Pods ' to 'Assign Memory Resources to Containers ' and from 'Assign CPU Resources to Containers and Pods ' to 'Assign CPU Resources to Containers ',

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/
https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/

**Comment by anubha-v-ardhan** [comment]
I'm working on this : )

**Comment by rajeshdeshpande02** [comment]
@anubha-v-ardhan Please wait till this issue gets accepted.

**Comment by anubha-v-ardhan** [comment]
> @anubha-v-ardhan Please wait till this issue gets accepted.

Sorry, I'm new. How do I know if an issue is accepted or not

**Comment by rajeshdeshpande02** [comment]
> > @anubha-v-ardhan Please wait till this issue gets accepted.
> 
> @rajeshdeshpande02 Sorry, I'm new. How do I know if an issue is accepted or not

@anubha-v-ardhan a label triage accepted will be added to issue
