### ISSUE TITLE
Suggestion for https://k8s.io/docs/concepts/storage/volume-snapshot-classes/

### ISSUE THREAD

**Issue by edoardo-c** [kubernetes/website#28728]
The is a typo in the Deletion Policy section

"It enables you to configure what happens to a VolumeSnapshotContent when the VolumeSnapshot object it is bound to is to be deleted."

**Comment by rajeshdeshpande02** [comment]
@edoardo-c Can you please provide the issue description?

**Comment by edoardo-c** [comment]
The is a typo in the `Deletion Policy` section

"It enables you to configure what happens to a VolumeSnapshotContent when the VolumeSnapshot object it is bound to is to be deleted."

**Comment by mehabhalodiya** [comment]
Hey @edoardo-c 
Can you tell me what's the type exactly in `volume-snapshot-classes.md`?

**Comment by edoardo-c** [comment]
Hi @mehabhalodiya,

I'm not sure what they tried to say. My guess is this:

`It enables you to configure what happens to a VolumeSnapshotContent when the VolumeSnapshot object it is bound to is deleted.`

**Comment by divya-mohan0209** [comment]
Ugh. Typo.
/remove-lifecycle stale

**Comment by divya-mohan0209** [comment]
@edoardo-c : The wording is correct IMO. The deletion policy allows you to configure what happens to a `VolumeSnapshotContent` when the associated `VolumeSnapshot` object will be deleted. For reference, if you checkout [the delete section](https://kubernetes.io/docs/concepts/storage/volume-snapshots/#delete) on the Volume Snapshots page, it explicitly states how the policy affects the behavior.

**Comment by Shubham82** [comment]
I agree with  @divya-mohan0209. It seems good. For better understanding can we link the [delete section](https://kubernetes.io/docs/concepts/storage/volume-snapshots/#delete) of the Volume Snapshots page under the [DeletionPolicy](https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/#deletionpolicy) of the Volume Snapshot Classes?
@divya-mohan0209 WDYT?

**Comment by Shubham82** [comment]
> I agree with @divya-mohan0209. It seems good. For better understanding can we link the [delete section](https://kubernetes.io/docs/concepts/storage/volume-snapshots/#delete) of the Volume Snapshots page under the [DeletionPolicy](https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/#deletionpolicy) of the Volume Snapshot Classes?
> @divya-mohan0209 WDYT?

Hi, @divya-mohan0209, your thoughts on the above comment?

**Comment by sftim** [comment]
If anyone'd like to add that hyperlink, they are welcome to.
/remove-triage needs-information

/retitle Suggestion for https://k8s.io/docs/concepts/storage/volume-snapshot-classes/

**Comment by Shubham82** [comment]
Thanks @sftim 
I will add  hyperlink for it.

**Comment by Shubham82** [comment]
Added the hyperlink through the following PR: #42205
