### ISSUE TITLE
DNS for Services and Pods docs improvement suggestions

### ISSUE THREAD

**Issue by joestringer** [kubernetes/website#28725]
Here's the text I see in the Pod's DNS policy section today:

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

```
Pod's DNS Policy
DNS policies can be set on a per-pod basis. Currently Kubernetes supports the following pod-specific DNS policies. These policies are specified in the dnsPolicy field of a Pod Spec.

"Default": The Pod inherits the name resolution configuration from the node that the pods run on. See related discussion for more details.
"ClusterFirst": Any DNS query that does not match the configured cluster domain suffix, such as "www.kubernetes.io", is forwarded to the upstream nameserver inherited from the node. Cluster administrators may have extra stub-domain and upstream DNS servers configured. See related discussion for details on how DNS queries are handled in those cases.
"ClusterFirstWithHostNet": For Pods running with hostNetwork, you should explicitly set its DNS policy "ClusterFirstWithHostNet".
"None": It allows a Pod to ignore DNS settings from the Kubernetes environment. All DNS settings are supposed to be provided using the dnsConfig field in the Pod Spec. See Pod's DNS config subsection below.
Note: "Default" is not the default DNS policy. If dnsPolicy is not explicitly specified, then "ClusterFirst" is used.
```

I've found a few issues with this:
* `ClusterFirstWithHostNet` doesn't explain what it does, it just says to use it. As far as I could tell from some discussion with colleagues, it's the same as `ClusterFirst` but using search domains from the node on the pod as well as the search domains from `ClusterFirst`. Is that the case?
* The link for "See related discussion for details on how DNS queries are handled in those cases."  leads here: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#effects-on-pods . However, I cannot find any "effects on pods" section. Perhaps this was removed or moved at some point? I'd be curious what that discussion was about, but I don't know where it's supposed to be or what the discussion says so it's a bit hard to find without a valid link.

**Comment by sftim** [comment]
/kind bug
because of the broken hyperlink

Thanks for the suggestion @joestringer 
/triage accepted
/priority backlog
