### ISSUE TITLE
Pod Security Standards website updates

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#28721]
**This is a Feature Request**

Umbrella issue tracking pending updates to https://kubernetes.io/docs/concepts/security/pod-security-standards/ as part of https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement#pod-security-standards

- https://github.com/kubernetes/website/pull/28587
  - [x] Remove `csi` from the forbidden list of fields for https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted "Volume Types"
- https://github.com/kubernetes/website/pull/28903
  - [x] add `net.ipv4.ip_unprivileged_port_start` to safe sysctl list
  - [x] Update "Capabilities" check in https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline to explicitly enumerate permitted capabilities: AUDIT_WRITE, CHOWN, DAC_OVERRIDE, FOWNER, FSETID, KILL, MKNOD, NET_BIND_SERVICE, SETFCAP, SETGID, SETPCAP, SETUID, SYS_CHROOT
  - [x] Add seccomp baseline check:
    - 1.0-1.18: allow unset annotation or any value other than `unconfined` (xref https://github.com/kubernetes/kubernetes/issues/103388)
    - 1.19+: allow unset field or any type other than "Unconfined"
  - [x] Update seccomp restricted check in 1.19+: field must be set and type must be `RuntimeDefault` or `Localhost`
  - [x] s/cephFS/cephfs/, add photonPersistentDisk
- https://github.com/kubernetes/website/pull/28413
  - [x] Add `windowsOptions.hostProcess` to the baseline policy, with allowed values `undefined` or `false`

TODO:
- [ ] clarify non-root group check we declined to include in PodSecurity initial implementation - https://github.com/kubernetes/kubernetes/issues/103204#issuecomment-870735877
- [ ] clarify inline volumes check: require one of `configMap, downwardAPI, emptyDir, projected, secret, csi, persistentVolumeClaim, ephemeral` to be set

**Comment by tallclair** [comment]
CSI issue was addressed by https://github.com/kubernetes/website/pull/28587 (I don't have edit permissions on this issue)

**Comment by tallclair** [comment]
for seccomp baseline check, xref: https://github.com/kubernetes/kubernetes/issues/103388

**Comment by liggitt** [comment]
/assign @tallclair 
for last two items

**Comment by tengqm** [comment]
/reopen
Looks like we still have some work to do for this?

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/website/pull/31486 to address last two issues

**Comment by mehabhalodiya** [comment]
Closing as all mentioned issues are addressed.
/close
