### ISSUE TITLE
Document how to install kubectl convert plugin

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28724]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/tasks/tools/#kubectl (really, the 3 pages that it links to) to let readers know how to install `kubectl-convert`

**Why is this needed**
1. `kubectl convert` is now delivered as a plugin, not part of the main binary.
2. Kubernetes v1.22 includes lots of [API removals](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) and release v1.22 is the first time lots of readers will really notice the deprecations. However, there has been no API removal release since `kubectl convert` was moved to be a plugin.

**Comments**
/sig cli
/kind feature

/priority important-soon
(IMO)

**Comment by eddiezane** [comment]
ref: https://github.com/kubernetes/kubectl/issues/725

**Comment by sftim** [comment]
<details>
 <summary><em>It's there for the installing</em></summary>
<pre>
$ curl -L -I https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl-convert
HTTP/2 302 
server: nginx
date: Wed, 30 Jun 2021 23:06:44 GMT
content-type: text/html
content-length: 154
location: https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl-convert
via: 1.1 google
alt-svc: clear
</pre>

```
HTTP/2 200 
x-guploader-uploadid: ADPycdsaZMcxEnfiZZ1nzG3phfKLIehdSu7hXEGCVeIrUOnk2KrfRpl4PCNg5Zy9EryF9WsK-w70YFKS6zRwWo1EYpOlqxLDZQ
expires: Thu, 01 Jul 2021 00:06:44 GMT
date: Wed, 30 Jun 2021 23:06:44 GMT
cache-control: public, max-age=3600
last-modified: Thu, 08 Apr 2021 17:54:04 GMT
etag: "872a8ed0bd1878cb825c5c8be52b62bd"
x-goog-generation: 1617904444155458
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 53419368
x-goog-meta-goog-reserved-file-mtime: 1617902423
content-type: application/octet-stream
x-goog-hash: crc32c=K2T6jA==
x-goog-hash: md5=hyqO0L0YeMuCXFyL5StivQ==
x-goog-storage-class: STANDARD
accept-ranges: bytes
content-length: 53419368
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```
</details>


Where current docs say to fetch (eg) `https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl`, let's tell them to install `https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl-convert` as well.

**Comment by bhumijgupta** [comment]
Since kubectl-convert is a separate binary, should reference of the command from [kubectl overview](https://kubernetes.io/docs/reference/kubectl/overview/) page also be removed?

**Comment by sftim** [comment]
/help

I'm willing to revise this issue description if it's not clear how to make these changes.

**Comment by sftim** [comment]
@bhumijgupta what you're asking sounds like a separate issue.

**Comment by bhumijgupta** [comment]
@sftim I would like to work on this issue. From what I understand, a new command to download `kubectl-convert` has to be added under the first point titled `Download the latest release` for all the three operating systems something like this.
```markdown
Download kubectl-convert (optional)  
`curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert`
```


Does verifying checksum step also have to added for kubectl-convert?

**Comment by sftim** [comment]
> Does verifying checksum step also have to added for kubectl-convert?

Yes, we should let readers know how to check that the software they download is genuine.

**Comment by sftim** [comment]
We should also briefly explain what `kubectl convert` does (a hyperlink is OK)

**Comment by bbugh** [comment]
@bhumijgupta the command line reference page still lists `convert` - https://kubernetes.io/docs/reference/kubectl/overview/

**Comment by mathijsfr** [comment]
How do you install kubectl convert for windows? I don't seem to have it installed.

**Comment by sftim** [comment]
I'm going to mark https://github.com/kubernetes/website/issues/28724#issuecomment-1279938883 as off-topic; the original issue _is_ resolved.

**Comment by piradata** [comment]
How is this issue resolved/closed?

I didn't found anywhere on the docs how to install the `kubectl-convert` plugin/binary, only found this info on a third-party site: https://pet2cattle.com/2022/06/kubectl-convert

This really should be better documented, and there is still a mention of this command on this page without any word about it being deprecated and transformed into a plugin/binary:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#migrate-to-non-deprecated-apis

**Comment by sftim** [comment]
> How is this issue resolved/closed?
> 
> I didn't found anywhere on the docs how to install the `kubectl-convert` plugin/binary, only found this info on a third-party site: https://pet2cattle.com/2022/06/kubectl-convert

Try this link:
https://www.google.com/search?q=install+kubectl+convert

For me, the top search result is to a page with a section “Install `kubectl convert` plugin”. I think this issue was OK to close.

**Comment by piradata** [comment]
> For me, the top search result is to a page with a section “Install kubectl convert plugin”. I think this issue was OK to close.

Truly, didn't have found this section, thanks 😄

But i also didn't expected a deprecated command installation instructions would be directly on the page that teaches how to install the `kubectl` command itself, thought it would be in a `plugins` or `deprecation apis` section.

Can we at least add the link about [how to install kubectl convert plugin](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-convert-plugin) on the page that teaches how to [migrate to non deprecated apis](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#migrate-to-non-deprecated-apis)?

That what people trying to migrate from 1.22 to 1.23 would find it easier.

**Comment by tford-umd** [comment]
I'm on a macbook pro Ventura 13, M1 chip.  I followed the instructions using ARM64 version.  Step 3 didn't work, so I used this instead:

`install -o $(whoami) -g $(id -gn) -m 0755 kubectl-convert /usr/local/bin/kubectl-convert`

Then, ran `kubectl convert -help` and got: "Error: exec format error"

**Comment by Gauravpadam** [comment]
> Am I doing something wrong or does this plugin not work on Mac with M1?

@tford-umd You should try asking in [Kubernetes slack channel](https://kubernetes.slack.com/messages/CNXNB0ZTN)
