### ISSUE TITLE
kube-apiserver Audit Configuration (v1)

### ISSUE THREAD

**Issue by aaabdallah** [kubernetes/website#28735]
Under the section for PolicyRule, the following is written:

> "Requests must match the rules of every field (an intersection of rules)."

That seems a bit confusing, or at least could be written better. The word "rules" on this page is more or less taken by the rules found in a Policy, where the first matching rule for a request is used.

The intent of the author who wrote this is reasonably clear, but it seems there is a better choice of words here.

**Comment by sftim** [comment]
I think this issue report is about the page at https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/

**Comment by aaabdallah** [comment]
> 
> 
> I think this issue report is about the page at https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/

Correct, I apologize I did not include the link in my original comment.

**Comment by tengqm** [comment]
Any proposals on fixing this should go to the upstream source code, from which the reference doc is generated.
Source code link: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/v1/types.go#L182-L183

/close

**Comment by sftim** [comment]
@aaabdallah if you'd like help raising an issue against that upstream source code, ask in #sig-docs on the Kubernetes Slack channel. See https://slack.k8s.io/ if you'd like an (robot issued) invitation.
