### ISSUE TITLE
TopologyManager documentation possible mistakes

### ISSUE THREAD

**Issue by Padarn** [kubernetes/website#28747]
**This is a Bug Report**

This is trivial and perhaps incorrect on my behalf, but some of the working on the documentation here https://kubernetes.io/blog/2020/04/01/kubernetes-1-18-feature-topoloy-manager-beta/ seems a bit odd. 

Firstly, we have the example of `TopologyHInts`:

```
{01: True}, {10: True}, {11: False}
```

Along with the statement 

```
Normally, this will only be True for TopologyHints with a single NUMA node set in their bitmask
````

These seem to contradict each other.

In the following section we also have this statement 

```
NOTE: Setting of the Preferred field in this way is not based on the set of currently available resources. It is based on the ability to physically allocate the number of requested resources on some minimal set of NUMA nodes.

In this way, it is possible for a HintProvider to return a list of hints with all Preferred fields set to False if an actual preferred allocation cannot be satisfied until other containers release their resources. 
```

This again seems a bit backwards: Presumably the `HintProvider` should return all **True** (or for the setting of preferred field to be set on currently available resources - rather than **not based on**)

Sorry if I misunderstood something.

**Page to Update:**
https://kubernetes.io/blog/2020/04/01/kubernetes-1-18-feature-topoloy-manager-beta/

**Comment by sftim** [comment]
Hi

https://kubernetes.io/blog/2020/04/01/kubernetes-1-18-feature-topoloy-manager-beta/ is actually not part of the documentation, its from a blog article.
/area blog

We typically wouldn't pick up correction a blog about a now-unsupported release. The Kubernetes project maintains release branches for the most recent three minor releases. Currently, that's: v1.19, v1.20, v1.21.

@padarn if you'd like to make sure that the current Topology Manager [task](https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/) page, or about improving the [Device Plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-integration-with-the-topology-manager) concept, we'd be happy to accept an issue about the documentation itself.

**Comment by Padarn** [comment]
Hi @sftim - Thanks for the clarification. I'll close this issue now, I should have checked that this was the right place for this issue earlier.
