### ISSUE TITLE
Outdated Korean contents in the dev-1.21-ko.6 branch

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#28746]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.21-ko.6 branch.
Report from the `./scripts/diff_l10n_branches.py ko upstream/dev-1.21-ko.5 upstream/dev-1.21-ko.6`.

### 26 files to be modified 
1. [x] M1.  `content/en/_index.html`  | 1(+XS) 1(-)
1. [x] M2.  `content/en/docs/concepts/architecture/nodes.md`  | 16(+S) 1(-)
1. [x] M3.  `content/en/docs/concepts/cluster-administration/manage-deployment.md`  | 1(+XS) 1(-)
1. [x] M4.  `content/en/docs/concepts/configuration/organize-cluster-access-kubeconfig.md`  | 5(+XS) 1(-)
1. [x] M5.  `content/en/docs/concepts/containers/images.md`  | 14(+S) 0(-)
1. [x] M6.  `content/en/docs/concepts/extend-kubernetes/operator.md`  | 2(+XS) 1(-)
1. [x] M7.  `content/en/docs/concepts/policy/pod-security-policy.md`  | 50(+M) 10(-)
1. [x] M8.  `content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md`  | 6(+XS) 6(-)
1. [x] M9.  `content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md`  | 17(+S) 4(-)
1. [x] M10.  `content/en/docs/concepts/services-networking/dns-pod-service.md`  | 1(+XS) 1(-)
1. [x] M11.  `content/en/docs/concepts/storage/volumes.md`  | 12(+S) 0(-)
1. [x] M12.  `content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md`  | 7(+XS) 5(-)
1. [x] M13.  `content/en/docs/contribute/generate-ref-docs/quickstart.md`  | 3(+XS) 3(-)
1. [x] M14.  `content/en/docs/contribute/new-content/open-a-pr.md`  | 9(+XS) 9(-)
1. [x] M15.  `content/en/docs/contribute/new-content/overview.md`  | 2(+XS) 2(-)
1. [x] M16.  `content/en/docs/contribute/participate/_index.md`  | 2(+XS) 2(-)
1. [x] M17.  `content/en/docs/contribute/participate/pr-wranglers.md`  | 2(+XS) 2(-)
1. [x] M18.  `content/en/docs/contribute/participate/roles-and-responsibilities.md`  | 2(+XS) 2(-)
1. [x] M19.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 2(+XS) 1(-)
1. [x] M20.  `content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md`  | 7(+XS) 0(-)
1. [x] M21.  `content/en/docs/tasks/administer-cluster/certificates.md`  | 3(+XS) 0(-)
1. [x] M22.  `content/en/docs/tasks/administer-cluster/highly-available-control-plane.md`  | 2(+XS) 2(-)
1. [x] M23.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md`  | 1(+XS) 1(-)
1. [x] M24.  `content/en/docs/tasks/tls/certificate-rotation.md`  | 3(+XS) 3(-)
1. [x] M25.  `content/en/docs/tutorials/configuration/configure-redis-using-configmap.md`  | 2(+XS) 2(-)
1. [x] M26.  `content/en/examples/policy/restricted-psp.yaml`  | 3(+XS) 4(-)

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.21-ko.6` branch.

For example:
```
# checkout `upstream/dev-1.21-ko.6`
...
# check what is updated in the upstream 
git diff upstream/dev-1.21-ko.5 upstream/dev-1.21-ko.6 -- content/en/_index.html
# apply changes to content/ko
vi content/ko/_index.html
...
# commit and push
...
# make PR to `upstream/dev-1.21-ko.6`
```

## Pages to Update

Pages in content/ko

**Comment by niteshseram** [comment]
Can I work on this?

**Comment by seokho-son** [comment]
Hi @nitehseram , 
Whereas this issue for maintaining Korean localization branch, we are welcome contributions! :)
However, this issue requires understanding of Korean language. I hope to check you can handle Korean contents.

**Comment by niteshseram** [comment]
Hello @seokho-son,  I can see there are some files that don't require us to change the things in Korean. Is It okay if I make the PR for those changes only

**Comment by seokho-son** [comment]
@niteshseram Sure :) Thank you.
Could you tell me which files can be handled by you? 
I will invite and assign additional contiributors who can handle the other files.

**Comment by niteshseram** [comment]
@seokho-son I had a look at all the files carefully. 
It seems only _index.html file doesn't require changes in Korean and all other files do. So maybe I can only make a PR for the _index.html file. 
But feel free to assign to anyone else because I am already struggling to run the website locally on my machine.

**Comment by seokho-son** [comment]
M20 - M26 on me :)
/assign @seokho-son 

M1 : @niteshseram 
M2 - M19 : TBD (Help!, you can take this partially)
M20 - M26 : @seokho-son

**Comment by jihoon-seo** [comment]
- M2
- M11 - M19

on me 😊

/assign

**Comment by jihoon-seo** [comment]
M3 - M10 on me 😊

**Comment by seokho-son** [comment]
M1 : @niteshseram
M2 - M19 : @jihoon-seo 
M20 - M26 : @seokho-son

Thank you!!

**Comment by seokho-son** [comment]
Done!

/close
