### ISSUE TITLE
Deprecated but referenced kubelet flags in k8s.io/docs/concepts/cluster-administration/logging/

### ISSUE THREAD

**Issue by SudoNova** [kubernetes/website#28774]
It's mentioned that:
>  The two kubelet flags container-log-max-size and container-log-max-files can be used to configure the maximum size for each log file and the maximum number of files allowed for each container respectively.

But [here](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) we have:

> (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

And in the [mentioned reference](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/) there is another reference to [Kubelet Configuration (v1beta1)
](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) which has a brief [LoggingConfiguration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#LoggingConfiguration) section, that links to a [source code](https://github.com/kubernetes/component-base/blob/master/logs/options.go) which does not contain any configuration option information.
Though there are two separate issues here, my point is if it's deprecated, it should not be in the docs, or should be marked as deprecated until fresh documentation is provided.

**Comment by chenxuc** [comment]
I will update k8s.io/docs/concepts/cluster-administration/logging/ for the correct way to use these option.
/triage accepted
/assign

**Comment by chenxuc** [comment]
the doc has been updated.
/close
