### ISSUE TITLE
ControllerManagerLeaderMigration feature gate is not listed in feature gates page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28787]
**This is a Bug Report**

**Problem:** [Feature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) doesn't list ControllerManagerLeaderMigration although there is a [task](https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/) page that mentions it.

**Proposed Solution:**
Update / write the documentation for the feature, including a mention of `ControllerManagerLeaderMigration` in https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Additional Information:**
/sig cloud-provider

**Comment by sftim** [comment]
@PI-Victor I think there's a plan to graduate this to beta; if so, we should definitely look at getting it properly documented.

**Comment by PI-Victor** [comment]
yup, agreed. I think we can address it once they open a doc for their enhancement
/cc @chrisnegus 
/triage accepted
