### ISSUE TITLE
Document feature gates for kubeadm

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28788]
**This is a Feature Request**

**What would you like to be added**
Document all the feature gates for kubeadm

**Why is this needed**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ should be a list of feature gates for at least all in-tree tools. I'm not sure if we count kubeadm as in-tree but it's certainly a core part of Kubernetes in terms of how we document things.

If we don't document the kubeadm feature gates in 
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ then instead 
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ should hyperlink to a page that does.

**Comments**
Prompted by https://github.com/kubernetes/enhancements/issues/2568#issuecomment-873584540
/sig cluster-lifecycle

**Comment by neolit123** [comment]
commented here:
https://github.com/kubernetes/enhancements/issues/2568#issuecomment-873642653

historically, kubeadm has not been much of a FG user, but once a feature moves to beta we always document it at k8s.io.

if anyone wants to contribute this it must be a new page.
/help

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/pull/28036 (generate feature gate lists from data) - for context only. No need for kubeadm to participate in the automation.

**Comment by sftim** [comment]
/priority important-longterm
People might want to try out alpha features; we should make it clear how they can, _and_ follow docs conventions to explain that these are alpha.

(same for beta, if that applies)

**Comment by neolit123** [comment]
https://github.com/kubernetes/website/pull/31687
merged.

/close
