### ISSUE TITLE
Mention or link to security embargo policy

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28786]
**This is a Feature Request**

**What would you like to be added**
Mention the [security embargo policy](https://github.com/kubernetes/security/blob/master/private-distributors-list.md#embargo-policy) within https://k8s.io/releases/, or link to it.

**Why is this needed**
Readers might have an interest in knowing how security fixes are planned and communicated.

**Comments**
/sig release
/sig security
/language en
/kind feature

**Comment by Shubham82** [comment]
/assign
I can work on this.

**Comment by Shubham82** [comment]
Hi @sftim
Please suggest which option from the following I will go with 
In this, we will have to make a page for embargo policy(security-embargo-policy.md)  as we do not mention the link directly.
1) Copy the whole content from the [security/private-distributors-list.md](https://github.com/kubernetes/security/blob/master/private-distributors-list.md) to security-embargo-policy.md. which seems redudant as it already mention in kubernete/security.
2) Mention the below text and then the link to [security/private-distributors-list.md](https://github.com/kubernetes/security/blob/master/private-distributors-list.md)  for more details like: 

> To know about Security Embargo Policy in Kubernetes like what is it? what are the prerequisites to join the distributors-announce@kubernetes.io mailing list? How can you raise a request for joining it? for all those details please refer to this [document](https://github.com/kubernetes/security/blob/master/private-distributors-list.md)  Which give you an idea of how security fixes are planned and communicated in k8s.

**Comment by sftim** [comment]
I can clarify: this issue is about explaining that some information about upcoming releases is subject to embago, and that there is a defined policy about how those embargos are set.

I don't see a need to mention how to join the mailing list for distributors within https://k8s.io/releases/. If someone is maintaining a Kubernetes distribution, I hope they're able to follow hyperlinks well enough to work that out.

> which seems redudant as it already mention in kubernete/security.

We have readers who might not think to look there. That's why we should refer to it (a hyperlink could be OK).

**Comment by Shubham82** [comment]
Thanks @sftim for suggestion.
will create a pr for it soon.

**Comment by Shubham82** [comment]
fixed it here: #28810
