### ISSUE TITLE
State of Logging Architecture with journald

### ISSUE THREAD

**Issue by ajfriesen** [kubernetes/website#28798]
I have read the [Logging Architecture](https://kubernetes.io/docs/concepts/cluster-administration/logging/#logging-at-the-node-level) page.

I am currently not sure what the state of the kubernetes community and project is to use the docker log driver of journald instead of json file.

The company I work for provides a Kubernetes Paas.
We host several for customers.
Technically I really like that journald can handle the log rotation and you do not have to worry about that anymore.
But some customers are surprised about our decision and I just want to reevaluate our decision.

- Is this a supported and also recommended scenario?
- Is this just not documented yet?
- What is your general take on that?

Happy to help by adding documentation, if needed.

**Comment by sftim** [comment]
We'd love to see that page improved @ajfriesen!

Kubernetes itself is not a logging solution, and is largely agnostic about which solution you might prefer. Some popular technologies that are relevant to Kubernetes cluster operators and cloud native developers include Fluent, OpenTelemetry, `systemd-journald`, Loki, and Honeycomb. There are many more; https://landscape.cncf.io/card-mode?category=logging&grouping=category lists 18.

A few things:
- we have a shortcode for embedding CNCF landscape in pages. That might be useful? See https://kubernetes.io/training/#kubernetes-training-partners for an example
- https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed defines what is (and isn't) allowed. We don't favor 3rd party solutions and projects other others even if they are siblings within the CNCF.
- we definitely don't recommend which solution to adopt

I'd also be very happy to see a [blog](https://blog.k8s.io/) post about logging and what to _look for_ in a solution. We don't recommend one technology over another in our articles - we let vendors write that kind of content up on their own websites. A neutral article explaining what to consider when you choose would be really useful.

If you want to get started on improving that page (even a little), check out https://k8s.io/docs/contribute/
