### ISSUE TITLE
I want my table to render without splitting words

### ISSUE THREAD

**Issue by ankeesler** [kubernetes/website#28815]
**This is a Bug Report**

**Problem:**

- I want my table to render without splitting words.
- Rendering: ![image](https://user-images.githubusercontent.com/3081590/124658006-3cf08b00-de71-11eb-906a-b7884ca3ed11.png)
- Source:
```
| `interactiveMode` Value | Meaning |
| ----------------------- | ------- |
| `Never` | This exec plugin never needs to use standard input, and therefore the exec plugin will be run regardless of whether standard input is available for user input. |
| `IfAvailable` | This exec plugin would like to use standard input if it is available, but can still operate if standard input is not available. Therefore, the exec plugin will be run regardless of whether stdin is available for user input. If standard input is available for user input, then it will be provided to this exec plugin. |
| `Always` | This exec plugin requires standard input in order to run, and therefore the exec plugin will only be run if standard input is available for user input. If standard input is not available for user input, then the exec plugin will not be run and an error will be returned by the exec plugin runner. |
```

**Proposed Solution:**

- Eh, I dunno...give the user some way to control this?

**Page to Update:**

- This comes from https://github.com/kubernetes/website/pull/28429#discussion_r664774943.

**Comment by PI-Victor** [comment]
hmm, maybe

/area web-development

**Comment by sftim** [comment]
In CSS, it could be something like:
if a monospaced `<tt>` element is the first _and_ last child of a `<td>` (ie, it's the whole cell) then try to avoid wrapping.

If there's no pure-CSS solution, we could improve the existing table shortcode to let you specify colgroups. Sounds trick though!
