### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/included/

### ISSUE THREAD

**Issue by afolarin** [kubernetes/website#28813]
https://kubernetes.io/docs/tasks/tools/included/  seems orphaned in RHS menu.

**Comment by sftim** [comment]
As I understand it, these are intended as headless pages and shouldn't appear rendered at all.
/kind bug
/language en
/triage accepted

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/29782 AIUI
/close
