### ISSUE TITLE
Use Port Forwarding to Access Applications in a Cluster

### ISSUE THREAD

**Issue by imoisharma** [kubernetes/website#28823]
Link: kubectl apply -f https://k8s.io/examples/application/guestbook/mongo-deployment.yaml is removed. Fix the new URL for the mong-deployment.yaml

Site Link: https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/

**Comment by jihoon-seo** [comment]
This issue will be resolved when the PR #28530 is merged.

**Comment by jihoon-seo** [comment]
This issue is resolved since the PR #28530 has been merged.
/close

**Comment by imoisharma** [comment]
Cheers.
