### ISSUE TITLE
kubeadm cgroupDriverAdvice is specific to a Kubernetes version

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28836]
**This is a Bug Report**

**Problem:**
The v1.22 version of `/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md` ([permalink](https://github.com/kubernetes/website/blame/61047b9fa9440b39bebfbd0c7654f68dd0d9a26f/content/en/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md#L36)) shows some text:
> In v1.22, if the user is not setting the `cgroupDriver` field under `KubeletConfiguration`, `kubeadm` will default it to `systemd`.

This might / will confuse readers when v1.23 is released as to what the default behavior is for a v1.23 cluster.

**Proposed Solution:**
Reword that note. Either:
- omit the mention of versions entirely; the Kubernetes documentation itself is versioned
- write “If you do not  set the `cgroupDriver` field under `KubeletConfiguration`, `kubeadm` will default it to `systemd`”, and _also_ remind readers to check that they are reading the right version of the docs for the cluster they want to deploy.
- something equivalent

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

**Kubernetes Version:**
v1.22

**Additional Information:**
/sig cluster-lifecycle

**Comment by neolit123** [comment]
@sftim the discussion about this exact wording was here and you participated:
https://github.com/kubernetes/website/pull/28049#discussion_r636012074

> If there's no relevant feature gate it might be more reasonable to remove the shortcode and use text to explain what versions provide what behavior.

later the PR was approved as is.

**Comment by sftim** [comment]
aside: _I think this is SIG Docs pretty much_ working as intended.
_We merged some useful docs updates, and now we have a chance to make a follow-on PR that makes them even better._
