### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by filipp-filippov** [kubernetes/website#28846]
In ingress documentation, for first sight, it's not obvious that when you deploy a nginx ingress controller you have to use cloud managed load balancer or any other bastion server to redirect your requests to ingress controller service port.
I.e. let's say you k8s cluster installed on bare-maetal, or you don't like to use cloud load balancer service for this cluster by some reason, and all of your nodes exposed to the private network, so to access any of resources, first of all you need to call ingress-controller service, which is usually exposed via nodeport, i.e. if you have DNS record for **k8s.mycompany.local** which contains ip adresses of all of your nodes, you can't simply call your service using CNAME record like **myservice.mycompany.local/$PATH** which is reffering to **k8s.mycompany.local**. You'll need to call **myservice.mycompany.local:$INGRESS_CONTROLLER_PORT/$PATH**, since exposure of ports 80 and 443 not always possible.
Could you please add this clarification somewhere? I believe it will be useful for users who are new to ingress.
Thanks.

**Comment by sftim** [comment]
@filipp-filippov this sounds a bit like a detail of a _specific_ Ingress controller - there are lots of different ones and some don't need the steps you've mentioned.

What might be good is a tutorial for each of the in-project Ingress controllers (AWS, GCP and nginx). However, getting those added means finding folks to volunteer to write them. I hope it does happen.

**Comment by filipp-filippov** [comment]
@sftim, probably I could describe couple of examples for AWS and Bare metal installations, if it would make sense. Please let me know where I should post it?
