### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/dns-custom-nameservers/

### ISSUE THREAD

**Issue by fbrier** [kubernetes/website#28844]
It is not clear how to edit the yaml and corefile contents that are illustrated. There are no command line or descriptions of how to change them via the dashboard (ie: what are the names and namespaces of the pods/services/ConfigMaps that contain these values). I am trying to determine why CoreDNS is not forwarding requests to the DNS server specified in the "microk8s enable dns:xxx.xxx.xxx.xxx". Using the DNS troubleshooting page is showing that the DNS is not resolving properly.

**Comment by sftim** [comment]
/kind support
The [CoreDNS documentation](https://coredns.io/) might also cover this - does that help?

I'm not sure what principal question you had @fbrier. I looked at the page and the manifests I saw _did_ mention namespaces.

To anyone: I think this page should mention familiarity with `kubectl` or similar tools as a prerequisite.
