### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/pods/

### ISSUE THREAD

**Issue by djedjethai** [kubernetes/website#28848]
This is the ''Pod" page, wy are you showing an exemple of a "Job" object ????

**Comment by chenxuc** [comment]
I think the example in this page is correct.

The Job object contains a Pod. The example is to show how to use the Pod template inside the Job. In may real world usage cases, a Pod is usually created by other higher level workload objects, such as Jobs or Deployments.

**Comment by djedjethai** [comment]
Make sense, but still imagine someone learning k8s(same me) need a Pod's template for some exercices, he should look into the official documentation's Pod page but unfortunatly there is no Pod but a Job. In fact to get a single Pod's template he should go to the Service-account's page or the Probes's page or even the Managing-Resources-For-Containers's page..... It's kind of strange.

**Comment by tylerauerbeck** [comment]
I actually think I agree with @djedjethai here. For folks who have some experience with k8s, this makes sense and they know that a job will launch a pod. But for this doc, which is primarily targeted at beginners, using a `Job` to show `Pod` concepts could be a bit confusing and IMO would benefit from an update to reference a `Pod` template directly.

**Comment by sftim** [comment]
To work on this:
- edit https://k8s.io/docs/concepts/workloads/pods/ to show creating a Pod directly
- then immediately explain that usually you use a workload resource do that indirectly (and link to the section of the page that introduces an example Job).

/help

**Comment by 100mik** [comment]
I would love to take this up, if that's fine!
/assign

**Comment by sftim** [comment]
For Kubernetes SIG Docs, anyone can work on any issue (our more jargon-y way of saying this is “no [cookie licking](https://devblogs.microsoft.com/oldnewthing/20091201-00/?p=15843)”) and open a pull request to propose a related change.

**Comment by 100mik** [comment]
Oops I didn't know that! Sorry. Thanks for letting me know. 
I'll put in a PR soon!
