### ISSUE TITLE
Use Port Forwarding to Access Applications in a Cluster

### ISSUE THREAD

**Issue by sgpinkus** [kubernetes/website#28854]
Broken link to https://k8s.io/examples/application/guestbook/mongo-deployment.yaml.

**Comment by jihoon-seo** [comment]
- This issue will be resolved when the PR #28530 is merged.
- (#28823)

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/28530#issuecomment-865483779 is relevant here too.

**Comment by jihoon-seo** [comment]
This issue is resolved since the PR #28530 has been merged.
/close
