### ISSUE TITLE
PodSecurity Beta documentation

### ISSUE THREAD

**Issue by tallclair** [kubernetes/website#28867]
Documentation we want to add before PodSecurity goes to beta. Depends on https://github.com/kubernetes/website/issues/28866.

- [ ] ~~Extending PodSecurity: extension points in the code, maybe a pointer to another page (or docs on the pod-security-admission repo)~~ punted to https://github.com/kubernetes/kubernetes/issues/106561
- [ ] ~~What do when you need more control: pros/cons of extending, running alongside a 3p plugin, migrating to a 3p plugin~~
- [ ] Webhook usage & installation instructions

**Comment by sftim** [comment]
/triage accepted
/sig auth
/sig security
/sig docs
/priority important-longterm

I recommend documenting that contextual detail within https://k8s.io/docs/concepts/security/

**Comment by liggitt** [comment]
`Webhook usage & installation instructions` is tracked in https://github.com/kubernetes/website/issues/30133

**Comment by tallclair** [comment]
Resolved by #30351
