### ISSUE TITLE
Improvement for k8s.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by sgpinkus** [kubernetes/website#28861]
On [dynamic volume binding](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic) it is stated:

> To enable dynamic storage provisioning based on storage class, the cluster administrator needs to enable the DefaultStorageClass admission controller on the API server. 

This seems strange. The purpose of the "DefaultStorageClass admission controller" seems merely to be to provide a default value for `PVC.storageClassName` if it is absent. Why should whether it is enabled or disabled effect dynamic provisioning? 

The [linked description](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass) of the "DefaultStorageClass admission controller" offers no clue as to why this may be the case:

> This admission controller observes creation of PersistentVolumeClaim objects that do not request any specific storage class and automatically adds a default storage class to them. This way, users that do not request any special storage class do not need to care about them at all and they will get the default one. This admission controller does not do anything when no default storage class is configured. 

That's consistent with "merely to provide a default value for `PVC.storageClassName` when it is absent." as above.

Conclusion: either the first quote is wrong or could really do with further explanation.

**Comment by Kartik494** [comment]
@sgpinkus yes the statement in documentation seems confusing i.e if the PersistentVolumeClaim objects that do not request any specific storage class and automatically adds a default storage class to them,  then why there is need to enable dynamic storage class for  `PVC.storageClassName` !
