### ISSUE TITLE
Google Analytics opt-out via Do Not Track

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28865]
**This is a Feature Request**

**What would you like to be added**
Pretty much this:
https://justmarkup.com/articles/2018-03-01-do-not-track-user-preference/

Add a mechanism to check [`navigator.doNotTrack`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack) and only load Google Analytics for clients that haven't expressed an opt-out preference.

**Why is this needed**
This change means we honor our visitors' / readers' preferences about being tracked.

**Comments**
Similar to #28674

/area web-development
/kind feature

**Comment by bhumijgupta** [comment]
Hey @sftim , I would like to work on this. Is this the correct place to add the validation?
https://github.com/kubernetes/website/blob/4b18015cd363b2c23a119258201dd274940cdc0f/layouts/partials/head.html#L5-L11

**Comment by sftim** [comment]
That might be the right place. https://github.com/kubernetes/website/blob/4b18015cd363b2c23a119258201dd274940cdc0f/layouts/partials/head.html#L36-L38 also looks important. I recommend checking them both out.

**Comment by bhumijgupta** [comment]
Sure. I will look into it.
/assign

**Comment by divya-mohan0209** [comment]
@bhumijgupta Are you interested in continuing work on this? Otherwise, we can open it up for other contributors to pitch in.

**Comment by bhumijgupta** [comment]
@divya-mohan0209 This can be open up for other contributors as I don't have bandwidth to continue working on this.

**Comment by Gauravpadam** [comment]
Hey, Is this issue still relevant and open to work? I'd like to help.

**Comment by divya-mohan0209** [comment]
Yep, this is still open.

**Comment by chalin** [comment]
FYI, from the [Linux Foundation’s Privacy Policy](https://www.linuxfoundation.org/legal/privacy-policy), under **Cookies, Tracking, and Interest-Based Ads**:

> Please note that TLF does not respond to browser “do not track” signals or other similar mechanisms intended.

So this issue might no longer be relevant.

/cc @caniszczyk @nate-double-u
