### ISSUE TITLE
Describe the proper way to restart kube-* pods after manually certificate renewal

### ISSUE THREAD

**Issue by rayw000** [kubernetes/website#28875]
**This is a Bug Report**

**Problem:**
After manually certificate renewal, `kube-apiserver`, `kube-controller-manager` and `kube-scheduler` need to be properly restarted. This should be described in (maybe) this section: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal , and currently not.

Ref: https://github.com/kubernetes/kubernetes/issues/103575

**Proposed Solution:**
Describe if `kube-apiserver`, `kube-controller-manager` and `kube-scheduler` need to be restarted, and also describe the proper way to restart them.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/help
PRs welcome

/priority backlog
given `kubeadm certs renew` prints instructions that users must restart.

> Describe if kube-apiserver, kube-controller-manager and kube-scheduler need to be restarted, and also describe the proper way to restart them.

etcd should be included in this list.

there are multiple ways to restart the static pods:
1. temporary rename the `/etc/kubernetes/manifests` folder for more than 20 seconds [*].
2. restart the containers using the container runtime CLI (setup specific).
...

i'd prefer option 1.

[*]
see `fileCheckFrequency`
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults.go#L62-L63

**Comment by aliakbar-hemmati** [comment]
Hi, I would like to help but I have a question first. How does changing the name of `/etc/kubernetes/manifests/` help? I mean the behavior of Kubelet is not clear for me regarding this fileFrequencyCheck and the corresponding docs do not help, too. I like to explain that in certificate renewal docs, too. @neolit123

**Comment by neolit123** [comment]
The better place to document details about the static pod refresh timeouts
is the "creating static pods page:
https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

If you remove a manifest file, the kubelet will find out about that every
~20sec and remove the pod from managent. If the file is then brought back
the kubelet will recreate the pod acting like a restart.
