### ISSUE TITLE
Adding Windows nodes

### ISSUE THREAD

**Issue by king311247** [kubernetes/website#28873]
According to the documentation https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

join a windows node,the windows host server will crash when the flannel cni container start

my system config like this
![image](https://user-images.githubusercontent.com/10952874/125014041-81616e00-e09f-11eb-9d39-b2bfb63efaa9.png)

![image](https://user-images.githubusercontent.com/10952874/125014236-e7e68c00-e09f-11eb-85aa-2a378320d035.png)

**Comment by tengqm** [comment]
This doesn't look like a documentation issue. Please contact sig-windows for bug report or seek help from their slack channel.
/close
