### ISSUE TITLE
Mirror article “How to choose a SIG as a non-code Kubernetes contributor”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28889]
**This is a Blog issue**

**What would you like to be added**
Copy article https://www.k8s.dev/blog/2021/07/09/how-to-choose-a-sig-as-a-non-code-kubernetes-contributor/ into the blog (folder `content/en/blog`)

**Why is this needed**
We mirror most articles from https://www.k8s.dev/blog/ to https://www.k8s.io/blog/

**Comments**
Set the `canonicalUrl:` field in the [front matter](https://gohugo.io/content-management/front-matter/) to: `https://www.k8s.dev/blog/2021/07/09/how-to-choose-a-sig-as-a-non-code-kubernetes-contributor/`

/area blog
/language en
/good-first-issue

See https://github.com/kubernetes/contributor-site/pull/205#issuecomment-877324201
(I'm fine for someone else to do that copying)

**Comment by Shatakshi0805** [comment]
Hello Tim! I would like to work on this. could be please tell in which file/folder inside the blog repository am I supposed to paste the copied content to? Apologies for asking such question as I am a beginner and not able to understand in which repository I should paste the content as there are multiple files and folders in the blog repository.

**Comment by jihoon-seo** [comment]
Hello @Shatakshi0805 

Source file:
- https://github.com/kubernetes/contributor-site/blob/master/content/en/blog/2021/non-code-contribution.md
- (Raw: https://raw.githubusercontent.com/kubernetes/contributor-site/master/content/en/blog/2021/non-code-contribution.md )

Destination:
Since the original article has no images included,
[`website/content/en/blog/_posts/`](https://github.com/kubernetes/website/tree/main/content/en/blog/_posts) seems proper directory to copy into.

**Comment by Shatakshi0805** [comment]
Thanks @jihoon-seo.

**Comment by jihoon-seo** [comment]
@Shatakshi0805 
@sftim 's suggestion is that
when you create `2021-07-09-how-to-choose-a-sig-as-a-non-code-kubernetes-contributor.md` in [`website/content/en/blog/_posts/`](https://github.com/kubernetes/website/tree/main/content/en/blog/_posts),
add `canonicalUrl: ` field.

e.g.

```
---
layout: blog
title: 'How to choose a SIG as a non-code Kubernetes contributor'
linkTitle: 'How to choose a SIG as a non-code Kubernetes contributor'
Author: Chris Short
date: 2021-07-09
slug: how-to-choose-a-sig-as-a-non-code-kubernetes-contributor
canonicalUrl: https://www.k8s.dev/blog/2021/07/09/how-to-choose-a-sig-as-a-non-code-kubernetes-contributor/
---
```

**Comment by sftim** [comment]
/close

We missed the boat :wink: on this one.
