### ISSUE TITLE
kubefed needs a reference doc

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/website#2888]
`kubectl` and other CLI tools have reference docs that list the available sub-commands. And then each sub-command has its own page that lists the available flags and some common ways of using the sub-command.  `kubefed` needs something similar too.

**Comment by madhusudancs** [comment]
cc @csbell @kubernetes/sig-federation-bugs @irfanurrehman @perotinus

**Comment by madhusudancs** [comment]
Examples here: 
https://kubernetes.io/docs/user-guide/kubectl/
https://kubernetes.io/docs/user-guide/kubectl/kubectl_create/

**Comment by irfanurrehman** [comment]
I will try to take a shot at this.
Meanwhile, I think we should be able to have some way of auto-generating this doc.
Trying to figure out how.
Any guidance on this, and/or the correct placeholder/github location is appreciated.. :-)

**Comment by nikhiljindal** [comment]
This is the code we use to autogenerate other docs: https://github.com/kubernetes/kubernetes/blob/7e0b68239f294179a23a771acf95d381fc3ef3f3/hack/lib/util.sh#L193

**Comment by irfanurrehman** [comment]
@nikhiljindal, thanks a lot for the info. I sort of already had a look at that and could also figure out that for federation commands this is the code -> https://github.com/kubernetes/kubernetes/blob/master/federation/cmd/genfeddocs/gen_fed_docs.go.
I am guessing that adding some code for kubefed will do the trick.

What I couldn't get sure of (and the reason, I posted the question) is how exactly do I go about creating a placeholder at https://kubernetes.io/docs (for example, I am guessing that https://github.com/kubernetes/kubernetes/blob/master/docs/admin/federation-apiserver.md gets a placeholder at https://kubernetes.io/docs/admin/federation-apiserver); where do I manipulate it, and the bigger question how exactly do I test it out?

Thanks again for the guidance.

**Comment by nikhiljindal** [comment]
k8s.io is served from https://github.com/kubernetes/kubernetes.github.io.
For example, that federation-apiserver doc you linked to is served from https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/federation-apiserver.md. 

https://github.com/kubernetes/kubernetes.github.io/blob/master/README.md has more details on how to contribute docs.

**Comment by madhusudancs** [comment]
@irfanurrehman 

> What I couldn't get sure of (and the reason, I posted the question) is how exactly do I go about creating a placeholder at https://kubernetes.io/docs (for example, I am guessing that https://github.com/kubernetes/kubernetes/blob/master/docs/admin/federation-apiserver.md gets a placeholder at https://kubernetes.io/docs/admin/federation-apiserver); 

https://github.com/kubernetes/kubernetes/blob/master/docs/admin/federation-apiserver.md and https://kubernetes.io/docs/admin/federation-apiserver are unrelated. You can create the former file manually in the Kubernetes repo to ensure that anything else won't get checked in at that path. But that's not necessary strictly.

> where do I manipulate it, 

If you want to create a doc at https://kubernetes.io/docs/admin/federation-apiserver, what you need is a file at https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/federation-apiserver.md. You can just generate this doc in the core repo using the `hack/` script and copy the generated content here.

> and the bigger question how exactly do I test it out?

This is somewhat tricky and depends on your setup.

1. We use a web tool called netlify that runs as a presubmit on the PRs in this repo. It renders the doc the same way kubernetes.io would. But it rarely works for me. Most of the times I either get a HTTP 404 or some other error.

2. My text editor has a plugin to render Github-flavored markdown of the document I am editing and I just use it to verify that things look good. I generally don't test the links or navigate. Just that one page I am editing.

3. The tool that Github uses to render their markdown is Jekyll. There is a Jekyll docker image that you can run on your machine to render kubernetes.io/docs locally. https://hub.docker.com/r/starefossen/github-pages/

**Comment by irfanurrehman** [comment]
Thanks @madhusudancs @nikhiljindal for all the useful info.

**Comment by tengqm** [comment]
Issue solved.
