### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/overview/

### ISSUE THREAD

**Issue by corpix** [kubernetes/website#28880]
Where is the `custom-columns` list? Here https://kubernetes.io/docs/reference/kubectl/overview/#custom-columns I can see nothing but an example. Where should I get an information to build custom-columns path expressions?

**Comment by sftim** [comment]
This looks like a request to add a custom columns expression reference into the Kubernetes documentation.

/sig cli
/kind feature
/priority backlog
/triage accepted

**Comment by sftim** [comment]
/reopen

We should try to add this.
