### ISSUE TITLE
Deployments: pausing and resuming

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#28884]
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pausing-and-resuming-a-deployment suggests:
```
• Get the rollout status:

kubectl get rs

The output is similar to this:

NAME               DESIRED   CURRENT   READY     AGE
nginx-2142116321   3         3         3         1m

• Pause by running the following command:

kubectl rollout pause deployment.v1.apps/nginx-deployment

The output is similar to this:

deployment.apps/nginx-deployment paused
```
Do changes, then
```
• Get the rollout status to ensure that the Deployment is updated successfully:

kubectl get rs

The output is similar to this:

NAME               DESIRED   CURRENT   READY     AGE
nginx-2142116321   3         3         3         2m
```

The output is equivalent to the previous run of `kubectl get rs`.  I do not see, how this output can confirm, that the Deployment was updated.

**Comment by chenxuc** [comment]
@dilyanpalauzov Welcome and thanks for contributing your first issue here!

This sentence does seem confusing to me. I will improve it.

/triage accepted
/kind bug
/assign
