### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/create-cluster/

### ISSUE THREAD

**Issue by Donkere-vader** [kubernetes/website#28886]
It would be nice to have a bit of text about what a cluster is, cuz I don't know what it does in kubernetes.

**Comment by jihoon-seo** [comment]
Someone might add a link to https://kubernetes.io/docs/concepts/overview/components/ in [that page](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/).

**Comment by sftim** [comment]
The [glossary shortcodes](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) let you automatically include the existing explanation of what a cluster is. That ought to help too.

**Comment by sftim** [comment]
We could also link to https://k8s.io/docs/setup/ and https://k8s.io/releases/

**Comment by chenxuc** [comment]
/unassign 
Unassign myself since @RA489 is already working on this issue. Thanks.

**Comment by mehabhalodiya** [comment]
> The [glossary shortcodes](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) let you automatically include the existing explanation of what a cluster is. That ought to help too.

@Donkere-vader you may have a look at [this](https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-cluster).
I think it will help you to understand, what the cluster is!
Thank you.
