### ISSUE TITLE
DaemonSet: kubectl delete --cascade=false

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#28890]
According to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#delete the `kubectl delete` can get a parameter `--cascade` with a value of "background", "orphan", or "foreground".

https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#updating-a-daemonset proposes to use `--cascade=false`.

**Comment by jihoon-seo** [comment]
Hello @dilyanpalauzov 

Related PRs/issues:
- #25985
> `kubectl delete --cascade=false` is now deprecated in favor of `kubectl delete --cascade=orphan`
- #27920
> warning: `--cascade=false` is deprecated (boolean value) and can be replaced with `--cascade=orphan`
- #28374
> Cascade=false is deprecated in kubectl 1.21, according to Bug #27920

So, the page https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#updating-a-daemonset should be updated.

/kind bug
/language en
/help

**Comment by jihoon-seo** [comment]
To @Dapperton-prog :
@Patil2099 has already assigned himself/herself,
and posted a PR (#28900).
