### ISSUE TITLE
Remove dup PNG files in `blog/_posts/`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#28892]
**This is a Bug Report**

**Problem:**
There exist dup PNG files in `blog/_posts/`.
(These files were added by the PR #24136 .)

In [`blog/_posts/`](https://github.com/kubernetes/website/tree/main/content/en/blog/_posts)
![image](https://user-images.githubusercontent.com/46767780/125179848-a4218d00-e22d-11eb-8d62-6834bfc208b7.png)

In [`blog/_posts/2020-09-30-writing-crl-scheduler/`](https://github.com/kubernetes/website/tree/main/content/en/blog/_posts/2020-09-30-writing-crl-scheduler)
![image](https://user-images.githubusercontent.com/46767780/125179865-c4e9e280-e22d-11eb-83f6-2e3375f8a512.png)

**Proposed Solution:**
Remove dup PNG files in `blog/_posts/`.

**Page to Update:**
The blog article https://kubernetes.io/blog/2020/12/21/writing-crl-scheduler/ should not be affected by the change this issue is suggesting.

/kind cleanup
/help

**Comment by kaushambisharma** [comment]
I'd like to work on this issue

**Comment by jihoon-seo** [comment]
To @Dapperton-prog :
@kaushambisharma has already assigned himself/herself,
and posted a PR (#28923).

**Comment by Atharva-Shinde** [comment]
its been 6 days and still no MR, should I assign this to me as I have found the duplicate pngs..I am a beginner too.

**Comment by nate-double-u** [comment]
fixed in https://github.com/kubernetes/website/pull/28923
/close
