### ISSUE TITLE
Unable to follow Ingress with NGINX task in Katacoda

### ISSUE THREAD

**Issue by iRachana06** [kubernetes/website#28897]
no matches for kind "Ingress" in version "networking.k8s.io/v1" is shown and validation upon kubectl apply is getting failed

**Comment by jihoon-seo** [comment]
Link to the related page: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

**Comment by RA489** [comment]
@iRachana06 as a workaround please try apiversion as networking.k8s.io/v1beta1

**Comment by jihoon-seo** [comment]
Maybe-related page: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/

**Comment by RA489** [comment]
@iRachana06 any update with the workaround?

**Comment by sftim** [comment]
/kind support

@iRachana06 check that the documentation you're reading matches the version you're running. See https://kubernetes.io/docs/home/supported-doc-versions/

**Comment by iRachana06** [comment]
Working locally, is fine. Locally on own minikube setup, its working fine. On the katacoda environment that is provided with the Documentation, kubectl apply command gives error.: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/
 Attaching screenshot for reference

![image](https://user-images.githubusercontent.com/68515362/125786070-8a438f33-a3d2-4fc9-a562-87aba5cbf0e3.png)

**Comment by sftim** [comment]
/retitle Unable to follow Ingress with NGINX task in Katacoda

**Comment by sftim** [comment]
/triage duplicate
First reported in #27493

**Comment by sftim** [comment]
/triage accepted
We'll focus work on issue #29204

**Comment by sftim** [comment]
Fixed by #29616
/close
