### ISSUE TITLE
Create a task page for using finalizers to control deletion

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#28909]
Relates to #28870 

## Overview

While we have a great [blog post](https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/) about using finalizers, we should formalize that in our docs. #28870 added a concept page for Finalizers. We should add on to that with a task to use them. Source material from the blog post + elsewhere. 

/assign
/triage accepted
/sig docs
/cc @sftim

**Comment by shannonxtreme** [comment]
I'm wondering what a good use case for this would be. Like, how would we structure this task? What's a scenario where this would be useful?

**Comment by sftim** [comment]
This task is useful for somebody implementing a Kubernetes extension _or_ this task is useful for a cluster operator wondering about why things aren't deleting the way they expect.

Not sure which audience to focus on. Thoughts?

/remove-lifecycle rotten

**Comment by shannonxtreme** [comment]
> This task is useful for somebody implementing a Kubernetes extension _or_ this task is useful for a cluster operator wondering about why things aren't deleting the way they expect.
> 
> Not sure which audience to focus on. Thoughts?
> 
> /remove-lifecycle rotten

I feel like the more common use case is the cluster operator, but that reads more like a troubleshooting task no? How to identify finalizers and figure out why they're there?

**Comment by sftim** [comment]
Maybe a tutorial page would be better.

**Comment by shannonxtreme** [comment]
Yeah this would work better as a tutorial focusing on a specific scenario
