### ISSUE TITLE
Redirection rules with wildcard(`*`) works differently from expectation

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#28917]
**This is a Bug Report**

**Problem:**

In [`static/_redirects`](https://github.com/kubernetes/website/blob/main/static/_redirects), 
There are some redirection rules with wildcard(`*`).

---

```
/docs/reference/generated/kubectl/kubectl/kubectl_*.md    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
/docs/reference/kubectl/kubectl/kubectl_*.md    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
```

Expectation:
- Netlify redirects https://kubernetes.io/docs/reference/generated/kubectl/kubectl/kubectl_get.md to 
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get

Reality:
- https://kubernetes.io/docs/reference/generated/kubectl/kubectl/kubectl_get.md gives `404 not found`
- Instead, Netlify redirects https://kubernetes.io/docs/reference/generated/kubectl/kubectl/kubectl_*.md (literally) to
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#:splat (literally)

---

```
/docs/user-guide/kubectl/kubectl_*/     /docs/reference/generated/kubectl/kubectl-commands#:splat 301
```

Expectation:
- Netlify redirects https://kubernetes.io/docs/user-guide/kubectl/kubectl_get/ to
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get

Reality:
- Netlify redirects https://kubernetes.io/docs/user-guide/kubectl/kubectl_get/ to
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get/ (with trailing slash)
which is not a valid anchor URL (because of the trailing slash).

---

**Proposed Solution:**

**File to Update:**
[`static/_redirects`](https://github.com/kubernetes/website/blob/main/static/_redirects)

**Comment by anubha-v-ardhan** [comment]
I would like to give this a try
/assign

**Comment by niteshseram** [comment]
@jihoon-seo how can I test these redirect things after I made the changes? Do I have to make a PR to get the netlify link to test the things?

**Comment by anubha-v-ardhan** [comment]
@niteshseram Are you working on this issue?

**Comment by niteshseram** [comment]
@anubha-v-ardhan Ya I was trying but couldn't figure out how can I test these redirects after making the changes

**Comment by anubha-v-ardhan** [comment]
@niteshseram Thanks, I will unassign myself. Please consider commenting before. It helps others to know about the progress of issue.
/unassign

**Comment by niteshseram** [comment]
> @niteshseram Thanks, I will unassign myself. Please consider commenting before. It helps others to know about the progress of issue.
> /unassign

It was my bad.

**Comment by niteshseram** [comment]
@jihoon-seo I think the problem is with the link itself.
https://kubernetes.io/docs/reference/generated/kubectl/kubectl/kubectl_get.md.
https://kubernetes.io/docs/reference/generated/kubectl/kubectl/kubectl_get.md
Here may be _get.md_ is the splat. Maybe that's why it's unable to redirect.
If I change the redirect to something like below without the .md it works fine
```
/docs/reference/generated/kubectl/kubectl/kubectl_*    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
/docs/reference/kubectl/kubectl/kubectl_*    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
```
And for this link https://kubernetes.io/docs/user-guide/kubectl/kubectl_get/, the splat is _get/_ and hence it redirects to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get/. This can be resolve if we remove the _trailing slash_ from this link https://kubernetes.io/docs/user-guide/kubectl/kubectl_get/ 
So, where are all these links present if we want to modify the link itself?

**Comment by jihoon-seo** [comment]
@niteshseram What a great research!

> how can I test these redirect things after I made the changes? Do I have to make a PR to get the netlify link to test the things?

I think so. To do tests, you should 
1. make changes on [`static/_redirects`](https://github.com/kubernetes/website/blob/main/static/_redirects) file, 
2. post a PR, and
3. test the redirection rules on the deploy preview: https://deploy-preview-xxxxx--kubernetes-io-main-staging.netlify.app/

---

And regarding your research, I suggest to make changes like these:

```diff
-/docs/reference/generated/kubectl/kubectl/kubectl_*.md    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
+/docs/reference/generated/kubectl/kubectl/kubectl_*    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
```

```diff
-/docs/reference/kubectl/kubectl/kubectl_*.md    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
+/docs/reference/kubectl/kubectl/kubectl_*    /docs/reference/generated/kubectl/kubectl-commands#:splat 301
```

```diff
-/docs/user-guide/kubectl/kubectl_*/     /docs/reference/generated/kubectl/kubectl-commands#:splat 301
+/docs/user-guide/kubectl/kubectl_*     /docs/reference/generated/kubectl/kubectl-commands#:splat 301
```

and test on the deploy preview of the PR you will post.

---

> So, where are all these links present if we want to modify the link itself?

I did some searching and found these:

content/en/blog/_posts/2016-08-00-Kubernetes-Namespaces-Use-Cases-Insights.md
```diff
-[kubectl context](/docs/user-guide/kubectl/kubectl_config_set-context/)
+[kubectl context](/docs/reference/generated/kubectl/kubectl-commands#-em-set-context-em-)
```

content/en/blog/_posts/2016-12-00-Statefulset-Run-Scale-Stateful-Applications-In-Kubernetes.md
```diff
-[kubectl create](/docs/user-guide/kubectl/kubectl_create/)
+[kubectl create](/docs/reference/generated/kubectl/kubectl-commands#create)
```

```diff
-[kubectl apply](/docs/user-guide/kubectl/kubectl_apply/)
+[kubectl apply](/docs/reference/generated/kubectl/kubectl-commands#apply)
```

**Comment by niteshseram** [comment]
@jihoon-seo I have made the PR. Let me know if I have to do some more changes or anything
