### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/storage-classes/

### ISSUE THREAD

**Issue by sheisnicola** [kubernetes/website#28924]
There is no documentation for the in-tree NFS `kubernetes.io/nfs` storage class provisioner. What parameters does it support or require, if any? Where can I find documentation for this?

**Comment by chenxuc** [comment]
@sheisnicola Welcome and thanks for your first issue here!

Someone please correct me if I'm wrong. But as this page points out `NFS doesn't provide an internal provisioner`, so there's no `kubernetes.io/nfs` storage class in Kubernetes in-tree providers. We have to use external providers for nfs. And we might not want to link to external provider as example in this page.

**Comment by chenxuc** [comment]
I found an example for nfs storageClass with [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner) provided by kubernetes-sigs GitHub organizations. I think we can add a link to that example.

/triage accepted
/assign

**Comment by sheisnicola** [comment]
Hi @chenxuc!

Yes, that was my initial reading on this particular page of documentation, but is is very ambiguous to me. I did find some documentation on the subject eventually when proceeding to read about Physical Volume definitions using the in-tree kubernetes.io/nfs class at https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs, but if anything it just confused the issue even more since the storage class is empty.

Essentially I'm trying to understand a set of Kubernetes manifests in our existing enterprise application that has been using a kubernetes.io/nfs storage class provisioner for a few years. Something in our manifest either doesn't add up, or I'm missing some documentation somewhere.

(We have a PVC pointing to a PV that mounts an NFS export, and that PV is using a storage class using kubernetes.io/nfs that points to the same NFS host and export path).

I've been trying to understand the issue from reading:

* https://github.com/kubernetes/kubernetes/tree/4ad08fa5b611826505fa2892cdce463f12d32b35/pkg/volume
* https://github.com/kubernetes/kubernetes/blob/4ad08fa5b611826505fa2892cdce463f12d32b35/pkg/volume/nfs/nfs.go#L66
* https://docker-docs.netlify.app/ee/ucp/admin/configure/use-nfs-volumes/#create-the-nfs-server
* https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner
* https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs
* https://github.com/kubernetes/kubernetes/blob/4ad08fa5b611826505fa2892cdce463f12d32b35/pkg/volume/plugins.go#L145

Should I take this to mean simply that I don't need an NFS storage class client to simply provide a PV mounting an existing NFS export, and that therefore I'm trying to look for documentation that indeed does not exist because it doesn't make sense? (A storage class is not needed for a kubernetes.io/nfs PV?)

Apologies, I think this ended up being a misunderstanding from my interpretation of the documentation if this is the case? Confirmation or any clarification would be greatly appreciate.
 
Many thanks.

**Comment by chenxuc** [comment]
@sheisnicola The storage class is used to dynamic provision storage. If you create the PV/PVC manually, it might not need the storage class to use nfs. Sorry that I'm not very familiar with this part and cannot help all your questions.
