### ISSUE TITLE
Mention container probes in https://k8s.io/docs/concepts/workloads/pods/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#28955]
**This is a Feature Request**

**What would you like to be added**
The [Pod](https://kubernetes.io/docs/concepts/workloads/pods/) concept should mention [container probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes).

**Why is this needed**

- Make sure that a reader can find “probe” in https://kubernetes.io/docs/concepts/workloads/pods/ if they search-in-page
- Give readers a clue that this container-level health checking is possible in Kubernetes

**Comments**
A brief mention and a hyperlink to https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes would be enough. Maybe try to get the keyword “health” in their too.

/language en
/kind feature
/help

**Comment by slayer321** [comment]
Hey @sftim, I will like to take up this issue.

**Comment by anubha-v-ardhan** [comment]
Thanks @slayer321 
/assign @slayer321

**Comment by slayer321** [comment]
adding [container probe](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes) in the [pod](https://kubernetes.io/docs/concepts/workloads/pods/) docs must be as a new heading or it must be the subpart of the other content?

if we are adding it as a new heading then is this format correct?

### Container probes
A Probe is a diagnostic performed periodically by the kubelet on a Container. To perform a diagnostic, the kubelet calls a Handler implemented by the container. There are three types of handlers:
- ExecAction
- TCPSocketAction
- HTTPGetAction

you can read more about it [here](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes).
