### ISSUE TITLE
Outdated Korean contents in the dev-1.21-ko.7 branch 

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#28963]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.21-ko.7 branch.

Report generated by the `./scripts/diff_l10n_branches.py ko upstream/dev-1.21-ko.6 upstream/dev-1.21-ko.7`

### 27 files to be modified 
1. [ ] M1.  `content/en/docs/concepts/architecture/cloud-controller.md`  | 1(+XS) 1(-)
1. [ ] M2.  `content/en/docs/concepts/architecture/nodes.md`  | 1(+XS) 1(-)
1. [ ] M3.  `content/en/docs/concepts/cluster-administration/logging.md`  | 5(+XS) 2(-)
1. [ ] M4.  `content/en/docs/concepts/configuration/secret.md`  | 6(+XS) 10(-)
1. [ ] M5.  `content/en/docs/concepts/extend-kubernetes/operator.md`  | 1(+XS) 2(-)
1. [ ] M6.  `content/en/docs/concepts/storage/storage-classes.md`  | 3(+XS) 3(-)
1. [ ] M7.  `content/en/docs/concepts/storage/volumes.md`  | 1(+XS) 1(-)
1. [ ] M8.  `content/en/docs/concepts/workloads/pods/pod-lifecycle.md`  | 12(+S) 2(-)
1. [ ] M9.  `content/en/docs/reference/_index.md`  | 4(+XS) 0(-)
1. [ ] M10.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 7(+XS) 1(-)
1. [ ] M11.  `content/en/docs/reference/glossary/kube-controller-manager.md`  | 1(+XS) 1(-)
1. [ ] M12.  `content/en/docs/reference/tools/_index.md`  | 2(+XS) 2(-)
1. [ ] M13.  `content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md`  | 1(+XS) 1(-)
1. [ ] M14.  `content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md`  | 2(+XS) 0(-)
1. [ ] M15.  `content/en/docs/tasks/administer-cluster/highly-available-control-plane.md`  | 1(+XS) 1(-)
1. [ ] M16.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md`  | 1(+XS) 1(-)
1. [ ] M17.  `content/en/docs/tasks/tools/install-kubectl-linux.md`  | 57(+M) 1(-)
1. [ ] M18.  `content/en/docs/tasks/tools/install-kubectl-macos.md`  | 77(+M) 1(-)
1. [ ] M19.  `content/en/docs/tasks/tools/install-kubectl-windows.md`  | 44(+M) 1(-)
1. [ ] M20.  `content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html`  | 2(+XS) 1(-)
1. [ ] M21.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html`  | 3(+XS) 1(-)
1. [ ] M22.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html`  | 3(+XS) 1(-)
1. [ ] M23.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html`  | 2(+XS) 2(-)
1. [ ] M24.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html`  | 3(+XS) 1(-)
1. [ ] M25.  `content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html`  | 3(+XS) 1(-)
1. [ ] M26.  `content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html`  | 6(+XS) 1(-)
1. [ ] **M27.**  `content/en/docs/tutorials/stateless-application/guestbook.md`  | **222(+L) 188(-)**

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.21-ko.7` branch.

For example:
```
# checkout `upstream/dev-1.21-ko.7`
...
# check what is updated in the upstream 
git diff upstream/dev-1.21-ko.6 upstream/dev-1.21-ko.7 -- content/en/docs/concepts/architecture/cloud-controller.md
# apply changes to content/ko
vi content/ko/docs/concepts/architecture/cloud-controller.md
...
# commit and push
...
# make PR to `upstream/dev-1.21-ko.7`
```

## Pages to Update

Pages in content/ko

/language ko
/help

**Comment by seokho-son** [comment]
M27. content/en/docs/tutorials/stateless-application/guestbook.md | 222(+L) 188(-)
에 변경 사항이 많아보이지만, 
대부분 들여쓰기나 개행에 대한 조정이라 큰 부담은 없을 것 같습니다. 참고하시기 바랍니다.

**Comment by ClaudiaJKang** [comment]
M13-M26 는 제가 처리해보겠습니다~

- M13-M26: @ClaudiaJKang

**Comment by seokho-son** [comment]
M27 on me !
/assign
