### ISSUE TITLE
Highlight development tools for that get feedback from running code within Kubernetes

### ISSUE THREAD

**Issue by hw-claudio** [kubernetes/website#28967]
https://k8s.io/docs/tasks/debug-application-cluster/crictl/

completely misses what docker has, and crictl hasn't.

docker commit
docker save

how to do that?

**Comment by sftim** [comment]
Within the context of **Monitoring, Logging, and Debugging**: how are the commands `docker commit` and `docker save` useful?

That explanation will help us decide if those omissions are a drawback or actually that it's OK given the scope of that page.

**Comment by hw-claudio** [comment]
for debugging it's useful to do slight modifications to containers and save the results.

If another place is better to document how to do docker commit and docker save, by all means. A path to help existing docker users navigate how to do the same things with this new set of tools is sorely missing.

**Comment by sftim** [comment]
@hw-claudio if you'd like to either:
- reshape this issue to be about new content, helping people who are used to Docker adapt to using Kubernetes
- request a specific page about how to achieve the equivalent of `docker save` and `docker commit` for &hellip; a running Pod? (I'm not sure)

then please do.
Right now it's not clear to me what improvement addresses the need you've mentioned.

/language en
/triage needs-information

**Comment by hw-claudio** [comment]
both things are useful, this is really a FAQ without an answer.

https://github.com/containerd/containerd/issues/4818
https://github.com/kubernetes/kubernetes/issues/80818
...
this is requested many times, but things just die off.

docker commit is considered an anti-pattern of course: you want to build containers from scratch from Dockerfile etc.

But then as the theory is put into practice, you get strange behavior and interactions between the K8S infrastructure and the workload running in the POD that needs to be debugged at runtime, and you want to save the state.

The group tending to the runtime operations might even not be the same group of people tending to the build process (of course, people _should_ change to devops right? But then it's again about when the tire hits the road, this is not always possible). So doing things "properly" starting from scratch from the Dockerfile  is great in the normal case, but can become a disaster at debugging time when the clock is ticking, where quick feedback and validation of attempts is key, and when the people running the workload and attempting to understand what is wrong are different from the people producing the containers. 

Just my opinion of course, but this is a fairly common missing feature I think.

Thanks

**Comment by sftim** [comment]
Maybe the question is “how do I get a shorter feedback loop but still run my code as if / actually in the target cluster”.

People use https://tilt.dev/, https://nocalhost.dev, https://squash.solo.io/, https://www.telepresence.io/, and other tools for that.

**Comment by annajung** [comment]
Hi there, [PR wrangler](https://github.com/kubernetes/website/wiki/PR-Wranglers) here for this week. 

Based on the [documentation for triaging an issue](https://kubernetes.io/docs/contribute/review/for-approvers/#triaging-an-issue), I'll close out this issue as it contains both `lifecycle/stale` and `triage/needs-information` labels.

Feel free to reopen with correct labels if it's still relevant.

/close

**Comment by guettli** [comment]
I think "how to `docker commit` in K8s?" is a FAQ and should be answered somewhere.

**Comment by sftim** [comment]
@guettli we have an issue you can use to discuss and report issues connected to the removal of dockershim: `https://github.com/kubernetes/kuberetes/issues/106917`

You can also log a new feature request, something like “document equivalent of docker commit for development on Kubernetes”. To do that, visit https://github.com/kubernetes/website/issues/new/choose

**Comment by sftim** [comment]
/reopen
/retitle Highlight development tools for that get feedback from running code within Kubernetes
/remove triage needs-information
/priority awaiting-more-evidence
/kind feature

We don't have a focus on documenting external tools (there's enough work on documenting Kubernetes itself that takes priority), but anyone who wants to work on this issue is welcome to; that's a benefit of open source.
If opening PRs, take account of [What's Allowed](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed) in the content guide.

I'm also an editor for the blog. I would welcome a vendor-neutral survey of your options for this kind of development, especially one that mentions how using `docker commit` will require extra work after the dockershim removal.
