### ISSUE TITLE
Issue with /docs/concepts/cluster-administration/out-of-resource/

### ISSUE THREAD

**Issue by bytesandwich** [kubernetes/website#2896]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The last section of [Configuring Out Of Resource Handling](https://kubernetes.io/docs/concepts/cluster-administration/out-of-resource/#how-kubelet-ranks-pods-for-eviction-in-response-to-inode-exhaustion), "How kubelet ranks pods for eviction in response to inode exhaustion" mentions
https://github.com/google/cadvisor/issues/1422 as future work, but this issue is closed. Is the doc up to date?

**Proposed Solution:**

@dashpole @derekwaynecarr is this entire page up to date regarding that issue?

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/out-of-resource/

**Comment by zacharysarah** [comment]
Bumping for tech review.
