### ISSUE TITLE
Object Names and IDs referring to wrong RFC?

### ISSUE THREAD

**Issue by tachylatus** [kubernetes/website#28969]
I am no expert on RFCs, but I could not find any precise definitions of DNS subdomains or labels in the linked to memo RFC 1123.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/
https://datatracker.ietf.org/doc/html/rfc1123

After a quick internet search, I found RFC 1035, which contains a formal definition of the name syntax in BNF, on page 8. 

https://datatracker.ietf.org/doc/html/rfc1035#page-8

There are subtle differences between the naming rules in the Kubernetes doc and the RFC spec, with RFC 1035 allowing uppercase characters (no significance attached to the case) and disallowing a digit as the first character.

Still, I suggest updating the Kubernetes doc to refer to RFC 1035 instead of RFC 1123.

**Comment by warmchang** [comment]
The long story(discuss): https://github.com/kubernetes/kubernetes/issues/199
And the final identifiers: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md#definitions
