### ISSUE TITLE
Issue with k8s.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/

### ISSUE THREAD

**Issue by bbarnes52-zz** [kubernetes/website#28968]
There appears to be some incorrect statements in [CA Reusage and Conflicts sections](https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/#ca-reusage-and-conflicts)

```
If both --client-ca-file and --requestheader-client-ca-file are provided, then the request first checks the --requestheader-client-ca-file CA and then the --client-ca-file. Normally, different CAs, either root CAs or intermediate CAs, are used for each of these options; regular client requests match against --client-ca-file, while aggregation requests match against --requestheader-client-ca-file. However, if both use the same CA, then client requests that normally would pass via --client-ca-file will fail, because the CA will match the CA in --requestheader-client-ca-file, but the common name CN= will not match one of the acceptable common names in --requestheader-allowed-names. This can cause your kubelets and other control plane components, as well as end-users, to be unable to authenticate to the Kubernetes apiserver.

For this reason, use different CA certs for the --client-ca-file option - to authorize control plane components and end-users - and the --requestheader-client-ca-file option - to authorize aggregation apiserver requests.
```

I have observed the following behavior: if the CN does match one of the acceptable common names in `--requestheader-allowed-names` and both `--client-ca-file` and `--requestheader-client-ca-file` are provided, _the apiserver falls back to `--client-ca-file` auth_. This statement is incorrect: `However, if both use the same CA, then client requests that normally would pass via --client-ca-file will fail`. I verified this behavior on 1.20.1.

Consequently, there does not seem to be any justification for recommending different CAs for --client-ca-file and --requestheader-client-ca-file.

**Comment by enj** [comment]
/remove-lifecycle rotten
/triage accepted

There is quite a lot of nuance in how these authenticators work together, and we should definitely continue to recommend the use of different CAs for these purposes.

For example, the `CN` check for the request header authenticator is not required.

If you use the same CA, there are situations where an aggregated API server can get confused about the incoming identity (the specifics are eluding me right now because it has been a while).

The advice in the docs is correct, but the reasoning will require some effort to explain clearly.

**Comment by bbarnes52** [comment]
I do not disagree with recommending the use of different CAs per-se. I filed this issue because the current documentation makes assertions that are verifiably incorrect.

**Comment by sftim** [comment]
/kind bug
/language en

/priority backlog

(but, folks, please feel very welcome to work on this one - the docs for APIService need some love)
