### ISSUE TITLE
Issue with /docs/api-reference/v1/definitions/

### ISSUE THREAD

**Issue by bytesandwich** [kubernetes/website#2897]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
v1.ResourceQuotaScope has a declaration and a use but no definition
in https://kubernetes.io/docs/api-reference/v1/definitions/

**Proposed Solution:**
Regenerate the definition.

**Page to Update:**
https://kubernetes.io/docs/api-reference/v1/definitions/

**Comment by zacharysarah** [comment]
@bytesandwich Thanks for opening this issue. I'm not seeing an API resource for ResourceQuotaScope&mdash;only an entry for [ResourceQuote](https://kubernetes.io/docs/api-reference/v1.7/#resourcequota-v1-core). Can you clarify whether the bug you're seeing still exists? Thanks in advance.

**Comment by tengqm** [comment]
Cannot see the reported entry either. Closing this.
