### ISSUE TITLE
Kubernetes Scheduler: use distinct names for Scheduling Policies and Scheduling Policies

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#28977]
https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/#kube-scheduler-implementation says:
```
There are two supported ways to configure the filtering and scoring behavior of the scheduler:
1. Scheduling Policies allow you to configure to...
2. Scheduling Policies allow you to configure to...
```

Where _Scheduling Policies_ are hyper links, pointing to different locations.

If there are two ways to achieve something, the names of the ways must be distinct.

**Comment by niteshseram** [comment]
Hi @dilyanpalauzov, I think you misread the paragraph. It is written as _**Scheduling Policies**_ and _**Scheduling Profiles**_.

**Comment by dilyanpalauzov** [comment]
I agree.
