### ISSUE TITLE
Issue with k8s.io/docs/concepts/scheduling-eviction/taint-and-toleration/

### ISSUE THREAD

**Issue by dannydombrowski** [kubernetes/website#28982]
Broken link in the section https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition  

"node conditions" is pointing to https://kubernetes.io/docs/concepts/scheduling-eviction/pod-eviction#node-conditions which returns a 404.

**Comment by jihoon-seo** [comment]
This issue will be resolved when the PR #28797 is merged.
/kind bug
/kind cleanup

**Comment by jihoon-seo** [comment]
This issue was resolved by the PR #28797.
/close
