### ISSUE TITLE
StatefulSets

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#28999]
Document's section: [https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage)

Currenty it says:
   **Kubernetes creates one PersistentVolume for each VolumeClaimTemplate**

That is not wrong, but not exact. What about replacing it by something like this:
   **Per each StatefulSet triggered pod Kubernetes creates a PersistentVolumeClaim object for each VolumeClaimTemplates entry defined in the StatefulSet object**

/language en

**Comment by Kartik494** [comment]
I would like to work on this

/assign

**Comment by Kartik494** [comment]
Hi @antaloala i have raised a [PR](https://github.com/kubernetes/website/pull/29012) this.

**Comment by antaloala** [comment]
Thanks @Kartik494 ;-)
