### ISSUE TITLE
Pod 安全策略

### ISSUE THREAD

**Issue by lemonit-eric-mao** [kubernetes/website#29004]
我看到此文章当中提到了https://kubernetes.io/zh/docs/concepts/policy/pod-security-policy/

FEATURE STATE: Kubernetes v1.21 [deprecated]
PodSecurityPolicy 在 Kubernetes v1.21 版本中被弃用，将在 v1.25 中删除。

Pod 安全策略使得对 Pod 创建和更新进行细粒度的权限控制成为可能。

但是这里并没有明确说明删除的原因与替代的方案

**Comment by chenxuc** [comment]
@lemonit-eric-mao Welcome and thank you for your first issue here!
The Chinese page you mentioned is out of sync with [English version](https://kubernetes.io/docs/concepts/policy/pod-security-policy/). As the English version page points out, you can refer to [this blog](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) for more information for how to handle the deprecated feature.

The Chinese page will be updated with the new information later.

/triage accepted
/kind feature
/assign

**Comment by lemonit-eric-mao** [comment]
@chenxuc  I see. Thank you

**Comment by lemonit-eric-mao** [comment]
@chenxuc I see. Thank you
