### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-macos/

### ISSUE THREAD

**Issue by AnandAseem** [kubernetes/website#29000]
Where's complete uninstall instructions for mac - for kubectl and minikube?

**Comment by jihoon-seo** [comment]
How to install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/

### If you installed kubectl binary with curl on macOS

```shell
sudo rm -rvf /usr/local/bin/kubectl
```

### If you installed kubectl with [Homebrew](https://docs.brew.sh/Manpage#uninstall-formula) on macOS

```shell
brew uninstall kubectl
```

or

```shell
brew uninstall kubernetes-cli
```

### If you installed kubectl with [Macports](https://guide.macports.org/#using.port.uninstall) on macOS

```shell
sudo port uninstall kubectl
```

---

How to install minikube: https://minikube.sigs.k8s.io/docs/start/

### If you installed minikube binary with curl on macOS

```shell
sudo rm -rvf /usr/local/bin/minikube
```

### If you installed minikube with [Homebrew](https://docs.brew.sh/Manpage#uninstall-formula) on macOS

```shell
brew uninstall minikube
```
