### ISSUE TITLE
Potentially outdated documentation mentioning `PodSecurityPolicy`

### ISSUE THREAD

**Issue by su225** [kubernetes/website#29010]
**Page to Update:**
https://kubernetes.io/docs/tutorials/clusters/apparmor/#restricting-profiles-with-the-podsecuritypolicy

Kubernetes is deprecating `PodSecurityPolicy` as mentioned [here](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/). But in the page linked there is not even a mention of PSP being deprecated. Either that section should be removed or a deprecation notice needs to be added so that the users wouldn't end following those steps if they are on higher versions.

**Comment by jihoon-seo** [comment]
For anyone's information:

In https://kubernetes.io/docs/concepts/policy/pod-security-policy/

> FEATURE STATE: Kubernetes v1.21 [deprecated]
> 
> PodSecurityPolicy is deprecated as of Kubernetes v1.21, and will be removed in v1.25. For more information on the deprecation, see [PodSecurityPolicy Deprecation: Past, Present, and Future](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/).

> Recommended Practice
PodSecurityPolicy is being replaced by a new, simplified `PodSecurity` admission controller. For more details on this change, see [PodSecurityPolicy Deprecation: Past, Present, and Future](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/). Follow these guidelines to simplify migration from PodSecurityPolicy to the new admission controller:

/triage accepted
/language en

**Comment by Shubham82** [comment]
/assign
I would like to work on this.

**Comment by Shubham82** [comment]
fixed it here: #29014
