### ISSUE TITLE
[ko] Wrong Korean translations

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#29027]
**This is a Bug Report**

**Problem:**
- `PodCondition` / `pod condition` 이 `파드(의) 조건` 으로 번역된 경우가 있음.
- `node condition` 이 `노드(의) 조건` 으로 번역된 경우가 있음.

**Proposed Solution:**
Replace:
- `파드 조건` -> `파드 컨디션`
- `파드의 조건` -> `파드의 컨디션`
- `노드 조건` -> `노드 컨디션`
- `노드의 조건` -> `노드의 컨디션`
- `조건` -> `컨디션` (문맥을 잘 파악하면서 선택적으로 replace 해야 함)

**Page to Update:**
- https://kubernetes.io/ko/docs/concepts/workloads/pods/pod-lifecycle/
- https://kubernetes.io/ko/docs/tutorials/stateful-application/basic-stateful-set/
- https://kubernetes.io/ko/docs/concepts/scheduling-eviction/taint-and-toleration/
- ...

/language ko

**Comment by jihoon-seo** [comment]
@anubha-v-ardhan I think that someone who is a Korean native speaker is appropriate for this issue.

**Comment by anubha-v-ardhan** [comment]
yup, sorry for inconvenience 
/unassign

**Comment by jayesh-srivastava** [comment]
Hi @jihoon-seo I have understood the issue and I would like to work on it. Although I am not a native Korean speaker, I want to contribute to this issue since it is pending for such a long time.

**Comment by jihoon-seo** [comment]
@jayesh-srivastava Okay, please open a PR 😊
/assign @jayesh-srivastava

**Comment by jayesh-srivastava** [comment]
Hey @jihoon-seo are there more pages to update or the ones mentioned in the issue?

**Comment by jihoon-seo** [comment]
@jayesh-srivastava After my doing some searching, it seems that there is no more pages to be updated. 😊

**Comment by jayesh-srivastava** [comment]
Hey @jihoon-seo, I have made the changes required. Please review. There might be some stuff which I have missed, will be happy to make the changes again.

**Comment by jihoon-seo** [comment]
PR #29732 과 #30287 이 후속 조치가 되지 않고 있어서
제가 하겠습니다~
/unassign jayesh-srivastava
/unassign suhhee1011
/assign

**Comment by jihoon-seo** [comment]
- This issue was resolved by the PR #31365.
