### ISSUE TITLE
Improvement for k8s.io/docs/tasks/job/automated-tasks-with-cron-jobs/

### ISSUE THREAD

**Issue by ryanmarsh** [kubernetes/website#29035]
I had to use batch/v1beta1 for a cronjob this should be updated in the docs as well.
kubectl version         
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.10-gke.1600",

**Comment by Kartik494** [comment]
I have used it with apiVersion `apiVersion: batch/v1` and seems like it is  running fine
i also used kubectl version v1.21
