### ISSUE TITLE
DNS name for pods / services can not start with an alphanumeric character

### ISSUE THREAD

**Issue by gOATiful** [kubernetes/website#29057]
**This is a Bug Report**

**Problem:**
Pod / Service names can not start with an alphanumeric character in kubernetes, but should be possible according to RFC1123

**Proposed Solution:**
Change documentation in sections `DNS Subdomain Names` and `DNS Label Names` to: 
`* start with an alphabetic character`

or  

change kubernetes name check to use the specification in RFC1123.

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names

Kubernetes Version:
1.19.11

**Comment by tengqm** [comment]
Kubernetes does not strictly follow the RFC.

**Comment by gOATiful** [comment]
this might be true, but the documentation says otherwise.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
eg.
`Most resource types require a name that can be used as a DNS subdomain name as defined in RFC 1123.`

**Comment by tengqm** [comment]
According to the validation logic, starting with alphanumeric characters should be okay. Can you paste the error message you have got?

**Comment by tengqm** [comment]
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L177-L217

**Comment by bhumijgupta** [comment]
@tengqm I tried locally, and getting this error
![image](https://user-images.githubusercontent.com/30751793/126888918-1f7f4100-fad2-49ea-aa03-3910b085a7f3.png)

**Comment by tengqm** [comment]
@bhumijgupta Just double checked the validation logic for core v1 Service. Its name must be a RFC1035 label rather than a RFC1123 label. This is something we need to fix in the docs.
Related code: https://github.com/kubernetes/kubernetes/blob/47e1df8f4e86af1904ec9b3ecf427e1f1178be6e/staging/src/k8s.io/apimachinery/pkg/api/validation/generic.go#L53
