### ISSUE TITLE
Update deprecated kubectl flag delete-local-data in kubeadm docs

### ISSUE THREAD

**Issue by xinydev** [kubernetes/website#29058]
**This is a Bug Report**

**Problem:**

https://github.com/kubernetes/website/blob/main/content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md#remove-the-node

```shell
kubectl drain <node name> --delete-local-data --force --ignore-daemonsets
```
Flag --delete-local-data has been deprecated, This option is deprecated and will be deleted. Use --delete-emptydir-data.

I don’t know if it’s a good time to update this flag . If so, I can help update it.

**Proposed Solution:**

Update to 
```shell
kubectl drain <node name> --delete-emptydir-data  --force --ignore-daemonsets
```

**Page to Update:**
https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tear-down

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#remove-the-node

https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#%E3%83%8E%E3%83%BC%E3%83%89%E3%81%AE%E5%89%8A%E9%99%A4

https://kubernetes.io/fr/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tear-down

https://kubernetes.io/id/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#menghapus-node

/sig cluster-lifecycle

**Comment by xinydev** [comment]
cc @neolit123

**Comment by neolit123** [comment]
> Flag --delete-local-data has been deprecated, This option is deprecated and will be deleted. Use --delete-emptydir-data.
> I don’t know if it’s a good time to update this flag . If so, I can help update it.

i see the discussion / PR here:
https://github.com/kubernetes/kubernetes/issues/80228
https://github.com/kubernetes/kubernetes/pull/95076

using `--delete-emptydir-data` in the kubeadm docs makes sense.

/triage accepted
/help
