### ISSUE TITLE
Update Blog group list of groups in K8s groups.yaml file

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#29065]
**This is a Feature Request**

**What would you like to be added**

We should update the Blog group in the https://github.com/kubernetes/k8s.io/blob/main/groups/groups.yaml file.

**Why is this needed**

https://github.com/kubernetes/k8s.io/blob/main/groups/groups.yaml seems to be out of date -- there are some members in the Blog group that may no longer be active, and there are new folks that aren't represented.

**Comment by sftim** [comment]
@nate-double-u - or anyone - would you be willing to ping existing members there and see what level of involvement they're happy to have?

**Comment by vonguard** [comment]
I'm still in.

**Comment by nate-double-u** [comment]
I've pinged the list, only one person has responded. I suggest that we add who we need/want, and if someone feels they are getting too much email, they can request to be removed.

That said, who should be added to this list?

**Comment by sftim** [comment]
/remove-lifecycle rotten
We should do this

**Comment by nate-double-u** [comment]
Just a note, commit [37c96cf](https://github.com/kubernetes/k8s.io/commit/37c96cfced626166b1541a2b1926e9a6e49a6863#diff-9470e73f24dec81b0a2a25daf2a7ab19b5a9774ad57a80ef24c09e7ef606301b) moved this info into the [/groups/sig-docs/groups.yaml](https://github.com/kubernetes/k8s.io/blob/main/groups/sig-docs/groups.yaml) file.
