### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/expose-interactive/

### ISSUE THREAD

**Issue by huyz** [kubernetes/website#2907]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Step 1 of "Kubernetes Bootcamp - Module 4" is confusing.  I'm left more confused than when I started.

**Proposed Solution:**

Step 1 in the tutorial needs a lot more explanation:

- what's a cluster IP?  who can see the the cluster IP?

- what's an external IP? who can see the external IP?  The tutorial says external IP is "(the IP of the Node)"; why then does the output say "&lt;nodes&gt;" instead of just listing an IP address?  What does "&lt;nodes&gt;" mean?  does that mean a service has multiple IP addresses and how does that make sense?

- in the beginning of the tutorial, the service was exposed as port 8080.  So then why are we "curl"ing on port "$NODE_PORT" which is different?  The text even says "Now we can test that the app is exposed outside of the cluster using curl, the IP of the Node and the externally exposed port". So which port is exposed: 8080 or $NODE_PORT?

- what is "host01"? where does that come from?  why can't I curl either the cluster IP or the external IP of the service? Is either supposed to work?

- And the page "Using a service to expose your app" doesn't help to clarify any of these issues.  The page uses IP addresses 10.10.10.* and 10.10.9.* but this tutorial uses 10.0.0.* and 172.18.0.*.  And the diagrams on the page aren't labeled "cluster IP", "external IP", or "node IP".  So it's impossible to see what matches up between this tutorial and the page.

**Page to Update:**

Both:

https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/

and

https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-interactive/

**Comment by zacharysarah** [comment]
@huyz Thanks for opening this issue, and for the clarity of your observations. This looks like more of a feature request than a bug report _per se_, so I updated the original description to reflect that. I'm assigning the default priority for docs issues.

**Comment by tengqm** [comment]
Closing this. Please feel free to reopen it if kubernetes#3103 hasn't solved the issue.
