### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/encrypt-data - command provides invalid base64 string

### ISSUE THREAD

**Issue by matteaston** [kubernetes/website#29083]
Under the [Encrypting your data](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#encrypting-your-data) section, the provided command to generate a 32 byte random key and then base64 encode it does not work. This looks like it is due to a newline character being included in the base64 encoded string - when this is used in the 'EncryptionConfiguration' file then the api server returns an error like:

`Error: error while parsing encryption provider configuration file "[PathToEncryptionConfigurationFile]": error while parsing file: resources[0].providers[0].aescbc.keys[0].secret: Invalid value: "REDACTED": secrets must be base64 encoded`

Suggestion to fix - add the base64 line wrap argument to generate a compliant string, e.g.

`head -c 32 /dev/urandom | base64 -w0`

**Comment by chenxuc** [comment]
@matteaston I tried the original command but kube-apiserver seems starts normally. Where do you see the `Error: error while parsing encryption provider configuration file...` error message, is it in the kube-apiserver's log during start?
