### ISSUE TITLE
Improvement for k8s.io/docs/concepts/extend-kubernetes/service-catalog/

### ISSUE THREAD

**Issue by hollander-cegeka** [kubernetes/website#29084]
Where does one find the value of key topic?

**Comment by sftim** [comment]
I think
/kind support

I wasn't sure what question you're asking @hollander-cegeka

**Comment by Kartik494** [comment]
@hollander-cegeka could you give details for what value you are referencing here?

**Comment by hollander-cegeka** [comment]
My question is about this snippet:

env:
          - name: "TOPIC"
            valueFrom:
                secretKeyRef:
                   name: provider-queue-credentials
                   key: topic
                   
If I understand this correctly:The name of secretKeyRef (provider-queue-credentials) is the name of a ServiceBinding (not a Secret) and the key of secretKeyRef is a key defined within a Secret that is defined anywhere in another manifest.

**Comment by Kartik494** [comment]
if i understood it correctly you want to add  a use case  example for getting  the `TOPIC` env value i.e from where this key value comes from?

**Comment by hollander-cegeka** [comment]
I suspect that this sentence is not correct:
_In this example, the messaging queue topic name is mapped from a **secret** named provider-queue-credentials with a key named topic to the environment variable TOPIC._

I believe that this should be:
_In this example, the messaging queue topic name is mapped from a **servicebinding** named provider-queue-credentials with a key named topic to the environment variable TOPIC._

This still does not explain how the key of the secret can be derived, but that is described in my previous comment.
