### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by micmac** [kubernetes/website#2908]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Section 3 only states that you need one pod network. It doesn't go into details about what a pod network is, which is fine. However, at least some of the configurations linked don't work as is (tried romana and calico unsuccessfully, canal works out of the box)

**Proposed Solution:**
Mention at least one pod network config that works out of the box - maybe with its caveats - so that the document is indeed a quick start.

**Page to Update:**
http://kubernetes.io/docs/getting-started-guides/kubeadm/

# kubeadm version
kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by caseydavenport** [comment]
@micmac each of the linked addons you mention above should work out of the box.  I notice you're using kubeadm v1.6.0 alpha which may not be stable / compatible yet with the stable add-on manifests.

If you haven't already, I'd recommend raising any compatibility issues you've seen with the respective projects.

As for the kubeadm getting started guide, I don't think the right solution is to enumerate add-ons again in that doc.  The [add-ons page](https://kubernetes.io/docs/admin/addons/) is meant to be the source of truth for supported CNI add-ons.

**Comment by micmac** [comment]
Thanks, I'll investigate further why it doesn't work for me. As for using kubeadm 1.6.0 alpha, that's what I get if I follow the document, so I assumed it should work with the steps written there.

I did not propose enumerating add-ons again, but as the document is now, it's not a "quick", and for someone that's not familiar with Kubernetes, may not even be a "start".

**Comment by zacharysarah** [comment]
Bumping for technical review about whether the docs need updates specific to kubeadm.

/cc @caseydavenport 👋

**Comment by caseydavenport** [comment]
@micmac have you had a chance to try again with a stable version of kubeadm and corresponding add-on?

@zacharysarah I think the kubeadm docs are doing what they are intended to do, which is direct users at a list of appropriate network plugin add-ons (in this case, Calico was chosen).

Perhaps the add-ons page needs to be a table with a column for "Compatible with kubeadm" so users can feel more confident about selecting an add-on and expecting it to work?  I think all of the add-ons would tick that box though.

**Comment by tengqm** [comment]
Can we close this?
