### ISSUE TITLE
The PrepareNode.ps1 script disappeared after the last changes

### ISSUE THREAD

**Issue by eglookz** [kubernetes/website#29097]
Please change the link at https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#install-wins-kubelet-and-kubeadm ("Adding Windows nodes" page):
https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1

with the new one: 
https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/kubeadm/scripts/PrepareNode.ps1

**Comment by chenxuc** [comment]
@eglookz Welcome and thanks for the first issue here!
I will look into this issue. 
/assign

**Comment by neolit123** [comment]
Instead you can request a new release in the sig windows tools repo, by logging an issue there.
Linking to the master branch there is not a good idea.

/sig windows

**Comment by neolit123** [comment]
Also what problems are you seeing?

**Comment by chenxuc** [comment]
The problem is that the link `https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/PrepareNode.ps1` is dead. We need to replace it with the link in raw.githubusercontent.com.
