### ISSUE TITLE
kube-apiserver: Term replicationcontrollers is deprecated 

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes/website#29101]
In the `component tools/kube-apiserver` I notice that there's the term `replicationcontrollers` which was deprecated.

It's better to change the term `replicationcontrollers` to `Deployments` (for example).

Ref:
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

/sig docs
/good-first-issue

**Comment by sftim** [comment]
Caution, though: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ is generated documentation.

See https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/

**Comment by yuswift** [comment]
I'm not sure if this page refers to https://github.com/kubernetes/kubernetes/blob/584658a17d958f0b663cb39dec1907cbba641300/cmd/kube-apiserver/app/server.go#L98
If so, I think we need to open a pr for Kubernetes, then we can update the docs.

**Comment by mcbenjemaa** [comment]
@yuswift  yes and then
you should use 
https://github.com/kubernetes-sigs/reference-docs

to generate the component docs

**Comment by yuswift** [comment]
There are lots of codes related to `replicationcontroller`. IMO, if we just update the two reference codes, the Kubernetes upstream will not approve the pr cause there still remains a lot of codes. I guess we need to wait for the community to deprecate the `replicationcontroller` officially, then the page will be updated.
https://github.com/kubernetes/kubernetes/search?q=replicationcontrollers&type=code

**Comment by towfeeqfayaz11** [comment]
Hi Team,
This is my first time exposure to open source.
Apologies if I am writing in the wrong section!
I want to contribute to this issue. Would appreciate the guidance from fellow members.
Regards
Towfeeq

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/29101#issuecomment-886659467 is right

Does anyone want help updating the Kubernetes source code?
/remove-good-first-issue

**Comment by sftim** [comment]
The only mention of replicationcontrollers references a specific watch cache functionality. It might or might not be out of date.

I'm OK with leaving this auto-closed.
