### ISSUE TITLE
Feedback on grammar in Service concept page

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29107]
The first sentence https://kubernetes.io/docs/concepts/services-networking/service/:
> An abstract way to expose an application running on a set of Pods as a network service. 

has no verb.  Moreover, describing the term Service by using the term “network service” is not good.

**Comment by sftim** [comment]
How about this phrase (adapted from one useselsewhere on the site):
> In Kubernetes, a Service lets you expose an application running in Pods to be reachable from outside your cluster.

?

**Comment by dilyanpalauzov** [comment]
This is not the only purpose of the Service.  The Service can be used to distribute internal load between Pods.

**Comment by sftim** [comment]
That's a good point! Let's aim to capture that detail too. Services can be about exposing a workload, but they can also be about discovery.

**Comment by sftim** [comment]
/retitle Feedback on grammar in Service concept page
