### ISSUE TITLE
Wrong output of 'id' command in "Configure a Security Context for a Pod or Container"

### ISSUE THREAD

**Issue by xiaofhe** [kubernetes/website#29108]
1. Original text:
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
Chart: Set the security context for a Pod
Pod's yaml file is liste below : 

apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    **runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000**

Run the following command in the POD:
$ id
uid=1000 gid=3000 **groups=2000**

2.
I have tried in kubernetes v1.20, the output is as below. 
groups=3000 is missing in the current document. i think it should be corrected.

$ id
uid=1000 gid=3000 groups=**3000,2000**

**Comment by yuswift** [comment]
> 1. Original text:
>    https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
>    Chart: Set the security context for a Pod
>    Pod's yaml file is liste below :
> 
> apiVersion: v1
> kind: Pod
> metadata:
> name: security-context-demo
> spec:
> securityContext:
> **runAsUser: 1000 runAsGroup: 3000 fsGroup: 2000**
> 
> Run the following command in the POD:
> $ id
> uid=1000 gid=3000 **groups=2000**
> 
> 
> I have tried in kubernetes v1.20, the output is as below.
> groups=3000 is missing in the current document. i think it should be corrected.
> 
> $ id
> uid=1000 gid=3000 groups=**3000,2000**

Hi, I tried to use v1.19.8, here is the output.
```
/ $ id
uid=1000 gid=3000 groups=2000
```

**Comment by xiaofhe** [comment]
Does the different behaviour come from different OS release or different K8S  release ?
my OS is CentOS Linux release 7.9.2009 
thanks

**Comment by yuswift** [comment]
> Does the different behaviour come from different OS release or different K8S release ?
> my OS is CentOS Linux release 7.9.2009
> thanks

I tested it with ubuntu 16
