### ISSUE TITLE
Incorrect runtime-config parameters in 1.22 API removal blog post

### ISSUE THREAD

**Issue by tsndqst** [kubernetes/website#29117]
**This is a Bug Report**

**Problem:**
Incorrect runtime-config parameters in 1.22 API removal blog post

**Proposed Solution:**
In the [Rehearse for the upgrade](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#rehearse-for-the-upgrade) section, the runtime-config parameters should look like this:
```
--runtime-config=admissionregistration.k8s.io/v1beta1=false,apiextensions.k8s.io/v1beta1=false,apiregistration.k8s.io/v1beta1=false,authentication.k8s.io/v1beta1=false,authorization.k8s.io/v1beta1=false,certificates.k8s.io/v1beta1=false,coordination.k8s.io/v1beta1=false,extensions/v1beta1/ingresses=false,networking.k8s.io/v1beta1=false
```
`authorization.k9s.io/v1` should be `authorization.k8s.io/v1beta1`
`certificates.k8s.io/v1beta` should be `certificates.k8s.io/v1beta1`

**Page to Update:**
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

**Comment by sftim** [comment]
Oops.

/area blog
/priority important-soon
/triage accepted

Thanks for reporting this @tsndqst

**Comment by sftim** [comment]
Fixed
/close
