### ISSUE TITLE
TLS bootstrapping: it has an ability to…

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29139]
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/#token-authentication-file says:

> kube-apiserver has AN ability to accept tokens as authentication. 

My subjective intuition proposes a better wording:

> kube-apiserver has THE ability to accept tokens as authentication.

**Comment by yuswift** [comment]
Thanks. Could you find more wordings and open a pr for the repo?
/help
/good-first-issue

**Comment by dilyanpalauzov** [comment]
I am not going to do anything more, apart from saying that this wording is suboptimal.

**Comment by sftim** [comment]
/remove-good-first-issue
(good-first-issue is best added when there is a volunteer to help shepherd new contributors). Still merits /help

/language en
/priority backlog
/triage accepted

**Comment by sandipanpanda** [comment]
I want to work on this. Can you assign me?

**Comment by sftim** [comment]
SIG Docs policy is that anyone who wants to can open a pull request for any issue. If someone has said they plan to work on something, and you also want to work on it, it's friendly to get in touch with them first.

If two valid PRs are open for the same issue (it does happen), usually we merge the oldest one and close the other one.

**Comment by yuswift** [comment]
> I want to work on this. Can you assign me?

if you wat to work on this, you just need to leave a comment "/assign".

**Comment by sftim** [comment]
Fixed in #29172 I think
/close
