### ISSUE TITLE
TLS error accessing predicted URL of archived docs

### ISSUE THREAD

**Issue by tpepper** [kubernetes/website#29132]
**This is a Bug Report**

**Problem:**

If I manually go to a page such as https://v1-21.docs.kubernetes.io/docs/home/, having observed the versioned url scheme and knowing 1.21 is the current released version and I presuming it should give a valid url, I get a "Privacy error" from my browser:

<details>
  <summary> NET::ERR_CERT_COMMON_NAME_INVALID</summary>
  
Subject: *.netlify.app

Issuer: DigiCert TLS Hybrid ECC SHA384 2020 CA1

Expires on: Mar 1, 2022

Current date: Jul 27, 2021

PEM encoded chain:
-----BEGIN CERTIFICATE-----
MIIE7jCCBHWgAwIBAgIQBe4RvY3JaZ7c1/TCSJxxgDAKBggqhkjOPQQDAzBWMQsw
CQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTAwLgYDVQQDEydEaWdp
Q2VydCBUTFMgSHlicmlkIEVDQyBTSEEzODQgMjAyMCBDQTEwHhcNMjEwMzA5MDAw
MDAwWhcNMjIwMzAxMjM1OTU5WjBpMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2Fs
aWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEVMBMGA1UEChMMTmV0bGlm
eSwgSW5jMRYwFAYDVQQDDA0qLm5ldGxpZnkuYXBwMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEXGrFAeMmnjc95Jka/BzvWg95op7l/AC5y2LkGg2PaGxzlmelwkqE
UR3i0JMiwxXYB8okgzaVnvy6OtwzqNjUXKOCAxAwggMMMB8GA1UdIwQYMBaAFAq8
CCkXjKU5bXoOzjPHLrPt+8N6MB0GA1UdDgQWBBSx9WtLJkh5if1n9Y3dDLcsW0PS
LzAlBgNVHREEHjAcgg0qLm5ldGxpZnkuYXBwggtuZXRsaWZ5LmFwcDAOBgNVHQ8B
Af8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGXBgNVHR8E
gY8wgYwwRKBCoECGPmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRM
U0h5YnJpZEVDQ1NIQTM4NDIwMjBDQTEuY3JsMESgQqBAhj5odHRwOi8vY3JsNC5k
aWdpY2VydC5jb20vRGlnaUNlcnRUTFNIeWJyaWRFQ0NTSEEzODQyMDIwQ0ExLmNy
bDA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3
LmRpZ2ljZXJ0LmNvbS9DUFMwgYMGCCsGAQUFBwEBBHcwdTAkBggrBgEFBQcwAYYY
aHR0cDovL29jc3AuZGlnaWNlcnQuY29tME0GCCsGAQUFBzAChkFodHRwOi8vY2Fj
ZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUTFNIeWJyaWRFQ0NTSEEzODQyMDIw
Q0ExLmNydDAMBgNVHRMBAf8EAjAAMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYA
RqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcAAAF4GA6C+wAABAMARzBF
AiEAgVelh8/yz0qqQUCVFe2kH37Iopq6wDbOpVEOwwre1g4CIDJ4mblNEwERFKjk
1B5k8B/baSZNKu8lhNFpXi9hG/lDAHYAIkVFB1lVJFaWP6Ev8fdthuAjJmOtwEt/
XcaDXG7iDwIAAAF4GA6DDwAABAMARzBFAiEAjQbA/3wPYzeu4+ERAgGQsUwAbTUV
m795hYpcg4lnjloCICia5Sw3kK5/nFn2w5RFV+dNdWgXQ93RBSffv2iKQBEsMAoG
CCqGSM49BAMDA2cAMGQCMEyZAqzBsqUos7UHsCHxtpi4XuxW/XLp6zgXLnZuiqKj
yL3L+vRIft1I8BnVgnc57gIwLe6agLjkLOaugHAAFZjgHNgSL4K8tFMtbFcjQPm9
PQBb73IjJgvi8xlugLMu0vkO
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEQzCCAyugAwIBAgIQCidf5wTW7ssj1c1bSxpOBDANBgkqhkiG9w0BAQwFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0yMDA5MjMwMDAwMDBaFw0zMDA5MjIyMzU5NTlaMFYxCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxMDAuBgNVBAMTJ0RpZ2lDZXJ0IFRMUyBI
eWJyaWQgRUNDIFNIQTM4NCAyMDIwIENBMTB2MBAGByqGSM49AgEGBSuBBAAiA2IA
BMEbxppbmNmkKaDp1AS12+umsmxVwP/tmMZJLwYnUcu/cMEFesOxnYeJuq20ExfJ
qLSDyLiQ0cx0NTY8g3KwtdD3ImnI8YDEe0CPz2iHJlw5ifFNkU3aiYvkA8ND5b8v
c6OCAa4wggGqMB0GA1UdDgQWBBQKvAgpF4ylOW16Ds4zxy6z7fvDejAfBgNVHSME
GDAWgBQD3lA1VtFMu2bwo+IbG8OXsj3RVTAOBgNVHQ8BAf8EBAMCAYYwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMBIGA1UdEwEB/wQIMAYBAf8CAQAwdgYI
KwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5j
b20wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdp
Q2VydEdsb2JhbFJvb3RDQS5jcnQwewYDVR0fBHQwcjA3oDWgM4YxaHR0cDovL2Ny
bDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsUm9vdENBLmNybDA3oDWgM4Yx
aHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsUm9vdENBLmNy
bDAwBgNVHSAEKTAnMAcGBWeBDAEBMAgGBmeBDAECATAIBgZngQwBAgIwCAYGZ4EM
AQIDMA0GCSqGSIb3DQEBDAUAA4IBAQDeOpcbhb17jApY4+PwCwYAeq9EYyp/3YFt
ERim+vc4YLGwOWK9uHsu8AjJkltz32WQt960V6zALxyZZ02LXvIBoa33llPN1d9R
JzcGRvJvPDGJLEoWKRGC5+23QhST4Nlg+j8cZMsywzEXJNmvPlVv/w+AbxsBCMqk
BGPI2lNM8hkmxPad31z6n58SXqJdH/bYF462YvgdgbYKOytobPAyTgr3mYI5sUje
CzqJx1+NLyc8nAK8Ib2HxnC+IrrWzfRLvVNve8KaN9EtBH7TuMwNW4SpDCmGr6fY
1h3tDjHhkTb9PA36zoaJzu0cIw265vZt6hCmYWJC+/j+fgZwcPwL
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD
QTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT
MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
b20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB
CSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97
nh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt
43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P
T19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4
gdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO
BgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR
TLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw
DQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr
hMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg
06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF
PnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls
YSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk
CAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=
-----END CERTIFICATE-----

Certificate Transparency:

SCT Google 'Xenon2022' log (Embedded in certificate, Verified)

SCT DigiCert Yeti2022 Log (Embedded in certificate, Verified)

</details>

**Proposed Solution:**

If this is a valid url, it should have a valid certificate.

**Page to Update:**
n/a (not page specific, but rather global config?)

**Comment by tpepper** [comment]
I do wonder if this is simply not yet a valid/configured page.  Telling my browser to proceed despite the SSL error, I get a page showing nothing but, eg:
```
Not found - Request ID: 01FBM78GRANP28C60EHJVWM73K
```

**Comment by jimangel** [comment]
Leaving a comment here and will link back to the slack discussion:

This is intended behavior, 1.21 is the latest page/version (`main` branch). Clicking it does nothing because you are already there! Updating the URL is to a URL that does not exist until 1.22 is created / rolled over via docs.

Is there a better way to present this information, or a use case we're missing, to avoid relying on institutional release process knowledge to explain away behavior? heh

**Comment by sftim** [comment]
Ah, this slightly relates to #12303 
We could use Netlify for the live documentation sites and have some different wildcard DNS record direct people to an HTTPS site that serves a friendlier 404 page. Maybe a 410 for once-valid docs?

**Comment by sftim** [comment]
I know how to do all the necessary technical bits for what I just wrote. So far I haven't prioritised putting time into that.

**Comment by jimangel** [comment]
I think potentially adding a `1.xx (current)` parenthetical snip to the right of the latest version might clear things up. However this might set the expectation that the short code updates to "`(current)`" depending on version / URL. While possible, that adds a lot more complexity in the version marker shortcode. 🤷

**Comment by sftim** [comment]
/retitle TLS error accessing https://v1-21.docs.kubernetes.io/

**Comment by sftim** [comment]
Aside: https://v1-21.docs.kubernetes.io/ works now

**Comment by sftim** [comment]
Maybe the feature request is to have a simple site for the current release that 302 redirects any valid page to the main docs?

**Comment by sftim** [comment]
/retitle TLS error accessing predicted URL of archived docs

(eg https://v1-21.docs.kubernetes.io/ when v1.21 was current)
