### ISSUE TITLE
Add diagnostic advice for “Indexed Job for Parallel Processing with Static Work Assignment”

### ISSUE THREAD

**Issue by benbolivar** [kubernetes/website#29137]
$JOB_COMPLETION_INDEX is not being set as an environment resulting to all jobs/pods working on the first element of the array only (items[0], to be exact items[""]).  All pod logs will show output of "oof" and not work through the array.

**Comment by sftim** [comment]
If this outcome is because the `IndexedJob` feature gate is not enabled, we could help readers troubleshoot this by adding a note callout about why you might see “oof” as the only output.

**Comment by benbolivar** [comment]
Thanks that would indeed be helpful.

I was also able to figure it out and was able to make the code work after adding —feature-gate=IndexedJob in both the kube-api and cube-controller manifests.

Thanks again.

Ben

**Comment by sftim** [comment]
/triage accepted
/retitle Add diagnostic advice for “**Indexed Job for Parallel Processing with Static Work Assignment**”

Page to revise is https://kubernetes.io/docs/tasks/job/indexed-parallel-processing-static/

**Comment by tengqm** [comment]
/remove-lifecycle rotten
This issue is still open.
