### ISSUE TITLE
Kubernetes Security and Disclosure Information

### ISSUE THREAD

**Issue by jgarriso** [kubernetes/website#29142]
On https://kubernetes.io/docs/reference/issues-security/security/ a link is offered to subscribe to an RSS feed (https://groups.google.com/forum/feed/kubernetes-security-announce/msgs/rss_v2_0.xml?num=50) for the kubernetes-security-announce group.

However, the RSS feed link results in a 404 error. Will the ability to subscribe to an RSS feed for kubernetes-security-announce be restored anytime soon, or replaced with something else?

**Comment by shannonxtreme** [comment]
I'm pretty sure Google Groups no longer supports RSS feeds.

**Comment by sftim** [comment]
Slightly related to https://github.com/kubernetes/website/issues/30051

**Comment by PushkarJ** [comment]
KEP is in review for fixing this issue: https://github.com/kubernetes/enhancements/pull/3204. happy to get any feedback you may have on this!
