### ISSUE TITLE
The URLs to sig-windows-tools do not work (404)

### ISSUE THREAD

**Issue by jeroenlandheer** [kubernetes/website#29149]
There are some URLs to the `sig-windows-tools` repo on github, they all return 404's. 

The links are: 
https://github.com/kubernetes-sigs/sig-windows-tools/releases/download/windows-containerd-hostprocess/flannel-host-gw.yml
https://github.com/kubernetes-sigs/sig-windows-tools/releases/download/windows-containerd-hostprocess/kube-proxy.yml

Are there any alternatives for these?

**Comment by niteshseram** [comment]
I think this issue is somewhat related to #29097
/sig windows
/kind bug

**Comment by sftim** [comment]
Hi @jeroenlandheer 

Would you be willing to add the URL(s) of the documentation page that needs fixing?

**Comment by jeroenlandheer** [comment]
@sftim Sure, but the issue is really that the 'latest' link points to the 'Windows ContainerD Host Process" in the "Kubernetes-sig" repo, while the yaml files referred to are in the "Kubeadm for Windows v0.1.5" release.

Once that release gets an update, these URL will not point to the latest releease anymore, hence every time they release a new "Kubeadm for Windows" version these links needs to get updated in the documentation as well. 

I think the fact that they have 2 different projects in that same repo is the real problem.

You can see what I mean on this page: https://github.com/kubernetes-sigs/sig-windows-tools/releases/ 
 - Commit `d78d56db826e05d511c13f3bd6dd6c3bc730ffc0` is marked as the latest release, this release does not contain these files
 - Commit `c19b43da06e9dbb04e185eb44b9cb718d0d81ecd` was the actual latest release of Kubeadm for Windows, which do contain those files.

**Comment by sftim** [comment]
If someone told me that this was fixed, and I wanted to check if they were right, is there a web page within https://kubernetes.io/docs/ that I could visit and look to see how they'd addressed the problem?

If the problem is just in https://github.com/kubernetes-sigs/sig-windows-tools/ then I would file an issue there instead.

**Comment by niteshseram** [comment]
If I am not wrong, this might be the page https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
The `flannel-host-gw.yml` file can be accessed using https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/kubeadm/flannel/flannel-host-gw.yml with _raw.githubusercontent.com_ .
And `ube-proxy.yml` file can be accessed using https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/kubeadm/kube-proxy/kube-proxy.yml

**Comment by jeroenlandheer** [comment]
The pages I found broken links on are:

- https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
- https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/
(This doesn't mean there aren't more, but they do all have to do with Kubernetes on Windows)

@niteshseram Those URL's point to the repository of those files, but they aren't necessarily the released versions of those files. That's why they are probably using the "release/latest" url's instead. 

@sftim I'm not sure where this issue lies, it can be in the docs, or with the way the kubernetes-sig repo works, since I'm not part of either team I decided to report this issue here, since this is where the broken links are.

**Comment by sftim** [comment]
/triage accepted
Thanks

**Comment by neolit123** [comment]
These documents and the repository are techinically owned by sig windows.

Having multiple projects in the same repository without distinctive versioning can be a problem. Instead of linking to the master branch, released docs at k/website could link to git SHAs or release tags of the repository.

/sig windows
You can try bringing this topic for discussion in #sig-windows on k8s slack.

**Comment by reylejano** [comment]
Links are fixed, see [comment](https://github.com/kubernetes/website/pull/29755#issuecomment-924317320)
/close

**Comment by marosset** [comment]
/reopen
It looks like the links are broken again
/assign

**Comment by marosset** [comment]
/close

All of the links on kubernetes.io are still valid.
Let me know if there are any other issues with links here.
