### ISSUE TITLE
“Kubelet TLS Bootstrapping” uses outdated wording

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29140]
**This is a Bug Report**

**Problem:**
[Kubelet TLS Bootstrapping](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/) uses the outdated term “master” and “master node”.

**Proposed Solution:**
Replace references to the control plane that use the term “master” with the current term: “control plane”.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/

**Additional Information:**
/language en
/kind cleanup
/wg naming

**Comment by sftim** [comment]
/retitle “Kubelet TLS Bootstrapping” uses outdated wording

**Comment by niteshseram** [comment]
I would like to take up this issue
