### ISSUE TITLE
kubectl command reference page lists “kubectl convert” (which is provided by a plugin)

### ISSUE THREAD

**Issue by bhumijgupta** [kubernetes/website#29143]
**This is a Bug Report**

**Problem:**
kubectl-convert is now a plugin and does not come bundled with kubectl, but the [kubectl operation table](https://kubernetes.io/docs/reference/kubectl/overview/#operations) still lists convert as a operation

**Proposed Solution:**
Remove the reference of convert from operations

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/overview/#operations

**Comment by sftim** [comment]
We could also leave it in the table but mark that it depends on an in-tree plugin that you must already have installed onto your client.

**Comment by sftim** [comment]
/retitle kubectl command reference page lists “kubectl convert” (which is provided by a plugin)

**Comment by bhumijgupta** [comment]
> We could also leave it in the table but mark that it depends on an in-tree plugin that you must already have installed onto your client.

Sure. I will create a PR for this
