### ISSUE TITLE
Misalignment in /community, on mobile browsers.

### ISSUE THREAD

**Issue by code-reaper08** [kubernetes/website#29155]
**This is a Bug Report**

**Problem:**
There is a slight misalignment problem with the `Discussions` section of [https://kubernetes.io/community/](https://kubernetes.io/community/)

![1](https://user-images.githubusercontent.com/64256342/127533531-c0d59248-e67e-4465-bc16-6bfc99bbb523.png)

**Proposed Solution:**
Remove the  `font-size` from media queries, `(min-width:450px) and (max-width:600px)` & `(max-width:450px)`. I've tested on Android **Chrome 92.0.4515.115** and **Firefox 90.1.2**

**Page to Update:**
https://kubernetes.io/community/

**Comment by code-reaper08** [comment]
Hello @CIPHERTron 😄 

I didn't have time to look into it, since I filed the issue,  so the issue is still open AFAIK.

**Comment by CIPHERTron** [comment]
Hey, @code-reaper08 would you mind if I work on it?

**Comment by code-reaper08** [comment]
> Hey, @code-reaper08 would you mind if I work on it?

Sure @CIPHERTron 😄💯
