### ISSUE TITLE
[ko] Fix wrong link in assign-pod-node.md

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#29164]
**This is a Bug Report**

**Problem:** In [scheduling-eviction/assign-pod-node korean page](https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node), there is worng link related to labels-annotations-taints.

**Proposed Solution:**
Change link `[잘 알려진 레이블, 어노테이션 및 테인트](/docs/reference/labels-annotations-taints/)` to `[잘 알려진 레이블, 어노테이션 및 테인트](/ko/docs/reference/labels-annotations-taints/)` on [assign-pod-node.md](https://github.com/kubernetes/website/blob/dev-1.21-ko.7/content/ko/docs/concepts/scheduling-eviction/assign-pod-node.md)

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node

**Note**
Set base branch `Korean Team working branch`!
> Currently the working branch of Korean Team is `dev-1.21-ko.7`.

/language ko

**Comment by Darshnadas** [comment]
Is anyone working on it? If no, then I would like to work on it.
