### ISSUE TITLE
[ko] kubeadm cluster upgrade

### ISSUE THREAD

**Issue by SeongJuMoon** [kubernetes/website#29179]
https://kubernetes.io/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

[Korean]
시작하기 전에 섹션 이후로 설명하는 CoreDNS에 대한 오타가 있어 제보드립니다. 

[English]
Dear, ko-kr localization teams.

I found typo that after before started section. 
in my opinion, the typo, must be changed to coreDNS.

![image](https://user-images.githubusercontent.com/35333506/127772202-65b8ad41-6a57-4196-b4ef-c65d5aba5372.png)

**Comment by ClaudiaJKang** [comment]
@SeongJuMoon 제보 감사합니다. 

/triage accepted
/language ko
/assign
