### ISSUE TITLE
Clarify nature of CRI-O in container runtimes page

### ISSUE THREAD

**Issue by guedes84** [kubernetes/website#29185]
Cri-o in https://cri-o.io/, is descibed as "Container Runtime Interface" not "container runtime", but in https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o cri-o is described as container runtime, like containerd. CRI isnt CR.

**Comment by yuswift** [comment]
IMO, Cri-o is a `LIGHTWEIGHT CONTAINER RUNTIME FOR KUBERNETES`.
The [link](https://cri-o.io/) also says
`CRI-O is an implementation of the Kubernetes CRI (Container Runtime Interface)`

**Comment by sftim** [comment]
My take:
CRI-O is an adapter. From the CRI's point of view, CRI-O looks like a container runtime. However, CRI-O.
implements the Kubelet Container Runtime Interface (CRI) using OCI conformant runtimes. So you also need an OCI conformant container runtime for CRI-O to be useful.

/retitle Clarify nature of CRI-O in container runtimes page.

**Comment by tengqm** [comment]
/remove-lifecycle stale
I believe this clarification would be useful.

**Comment by sftim** [comment]
/retitle Clarify nature of CRI-O in container runtimes page

**Comment by sftim** [comment]
Looks like https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o is clear enough now.
/close
