### ISSUE TITLE
Static pods page is missing

### ISSUE THREAD

**Issue by rayw000** [kubernetes/website#29186]
**This is a Bug Report**

**Problem:**
Static Pods link on page https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal is missing.

**Proposed Solution:**
Perhaps one of the followings works.
1. Repair the broken link on certificate renewal page.
2. Add page `/docs/tasks/configure-pod-containerstatic-pod/`

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal
https://kubernetes.io/docs/tasks/configure-pod-containerstatic-pod/

**Comment by Shubham82** [comment]
/assign
I can work on this.

**Comment by Shubham82** [comment]
Fixed it here: #29188
