### ISSUE TITLE
Unable to follow Ingress with NGINX task in Katacoda

### ISSUE THREAD

**Issue by p4pramod** [kubernetes/website#29181]
At  step - > Create an Ingress resource

`kubectl apply -f https://k8s.io/examples/service/networking/example-ingress.yaml`

I am getting following error

unable to recognize "https://k8s.io/examples/service/networking/example-ingress.yaml": no matches for kind "Ingress" in version "networking.k8s.io/v1"

**Comment by sftim** [comment]
/kind support
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/ might be relevant. Essentially, the key thing is to make sure that the version of the documentation you're reading is for the version of Kubernetes that you're running.

**Comment by p4pramod** [comment]
Th issue  is that the steps are not working in KATACODA leave alone on local env. For replication of issue please follow the steps mentioned on the webpage below on the page itself. 

https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

**Comment by sftim** [comment]
/remove-kind support
Thanks for clarifying.

This Katacoda environment is out of date. We should update it.
/kind bug
/triage accepted

**Comment by sftim** [comment]
/retitle Unable to follow Ingress with NGINX task in Katacoda

**Comment by sftim** [comment]
/triage duplicate
First reported in #27493

**Comment by sftim** [comment]
Fixed by #29616
/close
