### ISSUE TITLE
Everything except one h2 is centered

### ISSUE THREAD

**Issue by AnirudhPanda** [kubernetes/website#29207]
**This is a Bug Report**

Every header on [this page](https://kubernetes.io/training/) is centered except the one shown
![is1](https://user-images.githubusercontent.com/66218496/128050993-4a461ff6-c2da-4071-98f3-1089524d5c1f.PNG)

**Proposed Solution:**
I would like to center it like all the headers on the page so that looks clean and flexible
**Page to Update:**
https://kubernetes.io/training/

**Comment by AnirudhPanda** [comment]
Can anyone assign me this?

**Comment by AnirudhPanda** [comment]
> /assign @AnirudhPanda

Help Required!
Where in the `website` folder I can find this css content?


![where](https://user-images.githubusercontent.com/66218496/128164127-4565268a-9a0c-41bd-8670-06df9ecad0da.PNG)

**Comment by sftim** [comment]
This might give you a clue about how the CSS is rendered and laid out: https://github.com/kubernetes/website/search?q=font-size%3A+2rem%3B

The website uses a mix of [Sass](https://sass-lang.com/) and plain CSS. Some of the styling lives in the [Docsy](https://www.docsy.dev/) theme (within `themes/docsy`) - but the nature of CSS means we're able to override it.

**Comment by niteshseram** [comment]
You can use the `<center></center>` tag. The others headers on that same page have been centered using `<center></center>` tag. 
You can do it in the same way. I think there is no need of touching the CSS.

**Comment by AnirudhPanda** [comment]
> You can use the `<center></center>` tag. The others headers on that same page have been centered using `<center></center>` tag.
> You can do it in the same way. I think there is no need of touching the CSS.

Yeah, you are right!! ✔

**Comment by AnirudhPanda** [comment]
#29214 
Made necessary changes!
