### ISSUE TITLE
Minikube playground (Katacoda) uses dated Kubernetes version

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29204]
**This is a Bug Report**

**Problem:**
The Minikube playground (pages such as [Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/)) launches Kubernetes v1.17
This is a shortcoming because there is drift between what we're documenting in pages like https://k8s.io/docs/tasks/access-application-cluster/ingress-minikube/, and what actually works in the Katacoda environment.

**Proposed Solution:**
Update the Katacoda playground to use a newer version of Minikube and hence a newer Kubernetes cluster version.

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/
(and others that use the `kat-button` shortcode)

**Additional Information:**
/priority important-longterm

**Comment by sftim** [comment]
This causes:
- #27493
- #27935
- #28897
- #29181

**Comment by jihoon-seo** [comment]
[The `kat-button` shortcode is rendered into [HTML](https://kubernetes.io/docs/test/) like this:]
```html
<div id="my-panel" data-katacoda-ondemand="true" data-katacoda-port="30000" data-katacoda-env="minikube" data-katacoda-command="start.sh" data-katacoda-ui="panel"></div>
<script src="https://katacoda.com/embed.js"></script>
<button class="button" onclick="window.katacoda.init(); ">Launch Terminal</button>
```

[URL of the embedded terminal]
view-source:https://katacoda.com/embed/minikube/?v=2&embed=true&ui=panel&host=kubernetes.io&url=https%3A%2F%2Fkubernetes.io%2Fdocs%2Ftutorials%2Fhello-minikube%2F&target=my-panel&nonce=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWJlZCI6dHJ1ZSwiZG9tYWluIjoiaHR0cHM6Ly9rdWJlcm5ldGVzLmlvLyIsImlwIjoiMTI5LjI1NC43NS4xNzgiLCJpYXQiOjE2MjgwMzk0OTUsImV4cCI6MTYyODAzOTUyNX0.n--fdeKLM0EB3LMXrajHkoVdmMTtn6eotxAwKX3dPpw&port=30000&command=start.sh

[Content of `/usr/bin/start.sh`]

```shell
echo -n "Starting Kubernetes..."

minikube version
minikube start --wait=false
sleep 2
n=0
until [ $n -ge 10 ]
do
   minikube addons enable dashboard && break
   n=$[$n+1]
   sleep 1
done
sleep 1
n=0
until [ $n -ge 10 ]
do
   kubectl apply -f /opt/kubernetes-dashboard.yaml &>/dev/null  && break
   n=$[$n+1]
   sleep 1
done

echo "Kubernetes Started"
```

I digged these pages but could not find where to update to change the minikube & K8s version:
- https://github.com/katacoda
- https://github.com/katacoda-scenarios
- https://katacoda.com/embed/panel
- https://katacoda.com/embed.js

**Comment by sftim** [comment]
@BenHall do you know / can you recommend someone who can help explain where we might open a PR to update this?

**Comment by BenHall** [comment]
@sftim Let me find out for you. The person is away this week so expect a respond next week.

**Comment by tylerauerbeck** [comment]
@BenHall @sftim Was there an update on this? Would be happy to help get this updated if needed.

**Comment by BenHall** [comment]
@sftim Sorry for the delay. It was caught up with other conversations. I've raised a PR in https://github.com/kubernetes/website/pull/29615.  It will now use K8s 1.20 which is the latest available in Katacoda.

I haven't tested the build yet but will do once ready and will update accordingly.

**Comment by medyagh** [comment]
@BenHall I was reffering to minkube version not kubernetes version. is it possible to re-open the this issue

**Comment by jihoon-seo** [comment]
@medyagh It seems that you have already opened another PR #37817 that addresses the Minikube version of Katacoda issue.
