### ISSUE TITLE
Interactive Tutorial - Module 4 Step 1 States MiniKube Does Not Support LoadBalancer Option, This is No Longer True

### ISSUE THREAD

**Issue by apmarshall** [kubernetes/website#29210]
Here's the quote:

> To create a new service and expose it to external traffic we’ll use the expose command with NodePort as parameter (minikube does not support the LoadBalancer option yet).

Minikube does support LoadBalancer since [0.31.0](https://github.com/kubernetes/minikube/blob/a03fbcf166e6f74ef224d4a63be4277d017bb62e/CHANGELOG.md#version-0310---12082018), so this should be removed and/or (even better) an updated tutorial added which demonstrates the LoadBalancer functionality.

**Comment by sftim** [comment]
I think this issue is about https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

For Kubernetes _basics_ I wouldn't cover load balancing in Minikube.

/kind bug
/language en

**Comment by yuswift** [comment]
Could you tell me how to update the `Interactive Tutorial`? I took a look at `content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html` but didn't find docs that are related to the `Interactive Tutorial`.

**Comment by sftim** [comment]
These tutorials are in a different Git repository: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

**Comment by yuswift** [comment]
> These tutorials are in a different Git repository: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

Thanks. BTW, removing `(minikube does not support the LoadBalancer option yet).` is enough?
