### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by data-ghoti** [kubernetes/website#29211]
![k8s-io tutorial errors](https://user-images.githubusercontent.com/87723357/128086991-88b692ca-13d3-4f96-be16-848eee5f6605.jpg)

basic k8s commands fail with network error as seen in attached screenshot.

**Comment by jihoon-seo** [comment]
URL: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

I followed these steps:
1. `minikube version`
1. `minikube start`
1. `kubectl version`
1. `kubectl cluster-info`
1. `kubectl get nodes`

![image](https://user-images.githubusercontent.com/46767780/128105812-5a869fd1-cc3b-44d4-bfae-96c194fce6de.png)

For me, it works well. 😊

**Comment by sftim** [comment]
@data-ghoti are these symptoms still happening?
/priority awaiting-more-evidence

**Comment by data-ghoti** [comment]
I tried it again from the beginning and appears to be working now!  Thank you very much, please close the ticket.

**Comment by jihoon-seo** [comment]
@data-ghoti 😊
/close
