### ISSUE TITLE
Add Eviction to glossary

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29223]
**This is a Feature Request**

**What would you like to be added**
Add an entry to the Kubernetes glossary, “Eviction”. Explain how Kubernetes uses this term. There are two flavors of eviction: node-initiated eviction, and API-initiated eviction. The detailed glossary entry should mention both and hyperlink to more detailed articles on these.

**Why is this needed**
“eviction” is Kubernetes jargon; readers may well come across the term without recognising it.

We have entries for the specific flavors but not an overall entry for the general term.

**Comments**
Also see issue #14507
/kind feature
/language en
/priority backlog

**Comment by jihoon-seo** [comment]
Related pages:
- Scheduling, Preemption and Eviction https://kubernetes.io/docs/concepts/scheduling-eviction/
  - Node-pressure Eviction https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/
  - API-initiated Eviction https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/
