### ISSUE TITLE
Page responsiveness problem in https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/

### ISSUE THREAD

**Issue by niteshseram** [kubernetes/website#29245]
**This is a Bug Report**

**Problem:**
There is some page responsiveness problem in mobile view in https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/.
![Capture](https://user-images.githubusercontent.com/51370246/128294904-b32629a2-a6b0-4693-9e63-5d70e959cddb.JPG)

Maybe it is caused by the below link because the text is overflowing. Hence, it is taking a single long line that extends the width of the page.

![Capture2](https://user-images.githubusercontent.com/51370246/128295082-4fd553f3-bc05-49c6-9f5e-1004bb3ea8aa.PNG)

**Proposed Solution:**
I think this can be solved by simply adding `overflow-wrap: break-word` in CSS.
**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/

/area web-development

**Comment by AnirudhPanda** [comment]
Can I work on this?

**Comment by sbarikdev** [comment]
//assign

**Comment by niteshseram** [comment]
Hi@sbarikdev, I believe @AnirudhPanda has already taken up the issue

**Comment by sbarikdev** [comment]
@niteshseram K

**Comment by AnirudhPanda** [comment]
Hey, @niteshseram where to override the css style.
The page is in Markdown. I am yet to find the exact css file.
Would like a little help here!

**Comment by niteshseram** [comment]
https://github.com/kubernetes/website/blob/c28fd4bfb5dea2297003013c5e46ecbc137502d3/assets/scss/_base.scss#L43-L49
I would add it here

**Comment by sftim** [comment]
I've seen this issue before (I think it might be a duplicate report); it affects multiple pages and not just https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/

**Comment by sftim** [comment]
I'd like to see a CSS fix where you can have a wide element in the page (sometimes we can't avoid these) and what happens is that you can scroll horizontally for the page spiel, but the top navigation stays fixed to the viewport.
