### ISSUE TITLE
Component reference docs not updated for Kubernetes v1.22 release

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/website#29255]
**This is a Bug Report**

**Problem:**

Each kubernetes component's feature gate list is outdated.

There is no feature gate newly proposed at v1.22 in the `--feature-gates` parameter.

**Proposed Solution:**

Generate those files? I am not sure about how to sync them.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
...

**Comment by sftim** [comment]
This is a more general issue
/retitle Component reference docs not updated for Kubernetes v1.22 release
/triage accepted

**Comment by sftim** [comment]
There is a PR for a fix that is ready for review: #29242

**Comment by tengqm** [comment]
Done.
/close

**Comment by gjkim42** [comment]
https://github.com/kubernetes/website/pull/29242#issuecomment-893482617

It seems that some components are still outdated.
(kubelet, kubectl)

/reopen

**Comment by tengqm** [comment]
kubelet reference is not auto-generated ...
A manual fix is proposed in #29284

**Comment by gjkim42** [comment]
#29284 has been merged.

/close
