### ISSUE TITLE
Outdated Korean contents in the dev-1.22-ko.1 branch

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#29257]
# This is a Bug Report
## Problem
Outdated files in the origin/dev-1.22-ko.1 branch.

### 77 files to be modified 
1. [x] M1.  `content/en/community/_index.html`  | 1(+XS) 1(-)
1. [x] M2.  `content/en/docs/concepts/architecture/nodes.md`  | 43(+M) 0(-)
1. [x] M3.  `content/en/docs/concepts/configuration/manage-resources-containers.md`  | 1(+XS) 1(-)
1. [x] M4.  `content/en/docs/concepts/configuration/secret.md`  | 32(+M) 23(-)
1. [x] M5.  `content/en/docs/concepts/containers/images.md`  | 2(+XS) 1(-)
1. [x] M6.  `content/en/docs/concepts/containers/runtime-class.md`  | 1(+XS) 1(-)
1. [x] M7.  `content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md`  | 10(+S) 1(-)
1. [x] M8.  `content/en/docs/concepts/overview/what-is-kubernetes.md`  | 1(+XS) 1(-)
1. [x] M9.  `content/en/docs/concepts/overview/working-with-objects/annotations.md`  | 5(+XS) 0(-)
1. [x] M10.  `content/en/docs/concepts/overview/working-with-objects/labels.md`  | 2(+XS) 2(-)
1. [x] M11.  `content/en/docs/concepts/overview/working-with-objects/names.md`  | 13(+S) 2(-)
1. [x] M12.  `content/en/docs/concepts/policy/resource-quotas.md`  | 2(+XS) 2(-)
1. [x] M13.  `content/en/docs/concepts/scheduling-eviction/assign-pod-node.md`  | 2(+XS) 2(-)
1. [x] M14.  `content/en/docs/concepts/scheduling-eviction/kube-scheduler.md`  | 1(+XS) 1(-)
1. [x] M15.  `content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md`  | 3(+XS) 3(-)
1. [x] M16.  `content/en/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md`  | 2(+XS) 2(-)
1. [x] M17.  `content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md`  | 3(+XS) 3(-)
1. [x] M18.  `content/en/docs/concepts/security/overview.md`  | 3(+XS) 1(-)
1. [x] M19.  `content/en/docs/concepts/services-networking/dns-pod-service.md`  | 23(+S) 1(-)
1. [x] M20.  `content/en/docs/concepts/services-networking/ingress-controllers.md`  | 1(+XS) 0(-)
1. [x] M21.  `content/en/docs/concepts/services-networking/ingress.md`  | 6(+XS) 1(-)
1. [x] M22.  `content/en/docs/concepts/services-networking/network-policies.md`  | 11(+S) 3(-)
1. [x] M23.  `content/en/docs/concepts/services-networking/service.md`  | 43(+M) 9(-)
1. [x] **M24.**  `content/en/docs/concepts/storage/persistent-volumes.md`  | **118(+L) 32(-)**
1. [x] M25.  `content/en/docs/concepts/storage/storage-classes.md`  | 30(+M) 1(-)
1. [x] M26.  `content/en/docs/concepts/storage/volumes.md`  | 13(+S) 48(-)
1. [x] M27.  `content/en/docs/concepts/workloads/controllers/cron-jobs.md`  | 4(+XS) 3(-)
1. [x] M28.  `content/en/docs/concepts/workloads/controllers/daemonset.md`  | 3(+XS) 1(-)
1. [x] M29.  `content/en/docs/concepts/workloads/controllers/job.md`  | 54(+M) 16(-)
1. [x] M30.  `content/en/docs/concepts/workloads/controllers/replicaset.md`  | 2(+XS) 2(-)
1. [x] M31.  `content/en/docs/concepts/workloads/controllers/statefulset.md`  | 29(+S) 15(-)
1. [x] M32.  `content/en/docs/concepts/workloads/pods/_index.md`  | 14(+S) 2(-)
1. [x] M33.  `content/en/docs/concepts/workloads/pods/disruptions.md`  | 1(+XS) 1(-)
1. [x] M34.  `content/en/docs/concepts/workloads/pods/ephemeral-containers.md`  | 4(+XS) 116(-)
1. [x] M35.  `content/en/docs/concepts/workloads/pods/init-containers.md`  | 2(+XS) 1(-)
1. [x] M36.  `content/en/docs/concepts/workloads/pods/pod-lifecycle.md`  | 2(+XS) 2(-)
1. [x] M37.  `content/en/docs/contribute/generate-ref-docs/quickstart.md`  | 7(+XS) 8(-)
1. [x] M38.  `content/en/docs/reference/_index.md`  | 4(+XS) 1(-)
1. [x] M39.  `content/en/docs/reference/access-authn-authz/service-accounts-admin.md`  | 2(+XS) 7(-)
1. [x] **M40.**  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | **217(+L) 68(-)**
1. [x] M41.  `content/en/docs/reference/glossary/api-eviction.md`  | 1(+XS) 1(-)
1. [x] M42.  `content/en/docs/reference/glossary/kube-scheduler.md`  | 1(+XS) 1(-)
1. [x] M43.  `content/en/docs/reference/kubectl/kubectl.md`  | 24(+S) 0(-)
1. [x] M44.  `content/en/docs/reference/kubectl/overview.md`  | 1(+XS) 1(-)
1. [x] **M45.**  `content/en/docs/reference/labels-annotations-taints.md`  | **106(+L) 3(-)**
1. [x] M46.  `content/en/docs/reference/scheduling/config.md`  | 67(+M) 59(-)
1. [x] M47.  `content/en/docs/reference/scheduling/policies.md`  | 1(+XS) 1(-)
1. [x] M48.  `content/en/docs/reference/tools/_index.md`  | 1(+XS) 1(-)
1. [x] M49.  `content/en/docs/reference/using-api/health-checks.md`  | 2(+XS) 2(-)
1. [x] M50.  `content/en/docs/setup/best-practices/cluster-large.md`  | 3(+XS) 0(-)
1. [x] M51.  `content/en/docs/setup/production-environment/container-runtimes.md`  | 32(+M) 0(-)
1. [x] **M52.**  `content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md`  | **140(+L) 20(-)**
1. [x] M53.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 7(+XS) 5(-)
1. [x] M54.  `content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md`  | 27(+S) 34(-)
1. [x] M55.  `content/en/docs/setup/production-environment/windows/user-guide-windows-containers.md`  | 6(+XS) 6(-)
1. [x] M56.  `content/en/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md`  | 2(+XS) 2(-)
1. [x] M57.  `content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md`  | 2(+XS) 2(-)
1. [x] M58.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md`  | 14(+S) 4(-)
1. [x] M59.  `content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md`  | 39(+M) 25(-)
1. [x] M60.  `content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md`  | 1(+XS) 1(-)
1. [x] M61.  `content/en/docs/tasks/manage-daemon/update-daemon-set.md`  | 9(+XS) 6(-)
1. [x] M62.  `content/en/docs/tasks/manage-hugepages/scheduling-hugepages.md`  | 6(+XS) 0(-)
1. [x] M63.  `content/en/docs/tasks/network/validate-dual-stack.md`  | 1(+XS) 1(-)
1. [x] M64.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md`  | 1(+XS) 1(-)
1. [x] M65.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale.md`  | 11(+S) 8(-)
1. [x] M66.  `content/en/docs/tasks/tools/install-kubectl-macos.md`  | 2(+XS) 2(-)
1. [x] M67.  `content/en/docs/tutorials/clusters/apparmor.md`  | 5(+XS) 0(-)
1. [x] M68.  `content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html`  | 1(+XS) 1(-)
1. [x] M69.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html`  | 2(+XS) 2(-)
1. [x] M70.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html`  | 2(+XS) 2(-)
1. [x] M71.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html`  | 2(+XS) 2(-)
1. [x] M72.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html`  | 1(+XS) 1(-)
1. [x] M73.  `content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html`  | 2(+XS) 2(-)
1. [x] M74.  `content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html`  | 1(+XS) 1(-)
1. [x] M75.  `content/en/docs/tutorials/stateful-application/cassandra.md`  | 2(+XS) 2(-)
1. [x] M76.  `content/en/docs/tutorials/stateful-application/zookeeper.md`  | 4(+XS) 4(-)
1. [x] M77.  `content/en/docs/tutorials/stateless-application/guestbook.md`  | 1(+XS) 1(-)

### 2 files to be deleted 
1. [x] D1.  `content/en/docs/concepts/cluster-administration/kubelet-garbage-collection.md`
1. [x] D2.  `content/en/docs/concepts/workloads/controllers/garbage-collection.md`

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `origin/dev-1.22-ko.1` branch.

For example:
```
# checkout `origin/dev-1.22-ko.1`
...
# check what is updated in the upstream 
git diff origin/dev-1.21-ko.7 origin/dev-1.22-ko.1 -- content/en/community/_index.html
# apply changes to content/ko
vi content/ko/community/_index.html
...
# commit and push
...
# make PR to `origin/dev-1.22-ko.1`
```

## Pages to Update

Pages in content/ko

/language ko

**Comment by ClaudiaJKang** [comment]
M2, M7, M12, M13, M14, M16, M18, M19, M21, M24, M26, M27, M30, M31, M34, M39, M43, M36, M47, M51, M52, M54, M62의 경우 #29253 에서도 적용되니 작업 시작 전 확인 부탁드립니다.

**Comment by seokho-son** [comment]
I will take M1 - M18 tasks ~!

- M1 - M18 : @seokho-son 
- ...
- ...

**Comment by jihoon-seo** [comment]
M61 - M77 제가 하겠습니다~
/assign

**Comment by ClaudiaJKang** [comment]
I will assign M31-M50!

M1 - M18 : @seokho-son
...
M31 - M60 : @ClaudiaJKang
M61 - M77 : @jihoon-seo

**Comment by jihoon-seo** [comment]
M19 - M30 제가 하겠습니다~
/assign

* M1 - M18 : @seokho-son
* M19 - M30 : @jihoon-seo 
* M31 - M60 : @ClaudiaJKang 
* M61 - M77 : @jihoon-seo

**Comment by seokho-son** [comment]
@ClaudiaJKang 님과 협의하여~

M52. content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md | 140(+L) 20(-)
는 제가 처리하도록 하겠습니다!
