### ISSUE TITLE
Outdated Korean contents in the dev-1.21-ko.8 branch

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#29253]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.21-ko.8 branch.

Generated report by the following command.
`scripts/diff_l10n_branches.py ko upstream/dev-1.21-ko.7 upstream/dev-1.21-ko.8`

Note that `dev-1.21-ko.8` recreated. based on https://github.com/kubernetes/website/pull/30292

### 55 files to be modified 
1. [ ] M1.  `content/en/community/_index.html`  | 1(+XS) 1(-)
1. [ ] M2.  `content/en/docs/concepts/configuration/manage-resources-containers.md`  | 1(+XS) 1(-)
1. [ ] M3.  `content/en/docs/concepts/configuration/secret.md`  | 32(+M) 23(-)
1. [ ] M4.  `content/en/docs/concepts/containers/images.md`  | 2(+XS) 1(-)
1. [ ] M5.  `content/en/docs/concepts/containers/runtime-class.md`  | 1(+XS) 1(-)
1. [ ] M6.  `content/en/docs/concepts/overview/what-is-kubernetes.md`  | 1(+XS) 1(-)
1. [ ] M7.  `content/en/docs/concepts/overview/working-with-objects/annotations.md`  | 5(+XS) 0(-)
1. [ ] M8.  `content/en/docs/concepts/overview/working-with-objects/labels.md`  | 2(+XS) 2(-)
1. [ ] M9.  `content/en/docs/concepts/overview/working-with-objects/names.md`  | 13(+S) 2(-)
1. [ ] M10.  `content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md`  | 3(+XS) 3(-)
1. [ ] M11.  `content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md`  | 3(+XS) 3(-)
1. [ ] M12.  `content/en/docs/concepts/services-networking/ingress-controllers.md`  | 1(+XS) 0(-)
1. [ ] M13.  `content/en/docs/concepts/services-networking/network-policies.md`  | 1(+XS) 1(-)
1. [ ] M14.  `content/en/docs/concepts/services-networking/service.md`  | 2(+XS) 2(-)
1. [ ] M15.  `content/en/docs/concepts/storage/storage-classes.md`  | 24(+S) 1(-)
1. [ ] M16.  `content/en/docs/concepts/workloads/controllers/daemonset.md`  | 3(+XS) 1(-)
1. [ ] M17.  `content/en/docs/concepts/workloads/controllers/job.md`  | 2(+XS) 1(-)
1. [ ] M18.  `content/en/docs/concepts/workloads/pods/_index.md`  | 11(+S) 0(-)
1. [ ] M19.  `content/en/docs/concepts/workloads/pods/disruptions.md`  | 1(+XS) 1(-)
1. [ ] M20.  `content/en/docs/concepts/workloads/pods/init-containers.md`  | 2(+XS) 1(-)
1. [ ] M21.  `content/en/docs/concepts/workloads/pods/pod-lifecycle.md`  | 2(+XS) 2(-)
1. [ ] M22.  `content/en/docs/contribute/generate-ref-docs/quickstart.md`  | 7(+XS) 8(-)
1. [ ] M23.  `content/en/docs/reference/_index.md`  | 1(+XS) 1(-)
1. [ ] M24.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 3(+XS) 0(-)
1. [ ] M25.  `content/en/docs/reference/glossary/api-eviction.md`  | 1(+XS) 1(-)
1. [ ] M26.  `content/en/docs/reference/glossary/kube-scheduler.md`  | 1(+XS) 1(-)
1. [ ] M27.  `content/en/docs/reference/kubectl/overview.md`  | 1(+XS) 1(-)
1. [ ] M28.  `content/en/docs/reference/labels-annotations-taints.md`  | 2(+XS) 1(-)
1. [ ] M29.  `content/en/docs/reference/tools/_index.md`  | 1(+XS) 1(-)
1. [ ] M30.  `content/en/docs/reference/using-api/health-checks.md`  | 2(+XS) 2(-)
1. [ ] M31.  `content/en/docs/setup/best-practices/cluster-large.md`  | 3(+XS) 0(-)
1. [ ] M32.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 7(+XS) 5(-)
1. [ ] M33.  `content/en/docs/setup/production-environment/windows/user-guide-windows-containers.md`  | 6(+XS) 6(-)
1. [ ] M34.  `content/en/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md`  | 2(+XS) 2(-)
1. [ ] M35.  `content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md`  | 2(+XS) 2(-)
1. [ ] M36.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md`  | 12(+S) 1(-)
1. [ ] M37.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md`  | 33(+M) 33(-)
1. [ ] M38.  `content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md`  | 39(+M) 25(-)
1. [ ] M39.  `content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md`  | 1(+XS) 1(-)
1. [ ] M40.  `content/en/docs/tasks/manage-daemon/update-daemon-set.md`  | 2(+XS) 1(-)
1. [ ] M41.  `content/en/docs/tasks/network/validate-dual-stack.md`  | 1(+XS) 1(-)
1. [ ] M42.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md`  | 1(+XS) 1(-)
1. [ ] M43.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale.md`  | 11(+S) 8(-)
1. [ ] M44.  `content/en/docs/tasks/tools/install-kubectl-macos.md`  | 2(+XS) 2(-)
1. [ ] M45.  `content/en/docs/tutorials/clusters/apparmor.md`  | 5(+XS) 0(-)
1. [ ] M46.  `content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html`  | 1(+XS) 1(-)
1. [ ] M47.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html`  | 2(+XS) 2(-)
1. [ ] M48.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html`  | 2(+XS) 2(-)
1. [ ] M49.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html`  | 2(+XS) 2(-)
1. [ ] M50.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html`  | 1(+XS) 1(-)
1. [ ] M51.  `content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html`  | 2(+XS) 2(-)
1. [ ] M52.  `content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html`  | 1(+XS) 1(-)
1. [ ] M53.  `content/en/docs/tutorials/stateful-application/cassandra.md`  | 2(+XS) 2(-)
1. [ ] M54.  `content/en/docs/tutorials/stateful-application/zookeeper.md`  | 4(+XS) 4(-)
1. [ ] M55.  `content/en/docs/tutorials/stateless-application/guestbook.md`  | 1(+XS) 1(-)

### 2 files to be deleted 
1. [ ] D1.  `content/en/docs/concepts/cluster-administration/kubelet-garbage-collection.md`
1. [ ] D2.  `content/en/docs/concepts/workloads/controllers/garbage-collection.md`

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.21-ko.8` branch.

For example:
```
# checkout `upstream/dev-1.21-ko.8`
...
# check what is updated in the upstream 
git diff upstream/dev-1.21-ko.7 upstream/dev-1.21-ko.8 -- content/en/community/_index.html
# apply changes to content/ko
vi content/ko/community/_index.html
...
# commit and push
...
# make PR to `upstream/dev-1.21-ko.8`
```

## Pages to Update

Pages in content/ko

**Comment by ClaudiaJKang** [comment]
M1, M2, M3, M4, M5, M6, M7, M8, M9, M12, M14, M15, M17, M18, M20, M22, M24, M26, M27, M28, M29, M30, M33 의 경우 #29257 에서도 적용되니 작업 시작 전 확인 부탁드립니다.

**Comment by jihoon-seo** [comment]
[참고할 수 있는 PR들]

### 33 files to be modified
1. [ ]  _M1_.  `content/en/docs/concepts/architecture/nodes.md`  | 43(+M) 0(-)
   - #29934 (by @seokho-son)
2. [ ]  _M2_.  `content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md`  | 10(+S) 1(-)
   - #29931 (by @seokho-son)
3. [ ]  _M3_.  `content/en/docs/concepts/policy/resource-quotas.md`  | 2(+XS) 2(-)
   - #29931 (by @seokho-son)
4. [ ]  _M4_.  `content/en/docs/concepts/scheduling-eviction/assign-pod-node.md`  | 2(+XS) 2(-)
   - #29931 (by @seokho-son)
5. [ ]  _M5_.  `content/en/docs/concepts/scheduling-eviction/kube-scheduler.md`  | 1(+XS) 1(-)
   - #29931 (by @seokho-son)
6. [ ]  _M6_.  `content/en/docs/concepts/scheduling-eviction/scheduler-perf-tuning.md`  | 2(+XS) 2(-)
   - #29931 (by @seokho-son)
7. [ ]  _M7_.  `content/en/docs/concepts/security/overview.md`  | 3(+XS) 1(-)
   - #29931 (by @seokho-son)
8. [ ]  _M8_.  `content/en/docs/concepts/services-networking/dns-pod-service.md`  | 23(+S) 1(-)
   - #29842 (by @jihoon-seo)
9. [ ]  _M9_.  `content/en/docs/concepts/services-networking/ingress.md`  | 6(+XS) 1(-)
   - #29842 (by @jihoon-seo)
10. [ ]  M10.  `content/en/docs/concepts/services-networking/network-policies.md`  | 12(+S) 4(-)
    - #29842 (by @jihoon-seo)
11. [ ]  M11.  `content/en/docs/concepts/services-networking/service.md`  | 42(+M) 8(-)
    - #29842 (by @jihoon-seo)
12. [ ]  **_M12_.**  `content/en/docs/concepts/storage/persistent-volumes.md`  | **118(+L) 32(-)**
    - #29842 (by @jihoon-seo)
13. [ ]  M13.  `content/en/docs/concepts/storage/storage-classes.md`  | 6(+XS) 0(-)
    - #29843 (by @jihoon-seo)
14. [ ]  _M14_.  `content/en/docs/concepts/storage/volumes.md`  | 13(+S) 48(-)
    - #29843 (by @jihoon-seo)
15. [ ]  _M15_.  `content/en/docs/concepts/workloads/controllers/cron-jobs.md`  | 4(+XS) 3(-)
    - #29843 (by @jihoon-seo)
16. [ ]  M16.  `content/en/docs/concepts/workloads/controllers/job.md`  | 52(+M) 15(-)
    - #29843 (by @jihoon-seo)
17. [ ]  _M17_.  `content/en/docs/concepts/workloads/controllers/replicaset.md`  | 2(+XS) 2(-)
    - #29843 (by @jihoon-seo)
18. [ ]  _M18_.  `content/en/docs/concepts/workloads/controllers/statefulset.md`  | 29(+S) 15(-)
    - #29834 (by @ClaudiaJKang)
19. [ ]  M19.  `content/en/docs/concepts/workloads/pods/_index.md`  | 3(+XS) 2(-)
    - #29834 (by @ClaudiaJKang)
20. [ ]  _M20_.  `content/en/docs/concepts/workloads/pods/ephemeral-containers.md`  | 4(+XS) 116(-)
    - #29834 (by @ClaudiaJKang)
21. [ ]  M21.  `content/en/docs/reference/_index.md`  | 3(+XS) 0(-)
    - #29834 (by @ClaudiaJKang)
22. [ ]  _M22_.  `content/en/docs/reference/access-authn-authz/service-accounts-admin.md`  | 2(+XS) 7(-)
    - #29834 (by @ClaudiaJKang)
23. [ ]  **M23.**  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | **214(+L) 68(-)**
    - #29851 (by @ClaudiaJKang)
24. [ ]  _M24_.  `content/en/docs/reference/kubectl/kubectl.md`  | 24(+S) 0(-)
    - #29826 (by @ClaudiaJKang)
25. [ ]  **M25.**  `content/en/docs/reference/labels-annotations-taints.md`  | **104(+L) 2(-)**
    - #29835 (by @ClaudiaJKang)
26. [ ]  _M26_.  `content/en/docs/reference/scheduling/config.md`  | 67(+M) 59(-)
    - #29826 (by @ClaudiaJKang)
27. [ ]  _M27_.  `content/en/docs/reference/scheduling/policies.md`  | 1(+XS) 1(-)
    - #29826 (by @ClaudiaJKang)
28. [ ]  _M28_.  `content/en/docs/setup/production-environment/container-runtimes.md`  | 32(+M) 0(-)
    - #29813 (by @ClaudiaJKang)
29. [ ]  **_M29_.**  `content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md`  | **140(+L) 20(-)**
    - #29941 (by @seokho-son)
30. [ ]  _M30_.  `content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md`  | 27(+S) 34(-)
    - #29813 (by @ClaudiaJKang)
31. [ ]  M31.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md`  | 4(+XS) 5(-)
    - #29813 (by @ClaudiaJKang)
32. [ ]  M32.  `content/en/docs/tasks/manage-daemon/update-daemon-set.md`  | 7(+XS) 5(-)
    - #29736 (by @jihoon-seo)
33. [ ]  _M33_.  `content/en/docs/tasks/manage-hugepages/scheduling-hugepages.md`  | 6(+XS) 0(-)
    - #29736 (by @jihoon-seo)

**Comment by seokho-son** [comment]
#29257 작업에서 참고할 수 있는 Task들 (check)

1. [ ] M1.  `content/en/community/_index.html`  | 1(+XS) 1(-)
1. [ ] M2.  `content/en/docs/concepts/configuration/manage-resources-containers.md`  | 1(+XS) 1(-)
1. [ ] M3.  `content/en/docs/concepts/configuration/secret.md`  | 32(+M) 23(-)
1. [ ] M4.  `content/en/docs/concepts/containers/images.md`  | 2(+XS) 1(-)
1. [ ] M5.  `content/en/docs/concepts/containers/runtime-class.md`  | 1(+XS) 1(-)
1. [ ] M6.  `content/en/docs/concepts/overview/what-is-kubernetes.md`  | 1(+XS) 1(-)
1. [ ] M7.  `content/en/docs/concepts/overview/working-with-objects/annotations.md`  | 5(+XS) 0(-)
1. [ ] M8.  `content/en/docs/concepts/overview/working-with-objects/labels.md`  | 2(+XS) 2(-)
1. [ ] M9.  `content/en/docs/concepts/overview/working-with-objects/names.md`  | 13(+S) 2(-)
1. [ ] M10.  `content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md`  | 3(+XS) 3(-)
1. [ ] M11.  `content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md`  | 3(+XS) 3(-)
1. [ ] M12.  `content/en/docs/concepts/services-networking/ingress-controllers.md`  | 1(+XS) 0(-)
1. [ ] M13.  `content/en/docs/concepts/services-networking/network-policies.md`  | 1(+XS) 1(-)
1. [ ] M14.  `content/en/docs/concepts/services-networking/service.md`  | 2(+XS) 2(-)
1. [ ] M15.  `content/en/docs/concepts/storage/storage-classes.md`  | 24(+S) 1(-)
1. [ ] M16.  `content/en/docs/concepts/workloads/controllers/daemonset.md`  | 3(+XS) 1(-)
1. [ ] M17.  `content/en/docs/concepts/workloads/controllers/job.md`  | 2(+XS) 1(-)
1. [ ] M18.  `content/en/docs/concepts/workloads/pods/_index.md`  | 11(+S) 0(-)
1. [ ] M19.  `content/en/docs/concepts/workloads/pods/disruptions.md`  | 1(+XS) 1(-)
1. [ ] M20.  `content/en/docs/concepts/workloads/pods/init-containers.md`  | 2(+XS) 1(-)
1. [ ] M21.  `content/en/docs/concepts/workloads/pods/pod-lifecycle.md`  | 2(+XS) 2(-)
1. [ ] M22.  `content/en/docs/contribute/generate-ref-docs/quickstart.md`  | 7(+XS) 8(-)
1. [ ] M23.  `content/en/docs/reference/_index.md`  | 1(+XS) 1(-)
1. [ ] M24.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 3(+XS) 0(-)
1. [ ] M25.  `content/en/docs/reference/glossary/api-eviction.md`  | 1(+XS) 1(-)
1. [ ] M26.  `content/en/docs/reference/glossary/kube-scheduler.md`  | 1(+XS) 1(-)
1. [ ] M27.  `content/en/docs/reference/kubectl/overview.md`  | 1(+XS) 1(-)
1. [ ] M28.  `content/en/docs/reference/labels-annotations-taints.md`  | 2(+XS) 1(-)
1. [ ] M29.  `content/en/docs/reference/tools/_index.md`  | 1(+XS) 1(-)
1. [ ] M30.  `content/en/docs/reference/using-api/health-checks.md`  | 2(+XS) 2(-)
1. [ ] M31.  `content/en/docs/setup/best-practices/cluster-large.md`  | 3(+XS) 0(-)
1. [ ] M32.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 7(+XS) 5(-)
1. [ ] M33.  `content/en/docs/setup/production-environment/windows/user-guide-windows-containers.md`  | 6(+XS) 6(-)
1. [ ] M34.  `content/en/docs/tasks/access-application-cluster/port-forward-access-application-cluster.md`  | 2(+XS) 2(-)
1. [ ] M35.  `content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md`  | 2(+XS) 2(-)
1. [ ] M36.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-certs.md`  | 12(+S) 1(-)
1. [ ] M37.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md`  | 33(+M) 33(-)
1. [ ] M38.  `content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md`  | 39(+M) 25(-)
1. [ ] M39.  `content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md`  | 1(+XS) 1(-)
1. [ ] M40.  `content/en/docs/tasks/manage-daemon/update-daemon-set.md`  | 2(+XS) 1(-)
1. [ ] M41.  `content/en/docs/tasks/network/validate-dual-stack.md`  | 1(+XS) 1(-)
1. [ ] M42.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md`  | 1(+XS) 1(-)
1. [ ] M43.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale.md`  | 11(+S) 8(-)
1. [ ] M44.  `content/en/docs/tasks/tools/install-kubectl-macos.md`  | 2(+XS) 2(-)
1. [ ] M45.  `content/en/docs/tutorials/clusters/apparmor.md`  | 5(+XS) 0(-)
1. [ ] M46.  `content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html`  | 1(+XS) 1(-)
1. [ ] M47.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html`  | 2(+XS) 2(-)
1. [ ] M48.  `content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html`  | 2(+XS) 2(-)
1. [ ] M49.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-interactive.html`  | 2(+XS) 2(-)
1. [ ] M50.  `content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html`  | 1(+XS) 1(-)
1. [ ] M51.  `content/en/docs/tutorials/kubernetes-basics/scale/scale-interactive.html`  | 2(+XS) 2(-)
1. [ ] M52.  `content/en/docs/tutorials/kubernetes-basics/update/update-interactive.html`  | 1(+XS) 1(-)
1. [ ] M53.  `content/en/docs/tutorials/stateful-application/cassandra.md`  | 2(+XS) 2(-)
1. [ ] M54.  `content/en/docs/tutorials/stateful-application/zookeeper.md`  | 4(+XS) 4(-)
1. [ ] M55.  `content/en/docs/tutorials/stateless-application/guestbook.md`  | 1(+XS) 1(-)

**Comment by seokho-son** [comment]
M1 - M12 : @seokho-son

**Comment by jihoon-seo** [comment]
M13 - M40 제가 하겠습니다~
/assign

M1 - M12 : @seokho-son
M13 - M40 : @jihoon-seo
M41 - M55 : @seokho-son

**Comment by jihoon-seo** [comment]
모든 M** 처리가 완료되어
이제 `dev-1.21-ko.8` 을 `release-1.21` 에 merge하면 될 것 같습니다 😊

**Comment by seokho-son** [comment]
@jihoon-seo 감사합니다!

1.22 에서는 해당 D1, D2 를 삭제하지 않고, 변합된 문서로 링크를 하였으나,
https://kubernetes.io/ko/docs/concepts/cluster-administration/kubelet-garbage-collection/

release에서는 오히려 혼동을 줄이기 위해서 삭제를 하는 것이 좋겠다는 생각입니다.

머지 PR 올리면서 정리하도록 하겠습니다!

**Comment by seokho-son** [comment]
아.. 머지를 하고 나서;; 추가로 처리하는 것이 좋을 것 같습니다!!

**Comment by jihoon-seo** [comment]
For anyone's information:
`dev-1.21-ko.8` 을 `release-1.21` 에 반영하는 PR #30600 이 merge 되었습니다.
D1, D2 만 처리되면, 이 이슈는 resolve 됩니다. 😊
