### ISSUE TITLE
Incorrect feature state for Server-side Apply

### ISSUE THREAD

**Issue by Jean-Daniel** [kubernetes/website#29266]
According to the [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#server-side-apply-graduates-to-ga): this feature has been graduated to GA in 1.22

The doc still indicates:

`FEATURE STATE: Kubernetes v1.16 [beta]`

```
Disabling the feature

Server Side Apply is a beta feature, so it is enabled by default. To turn this feature gate off, you need to include the --feature-gates ServerSideApply=false flag when starting kube-apiserver. If you have multiple kube-apiserver replicas, all should have the same flag setting.
```

**Comment by sftim** [comment]
/retitle Incorrect feature state for Server-side Apply
/kind bug
/language en

Which page is wrong, @Jean-Daniel ? Can you provide the URL for it?

**Comment by sftim** [comment]
I think the page is https://kubernetes.io/docs/reference/using-api/server-side-apply/
/triage accepted
