### ISSUE TITLE
Releases 1.22 Version is not navigating | Missing URL

### ISSUE THREAD

**Issue by imoisharma** [kubernetes/website#29274]
Hi folks, 

When I am trying to click on the versions drop-down and select the 1.22 k8s version, it should navigate me to the https://v1-22.docs.kubernetes.io/ but instead, it navigates me to the https://kubernetes.io/

Could you please fix the link on the website. Cheers.

Steps for replications.
1. Go to kubernetes.io website
2. Click Versions from the header
3. Select 1.22 version
4. it should take it to the v1-22.docs.kubernetes.io but it navigates back to the home of kubernetes.

Feel free to message me, if you need more information.

Best Regards
Mohit Sharma.

**Comment by niteshseram** [comment]
Hi @imoisharma, I believe it is intended to behave that way because you are already in the current version which is 1.22. Current version(1.22) is mapped to kubernetes.io

**Comment by tengqm** [comment]
The 'kubernetes.io/docs' or 'k8s.io/docs' is about the latest version, i.e. 1.22.
/close
