### ISSUE TITLE
`go.mod` not working well in Go 1.16

### ISSUE THREAD

**Issue by astraw99** [kubernetes/website#29287]
**This is a Bug Report**

**Problem:**

On Mac 10.15
go version 1.16

run `go mod tidy`, got:
```
go: k8s.io/kubernetes@v0.0.0 requires
        k8s.io/pod-security-admission@v0.0.0: reading k8s.io/pod-security-admission/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Proposed Solution:**
need to replace `k8s.io/pod-security-admission@v0.0.0` with proper version.

**Page to Update:**
go.mod

**Comment by sftim** [comment]
I'm not sure I know why there is Go code in _this_ repo. @tengqm have we written this up anywhere?

**Comment by tengqm** [comment]
@sftim They are for running the examples test case, which is a guardian for ensuring all manifests under `examples` work for the "current" release.
