### ISSUE TITLE
Broken example in Configuration Best Practices concept

### ISSUE THREAD

**Issue by aditya7041** [kubernetes/website#29289]
https://kubernetes.io/docs/concepts/configuration/overview/ 
Link of config file example is broken.

**Comment by imoisharma** [comment]
Hi @aditya7041, could you provide some more details, which link is broken when you try to access it?

**Comment by yuswift** [comment]
I think the link is https://github.com/kubernetes/examples/tree/main/guestbook/all-in-one/guestbook-all-in-one.yaml.

**Comment by sftim** [comment]
/retitle Broken example in Configuration Best Practices concept
