### ISSUE TITLE
Auditing - githubbranch param pointing to "main" breaks certain links.

### ISSUE THREAD

**Issue by jorlamd** [kubernetes/website#29298]
**This is a Bug Report**

**Problem:** variable githubbranch points to "main". However, the links referring to files on the kubernetes/kubernetes repo are broken, as this repo uses "master" for the main branch naming convention.

**Proposed Solution:** Review the toml file containing the githubbranch variable.

**Comment by yuswift** [comment]
ref https://github.com/kubernetes/website/issues/29263#issuecomment-894025463

**Comment by sftim** [comment]
The `githubbranch` value is correct. However, links to _other_ repos shouldn't rely on the default branch there being called _master_ or _main_ or anything else. Instead, we can hard-code the name of the target repo's default branch.

/kind bug
