### ISSUE TITLE
Broken link: webhook.go give 404 error.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#29294]
**This is a Bug Report**

**Problem:**
In [Webhook Mode](https://kubernetes.io/docs/reference/access-authn-authz/webhook/) docs, [webhook.go](https://github.com/kubernetes/kubernetes/blob/main/staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go) link give 404 error.

**Proposed Solution:**
webhook.go should be linked to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook.go

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/webhook/

**Comment by Shubham82** [comment]
/assign
i can work on this.

**Comment by Shubham82** [comment]
Fixed it here: #29299

**Comment by yuswift** [comment]
ref https://github.com/kubernetes/website/issues/29263#issuecomment-894025463

**Comment by Shubham82** [comment]
Hi @yuswift
I think we don't change in config.toml file as it is used as configuration when building the website. It was changed in this [PR](https://github.com/kubernetes/website/pull/29196), as for website repo master branch renamed to main in k8s v1.22.
