### ISSUE TITLE
Volumes - Broken links to azure disk and azure file csi driver examples

### ISSUE THREAD

**Issue by ominiet** [kubernetes/website#29303]
When clicking link to `azureFile volume plugin`, I expect to be taken to a github link with associated content, however, I am sent to
https://github.com/kubernetes/examples/tree/main/staging/volumes/azure_file/README.md
and receive a 404. The same behavior happens when selecting `azureDisk volume plugin`

**Comment by niteshseram** [comment]
Ref #29263 
/kind bug
