### ISSUE TITLE
Namespaces :: contradictions

### ISSUE THREAD

**Issue by sgpinkus** [kubernetes/website#29307]
Let's approach from a user goal: I want to run multiple projects on the same cluster and securely isolate them. For example: A. testing/staging/prod envs of the same product. B. Multiple projects from different clients, like small websites. Is namespaces supposed to be what I  use to achieve this isolation? The first paragraph:

> Kubernetes supports multiple virtual clusters backed by the same physical cluster. These virtual clusters are called namespaces.

OK! Looks like namespaces is how I isolate groups of unrelated resources. Cool. The very next paragraph:

> Namespaces are intended for use in environments with many users spread across multiple teams, or projects. For clusters with a few to tens of users, you should not need to create or think about namespaces at all. Start using namespaces when you need the features they provide.

Wait so only multi user access control in large orgs? Fourth, paragraph:

> Namespaces are a way to divide cluster resources between multiple users (via resource quota). It is not necessary to use multiple namespaces to separate slightly different resources, such as different versions of the same software: use labels to distinguish resources within the same namespace

Hmm, you seem to be saying I should stay away from namespaces unless my use case is cluster access control by multiple real users,  and I should use labels instead.

Later on:

> When you create a Service, it creates a corresponding DNS entry. This entry is of the form <service-name>.<namespace-name>.svc.cluster.local, which means that if a container only uses <service-name>, it will resolve to the service which is local to a namespace. This is useful for using the same configuration across multiple namespaces such as Development, Staging and Production. If you want to reach across namespaces, you need to use the fully qualified domain name (FQDN).

Wait, that's exactly one of my use cases - separate testing/staging/prod on same cluster, nothing to do with multi user access. So I really should be using namespaces for this?

Conclusion: It's really the [2nd section](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#when-to-use-multiple-namespaces) that's confusing and wrong. It dismisses namespaces as only something that applies to access by multiple real users, and only when you have "tens" of them. But that ignores service-accounts. It's also unclear whether deploying services into different namespaces implicitly isolates them without the need for service-accounts at all, in which case users and service-accounts are both N/A (UPDATE: I tested that and you can access pods and svc in other namespaces, at least be default. Weird).

**Comment by sftim** [comment]
/sig architecture
I guess

**Comment by sftim** [comment]
I think it's reasonable to suggest that namespaces could be useful for a small or even solo team, if you want to use namespaces to isolate workload environments from one another.
