### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by yukurt** [kubernetes/website#29306]
Katacoda terminal says:

```
This environment is no longer available
```

I then can't type anything on the terminal.

**Comment by niteshseram** [comment]
Hi @yukurt, I am not able to reproduce the problem and it is working completely fine. Are you still facing the same issue?

**Comment by yukurt** [comment]
hi @niteshseram, i can't reproduce the error either.
what i did was i just refreshed my web browser.
i think the web browser/terminal must have "expired" since i did not use the browser for several hours prior to using it again.
thank you for your assistance.
