### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by tRavAsty** [kubernetes/website#29319]
The interactive terminal is no longer available
<img width="1445" alt="Screen Shot 2021-08-10 at 4 50 09 PM" src="https://user-images.githubusercontent.com/12147341/128933149-dd080c82-9b66-4f47-a863-02bd20c35f4a.png">

**Comment by RA489** [comment]
@tRavAsty could you please refresh and try it works for me.

**Comment by tRavAsty** [comment]
> @tRavAsty could you please refresh and try it works for me.

yeah it is working now
