### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by stuart23** [kubernetes/website#29317]
Azure Files link is broken

**Comment by yuswift** [comment]
#29311 will fix it

**Comment by sftim** [comment]
/kind bug
/language en
/triage duplicate 

Duplicates #29298

**Comment by sftim** [comment]
Thanks for reporting this @stuart23

**Comment by sftim** [comment]
Fixed in #29311
/close
