### ISSUE TITLE
Error from server (Forbidden): namespaces is forbidden: User "system:node:xxxxxxxxxx" cannot list resource

### ISSUE THREAD

**Issue by partsauthority** [kubernetes/website#29313]
After updating the kubernetes cluster certs using the below document getting below error. Please advise

[](https://www.ibm.com/docs/en/fci/1.1.0?topic=kubernetes-renewing-cluster-certificates)

# kubectl get namespaces
Error from server (Forbidden): namespaces is forbidden: User "system:node:xxxxxx" cannot list resource "namespaces" in API group "" at the cluster scope

kubernetes version:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by yuswift** [comment]
How do you update the cluster certs?

**Comment by partsauthority** [comment]
I updated the certs using the below command.

kubeadm alpha certs renew all

After this the kubelet.conf was not updated with the new certificate, so I
did run the below command.

sudo kubeadm alpha kubeconfig user --org system:nodes --client-name
system:node:$(hostname) > kubelet.conf

And after this I copied the certificate-data and certificate-key from
kubelet.conf to .kube/config. After this I was able to list pods but
nothing else.

Thanks
Srikanth Bhagyasri

**Comment by neolit123** [comment]
hi, this repository is for features/bugs in the docs.

please use the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close

**Comment by yuswift** [comment]
> I updated the certs using the below command. kubeadm alpha certs renew all After this the kubelet.conf was not updated with the new certificate, so I did run the below command. sudo kubeadm alpha kubeconfig user --org system:nodes --client-name system:node:$(hostname) > kubelet.conf And after this I copied the certificate-data and certificate-key from kubelet.conf to .kube/config. After this I was able to list pods but nothing else. Thanks Srikanth Bhagyasri
> […](#)
> On Tue, Aug 10, 2021 at 7:07 AM Swift ***@***.***> wrote: *CAUTION: *This Email is from an EXTERNAL source. Ensure you trust this sender before clicking on any links or attachments. How do you update the cluster certs? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kubernetes_website_issues_29313-23issuecomment-2D896059070&d=DwMCaQ&c=ZD4UquQXZ0yA-RSlUqe8CfLnRLhwU4IIz-bJ8pw2VMY&r=FPaI2vHFJWVzl-YOfxAezMqvfX2A2nlU4-YTdkTbsAI&m=pAVzmVmsdInpdZMphzWlMcUYag1-Y3OuBanDFDb3UGI&s=n1J1MMDLoUx55UOs3GfgFaWEBEzGaXjQoudu9rhkiGk&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ALXM3B6ZC7NAZKFKYUVFCB3T4EXAXANCNFSM5B3L6KQQ&d=DwMCaQ&c=ZD4UquQXZ0yA-RSlUqe8CfLnRLhwU4IIz-bJ8pw2VMY&r=FPaI2vHFJWVzl-YOfxAezMqvfX2A2nlU4-YTdkTbsAI&m=pAVzmVmsdInpdZMphzWlMcUYag1-Y3OuBanDFDb3UGI&s=05YcPwInVWaGMU6_1EAX7tvwMvgFD26L6j4vER35eyQ&e=> . Triage notifications on the go with GitHub Mobile for iOS <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=ZD4UquQXZ0yA-RSlUqe8CfLnRLhwU4IIz-bJ8pw2VMY&r=FPaI2vHFJWVzl-YOfxAezMqvfX2A2nlU4-YTdkTbsAI&m=pAVzmVmsdInpdZMphzWlMcUYag1-Y3OuBanDFDb3UGI&s=ypCPQZTZ7eDb0e7LkKUNpjy2vgyXZO8At7Lr9bvuJIY&e=> or Android <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=ZD4UquQXZ0yA-RSlUqe8CfLnRLhwU4IIz-bJ8pw2VMY&r=FPaI2vHFJWVzl-YOfxAezMqvfX2A2nlU4-YTdkTbsAI&m=pAVzmVmsdInpdZMphzWlMcUYag1-Y3OuBanDFDb3UGI&s=uNOgfqvttf-yiHPBTc1_LcAkTnYuUg_oe1yYdGvJBBQ&e=> .

The first command is right, the second command you executed only gave you access to list nodes. I guess you need to try the first command again.
