### ISSUE TITLE
Typos in the explanation of the role of activeDeadlineSeconds in initContainers behaviour

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [kubernetes/website#29324]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior
```
Use activeDeadlineSeconds on the Pod to prevent init containers from failing forever. The active deadline includes init containers. However it is recommended to use activeDeadlineSeconds if user deploy their application as a Job, because activeDeadlineSeconds has an effect even after initContainer finished. The Pod which is already running correctly would be killed by activeDeadlineSeconds if you set.
```

**Proposed Solution:**
1. Change `However it is recommended` to `However it is NOT recommended`
2. Change `activeDeadlineSeconds if user deploy their application` to `activeDeadlineSeconds if the user deploys their application`
3. Change `an effect even after initContainer finished` to `an effect even after the init containers have finished`
4. Change `by activeDeadlineSeconds if you set.` to `by activeDeadlineSeconds if you set it.`

```
Use activeDeadlineSeconds on the Pod to prevent init containers from failing forever. The active deadline includes init containers. However it is NOT recommended to use activeDeadlineSeconds if the user deploys their application as a Job, because activeDeadlineSeconds has an effect even after the init containers have finished. The Pod which is already running correctly would be killed by activeDeadlineSeconds if you set it.
```
**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

**Comment by HarikrishnanBalagopal** [comment]
Closest issue I could fine related to this https://github.com/kubernetes/website/issues/28825

**Comment by sayantani11** [comment]
@HarikrishnanBalagopal Is the issue open? I would be happy to work on it. Thank you.

**Comment by sayantani11** [comment]
@HarikrishnanBalagopal Just a clarification. We only need to make the mentioned changes?

**Comment by RA489** [comment]
@HarikrishnanBalagopal Do you mind testing it on your local environment. I think the correct documentation is correct.

**Comment by s-kawamura-w664** [comment]
@HarikrishnanBalagopal @RA489 

> Use activeDeadlineSeconds on the Pod to prevent init containers from failing forever.
> However it is recommended to use activeDeadlineSeconds if user deploy their application as a Job,

Perhaps the words "Pod" and "Job" may have been misleading.
I think "Job" refers to a container that complete in a certain period. 
In other words, this explanation means the following.
The activeDeadlineSeconds is recommended to be use for containers (Pod) that complete after a certain period.
It should not be used for containers (Pod) that will run forever.

**Comment by s-kawamura-w664** [comment]
@HarikrishnanBalagopal 
I would suggest the following.
How about it?

before:
 `However it is recommended to use activeDeadlineSeconds if user deploy their application as a Job,`

after:
 `However it is recommended to use activeDeadlineSeconds only if user deploy their application as a Job,`

**Comment by RA489** [comment]
> @HarikrishnanBalagopal I would suggest the following. How about it?
> 
> before: `However it is recommended to use activeDeadlineSeconds if user deploy their application as a Job,`
> 
> after: `However it is recommended to use activeDeadlineSeconds only if user deploy their application as a Job,`

https://github.com/kubernetes/website/pull/29868
