### ISSUE TITLE
Broken link at Configure Liveness, Readiness and Startup Probes page

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes/website#29322]
Link at https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request it's broken 

The link at

> You can see the source code for the server in **server.go**

Points to https://github.com/kubernetes/kubernetes/blob/main/test/images/agnhost/liveness/server.go 

This is due to 
`https://github.com/kubernetes/kubernetes/blob/{{< param "githubbranch" >}}/test/images/agnhost/liveness/server.go` 

is Pointing to `main` due to `kubernetes/website` is using `main` but `kubernetes/kubernetes` is still using `master`

**Comment by mengjiao-liu** [comment]
PR #29311 is working on this issue to point to the correct address.
