### ISSUE TITLE
Volumes: broken links

### ISSUE THREAD

**Issue by circy9** [kubernetes/website#29321]
The links for "azureDisk volume plugin" and "azureFile volume plugin" are broken.

Current: https://github.com/kubernetes/examples/tree/main/staging/volumes/azure_disk/README.md
Should be: https://github.com/kubernetes/examples/tree/master/staging/volumes/azure_disk/README.md

**Comment by yuswift** [comment]
#29311 will fix it

**Comment by sftim** [comment]
Fixed in #29311 
/close
