### ISSUE TITLE
Specifying a Disruption Budget for your Application

### ISSUE THREAD

**Issue by edmondsw** [kubernetes/website#29333]
https://kubernetes.io/docs/tasks/run-application/configure-pdb/#before-you-begin says "Your Kubernetes server must be at or later than version v1.21" but that is not true for much of the content on this page. This is misleading.

**Comment by sftim** [comment]
Another option could be for somebody (with plenty of spare time) to improve the `feature-state` shortcode to generate that kind of advice automatically.
