### ISSUE TITLE
Update "multiple schedulers" examples

### ISSUE THREAD

**Issue by damemi** [kubernetes/website#29342]
**This is a Bug Report**
**Problem:**
The page for configuring multiple schedulers (https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#define-a-kubernetes-deployment-for-the-scheduler) includes references to the `--scheduler-name` flag, which is removed, and so the examples do not work.

**Proposed Solution:**
Scheduler name needs to be set via profiles now, so this page should be updated to show passing a `KubeSchedulerConfiguration` to the custom scheduler deployment via ConfigMap

**Page to Update:**
https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#define-a-kubernetes-deployment-for-the-scheduler

Kubernetes Version:
1.22+

Additional Information:
/sig scheduling
xref: https://github.com/kubernetes/kubernetes/pull/102805#issuecomment-897663042

**Comment by damemi** [comment]
@alculquicondor good catch thanks, description updated

**Comment by chirangaalwis** [comment]
@sftim I would like to work on this but TBH when I tried to get this to work, I experienced failures.

The discussion I had in Slack with regard to this ended abruptly with no responses for a few days (see https://kubernetes.slack.com/archives/C09TP78DV/p1633633243117000 in SIG Scheduling).

I would love to have some basic support for this so that I can try this out and I would be happy to update the doc.

**Comment by sftim** [comment]
Let's use this issue to track the original report - https://github.com/kubernetes/website/issues/29342#issue-968938470

@chirangaalwis I recommend that you request support by some other means - GitHub isn't the best place for that kind of request.

**Comment by chirangaalwis** [comment]
@alculquicondor 
> > But `my-scheduler` is not recognised although the workload is running fine.
> 
> Can you please be more explicit? What do you mean it's not recognized?

The Pods we schedule with the `.spec.schedulerName` set to `my-scheduler` do not get scheduled. They stay in `Pending` state. That is what I have meant by not recognised in the above case.

> The scheduler starts or not? Which workload is running fine? The scheduler or a pod that has the `schedulerName` set to `my-scheduler`?

@alculquicondor the scheduler starts. What I meant here was that the Deployment workload used to deploy the `my-scheduler` works fine.

**Comment by chirangaalwis** [comment]
@sftim @alculquicondor @damemi please find the details of the issue and the requested logs uploaded to SIG for Scheduling Slack channel [thread](https://kubernetes.slack.com/archives/C09TP78DV/p1634250620170400).

**Comment by chirangaalwis** [comment]
@damemi @alculquicondor we should be able to close this can't we?

This was covered some time back.

**Comment by alculquicondor** [comment]
Thanks!

**Comment by JingbenShi668** [comment]
> @alculquicondor
> 
> > > But `my-scheduler` is not recognised although the workload is running fine.
> > 
> > 
> > Can you please be more explicit? What do you mean it's not recognized?
> 
> The Pods we schedule with the `.spec.schedulerName` set to `my-scheduler` do not get scheduled. They stay in `Pending` state. That is what I have meant by not recognised in the above case.
> 
> > The scheduler starts or not? Which workload is running fine? The scheduler or a pod that has the `schedulerName` set to `my-scheduler`?
> 
> @alculquicondor the scheduler starts. What I meant here was that the Deployment workload used to deploy the `my-scheduler` works fine.

@chirangaalwis hi,  I also encountered  the problem now. The Deployment workload used to deploy the `my-scheduler` works fine. However, the Pods I schedule with the `.spec.schedulerName` set to `my-scheduler` do not get scheduled. They stay in `Pending` state.  Could you give me some advice? Thanks.
