### ISSUE TITLE
[hi] Localize content/en/docs/setup/best-practices/node-conformance.md to Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#29359]
This issue is a part of ongoing hi localization effort #29353

/language hi

**Comment by anubha-v-ardhan** [comment]
@ShivamTyagi12345 assign this to yourself using `/assign`

**Comment by ShivamTyagi12345** [comment]
/assign

getting started

**Comment by ShivamTyagi12345** [comment]
Made the local changes ,What next?

**Comment by anubha-v-ardhan** [comment]
@ShivamTyagi12345 Open a **draft pull request** to kubernetes/website. Do use the command `/language hi`

**Comment by anubha-v-ardhan** [comment]
we dropping the idea of individual issues
