### ISSUE TITLE
Updates for co-chair(s) to emeritus

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#29354]
This is a tracking issue to move @irvifa and @kbarnard10 to emeritus based on their own request. At this time there are no replacements but we have began announcing the transition and encouraging folks to step up. I plan on sending out an email to SIG Docs with a more direct call to action in the near future (/cc @parispittman).

## Required changes

Co-chair transitions to emeritus require some updates.

Repo | file | PR
---|---|---
k/community | [OWNERS_ALIASES](https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/community/pull/5949
k/community | [sig-docs/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/README.md) | https://github.com/kubernetes/community/pull/5949
k/community | [sig-docs/blog-subproject/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/blog-subproject/README.md) | https://github.com/kubernetes/community/pull/5949
k/community | [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md) | https://github.com/kubernetes/community/pull/5949
k/community | [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml) | https://github.com/kubernetes/community/pull/5949
k/enhancements | [OWNERS_ALIASES](https://github.com/kubernetes/enhancements/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/enhancements/pull/2859
k/org | [OWNERS_ALIASES](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/org/pull/2890
k/org | [config/kubernetes/sig-docs/teams.yaml](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml) | https://github.com/kubernetes/org/pull/2890
k/org | [config/kubernetes-sigs/sig-docs/teams.yaml](https://github.com/kubernetes/org/blob/master/config/kubernetes-sigs/sig-docs/teams.yaml) | https://github.com/kubernetes/org/pull/2890
k/website | [OWNERS](https://github.com/kubernetes/website/blob/master/OWNERS) | https://github.com/kubernetes/website/pull/29357
k/website | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/website/pull/29357
k/website | [SECURITY_CONTACTS](https://github.com/kubernetes/website/blob/master/SECURITY_CONTACTS) | https://github.com/kubernetes/website/pull/29357
k/k | [OWNERS_ALIASES](https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/kubernetes/pull/104355
k/test-infra | [OWNERS_ALIASES](https://github.com/kubernetes/test-infra/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/test-infra/pull/23240
k-sigs/reference-docs | [OWNERS](https://github.com/kubernetes-sigs/reference-docs/blob/master/OWNERS) | https://github.com/kubernetes-sigs/reference-docs/pull/252
k-sigs/reference-docs | [SECURITY_CONTACTS](https://github.com/kubernetes-sigs/reference-docs/blob/master/SECURITY_CONTACTS) | https://github.com/kubernetes-sigs/reference-docs/pull/252
k/k8s.io | [OWNERS_ALIASES](https://github.com/kubernetes/k8s.io/blob/master/OWNERS_ALIASES) | https://github.com/kubernetes/k8s.io/pull/2535

I would appreciate, but not require, a confirmation / "+1" from @irvifa and @kbarnard10 to demonstrate that I am not acting alone and this issue is opened in good faith for the sake of integrity & community.

### From @jimangel:

@kbarnard10 stepped into the co-chair role officially in [early 2020](https://github.com/kubernetes/website/issues/18117) and is a big reason the blog is as successful as it is today. Thank you for all you work and effort in making SIG Docs a great place to be!

@irvifa became co-chair later in [September of 2020](https://github.com/kubernetes/website/issues/23797) and brought an immense number of improvements to the localization efforts underway for SIG Docs, including a new monthly meeting dedicated to issues localizing documentation. Thank you!

/assign @kbhawkey @sftim @onlydole 
/sig docs

**Comment by sftim** [comment]
Thanks for many valuable contributions @kbarnard10 and @irvifa 
I see this as entirely in good faith.

**Comment by kbhawkey** [comment]
🦸‍♀️ @irvifa , @kbarnard10 🦸‍♀️ 
🎉 Thank you for your many contributions to Sig Docs.

**Comment by irvifa** [comment]
Hi all, thank you for your help and yes I’ll give my +1 for my part.

**Comment by geojaz** [comment]
@jimangel What does it take to get started as a docs reviewer in English?

**Comment by jimangel** [comment]
@geojaz! Nice to see you on the open source side of things! 😄 

If you're specifically asking about becoming a reviewer, check out our [roles and responsibilities](https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/) section of the [SIG Docs contributor guide](https://kubernetes.io/docs/contribute/).

I see you're already an org member, but that's traditionally the first recommendation. Details outlined [here](https://github.com/kubernetes/community/blob/master/community-membership.md#member).

Other than that, it's a matter of learning how the k8s docs work, attending meetings, and providing additional reviews (even if not assigned on the PR). Generally building a track record of providing reliable docs content / reviews. If you're new to docs, you can observe how others review PRs too.

Two YouTube videos I'd recommend for new contributors to docs:
* [Writing for Developers: Take your Project Docs to the Next Level - Celeste Horgan, CNCF](https://www.youtube.com/watch?v=vz_5EdhHrmI)
* [Intro to Kubernetes Docs - Celeste Horgan, Linux Foundation; Brad Topol, IBM; Tim Bannister](https://www.youtube.com/watch?v=pprMgmNzDcw)

If you're interested in contributing directly vs. reviewing, here is list of [good first issues](https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) (all localizations, not just English).

Lastly, pop into the `#SIG-Docs` slack channel and say "hey!"" It's a great place to ask any questions if you're looking for something to work on. Cheers!

**Comment by sftim** [comment]
Just waiting on https://github.com/kubernetes/test-infra/pull/23240 I think.

**Comment by sftim** [comment]
Done
/close

**Comment by BenTheElder** [comment]
Hmm seems prow missed the hook?
/close
