### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/namespaces/

### ISSUE THREAD

**Issue by balacc** [kubernetes/website#29351]
See namespace design under What's next? section returns 404.

**Comment by Shubham82** [comment]
Hi @balacc 
This issue will be resolved when the PR #29311 is merged.

**Comment by Shubham82** [comment]
Hi @reylejano 
This link is working now. It was fixed in the above PR #29311
We can close it now.

**Comment by reylejano** [comment]
Issue is fixed in PR https://github.com/kubernetes/website/pull/29311
/close
