### ISSUE TITLE
[hi] Localize content/en/docs/home/supported-doc-versions.md to Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#29356]
This issue is a part of ongoing `hi` localization effort #29353 

/language hi

**Comment by anubha-v-ardhan** [comment]
@verma-kunal  assign this to yourself using `/assign`

**Comment by verma-kunal** [comment]
Ready for a PR!! 👍

**Comment by anubha-v-ardhan** [comment]
we dropping the idea of individual issues
