### ISSUE TITLE
README.md in TAMIL TA

### ISSUE THREAD

**Issue by aasim-syed** [kubernetes/website#29379]
**This is a Feature Request**

I would like to contribute to README.md to translate to it in TAMIL

Its enhances people to learn more

**Comments**

**Comment by sftim** [comment]
Hi. Thanks for suggesting that improvement.

We'd accept a Tamil README if there were a new localization to Tamil.

https://kubernetes.io/docs/contribute/localization/#start-a-new-localization covers what people would need to do to start that off (you will need at least 1 collaborator).

**Comment by anubha-v-ardhan** [comment]
@aasim-syed Can we have an update. Are you starting a new localization to Tamil?
