### ISSUE TITLE
Issue with /docs/getting-started-guides/vsphere/

### ISSUE THREAD

**Issue by ahmusthafa** [kubernetes/website#2938]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

Is there a way to deploy K8s in VMware vCloud Director platform? Looks like GOVC is only for vCenter and doesn't support vCD.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmusthafa** [comment]
Feature request

**Comment by zacharysarah** [comment]
I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).
