### ISSUE TITLE
Volumes documentation missing NFS example

### ISSUE THREAD

**Issue by robotrapta** [kubernetes/website#29415]
In the NFS section of the Volumes doc page [https://kubernetes.io/docs/concepts/storage/volumes/#nfs](https://kubernetes.io/docs/concepts/storage/volumes/#nfs) there is no useful example, but only a link to ["NFS example"](https://github.com/kubernetes/examples/tree/main/staging/volumes/nfs) which links to [https://github.com/kubernetes/examples/tree/main/staging/volumes/nfs](https://github.com/kubernetes/examples/tree/main/staging/volumes/nfs) which is currently 404.

My recollection from trying to figure this out months ago was that the linked example code was not helpful because it was showing how to mount NFS using a PVC which is much more complicated than just directly mounting an NFS volume.  I believe this section is supposed to show the simple way of directly mounting an NFS volume without PV / PVC.  This technique is wonderfully simple, and last time I looked almost if not entirely undocumented.

**Comment by sftim** [comment]
The PR #29311 looks like it will restore the broken hyperlink.
