### ISSUE TITLE
Translate a Docker Compose File to Kubernetes Resources

### ISSUE THREAD

**Issue by kish0620** [kubernetes/website#29425]
When I run the curl command to install kompose, it tells me the exe is incompatible with the 64 bit version of windows. Do you know how I can fix this?

**Comment by sftim** [comment]
@kish0620 would you be willing to provide some more information?

- the command that you ran
- the error message that you saw
- the version of Windows you're running
- what CPU architecture your PC uses

That will help us work out how to revise that page.

/triage needs-information
/language en
/sig cli
