### ISSUE TITLE
Links for Azure File, Azure Disk etc. within the volumes documentation receive a 404

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [kubernetes/website#29422]
REF: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/storage/volumes.md

For example, Azure File is pointing to:

https://github.com/kubernetes/examples/tree/main/staging/volumes/azure_file/README.md

instead of

https://github.com/kubernetes/examples/blob/master/staging/volumes/azure_file/README.md

(there doesn't seem to be a "main" branch, only "master").

This is causing all of these links to fail at the moment

**Comment by mengjiao-liu** [comment]
https://github.com/kubernetes/website/pull/29311 work on it.

**Comment by sftim** [comment]
The canonical URL for that page is https://kubernetes.io/docs/concepts/storage/volumes/ @AdamSharif-MSFT 

I think this was fixed by #29311 - feel free to re-open if you still see symptoms.

/close
/triage duplicate
/language en
