### ISSUE TITLE
Katacoda environment not working for “Interactive Tutorial - Exploring Your App”

### ISSUE THREAD

**Issue by trungtranwata** [kubernetes/website#29427]
Kubernetes Bootcamp Terminal
This environment is no longer available.

CAN'T follow the tutorial, please fix.

**Comment by niteshseram** [comment]
Hi @trungtranwata, we have seen this issue before as well. I think it should be working if you refresh the page. Your session might have expired.

**Comment by trungtranwata** [comment]
Thank @niteshseram I will give it a try.

**Comment by sftim** [comment]
/retitle Katacoda environment not working for “Interactive Tutorial - Exploring Your App”

/priority awaiting-more-evidence
