### ISSUE TITLE
Create a Hugo layout to not display release information on older versions of k8s.io

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#29428]
## Problem

When a Kubernetes release happens, like 1.22, the now "old" site becomes a subdomain snapshot (ie: https://v1-21.docs.kubernetes.io/). This is great for archival purposes, however, if you navigate to the snapshot's release page (https://v1-21.docs.kubernetes.io/releases/) it is stuck at that point in time.

This problem exists because each older site is a branch. 1.21 is on the `release-1.21` branch.

## Solution

We should have a single source of truth (`main`) and all other subdomains should automatically point to the current documentation.

I would recommend adding a shortcode, much like we do to create the yellow box* on older pages. 

![image](https://user-images.githubusercontent.com/4601051/129661748-fbbe796f-ac4b-430b-8ec1-b343c93bda15.png)

## Pointers

The yellow box shortcode exists on all versions and branches of k/website, but is contingent on a hugo configuration value (set [here](https://github.com/kubernetes/website/blob/main/config.toml#L147)). For example:

- 1.22 on the `main` branch does not have the box appear and the config.toml is set to false (https://github.com/kubernetes/website/blob/main/config.toml#L147).
- 1.21 on the `release` branch does have the box appear and the config.toml is set to true (https://github.com/kubernetes/website/blob/release-1.21/config.toml#L147)

The bit of code that actually generates the parameter is in the following layout partial:
- https://github.com/kubernetes/website/blob/main/layouts/partials/deprecation-warning.html
```
{{ if (.Site.Param "deprecated") }}
<section id="deprecation-warning">
  <div class="content deprecation-warning">
    <h3>
      {{ T "deprecation_title" }} {{ .Param "version" }}
    </h3>
    <p> Kubernetes {{ .Param "version" }} {{ T "deprecation_warning" }}
      <a href="{{ site.Params.currentUrl }}">{{ T "latest_version" }}</a>
    </p>
  </div>
</section>
{{ end }}
```

The "T" before the value references using the translated strings that are localized in the relative language files. For example, the English translation is located [here](https://github.com/kubernetes/website/blob/main/data/i18n/en/en.toml).

For more information on the releases page and how it's made, check out the PR: https://github.com/kubernetes/website/pull/27929

This is a well scoped issue, but maybe slightly more advanced for a first issue. I will mark it as such either way.

/sig docs
/good-first-issue

**Comment by Divya063** [comment]
I would like to work on this. 
/assign

**Comment by sftim** [comment]
Would it be OK to redirect https://v1-21.docs.kubernetes.io/releases/ to https://kubernetes.io/releases/ ?

At the point we make a release we could commit in some extra redirects (for v1.21, that'd be retrospective).

**Comment by jimangel** [comment]
> Would it be OK to redirect https://v1-21.docs.kubernetes.io/releases/ to https://kubernetes.io/releases/ ?

I believe this would disrupt the assumed UX, "I _thought_ I was on the 1.21 docs" or the subsequent navigation. In addition, baking it into a shortcode similar to deprecations, there is no additional work for the docs release team.

I think that would be a fine solution short term though.

**Comment by sftim** [comment]
We could use a Hugo _layout_ rather than a shortcode for this. If we copy the way that the docs pages do that, I think that could work. Maybe with a tweak to say “release information” rather than “documentation”; maybe use shared wording but tweak it to be more neutral.

**Comment by jimangel** [comment]
> We could use a Hugo layout rather than a shortcode for this.

Absolutely. As mentioned in my description, I want to ensure the "things on the page" are of value to the reader.

What are columns vs. rows (sperated by OS? Arch? Binary? K8s version?) that provide impact. Another way of asking is, what value do folks get from downloadkubernetes that we can adapt within the limitations of Hugo?

Once we answer that, the solution can be 1 of 1,000 possibilities 😅

**Comment by jimangel** [comment]
Sorry, thought this was a reply to a different issue.

If we use a layout, we're still in the same problem of the release date contained on the branch never getting touched, right?

**Comment by sftim** [comment]
> If we use a layout, we're still in the same problem of the release data contained on the branch never getting touched, right?

That layout can have a conditional, “is this the current release?” and skip rendering part of the page if the answer is `false`.
(The yellow deprecation warning is actually a layout not a shortcode)

/retitle Create a Hugo layout to not display release information on older versions of k8s.io

As this has confused two experienced contributors(!) I'll leave this marked as Help Wanted but not as a good first issue.
/remove-good-first-issue

**Comment by sftim** [comment]
/reopen
I'd like to see this change happen.

**Comment by dipesh-rawat** [comment]
I'm happy to jump in and work on this issue to help move it forward.

/assign
