### ISSUE TITLE
Generating this site takes an alarming amount of resources.

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#29429]
Look into evaluating how we can make building the site take less memory / cpu.

## Problem

As `k/website` has grown, it went from a small hugo build to what it is today (a large, memory and file hungry build).

This is all good though, it means we are adding content and localizations.

## Solution

Look into ways to reduce build time. A few options come to mind:
- Can we remove a large chunk of unused content?
- Can we build only a small subset of docs (easily and portable to the various localizations)?
- Are there any optimizations in hugo itself?

There should be a way to reduce the amount of resources required to build `k/website`. Considering there isn't a clear solution, I won't mark as good-first-issue.

/sig docs
/triage accepted

**Comment by niteshseram** [comment]
Hi @jimangel, I tried doing [partialCached](https://gohugo.io/functions/partialcached/) for all the Partial templates. I think it improved the build time quite much. But I am not sure if it is recommended or not. Let me know it is okay to do _partialCached_ for all the partial templates.

**Comment by sftim** [comment]
Idea: run the build localization-by-localization. I don't know if Hugo supports this but if it might let us run 14 shorter builds (potentially in parallel) rather than 1 long one.

Idea: look for image resize options at build time. If reasonable to do so, replace the source image with what it gets resized to.

**Comment by sftim** [comment]
This might be an area where we could look for resources from CNCF to help with it - especially if the fix is applicable across multiple CNCF projects.
