### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-service-account/

### ISSUE THREAD

**Issue by sahsz123** [kubernetes/website#29438]
It appears that the correct syntax of ServiceAccount in the podspec section is:
spec:
      containers:
      - image: nginx
  **serviceAccount**: dashboard-sa
...
**instead of:
** serviceAccountName:

**Comment by sftim** [comment]
The `serviceAccount` field is [deprecated](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#deprecated)
/kind support
