### ISSUE TITLE
wrong link

### ISSUE THREAD

**Issue by 494846880** [kubernetes/website#29442]
**This is a Bug Report**

**Problem:**
the reference link is broken.
**Proposed Solution:**
should be fixed.
**Page to Update:**
https://github.com/kubernetes/website/blob/main/content/zh/docs/contribute/generate-ref-docs/_index.md

**Comment by yuswift** [comment]
The page is not broken. https://kubernetes.io/docs/contribute/generate-ref-docs/
It looks so strange...

**Comment by mengjiao-liu** [comment]
ref https://github.com/kubernetes/website/pull/29510#issuecomment-906899277

/close
feel free to open it again.
