### ISSUE TITLE
Upgrading kubeadm clusters v1.20

### ISSUE THREAD

**Issue by tpoland** [kubernetes/website#29467]
The documentation for upgrading from v1.19 to v1.20 have been overwritten by the instructions for upgrading from v1.21 to v1.22.

https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
there is an open PR to fix this:
https://github.com/kubernetes/website/pull/29009

issue:
https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

/close
