### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateless-application/guestbook/

### ISSUE THREAD

**Issue by RayMountaineer** [kubernetes/website#29483]
giving information about 
a) describing the reason of the .yaml files (eg: the ... deployment is for getting the image)
b) the selectors who connect the "components" together,
eg "hints for the selectors of the deployment.yaml": 
1.) spec:selector:matchLabels:app: redis is needed for ...
2.1) spec:template:metadata:labels:app: redis is needed for ...
2.2) spec:template:metadata:labels:role: leader is needed for ...
2.3) spec:template:metadata:labels:tier: backend is needed for ...
in comparison to the first labels:
3.1) metadata:labels:app: redis is needed for ...
3.2) metadata:labels:role: leader is needed for ...
3.3) metadata:labels:tier: backend is needed for ...

in conjunction with the selectors in the service.yaml
would be nice.

Perhaps, it would be better to add a set of examples to the:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
... and then simply add the links to these examples.

Now, I need to rely on 3rd party information like this:
https://medium.com/@zwhitchcox/matchlabels-labels-and-selectors-explained-in-detail-for-beginners-d421bdd05362

So, I now need to play around and test this and that - do I need all 3 key-value pairs matching? can I use different ones? is it a redis-thing? ... I have not started yet, but I do have more questions than I would have needed, don't I?

however: thank you guys for your service - you are helping humanity to build great things (even if the docs could be improved ;-) )

**Comment by sftim** [comment]
:+1: to adding some links to pages that add more context
