### ISSUE TITLE
README.md Turkish Translation 

### ISSUE THREAD

**Issue by ctnkaan** [kubernetes/website#29484]
**This is a Feature Request**

**What would you like to be added**
Turkish translation of the README.md file https://github.com/kubernetes/website#readme

**Why is this needed**
There is no Turkish translation.

**Comments**
Looking forward to contribute 😊

**Comment by sftim** [comment]
We'd be happy to add a new Turkish localization. We'd want to be confident that we can maintain what we merge though.

@ctnkaan here's what you (and other people) need to do to [start a new localization](https://kubernetes.io/docs/contribute/localization/#start-a-new-localization)

/hold

**Comment by ctnkaan** [comment]
Okay that makes sense. I will try to assemble a translation group and come back. 👍

**Comment by sftim** [comment]
/close
SIG Docs would welcome a new Turkish localization that met the minimum requirements.
