### ISSUE TITLE
Better documentation of local ephemeral storage

### ISSUE THREAD

**Issue by xhejtman** [kubernetes/website#29494]
I believe, documentation about where ephemeral-storage capacity is taken from should be improved.

none of these two pages
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage

states, that ephemeral-storage capacity is taken from a volume where kubelet --root-dir is. The latte page mentions that one can have two file systems but not mention it how exactly to configure this situation so that kubelet recognizes correctly local storage capacity.

I suggest to improove this text:
_The kubelet writes logs to files inside its configured log directory (/var/log by default); and has a base directory for other locally stored data (/var/lib/kubelet by default)._

_Typically, both /var/lib/kubelet and /var/log are on the system root filesystem, and the kubelet is designed with that layout in mind._

_Your node can have as many other filesystems, not used for Kubernetes, as you like._

to:
_The kubelet writes logs to files inside its configured log directory (/var/log by default); and has a base directory for other locally stored data (/var/lib/kubelet by default)._ **Capacity of file system hosting the base directory is projected to ephemeral-storage resource.**

_Typically, both /var/lib/kubelet and /var/log are on the system root filesystem, and the kubelet is designed with that layout in mind._

_Your node can have as many other filesystems, not used for Kubernetes, as you like._

Not sure about the case of two file systems, how do they suppose to work.

**Comment by Kartik494** [comment]
Hi @xhejtman  i have a question regarding this, is it necessary to highlight to capacity of file system hosting the base directory? It is stated [here](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#types-of-ephemeral-volumes)  that `storage coming locally from the kubelet base directory (usually the root disk) or RAM`

**Comment by Kartik494** [comment]
so if i am not wrong here you want to propose idea that ephemeral-storage should not take capacity of kubelet base directory?

**Comment by xhejtman** [comment]
Well, it depends, maybe an option where to take ephemeral-storage capacity from would be a good way. In mean time, I propose to more clearly document that the capacity (not just storage but storage capacity of `ephemeral-storage` resource) is taken from kubelet directory.

**Comment by Kartik494** [comment]
i am not so sure on that proposal , but we can take a look for documentation modification for the same
