### ISSUE TITLE
Specifying a Disruption Budget for your Application

### ISSUE THREAD

**Issue by shivrajjadhav733** [kubernetes/website#29496]
How to delete pdb if there is no matching pod found?

**Comment by yuswift** [comment]
kubectl delete pdb -n foo

**Comment by sftim** [comment]
/kind support
I think

**Comment by borkod** [comment]
@shivrajjadhav733 How are you creating your pod and pdb?

If you're creating your pods using a deployment, you can put your pdb into the same YAML file as your deployment. When creating the resources you then provide the file name:

`kubectl create -f myapp.yaml`

You can then use the file to remove the resources:

`kubectl delete -f myapp.yaml`

Another alternative approach is to provide the same labels to all your resources and then use the labels to delete them together.

There is no "automated" way to trigger a deletion of pdb if the only action is a deletion of a pod (as far as I am aware). You would have to build some sort of custom implementation to do that.

Hope this helps.
