### ISSUE TITLE
Query about Web UI (Dashboard) task and HTTPS

### ISSUE THREAD

**Issue by n2vo** [kubernetes/website#29508]
The URL should NOT include the "https", methinks?  I had an issue access the kubernetes-dashboard using the link as documented in the page: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/.  After some fiddling around, I removed the "https" and was able to access it.  If this is incorrect, please ignore.

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:https/proxy/

**Comment by sftim** [comment]
/retitle Query about Web UI (Dashboard) task and HTTPS

**Comment by tylerauerbeck** [comment]
@n2vo This may be along the lines of what you were saying, but i think it needs to be something like this:

http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/

Is that what you're seeing? Or are you saying that it only works for you when you remove both `https` ?

**Comment by n2vo** [comment]
Hi Tyler,

Yes, the second "https" needs to be removed.  Sorry if I wasn't clearer in
the original report.

N2--

Anh Thu (N2) Vo
***@***.***
***@***.***
408-218-0002 (mobile)

**Comment by jihoon-seo** [comment]
This issue seems okay to be closed since the PR #29526 is merged.

**Comment by n2vo** [comment]
Agreed, tried following the new doc page today with the corrected link.  It worked!  👍
