### ISSUE TITLE
Rename product security committee

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29512]
**This is a Feature Request**

**What would you like to be change**
We should find the term “product security committee” anywhere within the English-language docs, and replace that term with “security response committee”.
We don't need to revise any blog articles. If we feel there are some blog articles where an exception is justified, I'd revise those in a separate PR per article as the review process is different.

**Why is this needed**
https://github.com/kubernetes/community/pull/5597 renamed the product security committee to “Security Response Committee”

**Comments**
/language en
/sig docs
/sig security
/help
/triage accepted
Relevant to https://github.com/kubernetes/security/pull/128

**Comment by lukehinds** [comment]
thanks @sftim , PR's are incoming org wide for the change.

**Comment by niteshseram** [comment]
I would like to take this up
/assign
