### ISSUE TITLE
[hi] Fix README-hi.md

### ISSUE THREAD

**Issue by AvineshTripathi** [kubernetes/website#29519]
Problem: 
The sentence below in the README-hi.md seems to be incomplete 

"अपने fork में कोई भी परिवर्तन करना चाहते हैं, और जब आप उन परिवर्तनों को हमारे पास भेजने के लिए तैयार हों, तो अपने fork पर जाएं और हमें इसके बारे में बताने के लिए एक नया pull request बनाएं।"
 the first part i.e "अपने fork में कोई भी परिवर्तन करना चाहते हैं" makes no proper connection with the other part

**Comment by anubha-v-ardhan** [comment]
We would like to have better sentence structure. What solution do you recommend?

**Comment by AvineshTripathi** [comment]
I think starting the statement with " इस fork में आप अपने इच्छा अनुसार परिवर्तन कर सकते है  " would sound more correct as well as it would go with the flow with the entire statement

**Comment by anubha-v-ardhan** [comment]
We need to mean the same as `Make any changes you want in your fork, and when you are ready to send those changes to us, go to your fork and create a new pull request to let us know about it.`

**Comment by AvineshTripathi** [comment]
अपने fork में कोई भी परिवर्तन करना चाहते हैं (existing one) -> this means "want to make any changes to your fork" which is a kind of question to user while we want to convey a assertive sentence that developers can make changes to their fork if you get what I mean

**Comment by anubha-v-ardhan** [comment]
Exactly, we need to mean `want to make any changes to your fork`. You can refer the `en` version I stated above.

**Comment by AvineshTripathi** [comment]
"want to make any changes to your fork, and when you are ready to send those changes to us, go to your fork and create a new pull request to let us know about it. " this is what the (hi) translation sounds to me I guess that is abrupt

**Comment by anubha-v-ardhan** [comment]
How about `अपने fork के परिवर्तन करने के बाद जब आप उनको हमारे पास भेजने के लिए तैयार हों, तो अपने fork पर जाएं और हमें इसके बारे में बताने के लिए एक नया pull request बनाएं`

**Comment by AvineshTripathi** [comment]
perfect to me

**Comment by anubha-v-ardhan** [comment]
Thanks

**Comment by AvineshTripathi** [comment]
if you want you can go with your PR

**Comment by anubha-v-ardhan** [comment]
Why did you unassign. You can make a PR, else this could be a `good-first-issue` with some tweaks to issue description.

**Comment by anubha-v-ardhan** [comment]
You need to PR to https://github.com/kubernetes/website for things to change here.
/reopen
