### ISSUE TITLE
Bug: Upgrading kubeadm clusters

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/website#29520]
Hello,

all the older sites like https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ show the update process up to 1.22 .

I have expected that I find 1.20 -> 1.21 , for example

**Comment by neolit123** [comment]
this is a duplicate of:
https://github.com/kubernetes/website/issues/27525

there is a PR in progress to fix it, but merging it is a bit complicated.

/sig cluster-lifecycle
/close
