### ISSUE TITLE
Document effects on secrets when memory swap is enabled in 1.22+

### ISSUE THREAD

**Issue by ritazh** [kubernetes/website#29524]
**This is a Feature Request**

**What would you like to be added**

Add a warning for when memory swap feature is turned on, then kubernetes secrets that was written to tmpfs could be swapped to write to disk.
https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory

**Why is this needed**
This security risk should be documented so users are aware of the impact before turning on the alpha feature.

**Comments**

xref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/707
cc @tomhjp

**Comment by sftim** [comment]
/sig security
/sig node

We're usually sanguine about not documenting security concerns in full for alpha features (we label the feature as alpha and intend that as a strong hint it's unfinished). We should document this for beta. What I would typically do is run with swap backed by an encrypted file or block device.

**Comment by abhibhaw** [comment]
Hey, I am new to the community and interested in contributing.
Can I work on this issue?

**Comment by sftim** [comment]
_Anyone_ who signs the CLA is welcome to work on any issue in this Kubernetes repo.

**Comment by abhibhaw** [comment]
Thanks, @sftim, for the assistance. Can I get some resources that can help me better understand what all and where I need to add?

**Comment by abhibhaw** [comment]
![swap](https://user-images.githubusercontent.com/39991296/132586193-85fec700-4fc5-4426-ab69-6e17a60f90cb.png)
Hey @sftim @ritazh was this all needed to be done? Should I send a PR?

**Comment by sftim** [comment]
Done in https://github.com/kubernetes/website/pull/29663
/close
