### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by mlromramse** [kubernetes/website#29523]
The link to the dashboard has an additional ``:https`` part at the end of the service name making the link not working.

E.g. This link works: ``http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/``

**Comment by niteshseram** [comment]
Same issue #29508
/language en

**Comment by mlromramse** [comment]
You're welcome!

Den tis 24 aug. 2021 kl 20:26 skrev Nitesh Seram ***@***.***>:

**Comment by jihoon-seo** [comment]
This issue seems okay to be closed since the PR #29526 is merged.
