### ISSUE TITLE
Wrong "What's next" links in portuguese section

### ISSUE THREAD

**Issue by gabrielalbino** [kubernetes/website#29522]
**This is a Bug Report**

**Problem:**
Links in portuguese section "What's next" are forwarding to english section, even if the page is avaliable in portuguese, harming the user reading experience.
eg.: In "What's next" section of [portuguese "What is kubernetes" page](https://kubernetes.io/pt-br/docs/concepts/overview/what-is-kubernetes/), the link "Dê uma olhada em Componentes do Kubernetes." is forwarding to [the english page](https://kubernetes.io/docs/concepts/overview/components/) instead [the portuguese one](https://kubernetes.io/pt-br/docs/concepts/overview/components/).

Something to keep in mind: many in-text links will need update as translation grows, is there a way to make this reference update less laborious?

**Proposed Solution:**
- Update already translated references 
- Make "update references" an acceptance criteria
**Page to Update:**
https://kubernetes.io/pt-br/docs/concepts/overview/what-is-kubernetes/

/language pt

**Comment by AayushSaini101** [comment]
Can i work on this issue..

**Comment by neha200** [comment]
can i work on this issue?

**Comment by anshkhandelwal12** [comment]
I think no one was working on this issue so I can work on this issue

**Comment by jihoon-seo** [comment]
This issue will be resolved if the PR #29581 by @SwapnaneelChowdhury is merged.
/assign @SwapnaneelChowdhury

**Comment by jihoon-seo** [comment]
This issue is resolved by the PR #29581.
/close
