### ISSUE TITLE
Inaccurate advice in “Exposing Your App” interactive tutorial

### ISSUE THREAD

**Issue by yyy1000** [kubernetes/website#29530]
In this module, Step 1 Create a new service
there saying that: (minikube does not support the LoadBalancer option yet).
However, I have tested that minikube has supported the LoadBalancer option.
So I think that the docs can be revised.

**Comment by sftim** [comment]
/retitle Inaccurate advice in “Exposing Your App” interactive tutorial
/kind bug
/language en
/triage accepted
