### ISSUE TITLE
Blog organization inconsistencies

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#29557]
**This is a Request for Discussion**

**What would you like to be changed**

Currently there appears to be 2 ways to organize blog posts and their associated files:
1. The post is added as a single file in `/content/en/blog/_posts`, formatted as `<date>-<blog name>.md`. Any supplementary content is added to `/static/images/blog` (usually, but not always, in a subfolder refering to the `<date>-<blog name>` blog post). 
2. The post is added as a folder in `/content/en/blog/_posts`, formatted as `<date>-<blog name>`, with an `index.md` file with in it along side any supplementary content (images, etc.).

There may be other ways of organizing that I've not picked up on.

Some questions:
* Is it OK to have 2 methods? 
* Is there a preferred way to organize blog entries?
* Do we translate blog posts? If so, is there an organization that works well for localizers?

If one method is preferred, then we might add an image to the [blog-post archetype](https://github.com/kubernetes/website/blob/main/archetypes/blog-post.md) and update the _[Submitting blog posts and case studies page](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/)_ to illustrate how to organize a blog post.

**Comment by sftim** [comment]
> -  Is it OK to have 2 methods?

IMO yes

> -  Is there a preferred way to organize blog entries?

For my part: no strong opinion. The existing loose conventions seem OK. I don't mind changing away from them. I do like that there's a basic attempt at rigor / consistency.

**Comment by nate-double-u** [comment]
I think we can close this now.
