### ISSUE TITLE
[ko] Translate docs/tasks/administer-cluster/sysctl-cluster.md in Korean

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#29560]
**This is a Feature Request**
Translate [docs/tasks/administer-cluster/sysctl-cluster.md](https://github.com/kubernetes/website/blob/dev-1.22-ko.1/content/en/docs/tasks/administer-cluster/sysctl-cluster.md) in Korean

**What would you like to be added**

Translate [docs/tasks/administer-cluster/sysctl-cluster.md](https://github.com/kubernetes/website/blob/dev-1.22-ko.1/content/en/docs/tasks/administer-cluster/sysctl-cluster.md) in Korean

**Why is this needed**

This file is not translated yet.

**Comments**

[https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/)

/language ko

**Comment by imoisharma** [comment]
Hi @ClaudiaJKang, I am happy to do this task. Is there any doc I can follow for transitioning the above link to ko lang?

**Comment by ClaudiaJKang** [comment]
@imoisharma Hi. I am working on this issue. Currently, there is no doc related to this issue.

**Comment by jihoon-seo** [comment]
Translated page:
https://kubernetes.io/ko/docs/tasks/administer-cluster/sysctl-cluster/

Related PRs:
- #30010
- #30412

/close
