### ISSUE TITLE
Weirdness with kubernetes.io/docs navigation

### ISSUE THREAD

**Issue by 3n-mb** [kubernetes/website#29578]
Verbatim from http://kwlug.org/pipermail/kwlug-disc_kwlug.org/2021-August/020588.html

I just had a huge relief in noticing weirdness/quirk in kubernetes.io/docs that breaks expected behaviour of content outline tree.

When you look at any other normal docs, e.g. Docker, SaltStack, on the side you have this tree form of content that expands and shows you where you are. And since docs are packaged with some logic, related to structure of the subject, such outline helps, and apparently subconscious mind gets used to this "map" of concepts in territory you explore at the moment.

So, in kubernetes.io/docs, when you go in depth, deep enough, 4th, or even just 3rd layer deep may remove from the content tree siblings of a parent. To this moment this has always been creating a feeling of confusion to me. Now I understand that this hiding has been messing up with my territory tracking, creating a feeling of being lost, being dumb, and I really don't appreciate such feelings. I really thought that I have constantly been thrown into a different part of the site, from which I won't find a way back.

If you feel lost in k8s docs, it might be this. When you notice it rationally, scare stops.

If you can, please change this behavior to be consistent with everywhere else.

**Comment by sftim** [comment]
/area web-development

The next Kubernetes release (v1.24) should bring some improvements in this area.
