### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

### ISSUE THREAD

**Issue by dfisher1** [kubernetes/website#29588]
The tutorial refers to the path: sample-kubernetes-config/start/

There is no such folder on my machine, nor is the file kubernetes.yaml to be found anywhere on my system.

I have installed minikube 1.20.0 and Oracle VM VirtualBox  6.1.26 r145957 (Qt5.6.2) on Windows 10

Is there something else I need to install that is not mentioned in the tutorial?

**Comment by shannonxtreme** [comment]
The interactive tutorial uses an existing Katacoda environment. File paths are relative to the remote, not to your local machine.
