### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by rajeev2509** [kubernetes/website#29596]
Draining a node is discussed in doc after master node upgrade. Master node HA is not considered here hence draining the master node should have come in picture much before. doc is confusing....

**Comment by neolit123** [comment]
hello, i don't think the page is that confusing.

the page has two main sections, as you can see:
- Upgrading control plane nodes
- Upgrading worker nodes

draining a node is a necessary step before upgrading a kubelet on a node for all node types.
for control plane nodes it is done *after* calling "kubeadm upgrade ..." on all of them.

> doc is confusing....

do you have any improvements in mind?

/sig cluster-lifecycle
/kind support
/triage needs-information

**Comment by neolit123** [comment]
/close
Please reopen if the above Qs are answered.
