### ISSUE TITLE
Kubernetes Deprecation Policy page lists wrong release cadence

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#29591]
In k8s document page: https://kubernetes.io/docs/reference/using-api/deprecation-policy/

Second paragraph below Rule #4b says:

All of this is best illustrated by examples. Imagine a Kubernetes release, version X, which introduces a new API group. **A new Kubernetes release is made every approximately 3 months (4 per year).**

It should say:

All of this is best illustrated by examples. Imagine a Kubernetes release, version X, which introduces a new API group. A new Kubernetes release is made every approximately **4 months (3 per year)**.

**Comment by sftim** [comment]
/kind bug
/retitle Kubernetes Deprecation Policy page lists wrong release cadence
/language en
/help
/priority backlog
/triage accepted

Thanks for the report.

**Comment by bhumijgupta** [comment]
I would like to pick this up
/assign
