### ISSUE TITLE
Typo in a sample manifest

### ISSUE THREAD

**Issue by demonCoder95** [kubernetes/website#29597]
**This is a Bug Report**

**Problem:**
In the blog titled ``OPA Gatekeeper: Policy and Governance for Kubernetes``, a sample manifest is provided for a ``ConstraintTemplate``. This blog is in the file ``content/en/blog/_posts/2019-08-06-OPA-Gatekeeper-Policy-and-Governance-for-Kubernetes.md``

The ``spec.targets[].rego`` provides a rule named ``deny`` and when applied, the GateKeeper admission controller rejects the object with the error:
``` bash
Error from server (Invalid rego: 
Missing required rule: violation): error when creating "k8s-labels-template.yaml": admission webhook "validation.gatekeeper.sh" denied the request: Invalid rego: 
Missing required rule: violation
```

**Proposed Solution:**
The solution is to replace the keyword ``deny`` with ``violation`` to rename the rule appropriately for the admission controller. This fixes the problem as I've tested it.

**Page to Update:**
https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/

Kubernetes API ``v1.21.0``

GateKeeper manifest for ``GateKeeper 3.3``

I can send a quick PR for the fix, if required.

**Comment by demonCoder95** [comment]
If I can be given membership of the org, I can hunt down more such typos and triage my issues to expedite patching. Let me know if this helps :)

**Comment by tengqm** [comment]
@demonCoder95 Org membership should not be a blocker for any contributors. See [getting started](https://kubernetes.io/docs/contribute/#getting-started).

**Comment by demonCoder95** [comment]
@tengqm I was just mentioning it, so that I can add triaged tags for myself with typos like these that I may find in the future. Thanks for the help! I'll send a short patch right away to fix this thing.
