### ISSUE TITLE
Kubernetes Components

### ISSUE THREAD

**Issue by AvineshTripathi** [kubernetes/website#29602]
The image seems to be small and reading it is quite difficult can we have an image that is more readable than current existing one

![Screenshot from 2021-09-02 10-44-16](https://user-images.githubusercontent.com/73980067/131785746-9f273448-121f-492a-a4cb-7afd70cb2b25.png)

**Comment by tengqm** [comment]
Agree. Looks to me like some unknown islands in the Pacific ocean. There are other diagrams which have the same problems.

**Comment by niteshseram** [comment]
Similar issue #29340

**Comment by AvineshTripathi** [comment]
#29340
