### ISSUE TITLE
Module 2 - Interactive terminal hanging and not allow enter anything after using shortcuts from module or if i open secondary terminal

### ISSUE THREAD

**Issue by comdiv** [kubernetes/website#29611]
1. Open module 2 
2. wait it starting kube ctl
3. try write something - all ok
4. try open secondary terminal/ or click shortcut in module text
5. it will be opened or executed
6. but after it it does not listening to keyboard anymore

**Comment by sftim** [comment]
Hi @comdiv 

Can you also mention the URL of the web page that you were accessing when you encountered problems?
