### ISSUE TITLE
Incorrect statement in “Exposing Your App” interactive tutorial

### ISSUE THREAD

**Issue by psvensson** [kubernetes/website#29618]
The output of the 'kubectl get services' command does not display an external IP, in contrast to the statement just after,

"We have now a running Service called kubernetes-bootcamp. Here we see that the Service received a unique cluster-IP, an internal port and an external-IP (the IP of the Node)."

This leaves the laborator a bit confused and make learning a bit harder than I think was intended

**Comment by sftim** [comment]
/kind bug
/retitle Incorrect statement in “Exposing Your App” interactive tutorial
/triage accepted
/priority backlog
