### ISSUE TITLE
kubernetes.io/change-cause annotation not listed

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29633]
**This is a Bug Report**

**Problem:** 
[Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) doesn't mention the annotation `kubernetes.io/change-cause`.

**Proposed Solution:**
Add `kubernetes.io/change-cause` to the list. If it's deprecated, add it but with a note to say that it's deprecated.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig cli
/lifecycle frozen
The `kubectl` tool used to set this annotation on some objects.

**Comment by CIPHERTron** [comment]
> kubernetes.io/change-cause

@sftim how to know if `kubernetes.io/change-cause` is deprecated or not?

**Comment by mehabhalodiya** [comment]
/triage accepted

Closing this issue as https://github.com/kubernetes/website/pull/29896 is already merged!
/close
