### ISSUE TITLE
Issue with /docs/user-guide/walkthrough/

### ISSUE THREAD

**Issue by rriouxr** [kubernetes/website#2963]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
After following instructions, when trying to deploy a pod i get the following:
[root@km01 nginx]# kubectl create -f pod-nginx.yaml
Error from server (ServerTimeout): error when creating "pod-nginx.yaml": No API token found for service account "default", retry after the token is automatically created and added to the service account

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

kubernetes-master-1.5.2-0.2.gitc55cf2b.el7.x86_64
kubernetes-client-1.5.2-0.2.gitc55cf2b.el7.x86_64
kubernetes-1.5.2-0.2.gitc55cf2b.el7.x86_64
kubernetes-node-1.5.2-0.2.gitc55cf2b.el7.x86_64

[root@km01 nginx]# uname -a
Linux km01.home.local 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@km01 nginx]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

Tried repo from the document first, then stock centos repo, both had exact same results.

**Comment by zacharysarah** [comment]
@rriouxr Are you still experiencing this issue?

**Comment by rriouxr** [comment]
> @rriouxr Are you still experiencing this issue?

Honesty I moved on from the issue. I believe I switched OS'es ...
