### ISSUE TITLE
notifying localization teams when changes are made

### ISSUE THREAD

**Issue by RinkiyaKeDad** [kubernetes/website#29649]
**This is a Feature Request**

**What would you like to be added**

A way to notify the downstream localization teams whenever we make any major updates to documentation. 

**Why is this needed**

This originated from a discussion in the SIG Docs meeting on [7th September 2021](https://docs.google.com/document/d/1ddHwLK3kUMX1wVFIwlksjTk0MsqitBnWPe1LRa1Rx5A/edit?usp=sharing). PRs making large changes pose huge challenges to the localization teams. We need a way to notify localization teams of such changes (possibly even before the PR is merged) so that folks are prepared for big changes.

**Comments**

See [#29385 (comment)](https://github.com/kubernetes/website/pull/29385#issuecomment-907544228).

**Comment by AvineshTripathi** [comment]
maybe we can have a label to the PR that would notify other teams about the major change

**Comment by shannonxtreme** [comment]
Is there a way to configure the bot to add sig docs-localization to any L PRs and higher?

**Comment by AvineshTripathi** [comment]
> Is there a way to configure the bot to add sig docs-localization to any L PRs and higher?

I had a thought of the same but the thing is how  would the bot notify the team . I think we can assign a particular label on response the bot would tag the head of the teams or members of the teams

**Comment by mbbroberg** [comment]
I just spoke with @AvineshTripathi -- it'd be great to see the specifics of what the bot would do and when, then we could get help from infra to see the next steps forward.

**Comment by AvineshTripathi** [comment]
@mbbroberg maybe we can have a special label for this which would be given by reviewer and in response to that bot would tag the members of the localization teams. The label thing can be done automatically but for that we need to have a threshold point beyond which we can say the change is major but I m not sure if we can have that threshold number so doing it manually would be better still if there is another solution we can have a discussion surly

**Comment by shannonxtreme** [comment]
@AvineshTripathi for the threshold, could we use the PR size? Like, localization teams get tagged for <size> PRs or larger, since the bot already has that functionality? Worth discussing at tomorrow's async Slack meeting, along with other feedback from our localizers (idk if that's the right word)

**Comment by AvineshTripathi** [comment]
@shannonxtreme  definately we can have size as a parameter but the question remains same what can the size after which the bot should notify

**Comment by shannonxtreme** [comment]
@AvineshTripathi Yep that's what I meant when I said we should discuss it at the async meeting on Slack on the 21st. Added to the [agenda](https://docs.google.com/document/d/1ddHwLK3kUMX1wVFIwlksjTk0MsqitBnWPe1LRa1Rx5A/edit)

**Comment by AvineshTripathi** [comment]
@shannonxtreme i couldn't attend the meeting can you tell me the summary of discussion happened for this issue ?

**Comment by reylejano** [comment]
During the SIG Docs on Sept 21 (APAC friendly meeting), we discussed creating a new label for `re-factor` which helps identifies PRs that makes large re-factoring changes e.g. removing files and moving content from one page to another

**Comment by AvineshTripathi** [comment]
@reylejano are we going to automate it (labelling) or do the labelling manually ?

**Comment by shannonxtreme** [comment]
Rey that's a good start for sure. In addition to Avinesh's question, how would we ensure that this label would mean localization folks are informed? Would the bot add the loc leads to CC on `refactor` labelled PRs?

**Comment by reylejano** [comment]
@AvineshTripathi and @shannonxtreme all good questions. 
I believe it will be manual at first but we should look into automating
IMO, localization teams and reviewers should be informed about PRs with a `re-factor`/`refactor` label.
More discussion is needed either on this issue, SIG Docs meeting, or Slack thread.

**Comment by sftim** [comment]
I think it'd have to be manual: automation can't spot a refactor easily (and if it could, we wouldn't need the label, we could update the tooling that localization teams use to use that algorithm directly).

**Comment by AvineshTripathi** [comment]
Ya I agree to that @sftim   and also @reylejano  are we planning to tag people of localisation team via bot or just having a label will do ?

**Comment by shannonxtreme** [comment]
> Ya I agree to that @sftim and also @shannonxtreme what is CC??

I meant tagging the relevant team in a Github comment on that PR (something like `cc @kubernetes/sig-architecture-leads` 

And yes manual works to start off at least.

**Comment by AvineshTripathi** [comment]
Sounds perfect to me @shannonxtreme let me know how to start working on this

**Comment by AvineshTripathi** [comment]
Hey everyone sorry for not being able to solve the issue till now, I am giving a another try and hopefully completing the entire job. @shannonxtreme @sftim @reylejano  I wanted to know if for this issue we are looking for a periodic job done by the bot or we are expecting a general prow job for this issue PS: I am new so I might need some help

**Comment by shannonxtreme** [comment]
The question here is do we want to block this issue from being closed because we want automation? 

I think we are good to close this - we have the `refactor` label, and triage folks are using it where needed. @reylejano if you agree, please close :)

**Comment by sftim** [comment]
I'm also :+1: to closing this issue.

**Comment by shannonxtreme** [comment]
This issue is donezo

/close
