### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/

### ISSUE THREAD

**Issue by n-hebert** [kubernetes/website#29641]
Please provide links on the 'Before you begin' section, teaching how to 'have dynamic PersistentVolume provisioner with a default StorageClass'.

I'm quite new to K8s and am not sure how to verify if I have the former half of this sentence, and the latter end of it (static provisioning) looks less automated / more difficult.

**Comment by n-hebert** [comment]
Seems like it could just link here: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

**Comment by sftim** [comment]
If anyone does work on this, it's easier to review PRs that only touch a _single_ localization.

**Comment by AvineshTripathi** [comment]
@sftim  do we have any section on dynamic PersistentVolume provisioner with a default StorageClass ?

**Comment by sftim** [comment]
Let's open that question up - anyone who wants to answer it is welcome to.
