### ISSUE TITLE
Issue with k8s.io/docs/tutorials/hello-minikube/ - Connecting to hello-node service didn't work

### ISSUE THREAD

**Issue by emschwartz** [kubernetes/website#29654]
During the `Create a Service` part of the tutorial, I was not able to connect to the `hello-node` service. The port generated was `31275` but when I tried to view that port on the host, it would try to connect and then show the error message `Unable to connect to Port 31275.`

**Comment by sftim** [comment]
Hi @emschwartz 

Were you using Minikube via the web page (Katacoda) or running Minikube on your own PC?
/language en

**Comment by emschwartz** [comment]
Via Katacoda

>

**Comment by sftim** [comment]
I ran through https://kubernetes.io/docs/tutorials/hello-minikube/ and all the steps were correct for me. There is room to make the explanation more clear for a reader.

/triage not-reproducible

@emschwartz if you wanted to, you could file an issue to make clear any parts of that page that you think are particularly confusing.

/close
