### ISSUE TITLE
Extend “Hello Minikube” tutorial to include accessing metrics server

### ISSUE THREAD

**Issue by emschwartz** [kubernetes/website#29655]
Under the `Enable addons` section, it would be nice to try connecting to the metrics server to see what it says (or link to some other documentation page about that specific service) before disabling that add-on.

**Comment by sftim** [comment]
/languge en
/kind feature

/retitle Extend “Hello Minikube” tutorial to include accessing metrics server

**Comment by sftim** [comment]
@emschwartz: could you outline the benefit to readers from making this change? That'll help folks to prioritize the work.

**Comment by emschwartz** [comment]
Hi @sftim,

That section of the tutorial describes how to enable and disable add-ons. If you're going through and following each of the steps, it seems a bit odd to be told "enable this add-on", "check that it's running" (using logs that at this point in the tutorial I only somewhat grok), and then "disable it", without seeing what the add-on actually does. It's pretty obvious from the name of the example add-on (`metrics-server`) what it does, but as someone who's new to kubernetes, I'm not entirely sure how to interact with it.

In other places in the main tutorial, it tells you to run a `curl` command against services when you spin them up (in addition to viewing what's running using `kubectl` commands) to show that the service is indeed there. As a new user, I believe it a bit more when I run the `curl` command than just taking `kubectl` at its word that the service listed as running or the add-on listed as enabled is actually doing something.

Hope that helps,
Evan

**Comment by sftim** [comment]
Maybe we could hyperlink away to a page about trying each add-on, so the option's there for folks who might be interested?

**Comment by sftim** [comment]
Despite https://github.com/kubernetes/website/issues/29655#issuecomment-920549060, I don't think this issue is one we'd prioritise.

Maybe if more contributors have time to work on things, we could revisit that decision.

/close
