### ISSUE TITLE
Refactor proposal for `kubernetes.io/community` page CSS styles

### ISSUE THREAD

**Issue by CIPHERTron** [kubernetes/website#29667]
**This is an Enhancement Request**
This is a proposal to refactor the CSS styles for the `kubernetes.io/community` page.

**What would you like to be added**

The [kubernetes.io/community](https://kubernetes.io/community/) page has many repeated CSS styles, it has both inline styles added as well as styles added in a separate [CSS file](https://github.com/kubernetes/website/blob/main/static/css/newcommunity.css). I don't have any idea about the rest of the pages but I've worked on an issue in the `kubernetes.io/community` page. I have gone through the styles and can say that it needs to be refactored.
For instance: 
* using flexbox or grids in place of float for defining the layout of elements
* removing extra media queries that have been applied in many cases
* removal of unused CSS, separating CSS & HTML i.e. migrating all inline CSS styles to `static/css/newcommunity.css`
* Applying best practices that can reduce the code to a greater extent

**Why is this needed**
Doing this will help us track styles in a single place itself. There will be no overlapping of styles which at times causes confusion because inline CSS has a high priority over CSS applied in a separate CSS file i.e. the inline CSS will be applied instead of the external CSS. Not only this, the CSS file will be half the number of lines it has right now if written by following the best practices.

**Comments**

Also, if this issue is accepted then I think it can be marked as a `good-first-issue` through which we can involve newcomers in the community.

/area web-development
/sig docs

**Comment by sftim** [comment]
This sounds a bit much for a good first issue. Labelling with /help could be a good idea though.

Ideally, we'd switch the English localization not to use ``newcommunity.css`](https://github.com/kubernetes/website/blob/main/static/css/newcommunity.css) (leave it there for downstream localizations, though) in favor of new Sass within https://github.com/kubernetes/website/tree/main/assets/scss

**Comment by CIPHERTron** [comment]
> This sounds a bit much for a good first issue. Labelling with /help could be a good idea though.
> 
> Ideally, we'd switch the English localization not to use [`newcommunity.css`](https://github.com/kubernetes/website/blob/main/static/css/newcommunity.css) (leave it there for downstream localizations, though) in favor of new Sass within https://github.com/kubernetes/website/tree/main/assets/scss

@sftim Yeah, fair enough. `good-first-issue` is a bit too much, I totally agree. Labelling it with `/help` SGTM 🚀

**Comment by sftim** [comment]
/remove-lifecycle stale

Help is welcome!

**Comment by sftim** [comment]
Ideally, we could remove `static/css/newcommunity.css` entirely in favor of some new Sass code within `assets/scss`.

**Comment by CIPHERTron** [comment]
Wow......tysm @sftim for sending a PR against this issue. That was quick!

I'll help review #31658 🚀

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/31658 aims to start the work. If that merges, I think the are opportunities to do more. Some of that is localization; other parts are CSS tweaks and further changes to the English page.

It would be nice to bring back a working events feed (that should be a separate issue, though).

**Comment by CIPHERTron** [comment]
> If that merges, I think the are opportunities to do more.

I think we have some interested folks who can help with that. Also, I'm interested too. Let me know how I can help with #31658 and I would be happy to help if we plan on extending this refactoring to other pages too. 

> It would be nice to bring back a working events feed (that should be a separate issue, though).

Agreed 💯
