### ISSUE TITLE
Disable Netlify Drawer for previews

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29677]
**This is a Bug Report**

**Problem:**
Deploy previews contain a [Netlify Drawer](https://docs.netlify.com/site-deploys/deploy-previews/#test-and-troubleshoot-with-collaboration-tools)
However, SIG Docs doesn't use this functionality.

**Proposed Solution:**
Remove Netlify Drawer from site (change Netlify configuration)

**Page to Update:**
https://kubernetes.io/

**Comment by sftim** [comment]
I've disabled this in the Netlify configuration.

**Comment by Guneetconvent2002** [comment]
> I've disabled this in the Netlify configuration.

So, is this issue open or closed??

**Comment by sftim** [comment]
I think this is done.
/close
