### ISSUE TITLE
Query about “Controlling Access to the Kubernetes API”

### ISSUE THREAD

**Issue by parvezsyed** [kubernetes/website#29680]
In the docs on "Controlling access to K8s" we say: In a typical Kubernetes cluster, the API serves on port 443, protected by TLS, but in "API server ports and IPs" secure port default is 6443

Which statement is correct?

**Comment by sftim** [comment]
/retitle Query about “Controlling Access to the Kubernetes API”

The true situation is that the API server listens on a nonstandard port, 6443, by default. As a cluster operator you're expected either to override this to the actual port used for HTTP over TLS (443), or to insert a reverse HTTP or TLS SNI proxy between the client and the API server.

I don't think the existing document makes that clear, and we don't have a good page about the API server to add that detail to.

/language en
/sig architecture
I suppose

**Comment by jayesh-srivastava** [comment]
Hey, I would like to work on this issue. Can I assign it to myself?

**Comment by Sea-n** [comment]
As sftim said above, the document could be more clear to avoid confusion.

Hey @jayesh-srivastava, would you like to fix this? 😊

/remove-lifecycle rotten

**Comment by Sea-n** [comment]
I think @jayesh-srivastava is busy for other stuff. You can assign yourself again anytime.
/unassign @jayesh-srivastava

Now, anyone can assign themself using `/assign` command. It would be nice if someone willing to work on this.

**Comment by jayesh-srivastava** [comment]
@Sea-n apologies for being inactive. Was acquired a bit. Would be happy to fix this, some help can be great as well.

**Comment by sftim** [comment]
Content unclear about “Controlling Access to the Kubernetes API” and ports in use
/remove-lifecycle rotten
/lifecycle stale
