### ISSUE TITLE
Umbrella Issue: Clean up interactive tutorials

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#29688]
## Overview

We have multiple issues being opened because of blockers or quality problems with our interactive tutorials. We should review our tutorials and update them to improve the user experience.

## Current issues

* #29683 
* #29627 
* #29618 
* #29617 
* #29588 
* #29530 
* #29210 
* #28428 
* #28169

There are more (see this search: https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+%22interactive+tutorial%22+in%3Atitle)

## Proposed solution

Work through each interactive tutorial. Clean up instructions for style, technical accuracy, and ensure that the steps achieve the objective in the tutorial. 

Tutorial source is at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios.

/sig docs
/label team-katacoda
/language en

**Comment by shannonxtreme** [comment]
Thank you @Debanitrkl I blame Mondays.

**Comment by sftim** [comment]
I don't think the issues here are just for the Katacoda folks though, or even really shortcomings with Katacoda itself.

/remove-label team/katacoda

**Comment by sftim** [comment]
We no longer have any interactive tutorials.

/close not-planned
