### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/rbac/

### ISSUE THREAD

**Issue by dfisk** [kubernetes/website#29696]
This reference manual on RBAC fails to define its terms; the legal and recognized "verbs" in this syntax are nowhere to be found; one can only glean the verbs from the arbitrary examples given, with no expectation of comprehensiveness, and otherwise go searching elsewhere.

**Comment by sftim** [comment]
/wg api-expression

PR #25299 might help by adding a better list of verbs. However, I don't think there is an agreed list of API verbs defined anywhere.
