### ISSUE TITLE
Add diagrams page to Documentation style overview 

### ISSUE THREAD

**Issue by chrismetz09** [kubernetes/website#29692]
**This is a Feature Request**

Add documentation diagram page to documentation style overview. This provides guidance/instructions on how to create and add useful diagrams to contributions where appropriate.

**What would you like to be added**

Diagrams add clarity and understanding to docs readers. Docs contributors should have instructions on how to create and add very simple diagrams to docs  pages. 

**Why is this needed**

- No formal or informal content on docs diagram generation, placement, different methods, etc. Result is ad-hoc or no diagrams.

**Comments**

- Refactor https://github.com/chrismetz09/K8s-docs-mermaid as input
- Include instructions/examples of how to imbed and reference svg or png files
- any other important features/functions contributors should have for making diagrams.

**Comment by jayesh-srivastava** [comment]
Hi @chrismetz09 Can I work on this issue?

**Comment by chrismetz09** [comment]
Hey @jayesh-srivastava, I already have some content ready to go. Can I ask you to review?

**Comment by jayesh-srivastava** [comment]
@chrismetz09 Sure will review it.
