### ISSUE TITLE
Add a reference doc for ports and protocols info

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/website#29698]
**What would you like to be added**
Create a dedicated ports and protocols page for Kubernetes Clusters. 

**Why is this needed**
- Currently, the closest page that provides this information is under KubeAdm install setup [page](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports). 
- This is hard to find for any cluster administrator trying to deploy Kubernetes
- Documented Ports for [kube-controller](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) and [kube-scheduler](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/) are incorrect and need an update
Slack thread: https://kubernetes.slack.com/archives/C1J0BPD2M/p1628568604069300

/sig security node docs architecture
/area security

**Comment by sftim** [comment]
Hi @PushkarJ 

Would you be OK to have this as a reference page, rather than as a concept?

**Comment by neolit123** [comment]
/sig cluster-lifecycle
Given the PR touches kubeadm docs.

**Comment by PushkarJ** [comment]
> Hi @PushkarJ
> 
> Would you be OK to have this as a reference page, rather than as a concept?

Moved it under `reference`. This was the kind of feedback I was looking for from SIG Docs. Thank you @sftim
