### ISSUE TITLE
Adding Windows nodes

### ISSUE THREAD

**Issue by leandroscardua** [kubernetes/website#29708]
Hi K8s Team,

Please take a look on the step 4 (Add Windows Flannel and kube-proxy DaemonSets)
The list there is not working, looks like the sig-windows team made change on the git repository.
Also, on the step: joining a Windows worker node, both links to install docker EE and ContainerD are not working too

Could you please update the documentation?

**Comment by alexglyde** [comment]
Running into this as well. Neither of the following links in step4 of the documentation are working. 
https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml
https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-overlay.yml

As far as I can tell, the files aren't present. Running the curl commands in step 4 on the "Adding a Windows Node" page is failing with "Not Found". The URL for the documentation that I'm referring to is: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#configuring-flannel

 @sftim Has anyone recommended new commands to run to get these files and/or to configure flannel for windows on the linux k8 master node? Need this to keep going on setting up an on premise k8 cluster.

**Comment by alexglyde** [comment]
Seems like I was able to download a version of these files using the following links:
https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/kubeadm/kube-proxy/kube-proxy.yml
https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/kubeadm/flannel/flannel-overlay.yml

Got the idea from: https://github.com/kubernetes/website/issues/29149#issuecomment-889838963

**Comment by reylejano** [comment]
Links are fixed, see [comment](https://github.com/kubernetes/website/pull/29755#issuecomment-924317320)
/close

**Comment by leandroscardua** [comment]
Thank you Team
