### ISSUE TITLE
Use of config

### ISSUE THREAD

**Issue by wendao8469759** [kubernetes/website#29723]
I am a novice who is learning kubernetes
When I see the "-- default not ready tolerance seconds" and "-- default unreachable tolerance seconds" attributes
I think I need it, but I tried it several times and failed to set it. I didn't see how to use this attribute on the official website.

**Comment by sftim** [comment]
/kind support
(I think)

Would you like to clarify the issue you're reporting @wendao8469759 ?

**Comment by ashutosh887** [comment]
@wendao8469759 @sftim @k8s-ci-robot @drnic @gnufied 
I wanted to start contributing for this project
Can someone please help me or guide me a bit

**Comment by Tej-Singh-Rana** [comment]
Please check it out on this page.
https://kubernetes.io/docs/contribute/
This is especially created for new contributors. @ashutosh887

**Comment by tengqm** [comment]
Closing since this is not a doc issue. Feel free to reopen.
/close
