### ISSUE TITLE
Operating etcd clusters for Kubernetes

### ISSUE THREAD

**Issue by mkrupczak3** [kubernetes/website#29734]
The example restore endpoint for etcdctl is the arbitrary IP `10.2.0.9:2379` which is unnecessary and entirely unhelpful for operators.

A better IP to use in the example may be the localhost loopback address `127.0.0.1:2379`

This will be more useful in the majority of cases and reduce the cognitive load of operators attempting to restore a cluster at a stressful time when they need to do so.

**Comment by mkrupczak3** [comment]
This page: https://github.com/kubernetes/website/issues/new?title=Operating%20etcd%20clusters%20for%20Kubernetes

**Comment by RinkiyaKeDad** [comment]
Hey @mkrupczak3 the link you posted is for opening a new issue. Could you please provide the link for the page where you're suggesting this change?

/triage needs-information

**Comment by mkrupczak3** [comment]
Oops, okay this page: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster

Proposed fix in PR #29735

**Comment by mkrupczak3** [comment]
Thanks @RinkiyaKeDad for taking a taking a look

**Comment by annajung** [comment]
Hi there, [PR wrangler](https://github.com/kubernetes/website/wiki/PR-Wranglers) here for this week. 

Based on the [documentation for triaging an issue](https://kubernetes.io/docs/contribute/review/for-approvers/#triaging-an-issue), I'll close out this issue as it contains both `lifecycle/stale` and `triage/needs-information` labels.

Feel free to reopen with correct labels if it's still relevant.
