### ISSUE TITLE
Issue with /docs/concepts/workloads/controllers/statefulset/

### ISSUE THREAD

**Issue by gtema** [kubernetes/website#2973]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Broken link to http://releases.k8s.io/master/build/kube-dns/README.md

**Proposed Solution:**
most likely it should point somewhere to https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/, but the content might need to be adapted

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

**Comment by tengqm** [comment]
already fixed.
