### ISSUE TITLE
Kubernetes Release Cycle page images are broken

### ISSUE THREAD

**Issue by Tej-Singh-Rana** [kubernetes/website#29745]
**In the below page, attached images are broken.** 
https://github.com/kubernetes/website/blob/main/content/en/releases/release.md

Thank you,

**Comment by sftim** [comment]
@Tej-Singh-Rana the page we'd expect you to visit is [Kubernetes Release Cycle](https://k8s.io/releases/release/) and is rendered with the following warning:
> Warning: This content is auto-generated and links may not function. The source of the document is located [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md).

https://github.com/kubernetes/website/blob/main/content/en/releases/release.md is the source code used to generate that page. As Kubernetes is open source, you get to see details like this if you look for them.

We could improve the import script to also copy images across.

**Comment by sftim** [comment]
/retitle Kubernetes Release Cycle page images are broken

**Comment by Tej-Singh-Rana** [comment]
Thanks for the detailed information. Literally I ignored that warning. @sftim 👍
