### ISSUE TITLE
simplify sig-windows docs 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#29769]
**This is a Bug Report**
 

**Problem:**

We currently have copious references to flannel, wins, etc in the getting started w/ windows stuff.

- hostProcess containers will obviate the need to use kube-proxy over wins
- for now nssm is a easy, commonly done solution

**Proposed Solution:**

Clean out docs to just use a commonly supported, easily reproduced recipe for windows bootstrapping.

**Comment by jsturtevant** [comment]
/close 
in favor of https://github.com/kubernetes/website/issues/31428 which has more details
