### ISSUE TITLE
default Pod:EntryPoint for OCI images

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29765]
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#entrypoint says the default entry point for an image  (Pod→spec→Containers) is 

> The docker image's ENTRYPOINT is used if this is not provided

Please clarify, if this also applies to OCI images, or OCI images have to specify command⇔entrypoint explicitly.

**Comment by sftim** [comment]
In the [upstream code](https://github.com/kubernetes/kubernetes/blob/76c0573ff4b455dd45426b4fb09c5403ccca56ed/pkg/apis/core/types.go#L2125), we could replace “docker image” with “container image”.
