### ISSUE TITLE
Set up Ingress on Minikube with the NGINX Ingress Controller

### ISSUE THREAD

**Issue by FrantzT** [kubernetes/website#29760]
In:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080

Should be:

              service:
                name: web
                port:
                  number: 80
                  
 Otherwise 
 
 kubectl get ingress
 
 Returns:
 
 NAME              CLASS    HOSTS              ADDRESS        PORTS   AGE
example-ingress   <none>   hello-world.info                        80      38s

ADDRESS is not assigned

As it has wrong port mapping to the service 8080 instead of 80

**Comment by RA489** [comment]
@FrantzT I have tried setting up Ingress on Minikube with NGINX Ingress controller but it works fine for me. web service is being exposed on port 8080 thats what mentioned in ingress web service port.

**Comment by FrantzT** [comment]
What configuration do you use?
I used wsl2 on Windows. And it only works when port 80 is set not 8080.
I found a note on internet that other people has this problem, that's how I
have solved it.

You can see that example-ingress is set to port 80 on the page not 8080.

**Comment by divya-mohan0209** [comment]
I would recommend opening up an issue against kubernetes/minikube repository if you're still facing an issue. 
/close
