### ISSUE TITLE
Update dockershim deprecation timeline in published blog post from K8s v1.23 -> v1.24

### ISSUE THREAD

**Issue by cwilhit** [kubernetes/website#29776]
**This is a Bug Report**

**Problem:**
When the community originally announced deprecation of dockershim in Kubernetes, a FAQ was published detailing the deprecation timeline ([link](https://kubernetes.io/blog/2020/12/02/dockershim-faq/#when-will-dockershim-be-removed)). The timeline as presented states:

> It will not be removed before Kubernetes 1.22, meaning the earliest release without dockershim would be 1.23 in late 2021

Since then, the timeline has been revised and extended to 1.24, as found in kubernetes/enhancements#2221.  Additionally, the FAQ links out a KEP that is now invalid listed under [this section](https://kubernetes.io/blog/2020/12/02/dockershim-faq/#why-is-dockershim-being-deprecated).

As this blog post is likely the first place people will land on when people do a web search, we should at minimum update the KEP link and preferably update the timeline as advertised in the blog post.

**Proposed Solution:**

1. Revise the wording in section "when-will-dockershim-be-removed" to say (changes in **bold**), "It will not be removed before Kubernetes **1.23**, meaning the earliest release without dockershim would be **1.24** in **early 2022**"
2. Invalid KEP link called out in above section should be changed to point at kubernetes/enhancements#2221

**Page to Update:**
https://kubernetes.io/blog/2020/12/02/dockershim-faq

**Comment by reylejano** [comment]
Created PR https://github.com/kubernetes/website/pull/29780 to fix this issue

**Comment by sftim** [comment]
When we revise published blog articles (and we're not just correcting something that, at the time, we'd have fixed before merge if we'd spotted it), we should clearly call out that we're making changes and what the original text would have said.

This is especially important for key details, such as this one.
/area blog
/remove-kind bug
/triage accepted

**Comment by sftim** [comment]
(The hyperlink to the KEP is uncontroversial - you might want to split that fix into its own PR)

**Comment by sftim** [comment]
Fixed in #29780, I think
/close
