### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

### ISSUE THREAD

**Issue by mpaine-act** [kubernetes/website#29794]
Please update for Windows Server 2022.

**Comment by imoisharma** [comment]
Hi @mpaine-act,

`With this release and future releases, the Windows 10 release nomenclature is changing from a year and month pattern (YYMM) to a year and half-year pattern (YYH1, YYH2).
`
please look [here](https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-20h2)

Best Regards
Mohit Sharma
