### ISSUE TITLE
SIG Docs Co-chair onboarding: divya-mohan0209

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#29805]
# SIG Docs Co-chair onboarding

As part of the [7th September 2021 SIG Docs meeting](https://docs.google.com/document/d/1ddHwLK3kUMX1wVFIwlksjTk0MsqitBnWPe1LRa1Rx5A/edit#heading=h.8kj39dqgwkc8) @divya-mohan0209 was nominated for the co-chair role within SIG Docs by @jimangel  

### Transition date

Without further input, the [lazy consensus](https://groups.google.com/g/kubernetes-sig-docs/c/AFWmzt43G3Y/m/ie1uCwjaBgAJ) was to transition on 24th September, 2021.

## Required changes

Co chair onboarding requires some updates:

| Repo  | file  | Complete?  |
|---|---|---|
| k/community  | [OWNERS_ALIASES](https://github.com/kubernetes/community/blob/master/OWNERS_ALIASES)  |   |
| k/community  | [sig-docs/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/README.md)  |   |
| k/community  | [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md)  |   |
| k/community  | [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1185-L1198) |   |
| k/enhancements  | [OWNERS_ALIASES](https://github.com/kubernetes/enhancements/blob/master/OWNERS_ALIASES#L40)   |   |
| k/org  | [OWNERS_ALIASES](https://github.com/kubernetes/org/blob/master/OWNERS_ALIASES#L39) |   |
| k/website  | [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/master/OWNERS_ALIASES#L141)  |   |
| k/website  | [SECURITY_CONTACTS](https://github.com/kubernetes/website/blob/master/SECURITY_CONTACTS) |   |

/sig docs

**Comment by sftim** [comment]
This all looks done to me. (If I'm wrong, then of course it's OK to reopen this).
/close
