### ISSUE TITLE
Error running Hello Minikube tutorial on Apple Silicon M1

### ISSUE THREAD

**Issue by rbrtmrtn** [kubernetes/website#29812]
Hello!

I am working through the Hello Minikube tutorial [https://kubernetes.io/docs/tutorials/hello-minikube/](here). When I try to create a deployment of `echoserver` I get an error in my kubectl logs:

```bash
nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:54
```

As a sanity check I tried running `docker run k8s.gcr.io/echoserver:1.4` and got this warning, which I suspect may be a clue:

```bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

I am working through the tutorial on an Apple MacBook Air M1 2020 running macOS 11.6 Big Sur.

Thank you for any insights on this!

---

**UPDATE**: I tried passing the `--platform` flag to fetch the ARM64 image (so, `docker run --platform linux/arm64/v8 k8s.gcr.io/echoserver:1.4`) and got a similar error:

```bash
docker: Error response from daemon: image with reference k8s.gcr.io/echoserver:1.4 was found but does not match the specified platform: wanted linux/arm64/v8, actual: linux/amd64.
```

**Comment by sftim** [comment]
It looks like the Hello Minikube tutorial requires a Linux AMD64 node, or at least isn't compatible with a VM running AArch64 & Linux.
I'm not sure what the best step forward might be here. Perhaps a newer version of that `echoserver` container supports AArch64?

**Comment by rbrtmrtn** [comment]
Hi @sftim, thanks for taking a look at this! I was poking around in the `echoserver` project and I found some hints that multi-arch builds should be supported. This mentions `arm64`, which is what seems to be missing from the container registry.

https://github.com/kubernetes/kubernetes/blob/master/test/images/echoserver/BASEIMAGE

I'm wondering if maybe the non-`amd64` builds aren't happening for some reason, or aren't getting pushed up? A little out of my depth on this one 😆
