### ISSUE TITLE
[zh] docs wrong - https://kubernetes.io/zh/docs/reference/labels-annotations-taints/#node-kubernetes-io-unreachable

### ISSUE THREAD

**Issue by zhangguanzhang** [kubernetes/website#29819]
https://kubernetes.io/zh/docs/reference/labels-annotations-taints/#node-kubernetes-io-unreachable
如果 NodeCondition 的 `NodeCondition` 超链接到英文文档了。
@tengqm

**Comment by Sea-n** [comment]
Could you check it again?
I think this issue is fixed by PR #32376.
- #32376

**Comment by zhangguanzhang** [comment]
> Could you check it again? I think this issue is fixed by PR #32376.
> 
> * [[zh] Update labels-annotations-taints related reference pages #32376](https://github.com/kubernetes/website/pull/32376)

Fixed
