### ISSUE TITLE
header looks weird in Safari when using in-page search

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#2981]
There is some text hiding behind the header. It's not visible, but if you try to search for something on the page you get this

![screenshot 2018-02-20 13 42 35](https://user-images.githubusercontent.com/251467/36427041-ed92a0fa-1643-11e8-9bd1-a2ea4226c013.png)

It becomes more visible, when you scroll down

![screenshot 2018-02-20 13 43 09](https://user-images.githubusercontent.com/251467/36427083-0542e660-1644-11e8-8045-c377901d160d.png)

And it stays after you hide the search box

![screenshot 2018-02-20 13 43 12](https://user-images.githubusercontent.com/251467/36427099-13dc57ec-1644-11e8-95e8-f2a9fd226c4f.png)

**Comment by ahmetb** [comment]
It looks like this doesn't happen unless you search for something in the page?

**Comment by jaredbhatti** [comment]
Closing as unreproducible. Let me know if this issue comes back up.

**Comment by errordeveloper** [comment]
I've re-uploaded screenshots and clarified what actually happens from user's perspective.

**Comment by zacharysarah** [comment]
I'm able to reproduce it in Safari, too:

![screen shot 2018-03-05 at 11 58 18 am](https://user-images.githubusercontent.com/3210446/36996858-aceca680-206c-11e8-82cc-a6638f12331d.png)

Looking at the [header text itself](https://github.com/kubernetes/website/blob/master/_includes/header.html), I'm honestly not fond of it. The argument in favor of keeping it would be descriptive text for adaptive settings and devices--but I question whether the text is any more helpful than the section names themselves. 

Unless someone strenuously objects to removing mediocre text visible only (?) in Safari, I'm going to mark this issue as `Actionable`. Specifically, to close this issue:

- Remove [header description text](https://github.com/kubernetes/website/blob/master/_includes/header.html#L33-L56)
