### ISSUE TITLE
[zh] wrong: https://kubernetes.io/zh/docs/tasks/administer-cluster/out-of-resource/

### ISSUE THREAD

**Issue by zhangguanzhang** [kubernetes/website#29822]
https://kubernetes.io/zh/docs/tasks/administer-cluster/out-of-resource/#%E8%8A%82%E7%82%B9-oom-%E8%A1%8C%E4%B8%BA
Guaranteed 的 `oom_score_adj` 我测试了下发现是和英文文档的 `-997` 而不是目前中文版本里的 `-998`

**Comment by mayocream** [comment]
This [file](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/administer-cluster/out-of-resource.md) is removed in the upstream, but I see [out-of-resource](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource) is redirected to [node-pressure-eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/), how to achieve that? 
cc @tengqm 

```bash
./scripts/lsync.sh content/zh/docs/tasks/administer-cluster/out-of-resource.md
content/en/docs/tasks/administer-cluster/out-of-resource.md has been removed.
```

**Comment by tengqm** [comment]
@mayocream We'd have to move this file to sync with upstream.

**Comment by howieyuen** [comment]
this issue is fixed, check here: https://kubernetes.io/zh/docs/concepts/scheduling-eviction/node-pressure-eviction/#%E8%8A%82%E7%82%B9%E5%86%85%E5%AD%98%E4%B8%8D%E8%B6%B3%E8%A1%8C%E4%B8%BA

/close
