### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/

### ISSUE THREAD

**Issue by murindwaz** [kubernetes/website#29836]
The command (`kubectl delete pod/redis configmap/example-redis-config`) suggested to delete a pod (redis pod) ~ doesn't actually delete the pod. The deleted pod sticks around, and when lunching(updating) the pod as indicated in the documentation, the status `CrashLoopBackOff` re-tries indifinitely.

**Comment by murindwaz** [comment]
@sftim ~ _If you waited to see if the Pod was removed after some time, how long did you wait?_ - Indefinitely. I had to reboot my computer. You are right, the Pod sticks around forever for some weird reasons. 

I learnt after the fact that deleting the Deployment and not the Pod is the way to go. The question is, can that be mentioned in the documentation?

**Comment by Kartik494** [comment]
@murindwaz i think the description of the command is to delete the pod , it;s not certain that pod is deployed through deployment or statefulset.i think it's just an example statement . what you think @sftim

**Comment by sftim** [comment]
We know from https://k8s.io/docs/tutorials/configuration/configure-redis-using-configmap/ that the Pod was directly created.

If you're not following this guide, pasting in excerpts from it might not achieve what you want.

/kind support
/close
