### ISSUE TITLE
[ko] Fix wrong link in concepts/workloads/controllers/replicaset.md

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#29852]
**This is a Bug Report**

**Problem:** In [replicaset korean page](https://kubernetes.io/ko/docs/concepts/workloads/controllers/replicaset/), there is worng link related to labels-annotations-taints.

**Proposed Solution:**
Change link "`controller.kubernetes.io/pod-deletion-cost`](/docs/reference/labels-annotations-taints/#pod-deletion-cost)" to 
"`controller.kubernetes.io/pod-deletion-cost`](`/ko/`docs/reference/labels-annotations-taints/#pod-deletion-cost)."

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/workloads/controllers/replicaset

**Note**
Set base branch `Korean Team working branch`!
> Currently the working branch of Korean Team is `dev-1.22-ko.1`.

/language ko

**Comment by abritpal** [comment]
Hi!, I would like to work on this
