### ISSUE TITLE
Kubernetes Documentation

### ISSUE THREAD

**Issue by skdas2016** [kubernetes/website#29863]
I am using Kubernetes 1.12 . Trying to use local ephemeral storage for POD . not sure whether this feature is available since 1.10 or after 1.16 . Please suggest

I am referring to this doc .. Section 
https://kubernetes.io/docs/concepts/configuration/_print/#local-ephemeral-storage

**Comment by sftim** [comment]
/kind support

See https://kubernetes.io/docs/home/supported-doc-versions/ for which versions of Kubernetes the documentation supports.
