### ISSUE TITLE
tasks/administer-cluster/dns-custom-nameservers: update link to cluster addons

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29861]
The first paragraph at https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction contains a link to  cluster add-on → https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md

The latter page says, this is a legacy document, and refers to https://kubernetes.io/docs/concepts/cluster-administration/addons/ .

• Replace in https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction the link from https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md to https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md

**Comment by Kartik494** [comment]
@dilyanpalauzov  i think in the issue description you provided the link to be corrected to original link.
I think you here mean to correct the link to [this](https://kubernetes.io/docs/concepts/cluster-administration/addons/).WDYT

**Comment by Kartik494** [comment]
Although i think the links provided in the documentations are correct the link provided in [inroduction](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction) is reference for addon manager and the reference for installing addon is documented in this [file](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md)

**Comment by Kartik494** [comment]
So as per documentation i think it seems to reference this [link](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/README.md) which is  manager add on but it refers to [legacy addon](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/README.md)
