### ISSUE TITLE
Unnecessary code are rendered at "Enable the Ingress controller" section

### ISSUE THREAD

**Issue by niteshseram** [kubernetes/website#29864]
**This is a Bug Report**

**Problem:**
There are some unnecessary codes being rendered at  step 2 of "Enable the Ingress controller" section in this tutorial https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#enable-the-ingress-controller as shown below
![Capture](https://user-images.githubusercontent.com/51370246/135390981-b1b3034e-d10d-4c34-8f79-0c66fa6bab4c.PNG)

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube

/language en

**Comment by niteshseram** [comment]
I can see this PR #29206 is solving this issue.

**Comment by sftim** [comment]
Solved
/close
