### ISSUE TITLE
Issue with /docs/getting-started-guides/centos/centos_manual_config/

### ISSUE THREAD

**Issue by carroarmato0** [kubernetes/website#2988]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Centos repository mentioned to use contains ancient versions of software from back in 2015.

**Proposed Solution:**
Point to a repository containing the latest and greatest for a smoother getting-started-experience.

**Page to Update:**
http://kubernetes.io/...

**Comment by superawesome** [comment]
For reference, this full URL to this page is:

https://kubernetes.io/docs/getting-started-guides/centos/centos_manual_config/

**Comment by tengqm** [comment]
the links now points to latest virt7 repo.
