### ISSUE TITLE
Misleading entry in kubectl cheatsheet

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29893]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#interacting-with-running-pods lists:
```bash
kubectl run nginx --image=nginx -n 
mynamespace                                         # Run pod nginx in a specific namespace
```

There are at least two problems
1. This command doesn't interact with a running Pod, so it's in the wrong section
2. It's invalid code. If you paste that into a POSIX shell, first `kubectl` will tell you that you didn't specify a namespace, and then your shell will fail to find a command called `mynamespace`.

**Proposed Solution:**

1. Move that entry under [Creating objects](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#creating-objects)
   (possibly with an explanatory comment)
   I'd put it after `kubectl explain pods`.
2. Fix it so that it's valid POSIX shell
3. Consider revising the comment to explain that creating a Pod like that implies that the new Pod has 1 container named after the image (`nginx` in this case).

**Page to Update:**
https://k8s.io/cheatsheet

**Additional Information:**
/language en

**Comment by niteshseram** [comment]
> It's invalid code. If you paste that into a POSIX shell, first kubectl will tell you that you didn't specify a namespace, and then your shell will fail to find a command called mynamespace.

We need to first create a namespace `mynamespace` by running `kubectl create namespace mynamespace`, then it will work. So, there is nothing wrong with current command.

**Comment by niteshseram** [comment]
Do we still want to move this up to the `Creating Objects` section?

**Comment by sftim** [comment]
> @sftim We need to first create a namespace mynamespace by running kubectl create namespace mynamespace, then it will work. So, there may be there is nothing wrong with the current command.

The linebreak is a problem too. If you paste that into a POSIX shell as-is: first `kubectl` will tell you that you didn't specify a namespace, and then your shell will fail to find a command called `mynamespace`.

We should fix **both** issues.

**Comment by niteshseram** [comment]
> > @sftim We need to first create a namespace mynamespace by running kubectl create namespace mynamespace, then it will work. So, there may be there is nothing wrong with the current command.
> 
> The linebreak is a problem too. If you paste that into a POSIX shell as-is: first `kubectl` will tell you that you didn't specify a namespace, and then your shell will fail to find a command called `mynamespace`.
> 
> We should fix **both** issues.
I removed the line break from the command. Hopefully, this should solve the issue.

**Comment by sftim** [comment]
@niteshseram is there a pull request you'd like reviewed?

**Comment by niteshseram** [comment]
> @niteshseram is there a pull request you'd like reviewed?

I created this PR #29902 but it seems there is another similar issue #29278 with the PR, so I closed it. Let me know if it is different I can reopen it.
