### ISSUE TITLE
kubelet-config.v1beta1 - default values for required parameters

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29892]
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration says:

> enableServer [Required] bool ------ enableServer enables Kubelet's secured server. Note: Kubelet's insecure port is controlled by the readOnlyPort option. If DynamicKubeletConfig (deprecated; default off) is on, when dynamically updating this field, consider that it may disrupt components that interact with the Kubelet server. Default: true

Since the parameter is required, it is mandatory to provide it, and the default never applies.

The same applies to:

> logging [Required] LoggingConfiguration ---------- logging specifies the options of logging. Refer to [Logs Options](https://github.com/kubernetes/component-base/blob/master/logs/options.go) for more information. Default:   Format: text

**Comment by tengqm** [comment]
@dilyanpalauzov Please consider file an issue against kubernetes/kubernetes repo. The configuration reference is generated from the upstream source. The `enableServer` one can be found here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L91-L97

**Comment by tengqm** [comment]
We won't fix the generated reference directly.
/close
