### ISSUE TITLE
Improvement for k8s.io/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by king3379** [kubernetes/website#29899]
Could not connect to packages.cloud.google.com:443 (172.217.160.78), connection timed out
Reading package lists... Done
W: Failed to fetch https://apt.kubernetes.io/dists/kubernetes-xenial/InRelease  Could not connect to packages.cloud.google.com:443 (172.217.160.78), connection timed out
W: Some index files failed to download. They have been ignored, or old ones used instead.
中国地区这种工具完全不好使呢

**Comment by sftim** [comment]
/kind support

@king3379 I think you're saying that the existing documentation is correct, but you're having trouble accessing https://apt.kubernetes.io/
This might be because of a network fault or explicit administrative denial on the network that you are using.
