### ISSUE TITLE
Grammar mistake in “Assign CPU Resources to Containers and Pods”

### ISSUE THREAD

**Issue by esimim** [kubernetes/website#29900]
There is a grammar mistake here in my understanding, please correct me if I am wrong.

"If you do not specify a CPU limit for a Container, then one of these situations applies:"

Should it be this?

"If you do not specify a CPU limit for a Container, then one of these situations apply:"

**Comment by sftim** [comment]
/retitle Grammar mistake in “Assign CPU Resources to Containers and Pods”

@esimim the existing text "If you do not specify a CPU limit for a Container, then one of these situations applies” is idiomatic English. The phrase “one of these situations” represents a single item.

**Comment by sftim** [comment]
I don't think there's anything that needs fixing.
/close
