### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

### ISSUE THREAD

**Issue by shlomiGit** [kubernetes/website#29903]
broken link in page: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/deploying-resources

**Comment by sftim** [comment]
/kind bug
/sig windows
/language en
/triage accepted
/priority backlog

Thanks for the report @shlomiGit

**Comment by PulkitSinghDev** [comment]
Would like to work on this issue
/assign
