### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by DavTho1983** [kubernetes/website#29914]
I replicated these exact steps with minikube on my new arm M1 Mac mini. It did not work.

kubectl get pods:

```
NAME                        READY   STATUS             RESTARTS      AGE
backend-685445b9db-82bsn    0/1     CrashLoopBackOff   4 (21s ago)   108s
backend-685445b9db-lfnc5    0/1     CrashLoopBackOff   4 (19s ago)   108s
backend-685445b9db-vzvd7    0/1     Error              4 (63s ago)   108s
frontend-65cd658457-z2nxb   1/1     Running 
```

With kubectl get service frontend --watch the EXTERNAL IP is always stuck in pending.

This is my exact kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/arm64"}
```

minikube version is:

```
minikube version: v1.23.0
commit: 5931455374810b1bbeb222a9713ae2c756daee10
```

**Comment by DavTho1983** [comment]
I would really appreciate some feedback to help me understand what is happening. I have not been able to set up any services using kubectl and I really need to learn k8s fast

**Comment by sftim** [comment]
Actually, no. This _is_ a request for support but maybe also the page could be clearer about its prerequisites and / or what to do if there are problems.
/remove-kind support
/language en

**Comment by sftim** [comment]
I think the page should say that it assumes you're using an AMD64 architecture PC.
