### ISSUE TITLE
Struggles with kubelet.service

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29913]
I have compiled kubernetes from source (kubeadm, kubelet, kube-apiserver, kube-proxy, kube-scheduler).  Then I follow the documentation at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ - Bootstrapping clusters with kubeadm - to setup my cluster.  The documentation contains first the chapter “Creating a cluster with kubeadm”, where it is proposed to run just `kubeadm init`.  `kubeadm init` checks if the kubelet service is installed and active.

Then follows the chapter “Configuring each kubelet in your cluster using kubeadm”.  The latter discusses very briefly how to start kubelet using systemd integration.

In particular it says at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd: 
> kubeadm ships with configuration for how systemd should run the kubelet. Note that the kubeadm CLI command never touches this drop-in file.
>
> This configuration file installed by the kubeadm DEB or RPM package is written to /etc/systemd/system/kubelet.service.d/10-kubeadm.conf and is used by systemd. It augments the basic kubelet.service for RPM or kubelet.service for DEB:
```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf
--kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generate at runtime, populating
the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably,
# the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead.
# KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```

-----------
> kubeadm ships with configuration for how systemd should run the kubelet. Note that the kubeadm CLI command never touches this drop-in file.
>
> This configuration file installed by the kubeadm DEB or RPM package is written to /etc/systemd/system/kubelet.service.d/10-kubeadm.conf and is used by systemd. It augments the basic kubelet.service for RPM or kubelet.service for DEB:

The above information is not correct.  The source code of kubeadm/kuebernetes/kubelet does not contain configuration how systemd should run the kubelet.  This information is provided by the package managers (red hat, debian).  

---------------
Since configuring correctly the systemd service for the kubelet must be performed before `kubeadm init` is run, the chapter about kubelet.service must be before the chapter “Creating a cluster with kubeadm”.

------------
Please include a full kubelet.service file, which shall be utilized, so that `kubeadm init` will not produce mystic errors.  This service shall be usable on Linux from Scratch systems, where no DEB or RPM packages are written.

**Comment by sftim** [comment]
> This configuration file installed by the kubeadm DEB or RPM package is written to /etc/systemd/system/kubelet.service.d/10-kubeadm.conf and is used by systemd. It augments the basic kubelet.service for RPM or kubelet.service for DEB:

implies that you need to install `kubeadm` from a package to benefit from that feature.

I don't see a bug here @dilyanpalauzov 
If this section could be more clear, we're keen to understand how.

/sig cluster-lifecycle
/remove-kind bug
/priority awaiting-more-evidence

**Comment by sftim** [comment]
By the way: these kubeadm pages are not yet localized into Russian and Ukrainian. Some parts of the docs already are, though:
- [Русский](https://kubernetes.io/ru/)
- [Українська ](https://kubernetes.io/uk/)

If you happen speak either of those languages and would like to help out, I'm sure the project would appreciate that (see https://kubernetes.io/blog/2019/04/26/how-you-can-help-localize-kubernetes-docs/ for a starting point).

**Comment by dilyanpalauzov** [comment]
I want to install kuberenetes on a Linux from Scratch system.  It does not have packages.  The documentation shall state, how the final kubelet.service should like (e.g. does it include Restart=), as if packages (DEB, RPM) were never invented.

**Comment by sftim** [comment]
You'd like to have a document that explains how to configure systemd when building kubeadm from scratch?

To me, that sounds like a feature request more than a bug. We could consider it but I do not think it would be a priority for the Kubernetes project.
Documenting a wholly “from scratch” Kubernetes build is rather a daunting prospect (I say this as a technical lead for SIG Docs).

**Comment by dilyanpalauzov** [comment]
Yes, I want to have a document, which describes how to setup kubernetes from scratch.  One aspect is getting the right systemd service file for kubelet, so that it can be used by `kubeadm init`.  Another aspect is how to utilize `kube-apiserver`, `kube-controller-manager`, `kube-proxy` and `kube-scheduler` (and etcd, coredns), once they are compiled from kubernetes source code.

**Comment by dilyanpalauzov** [comment]
In any case, by its structure, the documentation shall first talk about the kubele-service drop-in, before mentioning `kubeadm init`.

**Comment by tengqm** [comment]
If you want to use kubeadm, you'd understand how the docker images for the control plane components are built. You can then build your own images and tell kubeadm to use your own image registry.

**Comment by neolit123** [comment]
If you go to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Under inatalling kubeadm, kubectl...there is a tab called "Without a package manager" and it has steps to download all systemd files. Isn't that what you are looking for?

The "configuring a kubelet" document is more about implementation details. If you want something changed in these docs PRs welcome.

**Comment by sftim** [comment]
I'm tempted to triage this as
/kind support

_but_ absolutely, we welcome PRs and also sub-issues that clearly describe what changes might help.

**Comment by dilyanpalauzov** [comment]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ does indeed contain information where to download the systemd service files for kubelet.  However this is mixed together with instructions how to download the compiled binaries.  Since I have compiled the binaries by myself, I am not interested in this information and I have overseen it.  Moreover, the file is split into two (base kubelete.service and a drop-in file) which adds unnecessary complexity.

I would prefer, if the kubelet.service file is included in the webpage.  Thus it will be harder to overee and, once the documentation is downloaded, searching in it with `grep` can find results.

**Comment by sftim** [comment]
@dilyanpalauzov would you be willing to revise the issue description to describe the enhancement you'd like to see? It's also OK to open a new issue and link it to this one.

**Comment by sftim** [comment]
My gut feeling is that if you want to build Kubernetes (and components) from source, you'd be better looking on https://k8s.dev/

We _could_ consider adding more guides there. That's a **lot** of work across multiple special interest groups, and I don't think the appetite is there.

**Comment by sftim** [comment]
It sounds like this has been an experience you found frustrating @dilyanpalauzov 

I'm confident that the Kubernetes project does not want to document these details, because adding such documentation also represents a commitment to keep these documents up to date. This entails a significant extra effort.

However, you might like to propose a blog article to either https://k8s.dev/blog/ or to https://kubernetes.io/blog/ that concerns a from scratch deploy of Kubernetes where you use `kubeadm` (ie, not [Kubernetes the hard way](https://github.com/kelseyhightower/kubernetes-the-hard-way/)). With such an article there is no implicit promise to keep the details current.

If you have the appetite for it, you are also welcome to create or adapt your own from-scratch guide. I don't think the Kubernetes project could maintain that guide either, but individual contributors might be quite willing to help informally.

**Comment by sftim** [comment]
I will mention for completeness that there is a sizable [ecosystem of organizations that can help here](https://www.cncf.io/certification/kcsp/), but that would typically do so as a commercial undertaking. You can also ask for advice on https://discuss.kubernetes.io/
