### ISSUE TITLE
Deploy and Access the Kubernetes Dashboard

### ISSUE THREAD

**Issue by manishpanjwani21** [kubernetes/website#29917]
While deploying the dashboard on 1.22.2 I am getting a warning
Warning: spec.template.metadata.annotations[seccomp.security.alpha.kubernetes.io/pod]: deprecated since v1.19; use the "seccompProfile" field instead. 
Please if you can fix it.

annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'

**Comment by sftim** [comment]
/retitile Warning whilst following task “Deploy and Access the Kubernetes Dashboard”

**Comment by sftim** [comment]
I think this report is about https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
/language en

**Comment by sftim** [comment]
That page links to https://raw.githubusercontent.com/kubernetes/dashboard/v2.3.1/aio/deploy/recommended.yaml

I suspect the fix will be to update that to a more recent all-in-one manifest, and test that the updated manifest works.
/kind bug

**Comment by Garima-Negi** [comment]
Seeing an error (not warning) : `error: error validating "https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.PodSecurityContext; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by Garima-Negi** [comment]
Hi, can this be assigned to me?

**Comment by Garima-Negi** [comment]
@dims @mehabhalodiya The corresponding PR for this issue is now closed. 
How do I go about closing this issue?
