### ISSUE TITLE
Sample kubelet.service contains unnecessary, second `ExecStart=`

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29912]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd says for the systemd unit file:
```
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```

The first `ExecStart=` is a no-op.

The snippet does not contain `Type=oneshot` and therefore [exactly one ExecStart must be given](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStart=).

**Comment by sftim** [comment]
This might be a genuine excerpt, in which case: the docs are accurate, and it's an upstream bug.
(I haven't checked).

/sig cluster-lifecycle
/language en

**Comment by sftim** [comment]
Thanks for spotting this @dilyanpalauzov

**Comment by dilyanpalauzov** [comment]
As a drop-in file, the purpose of the empty `ExecStart=` is the clear the value from the base unit:
