### ISSUE TITLE
Confusing text in “Updating Your App” interactive tutorial

### ISSUE THREAD

**Issue by henry-osorio** [kubernetes/website#29916]
wrong command:
      kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=gcr.io/google-samples/kubernetes-bootcamp:v10

it should be:
      kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=gcr.io/google-samples/kubernetes-bootcamp:v1

**Comment by sftim** [comment]
> it should be:
> ```
> kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=gcr.io/google-samples/kubernetes-bootcamp:v1
> ```

@henry-osorio how did you reach that conclusion? Your reasoning will help us to triage this report.

/language en

**Comment by henry-osorio** [comment]
I was doing the tutorial and this command failed. Troubleshooting the error and taking into account that the goal of the task was rolling the containers image back to the original I could notice the right version is v1 the one used to deploy containers initially and not v10 as indicated in the instructions

**Comment by sftim** [comment]
We could perhaps reword “Let’s perform another update, and deploy an image tagged with v10:” to imply an attempt (that might not succeed).
If anyone wants to do that rewording, the file to change is https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/blob/master/6/step3.md
