### ISSUE TITLE
Trouble running HostProcess pod on Windows node

### ISSUE THREAD

**Issue by pjohnst5** [kubernetes/website#29924]
Hello,

When I try to run a HostProcess pod I get the following
```
Created container win-container
  Normal   Pulled     5m10s                 kubelet, 4113k8s00000000  Successfully pulled image "acnpublic.azurecr.io/azure-cns-win:v1.4.12-43-g21f203db8-dirty" in 255.44ms
  Warning  Failed     5m5s (x4 over 6m3s)   kubelet, 4113k8s00000000  Error: failed to start containerd task "win-container": failed to get application name from commandline "/usr/local/bin/azure-cns.exe": failed to find executable "\\usr\\local\\bin\\azure-cns.exe": unknown
```

However, when I remove the following lines from [azure-cns-windows.yaml](https://github.com/pjohnst5/azure-container-networking/blob/x/hostprocess/cns/azure-cns-windows.yaml) to just make it a normal pod, and redeploy
```
...
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\Local service"
      hostNetwork: true
     ...
```

It works
```
k logs windows-daemonset-jxp6n
Azure Container Network Service
Version v1.4.12-43-g21f203db8-dirty
```

Any idea on how to fix that error above for HostProcess? Could definitely be from my end

The [Dockerfile ](https://github.com/Azure/azure-container-networking/pull/1043/files ) and [azure-cns-windows.yaml](https://github.com/pjohnst5/azure-container-networking/blob/x/hostprocess/cns/azure-cns-windows.yaml)

**Comment by sftim** [comment]
/retitle Trouble running HostProcess pod on Windows node

/kind support

**Comment by sftim** [comment]
@pjohnst5 this repository is for the documentation; issues here are to report problems with the documentation, or to ask for features.

You could instead post your question on the [Kubernetes Slack](http://slack.k8s.io/) or ask in the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
