### ISSUE TITLE
usage note in reference page for create secret missing word secret

### ISSUE THREAD

**Issue by cmjohns** [kubernetes/website#29929]
On the reference page for [kubectl create secret docker-registry](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-secret-docker-registry-em-) the usage example excludes the word "secret" from the command

I see

`$ kubectl create docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-file=[key=]source] [--dry-run=server|client|none]`

I expected
`$ kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-file=[key=]source] [--dry-run=server|client|none]`

**Comment by sftim** [comment]
/kind bug

This looks like a bug in the code that automatically generates documentation for `kubectl`.

**Comment by Kartik494** [comment]
@cmjohns If you want to use the correct commands you can look it at [here](https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pods-with-prod-test-credentials) untill this bug is not fixed

**Comment by Veercodeprog** [comment]
i want to contribute and try to fix this

**Comment by Kartik494** [comment]
@sftim Thanks for clarification. it's understood now

**Comment by Veercodeprog** [comment]
how to mark it fresh

**Comment by Veercodeprog** [comment]
guide me ,i work on it
