### ISSUE TITLE
Include the kubelet.service file in the documentation

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#29943]
Kubeadm verifies, that the kubelet service is running.  It does not say however how kubelet shall have been started and searching for the right kubelet.service file turned out to be very difficult.  At https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ under “Without a package manager” it does contain this text
> Install kubeadm, kubelet, kubectl and add a kubelet systemd service:
> RELEASE_VERSION="v0.4.0"
> curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubelet/lib/systemd/system/kubelet.service" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | sudo tee /etc/systemd/system/kubelet.service
> sudo mkdir -p /etc/systemd/system/kubelet.service.d
> curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/kubepkg/templates/latest/deb/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | sudo tee /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

but it is very hard to find.  In fact, how to run kubelet is not described in the section How to install kubelet, but in the section How to install kubeadm.  Since I have installed kubelet, but not the service files, I searched specifically for the service files for kubelet and these turned impossible to find. Besides, the downloaded file is split in two: base kubelet.service and a drop-in file, improving the base kubelet.service.  This split makes things unnecessary complicated.

I propose including in the documentation the source code of the systemd unit file:

```
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/

[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generate at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably,
# the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead.
# KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
Restart=always
StartLimitInterval=0
# NOTE: kind deviates from upstream here with a lower RestartSecuse
RestartSec=10

[Install]
WantedBy=multi-user.target
```

See also https://github.com/kubernetes/website/issues/29913.

**Comment by dilyanpalauzov** [comment]
See also https://github.com/kubernetes/kubeadm/issues/2584.

**Comment by neolit123** [comment]
> but it is very hard to find

I'd argue that is not hard to find. You literally must follow that guide because of a number of different prerequisites like cni, cni must be setup properly too. Not only systemd + kubelet.

Including the systemd files in a static page can render them out of date after changes in k/release. This is undesired.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#the-kubelet-drop-in-file-for-systemd is just an example covering the file variables.

Cc @sftim

**Comment by neolit123** [comment]
@dilyanpalauzov i encourage you to stop spamming issues with ideas in different repositories and concentrate the discussion in a single issue - https://github.com/kubernetes/website/issues/29913

**Comment by neolit123** [comment]
Users definitelly find that...
If those steps are out of date they log issues about it or PR fixes directly. For help they rally in #kubeadm on k8s slack.

**Comment by sftim** [comment]
I'm happy to agree with SIG Cluster Lifecycle on this one.

**Comment by sftim** [comment]
This is certainly a feature request rather than a bug.
/language en
/sig cluster-lifecycle
/remove-kind bug
/kind feature
/priority awaiting-more-evidence

**Comment by dilyanpalauzov** [comment]
I close this, as I consider any progress here as hopeless.
