### ISSUE TITLE
Mention Markdown flavor in “Contributing new content”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29945]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/contribute/new-content/ to tell readers what flavor of Markdown we use.
(it's [CommonMark](https://commonmark.org/)).

Optionally, also let readers know that you can use shortcodes [from Docsy](https://www.docsy.dev/docs/adding-content/shortcodes/) as well as our own [custom shortcodes](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/), and any that are [built in to Hugo](https://gohugo.io/content-management/shortcodes/) itself.

**Why is this needed**
There's more than one kind of Markdown, and a new contributor might not be sure which of those flavors they should use.

**Comments**
/language en
/kind feature
/help
/priority backlog

Hat tip to @dims for the suggestion

**Comment by siddhantprateek** [comment]
@sftim, yes i do

**Comment by niteshseram** [comment]
> @sftim, yes I do, I'm having a problem with setting up the project
What is the problem you are facing?

**Comment by siddhantprateek** [comment]
> What is the problem you are facing?

Thanks, but I figured it out. [PR#30012](https://github.com/kubernetes/website/pull/30012), I was having a problem running the website using a container, it did work locally using Hugo. 


**OS**: ubuntu 20.04

**Comment by PranshuSrivastava** [comment]
Hey, is this issue open to work on ? As both the PRs have been closed

**Comment by mehabhalodiya** [comment]
Can someone please close this issue?
