### ISSUE TITLE
Migrate identifiers reference into documentation

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#29960]
**This is a Feature Request**

**What would you like to be added**
Migrate https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md into a new page within https://kubernetes.io/docs/reference/

**Why is this needed**
The identifiers reference documentation is useful to Kubernetes users as well as to the contributor community.
We should:
- present it as part of the documentation
- localize it

After migration, https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md should become a short document that links to the new page, at least for a few years. 

**Comments**
/language en
/kind feature
/sig architecture

**Comment by ShivamTyagi12345** [comment]
hey @sftim  I would like to help with this

**Comment by sftim** [comment]
I've changed my mind on what we should do here; see  https://github.com/kubernetes/website/pull/29993#pullrequestreview-847160549

Sorry about that.
