### ISSUE TITLE
Broken link to iana on Service Reference API docs for appProtocol

### ISSUE THREAD

**Issue by Sodman** [kubernetes/website#29986]
**This is a Bug Report**

**Problem:**
The link to iana.org is broken in the [Service API Reference docs](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/), in the `ports.appProtocol` section.

This is due to a trailing paren `)` after the link. 

Browsers interpret this link as `https://www.iana.org/assignments/service-names)`, which results in a 404, instead of the intended `https://www.iana.org/assignments/service-names`.

**Proposed Solution:**
Either change the comment that results in this link being generated such that it doesn't end with a paren, or wrap the link with a `<a href ...>` tag so the browser doesn't try and fail to parse it from the text.

**Page to Update:**
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

Confirmed behavior on latest Firefox, Chrome and Safari.

**Comment by amalik17** [comment]
Can I work on this? It'd be my first contribution but I signed the agreement and looked at the instructions for contributing.

**Comment by shannonxtreme** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/107603

/close

**Comment by shannonxtreme** [comment]
And also 

/remove-lifecycle rotten
