### ISSUE TITLE
Second level menu items are missing on docs

### ISSUE THREAD

**Issue by snnsnn** [kubernetes/website#29997]
**This is a Bug Report**

When left column menu goes 3 levels deep, for example Concepts >> Workloads >> Pod is active,  2nd level items following the active parent, for our example anything that follows "Workloads", are not displayed.

Check the screenshot for the page https://kubernetes.io/docs/concepts/workloads/pods/, items like "Services, Load Balancing, and Networking" that come after Workloads are missing:

![image](https://user-images.githubusercontent.com/16473630/136657664-d81e2be2-eebc-4889-9069-d1a4e88fea59.png)

Behavior is confirmed for Firefox and Chrome, both in normal and private windows.

**Comment by snnsnn** [comment]
@sftim It is not likely a designed behavior because it does not follow a predictable pattern when folding the parent items. Even if that is the case, there should be some indicator because there is no way to know Concepts has hidden items.

Current implementation makes it very hard to navigate between third level pages, i.e from "Pods" or its children to "Services, Load Balancing, and Networking" and its children. More importantly there is no obvious benefit in hiding them.

**Comment by sidverma32** [comment]
@snnsnn @sftim  what's the behaviour decided here and is anyone working on this issue?

**Comment by sftim** [comment]
The SIG Docs consensus was that this isn’t intended behavior, and we should be looking into a PR to address it.
/triage accepted
/lifecycle frozen
/priority backlog

**Comment by sftim** [comment]
There's no hint at the moment that anyone's working on this.

**Comment by sftim** [comment]
- Pull requests are welcome
- Work to diagnose the issue further is welcome

**Comment by sidverma32** [comment]
okay, it's reproducible . Will check for the fix. @sftim  you can assign to me.

**Comment by sftim** [comment]
For Kubernetes SIG Docs, anyone can work on any issue (our more jargon-y way of saying this is “no [cookie licking](https://devblogs.microsoft.com/oldnewthing/20091201-00/?p=15843)”) and open a pull request to propose a related change.

**Comment by sftim** [comment]
(for my part, I rarely assign issues to myself - but when I have a draft or finished PR ready, I will link it to the issue and that  provides a hint in the issue about progress).

**Comment by sidverma32** [comment]
How to run the website in local?

**Comment by a-mccarthy** [comment]
Are folks still seeing this issue? i was just looking at the site, and second level items under Workloads are now visible when on the Pods page.
<img width="517" alt="Screen Shot 2022-08-25 at 2 11 06 PM" src="https://user-images.githubusercontent.com/20771501/186738561-5b38f984-0d13-4c92-80e3-10cb4d808229.png">


@sftim do you know of a PR that may have addressed this? or another example of where this is happening on the site? thanks!

let me know if i'm misunderstanding the issue :)
