### ISSUE TITLE
Interactive Tutorial - Exploring Your App

### ISSUE THREAD

**Issue by maple5233** [kubernetes/website#29994]
**This is a Bug Report**

**Problem:**
In Module 2
I create depolyment and service with
```shell
kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment hello-minikube --type=NodePort --port=8080
```

Module 3 - Step 2

curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/ works

but when I curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/

it returns 
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 172.17.0.5:80: connect: connection refused",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Info**
OS: Mac OS

Kubernetes Version: 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

minikube version: v1.23.2 with commit: 0a0ad764652082477c00d51d2475284b5d39ceed

docker image: gcr.io/k8s-minikube/kicbase   v0.0.27   9fa1cc16ad6d

**Comment by Garima-Negi** [comment]
HI @maple5233 , curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/ 
returns: 
```$ curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-fb5c67579-744pw | v=1```  in the tutorial.

Can you confirm that in the Katacoda interactive terminal, you see a terminal 2 tab ?
Does this tab show
```
Starting Proxy. After starting it will not output a response. Please click the first Terminal Tab

Starting to serve on 127.0.0.1:8001```

This would indicate that the proxy server is running and then you can curl for proxy to get correct output

**Comment by Garima-Negi** [comment]
Can I triage this issue?

**Comment by maple5233** [comment]
> HI @maple5233 , curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/ returns: `$ curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/ Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-fb5c67579-744pw | v=1` in the tutorial.
> 
> Can you confirm that in the Katacoda interactive terminal, you see a terminal 2 tab ? Does this tab show
> 
> `Starting Proxy. After starting it will not output a response. Please click the first Terminal Tab`
> 
> `Starting to serve on 127.0.0.1:8001`
> 
> This would indicate that the proxy server is running and then you can curl for proxy to get correct output

thanks for reply! I did NOT try the command in the Katacoda interactive terminal, instead i run the command in my local terminal, i use minikube to study Kubernetes.
And i am sure that the proxy server for kubernetes api server is running?
Is this a issue with minikube?
