### ISSUE TITLE
Outdated Korean contents in dev-1.22-ko.2 branch

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#30000]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.22-ko.2 branch.

Report generated by the following command.
`scripts/diff_l10n_branches.py ko upstream/dev-1.22-ko.1 upstream/dev-1.22-ko.2`

### 71 files to be modified 
1. [x] M1.  `content/en/blog/_posts/2021-08-04-kubernetes-release-1.22.md`  | 1(+XS) 1(-)
1. [x] M2.  `content/en/docs/concepts/architecture/nodes.md`  | 76(+M) 46(-)
1. [x] M3.  `content/en/docs/concepts/cluster-administration/logging.md`  | 1(+XS) 1(-)
1. [x] M4.  `content/en/docs/concepts/cluster-administration/manage-deployment.md`  | 1(+XS) 1(-)
1. [x] M5.  `content/en/docs/concepts/cluster-administration/networking.md`  | 1(+XS) 22(-)
1. [x] M6.  `content/en/docs/concepts/configuration/configmap.md`  | 5(+XS) 0(-)
1. [x] M7.  `content/en/docs/concepts/configuration/manage-resources-containers.md`  | 12(+S) 2(-)
1. [x] M8.  `content/en/docs/concepts/configuration/overview.md`  | 2(+XS) 28(-)
1. [x] M9.  `content/en/docs/concepts/configuration/secret.md`  | 24(+S) 13(-)
1. [x] M10.  `content/en/docs/concepts/containers/container-environment.md`  | 1(+XS) 1(-)
1. [x] M11.  `content/en/docs/concepts/containers/images.md`  | 73(+M) 15(-)
1. [x] M12.  `content/en/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md`  | 4(+XS) 4(-)
1. [x] M13.  `content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md`  | 6(+XS) 6(-)
1. [x] M14.  `content/en/docs/concepts/extend-kubernetes/operator.md`  | 1(+XS) 0(-)
1. [x] M15.  `content/en/docs/concepts/extend-kubernetes/service-catalog.md`  | 1(+XS) 1(-)
1. [x] M16.  `content/en/docs/concepts/overview/components.md`  | 1(+XS) 1(-)
1. [x] M17.  `content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md`  | 4(+XS) 5(-)
1. [x] M18.  `content/en/docs/concepts/overview/working-with-objects/namespaces.md`  | 4(+XS) 1(-)
1. [x] M19.  `content/en/docs/concepts/scheduling-eviction/kube-scheduler.md`  | 1(+XS) 1(-)
1. [x] M20.  `content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md`  | 20(+S) 20(-)
1. [x] M21.  `content/en/docs/concepts/security/controlling-access.md`  | 1(+XS) 1(-)
1. [x] M22.  `content/en/docs/concepts/security/overview.md`  | 1(+XS) 0(-)
1. [x] M23.  `content/en/docs/concepts/services-networking/connect-applications-service.md`  | 3(+XS) 3(-)
1. [x] M24.  `content/en/docs/concepts/services-networking/dns-pod-service.md`  | 2(+XS) 2(-)
1. [x] M25.  `content/en/docs/concepts/services-networking/network-policies.md`  | 2(+XS) 1(-)
1. [x] M26.  `content/en/docs/concepts/services-networking/service.md`  | 27(+S) 5(-)
1. [x] M27.  `content/en/docs/concepts/storage/persistent-volumes.md`  | 26(+S) 14(-)
1. [x] M28.  `content/en/docs/concepts/storage/volumes.md`  | 11(+S) 11(-)
1. [x] M29.  `content/en/docs/concepts/workloads/controllers/cron-jobs.md`  | 25(+S) 17(-)
1. [x] M30.  `content/en/docs/concepts/workloads/controllers/daemonset.md`  | 16(+S) 1(-)
1. [x] M31.  `content/en/docs/concepts/workloads/controllers/deployment.md`  | 16(+S) 14(-)
1. [x] M32.  `content/en/docs/concepts/workloads/controllers/job.md`  | 22(+S) 5(-)
1. [x] M33.  `content/en/docs/concepts/workloads/controllers/replicaset.md`  | 11(+S) 0(-)
1. [x] M34.  `content/en/docs/concepts/workloads/controllers/replicationcontroller.md`  | 8(+XS) 3(-)
1. [x] M35.  `content/en/docs/concepts/workloads/controllers/statefulset.md`  | 16(+S) 8(-)
1. [x] M36.  `content/en/docs/concepts/workloads/pods/_index.md`  | 9(+XS) 2(-)
1. [x] M37.  `content/en/docs/concepts/workloads/pods/init-containers.md`  | 10(+S) 6(-)
1. [x] M38.  `content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md`  | 17(+S) 13(-)
1. [x] M39.  `content/en/docs/contribute/new-content/_index.md`  | 60(+M) 0(-)
1. [x] M40.  `content/en/docs/home/_index.md`  | 2(+XS) 2(-)
1. [x] M41.  `content/en/docs/reference/_index.md`  | 2(+XS) 0(-)
1. [x] M42.  `content/en/docs/reference/access-authn-authz/authorization.md`  | 22(+S) 11(-)
1. [x] M43.  `content/en/docs/reference/access-authn-authz/service-accounts-admin.md`  | 1(+XS) 1(-)
1. [x] M44.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 9(+XS) 15(-)
1. [x] M45.  `content/en/docs/reference/command-line-tools-reference/kube-proxy.md`  | 1(+XS) 1(-)
1. [x] M46.  `content/en/docs/reference/issues-security/security.md`  | 4(+XS) 4(-)
1. [x] M47.  `content/en/docs/reference/kubectl/overview.md`  | 26(+S) 0(-)
1. [x] M48.  `content/en/docs/reference/scheduling/config.md`  | 1(+XS) 1(-)
1. [x] M49.  `content/en/docs/reference/setup-tools/kubeadm/_index.md`  | 1(+XS) 1(-)
1. [x] M50.  `content/en/docs/reference/tools/_index.md`  | 5(+XS) 2(-)
1. [x] M51.  `content/en/docs/reference/using-api/health-checks.md`  | 1(+XS) 1(-)
1. [x] M52.  `content/en/docs/setup/best-practices/certificates.md`  | 47(+M) 3(-)
1. [x] M53.  `content/en/docs/setup/learning-environment/_index.md`  | 3(+XS) 1(-)
1. [x] M54.  `content/en/docs/setup/production-environment/_index.md`  | 1(+XS) 1(-)
1. [x] M55.  `content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md`  | 3(+XS) 3(-)
1. [x] M56.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 5(+XS) 26(-)
1. [x] **M57.**  `content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md`  | **768(+XL) 1138(-)**
1. [x] M58.  `content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md`  | 22(+S) 16(-)
1. [x] M59.  `content/en/docs/tasks/administer-cluster/access-cluster-api.md`  | 1(+XS) 1(-)
1. [x] M60.  `content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md`  | 1(+XS) 1(-)
1. [x] M61.  `content/en/docs/tasks/administer-cluster/highly-available-control-plane.md`  | 9(+XS) 2(-)
1. [x] M62.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md`  | 41(+M) 42(-)
1. [x] M63.  `content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md`  | 1(+XS) 1(-)
1. [x] M64.  `content/en/docs/tasks/configure-pod-container/static-pod.md`  | 8(+XS) 1(-)
1. [x] M65.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md`  | 3(+XS) 1(-)
1. [x] M66.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale.md`  | 1(+XS) 10(-)
1. [x] M67.  `content/en/docs/tasks/tools/install-kubectl-windows.md`  | 4(+XS) 4(-)
1. [x] M68.  `content/en/docs/tutorials/_index.md`  | 2(+XS) 0(-)
1. [x] M69.  `content/en/docs/tutorials/hello-minikube.md`  | 10(+S) 4(-)
1. [x] M70.  `content/en/docs/tutorials/stateful-application/basic-stateful-set.md`  | 1(+XS) 1(-)
1. [x] M71.  `content/en/docs/tutorials/stateful-application/zookeeper.md`  | 1(+XS) 1(-)

### 1 files to be deleted 
1. [x] D1.  `content/en/docs/contribute/new-content/overview.md`

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.22-ko.2` branch.

For example:
```
# checkout `upstream/dev-1.22-ko.2`
...
# check what is updated in the upstream 
git diff upstream/dev-1.22-ko.1 upstream/dev-1.22-ko.2 -- content/en/blog/_posts/2021-08-04-kubernetes-release-1.22.md
# apply changes to content/ko
vi content/ko/blog/_posts/2021-08-04-kubernetes-release-1.22.md
...
# commit and push
...
# make PR to `upstream/dev-1.22-ko.2`
```

## Pages to Update

Pages in content/ko

**Comment by seokho-son** [comment]
M1 은 가급적 신규 컨트리뷰터께 할당하도록 하겠습니다.. ^^

**Comment by seokho-son** [comment]
M58-M71 : @seokho-son

**Comment by yoonian** [comment]
M52-M53, M57 은 제가 해보겠습니다~

**Comment by seokho-son** [comment]
[Tasks assigned]

M1 : @lifeoncloud
M2 : @gochist
M3-M5: @seokho-son
M6-M35: @gochist
M36-M41: @seokho-son
M42-M49 : HEEEEEEEEEEEEEEELP
M50-M51 : @lifeoncloud
M52-M53 : @yoonian 
M54-M56 : @seokho-son
M57 : @yoonian 
M58-M71 : @seokho-son
D1 : @seokho-son

@yoonian 감사합니다. M57은 분량이 많아서, 혹시 이번에 처리가 어려운 경우, 다음 브랜치에서 처리 가능한 것으로 예외 처리 하였습니다..^^ 

나머지는 가급적 일정에 맞춰 진행하려 합니다.

**Comment by jihoon-seo** [comment]
M42 해보겠습니다~

**Comment by seokho-son** [comment]
M43-M49 제가 처리하겠습니다~~

**Comment by seokho-son** [comment]
@lifeoncloud  ko.2 마감 일정이 임박하여, M50은 제가 빠르게 처리하도록 하겠습니다...^^ 양해 부탁드립니다.

**Comment by lifeoncloud** [comment]
@seokho-son ㅠㅠ 감사합니다! 'fatal: bad revision'나와서 애먹고 있었어요ㅠㅠ

**Comment by seokho-son** [comment]
아닙니다~~ 브랜치 관리에 도움주셔서 감사합니다~~ :)

**Comment by seokho-son** [comment]
/close

but #30364 needs to be resolved ;)
