### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by ruslanzelinskyy** [kubernetes/website#30006]
ERR_CONNECTION_TIMED_OUT

Done every step like in docs:
```
minikube delete
minikube start
minikube addons enable ingress

kubectl create deployment web --image=gcr.io/google-samples/hello-app:1.0
kubectl expose deployment web --type=NodePort --port=8080
kubectl get service web
#Wait for ingress controller to deploy
sleep 30
kubectl get pods -n ingress-nginx
kubectl apply -f https://k8s.io/examples/service/networking/example-ingress.yaml
kubectl get ingress
curl hello-world.info
```

Result:
curl: (28) Failed to connect to hello-world.info port 80: Timed out

**Comment by ruslanzelinskyy** [comment]
used windows 10 docker desktop
minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed

**Comment by ruslanzelinskyy** [comment]
Well the issue is pretty uncommon for me:

Ingress for minikube is creating on 192.168.49.2 IP address which should mean LAN (private) network address, Right?
But on my router i have LAN subnet mask 255.255.255.0 which means that all adresses except 192.168.0.* will be handled as public.

Windows DNS also are working pretty odd, instead of forwarding **hello-world.info** requests to 192.168.49.2 which available locally it forwards request on Router IP which is 192.168.0.1 and which handle it as public IP.


So I tried to **set LAN subnet mask from 255.255.255.0 to 255.255.0.0**
Now requests to **hello-world.info** seams to be handled correctly by host.docker.internal [192.168.0.103] instead of 192.168.0.1

Than i discovered Minikube gives this error: 
```
Unable to create dedicated network, this might result in cluster IP change after restart: un-retryable: no free private network subnets found with given parameters (start: "19
2.168.9.0", step: 9, tries: 20)
```

And creates Ingress Service under 172 subnet (what ?)

I also tried to change Docker desktop configuration of Docker subnet from 192.168.65.0/24 to 192.168.0.0/24 but it doesn't work.

Can you please advise what is going on here?

**Comment by ruslanzelinskyy** [comment]
OK, it was pretty hard to detect without docs but solution is pretty simple:
On windows 10:
1. **Set your test host to point on loopback 127.0.0.1 hello-world.info**
2. Run `minikube tunnel`
3. PROFIT

Please close if you think you should.

**Comment by sftim** [comment]
OK, so if you're trying this by running minikube on Windows, you also need to run `minikube tunnel`?

That detail is relevant to the page and possibly also to PR https://github.com/kubernetes/website/pull/29206. Good to know.
/remove-kind support
/kind feature

Let's mention that
/triage accepted
/language en
/priority backlog

**Comment by ruslanzelinskyy** [comment]
> OK, so if you're trying this by running minikube on Windows, you also need to run minikube tunnel?

@sftim yes. As i understand minikube on Windows works differently then on Linux. It uses single docker container and DNS resolving handles with Docker Desktop. 
Please check, but you should know better anyway.
