### ISSUE TITLE
Confusion following steps within “Updating Your App” interactive tutorial

### ISSUE THREAD

**Issue by andyleung** [kubernetes/website#30011]
In the image depository
gcr.io/google-samples/kubernetes-bootcamp

kubernetes-bootcamp v10 image is missing (only v1 was there) which cause error for the last part of the lab.

**Comment by sftim** [comment]
/kind support

I'm afraid @andyleung the exercise expects that step to fail. 
https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/42 might help readers who are confused here.
