### ISSUE TITLE
[ko] Translate docs/tasks/debug-application-cluster/get-shell-running-container.md in Korean

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#30038]
**This is a Feature Request**
Translate [docs/tasks/debug-application-cluster/get-shell-running-container.md](https://github.com/kubernetes/website/blob/dev-1.22-ko.1/content/en/docs/tasks/debug-application-cluster/get-shell-running-container.md) in Korean

**What would you like to be added**

Translate [docs/tasks/debug-application-cluster/get-shell-running-container.md](https://github.com/kubernetes/website/blob/dev-1.22-ko.1/content/en/docs/tasks/debug-application-cluster/get-shell-running-container.md) in Korean

**Why is this needed**

This file is not translated yet.

**Comments**

[https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/](https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/)

/language ko

**Comment by jihoon-seo** [comment]
Translated page:
https://kubernetes.io/ko/docs/tasks/debug-application-cluster/get-shell-running-container/

Related PRs:
- #30328
- #30412

/close
