### ISSUE TITLE
[ko] Translate docs/tasks/debug-application-cluster/debug-stateful-set.md in Korean

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#30039]
**This is a Feature Request**
Translate [docs/tasks/debug-application-cluster/debug-stateful-set.md](https://github.com/kubernetes/website/blob/dev-1.22-ko.1/content/en/docs/tasks/debug-application-cluster/debug-stateful-set.md) in Korean

**What would you like to be added**

Translate [docs/tasks/debug-application-cluster/debug-stateful-set.md](https://github.com/kubernetes/website/blob/dev-1.22-ko.1/content/en/docs/tasks/debug-application-cluster/debug-stateful-set.md) in Korean

**Why is this needed**

This file is not translated yet.

**Comments**

[https://kubernetes.io/docs/tasks/debug-application-cluster/debug-stateful-set/](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-stateful-set/)

/language ko

**Comment by jihoon-seo** [comment]
Translated page:
https://kubernetes.io/ko/docs/tasks/debug-application-cluster/debug-stateful-set/

Related PRs:
- #30329
- #30412

/close
