### ISSUE TITLE
Translate content/en/blog/_posts/2021-08-04-kubernetes-release-1.22.md in Korean

### ISSUE THREAD

**Issue by lifeoncloud** [kubernetes/website#30041]
**This is a Feature Request**

**What would you like to be added**

Translate content/en/blog/_posts/2021-08-04-kubernetes-release-1.22.md in Korean

**Why is this needed**
No translation with content/en/blog/_posts/2021-08-04-kubernetes-release-1.22.md in Korean

**Comments**

Page to Update: https://github.com/kubernetes/website/blob/9c8e57535e5da63f37e70e6e1a0edc9d8fa95664/content/en/blog/_posts/2021-08-04-kubernetes-release-1.22.md

**Comment by jihoon-seo** [comment]
This issue seems okay to close, since the PR #30043 is merged. 😊
/close
