### ISSUE TITLE
setup-tools/kubeadm/: replace link from api-beta2 to api-beta3

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#30040]
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file says:

> For more information on the fields and usage of the configuration you can navigate to our API reference page.

where “API reference page” is a hyperlink to https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/ . The hyperlink shall point instead to https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/ (beta2 → beta3)

**Comment by sftim** [comment]
I opened https://github.com/kubernetes/website/pull/30050 to fix that.

**Comment by siddhantprateek** [comment]
@sftim  this issue is reponed, may I know if I have to open a new PR for this. I guess i was working on the wrong branch and I thought it belongs to `dev-1.23`.

**Comment by neolit123** [comment]
looks like https://github.com/kubernetes/website/pull/30050 merged
/close
