### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/certificate-signing-requests/

### ISSUE THREAD

**Issue by svetoslav-vodenicharov** [kubernetes/website#30057]
Conducted the certificate issue process step by step - the CSR is approved, but there is no status.certificate.
Guess the "Sign" has not been done, please provide example for Sign process
kubernetes v1.21
Regars.

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/ is a reference page

Perhaps, as a feature request, we could add a new task page that shows an example of getting a certificate signed by a CSR signing controller? Is that similar to what you're asking for @svetoslav-vodenicharov ?

/triage needs-information

/language en

**Comment by tengqm** [comment]
I don't think this warrants a new task page. The approve/deny operation is very simple and the operation is not one heavily used.

```
$ kubectl certificate --help
Modify certificate resources.

Available Commands:
  approve     Approve a certificate signing request
  deny        Deny a certificate signing request

Usage:
  kubectl certificate SUBCOMMAND [options]
```
