### ISSUE TITLE
[ko] Translation is missing in ko/docs/concepts/services-networking/ingress

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#30056]
**This is a Bug Report**

**Problem:**
Korean Translation is missing in 
https://kubernetes.io/ko/docs/concepts/services-networking/ingress/#네임스페이스-범위의-파라미터

**Proposed Solution:**
Translate this paragraph in [English page](https://kubernetes.io/docs/concepts/services-networking/ingress/#namespace-scoped-parameters):

> Namespace-scoped parameters avoid the need for a cluster-scoped CustomResourceDefinition for a parameters resource. This further avoids RBAC-related resources that would otherwise be required to grant permissions to cluster-scoped resources.

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/services-networking/ingress/#네임스페이스-범위의-파라미터

/language ko

**Comment by jihoon-seo** [comment]
/assign

[Suggestion]

```
네임스페이스 범위의 파라미터를 사용하면 파라미터 리소스에 대해 
클러스터 범위의 CustomResourceDefinition이 필요하지 않다. 
또한, 클러스터 범위의 리소스에 권한을 부여하는 데 필요한 
RBAC 관련 리소스도 필요하지 않게 만든다.
```

**Comment by ianychoi** [comment]
Closing this issue per the comment: https://github.com/kubernetes/website/issues/30846#issuecomment-1022902088
