### ISSUE TITLE
Known Issues Page

### ISSUE THREAD

**Issue by khenidak** [kubernetes/website#30051]
**This is a Feature Request**
Add a new page for known issues.

**What would you like to be added**
We need a page describing known issues similar to https://github.com/kubernetes/kubernetes/issues/105610 with documentation guiding users to workarounds

**Why is this needed**
We don't have a standard method and known location for all of these which result into:
1. Duplicate bug reporting.
2. Wasted time and resources on users' side. 

FYI @sftim 

**Comments**
The page needs to describe issues, workarounds and impacted versions

**Comment by sftim** [comment]
I'd add this as a new page into the reference section.

/sig docs
/language en
/triage accepted
/priority important-longterm

**Comment by sftim** [comment]
I don't think anyone added that page yet.

There's a separate but possibly relevant piece of work to generate a list of security issues and link to their details.
