### ISSUE TITLE
使用 kubeadm 创建集群 Broken link

### ISSUE THREAD

**Issue by yangyunfeng007** [kubernetes/website#30060]
https://kubernetes.io/zh/docs/setup/release/version-skew-policy/#supported-versions

![image](https://user-images.githubusercontent.com/17523539/136955177-067ac821-8cd0-4307-ab20-a22ead33e33b.png)

**Comment by tengqm** [comment]
/triage accepted
@yangyunfeng007 Would you mind propose a fix?

**Comment by tengqm** [comment]
/triage accepted
/kind feature

This was caused by some recent content reorg in the English site. Some pages were migrated into the content/en/releases directory, out of content/en/docs/. The contents under content/en/releases need to be retranslated, I guess.

```
releases/
├── OWNERS
├── _index.md
├── download.md
├── notes.md
├── patch-releases.md
├── release-managers.md
├── release.md
└── version-skew-policy.md
```

**Comment by tengqm** [comment]
/close
We are catching up anyway.
