### ISSUE TITLE
Migration guide between KubeSchedulerConfig versions

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#30063]
**What would you like to be added**

A section in this page https://kubernetes.io/docs/reference/scheduling/config/ with migration instructions between API versions (v1beta1 to v1beta2 and v1beta2 to v1beta3), similar to this https://kubernetes.io/docs/reference/using-api/deprecation-guide

**Why is this needed**

This is specially important after the removal of v1beta1 (kubernetes/kubernetes#104782) and the introduction of v1beta3 (kubernetes/kubernetes#104251)

**Comments**

The information can be recovered from release notes, although I admit they are scattered.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#api-change

At least these changes are related:

- v1beta1 to v1beta2
    - kubernetes/kubernetes#101822
    - kubernetes/kubernetes#99582
    - kubernetes/kubernetes#99597
 - v1beta2 to v1beta3 (these would need to go in the branch for the next release)
     - kubernetes/kubernetes#104251

**Comment by sftim** [comment]
> when considering where to put this, let's do it in a way that would make sense for something similar for v1beta2 → v1beta3 config, and v1beta3 → v1

One page, with [tabs](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#tabs)?

Things that suggest a task:

**Comment by sftim** [comment]
We could also consider making a whole section of tasks around upgrading. That might cover:
- some of what's in https://kubernetes.io/docs/reference/using-api/deprecation-guide/, but framed step-by-step
- how to move between different API versions for configuration files
- using `kubectl convert`
- how to upgrade your cluster!
- how to upgrade tools, eg `kubectl`

and more!

**Comment by alculquicondor** [comment]
Note that configuration files don't work with kubectl. I think they should be treated separately.

I think the changes won't make enough content for a task (at least for v1beta1 to v1beta2). It's just a handful of bullet points.

Maybe we will require a task for v1beta3 @damemi

**Comment by kerthcet** [comment]
kindly reminding @mehabhalodiya , `v1beta1 -> v1beta2 ` and `v1beta2 -> v1beta3` document migration has been merged.
