### ISSUE TITLE
Add KCNA to training page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30077]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/training/ to mention the [KCNA](https://training.linuxfoundation.org/certification/kubernetes-cloud-native-associate/) qualification.

**Why is this needed**
There's now a KCNA qualification that you can train for.

**Comments**
/kind feature
/language en
/priority important-longterm

**Comment by shannonxtreme** [comment]
/assign

(I just modifying the index.html in the training folder, please LMK if that was not the right way)
