### ISSUE TITLE
API reference loadBalancerSourceRanges: "More info" points to doc without info about SourceRanges

### ISSUE THREAD

**Issue by Kumm-Kai** [kubernetes/website#30080]
**This is a Bug Report**

**Problem:**
Since 1.22 the API reference for `loadBalancerSourceRanges` points to https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/ for more information.
But that documentation **doesn't contain** any information about SourceRanges.

Before 1.22 the reference pointed to https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/ which was removed due to #20232 and #21459.

**Proposed Solutions:**
- Adding documentation about the SourceRanges to https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
- Remove the `More info: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/` part of the API reference.
- Think about adding `Configure Your Cloud Provider's Firewalls` back to the documentation, removing the third party content and updating the link in the API reference. Also renaming the documentation to better fit the scope.
- Pointing to https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support, but that would be even more provider specific and shallow on the information part. And I would guess that it will also be removed in the future.

**Page to Update:**
- https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#servicespec-v1-core
- Output of `kubectl explain`

**Comment by sftim** [comment]
/sig docs network

Which is the web page that doesn't look right @Kumm-Kai?

/language en

It sounds like the fix might need to happen within the [k/kubernetes](https://github.com/kubernetes/kubernetes) repository - if that turns out to be the case, SIG Docs can provide pointers on how and where to fix that. We add that kind of detail so that people picking up the work are clear about the steps to follow when proposing a fix.

**Comment by sftim** [comment]
Thanks, that clears things up.

I think it makes sense to add text similar to
```markdown

When using a Service with `.spec.type` set to `LoadBalancer`, you can specify the IP address ranges that are allowed to access the load balancer,  by setting `.spec.loadBalancerSourceRanges`. This field takes a list of IP CIDR ranges, which Kubernetes will use to configure firewall exceptions.

This field will be ignored if the cloud provider does not support the feature.
```

into https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

/triage accepted
