### ISSUE TITLE
Improve logo layout for https://kubernetes.io/training/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30085]
**This is a Feature Request**

**What would you like to be added**
The narrow (square grid) and wide (single row) logo layouts for https://kubernetes.io/training/ are fine, however there is an intermediate state that we'd like to cut out.
See https://github.com/kubernetes/website/pull/30078#issuecomment-942612149 for an animation showing the issue

**Why is this needed**
It's odd to show the logos in a 3:1 split. Two even rows would look better.

**Comments**
The fix for this should be Sass / CSS changes only.
/area web-development

Follows on from https://github.com/kubernetes/website/issues/30077

**Comment by shannonxtreme** [comment]
I'm interested to see how this works. I spend a good hour fiddling with flexboxes and now I cascadingly hate stylesheets

**Comment by shannonxtreme** [comment]
Also
/triage accepted
