### ISSUE TITLE
[zh] Translate the release contents

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#30096]
The content/en/releases directory is "not" localized. It is a collection of pages migrated from content/en/docs, but it is hard to trace back our original localizations. So ... the best we can do is to retranslate the contents.

/language zh
/kind feature

**Comment by sftim** [comment]
On https://kubernetes.io/zh/ the top menu has a menu item “Release Information” that links to https://kubernetes.io/releases/

I'm guessing there is a related improvement / issue, depending on this one, to:
- localize that text, “Release Information”
- link to the localized release docs if they exist for a localization

(does that sound right?)

**Comment by Sea-n** [comment]
It's almost done by @howieyuen.
/remove-lifecycle rotten
/assign @howieyuen

Most files (`_index.md`, `download.md`, `notes.md`, `patch-releases.md`, `release-managers.md`, `version-skew-policy.md`) are translated last week.
There is only `release.md` file left, which is being reviewing. And `OWNERS` file seems to be unnecessary for localized version.

**Comment by howieyuen** [comment]
all pages are translated.
issue can be closed now.
/close
