### ISSUE TITLE
Glossary: Add a definition for "resource"

### ISSUE THREAD

**Issue by stefanlasiewski** [kubernetes/website#30092]
I just learned about https://kubernetes.io/docs/reference/glossary and I think it's a great tool that will help provide a common language for the community, and also for our team where we struggle often over simple definitions.

I was reading through different definitions, and that many definitions refer to the term "resource", but the term itself is not defined. Some of the usage is confusing. It would  be great to define the term __resource__, and since it's used in different contexts, clarify the usage for those contexts.

Here's a few quotes from the Glossary.

From the following 3 definitions, we know that a "resource" is something like a Deployment or a Pod. A command like`kubectl get pods` will return a list of pod resources and their names. In the API, I can refer to that resource at `/api/v1/pods/some-name`. Although, is _[object](https://kubernetes.io/docs/reference/glossary/?all=true#term-object)_ actually the correct term here and not _resource_? If not, what is the difference between the term __resource__ used here and an __object__?

> * DisruptionDisruptions are events that lead to one or more Pods going out of service. A disruption has consequences for workload resources, such as Deployment, that rely on the affected Pods.

> * Selector
> Allows users to filter a list of resources based on labels.

> * Name
> A client-provided string that refers to an object in a resource URL, such as /api/v1/pods/some-name

The page also uses _resource_ to refer to things in a host context, such as the following definitions. I might call these __node resources__.

> * LimitRangeProvides constraints to limit resource consumption per Containers or Pods in a namespace.

> * Node-pressure eviction
> Also known as:kubelet eviction
> Node-pressure eviction is the process by which the kubelet proactively terminates pods to reclaim resources on nodes

**Comment by afro-coder** [comment]
Hey @sftim I would like to contribute to the issue, however, I'm very new to Kubernetes, I understand that a resource would be something like a Deployment or pod as the OP said or it can also be something like a CPU resource limit(Please correct me if I'm wrong). I'm still confused as to what is the primary definition and how to find the other definitions, any hints would be appreciated.

searching online leads me to articles like this.
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by stefanlasiewski** [comment]
> This looks to me like a duplicate of issue #20074 though.

I'd be fine with moving this question into #20074, although unfortunately that issue is stale and I don't want this issue to get lost.

I do think that newcomers, including people who are experienced with other systems outside of kubernetes, may find parts of the documentation confusing. The context in much of the conversation is not clear. Here's another example from

https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#kubernetes-objects

> Kubernetes objects are persistent entities in the Kubernetes system. Kubernetes uses these entities to represent the state of your cluster. Specifically, they can describe:
>
> * What containerized applications are running (and on which nodes)
> * The resources available to those applications
> * The policies around how those applications behave, such as restart policies, upgrades, and fault-tolerance

I'm not actually sure what "resources" means in this context. Is that text trying to say that an Kubernetes objects have access to Kubernetes resources?
