### ISSUE TITLE
Update namespace definition

### ISSUE THREAD

**Issue by chrismetz09** [kubernetes/website#30095]
**This is a Feature Request**

Good first issue!

**What would you like to be added**
Revised definition of namespace. 

**Why is this needed**
Suggested during Kubecon 21 talk that namespace definition is 5 years old. [Page in question](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/)

**Comments**
[Slides from Kubecon talk](https://static.sched.com/hosted_files/kccncna2021/2e/Beyond%20Namespaces_%20Virtual%20Clusters%20are%20the%20Future%20of%20Multi-Tenancy%20-%20Lukas%20Gentele%2C%20Loft%20Labs.pdf). See slides 5 and 6.

Related issue - https://github.com/kubernetes/website/issues/29307.

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/30086 and https://github.com/kubernetes/website/pull/30086/files both aim to cover this.

**Comment by sftim** [comment]
/close
Fixed in #30088
