### ISSUE TITLE
Translate README in Urdu

### ISSUE THREAD

**Issue by ghulamyazdani** [kubernetes/website#30102]
**This is a Feature Request**
There are so many people whose native language is Urdu and struggle in reading English . It would be great if readme in Urdu lang is added.

**What would you like to be added**

Readme, while translated in Urdu, should be added.

**Why is this needed**
Because so many people around the world (whose native language is Urdu) struggle to read English. Adding an Urdu readme file will be very helpful for them.
**Comments**

**Comment by sftim** [comment]
Here's our guide to [starting a new localization](https://kubernetes.io/docs/contribute/localization/#start-a-new-localization) of the Kubernetes docs.
