### ISSUE TITLE
Ephemeral Container securityContext still appearing as not-allowed in documentation

### ISSUE THREAD

**Issue by verb** [kubernetes/website#30100]
**This is a Bug Report**

**Problem:**

Setting `securityContext` for ephemeral containers is allowed as of Kubernetes 1.22, but it's still showing up as a "not allowed" field here: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#not-allowed

**Proposed Solution:**

This page looks to be autogenerated based on the API definition, but I'm not sure how it's detecting not allowed fields. If it's automatic we'll correct the metadata or if it's curated then just reclassify the field in docs.

**Page to Update:**
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#not-allowed

**Comment by sftim** [comment]
The fix is likely to happen within https://github.com/kubernetes-sigs/reference-docs/

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/ _is_ autogenerated.
I don't think https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-resourcesdocs/config received field updates for v1.22

**Comment by kbhawkey** [comment]
Track the update of the documentation as an issue in this repository.
/triage accepted

**Comment by verb** [comment]
Looks like this is still happening, and also `EphemeralContainers` is showing up under the alpha heading even though its description says (correctly) that it's beta. This dropped off my radar, but I'll take a look at it in the next few days.

/remove-lifecycle stale

**Comment by sftim** [comment]
/remove-priority critical-urgent
/priority important-soon
/sig security

@verb you're welcome to make a case for raising it back to critical. What would be the motivation there?

**Comment by verb** [comment]
Hi @sftim, I *don't* wish to make that case. I was just trying to assign a priority according to guidance [here](https://kubernetes.io/docs/contribute/review/for-approvers/) and [here](https://www.kubernetes.dev/docs/guide/issue-triage/#step-three-define-priority). The documentation is wrong for a core feature, which seems like a "fix it now" rather than "fix it in the next release" priority.

The priority isn't important to me, though. Happy for it to be whatever you think is best.

**Comment by sftim** [comment]
This repo uses continuous deployment (we don't wait for a release for fixes). Anyway, yes, it looks important.
