### ISSUE TITLE
Broken link in k8s.io/releases/release-managers/

### ISSUE THREAD

**Issue by niteshseram** [kubernetes/website#30116]
**This is a Bug Report**

**Problem:**
All the `Security Response Committee` hyperlinks which are pointing to this [link](https://github.com/kubernetes/community/blob/master/committee-product-security/README.md) are broken.
**Proposed Solution:**
I suppose it should point to this [link](https://github.com/kubernetes/community/blob/master/committee-security-response/README.md) now. 
**Page to Update:**
https://kubernetes.io/releases/release-managers/

/language en

**Comment by Shatakshi0805** [comment]
Can I work on this?
