### ISSUE TITLE
Translate tasks/access-application-cluster/ingress-minikube.md into Korean

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#30121]
This is a Feature Request
Translate [/content/en/docs/tasks/access-application-cluster/ingress-minikube.md] in Korean

What would you like to be added
Translate [/content/ko/docs/tasks/access-application-cluster/ingress-minikube.md] in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

/language ko
/assign

**Comment by jihoon-seo** [comment]
Translated page:
https://kubernetes.io/ko/docs/tasks/access-application-cluster/ingress-minikube/

Related PRs:
- #30272
- #30412

/close
