### ISSUE TITLE
Update ingress class setup note in the k8s.io/docs/concepts/services-networking/ingress-controllers/ page

### ISSUE THREAD

**Issue by vitalyrychkov** [kubernetes/website#30126]
Hello,

Kubernetes 1.18 introduced the IngressClass resource, effectively replacing the kubernetes.io/ingress.class annotation convention. The page above only advises to set ingress class as ingress.class annotation which is outdated. Update needed in all versions 1.18+ including  1.22.

Source:
https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

**Comment by fOO223Fr** [comment]
@vitalyrychkov from what i understand
updated is needed in this page: https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/#using-multiple-ingress-controllers in the section "Using multiple Ingress controllers" is taht correct?

/assign fOO223Fr
