### ISSUE TITLE
Invalid link in k8s.io/docs/concepts/overview/working-with-objects/finalizers/

### ISSUE THREAD

**Issue by UOndro** [kubernetes/website#30139]
Hi, 

The link https://kubernetes.io/concepts/overview/working-with-objects/owners-dependents/ returns 404, and the link is used here -> https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/

**Comment by mayocream** [comment]
In this section https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/#owners-labels-finalizers

We might run `linkchecker.py` script to check if there are other links that have the wrong path.

**Comment by sandipanpanda** [comment]
owner references now links to this: https://kubernetes.io/concepts/overview/working-with-objects/owners-dependents/ which is 404, in order to fix this issue, I should link it to https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/. Am I right?
