### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by tepecat** [kubernetes/website#30149]
Hallo,
this site looks a little bit outdated, but this is not my main concern.

Where can I find md5 or sha checksums for downloaded files? I miss any checksum check. It is good practice, don't install anything blind into a system.

I mean something like this
```
curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-linux-${ARCH}-${CNI_VERSION}.tgz" | sudo tar -C /opt/cni/bin -xz
```

Are there any reasons for this kind of installation?

viele Grüsse,
thomas.

**Comment by neolit123** [comment]
Artifacts that k8s publishes such as kubectl do have checksum files next to
the binaries.

Same goes for the thirt party tools like cni-plugins. Except that those are
stored in github releases instead of GCS.

**Comment by sbarikdev** [comment]
Hi folks!
Is there any update on this issue?
If it seems good then I'm up for it.
