### ISSUE TITLE
[es] Add feature gate to the spanish glossary

### ISSUE THREAD

**Issue by raelga** [kubernetes/website#30144]
**What would you like to be added**

 Add the definition of feature gate in Spanish as glossary term, so it can be referenced.

**Why is this needed**

Feature Gate is a tricky word to translate to Spanish, as is a well known Kubernetes concept. So the best approach is to use the original term, but with a tooltip providing more information.

/assign
/label language/es

**Comment by Midas847** [comment]
Hey, I want to work on this issue. Can you explain it more?

**Comment by Alekhya193** [comment]
hey! i want to work on this issue

**Comment by raelga** [comment]
Awesome @Alekhya193 , feel free to open a PR with the glossary word.

**Comment by srinivas-pokala** [comment]
@raelga, I am new to k8s community. I want to work on this issue. can you guide me on this issue.

**Comment by ManriqueGarcia** [comment]
Hi, I am not surewhich repository I have to choose make the  pull request.

Regards

**Comment by raelga** [comment]
Hello @ManriqueGarcia , the feature gate definition should go here:

https://github.com/kubernetes/website/tree/main/content/es/docs/reference/glossary
