### ISSUE TITLE
[ja] Update `content/ja/docs/concepts/architecture/nodes.md`

### ISSUE THREAD

**Issue by riita10069** [kubernetes/website#30156]
**This is a Feature Request**

**What would you like to be added**

About `content/ja/docs/concepts/architecture/nodes.md`

* Graceful node shutdown 
* Swap memory management 

**Why is this needed**

Graceful node shutdown is FEATURE STATE: Kubernetes v1.21 [beta] 
and Swap memory management is FEATURE STATE: Kubernetes v1.22 [alpha] 

The Japanese documents do not reflect the latest updates of them.
In addition to that, I made some corrections.

**Comments**

**Comment by nasa9084** [comment]
/remove-lifecycle rotten
because the related PR is under reviewing

/triage accepted
