### ISSUE TITLE
Issue with k8s.io/zh/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by moluzhui** [kubernetes/website#30172]
**This is a Bug Report**

**Problem:**
When I create a custom scheduler using the page's YAML, I get the following error
```
kubectl logs -f my-scheduler-64b9ffdbf-6clcg -n kube-system
I1021 07:51:49.297528       1 registry.go:150] Registering EvenPodsSpread predicate and priority function
I1021 07:51:49.297595       1 registry.go:150] Registering EvenPodsSpread predicate and priority function
I1021 07:51:50.371878       1 serving.go:313] Generated self-signed cert in-memory
W1021 07:51:52.038924       1 authentication.go:349] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
 Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
W1021 07:51:52.038975       1 authentication.go:298] Continuing without authentication configuration. This may treat all requests as anonymous.
W1021 07:51:52.038986       1 authentication.go:299] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
W1021 07:51:52.040797       1 options.go:324] Neither --kubeconfig nor --master was specified. Using default API client. This might not work.
I1021 07:51:52.058298       1 registry.go:150] Registering EvenPodsSpread predicate and priority function
I1021 07:51:52.058331       1 registry.go:150] Registering EvenPodsSpread predicate and priority function
W1021 07:51:52.062732       1 authorization.go:47] Authorization is disabled
W1021 07:51:52.062773       1 authentication.go:40] Authentication is disabled
I1021 07:51:52.062812       1 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I1021 07:51:52.065505       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1021 07:51:52.065543       1 shared_informer.go:223] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1021 07:51:52.066167       1 secure_serving.go:178] Serving securely on [::]:10259
I1021 07:51:52.066606       1 tlsconfig.go:240] Starting DynamicServingCertificateController
E1021 07:51:52.068652       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1021 07:51:53.350381       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1021 07:51:55.293749       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1021 07:51:59.618667       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1021 07:52:10.488750       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E1021 07:52:23.561973       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

It appears that the **ClusterRole** for **system: kube-scheduler** does not have access to configMap resources

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sbarikdev** [comment]
In order to run your scheduler in a Kubernetes cluster, create the deployment specified in the config below in a Kubernetes cluster:

kubectl create -f my-scheduler.yaml
Verify that the scheduler pod is running:

kubectl get pods --namespace=kube-system
NAME                                           READY     STATUS    RESTARTS   AGE
....
my-scheduler-lnf4s-4744f                       1/1       Running   0          2m
...
You should see a "Running" my-scheduler pod, in addition to the default kube-scheduler pod in this list.

Enable leader election
To run multiple-scheduler with leader election enabled, you must do the following:

First, update the following fields in your YAML file:

--leader-elect=true
--lock-object-namespace=<lock-object-namespace>
--lock-object-name=<lock-object-name>
Note: The control plane creates the lock objects for you, but the namespace must already exist. You can use the kube-system namespace.
If RBAC is enabled on your cluster, you must update the system:kube-scheduler cluster role. Add your scheduler name to the resourceNames of the rule applied for endpoints and leases resources, as in the following example:

kubectl edit clusterrole system:kube-scheduler

**Comment by sbarikdev** [comment]
@moluzhui if the issue is resolved, please close it.

**Comment by jbg** [comment]
@sbarikdev This issue isn't resolved. Following the instructions on the (English) documentation precisely leads to the following errors repeated constantly in the my-scheduler logs:

```
requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
reflector.go:138] runtime/asm_arm64.s:1133: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
reflector.go:324] runtime/asm_arm64.s:1133: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

Running this (not mentioned anywhere in the documentation) resolves it:

```
kubectl create rolebinding -n kube-system my-scheduler-extension-apiserver-authentication-reader --role=extension-apiserver-authentication-reader --serviceaccount=kube-system:my-scheduler
```

**Comment by JingbenShi668** [comment]
> @sbarikdev This issue isn't resolved. Following the instructions on the (English) documentation precisely leads to the following errors repeated constantly in the my-scheduler logs:
> 
> ```
> requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
> reflector.go:138] runtime/asm_arm64.s:1133: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
> reflector.go:324] runtime/asm_arm64.s:1133: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
> ```
> 
> Running this (not mentioned anywhere in the documentation) resolves it:
> 
> ```
> kubectl create rolebinding -n kube-system my-scheduler-extension-apiserver-authentication-reader --role=extension-apiserver-authentication-reader --serviceaccount=kube-system:my-scheduler
> ```
Yes, your solution is correct. The error info  in my k8s cluster is as follows.
`W1109 15:30:32.624055       1 reflector.go:424] pkg/server/dynamiccertificates/configmap_cafile_content.go:206: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system".
E1109 15:30:32.624081       1 reflector.go:140] pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:my-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"`

Yes, we can solve the problem by creating new clusterrolebinding for your own serviceaccount  related to your customized kube-scheduler. 
The clusterrolebinding creating command is the following command in  k8s in higher version.
`kubectl create clusterrolebinding \
    -n kube-system my-scheduler-extension-apiserver-authentication \
    --clusterrole=extension-apiserver-authentication-reader \
    --serviceaccount=kube-system:my-scheduler`
