### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/storage-classes/

### ISSUE THREAD

**Issue by lzolezzi** [kubernetes/website#30182]
In the section Azure Disk storage class (starting from v1.7.2) , its specifies the parameter  **resourceGroup** when the correct one is **resourcegroup** (no camelcase)

**Comment by Kartik494** [comment]
@lzolezzi As per this concern the `resourceGroup` is used as in documentation only, not for any yaml file?

**Comment by lzolezzi** [comment]
> @lzolezzi As per this concern the `resourceGroup` is used as in documentation only, not for any yaml file?

Yes as far as I know

**Comment by Kartik494** [comment]
Is there any example yaml you have to test whether it's `resourceGroup` in camel-case or not

**Comment by tengqm** [comment]
According to microsoft official docs, this field should be named 'resourceGroup'.
According to azure-disk CSI implementation, this field should be named 'resourcegroup'.
I believe the implementation rather than the docs.
/remove-lifecycle rotten
