### ISSUE TITLE
[ko] Incorrectly  translated content in /docs/concepts/services-networking/ingress

### ISSUE THREAD

**Issue by imjeongwoo** [kubernetes/website#30192]
**This is a Bug Report**

**Problem:**
There is awkwardly translated content in https://kubernetes.io/ko/docs/concepts/services-networking/ingress/#경로-유형
> /foo/bar 와 /foo/bar/baz 와 일치하지만, /foo/barbaz 는 일치하지 않는다

**Proposed Solution:**
- **Incorrect translation**
    - /foo/bar 와 /foo/bar/baz 와 일치하지만, /foo/barbaz 는 일치하지 않는다

- **I suggest**
    - /foo/bar `는` /foo/bar/baz 와 일치하지만, /foo/barbaz `와는` 일치하지 않는다

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/services-networking/ingress/#경로-유형

/language ko

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #30195. 😊
/close
