### ISSUE TITLE
List All Container Images Running in a Cluster

### ISSUE THREAD

**Issue by imoisharma** [kubernetes/website#30206]
As a reporter,

I noticed today, in the [List Container images by Pod section](https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/#list-container-images-by-pod) contains equal to sign while putting the output as json. It's kind of look bug to me. 

The bug can be seen under List container images by pod section 
https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/

The file to be edited can be found here
https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/list-all-running-container-images.md

Best Regards
Mohit Sharma

**Comment by mehabhalodiya** [comment]
> I don't think this is actually a bug. We could change the formatting for aesthetics.
> 
> /language en

It's not a bug. 
Agree with @sftim

**Comment by mehabhalodiya** [comment]
Hey @jihoon-seo @seokho-son
Do check on issue triage for this!
Thank you.

**Comment by imoisharma** [comment]
Can we close the issue as PR is already merged?

**Comment by sftim** [comment]
Not really a bug, but we fixed it anyway.

/close
