### ISSUE TITLE
[zh] Incorrect translations or incorrect formats on kubeadm

### ISSUE THREAD

**Issue by calvin0327** [kubernetes/website#30218]
**This is a Bug Report**

**Problem:**
I read through the document of kubeadm and found some problem:
* incorrect translations
* Incorrect spelling of words
* incorrect formatting

**Proposed Solution:**
Although it does not affect reading, it will be better after modification.

**Page to Update:**
https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/
https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by mayocream** [comment]
Closing this issue since fixed.
/close
