### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by jeasterman-zz** [kubernetes/website#30244]
I get the error 
"Error: required flag(s) "image" not set" when trying to perform Module 2.

**Comment by jihoon-seo** [comment]
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

![image](https://user-images.githubusercontent.com/46767780/140848580-8afa1be9-5cff-4f1d-b7ca-0406248c2a93.png)

It works for me.

- Windows 10 Enterprise 20H2
- Chrome 95.0.4638.69

/kind support
