### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by irataxy** [kubernetes/website#30259]
The following command does not function correctly:

```
echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"; 
kubectl proxy
```

The second terminal opens and displays the following:

`Permission denied (publickey,password).
`
I received the same result on two work computers: Mac OS 11.6, Chrome Version 95.0.4638.54 and
Windows 10 Enterprise Version 1909, Chrome Version 95.0.4638.54

It also did not work on another Mac of mine, which is not subject to any corp control.

**Comment by jihoon-seo** [comment]
![image](https://user-images.githubusercontent.com/46767780/140848580-8afa1be9-5cff-4f1d-b7ca-0406248c2a93.png)

It works for me too.

- Windows 10 Enterprise 20H2
- Chrome 95.0.4638.69

**Comment by irataxy** [comment]
This works now for me. Thanks!
