### ISSUE TITLE
[ko] Wrong Korean translations

### ISSUE THREAD

**Issue by msyhu** [kubernetes/website#30271]
**This is a Bug Report**

**Problem:**
- https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node/ 에 오역 존재.
- 향후에는 파드의 노드 어피니티 요구 사항을 충족하지 않는 노드에서 파드를 제거한다는 점을 제외하고는 `preferredDuringSchedulingIgnoredDuringExecution` 와 동일한 `requiredDuringSchedulingIgnoredDuringExecution` 를 제공할 계획이다.

**Proposed Solution:**
- 영어 원문을 번역해본 결과 밑과 같이 고치는 것을 제안함.
- In the future we plan to offer `requiredDuringSchedulingRequiredDuringExecution `which will be identical to `requiredDuringSchedulingIgnoredDuringExecution `except that it will evict pods from nodes that cease to satisfy the pods' node affinity requirements.
- 향후에는 파드의 노드 어피니티 요구 사항을 충족하지 않는 노드에서 파드를 제거한다는 점을 제외하고는 `requiredDuringSchedulingIgnoredDuringExecution` 와 동일한 `requiredDuringSchedulingRequiredDuringExecution` 를 제공할 계획이다. 

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/assign-pod-node/

/language ko

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #30301. 😊
/close
