### ISSUE TITLE
Clarify kubelet ephemeral storage enforcement behavior when using two filesystems

### ISSUE THREAD

**Issue by mrunalp** [kubernetes/website#30283]
**Problem:**
The kubelet doesn't consider the container writeable layer for ephemeral storage when the imagefs is on a separate filesystem from the root storage. This isn't clear in the current documentation. 

**Proposed Solution:**
Update the documentation to describe the current kubelet behavior.

**Page to Update:**
https://github.com/kubernetes/website/blob/dc262ad58bdb2b760def8866fd3592a8958792bb/content/en/docs/concepts/configuration/manage-resources-containers.md

**Comment by Kartik494** [comment]
Hi @mrunalp Could you please elaborate how you want the behaviour to be documented.

**Comment by Kartik494** [comment]
@mrunalp could you please take a look on the query.

**Comment by SergeyKanzhelev** [comment]
/cc @rphillips 

this might already be done

**Comment by rphillips** [comment]
Added here https://github.com/kubernetes/website/pull/36397

/close
