### ISSUE TITLE
Translate tasks/extend-kubernetes/setup-konnectivity.md into Korean

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#30285]
This is a Feature Request
Translate [/content/en/docs/tasks/extend-kubernetes/setup-konnectivity.md] in Korean

What would you like to be added
Translate [/content/ko/docs/tasks/extend-kubernetes/setup-konnectivity.md] in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

/language ko
/assign

**Comment by jihoon-seo** [comment]
Translated page:
https://kubernetes.io/ko/docs/tasks/extend-kubernetes/setup-konnectivity/

Related PRs:
- #30310
- #30412

/close
