### ISSUE TITLE
Replace words 'master', 'slave' with something else

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#30284]
**This is a Feature Request**

**What would you like to be enhanced**

Replace words 'master', 'slave' with something else.
- https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/
- https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/
- ...

For example, in https://kubernetes.io/docs/tutorials/stateless-application/guestbook/ ,
the terms 'redis-leader' and 'redis-follower' are used.

**Why is this needed**
It seems good to avoid to use the words like 'master' and 'slave'.

**Comments**

/language en

**Comment by niteshseram** [comment]
I think `leader` ad `follower` sounds good to me. But there are other alternative names like `conductor` and `follower`, `primary` and `standby`, `source` and `sink`, `primary` and `replica`. Do let me know which one sounds good? Would love to raised a PR.

**Comment by shannonxtreme** [comment]
It depends on the context too. Where applicable, replace Kubernetes master with control plane. Primary/secondary is a good substitute for controllers with that master/slave terminology. 

Worth doing multiple smaller PRs for this so that instances can be discussed and reviewed.

**Comment by jihoon-seo** [comment]
Thank you all for your comments!

@AvineshTripathi 
> I wondering if the label kind/feature is appropriate for this issue

This label was added because I used the "Feature Request" issue template.
Let's remove this! 😊

/remove-kind feature

**Comment by jihoon-seo** [comment]
This issue is a duplicate of issue #21621.
/triage duplicate

**Comment by sftim** [comment]
/close
as a duplicate
