### ISSUE TITLE
Kubernetes Security Announce RSS feed link is not working

### ISSUE THREAD

**Issue by ngeorgakopoulos-deloitte** [kubernetes/website#30293]
> You can also subscribe to an RSS feed of the above using this [link](https://groups.google.com/forum/feed/kubernetes-security-announce/msgs/rss_v2_0.xml?num=50).

The link https://groups.google.com/forum/feed/kubernetes-security-announce/msgs/rss_v2_0.xml?num=50 is not working.

**Comment by dhuckmann** [comment]
[It looks like Google Groups removed the RSS feature sometime in late 2021](https://support.google.com/groups/thread/118690869/when-will-googlegroups-rss-feed-be-back-online?hl=en). There is no longer a way to pull the security advisories via RSS, without introducing additional complexity/point of failure with a third party service.

A side effect of this, is that there is no longer an easy way to consume security advisories without either a: 

a) Google account.
b) Web scraper.

Additionally, anyone who was relying on RSS for notifications is no longer receiving them.

**Comment by sftim** [comment]
Fixed in 9486fa2c65a8c4d298fdab81ee5c9131a8bab831.
