### ISSUE TITLE
Issue with k8s.io/docs/reference/issues-security/security/

### ISSUE THREAD

**Issue by amirkCA** [kubernetes/website#30308]
the link:https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md is broken

**Comment by divya-mohan0209** [comment]
Hello @amirkCA, where did you find the link? And could you provide more details around where you intend to replace it?

**Comment by Shubham82** [comment]
Hi @divya-mohan0209 
The link to the page is mentioned as the title of this issue. and the broken link (all Kubernetes bug reports) is under [Report a Vulnerability](https://kubernetes.io/docs/reference/issues-security/security/#report-a-vulnerability)

**Correct link**:  https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml

**Comment by divya-mohan0209** [comment]
Thank you @Shubham82 !
/triage-acceptec

**Comment by divya-mohan0209** [comment]
@Shubham82 : Could you amend the body if the issue to reflect the above?

**Comment by Shubham82** [comment]
Hi @divya-mohan0209 
I can't amend the body of the issue as I didn't create the issue. For the PR  I'm up for it and will soon create a PR.

**Comment by divya-mohan0209** [comment]
Hello @amirkCA could you please amend the body of the issue properly?

**Comment by Shubham82** [comment]
Fixed it here: #30313
