### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by trevorboydsmith** [kubernetes/website#30314]
- the example documentation for this page runs the pods with port 80 and the user is root user.
- current best practice that i've seen is to not run any pods with root user.

#### suggestion: so i think the documentation should not be showing users examples where your pods run as root user... when every production environment and guide says "do not run pods with root user".

the docs can be changed to instead show the pods running as a non-root user and have the containers running at port 8080 and then have the service run with port 80 and point to the container port 8080.

p.s. i wrote this because i am relatively new to kubernetes and coworkers are all saying "don't run any pods with root user" and then i see your guide and it is running as root user. (the other web page runs the nginx pod with root user too... i think https://kubernetes.io/docs/concepts/workloads/pods/ .)

**Comment by Kartik494** [comment]
@trevorboydsmith just for clarification i want to know where it is documented that the deployment from which pods  are running are root user?

**Comment by Kartik494** [comment]
I think from  pods prospective we are looking for [nslookup](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#dns) command here or exec into the pod
