### ISSUE TITLE
k8s service label selector

### ISSUE THREAD

**Issue by hahamofu** [kubernetes/website#30340]
the k8s service just suppport selector, like this:
![image](https://user-images.githubusercontent.com/67695348/140022940-831d2e28-9133-46e5-9844-9784adf402f1.png)

but the deployment support the selector with matchLabels and matchExpressions，like this:
![image](https://user-images.githubusercontent.com/67695348/140023159-9a1db2e6-432f-4306-951b-11cbebd4383e.png)

I I want to know when k8s service can also support matchLabels and matchExpressions

**Comment by ashish-jaiswar** [comment]
hi, I want to work on that issues.

**Comment by hahamofu** [comment]
@ashish-jaiswar: Thanks a lot! Looking forward to your reply.

**Comment by ashish-jaiswar** [comment]
@hahamofu k8s service not support matchLabels and matchExpressions , if you are adding it in service yaml file it will give error because service spec only support equality-based selectors and deployment is a newer resource that support only equality-based and set-based.
