### ISSUE TITLE
Update crictl version in the docs

### ISSUE THREAD

**Issue by aahemm** [kubernetes/website#30349]
**This is a Feature Request**

**What would you like to be added**
The version of the crictl in "install kubeadm" doc when installing without package managers is v1.17.0. It should be v1.22.0.

**Why is this needed**
 I think it should be updated because newer versions are available unless there are compatibility issues with Kubelet. 

**Comments**

This is where problem exists: 
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

**Comment by Babapool** [comment]
Hello, I would want to work on this issue as my 1st PR . Can you please assign this to me :)

**Comment by Babapool** [comment]
@aahemm Thanks. Just to confirm I have to change the crictl version to v1.22.0.

**Comment by aahemm** [comment]
I'not sure. Maybe kubelet is not compatible with crictl v1.22.0 or there was another reason.

**Comment by neolit123** [comment]
this matrix might be out of date, but according to it >=1.16 critools are compatible with >=1.16 kubernetes:
https://github.com/kubernetes-sigs/cri-tools#current-status

**Comment by neolit123** [comment]
i'd say just send the PR to update and if something breaks for someone users will report it..

**Comment by Babapool** [comment]
Okay sure. Thanks
