### ISSUE TITLE
Outdated Korean windows/intro-windows-in-kubernetes.md

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#30364]
**This is a Bug Report**

**Problem:**
content/ko/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
is outdated

**Proposed Solution:**
Update the outdated 

content/**ko**/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md 

according to 

content/**en**/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md

- check what is updated in the upstream (compare with latest English document)
git diff upstream/**dev-1.22-ko.1** upstream/dev-1.22-ko.**X**-- content/**en**/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md

- apply changes to content/ko
vi content/**ko**/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md

Ref: #30000

**Page to Update:**
https://kubernetes.io/ko/docs/setup/production-environment/windows/intro-windows-in-kubernetes/

/language ko

**Comment by seokho-son** [comment]
Ref: #30363 (for adding outdated node)

**Comment by seokho-son** [comment]
https://github.com/kubernetes/website/issues/30414
에서 추가로 변경이 있습니다.

M27. content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md | 5(+XS) 12(-)

**Comment by jihoon-seo** [comment]
영문 파일 (`content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md`) 에 큰 변화가 있을 예정이니,
영문 파일 작업이 어느 정도 완료될 때까지 기다려 보는 것도 좋겠습니다. 😊

- #29894
- #31428
- #31457

**Comment by jihoon-seo** [comment]
@yoonian 님~~
https://github.com/kubernetes/website/issues/34903#issuecomment-1189893230 에 따라
제가 작업하겠습니다~~ 😊
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35423 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
