### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by HB116** [kubernetes/website#30399]
## this is chrome console
```js
### Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:1313/js/jquery-3.3.1.min.js' with computed SHA-256 integrity 'T+aPohYXbm0fRYDpJLr+zJ9RmYTswGsahAoIsNiMld4='. The resource has been blocked.
script.js:63 
### Uncaught ReferenceError: $ is not defined
    at script.js:63
    at script.js:220
(index):267 
### Uncaught ReferenceError: $ is not defined
    at 127.0.0.1/:267
127.0.0.1/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:1313/js/popper-1.14.3.min.js' with computed SHA-256 integrity 'iVAHoM0OdpydTDdj0rPN0J3DwZwQNpKQYd8yOk/hAbo='. The resource has been blocked.
127.0.0.1/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:1313/js/bootstrap-4.3.1.min.js' with computed SHA-256 integrity 'O82ALp93hJ58HpPIcnn7uwTUWUnSvnmwNWbOrN4psVg='. The resource has been blocked.
main.js:65 
### Uncaught ReferenceError: jQuery is not defined
    at main.js:65
```

## cmd in here(but this is ok):
=================================>hugo server --buildFuture
Start building sites …
hugo v0.89.2-63E3A5EB+extended windows/amd64 BuildDate=2021-11-08T15:22:24Z VendorInfo=gohugoio
WARN 2021/11/09 09:55:59 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url

                   |  EN  | ZH  | KO  | JA  | FR  | IT  | DE  | ES  | PT-BR | ID  | RU  | VI  | PL  | UK
-------------------+------+-----+-----+-----+-----+-----+-----+-----+-------+-----+-----+-----+-----+------
  Pages            | 1394 | 926 | 519 | 403 | 338 |  71 | 160 | 274 |   170 | 335 | 155 |  77 |  69 |  92
  Paginator pages  |   40 |   7 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0
  Non-page files   |  486 | 356 | 190 | 260 |  73 |  20 |  17 |  33 |    29 | 105 |  24 |   8 |   6 |  20
  Static files     |  803 | 803 | 803 | 803 | 803 | 803 | 803 | 803 |   803 | 803 | 803 | 803 | 803 | 803
  Processed images |    1 |   1 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0
  Aliases          |    9 |   1 |   2 |   0 |   0 |   1 |   0 |   0 |     1 |   1 |   1 |   0 |   0 |   0
  Sitemaps         |    2 |   1 |   1 |   1 |   1 |   1 |   1 |   1 |     1 |   1 |   1 |   1 |   1 |   1
  Cleaned          |    0 |   0 |   0 |   0 |   0 |   0 |   0 |   0 |     0 |   0 |   0 |   0 |   0 |   0

Built in 10134 ms
Watching for changes in E:\go_www\src\website-main2\{archetypes,assets,content,data,i18n,layouts,package.json,postcss.config.js,static,themes}
Watching for config changes in E:\go_www\src\website-main2\config.toml, E:\go_www\src\website-main2\themes\docsy\config.toml, E:\go_www\src\website-main2\go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

**Comment by HB116** [comment]
my proplem: $ is not defined

===>

### my problem: $ is not defined
sorry

**Comment by ashish-jaiswar** [comment]
I want to work on that issues.
