### ISSUE TITLE
List All Container Images Running in a Cluster

### ISSUE THREAD

**Issue by amalic** [kubernetes/website#30409]
Contrary to the title, this [page](https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/) shows how to list all images of pods only. 

To get all images this one works for me:
```
kubectl get pods --all-namespaces -o jsonpath="{..image}" |\
tr -s '[[:space:]]' '\n' |\
sort |\
uniq -c
```

**Comment by sftim** [comment]
@amalic can you also show an example of the incorrect output you see when following the existing documentation, and point out why it's wrong?

/language en

**Comment by Kartik494** [comment]
@sftim @amalic i have tested the command in my env and i got the expected output.

**Comment by sftim** [comment]
/triage needs-information
/language en

I don't (yet) see anything to fix.
