### ISSUE TITLE
[ja]Missing link to API Reference

### ISSUE THREAD

**Issue by YuikoTakada** [kubernetes/website#30401]
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/ja/docs/concepts/overview/kubernetes-api/ , link to API Reference is missing. This link points to https://kubernetes.io/ja/docs/reference/kubernetes-api/ but this page doesn't exist.

**Proposed Solution:**
Fix link to correct URL. Currently, there is no `kubernetes-api.md` in `content/ja/docs/reference` , so fixing link to points `content/docs/reference/kubernetes-api.md` (English page) is appropriate solution?

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/overview/kubernetes-api/

**Comment by nasa9084** [comment]
I think this issue is fixed by #30858
/close
