### ISSUE TITLE
Outdated Korean contents in dev-1.22-ko.3

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#30414]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.22-ko.3 branch.

Report generated by the following command.
`scripts/diff_l10n_branches.py ko upstream/dev-1.22-ko.2 upstream/dev-1.22-ko.3`

### 38 files to be modified 
1. [x] M1.  `content/en/docs/concepts/architecture/nodes.md`  | 17(+S) 1(-)
1. [x] M2.  `content/en/docs/concepts/cluster-administration/networking.md`  | 1(+XS) 7(-)
1. [x] M3.  `content/en/docs/concepts/extend-kubernetes/_index.md`  | 3(+XS) 3(-)
1. [x] M4.  `content/en/docs/concepts/overview/components.md`  | 1(+XS) 5(-)
1. [x] M5.  `content/en/docs/concepts/overview/working-with-objects/namespaces.md`  | 1(+XS) 2(-)
1. [x] M6.  `content/en/docs/concepts/security/overview.md`  | 7(+XS) 7(-)
1. [x] M7.  `content/en/docs/concepts/services-networking/network-policies.md`  | 1(+XS) 1(-)
1. [x] M8.  `content/en/docs/concepts/services-networking/service.md`  | 3(+XS) 0(-)
1. [x] M9.  `content/en/docs/concepts/workloads/controllers/cron-jobs.md`  | 1(+XS) 1(-)
1. [x] M10.  `content/en/docs/concepts/workloads/controllers/deployment.md`  | 22(+S) 22(-)
1. [x] M11.  `content/en/docs/concepts/workloads/controllers/replicationcontroller.md`  | 1(+XS) 1(-)
1. [x] M12.  `content/en/docs/concepts/workloads/pods/_index.md`  | 16(+S) 1(-)
1. [x] M13.  `content/en/docs/concepts/workloads/pods/init-containers.md`  | 1(+XS) 1(-)
1. [x] M14.  `content/en/docs/concepts/workloads/pods/pod-lifecycle.md`  | 1(+XS) 1(-)
1. [x] M15.  `content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md`  | 32(+M) 32(-)
1. [x] M16.  `content/en/docs/contribute/_index.md`  | 89(+M) 4(-)
1. [x] M17.  `content/en/docs/contribute/new-content/_index.md`  | 74(+M) 20(-)
1. [x] M18.  `content/en/docs/contribute/new-content/open-a-pr.md`  | 94(+M) 6(-)
1. [x] M19.  `content/en/docs/contribute/review/reviewing-prs.md`  | 32(+M) 1(-)
1. [x] M20.  `content/en/docs/reference/access-authn-authz/authorization.md`  | 15(+S) 0(-)
1. [x] M21.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 2(+XS) 6(-)
1. [x] M22.  `content/en/docs/reference/glossary/extensions.md`  | 1(+XS) 1(-)
1. [x] M23.  `content/en/docs/reference/glossary/namespace.md`  | 2(+XS) 2(-)
1. [x] M24.  `content/en/docs/reference/issues-security/security.md`  | 1(+XS) 1(-)
1. [x] M25.  `content/en/docs/reference/scheduling/config.md`  | 44(+M) 11(-)
1. [x] M26.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 5(+XS) 1(-)
1. [x] M27.  `content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md`  | 5(+XS) 12(-)
1. [x] **M28.**  `content/en/docs/tasks/access-application-cluster/ingress-minikube.md`  | **134(+L) 149(-)**
1. [x] M29.  `content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md`  | 1(+XS) 1(-)
1. [x] M30.  `content/en/docs/tasks/administer-cluster/change-pv-reclaim-policy.md`  | 4(+XS) 4(-)
1. [x] M31.  `content/en/docs/tasks/configure-pod-container/configure-gmsa.md`  | 1(+XS) 1(-)
1. [x] M32.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md`  | 2(+XS) 2(-)
1. [x] M33.  `content/en/docs/tasks/tools/install-kubectl-linux.md`  | 4(+XS) 4(-)
1. [x] M34.  `content/en/docs/tasks/tools/install-kubectl-macos.md`  | 2(+XS) 2(-)
1. [x] M35.  `content/en/docs/tasks/tools/install-kubectl-windows.md`  | 2(+XS) 2(-)
1. [x] M36.  `content/en/docs/tutorials/stateful-application/zookeeper.md`  | 2(+XS) 2(-)
1. [x] M37.  `content/en/releases/notes.md`  | 2(+XS) 2(-)
1. [x] M38.  `content/en/training/_index.html`  | 12(+S) 0(-)

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.22-ko.3` branch.

For example:
```
# checkout `upstream/dev-1.22-ko.3`
...
# check what is updated in the upstream 
git diff upstream/dev-1.22-ko.2 upstream/dev-1.22-ko.3 -- content/en/docs/concepts/architecture/nodes.md
# apply changes to content/ko
vi content/ko/docs/concepts/architecture/nodes.md
...
# commit and push
...
# make PR to `upstream/dev-1.22-ko.3`
```

## Pages to Update

Pages in content/ko

**Comment by seokho-son** [comment]
- M1: @seokho-son 
- ...
- ...

**Comment by jihoon-seo** [comment]
M28 제가 하겠습니다~~

- M1-M3: @seokho-son
- ...
- M28: @jihoon-seo 
- ...

**Comment by jihoon-seo** [comment]
GitLens (VScode extension) 로
`upstream/dev-1.22-ko.3` 브랜치와 `upstream/dev-1.22-ko.2` 브랜치를 비교하면
위의 M** 목록에 없는 항목들도 있네요..

---

이렇게 GitLens 에서는
`content/en/docs/setup/production-environment/tools/kubeadm/` 아래에
변경된 파일이 6개 있다고 뜨는데

![image](https://user-images.githubusercontent.com/46767780/142138051-b1e6fc5f-eb11-44df-8014-1c2c4eca1935.png)

그런데 위에 M** 목록에는
> 26. [ ]  M26.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 5(+XS) 1(-)

이거 하나만 있네요..

**Comment by jihoon-seo** [comment]
M4 ~ M15 중에서
앞번호에서부터 하는데까지 해 보겠습니다~~

**Comment by seokho-son** [comment]
- M1-M3: @seokho-son
- M4-M8: @jihoon-seo 
- ...
- M19-M26: @jihoon-seo 
- M27: #30364
- M28-M38: @jihoon-seo

**Comment by jihoon-seo** [comment]
M9 ~ M18 도 제가 하겠습니다~~

- M1-M3: @seokho-son
- M4-M26: @jihoon-seo 
- M27: #30364
- M28-M38: @jihoon-seo

**Comment by seokho-son** [comment]
Complete !
/close
