### ISSUE TITLE
Wrong Link for Authorization.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#30429]
**This is a Bug Report**

**Problem:**
The link for **Authorization**  under[ API Access Extensions](https://kubernetes.io/docs/concepts/extend-kubernetes/#authorization) in [Extending Kubernetes](https://kubernetes.io/docs/concepts/extend-kubernetes/) is wrong. It is redirected to the [Webhook Mode](https://kubernetes.io/docs/reference/access-authn-authz/webhook/) which is wrong, It should redirect to  [Authorization Overview](https://kubernetes.io/docs/reference/access-authn-authz/authorization/)

**Proposed Solution:**
We will have to use this link:`https://kubernetes.io/docs/reference/access-authn-authz/authorization/` for Authorization instead of `https://kubernetes.io/docs/reference/access-authn-authz/webhook/`.

**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/

**Comment by Shubham82** [comment]
Fixed it here: #30430

**Comment by mehabhalodiya** [comment]
Hey @jihoon-seo @seokho-son
Do check on issue triage for this!
Thank you.
