### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by nishankgu** [kubernetes/website#30470]
page not rendering correctly.

**Comment by anubha-v-ardhan** [comment]
Wrong formatting, flows across the width of screen
Similar issue #30467 

triage/accepted

**Comment by anubha-v-ardhan** [comment]
Wrong formatting, flows across the width of screen
Similar issue #30467

/triage accepted

**Comment by anubha-v-ardhan** [comment]
![Screenshot from 2021-11-14 11-19-07](https://user-images.githubusercontent.com/71918957/141670042-3b266af9-092c-4199-97ed-6fbe8c79bf74.png)

**Comment by webbertakken** [comment]
It's caused by the [output of pi](https://github.com/kubernetes/website/blob/7b07d97a0b0c20343c63f422f82959e738377a4a/content/en/docs/concepts/workloads/controllers/job.md?plain=1#L115) on a single line combined with having no `word-wrap: break-word`.

**Comment by webbertakken** [comment]
Most likely caused by https://github.com/kubernetes/website/pull/30082 2 days ago.

**Comment by webbertakken** [comment]
@nishankgu would you mind renaming this issue, to make it more descriptive; indicating it's a bug and that the layout it broken for multiple pages?

**Comment by nishankgu** [comment]
Thanks for fixing this at priority @webbertakken
