### ISSUE TITLE
[de] Typo in k8s.io/de/docs/concepts/overview/what-is-kubernetes

### ISSUE THREAD

**Issue by SlothLazybones** [kubernetes/website#30475]
Typo
...erleichtert. Es hat **einen** großes, schnell wachsendes Ökosystem. Kubernetes...
sollte angepasst werden zu:
...erleichtert. Es hat **ein** großes, schnell wachsendes Ökosystem. Kubernetes...

**Comment by tengqm** [comment]
/retitle [de] Typo in k8s.io/de/docs/concepts/overview/what-is-kubernetes
