### ISSUE TITLE
Missing Page Content for a Concept on Doc Website

### ISSUE THREAD

**Issue by epaitoo** [kubernetes/website#30487]
**This is a Bug Report**

**Problem:**
Contents for <em>Connecting Applications with Services</em> which is under  **Services, Load Balancing, and Networking** Concept in the Documentation is not displaying. I tried accessing it on both Chrome and Firefox but the same result.

**Proposed Solution:**
Page content for <em>Connecting Applications with Services</em> which is under  **Services, Load Balancing, and Networking** Concept in the Documentation should display and not be blank.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by epaitoo** [comment]
![kub-capture](https://user-images.githubusercontent.com/36279649/141777302-fb0cef86-1e59-47ac-a3ff-49bea7e09c02.PNG)

**Comment by AvineshTripathi** [comment]
Hey @epaitoo thank you for raising this issue I tried opening this too it seems to be blank also I tried opening in my mobile browser without desktop mode on and I found the content correctly

**Comment by epaitoo** [comment]
@AvineshTripathi Just check the mobile version and its available but the text are not fully responsive. I personally read the docs from my laptop and it will be nice to have the content available for larger screens.

**Comment by AvineshTripathi** [comment]
yeah definately and as I see we have a PR for the same issue in #30490

**Comment by epaitoo** [comment]
That's really great!
