### ISSUE TITLE
Improve prerequisites for “Run a Replicated Stateful Application”

### ISSUE THREAD

**Issue by QWQyyy** [kubernetes/website#30484]
I think this place should display a example for get pv and pvc, this demo real can not give me some instruct.

**Comment by sftim** [comment]
Our policy in SIG Docs is to make improvements first to the English (“upstream”) documentation, and then localize that into other (“target”) languages such as Chinese.

Making this improvement to https://k8s.io/docs/tasks/run-application/run-replicated-stateful-application/ could well be reasonable. Specifically, we should improve the [prerequisites](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#before-you-begin) section.

/retitle Improve prerequisites for “Run a Replicated Stateful Application”

**Comment by sftim** [comment]
I'm also going to assert that we should improve the English page first.
/language en

and then update the Chinese page to match.

**Comment by QWQyyy** [comment]
well notes, thank you sir.
