### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by QWQyyy** [kubernetes/website#30482]
The "cassandra-statefulset.yaml" can not work, and I don't find anything about how to reviwer this file adapt my k8s.

**Comment by QWQyyy** [comment]
![image](https://user-images.githubusercontent.com/54056797/141727198-1e1d79e6-959f-4b56-b9e5-f2d848b57baf.png)
![image](https://user-images.githubusercontent.com/54056797/141727222-3cd28846-98a7-479d-a068-965db4d74454.png)

**Comment by tengqm** [comment]
The failedscheduling message is clear, right?

**Comment by QWQyyy** [comment]
I should know how to create pv and pvc etc... But as a demo, I still persistent this should add some quick link. thank you.

**Comment by jihoon-seo** [comment]
Link to the English page: https://kubernetes.io/docs/tutorials/stateful-application/cassandra/

**Comment by sftim** [comment]
I think we should fix the English original page, then localize the fixes back to zh
