### ISSUE TITLE
Warn people about mistaking "M" suffix for "m" when setting resource limits

### ISSUE THREAD

**Issue by dialogbox** [kubernetes/website#30499]
Although it's not recommended, we also support 'm' as an unit for memory which means milli-bytes.

https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go#L46

We need to document it.

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory

**Comment by sftim** [comment]
@dialogbox can you explain why? I imagine it's in case someone writes a quantity as, eg, 256m meaning 256Mi, and they don't realize their error?

We do document quantities: https://kubernetes.io/docs/reference/glossary/?all=true#term-quantity

/priority awaiting-more-evidence
/language en

**Comment by dialogbox** [comment]
@sftim Yes. That is exactly the case. Although we have a document about the general quantities, this page would be the page someone who is searching about memory configuration.

And since this page also mentions but only mentions E, P, T, G, M, k, and since 'm' just works, I saw some people blindly assumed that the 'm' means 'Mega'. This might not be a big problem for resource limits because the differences are so huge like 1/1,000,000,000, most likely this mistake will cause cgroup OOM. However, when it comes to the resource requests, it's not easy to know there is some mistake. But pod scheduling might work incorrectly because the the requests is incorrect.

So I'm requesting to add this as a kind of warning.

**Comment by sftim** [comment]
/triage accepted
/kind feature
/priority backlog
/help
/language en

Thanks for clarifying. Let's try to use a [glossary tooltip](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) for what we mean by “quantity”, too, if we can.

**Comment by sftim** [comment]
/retitle Warn people about mistaking "M" suffix for "m" when setting resource limits

**Comment by Babapool** [comment]
Hi, I would like to work on this.

**Comment by Babapool** [comment]
I was thinking to solve the PR in the following manner:

1.  On the page https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory I will add 'm (milli)' in the list of suffixes.
2. Before the example I would include a Caution/ Note telling people while setting resource limits that they should not mistake the m (mili) suffix as M  (mega) suffix of memory.
3. In the same Note/Caution I will try to add the glossary tooltip for memory.

**Comment by Babapool** [comment]
@sftim @dialogbo Could be you please provide your inputs for my method above to fix this PR. Thanks.

**Comment by dialogbox** [comment]
@Babapool I love the idea of having the `Caution/ Note`. Can you please add the comment to the https://github.com/kubernetes/website/pull/30501?

**Comment by Babapool** [comment]
@dialogbox Let me ask the reviewers on #30501 on how to proceed on the same and as per their advice/suggestion I will do the necessary changes.

**Comment by Babapool** [comment]
@dialogbox Since you have squashed and merged the commits in #30501 can ask whether I could add the `Caution/Note` part ?

**Comment by dialogbox** [comment]
@Babapool I think making it as `caution/note` is a reasonable idea but I'm not sure if others would agree on that. How about keep having discussion here and filing a new pr for adding `Caution/Note` once we got concluded?

**Comment by Babapool** [comment]
@dialogbox Thanks I will ask them again the PR conversation.

**Comment by Babapool** [comment]
This issue is fixed by PR #30501. I believe that this issue can be closed. Thanks.
