### ISSUE TITLE
Tidy prerequisites for “Set up Konnectivity service”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30514]
**This is a cleanup request**

**Problem:** The page [Set up Konnectivity service](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/) has some prerequisites that aren't mentioned until after end of the prerequisites section.

Also, the prerequisites currently suggest you can try this in an online playground; you can't. A tiny bug.

**Proposed Solution:**
Move the following to be listed as prerequisites (about line 15 of the current Markdown, as of commit 768905ec73d40884c42a3a6edd8133e043801ee8):
- >  [Service Account Token Volume Projection](/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) feature enabled in your cluster. It is enabled by default since Kubernetes v1.20.

Omit `{{< include "task-tutorial-prereqs.md" >}}` from the prerequisites and instead write custom text that doesn't mention Katacoda or Play with Kubernetes.

**Page to Update:**
https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

**Additional Information:**
/language en

Follow-up to PR #30385

**Comment by ashish-jaiswar** [comment]
@sftim is anyone working or assign for this issue?

**Comment by sftim** [comment]
@ashish-jaiswar you've assigned this to yourself, which by convention means that you plan to work on it
Nobody else has mentioned in this issue that they plan to work on it.

**Comment by ashish-jaiswar** [comment]
hey, @sftim I have confusion regarding the proposed solution. Can you tell me more about this line > "Omit {{< include "task-tutorial-prereqs.md" >}} from the prerequisites and instead write custom text that doesn't mention Katacoda or Play with Kubernetes."

**Comment by sftim** [comment]
In https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/ there is some text:
> You need to have a Kubernetes cluster, and the kubectl command-line tool must be configured to communicate with your cluster. It is recommended to run this tutorial on a cluster with at least two nodes that are not acting as control plane hosts. If you do not already have a cluster, you can create one by using minikube or you can use one of these Kubernetes playgrounds:
>
> - [Katacoda](https://www.katacoda.com/courses/kubernetes/playground)
> - [Play with Kubernetes](http://labs.play-with-k8s.com/)

and the [source code](https://github.com/kubernetes/website/edit/main/content/en/docs/tasks/extend-kubernetes/setup-konnectivity.md) for that is text is a [shortcode](https://gohugo.io/content-management/shortcodes/#figure):
> `{{< include "task-tutorial-prereqs.md" >}}`

So this part of the task is 3 steps:
1. Write new text that starts “You need to have a Kubernetes cluster, and the `kubectl` command-line tool&hellip;”
2. Delete `{{< include "task-tutorial-prereqs.md" >}}` from the source code for “Set up Konnectivity service”
3. Replace the deleted shortcode with the new text you wrote.

The new text can be as close to the original as you like, so long as it doesn't link to Katacoda or Play with Kubernetes.

**Comment by ashish-jaiswar** [comment]
@sftim, I submitted the PR  of this issue can you review it ?

**Comment by mehabhalodiya** [comment]
> @sftim, I submitted the PR of this issue can you review it ?

@ashish-jaiswar I would request you to mention the respective issue number in the particular PR you have submitted.
Thanks!

**Comment by sftim** [comment]
I'm happy to let any SIG Docs reviewer take a look. Which PR did you have in mind @ashish-jaiswar ?

**Comment by ashish-jaiswar** [comment]
@mehabhalodiya can you review this PR?
 [issue](https://github.com/kubernetes/website/pull/30664)

**Comment by ashish-jaiswar** [comment]
@sftim close this issue, PR of this issue is merged.

**Comment by sftim** [comment]
Fixed
/close
