### ISSUE TITLE
Highlight contributor site from Community page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30515]
**This is a Feature Request**

**What would you like to be added**
Update the page at https://kubernetes.io/community/ to hyperlink, prominently, to https://k8s.dev/

**Why is this needed**
https://github.com/kubernetes/contributor-site/issues/202 calls for making the contributor site more findable.

**Comments**
/language en
/good-first-issue

per SIG Docs fortnightly meeting:
/assign @occase

**Comment by sftim** [comment]
The file to change is https://github.com/kubernetes/website/blob/main/content/en/community/_index.html

Unlike most of this site, that page is in HTML. https://kubernetes.io/docs/contribute/new-content/open-a-pr/ has some general tips on what to do.
It's OK to ask questions for more advice.

**Comment by ashish-jaiswar** [comment]
assign

**Comment by ashish-jaiswar** [comment]
@sftim somebody updated the community page before assigning this issue. I was working on same issues.

**Comment by sftim** [comment]
@ashish-jaiswar I'm afraid you're not right about the timeline. As discussed in the fortnightly SIG Docs call, I highlighted this issue to @occase in https://github.com/kubernetes/website/issues/30515#issue-1055543261. Their PR came in first too, and I was happy to approve it.

I hope that this wasn't too much of an inconvenience for you. This SIG is usually happy to pick the first PR for an issue; if someone is already likely to be working on an issue, it's polite to sync with them first before you start your own work on it.

_This_ issue is, however, now done (by #30521).
/close
