### ISSUE TITLE
Document serviceAccountToken projected volumes

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30516]
**This is a Feature Request**

**What would you like to be added**
Add `serviceAccountToken` as a ~volume type~ kind of projected volume into https://kubernetes.io/docs/concepts/storage/volumes/

**Why is this needed**
https://github.com/kubernetes/website/pull/30366/files#r743717303 highlights that currently, that volume type is not documented.

**Comments**
/kind feature
/sig storage
/language en

**Comment by AvineshTripathi** [comment]
Hey @sftim I am willing to work on this can you help me with resources which I can look and learn about it

**Comment by sftim** [comment]
@AvineshTripathi are you a member of Kubernetes Slack? (if not, you can visit https://slack.k8s.io/ to request an invitation).

A good place to ask for mentoring help is the [#sig-docs](https://kubernetes.slack.com/messages/sig-docs) channel - there are many contributors who might have time for that, and it's a better approach than singling out one contributor and asking them.

**Comment by AvineshTripathi** [comment]
Hey thanks I ll do the same

**Comment by Kartik494** [comment]
@sftim  SO the aim here to move `ServiceAccountToken` documentation under volumes? or we can just add a [reference](https://kubernetes.io/docs/concepts/storage/projected-volumes/#introduction) here for serviceAccountToken

**Comment by sftim** [comment]
I think it would be enough to edit https://kubernetes.io/docs/concepts/storage/volumes/ to mention the `serviceAccountToken` volume type, briefly, and to hyperlink to existing more detailed documentation.

**Comment by mehabhalodiya** [comment]
> I think it would be enough to edit https://kubernetes.io/docs/concepts/storage/volumes/ to mention the `serviceAccountToken` volume type, briefly, and to hyperlink to existing more detailed documentation.

Where's the existing detailed documentation of `serviceAccountToken` ?
Can you please provide the link?

**Comment by sftim** [comment]
I'd link to https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

I found this using the following web search: https://www.google.com/search?q=serviceaccounttoken

**Comment by sftim** [comment]
OK, so https://kubernetes.io/docs/concepts/storage/volumes/#projected already links to the right docs.

I suggest we expand that section to explicitly list the types of projected volumes, so that people doing a “find in page” do find the details they were looking for.
