### ISSUE TITLE
[ja] Translate tasks/inject-data-application/distribute-credentials-secure into Japanese

### ISSUE THREAD

**Issue by ptux** [kubernetes/website#30518]
# This is a Feature Request

## What would you like to be added

Translate [tasks/inject-data-application/distribute-credentials-secure](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/)  into Japanese.

## Why is this needed

This page has not been translated.

## Comments

/language ja
/assign

**Comment by nasa9084** [comment]
triage/accepted
