### ISSUE TITLE
[ja] Translate tasks/administer-cluster/securing-a-cluster into Japanese

### ISSUE THREAD

**Issue by ptux** [kubernetes/website#30528]
# This is a Feature Request

## What would you like to be added

Translate [tasks/administer-cluster/securing-a-cluster into Japanese](https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/)  into Japanese.

## Why is this needed

This page has not been translated.

## Comments

/language ja
/assign

**Comment by nasa9084** [comment]
doubled #30810
and fixed already
/close
