### ISSUE TITLE
[hi] Localize optional-kubectl-configs-bash-linux.md to Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#30569]
**This is a Feature Request**

**What would you like to be added**

We need to localize [optional-kubectl-configs-bash-linux.md](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md) to Hindi.

**Why is this needed**

This page is needed as per [minimum required content](https://kubernetes.io/docs/contribute/localization/#minimum-required-content) for the ongoing Hindi Localization effort.

**Comments**

The current working branch for `hi` localization work is `dev-1.22-hi.1`. Please make sure to open a PR against `dev-1.22-hi.1`.
For more info see Hindi localization progress tracking issue #29353 

/language hi
/kind feature
/priority important-soon (`dev-1.22-hi.1` is broken due to this missing page)

**Comment by sftim** [comment]
/remove-priority important-soon
/priority backlog

These are key for Hindi but overall (across SIG Docs) the priority for this work is only backlog I'm afraid.

**Comment by ashish-jaiswar** [comment]
hey @anubha-v-ardhan I submitted the PR of this issue ,can you review it?
netlify cases are failed , how to resolve this issues?

**Comment by anubha-v-ardhan** [comment]
@ashish-jaiswar Thanks for the PR
I have suggested some changes (with reason of failure) that should fix the problem.

**Comment by anubha-v-ardhan** [comment]
/close
fixed with #30627
