### ISSUE TITLE
Document kubernetes.io/psp annotation

### ISSUE THREAD

**Issue by disconnect3d** [kubernetes/website#30578]
Hey,

I have a question regarding validating if PSP is applied, as well as an enhancement request on clarifying this.

It seems to me that when a Pod is validated with a PSP, a `"kubernetes.io/psp"` annotation is added with the name of the used pod security policy as its value. It is not obvious if that mechanism can be relied on, especially since it is not documented in the PSP documentation - https://kubernetes.io/docs/concepts/policy/pod-security-policy/.

However, it can be found to be relied on per the psp/rbac examples readme:
https://github.com/kubernetes/examples/blob/master/staging/podsecuritypolicy/rbac/README.md#testing-access

## "Show me the code"

The `"kubernetes.io/psp"` is defined in [pkg/security/podsecuritypolicy/util/util.go#L29](https://github.com/kubernetes/kubernetes/blob/v1.18.0/pkg/security/podsecuritypolicy/util/util.go#L29) and the annotation is written into the pod object in [plugin/pkg/admission/security/podsecuritypolicy/admission.go#L139](https://github.com/kubernetes/kubernetes/blob/v1.18.0/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L139). I haven't debugged this piece of code nor have I tested if it is invoked in all possible paths, and so on. That's also partially why I want to make this issue: to confirm this detail ;).

## TLDR

**What would you like to be added**:
Documentation about the `kubernetes.io/psp` annotation in Pod Security Policy docs.

**Why is this needed**:
To know how to check if a given Pod was validated by a given PSP. This can be very important when using managed kubernetes services, as some providers add a "privileged" PSP by default, to keep backwards compatibility.

It will also be useful for auditors to have a ground truth for this behaviour and have a place to link to :).

**Comment by sftim** [comment]
The actions I'd want:
- update https://kubernetes.io/docs/reference/labels-annotations-taints/ to mention the annotation, and that the API that uses it (PodSecurityPolicy) is deprecated
- link from https://kubernetes.io/docs/concepts/policy/pod-security-policy/ to the specific section added in the previous step

Those are fairly self-contained

@disconnect3d would you be willing to update the issue description to link to this specific comment?
(if you do, we can mark this as a good first issue)

**Comment by sftim** [comment]
BTW the “important-soon” priority is because the replacement feature is going beta in the next release, and properly documenting the feature it replaces is equally timely.

**Comment by mtardy** [comment]
I can do that!
/assign
