### ISSUE TITLE
kubectl config documentation on kubernetes.io is broken

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes/website#30577]
#### What happened:

In the generated kubectl documentation hosted on https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands, one of the lines in the description of [kubectl config](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config) overlaps the examples section of the command.

![image](https://user-images.githubusercontent.com/22327577/125075577-1cb60b80-e0bf-11eb-94ed-a6ee5d8e3a3d.png)

#### What you expected to happen:

I would have expected a line break to prevent the overlap.

#### How to reproduce it (as minimally and precisely as possible):

Visit https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config.

#### Environment:
- Chromium 91.0.4472.77 Arch Linux
- Mozilla Firefox 89.0.1

/sig docs

**Comment by sftim** [comment]
/sig cli
/language en
/kind bug

The page in question is [auto generated](https://github.com/kubernetes-sigs/reference-docs/).

**Comment by shuuji3** [comment]
Hi, I believe this issue was fixed in the latest documentation. I checked the page on Google Chrome and Mozilla Firefox on macOS.

<img width="1413" alt="Screenshot 2022-12-30 at 21 11 53" src="https://user-images.githubusercontent.com/1425259/210069135-70902be6-7501-4da7-9639-828a3f9403f4.png">

**Comment by dgrisonnet** [comment]
You are correct @shuuji3, thank you for pointing it out.

**Comment by shuuji3** [comment]
Thanks for the confirmation!
