### ISSUE TITLE
Document metadata.namespace behavior for webhooks

### ISSUE THREAD

**Issue by riking** [kubernetes/website#30574]
**What would you like to be added**:
Webhook authors should be aware that the metadata.namespace of submitted objects is not trustworthy in Mutating Webhooks, and may be blank in Validation Webhooks. The namespace needs to always be read out of the AdmissionReview object.

**Why is this needed**:
If a webhook author does not test their code with a modified kubectl default namespace, a validating webhook may incorrectly think a resource is being created in the `default` namespace.
Namespaces that mismatch between the URL and resource are not blocked by the apiserver until after the object has been sent to Mutating webhooks. A mutating webhook that reads the wrong namespace field may be vulnerable to information disclosure in error messages, or in extreme cases acting as a Confused Deputy if the webhook has side effects (please do not make a mutating webhook with side effects).

The correct fix for these problems is to fix the webhook code via developer education. Improve the docs so this is obvious.

/sig api-machinery
/sig docs
/area ecosystem

**Comment by sftim** [comment]
The primary place to document this is on the Kubernetes [website](https://k8s.io/)

**Comment by liggitt** [comment]
fwiw, I'm looking at improving this behavior in https://github.com/kubernetes/kubernetes/pull/94637, but that will likely land in 1.24, so we still want this documented for things interoperating with older server versions

**Comment by riking** [comment]
> @sftim said: would you be willing to revise the issue description based on https://github.com/kubernetes/kubernetes/issues/88282#issuecomment-689213634 ?

I think someone already did - the issue text now already says "Namespaces that mismatch between the URL and resource are not blocked by the apiserver until after the object has been sent to Mutating webhooks". (Possibly me, but github shows no edit history.)

The only place I incorrectly stated that "intended behavior" was that comment.

I don't intend to actually work on this myself - I filed this because I saw a conversation somewhere (Slack??) about this suspicious API behavior and filed the issue to make sure it didn't get dropped.

**Comment by sftim** [comment]
I think
> Webhook authors should be aware that the metadata.namespace of submitted objects is not trustworthy in Mutating Webhooks, and may be blank in Validation Webhooks. The namespace needs to always be read out of the AdmissionReview object.

is slightly misleading. The description for https://github.com/kubernetes/kubernetes/pull/94637 puts it more clearly. I want to make it obvious to anyone who does pick this issue up where they can find clear guidance on what to document.

**Comment by sftim** [comment]
To clarify:
> If a webhook author does not test their code with a modified kubectl default namespace, a validating webhook may incorrectly think a resource is being created in the default namespace.

does not need a special warning, because even the most naive of validating webhooks doesn't need to care about namespace mismatches. Validation still fails at some point before persistence.
