### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

### ISSUE THREAD

**Issue by ppbrown** [kubernetes/website#30572]
This actually applies to all the tutorials

problem 1: the default framing is way too limiting. Even if you have a large browser window, it is effectively too small, because
    1.1 the tutorial takes up 50% or less of the window
    1.2 there are multiple parts, all in the same frame. 
    Better interactive tutorials default to separating out the instructions from the interactive typie bit.
    They also take up MOST of the browser window.

problem 2: I dont want to have to start up the interactive tutorial at all! I Just Want To Read The Steps!!
Please dont force people to wade through the tutorial if they just want the info. Its kinda like being forced to watch a video instead of just being able to read the transcript.

**Comment by sftim** [comment]
/kind bug
/triage accepted
/language en
/priority backlog
That seems like a fair criticism.

**Comment by sftim** [comment]
I think it'd make sense to convert these to be non-interactive tutorials.
