### ISSUE TITLE
Mention k-sigs/kui within docs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30584]
**This is a Feature Request**

**What would you like to be added**
Mention kui within https://kubernetes.io/docs/

**Why is this needed**
We should make the [kui](https://github.com/kubernetes-sigs/kui) tool more prominent.

**Comments**
Based on an idea from https://github.com/kubernetes-sigs/kui/issues/8267
/kind feature
/triage accepted
/language en
/priority backlog

**Comment by sftim** [comment]
I would make this change by editing https://kubernetes.io/docs/reference/tools/ and adding a new entry that describes kui.
/help

**Comment by Babapool** [comment]
Hi @sftim , I would like to work on this issue.
/assign

**Comment by Babapool** [comment]
I have one question: While describing about about kui, should I also include some of its uses? @sftim
