### ISSUE TITLE
[hi] Localize docs/reference/glossary/index.md to Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#30591]
**This is a Feature Request**

**What would you like to be added**

We need to localize [glossary/index.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/index.md) to Hindi.

**Why is this needed**

This page is needed for Netlify preview to work on `dev-1.22-hi.1`

**Comments**

The current working branch for `hi` localization work is `dev-1.22-hi.1`. Please make sure to open a PR against `dev-1.22-hi.1`.
For more info see Hindi localization progress tracking issue #29353 

/language hi
/kind feature
/priority backlog

**Comment by Polokghosh53** [comment]
So, currently there is not any reference folder in the docs directory, right? 
- So, do we have to just localise https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/index.md but just in Hindi?
Would like to know more so that I can get started.

**Comment by Polokghosh53** [comment]
@anubha-v-ardhan just tagged to let you know about the query above.

**Comment by anubha-v-ardhan** [comment]
>So, currently there is not any reference folder in the docs directory, right?

Yes, you can create the folder if it's not present. Tracking issue #29353's description has the steps mentioned to localize a page.
This issue is already assigned by @ashish-jaiswar, you can approach him if you wish to work together :)

**Comment by Polokghosh53** [comment]
Thank you @anubha-v-ardhan .  I will reach out to you for any query.

**Comment by anubha-v-ardhan** [comment]
/close 
fixed with #30652
