### ISSUE TITLE
[hi] Localize task-tutorial-prereqs.md to Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#30590]
**This is a Feature Request**

**What would you like to be added**

We need to localize [task-tutorial-prereqs.md](https://github.com/kubernetes/website/blob/main/content/en/includes/task-tutorial-prereqs.md) to Hindi.

**Why is this needed**

This page is needed for Netlify preview to work on `dev-1.22-hi.1`

**Comments**

The current working branch for `hi` localization work is `dev-1.22-hi.1`. Please make sure to open a PR against `dev-1.22-hi.1`.
For more info see Hindi localization progress tracking issue #29353 

/language hi
/kind feature
/priority backlog

**Comment by Nawaz027** [comment]
Hey @anubha-v-ardhan, I'm new to kubernetes. Would love to localize and get comfortable with contributing. Can you please assign this issue to me?

**Comment by anubha-v-ardhan** [comment]
/assign @Nawaz027
Thank you

**Comment by Polokghosh53** [comment]
@anubha-v-ardhan may I assign this issue to myself, if it is not being fixed?

**Comment by anubha-v-ardhan** [comment]
@Polokghosh53 The PR #30602 is open fixing this issue

**Comment by anubha-v-ardhan** [comment]
/close 
#30602 fixed it

**Comment by Polokghosh53** [comment]
> @Polokghosh53 The PR #30602 is open fixing this issue

Ohh okay. Did not find the link referral, so I thought this was available. Anyways, thanks.
