### ISSUE TITLE
[zh] Translate docs/reference/glossary/affinity.md into Chinese

### ISSUE THREAD

**Issue by UOS-liang** [kubernetes/website#30619]
Hi, I'm interested to translate the "reference/glossary/affinity.md" page.

This is a Feature Request:

translate en/docs/reference/glossary/pod-disruption.md into Chinese.

What would you like to be added:

zh/docs/reference/glossary/affinity.md

/language zh
/kind feature

**Comment by sftim** [comment]
/remove-kind support
/kind feature
/retitle [zh] Translate docs/reference/glossary/affinity.md into Chinese
