### ISSUE TITLE
Incorrect docs for label kubernetes.io/metadata.name

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30614]
**This is a Bug Report**

**Problem:**
The docs for [`kubernetes.io/metadata.name`](https://kubernetes.io/docs/reference/labels-annotations-taints/) say that this label is set on namespaces when you enable a feature gate, `NamespaceDefaultLabelName`. However that's no longer true. In current Kubernetes the control plane always sets that label on namespaces.

**Proposed Solution:**
Reword that section to make it clear that the control plane always sets that label

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetes-io-metadata-name

**Kubernetes Version:**
v1.22

**Additional Information:**
/language en
/kind bug
/help
/priority backlog

**Comment by Babapool** [comment]
Hi, I would like to work on this issue.
/assign

**Comment by sftim** [comment]
Any questions about how to fix it?

**Comment by Babapool** [comment]
I have a few technical questions:
1. Since the `Control Plane` sets the label on the namespaces instead of enabling the `feature gate` , so there would be no role of K8s API server in this process?
2. How will the `Control Plane` set label on the namespaces? I mean will it do it automatically or we need to do something else?

**Comment by sftim** [comment]
The API server is part of the control plane - see https://kubernetes.io/docs/concepts/overview/components/
The component within the control plane that sets the label isn't a detail we need to specify here. All we need to mention is that it happens, and phrase it to make it clear it's not optional.

**Comment by Babapool** [comment]
Just to be clear that the `Control plane` will set the labels of the namespace and this setting of the labels is compulsorily (i.e. it is not optional).?

**Comment by sftim** [comment]
(also, we'll get the API Machinery folks to check technical accuracy _anyway_ - it's not on the docs contributors to thoroughly verify this kind of detail).

**Comment by Babapool** [comment]
Okay thanks . I will  file the PR soon :)

**Comment by Babapool** [comment]
I have a doubt: The phrase which tells that `It is compulsory to set a label to namespace` ,would it be better to  included it as a `Note` shortcode or it should be kept as a normal text.?

**Comment by sftim** [comment]
@babapool the best way for folks to review your proposed changes is to open a pull request. (Also: anyone else who wants to work on this is welcome to - please liaise with @Babapool if that's feasible).

**Comment by Babapool** [comment]
I have filed a PR but if anyone wants to work on this they are welcome to share their suggestions in the PR Conversation. Thanks.
