### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/field-selectors/

### ISSUE THREAD

**Issue by samfullman** [kubernetes/website#30625]
So the first thing that anyone with a database background is going to ask is, What comparators are allowed?  Are you only able to do = and != ?  What about <, >, regex, or some type of IN(valueA, valueB)?  If it's not available, specify it, and if that's true are there extensions that do this, and/or is this proposed/coming?

**Comment by sftim** [comment]
I suspect you're looking for the section [Supported Operators](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-operators) @samfullman 

Does that list answer the question about what operators are allowed? If not, what extra text would help?
We usually, and intentionally, _don't_ document improvements and new features that might turn up in the future. Those are sketched out in [KEPs](https://github.com/kubernetes/enhancements/).

/language en

**Comment by samfullman** [comment]
hyperlinking to this section in the section of the page I referenced would
be helpful.

**Comment by sftim** [comment]
@samfullman would you be willing to revise the issue description with a summary of the fix you'd like made?
