### ISSUE TITLE
Translate a Docker Compose File to Kubernetes Resources

### ISSUE THREAD

**Issue by ComradePashka** [kubernetes/website#30629]
Hello guys!

Seems that documentation from page https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/ is outdated now.
At first, v1.24.0 is used in installation instructions, however latest one is v1.26.0
But more important is that there are no commands `up` and `down` at all! I creates another issue here: https://github.com/kubernetes/kompose/issues/969 and additionally check https://kompose.io/user-guide/ and there's no any mention about these commands.

**Comment by sftim** [comment]
`kompose down` and `kompose up` are [deprecated](https://github.com/kubernetes/kompose/pull/1297), so the documentation at https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/ is wrong.

We should either fix the existing docs, or replace them with a redirect to https://kubernetes.io/docs/reference/tools/#kompose. We support `kompose`; it's an official Kubernetes tool.

/kind bug
/language en
/priority backlog
/triage accepted
