### ISSUE TITLE
[ko] Translate tasks/service-catalog/install-service-catalog-using-helm.md

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#30632]
This is a Feature Request
Translate [/content/en/docs/tasks/service-catalog/install-service-catalog-using-helm.md] in Korean

What would you like to be added
Translate [/content/en/docs/tasks/service-catalog/install-service-catalog-using-helm.md] in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/

/language ko
/assign

**Comment by sftim** [comment]
It might be easier to propose an English PR that removes the page https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/

https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/ is not very good documentation and I don't recommend keeping it.

**Comment by sftim** [comment]
The _ideal_ is to maintain good docs for [Service Catalog](https://svc-cat.io/) and fully integrate them into the Kubernetes docs. That's more work than I think we can easily take on, though.

**Comment by sftim** [comment]
Related: https://github.com/kubernetes/website/issues/22720

**Comment by bang9211** [comment]
I got it. I'm going to close this issue.
