### ISSUE TITLE
Document API response compression

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30639]
**This is a Feature Request**

**What would you like to be added**
There is a feature gate, `APIResponseCompression`. There's barely documentation for this feature - mostly just https://github.com/kubernetes/kubernetes/pull/46966 if you find it, I think, plus the source code.

**Why is this needed**
Readers might want to know what kind of compression (eg HTTP hop-by-hop compression, HTTP end-to-end compression) the API Server might employ and under what circumstances.

Can a client turn it off? Can a client demand a compressed response? 

**Comments**
/sig api-machinery
/sig docs
/kind feature
/priority backlog
/language en

**Comment by mehabhalodiya** [comment]
triage/accepted

**Comment by mehabhalodiya** [comment]
@a-mccarthy I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @a-mccarthy

**Comment by mrgiles** [comment]
@sftim what would be a good place to add the `APIResponseCompression` documentation?
- https://kubernetes.io/docs/reference/using-api/api-concepts/ -or-
- https://kubernetes.io/docs/concepts/overview/kubernetes-api/

Let me know and I'll add it. Thanks!

**Comment by mrgiles** [comment]
@sftim, should I pick the content placement myself? Should I ask in Slack? What's the process? 
Thanks

**Comment by mrgiles** [comment]
Do you know @tengqm?

**Comment by tengqm** [comment]
I'd prefer adding this to the reference because it is something happening behind the scene. Not all users are aware of it or even care about it. It is not something you have to know to interact with Kubernetes API.

**Comment by mrgiles** [comment]
Thank! I'll add it to `/docs/reference/using-api/api-concepts/`
