### ISSUE TITLE
Italic is not applied to the text in mermaid figure

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#30641]
**This is a Bug Report**

**Problem:**
In https://kubernetes.io/docs/contribute/new-content/ ,
there is an mermaid figure,
![image](https://user-images.githubusercontent.com/46767780/143518101-96e71eff-e5c9-42b3-bf14-3c6ab92e9182.png)

but italic is not applied to the text in mermaid figure.
`_'/content/../docs'_ folder contains docs
for multiple languages`

**Proposed Solution:**

Maybe just `'/content/../docs' folder contains docs
for multiple languages` ?

**Page to Update:**
https://kubernetes.io/docs/contribute/new-content/

**Comment by Deepakktripathy** [comment]
I am interested to work on this

**Comment by anubha-v-ardhan** [comment]
/close
fixed with #30792
