### ISSUE TITLE
Pod cidr and service cidr intersect in Dual-stack documentation

### ISSUE THREAD

**Issue by maaoBit** [kubernetes/website#30646]
**This is a Bug Report**

**Problem:**
I build a dual-stack cluster with kubeadm following [Dual-stack support with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/dual-stack-support/),  but kubernetes service clusterIP(`2001:db8:42:1::1/128`) can't be accessed in slave node. I found the reason is  Pod cidr(`2001:db8:42:0::/56`) and service cidr(`2001:db8:42:1::/112`) intersect which cause the request package not MASQUERADE in ip6tables.
After I update the `cluster-cidr` of kube-proxy from `2001:db8:42:0::/56` to `2001:db8:42:0::/64`, the problem is solved.

**Proposed Solution:**
Modify pod cidr in the documentation from `2001:db8:42:0::/56` to `2001:db8:42:0::/64`

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/dual-stack-support/

**Kubernetes Version:**
v1.21.3

**Comment by sftim** [comment]
You shouldn't use `2001:db8` IP addresses in your actual Kubernetes cluster; these ranges are only **examples**. Let's revise that document to point out that assigning actual IP addresses that you control is expected.

/language en
/priority backlog

**Comment by maaoBit** [comment]
Maybe I didn't express it clearly. The ranges of examples are intersect. Service cidr(`2001:db8:42:1::/112`) is a part of Pod cidr(`2001:db8:42:0::/56`). But Pod cidr and service cidr are not allowed to intersect in kubernetes. So I think we should fix this wrong example.

**Comment by sftim** [comment]
I don't really mind if two example ranges intersect. We could move them apart; we could also add a note to say that in a real cluster you should pick ranges that don't intersect.

How about we do both those things?

**Comment by sftim** [comment]
Given that you did try these ranges @maaoBit, I think it might be an idea to leave the intersection in place. That way, people who use the example ranges on their cluster will run into a problem and might then revisit the documentation - spotting, I hope, the new exhortation to pick real ranges.

**Comment by sftim** [comment]
We already have this text:
> You need to have an IPv4 and and IPv6 address range to use. Cluster operators typically use private address ranges for IPv4. For IPv6, a cluster operator typically chooses a global unicast address block from within 2000::/3, using a range that is assigned to the operator. You don't have to route the cluster's IP address ranges to the public internet.
