### ISSUE TITLE
Integrate docs for tasks/service-catalog into Kubernetes docs

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#30645]
**This is a Feature Request**
Integrate docs for tasks/service-catalog into Kubernetes docs.

**What would you like to be added**
Improved docs related to service-catalog.

**Why is this needed**
The tasks/service-catalog documentation is bad and should be integrated into other Kubernetes documentation.
Related: #30632 #22720

**Comments**

**Comment by sftim** [comment]
The documentation to integrate / link to: https://svc-cat.io/docs/

**Comment by sftim** [comment]
The source: https://github.com/kubernetes-sigs/service-catalog/tree/master/docs
