### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/quality-service-pod/

### ISSUE THREAD

**Issue by frsh-augustin** [kubernetes/website#30647]
In this document，I know Kubernetes assigns one of these QoS classes to the Pod:

- Guaranteed
- Burstable
- BestEffort

But the document doesn't describe the behavior of the Pod if it is assigned different QoS classes. Can anyone add more information?

**Comment by sftim** [comment]
I recommend adding a new reference page that lists the QoS classes, and then changing various task and concept pages about QoS to hyperlink to that new reference page.

/language en
/kind feature
/priority backlog
