### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by rajeshpanara** [kubernetes/website#30653]
please mentioned exact step for backup and restore.

explaining unnecessary things make it complicated to understand.

**Comment by RA489** [comment]
@rajeshpanara Is these https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#built-in-snapshot and https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster doesn't helped you to backup and restore the cluster. Any specific information your need on this page?

**Comment by tengqm** [comment]
/close
The reporter didn't respond to the hints provided. I believe this one can be closed.
