### ISSUE TITLE
Bug in Deprecated API Migration Guide

### ISSUE THREAD

**Issue by skhalidgh** [kubernetes/website#30654]
The replacement for  extensions/v1beta1 k8s 1.22 should be mentioned as extensions/v1beta1 instead of networking.k8s.io/v1 in documentation.

**Comment by sftim** [comment]
Hi @skhalidgh 

I' m not sure what you're suggesting. Can you let us know which page you think isn't right and outline what change might fix the issue? If you're not sure about the fix, please quote the part of that web page that doesn't seem correct.

/language en
/triage needs-information

**Comment by jihoon-seo** [comment]
Looks like here:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

> The `extensions/v1beta1` and `networking.k8s.io/v1beta1` API versions of Ingress is no longer served as of v1.22.
> - Migrate manifests and API clients to use the `networking.k8s.io/v1` API version, available since v1.19.
> - ...

@skhalidgh Is this right? 😊

**Comment by sftim** [comment]
The text you've quoted is correct @jihoon-seo - there doesn't seem to be anything to fix.

**Comment by sftim** [comment]
Nothing to fix

/retitle Bug in Deprecated API Migration Guide
(that's the report, incorrect though it may be)
/close
