### ISSUE TITLE
Example: Configuring a Java Microservice

### ISSUE THREAD

**Issue by Bcodms** [kubernetes/website#30660]
Not sure I was saving files when using the text editor within the tutorial

**Comment by RA489** [comment]
@Bcodms can you please point out which page has issues?

**Comment by jihoon-seo** [comment]
https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

It seems that the auto-save feature is on, so it will be automatically saved every time you make a change.

**Comment by jihoon-seo** [comment]
@RA489 How about reverting the PR status to rotten, and let the bot close this PR after certain amount of time?

**Comment by RA489** [comment]
> @RA489 How about reverting the PR status to rotten, and let the bot close this PR after certain amount of time, or closing this PR manually?

sure.
/close
