### ISSUE TITLE
Avoid using the words "master" and "slave"

### ISSUE THREAD

**Issue by ecmonsen** [kubernetes/website#30675]
Please change the example code to avoid references to slavery. Example page containing such references: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

There are many news articles about this if you want to know more. Here is one.

https://www.forbes.com/sites/elanagross/2020/07/03/twitter-and-jpmorgan-chase-are-the-latest-companies-to-remove-terms-master-and-slave-from-programming-code/?sh=244419d63ced

**Comment by sftim** [comment]
@ecmonsen this is a duplicate of issue #21621. You're welcome to open pull requests to help with the cleanup.

/triage duplicate

**Comment by ecmonsen** [comment]
Thank you, I should have checked existing issues!

**Comment by sftim** [comment]
/close
Duplicates #21621
