### ISSUE TITLE
[ko] Fix wrong link in downward-api-volume-expose-pod-information.md

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#30678]
**This is a Bug Report**

**Problem:** In [tasks/inject-data-application/downward-api-volume-expose-pod-information/ korean page](https://kubernetes.io/ko/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/), there is worng link related 환경변수.

**Proposed Solution:**
Change link `[환경 변수](/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api)` to `[환경 변수](/ko/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api)` on [downward-api-volume-expose-pod-information](https://github.com/kubernetes/website/blob/main/content/ko/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md)

**Page to Update:**
https://kubernetes.io/ko/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

**Note**

/language ko

**Comment by jihoon-seo** [comment]
PR #30485 에 의해, `dev-1.22-ko.3` 에는 반영되었습니다.
`dev-1.22-ko.3` 이 `main` 에 merge 되면 해결될 예정입니다 😊
/assign

**Comment by jihoon-seo** [comment]
Resolved by the PRs #30485 & #30749
/close
