### ISSUE TITLE
[ko] Fix wrong link in `force-delete-stateful-set-pod.md`

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#30679]
**This is a Bug Report**

**Problem:** In [tasks/debug-application-cluster/debug-stateful-set/ korean page](https://kubernetes.io/ko/docs/tasks/debug-application-cluster/debug-stateful-set/), there is worng link related to 스테이트풀셋 디버깅하기.

**Proposed Solution:**
Change link `[스테이트풀셋 디버깅하기](/docs/tasks/debug-application-cluster/debug-stateful-set/)` to `[스테이트풀셋 디버깅하기](/ko/docs/tasks/debug-application-cluster/debug-stateful-set/)` on [debug-stateful-set](https://github.com/kubernetes/website/blob/main/content/ko/docs/tasks/debug-application-cluster/debug-stateful-set.md)

**Page to Update:**
https://kubernetes.io/ko/docs/tasks/debug-application-cluster/debug-stateful-set/

**Note**

/language ko

**Comment by jihoon-seo** [comment]
https://kubernetes.io/ko/docs/tasks/debug-application-cluster/debug-stateful-set/ 이 페이지에는
`[스테이트풀셋 디버깅하기](/docs/tasks/debug-application-cluster/debug-stateful-set/)` 링크가 없습니다.

`content/ko/docs/tasks/run-application/force-delete-stateful-set-pod.md` 파일에
`[스테이트풀셋 디버깅하기](/docs/tasks/debug-application-cluster/debug-stateful-set/)` 링크가 있는데,

PR #30485 에 의해, `dev-1.22-ko.3` 에는 반영되었습니다.
`dev-1.22-ko.3` 이 `main` 에 merge 되면 해결될 예정입니다 😊
/assign
/retitle [ko] Fix wrong link in `force-delete-stateful-set-pod.md`

**Comment by jihoon-seo** [comment]
Resolved by the PRs #30485 & #30749
/close
