### ISSUE TITLE
/docs/reporting-security-issues/ and /security redirects to a [ko] page

### ISSUE THREAD

**Issue by reylejano** [kubernetes/website#30676]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reporting-security-issues
and
https://kubernetes.io/security

redirect to a Korean localization page

I think content was moved and _redirects wasn't been updated

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reporting-security-issues
and
https://kubernetes.io/security

**Comment by jihoon-seo** [comment]
@ClaudiaJKang I think that `[ko]` prefix in the title is not appropriate for this issue. 😊
/retitle /docs/reporting-security-issues/ and /security redirects to a [ko] page

---

@reylejano 
I examined `static/_redirects` file, ~but I cannot find which line causes this behavior.~

```
/docs/reporting-security-issues/     /security/ 301
...
```

---

It seems that
the line `aliases: [/security/]` in `content/ko/docs/reference/issues-security/security.md` 
causes the redirection `https://kubernetes.io/security` to `https://kubernetes.io/ko/docs/reference/issues-security/security/`.

/assign

**Comment by rikatz** [comment]
@jihoon-seo yes, I was looking into that as well :)

I'm going to drop the alias in korean translation + add this into aliases, but if you are working on this go for it :)

**Comment by jihoon-seo** [comment]
@rikatz Please look #30684 and give comments/suggestions if you have one! 😊

**Comment by rikatz** [comment]
yes, reviewing here
