### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl-windows/

### ISSUE THREAD

**Issue by bspeiser** [kubernetes/website#30698]
You are pedantic pieces of shitee that deserve to be flushed to nerd hell. There is no reason for this to be as difficult as it is other than you made it so.

**Comment by sftim** [comment]
The Kubernetes project expects all contributors to follow the [code of conduct](https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md#code-of-conduct).

This feedback isn't in line with how we expect folks to treat others in the community.
/close
