### ISSUE TITLE
Redirect from app.kubernetes.io to common-labels.md

### ISSUE THREAD

**Issue by imjasonh** [kubernetes/website#30696]
**This is a Feature Request**

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/ documents a number of common recommended labels, with keys beginning with the standard `app.kubernetes.io/` prefix, e.g., `app.kubernetes.io/name`.

Perhaps unintentionally, this string is also a valid URL, but if a user browses to that URL in their browser they'll only see an error: https://app.kubernetes.io/name

<img width="382" alt="Screen Shot 2021-11-30 at 1 29 19 PM" src="https://user-images.githubusercontent.com/210737/144106484-87c71d80-25d4-4029-8ba0-03e7d531558e.png">

**What would you like to be added**

I think it could be useful if any URL under https://app.kubernetes.io simply redirected to the page documenting the common labels, at https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Why is this needed**

Reduce confusion and wasted time for users who browse to these seeming-URLs.

**Comments**

It looks like there's currently nothing in place to even serve on https://app.kubernetes.io, and it might be hard enough to get that set up that it isn't worth it to set up this redirect. If that's the case I totally understand, but I thought it'd be good to consider anyway.

**Comment by sftim** [comment]
Thanks for the suggestion @imjasonh

/kind feature
/priority awaiting-more-evidence

To me it doesn't seem reasonable to cater for the kind of confusion that might mean someone mistakes a Kubernetes label for part of a URI. If there were, should we set up redirects for _every_ label or just some?

The easy answer is to do none of it and hope that folks can use web search engines etc to learn about how Kubernetes works.

**Comment by shannonxtreme** [comment]
I agree with @sftim - this would add maintenance overhead as well, any time a label is added or modified. The page says that the labels are metadata for organization. I think that's enough, esp for our target audience.

**Comment by imjasonh** [comment]
sgtm, thanks for the prompt feedback! 👍
