### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy/

### ISSUE THREAD

**Issue by rajeshpanara** [kubernetes/website#30693]
Hi,
Please include steps/commands to install CNIs.
it's difficult for beginner to moving and searching it on other site other than kubernets.io

at lease include for weave net.

Thanks.

**Comment by sftim** [comment]
The page at https://www.weave.works/docs/net/latest/install/ looks great. I'm happy to see people use that, even if they have to use a web search engine and look for terms like “install Weave Net CNI plugin”.

I think the story might be different if Kubernetes had maybe 5 times the level of docs contribution but the truth is that we don't and we have a [backlog](https://github.com/kubernetes/website/issues?q=is%3Aissue+created%3A%3C2020-01-01+state%3Aopen++label%3Alanguage%2Fen+label%3Apriority%2Fimportant-longterm%2Cpriority%2Fimportant-soon) of triaged work that should take priority.

/kind feature
/language en
/priority awaiting-more-evidence
