### ISSUE TITLE
Add warning for creating namespaces with the same name as TLDs

### ISSUE THREAD

**Issue by savitharaghunathan** [kubernetes/website#30717]
**This is a Feature Request**

By creating namespaces with the same name as public TLDs, services in those namespaces can have short DNS names that overlap with public DNS names

**What would you like to be added**
Add a warning highlighting the potential security risk
Add recommendations

**Comment by savitharaghunathan** [comment]
triage/accepted

**Comment by sftim** [comment]
Eesh. There's a _lot_ of TLDs these days, too.

**Comment by mtardy** [comment]
I would be interested in this opportunity as my first contribution! I attended the sig security meeting when this was discussed so I think I can come up with something! 😀 

/assign

**Comment by savitharaghunathan** [comment]
Thanks, @mtardy :)

**Comment by mtardy** [comment]
I think we can now close this issue 🤗! I'm amazed at how fast the feedback and merging process was.

**Comment by sftim** [comment]
Done in PR https://github.com/kubernetes/website/pull/31518
