### ISSUE TITLE
Update date to mention KubeCon NA 2022

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#30718]
**This is a Bug Report**

**Problem:**
KubeCon North America 2021 is over but we still have `Attend KubeCon North America on October 11-15, 2021`
**Proposed Solution:**
Update the text to `Attend KubeCon North America on October 24-28, 2022`
**Page to Update:**
https://kubernetes.io/

/good-first-issue

**Comment by sftim** [comment]
I suggest we invite people to attend the next KubeCon, that is: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/ in May 2022.

**Comment by sftim** [comment]
Typically we'd change the English docs only and let all localization teams pick up the change.
@mehabhalodiya I hope it's OK to:
/remove-language ko

**Comment by anubha-v-ardhan** [comment]
/close
fixed with #30722
