### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-linux/

### ISSUE THREAD

**Issue by dhs-rec** [kubernetes/website#30726]
Installation instructions for Debian family systems are somewhat outdated:

- Starting with Debian 10/Ubuntu 18.04, there's no need for `apt-transport-https` anymore. The functionality has been moved into the main apt package and `apt-transport-https` has become a s.c. transitional (dummy) package that will be removed in a future release
- ~~Repository keyrings are to be stored in `/etc/apt/trusted.gpg.d`, making the `signed_by` tag unnecessary, so that the repository definition can be shortened to `deb https://apt.kubernetes.io/ kubernetes-xenial main`~~

**Comment by sftim** [comment]
@dhs-rec the keyring change you're proposing here might not represent good practice for using packages from a third party repository.

https://wiki.debian.org/DebianRepository/UseThirdParty advocates using `signed_by` for consuming third party code, and I agree with that page.

I agree about skipping the `apt-transport-https` install recommendation now that the built-in support is common.

**Comment by dhs-rec** [comment]
@sftim, wasn't aware of Debians recommendation about keyrings storage. Please ignore that suggestion, then.

**Comment by sftim** [comment]
@dhs-rec would you be willing to strike through that part of the issue description, for clarity?
