### ISSUE TITLE
Configure a Pod to Use a ConfigMap

### ISSUE THREAD

**Issue by nmacgreg** [kubernetes/website#30729]
This document jumps right into confusing vernacular describing the high-level effect:  "ConfigMaps allow you to decouple configuration artifacts...", meaningless to newbies.  Why not start by saying something inviting like, 
"Do you struggle with adjusting the parameters, like passwords or memory allocation, within a pod?  Then create a named ConfigMap (a key/value store managed within the core of Kubernetes itself), set up your parameters, then start your pod associated with the ConfigMap of your choice!"
This is a neat feature, but I had to read to the end of the document, and the linked example, before I began to understand what the opening statement actually means.

**Comment by sftim** [comment]
Pull requests welcome!

Please consider revising the [glossary entry for ConfigMap](https://kubernetes.io/docs/reference/glossary/?fundamental=true&storage=true&core-object=true#term-configmap) at the same time.

**Comment by deepakcpakhale06** [comment]
@nmacgreg  Do you mind reviewing the PR ? https://github.com/kubernetes/website/pull/31466

**Comment by Kartik494** [comment]
As #31466 is merged can we close this issue?

**Comment by mehabhalodiya** [comment]
I'm closing as #31466 resolves this issue.
If you feel anything's remaining, feel free to reopen! Thank you!
/close
