### ISSUE TITLE
Explain HTTPS ports (443, 6443) and differences for API server

### ISSUE THREAD

**Issue by cawoodm** [kubernetes/website#30725]
It's really ambiguous from the documentation which port the API server resides on:

> "the API serves on port 443, protected by TLS. "

> "default is port 6443"

Both refer to a secure, TLS, API Port.

It would be good to explain the distinction (if any) and how to change these ports. It would also help to explain if these are ports on the host or in the cluster.

Further confusion is the fact that "metrics-service" runs on the ClusterIP port 443 (internally).

**Comment by sftim** [comment]
/retitle Explain HTTPS ports (443, 6443) and differences for API server

The API server listens on port 6443 (by default). When you set up a non-toy cluster, you should _expose_ the API server on port 443; for example, using a load balancer that isn't part of Kubernetes.

My suggestion: add extra notes to https://k8s.io/docs/reference/ports-and-protocols/ about that, and then edit https://k8s.io/docs/concepts/security/controlling-access/ to link to that updated page.
