### ISSUE TITLE
[ko] Translate tasks/run-application/scale-stateful-set.md into Korean

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#30735]
This is a Feature Request
Translate [/content/en/docs/tasks/run-application/scale-stateful-set.md] in Korean

What would you like to be added
Translate [/content/ko/docs/tasks/run-application/scale-stateful-set.md] in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #30998
- #31637

/close
