### ISSUE TITLE
[hi] Localize what-is-kubernetes.md to Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#30732]
**This is a Feature Request**

**What would you like to be added**

We need to localize [what-is-kubernetes.md](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/overview/what-is-kubernetes.md) to Hindi.

**Why is this needed**

This page is needed as per [minimum required content](https://kubernetes.io/docs/contribute/localization/#minimum-required-content) for the ongoing Hindi Localization effort.

**Comments**

The current working branch for `hi` localization work is `dev-1.22-hi.1`. Please make sure to open a PR against `dev-1.22-hi.1`.
For more info see Hindi localization progress tracking issue #29353 

/language hi
/kind feature

**Comment by kranurag7** [comment]
Hey @ashish-jaiswar I would love to work with you on this issue.

**Comment by ashish-jaiswar** [comment]
/assign @kranurag7 
go ahead

**Comment by ashish-jaiswar** [comment]
hey @kranurag7, we both are working on the same issue, can you translate this page from 
## Why you need Kubernetes and what it can do {#why-you-need-kubernetes-and-what-can-it-do}
If you have any questions, feel free to ask.

**Comment by kranurag7** [comment]
Sure @ashish-jaiswar I will do it.

**Comment by ashish-jaiswar** [comment]
Hi @kranurag7 ,  hope you are doing great, are you completed the task ? If yes then please send it to me.

**Comment by kranurag7** [comment]
@ashish-jaiswar Yes, I have completed the localisation. I will review that once that and submit to you by evening today. Also, Please let me know where to submit?

**Comment by ashish-jaiswar** [comment]
ok, you can share me on slack. If you haven't join please in #kubernetes-docs-hi.

**Comment by kranurag7** [comment]
Yes, I have joined. I will share there.

**Comment by anubha-v-ardhan** [comment]
/close
Solved with #30847
