### ISSUE TITLE
Update /docs/concepts/cluster-administration/networking/ to exclude vendor specific information

### ISSUE THREAD

**Issue by jimangel** [kubernetes/website#30745]
**This is a Feature Request**

Update https://kubernetes.io/docs/concepts/cluster-administration/networking/ to either remove all vendor specific information or link to 3rd party documentation.

Related: https://github.com/kubernetes/website/pull/30134

**Why is this needed**

Update the docs to match our [style guide for 3rd party documentation](https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content).

/sig docs
/good-first-issue

**Comment by sftim** [comment]
/triage accepted

If you have questions about how to work on this, or you're not sure whether a piece of text does or doesn't comply with the policy on 3rd party content: go ahead and reply here to ask for that help.

SIG Docs reviewers are here to offer you that kind of advice.

**Comment by chetak123** [comment]
Should I remove all links which aren't pointing to a page in https://kubernetes.io/docs
For eg. should I remove all links in [this](https://kubernetes.io/docs/concepts/cluster-administration/networking/#cni-genie-from-huawei) paragraph and just remain normal texts ?

**Comment by kalashjain23** [comment]
> /triage accepted
> 
> **Everyone:** If you have questions about how to work on this, or you're not sure whether a piece of text does or doesn't comply with the policy on 3rd party content: go ahead and reply here to ask for that help.
> 
> SIG Docs reviewers are here to offer you that kind of advice.

I would like work on this but can you help with the information regarding projects that are necessary for kubernetes to function. I get the idea of removing unnecessary links but dont know which project to act on, so i will be looking forward to your reply :)

**Comment by kalashjain23** [comment]
Here's my attempt to solve this issue. Please guide me if there's something more to do or if I have removed something very important  :) 👍

**Comment by sftim** [comment]
@Tobi1to I'll highlight your request to the documentation special interest group

**Comment by sftim** [comment]
@Tobi1to did you have any specific questions about how to get started?

**Comment by NitishKumar06** [comment]
Hey @sftim , I'd be happy to work on this. Please guide me on how to get started here.

**Comment by debdeepsanyal** [comment]
/ assign

**Comment by debdeepsanyal** [comment]
@sftim hey can you please elaborate what exactly is vendor specific information so that i can edit it out of the documentation?
