### ISSUE TITLE
Extend the Kubernetes API with CustomResourceDefinitions

### ISSUE THREAD

**Issue by amniskin** [kubernetes/website#30748]
The documentation [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) says:

> The CRD can be either namespaced or cluster-scoped, as specified in the CRD's scope field. As with existing built-in objects, deleting a namespace deletes all custom objects in that namespace. CustomResourceDefinitions themselves are non-namespaced and are available to all namespaces.

This seems contradictory. Are CRDs namespaced (hence deleted along with the namespace) or not? Or does this mean that all CRDs are available to the whole cluster even if it's namespaced?

**Comment by sftim** [comment]
/wg api-expression

- CustomResourceDefinitions themselves are non-namespaced and are available to all namespaces.
- The CRD can be either namespaced or cluster-scoped, as specified in the CRD's scope field. 

When you add a CRD, you add that new custom resource API to the whole cluster. You must have rights to do this cluster wide.
The API that you add could be a namespaced API or it might not be. The `/apis/apiextensions.k8s.io/v1/customresourcedefinitions` [API](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/) is cluster-scoped (there is no namespace in the URL).

/language en

**Comment by sftim** [comment]
Maybe there's room to reword this, or to recommend some background reading to provide context?

**Comment by amniskin** [comment]
I'd appreciate that because those two bullet points seem like direct contradictions of one another. If a CRD is always non-namespaced, then it can't either be namespaced or cluster-scoped. CRD is the acronym for CustomResourceDefinition, right?
