### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/dns-pod-service/

### ISSUE THREAD

**Issue by Narsilion** [kubernetes/website#30744]
HI,

Looks like you have a typo on the page:
In summary, a pod in the test namespace can successfully resolve either data.prod or data.prod.svc.cluster.local.

Shouldn't here be "data.test or data.test.svc.cluster.local" instead?

**Comment by sftim** [comment]
The **pod** is in the test namespace. The **data service** is in the prod namespace.

I think the existing page text is accurate. We could make it more clear for people who read it and misunderstand.

@Narsilion do you think that we should emphasize things here? If so, which bits?

**Comment by Narsilion** [comment]
Hi @sftim, thank you, now I see and it it clearer to me. I think the concept is tricky itself, not sure if you can make it more clear.
