### ISSUE TITLE
Improvement for k8s.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/

### ISSUE THREAD

**Issue by averatio** [kubernetes/website#30761]
Hi,
First, I thank you for the present dcumentation.
I propose the following imporvements:
1/ I was looking for specification of a kubelet-credential-provider. I want to design  it for Hashicorp Vault (I have not found one yet) and then I need the interface and behavior interface. So, could we add a link towards the spec ?
2/ I was also looking for more information on "feature gate" related to the credential provider. 
Thanks a lot for K8S and all the work of the community.
AF

**Comment by tengqm** [comment]
Both `CredentialProviderConfig` and `CredentialProvider` are defined in [`pkg/kubelet/apis/config/types.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go#L530). However, these definitions are not showing up in the [kubelet config APIs](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go). That is the reason why we are missing them from the [Config API reference](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/).

**Comment by tengqm** [comment]
Dug more into it. Looks like `CredentialProviderConfig` and `CredentialConfig` are only part of the v1alph1 kubelet config API. I'm working on generating this reference.
/triage accepted
/kind feature
/assign

**Comment by tengqm** [comment]
Update: #30859 was submitted to add v1alpha1 version of kubelet API which includes the required struct definition. A follow up PR #30860 was added for introducing the communication APIs.
