### ISSUE TITLE
Umbrella issue: Assess existing documentation for docker mentions

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30771]
This issue is a part of the [Docs Dockershim removal](https://github.com/orgs/kubernetes/projects/67) project. 

## Description 

Assess the existing documentation set for mentions of docker to remove. 

This umbrella issue breaks out the documentation into its major sections so we can move through the docs set more easily. 

For now, the scope of this issue is the `en` localization. 

## Dependencies and timeline 

**All subtasks in this issue must be done before December 31st, 2021. If you take on a ticket in this umbrella issue and it is not complete before 2022, the issue owners will take over :)**

Owners: @celestehorgan, @nate-double-u

## Action plan  

We suggest:
- Doing a grep or plain-text search of the docs section in question for "docker"
- Next, doing a _visual_ review of the section's live pages on kubernetes.io, with a particular focus on code samples and sample YAML files. This is required to catch any sample files being pulled in which may not be present in a full-text search of the markdown source.

## Follow-up 

Once all subissues have reported their results, do the following in the 1.24 branch:

- Add a warning to all listed pages that any examples may not work (with a link back to the issue?) 
- Create an issue for each page for updates.

## Sub-issues

Contributors can select any open issue. For the ones with note: **not a beginner issue** beside them: please leave these to more experienced members of SIG Docs.

### Top-level pages 

- https://github.com/kubernetes/website/issues/30934
- https://github.com/kubernetes/website/issues/30936
- https://github.com/kubernetes/website/issues/30937

### Concepts 

- https://github.com/kubernetes/website/issues/30772
- https://github.com/kubernetes/website/issues/30773
- https://github.com/kubernetes/website/issues/30774
- https://github.com/kubernetes/website/issues/30775
- https://github.com/kubernetes/website/issues/30777
- https://github.com/kubernetes/website/issues/30921
- https://github.com/kubernetes/website/issues/30922

### Tasks 

- https://github.com/kubernetes/website/issues/30923
- https://github.com/kubernetes/website/issues/30925
- https://github.com/kubernetes/website/issues/30928
- https://github.com/kubernetes/website/issues/30929
- https://github.com/kubernetes/website/issues/30930

### References 

- https://github.com/kubernetes/website/issues/30931
- https://github.com/kubernetes/website/issues/30939 (note: **not a beginner issue**)
- https://github.com/kubernetes/website/issues/30932
- https://github.com/kubernetes/website/issues/30933
- https://github.com/kubernetes/website/issues/30941 (note: **not a beginner issue**)

**Comment by sftim** [comment]
This is also part of https://github.com/kubernetes/kubernetes/issues/104878

**Comment by anubha-v-ardhan** [comment]
> /assign

@shrikanta8 This is an umbrella issue you can assign one of the issues listed in this issue's description. Thank you

**Comment by shrikanta8** [comment]
sorry for the mistake

**Comment by celestehorgan** [comment]
Everything here has finally been categorized and ticketed!

Closing :D

**Comment by sftim** [comment]
Also relevant: https://github.com/kubernetes/website/issues/38898
