### ISSUE TITLE
Merge tutorials->clusters into tutorials->security

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/website#30778]
**This is a Feature Request**

**What would you like to be added**

Post-merge of #30422 , move the tutorials under https://github.com/kubernetes/website/tree/main/content/en/docs/tutorials/clusters into https://github.com/kubernetes/website/tree/main/content/en/docs/tutorials/security

Merge clusters section into security section here: https://github.com/kubernetes/website/blob/main/content/en/docs/tutorials/_index.md

**Why is this needed**
https://github.com/kubernetes/website/pull/30422#pullrequestreview-823841225

Issue description is a slight modification from original request in the comment

**Comments**

/hold for #30422 
/cc @sftim 
/sig docs security

**Comment by PushkarJ** [comment]
@savitharaghunathan this might be a good first issue for new contributors in sig-security-docs
/triage accepted

**Comment by Babapool** [comment]
Hi, I would like to work on this issue.
/assign

**Comment by Babapool** [comment]
Hi @PushkarJ, I have some questions regarding the fix of this issue:
1.  In the https://github.com/kubernetes/website/blob/main/content/en/docs/tutorials/_index.md file I need to rename the Clusters section as the Security section? (as I understood from the comment on the PR)
2.  About moving the Tutorials under the https://github.com/kubernetes/website/tree/main/content/en/docs/tutorials/security I just need move the tutorials from Clusters part to the Security part? 
If you and @sftim  have any better suggestions regarding the moving of tutorials, do share (I am little confused regarding this part) 
Thanks.

**Comment by Babapool** [comment]
Hi @PushkarJ @sftim , I a query:
1. After moving the tutorials from the cluster sub-directory into the security sub-directory, the cluster sub-directory will only have its _index.md file do I need to do something regarding it (_index.md file)? 
Thanks

**Comment by Babapool** [comment]
@sftim Whenever you are free can you please help me with the above mentioned query. Thanks
