### ISSUE TITLE
Check Concepts > Security and Concepts > Policies for dockershim content 

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30777]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check https://kubernetes.io/docs/concepts/security/ and h[ttps://kubernetes.io/docs/concepts/configuration/](https://kubernetes.io/docs/concepts/policy/) and **all their subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
Hi @ashish-jaiswar 

This ticket is time-sensitive and needs to be completed preferably before the end of the year. That said, it's pretty easy (just check for mentions of docker in these sections!)

If you can commit to the timeline, please go ahead. If not I'd prefer to assign someone else who can :)

**Comment by ashish-jaiswar** [comment]
hi @celestehorgan I am trying to resolve this issue ,If I can't then I will unassign for this issue.

**Comment by celestehorgan** [comment]
Hi @ashish-jaiswar! 

I'm not seeing a ton of movement on this issue and it's very time-sensitive: I'm going to reassign this to myself

/assign @celestehorgan

**Comment by celestehorgan** [comment]
Topics to update:

https://kubernetes.io/docs/concepts/security/overview/#the-4c-s-of-cloud-native-security - Diagram needs updating 

https://kubernetes.io/docs/concepts/security/overview/#the-4c-s-of-cloud-native-security, specifically https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/policy/restricted-psp.yaml 

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#capabilities

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp
