### ISSUE TITLE
gRPC probes with the different security configurations of the endpoints

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#30804]
**This is a Feature Request**

Starting 1.23, gRPC probes are built-in to k8s. https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe

It will be great to expand documentation explaining which secure endpoint settings will be respected and which wouldn't. Built-in gRPC probe will ignore certificate for TLS, but will likely not work with mutual TLS.

Need to work thru various configurations of endpoint setting and list whether it is supported by the built-in gRPC probe.

/sig node
KEP: https://github.com/kubernetes/enhancements/issues/2727
/help

**Comment by SergeyKanzhelev** [comment]
also can publish recommendation on testing gRPC endpoints by exposing plaintext endpoint and using TCP check. Like here: https://cloud.google.com/traffic-director/docs/security-proxyless-setup#create-health-check

**Comment by sftim** [comment]
Not yet triaged as accepted
/remove-help
