### ISSUE TITLE
Document annotation: volume.kubernetes.io/storage-provisioner

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30807]
**This is a Bug Report**

**Problem:** Kubernetes sets an annotation, `volume.kubernetes.io/storage-provisioner`. However, this annotation is not registered / documented.

**Proposed Solution:**
Add that annotation to [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/).
There is also a deprecated beta annotation, `volume.beta.kubernetes.io/storage-provisioner`; register / document that, and mark it as deprecated.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig storage
/language en
/priority backlog

https://github.com/kubernetes/kubernetes/pull/104590 and https://github.com/kubernetes/kubernetes/issues/104760 may provide some context for this.

**Comment by Kartik494** [comment]
/assign
I would like to work on this
