### ISSUE TITLE
Dockershim: Draft empathy blog post

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/website#30813]
Pre the first alpha cut of 1.24, a blog post should be drafted expressing the project's understanding that many users have not migrated off of dockershim, and migration can be painful but its needed for a variety of reasons and we are committed to documenting and making it as easy as possible.

/assign @celestehorgan @nate-double-u @sftim 
(For visibility)

/assign @SergeyKanzhelev @dims
sig-arch / sig-node (please loop in / assign others)

/assign
(for myself to keep track of)

/sig node architecture
/priority important-soon
/area blog

**Comment by sftim** [comment]
:100:
/triage accepted

**Comment by dims** [comment]
hoping @endocrimes can cover for me! also cc @adisky

**Comment by SergeyKanzhelev** [comment]
I started the draft, which is super rough and doesnt' have all the outline yet: https://docs.google.com/document/d/160edAf2q3-FY8SFNCfEoSWcQ0Y7OUUy4hD7nc-b11n8/edit#

**Comment by shannonxtreme** [comment]
IMO the draft is in a good enough place to be converted to a PR.
