### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/migrate-from-psp/

### ISSUE THREAD

**Issue by jglick** [kubernetes/website#30823]
This page would be more helpful if it listed actual `PodSecurityPolicy` YAML corresponding (to the extent possible) to the new baseline and restricted levels.

**Comment by sftim** [comment]
@jglick maybe if that page linked to the example PSP list in https://kubernetes.io/docs/concepts/security/pod-security-standards/#policy-instantiation? Would that help?

(BTW, those “levels” aren't entirely new - the 3 pod security standards have been in Kubernetes docs since May 2020)

**Comment by jglick** [comment]
Yes, that is exactly what I was looking for. Adding a link would be helpful.

**Comment by jglick** [comment]
There is https://kubernetes.io/docs/reference/access-authn-authz/psp-to-pod-security-standards/ which is probably good enough. I still find it somewhat clearer to just see stock PSP YAML examples so that you can check whether an existing PSP resources was simply copied from one of these. Unfortunately the link you referenced in https://github.com/kubernetes/website/issues/30823#issuecomment-1006141653 is no longer useful because the links to the PSP example files (though not the files themselves) was deleted: https://github.com/kubernetes/website/pull/33512#discussion_r875029058

**Comment by sftim** [comment]
There's a technical blocker to having example PodSecurityPolicies in the current docs: we validate the example manifests, and PSP is no longer part of Kubernetes.
