### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/init-containers/

### ISSUE THREAD

**Issue by chenlrambus** [kubernetes/website#30824]
The examples used in the doc do not make a lot of sense. 
We followed examples and implemented in  our application.  It does not work well, still see pods restarts multiple times before all pods settle. 

The root cause is that the examples use nslookup to check dependency microservice service IP, which could be available much earlier/quicker than the corresponding pods online. In an extreme case,  a service could be created with an IP address, but no corresponding pods.

**Comment by Kartik494** [comment]
Hi @chenlrambus i have tried it on my env the given example  running fine without many number of restarts
` 
kubectl get pods

NAME        READY   STATUS    RESTARTS   AGE
myapp-pod   1/1     Running   0          94s
`

**Comment by chenlrambus** [comment]
> Hi @chenlrambus i have tried it on my env the given example running fine without many number of restarts
> 
> kubectl get pods
> 
> NAME READY STATUS RESTARTS AGE myapp-pod 1/1 Running 0 94s

Probably the start up time of your pod is fast. If your pod start up time is slow, you will notice the issue.

**Comment by Kartik494** [comment]
@chenlrambus So for increasing the time for startup should i modify value for `sleep` in  pod yaml?
