### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-linux/

### ISSUE THREAD

**Issue by CatalinCnif** [kubernetes/website#30831]
Needs adaptation for redhat8.

**Comment by sftim** [comment]
Hi @CatalinCnif 

Could you describe how the current documentation falls short of what you were hoping for?

/language en
/triage needs-information
/sig cli

**Comment by CatalinCnif** [comment]
Following the guide here:
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

Redhat based distribution
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
has this link: baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
that is for redhat7

I was suggesting that a redhat8 would be necessary also going forward.

Thank you!

**Comment by mehabhalodiya** [comment]
@CatalinCnif I think it's somehow similar to [this](https://github.com/kubernetes/website/issues/27951).
Please have a look.
