### ISSUE TITLE
Add banner to highlight dockershim migration docs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30837]
**This is a Feature Request**

**What would you like to be added**
When there are good / good-enough docs for migration away from dockershim, add a banner that highlights these docs. Leave that banner in place until (maybe even after) the v1.24 release.

**Why is this needed**
[We're removing dockershim](https://github.com/kubernetes/kubernetes/issues/104878) from Kubernetes

**Comments**
/sig node
/kind feature

Will need steering committee signoff

**Comment by reylejano** [comment]
Hi @kubernetes/steering-committee , just want to put this on your radar

**Comment by reylejano** [comment]
@chris-short here's the PR that added a banner for KubeCon Europe 2021 
https://github.com/kubernetes/website/pull/27844
and here's one for a banner for KubeCon NA 2021 and announcement for KubeCon China
https://github.com/kubernetes/website/pull/29192

**Comment by liggitt** [comment]
is a months-long site-wide banner appropriate for this?

**Comment by sftim** [comment]
> months-long

I hadn't imagined that the banner would be _shown_ for months. It might be _ready_ for over a month though. I suppose I started off pessimistic that the relevant docs would be ready well before the next release.

We could
- add the banner with timings so that it's in place for a short time around the release - perhaps 3 days before the release and 7 days afterwards
- have a PR ready to add a banner, and hold that PR pending a problematic social media reaction (unholding if we think it becomes important to direct all readers to our key page on the topic)

**Comment by sftim** [comment]
We don't have a mechanism to mark banners as seen. Maybe it'd be useful to add one.

**Comment by chris-short** [comment]
Okay, so not a sitewide banner for months, check.

What should the banner say? Where should it link?

Found this in #31425, applicable here?   
  
Warning: This page mentions Docker Engine. Docker Engine compatibility was deprecated as of Kubernetes 1.24. For more information see \[Dockershim FAQ\](https://kubernetes.io/blog/2020/12/02/dockershim-faq/)

**Comment by sftim** [comment]
@chris-short what #31425 suggests a notice for specific pages.

This is about adding a banner (see https://github.com/kubernetes/website/pull/23183 for an example) that shows across every page of the site, during a defined period.

We might want to do either or both. _This_ suggestion, the site-wide banner, is not yet triaged as accepted.

**Comment by sftim** [comment]
I'm thinking we might say “Want to know more about changes in Kubernetes v1.24 around integration with Docker Engine? Visit xxxx”. Something like that.

**Comment by chris-short** [comment]
Yes, I good with the schedule and mechanics of making that happen.

I was more interested in the message itself. I still think the dockershim FAQ might be the best to send folks despite it having an outdated info warning on it now. Can we turn that off for that page?!?

**Comment by chrisnegus** [comment]
@chris-short It looks like someone just put out an update of the blog: https://kubernetes.io/blog/2022/02/17/dockershim-faq/

**Comment by chris-short** [comment]
That was me

**Comment by chrisnegus** [comment]
Since I took on [Issue #31425](https://github.com/kubernetes/website/issues/31425) I can work on this one as well.
/assign

**Comment by chrisnegus** [comment]
I added [PR #32805](https://github.com/kubernetes/website/pull) to address this issue. I'm looking for feedback on wording, graphics and timeframe.

**Comment by chrisnegus** [comment]
[PR #32805](https://github.com/kubernetes/website/pull/32805) merged
/close

**Comment by sftim** [comment]
/reopen

We should prepare a banner update to go live on release day.

**Comment by sftim** [comment]
Done
/close
