### ISSUE TITLE
Document on the probes page that redirects are not followed to

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#30849]
/sig node
/help
/priority backlog

On this page: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ it will be nice to note that the http probe will not follow redirects. It will succeed on redirect response like `302`, but will report the warning like seen here: See this comment: https://github.com/kubernetes/kubernetes/pull/103967/files#r766430505

```
Events:
  Type     Reason        Age                     From               Message
  ----     ------        ----                    ----               -------
  Normal   Scheduled     29m                     default-scheduler  Successfully assigned default/httpbin-7b8bc9cb85-bjzwn to daocloud
  Normal   Pulling       29m                     kubelet            Pulling image "docker.io/kennethreitz/httpbin"
  Normal   Pulled        24m                     kubelet            Successfully pulled image "docker.io/kennethreitz/httpbin" in 5m12.402735213s
  Normal   Created       24m                     kubelet            Created container httpbin
  Normal   Started       24m                     kubelet            Started container httpbin
  Warning  ProbeWarning  4m11s (x1197 over 24m)  kubelet            Readiness probe warning: <body>
```

This is also an important change over the http lifecycle hook, see: https://github.com/kubernetes/kubernetes/pull/86139 Perhaps it can be noted on this page: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

**Comment by sftim** [comment]
/language en
/triage accepted

Thanks for reporting on this.

**Comment by brianpursley** [comment]
Is this true for redirects in general, or only external redirects?

The [issue that PR fixes](https://github.com/kubernetes/kubernetes/issues/103877) says "external redirects" and redirects to a different host in the readiness probe.

The below seems to work fine for me (no warnings).  I can use `/old` as my readiness probe even though it 302 redirects to `/health`:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      absolute_redirect off;
      location ~ ^/health$ {
        add_header Content-Type text/plain;
        return 200 'healthy';
      }
      rewrite ^/old$ /health redirect;
    }
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: config
      mountPath: /etc/nginx/conf.d
    readinessProbe:
      httpGet:
        path: /old
        port: 80
  volumes:
  - name: config
    configMap:
      name: nginx-config
      items:
      - key: default.conf
        path: default.conf
```

**Comment by sftim** [comment]
I spotted the feedback from https://github.com/kubernetes/website/issues/30849#issuecomment-1165922398

This is not a valid issue as it stands.
/remove-triage accepted
/remove-help

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/44098

/close
