### ISSUE TITLE
[Dockershim removal] Document the change for pod-infra-container-image

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#30842]
/kind feature
/sig node

1. Update docs for the flag pod-infra-container-image as dockershim is removed (also tracked here: https://github.com/kubernetes/kubernetes/issues/106893)

2. Document how to transition from using this flag to Contained setting when migrating off dockershim

Also see https://github.com/kubernetes/kubernetes/issues/106903#issuecomment-990131103

**Comment by chris-short** [comment]
I'm not quite sure what needs to happen with this issue specifically. Is the umbrella issue going to cover this?

What needs to change in relation to this issue?

**Comment by mehabhalodiya** [comment]
> What needs to change in relation to this issue?

@SergeyKanzhelev Can you please describe more?

**Comment by SergeyKanzhelev** [comment]
similar to this: https://github.com/kubernetes/kubernetes/issues/108144

The flag `pod-infra-container-image` is deprecated. On migration - users needs to stop using this flag and instead configure the container runtime with the proper configuration setting. For containerd it is a `sandbox_image`

**Comment by hakman** [comment]
@SergeyKanzhelev Users should stop using the flag only when using a container runtime that supports image pinning. At the moment there's work being done on the containerd side.
https://github.com/containerd/containerd/pull/6456

Other CRIs only have issues created for implementing image pining:
https://github.com/cri-o/cri-o/issues/5652
https://github.com/Mirantis/cri-dockerd/issues/39

**Comment by afbjorklund** [comment]
The current situation is that you end up with two (or more) versions of pod-infra-container:

```
IMAGE                                     TAG                 IMAGE ID            SIZE
k8s.gcr.io/pause                          3.1                 da86e6ba6ca19       742kB
k8s.gcr.io/pause                          3.6                 6270bb605e12e       683kB
```

Depending on the actual versions of kubernetes and the container runtime being involved.

Ironically the containerd config said "k8s.gcr.io/pause:3.2", so something else is broken too.

**Comment by chrisnegus** [comment]
The pod-infra-container-image flag is only mentioned in two files currently. The one in reference docs will go away when reference docs are rebuilt for 1.24. The mention in https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/ will be removed in PR to be named later. If there are new feature to replace image pining for other runtimes, please create a new issue.

**Comment by chrisnegus** [comment]
[PR #31899](https://github.com/kubernetes/website/pull/31899/files) removes the --pod-infra-container-image option. So we should close this issue once that PR merges.

**Comment by nate-double-u** [comment]
The dockershim work is ongoing, but as 1.24 is releasing today, i'm clearing the milestone.

/milestone clear

**Comment by chrisnegus** [comment]
The final instance of --pod-infra-container-image was removed with [PR # 33582](https://github.com/kubernetes/website/pull/33582/).
/close

**Comment by SergeyKanzhelev** [comment]
/reopen

this bug was suggesting to add a note to dockershim migration document to suggest customers what to replace this flag with on migration off dockershim. See comment https://github.com/kubernetes/website/issues/30842#issuecomment-1048088591

This document will benefit from this instruction: https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/#configure-the-kubelet-to-use-containerd-as-its-container-runtime


This is one of the flags, other flags not documented in the migration document and causing confusion (see report: https://twitter.com/krisnova/status/1528735755794894850?t=RWDf1J4FsWgZdNmGk4Cf4A&s=03):

> Upon closer investigation [these flags were removed](https://github.com/kubernetes/kubernetes/pull/106907) for the notorious “dockershim deprecation”.

**Comment by afbjorklund** [comment]
> The flag `pod-infra-container-image` is deprecated. On migration - users needs to stop using this flag and instead configure the container runtime with the proper configuration setting. For containerd it is a `sandbox_image`

For cri-dockerd, it is called `--pod-infra-container-image` :-) Eventually it will also be possible to set using configuration files:

* https://github.com/Mirantis/cri-dockerd/issues/102

**Comment by divya-mohan0209** [comment]
@SergeyKanzhelev Would it be appropriate to link [this](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/#configure-the-kubelet-to-use-containerd-as-its-container-runtime) right before [this section](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#override-pause-image-containerd) starts by adding a note stating that if you're migrating away from Docker refer to the guide to understand how to get Kubelet working with containerd? 
If not, where else would you place it?
