### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateless-application/

### ISSUE THREAD

**Issue by jazeem-azeez** [kubernetes/website#30861]
Please refer 
https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
I would like to see documentation similar to the one above for stateless

**Comment by sftim** [comment]
@jazeem-azeez would you be willing to explain how https://kubernetes.io/docs/tutorials/#stateless-applications falls short of what you were hoping for?

/triage needs-information
/language en
