### ISSUE TITLE
Endpoints - The example section should be formatted as code

### ISSUE THREAD

**Issue by benignbala** [kubernetes/website#30878]
The example section of the Endpoints page shows a JSON example that needs to be formatted as code.

**Comment by sftim** [comment]
It sounds like you're reporting an issue in https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoints-v1/

That page is generated from Kubernetes source code, and we don't yet have a way to represent markup in that source code. Issue https://github.com/kubernetes/kubernetes/issues/106437 is very broadly about the same kind of thing.
