### ISSUE TITLE
Clarify default preemption behavior

### ISSUE THREAD

**Issue by WilliamDenniss** [kubernetes/website#30887]
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

Regarding this line:

> If there is no PriorityClass with globalDefault set, the priority of Pods with no priorityClassName is zero.

I think it's worth adding some documentation about the default _preempting_ behavior too -- being that the default priority will preempt pods with a negative priority (i.e. if it was expressed as a PriorityClass, the setting would be `PreemptionPolicy: PreemptLowerPriority`). Something like:

> If there is no PriorityClass with globalDefault set, the priority of Pods with no priorityClassName is zero, and will preempt lower priority pods (being those with a negative priority).

**Comment by sftim** [comment]
/language en
/kind feature
/triage accepted
/help


We could link to https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#non-preempting-priority-class to highlight that if you want Pods to have non-preempting behavior, you must explicitly configure this and assign those Pods to the PriorityClass you declared.

**Comment by brianpursley** [comment]
I'm trying to understand if clarification is needed here or not.

I feel like this suggested text already seems obvious, to me at least, and a this information is provided elsewhere on the page already:
```
and will preempt lower priority pods (being those with a negative priority).
```

That being said, if is decided that clarification would be helpful here, how about something like this?

> A pod's [priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) is used by the scheduler to determine its position in the scheduling queue, and along with [`preemptionPolicy`](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#non-preempting-priority-class), determines whether it can preempt, or be preempted, when there are not enough node resources available to satisfy all pod requests.

**Comment by sftim** [comment]
/retitle Clarify default preemption behavior

I'm also not sure if further clarification is needed.
/remove-help
/priority backlog

If this rots out, so be it.

**Comment by sftim** [comment]
@WilliamDenniss if you open a pull request to make the improvement in https://github.com/kubernetes/website/issues/30887#issuecomment-1165870514, we'll review it.
