### ISSUE TITLE
Play with k8s website not loading 

### ISSUE THREAD

**Issue by ashish211985** [kubernetes/website#30888]
**This is a Bug Report**

Play with k8s website is not loading after i sign in. Its giving the following error :
**_This page isn’t workinglabs.play-with-k8s.com is currently unable to handle this request.
HTTP ERROR 500_**

Can someone please help ?

**Comment by jihoon-seo** [comment]
For me,

right after login with GitHub:
![image](https://user-images.githubusercontent.com/46767780/145786762-210f4c79-9632-4f80-99c4-84e94c27b8db.png)

---

after click the "Start" button:
![image](https://user-images.githubusercontent.com/46767780/145787281-a7177b33-93c9-4a77-862b-c6adfb63b3fc.png)

---

Not loading here too! 😥

But I think that an issue should be opened at https://github.com/play-with-docker/play-with-docker repo, not here 😊
