### ISSUE TITLE
Update glossary entry for Quantity

### ISSUE THREAD

**Issue by systems1** [kubernetes/website#30885]
update memory to include M  G vs Mi Gi (Gibibyte versus Gigabyte)

**Comment by jihoon-seo** [comment]
- Link to the page: https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

In the [Memory units section](https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#memory-units), there exists a paragraph:
> The memory resource is measured in bytes. You can express memory as a plain integer or a fixed-point integer with one of these suffixes: E, P, T, G, M, K, Ei, Pi, Ti, Gi, Mi, Ki. For example, the following represent approximately the same value:

---

@systems1 Could you elaborate what you are suggesting exactly? (Including your example would be a good idea) 😊

**Comment by systems1** [comment]
could you add few  lines of below to make it easy to understand
Base 2 versus base 10 calculation of data
GiB stands for Gibibyte and GB stands for Gigabyte.
GiB: unit symbol of Gibibyte
GB: unit symbol of Gigabyte

**Comment by sftim** [comment]
We could add a [glossary](https://kubernetes.io/docs/reference/glossary/?all=true) entry for “Quantity” and include some of these details in that entry.

(That's what I'd do).

Also see the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/) for quantity. This is directly generated from upstream code.

**Comment by Kartik494** [comment]
Hi @sftim is it ok to document this in https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

> could you add few lines of below to make it easy to understand as both are allowed and some people new Base 2 versus base 10 calculation of data GiB stands for Gibibyte and GB stands for Gigabyte. GiB: unit symbol of Gibibyte GB: unit symbol of Gigabyte

**Comment by sftim** [comment]
> Hi @sftim is it ok to document this in https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/

Yes, I think so. However, I recommend adding a glossary entry for Quantity and putting at least an outline of the details there instead.

**Comment by Kartik494** [comment]
@sftim Sure i will give a try on this.

**Comment by divya-mohan0209** [comment]
@Kartik494 : Just checking in, are you still working on this? We'd otherwise be able to publish this as an issue for contributors to work on.

**Comment by Kartik494** [comment]
@divya-mohan0209  sorry for delaying , i have been busy working on other issues , please feel free to assign this issue if someone want to work on it.

**Comment by divya-mohan0209** [comment]
Thank you for confirming @Kartik494 . Please don't be sorry, we understand!

**Comment by divya-mohan0209** [comment]
To those picking up the issue: 

[This comment](https://github.com/kubernetes/website/issues/30885#issuecomment-993643050) will need to be fleshed out a bit more for the Glossary entry. You can also refer  The new Glossary entry page will need to be added [here](https://github.com/kubernetes/website/tree/main/content/en/docs/reference/glossary). Please ask questions if you have any doubts!

**Comment by Aayush987** [comment]
So we have to create a new file for quantity in glossary and add the above mentioned comment's data in it?@divya-mohan0209

**Comment by divya-mohan0209** [comment]
Not word-for-word, but yes. You need to elaborate on the content in the comment a bit more and create a new file for Quantity in the glossary section.

**Comment by Aayush987** [comment]
> Not word-for-word, but yes. You need to elaborate on the content in the comment a bit more and create a new file for Quantity in the glossary section.

One last question, where can I search for the content , like is there any document i could take help from?

**Comment by divya-mohan0209** [comment]
Please refer to [this comment](https://github.com/kubernetes/website/issues/30885#issuecomment-1004256060) above. I'd also request you to read through the above discussion entirely to gain context of the issue at hand and then ask questions.

**Comment by FavourDaniel** [comment]
I can work on this right away, has it been assigned to anyone? @divya-mohan0209

**Comment by divya-mohan0209** [comment]
@FavourDaniel : 

SIG Docs' no cookie-licking policy applies: it's always OK for anyone to open a pull to work on any issue, including this one. When starting work, liaising with anyone who has already opened a PR or otherwise expressed an intention to work on the issue is polite.

**Comment by FavourDaniel** [comment]
alright thank you @divya-mohan0209

**Comment by Sajiyah-Salat** [comment]
I want to work on this issue. Can I get this assigned?

**Comment by divya-mohan0209** [comment]
Please see [comment](https://github.com/kubernetes/website/issues/30885#issuecomment-1386558553) above @Sajiyah-Salat . You can assign yourself the issue by using the /assign command FYI.

**Comment by sftim** [comment]
Turns out we've had one since https://github.com/kubernetes/website/pull/9780

**Comment by sftim** [comment]
/retitle Update glossary entry for Quantity

Oops.

**Comment by KhushPatibandha** [comment]
I would like to work on this issue. This is my first contribution, so please help me if I get stuck.

**Comment by KhushPatibandha** [comment]
<img width="582" alt="k8s" src="https://user-images.githubusercontent.com/104303438/219743680-09465351-bcc1-4e76-91ba-563594fa8c6f.png">

Based on the understanding from the past conversation, I made these changes made sort of draft. Can you please check if everything is correct so I can make a PR with final changes.

**Comment by sftim** [comment]
This is done now - https://kubernetes.io/docs/reference/glossary/?all=true#term-quantity has the details needed.

/close
