### ISSUE TITLE
kubeadm install needs apparmor

### ISSUE THREAD

**Issue by PhilipMay** [kubernetes/website#30899]
I have a "bare metal" Debian 11 server and install k8s with kubeadm.

I follow this guide: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

The install with `kubeadm init --pod-network-cidr=192.168.0.0/16` fails:

```text
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
		- 'crictl --runtime-endpoint /run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'crictl --runtime-endpoint /run/containerd/containerd.sock logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
```

Looking at containerd logs shows this: `error="failed to create containerd container: get apparmor_parser version: exec: \"apparmor_parser\": executable file not found in $PATH"`

Installing apparmor `apt install apparmor` fixes it and the installation works.

IMO this dependency should be added at the installation instructions. Somehere here: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by PhilipMay** [comment]
Well - it could be added as a hint in this "Install containerd:" box here: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

Want me to suggest a PR?

**Comment by neolit123** [comment]
I am waiting on a response in
https://github.com/kubernetes/kubernetes/issues/106974 from sig node
because apparmor was not a requirement before.

Maybe containerd changed.

/sig node

**Comment by sftim** [comment]
Some docs somewhere need to change. Right now it's not clear which.

**Comment by neolit123** [comment]
response here:
https://github.com/kubernetes/kubernetes/issues/106974#issuecomment-995128016

the summary is that this is a problem (missing dependency) in the containerd packages, not the k8s packages.
please report this to containerd.

the docs in the k8s website can be updated if needed (e.g. switching to a different repo from the one from docker for containerd), but i don't think we need to mention the apparmor CLI explicitly.

**Comment by sftim** [comment]
/remove-priority awaiting-more-evidence
/language en
/triage accepted
/priority backlog

We should update our docs on installing containerd. Perhaps we can link to external install instructions?

**Comment by neolit123** [comment]
> We should update our docs on installing containerd. Perhaps we can link to external install instructions?

looks like this is being updated as part of https://github.com/kubernetes/website/pull/30882/files#r805354269
https://github.com/kubernetes/website/pull/30882/files#r805354518

/close
