### ISSUE TITLE
Action on Docker mentions in Concepts > Extending Kubernetes

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30898]
Umbrella issue: #30771 
Fixes #30922

https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
FIle: kubernetes/website/content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md

- Description: Docker is mentioned three times in the doc and `dockershim` once
- Line: 24, 31, 33, 149
- Actions
  
  - For [Installation](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#installation), not sure. The description of how the kubelet looks for plugins probably needs to change. 
  - For [Network plugin requirements](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements), update the URL in the link to the CRI equivalent (perhaps k8s.io/cri-api/pkg/apis/runtime/v1, not sure)
  - For [Network plugin requirements](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements), remove `like Docker with a bridge`.
  - For [Customizing the MTU](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#customizing-the-mtu-with-kubenet), remove Docker.

/sig docs
/language en
/help-wanted

**Comment by mehabhalodiya** [comment]
What to do with these? @kubernetes/sig-docs-en-owners 
>For Installation, not sure. The description of how the kubelet looks for plugins probably needs to change.
For Network plugin requirements, update the URL in the link to the CRI equivalent (perhaps k8s.io/cri-api/pkg/apis/runtime/v1, not sure)

I am asking as @shannonxtreme is not sure.

**Comment by chris-short** [comment]
@reylejano Any thoughts here?

**Comment by reylejano** [comment]
There is an open PR to update this page, PR https://github.com/kubernetes/website/pull/31667 but still need a few fixes for this issue:

- For [Network plugin requirements](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements), SIG Node would have to confirm what the updated link should be to

- I agree with @shannonxtreme on the [Network plugin requirements](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#network-plugin-requirements) section to remove `like Docker with a bridge`

**Comment by mehabhalodiya** [comment]
Okay, so someone is working on this, I am unassigning myself 🙂 
Thank you for the updates!

**Comment by nate-double-u** [comment]
/assign @chrisnegus 
To follow up on the status of this issue.

**Comment by sftim** [comment]
An org member can close this. What's the reason / justification for closing?

**Comment by rolfedh** [comment]
@sftim Looking over the content, it seems like the issue has been resolved. I reviewed this with the team in the "SIG Docs: 1.24 Dockershim removal" meeting, and we agreed that this looks like it should be closed.
