### ISSUE TITLE
Remove docker from Node-pressure Eviction

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30896]
URL: https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/
File: /docs/concepts/scheduling-eviction/node-pressure-eviction.md
Umbrella issue: #30771 
Partially fixes: #30921 

## What to do

On line 238, remove `docker` from the examples of system daemons. 

## How to do it

Refer to the [Contributor Guide](https://kubernetes.io/docs/contribute/new-content/open-a-pr/) for instructions.

Do the following:

1. Fork k/website and switch to a new branch 
2. Remove `docker` from line 238 of the `/docs/concepts/scheduling-eviction/node-pressure-eviction.md` file
3. Open a PR for the change and mention this issue to close it when the PR is merged

/triage accepted
/sig docs
/help-wanted
/language en

**Comment by killerkc12** [comment]
I would like to work on this

**Comment by celestehorgan** [comment]
@killerkc12 do you intend to work on this? If not I'd like to reassign it to someone who will. No hard feelings either way!

**Comment by PurneswarPrasad** [comment]
@celestehorgan I think this issue has been resolved in this PR here #30913
