### ISSUE TITLE
Action on Docker mentions in Concepts > Cluster Administration 

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30897]
Umbrella issue: #30771 
Partially fixes #30921 

URL: https://kubernetes.io/docs/concepts/cluster-administration/logging/
File: kubernetes/website/content/en/docs/concepts/cluster-administration/logging.md
- Description: Docker is mentioned as an example of a container engine. 
- Line: 65-70
- Action: Not sure if remove or not. 

---

URL: https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-location
File: kubernetes/website/content/en/docs/concepts/cluster-administration/system-logs.md
- Description: Docker is used as the runtime example
- Line: 185
- Action: Remove `for example, Docker`.

/sig docs
/language en
/help-wanted

**Comment by sftim** [comment]
For https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-location I would turn “container runtime” into a glossary tooltip.
/sig node

**Comment by shannonxtreme** [comment]
For https://kubernetes.io/docs/concepts/cluster-administration/logging/, I don't know what the correct action is. I'm leaning towards deleting the stuff about Docker Engine and the logging driver that it uses. 

/assign
/triage accepted

**Comment by mehabhalodiya** [comment]
> For https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-location I would turn “container runtime” into a glossary tooltip. /sig node

@sftim May I add a glossary tooltip for `container runtime`?

**Comment by sftim** [comment]
> May I add a glossary tooltip for container runtime?

You're entirely welcome to open a PR for that @mehabhalodiya (and no, I don't have any objection). https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary has the docs on how our glossary tooltips work.

**Comment by shannonxtreme** [comment]
My PR already adds that. Container runtime is already a glossary entry so I just added the tooltip in #31282 @mehabhalodiya

**Comment by mehabhalodiya** [comment]
Fine, I will not add anything! 
Good work @shannonxtreme 🎉
