### ISSUE TITLE
Document observability concerns for production clusters

### ISSUE THREAD

**Issue by carmilea** [kubernetes/website#30901]
I believe a key topic area is missing from this document, "Production environment", which has to do with Observibillity, Monitoring, and Alerting.

Observability, Monitoring, and Alerting should be a defacto conversation point on any Kubernetes cluster meant for production workloads.  I'm not suggesting we go in-depth into how to set up monitoring and alerting, but it should be touched on in the Production Section.

It could be that I'm missing something and this topic is touched on elsewhere?

**Comment by sftim** [comment]
/kind feature
/retitle Document observability concerns for production clusters
/sig instrumentation docs
/language en

**Comment by sftim** [comment]
The section to update: https://kubernetes.io/docs/setup/production-environment/

**Comment by dashpole** [comment]
cc @ehashman
We generally try to stay neutral on telemetry pipelines and backends, which are generally required to set up production monitoring, tracing and logging.  But if there are ways for us to improve documentation without recommending backends, that would be useful.

**Comment by dashpole** [comment]
@serathius mentioned there are [SLOs](https://github.com/kubernetes/community/tree/master/sig-scalability/slos) we should recommend users monitor in production clusters to ensure the cluster is working as expected.  Pointing out _which_ metrics, rather than where to send them, may be a good content for such a guide.

**Comment by ehashman** [comment]
As @dashpole said, this is an area that's very context dependent and with a number of different tools and options (both open and closed source). As a SIG, we've tried to move away from documenting all possible monitoring solutions, e.g. https://github.com/kubernetes/kubernetes/pull/106360

However, there are a couple of talks I gave (solo and with @logicalhan) that focus on CNCF-maintained monitoring solutions and provide an overview of Kubernetes production monitoring that may be helpful here:

- [Operating within Normal Parameters: Monitoring Kubernetes](https://youtu.be/GDo-Ixy_i9k) at SREcon 2019 Americas. 
    - Related link dump on my website: https://hashman.ca/srecon-2019/
- [Weighing a Cloud: Measuring Your Kubernetes Clusters](https://www.youtube.com/watch?v=BknenxQ_NLQ) at KubeCon NA 2019.
    - Related link dump on my website: https://hashman.ca/kubecon-2019/
- Monitoring demo I put together based on 1.12: https://github.com/ehashman/k8s-monitoring-demo (not updated for the latest k8s but fundamentals remain the same)

**Comment by sftim** [comment]
SIG Instrumentation folks, should we triage this as accepted?

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/27840 might also be relevant (slightly)
