### ISSUE TITLE
NetworkPolicy concept doc needs update after egress added

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#30908]
As discussed in the sig-networking mailing list (https://groups.google.com/g/kubernetes-sig-network/c/6k1A8l5uxLY), https://kubernetes.io/docs/concepts/services-networking/network-policies/#isolated-and-non-isolated-pods has not been fully updated since the introduction of egress filtering.

**Comment by sftim** [comment]
/sig network
/sig docs

/kind bug
(it's a bug because the doc should already have been updated)

/language en

/triage accepted
