### ISSUE TITLE
Blog post: What you need to do to have a working cluster for 1.24

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30917]
## Description 

The team wants to see a bare-bones blog post with the theme "here's exactly what you need to do to go from a working 1.23 cluster to a working 1.24 cluster" in regards to the Dockershim removal.

Writing this post will entail pulling down the alpha release, which is ready as of now. 

The goal here is to provide a no-nonsense outline for cluster operators and administrators. 

The nature of the post is that it _will_ become dated at some point in the future: it should be written and structured as something relevant for a certain period of time rather than something intended to be evergreen.

If for some reason a cluster operator needs to maintain compatibility with Docker, the post should cover what their options are in doing so.

## Release date 

Early in the 1.24 release cycle - let's target end of January or early February

## Other thoughts 

Perhaps talk to @jimangel about this, as he's a cluster operator and can offer valuable insight.
Talk to @mrbobbytables  about some of the work Mirantis et al are handling in this regard.

**Comment by jimangel** [comment]
Happy to help here! It might be worth chatting with [SIG Cluster Lifecycle](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle) too about their plans for the kubeadm upgrade document.

I wrote a post about moving from 1.23 to 1.24 but I did some semi-anti-pattern things like altering the `kubeadm` config before upgrading (`kubeadm` recommends to build new vs. tweak config inflight) and manually adjusted the `kubelet` config. They might have a strong opinion on the _how_ we recommend upgrading / updating the `kubelet` config.

cc @neolit123

**Comment by neolit123** [comment]
Having a single blog post covering everything around dockershim for 1.24 makes sense.

I would like this migration guide to merge first:
https://github.com/kubernetes/website/pull/30141
I already reviewed it and it should include kubeadm notes.

The kubeadm upgrade page for 1.24 can link to it as a pre req. Blog posts and the main container runtime page can link to it too.

Migrating dockershim as part of the kubeadm upgrade is risky. If users face both container runtime and k8s component upgrade problems it can be difficult to debug for them and those who will try to help them.

**Comment by mickeyboxell** [comment]
Thanks @nate-double-u. It looks like this blog would be another good candidate for inclusion in the 1.24 deprecations and removals blog post as long at it is complete prior to 31-MAR-2022.

**Comment by sftim** [comment]
Article is merged and published
/close
