### ISSUE TITLE
Blog post: historical context of the dockershim removal

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30918]
~If you aren't @amye don't assign yourself to this~

## Description 

The dockershim removal is a confusing change to communicate: why is Dockershim in Kubernetes to begin with? How is Docker as a company related to this change, 

Write a blog post describing the historical context of why dockershim was in Kubernetes in the first place, why the project is choosing to remove and deprecate it (and how that benefits both the ecosystem and the project in the long run), and how this is a chance for the community to come together in support of open standards.

Some points to highlight:
- moving towards open standards like crictl is in line with our open source philosophy!
- as is deprecating vendor-specific code!
- docker still works inside containers!
- ... and more!

## Concerns

Let @amye handle this one, as we want to make sure to message this correctly. 

## Due date 

Somewhere in the 1.24 cycle Mid to late March

**Comment by amye** [comment]
Concerns: 
Some users may still be surprised! We do the very best we can to make sure the surprise is (1) minimal and (2) fixable.

**Comment by afbjorklund** [comment]
This historical article needs to make surte to mention the `rkt` container runtime:

https://kubernetes.io/blog/2016/07/rktnetes-brings-rkt-container-engine-to-kubernetes/

https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/

The main burial ground is https://github.com/kubernetes-retired/rktlet if wanting to visit...

i.e. both "rkt" container runtime and "docker" container runtime lives on, through CRI.

The real removal is for the rktnetes and the dockershim internal "half-way" steps.

----

I think rkt was introduced in 1.3 and killed off around 1.10, or something like that ?

Then there was a long silence, until resurfacing again with kubernetes 1.20 release.

**Comment by sftim** [comment]
I'd probably only mention rkt etc in passing. It was one of several container runtimes available at the time; for example, https://kubernetes.io/blog/2016/05/hypernetes-security-and-multi-tenancy-in-kubernetes/ talks about another.

**Comment by afbjorklund** [comment]
Didn't know that it was merged in the same way (hypernetes). But I guess there is near-term and long-term history...

**Comment by sftim** [comment]
@amye, do you have all the context you need to move this forward?

**Comment by mickeyboxell** [comment]
Does this blog look like a good candidate for inclusion in the 1.24 deprecations and removals blog post?

**Comment by sftim** [comment]
> does this blog look like a good candidate for inclusion in the 1.24 deprecations and removals blog post?

I think what you're suggesting is that we aim publish _this_ article ahead of the v1.24 deprecations and removals blog post, and then have the 1.24 deprecations and removals blog post hyperlink to this article. Is that right?

if so, @mickeyboxell, that does sound like a good idea.

**Comment by amye** [comment]
> @amye, do you have all the context you need to move this forward?

Sorry, I think there's been a miscommunication on this! This is not a thing that I can carry, this is something that the release team should work with. 
What I _can_ do is work with the CNCF PR team if you need them to be able to publicize this.

**Comment by mickeyboxell** [comment]
@katcosgrove This was the post we chatted about.

**Comment by katcosgrove** [comment]
@mickeyboxell Should this wait for the other Dockershim removal blog I have assigned, or the other way around?

**Comment by nate-double-u** [comment]
If the other one is https://github.com/kubernetes/website/issues/30917, I think the Idea was for it to go out first, and this one to go out on release day. 

Both are listed on the [blog articles planning board](https://github.com/kubernetes/website/projects/11), but there are no dates associated there either. @sftim do you have a sense of when these should go out (in relation to the other posts that are already scheduled)?

**Comment by shannonxtreme** [comment]
I'm not Tim (obviously) but I think the blog post about having a working cluster for 1.24 should take priority. I'd imagine that a cluster operator would care more about how not to enter a broken state in 1.24 than they would care about why we are doing the change (the why can come after they aren't broken). My vote is to publish the "how not to be broken" post soon. 

(also I don't think calling this blog post "historical context" would be great. I really like the content components - how does this benefit the ecosystem, how does it align with our philosophy, etc. I think the title and marketing of the post should be focused on that. "Why Kubernetes removing dockershim is a good thing" basically.)

**Comment by mickeyboxell** [comment]
@katcosgrove as discussed over Slack, it would be great to see this ship on 4-MAY-2022.

**Comment by nate-double-u** [comment]
/milestone clear
v1.24 has been released, but this can come in after.
