### ISSUE TITLE
Dockershim: collate a list of 3rd party resources on the topic

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30919]
## Description 

Assemble a list of links for 3rd party resources regarding migrating k8s resources away from Docker and onto other platforms. 

## Other thoughts 

This needs more scoping, and I think @mrbobbytables has a better idea of what needs to be done here.

**Comment by rolfedh** [comment]
@celestehorgan @mrbobbytables This is my first time contributing a new topic to kubernetes/website. From reading the contributor information and looking at the content structure, I'm guessing the deliverable should be a reference topic named `/kubernetes/website/content/en/docs/tasks/administer-cluster/migrating-from-dockershim/third-party-topics-on-dockershim-deprecation.md`. WDYT?

**Comment by rolfedh** [comment]
@celestehorgan Do I understand the user story for this task correctly:

"As a k8s admin, I want to a list of authoritative third-party articles on the dockershim deprecation and using alternative CRI-compatible runtimes."

Please clarify any missing user roles and stories. 

How about including primary (Kubernetes) and secondary sources?
