### ISSUE TITLE
Check Tasks > Install and Tasks > Configure Pods and Containers for mentions of Docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30923]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check [Tasks > Install](https://kubernetes.io/docs/tasks/tools/) & [Tasks > Configure Pods and Containers](https://kubernetes.io/docs/tasks/configure-pod-container/) and **all their subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24
/good-first-issue
/help-wanted 

Note: Anyone taking this issue **must complete it before December 31st**.

**Comment by sftim** [comment]
- https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/ mentions
  “This page assumes you're using Docker to run Pods, and that your nodes are running the Fedora operating system. Instructions for other distributions or Kubernetes installations may vary.”
  - We need an issue to update that page.
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ has sample data that suggests the container runtime is Docker Engine
  - we should update that page, with backlog priority
- https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ clearly needs an update or even splitting into different pages. There are lots of Docker-specific details, some of which need to stay and some of which need to change.
    - We need an issue to update that page.
    - The example container registry is Docker Hub, so we might need to explain to readers what the different meanings of Docker could be.
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/ mentions image pull secrets, and might need an update.
   - We need an issue to update that page.
- https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ has a link to a Docker-specific security tuning page. 
We should omit that link or replace it.
  - We need an issue to update that page.
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-gmsa/ mentions Docker as a container runtime. 
  - We need an issue to update that page.
  - When working on that issue, we should ook for another way to convey the relevant information.
- https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/ has sample data that suggests the container runtime is Docker Engine
  - we should update that page, with backlog priority
- https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/ is about Docker Compose, not Docker Engine.
  - For the avoidance of doubt: **no work is needed** in the context of this project / umbrella issue.

**Comment by sftim** [comment]
Files to change:
```
content/en/docs/tasks/configure-pod-container/static-pod.md
content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md
content/en/docs/tasks/configure-pod-container/configure-service-account.md
content/en/docs/tasks/configure-pod-container/security-context.md
content/en/docs/tasks/configure-pod-container/configure-gmsa.md
content/en/docs/tasks/configure-pod-container/assign-memory-resource.md
content/en/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
```

**Comment by sftim** [comment]
/remove-label good-first-issue
/remove-label help

I picked this one up.

**Comment by celestehorgan** [comment]
I've broken these out into individual issues!

**Comment by sftim** [comment]
Ah, thanks Celeste.
