### ISSUE TITLE
Check Tasks > Monitoring, Logging & Debugging & Tasks > Extend Kubernetes for mentions of Docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30929]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check [Tasks > Monitoring, Logging & Debugging](https://kubernetes.io/docs/tasks/debug-application-cluster/) & [Tasks > Extend Kubernetes](https://kubernetes.io/docs/tasks/extend-kubernetes/) and **all their subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24
/good-first-issue
/help-wanted 

Note: Anyone taking this issue **must complete it before December 31st**.

**Comment by shannonxtreme** [comment]
Opened #30976 with a list of actionable pages and items :)

**Comment by shannonxtreme** [comment]
/tasks/extend-kubernetes/configure-multiple-schedulers.md also contains the following, not sure how to action it: 


Create a container image containing the kube-scheduler binary. Here is the `Dockerfile`
to build the image:

```docker
FROM busybox
ADD ./_output/local/bin/linux/amd64/kube-scheduler /usr/local/bin/kube-scheduler
```

Save the file as `Dockerfile`, build the image and push it to a registry. This example
pushes the image to
[Google Container Registry (GCR)](https://cloud.google.com/container-registry/).
For more details, please read the GCR
[documentation](https://cloud.google.com/container-registry/docs/).

```shell
docker build -t gcr.io/my-gcp-project/my-kube-scheduler:1.0 .
gcloud docker -- push gcr.io/my-gcp-project/my-kube-scheduler:1.0
```

**Comment by celestehorgan** [comment]
@shannonxtreme - the action here would be to rewrite the example and all surrounding text using another container runtime (preferably an open source one like containerd). Open an issue for just that and I'll close this off 😍

**Comment by shannonxtreme** [comment]
Thanks Celeste! I'm glad I checked 😁

**Comment by shannonxtreme** [comment]
This can be closed :)

**Comment by manavsiddharthgupta** [comment]
can any one assign me i would like to work on this
