### ISSUE TITLE
Check Tasks > Administer a Cluster for mentions of Docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30925]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check [Tasks > Administer a Cluster](https://kubernetes.io/docs/tasks/administer-cluster/) and **all its subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24
/good-first-issue
/help-wanted 

Note: Anyone taking this issue **must complete it before December 31st**.

**Comment by shannonxtreme** [comment]
A list is in existing issue #30897

**Comment by shannonxtreme** [comment]
Created #30925 with links etc :)

**Comment by celestehorgan** [comment]
Thanks for diving on this, @shannonxtreme!

**Comment by celestehorgan** [comment]
FYI - i'm retroactively assigning you to these tasks, @shannonxtreme. If you ever want to apply for reviewer or approver status, feel free to mention the work you did here, which was extremely necessary and valuable!

/assign @shannonxtreme
