### ISSUE TITLE
Check Reference > K8s Issues & Security, Reference > Setup Tools > kubeadm, & Reference > Component tools for mentions of Docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30932]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check [Kubernetes Issues & Security](https://kubernetes.io/docs/reference/issues-security/), [Reference> Setup tools > kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/) & [Reference > Component tools](https://kubernetes.io/docs/reference/command-line-tools-reference/) and **all its subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24
/good-first-issue
/help-wanted 

Note: Anyone taking this issue **must complete it before December 31st**.

**Comment by shannonxtreme** [comment]
For kubeadm, the only page that mentions docker is [Implementation details](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#preflight-checks). 

Will kubeadm be adding new preflight checks for docker runtimes post 1.24?

**Comment by shannonxtreme** [comment]
Component tools has a bunch of refs to docker, but there's nothing in Issues/Security.

**Comment by neolit123** [comment]
hello, i have a PR in flight that adjusts all kubeadm documentation about the dockershim removal:
https://github.com/kubernetes/website/pull/31309
happy to answer questions or adjust it if needed.

**Comment by celestehorgan** [comment]
@neolit123 awesome. If you don't mind, create a tracking issue for it and let me know what the issue number is!

**Comment by neolit123** [comment]
we use this tracking issue for the kubeadm changes for 1.24:
https://github.com/kubernetes/kubeadm/issues/2626
but it will also be used for 1.25.
