### ISSUE TITLE
Check Reference > kubectl, Reference > Scheduling and Reference > Other tools for mentions of Docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30933]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check [Reference > Kubectl](https://kubernetes.io/docs/reference/kubectl/), [Reference > Scheduling](https://kubernetes.io/docs/reference/scheduling/), [Reference > Other tools](https://kubernetes.io/docs/reference/tools/) and **all their subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24
/good-first-issue
/help-wanted 

Note: Anyone taking this issue **must complete it before December 31st**.

**Comment by shannonxtreme** [comment]
## References > kubectl

* docker-cli-to-kubectl should just be removed, but isn't in scope for dockershim removal I think

## References > Scheduling

Nothing

## References > Other tools

Nothing related to docker as a runtime or dockershim

**Comment by snehaljos** [comment]
hi am interested in this issue can I work on it?

**Comment by shannonxtreme** [comment]
@snehaljos you can! I've already done the analysis required by this issue but you're welcome to redo it and make sure I didn't miss something :)
