### ISSUE TITLE
Check the Kubernetes API for references to Docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30939]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check https://kubernetes.io/docs/reference/kubernetes-api/ and **all their subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24

/assign @celestehorgan

Assigning this to myself so that no one inadvertently takes it :)

**Comment by shannonxtreme** [comment]
My findings in the one-page autogenerated API reference (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/)

There might be some (or all) that don't apply to the dockershim removal. 

---

[`Container`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#container-v1-core)
File: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2294

Actions: Remove "docker" from the phrase "docker image". Maybe replace with "container image" where it makes sense, or just "image".

---

[`ContainerStatus`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#containerstatus-v1-core)
File: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2582

Actions: Make the description of `containerID` not docker-specific.

---

[`PodStatus`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#podstatus-v1-core)
File: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L3835

Actions: Remove sentence about `docker inspect` from `containerStatuses`

---

[`ContainerStateTerminated`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#containerstateterminated-v1-core)
File: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2561

Actions: Make the description of `containerId` not docker specific.

---

[`EphemeralContainer`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#ephemeralcontainer-v1-core)
File: https://github.com/kubernetes/kubernetes/blob/4c9659b1a6c526612534f75140b1e6f345d1efdb/staging/src/k8s.io/api/core/v1/types.go#L3597

Actions: Remove "docker" from the phrase "docker image". Maybe replace with "container image" where it makes sense, or just "image".

---

**Comment by sftim** [comment]
I'll pick these up
