### ISSUE TITLE
Update the kubectl reference docs for dockershim removal

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30938]
Once https://github.com/kubernetes/website/issues/30933 is complete, we need to update the kubectl docs. These docks are autogenerated from code.

The person who does this needs to be technically competent enough to both [complete the generation process](https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/) but also work in the `kubernetes/kubernetes` repository to remove any issues in code. This is not a beginner issue.

## Description

needs further scoping.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24

/assign @celestehorgan 

Assigning this to myself so that no one inadvertently takes it :)

**Comment by shannonxtreme** [comment]
The kubectl reference docs don't *seem* to have any mentions of docker or dockershim. Is there anywhere specific to look?

**Comment by nate-double-u** [comment]
I'd be happy for the help on this @chris-short 🙂

**Comment by nate-double-u** [comment]
> The kubectl reference docs don't seem to have any mentions of docker or dockershim. Is there anywhere specific to look?

@shannonxtreme, Is this where we're looking: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands?

**Comment by nate-double-u** [comment]
Instructions to generate the ref docs: https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/

**Comment by shannonxtreme** [comment]
Sorry, what I meant with my comment was that I searched the kubectl command doc and couldn't find a relevant mention of Docker or the shim to remove. I think we're ok to close this issue as being investigated @nate-double-u :)

**Comment by reylejano** [comment]
PR https://github.com/kubernetes/kubernetes/pull/109033 fixes this issue

**Comment by reylejano** [comment]
> @reylejano is this OK to close as Done?

yes, done and closing issue
