### ISSUE TITLE
Update restricted-psp.yaml removing docker support

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30949]
Ref: https://github.com/kubernetes/website/issues/30777 

The page https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies uses an example file, https://github.com/kubernetes/website/blob/main/content/en/examples/policy/restricted-psp.yaml that refers to the `docker/default` profile. 

Update the file as needed for the dockershim removal in 1.24. 

/sig security 
/milestone 1.24

**Comment by sftim** [comment]
Caution: docs for older releases may also reference this example.

**Comment by chrisnegus** [comment]
This is also identified to fix in [Issue #30949](https://github.com/kubernetes/website/issues/30949). I think this one can be closed.

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/30927 is for the page https://kubernetes.io/docs/concepts/overview/components/#container-runtime

I'm not sure I can see the overlap @chrisnegus - can you clarify?

**Comment by sftim** [comment]
> what if anything should be done with things pointing to this example in older releases?

We should make sure that when older docs branches reference an example, they refer to the example from their own release branch and not from _main_.
That may well merit its own issue, and then a fix to _main_, and then a series of backports to the previous releases.

@chris-short if you open the issue for that, let me know, I'll be happy to check it matches what I've tried to explain.

**Comment by chrisnegus** [comment]
> #30927 is for the page https://kubernetes.io/docs/concepts/overview/components/#container-runtime
> 
> I'm not sure I can see the overlap @chrisnegus - can you clarify?

I see what you mean. I didn't check that they were meant for different branches.

**Comment by chris-short** [comment]
@sftim I'm confused at this point.

**Comment by chrisnegus** [comment]
Here's what I intend to do (let me know if you disagree):
* Add a note saying that dockershim has been removed for 1.24.
* Indicate that the [Dockershim Removal FAQ](https://kubernetes.io/blog/2022/02/17/dockershim-faq/) can provide details on what that means.

**Comment by chrisnegus** [comment]
The reference to the [restricted-psp.yaml](https://github.com/kubernetes/website/blob/main/content/en/examples/policy/restricted-psp.yaml) file has been removed from the [pod security](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example-policies) page for 1.24. The page remains in the main branch so it can be referenced by other versions of the docs. Unless someone objects, I will shortly close this PR.

**Comment by sftim** [comment]
@chrisnegus this is an issue, not a PR. We should leave the issue open until a fix is merged to the _dev-1.24_ branch.

**Comment by chrisnegus** [comment]
Okay. I'll reference the PR when we have it.

**Comment by chrisnegus** [comment]
After discussing this issue at the dockershim removal meeting, it was decided to add a comment that identifies. the docker/default annotation as a policy name that is not specifically associated with Docker. When PSP is eventually removed [from Kubernetes (currently deprecated) we will probably want to remove the yaml file altogether.

PR #33219](https://github.com/kubernetes/website/pull/33219) was created to address this issue.

**Comment by chrisnegus** [comment]
[PR #33219](https://github.com/kubernetes/website/pull/33219) has merged, so I am closing this issue.
/close
