### ISSUE TITLE
Check the Configuration APIs for mentions of Docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30941]
Umbrella issue: https://github.com/kubernetes/website/issues/30771

## Description

Check https://kubernetes.io/docs/reference/config-api/ and **all its subpages** for mentions of Docker. 

This includes:
- The word "docker" in plain text
- References to or docker commands in code samples. [Most docker commands start with `docker`](https://github.com/wsargent/docker-cheat-sheet) so this shouldn't be an issue.

## How to check 

1. Pull down the repository
2. Navigate to the content **english**  content directory for the pages in question
3. Do a full-text search in an IDE or via the command line grep) in **only this directory**
4. Next, look at the pages on the live website: https://kubernetes.io/docs/concepts/overview/. Some content is pulled in dynamically and will not show up in full text searches.

## Reporting your results

When you are done: 

1. Generate a list of links to **files in the repo** and **URLs on the website** for pages which need attention. 
2. Post your list as a comment on this issue and ask that the issue be closed.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24

/assign @celestehorgan

Assigning this to myself so that no one inadvertently takes it :)

**Comment by shannonxtreme** [comment]
Page: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/#kubeadm-init-configuration-types
Source: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta2/doc.go#L154

The example YAML uses dockershim.

Actions: Replace with a fully-fledged example using a different CRI. 

---

Page: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
Source: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta3/doc.go#L176

The example YAML uses dockershim.

Actions: Clean up the YAML formatting (it's currently rendering as a bulleted list) and replace the example with one that uses a different CRI. 

---

https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/ has a mention of the docker daemon in `serializeImagePulls` but IDK if relevant.

**Comment by celestehorgan** [comment]
Updated #30942 with the above!
