### ISSUE TITLE
Update Configuration API reference docs for dockershim removal

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30942]
Once https://github.com/kubernetes/website/issues/30941 is complete, we need to update the configuration API docs. These docks are autogenerated from code.

The person who does this needs to be technically competent enough to both [complete the generation process](https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/) but also work in the `kubernetes/kubernetes` repository to remove any issues in code. This is not a beginner issue.

## Description

(thanks @shannonxtreme!) 

Page: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/#kubeadm-init-configuration-types
Source: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta2/doc.go#L154

The example YAML uses dockershim.

Actions: Replace with a fully-fledged example using a different CRI.

---

Page: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
Source: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta3/doc.go#L176

The example YAML uses dockershim.

Actions: Clean up the YAML formatting (it's currently rendering as a bulleted list) and replace the example with one that uses a different CRI.

---

https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/ has a mention of the docker daemon in serializeImagePulls but IDK if relevant.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24

/assign @celestehorgan

Assigning this to myself so that no one inadvertently takes it :)

**Comment by nate-double-u** [comment]
I'd be happy for the help on this @chris-short 🙂

**Comment by nate-double-u** [comment]
Looks like this was fixed in https://github.com/kubernetes/kubernetes/pull/107317

**Comment by tengqm** [comment]
Based on the issue report and the upstream fix, we can close the issue now.
New reference will be generated once 1.24 is out.
