### ISSUE TITLE
Update Component tools reference docs for dockershim removal

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30943]
Once https://github.com/kubernetes/website/issues/30932 is complete, we need to update the configuration API docs. These docks are autogenerated from code.

The person who does this needs to be technically competent enough to both [complete the generation process](https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/) but also work in the `kubernetes/kubernetes` repository to remove any issues in code. This is not a beginner issue.

## Description

needs further scoping.

**Comment by shannonxtreme** [comment]
The only page in Component tools that has docker mentions is [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)

The source file is here, I think: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/flags.go#L85

Already neatly grouped up too :D

**Comment by mehabhalodiya** [comment]
I would like to work on this.
But I might need some help 🙂

**Comment by nate-double-u** [comment]
Thanks for offering to help @mehabhalodiya, this is one of 4 similar issues that Rey and I will tackle. As we do these I'm happy to share the process so it's easier for folks to jump in and do this kind of docs work in future.

**Comment by nate-double-u** [comment]
It looks like https://github.com/kubernetes/kubernetes/pull/106907 has solved this issue in k/k.

Next step: pull in the update using the instructions on the [Generating Reference Documentation for kubectl Commands](https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/) page.
