### ISSUE TITLE
Update diagram on Security > Overview to remove Docker logo 

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30948]
Ref: https://github.com/kubernetes/website/issues/30777

Update the diagram on https://kubernetes.io/docs/concepts/security/overview/#the-4c-s-of-cloud-native-security  to remove the docker logo. Find another way to visually represent a container!

The file is here: https://github.com/kubernetes/website/blob/main/static/images/docs/4c.png

If possible, also convert this file to an .svg format so others can edit it in future.

**Comment by enraiha0307** [comment]
Hi, is anyone working on this issue? I'm new to open-source, thought I could help on this

**Comment by Architsharma7** [comment]
Hey!! If no one i working on this project, i can help.

**Comment by sftim** [comment]
Anyone's welcome to [sign the CLA](https://www.kubernetes.dev/docs/guide/#sign-the-cla) and open a PR that fixes this.

**Comment by RayAsh37** [comment]
I have created a PR #31338
Sorry I didn't reference it the last time.
