### ISSUE TITLE
Rewrite topics in Concepts > Storage > Volumes to remove mentions of Docker in text and code samples

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30944]
ref: https://github.com/kubernetes/website/issues/30775

After removing Dockershim, all of https://kubernetes.io/docs/concepts/storage/volumes/ needs a technical review, and the following sections need to be rewritten almost completely:

- https://kubernetes.io/docs/concepts/storage/volumes/#background
- https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
- https://kubernetes.io/docs/concepts/storage/volumes/#configuration

**Comment by sftim** [comment]
I aim to work on this. Should be able to make headway without SIG Storage input, at least at first.
/assign

**Comment by sftim** [comment]
I'm happy to [try to] answer questions about how to reword here.

**Comment by nate-double-u** [comment]
Clearing the 1.24 milestone. This can be added to subsequent milestones if needed.
/milestone clear

**Comment by sftim** [comment]
Can I check if somebody is working on this?
