### ISSUE TITLE
Update topics in Concepts > Configuration > Manage resources & containers to remove mentons of docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30946]
Ref: https://github.com/kubernetes/website/issues/30775 

Specifically these two sections need updating: 
- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run
- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#my-container-is-terminated (terminal output samples - does this still work?)

**Comment by msaini0r** [comment]
@celestehorgan I would like to work on this issue.

**Comment by celestehorgan** [comment]
@msaini0r Do you intend to work on this? If not I'd prefer to reassign it to someone who will. No hard feelings either way!

**Comment by chrisnegus** [comment]
I don't see mentions of Docker in either of the two links mentioned above. I believe they have been taken care of by [PR #29227](https://github.com/kubernetes/website/pull/29227/files). I think this can be closed.
