### ISSUE TITLE
Update the Kubernetes API reference docs for dockershim removal 

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30940]
Once https://github.com/kubernetes/website/issues/30939 is complete, we need to update the Kubernetes API docs. These docks are autogenerated from code.

The person who does this needs to be technically competent enough to both [complete the generation process](https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/) but also work in the `kubernetes/kubernetes` repository to remove any issues in code. This is not a beginner issue.

## Description

needs further scoping.

**Comment by celestehorgan** [comment]
/triage accepted
/milestone 1.24

/assign @celestehorgan

Assigning this to myself so that no one inadvertently takes it :)

**Comment by chris-short** [comment]
@nate-double-u Need any help here? I can find a coder if needed.

**Comment by nate-double-u** [comment]
I'd be happy for the help on this @chris-short 🙂

**Comment by sftim** [comment]
I'm happy to help here

**Comment by nate-double-u** [comment]
> I'm happy to help here

I may need to take you up on that @sftim. Does will https://github.com/kubernetes/kubernetes/pull/108282 solve this issue?

**Comment by sftim** [comment]
https://github.com/kubernetes/kubernetes/pull/108282 should solve this, but needs extra work - I need to figure out how to bring up a local Kubernetes dev environment.

**Comment by sftim** [comment]
There's about 9 days before the merge deadline.
