### ISSUE TITLE
Rewrite Concepts > Containers > Container Environment in light of dockershim removal

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30952]
Ref: https://github.com/kubernetes/website/issues/30773

The page https://kubernetes.io/docs/concepts/containers/container-environment/ is centered around Docker examples and needs a rewrite in light of the Dockershim removal.

/triage accepted
/milestone 1.24

**Comment by anubha-v-ardhan** [comment]
Hi, I would like to work on this but I may need a little help.

When we say "rewrite in light of the Dockershim removal", does it just means removing the Docker references on the page ( i.e removing `Those environment variables match the syntax of Docker links.` on this page) or something more is expected.

**Comment by chrisnegus** [comment]
@anubha-v-ardhan Thanks for taking this on. In my opinion, there are two issues to deal with here. The first is easy. Change "Docker image" to "container image". I believe the second instance refers to a legacy Docker feature called [links](https://docs.docker.com/network/links/). I think it is safe to just remove that sentence.

**Comment by anubha-v-ardhan** [comment]
Thankyou @chrisnegus :)
I'll make a PR by tomorrow

/assign
