### ISSUE TITLE
Remove dockershim section from Containers > Runtime Class > CRI Configuration

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#30953]
Ref: https://github.com/kubernetes/website/issues/30773

Remove the section on dockershim here: https://kubernetes.io/docs/concepts/containers/runtime-class/#cri-configuration

Do not replace or indicate with a warning. The best way to discourage users from using deprecated functionality is to remove it from the docs so they don't even know it's there :D 

/triage accepted
/milestone 1.24
/good-first-issue

**Comment by SaarthakMaini** [comment]
Hello, I would like to work on this issue. I am new to open source so can you please help me along the process? Also can you please tell me where the HTML file for this page is located so that I can make the changes?

**Comment by celestehorgan** [comment]
@shoukathmd @Midas847 @SaarthakMaini  @ajinkya359 - I need one of your four to open a PR for this or I need to assign someone who will :)

**Comment by SaarthakMaini** [comment]
@celestehorgan  I'm on it, can you please tell me where the HTML file for the same is located in the repository so that I can make the necessary changes?

**Comment by SaarthakMaini** [comment]
Hello! This is the pull request I made, #31511. I am receiving a message that it is not authorized under CLA. I am new to open source, can anyone guide me with this?

**Comment by chrisnegus** [comment]
> Hello! This is the pull request I made, #31511. I am receiving a message that it is not authorized under CLA. I am new to open source, can anyone guide me with this?

Hi @SaarthakMaini Thanks for jumping in to help. Before you can have a PR accepted you need to sign the [Kubernetes CLA](https://github.com/kubernetes/community/blob/master/CLA.md).

**Comment by Midas847** [comment]
#31520

**Comment by jihoon-seo** [comment]
The merged PR #31520 has removed the dockershim section on `dev-1.24` branch.
It seems that this issue is okay to close, and folks please check and confirm. 😊

**Comment by chrisnegus** [comment]
Both  [PR #31520](https://github.com/kubernetes/website/pull/31520/) and [PR #31525](https://github.com/kubernetes/website/pull/31525) have merged, so I’m closing this issue.
/close
