### ISSUE TITLE
Action on Docker mentions in Concepts > Services, LB, Networking

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30966]
Umbrella issue: #30771
Originating issue: #30774 (partially fixes)

---

File: /concepts/services-networking/connect-applications-service.md
URL: https://k8s.io/docs/concepts/services-networking/connect-applications-service

Line 16+ : Uses Docker to contrast against the Kubernetes model of connecting containers. 

Action: Remove the Docker contrast. Just describe how Kubernetes does container networking. 

---

/usr/local/google/home/shannduin/Desktop/Git/kubernetes/website/content/en/docs/concepts/services-networking/service.md

File: /concepts/services-networking/service.md
URL: https://k8s.io/docs/concepts/services-networking/service

Line 453-455: Mentions dockerlinks as supported environment variables.

Action: Maybe remove? 

/sig docs
/language en

**Comment by sftim** [comment]
@shannonxtreme that tidying sounds useful overall. Do we need it in connection with the removal of dockershim though?

(if so, why?)

**Comment by shannonxtreme** [comment]
@sftim TBH I was going through and looking for any mentions of Docker in the docs. That's why I'm opening these issues without triage-accepted, so that someone with more knowledge (like you) can advise on whether it's applicable. 

Maybe I can retitle to a cleanup issue and remove from the dockershim project?

**Comment by sftim** [comment]
> retitle to a cleanup issue

SGTM

**Comment by yashodhanmohan** [comment]
@shannonxtreme 
Can I take this up as my first contribution? If yes, should I assign it to myself?

**Comment by shannonxtreme** [comment]
> @shannonxtreme 
> Can I take this up as my first contribution? If yes, should I assign it to myself?

Heck yes! Go for it. I'm happy to help with any questions you might have, and to review this. 

/assign @yashodhanmohan

**Comment by yashodhanmohan** [comment]
Hey @shannonxtreme  I've raised a PR for this change. For the change regarding dockerlinks, I tried to pick an appropriate replacement but I'm open to any other better suggestions. Let me know any feedback or if any content seems disconnected because of the removal.

**Comment by yashodhanmohan** [comment]
The related PR has been merged so this can be closed I believe. :+1:
