### ISSUE TITLE
Action on Docker mentions in Concepts > Workloads

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30965]
Umbrella issue: #30771 
Originating issue: #30774 (partially fixes)

File: /concepts/workloads/controllers/daemonset.md
URL: https://k8s.io/docs/concepts/workloads/controllers/daemonset

Line 207 contains `(e.g. start directly via Docker).`

The code sample includes docker mentions. 

Action: remove the phrase. Add warning about code samples potentially breaking. Test code samples on a cluster with a different runtime and on a cluster with cri-dockerd and Docker. 

---

File: /concepts/workloads/controllers/deployment.md
URL: https://k8s.io/docs/concepts/workloads/controllers/deployment

Line 65 contains Docker Hub as an example.

Action: keep, since it's an example image.

---

File: /concepts/workloads/controllers/replicaset.md
URL: https://k8s.io/docs/concepts/workloads/controllers/replicaset

Last sentence in line 392 contains Docker as an example.

Action: Rephrase to "some agent on the node, such as the kubelet"

---

File: /concepts/workloads/controllers/replicationcontroller.md
URL: https://k8s.io/docs/concepts/workloads/controllers/replicationcontroller

Line 142 and 273 have Docker as an example. 

Action: 

* Line 142: remove "or Docker".
* Line 273: rephrase to "some agent on the node, such as the kubelet."
---

File: /concepts/workloads/pods/_index.md
URL: https://k8s.io/docs/concepts/workloads/pods/

Line 35 - 48: Uses Docker to describe what Pods are.

Action: reword the overview of a Pod to describe it without a reliance on a third party. Use content from our Glossary. 

---

File: /concepts/workloads/pods/init-containers.md
URL: https://k8s.io/docs/concepts/workloads/pods/init-containers

Output in line 189 and 190 seem to use docker as the runtime.

Action: not sure. Replace example output with the output while using containerd or cri-o?

---

File: /concepts/workloads/pods/pod-lifecycle.md
URL: https://k8s.io/docs/concepts/workloads/pods/pod-lifecycle

Line 208 uses docker as the container ID example

Action: keep as-is. 

/sig docs
/language en
/help-wanted

**Comment by enraiha0307** [comment]
Hi, Can I work on this?

**Comment by shannonxtreme** [comment]
@enraiha0307 yup, go for it! If you run into issues or have questions, feel free to ask here or on Slack :) 

/assign @enraiha0307

**Comment by enraiha0307** [comment]
Hi, good evening, I wanted to clarify something
in
```
File: /concepts/workloads/controllers/daemonset.md
URL: https://k8s.io/docs/concepts/workloads/controllers/daemonset

Line 207 contains (e.g. start directly via Docker).

The code sample includes docker mentions.

Action: remove the phrase. Add warning about code samples potentially breaking. Test code samples on a cluster with a different runtime and on a cluster with cri-dockerd and Docker.
```
I have to implement the daemonset.yaml code using cri-dockerd and Docker right? Different runtime means we have to use  containerd, runC or CRI-O right??

**Comment by sftim** [comment]
@enraiha0307 that's my understanding. If you use a container runtime that's not docker and also not one of the ones you listed, that's also fine.

**Comment by chris-short** [comment]
[**@enraiha0307**](https://github.com/enraiha0307) Need any help here?

**Comment by chris-short** [comment]
**@enraiha0307 Need any help here?**

**Comment by mangoGoForward** [comment]
Hi @enraiha0307,  are you working on this issue already? If not I'd like to tackle this issue :)

**Comment by enraiha0307** [comment]
@mangoGoForward Yeah I'm working I have corrected the simple text changes but I'm having trouble running containerd on my system for replacing docker examples as mentioned in the issue, you can work on this if you want 😀 👍

**Comment by mehabhalodiya** [comment]
> I'm having trouble running containerd on my system for replacing docker examples as mentioned in the issue

@enraiha0307 kindly unassign yourself from this issue, so that other people can take it up. Thanks!

@mangoGoForward Are you working on this?

**Comment by enraiha0307** [comment]
Sorry, I didn't know I had to unassign it by myself. I thought only a contributor will have this authority. Now I know and have unassigned myself.

**Comment by rishi8055** [comment]
@mehabhalodiya If no one is working on this issue can you assign this issue to me .

**Comment by mehabhalodiya** [comment]
Sure @rishi8055 you can go ahead.
Anytime, you can assign yourself by commenting `/assign` on particular issue you want to work.

For now, I am assigning this to you.
/assign @rishi8055

**Comment by rishi8055** [comment]
Thank you Meha for assigning me for this issue . Let me know you that i am
new in this open source contribution journey and indeed  so much of
guidance to move forward it will be very helpful if you can do this for me
in anyway.

**Comment by shannonxtreme** [comment]
Hi @rishi8055 did you need any help with this issue to move it along?

**Comment by nate-double-u** [comment]
Clearing the 1.24 milestone. This can be added to subsequent milestones if needed.
/milestone clear

**Comment by sftim** [comment]
It's been a while since the last update. PRs to address this issue are welcome (by any contributor).
/priority important-longterm

**Comment by mehabhalodiya** [comment]
@rishi8055 I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on it! Thank you 🙂 
/unassign @rishi8055

**Comment by 889-dj** [comment]
hi the context in the 5th issue from the top is quite unclear to me
what I understand is that the I have to remove reference of docker with pods and redefine it as below plz help me with this 

While Kubernetes supports more
{{< glossary_tooltip text="container runtimes" term_id="container-runtime" >}}
than just Docker, [Docker](https://www.docker.com/) is the most commonly known
runtime.
{{< /note >}}

The Pod is the smallest and simplest Kubernetes object which is a set of Linux namespaces, cgroups, and
potentially other facets of isolation . Within a Pod , the individual applications may have
further sub-isolations applied.

A Pod represents a set of running [containers](https://kubernetes.io/docs/concepts/containers/) on your cluster. [[-]](javascript:void(0))
A Pod is typically set up to run a single primary container. It can also run optional sidecar containers that add supplementary features like logging.

**Comment by sftim** [comment]
@889-dj what I suggest you do is open a PR to work on that and show your initial thinking, and also write a PR description that explains how you approached the challenge. Then, a reviewer can comment on both the intent and the changes you've made.

A word of warning, though. This particular sub-task calls for a strong ability to explain a technical concept. If you're not comfortable with that, it's OK to pick a different subtask from the list that looks easier to tackle.

**Comment by 889-dj** [comment]
sure @sftim thanks for the suggestion

**Comment by NitishKumar06** [comment]
Is this issue still needed to be worked upon?

**Comment by mehabhalodiya** [comment]
Yes @NitishKumar06, you can pick it up if you want to work on 🙂

**Comment by rogue-gamer-ryt** [comment]
Hey @NitishKumar06 let me know if you are not working on this, I can pick it up :)

**Comment by NitishKumar06** [comment]
@rogue-gamer-ryt Go ahead and work on this issue. I'd love to see what changes you bring:)

**Comment by BenTheElder** [comment]
>  Add warning about code samples potentially breaking. Test code samples on a cluster with a different runtime and on a cluster with cri-dockerd and Docker.

At this point we're pretty unlikely to be testing things on docker as a runtime given it hasn't been supported for multiple releases (unless using cri-dockerd, which may have it's own breakage).

Also, FWIW, generally workloads should not be container runtime sensitive, though some unusual edge cases exist mostly which are also technically configurable etc. and can be different even using the same runtime.
