### ISSUE TITLE
Action on Docker mentions in Tasks > Administer Cluster

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30970]
Umbrella issue: #30771 
Fixes: #30925 

---

File: /tasks/administer-cluster/kubelet-in-userns.md
URL: https://k8s.io/docs/tasks/administer-cluster/kubelet-in-userns

The page talks about rootless Docker and Podman. No mentions of the docker runtime or dockershim.

Action: No action needed. 

---

File: /tasks/administer-cluster/reserve-compute-resources.md
URL: https://k8s.io/docs/tasks/administer-cluster/reserve-compute-resources

Line 70 mentions the `systemd` cgroup driver from the `docker` runtime. 

Action: Change to a different runtime such as CRI-O or containerd.

---

File: /tasks/administer-cluster/kubeadm/adding-windows-nodes.md
URL: https://k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes

Line 149-174: Installation instructions present for Docker EE

Action: Remove the Docker EE tab. Keep containerd. 

---

File: /tasks/administer-cluster/kubeadm/adding-windows-nodes.md
URL: https://k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes

Line 149-174: Installation instructions present for Docker EE

Action: Remove the Docker EE tab. Keep containerd. 

/sig docs
/language en

**Comment by championshuttler** [comment]
@shannonxtreme Can i work on it?

**Comment by jihoon-seo** [comment]
@chrisnegus Please note that
the TODO with `/tasks/administer-cluster/kubeadm/adding-windows-nodes.md` is already done in the PR #31309,
so it seems that all you have to do regarding this issue is to modify `/tasks/administer-cluster/reserve-compute-resources.md`. 😊

**Comment by neolit123** [comment]
The Docker installatiin steps (e.g. tabs) should not be removed. Instead we should talk about the cri-dockerd project. See the discussion in https://github.com/kubernetes/website/pull/31309

**Comment by chrisnegus** [comment]
@jihoon-seo and @neolit123, thanks for tips. I'm just getting started on it.

**Comment by chrisnegus** [comment]
@jihoon-seo I just filed PR #31546. From what you said, I believe that all the issues listed are now being addressed.

**Comment by jihoon-seo** [comment]
It seems that it is okay to close this issue, folks please confirm 😊

**Comment by shannonxtreme** [comment]
Closing as all issues are fixed either now or in dev-1.24

/close
