### ISSUE TITLE
Action on Docker mentions in Tasks > Monitoring Logging and Debugging

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30976]
Umbrella issue #30771 
Fixes issue #30929 
---

File: /tasks/debug-application-cluster/resource-usage-monitoring.md
URL: https://k8s.io/docs/tasks/debug-application-cluster/resource-usage-monitoring

Line 44 mentions how the kubelet pulls info for Docker integration for metrics-server.

Action: Review to see if it works as intended in a world without dockershim.

## Done

~~File: /tasks/debug-application-cluster/crictl.md~~
~~URL: https://k8s.io/docs/tasks/debug-application-cluster/crictl~~

~~The entire page mentions and implements dockershim. Also includes guides for mapping docker cli commands to crictl.~~

~~Action: Rewrite the entire page without dockershim and docker CLI~~

---

~~File: /tasks/debug-application-cluster/debug-application.md~~
~~URL: https://k8s.io/docs/tasks/debug-application-cluster/debug-application~~

~~Line 61 mentions doing `docker pull <image>`.~~

~~Action: Provide an alternative or remove the line.~~

---

~~File: /tasks/debug-application-cluster/debug-pod-replication-controller.md~~
~~URL: https://k8s.io/docs/tasks/debug-application-cluster/debug-pod-replication-controller~~

~~Line 89 mentions doing `docker pull <image>`. ~~

~~Action: Provide an alternative or remove the line.~~

---

File: /tasks/debug-application-cluster/debug-application-introspection.md
URL: https://k8s.io/docs/tasks/debug-application-cluster/debug-application-introspection

Line 106 and other output examples use docker as the runtime. 

Action: Reproduce the output samples on a cluster not running Docker and update the samples. 

---
kubernetes/website/content/en/docs/tasks/debug-application-cluster/troubleshooting.md
File: /tasks/debug-application-cluster/troubleshooting.md
URL: https://k8s.io/docs/tasks/debug-application-cluster/troubleshooting

Line 103 mentions specifying the Docker version when filing a Github issue. 

Action: Say instead to mention the runtime and version being used.

---

File: /tasks/debug-application-cluster/debug-service.md
URL: https://k8s.io/docs/tasks/debug-application-cluster/debug-service

Line 679 has `--runtime-cgroups=/docker-daemon`. 

Action: Reproduce using a different runtime and update.

/sig docs
/language en

**Comment by sftim** [comment]
I'm tempted to move https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/#mapping-from-docker-cli-to-crictl to a new page in the reference section, that we insta-deprecate (removal in, say, v1.27).

How does that sound?

**Comment by shannonxtreme** [comment]
Agreed @sftim! 

/assign

**Comment by chrisnegus** [comment]
@shannonxtreme Are you covering everything listed in this issue? If so, I'd like to move this from backlog to in-flight in the dockershim project board, so nobody else tries to work on this.

**Comment by shannonxtreme** [comment]
@chrisnegus yes, thank you!

**Comment by chris-short** [comment]
Is everything listed in the first entry done? What's left, if anything?

**Comment by chris-short** [comment]
cc @shannonxtreme

**Comment by shannonxtreme** [comment]
> Is everything listed in the first entry done? What's left, if anything?

Yes it is, I'm waiting for my PR in kubernetes/cri-tools to get merged before I close that one :)

**Comment by shannonxtreme** [comment]
> File: /tasks/debug-application-cluster/debug-service.md
URL: https://k8s.io/docs/tasks/debug-application-cluster/debug-service
> Line 679 has --runtime-cgroups=/docker-daemon.
> Action: Reproduce using a different runtime and update.

I don't think this needs to change tbh, since it's a very generic example.

**Comment by chrisnegus** [comment]
It looks like the IPv6 address has been fixed. Looks ready to merge to me.
/lgtm

**Comment by nate-double-u** [comment]
Dockershim removal work is ongoing, clearing the 1.24 milestone. This can be added to subsequent milestones if needed.
/milestone clear
