### ISSUE TITLE
Action on Docker mentions in Tasks > Networking

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30977]
Umbrella issue #30771 
Fixes #30930 

File: /tasks/network/customize-hosts-file-for-pods.md
URL: https://k8s.io/docs/tasks/network/customize-hosts-file-for-pods

Line 121 mentions that the kubelet manages the hosts file to prevent Docker from modifying it. 

Action: Update the page to remove sections that are made irrelevant by the dockershim removal. 

/sig docs
/language en

**Comment by sftim** [comment]
For this one, we might still want to explain the historical context for hosts file management. Otherwise: are we telling the reader that their node does a thing but not why that happens?

**Comment by shannonxtreme** [comment]
I was thinking more just revise the sentence to say "The kubelet manages the hosts file for each container of the Pod to prevent the container runtime from modifying the file after the containers have already been started." (if that is accurate)

**Comment by PurneswarPrasad** [comment]
Hey, I went through the doc and think that the mention of Docker as some previous version of it which modified the hosts file. And now since Docker support is being dropped, for the time being, @shannonxtreme 's revised sentence seems good.

**Comment by shannonxtreme** [comment]
This issue was fixed in #31398
