### ISSUE TITLE
Clean up Tasks > Inject Data into Applications > Define a Command and Arguments

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30971]
URL: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes
File: /tasks/inject-data-application/define-command-argument-container.md

Remove the entire Notes section. Clean up the page so that there's no mention of a *specific* runtime. 

/sig docs
/language en

**Comment by sftim** [comment]
I would remove the entire https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes section.

Docker is far from the only alternative to Kubernetes. If someone wanted to, we could accept a blog article that compares Docker, Kubernetes, Nomad, etc for how you specify these things. But it's fine if that blog is never submitted.
/triage accepted

**Comment by sftim** [comment]
@shannonxtreme to me this is more about comparing Docker Swarm to Kubernetes. I think it's a good bit of tidying but I'm not sure it's needed for the dockershim removal work.
