### ISSUE TITLE
Explain how to tell dockershim apart from cri-dockerd

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#30974]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use/ to explain how to tell apart two cases that involve Docker Engine as a container runtime
- Docker Engine + dockershim + kubelet
- Docker Engine + cri-dockerd + kubelet

The second case, using 2 third-party components, is not affected by the dockership deprecation. As a project we are not telling cri-dockerd users to migrate away.

**Why is this needed**
If someone is using cri-dockerd with Docker Engine, they don't need to take action relating to the deprecation of dockershim. That person might visit https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use/  and then be confused about whether they still need to take action.

**Comments**
/sig node
/priority important-soon
/language en
/kind feature

Part of https://github.com/kubernetes/kubernetes/issues/104878

**Comment by sftim** [comment]
Very relevant to #30972

**Comment by afbjorklund** [comment]
It really should say `# For docker`, rather than `# For dockershim`

It doesn't say "for cri-containerd" or "for containerd with cri plugin", either.

**Comment by afbjorklund** [comment]
Neither `kubectl` nor `crictl` seem to have a way to tell the CRI in use ?

They only describe the container runtime, and in some cases the API version...

**Comment by afbjorklund** [comment]
Looks like crictl is only documented under "debugging", even if now required ?

https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/

**Comment by afbjorklund** [comment]
> If someone is using cri-dockerd with Docker Engine, they don't need to take action relating to the deprecation of dockershim.

I think it would be more interesting to look at users using the "docker" container runtime, to see if they have changed CRI.

They would need to change their CRI, from dockershim.sock to cri-dockerd.sock. Including kubelet and crictl configuration ?

But they don't need to relearn everything or transfer images, etc.

**Comment by afbjorklund** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use/

This should say "docker" (which the command _does_), and not `# For dockershim` (not really relevant)

**Comment by sftim** [comment]
> it should be divided into two:
> 1. how to change dockershim to cri-dockerd
> 1. how to change docker to containerd

That seems fair enough. We can also add instructions for switching your node from Docker Engine to something else, if we want.

**Comment by sftim** [comment]
_where feasible_ we prefer to link to external docs that are specific to external tools, rather than document them ourselves.
This case seems like a reasonable case for doing the documenting ourselves.

**Comment by afbjorklund** [comment]
Unfortunately it also assumes that there _are_ any good external docs, which doesn't seem to be the case for either CRI.

**Comment by afbjorklund** [comment]
Visual summary:

![dockershim-to-cri-dockerd](https://user-images.githubusercontent.com/10364051/152586755-ba6879d6-0e23-43ca-92a0-a7b9df91d235.png)

The top diagram would be when running Kubernetes 1.23, and the bottom diagram would be when running Kubernetes 1.24

The docker installation (`docker.service`) stays the same, the only introduction is the new cri-dockerd (`cri-docker.service`)

**Comment by shannonxtreme** [comment]
@afbjorklund @sftim 

From what I understand, [Find out what container runtime is used on a node](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use/) needs to add info about how cri-dockerd users aren't affected, and how to check the CRI socket to tell if you do use cri-dockerd. (how? if crictl is not installed, is there another way?)

Also, https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/ needs more guidance for migrating from dockershim to cri-dockerd (in addition to migrating from Docker Engine to containerd). Is this out of scope for this issue? 

/assign

**Comment by sftim** [comment]
> more guidance for migrating from dockershim to cri-dockerd &hellip; is this out of scope for this issue?

I'd say yes: it _is_ out of scope for this issue. It's fine to track a separate issue to add docs for that.

**Comment by afbjorklund** [comment]
> if crictl is not installed, is there another way?

I believe that `crictl` is mandatory, without dockershim

**Comment by sftim** [comment]
There is a [`Version` request](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto#L35). If you talk CRI to some unidentified CRI socket and the thing at the other end identifies itself as Docker Engine, odds on you're talking to `cri-dockerd` or `dockershim`.

You can narrow it down by running `lsof /path/to/unknown/socket`. That's likely to give you either the PID and name of the daemon involved, or possibly point to a socket-activation tool such as systemd. If it is systemd owning the socket, you'd grep through systemd config to find what's configured to listen on that socket.

**Comment by chris-short** [comment]
@sftim Is this essentially an umbrella issue for #32131 and #31132 now?

**Comment by sftim** [comment]
It's all done!
