### ISSUE TITLE
Action on Docker mentions in Tasks > Configure Multiple Schedulers

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#30992]
Umbrella issue #30771 
Related issue #30929

Page: https://k8s.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers
File: /tasks/extend-kubernetes/configure-multiple-schedulers.md

Rewrite the example and surrounding content on this page using an open-source runtime like containerd.

/triage accepted
/sig docs
/language en

**Comment by shannonxtreme** [comment]
I'm not sure that this page needs to be changed in the context of the dockershim removal, since the task is about packaging kube-scheduler into an image to use as a second scheduler. If not needed, we can close this.

**Comment by celestehorgan** [comment]
@shannonxtreme I recommend filing a separate issue for what you mentioned above, but I don't think it needs to change for dockershim.
