### ISSUE TITLE
[Dockershim removal] move content of monitoring and security agents document to the markdown

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#30999]
/sig node

We discussed that moving content of https://docs.google.com/document/d/1ZFi4uKit63ga5sxEiZblfb-c23lFhvy6RXVPikS8wf0/edit# to https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents/ would increase discoverability of the content. We need to make sure we only collect links to vendor docs, not specific instructions.

**Comment by sftim** [comment]
BTW, that new page needs to use the `{{% thirdparty-content %}}` shortcode.

**Comment by championshuttler** [comment]
can i work on it @sftim

**Comment by sftim** [comment]
I think we could postpone this 'til after the v1.24 release. Thoughts?

**Comment by chrisnegus** [comment]
The content shown in https://docs.google.com/document/d/1ZFi4uKit63ga5sxEiZblfb-c23lFhvy6RXVPikS8wf0/edit# was added to the docs in [PR #31469](https://github.com/kubernetes/website/pull/31469) and has been merged. I'm closing this issue.
/close

**Comment by SergeyKanzhelev** [comment]
I thought the idea was to move specific agents information as well? I found that it is way less discoverable with the google doc link

/reopen

**Comment by nate-double-u** [comment]
Dockershim removal work continues. Clearing milestone, this can be added to subsequent milestones if needed.
/milestone clear
