### ISSUE TITLE
Can't use curl on Minikube with the NGINX Ingress Controller

### ISSUE THREAD

**Issue by gpierard** [kubernetes/website#30996]
hey all, I'm trying to follow the basic ingress [tutorial](https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) using minikube, but on both windows 10 and Mac OS I get an error trying to `curl $(minikube ip)` .
This is the result of my kubectl get ingress , as you can see I only have localhost instead of an IPV4 address.
```
kubectl get ingress
NAME              CLASS   HOSTS              ADDRESS     PORTS   AGE
example-ingress   nginx   hello-world.info   localhost   80      8m41s 
```
All commands to reproduce:
```
minikube addons enable ingress
kubectl create deployment web --image=gcr.io/google-samples/hello-app:1.0
kubectl expose deployment web --type=NodePort --port=8080
kubectl apply -f https://k8s.io/examples/service/networking/example-ingress.yaml
curl $(minikube ip)
curl: (7) Failed to connect to 192.168.49.2 port 80: Timed out
```
Thanks for any help

**Comment by jihoon-seo** [comment]
Please see:
- How to install CURL on Windows 11/10 https://www.thewindowsclub.com/how-to-install-curl-on-windows-10
- Install cURL Command on Windows 10 https://www.configserverfirewall.com/windows-10/install-curl-windows-10/
- Install curl on Mac OSX https://macappstore.org/curl/
- Learn how to install & run cURL on Windows/MacOSX/Linux https://help.ubidots.com/en/articles/2165289-learn-how-to-install-run-curl-on-windows-macosx-linux

/kind support
