### ISSUE TITLE
Managing Resources for Containers

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#30994]
Read about project quotas in XFS in https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#what-s-next
https://xfs.org/docs/xfsdocs-xml-dev/XFS_User_Guide/tmp/en-US/html/xfs-quotas.html the link is 404

I cannot find a page named xfs-quotas in xfs.org.

I only find https://xfs.org/index.php/XFS_FAQ#Q:_Quota:_What.27s_project_quota.3F .

**Comment by Babapool** [comment]
The issue is fixed by PR #31701. I believe we can close this issue. Thanks.
