### ISSUE TITLE
Doc page on headless services

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#31015]
**This is a Feature Request**
 
I think we need a doc page on how to use headless services.  I wrote one up on my personal blog https://jayunit100.blogspot.com/2021/12/looking-at-headless-services-coredns.html if someone wants to copy/format it over

**What would you like to be added**

A doc page on headless services and DNS

**Why is this needed**

Alot of apps use a headless service to directly build quorum between pods (rabbit/minio/...) and alot of folks have filed issues about this and how to do it/optimize it/etc...

https://github.com/kubernetes/kubernetes/issues/92559

https://blog.rabbitmq.com/posts/2020/08/deploying-rabbitmq-to-kubernetes-whats-involved/

https://groups.google.com/g/rabbitmq-users/c/alEUctR97lo

https://github.com/minio/operator/issues/732

etc

**Comment by sftim** [comment]
@jayunit100 can you confirm that the content on that blog is licensed to Kubernetes under the CLA? We'll need that in order to accept that contribution, even as a draft.
/sig network

**Comment by sftim** [comment]
For the _idea_ of improving docs around headless services: definitely accepted.
