### ISSUE TITLE
Many Api docs are 404

### ISSUE THREAD

**Issue by grodrigues3** [kubernetes/website#3101]
Kubernetes rest api docs is missing 

**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

https://kubernetes.io/docs/api-reference/apps/v1beta1/operations/
is missing

cc @puyangsky

**Comment by ahmetb** [comment]
We're aware of some 404s in k8s.io/docs/reference page, this is one of them.

> 
![image](https://cloud.githubusercontent.com/assets/159209/24522500/9dc71700-1544-11e7-845d-43ac57e8bc4d.png)

cc: @chenopis

**Comment by grodrigues3** [comment]
if there's another issue open, feel free to close and dedupe

**Comment by ahmetb** [comment]
Let's keep this, we can edit the title. Many api docs are 404 at this point.

**Comment by grodrigues3** [comment]
@chenopis updates here?  can we close this?

**Comment by chenopis** [comment]
@grodrigues3 Yes, we've moved around some docs, cleaned up the broken links, and added server-side redirects, so I'm going to close this.
