### ISSUE TITLE
[hi] Localize docs/contribute/_index.md to Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#31012]
**This is a Feature Request**

**What would you like to be added**

We need to localize [docs/contribute/_index.md](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/_index.md) to Hindi.

**Comments**

The current working branch for `hi` localization work is `dev-1.22-hi.1`. Please make sure to open a PR against `dev-1.22-hi.1`.
For more info see Hindi localization progress tracking issue #29353 

/language hi
/kind feature

**Comment by Nawaz027** [comment]
Hey @anubha-v-ardhan , I am interested in localizing, can you please assign this issue to me?

**Comment by anubha-v-ardhan** [comment]
/assign @Nawaz027 
Thank you :)

**Comment by anubha-v-ardhan** [comment]
/close
Resolved by #31162
