### ISSUE TITLE
[hi] Update data/i18n/hi/hi.toml to include missing strings

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#31013]
**This is a Bug Report**

**Problem:**
The current [data/i18n/hi/hi.toml](https://github.com/kubernetes/website/blob/dev-1.22-hi.1/data/i18n/hi/hi.toml) on branch `dev-1.22-hi.1` is not up to date with the English version.

**Proposed Solution:**
Compare [en.toml](https://github.com/kubernetes/website/blob/dev-1.22-hi.1/data/i18n/en/en.toml) with [hi.toml](https://github.com/kubernetes/website/blob/dev-1.22-hi.1/data/i18n/hi/hi.toml) and add the missing strings (19 in number)

**Page to Update:**
https://github.com/kubernetes/website/blob/dev-1.22-hi.1/data/i18n/hi/hi.toml

**Note:**
The current working branch for `hi` localization work is `dev-1.22-hi.1`. Please make sure to open a PR against `dev-1.22-hi.1`.
For more info see Hindi localization progress tracking issue #29353

/language hi
/kind bug

**Comment by Babapool** [comment]
Hi I would like to work on this issue.

**Comment by anubha-v-ardhan** [comment]
/close
resolved by #31072
