### ISSUE TITLE
Add releases page to minimum required content

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31010]
**This is a Feature Request**

**What would you like to be added**
I propose that https://kubernetes.io/docs/contribute/localization/#minimum-required-content should include https://k8s.io/releases/

**Why is this needed**
The releases page (just the front page, and not requiring any pages within it) is a key document to make available to readers. The shortcode this page uses already has localization support.

I think we should localize this page.

**Comments**
If we accept this issue, we should also open one issue per downstream localization, about making sure that that localization team works on and localizes `/releases` for their target localization. Link each of those issues back to this one, which then becomes an umbrella issue.

**Comment by sftim** [comment]
PS. The `pl` localization is [ahead of the curve](https://kubernetes.io/pl/releases/) on this one, and shows an example of what success looks like.

_There's one paragraph in the shortcode that doesn't yet localize; if you look at the rendered page you'll see that it's marked as English._ Fixing that would be a separate issue.

**Comment by jayesh-srivastava** [comment]
Hi @sftim, if the issue is still open, can I work on it?

**Comment by anubha-v-ardhan** [comment]
/assign @jayesh-srivastava 
Sure

**Comment by sftim** [comment]
@jayesh-srivastava do you have any questions about how to get started? You're very welcome to open a pull request.

**Comment by jayesh-srivastava** [comment]
@sftim Hey I made the PR, if you can review it that would be great!
