### ISSUE TITLE
Explain requirement for YUM basearch in kubeadm install docs

### ISSUE THREAD

**Issue by strikingraghu** [kubernetes/website#31038]
### What happened?

While installing K8s on CentOS VM, below steps didn't work seamlessly:

Site Link - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
----------------------------------------------------------------------------------------------------------------------------
Code Section:

cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

----------------------------------------------------------------------------------------------------------------------------

I see an issue in the baseurl getting 404 error, which needs to be adjusted/modified accordingly

Solution:
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch [DOESN'T WORK]
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 [WORKS WELL]

Can someone validate this and update the documentation?

### What did you expect to happen?

I see an issue in the baseurl getting 404 error, which needs to be adjusted/modified accordingly

### How can we reproduce it (as minimally and precisely as possible)?

Installing kubeadm, kubelet and kubectl via below provided packages link:

----------------------------------------------------------------------------------------------------------------------------
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

# Set SELinux in permissive mode (effectively disabling it)
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
sudo systemctl enable --now kubelet
----------------------------------------------------------------------------------------------------------------------------

In the above mentioned code, this line would create a problem.
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch

### Kubernetes version

<details>

```console
$ kubectl version
Latest Version Applicable
```

</details>

### Cloud provider

<details>
On-Prem Installation
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
CentOS-8
# paste output here
$ uname -a
# paste output here
Linux x86_64
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Containerd.io
But the CRI is not relevant for this problem
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
Its a package manager issue.

> Hence, I am requesting to make it simpler to new users to download and install K8s without much issues.

Your yum configuration seems to be missing the basearch setting. It happens on some distros and architectures.

We can mention in the docs to manually set the setting if its missing. I don't see what else can be done here.

**Comment by strikingraghu** [comment]
> Its a package manager issue.
> 
> > Hence, I am requesting to make it simpler to new users to download and install K8s without much issues.
> 
> Your yum configuration seems to be missing the basearch setting. It happens on some distros and architectures.
> 
> We can mention in the docs to manually set the setting if its missing. I don't see what else can be done here.

Thanks @neolit123. Good to get it updated in doc and closing this issue.

**Comment by sftim** [comment]
/sig docs
/sig cluster-lifecycle
/kind feature
/priority backlog
/triage accepted

/retitle Explain requirement for YUM basearch in kubeadm install docs

**Comment by strikingraghu** [comment]
> /sig docs /sig cluster-lifecycle /kind feature /priority backlog /triage accepted
> 
> /retitle Explain requirement for YUM basearch in kubeadm install docs

Thanks for acceptance!

**Comment by chrisnegus** [comment]
The URL should just work as it is. If for some reason it doesn't, and you want to tell the user how to get it for their specific machine, add a note to show something like this:

`echo https://packages.cloud.google.com/yum/repos/kubernetes-el7-$(uname -m)`
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

Use the output to replace the URL in the example. It looks like supported architectures are x86_64, aarch64, armhfp, ppc64le, s390xx86_64, aarch64, armhfp, ppc64le, and s390x.

**Comment by chrisnegus** [comment]
I'll take this one on.
/assign

**Comment by neolit123** [comment]
https://github.com/kubernetes/website/pull/31917 merged, thanks
/close
