### ISSUE TITLE
The description of the Summary API Source section does not match the KEP and code implementation

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/website#31035]
**Problem:**
When I was reading this [page](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#summary-api-source), I felt very confused.
```
The Kubelet gathers stats at node, volume, pod and container level, and omits them in the Summary API for consumers to read.
```
The meaning of this sentence is to explain that the node, volume, pod and container level information cannot be obtained from the summary API?

But I read  [cAdvisor-less, CRI-full Container and Pod Stats KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2371-cri-pod-container-stats/README.md) and code implementation:
```
enhance the CRI API with enough metrics to be able to supplement the pod and container fields in the summary API directly from CRI.
```
My understanding is:
The node, volume, pod and container level information can be obtained from the summary API.
So is `omits them in the Summary API for consumers to read` an expression error? 

**Proposed Solution:**
Enhanced description to avoid ambiguity or misrepresentation.

Suggested modification:
```
The Kubelet gathers stats at node, volume, pod and container level, and outputs their statistics in the Summary API for consumers to read.
```

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/

The English version of the original PR: https://github.com/kubernetes/website/pull/30535

/assign @haircommander

**Comment by chrismetz09** [comment]
Hi @mengjiao-liu, agree it needs fixing per https://github.com/kubernetes/website/issues/27840. I have a bunch of notes, please add your thoughts so we can clarify this matter. It is confusing.

**Comment by sftim** [comment]
/language en
The best place to add more notes is issue #27840

**Comment by mengjiao-liu** [comment]
Thanks for the reminder, I've added comments to #27840

**Comment by haircommander** [comment]
> The Kubelet gathers stats at node, volume, pod and container level, and omits them in the Summary API for consumers to read.

it sounds like the original author intended `emits` instead. Outputs definitely works too.

**Comment by mengjiao-liu** [comment]
> it sounds like the original author intended emits instead. Outputs definitely works too.

Use `emits` as the word makes sense, thanks for the reply!
