### ISSUE TITLE
Update layout for blog pages so that a warning is displayed on posts 1+ years old

### ISSUE THREAD

**Issue by chalin** [kubernetes/website#31043]
From @mrbobbytables's [comment on Slack](https://kubernetes.slack.com/archives/C02PZMA3R6E/p1639511731062200?thread_ts=1639511364.059400&cid=C02PZMA3R6E):

> [add] a general blog warning msg - we do not go back and update anything more than a year old and the content may not reflect reality. ... like a template that checks the date, if more than a 1yr old add a preamble at the top

The comment was made in the context of the Dockershim-removal effort. I'm opening this PR following discussions with @celestehorgan.

The warning, which would appear only on posts that are >= 1 year old, might read something like this:

> **Warning**: this blog post may contain **outdated information**, since posts that are more than a year old (like this one) are no longer updated.

Comments are welcome.

/cc @nate-double-u @sftim

**Comment by chalin** [comment]
I'm glad to work on this, though it might not happen until January.

**Comment by sftim** [comment]
Good idea
/area web-development

I suggest borrowing the _styling_ from [`pageinfo`](https://www.docsy.dev/docs/adding-content/shortcodes/#pageinfo).

**Comment by chalin** [comment]
/assign

I don't know if the command above will work. If it doesn't @sftim or @nate-double-u can you assign this to me? I've started working on this now.

**Comment by nate-double-u** [comment]
Thanks @chalin!
(and the `/assign` looks to have worked 🙂)
