### ISSUE TITLE
[ko] Translate tasks/debug-application-cluster/debug-cluster.md

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#31062]
This is a Feature Request
Translate [/content/en/docs/tasks/debug-application-cluster/debug-cluster.md] in Korean

What would you like to be added
Translate [/content/ko/docs/tasks/debug-application-cluster/debug-cluster.md] in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #31155
- #31637

/close
