### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateful-application/basic-stateful-set/

### ISSUE THREAD

**Issue by balrajkannan** [kubernetes/website#31114]
Hello Doc Team,

This document is very detailed to explain the steps related to Statefulsets. Thank you, also I would like to suggest set of cleanup steps to delete the volumes assigned as part of the tutorial. This would help to leave the system clean at the end of tutorial.

{code}
As part of clean up run the following commands to check the physical volumes assigned.

kubectl get pvc
kubectl get pv
#delete all the volumes assigned.
kubectl delete pvc www-web-0 www-web-1 www-web-2 www-web-3 www-web-4
#validate the volumes released.
kubectl get pvc

{code}

Thank you,
Balraj

**Comment by Kartik494** [comment]
@balrajkannan There is a note in that [documentation](/remove-lifecycle stale) which refers to clear all the persistent volume we have created . @sftim  so is this good idea to add the clean up step also?

**Comment by sftim** [comment]
> This document is very detailed to explain the steps related to Statefulsets. Thank you, also I would like to suggest set of cleanup steps to delete the volumes assigned as part of the tutorial. This would help to leave the system clean at the end of tutorial.

I agree. Adding a Clean Up section to that document is a good idea.

/triage accepted
/priority backlog

**Comment by Kartik494** [comment]
I would like to work on this.
/assign

**Comment by Kartik494** [comment]
@sftim @balrajkannan i have create a PR for the same. PTAL

**Comment by Kartik494** [comment]
@sftim i hae opened the PR and addressed all the comments could you please take a look .
