### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by ryoung75** [kubernetes/website#31110]
This tutorial sucks! Missing objects, illegal access though signed in as root.
![Tutorial error](https://user-images.githubusercontent.com/70113416/147398160-fe01dab9-34f1-418e-8dc4-40400db44786.png)

**Comment by sftim** [comment]
Perhaps the easiest fix is to remove that [tutorial](https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/). I'm not sure that there are resources available to maintain it.
