### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/high-availability/

### ISSUE THREAD

**Issue by jasalgado** [kubernetes/website#31168]
Weave-net URL has changed.

The correct url for Kubernetes 1.16 or later is https://cloud.weave.works/k8s/v1.16/net.yaml

$ curl "https://cloud.weave.works/k8s/net?k8s-version=1.20.0"
code: Redirect
message: >-
  Moved permanently to `/k8s/v1.16/net.yaml`, returning config for Kubernetes
  version v1.16 and above.

It could be interesting include IPALLOC_RANGE environment variable in documentation, too.

Thanks

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/kind cleanup
/help

we should remove the text and example instead of updating it:
```
In this example we are using Weave Net:

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

it already links to another page with CNI instructions:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

**Comment by sftim** [comment]
> we should remove the text and example instead of updating it

:+1:
/triage accepted

**Comment by neolit123** [comment]
/close
fixed in https://github.com/kubernetes/website/pull/31325
