### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/labels/

### ISSUE THREAD

**Issue by WoodpeckerBaby** [kubernetes/website#31190]
Please further clarify `exists` [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement).

**Comment by sftim** [comment]
/kind feature
/language en

The existing explanation (“only the key identifier”) is terse; we can and should expand on that.

**Comment by WoodpeckerBaby** [comment]
Ohh, you mean just the tag! I got it. 'Exists' means a single "key identifier" by itself, like Boolean logic. It's worded a bit awkwardly, I didn't realize the third and fourth statements are examples of exists. 
```
environment in (production, qa)
tier notin (frontend, backend)
partition
!partition
```
