### ISSUE TITLE
Interactive Tutorial - Scaling Your App

### ISSUE THREAD

**Issue by tcellucci** [kubernetes/website#31200]
>   Warning  FailedToUpdateEndpointSlices  4m53s  endpoint-slice-controller  Error updating Endpoint Slices for Service default/kubernetes-bootcamp: failed to update kubernetes-bootcamp-5899q EndpointSlice for Service default/kubernetes-bootcamp: Operation cannot be fulfilled on endpointslices.discovery.k8s.io "kubernetes-bootcamp-5899q": the object has been modified; please apply your changes to the latest version and try again

not sure what the above means exactly, but it blocks completion of the exercise...

**Comment by Shubham82** [comment]
Hi @tcellucci
I tried this [tutorial](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/) on given katakoda terminal but I didn't encounter any this kind of error, for me it is working fine.

**Comment by sftim** [comment]
This might be an intermittent fault with the online Kubernetes environment.

BTW @tcellucci when you log issues, it helps to include the URL of the page where you saw the error.

**Comment by annajung** [comment]
I was also not able to reproduce the error. @tcellucci Could you check to see if you are still running into the same error? If so, could you provide more details on which step?

/language en
/triage not-reproducible
