### ISSUE TITLE
[ko] Translate concepts/architecture/cri.md in Korean 

### ISSUE THREAD

**Issue by anencore94** [kubernetes/website#31211]
This is a Feature Request
Translate `/content/en/docs/concepts/architecture/cri.md` in Korean

What would you like to be added
Translate `/content/en/docs/concepts/architecture/cri.md` in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/concepts/architecture/cri/
/language ko
/assign

**Comments**

I see dev-1.23-ko.1 branch will be merged on 01/06, 2022 from #30832 
Do I need to checkout from dev-1.23-ko.2 when it is created, or just ok to work from dev-1.23-ko.1 ?

**Comment by jihoon-seo** [comment]
Two options will be available.
1. Start your translation from `dev-1.23-ko.1`,
and after `dev-1.23-ko.2` is created,
rebase to `dev-1.23-ko.2` and open a PR. 😊
2. Wait for `dev-1.23-ko.2` to be open,
and start your work from `dev-1.23-ko.2`. 😊

그런데 https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Aopen+base%3Adev-1.23-ko.1 를 보시면
merge target이 `dev-1.23-ko.1` 인 PR들이 아직 많이 열려 있어서
아마 `dev-1.23-ko.1` 브랜치가 오늘 `main`에 머지되지는 못할 것 같습니다.. 😅

그래서, 저는 위의 옵션 중에서는 1번을 추천드립니다. 😊

/triage accepted
