### ISSUE TITLE
[ko] Translate tasks/debug-application-cluster/local-debugging.md into Korean

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#31228]
This is a Feature Request
Translate [/content/en/docs/tasks/debug-application-cluster/local-debugging.md] in Korean

What would you like to be added
Translate [/content/ko/docs/tasks/debug-application-cluster/local-debugging.md] in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/tasks/debug-application-cluster/local-debugging/

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35781
- #36804
- #36810

/close
