### ISSUE TITLE
Versioned kubectl docs need a "latest" version

### ISSUE THREAD

**Issue by foxish** [kubernetes/website#3122]
All links to kubectl commands referenced in various parts of the documentation need to be updated to point to the newer prettier documentation in https://kubernetes.io/docs/user-guide/kubectl/v1.6/#expose
However, these docs appear to be versioned. We need a "latest" version of the docs to link all of our other documentation to.

cc @grodrigues3 @pwittrock @kubernetes/sig-docs-maintainers

**Comment by pwittrock** [comment]
Should we just copy the files?

**Comment by foxish** [comment]
That should work. But if we auto-generate the new docs again, would that somehow cause the other directories/files to get deleted?

**Comment by chenopis** [comment]
@ahmetb Any ideas on a good way to do this?

**Comment by ahmetb** [comment]
I think it's not too bad that these links are versioned. It will help to provide a consistent snapshot of docs while still following the links when we implement versioned docs (#3239, #3992).

We already extensively use template variables `{{page.githubbranch}}` and `{{page.version}}` (defined in _config.yml) in the documentation and it seems to be working. So if you need this "latest" for the k8s.io website, you should follow the same pattern and things will keep working on each release.

It shoudn't be too hard to do by modifying the import script, but I'd like to understand better why we need this.
