### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress-controllers/

### ISSUE THREAD

**Issue by nigoroll** [kubernetes/website#31223]
We have a varnish-cache based ingress also known as Viking https://code.uplex.de/uplex-varnish/k8s-ingress/
@slimhazard

**Comment by sftim** [comment]
I see that https://code.uplex.de/uplex-varnish/k8s-ingress/ describes the project as a
`NOTE: WORK IN PROGRESS`

Once there's a website / non-WIP looking repo for the ingress controller, feel free to open a PR to add it into the list.

**Comment by nigoroll** [comment]
@sftim that's sensible, thank you
