### ISSUE TITLE
Example: Deploying WordPress and MySQL with Persistent Volumes

### ISSUE THREAD

**Issue by yasim21c** [kubernetes/website#31232]
[hi~

i ha](https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/
Example: Deploying WordPress and MySQL with Persistent Volumes

Hello.

I installed the example successfully and saw the WordPress screen.

Basic contents were registered and confirmed.

After that, when I shut down the minikube service and started the service again, the server did not come up and I could not see the WordPress screen.

what's the reason?)

**Comment by Kartik494** [comment]
@yasim21c When you delete the environment the services you deploy in cluster also get deleted 
`
kubectl get svc
NAME              TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
kubernetes        ClusterIP      10.96.0.1       <none>        443/TCP        8d
wordpress         LoadBalancer   10.105.38.231   <pending>     80:31573/TCP   4m
wordpress-mysql   ClusterIP      None            <none>        3306/TCP       4m29s
`

**Comment by Kartik494** [comment]
Ideally that doesn't work if you don't have any service deploy on your cluster , for running this again, you have to deploy this application again

**Comment by yasim21c** [comment]
> Ideally that doesn't work if you don't have any service deploy on your cluster , for running this again, you have to deploy this application again

thank you.
