### ISSUE TITLE
[ko] Example: Deploying WordPress and MySQL with Persistent Volumes

### ISSUE THREAD

**Issue by yasim21c** [kubernetes/website#31233]
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/
Example: Deploying WordPress and MySQL with Persistent Volumes

안녕하세요.

나는 예제를 성공적으로 예제를 설치하고 워드프레스 화면을 보았다.

기본적인 내용을 등록, 확인하였다.

이후 minikube 서비스를 종료하고 다시 서비스를 시작하니 서버도 올라오지 않고 워드프레스 화면도 볼 수가 없었다.

이유가 무엇입니까?

**Comment by jihoon-seo** [comment]
/retitle [ko] Example: Deploying WordPress and MySQL with Persistent Volumes
/kind support
