### ISSUE TITLE
Document that specifying --service-account-issuer multiple times requires k8s v1.22 or later

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#31235]
**This is a Bug Report**

**Problem:**
As per discussion in [#107031](https://github.com/kubernetes/kubernetes/issues/107031) we have to add a note [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection) for  **`--service-account-issuer`**  flag that we can specify it multiple times only in k8s v1.22 and v1.22+ versions.

Ref: [#107031](https://github.com/kubernetes/kubernetes/issues/107031), [#101155](https://github.com/kubernetes/kubernetes/pull/101155) 

**Proposed Solution:**
Add note that we can allow or specify **`--service-account-issuer`**  flag multiple times in k8s v1.22 and v1.22+ versions

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

**Comment by sftim** [comment]
/retitle Document that specifying --service-account-issuer multiple times requires k8s v1.22 or later
/language en
/remove-kind bug
/kind feature

**Comment by Shubham82** [comment]
Thanks, @sftim for taking look at this.

**Comment by Shubham82** [comment]
Fixed it here: #31237
