### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl-windows/

### ISSUE THREAD

**Issue by shubham-mandhare** [kubernetes/website#31243]
When I run the suggested command to Enable shell autocompletion it returns the following error:

```
kubectl completion powershell >> $PROFILE
error: Unsupported shell type "powershell".
See 'kubectl completion -h' for help and examples
```

I have kubectl version 1.22.4

**Comment by anubha-v-ardhan** [comment]
Was the kubectl completion script generated successfully?

**Comment by anubha-v-ardhan** [comment]
Was the kubectl completion script generated successfully?

**Comment by anubha-v-ardhan** [comment]
Was the kubectl completion script generated successfully?

/kind support

**Comment by shubham-mandhare** [comment]
> 

Yes.

**Comment by mehabhalodiya** [comment]
@shubham-mandhare Have a look at [this](https://github.com/kubernetes/website/issues/31341).
I think it's somehow related.

**Comment by anubha-v-ardhan** [comment]
>No. kubectl completion -h does not show PowerShell as a valid option. Whereas the documentation says it exists.

@shubham-mandhare If I'm not wrong v1.22 doesn't have autocompletion support for Powershell (refer [v1.22 documentation for Optional kubectl configurations and plugins](https://v1-22.docs.kubernetes.io/docs/tasks/tools/install-kubectl-windows/#optional-kubectl-configurations-and-plugins)

If possible, you can update to latest version (v1.23) which has autocompletion support for  Bash, Zsh, Fish, and PowerShell ([refer v.23 docs](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#optional-kubectl-configurations-and-plugins)
