### ISSUE TITLE
New timings for APAC friendly SIG Docs meeting

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#31256]
The new APAC friendly meetings for SIG Docs have been moved per community consensus to account for all timezones under APAC per [this slack thread](https://kubernetes.slack.com/archives/C1J0BPD2M/p1638888987356000) and [this email](https://groups.google.com/g/kubernetes-sig-docs/c/P7iLejmEIFA). 

## Required changes

This requires some updates

| Repo  | file  | Complete?  |
|---|---|---|
| k/community  | [sig-docs/README.md](https://github.com/kubernetes/community/blob/master/sig-docs/README.md)  |   |
| k/community  | [sigs.yaml](https://github.com/kubernetes/community/blob/master/sigs.yaml#L1389) |   |
| k/community  | [sig-list.md](https://github.com/kubernetes/community/blob/master/sig-list.md) |   |

**Comment by jihoon-seo** [comment]
It seems that all 3 files are updated so this issue is okay to close. 😊

**Comment by tengqm** [comment]
Let's mark it done then.
