### ISSUE TITLE
Explain meaning of “object” in Nodes concept

### ISSUE THREAD

**Issue by neetika-Sri** [kubernetes/website#31253]
https://kubernetes.io/docs/concepts/architecture/nodes/#management

On line `after you create a node object.... ` - Its better to clarify where node object is created. My assumption is on control panel (api server).

**Comment by sftim** [comment]
We could use a [glossary tooltip](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) for “object”, so that you can click on that and confirm that objects are created in the API server.

/kind feature
/triage accepted
/priority backlog

**Comment by sftim** [comment]
/retitle Explain meaning of “object” in Nodes concept
/help

**Comment by Babapool** [comment]
Hi, I would like to work on this issue.
/assign
