### ISSUE TITLE
Remove "Copied to clipboard" popup

### ISSUE THREAD

**Issue by shivanshu1333** [kubernetes/website#31258]
**This is a Feature Request**

**What would you like to be added**

Whenever a user copies to the clipboard using the copy button, a pop message as shown is displayed, which stays on the screen and require the user to manually click ok to close it, this is not an intended behaviour as it requires "manual effort" for not so useful task.
It becomes annoying, especially during the certification exam.

**Why is this needed**
To remove user interaction to manually close the clipboard message, saving time
**Comments**

For eg. try clicking on `pods/storage/pv-claim.yaml Copy pods/storage/pv-claim.yaml to clipboard
` on https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage#create-a-persistentvolumeclaim
<img width="1190" alt="Screenshot 2022-01-09 at 1 28 03 PM" src="https://user-images.githubusercontent.com/26167974/148674669-5fa71da2-d467-47b5-9183-16da4629d05b.png">

** Proposed solution**
It is not required to show the pop message blocking the whole screen, either change the colour of the component for a few seconds, or do nothing at all.

**Comment by sftim** [comment]
BTW: as a work-around you can press Enter to dismiss that “copied” message.

**Comment by mehabhalodiya** [comment]
What to do with this issue? Should we accept?
Additionally, PR is up which resolves this issue!

**Comment by sftim** [comment]
It'd be nice to show a non-modal notification. Maybe an animation on the copy icon? Maybe show the word “copied to clipboard” but hide that hint automatically after a few seconds?

**Comment by sftim** [comment]
> Also, "copy to clipboard" is not available everywhere 

@shivanshu1333 you are very welcome to file an issue on that topic, or to submit a pull request. Please do bear in mind that the project's review criteria for any change are going to be “does this change improve the docs?” and not specifically “does this change help people who are in a Kubernetes exam?”.

**Comment by shivanshu1333** [comment]
Completely Agree!
It's just an addon that may help during certifications (bad issue name I know, my bad).
This is something that I noticed and I feel it isn't an intended behaviour (gives bad user experience), so I reported it.

Does it make sense to follow the same pattern across the complete documentation website? i.e. if we have a copy button let's have it everywhere or remove it from everywhere to maintain homogeneity, or we can keep it like that (no one really notices)
 
Do you think this needs attention and will add value to Kubernetes documentation? I know this is a tedious task, figuring out the various points where the "copy button" is missing and implementing them, but could be a good first issue.
WDYT? @sftim :)
