### ISSUE TITLE
CRI doc in website isn't synced with master branch. 

### ISSUE THREAD

**Issue by jmyung** [kubernetes/website#31260]
CRI doc(https://kubernetes.io/docs/concepts/architecture/cri/) in website is not synced with [cri.md](https://github.com/kubernetes/website/blob/81b52552244d52b561341f940a581f6cf4c20022/content/en/docs/concepts/architecture/cri.md?plain=1#L18) in ~~master~~ main branch.

Shouldn't it be synced?

**Comment by jmyung** [comment]
help 😅  @saschagrunert

**Comment by sftim** [comment]
/priority awaiting-more-evidence
/triage not-reproducible

What doesn't seem to be current @jmyung? This [k/website](https://github.com/kubernetes/website) repository doesn't have a branch named `master`

**Comment by jmyung** [comment]
**site: https://kubernetes.io/docs/concepts/architecture/cri/**
```
You need a working container runtime on each Node in your cluster, so that the kubelet can launch Pods and their containers.

The main protocol for the communication between the kubelet and Container Runtime.

The Kubernetes Container Runtime Interface (CRI) defines the main gRPC protocol for the communication between the cluster components kubelet and container runtime.
```

**main branch: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/architecture/cri.md**
- line 12-18
- no contents starts with _The main protocol ..._
```
You need a working
{{<glossary_tooltip text="container runtime" term_id="container-runtime">}} on
each Node in your cluster, so that the
{{< glossary_tooltip text="kubelet" term_id="kubelet" >}} can launch
{{< glossary_tooltip text="Pods" term_id="pod" >}} and their containers.

{{< glossary_definition term_id="container-runtime-interface" length="all" >}}
```

**Comment by saschagrunert** [comment]
@sftim @jmyung from what I can see they're not out of sync, we just reference the glossary definition into it:

```
{{< glossary_definition term_id="container-runtime-interface" length="all" >}}
```

compiles to 

```
The main protocol for the communication between the kubelet and Container Runtime.

<!--more-->

The Kubernetes Container Runtime Interface (CRI) defines the main
[gRPC](https://grpc.io) protocol for the communication between the
[cluster components](/docs/concepts/overview/components/#node-components)
{{< glossary_tooltip text="kubelet" term_id="kubelet" >}} and
{{< glossary_tooltip text="container runtime" term_id="container-runtime" >}}.
```

**Comment by saschagrunert** [comment]
We could enhance this by applying something like https://github.com/kubernetes/website/pull/31266

**Comment by saschagrunert** [comment]
@jmyung we improved the docs, see: https://deploy-preview-31266--kubernetes-io-main-staging.netlify.app/docs/concepts/architecture/cri/

Let's close this for now, feel free to reopen if we missed anything. Thanks!

/close
