### ISSUE TITLE
Issue with k8s.io/docs/reference/kubectl/overview/

### ISSUE THREAD

**Issue by praveensh0** [kubernetes/website#31264]
Hi All,

In the subject of this ticket, the link is mentioned, an example mentioned is incorrect.

We are creating a shell script "kubectl-hello" and placing it in the /use/local/bin then how come the output is "hello world" with "**kubectl hello**" command shouldn't it be "**kubectl-hello**" ?

The Examples: **Creating and using plugins** 

create a simple plugin in any language and name the resulting executable file so that it begins with the prefix "kubectl-"
cat ./kubectl-hello

#!/bin/sh

this plugin prints the words "hello world"
echo "hello world"

With a plugin written, let's make it executable:

chmod a+x ./kubectl-hello

and move it to a location in our PATH
sudo mv ./kubectl-hello /usr/local/bin
sudo chown root:root /usr/local/bin

You have now created and "installed" a kubectl plugin.
You can begin using this plugin by invoking it from kubectl as if it were a regular command
**kubectl hello**

The plugin mentioned should be **kubectl-hello** instead of **_kubectl hello_**"

Similar issue in the document in other examples:
kubectl whoami -> kubectl-whoami

**Comment by sftim** [comment]
/kind support

@praveensh0 the text of the page looks correct to me. Did you try running `kubectl hello`?

**Comment by praveensh0** [comment]
@sftim When I ran it, it's working but I am wondering how it's working. How /kubectl-hello is translated into /kubectl hello?
