### ISSUE TITLE
`OWNERS_ALIASES` links go to `OWNERS`, which is wrong

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#31279]
**This is a Bug Report**

**Problem:**
In [here](https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-reviewer) and [here](https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-an-approver),
`OWNERS_ALIASES` links go to https://github.com/kubernetes/website/blob/main/OWNERS, which is wrong.

They should go to https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES .

**Proposed Solution:**
Find `[OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS)`,
and replace with `[OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES)` .

**Page to Update:**
https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/

/language en
/kind cleanup
/good-first-issue

**Comment by Harshmori** [comment]
hello, is anyone solving this issue? or should I start(it's my first time)
