### ISSUE TITLE
Add "event" to glossary

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#31291]
**This is an Enhancement Request**

**What would you like to be added**

Add "event" entry to the Kubernetes [Reference Glossary](https://kubernetes.io/docs/reference/glossary/?fundamental=true).

**Why is this needed**

`event`s are referenced several times in other definitions, but it is not itself defined.

**Comment by anubha-v-ardhan** [comment]
/assign
I would like to give this a try

**Comment by nate-double-u** [comment]
Awesome, thanks @anubha-v-ardhan!
