### ISSUE TITLE
Issue with k8s.io/docs/tasks/extend-kubernetes/setup-konnectivity/

### ISSUE THREAD

**Issue by parmentelat** [kubernetes/website#31294]
hi
I'm trying to follow the instructions provided on that page - mentioned in the header
and am facing an issue understanding this part:

![image](https://user-images.githubusercontent.com/4519227/149015159-8e3968d2-4229-4f3e-be22-65862d01e9db.png)

the framed code seems to belong to a yaml file describing a pod
and it is suggested this would belong to the apiserver pod; is that right? 
if so, where do I find the yaml file in question so that I can add these settings ? 

sorry I'm a bit of a newbie with kubernetes and the general configuration flow is still not something that I am fluent with - obviously

in any case this particular point could imho be made clearer

thanks in advance

**Comment by sftim** [comment]
Easy part of a fix: how about we list “you should already know how to configure the kube-apiserver for your cluster” as a prerequisite?

Harder part of a fix: add a task page that explains how to reconfigure the kube-apiserver (including determining whether you even have access to do so).

**Comment by parmentelat** [comment]
so you're saying there's currently no page that explains how to reconfigure the apiserver; maybe that's the core of my problem then ;)

as to know whether I have access to configuring the apiserver, I do have root access on all those boxes since I am the one who installed them from scratch in the first place; I am evidence it is perfectly possible to install a simple but functional cluster without knowing how to configure the apiserver, as at this early point it is all taken care for me by kubeadm..
