### ISSUE TITLE
[ko] Translate concepts/architecture/garbage-collection.md in Korean 

### ISSUE THREAD

**Issue by anencore94** [kubernetes/website#31302]
This is a Feature Request
Translate `/content/en/docs/concepts/architecture/garbage-collection.md` in Korean

What would you like to be added
Translate `/content/en/docs/concepts/architecture/garbage-collection.md` in Korean

Why is this needed
This file is not translated yet.

Comments
Page to translate : https://kubernetes.io/docs/concepts/architecture/garbage-collection/
/language ko
/assign

**Comments**

**Comment by jihoon-seo** [comment]
Resolved by 
- #31924
- #32789

`ko` page: https://kubernetes.io/ko/docs/concepts/architecture/garbage-collection/

/close
