### ISSUE TITLE
Query about injecting cluster details into Pod as environment variable

### ISSUE THREAD

**Issue by anasokan** [kubernetes/website#31301]
Do we have any option to inject the cluster name as environment variables to pod?

I have a requirement that the cluster name has to be used by pod to determine the location where it is running. In case of multiple Kubernetes cluster the local region is identified using this

**Comment by sftim** [comment]
I think this might be feature request for Kubernetes. The Kubenetes API doesn't know the name of a cluster.

Workaround: store the details you want to use in a ConfigMap.

**Comment by sftim** [comment]
/retitle Query about injecting cluster details into Pod as environment variable
(the issue is feedback for the page https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/)

**Comment by anasokan** [comment]
@sftim ,

Thanks for the workaround.
Let's keep this open and see if this feature can be taken in Kubernetes.

**Comment by sftim** [comment]
/close

If you want to propose a new feature to Kubernetes where the cluster becomes aware of its name, see https://github.com/kubernetes/kubernetes/issues/new/choose
