### ISSUE TITLE
Error link in DaemonSet page

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/website#31311]
Doc page: Perform a Rolling Update on a DaemonSet https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/#performing-a-rolling-update

It incorrectly links to Deployment page for DaemonSet API fields. 

Also , the field should be `.spec.updateStrategy.rollingUpdate.maxSurge` instead of `.spec.maxSurge`

**Comment by mengjiao-liu** [comment]
Both `Daemonset` and `Deployment` use the fields `MaxUnavailable` and `MaxSurge` of the [RollingUpdateDaemonSet](https://github.com/kubernetes/kubernetes/blob/2f64227aeab46ab77de4b996a4ce63209295de60/pkg/apis/apps/types.go#L582) structure, so the explanation of the link to the deployment field is not wrong, it's just a bit misleading.

Of course, I think the best way is to describe these fields on a page so that the daemonset and deployment refer to them, rather than linking directly to the deployment page from the daemonset page.

> Also , the field should be .spec.updateStrategy.rollingUpdate.maxSurge instead of .spec.maxSurge

I think you are right. correct identification: `.spec.updateStrategy.rollingUpdate.maxSurge`

**Comment by sftim** [comment]
We could link to https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec (and provide context for that link), instead of linking to the Deployment concept.

**Comment by mengjiao-liu** [comment]
> (and provide context for that link)

How to understand this sentence? How to do?  I'm not clear.

**Comment by 889-dj** [comment]
hello @mehabhalodiya I would love to work on this as I m new could u please guide me as what I understood is a link needs to be changed

**Comment by Anubhavdevv** [comment]
Hello @mehabhalodiya @anubha-v-ardhan I would like to contribute to it can you assign this issue to me 
Thank you !!

**Comment by mehabhalodiya** [comment]
Hey @889-dj @Anubhavdevv 
Glad to hear that you are willing to work on this! 🎉 
But it is fixed here:
-  #31354 

If you are interested to work on another `good first issue` let me know how can I help you.
Thank you 🙂

**Comment by Anubhavdevv** [comment]
Sure @mehabhalodiya it would be great if you mentioned some good first issue so that I can contribute 🙂

**Comment by mehabhalodiya** [comment]
@MdSahil-oss Can you please assign this issue to yourself with `/assign @MdSahil-oss` here?

**Comment by 889-dj** [comment]
> Hey @889-dj @Anubhavdevv Glad to hear that you are willing to work on this! 🎉 But it is fixed here:
> 
> * [Update update-daemon-set.md #31354](https://github.com/kubernetes/website/pull/31354)
> 
> If you are interested to work on another `good first issue` let me know how can I help you. Thank you 🙂

Thanku Meha I will surely look for other issues 🙂

**Comment by PriyanshuAhlawat** [comment]
hey @janetkuo i will like to work on this issue , i am just a beginner in open source so can you guide me regarding what needs to be done for the link leading to deployment page and does field .spec.maxSurge still needs to be updated?

**Comment by mehabhalodiya** [comment]
This issue is fixed #31407.

/close
