### ISSUE TITLE
Change Go Doc URL from godoc.org to pkg.go.dev

### ISSUE THREAD

**Issue by inductor** [kubernetes/website#31318]
**This is a Feature Request**

https://godoc.org/ is an old endpoint and it automatically redirects to https://pkg.go.dev/. Before it will be removed at some point, it makes sense to change the URL.

**What would you like to be added**
Modify Go Doc reference URL

**Why is this needed**

The current URL is deprecated.

**Comments**

**Comment by RayAsh37** [comment]
I have opened a PR #31340
