### ISSUE TITLE
Metrics for PodOverhead was split into two

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#31348]
**This is a Bug Report**

/sig node
/priority important-longterm
KEP: https://github.com/kubernetes/enhancements/issues/688

PodOverhead metrics mentioned here https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/#observability was split into two in this PR: https://github.com/kubernetes/kube-state-metrics/pull/1168/

Instead of `kube_pod_overhead` with two labels, there is now two metrics `kube_pod_overhead_cpu_cores` and `kube_pod_overhead_memory_bytes`.

**Comment by nate-double-u** [comment]
fixed in https://github.com/kubernetes/website/pull/32328
/close
