### ISSUE TITLE
Install and Set Up kubectl on Windows

### ISSUE THREAD

**Issue by PaulaMihalcea** [kubernetes/website#31341]
Hello,

I have recently[ installed kubectl on Windows 10 using curl](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows) and I have noticed that there is a slight error at step 3. Namely, the line says:

`"Add the binary in to your PATH."`

when it really should be:

`"Add the binary's folder to your PATH."`

I have tested it a few times and indeed, adding `\path_to_kubectl\kubectl.exe` to PATH does _not_ work, while simply adding `\path_to_kubectl\` yields the correct result (i.e. being able to invoke kubectl commands from the command prompt).

I know it is a minor issue but for beginners (like myself) it could make the difference between completing the installation or not.

Even though I have not tried other methods of installation, I suspect that the same step should also be corrected in section [_Install kubectl convert plugin_](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-convert-plugin), where it also says "Add the binary in to your PATH."

Best regards,
Paula

**Comment by jihoon-seo** [comment]
/triage accepted

Similar issue exists in ["Install kubectl binary with curl on Linux" section](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux).

> and then add ~/.local/bin/kubectl to $PATH

---

cf. In ["Install and Set Up kubectl on macOS" page](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-kubectl-binary-with-curl-on-macos):

![image](https://user-images.githubusercontent.com/46767780/149474650-c176f5b9-8d67-4eb5-ae16-762a31c9e3a0.png)

**Comment by sftim** [comment]
>  add `~/.local/bin/kubectl` to `$PATH`

is kind of techie vernacular (it's how I'd say it in spoken English to a colleague), but in technical docs we can be more precise.
/language en

**Comment by Babapool** [comment]
Hi, I would like to work on this issue.
/assign
