### ISSUE TITLE
PodSecurity migration guide needs some clarification

### ISSUE THREAD

**Issue by photoni-137** [kubernetes/website#31367]
The steps described on k8s.io/docs/tasks/configure-pod-container/migrate-from-psp/ are a great help! However, it is not explained how one would manage to "[c]lone [...] mutating PSPs into a non-mutating version". The [Docs for PSPs](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) explicitly mark some fields like `MustRunAsNonRoot` or `DefaultAddCapabilities` as mutating, but it's not clear whether those form an exhaustive list or there are other, more implicit "mutators".

IMO, clarification is needed on the following points:
1. Which fields of a PSP are potential "mutators"?
1. Is there are way to make any PSP non-mutating *independently* of its potential targets' security context?
1. If not, how can non-mutability be ensured? Dropping all mutating fields in the PSP and hardcoding their values into the security context of their target pods?

**Comment by sftim** [comment]
/sig auth
/sig security
/language en
/kind feature

I'm not sure how to prioritize this. PodSecurityPolicy is a beta feature and we don't plan to improve it further; however, people who are already using the beta feature do want guidance on how to move away.

SIG Docs folks: thoughts on prioritization?

**Comment by tallclair** [comment]
Yes, I agree this is confusing (or just flat out wrong) and needs clarification. Some of the fields recommended for the restricted PSP (https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/policy/restricted-psp.yaml) are actually mutating (requiredDropCapabilities).

@sftim Users must mirate off of PSP in v1.24, since it's going away in v1.25, so I think having a clear migration guide is a high priority. I'll take this on.

**Comment by tallclair** [comment]
@photoni-137 it looks like I can't assign the PR to you, but if you get a chance I'd appreciate your feedback on the updated guide: https://github.com/kubernetes/website/pull/31782

**Comment by photoni-137** [comment]
@tallclair Looks great! The updated guide covers all of my questions and I'm sure it will a valuable asset to anyone else migrating to the new Standards. Thank you for writing such a detailed guide! :)
