### ISSUE TITLE
Improvement for k8s.io/docs/concepts/cluster-administration/networking/ Call it "add-on" or don't call it "add-on"?

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#31371]
> See a list of add-ons that implement the [Kubernetes networking model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model)

But the page [Kubernetes networking model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model) never uses the term "add-on".

Please agree on the terminology. What does this page list? Is it a list of add-ons or not?

**Comment by sftim** [comment]
Are network plugins a special case of add-on? https://kubernetes.io/docs/concepts/cluster-administration/addons/ strongly implies they are. This seems like a minor thing.

/kind cleanup
/language en

I recommend moving https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model _and_ https://kubernetes.io/docs/concepts/cluster-administration/addons/#networking-and-network-policy into a new page that lives within the Reference section.
