### ISSUE TITLE
About Kubernetes manifests (YAML format)

### ISSUE THREAD

**Issue by ytqiao3** [kubernetes/website#31382]
I hope to be able to produce a document to explain what attributes can be defined in the yaml file of each controller and pod

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/ is the closest we have.

Did you want to work on making something similar but different @ytqiao3 ?

/triage needs-information

/retitle About Kubernetes manifests (YAML format)

**Comment by tengqm** [comment]
You may want to give KAB a try by running `docker run -p 8000:8000 quay.io/tengqm/kab` and then opening "http://localhost:8000" in a browser.
