### ISSUE TITLE
Update kubeadm join for windows documentation for hostprocess containers support

### ISSUE THREAD

**Issue by marosset** [kubernetes/website#31395]
**This is a Feature Request**

**What would you like to be added**

The documentation for add using kubeadm to join Windows nodes to a cluster should be updated to take into account running CNI pods as HostProcessContainers.

[content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md ](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md)

**Why is this needed**
When using containerd CNIs needed to either be installed as a windows service or run as a HostProcessContainer to function properly.

The currently installation steps only work when running CNIs as a Windows server OR running CNI pods with Docker (which uses a docker network to work around host-networking limitations on Windows)

**Comments**

/sig windows

**Comment by sftim** [comment]
/sig cluster-lifecycle
too
