### ISSUE TITLE
Update Create static Pods task to remove Docker mentions

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#31394]
ref: https://github.com/kubernetes/website/issues/30923

On https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/, update the following: 

1. Update the following line in the [Before you begin](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/#before-you-begin) section: 

> This page assumes you're using Docker to run Pods, and that your nodes are running the Fedora operating system. Instructions for other distributions or Kubernetes installations may vary.

Update this to: 

> This page assumes you're using containerd to run Pods, and that your nodes are running the Fedora operating system. Instructions for other distributions or Kubernetes installations may vary.

2. Replace all instances of `docker ps` with `crictl ps` 

3. Replace **all output blocks** after `docker ps` commands with the equivalent `crictl ps` command output 

/triage accepted
/language en

**Comment by afbjorklund** [comment]
I thought fedora users used cri-o (not containerd) ?

**Comment by RishiKumarRay** [comment]
@chris-short Are you working on this or else please do assign to me , I would love to contribute

**Comment by chris-short** [comment]
I'm testing the steps now.

**Comment by chris-short** [comment]
/hold

I missed a docker.

**Comment by chris-short** [comment]
This is done.
