### ISSUE TITLE
Capacity section in Persistent Volumes points to archived page

### ISSUE THREAD

**Issue by amej** [kubernetes/website#31396]
> See the Kubernetes Resource Model to understand the units expected by capacity.

The [Kubernetes Resource Model ](https://git.k8s.io/community/contributors/design-proposals/scheduling/resources.md) points to archived design proposal.  url: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/resources.md

I expect the section to point to a url specifying expected/recommended storage units by Kubernetes, say Gi/Ti/G/Bytes etc .

How to locate the above section:
Navigate as follows: Kubernetes Documentation -> Concepts -> Storage -> Persistent Volumes

Page:  [Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
Sub-Section :  [Capacity](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#capacity)

**Comment by sftim** [comment]
/language en

We should update the page you're thinking of to reference some current docs about quantities. What's the URL of the page that is wrong @amej?

**Comment by amej** [comment]
> We should update the page you're thinking of to reference some current docs about quantities. What's the URL of the page that is wrong @amej?

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#capacity

**Comment by tengqm** [comment]
We have some text scattered somewhere, for example, https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#memory-units

**Comment by sftim** [comment]
Also https://kubernetes.io/docs/reference/glossary/?all=true#term-quantity

**Comment by amej** [comment]
The issue is fixed with #31566 .

**Comment by amej** [comment]
> /remove-triage

The issue can be closed because the relevant PR has been merged.  I will like to perform 2 activities on this issue before closure
 1.  In the subsection  "Linked pull requests Successfully merging a pull request may close this issue. " ,  add the link to the PR.
 2.  Remove the "needs-triage" label 
As seen from my comments, my attempts have failed.  How do I achieve the above 2 actions?

**Comment by sftim** [comment]
@amej, would you be interested in [joining the Kubernetes organization](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+amej)? If so, ask in Slack - see https://slack.k8s.io/ for an overall invitation, or https://kubernetes.slack.com/messages/sig-docs for the SIG Docs channel - folks will be happy to help.

**Comment by amej** [comment]
> @amej, would you be interested in [joining the Kubernetes organization](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&template=membership.yml&title=REQUEST%3A+New+membership+for+amej)? If so, ask in Slack - see https://slack.k8s.io/ for an overall invitation, or https://kubernetes.slack.com/messages/sig-docs for the SIG Docs channel - folks will be happy to help.

I am interested. I will start the process.
