### ISSUE TITLE
issue in docs/concepts/services-networking/service-traffic-policy

### ISSUE THREAD

**Issue by KobayashiD27** [kubernetes/website#31403]
**This is a Feature Request**

**What would you like to be added**

This feature state looks need to be updated.

**Why is this needed**
In [server-traffic-policy](https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/), the Feature state is v1.21[alpha]. However, this feature has already been beta. https://github.com/kubernetes/kubernetes/pull/103462

**Comments**

**Comment by MdSahil-oss** [comment]
Fixed this issue :-> #31408
