### ISSUE TITLE
Update Japanese content to mention KubeCon 2022 conference

### ISSUE THREAD

**Issue by krvaibhaw** [kubernetes/website#31400]
**This is a Bug Report**

**Problem:**

These KubeCon conferences are already over but we still have :

- 2020年11月17日-20日のKubeCon NAバーチャルに参加する
- 2021年5月4日-7日のKubeCon EUバーチャルに参加する

**Proposed Solution:**

Needs to be updated to :

- 2021年5月4日-7日のKubeCon EUバーチャルに参加する
- スペインのKubeConバレンシアに参加+バーチャル、2022年5月16〜20日

**Page to Update:**

`website/content/ja/_index.html`

/good-first-issue

**Comment by jihoon-seo** [comment]
- Related PR: #31401

/triage accepted

**Comment by krvaibhaw** [comment]
Hey, @jihoon-seo

Could you be my sponsors to get the membership of Kubernetes?

My contributions to the Kubernetes Project includes : 
https://github.com/kubernetes/website/commits/main?author=krvaibhaw

I think I could review PRs for website updates and other minor changes.
That's why I want to become a member and contribute to open source.

**Comment by jihoon-seo** [comment]
@krvaibhaw Sure!

[Requirements & steps to become a member]
- https://kubernetes.io/docs/contribute/participate/roles-and-responsibilities/#becoming-a-member
  - Submit at least 5 substantial pull requests: https://github.com/kubernetes/website/pulls?q=is%3Apr+author%3Akrvaibhaw
- https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by krvaibhaw** [comment]
Fixed with #31401
/close
