### ISSUE TITLE
Rewrite “Pull an Image from a Private Registry” topic

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#31409]
ref: https://github.com/kubernetes/website/issues/30923

From @sftim: 

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ clearly needs an update or even splitting into different pages. There are lots of Docker-specific details, some of which need to stay and some of which need to change. 
   - We need an issue to update that page.
   - The example container registry is Docker Hub, so we might need to explain to readers what the different meanings of Docker could be.

----

I suggest the following: 

- Update mentions of Docker to specifically refer to Docker Hub
- Update the introduction to this page to the following: 
   > This page shows how to create a Pod that uses a Secret to pull an image from a private container image registry or repository. There are many private registries in use. This task uses Docker Hub as an example of the steps needed.
- Update the Before You Begin section to the following:

```
* {{< include "task-tutorial-prereqs.md" >}}

* To do this exercise, you need the `docker` command line tool, and a
  [Docker Hub ID](https://docs.docker.com/docker-id/) for which you know the password.
* If you are using a different private container registry, you need the command line tool for that registry and any login information for the registry. 
```

---

I would recommend this task for someone experienced with Secrets. 

/triage accepted
/milestone 1.24

**Comment by sftim** [comment]
/retitle Rewrite “Pull an Image from a Private Registry” topic
