### ISSUE TITLE
Make small wording adjustments to some Case Studies for mentions of docker

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#31424]
ref: https://github.com/kubernetes/website/issues/30934

Some of the case studies need a bit of rewording to remove unnecessary mention of docker.

**Note:** the case studies are HTML + CSS rather than markdown - you need to be familiar with that in order to update these!

https://kubernetes.io/case-studies/peardeck/index.html
➤ I'd reword “Docker containers” to “containers”

https://kubernetes.io/case-studies/prowise/index.html
➤ I'd reword “Dockerize” to “containerize”

https://kubernetes.io/case-studies/squarespace/index.html
➤ I'd reword “Docker file” to “Dockerfile”

https://kubernetes.io/case-studies/wink/index.html
➤ I'd change “just over two years ago” to “in 2015”
➤ I'd also change “Dockerized” to “containerized”

/priority backlog
/triage accepted

**Comment by Babapool** [comment]
Hi there, I would like to work on this issue.
/assign

**Comment by Babapool** [comment]
I have an question does the PR need to made against the `main` branch or the `dev-1.24` branch? Thanks

**Comment by mehabhalodiya** [comment]
> I have an question does the PR need to made against the `main` branch or the `dev-1.24` branch? Thanks

@Babapool You need to make a PR against the `main` branch.

**Comment by Babapool** [comment]
Hi @mehabhalodiya, I have opened a [PR](https://github.com/kubernetes/website/pull/31487) regarding this a few day ago. If you are free can you PTAL at the PR. Thanks.

**Comment by mehabhalodiya** [comment]
@shoukathmd Please close your PR #31519 as @Babapool has already [submitted](https://github.com/kubernetes/website/issues/31424#issuecomment-1022168402) it earlier.
Kindly look into those issues which are not already assigned to someone.
Thank you.
