### ISSUE TITLE
Update blog page template to display a warning on blog posts older than year 

### ISSUE THREAD

**Issue by celestehorgan** [kubernetes/website#31426]
ref: https://github.com/kubernetes/website/issues/30771, but this is also just a general feature!

Blog posts by their nature go stale over time. This becomes particularly problematic when we decide to deprecate functionality in the project, as those blog posts are forever a part of the docs and forever searchable via Google.

Update the blog post's templates (probably https://github.com/kubernetes/website/blob/main/layouts/blog/baseof.html, but you may need to copy over `single.html` from the Docsy theme) to include a warning for blog posts over 1 year old:

> **Warning:** This blog post was published over a year ago. Use caution when following any steps published, unless otherwise noted in the post.

Some notes:

- Use standard docsy warning block styles
- Make sure strings are in localization files so the localization teams know where to look

/triage accepted
/priority important-soon
/area website

**Comment by chalin** [comment]
Sorry y'all, I hadn't seen this issue before I created #31043. It turns out that there's a clean solution that doesn't involve changes to the blog template.

Anyhow, this has been closed by #31594. /cc @sftim @nate-double-u

**Comment by nate-double-u** [comment]
/close

Thanks @chalin!
