### ISSUE TITLE
Fix incorrect / outdated URIs in list of network plugins

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#31430]
**This is a Feature Request**

**What would you like to be added**

In [`content/en/docs/concepts/cluster-administration/networking.md`](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/networking.md#cni-genie-from-huawei),
- update the link URL from https://github.com/Huawei-PaaS/CNI-Genie 
  to https://github.com/cni-genie/CNI-Genie
- update the link URL from https://github.com/Huawei-PaaS/CNI-Genie/blob/master/docs/multiple-cni-plugins/README.md#what-cni-genie-feature-1-multiple-cni-plugins-enables 
  to https://github.com/cni-genie/CNI-Genie/blob/master/docs/multiple-cni-plugins/README.md#what-cni-genie-feature-1-multiple-cni-plugins-enables
- update the link URL from https://github.com/coreos/flannel#flannel
  to https://github.com/flannel-io/flannel#flannel
- update the link URL from https://docs.projectcalico.org
  to https://projectcalico.docs.tigera.io/about/about-calico
- update the link URL from https://www.weave.works/products/weave-net/
  to https://www.weave.works/oss/net/
- update the link URL from https://github.com/Huawei-PaaS/CNI-Genie/blob/master/docs/multiple-ips/README.md#feature-2-extension-cni-genie-multiple-ip-addresses-per-pod
  to https://github.com/cni-genie/CNI-Genie/blob/master/docs/multiple-ips/README.md#feature-2-extension-cni-genie-multiple-ip-addresses-per-pod

**Why is this needed**

https://github.com/Huawei-PaaS/CNI-Genie redirects to https://github.com/huawei-cloudnative/CNI-Genie ,
which is a fork of https://github.com/cni-genie/CNI-Genie and currently 62 commits behind `cni-genie:master`.

- The latest commit of https://github.com/cni-genie/CNI-Genie : on 29 Oct 2021
- The latest commit of https://github.com/huawei-cloudnative/CNI-Genie : on 12 Feb 2019

and for other CNIs, it would be better to use the final URLs than using redirecting URLs.

**Comments**

Page to update: https://kubernetes.io/docs/concepts/cluster-administration/networking/#cni-genie-from-huawei

**Comment by sftim** [comment]
/retitle Fix incorrect / outdated URIs in list of network plugins
/language en
/priority backlog
