### ISSUE TITLE
Error while downloading kubectl convert

### ISSUE THREAD

**Issue by karan316** [kubernetes/website#31438]
I was following the instructions on [this page](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/). When I download the kubectl convert plugin, it gives me this error.

![Screenshot_20220121_113954](https://user-images.githubusercontent.com/39960656/150475421-60a59877-74a8-4f15-ad00-7156a7e441a7.png)

**Comment by Shubham82** [comment]
Hi @karan316
The URL  used by you is wrong. In your URL you put a backslash (\) in two places one is after **$** and the second after **stable.txt** 
see below:
`curl -LO https://dl.k8s.io/release/$\(curl -L -s https://dl.k8s.io/release/stable.txt\)/bin/linux/amd64/kubectl-convert`

Correct one is: 
`curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert`

**Comment by jihoon-seo** [comment]
For me,
there seems no backslashes in the command,
![image](https://user-images.githubusercontent.com/46767780/150478871-6a8b0f3c-1ef9-41f1-a1e3-e8717c6297a0.png)

but when I copy that and paste, the backslashes appear.

![image](https://user-images.githubusercontent.com/46767780/150479004-37291499-32c2-487c-99a6-6a0930dc688e.png)

(Copied in Windows 10 x64, Chrome 97.0.4692.71,
pasted to the Oracle Virtualbox VM, Ubuntu 18.04 desktop x64, bundled Terminal app)

---

In that page, 
replacing `curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert` 
to `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert"` 
might resolve the problem.

![image](https://user-images.githubusercontent.com/46767780/150479264-37b762a9-8ffc-4db3-8bfb-28a76105a7ed.png)
(This one causes no problem.)

/kind bug
/triage accepted

**Comment by Shubham82** [comment]
Hi @jihoon-seo
when I do copy and paste it, the backslash does not appear in the command.

> ~$ curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert

**Comment by jihoon-seo** [comment]
Maybe `zsh` automatically adds backslashes..

I am using `zsh`, and I guess that @karan316 is using `zsh` too. (@karan316 Is this correct? 😊)

And It seems that @Shubham82 you are using other than `zsh`, @Shubham82 Is this correct? 😊

---

If these are correct, 
then I guess that replacing to `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert"` will cause no problem on `bash`, `zsh`, and so on.

**Comment by Shubham82** [comment]
Hi @jihoon-seo 

> And It seems that @Shubham82 you are using other than `zsh`, @Shubham82 Is this correct? blush

yes, I am using the bash, maybe it is with zsh.

> If these are correct, then I guess that replacing to `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert"` will cause no problem on `bash`, `zsh`, and so on.

I tried this command and it is also working, so we can replace the command with `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert"`

**Comment by karan316** [comment]
> Maybe `zsh` automatically adds backslashes..
> 
> I am using `zsh`, and I guess that @karan316 is using `zsh` too. (@karan316 Is this correct? blush)
> 
> And It seems that @Shubham82 you are using other than `zsh`, @Shubham82 Is this correct? blush
> 
> If these are correct, then I guess that replacing to `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl-convert"` will cause no problem on `bash`, `zsh`, and so on.

Yup, I am using zsh as well
