### ISSUE TITLE
[zh] kubelet options "register-with-taints" is DEPRECATED?

### ISSUE THREAD

**Issue by zzzzoy** [kubernetes/website#31459]
In chinese document the option register-with-taints is DEPRECATED, I wonder if this is a translation mistake

--register-with-taints mapStringString
--
  | 设置本节点的污点标记，格式为 <key>=<value>:<effect>， 以逗号分隔。当 --register-node 为 false 时此标志无效。 **已弃用：将在未来版本中移除。**

--
  | Register the node with the given list of taints (comma separated <key>=<value>:<effect>). No-op if --register-node is false.

**Comment by jihoon-seo** [comment]
@xzyangNB It would be great to assign yourself to the issue before you start working on. 😊

/assign @xzyangNB

**Comment by xzyangNB** [comment]
> @xzyangNB It would be great to assign yourself to the issue before you start working on. blush
> 
> /assign @xzyangNB

Well, thank you
