### ISSUE TITLE
Remove cinder from content/en/docs/concepts/storage/persistent-volumes.md 

### ISSUE THREAD

**Issue by gamba47** [kubernetes/website#31467]
**Problem:**
I'm working on spanish translation of content/en/docs/concepts/storage/persistent-volumes.md 

I saw at least 11 times cinder witch is deprecated in 1.18 release as says line 374

**Proposed Solution:**
I will remove those lines based on this deprecation on english and spanish versions and make both prs. Maybe others groups will do the same after this change.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by gamba47** [comment]
Hi @raelga you will do this pr? please let me know if i can help.

Emiliano

**Comment by jihoon-seo** [comment]
- Resolving PR: #31515

**Comment by gamba47** [comment]
Hi guys! thanks for your time. I will close this issue since there is a pr.
