### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/ingress-controllers/

### ISSUE THREAD

**Issue by cawoodm** [kubernetes/website#31465]
The [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend) document links [here](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) saying:
>  The defaultBackend is conventionally a configuration option of the Ingress controller and is not specified in your Ingress resources.

However, there is no information on the ingress controllers page about how to configure the default backend.

**Comment by sftim** [comment]
Looks like an area that could use improvement.
/language en
/kind feature
/sig network

An interim improvement would be to update https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend, copying the wording from the API reference, with minor tweaks:
> `.spec.defaultBackend` is the backend that should handle requests that don't match any rule. If no `.spec.rules` are specified, `.spec.defaultBackend` **must** be specified. If `defaultBackend` is not set, the handling of requests that do not match any of the rules will be up to the ingress controller (consult the documentation for your ingress controller to find out how it handles this case).

/help

Anyone picking this up is welcome to use that suggested wording as-is. You are also welcome to go beyond that and add more explanation, or perhaps a flowchart [using Mermaid](https://www.kubernetes.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/)?

/priority backlog

**Comment by sftim** [comment]
@cawoodm thanks for reporting this!

**Comment by sftim** [comment]
New to Kubernetes docs and want to help? Check out https://kubernetes.io/docs/contribute/new-content/#contributing-basics

**Comment by PriyanshuAhlawat** [comment]
will like to work on it
/assign

**Comment by jihoon-seo** [comment]
- Related PR: #31492

/triage accepted
