### ISSUE TITLE
What is Kubernetes?

### ISSUE THREAD

**Issue by UtkarshMishra12** [kubernetes/website#31462]
Hi, I'm interested in correcting the 18 errors (grammatical : including punctuation, comma, etc) in [https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/](url) in this page.

**Comment by anubha-v-ardhan** [comment]
What are the errors like. Can you give some examples please

**Comment by UtkarshMishra12** [comment]
**Virtualized deployment era** -> Comma after _virtualization_ , unnecessary _own_ before the operating system.
**Container deployment era** -> Unnecessary _own_ before filesystem, missing _the_ before share.
**Kubernetes provides you with** -> Making the first word start with a  _Capital Letter_ in the sub-heading, again unnecessary _own_ in between the sentences.
**What Kubernetes is not**-> Replacing _Does_ with _Do_ in the sentences
<br>
These are some changes that will make the documentation more meaningful to the reader.

**Comment by anubha-v-ardhan** [comment]
> Virtualized deployment era -> Comma after virtualization , unnecessary own before the operating system.

I think comma after virtualization maybe justified
I would prefer having own before operating system to make the doc more clear

> Container deployment era -> Unnecessary own before filesystem, missing the before share

I would prefer having own before filesystem to make the doc more clear
I'm afraid the is not required before share. Thoughts?

> Kubernetes provides you with -> Making the first word start with a Capital Letter in the sub-heading, again unnecessary own in between the sentences.

Capitalizing first letters maybe justified
I would again prefer own for more clarity

> What Kubernetes is not-> Replacing Does with Do in the sentences
I think using does make more grammatical sense. Thoughts?

**Comment by sftim** [comment]
/language en
/priority awaiting-more-evidence

This would be easier to review as a pull request. @UtkarshMishra12 you're welcome to open one but I would want to caution you that the current page looks basically fine. There are other issues that are more important to the Kubernetes project (that we'll prioritize work on, and reviews for).

I think it's fine to leave the existing page as is in terms of grammar.
