### ISSUE TITLE
[ja] Translate a-guide-to-admission-controller into Japanese

### ISSUE THREAD

**Issue by aquiladayc** [kubernetes/website#31476]
This is a Feature Request

What would you like to be added
Translate [blog/a-guide-to-admission-controller](https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/) into Japanese

Why is this needed
This page has not been translated.

Comments
/language ja
/assign

**Comment by jihoon-seo** [comment]
/triage accepted
/retitle [ja] Translate a-guide-to-admission-controller into Japanese
