### ISSUE TITLE
Add a section on multi-tenancy best practices and projects

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/website#31479]
**This is a Feature Request**

**What would you like to be added**

A section in the Kubernetes documentation to provide users with best practice guidelines and references to Kubernetes projects and solutions for multi-tenancy. This can be a new section in [Concepts](https://kubernetes.io/docs/concepts/).

**Why is this needed**

Kubernetes is commonly used by multiple teams and to run multiple applications. The [Kubernetes Multi-Tenancy WG](https://github.com/kubernetes/community/blob/master/wg-multitenancy/README.md) has been chartered with defining multi-tenancy models for Kubernetes and making these easy to consume for end users.

The group has produced multiple projects like [HNC](https://github.com/kubernetes-sigs/hierarchical-namespaces), [Virtual Clusters](https://github.com/kubernetes-sigs/cluster-api-provider-nested/tree/main/virtualcluster), and [Benchmarks ](https://github.com/kubernetes-sigs/multi-tenancy/tree/master/benchmarks)and published blog posts on [Kubernetes tenancy models](https://kubernetes.io/blog/2021/04/15/three-tenancy-models-for-kubernetes/) and the projects ([HNC](https://kubernetes.io/blog/2020/08/14/introducing-hierarchical-namespaces/), [Virtual Clusters](https://www.cncf.io/blog/2019/06/20/virtual-cluster-extending-namespace-based-multi-tenancy-with-a-cluster-view/)). 

The HNC and Virtual Cluster projects have “graduated” from the working group and are now managed under SIG-auth and SIG-cluster-lifecycle. 

However, multi-tenancy remains a confusing and complex topic for Kubernetes users, especially beginners. Having a section on multi-tenancy in the Kubernetes documentation, with links to projects, would be helpful to all users.

**Comments**

If this seems like a good idea, the Multi-Tenancy WG can take the lead to propose a draft document.

cc: @tashimi @adrianludwin @Fei-Guo @rjbez17

**Comment by sftim** [comment]
Happy for multitenancy WG to take this forward - also, that WG is welcome to triage this as accepted.

Please also explore whether you can put new content within three of the existing sections:
- https://kubernetes.io/docs/concepts/architecture/
- https://kubernetes.io/docs/concepts/extend-kubernetes/
- https://kubernetes.io/docs/concepts/cluster-administration/

and, that way, avoid adding a new section to the concept list - we already have quite a few.

of course, it's also fine to add new Task or Reference pages that cover multi-tenancy aspects.

**Comment by tashimi** [comment]
👍

**Comment by adrianludwin** [comment]
See also https://github.com/cncf/tag-app-delivery/issues/193
