### ISSUE TITLE
Kubectl set env from secret leads to uppercase of the secret keys

### ISSUE THREAD

**Issue by ThuF** [kubernetes/website#31489]
As proposed by @sftim, I'm opening an issue for the Kubernetes Website, to address a limitation/bug of the **kubectl**:

---

### What happened?

I have a **Secret** created by the following command: 
```
kubectl -n <namespace-name> create secret generic xsuaa-credentials \
--from-literal=url='<xsuaa-url>' \
--from-literal=clientid='<xsuaa-clientid>' \
--from-literal=clientsecret='<xsuaa-clientsecret>' \
--from-literal=verificationkey='<xsuaa-verificationkey>' \
--from-literal=xsappname='<xsuaa-xsappname>'
```
> **_Note:_** The secret keys are in lowercase.

I'm binding the secret to a **Deployment** with the following command:

```
kubectl -n <namespace-name> set env --from=secret/xsuaa-credentials deployment/xsk
```

When describing the deployment I get the following output:

```
Name:                   xsk
Namespace:              xsk-demo-sdi
CreationTimestamp:      Fri, 14 Jan 2022 18:27:12 +0200
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 2
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"xsk","namespace":"xsk-demo-sdi"},"spec":{"replicas":1,"se...
Selector:               app=xsk
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=xsk
  Containers:
   xsk:
    Image:      dirigiblelabs/xsk-kyma:latest
    Port:       8080/TCP
    Host Port:  0/TCP
    Environment:
      URL:                      <set to the key 'url' in secret 'xsuaa-credentials'>              Optional: false
      VERIFICATIONKEY:          <set to the key 'verificationkey' in secret 'xsuaa-credentials'>  Optional: false
      XSAPPNAME:                <set to the key 'xsappname' in secret 'xsuaa-credentials'>        Optional: false
      CLIENTID:                 <set to the key 'clientid' in secret 'xsuaa-credentials'>         Optional: false
      CLIENTSECRET:             <set to the key 'clientsecret' in secret 'xsuaa-credentials'>     Optional: false
```

Where the environment variables are in uppercase:
- clientid &#8594; CLIENTID
- clientsecret &#8594; CLIENTSECRET
- verificationkey &#8594; VERIFICATIONKEY
- xsappname &#8594; XSAPPNAME

### What did you expect to happen?

The environment variables to be in lowercase, as they are defined in the secret.

---

Related to issue: https://github.com/kubernetes/kubernetes/issues/107562

**Comment by ThuF** [comment]
As [commented](https://github.com/kubernetes/kubernetes/issues/107562#issuecomment-1017782951) by @sftim:

> At a minimum, we should clearly document this behavior (consider opening an issue against k/website to request that).
> It would also be useful to have kubectl emit a warning that it has rewritten the keys to uppercase.

**Comment by a-mccarthy** [comment]
Thanks for filing @ThuF, this is definitely something we should have a note about. I think we should update, https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/ but there might be more pages. Do you have any other suggested pages where we should make this update?

/remove-kind bug

/triage accepted
/kind feature
/language en

**Comment by ThuF** [comment]
Hi @a-mccarthy, I think we should update also the following pages:
- https://kubernetes.io/docs/reference/kubectl/cheatsheet/
- https://kubernetes.io/docs/concepts/configuration/secret/
- https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/

**Comment by sftim** [comment]
I can't see where on https://kubernetes.io/docs/reference/kubectl/cheatsheet/ we'd mention this gotcha. Updating https://kubernetes.io/docs/reference/kubectl/cheatsheet/ makes sense to me.
For https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kubectl/, perhaps we could hyperlink to https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/ and rely on people following that link?

**Comment by sftim** [comment]
Was this a kubectl bug or an intended behavior?
/remove-lifecycle rotten

**Comment by ckhordiasma** [comment]
/remove-lifecycle rotten

just ran into this today. maybe a few sentences could be added on this page in the examples that involve a secret? https://kubernetes.io/docs/reference/kubectl/generated/kubectl_set/kubectl_set_env/
