### ISSUE TITLE
[zh]  A translation problem was found in  /content/zh/includes/user-guide-content-moved.md

### ISSUE THREAD

**Issue by xzyangNB** [kubernetes/website#31484]
**This is a Bug Report**

In  /content/zh/includes/user-guide-content-moved.md. 
I think it's better to translate "user guide" into “用户指南”

**Comment by jihoon-seo** [comment]
File: https://github.com/kubernetes/website/blob/main/content/zh/includes/user-guide-content-moved.md?plain=1
/language zh
