### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-linux/

### ISSUE THREAD

**Issue by Chaz6** [kubernetes/website#31491]
The current documentation for Red Hat refers to version 7 but the current version is 8, and there is no equivalent repository at https://packages.cloud.google.com/yum/repos/kubernetes-el8-x86_64

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management

**Comment by mk46** [comment]
Hi @Chaz6, You can build `kubectl` by source with below steps
```
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
make WHAT=cmd/kubectl
cd _output/bin
./kubectl --<whatever you want>
```

**Comment by divya-mohan0209** [comment]
@Chaz6 the documentation reflects the current state of affairs correctly afaik.
/sig cluster-lifecycle
