### ISSUE TITLE
Document SOCKS5 proxy mode for kubectl

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31497]
**This is a Feature Request**

**What would you like to be added**
Document how to set up `kubectl` to make use of a SOCKS proxy when interacting with a workload running on your cluster.
The page should briefly explain what SOCKS is - a link to further reading is fine - and outline how the SOCKS proxy fits in. A diagram would be really helpful too. See https://www.k8s.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/ for one approach to that diagram.

**Why is this needed**
https://github.com/kubernetes/kubernetes/pull/105632 added support for using a SOCKS proxy for some `kubectl` subcommands, but there's no page explaining how to make use of that new feature.

**Comments**
Assuming that these changes will go into Kubernetes 1.24, the pull request to add these docs should target the _dev-1.24_ branch.
/sig cli
/language en

**Comment by sftim** [comment]
@xens, would you be willing to check the issue description and see if anything needs amending / adding / removing?

If you could also find time (or people!) to help document the new feature, even better.

**Comment by xens** [comment]
@sftim sure I can give it a try !

**Comment by xens** [comment]
I just pushed the first iteration inside #31527, based on the `main` branch, let me know if I need to switch to the `dev-1.24` branch. Also I'm not sure if there's a way to have a preview of the compiled file ? I've added a Mermaid diagram and I'm not sure if it'll render properly.

**Comment by mehabhalodiya** [comment]
Hey @xens

> I just pushed the first iteration inside #31527, with main as the target branch, let me know if I need to switch to the dev-1.24 branch instead.

No need to switch to the `dev-1.24`. All good!

> Also I'm not sure if there's a way to have a preview of the compiled file? I've added a Mermaid diagram and I'm not sure if it'll render properly.

Yes, you can browse the preview. The [link](https://github.com/kubernetes/website/pull/31527#issuecomment-1022560425) is available. 
Head over to the particular location where you have done the changes and you will be able to see everything. In this case: https://deploy-preview-31527--kubernetes-io-main-staging.netlify.app/docs/tasks/extend-kubernetes/socks5-proxy-access-api/

Let me know if you face any issue.
Thank you.

**Comment by xens** [comment]
thanks @mehabhalodiya I've seen the netlify bot link after posting my comment :+1:

**Comment by jihoon-seo** [comment]
Resolved by #31527.
/close
