### ISSUE TITLE
Advice on using CronJob with Kubernetes v1.20

### ISSUE THREAD

**Issue by mickleissa** [kubernetes/website#31507]
Hello, 
In the example CronJob the apiVersion: batch/v1 not working with v1.20
when I created Imperative CronJob the apiVersion: batch/v1beta1 worked fine with v1.20

Thank you.

**Comment by sftim** [comment]
/retitle Advice on using CronJob with Kubernetes v1.20
/kind support 

@mickleissa if you're reading https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ then that documentation is for v1.23

Try reading https://v1-20.docs.kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ instead? (there is a drop-down near the top right of the desktop view where you can pick which version you're viewing)
