### ISSUE TITLE
[zh] Resync "Configure Multiple Schedulers"

### ISSUE THREAD

**Issue by kernelv5** [kubernetes/website#31502]
--lock-object-name this information is missing, i compare with Chinese version page

**Comment by kernelv5** [comment]
- --scheduler-name information also missing

**Comment by jihoon-seo** [comment]
- en: https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/ (Last modified December 08, 2021)
- zh: https://kubernetes.io/zh/docs/tasks/extend-kubernetes/configure-multiple-schedulers/ (Last modified May 06, 2021)

I guess that the Chinese one is outdated so needs update. 😊

/language zh
/retitle [zh] Resync "Configure Multiple Schedulers"
/kind bug
/triage accepted
