### ISSUE TITLE
Wrong footer rendering

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#31509]
**This is a Bug Report**

**Problem:**
(Despite the PR #31277 has been merged, it seems that the error still exists. 🤔
So opening an issue here. 😊)

From the PR #31277:

> The [community page](https://kubernetes.io/community/) has the wrong rendering for the page footer.
> We should:
> - ensure that the footer is as wide as the viewport.
> - improve how the text in the footer is laid out when the viewport is quite wide.

[As-is]
![image](https://user-images.githubusercontent.com/46767780/148865726-c3ea26b3-a3f8-4978-a953-5badbc718a93.png)
![image](https://user-images.githubusercontent.com/46767780/148865750-f4bcdb00-0126-4c3f-8d17-4d4fd0724fea.png)

[To-be]
![image](https://user-images.githubusercontent.com/46767780/148865788-e2fc77b8-06de-4670-818d-fe86024a3dfd.png)
![image](https://user-images.githubusercontent.com/46767780/148865810-6d2e213c-b67b-40f3-ba72-ccc143a2ae7c.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/community/

CC @sftim
/area web-development

**Comment by ravikiranr26** [comment]
Hello @jihoon-seo Thanks for reporting this issue. May i kindly know some more details to reproduce the issue. 
1) Browser & Version ?
2) Resolution of your display ?

I'm trying to reproduce it on wide viewport 
![image](https://user-images.githubusercontent.com/1841796/151217813-7b861ee9-04c6-4cae-8fa4-9598a39c69f8.png)

**Comment by jihoon-seo** [comment]
Hello @ravikiranr26 😊

Here is the info of my env:

- Windows 10 Enterprise 20H2
- Google Chrome 97.0.4692.99 (64bit)
- Monitor resolution: 3840 * 1600

Chrome window size:

[1868 * 1592]
![image](https://user-images.githubusercontent.com/46767780/148865726-c3ea26b3-a3f8-4978-a953-5badbc718a93.png)
[1868 * 1592]

---

[3767 * 1600]
![image](https://user-images.githubusercontent.com/46767780/148865750-f4bcdb00-0126-4c3f-8d17-4d4fd0724fea.png)
[3767 * 1600]

**Comment by sftim** [comment]
I can replicate this with Chromium and with Firefox.

**Comment by ravikiranr26** [comment]
@jihoon-seo  Thanks for the information. @sftim Please can you assign this issue to me.

**Comment by sftim** [comment]
@ravikiranr26 try this Prow command: /assign ravikiranr26
(reply in a comment with that command on a line by itself)
