### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by b4rsch** [kubernetes/website#31508]
I am running the first commands of this tutorial to setup the ip tables but when I try to run the command `sudo sysctl --system` I'm getting the following errors:
```
* Applying /etc/sysctl.d/k8s.conf ...
sysctl: setting key "net.bridge.bridge-nf-call-ip6tables": No such file or directory
sysctl: setting key "net.bridge.bridge-nf-call-iptables": No such file or directory
```

Obviously, there is missing some file or something, but I don't know where this should be and what.

I'm on Centos 7, freshly installed

**Comment by neolit123** [comment]
hi, as discovered in this prior issue:
https://github.com/kubernetes/website/issues/26503#issuecomment-778831615

`sysctl --system` works despite the warnings, and the recommended tool `systemd-sysctl` prints even more warnings.
seems to be a distro problem.

/sig cluster-lifecycle
/kind support
/close

**Comment by neolit123** [comment]
actually see this:
https://github.com/kubernetes/website/issues/26503#issuecomment-778834044

> sudo sysctl net.bridge.bridge-nf-call-iptables

^ you can verify the keys using this command.

**Comment by b4rsch** [comment]
> > sudo sysctl net.bridge.bridge-nf-call-iptables
> 
the keys are still set to `0`

**Comment by neolit123** [comment]
/reopen

does this fix work for you?
https://gist.github.com/iamcryptoki/ed6925ce95f047673e7709f23e0b9939

**Comment by b4rsch** [comment]
No this doesn't work either.

```
~]# sysctl -p /etc/sysctl.conf
sysctl: setting key "net.bridge.bridge-nf-call-iptables": No such file or directory
```

**Comment by neolit123** [comment]
is the module loaded?
> Make sure that the br_netfilter module is loaded. This can be done by running lsmod | grep br_netfilter. To load it explicitly call sudo modprobe br_netfilter.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic

**Comment by b4rsch** [comment]
the module is loaded but I am a bit confused about the `used by` column. Every process is used by `-2`
```
# lsmod|grep br_netfilter
br_netfilter            4242  -2 
bridge                  4242  -2 br_netfilter

```

**Comment by b4rsch** [comment]
fyi I'm on a virtual host if it matters

**Comment by neolit123** [comment]
i'm not sure what -2 means here. running in a VM should not matter.
you can try `s/sysctl/systemd-sysctl` and see if that works. `systemd-sysctl` worked for me the last time i tested it, but it was on Ubuntu.

**Comment by b4rsch** [comment]
huh the service seems to fail

```
~]# systemctl status systemd-sysctl.service
● systemd-sysctl.service - Apply Kernel Variables
   Loaded: loaded (/usr/lib/systemd/system/systemd-sysctl.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Di 2022-01-25 23:24:44 CET; 12s ago
     Docs: man:systemd-sysctl.service(8)
           man:sysctl.d(5)
  Process: 571 ExecStart=/usr/lib/systemd/systemd-sysctl (code=exited, status=1/FAILURE)
 Main PID: 571 (code=exited, status=1/FAILURE)

systemd[1]: Starting Apply Kernel Variables...
systemd[1]: systemd-sysctl.service: main process exited, ...URE
systemd[1]: Failed to start Apply Kernel Variables.
systemd[1]: Unit systemd-sysctl.service entered failed state.
systemd[1]: systemd-sysctl.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

```

**Comment by b4rsch** [comment]
the `/etc/sysctl.d/99-sysctl.conf` and `/etc/sysctl.conf` files are completely empty except for the line I wrote in testing the one command you proposed

**Comment by neolit123** [comment]
systemd-sysctl failing to start is not great.

you could try adding the `key=1` entries manually in the `/etc/sysctl.d/foo.conf` files.
then `sysctl net.bridge.bridge-nf-call-ip{6}tables` should show `1`.

also, googling for `"sysctl: setting key" "No such file or directory"` does not reveal many results and given we already have centos7 users, i wonder if something has bugged out with `*-sysctl` in your particular case.

sorry, i don't think i can help further here, but you can try the support channels where a linux / centos expert might see your ask:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by b4rsch** [comment]
Nevertheless, thanks for your help. Maybe I'll just try on ubuntu
