### ISSUE TITLE
v1.23.3 missing from release details

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31501]
**This is a Bug Report**

**Problem:**
There ~is~ soon will be an out of band v1.23.3 release - see https://groups.google.com/a/kubernetes.io/g/dev/c/Xl1sm-CItaY - and the releases page should mention it.

**Proposed Solution:**
Update the releases page to mention v1.23.3

To change that, edit the data within https://github.com/kubernetes/website/tree/main/data/releases

**Pages to Update:**
- https://kubernetes.io/releases/

**Kubernetes Version:**
v1.23.3

**Additional Information:**
/sig release
/priority important-soon

**Comment by sftim** [comment]
Related to #31494

**Comment by Babapool** [comment]
Hi, I would like to work on this issue.
/assign

**Comment by sftim** [comment]
https://kubernetes.io/releases/ now _is_ out of date as v1.23.3 is live - see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#v1233
