### ISSUE TITLE
Issue with 'kubectl completion powershell'

### ISSUE THREAD

**Issue by east4ming** [kubernetes/website#31510]
kubectl completion powershell
error: Unsupported shell type "powershell".
See 'kubectl completion -h' for help and examples

**Comment by jihoon-seo** [comment]
EN page: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/

It seems that you can use `kubectl completion powershell` with `kubectl` v1.23~.

If you are using `kubectl` ~v1.22, then you cannot use `kubectl completion powershell`.

Please run `kubectl version`, and copy & paste the result to here!

For example:

```
❯ kubectl version                                            
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-21T02:19:59Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
```

/kind support
/retitle Issue with 'kubectl completion powershell'

**Comment by east4ming** [comment]
> EN page: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/
> 
> It seems that you can use `kubectl completion powershell` with `kubectl` v1.23~.
> 
> If you are using `kubectl` ~v1.22, then you cannot use `kubectl completion powershell`.
> 
> What is the version of `kubectl` you are using? Please run `kubectl version`, and copy & paste the result to here!
> 
> For example:
> 
> ```
> ❯ kubectl version                                            
> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-21T02:19:59Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> /kind support /retitle Issue with 'kubectl completion powershell'

Thank you! 
My version is 1.22, I will update to 1.23

**Comment by jihoon-seo** [comment]
It seems that this issue has been resolved and okay to close. 😊
/close
