### ISSUE TITLE
[fr] Broken link in docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by tapter-mwm** [kubernetes/website#31535]
Hi. 

On this section of the french Ingress documentation, https://kubernetes.io/fr/docs/concepts/services-networking/ingress/#la-ressource-ingress, there seems to be a dead link at _la specification de la ressource ingress_. 

French version seems outdated in comparaison with the english one. 

Cheers 🇫🇷

**Comment by anubha-v-ardhan** [comment]
Thank you for reporting this

The correct link should be: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

/triage accepted
/good-first-issue

**Comment by praveenrewar** [comment]
I would like to take this up.

**Comment by anubha-v-ardhan** [comment]
/retitle [fr] Broken link in docs/concepts/services-networking/ingress/

**Comment by anubha-v-ardhan** [comment]
/assign @praveenrewar 
Thank you :)
