### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by 916** [kubernetes/website#3153]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Suspected minor bug in sample command:
kubectl apply -n sock-shop -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"

The switch '-n' should be for the kubectl base command according to kubectl options (not documented for sub command apply)

**Proposed Solution:**
Move the switch to the base command. :-)

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by ahmetb** [comment]
Global arguments like `-n/--namespace` apply to the subcommands as well. In `kubectl apply -h` you will see at the end:

    Use "kubectl options" for a list of global command-line options (applies to all commands).

So this is valid. You can do both `kubectl -n foo apply` or `kubectl apply -n foo`.
