### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by alexisgaziello** [kubernetes/website#31544]
Although the recommended driver for Minikube is Docker, this tutorial doesn't work with Docker as a driver.

I lost some time until I restarted Minikube with:
`minikube start --driver=virtualbox `

I think the driver needed to complete the tutorial should be indicated.

**Comment by RA489** [comment]
@alexisgaziello I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!
