### ISSUE TITLE
Add multi-container info on docs/tasks/debug-application-cluster/determine-reason-pod-failure

### ISSUE THREAD

**Issue by brunosaboia** [kubernetes/website#31543]
**This is a Feature Request**

**What would you like to be added**
The `go-template` example works well for a single-container pod. However, it is important for multi-container pods to know _which_ container failed.

The following `kubectl` command would show which container failed within the pod:

```kubectl get pod termination-demo -o go-template='{{range .status.containerStatuses}}{{printf "%s:\n%s\n\n" .name .lastState.terminated.message}}{{end}}'```

**Why is this needed**
Because the current command only shows the error message, not which container is failing — thus confusing if it is a multi-container pod.

This change will hopefully help people running multi-container pods figuring out the faulty container. 

**Comments**

None.

**Comment by Rohan749** [comment]
Hello developers! 
I want to contribute to this issue and give info about multi-container info. 
If anyone can guide me to the resources, it would be really helpful.

**Comment by brunosaboia** [comment]
Hello @Rohan749 , thanks for your help.

You can take a look at the PR created [here](https://github.com/kubernetes/website/pull/31768), and see if you find anything odd.

If so, please comment or add a patch to it. Thanks!

**Comment by Rohan749** [comment]
Okay!
