### ISSUE TITLE
Wrong capitalization for volume types

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31540]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options lists some volume types. The capitalization is wrong.

**Proposed Solution:**
Update the capitalization of the volume types listed in https://kubernetes.io/docs/concepts/storage/persistent-volumes/#mount-options to match the capitalization used in https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Additional Information:**
/sig storage

**Comment by yashodhanmohan** [comment]
I've raised a PR for this.

/assign

**Comment by yashodhanmohan** [comment]
The PR is merged so this can be resolved I guess.

**Comment by Stergios13** [comment]
Hello. i would like to contribute. I am a newcomer but i know some html code in order to correct the capitalization you ask for.

**Comment by sftim** [comment]
/close

Fixed in #31542
