### ISSUE TITLE
Old versions of “Upgrade A Cluster” report wrong version details

### ISSUE THREAD

**Issue by kohtala** [kubernetes/website#31551]
https://v1-21.docs.kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/ has the header "You are viewing documentation for Kubernetes version: v1.21". However the content tells "This page is about upgrading from Kubernetes 1.22 to Kubernetes 1.23. If your cluster is not currently running Kubernetes 1.22 then please check the documentation for the version of Kubernetes that you plan to upgrade to." This content seems to be the same for all versions you can select from the upper right corner.

[moved to #31583] ~~Similarly https://v1-21.docs.kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/ has the header, but contains securityContext.allowPrivilegeEscalation. I have a cluster in 1.21.7 version in AKS, but `kubectl explain Pod.spec.securityContext` does not list the field.~~

**Comment by jihoon-seo** [comment]
/triage accepted
/kind bug

Related issues:
- #27525
- #28000
- #29467
- #29520
- #29538
- #29725

Related PRs:
- ~#27540~
(see #29746 instead)
- ~#27541~
(see #29746 instead)
- ~#27542~
(see #29746 instead)
- #29009
- #29746
- #29754
- #29758

**Comment by sftim** [comment]
I have a feeling this is two separate issues.

@kohtala would you be willing to file a separate issue about the inaccurate API reference for v1.21? We can leave this one to cover the misleading version details in old versions of https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/

**Comment by kohtala** [comment]
Thank you. I created new issue #31583.

**Comment by sftim** [comment]
/priority important-longterm
/retitle Old versions of “Upgrade A Cluster” report wrong version details
/language en

**Comment by sftim** [comment]
When we make a fix, we will need to backport it to previous versions of the documentation.

**Comment by jihoon-seo** [comment]
The PR #34346 has resolved this issue for v1.21 docs.
/close
