### ISSUE TITLE
Linux 系统中的 bash 自动补全功能

### ISSUE THREAD

**Issue by omaidb** [kubernetes/website#31555]
Ubuntu18.04按照教程配置完kubectl自动补全后,按下tab键,不能补全,而且报错.
![image](https://user-images.githubusercontent.com/18365223/151566374-f8a196b9-4b44-433c-b915-f2066781cb30.png)

**Comment by jihoon-seo** [comment]
See: https://stackoverflow.com/questions/50406142/kubectl-bash-completion-doesnt-work-in-ubuntu-docker-container
/kind support

**Comment by omaidb** [comment]
```bash
apt-get update && apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubectl
echo 'source <(kubectl completion bash)' >> ~/.bashrc
```

**Comment by Sea-n** [comment]
As [previous comment](https://github.com/kubernetes/website/issues/31555#issuecomment-1032114695), the problem have been resolved.
/close
