### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/

### ISSUE THREAD

**Issue by abhinavkshitij** [kubernetes/website#31561]
NodePort does not work when I replicate the same tutorial on my MacBook with Docker, although this issue does not arise with hyperkit. I am quite sure I have followed the steps outlined in the tutorial but the curl-ing into the minikube ip:$NODE_PORT hangs up every single time.

Steps:
`minikube start --disk-size 2000mb`
`kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1`
`kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080`
`export NODE_PORT=$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')`
`curl $(minikube ip):$NODE_PORT`

hangs

**Comment by sftim** [comment]
This _might_ be more of a docs issue than a support request. I'm not sure.

@abhinavkshitij am I right that you can follow the tutorial OK using the online console, but not locally?

**Comment by vickykushwaha** [comment]
triage/accepted
