### ISSUE TITLE
Remove page “Reconfigure a Node's Kubelet in a Live Cluster”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31585]
**This is a Cleanup Request**

**What would you like to be removed**
Remove https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/

**Why is this needed**
v1.24 of Kubernetes will remove the dynamic kubelet config feature (deprecated since Kubernetes v1.22)

**Comments**
/sig node
/language en
/milestone 1.24

**Comment by sftim** [comment]
See https://github.com/kubernetes/kubernetes/pull/106932

**Comment by sftim** [comment]
BTW Any PR for this should target the branch _dev-1.24_

**Comment by MdSahil-oss** [comment]
> BTW Any PR for this should target the branch _dev-1.24_

Okay... But I want to clear that you want me to remove the entire page https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ from "Administer a Cluster" . Am I Right ?

**Comment by nate-double-u** [comment]
This won't be in 1.24's docs, clearing the milestone. This can be added to subsequent milestones if needed. (or closed if I'm missing a PR somewhere)
/milestone clear

**Comment by sftim** [comment]
We should have updated the page to state when the removal _is_ due, or to remove the commitment if we're no longer sure.

**Comment by sftim** [comment]
/label good-first-issue

All you need to do is remove https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ from the docs.

**Comment by sftim** [comment]
/good-first-issue


https://github.com/kubernetes/enhancements/blob/2cd758cc6ab617a93f578b40e97728261ab886ed/keps/sig-node/281-dynamic-kubelet-configuration/kep.yaml states that the feature was removed.

@nate-double-u why did we take this change out of the v1.24 milestone?

**Comment by hamees-sayed** [comment]
@sftim should I also remove all the links that lead to [/content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md]?(https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md)  

for example, here: [at the bottom, how can I learn more](https://github.com/kubernetes/website/blob/f6b4fedd70632144f25d661b63af2ff0f251e315/content/en/blog/_posts/2018-07-11-dynamic-kubelet-configuration.md#how-can-i-learn-more)

**Comment by sftim** [comment]
> @sftim should I also remove all the links that lead to `/content/en/docs/tasks/administer-cluster/reconfigure-kubelet.md`

Not **required**, but much better if you do.

**Comment by hamees-sayed** [comment]
hey, @sftim I have made the required changes in the PR, could you please review it?

**Comment by Karthik-PM** [comment]
can i work on this issue as well?

**Comment by sftim** [comment]
@Kart121 

> can i work on this issue as well?

You're welcome to. The next step on contributing is to review https://github.com/kubernetes/website/pull/37268

**Comment by Kart121** [comment]
> @Kart121
> 
> > can i work on this issue as well?
> 
> You're welcome to. The next step on contributing is to review #37268

will do !

**Comment by debdeepsanyal** [comment]
hey @sftim , this is my contribution and i would be glad to help and have an insight. can you tell me what to do? im new, just trying to get familiar with all of this

**Comment by sftim** [comment]
How to work on this:
Please open a PR that removes https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/

If there are any other English pages that link to https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ then please turn the links into plain text, or otherwise fix them up.

**Comment by Bhavya031** [comment]
The issue has been resolved. all [https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/](url) are removed or commented out. still there are some mention of this like but they there only to point out that the dynamic kubelet config is removed from v1.24.

**Comment by mehabhalodiya** [comment]
@championshuttler I don't see any updates from your side; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @championshuttler

**Comment by Bhavya031** [comment]
@mehabhalodiya i think this issue is resolved.

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya i think this issue is resolved.

@Bhavya031 If [this comment](https://github.com/kubernetes/website/issues/31585#issuecomment-1379098470) is addressed somewhere in the PR then can you please share a link of the respective PR?

Thanks!

**Comment by Bhavya031** [comment]
Can I open pr??

**Comment by Santosh-Kumar-Perumal** [comment]
Can I work on this issue is this still open ?

**Comment by vj-codes** [comment]
@sftim heyyo can you please confirm what branch this issue fix needs to be targeted on? Thanks in advance:)

**Comment by sftim** [comment]
To remove that page, make the change to the _main_ branch.

Ideally, also find any English pages - _just_ English - that link to https://k8s.io/docs/tasks/administer-cluster/reconfigure-kubelet/ and edit them so that they don't.

**Comment by MasSica** [comment]
Hi @sftim, 
This is my first contribution to open source, I have deleted the requested page.
Should I proceed to open a pull request?

**Comment by vj-codes** [comment]
@MasSica heyyo if you don't mind I was already working on the issue and have made the changes three days ago just haven't pushed them yet

**Comment by MasSica** [comment]
@vj-codes  of course!
 I noticed you did not claim the issue with the bot so I thought I was good to go :)

**Comment by vj-codes** [comment]
update : will create a PR tomorrow.

**Comment by MaheshGayakwad** [comment]
is this issue still open ??

**Comment by abuharish02** [comment]
Hi, I want to work on this. Is this stll open ?

**Comment by sftim** [comment]
> Hi, I want to work on this. Is this still open ?

Hi. There's a white-on-green “Open” marker at the left of the top navigation, at least in the default desktop view. That indicates that the issue is open.

Anyone is welcome to suggest a fix, or to propose closing the issue if the fix has already happened.

I can see that the page https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/ is still there at the time of writing.

**Comment by paul-abhirup** [comment]
hi I can fix this issue u can assign me it.

**Comment by sftim** [comment]
> **Anyone** is welcome to suggest a fix, or to propose closing the issue if the fix has already happened.

**Comment by paul-abhirup** [comment]
where are the html file of this page in the repo
