### ISSUE TITLE
Running Automated Tasks with a CronJob

### ISSUE THREAD

**Issue by maciejburzynskigft** [kubernetes/website#31589]
Incorrect apiversion for cronjob
Currently : apiVersion: batch/v1
Correct: apiVersion: batch/v1beta1
Link : https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by sftim** [comment]
/kind support

@maciejburzynskigft make sure that you select the version of the Kubernetes documentation that matches your cluster's version of Kubernetes. Visit https://kubernetes.io/docs/home/supported-doc-versions/ to see which versions are documented.

**Comment by maciejburzynskigft** [comment]
Checking on KodeKloud env from udemy course made by @mmumshad

**Comment by sftim** [comment]
/close

Documentation for Kubernetes v1.23 correctly recommends using the generally available v1 API for CronJob.
Older Kubernetes clusters may not have the stable v1 API available, but that is not a bug in the v1.23 Kubernetes docs.
