### ISSUE TITLE
Annotation kubernetes.io/description not registered or documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31588]
**This is a Bug Report**

**Problem:**
Kubernetes [uses](https://github.com/kubernetes/kubernetes/blob/954fa57f0ead10b520328e1b936912290ced62ee/pkg/controller/certificates/rootcacertpublisher/publisher.go#L43) an annotation, `kubernetes.io/description`, that is not registered or documented.

**Proposed Solution:**
Register and document this annotation.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

Also consider whether to mention that annotation in https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Additional Information:**
/sig auth
/language en

**Comment by mk46** [comment]
I would like to work on this.
