### ISSUE TITLE
Add node-role to Well-Known Labels, Annotations and Taints

### ISSUE THREAD

**Issue by jgreat** [kubernetes/website#31592]
There doesn't seem to be any details on the `node-role.kubernetes.io/<role>` label and what I believe is now deprecated, `kubernetes.io/role` label.

I'd like to know the official guidance on setting these labels and information about deprecation of `kubernetes.io/role=master` and when `node-role.kubernetes.io/master=""` is transitioning to `node-role.kubernetes.io/control-plane=""`

**Comment by sftim** [comment]
/triage duplicate
@jgreat we have an issue about this already - would you like to help work on that?
/language en

**Comment by neolit123** [comment]
there is an open PR for these here:
https://github.com/kubernetes/website/pull/31391

**Comment by jgreat** [comment]
Thanks, that's the info I was looking for.  I'll close this one in favor of 30613.  Sorry for the noise.
