### ISSUE TITLE
Under what conditions is a pod not ready?

### ISSUE THREAD

**Issue by roy-work** [kubernetes/website#31596]
**This is a Bug Report**

**Problem:** the docs don't fully describe the circumstances under which a pod is not ready

For example, today, I had a pod transition to not ready, i.e., `status.conditions` contained,
```
{
    type:"Ready",
    status:"False",
    lastProbeTime:null,
    lastTransitionTime:"2022-02-01T14:45:23Z"
},
```
& I'd like to know why. Weirdly, in this case, all (one) containers _are_ ready, so I'm looking at something unusual.

<details>
<summary><tt>status.containerStatuses</tt> from that same Pod:</summary>

```
[
    {
        name:"<snip>",
        state:
        {
            running:
            {
                startedAt:"2022-01-29T17:25:06Z"
            }
        },
        lastState:{ },
        ready:true,
        restartCount:0,
        image:"<snip>",
        imageID:"<snip>",
        containerID:"containerd://<snip>",
        started:true
    }
],
```

</details>

**Proposed Solution:** Update the docs; what to update it to, I'm not clear on, as I'm still unsure of the answer to my question: what _is_ the complete set of reasons a Pod can be unready?

(It seems like the node-controller is what made the change… so I think we had some sort of machine or node health event, … and I'd love to know where what & why, ofc.
Edit: seems like b/c the node-controller hadn't heard from the node's kubelet long enough that we got a "Kubelet stopped posting node status"; it seems like this causes the node-controller to mark all pods on the node as not ready?)

**Page to Update:**

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

This page states:

> A Pod is considered ready when all of its containers are ready.

Which is clearly not true given the output we see, but also because another page in the docs contradicts it.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#podspec-v1-core

This page states:

> If specified, all readiness gates will be evaluated for pod readiness. A pod is ready when all its containers are ready AND all conditions specified in the readiness gates have status equal to "True"

Closer! Unfortunately, my Pod has no readiness gates, so this is still incomplete in some manner.

Kubernetes Version: v1.21.2

Additional Information: on Azure AKS.

**Comment by sftim** [comment]
/remove-kind bug
/kind feature
/language en
/sig node

My take on the feature request is: add a new reference page that lists all conditions that can apply to a Pod (and undertake to keep this up to date).
