### ISSUE TITLE
Localize Kubernetes website into Bengali

### ISSUE THREAD

**Issue by mitul3737** [kubernetes/website#31605]
We can add the Bengali language which is used spoken by more than [230 million people ](https://en.wikipedia.org/wiki/Bengali_language)

Again, we are working with CNCF's  glossary  project with the Bengali Language: https://github.com/cncf/glossary/tree/dev-bn

Please do allow me to work on the Bengali language

**Comment by sftim** [comment]
We can add that label when the work is beginning to get under way (draft PRs open from at least 2 different contributors).

**Comment by sftim** [comment]
@mitul3737 anyone can start a localization. You will need *at least* one other person who speaks the new language well, and you the people taking a lead on the work need to include reviewers who also a good understanding of English, so that you can each check one another's work.

https://kubernetes.io/docs/contribute/localization/#start-a-new-localization covers what to do.

**Comment by mitul3737** [comment]
@sftim  We have almost 4 people on our team talking in the Bengali Language. I will then start to work with the localization team

**Comment by Mouly22** [comment]
@sftim @mitul3737  I am interested

**Comment by ikramulkayes** [comment]
@sftim  @mitul3737  I want to work too.

**Comment by mitul3737** [comment]
@sftim  , we have @Mouly22 , @ikramulkayes also ready  for the task 😁

**Comment by mitul3737** [comment]
@sftim Can you create dev-1.23-bn.1 for us to work on?

**Comment by sftim** [comment]
@mitul3737 did you plan to stop the localization effort?

We can delete the branch for this work if that's the case.

**Comment by mitul3737** [comment]
@sftim No no, we are working  fine. Just closed it because I though we are now up and running and might not need this issue😅

**Comment by mitul3737** [comment]
@sftim also we have a tracking issue for our localization  and thus closed it. No intention to stop the localization  effort at all.

**Comment by sftim** [comment]
(I'd expect _this_ would be the tracking issue, TBH)

**Comment by mitul3737** [comment]
Actually  we created a tracking issue #31677

**Comment by sftim** [comment]
Superseded by duplicate issue #31677
/close
