### ISSUE TITLE
[hi] config.toml is not localized for Hindi

### ISSUE THREAD

**Issue by anubha-v-ardhan** [kubernetes/website#31600]
**This is a Bug Report**

**Problem:**
Parts of config.toml are not localized in Hindi.

**Proposed Solution:**
Localize `[langauges.hi]` section as following
```
[languages.hi]
title = "Kubernetes"
description = "<localized text>"
languageName = "हिंदी Hindi"
weight = 11
contentDir = "content/hi"
languagedirection = "ltr"
```
**Page to Update:**
https://github.com/kubernetes/website/blob/main/config.toml#L430

/kind bug
/good-first-issue
/triage accepted

**Comment by vickykushwaha** [comment]
Assign me I can fix it

**Comment by jatinTyagi98** [comment]
@anubha-v-ardhan I am new to kubernetes . I want to work on this issue . I just want to ask , do I just need to add a word hindi(in hindi language) there ?

**Comment by kranurag7** [comment]
@jatinTyagi98 I have created a PR for this issue. Meanwhile welcome to the community and make sure that you join slack channel. 
If you are interested in localisation then there is a channel `kubernetes-docs-hi` in k8s slack. Make sure you join that.

**Comment by kranurag7** [comment]
@jatinTyagi98 If you get stuck somewhere feel free to ping me back.

**Comment by JagveerGagaan** [comment]
can you help me how I can get this issue

**Comment by srinivas-pokala** [comment]
@anubha-v-ardhan  I am new to k8's community. I want to work this issue, Is the change which  mentioned at: https://github.com/kubernetes/website/blob/main/config.toml#L430 is ok to raise new PR.

**Comment by anubha-v-ardhan** [comment]
Hey @srinivas-pokala thankyou for showing interest but we are deciding a new standard of writing this section (see #31657)
Also, This issue is currently assigned by @kranurag7 and a PR #31609 is open waiting for decision of the new format.

But hey! welcome to Kubernetes. Do join the slack if you haven't already and `#kubernetes-docs-hi` there if you're interested in Hindi l10n

**Comment by sftim** [comment]
/remove-help
/remove-good-first-issue
/remove-triage accepted

I'm not sure that this issue is valid. The Hindi localization is not yet launched and work is happening on branch _dev-1.22-hi.1_.

**Comment by anubha-v-ardhan** [comment]
Not required anymore
