### ISSUE TITLE
ja/blog marked as outdated -- Hugo or docsy bug?

### ISSUE THREAD

**Issue by chalin** [kubernetes/website#31601]
_Originally posted by @chalin in https://github.com/kubernetes/website/issues/31594#issuecomment-1028266049_

> @sftim @nate-double-u - Btw, I did want to mention one minor (IMHO) glitch: the Japanese _blog landing page_ gets marked as outdated, presumable because it contains a single blog entry that is itself outdated — see https://kubernetes.io/ja/blog/
> 
> IMHO, this is a docsy (or Hugo) glitch, no worth writing custom layout code for. This might be fixed in a more recent version of Docsy. Let me know if you're ok with this glitch or whether you'd like for me to investigate further.

**Comment by sftim** [comment]
I think it's fine. If we want to fix it, we can localize an important blog article (eg the one about dockershim removal) to Japanese, and the symptoms disappear.

**Comment by sftim** [comment]
Also, it's not a Docsy bug; it's an issue specific to how we're customizing our theme.
/area web-development
/area blog
