### ISSUE TITLE
Update Portuguese content to mention KubeCon 2022 conference

### ISSUE THREAD

**Issue by krvaibhaw** [kubernetes/website#31618]
**This is a Bug Report**

**Problem:**

These KubeCon conferences are already over but we still have :

- KubeCon em Barcelona on Maio 20-23, 2019
- KubeCon em Shanghai em Junho, 24-26 de 2019

**Proposed Solution:**

Needs to be updated to :

- KubeCon na Europa de 16 a 20 de maio de 2022
- KubeCon na América do Norte de 24 a 28 de outubro de 2022

**Reference:**

- https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccnceu22
- https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna22

**Page to Update:**

`website/content/pt-br/_index.html`

/good-first-issue

**Comment by jatinTyagi98** [comment]
@theanshi I think your pr is not accepted yet !

**Comment by krvaibhaw** [comment]
Thanks for the PRs
Fixed with #31619
/close
