### ISSUE TITLE
Wrong policy key in Auditing page

### ISSUE THREAD

**Issue by Aniket211** [kubernetes/website#31640]
key **verbs:** mentioned in [audit/audit-policy.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/audit/audit-policy.yaml) is incorrect, the correct key should be **verb:**
kube-api contianer fails to get created due to this key with the error mentioned below.
`Error: loading audit policy file: failed decoding: yaml: line 6: did not find expected key: from file /etc/kubernetes/prod-audit.yaml`

**Comment by sftim** [comment]
/retitle Wrong policy key in Auditing page

**Comment by championshuttler** [comment]
@Aniket211 @sftim as per source code this bug should be invalid 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/audit/v1/types.go#L210

**Comment by sftim** [comment]
I don't think this is a valid issue report.
