### ISSUE TITLE
Document EncryptionConfiguration format for kube-apiserver

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31649]
**This is a Feature Request**

**What would you like to be added**
- Within https://kubernetes.io/docs/reference/config-api/ add a new generated page that documents the format for an encryption configuration.
- Update https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/ to hyperlink to that new reference

**Why is this needed**
Within `apiserver.config.k8s.io/v1`, there is a configuration format for the API server, EncryptionConfiguration. At the moment that format is not documented in https://kubernetes.io/docs/reference/config-api/
Readers may want to look up what that format covers.

**Comments**
/sig api-machinery
/sig auth
/kind feature
/language en

**Comment by tengqm** [comment]
/assign
This file is already generated in the generator. All we need to do is to copy it to the website repo.
