### ISSUE TITLE
Remove kubenet from docs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31659]
**This is a Bug Report**

**Problem:** Per https://github.com/kubernetes/kubernetes/issues/100707 the kubenet network plugin is no longer needed / used / part of Kubernetes.

**Proposed Solution:**
Find all mentions of kubenet in the documentation and, for v1.24 of Kubernetes, remove those mentions

**Kubernetes Version:**
v1.24

**Additional Information:**
/milestone 1.24
/language en

**Comment by reylejano** [comment]
k/website PR https://github.com/kubernetes/website/pull/31667 fixes this issue

**Comment by chris-short** [comment]
Should we close this one then @reylejano, @sftim, @nate-double-u?

cc @chrisnegus

**Comment by reylejano** [comment]
@chris-short once PR https://github.com/kubernetes/website/pull/31667 closes, it should auto close this issue

**Comment by chris-short** [comment]
Ah, thank you.

**Comment by mk46** [comment]
Hi @sftim, #31667 merged.  Can we close this?
Thanks!!
