### ISSUE TITLE
Update languageName in config.toml to use both native and English alphabets

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#31657]
**This is a Feature Request**

**What would you like to be updated**

Update languageName in [config.toml](https://github.com/kubernetes/website/blob/main/config.toml) to use both native and English alphabets (letter) for each language (except English).

  - [ ] modify the localization guide document. (to mention a new recommended best practice for `languageName` in each language block. https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/localization.md#modify-the-site-configuration 
  - [ ] modify value for `languageName` parameter in each language blocks in the block for [languages](https://github.com/kubernetes/website/blob/996ac4d94147a6531e0835045c5915dbe6efbb5e/config.toml#L294) in [config.toml](https://github.com/kubernetes/website/blob/main/config.toml): using both their own alphabets and English alphabets (ex: `languageName = "한국어 Korean"`) if it is applicable.
    - I'd like to suggest a format for consistency: `languageName = "Native alphabet (English alphabet)"` 
      - languageName = "中文 (Chinese)"
      - languageName = "한국어 (Korean)"
      - languageName ="Français (French)"
      - languageName = "हिन्दी (Hindi)"
      - ...

**Why is this needed**

The block for [languages](https://github.com/kubernetes/website/blob/996ac4d94147a6531e0835045c5915dbe6efbb5e/config.toml#L294) in config.toml configures multiple languages to the site. And `languageName` parameter in each language block is used to show language menu on the website.

![image](https://user-images.githubusercontent.com/5966944/152939790-01585f9b-573e-45fb-a874-6fb7a3233da9.png)

Some languages (Chinese, Korean and Japanese) are using both their own alphabets and English alphabets in languageName (ex: `languageName = "한국어 Korean"`), but the others are using own alphabet only.

This inconsistency issue was discussed in Kube SIG Docs localization meeting Monday 2/7, 2022. And we decided a new recommended best practice using both native alphabets and English (ex: "한국어 Korean") as it help folks who can't read native alphabet to know which language it is.

> - [Anubhav] Decide a standard for localizations using non-Latin script
>   - How to write [languageName](https://github.com/kubernetes/website/blob/main/config.toml#L433) in config.toml? 
>   - both latin and language’s script OR only in language’s script
>
> - We decided to recommend as a best practice to include both Latin and Native script as done here: https://github.com/kubernetes/website/pull/31609/files
>   - AI to [Brad]  Brad to inform the localization teams of the new recommended best practice.
>   - AI to [Seokho] to update the localization guide to mention this new recommended best practice

**Comments**

Related discussions: 
 - https://kubernetes.slack.com/archives/C0191RDKHU1/p1643965522495389
 - Kube SIG Docs localization meeting Monday 2/7: https://docs.google.com/document/d/1NwO1AN8Ea2zlK8uAdaDAKf1-LZDAFvSewIfrKqfl5No/edit#

**Comment by seokho-son** [comment]
PTAL @bradtopol @anubha-v-ardhan :)

**Comment by seokho-son** [comment]
Let me open a PR to modify the localization guide document. :)
/assign

**Comment by anubha-v-ardhan** [comment]
Looks good to me. Thank you @seokho-son <3

**Comment by sftim** [comment]
Hmm, we should add that label!

**Comment by sftim** [comment]
My suggestion: two fields.

`languageName` plus an optional second one `languageNameLatinScript`. That will let us retain access to the actual localized `languageName` if we need it.

**Comment by a-mccarthy** [comment]
thanks for writing this up @seokho-son. I like Tim's suggestion of making this into 2 variables as well

**Comment by seokho-son** [comment]
@sftim Thanks for the suggestion :) 
I hope to check your suggestion is about adding additional parameter (`languageNameLatinScript`) in the block for [languages.xx](https://github.com/kubernetes/website/blob/996ac4d94147a6531e0835045c5915dbe6efbb5e/config.toml#L342) of config.toml

For instance,

```diff
[languages.fr]
title = "Kubernetes"
description = "Solution professionnelle d’orchestration de conteneurs"
- languageName ="Français"
+ languageName ="Français (French)"
+ languageNameLatinScript ="Français"
weight = 5
contentDir = "content/fr"
languagedirection = "ltr"
```

If it is what you meant, I am not sure how `languageNameLatinScript` works in Hugo. (I cannot find this parameter)
Could you give me more context ?

**Comment by sftim** [comment]
I think `languageNameLatinScript` would be a Kubernetes thing, not a Hugo thing. So long as Hugo lets us set it, we can then access that data in the theme and use it somewhere sensible.
