### ISSUE TITLE
kubeadm-upgrade: add note about verifying the kubelet service status

### ISSUE THREAD

**Issue by ds01efp1** [kubernetes/website#31650]
For the Redhat when upgrading the kubelet you should have following for Restart kubelet
sudo systemctl daemon-reload
sudo systemctl stop kubelet
ps -ef | grep kubelet (verfiy kubelet stopped kill process if not stopped)
sudo systemctl start kubelet

**Comment by neolit123** [comment]
hi, i'm not sure what issue are you reporting.
can you elaborate?

/kind support

**Comment by sftim** [comment]
/sig cluster-lifecycle

I think @ds01efp1 is asking for a detailed walkthrough of how to restart a service on RedHat-like hosts, and then to verify that the restarted service is healthy.
There's some value in this but also we need to bear in mind that systemd and Linux are not the only options for nodes, and that we could instead declare “you should know how to restart services and verify that they are healthy” as a prerequisite.

Any Kubernetes-specific way to verify that a kubelet is healthy _is_ valid and we should document it.

**Comment by Rohan749** [comment]
Hey @sftim, can I work on this issue?

**Comment by neolit123** [comment]
> Any Kubernetes-specific way to verify that a kubelet is healthy is valid and we should document it.

we could add the following bullet point here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#additional-information

> - To verify that the kubelet service has successfully restarted after the kubelet has been upgraded, you can execute `systemctl status kubelet` our view the service logs with `journalctl -xeu kubelet`

@Rohan749 would you like to send a PR for that?

**Comment by neolit123** [comment]
/kind feature
/remove-triage needs-information
/triage accepted
/retitle kubeadm-upgrade: add note about verifying the kubelet service status
