### ISSUE TITLE
https://k8s.io/dockershim is marked outdated

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31663]
**This is a Bug Report**

**Problem:** https://k8s.io/dockershim is marked deprecated (since the merge of https://github.com/kubernetes/website/pull/31594)

**Proposed Solutions:**

Either:
- Write a new article
  - Update https://kubernetes.io/blog/2020/12/02/dockershim-faq/ to link prominently to the new article
  - Update https://k8s.io/dockershim to redirect to the new article
- Something complicated involving custom expiry periods in front matter

**Page to Update:**
https://k8s.io/dockershim etc (see above)

**Additional Information:**
/priority important-soon
/sig node
/language en

Also see https://github.com/kubernetes/website/pull/30840

**Comment by sftim** [comment]
Right now, https://k8s.io/dockershim is a Hugo alias; PR #30840 would replace that with a Netlify redirect (experience suggests that these cause fewer issues).

**Comment by sftim** [comment]
BTW folks, which approach are we taking? I strongly favor adding a new article (which can be much the same as the one it replaces, just newer) rather than more complex & technical fixes.

**Comment by chris-short** [comment]
Could we bump the date forward? This FAQ is something I routinely point people to.

**Comment by sftim** [comment]
It's a blog. We wouldn't remove the existing article - people will have bookmarked it with it's URL, and also it's just a bit weird to change an already-published article have a new date.

Nothing wrong with _duplicating_ (or near-duplicating) the article as I've suggested, though.

**Comment by chris-short** [comment]
It's a FUD machine at the moment. I don't care what happens to make it not a FUD machine. It just needs to happen fast; anything I can do to help?

**Comment by sftim** [comment]
> anything I can do to help?

- Open a PR to make a new article
- Check with the authors of the existing article that they are happy for a no-change update to go out.

@chris-short this?

**Comment by chris-short** [comment]
On it.

**Comment by chris-short** [comment]
/assign

Please see #31765 for my first attempt at this.
