### ISSUE TITLE
Invalid link for `API server config API (v1beta1)`

### ISSUE THREAD

**Issue by foolwc** [kubernetes/website#31665]
Hi, this page https://kubernetes.io/docs/concepts/cluster-administration/system-traces/  has a link
[API server config API (v1beta1)](https://kubernetes.io/docs/reference/config-api/apiserver-config.v1beta1/#apiserver-k8s-io-v1beta1-TracingConfiguration) which is 404, but I can't find this page in kubernetes website.

**Comment by mengjiao-liu** [comment]
In this PR https://github.com/kubernetes/website/pull/30826 the page: https://kubernetes.io/docs/reference/config-api/apiserver-config.v1beta1 has been removed.

[API server config API (v1beta1)](https://kubernetes.io/docs/reference/config-api/apiserver-config.v1beta1/#apiserver-k8s-io-v1beta1-TracingConfiguration) should point to the latest page link: https://kubernetes.io/docs/reference/config-api/apiserver-config.v1/

/assign

**Comment by foolwc** [comment]
> In this PR #30826 the page: https://kubernetes.io/docs/reference/config-api/apiserver-config.v1beta1 has been removed.
> 
> [API server config API (v1beta1)](https://kubernetes.io/docs/reference/config-api/apiserver-config.v1beta1/#apiserver-k8s-io-v1beta1-TracingConfiguration) should point to the latest page link: https://kubernetes.io/docs/reference/config-api/apiserver-config.v1/
> 
> /assign

I could not find the `TracingConfiguration` description in the latest page link https://kubernetes.io/docs/reference/config-api/apiserver-config.v1/.  Is that missing?

**Comment by mengjiao-liu** [comment]
Yes, I also checked this struct just now, it doesn't exist in the v1 version.
This struct  `TracingConfiguration ` was removed in version v1.

**Comment by tengqm** [comment]
There were some nits in the reference generator. We are fixing them and then regenerate the references.

**Comment by dashpole** [comment]
TracingConfiguration is still alpha, and thus doesn't exist in the v1 version of the API.

**Comment by mengjiao-liu** [comment]
So do we need to create a new page `docs/reference/config-api/apiserver-config.v1alpha1.md` containing the TracingConfiguration struct so that we can link to it? 

Or link to the kubernetes TracingConfiguration code line:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1/types.go#L154 

Which one do you prefer or have a better suggestion? @tengqm  @sftim

**Comment by tengqm** [comment]
I'll create a PR updating the config APIs.
As for the TracingConfiguration type, it is only part of the v1alpha1 version. This means the current code is incorrect and the v1alpha1 reference needs to be added back. This warrants a separate PR.

**Comment by tengqm** [comment]
First PR created #31786

**Comment by tengqm** [comment]
Second PR created #31787
/assign
