### ISSUE TITLE
 Error: failed to fetch endpoints from etcd cluster member list: context deadline exceeded

### ISSUE THREAD

**Issue by sanjaz10** [kubernetes/website#31674]
## What happened?

I tried to Set up a High Availability etcd Cluster with kubeadm.
I followed the official guide https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
after all the steps execute when i check cluster health its giving below error message 

[root@etcd-01 ~]# docker run --rm -it \
> --net host \
> -v /etc/kubernetes:/etc/kubernetes k8s.gcr.io/etcd:3.5.1-0 etcdctl \
> --cert /etc/kubernetes/pki/etcd/peer.crt \
> --key /etc/kubernetes/pki/etcd/peer.key \
> --cacert /etc/kubernetes/pki/etcd/ca.crt \
> --endpoints https://137.184.157.161:2379 endpoint health --cluster
{"level":"warn","ts":"2022-02-09T08:12:22.497Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00045e540/137.184.157.161:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 137.184.157.161:2379: connect: connection refused\""}
Error: failed to fetch endpoints from etcd cluster member list: context deadline exceeded

## What you expected to happen?
as per the official guide etcd cluster should be healthy state.

## How to reproduce it (as minimally and precisely as possible)?

You can follow the official guide with https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ 

## Versions

**kubeadm version** (use `v1.23.3`):

**Environment**:
- **Kubernetes version** (use `v1.23.3`):
- **Cloud provider or hardware configuration**:

Master Nodes -03 
Worker Nodes -03 
etcd -03 
HA load balancer -01 

Digital Ocean cloud 
all instance - 4 HB Ram ,2 CPU ,80 GB disk 

- **OS** (e.g. from /etc/os-release):
CentOS 8

[root@etcd-01 ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

- **Kernel** (e.g. `uname -a`):

[root@etcd-01 ~]# uname -a
Linux etcd-01 4.18.0-277.el8.x86_64 #1 SMP Wed Feb 3 20:35:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- **Container runtime (CRI)** (e.g. containerd, cri-o):
Docker

- **Container networking plugin (CNI)** (e.g. Calico, Cilium):
wavenet 
- **Others**:

**Comment by sanjaz10** [comment]
Issue fixed my self. In the Step 01 Configure the kubelet to be a service manager for etcd  remove the this line "
--container-runtime=remote --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock " . Please use below command in the steps 01.
cat << EOF > /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
[Service]
ExecStart=
# Replace "systemd" with the cgroup driver of your container runtime. The default value in the kubelet is "cgroupfs".
# Replace the value of "--container-runtime-endpoint" for a different container runtime if needed.
ExecStart=/usr/bin/kubelet --address=127.0.0.1 --pod-manifest-path=/etc/kubernetes/manifests --cgroup-driver=systemd 
Restart=always
EOF

**Comment by neolit123** [comment]
See this if you are using docker:
https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/

**Comment by sanjaz10** [comment]
@neolit123 yea. that's why i already removed and checked .
