### ISSUE TITLE
Improvement for k8s.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

### ISSUE THREAD

**Issue by moonlight16** [kubernetes/website#31688]
The whole section about "Should I add a customer resources to my Kubernetes Cluster?" is confusing.

The title leads me to believe your going to discuss when to use CRDs vs build-in resources.  But your really talking about building some sort of stand-alone API (is this still a CRD?).   OR should you use API Aggregation (which the descriptions under API agg say its different than CRDs) -- a third concept here???

And what does it mean stand-alone API?  Are we saying building stand-alone API is a CRD?  But that cannot be...

Under the table.  It says you should consider "stand-alone API" if kubectl support is not required.  But it says above CRDs can be accessible with kubectl, so this column cannot be for CRDs.  But the other column is for API aggregation, which is not supposed to be the same as CRDs.  Do you see the contradiction here?

**Comment by sftim** [comment]
Really, https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#should-i-add-a-custom-resource-to-my-kubernetes-cluster belongs in https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/ and not in the custom resources page. 

It would also be nice to make the overall wording more easy to understand.

/language en
/wg api-expression
/sig docs
/kind cleanup

**Comment by NitishKumar06** [comment]
Hey @sftim I'll work on this issue. I believe it'll be best if we can add a short intro in https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/ related to Custom Resources and API aggregation layer.

**Comment by NitishKumar06** [comment]
@moonlight16 Please go through the PR I raised for this issue .

**Comment by moonlight16** [comment]
> @moonlight16 Please go through the PR I raised for this issue .

@NitishKumar06 I didn't see a link to the PR in this thread.  Can you post a link?  thx!

**Comment by NitishKumar06** [comment]
@moonlight16 https://github.com/kubernetes/website/pull/34246
