### ISSUE TITLE
kubectl download page for Linux assumes amd64 architecture

### ISSUE THREAD

**Issue by ctron** [kubernetes/website#31699]
The page assumes one is using `amd64` and as an architecture. The download commands won't work for e.g. `aarch64` / `arm64`.

**Comment by sftim** [comment]
/kind bug
/retitle kubectl download page for Linux assumes amd64 architecture

**Comment by sftim** [comment]
/language en
/triage accepted
/priority important-longterm

Thanks for filing this @ctron
