### ISSUE TITLE
'XFS project quotas' link in `manage-resources-containers.md` is broken

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#31690]
**This is a Bug Report**

**Problem:**

In ["What's next" section](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#what-s-next) of ['Resource Management for Pods and Containers' page](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/),
the link '[project quotas](https://xfs.org/docs/xfsdocs-xml-dev/XFS_User_Guide/tmp/en-US/html/xfs-quotas.html) in XFS' is broken.
It returns 404 Not Found.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#what-s-next

**File to Update:**
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/configuration/manage-resources-containers.md

**Comment by Babapool** [comment]
I think we can `project quotas` to this link: https://xfs.org/index.php/XFS_FAQ#Q:_Quota:_Do_quotas_work_on_XFS.3F . Thoughts?

**Comment by sftim** [comment]
/language en
@Babapool sure - would you like to open a pull request?
