### ISSUE TITLE
Set up a High Availability etcd Cluster with kubeadm - document issue 

### ISSUE THREAD

**Issue by sanjaz10** [kubernetes/website#31692]
I don't have any issue .but i have suggestion . 

when i follow the official guide https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ i noticed a document incorrect path issue. 

In the steps 7 they mention kubeadmcfg.yaml in /tmp folder all the etcd instance. but steps 6 showing in the kubeadmcfg.yaml only $HOST0 having tmp other etcd instance having document root. Document should update the correct path

![image](https://user-images.githubusercontent.com/35827824/153545574-b6b8c5a0-98cc-4213-9d74-176e94db9dc8.png)

**Comment by sftim** [comment]
/language en
/sig cluster-lifecycle

I don't think I've understood the report you've filed @sanjaz10. In the existing page, which specific part of that text contains the details that you think we should change?

**Comment by sanjaz10** [comment]
Hi @sftim 

In the step 7 path should be correct as below 

root@HOST0 $ kubeadm init phase etcd local --config=/tmp/${HOST0}/kubeadmcfg.yaml
root@HOST1 $ kubeadm init phase etcd local --config=/$HOME/kubeadmcfg.yaml
root@HOST2 $ kubeadm init phase etcd local --config=/$HOME/kubeadmcfg.yaml

**Comment by neolit123** [comment]
> root@HOST0 $ kubeadm init phase etcd local --config=/tmp/${HOST0}/kubeadmcfg.yaml
> root@HOST1 $ kubeadm init phase etcd local --config=/$HOME/kubeadmcfg.yaml
> root@HOST2 $ kubeadm init phase etcd local --config=/$HOME/kubeadmcfg.yaml

if you look at step 4:
> Create certificates for each member

all kubeadmcfg.yaml files are under `--config=/tmp/${HOSTX}/kubeadmcfg.yaml`

so it seems step 6 is the one that is wrong.

**Comment by neolit123** [comment]
fix here:
https://github.com/kubernetes/website/pull/31971
