### ISSUE TITLE
Issue with /docs/getting-started-guides/ubuntu/manual/

### ISSUE THREAD

**Issue by anandkolli** [kubernetes/website#3170]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
For installation kube-controller-manager is missing

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@anandkolli is it missing in the `tree cluster/ubuntu/binaries` output? Can you please provide more detail?

**Comment by anandkolli** [comment]
Sure, what I mean was, Once we download from git repo, the compilation and building steps of Kubernetes is missing. As it directly jumps on how to start a cluster using command kube-controller-manager.

**Comment by zacharysarah** [comment]
@anandkolli Thanks for opening this issue. There's enough information to make this actionable for docs, though investigation into [compiling and building k8s](https://kubernetes.io/docs/getting-started-guides/binary_release/) is probably required. 👍
