### ISSUE TITLE
Seccomp support isn't documented

### ISSUE THREAD

**Issue by php-coder** [kubernetes/website#3173]
I didn't find anything except [proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/seccomp.md) about supporting seccomp profiles.

**Comment by ahmetb** [comment]
@php-coder have you been able to use seccomp with Kubernetes. It doesn’t seem like the feature has been implemented and released yet.

**Comment by php-coder** [comment]
@ahmetb No, I didn't use it. But because it's undocumented how it's supposed that user will know about it? The only way at present is to reading sources.

**Comment by zacharysarah** [comment]
@php-coder :wave: Thanks for opening this issue. Because support for seccomp remains proposed but not implemented, I'm going to close this issue until it's actionable for docs.

**Comment by php-coder** [comment]
Another attempt:
/reopen

**Comment by php-coder** [comment]
So far there is only how to control it's usage with PSP: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp I'm not sure whether it's enough or not.

**Comment by tengqm** [comment]
Let's keep this open.
/remove-lifecycle stale
