### ISSUE TITLE
Usage of PSP for controlling safe/unsafe sysctls isn't documented

### ISSUE THREAD

**Issue by php-coder** [kubernetes/website#3174]
It turns out that user can annotate PSP with `security.alpha.kubernetes.io/sysctls` annotation to specify "whitelist of allowed safe and unsafe sysctls in a pod spec". It isn't documented.

**Comment by liggitt** [comment]
I'd rather see them graduate to fields before getting officially documented and used
@pweil-

**Comment by pweil-** [comment]
Ok.  @php-coder let's discuss what else needs to be done on the roadmap to graduate the feature and get this worked into a card for PM

**Comment by php-coder** [comment]
I found that the usage of safe/unsafe sysctls are documented here: https://kubernetes.io/docs/concepts/cluster-administration/sysctl-cluster/ But its usage doesn't relate to PSP at all.

@sttts Could you explain how PSP strategy (`pkg/security/podsecuritypolicy/sysctl`) is correlated with the current behavior when admin need to pass `--experimental-allowed-unsafe-sysctls` option to the kubelet?

**Comment by sttts** [comment]
The design and implementation is documented in https://github.com/kubernetes/community/blob/930ce65595a3f7ce1c49acfac711fee3a25f5670/contributors/design-proposals/node/sysctl.md#proposed-design.

**Comment by php-coder** [comment]
The documentation was added in #7600 and is available at https://kubernetes.io/docs/concepts/cluster-administration/sysctl-cluster/#podsecuritypolicy-annotations

/close
