### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by icculp** [kubernetes/website#31755]
Trying to start the interactive tutorial, the terminal was unusable:
```
Kubernetes Bootcamp Terminal

The content owner's account has reached capacity. Please try again in 10 minut
```
![image](https://user-images.githubusercontent.com/57159226/154090402-1483e440-5ef9-4947-8a91-f02e8d954c71.png)

**Comment by mk46** [comment]
Hi @icculp,  I tried this tutorial, and all the given steps are working.

**Comment by icculp** [comment]
It's working now. It started working maybe an hour or so after I posted this issue. Figured I'd leave the issue open so the team would be aware of the over load at that time.
