### ISSUE TITLE
Node Affinity NodeSelectorTerms description is wrong

### ISSUE THREAD

**Issue by dancnfoo** [kubernetes/website#31769]
> If you specify multiple nodeSelectorTerms associated with nodeAffinity types, then the pod can be scheduled onto a node **if one of** the nodeSelectorTerms can be satisfied.

> If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node **only if all* matchExpressions is satisfied.

Should be, 

If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node **if one of** matchExpressions can be satisfied.

If you specify multiple node label requirements associated with matchExpressions types, then the pod can be scheduled onto a node **only if all** requirements can be satisfied.

**Comment by sftim** [comment]
Hi @dancnfoo 

What's the URL of the page that you don't think is correct?
/triage needs-information
/language en

**Comment by championshuttler** [comment]
@sftim i guess this https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by dancnfoo** [comment]
https://v1-20.docs.kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity

**Comment by dancnfoo** [comment]
Can someone confirm this issue has been triaged?

**Comment by alculquicondor** [comment]
#37991 also tried to "fix" this. But I think there is nothing to fix.

**Comment by alculquicondor** [comment]
Here is my attempt #38032, but @cortespao is suggesting that it's better to add samples. Is anyone willing to take this over?
