### ISSUE TITLE
配置 Pod 以使用卷进行存储

### ISSUE THREAD

**Issue by Reeker-Liu** [kubernetes/website#31772]
> 因此当一个容器终止并重新启动，对该容器的文件系统改动将丢失。

这里应该是**pod**重启才会导致丢失，仅**容器**重启不会丢失，后面的例子也证明了这一点

**Comment by Reeker-Liu** [comment]
https://kubernetes.io/zh/docs/tasks/configure-pod-container/configure-volume-storage/

**Comment by tengqm** [comment]
Won't be able to fix this in Chinese alone. The English upstream needs an update instead.
