### ISSUE TITLE
Fix typo in `feature-gates.md`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#31785]
**This is a Bug Report**

**Problem:**
- Typo exists: `Derecated`
- Wrong bullet character is used:
https://github.com/kubernetes/website/blob/670ae1a6de2f4453165cbc607e1ed90125347580/content/en/docs/reference/command-line-tools-reference/feature-gates.md?plain=1#L813-L820

**Proposed Solution:**
- `Derecated` => `Deprecated`
- `= ` => `- ` (in L818)

**Page to Update:**
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=%2D-,Derecated,-1.17
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=%3D%20GracefulNodeShutdownBasedOnPodPriority

**File to Update:**
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/feature-gates.md

**Comment by anubha-v-ardhan** [comment]
/triage accepted
I believe this can be a good first issue
/good-first-issue

**Comment by ShivamTyagi12345** [comment]
hey @jihoon-seo , Would you kindly point me to where did u find the term "Derecated". It would wrap things up faster:)

**Comment by anubha-v-ardhan** [comment]
@Mouly22 @ikramulkayes Sorry, but this issue seems an individual task. Thank you for wanting to contribute, you can have a look at other issues and try them if you wish. Thank you
/unassign @Mouly22 
/unassign @ikramulkayes

**Comment by Mouly22** [comment]
Hey @anubha-v-ardhan I am sorry but I have already updated in https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=%2D-,Derecated,-1.17 this page

**Comment by ikramulkayes** [comment]
> @Mouly22 @ikramulkayes Sorry, but this issue seems an individual task. Thank you for wanting to contribute, you can have a look at other issues and try them if you wish. Thank you /unassign @Mouly22 /unassign @ikramulkayes

@anubha-v-ardhan  okay, mate. Looking forward to the next issue to work on.

**Comment by Mouly22** [comment]
@ShivamTyagi12345 Happy to help 😅
