### ISSUE TITLE
Improvement for k8s.io/zh/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by zhuyaguang** [kubernetes/website#31790]
![image](https://user-images.githubusercontent.com/8857976/154647844-c233c15b-6f76-40be-a3ee-144b9f6fe33a.png)

![image](https://user-images.githubusercontent.com/8857976/154647939-8628cf23-d4be-400c-abc7-10073d3898d2.png)

应该带上端口号

**Comment by tengqm** [comment]
/close
This doesn't look right.
Even if the problem is true and we need to fix it, we should start from the English upstream.
