### ISSUE TITLE
[ko] Better translation of the terms `request` and `limit`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#31791]
**This is a Bug Report**

**Problem:**
예를 들어, `request` 및 `limit` 단어가
["컨테이너 리소스 관리"](https://kubernetes.io/ko/docs/concepts/configuration/manage-resources-containers/) 페이지에는 "요청 및 제한" 이라고 번역되어 있습니다.

이 페이지 등을 참고하여 저도 번역을 할 때 여러 부분에 "요청" 및 "제한" 으로 번역을 하였는데..

방금 용어집을 확인해 보니
> 한도(limit)
> 리소스의 개수나 용량을 한정하기 위한 수치로 사용된 경우 선택적으로 사용 (API 오브젝트의 속성으로 limit을 사용한 경우는 가능한 영문 유지)

> 요청(request)
> 리소스의 개수나 용량에 대한 요청 수치를 표현하기 위해 사용된 경우 선택적으로 사용 (API 오브젝트 속성으로 request를 사용한 경우는 가능한 영문을 유지)

이렇게 되어 있네요 😊

또 다른 경우는,
- https://kubernetes.io/ko/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/
- https://kubernetes.io/ko/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

등을 보면
각각 "요청량", "상한" 으로 번역되어 있습니다.

제가 지금까지 번역을 하면서 보니
`request`를 "요청" 이라고 번역하면
"리소스의 개수나 용량에 대한 요청 수치를 표현하기 위해 사용된 경우" 라는 점이 잘 전달되지 않고
마치 "요청하는 행위" 로 잘못 전달될 가능성이 있으며

`limit`을 "제한" 이라고 번역하면
"리소스의 개수나 용량을 한정하기 위한 수치로 사용된 경우" 라는 점이 잘 전달되지 않고
마치 "제한하는 행위" 로 잘못 전달될 가능성이 있습니다.

저는 개인적으로는 "요청량", "상한" 이 의미 전달 면에서 좋을 것 같은데,
@kubernetes/sig-docs-ko-reviews 다른 분들은 어떻게 생각하시나요? 😊

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/ko/...

/language ko

**Comment by seokho-son** [comment]
@jihoon-seo 
예전에 관련 논의가 기억 나네요. ^^ https://github.com/kubernetes/website/pull/21339

**Comment by sftim** [comment]
@jihoon-seo a nit: if the issue is a ”good translation” then that doesn't sound like a bug. Maybe you meant to report that there is a _bad_ translation?

**Comment by jihoon-seo** [comment]
@sftim Thank you for the pointing.
This issue is rather about 'which translation would be better?'. 😅
So it would be better to update the label and title:
/retitle [ko] Better translation of the terms `request` and `limit`
/remove-kind bug

**Comment by jihoon-seo** [comment]
이런 부분도 있네요
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/#discussion

> As you have seen in this exercise, you can use a ResourceQuota to restrict the memory request total for all Pods running in a namespace. You can also restrict the totals for memory limit, cpu request, and cpu limit.
> 
> Instead of managing total resource use within a namespace, you might want to restrict individual Pods, or the containers in those Pods. To achieve that kind of limiting, use a [LimitRange](https://kubernetes.io/docs/concepts/policy/limit-range/).

`restrict` 라는 단어도 있고
`limit` 이라는 단어도 있는데,
만약 둘다 "제한"으로 번역하면.. 바람직하지 않을 것 같아요.. 🤔
