### ISSUE TITLE
Ensure “Download Kubernetes” link goes to right page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31794]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/home/ has a link (styled as a button) titled “Download Kubernetes”. At the moment that link goes to https://kubernetes.io/releases/notes/ which isn't quite right.

**Proposed Solution:**
Change the site so that that link goes instead to https://kubernetes.io/releases/download/

**Page to Update:**

https://kubernetes.io/docs/home/

**Additional Information:**
/kind cleanup
/language en

/help

**Comment by shaggyyy2002** [comment]
#31812 
@sftim I have changed the path to download kubernetes.

**Comment by tengqm** [comment]
/close
This one has been fixed. Manually closing.
