### ISSUE TITLE
1.20.11 version Unable to expand the master node！

### ISSUE THREAD

**Issue by QiuToo** [kubernetes/website#31802]
在kubernetes1.20.11版本扩容master节点时出现以下问题：
[root@tes-master2 ~]# cd  /root  && mkdir -p /etc/kubernetes/pki/etcd && mkdir -p ~/.kube/
[root@tes-master2 ~]# ls  /etc/kubernetes/pki/
ca.crt  ca.key  etcd  front-proxy-ca.crt  front-proxy-ca.key  sa.key  sa.pub
[root@tes-master2 ~]# ls  /etc/kubernetes/pki/etcd/
ca.crt  ca.key

[root@tes-master2 ~]# kubeadm join 192.168.2.41:6443 --token ljkqm7.fpf0ifgzyjn36lo5     --discovery-token-ca-cert-hash sha256:41af0faf075d1b06e90539c4e9f6d53f3d2217974e023a51e73e852f9a58aef1   --control-plane
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
error execution phase preflight: 
One or more conditions for hosting a new control plane instance is not satisfied.

unable to add a new control plane instance a cluster that doesn't have a stable controlPlaneEndpoint address

Please ensure that:
* The cluster has a stable controlPlaneEndpoint address.
* The certificates that must be shared among control plane instances are provided.

To see the stack trace of this error execute with --v=5 or higher

验视：
使用1.20.6可正常扩容master节点。

**Comment by sftim** [comment]
Hi @qiutoo

Could you write the bug report in English? We use that as the main language for contribution to Kubernetes.

I suspect that this is more of a support request than a bug report; in that case, though, I'm afraid you have come to the wrong place. https://kubernetes.io/zh/docs/tasks/debug-application-cluster/troubleshooting/ might help you perhaps?

/triage needs-information
(the English version of the report)

**Comment by neolit123** [comment]
closing due to no response for ~20 days.
please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
