### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by pboling** [kubernetes/website#31825]
`configure-upgrade-etcd.md` has literally no information on upgrading an etcd cluster...

😵‍💫 

[This somewhat dated guide](https://dzone.com/articles/kubernetes-upgrade-the-definitive-guide-to-do-it-yourself) is the best I have found so far, but it is hard to evaluate how dated, or accurate it might be, since there is no info in the official upgrade guide...

**Comment by sftim** [comment]
I suggest we hyperlink to https://etcd.io/docs/latest/upgrades/ with a note that the reader should check the docs for the version they actually intend to upgrade to.

/language en

**Comment by mangoGoForward** [comment]
I'd like to tackle this issue :)
/assign
