### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by shaneboulden** [kubernetes/website#31827]
Currently the tutorial is reporting the 'environment is not starting correctly'. No debug information is provided.

![Screenshot from 2022-02-22 10-12-33](https://user-images.githubusercontent.com/1834999/155036857-b21e59b9-091d-4eeb-a1b3-daf501ad51aa.png)

**Comment by sftim** [comment]
Thanks for reporting this
/label team/katacoda

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

It seems that occasionally, some people are experiencing problems with Katacoda.

For me, for now:
![image](https://user-images.githubusercontent.com/46767780/155496618-806214d5-bf85-4e78-8a61-118a61c9afa3.png)
