### ISSUE TITLE
Document ServiceAccount within concepts section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31847]
**This is a Feature Request**

**What would you like to be added**
*Within the Concepts section* of the docs, add a page or page section that introduces ServiceAccount and outlines the concepts.

**Why is this needed**
Kubernetes ServiceAccounts are very useful, and people who want to operate a secure platform need to understand ServiceAccounts; however, someone reading through the Concepts section only sees oblique hints and hyperlinks to more information. In the current site, the concept is split between some pages in the Tasks section and other pages in the Reference section.

**Comments**
:information_source: If opening pull requests that move existing content, please add the **refactor** label to those PRs.

Also see:
- https://github.com/kubernetes/website/issues/4410
- https://github.com/kubernetes/website/pull/31845#issuecomment-1048105564
- https://github.com/kubernetes/website/issues/28285

/language en
/sig auth
/sig security
/kind feature

**Comment by sftim** [comment]
The page that I would change is  https://kubernetes.io/docs/concepts/security/controlling-access/ (adding a new section). It's also OK to create a whole new page for the service account concept.

**Comment by ediazgallego** [comment]
Hi @sftim are you working on this? or can I take it and work on it?.

**Comment by sftim** [comment]
I reported this, I haven't done anything further. Folks (@ediazgallego included) are most welcome to work on it.

**Comment by sftim** [comment]
The historical page at https://github.com/kubernetes/kubernetes/blob/a20258efaecfc5b46f24111f17bc18168713a124/docs/design/service_accounts.md might provide a starting point?

**Comment by ediazgallego** [comment]
Planning to work on this starting tomorrow.

**Comment by sftim** [comment]
@ediazgallego would you like any help with moving that work forward?

**Comment by shannonxtreme** [comment]
I created a rough outline of what a concept page might look like. I've opened it up for collaboration and suggestions in [this Google Doc](https://docs.google.com/document/d/1UcEFreczITmFhcHAgZkIpuEJD4m1AraiRQAtzpNIRaE/edit?usp=sharing).

After we get some feedback from docs and sig-auth on the outline, I will work on what can be child issues and how to split up the work to be more reviewer-friendly/good-first-issues. I'll draft the content after we've figured that stuff out. 

/assign

**Comment by ritazh** [comment]
@shannonxtreme can you please make this is included in the new doc? https://github.com/kubernetes/website/issues/32688#issuecomment-1086670793

**Comment by shannonxtreme** [comment]
Made some updates based on reviewer comments and feedback @ritazh

**Comment by Shubham82** [comment]
> I created a rough outline of what a concept page might look like. I've opened it up for collaboration and suggestions in [this Google Doc](https://docs.google.com/document/d/1UcEFreczITmFhcHAgZkIpuEJD4m1AraiRQAtzpNIRaE/edit?usp=sharing).
> 
> After we get some feedback from docs and sig-auth on the outline, I will work on what can be child issues and how to split up the work to be more reviewer-friendly/good-first-issues. I'll draft the content after we've figured that stuff out.
> 
> /assign

Hi @shannonxtreme Thanks for the docs, It is very useful. I made a comment there could you please take l look?

**Comment by shannonxtreme** [comment]
> > I created a rough outline of what a concept page might look like. I've opened it up for collaboration and suggestions in [this Google Doc](https://docs.google.com/document/d/1UcEFreczITmFhcHAgZkIpuEJD4m1AraiRQAtzpNIRaE/edit?usp=sharing).
> > 
> > After we get some feedback from docs and sig-auth on the outline, I will work on what can be child issues and how to split up the work to be more reviewer-friendly/good-first-issues. I'll draft the content after we've figured that stuff out.
> > 
> > /assign
> 
> Hi @shannonxtreme Thanks for the docs, It is very useful. I made a comment there could you please take l look?

Will do friend! I've admittedly been a bit busy lately but can't wait to dive into a PR for this soon ☺️

**Comment by sftim** [comment]
Done! Nice work @shannonxtreme 

/close
