### ISSUE TITLE
kubernetes.io/enforce-mountable-secrets annotation unregistered and undocumented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31853]
**This is a Bug Report**

**Problem:**
Kubernetes uses an annotation, `kubernetes.io/enforce-mountable-secrets`, that isn't yet registered or documented in https://kubernetes.io/docs/reference/labels-annotations-taints/

**Proposed Solution:**
Update https://kubernetes.io/docs/reference/labels-annotations-taints/ to include that annotation

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig auth
/language en

**Comment by Shubham82** [comment]
Fixed it here: #31864
PTAL!
