### ISSUE TITLE
Typo in `cpu-constraint-namespace.md` & `memory-default-namespace.md`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#31856]
**This is a Bug Report**

**Problem:**
In [here](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/#attempt-to-create-a-pod-that-does-not-meet-the-minimum-cpu-request),
the section title is "Attempt to create a Pod that does not meet the minimum CPU **request**",
but in the paragraph it says:
> The output shows that the Pod does not get created, because it defines an unacceptable container. That container is not acceptable because it specifies a CPU **limit** that is lower than the enforced minimum:

---

In ["Motivation for default memory limits and requests" section](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#motivation-for-default-memory-limits-and-requests),
"CPU limits" seems to be a typo of "Memory limits".

> **CPU limits** apply a resource reservation on the node where the Pod in question is scheduled. The total amount of memory reserved for all Pods in the namespace must not exceed a specified limit.

**Proposed Solution:**

L172-L174 of [`cpu-constraint-namespace.md`](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace.md?plain=1):
```diff
The output shows that the Pod does not get created, because it defines an unacceptable container.
-That container is not acceptable because it specifies a CPU limit that is lower than the
+That container is not acceptable because it specifies a CPU request that is lower than the
enforced minimum:
```

---

L180 of [`memory-default-namespace.md`](https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md?plain=1):
```diff
-* CPU limits apply a resource reservation on the node where the Pod in question is scheduled.
+* Memory limits apply a resource reservation on the node where the Pod in question is scheduled.
```

**Page to Update:**
- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/#:~:text=specifies%20a%20CPU-,limit,-that%20is%20lower
- https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/#:~:text=for%20its%20containers).-,CPU,-limits%20apply%20a

/language en

**Comment by ShivamTyagi12345** [comment]
triage/accepted 
I also find it a beginner-friendly issue 
/good first issue

**Comment by Aayush987** [comment]
I am sorry but i have taken the issue so maybe you can look for another one.@mitul3737

**Comment by mitul3737** [comment]
Okay sure!
