### ISSUE TITLE
API operations don't match authorization verbs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#3186]
I'm not sure where the operation names used in https://kubernetes.io/docs/api-reference/v1.6/ (read, replace, etc) come from, but it would be ideal if they matched the actual verbs used [by authorization](https://kubernetes.io/docs/admin/authorization/#request-attributes) (get, list, watch, create, update, patch, delete, deletecollection) 

cc @jhorwit2

**Comment by ahmetb** [comment]
This sounds more like it comes from swagger. I am not sure if it’s something API reference generator decides.

**Comment by zacharysarah** [comment]
@ahmetb 👋 Any updates here?

**Comment by ahmetb** [comment]
The verbs probably come from https://github.com/kubernetes-incubator/reference-docs @liggitt if you want to change, feel free to send a patch there, pwittrock can pick up for the next release. If it's not high priority enough, we can close this.

**Comment by tengqm** [comment]
Filed an issue in the reference-docs project for tracking. Closing this one here.
/close
