### ISSUE TITLE
[zh]sync content/en/docs/tutorials/security/apparmor.md

### ISSUE THREAD

**Issue by howieyuen** [kubernetes/website#31868]

**Comment by jihoon-seo** [comment]
Please notice that:
- Renamed in EN: [en/docs/tutorials/clusters/apparmor.md → en/docs/tutorials/security/apparmor.md](https://github.com/kubernetes/website/commit/ec94e69c4ef0ea63692c312038f16c8fc2e1b6b7#diff-224d62801d454f076db335ddf57a698e1fd065ac6a637fc794c131213e6c01c4)
- ZH version exists: https://kubernetes.io/zh/docs/tutorials/clusters/apparmor/

Suggestion:
- Move https://kubernetes.io/zh/docs/tutorials/clusters/apparmor/ to https://kubernetes.io/zh/docs/tutorials/security/apparmor/
- Resync, if needed.
