### ISSUE TITLE
Command to delete the zookeeper-ready script from the file system of Pod zk-0  trows an error.

### ISSUE THREAD

**Issue by tarikly** [kubernetes/website#31872]
**This is a Bug Report**

**Problem:**
At https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#testing-for-liveness command to delete the zookeeper-ready script from the file system of Pod zk-0  trows an error.

**Proposed Solution:**
Didn't solve that problem.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#testing-for-liveness

**Comment by jihoon-seo** [comment]
@tarikly Could you copy and paste the error you saw to here?

**Comment by tarikly** [comment]
@jihoon-seo 

Command:

```
kubectl exec zk-0 -- rm /usr/bin/zookeeper-ready
```

Command output:

```
rm: cannot remove '/usr/bin/zookeeper-ready': Permission denied
command terminated with exit code 1
```

Screen capture:
![image](https://user-images.githubusercontent.com/8581805/155519548-3c975ebc-84bc-47eb-a2a4-da463b8c0ceb.png)

**Comment by jihoon-seo** [comment]
I followed the steps, and encountered the same output.

```
❯ kubectl exec zk-0 -- rm /usr/bin/zookeeper-ready
rm: cannot remove '/usr/bin/zookeeper-ready': Permission denied
command terminated with exit code 1
```

---

```
❯ kubectl exec zk-0 -- id
uid=1000(zookeeper) gid=1000(zookeeper) groups=1000(zookeeper)
```

```
❯ kubectl exec -ti zk-0 -- ls -alh /usr/bin/zookeeper-ready
lrwxrwxrwx 1 root root 34 Jun 13  2017 /usr/bin/zookeeper-ready -> /opt/zookeeper/bin/zookeeper-ready
```

```
❯ kubectl exec -ti zk-0 -- ls -alh /opt/zookeeper/bin/zookeeper-ready                        
-rwxr-x--- 1 zookeeper zookeeper 900 Jun 13  2017 /opt/zookeeper/bin/zookeeper-ready
```

```
❯ kubectl exec zk-0 -- rm /opt/zookeeper/bin/zookeeper-ready
(The file was successfully deleted)
```

```
❯ kubectl get pod -w -l app=zk
NAME   READY   STATUS    RESTARTS   AGE
zk-0   1/1     Running   0          7m23s
# Deleted /opt/zookeeper/bin/zookeeper-ready at here
zk-0   0/1     Running   0          18m
zk-0   0/1     Running   1          19m
zk-0   1/1     Running   1          19m
```

**Proposed Solution:**
L776 in [content/en/docs/tutorials/stateful-application/zookeeper.md](https://github.com/kubernetes/website/blob/main/content/en/docs/tutorials/stateful-application/zookeeper.md?plain=1)

```diff
-kubectl exec zk-0 -- rm /usr/bin/zookeeper-ready
+kubectl exec zk-0 -- rm /opt/zookeeper/bin/zookeeper-ready
```

/triage accepted
/good-first-issue

**Comment by jihoon-seo** [comment]
/remove-good-first-issue
@tarikly Are you okay to handle this issue when you review the full content of the zookeeper tutorial and make a new PR? 😊
/assign @tarikly

**Comment by tarikly** [comment]
@jihoon-seo I believe I can do that, keep it assigned.
