### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by msyretis** [kubernetes/website#31870]
specifically this chapter
https://kubernetes.io/docs/concepts/services-networking/ingress/#what-is-ingress

fails to load a schematic that was previously there.

**Comment by jihoon-seo** [comment]
My env:
- Windows 10 Pro 21H2 19044.1526
- Google Chrome 98.0.4758.82 (64bit)

---

For me:
![image](https://user-images.githubusercontent.com/46767780/155429350-fa5359d2-0606-429c-b582-1b474000ac70.png)

**Comment by msyretis** [comment]
Hey, also started working for me later the same evening, different os and
browser to yours.

Thanks for having a look.

**Comment by jihoon-seo** [comment]
Good to hear!
/close
