### ISSUE TITLE
[zh] fix some translations error for zh  docs

### ISSUE THREAD

**Issue by FOWind** [kubernetes/website#31888]
**This is a Bug Report**

**Problem:**
- `content/zh/docs/concepts/cluster-administration/system-metrics.md` 
    line 131 , '启用' should be '弃用'

-  `content/zh/docs/reference/access-authn-authz/_index.md` 
   Title '访问 API' should be ‘API 访问控制'

**Page to Update:**
- https://kubernetes.io/zh/docs/concepts/cluster-administration/system-metrics
- https://kubernetes.io/zh/docs/reference/access-authn-authz/

**Comment by shaggyyy2002** [comment]
#31897 I have commited the changes.

**Comment by jihoon-seo** [comment]
Resolved by #31889 .
/close
