### ISSUE TITLE
Style guide recommends writing Kubernetes in initial caps, but logo has “kubernetes” all-lowercase

### ISSUE THREAD

**Issue by natereid72** [kubernetes/website#31904]
https://kubernetes.io/docs/contribute/style/style-guide/#kubernetes-io-word-list

States "A list of Kubernetes-specific terms and words to be used consistently across the site." and "Kubernetes should always be capitalized."

But at the top left of every page in the docs, is an occurrence of 'kubernetes' with lower case 'k'
<img width="226" alt="image" src="https://user-images.githubusercontent.com/45366367/155667590-a4d54a16-f8e0-4ac1-9e44-805bb93f2772.png">

**Comment by jihoon-seo** [comment]
That is the K8s logo image, not a text, and 'k' in the logo is in lower case.
https://github.com/kubernetes/kubernetes/blob/master/logo/name_blue.svg

**Comment by natereid72** [comment]
granted, and this is the least thing I am concerned with. But as it is, it says to be used consistently across the site. So seems that includes logos with the word kubernetes in it as it's an occurrence of Kubernetes. I know the Kubernetes logo is not going to be changed (but If it was called 7, there wouldn't be any confusion with case), so maybe a simple change in wording "A list of Kubernetes-specific terms and words to be used consistently in text across the site'

**Comment by sftim** [comment]
/retitle Style guide recommends writing Kubernetes in initial caps, but logo has “kubernetes” all-lowercase
