### ISSUE TITLE
Use Cascading Deletion in a Cluster

### ISSUE THREAD

**Issue by faust64** [kubernetes/website#31931]
Running Kubernetes 1.21.6
I'm trying to delete a deployment, while preserving its pods (change the spec.selector.matchLabels, which is immutable, recreating the deployment object without stopping my containers).

It's been a while since I didn't do something like this ... with previous versions of k8s, I would have used `kubectl delete something --cascade=false`

https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#set-orphan-deletion-policy

Apparently, now it's `cascade=orphan`
Although neither orphan or false work.
Adding debugs to kubectl while deleting the object, I  can see the response JSON with some `finalizers:["cascade"]`.
Then, my pods and replicasets are all gone.

I kind of recall reading something about some garbage collection, controllers purging objects with non-existing owner refs (? could be wrong). In doubt, I tried to kick the ownerReferences array from my replicaset: no luck here. It's never really removed, or re-added before I can check back on that object.

How should I proceed to replace my deployment without stopping its containers?

**Comment by tengqm** [comment]
Sounds like a bug rather than documentation issue. Would you file an issue against kubernetes/kubernetes project?

**Comment by faust64** [comment]
sure, https://github.com/kubernetes/kubernetes/issues/108372
