### ISSUE TITLE
Document SIG Docs New Contributor Ambassador Program

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#31946]
cc: @RinkiyaKeDad @natalisucks @reylejano @jimangel

We require more documentation around the New Contributor Ambassador role to set off with the formalization of the process. Opening up this issue to track the progress in these potential areas

- [x] Modify [README](https://github.com/kubernetes/website/README.md)
- [x] Discuss potential for inclusion in Contributor guide for SIG Docs
- [x] If outcome of above discussion is a yes, suitable edits to be made on the Contributor guide.

These are a few places I could think of. Please use this issue as an avenue for discussing any other areas that might benefit from including details about the role.

**Comment by RinkiyaKeDad** [comment]
Thanks for opening the issue to track this @divya-mohan0209! By "Contributor guide" do you mean https://kubernetes.io/docs/contribute/?

**Comment by divya-mohan0209** [comment]
@RinkiyaKeDad : Yes, I don't know if it'd be a good fit given the nature of the contributor guide. But we need to have it documented somewhere as a role like we have the [Release Team shadow/roles](https://github.com/kubernetes/sig-release/tree/master/release-team) under the sig-release repo.

**Comment by RinkiyaKeDad** [comment]
Ping to update the checklist :) Readme has been updated, will start a discussion on Slack to see if the Contributor guide needs to be updated next.

**Comment by RinkiyaKeDad** [comment]
/remove-lifecycle stale

I can get to this next month!

**Comment by divya-mohan0209** [comment]
@RinkiyaKeDad - gentle reminder on this one. Do you need anything from our side?

**Comment by RinkiyaKeDad** [comment]
> @RinkiyaKeDad - gentle reminder on this one. Do you need anything from our side?

Thanks! This totally fell off radar. I'll get the discussions for this going this week!

**Comment by RinkiyaKeDad** [comment]
Started discussions here: https://kubernetes.slack.com/archives/C1J0BPD2M/p1666775238623839

**Comment by divya-mohan0209** [comment]
Hello @RinkiyaKeDad , please may I know if you have had a chance to work on this? Please let us know if you need anything from our side.

**Comment by RinkiyaKeDad** [comment]
Hey @divya-mohan0209, if you see the Slack thread in the comment above, I need someone to confirm if it is okay to proceed with adding the section on that page. LMK if yes, and I will make the PR!

**Comment by divya-mohan0209** [comment]
@RinkiyaKeDad thank you for clarifying. However the expectation was to timebox the consensus seeking process to a few days/weeks. After which, the PR you submit for amending the page would be put through a formal review by the website approvers & reviewers. So, if there is no dissent/feedback, it'd be okay for us to now have a PR opened to k/website per the initial idea & then figure out the placement/duplication there onwards.

**Comment by RinkiyaKeDad** [comment]
Hello! I talked with Sreeram on one of our New Contributors Meet and Greet calls, and they expressed an interest in picking this issue up so I'm assigning them for now. I have communicated what needs to be done over the call to them and given them the required context. @sreeram-venkitesh please feel free to ping me if you have more questions and tag me for a review on the PR!


/assign @sreeram-venkitesh

**Comment by divya-mohan0209** [comment]
@RinkiyaKeDad @sreeram-venkitesh : Any updates on this? Please can we prioritise work on this?

**Comment by sreeram-venkitesh** [comment]
Sorry for the delay! Will work on this on priority.

**Comment by divya-mohan0209** [comment]
@sreeram-venkitesh - Any updates on this, please?

**Comment by sreeram-venkitesh** [comment]
@divya-mohan0209 I have raised a [PR](https://github.com/kubernetes/website/pull/42481) and asked for review from @RinkiyaKeDad . Sorry for the delay in getting this done!

**Comment by divya-mohan0209** [comment]
All the objectives to track the formalisation of the New Contributor Ambassador have been completed with the merge of #42481 . Hence closing this as completed.
/close
