### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by dymax** [kubernetes/website#31950]
This is a great tutorial to grasp the fundamental concepts of Kubernetes. But, I think a concept of how to use/set up a YAML file for different resources has been missed.

**Comment by sftim** [comment]
/language en

@dymax how much does https://kubernetes.io/docs/tutorials/hello-minikube/ cover what you wanted to see?

**Comment by Kartik494** [comment]
@dymax you can refer objects deployments file in kubernetes documentation, like here for deployment [yaml](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment) you will find more on each field of the deployment object.

**Comment by Kartik494** [comment]
@dymax Hi, If you are able to find  yaml  for different resources, Can you close this issue?
