### ISSUE TITLE
Issue with /docs/tasks/configure-pod-container/define-environment-variable-container/

### ISSUE THREAD

**Issue by podollb** [kubernetes/website#3195]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

The page doesn't mention if the env var you set via this method would override pre-existing env vars that the container (per the dockerfile) may have already set.

**Proposed Solution:**

Update the page to define the behavior.

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
@podollb I suspect this is kubernetes specific. Value for an environment variable assigned at runtime would override the one specified in container image.

This is well-known docker/containerd behavior. 

```
$ docker run --rm alpine env | grep HOME
HOME=/root

$ docker run --rm -e HOME=other alpine env | grep HOME
HOME=other
```

Somebody should still decide if this requires documentation.
