### ISSUE TITLE
<kubeadm init> while use this command i am facing this issues pls help me on this 

### ISSUE THREAD

**Issue by prassu4b4** [kubernetes/website#31958]
[init] Using Kubernetes version: v1.23.4
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by jihoon-seo** [comment]
/kind support
Try this:
```
mv /etc/kubernetes/manifests/kube-apiserver.yaml \
/etc/kubernetes/manifests/kube-controller-manager.yaml \
/etc/kubernetes/manifests/kube-scheduler.yaml \
/etc/kubernetes/manifests/etcd.yaml ./
```
and try `kubeadm init` again.

**Comment by RA489** [comment]
@prassu4b4 Please try ` kubeadm reset` and then run `kubeadm init` as workaround.

**Comment by prassu4b4** [comment]
> @prassu4b4 Please try ` kubeadm reset` and then run `kubeadm init` as workaround.

tried no luck

**Comment by neolit123** [comment]
`kubeadm reset` will definitely remove the files reported with a `FileAvailable` error.

also see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> We use GitHub for tracking bugs and feature requests. This isn't the right place to get support for using Kubernetes, but the following resources are available below, thanks for understanding.

/close

**Comment by bestofman** [comment]
I have the same issue and posted that here but no body answered yet!

https://devops.stackexchange.com/questions/17033/the-connection-to-the-server-localhost8080-was-refused-did-you-specify-the-ri

**Comment by hebabaze** [comment]
apt update
apt install containerd.io 
sudo rm /etc/containerd/config.toml 
systemctl restart containerd The

**Comment by majidfarzaneh** [comment]
> apt update apt install containerd.io sudo rm /etc/containerd/config.toml systemctl restart containerd

I had the same error but your advice solved my problem,
Thanks
