### ISSUE TITLE
Serialization format on https://k8s.io/docs/reference/kubernetes-api/common-definitions/quantity/ is hard to read

### ISSUE THREAD

**Issue by MPvHarmelen** [kubernetes/website#31967]
The page does not show the serialization format in a readable way: it seems like there should've been a code block.

**Comment by sftim** [comment]
/kind feature

We don't yet have any mechanism to convey formatting in our API reference code and, later, in the documentation that we generate from it.

/wg api-expression

**Comment by sftim** [comment]
/retitle Serialization format on https://k8s.io/docs/reference/kubernetes-api/common-definitions/quantity/ is hard to read

**Comment by sftim** [comment]
If there were a way to express and then render a [syntax diagram](https://en.wikipedia.org/wiki/Syntax_diagram), that'd be lovely. It'd need some extra tooling somewhere, though.
