### ISSUE TITLE
[zh] Translate Reference/tools/Mapping from dockercli to crictl

### ISSUE THREAD

**Issue by shixiuguo** [kubernetes/website#31981]
Hi, I'm interested to translate the "Reference/Other Tools/Mapping from dockercli to crictl" page.

This is a Feature Request:
translate en/docs/reference/tools/map-crictl-dockercli.md into Chinese.

What would you like to be added:
zh/docs/reference/tools/ map-crictl-dockercli.md

/language zh
/kind feature

**Comment by tengqm** [comment]
This one is done: https://github.com/kubernetes/website/pull/31943
