### ISSUE TITLE
Issue with /docs/getting-started-guides/aws/

### ISSUE THREAD

**Issue by scribnar** [kubernetes/website#3199]
**This is a...** 

- [ Bug Report]

**Problem:**
The document is supposed to show how to run Kubernetes on AWS. However, the script https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh mentions below comment.

That means the whole document should not exist at all. Since, code support for running on aws is withdrawn, this document should be removed as well so that its not misleading.

WARNING: The bash deployment for AWS is obsolete. The
v1.5.x releases are the last to support cluster/kube-up.sh with AWS.
For a list of viable alternatives, see:

  http://kubernetes.io/docs/getting-started-guides/aws/

**Proposed Solution:**

Remove the document or fix the util.sh code

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/aws/

**Comment by remram44** [comment]
Yes. Having a document that tells you to run a command that sends you to the document is absurd.

**Comment by VinceMD** [comment]
so what's the way to install kub 1.6 on AWS?

**Comment by remram44** [comment]
I managed to set it up manually with kubeadm with no issue. I don't have all the integrations working just yet but I mostly don't need them.

**Comment by remram44** [comment]
kube-up is not mentioned anymore in the document, so this can probably be closed.
