### ISSUE TITLE
Annotation kubernetes.io/limit-ranger not documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#31994]
**This is a Bug Report**

**Problem:** Kubernetes uses an annotation, `kubernetes.io/limit-ranger`; however, this annotation is not registered or documented.

**Proposed Solution:**
Document the annotation

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/language en

**Comment by PriyanshuAhlawat** [comment]
can anyone give an example of how this annotation is used.
