### ISSUE TITLE
Improvement for k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/

### ISSUE THREAD

**Issue by ydahan** [kubernetes/website#32006]
Hi,

Please provides examples at each page with reference.

There are options but no reference regarding where or how to configure them (which is essential to use the options).

It is relevant for many pages include:

https://kubernetes-docsy-staging.netlify.app/docs/tasks/debug-application-cluster/audit/

**Comment by sftim** [comment]
/kind feature
/language en

@ydahan perhaps you could sketch out how a revise page might look, so that it's clear to someone who wants to work on this issue?

**Comment by shaggyyy2002** [comment]
@ydahan can you explain?

**Comment by ydahan** [comment]
Yes, in many pages there are targeted pieces of examples without explanation regarding how to implement them. Not all users understand the context of specific configuration. I will try to provide a suggestion regarding how to provide practical information (explanation, example and the context). Personally I find myself looking for alternate  information sources since the one provided is partially/not helpful.

**Comment by ydahan** [comment]
In the specific Audit policy section it's written that you can pass parameters to kube-api server without any further explanation.
![image](https://user-images.githubusercontent.com/15953845/156744271-c7fb8b19-d51f-4c15-bf08-39df59365b58.png).
I used other sources to find that I need to edit the file /etc/kubernetes/manifests/kube-apiserver.yaml. however I had to rollback since the kube-apiserver went missing and no feasible errors where detected by me.

**Comment by sftim** [comment]
This could be a request for a [_tutorial_](https://k8s.io/docs/tutorials/) page on configuring auditing, perhaps?

**Comment by sftim** [comment]
If there are other topics where you want to see a tutorial added, those could be separate issues @ydahan.
