### ISSUE TITLE
Issue with /docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by ApsOps** [kubernetes/website#3200]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This page seems severely outdated. Some flags (for example, `configure-cbr0`) have been removed from code. Basically the whole setup process feels wrong.

**Proposed Solution:**
Revise and update the info with details. This page is very helpful and necessary for understanding the working of components and creating custom setup scripts.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/scratch/

**Comment by zacharysarah** [comment]
@ApsOps Thanks for opening this issue. I'm flagging it for technical review.

**Comment by DanyC97** [comment]
@ApsOps few things changed since you open the issue, am i right in saying that is safe to close the issue ? the page you pointed at no longer exist

**Comment by ApsOps** [comment]
That's a shame. It was really helpful in understanding what all goes behind the scenes for setting up a cluster.

**Comment by sftim** [comment]
https://kubernetes.io/docs/getting-started-guides/scratch/ has indeed gone
/close
