### ISSUE TITLE
Add docs about services about why VRFs are not supported

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#32016]
**This is a Bug Report** 

**Problem:**

right now some folks are interested in  pods  that are on different service networks in the same cluster

**Proposed Solution:**

Add a doc page explaining why this isnt a part of the K8s service model 
- maybe its not even possible bc of the datamodel for service CIDRs???? 
- not sure??? 

**Page to Update:**

https://kubernetes.io/docs/concepts/services-networking/legacy-apps

https://github.com/kubernetes/kubernetes/issues/91728 , cc network plumbing group, references https://docs.openshift.com/container-platform/4.7/networking/multiple_networks/assigning-a-secondary-network-to-a-vrf.html

We discussed this on antrea -live this week, for the full discussion, link is at https://www.youtube.com/watch?v=ZePPz6L2cNQ

**Comment by jayunit100** [comment]
https://github.com/kubernetes/kubernetes/issues/91728  , cc network plumbing group, references https://docs.openshift.com/container-platform/4.7/networking/multiple_networks/assigning-a-secondary-network-to-a-vrf.html

**Comment by sftim** [comment]
I'm really not convinced that this issue is written up clearly enough so that someone new to SIG Docs can pick it up and work on it.

/remove-help
/remove-good-first-issue
/language en
