### ISSUE TITLE
Broken Mermaid graphs

### ISSUE THREAD

**Issue by sergioagm** [kubernetes/website#32010]
There's two graphs made with mermaid.js that are broken on the tutorial page for getting the source IP.

URL: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

**Comment by sftim** [comment]
/triage duplicate

This issue duplicates https://github.com/kubernetes/website/issues/31960

**Comment by chrismetz09** [comment]
Hi @sergioagm, use browser hard refresh `shift + command R` to clear the error. Permanent solution investigation underway.

**Comment by sftim** [comment]
/remove-lifecycle rotten

Still important to fix this.

**Comment by sftim** [comment]
However, it's a duplicate.
/close
