### ISSUE TITLE
Taints and Tolerations

### ISSUE THREAD

**Issue by pnarayanan01** [kubernetes/website#32039]
The documentation mentions 
To remove the taint added by the command above, you can run:

`kubectl taint nodes node1 key1=value1:NoSchedule-`

However the correct command, based on my testing seems to be 
`kubectl taint nodes node1 key1/value1:NoSchedule-`

**Comment by shaggyyy2002** [comment]
hey [pnarayanan01](https://github.com/pnarayanan01) can you please link the document here and where to make the changes

**Comment by pnarayanan01** [comment]
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ 
Under the Concepts heading, the second code snippet

**Comment by shaggyyy2002** [comment]
I have opened a PR. #32042

**Comment by mk46** [comment]
@pnarayanan01 Kindly share kubernetes verson and output of `kubectl describe node <your tainted node> | grep Taints`
/triage needs-information

**Comment by pnarayanan01** [comment]
@mk46 I no longer have access to this environment. However I think the syntax isn't version dependent. Sorry, I couldn't be of more help at the moment.

**Comment by mk46** [comment]
I tried in minikube version: v1.18.0

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
and observed that 
1. if taint by `kubectl taint nodes node1 key1=value1:NoSchedule` then `kubectl taint nodes node1 key1=value1:NoSchedule-` is valid to untaint
2. if taint by `kubectl taint nodes node1 key1/value1:NoSchedule` then `kubectl taint nodes node1 key1/value1:NoSchedule-` is valid to untaint
