### ISSUE TITLE
调度框架

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [kubernetes/website#32036]
There is a bug:
https://kubernetes.io/zh/docs/concepts/scheduling-eviction/scheduling-framework/#:~:text=%E8%BF%9B%E8%A1%8C%E7%BB%91%E5%AE%9A%E3%80%82-,%E6%8B%92%E7%BB%9D,-%E5%A6%82%E6%9E%9C%E4%BB%BB%E4%BD%95%20Permit
"1. 拒绝" should be changed to "2. 拒绝"

https://kubernetes.io/zh/docs/concepts/scheduling-eviction/scheduling-framework/#:~:text=Unreserve%20%E6%8F%92%E4%BB%B6%E3%80%82-,%E7%AD%89%E5%BE%85%EF%BC%88%E5%B8%A6%E6%9C%89%E8%B6%85%E6%97%B6%EF%BC%89,-%E5%A6%82%E6%9E%9C%E4%B8%80%E4%B8%AA%20Permit
"1. 等待（带有超时）" should be changed to "2. 等待（带有超时）"

**Comment by shaggyyy2002** [comment]
[wangxiaoyang-dev](https://github.com/wangxiaoyang-dev) on what lines are the changes required?

**Comment by shaggyyy2002** [comment]
I have opened a PR on #32041.

**Comment by wangxiaoyang-dev** [comment]
OK.
