### ISSUE TITLE
Documentation for automatic ECR authentication when on EC2 is gone in English docs but still present in French docs

### ISSUE THREAD

**Issue by et304383** [kubernetes/website#32043]
**This is a Bug Report**

As per the title, the docs for how built in auth against AWS ECR will happen automatically are GONE in the English (and maybe other language) docs, but still present in the French docs.  I think these should still be present in all docs.

**Proposed Solution:**

Restore the English documentation on how K8s automatically authenticates against ECR if on EC2.

**Page to Update:**
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/containers/images.md
https://github.com/kubernetes/website/blob/main/content/fr/docs/concepts/containers/images.md

**Comment by et304383** [comment]
Apparently this was removed under PR #21438.

**Comment by et304383** [comment]
> /language fr
> 
> We should update the French content to remove that page as well.

Why is that the solution?  How is one supposed to find out that K8s automagically logs into AWS ECR?

**Comment by sftim** [comment]
@et304383 I hope from discussion elsewhere you're now clear on why we only document the behavior of Kubernetes itself, and we usually don't document third party products / software that incorporate Kubernetes components.

**Comment by et304383** [comment]
> @et304383 I hope from discussion elsewhere you're now clear on why we only document the behavior of Kubernetes itself, and we usually don't document third party products / software that incorporate Kubernetes components.

Yes.  But given that I am seeing AWS ECR authentication occur automatically as per the old documentation, I firmly believe this is part of the core functionality of K8s.

One guide in particular:
http://docs.heptio.com/content/private-registries/pr-ecr.html
 >After the IAM role is attached to the node, the kubelet on the node takes care of fetching and refreshing ECR credentials.

This needs to be documented somewhere so folks know this happens automatically and they don't need to go through the creation of secrets and applying those secrets via the `imagePullSecrets` key.

**Comment by sftim** [comment]
I've logged https://github.com/kubernetes/website/issues/32047 - it looks like there is a gap around documenting that legacy mechanism.

@et304383 I'm not sure that it makes sense to leave _this specific issue_ open; it's not work that I'd expect the French localization to prioritize.

**Comment by et304383** [comment]
@sftim  agreed.   I did some digging and it seems that the AWS ECR automagic login is related to the AWS provider:

https://github.com/kubernetes/cloud-provider-aws

So in that sense, I suppose it does fall outside of the core of K8s.

**Comment by sftim** [comment]
https://github.com/kubernetes/cloud-provider-aws is definitely part of the Kubernetes project.

**Comment by sftim** [comment]
/close

This issue is more specific that it needs to be; #32047 should supersede it.
