### ISSUE TITLE
Document kubelet image credential provider extension concept

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#32048]
**This is a Feature Request**

**What would you like to be added**
Mention kubelet image credential providers within https://kubernetes.io/docs/concepts/extend-kubernetes/

**Why is this needed**
The concepts section about [extending Kubernetes](https://kubernetes.io/docs/concepts/extend-kubernetes/) does not list kubelet credential providers. 
https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/ exists but largely in isolation; you'd have to know it existed to find it.

It's also OK to mention this concept elsewhere - and _especially_ encouraged if the feature looks likely to graduate towards beta.

**Comments**
/sig node
/language en
/kind feature

**Comment by vaibhav2107** [comment]
I would like to work on this

**Comment by mehabhalodiya** [comment]
I don't see any updates from @vaibhav2107  so unassigning 🙂 
Feel free to assign it if you are interested in taking it up. Thanks!

/unassign @vaibhav2107

**Comment by sftim** [comment]
The removals of in-tree support - eg https://github.com/kubernetes/kubernetes/pull/116329 - make this documentation more important.
