### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

### ISSUE THREAD

**Issue by bitsector** [kubernetes/website#32079]
Setting KUBECONFIG variable doesn't work very well on macOS (Monterey 12.2.1).

In the line:
`export KUBECONFIG=$KUBECONFIG:config-demo:config-demo-2`
The first colon (:) will make the following character (c) dissappear:
What I get is the mangled text:
/Users/.../.kube/config:/Users/.../.kube/aws-kubeconfigonfig-demo:config-demo-2

What works for me better is explicitly using full paths:
`export KUBECONFIG=$KUBECONFIG:/Users/.../.kube/config-demo:/Users/.../.kube/config-demo-2`

**Comment by tengqm** [comment]
```
export KUBECONFIG=${KUBECONFIG}:config-demo:config-demo-2
```

**Comment by Sea-n** [comment]
Thanks for reporting, I can open a PR to fix this! 😊

/remove-lifecycle stale
/assign
