### ISSUE TITLE
调度策略

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [kubernetes/website#32085]
There is a bug:
Chinese Content: https://kubernetes.io/zh/docs/reference/scheduling/policies/
English Content: https://kubernetes.io/docs/reference/scheduling/policies/

chinese content is different from english content.

**Comment by tengqm** [comment]
The English page has changed a lot.

```
./scripts/lsync.sh content/zh/docs/reference/scheduling/policies.md 
```

/triage accepted
