### ISSUE TITLE
[ja] Translate /docs/reference/scheduling/policies/ into Japanese

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes/website#32082]
**This is a Feature Request**

**What would you like to be added**

Translate [reference/scheduling/policies/](https://kubernetes.io/docs/reference/scheduling/policies/) into Japanese.

**Why is this needed**
This page has not been translated.

**Comments**

/language ja
/assign

**Comment by sftim** [comment]
/retitle [ja] Translate /docs/reference/scheduling/policies/ into Japanese
