### ISSUE TITLE
[zh]Translate docs/reference/kubernetes-api/common-definitions/Status page into Chinese 

### ISSUE THREAD

**Issue by shixiuguo** [kubernetes/website#32089]
**This is a Feature Request**

**What would you like to be added**
Translate docs/reference/kubernetes-api/common-definitions/status.md into Chinese

**Why is this needed**
Not translated yet

**Comments**
/language zh
/assign

**Comment by mengjiao-liu** [comment]
page https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-definitions/status/ has existed.

/close
