### ISSUE TITLE
[zh]Translate docs/reference/kubernetes-api/common-definitions/ResourceFieldSelector page into Chinese

### ISSUE THREAD

**Issue by shixiuguo** [kubernetes/website#32088]
**This is a Feature Request**

**What would you like to be added**
Translate docs/reference/kubernetes-api/common-definitions/resource-field-selector.md into Chinese

**Why is this needed**
Not translated yet

**Comments**
/language zh

**Comment by mengjiao-liu** [comment]
page: https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-definitions/resource-field-selector/

https://github.com/kubernetes/website/pull/32519 worked on it and done.
/close
