### ISSUE TITLE
Mermaid graphs are broken

### ISSUE THREAD

**Issue by lhaendler** [kubernetes/website#32096]
![image](https://user-images.githubusercontent.com/94445906/157029473-263e75e3-b5d9-4953-8a8e-e1b08974d673.png)
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#example-one-topologyspreadconstraint

**Comment by mk46** [comment]
Duplicate of https://github.com/kubernetes/website/issues/31960
/triage duplicate

**Comment by anubha-v-ardhan** [comment]
@lhaendler Its working for me, can you recheck please
![Screenshot_20220310_151010](https://user-images.githubusercontent.com/71918957/157635384-c04e6af0-8239-4244-8f18-d246a1940cc9.png)

**Comment by lhaendler** [comment]
Still Broken for me, I managed to get one successful render after disabling my ad blocker, but after refreshing with disabled ad blocker it was broken again.

OS: MacOS 12.2.1
Browser: Firefox 97.0.2

**Comment by sftim** [comment]
Folks, this is a duplicate issue. Please discuss on https://github.com/kubernetes/website/issues/31960

/close
