### ISSUE TITLE
Docs build container image only supports AMD64 architecture

### ISSUE THREAD

**Issue by stormqueen1990** [kubernetes/website#32099]
**This is a Feature Request**

**What would you like to be added**
Right now, building container images for local use of this repository via `make container-image` does not work with Apple Silicon chips. This is because the Dockerfile downloads the Hugo binary for amd64 architecture.

I have been able to workaround this issue by explicitly asking for `--platform linux/amd64`, however, containers built in this way have very poor performance.

Instead, I would like to contribute a Dockerfile that works for arm64 architecture, in a way that contributors can build container images that work in architectures that are not amd64.

**Why is this needed**
Provide a better contributor experience while creating new documentation pages and testing them locally using containers.

**Comment by stormqueen1990** [comment]
I created pull request https://github.com/kubernetes/website/pull/32100 with a Dockerfile and Makefile target that I have tested to address this issue.

**Comment by sftim** [comment]
/retitle Docs build container image only supports AMD64 architecture
