### ISSUE TITLE
Secrets page shows a Secret manifest instead of Docker config

### ISSUE THREAD

**Issue by stormqueen1990** [kubernetes/website#32105]
**This is a Bug Report**

**Problem:**
In the Docker config section of the Secrets page, the wording currently states that a Docker config generated on-the-fly by `kubectl` will be presented, but presents the Secret manifest instead.

**Proposed Solution:**
Show both the Secret manifest and the Docker config, preceded by wording that states what each one of those are.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by sftim** [comment]
/language en
/triage accepted

PR ##30984 also has a fix for this.

**Comment by stormqueen1990** [comment]
Hi @sftim!

Should I close the PR I opened in this case?

**Comment by Kartik494** [comment]
Hi @stormqueen1990 @sftim as #30984 has been merged so should we close this issue?

**Comment by stormqueen1990** [comment]
Hi @Kartik494! Yes, this issue can be closed!
