### ISSUE TITLE
Regarding baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch

### ISSUE THREAD

**Issue by supaplextor** [kubernetes/website#32117]
Right now https://packages.cloud.google.com/yum/repos/kubernetes-el6-x86_64/repodata/filelists.xml reports zero packages.

I'm unable to install software as outlined on https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Using rpm based Mariner Linux full clean install.

 ![VirtualBox_Mariner Linux Docker Test_07_03_2022_17_21_43](https://user-images.githubusercontent.com/4638774/157140825-ce8e97e0-1944-4fa4-924c-462082180efa.png)

**Comment by supaplextor** [comment]
![VirtualBox_Mariner Linux Docker Test_07_03_2022_17_25_12](https://user-images.githubusercontent.com/4638774/157141169-0e5dace6-6e83-48fc-8596-b0975297b130.png)
First screenshot has old typo, attaching current copy

**Comment by neolit123** [comment]
@supaplextor 
hi, i'm not sure what the issue is, but it might be the `-package-key...` text being on new line.

i cannot reproduce the problem in a `fedora:36` container following the steps here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

```
$ yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

...

Upgraded:
  libblkid-2.38-0.2.fc36.x86_64             libmount-2.38-0.2.fc36.x86_64             libsmartcols-2.38-0.2.fc36.x86_64             libuuid-2.38-0.2.fc36.x86_64            
Installed:
  conntrack-tools-1.4.6-2.fc36.x86_64                      containernetworking-plugins-1.1.0-1.fc37.x86_64              cri-tools-1.19.0-0.x86_64                              
  cryptsetup-libs-2.4.3-2.fc36.x86_64                      dbus-1:1.13.22-1.fc37.x86_64                                 dbus-broker-29-5.fc36.x86_64                           
  dbus-common-1:1.13.22-1.fc37.noarch                      device-mapper-1.02.175-7.fc36.x86_64                         device-mapper-libs-1.02.175-7.fc36.x86_64              
  diffutils-3.8-2.fc36.x86_64                              ebtables-legacy-2.0.11-11.fc36.x86_64                        ethtool-2:5.16-2.fc36.x86_64                           
  iproute-5.15.0-2.fc36.x86_64                             iptables-legacy-1.8.7-16.fc37.x86_64                         iptables-legacy-libs-1.8.7-16.fc37.x86_64              
  iptables-libs-1.8.7-16.fc37.x86_64                       kmod-libs-29-7.fc36.x86_64                                   kubeadm-1.23.4-0.x86_64                                
  kubectl-1.23.4-0.x86_64                                  kubelet-1.23.4-0.x86_64                                      libargon2-20171227-8.fc36.x86_64                       
  libbpf-2:0.7.0-3.fc37.x86_64                             libfdisk-2.38-0.2.fc36.x86_64                                libibverbs-39.0-1.fc36.x86_64                          
  libmnl-1.0.4-15.fc36.x86_64                              libnetfilter_conntrack-1.0.8-4.fc36.x86_64                   libnetfilter_cthelper-1.0.0-21.fc36.x86_64             
  libnetfilter_cttimeout-1.0.0-19.fc36.x86_64              libnetfilter_queue-1.0.5-2.fc36.x86_64                       libnfnetlink-1.0.1-21.fc36.x86_64                      
  libnl3-3.5.0-9.fc36.x86_64                               libpcap-14:1.10.1-3.fc36.x86_64                              libseccomp-2.5.3-2.fc36.x86_64                         
  libutempter-1.2.1-6.fc36.x86_64                          libxkbcommon-1.4.0-1.fc36.x86_64                             psmisc-23.4-3.fc36.x86_64                              
  qrencode-libs-4.1.1-2.fc36.x86_64                        socat-1.7.4.2-2.fc36.x86_64                                  systemd-250.3-6.fc37.x86_64                            
  systemd-libs-250.3-6.fc37.x86_64                         systemd-networkd-250.3-6.fc37.x86_64                         systemd-pam-250.3-6.fc37.x86_64                        
  systemd-resolved-250.3-6.fc37.x86_64                     util-linux-2.38-0.2.fc36.x86_64                              util-linux-core-2.38-0.2.fc36.x86_64                   
  xkeyboard-config-2.35.1-1.fc37.noarch 
```

you can try asking at that Linux distribution forums or k8s forums for help, but these steps are currently working as far as i can tell:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close

**Comment by supaplextor** [comment]
I carefully checked the ruler in vim, it's not a new line. And for whatever reason I reported el6 in the first post when I thought I was using el7, sorry about that confusion.  I found a similar post online, https://serverfault.com/questions/1017828/no-kubelet-kubeadm-kubectl-packages but their caveat was unicode dashes. I checked the yum repo file, and there are normal dashes only in the config file.

yum in Mariner Linux for whatever reason does not know how to handle the --disableexcludes=kubernetes portion so I have to omit that.

[kubernetes.repo.gz](https://github.com/kubernetes/website/files/8220189/kubernetes.repo.gz)

**Comment by supaplextor** [comment]
I was able to install on Fedora Server 35. I took the same kubernetes.repo via scp to Mariner, but Mariner Linux was unable to install. Not a kubernetes issue at this point. Thank you for your time.

[kubernetes.repo.gz](https://github.com/kubernetes/website/files/8220357/kubernetes.repo.gz)
![VirtualBox_Fedora Reference_09_03_2022_21_34_45](https://user-images.githubusercontent.com/4638774/157590564-9f888845-f0cc-4af5-8ff4-c688c845d6a3.png)
![VirtualBox_Mariner Linux Docker Test_09_03_2022_21_36_28](https://user-images.githubusercontent.com/4638774/157590661-0d9f7dae-80b9-4180-bd23-f01cfe65d30a.png)

**Comment by supaplextor** [comment]
![VirtualBox_Mariner Linux Docker Test_10_03_2022_00_33_38](https://user-images.githubusercontent.com/4638774/157611449-514c2ee3-33ac-4756-ad73-7fb593d5ab76.png)

I disabled gpg, and now it is working.
