### ISSUE TITLE
TLS 启动引导，unrecognized feature gate: RotateKubeletClientCertificate

### ISSUE THREAD

**Issue by QiuToo** [kubernetes/website#32119]
问题描述：
[root@two-node1 ~]# systemctl status  kubelet  -l
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 二 2022-03-08 11:43:15 CST; 1s ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 82134 ExecStart=/usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/kubelet-bootstrap.kubeconfig --cert-dir=/etc/kubernetes/pki/ --kubeconfig=/etc/kubernetes/kubelet.kubeconfig --config=/etc/kubernetes/kubelet.json --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.2 --rotate-certificates --alsologtostderr=true --logtostderr=false --log-dir=/var/log/kubernetes --v=2 (code=exited, status=1/FAILURE)
 Main PID: 82134 (code=exited, status=1/FAILURE)

3月 08 11:43:15 two-node1 kubelet[82134]: I0308 11:43:15.427015   82134 flags.go:59] FLAG: --topology-manager-scope="container"
3月 08 11:43:15 two-node1 kubelet[82134]: I0308 11:43:15.427017   82134 flags.go:59] FLAG: --v="2"
3月 08 11:43:15 two-node1 kubelet[82134]: I0308 11:43:15.427020   82134 flags.go:59] FLAG: --version="false"
3月 08 11:43:15 two-node1 kubelet[82134]: I0308 11:43:15.427024   82134 flags.go:59] FLAG: --vmodule=""
3月 08 11:43:15 two-node1 kubelet[82134]: I0308 11:43:15.427027   82134 flags.go:59] FLAG: --volume-plugin-dir="/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"
3月 08 11:43:15 two-node1 kubelet[82134]: I0308 11:43:15.427045   82134 flags.go:59] FLAG: --volume-stats-agg-period="1m0s"
3月 08 11:43:15 two-node1 kubelet[82134]: I0308 11:43:15.427077   82134 feature_gate.go:243] feature gates: &{map[]}
3月 08 11:43:15 two-node1 kubelet[82134]: Flag --network-plugin has been deprecated, will be removed along with dockershim.
3月 08 11:43:15 two-node1 kubelet[82134]: Flag --rotate-certificates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
3月 08 11:43:15 two-node1 kubelet[82134]: E0308 11:43:15.428591   82134 server.go:216] "Failed to set feature gates from initial flags-based config" err="unrecognized feature gate: RotateKubeletClientCertificate"
[root@two-node1 ~]# 
[root@two-node1 ~]# cat  /usr/lib/systemd/system/kubelet.service 
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=docker.service
Requires=docker.service
[Service]
WorkingDirectory=/var/lib/kubelet
ExecStart=/usr/local/bin/kubelet \
  --bootstrap-kubeconfig=/etc/kubernetes/kubelet-bootstrap.kubeconfig \
  --cert-dir=/etc/kubernetes/pki/  \
  --kubeconfig=/etc/kubernetes/kubelet.kubeconfig \
  --config=/etc/kubernetes/kubelet.json \
  --network-plugin=cni  \
  --pod-infra-container-image=k8s.gcr.io/pause:3.2 \
  --rotate-certificates \
  --alsologtostderr=true \
  --logtostderr=false \
  --log-dir=/var/log/kubernetes \
  --v=2
Restart=on-failure
RestartSec=5
 
[Install]
WantedBy=multi-user.target

[root@two-node1 ~]# ls  /etc/kubernetes/
kubelet-bootstrap.kubeconfig  kubelet.json  pki
[root@two-node1 ~]# ls  /etc/kubernetes/pki/
ca.pem
[root@two-node1 ~]# 
[root@two-node1 ~]# vim  /etc/kubernetes/kubelet-bootstrap.kubeconfig 

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVVVNYUHQxbC9oekZmWjAxa3ltQVpmSFRiL1g4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HYzNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEl5TURNd01URXpOVEl3TUZvWERUTXlNREl5TnpFek5USXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HYzNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBenpjS0pnNjNNeEhUL2FURjhsdkQKTjN4NWU5NnlPdlNsWFhMb2RDb1k4WjYvUTdzZVhQWFE4bGdiZFFZQ005SHZhMU9YZHk0VFdDbk9iNXRlRTl0ZQpJNmFBOFc1c25wdzkrSGhIa0k4RHdxK05WakdhNjUzOGNMdXM2NzZhdThVSjZqVXQyUWxuWjlLTEtYdTd6Vy92CmhGejI0K1ZmdmYwbVd4NWVqQWtWVlMra0ZBZ3FnSlFWcEdJb2hSamI4TFc0eW9Yc0U5ZHRPZGdEZ2lDL1NDMkcKbEV5N1QxcUNpVk5USmZpdFBoTm5oT2VadUU0NFBlS2lGTjdwVEZadk90ZE51SElEUmczenlORUdhNngyd3dRagpubmJTYU9xNWFvcEllaDM3dmVlbXNzQ29jcG8vNEdLK0RLY3RNeFdPZ3VwcDhXYnBwYVU2Y3lzSUM1ZCt1RXhaCktRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVWWDBTeE0ya2NkR1ZJL1lBRi9SejRJSG55SVl3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVjZwpjVTlycWNlYmJ4c3ZWZjdlcmhiOUpLY0xNaTdwMGlQWmc4Smk0Mk9ZYWlRUUtnbW5iNVFqcUxLRHFHTkNvUUpICnZQaWRoMnl6UitMT0pWYVg1M2xoZjlNMWJDdXMzNW9BVzdjL1ZGeW1LNmk4WUg0OGJxRzU3N200amhJMHBINU8KRys3eXZsWDZsQmc4ak9tdDU1TFBjcXRTeGxZazZsTk81RmNGOHdtckt6SjNYWHZYcW1xTDhnK005ZVIrSTcybgpPZHQ0cENsSWZoVmlWZHdUTEFYV01wV1ZVd3hNM2VNV3hQR1kwSDZsT25mVEYySC9PYldqZnd4Z3RIT3d4L29lCnBac3lYckFjTUlkVnd3TUY5bmpTUlVzaDc5ZGdlZ2l1V2kwU3ZKT05aM2xabnl0U25VaXFNeGJ5ckZ0UW1IeTYKckhRZ2xKTEhLb05XMHJGUFN4OD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://192.168.2.91:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet-bootstrap
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: kubelet-bootstrap
  user:
    token: ecc07abe3b1717eec9ae22a9c93082c7
[root@two-node1 ~]# cat /etc/kubernetes/kubelet.json
{
  "kind": "KubeletConfiguration",
  "apiVersion": "kubelet.config.k8s.io/v1beta1",
  "authentication": {
    "x509": {
      "clientCAFile": "/etc/kubernetes/pki/ca.pem"
    },
    "webhook": {
      "enabled": true,
      "cacheTTL": "2m0s"
    },
    "anonymous": {
      "enabled": false
    }
  },
  "authorization": {
    "mode": "Webhook",
    "webhook": {
      "cacheAuthorizedTTL": "5m0s",
      "cacheUnauthorizedTTL": "30s"
    }
  },
  "address": "192.168.2.93",
  "port": 10250,
  "readOnlyPort": 10255,
  "cgroupDriver": "systemd",
  "hairpinMode": "promiscuous-bridge",
  "serializeImagePulls": false,
  "featureGates": {
    "RotateKubeletClientCertificate": true,
    "RotateKubeletServerCertificate": true
  },
  "clusterDomain": "cluster.local.",
  "clusterDNS": ["10.255.0.2"]
}

**Comment by tengqm** [comment]
The `RotateKubeletClientCertificate` feature has GA'ed in 1.19. In a cluster version later than that, you can safely remove that feature gate setting. In your case, remove `"RotateKubeletClientCertificate": true,` from your `/etc/kubernetes/kubelet-bootstrap.kubeconfig` file.

/close
