### ISSUE TITLE
Add task document for stub domains and upstream nameservers

### ISSUE THREAD

**Issue by bowei** [kubernetes/website#3211]
We need a tasks description for documenting how to use the configurable stub domains and upstream that was shipped in 1.6.

**Comment by ahmetb** [comment]
@bowei do you have time to add these docs? Would you like to self-assign?

**Comment by tengqm** [comment]
I believed this has been fixed with k8s.io/docs/tasks/administer-cluster/dns-custom-nameservers/ from #4063, #4207 etc.
