### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by scott-guthridge** [kubernetes/website#32133]
This is really an issue about the minikube environment, and may be incorrectly filed here.  Please redirect as needed.

The /root/.vimrc file in the minikube environment sets "tabstop=2".  This line should be deleted.  In vi and vim, indentation level is controlled through the shiftwidth setting **only**, and that setting is correctly set to 2.

The tabstop value, on the other hand, has nothing to do with indentation level in the file.  What setting it to 2 means is: tabs still have a value of 8 spaces, but display them on the screen as if they were 2.  This is rarely what anyone wants -- mixtures of tabs and spaces are displayed ambiguously on the screen, and the file is usually left with completely incorrect indentation.

I know, many people work around these problems by just avoiding tabs altogether.  But tabs actually do have their place, and vi is very good at handling them nicely, provided that the tabstop setting is left always on the default value of 8.  Please remove that line.

**Comment by sftim** [comment]
/team katacoda
/priority awaiting-more-evidence

Can you clarify what you mean by “the minikube environment” @scott-guthridge 

The web page at  states
> The online terminal is a pre-configured Linux environment that can be used as a regular console (you can type commands). Clicking on the blocks of code followed by the ENTER key will execute that command in the terminal.

Do you mean that environment (which is katacoda)? If so, you can remove that configuration by running:
`rm /root/.vimrc`

You can also edit it to match your preference.

**Comment by scott-guthridge** [comment]
Yes, I meant the katacode environment.  I'm suggesting that the default .vimrc is not just a preference difference; rather, the default setting is a bug.  It's always incorrect to change both tabstop and shiftwidth settings in vi.  Vim already removed the 3rd (and probably most problematic of all) tab settings, hardtabs, which really changes the value of a tab to be something other than 8.  That option is now silently ignored.  I should open a bug with vim and suggest they do the same with tabstop.  The world would be a better place without that option.  :-)
