### ISSUE TITLE
kubernetes.io/zh/docs/concepts/policy/pod-security-policy/ page garbled

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/website#32136]
**This is a Bug Report**

**Problem:**
page https://kubernetes.io/zh/docs/concepts/policy/pod-security-policy/  garbled.

![image](https://user-images.githubusercontent.com/44460091/157361567-9b00c8e0-a25d-48d9-aa66-2a9f96e11320.png)

/language zh

**Comment by mengjiao-liu** [comment]
I suddenly saw this page showing garbled characters today.  Can you take a look? @tengqm

**Comment by tengqm** [comment]
@mengjiao-liu Looking into this.

**Comment by tengqm** [comment]
raised  a PR for diagnosis
looks like the cached version of the HTML is corrupted. It is not treated as HTML media type.
