### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by vahid79t** [kubernetes/website#32130]
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

but it needs to be edited to :

echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

because there should not be space https://apt.kubernetes.io/kubernetes-xenial main

**Comment by RA489** [comment]
@vahid79t are you facing any error because of this ?

**Comment by RA489** [comment]
@vahid79t the apt repo fro kuberenetes is https://apt.kubernetes.io/ not https://apt.kubernetes.io/kubernetes-xenial. If you remove space then it will throw Malformed entry error.
