### ISSUE TITLE
Issue with k8s.io/zh/docs/tutorials/

### ISSUE THREAD

**Issue by webf5** [kubernetes/website#32135]
https://kubernetes.io/zh/docs/tutorials/clusters/apparmor/ 
unable to access

**Comment by taniaduggal** [comment]
@sftim how can I redirect link from one to another?

**Comment by mengjiao-liu** [comment]
>  how can I redirect link from one to another?

@taniaduggal  you can update the file https://github.com/kubernetes/website/blob/main/static/_redirects and add 
```
/zh-cn/docs/tutorials/clusters/apparmor   /zh-cn/docs/tutorials/security/apparmor/
```
