### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by WaltSection** [kubernetes/website#32152]
Went to run the tutorial and got the following:  Internal Server Error - Request ID: 01FXQH82VAN6SYS7BN1GKJRWHD

**Comment by sftim** [comment]
/kind bug

This was due a [problem at Netlify](https://www.netlifystatus.com/incidents/f0frsy75h7n2). I think it's fixed - are things working for you @WaltSection ?
