### ISSUE TITLE
使用 kubeconfig 文件组织集群访问

### ISSUE THREAD

**Issue by 1qiqiyang** [kubernetes/website#32164]
If a lower version of Kubelet uses a higher version of KubeconFig to access a higher version of the cluster, will there be a problem?

**Comment by jihoon-seo** [comment]
/kind support
Please refer: https://kubernetes.io/releases/version-skew-policy/#kubelet

**Comment by 1qiqiyang** [comment]
> /kind support Please refer: https://kubernetes.io/releases/version-skew-policy/#kubelet
The cluster I am using is version 1.20 and the description of this version is 404 on the official website

**Comment by jihoon-seo** [comment]
That file is renamed in [here](https://github.com/kubernetes/website/commit/7edf8903737573a419aace58c517b1a09b672667),
so the page you are looking at is https://v1-20.docs.kubernetes.io/docs/setup/release/version-skew-policy/ .

But I can see that
the v1.20 page (https://v1-20.docs.kubernetes.io/docs/setup/release/version-skew-policy/) is not much different from
the latest page (https://kubernetes.io/releases/version-skew-policy/) ,
which seems as a bug.

The issues and PRs that point out this bug exist.
(Ref: #31551)

**Comment by 1qiqiyang** [comment]
Yes, the 1.20 page is nowhere to be found

**Comment by tengqm** [comment]
Either this issue has been fixed by #34189, or we won't fix it because 1.20 is too old to maintain.
I'm closing this issue because we don't have abundant bandwidth to track it. Feel free to reopen if there is something we can fix.
/close
