### ISSUE TITLE
Issue with kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

### ISSUE THREAD

**Issue by shaoyifeng1013** [kubernetes/website#32167]
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#kubernetes-signers

kubernetes.io/kubelet-serving:
4.Permitted key usages - exactly ["key encipherment", "digital signature", **"server auth"**].

in chinese this is client auth

**Comment by jihoon-seo** [comment]
/triage accepted
/language zh
https://github.com/kubernetes/website/blob/1ab5c0c58d179235edf00977b17a8a39209f3539/content/zh/docs/reference/access-authn-authz/certificate-signing-requests.md?plain=1#L285
https://github.com/kubernetes/website/blob/1ab5c0c58d179235edf00977b17a8a39209f3539/content/zh/docs/reference/access-authn-authz/certificate-signing-requests.md?plain=1#L297

**Comment by PriyanshuAhlawat** [comment]
#32176

**Comment by PriyanshuAhlawat** [comment]
#32204
