### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by arthurspa** [kubernetes/website#32174]
Creating Cluster page doesn't show any terminal.

![image](https://user-images.githubusercontent.com/3959458/157660654-ae484933-9480-4bb8-8800-11a4c9e92eca.png)

**Comment by mk46** [comment]
It's working for me 

![cluster create](https://user-images.githubusercontent.com/52198964/158115927-66024441-be26-4055-bf79-0834ebad6ca6.png)
Os: Ubuntu 18.04
Browser: Chrome 97.0.4692.71
Seems like network issue. Please try on different network.

**Comment by arthurspa** [comment]
I had tried on a different network and got the same problem. But today it seems to be working.
