### ISSUE TITLE
Do not have chinese docs: https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/

### ISSUE THREAD

**Issue by twilight0620** [kubernetes/website#32187]
**This is a Bug Report**

**Problem:**
do not have chinese docs:  https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/

**Proposed Solution:**
add chinese docs in website

Comments
/language zh
/assign

**Comment by jihoon-seo** [comment]
Resolved by #32202
/close
