### ISSUE TITLE
Clarify Metrics API as Beta

### ISSUE THREAD

**Issue by chrismetz09** [kubernetes/website#32183]
**This is a Feature Request**

**What would you like to be added**

[Metrics API](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/#metrics-api) section describes the Metrics API. It should be designated as `beta`.

This PR can be pushed using one of two possible options:

1. Add a sentence after the second to last paragraph on the page indicating that the Metrics API is beta. 

2. Encapsulate this sentence using the Hugo {{< note >}} shortcode. An example using this short code is shown at the bottom of  the page. 

**Why is this needed**

Beta K8s APIs should be explicitly noted as beta in the K8s docs.

**Comment by happy4soul** [comment]
I would like to work on this

**Comment by anubha-v-ardhan** [comment]
/assign @happy4soul 
Thank you!
