### ISSUE TITLE
Improvement for k8s.io/docs/reference/using-api/deprecation-guide/

### ISSUE THREAD

**Issue by paschelino** [kubernetes/website#32208]
You could extend the migration guide with examples in a before/after style.

**Comment by sftim** [comment]
/language en
/kind feature

Thanks for this enhancement request @paschelino 
We'll consider it.

**Comment by sftim** [comment]
I'm not sure that the before/after examples are a good fit for our reference docs. I like the idea for doing this somewhere on the site, but it'd be a big commitment to do this for every API deprecation.

I'm going to decline this on the basis that we don't have capacity to staff it.
If the level of contribution changes, we'd be happy to see this reopened.

/close
