### ISSUE TITLE
Issue with the gpgkeys for Kubernetes repository

### ISSUE THREAD

**Issue by thomas-shelby-k8s** [kubernetes/website#32207]
_[When trying to follow advice in the page]_ Install and Set Up kubectl on Linux - [Install using native package management](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management), Red Hat-based distributions:

we are facing an issue when installing kubectl on Redhat/centos7 VM, and when applying:

1. `yum repolist`
```
kubernetes/signature                                                                                                                                                                                                  |  844 B  00:00:00
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x7AA99B80:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)"
 Fingerprint: e89b faec 34d3 1829 362f 7f7b 5668 44f3 7aa9 9b80
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
```
2. `cat /etc/yum.repos.d/kubernetes.repo`
```
[kubernetes]
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
gpgcheck=True
repo_gpgcheck=True
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                 https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

**Comment by sftim** [comment]
@thomas-shelby-k8s I'm going to take the liberty of reformatting the issue description so that it is more readable.

**Comment by sftim** [comment]
I'm not sure if you're reporting a fault @thomas-shelby-k8s or if you're asking for advice.

If there's a fault, please explain how we can replicate it and how the outcome differs from what you expected. If you want advice, _GitHub is not the right place for support requests. You could instead check [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and ask there if your question has not yet been answered._

_You can also post your question on the [Kubernetes Slack workspace](http://slack.k8s.io/) or to the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum._

/triage needs-information
/language en

**Comment by thomas-shelby-k8s** [comment]
@sftim I'm reporting an issue, when installing kubectl, using the following:
1. sudo yum install -y kubectl
```
Loaded plugins: fastestmirror, langpacks
Repository 'kubernetes' is missing name in configuration, using id
Loading mirror speeds from cached hostfile
 * base: de.mirrors.clouvider.net
 * extras: centos.mirror.net-d-sign.de
 * updates: ftp.plusline.net
base                                                                                                                                                                                                                  | 3.6 kB  00:00:00
docker                                                                                                                                                                                                                | 3.5 kB  00:00:00
extras                                                                                                                                                                                                                | 2.9 kB  00:00:00
kubernetes/signature                                                                                                                                                                                                  |  844 B  00:00:00
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x7AA99B80:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)"
 Fingerprint: e89b faec 34d3 1829 362f 7f7b 5668 44f3 7aa9 9b80
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
kubernetes/signature                                                                                                                                                                                                  | 1.4 kB  00:00:00 !!!
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.


 One of the configured repositories failed (kubernetes),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=kubernetes ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable kubernetes
        or
            subscription-manager repos --disable=kubernetes

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true

failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
```
2. The following failuer occurs:
```
failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
```
2. Then if I'm setting `gpgcheck` and `repo_gpgcheck` to False and trying to ` install kubectl` again it is installed successfully.
I assume that the following `gpgkey` are not valid anymore:
```
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                 https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

**Comment by srguglielmo** [comment]
Setting `repo_gpgcheck = 0` fixes the issue. (`gpgcheck` is still enabled, it's just `repo_gpgcheck` that must be disabled here.

**Comment by sftim** [comment]
It looks as if the Linux advice for https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management is out of date. Ideally, the Linux Foundation / CNCF / Kubernetes project would publish its own artifacts and not rely on Google here.

I'm not sure what the fix would be.

My guess is that we do prefer to have all signatures valid and not to recommend that people bypass some of the checks.
/sig security

@kubernetes/sig-release-leads is this a duplicate of an existing issue? If so, let's make that link.

**Comment by ac427** [comment]
any update on this issue? Looks like the issue is only with x86_64
https://github.com/kubernetes/website/pull/32621#issuecomment-1082334348

**Comment by jihoon-seo** [comment]
I googled and found some related issues:
- https://github.com/kubernetes/release/issues/1982
- https://github.com/kubernetes/kubernetes/issues/100757
- https://github.com/kubernetes/kubernetes/issues/60134

And here is a [suggestion](https://github.com/kubernetes/release/issues/1982#issuecomment-1081068425) from @BenTheElder:
> Folks, the Kubernetes project does not manage these keys, nor does the team that voluntarily continues to publish these packages until the project moves to community infrastructure. [#913](https://github.com/kubernetes/release/issues/913) seems to be the current tracking issue for this.
> 
> per https://cloud.google.com/compute/docs/troubleshooting/known-issues#keyexpired the recommendation is to disable GPG check in RPM.
> 
> > To fix this, disable repository GPG key checking in the yum repo configuration by setting repo_gpgcheck=0. In supported Compute Engine base images this setting might be found in /etc/yum.repos.d/google-cloud.repo file. However, your VM can have this set in different repository configuration files or automation tools.
> > Yum repositories do not usually use GPG keys for repository validation. Instead, the https endpoint is trusted.

---

So my suggestion for K8s Docs is:

In `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md` and
`content/en/docs/tasks/tools/install-kubectl-linux.md`,

```diff
-repo_gpgcheck=1
+repo_gpgcheck=0
```

**Comment by sftim** [comment]
> [skip PGP checking]

At a minimum, we should explain in a comment why this setting is OK. Otherwise folks are bound to ask / file issues / etc.

Better would be to migrate away from recommending Google-made packages. It'd be better to be wholly neutral of vendors here (publish our own packages); failing that, we can provide links to packages from Linux distributions:
- Fedora
- Ubuntu
- Debian

etc.

**Comment by jihoon-seo** [comment]
@sftim As far as I digged:

[Fedora]
It seems that in the official Fedora packages repo (https://packages.fedoraproject.org/),
- the `kubernetes-kubeadm` package exists: https://packages.fedoraproject.org/pkgs/kubernetes/kubernetes-kubeadm/
- there is no `kubectl` package; see https://packages.fedoraproject.org/search?query=kubectl
  - but there exists a [package `kubernetes-client`](https://packages.fedoraproject.org/pkgs/kubernetes/kubernetes-client/). I am not sure whether this package contains `kubectl` or not.
- there is no `kubelet` package; see https://packages.fedoraproject.org/search?query=kubelet
  - but we might check these:
  - https://packages.fedoraproject.org/pkgs/kubernetes/
  - https://packages.fedoraproject.org/pkgs/kubernetes/kubernetes/
  - https://packages.fedoraproject.org/pkgs/kubernetes/kubernetes-master/
  - https://packages.fedoraproject.org/pkgs/kubernetes/kubernetes-node/

[Ubuntu]
It seems that in the official Ubuntu packages repo, the packages (`kubeadm`, `kubectl`, `kubelet`) does not exist.
- https://packages.ubuntu.com/
- https://packages.ubuntu.com/search?keywords=kubeadm&searchon=names&suite=jammy&section=all
- https://packages.ubuntu.com/search?keywords=kubectl&searchon=names&suite=jammy&section=all
- https://packages.ubuntu.com/search?keywords=kubelet&searchon=names&suite=jammy&section=all

Instead, `snap` provides those packages.
- https://snapcraft.io/
- https://snapcraft.io/search?q=kubeadm
- https://snapcraft.io/search?q=kubectl
- https://snapcraft.io/search?q=kubelet

[Debian]
It seems that in the official Debian packages repo, the packages (`kubeadm`, `kubectl`, `kubelet`) does not exist.
- https://www.debian.org/distrib/packages
- https://packages.debian.org/search?keywords=kubeadm&searchon=names&suite=stable&section=all
- https://packages.debian.org/search?keywords=kubectl&searchon=names&suite=stable&section=all
- https://packages.debian.org/search?keywords=kubelet&searchon=names&suite=stable&section=all

**Comment by BenTheElder** [comment]
> Better would be to migrate away from recommending Google-made packages. It'd be better to be wholly neutral of vendors here (publish our own packages); failing that, we can provide links to packages from Linux distributions:


To be clear: the packaging sources are in k/release despite being built on my workstation often (needlessly! there's no real reason this can't be part of the Kubernetes release cloud build, we just block changes to the packaging ...), the packages themselves are defined by the project.

The google specific part is the package hosting and signing, which piggybacks on the GCP package host.

It would be most excellent to move to community packages, but there are none.

There are no other deb/rpm packages for Kubernetes.

> At a minimum, we should explain in a comment why this setting is OK. Otherwise folks are bound to ask / file issues / etc.

There are more details about the recommendation in the link quoted above. I think we should be linking there.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/release/issues/913

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/release/issues/913#issuecomment-1081121833

**Comment by sftim** [comment]
Based on https://github.com/kubernetes/kubernetes/issues/110667#issuecomment-1161855532, I'm persuaded that we can and _should_ omit mention of `repo_gpgcheck` from the docs.
This will apply the YUM default setting which is not to check the signature on repo metadata.

Because that metadata is always accessed over TLS, and the webservers are run by an organization with a reputation for doing TLS well, I think it's absolutely fine.

**Comment by manaschandrasahoo** [comment]
one word - thank u
