### ISSUE TITLE
This page contribute/style/diagram-guide/ has no Chinese version

### ISSUE THREAD

**Issue by javadoors** [kubernetes/website#32201]
**This is a Bug Report**
This page contribute/style/diagram-guide/ has no Chinese version

**Problem:**
This page contribute/style/diagram-guide/ has no Chinese version

**Proposed Solution:**
Translate Chinese version for contribute/style/diagram-guide/

**Page to Update:**
https://kubernetes.io/docs/contribute/style/diagram-guide/

v1.23

NA

Comments
/language zh
/assign

**Comment by tengqm** [comment]
It is being worked on.
https://github.com/kubernetes/website/pull/31912

**Comment by javadoors** [comment]
ok
