### ISSUE TITLE
Enforce Pod Security Standards by Configuring the Built-in Admission Controller

### ISSUE THREAD

**Issue by jmcmeek** [kubernetes/website#32215]
In the v1beta1 admission config example, I had to use `runtimeClasses` rather than `runtimeClassNames`

See https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/pod-security-admission/admission/api/v1beta1/types.go#L40-L44

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/
