### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/included/optional-kubectl-configs-pwsh/ not sopport powershell

### ISSUE THREAD

**Issue by Ricky816845** [kubernetes/website#32229]
![image](https://user-images.githubusercontent.com/20158450/158029501-f415640c-4500-49cf-9139-c0c11d954062.png)

**Comment by mk46** [comment]
@Ricky816845 Thanks for reporting, 
Powershell support was added in v1.23 by https://github.com/kubernetes/kubernetes/pull/103758.
Kindly check your kubectl version.
@sftim Could we mention something like `supported in kubectl v1.23 or later` ?

**Comment by Ricky816845** [comment]
The version is 1.22, which is installed from Docker Desktop.
After installing kubernetes-cli via chocolatey doesn't seem to point to the correct version
Found the problem, thanks.
