### ISSUE TITLE
The "kubernetes-cni" package is not mentioned in the package list

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/website#32222]
**This is a Bug Report**

**Problem:**

The "kubernetes-cni" is not mentioned, in the list of packages installed by kubernetes

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#kubernetes-binaries-and-package-contents

> Package name | Description
> -- | --
> `kubeadm` | Installs the /usr/bin/kubeadm CLI tool and the kubelet drop-in file for the kubelet.
> `kubelet` | Installs the kubelet binary in /usr/bin and CNI binaries in /opt/cni/bin.
> `kubectl` | Installs the /usr/bin/kubectl binary.
> `cri-tools` | Installs the /usr/bin/crictl binary from the [cri-tools git repository](https://github.com/kubernetes-sigs/cri-tools).

**Proposed Solution:**

Add a new row:

`kubernetes-cni` | Installs the /opt/cni/bin binaries from the [plugins git repository](https://github.com/containernetworking/plugins).

**Page to Update:**

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

Kubernetes Version:
v1.23.4

Additional Information:
The `kubernetes-cni` package is a dependency, from both `kubeadm` and `kubelet`.

```
Package: kubeadm
Version: 1.23.4-00
...
Depends: kubelet (>= 1.19.0), kubectl (>= 1.19.0), kubernetes-cni (>= 0.8.7), cri-tools (>= 1.19.0)
```

**Comment by PriyanshuAhlawat** [comment]
#32228

**Comment by afbjorklund** [comment]
The old text should also be removed from the `kubelet` row:

~~Installs the kubelet binary in /usr/bin and CNI binaries in /opt/cni/bin.~~

Installs the `/usr/bin/kubelet` binary.

Otherwise the content would be duplicated, between the packages.

**Comment by neolit123** [comment]
There was a plan by sig release to consolidate the cni package inside the kubelet package but that did not go well due to package manager errors and complexities for upgrading users.

+1 to reflect current state.

**Comment by sftim** [comment]
/sig cluster-lifecycle
/triage accepted

Aside: I'd be tempted to move https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/#kubernetes-binaries-and-package-contents so that it lives inside https://kubernetes.io/docs/reference/node/

**Comment by sftim** [comment]
We could instead move that section of the page to live within https://kubernetes.io/releases/

**Comment by neolit123** [comment]
Moving the package list to another location makes sense. I think "installing kubeadm" is the only page that talks about packages today (?) so that seems like a good fit. But ideally there ahould be a sig release page that talks about all produced artifacts - source tars, deb, rpm, images etc.

**Comment by neolit123** [comment]
i'm sort of -1 of enumerating the deps of e.g. the kubelet package or other packages on the website.
these are in flux and sig node are not maintaining them.

linking to the deb/rpm specs might not be a stable link either.
the kubelet deps are not enumerated anywhere by the owners - sig node.

**Comment by afbjorklund** [comment]
So they (crictl and /opt/cni) are undocumented on purpose ?

**Comment by neolit123** [comment]
i'm not sure i understand.
what i'm trying to say above is that we should probably accurately enumerate kubeadm, kubelet, kubectl, cri-tools, kubernetes-cni but not their inner deps like socat and iptables, etc.

**Comment by afbjorklund** [comment]
Thanks for clarifying, sounds good.

**Comment by neolit123** [comment]
Moving the package list to another location makes sense. I think
"installing kubeadm" is the only page that talks about packages today (?)
so that seems like a good fit. But ideally there ahould be a sig release
page that talks about all produced artifacts - source tars, deb, rpm,
images etc.
