### ISSUE TITLE
colocated vs collocated vs co-located

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#32242]
**This is a Bug Report**

**Problem:**

The docs contain all three terms: colocated, collocated, co-located

**Proposed Solution:**

Agree on **one** term

**Page to Update:**

https://kubernetes.io/search/?q=colocated

https://kubernetes.io/search/?q=collocated

https://kubernetes.io/search/?q=co-located

**Comment by sftim** [comment]
All three are acceptable. So it's a bug, but not an important bug to fix.

/priority awaiting-more-evidence

**Comment by guettli** [comment]
@sftim if you tell me the preferred term (colocated, collocated or co-located), then I can create a corresponding PR.
