### ISSUE TITLE
Issue with /docs/concepts/ : missing description of kubernetes cluster itself

### ISSUE THREAD

**Issue by ebullient** [kubernetes/website#3224]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**

The kubernetes concepts page misses basic information about kubernetes clusters themselves

**Proposed Solution:**

Some information from the tutorial, could be moved into the concepts page to give a better introduction to kubernetes clusters (as a concept): 
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/

**Page to Update:**
https://kubernetes.io/docs/concepts/

**Comment by gtirloni** [comment]
It seems that information is available in https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

**Comment by zacharysarah** [comment]
@ebullient The concept docs could use an overall quality improvement. I'm flagging this for work on that basis. 👍
