### ISSUE TITLE
[zh] Missing Chinese translation docs: https://kubernetes.io/blog/2022/02/16/sig-node-ci-subproject-celebrates/

### ISSUE THREAD

**Issue by sarazqy** [kubernetes/website#32267]
This is a Bug Report

Problem:
missing Chinese translation docs: https://kubernetes.io/blog/2022/02/16/sig-node-ci-subproject-celebrates/

Proposed Solution:
add Chinese translation docs in website Kubernetes Blog
 
Comments
/language zh

**Comment by ydFu** [comment]
This issue is being handled by PR #32440.

**Comment by ydFu** [comment]
/retitle [zh] Missing Chinese translation docs: https://kubernetes.io/blog/2022/02/16/sig-node-ci-subproject-celebrates/

**Comment by ydFu** [comment]
This issue is resolved by PR #32440.
/close
