### ISSUE TITLE
Translate Reference/kubernetes-api/common-definitions/TypedLocalObjectReference

### ISSUE THREAD

**Issue by liuzhilin12** [kubernetes/website#32269]
Hi,I am interested to translate the "reference/kubernetes-api/common-definitions/TypedLocalObjectReference"
This is a Feature Request:
translate en/docs/reference/kubernetes-api/common-definitions/typed-local-object-reference.md

What would you like to be added:
zh/docs/reference/kubernetes-api/common-definitions/typed-local-object-reference.md

/language zh
/kind feature

**Comment by twilight0620** [comment]
it seems alreay has the same issues: https://github.com/kubernetes/website/issues/32090
