### ISSUE TITLE
Issue with /docs/tasks/administer-cluster/upgrade-1-6/

### ISSUE THREAD

**Issue by t0mmyt** [kubernetes/website#3226]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

The page refers to the following document on moving from etcd 2.3 -> 3.x however this will still mean that /registry data is stored under the v2 API in v3.x and therefore not leveraging the v3 features.  There is no mention of the data migration from 2 to 3.

https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html

**Page to Update:**
~~http://kubernetes.io/docs/admin/upgrade-1-6/~~
https://kubernetes.io/docs/tasks/administer-cluster/upgrade-1-6/

**Comment by ahmetb** [comment]
@timothysc can you please take this one?

**Comment by t0mmyt** [comment]
Edited due to unstable doc paths

**Comment by zacharysarah** [comment]
@timothysc 👋 Any updates?
