### ISSUE TITLE
修复翻译 Pod 分配给节点亲和性nodeSelectorTerms的解释-Fix the translation about nodeSelectorTerms of Node affinity

### ISSUE THREAD

**Issue by irisrain** [kubernetes/website#32264]
如果你同时指定了 nodeSelector 和 nodeAffinity，两者必须都要满足， 才能将 Pod 调度到候选节点上。

如果你指定了多个与 nodeAffinity 类型关联的 nodeSelectorTerms，则 如果其中一个 nodeSelectorTerms 满足的话，pod将可以调度到节点上。

如果你指定了多个与 nodeSelectorTerms 关联的 matchExpressions，则 只有当所有 matchExpressions 满足的话，Pod 才会可以调度到节点上。

以上描述在1.18版验证过，是错误的，应该是下面描述才正确，不知道是不是BUG，请查验下。

如果你指定了多个与 nodeAffinity 类型关联的 nodeSelectorTerms，则 只有当所有 nodeSelectorTerms 满足的话，pod才会可以调度到节点上。

如果你指定了多个与 nodeSelectorTerms 关联的 matchExpressions，则 如果其中一个matchExpressions 满足的话，Pod 将可以调度到节点上。

Page to Update:
https://kubernetes.io/zh/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by tengqm** [comment]
Will not fix.
The upstream page has been heavily revised (rewritten).
Need a retranslation.
/close
