### ISSUE TITLE
kubectl Cheat Sheet: functions inside aliases

### ISSUE THREAD

**Issue by mkq** [kubernetes/website#32275]
This shell code
```
# short alias to set/show context/namespace (only works for bash and bash-compatible shells, current context to be set before using kn to set namespace) 
alias kx='f() { [ "$1" ] && kubectl config use-context $1 || kubectl config current-context ; } ; f'
alias kn='f() { [ "$1" ] && kubectl config set-context --current --namespace $1 || kubectl config view --minify | grep namespace | cut -d" " -f6 ; } ; f'
```
declares functions (which make sense) inside wrapper aliases (which I question).

I tend to agree with [this stackoverflow answer](https://stackoverflow.com/a/57377914) that it's probably cargo cult programming. Could you please add an explanation for the extra aliases or remove them?

**Comment by sftim** [comment]
I'm happy to remove the aliases; they're not teaching _Kubernetes_ as much as they are teaching bash.

We could also add a _blog article_ that offers some tips and tricks on setting up your shell for effective working with kubectl, to substitute for the slimmed down cheat sheet. We can add that article no matter which approach we take to this issue.
/language en

**Comment by mkq** [comment]
Yes, I think moving the shell integration to another page would be good.

But my point was: Could you please simplify the code to plain functions without the aliases like this
```
# short alias to set/show context/namespace (only works for bash and bash-compatible shells, current context to be set before using kn to set namespace) 
kx() { [ "$1" ] && kubectl config use-context $1 || kubectl config current-context ; }
kn() { [ "$1" ] && kubectl config set-context --current --namespace $1 || kubectl config view --minify | grep namespace | cut -d" " -f6 ; }
```
or tell me I'm wrong and explain (not only in this issue, but in the cheat sheet) the need for the extra functions?
