### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/quality-service-pod/

### ISSUE THREAD

**Issue by joja19** [kubernetes/website#32280]
I came to this page to understand the impact of QoS of pods on pod operations and on the nodes. This needs to be clarified.

**Comment by sftim** [comment]
We could add a concept or reference page about QoS for Pods

Some of the information in https://kubernetes.io/blog/2021/11/26/qos-memory-resources/ would be useful towards making that new page.

/kind feature
/language en
