### ISSUE TITLE
Reference to #32273,the zh version link will be modified for /docs/reference/labels-annotations-taints/_index.md page 

### ISSUE THREAD

**Issue by javadoors** [kubernetes/website#32288]
**This is a Bug Report**

There is a link /docs/tutorials/clusters/seccomp on line 481 of the page content \en\docs\reference\labels-annotations-taints_index.md,but this link does not exist.

**Problem:**
There is a link /docs/tutorials/clusters/seccomp on line 481 of the page content\en\docs\reference\labels-annotations-taints_index.md,but this link does not exist.
**Proposed Solution:**
[sftim](https://github.com/sftim) commented [12 hours ago](https://github.com/kubernetes/website/issues/32273#issuecomment-1067979444)
https://kubernetes.io/docs/tutorials/clusters/seccomp/ redirects to https://kubernetes.io/docs/tutorials/security/seccomp/

We should update https://kubernetes.io/docs/reference/labels-annotations-taints/ so that it hyperlinks to https://kubernetes.io/docs/tutorials/security/seccomp/ instead.

**Page to Update:**
https://kubernetes.io/zh/docs/reference/labels-annotations-taints/_index.md

v1.23

NA

Comments
/language zh
/assign

**Comment by Sea-n** [comment]
Already done, next time we can use `fixes #32288` in #33727 PR description to auto close this.

/close
