### ISSUE TITLE
Perform a Rolling Update on a DaemonSet

### ISSUE THREAD

**Issue by Celthi** [kubernetes/website#32287]
In https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/, the para says that 
> You may want to set [.spec.updateStrategy.rollingUpdate.maxUnavailable](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable) (default to 1), [.spec.minReadySeconds](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds) (default to 0) and [.spec.updateStrategy.rollingUpdate.maxSurge](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSetSpec) (a beta feature and defaults to 0) as well.

But after I click the page, I find no `.spec.updateStrategy.rollingUpdate.maxSurge` and I can only see `.spec.strategy`. I also try in my env, the `.spec.strategy.rollingUpdate.maxSurge' works but `updateStrategy` does not.

>error: error validating "dep-hello.yaml": error validating data: ValidationError(Deployment.spec): unknown field "updateStrategy" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

 Is this document outdated? I can make a fix if it is.

**Comment by Shubham82** [comment]
Hi @Celthi 
Both DaemonSet and Deployment use these 3 fields, linking to the deployment creates some confusion or misleading. I think we could link  `.spec.updateStrategy.rollingUpdate.maxUnavailable` and `.spec.minReadySeconds` to [DaemonSet](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/daemon-set-v1/#DaemonSet) , same as `.spec.updateStrategy.rollingUpdate.maxSurge`

refer to this issue for more info: #31311

**Comment by Shubham82** [comment]
> We only add that label for issues that have a barrier to entry that is zero or close to it.
Thanks, @sftim  for this information.

Actually, I forget to mention the page in my comment, This is the page we have to update: [Perform a Rolling Update on a DaemonSet](https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/)
