### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

### ISSUE THREAD

**Issue by nonomu** [kubernetes/website#32299]
We tried to install exactly  as the guide , windows node cannot connect to Linux cluster.
Kubelet service cannot start at all.

We using windows server 2019 and CentOS cluster with kubespray.
kubectl version 1.21.6v on both of them

**Comment by neolit123** [comment]
normally such problems should be reported against the https://github.com/kubernetes-sigs/sig-windows-tools repository, so not clear if t here is a documentation problem or something else is happening.

there is also a tracking issue to update the kubeadm / windows docs:
https://github.com/kubernetes/website/issues/31428

/sig windows cluster-lifecycle

**Comment by neolit123** [comment]
might be better to log an issue in https://github.com/kubernetes-sigs/sig-windows-tools and provide there full system logs that hint on why the kubelet is not starting.

**Comment by tengqm** [comment]
Please feel free to reopen if this has something to do with documentation.
/close
