### ISSUE TITLE
Add documentation for metric series that Kubernetes components emit

### ISSUE THREAD

**Issue by vsxen** [kubernetes/website#32302]
**This is a Feature Request**

**What would you like to be added**
Add System Components metrics introduction
such as
```golang
//source  vendor/k8s.io/component-base/metrics/testutil/promlint.go


	// k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/egressselector
	"apiserver_egress_dialer_dial_failure_count", // counter metrics should have "_total" suffix

	// k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz
	"apiserver_request_total", // label names should be written in 'snake_case' not 'camelCase'

	// k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters
	"authenticated_user_requests", // counter metrics should have "_total" suffix
	"authentication_attempts",     // counter metrics should have "_total" suffix

	// kube-apiserver
	"aggregator_openapi_v2_regeneration_count",
	"apiserver_admission_step_admission_duration_seconds_summary",
	"apiserver_current_inflight_requests",
	"apiserver_longrunning_gauge",
	"get_token_count",
	"get_token_fail_count",
	"ssh_tunnel_open_count",
	"ssh_tunnel_open_fail_count",

	// kube-controller-manager
	"attachdetach_controller_forced_detaches",
	"authenticated_user_requests",
	"authentication_attempts",
	"get_token_count",
	"get_token_fail_count",
	"node_collector_evictions_number",
```

**Why is this needed**

**Comment by sftim** [comment]
Hi @vsxen 

Why is this needed? Filling in that information will help contributors prioritize the feature request.

/triage needs-information
/language en

**Comment by tengqm** [comment]
I was trying to find this data as well. I need to know the list of metrics supported by each and every control plane components for health diagnosis, performance improvement, and dynamic resource planning.

**Comment by vsxen** [comment]
I want to set some alert in prometheus for system components.

when `apiserver` need to get token and open ssh tunnel？I don't understand.

**Comment by tengqm** [comment]
> when apiserver need to get token and open ssh tunnel？I don't understand.

The API server, when talking to kubelets via the PodResources API or the logging, profiling APIs, needs to open a SSL connection to the kubelet servers. The API server also needs to authenticate to Webhooks (authentication, authorization, addmission, etc). This is my understanding.

**Comment by vsxen** [comment]
> The API server, when talking to kubelets via the PodResources API or the logging, profiling APIs, needs to open a SSL connection to the kubelet servers. The API server also needs to authenticate to Webhooks (authentication, authorization, addmission, etc). This is my understanding.

But the vaule always is zero even when I run `kubectl exec ` & `kubectl port-forward`

```
// source pkg/kubelet/cri/streaming/server.go

		{"/exec/{token}", s.serveExec},
		{"/attach/{token}", s.serveAttach},
		{"/portforward/{token}", s.servePortForward},
```

**Comment by tengqm** [comment]
> But the vaule always is zero even when I run kubectl exec & kubectl port-forward

Maybe it is due to your kubelet configuration?

**Comment by vsxen** [comment]
ping

**Comment by sftim** [comment]
@vsxen could you explain more about which page you recommend changing, and what should be added?

Alternatively: describe a task that a reader might want to achieve, and highlight gaps in how they could learn to perform that task.

**Comment by vsxen** [comment]
for example: apiserver

when I run `k get --raw /metrics |grep TYPE`, I can see  apiserver has this metrics

My questions is:

1. which metrics can tell me apiserver is slow so I should  add new instances
2. which metrics can tell me aggr api is ok (v1beta1.metrics.k8s.io)
3. why apiserver has `ssh_tunnel_open_count`  and `workqueue_depth` metrics 
4. what should I do if `workqueue_depth` is always 1

https://github.com/kubernetes/kubernetes/issues/106513

https://sysdig.com/blog/monitor-kubernetes-api-server/

```
# TYPE aggregator_openapi_v2_regeneration_count counter
# TYPE aggregator_openapi_v2_regeneration_duration gauge
# TYPE apiextensions_openapi_v2_regeneration_count counter
# TYPE apiserver_admission_controller_admission_duration_seconds histogram
# TYPE apiserver_admission_step_admission_duration_seconds histogram
# TYPE apiserver_admission_step_admission_duration_seconds_summary summary
# TYPE apiserver_admission_webhook_admission_duration_seconds histogram
# TYPE apiserver_audit_event_total counter
# TYPE apiserver_audit_level_total counter
# TYPE apiserver_audit_requests_rejected_total counter
# TYPE apiserver_client_certificate_expiration_seconds histogram
# TYPE apiserver_current_inflight_requests gauge
# TYPE apiserver_init_events_total counter
# TYPE apiserver_longrunning_gauge gauge
# TYPE apiserver_registered_watchers gauge
# TYPE apiserver_request_count counter
# TYPE apiserver_request_duration_seconds histogram
# TYPE apiserver_request_latencies histogram
# TYPE apiserver_request_latencies_summary summary
# TYPE apiserver_request_terminations_total counter
# TYPE apiserver_request_total counter
# TYPE apiserver_response_sizes histogram
# TYPE apiserver_storage_data_key_generation_duration_seconds histogram
# TYPE apiserver_storage_data_key_generation_failures_total counter
# TYPE apiserver_storage_data_key_generation_latencies_microseconds histogram
# TYPE apiserver_storage_envelope_transformation_cache_misses_total counter
# TYPE apiserver_watch_events_sizes histogram
# TYPE apiserver_watch_events_total counter
# TYPE authenticated_user_requests counter
# TYPE authentication_attempts counter
# TYPE etcd_object_counts gauge
# TYPE etcd_request_duration_seconds histogram
# TYPE etcd_request_latencies_summary summary
# TYPE get_token_count counter
# TYPE get_token_fail_count counter
# TYPE go_gc_duration_seconds summary
# TYPE go_goroutines gauge
# TYPE go_info gauge
# TYPE go_memstats_alloc_bytes gauge
# TYPE go_memstats_alloc_bytes_total counter
# TYPE go_memstats_buck_hash_sys_bytes gauge
# TYPE go_memstats_frees_total counter
# TYPE go_memstats_gc_cpu_fraction gauge
# TYPE go_memstats_gc_sys_bytes gauge
# TYPE go_memstats_heap_alloc_bytes gauge
# TYPE go_memstats_heap_idle_bytes gauge
# TYPE go_memstats_heap_inuse_bytes gauge
# TYPE go_memstats_heap_objects gauge
# TYPE go_memstats_heap_released_bytes gauge
# TYPE go_memstats_heap_sys_bytes gauge
# TYPE go_memstats_last_gc_time_seconds gauge
# TYPE go_memstats_lookups_total counter
# TYPE go_memstats_mallocs_total counter
# TYPE go_memstats_mcache_inuse_bytes gauge
# TYPE go_memstats_mcache_sys_bytes gauge
# TYPE go_memstats_mspan_inuse_bytes gauge
# TYPE go_memstats_mspan_sys_bytes gauge
# TYPE go_memstats_next_gc_bytes gauge
# TYPE go_memstats_other_sys_bytes gauge
# TYPE go_memstats_stack_inuse_bytes gauge
# TYPE go_memstats_stack_sys_bytes gauge
# TYPE go_memstats_sys_bytes gauge
# TYPE go_threads gauge
# TYPE grpc_client_handled_total counter
# TYPE grpc_client_msg_received_total counter
# TYPE grpc_client_msg_sent_total counter
# TYPE grpc_client_started_total counter
# TYPE kubernetes_build_info gauge
# TYPE process_cpu_seconds_total counter
# TYPE process_max_fds gauge
# TYPE process_open_fds gauge
# TYPE process_resident_memory_bytes gauge
# TYPE process_start_time_seconds gauge
# TYPE process_virtual_memory_bytes gauge
# TYPE process_virtual_memory_max_bytes gauge
# TYPE rest_client_request_duration_seconds histogram
# TYPE rest_client_request_latency_seconds histogram
# TYPE rest_client_requests_total counter
# TYPE ssh_tunnel_open_count counter
# TYPE ssh_tunnel_open_fail_count counter
# TYPE workqueue_adds_total counter
# TYPE workqueue_depth gauge
# TYPE workqueue_longest_running_processor_seconds gauge
# TYPE workqueue_queue_duration_seconds histogram
# TYPE workqueue_retries_total counter
# TYPE workqueue_unfinished_work_seconds gauge
# TYPE workqueue_work_duration_seconds histogram
```

**Comment by sftim** [comment]
/retitle Add documentation for metric series that Kubernetes components emit

We might want to split this into 2 requests:
1. Document the stable metrics
2. Document the other (unstable) metrics

**Comment by tengqm** [comment]
I can vaguely recall that there was a PR fixing the pointer to the stable k8s metrics page (which is currently almost empty).
The SIG Instrumentation team does have a list of stable metrics [here](https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/testdata/stable-metrics-list.yaml), but I have no idea if the team has a registry for all component metrics.

**Comment by sftim** [comment]
I've accepted this in that it's something that SIG Docs would agree is nice to work on; I've marked it as a backlog item because there are other improvements that we would prioritize before this one.

Anyone who wants to help out here is very welcome to.

**Comment by sftim** [comment]
Done in https://github.com/kubernetes/website/pull/37522

/close
