### ISSUE TITLE
[zh]Translate /docs/reference/config-api/kubelet-config.v1alpha1/ page into Chinese

### ISSUE THREAD

**Issue by javadoors** [kubernetes/website#32317]
**This is a Feature Request**

[zh]Translate /docs/reference/config-api/kubelet-config.v1alpha1/ page into Chinese

**What would you like to be added**
Add the page /docs/reference/config-api/kubelet-config.v1alpha1 zh localization

**Why is this needed**
Add the page /docs/reference/config-api/kubelet-config.v1alpha1 zh localization
**Comments**
NA

/language zh
/assign

**Comment by tengqm** [comment]
Done.
/close
