### ISSUE TITLE
[zh] Localization bugs / work required for Deployment concept

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [kubernetes/website#32316]
There are some bugs:
https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=apps/nginx%2Ddeployment-,nginx%3Dnginx%3A1.9.1,-%2D%2Drecord%3Dtrue%0A3
"nginx=nginx:1.9.1" should be changed to "nginx=nginx:1.16.1"

https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=apps/nginx%2Ddeployment-,nginx%3Dnginx%3A1.91,-%2D%2Drecord%3Dtrue
"nginx=nginx:1.91" should be changed to "nginx=nginx:1.161"

https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=image%20updated%20to%201.9.1
"image updated to 1.9.1" should be changed to "image updated to 1.16.1"

The content of this article has many "deployment.v1.apps", it could be changed to "deployment". For example:
https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=%E4%B8%8A%E7%BA%BF%E8%A2%AB%E8%A7%A6%E5%8F%91%EF%BC%9A-,kubectl%20rollout%20history%20deployment.v1.apps/nginx%2Ddeployment,-%E8%BE%93%E5%87%BA%E7%B1%BB%E4%BC%BC%E4%BA%8E
"kubectl rollout history deployment.v1.apps/nginx-deployment" could be changed to "kubectl rollout history deployment/nginx-deployment"

**Comment by RA489** [comment]
@wangxiaoyang-dev seems like docs is already updated to nginx:1.16.1. Do you mind closing this issue?

**Comment by wangxiaoyang-dev** [comment]
@RA489 There should still be a few places left unfinished.

**Comment by RA489** [comment]
@wangxiaoyang-dev Could you please edit the issue which needs to be still updated?

**Comment by wangxiaoyang-dev** [comment]
Bug1: https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=apps/nginx%2Ddeployment-,nginx%3Dnginx%3A1.9.1,-%2D%2Drecord%3Dtrue%0A3
"nginx=nginx:1.9.1" should be changed to "nginx=nginx:1.16.1"

Bug2:
https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=apps/nginx%2Ddeployment-,nginx%3Dnginx%3A1.91,-%2D%2Drecord%3Dtrue
"nginx=nginx:1.91" should be changed to "nginx=nginx:1.161"

Bug3:
https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=image%20updated%20to%201.9.1
"image updated to 1.9.1" should be changed to "image updated to 1.16.1"

Bug4:
The content of this article has many "deployment.v1.apps", it could be changed to "deployment". For example:
https://kubernetes.io/zh/docs/concepts/workloads/controllers/deployment/#:~:text=%E4%B8%8A%E7%BA%BF%E8%A2%AB%E8%A7%A6%E5%8F%91%EF%BC%9A-,kubectl%20rollout%20history%20deployment.v1.apps/nginx%2Ddeployment,-%E8%BE%93%E5%87%BA%E7%B1%BB%E4%BC%BC%E4%BA%8E
"kubectl rollout history deployment.v1.apps/nginx-deployment" could be changed to "kubectl rollout history deployment/nginx-deployment"

@RA489

**Comment by RA489** [comment]
@wangxiaoyang-dev Thanks for clarifying.

/assign

**Comment by sftim** [comment]
/retitle [zh] Localization bugs / work required for Deployment concept
