### ISSUE TITLE
Misleading explanation of when init container changes trigger Pod restart

### ISSUE THREAD

**Issue by ultraasi-atanas** [kubernetes/website#32325]
Spotted that both 

- Altering an init container image field is **equivalent** to restarting the Pod. (under Detailed behaviour)
- The Pod will **not** be restarted when the init container image is changed (v1.20 or later, under Pod restart reasons)

Are mentioned on the same page, despite the k version being of importance, could this not be said in a different way? 
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by sftim** [comment]
/retitle Misleading explanation of when init container changes trigger Pod restart
/language en
/kind bug
