### ISSUE TITLE
Configuration Best Practices 404 link

### ISSUE THREAD

**Issue by Deseao** [kubernetes/website#32322]
The v1.20 documentation has a broken link on the [Configuration Best Practices](https://v1-20.docs.kubernetes.io/docs/concepts/configuration/overview/) page when attempting to follow the link to the [guestbook-all-in-one.yaml](https://github.com/kubernetes/examples/tree/v1.20.13/guestbook/all-in-one/guestbook-all-in-one.yaml) file. I see that it does exist on [master](https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml), but may not be correct compared to the specification for version 1.20.

**Comment by miteshskj** [comment]
@sftim @tengqm  - This is fixed in newer versions (1.22 on wards). What is the process/policy of pushing changes to older supported versions?

**Comment by tengqm** [comment]
@miteshskj The convention is to avoid amending docs for old versions of k8s, while allowing for important bug fixes.

**Comment by sftim** [comment]
Really the priority is that we prioritise docs for the current and the upcoming release. If we had a surfeit of volunteer capacity we could try to apply that to checking and fixing the docs for older releases.

**Comment by Deepakktripathy** [comment]
Hi, can anyone tell me where should the new link point to?

**Comment by tengqm** [comment]
Maybe pointing to the master branch would be okay. https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml

There is not such tag named v1.20.13 or something like that.

**Comment by sftim** [comment]
If we want versioning by release, we can make a copy of that manifest within https://github.com/kubernetes/website/tree/main/content/en/examples (and then onto a release branch rather than _main_).

**Comment by Deepakktripathy** [comment]
Hi, where is the file for this issue situated? I am having trouble finding it

**Comment by miteshskj** [comment]
@Deepakktripathy  - website/content/en/docs/concepts/configuration/overview.md in release-1.20 branch.
