### ISSUE TITLE
Improvement for k8s.io/zh/docs/concepts/overview/working-with-objects/common-labels/

### ISSUE THREAD

**Issue by tramplpf** [kubernetes/website#32327]
可以给出一个比较完整的demo。通过这里的demo，对共享标签的作用，自己依然没有理解

**Comment by sftim** [comment]
Does this actually need fixing first in the upstream English docs? Localizations should be a faithful, relevant conversion of the original text.

**Comment by tengqm** [comment]
/close
This issue won't be solved in the zh localization. Feel free to file one about label examples.
