### ISSUE TITLE
Translate Reference/kubernetes-api/common-definitions/label-selector.md

### ISSUE THREAD

**Issue by syxunion** [kubernetes/website#32341]
Hi, I'm interested to translate the "Reference/kubernetes-api/common-definitions/label-selector.md" page.

This is a Feature Request:

translate en/docs/Reference/kubernetes-api/common-definitions/label-selector.md into chinese

What would you like to be added:

zh/docs/reference/reference/kubernetes-api/common-definitions/label-selector.md

/language zh
/kind feature

**Comment by jihoon-seo** [comment]
@syxunion This issue is dup with #32187 .
PR: #32202
/triage duplicate
