### ISSUE TITLE
Services, Load Balancing, and Networking

### ISSUE THREAD

**Issue by sgpinkus** [kubernetes/website#32360]
This confusing series of [statements is made](https://kubernetes.io/docs/concepts/services-networking/):

 A. pods on a [node](https://kubernetes.io/docs/concepts/architecture/nodes/) can communicate with all pods on all nodes without NAT
 B. agents on a node (e.g. system daemons, kubelet) can communicate with all pods on that node
 C. For those platforms that support Pods running in the host network (e.g. Linux): pods in the host network of a node can communicate with all pods on all nodes without NAT.

Statement C is implied by A. So why is it stated at all?? C is effectively saying there is no exception to statement A when  Pods are running in the host network. Seems like a very strange statement to make out of the blue. Maybe statement A is actually wrong? Or maybe statement C needs to be clarified. Not sure, hence issue rather than PR.

**Comment by tengqm** [comment]
HostNetwork is a mode for some special use cases. It has its own security and management problems, so it's NOT the recommended mode for most scenarios.
/kind support

**Comment by sgpinkus** [comment]
Closing. Opened PR instead - see linked.
