### ISSUE TITLE
Changing the Container Runtime on a Node from Docker Engine to containerd

### ISSUE THREAD

**Issue by ywei2017** [kubernetes/website#32381]
This instruction missed noting 
1. that the control plane should also be migrated.
2. `crictl config` be run to set the cri endpoint by removing dockershim

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/

**Comment by RA489** [comment]
The procedure to upgrade the container runtime on control plane is exactly the same than on the node.
