### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by vdellaglio** [kubernetes/website#32392]
Hi,

I think there's an error in the docs about `Use the option --from-env-file to create a ConfigMap from an env-file`

Here you can find:
`Caution: When passing --from-env-file multiple times to create a ConfigMap from multiple data sources, only the last env-file is used.`

but in fact it takes into consideration all env files you put in the command. Here is the test:
```
root@master:~# cat configure-pod-container/configmap/env-file.1
env-file-1=true
name1=this-is-env-file-1
```
```
root@master:~# cat configure-pod-container/configmap/env-file.2
env-file-2=true
name2=this-is-env-file-2
```

```
root@master:~# kubectl create configmap my-config-map --from-env-file=configure-pod-container/configmap/env-file.1 --from-env-file=configure-pod-container/configmap/env-file.2
configmap/my-config-map created
```
Checking "my-config-map":

```
root@master:~# kubectl get cm my-config-map -o yaml
apiVersion: v1
data:
  env-file-1: "true"
  env-file-2: "true"
  name1: this-is-env-file-1
  name2: this-is-env-file-2
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-21T09:54:47Z"
  name: my-config-map
  namespace: default
  resourceVersion: "3777559"
  uid: 8a107cee-f87b-415a-b01f-79aec820b489
```

**Comment by vdellaglio** [comment]
Adding the environment version:

```
root@master:~# kubectl get nodes
NAME      STATUS   ROLES                  AGE    VERSION
master    Ready    control-plane,master   409d   v1.23.4
worker1   Ready    <none>                 409d   v1.20.2
worker2   Ready    <none>                 409d   v1.20.2

```

**Comment by Kartik494** [comment]
Hi @vdellaglio if i am not wrong here , you are getting both env file in config map when running command `kubectl get configmap config-multi-env-files -o yaml` but it should be showing only latest file env?

**Comment by sftim** [comment]
Please confirm what version of Kubernetes and of `kubectl` you replicated that with @vdellaglio 

It's possible that the behavior with Kubernetes v1.23 is what's documented; if not, we should fix the docs.

**Comment by vdellaglio** [comment]
> Hi @vdellaglio if i am not wrong here , you are getting both env file in config map when running command `kubectl get configmap config-multi-env-files -o yaml` but it should be showing only latest file env?

Yes, I understand that your documentation is saying that I can pass several env files in the command, but only the last one will be taken into consideration:

"Caution: When passing --from-env-file multiple times to create a ConfigMap from multiple data sources, only the last env-file is used."

**Comment by vdellaglio** [comment]
> Please confirm what version of Kubernetes and of `kubectl` you replicated that with @vdellaglio
> 
> It's possible that the behavior with Kubernetes v1.23 is what's documented; if not, we should fix the docs.

`root@master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1`

**Comment by vdellaglio** [comment]
So I decided to upgrade all the environment, previously it had a version skew which was not supported. Now the environment is 100% updated:

```root@master:~# kubectl get nodes
NAME      STATUS   ROLES                  AGE    VERSION
master    Ready    control-plane,master   414d   v1.23.5
worker1   Ready    <none>                 414d   v1.23.5
worker2   Ready    <none>                 414d   v1.23.5

root@master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

root@master:~# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:57:37Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

All configmaps deleted:

```
root@master:~# kubectl get cm
NAME               DATA   AGE
kube-root-ca.crt   1      414d
```

Env files:

```
root@master:~# cat configure-pod-container/configmap/env-file.1
env-file-1=true1
name1=this-is-env-file1

root@master:~# cat configure-pod-container/configmap/env-file.2
env-file-2=true2
name2=this-is-env-file2
```

ConfigMap created:
```
root@master:~# kubectl create configmap new-cm --from-env-file=configure-pod-container/configmap/env-file.1 --from-env-file=configure-pod-container/configmap/env-file.2
configmap/new-cm created
```

Checking results:

```
root@master:~# kubectl get cm new-cm -o yaml
apiVersion: v1
data:
  env-file-1: true1
  env-file-2: true2
  name1: this-is-env-file1
  name2: this-is-env-file2
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-26T14:07:34Z"
  name: new-cm
  namespace: default
  resourceVersion: "4397303"
  uid: 61c9d425-99d9-4a79-8fcd-255c8ef74f60
```

```
root@master:~# kubectl describe cm new-cm
Name:         new-cm
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
env-file-1:
----
true1
env-file-2:
----
true2
name1:
----
this-is-env-file1
name2:
----
this-is-env-file2

BinaryData
====

Events:  <none>
```

Same results as before: docs are not reflecting the current behaviour.

**Comment by miteshskj** [comment]
@sftim  - v1.23 added support for multiple env files. Should we remove the caution note (about kubectl accepting only single env file as input) or we add additional info, informing users that this behavior is changed starting v1.23?

**Comment by Kartik494** [comment]
@miteshskj thanks for the inputs . @sftim  i am interested in raising a PR for this if no-one is currently working on this issue.Please let me know on this.

**Comment by miteshskj** [comment]
@Kartik494  - I am working on this. Sorry missed to assign myself.
/assign

**Comment by Kartik494** [comment]
@miteshskj No problem, thanks for clarification, please let me know oi you need any help on this.
