### ISSUE TITLE
Mermaid diagram on Authenticating page is unreadable

### ISSUE THREAD

**Issue by prasadkatti** [kubernetes/website#32420]
The mermaid diagram in the https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens section is unreadable. The text is overlapping. That might be dependent on your screen width, i guess. But it doesn't render properly on a regular 15" MBP.

Here is a screenshot - 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/7345249/159534477-9a20e0a0-4311-428f-a1cf-1e2605d502e0.png">

@sftim rightly pointed out that I have a user css applied (Dark Reader chrome plugin). I tried to get a screenshot with the plugin turned off but I haven't been able to reproduce.

**Comment by anubha-v-ardhan** [comment]
Renders fine for me on both Chrome 99.0.4844.82 and Firefox 98.0.1

**Comment by sftim** [comment]
I can replicate this.
Let's convert that diagram to SVG and serve that.

/triage accepted
/priority backlog

BTW @prasadkatti it looks like you have a user stylesheet applied. That's OK, but when taking screenshots I recommend that you revert to the site default stylesheet.

**Comment by reylejano** [comment]
The diagram renders fine for me
![image](https://user-images.githubusercontent.com/52760880/159583241-17ecb0ac-60c6-45b6-b9c0-08b1bd671054.png)
It still looks fine when the browser window is 1/4 of my screen
![image](https://user-images.githubusercontent.com/52760880/159583391-975359e3-6960-49e3-80c8-14d5cc05f8c0.png)

**Comment by jihoon-seo** [comment]
Maybe relevant with:
- #31960

**Comment by sftim** [comment]
The fix I recommend: https://github.com/kubernetes/website/issues/32420#issuecomment-1075476014

**Comment by sftim** [comment]
For me that diagram is rendering fine now.

/close

@prasadkatti if you're still seeing symptoms, it's OK to reopen this issue.
