### ISSUE TITLE
Translate label selector

### ISSUE THREAD

**Issue by xuezhixin** [kubernetes/website#32428]
This is a Feature Request:
translate content/en/docs/reference/kubernetes-api/common-definitions/label-selector.md

What would you like to be added:
content/zh/docs/reference/kubernetes-api/common-definitions/label-selector.md

/language zh
/kind feature

**Comment by jihoon-seo** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/ already has a Chinese version.
https://kubernetes.io/zh/docs/reference/kubernetes-api/common-definitions/label-selector/
Issue: #32187
PR: #32202
/close
