### ISSUE TITLE
Translate ObjectReference

### ISSUE THREAD

**Issue by xuezhixin** [kubernetes/website#32433]
Hi,I am interested to translate the "Kubernetes Documentation/Reference/Kubernetes API/Common Definitions/ObjectReference"
This is a Feature Request:
translate en/docs/reference/kubernetes-api/common-definitions/object-reference.md

What would you like to be added:
content/zh/docs/reference/kubernetes-api/common-definitions/object-reference.md

/language zh
/kind feature

**Comment by ydFu** [comment]
LGTM,This issue has been resolved in PR #32433 , thank you for your contribution.
/close
/cc @tengqm
