### ISSUE TITLE
Unclarity regarding restart on failed readiness checks

### ISSUE THREAD

**Issue by joerghoh** [kubernetes/website#32446]
**This is a Bug Report**

**Problem:**
The documentation on readiness probes is unclear. It describes how to configure readiness for a single container, but when it comes to the restart behavior, it's not exactly clear, if just the container or the complete pod is restarted:
* the documentation says: ```[...] and the containers have been killed and recreated.```
* but then ```kubectl get pod ...``` command is used to show that the restart counter of the *pod* has been increased. 

It is not clear in the documentation, if this restart counter relates to all containers in the pod (meaning that all containers in that pod have been restarted due to failed readiness checks of a single container in that pod) or just a single container in the pod. In the example it does not matter because the pod consists of just a single container.

**Proposed Solution:**
Please clarify if a single failing container causes a restart of the whole pod or just of the affected container, and how it relates to the *RESTARTS* field of the output of the ```kubectl get pod``` command.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by sftim** [comment]
/remove-kind bug
This is a request to improve docs; the existing docs are unclear, not wrong.

/language en
/sig node
/triage accepted

**Comment by akankshakumari393** [comment]
I would like to work on it.
