### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by tridelt** [kubernetes/website#32469]
I believe not using CredStore is an [excpetion](https://stackoverflow.com/questions/55188020/how-to-force-docker-login-command-to-ignore-existing-credentials-helper#:~:text=To%20avoid%20using%20a%20credsStore,auth%20token%20into%20the%20file.) to the rule. 

I suggest focusing in the docs on how to create a Secret from `~/.docker/config.json` that uses a **CredStore** as I don't think it is straight forward at all. In the current state, the docs didn't help me, unfortunately.

**Comment by sftim** [comment]
This sounds like a feature request about how to migrate from using a CredStore with Docker locally, to storing a Secret in Kubernetes that stores the equivalent credentials.

I'm not sure we'd prioritize adding this (and then maintaining that page). If someone wants to write that up as a blog article, I'd be minded to accept it though.
/language en
/kind feature
