### ISSUE TITLE
Incorrect or out of date script localization in init 容器 concept

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [kubernetes/website#32466]
There is a bug:
https://kubernetes.io/zh/docs/concepts/workloads/pods/init-containers/#:~:text=if%20dig%20myservice%3B-,then%20exit%200%3B%20fi%3B,-exit%201
"then exit 0; fi; exit 1" should be changed to "then exit 0; fi; done; exit 1"

**Comment by sftim** [comment]
/triage accepted
/retitle Incorrect or out of date script localization in init 容器 concept
/language zh

**Comment by shaggyyy2002** [comment]
@wangxiaoyang-dev on what line can you explain?
