### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/

### ISSUE THREAD

**Issue by sriharikadali** [kubernetes/website#32470]
All the hyper links are not secure NET::ERR_CERT_INVALID certs are not valid

**Comment by sftim** [comment]
The hyperlinks in https://k8s.io/docs/tasks/tools/ work OK with no TLS error.

@sriharikadali check that these symptoms are not down to your local network configuration.

/triage not-reproducible
/language en

**Comment by reylejano** [comment]
I tired every hyperlink in https://k8s.io/docs/tasks/tools/ without an TLS issues

/close
