### ISSUE TITLE
[fr] Incorrect spaces in paragraph to deploy-intro tutorial page

### ISSUE THREAD

**Issue by ggallon** [kubernetes/website#32493]
**This is a Bug Report**

**Problem:**
Incorrect spaces in paragraph to deploy-intro tutorial page

**Proposed Solution:**
Remove break lines to: 
https://github.com/kubernetes/website/blob/5328fdf7979f81f0338dad4d16a564390d6e1542/content/fr/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html#L30-L35

**Page to Update:**
https://github.com/kubernetes/website/blob/main/content/fr/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

Screenshot
![deploy-intro](https://user-images.githubusercontent.com/3640689/160097066-d4c0ca22-f1f2-4a7d-a159-10db9f7dc254.png)
t

**Comment by jihoon-seo** [comment]
- en page: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
- fr page: https://kubernetes.io/fr/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

/triage accepted
