### ISSUE TITLE
Hello Minikube - Cleanup steps are blocked by the popup terminal

### ISSUE THREAD

**Issue by bitspittle** [kubernetes/website#32511]
The cleanup steps are blocked for me by the popup terminal. This seems to be happening because I'm using a monitor with a vertical layout.

Expected: One of...
* Be able to minimize the terminal
* Be able to pop-out the terminal
* Be able to move the terminal to the top of the window
* Open the terminal in a frame below the current window, instead of on top of it, so that there are two vertical scrollbars perhaps

Here's what I'm seeing:

![hello-minikube-clean-up](https://user-images.githubusercontent.com/43705986/160160388-4074a636-b8e0-4104-8f56-e0ceb98c2d41.png)

**Comment by sftim** [comment]
I'm going to freeze this one
/lifecycle frozen

It'll need fixing, unless we change quite a lot of how the site works.

/priority backlog

**Comment by divya-mohan0209** [comment]
Since we no longer use Katacoda, this issue is not reproducible. Tagging and closing it appropriately.
