### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by cloudsapiens** [kubernetes/website#32523]
Incorrect apiVersion used in example (application/job/cronjob.yaml):

Currently used: apiVersion: batch/v1
Correct one: **apiVersion: batch/v1beta1**

Thanks for fixing it in the documentation (https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/).

**Comment by Tellz777** [comment]
**batch/v1** is used since 1.21 and **batch/v1beta1** will be deprecated since 1.25 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125 So, I guess its correct to reference on **batch/v1** in all docs from the 1.21 version.

**Comment by sftim** [comment]
/triage invalid
@cloudsapiens you *must* read the docs for the version of Kubernetes that you are running, otherwise you might assume the latest version's docs are incorrect when they are actually accurate.

**Comment by sftim** [comment]
/triage unresolved

/close
Nothing to fix here.
