### ISSUE TITLE
Pod 拓扑分布约束，相互作用一节排版有误

### ISSUE THREAD

**Issue by expoli** [kubernetes/website#32552]
https://kubernetes.io/zh/docs/concepts/workloads/pods/pod-topology-spread-constraints/#interaction-with-node-affinity-and-node-selectors

此处排版有误。

![image](https://user-images.githubusercontent.com/31023767/160265345-26e953a4-fe65-47ba-bb53-b98e2f64056a.png)

![image](https://user-images.githubusercontent.com/31023767/160265349-6ba9118b-76d1-4678-885c-4fe3d30c6382.png)

**Comment by tengqm** [comment]
/triage accepted
/kind bug

The page is out of sync.
