### ISSUE TITLE
Managing Kubernetes Objects Using Imperative Commands rename in Docs

### ISSUE THREAD

**Issue by Smidra** [kubernetes/website#32573]
**I propose to rename [this](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/) section of the k8s documentation to**:

`Imperative Management of Kubernetes Objects Using Commands`

It improves the readability of the documentation neatly making the first word of the name useful for orientation. Do I need to learn about Declarative/Imperative managmement?

- Why are we solving this issue?
  - Make k8s documentation more readable
- To address this issue, are there any code changes? If there are code changes, what needs to be done in the code and what places can the assignee treat as reference points?
  - No code changes to the k8s project needed.
- Does this issue have zero to low barrier of entry?
  - Yes
- How can the assignee reach out to you for help?
  - Comment on this issue. 

The improved readability in the k8s documentation is best seen in the [section above](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/).

# **OLD version:**
![image](https://user-images.githubusercontent.com/25660869/160400643-ddde9808-576f-4597-aec4-3d0bcc3e1376.png)

# **Proposed new version:**
![image](https://user-images.githubusercontent.com/25660869/160400885-4dfcc90f-c1d3-4b12-92ff-7cb28ac1a57a.png)

**Comment by sftim** [comment]
To me, “Imperative Management of Kubernetes Objects Using Commands” is less of a task-type title than the current title. However, the other pages are wrong too!

We can make the small change and then consider making the bigger change.

/kind cleanup
/triage accepted
/help
/language en

**Comment by sftim** [comment]
The page to update is https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/

**Comment by eminalemdar** [comment]
> The page to update is https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/

Hello @sftim, is the title of this page should be changed as proposed?

**Comment by sftim** [comment]
I didn't understand https://github.com/kubernetes/website/issues/32573#issuecomment-1128658282 @eminalemdar 

The page that nees fixing is https://kubernetes.io/docs/tasks/manage-kubernetes-objects/imperative-command/
The fix that @Smidra recommends is to change the title of that page to “Imperative Management of Kubernetes Objects Using Commands”

I support making that change.

**Comment by eminalemdar** [comment]
Perfect! I can do that @sftim

**Comment by vaibhav2107** [comment]
Can be closed, fixes in #33829
