### ISSUE TITLE
Trouble following HorizontalPodAutoscaler walkthrough

### ISSUE THREAD

**Issue by oluyinkos** [kubernetes/website#32582]
When I run the load generator pod, it is unable to connect to the php-apache service. 

The error received is: 

```wget: can't connect to remote host (10.109.151.227): Connection timed out```

I'm unable to connect to the php-apache service from the browser either. The workaround I have used for that is to run the following command: 

```kubectl port-forward service/php-apache 31000:80```

Then I can use locahost:31000 to access the service. But localhost doesn't work for the load generator. 

Does anyone know why the minikube service (php-apache) isn't accessible at http://php-apache and how we can make that url work? 

Note: I use docker driver. 

Thanks for any assistance given.

**Comment by sftim** [comment]
/retitle Trouble following HorizontalPodAutoscaler walkthrough
/language en

**Comment by Shubham82** [comment]
Hi @oluyinkos 
I have tried the [HPA walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#run-and-expose-php-apache-server) it is working fine for me.
I have used docker as VM Driver.

```
$ kubectl run -i --tty load-generator --rm --image=busybox:1.28 --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://php-apache; done"
If you don't see a command prompt, try pressing enter.
OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!
```
```
minikube version: v1.22.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by oluyinkos** [comment]
> Hi @oluyinkos I have tried the [HPA walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#run-and-expose-php-apache-server) it is working fine for me. I have used docker as VM Driver.
> 
> ```
> $ kubectl run -i --tty load-generator --rm --image=busybox:1.28 --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://php-apache; done"
> If you don't see a command prompt, try pressing enter.
> OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!OK!
> ```
> 
> ```
> minikube version: v1.22.0
> 
> kubectl version
> Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
> ```

Thanks for the feedback @Shubham82. Note that I tried it on a Mac. I was able to get it to work eventually by changing the driver to hyperkit. Did you test it on a Mac as well?

**Comment by Shubham82** [comment]
No @oluyinkos I didn't try it on MAC. I tried it on Ubuntu 18.04.
See [this](https://minikube.sigs.k8s.io/docs/drivers/#macos) drivers page, may be this will help you.
