### ISSUE TITLE
Wrong links in sidebar menu of k/w repo wiki

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#32626]
**This is a Bug Report**

**Problem:**
In the sidebar menu of k/w repo wiki, there exist links:
- [I18n team meeting notes](https://github.com/kubernetes/website/wiki/Guidelines-for-Reviewing-and-Merging-PRs/wiki/Translation-team-meeting-notes)
- [Q&A with OpenStack i18n](https://github.com/kubernetes/website/wiki/Guidelines-for-Reviewing-and-Merging-PRs/wiki/OpenStack-Q&A:-i18n)

But these links go to wrong page.

**Proposed Solution:**
- Update `I18n team meeting notes` link to go to https://github.com/kubernetes/website/wiki/Translation-team-meeting-notes
- Update `Q&A with OpenStack i18n` link to go to https://github.com/kubernetes/website/wiki/OpenStack-Q&A:-i18n

(P.S. the sidebar menu and each page seems not maintained for some years.)

**Page to Update:**
https://github.com/kubernetes/website/wiki

**Comment by championshuttler** [comment]
/unassign 
it seems only privileged contributors can make the changes
