### ISSUE TITLE
[ja] Update /ja/docs/concepts/scheduling-eviction/kube-scheduler.md to fix the weight and some links

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes/website#32677]
**This is a Feature Request**

**What would you like to be added**

Update ja/docs/concepts/scheduling-eviction/kube-scheduler.md to fix the weight and some links.

**Why is this needed**
- The weight value has changed on the current English page.
- One of the links on this page does not work.
- Update to other links.

**Comments**

/language ja
/assign

**Comment by nasa9084** [comment]
/retitle [ja] Update /ja/docs/concepts/scheduling-eviction/kube-scheduler.md to fix the weight and some links
/triage accepted
