### ISSUE TITLE
Інтерактивний урок - Розгортання застосунку page incorrect

### ISSUE THREAD

**Issue by Snorri1986** [kubernetes/website#32700]
Module 2.Depoly an App.
There is an error in the example of Step 3.
URL: https://kubernetes.io/uk/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
IF you write two commands as described in the example and push ENTER button - you will got an error:
`echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n"; 
kubectl proxy`
`echo -e "\n\n\n\e[92mStarting Proxy. After starting it will not output a response. Please click the first Terminal Tab\n";` 
and
`kubectl proxy`
must be separated by ENTER.
I have found this mistake in example on next steps in the tutorial.
Fix the text in example.
Thank you.

**Comment by sftim** [comment]
Hi @Snorri1986 

What is the URL of the page that does not seem right?

/triage needs-information

**Comment by Snorri1986** [comment]
Good afternoon,@sftim.
First of all I have caught this mistake by link https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
After, I have seen it futher.

**Comment by sftim** [comment]
/retitle Error in page Interactive Tutorial - Deploying an App

@Snorri1986 Your original title suggests you were looking at the Ukrainian localization. Which is right?
@Snorri1986 Ви читали англійську чи українську веб-сторінку?

**Comment by Snorri1986** [comment]
Ukrainian.I will send Ukrainian link on next Monday.

**Comment by sftim** [comment]
/retitle Інтерактивний урок - Розгортання застосунку page incorrect
/language ua

More information about the issue is welcome

**Comment by Snorri1986** [comment]
@sftim do you need some additional information from me ?

**Comment by Snorri1986** [comment]
@sftim updated
