### ISSUE TITLE
Issue with /docs/getting-started-guides/openstack-heat/

### ISSUE THREAD

**Issue by sudharsanmit** [kubernetes/website#3271]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The kubernetes documentation in the code says that kubectl.sh will be deprecated soon and advises only to use kubectl.

Source - https://github.com/kubernetes/kubernetes/blob/master/cluster/kubectl.sh

```
# Stop the bleeding, turn off the warning until we fix token gen.
# echo "-=-=-=-=-=-=-=-=-=-="
# echo "NOTE:"
# echo "kubectl.sh is deprecated and will be removed soon."
# echo "please replace all usage with calls to the kubectl"
# echo "binary and ensure that it is in your PATH." 
# echo ""
# echo "Please see 'kubectl help config' for more details"
# echo "about configuring kubectl for your cluster."
# echo "-=-=-=-=-=-=-=-=-=-="
```

But the documentation (https://kubernetes.io/docs/getting-started-guides/openstack-heat/) - k8 for Openstack heat still references kubectl.sh

Which one is right?

**Proposed Solution:**
Please update the document to reference the correct procedure.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/openstack-heat/#inspect-your-cluster

(Multiple references in the same page)

**Comment by ahmetb** [comment]
@idvoretskyi can you please take a look at this?

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-openstack-bugs @zreigz

**Comment by tengqm** [comment]
openstack-heat support is deprecated.
