### ISSUE TITLE
Document OCI integration with Service API

### ISSUE THREAD

**Issue by hyder** [kubernetes/website#32742]
Hi,

We would like to add Oracle Cloud Infrastructure (OCI) documentation to the [services-networking page](https://kubernetes.io/docs/concepts/services-networking/service/), specifically additional annotations as well as Network Load Balancer.

How would you recommend we structure our content on this page? Should we break it down by cloud vendor or by service/feature?

Please advise.

**Comment by hyder** [comment]
Thanks @sftim. I see you intend to drop the vendor details. Will there be a place here where we can add links to provider docs?

**Comment by Djelibeybi** [comment]
@sftim would you propose that cloud vendor specific documentation links go into the "What's next" section or somewhere else? We'll watch your refactor PR and then submit a link to our own docs once that's merged.

**Comment by sftim** [comment]
I'm tempted to make a reference page that lists cloud provider integrations with the Service API and that hyperlinks to the docs for each provider where those exist.

**Comment by sftim** [comment]
/retitle Document OCI integration with Service API

**Comment by sftim** [comment]
@hyder you might also want to update https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/ for similar reasons.
