### ISSUE TITLE
Hello Minikube: Default to install minikube on own machine

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#32753]
Page: https://kubernetes.io/docs/tutorials/hello-minikube/

At the moment the default is to use the minikube in Katacoda.

There is a note that you can run the command in your minikube, too. But the current default seems
to be Katacoda.

I am unsure if this is, what most people prefer.

I have the vague feeling that people prefer to install minikube locally and run commands there.

Someone who has access to the web-page analytics could have a look if what people actually do.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

Do people prefer to try Kubernetes in an online hosted sandbox, or to install things locally?
