### ISSUE TITLE
Offer non-interactive equivalents for interactive tutorials

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#32754]
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

It takes ages to start the interactive session. 

I think it would be better to have pure text and show the commands which you need to enter in
your local minikube.

The "Hello Minikube" page is better in this regards, since you see the commands and execute them in your local
minikube. See related issue #32753.

Story from the past: IIRC I had a look at the kubernetes docs three years ago. The Katacoda terminal was way to slow, so I stopped. Then came daily work, and I did not learn Kubernetes. Just some months ago I started again, and I am sorry that I did not start to learn Kubernetes earlier.

Related thread in #sig-docs https://kubernetes.slack.com/archives/C1J0BPD2M/p1648739540122659

And it is not stable. I was some minutes away from keyboard, now I get:

> Sorry, invalid request was made

![image](https://user-images.githubusercontent.com/414336/161596425-dc150663-ca9e-4d6b-b3c5-aa32189c9540.png)

**Comment by sftim** [comment]
/retitle Interactive tutorial sessions slow to start
/team katacoda

**Comment by sftim** [comment]
> I think it would be better to have pure text and show the commands which you need to enter in
your local minikube.

We could not then call that an “interactive tutorial”. I think maybe @guettli you would like to request that we add a non-interactive version of each interactive tutorial?

**Comment by guettli** [comment]
@sftim yes, this makes sense. So that the user can decide if he wants to use his own minikube or a minikube in the browser.

**Comment by sftim** [comment]
/kind feature
/retitle Offer non-interactive equivalents for interactive tutorials
/priority awaiting-more-evidence

I'd like to see some +1 reactions on this issue before we accept it - that'd create a significant extra work backlog for our 13 or so localization teams.

**Comment by guettli** [comment]
sftim is right, this creates a lot of work. There are already several free ways to learn Kubernetes.
