### ISSUE TITLE
Layout is broken in /ja/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by oke-py** [kubernetes/website#32756]
**This is a Bug Report**

**Problem:**
There is a layout corruption in https://kubernetes.io/ja/docs/tasks/tools/install-kubectl/ .
The "Zsh" tab is not working.

<img width="1064" alt="ss_ 2022-04-05 11 47 45" src="https://user-images.githubusercontent.com/4710215/161669468-c13c62ef-a6fc-423d-be66-a02032b3e4bd.png">

The right column is displayed in the lower left probably due to the same reason.

**Proposed Solution:**
There may be a discrepancy between the open tag and the close tag.

**Page to Update:**
https://kubernetes.io/ja/docs/tasks/tools/install-kubectl/

/language ja

**Comment by t-inu** [comment]
There were no start/end tag mismatches.
The following part in the "macOSでのBash" tab seems to affect the layout.

```
   {{< note >}}
   Homebrewでインストールしたbash-completion v2は`BASH_COMPLETION_COMPAT_DIR`ディレクトリ内のすべてのファイルをsourceするため、後者の2つの方法が機能します。
   {{< /note >}}
```

After removing the indent or removing the `note` tag, this page was displayed normally.

And I found a difference between v1.21 and v1.22 pages.
OK: https://v1-21.docs.kubernetes.io/ja/docs/tasks/tools/install-kubectl/
NG: https://v1-22.docs.kubernetes.io/ja/docs/tasks/tools/install-kubectl/

But the layout was broken when I rebuilt using the v1.21 source.
So, the specifications of the site generator may have changed.

**Comment by s-kawamura-w664** [comment]
The Hugo shortcode for note is here: https://github.com/kubernetes/website/blob/main/layouts/shortcodes/note.html

This file updated by #30068.

This problem will occur after fixed #30068.
But, I think that #30068 is no problem.
The issue existed before #30068., but users could not look it.

I found the fix method, but I don't know that it is correct.

File : <https://github.com/kubernetes/website/blob/main/layouts/shortcodes/note.html>

- before:
  ```
  <div class="alert alert-info note callout" role="alert">
    <strong>{{ T "note" }}</strong> {{ trim .Inner " \n" | markdownify }}
  </div>
  ```
- after:
  ```
  <div class="alert alert-info note callout" role="alert">
    <strong>{{ T "note" }}</strong> {{ trim .Inner " \n" | markdownify }}</div>
  ```

**Comment by s-kawamura-w664** [comment]
I know that this issue will occur by using `tabs` and `list` and `note`.
There are not problems by using only `list` and `note`.

**Comment by s-kawamura-w664** [comment]
Report test details.

I confirmed the following code for test.

```
{{< tabs name="test-tab" >}}

{{% tab name="Page-1" %}}

This is page-1.

* List-1

* List-2

  {{< note >}}
  This is note on page-1.
  {{< /note >}}

{{% /tab %}}

{{% tab name="Page-2" %}}

This is page-2.

{{% /tab %}}

{{< /tabs >}}
```

The html is below. 
This was built by Hugo, then I formed it to make it easier to read.

```
<ul class="nav nav-tabs" id="test-tab" role="tablist">
  <li class="nav-item"><a data-toggle="tab" class="nav-link active" href="#test-tab-0" role="tab" aria-controls="test-tab-0" aria-selected="true">Page-1</a></li>
  <li class="nav-item"><a data-toggle="tab" class="nav-link" href="#test-tab-1" role="tab" aria-controls="test-tab-1">Page-2</a></li>
</ul>

<div class="tab-content" id="test-tab">
  <div id="test-tab-0" class="tab-pane show active" role="tabpanel" aria-labelledby="test-tab-0">
    <p>
    <p>This is page-1.</p>
    <ul>
      <li>
        <p>List-1</p>
      </li>
      <li>
        <p>List-2</p>
        <div class="alert alert-info note callout" role="alert">
        <strong>Note:</strong> This is note on page-1.             <-- There is not </div> here.
      </li>
    </ul>
        </div>                                        <-- This will be a </div> to close the <note>.
  </div>
  <div id="test-tab-1" class="tab-pane" role="tabpanel" aria-labelledby="test-tab-1">
    <p>
    <p>This is page-2.</p>
  </div>
</div>
```

The `</div>` to close the `<note>` is outside the list, which is causing problems.
So, I reported the fix of notes.html.
