### ISSUE TITLE
Issue with /docs/getting-started-guides/aws/

### ISSUE THREAD

**Issue by sudharsanmit** [kubernetes/website#3277]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The link https://github.com/kubernetes/kubernetes/tree/master/cluster/aws/config-default.sh is broken

> By default, the script will provision a new VPC and a 4 node k8s cluster in us-west-2a (Oregon) with EC2 instances running on Debian. You can override the variables defined in **config-default.sh** to change this behavior as follows:

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/aws/#cluster-turnup

**Comment by ahmetb** [comment]
@justinsb it looks like the [bash deployment for AWS is now obsolete](https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/util.sh). Do you have time to help bringing this page up to date?

**Comment by justinsb** [comment]
@ahmetb do you think we should just remove references to kube-up entirely from that page (and keep e.g. the sizing information)?

**Comment by ahmetb** [comment]
@justinsb you're the subject matter expert in the area so I think we’re more open to suggestions from you. What I notice is that the ToC goes like:

- kube-up is **no longer supported** in kubernetes 1.6
  - Prerequisites
  - Cluster turnup
    - Supported procedure: get-kube **(&larr; super confusing whether it’s supported or not)**

The user-reported bug comes from that confusing section that does not work.

I recommend we get rid of the kube-up section completely while preserving valuable information. However it looks like the moment we get rid of kube-up section, there’s nothing left in this guide.

So is this document even valid anymore? Maybe this page should no longer exist or it could just be a brief page that links to various solutions (some already listed) and kubeadm, kops etc. Right now I see links to neither kubeadm nor kops, which doesn't sound right.

**Comment by zacharysarah** [comment]
@justinsb 👋 Any updates here?
