### ISSUE TITLE
git clone and kubectl apply

### ISSUE THREAD

**Issue by andresgarcia0313** [kubernetes/website#32770]
Please post a short session to run a git clone and kubectl apply -k ./ for various software

example https://github.com/docker/awesome-compose

Por favor colocar una sesión corta para ejecutar un git clone y kubectl apply -k ./ para distintos software 

please leave the documentation in Spanish

**Comment by sftim** [comment]
/kind feature

This kind of request might be better made to [SIG Usability](https://github.com/kubernetes/community/tree/master/sig-usability); it doesn't sound like a request to document Kubernetes itself.

/priority awaiting-more-evidence

**Comment by andresgarcia0313** [comment]
something has been known
