### ISSUE TITLE
`config API reference generator` still outputs `godoc.org`, not `pkg.go.dev`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#32790]
**This is a Bug Report**

**Problem:**
According to #31318 and #31319,
> https://godoc.org/ is an old endpoint and it automatically redirects to https://pkg.go.dev/. Before it will be removed at some point, it makes sense to change the URL.

so @tengqm updated the generator and opened a PR #31786 which replaces most of `godoc.org` string with `pkg.go.dev`,
but [some `godoc.org` strings were not replaced](https://github.com/kubernetes/website/pull/31786/files#diff-529642a7ae8ff36aa9b875aba977d33431be275a59526b0f94fccd861d2191e3R116) and remain in these files:
- `content/en/docs/reference/config-api/kubeadm-config.v1beta2.md`
- `content/en/docs/reference/config-api/kubeadm-config.v1beta3.md`
- `content/en/docs/reference/config-api/kubelet-credentialprovider.v1alpha1.md`

**Proposed Solution:**
- Maybe we need to check/update the generator again, and then generate references again.
- Or, if the generator is fine, then we might update those files manually.

**Page to Update:**
- https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/#:~:text=proxy/%20or%20https%3A//-,godoc.org,-/k8s.io/kube
- https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#:~:text=proxy/%20or%20https%3A//-,godoc.org,-/k8s.io/kube
- https://kubernetes.io/docs/reference/config-api/kubelet-credentialprovider.v1alpha1/#:~:text=cacheDuration-,meta/v1.Duration,-cacheDuration%20indicates%20the

**Comment by tengqm** [comment]
/reopen
The kubeadm reference is still on its way to be regenerated.
The kubelet credential providers one is yet to be fixed.

**Comment by mengjiao-liu** [comment]
> The kubelet credential providers one is yet to be fixed.

But I didn't find the link https://godoc.org/ in this file `content/en/docs/reference/config-api/kubelet-credentialprovider.v1alpha1.md`. 

https://kubernetes.io/docs/reference/config-api/kubelet-credentialprovider.v1alpha1/#:~:text=cacheDuration-,meta/v1.Duration,-cacheDuration%20indicates%20the page points to https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Duration

There are the only https://godoc.org/ links that still exist in this directory https://github.com/kubernetes/kubernetes/tree/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/kubelet/pkg/apis :
>// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.

for example https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1alpha/api.pb.go#L666 (Code generated by protoc-gen-gogo. DO NOT EDIT.)

If these links need to be updated, they need to be updated in https://github.com/gogo/protobuf or https://github.com/golang/protobuf repository. This part of the update should be beyond the scope of Kubernetes.
