### ISSUE TITLE
Опечатка в Создание сервиса для открытия доступа к приложению

### ISSUE THREAD

**Issue by 6puCCeH** [kubernetes/website#32796]
https://kubernetes.io/ru/docs/tutorials/kubernetes-basics/expose/expose-intro/

«ниже описано, в каких случаях понадобиться сервис без указания selector в спецификации»

В слове «понадобиться» нужно убрать мягкий знак.

**Comment by sftim** [comment]
/language ru
/retitle Опечатка в Создание сервиса для открытия доступа к приложению

**Comment by shurup** [comment]
@sftim this issue can be closed since it was fixed in #33424.
