### ISSUE TITLE
[ko] Wrong `Note` box scoping in Korean "Volumes" page

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#32808]
**This is a Bug Report**

**Problem:**

In the 'RBD CSI migration' section of English "Volumes" page, the `Note` box ends right before the 'secret' section starts:

---

![image](https://user-images.githubusercontent.com/46767780/162343922-95aa66ce-7ae3-4335-a4c7-6547609cb8e2.png)

---

But the `Note` box in Korean "Volumes" page does not end where it should, spanning improperly.

---

![image](https://user-images.githubusercontent.com/46767780/162343945-ee12bfbd-4d4b-46e3-92ab-748333e220b5.png)

---

**Proposed Solution:**
Put `{{< /note >}}` right before the heading `### secret`.

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/storage/volumes/#rbd-csi-migration

/language ko
/assign

**Comment by jihoon-seo** [comment]
In upstream website: Resolved by #33566 and #34817.

In v1.23 website: Will be resolved by a future PR that merges `dev-1.23-ko.3` into `release-1.23`.

/remove-lifecycle stale

**Comment by seokho-son** [comment]
/close

Since dev-1.23-ko.3 into release-1.23. is complete
