### ISSUE TITLE
English Issue with what-is-kubernetes.md

### ISSUE THREAD

**Issue by paul-hammant** [kubernetes/website#3281]
**This is a...** 

- [ ] Feature Request
- [*] Bug Report

**Problem:**

"Kubernetes is not:" section - first bullet - "Kubernetes does not limit the types of applications supported. It does not ..." 

There are bullets within that bullets. Or there should be. Or the section should be rethought.  The "not/doesn't" connotation doesn't clearly associate with those implied sub-bullets.

It is also perilously close to double-negatives in places.

**Proposed Solution:**

Redo section somehow.

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

**Comment by ahmetb** [comment]
@bgrant0607 do you have any plans to revamp `what-is-kubernetes` page?

**Comment by bgrant0607** [comment]
I am going to revamp this page, hopefully sometime soonish.

**Comment by paul-hammant** [comment]
Yay!

**Comment by bgrant0607** [comment]
I simplified this bullet in #7349, so hopefully addressed.
