### ISSUE TITLE
Issue with /docs/user-guide/kubectl-conventions/

### ISSUE THREAD

**Issue by craigbilner** [kubernetes/website#3282]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
# kubectl apply
It says
> To use kubectl apply to update resources, always create resources initially with kubectl apply or with --save-config. See managing resources with kubectl apply for the reason behind it

but when you go to [Managing Resources](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#kubectl-apply) it's not immediately obvious what is the explanation.

**Proposed Solution:**
Perhaps it should explicitly say `--save-config` should always be used otherwise the two/three way diff can never be performed and there's some form of downside to this...? I'm raising this off the back of the Udacity course which doesn't use it, and I was/am wondering what exactly it is that you lose if you don't/forget to use the flag.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#kubectl-apply

**Comment by ahmetb** [comment]
Apparently this is now updated to say:

> Note: To use apply, always create resource initially with either kubectl apply or kubectl create --save-config.

@craigbilner if this solves the problem, consider closing the issue.

**Comment by craigbilner** [comment]
thanks @ahmetb, not really.

I'm still not clear on the "why" and why one wouldn't use it all the time, just in case you want to use `apply` in the future, and in that case why it's not the default etc. etc.

**Comment by ahmetb** [comment]
@craigbilner I had the same annoyance. Basically we should have only `kubectl apply` everywhere. I don't think there's any point of using `kubectl create` in particular (not sure why someone wouldn't like to save the last-applied-configuration). I have a thread about this here: https://groups.google.com/forum/#!msg/kubernetes-users/eA0KlrynWCQ/lkJTvMx9CAAJ;context-place=forum/kubernetes-users

**Comment by craigbilner** [comment]
cool, ta. I guess if you want to close this request the quickest way would be to remove `See managing resources with kubectl apply for the reason behind it` if there's actually no reason :-)

**Comment by ahmetb** [comment]
to be honest I read https://kubernetes.io/docs/tutorials/object-management-kubectl/object-management/#trade-offs-1 still can't tell why would I use `kubectl create` instead of `kubectl apply`. :/
