### ISSUE TITLE
Improve wording for “What is Kubernetes”

### ISSUE THREAD

**Issue by kenhtanaka** [kubernetes/website#32828]
In the section titled "Why you need Kubernetes and what it can do" the first bullet point reads:

- **Service discovery and load balancing** Kubernetes can expose a container using the DNS name or using their own IP address. If traffic to a container is high, Kubernetes is able to load balance and distribute the network traffic so that the deployment is stable.

I'm not clear on the meaning here with regards to load balancing being a benefit with one container. I'm new to Kubernetes, but I assume that multiple containers make more sense. Would this be an accurate rewrite?

- **Service discovery and load balancing** Kubernetes can expose a container using the DNS name or using their own IP address. If traffic to one container is high, Kubernetes is able to load balance and distribute some of the network traffic to other available containers so that the deployment is stable.

**Comment by sftim** [comment]
/retitle Improve working for “What is Kubernetes”
/language en

The original wording is more appropriate. Balancing, whether it's network traffic, a finance ledger, or weights on beam, is something done _in aggregate_.

Additionally, the thing that Kubernetes directs traffic to is actually a different endpoint - usually a [Pod](https://kubernetes.io/docs/concepts/workloads/pods/). It's OK to be simple but the more detail we add to this overview, it becomes more problematic not to cover the full detail.

I like having a simple summary that doesn't yet include all the detail. We could look for a different wording that implies that the one overloaded container might be part of a broader set of some kind (without mentioning the actual implementation details: ReplicaSet, Deployment, etc).

**Comment by kenhtanaka** [comment]
I see, "Balancing" implies an aggregate action to me too, so with regards to "a container" I wasn't sure if I was making the right assumption that "there must be other containers" to make that work. I think this would be clearer to me to identify a broader set (change in italics):

- **Service discovery and load balancing** Kubernetes can expose a container using the DNS name or using their own IP address. If traffic to _one of the containers_ is high, Kubernetes is able to load balance and distribute the network traffic so that the deployment is stable.

Would that wording meet your goal of keeping a simple summary that is still accurate?

**Comment by sftim** [comment]
/retitle Improve wording for “What is Kubernetes”

How about:
_Service discovery and load balancing Kubernetes can expose a container using the DNS name or using their own IP address. When there are multiple containers backing a service, Kubernetes is able to load balance and distribute the network traffic. Load balancing helps ensure that a workload can stay available even if one container stops working, or during deployments._

**Comment by kenhtanaka** [comment]
Yes, that reads much clearer to me.

**Comment by NitishKumar06** [comment]
Hey @sftim , I've reviewed the PR for this issue. Kindly look at it and feel free to suggest some changes if necessary.

**Comment by sftim** [comment]
> I've reviewed the PR for this issue. Kindly look at it and feel free to suggest some changes if necessary.

English nit: you've _opened_ a PR and are requesting a review.

**Comment by NitishKumar06** [comment]
@sftim My bad! Sorry, I mean I've made changes to the PR as required so now I'm asking  for review if any further changes are required to be made before merging.

**Comment by sftim** [comment]
/remove-help

We shouldn't label updates to the What Is Kubernetes page as good first issues, unless the fixes are genuinely trivial. Updates to that page always require extra review.

**Comment by NitishKumar06** [comment]
I think we can close this issue. WDYT @sftim ?

**Comment by kenhtanaka** [comment]
As @sftim commented on Apr 13, does this change when merged? I'm not familiar with your workflow on when https://kubernetes.io/docs/concepts/overview/ will change.

**Comment by sftim** [comment]
/remove-lifecycle stale

BTW, once someone merges a fix for this issue, we can close the issue. I think there is room to improve the wording in https://kubernetes.io/docs/concepts/overview/

**Comment by NitishKumar06** [comment]
@sftim As far as the last comment by @reylejano (https://github.com/kubernetes/website/pull/34037#issuecomment-1226797408) , Do you think that any change is required?

**Comment by sftim** [comment]
I still think we should make an improvement (see my [previous comment](https://github.com/kubernetes/website/issues/32828#issuecomment-1348594887)). It needs to be a change that reviewers agree is a benefit to the Kubernetes docs.
