### ISSUE TITLE
Reword recommendation to migrate from dockershim

### ISSUE THREAD

**Issue by chrisnegus** [kubernetes/website#32827]
While evaluating [Issue #25879](https://github.com/kubernetes/website/issues/25879), it was suggested that we should make a stronger statement about migrating from dockershim on the [Migrating from dockershim](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/) page. The current wording is:

`It is recommended to migrate from dockershim to alternative container runtimes.`

Perhaps it could be more along the lines of:

`Because dockershim is no longer part of Kubernetes as of release 1.24, to upgrade to 1.24 you need to either migrate to another container runtime or find an alternate means of obtaining Docker Engine support`

**Comment by Babapool** [comment]
Hi, I would like to work on this issue. Thanks.
/assign

**Comment by Babapool** [comment]
I have one question: The PR for this issue should target the `dev-1.24` branch or the `main` branch?

**Comment by chrisnegus** [comment]
> I have one question: The PR for this issue should target the `dev-1.24` branch or the `main` branch?

Good question. I think clarity is a good thing right now. So my personal preference is `main`.
