### ISSUE TITLE
Highlight current Heading in the righ TOC of the page

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#32825]
thank you for the great docs!

Nevertheless I think it would help the user if the current heading in the TOC of the page (right side) would
highlight the current heading.

![image](https://user-images.githubusercontent.com/414336/162515954-2d844d06-d410-45a9-88bb-25b7662476ae.png)

In this case it would be great if "Service account token Secrets" would be highlighted in the right column.

The highlighted heading should get updated, when the user scrolls down the page.

I have seen this on a static page of them tech project some days ago.

What do you think?

**Comment by sftim** [comment]
/kind feature
/area web-development

It's a nice idea but I suspect would be a lower priority than some other improvements that SIG Docs is keen to focus on. PRs to implement this are nevertheless welcome - ideally [upstream](https://docsy.dev/).

**Comment by sftim** [comment]
This might work better as a feature request against [Docsy](https://www.docsy.dev/)

/remove-lifecycle rotten

**Comment by sftim** [comment]
/priority awaiting-more-evidence

@guettli if you're sure you don't want this as an upstream feature, feel free to comment. If this does fit better as a feature for Docsy, please file an issue there, reference this one, and then close this.

We should otherwise let this issue rot out.

**Comment by guettli** [comment]
Thank you Tim, I created an issue at Docsy: https://github.com/google/docsy/issues/1287
