### ISSUE TITLE
Create static Pods: `--pod-manifest-path` has been deprecated

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#32835]
On: https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

> Configure your kubelet on the node to use this directory by running it with --pod-manifest-path=/etc/kubelet.d/ argument.

But I get:

>  Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.

Sorry, I can't provide a PR at this moment.

**Comment by sftim** [comment]
/kind bug
/sig node
/language en
/priority important-longterm

Static pods are on the syllabus for the CKA qualification, so we should especially avoid recommending a deprecated approach.

**Comment by guettli** [comment]
Maybe it makes sense to change to docs from `/etc/kubelet.d` to `/etc/kubernetes/manifests`, too, since that what kubeadm creates.

**Comment by sftim** [comment]
I think this is still worth tracking, but isn't a short term priority.

/reopen
/lifecycle frozen

**Comment by sftim** [comment]
/retitle Create static Pods: `--pod-manifest-path` has been deprecated

**Comment by adityasamant25** [comment]
/assign

I will try to work on a PR for this issue.
