### ISSUE TITLE
Interactive Tutorials depend on tracker domain on adblocker lists

### ISSUE THREAD

**Issue by fake-name** [kubernetes/website#32832]
Effectively the title. The interactive tutorials completely fail to operate if `trackjs.com` is blocked, which it is if the client has any anti-tracking protections running.

This includes EasyList's `easyprivacy`, which is one of the default lists used as part of uBlock origin.

Trying to run the interactive tutorial therefore fails in the following way:

```
Uncaught ReferenceError: trackJs is not defined
    at TerminalViewLayout.init.init (terminal-application.js?v=20211119:1:1261)
    at window.onInit (?v=2&embed=true&ui=inline&host=kubernetes.io&url=https%3A%2F%2Fkubernetes.io%2Fdocs%2Ftutorials%2Fkubernetes-basics%2Fcreate-cluster%2Fcluster-interactive%2F&target=inline-terminal-1&nonce=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWJlZCI6dHJ1ZSwiZG9tYWluIjoiaHR0cHM6Ly9rdWJlcm5ldGVzLmlvLyIsImlwIjoiMjYwMDo4ODAyOjUzMDA6MmU4Ojk1NjA6NjhkMTpjYWNhOmRmYzQiLCJpYXQiOjE2NDk0ODg0MDEsImV4cCI6MTY0OTQ4ODQzMX0.HDlp1X8-nTZ9s3e0dJpbc1sj74DHcDYQi9rBhFSncbQ&prompt=Kubernetes Bootcamp Terminal&color=326de6&secondary=273d6d&hideintro=false:302:17)
    at HTMLDocument.<anonymous> (?v=2&embed=true&ui=inline&host=kubernetes.io&url=https%3A%2F%2Fkubernetes.io%2Fdocs%2Ftutorials%2Fkubernetes-basics%2Fcreate-cluster%2Fcluster-interactive%2F&target=inline-terminal-1&nonce=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWJlZCI6dHJ1ZSwiZG9tYWluIjoiaHR0cHM6Ly9rdWJlcm5ldGVzLmlvLyIsImlwIjoiMjYwMDo4ODAyOjUzMDA6MmU4Ojk1NjA6NjhkMTpjYWNhOmRmYzQiLCJpYXQiOjE2NDk0ODg0MDEsImV4cCI6MTY0OTQ4ODQzMX0.HDlp1X8-nTZ9s3e0dJpbc1sj74DHcDYQi9rBhFSncbQ&prompt=Kubernetes Bootcamp Terminal&color=326de6&secondary=273d6d&hideintro=false:287:16)
    at HTMLDocument.dispatch (jquery-3.5.1.min.js:2:43090)
    at HTMLDocument.v.handle (jquery-3.5.1.min.js:2:41074)
```

Please don't make your webapp hard-depend on trackers.

**Comment by fake-name** [comment]
I should further add, `trackjs.com` is blocked in a lot of places. If you have DNS-based adblocking, it's generally blocked there too.

**Comment by sftim** [comment]
https://trackjs.com/ is an error logging tool (code library and web service). To me, error logging is a feature more than a bug. I'm not sure it's reasonable to block that tool on the grounds of it being a “tracker”.

Could you explain your concern @fake-name?

/priority awaiting-more-evidence

We could add an explanation that the uBlock tool considers the error logging within the interactive tutorial unacceptable, and advise people who use that blocker to look for an appropriate work-around.

**Comment by fake-name** [comment]
> https://trackjs.com/ is an error logging tool (code library and web service)

The concern here is it's effectively a 3rd party data aggregator that can operate on multiple websites. That sounds like something functionally indistinguishable from a tracker.

In any event, the point is, probably the most used ad-blocker (ublock origin) out there includes it in it's default set of block lists.  

Basically, the solution here would be to try loading the error logging tool, and if it doesn't load *don't* explode and completely fail to operate.

**Comment by sftim** [comment]
Tangential relevance: https://github.com/kubernetes/website/issues/33936

@fake-name we can't customize how Katacoda works. What we might be able to do instead is provide better diagnostics, so that people who use tools like uBlock can opt to turn the tool off once they decide they are happy with the level of error reporting that doing so implies.

**Comment by Darathor17** [comment]
Just come here to say I had the same problem with NextDNS and indeed tutorial is completely broken unless all blockers are disabled. 

I understand that the team does not have much margin here so maybe just give an explicit message about it (more and more people does use ad & tracker blockers). it will save a lot of time debugging it. (If I didn't find this thread, I would have skipped the tutorial completely).

**Comment by sftim** [comment]
/priority backlog
I don't think I can justify setting important-longterm here.

Feature improvement could be to detect likely blocking and reveal a note message that gives a hint about how to fix it.
/area web-development
/triage accepted

**Comment by Darathor17** [comment]
> Feature improvement could be to detect likely blocking and reveal a note message that gives a hint about how to fix it.

That would be an acceptable solution to this issue. 

IMO and while not something you did or can change in any way, the real issue lies with Katacoda -> not working at all while `trackjs.com` is blocked is not acceptable nowadays (as mentioned by @fake-name)

**Comment by fake-name** [comment]
> I don't think “some third party product doesn't like one of our suppliers' choice of libraries and services” counts as an actual bug.

This is an inaccurate summary. 

A more accurate summary would be "A large subset of privacy-focused tools regard one of your dependencies as functionally indistinguishable from creepy ad tracker".

You can argue with the characterization, but the fact is multiple independent tools have apparentlt started blocking `trackjs.com` due to privacy concerns. **This is an indisputable fact**.

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/37417

**Comment by sftim** [comment]
> We could add an explanation that the uBlock tool considers the error logging within the interactive tutorial unacceptable, and advise people who use that blocker to look for an appropriate work-around.

This is what I recommend. Separately, and for the longer term, we might feasibly be able to find a team of contributors willing to switch to a different way of providing those tutorials. I think that is a big ask.

**Comment by fake-name** [comment]
I still don't see why simply not failing on the error logging facility not loading isn't the preferred option.

**Comment by sftim** [comment]
Contributors are welcome to make a new live tutorial service to replace Katacoda, or to migrate our tutorials to a different service.

I think either of those options represents quite a lot of work. A _much_ more achievable step is to warn readers that our tutorial service relies on an error reporting tool that tracks use, and some ad blockers block it. We can provide additional detail about why there isn't any advertising.

All of that is _considerably_ less effort than migrating to a new in-browser Kubernetes environment, and we could deliver that very soon. I think we should do the quick easy thing early, and then decide on next steps.

/remove-priority awaiting-more-evidence

If folks would like to, come to the next Zoom meeting of SIG Docs, and recommend the approach to take. We can then decide if we'd have enough volunteer resources to make that happen.

**Comment by sftim** [comment]
> simply not failing on the error logging facility not loading isn't the preferred option.

It may not be as simple as you think, @fake-name. If you can show otherwise, that'd be really useful to learn.

**Comment by sftim** [comment]
We're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/). As such, we don't plan to fix this bug.

/triage unresolved

/remove-triage accepted

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
