### ISSUE TITLE
Is this right? A ClusterIP Service, to which the NodePort Service routes, is automatically created

### ISSUE THREAD

**Issue by usernameisnull** [kubernetes/website#32837]
**This is a Bug Report**
In the doc:
```
 A ClusterIP Service, to which the NodePort Service routes, is automatically created
```
When I create a service of type NodePort, a service of type ClusterIP is automatically created?
I doubt that.

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types

**Comment by sftim** [comment]
/remove-kind bug
/language en

Relevant to https://github.com/kubernetes/website/pull/30817 (see https://deploy-preview-30817--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/#publishing-services-service-types for a summary of Service types, and text that specifically states that later types depend on the existence of earlier ones).

**Comment by sftim** [comment]
@usernameisnull I've proposed a page rewrite that should help here. Would you have time to review that and see what you think?

**Comment by usernameisnull** [comment]
In https://deploy-preview-30817--kubernetes-io-main-staging.netlify.app/docs/concepts/services-networking/service/#publishing-services-service-types , it's the same。My native language is not english,I just feel that this sentence means that when the NodePort service is created, a ClusterIp service is automatically created. I am confused.

![image](https://user-images.githubusercontent.com/3390414/162745173-4cf00e3f-f412-4532-8e9c-f33e79c200da.png)

**Comment by usernameisnull** [comment]
thumbs up
