### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by Pengulll** [kubernetes/website#32849]
The following tutorial is not working: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

After I click "Click to Connect" with an image of the cat with a mask, and then "Start Scenario" nothing in the interactive tutorial will work or let me click on it.

**Comment by sftim** [comment]
Thanks for the report @Pengulll 

Can you try to rule out that this isn't an issue with network filtering? For example, if you are behind a network filter that only allows specific websites, maybe this tutorial relies on a website that is forbidden.

**Comment by Pengulll** [comment]
I have never set up such a thing. The only thing I found was to allow cookies but that didn't do anything :P Should I check somewhere for a network filter? I will look thoroughly in my chrome settings for one.

**Comment by Pengulll** [comment]
I'm trying to complete this lab for college and I don't see why it wouldn't work.

**Comment by miteshskj** [comment]
@Pengulll - If you have adblock or any other extensions, try disabling them for this page. I had the same problem and it worked after disabling adblock.

**Comment by Ulrar** [comment]
Same issue here, had to disable pihole.

**Comment by Jun10ng** [comment]
It happened to me too and I solve it by **block the AdBlock chrome extension.**
