### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by josiah14** [kubernetes/website#3284]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
At least in my run-through of Module 2, there were actually 2 pods, one for what looks like Kubernetes, itself, and one for the delployed application. It appears that there was something wrong with the Kubernetes deployment, considering it was in an offline status of CrashLoopBackOff.  Google Search claims this normally means there's a required change to the configuration or the Dockerfile.

 ```
> kubectl get pods
NAME                                  READY     STATUS             RESTARTS   AGE
kubernetes-1677842136-h82s4           0/1       CrashLoopBackOff   7          11m
kubernetes-bootcamp-390780338-xfnfh   1/1       Running            0          59s
```

In terms of getting through the module, the problem is that the command provided by the tutorial will not, by itself, work for correctly setting the $POD_NAME var.

```
 > export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')

  > echo $POD_NAME
kubernetes-1677842136-h82s4 kubernetes-bootcamp-390780338-xfnfh
```

**Proposed Solution:**

The way I got around it was by adding a command before running the `curl` command to fix the POD_NAME var.

```
> export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')

  > export POD_NAME=`echo $POD_NAME | awk 'NF>1{print $NF}'`

  > echo $POD_NAME
kubernetes-bootcamp-390780338-xfnfh

  > curl http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAME/
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-390780338-xfnfh | v=1
```
**Page to Update:**

**Comment by josiah14** [comment]
Sorry for not providing a real solution - I'm more of a developer who hops in to do Linux administration as-needed.  Maybe somebody with more Sr. Level admin/ops chops can help out, here.

**Comment by zacharysarah** [comment]
@josiah14 Thanks for opening this issue. I'm flagging it for tech review. 👍

**Comment by BenHall** [comment]
Thank you for your feedback. We've updated the environment to remove the error and make this simpler. 

/close
