### ISSUE TITLE
Recommended Labels page suggests using SemVer when only a subset of semvers are valid

### ISSUE THREAD

**Issue by astellingwerf** [kubernetes/website#32855]
The page [Recommended Labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) recommends setting the `app.kubernetes.io/version` label. One of the suggested values is a semver. The problem with that recommendation is that there are plenty of fully compliant semvers that are incompatible with the restrictions that k8s put on the [character set](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set). Including the build number, for example, will cause a runtime error:

```
cannot patch "devx-fanout" with kind Ingress: Ingress.extensions "devx-fanout" is invalid: metadata.labels: Invalid value: "22.2.0+4770": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

**Comment by sftim** [comment]
/retitle Recommended Labels page suggests using SemVer when only a subset of semvers are valid

A plausible fix would be to specify the version of SemVer - as I understand it, all 1.x SemVers _are_ valid.

/language en

**Comment by sergeyshevch** [comment]
I guess that another option is to add notes after the table that should contain something similar to 
```Please note that not all symbols that is valid in SemVer is valid for label value```

**Comment by astellingwerf** [comment]
> I guess that another option is to add notes after the table that should contain something similar to `Please note that not all symbols that is valid in SemVer is valid for label value`

That's quite vague still, and doesn't really help in understand what is allowed. Would it make sense to mention "Semantic Versioning 1.0.0"?

**Comment by sftim** [comment]
> That's quite vague still, and doesn't really help in understand what is allowed. Would it make sense to mention "Semantic Versioning 1.0.0"?

I think it would. We're then explicitly declaring a version of, uh, SemVer that we can be compatible with, following the rules of that version of SemVer.

**Comment by sftim** [comment]
@astellingwerf you are welcome to edit the issue description with that recommended fix, or to include a link to https://github.com/kubernetes/website/issues/32855#issuecomment-1284524320

**Comment by sergeyshevch** [comment]
Ok so we want to change the description in the table to 
```
The current version of the application (e.g., a semantic version v1.x.x, revision hash, etc.)
```

**Comment by jai** [comment]
> As a project, let's _recommend_ using SemVer 1.0
> 
> We can explain that if people want to use another version scheme, they have options:
> 
> * use your own **annotation** (custom key)
> * use different label, which means using a custom key for that

I'm not sure how far/how we wanted to go about this @sftim - 

* _recommend_ using SemVer 1.0 - do we mean more so than revision, hash, etc? In which case re-word the whole line from:

```
The current version of the application (e.g., a SemVer 1.0, revision hash, etc.)
```

to 

```
The current version of the application (e.g., SemVer 1.0 recommended)
```
---
Then for the explanation on custom keys, add to the bottom of the table as a footnote or something similar?
