### ISSUE TITLE
Add examples for creating an object to new-style API reference

### ISSUE THREAD

**Issue by vishwanathjadhav** [kubernetes/website#32858]
A few examples to use API methods will be helpful. Documentation is missing the examples.

Example page: https://k8s.io/docs/reference/kubernetes-api/cluster-resources/node-v1/

**Comment by sftim** [comment]
Hello. Would you be able to explain more the improvement you have in mind? If you could sketch out one or two of the examples you were hoping to see (don't worry about being technically accurate, that's not what we need for the sketch) then that will help us understand the gap better.

**Comment by vishwanathjadhav** [comment]
Hi Tim,

Thanks for the quick reply. I am looking at [Kubernetes API](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/node-v1/#create-create-a-node) Doc for node creation(overall management) but I don't know what format of the metadata/parameters needs to provide so that my curl request would create/add the node as a control plane node or a worker node. Few examples for adding, removing nodes would be helpful

Using the following API I can list the nodes added to the cluster
e.g: 
~~~
 curl -X GET https://10.10.101.8:16443/api/v1/nodes --header "Authorization: Bearer $TOKEN" --cacert /var/snap/microk8s/3052/certs/ca.crt
~~~

But If I want to add another node using the API (e.g: POST /api/v1/nodes) what payload/parameters need to be provided for curl, and what curl request will look like. Is it possible to create/add a new node as a worker/control plane node using REST-APIS? Is there any API that is directly used to invite the other node to join the current cluster?

Please let me know if you have some doubts about the above query.

**Comment by sftim** [comment]
/retitle Add examples for creating an object to new-style API reference

**Comment by sftim** [comment]
The client that adds a node is _usually_ the kubelet. We can still look to give an example for how you'd create an object of each type.
Part of that story could be a page about how to read the API reference and work out a JSON payload based on what you see there and the object you want to create. Then each API reference page could use a shortcode to include a summary of that page and also link to the full thing.

If we did this, I'd want to see enough detail so that the reader can use either a **create** verb or can use server-side apply.

**Comment by vishwanathjadhav** [comment]
@sftim - Thanks, Let us know if you need any additional information

**Comment by sftim** [comment]
/language en
/triage accepted
/priority backlog

Other improvements are more urgent.

**Comment by vishwanathjadhav** [comment]
Hi Guys Any progress on this ?

**Comment by sftim** [comment]
> guys

A [tip](https://www.theatlantic.com/family/archive/2018/08/guys-gender-neutral/568231/) on inclusive language.

Other improvements are, I judge, still taking priority. We should do this work - I like the idea - but it's not top of the list.

https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Apriority%2Fimportant-longterm%2Cpriority%2Fimportant-soon%2Cpriority%2Fcritical-urgent+sort%3Acreated-asc lists the issues that have higher priority than this enhancement.
