### ISSUE TITLE
bug: 在集群中使用级联删除 hyperlink is 404

### ISSUE THREAD

**Issue by wangxiaoyang-dev** [kubernetes/website#32851]
There is a bug:
https://kubernetes.io/zh/docs/tasks/administer-cluster/use-cascading-deletion/#:~:text=%E4%BA%86%E8%A7%A3%20Kubernetes%20finalizers-,%E4%BA%86%E8%A7%A3%E5%9E%83%E5%9C%BE%E6%94%B6%E9%9B%86.,-%E5%8F%8D%E9%A6%88
This hyperlink is 404, it should be "https://kubernetes.io/zh/docs/concepts/architecture/garbage-collection/"

**Comment by mengjiao-liu** [comment]
The issue was solved by PR #32852. If there is any problem, please give feedback again.
/close
