### ISSUE TITLE
Translation of "grace period"

### ISSUE THREAD

**Issue by shinegrin** [kubernetes/website#32854]
**This is a Feature Request**

**What would you like to be added**

In https://kubernetes.io/zh/docs/concepts/workloads/pods/pod-lifecycle/, the chinese translation of "grace period" may be better with "优雅限期", rather than "体面期限".
In other words, the word "grace" may be better with translating it into "优雅".

**Why is this needed**
优雅地终止Pod，优化终止期限，在语言表达上要比“体面”更加符合翻译的“信达雅”准则。

**Comments**

**Comment by tengqm** [comment]
这个问题讨论过多次了。Gracefully shutdown a node. 究竟是“优雅地关闭一个节点”，还是“体面地关闭一个节点”。

在英文中，grace 这个词有一种解释，非常接近我们这个上下文：

noun.
a period officially allowed for payment of a sum due or for compliance with a law or condition, especially an extended period granted as a special favor.

grace 的另一个英文解释，更接近中文的“优雅”，甚至接近于 charm 的含义。

noun.
simple elegance or refinement of movement

就节点关闭或 Pod 终止而言，根本谈不上什么“优雅”。这里的 gracefullly 是相对于 forcefully、brutally 而言的。其用途是让节点或 Pod 在即将被删除之前能够有一点时间做一些收尾、清理工作。这个事情是被 granted、allowed，究竟是被动的。与被强制地、不由分说地杀死相比，给了节点或 Pod 一点点“尊严”，让它们能够在一定程度上被善待、被尊重。

因此，在讨论术语翻译时已经讨论过，这个词翻译为“体面地”。

/close
