### ISSUE TITLE
为命名空间配置默认的 CPU 请求和限制

### ISSUE THREAD

**Issue by zguolee** [kubernetes/website#32879]
删除你的命名空间：

`kubectl delete namespace constraints-cpu-example`

应该是

`kubectl delete namespace default-cpu-example`

**Comment by tengqm** [comment]
@zguolee Would you like propose a fix?

**Comment by zguolee** [comment]
Ok, I've done it.

**Comment by jihoon-seo** [comment]
- en: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/#:~:text=kubectl%20delete%20namespace%20default%2Dcpu%2Dexample
- zh: https://kubernetes.io/zh/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/#:~:text=kubectl%20delete%20namespace%20constraints%2Dcpu%2Dexample

/triage accepted
