### ISSUE TITLE
Cannot drag horizontal scrollbars in documentation

### ISSUE THREAD

**Issue by alfahadp** [kubernetes/website#32873]
Horizontal scrollbar on certain code sections are not working. 

eg: https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/#supported-fields

**Comment by sftim** [comment]
I can replicate this
/kind bug
/area web-development
/triage accepted
/lifecycle frozen

**Comment by a-mccarthy** [comment]
I checked out the linked example, but its seems to be working now. Does someone know of another example of the horizontal scrollbars not working correct?

@sftim I think this might be something else fixed by upgrading the [docsy version](https://github.com/kubernetes/website/pull/32906).

**Comment by sftim** [comment]
I can no longer replicate this. :tada:

/close

@alfahadp if this is still happening, you're welcome to either reply to this comment or to reopen the issue.
