### ISSUE TITLE
Secrets: Mounting optional Secrets as Volumes

### ISSUE THREAD

**Issue by synox** [kubernetes/website#32889]
The docs make it seem that you can only mark secrets mounted as parameters as optional, but not when mounted as volumes. 
However, my tests confirmed that k8s `v1.21.11` does support mounting secrets as volumes marked as optional. 

Docs to improve:
> https://kubernetes.io/docs/concepts/configuration/secret/#restriction-secret-must-exist
> When you define a container **environment variable** based on a Secret, you **can mark it as optional**.

**Comment by sftim** [comment]
I actually think this might still need fixing. @synox is this definitely fixed?

**Comment by manudev-1** [comment]
Is this still an issue?

**Comment by tengqm** [comment]
Not sure which sentence leads you to think that way?

**Comment by synox** [comment]
From what I see the docs are still not accurate, or at least confusing to me.
