### ISSUE TITLE
“Creating a cluster with kubeadm” unclear on meaning of Installing kubeadm step

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#32880]
**This is a Bug Report**

**Problem:**
[Creating a cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/) lists prerequisites but does not mention that each server must already have a container runtime installed and working.

The need for a container runtime (and the fact that it doesn't come with Kubernetes) is a crucial detail; omitting it may give readers who are new to Kubernetes the impression that our docs are unfinished or unhelpful.

**Proposed Solution:**
- Update the page to explicitly list a container runtime as a prerequisite.
- Link to https://kubernetes.io/docs/setup/production-environment/container-runtimes/

_or_

clarify that “installing kubeadm” actually also covers container runtime setup

_or_

move the part where people install a container runtime out of https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/, and make https://kubernetes.io/docs/setup/production-environment/container-runtimes/ be the page that runs through a container runtime install

_or_

something else? Comments are welcome

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Additional Information:**
/language en
/priority backlog
/sig cluster-lifecycle

**Comment by miteshskj** [comment]
The Instructions begins with "Installing kubeadm" which is a link to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ .
That page covers all the prerequisites (including container runtime and additional details not covered in create-cluster-kubeadm page).
Instead of adding same details again, should we just remove all duplicate info from create-cluster-kubeadm page and inform users to complete the requirements in install-kubeadm page before proceeding with cluster creation?

**Comment by sftim** [comment]
In code, it's usually a good idea to avoid repeating yourself.

In docs, though, it can be worthwhile making the same point twice. Maybe we should move the part where people install a container runtime out of https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

Someone who has `kubeadm` installed but doesn't have a container runtime is likely to skip past “Installing kubeadm” and might actually be frustrated to find that the step they missed appears to be buried within a step that they were sure they had completed.

**Comment by miteshskj** [comment]
Agree. Currently, https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ only mentions that container runtimes need to be setup and links to https://kubernetes.io/docs/setup/production-environment/container-runtimes/ for detailed instructions.

In this page (create-cluster), we rename step 1 to something as "Prepare the hosts" and here we inform users that they need to complete all the prerequisites mentioned in the install-kubeadm page along with its link.
