### ISSUE TITLE
Update docs to mark in-tree Cinder plugin as deprecated

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/website#32904]
**This is a Bug Report**

**Problem:**

CSI Migration for OpenStack Cinder moved to Beta in 1.21 release so the in-tree plugin was already deprecated at that time. The in-tree plugin should be marked as deprecated in Kubernetes docs.

https://kubernetes.io/docs/concepts/storage/volumes/#cinder

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/retitle Update docs to mark in-tree Cinder plugin as deprecated
