### ISSUE TITLE
Update docs to mark in-tree GCP PD plugin as deprecated

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/website#32902]
**This is a Bug Report**

**Problem:**
CSI Migration for gcepersistentdisk moved to Beta in 1.17 release so the in-tree plugin was already deprecated at that time. The in-tree plugin should be marked as deprecated in Kubernetes docs.

https://kubernetes.io/docs/concepts/storage/volumes/#gcepersistentdisk

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/retitle Update docs to mark in-tree GCP PD plugin as deprecated
/language en
