### ISSUE TITLE
Improvement for en/docs/reference/glossary/api-eviction.md

### ISSUE THREAD

**Issue by 196Ikuchil** [kubernetes/website#32935]
**This is a Feature Request**

**What would you like to be added**

I think it is difficult to understand the difference between this and the DELETE API.
The Eviction API complies with PodDisruptionBudget.
Therefore, I would like to add new lines that explain about PodDisruptionBudget like this.
```
API-initiated evictions respect your configured [`PodDisruptionBudgets`](/docs/tasks/run-application/configure-pdb/)
and [`terminationGracePeriodSeconds`](/docs/concepts/workloads/pods/pod-lifecycle#pod-termination).
```
(This is from [this page](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/))

**Comment by sftim** [comment]
/kind feature

It'd also be OK to change the final part of the glossary entry to hyperlink to https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/
