### ISSUE TITLE
Hyperlink to support period details

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#32930]
**This is a Feature Request**

**What would you like to be added**
- Update https://kubernetes.io/releases/ so that the text “_approximately 1 year of patch support_” is a hyperlink to https://kubernetes.io/releases/patch-releases/#support-period
- Update https://kubernetes.io/docs/home/supported-doc-versions/ to add some next text of your choice that also includes a hyperlink to https://kubernetes.io/releases/patch-releases/#support-period

Make sure that the changes you propose follow our [style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

**Why is this needed**
We want to make it easy to find out how long Kubernetes is supported for, and https://kubernetes.io/releases/patch-releases/#support-period is not as easy to discover as it could be.

**Comments**
/kind feature
/language en
/triage accepted
/priority backlog
/good-first-issue

[Contributing new content](https://kubernetes.io/docs/contribute/new-content/) is there to help you get started if you're new to this (if you're not a new contributor, this good-first-issue might be something you consider leaving for someone else to work on.)

**Comment by sftim** [comment]
Feel free to reply to this issue if you want to work on this but have questions about how to do that.

**Comment by VanshulB** [comment]
@sftim I want to work on that issue
Can you please assign it to me.

**Comment by shivam-sharma7** [comment]
could you assign me for this issues?

**Comment by samnoon1971** [comment]
Hi! I added the necessary fixed in pull request

**Comment by sftim** [comment]
PR #32986 covers this.

**Comment by sftim** [comment]
Folks looking to work on this: there is already a pull request open.

**Comment by mehabhalodiya** [comment]
> What would you like to be added
> 
>-  Update https://kubernetes.io/releases/ so that the text “approximately 1 year of patch support” is a hyperlink to https://kubernetes.io/releases/patch-releases/#support-period
> - Update https://kubernetes.io/docs/home/supported-doc-versions/ to add some next text of your choice that also includes a hyperlink to https://kubernetes.io/releases/patch-releases/#support-period

@NitishKumar06 #33007 addresses one of the issues and #33772 resolves another one from above mentioned two of them. 
Right now, one is already merged and waiting for #33772 to get approved, and then we can close this issue.
Hope you got my point!
Thank you 🙂

**Comment by mehabhalodiya** [comment]
Closing as per [this comment](https://github.com/kubernetes/website/issues/32930#issuecomment-1140745953).
/close
