### ISSUE TITLE
Add dockershim to the Glossary

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#32936]
Not a 1.24 blocker.

[Original discussion on Slack.](https://kubernetes.slack.com/archives/C02PZMA3R6E/p1649868016215619)

Add `dockershim` to the Kubernetes glossary. 

### Proposed content

dockershim

A component present in Kubernetes version 1.23 and earlier that allowed Docker Engine to communicate with Kubernetes system components like the kubelet. The dockershim was removed in v1.24. For more information, read the [Dockershim FAQs](https://kubernetes.io/dockershim).

/sig docs
/language en
/cc @sftim 
/assign

**Comment by sftim** [comment]
/triage accepted
Thanks @shannonxtreme 

/help
