### ISSUE TITLE
Dynamic Admission Control

### ISSUE THREAD

**Issue by chipzoller** [kubernetes/website#32960]
I recommend adding a section or at least sentence which explains to readers the order in which multiple webhooks of the same type are called. I.e., there are three validating webhooks configured in a cluster. Are they called serially? If so, what logic does the API server use to determine which goes first, second, and last?

**Comment by sftim** [comment]
Hi @chipzoller 

What's the URL of the page that you recommend fixing?

**Comment by chipzoller** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

**Comment by sftim** [comment]
I think we should document that validating webhooks may be called in any order and potentially even in parallel.

/sig api-machinery
