### ISSUE TITLE
[ja] `concepts/cluster-administration/addons` might be outdated

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#32999]
**This is a Bug Report**

**Problem:**
The file `content/ja/docs/concepts/cluster-administration/addons.md` might be outdated.
- en: https://kubernetes.io/docs/concepts/cluster-administration/addons/
  Under "Networking and Network Policy" section,
  the entry "Contiv" exists.
- ja: https://kubernetes.io/ja/docs/concepts/cluster-administration/addons/
  The entry "Contiv" does not exist.

**Proposed Solution:**
Update `content/ja/docs/concepts/cluster-administration/addons.md`.

**Page to Update:**
https://kubernetes.io/ja/docs/concepts/cluster-administration/addons/

/language ja

**Comment by t-inu** [comment]
@hase1128
I'd like to create a PR for this issue.
Please comment if you are working on this issue.

**Comment by hase1128** [comment]
@t-inu 
sorry, I have not started to work this issue.
please do that.

**Comment by t-inu** [comment]
@hase1128
Thanks for your reply. I'll do it.
/assign
