### ISSUE TITLE
Extend the Kubernetes API with CustomResourceDefinitions

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#33026]
In section [Create a CustomResourceDefinition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) it is said:

   _**The CRD can be either namespaced or cluster-scoped, as specified in the CRD's ``scope``**_

That text is wrong (a CRD object and the custom resource created from that CRD object are not the same). It should better say:

   _**The custom resource created from a CRD object can be either namespaced or cluster-scoped, as specified in the CRD's ``spec.scope`` field**_

**Comment by sftim** [comment]
/wg API expression
/language en
I like the new wording you suggested @antaloala - would you be willing to open a pull request proposing that fix?

**Comment by antaloala** [comment]
Thanks @sftim 
Yes, I am raising the PR. It is to be the first one I am creating against kubernetes documentation. Anything I should take care of? (thanks in advance ;-)

**Comment by antaloala** [comment]
I found all details in [https://github.com/kubernetes/website#contributing-to-the-docs](https://github.com/kubernetes/website#contributing-to-the-docs). I am then following it ;-)

**Comment by sftim** [comment]
@antaloala you've found the right guide. I hope it covers everything you need to know, but if it doesn't then please feel free to ask questions.

**Comment by mehabhalodiya** [comment]
@antaloala I don't see any updates; so unassigning you. Please feel free to assign it, if you come back here again and are willing to work on it! Thank you 🙂 
/unassign @antaloala 

/good-first-issue

**Comment by Rishit-dagli** [comment]
Saw this good first issue with no on assigned, I could take it up
/assign

**Comment by antaloala** [comment]
Thanks a lot for putting hands on this ... and sorry a lot for not having done it myself as initially proposed (I was disconnected for some long time).
