### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/

### ISSUE THREAD

**Issue by gokhankocak** [kubernetes/website#33027]
Hello,
It's not clear what the meaning of restricted warnings and restricted audit or any combination of them.
It seems that you attempt to design in a way that you want to make things more complicated.
The aim of your design seems that nobody should be able to understand clearly and one should spend a lot of time for understanding the basics.
You can create very complex systems but at the end you will see that nobody uses them.
We have seen such attempts in the past from big vendors and after a lot of marketing and spending millions of dollars, those big guys failed miserably.

Can someone explain the meaning of all those and possibly more combinations?

enforce: baseline, audit: baseline, warn: baseline
enforce: baseline, audit: restricted, warn: baseline
enforce: baseline, audit: restricted, warn: restricted
enforce: restricted, audit: baseline, warn: baseline
enforce: restricted, audit: restricted, warn: baseline
enforce: restricted, audit: restricted, warn: restricted
enforce: privileged, audit: baseline, warn: baseline
enforce: privileged, audit: privileged, warn: baseline
enforce: privileged, audit: privileged, warn: privileged
enforce: baseline, audit: restricted, warn: privileged
...
...
...

**Comment by sftim** [comment]
The first sentence in this page is
> Namespaces can be labeled to enforce the [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards).

Although this introduction is accurate, we could add more text to avoid the risk of a reader skipping past it and then feeling confused.

For example, we could name the three Pod Security Standards and make each of those names a link to the relevant part of https://kubernetes.io/docs/concepts/security/pod-security-standards; we could also repeat the table from the top of https://kubernetes.io/docs/concepts/security/pod-security-standards

@gokhankocak do you think adding more text to the introduction would help here?

/language en
