### ISSUE TITLE
The CNCF hyperlink on the HOME page is overwritten and cannot be clicked

### ISSUE THREAD

**Issue by jpanda-cn** [kubernetes/website#33034]
**This is a Bug Report**

**Problem:**
The CNCF hyperlink on the HOME page is overwritten and cannot be clicked
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/50101020/164016125-eb97d885-f0a5-4237-b05d-89e07a1ce1be.png">

**Proposed Solution:**
After analyzing the element, I think the element may just want to get a `margin-top: 1rem !important;` effect,
**Page to Update:**
https://kubernetes.io/...

**Comment by jpanda-cn** [comment]
I will try to fix this if needed

**Comment by divya-mohan0209** [comment]
Fixed by #33038, hence closing.
