### ISSUE TITLE
Register and document service.alpha.kubernetes.io/tolerate-unready-endpoints annotation

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33061]
**This is a Bug Report**

**Problem:**
https://pkg.go.dev/k8s.io/kubernetes@v1.23.0/pkg/controller/endpoint mentions an unregistered annotation, `service.alpha.kubernetes.io/tolerate-unready-endpoints`

**Proposed Solution:**
Register the annotation (by updating [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/)) and document what it is / was for. Do this even if the annotation is deprecated; we should retain that documentation for a good number of versions after the deprecations.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig network
/triage accepted

**Comment by sftim** [comment]
/remove-lifecycle rotten

We should document this.

**Comment by mehabhalodiya** [comment]
@PriyanshuAhlawat I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @PriyanshuAhlawat

**Comment by Kartik494** [comment]
I would like to give a try on this.
