### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by opabloc** [kubernetes/website#33069]
Hi I just want to say that deployment application on interactive tutorial doesn't work.

Regards.

**Comment by secondsleep-blaine** [comment]
It appears to be working now. It may have been a transient issue, or it's been fixed before anyone had a chance to update this issue.

**Comment by shannonxtreme** [comment]
Dunno if this is related, but the iframe with the environment is static for me on Chrome 100.0.4896.88

![2022-04-21_18-14-33 (1)](https://user-images.githubusercontent.com/30392854/164560714-9326a342-b9fd-4459-8ead-95e3b5932ea1.gif)

**Comment by Kartik494** [comment]
@opabloc  this deployment interactive tutorial running fine on my env. Maybe could you recheck at your end.
Thanks!

**Comment by Kartik494** [comment]
@opabloc would you mind to recheck this again, if this seems to running fine then we can close this issue.
