### ISSUE TITLE
Certificate Signing Requests

### ISSUE THREAD

**Issue by boyadzhievb** [kubernetes/website#33081]
root@controlplane:~# kubectl apply -f userjhon
error: error validating "userjhon": error validating data: ValidationError(CertificateSigningRequest.spec): unknown field "expirationSeconds" in io.k8s.api.certificates.v1.CertificateSigningRequestSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by tengqm** [comment]
Have you turned the `CSRDuration` feature gate on?

**Comment by sftim** [comment]
GitHub is not the right place for support requests.

If you're looking for help, @boyadzhievb, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by boyadzhievb** [comment]
> 

I like your opinion, but this is not support request. I am accepting your apology. I just showed that k8s documentation has issue. Thank you.

**Comment by sftim** [comment]
/remove-kind support
/triage needs-information
/language en

Can you let us know:
- the URL of the web page that is wrong
- what is wrong with that page?

**Comment by boyadzhievb** [comment]
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/

I used a link on the page for reporting issues and thought that it will add the link automaticaly.

**Comment by sftim** [comment]
Thanks. And the other question was: what is wrong with that page?

**Comment by Shubham82** [comment]
Hi @boyadzhievb
Which Kubernetes version you are using?
 

> The spec.expirationSeconds field was added in Kubernetes v1.22. Earlier versions of Kubernetes do not honor this field. and 
  the minimum valid value for this field is 600, i.e. ten minutes.
