### ISSUE TITLE
Install and Set Up kubectl on Linux

### ISSUE THREAD

**Issue by Pradeepjraman** [kubernetes/website#33082]
Hello,
I was trying to install the kubectl binary in the non-internet/non-proxy enabled Linux RHEL OS machine. Could you please suggest here, how can I process this.

Thanks 
Pradeep

**Comment by jihoon-seo** [comment]
From https://github.com/kubernetes/website/issues/33110#issuecomment-1106528294:

"This looks like a request for help.

If you're looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

GitHub is not the right place for support requests."
