### ISSUE TITLE
Pull an Image from a Private Registry

### ISSUE THREAD

**Issue by asruc** [kubernetes/website#33110]
ImagePullBackOff error from K8s pod

Hi, we are facing an issue while pulling image from DockerHub private repository onto the AWS EKS pods. I have created the docker registry secret:
kubectl create secret docker-registry --dry-run=client docker-registry-secret --docker-server=https://index.docker.io/v1/ --docker-username=<username> --docker-password=<password> --docker-email=<email>

In my K8s Deployment script, I have specified the imagePullSecrets as well. But when I tried to recreate the pod, it gives me the following error:
Failed to pull image "<image:tag>": rpc error: code = Unknown desc = Error response from daemon: pull access denied for <image-repo>, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

I'm able to see the secret when running:
kubectl get secret docker-registry-secret --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode

Attached my deployment script.

![image](https://user-images.githubusercontent.com/85205792/164684189-89ffa954-ab68-4324-bcff-76b93fccb06f.png)

**Comment by sftim** [comment]
This looks like a request for help.

If you're looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

GitHub is not the right place for support requests.

/kind support

**Comment by reylejano** [comment]
I'm closing this issue as this is a support request and not an issue related with kubernetes.io
To help you with you issue and this is my opinion only, you need to state the full path to the image including the private registry
e.g. 
`image: my-registry.io/images/my-image:tag`
