### ISSUE TITLE
Putting up the Chinese version of http://kubernetes.io

### ISSUE THREAD

**Issue by xinzhangcmu** [kubernetes/website#3313]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

Per discussion with @dankohn from CNCF, we aim to put up the Chinese version of http://kubernetes.io prior to the the [Linux Foundation event]( http://events.linuxfoundation.org/events/linuxcon-containercon-cloudopen-china) in Beijing, China this June.

**Proposed Solution:**

@dankohn and us (Caicloud) have discussed the attack plan as follows:

- Translate the md files
  - create a top-level `cn` directory where all the translated files will reside (already done in PR #2715 )
  - Caicloud will take the initiatives to translate dozens of .md files
  - We will call for volunteers from the broader Chinese Kubernetes community for crowd translation (**but before this we need to figure out the reviewing process**)

- Bring to life the Chinese Kubernetes site
  - get an appropriate domain for the site
  - pull together the website from those .md files

**Page to Update:**
http://kubernetes.io/...

Feel free to include relevant people in this thread

@bgrant0607 @janetkuo @chenopis @

**Comment by tsjsdbd** [comment]
挺好的，Kubernetes在中国还是非常流行的，+1

**Comment by chenopis** [comment]
@xinzhangcmu Do you have any ideas for the review process? Do we need to create a list of bilingual engineers in the Kubernetes community that could help review the translations?

**Comment by warmchang** [comment]
+1.

**Comment by zjj2wry** [comment]
+1 @chenhonggc i 'd like help review

**Comment by chenhonggc** [comment]
+1 支持国文。

**Comment by dankohn** [comment]
/remove-lifecycle stale

This is a high priority to support this quarter, once the Chinese translations of sufficient quality are finished and merged.

Cc @zacharysarah

**Comment by dankohn** [comment]
/remove-lifecycle stale

@zacharysarah Please feel free to close if this is being handled in a different issue.

**Comment by ajaeger** [comment]
@xinzhangcmu , @zacharysarah, https://kubernetes.io/cn/ is available - can this bug get closed now?
