### ISSUE TITLE
It's not clear how to contribute to interactive tutorials

### ISSUE THREAD

**Issue by ivan-freedomfi** [kubernetes/website#33140]
I've found a few minor problems in the [Deploying an App Interactive Tutorial](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/).

I want to fix them myself, but I can't find the code for this tutorial in this repository.

[Edit this page button](https://github.com/kubernetes/website/edit/main/content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html) on the tutorial page suggest to edit [deploy-interactive.md](https://github.com/kubernetes/website/edit/main/content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html), which only has a `<div class="katacoda__box" id="inline-terminal-1">` element.

The only thing I found is [retired kubernetes-bootcamp repo](https://github.com/kubernetes-retired/kubernetes-bootcamp/tree/5a965503bcd6e37e14bc1aeab11d89db45c0dca5/code/katacoda) with something resembling the interactive tutorial scenarios.

In the [Contribute guide docs](https://kubernetes.io/docs/contribute/) I couldn't find anything about editing the interactive tutorials.

Please tell me when can I edit the tutorial, and I'd fix it and add the info to the docs.

<img width="1675" alt="kubernetes-pod-name-tutorial-bug" src="https://user-images.githubusercontent.com/6686679/164893033-71192f92-145d-41a7-9dc4-1cc4c03b8dae.png">

<img width="1679" alt="kubernetes tutorial bug" src="https://user-images.githubusercontent.com/6686679/164893039-7e9cb0b8-650d-438c-85db-6915c13d74cb.png">

**Comment by sftim** [comment]
/kind feature

We should document that these live in https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios
/language en
