### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by nvsd** [kubernetes/website#33160]
Tutorials aren't interactive after initial load

**Comment by Kartik494** [comment]
Hi @nvsd Tutorial seems to be running fine , able to do all the steps mentioned there.Could you describe in details what error you are facing in it.
Thanks!!

**Comment by nvsd** [comment]
@Kartik494 Sure, the tutorial `iframe` element with the id `id="katacoda-container"` isn't interactable on the referenced page.

It's 100% due to an extension or firefoxes built in anti-tracking. It looks like `track.js` throws causing the tutorial to become unusable.

`Uncaught ReferenceError: trackJs is not defined` is the error.


<img width="400" alt="image" src="https://user-images.githubusercontent.com/7391612/166624338-82a01868-d872-47c7-8be3-621b2032e5b7.png">
and beyond that I have UBlock running.

I don't think there's much to do here beyond handling that failure gracefully but at the same time you can't support every crazy scenario browser extensions throw at you.

**Comment by sftim** [comment]
We don't maintain Katacoda, so a fix here would be a stretch. Is this OK to close?

**Comment by sftim** [comment]
Maybe we could add some separate JavaScript to detect that blocking has occurred and explain how to work around it?

**Comment by nvsd** [comment]
Yeah, I wasn't sure if track.js was implemented on your end or theirs.

`Maybe we could add some separate JavaScript to detect that blocking has occurred and explain how to work around it?`

This would definitely be a better UX.

**Comment by Kartik494** [comment]
> @Kartik494 Sure, the tutorial `iframe` element with the id `id="katacoda-container"` isn't interactable on the referenced page.
> 
> It's 100% due to an extension or firefoxes built in anti-tracking. It looks like `track.js` throws causing the tutorial to become unusable.
> 
> `Uncaught ReferenceError: trackJs is not defined` is the error.
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/7391612/166624338-82a01868-d872-47c7-8be3-621b2032e5b7.png">
> 
> and beyond that I have UBlock running.
> I don't think there's much to do here beyond handling that failure gracefully but at the same time you can't support every crazy scenario browser extensions throw at you.

@nvsd so it's an issue with extension or Firefox , and you are ok with it so can we close this issue.

**Comment by nvsd** [comment]
Er, sure.
