### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by FranCao** [kubernetes/website#33166]
Unable to work with any of the interactive tutorials. Shows a blank console, and the instructions on the left are also frozen at that spot.

![image](https://user-images.githubusercontent.com/43524590/164977868-2ed0e897-9060-4ca8-b5c2-5056fa7d8646.png)

**Comment by Shubham82** [comment]
Hi @FranCao
I tried the tutorial, it is working fine for me. Maybe this problem is from Katacoda side.
Could you please try again!

**Comment by jihoon-seo** [comment]
/team katacoda
For now, I see the same blank console.

**Comment by Shubham82** [comment]
For me it is still working

![Scrnshot](https://user-images.githubusercontent.com/50987400/165088478-6d3a3c37-e2ff-45f0-9ebe-6626ff82e341.png)

**Comment by Y-k-Y** [comment]
I have the same problem the terminal doesn't work at all. I can only click the button on the start screen

**Comment by martinanaya** [comment]
Try disabling any ad-blockers including those that are DNS-based. Had the same issue.

**Comment by sftim** [comment]
I think this would be fixed. @FranCao can you confirm if this works for you? (please try a few browsers, and be aware that some ad blockers block Katacoda even though it is not an advertisement).
