### ISSUE TITLE
Improvement for k8s.io/zh/docs/concepts/scheduling-eviction/kube-scheduler/

### ISSUE THREAD

**Issue by wwwpf** [kubernetes/website#33180]
original：Factors that need to be taken into account for scheduling decisions include individual and collective resource requirements, hardware / software / policy constraints, affinity and anti-affinity specifications, data locality, inter-workload interference, and so on.

translation：在做调度决定时需要考虑的因素包括：单独和整体的资源请求、硬件/软件/策略限制、 亲和以及反亲和要求、数据局域性、负载间的干扰等等。

"data locality" should translate to "数据局部性", not "数据局域性".

**Comment by mengjiao-liu** [comment]
[Wikipedia](https://zh.wikipedia.org/w/index.php?title=%E6%95%B0%E6%8D%AE%E5%B1%80%E9%83%A8%E6%80%A7&redirect=no) translates it as "数据局部性".
Generally speaking, in computer terminology, we translate this as "data locality".
Does this page need to be changed？
Request for advice@tengqm @howieyuen @Sea-n

**Comment by howieyuen** [comment]
查阅了相关资料，似乎只有“局部”这个词的解释，“局域”一般都和“网”连在一起，以“局域网”为词语出现。

**Comment by mengjiao-liu** [comment]
好的，那我们修改一下这个翻译吧，我打开了一个 PR #34818 来修复这个问题。
