### ISSUE TITLE
Tools Included : fish completion not supported

### ISSUE THREAD

**Issue by kifeo** [kubernetes/website#33205]
from the kubectl completion -h command, the fish auto completion is not mentioned, only bash and zsh.

also the command does not work as mentioned in the website:

```
kubectl completion fish
error: Unsupported shell type "fish".
See 'kubectl completion -h' for help and examples
```

**Comment by mk46** [comment]
Hi @kifeo, Seems like you are using `kubectl < v1.23`. Support of fish was added in v1.23 by https://github.com/kubernetes/kubernetes/pull/92989.

**Comment by kifeo** [comment]
Thanks @mk46, you were right, I was using 1.19 on that machine.
