### ISSUE TITLE
Safely Drain a Node topic does not mention kubectl cordon command

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#33202]
It seems like the "Safely Drain a Node" topic is supposed to mention the `cordon` command, but omits it by accident.

* The https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/ topic that links to this "Safely Drain a Node" topic states "The best practice prior to bringing your node down is to [safely drain and **cordon** your node](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)."
*  The "Safely Drain a Node" topic tells the user to `uncordon` command when they're done.

**Comment by sftim** [comment]
/retitle Safely Drain a Node topic does not mention kubectl cordon command

**Comment by sftim** [comment]
@rolfedh I think you wanted to report an issue with https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/ - is that the right URL?

/language en

**Comment by sftim** [comment]
A drain implicitly performs a cordon. We could mention https://k8s.io/images/docs/kubectl_drain.svg somewhere to make that more clear.

**Comment by sftim** [comment]
To fix this, we could add “drain” to the glossary and repeat that definition in this task page. We could also add a new page within https://kubernetes.io/docs/reference/node/ that defines:
- cordon
- uncordon
- drain

and add inbound links to that new reference page.
