### ISSUE TITLE
Kubernetes Release Cycle: release-cycle.png not available 

### ISSUE THREAD

**Issue by STRRL** [kubernetes/website#33204]
The picture with the address https://kubernetes.io/releases/release/release-cycle.png is not available.
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/20221408/165230465-dcfe31af-fa0e-4c38-b7f4-b5f2009299b2.png">

**Comment by STRRL** [comment]
https://kubernetes.io/releases/release/release-lifecycle.png +1

It seems they still exist at https://github.com/kubernetes/community/tree/master/contributors/devel/sig-release, but as .jpg

**Comment by sftim** [comment]
/kind bug
/language en
/sig release
/priority backlog

Part of the fix needs to happen in [k/community](https://github.com/kubernetes/community).

Ideal fix: find the vector source of that image, add that image as SVG to _this_ repository, update https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md to reference the image from https://kubernetes.io/

Failing that, make a PNG image that is current and uses Kubernetes colors where possible. Pick a high enough resolution that it will render well on the website but not look huge on k/community.

I think that'd work. There's a tension between keeping the doc in k/community working and keeping the autogenerated copy on https://kubernetes.io/ working, so any solution needs to account for both sides.

I don't recommend using a JPEG image. JPEG encoding is lossless and this makes it a poor choice for diagrams.

**Comment by mk46** [comment]
@sftim @STRRL Hi, Seems like this had been addressed in https://github.com/kubernetes/website/pull/34918.
Can we close this?
Thanks!!

**Comment by STRRL** [comment]
> @sftim @STRRL Hi, Seems like this had been addressed in #34918. Can we close this? Thanks!!

Yes! I could see the picture from the website. I am going to close this issue now!
