### ISSUE TITLE
Link for Auditing is not working.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#33211]
**This is a Bug Report**

**Problem:**
The Monitoring, Logging, and Debugging task section is Reorganized (for reference #32823). Due to this Auditing [hyperlink](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) show 404(nothing) because it is now under `content/en/docs/tasks/debug/debug-cluster/audit.md` not in `content/en/docs/tasks/debug-application-cluster/audit/`.  So we have update those Auditing links.
**Proposed Solution:**
We will have to use this link:` https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/` for Auditing instead of `https://kubernetes.io/docs/tasks/debug-application-cluster/audit/`.
**Page to Update:**

https://kubernetes.io/docs/concepts/cluster-administration/
https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/
https://kubernetes.io/docs/concepts/security/controlling-access/
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

**Comment by sftim** [comment]
As well as fixing the hyperlinks, I recommend adding a redirect (edit `static/_redirects`).
/triage accepted
/priority backlog

**Comment by Shubham82** [comment]
> As well as fixing the hyperlinks, I recommend adding a redirect (edit `static/_redirects`). /triage accepted /priority backlog

Sure I will do that soon.

**Comment by duncan485** [comment]
Had the unfortunate luck that this arised during my CKS certification exam. Please merge this asap.

**Comment by sftim** [comment]
Also see issue #33227

**Comment by Shubham82** [comment]
> 

Sure.
