### ISSUE TITLE
“Installing kubeadm” recommends downloads from non-canonical (?) URLs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33228]
**This is a Bug Report**

**Problem:**
The “without a package manager” section of [Installing kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) suggests that people download components from within https://storage.googleapis.com/kubernetes-release/release/

However, https://www.downloadkubernetes.com/ recommends downloading from https://dl.k8s.io/

To me, the https://dl.k8s.io/ URLs seem more official and also make it easier for us to bolt in a CDN or whatever if we want to serve content from not-Google. 

**Proposed Solution:**
- Revise the “without a package manager” tab in  [Installing kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) to recommend downloading `kubeadm` and `kubelet` from https://dl.k8s.io/
   - If possible, avoid fetching the latest release version via HTTP.
     This website repo already has the release information available so we can cut out a step (and make the docs more accurate when people are reading docs for previous Kubernetes versions).
- For the `kubectl` download, refer readers to https://kubernetes.io/docs/tasks/tools/#kubectl
- Continue to recommend downloading `crictl` from GitHub
- Continue to recommend downloading CNI tooling from GitHub

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Additional Information:**
The same page also recommends downloading packages (RPM, `.deb`) from Google. This issue doesn't cover the packaged downloads, just the direct downloads of the files.
This issue also doesn't cover a change to how people download `crictl` and install that tool.
This issue also doesn't cover a change to how people download CNI tooling.

/sig release
/sig cluster-lifecycle
/language en

**Comment by shannonxtreme** [comment]
If we remove the RELEASE version fetch step, we'd need a step to choose a Kubernetes version right? So something like "Choose the Kubernetes version you want to install from the Releases page." 

And then another line in the actual command that downloads kubeadm and the rest that says "Replace $RELEASE with the Kubernetes version that you selected". 

Am I off track here? 

also 

/triage accepted

**Comment by sftim** [comment]
You can _already_ choose which Kubernetes version you're reading the docs for, so it ought to be enough to signpost readers to the choice.

To help readers, we can also link from https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ to the same doc in each of the supported docs versions - I think that'd need a shortcode, but it could be done.

**Comment by sftim** [comment]
For example, https://v1-21.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ could explain how to install `kubeadm` v1.21.x (whatever is latest for v1.21).
