### ISSUE TITLE
Replace/Fix git.io URLs

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/website#33231]
**This is a Bug Report**

**Problem:**
git.io has been deprecated and will be [discontinued on 04-29-2022, when it will no longer redirect to the destination URL](https://github.blog/changelog/2022-04-25-git-io-deprecation/).

**Proposed Solution:**
A grep shows several places where git.io URLs are used:
```
content/pt-br/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # criar recurso(s) a partir de URL
content/zh/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # create resource(s) from url
content/zh/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo         # 从 URL 中创建资源
content/ja/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # urlで公開されているファイルからリソースを作成します
content/en/blog/_posts/2016-09-00-How-We-Made-Kubernetes-Easy-To-Install.md:- Install a pod network. [Weave Net](https://github.com/weaveworks/weave-kube) is a great place to start here. Install it using just kubectl apply -f https://git.io/weave-kube
content/en/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # create resource(s) from url
content/fr/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # Crée une ou plusieurs ressources depuis une url
content/ru/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # создать ресурсы из URL-адреса
content/de/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # Ressource(n) aus URL erstellen
content/id/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # membuat sumber daya dari sebuah tautan
content/vi/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # tạo tài nguyên từ url
content/ko/docs/reference/kubectl/cheatsheet.md:kubectl apply -f https://git.io/vPieo          # url로부터 리소스(들) 생성
```

There are really only two URLs:

|git.io URL|Redirects to|Proposed Solution|
|---|---|---|
|https://git.io/vPieo|https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.4/hack/testdata/recursive/pod/busybox.yaml|This manifest is from version 1.4, so pretty old and is used by the [kubectl cheat sheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#creating-objects).  The simplest fix would be to reference it directly instead of using a shortened URL.  Would it be preferable to copy this manifest out of the k/k repo and into the k/website repo?  I don't know, maybe|
|https://git.io/weave-kube|https://github.com/weaveworks/weave/releases/download/latest_release/weave-daemonset.yaml|This URL 404s, so I don't really know what this is supposed to be.  This usage is on [an old blog post from 2016](https://kubernetes.io/blog/2016/09/how-we-made-kubernetes-easy-to-install/) that just got stale.  Maybe it is OK to leave it as-is, or provide a comment acknowledging that the link is broken.  Is there a policy on how to treat stale blog posts?|

**Page to Update:**
* https://kubernetes.io/docs/reference/kubectl/cheatsheet/#creating-objects
* (Maybe?) https://kubernetes.io/blog/2016/09/how-we-made-kubernetes-easy-to-install/

**One more thought about URL shorteners in example code...**
I also think that in general we should probably not suggest for users to apply a shortened URL directly by using `kubectl apply -f` as the creator of that shortened URL could, at any time, change the redirect destination to something malicious without the knowledge of the documentation maintainers, resulting in a security problem.  It would be safer to have it point to a location in a repo owned by the Kubernetes org in the case of example code.

I don't know, maybe there is already a policy about this, but if not, maybe one should be considered.  I'm mostly talking about something a user might paste and execute from a command line example, and less about general documentation links, which are probably fine.

**Comment by sftim** [comment]
/language en

---

>  Is there a policy on how to treat stale blog posts?

We usually don't edit them.

It's OK to make edits to remove broken URLs. For example, we could change:

> Install a pod network. [Weave Net](https://github.com/weaveworks/weave-kube) is a great place to start here. Install it using just kubectl apply -f https://git.io/weave-kube Presto! You have a working Kubernetes cluster! [Try kubeadm today](https://kubernetes.io/docs/getting-started-guides/kubeadm/).

to:
> Install a pod network.

and add a note to the article to say it was edited to remove a broken hyperlink.

**Comment by sftim** [comment]
How about changing from `kubectl apply -f https://git.io/vPieo`  to `kubectl apply -f https://manifests.example/some-manifest.yaml`

The `example` domain will never serve malware via HTTPS; if it does, something is very wrong!

**Comment by brianpursley** [comment]
Yes, I like your idea of using an example domain here.  There is no reason for the sake of documentation that this has to resolve to an actual manifest, and is probably a safer option overall.

**Comment by brianpursley** [comment]
It looks like GitHub reconsidered based on developer feedback, and will continue serving existing git.io redirects, for now at least.

https://github.blog/changelog/2022-04-25-git-io-deprecation/?#changelog-64536

**Comment by sftim** [comment]
Based on this news, a fix is less urgent.

/priority awaiting-more-evidence
/remove-triage accepted

**Comment by zilmarr** [comment]
Hello!
Is this something I could work on?

**Comment by natalisucks** [comment]
/triage accepted

Accepting based on my agreement with @sftim's [comment](https://github.com/kubernetes/website/issues/33231#issuecomment-1113235410) on updating the cheatsheet, which I can see that work has already begun on
