### ISSUE TITLE
Getting 404 page not found on this URL - Auditing Policy

### ISSUE THREAD

**Issue by srinigundaputalech** [kubernetes/website#33244]
Getting 404 page not found on this URL

https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by sftim** [comment]
/triage duplicate

This is similar to https://github.com/kubernetes/website/issues/33211

/language en

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #33220.
And I confirm that in `content/en/`, there exists no link that points to `debug-application-cluster/**.md`.
/close
