### ISSUE TITLE
Adding a link to the Version Skew Policy to the Upgrading kubeadm clusters

### ISSUE THREAD

**Issue by edoardo-c** [kubernetes/website#33259]
**This is a Feature Request**

**What would you like to be added**
I would like to add a link to the [Upgrading kubeadm clusters](https://kubernetes.io/docs/tasks/administer-cluster/kubead/kubeadm-upgrade/) that refers to the [Version Skew Policy](https://kubernetes.io/releases/version-skew-policy/). This could probably be added at the end of the opening paragraph.

> This page explains how to upgrade a Kubernetes cluster created with kubeadm from version 1.22.x to version 1.23.x, and from version 1.23.x to 1.23.y (where y > x). Skipping MINOR versions when upgrading is unsupported. For more details, please visit [Version Skew Policy](https://kubernetes.io/releases/version-skew-policy/).

**Why is this needed**
When searching for the shortest way to upgrade multiple minor versions, I couldn't find the documentation I needed to do it efficiently. Version Skew Policy explains it but I could not find the document. I would look for "Kubernetes upgrade" or "Kubernetes upgrade path" but ended up on the same upgrade document or other blogs explaining how to upgrade their Kubernetes flavour.

**Comments**
The quote describes what I'd like to see updated in the documentation. Thanks.

**Comment by neolit123** [comment]
Makes sense. Thanks for logging the issue.

/sig cluster-lifecycle
/help
