### ISSUE TITLE
Can you please help me this kubelet issue

### ISSUE THREAD

**Issue by Venkatraj1986** [kubernetes/website#33264]
[root@k8master ~]# dmidecode | grep -i vm
Manufacturer: VMware, Inc.
Product Name: VMware Virtual Platform
Serial Number: VMware-56 4d 1c d5 04 c4 85 8d-9b 8c 28 07 ea 6c 8b 2c
Description: VMware SVGA II
String 1: [MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]
[root@k8master ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)
[root@k8master ~]#

===============================================================

Kubelet service error

=================================================================================
===error is ===

Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.376327 2318 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
[root@k8master ~]# journalctl -xefu kubelet | grep Failed
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.376327 2318 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"

[root@k8master ~]#
[root@k8master ~]# systemctl status kubelet.service
● kubelet.service - kubelet: The Kubernetes Node Agent
Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/kubelet.service.d
└─10-kubeadm.conf
Active: active (running) since Sat 2022-04-23 07:55:56 IST; 6min ago
Docs: https://kubernetes.io/docs/
Main PID: 2318 (kubelet)
Tasks: 14 (limit: 23356)
Memory: 157.7M
CGroup: /system.slice/kubelet.service
└─2318 /usr/bin/kubelet

Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.338803 2318 cpu_manager.go:214] "Reconciling" reconcilePeriod="10s"
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.338843 2318 state_mem.go:36] "Initialized new in-memory state store"
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.341492 2318 state_mem.go:88] "Updated default CPUSet" cpuSet=""
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.341514 2318 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.341545 2318 policy_none.go:49] "None policy: Start"
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.342468 2318 memory_manager.go:168] "Starting memorymanager" policy="None"
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.342540 2318 state_mem.go:35] "Initializing new in-memory state store"
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.343639 2318 state_mem.go:75] "Updated machine memory state"
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.376327 2318 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.377000 2318 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
[root@k8master ~]#

**Comment by neolit123** [comment]
> Apr 23 07:55:58 k8master kubelet[2318]: I0423 07:55:58.376327 2318 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"

this is seen here, but it's not an error.
https://github.com/kubernetes/kubernetes/issues/109143

there is probably another error message that is causing the kubelet to fail. check the logs for `F.....` and `E....` log entries.

**Comment by pacoxu** [comment]
link dup(wrongly created issue) https://github.com/kubernetes/kubeadm/issues/2685
