### ISSUE TITLE
Request for Netlify access

### ISSUE THREAD

**Issue by reylejano** [kubernetes/website#33274]
As a SIG Docs co-chair and to support release team efforts on release day, I request access to kubernetes.io Netlify to update Netlify configuration on release days

/assign @jimangel 
/cc @divya-mohan0209 @natalisucks

**Comment by sftim** [comment]
I think people from SIG ContribEx or SIG k8s infra look after access here.
It makes sense that each co-chair and tech lead has Netlify access.

**Comment by reylejano** [comment]
Access to netlify has been granted by @jimangel 
/close
