### ISSUE TITLE
Translate reference/kubernetes-api/cluster-resources/component-status-v1.md to chinese 

### ISSUE THREAD

**Issue by syxunion** [kubernetes/website#33279]
Hi, I'm interested to translate the "reference/kubernetes-api/cluster-resources/component-status-v1" page.

This is a Feature Request:

translate en/docs/reference/kubernetes-api/cluster-resources/component-status-v1.md into Chinese.

What would you like to be added:

zh/docs/reference/kubernetes-api/cluster-resources/component-status-v1.md

/language zh

**Comment by mengjiao-liu** [comment]
#34744 worked for this issue.
/close
