### ISSUE TITLE
Netlify access request for v1.24 release

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#33273]
I'm requesting Netlify access for myself, @PI-Victor , and @jlbutler for the v1.24 release.

I’m asking for Jesse and Victor to also be added as I will be travelling on release day, and want to make sure that we’re still able to run release day activities even if my hotel wifi is terrible. Both Jesse and Victor have been docs leads previously (and are currently participating in v1.24).

My Netlify account is `nate-double-u` (same as I use on GitHub), and I believe I already have read access to v1.16 (or something like that), so I should already be in the Netlify userlist.

@PI-Victor, @jlbutler, please respond to this issue with your Netlify accounts to let the Chairs know who to give access to.

/assign @divya-mohan0209 @jimangel @natalisucks @reylejano

/milestone 1.24

**Comment by sftim** [comment]
@nate-double-u for ease of reference, could you link to the part of the release docs guide that explains who should have Netlify access?

**Comment by nate-double-u** [comment]
Sorry, didn't see your question till now Tim
https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/docs/Release-Timeline.md#update-netlify

Says "A [SIG Docs chair](https://github.com/kubernetes/community/tree/master/sig-docs#leadership) can assist you with access", which suggests that the docs lead _could_ do the work.

**Comment by sftim** [comment]
/priority critical-urgent
(I assume)

**Comment by nate-double-u** [comment]
@reylejano and @jimangel have been running the Netlify portion of the release.

**Comment by nate-double-u** [comment]
Closing as @reylejano and @jimangel are on it this time around. Thank you both, your being on hand has made my travel-release much less stressful than it could have been. 🙂

/close
