### ISSUE TITLE
translate reference/kubernetes-api/cluster-resources/binding-v1/

### ISSUE THREAD

**Issue by syxunion** [kubernetes/website#33301]
Hi, I'm interested to translate the "reference/kubernetes-api/cluster-resources/binding-v1/" page.

This is a Feature Request:

translate en/docs/reference/kubernetes-api/cluster-resources/binding-v1/.md into Chinese.

What would you like to be added:

zh/docs/reference/kubernetes-api/cluster-resources/binding-v1.md

/language zh

**Comment by mengjiao-liu** [comment]
PR #https://github.com/kubernetes/website/pull/33843 has been merged, so we can close this issue.
