### ISSUE TITLE
Dead link on https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/

### ISSUE THREAD

**Issue by thomasd-ign** [kubernetes/website#33312]
**This is a Bug Report**

**Problem:** A dead link appears on the web page https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/ at the end of _(As you read that, bear in mind that Linux kernel namespaces are a different thing from [Kubernetes namespaces](https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/h/docs/concepts/overview/working-with-objects/namespaces/))_

**Proposed Solution:** replace the address by https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Page to Update:**
https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/

**Comment by Shivansh-yadav13** [comment]
@thomasd-ign if you are talking about [What Are Namespaces and cgroups, and How Do They Work?](https://www.nginx.com/blog/what-are-namespaces-cgroups-how-do-they-work/) then it's not a dead link. 
It is working fine.

**Comment by thomasd-ign** [comment]
Hello @Shivansh-yadav13, I'm talking about this one : As you read that, bear in mind that Linux kernel namespaces are a different thing from [Kubernetes namespaces](https://kubernetes.io/blog/2022/04/28/ingress-nginx-1-2-0/h/docs/concepts/overview/working-with-objects/namespaces/))

**Comment by Shivansh-yadav13** [comment]
@thomasd-ign Ohk mb, are you adding it?

**Comment by thomasd-ign** [comment]
I tried a write a PR : https://github.com/kubernetes/website/pull/33315
