### ISSUE TITLE
Node affinity operator behavior is not defined

### ISSUE THREAD

**Issue by WilliamDenniss** [kubernetes/website#33323]
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity

The operator field is a fairly important aspect of the node affinity concept, and yet the behavior of the operator fields are undefined.

The docs list the following:

> You can use the operator field to specify a logical operator for Kubernetes to use when interpreting the rules. You can use `In`, `NotIn`, `Exists`, `DoesNotExist`, `Gt` and `Lt`.

But don't define the behavior of these operators. I think a table documenting this would be appropriate here.

It looks like [other folks](https://stackoverflow.com/questions/65801887/kubernetes-how-to-use-gt-operator-in-pod-nodeaffinity) have had the same questions that I had when reading this doc ("I didn't find any documentation").

**Comment by utkarsh-singh1** [comment]
Thanks @WilliamDenniss , that's a good idea to propose , and I think i still have not found any detailed explanation of operator fields

**Comment by sftim** [comment]
/remove-lifecycle rotten

Nice to have

**Comment by mehabhalodiya** [comment]
@utkarsh-singh1 I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @utkarsh-singh1

**Comment by sftim** [comment]
For hints on what to document, see https://github.com/kubernetes/website/issues/39256#issuecomment-1418316723
