### ISSUE TITLE
Container Runtimes: Add containerd debugging/usage page

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#33322]
For new users moving from docker post 1.24, its not clear how to do containerd ls commands and so on. For example, things like containerd namespaces, pause conatiners,  etc need to  get disambiguated from k8s concepts.   @ridavid2002 is writing some docs for this , maybe lets add a page in the website "how to use containerd to debug pods in a running cluster".

**Comment by jayunit100** [comment]
```
since 1.24 it will be increasingly common to see containerd as a runtime in most clusters.  the ctr command is associated with a configuratino file (i.e. on linux its usually somewhere like /etc/containerblah/toml
```

**Comment by sftim** [comment]
I'm not sure we should accept this issue without some discussion. If we document these steps specifically for containerd, what other runtimes should we cover? We should aim to answer that before moving the work forward.

**Comment by sftim** [comment]
Could that documentation instead live as part of the containerd docs?

**Comment by ridavid2002** [comment]
@sftim thank you for this feedback. I will revisit it further and think about how to best proceed.

**Comment by jayunit100** [comment]
Can we link to those docs from this page ?
