### ISSUE TITLE
Container Runtimes - containerd - link to getting started

### ISSUE THREAD

**Issue by strattner** [kubernetes/website#33327]
Under 2. Install containerd
The link to _Getting started with containerd_ is stale. 
Link currently goes to: https://containerd.io/docs/getting-started/#starting-containerd

Their site now recommends: https://github.com/containerd/containerd/blob/main/docs/getting-started.md

**Comment by mk46** [comment]
Hi @strattner,  Please provide the URL of the page you want to be updated.
/triage needs-information

**Comment by shivam-sharma7** [comment]
location of folder where required update?

**Comment by mk46** [comment]
Seems like the suggested change is already applied in https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd by https://github.com/kubernetes/website/pull/33321.

**Comment by strattner** [comment]
Hi, yes when I go to check now the URL was changed and is now correct. I'll close this issue.
