### ISSUE TITLE
Review and update network-plugins page

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#33338]
Review and update [Network Plugins](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/
) page.

Follow up to PR: #31849

> While the point of the PR to remove `--pod-cidr` is valid....
>
> The entire page needs a full tech review and update as the contents are out of date.

_Originally posted by @mikebrow in https://github.com/kubernetes/website/pull/31849#pullrequestreview-958106893_

**Comment by sftim** [comment]
/triage accepted

Maybe we can use the CNCF landscape (we already have a suitable shortcode) to list network plugins.
