### ISSUE TITLE
Auditing documentation moved and no redirects configured

### ISSUE THREAD

**Issue by infa-knandi** [kubernetes/website#33345]
https://kubernetes.io/docs/tasks/debug-application-cluster/audit
This page is missing.
This page has significant importance as audit-log documentation is done on this page only.

**Comment by jihoon-seo** [comment]
Please refer to https://kubernetes.slack.com/archives/C1J0BPD2M/p1651053713582139 :

> The page "Auditing" is moved to https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/ .

[Related issues/PRs]
- #33211
- #33227
- There exists work that is already under way: https://github.com/kubernetes/website/pull/33220#pullrequestreview-953824594 .

**Comment by sftim** [comment]
/triage duplicate

/retitle Auditing documentation moved and no redirects configured
/language en

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #33220.
And I confirm that in `content/en/`, there exists no link that points to `debug-application-cluster/**.md`.
/close
