### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by adrianfdez469** [kubernetes/website#33360]
Can't use the terminal.
Google Chrome: Version 101.0.4951.41 (Official Build) (64-bit)
Windows 10

**Comment by mk46** [comment]
Hi @adrianfdez469, I am able to open the terminal on this page. Kindly share screenshots of the issue, which help us to fix it.

**Comment by adrianfdez469** [comment]
Hi @mk46, thanks for reply. I think the problem might been a connection issue. I try again today and it works fine. Closing issue.
