### ISSUE TITLE
Improve explanation for Services without selectors

### ISSUE THREAD

**Issue by Ileriayo** [kubernetes/website#33361]
The ___Note___ paragraph under "Service without selectors" section reads thus:
> Note: The Kubernetes API server does not allow proxying to endpoints that are not mapped to pods. Actions such as `kubectl proxy <service-name>` where the service has no selector will fail due to this constraint.

Since `kubectl proxy` is meant to proxy connections to the api-server, shouldn't the command rather be `kubectl port-forward <service-name> hostPort:servicePort`?

_For more details, see https://github.com/kubernetes/website/issues/33361#issuecomment-1613303593_

**Comment by jihoon-seo** [comment]
URL: https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

**Comment by sftim** [comment]
We should triage this.

**Comment by stormqueen1990** [comment]
It seems this note has the incorrect command indeed. As per [kubectl proxy docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#proxy), `kubectl proxy` doesn't take a resource name or object name as an unnamed argument. Although `kubectl proxy svc/<service-name>` doesn't fail, it does not seem to be any different from `kubectl proxy` without arguments and doesn't fail in the specific situation where a service without a selector is present in the cluster.

`kubectl port-forward`, on the other hand, will fail with an invalid service message if the service specified as a positional argument has no selectors:
```console
error: cannot attach to *v1.Service: invalid service '<test-svc>': Service is defined without a selector
```

/triage accepted

**Comment by sftim** [comment]
/retitle Improve explanation for Services without selectors
/close
Fixed
