### ISSUE TITLE
Have the website serving container available from a registry

### ISSUE THREAD

**Issue by craigbox** [kubernetes/website#33395]
I always forget I have to `make container-image` before `make container-serve`, which got me to thinking, why do I have to do this?

Per https://github.com/kubernetes/website/issues/33278#issuecomment-1112705866, a request that the image be served from a registry rather than built locally by each author.

**Comment by sftim** [comment]
/triage accepted
/lifecycle frozen
/priority important-longterm

Good idea!

**Comment by sftim** [comment]
@cpanato, this is the issue that I'd asked for some help with.
