### ISSUE TITLE
Grammar problem with Kubernetes Components concept

### ISSUE THREAD

**Issue by abs007** [kubernetes/website#33414]
The subtopic for [Addons](https://kubernetes.io/docs/concepts/overview/components/#addons) has a possible grammatical error. The second sentence starts with 'Because'. 

A likely fix would be to replace 'Because' with 'As'.

**Comment by sftim** [comment]
/retitle Grammar problem with Kubernetes Components concept
/language en

I don't see a grammar problem.
/priority awaiting-more-evidence

**Comment by abs007** [comment]
Fair enough. You can close the pr if you feel the need to do so.
