### ISSUE TITLE
Kubelet service issue 

### ISSUE THREAD

**Issue by Venkatraj1986** [kubernetes/website#33419]
[root@k8m ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.4 (Ootpa)
[root@k8m ~]#
[root@k8m ~]# dmidecode | grep -i vm
        Manufacturer: VMware, Inc.
        Product Name: VMware Virtual Platform
        Serial Number: VMware-56 4d da a4 dc 58 49 b5-c5 c9 c3 16 88 fd 74 7f
        Description: VMware SVGA II
        String 1: [MS_VM_CERT/SHA1/27d66596a61c48dd3dc7216fd715126e33f59ae7]
[root@k8m ~]#

[root@k8m ~]# systemctl status kubelet.service
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Tue 2022-05-03 16:27:14 IST; 5min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 4510 (kubelet)
    Tasks: 13 (limit: 49168)
   Memory: 38.1M
   CGroup: /system.slice/kubelet.service
           └─4510 /usr/bin/kubelet

May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.619005    4510 state_mem.go:36] "Initialized new in-memory state store"
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.619130    4510 state_mem.go:88] "Updated default CPUSet" cpuSet=""
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.619143    4510 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.619149    4510 policy_none.go:49] "None policy: Start"
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.620454    4510 memory_manager.go:168] "Starting memorymanager" policy="None"
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.620480    4510 state_mem.go:35] "Initializing new in-memory state store"
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.620722    4510 state_mem.go:75] "Updated machine memory state"
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.621661    4510 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.622133    4510 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
May 03 16:27:14 k8m kubelet[4510]: I0503 16:27:14.674114    4510 reconciler.go:157] "Reconciler: start to sync state"
[root@k8m ~]#

**Comment by neolit123** [comment]
Please try asking on support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
