### ISSUE TITLE
网络策略

### ISSUE THREAD

**Issue by Box-Cube** [kubernetes/website#33415]
![image](https://user-images.githubusercontent.com/64300761/166416942-76628a02-80cd-44f6-9b6c-889292981373.png)
not all namespace。In the Original English，it means " in a namespace".

**Comment by tengqm** [comment]
please provide the page location where a change is needed.

**Comment by Box-Cube** [comment]
> please provide the page location where a change is needed.

https://kubernetes.io/zh/docs/concepts/services-networking/network-policies/#networkpolicy-resource
search key words "该网络策略示例"

**Comment by tengqm** [comment]
Double checked the YAML and the text. The current translation is correct.
/close
