### ISSUE TITLE
Broken hyperlink in Dynamic Admission Control reference

### ISSUE THREAD

**Issue by jimsnab** [kubernetes/website#33423]
The "See JSON patch documentation" link on [this page](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) is invalid.

Is the link supposed to be https://datatracker.ietf.org/doc/html/rfc6902?

**Comment by sftim** [comment]
/retitle Broken hyperlink in Dynamic Admission Control reference

https://jsonpatch.com/ doesn't have a valid security certificate. We could remove the sentence that links to it or nudge the maintainers of https://jsonpatch.com/ to fix their site.

/kind bug
/language en

**Comment by shurup** [comment]
@sftim https://jsonpatch.com/ is now operating with no errors (i.e., with a valid SSL certificate), so this issue can be closed.
