### ISSUE TITLE
[zh] Refactor pages in `zh/docs/tasks/debug-application-cluster`

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#33428]
**This is a Bug Report**

**Problem:**

In #32823, 
the files in `content/en/docs/tasks/debug-application-cluster/*.md` was moved to 
`content/en/docs/tasks/debug/debug-application/*.md` or `content/en/docs/tasks/debug/debug-cluster/*.md`.

But in `zh/` directory,
there still exists `content/zh/docs/tasks/debug-application-cluster/` directory,
so some refactoring might be needed.

**Proposed Solution:**

| Files in `zh debug-application-cluster/`  | Exist in `zh debug-application/` too?  | Exist in `zh debug-cluster/` too?  | Okay to remove?  | Refactoring PR  |   |
|---|---|---|---|---|---|
| [_index.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/_index.md)  |   |   | Yes  | #33372  |   |
| [audit.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/audit.md)  |   | Yes ([audit.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug/debug-cluster/audit.md))  | Yes  | #33372  |   |
| [crictl.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/crictl.md)  |   | Yes ([crictl.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug/debug-cluster/crictl.md))  | Yes  | #33372  |   |
| [debug-application-introspection.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-application-introspection.md)  | No, so moving is needed <br> ([to debug-running-pod.md](https://github.com/kubernetes/website/pull/32823/files#diff-4067ea9b384ba7713fe8c420948c3c89a42ac7874424347321af0cbd6789e186))  |   |   | #33372  |   |
| [debug-application.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-application.md)  | No, so moving is needed <br> ([to debug-pods.md](https://github.com/kubernetes/website/pull/32823/files#diff-714196198a9cf46c8ef533dd70a18713085f50880821dc829b95e366e186bb7c))  |   |   |   |   |
| [debug-cluster.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-cluster.md)  |   | No, so moving is needed <br> ([to _index.md](https://github.com/kubernetes/website/pull/32823/files#diff-aaa3e891815f1cc532fb0b532cd583e770302eec74e13614d1baae579d47b839))  |   | #33372  |   |
| [debug-init-containers.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-init-containers.md)  | No, so moving is needed  |   |   |   |   |
| [debug-pod-replication-controller.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md)  |   |   |   |   |   |
| [debug-running-pod.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-running-pod.md)  | No, so moving is needed <br> ([to debug-running-pod.md](https://github.com/kubernetes/website/pull/32823/files#diff-4067ea9b384ba7713fe8c420948c3c89a42ac7874424347321af0cbd6789e186))  |   |   |   |   |
| [debug-service.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-service.md)  | Yes ([debug-service.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug/debug-application/debug-service.md))  |   | Yes  | #33372  |   |
| [debug-stateful-set.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/debug-stateful-set.md)  | No, so moving is needed <br> ([to debug-statefulset.md](https://github.com/kubernetes/website/pull/32823/files#diff-45fc446f23600c022a6ad7de2aa7c7eb0c250ebf46c17d608bfa2abf797e91bf))  |   |   |   |   |
| [determine-reason-pod-failure.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/determine-reason-pod-failure.md)  | No, so moving is needed  |   |   |   |   |
| [get-shell-running-container.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/get-shell-running-container.md)  | Yes ([get-shell-running-container.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug/debug-application/get-shell-running-container.md))  |   | Yes  | #33372  |   |
| [resource-usage-monitoring.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/resource-usage-monitoring.md)  |   | No, so moving is needed  |   | #33372  |   |
| [troubleshooting.md](https://github.com/kubernetes/website/blob/main/content/zh/docs/tasks/debug-application-cluster/troubleshooting.md)  |   |   |   |   |   |
|   |   |   |   |   |   |
|   |   |   |   |   |   |
|   |   |   |   |   |   |
|   |   |   |   |   |   |
|   |   |   |   |   |   |

**Page to Update:**
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/audit/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/crictl/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-application-introspection/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-application/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-cluster/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-init-containers/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-pod-replication-controller/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-running-pod/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-service/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-stateful-set/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/determine-reason-pod-failure/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/get-shell-running-container/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/resource-usage-monitoring/
- https://kubernetes.io/zh/docs/tasks/debug-application-cluster/troubleshooting/

And please also refer to: 
- #33220 
  (en PR that updates all the links to the task "Monitoring, Logging, and Debugging" on all pages)
- #33407
  (zh PR that adds https://k8s.io/zh/docs/tasks/debug/ ([Preview](https://deploy-preview-33407--kubernetes-io-main-staging.netlify.app/zh/docs/tasks/debug/)))

/language zh

**Comment by jihoon-seo** [comment]
Oh, now I found the PR #33372 that syncs `docs/tasks/debug`.

**Comment by tengqm** [comment]
Looks like this can be closed? @jihoon-seo

**Comment by jihoon-seo** [comment]
@tengqm Okay, let's close this.
