### ISSUE TITLE
Banner text color wrong for https://k8s.io/partners/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33426]
**This is a Bug Report**

**Problem:**
When a banner is shown and the banner does not specify a text color, https://kubernetes.io/partners/ is shown with black (not white) text.

**Proposed Solution:**
Fix the stylesheet (this requires investigation).
Make sure not to introduce any regression.

Changes to add CSS directly into the HTML, or to modify the banner data would not be the right fix.

**Page to fix:**
https://kubernetes.io/partners/

**Additional Information:**
/area web-development

**Comment by manavsiddharthgupta** [comment]
Hi @sftim , I would love to take this issue.

**Comment by sftim** [comment]
/triage accepted

PRs welcome!

**Comment by gullapalli9482** [comment]
Can I also work on this alongside or take it up if it is not assigned to anyone.

**Comment by sftim** [comment]
You can only see the symptoms when an announcement banner is showing. See https://github.com/kubernetes/website/blob/main/data/announcements/scheduled.yaml - if you edit this locally, and preview locally, you can see the symptoms.

**Comment by a-mccarthy** [comment]
@kadtendulkar a banner for kubecon na just went live. If you are still willing to work on this issue, you should be able to see the incorrect banner text color more easily,  https://kubernetes.io/partners/

**Comment by dipesh-rawat** [comment]
I see this has been pending for a long time. I'm happy to move this forward.

/assign
