### ISSUE TITLE
Installing kubeadm - confusing/misleading text

### ISSUE THREAD

**Issue by Ileriayo** [kubernetes/website#33468]
Under the [Check required ports section](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports), this following statement is misleading because nothing about pod network plugin was discussed on that page:

```
The pod network plugin you use (see below) may also require certain ports to be open. Since this differs with each pod network plugin, please see the documentation for the plugins about what port(s) those need.
```

The text in parenthesis `(see below)` should be taken out to avoid confusion.

**Comment by neolit123** [comment]
> The text in parenthesis (see below) should be taken out to avoid confusion.

I think it makes sense to remove the text.

/help
/sig cluster-lifecycle

**Comment by sftim** [comment]
/language en
/kind bug
/priority backlog


Anyone is welcome to open a PR that omits the text “(see below)”.

**Comment by Ileriayo** [comment]
I'll open a PR for it.
