### ISSUE TITLE
Network Plugins

### ISSUE THREAD

**Issue by marcusbooyah** [kubernetes/website#33466]
The instructions on [this page](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#usage-summary) are no longer valid. The `--network-plugin` option has been removed from kubelet.

**Comment by sftim** [comment]
Hi @marcusbooyah 

Which web page isn't right? Can you let us know the URL?

/language en
/triage needs-information

**Comment by marcusbooyah** [comment]
Sorry - I fixed the link in the description above.

**Comment by sftim** [comment]
/remove-triage needs-information
/sig node

The issue is fixed
/triage accepted
/kind bug
/close

**Comment by sftim** [comment]
/retitle Network Plugins page lists obsolete kubelet command line argument
