### ISSUE TITLE
404 on pages returned as search results (from inside 2 sections) of kubernetes.io/docs 

### ISSUE THREAD

**Issue by cg-cri-gl** [kubernetes/website#33464]
**This is a Bug Report**

**Problem**
The search after 'audit' on kubernetes.io/docs site returns wrong URLs. This first search result goes into a 404. 

This is not the only issue. The whole subsection actually "debug-application-cluster" from inside "https://kubernetes.io/docs/tasks/debug-application-cluster" 
 has been split into 2 section it seems , but the search engine result shows obsolete results, and the returned URLs simply 404

**Proposed Solution:**
https://kubernetes.io/docs/tasks/debug-application-cluster -> https://kubernetes.io/docs/tasks/**debug**/debug-cluster
https://kubernetes.io/docs/tasks/debug-application-cluster -> https://kubernetes.io/docs/tasks/**debug**/debug-application 

so, my search result should have been presented as: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/  instead of https://kubernetes.io/docs/tasks/debug-application-cluster/audit/ 

**Page to Update:**
search engine index

**Comment by ashish-jaiswar** [comment]
Hi @sftim can I work on this issue?

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #33220.
And I confirm that in `content/en/`, there exists no link that points to `debug-application-cluster/**.md`.
/close
