### ISSUE TITLE
[zh][Umbrella] Contribution docs to sync for 1.24

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#33474]
This is an umbrella issue for contribution docs that are out of sync for `zh` localization. The difference is captured on 2022-05-05, so the list may become outdated soon. Please do run the `scripts/lsync.sh` again before working on any issue.

/help

- [x] contribution-1   @windsonsea   https://github.com/kubernetes/website/pull/33616
```
2	2	content/en/docs/contribute/participate/roles-and-responsibilities.md
22	1	content/en/docs/contribute/participate/pr-wranglers.md
**removed**	content/en/docs//contribute/new-content/overview.md
116	0	content/en/docs/contribute/new-content/_index.md
```

- [x] contribution-2  @windsonsea  #33648
```
38	0	content/en/docs/contribute/new-content/blogs-case-studies.md
94	6	content/en/docs/contribute/new-content/open-a-pr.md
```

- [x] contribution-3 @windsonsea  #33677
```
37	2	content/en/docs/contribute/review/reviewing-prs.md
89	4	content/en/docs/contribute/_index.md
```

**Comment by windsonsea** [comment]
`/triage accepted`

**Comment by windsonsea** [comment]
I need check those 8 md files line by line. If any inconsistency between en and cn, I need change them, correct?

**Comment by windsonsea** [comment]
I'm starting to check this md. Hope this file can be completed by the next eod.
![roles](https://user-images.githubusercontent.com/79828097/167837029-a5e27bab-8f48-475d-a282-1cd20af521e1.png)

**Comment by tengqm** [comment]
@windsonsea You may find the `scripts/lsync.sh` tool useful. For example, run the following command on the **main** branch:

```shell
./scripts/lsync.sh content/zh/docs/contribute/participate/roles-and-responsibilities.md
```

It will show you the changes to the upstream English source since the last time that page was sync'ed (or translated).
Basically, those changes are the lines we need to resync to Chinese.

**Comment by tengqm** [comment]
@windsonsea Maybe you can start by working on the first item?

**Comment by windsonsea** [comment]
> ```shell
> ./scripts/lsync.sh content/zh/docs/contribute/participate/roles-and-responsibilities.md
> ```

hmmm, I runned this command on the ***main*** branch in VScode but nothing happened -_!  Could you join a WeMeet like [room no: 323-315-205](https://meeting.tencent.com/dm/3K4IgE7e6pi6)

**Comment by tengqm** [comment]
```shell
$ ./scripts/lsync.sh content/zh/docs/contribute/participate/roles-and-responsibilities.md
diff --git a/content/en/docs/contribute/participate/roles-and-responsibilities.md b/content/en/docs/contribute/participate/roles-and-responsibilities.md
index e59ffe4fe3..c577c3f8be 100644
--- a/content/en/docs/contribute/participate/roles-and-responsibilities.md
+++ b/content/en/docs/contribute/participate/roles-and-responsibilities.md
@@ -147,7 +147,7 @@ separately for reviewer status in SIG Docs.
 To apply:
 
 1. Open a pull request that adds your GitHub user name to a section of the
-   [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS) file
+   [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES) file
    in the `kubernetes/website` repository.
 
    {{< note >}}
@@ -219,7 +219,7 @@ separately for approver status in SIG Docs.
 To apply:
 
 1. Open a pull request adding yourself to a section of the
-   [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS)
+   [OWNERS_ALIASES](https://github.com/kubernetes/website/blob/main/OWNERS_ALIASES)
    file in the `kubernetes/website` repository.
 
     {{< note >}}
```

**Comment by windsonsea** [comment]
One question: How can I assign my PR to you? My PR comment is like:
```
Accepted a task https://github.com/kubernetes/website/issues/33474 to check zh text from @[tengqm](https://github.com/tengqm). This is the first md file in the list. I'm not familiar with using the scripts/lsync.sh, so perform a proofreading word by word. Most changes are for context consistency. Hope the reader can read a same word in a page instead of confusing with why those words are different, such as a link name PR 管理者 before/after a click. /assign @tengqm
```

**Comment by windsonsea** [comment]
contribution-1 is completed and a PR is opened right now. I will continue to handle contribution-2 and -3.

**Comment by tengqm** [comment]
> contribution-1 is completed and a PR is opened right now. I will continue to handle contribution-2 and -3.

Assigned.

**Comment by windsonsea** [comment]
Up to now, those files of contribution-1 and -2 are completed and merged, and contribution-3 is submitted in PR#33677 for your review. If you need any more support, just message me :)

**Comment by tengqm** [comment]
@windsonsea We usually do not assign tasks to contributors. We hope out contributors are signing on issues voluntarily. There are a few umbrella issues like [#33474](https://github.com/kubernetes/website/issues/33474), [#33475](https://github.com/kubernetes/website/issues/33475), [#33476](https://github.com/kubernetes/website/issues/33476), [#33477](https://github.com/kubernetes/website/issues/33477), [#33478](https://github.com/kubernetes/website/issues/33478), [#33479](https://github.com/kubernetes/website/issues/33479). These are filed for a bigger effort after the v1.24 release. There are other localization issues to be closed. You can find them by filtering the issues by the `language/zh` tag.

**Comment by tengqm** [comment]
This issue is done.
/close
