### ISSUE TITLE
[zh][Umbrella] Setup docs to sync for 1.24

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#33475]
This is an umbrella issue for setup docs that are out of sync for `zh` localization. The difference is captured on 2022-05-05, so the list may become outdated soon. Please do run the `scripts/lsync.sh` again before working on any issue.

/help

- [x] setup-1   @zaunist #33634
```
6	18	content/en/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
35	27	content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
40	19	content/en/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
```

- [x] setup-2   @zaunist  #33670
```
83	25	content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
12	13	content/en/docs/setup/production-environment/tools/kubeadm/kubelet-integration.md
51	5	content/en/docs/setup/best-practices/certificates.md
```

- [x] setup-3  @wlp1153468871 #33555 #33981
```
0	2	content/en/docs/setup/best-practices/node-conformance.md
110	290	content/en/docs/setup/production-environment/container-runtimes.md
```

- [x] setup-4 (not urgent, refactoring underway)
```
10	3	content/en/docs/setup/production-environment/windows/user-guide-windows-containers.md
716	1134	content/en/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
```

**Comment by wlp1153468871** [comment]
I want to work on setup-3
/assign

**Comment by windsonsea** [comment]
setup-4 is such a big task. do you need my help?
/assign

**Comment by tengqm** [comment]
@windsonsea setup-4 is big and it is not urgent because the English upstream is undergoing a heavy change, see #33582.

**Comment by windsonsea** [comment]
> @windsonsea setup-4 is big and it is not urgent because the English upstream is undergoing a heavy change, see #33582.

Understood. Wait for #33582 to be merged before this localization task of setup-4.

**Comment by tengqm** [comment]
Setup-4 has been manually marked as 'completed' due to large refactoring occurred in upstream. The Windows pages are now captured in a separate issue.
