### ISSUE TITLE
[zh][Umbrella] Reference pages to sync for 1.24

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#33478]
This is an umbrella issue for reference docs that are out of sync for `zh` localization. The difference is captured on 2022-05-05, so the list may become outdated soon. Please do run the `scripts/lsync.sh` again before working on any issue.

**Note** this issue does NOT cover the kubeadm reference docs.

/help

- [x] reference-1  @nameYULI   #33546
```
1	1	content/en/docs/reference/kubernetes-api/common-parameters/common-parameters.md
1	3	content/en/docs/reference/kubernetes-api/common-definitions/list-meta.md
7	7	content/en/docs/reference/kubernetes-api/common-definitions/object-meta.md
96	0	content/en/docs/reference/labels-annotations-taints/_index.md
```

- [x] reference-2  @nameYULI   #33550
```
35	0	content/en/docs/reference/labels-annotations-taints/audit-annotations.md
1	7	content/en/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
32	9	content/en/docs/reference/tools/_index.md
```

- [x] reference-3  @nameYULI   #33553
```
557	738	content/en/docs/reference/config-api/kubeadm-config.v1beta3.md
```

- [x] reference-4  @nameYULI   #33513 
```
151	244	content/en/docs/reference/config-api/apiserver-audit.v1.md
```

- [x] reference-5   @nameYULI   #33569
```
780	912	content/en/docs/reference/config-api/kube-scheduler-config.v1beta3.md
```

- [x] reference-6  @nameYULI   #33575
```
771	909	content/en/docs/reference/config-api/kube-scheduler-config.v1beta2.md
```

- [x] reference-7  @nameYULI   #33599
```
524	705	content/en/docs/reference/config-api/kubeadm-config.v1beta2.md
```

- [x] reference-8  @nameYULI  #33610
```
286	337	content/en/docs/reference/config-api/kube-proxy-config.v1alpha1.md
```

- [x] reference-9   @nameYULI
  **NOTE**: The `kube-controller-manager.md` file was partially changed in PR #33583 and the PR was merged prematurely. When checking this file, please checkout commit 5bfab64cc7774180d22f22838c9976696958a417 before performing a `./script/lsync.sh`.

  #33747
  #33776
```
12	96	content/en/docs/reference/command-line-tools-reference/kube-apiserver.md
13	97	content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md
30	100	content/en/docs/reference/command-line-tools-reference/kube-proxy.md
7	7	content/en/docs/reference/using-api/deprecation-guide.md
1	0	content/en/docs/reference/using-api/_index.md
```

- [x] reference-10  @nameYULI   #33797
```
145	76	content/en/docs/reference/command-line-tools-reference/feature-gates.md
```

- [x] reference-11 @zyy19981018     #33510  #33802
```
10	150	content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
30	19	content/en/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md
**removed**	content/en/docs//reference/kubectl/overview.md
```

- [x] reference-12  @nameYULI  #33827
```
10	0	content/en/docs/reference/kubectl/conventions.md
56	22	content/en/docs/reference/kubectl/cheatsheet.md
22	22	content/en/docs/reference/access-authn-authz/admission-controllers.md
```

- [x] reference-13   @nameYULI   #33841
```
552	1	content/en/docs/reference/kubectl/_index.md
```

- [x] reference-14  @nameYULI #33283  #33842  #33872
```
580	165	content/en/docs/reference/using-api/api-concepts.md
```

- [x] reference-15  @nameYULI  #33853
```
165	306	content/en/docs/reference/config-api/kubelet-config.v1beta1.md
```

- [x] reference-16  @nameYULI  #33855
```
85	85	content/en/docs/reference/config-api/kubelet-config.v1alpha1.md
```

**Comment by nameYULI** [comment]
I want to work on parts 1~8.
/assign

**Comment by nameYULI** [comment]
I want to work on parts 9~16.
/assign

**Comment by tengqm** [comment]
Special thanks to @nameYULI. 
We can close this one now.
/close
