### ISSUE TITLE
Document `PodAndContainerStatsFromCRI` feature gate / implications

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33509]
**This is a Bug Report**

**Problem:** The feature gate `PodAndContainerStatsFromCRI` amends node behavior around cAdvisor, but is not properly documented.

**Proposed Solution:**
Update https://kubernetes.io/docs/reference/node/ to ~include~ hyperlink to a new page about the changes from https://github.com/kubernetes/enhancements/issues/2371

For example, add a new page into https://kubernetes.io/docs/reference/instrumentation/

Ideally, write those docs to be finished before the feature moves the beta, so that the only change needed for graduation there is to mark the feature as being stable.

**Additional Information:**
/sig node
/language en

**Comment by sftim** [comment]
Aim to title and frame the new reference page as describing the situation after the enhancement is complete. For example, the title could be “Metrics About Containers And Pods” rather than “Migration from cAdvisor”.

**Comment by haircommander** [comment]
/assign

yeah I agree this is good criteria for beta. This kep having missed an alpha update in 1.25, it's not clear to me which release it will arrive in

**Comment by sftim** [comment]
We can document this at any time. We should push back on graduation to _stable_ if there's not been any movement on documenting the changes. It's definitely better to have good docs ready to accompany actual graduation to beta, and it's nice to have at least some docs as soon as a feature goes alpha.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/pull/37962

**Comment by sftim** [comment]
PR #30535 helps with this.

**Comment by krol3** [comment]
This issue is related to this [KEP](https://github.com/kubernetes/enhancements/issues/2371)

**Comment by sftim** [comment]
PR https://github.com/kubernetes/website/pull/37980 helps with this too.

**Comment by sftim** [comment]
/retitle Document `PodAndContainerStatsFromCRI` feature gate / implications
