### ISSUE TITLE
Translate reference/kubernetes-api/authorization-resources/subject-access-review-v1.md

### ISSUE THREAD

**Issue by shixiuguo** [kubernetes/website#33518]
**This is a Feature Request**

Hi, I'm interested to translate the "reference/kubernetes-api/authorization-resources/subject-access-review-v1.md" page.

translate en/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1.md into Chinese.

What would you like to be added:

zh/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1.md

/language zh

**Comment by howieyuen** [comment]
this task has been done here https://github.com/kubernetes/website/pull/34034, close it now
/close
