### ISSUE TITLE
Remove docs for Service Catalog integration

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33532]
**This is a removal request**

**What would you like to be added**
- Find the service catalog docs
  - https://k8s.io/search might be helpful
- Remove them (no forwarding address)

Also edit any pages on this site that previously linked there.

Make this change either to the _main_ branch, or to the branch for the upcoming Kubernetes release, whichever seems more appropriate.

**Why is this needed**
https://github.com/kubernetes/community/pull/6632

**Comments**
/sig service-catalog
/language en
/priority backlog
/lifecycle frozen
/triage accepted

**Comment by NitishKumar06** [comment]
Hi @sftim , Do you want to completely remove the context on the above page? https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/

**Comment by sftim** [comment]
We should find **all** the documentation that is for Service Catalog, and remove **all** of it. That removal would include deleting the page https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/

We might also want to edit the docs for earlier Kubernetes releases to add an explanatory note, because people will sometimes find those pages from a web search etc. However, the key task to fulfil _this_ issue is to delete the existing documentation for Service Catalog.

**Comment by jihoon-seo** [comment]
The PR #34387 closes this.
/assign @Rishit-dagli

**Comment by jihoon-seo** [comment]
Resolved by #34387.
/close
