### ISSUE TITLE
Install Service Catalog using Helm

### ISSUE THREAD

**Issue by karimib** [kubernetes/website#33533]
When trying to add the service catalog via helm the following error occurs.
Seems like the dcoumented URL at https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/ is not valid anymore ?

$ helm repo add svc-cat https://kubernetes-sigs.github.io/service-catalog
Error: looks like "https://kubernetes-sigs.github.io/service-catalog" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-sigs.github.io/service-catalog/index.yaml : 404 Not Found

**Comment by downtheroad77** [comment]
Look for the same to be added back - https://kubernetes-sigs.github.io/service-catalog/index.yaml

**Comment by davinder2385** [comment]
I am also facing the same issue.

**Comment by bhaumikovshek** [comment]
I couldn't find a resolution for this yet! Does anyone have any updates?

**Comment by mk46** [comment]
The service catalog will remove soon as per https://github.com/kubernetes/website/issues/33532. I don't think working on this, will be worthy

**Comment by karimib** [comment]
We use https://charts.drycc.cc/stable as an alternative

**Comment by jihoon-seo** [comment]
The PR #34387 closes this.
/assign @Rishit-dagli

**Comment by jihoon-seo** [comment]
The Service Catalog references are removed by the PR #34387.
/close
