### ISSUE TITLE
Improvement for k8s.io/releases/notes/

### ISSUE THREAD

**Issue by madhavisl** [kubernetes/website#33534]
Release Notes for each Release needs to be upfront visible to the users

**Comment by sftim** [comment]
How should we make these notes more visible? What other pages - perhaps even https://k8s.io/ - need to change?

/remove-lifecycle rotten
/triage needs-information

**Comment by divya-mohan0209** [comment]
@madhavisl : Please could you advise? @sftim has left a comment above.

**Comment by Shubham82** [comment]
@madhavisl your thoughts on @sftim above comment

**Comment by sftim** [comment]
With no follow up from you @madhavisl, I'll close this. You are welcome to reopen the issue to add more details.

/close
