### ISSUE TITLE
change nginx version from 11.14.2 to 1.14.2 in concepts/services-networking/service.md

### ISSUE THREAD

**Issue by mxfactorial** [kubernetes/website#33539]
**This is a Bug Report**

**Problem:**

https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/services-networking/service.md?plain=1#L125 displays `11.14.2` nginx version despite unavailability in [docker hub](https://hub.docker.com/_/nginx?tab=tags) and [repo](http://hg.nginx.org/nginx/tags)

**Proposed Solution:**

change to `1.14.2` nginx version

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by sftim** [comment]
Another possible fix: use an example image name, and make it clear that the manifest is an example.

/language en

**Comment by Shivansh-yadav13** [comment]
@mxfactorial @sftim can I fix it?
