### ISSUE TITLE
使用 kubeadm 创建集群

### ISSUE THREAD

**Issue by freeysw** [kubernetes/website#33537]
![image](https://user-images.githubusercontent.com/26788279/167233469-7f0893ad-030a-4b47-a180-5f321c0ffab3.png)
![image](https://user-images.githubusercontent.com/26788279/167233477-32d69b6e-49f1-48b5-92bb-b5a25327bdce.png)

**Comment by jihoon-seo** [comment]
/language zh
Page: https://kubernetes.io/zh/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#控制平面节点隔离

For me, I cannot find that English part.

**Comment by seokho-son** [comment]
Hi @freeysw

Please change the title in English.
We are sharing the repository and folks cannot easily understand purpose of this issue if you use your language in the title. (not all contents need to be in English, but at least the title)

**Comment by javadoors** [comment]
@jihoon-seo the English part link is: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation

**Comment by Abirdcfly** [comment]
Inconsistency between the Chinese translation and the original English content will be fixed by https://github.com/kubernetes/website/issues/33475 setup-2 @zaunist

**Comment by Abirdcfly** [comment]
https://github.com/kubernetes/website/pull/33670 has been merged.

/close
