### ISSUE TITLE
Issue with k8s.io/fr/docs/tutorials/kubernetes-basics/expose/

### ISSUE THREAD

**Issue by zouhirhanafi** [kubernetes/website#33543]
Empty page

**Comment by jihoon-seo** [comment]
/language fr
It seems that after someone adds the French version of either
- https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/
- https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

then that page would have the link to the added pages.
