### ISSUE TITLE
Translate a Docker Compose File to Kubernetes Resources - Command Typo / Change

### ISSUE THREAD

**Issue by princefishthrower** [kubernetes/website#33548]
From this page: https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

Small change requested: I notice that after I run 

```shell
kompose convert
```

I don't get a `frontend-service.yaml` but rather a `frontend-tcp-service.yaml`.

So the line:

```
kubectl apply -f frontend-service.yaml,redis-master-service.yaml,redis-slave-service.yaml,frontend-deployment.yaml,redis-master-deployment.yaml,redis-slave-deployment.yaml
```

Should be changed to:

```
kubectl apply -f frontend-tcp-service.yaml,redis-master-service.yaml,redis-slave-service.yaml,frontend-deployment.yaml,redis-master-deployment.yaml,redis-slave-deployment.yaml
```

I'm on macOS, not sure if that has an impact.

**Comment by princefishthrower** [comment]
Actually this then follows to further commands. It should instead of:

```shell
minikube service frontend
```

Should be: 

```
minikube service frontend-tcp
```

Really, the culprit or source of the bug would be to find where the `-tcp` is coming from. It's not present anywhere in the original `docker-compose.yml` file, but `kompose convert` puts it in there for some reason...

**Comment by princefishthrower** [comment]
Hah, even after running the proper `service` command, there is apparently a recent regression with port mapping as described here: https://github.com/kubernetes/minikube/issues/13736#issuecomment-1063470210

I found this comment useful as a fix: https://github.com/kubernetes/minikube/issues/14097#issuecomment-1117622322

In summary, you just forward the port manually by issuing:

```shell
kubectl port-forward service/frontend-tcp 8080:80
```

**Comment by taniaduggal** [comment]
Is this a pr to work on ? @princefishthrower
