### ISSUE TITLE
Query about using a single PodDisruptionBudget and multiple StatefulSets

### ISSUE THREAD

**Issue by aeimer** [kubernetes/website#33571]
Hi Guys,

I cant find it in the docs here, is it possible to have three StatefulSets with one PDB over all the STS.

Our setup has three STS:
- `stateful-app-0`
- `stateful-app-1`
- `stateful-app-2`

Which is scaled to 1 each, so there are three pods:
- `stateful-app-0-0`
- `stateful-app-1-0`
- `stateful-app-2-0`

We set the labels on the sts:
```
app.kubernetes.io/instance=stateful-app
app.kubernetes.io/name=stateful-app
id.ourname.com/instance-id=stateful-app-{ID_OF_STS => 0,1,2}
```

We have a PDB with:
```
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance=stateful-app
      app.kubernetes.io/name=stateful-app
```

So we see in k9s and lens that the PDB has 3 running pods, but when we trigger a change on the STS, all three pods are restarted the same time. How is this possible?

BR
Alex

**Comment by sftim** [comment]
/kind support
/retitle Query about using a single PodDisruptionBudget and multiple StatefulSets

**Comment by sftim** [comment]
@aeimer thanks for the nudge

GitHub is not the right place for support requests.

If you're looking for help, try asking on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
