### ISSUE TITLE
在 Windows 上安装 kubectl

### ISSUE THREAD

**Issue by fine-wind** [kubernetes/website#33606]
你需要一个 [kubeconfig 文件](https://kubernetes.io/docs/zh/concepts/configuration/organize-cluster-access-kubeconfig/)
此地址文件 404

**Comment by jihoon-seo** [comment]
The right URL is https://kubernetes.io/zh/docs/concepts/configuration/organize-cluster-access-kubeconfig/ .

**Comment by jihoon-seo** [comment]
In https://kubernetes.io/zh/docs/tasks/tools/install-kubectl-windows/#verify-kubectl-configration ,
[the link](https://kubernetes.io/zh/docs/tasks/tools/install-kubectl-windows/#:~:text=你需要一个-,kubeconfig%20文件,-，%20该文件在) is wrong.

[Suggested solution]
Update the link to point https://kubernetes.io/zh/docs/concepts/configuration/organize-cluster-access-kubeconfig/ .

/triage accepted
/kind bug
/language zh

**Comment by seokho-son** [comment]
Hi @fine-wind 
Please change the title in English. 
We are sharing the repository and folks cannot easily understand purpose of this issue if you use your language in the title.

**Comment by fine-wind** [comment]
ok, thanks
