### ISSUE TITLE
Troubleshooting kubeadm - invalid link

### ISSUE THREAD

**Issue by weaselchops** [kubernetes/website#33601]
The section: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubeadm-blocks-when-removing-managed-containers

The link to "Debugging Kubernetes nodes with crictl" (https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/)  is a 404

=== Original ===
A possible solution is to restart the container runtime and then re-run kubeadm reset. You can also use crictl to debug the state of the container runtime. See [Debugging Kubernetes nodes with crictl](https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/).

**Comment by neolit123** [comment]
we can change the link to `/docs/tasks/debug)/debug-cluster/crictl`

/help
/sig cluster-lifecycle

**Comment by Shubham82** [comment]
Hi @weaselchops @neolit123
It is working now.
reloved in this PR: #33314

**Comment by neolit123** [comment]
Thanks for the PR
/close
