### ISSUE TITLE
Document how to change pause image in CR page

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#33613]
This is a frequent problem. In airgapped environments  (e.g. behind firewall without GCR access) the container runtime continues to hardcode a pause / sandbox image in its config. So even if kubeadm or other installers say "you need somerepo/pause:3.7" the CR has "k8s.gcr.io/pause:3.1". This drift in pause image config is a CRI problem. Installers could wrap / manage CR config but that is maintenance complexity.

What we can do is:
- In https://kubernetes.io/docs/setup/production-environment/container-runtimes/ add steps to set  pause image in configs for all CRs
- In the "kubeadm init" page / section about custom images add notes that users must explicitly update the pause image in the CR config if using a custom image repo.

Xref
https://github.com/kubernetes/kubernetes/issues/109960

**Comment by neolit123** [comment]
/help
In case someone wants to take this.

**Comment by sftim** [comment]
/triage accepted

Per https://github.com/kubernetes/website/pull/33660#discussion_r882633285:
> are there any container runtimes that work properly with Kubernetes and that don't use a pause image at all?
