### ISSUE TITLE
为命名空间配置默认的 CPU 请求和限制

### ISSUE THREAD

**Issue by RaYong8080** [kubernetes/website#33612]
The name of the deleted namespace does not match the name of the namespace that you created

https://kubernetes.io/zh/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/

**Comment by seokho-son** [comment]
Hi @RaYong8080

Please change the title in English. 
We are sharing the repository and folks cannot easily understand purpose of this issue if you use your language in the tit

**Comment by tengqm** [comment]
This issue has been fixed.
/close
