### ISSUE TITLE
kubeadm init/join pre-flight checks stopping a 1.24 cluster installation with containerd

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#33628]
I just fresh installed a k8s 1.24 cluster with containerd as runtime engine, using latest kubeadm tooling and following step by step the installation procedure described in latest (1.24) k8s documentation; I experienced the problem reported in [kubeadm issue #1062](https://github.com/kubernetes/kubeadm/issues/1062) when raising ``kubeadm init`` and ``kubeadm join`` commands.
I solved the problem invoking (in master and worker nodes) the commands described at the beginning of that issue:

``modprobe br_netfilter``
``echo '1' > /proc/sys/net/ipv4/ip_forward``

After this, ``kubeadm init/join`` commands do their work perfectly ;-)

As we wait for this to be solved in kubeadm (automatically raising these commands when using a runtime engine different than docker) I think it would be good to document this in kubeadm-based installation pages.
(maybe also applicable for CRI-O ?)

P.S: It was an installation on Ubuntu-based Virtualbox VMs on a Windows10 host OS where Hyper-V has been fully disabled, so experienced issue is not related to any Hyper-V collision (not in my case).

**Comment by neolit123** [comment]
These are not only for docker. Please see https://kubernetes.io/docs/setup/production-environment/container-runtimes/#install-and-configure-prerequisites

This section was added recently due to user confusion.

/close

**Comment by antaloala** [comment]
Ops .. it looks I did not follow all the required steps as previously said:-(
Thanks a lot @neolit123 .. and sorry for not realizing on this before raising this issue :-(
