### ISSUE TITLE
Network Plugins: --network-plugin flag is missing in 1.24.0, yet documented as available

### ISSUE THREAD

**Issue by netikras** [kubernetes/website#33640]
![image](https://user-images.githubusercontent.com/2045031/168163445-965acb28-7eb8-473b-a760-f772d37dbb53.png)
ref: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

```
[root@CentOS-83-64-minimal ~]# kubelet --version
Kubernetes v1.20.4
[root@CentOS-83-64-minimal ~]# kubelet --help | grep network-plugin
      --network-plugin string                                    The name of the network plugin to be invoked for various events in kubelet/pod lifecycle. This docker-specific flag only works when container-runtime is set to docker.
      --network-plugin-mtu int32                                 The MTU to be passed to the network plugin, to override the default. Set to 0 to use the default 1460 MTU. This docker-specific flag only works when container-runtime is set to docker.
[root@CentOS-83-64-minimal ~]# 
```

```
root@netikras-hub:/etc/systemd/system/kubelet.service.d# kubelet --version
Kubernetes v1.24.0
root@netikras-hub:/etc/systemd/system/kubelet.service.d# kubelet --help | grep network-plugin
root@netikras-hub:/etc/systemd/system/kubelet.service.d# 
root@netikras-hub:/etc/systemd/system/kubelet.service.d# kubelet --network-plugin=cni 2>&1 | head -3
Error: failed to parse kubelet flag: unknown flag: --network-plugin
Usage:
  kubelet [flags]
root@netikras-hub:/etc/systemd/system/kubelet.service.d# 
```

**Comment by mk46** [comment]
/sig node
/kind cleanup
If any flag found which was removed in https://github.com/kubernetes/kubernetes/pull/106907, Kindly remove them too.

**Comment by agelosnm** [comment]
For anyone facing this issue and Kubernetes is not starting, I removed the `--network-plugin` flag from `/var/lib/kubelet/kubeadm-flags.env `file and restarted kubelet service. (`systemctl restart kubelet`).

**Comment by KatsuoRyuu** [comment]
I have run into the same problem and removing it from `/var/lib/kubelet/kubeadm-flags.env` does not work.
Basically this breaks the system

**Comment by mk46** [comment]
Hi @KatsuoRyuu @agelosnm, Seems like you are using `kubelet < 1.24`. If not ,kindly share kubelet version and log.
Thanks !!

**Comment by KatsuoRyuu** [comment]
The version i used was 1.24.0 from the debian repo, downgrading to 1.23.6 solved my issue and got everything running again

**Comment by mk46** [comment]
How you have bootstrapped the cluster? Using kubeadm or different tools

**Comment by agelosnm** [comment]
@mk46 I was using 1.23 and I came up with this issue upon performing updates to the nodes of the cluster (apt-get upgrade). Then, 1.24 was installed and the issue came up and I managed to resolve it as I mentioned above as the logs of the kubelet service were indicating error with the --network-plugin flag.

**Comment by mk46** [comment]
> @mk46 I was using 1.23 and I came up with this issue upon performing updates to the nodes of the cluster (apt-get upgrade). Then, 1.24 was installed and the issue came up and I managed to resolve it as I mentioned above as the logs of the kubelet service were indicating error with the --network-plugin flag.

Behaviour is expected. since remove in v1.24
Please share `/var/lib/kubelet/kubeadm-flags.env` and the output of `journalctl -b -u kubelet`?

**Comment by sftim** [comment]
Folks, this is an accepted issue. We should update that page to remove mentions of the `--network-plugin` command line argument.

Pull requests are welcome - see https://kubernetes.io/docs/contribute/ for tips on how to contribute.

**Comment by colindawson** [comment]
my cluster is down after doing an apt upgrade.   From what I can understand it looks like I have this issue, running version 1.24.0 as well.     Is here any instructions on how to downgrade my cluster so that I can get it up and running again?

**Comment by davidkarlsen** [comment]
> my cluster is down after doing an apt upgrade. From what I can understand it looks like I have this issue, running version 1.24.0 as well. Is here any instructions on how to downgrade my cluster so that I can get it up and running again?
@colindawson 
I got mine up by simply downgrading the kubelet to latest 1.23.x

**Comment by sftim** [comment]
If anyone has questions about how to propose a fix for https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/, you're very welcome to ask. You can reply here or, if you use the Kubernetes workspace for Slack, ask there in the `#sig-docs` channel.

**Comment by netikras** [comment]
I've created a SO page to redirect all the "how to fix my cluster now" questions there: https://stackoverflow.com/questions/72316016/after-upgrading-to-kubelet-v1-24-clusted-does-not-start . Should I update the OP to reflect this link and state that this is not a request to fix the cluster's setup? @sftim

**Comment by sftim** [comment]
Duplicated by issue #33862

**Comment by sftim** [comment]
We should edit https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ so that it is no longer incorrect, and then close this issue.

**Comment by sftim** [comment]
Anyone who wants to edit that page is welcome to.

**Comment by rolfedh** [comment]
@mikebrow is reviewing @tomkivlin's PR https://github.com/kubernetes/website/pull/33870

**Comment by duanhaowei** [comment]
remove " --network-plugin"flag  work fine.

**Comment by mperlik** [comment]
> For anyone facing this issue and Kubernetes is not starting, I removed the `--network-plugin` flag from `/var/lib/kubelet/kubeadm-flags.env `file and restarted kubelet service. (`systemctl restart kubelet`).

This resulted in my case just in another error:
```Jun 19 09:15:47 k8s-1m kubelet[1752935]: I0619 09:15:47.043427 1752935 util_unix.go:104] "Using this format as endpoint is deprecated, please consider using full url format." deprecatedFormat="" fullURLFormat="unix://"
Jun 19 09:15:47 k8s-1m kubelet[1752935]: W0619 09:15:47.044045 1752935 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix: missing address". Reconnecting...
Jun 19 09:15:47 k8s-1m kubelet[1752935]: Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix: missing address"
```

**Comment by BastienVigneron** [comment]
same error for me.

**Comment by Zappelphilipp** [comment]
same here.

**Comment by Zappelphilipp** [comment]
> > For anyone facing this issue and Kubernetes is not starting, I removed the `--network-plugin` flag from `/var/lib/kubelet/kubeadm-flags.env `file and restarted kubelet service. (`systemctl restart kubelet`).
> 
> This resulted in my case just in another error:
> 
> ```
> Jun 19 09:15:47 k8s-1m kubelet[1752935]: W0619 09:15:47.044045 1752935 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix: missing address". Reconnecting...
> Jun 19 09:15:47 k8s-1m kubelet[1752935]: Error: failed to run Kubelet: unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix: missing address"
> ```

same here

**Comment by sftim** [comment]
As this bug is resolved, I'm going to lock it to ensure that the record remains on-topic.
