### ISSUE TITLE
https://kubernetes.io/docs/concepts/cluster-administration/networking/#weave-net-from-weaveworks

### ISSUE THREAD

**Issue by SushilSanjayBhile** [kubernetes/website#33658]
[Weave Net](https://www.weave.works/oss/net/) is a resilient and simple to use the network for Kubernetes and its hosted applications. Weave Net runs as a [CNI plug-in](https://www.weave.works/docs/net/latest/cni-plugin/) or stand-alone. In either version, it doesn't require any configuration or extra code to run, and in both cases, the network provides one IP address per pod - as is standard for Kubernetes. The project has documentation for setting up a weave-net at [weave-net-kubernetes-integration](https://www.weave.works/blog/weave-net-kubernetes-integration/).

**Comment by SushilSanjayBhile** [comment]
It's challenging to find documentation to set up a weave network, the steps to install weave-net on Kubernetes are not available in k8s docs and on their website's manual page. It is available in blogs added by someone.

**Comment by sftim** [comment]
> It's challenging to find documentation to set up a weave network, the steps to install weave-net on Kubernetes are not available in k8s docs and on their website's manual page. It is available in blogs added by someone.

I'm not sure if that's your feedback on the docs here?
If I've guessed right @SushilSanjayBhile, you might prefer to file this at https://github.com/weaveworks/weave/issues/new

This website does not aim to provide detailed documentation for Weave Net.
