### ISSUE TITLE
kubectl generated command docs do not include 1.24 commands

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#33674]
**This is a Bug Report**

**Problem:**

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#create does not include commands added in 1.24 (notably `kubectl create token`)

It looks like https://github.com/kubernetes/website/tree/main/static/docs/reference/generated/kubectl is supposed to be auto-generated, but has not been updated for 1.24.

/sig cli

**Comment by sftim** [comment]
/priority important-soon

because of Docker mentions and the risk of confusion.
