### ISSUE TITLE
Fix up RBAC good practice guide

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33696]
**This is a cleanup request**

**Problem:**
https://github.com/kubernetes/website/pull/32812 merged with a few minor bits of feedback pending.

**Proposed Solution:** Update https://kubernetes.io/docs/concepts/security/rbac-good-practices/ to incorporate feedback from 
https://github.com/kubernetes/website/pull/32812#pullrequestreview-973237887

- write RoleBindings, not Role Bindings
- write ClusterRoleBindings, not Cluster Role Bindings
- fix the first hyperlink in [Minimize distribution of privileged tokens](https://kubernetes.io/docs/concepts/security/rbac-good-practices/#minimize-distribution-of-privileged-tokens)

##### _Optional extra work_

- Add a “what's next” section at the end of the page. See https://kubernetes.io/docs/reference/access-authn-authz/authorization/#what-s-next for an example.

**Page to Update:**
https://kubernetes.io/docs/concepts/security/rbac-good-practices/

**Additional Information:**
/language en
/sig security

**Comment by harshitasao** [comment]
Hi @sftim, I'm new to Kubernetes and was hoping to contribute to the project. Is it possible for me to work on this issue?

**Comment by sftim** [comment]
Anyone - and that absolutely includes you @harshitasao - is welcome to open a new pull request that fixes this issue.

If you'd like some hints, check out https://k8s.io/docs/contribute/new-content/ - or reply here with questions!

**Comment by harshitasao** [comment]
Thank you @sftim

**Comment by Shubham82** [comment]
Hi, @harshitasao are you working on this?

**Comment by harshitasao** [comment]
Hey @Shubham82,  yes I'm working on it.

**Comment by Babapool** [comment]
This issue is fixed by PR #33961 (which is merged). I think we can close this issue. Thanks.

/close
