### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/

### ISSUE THREAD

**Issue by waych** [kubernetes/website#33703]
As part of "Remove Docker Engine", this page should probably also tell the user that may want to clean up space was consumed by docker, e.g. `/var/lib/docker`.  Otherwise, potentially much space is left used but unmanaged on the node.

**Comment by sftim** [comment]
Sounds good.

We could link to https://docs.docker.com/engine/install/ubuntu/#uninstall-docker-engine and similar page fragments; if we do, we should caution people that Docker's advice has a risk of trampling on containerd.

Ideally, we provide just links to third party docs here.  However, neither Docker Engine nor containerd has docs for migrating from one thing to the other (let alone any Kubernetes-specific considerations). I'm happy to treat that as a valid exception from the usual [content guidelines](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed).
