### ISSUE TITLE
[zh] Updated the term "群集" to "集群"

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/website#33735]
see https://github.com/kubernetes/website/pull/33643#issuecomment-1125841238

在中文本地化中其他页面存在将“cluster” 翻译为“群集”的情况，
[术语对照表](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7)的建议是翻译为 “集群”，因此，需要修改此术语翻译。

因为涉及到的页面较多，同时需要同步文件，工作量较大，此 issue 用以追踪此更改。

由于 [zh -> zh-cn](https://github.com/kubernetes/website/issues/34221) 造成的文件迁移，同步时，我们需要运行下面的命令以检查上游变更情况。
```
git checkout 3d345b1816
```
ref https://github.com/kubernetes/website/issues/34221#issue-1267685875

涉及到的页面：

- [x] part1  https://github.com/kubernetes/website/pull/33708

```
# Pages that have been synchronized
content/zh/blog/_posts/2015-03-00-Welcome-To-Kubernetes-Blog.md
content/zh/blog/_posts/2016-07-00-Dashboard-Web-Interface-For-Kubernetes.md
content/zh/blog/_posts/2016-07-00-stateful-applications-in-containers-kubernetes.md
content/zh/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
content/zh/blog/_posts/2018-07-10-coredns-ga.md
content/zh/blog/_posts/2018-07-11-dynamic-kubelet-configuration.md
content/zh/blog/_posts/2018-10-10-runtimeclass.md
content/zh/blog/_posts/2019-03-28-PID-Limiting.md
content/zh/blog/_posts/2019-08-06-OPA-Gatekeeper-Policy-and-Governance-for-Kubernetes.md
content/zh/docs/concepts/cluster-administration/networking.md
content/zh/docs/concepts/cluster-administration/proxies.md
content/zh/docs/concepts/storage/dynamic-provisioning.md
content/zh/docs/concepts/storage/storage-classes.md
content/zh/docs/reference/glossary/cluster-operations.md
content/zh/docs/reference/kubectl/docker-cli-to-kubectl.md
content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_kubelet-config.md
content/zh/docs/setup/production-environment/tools/kops.md
content/zh/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
content/zh/docs/setup/production-environment/tools/kubeadm/high-availability.md
content/zh/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm.md
content/zh/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
content/zh/docs/tasks/administer-cluster/cluster-upgrade.md
content/zh/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods.md
content/zh/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md
content/zh/docs/tasks/administer-cluster/namespaces-walkthrough.md
content/zh/docs/tasks/administer-cluster/namespaces.md
content/zh/docs/tasks/administer-cluster/running-cloud-controller.md
content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
content/zh/docs/tasks/extend-kubernetes/configure-aggregation-layer.md
content/zh/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
content/zh/docs/tutorials/kubernetes-basics/explore/explore-intro.html
content/zh/docs/tutorials/security/apparmor.md
content/zh/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume.md
```

part-2
- [x] https://github.com/kubernetes/website/pull/33632.
```
content/zh/docs/tasks/administer-cluster/ip-masq-agent.md
```

- [ ] part-3 https://github.com/kubernetes/website/pull/33759 https://github.com/kubernetes/website/pull/35197

```
content/zh/case-studies/netease/index.html
content/zh/case-studies/nordstrom/index.html
content/zh/case-studies/wikimedia/index.html
```

- [ ]  part-4

```
content/zh/case-studies/ygrene/index.html
content/zh/case-studies/zalando/index.html
```

- [x] part-5 #34051 #33988 https://github.com/kubernetes/website/pull/35232

```
content/zh/docs/concepts/storage/volumes.md
content/zh/docs/reference/access-authn-authz/admission-controllers.md
content/zh/docs/reference/command-line-tools-reference/kube-apiserver.md
```

**Comment by mengjiao-liu** [comment]
please check the issues https://github.com/kubernetes/website/issues/33474, https://github.com/kubernetes/website/issues/33475, https://github.com/kubernetes/website/issues/33476, https://github.com/kubernetes/website/issues/33477, https://github.com/kubernetes/website/issues/33478, https://github.com/kubernetes/website/issues/33479 and sign on tasks there. It would help save your time and avoid conflicts when working on different pages.

Pages not listed in the issue above can be assigned here.

**Comment by fenggw-fnst** [comment]
Fix part2: content/zh/docs/tasks/administer-cluster/ip-masq-agent.md in #33632.

**Comment by Sea-n** [comment]
For `content/zh/case-studies/wikimedia/index.html`, I've made this PR to resync and fixed translation term.
- #33759

**Comment by Sea-n** [comment]
And this two file are fixed by different PR already.

- content/zh/docs/reference/access-authn-authz/admission-controllers.md
    - #34051
- content/zh/docs/reference/command-line-tools-reference/kube-apiserver.md
    - #33988

**Comment by tengqm** [comment]
There are still a few pages where the translation is inconsistent but the problem is not a big one.
/close
