### ISSUE TITLE
Install and Set Up kubectl on Linux

### ISSUE THREAD

**Issue by Sandiip96** [kubernetes/website#33764]
While installing bootstrap server, we need to configure 'kubectl', so i am using aws cloud, used this command to install
![error](https://user-images.githubusercontent.com/92013483/168776413-e029361c-4ceb-44b0-bbfa-3b3e313e0afe.png)

" curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64 "
But it shows an error it is deprecating then how can i install kubectl in amazon linux

**Comment by Shubham82** [comment]
Hi @Sandiip96
I think kubectl is installed. This errors message is for the flag you are using with `kubectl version`
It is due to the following code changes: 
See this PR: https://github.com/kubernetes/kubernetes/pull/108987 https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/version/version.go#L138

**Comment by sftim** [comment]
We could mention that `kubectl version --short` is the command to run (which it _is_ if you're not sure what version of kubectl you're going to get) but that you do see a deprecation warning.

The warning being printed does not indicate any error.

/language en

**Comment by sftim** [comment]
/remove-kind support

I'm not sure that this is a docs bug. Something needs to change, but maybe that thing is `kubectl` itself.

**Comment by reylejano** [comment]
Hi @Sandiip96 , this issue is better suited in https://github.com/kubernetes/kubectl, please re-create this issue in https://github.com/kubernetes/kubectl
Since this is not an issue with kubernetes.io, I'm closing this issue
