### ISSUE TITLE
kubeadm fails pulling images; containerd disabled CRI plugin

### ISSUE THREAD

**Issue by nobiit** [kubernetes/website#33770]
### What happened?

I can't initialize Kubernetes 1.24.0 cluster, failed at `kubeadm config images pull` step

```
+ sudo kubeadm config images pull
failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.0": output: time="2022-05-17T02:10:44+07:00" level=fatal msg="pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
```

### What did you expect to happen?

I can initialize Kubernetes 1.24.0 cluster without error

### How can we reproduce it (as minimally and precisely as possible)?

1. Prepare a computer with docker/containerd pre-installed and make sure it works properly
2. Install kubeadm/kubelet/kubectl 1.24.0 using apt
3. Run `kubeadm config images pull`

### Anything else we need to know?

- I opened an issue at kubeadm, and it looks like it's on k8s image maintenance.
https://github.com/kubernetes/kubeadm/issues/2696
- Everything works with 1.23.6, fails on 1.24.0

### Kubernetes version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### Cloud provider

Ubuntu

### OS version

Ubuntu 20.04

### Install tools

apt

### Container runtime (CRI) and version (if applicable)

containerd

**Comment by Awot83** [comment]
i had the same error with kubeadm v1.24,  (other VM can pull image, with kubeadm 1.23 on the same network)
so i did remove the file /etc/containerd/config.toml 
and restarted containerd 

but i still get this error : 
```
failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.0": output: time="2022-05-18T19:28:17+02:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.24.0\": dial tcp 108.177.15.82:443: connect: connection refused"
, error: exit status 1
```

**Comment by neolit123** [comment]
> connect endpoint 'unix:///var/run/containerd/containerd.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"

that seems like connectivity issue to the containerd endpoint?
make sure that containerd is running. try checking with `crictl -r <endpoint> info`.

**Comment by Awot83** [comment]
yes containerd was stopped 
now i get 
 kubeadm config images pull

```
failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.0": output: time="2022-05-18T19:54:01+02:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.24.0\": dial tcp 66.102.1.82:443: connect: connection refused"
, error: exit status 1
```

**Comment by neolit123** [comment]
> dial tcp 66.102.1.82:443: connect: connection refused"

seems like the machine has no access to the k8s GCR. try debugging the connectivity with curl or other tools.

**Comment by Awot83** [comment]
Hello, 
i did theses tests : 
(i am on centos 7)

- with the inital config.toml file

```
kubeadm config images pull:
failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.0": output: time="2022-05-19T13:59:29+02:00" level=fatal msg="pulling image: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
, error: exit status 1
```

- with the modified config.toml file : # disabled_plugins = ["cri"] 

(also tested without the file, same error) 
(and i reach my proxy with 200 ok )
```
kubeadm config images pull:
failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.0": output: time="2022-05-19T14:01:24+02:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.24.0\": dial tcp 108.177.15.82:443: connect: connection refused"
, error: exit status 1
```
do you have any advice how to debug this ?

**Comment by mk46** [comment]
if not then please check proxy URL is set in  environment var or not as `http_proxy`, `https_proxy`, `HTTP_PROXY`, `HTTPS_PROXY`?

**Comment by Awot83** [comment]
i tried ctr images pull k8s.gcr.io/kube-apiserver:v1.24.0  => it was  "connection refused"
then i added http_proxy / https_proxy in env var  (i already had HTTP_PROXY, HTTPS_PROXY and NO_PROXY) 
then  ctr images pull k8s.gcr.io/kube-apiserver:v1.24.0 was ok ! 

```
ctr images pull k8s.gcr.io/kube-apiserver:v1.24.0
k8s.gcr.io/kube-apiserver:v1.24.0:                                                resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:a04522b882e919de6141b47d72393fb01226c78e7388400f966198222558c955:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:c4b8eeef9a18fb047192dc0489de1106b111d2a5c515e3800ee198c5a36f4ed0: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:8ebfef20cea7c8354b4e7689ebbada4d386bed1dd853e3de4b25b31ebbe87cfc:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:529072250ccc6301cb341cd7359c9641b94a6f837f86f82b1223a59bb0712e64:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:36698cfa5275e0bda70b0f864b7b174e0758ca122d8c6a54fb329d70082c73f8:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:fe7d6916a3e133207125ddb4d8cdc8307cdb5f40d891cc3a9df906bf89738e79:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.3 s                                                                    total:  32.2 M (24.8 MiB/s)       
```

but kubeadm config images pull   is still KO with same error :
 
```
failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.0": output: time="2022-05-19T15:44:44+02:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.24.0\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.24.0\": dial tcp 66.102.1.82:443: connect: connection refused"
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
```
so i added 
  Environment="http_proxy=http://proxy...
  Environment="https_proxy=http://proxy..
  Environment="no_proxy..."
also in the file /etc/systemd/system/docker.service.d/http-proxy.conf (i had already the 3 line with capital letters) 
but i still get the same error on  kubeadm config images pull

**Comment by neolit123** [comment]
that looks like a kubeadm bug, where the system ENV vars are not passed to the `crictl` command.
could you please log an issue about it in [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm)?

https://github.com/kubernetes/kubernetes/blob/92285fd74e8906bc4910d6fb6729b7ec0e74f427/cmd/kubeadm/app/util/runtime/runtime.go#L71

we need something like `cmd.SetEnv(os.Environ())` there.

in the meantime just `kubeadm config images list` and pull images manually.

**Comment by neolit123** [comment]
> then i added http_proxy / https_proxy in env var (i already had HTTP_PROXY, HTTPS_PROXY and NO_PROXY)

that's an artifact of *nix having case sensitive env variables (unlike Windows) and some tools inconsistently need either the uppercase or lowercase variants.

**Comment by sftim** [comment]
`/etc/systemd/system/docker.service.d/http-proxy.conf` isn't relevant to the containerd runtime.

---


> that's an artifact of *nix having case sensitive env variables (unlike Windows) and some tools inconsistently need either the uppercase or lowercase variants.

It's actually defined specifically as lower case. A _de facto_ convention, but the aim is to avoid the risk of [CGI](https://en.wikipedia.org/wiki/Common_Gateway_Interface) setting `HTTP_PROXY` if a client sends a `PROXY:` (or `Proxy:`) request header. This `*_proxy` convention is different from most Unix / POSIX environment variables, which are all-uppercase.

---

This GitHub issue is not the place for general chat about `kubeadm` and issues using that tool with Kubernetes v1.24

I'm minded to lock _this_ issue, and encourage @nobitt as the original reporter to file a new issue that specifically focuses on documentation improvements. Additionally, @Awot83 is welcome to file an issue about `kubeadm` and HTTP proxy environment variables.

**Comment by sftim** [comment]
> that's an artifact of *nix having case sensitive env variables (unlike Windows) and some tools inconsistently need either the uppercase or lowercase variants.

It's actually defined specifically as lower case. A _de facto_ convention, but the aim is to avoid the risk of [CGI](https://en.wikipedia.org/wiki/Common_Gateway_Interface) setting `HTTP_PROXY` if a client sends a `PROXY:` (or `Proxy:`) request header. This `*_proxy` convention is different from most Unix / POSIX environment variables, which are all-uppercase.

---

This GitHub issue is not the place for general chat about `kubeadm` and issues using that tool with Kubernetes v1.24

I'm minded to lock _this_ issue, and encourage @nobiit as the original reporter to file a new issue that specifically focuses on documentation improvements. Additionally, @Awot83 is welcome to file an issue about `kubeadm` and HTTP proxy environment variables.

**Comment by neolit123** [comment]
We are still tracking https://github.com/kubernetes/website/issues/33770#issuecomment-1130693936 here.

@mk46 would you like to submit a PR for that as well?

The kubeadm proxy bug was fixed in https://github.com/kubernetes/kubeadm/issues/2697

**Comment by mk46** [comment]
@neolit123 Sure.

**Comment by bajoben** [comment]
@arun-chib @Awot83 
for me it helped adding http-proxy.conf to `/etc/systemd/system/containerd.service.d/http-proxy.conf`

**Comment by keobox** [comment]
> @arun-chib @Awot83 for me it helped adding http-proxy.conf to `/etc/systemd/system/containerd.service.d/http-proxy.conf` and setting the appropriate values for HTTP_PROXY, HTTPS_PROXY and NO_PROXY

I don't have that file (ubuntu 22.04 LTS). Could you be more specific please? Can you share the configuration file?

**Comment by arun-chib** [comment]
@keobox : Try these steps:

For containerd
sudo mkdir -p /etc/systemd/system/containerd.service.d

Create a file http-proxy.conf

cat /etc/systemd/system/containerd.service.d/http-proxy.conf

[Service]

Environment=”HTTP_PROXY=http://XXXX:8080"

Environment=”HTTPS_PROXY=http://XXXX:8080"

Restart the containerd daemon

systemctl daemon-reload

systemctl restart containerd



For docker
sudo mkdir -p /etc/systemd/system/docker.service.d

create a file /etc/systemd/system/docker.service.d/http-proxy.conf

cat /etc/systemd/system/docker.service.d/http-proxy.conf

[Service]

Environment=”HTTP_PROXY=http://10.115.27.54:3128"

Environment=”HTTPS_PROXY=http://10.115.27.54:3128"

Restart the docker daemon

systemctl daemon-reload

systemctl restart docker





For cri-o
sudo mkdir -p /etc/systemd/system/crio.service.d

Create a file http-proxy.conf

cat /etc/systemd/system/crio.service.d/http-proxy.conf

[Service]

Environment=”HTTP_PROXY=http://10.115.27.54:3128"

Environment=”HTTPS_PROXY=http://10.115.27.54:3128"

Restart the crio daemon

systemctl daemon-reload

systemctl restart crio

**Comment by keobox** [comment]
@arun-chib  thanks for helping, but I have these traces here that worry me

Jan 23 08:58:14 systemd[1]: /etc/systemd/system/containerd.service.d/http-proxy.conf:2: Invalid syntax, ignoring: ”HTTP_PROXY=http://XXXX:8080"
Jan 23 08:58:14 systemd[1]: /etc/systemd/system/containerd.service.d/http-proxy.conf:3: Invalid syntax, ignoring: ”HTTPS_PROXY=http://XXXX:8080"

**Comment by keobox** [comment]
Solved with this: https://serverfault.com/questions/1118051/failed-to-run-kubelet-validate-service-connection-cri-v1-runtime-api-is-not-im

**Comment by crklinkenberg** [comment]
> 

option [2] worked for me. and then **restarting the containerd service**
