### ISSUE TITLE
Broken link on kubectl-commands page

### ISSUE THREAD

**Issue by ashish-jaiswar** [kubernetes/website#33787]
### Problem:
Link of [https://index.docker.io/v1/](https://index.docker.io/v1/) give 404 error
### Proposed solution:
update link to [https://index.docker.io](https://index.docker.io)
### Page to update:
[https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-secret-docker-registry-em-](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-secret-docker-registry-em-)

/kind documentation
/good-first-issue

**Comment by sftim** [comment]
/remove-good-first-issue

This is generated documentation, and newcomers might not find a fix straightforward.

**Comment by ashish-jaiswar** [comment]
Hi @sftim if [https://index.docker.io/v1/](https://index.docker.io/v1/) is not a web page. Can I close this issue?

**Comment by sftim** [comment]
You're welcome to close this issue @ashish-jaiswar

**Comment by ashish-jaiswar** [comment]
closing this issue
