### ISSUE TITLE
Incorrect role restrictions on docs/contribute/review/for-approvers/

### ISSUE THREAD

**Issue by t-inu** [kubernetes/website#33784]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/contribute/review/for-approvers/
It seems the role restrictions for the below commands are incorrect.
- /assign: Reviewers or Approvers
- /close: Reviewers or Approvers

**Proposed Solution:**
- /assign: Anyone
- /close: Authors or Organization members

And, I think It's better to add the following statement to the /assign command's description.
The target user(s) must be an org member or should have previously commented on the issue or PR.

**Page to Update:**
https://kubernetes.io/docs/contribute/review/for-approvers/

/language en
/assign

**Comment by sftim** [comment]
Perhaps we can update [that page](https://kubernetes.io/docs/contribute/review/for-approvers/) to refer and hyperlink to https://www.kubernetes.dev/docs/guide/pull-requests/#the-testing-and-merge-workflow instead?

If we want to change the text of [Pull Request Process](https://www.kubernetes.dev/docs/guide/pull-requests/) (for example, to mention `/close`), we'd edit: https://github.com/kubesphere/community/blob/master/developer-guide/development/pull-requests.md

**Comment by t-inu** [comment]
@sftim
I agree that it's better to centralize the information.
Let me know the target range to be replaced with the link.
Do you think all of this page unnecessary?
If so, it may be better to close this issue and create another one because the purpose changes.

**Comment by sftim** [comment]
I think the page to edit is https://kubernetes.io/docs/contribute/review/for-approvers/

**Comment by t-inu** [comment]
I'll fix it according to the "Proposed Solution", and write as follows in the last part.

To view the commands that you can use in a PR, see the [Prow Command Reference](https://prow.k8s.io/command-help?repo=kubernetes%2Fwebsite). (This is an existing description)
And see the [The Testing and Merge Workflow](https://www.kubernetes.dev/docs/guide/pull-requests/#the-testing-and-merge-workflow) for the flow from creating a pull request to merging it.

@sftim If your opinion differs from this fix, please comment again.

**Comment by t-inu** [comment]
I found that the role restrictions have already fixed in https://github.com/kubernetes/website/pull/36899
/close
