### ISSUE TITLE
[zh][Umbrella] api-authorization reference pages to sync for 1.24

### ISSUE THREAD

**Issue by windsonsea** [kubernetes/website#33798]
**This is a Feature Request**

After suggestions from @tengqm, I carefully checked the [api-docs](https://kubernetes.io/docs/reference/kubernetes-api/) and current issues, and find the following docs are still no any Chinese version and localization assignment.

Could @tengqm, @mengjiao-liu please give a favor to confirm whether the following tasks can be assigned to me for localization? Thanks.

- [x] refer-1 @windsonsea #33828 
  ```
  499 content/en/docs/reference/kubernetes-api/authorization-resources/cluster-role-binding-v1.md
  ```
- [x] refer-2 @windsonsea #33892 
  ```
  495 content/en/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1.md
  ```
- [x] refer-3 @windsonsea #33916 
  ```
  602 content/en/docs/reference/kubernetes-api/authorization-resources/role-binding-v1.md
  ```
- [x] refer-4 @windsonsea #33940 
  ```
  587 content/en/docs/reference/kubernetes-api/authorization-resources/role-v1.md
  ```
- [x] refer-5 @windsonsea #33953
  ```
  172 content/en/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1.md
  176 content/en/docs/reference/kubernetes-api/authorization-resources/self-subject-rules-review-v1.md
  ```
  The file below is taken over to @windsonsea due to stagnated too many days by @shixiuguo at #33523.
  ```
  214 content/en/docs/reference/kubernetes-api/authorization-resources/subject-access-review-v1.md
  ```
- [x] refer-6  @windsonsea #34034 
  ```
  117 content/en/docs/reference/kubernetes-api/authorization-resources/local-subject-access-review-v1.md
  ```

**Comment by tengqm** [comment]
#33518 is an issue report. #33523 is the PR for the last item.

**Comment by howieyuen** [comment]
> 
update:
https://github.com/kubernetes/website/pull/34034 is the PR for the last item.
