### ISSUE TITLE
Help troubleshooting a cluster deployed using kubeadm

### ISSUE THREAD

**Issue by marco74** [kubernetes/website#33795]
Hello,

on the site I read
```You should now be able to curl the nginx Service on <CLUSTER-IP>:<PORT> from any node in your cluster.```

After following the instructions I can curl my nginx service only on that nodes where a pod is running. On the others I got
```curl: (7) Failed to connect to 10.107.64.40 port 80: No route to host```
 Is that intentionally or am I missing something?

Also the DNS part does not work at all for me. After following the instructions according to the page, I only get
```bash root@curl:/ ]$ nslookup my-nginx
Server:    10.96.0.10
Address 1: 10.96.0.10

nslookup: can't resolve 'my-nginx'
```
Since this takes that long I assume it's a timeout error.

I'm using kubernetes 1.24 on Debian Bullseye with cri-dockerd installed as mentioned on https://github.com/Mirantis/cri-dockerd

Marco

**Comment by Kartik494** [comment]
@marco74  could you  provide the task reference you are facing issue on?

**Comment by marco74** [comment]
Actually I do not understand your question. I already wrote that I followed the instructions on 

I followed every single step on https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

The first problem I see is that two pods have the same IP. With that they wont be able to cummunicate with each other, so what am I missing to not get the same IP on both pods (on different nodes):

```
marco@kn1:~/kubernetes/test1$ kubectl apply -f ./run-my-nginx.yaml
deployment.apps/my-nginx created
marco@kn1:~/kubernetes/test1$ kubectl get pods -l run=my-nginx -o wide
NAME                       READY   STATUS              RESTARTS   AGE   IP       NODE   NOMINATED NODE   READINESS GATES
my-nginx-df7bbf6f5-lsp2v   0/1     ContainerCreating   0          8s    <none>   kn6    <none>           <none>
my-nginx-df7bbf6f5-zkhvp   0/1     ContainerCreating   0          8s    <none>   kn3    <none>           <none>
marco@kn1:~/kubernetes/test1$ kubectl get pods -l run=my-nginx -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE   NOMINATED NODE   READINESS GATES
my-nginx-df7bbf6f5-lsp2v   1/1     Running   0          52s   172.17.0.2   kn6    <none>           <none>
my-nginx-df7bbf6f5-zkhvp   1/1     Running   0          52s   172.17.0.2   kn3    <none>           <none>
marco@kn1:~/kubernetes/test1$ kubectl get pods -l run=my-nginx -o yaml | grep podIP
    podIP: 172.17.0.2
    podIPs:
    podIP: 172.17.0.2
    podIPs:
```

**Comment by Kartik494** [comment]
@marco74 Could you please share which cni plugin you are using ?  i have checked in my env , pod's are getting different IP's .

kubectl get pods -l run=my-nginx -o wide
NAME                        READY   STATUS    RESTARTS   AGE   IP               NODE         
my-nginx-5b56ccd65f-9b55t   1/1     Running   0          70s   192.168.212.16   workernode1   
my-nginx-5b56ccd65f-x9rnz   1/1     Running   0          70s   192.168.212.15   workernode1

**Comment by marco74** [comment]
@Kartik494 Thank you for your answer. Different IPs must be necessary, otherwise one pod could not connect to the other because routing won't work, when the same subnets are used. Could you please drop me a thorough instruction set how to set up a cluster, starting right after OS-setup, then I could compare to find the mistake.

Usually I startup with a fresh installed Debian Bullseye on a Virtual-Box machine that's installed by a remastered netinst-image already including Docker installation.

### common instruction set (for master and worker):
```
## install cri-dockerd
sudo apt-get -y install golang
# From: https://github.com/Mirantis/cri-dockerd
git clone https://github.com/Mirantis/cri-dockerd.git
cd cri-dockerd/
mkdir bin
cd src/
go get
go build -o ../bin/cri-dockerd
cd ..
sudo mkdir -p /usr/local/bin
sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
sudo cp -a packaging/systemd/* /etc/systemd/system
sudo sed -i -e 's,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd,' /etc/systemd/system/cri-docker.service
cd ..

sudo systemctl daemon-reload
sudo systemctl enable cri-docker.service
sudo systemctl enable --now cri-docker.socket

## install kubernetes
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

sudo kubeadm --cri-socket unix:///run/cri-dockerd.sock config images pull
```

#### then on master
I initialize with:
```
sudo kubeadm --cri-socket unix:///run/cri-dockerd.sock init

## configure in personal directory
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
```
Then I either do
```
kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
```
or
```
kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
```
#### on the worker node I run the commend that the master shows me when I hit
```
echo "sudo `kubeadm token create --print-join-command --ttl 30m` --cri-socket=unix:///run/cri-dockerd.sock"
```

#### back on the master I can see all my workers
```
marco@kn1:~$ kubectl get nodes
NAME   STATUS   ROLES           AGE   VERSION
kn1    Ready    control-plane   94s   v1.24.0
kn2    Ready    <none>          30s   v1.24.0
kn3    Ready    <none>          25s   v1.24.0
kn4    Ready    <none>          21s   v1.24.0
kn5    Ready    <none>          15s   v1.24.0
kn6    Ready    <none>          11s   v1.24.0

```

Then I continue with https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

```
marco@kn1:~$ vim run-my-nginx.yaml
marco@kn1:~$ kubectl apply -f ./run-my-nginx.yaml
kubectl get pods -l run=my-nginx -o wide
deployment.apps/my-nginx created
NAME                       READY   STATUS    RESTARTS   AGE   IP       NODE   NOMINATED NODE   READINESS GATES
my-nginx-df7bbf6f5-bxh54   0/1     Pending   0          0s    <none>   kn4    <none>           <none>
my-nginx-df7bbf6f5-rvlnd   0/1     Pending   0          0s    <none>   kn5    <none>           <none>
marco@kn1:~$ kubectl get pods -l run=my-nginx -o wide
NAME                       READY   STATUS    RESTARTS   AGE   IP           NODE   NOMINATED NODE   READINESS GATES
my-nginx-df7bbf6f5-bxh54   1/1     Running   0          46s   172.17.0.2   kn4    <none>           <none>
my-nginx-df7bbf6f5-rvlnd   1/1     Running   0          46s   172.17.0.2   kn5    <none>           <none>

```

**Comment by Tej-Singh-Rana** [comment]
Hi @marco74 ,

If you choose the service type: `ClusterIP` then you can curl the nginx service from any pods (curl pkg should be installed on that pod's image or later on, you can install it by its package manager) on that XYZ node in your cluster.
Suppose **pod-1** is deployed on **worker-01** node and **pod-2** is deployed on **worker-02** node
then you can `Curl` to that nginx service on its `<CLUSTER-IP>:<PORT>` from inside pod (`pod-1` or `pod-2`). 
Simply run the command: `kubectl exec -it pod-1 -- bash`
then do `curl <CLUSTER-IP>:<PORT>`

If you want to curl from the node then change service type: `ClusterIP` to `NodePort`. 
 
Reference link - https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
 
Regards,

**Comment by marco74** [comment]
@Tej-Singh-Rana: Thank you for that hint! I can test this tomorrow. Just to give quicker replies (and hopefully answers): Isn't that considered as alpha in 1.24? So I'm wondering, why https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/ is not just working as expected. This also does not answer the question why two pods get the same IP. As far as I know networking, networking cannot work properly, when two participants have the same IP.

Regards,

**Comment by marco74** [comment]
After tests with Ubuntu 20.04 and 22.04 I found out following. Kubernetes stops supporting newer distributions including Ubuntu 22.04 and Debian 11 with Version 1.21. Since that version kube-system pods get restarted constantly:

```
marco@kn3:~$ cat /etc/debian_version 
11.3
marco@kn3:~$ dpkg -l kubectl kubeadm kubelet
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=====================================
ii  kubeadm        1.21.13-00   amd64        Kubernetes Cluster Bootstrapping Tool
ii  kubectl        1.21.13-00   amd64        Kubernetes Command Line Tool
ii  kubelet        1.21.13-00   amd64        Kubernetes Node Agent
marco@kn3:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                          READY   STATUS    RESTARTS   AGE
kube-system   coredns-558bd4d5db-dqb6t      0/1     Pending   0          57m
kube-system   coredns-558bd4d5db-p65tb      0/1     Pending   0          56m
kube-system   etcd-kn3                      1/1     Running   15         57m
kube-system   kube-apiserver-kn3            1/1     Running   13         57m
kube-system   kube-controller-manager-kn3   1/1     Running   13         57m
kube-system   kube-proxy-76dvp              1/1     Running   14         57m
kube-system   kube-scheduler-kn3            1/1     Running   12         57m
```

I assume that it's not intended to restart pods that often. Just as a comparision tha same with version 1.20 on the same OS (different VM):

```marco@kn2:~$ cat /etc/debian_version 
11.3
marco@kn2:~$ dpkg -l kubectl kubeadm kubelet
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=====================================
ii  kubeadm        1.20.15-00   amd64        Kubernetes Cluster Bootstrapping Tool
ii  kubectl        1.20.15-00   amd64        Kubernetes Command Line Tool
ii  kubelet        1.20.15-00   amd64        Kubernetes Node Agent
marco@kn2:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                          READY   STATUS    RESTARTS   AGE
kube-system   coredns-74ff55c5b-tbjxw       0/1     Pending   0          11h
kube-system   coredns-74ff55c5b-xb4ws       0/1     Pending   0          11h
kube-system   etcd-kn2                      1/1     Running   3          11h
kube-system   kube-apiserver-kn2            1/1     Running   2          11h
kube-system   kube-controller-manager-kn2   1/1     Running   2          11h
kube-system   kube-proxy-l8rwl              1/1     Running   2          11h
kube-system   kube-scheduler-kn2            1/1     Running   2          11h
```

The only difference in setting up the stack was

```
sudo apt-get -y install kubelet=1.21.13-00 kubectl=1.21.13-00 kubeadm=1.21.13-00
```
vs.
```
sudo apt-get -y install kubelet=1.20.15-00 kubeadm=1.20.15-00 kubectl=1.20.15-00
```

So, what prevents newer kubernetes versions from working cleanly on the latest distributions Debian 11 and Ubuntu 22.04? Does anybody know how to get kubernetes working on those distributions as well?

**Comment by marco74** [comment]
After having a look at https://github.com/kubernetes/kubernetes/issues/105762 I found a solution, that solves the restart problem on Debian 11. I do not use Ubuntu, therefore feel free to also test it on Ubuntu 22.04.

With the hint I updated `/etc/containerd/config.toml`:

```
version = 2

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
```

With this I got the stack running without restarts, also the network initialization works very smooth. My suggestion for the kubernetes documentation team. could you please add the two lines 
* `version = 2` 
* `runtime_type = "io.containerd.runc.v2"

at https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd ? I was not able to get the stack running without those two lines.

For all those who are interested in how I finally setup a cluster with Debian 11 and kubernetes 1.24:

```
sudo apt-get -y update
sudo apt-get -y install ca-certificates curl gnupg lsb-release

#from:
# * https://gist.github.com/dbathgate/737e8d800decde9adbf8a0130870bcc4
# * https://github.com/flannel-io/flannel
sudo mkdir -p /opt/bin/
sudo curl --location https://github.com/flannel-io/flannel/releases/download/v0.18.0/flanneld-amd64 -o /opt/bin/flanneld
sudo chmod +x /opt/bin/flanneld #/usr/local/bin/flanneld

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo   "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get -y update

sudo apt-get -y install containerd.io
sudo sed -i "s/^\(disabled_plugins\s*=\)/# \1/" /etc/containerd/config.toml
cat <<EOF | sudo tee -a /etc/containerd/config.toml
### from https://github.com/kubernetes/kubernetes/issues/105762
version = 2

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true

EOF
sudo systemctl restart containerd

## Prerequisites for kubernetes, according to:
##   https://kubernetes.io/docs/setup/production-environment/container-runtimes/
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# sysctl params required by setup, params persist across reboots
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

# Apply sysctl params without reboot
sudo sysctl --system

## install kubernetes
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl

sudo kubeadm config images pull

sudo kubeadm --pod-network-cidr=10.244.0.0/16 init

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml

kubectl get pods -n kube-system -o wide
```


Regards,

**Comment by sftim** [comment]
@marco74 as of now, is there a task page that needs fixing? If so, what's the task page and what in that page isn't right?

**Comment by marco74** [comment]
@sftim Thank you for asking, just looked up:

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd describes how to setup containerd for Kubernetes.

When reading containerd's documentation for configuration (https://github.com/containerd/cri/blob/master/docs/config.md) they write about `version = 2`. This was added with commit `e2550f6285638aaf591d40927c319a301b697d5f` on Jul, 24 2019 (https://github.com/containerd/cri/commit/e2550f6285638aaf591d40927c319a301b697d5f), not fully 3 years ago. `runtime_type = "io.containerd.runc.v2"` is mentioned in the same documentation since https://github.com/containerd/cri/commit/aaddaa27320bfe89959d838205a7117af825361e, on Dec, 16 2019. This was about 2.5 years ago.

Debian 11 released about 10 months ago. It works quite stable but I could not get Kubernetes running without those two settings. I also tried omitting one of the two lines – both are needed. I tested without using those two lines on Ubuntu 22.04 and could not get it running either. I did not test on Ubuntu 22.04, but I am pretty sure that this will work with those two lines.

It would be great, if somebody could explain me why version 2 is necessary, currently I do not know it. At the moment I only know that it helps. As you can read in this thread, I read about this on another thread, After I looked why the system-containers are restarting continuously.

Therefore I would really appreciate if this block:

```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  ...
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
```

could be adapted to this:

```
version = 2

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true

```

Could you, or probably somebody else do that?

Marco

**Comment by sftim** [comment]
For an analogy, think about the Linux kernel and userland tools.
If you want to do something that involves setting up Linux networking then you need to know about the kernel, and maybe also `iproute2` and other tools.
Each component there has documentation that goes so far but ultimately those docs often do stop at a point.

Because there's so much that touches Kubernetes but isn't actually Kubernetes, as a project we adopted an official [policy](https://github.com/kubernetes/enhancements/tree/master/keps/sig-docs/1326-third-party-content-in-docs#readme) on this. If in the future we find we have a much bigger amount of volunteered / contributed time going into docs, we're open to revising that policy. Right now, we want to make sure we're fair to all the different 3rd party tools out there and try to limit how much detail we go into

You are welcome to identify a page such as https://kubernetes.io/docs/setup/production-environment/container-runtimes/ and highlight a specific section that's wrong - no problem at all with that - or misleading. You can also propose improvements.

_This_ issue isn't, right now actionable enough. Imagine that a new docs contributor comes along and reads the issue description



> Hello,
> 
> on the site I read `You should now be able to curl the nginx Service on <CLUSTER-IP>:<PORT> from any node in your cluster.`
> 
> After following the instructions I can curl my nginx service only on that nodes where a pod is running. On the others I got `curl: (7) Failed to connect to 10.107.64.40 port 80: No route to host` Is that intentionally or am I missing something?
> 
> Also the DNS part does not work at all for me. After following the instructions according to the page, I only get
> 
> ```shell
> Server:    10.96.0.10
> Address 1: 10.96.0.10
> 
> nslookup: can't resolve 'my-nginx'
> ```
> 
> Since this takes that long I assume it's a timeout error.
> 
> I'm using kubernetes 1.24 on Debian Bullseye with cri-dockerd installed as mentioned on https://github.com/Mirantis/cri-dockerd
> 
> Marco

Can they use that information to work out what web page to fix and get an insight into how they might? I'm worried they can't.
We do, as a project, want to make it easier for folks to use `kubeadm` and to troubleshoot what happens when it goes wrong. However, this is a bit like the Linux kernel project offering only so much troubleshooting for someone whose Linux computer doesn't boot. At some point, an end user may be better off finding a packaged distribution (the likes of [EKD-D](https://aws.amazon.com/blogs/opensource/introducing-amazon-eks-distro/), [OKD](https://github.com/openshift/okd), or [RKE](https://rancher.com/products/rke)) and referring to the more opinionated docs for that specific combination of components. In the Linux computing world that might be Alpine, Debian, Fedora, Rocky, Ubuntu. You get the picture I hope.

I think the next steps here could be one of:

1. Treat this issue as having been mainly a support request along with some feedback, and close it.
2. You, @marco74, open a new issue that does aim to be more actionable for someone who tries to work on it.
3. File a feature request issue based on an identified need. For example:
   - add a guide on getting a cluster up and running that is more opinionated than the existing docs and also has more hand-holding than [Kubernetes the hard way](https://github.com/kelseyhightower/kubernetes-the-hard-way)
   - improve the docs for troubleshooting new clusters
   - improve the docs for troubleshooting issues relating to container runtime configuration
   - add more links to container runtime projects' docs on troubleshooting
   - _your own idea here!_

Which of those do you like best @marco74 ?

**Comment by sftim** [comment]
> container runtime projects' docs also does not have that good documentation

I agree. I believe that the right way to address the shortcomings you've seen working out how to build a cluster is to fix that.
In the Kubernetes project we don't really have capacity to document Kubernetes itself as well as we'd like. As a project, we don't have much capacity to go and improve those other products' docs - however, that is what needs to happen somehow.

---

GitHub issues are the right place to report that the documentation is wrong, or to suggest improvements. The original report here was actually not really in the right place, because you framed it as a support request. I'm afraid that GitHub is the wrong place to request help with Kubernetes, and this holds even if you felt that you wanted support because the docs fell short of expectations.

We have a [guide to communicating on GitHub](https://www.k8s.dev/docs/contributor-cheatsheet/#communicating-effectively-on-github). I hope I'm following the spirit of that guide, and I encourage everyone to. You're welcome to create more issues @marco74; I especially recommend that you read and follow the advice in [Creating an issue](https://www.k8s.dev/docs/contributor-cheatsheet/#creating-an-issue).

Maybe reporting an actionable issue doesn't match what you were looking for. If you'd like to have more of a discussion around how we document Kubernetes and help new folks get started, GitHub isn't the right place for that; maybe try [Discuss Kubernetes](https://discuss.kubernetes.io/)?
