### ISSUE TITLE
[zh] This page: /docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-removal-affects-you/ is inconsistent with Chinese doc check-if-dockershim-deprecation-affects-you.md

### ISSUE THREAD

**Issue by lishuai-hw** [kubernetes/website#33790]
**This is a Feature Request**

**What would you like to be added**

Modified the Chinese doc name to keep it consistent with its English doc name.

**Why is this needed**
This page: /docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-**removal**-affects-you/, it is inconsistent with Chinese doc name: check-if-dockershim-**deprecation**-affects-you.md

**Comments**

/language zh
/assign

**Comment by tengqm** [comment]
Fixed.
/close
