### ISSUE TITLE
Interactive Tutorial - Scaling Your App

### ISSUE THREAD

**Issue by Swannben** [kubernetes/website#33824]
the command to decrease the scaling is not workig properly, when i run the get pods it still lists 4 active ones instead of 2 desite thee eng only 2 deployments according to the get deployment

**Comment by Tej-Singh-Rana** [comment]
I didn't see this issue. 
Please find the attached screenshot.
<img width="558" alt="katacoda-demo" src="https://user-images.githubusercontent.com/58101587/169373002-7732ba9d-a45b-424c-bcd0-1a99e27e5625.png">


Regards,
