### ISSUE TITLE
Add new task page: override the wall-clock time in a Pod

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33847]
**This is a Feature Request**

**What would you like to be added**
Add new task page that explains two ways to have an app running inside Kubernetes see a different time:
1. Set the timezone for that application, and have the Pod inherit system time from the node.
2. Override the time for the container; for example, by using an entrypoint that sets a custom time and then execs the actual app.
  For this option, explain why you might do that. A relatively common story is to run some tests that verify time specific behavior. If you want to test how your app behaves when it encounters an expired certificate, you might force a test to run with the time set 2 years into the future.
   - You would need to grant the `SYS_TIME` capability; this is a better choice than running the workload as `root`.

I haven't checked whether Pods use a shared time namespace for the whole Pod, or a time namespace per container. If its the former, you could also use an init container to set the time.

The task page should outline how time works on computers and some common good practices, such as running nodes with accurate time (synchronized using NTP / PTP / etc).

Optionally, discuss the situation specifically for Windows containers and whether the system time for the Windows container should be UTC or the local timezone.

Working title: Override the Wall-Clock Time in a Pod

**Why is this needed**
Readers of the website search for `SYS_TIME` reasonably often. A page about how to achieve that task might help.

**Comments**
/language en
/kind feature

/priority backlog
(if accepted)

**Comment by sftim** [comment]
If appropriate: bump this down to /priority awaiting-more-evidence

**Comment by Rishit-dagli** [comment]
@sftim I noticed this issue in the backlog and I could take it up though I just wanted to run by my understanding with you once.

Here's how I plan to structure the new task page:

- Set timezone for a pod and have containers inherit it
- Set timezone for a deployment and have pods inherit it
- Set timezone for a container

About this part though:

>  have the Pod inherit system time from the node

I am a bit confused about implementing this?

**Comment by sftim** [comment]
@Rishit-dagli I recommend you focus on picking up issues that are marked as Accepted (this one isn't, yet).

How about any of these: https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Apriority%2Fcritical-urgent%2Cpriority%2Fimportant-soon+label%3Atriage%2Faccepted

**Comment by sftim** [comment]
If anyone does want to pick it up, then make sure it's a valid task to cover, and make sure that you (the author) already know how to perform the task that you want to explain.

**Comment by sftim** [comment]
> have the Pod inherit system time from the node

There is a file `/etc/localtime` for Linux systems. Making a copy of that file available readonly to a container lets the Pod / container pick up the node's local timezone, whatever that is.
I don't know what is available for Windows.
