### ISSUE TITLE
[zh]  policy-resources reference pages to sync for 1.24

### ISSUE THREAD

**Issue by TinySong** [kubernetes/website#33840]
**This is a Feature Request**
I found that the following documents still do not have any Chinese version and localization work， When working quotas in-memory-cpu-namespace.md in this PR: https://github.com/kubernetes/website/pull/33779.

@tengqm please help me to confirm. 😄 

- [ ]  task-1 @[Cosrider](https://github.com/Cosrider)
```
content/en/docs/reference/kubernetes-api/policy-resources/limit-range-v1.md
```

- [ ] task-2 @TinySong 
```
content/en/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
```

- [ ] task-3 @ [pengcong08](https://github.com/pengcong08)
```
content/en/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1.md
```

- [ ] task-4 @ [pengcong08](https://github.com/pengcong08)
```
content/en/docs/reference/kubernetes-api/policy-resources/pod-security-policy-v1beta1.md
```

- [ ] task-5 @[Cosrider](https://github.com/Cosrider)
```
content/en/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
```

**Comment by Cosrider** [comment]
i want to pick up task-1 and task-5 @TinySong

**Comment by pengcong08** [comment]
pick up task-3,task-4

**Comment by TinySong** [comment]
@pengcong08 @Cosrider please read https://kubernetes.io/zh/docs/contribute/localization/ to Know some matters needing attention.

**Comment by mengjiao-liu** [comment]
Is there any progress？

**Comment by tengqm** [comment]
This can be closed because all files have been translated.
/close
