### ISSUE TITLE
Link to CNCF contributor guide

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33848]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/contribute/ so that early in the page there is a link to
https://contribute.cncf.io/contributors/projects/#kubernetes

You should decide on some suitable text for the hyperlink. Read https://contribute.cncf.io/contributors/ to get ideas about what to write, if you're not sure.

:information_source:  Don't remove any of the existing links; this is an addition.

**Why is this needed**
This change will help signpost readers to the CNCF contributor site.

**Comments**
/kind feature
/language en
/triage accepted
/priority backlog
/help

**Comment by kadtendulkar** [comment]
Hello @sftim, I have gone through the issue mentioned, so I think the following changes can be suitable in the note section.

Note: To learn more about contributing to Kubernetes, [one of the CNCF hosted projects](https://contribute.cncf.io/contributors/projects/#kubernetes), see the [contributor documentation](https://www.kubernetes.dev/docs/).

the text for the hyperlink ( https://contribute.cncf.io/contributors/projects/#kubernetes ) should be one of the CNCF hosted projects.

**Comment by ashish-jaiswar** [comment]
Hi @NitishKumar06 We are working on this issue. please work on other issue.

**Comment by NitishKumar06** [comment]
I've already made changes to this issue now. Please let it be reviewed.

**Comment by ashish-jaiswar** [comment]
No you can't work on this issue if someone is already working . this is against the policy of kubernetes. tonight I will open PR for this issue. There are many issues just work on that.
/unassign @NitishKumar06

**Comment by NitishKumar06** [comment]
See this issue has been opened from three days and as far I've observed the another contributor also raised the assign option for the same. Let my changes be reviewed and if it doesn't hold good, definitely you can also raise PR. The best one will be merged. /assign

**Comment by NitishKumar06** [comment]
Infact there's @kadtendulkar as well. Why are you not removing her from assignes? Please be respectful.

**Comment by NitishKumar06** [comment]
cool. Do this I've raised the PR anyways.

**Comment by ashish-jaiswar** [comment]
@NitishKumar06 this is against the policy of kubernetes. 
/unassign @NitishKumar06

**Comment by kadtendulkar** [comment]
Hey @NitishKumar06 please don't work on this issue, I'm new to community and this going to be my first issue. @ashish-jaiswar is helping me with that. 
This is community to help and work with unity. Please give chance to new contributers to work as well.

/unassign @NitishKumar06

**Comment by NitishKumar06** [comment]
@kadtendulkar Actually this is infact my first contribution as well. The fact that @ashish-jaiswar has more PRs merged shows he isn't a newbie here. My last PR was not merged because someone else merged it through my changes . Please notice that!

**Comment by NitishKumar06** [comment]
@kadtendulkar Why are you doing this?

**Comment by kadtendulkar** [comment]
Hey @NitishKumar06 this is my first issue to work on, please let me solve this. This is not about competition, its only about community work, wouldn't it bother you if i do the same with you. 
Please don't go against kubernetes policies.  if someone is assigned on the issue first you must ask if they are still working or not. 
You are not doing the right thing @NitishKumar06 
And in this case I'm working on it. Today i will raise a PR. Please be kind and look for other issues you will find one definitely. 😀


/unassign @NitishKumar06

**Comment by ashish-jaiswar** [comment]
Hey @NitishKumar06  you are not following the policy of kubernetes. I will report you to Kubernetes community.

**Comment by NitishKumar06** [comment]
Okay @ashish-jaiswar , Let my PR be reviewed. Sounds good now?

**Comment by ashish-jaiswar** [comment]
hey @NitishKumar06, kubernetes community will not accept your PR. Because you are working against the policy of kubernetes.

**Comment by NitishKumar06** [comment]
@ashish-jaiswar My last PR was not merged because although I was working on this issue as well but someone after me started working on it and his PR got merged.

**Comment by sftim** [comment]
_I'm writing this as a [tech lead](https://github.com/kubernetes/community/tree/49ecc500205884984a2174422f7715e7f9556b28/sig-docs#leadership) for SIG Docs_

:white_circle:  **TL;DR;** calm it down and be excellent to each other. :white_circle: 

Folks, it's best if people co-ordinate work. **_Anyone_** is welcome to open a PR to work on an issue provided the sign the CLA and agree to abide by our [code of conduct](https://kubernetes.io/community/code-of-conduct/).

If reviewers see multiple PRs opened for the same issue, they will usually:
- sigh inwardly
- look at the PR that was opened first, see if it's good to merge, and if so, merge that
- if not, look at the other PRs in chronological order
and finally
- close the other PRs with an explanation


So there's three further things here as I see it:
1. https://github.com/kubernetes/website/issues/33848#issuecomment-1134518812 mentions that
   >  you can't work on this issue if someone is already working . this is against the policy of kubernetes.
  
   I'm afraid that's not true. For SIG Docs, we actually have a policy of no [cookie licking](https://www.redhat.com/en/blog/dont-lick-cookie): nobody should assert that they own the implementation of an issue. 

1. However, it's unhelpful to work on an issue where someone else has started work, without first discussing with that person how to move forward. The polite and compassionate thing to do if an has been open.
   - https://github.com/kubernetes/website/issues/33848#issuecomment-1133114248
   - https://github.com/kubernetes/website/issues/33848#issuecomment-1134446220
   are both examples of behavior I'd prefer not to see more of.

1. It's best if people who have already worked on an issue avoid picking up Good First Issue issues. This issue is _not_ a “good first issue”; I deliberately chose not to add the Good First Issue label because I left the implementer some work to do around writing the hyperlink text and deciding what message would be suitable.
   That means it is OK for someone who has already submitted a PR to work on this. However, I would encourage people who are already contributing to hold off on Help Wanted issues (this one included) and only start work on a Help Wanted issue if you don't see any other work that you can reasonably pick up.

This discussion is getting more heated than it should be. If folks want to discuss how SIG Docs works, take it to Slack (https://kubernetes.slack.com/messages/sig-docs - invitations available from https://slack.k8s.io/) or come to the community meeting, 5:30 AM UTC on Wednesday 2022-05-25. A Zoom link for that call is in the Slack channel.

GitHub issues are not the place for [ad hominem](https://en.wikipedia.org/wiki/Ad_hominem) criticisms etc and I hope all concerned will take that on board.

I don't see grounds to involve the code of conduct folks at this point, and I'm hoping things stay that way. @ashish-jaiswar if you do have a concern about someone not following the code of conduct, please raise that by following the documented process.

**Comment by NitishKumar06** [comment]
Thanks @sftim . This was needed! @ashish-jaiswar Please go through it especially the first point.

**Comment by kadtendulkar** [comment]
Thanks @sftim  

@NitishKumar06 I'm requesting since I'm new contributer please allow me to do. According to the 2nd and 3rd point its appropriate to check if assigned people are working or not. And i have already mentioned I'm working on it. please know that. 

/unassign @NitishKumar06

**Comment by NitishKumar06** [comment]
But why didn't @ashish-jaiswar raise this point at that time when you made yourself assigned to this issue? He was working on that issue before you . But when I assigned it to myself, you know .

**Comment by ashish-jaiswar** [comment]
/@unassign @NitishKumar06

**Comment by ashish-jaiswar** [comment]
/@unassign @NitishKumar06

**Comment by NitishKumar06** [comment]
Work on issue . See ya!

**Comment by kadtendulkar** [comment]
Hey @NitishKumar06 , @ashish-jaiswar is helping me to raise my first PR that's why he assigned himself first. Please understand, I'm new to kubernetes community and I'm finding such conflicts.
It is always good to ask if the assigned people are working or not and since beginning i an mentioning that I'm working on it. But seems like you are not coordinating with new contributers .

**Comment by natalisucks** [comment]
Natali Vlatko here, co-chair of SIG Docs. This conversation has become too heated and isn't in line with our community guidelines with regards to politeness and respect. Our tech lead, @sftim, had given great clarity and guidance for those involved to move forward, but unfortunately, this hasn't taken place. I'll be messaging all involved separately to resolve this disagreement via the Kubernetes Slack.
