### ISSUE TITLE
Issue with k8s.io/releases/download/

### ISSUE THREAD

**Issue by kf6spf** [kubernetes/website#33844]
Trying to get kubectl running of Raspberry Pi 4B but both Arm64 versions here (Linux and MacOS) say:

/usr/local/bin/kubectl: cannot execute binary file: Exec format error

**Comment by sftim** [comment]
This looks like a support request. [Server Fault](https://serverfault.com/questions/tagged/kubernetes) is a better place to ask for help.

/kind support
