### ISSUE TITLE
“Overview of Cloud Native Security” page doesn't reflect CNCF-level position on security 

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33849]
**Problem:**
The page at [Overview of Cloud Native Security](https://kubernetes.io/docs/concepts/security/overview/) is now a little out of date. [Version 2 of the CNCF Cloud Native Security white paper](
https://raw.githubusercontent.com/cncf/tag-security/98fc73ae263becbe1a4fb663e438893316040107/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf ) is out, and the white paper talks about different things from Overview of Cloud Native Security.

**Proposed Solution:**
We should revise [Overview of Cloud Native Security](https://kubernetes.io/docs/concepts/security/overview/) to frame the key ideas.

The page should mention the 4 [lifecycle phases](https://raw.githubusercontent.com/cncf/tag-security/98fc73ae263becbe1a4fb663e438893316040107/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf#page=9) and how they are relevant to Kubernetes. Maybe also the layers from that diagram; it's also OK to link to the whitepaper rather than restate the same thing. Ideally, use PDF fragments to link to specific pages.

The page should mention the [security principles](https://raw.githubusercontent.com/cncf/tag-security/98fc73ae263becbe1a4fb663e438893316040107/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf#page=40):
- Secure Defaults
  - Links here could include [Apply Pod Security Standards at the Cluster Level](https://kubernetes.io/docs/tutorials/security/cluster-level-pss/) (a cluster operator needs to take steps to define which namespaces enforce secure defaults for privileges) and [Configure Default Memory Requests and Limits for a Namespace](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/)
  - There might well be other pages or topics to mention
- Least Privilege (see https://kubernetes.io/docs/concepts/security/rbac-good-practices/#least-privilege and ideally also add bidirectional hyperlinks)
- Roles and Responsibilities (clarify that these are about people, rather than the Role and ClusterRole API that aim to represent similar ideas)
- Supply Chain Security
  - link to https://kubernetes.io/docs/tasks/administer-cluster/verify-signed-images/ and https://slsa.dev/)
  - encourage readers to think about the supply chain(s) for their own workloads
- GitOps
  - Declarative
    > A system managed by GitOps must have its desired state expressed declaratively

    (maybe link to https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/)
  - Versioned and immutable
    [paraphrased] _Desired state is stored in a way that enforces immutability and versioning, retaining a complete version history._

    Outline some good practice here, maybe link to https://opengitops.dev/blog/1.0-announcement#gitops-is-more-than-just-storing-infrastructure-as-code
  - Pulled Automatically
    > Software agents automatically pull the desired state declarations from the source.

    Link to https://continuousdelivery.com/, the canonical website on the topic.
  - Continuously Reconciled
    > Software agents continuously observe actual system state and attempt to apply the desired state.

    Link to https://kubernetes.io/docs/concepts/architecture/controller/
- Zero Trust Architecture
  - Choose where to link to (_you need to decide_!)
    Example: https://glossary.cncf.io/zero_trust_architecture/
    Example: https://www.cncf.io/online-programs/zero-trust-services-in-kubernetes/
    Example: https://www.cncf.io/online-programs/zero-trust-security-for-cloud-native-apps/
- Security Stack
  - Link to https://cnsmap.netlify.app/
  - Link to https://landscape.cncf.io/?category=security-compliance&project=graduated,incubating,sandbox&company-type=&grouping=no

**Page to Update:**
https://kubernetes.io/docs/concepts/security/overview/

**Additional Information:**

This is a substantial update; we do not need much text, but the page will be quite different after this work.
I'd expect to see either the diagram from https://raw.githubusercontent.com/cncf/tag-security/98fc73ae263becbe1a4fb663e438893316040107/security-whitepaper/v2/CNCF_cloud-native-security-whitepaper-May2022-v2.pdf#page=9 copied in as-is, or no diagram. The existing diagram in [Overview of Cloud Native Security](https://kubernetes.io/docs/concepts/security/overview/) does not align with the CNCF security white paper.

/language en

/sig security
/sig docs

**Comment by sftim** [comment]
If we keep https://kubernetes.io/docs/concepts/security/overview/#cloud-provider-security we should add a third-party content disclaimer:
```markdown
{{% thirdparty-content single="true" %}}
```

**Comment by sftim** [comment]
For the table in https://kubernetes.io/docs/concepts/security/overview/#cluster-applications we could make that into a list or single column table, where the text in the first existing column becomes the text of the hyperlink.

**Comment by shannonxtreme** [comment]
Really awesome issue description Tim. I can take a stab at planning/drafting this

/assign
/triage accepted

**Comment by shannonxtreme** [comment]
The Security principles feel like they could be in a "Security best practices" doc that's separate to the main Overview. WDYT @sftim?

**Comment by sftim** [comment]
> The Security principles feel like they could be in a "Security best practices" doc that's separate to the main Overview.

Sure. Maybe a _set_ of  good practice pages; we already have https://kubernetes.io/docs/concepts/security/rbac-good-practices/

I'm sure there's room for another one about pod and nodes (linking liberally to our existing content). Maybe network security too, one day?

**Comment by shannonxtreme** [comment]
That would be awesome. Opinionated guidance targeted towards operators and admins would go a long way I think! Yes, hyperlink all the things is top of the list, lol

**Comment by sftim** [comment]
An idea (and only an idea)

https://kubernetes.io/docs/concepts/security/ could list the immediate concepts and also some curated links (fragments of pages within the security section, direct links to some authnz concepts, Pod Security admission setup). If we did that, we could organize those links by the Cloud Native security principles and add some more, similar to the issue description.

**Comment by sftim** [comment]
I'm also fine with having a page dedicated to Principles. Whichever feels like the best fit.

**Comment by shannonxtreme** [comment]
Maybe a mixed approach? I like the idea of having our Security concepts page be more recipe-ish (Secure defaults heading and links to relevant sections etc like you say). It'd be a good excuse for an audit of what security docs we have so that we can organize and consolidate them! 

And also have a principles concept page called "Good practices for cloud native security" or similar, also linked from https://kubernetes.io/docs/concepts/security/, where we consolidate the advice and dive into a bit more detail about the *why*. 

IDK if both should be in the same issue or sub-issues, though. Either works for me

**Comment by shannonxtreme** [comment]
(I also really like the idea of good practices docs overall. So yeah, good practices for cost-efficiency/resource management, RBAC, application lifecycle security, availability, network security, and so on). I suppose that'd need significant collab from SMEs in the SIGs though)

**Comment by shannonxtreme** [comment]
Instead of linking to the PDF, we might be able to link to https://cnsmap.netlify.app/develop and so on

**Comment by shannonxtreme** [comment]
I have a *very* early draft of a plan here: https://docs.google.com/document/d/1nyrl9yV9MWdsRz0b0TMPeUXtgi8QvIrguFAYRIZUnto/edit# feel free to add to it and edit it

**Comment by sftim** [comment]
> https://cnsmap.netlify.app/develop

I suspect that might not have a long lifespan, so I'm `-0` on that idea.

**Comment by sftim** [comment]
If you've any time either to work on this, or mentor other contributors a bit for their work on it, that'd be smashing @shannonxtreme

**Comment by shannonxtreme** [comment]
I think this might be a good one to mentor, because that Secrets rework is pretty hefty. I'll work on a draft plan to break this down into sub-issues that we might be able to use as good first issues/well lit pathways! Would you be ok to review that when ready?

**Comment by sftim** [comment]
@shannonxtreme happy to review that

**Comment by shannonxtreme** [comment]
@sftim [Draft of a plan here](https://docs.google.com/document/d/1PtzITDU_oOtcYoXZFnu-xmFlYgP55nmV_khSXFTLdFw/edit#)

**Comment by sftim** [comment]
Plan LGTM. Thanks.

**Comment by PushkarJ** [comment]
@shannonxtreme added a couple of comments and a suggestion. Overall looks good! Happy to help you mentor folks who are new and willing contributors for this work!

**Comment by Santosh1176** [comment]
Hey, I would love to work on this. For a start, shall I prepare a draft outline and share it on Slack for review?

**Comment by prondubuisi** [comment]
I am also interested  @PushkarJ

**Comment by sftim** [comment]
> Hey, I would love to work on this. For a start, shall I prepare a draft outline and share it on Slack for review?

For my part, I'm happy for you to do that, _or_ open a PR: pull requests don't cost anything except effort. Either is fine.
@prondubuisi, I recommend you liaise with @Santosh1176 - eg via Slack. It's OK to have 2 PRs open but the duplication of effort isn't ideal.

**Comment by Santosh1176** [comment]
> pull requests don't cost anything except effort.

Thanks for the advice. I'll start working on a draft PR.

**Comment by prondubuisi** [comment]
Sure @sftim I will leave this to @Santosh1176
