### ISSUE TITLE
Troubleshooting kubeadm

### ISSUE THREAD

**Issue by Shaik-Jahangir** [kubernetes/website#33865]
I am trying to create a kubernetes cluster using kubeadm but when i executed the kubeadm init command, the pods are going in CrashLoopbackoff state and the connection to the server is refusing. I have deployed a weave net networking dns also, even after that the pods are going in CrashLoopbackoff state. 
Can anyone please help me understand any missing configuration..
![image](https://user-images.githubusercontent.com/78128685/169634227-1445f42f-58a7-44ed-9c26-f48e071cc423.png)

**Comment by neolit123** [comment]
Hi please see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

If you think our troubleshoting documentation can be improved - PRs welcome. Thanks.

/close
/kind support
