### ISSUE TITLE
Title for “Certificates” task does not describe a task

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33866]
**This is a Bug Report**

**Problem:**
Within the [Administer A Cluster](https://kubernetes.io/docs/tasks/administer-cluster/) tasks section, the page titles describe different tasks that a cluster operator might want to perform.

However, [Certificates](https://kubernetes.io/docs/tasks/administer-cluster/certificates/) has a title that describes a concept. As a result, this page stands out from the others when you look at the list.

**Proposed Solution:**
- Pick a new title that describes a task
  - you can look at other pages for an example
- Edit that page to switch to the new title

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/certificates/

**Additional Information:**
/kind cleanup
/language en

**Comment by NitishKumar06** [comment]
Hey @sftim , I'd like to work on this issue.

**Comment by sftim** [comment]
Fixed in  #33888
/close
