### ISSUE TITLE
Ingress docs diagrams are broken

### ISSUE THREAD

**Issue by waych** [kubernetes/website#33860]
Diagrams (e.g. under "What is Ingress?", and "Simple Fanout") are not rendering at all on Chrome, and are rendering an error "Syntax error in graph  mermaid version 8.13.0" in Firefox.

https://kubernetes.io/docs/concepts/services-networking/ingress/#simple-fanout

**Comment by jihoon-seo** [comment]
Maybe relevant with:
- #31960
- #32420

**Comment by waych** [comment]
Rendering to be working reliably now for me at the moment on both FF and Chrome with the identical setup fyi, whereas I wasn't able to get any of these diagrams to render at all previously even with hard refreshes (I have not tried the cache disable nor bandwidth limitting suggested in the other thread).

**Comment by sftim** [comment]
Is this OK to close in favor of tracking the [original issue](https://github.com/kubernetes/website/issues/31960)?

**Comment by waych** [comment]
Yup.
