### ISSUE TITLE
Update network-plugins.md to reflect removed dockershim flags in 1.24.

### ISSUE THREAD

**Issue by tomkivlin** [kubernetes/website#33862]
The [network plugins](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md) page need to be updated to reflect the removed flags that happened as part of [1.24 dockershim removal](https://github.com/kubernetes/kubernetes/pull/106907).

**Comment by kris-nova** [comment]
I am curious about this. We should ideally offer a path forward for folks migrating off of configuring CNI via the Kubelet systemd unit.

As far as I can tell the entire archlinux community's kubernetes systemd units broke when we released 1.24.

I don't think we are responsible for contributin to the arch docs, however I do think having a source of truth here would be important.


Primarily:

 - Where should we be configuring CNI now that the flags are removed
 - What should the values be for the suggested systemd files (I have a list I can provide)

**Comment by sftim** [comment]
/triage duplicate

@tomkivlin are you happy to close this as a duplicate?

**Comment by tomkivlin** [comment]
> /triage duplicate
> 
> @tomkivlin are you happy to close this as a duplicate?

Yep, thanks @sftim.
