### ISSUE TITLE
Changes to website do not require Netlify preview

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#33871]
**This is a Bug Report**

**Problem:**
PR  #33842 merged even though no Netlify preview was available (none had started). This was an easy mistake to make, because Prow _usually_ insists on tests passing. However, there is a data race: if changes achieve human approval _very very_ quickly, and Prow checks pass first, a Netlify check failure doesn't block a merge.

With #33842, the issue was that Netlify had changed its configuration.

**Proposed Solution:**
Configure GitHub not to merge PRs unless the Netlify deploy preview check has passed (admins can still override that).

*Additional Information:*
Also see issues #33869 and #33867

**Comment by tengqm** [comment]
I'm not 100% sure whether this is a configuration problem. From what I have seen during the past two days, netlify preview wasn't functioning at all. There was no way to see the preview. Some other checks were not showing results either.

**Comment by sftim** [comment]
The lack of any preview was #33869 (and is resolved).

The ability to for Prow merge without a preview succeeding is different; that's _this_ issue.

**Comment by sftim** [comment]
@tengqm do you have access to manage Netlify? If not, we should make sure you have tech lead access.

**Comment by tengqm** [comment]
@sftim No, I don't have access.
