### ISSUE TITLE
Broken link to “Inter-pod topological affinity and anti-affinity” design doc

### ISSUE THREAD

**Issue by magnus-longva-bouvet** [kubernetes/website#33893]
This is regarding this section in this page: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity

`See the [design doc](https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md) for many more examples of Pod affinity and anti-affinity.`

The link to https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md is dead.

**Comment by Shubham82** [comment]
Hi @magnus-longva-bouvet 

It is not a dead link, actually, Design proposals have been archived and moved under the[ kubernetes/design-proposals-archive](https://github.com/kubernetes/design-proposals-archive/) repo, and the same mention on the page

>  see [Design Proposals Archive Repo](https://github.com/kubernetes/design-proposals-archive/)

which redirects to kubernetes/design-proposals. so nodeaffinity.md is under  design-proposals-archive/scheduling/nodeaffinity.md

**Comment by sftim** [comment]
/retitle Broken link to “Inter-pod topological affinity and anti-affinity” design doc 
/kind bug
/priority backlog
/help
/language en

**Comment by sftim** [comment]
/triage accepted

Thanks @magnus-longva-bouvet

**Comment by Shubham82** [comment]
Hi @sftim

There are also other design proposals in the docs linked to this page, see some of the following below links: 

[Configure TLS-Bootstrapping for node joining](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#configure-tls-bootstrapping-for-node-joining)
[kubeadm join phases internal design](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#kubeadm-join-phases-internal-design)
[Design Docs](https://kubernetes.io/docs/reference/#design-docs)
[OpenAPI V2](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#openapi-v2)

These are a few examples, many more are there.
so is it better to update all of them at once or not? What do you think?

**Comment by NitishKumar06** [comment]
Hey @magnus-longva-bouvet Please refer to this PR: https://github.com/kubernetes/website/pull/33926

**Comment by eminalemdar** [comment]
Hello @NitishKumar06 the changes in the PR doesn't change the link at all.

**Comment by Sea-n** [comment]
Hey, I have opened PR #34155 to fix all those links, please take a look.
- #34155

**Comment by eminalemdar** [comment]
> Hey, I have opened PR #34155 to fix all those links, please take a look.
> 
> * [Fix links for k/design-proposals-archive #34155](https://github.com/kubernetes/website/pull/34155)

Hello @Sea-n I didn't see your PR before working on these actually. I can close my PRs. thanks for mentioning.
