### ISSUE TITLE
在 macOS 系统上安装和设置 kubectl

### ISSUE THREAD

**Issue by mytting** [kubernetes/website#33907]
On the MAC, I added `source <(kubectl completion zsh)` to the `~/.zshrc` file and opened a new terminal test to find `kubectl` changed to `_kubectl`. I need to add the following configuration to the `~/.zshrc` file to make autocomplete take effect
```zsh
if [ $commands[kubectl] ]; then
source <(kubectl completion zsh)
fi
```

**Comment by tengqm** [comment]
The command is about changing the behavior of your current Shell. If you want the change to be permanent, it is different.
You will do `echo '[[ $commands[kubectl] ]] && source <(kubectl completion zsh)' >> ~/.zshrc`.

/close
