### ISSUE TITLE
Update link on version-skew-policy page

### ISSUE THREAD

**Issue by ashish-jaiswar** [kubernetes/website#33919]
### Problem:
The link of **[regular cadence](#cadence)** is changed to https://kubernetes.io/releases/patch-releases/#cadence

### Proposed Solution:
Need to replace **regular cadence** link https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#cadence  to https://kubernetes.io/releases/patch-releases/#cadence

### Page to update:
[https://kubernetes.io/releases/version-skew-policy/](https://kubernetes.io/releases/version-skew-policy/)

/kind documentation

/assign

**Comment by ashish-jaiswar** [comment]
Hi @sftim I have updated the description of issue that what need to be change.

**Comment by ashish-jaiswar** [comment]
Hi @sftim I have updated the issue description what need to be change.

**Comment by reylejano** [comment]
Fixed by https://github.com/kubernetes/website/pull/33920
/close
