### ISSUE TITLE
Query about verifying Kubernetes code other than as documented in Verify Signed Container Images

### ISSUE THREAD

**Issue by MarcoR83** [kubernetes/website#33913]
Alright this is all well and good. But how do I verify other crucial components like kubelet,  kubeadm .. which are  prerequisite for running the control plane? 

I tried somehow to verify the sbom itself https://sbom.k8s.io/v1.24.0/release but as it is stored on a regular bucket and not in a OCI registry I could not figure out how to do a keyless verification of the bom, so I can trust the hashes contained within.

https://docs.sigstore.dev/cosign/other_types

**Comment by neolit123** [comment]
hi, you can log a support issue in https://github.com/kubernetes/release or ask in #sig-release on k8s slack.
this is the issue tracker of the website.

/sig release

**Comment by sftim** [comment]
/retitle Query about verifying Kubernetes code other than as documented in Verify Signed Container Images

/kind support

We could add something to https://kubernetes.io/docs/tasks/administer-cluster/verify-signed-images/ to make it clear that not only is the task page for an alpha feature, but that alpha feature is not complete.
I think it's a low priority; a lot of users will already know that features at the alpha stage are liable to be unfinished.

**Comment by sftim** [comment]
@MarcoR83 if there are tasks you'd like to perform, please file a new feature request issue about each individual task you'd like to see documented. That way, different people can pick up different tasks.

Bear in mind that we only document possible tasks; if you want a thing documented and Kubernetes doesn't support it, we'll probably transfer the issue to become a feature request against the relevant component.
