### ISSUE TITLE
Ingress docs: Syntax error in graph

### ISSUE THREAD

**Issue by Evalle** [kubernetes/website#33912]
**This is a Bug Report**

**Problem:**
Ingress docs shows "Syntax error in graph, mermaid version 8.13.0"

**Proposed Solution:**
n/a

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/#what-is-ingress

**Additional Information:**

Firefox 100.0.2, MacOS:
![Screenshot 2022-05-24 at 11 42 12](https://user-images.githubusercontent.com/2839811/170002125-f68b6fe7-9fc9-4a26-b752-ffad7de44a72.png)

Safari, MacOS:
![Screenshot 2022-05-24 at 11 43 43](https://user-images.githubusercontent.com/2839811/170002403-d014654a-9905-4e69-9ad4-d20d9f6e0d32.png)

**Comment by NitishKumar06** [comment]
@Evalle It'd be perfect if we remove  "Syntax error....."

**Comment by sftim** [comment]
/triage duplicate

This was previously reported as https://github.com/kubernetes/website/issues/31960
@Evalle, would you be willing to close this as not planned, in favor of the original report?

**Comment by Evalle** [comment]
Hi @sftim, sure, I'm going to close this as "not planned".
