### ISSUE TITLE
Address issues from Katacoda shutdown

### ISSUE THREAD

**Issue by AlanGreene** [kubernetes/website#33918]
See announcement from O'Reilly: https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html

> As a result, we can no longer support katacoda.com for public use, and we’ll be shuttering the site on June 15, 2022

It looks like the interactive tutorials currently load resources from katacoda.com. Is there an alternative in place or some agreement with O'Reilly to continue supporting this for the Kubernetes community?

**Comment by sftim** [comment]
> Is there an alternative in place or some agreement with O'Reilly to continue supporting this for the Kubernetes community?

No, there is not. We'll need to address this.

/remove-kind bug
/priority important-soon

**Comment by sftim** [comment]
https://killercoda.com is another plausible alternative

**Comment by sftim** [comment]
/priority critical-urgent
The deadline approaches.

**Comment by wuestkamp** [comment]
Hello! I have already posted on Slack but I feel here it's more persistent :)
I'm the creator of killercoda.com. Happy to help with any issues|questions for a possible migration.
Feel free to reach me via [Email](https://github.com/wuestkamp) or [Slack](https://killercoda.com/slack).

Is there a public repo for the current Katacoda scenarios used on https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive?
I would be up helping to maintain and maybe even improve these... best with others together

**Comment by sftim** [comment]
> Is there a public repo for the current Katacoda scenarios used on https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/?

https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

**Comment by BenHall** [comment]
The content was originally created via a Web UI by Container Solutions who
also created the longer-form non-interactive content within the tutorial.

Katacoda switched from a web editor to being Git based and the content was
exported. This is why a license would be missing. My assumption is it's
apache2 with the IP ownership being the same as Kubernetes documentation.

There aren't any blockers to the Git repository being transferred to
kubernetes-sigs and has been discussed a couple of times. Let me know and I
can trigger the transfer.

**Comment by sftim** [comment]
Based on https://github.com/kubernetes/website/issues/33936#issuecomment-1145151104, there aren't any issues to address.

/remove-triage accepted
/priority awaiting-more-evidence
/remove-kind bug

**Comment by wuestkamp** [comment]
Nice that Oreilly still offers the scenarios for K8s docs! In case we still need or want to move at some point in time I imported the bootcamp scenarios on https://killercoda.com/kubernetes-bootcamp-scenarios just for a little test. With little tweaks these seem to work, but would still need a bit more love.

**Comment by AlanGreene** [comment]
Closing as I don't believe there's anything more to do here. Thanks all

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/33936#issuecomment-1346832443 about the Kubernetes-specific shutdown.
