### ISSUE TITLE
Ingress WebPage

### ISSUE THREAD

**Issue by tiago-maia** [kubernetes/website#33943]
Error displaying image in https://kubernetes.io/docs/concepts/services-networking/ingress/
after the phrase : 
"Here is a simple example where an Ingress sends all its traffic to one Service: " 

![image](https://user-images.githubusercontent.com/56874412/170310818-69e169b4-fdae-4eff-8d92-a208cfe9fe66.png)

**Comment by eminalemdar** [comment]
Hello @tiago-maia, I can see the image:
<img width="907" alt="Screen Shot 2022-05-26 at 10 51 39" src="https://user-images.githubusercontent.com/77338109/170443687-ea542d67-0fd1-435a-bf18-537ffec7cca7.png">

**Comment by tiago-maia** [comment]
Today i can see it as well , not sure what error was that , weird. I will close it :)
