### ISSUE TITLE
Problem accessing “Creating a cluster” tutorial when 3rd party ad blocker is active

### ISSUE THREAD

**Issue by cabal-chan** [kubernetes/website#33951]
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/65152862/170395708-195b3144-d6cd-4f9f-a139-50823cec1288.png">

Getting this issue when trying to run the interactive tutorial. Terminal is unresponsive. It looks like adblock is throwing this error. Turning it off works.

**Comment by sftim** [comment]
/team katacoda

/retitle Problem accessing “Creating a cluster” tutorial when 3rd party ad blocker is active
