### ISSUE TITLE
Deployment task mentions ReplicaSet without context

### ISSUE THREAD

**Issue by vsasikiran** [kubernetes/website#33957]
In **Pausing and Resuming a rollout of a Deployment** section, it is mentioned to print rollout status but the command used is replica set

**Get the rollout status:** _-> Here the command used below states replica set, the statement is not clear.  May be it can be rephrased for better readability

`kubectl get rs`
The output is similar to this:

```
NAME               DESIRED   CURRENT   READY     AGE
nginx-2142116321   3         3         3         1m
```

**Comment by sftim** [comment]
/retitle Deployment task mentions ReplicaSet without context

I'd add that `kubectl get replicaset` is more obvious to readers than `kubectl get rs`

/language en
/sig apps

**Comment by Babapool** [comment]
I have question: should `kubectl get rs`  be replaced by `kubectl get replicaset` wherever it occurs on the whole page or in the `Pausing and Resuming a rollout of a Deployment` section?. Thanks

**Comment by sftim** [comment]
I'd write `kubectl get replicaset` everywhere. We could _separately_ add a Tips section to this kind of page with hints like using the abbreviated names for kubectl.

**Comment by Babapool** [comment]
Okay, thanks. Also for a _possible_ `Tips` section we would need to create a separate shortcode for it?

**Comment by sftim** [comment]
>  for a possible Tips section we would need to create a separate shortcode for it?

How about: start a new issue about adding that section (across the site), and the discussion can happen there.
