### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by syhmc** [kubernetes/website#33975]
Cannot type anything in the Kubernetes Interactive Tutorial Terminal on either Chrome or Firefox browser.  I don't see any command prompt in the Terminal section.  Any suggestion to resolve this issue?

![image](https://user-images.githubusercontent.com/106357775/170604171-9677edd6-9d01-4746-8415-3256edb29ecd.png)

Thanks.

**Comment by reylejano** [comment]
This scenario is working for me, I've made several attempts on Mozilla Firefox and Google Chrome and all were successful
![image](https://user-images.githubusercontent.com/52760880/175451586-f838dfbc-e514-46d1-b199-45125fdb3421.png)

**Comment by syhmc** [comment]
@reylejano Thanks, just tried the Kubernetes Interactive Tutorial again and it worked now.
