### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by mohitwasnik132** [kubernetes/website#33978]
The platform seems unresponsive and un-clickable.. 
I am trying to click onto commands but they don't execute as they always do.
Continue button does not respond.
Terminal add button does not respond.
Expand button does not respond.
Settings button does not respond.

It's like a single static page loading, but when you leave or refresh it does throw warning. 
I tried different browsers. 
Firefox, Brave, Chrome. 
Same on all the browsers.

**Comment by reylejano** [comment]
I confirmed this scenario is working fine
![image](https://user-images.githubusercontent.com/52760880/175451506-260699c4-9758-4efc-93ab-92dd893913e1.png)
