### ISSUE TITLE
Command line tool (kubectl) - yaml exporting in a strange format

### ISSUE THREAD

**Issue by BrettSanderson** [kubernetes/website#33970]
Hello. I recently exported the aws-auth configmap in the kube-system namespace using the following command:
kubectl get cm aws-auth -n kube-system -o yaml > test.yaml

In my production cluster (see attached "prod-yaml" file) it doesn't export as expected.  When I do the same in my staging cluster, the file is exported as expected (see attached "stage-yaml".

Any ideas for how to fix this?  Thanks
<img width="309" alt="stage-yaml" src="https://user-images.githubusercontent.com/60189197/170523988-8aa1b1b1-215c-4d63-93f9-b58198cfdfaf.png">
<img width="468" alt="prod-yaml" src="https://user-images.githubusercontent.com/60189197/170523993-2d2eca56-73b9-4008-969c-3e4490990446.png">
!

**Comment by tengqm** [comment]
You have to know what the `|` in the `mapRoles: |` line means.

**Comment by reylejano** [comment]
`|` means block literal style which means new lines are preserved
Since this is more of a support question, I'm closing this issue
The [#kubernetes-users channel on the Kubernetes Slack](https://kubernetes.slack.com/archives/C09NXKJKA) is a good resource
