### ISSUE TITLE
Change documentation technology used for Kubernetes

### ISSUE THREAD

**Issue by CaoZhenggg** [kubernetes/website#33986]
Hello,

Is there a new documentation solution that might be used in the near future？The reading experience of the current document is really not good.

Outline cannot change width, the experience was bad in my 13' macbook.

![image](https://user-images.githubusercontent.com/23628206/170667761-884a9501-eaca-4532-89c4-e3eb33bd4f94.png)

Here is the rust book. it's concise. 

![image](https://user-images.githubusercontent.com/23628206/170666790-c6c2a2b6-68ed-4ef4-897f-85bf0da5734e.png)

**Comment by CaoZhenggg** [comment]
The Spring Boot document's experience also good.

![image](https://user-images.githubusercontent.com/23628206/170670147-8a2fbd68-2cf7-4426-b381-38cc19547d25.png)

https://docs.spring.io/spring-boot/docs/2.7.0/reference/htmlsingle/#getting-started.introducing-spring-boot

**Comment by sftim** [comment]
I wasn't sure if you were hoping for improvements to the text of the website, or the way that that text appears on the page.
/triage needs-information


@CaoZhenggg it sounds like you might be suggesting a scope of work that covers the whole website. If you're actually looking at a smaller scope, this could be a partial duplicate for (closed) issue https://github.com/kubernetes/website/issues/22788

Contributions are welcome! Only through the effort of volunteers can we make the site better.

We ([SIG Docs](https://github.com/kubernetes/community/tree/master/sig-docs)) don't have a plan either to change either the theme or to reword all the pages. However, even those plans are written by volunteers and you can be part of that too. I hope you will feel empowered to.

**Comment by sftim** [comment]
/retitle Change documentation technology used for Kubernetes

**Comment by CaoZhenggg** [comment]
You know the problem and you don't want to solve it, awesome

**Comment by dims** [comment]
@CaoZhenggg thanks for your interest. definitely don't appreciate the tone.

**Comment by tengqm** [comment]
> You know the problem and you don't want to solve it, awesome

This is always a community work. Please show your respect to others. If there are things to improve, you can contribute to it. No one is tasked to resolve **your** problem.

**Comment by CaoZhenggg** [comment]
> 

I'm sorry for my bad English. There is no disrespect for the contributions of others, but the general direction is in the hands of a few people.

**Comment by CaoZhenggg** [comment]
> > You know the problem and you don't want to solve it, awesome
> 
> This is always a community work. Please show your respect to others. If there are things to improve, you can contribute to it. No one is tasked to resolve **your** problem.

I'm sorry for my bad English. There is no disrespect for the contributions of others, but the general direction is in the hands of a few people.

**Comment by CaoZhenggg** [comment]
> @CaoZhenggg thanks for your interest. definitely don't appreciate the tone.

I'm sorry for my tone, please forgive my english.
