### ISSUE TITLE
[CKA] Container runtimes and network plugins

### ISSUE THREAD

**Issue by ThomasBucaioni** [kubernetes/website#33998]
For the CKA certification, we need to stay on kubernetes.io
Would you have an install procedure only on your website?

**Comment by sftim** [comment]
/priority awaiting-more-evidence

The documentation doesn't specifically target help with exams.
With https://github.com/kubernetes/enhancements/tree/master/keps/sig-docs/1326-third-party-content-in-docs in mind, we'll continue not to provide detailed instructions for third party network software on https://k8s.io/ and https://kubernetes.io/ (even for some _third-party OSS content for components that require a third-party solution to function_).

The main concern we have about documenting Kubernetes network plugins is the combination of:
- the need to avoid picking favorites
- the amount of effort it'd take to maintain docs for all compatible network plugins

and a similar story applies for container runtimes.

My understanding is that the CKA and similar exams are written with the policy from KEP 1326 in mind.

@ThomasBucaioni you might like to pass on feedback to the CNCF exams folks either via https://github.com/cncf/curriculum/issues/new/choose or more directly to the exams team via https://trainingsupport.linuxfoundation.org/

**Comment by ThomasBucaioni** [comment]
Thank you for your answer, I wasn't expecting one actually.

Indeed, trying to keep the documentation Cri and Cni agnostic must be a headache. But if I may, the installation procedure is not clear at all... Also, I must admit I don't like going through docs much, but I spent the last 3 days trying to make an install on two virt-manager VMs and ended up compiling procedures from IT blogs.

Set aside the certification, maybe you could have a quick and dirty install page for students with a fixed version of Kubenetes and a couple of easy Cri and Cni. If a third party complains not be mentioned, you could still ask them for a hand to send you an out-of-the-box procedure.

But well, Kubernetes is very fast moving and I understand that you can't spend so much time keeping an exhaustive up-to-date guide.

Regarding the certification, I'll see with them. After all, they probably provide template manifests if needed.

Thanks again for taking the time to answer

**Comment by sftim** [comment]
> a quick and dirty install page for students with a fixed version of Kubenetes and a couple of easy Cri and Cni

I will add that adding docs specifically to help people pass particular questions on the CKA is something I'd actively not like to see. Although the exam and docs development efforts are not particularly synchronized, we do have docs contributors who sit exams like CKA and CKAD to make sure that the tasks that are set are covered (but, when we submit PRs to fix that, we **don't** mention the motivation). We document for an audience of developers, cluster operators etc and _not_ for “people sitting exams”.

**Comment by ThomasBucaioni** [comment]
> Hi,
> 
>
> 
>
>On June 25, 2022, the Linux Foundation will transition the CKA, CKAD and CKS Programs from PSI’s ExamsLocal platform to their new proctoring platform PSI Bridge, All exams scheduled to occur on or after that date will launch on the PSI Bridge Proctoring platform.
>
> 
>
>Scheduling of the CKA, CKAD, CKS exams will be disabled between June 16, 2022 and June 24, 2022 while we complete the transition. Scheduling for these exams will resume on June 25, 2022.
>
> 
>
>Please note: There are no changes to the exam itself (i.e. no changes to the exam items), but there are changes and improvements to your user experience.
>
 >
>
> New PSI Dashboard & Features to Improve Your Experience:
> 
> Candidates will be able to start the "Take Exam" Process up to 30 minutes prior to your scheduled exam time 
> Self check-in: no need to wait for  a proctor in order to upload your ID and scan your environment
> The exam will now be taken using the PSI Secure Browser, which can be downloaded using the newest versions of  Chrome, Firefox, Safari, or Microsoft Edge 
> Multiple monitors will no longer be permitted
> Use of browser bookmarks will no longer be permitted**
>
>
> **Personal browser bookmarks (such as bookmarked links to YAML files) will not be accessible within the PSI Secure Browser. Links to CNCF documentation, considered most helpful to complete your work, have been added to a Quick Reference box within each item’s instructions. We have worked closely with the CNCF team to ensure that YAML files included in the CNCF documentation are accurate.

Fixed
