### ISSUE TITLE
Kubernetes v1.19 websites not found

### ISSUE THREAD

**Issue by Sea-n** [kubernetes/website#34009]
**This is a Bug Report**

**Problem:**
We can visit `v1.20` to `v1.23` via top-right navbar or the [Upgrading kubeadm clusters](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) article. (Which is fine)

In [previous version](https://v1-20.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) of that article, we have link to [v1.19](https://v1-19.docs.kubernetes.io/), `v1.18`, `v1.17`, `v1.16` websites.

**Proposed Solution:**
(a) Config Netlify correctly
or (b) Redirect it to https://kubernetes.io/

**Comment by sftim** [comment]
We should fix the previous version page not to link to the unsupported documentation.
Separately, we might be able to change how we serve out documentation for Kubernetes; recent Hugo has some features that might help.

Netlify is configured correctly based on the current way to serve documentation.

**Comment by sftim** [comment]
/language en
/priority backlog

There are [higher priority](https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Apriority%2Fcritical-urgent%2Cpriority%2Fimportant-soon%2Cpriority%2Fimportant-longterm+sort%3Areactions-%2B1-desc) items to work on before addressing this.
