### ISSUE TITLE
[ko] Typo in ZooKeeper tutorial doc

### ISSUE THREAD

**Issue by jangjaelee** [kubernetes/website#34011]
오타 정정 요청

https://kubernetes.io/ko/docs/tutorials/stateful-application/zookeeper/#%EB%82%B4%EA%B5%AC%EC%84%B1%EC%9E%88%EB%8A%94-%EC%A0%80%EC%9E%A5%EC%86%8C-%EC%A0%9C%EA%B3%B5

페이지의 내용 중..

WAL에 커밋하고 메모리 상태의 스냅샷을 저장 {미디에}에 주기적으로 저장한다.

영어 원문을 보면 media로 되어 있어 미디어로 정정이 필요합니다.

**Comment by jihoon-seo** [comment]
/triage accepted
/retitle [ko] Typo in ZooKeeper tutorial doc
