### ISSUE TITLE
Link to release note in older version is broken

### ISSUE THREAD

**Issue by Sea-n** [kubernetes/website#34010]
**This is a Bug Report**

**Problem:**
In [v1.23](https://v1-23.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#before-you-begin) and previous document, the "release notes" is linked to current one (v1.24).

**Proposed Solution:**
Use hard-coded link instead of `{{< latest-release-notes >}}` for frozen website.

**Page to Update:**
https://v1-23.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#before-you-begin

**Comment by neolit123** [comment]
/sig cluster-lifecycle

> Use hard-coded link instead of {{< latest-release-notes >}} for frozen website.

we could just link to https://git.k8s.io/kubernetes/CHANGELOG and let the user find the version they need.
alternatively we could add new shortcodes such as `{{< release-notes-n >}}`, `{{< release-notes-n-1 >}}`

**Comment by SaumyaBhushan** [comment]
I would like to work on this issue.

**Comment by tengqm** [comment]
fixed by #34020 
/close
