### ISSUE TITLE
ReadOnlyAPIDataVolumes feature gate missing

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#34026]
**This is a Bug Report**

**Problem:**
It seems that Kubernetes previously had a feature gate named `ReadOnlyAPIDataVolumes`; however, [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/) does not mention that feature gate.

**Proposed Solution:**
Update [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/)  to mention `ReadOnlyAPIDataVolumes`.

**Page to Update:**
~https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/~
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

**Comment by sftim** [comment]
A web page that mentions the former feature gate: https://stackoverflow.com/questions/54321991/mount-kubernetes-secret-as-a-file-with-rw-permission

**Comment by tengqm** [comment]
According to CHANGELOG:

```
CHANGELOG/CHANGELOG-1.12.md:* The feature gates `ReadOnlyAPIDataVolumes` and `ServiceProxyAllowExternalIPs`, deprecated since 1.10, have been removed and any references must be removed from command-line invocations. ([#67951](https://github.com/kubernetes/kubernetes/pull/67951), [@liggitt](https://github.com/liggitt))
```

**Comment by Kartik494** [comment]
> According to CHANGELOG:
> 
> ```
> CHANGELOG/CHANGELOG-1.12.md:* The feature gates `ReadOnlyAPIDataVolumes` and
> `ServiceProxyAllowExternalIPs`, deprecated since 1.10, have been removed and any references
> must be removed from command-line invocations. 
> ([#67951](https://github.com/kubernetes/kubernetes/pull/67951), [@liggitt](https://github.com/liggitt))
> ```

Hi @tengqm @sftim so from this reference we don't need to add `ReadOnlyAPIDataVolumes` feature gate? and if so can we close this issue ?

**Comment by mehabhalodiya** [comment]
@PriyanshuAhlawat I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @PriyanshuAhlawat

**Comment by dipesh-rawat** [comment]
@sreeram-venkitesh How's this work going?

**Comment by tamilselvan1102** [comment]
i would like to work on it.
/assign

**Comment by sftim** [comment]
Thanks @tamilselvan1102
