### ISSUE TITLE
[zh]Translate Chinese version for docs/concepts/storage/windows-storage.md

### ISSUE THREAD

**Issue by zhangxyjlu** [kubernetes/website#34032]
**This is a Feature Request**

This page docs/concepts/storage/windows-storage.md has no Chinese version

**What would you like to be added**

Translate Chinese version for docs/concepts/storage/windows-storage.md

**Why is this needed**

This page docs/concepts/storage/windows-storage.md has no Chinese version
**Comments**

/language zh
/assign

**Comment by tengqm** [comment]
/close
Instead of opening this issue, we'd open an umbrella one for all Windows pages.

**Comment by tengqm** [comment]
Please refer to https://github.com/kubernetes/website/issues/34033.
