### ISSUE TITLE
[zh] Umbrella - translate/resync Windows pages

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#34033]
There have been quite some refactoring to the Windows content in the English upstream. We need to resync those pages.

- [x] win-1  @ihuibin  #34006 
```
     169 content/en/docs/tasks/debug/debug-cluster/windows.md
```

- [x] win-2  @windsonsea   #34065
```
      83 content/en/docs/concepts/configuration/windows-resource-management.md
```

- [x] win-3  @zhangxyjlu #34036
```
      55 content/en/docs/concepts/security/windows-security.md
```

- [x] win-4   @zhangxyjlu  #34136
```
      71 content/en/docs/concepts/storage/windows-storage.md
```

- [x] win-5   @windsonsea  #34092
```
     164 content/en/docs/concepts/services-networking/windows-networking.md
```

- [x] win-6  @winsonsea  #34120
```
     384 content/en/docs/concepts/windows/intro.md
```

- [x] win-7  @howieyuen   #34110
```
     310 content/en/docs/concepts/windows/user-guide.md
```

/language zh

**Comment by windsonsea** [comment]
I can hanle all :)
/assign

**Comment by Sea-n** [comment]
Hey @zhangxyjlu, to avoid conflicted works, you should raise your hand and wait for the maintainer to approve next time.

In the above comment, @windsonsea already said they are willing to handle all the tasks, it's frustrating to see others submitted a PR for half-done works.

**Comment by zhangxyjlu** [comment]
Sorry, I just noticed, to avoid conflict, I'm withdrawing my PR@[Sea-n](https://github.com/Sea-n) @[windsonsea](https://github.com/windsonsea)

**Comment by windsonsea** [comment]
May I take the win-2, which has no conflict with others?

**Comment by tengqm** [comment]
> May I take the win-2, which has no conflict with others?

Not that I'm aware of.

**Comment by windsonsea** [comment]
Hi, I would like to take win-5, 6, and 7 if no any conflict.

**Comment by tengqm** [comment]
> Hi, I would like to take win-5, 6, and 7 if no any conflict. /assign

win-5 is yours now.

**Comment by windsonsea** [comment]
May I take win-6? Thanks.
/assign

**Comment by tengqm** [comment]
> May I take win-6? Thanks. /assign

marked.

**Comment by howieyuen** [comment]
I am working on the last one, win-7
https://github.com/kubernetes/website/pull/34110

**Comment by tengqm** [comment]
@windsonsea Please check if ‘windows/intro.md’ needs a resync?

**Comment by tengqm** [comment]
This one is done.
/close
