### ISSUE TITLE
./scripts/releng/update-release-info.sh cannot download the related images

### ISSUE THREAD

**Issue by howieyuen** [kubernetes/website#34048]
this script directly replace the whole content of content/en/releases/release.md, cause two problems:
1. lose header part, like `title` and `type` info
2. will not download the related image, now is `release-cycle.jpg` and `release-lifecycle.jpg`

shall we improve this script or leave it by human handling?

**Comment by Kartik494** [comment]
Hi @howieyuen as #34049 has been merged can we close this issue? Please let me know if anything pending on correcting scripts files.
Thanks!
