### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by madhukusu** [kubernetes/website#34053]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
I followed the steps unable to install the kubeadm. 
I am getting the below error when I tried to install specific versionof kubelet, kubectl, kubeadm
No package kubelet-1.21.9 available.
No package kubectl-1.21.9 available.
No package kubeadm-1.21.9 available

It failed for centos

**Comment by neolit123** [comment]
There should be packages available for 1.21.9. If you are getting errors try logging an issue in kubernetes/release.

/sig release
/close
