### ISSUE TITLE
Link is broken on bootstrap-tokens.md page

### ISSUE THREAD

**Issue by ashish-jaiswar** [kubernetes/website#34052]
### Problem:
The link https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/bootstrap-discovery.md is dead.
see the [Link](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/bootstrap-discovery.md) to know more about the issue.

**Proposed Solution:**

This issue has been resolved by adding a simple link and enhancing the document line.
**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/
/kind document
/assign

**Comment by tengqm** [comment]
/triage accepted

Thanks for reporting this. I'm wondering how we should fix it: pointing to the new location or removing the pointer to design docs?

**Comment by Shubham82** [comment]
Hi @tengqm 
IMO we can point it to the new location, which is kubernetes/design-proposals-archive/cluster-lifecycle/bootstrap-discovery.md
https://github.com/kubernetes/design-proposals-archive/blob/main/cluster-lifecycle/bootstrap-discovery.md

So it is easy for the readers to understand things. What do you think?

**Comment by Babapool** [comment]
This PR is fixed by #34076 . I think we can close the PR. Thanks.

**Comment by tengqm** [comment]
Since it is already fixed. This issue can be closed.
/close

**Comment by Shubham82** [comment]
> @Shubham82 My primary concern is that the design proposals usually contain too many "design" details which a user doesn't really need to understand. My other concern is that such links are fragile considering that the upstream repo may move the files again and again.

@tengqm agree with you, there are so many design links in the docs which redirect to the same page. see this [comment](https://github.com/kubernetes/website/issues/33893#issuecomment-1135497781)
