### ISSUE TITLE
Revise docs for kubernetes.io/enforce-mountable-secrets annotations

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#34054]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/labels-annotations-taints/#enforce-mountable-secrets mentions the annotation `kubernetes.io/enforce-mountable-secrets`.
However, this enforcement is _I think_ not relevant for Kubernetes v1.22 or later, as the kubelet doesn't get tokens for ServiceAccounts using the Secret API anyway.

**Proposed Solution:**
- Check with SIG Auth if that annotation should be deprecated
  - _if so_: Update [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/)
to mark the `kubernetes.io/enforce-mountable-secrets` as deprecated
  - look at other annotations in that page for an example of how to mark an annotation deprecated

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/#enforce-mountable-secrets

**Additional Information:**
Context:
https://github.com/kubernetes/kubernetes/issues/110113#issuecomment-1141455922

/language en
/lifecycle frozen

**Comment by Santosh1176** [comment]
Hey @kranurag7, I hope all is well, if you are busy with other chores can I take up and work on this issue?

@mehabhalodiya @sftim

**Comment by kranurag7** [comment]
@Santosh1176 I see this issue in the triage section [here](https://github.com/orgs/kubernetes/projects/54#card-82854900). I'm waiting for the response from the sig-auth team.

**Comment by mehabhalodiya** [comment]
> @Santosh1176 I see this issue in the triage section [here](https://github.com/orgs/kubernetes/projects/54#card-82854900). I'm waiting for the response from the sig-auth team.

@kranurag7 I will highly recommend you to post this issue (requesting triage) on the Slack #sig-auth channel, for confirmation.

**Comment by kranurag7** [comment]
Thank you @mehabhalodiya I will ask this in the respective Slack channel.

**Comment by liggitt** [comment]
The annotation is still relevant. It controls what secrets can be mounted, not just service account token secrets

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/labels-annotations-taints/#enforce-mountable-secrets says that the annotation is used on ServiceAccounts only - is that wrong? If so, was it always wrong or did that change at some point.

**Comment by liggitt** [comment]
> https://kubernetes.io/docs/reference/labels-annotations-taints/#enforce-mountable-secrets says that the annotation is used on ServiceAccounts only - is that wrong? If so, was it always wrong or did that change at some point.

That's correct. You annotate the service account, and then pods running as that service account are limited to mounting secrets included in the service account's `.secrets` list

**Comment by kranurag7** [comment]
@stfim Do we still need to update anything? The annotation is still relevant, as suggested by Jordan.
