### ISSUE TITLE
Explain why tolerationSeconds field is optional

### ISSUE THREAD

**Issue by dipankardas011** [kubernetes/website#34066]
If the tolerationSeconds is an optional property
then why, Not having it in pod in case the node is tainted as NoExecute (Pod was scheduled before Node being Tainted) will cause pod to be in bounded state forever
There must some default seconds! before it gets evicted

As mentioned in [Link of official doc](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions)
second point 

if it makes it bounded forever then it should not be optional

**Comment by dipankardas011** [comment]
![Screenshot from 2022-06-01 17-34-01](https://user-images.githubusercontent.com/65275144/171400199-243a1110-5962-4b94-a678-d1580c1cb9e7.png)
it is not waiting for tolerationSeconds

**Comment by sftim** [comment]
This looks like a mix of a support request (“why is my Pod not running when I check”) and a suggestion for the docs about taints and tolerations. We'll focus on the improvement suggestion.

For help with Pods and troubleshooting, @dipankardas011, you could try [Server Fault](https://serverfault.com/questions/tagged/kubernetes). Make sure to explain what you're doing, outline the symptoms, and include the full manifest of the Pod that you're trying to run.
