### ISSUE TITLE
CSS inconsistencies between docs/tutorials/kubernetes-basics and the rest of the pages

### ISSUE THREAD

**Issue by mtardy** [kubernetes/website#34080]
**This is a Bug Report**

**Problem:** The CSS looks different between docs/tutorials/kubernetes-basics and the rest of the website. It has its local CSS files here https://github.com/kubernetes/website/tree/main/content/en/docs/tutorials/kubernetes-basics/public/css. Maybe the main CSS diverged from the local for these pages that were integrated as a whole, see [Integrate bootcamp into Kubernetes docs. #1203](https://github.com/kubernetes/website/pull/1203), or was just different from the start. Maybe that's not really an issue, I just noticed it because of the new Katacoda warning boxes that looked really different on these page and on the rest of the website.

For example, check the CSS differences between these pages:
- https://kubernetes.io/docs/tutorials/hello-minikube/
- https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Proposed Solution:** Try to simplify the local CSS to avoid classes overrides that break the website look.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/public/css/styles.css
https://kubernetes.io/docs/tutorials/kubernetes-basics/public/css/overrides.css

**Comment by tengqm** [comment]
/triage accepted

PRs are welcomed.

**Comment by sftim** [comment]
The ideal fix is that we can remove `https://kubernetes.io/docs/tutorials/kubernetes-basics/public/css/*.css` and instead have the appropriate style declarations be a part of the main website Sass (see https://github.com/kubernetes/website/tree/main/assets/scss)

**Comment by sftim** [comment]
Fixed in #34188 
/close
