### ISSUE TITLE
Update docs to use recommended labels

### ISSUE THREAD

**Issue by TheRealDwright** [kubernetes/website#34115]
**This is a Feature Request**
Requesting that docs be updated to use the Kubernetes [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) for service objects

**What would you like to be added**

Change app: MyApp examples to app.kubernetes.io/name: MyApp

**Why is this needed**

This caused some confusion for our engineers of what the best labels are to use and these docs examples often get copy pasted, having them be aligned to recommended labels makes sense.

**Comments**

N/A

**Comment by Sea-n** [comment]
Hey @TheRealDwright,

You can use `/assign` command to assign yourself on this issue. So that others know you are working on it.
