### ISSUE TITLE
Improvement for k8s.io/docs/reference/labels-annotations-taints/

### ISSUE THREAD

**Issue by gwynforthewyn** [kubernetes/website#34119]
In the standard labels reference, there is mention of the standard node-role labels 'node-role.kubernetes.io/control-plane', 'node-role.kubernetes.io/control-plane' (for scheduling) and 'node-role.kubernetes.io/master' is noted to be deprecated.

After experimenting, it seems to me like any node has a generic 'node-role.kubernetes.io/<some role>'  that can show up in 'kubectl describe nodes'. For example, if I have a worker node worker1.example.com and run `kubectl label node/worker1.example.com node-role.kubernetes.io/foo=bar` then `kubectl get nodes` will show:

```
vagrant@control:~$ kubectl get nodes
NAME                  STATUS   ROLES                     AGE     VERSION
control.example.com   Ready    control-plane             7h35m   v1.24.1
worker1.example.com   Ready    foo                7h29m   v1.24.1
```

This 'node-role.kubernetes.io/<some role>' pattern is very extensible and shows information about the node's intended usage in an easily accessible fashion, but  I could find it referenced as an option anywhere in the kubernetes docs website. Would this page be a good candidate for accepting a note about this functionality?

**Comment by tengqm** [comment]
Please note that the first line on the page referred says this:

```
Kubernetes reserves all labels and annotations in the kubernetes.io namespace.
```

I don't think we should encourage extending 'node-role.kubernetes.io/' for any usage other than the recommended or the well-known ones. None of these extensions are guaranteed to be working in the future.

**Comment by gwynforthewyn** [comment]
Thanks for the response!

I had seen that, but my think was that when worker nodes are provisioned they have a description in `kubectl get nodes` that defaults to something uninformative, so documenting this string as an intended use-case could be useful. 

Next week I can dig unto the k8s source and see what other fields might impact `kubectl get nodes`. I’ll at a minimum report back to this issue so that future folks with the same question can benefit.

**Comment by sftim** [comment]
No report back. Those labels are reserved just as @tengqm says.

/close
