### ISSUE TITLE
Pod Security Policies

### ISSUE THREAD

**Issue by museg27** [kubernetes/website#34117]
Hi!
For the example in "policy/restricted-psp.yaml", the more restrictive value for "readOnlyRootFilesystem" would be "true" not "false".
Thank you.

**Comment by NitishKumar06** [comment]
@museg27 Please provide a referred link to the content where improvement needs to take place according to you.

**Comment by museg27** [comment]
https://kubernetes.io/docs/concepts/security/pod-security-policy/#example-policies

In the example of a restrictive policy: [policy/restricted-psp.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/policy/restricted-psp.yaml)

on the last line:
readOnlyRootFilesystem: false
should be:
readOnlyRootFilesystem: true

**Comment by sftim** [comment]
@NitishKumar06 this doesn't need my input specifically. Any contributor with understanding of the topics could comment here; folks from SIG Auth are especially likely to understand the context of the Pod Security Standards.

**Comment by sftim** [comment]
/sig auth

We should document the _actual_ restrictions that PodSecurityPolicies impose. If we want to document good practice more generally, see https://github.com/kubernetes/website/pull/33992 and similar work.
