### ISSUE TITLE
[zh] Translate /docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1/ to Chinese

### ISSUE THREAD

**Issue by javadoors** [kubernetes/website#34137]
**This is a Feature Request**

certificate signing request

**What would you like to be added**
[zh] Translate /docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1/ to Chinese

**Why is this needed**
Translate /docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1 to Chinese
Add the page: /zh/docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1/
**Comments**
NA

/assign

**Comment by NitishKumar06** [comment]
Do you want this the content to be displayed in Chinese or you want a soft copy of the document in Chinese?

**Comment by javadoors** [comment]
localization the document to chinese.

**Comment by javadoors** [comment]
Add the page: /zh/docs/reference/kubernetes-api/authentication-resources/certificate-signing-request-v1
