### ISSUE TITLE
'Service Catalog' Helm repo URL is unavailable

### ISSUE THREAD

**Issue by shizkgit** [kubernetes/website#34138]
[root@master opt]#helm repo add svc-cat https://kubernetes-sigs.github.io/service-catalog
Error: looks like "https://kubernetes-sigs.github.io/service-catalog" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-sigs.github.io/service-catalog/index.yaml : 404 Not Found

this reporegistry URL from https://kubernetes.io/zh/docs/tasks/service-catalog/install-service-catalog-using-helm/.

**Comment by jihoon-seo** [comment]
Upstream (English) page: https://kubernetes.io/docs/tasks/service-catalog/install-service-catalog-using-helm/#add-the-service-catalog-helm-repository

**Comment by shizkgit** [comment]
Thank you for your answer. I used the helm reporegistry URL in the English page, but still reported the wrong reporegistry address and couldn't find it，Looks like the reporegistry address has expired.
The error information is as follows：
[root@master ~]# helm repo add svc-cat https://kubernetes-sigs.github.io/service-catalog
Error: looks like "https://kubernetes-sigs.github.io/service-catalog" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-sigs.github.io/service-catalog/index.yaml : 404 Not Found

**Comment by jihoon-seo** [comment]
Next time you open a issue, please write the title in English!

---

I see `404 Not Found` too.
> ❯ helm repo add svc-cat https://kubernetes-sigs.github.io/service-catalog
Error: looks like "https://kubernetes-sigs.github.io/service-catalog" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-sigs.github.io/service-catalog/index.yaml : 404 Not Found

/triage accepted
/kind bug
/retitle 'Service Catalog' Helm repo URL is unavailable
/language en

**Comment by Pearl1594** [comment]
It seems that the service-catalog repo has been archived and hence been moved to kubernetes-retired - https://github.com/kubernetes-retired/service-catalog, hence the chart is available at https://kubernetes-retired.github.io/service-catalog/. So would it be fine to update the link pointing to kubernetes-retired?

**Comment by sftim** [comment]
We should remove all the documentation relating to Service Catalog.
