### ISSUE TITLE
Incorrect information regarding VolumeSnapshot API in v1.24 upcoming removals article

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/website#34143]
**This is a Bug Report**

**Problem:**
Information regarding volume snapshot API in the following blog is not accurate.
https://kubernetes.io/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/#api-removals-deprecations-and-other-changes-for-kubernetes-1-24
Volume snapshot API moved to GA in 1.20, so volume snapshot v1beta1 was deprecated in 1.20.

**Proposed Solution:**
Information regarding volume snapshot API in this blog is correct:
https://kubernetes.io/blog/2022/05/03/kubernetes-1-24-release-announcement/#csi-snapshot

Please update the API Removals Deprecations blog accordingly.

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/retitle Incorrect information regarding VolumeSnapshot API in v1.24 upcoming removals article
/area blog
/language en

What is the correct statement about the fate of the v1beta1 API for VolumeSnapshot @xing-yang? When did (or will) that API version transition from deprecated to unsupported?

**Comment by sftim** [comment]
I suspect the fix is to edit:
>  VolumeSnapshot v1beta1 was deprecated in v1.21 and is now unsupported

to:
> VolumeSnapshot v1beta1 was deprecated in v1.20 and will become unsupported once Kubernetes v1.24 is released.

Does that sound right?

/triage needs-information

**Comment by humblec** [comment]
@sftim 
Change 1:

>which provides standardized APIs design (CRDs) and adds PV snapshot/restore support for CSI volume drivers, entered beta in v1.20
>

Above has to be : [diff: `beta` to `GA`]

`which provides standardized APIs design (CRDs) and adds PV snapshot/restore support for CSI volume drivers, entered GA in v1.20.`

Change 2:

> VolumeSnapshot v1beta1 was deprecated in v1.21 and is now unsupported.

Above has to be: [diff  `v1.21 to v1.20`]

`VolumeSnapshot v1beta1 was deprecated in v1.20 ..`

**Comment by NitishKumar06** [comment]
@sftim  I completely agree with the contexts that @xing-yang has shared.

**Comment by NitishKumar06** [comment]
New PR https://github.com/kubernetes/website/pull/34173 has been raised for this issue.
