### ISSUE TITLE
Transfer Katacoda scenarios to Kubernetes

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#34140]
**This is a Feature Request**

**What would you like to be added**
Transfer https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios to the GitHub organization [`kubernetes-sigs`](https://github.com/kubernetes-sigs/).

**Why is this needed**
These scenarios are part of the Kubernetes website. It'd be great to adopt the code that defines them.

See https://github.com/kubernetes/website/issues/33918#issuecomment-1145124218 for some more context.

**Comments**
Also
/team katacoda

**Comment by NitishKumar06** [comment]
Hey @sftim , it says that I don't have permission to create a public repo in [kubernetes-sigs](https://github.com/kubernetes-sigs/
)

**Comment by NitishKumar06** [comment]
@sftim Thanks for letting me know!

**Comment by NitishKumar06** [comment]
@sftim If this issue is resolved, we can close this issue.

**Comment by sftim** [comment]
> If this issue is resolved, we can close this issue.

That's true: if it were, we could.
We haven't yet transferred those scenarios to the Kubernetes organization.

/remove-lifecycle rotten

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/33936
