### ISSUE TITLE
Translate reference/kubernetes-api/cluster-resources/event-v1.md

### ISSUE THREAD

**Issue by syxunion** [kubernetes/website#34154]
Hi, I'm interested to translate the "reference/kubernetes-api/cluster-resources/event-v1.md" page.

This is a Feature Request:

translate en/docs/reference/kubernetes-api/cluster-resources/event-v1.md into Chinese.

What would you like to be added:

zh/docs/reference/kubernetes-api/cluster-resources/event-v1.md

/language zh
/kind feature

**Comment by tengqm** [comment]
/close
Tracked in #34733
