### ISSUE TITLE
Mermaid diagram on 'Authenticating' page is unreadable

### ISSUE THREAD

**Issue by birbilis** [kubernetes/website#34167]
Diagram text looks a bit messed up on Firefox/Win11:

![image](https://user-images.githubusercontent.com/3461504/172431210-aaed9481-f52a-45e5-b66b-236ab5b54740.png)

**Comment by jihoon-seo** [comment]
Thank you for spotting the problem.
This is a duplicate of #32420.

/triage duplicate
/retitle Mermaid diagram on 'Authenticating' page is unreadable

**Comment by sftim** [comment]
I'll close this as a duplicate.
