### ISSUE TITLE
Links to design-proposals are broken

### ISSUE THREAD

**Issue by ikswdev** [kubernetes/website#34165]
[Kubernetes Protobuf serialization](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md) link is broken

**Comment by divya-mohan0209** [comment]
@ikswdev : Could you add details where you found this link broken on the website in the description of this issue? 
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/protobuf.md

**Comment by NitishKumar06** [comment]
@divya-mohan0209 I think he means that the above link is not working when we try to open it since it shows 'Page not found'. Am I guessing right? @ikswdev

**Comment by jihoon-seo** [comment]
@divya-mohan0209 I guess that the page is: 
https://kubernetes.io/docs/concepts/overview/kubernetes-api/#:~:text=Kubernetes%20Protobuf%20serialization

This issue will be resolved by the PR #34155.

/triage accepted
/kind bug

**Comment by ikswdev** [comment]
Yes.
