### ISSUE TITLE
[ja] Translate docs/concepts/workloads/controllers/job.md into Japanese

### ISSUE THREAD

**Issue by ziyi-xie** [kubernetes/website#34170]
**This is a Feature Request**

**What would you like to be added**

Japanese translation for the [docs/concepts/workloads/controllers/job.md](https://kubernetes.io/docs/concepts/workloads/controllers/job/) file

**Why is this needed**
This page has not been translated

**Comments**

/language ja
/assign

**Comment by NitishKumar06** [comment]
@ziyi-xie Do you need some help from my side to work on this issue? If Yes, I'd love to do so.

**Comment by ziyi-xie** [comment]
@NitishKumar06 Thank you so much! I'm currently working on it and haven't concurred any problem yet, but I think I might definitely need help during this process. Could I ask for your opinion or help at that time?

**Comment by NitishKumar06** [comment]
@ziyi-xie Sure, Please feel free to reach out to me for any help you require. I'd be happy !

**Comment by NitishKumar06** [comment]
Hey @Sea-n , I'm not a Japanese Speaker but I understand some words of Japanese and currently learning the language as well.
