### ISSUE TITLE
Improvement for k8s.io/docs/setup/release/version-skew-policy/

### ISSUE THREAD

**Issue by barley-benincasa** [kubernetes/website#34183]
Repeatedly now, when running `kubectl version`, I receive:

`WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew`

Problem:  I am now having trouble with a cluster in DigitalOcean, but have no idea whether the two are related.  

Moreover, how does one remedy that?  Searches have proved fruitless.  

Would be great is docs supplied some more detailed discussion.

Thanks.

**Comment by jihoon-seo** [comment]
/kind support
It seems that you could downgrade your `kubectl` to `1.22`.

**Comment by barley-benincasa** [comment]
Yes, I did think something like that.  But what I simply want is to reconcile the skew.  

That is, I read the message to mean: `X is up-to-date, Y is a version or two behind`.  I was hoping for an `update` command, akin to what `npm` has.

**Comment by sftim** [comment]
@barley-benincasa if you'd like you ask the question “is there a command to upgrade a Kubernetes cluster”, a better place to ask that might be [Server Fault](https://serverfault.com/questions/tagged/kubernetes). For another example, you could ask the question “how do I install a version of kubectl that is compatible with a v1.22 Kubernetes cluster”, or “kubectl is warning me that my client version is too new; is this a problem?”

You could also type any question you have into a search engine such as Google, or even into the search form at https://k8s.io/search/

---

_However_, you also have an opportunity to help improve the Kubernetes docs, by telling us more about what didn't work for you.

If you use that search and find that the page you then follow doesn't cover things in as much depth as you'd hoped, you're welcome to file an issue against that page you did find. Tell us what search terms you used, too - we wouldn't be able to guess.

If you don't find a page for the task that you wanted to achieve, file a new feature request:
- explain what task you wanted to achieve
- explain what you searched for
- also detail, if it makes sense, why the first few search results were not the right fit

**Comment by sftim** [comment]
I'm not sure if there's anything to fix here. @barley-benincasa could you clarify that?
