### ISSUE TITLE
Update broken link on Cluster Networking page.

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34182]
**Problem:**
The link https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/networking.md is dead.
see the text '[networking design document](https://git.k8s.io/community/contributors/design-proposals/network/networking.md).' on the [Link](https://kubernetes.io/docs/concepts/cluster-administration/networking/) to know more about the issue.

**Proposed Solution:**
This issue has been resolved by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/networking/
Update the link https://github.com/kubernetes/community/blob/master/contributors/design-proposals/network/networking.md to https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/networking.md

/kind document
/assign
/help
/language en

**Comment by tewarig** [comment]
can i work on this ?

**Comment by jihoon-seo** [comment]
@kadtendulkar @tewarig Please note that the PR #34155 is [already fixing that link](https://github.com/kubernetes/website/pull/34155/files#diff-e320028fac8208e66e6f031f7a7ddc6561b0064172ea4fd277a5050f314079ac),
so you guys don't have to work on this issue.

```diff
-[networking design document](https://git.k8s.io/community/contributors/design-proposals/network/networking.md).
+[networking design document](https://git.k8s.io/design-proposals-archive/network/networking.md).
```

**Comment by kadtendulkar** [comment]
okay, I am closing this issue.
