### ISSUE TITLE
Register and document scheduler.alpha.kubernetes.io/defaultTolerations annotation

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#34212]
**This is a Bug Report**

**Problem:**
Kubernetes has alpha support for an annotation `scheduler.alpha.kubernetes.io/defaultTolerations`; however, this is not registered or documented.

**Proposed Solution:**
- register the annotation
- document it

We can achieve both of these by updating [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) with information about the annotation.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/language en
/kind bug
/sig scheduling
/lifecycle frozen

**Comment by sftim** [comment]
See https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podtolerationrestriction for a mention of `scheduler.alpha.kubernetes.io/defaultTolerations`

**Comment by Rishit-dagli** [comment]
I could take up this and #34213
/assign
