### ISSUE TITLE
Broken link on API Priority and Fairness page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34228]
**Problem:**
The text **enhancement proposal** on [link](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#prioritylevelconfiguration) is not working and redirecting to same [page](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#whats-next), it should point to this [link](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#what-s-next)

Check the page [API Priority and Fairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control) for the problem.

**Proposed Solution:**
This issue should be resolved by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/flow-control/
Update the link on text [enhancement proposal](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#prioritylevelconfiguration) to https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#what-s-next and not this link (https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#whats-next) .

/kind document
/assign
/help
/language en

**Comment by Sea-n** [comment]
Hey @kadtendulkar, I think it's unnecessary to label as `help wanted` for this issue since you are immediately working on it.

We label an issue as `good first issue` or `help wanted` to let other contributors know what issues they can take.

**Comment by kadtendulkar** [comment]
Okay @Sea-n  i will remove help tag.

**Comment by sftim** [comment]
/retitle Broken link on API Priority and Fairness page

**Comment by sftim** [comment]
IMO, we should update the link so that it takes you to https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness and not to the “What's Next” section of the page.

**Comment by kadtendulkar** [comment]
Hello @sftim , PR of this issue is reviewed and merged. So can we again open PR for same issue?

**Comment by kadtendulkar** [comment]
Hello @divya-mohan0209 , @sftim has suggested above some changes, and since PR is merged should i create new issue and add changes or is it fine to raise PR again. ?

**Comment by divya-mohan0209** [comment]
Should be fine @kadtendulkar

**Comment by mehabhalodiya** [comment]
Thank you @kadtendulkar for your contribution 🙂 
Closing this issue as https://github.com/kubernetes/website/pull/34231 and https://github.com/kubernetes/website/pull/34261 got merged!

/close
