### ISSUE TITLE
Interactive Tutorial window not accessible

### ISSUE THREAD

**Issue by danielgangl** [kubernetes/website#34239]
After starting scenario in the the interactive tutorial the window is covered by a div with class "terminal-wait". After deleting it via developer tools the instructions are usable but the terminal itself still not.

**Comment by sftim** [comment]
/kind bug

Hi @danielgangl 
What was the URL of the web page where you saw this? Also, could you provide a screenshot?

**Comment by danielgangl** [comment]
URL: "https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/"
Screenshot:
![image](https://user-images.githubusercontent.com/46197733/173360874-e885cc1b-f871-48f3-afb9-968f339477c3.png)

**Comment by jihoon-seo** [comment]
I can see this too.

- On Google Chrome 102.0.5005.63 (64bit), Windows 10, with uBlock Origin enabled.
![image](https://user-images.githubusercontent.com/46767780/173698026-f0231a1b-fdac-4ebf-81ee-6a5fa4a88e72.png)
- This behavior persists in spite of force refresh.
- After disabling uBlock Origin, this behavior disappears, 
  and is not reproducible for some moment, even after re-enabling uBlock Origin.
