### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by Rania193** [kubernetes/website#34253]
The interactive tutorial is not working. I don't have any access to the virtual terminal or the virtual environment. Nothing is clickable.
#katacoda

**Comment by sftim** [comment]
I tried to access https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ and, for me, the interactive tutorial worked OK.

/triage not-reproducible

Perhaps this was an intermittent or short-lived outage?

**Comment by spongecaptain** [comment]
> FYI: For me using Google Chrome on Windows 10,
> 
> * with uBlock Origin enabled: terminal does not appear.
> * with uBlock Origin disabled: terminal does appear.
> 
> So @Rania193 if you are using some ad-blocker, then you might disable that and try again.
> 
> Edit: I re-enabled uBlock Origin and refreshed, and terminal does appear now. It's kind of weird, it might not be due to the ad-blocker, and now I don't find how to reproduce.

The same on mac, it is not related to os. Turn off the uBlock Origin.

**Comment by AleD219** [comment]
The bug is caused by adblockers, i had a pihole instance for dns adblocking and ublock origin enabled and disabling them resolved the problem for me.

**Comment by sftim** [comment]
Similar to https://github.com/kubernetes/website/issues/32832
