### ISSUE TITLE
[zh] Translate docs/reference/kubernetes-api/workload-resources/pod-template-v1.md

### ISSUE THREAD

**Issue by qlijin** [kubernetes/website#34270]
**This is a Feature Request**

translate docs/reference/kubernetes-api/workload-resources/pod-template-v1.md into Chinese.

**What would you like to be added**

translate docs/reference/kubernetes-api/workload-resources/pod-template-v1.md into Chinese.

**Comments**

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-template-v1/

/language zh
/kind feature
/assign

**Comment by mengjiao-liu** [comment]
page  https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-template-v1/ has been translated.

https://github.com/kubernetes/website/pull/35395 worked on it and done.
/close
