### ISSUE TITLE
Turnkey Cloud Solutions

### ISSUE THREAD

**Issue by yaraju** [kubernetes/website#34284]
None of the cards are viewable - I can only see the menus and the title that shows that there should be 1000+ cards

![Screenshot from 2022-06-14 21-55-27](https://user-images.githubusercontent.com/3163792/173628129-7564f883-ea5c-4629-bacd-8a7259e1e320.png)

**Comment by yaraju** [comment]
I finally realised that I could just click the title "Cloud Native Landscape" and then this would open up at https://landscape.cncf.io/ but this was really not obvious till I started randomly clicking around. If you really don't want to embed it properly here, please at least put a clearer link so that people know that they can see the whole page if they visit the URL directly.

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/
/triage accepted

**Comment by reylejano** [comment]
I could not reproduce, the cards are viewable
This might depend on your browser and your window size
![image](https://user-images.githubusercontent.com/52760880/175446976-64b871ab-3e8f-46c6-b3b2-ad1ef38bf108.png)
/close

**Comment by yaraju** [comment]
As of today, the [link](https://kubernetes.io/docs/setup/production-environment/turnkey-solutions/) does show the cards completely as expected.
