### ISSUE TITLE
Add Tips Section for abbreviated names of `kubectl` resources

### ISSUE THREAD

**Issue by Babapool** [kubernetes/website#34286]
**This is a Feature Request**

**What would you like to be added**

Add a _Tips_ section for  abbreviated  `kubectl` resource names/ `kubectl` commands to help users with kubectl commands based on their experience.

**Why is this needed**
Based on @sftim 's suggestion in https://github.com/kubernetes/website/issues/33957#issuecomment-1138548316 ,  it is more easy to associate (more obvious to understand) with `kubectl get replicaset` rather than `kubectl get rs` as mention in the [Deployments page](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). I think a possible solution would be if could change the docs to mention `kubectl get replica set` on the [this page](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/).  A hint/tip section could be on the page to inform users that `kubectl get rs` could also be used.

Many such abbreviations which are used: 
-  `kubectl get cm`  for `kubectl get configmaps`
- `kubectl get svc`   for `kubectl get  services`  amongst others

We can add a tips section in the documentation pages which could provide users with hints like using the abbreviated names for kubectl. (or vice versa).
**Comments**

**Comment by reylejano** [comment]
I don't know if we need a dedicated Tips section since you can run `kubectl api-resources` to get the short names

**Comment by reylejano** [comment]
This is already stated on the cheatsheet
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#resource-types
I'm going to close this issue, but you feel otherwise please reopen
