### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by drornir** [kubernetes/website#34288]
Expected:
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
<Server Version>
```

but got 
```sg
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

![image](https://user-images.githubusercontent.com/12601664/173665631-99b4ae68-d104-485f-b6f4-ff12757e5355.png)

thanks!

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
/kind support
You should have run `minikube start` in Step 1, before running `kubectl version` in Step 2.
![image](https://user-images.githubusercontent.com/46767780/173699067-6e140afb-3017-467f-bd42-8389ed28afa8.png)

**Comment by sftim** [comment]
There's nothing to fix here.
/close
