### ISSUE TITLE
Removing the overlapping text (project) from CNCF Logo

### ISSUE THREAD

**Issue by UtkarshMishra12** [kubernetes/website#34289]
**This is a Bug Report**

**Problem:**
When I was testing the responsiveness of the website I saw this bug, the word project is overlapping with the CNCF text. I'm attaching the screenshot for the same.

**Proposed Solution:**
I will be solving this by changing the CSS of the element. 

**Page to Update:**
https://kubernetes.io/
![Screenshot (374)](https://user-images.githubusercontent.com/67385503/173667539-e1ddc30b-ce7c-4193-835b-f5f024c38111.png)

**Comment by UtkarshMishra12** [comment]
@sftim  Please assign this task to me.

**Comment by NitishKumar06** [comment]
@UtkarshMishra12 You can assign it yourself by typing `/assign
`

**Comment by UtkarshMishra12** [comment]
/assign 
@NitishKumar06 So can I start working on this now?

**Comment by NitishKumar06** [comment]
Yes! @UtkarshMishra12 as you can see k8s-c--robot assigned you for this PR after you typed the `/assign`. Also, please make sure that regarding some other issues, do have a look if someone is already working on an issue under the assignee's option.

**Comment by UtkarshMishra12** [comment]
Ok, thanks for the confirmation. @NitishKumar06 
I'll keep this in my mind.

**Comment by UtkarshMishra12** [comment]
Hey, @sftim  I'm not able to find the related issue's (.html) file in the code base. Can you please guide me for the same?
Thanks

**Comment by shurup** [comment]
Hi! How this case will actually happen? Both of my browsers (Chrome and Firefox) don't allow me to make the window's width less than 450px for this page, so the overlapping never happens.

**Comment by sftim** [comment]
> Hi! How this case will actually happen? Both of my browsers (Chrome and Firefox) don't allow me to make the window's width less than 450px for this page, so the overlapping never happens.

https://www.browserstack.com/guide/enable-responsive-design-mode-in-safari-and-firefox might help with testing small viewports.

**Comment by sftim** [comment]
/priority backlog
/triage accepted

This is a backlog issue. Within that overall prioritisation, I think it's not particularly important that we fix it. If someone wants to: great!
