### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by akshat-khare** [kubernetes/website#34298]
Not able to click anything and run anything

**Comment by Babapool** [comment]
Hi @akshat-khare , are you using any ad-blocker like `uBlock Origin` while trying to access the interactive tutorial? Thanks

**Comment by Rishit-dagli** [comment]
I tried to run the tutorial on https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ , for me, the tutorial did work well; perhaps a shoer-lived outage or what @Babapool suggests?

**Comment by Kartik494** [comment]
@akshat-khare Seems running perfectly fine, and able to do task mentioned in the tutorial .
