### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by cyrilhamidechi** [kubernetes/website#34306]
Katacoda, used by the K8s online tutorials, is [not available](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html) past June 15th, 2022.

**Comment by Shubham82** [comment]
Hi @cyrilhamidechi
The banner may not be accurate and the service is expected to survive beyond June 15th, 2022. 
For reference:#34255

**Comment by cyrilhamidechi** [comment]
Thank you @Shubham82 @Rishit-dagli for your swift answer 👌 
(and happy to know katacoda service is expected to survive beyond June 15th, 2022!)

**Comment by jihoon-seo** [comment]
Since there seems no concerns left, let me close this issue.
/close
