### ISSUE TITLE
HorizontalPodAutoscaler walkthrough page recommends unnecessary container image build

### ISSUE THREAD

**Issue by aabohorquezc** [kubernetes/website#34317]
If we are using k8s.gcr.io/hpa-example as our custom image, why do the documentation starts by telling the user to build an image from Dockerfile provided and the index.php code?

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by sftim** [comment]
/retitle HorizontalPodAutoscaler walkthrough page recommends unnecessary container image build
/kind bug
/language en
/triage accepted

Thanks for reporting this.

**Comment by Rishit-dagli** [comment]
I could take this up
/assign
