### ISSUE TITLE
Connecting Applications with Services - Service naming

### ISSUE THREAD

**Issue by cyrilhamidechi** [kubernetes/website#34322]
Hi there,

In the [Securing the Service](https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#securing-the-service) section there's a slight difference between services names which make the example not working as expected.
The [Makefile](https://github.com/kubernetes/examples/blob/master/staging/https-nginx/Makefile) pointed by the link within the section is about [`nginxsvc`](https://github.com/kubernetes/examples/blob/master/staging/https-nginx/Makefile#L25) while the k8s page is about `my-nginx` service.

Best regards,

Cyril

**Comment by patrocinio** [comment]
Per the discussion with @Shubham82 , the recommendation is to remove the part that talks about reusing the Makefile and always instruct to run the steps manually.

The Makefile points to nginxsvc, and it is used in some other pages and examples. Changing the Makefile to refer to my-nginx would require a lot of changes. So, the best solution is to simplify the instructions in this page.

**Comment by sftim** [comment]
This is a duplicate I think (see above mention)
/triage duplicate
