### ISSUE TITLE
README should document the need to run `make module-init` before running `make container-serve`

### ISSUE THREAD

**Issue by patrocinio** [kubernetes/website#34339]
**This is a Feature Request**

**What would you like to be added**

The section https://github.com/kubernetes/website#running-the-website-using-a-container in the README.md describes the need to run `make container-image` and `make container-serve`. However, if I run `make container-serve`, it fails with the following message:

```
% make container-serve
WARNING Submodule not initialized: api-ref-generator
WARNING Submodule not initialized: themes/docsy
You need to run make module-init to initialize missing modules first
make: *** [module-check] Error 1
```

**Why is this needed**
The README.md should instruct the need to run `make module-init` before running `make container-serve`

**Comments**

**Comment by taniaduggal** [comment]
Hyy @patrocinio . I wanna work on this issue . Can you elaborate please what suggested changes should i make ?

**Comment by patrocinio** [comment]
Hello @taniaduggal Thanks for looking at this suggestion. We need to say that between running `make container-image` and `make container-serve`, the user needs to run `make module-init`, so I would simply add this command like this:

```
make container-image
make module-init
make container-serve
```

**Comment by sftim** [comment]
:confused: 

You don't need to run `make container-image`, and if you run `make container-serve` without running `make module-init`, the error message tells you to run `make module-init`.

**Comment by sftim** [comment]
(The change to not require running `make container-image` is recent - see https://github.com/kubernetes/website/issues/33395)

Ah, but https://github.com/kubernetes/website/pull/32100 might be relevant. Maybe you do need to build that image on architectures other than `amd64`?

**Comment by sftim** [comment]
As of 15 days ago, https://github.com/kubernetes/website#running-the-website-using-a-container _doesn't_ mention running `make container-image`.

**Comment by stormqueen1990** [comment]
Hello there, @sftim! I can confirm the need to build the image locally in arm64 architectures.

**Comment by patrocinio** [comment]
> 😕
> 
> You don't need to run `make container-image`, and if you run `make container-serve` without running `make module-init`, the error message tells you to run `make module-init`.

Hello @sftim Yes, if you run `make containe-serve`, it tells to run `make module-init`, but it fails. I would rather document the happy path than being frustrated with a failure. Thoughts?

**Comment by patrocinio** [comment]
Hello @sftim. I missed the `git submodule` step. You are right: if I run it, the `make container-serve` works fine.
Thanks!
