### ISSUE TITLE
Register and document annotation "scheduler.alpha.kubernetes.io/node-selector"

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#34333]
**This is a Bug Report**

**Problem:**
Kubernetes can recognize a Pod annotation `scheduler.alpha.kubernetes.io/node-selector`; see https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector

However, that annotation is not registered or documented.

**Proposed Solution:**
Register and document the `scheduler.alpha.kubernetes.io/node-selector` annotation.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig scheduling
/lifecycle frozen
/language en

**Comment by RA489** [comment]
@chetak123 any update on this?

**Comment by chetak123** [comment]
Yes I'll making a pr soon for this issue

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/kubernetes/issues/57424
