### ISSUE TITLE
Install and Set Up kubectl on Linux

### ISSUE THREAD

**Issue by vraghavach** [kubernetes/website#34366]
I was trying to setup a local three node Kubernetes cluster trying to following the documentation. And I think we can make it better. My comments pertain to the section `Verify kubectl configuration`. 

The explanation when you run the following command can be a lot better I think.

`kubectl cluster-info
`
**Current explanation:**
_For example, if you are intending to run a Kubernetes cluster on your laptop (locally), you will need a tool like Minikube to be installed first and then re-run the commands stated above._

That is note really helpful is it? I  think it can be phrased better or can be a more elaborate.

I am currently stuck, so I am not sure what the solution should be. But if I figure it out, I will let you guys know.

**Comment by NitishKumar06** [comment]
@zacharysarah Regarding this issue, I'm thinking of an idea. What if we include some content on how to install minikube onto your local?

**Comment by mehabhalodiya** [comment]
> What if we include some content on how to install minikube onto your local?

@NitishKumar06 You can have a look at some of the content here respective to your question: [minikube content](https://kubernetes.io/search/?q=minikube)

I believe you will find a lot of information 🙂

**Comment by mehabhalodiya** [comment]
Thank you for spotting the problem.
This is a duplicate of https://github.com/kubernetes/website/issues/27951
So @NitishKumar06 if you want to work on this subject, you can assign https://github.com/kubernetes/website/issues/27951 to yourself!

/triage duplicate
/close
