### ISSUE TITLE
Improvement for k8s.io/docs/concepts/architecture/control-plane-node-communication/

### ISSUE THREAD

**Issue by cccsss01** [kubernetes/website#34365]
link to https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/ is broken in this document.

Node to Control Plane
kubelet TLS bootstrapping

**Comment by jihoon-seo** [comment]
In the PR #33130,
the file `docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping` was moved to
`docs/reference/access-authn-authz/kubelet-tls-bootstrapping`.

So the resolution might be:
update that link to `/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/`
(https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/)

**Comment by jihoon-seo** [comment]
The PR #34382 will resolve this issue, so @taniaduggal you don't have to work on this.

**Comment by taniaduggal** [comment]
oky @jihoon-seo
