### ISSUE TITLE
TLS secret format appears to be wrong

### ISSUE THREAD

**Issue by cen1** [kubernetes/website#34362]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets

There is a Note in this section that says you should **not** include the PEM BEGIN and END lines when creating the tls secret. 
I only tested this on GKE so not sure if this is GKE not following the spec or docs being wrong.

If I generate an RSA key and cert, adding them as tls secret with `kubectl create secret tls my-tls-secret --cert=path/to/cert/file --key=path/to/key/file`

And then `kubectl get secret ...` the values have the BEGIN and END sections still present.

Similarly, if I create the tls secret **without** BEGIN and END sections, the Ingress provisioning fails with "Error 400: The SSL certificate could not be parsed., sslCertificateCouldNotParseCert". When I create it with full PEM content it works fine.

So.. I am not sure but in practice it seems the opposite what the docs say is true, at least on GKE.

**Proposed Solution:**

Remove the note from the docs.
Correct the yaml example.
Add full cert and key in the yaml example instead of truncated content, it makes it unclear whether you should format your cert/key into a single line or not (you shouldn't, it should be exact pem file content).

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets

**Comment by sftim** [comment]
I think this issue report duplicates https://github.com/kubernetes/website/issues/32869
/triage duplicate
