### ISSUE TITLE
Stamper Otomatis

### ISSUE THREAD

**Issue by Luckyazimie391** [kubernetes/website#34402]
Saya baru saja mencoba Aplikasi Luar Biasa ini yang disebut Stempel Otomatis yang dengannya saya akan dapat Mencap Tanggal dan Waktu, Tanda Tangan, Lokasi, Logo dan stempel Urutan, dll. Pada Gambar yang Saya Tangkap dari Kamera Default. Saya sangat menyukainya dan Anda juga akan menyukainya. Klik di sini untuk Mengunduh.  N  nhttp: //bit.ly/AutoStamperShare

**Comment by jihoon-seo** [comment]
The English translation of this issue is:

> I just tried this Awesome App called Auto Stamp with which I will be able to Stamp Date and Time, Signature, Location, Logo and Sequence stamp, etc. On the Image I Capture from the Default Camera. I really like it and you will like it too. Click here to Download. N nhttp://bit.ly/AutoStamperShare

It seems that this issue is not appropriate for the k/w repo.
/close
