### ISSUE TITLE
Ingress - Simple fanout section manifest missing an annotations property 

### ISSUE THREAD

**Issue by JEFFTIMES** [kubernetes/website#34413]
Hi there, 
When I tried the Simple Fanout manifest bellow in [Igress](https://kubernetes.io/docs/concepts/services-networking/ingress/) page. 
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-fanout-example
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 4200
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 8080`
the source of the code points to [here](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/simple-fanout-example.yaml)
I found it won't work without the following `annotations` property being added to the manifest

`annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /`

because without rewrite-target to root, there isn't `/foo` and `/bar` path on the service1 and service2.

hope it is correct and helpful

**Comment by kundan2707** [comment]
@JEFFTIMES  as stated by @sftim  you havent mentioned if you installed ingress controller or not. if yes then which controller.
post complete information then only someone can answer you.
