### ISSUE TITLE
Technically accurate advise, but could mislead user who skimming it in “Use a SOCKS5 Proxy to Access the Kubernetes API”

### ISSUE THREAD

**Issue by wahjava** [kubernetes/website#34419]
There is a typo:

> export https_proxy=socks5h://localhost:1080

`s/socks5h/socks5/`

EDIT: Apparently the advice is technically accurate, but I got misled as I didn't quite completely read the page.

HTH

**Comment by sftim** [comment]
/retitle Typo in Use a SOCKS5 Proxy to Access the Kubernetes API

As I understand it, `socks5h` is correct. Was there something that led you to doubt this @wahjava ?

/language en

/priority awaiting-more-evidence

**Comment by wahjava** [comment]
```
❯ env  https_proxy=socks5h://localhost:8080 kubectl --kubeconfig $HOME/.kube/myconfig --context my-cluster-one get nodes
Unable to connect to the server: proxyconnect tcp: dial tcp: lookup socks5h on 127.0.0.1:53: no such host

❯ env  https_proxy=socks5://localhost:8080 kubectl --kubeconfig $HOME/.kube/myconfig --context my-cluster-one get nodes
NAME                                     STATUS   ROLES    AGE    VERSION
....
....
```

`kubectl` version:

    Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sftim** [comment]
Ah, you've edited the _title_ (thanks). I meant to ask if you'd edit the description, which currently reads:

> There is a typo:
> 
> > export https_proxy=socks5h://localhost:1080
> 
> `s/socks5h/socks5/`
> 
> HTH

**Comment by wahjava** [comment]
Hope the latest edit is better. Sorry, I got confused between title, and the post.

**Comment by sftim** [comment]
Thanks.

/priority backlog
