### ISSUE TITLE
kubelet configuration mentions option 'enableSystemLogHandler' which lacks details

### ISSUE THREAD

**Issue by Drugoy** [kubernetes/website#34410]
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
> `enableSystemLogHandler` `bool` | `enableSystemLogHandler` enables system logs via web interface `host:port/logs/` Default: `true`

IMO the docs should mention how to access the logs via that web interface, since visiting that url gives me 'Unauthorized' response even if I specify my bearer token (that I extracted from `kubectl` config file ~/.kube/config):
```
curl -H "Authorization: Bearer ${my_token}" "https://${my_k8s_worker_node}:${kubelet_port:-10250}/logs/"
Unauthorized
```

**Comment by sftim** [comment]
The reference docs aren't really there to explain how to do a task.

If the page did exist to explain what you had in mind @drugoy, what might its title be?

/remove-kind support
/language en
/triage needs-information

**Comment by Drugoy** [comment]
I want the docs to show how to access the exposed logs via web interface.
Currently I could just claim that the option is broken and not working and there's no way to know if that is true, because the docs don't describe how exactly the logs should be exposed with that option.

**Comment by sftim** [comment]
> I want the docs to show how to access the exposed logs via web interface.

We document how Kubernetes works, for the most recent release and for a few previous releases. As Kubernetes doesn't provide a web-based **user interface** for viewing logs, we wouldn't document that.

If a third-party project provides that, it might be useful to link to the section of the CNCF [Landscape](landscape.cncf.io/) that helps you find a suitable project.

However, if you want to know how to query the internal kubelet HTTP API for fetching node logs (for example, using `curl` within a control plane debug pod), this is a something we can aim to add. Was that what you wanted?

**Comment by Drugoy** [comment]
My issue was API telling me I'm not authorized. I don't know when the behavior changed, but now I can finally access the logs well.
