### ISSUE TITLE
使用 Helm 安装 Service Catalog

### ISSUE THREAD

**Issue by piglig** [kubernetes/website#34416]
![企业微信截图_16557150412169](https://user-images.githubusercontent.com/29155962/174563569-70d9f60a-1e0f-4f2b-b13a-12123d4eec22.png)

should be adjusted to "服务目录（Service Catalog）是一种扩展 API"

**Comment by tengqm** [comment]
Not sure if we are still hosting contents related to service catalogs.

**Comment by jihoon-seo** [comment]
/language zh
The English contents related to Service Catalog will be removed in #34387.

**Comment by windsonsea** [comment]
This issue is fixed by #34660. All content related to Service Catalog are removed.
/close
