### ISSUE TITLE
Broken link in the Gateway API blog

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes/website#34424]
**This is a Bug Report**

**Problem:**
Links are broken in [this](https://kubernetes.io/blog/2021/04/22/evolving-kubernetes-networking-with-the-gateway-api/#what-does-the-gateway-api-look-like) page. It gives a 404 error.

**Proposed Solution:**
We might need to link them with [gatewayclass](https://gateway-api.sigs.k8s.io/concepts/api-overview/#gatewayclass), [gateway](https://gateway-api.sigs.k8s.io/concepts/api-overview/#gateway), and [route resources](https://gateway-api.sigs.k8s.io/concepts/api-overview/#route-resources).
Confirm once with `#sig-network-gateway-api` channel.

**Page to Update:**
https://kubernetes.io/blog/2021/04/22/evolving-kubernetes-networking-with-the-gateway-api/

/good-first-issue
/area blog
/triage accepted

**Comment by sftim** [comment]
We typically don't apply fixes to blog articles more than 1 year old. Until there's more blog editorial resource, I'm happy to continue that policy.

/remove-good-first-issue
/remove-help
/priority awaiting-more-evidence

**Comment by sftim** [comment]
/remove-triage accepted

@mehabhalodiya, should we make an exception here?
