### ISSUE TITLE
Example for liveness-command on Page "Configure Liveness, Readiness and Startup Probes" are not working

### ISSUE THREAD

**Issue by paketb0te** [kubernetes/website#34426]
I tried running the example for liveness-commands [HERE](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command), but it kept failing.

The containers logs show an issue with `/bin/sh`:

```log
$ k logs pods/liveness-exec 
/bin/sh: can't load library 'libdl.so.2'
```

[StackOverflow](https://stackoverflow.com/questions/69607005/cannot-run-executables-with-alpine-and-busybox-docker-images) pointed me into the direction of glibc / musl-libc so I tried running the exact same example on `debian:buster-slim` instead of `busybox`, which worked fine (`busybox:glibc` didn't work either).

Maybe we can update the [example](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/probe/exec-liveness.yaml) to use a lightweight image with glibc?

**Comment by patrocinio** [comment]
Hello @paketb0te Where did you see the problem running the example with busybox? It worked fine for me...

**Comment by paketb0te** [comment]
Oh, I have to apologize - it seems that this is related to the cluster I tried to run the example on!

I tried recreating it on a different cluster and encountered no issues there.

I am closing this issue and the associated PR - sorry for the noise.
