### ISSUE TITLE
Need to add link for Usage of Job to run multiple Pods in parallel in job.md 

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#34444]
**This is a Bug Report**

**Problem:**
There is no example for explaining the usage of job to run multiple Pods in parallel in the job.md.

**Proposed Solution:**
Add this link as an example - https://kubernetes.io/docs/tasks/job/coarse-parallel-processing-work-queue/

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/job/

**Comment by reylejano** [comment]
There are links to three examples in the What's next section 
/close
