### ISSUE TITLE
Add etcd required version 3.5+ in blog `API Server Tracing`

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/website#34449]
[api-server-tracing](https://kubernetes.io/blog/2021/09/03/api-server-tracing/) is an awesome blog.

It didn't mention that required etcd version is 3.5+ to support [etcd tracing](https://kubernetes.io/blog/2021/09/03/api-server-tracing/#enabling-etcd-tracing).

**Comment by sftim** [comment]
@dashpole, this was your article. I'm guessing you'd be happy with the revision but as it is a blog article I wanted to check first.

/language en
/area blog
/remove-kind support

**Comment by dashpole** [comment]
Yes, I think it would be good to update it with that detail.
