### ISSUE TITLE
Translate docs/reference/kubernetes-api/cluster-resources/lease-v1

### ISSUE THREAD

**Issue by liuzhilin12** [kubernetes/website#34441]
Hi,I am interested to translate the the "docs/reference/kubernetes-api/cluster-resources/lease-v1"

translate en/docs/reference/kubernetes-api/cluster-resources/lease-v1.md

What would you like to be added:

zh/docs/reference/kubernetes-api/cluster-resources/lease-v1.md

/language zh
/kind feature

**Comment by windsonsea** [comment]
This is fixed by #34446.
/close
