### ISSUE TITLE
[zh] Translate docs/reference/kubernetes-api/service-resources/ingress-class-v1.md

### ISSUE THREAD

**Issue by qlijin** [kubernetes/website#34440]
**This is a Feature Request**

**What would you like to be added**

Translate docs/reference/kubernetes-api/service-resources/ingress-class-v1.md

**Comments**

Link: https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-class-v1/

/language zh
/kind feature
/assign

**Comment by tengqm** [comment]
/close

This is now tracked in #34733
