### ISSUE TITLE
Improvement for k8s.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

### ISSUE THREAD

**Issue by Rodrigo010497** [kubernetes/website#34443]
what do you mean by 'to register an API, you add an APIService object, which "claims" the URL path in the Kubernetes API' ?
what do you mean by "claims" ? quoted text like this  shouldn't be used for documentation it needs to be clear what the process that is occurring is. There is no way for readers to posibly no what you mean by "claim".

**Comment by sftim** [comment]
Thanks for the suggested.

We should use italics, not quoted text, per the style guide. Also we should clearly define what we mean by this claiming process: what does the claim try to prevent from occurring, and how is that _claim_ recorded (if anywhere).

/kind cleanup
/language en
/wg api-expression
/priority backlog
/triage accepted

> There is no way for readers to posibly no what you mean by "claim".

I wouldn't go this far. Some folks will work this out. Our job as SIG Docs is to help as many people as possible to follow the document and reach a good understanding.

**Comment by Rodrigo010497** [comment]
'I wouldn't go this far. Some folks will work this out. Our job as SIG Docs is to help as many people as possible to follow the document and reach a good understanding.'
yes you are right sorry

**Comment by NitishKumar06** [comment]
@sftim May I know from where I could get information regarding what exactly 'claim' means in the above sentence?

**Comment by sftim** [comment]
@NitishKumar06 please avoid asking specific individuals for advice. Instead, you could ask a whole set of folks. For example, there are Slack channels such as `#kubernetes-users` and `#sig-auth` where you could request help.

**Comment by NitishKumar06** [comment]
Feel free to work on this issue.
/unassign
