### ISSUE TITLE
테인트(Taints)와 톨러레이션(Tolerations)

### ISSUE THREAD

**Issue by CauchyPolymer** [kubernetes/website#34481]

**Comment by jihoon-seo** [comment]
@CauchyPolymer 안녕하세요~
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/taint-and-toleration/ 페이지에서 어떤 이슈를 발견하셨는지 기재해 주시면 되겠습니다~~
/triage needs-information

**Comment by CauchyPolymer** [comment]
에고 잘못눌렀습니다 죄송합니다;;;

2022년 6월 23일 (목) 오후 5:02, Jihoon Seo ***@***.***>님이 작성:
