### ISSUE TITLE
Broken link on Localizing Kubernetes documentation page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34537]
**Problem:**
The text **All site strings** on [link](https://kubernetes.io/docs/contribute/localization/) is not working and redirecting to same [page](https://kubernetes.io/docs/contribute/localization/#Site-strings-in-i18n), it should point to this [link](https://kubernetes.io/docs/contribute/localization/#site-strings-in-i18n)

Check the page [Localizing Kubernetes documentation](https://kubernetes.io/docs/contribute/localization/) for the problem.

**Proposed Solution:**
This issue should be resolved by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/contribute/localization/
Update the link on text [All site strings](https://kubernetes.io/docs/contribute/localization/#Site-strings-in-i18n) to https://kubernetes.io/docs/contribute/localization/#site-strings-in-i18n and not this link (https://kubernetes.io/docs/contribute/localization/#Site-strings-in-i18n) .

/kind document
/assign
/language en

**Comment by sftim** [comment]
/retitle Broken link on Localizing Kubernetes documentation page

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #34538.
/close
