### ISSUE TITLE
`Validate node setup` is out of date

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#34553]
It guides users to run conformance tests with `k8s.gcr.io/node-test:0.2` which was built in 2016.

The https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md is updated.

**Comment by taniaduggal** [comment]
Hyy @pacoxu .I want to work on this issue, Could you elaborate please?

**Comment by pacoxu** [comment]
> I would guess that the page is https://kubernetes.io/docs/setup/best-practices/node-conformance/

Yes. This page is out of date. 

> The https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md is updated.

We should update according to this readme.

> Hyy @pacoxu .I want to work on this issue, Could you elaborate please?

The aim is to make https://kubernetes.io/docs/setup/best-practices/node-conformance/ a correct guide for users to run conformance test for current releases(v1.21~v1.25)

**Comment by tengqm** [comment]
Seems still relevant and not fixed.
/remove-lifecycle stale
