### ISSUE TITLE
[zh-cn] Patch-releases page is out of sync.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#34577]
Patch 1897dfba16e4654dd2887b92f92326abc9b3430f and 199c78c0f39c7d936b51c9532b1e5cb21363ebd3 has introduced some changes to the following page:

`content/en/releases/patch-releases.md`

- Contents related to 1.21 release has been removed.
- Patch schedule for July cycle has changed.

We need to resync the page.
/language zh
/help

**Comment by NitishKumar06** [comment]
@tengqm Should the new changes that were made be removed as well and restore the pages to back it was before?

**Comment by tengqm** [comment]
@NitishKumar06 Two changes are required: contents related to 1.21 should be removed; contents for next release should be added. In other words, this localized page should be in full sync with the English upstream.

**Comment by NitishKumar06** [comment]
I got it! I'm not so comfortable with the language as it is required in the file. I thought the changes were to be made in the English file. 

If anyone is willing to work on this issue, please feel free to work!

**Comment by tengqm** [comment]
@NitishKumar06 Thank you for stepping forward.
