### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/extensible-admission-controllers/

### ISSUE THREAD

**Issue by dorisyang-forever** [kubernetes/website#34575]
For the first example, when apply -f, meet a problem:
**Error from server (BadRequest): error when creating "webhook.yaml": ValidatingWebhookConfiguration in version "v1" cannot be handled as a ValidatingWebhookConfiguration: illegal base64 data at input byte 10**

How should I resolve this?

the first example:
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "example-namespace"
      name: "example-service"
    caBundle: "Ci0tLS0tQk...<`caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate.>...tLS0K"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5

**Comment by tengqm** [comment]
/kind support

The `caBundle` attribute takes a base64-encode PEM. The example shows you this.
