### ISSUE TITLE
improvement in multi-tenancy Network isolation design doc

### ISSUE THREAD

**Issue by harshchauhan1988** [kubernetes/website#34592]
Scope of improvement in below mentioned doc:

Web Page:

https://kubernetes.io/docs/concepts/security/multi-tenancy/

In a multi-tenant environment, certain use case might requires traffic to be allowed between tenant owned namespaces, be very mindful to avoid any use of _empty label selector {} for namespaceSelector field in network policy definition_  and strictly stick with specific labels which is set to namespaces.

**Comment by sftim** [comment]
Hi @harshchauhan1988 

Can you clarifying what you're suggesting / reporting? Which web page is wrong (or could be improved)? Why are you recommending the change, and what should that be - either broadly or narrowly, it's up to you.

/triage needs-information 
/language en

**Comment by harshchauhan1988** [comment]
@sftim  Thanks for asking this clarification. There is nothing wrong currently in web page. It can be improved a bit. In this below mentioned paragraph you have mentioned the highlighted recommendation:
 
`Pod-to-pod communication can be controlled using [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/), which restrict communication between pods using namespace labels or IP address ranges. In a multi-tenant environment where strict network isolation between tenants is required, **starting with a default policy that denies communication between pods is recommended** with another rule that allows all pods to query the DNS server for name resolution.`

Similarly you can add additional recommendation as mentioned below:

`Avoid using  empty label selector '{}' for namespaceSelector field in network policy definition in case traffic need to be allowed between namespaces.`

**Comment by sftim** [comment]
I'll let the multitenancy working group triage this one.

**Comment by sftim** [comment]
@harshchauhan1988 didn't say which web page to improve. I've guessed that they meant https://kubernetes.io/docs/concepts/security/multi-tenancy/

**Comment by harshchauhan1988** [comment]
closing this issue  to avoid any duplicate work as i have raised below mentioned PR:

https://github.com/kubernetes/website/pull/34624
