### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by Faarhad** [kubernetes/website#34609]
after configure cgroup driver in this page it would be better if we specify a clear step for turn swap off, this is because all the prerequisite explained but there is no description about turn swap off.
Regards,

**Comment by sftim** [comment]
@Faarhad, it seems to me that if we cater for readers who skip past

> _Swap disabled. You **MUST** disable swap in order for the kubelet to work properly._

then we can't take much for granted at all. At some point, we really do need to assume that our readers are capable of following at least the instructions in bold, capitalized text.

However, that text might actually be out of date. The kubelet has [_alpha_ support](https://kubernetes.io/blog/2021/08/09/run-nodes-with-swap-alpha/) for running with swap space enabled on Linux. I wonder what the right course of action is here.

/sig cluster-lifecycle

**Comment by neolit123** [comment]
googling `linux turn off swap` gives clean results.

```
In simple ways or the other step:
Run swapoff -a: this will immediately disable the swap.
Remove any swap entry from /etc/fstab.
Get the system rebooted. Ok, if the swap is gone. ...
Repeat steps 1 and 2 and, after that, use fdisk or parted to delete the (now unused) swap partition.
```

the swap support in k8s is currently on hold before beta.
