### ISSUE TITLE
Docs reference nonexistent command line arguments to for kube-apiserver

### ISSUE THREAD

**Issue by webdog** [kubernetes/website#34611]
**This is a Bug Report**

**Problem:**

In the kube-apiserver docs, specifically enabling RBAC, the docs reference two attributes that don't exist as part of the CLI:

```
kube-apiserver --authorization-mode=Example,RBAC --other-options --more-options
```

Specifically, `--other-options` and `--more-options` seem to mean that "other/more" options could be passed via the command line when enabling RBAC. However, the docs present these as literal attributes, and I spent 15 minutes reading the docs, the [kube-apiserver source code](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go#L90-L155), and the [go package](https://pkg.go.dev/k8s.io/apiserver/pkg/server/options) to try and figure out if these were real attributes or not. This is a bit silly, but if someone like me, who has slightly-less-than-intermediate experience with Kube gets tripped up on this, others might be experiencing the same issue.

**Proposed Solution:**

* Remove attributes that don't exist
* Note that this is a subset/single attribute of the kube-apiserver.
  * Optionally, pass all required attributes to launch the `kube-apiserver`. 
* Ensure code blocks are working commands when copy and pasted, or note that they aren't 😃 

Re: last point when passing just `--authorization-mode` I receive the following error:

```shell
W0625 23:48:27.297635     225 services.go:37] No CIDR for service cluster IPs specified. Default value which was 10.0.0.0/24 is deprecated and will be removed in future releases. Please specify it using --service-cluster-ip-range on kube-apiserver.
I0625 23:48:27.297702     225 server.go:553] external host was not specified, using 10.130.29.82
Error: [--etcd-servers must be specified, service-account-issuer is a required flag, --service-account-signing-key-file and --service-account-issuer are required flags]
```

Happy to submit a PR if y'all would like one submitted for this!

**Page to Update:**
https://docs.kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by sftim** [comment]
/retitle Docs reference nonexistent command line arguments to for kube-apiserver
/language en

How about `--example-argument` and `--another-example-argument`? Would that be more obvious?

**Comment by sftim** [comment]
We want to make it clear that in the RBAC docs, we're not going to list _all_ the mandatory command line options to `kube-apiserver` (there are a lot of them).

What we could use is a document about deploying the kube-apiserver manually. _Not_ a full, Kubernetes-the-hard-way guide, just a basic guide that makes it clear you don't get a working Kubernetes cluster even if you follow it.

Then the RBAC page can link there.

**Comment by sftim** [comment]
It's also OK to add a comment that the command is for illustration and does not work if you run it.

**Comment by webdog** [comment]
> We want to make it clear that in the RBAC docs, we're not going to list all the mandatory command line options to kube-apiserver (there are a lot of them).

Yeah that makes sense to me.

> What we could use is a document about deploying the kube-apiserver manually. Not a full, Kubernetes-the-hard-way guide, just a basic guide that makes it clear you don't get a working Kubernetes cluster even if you follow it.

I’d ❤️ to write this up. Just documenting the steps in scope of the kube-apiserver I think would be very helpful, thinking about the slip ups I had building out my cluster. Happy to lead this and open a PR once I have a level of some content written up.
.
> It's also OK to add a comment that the command is for illustration and does not work if you run it.

I agree. Scoping this potential guide to specifically configuring kube-apiserver while noting that it is one portion of a larger process to spinning up k8s seems reasonable to me.

**Comment by sftim** [comment]
@webdog for the new page about running the kube-apiserver manually: would you log two issues?

- an overall, _umbrella_ issue for the set of task pages
- an issue specifically about the task for `kube-apiserver`


You might also want to mention this work to the author of https://github.com/kelseyhightower/kubernetes-the-hard-way - Kelsey Hightower - or to eventually open a PR against KTHW that references some of the new task pages as background reading.
