### ISSUE TITLE
best practice about a system-level watchdog for the init system or a metric

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#34629]
**This is a Feature Request**
We may need NPD or a watchdog to make sure of the node's health status. 

When a node is hung, we should mark the node as not ready and do some fencing for pod or volume.

- kubelet can cover the container runtime part, but will not cover other parts.
- We wrote a BMC-power-off-drain script to check the server's power state and drain the node itself once the power will be off. (It is a little similar to node graceful shutdown except for using the BMC hardware status.)

See some discussions in https://github.com/kubernetes/kubernetes/issues/110763 and https://kubernetes.slack.com/archives/C0BP8PW9G/p1656066099576309 and https://github.com/containerd/containerd/issues/7113

**What would you like to be added**

https://kubernetes.io/docs/setup/production-environment/#production-worker-nodes
about the best practise on this  topic

**Why is this needed**
In most scanerio, user depends on systemd to create pod. However, this is not the only way. So this should be optional. 

And it is hard to check if systemd hangs. Send a `strace` to check pid 1 and if no trace would indicate the systemd hang. Not sure if it is a good way.

This will help us trigger an external corrective response (eg fencing).

**Comments**

@chenk008 suggest to add the check in https://github.com/kubernetes/node-problem-detector/blob/master/pkg/healthchecker/health_checker.go#L138. But not sure if NPD should handle this. (maybe we can open a issue in NPD as well)

**Comment by sftim** [comment]
https://0pointer.de/blog/projects/watchdog.html explains a _systemd_ facility to detect and handle a hang.
