### ISSUE TITLE
Trouble accessing interactive tutorial using Mozilla browser

### ISSUE THREAD

**Issue by Omar-EM** [kubernetes/website#34626]
Hi, I came across this screen when starting an interactive tutorial. I can't see any readable text displayed.
I am using Mozilla on mac

![text not clear interactive tuto](https://user-images.githubusercontent.com/93885736/175831429-6179965a-bc07-4a2b-a4fc-f4c153c7612d.png)
.

**Comment by sftim** [comment]
/kind bug

With which web browsers can you reproduce this, @Omar-EM ?

**Comment by Omar-EM** [comment]
I've only tried in Mozilla and Safari. Safari is working fine.

**Comment by sftim** [comment]
/retitle Trouble accessing interactive tutorial using Mozilla browser

**Comment by Omar-EM** [comment]
I downloaded the latest version of Firefox, I even disabled some add-ons. Still not working.

**Comment by shurup** [comment]
I'm using the same version of Firefox (102.0) on Ubuntu Linux, so the version is `102.0+build2-0ubuntu0.18.04.1` (installed from `bionic-updates/main`), to be precise. Everything is okay for me in [this tutorial](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/).

![image](https://user-images.githubusercontent.com/1560718/179444297-99d9874c-90c7-4074-bf25-947f1a74d550.png)

**Comment by sftim** [comment]
So far this doesn't seem to be reproducible
/triage not-reproducible

If this is definitely not a bug in Firefox, and we can get evidence about how to reproduce it, we'll happily triage the report as accepted.

**Comment by sftim** [comment]
Which version of macOS are you running Firefox on, @Omar-EM ? If you're happy to, go to `about:support` (it's a pseudoURL), find the Graphics section of that report, and also paste that table into the issue.
