### ISSUE TITLE
./scripts/lsync.sh cannot sync files under zh-cn correctly.

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/website#34633]
**This is a Bug Report**
./scripts/lsync.sh cannot sync files under `zh-cn` correctly.

This problem should exist with  $LOCALIZED more than 2 characters.

** When happened
when zh -> zh-cn
see https://github.com/kubernetes/website/pull/34215

**Proposed Solution:**
`./scripts/lsync.sh` needs to be updated

```
EN_VERSION=`echo $LOCALIZED | sed "s/content\/..\//content\/en\//g"`
```
to
```
EN_VERSION=`echo $LOCALIZED | sed "s/content\/.\{2,5\}\//content\/en\//g"`
```

/cc @temnqm @howieyuen 
/language zh

**Comment by mengjiao-liu** [comment]
I found this problem when reviewing this PR https://github.com/kubernetes/website/pull/34556/files, the commit time of the `en` version is later than the `zh-cn` version, but `./script/lsync` did not correctly find the difference between the 2 versions.

**Comment by howieyuen** [comment]
nice catch!
