### ISSUE TITLE
Fix the link on Release Managers page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34647]
**Problem:**
The text **schedule and cadence for patch releases** on [link](https://kubernetes.io/releases/release-managers/) is not pointing to the exact section and redirect to the [page](https://kubernetes.io/patch-releases.md), it should point to this [link](https://kubernetes.io/releases/patch-releases/)

Check the page [Release Managers](https://kubernetes.io/releases/release-managers/) for the problem.

**Proposed Solution:**
This issue should be resolved by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/releases/release-managers/
Update the link on the text schedule and cadence for patch releases to https://kubernetes.io/releases/patch-releases/ and not this link (https://kubernetes.io/patch-releases.md).

/kind document
/assign
/language en

**Comment by divya-mohan0209** [comment]
triage/accepted
