### ISSUE TITLE
[ko] Fix a translation error in docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

### ISSUE THREAD

**Issue by henjoon** [kubernetes/website#34667]
**This is a Bug Report**

**Problem:**
애그리게이션 레이어는 [사용자 정의 리소스](https://kubernetes.io/ko/docs/concepts/extend-kubernetes/api-extension/custom-resources/)와는 다르며, 애그리게이션 레이어는 [kube-apiserver](https://kubernetes.io/ko/docs/concepts/overview/components/#kube-apiserver) 가 새로운 종류의 오브젝트를 인식하도록 하는 방법이다.

**Proposed Solution:**
애그리게이션 레이어는 [kube-apiserver](https://kubernetes.io/ko/docs/concepts/overview/components/#kube-apiserver) 가 새로운 종류의 오브젝트를 인식하도록 하는 방법인 [사용자 정의 리소스](https://kubernetes.io/ko/docs/concepts/extend-kubernetes/api-extension/custom-resources/)와는 다르다.

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

**Comment by jihoon-seo** [comment]
[en]
> The aggregation layer is different from [Custom Resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), which are a way to make the [kube-apiserver](https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver) recognise new kinds of object.

/triage accepted

**Comment by seokho-son** [comment]
Hi @henjoon 

I am one of the approvers for Korean localization.
We generally assume that the author of Issue has a high priority to be the assignee.

Even though @bishal7679 self-assigned and opened a PR, I hope to check your (@henjoon) willingness to resolve this issue first. @bishal7679 Sorry for inconvenience but this kind of workflow is important for opensource project. :)

**Comment by hjkim522** [comment]
Hi @seokho-son,
I am okay with assigning the issue to @bishal7679.
And thank @bishal7679 for the fast action.

**Comment by henjoon** [comment]
Hi @seokho-son,
I am okay with assigning this issue to @bishal7679,
and thanks @bishal7679 for handling the issue quickly.
