### ISSUE TITLE
Configure Access to Multiple Clusters: link to Katacoda is no longer valid

### ISSUE THREAD

**Issue by gmacario** [kubernetes/website#34662]
The page linked from "Katacoda" (<https://www.katacoda.com/courses/kubernetes/playground>) on page <https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/> returns

![image](https://user-images.githubusercontent.com/75182/176152929-4ffc384e-c3ea-4986-bdaa-828d691b426d.png)

**Comment by NitishKumar06** [comment]
This [PR](https://github.com/kubernetes/website/pull/34496) actually fixes this issue. We have tried to remove Katacoda and replaced it with [Killercoda](https://killercoda.com/playgrounds). That PR is under review . Although the changes look good according to @reylejano .

**Comment by sftim** [comment]
Duplicate of issue https://github.com/kubernetes/website/issues/34428

/triage duplicate

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #34429.
/close
