### ISSUE TITLE
Add clarification about API resources to the Style Guide

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#34666]
## Description

Kubernetes uses the word "resource" to refer to API resources, such as `pod`, `deployment`, and so on. We also use "resource" to talk about CPU and memory requests and limits.

Update the [Style guide](https://kubernetes.io/docs/contribute/style/style-guide/#documentation-formatting-standards) with a new section to clarify how we talk about API resources in our documentation. 

## What should you do? 

1.  [ ] Add a new section under _Documentation formatting standards_ called "Referring to Kubernetes API resources" (or similar).
2. [ ] In your new section, add guidance for the following (use a combination of paragraphs and bulleted lists):
    *  Differentiate between an HTTP API resource and a CPU/memory resource (you can use the first line of this issue description)
    *  Differentiate between Kubernetes API terminology and when to use:
        *  **Resource type**: the name used in the API URL (such as `pods`, `namespaces`)
        *  **Resource**: a single instance of a resource type (such as `pod`, `secret`)
        *  **Object**: a resource that serves as a "record of intent". An object is a desired state for a specific part of your cluster, which the Kubernetes control plane tries to maintain.
    *  Add a rule to always mention "resource" or "object" when referring to an API resource in docs. For example, use "a `Secret` object" over just "a `Secret`".
    * Add a rule to always format API resource names with PascalCase and `code formatting`. (link users to https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects and https://kubernetes.io/docs/contribute/style/style-guide/#code-style-inline-code for full guidance)
3. [ ] Review other API sections on the page to remove duplicate content or conflicting guidance. For example, https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects has the following, which can be moved and merged into your new section:

    ```
    You may use the word "resource", "API", or "object" to clarify a Kubernetes resource type in a sentence.

    Don't split an API object name into separate words. For example, use PodTemplateList, not Pod Template List.
    ```
4. [ ] Link to https://kubernetes.io/docs/reference/using-api/api-concepts/#standard-api-terminology for more information at the end of the section.

/sig docs
/help-wanted
/cc @sftim

**Comment by Rishit-dagli** [comment]
I could take this up
/assign

**Comment by debdeepsanyal** [comment]
@Rishit-dagli have you completely solved this issue?

**Comment by mehabhalodiya** [comment]
> @Rishit-dagli have you completely solved this issue?

@debdeepsanyal Yes, the pointers mentioned in the issue description have been addressed in the linked PR above.
Kindly pick up another `good first issue`. Thanks for showing your interest 🙂
