### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by MyKarpenko** [kubernetes/website#34678]
please add vim configuration ASAP
The new exam platform really needs it

just this

Create your ~/.vimrc (otherwise indentation will be messed up):

set expandtab

set tabstop=2

set shiftwidth=2

**Comment by MyKarpenko** [comment]
an alias k=kubectl is also a more  linux documentation trick and it is documented in kubernetes docs
I believe this is the same essential not for just exam sake but for any person setting the working environment up

**Comment by sftim** [comment]
> an alias k=kubectl or bash completion are also a more Linux documentation trick and it is documented in kubernetes docs

`kubectl` is part of Kubernetes.
`vim` is not part of Kubernetes. We don't document how to set up vim or other text editors. See https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed
