### ISSUE TITLE
Audit Configuration docs sentence incomplete

### ISSUE THREAD

**Issue by calebschoepp** [kubernetes/website#34671]
Something missing the sentence from the audit configuration documentation.

> NonResourceURLs is a set of URL paths that should be audited. s are allowed, but only as the full, final step in the path. Examples: "/metrics" - Log requests for apiserver metrics "/healthz" - Log all health checks

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/20216739/176254605-63c9d9d4-db09-4092-8fef-17f82c2c6871.png">

**Comment by tengqm** [comment]
The docs are generated from upstream source code comments. Some comments have weird syntax that are difficult to parse as markdown. These problems have to be fixed upstream.

In fact, I have proposed a fix to the upstream (https://github.com/kubernetes/kubernetes/pull/110354). The PR has been hanging there for almost 4 weeks, no feedbacks, no reviews, no merge...
