### ISSUE TITLE
Provide the website serving container from a registry in more architectures

### ISSUE THREAD

**Issue by stormqueen1990** [kubernetes/website#34704]
**This is a Feature Request**

**What would you like to be added**

As of early June, the build of a local container image is not required anymore, as the website serving container is now available from a registry. However, the available image is built only for the amd64 architecture.

I would like to propose a change to the current build process in order to include the arm64 architecture as well. This could be done using `docker buildx`, similar to what the ingress-nginx project currently uses: https://github.com/kubernetes/ingress-nginx/blob/9baaae1d4e827c5bc1ff233d35c63be6f63399a2/images/nginx/Makefile#L36.

**Why is this needed**
Provide a better contributor experience to people that use machines with arm64 architecture.

**Comment by sftim** [comment]
It's a good idea.

/kind feature
/priority backlog
/sig docs
/triage accepted

**Comment by sftim** [comment]
#38245 may have fixed this. @stormqueen1990 can you verify that it has?

**Comment by sftim** [comment]
One more thing? https://github.com/kubernetes/website/pull/38285#discussion_r1041663058
