### ISSUE TITLE
The text in the nodes of the svg image is not readable

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#3470]
**This is a...** 
- [x ] Bug Report

**Problem:**

On this page: https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/

The text (white font on blue background) in the nodes of the svg image is not readable

Here is the source: https://kubernetes.io/docs/tutorials/kubernetes-basics/public/images/module_01_cluster.svg

**Proposed Solution:**

Enlarge the text in the svg or remove it, if it is not important.

**Page to Update:**

https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/

My browser: Build-Identifikator: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by ahmetb** [comment]
@steveperry-53 do you know who maintains the bootcamp tutorial?

**Comment by jaredbhatti** [comment]
Ping?  I thought Katacoda owned it.

**Comment by ahmetb** [comment]
@jaredbhatti who can make this SVG image more legible for us
