### ISSUE TITLE
Error: failed to parse kubelet flag: unknown flag: --network-plugin

### ISSUE THREAD

**Issue by ramakrpr** [kubernetes/website#34755]
Hi,

I have a running cluster with version as below
GitVersion:"v1.24.2",

what is the solution for the CNI changes in this version for running clusters that are throwing errors for --network-plugin flags? i cant seem to find any way to fix the running clusters. 
2 of my clusters are apparently down due to this and cant seem to figure out how to fix

I have tried changing the file /var/lib/kubelet/kubeadm-flags.env to below and still doesnt help

KUBELET_KUBEADM_ARGS="--pod-infra-container-image=k8s.gcr.io/pause:3.5"
KUBELET_NETWORK_ARGS=''

**Comment by sftim** [comment]
This looks like a support request. See https://git.k8s.io/kubernetes/SUPPORT.md

/remove-kind bug
/kind support

**Comment by ramakrpr** [comment]
Related to the issue https://github.com/kubernetes/website/issues/33640
Documentation is updated and merged but what about running clusters? what can be done?

**Comment by sftim** [comment]
As that link explained, **GitHub is not the right place to get support for using Kubernetes**.

@ramakrpr my advice would be to ask your question on [Server Fault](https://serverfault.com/). You could also search the documentation.

**Comment by divya-mohan0209** [comment]
Hello @ramakrpr , thank you for flagging the issue. As @sftim mentioned, this is not an issue related to Kubernetes documentation. From the discussion, it seems you need support for using Kubernetes. Please route your questions to [Server Fault](https://serverfault.com/) or related communities and seek out support.
