### ISSUE TITLE
Minor typo in https://kubernetes.io/blog/2022/02/17/dockershim-faq/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#34754]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/blog/2022/02/17/dockershim-faq/ has a typo, “incluides”

**Proposed Solution:**
Fix the typo (it should read “includes”)

**Page to Update:**
https://kubernetes.io/blog/2022/02/17/dockershim-faq/

**Additional Information:**
/language en
/area blog
/priority backlog
/triage accepted
/good-first-issue

**Comment by sftim** [comment]
I've marked this as a good first issue. If you're a contributor who has already submitted PRs for the [k/website](https://github.com/kubernetes/website) repo, consider leaving this one to let a new contributor work on it.

**Comment by sftim** [comment]
Whether new to contributing to the Kubernetes docs, or have already made contributions, it's OK to ask questions. Check https://kubernetes.io/docs/contribute/ for a guide on how to contribute.

**Comment by shivam-sharma7** [comment]
Okay

**Comment by Kwazimolo** [comment]
> /assign
> 

@ritikaaaa177 ive already submitted the PR for this one

**Comment by ritikaaaa177** [comment]
@Kwazimolo yeah i saw it

**Comment by Sugarlust** [comment]
Is this issue still up for grabs?

**Comment by Kwazimolo** [comment]
Fixed #34760
