### ISSUE TITLE
Use kubeadm for GCE installation guide

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#3475]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:** https://kubernetes.io/docs/getting-started-guides/gce/ uses old `wget -q -O - https://get.k8s.io | bash` method...

**Proposed Solution:** It should use `kubeadm` to create the Google Compute Engine cluster.

(self-assign)

**Comment by craigbox** [comment]
https://github.com/kubernetes/kubernetes/issues/34949 talks about how to get the networking set up.
