### ISSUE TITLE
Documentation for enableServiceLinks needs to be moved or referenced 

### ISSUE THREAD

**Issue by StingyJack** [kubernetes/website#34761]
The page at https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

Needs to have the information for `enableServiceLinks` that is visible here https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service

**Comment by NitishKumar06** [comment]
@StingyJack Where would you like to see the link (https://github.com/kubernetes/website/issues/34756#issue-1291383994) added - after which paragraph / line ?

**Comment by StingyJack** [comment]
Probably in a "How to disable this behavior" section before the "Whats next"  section.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/ is about the _downward API_.

I think it's reasonable to hyperlink to https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service
/triage accepted
/priority backlog

If this issue goes stale, it doesn't feel like it's be a priority to keep it alive.

**Comment by NitishKumar06** [comment]
@sftim Do you mean we should try to add a little documentation in https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/ to hyperlink https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service ?

**Comment by sftim** [comment]
>  Do you mean we should try to add a little documentation in https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/ to hyperlink https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service ?

Yes, I do mean that.

**Comment by divya-mohan0209** [comment]
The link as mentioned in [this comment by @sftim](https://github.com/kubernetes/website/issues/34761#issuecomment-1201501612) by @nitishfy through #40643 and I'll be closing the issue as completed.
