### ISSUE TITLE
Create documentation on kubectl bash completion

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#3476]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:** There are no easily-findable docs on "kubectl bash completion". This query doesn't return any documentation.  This leads to blog posts such as: 
- https://blog.fabric8.io/enable-bash-completion-for-kubernetes-with-kubectl-506bc89fe79e 
- https://blog.merapar.com/fixing-bash-autocompletion-on-macos-for-kubectl-and-kops-e87f019652e8

**Proposed Solution:** Write a new doc that shows how to enable bash/zsh completion for kubectl. I just scraped the following existing snippet from https://kubernetes.io/docs/getting-started-guides/gce/ but it's not great and doesn't belong there.

```
#### Enabling bash completion of the Kubernetes command line tools

You may find it useful to enable `kubectl` bash completion:

* If you're using kubectl with Kubernetes version 1.2 or earlier, you can source the kubectl completion script as follows:<br>

  $ source ./contrib/completions/bash/kubectl


* If you're using kubectl with Kubernetes version 1.3, use the `kubectl completion` command as follows:<br>

  $ source <(kubectl completion bash)


**Note**: The above commands will last for the duration of your bash session. If you want to make this permanent you need to add corresponding command in your bash profile.

Alternatively, on most linux distributions you can also add a completions file to your bash_completions.d as follows:

* For kubectl with Kubernetes v1.2 or earlier:<br>

  $ cp ./contrib/completions/bash/kubectl /etc/bash_completion.d/


* For kubectl with Kubernetes v1.3:<br>

  $ kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl


but then you have to update it when you update kubectl.
```

**Comment by ahmetb** [comment]
I wonder why this section doesn't show up on search results https://kubernetes.io/docs/tasks/kubectl/install/#enabling-shell-autocompletion

**Comment by jaredbhatti** [comment]
Any further work to do here?

**Comment by ahmetb** [comment]
@jaredbhatti yeah I'll probably refactor the existing section to add:

- on Linux using ZSH
- on Linux/macOS using oh-my-zsh

**Comment by tengqm** [comment]
looks like the issue has been fixed just forgot to be closed.
