### ISSUE TITLE
[zh-cn] Translate /docs/concepts/security/multi-tenancy/ to Chinese

### ISSUE THREAD

**Issue by javadoors** [kubernetes/website#34798]
**This is a Feature Request**
[zh-cn] Translate /docs/concepts/security/multi-tenancy/ to Chinese

**What would you like to be added**
The page: zh-cn/docs/concepts/security/multi-tenancy/

**Why is this needed**
Translate /docs/concepts/security/multi-tenancy/ to Chinese

**Comments**
NA

/language zh
/assign

**Comment by mengjiao-liu** [comment]
#34821 has been merged, so we can close it.
