### ISSUE TITLE
Interactive Tutorial - Scaling Your App

### ISSUE THREAD

**Issue by EzzEddin** [kubernetes/website#34809]
In module 5: Step 2: Load Balancing

We need to expose the service first because last time we interacted with the Kubernetes service was when we deleted it.

So before the `describe` command, we need to do `expose` to the Deployment like this:

```bash
kubectl expose deployments/kubernetes-bootcamp --type="NodePort" --port 8080
```

**Comment by jihoon-seo** [comment]
@EzzEddin 
It seems that
- each module, I mean Module 4 and Module 5, is independent to each other.
- when you launch a test Katacoda env for the Module 5, some predefined objects are created & configured from scratch, including the NodePort Service for `kubernetes-bootcamp`.
  I can check this with running `kubectl get svc -A` right after launching a test Katacoda env for the Module 5:

```
$ kubectl get svc -A
NAMESPACE              NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default                kubernetes                      ClusterIP   10.96.0.1        <none>        443/TCP                  15s
default                kubernetes-bootcamp             NodePort    10.104.238.221   <none>        8080:30676/TCP           12s
kube-system            kube-dns                        ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   14s
kube-system            metrics-server                  ClusterIP   10.103.54.239    <none>        443/TCP                  10s
kubernetes-dashboard   dashboard-metrics-scraper       ClusterIP   10.99.179.40     <none>        8000/TCP                 9s
kubernetes-dashboard   kubernetes-dashboard            ClusterIP   10.106.239.112   <none>        80/TCP                   9s
kubernetes-dashboard   kubernetes-dashboard-katacoda   NodePort    10.103.151.123   <none>        80:30000/TCP             8s
```

- And I was able to go through all steps in Module 5 as-is without any error.
- Per your suggestion, when I execute `kubectl expose deployments/kubernetes-bootcamp --type="NodePort" --port 8080`
  before running `kubectl describe services/kubernetes-bootcamp`,
  it returns 'already exists' error:

```
$ kubectl expose deployments/kubernetes-bootcamp --type="NodePort" --port 8080
Error from server (AlreadyExists): services "kubernetes-bootcamp" already exists
```

So IMO we don't need to add the command `kubectl expose deployments/kubernetes-bootcamp --type="NodePort" --port 8080`
to the 'Interactive Tutorial - Scaling Your App'.
What do you think about this?

**Comment by EzzEddin** [comment]
@jihoon-seo Yup, I agree that we don't need to add that command after your explanation. Thanks!

I was just following up with these modules on my machine using `minikube` and `kubectl`. So I had to recreate the service because it was not ready as in the Katacoda environment.

Anyway, I used my machine (not the interactive k8s lab playground) because it was hard for me to follow up with the description (on the left screen) and apply on the terminals (on the right). Maybe we can take this as a piece of feedback to make the playground more appealing, or maybe make the reader aware of the best setup to follow along with the playground and the explanation. For example, I couldn't control the screen to be resized to the full width of the screen (and get rid of the TOC on the left).

**Comment by jihoon-seo** [comment]
@EzzEddin Okay I got it.

> it was hard for me to follow up with the description (on the left screen) and apply on the terminals (on the right).

Just in case you are not familiar with Interactive Tutorials in k8s.io website:
![image](https://user-images.githubusercontent.com/46767780/177288626-0dcadd7f-1fcc-42fe-be8f-4f60a7749528.png)

PTAL. 😊

**Comment by EzzEddin** [comment]
@jihoon-seo Yes, I knew that feature. I was also clicking on the command to open a new terminal when I ran `kubectl proxy` command.

The problem is that I couldn't control the width of both screens. I was just able to maximize the right screen but not able to maximize the left screen as well to follow along with the explanation.
