### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by mirzayevelshan** [kubernetes/website#34819]
envFrom option must write with "-"

**Comment by NitishKumar06** [comment]
Please share the link of the page to be updated.
/assign

**Comment by Shubham82** [comment]
Page: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

Hi @mirzayevelshan  But the example is correct. and it is working. the envFrom option is already started with "-"

```
envFrom:
- configMapRef:
    name: special-config
```
could you please tell where you want to do the changes?

**Comment by Shubham82** [comment]
Hi @mirzayevelshan 
if no more queries can we close this issue?

**Comment by Shubham82** [comment]
Closing this issue, As there is no problem with it.

/close
