### ISSUE TITLE
kubeadm: missing artifact mode in upgrade docs

### ISSUE THREAD

**Issue by mel1nn** [kubernetes/website#34829]
## FEATURE REQUEST

According to the installation documentation, we can install kubeadm **Without a package manager** and using the tar.gz file, but in the upgrade documentation, this mode is not proposed.

**Comment by neolit123** [comment]
/retitle kubeadm: missing artifact mode in upgrade docs

**Comment by taniaduggal** [comment]
I would like to work on this issue, could you elaborate please and how can I work on this issue?

**Comment by RA489** [comment]
https://github.com/kubernetes/website/issues/34829
