### ISSUE TITLE
Fix the broken link on Running ZooKeeper, A Distributed System Coordinator page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34832]
**Problem:**
The text [**ZooKeeper**](https://www-us.apache.org/dist/zookeeper/stable/) on [link](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/) is not pointing to the exact page and redirect to some [page](https://www-us.apache.org/dist/zookeeper/stable/), it should point to this [link](https://archive.apache.org/dist/zookeeper/stable/)

Check the page [Running ZooKeeper, A Distributed System Coordinator](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/) for the problem.

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/
Update the link on the text **ZooKeeper** to https://archive.apache.org/dist/zookeeper/stable/ and not this link (https://www-us.apache.org/dist/zookeeper/stable/).

/kind document
/assign
/language en

**Comment by tengqm** [comment]
Closed by #34833
/close
