### ISSUE TITLE
Improvement for k8s.io/zh-cn/docs/setup/production-environment/tools/kubespray/

### ISSUE THREAD

**Issue by coder-ldh** [kubernetes/website#34837]
remove doc

**Comment by utkarsh-singh1** [comment]
Hi @coder-ldh, Can you elaborate your issue more clearly and provide the link to the issue.

**Comment by NitishKumar06** [comment]
@utkarsh-singh1 I think here's the link: https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubespray/

**Comment by sftim** [comment]
Why remove https://k8s.io/zh-cn/docs/setup/production-environment/tools/kubespray/?

https://kubernetes.io/docs/setup/production-environment/tools/kubespray/ exists, so there should be a localization of that English page into Chinese.

If this is a takedown request I also don't see any content that would put Kubernetes' ICP license at risk (ie, content that the government of China would prefer to censor).
