### ISSUE TITLE
Kubernetes Release Cycle image failed

### ISSUE THREAD

**Issue by tracy4u** [kubernetes/website#34840]
Image of one Kubernetes release cycle
Image of Kubernetes release lifecycle spanning three releases

are 404 now

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/releases/release/

Links: 
- https://kubernetes.io/releases/release/#the-release-cycle
- https://kubernetes.io/releases/release/#:~:text=Each%20release%20is%20part%20of%20a%20broader%20Kubernetes%20lifecycle%3A

/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by #34918.
/close
