### ISSUE TITLE
Limit Ranges Typo

### ISSUE THREAD

**Issue by shanec42** [kubernetes/website#34857]
`The LimitRanger admission controller enforces `

Should be "LimitRange" not "LimitRanger" in the 3rd bullet under https://kubernetes.io/docs/concepts/policy/limit-range/#overview-of-limit-range

**Comment by Shubham82** [comment]
Hi
We shouldn't do that. The name of the Admission control plugin is **LimitRanger**. 

For reference: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#limitranger

**Comment by tengqm** [comment]
Checking ...

**Comment by tengqm** [comment]
Confirmed the name of the admission controller. '`LimitRanger`' is it.
/close
