### ISSUE TITLE
Verify Signed Container Images - Broken links

### ISSUE THREAD

**Issue by danielorf** [kubernetes/website#34854]
The `Installation` and `Configuration Options` link in the [Verifying Image Signatures with Admission Controller](https://kubernetes.io/docs/tasks/administer-cluster/verify-signed-images/#verifying-image-signatures-with-admission-controller) section are broken.

**Comment by utkarsh-singh1** [comment]
Hi @danielorf, I think the updated link are these-

Installation - https://docs.sigstore.dev/cosign/installation

Configuration for Kubernetes - https://docs.sigstore.dev/cosign/kubernetes

**Comment by utkarsh-singh1** [comment]
Hi @danielorf, I think the updated link can be found here -

Installation - https://docs.sigstore.dev/cosign/installation

Configuration for Kubernetes - https://docs.sigstore.dev/cosign/kubernetes

**Comment by utkarsh-singh1** [comment]
Looks like installation of cosign from https://github.com/sigstore/helm-charts/tree/main/charts/cosigned to https://github.com/sigstore/cosign#installation.

**Comment by NitishKumar06** [comment]
@utkarsh-singh1 What about Configuration link?

**Comment by utkarsh-singh1** [comment]
Hi @NitishKumar06, Instead of Configuration we can add Detailed usage of cosign there - https://github.com/sigstore/cosign/blob/main/USAGE.md.
