### ISSUE TITLE
Documentation of Network Policy lacks explanations of `empty` or `not set` ingress field.

### ISSUE THREAD

**Issue by jrsmroz** [kubernetes/website#34867]
The description of [networkpolicy-resource](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource), defined at [git source](https://github.com/kubernetes/website/blob/5c7ecd985fe45498d3ab96e25f3c8d2f9624cb4e/content/en/docs/concepts/services-networking/network-policies.md?plain=1#L66) does not states clearly what  an empty or not set ingress field means.

If one studies the examples, it can deduce that if ingress is not set, it means all traffic is allowed and if it's set to empty value, all traffic is blocked.

I believe it should be stated clearly in order to improve ease of understanding. [Go NetworkPolicySpec type doc](https://pkg.go.dev/k8s.io/api/networking/v1#NetworkPolicySpec) does that by writing `If his field is empty then this NetworkPolicy does not allow any traffic (and serves solely to ensure that the pods it selects are isolated by default)
 ` 

Same applies to the egress field.

**Comment by utkarsh-singh1** [comment]
Hi @jrsmroz, You can find about detailed description of components of networkpolicy.yaml here in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#networkpolicy-v1-networking-k8s-io.

**Comment by utkarsh-singh1** [comment]
Hi @jrsmroz, this link - https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#networkpolicy-v1-networking-k8s-io is mentioned just below the https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource.

Here
> See the [NetworkPolicy](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#networkpolicy-v1-networking-k8s-io) reference for a full definition of the resource.

**Comment by jrsmroz** [comment]
Ah, I've missed it when I was reading the document.
