### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by MidnightJava** [kubernetes/website#34868]
Running the interactive environment in the latest version of Chrome, and nothing happens when I click anywhere. It's completely dead. It works in Firefox.

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
/label team/katacoda

@MidnightJava have you tried disabling the ad blocker you are using and then reloading?

**Comment by Kartik494** [comment]
@MidnightJava it's working fine in chrome latest version.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
