### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by ChadCarver** [kubernetes/website#34871]
This page is missing the commands to install containerd. At the anchor [container-runtimes](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#container-runtimes), there is the following text:

"Use the following commands to install Containerd on your system:"

Yet there is nothing below this instructing how to perform the install. I believe it should have something along the lines of:
```
sudo apt-get update && sudo apt-get install -y containerd
sudo mkdir -p /etc/containerd
sudo containerd config default | sudo tee /etc/containerd/config.toml
```

But the actual instructions for installing containerd appear to be missing. 
Below this we find the following text indicating that a restart of the newly installed containerd service should be performed, but the instructions to perform the actual install are missing.
"If you apply this change, make sure to restart containerd:"
`sudo systemctl restart containerd'

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#container-runtimes
/language en

**Comment by NitishKumar06** [comment]
Hi @ChadCarver , There's already a line mentioned to go through this link (https://github.com/containerd/containerd/blob/main/docs/getting-started.md) and then come back to this step.

**Comment by sftim** [comment]
We should remove the text "Use the following commands to install Containerd on your system:” as these are obsolete. Instead, we expect the containerd documentation to cover that detail.

**Comment by sftim** [comment]
We could also revise the text to make it clear that following those third-party docs is a required step towards having a working containerd.

**Comment by NitishKumar06** [comment]
Perfect @sftim , I'll commit the changes as required !
