### ISSUE TITLE
Clarify documented privileges of kubectl debug node

### ISSUE THREAD

**Issue by kgibm** [kubernetes/website#34879]
**What would you like to be added**:

`oc` supports `chroot /host` (and even prints a helpful hint of "To use host binaries, run `chroot /host`") whereas `kubectl` causes "Operation not permitted" (even though `/host` is readable):

`oc` results:

```
$ oc debug node/$NODE -t --image=ubuntu -- chroot /host ls
Creating debug namespace/openshift-debug-node-vv26n ...
Starting pod/worker2-debug ...
To use host binaries, run `chroot /host`
bin   dev  home  lib64	mnt  ostree  root  sbin  sys	  tmp  var
boot  etc  lib	 media	opt  proc    run   srv	 sysroot  usr
```

`kubectl` results:

```
$ kubectl debug node/$NODE -it --image=ubuntu -- sh -c "ls /host; chroot /host ls"
Creating debugging pod node-debugger-worker2-xnmxh with container debugger on node worker2.
bin   dev  home  lib64	mnt  ostree  root  sbin  sys	  tmp  var
boot  etc  lib	 media	opt  proc    run   srv	 sysroot  usr
chroot: cannot change root directory to '/host': Operation not permitted
```

**Why is this needed**:

This is part of a broader lack of permissions in `kubectl debug node` that `oc debug node` does not suffer from which limits certain diagnostics. For example, I can't even look at all PIDs with `kubectl` even though I'm ostensibly `root`:

```
$ kubectl debug node/$NODE -it --image=ubuntu -- sh -c "id; ls -l /proc/3899524 >/dev/null"
Creating debugging pod node-debugger-worker2-4b7vb with container debugger on node worker2.
uid=0(root) gid=0(root) groups=0(root)
ls: cannot read symbolic link '/proc/3899524/cwd': Permission denied
ls: cannot read symbolic link '/proc/3899524/root': Permission denied
ls: cannot read symbolic link '/proc/3899524/exe': Permission denied
```

Although this works fine with `oc`:

```
$ oc debug node/$NODE -t --image=ubuntu -- sh -c "id; ls -l /proc/3899524 >/dev/null"
Creating debug namespace/openshift-debug-node-dhj8k ...
Starting pod/worker2-debug ...
To use host binaries, run `chroot /host`
uid=0(root) gid=0(root) groups=0(root)

```

The relevant bits of code appear to be the following and show significant differences in the debug node pod templates:

* [`kubectl`'s `generateNodeDebugPod`](https://github.com/kubernetes/kubectl/blob/f125772/pkg/cmd/debug/debug.go#L567)
* [`oc`'s `approximatePodTemplateForObject` in the `corev1.Node` case](https://github.com/openshift/oc/blob/bf53be9/pkg/cli/debug/debug.go#L1011)

**Comment by sftim** [comment]
The feature request is to document that Kubernetes ephemeral containers are unprivileged by default. Have I got that right?

**Comment by kgibm** [comment]
@sftim Yes, this is a documentation change request although I'm not sure what the correct term should be instead of privileged. I don't think unprivileged is right either because the pod does have privileged access to the worker node filesystem but it lacks other privileged permissions that one would normally expect `root` to have (such as introspecting all processes). I guess the best thing would be to ask a subject matter expert to describe what sorts of things the debug pod can do.

**Comment by sftim** [comment]
No, it's not about ephemeral containers. It's about debug pods that you can try to create with `kubectl`, as a way to get a form of node level access.

There aren't any docs for `kubectl debug node` yet; it looks like the folks doing the improvement might have missed out adding those when this subcommand got added.

**Comment by sftim** [comment]
/retitle “Debug Running Pods” gives poor advice about debugging via node shell

**Comment by kgibm** [comment]
@sftim 

> No, it's not about ephemeral containers. It's about debug pods that you can try to create with kubectl, as a way to get a form of node level access.

Correct. Not sure how ephemeral containers came into the picture.

> There aren't any docs for kubectl debug node yet; it looks like the folks doing the improvement might have missed out adding those when this subcommand got added.

Yes, there are, as quoted earlier: https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#node-shell-session

> If none of these approaches work, you can find the Node on which the Pod is running and create a privileged Pod running in the host namespaces. To create an interactive shell on a node using kubectl debug, run:
> 
> ```
> kubectl debug node/mynode -it --image=ubuntu
> ```

These are, in a sense, privileged, as the user is `root` and the worker node's filesystem is mounted into `/host`; however, they are also not fully privileged as the user does not have access to all processes (as documented earlier in the issue, and as compared to `oc debug node`). At least, not in the way that an average person defines as "privileged".

**Comment by sftim** [comment]
@kgibm would you be willing to revise the issue description to frame this as the improvement you would like to see?

**Comment by kgibm** [comment]
/retitle Clarify documented privileges of kubectl debug node

**Comment by kgibm** [comment]
@sftim I've updated the title. If you think it's better to close this issue and open a new issue that's cleaner and reference this as background, I can do that as well.

As far as what the actual clarification should be instead of the word "privileged", I'm not sure. I think a subject matter expert should opine on that. My guess is it should be something along the lines of:

> If none of the previous approaches work, you can find the Node on which the Pod is running and create a debug Pod on that node. This Pod runs as `root` and has access to the Node's filesystem through `/host`; however, it is not a fully privileged pod and there are some limitations such as reading some process information. To create an interactive shell on a Node using kubectl debug, run:

**Comment by sftim** [comment]
I suggest opening a new issue, given that the original issue was a CLI feature request and not a suggestion for docs.

BTW, the description is the longer text slightly below the issue title.

**Comment by kgibm** [comment]
Opened https://github.com/kubernetes/website/issues/35170. Closing this issue.
