### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/job/

### ISSUE THREAD

**Issue by pprotim** [kubernetes/website#34876]
unable to timeZone field in the CronJob spec. Version of kubernates is 
Client Version: v1.22.4
Server Version: v1.21.11-gke.1900

why timeZone is not taking?
1) error: error validating "deployment-cronjob.yaml": error validating data: ValidationError(CronJob.spec): unknown field "timeZone" in io.k8s.api.batch.v1.CronJobSpec;
2) error: error validating "deployment-cronjob.yaml": error validating data: ValidationError(CronJob.spec.jobTemplate.spec): unknown field "timeZone" in io.k8s.api.batch.v1.JobSpec;
3) error: error validating "deployment-cronjob.yaml": error validating data: ValidationError(CronJob.spec.jobTemplate.spec.template.spec): unknown field "timeZone" in io.k8s.api.core.v1.PodSpec;

**Comment by sftim** [comment]
The documentation for CronJob timezones is https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones

As that page explains, time zone support in the CronJob API is an alpha Kubernetes feature and not enabled by default.

/kind support
/language en

**Comment by pprotim** [comment]
Thank you for the information

**Comment by reylejano** [comment]
Looks like sftim gave a link to help you solve your issue
/close
