### ISSUE TITLE
[en] Typo in `cluster-intro` page

### ISSUE THREAD

**Issue by PrajwalBorkar** [kubernetes/website#34877]
**This is a Bug Report**

**Problem:**

- Typo exists: `containerd `

> The node should also have tools for handling container operations, such as containerd or Docker.

**Proposed Solution:**
`containerd ` => `containers `
**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

**Additional Information:**
/language en
/good-first-issue
/kind documentation
/kind bug

**Comment by sftim** [comment]
/priority awaiting-more-evidence
/remove-help
/remove-good-first-issue
/language en
/remove-kind bug
/language en

containerd is _not_ a typo in that page. It refers to [containerd](https://containerd.io/)

**Comment by PrajwalBorkar** [comment]
Ohh okay
