### ISSUE TITLE
Broken hyperlink on Running ZooKeeper, A Distributed System Coordinator page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34882]
**Problem:**
The text [**ZooKeeper Basics**](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#zookeeper-basics) on [link](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/) is not pointing to the exact section and redirect to the same [page](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#zookeeper-basics), it should point to this [link](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#zookeeper)

Check the page [Running ZooKeeper, A Distributed System Coordinator](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/) for the problem.

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/
Update the link on the text **ZooKeeper Basics** to https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#zookeeper and not this link (https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#zookeeper-basics).

/kind document
/assign
/language en

**Comment by sftim** [comment]
/retitle Broken hyperlink on Running ZooKeeper, A Distributed System Coordinator page

**Comment by kadtendulkar** [comment]
Since PR is merged, I'm closing the issue.
/close
