### ISSUE TITLE
Improvement for k8s.io/docs/concepts/storage/dynamic-provisioning/

### ISSUE THREAD

**Issue by nareshmaharaj-consultant** [kubernetes/website#34887]
When enabling dynamic provisioning as default behaviour:
https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#defaulting-behavior
It might be helpful to reference the following as a hyper link for clarity
https://kubernetes.io/docs/reference/labels-annotations-taints/#storageclass-kubernetes-io-is-default-class

**Comment by sftim** [comment]
/kind feature
/language en

It sounds as if we could add a hyperlink from https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/  to https://kubernetes.io/docs/reference/labels-annotations-taints/#storageclass-kubernetes-io-is-default-class and that would solve it for you @nareshmaharaj-consultant 

Have I got that right?

**Comment by nareshmaharaj-consultant** [comment]
Hi Tim,

I would agree this would be awesome for users.

Kind regards
Naresh Maharaj

**Comment by sftim** [comment]
@nareshmaharaj-consultant would you be willing to update (edit) the issue description, with https://github.com/kubernetes/website/issues/34887#issuecomment-1179521862 in mind, so that it's clear what change you are asking for?
