### ISSUE TITLE
Broken link on Communication between Nodes and the Control Plane page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34899]
**Problem:**
The text [**kubelet TLS bootstrapping**](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/) on [link](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/) is not pointing and redirect to some [page](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/), it should point to this [link](https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/)

Check the page [Communication between Nodes and the Control Plane](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/) for the problem.

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/
Update the link on the text kubelet TLS bootstrapping to https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/ and not this link (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping/).

/kind document
/assign
/language en

**Comment by sftim** [comment]
/retitle Broken link on Communication between Nodes and the Control Plane page

**Comment by kadtendulkar** [comment]
Since PR is merged I'm closing the issue.
/close
