### ISSUE TITLE
[ko] Re-arrange categories of Korean contribute doc as same as English

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/website#34897]
**This is a Feature Request**

**What would you like to be added**
Change the weights in ```_index.md``` file of ```Document style overview``` and ```Reference Docs Overview``` in Contribute docs.

**Why is this needed**
Since the weights are same, and was sorted by first letter of Korean, the order of listed categories in contribute docs of Korean is different with that of English.

**Comments**
Check the difference and comment me if it is needed.
[https://kubernetes.io/ko/docs/contribute/](https://kubernetes.io/ko/docs/contribute/)
[https://kubernetes.io/docs/contribute/](https://kubernetes.io/docs/contribute/)

**Comment by jihoon-seo** [comment]
[영문]
![image](https://user-images.githubusercontent.com/46767780/178212423-25011730-fd22-48f4-a3ac-1fa60d618823.png)

1. [Suggesting content improvements](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/suggesting-improvements.md?plain=1) - weight: 10
2. [Contributing new content](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/new-content/_index.md?plain=1) - weight: 20
3. [Reviewing changes](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/review/_index.md?plain=1) - weight: 30
4. [Localizing Kubernetes documentation](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/localization.md?plain=1) - weight: 50
5. [Participating in SIG Docs](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/participate/_index.md?plain=1) - weight: 60
6. [Documentation style overview](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/style/_index.md?plain=1) - **weight: 80**
   - [파일이 생성될 때 weight: 80 으로 설정됨](https://github.com/kubernetes/website/pull/9510/files#diff-c763d8920bdca9e54f0f6faa703d91bd6086adc21a390deaf2c616c97b410e71)
7. [Reference Docs Overview](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/_index.md?plain=1) - **weight: 80**
   - [파일이 생성될 때 weight: 80 으로 설정됨](https://github.com/kubernetes/website/pull/9510/files#diff-46242ff76a20eb0819ad84e4bdfb5abdd2f2dc70e8ca52472c0838eddf7ed6d5)
8. [Advanced contributing](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/advanced.md?plain=1) - weight: 98
9. [Viewing Site Analytics](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/analytics.md?plain=1) - weight: 100

[한국어]
![image](https://user-images.githubusercontent.com/46767780/178214575-14675a22-9c60-44df-8873-21e18c65c29a.png)

10. [쿠버네티스 문서 한글화 가이드](https://github.com/kubernetes/website/blob/main/content/ko/docs/contribute/localization_ko.md?plain=1) - weight가 없네요 ㅎㅎ
