### ISSUE TITLE
Creating a cluster with kubeadm

### ISSUE THREAD

**Issue by sudipju** [kubernetes/website#34907]
Following command : 
kubectl taint nodes --all node-role.kubernetes.io/control-plane- node-role.kubernetes.io/master-

should be replaced with : 
kubectl taint nodes --all node-role.kubernetes.io/control-plane node-role.kubernetes.io/master 

"-" removed

**Comment by NitishKumar06** [comment]
@sudipju I believe "-" should be there.

**Comment by sudipju** [comment]
I am probably missing the logic. Can you please help me to understand?

**Comment by sudipju** [comment]
To add, subsequently in the page,  following statement was described - "This will remove the node-role.kubernetes.io/control-plane and node-role.kubernetes.io/master". This doesn't include either control-plane- or master-. So, my recommendation is to remove "-" after control-plane and master as I recommended below:
kubectl taint nodes --all node-role.kubernetes.io/control-plane node-role.kubernetes.io/master

**Comment by neolit123** [comment]
Adding - at the end removes a taint which is the section for single node clusters.
I don't see a problem in the docs here?

**Comment by neolit123** [comment]
/close

closing as "won't fix", documentation is accurate.
if you have usage problems please join #kubeadm on k8s slack.
