### ISSUE TITLE
Broken hyperlink on Kubelet Configuration (v1beta1) page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#34914]
**Problem:**
The text [**KubeletConfiguration**](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) on [link](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/) is not pointing and redirect to same [page](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration), it should point to this [link](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration)

Check the page [kube-scheduler Configuration (v1beta2)](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/) for the problem.

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/
Update the link on the text **KubeletConfiguration** to https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration and not this link (https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration).

/kind document
/assign
/language en

**Comment by RA489** [comment]
@kadtendulkar feel free to raise PR for it.
