### ISSUE TITLE
[ko] Update branch name in 'Korean L10n guide' page

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#34930]
**This is a Bug Report**

**Note:**
`dev-1.24-ko.2` is the current work branch for Korean localization. (Ref: #34901)
It is highly recommended that you 
- fetch the latest `dev-1.24-ko.2` to your local dev env,
- branch off your feature branch from `dev-1.24-ko.2`, and
- set the merge target branch of your PR as `dev-1.24-ko.2`.

**Problem:**
The default branch's name of this repo was changed from `master` to `main`,
but the doc "쿠버네티스 문서 한글화 가이드" is not reflecting this change.

**Proposed Solution:**
Replace in https://github.com/kubernetes/website/blob/main/content/ko/docs/contribute/localization_ko.md?plain=1 :

[L22]
```diff
-한글화팀은 `master` 브랜치에서 분기한 개발 브랜치를 사용한다. 개발 브랜치 이름은 다음과 같은
+한글화팀은 `main` 브랜치에서 분기한 개발 브랜치를 사용한다. 개발 브랜치 이름은 다음과 같은
```

[L49]
```diff
-- [퀵윈(Quick Wins)](https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Amaster+-label%3A%22do-not-merge%2Fwork-in-progress%22+-label%3A%22do-not-merge%2Fhold%22+label%3A%22cncf-cla%3A+yes%22+label%3A%22size%2FXS%22+label%3A%22language%2Fko%22+)
+- [퀵윈(Quick Wins)](https://github.com/kubernetes/website/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Amain+-label%3A%22do-not-merge%2Fwork-in-progress%22+-label%3A%22do-not-merge%2Fhold%22+label%3A%22cncf-cla%3A+yes%22+label%3A%22size%2FXS%22+label%3A%22language%2Fko%22+)
```

[L224]
```diff
-1. 컨트리뷰터가 개선이 필요한 용어을 파악하면, ISSUE를 생성하여 개선 필요성을 공유하거나 `master` 브랜치에
+-1. 컨트리뷰터가 개선이 필요한 용어을 파악하면, ISSUE를 생성하여 개선 필요성을 공유하거나 `main` 브랜치에
PR을 생성하여 개선된 용어를 제안한다.
```

**Page to Update:**
https://kubernetes.io/ko/docs/contribute/localization_ko/

/language ko

**Comment by seokho-son** [comment]
/triage accepted

Thanks!!

**Comment by seokho-son** [comment]
Hi @bishal7679 
Thank you for your contribution.

But I need to say, IMO, self-assigning (and opening a PR) is not a good way to proceed handling an open issue in an open source project. 
We need to check who are going to handle the issue. (especially, if you are not the author of this issue)

@jihoon-seo I hope to check your willingness first for handling this issue.

**Comment by NitishKumar06** [comment]
@seokho-son I think the point you've mentioned does not sound correct. This issue was not assigned to anyone and if any contributor feels like they can work on the issue, they can assign themselves (if no one else has already been assigned). That's why the _/assign_ option is there. Even if the changes pushed were wrong at some line, they can be modified by taking the suggestion given on the PR by the reviewers.

**Comment by seokho-son** [comment]
Hi @NitishKumar06
Thank you for sharing your opinion. 
I don't have the answer for that, but I think it is a procedure to prevent duplicate works from multiple contributors and promote contributions opening issues.
Sometimes we are not sure intention of the author of issue (contributor who opened the issue) weather the contributor has a willing to be assigned or not. And there is a chance the author is also just waiting for accepted triage before self-assigning. Usually, contributor who opened the issue tends to have willingness to handle the issue as well.

So the comment I left is to add a minor procedure to check willingness of the author of this issue.
I don't have strong opinion on this procedure, but I think it is a convention in maintaining issues related with (at least) Korean localization.

**Comment by bishal7679** [comment]
Thanks @seokho-son will follow these from next contributions ✅

**Comment by jihoon-seo** [comment]
@seokho-son Thank you for the checking. 😊

Actually I wanted that someone other than me work on this,
but preferably someone who is a native Korean speaker, 
because this job might be seen as just fixing some strings but actually this job is a Korean L10n job,
since, for example, a Korean contributor may find and apply additional improvements to the document.

@bishal7679 @NitishKumar06 Please consider the point that I mentioned above!

**Comment by bishal7679** [comment]
@jihoon-seo yeap! You are absolutely right🌟
But can you consider this PR?
