### ISSUE TITLE
Document the kubeconfig format

### ISSUE THREAD

**Issue by danderson** [kubernetes/website#34935]
Currently, AFAICT, the only documentation of the format of kubeconfig is http://kubernetes.io/v1.1/docs/user-guide/kubeconfig-file.html , which provides a couple of examples and a suggestion to use the CLI to manipulate user configurations.

While this is nice as introductory material, it's insufficient as a reference for people building automation. It would be nice to have the kubeconfig format documented in the style of http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html , and the reference linked from the user guide entry.

**Comment by sftim** [comment]
I think we could add that information into to https://kubernetes.io/docs/reference/config-api/

**Comment by Pro-Coder04** [comment]
I would like to solve this issue
Could you tell me a bit more in detail as to what is to be done?

**Comment by reylejano** [comment]
At the moment, the current page on kubeconfig is a tasks page
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#define-clusters-users-and-contexts

**Comment by tengqm** [comment]
/close
This is done.
