### ISSUE TITLE
Improvement for k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig/

### ISSUE THREAD

**Issue by LeonardoLG95** [kubernetes/website#34949]
Hello, I propose to add how to create a config for success in creating a new kubeconfig and solve this problem (if exists put the link in the config param of the documentation):

`test@test:/etc/kubernetes/pki$ sudo kubeadm kubeconfig user --client-name=test --v=5`
`required flag(s) "config" not set`

**Comment by neolit123** [comment]
The page already links to examples

> For examples on how to use kubeadm kubeconfig user see [Generating kubeconfig files for additional users](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs#kubeconfig-additional-users).

/close
/sig cluster-lifecycle
