### ISSUE TITLE
Incorrect feature state data for kubelet credential provider

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#34953]
**This is a Bug Report**

**Problem:**
The Feature state of `Kubelet Credential Provider` is mentioned as `alpha` under [Configure a kubelet image credential provider](https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/) task, Which is not correct.  In k8s v1.24.0 `Kubelet Credential Provider` is graduated to `beta`. See the [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#kubelet-credential-provider-graduates-to-beta) of k8s v1.24.0 and Also mention under the [Feature Gates document](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features).

**Proposed Solution:**
Change the Feature State of `KubeletCredentialProvider` from Kubernetes v1.20 [alpha] to Kubernetes v1.24 [beta].
**Page to Update:**
https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/

**Comment by Shubham82** [comment]
fixed it here:#34954

**Comment by sftim** [comment]
As this is a bug report issue, I'm going to change the title to summarize what isn't right.

/retitle Incorrect feature state data for kubelet credential provider

Also:
/language en
/triage accepted
/sig node

**Comment by Shubham82** [comment]
thanks @sftim
