### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by raymundovr** [kubernetes/website#35002]
Hi guys,

After following the commands to expose a service I don't get an External IP address and I can't access my app from local computer.
```
kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080
```
And to verify
```
; kubectl get services
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes            ClusterIP   10.96.0.1       <none>        443/TCP          2d1h
kubernetes-bootcamp   NodePort    10.108.123.50   <none>        8080:31913/TCP   5s
```

**Comment by jihoon-seo** [comment]
The phenomenon that `EXTERNAL-IP` is not set is a normal, non-problematic one.
That one will be set when your Service's type is `LoadBalancer`, and it has been successfully linked with CSP's managed load balancer service.

BTW, your app is successfully exposed by the `kubernetes-bootcamp` NodePort Service already.
You can verify this with the remaining commands in the interactive tutorial:

```
$ export NODE_PORT=$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')

$ echo NODE_PORT=$NODE_PORT
NODE_PORT=31543

$ curl $(minikube ip):$NODE_PORT
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-fb5c67579-cq7ll | v=1
```

**Comment by raymundovr** [comment]
@jihoon-seo Then there's a mismatch in the documentation:

```
Step 1
...
We have now a running Service called kubernetes-bootcamp. Here we see that the Service received a unique cluster-IP, an internal port and an external-IP (the IP of the Node).
```

In addition, the command `curl $(minikube ip):$NODE_PORT` renders no result

**Comment by jihoon-seo** [comment]
> In addition, the command `curl $(minikube ip):$NODE_PORT` renders no result

Are you following this tutorial on your local computer with your K8s cluster, not on online terminal (Katacoda) in that page?

I confirm that I can get results after running `curl $(minikube ip):$NODE_PORT`, on online terminal (Katacoda) in that page.

---

> there's a mismatch in the documentation

About this, it would be better to hear other people's opinion.
/remove-kind support

**Comment by raymundovr** [comment]
@jihoon-seo tried both places

Also, is then the text
"
Step 1
...
We have now a running Service called kubernetes-bootcamp. Here we see that the Service received a unique cluster-IP, an internal port and an external-IP (the IP of the Node).
"

accurate?

I'm confused

**Comment by Shubham82** [comment]
I tried the tutorial and it's working for me.
@raymundovr  did it give any error? 

> The phenomenon that EXTERNAL-IP is not set is a normal, non-problematic one.
> That one will be set when your Service's type is LoadBalancer and it has been successfully linked with CSP's managed load balancer service.

you are right.  see [ServiceTypes](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) for more information.
IMO we can remove the line (the IP of the Node) from the tutorial which is just after external-IP or write about external-ip(why it is none) because it creates confusion.
WDYT @jihoon-seo

**Comment by jihoon-seo** [comment]
@Shubham82 Your suggestion looks good to me. 😊

**Comment by Shubham82** [comment]
@jihoon-seo, I think this will be done by katacoda team. am I right?

**Comment by jihoon-seo** [comment]
@Shubham82 I am not sure (don't know) whether the Katacoda team is active.

Instead, maybe someone might just open a issue and PR in https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios
to update the file https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/blob/master/8/step1.md .

**Comment by Shubham82** [comment]
Ok, @jihoon-seo, 
the katacoda team is not active, I saw the repo https://github.com/katacoda-scenarios/[kubernetes-bootcamp-scenarios](https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios) the last PR was on last year. No update on a current issue.
