### ISSUE TITLE
Unclear text in “Fine Parallel Processing Using a Work Queue” task

### ISSUE THREAD

**Issue by vidhyapg** [kubernetes/website#35026]
In this article, it is mentioned that 
"So, we set the completion count of the Job to 1". 
However I do not see this in the example given below, 
Completions:      <unset>

Example is according to this article https://kubernetes.io/docs/concepts/workloads/controllers/job/
Parallel Jobs with a work queue:
do not specify .spec.completions, default to .spec.parallelism.

But the below line is confusing and seems to be contradictory to both example and job page. 
"So, we set the completion count of the Job to 1".

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/#defining-a-job

**Comment by sftim** [comment]
/retitle Unclear text in “Fine Parallel Processing Using a Work Queue” task
/sig apps
/language en
