### ISSUE TITLE
Document application rebalancing

### ISSUE THREAD

**Issue by kargakis** [kubernetes/website#3502]
> Generally you would set a terminationGracePeriodSeconds on a pod that is at least as long as you expect a move to take (5-10m) and then register a preStop hook for your pod that starts the rebalance / waits for it to complete, then returns. The process does not receive SIGTERM under after preStop returns.

https://github.com/kubernetes/kubernetes/issues/43350#issuecomment-287632622

**Comment by jaredbhatti** [comment]
This doesn't appear to be a request for documentation.  I'm going to close this issue, but if there's something I need to document here, please reopen.

**Comment by kargakis** [comment]
People are going to need to setup rebalancing for distributed DBs so I think it's worth documenting the steps.

**Comment by jaredbhatti** [comment]
Can you give the docs team some guidance on next steps?  Are you the right person to talk to or should we be talking to someone else?

**Comment by kargakis** [comment]
@f-w can you help out on this one? It would be nice to have a real-world example documented, eg. ES rebalancing.

**Comment by f-w** [comment]
@kargakis, my pleasure. Here is the gist of my implementation with source code on GH 
1. added [preStop](https://github.com/bcgov/MyGovBC-MSP/blob/master/openshift/elk/templates/elk.yaml#L130) config and changed [terminationGracePeriodSeconds](https://github.com/bcgov/MyGovBC-MSP/blob/master/openshift/elk/templates/elk.yaml#L134) per @smarterclayton's suggestion
2. the preStop [script](https://github.com/bcgov/MyGovBC-MSP/blob/master/openshift/elk/docker-images/elastic-search/preStop.sh) gets current node's ES id, adding it to [routing allocation excluded list](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-filtering.html), then waits for doc count down to 0 and exit. Script can handle multi-pod termination simultaneously.  
3. [a cron job](https://github.com/bcgov/MyGovBC-MSP/blob/master/openshift/elk/docker-images/cron/cron-tasks.sh#L18) empties the list nightly when cluster is stable

With the changes, ES is auto-scalable. The whole ELK setup on OpenShift is documented [here](https://github.com/bcgov/MyGovBC-MSP/tree/master/openshift/elk)

**Comment by vinayk06** [comment]
@f-w so If I want to use it which version I can use?

**Comment by f-w** [comment]
@vinayk06, I use k8s@1.3, es@^2.4. I believe script itself works for es@5.
