### ISSUE TITLE
DNS for Services and Pods

### ISSUE THREAD

**Issue by aBetterGamer** [kubernetes/website#35034]
I think they have the subdomain and domain backwards in the documentation.

`For example, a Pod with hostname set to "foo", and subdomain set to "bar", in namespace "my-namespace", will have the fully qualified domain name (FQDN) "foo.bar.my-namespace.svc.cluster-domain.example".`

in the above example I think it would be "bar.foo.my-namespace.svc.cluster-domain.example" where bar comes before foo because bar is the subdomain and subdomains precede domains aka hostnames.

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields

**Comment by sftim** [comment]
@aBetterGamer I'd assume the docs are right, unless you've evidence otherwise.

/priority awaiting-more-evidence

**Comment by aBetterGamer** [comment]
Hey @sftim ,

Yeah reading over this again, it seems the terminology was just throwing me off.  I was thinking of host name as the entire domain name, but I think here they are using host name as leaf domain.  I think it would probably be clearer if they used leaf domain, sub domain and domain in the docs, instead of host name as host name is technically the whole thing.
