### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/tasks/administer-cluster/namespaces/

### ISSUE THREAD

**Issue by fusida** [kubernetes/website#35037]
https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/namespaces/
[名字空间的设计文档](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/namespaces.md)
404

**Comment by utkarsh-singh1** [comment]
Hi @fusida, can you please elaborate your issue the  current passage doesn't give enough information.

**Comment by fusida** [comment]
@utkarsh-singh1 see #35039

**Comment by tengqm** [comment]
This has been fixed.
/close
