### ISSUE TITLE
Document using kubectl to create an interactive debugging session on a node 

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#35031]
**This is a Feature Request**

**What would you like to be added**
Document `kubectl debug node` in a node troubleshooting context

**Why is this needed**
Other than a small mention in [Debug Running Pods](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/), there's no task documentation to cover the `kubectl` feature that lets you create a Pod on a node - and attach to it - for doing node troubleshooting tasks.

**Comments**
I'd expect to see an update to https://kubernetes.io/docs/tasks/debug/debug-cluster/ as part of this work. Maybe a hyperlink, maybe more than that.

/language en
/sig cli
/kind feature

Relevant to https://github.com/kubernetes/enhancements/issues/1441

**Comment by akankshakumari393** [comment]
hey I would like work on this. Could you provide some more details on what needs to be done?

**Comment by sftim** [comment]
@akankshakumari393: it's not clear who (which person, or which group) your request was aimed at.

If you've read https://github.com/kubernetes/website/issues/35031#issue-1305395977 and you have questions, maybe you can list some of the questions that you're now pondering?

**Comment by akankshakumari393** [comment]
Cool thanks, I will check and let you know on this.

**Comment by verb** [comment]
@akankshakumari393 you can assign the PR to me when it's ready

**Comment by sftim** [comment]
Folks who'd like to work on this are welcome to do so. Please liaise with @akankshakumari393 first if possible, to avoid duplicating work.
