### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/list-all-running-container-images/

### ISSUE THREAD

**Issue by SaintMichae64** [kubernetes/website#35054]
Give example commands not command requiring 'fill in the blank', instead of 'kubectl -n >namespace> get pods'; provide a command with actual namespaces or actual names (where applicable), kubectl -n sn-labs-b0b9817 get pods'. Real world examples in context.

**Comment by sftim** [comment]
@SaintMichae64, which part of https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/ has a placeholder where you expected to see an example value?

Can you quote the command block that you're discussing?

/triage needs-information
/language en
