### ISSUE TITLE
[hi] Translate docs/concepts/overview/components.md into Hindi

### ISSUE THREAD

**Issue by AmanSarraf** [kubernetes/website#35063]
**This is a Feature Request**

**What would you like to be added**
Hindi Translation for the [docs/concepts/overview/components.md ](https://kubernetes.io/docs/concepts/overview/components/)

**Why is this needed**
This page is not translated in Hindi yet

**Comments**
/language hi
/assign

**Comment by NitishKumar06** [comment]
@anubha-v-ardhan Would you like to add something to this issue?
