### ISSUE TITLE
[ko]Translate tasks/debug/debug-cluster/crictl into Korean

### ISSUE THREAD

**Issue by jinnypark9393** [kubernetes/website#35090]
**This is a Feature Request**

**What would you like to be added**

Translate "tasks/debug/debug-cluster/crictl" into Korean.

**Why is this needed**

Not translated into Korean yet.

**Comments**

https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/

**Comment by Seo-yul** [comment]
I received the issue through consultation.
Thank you @jinnypark9393

**Comment by jihoon-seo** [comment]
Resolved by
- #36690
- #38192

Thanks!
/close
