### ISSUE TITLE
[ko]Translate tasks/extend-kubernetes/configure-multiple-schedulers into Korean

### ISSUE THREAD

**Issue by rollony** [kubernetes/website#35092]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**

**Comments**

https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

/language ko
/assign

**Comment by jihoon-seo** [comment]
@rollony 감사합니다!
/triage accepted
