### ISSUE TITLE
[ko] Update outdated file: `tasks/run-application/horizontal-pod-autoscale/`

### ISSUE THREAD

**Issue by bart2001** [kubernetes/website#35103]
**This is a Feature Request**

Update `tasks/run-application/horizontal-pod-autoscale/ ` in Korean

**What would you like to be added**

**Why is this needed**
Mentioned in [Outdated Korean contents in the dev-1.24-ko.2 M100](https://github.com/kubernetes/website/issues/34903)

**Comments**

https://kubernetes.io/ko/docs/tasks/run-application/horizontal-pod-autoscale/

**Comment by seokho-son** [comment]
/triage accepted

Thanks @bart2001 !

**Comment by jihoon-seo** [comment]
Resolved by
- #35291 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
