### ISSUE TITLE
RBAC guide mentions obsolete authz bypass via insecure port

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#35101]
**This is a Bug Report**

**Problem:**
[Using RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-creation-or-update) states:
> If your API server runs with the insecure port enabled (`--insecure-port`), you can also make API calls via that port, which does not enforce authentication or authorization.

However, there is no such option in current Kubernetes. At least, I couldn't see it. As far as I can tell, the mechanisms that would work are:
- to perform the bootstrap when authenticated as a member of `system:masters`.

Because this is an API server restriction, you can't configure an extra authorizer during _initial_ bootstrap (such as a webhook authorizer). However, once any principal is bound to a ClusterRole that is allowed to escalate, it's all good and further bootstrapping can take place as that cluster role.

**Proposed Solution:**
Remove that item from the page.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Additional Information:**
/language en
/sig auth

**Comment by mehabhalodiya** [comment]
@dhanraj-druva I see that you haven't worked on this for long, so I stepped up and did this. Thank you for your interest 🙂
/unsassign @dhanraj-druva 
/assign
