### ISSUE TITLE
[ko]Translate website/content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md into Korean

### ISSUE THREAD

**Issue by onestone9900** [kubernetes/website#35127]
**This is a Feature Request**

**What would you like to be added**
Translate website/content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md into Korean

**Why is this needed**
Not translated into Korean yet.

**Comments**
https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/
/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #35280 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
