### ISSUE TITLE
Call out that image pull Secrets must be of appropriate type

### ISSUE THREAD

**Issue by KrashLeviathan** [kubernetes/website#35154]
In the [Specifying imagePullSecrets on a Pod](https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod) section, it could be really helpful to add a callout note that the secret MUST be of `type: kubernetes.io/dockerconfigjson`. I spent hours trying to debug image pull issues because my image pull secret was of the default secret type (Opaque) instead of `kubernetes.io/dockerconfigjson`.

**Comment by sftim** [comment]
/triage accepted
with the proviso that the PR will need tech review: I haven't looked at the code to check the list of Secret types that are acceptable.

**Comment by Shubham82** [comment]
Hi 
These are the types of secrets that are supported https://kubernetes.io/docs/concepts/configuration/secret/#secret-types
And we use `kubernetes.io/dockercfg` and `kubernetes.io/dockerconfigjson` as a type for  [Docker config Secrets](https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets).

I hope this will be helpful for the PR.
