### ISSUE TITLE
[zh-cn] suggest to modify some text in configure-liveness-readiness-startup-probes.md

### ISSUE THREAD

**Issue by big-omega** [kubernetes/website#35152]
> 就绪和存活探测可以在同一个容器上并行使用。 两者都可以确保流量不会发给还未就绪的容器，当这些探测失败时容器会被重新启动。

中的 ”两者都可以确保“ 应该翻译为 ”两者共同使用，可以确保“，否则会引起歧义。

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
/language zh

**Comment by windsonsea** [comment]
/retitle [zh-cn] suggest to modify some text in configure-liveness-readiness-startup-probes.md

**Comment by windsonsea** [comment]
https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

This issue is fixed.
/close
