### ISSUE TITLE
Clarify documented privileges of kubectl debug node

### ISSUE THREAD

**Issue by kgibm** [kubernetes/website#35170]
**This is a Bug Report**

**Problem:**

The following page writes: https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#node-shell-session

> ## Debugging via a shell on the node
> 
> If none of these approaches work, you can find the Node on which the Pod is running and create a privileged Pod running in the host namespaces. To create an interactive shell on a node using kubectl debug, run:
> 
> ```
> kubectl debug node/mynode -it --image=ubuntu
> ```

As discussed in issue #34879, the use of "privileged" in the phrase "create a privileged Pod" is not standard usage and causes confusion because the pod is not created with the privileged flag (as [`oc debug node` does](https://github.com/kubernetes/website/issues/34879#issuecomment-1179031886)). This means that commands such as `chroot /host` fail with `Operation not permitted` and reading some process information may fail with `Permission denied`.

**Proposed Solution:**

As far as what the actual clarification should be instead of the word "privileged", I'm not sure. I think a subject matter expert should opine on that. My guess is it should be something along the lines of:

> ## Debugging via a shell on the node
> 
> If none of the previous approaches work, you can find the Node on which the Pod is running and create a debug Pod on that node. This Pod runs as `root` and has access to the Node's filesystem through `/host`; however, it is not a fully privileged pod. Limitations include not being able to `chroot /host` and reading some process information may fail.
> 
> To create an interactive shell on a Node using kubectl debug, run:
> 
> ```
> kubectl debug node/mynode -it --image=ubuntu
> ```

**Page to Update:**

https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#node-shell-session

@sftim FYI

**Comment by seokho-son** [comment]
/unassign @NitishKumar06 

PR #35176 is an attempt to resolve this issue,
but the PR has been closed and this issue is not resolved yet.

Please take a look discussions and suggestions in the PR #35176 before self-assign. :)

**Comment by NitishKumar06** [comment]
@mehabhalodiya The PR for this issue has already been raised earlier.
