### ISSUE TITLE
[ko]Translate website/docs/concepts/storage/windows-storage/ into Korean

### ISSUE THREAD

**Issue by NayeonKeum** [kubernetes/website#35184]
**This is a Feature Request**

**What would you like to be added**

Translate "website/docs/concepts/storage/windows-storage/" into Korean

- Page: https://kubernetes.io/docs/concepts/storage/windows-storage/
- File: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/storage/windows-storage.md

**Why is this needed**

It is not translated into Korean yet.
I double-checked that this hasn't been Issued or translated in pending PRs.

**Comments**

**Comment by jihoon-seo** [comment]
관련 PR:
- #35698
- #35423 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

참고: https://github.com/kubernetes/website/pull/35698#issuecomment-1205972878
"PR #35698 의 기여 내용을 활용하여, `ko/docs/concepts/storage/windows-storage.md` 를
개선하는 신규 PR로 기여 내용을 추가적으로 반영" 하는 안이 제안되었음
