### ISSUE TITLE
In kubelet-api response, --hostname-override is missing

### ISSUE THREAD

**Issue by RajanikantVerma** [kubernetes/website#35185]
{cluster-ip}/api/v1/nodes/{worker-node}/proxy/configz

In the above api, --hostname-override parameters is not available, In my current requirement i need this parameter to be available in this api response. May i know by when Kubernetes will able to provide it ?

**Comment by sftim** [comment]
Are you asking about an API or a command line parameter @RajanikantVerma ? I see mentions of both API paths and command line arguments and these seem to be mixed together.

At the moment, this question does not make sense. If your overall request is to get help with Kubernetes, this GitHub repo is actually not the right place.

You could ask that question on [Server Fault](https://serverfault.com/questions/tagged/kubernetes) instead.

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
