### ISSUE TITLE
[ko] Translate tasks/job/indexed-parallel-processing-static into Korean

### ISSUE THREAD

**Issue by mocha-123** [kubernetes/website#35191]
**This is a Feature Request**

**What would you like to be added**

Translate tasks/job/indexed-parallel-processing-static into Korean.

**Why is this needed**
Not translated into Korean yet.

**Comments**

Page to translate: https://kubernetes.io/docs/tasks/job/indexed-parallel-processing-static/

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35817
- #36804
- #36810

/close
