### ISSUE TITLE
Broken hyperlinks for dedicated CA and custom CA

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#35190]
**This is a Bug Report**

**Problem:**
Following below hyperlinks are not working under [Manage TLS Certificates in a Cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/) task: 
[dedicated CA](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators) and [custom CA](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators)
The reason for it is it both redirects to  https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators but the ` A Note to Cluster Administrators (#a-note-to-cluster-administrators)` is changed to `Configuring your cluster to provide signing (#configuring-your-cluster-to-provide-signing)` in this PR: #31595

**Proposed Solution:**
 Changed https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#a-note-to-cluster-administrators to https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/#configuring-your-cluster-to-provide-signing for both dedicated CA and custom CA.
**Page to Update:**
https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

**Comment by Shubham82** [comment]
Also, the hyperlinks for both dedicated CA and custom CA were added in this PR: https://github.com/kubernetes/website/pull/30347

**Comment by sftim** [comment]
/language en
/triage accepted

Thanks for spotting this

**Comment by Shubham82** [comment]
> Thanks for spotting this

you're welcome!
