### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

### ISSUE THREAD

**Issue by amiga23** [kubernetes/website#35199]
An example would be great. Or at least a link to more details, e.g. https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

The documentation is splited in tasks and concepts. Search engines mainly lead to tasks section. It would be great if there could be links between these sections. Or even better do not split the documentation.

This is a general issue with the kubernetes documentation.

**Comment by NitishKumar06** [comment]
Can you elaborate the issue in more detail?

**Comment by amiga23** [comment]
I feel that the documentation is great. Really great. It contains a lot of information and is very detailed.
Just the information is not in one place but in sections.
So if you search for something, in this example for scheduling critical pods than the search engine shows results in the docs/tasks folder. This gives a high level information. But does not tell how to do it. So you have to search deeper and will find details in docs/concepts and for even more detailed information in docs/reference.
It would be great if the documentation could be reorganized or at least have cross references between these section.

**Comment by sftim** [comment]
I agree that more cross references would help. That's a fairly easy task and I'd love to see folks logging small feature request issues that highlight where a cross reference is useful.

**Comment by NitishKumar06** [comment]
@amiga23 Any idea on how to go further on resolving this issue? Where should the text changes be applied/modified?
