### ISSUE TITLE
[ko]Translate docs/tasks/administer-cluster/limit-storage-consumption into Korean

### ISSUE THREAD

**Issue by dewble** [kubernetes/website#35200]
**This is a Feature Request**

**What would you like to be added**

Translate ```docs/tasks/administer-cluster/limit-storage-consumption``` into Korean

- Page: https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/
- File: https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/limit-storage-consumption.md

**Why is this needed**

Not translated yet

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #36147
- #36804
- #36810

/close
