### ISSUE TITLE
[ko] Translate `docs/tasks/administer-cluster/cluster-upgrade` to Korean

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/website#35239]
**This is a Feature Request**

**What Would you like to be added**
Translate docs/tasks/administer-cluster/cluster-upgrade to Korean

**Why is this needed**
Not translated yet

**page**
https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/

/language ko
/assign

**Comment by jihoon-seo** [comment]
감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #35441
- #36804
- #36810

/close
