### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/

### ISSUE THREAD

**Issue by hhv** [kubernetes/website#35251]
How about "consists of a control plane and a set of machines called nodes"? Learning k8s is hard enough without obfuscating verbosity. For non-managers it's best to say it as it is ;-).

Apart from that: "consists of the components that represent the control plane" suggests that there are components that *represent* a control pane, not *are* a control pane, and a set of nodes. So where is the control pane? I'm probably a big introvert and a nerd, but this confuses me to the point where I actually have to think about what this means... "In what way do the components represent the control pane? Where is the control pane itself? Am I not getting this? Probably not. It probably means these components are the control pane. Stupid me, of course that's what it means." So, while I could have understood what was meant in a split second, it takes me a couple of seconds of contemplation and a few minutes to suggest an improvement.

**Comment by sftim** [comment]
We could update the source of https://kubernetes.io/docs/concepts/overview/components/ to make that change.
Nice suggestion.

https://kubernetes.io/docs/concepts/overview/ is automatically generated. For a bigger improvement, we could move https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/ to https://kubernetes.io/docs/concepts/overview/ and configure a redirect.

/language en

**Comment by sftim** [comment]
/triage accepted
/help

If someone is planning to move this forward:
- move https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/ to https://kubernetes.io/docs/concepts/overview/
- configure a redirect from the old URL to the new URL (see `static/_redirects`)
- make sure that the updated https://kubernetes.io/docs/concepts/overview/ ends how you'd expect. It's likely that setting `no_list: true` in the [front matter](https://gohugo.io/content-management/front-matter/) will help.

**Comment by sftim** [comment]
Feel free to reply with questions.

**Comment by Rishit-dagli** [comment]
I would love to takee this
/assign

**Comment by mehabhalodiya** [comment]
/good-first-issue
For the first-timers, look https://github.com/kubernetes/website/issues/35251#issuecomment-1192783833
