### ISSUE TITLE
[ko] Translate `docs/tasks/administer-cluster/namespace` into Korean

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#35283]
**This is a Feature Request**

**What would you like to be added**

Translate `docs/tasks/administer-cluster/namespaces` into Korean.
link: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/

**Why is this needed**
It has not been translated into Korean yet.

**Comments**

/language ko
/assign

**Comment by seokho-son** [comment]
Thanks ! :)

/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #35302 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
