### ISSUE TITLE
[ko] Translate the docs/tasks/access-application-cluster 'create-external-load-balancer' into Korean

### ISSUE THREAD

**Issue by Seo-yul** [kubernetes/website#35289]
This is a Feature Request

What would you like to be added
Translate docs/tasks/access-application-cluster/create-external-load-balancer into Korean

◾ Page: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/
◾ File: https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/access-application-cluster/create-external-load-balancer.md

Why is this needed
Not translated yet

Comments
/language ko
/assign

**Comment by seokho-son** [comment]
Thanks!

/triage accepted
