### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by retif** [kubernetes/website#35293]
recommended [application/mysql/mysql-statefulset.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/mysql/mysql-statefulset.yaml) example contains error:

init container init-mysql fails to run, with the error "hostname command not found". you can see this in init-mysql logs

**Comment by utkarsh-singh1** [comment]
Hi @retif, have you followed all the pre-requisites required to run the following [tasks](https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#before-you-begin) in your local cluster.

**Comment by jihoon-seo** [comment]
It seems that this issue is a duplicate of #35432.

This issue was filed prior to #35432, but IMO #35432 has more information now.

**Comment by tengqm** [comment]
/close
Closing as a dup.
