### ISSUE TITLE
Adding windows node article missing

### ISSUE THREAD

**Issue by VikasAgarwal1984** [kubernetes/website#35323]
Adding Windows node article is missing from few days now. 
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

Reference:
http://web.archive.org/web/20220530090758/https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

**Comment by neolit123** [comment]
duplicate of https://github.com/kubernetes/website/issues/34476
