### ISSUE TITLE
A `.devcontainer` for kubernetes/website

### ISSUE THREAD

**Issue by Rishit-dagli** [kubernetes/website#35332]
**This is a Feature Request**

**What would you like to be added**

It would be particularly helpful if we could create a [`.devcontainer`](https://code.visualstudio.com/docs/remote/create-dev-container) for this repository.

**Why is this needed**

Motivated by seeing this [Slack message](https://kubernetes.slack.com/archives/C1J0BPD2M/p1658657369855849) creating a `.devcontainer` would greatly reduce the efforts for contributors to set up a development environment, greatly simplifying this process. [GitHub Codespaces](https://github.com/features/codespaces) also recognizes the `.devcontainer` while spinning up a new instance. This is also the recommended way to configure dev environments inside GitHub Codespaces reference: [here](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers).

Overall, I believe this could greatly help contributors to this repository.

**Comments**

I would love to take on the efforts to implement this if it sounds like a good idea.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

If we do this, will it be easy to make sure that the dev container setup is maintained?

**Comment by Rishit-dagli** [comment]
@sftim If it is possible (since I'm not an approver or reviewer) I would be open to maintaining this setup preferably with someone else from SIG Docs
