### ISSUE TITLE
[ko] Translate the glossary term 'Dockershim, Helm Chart, HostAliases ... etc' into Korean

### ISSUE THREAD

**Issue by Seo-yul** [kubernetes/website#35342]
This is a Feature Request

What would you like to be added
Translate docs/reference/glossary/ {{ some_file }} into Korean

◾ Page: https://kubernetes.io/ko/docs/reference/glossary/?all=true

- [x] Dockershim
◾ File: https://github.com/kubernetes/website/blob/dev-1.24-ko.2/content/en/docs/reference/glossary/dockershim.md
- [x] Helm Chart
◾ File: https://github.com/kubernetes/website/blob/dev-1.24-ko.2/content/en/docs/reference/glossary/helm-chart.md
- [x] HostAliases
◾ File: https://github.com/kubernetes/website/blob/dev-1.24-ko.2/content/en/docs/reference/glossary/host-aliases.md
- [x] Kubeadm
◾ File: https://github.com/kubernetes/website/blob/dev-1.24-ko.2/content/en/docs/reference/glossary/kubeadm.md

Why is this needed
Not translated yet

Comments
/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35358 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
