### ISSUE TITLE
Document Kubernetes release artifact file signatures

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/website#35341]
We require additional documentation as part of the Signing release artifacts KEP graduation: https://github.com/kubernetes/enhancements/issues/3031

Inspiration how to start on this task can be found in the container image page, which has been added for the alpha feature: https://github.com/kubernetes/website/pull/32184

cc @kubernetes/release-engineering if anyone wants to pick this up

/sig release
/triage accepted

**Comment by Verolop** [comment]
@saschagrunert I'll adopt this :)

**Comment by saschagrunert** [comment]
Thank you!

/assign @Verolop

**Comment by sftim** [comment]
/language en

I think we should document:
- what signatures you can expect to find (as a reference-type page)
- how to verify these signatures (as a task-type page)

**Comment by cathchu** [comment]
Hey there 👋 @saschagrunert , 1.25 Release Docs Shadow here!

Thanks for filing this placeholder. As a reminder, final docs PRs are due August 9th. Take a look at [Documenting a release](https://kubernetes.io/docs/contribute/new-content/new-features/#for-developers-or-other-sig-members) for additional information for the docs requirement for the release.

Thanks again!

**Comment by saschagrunert** [comment]
We will do this in v1.26, according to the KEP update proposed in https://github.com/kubernetes/enhancements/pull/3451

**Comment by saschagrunert** [comment]
@Verolop are you still open to work on this for 1.26?

**Comment by saschagrunert** [comment]
Done
