### ISSUE TITLE
[ko]Translate website/content/en/docs/reference/glossary/horizontal-pod-autoscaler.md into Korean

### ISSUE THREAD

**Issue by onestone9900** [kubernetes/website#35352]
This is a Feature Request

What would you like to be added
Translate website/content/en/docs/reference/glossary/horizontal-pod-autoscaler.md into Korean

Why is this needed
Not translated into Korean yet.

Comments
link to en entry: https://kubernetes.io/docs/reference/glossary/?operation=true#term-horizontal-pod-autoscaler
link to ko entry: https://kubernetes.io/ko/docs/reference/glossary/?operation=true#term-horizontal-pod-autoscaler

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35408 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
