### ISSUE TITLE
[ko] Translate the glossary term 'CIDR' into Korean

### ISSUE THREAD

**Issue by bart2001** [kubernetes/website#35357]
**This is a Feature Request**

**What would you like to be added**

- link to en entry: https://kubernetes.io/docs/reference/glossary/?all=true#term-cidr
- link to ko entry: https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-cidr

**Why is this needed**
Not translated yet

**Comments**

/language ko
/assign

**Comment by sftim** [comment]
I'd localize this (eg to 사이더), but I don't think _translate_ feels like the right thing. 사이더 is more like a transliteration.

**Comment by seokho-son** [comment]
/triage accepted

:)

**Comment by bart2001** [comment]
@sftim 
Thank you for your comment.
Commonly, I have seen developers and engineers in Korea using the term CIDR as English itself, so I left it in English :)

**Comment by jihoon-seo** [comment]
Resolved by
- #35359 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
