### ISSUE TITLE
Broken hyperlinks on Documentation Style Guide page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#35375]
**Problem:**
The texts [**Check required ports**](https://kubernetes.io/docs/contribute/style/style-guide/#check-required-ports) and [**here**](https://kubernetes.io/docs/contribute/style/style-guide/#check-required-ports) on [link](https://kubernetes.io/docs/contribute/style/style-guide/) is not pointing to the exact section and redirect to the same [page](https://kubernetes.io/docs/contribute/style/style-guide/#check-required-ports), it should point to this [link](https://kubernetes.io/docs/reference/ports-and-protocols/)

Check the page [Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/) for the problem.

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.

**Page to Update:**
https://kubernetes.io/docs/contribute/style/style-guide/
Update the link on the texts **Check required ports** and **here** to https://kubernetes.io/docs/reference/ports-and-protocols/ and not this link (https://kubernetes.io/docs/contribute/style/style-guide/#check-required-ports).

/kind document
/assign
/language en

**Comment by divya-mohan0209** [comment]
Hey @kadtendulkar , what we're trying to provide in the style guide is an example of how to write the text for links and I don't think we actually are intending to point to the link mentioned by you in the description.  

@sftim / @tengqm : Please correct me if I'm wrong here.

**Comment by shannonxtreme** [comment]
Yeah this is working as intended, the reader isn't meant to leave the page (which is why it redirects to the same page). It's an example of how "good" link text looks

**Comment by kadtendulkar** [comment]
Hello @shannonxtreme and @divya-mohan0209 , I referred to this [link](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports) and found the ports and protocols page.
If the reader is not supposed to redirect to some other page, then can we add a section as below as mentioned in the [link](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports)
```

Check required ports
These [required ports](https://kubernetes.io/docs/reference/ports-and-protocols/) need to be open in order for Kubernetes components to communicate with each other. You can use tools like netcat to check if a port is open. For example:

nc 127.0.0.1 6443
The pod network plugin you use may also require certain ports to be open. Since this differs with each pod network plugin, please see the documentation for the plugins about what port(s) those need.
```

**Comment by divya-mohan0209** [comment]
Hey @kadtendulkar, thank you for raising this issue. However, we do not need to add that section is precisely what Shannon & I are trying to convey.

The style guide wants to instruct people who create/submit improvements that instead of using vague text for hyperlinking like "See here" or "Check this out", the contributors must provide more context in the text by using phrases such as "Check required ports" etc. This **does not** require the text in the style guide to point to any specific section. It is just an example of what kind of text is acceptable when hyperlinking.

Trust that clarifies your query?

**Comment by kadtendulkar** [comment]
Hello @divya-mohan0209 , can I close the PR and issue both?

**Comment by divya-mohan0209** [comment]
Yes please. You may link it to my comment, during closure.
