### ISSUE TITLE
field is inside the `spec` link

### ISSUE THREAD

**Issue by bishal7679** [kubernetes/website#35382]
**This is a Feature Request**

- It would be better if **field** is outside the link following the same on the entire page.
![Screenshot (202)](https://user-images.githubusercontent.com/70086051/180843154-0fd61bac-aa4c-4a11-8c56-19a0972e9dce.png)

- And the extra semi colon should be removed
![Screenshot (203)](https://user-images.githubusercontent.com/70086051/180843473-e61eee0c-8f61-4628-8554-598b0938899b.png)

**What would you like to be added**

![Screenshot (204)](https://user-images.githubusercontent.com/70086051/180843939-404b04d0-2f50-40fe-8c57-963c1a27bc3e.png)

**Why is this needed**

It will look better
**Comments**
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#kubernetes-objects

**Comment by sftim** [comment]
I like the existing text. “`spec` field” seems like valid anchor text to me. Why isn't it right?

**Comment by shannonxtreme** [comment]
I agree with Tim here. The word field is an informative part of the link text (by clicking it, you'll learn more about the field).

**Comment by shurup** [comment]
I'll second Tim. [Google developer documentation style guide](https://developers.google.com/style/link-text) (it's just one of such examples) states:

> If the text includes a command or another element usually conveyed with code font, include the description of the code element in the link text.
> 
> **Recommended**: To create an instance with a custom hostname, run the gcloud instances create command with the [--hostname flag](https://cloud.google.com/compute/docs/instances/custom-hostname-vm#gcloud).
> 
> **Not recommended**: To create an instance with a custom hostname, run the gcloud instances create command with the [--hostname](https://cloud.google.com/compute/docs/instances/custom-hostname-vm#gcloud) flag.

**Comment by divya-mohan0209** [comment]
Hey @bishal7679 , we appreciate your time in suggesting an improvement. However, due to no response from your end, we're closing this issue. Whenever you have some free cycles to get back and respond with further context, we'll pick up from where we're currently leaving it. Thanks!
/close
