### ISSUE TITLE
Improvement for k8s.io/docs/reference/using-api/api-concepts/

### ISSUE THREAD

**Issue by stephen-dahl** [kubernetes/website#35381]
While reading Events https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-uris to learn how to construct api urls I found that the instructions here do not cover how paths for core resources are constructed, mainly that they start with `/api` instead of `/apis`. 

It hints at this with the `GET /api/v1/namespaces` example but it should be directly stated to be more clear.

after rereading my original post let me me more clear.
Core resources start with /api
all other resources start with /apis
I am asking for this destinction to be made more clear in the docs.

**Comment by stephen-dahl** [comment]
after rereading my original post let me me more clear.
Core resources start with /api
all other resources start with /apis
I am asking for this destinction to be made more clear in the docs.

**Comment by sftim** [comment]
@stephen-dahl would you be willing to edit the original description that you wrote for the issue, to include that clarification?
