### ISSUE TITLE
Add .hugo_build.lock file to .gitignore

### ISSUE THREAD

**Issue by jinnypark9393** [kubernetes/website#35406]
**This is a Feature Request**

**What would you like to be added**

I would like to add .hugo_build.lock to .gitignore.

**Why is this needed**

In my recent PR(https://github.com/kubernetes/website/pull/35273), I was told that unnecessary file, .hugo_build.lock was added in my commit. This hugo_build.lock file is automatically generated during local hugo build from hugo v0.89.0(https://gohugo.io/news/0.89.0-relnotes/#notes) and should not be included in the commit.

Thus, it would be great if we could add .hugo_build.lock to .gitignore so that others will not make mistake like me.

**Comments**

I double-confirmed that there is no duplicated PR(both open & closed PRs). This suggestion was already made in previous PR(https://github.com/kubernetes/website/pull/31721) but it hasn’t been applied yet(since there is no open/closed PR related to this, I guess the author of https://github.com/kubernetes/website/pull/31721 forgot to seperate PR).

/assign

**Comment by jinnypark9393** [comment]
I opened PR #35405

**Comment by shannonxtreme** [comment]
Lmao yes please 

/triage accepted

**Comment by jinnypark9393** [comment]
This issue has been resolved by #35405
