### ISSUE TITLE
[ko] Translate the glossary term 'Finalizer' into Korean

### ISSUE THREAD

**Issue by having-dlrow** [kubernetes/website#35427]
**This is a Feature Request**

**What would you like to be added**

Translate the glossary term 'Finalizer' into Korean

link to en entry: https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-finalizer
link to ko entry: https://kubernetes.io/ko/docs/reference/glossary/?fundamental=true#term-finalizer

**Why is this needed**
Not translated yet

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35549 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
