### ISSUE TITLE
[ko] Translate the glossary term `CNCF` into Korean

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#35435]
**This is a Feature Request**

**What would you like to be added**

Translate the glossary term 'CNCF' into Korean.

link to `en` entry: https://kubernetes.io/docs/reference/glossary/?community=true#cncf
link to `ko` entry: https://kubernetes.io/ko/docs/reference/glossary/?community=true#cncf

**Why is this needed**
It has not been translated into Korean yet.

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35496 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
