### ISSUE TITLE
`hostname` cmd is missing in `mysql:5.7` image

### ISSUE THREAD

**Issue by ouohh** [kubernetes/website#35432]
When I execute the command ‘kubectl apply -f https://k8s.io/examples/application/mysql/mysql-statefulset.yaml’ the following problem occurs
$ kubectl describe pods mysql-0
```
...
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  11s                default-scheduler  Successfully assigned default/mysql-0 to node3
  Normal   Pulled     11s (x2 over 12s)  kubelet            Container image "mysql:5.7" already present on machine
  Normal   Created    11s (x2 over 12s)  kubelet            Created container init-mysql
  Normal   Started    11s (x2 over 12s)  kubelet            Started container init-mysql
  Warning  BackOff    9s (x2 over 10s)   kubelet            Back-off restarting failed container
```
$ kubectl logs  mysql-0 init-mysql
```
++ hostname
bash: line 2: hostname: command not found
+ [[ '' =~ -([0-9]+)$ ]]
+ exit 1
```

**Comment by utkarsh-singh1** [comment]
Hi @ouohh, can you send the details about `kubectl get pods -l app=mysql --watch` .

**Comment by ouohh** [comment]
> Hi @ouohh, can you send the details about `kubectl get pods -l app=mysql --watch` .

$ get pods -l app=mysql --watch
NAME      READY   STATUS       RESTARTS      AGE
mysql-0   0/2     Init:Error   2 (27s ago)   28s
mysql-0   0/2     Init:CrashLoopBackOff   2 (14s ago)   29s
mysql-0   0/2     Init:Error              3 (25s ago)   40s
mysql-0   0/2     Init:CrashLoopBackOff   3 (14s ago)   55s
mysql-0   0/2     Init:Error              4 (47s ago)   88s
mysql-0   0/2     Init:CrashLoopBackOff   4 (10s ago)   99s
mysql-0   0/2     Init:Error              5 (90s ago)   2m59s
mysql-0   0/2     Init:CrashLoopBackOff   5 (15s ago)   3m15s

**Comment by utkarsh-singh1** [comment]
Hi @ouohh, CrashLoopBackOff error is causing your pod to be crashed in an endless loop, have you followed all the pre-requisites.

**Comment by ouohh** [comment]
Yes, I can run the mysql5.6 image; the log error indicates that mysql5.7 does not have the "hostname" command.

**Comment by interconnectix** [comment]
The latest working image that I found that I specified in my stateful set to work is 'image: mysql:5.7.36'

**Comment by vividcloudpark** [comment]
This is matter of Oracle's Mysql team, not K8s team. They changed default image's os base from  debian to Oracle linux. It seems to Oracle linux doesn't contains hostname package. You'd better to use `mysql:5.7-debian` tan `mysql:5.7` (They set default as Oracle one, former was debian one).

**Comment by jihoon-seo** [comment]
/retitle `hostname` cmd is missing in `mysql:5.7` image
