### ISSUE TITLE
[Ko] Translate /tasks/extend-kubernetes/socks5-proxy-access-api/ in Korean

### ISSUE THREAD

**Issue by nine01223** [kubernetes/website#35437]
This is a Feature Request

What would you like to be added

Translate /tasks/extend-kubernetes/socks5-proxy-access-api/ in Korean

Why is this needed

Comments
지난 1월 이슈 생성했으나 개인적인 사정으로 완료하지 못해 Close되었습니다.(정말 죄송합니다.)
k8s 문서 한글화에 꼭 기여하고 싶어 이슈 생성합니다. 28일 머지 이후 다음 브랜치 PR 목표입니다. 감사합니다. 🙏

Pages to Update
https://kubernetes.io/docs/tasks/extend-kubernetes/socks5-proxy-access-api

**Comment by jihoon-seo** [comment]
@nine01223 감사합니다!!
/triage accepted

**Comment by Seo-yul** [comment]
혹여, 개인사정이 아직 있으시다면 제가 이 이슈를 받을 수 있을까요?

**Comment by nine01223** [comment]
넵. 대신 받아주셔도 됩니다. 열정적 도움에 진심으로 감사드립니다.

**Comment by nine01223** [comment]
> 넵. 대신 받아주셔도 됩니다. 열정적 도움에 진심으로 감사드립니다.

**Comment by Seo-yul** [comment]
> > 넵. 대신 받아주셔도 됩니다. 열정적 도움에 진심으로 감사드립니다.

감사합니다

**Comment by jihoon-seo** [comment]
Resolved by
- #36614
- #36804
- #36810

/close
/unassign @nine01223
