### ISSUE TITLE
[ko] Translate the glossary term 'wg(working group)' into Korean

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/website#35443]
**This is a Feature Request**

**What Would you like to be added**
Translate docs/tasks/administer-cluster/cluster-upgrade to Korean

**Why is this needed**
Not translated yet

**page**
https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-wg

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35444 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
