### ISSUE TITLE
Broken links on Using a KMS provider for data encryption page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#35449]
**Problem:**
The texts [**service.pb.go**](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/service.pb.go) and [**service.proto**](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/service.proto) on [link](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider) is not working, it should point to these [service.pb.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/api.pb.go) and [service.proto](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/api.proto) respectively.

Check the page [Using a KMS provider for data encryption](https://kubernetes.io/docs/tasks/administer-cluster/kms-provider) for the problem.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kms-provider

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the texts **service.pg.go** to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/api.pb.go and **service.proto** to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/v1beta1/api.proto respectively.

/kind document
/assign
/language en

**Comment by sftim** [comment]
I would link to specific commits or releases, not `master`. The `master` branch is _not_ a stable, “permalink” friendly ref.

**Comment by mk46** [comment]
Addressed in https://github.com/kubernetes/website/pull/35450
/close
