### ISSUE TITLE
network-plugins: misleading requirements for CNI loopback plugin

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#35456]
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#loopback-cni says:

> In addition to the CNI plugin installed on the nodes for implementing the Kubernetes network model, Kubernetes also requires the container runtimes to provide a loopback interface `lo`. Implementing the loopback interface can be accomplished by re-using the [CNI loopback plugin](https://github.com/containernetworking/plugins/blob/master/plugins/main/loopback/loopback.go).

As of https://github.com/containernetworking/plugins/issues/759 the undocumented loopback plugin is planned for deprecation and the article is outdated in regards to cri-o.

**Comment by divya-mohan0209** [comment]
@dilyanpalauzov Thank you for flagging this! However, I think a modification would be warranted once the loopback plugin has been deprecated on containerd too.
