### ISSUE TITLE
[ko] Translate the glossary term 'SIG' into Korean

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/website#35460]
**This is a Feature Request**

**What would you like to be added**

Translate the glossary term 'SIG' into Korean

- link to `en` entry: https://kubernetes.io/docs/reference/glossary/?community=true#term-sig
- link to `ko` entry: https://kubernetes.io/ko/docs/reference/glossary/?community=true#term-sig

**Why is this needed**
Not translated yet

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35463 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
