### ISSUE TITLE
[ja] Translate concepts/architecture/control-plane-node-communication into Japanese

### ISSUE THREAD

**Issue by musaprg** [kubernetes/website#35470]
**This is a Feature Request**

**What would you like to be added**

Translate [concepts/architecture/control-plane-node-communication/](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/) into Japanese.

**Why is this needed**

This page has not been translated into Japanese.

**Comments**

/language ja

**Comment by t-inu** [comment]
This file for the original page was renamed from `master-node-communication.md` to `control-plane-node-communication.md`, and some updates.
ref: https://github.com/kubernetes/website/pull/20265

The file for the Japanese page is not renamed yet.
So, "マスターとノード間の通信" remains and "Communication between Nodes and the Control Plane" for ja does not exist.

Japanese page also needs to be updated in the same way.
/assign
