### ISSUE TITLE
[ko] Translate the glossary term 'Manifest' into Korean

### ISSUE THREAD

**Issue by WESTZERO115** [kubernetes/website#35479]
**This is a Feature Request**

**What would you like to be added**
Translate the glossary term 'Manifest' into Korean

**Why is this needed**
Not Translated into Korean yet.

**Comments**
link: https://kubernetes.io/docs/reference/glossary/?fundamental=true

/language ko
/assign

**Comment by seokho-son** [comment]
@WESTZERO115 
혹시 해당 작업에 어려움이 있으시면 알려주세요~ :)
(열었다가 닫으신 PR 흔적이 있어서.. ㅎㅎ)
