### ISSUE TITLE
Tabs are malformed in "Install and Set Up kubectl on Linux" page

### ISSUE THREAD

**Issue by avinal** [kubernetes/website#35482]
**This is a Bug Report**

**Problem:**

The tab here is malformed and clicking on it doesn't work. https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management Instead of switching in place the tabs are formed stacked. See the screenshot, the instruction for *Red Hat based distribution* is below the instruction for "Debian based distributions".
![image](https://user-images.githubusercontent.com/74113200/181478915-c4df1606-9cfa-43d4-87e4-76ae0d5cc600.png)

**Proposed Solution:**

The tabs must be properly rendered and should show the content in place.

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

**Comment by Shubham82** [comment]
I will take a look at it.

/assign

**Comment by Shubham82** [comment]
Fixed it here: #35504

**Comment by avinal** [comment]
Thanks

**Comment by Shubham82** [comment]
Welcome @avinal
