### ISSUE TITLE
[ko] Translate the glossary term 'Disruption' into Korean

### ISSUE THREAD

**Issue by cat-taesik** [kubernetes/website#35480]
**This is a Feature Request**

**What would you like to be added**

Translate the glossary term 'Disruption' into Korean

- link to en entry: https://kubernetes.io/docs/reference/glossary/?all=true#term-disruption
- link to ko entry: https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-disruption

**Why is this needed**
Not translated yet

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35488 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
