### ISSUE TITLE
.gitignore does not anchor ignored paths “public” and “resources”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#35487]
**This is a Feature Request**

**What would you like to be added**
Update the `.gitignore` to only ignore the directories `public` and `resources` at the top level of the repository. 

**Why is this needed**
If somebody wants to create a content directory named `resources`, that ignore will conflict. We should tidy it so it wouldn't.

**Comments**
/kind cleanup

Docs for `.gitignore`: https://git-scm.com/docs/gitignore

**Comment by bconfiden2** [comment]
Can you assign it to me..??  👀
