### ISSUE TITLE
[ko] Missing Korean translation in "Contributing new content"

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#35491]
**This is a Bug Report**

**Problem:**
Missing Korean translation in "Contributing new content"

https://kubernetes.io/ko/docs/contribute/new-content/#:~:text=Figure%20%2D%20Contributing%20new,information%20details%20follow.

> Figure - Contributing new content preparation
> 
> The figure above depicts the information you should know prior to submitting new content. The information details follow.

**Proposed Solution:**
Add Korean translation.
It is highly recommended that a **native Korean speaker** self-assigns for this issue.

**Page to Update:**
https://kubernetes.io/ko/docs/contribute/new-content/#:~:text=Figure%20%2D%20Contributing%20new,information%20details%20follow.

/language ko

**Comment by Veryfirstmoment** [comment]
@jihoon-seo I'll take care of this.
/assign
