### ISSUE TITLE
[ko] Translate the glossary term 'Proxy' into Korean

### ISSUE THREAD

**Issue by BrendenHJH** [kubernetes/website#35494]
**This is a Feature Request**

**What would you like to be added**

Translate the glossary term 'Proxy' into Korean

* link to en entry: https://kubernetes.io/docs/reference/glossary/?all=true#term-proxy
* link to ko entry: https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-proxy

**Why is this needed**
Not translated yet

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
/retitle [ko] Translate the glossary term 'Proxy' into Korean

**Comment by jihoon-seo** [comment]
Resolved by
- #35501 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
