### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by concrain** [kubernetes/website#35518]
Update your instructions.  2019 man WTF
xhive is long gone

https://github.com/kubernetes/minikube/issues/5481

**Comment by divya-mohan0209** [comment]
@concrain We appreciate you opening the issue. Could you provide more details about the lack of updates? It'd be helpful for those volunteering to work on this problem to have those details handy.

**Comment by divya-mohan0209** [comment]
Hello @concrain please could you provide more context?
