### ISSUE TITLE
[ko] Translate the glossary term 'Approver' into Korean

### ISSUE THREAD

**Issue by sangminK** [kubernetes/website#35546]
**This is a Feature Request**

**What would you like to be added**

Translate the glossary term 'Approver' into Korean

- link to en entry: https://kubernetes.io/docs/reference/glossary/?all=true#term-approver
- link to ko entry: https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-approver

**Why is this needed**
Not translated yet

**Comments**
/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #35561 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
