### ISSUE TITLE
Run a Replicated Stateful Application

### ISSUE THREAD

**Issue by dc-weizhenhua** [kubernetes/website#35544]
1、there is no `hostname` command in mysql:5.7;

**Comment by jihoon-seo** [comment]
It seems that this issue is a duplicate of #35432.

**Comment by dc-weizhenhua** [comment]
> It seems that this issue is a duplicate of #35432.

#35432.  is still open!  I  thought it's so obvious error，where there's no solution stiill!

**Comment by tengqm** [comment]
/close
Closing as a dup.
