### ISSUE TITLE
[ko] Translate the glossary term `Preemption` into Korean

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#35560]
**This is a Feature Request**

**What would you like to be added**

Translate the glossary term `Preemption` into Korean
link to `en` entry: https://kubernetes.io/docs/reference/glossary/?all=true#term-preemption
link to `ko` entry: https://kubernetes.io/ko/docs/reference/glossary/?all=true#term-preemption

**Why is this needed**
This has not been translated into Korean yet.

**Comments**

/assign
/language ko

**Comment by jihoon-seo** [comment]
Resolved by
- #35565 (→ `dev-1.24-ko.2`)
- #35767 (`dev-1.24-ko.2` → `main`)

/close
