### ISSUE TITLE
Issue in kubectl-commands.html file

### ISSUE THREAD

**Issue by alfein** [kubernetes/website#35577]
Hello team.  

Recently I noticed that this page: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-secret-tls-em- shows wrong command.  Instead of 

`kubectl create tls NAME --cert=path/to/cert/file --key=path/to/key/file [--dry-run=server|client|none]`

it should be 

`kubectl create secret tls NAME --cert=path/to/cert/file --key=path/to/key/file [--dry-run=server|client|none]`

I believe the fix should go into this file https://github.com/kubernetes/website/blob/9ba644e361972562c5f3d39b92dedc8128c439b2/static/docs/reference/generated/kubectl/kubectl-commands.html

Please review.

Thank you

**Comment by jihoon-seo** [comment]
- `kubectl create secret`
  - `kubectl create docker-registry` -> `kubectl create secret docker-registry`
  - `kubectl create generic` -> `kubectl create secret generic`
  - `kubectl create tls` -> `kubectl create secret tls`
- `kubectl create service`
  - `kubectl create clusterip` -> `kubectl create service clusterip`
  - `kubectl create externalname` -> `kubectl create service externalname`
  - `kubectl create loadbalancer` -> `kubectl create service loadbalancer`
  - `kubectl create nodeport` -> `kubectl create service nodeport`

Also see this:

https://github.com/kubernetes/website/pull/35586#issuecomment-1200367839
> This file (`website/static/docs/reference/generated/kubectl/kubectl-commands.html`) is auto-generated, please don't fix it here.

https://github.com/kubernetes/website/pull/35586#issuecomment-1200369137
> FWIW, the upstream source code is here: 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go#L93

**Comment by dipankardas011** [comment]
@jihoon-seo should this issue be closed?

**Comment by jihoon-seo** [comment]
@dipankardas011 
@NitishKumar06 closed his prior PR, and opened [another one in k/k](https://github.com/kubernetes/kubernetes/pull/111602).

IMO it would be good to keep this issue open until the error in K8s Docs has been resolved. 😊

/kind bug

**Comment by dipankardas011** [comment]
> @dipankardas011 
> @NitishKumar06 closed his prior PR, and opened [another one in k/k](https://github.com/kubernetes/kubernetes/pull/111602).
> 
> IMO it would be good to keep this issue open until the error in K8s Docs has been resolved. 😊
> 
> /kind bug

Okay 👍

**Comment by NitishKumar06** [comment]
@jihoon-seo Should the PR be opened in Kuberenetes/website?
