### ISSUE TITLE
themes/docsy submodule showing up in PRs

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35588]
**This is a Bug Report**

**Problem:**

The `themes/docsy` submodule shows up in Pull Requests. 

- [Example #1 of unwanted `themes/docsy` in PR](https://github.com/kubernetes/website/pull/35297/files#diff-878506240f798243feafb6a64f3d3b434b18431764903360b9e00b0cb6394f07)
- [Example #2 of unwanted `themes/docsy` in PR](https://github.com/kubernetes/website/pull/35123/files#diff-878506240f798243feafb6a64f3d3b434b18431764903360b9e00b0cb6394f07)

**Proposed Solution:**

The Please see [similar issue](https://github.com/thegooddocsproject/website-hugo/issues/6) and [its resolution](https://github.com/thegooddocsproject/website-hugo/pull/7).

**Page to Update:**
NA

**Comment by sftim** [comment]
Could we use [`blockade`](https://pkg.go.dev/k8s.io/test-infra/prow/plugins/blockade) to protect `/themes`? Changes there should be rare and need special review.

/remove-kind bug

People _attempting_ to update Docsy in a PR isn't really a bug. We could however document how to clear that when it happens; if this issue is a request for those docs, then I see it as more of a feature request.

**Comment by sftim** [comment]
@rolfedh which direction would you like this issue to take?

**Comment by rolfedh** [comment]
Thanks for asking @sftim. I think I haven't explained this issue well enough: The `themes/docsy` directory shows up unbidden when folks generate a preview of the `/hi` docs. They have no intention of creating or modifying that directory. 

I propose that we either [set up submodules correctly](https://github.com/thegooddocsproject/website-hugo/pull/7) or add `themes/*` to the `.gitignore` file.

**Comment by sftim** [comment]
I suspect that we have set up submodules correctly, but the Hindi branch doesn't incorporate the right changes. I might have some time to work on that.

We could [Use Docsy as a Hugo module](https://www.docsy.dev/docs/get-started/docsy-as-module/).
[Use a module for a theme](https://gohugo.io/hugo-modules/use-modules/#use-a-module-for-a-theme) explains how. If we've an appetite for a change, I'd go in that direction. Specifically I think I'd recommend [vendoring](https://gohugo.io/hugo-modules/use-modules/#vendor-your-modules) Docsy to make life simpler for contributors. However, we'd need to check that Docsy's license is on the Kubernetes allowlist.

**Comment by rolfedh** [comment]
This seems related: https://kubernetes.slack.com/archives/C1J0BPD2M/p1615938858002000

**Comment by rolfedh** [comment]
I just wiped/up-forked/recloned `kubernetes/website` to my local machine.
Running `$ hugo` or `$ hugo server` was generating a `Error: from config: failed to resolve output format "print" from site config` message.
Then, I ran `$ git submodule update --init --recursive --depth 1`. The error went away and the build completed normally.

**Comment by rolfedh** [comment]
Problem apparently solved.
