### ISSUE TITLE
[zh-cn] Discuess about 授权 and 鉴权 for translating authn/authz

### ISSUE THREAD

**Issue by Sea-n** [kubernetes/website#35584]
When re-syncing [auth/node.md](https://github.com/kubernetes/website/pull/35552), @windsonsea found that `authorizer` are being translated into "鉴权器" and "授权器" on the same page.

I am confused about which word would be better when looking for documents. So I think it would be great if we reach a rough consensus and write into the [glossary of terms](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD%E5%AF%B9%E7%85%A7) in the Mandarin localization guide.

## File counts
Including "鉴权": 56 files / 229 lines / 243 words
Including "授权": 68 files / 182 lines / 196 words
Including both terms: 31 files

## Mixed files
It's hard to tell the correctness of files including both terms without reviewing them, it will cost a lot of time.
So here is just the line count for occurrence of two terms.
<pre><code>鉴权  授权  總行數  檔案名稱
17   19    2357   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/access-authn-authz/rbac.md?plain=1">content/zh-cn/docs/reference/access-authn-authz/rbac.md</a>
5    6     558    <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources.md?plain=1">content/zh-cn/docs/concepts/extend-kubernetes/api-extension/custom-resources.md</a>
13   5     226    <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/access-authn-authz/node.md?plain=1">content/zh-cn/docs/reference/access-authn-authz/node.md</a>
4    7     526    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/administer-cluster/securing-a-cluster.md?plain=1">content/zh-cn/docs/tasks/administer-cluster/securing-a-cluster.md</a>
6    4     2410   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md?plain=1">content/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver.md</a>

3    25    1383   <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/security/pod-security-policy.md?plain=1">content/zh-cn/docs/concepts/security/pod-security-policy.md</a>
3    4     903    <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md?plain=1">content/zh-cn/docs/reference/access-authn-authz/kubelet-tls-bootstrapping.md</a>
3    4     1003   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md?plain=1">content/zh-cn/docs/reference/command-line-tools-reference/kube-scheduler.md</a>
7    3     1981   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md?plain=1">content/zh-cn/docs/reference/command-line-tools-reference/kube-controller-manager.md</a>
10   3     2033   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/access-authn-authz/authentication.md?plain=1">content/zh-cn/docs/reference/access-authn-authz/authentication.md</a>

2    4     1630   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/using-api/api-concepts.md?plain=1">content/zh-cn/docs/reference/using-api/api-concepts.md</a>
2    2     2513   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md?plain=1">content/zh-cn/docs/reference/command-line-tools-reference/kubelet.md</a>
2    2     1151   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md?plain=1">content/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details.md</a>
2    2     1091   <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/security/multi-tenancy.md?plain=1">content/zh-cn/docs/concepts/security/multi-tenancy.md</a>
3    2     1374   <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md?plain=1">content/zh-cn/docs/reference/access-authn-authz/admission-controllers.md</a>
15   2     603    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md?plain=1">content/zh-cn/docs/tasks/extend-kubernetes/configure-aggregation-layer.md</a>

1    4     849    <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md?plain=1">content/zh-cn/docs/reference/access-authn-authz/certificate-signing-requests.md</a>
1    3     668    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/configure-pod-container/migrate-from-psp.md?plain=1">content/zh-cn/docs/tasks/configure-pod-container/migrate-from-psp.md</a>
1    2     500    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/configure-pod-container/configure-gmsa.md?plain=1">content/zh-cn/docs/tasks/configure-pod-container/configure-gmsa.md</a>
1    2     147    <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/cluster-administration/_index.md?plain=1">content/zh-cn/docs/concepts/cluster-administration/_index.md</a>
1    1     1182   <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/architecture/nodes.md?plain=1">content/zh-cn/docs/concepts/architecture/nodes.md</a>
1    1     344    <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/cluster-administration/system-metrics.md?plain=1">content/zh-cn/docs/concepts/cluster-administration/system-metrics.md</a>
1    1     373    <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/security/rbac-good-practices.md?plain=1">content/zh-cn/docs/concepts/security/rbac-good-practices.md</a>
1    1     1140   <a href="https://git.k8s.io/website/content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md?plain=1">content/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md</a>
1    1     370    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/administer-cluster/controller-manager-leader-migration.md?plain=1">content/zh-cn/docs/tasks/administer-cluster/controller-manager-leader-migration.md</a>
1    1     431    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/administer-cluster/namespaces-walkthrough.md?plain=1">content/zh-cn/docs/tasks/administer-cluster/namespaces-walkthrough.md</a>
1    1     519    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/administer-cluster/namespaces.md?plain=1">content/zh-cn/docs/tasks/administer-cluster/namespaces.md</a>
1    1     645    <a href="https://git.k8s.io/website/content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md?plain=1">content/zh-cn/docs/tasks/configure-pod-container/configure-service-account.md</a>
2    1     2240   <a href="https://git.k8s.io/website/content/zh-cn/docs/concepts/configuration/secret.md?plain=1">content/zh-cn/docs/concepts/configuration/secret.md</a>
4    1     60     <a href="https://git.k8s.io/website/content/zh-cn/docs/reference/access-authn-authz/_index.md?plain=1">content/zh-cn/docs/reference/access-authn-authz/_index.md</a>
15   1     588    <a href="https://git.k8s.io/website/content/zh-cn/docs/setup/production-environment/_index.md?plain=1">content/zh-cn/docs/setup/production-environment/_index.md</a>
</code></pre>

**Comment by Sea-n** [comment]
Opinion:

I found [this 知乎專欄 article](https://zhuanlan.zhihu.com/p/201837368) (Security Framework: identification, authorization, authentication, and permission control).

As it said: 授權 mapping to authorization, and 鑑權 mapping to authentication.

**Comment by Sea-n** [comment]
According to the official bilingual vocabulary list of Taiwan (temporary unavailable for unknown reason):

[authorization](https://www.google.com/search?q=authorization+site%3Aterms.naer.edu.tw) is recommended to be translated to 授權 / 核准
[authentication](https://www.google.com/search?q=authentication+site%3Aterms.naer.edu.tw) is recommended to be translated to 驗證 / 認證 / 鑑別 / 鑑定 / 鑑認

(Just for the reference, it's not that suitable for `zh-cn` translation.)

**Comment by Sea-n** [comment]
Hope we can get inputs from active translators.

CC @windsonsea @tengqm @howieyuen @mengjiao-liu @ydFu

**Comment by windsonsea** [comment]
wow, in my understanding, current authentication is 身份验证  with less confusion.
Authorizer is recommended to use 鉴权器, and 授权 is for authorize and authorization.
---
For most people, authz (authorize, authorizer, authorization) is related to 授权 for their first impression. This may cause some review efforts.

**Comment by tengqm** [comment]
> current authentication is 身份验证 with less confusion.
> Authorizer is recommended to use 鉴权器, and 授权 is for authorize and authorization.

I agree.

**Comment by howieyuen** [comment]
> current authentication is 身份验证 with less confusion.
> Authorizer is recommended to use 鉴权器, and 授权 is for authorize and authorization.

+1

**Comment by ydFu** [comment]
> current authentication is 身份验证 with less confusion.
> 
> Authorizer is recommended to use 鉴权器, and 授权 is for authorize and authorization.

+1
I refer to the localized content of AKS and EKS, and hold the same opinion.

[ref1: AKS](https://docs.microsoft.com/zh-cn/azure/aks/operator-best-practices-identity)
[ref2: EKS](https://aws.amazon.com/cn/blogs/china/eks-certification-and-authorization-practice/)

/triage accepted

**Comment by Sea-n** [comment]
I think we all agree to the translation @windsonsea provided in [this comment](https://github.com/kubernetes/website/issues/35584#issuecomment-1200326024).

Hey @windsonsea, may I ask you to add it into the glossary of terms? 🙇‍♂️

https://github.com/kubernetes/website/blob/a3f48fd544836e2568a1fdac6481bf6f307acea5/content/zh-cn/docs/contribute/localization_zh.md?plain=1#L340-L350

**Comment by windsonsea** [comment]
Ok, let me have a try to add this glossary.
