### ISSUE TITLE
Outdated link on Release Managers page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#35604]
**Problem:**
The text [**Build Admins**](https://github.com/kubernetes/sig-release/blob/master/release-engineering/packaging.md) on [link](https://kubernetes.io/releases/release-managers/#handbooks) could be updated to [page](https://github.com/kubernetes/release/blob/master/hack/rapture/README.md).

Check the page [Release Managers](https://kubernetes.io/releases/release-managers/) for the problem.

**Page to Update:**
https://kubernetes.io/releases/release-managers/

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the text **Build Admins** to https://github.com/kubernetes/release/blob/master/hack/rapture/README.md and not this link (https://github.com/kubernetes/sig-release/blob/master/release-engineering/packaging.md).

/kind document
/assign
/language en

**Comment by sftim** [comment]
/retitle Outdated link on Release Managers page

**Comment by kadtendulkar** [comment]
Since PR is merged, I'm closing the issue.
/close
