### ISSUE TITLE
ValidatingWebhookConfiguration asterisks/wildcards do not appear correctly

### ISSUE THREAD

**Issue by benmoss** [kubernetes/website#35613]
**This is a Bug Report**

**Problem:**
Under `webhooks.rules.apiGroups` on the [API reference for ValidatingWebhookConfigurations](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1/), it reads:

> APIGroups is the API groups the resources belong to. '' is all groups. If '' is present, the length of the slice must be one. Required.

The [docstring from the code](https://github.com/kubernetes/kubernetes/blob/acc64759f5fc434f325756f438f676daa3f0ed28/pkg/apis/admissionregistration/types.go#L26-L28) reads 
```
APIGroups is the API groups the resources belong to. '*' is all groups.
If '*' is present, the length of the slice must be one.
Required.
```
(funny enough, GitHub also removes the asterisk if I use a quote instead of a code block)

It seems somehow the `'*'` is being converted into just `''`.

**Proposed Solution:**
Not sure how this part is generated, I tried to build the api-reference but am getting errors.

**Page to Update:**
https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1/
I wouldn't be surprised if this affects more than just this page.

**Comment by sftim** [comment]
Thanks. The generation of these documentation uses a lot of heuristics, and there's no clear agreement within the project about whether or not we can treat the upstream code as Markdown or not.

/triage accepted
However, this is really an issue with the code in https://github.com/kubernetes-sigs/reference-docs/

**Comment by bishal7679** [comment]
@benmoss I would like to work on that issue
Can you please tell me exactly what I have to change?

**Comment by benmoss** [comment]
If I knew what to change I would just change it 😄 . I don't know where the code that controls this is, @sftim suggested its in https://github.com/kubernetes-sigs/reference-docs/ but I'm not sure which part. I think it might be a slightly complicated problem since it sounds like the bug is arising from treating the Go comments as Markdown, and there's ambiguity as to whether that's okay or not.

**Comment by bishal7679** [comment]
@benmoss  I am looking a problem here is as it is starting the sentence '*' is not showing
but if we use '\*' instead of '*' it is showing correctly

**Comment by bishal7679** [comment]
`'\*'` instead of `'*'`

**Comment by benmoss** [comment]
I don't think we want to change the comments in the Go code, but I don't really know

**Comment by bishal7679** [comment]
@benmoss I am not saying to change in the Go code. I can use `'\*'` in README file

**Comment by tengqm** [comment]
The upstream source code has to be changed. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/admissionregistration/v1/types.go#L26-L27

There are many similar cases in the same file.

This is not an ideal solution. We could have a separate repo hosting the API specification because the API is the core of the container orchestration platform. We do not want the API specification to be generated from source code. However, that won't happen any time soon. We have to live in an imperfect world and carry on.

**Comment by sftim** [comment]
We might be able to improve things incrementally with more heuristics in the code generator. I don't object to those incremental improvements, but it's a _lot_ of effort per fixed `*`.

**Comment by tengqm** [comment]
> We might be able to improve things incrementally with more heuristics in the code generator. I don't object to those incremental improvements, but it's a _lot_ of effort per fixed `*`.

Do you mind elaborate the "heuristics" we can employ? A '*' can be used to for italics, it can be used to mark bullet items, and it can be used as a literal string.

**Comment by sftim** [comment]
We could give special treatment to quoted single asterisks:
```
foo bar (wibble): '*' != "wibble"
something something
_emphasized text_ more text *more emphasis*

---
# now this is YAML but the code generator wouldn't know that
# and that's OK
foo:
  bar: "example value"
  wibble: "*"
```

Some of those asterisks mean emphasis; others don't.

**Comment by tengqm** [comment]
@sftim Wow, what you are suggesting is already a syntax parser. We will have to tokenize the comment string(s) and identify cases where a `'*'`, `"*"`, `'*/scale'` or `'*/*'` sub-string shows up. At least, such strings must have an enclosing quotation marks (either single quotes or double quotes).

In my view, it is much more straightforward to fix cases like this in the source code (if we insist that docs come from source comments). We show case this to the developers and let the team know: "Hey, we are treating these comments seriously, as documents to be published. Please help write them in markdown style. What we have today is something semi-markdown, not recognized as correct syntax."

**Comment by sftim** [comment]
If I had a magic wand to make it happen, I'd pick doc comments that are explicitly identified as Markdown. The Rust model for these is great, and could be an inspiration on how to do something similar for this project (no need to change Golang itself).

If we could assume reliably that we're parsing Markdown, we get to draw on lots of existing, well-tested code for parsing, linting, etc.
However, we don't have that magic wand.

Both (all?) options are a compromise: accepting the toil of individual fixups, vs the [yak shaving](https://joi.ito.com/weblog/2005/03/05/yak-shaving.html) stack of steps that are increasingly far away from “fix this one asterisk”.
So, whilst I'm reluctant, I'm still OK with individual fixes to the upstream code comments.

**Comment by sftim** [comment]
/reopen
/priority backlog
/remove-lifecycle rotten

It's not urgent that we fix this. Nice if we can though.
