### ISSUE TITLE
CSI Volume Cloning

### ISSUE THREAD

**Issue by chao007** [kubernetes/website#35629]
Cloning is only supported within the same Storage Class.
Cloning has supported different storage class 
https://github.com/kubernetes-csi/external-provisioner/pull/699/commits/96700cb7637640bcef39fc9e70244fb71b9c5ab4

**Comment by sftim** [comment]
Hello @chao007 

It sounds like you might want to report that a web page is wrong. If that's right, what's the URL of the webpage? Also, could you quote or point out the text in that page that isn't right?

/language en
/triage needs-information

**Comment by Kartik494** [comment]
Hi @chao007 @sftim i would like to explain this issue if i am not wrong @chao007 wants to update this [page](https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/) . As https://github.com/kubernetes-csi/external-provisioner/pull/699 is merged so now users will be able to clone a volume with a different Storage Class. The destination volume no longer has to be the same storage class as the source. But in current documentation we have the behaviour as.

`Cloning is only supported within the same Storage Class.
Destination volume must be the same storage class as the source
`

**Comment by Kartik494** [comment]
I would like to work on this.
/assign

**Comment by chao007** [comment]
@sftim Sorry my bad.. 
Thanks for @Kartik494 pointing it.
