### ISSUE TITLE
Kubernetes API 概念

### ISSUE THREAD

**Issue by yueyi0618** [kubernetes/website#35628]
名字空间作用域的资源：
GET /apis/GROUP/VERSION/RESOURCETYPE - 返回所有名字空间中指定资源类型的全部实例的集合
GET /apis/GROUP/VERSION/namespaces/NAMESPACE/RESOURCETYPE - 返回名字空间 NAMESPACE 内给定资源类型的全部实例的集合

is '/apis/GROUP/VERSION/RESOURCETYPE' wrong？maybe '/apis/GROUP/VERSION/namespaces/RESOURCETYPE'?

**Comment by jihoon-seo** [comment]
- `zh` page: https://kubernetes.io/zh-cn/docs/reference/using-api/api-concepts/
- `en` page: https://kubernetes.io/docs/reference/using-api/api-concepts/

I guess that this issue might be `kind/support`.
