### ISSUE TITLE
[ko] Translate concepts/storage/projected-volumes into Korean

### ISSUE THREAD

**Issue by Seo-yul** [kubernetes/website#35623]
This is a Feature Request

What would you like to be added
Translate content/en/docs/concepts/storage/projected-volumes.md into Korean

◾ Page: https://kubernetes.io/docs/concepts/storage/projected-volumes/
◾ File: https://github.com/kubernetes/website/blob/dev-1.24-ko.3/content/en/docs/concepts/storage/projected-volumes.md

Why is this needed
Not translated yet

Comments
/language ko
/assign

**Comment by jihoon-seo** [comment]
Resolved by
- #36381
- #36804
- #36810

/close
