### ISSUE TITLE
Broken hyperlink on Pod Topology Spread Constraints page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#35643]
**Problem:**
The text [**API above**](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#api) on [link](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints) is not working, it should point to these https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-topologyspreadconstraints-with-nodeaffinity
Check the page [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints) for the problem.

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the text **API Above** to https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-topologyspreadconstraints-with-nodeaffinity and not to this [link](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#api).

/kind document
/assign
/language en

**Comment by sftim** [comment]
Thanks
/help

**Comment by Kartik494** [comment]
@kadtendulkar i think this issue has been addressed in this [PR](https://github.com/kubernetes/website/pull/36396) , so i think it's ok to close this issue now?
