### ISSUE TITLE
New pull request guides user to url that 404's

### ISSUE THREAD

**Issue by spurin** [kubernetes/website#35666]
**This is a Bug Report**

Hi Team,

Hope you're all doing well.  

**Problem:**

When raising a PR for kubernetes/website, the guiding text is as follows -

```
PLEASE title the FIRST commit appropriately, so that if you squash all your commits into one, the combined commit message makes sense.

For overall help on editing and submitting pull requests, visit:

https://kubernetes.io/docs/contribute/suggest-improvements/
```

The URL listed, sadly, gives a 404.

**Proposed Solution:**

Either we fix the target url or update to an alternative location.  Thoughts?

Best Regards

James Spurin

**Comment by sftim** [comment]
The URL https://kubernetes.io/docs/contribute/suggesting-improvements/ works. Fixes welcome.

**Comment by Babapool** [comment]
I would like to work on this issue. Thanks.
/assign
