### ISSUE TITLE
Master FAQ (Issue with /docs/tutorials/kubernetes-basics/cluster-intro/)

### ISSUE THREAD

**Issue by techtonik** [kubernetes/website#3566]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

These things are not clear:
1. Is Master a Node?

It is said that **A Node is a VM or a physical computer**. Master should run somewhere. Does it run on **Master Node** that is a VM or a physical computer, but without `kubelet`?

2. Can Master run on the same Node as containers?

I assume that Node is a VM or a physical machine.

3. If Master can be run on the same Node, can it be run as a Docker container sibling to worker containers?

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/

**Comment by ahmetb** [comment]
@techtonik broad: answer to your question is that kubernetes master is a software that runs on a node (a VM or a physical machine). Depending on the setup, kubernetes master may run as a Docker container, or a process directly on the operating system. You can run other containers on the node the master runs, but that is not preferred and nodes running the master often don’t run user workloads (again, depends on your setup).

Based on this answer, how do you think we can make this page better?

**Comment by techtonik** [comment]
@ahmetb 
![module_01_cluster_master](https://cloud.githubusercontent.com/assets/515889/25553752/d53aacc8-2cc4-11e7-8df1-51bf5c338377.png)
[master-node.zip](https://github.com/kubernetes/kubernetes.github.io/files/965973/master-node.zip)

**Comment by ahmetb** [comment]
@techtonik The problem I see (sort of) with this is that the users are not always necessarily exposed to the Kubernetes Master. In some cases (such as Google Container Engine) users do not see the master at all, as it is managed by the cloud provider.

But I see your confusion is around 1) where does the master run? is it a separate node 2) can other processes/containers run on the machine the master is hosted.

**Comment by techtonik** [comment]
It is still not clear - if master node can run user workloads, then it should be in a Docker container and also running `kubelet`, right?
