### ISSUE TITLE
Kustomize bug was documented as a feature

### ISSUE THREAD

**Issue by KnVerey** [kubernetes/website#35669]
**This is a Bug Report**

**Problem:**
Commit https://github.com/kubernetes/website/commit/b9da040a08373cf764f4e93df32df182bbd8a835 / PR https://github.com/kubernetes/website/pull/30348. That PR documented a bug in Kustomize as though it were a feature, and unfortunately nobody from the Kustomize team saw the PR.

The behaviour in question is considered very problematic and clearly undesirable, as it violates two Kustomize's core principles/guarantees: being a template-free solution and having no build-time side-effects. In fact, in Kustomize's own docs, this behaviour is explicitly documented as something Kustomize will *never* support: [Eschewed Features list](https://kubectl.docs.kubernetes.io/faq/kustomize/eschewedfeatures/#build-time-side-effects-from-cli-args-or-env-variables).

Both Kustomize maintainers agree on this point, and we were also able to confirm with the person who originally copied the offending code from kubectl that this behaviour came along with that code entirely by accident.

**Proposed Solution:**
- Revert the PR, with or without a warning about relying on the behaviour (I originally proposed a straight revert, and added the warning at the request of the docs team. I am happy either way, as long as we get this problematic recommendation down ASAP): https://github.com/kubernetes/website/pull/35522
- A warning is already being emitted when the behaviour occurs in the latest version of Kustomize: https://github.com/kubernetes-sigs/kustomize/pull/4730.

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

**Comment by sftim** [comment]
/priority important-longterm

We need to decide on exactly what the fix will look like.
/sig cli

**Comment by sftim** [comment]
/remove-priority important-longterm
/priority important-soon

after discussion with SIG CLI

**Comment by nikitar** [comment]
It seems the issue has been addressed and can be closed, correct? I.e. the documentation change is reverted and a warning is added to Kustomize. Is there anything else that needs to be done?

(Came across this by browsing priority/important-soon)

**Comment by sftim** [comment]
Hi @sliekens 

GitHub is not the right place for support requests.

If you're mainly looking for advice, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by sftim** [comment]
/close

This issue is addressed.

**Comment by sliekens** [comment]
@sftim fair, but you could still make a general recommendation for users who were relying on removed functionality.
