### ISSUE TITLE
Localize content/en/docs/reference/scheduling/_index.md into Hindi

### ISSUE THREAD

**Issue by taniaduggal** [kubernetes/website#35663]
/assign
/needs-triage

**Comment by jihoon-seo** [comment]
`en` page: https://kubernetes.io/docs/reference/scheduling/
/language hi

**Comment by taniaduggal** [comment]
@anubha-v-ardhan needs triage.

**Comment by Babapool** [comment]
This issue has been resolved by PR #36061 (which has now been merged). This issue can now be closed. Thanks.
/close
