### ISSUE TITLE
[ko] Translate `docs/concepts/overview/working-with-objects/finalizers.md` into Korean

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#35668]
**This is a Feature Request**

**What would you like to be added**

Translate `docs/concepts/overview/working-with-objects/finalizers.md` into Korean.

- Page: https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/
- File: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/overview/working-with-objects/finalizers.md

**Why is this needed**
This has not been translated into Korean yet.

**Comments**

/assign
/language ko

**Comment by jihoon-seo** [comment]
@kyungjin99 감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #35822
- #36804
- #36810

/close
