### ISSUE TITLE
Connecting Applications with Services

### ISSUE THREAD

**Issue by theluke** [kubernetes/website#35697]
Hello, 
All previous steps work fine, but when I run the command 
` kubectl exec curl-deployment-646445496f-8xlnk  -- curl https://my-nginx --cacert /etc/nginx/ssl/tls.crt` 
I receive this error
`curl: (51) SSL: certificate subject name 'nginxsvc' does not match target host name 'my-nginx'`
I am on ubuntu 20
What am I doing wrong?

**Comment by sftim** [comment]
This is a duplicate I think (see above mention)
/triage duplicate

**Comment by mehabhalodiya** [comment]
Per [this comment](https://github.com/kubernetes/website/issues/35697#issuecomment-1205571392), closing this issue. Thanks!

/close
