### ISSUE TITLE
Deploy and Access the Kubernetes Dashboard

### ISSUE THREAD

**Issue by rameez523** [kubernetes/website#35709]
I applied istio mesh service rules to access the Kubernetes cluster from the public subdomain but I am getting this error.

Client sent an HTTP request to an HTTPS server.

**Comment by sftim** [comment]
/kind support

I think this is a request for help or advice.

**Comment by utkarsh-singh1** [comment]
Hi @rammez, can you send your istio config file.

**Comment by utkarsh-singh1** [comment]
You can find solution for this error here - https://istio.io/latest/docs/ops/common-problems/network-issues/#sending-https-to-an-http-port

**Comment by sftim** [comment]
GitHub is not the right place for support requests.

If you're looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
