### ISSUE TITLE
使用 Service 连接到应用

### ISSUE THREAD

**Issue by yantianpi** [kubernetes/website#35701]
创建service节的“ targetPort”和‘port’解释反了

**Comment by mengjiao-liu** [comment]
page：
https://kubernetes.io/zh-cn/docs/concepts/services-networking/connect-applications-service/#%E5%88%9B%E5%BB%BA-service

I checked the code, there should be no explanation error, the specific code location is as follows:

`targetPort`
https://github.com/kubernetes/kubernetes/blob/bd9444c1cfd438690dc21c31404dd79ab60dc6cb/staging/src/k8s.io/api/core/v1/types.go#L4632

`port`:
https://github.com/kubernetes/kubernetes/blob/bd9444c1cfd438690dc21c31404dd79ab60dc6cb/staging/src/k8s.io/api/core/v1/types.go#L4621

**Comment by mengjiao-liu** [comment]
Feel free to reopen it if you have any questions.
/close
