### ISSUE TITLE
Интерактивный урок - Изучение приложения

### ISSUE THREAD

**Issue by morooshka** [kubernetes/website#35748]
Hi kubernetes team!
Hope this finds you well.
While following the examples I was doing the same steps on my local minikube deployment as well as in the web terminal too. On the module 3 step 2 I faced a problem: the command
```
curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/
```
reported nothing on my local installation, while it was working right in the web terminal. I discovered with `kubectl describe deployments` that my local deployment has no ports set, while your web one had the following:
```
    Port:         8080/TCP
    Host Port:    0/TCP
```
After editing the local deployment adding this:
```
        ports:
        - containerPort: 8080
          protocol: TCP
```
the problem was gone.
Could you please explain why I had the different deployment configs locally and in the web?
Thank you

**Comment by bishal7679** [comment]
@morooshka Could you provide the yaml file in which you added these two line?

**Comment by sftim** [comment]
I assume you were working through https://kubernetes.io/ru/docs/tutorials/kubernetes-basics/explore/explore-interactive/ @morooshka 

(When you file an issue about a web page, it's really useful to mention the URL of that web page).

My guess is that the two scenarios have got out of sync. This will show up for somebody following along locally but not for someone trying them online within Katacoda.

The source code for these scenarios is in https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios, if somebody would like to check.

**Comment by morooshka** [comment]
@bishal7679 please find file attached, line 163
[deployment.txt](https://github.com/kubernetes/website/files/9275729/deployment.txt)
@sftim you are quite right about the web page. Thank you, I will follow your advice
