### ISSUE TITLE
Update `.gitignore` to ignore `.hugo_build.lock`

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35749]
**This is a Bug Report**

**Problem:**

For myself and other folks working on the `/hi` localization, generating a preview of the docs locally seems to add `.hugo_build.lock` file to our pull requests.

**Proposed Solution:**

Update `.gitignore` to reject `.hugo_build.lock`

**Page to Update:**
`.gitignore`

**Comment by rolfedh** [comment]
@a-mccarthy @bradtopol Do you have any indications that this might be an issue for other localization teams?

**Comment by sftim** [comment]
This change would **not** be specific to Hindi.

I run Hugo in a container, where there's no `.hugo_build.lock` generated - at least on the _main_ branch. I've also updated the Hindi branch just recently to incorporate updates from _main_. Maybe this isn't needed any more?

However, if it does help I'm still happy to see the change made.

/retitle Update `.gitignore` to ignore `.hugo_build.lock`
/priority awaiting-more-evidence

/remove-kind bug
/kind feature

**Comment by rolfedh** [comment]
@sftim `.gitignore` in `/main` contains `.hugo_build.lock`:
https://github.com/kubernetes/website/blob/f53d403591a3df439060cf4f0673c91a5dfa3dd2/.gitignore#L32

**Comment by rolfedh** [comment]
Please see the related PR, https://github.com/kubernetes/website/pull/35405 for background.

**Comment by rolfedh** [comment]
> This change would **not** be specific to Hindi.

I believe this issue is a problem for `dev-1.22-hi.1` and any other localization branches whose `.gitignore` files were last updated from `main` before https://github.com/kubernetes/website/pull/35405.

**Comment by rolfedh** [comment]
@sftim What do you think should be the next course of action?

**Comment by Sea-n** [comment]
The `.hugo_build.lock` file have just added to `.gitignore` file 2 weeks ago.
- #35405

I think you should merge `main` to `dev-1.22-hi.1` instead.

**Comment by rolfedh** [comment]
@Sea-n, both you and @sftim ([here](https://github.com/kubernetes/website/pull/35752#issuecomment-1207242290)) suggest merging `main` to `dev-1.22-hi.1`. 

This makes me nervous because I am unfamiliar with how kubernetes/website localization teams handle these things. 

I've created an example PR to illustrte the potential changes this merge might introduce here:  https://github.com/kubernetes/website/pull/35759

Is this what you recommend?

**Comment by rolfedh** [comment]
Thanks for your advice. I see this branch has the relevant update now. I apologize for not spotting that sooner.

https://github.com/kubernetes/website/blob/3692941165eecce44fb929643ebcba0047da5d9a/.gitignore#L32
