### ISSUE TITLE
Add `package.json` to `.gitignore`

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35769]
**Problem:**

`package.json` is missing from `.gitignore`. As a result, after you build docs using `$ hugo`, running `$ git status` shows   `modified:   package.json` among your unstaged changes. 

**Proposed Solution:**

Add `package.json` to `.gitignore`

**Comment by Sea-n** [comment]
I have left some comments in your PR #35770.

If you think it's an issue to discuss, then don't open PR immediately after you filed an issue.
If you think it's a trivial thing to do, then maybe no need to open an issue with duplicated title.

I'm afraid of the comments separated into two place will make us hard to discuss.

**Comment by sftim** [comment]
@rolfedh why is this a bug? (what are the symptoms?)

**Comment by rolfedh** [comment]
@sftim if one considers "contributor" a valid user role for the `website` repo, then the behavior described in the "Problem" section is a bug. That is, having unwanted files showing up in PRs is "an incorrect or unexpected result, or to behave in unintended ways." I wouldn't mind using a different issue category, but didn't see one that fit better. Which button would you use for issues like this?

**Comment by rolfedh** [comment]
Maybe not needed.
