### ISSUE TITLE
Update config.toml with `languageName = "हिन्दी (Hindi)"`

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35762]
In `dev-1.22-hi.1`, update `languageName = "हिन्दी"` to use the standard naming convention: `languageName = "हिन्दी (Hindi)"`.

Although this change is [already present in the `main` branch](https://github.com/kubernetes/website/blob/060218a16f65066d9d46ade60a73f952846bf9cb/config.toml#L446), we can't simply merge `main` to  `dev-1.22-hi.1` because doing so might disable Hindi where it is needed:

```
$ git diff dev-1.22-hi.1 main -- config.toml
diff --git a/config.toml b/config.toml
index 4b030df417..1f80097163 100644
--- a/config.toml
+++ b/config.toml
@@ -30,7 +30,8 @@ pygmentsStyle = "emacs"
 enableGitInfo = true
 
 # Norwegian ("no") is sometimes but not currently used for testing.
-disableLanguages = ["no"]
+# Hindi is disabled because it's currently in development.
+disableLanguages = ["hi", "no"]
 
 [caches]
  [caches.assets]
@@ -441,16 +442,15 @@ language_alternatives = ["en"]
 
 [languages.hi]
 title = "Kubernetes"
-description = "प्रोडक्शन-ग्रेड कंटेनर ऑर्केस्ट्रेशन"
-languageName = "हिन्दी"
+description = "Production-Grade Container Orchestration"
+languageName = "हिन्दी (Hindi)"
...
```

**Comment by NitishKumar06** [comment]
@rolfedh Should the changes be pushed to the `dev-1.22-hi.1` branch?

**Comment by rolfedh** [comment]
Hi @NitishKumar06, after I created this issue, I saw this PR and added a comment that I hope will fix the issue: https://github.com/kubernetes/website/pull/29679/files#r939666948
