### ISSUE TITLE
Frequent build failures (Build exceeded maximum allowed runtime)

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#35780]
**This is a Bug Report**

**Problem:**

I've seen several times where the build from Netlify in PR fails without a build error.

In this case, Netlify log ends with following message.

`Build exceeded maximum allowed runtime`

Usually when this happens to a PR, we ask the contributor to push additional or changed commit (meaningless commit) so that netlify restarts a build. 
 - Update the latest commit just to trigger a build test in the PR again.
    ```bash
    git commit --amend --date=now
    ```
 - Push the updated commit to your origin to update the PR. (you need to add `-f` option)
    ```bash
    git push {remote-of-your-forked-repo-(origin)} {your-feature-branch}
    ```

But, it is an inconvenient process.

--- 

Example of **failure case**,

Netlify log of a PR
https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/62ee857fea100d00089f626a 
(the log in the link can be changed and may not available soon according to the PR status. So, please see the following capture)

> ```
> 12:15:36 AM: ────────────────────────────────────────────────────────────────
> 12:15:36 AM:   1. build.command from netlify.toml                            
> 12:15:36 AM: ────────────────────────────────────────────────────────────────
> 12:15:36 AM: ​
> 12:15:36 AM: $ git submodule update --init --recursive --depth 1 && make deploy-preview
> 12:15:36 AM: hugo --enableGitInfo --buildFuture --environment preview -b https://deploy-preview-35751--kubernetes-io-main-staging.netlify.app/
> 12:15:36 AM: Start building sites …
> 12:15:36 AM: hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
> 12:15:42 AM: WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
> 12:51:12 AM: Build exceeded maximum allowed runtime
> ```

Build is **not finished within 36 minutes** in this case.

--- 
In a **normal case**,
Log: https://app.netlify.com/sites/k8s-dev-ko/deploys/62f0c6d876c94d000aae31c4

> ```
> 5:19:13 PM: ────────────────────────────────────────────────────────────────
> 5:19:13 PM:   1. build.command from netlify.toml                            
> 5:19:13 PM: ────────────────────────────────────────────────────────────────
> 5:19:13 PM: ​
> 5:19:13 PM: $ git submodule update --init --recursive --depth 1 && make deploy-preview
> 5:19:13 PM: hugo --enableGitInfo --buildFuture --environment preview -b https://deploy-preview-35767--k8s-dev-ko.netlify.app/
> 5:19:14 PM: Start building sites …
> 5:19:14 PM: hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
> ```
&hellip;

> ```
> 5:19:34 PM: Total in 20467 ms
> 5:19:34 PM: ​
> 5:19:34 PM: (build.command completed in 20.8s)
> 5:19:34 PM: ​
> 5:19:34 PM: ────────────────────────────────────────────────────────────────
> 5:19:34 PM:   2. Functions bundling                                         
> 5:19:34 PM: ────────────────────────────────────────────────────────────────
> ```
&hellip;

> ```
> 5:19:34 PM: (Functions bundling completed in 1ms)
> 5:19:34 PM: ​
> 5:19:34 PM: ────────────────────────────────────────────────────────────────
> 5:19:34 PM:   3. Deploy site                                                
> 5:19:34 PM: ────────────────────────────────────────────────────────────────
> ```
&hellip;

> ```
> 5:19:51 PM: ​
> 5:19:51 PM: (Deploy site completed in 16.8s)
> 5:19:51 PM: ​
> 5:19:51 PM: ────────────────────────────────────────────────────────────────
> 5:19:51 PM:   Netlify Build Complete                                        
> 5:19:51 PM: ────────────────────────────────────────────────────────────────
> 5:19:51 PM: ​
> 5:19:51 PM: (Netlify Build completed in 37.7s)
> 5:19:51 PM: Caching artifacts
> ```
&hellip;

> ```
> 5:22:24 PM: Post processing done
> 5:22:27 PM: Site is live ✨
> ```

Build is **finished less than 1 minutes** in a normal case.

---

**Proposed Solution:**

I don't have an answer for this bug yet, maybe we can check following.

 - need to investigate why build process is delayed or slower.
 - update configurations if necessary (@tengqm suggested #35773 already)
 - check any problematic short codes or configurations
 - check related Netlify configurations (ref: https://answers.netlify.com/search?q=Build%20exceeded%20maximum%20allowed%20runtime)

**Comment by seokho-son** [comment]
Since #35773 has been merged, I hope this issue has been resolved. (but we are not sure)
If I don't experience this issue anymore (for a while), I will close the issue. :)

**Comment by sftim** [comment]
/priority important-longterm
We do have work-arounds, but it's better if contributors don't have to learn those.

It's OK to lower or raise this priority.

**Comment by sftim** [comment]
I think the failures happen when a _Netlify_ build timeout is reached, BTW.

**Comment by jihoon-seo** [comment]
I found a PR in which the error persists.
- #35882
- https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/62f579dd3def490008991bd0

The `timeout` is `"180s"` in the feature branch of that PR.
https://github.com/jpbetz/website/blob/fix-etcd-repair-steps/config.toml#L18
https://github.com/jpbetz/website/blob/8d9e9a675bd524db812ba7f4cba27d41f0f8b4f8/config.toml#L18

**Comment by tengqm** [comment]
Alright, let's bump the timeout value again?

**Comment by seokho-son** [comment]
> I think the failures happen when a _Netlify_ build timeout is reached, BTW.

@sftim 
I think so too. _Netlify_ service seems to limit time for runtime (build ..) Maybe  `the default runtime is 15 minutes`.

> [perry](https://answers.netlify.com/u/perry)   [Netlify Alumni](https://answers.netlify.com/g/netlify_alumni) [Jun 18](https://answers.netlify.com/t/build-exceeded-maximum-allowed-runtime-gatsby-4-16-0/68407/2)
> hi there, i am going to guess that your build time will get shorter once you have a complete build and we don’t need to download dependencies and have something in cache.
> 
> the default runtime is 15 minutes - if you add a credit card to your account so that we can bill for additional build minutes should they become necessary, we can increase your build time sufficiently so you can get a build going. let me know if you want me to do that!

@tengqm @jihoon-seo 
(I guess) The problem is the build time of our website become very slow or pended occasionally. Eventually reaches to a runtime timeout of Netlify.
I am not sure we can experience this situation in local build (not Netlify).

We need to check why the build time of our website become very slow or pended occasionally. :)

**Comment by tengqm** [comment]
Yup. Just notice another case: https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/62f6dc1623987b0008f92501

The build took more than 35 minutes. There must be something wrong in GoHugo:

```
7:09:43 AM: Start building sites …
7:09:43 AM: hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
7:09:55 AM: WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
7:45:04 AM: Build exceeded maximum allowed runtime
```

**Comment by sftim** [comment]
This could be:
- a Hugo bug
- a (serious) “noisy neighbor” issue at Netlify

Would anyone like to try instrumenting Hugo or setting up to build with more debug info in Netlify?

**Comment by Sea-n** [comment]
As @tengqm's PR #36145 merged, it seems there are no other build errors occurred.
- #36145

Maybe it's time to close this issue.

**Comment by seokho-son** [comment]
Hi @Sea-n 

I saw this case today again.
https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/630c2f1f8127f50008098e59 
It seems the problem hasn't been fully resolved yet.

I heard @having-dlrow is also trying to find out cause of this issue (testing Hugo build locally with debug mode). :)

**Comment by having-dlrow** [comment]
1. Why don’t we ask netlify ?
    1. It doesn’t seem to be container resource limit problem,  but you know, Temporarily **node performance could be decreased** or **netlify could limit branch deploy count**.
        1. I roughly supposed netlify container resource based on these metrics. And it seems to be enough !
            1. netlify container’s cpu.cfs_quota_us : 0.4 cpu
            2. netlify container’s cpu.shares : 4core ( suppose.  6core 中 4core allocated )
            3. netlify container’s  memory.usage_in_bytes :  1G
            4. netlify container’s  memory.limit_in_bytes : 8G
2. For reosolving the issue, I think we need a log when they occured
    1. `--debug` and  `--templateMetrics`  let us watch what is happend during build. 
    2. Until the timeout error has occured again, **Why don’t we leave  `--debug` and  `--templateMetrics`  into `deploy-preview` command**. And then persistently watch logs ( It means editing the Make file and merging into main branch )
        
        ( I know you guys had tried debug, but it doesn’t merged into main branch  : https://github.com/kubernetes/website/pull/36103 )
        

**In short,** we can edit [https://github.com/kubernetes/website/blob/main/Makefile#L37](https://github.com/kubernetes/website/blob/main/Makefile#L37) like below

```java
deploy-preview:
	+ hugo --debug --templateMetrics --cleanDestinationDir --enableGitInfo --buildFuture --environment preview -b $(DEPLOY_PRIME_URL)
	- hugo --cleanDestinationDir --enableGitInfo --buildFuture --environment preview -b $(DEPLOY_PRIME_URL)
```

**Comment by tengqm** [comment]
This is an interesting topic. We don't know yet what is causing the hugo build problem so we tried to turn on the `--debug` flag. The observation was that we always get stuck by a few files that are empty (place holders). We tried to fix those files and hoped that could have solved the problem, but it turned out the problem is not limited to those files.
Let's start the game again.

**Comment by a-mccarthy** [comment]
@having-dlrow and @seokho-son thanks for bringing this issue up in the localization meeting yesterday. 

If you feel this is impactful enough, can you add a message to the [#sig-docs-localizations](https://kubernetes.slack.com/archives/C0191RDKHU1)with a summary of the issue and any steps to resolve the issue. I'd like to make sure all localization leads are aware of the issue and what to do if they notice this on their PRs. Thanks! cc: @bradtopol

**Comment by having-dlrow** [comment]
@a-mccarthy I shared to #sig-doc-localizations. 
Thank you for your suggestion.

It seems that the issue was not explained properly due to the short time at the last meeting.

After sharing enough, I think it would be good if the test could proceed.
Therefore, there is a document organized by looking at the issue, so I would like to share it. 
[sharing doc](https://bit.ly/3RPYG1k) 

cc: @bradtopol, @seokho-son

**Comment by Sea-n** [comment]
Still happening (ref to #38642)

/remove-lifecycle stale

**Comment by a-mccarthy** [comment]
Have we tried to reach out to Netlify support to help troubleshoot this issue? I'm still seeing the occasional failures, so I think its worth asking Netlify if they have any ideas on how to resolve this.

**Comment by tengqm** [comment]
I've been trying to attacking this via a trial-and-error approach.
PR #36741 is used as a tool for debugging this issue.
Unfortunately, the timeout is not so predictable.
In the few occasions where a timeout did occur, the build hangs when processing a `_index.html` page under some localization directories.
This observation has led me to another experiment, PR #38834, which tries to replace `_index.html` file by a `_index.md` file. `_index.html` is mentioned by Docsy but not Hugo. I'm not sure if that has some implications.
PR #38834 was not merged yet. I'm not sure what else I can do here.

**Comment by a-mccarthy** [comment]
@tengqm thanks for the update and for working on this issue! I keep hitting this is my PRs which prompted me to reach out in the issue :) 

Do you think this is Hugo/Docsy related only issue, or could Netlify be a factor?

**Comment by tengqm** [comment]
> @tengqm thanks for the update and for working on this issue! I keep hitting this is my PRs which prompted me to reach out in the issue :)
> 
> Do you think this is Hugo/Docsy related only issue, or could Netlify be a factor?

I not sure about this yet. This kind of transient timeout errors only surged during the past year. There is yet no evidence for us to blame Hugo/Docsy or Netlify, or both.

**Comment by divya-mohan0209** [comment]
@tengqm Maybe something worth noting is that the issue started popping up since Feb 5th last year per the emails sent to the K8s SIG Docs lead google group. 

Thread: https://groups.google.com/g/k8s-sig-docs-leads/c/f5ASIF-Je0c 

I know this might be long-drawn, but one of the ways we could potentially investigate is what changed since then. Either at the netlify end and/or at our end wrt config.

**Comment by tengqm** [comment]
I've checked the netlify best practices page but there seems no hint on occasional built timeout.

**Comment by sftim** [comment]
I've assumed we'll need to liaise with Netlify for troubleshooting help.

**Comment by sftim** [comment]
I sent a support message to Netlify just now.

**Comment by sftim** [comment]
3 recent deploys that failed:
- https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/63d9196632a3a20057975bb6
- https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/63d9062ad4b6b600091923ed
- https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/63d9050fe0252c0008bbb311

**Comment by sftim** [comment]
These failures occur for release deploys (`main` branch) and for deploy previews. Most succeed, but not all.

**Comment by sftim** [comment]
<details>
<summary>Example build log excerpt</summary>
<pre>
12:09:57 PM: build-image version: 1ca34a93198b041e44214013884c57d146a23fed (focal)
12:09:57 PM: build-image tag: v4.16.4
12:09:57 PM: buildbot version: 5d70ebdb976733297fb4c90b41002389a248e2df
12:09:57 PM: Fetching cached dependencies
12:09:57 PM: Starting to download cache of 681.8MB
12:10:01 PM: Finished downloading cache in 4.47s
12:10:01 PM: Starting to extract cache
12:10:03 PM: Finished extracting cache in 1.84s
12:10:03 PM: Finished fetching cache in 6.388s
12:10:03 PM: Starting to prepare the repo for build
12:10:04 PM: Preparing Git Reference refs/heads/main
12:10:06 PM: Parsing package.json dependencies
12:10:07 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'functions' versus '' in the Netlify UI
12:10:07 PM: Different build command detected, going to use the one specified in the Netlify configuration file: 'git submodule update --init --recursive --depth 1 && make production-build' versus 'hugo' in the Netlify UI
12:10:07 PM: Starting build script
12:10:07 PM: Installing dependencies
12:10:07 PM: Python version set to 2.7
12:10:07 PM: Started restoring cached Node.js version
12:10:08 PM: Finished restoring cached Node.js version
12:10:08 PM: v10.20.0 is already installed.
12:10:08 PM: Now using node v10.20.0 (npm v6.14.4)
12:10:08 PM: Started restoring cached build plugins
12:10:08 PM: Finished restoring cached build plugins
12:10:08 PM: Attempting Ruby version 3.0.1, read from environment
12:10:09 PM: Started restoring cached Ruby version
12:10:09 PM: Finished restoring cached Ruby version
12:10:09 PM: Using Ruby version 3.0.1
12:10:09 PM: Using PHP version 8.0
12:10:09 PM: Started restoring cached corepack dependencies
12:10:09 PM: mv: cannot move '/opt/build/cache/.node/corepack' to '/opt/buildhome/.node/corepack': No such file or directory
12:10:09 PM: Finished restoring cached corepack dependencies
12:10:09 PM: No npm workspaces detected
12:10:09 PM: Started restoring cached node modules
12:10:09 PM: Finished restoring cached node modules
12:10:09 PM: Bypassing sha validation. Running pre & post install scripts
12:10:09 PM: Installing npm packages using npm version 6.14.4
12:10:10 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
12:10:10 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:10:11 PM: audited 120 packages in 0.973s
12:10:11 PM: 9 packages are looking for funding
12:10:11 PM:   run `npm fund` for details
12:10:11 PM: found 14 vulnerabilities (6 moderate, 8 high)
12:10:11 PM:   run `npm audit fix` to fix them, or `npm audit` for details
12:10:11 PM: npm packages installed
12:10:11 PM: Installing Hugo 0.101.0
12:10:11 PM: hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
12:10:11 PM: Started restoring cached go cache
12:10:11 PM: Finished restoring cached go cache
12:10:11 PM: Installing Go version 1.10 (requested 1.10)
12:10:15 PM: unset GOOS;
12:10:15 PM: unset GOARCH;
12:10:15 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
12:10:15 PM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
12:10:15 PM: go version >&2;
12:10:15 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.10.linux.amd64.env"
12:10:15 PM: go version go1.10 linux/amd64
12:10:15 PM: Detected 2 framework(s)
12:10:15 PM: "hugo" at version "unknown"
12:10:15 PM: "zola" at version "unknown"
12:10:15 PM: Installing missing commands
12:10:15 PM: Verify run directory
12:10:15 PM: Section completed: initializing
12:10:16 PM: ​
12:10:16 PM:   Netlify Build                                                 
12:10:16 PM: ────────────────────────────────────────────────────────────────
12:10:16 PM: ​
12:10:16 PM: ❯ Version
12:10:16 PM:   @netlify/build 29.5.1
12:10:16 PM: ​
12:10:16 PM: ❯ Flags
12:10:16 PM:   baseRelDir: false
12:10:16 PM:   buildId: 63d9050f70017777e562c107
12:10:16 PM:   deployId: 63d9050fe0252c0008bbb311
12:10:16 PM: ​
12:10:16 PM: ❯ Current directory
12:10:16 PM:   /opt/build/repo
12:10:16 PM: ​
12:10:16 PM: ❯ Config file
12:10:16 PM:   /opt/build/repo/netlify.toml
12:10:16 PM: ​
12:10:16 PM: ❯ Context
12:10:16 PM:   production
12:10:16 PM: ​
12:10:16 PM:   1. build.command from netlify.toml                            
12:10:16 PM: ────────────────────────────────────────────────────────────────
12:10:16 PM: ​
12:10:16 PM: $ git submodule update --init --recursive --depth 1 && make production-build
12:10:16 PM: hugo --cleanDestinationDir --minify --environment production
12:10:17 PM: Start building sites …
12:10:17 PM: hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
12:45:51 PM: Build exceeded maximum allowed runtime
</pre>
</details>

**Comment by sftim** [comment]
A typical site build takes  ≅23s, locally. That's in development mode.

**Comment by tengqm** [comment]
This is more likely a Netlify issue than a Hugo issue. The timeout message is reported from Netlify, not Hugo.

**Comment by sftim** [comment]
Netlify pointed us to: https://discourse.gohugo.io/t/possible-explanations-for-stuck-hugo-builds-on-netlify/36166/7

**Comment by sftim** [comment]
We use a version of Hugo that incorporates the specific fix mentioned in that thread.

**Comment by sftim** [comment]
Is it useful to try using the most recent Hugo release and see if that helps at all?

**Comment by Dhairya-Arora01** [comment]
@sftim this again happened with my pr https://github.com/kubernetes/website/pull/39955

**Comment by sftim** [comment]
Good news, sort of. I saw a similar error locally. I attached `strace` to Hugo and saw
```
futex(0x38c4048, FUTEX_WAIT_PRIVATE, 0, NULL
```
&hellip; and then I pressed the wrong key and shut down the container. Oops.

However, this is promising. It means, I think, that we can trigger the error outside Netlify if we try enough times, and that means a new route to debugging it.

**Comment by sftim** [comment]
This was with commit `a3165dfa219976e3018b7322b94d94d9af69b71a`.

**Comment by sftim** [comment]
/retitle Occasional build failures (Build exceeded maximum allowed runtime)

**Comment by sftim** [comment]
If working on this, please first verify that the latest Hugo has the same symptoms; if not, we should upgrade.

**Comment by sftim** [comment]
This might be a symptom of https://github.com/gohugoio/hugo/issues/10565

**Comment by sftim** [comment]
See #40879 for a proposed fix.

**Comment by sftim** [comment]
I can no longer reproduce this locally. I won't close it right yet though.

**Comment by mrgiles** [comment]
This is still happening online ,,,

Deploy failed for kubernetes-io-main-staging
...
8:34:21 PM: Start building sites …
8:34:21 PM: hugo v0.111.3 linux/amd64 [...]
9:32:03 PM: Build exceeded maximum allowed runtime

#40879 

FYI @sftim @tengqm @seokho-son

**Comment by sftim** [comment]
Thanks for the notice. That's a frustration.

**Comment by sftim** [comment]
Slightly good news, I can replicate this locally.

**Comment by sftim** [comment]
To replicate it, I clone the repo and run `make module-init && make container-serve` (I also set `CONTAINER_ENGINE` to Podman).

Example:
```
$ CONTAINER_ENGINE='podman' nice -n 15 make container-serve
"podman" run --rm --interactive --tty --volume "/.../kubernetes/website:/src:ro,Z" --cap-drop=ALL --cap-add=AUDIT_WRITE --read-only --mount type=tmpfs,destination=/tmp,tmpfs-mode=01777 -p 1313:1313 gcr.io/k8s-staging-sig-docs/k8s-website-hugo:v0.111.3-557c27c02583 hugo server --buildFuture --environment development --bind 0.0.0.0 --destination /tmp/hugo --cleanDestinationDir --noBuildLock
Start building sites … 
hugo v0.111.3+extended linux/amd64 BuildDate=unknown
```
(and then nowt happens)

**Comment by sftim** [comment]
/retitle Frequent build failures (Build exceeded maximum allowed runtime) #35780

**Comment by sftim** [comment]
/retitle Frequent build failures (Build exceeded maximum allowed runtime)

**Comment by sftim** [comment]
Most deploys to _main_ are now also failing.
/remove-priority important-longterm
/priority important-soon

**Comment by sftim** [comment]
If people are still seeing this, try rebasing against _main_.

**Comment by sftim** [comment]
/close

The symptoms have pretty much disappeared.
