### ISSUE TITLE
[hi] Update `languageName = "हिन्दी"` in config.toml to implement recent changes in the language name standard.

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35783]
**This is a Bug Report**

**Problem:**

`config.toml` in `dev-1.22-hi.1` contains `languageName = "हिन्दी"`
`config.toml` in `main` contains  `languageName = "हिन्दी (Hindi)"`, which conforms to recent changes in the recent [language name standard](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/localization.md#modify-the-site-configuration). Also see #31657

**Proposed Solution:**

- We should update this line in `dev-1.22-hi.1` so it is the same as `main`.

**Page to Update:**

`config.toml`

**Comment by rolfedh** [comment]
Also see https://github.com/kubernetes/website/pull/29679/files#r939666948

**Comment by Garima-Negi** [comment]
I can work on this issue

**Comment by rolfedh** [comment]
@sftim, I closed https://github.com/kubernetes/website/pull/35784 in favor of https://github.com/kubernetes/website/pull/35898
@xzyangNB, please assign this issue to yourself.

**Comment by rolfedh** [comment]
Fixed by https://github.com/kubernetes/website/pull/35898
