### ISSUE TITLE
名字空间

### ISSUE THREAD

**Issue by linruikai** [kubernetes/website#35798]
名字空间 四个字，markdown语法未正常显示粗体
<img width="681" alt="WX20220809-102115@2x" src="https://user-images.githubusercontent.com/33476727/183549466-f4f52ce9-2d88-44fd-9323-053227f85ee4.png">

**Comment by mengjiao-liu** [comment]
page: https://kubernetes.io/zh-cn/docs/concepts/overview/working-with-objects/namespaces/
/triage accepted
/assign

**Comment by cobb-tx** [comment]
@mengjiao-liu  为什么namespace 不是翻译为命名空间 而是名字空间呢

**Comment by mengjiao-liu** [comment]
这两个都是可接受的。
https://github.com/kubernetes/website/pull/33179#issuecomment-1108159907
https://kubernetes.io/zh-cn/docs/contribute/localization_zh/
