### ISSUE TITLE
Outdated Korean contents in the dev-1.24-ko.3

### ISSUE THREAD

**Issue by mocha-123** [kubernetes/website#35802]
# This is a Bug Report
## Problem
Outdated files in the upstream/dev-1.24-ko.3 branch.

Report generated by the following command.
`./scripts/diff_l10n_branches.py ko upstream/dev-1.24-ko.2 upstream/dev-1.24-ko.3`

### 76 files to be modified 
1. [ ] M1.  `content/en/_index.html`  | 3(+XS) 3(-)
1. [ ] M2.  `content/en/docs/concepts/architecture/control-plane-node-communication.md`  | 1(+XS) 1(-)
1. [ ] M3.  `content/en/docs/concepts/architecture/nodes.md`  | 9(+XS) 14(-)
1. [ ] M4.  `content/en/docs/concepts/cluster-administration/_index.md`  | 48(+M) 28(-)
1. [ ] M5.  `content/en/docs/concepts/configuration/manage-resources-containers.md`  | 5(+XS) 1(-)
1. [ ] M6.  `content/en/docs/concepts/configuration/overview.md`  | 1(+XS) 1(-)
1. [ ] M7.  `content/en/docs/concepts/containers/runtime-class.md`  | 1(+XS) 1(-)
1. [ ] M8.  `content/en/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins.md`  | 2(+XS) 2(-)
1. [ ] M9.  `content/en/docs/concepts/overview/working-with-objects/kubernetes-objects.md`  | 24(+S) 10(-)
1. [ ] M10.  `content/en/docs/concepts/overview/working-with-objects/object-management.md`  | 3(+XS) 3(-)
1. [ ] M11.  `content/en/docs/concepts/scheduling-eviction/_index.md`  | 1(+XS) 0(-)
1. [ ] M12.  `content/en/docs/concepts/scheduling-eviction/assign-pod-node.md`  | 35(+M) 16(-)
1. [ ] M13.  `content/en/docs/concepts/scheduling-eviction/kube-scheduler.md`  | 1(+XS) 1(-)
1. [ ] M14.  `content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md`  | 14(+S) 9(-)
1. [ ] M15.  `content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md`  | 8(+XS) 6(-)
1. [ ] M16.  `content/en/docs/concepts/security/controlling-access.md`  | 3(+XS) 30(-)
1. [ ] M17.  `content/en/docs/concepts/security/pod-security-policy.md`  | 37(+M) 4(-)
1. [ ] M18.  `content/en/docs/concepts/security/windows-security.md`  | 15(+S) 8(-)
1. [ ] M19.  `content/en/docs/concepts/services-networking/dual-stack.md`  | 9(+XS) 9(-)
1. [ ] M20.  `content/en/docs/concepts/services-networking/service-traffic-policy.md`  | 1(+XS) 1(-)
1. [ ] **M21.**  `content/en/docs/concepts/services-networking/service.md`  | **101(+L) 57(-)**
1. [ ] M22.  `content/en/docs/concepts/storage/dynamic-provisioning.md`  | 1(+XS) 1(-)
1. [ ] M23.  `content/en/docs/concepts/storage/ephemeral-volumes.md`  | 18(+S) 12(-)
1. [ ] M24.  `content/en/docs/concepts/storage/persistent-volumes.md`  | 1(+XS) 1(-)
1. [ ] M25.  `content/en/docs/concepts/windows/intro.md`  | 1(+XS) 1(-)
1. [ ] M26.  `content/en/docs/concepts/windows/user-guide.md`  | 2(+XS) 2(-)
1. [ ] M27.  `content/en/docs/concepts/workloads/_index.md`  | 1(+XS) 1(-)
1. [ ] M28.  `content/en/docs/concepts/workloads/controllers/job.md`  | 20(+S) 7(-)
1. [ ] M29.  `content/en/docs/concepts/workloads/controllers/replicaset.md`  | 41(+M) 26(-)
1. [ ] M30.  `content/en/docs/concepts/workloads/controllers/statefulset.md`  | 38(+M) 17(-)
1. [ ] M31.  `content/en/docs/concepts/workloads/pods/_index.md`  | 1(+XS) 1(-)
1. [ ] M32.  `content/en/docs/concepts/workloads/pods/init-containers.md`  | 3(+XS) 3(-)
1. [ ] M33.  `content/en/docs/contribute/new-content/open-a-pr.md`  | 16(+S) 16(-)
1. [ ] M34.  `content/en/docs/contribute/review/reviewing-prs.md`  | 16(+S) 9(-)
1. [ ] M35.  `content/en/docs/reference/_index.md`  | 1(+XS) 1(-)
1. [ ] M36.  `content/en/docs/reference/access-authn-authz/authorization.md`  | 4(+XS) 0(-)
1. [ ] M37.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 3(+XS) 3(-)
1. [ ] M38.  `content/en/docs/reference/glossary/api-eviction.md`  | 1(+XS) 1(-)
1. [ ] M39.  `content/en/docs/reference/glossary/extensions.md`  | 6(+XS) 3(-)
1. [ ] M40.  `content/en/docs/reference/glossary/garbage-collection.md`  | 8(+XS) 5(-)
1. [ ] M41.  `content/en/docs/reference/kubectl/cheatsheet.md`  | 8(+XS) 0(-)
1. [ ] M42.  `content/en/docs/reference/labels-annotations-taints/_index.md`  | 10(+S) 0(-)
1. [ ] M43.  `content/en/docs/reference/scheduling/config.md`  | 1(+XS) 1(-)
1. [ ] M44.  `content/en/docs/reference/using-api/_index.md`  | 1(+XS) 1(-)
1. [ ] M45.  `content/en/docs/setup/best-practices/multiple-zones.md`  | 1(+XS) 1(-)
1. [ ] M46.  `content/en/docs/setup/production-environment/container-runtimes.md`  | 3(+XS) 3(-)
1. [ ] M47.  `content/en/docs/setup/production-environment/tools/kubespray.md`  | 29(+S) 25(-)
1. [ ] M48.  `content/en/docs/tasks/administer-cluster/access-cluster-api.md`  | 1(+XS) 1(-)
1. [ ] M49.  `content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md`  | 1(+XS) 0(-)
1. [ ] M50.  `content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md`  | 57(+M) 69(-)
1. [ ] M51.  `content/en/docs/tasks/configmap-secret/managing-secret-using-kubectl.md`  | 2(+XS) 0(-)
1. [ ] M52.  `content/en/docs/tasks/configure-pod-container/static-pod.md`  | 2(+XS) 2(-)
1. [ ] M53.  `content/en/docs/tasks/debug/debug-application/debug-statefulset.md`  | 2(+XS) 2(-)
1. [ ] M54.  `content/en/docs/tasks/debug/debug-application/determine-reason-pod-failure.md`  | 6(+XS) 2(-)
1. [ ] M55.  `content/en/docs/tasks/debug/debug-cluster/windows.md`  | 1(+XS) 1(-)
1. [ ] M56.  `content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md`  | 1(+XS) 1(-)
1. [ ] M57.  `content/en/docs/tasks/manage-kubernetes-objects/imperative-command.md`  | 2(+XS) 2(-)
1. [ ] M58.  `content/en/docs/tasks/manage-kubernetes-objects/imperative-config.md`  | 1(+XS) 1(-)
1. [ ] M59.  `content/en/docs/tasks/network/validate-dual-stack.md`  | 9(+XS) 9(-)
1. [ ] M60.  `content/en/docs/tasks/run-application/delete-stateful-set.md`  | 5(+XS) 5(-)
1. [ ] M61.  `content/en/docs/tasks/tls/managing-tls-in-a-cluster.md`  | 2(+XS) 2(-)
1. [ ] M62.  `content/en/docs/tasks/tools/install-kubectl-linux.md`  | 10(+S) 3(-)
1. [ ] M63.  `content/en/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice.md`  | 38(+M) 9(-)
1. [ ] M64.  `content/en/docs/tutorials/security/cluster-level-pss.md`  | 2(+XS) 1(-)
1. [ ] M65.  `content/en/docs/tutorials/security/ns-level-pss.md`  | 1(+XS) 1(-)
1. [ ] M66.  `content/en/examples/admin/konnectivity/egress-selector-configuration.yaml`  | 1(+XS) 1(-)
1. [ ] M67.  `content/en/examples/controllers/job.yaml`  | 1(+XS) 1(-)
1. [ ] M68.  `content/en/examples/pods/pod-with-affinity-anti-affinity.yaml`  | 2(+XS) 3(-)
1. [ ] M69.  `content/en/examples/pods/pod-with-node-affinity.yaml`  | 3(+XS) 2(-)
1. [ ] M70.  `content/en/examples/service/networking/dual-stack-default-svc.yaml`  | 2(+XS) 2(-)
1. [ ] M71.  `content/en/examples/service/networking/dual-stack-ipfamilies-ipv6.yaml`  | 2(+XS) 2(-)
1. [ ] M72.  `content/en/examples/service/networking/dual-stack-ipv6-svc.yaml`  | 2(+XS) 2(-)
1. [ ] M73.  `content/en/examples/service/networking/dual-stack-prefer-ipv6-lb-svc.yaml`  | 2(+XS) 2(-)
1. [ ] M74.  `content/en/examples/service/networking/dual-stack-preferred-ipfamilies-svc.yaml`  | 2(+XS) 2(-)
1. [ ] M75.  `content/en/examples/service/networking/dual-stack-preferred-svc.yaml`  | 2(+XS) 2(-)
1. [ ] M76.  `content/en/releases/version-skew-policy.md`  | 19(+S) 2(-)

### 1 files to be deleted 
1. [ ] D1.  `content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md`

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually 
to the `content/ko` of `upstream/dev-1.24-ko.3` branch.

For example:
```
# checkout `upstream/dev-1.24-ko.3`
...
# check what is updated in the upstream 
git diff upstream/dev-1.24-ko.2 upstream/dev-1.24-ko.3 -- content/en/_index.html
# apply changes to content/ko
vi content/ko/_index.html
...
# commit and push
...
# make PR to `upstream/dev-1.24-ko.3`
```

## Pages to Update

Pages in content/ko

/language ko

**Comment by seokho-son** [comment]
Thanks @mocha-123 :)

/triage accepted

**Comment by seokho-son** [comment]
D1. `content/en/docs/concepts/workloads/pods/pod-topology-spread-constraints.md` was not deleted.

It is relocated to `content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md` (bfff661) and its content has been updated as well. by following PR.
 - #33792 (https://github.com/kubernetes/website/pull/33792/files#r921636621)


Our tool (script) cannot report this kind of changes. Needs to be enhanced.

**Comment by seokho-son** [comment]
ref: https://github.com/kubernetes/website/issues?q=label%3Arefactor+is%3Amerged (label:refactor is:merged )

**Comment by having-dlrow** [comment]
M1~M5 작업 희망합니다.

**Comment by jinnypark9393** [comment]
M8, M19~M21 작업 해보겠습니다 :)

**Comment by seokho-son** [comment]
/assign @having-dlrow @jinnypark9393 

감사합니다!!

- M1~M5 : @having-dlrow 
- M8 : @jinnypark9393 
- M19~M21 : @jinnypark9393

**Comment by mocha-123** [comment]
M27~M32 작업 희망합니다.

**Comment by KimDoubleB** [comment]
M66-M76 작업해보겠습니다~!

**Comment by NayeonKeum** [comment]
M22~M26 작업 희망합니다!

**Comment by Veryfirstmoment** [comment]
M33~34, M63~65 작업 진행해 보겠습니다.

**Comment by seokho-son** [comment]
감사합니다! :)
/assign @mocha-123 @KimDoubleB @NayeonKeum @Veryfirstmoment

**Comment by yoonian** [comment]
M35-M49 까지 해보지요

**Comment by NayeonKeum** [comment]
M9~M13 작업 추가 희망합니다!

**Comment by NayeonKeum** [comment]
M53~62 작업 추가 희망합니다!

**Comment by onestone9900** [comment]
M50-M52 작업 진행 해보겠습니다~!

**Comment by seokho-son** [comment]
/assign @onestone9900 
😍

**Comment by bconfiden2** [comment]
M14 ~ M18 작업하겠습니다!

**Comment by jihoon-seo** [comment]
D1 제가 하겠습니다~
D1 처리하는 PR이 머지되면 #35841 도 업데이트 하겠습니다~

**Comment by seokho-son** [comment]
Complete !! Thanks to all contributors.

/close
