### ISSUE TITLE
broken link - section 'the downward api' no longer exists

### ISSUE THREAD

**Issue by mocha-123** [kubernetes/website#35814]
**This is a Bug Report**

**Problem:**
The link `/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api` is dead.
The content from the section seems moved into top of the document and glossary in [7f3604a](https://github.com/kubernetes/website/commit/7f3604a949c1d85b2074cea3e3068e1b522850d8#diff-a6d22beccc39e70b247db48068c8d2afd03e6c707122b8b6246d66226a5c79b2).

**Proposed Solution:**
- remove fragment `#the-downward-api` from the link
- change link to `/docs/concepts/workloads/pods/downward-api.md` or `/docs/reference/glossary/downward-api.md`

**Page to Update:**
- /docs/concepts/workloads/pods/downward-api
- /docs/tasks/inject-data-application/downward-api-volume-expose-pod-information
- /docs/tasks/job/indexed-parallel-processing-static

**Comment by sftim** [comment]
/language en
/triage accepted
/help

We should find existing hyperlinks to https://k8s.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/#the-downward-api and replace those with links to https://k8s.io/docs/concepts/workloads/pods/downward-api/
