### ISSUE TITLE
[ko] Translate /docs/concepts/security/pod-security-standards into Korean

### ISSUE THREAD

**Issue by rollony** [kubernetes/website#35812]
**This is a Feature Request**

**What would you like to be added**

Translate "/docs/concepts/security/pod-security-standards" into Korean.

**Why is this needed**

Not translated into Korean yet.

**Comments**

original entry: https://kubernetes.io/docs/concepts/security/pod-security-standards/

/language ko
/assign

**Comment by jihoon-seo** [comment]
@rollony 감사합니다!
/triage accepted
