### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by jhughes2112** [kubernetes/website#35838]
```
envFrom:
      - configMapRef:
```

The internet is full of people complaining that this feature does not work.  I tried it myself, did not work, but the parser did accept the keywords in my manifest.  Please either explain how this _actually works_ or remove it from the parser and documentation.  It's misleading (although it would be a great feature if it only worked as specified).

**Comment by sftim** [comment]
Each heading in that page (https://k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/) has a hyperlink icon that shows if you hover a pointer over that heading.

What's the URL of the section of the page that you don't think is right @jhughes2112 ?

If you ran a command and got an error message, please also mention:
- the command that you ran
- the error message

If commands worked but you didn't get the outcome you expected, please instead mention:
- the commands you ran
- what you expected to happen
- what actually happened instead

That information will help contributors to understand the issue as you've experienced it.


/language en

**Comment by jhughes2112** [comment]
Specifically the section I reference is this https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables

I basically did what the example says to do, referred to a ConfigMap that has `data:` section full of key: value pairs that I wanted to be environment variables.  None of them showed up with data in the execution of the container.  The same ConfigMap was used previously while using `configMapKeyRef:` and explicitly naming each variable, which is a drag, but worked.  Manifest submission parsed properly in both cases, but `envFrom:` does not actually work.  Either the feature should be fixed or the documentation should change to reflect that it _does not work._

**Comment by annajung** [comment]
Hi, could you please provide more details about the commands you're running?

I ran the following commands (from the page you shared), and was able to successfully test that env is set using the `configMapRef` field. 

```
kubectl create -f https://kubernetes.io/examples/configmap/configmap-multikeys.yaml
kubectl create -f https://kubernetes.io/examples/pods/pod-configmap-envFrom.yaml
```

```
kubectl logs pod/dapi-test-pod | grep SPECIAL
SPECIAL_LEVEL=very
SPECIAL_TYPE=charm
```

/triage needs-information

**Comment by RA489** [comment]
@jhughes2112 could you please provide above details suggested by @annajung  to proceed further?

**Comment by jhughes2112** [comment]
I have to build a repro case.  The place where I am finding this feature not working is too complex.  I will update here when I have done so.

**Comment by jhughes2112** [comment]
No bug here, sorry.  I stared at the env variable name for an hour without realizing it was being remapped to another (slightly different) name.
