### ISSUE TITLE
实现细节

### ISSUE THREAD

**Issue by bandiawy** [kubernetes/website#35843]
# words spelling error:
site position:  [为控制平面组件生成静态 Pod 清单](https://kubernetes.io/zh-cn/docs/reference/setup-tools/kubeadm/implementation-details/#generate-static-pod-manifests-for-control-plane-components)
`tier:ontrol-plane`  => `tier=control-plane`

**Comment by hs0210** [comment]
@bandiawy Hi, this issue has been fixed by [822b328](https://github.com/kubernetes/website/pull/35864/commits/822b3285a505454f69da02b503e84d1ea1be77f9#diff-7db071a90b4a927070f5a9dad6fadcd4711f5739a3bf325b028049c8835710d3R490), it can be closed.
