### ISSUE TITLE
Reusing SVG blocks

### ISSUE THREAD

**Issue by techtonik** [kubernetes/website#3584]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
Reusing SVG building blocks for my own diagrams.

I like k8s style for cluster diagrams (https://github.com/kubernetes/kubernetes.github.io/issues/3566#issuecomment-298152478), so how can I use them in my own works? Should I put CC-BY 4.0 on every my drawing with attribution info or there is another way?

Also, how about making a dedicated place for reusable blocks, so it could be loaded as a library to Inkscape and other tools?

**Page to Update:**
https://github.com/kubernetes/kubernetes.github.io

**Comment by ahmetb** [comment]
@jaredbhatti do you happen to have an answer for this?

**Comment by jaredbhatti** [comment]
The diagrams were created by a third party, so I don't have their image libraries.  Brian Grant might know more, or who to reach out to.

**Comment by techtonik** [comment]
/remove-lifecycle stale

Art library with clear licensing terms on derivative works is still needed.
