### ISSUE TITLE
container-level vs. pod-level isolation in "Resource Management for Pods and Containers"

### ISSUE THREAD

**Issue by rhuss** [kubernetes/website#35840]
When describing resource management for ephemeral storage, the following paragraph is not fully clear to me:

> For *container-level isolation*, if a container's writable layer and log usage exceeds its storage limit, the kubelet marks the Pod for eviction.
>
> For *pod-level isolation* the kubelet works out an overall Pod storage limit by summing the limits for the containers in that Pod. In this case, if the sum of the local ephemeral storage usage from all containers and the Pod's emptyDir volumes exceeds the overall Pod storage limit, then the kubelet also marks the Pod for eviction.

What is the concept of "container-level" and "pod-level" isolation? Are these two different modes that can be chosen in the configuration, or are two algorithms applied to decide whether a Pod needs to be evicted ? These modes are neither explained further in this document nor could I find them anywhere else.

**Comment by sftim** [comment]
/language en
It's OK to pick new language to replace the terms “container-level isolation“ and “ pod-level isolation”.
