### ISSUE TITLE
Register and document annotation `cluster-autoscaler.kubernetes.io/enable-ds-eviction`

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#35851]
**This is a Bug Report**

**Problem:**
The cluster autoscaler uses an annotation, `cluster-autoscaler.kubernetes.io/enable-ds-eviction`. However, we don't list that annotation in 
[Well-Known Labels, Annotations and Taints](
https://kubernetes.io/docs/reference/labels-annotations-taints/).

**Proposed Solution:**
Update [Well-Known Labels, Annotations and Taints](
https://kubernetes.io/docs/reference/labels-annotations-taints/) to mention the Pod annotation `cluster-autoscaler.kubernetes.io/enable-ds-eviction` and why you might use it. We could mention that you typically set this annotation in the _Pod template_ within a DaemonSet  and that you _don't_ set that annotation on the DaemonSet itself.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/language en

**Comment by Shubham82** [comment]
I would like to work on this.
/assign
/sig autoscaling

**Comment by Shubham82** [comment]
Fixed it here: #35897
