### ISSUE TITLE
[ko] Translate /docs/tasks/administer-cluster/limit-storage-consumption into Korean

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/website#35863]
**This is a Feature Request**

**What would you like to be added**

Translate `/docs/tasks/administer-cluster/limit-storage-consumption` into Korean
- page : https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/

**Why is this needed**
Not translated yet

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
@Kid-Chang 님~~
찾아 보니, 이미 #35200 이슈가 있습니다.
참고 부탁드립니다 😅
/triage duplicate

**Comment by jihoon-seo** [comment]
@Kid-Chang 님~~
이 이슈는 close 하겠습니다. 😊
지속적인 관심과 기여에 감사드립니다. 😊
/close
