### ISSUE TITLE
Service example does not follow Configuration Best Practices

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#35862]
The “Configuration Best Practices” at https://kubernetes.io/docs/concepts/configuration/overview/#services suggest creating a Service object before creating a Deployment/ReplicaSet/Pod.

One example at https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service utilizes ports in Services by name, where the name is defined in the pod’s definition.  In that example the definition of the Pod precedes the definition of the Service.  It is unclear, whether the port-by-name concept will work if the Service is defined before the Pod.

* Adjust the example at https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service to follow “Configuration Best Practices” by defining the Service after the Pod.

**Comment by sftim** [comment]
It's OK to create these in either order. On the page https://kubernetes.io/docs/concepts/services-networking/service/ let's make it clear that Kubernetes does the right thing, regardless of whichever order you create the Service and its backing Pods.

/language en
/priority backlog
/triage accepted

**Comment by dilyanpalauzov** [comment]
For me it is not clear how the description shall be updated.  There is a discrepancy between the example and the “Best Configuration Practices” at https://kubernetes.io/docs/concepts/configuration/overview/#services.

**Comment by sftim** [comment]
When I triaged this as accepted, that was based on an assumption that my proposed fix would be the approach we take.
/remove-triage accepted

I want to make it a bit more obvious that there's possibly a difference of opinion here. I don't agree with the change that you propose @dilyanpalauzov: I worry that it might make people believe that the order matters more than it actually does.

Folks are welcome to open PRs with proposed fixes. In the PR description, please highlight this issue and the open question about the best fix.
