### ISSUE TITLE
Configure Pods and Containers

### ISSUE THREAD

**Issue by yugesh-github** [kubernetes/website#35877]
ubuntu@ip-172-31-29-230:~$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
mynignxpod   1/1     Running   0          4h41m

ubuntu@ip-172-31-29-230:~$ kubectl delete pods mynginxpod
Error from server (NotFound): pods "mynginxpod" not found
ubuntu@ip-172-31-29-230:~$

How to delete my pod? What is the issue here? somebody please provide solution.

**Comment by sftim** [comment]
/kind support

This looks more like a request for help than a bug report about a page on the Kubernetes website.

**Comment by RA489** [comment]
>> How to delete my pod? What is the issue here? somebody please provide solution.

@yugesh-github If it is just a pod you can use` kubectl delete pod podname` . If this pod create from deployment you need to delete the deployment to remove all its related pods `kubectl delete deployment deploymentname`

**Comment by RA489** [comment]
/close
feel free to reopen if still your issue is not solved.
