### ISSUE TITLE
Issue with k8s.io/es/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by Cris123m** [kubernetes/website#35892]
katacoda.com is now closed to the public and content is no longer available. The full details are available on O'Reilly [here](https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html).

**Comment by rghdrizzle** [comment]
There is an alternative , https://killercoda.com/ which has a k8s playground . I believe that playground can be used instead of Katakoda since its services has been terminated .

**Comment by sftim** [comment]
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ works OK. The bug with https://kubernetes.io/es/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ is not related to the closure of the public Katacoda service.

/kind bug
