### ISSUE TITLE
Document setting up cloud provider kubectl auth via plugin (AKS, GKE)

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#35896]
**This is a Feature Request**

**What would you like to be added**
(As I understand it), Kubernetes ~v1.25~ v1.26 ships an updated `kubectl`. The updated `kubectl` won't include built-in plugins for authenticating to AKS or GKE.
This is likely to surprise folks.

Update 3 pages:
- https://kubernetes.io/docs/tasks/tools/install-kubectl-linux
- https://kubernetes.io/docs/tasks/tools/install-kubectl-macos
- https://kubernetes.io/docs/tasks/tools/install-kubectl-windows

to **signpost** users to the right internal ~and external~ docs. We can remove this signposting once Kubernetes v1.27 (sic) is the oldest supported version of Kubernetes (consider adding an HTML comment with that detail).

Optionally, also update https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins to mention that earlier versions of `kubectl` included built-in support for authenticating to AKS and GKE, but this is no longer present.

**Why is this needed**
Readers may follow the “install kubectl” docs and get a tool that's missing functionality they thought was built in.

**Comments**
> The gcp and azure auth plugins have been removed from client-go and kubectl. See [AKS](https://github.com/Azure/kubelogin) and [GKE](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke) documentation for details about the cloud-specific replacements.

/sig cli
/language en

**Comment by shannonxtreme** [comment]
For each of the three pages, add the following under the **Verify kubectl configuration** heading, at the end of the section:

```
### Panic: no auth provider found error message

{{% thirdparty-content %}}

In Kubernetes v1.25, kubectl removed the built-in authentication for the following cloud
providers' managed Kubernetes offerings. These providers have released kubectl plugins
to fix the authentication. For instructions, refer to the following provider documentation:

*  AKS (Azure): [kubelogin plugin](https://github.com/Azure/kubelogin)
*  GKE (Google Cloud): [gke-gcloud-auth-plugin](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin)
```

/help-wanted

**Comment by reylejano** [comment]
Kubernetes 1.25.0 did not remove Google and Azure auth plugins due to a regression issue, see https://github.com/kubernetes/kubernetes/issues/111911#issuecomment-1219783870. The revert is in PR https://github.com/kubernetes/kubernetes/pull/111918

**Comment by sftim** [comment]
This change is likely to arrive in v1.26, so we should get it staffed.

**Comment by sftim** [comment]
@shannonxtreme would you be willing to change the minor version in https://github.com/kubernetes/website/issues/35896#issuecomment-1218520038 ?

**Comment by palnabarun** [comment]
@enj @liggitt -- as author/reviewer of the [External Credential Provider KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/541-external-credential-providers), can you please review the doc change suggested by @shannonxtreme in https://github.com/kubernetes/website/issues/35896#issuecomment-1218520038?

**Comment by liggitt** [comment]
A few suggestions:
* I probably would not put "panic" in the heading title
* Can we link to https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins as well
* I'm on the fence about whether we need the cloud-specific links in this doc... if you try to use them in a kubectl version that has removed them, you already get a message output at time of use with the appropriate link/reference

**Comment by enj** [comment]
>     * I'm on the fence about whether we need the cloud-specific links in this doc... if you try to use them in a kubectl version that has removed them, you already get a message output at time of use with the appropriate link/reference.

I personally do not think the kube authn docs should contain cloud-specific links.  It is on the cloud providers to migrate their users anyway, and the cloud CLI tools are fully capable of hiding the bulk of this migration by performing runtime checks and/or preferring credential plugins over the legacy approach.

**Comment by sftim** [comment]
I agree about not including cloud-provider-specific links. Integrations with cloud providers are not required for a (vanilla) Kubernetes cluster to function.

See https://github.com/kubernetes/enhancements/tree/master/keps/sig-docs/1326-third-party-content-in-docs#readme for some more context.

**Comment by sftim** [comment]
We can instead advise readers to search in their cloud provider's documentation for further advice.

**Comment by krol3** [comment]
Hello @kadtendulkar  👋, 1.26 Release Docs Lead here. This feature request needs Docs for 1.26 release.

Please [follow the steps detailed in the documentation](https://kubernetes.io/docs/contribute/new-content/new-features/#open-a-placeholder-pr) to open a PR against dev-1.26 branch in the k/website repo. This PR can be just a placeholder at this time, and must be created by November 10. Also, take a look at [Documenting for a release](https://kubernetes.io/docs/contribute/new-content/new-features/#for-developers-or-other-sig-members) to familiarize yourself with the docs requirement for the release.

Any doubt, reach us! Thank you!

**Comment by sftim** [comment]
//remove-priority important-soon
/priority important-longterm
/triage accepted

**Comment by coder12git** [comment]
> > @sftim, could you kindly provide a detailed description of the issue once more? Upon reviewing the above comments, it appears that numerous changes have been implemented.
> 
> [#35896 (comment)](https://github.com/kubernetes/website/issues/35896#issue-1336892127) looks right to me.
> 
> > The task is to update 3 pages:
> > 
> > * https://kubernetes.io/docs/tasks/tools/install-kubectl-linux
> > * https://kubernetes.io/docs/tasks/tools/install-kubectl-macos
> > * https://kubernetes.io/docs/tasks/tools/install-kubectl-windows
> > 
> > to signpost users to the right internal and external docs. We can remove this signposting once Kubernetes v1.27 (sic) is the oldest supported version of Kubernetes (consider adding an HTML comment with that detail).
> > Optionally, also update https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins to mention that earlier versions of kubectl included built-in support for authenticating to AKS and GKE, but this is no longer present.
> 
> In terms of the “right internal and internal docs” to link to, you should use your judgement. You could link to https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins or to a task page; you might need to write the task page first.
> 
> Any more questions? It's clear to me, but I might have missed something.

Thanks @sftim , I am working on this, will create a PR soon ;)
