### ISSUE TITLE
[ko] Translate /docs/setup/best-practices/enforcing-pod-security-standards/ into Korean

### ISSUE THREAD

**Issue by NayeonKeum** [kubernetes/website#35919]
**This is a Feature Request**

**What would you like to be added**

Translate /docs/setup/best-practices/enforcing-pod-security-standards/ into Korean

[Link](https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/)

**Why is this needed**

Not translated yet

**Comments**

Double checked there's no same issue.

/language ko

**Comment by jihoon-seo** [comment]
Resolved by
- #36726
- #36804
- #36810

/close
