### ISSUE TITLE
The versions for cni-plugins and cri-tools vary between the kubeadm installations

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/website#35921]
**This is a Feature Request**

**What would you like to be added**

The package list for "Without a package manager", is lagging the behind the other two package managers.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

**Why is this needed**

They should be kept in sync, so that users are not installing a different version (possibly leading to issues)

A quick fix, would be to just copy the version lines from the release repository to the documention repository.

**Comments**

Currently the versions used for `apt` and `yum` are kept inside this repository:

https://github.com/kubernetes/release/blob/master/packages/rpm/kubelet.spec

```
%global CNI_VERSION 0.8.7
```
```
%global CRI_TOOLS_VERSION 1.24.2
```

But the versions used for third tab, are instead stored directly in the documentation:

https://github.com/kubernetes/website/blob/main/content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

```
CNI_VERSION="v0.8.2"
```
```
CRICTL_VERSION="v1.22.0"
```

----

The variables used are also different, and possibly misleading (is it the CNI version ?)

CNI_PLUGINS_VERSION

CRI_TOOLS_VERSION

A user accessible link to the project, instead of just a shell script, might also help here ?

* https://github.com/containernetworking/plugins

* https://github.com/kubernetes-sigs/cri-tools

I didn't label the issue as "bug", since it might still work OK with the old versions ?

The version skew for cni and cri is not well defined, and it is within reasonable limits.

**Comment by bishal7679** [comment]
triage/accepted

**Comment by neolit123** [comment]
not sure if hugo / website shortcodes can be used for that. alternatively we could generate the versions on site 'compile' time.

needs sig docs feedback.

/sig docs cluster-lifecycle

**Comment by afbjorklund** [comment]
The versions are now in sync, since b63c85ff84321fe17097a2d54026a848c6b1f3dc

release
packages/rpm/kubelet.spec:%global CRI_TOOLS_VERSION 1.25.0
packages/rpm/kubelet.spec:%global CNI_VERSION 1.1.1

website
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md:CRICTL_VERSION="v1.25.0"
content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md:CNI_PLUGINS_VERSION="v1.1.1"
