### ISSUE TITLE
Misleading documentation for upgrading existing kubeadm

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/website#35920]
**This is a Bug Report**

**Problem:**

There are [detailed instructions](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#instructions), on how to upgrade the `kubeadm` package for a particular package manager:

> If you have already installed kubeadm, run apt-get update && apt-get upgrade or yum update to get the latest version of kubeadm.

But this package is marked as "hold", so it won't upgrade... User might also a different package manager (or none)

**Proposed Solution:**

Removing these details from the main page and deferring them to the sub page, might help ?

> Install a [container runtime](https://kubernetes.io/docs/setup/production-environment/container-runtimes) and kubeadm on all the hosts. For detailed instructions and other prerequisites, see [Installing kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/).

It already has the details on how to install, so it could also included instructions on how to upgrade.

**Page to Update:**

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by neolit123** [comment]
> 
 Removing these details from the main page and deferring them to the sub page, might help ?

i think this makes sense.
PRs welcome / can comment more during review.

/sig cluster-lifecycle
