### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/addons.md

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35934]
Prerequisites: 
- If this is your first contribution, visit [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) for information on how to get started.
- Review a few [examples of localized glossary entries](https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859) to see which content you change and which you live unchanged.

Procedure:
1. Check out `dev-1.22-hi.1` and create a working branch called `localize-addons.md`.
1. Create a file called `content/hi/docs/reference/glossary/addons.md`.
1. Copy the content of https://raw.githubusercontent.com/kubernetes/website/main/content/en/docs/reference/glossary/addons.md to the file you created.
1. Localize the content.
1. Push your change and create a pull request.

Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/35600

**Comment by khannakshat7** [comment]
Hey @rolfedh, I would like to work on this issue

**Comment by anubha-v-ardhan** [comment]
/remove-good-first-issue
We usually don't prefer putting this label on localization work as they are not "zero barrier" and "easy" most of the times

**Comment by Babapool** [comment]
This issue has been resolved by PR #35961 (which has been merged). This issue can now be closed. Thanks.
/close
