### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/aggregation-layer.md

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35937]
# Prerequisites: 
- If this is your first contribution, visit [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) for information on how to get started.
- Review a few [examples of localized glossary entries](https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859) to see which content you change and which you live unchanged.

# Procedure:
1. Check out `dev-1.22-hi.1` and create a working branch called `localize-aggregation-layer.md`.
1. Create a file called `content/hi/docs/reference/glossary/aggregation-layer.md`.
1. Copy the content of https://raw.githubusercontent.com/kubernetes/website/main/content/en/docs/reference/glossary/aggregation-layer.md to the file you created.
1. Localize the content.
1. Push your change and create a pull request.

Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/35600

**Comment by khannakshat7** [comment]
Hey @rolfedh, I would like to work on this issue

**Comment by mukul-kr** [comment]
I guess this issue is fixed. Kindly close it.
