### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/affinity.md

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35936]
# Prerequisites: 
- If this is your first contribution, visit [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) for information on how to get started.
- Review a few [examples of localized glossary entries](https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859) to see which content you change and which you live unchanged.

# Procedure:
1. Check out `dev-1.22-hi.1` and create a working branch called `localize-affinity.md`.
1. Create a file called `content/hi/docs/reference/glossary/affinity.md`.
1. Copy the content of https://raw.githubusercontent.com/kubernetes/website/main/content/en/docs/reference/glossary/affinity.md to the file you created.
1. Localize the content.
1. Push your change and create a pull request.

Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/35600

**Comment by khannakshat7** [comment]
Hey @rolfedh, I would like to work on this issue

**Comment by GitBatra** [comment]
Hey @rolfedh, I would like to work on this issue

**Comment by amolmote** [comment]
@GitBatra  refer this issue #35600 and first search with file whether someone already opened it or not

**Comment by GitBatra** [comment]
Hey @rolfedh can you help me with how to localize the content. Which tool i have to use it? Any reference you can give would be very helpful

**Comment by amolmote** [comment]
Join the kubernetes slack then join #kubernetes-docs-hi channel we will help you for your first contribution

**Comment by GitBatra** [comment]
Thank you @amolmote for your reply. Joining soon

**Comment by SRV332003** [comment]
Is this issue yet to be resolved?
If Yes, assign to me...

**Comment by Babapool** [comment]
This issue has been resolved by PR #35997, which has been merged. This issue can now be closed.
/close
