### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/api-group.md

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35939]
# Prerequisites: 
- If this is your first contribution, visit [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) for information on how to get started.
- Review a few [examples of localized glossary entries](https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859) to see which content you change and which you live unchanged.

# Procedure:
1. Check out `dev-1.22-hi.1` and create a working branch called `localize-api-group`.
1. Create a file called `content/hi/docs/reference/glossary/api-group.md`.
1. Copy the content of https://raw.githubusercontent.com/kubernetes/website/main/content/en/docs/reference/glossary/api-group.md to the file you created.
1. Localize the content.
1. Push your change and create a pull request.

Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/35600

**Comment by khannakshat7** [comment]
Hey @rolfedh, I would like to work on this issue

**Comment by ayushontop** [comment]
I this issue still open?

**Comment by rolfedh** [comment]
Hi @ayushontop, thanks for your interest. Yes, this issue is open, pending merge of @khannakshat7 pull request #35962, shown above. If you're looking to volunteer, please introduce yourself on the Kubernetes #kubernetes-docs-hi channel at https://kubernetes.slack.com/archives/CJ14B9BDJ

**Comment by Aut0R3V** [comment]
I would like to take this up.

**Comment by khannakshat7** [comment]
Hey @Aut0R3V, Thanks for showing your interest. But I have already created the PR which is ready for merge. You can create a new issue and work on it.

**Comment by Aut0R3V** [comment]
Sure thanks!

**Comment by ibilalkayy** [comment]
Hey @rolfedh, can I make changes to it as you suggested? I didn't understand where to checkout `dev-1.22-hi.1` and how to create a working branch called `localize-api-group.`

**Comment by ibilalkayy** [comment]
Hey @rolfedh I am also going to add my local languages.

**Comment by rolfedh** [comment]
Hi @ibilalkayy, this issue and its associated PR are for the Hindi language docs. 
For other languages, please see https://kubernetes.io/docs/contribute/localization/ and find the two letter code for the language you want to contribute to. It's possible that there's already a community of like-minded contributors you can work with. Also check the slack channels for that two-letter code.

**Comment by dollar22** [comment]
@khannakshat7 do you want to contribute. if you don't want to do it please tell me i'll like to work on it

**Comment by ibilalkayy** [comment]
@dollar22 No I don't think you can work on it because the PR of this issue is already sent and the text is already converted into Hindi.

**Comment by vaibhav2107** [comment]
I think we can close this issue as it has been fixed by #35962
/close
