### ISSUE TITLE
Localize English artifacts from `{{< release-data >}}` shortcode in localized docs

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35932]
When the following shortcode appears in a localized document...

https://github.com/kubernetes/website/blob/6637a171c87cf28f6911b67f4d99551a605d0df4/content/ko/releases/_index.md?plain=1#L21

...the localized document displays English words such as: 

"Complete 1.24 [Schedule](https://deploy-preview-29679--kubernetes-io-main-staging.netlify.app/releases/patch-releases/#1-24) and [Changelog](https://git.k8s.io/kubernetes/CHANGELOG/CHANGELOG-1.24.md)" 

Instances of the `{{< release-data >}}` shortcode display English words in various localizations, such as:
- https://kubernetes.io/zh-cn/releases/
- https://kubernetes.io/ko/releases/
- https://kubernetes.io/pl/releases/

Is there a way to localize the languages these shortcodes display?

**Comment by rolfedh** [comment]
For instance, see https://github.com/kubernetes/website/pull/29679#issuecomment-1210551182.

**Comment by rolfedh** [comment]
I have asked this question in the Hugo forum, here: https://discourse.gohugo.io/t/can-i-translate-english-words-from-a-shortcode-so-they-match-the-localized-kubernetes-website-docs/39984

**Comment by sftim** [comment]
This is not a Hugo bug. https://github.com/kubernetes/website/blob/fac477b9e4d3e1569c53bc13f13b09b1e6602740/layouts/shortcodes/release-data.html#L36-L40 is the file to localize.

**Comment by rolfedh** [comment]
#35950 partially fixes this issue. Each localization branch would need to merge PR #35950 and add corresponding entries to their `data/i18n/<lang>/<lang>.toml` files, such as:
- `data/i18n/ko/en.toml`
- `data/i18n/pl/pl.toml`
- `data/i18n/zh-cn/zh-cn.toml`

**Comment by rolfedh** [comment]
> This is not a Hugo bug.
Thanks, yes. I wasn't sure whom to ask, and generally try not to bother you with every question I have.  The Hugo forum pointed us in the right direction, and @Sea-n quickly put together a PR solution.

**Comment by a-mccarthy** [comment]
>Each localization branch would need to merge PR https://github.com/kubernetes/website/pull/35950 and add corresponding entries to their data/i18n/<lang>/<lang>.toml files

@rolfedh Once you PR merges, we should plan to add this topic to a localization meeting and post a message in the localization slack channel. We can also send an email, re post messages in slack for additional visibility. We should make sure the message includes all the steps needed o implement this and any urgency/priority around this change for the localization teams 

By a partial fix in your PR, do you mean that Localization teams will need to take additional steps to apply the changes to their localization, or are there additional file changes that need to be made?

**Comment by rolfedh** [comment]
@a-mccarthy Yes, exactly. Once this PR merges, I would do all the things you've suggested above or arrange with someone to do them. I'll create separate issues for each of the localization teams to update their branches as needed. This is not a breaking change, so there is no urgency.

**Comment by rolfedh** [comment]
I've tested to make sure this isn't a breaking change. If the `data/i18n/<lang>/<lang>.toml` file is missing the required entries, the `http://localhost:1313/<lang>/releases/` page falls back and uses the entries from `data/i18n/en/en.toml`
