### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### ISSUE THREAD

**Issue by bmanojpatel** [kubernetes/website#35948]
The entire upgrade plan has a basic flaw.
This document has mixed the steps for Control plan and Node upgrade steps.

1-Before cordon of worker node, idle step should be to upgrade kubelet & Kubectl on Control plane.
2-Post this step we can check version of both the tools to ensure correct version is upgraded on control plane before starting Worker node cordon and upgrade steps.
3-Mention clearly that user has to ssh in to worker node after running cordon step and confirming running state of pods on other available node to ensure minimum downtime.
4-Then you can mention kubelet and kubectl upgrade on worker node.

Without above segrigation this document around upgrade is mixing control and worker node upgrade.

**Comment by neolit123** [comment]
> Without above segrigation this document around upgrade is mixing control and worker node upgrade.

i have seen a couple of complains that the document can be confusing, but that's a minority of users.

things like ssh, workload safety and checking versions are optional and/or implied.

 in any case happy to review contributor PRs.

/sig cluster-lifecycle
