### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/app-container.md

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35941]
[hi] Localize /en/docs/reference/glossary/app-container.md
# Instructions

- Review a few [examples of localized glossary entries](https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859).
- In the examples, notice which elements are translated and which ones are not.

## Translating the frontmatter

In the frontmatter, that is, between the `---` markers that enclose the first dozen lines:
- Translate the `title` and `short_description` values.
- Do not translate the `id`, `aka`, `tags` values. We will systematically translate those later on in a separate project.

## Translating the content body

Below the frontmatter, in the content body:
- Translate almost everything.
- If you encounter a glossary shortcode, for example, `{{< glossary_tooltip text="containers" term_id="container" >}}`, translate the `text` value. But do not translate the `term_id` value.

# Procedure:
1. In this issue, assign this issue to yourself by commenting: `/assign <your_github_id>`
1. Open PR #35942.
1. In the PR, select all the lines in the file and click `+` to comment. ![Screenshot 1](https://user-images.githubusercontent.com/350907/184517749-6b3283a1-31d1-4254-82bd-27f12a7c6f3e.png)
1. In the comment, click the **+/-** suggestion icon (screenshot 2). ![Screenshot 2](https://user-images.githubusercontent.com/350907/184517750-e11d44aa-c626-4033-88d4-247d0905d04d.png)
1. In the suggestion, localize the content to Hindi.
1. IMPORTANT: Click the **Start a review** button.
1. IMPORTANT: Click **Review changes**, **Comment**, and **Submit review**. ![Screenshot 3](https://user-images.githubusercontent.com/350907/184517748-f735cf8c-4ca8-4be5-be41-c1f60478e618.png)

*Note*: By completing these steps, your GitHub profile will give you credit for performing a code review!

As follow-up steps, I will do the following:
- Apply your suggested localization to the PR.
- Ask a reviewer to review the localized content.
- Update the content as needed.
- Get the PR approved and merged.

This feature issue is part of the following project:
- https://github.com/kubernetes/website/issues/35600

**Comment by bishal7679** [comment]
@NitishKumar06 Thanks for giving your valuable time 👍 
Actually some misunderstanding happened here. I think @rolfedh raised a demo PR for this term in english which has not localized in hindi yet. Thats why @taniaduggal got assigned.

**Comment by rolfedh** [comment]
@NitishKumar06 @taniaduggal @bishal7679 I created two issues like this one, each linked to PRs that contain an unlocalized file. I intended to provide a way for absolute newcomers to contribute without signing a CLA, setting up a fork/local clone of the repo, learning git, etc. I welcome anyone self-assigning these issues to take on the localization task. Please provide feedback to help me improve it for future contributors.

After I have this raft of issues and pull requests merged, let's do a quick retrospective. I'll use your feedback to update the templates and processes we use to help avoid any confusion as we scale this up to more and more contributors.
