### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/application-architect.md

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#35944]
# Instructions

- Review a few [examples of localized glossary entries](https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859).
- In the examples, notice which elements are translated and which ones are not.

## Translating the frontmatter

In the frontmatter, that is, between the `---` markers that enclose the first dozen lines:
- Translate the `title` and `short_description` values.
- Do not translate the `id`, `aka`, `tags` values. We will systematically translate those later on in a separate project.

## Translating the content body

Below the frontmatter, in the content body:
- Translate almost everything.
- If you encounter a glossary shortcode, for example, `{{< glossary_tooltip text="containers" term_id="container" >}}`, translate the `text` value. But do not translate the `term_id` value.

# Procedure:
1. In this issue, assign this issue to yourself by commenting: `/assign <your_github_id>`
1. Open PR https://github.com/kubernetes/website/pull/35945.
1. In the PR, select all the lines in the file and click `+` to comment. ![Screenshot 1](https://user-images.githubusercontent.com/350907/184517749-6b3283a1-31d1-4254-82bd-27f12a7c6f3e.png)
1. In the comment, click the **+/-** suggestion icon (screenshot 2). ![Screenshot 2](https://user-images.githubusercontent.com/350907/184517750-e11d44aa-c626-4033-88d4-247d0905d04d.png)
1. In the suggestion, localize the content to Hindi.
1. IMPORTANT: Click the **Start a review** button.
1. IMPORTANT: Click **Review changes**, **Comment**, and **Submit review**. ![Screenshot 3](https://user-images.githubusercontent.com/350907/184517748-f735cf8c-4ca8-4be5-be41-c1f60478e618.png)

*Note*: By completing these steps, your GitHub profile will give you credit for performing a code review!

As follow-up steps, I will do the following:
- Apply your suggested localization to the PR.
- Ask a reviewer to review the localized content.
- Update the content as needed.
- Get the PR approved and merged.

This feature issue is part of the following project:
- https://github.com/kubernetes/website/issues/35600

**Comment by divya-mohan0209** [comment]
This has been fixed by [#36084](https://github.com/kubernetes/website/pull/36084). Hence closing this issue. 
/close
