### ISSUE TITLE
[ko] Translate 'docs/tasks/configure-pod-container/assign-cpu-resource/' into Korean

### ISSUE THREAD

**Issue by yuzin9712** [kubernetes/website#35968]
**This is a Feature Request**

**What would you like to be added**

Translate 'docs/tasks/configure-pod-container/assign-cpu-resource/' into Korean.

**Why is this needed**
Not translated into Korean yet.

**Comments**

Related Link: https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/

/language ko
/assign

**Comment by jihoon-seo** [comment]
"Assign Memory Resources to Containers and Pods" 페이지는 한국어 버전이 있는데
제안해 주신 페이지는 아직 한국어 버전이 없네요 ㅎㅎ
감사합니다!
/triage accepted

**Comment by aj11anuj** [comment]
/triage duplicate
Subset of issue #41631 (M161)
