### ISSUE TITLE
Trouble following advice in “Configuring a cgroup driver”

### ISSUE THREAD

**Issue by cecco16** [kubernetes/website#35982]
Kubeadm init fails with the following error installing a cluster with containerd configured as per the guide. Looks like it cannot detect the CRI, it was fixed after removing the configuration file and restarting the service

```
[ERROR CRI]: container runtime is not running: output: E0815 14:18:26.988915  588267 remote_runtime.go:925] "Status from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
time="2022-08-15T14:18:26Z" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
        cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
        cmd/kubeadm/app/kubeadm.go:50
main.main
        cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571
```

**Comment by sftim** [comment]
/retitle Trouble following advice in “Configuring a cgroup driver”

I assume that the page you were reading is https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/ @cecco16 - is that right?

How did you decide which cgroup driver was right for your setup @cecco16?

You might find that https://github.com/containerd/containerd/issues/4581#issuecomment-1137887069 is relevant and that the issue is actually that you used the default configuration that comes with Ubuntu's containerd package. If you instead configurer containerd the way that Kubernetes expects, with CRI support enabled, then it'd work OK.

There's some basic [containerd documentation](https://containerd.io/docs/) but those docs do need some work.

**Comment by cecco16** [comment]
That is correct, I was going through the configuring a cgroup driver. The decision to go for systemd instead of cgroupfs is mostly due to stability reason.

Concerning the toml file that was recreated and changed the Systemdcgroup to true. Will go through the docs and give it another shot.

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by sftim** [comment]
/kind support

I think

**Comment by cecco16** [comment]
Hi Tim,

it was my bad, essentially what fixed the issue was to recreate the containerd configuration file once logged in as root, running it with sudo I messed up the output redirection.

Sent from [ProtonMail](https://protonmail.com), Swiss-based encrypted email.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by sftim** [comment]
Nothing to fix in k8s docs.
/close
