### ISSUE TITLE
Unwanted spaces in YAML file 

### ISSUE THREAD

**Issue by rghdrizzle** [kubernetes/website#36003]
**This is a Bug Report**

There are some unwanted spaces in the yaml file found in the page "configure a pod to use a configmap"

**Proposed Solution:**
To remove those unwanted spaces 

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

I would like to work on this.( btw im new to open source)

**Comment by jihoon-seo** [comment]
I guess that this issue is from https://github.com/kubernetes/website/issues/35986#issuecomment-1216038143.

Please note that each empty line contains 2 spaces in that page.

You may also see:
- #34447
- #34736

**Comment by sftim** [comment]
/triage accepted

A special case of https://github.com/kubernetes/website/issues/36813

**Comment by jihoon-seo** [comment]
Resolved by #36850
/close
