### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/access-cluster-api/

### ISSUE THREAD

**Issue by projectaws741** [kubernetes/website#36022]
Hello 
Error from server (Forbidden): <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fswagger-2.0.0.pb-v1%3Ftimeout%3D32s'/><script>window.location.replace('/login?from=%2Fswagger-2.0.0.pb-v1%3Ftimeout%3D32s');</script></head><body style='background-color:white; color:white;'>

Authentication required

im getting this error.
i created a gcp(google cloud) kubernetes cluster and i connected to that cluster via instance using gcp cli. i had written a pipeline script to execute the deployment.yml it throws back above error

**Comment by utkarsh-singh1** [comment]
Hi @projectaws741, can you paste your whole error here in code format so that it can be easily readable.

**Comment by sftim** [comment]
I think this is a support query. I'm not sure.

**Comment by utkarsh-singh1** [comment]
@projectaws741, has your issue have been resolved?

**Comment by utkarsh-singh1** [comment]
Hi @projectaws741, As this is support query please raise your query on

- https://serverfault.com/?tags=kubernetes
- https://discuss.kubernetes.io/
