### ISSUE TITLE
Tutorial interactivo - Crear un clúster

### ISSUE THREAD

**Issue by ivegamerayo** [kubernetes/website#36046]
katacoda.com is now closed to the public and content is no longer available.

**Comment by jihoon-seo** [comment]
`es` page: https://kubernetes.io/es/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
![image](https://user-images.githubusercontent.com/46767780/185254898-f4e3cf9b-74a6-44df-98ef-97a4678efeb2.png)

---

`en` page: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
![image](https://user-images.githubusercontent.com/46767780/185254948-5cfcd48d-4d6d-4b4d-a1b8-979ac0c22a79.png)

/language es
/triage accepted

**Comment by utkarsh-singh1** [comment]
Hi @jihoon-seo, I think Interactive tutorial environment for k8s is also showing same result here - https://kubernetes.io/id/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by jihoon-seo** [comment]
@utkarsh-singh1 it seems that to make the interactive tutorial in those pages work, someone has to update those pages to be synced with the English page.

**Comment by utkarsh-singh1** [comment]
@jihoon-seo , Will raising an issue with the link - https://kubernetes.io/id/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ can be helpful?

**Comment by jihoon-seo** [comment]
@utkarsh-singh1 it would be great! And other pages that have the same issue too.

**Comment by utkarsh-singh1** [comment]
@jihoon-seo I have checked the other pages, it seems pages translated in Spanish and Indonesian have these issue right now.
