### ISSUE TITLE
[de] L10n of the word 'abstraction' to German

### ISSUE THREAD

**Issue by Margrie** [kubernetes/website#36052]
Ich würde das Wort "Abstraktionen" durch das Wort "Entwicklungen" austauschen. Das ist im deutschen umgangssprachlicher als Abstraktionen.

**Comment by jihoon-seo** [comment]
@Margrie what is the URL of page that you think needs modifications? Please provide this information in the issue body.
(My guess is: https://kubernetes.io/de/docs/concepts/ )

And please try to write the issue title and body in English!

/language de
/retitle [de] L10n of the word 'abstraction' to German
