### ISSUE TITLE
[ko] Translate "/docs/concepts/workloads/pods/downward-api" into Korean

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/website#36058]
**This is a Feature Request**

**What would you like to be added**
Translate /docs/concepts/workloads/pods/downward-api into Korean.

**Why is this needed**
This page has not been translated yet.
https://kubernetes.io/docs/concepts/workloads/pods/downward-api/

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
@bconfiden2 감사합니다!
/triage accepted
