### ISSUE TITLE
Common Parameters: Chinese translation of fieldSelector is wrong

### ISSUE THREAD

**Issue by kevinat** [kubernetes/website#36060]
默认为返回所有字段 should be 默认为返回所有对象

because **fieldSelector** is intend to filter objects, not fields. 

Current translation may lead misunderstanding the functions of **fieldSelector**

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-parameters/common-parameters/
/language zh

**Comment by tengqm** [comment]
/close
The understanding is incorrect.
