### ISSUE TITLE
[zh] Example output does not match the description

### ISSUE THREAD

**Issue by cocakoala** [kubernetes/website#36064]
章节位置：https://kubernetes.io/zh-cn/docs/concepts/configuration/manage-resources-containers/#%E6%88%91%E7%9A%84%E5%AE%B9%E5%99%A8%E8%A2%AB%E7%BB%88%E6%AD%A2%E4%BA%86

kubectl describe pod simmemleak-hra99 的结果中关于容器终止原因的部分与正文描述不一致
示例输出：
```
    Last Termination State:     Terminated
      Exit Code:                1
      Started:                  Fri, 07 Jul 2015 12:54:30 -0700
      Finished:                 Fri, 07 Jul 2015 12:54:33 -0700
```

正文描述：
......
原因 OOMKilled 显示容器尝试使用超出其限制的内存量。
......

**Comment by jihoon-seo** [comment]
/language zh
/retitle [zh] Example output does not match the description

**Comment by mengjiao-liu** [comment]
It seems that some of the content is out of sync with the English, I will check.
/assign
