### ISSUE TITLE
Document best practices on LB configuration(s). 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/website#3607]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
Missing documentation on best practices for LB configurations.

**Proposed Solution:**

- Leverage /healthz endpoint in LB configs settings. 
  - http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html . This is to ensure that requests are properly sent to active api-servers.

- Encourage LBs leverage (source) settings to ensure cache hits.
  - Over the course of several years, the api-server has started to maintain larger and larger caches, encouraging source will leverage those caches more effectively.  (We should metrics hit %s honestly) 

- Update connection timeouts to their highest possible settings as this can lead to expensive relists. 

- Internal and External LBs.
  - Traffic isolation, cache hits, and external LB's don't need such a high TTL. 

**Page to Update:**
TODO

**Comment by jamiehannaford** [comment]
@timothysc I can work on this (feel free to assign). I'm a bit unclear on #2, what type of apiserver caching are you referring to? Do you expect the LB to handle content caching or the apiserver?
