### ISSUE TITLE
well-known labels restriction is missing k8s.io (?)

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/website#36078]
**This is a Bug Report**

**Problem:**

"Well-Known Labels, Annotations and Taints" says
> Kubernetes reserves all labels and annotations in the kubernetes.io namespace.

Except it's actually kubernetes.io *AND* k8s.io (?) cc @liggitt 

**Proposed Solution:**

Add k8s.io

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

Filing an issue so I don't forget this. See discussion https://github.com/kubernetes-sigs/kind/pull/2877

**Comment by NitishKumar06** [comment]
I think k8s.io and kubernetes.io both hold the same meaning.
