### ISSUE TITLE
Wrong image in example

### ISSUE THREAD

**Issue by Grigoryan-not-available** [kubernetes/website#36075]
**This is a Bug Report**

**Problem:**
Wrong image for this example
**mysql:5.7** now uses **oraclelinux:7-slim**
This OS doesn't have a "hostname" command
[image](https://fex.net/s/sem9yop)

**Proposed Solution:**
Using image **_mysql:5.7-debian_**

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#statefulset

**Comment by jihoon-seo** [comment]
This issue is a dup of #35432.
/triage duplicate

There is a relevant PR: #35857.
