### ISSUE TITLE
[ko] Translate tasks/debug/debug-cluster/crictl in Korean

### ISSUE THREAD

**Issue by marcushyungseoklee** [kubernetes/website#36093]
**This is a Feature Request**

**What would you like to be added**
Translate tasks/debug/debug-cluster/crictl in Korean.

**Why is this needed**

No translation with /tasks/debug/debug-cluster/crictl

**Comments**

Pages to Update
https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/

**Comment by jihoon-seo** [comment]
@marcushyungseoklee 님 안녕하세요~~
같은 문서에 대해 이미 이슈가 오픈되어 있습니다. ㅠㅠ (#35090)
참고 부탁드립니다 😊
/triage duplicate

**Comment by marcushyungseoklee** [comment]
@jihoon-seo 엇 그러네요 ㅠㅠ 감사합니다 다른부분으로 진행해보겠습니다.
