### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl-linux/

### ISSUE THREAD

**Issue by neilgierman** [kubernetes/website#36108]
The instructions for adding kubernetes to Debian-based distributions is still pointing to the old `https://apt.kubernetes.io` website. That needs to be changed to `https://packages.cloud.google.com/apt/` since now the previous server has SSL certificate issues.

**Comment by raghu-manne** [comment]
@utkarsh-singh1 Are you working on this?

**Comment by utkarsh-singh1** [comment]
Yeah @raghu-manne

**Comment by utkarsh-singh1** [comment]
Hi @neilgierman , I have tried installing kubectl in both debian -10 and debian-11 and https://apt.kubernetes.io automatically redirects to the https://packages.cloud.google.com/apt/.

**Comment by sftim** [comment]
There is a related problem, which is that https://packages.cloud.google.com/apt/ is in fact _not_ exactly an official Kubernetes artifact repository (it belongs instead to Google).

See https://github.com/kubernetes/release/issues/913#issuecomment-1081121833 for more context.

**Comment by sftim** [comment]
I don't think we should change the docs. I think we should change things on the release and artifacts side, where possible.

**Comment by utkarsh-singh1** [comment]
@neilgierman if the issue has been resolved please can you close it.

**Comment by neilgierman** [comment]
I am reluctant to close the issue based on comments from @sftim. This is no longer a documentation issue since right now the docs work again, however is redirecting to Google the correct action?

**Comment by sftim** [comment]
I don't think there's anything to fix here. SIG Release are already tracking the work to move away from the existing artifacts release process and hosting for Linux packages.

@neilgierman I recommend you close this. If you want to suggest work, or contribute,  https://github.com/kubernetes/release/issues/ is the place for that.
