### ISSUE TITLE
Explain requirement for `br_netfilter` module on Linux nodes

### ISSUE THREAD

**Issue by DJM0502** [kubernetes/website#36120]
Hi,

why we are adding this section "Make sure that the br_netfilter module is loaded" when this section will be coming from 
container run time https://v1-20.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

if you see you had already mention of this module on this page https://v1-20.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports  and steps to created this using file file  k8s.conf
 
while same is suppose to be coming from the container-rutimes br_netfilter.

this create confusion.

Thanks
DJM

**Comment by kundan2707** [comment]
@DJM0502  Agree with you point that br_netfilter module will be coming from container run time. 
but there is nothing wrong in validating again if module is loaded or not.

**Comment by neolit123** [comment]
/sig cluster-lifecycle

the section on the install page is also about iptables and we established it's required CR / networking. i don't think we should break apart the section or move it elsewhere, as it seems like a requirement before installing kubeadm not only the CR. More opinions are welcome, of course.

**Comment by sftim** [comment]
/retitle Explain requirement for `br_netfilter` module on Linux nodes
