### ISSUE TITLE
[en] Minor typo in tasks/debug/debug-cluster/local-debugging.md

### ISSUE THREAD

**Issue by bang9211** [kubernetes/website#36138]
**This is a Bug Report**

**Problem:**
tasks/debug/debug-cluster/local-debugging.md has a typo "$LOCAL_PORT:REMOTE_PORT"

**Proposed Solution:**
Fix the typo (it should be "$LOCAL_PORT:$REMOTE_PORT")

**Page to Update:**
https://kubernetes.io/docs/tasks/debug/debug-cluster/local-debugging/

/language en
/assign

**Comment by mk46** [comment]
Addressed in https://github.com/kubernetes/website/pull/36141
/close
