### ISSUE TITLE
Install Tools page states that kind requires Docker

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36159]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/tasks/tools/ states that kind requires Docker. This isn't right as I understand it; you can actually use `kind` with Podman, even if you don't have Docker installed at all.

**Proposed Solution:**
- check what's right
- update the docs to match the truth

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/

**Additional Information:**
/language en

**Comment by PriyanshuAhlawat** [comment]
@sftim according to my knowledge we can use Buildah for managing container images and Podman for managing containers if someone is looking for an alternative to docker. But these can be used only on Linux, so for windows or mac a Linux VM will be used to run these and I am thinking to put this in a note. 
Your suggestions?

**Comment by sftim** [comment]
https://www.google.com/search?q=does+kind+work+with+podman

(yes)

Also see https://kind.sigs.k8s.io/docs/user/rootless/

Kubernetes itself doesn't require any of the listed tools (Podman, Docker, Buildah); for example, you might use CRI-O and runsc and the kubelet, but no Docker Engine.

**Comment by afbjorklund** [comment]
Podman now has documentation on how to work with the `kind` and `minikube` plug-ins:

https://podman-desktop.io/docs/kubernetes
