### ISSUE TITLE
Advice on using containers

### ISSUE THREAD

**Issue by dolamaiti** [kubernetes/website#36156]
I am having an issue whenever a user is created the same pod gets initialized to the user instance and so I am unable to create a new pod for the particular user. I need different pods for different users.
There was no limit range for containers. The requirement is I need to assign container to the pods.

**Comment by sftim** [comment]
@dolamaiti, GitHub is not the right place for support requests.

If you're still looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
