### ISSUE TITLE
Multiple broken link in https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2022-05-06-storage-capacity-GA/index.md

### ISSUE THREAD

**Issue by kundan2707** [kubernetes/website#36151]
**This is a Bug Report**

**Problem:**
Broken links
**Proposed Solution:**
Link Correction
**Page to Update:**
https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2022-05-06-storage-capacity-GA/index.md

**Comment by jihoon-seo** [comment]
From https://github.com/kubernetes/website/pull/36152#issuecomment-1221678845:

> You might think that the links are broken in [the markdown file in this repo](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2022-05-06-storage-capacity-GA/index.md),
> but the markdown file is a source code file to render [this page](https://kubernetes.io/blog/2022/05/06/storage-capacity-ga/) eventually,
> and those links are not broken and working fine in that page.
> 
> Also, prepending the site domain name (`https://kubernetes.io`) in the markdown links is discouraged in this repo.
> 
> So it would be appropriate to close this issue.

So, let me close this.
/close
