### ISSUE TITLE
Guidelines for Hindi localization (glossary)

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#36163]
> @bishal7679 somewhere you also add English title with Hindi and somewhere not. What guidelines you follow to do like this. Please let me know:)

Thanks for reminding me
I forgot to add english with hindi as well

_Originally posted by @bishal7679 in https://github.com/kubernetes/website/issues/35600#issuecomment-1221472160_

**Comment by rolfedh** [comment]
@AmanSarraf If this isn't already covered, would you research some best practices on this issue and add it to the /hi style guide?
@taniaduggal @bishal7679

**Comment by AmanSarraf** [comment]
I will look into it
