### ISSUE TITLE
Punctuation errors on https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-definitions/

### ISSUE THREAD

**Issue by syxunion** [kubernetes/website#36187]
Hello, I noticed some punctuation errors on https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-definitions page
/language zh

**Comment by sftim** [comment]
/retitle Punctuation errors on https://kubernetes.io/zh-cn/docs/reference/kubernetes-api/common-definitions/

/remove-kind feature
/kind bug
