### ISSUE TITLE
Annotation `storage.alpha.kubernetes.io/migrated-plugins` not registered / documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36194]
**This is a Bug Report**

**Problem:**
Kubernetes can set an annotation, `storage.alpha.kubernetes.io/migrated-plugins`, but this is not registered or documented.

**Proposed Solution:**
Document the annotation in [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/).

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig storage
/language en

**Comment by afzal442** [comment]
Hi @sftim! Let me know how I can get the details of that and other `annotation`s usage. Thanks.

**Comment by sftim** [comment]
> Hi @sftim! Let me know how I can get the details of that and other `annotation`s usage. Thanks.

Although I was able to spot that the annotation was not documented, I do not know how Kubernetes uses this annotation.
If someone wants to work on this issue, it'll be a good idea to either:
- have a chat with SIG Storage folks about how Kubernetes uses this annotation
- read the Kubernetes source code to find out.

It's also OK to use a mix of those approaches.

**Comment by mehabhalodiya** [comment]
@afzal442 any updates here?

**Comment by sftim** [comment]
(anyone is welcome to work on this - we have a “no cookie licking” policy in SIG Docs)

If someone has said they plan to work on an issue, and you're also considering that work, it's polite - but not mandatory - to try to co-ordinate.

**Comment by Ritikaa96** [comment]
- I found usage of this plugin in OpenStack Cloud provider repo :[here](https://github.com/kubernetes/cloud-provider-openstack/blob/e87f50614b96a6af6095660aa6a77457223b344b/docs/openstack-cloud-controller-manager/migrate-to-ccm-with-csimigration.md?plain=1#L164)
```
root@small-k8s-1:~# kubectl get csinode small-k8s-2 -o yaml
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  annotations:
    storage.alpha.kubernetes.io/migrated-plugins: kubernetes.io/cinder
  ...
``` 

- in [#657](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/625-csi-migration/README.md),
the CSI migration specific field shows:
      `For CSINode object that maps to a node which installs CSIDriver, if CSI Migration is turned on, a new annotation will be added storage.alpha.kubernetes.io/migrated-plugins

**Comment by Ritikaa96** [comment]
/assign
I will like to work on this .

**Comment by Ritikaa96** [comment]
Just for cross check:
The documentation will be as follows:
```
Type: Annotation

Example:`storage.alpha.kubernetes.io/migrated-plugins:" kubernetes.io/cinder"`
 `storage.alpha.kubernetes.io/migrated-plugins: "kubernetes.io/vsphere-volume"`

Used on: CSINode

This annotation is automatically added when CSIMigration is enabled/turned-on for CSINode object that maps to a node that installs CSIDriver.
For example, after we enable the migration, the csinodes instance for the node should be updated with the storage.alpha.kubernetes.io/migrated-plugins annotation and we can see it in the node description i.e. `kubectl describe <csinode>`
```
How does this look?

**Comment by Ritikaa96** [comment]
Hi, JFYI I just made the new changes to remove CSImigration reference in the PR. I'll wait for more suggestions if there are any. Thanks!

**Comment by Ritikaa96** [comment]
As the PR has been merged , this issue is resolved.
thus closing it.
/close
