### ISSUE TITLE
Update PSP deprecation blog article to link to v1.25 release blog

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36199]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ (but check with @tabbysable, the author, before you do)
Make it obvious that your change is an update to an existing article. Hyperlink to https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#pod-security-changes

**Why is this needed**
PodSecurityPolicy is no longer deprecated; it is actually _removed_. It helps to amplify that story.

**Comments**
/area blog

Follows on from https://github.com/kubernetes/website/pull/34290

**Comment by sftim** [comment]
/retitle Update PSP deprecation blog article to link to v1.25 release blog

**Comment by NitishKumar06** [comment]
@tabbysable Any suggestion from your end?

**Comment by NitishKumar06** [comment]
@tabbysable ??

**Comment by tabbysable** [comment]
This seems like a good idea. Perhaps add something like this, up at the top of the document?

```
Update 2022/08/23:

With the release of Kubernetes v1.25, PodSecurityPolicy has been removed. This now-historical blog post documents the beginning of the removal process.

The release blog has more information about the removal of PSP: https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#pod-security-changes

```
