### ISSUE TITLE
Annotation `pv.kubernetes.io/bind-completed` not registered / documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36190]
**This is a Bug Report**

**Problem:**
Kubernetes can set an annotation, `pv.kubernetes.io/bind-completed`, but this is not registered or documented.

**Proposed Solution:**
Document the annotation in [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/).

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig storage
/language en

**Comment by sftim** [comment]
Try https://github.com/kubernetes/kubernetes/search?q=bind-completed&type=code as a way to find code that uses this annotation.

**Comment by afzal442** [comment]
Yes! that's nice. I had a same thought like searching out. 😄 

So, I would go like this as below:
```
pv.kubernetes.io/bind-completed
Example: pv.kubernetes.io/bind-completed "true"

Used on: PersistentVolumeClaim

The value for this annotation must be true to take effect. This annotation indicates that persistent volume attached to the pods must be bound and status is completed.

```

**Comment by sftim** [comment]
You can write `{{< glossary_tooltip text="PersistentVolume" term_id="persistent-volume" >}}` instead of `persistent volume` and you then get a nice tooltip (see [Custom Hugo Shortcodes](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary)).

**Comment by mehabhalodiya** [comment]
@afzal442 any updates on this? 🙂

**Comment by afzal442** [comment]
hey @mehabhalodiya u can refer to this comment https://github.com/kubernetes/website/pull/36399#issuecomment-1383836558

I think u can close this issue
