### ISSUE TITLE
"The specified key does not exist" error while installing kubeadm

### ISSUE THREAD

**Issue by SunsetFeng** [kubernetes/website#36212]
I'm follow the documentation to install kubeadm,but prompt me “The specified key does not exist.”

run command:

DOWNLOAD_DIR=/usr/local/bin
sudo mkdir -p $DOWNLOAD_DIR
RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
cd $DOWNLOAD_DIR
sudo curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/${ARCH}/{kubeadm,kubelet,kubectl}
sudo chmod +x {kubeadm,kubelet,kubectl}

documentation:https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by jihoon-seo** [comment]
/kind support

@SunsetFeng 
it seems that among the command list you listed, the command `ARCH="amd64"` is missing.

Please try:
run `ARCH="amd64"` before running `sudo curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/${ARCH}/{kubeadm,kubelet,kubectl}`

**Comment by SunsetFeng** [comment]
thanks,I can get it

**Comment by shurup** [comment]
It seems that the documentation itself is correct as it has the instruction mentioned above.

/retitle "The specified key does not exist" error while installing kubeadm
/close

**Comment by jihoon-seo** [comment]
From https://github.com/kubernetes/website/issues/36212#issuecomment-1259014457:

/retitle "The specified key does not exist" error while installing kubeadm
/close
