### ISSUE TITLE
v1.25 API is 404

### ISSUE THREAD

**Issue by abel533** [kubernetes/website#36260]
**This is a Bug Report**

**Problem:**
v1.25 API is 404
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/

Kubernetes Version: v1.25

![image](https://user-images.githubusercontent.com/1787798/186548654-855255fc-ee96-4e86-a94a-fee858f00c21.png)

![image](https://user-images.githubusercontent.com/1787798/186548689-5875a681-1854-4767-a4ed-604f9d580ae7.png)

**Comment by abel533** [comment]
I need to use this document to generate structured data.
![image](https://user-images.githubusercontent.com/1787798/186548941-80d77cb1-ec89-405f-9cb0-6b99517d40a0.png)

https://k8s.mybatis.io/

**Comment by mengjiao-liu** [comment]
https://github.com/kubernetes/website/pull/36112 is working on it.

**Comment by reylejano** [comment]
Fixed by PR https://github.com/kubernetes/website/pull/36112
