### ISSUE TITLE
Broken links in feature-gates.md

### ISSUE THREAD

**Issue by windsonsea** [kubernetes/website#36280]
**This is a Bug Report**

In the file:
```
content/en/docs/reference/command-line-tools-reference/feature-gates.md
```
find two hits:
```
See [Traces for Kubernetes System Components](/docs/concepts/cluster-administration/traces-for-kubernetes-system-components) for more details.
```
with broken links to 404.

/language en

**Comment by Shubham82** [comment]
Below is the correct link for **Traces for Kubernetes System Components**:
https://kubernetes.io/docs/concepts/cluster-administration/system-traces/
