### ISSUE TITLE
Add guidance for reviewers about squashing commits

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#36294]
**This is a Feature Request**

**What would you like to be added**

As a PR reviewer, I'd like guidance on when to ask PR owners to squash their commits, when to do it for them, and when to never squash commits.

**Why is this needed**

Please see the following thread:

[Rolfe Dlugy-Hegwer](https://app.slack.com/team/UMT020Y0Y)
Do we require PR owners to squash before merge, or do merge folk sometimes help them out by using the GitHub squash feature when we merge PRs? (edited) 

[sftim](https://app.slack.com/team/UGBUYDQR2)
If there are lots of commits, maybe a history of edits towards getting the PR right:
- I strongly prefer a squash first
- if the author doesn't know how, a maintainer can offer to squash it for them and update their fork with the result
- if there is time pressure we could get GitHub to do a squash instead, via the label

If there are two or three commits:
- I will ask for a squash first if I am confident the PR author knows how to
- if the author doesn't know how,  it's fine to add the label and get Tide / GitHub to sort it out
except that:
- if there are say three commits, and the middle commit does something obviously broken or unwise, and the last commit reverts it
  - then this will create rebase / merge conflicts for other folks
  - even though the “files” view in GitHub web looks OK, and the Netlify preview looks OK
- a maintainer should intervene as they see fit, to avoid that risk to other contributors

If we're launching a localization or doing a release, and we're merging in a branch that's not from a fork:
- never squash

**Comments**

**Comment by rolfedh** [comment]
FYI @sftim

**Comment by rolfedh** [comment]
Related topic: https://kubernetes.io/docs/contribute/review/for-approvers/

**Comment by sftim** [comment]
Thanks.
The wording _doesn't_ have to be exactly what I suggested.

/triage accepted
/language en

**Comment by mengjiao-liu** [comment]
Maybe you can refer to this document.
https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#squash-commits

```
After a review, prepare your PR for merging by squashing your commits.

All commits left on your branch after a review should represent meaningful milestones or units of work. Use commits to add clarity to the development and review process.

Before merging a PR, squash the following kinds of commits:

Fixes/review feedback
Typos
Merges and rebases
Work in progress
Aim to have every commit in a PR compile and pass tests independently if you can, but it's not a requirement. In particular, merge commits must be removed, as they will not pass tests.
```
This document is the same for the reviewer. If the developer does not do all the suggestions of the document, the reviewer can intervene at this time.

**Comment by sftim** [comment]
https://www.k8s.dev/docs/guide/github-workflow/ is the public URL of that document @mengjiao-liu
