### ISSUE TITLE
Using Source IP's sample image registry doesn't work.

### ISSUE THREAD

**Issue by nicholasyin** [kubernetes/website#36301]
`kubectl create deployment source-ip-app --image=registry.k8s.io/echoserver:1.4`

However, the `registry.k8s.io` domain doesn't seem to work anymore.

**Comment by Shubham82** [comment]
Hi @nicholasyin 
It is working for me.
```
$ kubectl create deployment source-ip-app --image=registry.k8s.io/echoserver:1.4
deployment.apps/source-ip-app created

$ kubectl get deployment
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
source-ip-app   1/1     1            1           12s

$ kubectl get pod
NAME                             READY   STATUS    RESTARTS   AGE
source-ip-app-5c687d697b-jlhk9   1/1     Running   0          14s
```

In k8sv1.25 container registry service is migrated from `k8s.gcr.io` to `registry.k8s.io` . see the [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#moved-container-registry-service-from-k8sgcrio-to-registryk8sio) of k8sv1.25

**Comment by nicholasyin** [comment]
Then it must be some kind of networking issue.
