### ISSUE TITLE
Restoring an etcd cluster does not have the complete instructions

### ISSUE THREAD

**Issue by rawhideron** [kubernetes/website#36338]
Should include (aproximately) the following:

sudo systemctl stop etcd

sudo rm -rf /var/lib/etcd

sudo ETCDCTL_API=3 etcdctl snapshot restore /home/cloud_user/etcd_backup.db \
--initial-cluster etcd-restore=https://etcd1:2380 \
--initial-advertise-peer-urls https://etcd1:2380 \
--name etcd-restore \
--data-dir /var/lib/etcd

sudo chown -R etcd:etcd /var/lib/etcd

sudo systemctl start etcd

ETCDCTL_API=3 etcdctl get cluster.name \
--endpoints=https://etcd1:2379 \
--cacert=/home/cloud_user/etcd-certs/etcd-ca.pem \
--cert=/home/cloud_user/etcd-certs/etcd-server.crt \
--key=/home/cloud_user/etcd-certs/etcd-server.key

**Comment by jihoon-seo** [comment]
Link: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster

**Comment by rawhideron** [comment]
I' having a lot of trouble understanding how the instructions in the above link can restore the etcd database
