### ISSUE TITLE
Release-branch deploys should be production quality

### ISSUE THREAD

**Issue by chalin** [kubernetes/website#36333]
**Problem:** currently, release-branch deploys are not "production quality". For example visit https://v1-24.docs.kubernetes.io/docs/home/ and view the page source. You'll see that the page source:

- Isn't minified
- Assets aren't finger printed -- e.g.:
  ```html
  <link href="/scss/main.css" rel="stylesheet">
  <script src="/js/script.js"></script>
  ```

But release-branch deploys _are_ officially supported documentation, and should be minified and assets finger printed (to avoid caching issues when assets are updated). The only thing that we don't want, as far as I understand, is for these deploys to be indexed. Is that correct @sftim?

**Proposed Solution:** recognized the officially supported release-branch deploys as "production" deploys, but with indexing turned off.

/cc @nate-double-u

**Comment by sftim** [comment]
/area web-development
/priority backlog

Minifying assets for older docs sounds useful. However, there are other issues I'd prefer us to prioritize - for example, https://github.com/kubernetes/website/issues/23518

**Comment by chalin** [comment]
You're right @sftim, when seen in that context. Let me offer a more complete formulation (since I forgot to include the full context in this issue, taking it as implicit).

**Comment by chalin** [comment]
@sftim @nate-double-u - Ok, here's a more complete (hopefully better) picture of the situation as I see it.

When the website is built in **production** mode, we get the following **by default** from Hugo/Docsy:

1. Site indexing is permitted
2. Analytics is enabled
3. Artifacts are minified
4. Assets are finger printed

We want:

- All of the above features for the main deploy, and
- All except (1) for release-branch deploys

PR #36334 proposes to:

- Build release-branch deploys in production mode and
- Selectively disable (1) based on the value of the config param`deprecated` set to `false` for release-branches

This seems like an approach that is more compatible with Hugo/Docsy, and would require less code customization, as compared to continuing to build release-branches in non-production mode and then selectively turning on **three** features (2 to 4).

Hopefully this makes the benefits of #36334 clearer.

Thoughts?

**Comment by chalin** [comment]
@reylejano - during the [01/10 SIG docs meeting](https://docs.google.com/document/d/1emuO4nmaQq3K8JZ9-MQeIygtrCPO9kWv7U7RzTaW4F8/edit#heading=h.ezz94asfzscl) we discussed this issue among others. It's the [previous comment](url) in particular that I'd like your feedback on. Thanks! /cc @a-mccarthy @nate-double-u

**Comment by chalin** [comment]
I still think that this is relevant. Waiting on feedback from https://github.com/kubernetes/website/issues/36333#issuecomment-1294012582.

**Comment by sftim** [comment]
> Minifying assets for older docs sounds useful. However, there are other issues I'd prefer us to prioritize - for example, https://github.com/kubernetes/website/issues/23518

This is still my opinion. However, we're also looking to [revisit](https://github.com/kubernetes/website/issues/45134) the approach for serving older docs. If we do that, I expect that this request gets delivered implicitly.
