### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/

### ISSUE THREAD

**Issue by scudella** [kubernetes/website#36336]
Migrating to containerd requires settings on /etc/systcl.d/99-kubernetes-cri.conf
e.g.
```
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF
```
The migration worked for me until I rebooted due to kernel upgrade. Apparently there were iptables rules left by docker install that allow containerd to work. After the reboot the docker iptables were gone and my nodes could not run e.g. kubernetes dashboard.

**Comment by sftim** [comment]
/language en

A few questions @scudella 
- Which network plugin (if any) were you using with Docker Engine?
- Which network plugin are you using now?
- What version of Kubernetes are you running?

Those answers will help us work out what advice to give to readers.

**Comment by scudella** [comment]
I was using (and still using) Weave cni plugin.
I believe I was running 1.23.4, then I did the dockershim migration to containerd and upgraded to 1.24.3. A couple of days ago I upgraded to 1.24.4 and rebooted. Then I had the problems with the work nodes.
I did install the cluster with instructions on https://github.com/jpetazzo/ampernetacle.git, commit 12616e3...
These iptables rules were still around before rebooting the nodes. After rebooting they were gone. I guess they might be related to the issue.
> DOCKER-USER  all  --  anywhere             anywhere            
> DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
> ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
> DOCKER     all  --  anywhere             anywhere            
> ACCEPT     all  --  anywhere             anywhere            
> ACCEPT     all  --  anywhere             anywhere            
32a39,55
> Chain DOCKER (1 references)
> target     prot opt source               destination         
> 
> Chain DOCKER-ISOLATION-STAGE-1 (1 references)
> target     prot opt source               destination         
> DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
> RETURN     all  --  anywhere             anywhere            
> 
> Chain DOCKER-ISOLATION-STAGE-2 (1 references)
> target     prot opt source               destination         
> DROP       all  --  anywhere             anywhere            
> RETURN     all  --  anywhere             anywhere            
> 
> Chain DOCKER-USER (1 references)
> target     prot opt source               destination         
> RETURN     all  --  anywhere             anywhere            
>

**Comment by tengqm** [comment]
You don't have to reboot the machine if you are simply changing some sysctl variables.
You can google how to make 'sysctl' effective immediately.
/kind support
/close
