### ISSUE TITLE
[zh] Translate CONTRIBUTING.md page

### ISSUE THREAD

**Issue by mack1024** [kubernetes/website#36379]
**This is a Feature Request**

Hi, I'm interested to translate the "CONTRIBUTING.md" page.

translate CONTRIBUTING.md into Chinese.

What would you like to be added:

CONTRIBUTING-ZH.md

/language zh
/kind feature

**Comment by mack1024** [comment]
Can I translate CONTRIBUTING.md?

**Comment by Sea-n** [comment]
The content in `CONTRIBUTING.md` is just a brief summary of [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) page.

The page is already translated here:
https://kubernetes.io/zh-cn/docs/contribute/
