### ISSUE TITLE
Confusing text on User Namespaces page

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#36386]
**This is a Bug Report**

**Problem:**

Below is the text from the 3rd paragraph of the section **Understanding user namespaces for stateless pods** on page https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/#understanding-user-namespaces-for-stateless-pods

> ... You can verify this, for example, if you check the user the container process is running `ps` from the host. The user `ps` shows is not the same as the user you see if you execute inside the container the command `id`.

This is not good English. The command `ps` command doesn't show the user ID or user name. 

**Proposed Solution:**

Revise the text.

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/#understanding-user-namespaces-for-stateless-pods

**Comment by tengqm** [comment]
@rata

**Comment by rata** [comment]
Thanks. @tengqm if we replace `ps` with `ps aux`, do you think it is clear?

**Comment by tengqm** [comment]
@rata, making the command more concrete and specific would be helpful. I assume users may try this difference by hand.

**Comment by rata** [comment]
@tengqm not sure I follow. Do you think using `ps faux` in the text will make it clear and solve this bug or not?

**Comment by tengqm** [comment]
@rata Please check the syntax of  the sentence. It simply doesn't flow.

**Comment by rata** [comment]
@tengqm I'm not a native english speaker. Is this correct?

> ... You can verify this, for example, if you check the user the container process is running by executing `ps aux` from the host. The user `ps` shows is not the same as the user you see if you execute inside the container the command `id`.

Otherwise, can you suggest exactly how you want that to be written?

**Comment by rata** [comment]
Thanks, opened a PR now!
