### ISSUE TITLE
A translation error

### ISSUE THREAD

**Issue by xzyangPlus** [kubernetes/website#36382]
I noticed a translation error at https://kubernetes.io/zh-cn/docs/reference/glossary/?all=true#term-containerd
. The brief description of each item will end with a “。”, but containerd does not have.

**Comment by mengjiao-liu** [comment]
The English page also has this problem, we can update the English part first
https://kubernetes.io/docs/reference/glossary/?all=true#term-containerd

I feel that this punctuation problem does not affect reading, maybe this can be updated next time this page is updated by the way.

/language en
