### ISSUE TITLE
Confusing term "isolation class" in APF doc

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#36393]
**This is a Bug Report**

**Problem:**
Someone reading https://kubernetes.io/docs/concepts/cluster-administration/flow-control/# was not able to discern the intended meaning of the term "isolation class".  See https://kubernetes.slack.com/archives/C01G8RY7XD3/p1661569471734649 .

This term is only used twice, and is used in a way that is synonymous with another term already introduced ("priority level").  I think it would be clearer to replace "isolation class" with "priority level".

**Proposed Solution:**
Replace "isolation class" with "priority level".

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#

This has been there for a while.

**Comment by pcgeek86** [comment]
This is what I originally posted in the #api-priority-and-fairness Slack channel. Thanks for filing this on GitHub, Mike.

![image](https://user-images.githubusercontent.com/466713/187722481-fc09c35b-f886-41fe-86d4-165108330213.png)
