### ISSUE TITLE
[ko]Translate content/en/docs/reference/glossary/*.md files into Korean

### ISSUE THREAD

**Issue by tonyhan18** [kubernetes/website#36392]
**This is a Feature Request**

**What would you like to be added**

Translate content/en/docs/reference/glossary/*.md files into Korean
page: https://kubernetes.io/ko/docs/reference/glossary/?all=true
File: https://github.com/kubernetes/website/content/en/docs/reference/glossary under files

- application-architect
- application-developer
- cadvisor
- cluster-architect
- cluster-operations
- cluster-operator
- containerd
- cri-o
- developer
- downstream
- downward-api
- endpoint-slice
- eviction
- flexvolume
- kops
- manifest
- master
- operator-pattern
- platform-developer
- pod-disruption-budget
- security-context
- shuffle-sharding
- upstream
- user-namespace

**Why is this needed**

not translated yet

**Comments**

/language ko

**Comment by seokho-son** [comment]
I'd like to close this issue since this issue can be divided into several individual issues.

/close
