### ISSUE TITLE
Wrong link context on Storage Classes page

### ISSUE THREAD

**Issue by xzyangPlus** [kubernetes/website#36409]
stay https://kubernetes.io/zh-cn/docs/concepts/storage/storage-classes/#vsphere In the page, the link at the text "vSphereVolume CSI 迁移" should be https://kubernetes.io/zh-cn/docs/concepts/storage/volumes/#vsphere -csi-migration

**Comment by mengjiao-liu** [comment]
Are you still working on it?

**Comment by mengjiao-liu** [comment]
I submitted PR  #36054 to solve this issue and put you as the co-author.
