### ISSUE TITLE
[ko]Translate content/en/docs/setup/best-practices/enforcing-pod-security-standards.md file into Korean

### ISSUE THREAD

**Issue by tonyhan18** [kubernetes/website#36402]
**This is a Feature Request**

**What would you like to be added**

Translate content/en/docs/setup/best-practices/enforcing-pod-security-standards.md file into Korean
page: https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/
File: https://github.com/kubernetes/website/content/en/docs/setup/best-practices/enforcing-pod-security-standards/

**Why is this needed**

not translated yet

**Comments**

/language ko

**Comment by jihoon-seo** [comment]
@tonyhan18 관심 및 기여에 감사드립니다. 그런데 동일 페이지에 대해 [이슈](https://github.com/kubernetes/website/issues/35919)가 열려 있습니다.. 😅
/triage duplicate

**Comment by tonyhan18** [comment]
@jihoon-seo  취소하겠습니다

**Comment by tonyhan18** [comment]
@jihoon-seo 취소하겠습니다
