### ISSUE TITLE
[ko] Translate docs/concepts/overview/working-with-objects/owners-dependents.md into Korean

### ISSUE THREAD

**Issue by tonyhan18** [kubernetes/website#36418]
**This is a Feature Request**

**What would you like to be added**

Translate docs/concepts/overview/working-with-objects/owners-dependents.md into Korean.

Page: https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
File: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/overview/working-with-objects/owners-dependents.md

**Why is this needed**

This has not been translated into Korean yet.

**Comments**

/language ko

**Comment by seokho-son** [comment]
/triage accepted

Thank you @tonyhan18  :)

**Comment by seokho-son** [comment]
/assign @tonyhan18 

considering #36743
