### ISSUE TITLE
[ko] Translate content/en/docs/tasks/kubelet-credential-provider/kubelet-credential-provider into Korean

### ISSUE THREAD

**Issue by Seo-yul** [kubernetes/website#36446]
This is a Feature Request

What would you like to be added
Translate content/en/docs/tasks/kubelet-credential-provider/kubelet-credential-provider.md into Korean

◾ Page: https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/
◾ File: https://github.com/kubernetes/website/blob/dev-1.24-ko.3/content/en/docs/tasks/kubelet-credential-provider/kubelet-credential-provider.md

Why is this needed
Not translated yet

Comments
/language ko
/assign

**Comment by jihoon-seo** [comment]
@Seo-yul 감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #36491
- #36804
- #36810

/close
