### ISSUE TITLE
There are errors in the document of《为 Kubernetes 文档出一份力》

### ISSUE THREAD

**Issue by mack1024** [kubernetes/website#36447]
Hi, I found a problem in the document. There is navigation on the right side of the English document, but there is no navigation on the right side of the Chinese document. I want to correct this error.

Chinese document :  https://kubernetes.io/zh-cn/docs/contribute/
English document :  https://kubernetes.io/docs/contribute/

![图片](https://user-images.githubusercontent.com/42838155/187638858-a1e150b4-3df2-4d78-8ef7-a0b9197763b6.png)
![图片](https://user-images.githubusercontent.com/42838155/187638886-2923d400-493b-485d-97a2-eeb4ac24e501.png)

**Comment by mack1024** [comment]
May I correct this error?

**Comment by tengqm** [comment]
@mack1024 Please go ahead and try fix it.
/assign @mack1024

**Comment by mengjiao-liu** [comment]
Now navigation in zh page version already exists.
![image](https://user-images.githubusercontent.com/44460091/200730246-5e40eccb-b03c-41ed-ade8-6e69a7e51936.png)

Maybe we can close the issue.

**Comment by tengqm** [comment]
/close

Feel free to reopen if the problem persists.
