### ISSUE TITLE
ControllerRevision doc update

### ISSUE THREAD

**Issue by sarahbx** [kubernetes/website#36456]
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/controller-revision-v1/

> Note that, due to its use by both the DaemonSet and StatefulSet controllers for update and rollback, this object is beta. However, it may be subject to name and representation changes in future releases, and clients should not depend on its stability. It is primarily for internal use by controllers.

Considering this is `apps/v1` should this 'beta' note be updated/removed?

**Comment by sftim** [comment]
Here's where it's wrong:
https://github.com/kubernetes/kubernetes/blob/6e9845f766e4d34620835aaa1e5f864211471a50/staging/src/k8s.io/api/apps/v1/types.go#L897

Looks like that text was missed when the API was promoted to stable.
