### ISSUE TITLE
Unclear / misleading docs on attribution of memory that containers write to `emptyDir` volumes

### ISSUE THREAD

**Issue by winhvu** [kubernetes/website#36453]
According to documentation at https://kubernetes.io/docs/concepts/storage/volumes/#emptydir:

> Depending on your environment, emptyDir volumes are stored on whatever medium that backs the node such as disk or SSD, or network storage. However, if you set the emptyDir.medium field to "Memory", Kubernetes mounts a tmpfs (RAM-backed filesystem) for you instead. While tmpfs is very fast, be aware that unlike disks, tmpfs is cleared on node reboot and any files you write count against your container's memory limit.

With above statement, I understand that every data that is written to emptyDir should be counted to memory of container even after the container comes up from a restart if the data still remains in the emptyDir volume.

However, it does not happen that way on my environment.  The below info is extracted from pod describe printout:
```
Containers:
  fluentbit:
    Limits:
      cpu:     100m
      memory:  100Mi
    Requests:
      cpu:     50m
      memory:  50Mi
    Mounts:
      /logs from empty_dir_volume (rw)

Volumes:
  empty_dir_volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  200Gi
```

And the following is the info about the data stored on the container:

```bash
bash-4.4$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
104857600
bash-4.4$ 
bash-4.4$ 
bash-4.4$ 
bash-4.4$ ls -lh testme.log 
-rw-r--r-- 1 206099 10000 147M Aug 31 09:58 testme.log
bash-4.4$  
bash-4.4$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           2.3G  148M  2.2G   7% /logs
bash-4.4$ 
``` 
I see that when the data stored into the emptyDir reaches the container limit, the container gets restarted due to OOM. But when the container comes up from the restart, and those files are still there in the emtyDir volume, the size of those are not added into the container memory. 

As those files still remain in the emptyDir, I wonder who will own those files. It would be nice if you add more information regarding this matter to emptyDir volume section.

**Comment by sftim** [comment]
/language en

> any files you write count against your container's memory limit

I thought that was true, but maybe it's wrong. I wonder if the tmpfs is now charged against the Pod rather than a specific container?

**Comment by winhvu** [comment]
I might have done something wrong in my test. When monitoring memory of container using this watcher:
```
watch -n1 "kubectl top pod --container | grep fluentbit"
```
and on another terminal, repeatedly add a file with '5Mi' of logs into the emptyDir, I can observe the container memory is increased 5Mi after each adding; and when the memory is over the limit, I can see container restart due to OOMKilled.

That behavior seems to be aligned with the documentation. 

However, one point I need to highlight here is that the memory of the container is back to normal which does not count the size of the previous files to its memory even those files are available at the emptyDir (data on emptyDir is swiped out just in case pod gets restarted)

**Comment by sftim** [comment]
When a container exits and leaves data in a memory `emptyDir`, the Pod becomes the “owner” of that data.

**Comment by sftim** [comment]
Perhaps you'd like to edit the issue title and description @winhvu to frame this as a request to improve that page?

**Comment by winhvu** [comment]
> When a container exits and leaves data in a memory emptyDir, the Pod becomes the “owner” of that data.

@sftim The allocated resources, request and limit of memory/CPU, to Pod are determined at container level. So, I do not quite understand which memory will be affected (increased) by those files on the emptyDir when 'the Pod becomes the owner'.

**Comment by winhvu** [comment]
Thanks @sftim. I have updated the title as well as the ticket description. Please let me know if it is good to go or more changes is required.

**Comment by sftim** [comment]
/retitle Unclear / misleading docs on attribution of memory that containers write to `emptyDir` volumes

**Comment by sftim** [comment]
Hope that's useful to other folk.
/triage accepted
