### ISSUE TITLE
https://kubernetes.io/docs/concepts/workloads/pods/ implies Docker support

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36450]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/workloads/pods/ implies that Kubernetes has Docker Engine support. In fact, Docker Engine only works with Kubernetes if you either:
- connect Kubernetes to the containerd that makes Docker Engine work
- use an adapter such as `cri-dockerd`

**Proposed Solution:**
Pick an option:
1. Reword the sentence:
  > While Kubernetes supports more [container runtimes](https://kubernetes.io/docs/setup/production-environment/container-runtimes) than just [Docker](https://www.docker.com/), Docker is the most commonly known runtime, and it helps to describe Pods using some terminology from Docker.
2. Make a bigger revision to the concept page (check if there is already work under way)

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/

**Additional Information:**
/language en

**Comment by souravsk** [comment]
Hi @sftim is this work fine or if you like to add something
> It is important to note that Kubernetes supports more container runtimes than just Docker, but Docker is only supported when Kubernetes is connected to the containers that run the Docker engine or when an adapter such as CRI-docker is used.
