### ISSUE TITLE
Unclear information about `emptyDir` volumes and relation to memory resource usage in a container / Pod

### ISSUE THREAD

**Issue by thernstig** [kubernetes/website#36494]
# This is a Feature Request

There is no good information in the documentation of how an `emptyDir` volume, mounted into more than one container, is counted towards each container's resource usage.

#### What would you like to be added?

Proper information about how file content added to an `emptyDir`, that is mounted into multiple containers, is calculated towards the container(s) resource requests/limits. By trial and error we _believe_ the way Kubernetes handles this is that the actual container that **writes** the content gets its resource usage counters increased.

#### Why is this needed
Users need to know how to properly dimension resource usage if `emptyDir` volumes are mounted into several containers.

### Context

In our enviroment this is what we found ~out~ about whether the `emptyDir.medium` matters:

- `emptyDir.medium: Ephemeral`
  A container that keeps writing files to the `emptyDir` can go over it's own resource limit without stopping being able to write data. It is only when all aggregated container's limit is reached it stops.

- `emptyDir.medium: Memory`
  We found that the container that writes the data gets OOMKilled once it reaches only its own limit. i.e. there is no aggregation as in the `Ephemeral` case. 
  For `Memory` the docs states it counts towards the container memory limits. So according to docs it seems to not suggest it has to do container runtime or host OS kernel.

  https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
  > However, if you set the `emptyDir.medium` field to `"Memory"`, Kubernetes mounts a tmpfs (RAM-backed filesystem) for you instead. While tmpfs is very fast, be aware that unlike disks, tmpfs is cleared on node reboot and any files you write count against your container's memory limit.

The problem with the documentation here is that even though one might be able to deduct this somehow, we (several developers amongst us) find this unclear. It'd be good to somehow explain this and the difference between the two mediums and how they relate to container's resource limits.

####  Example (for a Deployment)

`volumes` are created on Pod-level.
`volumeMounts`, `resources.limits.memory`, `resources.requests.memory`, `resources.limits.ephemeral-storage` and `resources.requests.ephemeral-storage` are configured on container-level.

If one adds a volume of type `emptyDir` with a certain `sizeLimit` and mount it into two different containers in the same Pod, there is no mention on how Kubernetes exactly calculates the storage used in the `emptyDir` per container and their resource usage. Here are some concerns users could have:
- Is it the full `emptyDir.sizeLimit` that needs to be added to each container's resources?
- Or is it only to one of the container's resources the full `emptyDir.sizeLimit` counts?

### Comments
Related pages that might require an update:
- https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/
- https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

It is also assumed here that the resource calculation done here is the same no matter if `emptyDir.medium` is set to `Memory` 
or `Ephemeral` (just that it then counts against either memory or ephemeral limits).

/sig node
/language en

**Comment by sftim** [comment]
For `emptyDir` backed by local block devices, that's easy. The pod owns all the storage and the container-level requests and limits are added up to work out what limit to apply. Container-level limits aren't enforced. https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-emphemeralstorage-consumption has more details.

For `emptyDir` backed by memory, I think that the answer here is going to partly depend on the container runtime and the host OS kernel.
For a typical vanilla-Linux-and-containerd, the memory is owned by the most specific memory cgroup that contained the process that last wrote each specific page (or hugepage).

https://kubernetes.io/docs/reference/node/ feels like a good place to document things at this level of detail.
/sig node

**Comment by thernstig** [comment]
@sftim In our enviroment this is what we found:

`emptyDir.medium: Ephemeral`
We found what you wrote, and what is explained there. I.e. a container that keeps writing files to the `emptyDir` can go over it's own resource limit without stopping being able to write data. It is only when all aggregated container's limit is reached it stops. Is that also what you meant?

`emptyDir.medium: Memory`
We found that the container that writes the data gets OOMKilled once it reaches only its own limit. I.e. there is no aggregation as in the `Ephemeral` case. Is that also what you meant?

**Comment by thernstig** [comment]
https://github.com/kubernetes/website/issues/36453 is somewhat related here.

**Comment by sftim** [comment]
@thernstig would you be willing to edit the description (the big text box, not the one-line title) of this issue, in order to summarize the situation as you see it today?

**Comment by thernstig** [comment]
> @thernstig would you be willing to edit the description (the big text box, not the one-line title) of this issue, in order to summarize the situation as you see it today?

I'd have a hard time summarizing what to do here, maybe you can elaborate? I thought the issue was describe ok already but maybe it is not.

**Comment by sftim** [comment]
If you can incorporate what you wrote in  into the initial description, that'll help.

**Comment by thernstig** [comment]
> If you can incorporate what you wrote in [#36494 (comment)](https://github.com/kubernetes/website/issues/36494#issuecomment-1246613438) into the initial description, that'll help.

Done, but feel very free to edit to simplify!

**Comment by sftim** [comment]
Edited
/remove-lifecycle stale

**Comment by sftim** [comment]
/retitle Unclear information about `emptyDir` volumes and relation to memory resource usage in a container / Pod
