### ISSUE TITLE
in example, nslookup doesn't work when following example with Rancher Desktop

### ISSUE THREAD

**Issue by UlrichKnaack** [kubernetes/website#36495]
Hi,

I followed the steps on https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

when I try `kubectl run curl --image=radial/busyboxplus:curl -i --tty` and `nslookup my-nginx` , the output is:

```
Server:    10.43.0.10
Address 1: 10.43.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'my-nginx'
```

Output from `kubectl exec my-nginx-df7bbf6f5-bgsgn -- printenv | grep SERV` is   
```
MY_NGINX_SERVICE_HOST=10.43.78.245
KUBERNETES_SERVICE_HOST=10.43.0.1
KUBERNETES_SERVICE_PORT=443
MY_NGINX_SERVICE_PORT=80
KUBERNETES_SERVICE_PORT_HTTPS=443
```

This is executed correctly: `curl www.google.de` in the cluster.

I'm using Rancher Desktop 1.5.1 with Kubernetes 1.24.4 on macOS Monterey 12.5.1

**Comment by sftim** [comment]
This might be a bug in https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

/language en

**Comment by sftim** [comment]
/kind bug

Let's assume that it _is_ a bug.
/triage accepted

**Help wanted** (but not marking this /help because there might not be enough hints for a docs contributor to find a fix).

**Comment by yashodhanmohan** [comment]
@UlrichKnaack can you please provide the output of the command below when the nslookup is failing? Just dotting the i's.

```
kubectl describe svc my-nginx
```

**Comment by Kartik494** [comment]
Hi @UlrichKnaack i have test this on my environment and found that this running fine for me . Please find the output as 

```
kubectl run curl --image=radial/busyboxplus:curl -i --tty
If you don't see a command prompt, try pressing enter.
[ root@curl:/ ]$ nslookup my-nginx
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      my-nginx
Address 1: 10.108.8.100 my-nginx.default.svc.cluster.local
```
I have test this on k8s v1.26 .

**Comment by divya-mohan0209** [comment]
This works on the following versions of Rancher Desktop - v1.10, v1.11.1, and v1.12.2 and MacOS (Sonoma). 

Additionally, according to the N-2 policy, the active and maintenance support for Kubernetes v1.24 ended 8 and 6 months ago, respectively.

I've tried the tutorial out on the N-2 versions for Kubernetes, as well, i.e. v1.29, v1.28, and v1.27 and this tutorial works fine for those. 

We recommend you upgrade to one of the supported versions on Rancher Desktop and see if the problem persists. 

If it does, please consider reopening the issue.

/close
