### ISSUE TITLE
Unclear default value for KubeletConfiguration.cgroupDriver 

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/website#36492]
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration says the default value for `cgroupDriver` is `"cgroupfs"`.

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#configuring-the-kubelet-cgroup-driver says:

> Note: In v1.22, if the user is not setting the cgroupDriver field under KubeletConfiguration, kubeadm will default it to systemd.

The latter does not say, that prior to 1.23 (thus 1.22, 1.21, 1.20) the default was `systemd` and was later changed to `cgroupfs`.  It says, that in the nearly end-of-life 1.22 the default is `systemd`.

Later https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#using-the-cgroupfs-driver contains:

> Using the `cgroupfs` driver
> To use `cgroupfs` and to prevent `kubeadm upgrade` from modifying the KubeletConfiguration cgroup driver on existing setups, you must be explicit about its value. This applies to a case where you do not wish future versions of `kubeadm` to apply the `systemd` driver by default.

In the above text, it is nowhere stated, that there is a plan to switch the default value of KubeletConfiguration.cgroupDriver  from cgroupfs to systemd.

The last citation suggests, that `kubeadm upgrade` will perform implicit switch from `cgroupfs` to `systemd`.  This is strengthened by the fact about 1.22, where the implicit (default) value seems to be `systemd`.

All in all, the above information stipulates, that in 1.22 the default value was `systemd`, not it is `cgroupfs` and in the future `kubeadm upgrade` will use as implicit (default) value again `systemd`.  In the lack of discussion in the documentation why the defauls change back and forth, this does not make sense,

**Comment by dilyanpalauzov** [comment]
Ah, so the default cgroup driver for kubelet is cgroupfs, while for kubeadm the default is systemd.

This shall be spelled explicitly, as it is counter-intuitive.

My understanding so far is, that the systemd-driver supports kernel’s cgroup v2, while kubernetes’ cgroup-driver does not support kernel’s cgroup v2.  This shall also be spelled explicitly, as it is confusing.

**Comment by sftim** [comment]
It sounds like the thing to call out is that, in the kubeadm docs, we should explicitly say that the setting that kubeadm applies by default is an override to the built-in kubelet default.

Does that sound right?

**Comment by dilyanpalauzov** [comment]
> It sounds like the thing to call out is that, in the kubeadm docs, we should explicitly say that the setting that kubeadm applies by default is an override to the built-in kubelet default.
> 
> Does that sound right?

Yes.  Ideally kubeadm and kubelet shall explicitly state, that their default is distinct from the default of the other tool.
