### ISSUE TITLE
[ko] Translate content/en/docs/tasks/extend-kubernetes/http-proxy-access-api into Korean

### ISSUE THREAD

**Issue by Seo-yul** [kubernetes/website#36503]
This is a Feature Request

What would you like to be added
Translate content/en/docs/tasks/extend-kubernetes/http-proxy-access-api.md into Korean

◾ Page: https://kubernetes.io/docs/tasks/extend-kubernetes/http-proxy-access-api/
◾ File: https://github.com/kubernetes/website/blob/dev-1.24-ko.3/content/en/docs/tasks/extend-kubernetes/http-proxy-access-api.md

Why is this needed
Not translated yet

**Comment by jihoon-seo** [comment]
@Seo-yul 감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #36505
- #36804
- #36810

/close
