### ISSUE TITLE
Mention bug in StatefulSets and DaemonSets where pod count in status can be invalid

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#36527]
**Problem:**
When we apply the ResourceQuota(limit the number of pods) on the Namespace then the StatefulSet/DaemonSet which deploys in that namespace reports invalid status.
For example, if we will limit the no. of pods in a Namespace to 2. After that when we will deploy StatefulSet or DaemonSet in that Namespace, it will run only 2 pods but when we will the status of the StatefulSet or DaemonSet its shows only 1 pod.

Please refer to this issue in k/k for details: [#112010](https://github.com/kubernetes/kubernetes/issues/112010)

This problem is in before k8s version v1.25. In v1.25, the problem for StatefulSet is resolved([#109694](https://github.com/kubernetes/kubernetes/pull/109694)) and For DaemonSet the pr is opened([#112127](https://github.com/kubernetes/kubernetes/pull/112127)) in k8sv1.26 and it is in a review state.

While discussing to backport this issue in the previous version of k8s  like v1.23 and v1.24, As per this [comment](https://github.com/kubernetes/kubernetes/issues/112010#issuecomment-1233262172)it came out like it is not a critical bug and we can only backport critical bug fixes.

**What would you like to be added:**
Can we add this as a limitation for StatefulSet and DaemonSet in k8s docs so that users will know about it like in which k8s version it will not work?
If yes, which is the best place to mention it in the docs?, as per the [comment](https://github.com/kubernetes/kubernetes/issues/112010#issuecomment-1234274074) it should be somewhere in https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/
The reference docs are automatically generated from the code comments. where does it seem good to write this?
**Why is this needed:**
It is useful for the end users, this limitation will make it difficult for users to debug if they applied ResourceQuota to their namespace in previous versions (before v1.25 for both sts and ds. and In v1.25 for ds).

**Comment by Shubham82** [comment]
maybe
/kind feature

**Comment by Shubham82** [comment]
/sig docs

PTAL!

**Comment by sftim** [comment]
/retitle Mention now-fixed bug in StatefulSets and DaemonSets where pod count in status can be invalid

**Comment by sftim** [comment]
/priority awaiting-more-evidence

I'd like to see some :+1: reactions on the issue before accepting this work.

**Comment by sftim** [comment]
Actually, the DaemonSet bug isn't fixed.
/retitle Mention bug in StatefulSets and DaemonSets where pod count in status can be invalid

**Comment by sftim** [comment]
Maybe the release notes are the right place to mention the bug?

**Comment by Shubham82** [comment]
I raised this concern on the slack channel(sig-app), There is a discussion going on it here is the link for it:
https://kubernetes.slack.com/archives/C18NZM5K9/p1663157430112409

**Comment by Shubham82** [comment]
so I am closing this as this issue is backported.
