### ISSUE TITLE
Document YAML compatibility bug

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36526]
**This is a Feature Request**

**What would you like to be added**
https://github.com/kubernetes/kubernetes/issues/34146 describes a bug in Kubernetes where YAML 1.2 documents are not parsed (Kubernetes does not have good support for YAML 1.1), but then also Kubernetes does incorrectly parse completely valid YAML 1.1 the way that the specification defines.

**Why is this needed**
The bug makes it hard for some people, using conformant libraries, to make YAML documents that Kubernetes accepts.
We should document the bug so that readers are aware of the shortcomings here.

**Comments**
/wg api-expression
/language en
/priority backlog

**Comment by souravsk** [comment]
@mehabhalodiya i can help you because I'm new to it so if i can tag along i will be able to learn a lot

**Comment by mrgiles** [comment]
@sftim would you add this as a warning note in [Objects In Kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/)?
