### ISSUE TITLE
Set up a High Availability etcd Cluster with kubeadm mentions testing with Docker

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36533]
**This is a Bug Report**

**Problem:**
[Set up a High Availability etcd Cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) mentions that you can check the static Pods by running a `docker` command.
This is unlikely - Kubernetes doesn't support Docker Engine natively any more.

**Proposed Solution:**
Remove the mention of `docker`; either omit that section, or provide some options for common container runtimes with CRI compatibility. 

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

**Additional Information:**
/sig cluster-lifecycle
/language en

**Comment by neolit123** [comment]
> Remove the mention of docker; either omit that section, or provide some options for common container runtimes with CRI compatibility.

+1, prs welcome.

/help

**Comment by sftim** [comment]
Either of the 2 approaches is fine.

If you're someone picking this up and you choose to list several container runtimes, have a look at https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content and https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#third-party-content-marker for advice on how to handle this.

**Comment by mehabhalodiya** [comment]
@sachinparihar I don't see any PR raised against this issue, so unassigning you for others to pick up.
If you are still interested then assign it again 🙂 
Thanks!

/unassign @sachinparihar
