### ISSUE TITLE
Kubernetes 1.11: In-Cluster Load Balancing and CoreDNS Plugin Graduate to General Availability

### ISSUE THREAD

**Issue by drohnow** [kubernetes/website#36537]
Per the release notes, IPVS is not yet the default when is went GA in release 1.11.  Can you tell me when IPVS replaced IPTables as default proxy mode?

**Comment by utkarsh-singh1** [comment]
Hi @drohnow, can you provide a link to the release page?

**Comment by reylejano** [comment]
iptables is still default as of 1.25
From https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/
/close


> --proxy-mode ProxyMode
> --
>  Which  proxy mode to use: 'iptables' (Linux-only), 'ipvs' (Linux-only),  'kernelspace' (Windows-only), or 'userspace' (Linux/Windows,  deprecated). The default value is 'iptables' on Linux and 'userspace' on  Windows(will be 'kernelspace' in a future release).This parameter is  ignored if a config file is specified by --config.
> 

/close
