### ISSUE TITLE
[zh] localize PodSecurityPolicy-Past-Present-and-Future.md

### ISSUE THREAD

**Issue by Michelle951** [kubernetes/website#36549]
localized [podsecuritypolicy-deprecation-past-present-and-future](https://kubernetes.io//blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) to Chinese

**Comment by ydFu** [comment]
This issue is solved(https://github.com/kubernetes/website/pull/36545)
LGMT

/close

**Comment by Michelle951** [comment]
> 
This file hasn't been localized. That pr (https://github.com/kubernetes/website/pull/36545) just synced another file and mentioned to localize this file.
