### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/quality-service-pod/

### ISSUE THREAD

**Issue by frsh-augustin** [kubernetes/website#36540]
Hi Team，
In this document, it is mentioned at the begining `Kubernetes uses QoS classes to make decisions about scheduling and evicting Pods.`

But I don't see any descriptions that explains the behavior of the QoS classes when the pod is scheduled and evicted. Can you please improve this document and elaborate?
- Guaranteed
- Burstable
- BestEffort

I see some documents like https://bytes.devopscube.com/p/kubernetes-pod-quality-of-servive, but it is not official document, is it trustable?

**Comment by utkarsh-singh1** [comment]
Hi @frsh-augustin, can you specify what do you want to add in Gauranteed, Burstable and Best Effort ?

/language en

**Comment by frsh-augustin** [comment]
@utkarsh-singh1 It is appreicated if the following points are elaborated in the document
1. When pod is scheduled to the node, what is behavior of pods with different QoS pods? For example, if node resources is not enough to schedle a `Gauranteed` pod, does `Best Effort` pod get killed to spare the node resources?
2. If the node runs out of resources, what happen to the running pods with different QoS class?

**Comment by tengqm** [comment]
/triage accepted
/remove-lifecycle rotten

I believe some clarification would be helpful.
