### ISSUE TITLE
Typo on Guide for scheduling Windows containers in Kubernetes page

### ISSUE THREAD

**Issue by UtkarshMishra12** [kubernetes/website#36554]
The spelling of the **functionality** i.e funcationality is wrong, I'm attaching the screenshot for the same.
May I open a new PR correcting the spelling?
![Typo](https://user-images.githubusercontent.com/67385503/188266290-7efc4676-76a7-402d-bdd8-3b75ecda0c4b.png)

**Comment by utkarsh-singh1** [comment]
Hi @UtkarshMishra12, you can raise a PR for that but also make sure to check for other errors on that same doc, also you can provide a link to that error instead of attaching a screenshot.

/language en

**Comment by UtkarshMishra12** [comment]
Hey @utkarsh-singh1  I was working on this issue but @akankshakumari393  has made a PR, I have given a lot of o time to finding the bug and she has raised a PR, Is it not wrong?

**Comment by akankshakumari393** [comment]
Hey @UtkarshMishra12 I did not check the comments here, you can Raise a PR if you want. I can close it. The issue was clear from the PR description. Let me know if you want me to close it. It wasn't assigned to anyone.

**Comment by UtkarshMishra12** [comment]
Hey @akankshakumari393 Yes please close your PR, I had given time to find the bug. I'll be grateful to you.

**Comment by utkarsh-singh1** [comment]
Hi @akankshakumari393, thanks for your response you can review the previous comments made on any issues and check if there is someone who already mentioned that they want to work on it and if you want to work on it you can ask the author of the issue.

**Comment by akankshakumari393** [comment]
Yeah sure, I will close the PR. Not an issue. Thanks!!
