### ISSUE TITLE
[Umbrella issue] adopt new localization strings for releases page

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#36568]
Now that https://github.com/kubernetes/website/issues/35932 is complete, I must take the follow up actions mentioned in [these comments](https://github.com/kubernetes/website/issues/35932#issuecomment-1230406887).

**Comment by rolfedh** [comment]
When those follow-up actions are complete, all localizations will display "Complete 1.25 Schedule and Changelog" in their releases page in their local language:
![image](https://user-images.githubusercontent.com/350907/188285494-acb9c88c-b42e-4423-b817-86395abc1f22.png)

**Comment by sftim** [comment]
/retitle [Umbrella issue] adopt new localization strings for releases page
/area localization

**Comment by rolfedh** [comment]
I have completed all the steps required for this task. Only the follow-up tasks I created, which are assigned to others, remain to be completed.
