### ISSUE TITLE
Restore links to API reference Resources docs

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#3656]
@pwittrock reported people still use `resources-reference` instead of `api-reference` sometimes because that's basically a web UI for `kubectl explain` and makes object model more available to write YAML manifests (not to mention, it has manifest samples too).

We should probably restore links to these pages (https://kubernetes.io/docs/resources-reference/v1.6/)

**Comment by jaredbhatti** [comment]
You mean "restore links from k8s.io pages to the 1.6 reference"?

**Comment by tengqm** [comment]
@ahmetb   is this still an issue?

**Comment by ahmetb** [comment]
It is.
