### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by yugesh-github** [kubernetes/website#36572]
What is the command to view / go inside namespace?

**Comment by mk46** [comment]
/kind support

**To view all namespace**

```shell
kubectl get namespace
```
See https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#viewing-namespaces

**For switching  namespace**
```shell
kubectl config set-context --current --namespace=<namespace in which you want to switch>
```
See https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#setting-the-namespace-preference
