### ISSUE TITLE
No link anchor to Cluster Diagram (Issue with /docs/tutorials/kubernetes-basics/cluster-intro/)

### ISSUE THREAD

**Issue by techtonik** [kubernetes/website#3658]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I can't give a link to Cluster Diagram, because no <a name or id is generated for h2 header.

**Proposed Solution:**
Generate anchors for subsections.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/

**Comment by jaredbhatti** [comment]
More of a feature request.  Our standard pages have anchors, but the interactive tutorial pages don't since they were written by a third party.

**Comment by techtonik** [comment]
Changed to feature request.
