### ISSUE TITLE
Suggestions for “Interactive Tutorial - Deploying an App”

### ISSUE THREAD

**Issue by Sunilgknair** [kubernetes/website#36627]
I think the tutorial is great but, as an amateur with Kubernetes, the page with the Module 2 must be improved. Can the commands be copied correctly to the attached terminal? What do the commands do? Can we split the commands so that it is easier to follow?
Can we perform the actions on the same tab, if not why?

Some of my doubts and I need a bit more clarity on this module but I hope I have been logical enough.

**Comment by sftim** [comment]
/retitle Suggestions for “Interactive Tutorial - Deploying an App”
