### ISSUE TITLE
[ko] add `finalizer` to Korean localization glossary

### ISSUE THREAD

**Issue by KimDoubleB** [kubernetes/website#36622]
**This is a Feature Request**

**What would you like to be added**

add `finalizer` translation to Korean localization glossary (한글화 용어집 `docs/contribute/localization_ko.md`).
- `finalizer` -> `파이널라이저(finalizer)`

**Why is this needed**

Currently, there is no 'finalizer' in Korean localization glossary.
To help with translation as this word is used a lot in other documents.

**Comments**

/language ko
/assign

**Comment by jihoon-seo** [comment]
@KimDoubleB 감사합니다!
최근 많은 기여가 이루어졌는데, 이 과정에서 발굴된 등록하면 좋을 다른 용어가 있다면, 함께 등록하는 것도 좋을 것 같습니다. 😊

Link: https://kubernetes.io/ko/docs/contribute/localization_ko/#한글화-용어집
/triage accepted

**Comment by KimDoubleB** [comment]
@jihoon-seo 
넵, 그러면 해당 이슈에 대한 PR로 다른 용어들도 같이 추가해보도록 하겠습니다 :)
