### ISSUE TITLE
Volume expansion incorrectly marked as beta

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36628]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims states that volume expansion is beta; however, the article at https://kubernetes.io/blog/2022/05/05/volume-expansion-ga/ says that the feature graduated to stable as part of Kubernetes v1.24

**Proposed Solution:**
Change the feature-state shortcode there to mark the feature as stable since v1.24

**Page to Update:**

https://kubernetes.io/docs/concepts/storage/persistent-volumes/

/language en

**Comment by rishavnandi** [comment]
Hi, I'd like to take this issue up and give it a try, sending a PR shortly : )

**Comment by sftim** [comment]
@bandya2003, if you didn't liaise with @rishavnandi please do.

_Anyone_ is welcome to send in a PR to fix an issue. We do favor folks co-ordinating work and I want to emphasize our “no cookie licking” policy (see https://github.com/kubernetes/website/issues/33848#issuecomment-1134575413 in what actually turned into a too heated conversation for more explanation).

**Comment by bandya2003** [comment]
@sftim 🙌sorry, will remember it next time

**Comment by mk46** [comment]
Addressed in https://github.com/kubernetes/website/pull/36638
/close
