### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/scale-interactive/

### ISSUE THREAD

**Issue by sergebug** [kubernetes/website#3664]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Step 2 of module 5 uses pre-existing service

kubectl describe services/kubernetes-bootcamp

This service is deleted during the module 4 therefore it's not possible to get the command above  produce valid result locally

**Proposed Solution:**

Do not create service in advance and include create service command in the exercise prior to the node scaling.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/scale-interactive/

**Comment by jaredbhatti** [comment]
The interactive tutorial was built by a third party, so I'll reach out to them.

**Comment by BenHall** [comment]
Thanks for your feedback on this. We've updated this as you suggested.

/close
