### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/configmap/

### ISSUE THREAD

**Issue by JustinRainwater** [kubernetes/website#36650]
> ```
>   volumes:
>     # You set volumes at the Pod level, then mount them into containers inside that Pod
>     - name: config
> ```

indenting is wrong on `- name`

**Comment by sftim** [comment]
We can, and should, update the example that appears after 
> Here's an example Pod that uses values from `game-demo` to configure a Pod:

We can make this use the `codenew` shortcode - see [Including code from another file](https://kubernetes.io/docs/contribute/style/write-new-topic/#including-code-from-another-file)

Whenever we give examples that the reader could try out by running them, we should prefer using `codenew` shortcodes.

**Comment by sftim** [comment]
/language en
/triage accepted

I recommend switching it to a `codenew` shortcode per https://github.com/kubernetes/website/issues/36650#issuecomment-1239317194

**Comment by sftim** [comment]
I'm not sure that there's anything actually _wrong_ with the `.spec` of that Pod, though.

/kind cleanup

**Comment by JustinRainwater** [comment]
Pasting that snippet into my own code gave me errors and it took me some time to figure out that it was due to the copied code being incorrect.

**Comment by sftim** [comment]
@JustinRainwater would you be willing to provide a diff for that manifest that shows the fix? It'd help.
