### ISSUE TITLE
Replace images on KMSv2 blog article with SVG vector versions

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36654]
**Problem:**
On the day of publication, https://k8s.io/blog/2022/09/09/kms-v2-improvements/ will use Mermaid images that load from an external source. This is OK for now but I'm concerned that the Mermaid service may not be as long-lived as this blog.

We should replace those images with content that we host ourselves.

**Proposed Solution:**
- Use Mermaid to generate SVG images for the figures in https://k8s.io/blog/2022/09/09/kms-v2-improvements/
- In the Markdown source for that article, replace the existing images with [`figure`](https://gohugo.io/content-management/shortcodes/#figure) shortcodes that reference those SVG images.

As a side effect, the image rendering will be much more crisp on high-DPI devices.

**Page to Update:**
https://k8s.io/blog/2022/09/09/kms-v2-improvements/ (live from 2022-09-09)

/area blog
/language en
/kind cleanup

**Comment by sftim** [comment]
This would be a fixup for PR #35675

**Comment by prsndp** [comment]
Hi @mtardy , could i take issue ? I would like to contribute to it.

**Comment by mtardy** [comment]
Yes, feel free!

/assign prsndp

**Comment by sftim** [comment]
Folks are welcome to work on this issue. @prsndp would you like any assistance?

**Comment by prsndp** [comment]
> Folks are welcome to work on this issue. @prsndp would you like any assistance?

### No thanks, I am on it, will give you update soon.

**Comment by sftim** [comment]
/close

Fixed in #36981 
Thanks @prsndp
