### ISSUE TITLE
[ko] Translate docs/tasks/configure-pod-container/configure-projected-volume-storage into Korean

### ISSUE THREAD

**Issue by WESTZERO115** [kubernetes/website#36666]
**This is a Feature Request**

**What would you like to be added**
Translate docs/tasks/configure-pod-container/configure-projected-volume-storage into Korean

**Why is this needed**
Not translated into Korean.

**Comments**
link : https://kubernetes.io/docs/tasks/configure-pod-container/configure-projected-volume-storage/

/language ko
/assign

**Comment by jihoon-seo** [comment]
@WESTZERO115 감사합니다!
/triage accepted
