### ISSUE TITLE
Concepts / Overview image suggestion

### ISSUE THREAD

**Issue by mercarey** [kubernetes/website#36664]
**This is a Feature Request**

**What would you like to be added**
In the historical context of the Overview page, the image represents the progression from legacy to containerized deployment models, showing the progression of utility in deployment methodologies. The "Traditional Deployment" image however could emphasize more the inefficiency of the legacy method; the text touched upon this: "_A solution for this would be to run each application on a different physical server. But this did not scale as resources were underutilized, and it was expensive for organizations to maintain many physical servers._"

The attached file is a mockup (not SVG) of an image that depicts the redundancy and inefficiency of legacy deployments.

![container_evolution](https://user-images.githubusercontent.com/110875472/188936554-e718ad06-daf7-48ee-860b-7d32cc208f6e.png)

**Why is this needed**
It isn't a must have, but a suggestion.

**Comments**

**Comment by sftim** [comment]
I wonder if we could explain the benefits of containers in general in a blog article that we mark as evergreen, and then we could use both the current (multiple apps, one server) and proposed (multiple servers, limited bin packing, more toil) versions of the physical servers architecture.

_Plus_, we can show that a Kubernetes cluster actually has multiple nodes, each typically running multiple containers.

For https://kubernetes.io/docs/concepts/overview/, I'd definitely want to keep _some_ diagram. Maybe it could show the progress of a containerised app from a developer (laptop) to multiple replicas in a production cluster - and, of course, link to that blog article I've suggested.

What do folks think? I could probably write that blog article, too.

**Comment by mercarey** [comment]
Your proposed "benefits of containers" is segued to at the end of the the "Container Deployment Era" subsection, i.e., _Containers have become popular because they provide extra benefits, such as:..._ ," so you may be onto something in your thematic chunking of the deployment evolution and (thereby) benefits of containerization.

Possible (spaghetti on wall) draft titles
- Containers: Where did they come from and why are they useful?
- A Brief History of (and Benefits to) Containerization
- Containers: How I Learned to stop Underutilizing Servers and Decouple Infrastructure

That blog post could cannibalize and retrofit the entire **Going Back in Time** section from the Overview, and in doing so strengthen the overview by significantly reducing its length and thus making it more fit as an Overview (i.e., a [short description](https://dictionary.cambridge.org/dictionary/english/overview)).

The Overview can then have its introduction and proceed directly to "Why you need Kubernetes..." and link to the blog in such fashion (or otherwise):
_Containers are a good way to bundle and run your applications -- [that's why they came about in the first place](link-to-evergreen).  In a production environment, you need to..._

The relocation of this content does not detract from the effectiveness of the overview page, since there are still apophatic "What Kubernetes is not" and cataphatic "What [Kubernetes] can do" elements that exhaustively provide the titular overview of what the platform is, precisely.

**Comment by sftim** [comment]
/remove-lifecycle rotten

If this rots again, let's close it as not staffed.
