### ISSUE TITLE
[ko] Translate concepts/workloads/pods/user-namespaces.md into Korean

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#36687]
**This is a Feature Request**

**What would you like to be added**

Translate `docs/concepts/workloads/pods/user-namespaces.md` into Korean.

- Page: https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/
- File: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/pods/user-namespaces.md

**Why is this needed**
Has not been translated into Korean yet.

**Comments**

/assign
/language ko

**Comment by jihoon-seo** [comment]
@kyungjin99 감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #36998
- #38192

Thanks!
/close
