### ISSUE TITLE
[ko] update contributor guide for Korean localization

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/website#36688]
**This is a Feature Request**

**What would you like to be added**
Update on how [reviewers in document](https://kubernetes.io/ko/docs/contribute/localization_ko/#%EB%A6%AC%EB%B7%B0%EC%96%B4-%EC%82%AD%EC%A0%9C) is handled.

**Why is this needed**
Dicussed in [#35423](https://github.com/kubernetes/website/pull/35423)

/language ko
/assign

**Comment by jihoon-seo** [comment]
@bconfiden2 감사합니다!
/triage accepted

**Comment by bconfiden2** [comment]
Already been processed in #36800 :sweat_smile: :sweat_smile:
