### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/

### ISSUE THREAD

**Issue by flickerfly** [kubernetes/website#36717]
It would be handy if near the top somewhere the version of kubernetes this started being supported in was called out and on the V1 version if the version that it was deprecated on was called out. This would make it easier to research what my scenario is in supporting various kubernetes versions as I choose the apiVersion.

**Comment by flickerfly** [comment]
https://i0.wp.com/andymcphee.com/wp-content/uploads/2020/08/notdeadyet-2.jpg

**Comment by sftim** [comment]
/remove-kind support

Seems like reasonable feedback.

**Comment by sftim** [comment]
This isn't particularly easy to add. It's reasonable feedback though.
Given that we'd need to put extra effort in (a mechanism to combine autogenerated API reference details with manually maintained text), it'd be good to make sure we think it's worth it.

/priority awaiting-more-evidence
