### ISSUE TITLE
Broken Link in Versions in CustomResourceDefinitions Page

### ISSUE THREAD

**Issue by akankshakumari393** [kubernetes/website#36715]
The link to CustomResourceDefinitions is broken. Rather it should point to  [CustomResourceDefinitions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#customresourcedefinition-v1-apiextensions-k8s-io)

> This page explains how to add versioning information to [CustomResourceDefinitions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#customresourcedefinition-v1beta1-apiextensions),

**Comment by sftim** [comment]
The link should actually be to https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/

(at least, that's where I recommend linking to)

/kind bug
/language en

**Comment by akankshakumari393** [comment]
cool, I will update the PR with [https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/)
