### ISSUE TITLE
Broken link need to fix 

### ISSUE THREAD

**Issue by amolmote** [kubernetes/website#36713]
**This is a Bug Report**

**Problem:**
visit this page [pull-requests](https://www.kubernetes.dev/docs/guide/pull-requests/)
when we click on this `Kubernetes Enhancement Proposal process` it returns 404 not found page,so this needs to be fix.

**Proposed Solution:**
correct link of md file require to provide.

**Page to Update:**
https://www.kubernetes.dev/docs/guide/pull-requests/

/language en
/assign

**Comment by akankshakumari393** [comment]
Hey @amolmote Can I work on this issue, If you are not already.
