### ISSUE TITLE
Need to fix the broken and Incomplete sentence structure in `blog-post.md`

### ISSUE THREAD

**Issue by amolmote** [kubernetes/website#36711]
Problem Description
visit this page [blog-post.md](https://github.com/kubernetes/website/blob/main/archetypes/blog-post.md) I have found the following issues need to  fix.

-  Unclickable slack workplace channel link, you can check by clicking on this highlighed sentence `The name of a channel on Slack, #a-channel`

-  second last line and last line is incomplete. like inside [] bracket text is missing it should be like this  `[github-id]` and  `design and development of project` to make the  sentence complete.

**Comment by shivaabhishek07** [comment]
I am interested in  making changes, Can anyone assign me.

**Comment by amolmote** [comment]
@shivaabhishek07, I am already working on this issue.

**Comment by amolmote** [comment]
by the way, this issue is waiting for triage acceptance, If you need any help please join the slack channel i will help you their
for your contribution as well

**Comment by shivaabhishek07** [comment]
> @shivaabhishek07, I am already working on this issue.

Ok

**Comment by reylejano** [comment]
[blog-post.md](https://github.com/kubernetes/website/blob/main/archetypes/blog-post.md) is an archetype not an actual page. 
It is like an example and does not have actual content
/close
