### ISSUE TITLE
[ko]Translate tasks/job/pod-failure-policy into Korean

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/website#36719]
This is a Feature Request

What would you like to be added

Translate "tasks/job/pod-failure-policy" into Korean.

Why is this needed

Not translated into Korean yet.

Comments

https://kubernetes.io/docs/tasks/job/pod-failure-policy/

/language ko
/assign

**Comment by jihoon-seo** [comment]
@Kid-Chang 감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
@Kid-Chang 님 안녕하세요~~
잘 지내고 계신가요.. ㅎㅎ
혹시 https://kubernetes.io/docs/tasks/job/pod-failure-policy/ 페이지에 대해 아직 작업 시작 전이시면,
이 이슈를 #40973 로 이관해도 괜찮을까요? ㅎㅎ

**Comment by Kid-Chang** [comment]
@jihoon-seo  네 이관 부탁드립니다..! issue open후 기여하지 못하여 죄송합니다..ㅠ
