### ISSUE TITLE
Need to update the `code-contributor.yaml`

### ISSUE THREAD

**Issue by amolmote** [kubernetes/website#36721]
Issue I have observed with `code-contributor.yaml`
Issue in the [code-contributor.yaml](https://github.com/kubernetes/website/blob/main/data/user-personas/contributors/code-contributor.yaml) is that the `lable: Learn about the Kubernetes Enhancement Proposal (KEP) process` it has broken url.
So we need to update it with the right url of KEP.

/language en
/assign

**Comment by amolmote** [comment]
@sftim, please accept the triage, I want to open pr for this issue

**Comment by mtardy** [comment]
Seems reasonable since the link is broken. I failed to find, do you have any examples of where this data is used? Where did you find out that this link was broken?

/triage accepted
/broken-link
/kind bug

**Comment by amolmote** [comment]
Here is it solution I have already opened pr in community repo
https://github.com/kubernetes/community/pull/6870
Can I open the pr for this as well

**Comment by mtardy** [comment]
> Here is it solution I have already opened pr in community repo [kubernetes/community#6870](https://github.com/kubernetes/community/pull/6870) Can I open the pr for this as well

I think you already did here https://github.com/kubernetes/website/pull/36735 no?

But, for understanding how this data is used, do you have any examples or you just searched for the broken URL in the repo?

**Comment by amolmote** [comment]
Actually I am reading the open pr process that time i got this issue and when I have come around this yml by reading the KEP process I thought that this also be a broken link
