### ISSUE TITLE
Pod Topology Spread Constraints: diagrams not showing

### ISSUE THREAD

**Issue by anthonyvdotbe** [kubernetes/website#36725]
The page https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
shows an error image saying:
> Syntax error in graph
> mermaid version 8.13.4

where it's supposed to show diagrams.

**Comment by mtardy** [comment]
I think this is related to [Mermaid diagrams are broken (replicable with Firefox) #31960](https://github.com/kubernetes/website/issues/31960). I suppose you were using Firefox?
You can continue the discussion on the other issue, I'll mark it as a duplicate for now and close if you are okay.

/triage duplicate

**Comment by anthonyvdotbe** [comment]
Thanks for pointing out the duplication, I was using Firefox indeed.
