### ISSUE TITLE
[ko]Translate /tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors into Korean

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/website#36720]
This is a Feature Request

What would you like to be added

Translate "tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors" into Korean.

Why is this needed

Not translated into Korean yet.

Comments

https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors/

/language ko
/assign

**Comment by jihoon-seo** [comment]
@Kid-Chang 감사합니다!
/triage accepted
