### ISSUE TITLE
Update Getting Started documentation for ARM

### ISSUE THREAD

**Issue by samkass** [kubernetes/website#36732]
**This is a Feature Request**

**What would you like to be added**

I decided to try to learn a bit of Kubernetes on my new M1 Mac. It all worked except for the `kubectl create deployment hello-node --image=registry.k8s.io/echoserver:1.4` command, as that image does not support ARM. A bit of Googling and a visit to StackOverflow fixed it for me, but it would be better if that information was in the core guide. For others following in my footsteps, I have created a pull request with the ARM image info.

**Why is this needed**

ARM-based devices are becoming increasingly popular dev platforms, especially for early prototyping and learning. A Getting Started guide that worked on these hosts would be preferable to one which doesn't.

**Comments**

I will link this Issue to my pull request. I realize the version number, not just the repo and name, are different from the existing image. However, being on an ARM device, I have no way of testing the original image, so I didn't change it.

**Comment by mtardy** [comment]
> ARM-based devices are becoming increasingly popular dev platforms, especially for early prototyping and learning. A Getting Started guide that worked on these hosts would be preferable to one which doesn't.

I agree, it would be nice that the "getting started" guide is working on both platforms or at least propose an alternative image for ARM.

Feel free to link this issue from the PR you made and thanks for taking the time!

/triage accepted
/priority backlog
/language en

**Comment by samkass** [comment]
Oops, I had a typo in the pull request link. Linked.
