### ISSUE TITLE
[ko]Translate /tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd into Korean

### ISSUE THREAD

**Issue by tonyhan18** [kubernetes/website#36745]
**This is a Feature Request**

**What would you like to be added**

Translate "/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd" into Korean.

**Why is this needed**

Not translated into Korean yet.

**Comments**

https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd/

/language ko
/assign

**Comment by jihoon-seo** [comment]
@tonyhan18 안녕하세요 이슈 올려 주셔서 감사합니다!
그런데 이미 동일 페이지 작업에 대한 이슈가 올라와 있습니다. ㅠㅠ
확인 부탁드려요~~
/triage duplicate
