### ISSUE TITLE
Reorganize horizontal space partitions for desktop / tablet view

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/website#36756]
**This is a Feature Request**

**What would you like to be added**
Remove unnecessary margins on the each posting and make website visually better.

**Why is this needed**
If the screen size is small, unnecessary margin stands out on the page like below:
![d](https://user-images.githubusercontent.com/58922834/189681914-16e952f5-56f1-4b43-a1bd-650000bfde50.PNG)

When the depth of the left sidebar deepens, this margin makes the sidebar very narrow and ugly.
How about removing the margins and increasing the sidebar?

**Comment by seokho-son** [comment]
@bconfiden2 
I think we need to check unnecessary margins and remove them if possible.
Thank you for sharing this issue.

**Comment by seokho-son** [comment]
@bconfiden2 
Do you have a plan to check unnecessary margins and update configurations ?
If you can initiate please feel free to assign this issue to yourself. (you don't have to fix all problems and we can cooperate)

**Comment by seokho-son** [comment]
![image](https://user-images.githubusercontent.com/5966944/189684170-0c47e1eb-1a23-424b-b81e-fbf18636d6c5.png)

**Comment by seokho-son** [comment]
In case of Korean,

![image](https://user-images.githubusercontent.com/5966944/189685001-d47226a3-8c66-41cc-9f61-cf665623ac20.png)

**Comment by seokho-son** [comment]
In case of Chinese,

![image](https://user-images.githubusercontent.com/5966944/189685464-5da6855b-1a1c-44fe-8665-d9d8e025d3d8.png)

**Comment by sftim** [comment]
The “margin” here is a style choice to make the text paragraphs easier to read. When paragraphs are very long, it is difficult to read them at speed. Research on this is [inconclusive](https://designregression.com/article/line-length-revisited-following-the-research); however, the current design is as intended and is not a bug.

**Comment by bconfiden2** [comment]
Oh I understood, thanks @sftim !!

**Comment by seokho-son** [comment]
Hi @sftim 
Thank you for sharing design intention for the margin :)

I think more major issue here is about Items in the sidebar tree.
The items (in 3rd level) are very hard to recognize in some situations according to device resolutions, browser page size, browser font size, ...

**Comment by seokho-son** [comment]
Can we increase the width for sidebar tree ?

**Comment by sftim** [comment]
Could we retitle this to, eg, “Reorganize horizontal space partitions for desktop / tablet view” ?

**Comment by bconfiden2** [comment]
Should I reduce the size of the existing space paritions a little and increase the width of the sidebar by that much?
