### ISSUE TITLE
Translate /reference/node/kubelet-checkpoint-api in Korean

### ISSUE THREAD

**Issue by marcushyungseoklee** [kubernetes/website#36770]
**This is a Feature Request**

**What would you like to be added**

Translate /reference/node/kubelet-checkpoint-api in Korean

**Why is this needed**

Not yet translated in Korean

**Comments**

https://kubernetes.io/docs/reference/node/kubelet-checkpoint-api/

**Comment by marcushyungseoklee** [comment]
신규 브랜치 dev-1.25-ko.1에서 진행 예정

**Comment by jihoon-seo** [comment]
@marcushyungseoklee 감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
@marcushyungseoklee 님 안녕하세요~~
잘 지내고 계신가요 ㅎㅎ

@Virusuki 님께서 동일 페이지에 대한 이슈를 올리셨는데.. (#40900)
혹시 @marcushyungseoklee 님께서 작업 시작 전이시고 현재 작업 여력이 마땅치 않으신 경우
Assignee 조정을 해도 괜찮을까요? ㅎㅎ

**Comment by marcushyungseoklee** [comment]
@jihoon-seo 안녕하세요^^ 오랜만입니다 ㅜㅜ 제가 현재 여력이 힘들어서..조정해주셔도 될것 같습니다.

**Comment by jihoon-seo** [comment]
@marcushyungseoklee 바쁘시군요... ㅎㅎㅎ 저도 그렇고 다들 바쁘신 것 같습니다.. ㅎㅎㅎ
바쁘신 와중에도 항상 관심 가져 주시고 기여해 주셔서 감사합니다.. ㅎㅎ
그러면 이번 건은 @Virusuki 님께 요청을 드리겠습니다. ㅎㅎ

/unassign @marcushyungseoklee

/assign @Virusuki
(↑ 이 명령은 안 될 수도.. ㅎㅎ)

**Comment by jihoon-seo** [comment]
#40900 를 남기고, 이 이슈는 close 하겠습니다~~
/close
