### ISSUE TITLE
Broken link in glossary entry code-contributor

### ISSUE THREAD

**Issue by mtardy** [kubernetes/website#36773]
**This is a Bug Report**

**Problem:**

The full link of this glossary entry is broken: https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/code-contributor.md, the link https://kubernetes.io/docs/community/devel/ leads to nowhere.

It's an issue when you click on "Code Contributor" in another entry and it redirects to that broken link, like here https://kubernetes.io/docs/reference/glossary/?all=true#term-developer.

**Proposed Solution:**

1. Remove that link completely
2. Point to other resources like https://github.com/kubernetes/community/tree/master/contributors/devel

**Comment by Shubham82** [comment]
Hi @mtardy
I checked this if we remove the `/docs/community/devel/`  which mention under `full_link:` from [code-contributor.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/code-contributor.md) then then `Code Contributor` under `Developer (disambiguation)` will redirects to `kubernetes.io/docs/reference/glossary/?all=true#term-code-contributor`, just like for Application Developer and Platform Developer.

So removing the `/docs/community/devel/` will resolve this issue.

**Comment by mtardy** [comment]
Thanks for the digging!

/good-first-issue

**Comment by amolmote** [comment]
@mtardy, I will wait for your response, then only I will open PR.

**Comment by mtardy** [comment]
You can create a PR with what you think is more sensible. I was thinking personally, like Shubham, that just removing the link was enough!

Thanks for spotting the duplicate, since the other issue was created way before, I will mark this one as duplicate and point to it in the other one.

/triage duplicate
