### ISSUE TITLE
PR 25764 is incomplete

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#36787]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#patch does not warn the reader that strategic merge patch does not work on custom resources.

**Proposed Solution:**
Add a warning.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

kubernetes/kubernetes#25764
See https://github.com/kubernetes/kubectl/issues/1280

**Comment by mk46** [comment]
/triage accepted
/language en
/assign
Seems like need to fix it first on upstream.

**Comment by tengqm** [comment]
@MikeSpreitzer Is this issue still relevant?

**Comment by MikeSpreitzer** [comment]
@tengqm : yes, this is still relevant.
/remove-lifecycle rotten
