### ISSUE TITLE
Expand the "Language specific style guide and glossary" section

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#36786]
@rolfedh and @AmanSarraf following up on our conversation in the localization meeting yesterday, I think it might be valuable to expand the note in the the [Language specific style guide and glossary](https://kubernetes.io/docs/contribute/localization/#language-specific-style-guide-and-glossary) section of the localization guide with more context about formalizing language specific localization best practices and creating specific translation word lists, like the Korean [list](https://kubernetes.io/ko/docs/contribute/localization_ko/#%ED%95%9C%EA%B8%80%ED%99%94-%EC%9A%A9%EC%96%B4%EC%A7%91).   

What do you think?

_Originally posted by @a-mccarthy in https://github.com/kubernetes/website/issues/35599#issuecomment-1245525533_

**Comment by a-mccarthy** [comment]
thanks @rolfedh!

**Comment by amolmote** [comment]
that great @rolfedh
