### ISSUE TITLE
[ko]Change the way removing `reviewer` section when localizing docs in Korean

### ISSUE THREAD

**Issue by jinnypark9393** [kubernetes/website#36800]
**This is a Feature Request**

**What would you like to be added**

- As discussed in previous SIG-Docs Korean L10n Team Meeting, I would like to change `### 리뷰어 삭제` part from leaving blank space to commenting the whole block in `content/ko/contribute/localizattion_ko.md`.

**Why is this needed**
- Reference: https://github.com/kubernetes/website/pull/35423#issuecomment-1196555307

**Comments**

/language ko

**Comment by jihoon-seo** [comment]
@jinnypark9393 감사합니다!
/triage accepted

**Comment by jinnypark9393** [comment]
This issue is resolved by https://github.com/kubernetes/website/pull/36802
