### ISSUE TITLE
Issue with /docs/concepts/configuration/secret/

### ISSUE THREAD

**Issue by attesch** [kubernetes/website#3681]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

[Risks](https://kubernetes.io/docs/concepts/configuration/secret/#risks) identified for Kubernetes Secrets should indicate that the secrets stored in YAML files must be protected.

**Proposed Solution:**

Add Risk Bullet:
- If a Base64 encoded secret is shared, it should be considered Compromised.  For Example: Checking secrets.yml into source control, placing secrets.yml on a document share, or emailing secret.yml.  All of these expose your secret to everyone who has access.  Base64 is considered [Plaintext](https://en.wikipedia.org/wiki/Plaintext) so secrets encoded as Base64 require additional controls to ensure only authorized users/systems can access them.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by jaredbhatti** [comment]
Add the bullet above under the following section: 
https://kubernetes.io/docs/concepts/configuration/secret/#risks

**Comment by tengqm** [comment]
issue solved.
