### ISSUE TITLE
Broken Link on /tasks/configure-pod-container/configure-persistent-volume-storage/ page

### ISSUE THREAD

**Issue by akankshakumari393** [kubernetes/website#36819]
the link to Storage Class on this [page](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/) is broken rather it should point to  [https://kubernetes.io/docs/concepts/storage/storage-classes/](https://kubernetes.io/docs/concepts/storage/storage-classes/)

> Cluster administrators can also use [StorageClasses](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#storageclass-v1-storage) to set up [dynamic provisioning](https://kubernetes.io/blog/2016/10/dynamic-provisioning-and-storage-in-kubernetes).

**Comment by amolmote** [comment]
good catch @akankshakumari393

**Comment by mtardy** [comment]
I saw you opened a similar issue here https://github.com/kubernetes/website/issues/36823, I don't know if there was an outage to the generated reference doc but the link is up now. Please reach out if the links are still down on your side.

/triage awaiting-more-evidence

**Comment by mtardy** [comment]
Oops
/triage not-reproducible

**Comment by mtardy** [comment]
I'm sorry I did not understand that the issue was that the anchor was not working! I guess you could fix the link to point to the new reference URL https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#storageclass-v1-storage-k8s-io!

/remove-triage not-reproducible
/triage accepted

**Comment by mk46** [comment]
Addressed in https://github.com/kubernetes/website/pull/36820
/close
