### ISSUE TITLE
Need to Refractor the Blog posts 

### ISSUE THREAD

**Issue by amolmote** [kubernetes/website#36824]
Observed some grammar  and punctuation's mistakes In  [this page](https://kubernetes.io/blog/2022/02/07/sig-multicluster-spotlight-2022/)
*some mistakes are:*

- `There's a few implementations of the MCS API out there and more are being developed.` *need to change like this*

`There are a few implementations of the MCS API out there, and more are being developed.`

- `where you're hoping to be in future?`  *need to change like this* `where you're hoping to be in the future?`
-  `There's a few projects that are kind of getting started, for example, Work API.` *need to change like this*
`There are a few projects that are kind of getting started, for example, Work API.` 

like this having so many minor mistakes need to fix it.

/assign

**Comment by sftim** [comment]
/area blog

/priority awaiting-more-evidence

With blog articles, we use the author's punctuation and grammar unless those are obviously wrong.

**Comment by sftim** [comment]
Concern about grammar and punctuation in Spotlight on SIG Multicluster article.

Also: https://kubernetes.io/blog/2022/02/07/sig-multicluster-spotlight-2022/ is a copy of https://www.k8s.dev/blog/2022/02/04/sig-multicluster-spotlight-2022/

If we made changes, we'd need to update https://www.k8s.dev/blog/2022/02/04/sig-multicluster-spotlight-2022/ at the same time.

**Comment by reylejano** [comment]
Since this blog is a mirror from a k8s.dev blog, this issue can be created on the contributor-site
Closing this issue for now as the source of this blog is not k/website
As a note, we like to keep the blog author's "voice" in the article unless there are grammar errors not stylistic changes
/close
