### ISSUE TITLE
Incorrect feature state in Topology Aware Hints concept

### ISSUE THREAD

**Issue by sergeyshevch** [kubernetes/website#36825]
**This is a Bug Report**

**Problem:**
I'm unsure about the right place to stay to comment about documentation inconvenience about this feature. 
The current documentation page for 1.25/1.24 [link](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/) said that the feature gate is NOT enabled by default, but feature gate documentation [link](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features) said it's enabled by default. 

As I found in issues (https://github.com/kubernetes/website/pull/32413, https://github.com/kubernetes/kubernetes/pull/108747, https://github.com/kubernetes/enhancements/issues/2433) It's enabled by default since 1.24
It's crucial for managed K8s users. EKS, for example, uses default feature gates and it was hard to get info about Topology Aware Hints support and information about When it will be supported in EKS.

**Proposed Solution:**
Update Topology Aware Hints documentation for 1.24+ versions.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/
https://v1-24.docs.kubernetes.io/docs/concepts/services-networking/topology-aware-hints/

**Kubernetes Version:-**
1.24 and further

I can make updates myself, but I guess that I need approval from the community to make sure that I'm right here

**Comment by sftim** [comment]
This is a bug in https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/

Thanks for reporting it. Pull requests are welcome (please fix the issue in _main_ first, and then we could backport that fix to _release-1.24_).

/retitle Incorrect feature state in Topology Aware Hints concept
/language en
/help
/triage accepted
/priority backlog

**Comment by sergeyshevch** [comment]
@sftim Thanks for triaging. I will try to fix it today

**Comment by sergeyshevch** [comment]
/close
Closed in https://github.com/kubernetes/website/pull/36828
