### ISSUE TITLE
Broken Link on Kubernetes API Concepts

### ISSUE THREAD

**Issue by akankshakumari393** [kubernetes/website#36823]
The link to `configuration object` is broken on this page [https://kubernetes.io/docs/reference/using-api/api-concepts/](https://kubernetes.io/docs/reference/using-api/api-concepts/) 

>Additionally, admission webhooks can declare in their [configuration object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#webhook-v1beta1-admissionregistration-k8s-io) that they do not have side effects, by setting their sideEffects field to None.

**Comment by mtardy** [comment]
Same comment as here https://github.com/kubernetes/website/issues/36819#issuecomment-1247747442.

/triage not-reproducible

**Comment by NitishKumar06** [comment]
The link is working fine for me.

**Comment by sergeyshevch** [comment]
@mtardy It has also broken for me. It points to an incorrect anchor. So I was navigated to the top of the page

**Comment by mtardy** [comment]
Oh, I'm sorry, I went too fast on that one, you were meaning that the anchor was incorrect and not that the link was pointing to nothing, like a 404!

So I guess we should update the link and point to:
- https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#validatingwebhook-v1-admissionregistration-k8s-io
- or https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#mutatingwebhook-v1-admissionregistration-k8s-io

Or point to something else!

/remove-triage not-reproducible
/triage accepted
/kind bug
/help

**Comment by akankshakumari393** [comment]
Thanks @mtardy I have raised a PR and corrected the anchor to [https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#validatingwebhook-v1-admissionregistration-k8s-io](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#validatingwebhook-v1-admissionregistration-k8s-io). Since the Paragraph mentions about validation webhook.

**Comment by mk46** [comment]
Addressed in https://github.com/kubernetes/website/pull/36834
/close
