### ISSUE TITLE
Unspecified issue with “Installing kubeadm” page

### ISSUE THREAD

**Issue by 9948180189** [kubernetes/website#36827]

**Comment by NitishKumar06** [comment]
Please elaborate the issue.

**Comment by sftim** [comment]
https://k8s.io/docs/setup/independent/install-kubeadm/ is a redirect to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

/retitle Unspecified issue with “Installing kubeadm” page

/triage needs-information

**Comment by sftim** [comment]
/close

Without a description of the issue, we can't work on this @9948180189
