### ISSUE TITLE
`release_complete` localization string is unused

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#36839]
This term is never used, we should just remove it from `data/i18n/en/en.toml`.

_Originally posted by @Sea-n in https://github.com/kubernetes/website/pull/36774#discussion_r969684043_

**Comment by rolfedh** [comment]
@sergeyshevch Hi, Sergey. I hope you're doing well. Do you have any questions about this task?

**Comment by sergeyshevch** [comment]
@rolfedh Sorry. But bad that it's delayed a little bit more than I expected. I will work on it this week.

**Comment by rolfedh** [comment]
No worries. Thanks!

**Comment by sergeyshevch** [comment]
@rolfedh Really sorry for such a delay. Just created PR to close this. #37384

**Comment by rolfedh** [comment]
> @rolfedh Really sorry for such a delay. Just created PR to close this. #37384

No problem! Thanks, @sergeyshevch !

**Comment by sergeyshevch** [comment]
Fixed in https://github.com/kubernetes/website/pull/37384 /close

**Comment by sergeyshevch** [comment]
Fixed in https://github.com/kubernetes/website/pull/37384 

/close
