### ISSUE TITLE
Annotation `service.kubernetes.io/topology-aware-hints` not registered

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#36830]
**This is a Bug Report**

**Problem:**
[Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) doesn't list the annotation 
 `service.kubernetes.io/topology-aware-hints`.

**Proposed Solution:**

Add `service.kubernetes.io/topology-aware-hints` to the Well-Known Labels, Annotations and Taints reference.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**

See https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/ for details, and maybe put a link in the annotation reference that links there.

/language en
/sig network

**Comment by sftim** [comment]
We should fix this before https://github.com/kubernetes/enhancements/issues/2433 graduates to stable.

**Comment by Shivansh-yadav13** [comment]
@sftim can I contribute?

**Comment by sftim** [comment]
Anyone is welcome to contribute.

**Comment by sergeyshevch** [comment]
It looks like we resolved it in https://github.com/kubernetes/website/pull/36828

/close

**Comment by sftim** [comment]
[Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) still doesn't list the annotation `service.kubernetes.io/topology-aware-hints`.

/reopen

**Comment by sergeyshevch** [comment]
@sftim Thanks! I'd really missed that I didn't add it to this page. 
Will create PR with the fix today 

/assign
