### ISSUE TITLE
kubectl default namespace not always 'default' but depends on kubeconfig

### ISSUE THREAD

**Issue by sagayd** [kubernetes/website#36851]
_This is different from what happens outside of a cluster; when kubectl runs outside a cluster and you don't specify a namespace, the kubectl command acts against the default namespace._

On the above documentation, the kubectl does not act against 'default' namespace but the one assigned to the current-context. The kubeconfig files default context may be pointed to 'default' namespace, but that is not the default namespace all the time.

**Comment by mtardy** [comment]
Hey, I had to search to retrieve where the context of what you mentioned, [it's from here](https://kubernetes.io/docs/reference/kubectl/#in-cluster-authentication-and-namespace-overrides:~:text=This%20is%20different%20from%20what%20happens%20outside%20of%20a%20cluster%3B%20when%20kubectl%20runs%20outside%20a%20cluster%20and%20you%20don%27t%20specify%20a%20namespace%2C%20the%20kubectl%20command%20acts%20against%20the%20default%20namespace.) for further info.

This is indeed a simplification but might be correct most of the time with default configured kubeconfig contexts. It could be more precise, mentioning the kubeconfig file (keeping in mind that this section is about in-cluster config).

/sig cli
/triage accepted
/priority backlog
/language en

**Comment by mtardy** [comment]
/retitle kubectl default namespace not always 'default' but depends on kubeconfig

If you can find a better title, just needed to make something a bit more precise than just an issue on kubectl
