### ISSUE TITLE
Outdated Korean contents in the dev-1.25-ko.1

### ISSUE THREAD

**Issue by kyungjin99** [kubernetes/website#36863]
# This is a Bug Report

Report generated by the following command.
`./scripts/diff_l10n_branches.py ko upstream/dev-1.24-ko.3 upstream/dev-1.25-ko.1`

## Problem
Outdated files in the upstream/dev-1.25-ko.1 branch.

### 126 files to be modified 
1. [ ] M1.  `content/en/_index.html`  | 1(+XS) 1(-)
1. [ ] M2.  `content/en/community/code-of-conduct.md`  | 2(+XS) 1(-)
1. [ ] M3.  `content/en/community/static/cncf-code-of-conduct.md`  | 10(+S) 11(-)
1. [ ] M4.  `content/en/docs/concepts/architecture/garbage-collection.md`  | 1(+XS) 1(-)
1. [ ] M5.  `content/en/docs/concepts/architecture/nodes.md`  | 2(+XS) 3(-)
1. [ ] M6.  `content/en/docs/concepts/cluster-administration/addons.md`  | 3(+XS) 3(-)
1. [ ] M7.  `content/en/docs/concepts/cluster-administration/networking.md`  | 3(+XS) 164(-)
1. [ ] M8.  `content/en/docs/concepts/cluster-administration/proxies.md`  | 2(+XS) 2(-)
1. [ ] M9.  `content/en/docs/concepts/cluster-administration/system-traces.md`  | 30(+M) 1(-)
1. [ ] M10.  `content/en/docs/concepts/configuration/manage-resources-containers.md`  | 7(+XS) 8(-)
1. [ ] M11.  `content/en/docs/concepts/configuration/secret.md`  | 3(+XS) 3(-)
1. [ ] M12.  `content/en/docs/concepts/containers/container-lifecycle-hooks.md`  | 1(+XS) 1(-)
1. [ ] M13.  `content/en/docs/concepts/containers/images.md`  | 5(+XS) 2(-)
1. [ ] M14.  `content/en/docs/concepts/extend-kubernetes/api-extension/custom-resources.md`  | 9(+XS) 9(-)
1. [ ] M15.  `content/en/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md`  | 1(+XS) 1(-)
1. [ ] M16.  `content/en/docs/concepts/extend-kubernetes/operator.md`  | 20(+S) 20(-)
1. [ ] M17.  `content/en/docs/concepts/overview/_index.md`  | 93(+M) 3(-)
1. [ ] M18.  `content/en/docs/concepts/overview/components.md`  | 2(+XS) 2(-)
1. [ ] M19.  `content/en/docs/concepts/overview/kubernetes-api.md`  | 6(+XS) 3(-)
1. [ ] M20.  `content/en/docs/concepts/overview/working-with-objects/common-labels.md`  | 2(+XS) 0(-)
1. [ ] M21.  `content/en/docs/concepts/overview/working-with-objects/labels.md`  | 1(+XS) 1(-)
1. [ ] M22.  `content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md`  | 3(+XS) 3(-)
1. [ ] M23.  `content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md`  | 69(+M) 14(-)
1. [ ] M24.  `content/en/docs/concepts/security/overview.md`  | 1(+XS) 0(-)
1. [ ] M25.  `content/en/docs/concepts/security/pod-security-policy.md`  | 12(+S) 763(-)
1. [ ] M26.  `content/en/docs/concepts/security/pod-security-standards.md`  | 27(+S) 26(-)
1. [ ] M27.  `content/en/docs/concepts/security/rbac-good-practices.md`  | 13(+S) 14(-)
1. [ ] M28.  `content/en/docs/concepts/services-networking/connect-applications-service.md`  | 11(+S) 8(-)
1. [ ] M29.  `content/en/docs/concepts/services-networking/dns-pod-service.md`  | 2(+XS) 2(-)
1. [ ] M30.  `content/en/docs/concepts/services-networking/endpoint-slices.md`  | 2(+XS) 2(-)
1. [ ] M31.  `content/en/docs/concepts/services-networking/network-policies.md`  | 2(+XS) 6(-)
1. [ ] M32.  `content/en/docs/concepts/services-networking/service.md`  | 14(+S) 14(-)
1. [ ] M33.  `content/en/docs/concepts/services-networking/topology-aware-hints.md`  | 2(+XS) 2(-)
1. [ ] M34.  `content/en/docs/concepts/storage/ephemeral-volumes.md`  | 1(+XS) 4(-)
1. [ ] M35.  `content/en/docs/concepts/storage/persistent-volumes.md`  | 49(+M) 30(-)
1. [ ] M36.  `content/en/docs/concepts/storage/storage-capacity.md`  | 1(+XS) 1(-)
1. [ ] M37.  `content/en/docs/concepts/storage/storage-classes.md`  | 3(+XS) 152(-)
1. [ ] M38.  `content/en/docs/concepts/storage/volume-pvc-datasource.md`  | 3(+XS) 3(-)
1. [ ] M39.  `content/en/docs/concepts/storage/volume-snapshots.md`  | 2(+XS) 0(-)
1. [ ] M40.  `content/en/docs/concepts/storage/volumes.md`  | 69(+M) 139(-)
1. [ ] M41.  `content/en/docs/concepts/storage/windows-storage.md`  | 1(+XS) 1(-)
1. [ ] M42.  `content/en/docs/concepts/windows/intro.md`  | 3(+XS) 4(-)
1. [ ] M43.  `content/en/docs/concepts/windows/user-guide.md`  | 4(+XS) 5(-)
1. [ ] M44.  `content/en/docs/concepts/workloads/controllers/cron-jobs.md`  | 1(+XS) 1(-)
1. [ ] M45.  `content/en/docs/concepts/workloads/controllers/deployment.md`  | 3(+XS) 3(-)
1. [ ] M46.  `content/en/docs/concepts/workloads/controllers/job.md`  | 85(+M) 0(-)
1. [ ] M47.  `content/en/docs/concepts/workloads/controllers/statefulset.md`  | 6(+XS) 8(-)
1. [ ] M48.  `content/en/docs/concepts/workloads/pods/_index.md`  | 17(+S) 0(-)
1. [ ] M49.  `content/en/docs/concepts/workloads/pods/disruptions.md`  | 38(+M) 0(-)
1. [ ] M50.  `content/en/docs/concepts/workloads/pods/downward-api.md`  | 2(+XS) 2(-)
1. [ ] M51.  `content/en/docs/concepts/workloads/pods/ephemeral-containers.md`  | 1(+XS) 1(-)
1. [ ] M52.  `content/en/docs/concepts/workloads/pods/pod-lifecycle.md`  | 39(+M) 2(-)
1. [ ] M53.  `content/en/docs/contribute/participate/_index.md`  | 1(+XS) 1(-)
1. [ ] M54.  `content/en/docs/contribute/style/write-new-topic.md`  | 2(+XS) 2(-)
1. [ ] M55.  `content/en/docs/reference/access-authn-authz/authorization.md`  | 2(+XS) 0(-)
1. [ ] M56.  `content/en/docs/reference/access-authn-authz/service-accounts-admin.md`  | 16(+S) 7(-)
1. [ ] M57.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 86(+M) 38(-)
1. [ ] M58.  `content/en/docs/reference/command-line-tools-reference/kube-proxy.md`  | 3(+XS) 3(-)
1. [ ] M59.  `content/en/docs/reference/glossary/cni.md`  | 4(+XS) 4(-)
1. [ ] M60.  `content/en/docs/reference/glossary/eviction.md`  | 18(+S) 18(-)
1. [ ] M61.  `content/en/docs/reference/glossary/persistent-volume-claim.md`  | 1(+XS) 1(-)
1. [ ] M62.  `content/en/docs/reference/glossary/pod-security-policy.md`  | 2(+XS) 1(-)
1. [ ] M63.  `content/en/docs/reference/glossary/sig.md`  | 1(+XS) 1(-)
1. [ ] M64.  `content/en/docs/reference/issues-security/issues.md`  | 5(+XS) 2(-)
1. [ ] M65.  `content/en/docs/reference/kubectl/cheatsheet.md`  | 2(+XS) 2(-)
1. [ ] M66.  `content/en/docs/reference/labels-annotations-taints/_index.md`  | 49(+M) 24(-)
1. [ ] M67.  `content/en/docs/reference/node/topics-on-dockershim-and-cri-compatible-runtimes.md`  | 9(+XS) 7(-)
1. [ ] M68.  `content/en/docs/reference/scheduling/config.md`  | 49(+M) 41(-)
1. [ ] M69.  `content/en/docs/reference/scheduling/policies.md`  | 1(+XS) 2(-)
1. [ ] M70.  `content/en/docs/setup/best-practices/node-conformance.md`  | 3(+XS) 3(-)
1. [ ] M71.  `content/en/docs/setup/production-environment/container-runtimes.md`  | 60(+M) 53(-)
1. [ ] M72.  `content/en/docs/setup/production-environment/tools/kubeadm/control-plane-flags.md`  | 18(+S) 15(-)
1. [ ] M73.  `content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md`  | 11(+S) 10(-)
1. [ ] M74.  `content/en/docs/tasks/access-application-cluster/access-cluster.md`  | 2(+XS) 2(-)
1. [ ] M75.  `content/en/docs/tasks/access-application-cluster/web-ui-dashboard.md`  | 1(+XS) 1(-)
1. [ ] M76.  `content/en/docs/tasks/administer-cluster/access-cluster-api.md`  | 1(+XS) 1(-)
1. [ ] M77.  `content/en/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md`  | 3(+XS) 3(-)
1. [ ] M78.  `content/en/docs/tasks/administer-cluster/namespaces.md`  | 2(+XS) 2(-)
1. [ ] M79.  `content/en/docs/tasks/administer-cluster/sysctl-cluster.md`  | 2(+XS) 55(-)
1. [ ] M80.  `content/en/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity.md`  | 1(+XS) 1(-)
1. [ ] M81.  `content/en/docs/tasks/configure-pod-container/static-pod.md`  | 1(+XS) 1(-)
1. [ ] M82.  `content/en/docs/tasks/debug/debug-application/debug-running-pod.md`  | 8(+XS) 5(-)
1. [ ] M83.  `content/en/docs/tasks/debug/debug-cluster/local-debugging.md`  | 1(+XS) 1(-)
1. [ ] M84.  `content/en/docs/tasks/extend-kubernetes/setup-extension-api-server.md`  | 1(+XS) 1(-)
1. [ ] M85.  `content/en/docs/tasks/inject-data-application/define-command-argument-container.md`  | 17(+S) 17(-)
1. [ ] M86.  `content/en/docs/tasks/inject-data-application/define-environment-variable-container.md`  | 23(+S) 23(-)
1. [ ] M87.  `content/en/docs/tasks/inject-data-application/define-interdependent-environment-variables.md`  | 25(+S) 21(-)
1. [ ] M88.  `content/en/docs/tasks/inject-data-application/distribute-credentials-secure.md`  | 26(+S) 26(-)
1. [ ] M89.  `content/en/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md`  | 1(+XS) 1(-)
1. [ ] M90.  `content/en/docs/tasks/job/automated-tasks-with-cron-jobs.md`  | 4(+XS) 0(-)
1. [ ] M91.  `content/en/docs/tasks/job/coarse-parallel-processing-work-queue.md`  | 1(+XS) 1(-)
1. [ ] M92.  `content/en/docs/tasks/job/indexed-parallel-processing-static.md`  | 1(+XS) 1(-)
1. [ ] M93.  `content/en/docs/tasks/manage-daemon/update-daemon-set.md`  | 1(+XS) 1(-)
1. [ ] M94.  `content/en/docs/tasks/manage-gpus/scheduling-gpus.md`  | 2(+XS) 2(-)
1. [ ] M95.  `content/en/docs/tasks/manage-kubernetes-objects/kustomization.md`  | 3(+XS) 12(-)
1. [ ] M96.  `content/en/docs/tasks/network/validate-dual-stack.md`  | 11(+S) 11(-)
1. [ ] M97.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md`  | 2(+XS) 25(-)
1. [ ] M98.  `content/en/docs/tasks/tls/managing-tls-in-a-cluster.md`  | 1(+XS) 1(-)
1. [ ] M99.  `content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md`  | 6(+XS) 2(-)
1. [ ] M100.  `content/en/docs/tutorials/hello-minikube.md`  | 2(+XS) 2(-)
1. [ ] M101.  `content/en/docs/tutorials/security/apparmor.md`  | 3(+XS) 46(-)
1. [ ] M102.  `content/en/docs/tutorials/services/source-ip.md`  | 2(+XS) 2(-)
1. [ ] M103.  `content/en/docs/tutorials/stateful-application/basic-stateful-set.md`  | 10(+S) 10(-)
1. [ ] M104.  `content/en/examples/admin/konnectivity/konnectivity-server.yaml`  | 1(+XS) 1(-)
1. [ ] M105.  `content/en/examples/admin/logging/two-files-counter-pod-agent-sidecar.yaml`  | 1(+XS) 1(-)
1. [ ] M106.  `content/en/examples/admin/sched/pod1.yaml`  | 1(+XS) 1(-)
1. [ ] M107.  `content/en/examples/admin/sched/pod2.yaml`  | 1(+XS) 1(-)
1. [ ] M108.  `content/en/examples/admin/sched/pod3.yaml`  | 1(+XS) 1(-)
1. [ ] M109.  `content/en/examples/application/php-apache.yaml`  | 1(+XS) 1(-)
1. [ ] M110.  `content/en/examples/application/web/web-parallel.yaml`  | 1(+XS) 1(-)
1. [ ] M111.  `content/en/examples/application/web/web.yaml`  | 1(+XS) 1(-)
1. [ ] M112.  `content/en/examples/application/zookeeper/zookeeper.yaml`  | 1(+XS) 1(-)
1. [ ] M113.  `content/en/examples/debug/node-problem-detector-configmap.yaml`  | 1(+XS) 1(-)
1. [ ] M114.  `content/en/examples/debug/node-problem-detector.yaml`  | 1(+XS) 1(-)
1. [ ] M115.  `content/en/examples/pods/inject/dapi-envars-container.yaml`  | 1(+XS) 1(-)
1. [ ] M116.  `content/en/examples/pods/inject/dapi-envars-pod.yaml`  | 1(+XS) 1(-)
1. [ ] M117.  `content/en/examples/pods/inject/dapi-volume-resources.yaml`  | 1(+XS) 1(-)
1. [ ] M118.  `content/en/examples/pods/inject/dapi-volume.yaml`  | 1(+XS) 1(-)
1. [ ] M119.  `content/en/examples/pods/pod-with-affinity-anti-affinity.yaml`  | 1(+XS) 1(-)
1. [ ] M120.  `content/en/examples/pods/pod-with-node-affinity.yaml`  | 1(+XS) 1(-)
1. [ ] M121.  `content/en/examples/pods/pod-with-pod-affinity.yaml`  | 1(+XS) 1(-)
1. [ ] M122.  `content/en/examples/pods/topology-spread-constraints/one-constraint-with-nodeaffinity.yaml`  | 1(+XS) 1(-)
1. [ ] M123.  `content/en/examples/pods/topology-spread-constraints/one-constraint.yaml`  | 1(+XS) 1(-)
1. [ ] M124.  `content/en/examples/pods/topology-spread-constraints/two-constraints.yaml`  | 1(+XS) 1(-)
1. [ ] M125.  `content/en/releases/_index.md`  | 2(+XS) 2(-)
1. [ ] M126.  `content/en/releases/version-skew-policy.md`  | 1(+XS) 1(-)

### 1 files to be deleted
1. [x] D1.  `content/en/docs/concepts/overview/what-is-kubernetes.md`

## Proposed Solution

Use `git diff` to check what is changed in the upstream. And apply the upstream changes manually
to the `content/ko` of `upstream/dev-1.25-ko.1` branch.

For example:
```
# checkout `upstream/dev-1.25-ko.1`
...
# check what is updated in the upstream
git diff upstream/dev-1.24-ko.3 upstream/dev-1.25-ko.1 -- content/en/_index.html
# apply changes to content/ko
vi content/ko/_index.html
...
# commit and push
...
# make PR to `upstream/dev-1.25-ko.1`
```

## Pages to Update

Pages in content/ko

/language ko

**Comment by seokho-son** [comment]
Thanks, @kyungjin99 for this report!

/triage accepted

**Comment by having-dlrow** [comment]
- M1 - M10 @having-dlrow

**Comment by mocha-123** [comment]
M34 - M41 작업하겠습니다.

**Comment by Seo-yul** [comment]
M90 - M126 작업하겠습니다.

**Comment by bconfiden2** [comment]
- M74 - M89 : @bconfiden2

**Comment by seokho-son** [comment]
- [ ] M1 - M10 : @having-dlrow
- [ ] HELP
- [ ] M34 - M41 : @mocha-123
- [ ] HELP
- [ ] M74 - M89 : @bconfiden2
- [ ] M90 - M126 : @Seo-yul

I will keep update this comment to trace assignees for parts of takes.

**Comment by PARKINHYO** [comment]
@seokho-son 님 안녕하세요! M17-M21 해보겠습니다.

**Comment by onestone9900** [comment]
M42 ~ M52 진행해보겠습니다!

**Comment by seokho-son** [comment]
@PARKINHYO 님 안녕하세요.
제가 파일을 몇 개 살펴보니,  

M17. content/en/docs/concepts/overview/_index.md | 93(+M) 3(-)
은 새로 작성된 내용이 아니라,

D1. content/en/docs/concepts/overview/what-is-kubernetes.md
의 기존 내용을 단순 이동(내용을 카피)한 것으로 보입니다.

혹시나 완전히 새롭게 작업하지 마시고, 두 파일을 함께 살펴보면서 작업하시면 좋을 것 같습니다. (content/ko/docs/concepts/overview/what-is-kubernetes.md)

**Comment by PARKINHYO** [comment]
> @PARKINHYO 님 안녕하세요. 제가 파일을 몇 개 살펴보니,
> 
> M17. content/en/docs/concepts/overview/_index.md | 93(+M) 3(-) 은 새로 작성된 내용이 아니라,
> 
> D1. content/en/docs/concepts/overview/what-is-kubernetes.md 의 기존 내용을 단순 이동(내용을 카피)한 것으로 보입니다.
> 
> 혹시나 완전히 새롭게 작업하지 마시고, 두 파일을 함께 살펴보면서 작업하시면 좋을 것 같습니다. (content/ko/docs/concepts/overview/what-is-kubernetes.md)

넵 알려주셔서 감사합니다!

**Comment by WESTZERO115** [comment]
M22~M33 진행하겠습니다!

**Comment by hj-johannes-lee** [comment]
안녕하세요.! 제가 조금씩이라도 좀 의미있는 컨트리뷰션을 좀 해보려고 하다가, 번역 관련 된 내용도 있다는 것을 알게 되었습니다.!
여기에 그냥 코멘트로 하고자 하는 번역 남기면 assign 해주시는 건가요? :)

만약 그렇다면,, M71-M73 진행해도 될까요? :)

**Comment by seokho-son** [comment]
@hj-johannes-lee 
기여에 관심 가져주셔서 감사합니다!! 환영합니다. :)
M71-M73 진행해주시면 좋을 것 같습니다.
그런데 해당 이슈에 Task 처리는 한글 작업 브랜치(마일스톤: dev-1.25-ko.1) 일정과 연계가 되어 있어서,
다소 빠르게 처리해야 할 수도 있을 것 같습니다.
꼭 여러개의 Task를 한꺼번에 처리해야 하는 것은 아니니, Task를 하나씩 처리해보시면 어떨까요?
(예를 들면, M71 우선 처리, 이후 다른 Task를 다시 할당하여 처리)

**Comment by hj-johannes-lee** [comment]
넵, 말씀 주신대로 하나씩 하고서 PR 올려보겠습니다.!

**Comment by hj-johannes-lee** [comment]
@seokho-son M72-73도 며칠 전에 완료 하긴 했습니다.! 안 바쁘실 때 한번 검토해 주세용! :)

**Comment by seokho-son** [comment]
@hj-johannes-lee 
오오..  빠르시군요! 감사합니다!! :)

**Comment by bconfiden2** [comment]
바빠서 신경을 못쓰고 있었는데... M53-M70 아직 남아있으면 하겠습니다!!

**Comment by seokho-son** [comment]
@bconfiden2 감사합니다! 할당하겠습니다~~

**Comment by hj-johannes-lee** [comment]
M61-65 // M67 // M69-M70 해보겠습니다.!
M66과 M68은 좀 양이 많은 것 같아서,, 다른 분이 안 맡으시면 나중에 시도해보도록 하겠습니다.!

**Comment by hj-johannes-lee** [comment]
@seokho-son M66 하겠습니다!

**Comment by seokho-son** [comment]
complete !

/close
