### ISSUE TITLE
create script for generating first draft translation 

### ISSUE THREAD

**Issue by bart2001** [kubernetes/website#36879]
**This is a Feature Request**

create script for generating first draft translation using translation open source.

this feature starts with English(source language) to Korean(target language) and may extend to other target languages

**What would you like to be added**

python file for draft translation

**Why is this needed**
Localization work is time-consuming and requires human effort.

generating first draft translation with script may help this.

**Comments**

https://github.com/kubernetes/website/issues/36879#tasklist-block-8ec40ce9-a36f-4687-b67f-92fcc8f04711

**Comment by sftim** [comment]
Sounds useful.

**Comment by a-mccarthy** [comment]
This sounds really interesting!

**Comment by seokho-son** [comment]
Let me close this issue since we have another umbrella issue which we can refer. #37954

/close
