### ISSUE TITLE
[ko] Need to update the code-contribution.md 

### ISSUE THREAD

**Issue by amolmote** [kubernetes/website#36882]
**This is a Bug Report**

*what is the problem?*
When you visit  [this page](https://kubernetes.io/ko/docs/reference/glossary/?fundamental=true&community=true)
and click on `코드 기여자` it results in page not found issue.
![korian](https://user-images.githubusercontent.com/98871024/190886182-df34a0ed-5f16-4f0e-b851-e72753a892be.PNG)

*Which page required to update?*
[code-contributor.md](https://github.com/kubernetes/website/blob/main/content/ko/docs/reference/glossary/code-contributor.md)

/assign

**Comment by seokho-son** [comment]
Hi @amolmote
I am maintaining Korean contents.

![image](https://user-images.githubusercontent.com/5966944/190934730-ef9131fa-a2ee-41e2-a40f-a5958ae48541.png)

We already have the `Code Contributor` term in Korean. (`코드 컨트리뷰터(Code Contributor)`)
(Please note that `컨트리뷰터` is acceptable translation for `contributor`)

The term you captured is for `Developer (disambiguation)` which is different term.
![image](https://user-images.githubusercontent.com/5966944/190934776-efe07710-eb82-41a0-a076-9c564aefc041.png)

So, if I understood your issue correctly, it seems not a bug.

**Comment by seokho-son** [comment]
@amolmote 
Oh, I misunderstood your issue !

The link about `code contributor` in `Developer (disambiguation)` in Korean is not accessible!

It is a bug. :) Thanks!

/triage accepted

By the way, please use `dev-1.25-ko.1` branch as the base branch of Korean contents contribution.
