### ISSUE TITLE
CronJob cron format "Once every X minutes"

### ISSUE THREAD

**Issue by catmanjan** [kubernetes/website#36891]
Hello does CronJob's cron format support the format "*/5 * * * *"

Which would trigger every 5 minutes?

**Comment by Shubham82** [comment]
Hi @catmanjan 
Yes, this format is supported by the CronJob object.

**Comment by Shubham82** [comment]
To check and Hands-on on it, you can perform this [task](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/) with your own value for the `schedule:` field.
To generate expression you can take the help of [crontab.guru](https://crontab.guru/).

**Comment by reylejano** [comment]
Closing this issue as there is a link to a tool that helps to generate a cron schedule
/close

**Comment by catmanjan** [comment]
Thanks all good - just an FYI the doco is not fully clear on what is supported - e.g. https://crontab.guru/ lists @reboot as an option

It would be good to get a definitive list in the kubernetes doco
