### ISSUE TITLE
"API Priority and Fairness" doc must be updated

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#36894]
(1) The user-facing changes in https://github.com/kubernetes/kubernetes/pull/110104 are not yet reflected in the doc.

(2) There are four possible values for the `reason` of a rejection ("concurrency-limit", "queue-full", "time-out", and "cancelled") but "cancelled" is not listed in the doc.

The relevant page is https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

/sig api-machinery
@tkashem 
@MikeSpreitzer

**Comment by mtardy** [comment]
APF is for API Priority and Fairness just for people looking into this issue.

/triage accepted
/priority important-longterm

**Comment by mtardy** [comment]
Please feel free to change it again if it is not correct.

/retitle "API Priority and Fairness" doc must be updated
