### ISSUE TITLE
Broken link on Documenting a feature for a release page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#36900]
**Problem:**
The text [**Commit into another person's PR**](https://kubernetes.io/docs/contribute/review/for-approvers/#commit-into-another-persons-pr) on [link](https://kubernetes.io/docs/contribute/new-content/new-features/) should point to these https://kubernetes.io/docs/contribute/review/for-approvers/#commit-into-another-person-s-pr
Check the page [Documenting a feature for a release](https://kubernetes.io/docs/contribute/new-content/new-features/) for the problem.

**Page to Update:**
https://kubernetes.io/docs/contribute/new-content/new-features/

**Proposed Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the link on the text **Commit into another person's PR** to https://kubernetes.io/docs/contribute/review/for-approvers/#commit-into-another-person-s-pr and not to this [link](https://kubernetes.io/docs/contribute/review/for-approvers/#commit-into-another-persons-pr).

/kind document
/assign
/language en

**Comment by Sea-n** [comment]
For the record: I've already opened PR #36899 20 minutes before this issue.
- #36899

**Comment by mtardy** [comment]
It was fixed by https://github.com/kubernetes/website/pull/36899.

/close
