### ISSUE TITLE
Display bug in `rules.http.paths.pathType` section of Ingress API referenc

### ISSUE THREAD

**Issue by vmahilevskyi** [kubernetes/website#36912]
There is a display bug in `rules.http.paths.pathType`  section of [IngressSpec](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec)

`Exact` and `Prefix` values are not displayed properly as `ImplementationSpecific` is.

![image](https://user-images.githubusercontent.com/30826865/191179628-3d0373d5-2f44-48aa-99a4-aa27830db9ca.png)

I guess the list of values should be looking like this:

* Exact: Matches the URL path exactly. 
* Prefix: Matches based on a URL path prefix split by '/'. Matching is done on a path element by element basis. A path element refers is the list of labels in the path split by the '/' separator. A request is a match for path p if every p is an element-wise prefix of p of the request path. Note that if the last element of the path is a substring of the last element in request path, it is not a match (e.g. /foo/bar matches /foo/bar/baz, but does not match /foo/barbaz).

* ImplementationSpecific: Interpretation of the Path matching is up to the IngressClass. Implementations can treat this as a separate PathType or treat it identically to Prefix or Exact path types. Implementations are required to support all path types.

**Comment by sftim** [comment]
/retitle Display bug in `rules.http.paths.pathType` section of Ingress API referenc

/sig docs
/language en
/triage accepted
/priority backlog

This could be seen as a feature request for the code that [generates](https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-resourcesdocs) API reference docs.

**Comment by sftim** [comment]
/retitle Display bug in rules.http.paths.pathType section of Ingress API reference

**Comment by sftim** [comment]
/retitle Display bug in `rules.http.paths.pathType` section of Ingress API referenc
