### ISSUE TITLE
Host Ports description at Pod Security Standards can mislead user

### ISSUE THREAD

**Issue by KrzysztofDziankowski** [kubernetes/website#36938]
**This is a Feature Request**

[Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) _"Host Ports"_ rule have the following description _"HostPorts should be disallowed, or at minimum restricted to a known list."_
It is not clear for the reader that this statement is composed from two mutually exclusive terms _"HostPorts should be disallowed”_ OR _“HostPorts should be restricted to a known list."_
Additionally, it is not clear that _Pod Security Admission Controller_  implements the first option and the second one is for 3rd party controllers like Gatekeeper/Kyverno.

**What would you like to be added**

[Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) _"Host Ports"_ rule can be rephrased so it is clear that it consist of two mutually exclusive options. Or it be divided into two separate rules (two rows in the table).

[Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) doc or/and [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) doc should clearly state which _"Host Ports"_ option is implemented by the _"Pod Security Admission"_

**Why is this needed**

Pod Security Standards doc can mislead user.

**Comments**

**Comment by shannonxtreme** [comment]
If we're updating the PSA doc, we should perhaps work with sig-auth (@tallclair maybe) to identify if there are other Pod Security Standards where PSA only enforces a specific condition or behaviour by default.

**Comment by mehabhalodiya** [comment]
@ritazh I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on 🙂 
/unassign @ritazh

**Comment by shannonxtreme** [comment]
For the adventurous contributor looking for a good issue, here's what you need to do:

In the **Host Ports** row in https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline, replace the first sentence with "HostPorts should be disallowed."

For instructions to edit a page and create a PR, use [Changes using GitHub](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#changes-using-github) in our contributor guide

/help-wanted
