### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by FadyNos-hy** [kubernetes/website#36939]
The interactive session doesn't start

**Comment by mtardy** [comment]
I just tried and it worked on my side, I don't know if it was a temporary outage or if it's a region thing.
Please tell us if it still doesn't work on your side.

/triage not-reproducible

**Comment by Shubham82** [comment]
Hi @FadyNos-hy 
It is working for me also.

It might be due to an ad-blocker. Please check if the ad-blocker is enabled or not on your browse, if yes then pls disable it and try again.
Refer: [#34253](https://github.com/kubernetes/website/issues/34253#issuecomment-1153578416)

**Comment by Shubham82** [comment]
Closing this issue, as it is not reproducible.
Please open it again if you have any concerns regarding it.

/close
