### ISSUE TITLE
Difference in inserting glossary definition

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/website#36957]
**This is a Feature Request**

**What would you like to be added**
Modify the [cloud-controller-manager](https://github.com/kubernetes/website/edit/main/content/en/docs/concepts/overview/components.md)'s glossary definition `length` property from `short` to `all`.

**Why is this needed**
`length="short"` in [cloud-controller-manager](https://github.com/kubernetes/website/edit/main/content/en/docs/concepts/overview/components.md) makes the glossary tooltip to unmatch the intended blank... is it intended?

<img width="1412" alt="스크린샷 2022-09-22 오후 3 26 33" src="https://user-images.githubusercontent.com/58922834/191674818-94666b74-9a93-4a54-b781-efe8e47cbcd2.png">

/assign

**Comment by mtardy** [comment]
Yes it seems to be out of a paragraph HTML tag in the rendered page
![image](https://user-images.githubusercontent.com/11256051/192466496-8c253771-422a-487b-8d5f-2b9f38d479cc.png)

To have a direct link, this issue is about the page [Kubernetes Components](https://kubernetes.io/docs/concepts/overview/components/#cloud-controller-manager).

/triage accepted
/kind bug
/priority backlog

**Comment by rolfedh** [comment]
Setting aside the issue of the missing paragraph tag, which we should fix separately, let's compare the result of the change in this PR:
- Before: https://kubernetes.io/docs/concepts/overview/components/#cloud-controller-manager
- After: https://deploy-preview-37048--kubernetes-io-main-staging.netlify.app/docs/concepts/overview/components/#cloud-controller-manager

In effect, this PR adds the following paragraph:
```
By decoupling the interoperability logic between Kubernetes and the underlying cloud infrastructure, the cloud-controller-manager component enables cloud providers to release features at a different pace compared to the main Kubernetes project.
```
