### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/ip-masq-agent/

### ISSUE THREAD

**Issue by porrascarlos802018** [kubernetes/website#36984]
please add clarification in the case of containers, where are containers masq records saved or how to track down which container initiated a connection behind node ip

**Comment by mtardy** [comment]
Hey, I think this is not a support request, however, it would require more information.

Have you checked the [IP masq agent](https://github.com/kubernetes-sigs/ip-masq-agent) documentation as well that this page link to for more precise information on these topics?

**Comment by sftim** [comment]
If you can describe what you wanted when you wrote
> how to track down which container initiated a connection behind node ip

then @porrascarlos802018 we might be able to make that into a request to improve the documentation.
