### ISSUE TITLE
Duplicate words in securityContext

### ISSUE THREAD

**Issue by Santosh1176** [kubernetes/website#37046]
**This is a Bug Report**

**Problem:**
In **Configure volume permission** section of `securityContext`, while describing the `OnRootMismatch` value for `fsGroupChangePolicy` field, the words *permissions and ownership if* are repeated.
**Proposed Solution:**
Remove duplicate words.
**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

/assign

**Comment by shannonxtreme** [comment]
@Santosh1176 do you plan on creating a PR for this? 

/triage accepted
/sig docs
/language en

**Comment by Santosh1176** [comment]
> @Santosh1176 do you plan on creating a PR for this?
> 
> /triage accepted /sig docs /language en

Sure, I’ll raise an PR shortly. Thank you.

**Comment by Santosh1176** [comment]
@Pro-Coder04 I am working on this and have been assigned
>  I’ll raise an PR shortly. Thank you.
