### ISSUE TITLE
kube-apiserver

### ISSUE THREAD

**Issue by muyangren2** [kubernetes/website#37054]
<html>
<body>

https://kubernetes.io/zh-cn/docs/reference/command-line-tools-reference/kube-apiserver/

--service-account-issuer strings
--
  | 服务帐号令牌颁发者的标识符。 颁发者将在已办法令牌的 "iss" 声明中检查此标识符。 此值为字符串或 URI。 如果根据 OpenID Discovery 1.0 规范检查此选项不是有效的 URI，则即使特性门控设置为 true， ServiceAccountIssuerDiscovery 功能也将保持禁用状态。 强烈建议该值符合 OpenID 规范： https://openid.net/specs/openid-connect-discovery-1_0.html 。 实践中，这意味着 service-account-issuer 取值必须是 HTTPS URL。 还强烈建议此 URL 能够在 {service-account-issuer}/.well-known/openid-configuration 处提供 OpenID 发现文档。 当此值被多次指定时，第一次的值用于生成令牌，所有的值用于确定接受哪些发行人。

颁发者将在已“办法”令牌的  应该把办法改成 颁发

</body>
</html>

**Comment by sftim** [comment]
/language zh

I assume this is a bug report. If possible, clarify whether the issue is with the upstream (English) docs or with the way those docs have been localized.

/triage needs-information
