### ISSUE TITLE
Wrong command in “Using NodeLocal DNSCache in Kubernetes Clusters”

### ISSUE THREAD

**Issue by Unknown256** [kubernetes/website#37057]
1.25： 
```bash
sed -i "s/__PILLAR__LOCAL__DNS__/$localdns/g; s/__PILLAR__DNS__DOMAIN__/$domain/g; s/__PILLAR__DNS__SERVER__//g; s/__PILLAR__CLUSTER__DNS__/$kubedns/g" nodelocaldns.yaml
```

Prior to version 1.25： 
```bash
sed -i "s/__PILLAR__LOCAL__DNS__/$localdns/g; s/__PILLAR__DNS__DOMAIN__/$domain/g; s/,__PILLAR__DNS__SERVER__//g; s/__PILLAR__CLUSTER__DNS__/$kubedns/g" nodelocaldns.yaml
```

PS：`,` before __PILLAR__DNS__SERVER

if I use script from 1.25 to change `nodelocaldns.yaml`, the pod will crash, but if I use 1.24 version, it is done, so it seems like `,` is missing

**Comment by Shubham82** [comment]
Page: https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

**Comment by sftim** [comment]
/retitle Wrong command in “Using NodeLocal DNSCache in Kubernetes Clusters”

**Comment by sftim** [comment]
/language en
/kind bug

Seems valid.

**Comment by sftim** [comment]
@Unknown256 I edited the issue description to make it more readable.
