### ISSUE TITLE
[ko] Untranslated sentence in ko/"Deployments" page

### ISSUE THREAD

**Issue by gain-yoo** [kubernetes/website#37065]
**This is a Feature Request**

**What would you like to be added**

Translate /ko/docs/concepts/workloads/controllers/deployment/#이전-수정-버전으로-롤백 into Korean

**Why is this needed**
Not translated into Korean yet.

**Comments**

**Comment by jihoon-seo** [comment]
/retitle [ko] Untranslated sentence in ko/"Deployments" page
/triage accepted

**Comment by jihoon-seo** [comment]
Resolved by
- #37120
- #38192

Thanks!
/close
