### ISSUE TITLE
Markdown style missing on Advanced contributing page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#37066]
**Problem**:
The text **#sig-docs** on [link](https://kubernetes.io/docs/contribute/advanced/) is missing markdown style.
Check the page [Advanced Contributing](https://kubernetes.io/docs/contribute/advanced/) for the problem.

**Page to Update:**
https://kubernetes.io/docs/contribute/advanced/

**Proposed Solution:**
It should resolve this issue by adding a backtick symbol and enhancing the document line.
Add backtick to the text **#sig-docs** on [link](https://kubernetes.io/docs/contribute/advanced/).

/kind document
/assign
/language en

**Comment by sftim** [comment]
/priority awaiting-more-evidence

Why is this improvement worth making? Could it actually be a [trivial edit](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits) if we do?
/language en
