### ISSUE TITLE
Wrong command in kubectl delete doc

### ISSUE THREAD

**Issue by Dennis-Rall** [kubernetes/website#37077]
**This is a Bug Report**
The command in the example of the kubectl delete command is wrong:

**Problem:**
![image](https://user-images.githubusercontent.com/56480601/192981781-de5a0dc7-a7c4-45a3-b32f-edf407560c1b.png)

**Proposed Solution:**
kubectl delete -f '*.json'

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#delete

**Comment by shannonxtreme** [comment]
This is an auto-generated page that will require a PR in the corresponding kubernetes repo to update the upstream source file 

/kind bug

**Comment by Shubham82** [comment]
I think we have to update it here:
https://github.com/kubernetes/website/blob/main/static/docs/reference/generated/kubectl/kubectl-commands.html#L3034

PTAL!

**Comment by sftim** [comment]
As the URL hints, https://github.com/kubernetes/website/blob/main/static/docs/reference/generated/kubectl/kubectl-commands.html is a generated file. Also see https://github.com/kubernetes/website/issues/37077#issuecomment-1262172799

**Comment by Dennis-Rall** [comment]
It is fixed now!

![image](https://user-images.githubusercontent.com/56480601/195282668-0d7c6d5c-1788-412a-a548-2dd25c5c60bb.png)
