### ISSUE TITLE
Extra blank lines in a YAML example

### ISSUE THREAD

**Issue by windsonsea** [kubernetes/website#37088]
When syncing the file in #37087, find a YAML example has extra lines at: https://kubernetes.io/docs/tasks/job/pod-failure-policy/

Don't know how to fix it yet.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/79828097/193171283-b0eb6530-e28d-4c79-9579-3b5893b57096.png">

**Comment by Shubham82** [comment]
Hi @windsonsea 
Similar kind of  issues opened earlier, Here it is:

Some yaml examples have an extra blank line between every line #36813

debug-cluster/monitor-node-health: YAML file contains many empty lines #36361

Unwanted spaces in YAML file #36003

**Comment by Shubham82** [comment]
PR #36850 will resolve this issue.

**Comment by sftim** [comment]
Also see:

https://github.com/kubernetes/website/issues/36813
https://github.com/kubernetes/website/issues/36361
#36003

/remove-triage accepted
/triage duplicate

**Comment by Shubham82** [comment]
this issue is resolved by this PR: #36850, so closing this issue.
/close
