### ISSUE TITLE
Query about API versioning

### ISSUE THREAD

**Issue by jcookson-infoblox** [kubernetes/website#37084]
After reading this, am curious if this versioning scheme would fall within this ...
v1beta2alpha3
stable version : v1
beta code version : beta2
new alpha version on that branch : alpha3

**Comment by sftim** [comment]
/retitle Query about API versioning

I'm not really sure what improvement you're suggesting here @jcookson-infoblox 

Maybe you had a question you weren't able to answer?

/triage needs-information
/language en

**Comment by Kartik494** [comment]
@jcookson-infoblox PTAL here https://kubernetes.io/docs/reference/using-api/#api-versioning
