### ISSUE TITLE
Potentially stale: https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/

### ISSUE THREAD

**Issue by kdaula** [kubernetes/website#37109]
Per [Use a User Namespace With a Pod](https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/), https://github.com/kubernetes/enhancements/issues/127  is slated for 1.25 alpha. However, Kubernetes 1.25 is shipped. Seems like the doc or issue needs a revision.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/ states that the user namespace feature is alpha and first shipped in Kubernetes v1.25

Is that correct?

/language en
/priority awaiting-more-evidence
/sig node

**Comment by Shubham82** [comment]
> https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/ states that the user namespace feature is alpha and first shipped in Kubernetes v1.25
> 
> Is that correct?
> 

Hi @sftim, yes it is correct. Here is PR #35235 for it which merged in k8s v1.25

**Comment by Shubham82** [comment]
I think we can close this issue if there is no issue that needs to fix.
WDYT @sftim

**Comment by jpmcb** [comment]
We can close this: phase 1 of the implementation made it into k8s v1.25: https://github.com/kubernetes/kubernetes/pull/111090 so the `alpha` docs are valid

**Comment by sftim** [comment]
/close
/triage invalid
/remove-priority awaiting-more-evidence

Nothing to fix
