### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by JayeshVipparthi** [kubernetes/website#37100]
MiniKube version is not working sinc eit not installed properly

**Comment by JayeshVipparthi** [comment]
Okay

**Comment by utkarsh-singh1** [comment]
Hi @JayeshVipparthi, Can you elaborate your issue, is minikube not working with your current environment in the interactive tutorial?

/language en
/priority awaiting-more-evidence

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
