### ISSUE TITLE
Issue with concepts/workloads/controllers/cron-jobs/#prerequisites

### ISSUE THREAD

**Issue by joshrosso** [kubernetes/website#3710]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

In the prereqs section of CronJobs, adding the flag to the API server isn't enough if you're adding this to an existing cluster.

**Proposed Solution:**

We should note in the prereq section of CronJobs that if adding the `--runtime-config=batch/v2alpha1=true` to a running cluster, you *must restart your controller managers* along with the api server.

As mentioned in https://github.com/kubernetes/kubernetes/issues/35508#issuecomment-271494742

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#prerequisites

**Comment by ahmetb** [comment]
@joshrosso do you mind contributing a patch to the doc?

**Comment by manypozo** [comment]
I had this same issue and did the patch contribution to the doc. Waiting to be merged.

**Comment by tengqm** [comment]
Looks like the patch is still traveling in a wonderland.
