### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by KlockiLego** [kubernetes/website#37108]
This section:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroupfs-cgroup-driver

I would add information like here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/#configuring-the-kubelet-cgroup-driver

Note: In v1.22, if the user is not setting the cgroupDriver field under KubeletConfiguration, kubeadm will default it to systemd.

**Comment by neolit123** [comment]
this section already links to:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#migrating-to-the-systemd-driver-in-kubeadm-managed-clusters

already links to:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver

PRs welcome with proposed improvements.

/help
/sig cluster-lifecycle

**Comment by sftim** [comment]
If someone wants to help here, I'm not sure what steps they should follow to assist.
Because of that:
/remove-help

**Comment by mythi** [comment]
> Note: In v1.22, if the user is not setting the cgroupDriver field under KubeletConfiguration, kubeadm will default it to systemd.

I think the suggestion is to add something about `KubeletConfiguration` to container-runtimes pages but I don't think that fits well on that page because it only covers the container runtime side. What could be added though is that there's a note/reminder to ensure they are always the same. I can work on that if we agree what's what we want here.

**Comment by mythi** [comment]
> What could be added though is that there's a note/reminder to ensure they are always the same.

hmm, looks like this is already covered too.

**Comment by mythi** [comment]
some additional feedback in #36492
