### ISSUE TITLE
[ko] Translate `docs/concepts/security/security-checklist` to Korean

### ISSUE THREAD

**Issue by KimDoubleB** [kubernetes/website#37129]
**This is a Feature Request**

**What would you like to be added**

Translate `docs/concepts/security/security-checklist` to Korean
- https://kubernetes.io/docs/concepts/security/security-checklist/

**Why is this needed**

Not translated yet

**Comments**

/language ko
/assign

**Comment by seokho-son** [comment]
/triage accepted 

Thanks!

**Comment by seokho-son** [comment]
Hi @KimDoubleB :) 
I hope to check you are working on this issue since lifecycle/stale is applied. (you don't need to hurry on contribution. we can simply remove the tag if you are still interested)
