### ISSUE TITLE
Needs proper doc to FederatedReplicaSetPreference

### ISSUE THREAD

**Issue by henriquetruta** [kubernetes/website#3712]
ClusterReplicaSetPreferences docs point to a source code file in the main repo

This also happens in /docs/tasks/administer-federation/replicaset/

**Comment by jaredbhatti** [comment]
Do you mean FederatedReplicaSetPreference?  I can't find ClusterReplicaSetPreference

**Comment by henriquetruta** [comment]
@jaredbhatti exactly! FederatedReplicaSetPreference is correct. Sorry for it
