### ISSUE TITLE
Install and Set Up kubectl on macOS

### ISSUE THREAD

**Issue by EllaRaveala** [kubernetes/website#37136]
When running kubectl -commands, such as kubectl version, I suddenly started to get an error: Unable to connect to the server: net/http: TLS handshake timeout.

After tying everything else, I tried to install kubectl with homebrew again, but the same problem occurred. Client version was ok.

Current versions:
kubernetes-cli  is 1.25.2
Kustomize Version: v4.5.7

Any ideas what could be the reason? I am using Apple M1 Pro, macOS 12.6. With Kubernetes I am using
using docker desktop.

**Comment by utkarsh-singh1** [comment]
Hi @EllaRaveala, this can be a proxy error, you can try these commands - 
```
$ unset http_proxy
$ unset https_proxy
```
And try your kubectl call again.

Also, you can ask these support question on [serverfault](https://serverfault.com/?tags=kubernetes) .

**Comment by utkarsh-singh1** [comment]
Hi @EllaRaveala, has your issue has been resolved?

/triage needs-information

**Comment by sftim** [comment]
GitHub is not the right place for support requests.

If you're still looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close not-planned
