### ISSUE TITLE
TLS Secrets

### ISSUE THREAD

**Issue by carlin-q-scott** [kubernetes/website#37168]
I'm confused by the [documentation about creating a TLS secret](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) from a PEM cert. It states:
> Note:
A kubernetes.io/tls Secret stores the Base64-encoded DER data for keys and certificates. If you're familiar with PEM format for private keys and for certificates, the base64 data are the same as that format except that you omit the initial and the last lines that are used in PEM.
For example, for a certificate, you do not include --------BEGIN CERTIFICATE----- and -------END CERTIFICATE----.

But `kubectl create secret tls domain-cert --help` states:
> --cert='':
Path to PEM encoded public key certificate.

When I run the command, providing a PEM cert, it base64 encodes the PEM including the BEGIN and END lines. Which documentation is correct?

### Version
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0

**Comment by sftim** [comment]
I think this issue report duplicates https://github.com/kubernetes/website/issues/32869
/triage duplicate
/language en

**Comment by mehabhalodiya** [comment]
Let's shift the discussion to the issue mentioned in [this comment](https://github.com/kubernetes/website/issues/37168#issuecomment-1268985773).

@carlin-q-scott head over to the already opened issue, read the comments, and then put up your views there. Thanks!
/close
