### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by rjt65** [kubernetes/website#37164]
the interactive demo is bombing azat this step in module 2 - i am running Proxy  put Curl into proxy it runs on primary page but hangs doing nothing 

curl http://localhost:8001/version

Note: Check the top of the terminal. The proxy was run in a new tab (Terminal 2), and the recent commands were executed the original tab (Terminal 1). The proxy still runs in the second tab, and this allowed our curl command to work using localhost:8001.

If Port 8001 is not accessible, ensure that the kubectl proxy started above is running.

**Comment by utkarsh-singh1** [comment]
Hi @rjt65, Can you reload your interactive session if you can't get your result and check again because I am currently running the same command, and it is working for me.

`curl http://localhost:8001/version`

Output 
>{
  "major": "1",
  "minor": "20",
  "gitVersion": "v1.20.2",
  "gitCommit": "faecb196815e248d3ecfb03c680a4507229c2a56",
  "gitTreeState": "clean",
  "buildDate": "2021-01-13T13:20:00Z",
  "goVersion": "go1.15.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}

**Comment by rjt65** [comment]
> Hi @rjt65, Can you reload your interactive session if you can't get your result and check again because I am currently running the same command, and it is working for me.
> 
> `curl http://localhost:8001/version`
> 
> Output
> 
> > {
> > "major": "1",
> > "minor": "20",
> > "gitVersion": "v1.20.2",
> > "gitCommit": "faecb196815e248d3ecfb03c680a4507229c2a56",
> > "gitTreeState": "clean",
> > "buildDate": "2021-01-13T13:20:00Z",
> > "goVersion": "go1.15.5",
> > "compiler": "gc",
> > "platform": "linux/amd64"
> > }

going to retry today 
thks will update

**Comment by rjt65** [comment]
> 

weird got it working failed 2 more times so i reran the kubectl proxy command in 2nd terminal window and it properly restrted the proxy than the curl and bingo got the output it seems the proxy was opening but not running properly --thanks!

**Comment by utkarsh-singh1** [comment]
I think it was with the connectivity glitch, glad it got resolved.

/close

**Comment by utkarsh-singh1** [comment]
Hi @rjt65, if your issue has been resolved, can you close this issue?

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
