### ISSUE TITLE
Managing Service Accounts page states that token controller automatically creates Secret on ServiceAccount creation

### ISSUE THREAD

**Issue by dacamposol** [kubernetes/website#37181]
In the [documentation about Managing Service Accounts](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/access-authn-authz/service-accounts-admin.md), it says the following in about the Token Controller:

> watches ServiceAccount creation and creates a corresponding ServiceAccount token Secret to allow API access.

But that's not true from K8s version 1.24+, and the Secret has to be explicitly created if we want to issue a token for that Service Account.

I think that should be reflected in the documentation so it's easy to find on the official source, as the only sources which mention this case are external blogs.

- [x] I volunteer to do a PR regarding this as soon as I have some time.

**Comment by sftim** [comment]
/retitle Managing Service Accounts page states that token controller automatically creates Secret on ServiceAccount creation
/kind bug
/language en

@shannonxtreme did you have any work-in-progress that might help with this?

**Comment by sftim** [comment]
> the Secret has to be explicitly created if we want to issue a token for that Service Account

This isn't true, you can issue a token using the TokenRequest mechanism (which we need to document better).

**Comment by shannonxtreme** [comment]
Maybe we can go with something like this?

>In Kubernetes v1.21 and earlier, watches ServiceAccount creation and creates a corresponding ServiceAccount token Secret to allow API access. If you want to use a static Secret for tokens in v1.22 and later, you must manually create the Secret. The Kubernetes project recommends that you use the `TokenRequest` API for more secure credentials instead.

For the first bullet point in that list. 

WDYT Tim? I can add that to my WIP draft as well for the new concept
