### ISSUE TITLE
Update training to mention PCA

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#37190]
**This is a Feature Request**

**What would you like to be added**
As suggested in https://github.com/cncf/techdocs/issues/139:
* update the training page (https://kubernetes.io/training/) to include a reference to PCA (in the _Get Kubernetes Certified_ section): https://www.cncf.io/certification/pca/
* Update section name from "Get Kubernetes Certified" to "Get Kubernetes and Cloud Native Certifications"

**Why is this needed**

To increase awareness of related cloud native certifications

**Comment by thisisobate** [comment]
Would love to take on this issue. 
/assign me

**Comment by sftim** [comment]
The [content guide](https://kubernetes.io/docs/contribute/style/content-guide/#what-s-allowed) doesn't make it clear that this is or isn't OK, as the training page is outside of our docs.

It's a switch from the spirit of the content guide, though: previously, we explicitly didn't favor projects that were part of the LF / CNCF over other vendors' projects. If we're now doing that, I suggest we go through an enhancement proposal to make the new policy clear.

**Comment by sftim** [comment]
Maybe we change the top nav to take people to https://www.cncf.io/certification/training/#kubernetes and annotate the “Training” item with an icon to hint that it's an off-site link?

To make that work, we / CNCF could put some time into making https://www.cncf.io/certification/training/#kubernetes be a working fragment.

**Comment by thisisobate** [comment]
> Maybe we change the top nav to take people to https://www.cncf.io/certification/training/#kubernetes and annotate the “Training” item with an icon to hint that it's an off-site link?

Sounds like a good idea.
@nate-double-u @caniszczyk

**Comment by nate-double-u** [comment]
> Maybe we change the top nav to take people to https://www.cncf.io/certification/training/#kubernetes and annotate the “Training” item with an icon to hint that it's an off-site link?
> 
> To make that work, we / CNCF could put some time into making https://www.cncf.io/certification/training/#kubernetes be a working fragment.

Do you mean completely removing the https://kubernetes.io/training/ page, and linking the top nav to the cncf.io training site? (We'd have to update the cncf training page to include the #kubernetes anchor). I expect we'd need to work with the sig-docs chairs to approve, but I think this is an interesting idea. It also means that there is one less K8s website page to maintain.

**Comment by reylejano** [comment]
I would not classify this as a web development issue
