### ISSUE TITLE
Update community docs to include more Localization team information and details on the subproject 

### ISSUE THREAD

**Issue by a-mccarthy** [kubernetes/website#37200]
**This is a Feature Request**

Right now we have some basic information in the community repo for the Localization subproject, https://github.com/kubernetes/community/tree/master/sig-docs. This is where all SIGs list information about their SIG and subprojects.

I'd like to propose that we expand on the localization subproject content to be more like the Blog subproject docs, https://github.com/kubernetes/community/tree/master/sig-docs/blog-subproject. 

I'm making this issue here to get more visibility and discussion.

**What would you like to be added**
I think we should add:
* A list of all localization teams, their team leads, and how to get involves with each team. Some of this content is currently listed on the [README.md](https://github.com/kubernetes/community/tree/master/sig-docs) file, but i think it can be expended - 
* A description of roles for the subproject to help folks the role better. Right now this is Subproject lead

This would be in a new folder in the community repo (like the blog subproject). 

We have a lot of content already on how a localization team can form and run located on the website: https://kubernetes.io/docs/contribute/localization/. I'm not advocating for moving or duplicating it, more adding some complementary information around localization in the place where the community documents community roles and leaders.

**Why is this needed**
The localization teams are doing a lot of work, and I'd like to make sure that we have a place for localization teams to list their contact information. Additionally, I think we should have a place for localization leads to be listed as taking leadership positions within the community. 

This content will also make it easier to hand over leadership roles within the subproject, because roles will be defined. 

**Comments**

I think to do this we should make sure we have a solid definition for the roles within the localization subprojects and the localization teams. In terms of the localization teams, they often mirror the roles of the rest of SIG docs within the bounds of the localized content: being a reviewer, approver, team lead. But any differences should be noted.

**Comment by a-mccarthy** [comment]
Would appreciate feedback on this issue :)

**Comment by a-mccarthy** [comment]
/remove-lifecycle stale

Just created a PR for this in the community repo: https://github.com/kubernetes/community/pull/7026

**Comment by seokho-son** [comment]
By @a-mccarthy https://github.com/kubernetes/community/pull/7026 

Now we have the documentation for SIG-Docs Localization Subproject
https://github.com/kubernetes/community/tree/master/sig-docs/localization-subproject

Thanks!

/close
