### ISSUE TITLE
Feedback form on pages includes clicks from bots in Google Analytics

### ISSUE THREAD

**Issue by a-mccarthy** [kubernetes/website#37201]
**This is a Bug Report**

Looking at the data from out feedback form, it appears that a lot of data is from bots. Google Analytics has a way to filter bot activity, https://support.google.com/analytics/thread/16422940?hl=en. But we do not have that enabled

It looks like bot activity is turned off by default in the next version of Google Analytics, https://support.google.com/analytics/answer/9888366?hl=en. We are in the process of migrating to this version in https://github.com/kubernetes/website/issues/35299. 

**Problem:**

It looks like bot activity is throwing off users feedback in out feedback forms. For example, in the screen shot, this page has 41 response on the feedback form, but they are all from the same day.

<img width="1579" alt="Screen Shot 2022-10-06 at 11 01 36 AM" src="https://user-images.githubusercontent.com/20771501/194581419-17f5327f-eb33-4c93-bc69-402736a08bc0.png">

**Proposed Solution:**

Exclude bot data from the charts, https://support.google.com/analytics/answer/9888366?hl=en.

**Page to Update:**
This would be a change in Google Analytics.

**Comment by a-mccarthy** [comment]
also, feedback for is located on the bottom of doc pages: https://kubernetes.io/docs/tutorials/. and tracks "Was this page helpful".

Until we get the filtering figured out, we aren't able to accurately see if pages are helpful/unhelpful.

**Comment by a-mccarthy** [comment]
i tried adding the filter, but still saw the same results. Going to keep researching this to see if there is a better answer

**Comment by a-mccarthy** [comment]
Thanks @chalin!

**Comment by chalin** [comment]
This is still relevant. /cc @a-mccarthy
