### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by tobiasgbg** [kubernetes/website#37222]
"You need to have a Kubernetes cluster, and the kubectl command-line tool must be configured to communicate with your cluster."

Do I have to configure the kubectl command on the worker nodes?

**Comment by sftim** [comment]
/kind support

We could clarify that you don't need to install and configure `kubectl` on each node; however, this ought to be implied by the fact that we don't state it is needed. There is a very long list of things that readers _don't_ need to do to follow a page, and I'm wary of trying to list these.

/language en

**Comment by Kartik494** [comment]
IMO For worker nodes you just need to install both kubelet and kubeadm. kubectl is a CLI for controlling your cluster so you do not need to install it on the worker nodes.
