### ISSUE TITLE
why rpm repo not support redhat 8 and 9?

### ISSUE THREAD

**Issue by ycyxuehan** [kubernetes/website#37239]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**

**Comments**

**Comment by sftim** [comment]
/remove-kind feature

We document Kubernetes and its _existing_ behavior.
If you would like to ask for Kubernetes to publish RPM packages for RHEL 8 and RHEL 9, you can request this via 
https://github.com/kubernetes/release/issues

There may well be an existing issue to track this; in which case, you can give that issue a thumbs-up reaction to mean that you agree with it. Check https://github.com/kubernetes/release/issues?q=is%3Aissue+is%3Aopen+RPM and https://github.com/kubernetes/kubernetes/issues?q=is%3Aissue+is%3Aopen+RPM to look for issues on that topic.
