### ISSUE TITLE
Interactive Tutorial - Updating Your App

### ISSUE THREAD

**Issue by saksham31** [kubernetes/website#37238]
In Module 6 - (Updating Your App), I'm unable to interact with the terminal in order to get the hands on practise with kubernetes. Neither the zoom in and zoom out button button is working.

![Screenshot from 2022-10-09 23-57-55](https://user-images.githubusercontent.com/72609878/194773591-0de69c74-707b-47fa-8165-fb84f126f17a.png)

**Comment by utkarsh-singh1** [comment]
Hi @saksham31, There can be few reasons due to which your interactive tutorial not be working -

1. Network glitch - Just reload the current Kubernetes tutorial session 
2.  Browser Ad Blocker Extension enabled - Disable this extension, then reload your interactive session.

**Comment by utkarsh-singh1** [comment]
Hi @saksham31, if your issue has been resolved, can you close this issue.
