### ISSUE TITLE
Difficulty following some tutorials via interactive playground

### ISSUE THREAD

**Issue by hahamili** [kubernetes/website#37240]
i have installed k8s locally, so can also provide all txt tutorials without a interactive mode?
as for some network reason, it's hard for me to use the interactive mode.

**Comment by sftim** [comment]
> i have installed k8s locally, so can also provide all txt tutorials without a interactive mode?

_All_ our tutorials are designed to let you follow along locally. If you find a tutorial where that's not possible, please report what went wrong when you tried.

You might find that a corporate network filter or state-level censorship mechanism is preventing you from using the tutorials. If you'd like us to consider designing a workaround for that scenario, please file a specific feature request about that topic.

/priority awaiting-more-evidence

/retitle Difficulty following some tutorials via interactive playground

**Comment by hahamili** [comment]
Thanks for the reply. 

as many people know, it is hard to visit the google domain in china.

when i visit the website such as https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-interactive/ ,the js loading is alaways time out or 404, then i can not view the tutorial content.

i just want to view the tutorial content directly through a website like https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

**Comment by sftim** [comment]
We'd be happy to consider a feature request. We already adapted https://k8s.io/search to work even when Google is censored.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
