### ISSUE TITLE
Bolding style error in the line below the Static Pod section of the Pod page

### ISSUE THREAD

**Issue by LetFu** [kubernetes/website#37248]
**This is a Bug Report**

**Problem:**
There is a problem with the bold style in the line below the Static Pod of the Pod page.
**Proposed Solution:**
Maybe the original expectation was to bold "静态 Pod（Static Pod）"
**Page to Update:**
https://kubernetes.io/zh-cn/docs/concepts/workloads/pods/#static-pods

**Comment by utkarsh-singh1** [comment]
Hi @LetFu, there should be a space between bold static pod and the text - 

Original text - 
> **静态 Pod（Static Pod）**直接由特定节点上的 

Corrected- 
> **静态 Pod（Static Pod）** 直接由特定节点上的

**Comment by Sea-n** [comment]
Fixed in PR #37531.
/close
