### ISSUE TITLE
Spelling mistake in Traces For Kubernetes System Components page

### ISSUE THREAD

**Issue by having-dlrow** [kubernetes/website#37249]
What would you like to be added

The spelling of the receiver  i.e [reciever](https://kubernetes.io/docs/concepts/cluster-administration/system-traces/) is wrong

Why is this needed
Fix Spelling

Comments

/language en
/assign

**Comment by K0more** [comment]
can I work on this issue
/assign

**Comment by ankitsingh241** [comment]
Hi can I work on this ?

**Comment by jihoon-seo** [comment]
@ankitsingh241 actually, there already exists an open PR (#37250) that @having-dlrow opened.
/assign @having-dlrow

**Comment by ankitsingh241** [comment]
Ok, Should I unassign myself ?
