### ISSUE TITLE
Issue with /docs/getting-started-guides/centos/centos_manual_config/

### ISSUE THREAD

**Issue by johnappliedbb** [kubernetes/website#3725]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
In bullet item "Configure kubectl"

**Proposed Solution:**

Are these configuration actions to be take on the master only or also on the Minions?

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
Not sure, need tech clarification

**Comment by ahmetb** [comment]
@johnappliedbb you can apply `Configure kubectl` section if you're planning to use kubectl on all your minions. Ideally I think you should be installing kubectl only on the machine that you will manage your kubernetes cluster from.

I see the tutorial creates are `centos-master` host entry in /etc/hosts, so wherever that host entry is present (looks like it's added to all machines in the cluster) you can set up kubectl there. But if you're not going to use kubectl on all nodes (and you shouldn't), no need to install it everywhere.

If this explanation helped you understand, I appreciate if you contribute a patch to the tutorial to make it clearer for the next person. :)
