### ISSUE TITLE
Issue with /docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by sdanieru** [kubernetes/website#3726]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
```
$ kubectl create -f http://k8s.io/docs/tasks/access-application-cluster/frontend.yaml
service "frontend" created
error: error validating "http://k8s.io/docs/tasks/access-application-cluster/frontend.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
```

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
Can you give me some more context on this error?

**Comment by ahmetb** [comment]
@sdanieru your Kubernetes client is 1.6 and server is old (probably 1.5). Can you upgrade or download and edit the `frontend.yaml` to have `apiVersion: extensions/v1beta1` instead of `apps/v1beta1`?
