### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/dual-stack/

### ISSUE THREAD

**Issue by lolo32** [kubernetes/website#37260]
You write that it's needed to use an egress, or use ip-masq-agent to masquerade not public ipv6 routed address.

It's also possible, if using calico, to ask it to apply masquerade automatically, with:

```
kubectl -n kube-system patch ippools default-ipv6-ippool --type=merge --patch '{"spec":{"natOutgoing":true}}'
```

it will automatically apply some `iptable` rule in the `nat` table, like this one (took from my computer):
```
iptables -t nat -A cali-nat-outgoing -m comment --comment "cali:Ir_z2t1P6-CbTGdf" -m set --match-set cali60masq-ipam-pools src -m set ! --match-set cali60all-ipam-pools dst -j MASQUERADE --random-fully
```

**Comment by sftim** [comment]
The existing text says:
> If you want to enable egress traffic in order to reach off-cluster destinations (eg. the public Internet) from a Pod that uses non-publicly routable IPv6 addresses, you need to enable the Pod to use a publicly routed IPv6 address via a mechanism such as transparent proxying or IP masquerading.

This is correct. Using Calico to achieve that outcome qualifies as “enabling the Pod to use a publicly routed IPv6 address”. The docs seem correct; we don't need to mention all the possible ways to achieve that outcome.

I don't think anything needs fixing here @lolo32 

/language en
/priority awaiting-more-evidence

**Comment by lolo32** [comment]
In the first read, I understand that the IPv6 in the cluster can access directly internet (=are public, no private ipv6 prefix use). But you are right, this is written `a mechanism such as transparent proxying or IP masquerading.`

What put me in the wrong direction is the mention of:
> […] The [ip-masq-agent](https://github.com/kubernetes-sigs/ip-masq-agent) project supports IP masquerading on dual-stack clusters.

Maybe speaking about that there are some already integrated functions that exists…

**Comment by sftim** [comment]
Perhaps you can try to explain the (untrue) thing that you believed after reading the page @lolo32? If you can explain that, we can try to avoid giving a misleading impression.
