### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/

### ISSUE THREAD

**Issue by bavishal** [kubernetes/website#37269]
Documentation misses couple of major points which has caused many issues.
1. What exactly is [AdmissionController](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/)
2. The usage of flag "--admission-control-config-file", this AdmissionController, and the corresponding ```PodSecurity``` plugin
e.g: ```kube-apiserver --admission-control-config-file=/some/path/pod-security.yaml```.
3. No support for Different CRI Flavours' Implementation. For e.g: Rancher does not have a straight forward way of changing ```/etc/kubernetes/manifests/kube-apiserver.yaml```, as this file does not even exist for Rancher K3S implementation.

**Comment by sftim** [comment]
> What exactly is [AdmissionController](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/)

It feels like the clue is in the question.

The first link in k8s.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/ is to https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/
If you wish to, you can report an issue about https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/ and explain what parts of _that_ page you found difficult to understand.

> The usage of flag "--admission-control-config-file", this AdmissionController, and the corresponding PodSecurity plugin
e.g: kube-apiserver --admission-control-config-file=/some/path/pod-security.yaml.

That is a fair comment. We should improve https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/ to explain setting the `--admission-control-config-file` command line argument to the API server, and to state that you must make sure to enable the PodSecurity admission controller (it's enabled by default, but it doesn't hurt to check).

> No support for Different CRI Flavours' Implementation. For e.g: Rancher does not have a straight forward way of changing /etc/kubernetes/manifests/kube-apiserver.yaml, as this file does not even exist for Rancher K3S implementation.

You can use Pod Security Admission with any CRI implementation. However, if you are using a Kubernetes distribution or service that doesn't let you changes these settings, this documentation won't be relevant. Typically, you should read the docs for the distribution or service instead.

We won't update our docs to document restrictions that only exist in third-party software, even third-party software that is based on or includes Kubernetes.

**Comment by aramase** [comment]
/triage accepted

- we plan to bring this up in sig-auth meeting to discuss how we can better handle making enforce as default.
- Until the default discussion is done, this issue can be used to track for docs improvement as mentioned in @sftim's comment.

**Comment by sftim** [comment]
SIG Auth folks: what's your intent here?
