### ISSUE TITLE
Advice in “Configuring Redis using a ConfigMap” not quite correct

### ISSUE THREAD

**Issue by olekszhel** [kubernetes/website#37331]
```
The configuration values have not changed because the Pod needs to be restarted to grab updated values from associated ConfigMaps.
```
This is not correct really and leads to confusion. As configmap is mounted as a volume it automatically updates appropriate config file inside pod. But redis application itself is not configured to update config automatically. It really creates wrong imagination about core topic (configmap). That's why I believe redis is not a good example to demonstrate that configmap automatically updates config inside pod and it doesn't required pod recreation.

**Comment by Shubham82** [comment]
Page to update: https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/

**Comment by sftim** [comment]
/retitle Advice in “Configuring Redis using a ConfigMap” not quite correct
/language en

**Comment by sftim** [comment]
> The configuration values have not changed because the Pod needs to be restarted to grab updated values from associated ConfigMaps.

This sentence is _true_, but we could explain more about the context that makes it true.

**Comment by yashodhanmohan** [comment]
Would it help here to add an additional demonstration step that the underlying `redis.conf` did _indeed_ update but that the Redis configuration didn't change because it needs to restart to pick the new values? I can pick it up @sftim if the change is acceptable. Let me know if there might be a simpler update to this.
