### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by yanhao-pro** [kubernetes/website#37333]
> Max Unavailable
> .spec.strategy.rollingUpdate.maxUnavailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process. The value can be an absolute number (for example, 5) or a percentage of desired Pods (for example, 10%). The absolute number is calculated from percentage by rounding down. The value cannot be 0 if .spec.strategy.rollingUpdate.maxSurge is 0. The default value is 25%.

In this section, is `.spec.strategy.rollingUpdate.maxSurge` supposed to be `.spec.strategy.rollingUpdate. maxUnavailable `?

**Comment by jihoon-seo** [comment]
Link: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable

**Comment by yanhao-pro** [comment]
I misunderstood it. Thank you for your explanation, @utkarsh-singh1 !
