### ISSUE TITLE
Issue with /docs/getting-started-guides/dcos/

### ISSUE THREAD

**Issue by javajon** [kubernetes/website#3734]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

Instructions on this page say "dcos config prepend..."  My dcos command does not offer that option:

dcos config prepend package.sources https://github.com/mesosphere/multiverse/archive/version-1.x.zip
Command not recognized

Usage:
    dcos config --help
    dcos config --info
    dcos config --version
    dcos config set <name> <value>
    dcos config show [<name>]
    dcos config unset <name>
    dcos config validate

**Proposed Solution:**

Perhaps there is an alternative command?  I'm using the latest:

dcos --version
dcoscli.version=0.4.16
dcos.version=1.9.0
dcos.commit=0ce03387884523f02624d3fb56c7fbe2e06e181b
dcos.bootstrap-id=58fd0833ce81b6244fc73bf65b5deb43217b0bd7

**Page to Update:**
http://kubernetes.io/...

**Comment by jaredbhatti** [comment]
The problems of linking to another group's docs :(

Is there someone at Mesosphere we can talk to?

**Comment by ahmetb** [comment]
This doc did not get any updates within the past 1.5 years, it's no surprise it's broken. I think we should just remove this page. Thoughts @steveperry-53?
