### ISSUE TITLE
[ja] In-page links are not working etc in /ja/docs/tasks/debug/debug-application/debug-pods.md

### ISSUE THREAD

**Issue by t-inu** [kubernetes/website#37351]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/ja/docs/tasks/debug/debug-application/debug-pods/
There are 2 problems.
- In-page links in "問題の診断" section are not working.
- The following bold notation in "PodがPendingのまま" section is not effective.
  `**あなたが使用しているのはhostPort**です。`

**Proposed Solution:**
```
### Podのデバッグ
### レプリケーションコントローラーのデバッグ
### Serviceのデバッグ
```
↓
```
### Podのデバッグ {#debugging-pods}
### レプリケーションコントローラーのデバッグ {#debugging-replication-controllers}
### Serviceのデバッグ {#debugging-services}
```
And the following links should be translated into Japanese.
```
   * [Debugging Pods](#debugging-pods)
   * [Debugging Replication Controllers](#debugging-replication-controllers)
   * [Debugging Services](#debugging-services)
```
↓
```
   * [Podのデバッグ](#debugging-pods)
   * [レプリケーションコントローラーのデバッグ](#debugging-replication-controllers)
   * [Serviceのデバッグ](#debugging-services)
```

Regarding bold notation, put a space the end of the asterisk.
And it's better to bold including "です。".
```**あなたが使用しているのは`hostPort`**です。Podを`hostPort`にバインドすると、...```
↓
```**あなたが使用しているのは`hostPort`です。** Podを`hostPort`にバインドすると、...```

**Page to Update:**
https://kubernetes.io/ja/docs/tasks/debug/debug-application/debug-pods/

/language ja

**Comment by K0more** [comment]
can I work on this 
/assign

**Comment by K0more** [comment]
@t-inu hi, can you check if there is any more changes to be made.

**Comment by t-inu** [comment]
@K0more Thanks for creating a PR. I left comments in the PR.
