### ISSUE TITLE
Add information about MastOperator 

### ISSUE THREAD

**Issue by kivio** [kubernetes/website#37354]
Hi, we have build simplified method of building operators using Ansible - without image building (mostly). 
I propose to add link to documentation of our tool into https://kubernetes.io/docs/concepts/extend-kubernetes/operator/#writing-operator section. 

Our tool documentation for operators: https://docs.ansi.services/mast/user_guide/operator/
Main documentation: https://docs.ansi.services/mast/

**Comment by sftim** [comment]
/language en

/kind feature

Why should we make this change @kivio? I recommend always mentioning the “why” for a feature request issue.

**Comment by kivio** [comment]
Sure, it's valid question.

Why we build Mast and why it can be valuable for others?

We are building huge enterprise environments that connect kubernetes and not kubernetes based systems. As we i mean group of people for few companies. We decided to choose kubernetes as center of our operational management. To implement it we need to write new operators for managing such platforms. Best choice for performing actions in such circumstances is to choose ansible as code runner. However ansible-operator as part of operator-framework is not flexible enough for our code changes.
This makes us to decide to build simplified dynamic and declarative operator framework that will remove strong connection between code and handler definition. It's main goal of Mast. We do it as open source as we love open source.

We believe that others can have similar needs, I got feedback with few cases for that tool. It makes us feel we should share information about possibility to do this to wider audience, this page is best place for sharing such information.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sftim** [comment]
Anyone is welcome to work on this issue.

**Comment by vaibhav2107** [comment]
@kivio Is this issue resolved ?

**Comment by kivio** [comment]
Yes, not sure what issue is not closed, Mast is listed on Operator website.
