### ISSUE TITLE
Confusing punctuation in Kubernetes components page

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#37409]
**This is a Bug Report**

**Problem:**
`Kubernetes` spelling is misplaced as `kubernetes'` under [etcd](https://kubernetes.io/docs/concepts/overview/components/#etcd) section in [kubernetes components](https://kubernetes.io/docs/concepts/overview/components/).

**Proposed Solution:**
Remove `'` in word `kubernetes'` under [etcd](https://kubernetes.io/docs/concepts/overview/components/#etcd).
**Page to Update:**
https://kubernetes.io/docs/concepts/overview/components/

**Comment by sftim** [comment]
> Kubernetes'

This means “belonging to Kubernetes”. It's similar to “Tim's hat” or “Linus' computer”

I don't think we need to fix it. We could reword to make the meaning more clear to people not used to less common cases for possessive apostrophes.

/language en

**Comment by T-Lakshmi** [comment]
Hi @sftim 
Thanks for this information!
How about this.

> Consistent and highly-available key value store used as **backing store of Kubernetes** for all cluster data.

 If this seems good then I will update it. WDYT?

**Comment by sftim** [comment]
I'd be happy with that change.

**Comment by sftim** [comment]
/remove-kind bug
/triage accepted
/retitle Confusing punctuation in Kubernetes components page

**Comment by T-Lakshmi** [comment]
Fixed it here #37635

**Comment by T-Lakshmi** [comment]
Hi @sftim,

I raised PR for it #37635, Could you please take a look. so that it will merge soon.

**Comment by sftim** [comment]
I am happy for anyone to review PR https://github.com/kubernetes/website/pull/37635
