### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by rayarazan** [kubernetes/website#37417]
Hello;

the interactive terminal on the website https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/ 

is not working , its blank page , I am using google chrome 
![Uploading k.PNG…]()

**Comment by jihoon-seo** [comment]
If you are using ad blocker, try disable it and reload the page.

**Comment by Kartik494** [comment]
@rayarazan It's working fine could you please recheck  at your end,

**Comment by sftim** [comment]
This might be similar to issue #32832 

@rayarazan do you think this might have been caused by an ad blocker tool?

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
