### ISSUE TITLE
Configure Liveness, Readiness and Startup Probes confusing failureThreshold

### ISSUE THREAD

**Issue by LouisJULIEN** [kubernetes/website#37414]
`failureThreshold` definition in [configure-liveness-readiness-startup-probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes) is confusing and different than [Probe v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#probe-v1-core)

# configure-liveness-readiness-startup-probes
The definition is as follow

> failureThreshold: When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready. Defaults to 3. Minimum value is 1.

One could understand that when set to N, Kubernetes will need N+1 failures. It's true that it's written _try_ and not _retry_ but it's unclear whether the first probe failure counts.

# Probe v1 core

> Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.

Number of failure before probe is considered failed clear.

**Comment by sftim** [comment]
We could clarify that Kubernetes makes `failureThreshold` attempts to _restart_ a container, so there can be up to (`failureThreshold` + 1) total container starts, and that after this a failed probe counts as overall failure.

/language en

**Comment by sftim** [comment]
Largely duplicated by https://github.com/kubernetes/website/issues/37503

**Comment by tback** [comment]
Another aspect that this page is lacking is the following (moved over from #37503):
It'd be really great if the page about liveness, readiness & startup would clarify the behavior for failureThreshoulds.
Consider the following livenessProbe:

livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 30
  failureThreshold: 3

What is the minimal/maximal amount of time until the pod will restart?

Maximal case:
Will the kubelet spawn probes while it's waiting for a probe to respond? (restart after 3failures * 5s + 30s => 45s)?
Will it wait for the the first probe to fail and then spawn the next probe immediately after (restart after 3failuress * 30s => 90s)?

Minimal case should be clear (restart after 3failures * 5s => 15s).

**Comment by LouisJULIEN** [comment]
Solved by https://github.com/kubernetes/website/pull/37416
Thanks for your comments
