### ISSUE TITLE
[ko] Wrong translation of the term "cordoned"

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#37426]
Please note that:
**Contributor that opens a PR to resolve this issue should branch off the feature branch from `dev-1.25-ko.1`,
and set the merge target branch to `dev-1.25-ko.1` as well.**

---

**This is a Bug Report**

**Problem:**
In https://kubernetes.io/ko/docs/concepts/architecture/nodes/ ,
the term "cordoned" is translated as "코드화된", which is wrong.

**Proposed Solution:**
"코드화된" -> "통제된(cordoned)"

**Page to Update:**
https://kubernetes.io/ko/docs/concepts/architecture/nodes/

/language ko

**Comment by bishal7679** [comment]
triage/accepted

**Comment by seokho-son** [comment]
@jihoon-seo 

cordoned Node 를 통제된 노드라고 하면, 의미를 오해할 수 있을 것 같은 데 어떻게 생각하시나요?

Node unschedulable 에 해당하는 의미를 지니거나
`kubectl cordon $NODENAME` 인 것을 고려하면.
음차를 하는 것이 더 낫지 않을까 싶습니다.

**Comment by jihoon-seo** [comment]
@seokho-son 
음차를 한다면
- 'a cordoned Node' - 코돈된(cordoned) 노드 or 코돈(cordon)된 노드
- 'Since `node-1` is cordoned,' - `node-1`은 코돈되었으므로,
- 'Uncordon the node'
  - 노드를 언코돈한다 or 노드를 코돈 해제한다
  - (헤더로 쓰인 경우) 노드 언코돈하기 or 노드 코돈 해제하기
- ...

검색을 해 보니 이 단어를 번역하거나 음차하여 한국어로 표현한 사례가 없는 것 같아서
어떻게 하는 것이 좋을지 고민이 되네요.. ㅎㅎ

---

현재 'cordon'이 번역되어 들어가 있는 파일의 목록은 다음과 같습니다.
- content/ko/docs/concepts/architecture/nodes.md
- content/ko/docs/concepts/workloads/pods/disruptions.md
- content/ko/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md
- content/ko/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes.md
- content/ko/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd.md
- content/ko/docs/tutorials/stateful-application/zookeeper.md
- ~content/ko/docs/tasks/administer-cluster/migrating-from-dockershim/troubleshooting-cni-plugin-related-errors.md~ (아직 번역 파일 없음)
- ~content/ko/docs/tasks/job/pod-failure-policy.md~ (아직 번역 파일 없음)
- ~content/ko/docs/tasks/run-application/run-replicated-stateful-application.md~ (아직 번역 파일 없음)
- ~content/ko/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver.md~ (아직 번역 파일 없음)
