### ISSUE TITLE
Add Abbreviation for "containerized applications" in Glossary page and provide Hyperlink for the same in Components page.

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#37428]
**This is a Feature Request**

**What would you like to be added**

Add Abbreviation of **`containerized applications`** in [Glossary](https://kubernetes.io/docs/reference/glossary/?all=true#) as this word mentioned in [Components](https://kubernetes.io/docs/concepts/overview/components/). 

**Why is this needed**
This change will help to understand about **containerized applications** for the people who are unfamiliar with `container concepts`.

**Comments**
kind/feature

**Comment by sftim** [comment]
When you say ”abbreviation”, do you mean “explanation”?

We might like to borrow from https://glossary.cncf.io/containerization/ or https://glossary.cncf.io/containers/

We also already have https://kubernetes.io/docs/reference/glossary/?all=true#term-container - maybe we can expand that?

/language en

**Comment by T-Lakshmi** [comment]
Hi @sftim,

> When you say ”abbreviation”, do you mean “explanation”?

Yes, basic Explanation/information about `containerized applications`. 

> We also already have https://kubernetes.io/docs/reference/glossary/?all=true#term-container - maybe we can expand that?

Yes, my idea is same to expand this by adding about `containerized applications`. WDYT?

> We might like to borrow from https://glossary.cncf.io/containerization/ or https://glossary.cncf.io/containers/

   If you think it's better to borrow from here, i can follow the same.

Please provide your opinion.

**Comment by T-Lakshmi** [comment]
Hi @sftim,

Can you please comment on above.

**Comment by sftim** [comment]
I recommend expanding https://kubernetes.io/docs/reference/glossary/?all=true#term-container rather than adding a new entry for “containerized application”.

I don't mind whether or not you borrow from the Cloud Native Glossary - feel free to do it whichever way you prefer.

**Comment by T-Lakshmi** [comment]
> I recommend expanding https://kubernetes.io/docs/reference/glossary/?all=true#term-container rather than adding a new entry for “containerized application”.
> 
> I don't mind whether or not you borrow from the Cloud Native Glossary - feel free to do it whichever way you prefer.

Thanks @sftim for your comment, I will work on it and raise PR soon.

**Comment by T-Lakshmi** [comment]
Fixed it here #37812.

**Comment by sftim** [comment]
Should we make this change? Any objections?

**Comment by shurup** [comment]
> Should we make this change? Any objections?

Personally, I like what's done here, and I was just waiting for someone with "better experience" in the glossary entries to approve it.

**Comment by T-Lakshmi** [comment]
Hi @shurup,
Thanks for sharing your feedback.

> Should we make this change? Any objections?
Can anyone else please comment on it.
