### ISSUE TITLE
Interactive Tutorial - Creating a Cluster - won't run from Linux "screen too narrow"

### ISSUE THREAD

**Issue by cjoprey** [kubernetes/website#37431]
I'm running on Ubuntu 22.04 on a Dell laptop. I have two external monitors connected, running at 1920x1080. I've tried to run this tutorial in Edge, Chromium and Firefox, and they all fail the same way:

![screenshot](https://user-images.githubusercontent.com/14791109/197174224-3f4f7604-c1e0-4862-a4e1-df790317b2a6.png)

This is happening on https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by cjoprey** [comment]
Adding comment - I can click to connect, even with the warning, but the terminal will not do anything.

**Comment by sftim** [comment]
I can replicate this.

/kind bug
/area web-development

**Comment by sftim** [comment]
Thanks for reporting this @cjoprey

It works fine on a 2160p screen; however, we can't assume that everyone has one of those.

**Comment by sftim** [comment]
This also reminds me of https://github.com/kubernetes/website/issues/34908

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/37711

**Comment by utkarsh-singh1** [comment]
@sftim @cjoprey, there is an issue of error text - `The screen is too narrow to interact with the Terminal, please use a desktop/tablet.` but I can interact with the terminal.

**Comment by cjoprey** [comment]
I just re-checked on the same machine using the same browser, and it still gives the error message but the terminal is now indeed functional. :)

**Comment by nikitar** [comment]
The tutorial appears to work at any reasonable screen resolution, including on my phone. Though scrolling does become wonky when it switches from left-right to top-bottom split.

![IMG_9864](https://user-images.githubusercontent.com/396798/206107887-67293481-07c6-45e7-bbe4-4939957511c3.PNG)

I am tempted to [remove](https://github.com/kubernetes/website/blob/5888082a2f7cacb39f02f1ddc6f0299cdbdb7386/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html#L21-L23) the message. Can't be 100% certain, but I suspect katacoda__alert is a deprecated feature, something they used before they added the narrow-screen layout. I.e. it used to be shown conditionally. And now it adds nothing except mild confusion.

@sftim What do you think?

**Comment by sftim** [comment]
/remove-priority important-soon

in light of https://github.com/kubernetes/website/issues/33936#issuecomment-1346832443
