### ISSUE TITLE
Add editable version of docs images

### ISSUE THREAD

**Issue by mboukhalfa** [kubernetes/website#37455]
**This is a Feature Request**

**What would you like to be added**
As a contributor to docs localization I would like to have an editable version of image so I can translate it without need to recreate the diagram from scratch. 

**Why is this needed**
Not all SVG images have text editable and due to the requirement to reflect the translated docs text, images need to be translated as well. But since some SVG images do not have an editable text it is not possible to translate them without redrawing the content from scratch which is not convenient. 

**Comments**
e.g. https://kubernetes.io/docs/concepts/overview/#going-back-in-time

**Comment by tengqm** [comment]
There isn't a simple way to add back the original SVG source for existing SVG images. Probably we have to create new SVG files for these images.

**Comment by sftim** [comment]
@mboukhalfa what scope did you want for this issue:
- all raster images on the website
- just some of those images

If the scope is for all of the raster images, we'd probably treat this as an umbrella (overall) issue, and then file issues for making (or tracking down) vector versions of specific images.

**Comment by sftim** [comment]
The image in https://kubernetes.io/docs/concepts/overview/#going-back-in-time doesn't have editable text. You can however load it into a vector editor and type in new text, deleting what is already there.

**Comment by sftim** [comment]
I used Git to look at the history of this diagram. It looks as if it was added in https://github.com/kubernetes/website/pull/555 and was later edited to use the Calibri typeface.

If editing it, try to use Open Sans.

**Comment by mboukhalfa** [comment]
> @mboukhalfa what scope did you want for this issue:
> 
>     * all images on the website that don't have editable text
> 
>     * all raster images on the website
> 
>     * just some of those images
> 
> 
> If the scope is for all of the images that don't have editable text, we'd probably treat this as an umbrella (overall) issue, and then file issues for making (or tracking down) vector versions of specific images.

Umbrella issue sound good

**Comment by mboukhalfa** [comment]
> The image in https://kubernetes.io/docs/concepts/overview/#going-back-in-time doesn't have editable text. You can however load it into a vector editor and type in new text, deleting what is already there.

you mean just erase the old text and insert editable text which tools you recommend would be great if we have something online

**Comment by mboukhalfa** [comment]
> I used Git to look at the history of this diagram. It looks as if it was added in #555 and was later edited to use the Calibri typeface.
> 
> If editing it, try to use Open Sans.

For me, I would use this diagram in new ar localization so I would use a different font

**Comment by sftim** [comment]
The tool _I_ use to edit SVG images is [Inkscape](https://inkscape.org/), which is open source donationware. Any other tool that talks SVG is also viable.

**Comment by a-mccarthy** [comment]
/area localization

I'm not overly familiar with the images/diagrams on the site. Some questions i have around this:
* Do we have an idea of how many images will need to be updated? Is there an easy way to get a list of all the to update? Or is the "best" way to manually review the images that we should update
* Are you able to localize mermaid diagrams? (more info on [mermaid diagramming](https://kubernetes.io/docs/contribute/style/diagram-guide/) for context)

**Comment by stormqueen1990** [comment]
I'm able to edit text on a copy of an SVG image using a regular text editor. Is this an acceptable way of localizing SVG graphics from the website?

**Comment by stormqueen1990** [comment]
> I guess this one https://kubernetes.io/docs/concepts/overview/#going-back-in-time is not editable as you confirmed on slack discussion https://kubernetes.slack.com/archives/C1J0BPD2M/p1686152844473749?thread_ts=1686074817.552909&cid=C1J0BPD2M

Perhaps we could replace SVG images that don't have editable text nodes for ones that do. That would enable us to localize specific images in the website.

I'm not super experienced with Mermaid diagrams, but in my (limited) previous experience I was able to edit text inside of those as well.
