### ISSUE TITLE
Advisory note to be displayed when the search functionality defaults to Bing instead of Google

### ISSUE THREAD

**Issue by rhinck** [kubernetes/website#37451]
If you use the search functionality on the website and type in `persistent volumes` then the results will populate with identical entries. The results only differ slightly by the query parameters in the URL.

It appears that links with query parameters like `ref` are being included in search results and leading to duplicate results.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/37898062/197369782-f996ae50-ffbb-4d0c-af71-528208fd94f0.png">

**Comment by jihoon-seo** [comment]
I tried to reproduce this but couldn't; the search results of mine is different from yours:

https://kubernetes.io/search/?q=persistent%20volumes
![image](https://user-images.githubusercontent.com/46767780/197431260-3ba44682-69c0-47d8-8745-cf59fb2ef2f3.png)

Locale of my env:
- Windows 10 64bit ko_KR
- Google Chrome 106.0.5249.119 64bit ko_KR

**Comment by Shubham82** [comment]
Hi @rhinck 
I also tried this one, but for me, it is not reproducible. Below is the screenshot of the search:
https://kubernetes.io/search/?q=persistent%20volumes
![Screenshot from 2022-10-24 12-53-51](https://user-images.githubusercontent.com/50987400/197470446-11454e7d-2bcd-4124-a60d-8635df8faa0c.png)

Could you please check it again?

**Comment by sftim** [comment]
/retitle Query parameters included in search results when Bing search used

We fall back to Bing search. However, Bing search is not as good as Google at indexing websites where different query strings might be used. I think that explains the symptoms.

**Comment by sftim** [comment]
Maybe we can find an API-based search service that offers effective indexing when they crawl the site.

**Comment by rhinck** [comment]
> Hi @rhinck 
> 
> I also tried this one, but for me, it is not reproducible. Below is the screenshot of the search:
> 
> https://kubernetes.io/search/?q=persistent%20volumes
> 
> ![Screenshot from 2022-10-24 12-53-51](https://user-images.githubusercontent.com/50987400/197470446-11454e7d-2bcd-4124-a60d-8635df8faa0c.png)
> 
> 
> 
> Could you please check it again?

@sftim mentioned that the search falls back to Bing. Does that mean      that Bing is only used if there is an issue with the internal search mechanism for the documentation website?

If so, I'm assuming that's why others are unable to replicate the issue

**Comment by sftim** [comment]
The search falls back to Bing in the case of:
- state level censorship (countries that don't let their citizens access web search outside their borders)
- use behind a corporate network filter that blocks access to Google
- some rather vigorous ad blockers (Google run an ad network)

**Comment by rhinck** [comment]
Got it.

Makes sense now as I'm using Firefox 106.0.1 (64-bit) with uBlock Origin

**Comment by sftim** [comment]
We could also add advice to readers if we detect that something is blocking the Google Search results from loading, to explain why the search isn't as good as we'd hope.

**Comment by Shubham82** [comment]
> We could also add advice to readers if we detect that something is blocking the Google Search results from loading, to explain why the search isn't as good as we'd hope.

@sftim as it is working fine, should we still want to add the above advice?
your thoughts?

**Comment by sftim** [comment]
> as it is working fine, should we still want to add the above advice?

Yes. But: this issue is about query parameters, not advice. Following my suggestion would have helped with _triage_ for this issue, not with a fix.

**Comment by divya-mohan0209** [comment]
> We could also add advice to readers if we detect that something is blocking the Google Search results from loading, to explain why the search isn't as good as we'd hope.

@sftim would this mean an advisory/note somewhere in our documentation? It wouldn't be a fix, like you said, but more of a "hey, we know it's not as great as we expected under the given conditions but this is the best we can do."

**Comment by sftim** [comment]
> would this mean an advisory/note somewhere in our documentation? It wouldn't be a fix, like you said, but more of a "hey, we know it's not as great as we expected under the given conditions but this is the best we can do."

What I imagined is that when the page can't show Google Search, and Bing shows up instead, we add a note about why. I imagine the note needs to be neutral; we don't _know_ that Google Search is blocked due to censorship, and there will be geopolitics around explaining that detail.

We don't need to show the note under other circumstances. Someone who has full access to the public internet would never see it.

**Comment by divya-mohan0209** [comment]
So, we'll need to detect if the browser falls under any of the categories mentioned [here](https://github.com/kubernetes/website/issues/37451#issuecomment-1289486631) and then show the message, right? Are there any other circumstances under which it would default to Bing, by any chance?

**Comment by sftim** [comment]
(I haven't looked in detail at how we choose to switch to Bing. I know there's some code and I think we rely on a geolocation service to help us pick.)

**Comment by divya-mohan0209** [comment]
To anyone picking up the issue:

- Please read [this comment](https://github.com/kubernetes/website/issues/37451#issuecomment-1289486631) for context on why the search functionality defaults to Bing.
- Please read [the description of the issue](https://github.com/kubernetes/website/issues/37451#issue-1419597750) for context on what happens when this default switch happens.
- [This comment](https://github.com/kubernetes/website/issues/37451#issuecomment-1840736923) provides details on the file that contains the code for finding out the geolocation. This file was introduced in PR #9845. 

What you need to do: 
- When the switch happens to Bing's search engine, based on the above file, we need an advisory note to be displayed on the search results page stating the reason.

**Comment by coder12git** [comment]
I have created a [PR](https://github.com/kubernetes/website/pull/44463) for this. Will be great if someone can review :)

**Comment by sftim** [comment]
We're considering dropping Bing; see https://github.com/kubernetes/website/issues/44475

(We only use Bing because of state-level censorship that blocks Google).

**Comment by coder12git** [comment]
This means that now there is no use of this [PR](https://github.com/kubernetes/website/pull/44463)

**Comment by sftim** [comment]
We no longer use Bing search

/close not-planned
