### ISSUE TITLE
Improper case usage on Titles and Headings

### ISSUE THREAD

**Issue by chrisnegus** [kubernetes/website#37487]
**This is a Bug Report**

Use of upper and lower case for titles and headings in Kubernetes documentation is inconsistent. Here are examples of how case should be handled in Titles, Headings, and when referring to those items in text, from the K8s [Documentation Style Guide](https://kubernetes.io/docs/contribute/style/style-guide/):

* **Titles**: Use title case for titles. For example, "Kubernetes API Server Bypass Risks". A title refers only to text on the "title:" line at the top of docs pages. For example:
   ```
   title: Kubernetes API Server Bypass Risks
   description: >
     Security architecture information relating to the API server and other components
   content_type: concept
   ---
   ```
* **Headings**: 
   * For headings themselves, use sentence case. For example, the heading "Where certificates are stored".
   * In text: Use sentence case for referencing to Headings or Titles in the page body. For example, use "Extend kubectl with plugins" in the text when referring to a title "Extend Kubectl With Plugins".

**Proposed solution:**
Fix pages that do not follow these standards.

**Pages to update:**
Find pages that do not follow these capitalizaion standards and point your PRs you create on this subject to this issue.

See [PR #35990](https://github.com/kubernetes/website/pull/35990) for a discussion of this topic.

**Comment by sreekaransrinath** [comment]
/assign

I'd like to take over this!

**Comment by sreekaransrinath** [comment]
Question:

Which title case guideline are we using? There are a bunch (NYT, AP, APA, etc) that differ very slightly. @natalisucks suggests Google's Title Case style guide (which I'm unable to find)

I suggest going with NYT or AP.

@shannonxtreme would like to get your eyes on this.

**Comment by shivaylamba** [comment]
I agree with @sreekaransrinath +1

**Comment by sreekaransrinath** [comment]
Once we figure this out, I'll submit a PR to codify this in the style guide.

**Comment by shannonxtreme** [comment]
> Question:
> 
> Which title case guideline are we using? There are a bunch (NYT, AP, APA, etc) that differ very slightly. @natalisucks suggests Google's Title Case style guide (which I'm unable to find)
> 
> I suggest going with NYT or AP.
> 
> @shannonxtreme would like to get your eyes on this.
> 
> 

https://developers.google.com/style/headings is the Google title case guidance in the developer docs style guide. 

Before we fix pages, we need to have a discussion about whether we want to change our style guidance to use sentence case in titles. We currently say to use title case in titles. 

I did a small poll in a sig docs slack standup and got positive results for switching our guideline to sentence case for all. However we should have a broader discussion and involve more of the community in that decision, if possible. 

I propose using sentence case for headings and titles across our docs. My reasoning is:

1. It'll be easier to remember one convention vs two for authors, so less friction in reviews
1. Title casing is hard! I still have trouble figuring out what words to caps and what not to. 
1. It'll simplify our style guide and improve new contributor experience
1. It'll keep consistency with technical docs in cloud providers. [AWS](docs.aws.amazon.com/eks/latest/userguide/), [Microsoft](https://learn.microsoft.com/en-us/style-guide/capitalization#sentence-style-capitalization-in-titles-and-headings), and [Google](https://developers.google.com/style/headings) all use sentence-style in headings and titles. 

cc @natalisucks , @sftim , @reylejano , @divya-mohan0209 as well for discussion

**Comment by divya-mohan0209** [comment]
@shannonxtreme I agree with your reasoning. However, in addition to the style guide amendment, I suggest we codify the check for this. There are two reasons for this:
- We can avoid any trivial edits being made specifically wrt casing.
- We can ensure that proper sentence casing is followed for future PRs.

I'm curious to see what other people think of this.

**Comment by shannonxtreme** [comment]
@divya-mohan0209 I'm not sure what "codify" means in this context, sorry! Do you mean to make it part of the PR reviewer's checklist?

/remove-lifecycle stale

**Comment by divya-mohan0209** [comment]
By codify, I mean to include it in PROW, possibly, for automating it. I'm assuming that's where we need to include it and not GH Actions.

**Comment by shannonxtreme** [comment]
> By codify, I mean to include it in PROW, possibly, for automating it. I'm assuming that's where we need to include it and not GH Actions.

Ooh, that'd be awesome! I guess prow could check for only the title being changed? @sftim prob has allll the answers

**Comment by shannonxtreme** [comment]
> > > By codify, I mean to include it in PROW, possibly, for automating it. I'm assuming that's where we need to include it and not GH Actions.
> > 
> > Ooh, that'd be awesome! I guess prow could check for only the title being changed? @sftim prob has allll the answers
> 
> My idea was to codify that check for every PR submitted - new content/old content/whatever. The casing needs to be adhered to; otherwise, it'll fail. 

I see what you mean. I wonder if that's possible since API names like "Secrets" and proper nouns would still need caps?

**Comment by sftim** [comment]
I think it's hard to check for sentence case, but it's perhaps easier to spot that a sentence is all first-letter-capitalized (title case)? Maybe with a minimum word count?

**Comment by shannonxtreme** [comment]
> I think it's hard to check for sentence case, but it's perhaps easier to spot that a sentence is all first-letter-capitalized (title case)? Maybe with a minimum word count?

I don't know that that would work in either case, since not every word in title case would be capitalized. I wonder if it could be a Prow message that reminds assigned reviewers to spot check the title for casing?
