### ISSUE TITLE
Autogenerator code update in k/website for page weight issues

### ISSUE THREAD

**Issue by natalisucks** [kubernetes/website#37486]
**This is a Feature Request**

During the KubeCon/CloudNativeCon NA 2022 SIG Docs sprint, a group of enthusiastic contributors worked on updating page weights as per the following bug report: Issue #35093. Our standard is that page weights are included in increments of 10 (10, 20, 30, etc.).

However, some of the pages that needed updating are auto-generated, which @sftim helpfully informed us of. After some discussion during the sprint and in [the following Slack thread](https://kubernetes.slack.com/archives/C1J0BPD2M/p1666628041706409?thread_ts=1666623272.645319&cid=C1J0BPD2M), it's been deemed worthwhile for us to update the page generator to produce our preferred values instead.

The generator code can be found here: [website/update-imported-docs/update-imported-docs.py](https://github.com/kubernetes/website/blob/main/update-imported-docs/update-imported-docs.py)

**Why is this needed**

We need this to be updated so that page weights for auto-generated docs are following the standard that we're setting across docs. This is also worth prioritizing before the 1.26 release, thus is a high priority (and needs to be tracked by the Release 1.26 team).

/sig docs

**Comment by a-mccarthy** [comment]
I also wanted to add a note that the new page https://github.com/kubernetes/website/blob/main/content/en/docs/reference/instrumentation/metrics.md does not have a page weight. It's the only page in that folder, but we should add a weight to the page to make sure we are following a new guidelines. This is a different autogenerated file than the reference/kubernetes-api docs, so it will need to be updated in a different place.

If we want I can open a separate issue about updating the page weight on this page. But i wanted to at least make a quick note about it while reviewing the remaining work for #35093

**Comment by a-mccarthy** [comment]
I was going through the reference folder and tried to make a list of all the autogenerated pages that need page weight changes. I'm not sure where all these pages are generated from however.

List of auto-generated pages that need page weights updates:
* https://github.com/kubernetes/website/tree/main/content/en/docs/reference/kubernetes-api All the folders and files in the folders are autogenerated (except the _index.md file) and should have the weights adjusted from using single digits to tens. For example, change weights of 1,2,3,4 to 10,20,30,40. 
* /reference/command-line-tools-reference All these pages are in the same folder and have a page weight of 30
  * https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/kube-apiserver.md 
  * https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/kube-controller-manager.md 
  * https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/kube-proxy.md
  * https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/kube-scheduler.md
 * https://github.com/kubernetes/website/tree/main/content/en/docs/reference/config-api These pages do not have page weights. 
* https://github.com/kubernetes/website/blob/main/content/en/docs/reference/instrumentation/metrics.md: Needs page weight (my previous comment also talks about this page)

**Comment by tengqm** [comment]
@a-mccarthy I'll take a look at the page weight issue. There is a manually maintained index page for the config APIs, so page weights there don't matter that much. I'll check the command line tools references.

**Comment by a-mccarthy** [comment]
@tengqm, following up here, did you get a chance to look into this? thanks!

**Comment by tengqm** [comment]
For command line tools (aka, kubernetes components), I'm not sure which order is better. Maybe the default order (sorting the reference by component names) is already good enough? That means we can remove the `weight` or assign the same `weight` value.

**Comment by tengqm** [comment]
@a-mccarthy I was talking about this page https://kubernetes.io/docs/reference/command-line-tools-reference/. The collection of the pages under that directory is stable.

> For the files under /reference/command-line-tools-reference, they all have a page weight of 30 ..

This is not an issue IMO. I don't think any localization team would translate `kube-apiserver.md` into something else. The file name is the binary name and the binary name is always the same across all languages.

**Comment by sftim** [comment]
There is https://kubernetes.io/ko/docs/reference/command-line-tools-reference/kube-proxy/ as an example. The weights being the same is a small issue because the names of these tools don't get localized.

**Comment by a-mccarthy** [comment]
@sftim and @tengqm thanks for explaining! If those pages titles aren't going to be changed, then its probably a low priority to change the page weights. 

Is that true for the other sections of the reference section? Looking at the config-api section in english https://kubernetes.io/docs/reference/config-api/ and chinese https://kubernetes.io/zh-cn/docs/reference/config-api/, some of the page titles are localized and the page ordering is different because those pages dont have page weights.

**Comment by tengqm** [comment]
It is probably true for other localization that the ordering of the reference pages are not consistent across languages, but I don't think that is an important issue. There is no inherent order among these reference pages anyway.

**Comment by sftim** [comment]
Are we happy to drop this to important-longterm priority? It feels lower priority than some of the other important-soon issues.

**Comment by a-mccarthy** [comment]
@sftim I think it's ok to move down in priority as long as all the changes needed in this section are in autogenerated code. 

This seem like a good candidate to break up into "good first issues" because they are relatively small updates (i believe). But we need to have a clear way to point folks to the changes that need to be made. Do you think a tech lead or someone more familiar with the code base need to make these changes?

**Comment by sftim** [comment]
//remove-priority important-soon
/priority backlog
/triage accepted
