### ISSUE TITLE
Create a concept doc for Projected Volumes

### ISSUE THREAD

**Issue by jaredbhatti** [kubernetes/website#3749]
**Problem:**
There are a few tasks that talk about projected volumes:
https://kubernetes.io/docs/tasks/configure-pod-container/projected-volume/

but the only concepts doc available is the community-proposed design doc: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/all-in-one-volume.md

**Proposed Solution:**
Convert the community doc into a proper concepts docs on kubernetes.io.

**Comment by jseldess** [comment]
For now, in https://github.com/kubernetes/kubernetes.github.io/pull/3771, I've listed the `projected` volume type on the volumes concept page.

**Comment by tengqm** [comment]
issue addressed in #3856
