### ISSUE TITLE
Table in admonition block does not work

### ISSUE THREAD

**Issue by yukiiiteru** [kubernetes/website#37500]
**Problem:**

![image](https://user-images.githubusercontent.com/37299119/197666068-911d61f4-d672-470a-a788-22e9cf4d51cd.png)

**Proposed Solution:**

I have no idea because I have never used Hugo 😢

**Page to Update:**

- https://kubernetes.io/docs/test/
- https://github.com/kubernetes/website/blob/main/content/en/docs/test.md

**Comment by AhmedGrati** [comment]
Can I take care of it?

**Comment by adityasamant25** [comment]
I have raised a [post](https://discourse.gohugo.io/t/tables-inside-a-notes-sidebar-are-not-rendered-correctly/47537) for support in the Hugo forums.

**Comment by adityasamant25** [comment]
There is an answer on the Hugo forum stating that this is not a Hugo issue. The suggestions is to fix the CSS. Any pointers?
