### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/update/update-intro/

### ISSUE THREAD

**Issue by nfrik** [kubernetes/website#37512]
I was looking for documentation, not an interactive tutorial.

**Comment by RA489** [comment]
@nfrik do you mind explaining it in bit more details what is the issue you're facing?

**Comment by T-Lakshmi** [comment]
Page related to issue opened: https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/
@nfrik,
You can follow the guidelines which are available in the interactive session for brief explanation.
Also you can find documentation on `Perform a Rolling Update and Rollback for Daemonset` [here ](https://kubernetes.io/docs/tasks/manage-daemon/) which can help for more understanding the concept of `Performing a Rolling Update`.

**Comment by T-Lakshmi** [comment]
**`Page related to issue opened`**: https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/
@nfrik,
You can follow the guidelines which are available in the interactive session for brief explanation.
Also you can find documentation on `Perform a Rolling Update and Rollback for Daemonset` [here ](https://kubernetes.io/docs/tasks/manage-daemon/)which can help for more understanding the concept of `Performing a Rolling Update`.

**Comment by manudev-1** [comment]
Is this still an issue?

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
