### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/kubelet.md

### ISSUE THREAD

**Issue by bishal7679** [kubernetes/website#37515]
### Prerequisites:

- If this is your first contribution, visit [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) for information on how to get started.
- Review a few https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859 to see which 
  content you have to change and which you leave unchanged.

### Procedure:

- Make sure your base, target branch is `main` and create a working branch called `hi-kubelet.md`.
- Create a file called content/hi/docs/reference/glossary/kubelet.md.
- Copy the content of 
  https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/kubelet.md to the 
  file you created
- Localize the content.
- Push your change and create a pull request.

Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/35600

> **Note**:- Don't forget to join [`slack`](https://communityinviter.com/apps/kubernetes/community) `kubernetes-docs-hi` channel if facing any problem!
 

/language hi
/triage accepted

**Comment by Aayush987** [comment]
HI @vaibhav2107 , are you still working on this issue?

**Comment by vaibhav2107** [comment]
@Aayush987 I have opened a PR #37532 for this issue that will close this

**Comment by Aayush987** [comment]
> @Aayush987 I have opened a PR #37532 for this issue that will close this

Ok. Thank you for informing.
