### ISSUE TITLE
Request for a machine-readable file of deprecated / removed APIs

### ISSUE THREAD

**Issue by reylejano** [kubernetes/website#37523]
This request is for a machine-readable file of deprecated / removed APIs similar to the [Deprecated API Migration guide page](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)

**Comment by sftim** [comment]
/priority awaiting-more-evidence

Sounds great. Can you write out why this is useful @reylejano ?

**Comment by sftim** [comment]
BTW, I expect that this will be a pain to implement and manage unless k/k provides that source data.

**Comment by sftim** [comment]
This is now more feasible as we have the data available.
