### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/workload.md

### ISSUE THREAD

**Issue by bishal7679** [kubernetes/website#37534]
### Prerequisites:

- If this is your first contribution, visit [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) for information on how to get started.
- Review a few https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859 to see which 
  content you have to change and which you leave unchanged.

### Procedure:

- Make sure your base, target branch is `main` and create a working branch called `hi-workload.md`.
- Create a file called content/hi/docs/reference/glossary/workload.md
- Copy the content of 
  https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/workload.md to 
  the file you created
- Localize the content.
- Push your change and create a pull request.

Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/35600

> **Note**:- Don't forget to join [`slack`](https://communityinviter.com/apps/kubernetes/community) `kubernetes-docs-hi` channel if facing any problem!

> **Note**:- As we are creating this issues for new contributors to help them. Please follow this guideline that `one time get assigned one issue only`. After completion that you can take another one. Follow this approach!
 

/language hi
/triage accepted

**Comment by surbhiahuja** [comment]
https://github.com/kubernetes/website/pull/37551 - Raised PR

**Comment by akshat5302** [comment]
I would like to work on this issue
So let me know if this issue is still open @bishal7679

**Comment by surbhiahuja** [comment]
@akshat5302 , @bishal7679 , I will complete them today

**Comment by bishal7679** [comment]
Hello @surbhiahuja due to inactivity since 6 months we are assigning this issue to another interested contributor
Feel free to take another issue!
Hope you understand :!

**Comment by bishal7679** [comment]
Hey @akshat5302 are u still interested to work on this issue?
Feel free to comment by `/assign` if so

**Comment by bishal7679** [comment]
Hello @akshat5302 are u still interested to work on this issue?
Feel free to comment `/assign` here if so!
You can take ref from this PR #37551 as it's already got so many suggestions!

**Comment by akshat5302** [comment]
@bishal7679 let other potential contributors work on it 👍

**Comment by ranjan2829** [comment]
#42549 PR done !

**Comment by ranjan2829** [comment]
@bishal7679 PR done! #42549

**Comment by divya-mohan0209** [comment]
Closing as completed.
/close
