### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/

### ISSUE THREAD

**Issue by greenorca** [kubernetes/website#37541]
With recent versions for mysql (8.0) and Wordpress, there are some errors, e.g. 
* the environment variable for WORDPRESS_DB_USER is missing in the wordpress YAML (could be root for simplicity)
* the default wordpress DB should created during setup of the mysql-container (this I don't know how to do)

Thanks a lot for consideration

**Comment by donghui12** [comment]
WORDPRESS_DB_USER default root,  wordpress DB created when connect mysql-container;

**Comment by greenorca** [comment]
Thanks for the quick reply. The database is not created automatically with the current version of WP6.0. So it would be great if this was done during setup of the wordpress-mysql deployment
