### ISSUE TITLE
Invaild images for Configure Multiple Schedulers chart on k8s.io

### ISSUE THREAD

**Issue by JingbenShi668** [kubernetes/website#37561]
There are many pictures that can't been shown normally  on https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/. In other words, the links of some pictures are invalid now.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/39040502/198291123-84a0ecb3-6801-4533-b977-6357dfa5b9c2.png">
<img width="983" alt="image" src="https://user-images.githubusercontent.com/39040502/198291170-18c5ca53-763c-4d05-b752-bec4cf735f50.png">

**Comment by utkarsh-singh1** [comment]
Hi @JingbenShi668, Can you check your internet connection if it is slow or reload the site again because I have not found any issue right now.

/language en
/triage need-information

**Comment by JingbenShi668** [comment]
> Hi @JingbenShi668, Can you check your internet connection if it is slow or reload the site again because I have not found any issue right now.
> 
> /language en /priority awaiting-more-evidence

Hi , my internet works well. I have attempted for extra some times, and it seems that some icon image resources can't load successfully  on https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/. 😊
<img width="985" alt="image" src="https://user-images.githubusercontent.com/39040502/198622678-e696e7d0-5a88-41ec-bc50-ee379eec03eb.png">

**Comment by utkarsh-singh1** [comment]
Hi @JingbenShi668, Here is the view I have of the same page, 


![Screenshot from 2022-10-28 20-14-21](https://user-images.githubusercontent.com/96516301/198657164-ba0106f5-edb6-4dc9-9fcb-44cf2398118c.png)

![Screenshot from 2022-10-28 20-14-39](https://user-images.githubusercontent.com/96516301/198657372-8603b06b-d41b-4be0-9f33-3158c839bc67.png)

What's your opinion on this error @sftim?

**Comment by JingbenShi668** [comment]
@utkarsh-singh1 oh, sorry, when I attempted to visit the website, my internet seems to be unstable. Now,  I attempt one more time, the website works well. Thanks for your explanation, I will close the issue. 
<img width="994" alt="image" src="https://user-images.githubusercontent.com/39040502/198683107-ce2790cf-8818-4a0d-b570-cddbcd217eba.png">
