### ISSUE TITLE
Document preemption toleration annotation for PriorityClasses

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#37589]
**This is a Feature Request**

**What would you like to be added**
Document two annotations:
- `preemption-toleration.scheduling.sigs.k8s.io/minimum-preemptable-priority`
- `preemption-toleration.scheduling.sigs.k8s.io/toleration-seconds`

in https://kubernetes.io/docs/reference/labels-annotations-taints/

These are used on PriorityClasses.

**Why is this needed**
We try to document all the official Kubernetes labels, annotations, and taints.

**Comments**
See https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/kep/205-preemption-toleration/README.md#preemption-toleration-api

/sig scheduling
/language en

**Comment by alculquicondor** [comment]
Wait a second, this is not kube-scheduler. This is the experimental scheduler-plugins repo.

**Comment by sftim** [comment]
> Wait a second, this is not kube-scheduler. This is the experimental scheduler-plugins repo.

Yep, but we aim to register all annotations that are used in project. Even those for alpha or beta features.
(if we want to release code that is so experimental that the annotation it uses shouldn't be registered, we should avoid hard-coding the annotation key - maybe require the user to specify it)

**Comment by alculquicondor** [comment]
But this is not part of the kubernetes release.

**Comment by sftim** [comment]
The trigger for registration is using a value in the namespace:

> Kubernetes reserves all labels and annotations in the kubernetes.io and k8s.io namespaces.
> 
> This document[[1](https://kubernetes.io/docs/reference/labels-annotations-taints/)] serves both as a reference to the values and as a coordination point for assigning values.

If we're using annotations in either namespace, we should do that coordination. There's formally an open question about whether kubernetes.io and k8s.io cover subdomains, but most contributors seem to have settled on “it does”.

**Comment by alculquicondor** [comment]
@Huang-Wei I think we should change the annotation to be `x-k8s.io`

**Comment by Huang-Wei** [comment]
> @Huang-Wei I think we should change the annotation to be under `x-k8s.io`

+1, I would be keen on changing the labels.

**Comment by Huang-Wei** [comment]
Created https://github.com/kubernetes-sigs/scheduler-plugins/issues/525 to track it. @sftim we should hold off mentioning scheduler-plugin's labels in k/website.

**Comment by divya-mohan0209** [comment]
Hello folks, would it be prudent to keep the [PR](https://github.com/kubernetes/website/pull/37868) open if we're holding off on mentioning it in k/website? Is there a timeline and a potential location we can agree upon so that we have clarity on whether we need this PR to stay open for longer?

**Comment by alculquicondor** [comment]
scheduler-plugins already swapped the domain.
From my PoV, we can close this PR.
