### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by gnuion** [kubernetes/website#37603]
I don't know why there is a sidebar on the right for just 4 links. The Iframe in the middle is too small to interact with the console. 

![image](https://user-images.githubusercontent.com/16549839/198876858-2f872cda-8bd3-4a07-a795-4eda33a35bad.png)

**Comment by utkarsh-singh1** [comment]
Hi @gnuion, Can you clarify your issue, which side of intercative tutorial you are having issue with - terminal area or  tutorial area.

/language en
/priority awaiting-more-evidence

**Comment by gnuion** [comment]
Hello @utkarsh-singh1!
I assume you know what an [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) is? 

The area of the iframe is too narrow, leaving the terminal hard to work with.
