### ISSUE TITLE
[zh-cn] User Namespaces document is missing

### ISSUE THREAD

**Issue by chengxiangdong** [kubernetes/website#37624]
**This is a Feature Request**

**What would you like to be added**

add and translate Chinese document:
`content/zh-cn/docs/concepts/workloads/pods/user-namespaces.md`

English:
https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces

**Why is this needed**
Support for more localization.

**Comments**

/language zh
/assign

**Comment by windsonsea** [comment]
This issue is solved by #39023 

/close
