### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/included/optional-kubectl-configs-pwsh/

### ISSUE THREAD

**Issue by eholman** [kubernetes/website#37650]
After running `kubectl completion powershell >> $PROFILE` the following information is added to $PROFILE, which isn't correct:

![image](https://user-images.githubusercontent.com/5081051/199348317-b6b6a01a-36b9-4ed2-b8a1-73274429c3e0.png)

After restarting the shell:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/5081051/199348998-a4d6ffa1-48ba-4887-ab0b-fe35ce131912.png">

**Comment by sftim** [comment]
Aside: the page at https://k8s.io/docs/tasks/tools/included/optional-kubectl-configs-pwsh/ is misconfigured and shouldn't be served; it's there to be included in other pages.
