### ISSUE TITLE
Ensure that page-feedback events are usable with Google Analytics 4

### ISSUE THREAD

**Issue by chalin** [kubernetes/website#37657]
This can be viewed as a subtask of #35299 or a followup task, which is why I'm creating a separate issue. I'd vote for the latter.

While the website's custom [layouts/partials/feedback.html](https://github.com/kubernetes/website/blob/main/layouts/partials/feedback.html) is already using the `gtag.js` library, the **custom event name** (`click`) **conflicts with GA4's use of the same name** to measure **[outbound clicks][]**.

It isn't clear to me yet if we can still (relatively easily) extract the page-feedback data or, for example, write custom GA4 i/f code to rectify this name clash, but IMHO, it would be easier to choose an event name that doesn't clash.

This is also an issue for Docsy, see https://github.com/google/docsy/issues/1302. I'll likely be exploring solutions for Docsy, and can port the required changes here.

/cc @a-mccarthy @nate-double-u 

[outbound clicks]: https://support.google.com/analytics/answer/9216061?hl=en

**Comment by a-mccarthy** [comment]
Thanks for filing this @chalin. I also noticed that the data we are currently getting from the feedback form is not reliable. I opened a bug here: https://github.com/kubernetes/website/issues/37201.  I've done a bit of investigating to try and remove the bot data, but its looking like this is not as straight forward as i was hoping. I dont have a solution yet, but wanted to make sure to note the issue here to remind ourselves about it :)

**Comment by chalin** [comment]
Progress: I've defined an [Event Modification rule](https://support.google.com/analytics/answer/10085872) through the analytics console interface. It changes the event name of Docsy page-feedback events to `page_helpful` from `click`:

> <img width="550" alt="image" src="https://user-images.githubusercontent.com/4140793/199631577-bf6dc5c5-ef53-4829-9ef8-e6db0e7fc07d.png">

So far it is working in realtime in the debugger. It also is appearing in the Realtime overview events panel:

> <img width="275" alt="image" src="https://user-images.githubusercontent.com/4140793/199632082-4c9b2017-d6fd-4f8f-bdf4-0f8e3f0f5ad0.png">

Here's an example of the parameters of one of these modified events:

> <img width="500" alt="image" src="https://user-images.githubusercontent.com/4140793/199632291-4e0e47f9-6232-4aa1-8b2c-2c3ece73b5b9.png">

I'm not sure how we can conveniently see `page_helpful` stats per page path. We might have to create a custom report for that. I'll check that tomorrow.

**Comment by chalin** [comment]
Here is an example of the kind of page-feedback report that we can create. This is for Nov 2 (the only day we have data for since I added the event-modification rule):

> <img width="600" alt="image" src="https://user-images.githubusercontent.com/4140793/199851087-a267f004-a725-4bad-859e-4a99ff2ea582.png">

**Comment by a-mccarthy** [comment]
Thanks for working on this @chalin! Just so i understand the numbers, does the `3` for `/release/notes` mean three clicks? Is it possible to determine if the click is yes or no?

Previously, the clicks value was calculated as `yes` is 1 and `no` is 0, and then GA would calculated an average value of the clicks. So the feedback `is this page helpful?` would show up as a percentage between 0-1, where the closer to 1 the number was, the more `helpful` the page.  I'm not saying this was better, just describing how it worked previously. 

I'm not sure if GA4 tracks values in the same way or if we are passing the value correctly for GA4. We may need to define a metric/dimension to be able to use this data in a report 🤔

**Comment by chalin** [comment]
Oh, you're right, I'm missing a data (missing a column). I've updated the screenshot, adding an "Event count" column. PTAL. I've found it challenging to create reports in GA4. Maybe it's just a steep learning curve, or maybe the i/f needs improvements (or both) 😄

**Comment by chalin** [comment]
There might be a better way to visualize that data. If there is, I haven' t found it yet. 🤷‍♂️ ... But I'll keep looking!

**Comment by a-mccarthy** [comment]
I was just poking around a bit in GA4 just now, and it seems a lot like creating graphs in Google Data Studio. Which is NOT easy either. I used a pre made Data studio template when i put together the analytics dashboard for the Kubernetes site, which is the only reason we have the pretty graphs.

So i understand, the `/release/notes/` 3 here in both columns mean 3 `yes` clicks. But for a page like `/zh-cn/docs/setup/learning-environment` there were 3 page_helpful clicks, but on 1 was `yes`?

**Comment by chalin** [comment]
I'm glad that you found that GDS template then! (Thanks for sharing your experience with GDS and validating that you found that challenging too.

My understanding of the data matches yours.

**Comment by chalin** [comment]
Page-feedback events _are_ currently being processed thanks to a workaround so I'll close this issue now. Once Docsy is fixed to address this issue, and it is updated here, things will fall into place.
