### ISSUE TITLE
Ingress-nginx whitelist-source-range annotation is not working

### ISSUE THREAD

**Issue by KrishnaRIG** [kubernetes/website#37674]
Hi Team,

We are using ingress-nginx in Azure Kubernetes cluster to expose services running in Kubernetes to outside world with hostname. Also we are using following annotation in ingress YAML file to restrict the domain access to specific IPs for security purpose. This configuration was working as expected till upgrade. After upgrading from 1.21.x to 1.22.x this configuration is not working properly, the URL will be accessible from anywhere. The IP restriction is not working. 

        `nginx.ingress.kubernetes.io/whitelist-source-range: "XX.XX.XX.XX"`

>> If we use the below annotations instead of blocking from specific IP address the ingress is blocking complete access to that URL.
       
       `ingress.kubernetes.io/whitelist-source-range: "XX.XX.XX.XX"`    

Can you please provide us the proper configuration to restrict the access.

**AKS Cluster Version:** 1.22.11
**ingress-nginx/controller:** v1.3.0

**Comment by kundan2707** [comment]
@KrishnaRIG  you are mentioning only one ip address. there should be ip address rang for whitelist-source-range.
```
Whitelist source range
You can specify allowed client IP source ranges through the nginx.ingress.kubernetes.io/whitelist-source-range annotation. The value is a comma separated list of [CIDRs](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing), e.g. 10.0.0.0/24,172.10.0.1.
```

**Comment by sftim** [comment]
/kind support

This repository is not the repository for ingress nginx; it is instead the repository where the https://k8s.io/docs/ pages are managed.


@KrishnaRIG you could instead ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes) or to the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
