### ISSUE TITLE
[zh] Localization of resource quota scopes subtopic is not idiomatic Chinese

### ISSUE THREAD

**Issue by xzyangPlus** [kubernetes/website#37690]
Hi All，I noticed a defect at https://deploy-preview-37680--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/policy/resource-quotas/#quota-scopes, I don't think this sentence is very smooth. The existence of Chinese documents should make readers understand them better, rather than translate them from English as much as possible。
The specific text is "需要注意的是，你不可以在同一个配额对象中同时设置 Terminating 和 NotTerminating 作用域，你也不可以在同一个配额中同时设置 BestEffort 和 NotBestEffort 作用域。"

**Comment by sftim** [comment]
/retitle [zh] Localization of resource quota scopes subtopic is not idiomatic Chinese
