### ISSUE TITLE
[zh] Sync “Resource Management for Pods and Containers” topic

### ISSUE THREAD

**Issue by xzyangPlus** [kubernetes/website#37693]
Hi，I found a missing translation at  /content/zh-cn/docs/concepts/configuration/manage-resources-containers.md,I think 'status' should be translated

**Comment by xzyangPlus** [comment]
> Hi，I found a missing translation at /content/zh-cn/docs/concepts/configuration/manage-resources-containers.md,I think 'status' should be translated

I think "kubelet 会将 Pod 的资源使用情况作为 Pod[`status`]" in the above documents should be translated into "kubelet 会将 Pod 的资源使用情况作为 Pod[`状态`]"

**Comment by sftim** [comment]
/retitle [zh] Sync “Resource Management for Pods and Containers” topic

**Comment by tengqm** [comment]
> > Hi，I found a missing translation at /content/zh-cn/docs/concepts/configuration/manage-resources-containers.md,I think 'status' should be translated
> 
> I think "kubelet 会将 Pod 的资源使用情况作为 Pod[`status`]" in the above documents should be translated into "kubelet 会将 Pod 的资源使用情况作为 Pod[`状态`]"

No. ``[`status`](/zh-cn/.../md)`` is markdown link syntax. The `status` in the context is a field from the `Pod` resource definition. We are not translating those field names.
/close
