### ISSUE TITLE
document interaction between PodDisruptionBudget and rollout strategy

### ISSUE THREAD

**Issue by dhduvall** [kubernetes/website#37709]
### What would you like to be added?

The documentation on PodDisruptionBudgets (https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) doesn't mention strategy at all. Likewise, the documentation on strategy (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy) doesn't mention PodDisruptionBudgets. https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/ would also be a logical place to find the two covered together.

Given that these two mechanisms for deciding what pods are allowed to die and which aren't come at the problem from different directions, it's really not clear how they interact. It would be really nice to see something (in multiple places, even if one is primarily referenced by the others) that explains what happens when a pod deletion decision is made, and how or whether each bit of configuration is taken into account.

### Why is this needed?

Clearly, this is confusing to many people, as evidenced by kubernetes/kubernetes#48307. While I would love a solution to that issue, having the PDB documentation at least mention that `rollingUpdate.maxSurge` isn't taken into account when computing allowed disruption (and what to do in that situation) would be incredibly useful. It likely would have prevented me from spending many hours trying to figure out what I was doing wrong before I went looking for any documentation that talked about both mechanisms (which led me to that bug). I suspect I'm not alone in that.

**Comment by sftim** [comment]
How about adding a whole new page:
https://kubernetes.io/docs/concepts/workloads/rollouts/

to explain the overall concept of rolling out a change, and that then links to details of how these work for Deployments, StatefulSets, etc.

The rollouts page can also explain its relation to horizontal scaling and to PodDisruptionBudgets.

**Comment by alvaroaleman** [comment]
Unless my understanding is outdated, PDBs and any form of workload strategy are completely disconnected things, because workload controllers delete pods rather than evicting them and the eviction in turn might block, but will never cause a workload controller to create a new pod. If that is still correct, that might be worth documenting though (I was very surprised when I learned this originally).

**Comment by EsqerYasen** [comment]
> How about adding a whole new page: https://kubernetes.io/docs/concepts/workloads/rollouts/
> 
> to explain the overall concept of rolling out a change, and that then links to details of how these work for Deployments, StatefulSets, etc.
> 
> The rollouts page can also explain its relation to horizontal scaling and to PodDisruptionBudgets.

@sftim  looks link is dead , can you please edit it or send to me , thank you!
