### ISSUE TITLE
[zh-cn] sync Kubernetes Community Code of Conduct

### ISSUE THREAD

**Issue by aimuz** [kubernetes/website#37707]
**This is a Feature Request**

https://kubernetes.io/community/code-of-conduct

https://kubernetes.io/zh-cn/community/code-of-conduct/

The English version has been updated, and the Chinese version needs to be synchronized

**What would you like to be added**

**Why is this needed**

**Comments**

**Comment by Sea-n** [comment]
Done by @windsonsea, thanks!
/close
