### ISSUE TITLE
Stale link in French concept page “Secrets”

### ISSUE THREAD

**Issue by brodier** [kubernetes/website#37718]
The link https://git.k8s.io/community/contributors/design-proposals/auth/secrets.md is broken

**Comment by bishal7679** [comment]
Hey @brodier Could you provide the page in which you found this broken link!

**Comment by brodier** [comment]
The broken link is on the following page:
https://kubernetes.io/fr/docs/concepts/configuration/secret/

**Comment by brodier** [comment]
I think the correct link is : 
https://github.com/kubernetes/design-proposals-archive/blob/main/auth/secrets.md

**Comment by NitishKumar06** [comment]
@sftim the language is not `en`, it's `fr`.
/language fr

**Comment by sftim** [comment]
/retitle Stale link in French concept page “Secrets”
