### ISSUE TITLE
Add more items in what's next section of Understanding Kubernetes objects

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#37714]
**This is a Bug Report**

**Problem:**
Below information is needed to mention in Kubernetes-objects [what's-next section](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#what-s-next)
- Learn more about deployments
- Learn about kubectl and kubectl commands

**Proposed Solution:**
Add Below points under Kubernetes-objects [what's-next section](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#what-s-next)
- Learn more about [deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)
- Learn about [kubectl](https://kubernetes.io/docs/reference/kubectl/) and [kubectl commands](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands)

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

**Comment by sftim** [comment]
/triage accepted

Good idea

**Comment by T-Lakshmi** [comment]
Fixed it here #37747
