### ISSUE TITLE
Align securing a cluster task with security checklist

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#37738]
**This is a Feature Request**

We have two pages with similar aims:
- https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/
- https://kubernetes.io/docs/concepts/security/security-checklist/

We should ensure that the advice in the two documents is aligned, and also make sure that the two documents link to each other.

**Why is this needed**
It's a bad idea to document multiple ways to make sure that your cluster is secure, unless those are well aligned.

**Comments**
/sig security
/sig docs
/language en

**Comment by sftim** [comment]
Relevant to #25119

**Comment by Ritikaa96** [comment]
Regarding this:
> also make sure that the two documents link to each other.

We can use a reference section/note/what's next section in the end of [securing-a-cluster.md](https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/) stating:
- `Find an extensive list of security checks [here](https://kubernetes.io/docs/concepts/security/security-checklist/)`

**Comment by Aut0R3V** [comment]
Hey
I would like to work on this.
