### ISSUE TITLE
Add configMap volume type to the Volumes concept page

### ISSUE THREAD

**Issue by jseldess** [kubernetes/website#3773]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The `configMap` volume type is not listed on the [Volumes](https://kubernetes.io/docs/concepts/storage/volumes/#secret) concept page. 

This came up when I was adding the `projected` volume type to that page, `configMap` being one of 3 types that can be projected.

**Proposed Solution:**

Add a new section on this type. 

**Page to Update:**
http://kubernetes.io/blob/master/docs/concepts/storage/volumes.md

**Comment by ahmetb** [comment]
@jseldess would you like to contribute a patch?

**Comment by jseldess** [comment]
@ahmetb, sure, happy to give it a shot. I have another PR touching that page, though, so would it be ok to integrate this work into that PR, or would you prefer I handle it in a separate PR (conflicts would eventually need to be resolved in one or the other PR).

**Comment by ahmetb** [comment]
You can submit it after existing PR is merged, it'd be easier for you probably as well.

**Comment by jseldess** [comment]
OK, sure. Anything I can do to speed up that other PR? It requires a response/input from an engineer.

**Comment by ahmetb** [comment]
@jseldess you can add a couple of owners from the `assignees` header of the markdown documents in the patch. It can take 1-2 days for people to review.

**Comment by ahmetb** [comment]
It looks like you can actually implement this in docs/concepts/storage/volumes.md without conflicting with the open PR.

**Comment by jseldess** [comment]
@ahmetb, where do you think it belongs? The list of volume types does not seem to follow any ordering principles, which is why I added the `projected` type just at the bottom of the list. If I do the same for `configMap` in a separate PR, I do think there will end up being a conflict in the file. Not a big deal, though.

**Comment by ahmetb** [comment]
Hmm, I am not sure if there was a particular ordering. In a separate PR you can probably reorder them. I would ideally love to see 1st party stuff on top and then plugins.

**Comment by zacharysarah** [comment]
@jseldess @ahmetb 👋 Any updates here?

**Comment by tengqm** [comment]
Dup: #2385
