### ISSUE TITLE
[ko] Missing one line translation website/content/ko/docs/concepts/scheduling-eviction/pod-priority-preemption

### ISSUE THREAD

**Issue by onestone9900** [kubernetes/website#37740]
**This is a Feature Request**

**What would you like to be added**
Translate untranslated line in
`website/content/ko/docs/concepts/scheduling-eviction/pod-priority-preemption`
into Korean.

**Why is this needed**
Missing one line translation : 
`the scheduler always tries the "nominated Node" before iterating over any other nodes.`

**Page**
https://kubernetes.io/ko/docs/concepts/scheduling-eviction/pod-priority-preemption/#%EC%82%AC%EC%9A%A9%EC%9E%90-%EB%85%B8%EC%B6%9C-%EC%A0%95%EB%B3%B4

/language ko

**Comment by seokho-son** [comment]
/good-first-issue

Good-first-issue for a contributor who can translate `the scheduler always tries the "nominated Node" before iterating over any other nodes` into Korean (expect a native Korean)
