### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by cryptosquirrels** [kubernetes/website#37757]
doesn't include information about initial-cluster or initial-advertise-peer-url

**Comment by Ritikaa96** [comment]
Hi , could you please explain further, where and what kind of information you want this page to add?

/language en

**Comment by Ritikaa96** [comment]
For information regarding the flags, you can find detailed info [here](https://etcd.io/docs/v3.1/op-guide/configuration/#--initial-advertise-peer-urls)

In the latest version of etcd the same is explained [here](https://etcd.io/docs/v3.5/op-guide/configuration/#clustering)

**Comment by Ritikaa96** [comment]
Hi @cryptosquirrels , would you like to share further information regarding the changes you want to see? Please do confirm.
