### ISSUE TITLE
Broken link on Creating a cluster with kubeadm page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#37750]
**Problem:**
The text [**back up etcd**](https://coreos.com/etcd/docs/latest/admin_guide.html) on [link](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#resilience) is not working, it should point to this https://etcd.io/docs/v2.3/admin_guide/
Check the page [Creating a cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)
for the problem.

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Suggested Solution:**
It should resolve this issue by adding a simple link and enhancing the document line.
Update the text **back up etcd** link to https://etcd.io/docs/v2.3/admin_guide/ and not to this [link](https://coreos.com/etcd/docs/latest/admin_guide.html).

/kind document
/assign
/language en

**Comment by reylejano** [comment]
The suggested solution is incorrect because Kubernetes uses etcd v3 and we should not link to etcd v2 docs
