### ISSUE TITLE
Implement Hugo translation of canonical tags in the glossary

### ISSUE THREAD

**Issue by stormqueen1990** [kubernetes/website#37760]
**This is a Feature Request**

**What would you like to be added**
Implement translation of the canonical tags (listed under `tags:` in the glossary entries) for the glossary page. Currently, the tag filter in the glossary page is English-only. This causes the page to look a little bit strange after translated since the only terms that are listed in a different language are the tags.

**Why is this needed**
Improve reader experience when looking at the glossary.

/cc @a-mccarthy @seokho-son

**Comment by seokho-son** [comment]
Related files for the glossary page localization.
- Layout: [layouts/docs/glossary.html](https://github.com/kubernetes/website/blob/main/layouts/docs/glossary.html)
- Tags: [data/canonical-tags](https://github.com/kubernetes/website/tree/main/data/canonical-tags)

**Comment by a-mccarthy** [comment]
/area localization

Now that i'm reading through this, i believe we already have an issue for updating this: https://github.com/kubernetes/website/issues/30016. This issue has some more details about the work needed to do this

**Comment by seokho-son** [comment]
Oh I accepted triage of https://github.com/kubernetes/website/issues/30016 as well. :octocat:

**Comment by sftim** [comment]
/triage duplicate
/remove-triage accepted

Let's shift discussion to #30016.

**Comment by stormqueen1990** [comment]
@a-mccarthy it is indeed the same. I'll close this one and switch focus to the older one.

Thanks!
