### ISSUE TITLE
issue with k8s.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

### ISSUE THREAD

**Issue by JingbenShi668** [kubernetes/website#37765]
**This is a Bug Report**

**Problem:**
When I attempted to configure the Multiple Schedulers by https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/. I encountered some problem, and I have found similar problems in closed issues. But, the update for the tutorial https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/ doesn't appears.

Description for problem
I follow the steps in the https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/. I can run the my-scheduler successfully. However, when I deploy pods that I schedule with the .spec.schedulerName set to my-scheduler, the pod wasn't scheduled. And, the pod always was pending status. I don't know why the problem appears?
<img width="809" alt="image" src="https://user-images.githubusercontent.com/39040502/200389294-650c4cf6-4446-43f0-98f8-f55cee08b260.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/39040502/200389193-313544b5-797a-44a4-abae-bae835ca1e1f.png">

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/39040502/200389470-c0384603-003a-4ea7-8d4b-1dc9f1f2e1c9.png">

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

**Kubernetes Version:**
Centos7.6
Kubernetes v1.23.0
Docker client 20.10.21
Docker engine 20.10.21
go version go1.19.3 linux/amd64

**Additional Information:**
I see many closed issues about the problem. However, I don't  find a valid way to solve the problem. Currently, I have no idea for the problem. If I know how to fix the error, I'll create a PR to update the [Configure Multiple Schedulers](https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/).

**Comment by Denny991** [comment]
我遇到和你一样的问题，请问该问题最终解决了么，
