### ISSUE TITLE
Move PodOverhead feature gate to removed feature gates list

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#37779]
Move PodOverhead feature gate to removed feature gates list

- https://github.com/kubernetes/kubernetes/pull/112579
- https://github.com/kubernetes/enhancements/pull/3526

Both https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ and https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/ do need to change.

_Originally posted by @SergeyKanzhelev in https://github.com/kubernetes/enhancements/issues/688#issuecomment-1251458360_

**Comment by tengqm** [comment]
The concept of 'GA' is different from 'removed'. 
For GA'ed gates, we document them at https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/, for removed gates, we use the page https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

**Comment by pacoxu** [comment]
Update the title. It is still beta in dev-v1.26 and need an update.

**Comment by pacoxu** [comment]
PodOverhead feature gate was removed as the feature is in GA since 1.24
- GAed in v1.24
- Removed in v1.26

**Comment by sftim** [comment]
/sig node
/milestone 1.26

/retitle Move PodOverhead feature gate to removed feature gates list

Does that sound right?

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/ does _not_ need to change.

Both https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ and https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/ do need to change.

**Comment by sftim** [comment]
/triage accepted

@pacoxu please update the issue description so that a contributor can easily see what needs fixing.

**Comment by Shubham82** [comment]
Proposed Solution:
In this we have to move the following things from[ Feature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) to [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/):

1) Move the feature gate `PodOverhead` from [Feature gates for graduated or deprecated features](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features) to [Feature gates that are removed](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/#feature-gates-that-are-removed) 

2) Move `PodOverhead` description under [List of feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates)  to  [Descriptions for removed feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/#descriptions-for-removed-feature-gates)

**Comment by Shubham82** [comment]
Hi @pacoxu
This is what we have to do for this issue. Am I right?

**Comment by pacoxu** [comment]
Fixed in #37925.
