### ISSUE TITLE
Creating a cluster with kubeadm

### ISSUE THREAD

**Issue by ravishthecoder** [kubernetes/website#37776]
Team, 

I am working on a project where we are trying to set up the Kubernetes cluster network on-premise using the Kubernetes tool KubeAdm. Is there any article that we can use as a reference for this? We would need to set up a windows worker node.

Thanks in advance

**Comment by neolit123** [comment]
the windows worker nodes docs are missing / wip. please watch:
https://github.com/kubernetes/website/issues/34476

/close
