### ISSUE TITLE
Document limits and best practices for network between kubelet and API server

### ISSUE THREAD

**Issue by csantanapr** [kubernetes/website#37799]
Where is the documentation that have details on the limitation or requirement running control plane node and a worker node far apart like in separate cloud regions? Or public (control plane) and on-premises (worker nodes)

Not talking about the distance between etcd nodes this is cover in [etcd tuning](https://etcd.io/docs/v3.5/tuning/#time-parameters), I'm referring about distance/connectivity between kubelet and api server.

I tried searching but only thing close was this page and it doesn’t mention it https://kubernetes.io/docs/setup/best-practices/multiple-zones/

**Comment by sftim** [comment]
/retitle Document limits and best practices for network between kubelet and API server

/language en
/kind feature
