### ISSUE TITLE
kube-apiserver Audit Configuration (v1) - Level should be `enum` of values instead of alias of string

### ISSUE THREAD

**Issue by distortedsignal** [kubernetes/website#37794]
Presently, [the documentation of the `Level` type](https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/#audit-k8s-io-v1-Level) says that it is

> Alias of string

and I do not believe that this is correct. The [Audit Policy documentation](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/#audit-policy) states that there are four defined levels:

* `None`
* `Metadata`
* `Request`
* `RequestResponse`

I think that this speaks to `Level` being less an alias of the `string` type and more of an `enum` type.

If `Level` were an alias of `string`, then any value for `Level` would be expected to work, whereas specifying `enum` would imply that only a few, specialized strings are expected.

**Comment by distortedsignal** [comment]
I've been informed that the documentation page for the `Level` type was autogenerated, and that I should mention this fact in any tickets that I open.

**Comment by mengjiao-liu** [comment]
[Level type](https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/#audit-k8s-io-v1-Level) is alias of string.

source code is as follows:
```
// Level defines the amount of information logged during auditing
type Level string

// Valid audit levels
const (
	// LevelNone disables auditing
	LevelNone Level = "None"
	// LevelMetadata provides the basic level of auditing.
	LevelMetadata Level = "Metadata"
	// LevelRequest provides Metadata level of auditing, and additionally
	// logs the request object (does not apply for non-resource requests).
	LevelRequest Level = "Request"
	// LevelRequestResponse provides Request level of auditing, and additionally
	// logs the response object (does not apply for non-resource requests).
	LevelRequestResponse Level = "RequestResponse"
)
```

https://github.com/kubernetes/kubernetes/blob/e62cfabf9326cdec65e926b697fa1911b4e85da6/staging/src/k8s.io/apiserver/pkg/apis/audit/v1/types.go#L35-L50

> and I do not believe that this is correct. The [Audit Policy documentation](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/#audit-policy) states that there are four defined levels:
None
Metadata
Request
RequestResponse

This is because the validation added four level constants to the string slice `validLevels`.
```
var validLevels = []string{
	string(audit.LevelNone),
	string(audit.LevelMetadata),
	string(audit.LevelRequest),
	string(audit.LevelRequestResponse),
}
```
https://github.com/kubernetes/kubernetes/blob/e62cfabf9326cdec65e926b697fa1911b4e85da6/staging/src/k8s.io/apiserver/pkg/apis/audit/validation/validation.go#L54-L59

**Comment by tengqm** [comment]
This is a limitation of the reference generator currently. From data type's perspective, we can only say that `Level` is an alias of `string`. We are unable to enumerate all values of `type Level` across the source code.

**Comment by sftim** [comment]
This is a string (aliased) value with, if you like, only 4 value values.

Lots of string fields in configuration files have additional validation but are still essentially strings. Maybe one day we'll also be able to document which values are allowed. I think even then we might this a string type, just with extra context.

The generator code lives in https://github.com/kubernetes-sigs/reference-docs/

**Comment by distortedsignal** [comment]
I think this would also benefit with a link to the docs that lays out the blessed strings.
