### ISSUE TITLE
Adding Google Analytics to minikube website

### ISSUE THREAD

**Issue by medyagh** [kubernetes/website#37801]
Hello 

I am from Minikube team and per conversation with @jimangel I am creating this issue, to request adding Google analytics to minikube website https://minikube.sigs.k8s.io/ (similar to what Kubernetes website has)

I would like to start this request and would like to know what is the next step, and do we create our own Google analytics account or share with Kubernetes Website?

**Comment by a-mccarthy** [comment]
Thanks for filing @medyagh! We are currently in the process of [migrating](https://github.com/kubernetes/website/issues/35299) to a new versions of google analytics, but i think it should be straightforward to set up the minikube site as a new property under the GA4 account we have. 

@chalin do you mind weighing in here and letting us know your thoughts about the best way to add a new site? thanks!

**Comment by chalin** [comment]
The **recommended account structure under GA4** differs from that for UA. For context, I'd suggest first reading [Google Analytics 4 account structure].

I see the [Kubernetes organization] like **Example B** in [that GA4 docs page][Google Analytics 4 account structure], which would suggest that we'd use the same property (and it's single web data stream) to track all websites under the [Kubernetes organization]. With such a setup, we'll be able to track user journeys across all k8s sites. Also with this approach, we'll probably have to define custom reports for each website, but we would have to do that anyways if we want the equivalent of the UA views defined as part of the original Kubernetes UA account (it had 4 defined views).

I'm still learning about this (GA4 is quite different from UA), so the above is to the best of my understanding. Comments are welcome. I'd be willing to hop onto a VC to discuss this if that could help.

/cc @nate-double-u 

[Google Analytics 4 account structure]: https://support.google.com/analytics/answer/9679158
[Kubernetes organization]: https://github.com/kubernetes

---

Question: how urgent is this? Or, to ask this another way, by when would you like GA to be setup for the site?

**Comment by chalin** [comment]
> we'll probably have to define custom reports

Ok, I've finally gotten the GA4 i/f to cooperate: I'm now able to create, save and make easily accessible custom reports that filter, for example, by hostname.

**Comment by chalin** [comment]
The **simplest way to enable analytics** to the minikube website is via [Netlify snippet injection], as is done for kubernetes.io. @medyagh - I'd be glad to set that up, or guide someone into doing so, If someone grants me access to the minikube Netlify account.

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

FYI: the Docsy version of the minikube website is too old to support GA4, so Docsy would need to be updated if we'd want to enable GA4 via Docsy config.

**Comment by medyagh** [comment]
Thank you very much @chalin we will update our docsy submodule, what code do we need to inject to our template ? and after that how do we access the metrics ?

**Comment by sftim** [comment]
> Should this issue be moved to the minikube website repo?

I'm happy to move it (I think we'd need to open a new issue and close this one).

**Comment by chalin** [comment]
@a-mccarthy et al.: are you ok with what is proposed in https://github.com/kubernetes/website/issues/37801#issuecomment-1309395460?

**Comment by chalin** [comment]
> Thank you very much @chalin we will update our docsy submodule, what code do we need to inject to our template ? and after that how do we access the metrics ?

@medyagh - it won't hurt to update the Docsy module in the meantime, but I'd hold off on enabling analytics via Docsy. As I mention in https://github.com/kubernetes/website/issues/37801#issuecomment-1310569148, I recommend using snippet injection instead. Do you know if the website is hosted by Netlify?

**Comment by medyagh** [comment]
Thanks @chalin we just updated the Docsy https://github.com/kubernetes/minikube/pull/15342

I am not familiar with snippet, is there any action needed on our end ? and how do we accesses the analytics metrics

**Comment by a-mccarthy** [comment]
@chalin I agree with your assessment. It appears that example b in the linked page is the closes to how we currently have the analytics set up, as well as how we'd like to collect analytics going forward. In this model, we'd have one `account` and a separate `property` for each website we collect analytics for. Do we have a list of all the current websites we are tracking our should add to the new G4 account? So we know what should be migrated over, if anything? 

You've raised questions about what sites should be connected to the Kubernetes analytics account before, and i'm note sure if there was a final answer there. But this feels like something we should decide on and keep track of somewhere. Hopefully we can write down the criteria and process for getting added so folks know how to ask for this in the future. 

(ps sorry for my delayed response)

**Comment by chalin** [comment]
@a-mccarthy: thanks for your response. Actually, "Example B" in the [Google Analytics 4 account structure](https://support.google.com/analytics/answer/9679158) page suggests a single property for all websites, and in fact, a single web stream for all websites (so that, e.g., we can configure cross-domain tracking).

For a list of k8s websites (at least those that I currently know about), see rows 2 - 12 of the [CNCF project GA4 migration status](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA). 

> You've raised questions about what sites should be connected to the Kubernetes analytics account before, and i'm note sure if there was a final answer there. 

Yes, that is the main question to be answered, and the one that will impact how we choose to setup the GA4 account. As you proposed elsewhere, maybe we should meet to discuss this.

> But this feels like something we should decide on and keep track of somewhere. Hopefully we can write down the criteria and process for getting added so folks know how to ask for this in the future.

Agreed.

**Comment by medyagh** [comment]
thank you both @a-mccarthy and @chalin to get this updated, and glad we are making this a process for next websites,   is there any action on our end (minikube team) to do ?

**Comment by chalin** [comment]
Not that I can see @medyagh, thanks.

**Comment by medyagh** [comment]
hi @chalin @a-mccarthy @sftim  just following up on this, is there any instruction for minikube maintainers how we can register/login to see the analytics ?

**Comment by chalin** [comment]
@medyagh - the GA4 measurement ID is `G-JPP6RFM2BP`. You can add it to the project's Hugo config file: search for "analytics" and replace the bogus ID that's there with the GA4 ID. Let me know which email address(es) to grant access to.

**Comment by medyagh** [comment]
thank you @a-mccarthy and also @chalin, we just added the ID to our config, 

@chalin would you mind sharing the access with me ? if needed to share personal email, maybe we could exchange info on slack ?

**Comment by chalin** [comment]
@medyagh - sure, DM me via Slack (K8S or CNCF)

**Comment by chalin** [comment]
I can confirm with the Tag Assistant that the GA4 ID is being used by the minikube site. Can we close this issue now?

**Comment by chalin** [comment]
FYI, the console is showing MiniKube events:

> <img width="464" alt="image" src="https://user-images.githubusercontent.com/4140793/208185417-6e7ee406-7940-487c-94b4-c0f20b367969.png">

**Comment by chalin** [comment]
Also, I added a custom MiniKube report so that you can easily determine page views for the site:

> <img width="398" alt="Screen Shot 2022-12-16 at 15 47 55" src="https://user-images.githubusercontent.com/4140793/208186484-7f96064f-26e2-41ae-81d7-cfe4c8e4cb22.png">
