### ISSUE TITLE
Interactive Tutorial - Creating a Cluster

### ISSUE THREAD

**Issue by softhuafei** [kubernetes/website#37809]
Can't open the interactive tutorial. Can you show the tutorial steps independently so that we can learn the tutorial locally

**Comment by utkarsh-singh1** [comment]
Hi @softhuafei, Can you give detailed description why you can't open interactive tutorial? If there is any black screen, you can disable your ad blocker and reload interactive tutorial.

**Comment by softhuafei** [comment]
hi, I try disable my ad blocker and reload the interactive tutorial, but it still doesn't work. 
![image](https://user-images.githubusercontent.com/25077829/201009790-0dd33e95-c6db-4735-9de3-fb20679dcf72.png)

**Comment by utkarsh-singh1** [comment]
It can be due to slow connectivity because tutorial is still not loaded, also I can create a working environment for deploying an app, 

> ![image](https://user-images.githubusercontent.com/96516301/201022441-365d24de-fb3a-4e97-b9d7-14b0ab8b968d.png)

**Comment by T-Lakshmi** [comment]
@softhuafei,
Are you still facing this issue? if not we can close this issue.

**Comment by reylejano** [comment]
I'm closing this issues. As of Feb 6, 2023, the interactive tutorial is working for me, seems to be the user's browser or connectivity as others are able to reach the tutorial
/close
