### ISSUE TITLE
Hard to understand "Extend the Kubernetes API with CustomResourceDefinitions"

### ISSUE THREAD

**Issue by HeGaoYuan** [kubernetes/website#37803]
It is to hard to understand the document "[Extend the Kubernetes API with CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)".

For example, I read the document from top to bottom. When I reached the chapter "[Specifying a structural schema](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/)", I met the allOf, anyOf, oneOf etc, but there are no introductions about these terminologies, I can't understand what the meaning of these words.

Would you please consider to rewrite this document?

**Comment by tengqm** [comment]
/kind support

@HeGaoYuan You have to spend sometime learning OpenAPI (Swagger or v3).

**Comment by HeGaoYuan** [comment]
> Specifying a structural schema

My mistake, I find the document has a link to [OpenAPI v3.0 validation schema](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation)
