### ISSUE TITLE
[zh-cn] sync /static/cncf-code-of-conduct.md

### ISSUE THREAD

**Issue by niuzhenguo** [kubernetes/website#37811]
**This is a Bug Report**

**Problem:**

/static/cncf-code-of-conduct.md needs to be synced

**Proposed Solution:**
sync with en version

**Page to Update:**
https://kubernetes.io/community/code-of-conduct/

**Comment by windsonsea** [comment]
May need to wait for this PR to merge:
https://github.com/cncf/foundation/pull/450

**Comment by windsonsea** [comment]
https://github.com/cncf/foundation/pull/450

This is merged now. You can move forward.
