### ISSUE TITLE
Annotation `pv.kubernetes.io/migrated-to` not registered / documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#37814]
**This is a Bug Report**

**Problem:**
Kubernetes uses an annotation, `pv.kubernetes.io/migrated-to`. However, this annotation is not registered in https://kubernetes.io/docs/reference/labels-annotations-taints/

**Proposed Solution:**
Document the annotation (which also means it gets registered).

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**

Aside: if there are other `pv.kubernetes.io` annotations, let's document all of them.

/language en
/sig storage

**Comment by Ritikaa96** [comment]
Hi @sftim , If no one's working on this issue , i'd like to take this up.

**Comment by sftim** [comment]
Anyone is welcome to work on this issue. It's better to prioritize issues already triaged as accepted.

/triage accepted
/priority backlog

**Comment by Ritikaa96** [comment]
Hi @sftim 
I have raised a PR ( #37928) resolving this issue with all pv.kubernetes.io annotations registered. 
PTAL!
