### ISSUE TITLE
Add a “What's next” section to  Labels & Selector concept

### ISSUE THREAD

**Issue by Ritikaa96** [kubernetes/website#37849]
**This is a Feature Request**

**What would you like to be added**
Add a “What's next” section to the concept page about Labels and Selector.
*Update: see https://github.com/kubernetes/website/issues/37849#issuecomment-1313087207 for more details on what to put there*

**Why is this needed**
In [Labels.md](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) , some tasks and references can be incorporated to show usage of labels and selector.

**Comment by sftim** [comment]
/language en

Where should we link to? (what URLs)

**Comment by Ritikaa96** [comment]
Hi @sftim, i added these links, they might help a new user to understand the extensive use of labels and find references to understand the same :
- Learn how to [add a label to a node](/docs/tasks/configure-pod-container/assign-pods-nodes/#add-a-label-to-a-node)
- Find [Well-known labels, Annotations and Taints ](/docs/reference/labels-annotations-taints/)
- See [Recommended labels](/docs/concepts/overview/working-with-objects/common-labels/)
- [Enforce Pod Security Standards with Namespace Labels](/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/)
- [Use Labels effectively](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/#using-labels-effectively) to manage deployments.
- Read a blog on [Writing a Controller for Pod Labels](https://kubernetes.io/blog/2021/06/21/writing-a-controller-for-pod-labels/)

**Comment by sftim** [comment]
/good-first-issue
/triage accepted

If people have questions about how to work on this, it's OK to ask.

**Comment by cmaguluri1305** [comment]
hello i would like to work on the issue can anyone one assign this to me?

**Comment by sftim** [comment]
@cmaguluri1305 it's polite to sync with other contributors - see https://github.com/kubernetes/website/issues/37849#issuecomment-1316779565 - who have already started work.

**Comment by Ritikaa96** [comment]
Hi @cmaguluri1305 , I'm open to other suggestions or to explanations needed on the issue.You can check it out once if you have new references to add other than [these](https://github.com/kubernetes/website/issues/37849#issuecomment-1313087207)
