### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1/

### ISSUE THREAD

**Issue by kind03** [kubernetes/website#37854]
Can we have more explanation on the "rules.apiGroups"? Totally have no idea on what is it

**Comment by dipankardas011** [comment]
@kind03 the problem is not quite sure (where you want to add the description)
> Here is a link which might be helpful https://github.com/kubernetes/website/tree/main/content/en/docs/reference/access-authn-authz

**Comment by utkarsh-singh1** [comment]
Hi @kind03, Can you provide a more brief explanation about the issue you are facing with `rules.apiGroups` definition? As it can be improved based on your suggestion.

/language en
/priority awaiting-more-evidence

**Comment by utkarsh-singh1** [comment]
Hi @kind03, follow this link for info on API Groups - https://kubernetes.io/docs/reference/using-api/#api-groups.

**Comment by utkarsh-singh1** [comment]
Also, you can find available resources and their apiGroups using -

```bash
kubectl api-resources -o wide
```

The output is in form of  -

>apiGroup/version
