### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubernetes-api/authorization-resources/cluster-role-v1/

### ISSUE THREAD

**Issue by kind03** [kubernetes/website#37853]
can we have the available resource list on this page?

**Comment by utkarsh-singh1** [comment]
Hi @kind03, the available resource list is quite long you can use command 
`kubectl api-resources | more` 
for list of resources.

**Comment by utkarsh-singh1** [comment]
Hi @kind03, has your issue has been resolved?

/triage needs-information

**Comment by tengqm** [comment]
/close
The mentioned page is auto-generated out of upstream source code. Won't fix it here.
