### ISSUE TITLE
[hi] Localize /en/docs/reference/glossary/limitrange.md

### ISSUE THREAD

**Issue by bishal7679** [kubernetes/website#37856]
### Prerequisites:

- If this is your first contribution, visit [Contribute to K8s docs](https://kubernetes.io/docs/contribute/) for information on how to get started.
- Review a few https://github.com/kubernetes/website/issues/35600#issuecomment-1214215859 to see which 
  content you have to change and which you leave unchanged.

### Procedure:

- Make sure your base, target branch is `main` and create a working branch called `hi-limitrange.md`.
- Create a file called content/hi/docs/reference/glossary/limitrange.md
- Copy the content of 
  https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/limitrange.md 
  to the file you created
- Localize the content.
- Push your change and create a pull request.

Completing this feature issue fixes part of https://github.com/kubernetes/website/issues/35600

> **Note**:- Don't forget to join [`slack`](https://communityinviter.com/apps/kubernetes/community) `kubernetes-docs-hi` channel if facing any problem!

> **Note**:- As we are creating this issues for new contributors to help them. Please follow this guideline that `one time get assigned one issue only`. After completion that you can take another one. Follow this approach! **This issue is for first-time-contributor only**
 

/language hi
/triage accepted

**Comment by NitishKumar06** [comment]
Ahan! A great approach to helping new contributors. Sorry I missed that point.
/unassign

**Comment by chiukapoor** [comment]
Hello Team, This is my first issue on kubernetes/website. I would like to work on it

/assign

**Comment by NitishKumar06** [comment]
@chiukapoor Keep working on this issue. Feel free to raise a PR
