### ISSUE TITLE
“Example” buttons do not work for legacy API reference page

### ISSUE THREAD

**Issue by rodraco** [kubernetes/website#37861]
**This is a Bug Report**
The "example" buttons do not currently work on anything. Older version documentation has the same issue.

**Problem:**
jquery-3.3.1.min.js, jquery.scrollTo-2.1.2.min.js and bootstrap-4.3.1.min.js fail to load; tried Multipe browsers and OS (Windows + Brave, Win + Chrome, Linux + Chromium, Linux + Firefox)
**Proposed Solution:**
Make sure the files are deployed; 
**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25

![2022-11-12 16_47_55-Kubernetes API Reference Docs](https://user-images.githubusercontent.com/64062704/201479847-a79c8d97-5495-4b38-864b-cbab15ec6208.png)

**Comment by sftim** [comment]
/retitle “Example” buttons do not work for legacy API reference page

**Comment by sftim** [comment]
/priority backlog

Thanks for reporting this @rodraco

**Comment by tamilselvan1102** [comment]
Not only deployed jQuery and Bootstrap library files, the corresponding processing action code also not there.

**Comment by aj11anuj** [comment]
Fixed by #39719
/close
