### ISSUE TITLE
Query around URL of documentation for current Kubernetes release

### ISSUE THREAD

**Issue by saeeda** [kubernetes/website#37871]
https://v1-25.docs.kubernetes.io/docs/concepts/cluster-administration/addons/ certificate error

The above page shows `NET::ERR_CERT_COMMON_NAME_INVALID` error as the certificate is issued to `Netlify`.
```
Common Name (CN)	*.netlify.app
Organization (O)	Netlify, Inc
```
While `v1-24` and `v1-23` are correctly setup and are secure.

This can be solved by setting an automatic forward to a page inside `docs.kubernetes.io` domain.

**Comment by sftim** [comment]
Hi.
The correct URL for this documentation is https://kubernetes.io/docs/concepts/cluster-administration/addons/ 

We don't yet support accessing the current Kubernetes docs via a version-specific permalink.

/kind support

**Comment by sftim** [comment]
/retitle Query around URL of documentation for current Kubernetes release

**Comment by dipankardas011** [comment]
## Just keen to know?
@sftim where is this URL used?
```
```
@saeeda from where you got this URL?
```
```

**Comment by saeeda** [comment]
@dipankardas011 In the [kubeadm upgrade](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#call-kubeadm-upgrade) document, there is a step referring to `addons` to check whether they need upgrade themselves.
> Your Container Network Interface (CNI) provider may have its own upgrade instructions to follow. Check the [addons](https://kubernetes.io/docs/concepts/cluster-administration/addons/) page to find your CNI provider and see whether additional upgrade steps are required.
Since I was performing the upgrade between minor versions `v1.25`, and the page was hosted on `v1-24.docs.kubernetes.io`, so I checked the `v1-25` version, and noticed the certificate error.

It would be helpful to have a section/paragraph in the current/latest _addons_ page that explains if any step is needed for upgrading between minor versions.

**Comment by dipankardas011** [comment]
> @dipankardas011 In the [kubeadm upgrade](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#call-kubeadm-upgrade) document, there is a step referring to `addons` to check whether they need upgrade themselves.
> > Your Container Network Interface (CNI) provider may have its own upgrade instructions to follow. Check the [addons](https://kubernetes.io/docs/concepts/cluster-administration/addons/) page to find your CNI provider and see whether additional upgrade steps are required.
> 
> Since I was performing the upgrade between minor versions `v1.25`, and the page was hosted on `v1-24.docs.kubernetes.io`, so I checked the `v1-25` version, and noticed the certificate error.
> It would be helpful to have a section/paragraph in the current/latest _addons_ page that explains if any step is needed for upgrading between minor versions.

Thanks, for clearing my doubt😇
