### ISSUE TITLE
Provide the hyperlink to [persistentVolumes] in Namespaces page

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#37890]
**This is a Feature Request**

**What would you like to be added**
Under [Namespaces](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/) page,  provide hyperlink for `persistentVolumes` in section [Not all objects are in a namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#not-all-objects-are-in-a-namespace).

**Why is this needed**
it would be useful for quick reference.

**Comments**
/good-first-issue
/language en
/assign

**Comment by H4LKEye** [comment]
I would like to work on this.

**Comment by sftim** [comment]
This issue isn't really well specified enough to be a good first issue.

/triage accepted
/remove-good-first-issue
