### ISSUE TITLE
How we can send kubernetes audit logs to splunk in puppet

### ISSUE THREAD

**Issue by kavita1205** [kubernetes/website#37915]
Hi Team,

How we can send kubernetes audit logs to splunk if we are using puppet. We are using below configurations , so in case of sending audit logs what would be the configurations here. Can someone please help me here.

```
# SplunkForwarder file input parameters
profile::splunkforwarder::input_files_parameters_sections:
  'syslog-input':
    section: 'monitor:///var/log/syslog'
    setting: 'disabled'
    value: '0'
    tag: 'splunk_input_syslog'
  'syslog-index':
    section: 'monitor:///var/log/syslog'
    setting: 'index'
    value: 'ml_logs'
    tag: 'splunk_input_syslog'
```

**Comment by Ritikaa96** [comment]
Hey @kavita1205 , Here is a similar issue explaining way sending logs to splunk in thread , also linked issues to it are important as well. 
Sending the find in case anybody else has similar query.

**Comment by Ritikaa96** [comment]
marking /remove-lifecycle rotten 
@kavita1205 , do you still have any query? It will be great if you share your update here as well as explaining the solution.
In case you don't have further query you can close it using the mentioned tag.
