### ISSUE TITLE
https://k8s.io/docs/reference/instrumentation/metrics/ documents v1.26

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#37922]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/instrumentation/metrics/ documents metrics for Kubernetes v1.26 but that's incorrect because at the time I'm filing this the live documentation is for Kubernetes v1.25

**Proposed Solution:**
Revert whichever PR bumped the document too early

_or_

do a careful partial revert that only omits the v1.26 changes

**Page to Update:**
https://kubernetes.io/docs/reference/instrumentation/metrics/

**Additional Information:**
/sig instrumentation
/language en

If v1.26 gets released before we fix this, it's OK to close the issue. Consider a backport to the v1.25 docs, though.

**Comment by Pradumnasaraf** [comment]
Hey, @sftim I have found that PR https://github.com/kubernetes/website/pull/37822 . Can you please confirm these PR changes are to be reverted?

**Comment by Pradumnasaraf** [comment]
Hey, @dashpole I already assign it to myself and opened the PR. Thank you :)
