### ISSUE TITLE
S3 bucket mount in K8s Pods

### ISSUE THREAD

**Issue by itpradeep2018** [kubernetes/website#37929]
Is there any simple way to mount S3 in K8s Pods?

**Comment by tamilselvan1102** [comment]
@itpradeep2018 
hope it would be help
https://blog.meain.io/2020/mounting-s3-bucket-kube/

**Comment by sftim** [comment]
If you're just looking for someone else to give you advice on how to use Kubernetes with AWS, you could indeed ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

I'm afraid that this issue tracker is not the right place for support requests.

/close
