### ISSUE TITLE
Clarify cordon difference between control plane and other nodes for kubeadm upgrade steps

### ISSUE THREAD

**Issue by rawhideron** [kubernetes/website#37938]
It is not so obvious that you need to run the kubectl drain and uncordon node commands on the control-plane node and the rest on the worker node. the documentation could benefit with some clarity here.

**Comment by sftim** [comment]
Is this feedback for a specific documentation page @rawhideron ? If so, what is its URL?

**Comment by rawhideron** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by sftim** [comment]
/retitle Clarify cordon difference between control plane and other nodes for kubeadm upgrade steps
/sig cluster-lifecycle

**Comment by Kartik494** [comment]
I would like to give a try on this , i think by adding note as clarification for both the nodes is better approach. Please let me know on this.

**Comment by rawhideron** [comment]
Were you asking for my feedback on this? I'm quite new to this but my reply is yes.
