### ISSUE TITLE
Adding glossary tooltip for kube-proxy

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#37949]
**What would you like to be added**
Under [Getting started](https://kubernetes.io/docs/setup/) page,  provide hyperlink for `kube-proxy` 

**Why is this needed**
Adding the hyperlink will helps the readers to know about kube-proxy

**Comments**
/sig docs
/language en
/assign

**Comment by mengjiao-liu** [comment]
Sorry, I accidentally wrote the issue link in my PR, resulting in the link reference on this page.

**Comment by sftim** [comment]
I'd use a [glossary tooltip](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) (which is also clickable).

**Comment by tamilselvan1102** [comment]
@sftim 
shall i proceed with glossary tooltip?

**Comment by dipesh-rawat** [comment]
Changes to address this issue have been merged as part of #38024

/close
