### ISSUE TITLE
Request for Adding a Hyperlink for kube-apiserver

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#37948]
**What would you like to be added**
Under [Getting started](https://kubernetes.io/docs/setup/) page,  provide hyperlink for `kube-apiserver` 

**Why is this needed**
Adding the hyperlink will helps the readers to know about kube-apiserver.

**Comments**
/sig docs
/language en
/assign

**Comment by sftim** [comment]
I'd use a [glossary tooltip](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary).

**Comment by tamilselvan1102** [comment]
@sftim
shall i proceed with glossary tooltip?
