### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/concepts/overview/working-with-objects/names/

### ISSUE THREAD

**Issue by lengcangkuganmian** [kubernetes/website#37946]
Hello, I found some ambiguity in the Chinese translation of the documentation.

In this document(https://kubernetes.io/zh-cn/docs/concepts/overview/working-with-objects/names/)  the third line
in chinese version is:
"比如，在同一个名字空间中有一个名为 myapp-1234 的 Pod，但是可以命名一个 Pod 和一个 Deployment 同为 myapp-1234。"

And in english  version is:
"For example, you can only have one Pod named myapp-1234 within the same namespace, but you can have one Pod and one Deployment that are each named myapp-1234."

The word "only" is missing in the Chinese version, which will cause ambiguity.
Thanks

**Comment by mengjiao-liu** [comment]
It seems that there is indeed an ambiguity, we can modify it.
/assign
