### ISSUE TITLE
Clarify what means immutable by design

### ISSUE THREAD

**Issue by zioproto** [kubernetes/website#37959]
**Problem:**

I find this information confusing:

https://github.com/kubernetes/website/blob/9ac44f2f332144d87499b6b610b45b7bba252bad/content/en/docs/concepts/containers/_index.md?plain=1#L34-L37

Containers are designed to be staless and immutable, but it is the responsibility of the users to maintain these properties. The wording "by design" suggests that the container is immutable however it is used.

It is incorrect that you cannot  change the code of a container that is already running. I have seen the anti-pattern of running `apt-get update && apt-get install <package>` in the containers entrypoint. This makes the container not reproducible, because of the download of a different version of the software every time the container starts, and it proves that the container "by design" is not immutable.

More on this container operations thoughts can be found here:

https://cloud.google.com/architecture/best-practices-for-operating-containers#ensure_that_your_containers_are_stateless_and_immutable

**Proposed Solution:**

I will propose a PR with the following:

Containers are designed to be stateless and immutable: you should not change the code of a 
container that is already running. If you have a containerized application 
 and want to make changes, the correct process is to build a new image that includes 
 the change, then recreate the container to start from the updated image. 

**Page to Update:**
https://kubernetes.io/docs/concepts/containers/

**Comment by sftim** [comment]
/remove-kind bug

I agree: app containers are _intended_ to be immutable, but the container _is_ able to mutate itself and external actors can do that too.
