### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by Jackcrampton** [kubernetes/website#37955]
terminal  hangs with cmd   echo -e "\n\n\n\e[92mstarting proxy.after starting it will not output a response. please click the first terminal tab\n"; kubectl proxy

**Comment by T-Lakshmi** [comment]
`Related page:` https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

**Comment by T-Lakshmi** [comment]
Hi @Jackcrampton,
Terminal is working for me fine, could you please recheck once and confirm. 
Make sure your internet connection should be good.

![image](https://user-images.githubusercontent.com/56723673/202635662-5c3a7bc6-d23e-4f0d-9c8c-66e4c1cb2dcb.png)

**Comment by mengjiao-liu** [comment]
I can use it normally.

**Comment by sftim** [comment]
@Jackcrampton are you still seeing these symptoms?

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
