### ISSUE TITLE
Interactive tutorial is subject to Docker Hub rate limiting

### ISSUE THREAD

**Issue by lukaszkuczynski** [kubernetes/website#37994]
the build on this step of the tutorial keeps failing with Docker rate limits:

https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project system: Could not build image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit -> [Help 1]

**Comment by T-Lakshmi** [comment]
Hi @lukaszkuczynski,

It seems you have reached the number of Docker image downloads (“pulls”).

Docker Hub limits the number of Docker image downloads (“pulls”) based on the account type of the user pulling the image. For anonymous users, the rate limit is set to 100 pulls per 6 hours per IP address. For [authenticated](https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests) users, it is 200 pulls per 6 hour period. Pull requests exceeding these limits will be denied until the six hour window elapses.

you can check your current pull limit and if you reached maximum limit you can wait for next 6hours to resume the pull limit or you can also go for paid services.

For more details visit https://www.docker.com/increase-rate-limits/ and https://www.docker.com/increase-rate-limits/.

**Comment by sftim** [comment]
/retitle Advice on Docker Hub rate limiting

**Comment by T-Lakshmi** [comment]
Issue repeated in #38018.

**Comment by Ritikaa96** [comment]
@lukaszkuczynski if you want to check your current rate limit and more regarding the same follow this [link](https://docs.docker.com/docker-hub/download-rate-limit/#how-can-i-check-my-current-rate)

**Comment by T-Lakshmi** [comment]
Hi @lukaszkuczynski, @Harisalghifary, @pipemonNexplore
Please confirm is this issue resolved for you or still facing the same issue?

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
