### ISSUE TITLE
Getting started page format is not synced with other pages

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#37998]
**This is a Bug Report**

Problem:

1. All the subsections should be described and linked to correspond pages.
   a)  Like `Learning environment` and `Production environment` , **best practices** as well described in this page.
   b)  Like [concepts](https://kubernetes.io/docs/concepts/)  page all subsection should be linked to corresponding pages.

2. remove `Learn about best practice for cluster setup` from [What's next](https://kubernetes.io/docs/setup/#what-s-next)
   Reason : As per point 1, it would be a subsection of this page 

3. Incorrect context in  [What's next](https://kubernetes.io/docs/setup/#what-s-next) section
    [Download and install tools ~~including~~ kubectl] to be changed to [`Download and install tools such as  kubectl  and kind etc`]

4. The sentence between `Learn about best practices for cluster setup` and `Learn to set up clusters with Windows nodes`  in the  [What's next](https://kubernetes.io/docs/setup/#what-s-next) section should be  removed and copied to [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/ ) page.

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/

**Comment by sftim** [comment]
> 3\. Incorrect context in  [What's next](https://kubernetes.io/docs/setup/#what-s-next) section

I don't think that content is _incorrect_.



> 4\. The sentence between `Learn about best practices for cluster setup` and `Learn to set up clusters with Windows nodes`  in the  [What's next](https://kubernetes.io/docs/setup/#what-s-next) section should be  removed and copied to [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/) page.

I disagree here. People might want to learn that Kubernetes is designed for its control plane to run on Linux (only), and that nodes but not the control plane can also run Windows.

/priority awaiting-more-evidence

I'd like to be convinced about why we should make the changes you're suggesting @tamilselvan1102 
Was there something you didn't enjoy about the existing page and how it is written?

@tami

**Comment by tamilselvan1102** [comment]
3. [Download and install tools including kubectl] under this topic having various tools details are there to be installed. But here specifically mentioned only kubectl. That's why thought to rewrite.

4. [What's next] section have to focus on pinpoint to features not detailed description. That's why thought to move the description to [Windows in Kubernetes](https://kubernetes.io/docs/concepts/windows/) section. Otherwise move the content as attached file.
<img width="501" alt="WhatsNext" src="https://user-images.githubusercontent.com/20103020/203271799-3659e8d6-fd54-486a-a7b5-3eb22d2bf31d.png">

**Comment by tamilselvan1102** [comment]
@sftim
could you please check the above proposal?

**Comment by sftim** [comment]
I'm afraid that I don't fully understand what you're proposing @tamilselvan1102

You're welcome to open a pull request to illustrate how you think the page should look; that might be easier. Please do consider that we might prefer the existing page (I remember updating it to the current format within the last couple of years, and at the time I was happy with those improvements). Of course, there are lots of reviewers and there is more than one opinion, not just mine.

So long as you're willing for the answer to be "no", we're very very happy to consider making changes.

**Comment by tamilselvan1102** [comment]
@sftim 
Sorry, This was an oversight. 
I thought to make only bullet points in the [What's next](https://kubernetes.io/docs/setup/#what-s-next) section.
