### ISSUE TITLE
Install and Set Up kubectl on Linux

### ISSUE THREAD

**Issue by adejonghm** [kubernetes/website#37992]
The content of the kubernetes.repo file has an error in the ` baseurl`   variable. This string has a "\\" before `  $basearch`  and the correct URL does not.

[Current content:]

![Screenshot_2022-11-20_22-44-57](https://user-images.githubusercontent.com/29492844/202943928-3f9abf22-5a09-453b-a32d-599faddae669.png)

I had an error running `  sudo dnf update`   after adding the content to the file.

**Comment by mengjiao-liu** [comment]
There is no problem with this command. When you apply this command, you will find the actual `kubernetes.repo` file shown below:
```
kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
enabled=1
gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
```

This string has a `\` before `$basearch`,which is to prevent `$basearch` from being treated as a variable of the current bash and not being written to the file.

**Comment by sftim** [comment]
/remove-label needs-triage
/close

There's clearly nothing here to fix. @adejonghm if you're convinced otherwise, please reopen this issue.
