### ISSUE TITLE
Documentation about `imagePullPolicy` confuses readers

### ISSUE THREAD

**Issue by rinocata** [kubernetes/website#38005]
The section on `imagePullPolicy` seems to be misleading. `Always` seems to, well, always pull images no matter what despite what the description says.

**Comment by mengjiao-liu** [comment]
page: https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy

/kind support

**Comment by utkarsh-singh1** [comment]
/language en

Hi @rinocata, `always` value of `imagePullPolicy` ensures that the latest image of container is present every time you create, deploy or run the pod.

> You can find more details about the default value of `imagePullPolicy` here -  https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

**Comment by rinocata** [comment]
You seem to be correct @utkarsh-singh1 but the page you linked contradicts the one @mengjiao-liu (thanks) posted.

> If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image

This seems to be the behavior of `IfNotPresent`, not `Always`.

**Comment by rinocata** [comment]
Also, it's not dependent on container runtime, same behavior occurs with containerd and CRI-O. My guess is simply unverified or outdated information.

**Comment by sftim** [comment]
> Also, it's not dependent on container runtime, same behavior occurs with containerd and CRI-O. My guess is simply unverified or outdated information.

Although two container runtimes both behave a particular way, that doesn't mean we can conclude they all behave that way.

Issue 37926 is very similar to this.

/remove-kind support
/triage duplicate

**Comment by sftim** [comment]
/retitle Documentation about `imagePullPolicy` confuses readers

**Comment by sftim** [comment]
I'd like to see some evidence that the existing text is factually incorrect. I'm very willing to accept that it's not easy to understand, but I believe that it's not actually _wrong_.

**Comment by rinocata** [comment]
Would `kubectl describe pod` logs constitute evidence?

**Comment by sftim** [comment]
> Would `kubectl describe pod` logs constitute evidence?

The way I'm imagining this, you'd also need to show the state of the image cache for the container runtime used on that node before the Pod was scheduled there.

**Comment by sftim** [comment]
Please add any evidence to https://github.com/kubernetes/website/issues/37926 (which this issue pretty much duplicates)

**Comment by rinocata** [comment]
>show the state of the image cache for the container runtime 
Would `crictl` output be enough?

**Comment by sftim** [comment]
Let's continue discussion in issue #37926

**Comment by mehabhalodiya** [comment]
Per [this comment](https://github.com/kubernetes/website/issues/38005#issuecomment-1325620714), I am closing this issue. Thanks!

/close
