### ISSUE TITLE
Advice on Docker Hub rate limiting

### ISSUE THREAD

**Issue by pipemonNexplore** [kubernetes/website#38018]
Commands crash with [ERROR] toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.

` mvn package -pl system `
` mvn package -pl inventory `

**Comment by jihoon-seo** [comment]
This issue seems a duplicate of #37994.
/triage duplicate

**Comment by Ritikaa96** [comment]
Hi @pipemonNexplore 
@T-Lakshmi had given an explanation for the same issue [here] (https://github.com/kubernetes/website/issues/37994#issuecomment-1321724170)

You can see if this helps you with your issue as both logged issues are same.

**Comment by sftim** [comment]
/retitle Advice on Docker Hub rate limiting

**Comment by sftim** [comment]
To help avoid people asking for advice, perhaps we could find a different home for the images that this tutorial relies upon?

**Comment by Ritikaa96** [comment]
> This issue seems a duplicate of #37994. /triage duplicate

If this issue is a duplicate of the #37994 , then it Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/). The same has been mentioned in the linked issue.

**Comment by Ritikaa96** [comment]
If there is no further problem , shall we close this issue?

**Comment by T-Lakshmi** [comment]
@pipemonNexplore, I hope your issue is resolved now.

With reference to parent issue #37994 [comment](https://github.com/kubernetes/website/issues/37994#issuecomment-1435646490) i am closing this issue.

/close
