### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by Harisalghifary** [kubernetes/website#38028]
![image](https://user-images.githubusercontent.com/47595840/203573586-c72c2daa-07c1-4c95-82cd-fcf448a63859.png)
Error when build project using maven with error message : Could not build image: toomanyrequests: You have reached your pull rate limit.

**Comment by T-Lakshmi** [comment]
This issue is already reported in #37994 and #38018.
/traige duplicate

**Comment by T-Lakshmi** [comment]
Hi @Harisalghifary,
I had given an explanation for the same issue here #37994, you can check it once. 
I hope that will resolve your query.

**Comment by T-Lakshmi** [comment]
@Harisalghifary,
Please confirm are you still facing the same issue.
