### ISSUE TITLE
Confusing word (pod pair) in Garbage collection page.

### ISSUE THREAD

**Issue by amosshapira** [kubernetes/website#38026]
The description of `MaxPerPodContainer` under [Conrainer garbage collection](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#container-image-garbage-collection) mentions `Pod pair` without explaining what it means:
> MaxPerPodContainer: the maximum number of dead containers each Pod pair can have. Disable by setting to less than 0.

I suspect that this is a typo and `pair` should be removed.

**Comment by kundan2707** [comment]
@amosshapira  here pod pair mean pod (UID, container name) pair. 
I will update doc for better understanding

**Comment by kundan2707** [comment]
/retitle Confusing word (pod pair) in Garbage collection page.
