### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/dns-pod-service/

### ISSUE THREAD

**Issue by JuliaMongo** [kubernetes/website#38033]
Please allow linking to items within the generated API reference. For example, we needed a link to publishNotReadyAddresses in the [API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/), but couldn't get it.
Also, there is something with the search for this setting. When searching for it, the results that come up point to the 1.21 version of the API reference, which is not the latest.

**Comment by tengqm** [comment]
This would be difficult to implement if possible at all. There are cases where structs share the same field names. Adding anchors to the API reference page is an option. You can file an issue at kubernetes-sigs/reference-docs repo.

**Comment by JuliaMongo** [comment]
@tengqm how do I file an issue with that repo? Could you please share a link? I am sorry for not replying sooner, I haven't noticed that you replied to me and very much appreciate your reply. Thank you!

**Comment by tengqm** [comment]
@JuliaMongo https://github.com/kubernetes-sigs/reference-docs/issues

**Comment by JuliaMongo** [comment]
I opened the issue in the repo you suggested, @tengqm

**Comment by JuliaMongo** [comment]
@tengqm please reopen the issue.

**Comment by tengqm** [comment]
/close
This is not supposed to be fixed here.
