### ISSUE TITLE
Unable to connect the Azure Sql Server DB from the K8s pod

### ISSUE THREAD

**Issue by anandarajr** [kubernetes/website#38039]
Hi Team,

I have set up kubenetes cluster using the tool "KubeAdm" by creating following virtual machines in AWS.
	Master Node VM: Ubuntu
	Worker Node VM: Windows Server 2019

	When I run the docker image (using the yaml file provided below), it is not able to connect with Azure SQL Server DB from the kubernetes pod. Getting below error. 
	
        **Yaml file:**

	apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: XXXX
	  namespace: xx
	spec:
	  replicas: 1
	  selector:
		matchLabels:
			app: xxxx
	  template:
		metadata:
		  labels:
			lbtype: external
			app: xxx
		spec:
		  nodeName: xxx
		  containers:
		  - image: xxx
			imagePullPolicy: Always
			name: xxx
			ports:
			  - containerPort: 80
				name: "configport"
		  nodeSelector:
		   kubernetes.io/os: windows
	
	**Error.**
	
	A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configure
	d to allow remote connections. (provider: TCP Provider, error: 0 - No such host is known.) ---> System.ComponentModel.Win32Exception (0x80004005): No such host is known	

Kindly suggest.

**Comment by sftim** [comment]
/kind support


GitHub is not the right place for support requests @anandarajr 

If you are looking for help about using Kubernetes, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and ask your question there if a similar question has not yet been answered.

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
