### ISSUE TITLE
Add references and glossary tooltip in the control-plane-node-communication page

### ISSUE THREAD

**Issue by Ritikaa96** [kubernetes/website#38049]
**This is a Feature Request**

**What would you like to be added**
- There are terms that can use the addition of a glossary tooltip to show the meaning of the said term. 
- There is no `what's next` or reference section
- Some terms can use references like : `hub and spoke API pattern `, `SSH tunnels`

**Why is this needed**
Rather than searching for the definitions of  some terms , the references can help understanding the concept while staying on same page or finding more about the concept with right link. it will enhance user experience and bring more clarity and less confusion.

**Comments**
- The page needed to be updated here is : https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/

**Comment by Ritikaa96** [comment]
If the triage is accepted would be happy to contribute references I have searched while reading the concept.
/assign

**Comment by sftim** [comment]
Worth doing, but the change I outline in https://github.com/kubernetes/website/issues/29049#issuecomment-885977653 is more valuable to work on.

**Comment by Ritikaa96** [comment]
https://github.com/kubernetes/website/issues/29049#issuecomment-885977653 here seems to be about the https://kubernetes.io/docs/concepts/architecture/ and https://kubernetes.io/docs/concepts/architecture/nodes/ page in particular.
I'd agree with the general idea of making the content brief and putting extra information in the reference. 

For control-plane-node-communication page, I see your comment about adding a diagram there. Will try to add that as well.

**Comment by Ritikaa96** [comment]
@sftim  For now, I'll push this commit, in case even if we shift this content to reference or another section, we would still need some of the links and references.
