### ISSUE TITLE
Enable click-to-zoom for some diagrams and other images

### ISSUE THREAD

**Issue by Ritikaa96** [kubernetes/website#38051]
**This is a Feature Request**

Some images in concepts sections are quite detailed but in normal scope the texts inside of them look small and unreadable.
Can we add feature for the images to pop up on clicking?
It will add to the user experience as well as ease the pain of zooming out the page in whole. 

**What would you like to be added**
Feature to Pop up images on click

**Why is this needed**
The texts and details seem too small to read.

**Comments**
Reference of some of the pages where the issue arises:
- https://kubernetes.io/docs/concepts/overview/#going-back-in-time
- https://kubernetes.io/docs/concepts/overview/components/

Example to the pop-up view for image:
https://keda.sh/docs/2.7/concepts/#architecture

**Comment by sftim** [comment]
/area web-development

Something similar to https://medium-zoom.francoischalifour.com/ ?

**Comment by sftim** [comment]
/retitle Enable click-to-zoom for some diagrams and other images

**Comment by Ritikaa96** [comment]
Thanks @sftim ,
I investigated on hugo's documents regarding any shortcode or feature that provide this functionality. but till now haven't found any.

**Comment by Ritikaa96** [comment]
For now I'll investigate more and try to find out what can work so assigning it to myself
/assign

**Comment by sftim** [comment]
A couple of hints:
```html
{{- if .HasShortcode "figure" -}}

<!-- Enable zoom-on-click for figures that opt in to this -->
<script defer src="{{ "/js/zoom.js" | relURL }}"></script>
{{- end -}}
```

```markdown
{{<figure src="/images/blog/2019-03-21-a-guide-to-kubernetes-admission-controllers/admission-controller-phases.png" clicktozoom="true" >}}
```

**Comment by Ritikaa96** [comment]
There is one more way like the above reference link mentioned,
If we put full-resolution images in other paths and do this :
`[![Alternative Text](/path/of/image.jpg)](/path/to/image.jpg)`

It is in case we want minimal change in the code. 
I'm going to add ways here as I find so the community can vote or suggest which will be better for a clean code

**Comment by Ritikaa96** [comment]
[This](https://github.com/adityatelange/hugo-PaperMod/issues/384#issuecomment-899219940)
one is a good reference for same functionality with example.
I'll try both and raise a PR after that.

**Comment by sftim** [comment]
> full-resolution images

We [recommend](https://kubernetes.io/docs/contribute/style/diagram-guide/) using vector images.

**Comment by Ritikaa96** [comment]
My apologies,Due to bandwidth issue couldn't work on this, It's open for other people to self-assign.

**Comment by dipesh-rawat** [comment]
This could be a positive and beneficial addition to the website. 
Worth doing (re-triaging as accepted).

/triage accepted
/lifecycle frozen

**Comment by dipesh-rawat** [comment]
Let me see if I can assist with this.
