### ISSUE TITLE
Update scheduling framework page with latest changes

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/website#38069]
**This is a Feature Request**

**What would you like to be added**

In v1.26, we introduced a new extension point in scheduling framework named `PreEnqueue`, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3521-pod-scheduling-readiness, but this page hasn't been updated https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/scheduling-eviction/scheduling-framework.md, we should populate this.

**Why is this needed**

Keep the document up-to-date.

**Comments**

/sig scheduling
/kind help

**Comment by YashPimple** [comment]
@kerthcet could you make elaborate on what I need to change since I am unable to understand the feature request?

**Comment by kerthcet** [comment]
I mean we should add another extension point named `PreEnqueue`, which is new introduced in last release v1.26.

**Comment by haripriya9647** [comment]
@YashPimple are you still working on this issue ??

**Comment by kerthcet** [comment]
Thanks @haripriya9647 for your attention, but I think we have updated the document. See https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/scheduling-eviction/scheduling-framework.md#preenqueue-pre-enqueue

So I'd like to close it.
/close
