### ISSUE TITLE
Add more points to What's Next section under init-containers page.

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#38066]
**This is a Bug Report**
**Problem:**
[What's next](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#what-s-next) section of [init-containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) page does not cover all required reference points which are mentioned throughout page.
**Proposed Solution:**
Add references of below topics under what's next section of [init-containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) page.
- learn about service, volume.
- kubelet, kubectl overview.
- Garbage Collection that Kubernetes uses to clean up cluster resources.
- Types of probes. Liveness, Readiness and Startup Probes.
**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

**Comment by sftim** [comment]
/remove-kind bug
/triage accepted

I'm not sure how much we need to tell people about Services and Volumes; maybe we should instead signpost readers to learn more about Pods in general - perhaps links to specific fragments of relevant Pod pages?

Same for garbage collection really.

**Comment by T-Lakshmi** [comment]
> I'm not sure how much we need to tell people about Services and Volumes; maybe we should instead signpost readers to learn more about Pods in general - perhaps links to specific fragments of relevant Pod pages?

Sure @sftim , In that case i will add one link in general to know more about pods and service under What's next section.

> Same for garbage collection really.

For garbage collection its already available under what's next section. So i will not add reference link inside page.

**Comment by T-Lakshmi** [comment]
Hi @sftim ,
Below, i prepared the preview changes what i am planning to do as per my understanding based your comment above. I would like to confirm is these changes you were expecting to do for this issue.
![init-container1](https://user-images.githubusercontent.com/56723673/205045046-8f13ed2a-92b5-469f-a77a-464c481fa3e2.png)

Please suggest.

**Comment by T-Lakshmi** [comment]
Hi @sftim,
Could you please confirm on above comment.

**Comment by T-Lakshmi** [comment]
Hi @sftim,
Could you please take a look on 

> Hi @sftim , Below, i prepared the preview changes what i am planning to do as per my understanding based your comment above. I would like to confirm is these changes you were expecting to do for this issue. ![init-container1](https://user-images.githubusercontent.com/56723673/205045046-8f13ed2a-92b5-469f-a77a-464c481fa3e2.png)
> 
> Please suggest.

Hi @sftim,
Please confirm if these changes sounds good to you. So that i can go ahead and work on it, Thanks.

**Comment by sftim** [comment]
When adding links, please use links that have words like “volumes”; readers don't need to see the URL.

If you send in a pull request @T-Lakshmi, we can offer feedback on it directly. Ideally we can accept it as is!

**Comment by T-Lakshmi** [comment]
@sftim,
Thanks for your response, i will soon open a PR for it.

**Comment by T-Lakshmi** [comment]
Fixed it here #41514.
