### ISSUE TITLE
Move or remove the detailed steps for Secret use cases from the concept

### ISSUE THREAD

**Issue by shannonxtreme** [kubernetes/website#38084]
Umbrella issue: #4491

https://kubernetes.io/docs/concepts/configuration/secret/#use-cases contains multiple "use cases" for Secrets. However, many of these are mini-tasks. In this issue, I'd like to discuss each of these use cases at a high level to see which we can remove, which we can trim, and which we can move to a new or existing task page. That way, the "Use cases section could even be a bulleted list with links to relevant tasks.

## Discussion items

*  Use case: As container environment variables
    *  Recommendation: Delete 
    * Justification: the goal is achieved in [Define container environment variables using Secret data](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data). This also isn't a use *case*, it's a way to use a secret.
*  Use case: Pod with SSH keys
    *  Recommendation: Delete content, keep use case as bullet
    *  Justification: the steps add no value beyond the existing task to [use a secret as a volume](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume).
*  Use case: Pods with prod / test credentials
    *  Recommendation: Move content to a new or existing task
    *  Justification: The content is complex enough that it can be its own task, either as part of [Distribute Credentials Securely Using Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume) or a new task page.
*  Use case: dotfiles in a secret volume
    *  Recommendation: Remove steps and keep as bullet point with additional info about why it would be useful.
*  Use case: Secret visible to one container in a Pod
    *  Recommendation:  Move content to a new or existing task
    *  Justification: The content is complex enough that it can be its own task, either as part of [Distribute Credentials Securely Using Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume) or a new task page with actual steps to achieve more than just "secret visible to one container". Perhaps including RBAC steps.

## What you need to do

If you're interested, review each use case and leave a comment for each agreeing, disagreeing, or providing a different approach to each use case. 
 
After we've discussed and settled on an action for these use cases, we can start the actual work!

/sig docs
/cc @sftim

**Comment by sanchita-07** [comment]
I think the "Use case: As container environment variables" can be removed as the goal is achieved in [Using Secrets as environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) too.

**Comment by shannonxtreme** [comment]
> I think the "Use case: As container environment variables" can be removed as the goal is achieved in [Using Secrets as environment variables](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) too.

Yeah agreed, although I'm separately removing that section and linking it to our existing task page as part of #38083

**Comment by sanchita-07** [comment]
Let's shift "Use case: Pods with prod/test credentials"  and "Use case: secret visible to one container in a Pod" to [Distribute Credentials Securely Using Secrets](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#create-a-pod-that-has-access-to-the-secret-data-through-a-volume) and attach the link in the use case section as bullet notes.

**Comment by shannonxtreme** [comment]
Imo the prod/test thing might not even need to move - it can live as an example in the concept but the task steps seem quite basic now that I think about it. Just referencing two Secrets in two different Pods...
