### ISSUE TITLE
Advice on nesting Kubernetes clusters

### ISSUE THREAD

**Issue by Olg-star** [kubernetes/website#38094]
Is there any way to achieve hierarchical arrangement in k8s?That is, can a master node become a node of another master node?

**Comment by kundan2707** [comment]
@Olg-star  there could me multiple master nodes in a high availability  cluster in which inactive cluster will act as node and when active master will be done another one can take over.

**Comment by Olg-star** [comment]
> /retitle Advice on nesting Kubernetes clusters
> 
> This _is_ support, but we could also document that it's possible to do this.

Thank you. But do you know how to implement it?

**Comment by sftim** [comment]
GitHub is not the right place for support requests.

For help, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
