### ISSUE TITLE
Wrong Links for SupportNodePidsLimit and  SupportPodPidsLimit feature gates.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#38118]
**This is a Bug Report**

From  k8s v1.24 the `SupportNodePidsLimit` and  `SupportPodPidsLimit` are no longer available as a feature gate in k8s. From v1.25 there is a separate document that contains information on feature gates that have been removed i.e. [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/).

In the [Process ID Limits And Reservations](https://kubernetes.io/docs/concepts/policy/pid-limiting/) `SupportNodePidsLimit` and  `SupportPodPidsLimit` feature gate link to the[ Feature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) page which is incorrect, instead of that, it should be [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/) page. The information for both feature gates is on the Feature Gates (removed) page not on the Feature Gates page. 

**Proposed Solution:**
SupportNodePidsLimit and  SupportPodPidsLimit feature gates should be linked to` https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/` instead of `https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/`
**Page to Update:**
https://kubernetes.io/docs/concepts/policy/pid-limiting/

**Comment by tengqm** [comment]
For GA'ed feature or deprecated feature, if the gate is removed, we may want to remove the linking texts altogether rather than having existing text pointing to the outdate gate names.

**Comment by Shubham82** [comment]
Hi @tengqm 
Just want to confirm it: So for this, you want to remove the whole note section for both feature gates, because both feature gates are removed.
Am I understanding right?

**Comment by Shubham82** [comment]
> Just want to confirm it: So for this, you want to remove the whole note section for both feature gates, because both feature gates are removed.
> Am I understanding right?

@tengqm, is it seems good to you?

**Comment by tengqm** [comment]
@Shubham82 I meant this: move the "removed" feature to the dedicated page, if this is not done yet. The "removed" features will stay there for the sole purpose of reference. For all texts (including notes) that reference these gates, remove those references. If a feature is deprecated and removed, those texts may well become invalid. If a feature is GA'ed and removed, those texts may be still valid, but the reference to the gate should disappear.

**Comment by Shubham82** [comment]
> @Shubham82 I meant this: move the "removed" feature to the dedicated page, if this is not done yet. The "removed" features will stay there for the sole purpose of reference. For all texts (including notes) that reference these gates, remove those references. If a feature is deprecated and removed, those texts may well become invalid. If a feature is GA'ed and removed, those texts may be still valid, but the reference to the gate should disappear.

Thanks, @tengqm for your response.

**Comment by Shubham82** [comment]
`SupportNodePidsLimit` and `SupportPodPidsLimit` both feature gates were graduated in v1.20 and removed in v1.23. Both are present on the dedicated page i.e.  [Feature Gates (removed)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/). So I will remove the reference to these gates.

**Comment by Shubham82** [comment]
I will create PR for it soon.

**Comment by Shubham82** [comment]
Fixed it here: #38224
