### ISSUE TITLE
Label `kube-aggregator.kubernetes.io/automanaged` not registered / documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38126]
**This is a Bug Report**

**Problem:**
Code from the Kubernetes project sets (or previously did set) a label, `kube-aggregator.kubernetes.io/automanaged`

This looks intended, but https://kubernetes.io/docs/reference/labels-annotations-taints/ doesn't document that label.

**Proposed Solution:**
Document that label; as a side effect, this registers it. If it's deprecated, we should mark it as deprecated but still document it.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/language en
/priority backlog

**Comment by Ritikaa96** [comment]
Created a [PR](https://github.com/kubernetes/website/pull/38161), Havent seen any document for it's deprecation . Please let me know if any change is needed.

**Comment by Ritikaa96** [comment]
Since this issue's PR is already merged. i'd like to close it
