### ISSUE TITLE
xfs.org site is unreachable.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#38146]
**This is a Bug Report**

**Problem:**
The link for XFS is unreachable under [What's next](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#what-s-next) in [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).  Below is the screenshot  of the error: 
![Screenshot from 2022-11-29 12-11-33](https://user-images.githubusercontent.com/50987400/204460349-fec6610e-7379-475f-9e5b-617b1580922e.png)

**Proposed Solution:**
It should be redirected to the reachable site for XFS.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by Shubham82** [comment]
cc @sftim 
PTAL!

**Comment by sftim** [comment]
https://xfs.wiki.kernel.org/ is a similar site about XFS (specifically on Linux)

**Comment by sftim** [comment]
/unassign

I don't feel I have special insight into this bug.

**Comment by Shubham82** [comment]
Thanks, @sftim for your input.

**Comment by Shubham82** [comment]
Hi, @SaumyaBhushan Are you working on this issue?

**Comment by SaumyaBhushan** [comment]
Let me raise a PR @Shubham82

**Comment by Shubham82** [comment]
Thanks @SaumyaBhushan

**Comment by Shubham82** [comment]
I have asked in the slack channel about it. Here is the link for it:
https://kubernetes.slack.com/archives/C1J0BPD2M/p1676428883647819

**Comment by SaumyaBhushan** [comment]
Hi, @Shubham82 I have created PR but I can't find the exact resource in the suggested link by @sftim .

**Comment by Shubham82** [comment]
@SaumyaBhushan, for that I asked in the sig-docs slack channel, let's see what folks will suggest.

**Comment by SaumyaBhushan** [comment]
> @SaumyaBhushan, for that I asked in the sig-docs slack channel, let's see what folks will suggest.

Sure Thanks a lot @Shubham82
