### ISSUE TITLE
[fr] Broken link in Dashboard task page

### ISSUE THREAD

**Issue by Heronal** [kubernetes/website#38149]
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml

This command line is not working due to the error 404 on the link, 
Have a good day

**Comment by utkarsh-singh1** [comment]
/language fr

Thanks, @Heronal, for raising this issue, can you also provide link to the doc where you have found this issue?

**Comment by Heronal** [comment]
Of course, there it is:

https://kubernetes.io/fr/docs/tasks/access-application-cluster/web-ui-dashboard/

**Comment by utkarsh-singh1** [comment]
I think french docs have not been updated with the latest link

as in English doc - https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.6.1/aio/deploy/recommended.yaml`

It is working, as I have tested just now.

**Comment by utkarsh-singh1** [comment]
Hi @Heronal, Your issue has been resolved , it you have other issues please state them or  you can close this issue.

**Comment by sftim** [comment]
/remove-triage needs-information
/remove-lifecycle stale

/retitle [fr] Broken link in Dashboard task page
