### ISSUE TITLE
Update What's next section under Deployment page

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#38159]
**This is a Feature Request**
**What would you like to be added**
I would like to add below references under `What's next section` of `Deployment` page.
1. Using kubectl to [Create a Deployment](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/)
2. Interactive Tutorial - [Deploying an App](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/)

**Why is this needed**
Above Reference links providing interactive tutorial sections for Deployment which are more helpful to the user to understand the concept clearly and provide hands-on experience.  
**Comments**
Page to update: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by T-Lakshmi** [comment]
Fixed it here #38230.

**Comment by T-Lakshmi** [comment]
PR is not reviewed as label triage accepted not added yet for this issue.
can anyone please check and accept triage for this.

**Comment by divya-mohan0209** [comment]
Hey @T-Lakshmi , point #2 will not be required in light of the recent Katacoda removals. 
However,  otherwise, I'm okay with these additions.
/triage accepted

**Comment by T-Lakshmi** [comment]
Hi @divya-mohan0209,
Agree with removing point https://github.com/kubernetes/website/issues/2 and also thanks for triaged the issue.
