### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/static-pod/

### ISSUE THREAD

**Issue by devinbost** [kubernetes/website#38157]
It would be helpful to provide more information about how to troubleshoot issues when a static pod isn't starting since it's not clear how to get log information on a pod that doesn't appear in the list of pods when running `crictl ps` or `kubectl get pods`

**Comment by T-Lakshmi** [comment]
/kind documentation
/sig docs
/language en
Page to update: [k8s.io/docs/tasks/configure-pod-container/static-pod](url)

**Comment by kundan2707** [comment]
@devinbost  a separate documentation is present for monitoring and debugging pods or getting logs.
https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#debugging-pods
you can get information related to various scenarios

**Comment by Ritikaa96** [comment]
> Page to update: [k8s.io/docs/tasks/configure-pod-container/static-pod](https://github.com/kubernetes/website/issues/url)

I guess you mean: https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

I understand debugging-pods doesn't contain information regarding the static pod logs and troubleshooting as much but there is page for same information with https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#get-a-container-s-logs

**Comment by Ritikaa96** [comment]
As @devinbost  mentioned

> it's not clear how to get log information on pod that doesn't appear in the list of pods when running `crictl ps` or `kubectl get pods`

In the page mentioned above , you can find a warning [here](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#get-a-container-s-logs) that state:


 

> **Warning**: If you use crictl to create pod sandboxes or containers on a running Kubernetes cluster, the **Kubelet will eventually delete** them. crictl is not a general purpose workflow tool, but a tool that is useful for debugging.

In such cases according  to this issue: https://github.com/kubernetes-sigs/cri-tools/issues/266
We need to use `crictl ps -a` to get the container list created by crictl not `crictl ps`.

Let me know if this was the case.

**Comment by Ritikaa96** [comment]
Maybe we can add a reference for same in the static pod document [here](https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/#behavior-of-static-pods). It will be lot helpful for someone not having idea of how to get logs for static pods.

**Comment by Ritikaa96** [comment]
Hi @devinbost Hope your query is resolved , also I think for future purposes I have added some more info on the page you mentioned in [this](https://github.com/kubernetes/website/pull/38229) PR
