### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

### ISSUE THREAD

**Issue by hlavki** [kubernetes/website#38160]
Example on this page does not work, because second pod is terminated, so it tries to restart it and finally became degradated. This scenario will work if second container was `initContainer`. Would be helpful provide real-word examples. Thanks

**Comment by hlavki** [comment]
triage/accepted

**Comment by Kartik494** [comment]
Hi @hlavki i have tried this in my environment and it's running fine  i.e i can communicate from between two pods 

ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.2   8924  5556 ?        Ss   05:09   0:00 nginx: master process nginx -g daemon off;
nginx         29  0.0  0.1   9312  2628 ?        S    05:09   0:00 nginx: worker process
root          30  0.0  0.1   4156  3440 pts/0    Ss   05:14   0:00 /bin/bash
root         371  0.0  0.1   6752  2996 pts/0    R+   05:14   0:00 ps aux
root@two-containers:/# curl localhost
Hello from the debian container

**Comment by hlavki** [comment]
This is strange, because if you look into this article, there is the part where the status of both containers is printed and debian container is in `terminated` state:
```
kubectl get pod two-containers --output=yaml
```

**Comment by Kartik494** [comment]
> Hi @hlavki i have tried this in my environment and it's running fine i.e i can communicate from between two pods
> 
> ps aux USER PID %CPU %MEM VSZ RSS TTY STAT START TIME COMMAND root 1 0.0 0.2 8924 5556 ? Ss 05:09 0:00 nginx: master process nginx -g daemon off; nginx 29 0.0 0.1 9312 2628 ? S 05:09 0:00 nginx: worker process root 30 0.0 0.1 4156 3440 pts/0 Ss 05:14 0:00 /bin/bash root 371 0.0 0.1 6752 2996 pts/0 R+ 05:14 0:00 ps aux root@two-containers:/# curl localhost Hello from the debian container

 i was mentioning here that i was able to communicate with containers in the  same pod shared volume,  and yes one of my pod is in running state i.e nginx only, i am not so sure on  running second container in same pod as `init` container.

**Comment by Kartik494** [comment]
May be this part

> The Volume in this exercise provides a way for Containers to communicate during the life of the Pod. If the Pod is deleted and recreated, any data stored in the shared Volume is lost

 
 in the  [discussion](https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/#discussion) would help you in this.

**Comment by hlavki** [comment]
ok thanks, I see the point, but this example shows basically edge case. What I was looking for is real world example, where we needed to copy data on startup from one container to another and stay healthy.
Maybe there is a space to improve documentation by adding example like this. 
And yes, when you use initContainer and pod is deleted and recreated, shared volume data are also lost.

**Comment by Kartik494** [comment]
@hlavki sure i will check with `init` container also.

**Comment by Kartik494** [comment]
@hlavki i have checked this and found that it works for init container also.

> Events:
>   Type    Reason     Age    From               Message
>   ----    ------     ----   ----               -------
>   Normal  Scheduled  2m20s  default-scheduler  Successfully assigned default/two-containers to node01
>   Normal  Pulling    2m19s  kubelet            Pulling image "debian"
>   Normal  Pulled     2m15s  kubelet            Successfully pulled image "debian" in 4.857357629s
>   Normal  Created    2m14s  kubelet            Created container debian-container
>   Normal  Started    2m14s  kubelet            Started container debian-container
>   Normal  Pulling    2m13s  kubelet            Pulling image "nginx"
>   Normal  Pulled     2m9s   kubelet            Successfully pulled image "nginx" in 4.989820473s
>   Normal  Created    2m8s   kubelet            Created container nginx-container
>   Normal  Started    2m8s   kubelet            Started container nginx-container

> root@two-containers:/# ps aux
> USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> root           1  0.0  0.2   8924  5584 ?        Ss   06:49   0:00 nginx: master process nginx -g daemon off;
> nginx         28  0.0  0.1   9312  2648 ?        S    06:49   0:00 nginx: worker process
> root          29  0.0  0.1   4156  3480 pts/0    Ss   06:50   0:00 /bin/bash
> root         370  0.0  0.1   6752  2888 pts/0    R+   06:51   0:00 ps aux
> root@two-containers:/#  curl localhost
> Hello from the debian container

pod status:

> kubectl get pods
> NAME             READY   STATUS    RESTARTS   AGE
> two-containers   1/1     Running   0          2m14s

**Comment by Kartik494** [comment]
this is the corresponding changes in yaml

  containers:
  - name: nginx-container
    image: nginx
   volumeMounts:

    - name: shared-data

      mountPath: /usr/share/nginx/html

  initContainers: 

  - name: debian-container

    image: debian

    volumeMounts:

    - name: shared-data

      mountPath: /pod-data

    command: ["/bin/sh"]

    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]


i would like to raise the PR if community agrees on this changes.

**Comment by hlavki** [comment]
Hi @Kartik494, great to hear that. I appreciate your time on this task and hope the community will agree.
