### ISSUE TITLE
I want to contribute to this project but I am a newbie can someone please guide me how can I start?

### ISSUE THREAD

**Issue by ShivankK26** [kubernetes/website#38193]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by utkarsh-singh1** [comment]
Hi @ShivankK26, below are some links that will help you to start in contributing for Kubernetes.

https://www.kubernetes.dev/docs/guide/#contributor-guide

https://kubernetes.io/docs/contribute/

https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md
