### ISSUE TITLE
RBAC / Default kubernetes users are not documented

### ISSUE THREAD

**Issue by lc4ntoni-centralway** [kubernetes/website#3820]
Hello,

I'm attempting to setup a kubernetes cluster (1.5.4) with RBAC support , but I'm having problems related to the fact that some components are not using only service accounts, but also "users" defined within kubernetes, for which I can't find documentation and for which the default clusterrolebindings apparently are not sufficient for maintaining an healthy cluster. I've found a list of users and group  by looking into the sources which I'm not sure is complete:

```
// well-known user and group names
const (
    SystemPrivilegedGroup = "system:masters"
    NodesGroup            = "system:nodes"
    AllUnauthenticated    = "system:unauthenticated"
    AllAuthenticated      = "system:authenticated"

    Anonymous     = "system:anonymous"
    APIServerUser = "system:apiserver"

    // core kubernetes process identities
    KubeProxy             = "system:kube-proxy"
    KubeControllerManager = "system:kube-controller-manager"
    KubeScheduler         = "system:kube-scheduler"
)
```

The only way (for now) I got my cluster working was by giving the cluster-admin privileges to all the authenticated users, which is way insecure.

I think that people attempting to configure RBAC would benefit of having some documentation regarding the default kubernetes users, which components are using them and what type of privileges they require on the cluster.

Also some commands like
```
kubectl get users
kubectl create user
kubectl get groups
kubectl create group
```
Would be useful. Let me know if I should open another issue for this.

**Comment by liggitt** [comment]
user creation is the responsibility of the installation/deployment, and depends on the authentication methods configured. for example, some deployments configure x509 client certificate authentication, some configure bearer token authentication. the method for creating a new user varies by auth mechanism.

**Comment by julian-alarcon** [comment]
This would be really helpful. I have the same issue trying to setup a Cluster from scratch.
Thanks for your help @lc4ntoni-centralway !
