### ISSUE TITLE
Outdated minikube information

### ISSUE THREAD

**Issue by gt814** [kubernetes/website#38201]
**This is a Bug Report**

**Problem:**
Documentation says: "minikube runs a single-node Kubernetes cluster",
but minikube already can run multi-node local Kubernetes cluster.

Here is how to use multi-node clusters https://minikube.sigs.k8s.io/docs/tutorials/multi_node/.

**Proposed Solution:**
Replace the description with the following: "minikube runs an all-in-one or a multi-node local Kubernetes cluster".

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/

Additional Information:
/sig docs
/language en
/assign

**Comment by Saumya132** [comment]
@gt814 Can I work on this issue?

**Comment by gt814** [comment]
> @gt814 Can I work on this issue?

@Saumya132  I already did it and I'm going to open PR.

**Comment by Shubham82** [comment]
closing this PR as this issue is resolved in the following PR: #38219 
/close
