### ISSUE TITLE
kube-proxy `kernelspace` mode is not documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38244]
**This is a Bug Report**

**Problem:**
kube-proxy supports a `kernelspace` operating mode, but this is not documented.

**Proposed Solution:**
Properly document the `kernelspace` operating mode for kube-proxy

**Page to Update:**
https://kubernetes.io/docs/reference/networking/virtual-ips/

**Additional Information:**
See #38243

/sig network
/sig windows

**Comment by marosset** [comment]
https://github.com/kubernetes/website/pull/38243 has merged, is there more work to be done for this issue?
cc @MikeZappa87 @jayunit100 @daschott

**Comment by sftim** [comment]
Would be good to have someone check / update the docs. Last time I worked on Windows Server, I was looking after Exchange 2010.

**Comment by sftim** [comment]
/close

It's documented now!
