### ISSUE TITLE
Issue with /docs/tasks/manage-gpus/scheduling-gpus/

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#3825]
**Problem:** GPU user guide has the `scheduler.alpha.kubernetes.io/affinity` annotation used in is no longer valid as `nodeAffinity` has moved to beta and has its own field now.

**Proposed Solution:** Replace scheduler.alpha.kubernetes.io/affinity annotation with nodeAffinity field in the snippet.

**Page to Update:** https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/

**Comment by tengqm** [comment]
Closing this because it is no longer an issue. Node selection via labels works well now.
