### ISSUE TITLE
 Add to Documentation - Network Policies - Example: Allow Egress DNS

### ISSUE THREAD

**Issue by zenhighzer** [kubernetes/website#38267]
Hi there,

I was playing around with Network Policies based on https://kubernetes.io/docs/concepts/services-networking/network-policies/ and finally I banged my head on my keyboard: 
- I created a Default Deny for Egress like in the example
- I forgot to add Egress Exception Rule for pods beeing able to talk to DNS. 

Because I am an K8s-beginner I thought, that dns-resolution was done by kubernetes by "magic". 

To protect others from banging their heads onto their keyboards I would like to suggest to add a little hint and maybe an example about egress/dns to the documentation on https://kubernetes.io/docs/concepts/services-networking/network-policies/ . It would be nice to know that if egress default deny is in place, that also dns-resolution is not working anymore :-D 

What do you think? 

Best Regards
Zen

**Comment by sftim** [comment]
We could add a new Task page, and hyperlink to that task page from https://kubernetes.io/docs/concepts/services-networking/network-policies.

/priority backlog
Other improvements are more urgent.
