### ISSUE TITLE
Init containers concept page is confusing - https://k8s.io/docs/concepts/workloads/pods/init-containers/

### ISSUE THREAD

**Issue by aaron1989041** [kubernetes/website#38271]
K8S v1.23 doc about init containers have these two lines:
1、“Changes to the init container spec are limited to the container image field. Altering an init container image field is equivalent to restarting the Pod.”
2、“The Pod will not be restarted when the init container image is changed, or the init container completion record has been lost due to garbage collection.”

so which one is true? altering an init container image will restart the pod or not?

**Comment by sftim** [comment]
/retitle **Init containers** concept page is confusing - https://k8s.io/docs/concepts/workloads/pods/init-containers/

**Comment by sftim** [comment]
There's a difference between changing the string that represents the URI of an image, and changing the image that the URI represents. I think the page is talking about 2 different things, but not very clearly.

(aside: Docker uses the term URI or URL for images, but the rest of the world of IT uses the term URI to mean web [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)s)

**Comment by utkarsh-singh1** [comment]
We can mention the Pod image field as - .spec.containers.image and can mention init container image as (changing image from the repository.)

**Comment by jnelson-wasabi** [comment]
If someone can give me the correct idea behind each of those two statements, I would be glad to make the change to the docs and create a pull req.

**Comment by vishnuswmech** [comment]
Raised the PR for this.
https://github.com/kubernetes/website/pull/47946
