### ISSUE TITLE
Pod Lifecycle - Completed

### ISSUE THREAD

**Issue by tushartgupta** [kubernetes/website#38294]
Should we also add the lifecycle state of "Completed"? I created a pod that prints a random number and then completes. RestartPolicy is set to Never, and now the POD state is "Completed"

**Comment by utkarsh-singh1** [comment]
Hi @tushartgupta, can you elaborate your issue in detail.

Do you want some change in Kubernetes docs, if yes, then can you provide link to the doc?

**Comment by sftim** [comment]
/remove-kind support

Maybe there is room to improve a page in the documentation.
