### ISSUE TITLE
[zh-cn] sync /networking/virtual-ips.md

### ISSUE THREAD

**Issue by ktKongTong** [kubernetes/website#38295]
**This is a Feature Request**
[zh-cn] Translate [content/en/docs/reference/networking/virtual-ips.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/networking/virtual-ips.md) into Chinese

**What would you like to be added**

add and translate Chinese document:
content/zh/docs/reference/networking/virtual-ips.md
**Why is this needed**
localization
**Comments**

/language zh
/assign

**Comment by sftim** [comment]
Note that some of this text is already localized into https://github.com/kubernetes/website/blob/main/content/zh-cn/docs/concepts/services-networking/service.md (it moved in https://github.com/kubernetes/website/pull/36675)
