### ISSUE TITLE
Broken Link in container-storage-interface-ga blog

### ISSUE THREAD

**Issue by dharmicksai** [kubernetes/website#38304]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/#:~:text=For%20more%20details%20please%20see%20the%20CSI%20implementation%20design%20doc%20and%20documentation.
In the above blog the link to design doc is broken. On clicking the link i am getting a page not found error

**Proposed Solution:**
Replace the link for design doc with the link https://github.com/kubernetes/design-proposals-archive/blob/main/storage/container-storage-interface.md

**Page to Update:**
https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/

**Comment by sftim** [comment]
Thanks for the report.

That article is more than one year old. Older articles may contain outdated content, and we don't prioritize maintaining them.

We'll consider a fix but we also won't prioritise reviews for any PR, because of the same policy.

/priority awaiting-more-evidence
/area blog

**Comment by kundan2707** [comment]
@satyamkale27 Are you working on it ?

**Comment by aj11anuj** [comment]
As per comment https://github.com/kubernetes/website/pull/41984#issuecomment-1633551658

/close not-planned
