### ISSUE TITLE
This is a solution for misintepretation of integer-like strings when deploying a ConfigMap

### ISSUE THREAD

**Issue by Abhishek-akg** [kubernetes/website#38301]
Proposed solution: Use single quoted commas around the integer-like strings.

**Comment by utkarsh-singh1** [comment]
Hi @Abhishek-akg, please also provide link to the doc where you want the improvement.

/priority awaiting-more-evidence

**Comment by utkarsh-singh1** [comment]
Hi @Abhishek-akg, Is your issue has been resolved?
