### ISSUE TITLE
Link to AdminNetworkPolicy API docs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38306]
**This is a Feature Request**

**What would you like to be added**
Add a link to https://network-policy-api.sigs.k8s.io/

**Why is this needed**
As well as in-tree NetworkPolicy, there is AdminNetworkPolicy. Readers might like to know about this.

**Comments**
/sig network
/kind feature
/language en

**Comment by gauravrattan** [comment]
@sftim can you tell brief about what we change/add above docs

**Comment by satyampsoni** [comment]
can you Please let me know where API docs is present?

PS: Link of the documentation is highly appreciable.

**Comment by sftim** [comment]
We don't need to change pages within https://network-policy-api.sigs.k8s.io/

We should change pages within https://k8s.io/docs/ so that appropriate pages hyperlink to https://network-policy-api.sigs.k8s.io/

If you're not sure what pages should link to AdminNetworkPolicy, it's OK to leave this issue so that someone else can work on it.

**Comment by mehabhalodiya** [comment]
@rishitashaw any updates here?
