### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by vifeng** [kubernetes/website#38319]
Hi,
the maven package command lines aren't working. here are the traces.
also, please provide with the source code. the Interactive Tutorial is not practical to see a microservice. And we could run it locally.
It would be nice to have a tutorial on the manifest before this one. 
Thanks,
remaining at your disposal,
V

1st app
-------------------------
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project system: Could not build image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
$ 

2nd app
-------------------------
[ERROR] Unknown lifecycle phase "mvn". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException
$

**Comment by sftim** [comment]
There's no solution really; I updated https://github.com/kubernetes/website/issues/37994 to reflect my new understanding of the bug.

/kind bug
/language en

**Comment by mehabhalodiya** [comment]
Per [this comment](https://github.com/kubernetes/website/issues/38319#issuecomment-1345677827), I am closing this issue. Thanks!

/close
