### ISSUE TITLE
Freeze k/website for Kubernetes 1.26 release

### ISSUE THREAD

**Issue by krol3** [kubernetes/website#38317]
This issue is for freezing the k/website for the Kubernetes 1.26 release.

The release is scheduled to happen tomorrow (Thursday 8th December 2022) and No PRs are allowed to merge until the release PR has successfully merged.

If there are any questions, please contact me or anyone from the docs release team

cc: @reylejano @onlydole @divya-mohan0209  @jimangel  @natalisucks 
cc: @cathchu @mickeyboxell @katmutua @Rishit-dagli

/sig release
/label tide/merge-blocker

**Comment by onlydole** [comment]
Site is live!

https://deploy-preview-38363--kubernetes-io-vnext-staging.netlify.app/
