### ISSUE TITLE
Interactive Tutorial - Exploring Your App

### ISSUE THREAD

**Issue by AL292** [kubernetes/website#38323]
In the step 2, last command is written `curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/` and that outputs an error
`{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 172.17.0.7:80: connect: connection refused",
  "reason": "ServiceUnavailable",
  "code": 503
}`
For the new learners it can be a little confuse. When we remove the `proxy/` from the end of the line it does what is realy meant to do

**Comment by utkarsh-singh1** [comment]
I have also not faced any errors till the completion of this tutorial. Please confirm you have a proxy running in the second tab of the terminal.

**Comment by utkarsh-singh1** [comment]
The same issue is also mentioned here - #37722.

/triage duplicate

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
