### ISSUE TITLE
/docs/tasks/access-application-cluster/create-external-load-balancer/ doesn't mention ingress

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#3832]
**Problem:** https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/ this page should mention `Ingress` concept as a way to create an external LB to an application.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

**Comment by zacharysarah** [comment]
There are some offhanded mentions of Ingress in samples, but they're likely to be more confusing than not. Agreed: more/better docs needed.
