### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

### ISSUE THREAD

**Issue by FaQQQ** [kubernetes/website#38333]
The documentation on this page fails to describe the relationship between kubelet and Windows.

**Comment by utkarsh-singh1** [comment]
Related Doc - https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

/kind support
/language zh

**Comment by mengjiao-liu** [comment]
The content on the Chinese page is synchronized with that on the English upstream page. 

/language en

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

**Comment by mengjiao-liu** [comment]
missing kubeadm on windows docs ticket
https://github.com/kubernetes/website/issues/34476

**Comment by tengqm** [comment]
/close
as a dup of #34476
