### ISSUE TITLE
Clarify how to use pod affinity to colocate pods of the same workload

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#38339]
**What would you like to be added**

Describe the behavior of pod-affinity when the pod that defines it matches the affinity rule and it's the first pod of the series

https://github.com/kubernetes/kubernetes/blob/7cba7e6c58078865bedaa3ba7ea30f0c3193ff4d/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L351-L361

https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity

**Why is this needed**

This is a common pattern to collocate jobs with pods that need to communicate with each other.

**Comments**

**Comment by sftim** [comment]
/language en

What needs clarifying @alculquicondor ?

**Comment by sftim** [comment]
We could pretty much copy in this text as-is:
> This pod may be the first pod in a series that have affinity to themselves. In order to not leave such pods in pending state forever, we check that if no other pod in the cluster matches the namespace and selector of this pod, the pod matches its own terms, and the node has all the requested topologies, then we allow the pod to pass the affinity check.

However, a tweak is good: [avoid using “we”](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-using-we) in the docs.

**Comment by alculquicondor** [comment]
yes, basically we have to transcribe that comment and make it fit well in the existing documentation.

The existing documentation talks about a group of pods having affinity to pods of another service. We need to clarify that is also possible to do affinity within the group.

**Comment by alculquicondor** [comment]
/close
#42920
