### ISSUE TITLE
Horizontal Pod Autoscaling - docs have syntax error

### ISSUE THREAD

**Issue by kiefersmith** [kubernetes/website#38341]
![Screen Shot 2022-12-08 at 10 36 25 AM](https://user-images.githubusercontent.com/15173946/206489020-c968c7f2-9dda-45f1-8aa1-1ffe988eaa97.png)

Seen on: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

Looks like this commit introduced the issue: https://github.com/kubernetes/website/commit/b319f844db4f471d6ea9c7427a8db015937170e3

**Comment by kundan2707** [comment]
@kiefersmith  nthing seems wrong in this page. everything correct

**Comment by utkarsh-singh1** [comment]
Hi @kiefersmith, This problem is duplicate of issue #37357, it seems to have issue with the 3rd party tool `mermaid `. 

/triage duplicate
/language en

**Comment by utkarsh-singh1** [comment]
Hi @kiefersmith, this issue is similar to #37357, which is work in progress, so please close this issue.
