### ISSUE TITLE
Error in the docs, in section Configure Service Accounts for Pods

### ISSUE THREAD

**Issue by SergiyKolesnikov** [kubernetes/website#38357]
In the subsection [Manually create an API token for a ServiceAccount](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount), the command `kubectl create token admin-user` references a wrong service account. It should be `kubectl create token build-robot`.

**Comment by jihoon-seo** [comment]
This issue has been resolved by the PR #38321.
/close
