### ISSUE TITLE
k8s.gcr.io still referenced as kubeadm default in v1.24 and older

### ISSUE THREAD

**Issue by rjsadow** [kubernetes/website#38359]
**This is a Bug Report**

**Problem:**
The `imageRepository` field for kubeadm config (v1beta2 and v1beta3) still reference `k8s.gcr.io` as the default registry used. Though that's true for initial versions of 1.22-1.24, it changed in the most recent patch versions to be `registry.k8s.io`. 

**Proposed Solution:**
I guess the question comes down to whether the documentation is supposed to be accurate to the latest patch release or the initial release and users are expected to find patch specific updates in the CHANGELOG. If it's the former then I believe the documentation should be updated to reflect `registry.k8s.io`. 

**Page to Update:**
https://v1-24.docs.kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/#kubeadm-k8s-io-v1beta2-ClusterConfiguration
https://v1-24.docs.kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-ClusterConfiguration
https://v1-23.docs.kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/#kubeadm-k8s-io-v1beta2-ClusterConfiguration
https://v1-23.docs.kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-ClusterConfiguration
https://v1-22.docs.kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta2/#kubeadm-k8s-io-v1beta2-ClusterConfiguration
https://v1-22.docs.kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-ClusterConfiguration

**Kubernetes Version:**
1.22, 1.23, 1.24

**Additional Information:**
Kubeadm issues to update default imageRepository
https://github.com/kubernetes/kubernetes/pull/113395
https://github.com/kubernetes/kubernetes/pull/113393
https://github.com/kubernetes/kubernetes/pull/113388

**Comment by tengqm** [comment]
Those reference were generated using the then current code base. However, this change of registry applies to all people running those old releases as well. So I'd suggest we manually update the reference instead of regenerating them.

**Comment by neolit123** [comment]
thanks for the api docs updates @tengqm 

@rsadowsk looks like we only need to update the registry  mention here for the k/website branches in support
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

you can help us by sending prs if you'd like?

also, only for /en as the other languages are maintained / forked by dedicated teams.

**Comment by rsadowsk** [comment]
@neolit123 Sounds good! I'll get in a pr early this week.

**Comment by sftim** [comment]
From https://github.com/kubernetes/website/pull/38423 / https://github.com/kubernetes/website/pull/38424 / https://github.com/kubernetes/website/pull/38425:

> I suppose we could try to make that clear to the reader, though I'm not sure how to structure that since the docs are only for minor versions and not specific patches. Typically is the documentation supposed to be accurate to the latest patch version or the initial release and users are expected to find patch specific updates in the CHANGELOG? If we add specific references we'll need @tengqm to update some merges he did on Satuday for #38359

https://github.com/kubernetes/website/pull/38423#discussion_r1045973244 is a sketch about how I'd do this. Please use the actual correct release information for each minor release.

I don't think you'd need to liaise with @tengqm here before we merge this. For the reference information, we don't customize the text away from what the Kubernetes code (and its comments) lets us produce.

**Comment by tengqm** [comment]
This case is a little bit special. Clarifying which version of kubeadm changes its behavior would be ideal. Otherwise, we have to manually fix this. This behavior change is not something reflected accurately in the upstream source code (comments).

**Comment by sftim** [comment]
Done

/close

Thanks @rjsadow
