### ISSUE TITLE
MinDomainsInPodTopologySpread is reported as `false` by default in `Kubernetes 1.25.0` in Feature Gate page

### ISSUE THREAD

**Issue by ValetteValette** [kubernetes/website#38358]
**This is a Bug Report**

**Problem:**
The Feature Gate page ( https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ ) reports `MinDomainsInPodTopologySpread` to be `false` by default in `1.25.0` for `beta` status whereas the Pod Topology Constraint page ( https://kubernetes.360ai.org/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition ) says it's `true` by default in `1.25.0`.
I understand that all `beta` are `true` by default.

**Proposed Solution:**
Update the status in Feature Gate page from `false` to `true` for `MinDomainsInPodTopologySpread` in `1.25.0`.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by mengjiao-liu** [comment]
/triage accepted
The kubernetes source code sets this MinDomainsInPodTopologySpread  feature gate beta default to false, which we need to modify first in the kubernetes repository.

According to the [KEP description](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3022-min-domains-in-pod-topology-spread#beta-v125), It should have been set to true by default in 1.25(but don't know why there is no).

I have summited a PR https://github.com/kubernetes/kubernetes/pull/114445 for this issue.

**Comment by mengjiao-liu** [comment]
PR https://github.com/kubernetes/kubernetes/pull/114445 has been merged.

The documentation needs to be modified after the k8s 1.27 release:
Update the status on the feature gate page from false to true for MinDomainsInPodTopologySpread in 1.27.

**Comment by mengjiao-liu** [comment]
How should we update this document in 1.27? Under the MinDomainsInPodTopologySpread new add one line?
```
| `MinDomainsInPodTopologySpread` | `true` | Beta | 1.27 | |
```
The final result is shown below:
![image](https://user-images.githubusercontent.com/44460091/208338935-9603c223-566a-49b0-9d6e-189dd2541664.png)

Generally, a feature gate may have three lines: alpha, beta, GA. 
Would it be misleading to add an extra line to make this feature gate because of the default value change?
Or is there any other better suggestion here? 
/cc @sftim

**Comment by tengqm** [comment]
There are other cases where the default value for a gate is 'false' although it is in Beta or vice versa. Just document the true fact should be fine. The number of lines doesn't matter at all. In your screenshot, you forgot to mention that the feature remained to be 'false' till '1.26', i.e. the second row.

**Comment by mengjiao-liu** [comment]
> There are other cases where the default value for a gate is 'false' although it is in Beta or vice versa. Just document the true fact should be fine. The number of lines doesn't matter at all

ok, I got it.

> In your screenshot, you forgot to mention that the feature remained to be 'false' till '1.26', i.e. the second row.

```
- The "Until" column, if not empty, contains the last Kubernetes release in which
  you can still use a feature gate.
```

yes, I may have misunderstood the meaning of "Until". I initially thought that changing the default value would not change the value of the "Until" column.

After modifying the data:
![image](https://user-images.githubusercontent.com/44460091/208387523-763fefda-5546-4dd4-ba3b-f478c864cb79.png)

PR #38549 to update it in the dev-1.27 branch.

**Comment by sanposhiho** [comment]
Hi, I'm the author/developer of the minDomain KEP, sorry for this trouble.

Could you please fix ↓ this note as well?
> Note: The minDomains field is a beta field and enabled by default in 1.25. You can disable it by disabling the MinDomainsInPodTopologySpread [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/).
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Comment by mengjiao-liu** [comment]
Oh, I didn't notice that line and I will fix the note.

Change it to:
```
Note: The minDomains field is a beta field and disabled by default in 1.25. You can enable it by enabling the MinDomainsInPodTopologySpread [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/).
```
Can this be modified like this? @sanposhiho

**Comment by mengjiao-liu** [comment]
@tengqm  I need to commit the update in the `release-1.25` and `main` branches, right?

**Comment by tengqm** [comment]
> @tengqm I need to commit the update in the `release-1.25` and `main` branches, right?
> 
> I'm not sure if this needs to be changed in `release-1.25`.

If there are defects in v1.25 docs, we should fix it by committing to release-1.25 branch.

**Comment by mengjiao-liu** [comment]
ok, I got it.

**Comment by mehabhalodiya** [comment]
Closing this issue as I see it's resolved now!
Feel free to reopen if anything slipped away from my sight 🙂 Thanks!

/close
