### ISSUE TITLE
DownwardAPI documentation is incorrect about which fields are available as files

### ISSUE THREAD

**Issue by jrhunger** [kubernetes/website#38361]
**This is a Bug Report**

**Problem:**
Documentation should state that spec and status downward API fields are only available as environment variables, not as files.

**Proposed Solution:**
Add text before spec.serviceAccountName stating:

> The following information is available through environment variables **but not as a downwardAPI volume fieldRef**

Then for consistency, a few lines down change:

> In addition, the following information is available through a downwardAPI volume fieldRef, **but not as environment variables**:

to

> The following information is available through a downwardAPI volume fieldRef, **but not as environment variables**:

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/downward-api/

Kubernetes Version: 
Confirmed on v1.24 and v1.25

Additional Information:
Error message from kubectl (1.25) apply shows which values are allowed for each type (line breaks added for readability)
```
* spec.template.spec.volumes[0].downwardAPI.fieldRef.fieldPath: Unsupported value: "spec.nodeName": 
supported values: "metadata.annotations", "metadata.labels", "metadata.name", "metadata.namespace", "metadata.uid"

* spec.template.spec.containers[0].env[1].valueFrom.fieldRef.fieldPath: Unsupported value: "metadata.labels": 
supported values: "metadata.name", "metadata.namespace", "metadata.uid", "spec.nodeName", "spec.serviceAccountName", "status.hostIP", "status.podIP", "status.podIPs"
```

**Comment by sftim** [comment]
Thanks for the report

/sig node

**Comment by SergeyKanzhelev** [comment]
/triage accepted

sounds reasonable, thank you

**Comment by Kartik494** [comment]
I would like to give a try on this.
/assign
