### ISSUE TITLE
How can I measure the network consumption in the image pulling process

### ISSUE THREAD

**Issue by Olg-star** [kubernetes/website#38377]
To do an experiment, because the image is pulled by layer, I want to know whether the new image will use the layer of the old image that has been pulled to the local version, and then pull the changed layer of the new image to replace it, so that the network will consume less traffic when the image is updated to the latest version.So I want to know whether the shared image layer will also be pulled? And How can I measure the network consumption in the image pulling process

**Comment by adityassharma-ss** [comment]
There are a variety of tools available for monitoring network traffic, you can use any of them. For example, netstat, tcpdump etc.

**Comment by sftim** [comment]
I feel like https://github.com/kubernetes/enhancements/issues/3542 is relevant, but not yet relevant for docs: we only document features that are either implemented, or where an early implementation is already released.
