### ISSUE TITLE
kubeadm init fail with kubernet service failed to start because CRI not implemented

### ISSUE THREAD

**Issue by dantanqikun** [kubernetes/website#38385]
(ubuntu1604, kubernets 1.26, containerd 1.26)"command failed" err="failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"

**Comment by utkarsh-singh1** [comment]
Hi @dantanqikun, can you tell me the version of containerd installed.

/priority awaiting-more-evidence

**Comment by neolit123** [comment]
your version of containerd is too old.
go to the "container runtime" page of k8s.io and install the latest containerd.

for more support questions please use discuss.k8s.io or slack.

/kind support
/close

**Comment by dantanqikun** [comment]
Find the new version solved the problem, thx guys.
