### ISSUE TITLE
Improvement for k8s.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by hrider** [kubernetes/website#38409]
Provide copy button/icon on the code snippets to enable quick copy and paste to help developers/learners/exam prep.

**Comment by jihoon-seo** [comment]
We might replace the snippet code with `codenew`, which is used in [here](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource).

But I guess that to use the `codenew` shortcode, the code should be exist as a separate manifest file.

---

I thought that it would be great if the `codenew` shortcode support 'in-file code snippet embedding feature',
for the case that we don't need to separate the code as a manifest file but want to provide a code-copying convenience to the doc readers.

[Pseudo-code of the `codenew` shortcode's 'in-file code snippet embedding feature']

```markdown
{{< codenew syntax="yaml" code=`
apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: default
spec:
  restartPolicy: Never
  volumes:
  - name: vol
    hostPath:
      path: /any/path/it/will/be/replaced
  containers:
  - name: pv-recycler
    image: "registry.k8s.io/busybox"
    command: ["/bin/sh", "-c", "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"]
    volumeMounts:
    - name: vol
      mountPath: /scrub
` >}}
```

**Comment by sftim** [comment]
I agree, we should switch to the `codenew` shortcode, which provides such a copy button. This saves readers having to select the manifest first before copying.

We also want each example downloadable, so we couldn't easily provide that with inline snippets.

**Comment by sftim** [comment]
/triage accepted
/kind cleanup
/priority backlog

The way to work on this is to use a `codenew` snippet and make a new manifest file.

**Comment by Kartik494** [comment]
> The way to work on this is to use a `codenew` snippet and make a new manifest file.

Hi @sftim  could you let me know should i place new yaml manifest under `examples/admin`?
