### ISSUE TITLE
Patch versions need updates for older docs

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#38414]
**This is a Bug Report**

As of today (2022-12-12), the latest patch versions of each minor versions are as follow:
- v1.25.5
- v1.24.9
- v1.23.15
- v1.22.17

**Problem:**

The latest patch versions info in the pages below are outdated and thus need updates.

**Proposed Solution:**

**Page to Update:**
- v1.25 docs
  - https://v1-25.docs.kubernetes.io/releases/download/
  - https://v1-25.docs.kubernetes.io/releases/
  - `config.toml`
- v1.24 docs
  - https://v1-24.docs.kubernetes.io/releases/download/
  - https://v1-24.docs.kubernetes.io/releases/
  - `config.toml`
- v1.23 docs
  - https://v1-23.docs.kubernetes.io/releases/
  - `config.toml`
- v1.22 docs
  - https://v1-22.docs.kubernetes.io/releases/
  - `config.toml`

**Comment by aj11anuj** [comment]
Issue is not relevant to fix as of today as currently K8s/website is maintaing docs (1.25 - 1.29)
/close not-planned
