### ISSUE TITLE
'Doc for old version' banner is missing for v1.25 docs

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#38412]
**This is a Bug Report**

~Note: there might be possibility that this issue will be automatically resolved when the issue #38411 gets resolved.~

**Problem:**
'Doc for old version' banner is missing for v1.25 docs.

![image](https://user-images.githubusercontent.com/46767780/206944746-4318bd5e-96c1-41f4-bd0a-155c48358223.png)

![image](https://user-images.githubusercontent.com/46767780/206944682-99abe3a1-32a4-4777-b49c-df7e9b64de7c.png)

**Proposed Solution:**

**Page to Update:**
https://v1-25.docs.kubernetes.io/docs/*

**Comment by sftim** [comment]
Check the setting of `deprecated` in https://github.com/kubernetes/website/blob/release-1.25/config.toml - it should be `true` to mark that these are not the current docs.

/help

**Comment by reylejano** [comment]
/assign
Proposed fix in https://github.com/kubernetes/website/pull/39238

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/39238

/close
