### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by mostafashahcheraghian** [kubernetes/website#38421]
On the page "nteractive Tutorial - Deploying an App"

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

This message appears to me :

Sorry, we encountered a problem with the connection. Support has been alerted.
This is potentially due to a HTTP Proxy blocking Websockets.
Websocket Error - Connection Failed.
Reload the page to try again

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
