### ISSUE TITLE
Kubernetes Metrics Reference: word wrapping problems

### ISSUE THREAD

**Issue by tallclair** [kubernetes/website#38438]
The [Kubernetes Metrics Reference](https://kubernetes.io/docs/reference/instrumentation/metrics/) table is hard to read due to word wrapping problems, even in a fairly wide (2036px) window:

![image](https://user-images.githubusercontent.com/29742491/207180480-37cc26be-3e03-43e1-a601-197d9b15048c.png)

Given the long names, I think it's going to be too difficult to fit this into a multi-column table layout. I'd suggest adopting a list (or single-column table) format instead. Something like:

---

**apiserver_admission_controller_admission_duration_seconds**
Admission controller latency histogram in seconds, identified by name and broken out for each operation and API resource and type (validate or admit).

- **Stability:** STABLE
- **Type:** Histogram
- **Labels:** name, operation, rejected, type

---

**apiserver_longrunning_requests**
Gauge of all active long-running apiserver requests broken out by verb, group, version, resource, scope and component. Not all requests are tracked this way.

- **Stability:** STABLE
- **Type:** Gauge
- **Labels:** component, group, resource, scope, subresource, verb, version

---

/sig instrumentation

**Comment by sftim** [comment]
This isn't really something we'd expect the _instrumentation_ SIG to know how to fix. Help from any quarters with generating better Markdown (or HTML) is welcome.

/area web-development

Something that can work is a table with `rowspan`: have the metric description / Help text on a second row, for example, but have the metric name and stability level be set to span two rows, with other details above that.

I am also OK with the idea of a list format. It _is_ nice to leave scope a search or filter mechanism; https://www.k8s.dev/resources/keps/ is the one that springs to mind.

For example, a reader might want to only view stable metrics, or only view API server metrics. Any change we make shouldn't block our way to adding that filtering later on.

---

The source code we already have, such as:
```html
<td class="metric_labels_varying">
<div class="metric_label">type</div>
<div class="metric_label">name</div>
<div class="metric_label">operation</div>
<div class="metric_label">rejected</div>
</td>
```
gives us options to improve things in CSS, too.

For example, we could set the width of the metric description `<td>` (column heading Help) using CSS and `calc()`; we can style the labels in monospace, and we can tell the browser to avoid wrapping that text if feasible.

---

This site generator can work with page fragments: some code generates just the table itself, and SIG Docs provides the rest of the page text plus the mechanism to include the list or table fragment that was generated.

**Comment by sftim** [comment]
This particular page is autogenerated but the automatic generation is not yet fully documented; see https://github.com/kubernetes/website/pull/37522#issuecomment-1293786765 for some more context.

**Comment by dashpole** [comment]
cc @logicalhan

I agree our sig probably isn't equipped to fix this, but thanks for raising it

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/42342

**Comment by sftim** [comment]
:+1: for either:
- true single-column table format 
- multicolumn, where one column has a row for each detail of the metric, and the single other column uses `rowspan` to mark the metric overall.

Extra credit for giving each metric a fragment identifier.

**Comment by sftim** [comment]
Think about how filtering might work. If someone wants to filter to see only the stable metrics, does the implementation we pick allow implementing that?

**Comment by Gauravpadam** [comment]
In light of recent conversation at #42342, I'll be assigning this issue to myself
/assign

**Comment by Gauravpadam** [comment]
> Think about how filtering might work. If someone wants to filter to see only the stable metrics, does the implementation we pick allow implementing that?
> 
> Same idea for filtering by the component that emits the metric.

The idea of filtering is good, We can also go for a search bar
filtering should be more useful imo, I'll keep that angle open

**Comment by Gauravpadam** [comment]
I think we can close this issue with the merge of https://github.com/kubernetes/website/pull/42823, I'll be happy to assist with a follow up PR adding the filtering functionality @sftim
