### ISSUE TITLE
Stale information about Windows privileged containers

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38433]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/workloads/pods/#privileged-mode-for-containers mentions the `WindowsHostProcessContainers` feature gate. This is relevant for older versions of Kubernetes; v1.26 onwards don't support disabling that feature as it's now GA.

**Proposed Solution:**
Tweak the wording; use a [`feature-state`](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#feature-state) shortcode if that also helps.

Try to make the docs still relevant for someone who is running an older Kubernetes release.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/

**Additional Information:**
/language en
/help

**Comment by dshebib** [comment]
https://github.com/kubernetes/website/pull/38673

Above changes based on https://kubernetes.io/docs/concepts/storage/volumes/#azurefile. That document is also quite cluttered and could possibly use some cleanup as well.

**Comment by sftim** [comment]
Fixed
/close
