### ISSUE TITLE
Split “can approve English content changes” from “can review general website changes” permissions

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38431]
**This is a Feature Request**

**What would you like to be added**
At the time of writing, someone who is an approver for English gets approve access to the website overall, bar a few places where the top level permission is not inherited.

We should narrow this. 

**Why is this needed**
Being good at English doesn't mean you are also good at managing `OWNERS_ALIASES` files, for example.

**Comments**
 This change lets us lower the barrier for people approving for English.

**Comment by a-mccarthy** [comment]
@sftim To clarify, are you suggesting that we should narrow English approver access to only the /en directory? In the same way the localization teams are granted access to only the language directory for the team they are a part of? 

I think thats and interesting idea, and probably makes sense to have more fine grained ways to grant access to parts of the repo.

**Comment by sftim** [comment]
> are you suggesting that we should narrow English approver access to only the /en directory? In the same way the localization teams are granted access to only the language directory for the team they are a part of?

Exactly this. We then need to have other approvers for things that aren't English (eg: CSS; images; the container image build process), which we'd assign appropriately.

**Comment by divya-mohan0209** [comment]
Based on your previous comment, @sftim , would it be worthwhile having the approver/reviewer list for these different areas curated like we have for blogs and for the localizations?
You mentioned a few above and I was wondering if we could achieve the same granularity that you're proposing for the general website when it comes to css, images etc.

**Comment by sftim** [comment]
See PR #42206

**Comment by sftim** [comment]
Done in #42206 

/close
