### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

### ISSUE THREAD

**Issue by neerajg5** [kubernetes/website#38441]
![image](https://user-images.githubusercontent.com/52025277/207225938-c8f98d53-25d3-46a2-9d4c-13957b028d0c.png)

**Comment by jihoon-seo** [comment]
/triage duplicate

This is a duplicate of issue #37994.

/kind bug
/language en

**Comment by T-Lakshmi** [comment]
/team katakoda
It seems many new people are facing this issue and opening new ticket frequently for the already existing/duplicate ticket,
i think its better to document the solution as a part of troubleshooting or FAQ somewhere in the documents.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
