### ISSUE TITLE
Broken links to v1.25 docs

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38457]
**This is a Bug Report**

**Problem:**
https://v1-22.docs.kubernetes.io/docs/home/supported-doc-versions/
https://v1-23.docs.kubernetes.io/docs/home/supported-doc-versions/
https://v1-24.docs.kubernetes.io/docs/home/supported-doc-versions/

each have a link to the docs for Kubernetes v1.25; however, **some** of those links are broken
See https://github.com/kubernetes/website/issues/38457#issuecomment-1350154942

This error was introduced as part of the [v1.26 release](https://kubernetes.io/blog/2022/12/09/kubernetes-v1-26-release/).

**Pages to Update:**
~https://v1-22.docs.kubernetes.io/docs/home/supported-doc-versions/~
https://v1-23.docs.kubernetes.io/docs/home/supported-doc-versions/
https://v1-24.docs.kubernetes.io/docs/home/supported-doc-versions/

(however, the problem is in `config.toml` for the branches _release-1.23_ and _release-1.24_. I think that the Markdown in the supported doc versions page itself is fine.)

**Additional Information:**
/language en
/kind bug
/priority backlog
/triage accepted

**Comment by jihoon-seo** [comment]
- [The link in 1.22 doc](https://v1-22.docs.kubernetes.io/docs/home/supported-doc-versions/#:~:text=Older%20versions-,v1.25,-v1.24): working
  - It goes to https://v1-25.docs.kubernetes.io/docs/home/supported-doc-versions/
- [The link in 1.22 doc](https://v1-23.docs.kubernetes.io/docs/home/supported-doc-versions/#:~:text=Older%20versions-,v1.25,-v1.24): **not working**
  - it goes to https://v1-25.kubernetes.io/docs/home/supported-doc-versions/
- [The link in 1.24 doc](https://v1-24.docs.kubernetes.io/docs/home/supported-doc-versions/#:~:text=Older%20versions-,v1.25,-v1.24): **not working**
  - it goes to https://v1-25.kubernetes.io/docs/home/supported-doc-versions/

For anyone that wants to work on this:
please notice the slight difference among those links.

**Comment by sftim** [comment]
Looks fixed

/close
