### ISSUE TITLE
I18n TOML File Key Standardization

### ISSUE THREAD

**Issue by QuinceyJames** [kubernetes/website#38459]
**This is a Bug Report**

**Problem:**
Currently, there are keys in the i18n TOML files that are slight variants of each other (e.g. `layout_*` vs. `layouts_*`). As a result, when the files are sorted alphabetically, it makes it hard to find the key you need. 

**Proposed Solution:**
- Run a find a replace to change all instances of `layouts` to `layout` in **all** languages

**Page to Update:**
- layouts/_default/search.html  (1 usage found)
    - line 44 `<div id="bing-results-container">{{ T "layouts_docs_search_fetching" }}</div>`
- layouts/case-studies/list.html  (1 usage found)
    - line 63 `images/case-studies/story.svg" alt="{{ T "layouts_case_studies_list_tell" }}"></a>`
- layouts/docs/glossary.html  (6 usages found)
    - line 9 `<p>{{ T "layouts_docs_glossary_description" }}</p>`
    - line 11 `<p>{{ T "layouts_docs_glossary_filter" }}</p>`
    - line 25 `<span class="tag-option"><a id="select-all-tags" href="javascript:void(0)">{{ T "layouts_docs_glossary_select_all" }}</a></span>`
    - line 26 `<span class="tag-option"><a id="deselect-all-tags" href="javascript:void(0)">{{ T "layouts_docs_glossary_deselect_all" }}</a></span>`
    - line 28 `<p>{{ T "layouts_docs_glossary_click_details_before" }} <a href="javascript:void(0)" class="no-underline">[+]</a> {{ T "layouts_docs_glossary_click_details_after" }}</p>`
    - line 46 `{{ T "layouts_docs_glossary_aka" }}:<i>{{ delimit . ", " }}</i>`
- layouts/partials/feedback.html  (5 usages found)
    - line 8 `{{ T "layouts_docs_partials_feedback_thanks" }}`
    - line 12 `{{ T "layouts_docs_partials_feedback_issue" }}`
    - line 15 `{{ T "layouts_docs_partials_feedback_problem" }}</a>`
    - line 16 `{{ T "layouts_docs_partials_feedback_or" }}`
    - line 19 `{{ T "layouts_docs_partials_feedback_improvement" }}</a>.`

**Additional Information:**
/kind cleanup

Relates to: #38287, #38257

**Comment by QuinceyJames** [comment]
cc: @sftim @divya-mohan0209

**Comment by sftim** [comment]
/triage accepted
/priority backlog

When working on fixes for this, make sure to consider the impact on all the downstream localizations that are currently consuming the existing keys.

**Comment by QuinceyJames** [comment]
Gotcha. Also, can we get #38287 merged before I start on this fix?
