### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice: Problems when building the project.

### ISSUE THREAD

**Issue by tanja3981** [kubernetes/website#38454]
The project cannot be build with maven, as there seem to be too many dependencies downloaded: 
Command `mvn package -pl system` results in

`[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project system: Could not build image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit -> [Help 1]`

**Comment by sftim** [comment]
/triage duplicate

This is a duplicate of issue #37994.

/kind bug
/language en

**Comment by mehabhalodiya** [comment]
Per [this comment](https://github.com/kubernetes/website/issues/38454#issuecomment-1350031815), I am closing this issue. Thanks!

/close
