### ISSUE TITLE
Document `--protect-kernel-defaults` argument to kubelet

### ISSUE THREAD

**Issue by YanzhaoLi** [kubernetes/website#38477]
### What happened?

There are 6 kernel parameters related to this parameters

- if not setting `--protect-kernel-defaults`: kubelet would restore the 6 kernel parameters to their default values when bootstrap, no matter what their values were.
- if setting `--protect-kernel-defaults`: kubelet would check whether the 6 kernel parameters were set to their default values, if not, kubelet would fail to start.

Thus, in both two cases, the 6 kernel parameters would be their default values when kubelet start.

### What did you expect to happen?

If in both cases the 6 parameters would be the same, I wonder what's the meaning of this parameters?  
Is it to let sysadmin know that kubelet has set the 6 kernel parameters to the default values?

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ documents `--protect-kernel-defaults` as a **deprecated** command line option. Cluster operators should not set this command line option.

I think this issue is already done.
/close
