### ISSUE TITLE
Wrong `cosign` command in “Verify Signed Kubernetes Artifacts” task

### ISSUE THREAD

**Issue by rascasoft** [kubernetes/website#38473]
The right command line for `cosign` usage should be:

```
cosign verify-blob "$BINARY" --signature "$BINARY".sig --cert "$BINARY".cert
```

So with `--cert` instead of the actual `--certificate` which is an unrecognized option, at least in `cosign` version 1.6.0.

**Comment by sftim** [comment]
/retitle Wrong `cosign` command in “Verify Signed Kubernetes Artifacts” task
/language en

**Comment by mengjiao-liu** [comment]
It appears that the version [v1.9.0](https://github.com/sigstore/cosign/blob/30bf1c09c6fde849245648ff294725d86094fe28/CHANGELOG.md#v190) of cosign has updated this parameter to --certificate

But for compatibility with previous versions, both --cert and --certificate can be used.

related issue:
- https://github.com/sigstore/cosign/issues/1847

related PR:
- https://github.com/sigstore/cosign/pull/1868

code：
https://github.com/sigstore/cosign/blob/1c04ce6299e63fe2af5823f7dcc4d179806208df/cmd/cosign/cli/options/certificate.go#L41

**Comment by rascasoft** [comment]
Today, if you follow the instructions (and so you download `cosign` 1.6.0), you get an error, so it might be useful to fix this anyway.

**Comment by mengjiao-liu** [comment]
Perhaps, the version of `cosign` needs to be indicated in the docs? 

For more advice. @sftim

**Comment by rascasoft** [comment]
> Perhaps, the version of `cosign` needs to be indicated in the docs?
> 
> For more advice. @sftim @saschagrunert

Yes, maybe that would fix the problem as well.

**Comment by saschagrunert** [comment]
I agree having the cosign version mentioned in the docs will help us to prevent such issues in the future.

**Comment by Shubham82** [comment]
Page to update: https://kubernetes.io/docs/tasks/administer-cluster/verify-signed-artifacts/

**Comment by Shubham82** [comment]
Can we also mention the note about cosign, something like this: if we are using cosign version v1.9.0+ we should use the `--cert` parameter instead of the `--certificate`
