### ISSUE TITLE
Incorrect shell command expression in Download Kubernetes page

### ISSUE THREAD

**Issue by zalmarge** [kubernetes/website#38484]
I am quite sure there's an error in a command to fetch a list of signed Kubernetes container images in SPDX 2.2 format. Right now it is stated (see https://kubernetes.io/releases/download/#container-images) that a list is fetched with:

```sh
curl -Ls "https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/latest.txt)/release"  | awk '/Package: registry.k8s.io\// {print $3}'
```

but this command does not return any output, as regexp in AWK does not match anything.

**Comment by sftim** [comment]
/retitle Incorrect shell command expression in Download Kubernetes page
/sig release
/kind bug
/language en

**Comment by Kartik494** [comment]
I have encountered the same problem , i just check the reference [here](https://github.com/kubernetes/website/pull/35827#pullrequestreview-1067543994) ,  i would like to give a try on this.

**Comment by tengqm** [comment]
Sounds like this is resolved.
