### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by RoyeA** [kubernetes/website#38496]
Tried and failed on the followings:
[ERROR] toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
[WARNING] An attempt failed, will retry 1 more times
org.apache.maven.plugin.MojoExecutionException: Could not build image

**Comment by sftim** [comment]
/triage duplicate

This is a duplicate of issue #37994.

/kind bug
/language en

**Comment by mehabhalodiya** [comment]
Per [this comment](https://github.com/kubernetes/website/issues/38496#issuecomment-1353490684), I am closing this issue. Thanks!

/close
