### ISSUE TITLE
The "To" version for removed feature gate HugePageStorageMediumSize is wrong

### ISSUE THREAD

**Issue by cbf123** [kubernetes/website#38498]
**This is a Bug Report**

**Problem:**
At https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/ the "To" version for feature gate HugePageStorageMediumSize  is listed as 1.24, however, on kubelet 1.24.4 I get the following error log:

`2022-12-15T02:57:08.113 controller-0 kubelet[1218042]: info Error: failed to set feature gates from initial flags-based config: unrecognized feature gate: HugePageStorageMediumSize`

**Proposed Solution:**
Change the "To" version to 1.23

**Page to Update:**
 https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

Kubernetes Version: 1.24.4

**Comment by cbf123** [comment]
Support for this feature gate was removed in commit 0447c48a which precedes the 1.24.0 branch.

**Comment by mengjiao-liu** [comment]
This feature was indeed removed from Kubernetes version 1.24.

See the PR for more details: https://github.com/kubernetes/kubernetes/pull/104120


But according to the definition of "To", there are no errors in the document.
```
The "To" column, if not empty, contains the last Kubernetes release in which you can still use a feature gate. If the feature stage is either "Deprecated" or "GA", the "To" column is the Kubernetes release when the feature is removed.
```

**Comment by cbf123** [comment]
My bad, I overlooked the difference if the feature stage is "GA".

I would suggest though that the semantics are confusing since in some cases it's the last release where you *can* use it, and in some cases it's the first release where you *can't* use it.

Arguably it would be better for consistency if the "to" release was always the last release in which you could still use the feature gate.  That way "from" and "two" would be inclusive endpoints in all cases.

**Comment by cbf123** [comment]
Confusingly, the other feature gate I was interested in ("TTLAfterFinished") is also GA, and shows 1.24 in the "to" field, but is still usable in 1.24.  The entry for it in kube_features.go reads:

	TTLAfterFinished:                               {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.25
	
So given that the comment says "remove in 1.25" shouldn't it show 1.25 on https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/ ?

**Comment by tengqm** [comment]
@cbf123 The comment `// remove in 1.25` doesn't matter. It is a reminder to those developers. However, sometimes they simply forget to remove the gate, or in more general, they forget to land these changes. We have to check if the gate is still  there in the `release-1.25` branch.

**Comment by sftim** [comment]
/triage not-reproducible

Please file a separate issue to report an issue with `TTLAfterFinished`.
