### ISSUE TITLE
Typo in "Feature Gates" page

### ISSUE THREAD

**Issue by jihoon-seo** [kubernetes/website#38503]
**This is a Bug Report**

**Problem:**
Typo in "Feature Gates" page
> - `TopologyManagerPolicyBetaOptions`: Allow fine-tuning of topology manager policies, experimental, **Beta**-quality options. This feature gate guards a group of topology manager options whose quality level is **alpha**. This feature gate will never graduate to stable.

cf.
> - `TopologyManagerPolicyAlphaOptions`: Allow fine-tuning of topology manager policies, experimental, **Alpha**-quality options. This feature gate guards a group of topology manager options whose quality level is **alpha**. This feature gate will never graduate to beta or stable.

> - `CPUManagerPolicyAlphaOptions`: This allows fine-tuning of CPUManager policies, experimental, **Alpha**-quality options This feature gate guards a group of CPUManager options whose quality level is **alpha**. This feature gate will never graduate to beta or stable.
> - `CPUManagerPolicyBetaOptions`: This allows fine-tuning of CPUManager policies, experimental, **Beta**-quality options This feature gate guards a group of CPUManager options whose quality level is **beta**. This feature gate will never graduate to stable.

**Proposed Solution:**
In `TopologyManagerPolicyBetaOptions`, replace `alpha` with `beta`.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=of%20topology%20manager%20options%20whose%20quality%20level%20is-,alpha,-.%20This%20feature%20gate%20will%20never%20graduate%20to%20stable

**Comment by chinu-anand** [comment]
Hi @SaumyaBhushan, could you provide an update on the progress of this issue? I'm particularly interested in knowing what the current status is and if I can carry on this issue.

**Comment by SaumyaBhushan** [comment]
@chinu-anand , I will submit a PR today .

**Comment by SaumyaBhushan** [comment]
Hi @chinu-anand submitted a PR please review.
