### ISSUE TITLE
Broken Link in Validating Admission Policy docs - 1.26

### ISSUE THREAD

**Issue by jimmyraywv** [kubernetes/website#38518]
**This is a Bug Report**

**Problem:**
The [admission request](https://kubernetes.io/pkg/apis/admission/types.go#AdmissionRequest) link in this [section](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#validation-expression) leads to a 404 error.

**Proposed Solution:**
Fix link to point to desired document.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/#validation-expression

Kubernetes Version: 1.26

**Comment by tengqm** [comment]
/triage accepted
This anchor should not point to the source code. It should point to the generated API reference instead.
