### ISSUE TITLE
HTML excerpt from CLA page

### ISSUE THREAD

**Issue by Operate1** [kubernetes/website#38529]
<a href="https://easycla.lfx.linuxfoundation.org/#/?version=2"><img src="https://s3.amazonaws.com/cla-project-logo-prod/cla-signed.svg" alt="CLA Signed" align="left" height="28" width="328" ></a><br/><br />The committers listed above are authorized under a signed CLA.<ul><li>:white_check_mark: login: Operate1 / name: مؤسسة أوبريت لتنظيف وصيانة المباني ونقل العفش  (6ce362ddee8cc63831ba4775bf391cd0db042dea)</li></ul>

_Originally posted by @linux-foundation-easycla[bot] in https://github.com/kubernetes/website/issues/38526#issuecomment-1356265938_

**Comment by sftim** [comment]
/retitle HTML excerpt from CLA page

Title was:
```

**Comment by sftim** [comment]
Seems like nonsense
/close
