### ISSUE TITLE
Help with CLA

### ISSUE THREAD

**Issue by Operate1** [kubernetes/website#38527]
<a href="https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38526/#/?version=2"><img src="https://s3.amazonaws.com/cla-project-logo-prod/cla-not-signed.svg" alt="CLA Not Signed" align="left" height="28" width="328"></a><br/><br /><ul><li><a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38526/#/?version=2' target='_blank'>:x:</a> - login: @Operate1 / name: مؤسسة أوبريت لتنظيف وصيانة المباني ونقل العفش . The commit (6ce362ddee8cc63831ba4775bf391cd0db042dea) is not authorized under a signed CLA. <a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38526/#/?version=2' target='_blank'>Please click here to be authorized</a>. For further assistance with EasyCLA, <a href='https://jira.linuxfoundation.org/servicedesk/customer/portal/4' target='_blank'>please submit a support request ticket</a>.</li></ul>

_Originally posted by @linux-foundation-easycla in https://github.com/kubernetes/website/pull/38526#issuecomment-1356265938_

**Comment by utkarsh-singh1** [comment]
HI @Operate1, can you please specify your issue in proper format as current format does not explain the issue.

/priority awaiting-more-evidence

**Comment by sftim** [comment]
The issue description is null (GitHub bug?)
Here's what was in the issue title before I simplified it:
> ```
> <a href="https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38526/#/?version=2"><img src="https://s3.amazonaws.com/cla-project-logo-prod/cla-not-signed.svg" alt="CLA Not Signed" align="left" height="28" width="328"></a><br/><br /><ul><li><a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38526/#/?version=2' target='_blank'>:x:</a> - login: @Operate1 / name: مؤسسة أوبريت لتنظيف وصيانة المباني ونقل العفش . The commit (6ce362ddee8cc63831ba4775bf391cd0db042dea) is not authorized under a signed CLA. <a href='https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38526/#/?version=2' target='_blank'>Please click here to be authorized</a>. For further assistance with EasyCLA, <a href='https://jira.linuxfoundation.org/servicedesk/customer/portal/4' target='_blank'>please submit a support request ticket</a>.</li></ul>
> ```

**Comment by sftim** [comment]
@Operate1 what's the problem you'd like help with?

/remove-priority awaiting-more-evidence 
/triage needs-information

**Comment by sftim** [comment]
Seems like nonsense
/close
