### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/update/update-intro/

### ISSUE THREAD

**Issue by rkg1979** [kubernetes/website#38540]
I appreciate the interactive tutorial but the main content how to define rolling upgrade is missing.  like how to define rolling upgrade strategy in a deployment, etc.

**Comment by tan-i-ham** [comment]
Hi @divya-mohan0209 @sftim , I would like try to do this task.

My idea is describing and presenting `RollingUpdate` strategy code example in [this page](https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/).
What do you think?

**Comment by Kartik494** [comment]
Hi @tan-i-ham please assign yourself  if you are currently working on this , else i would like to give a try if no one is currently working on it . Please let me know.
Thanks!

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
