### ISSUE TITLE
ReplicaSet Spec 'template' parameter should be required?

### ISSUE THREAD

**Issue by GoldenCave** [kubernetes/website#38541]
Hi there, I was reading the ReplicaSet API Reference documentation, and thought it was odd to see that the "template" parameter is not required: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/replica-set-v1/#ReplicaSetSpec

However, when I attempted to create a ReplicaSet declaratively without that property, it failed with the following error: 

```
"The ReplicaSet "myapp2-rs" is invalid:
* spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`
* spec.template.spec.containers: Required value"
```

In comparison, for the Deployment API Reference, the "template" is required there.
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec

Trying to create a Deployment without a template parameter gives the following error:
`
error: error validating "04-deployment.yml": error validating data: ValidationError(Deployment.spec): missing required field "template" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false"`

My thinking is that the same validation for the template argument should be used in ReplicaSet as it does in the Deployment.

**Comment by sftim** [comment]
This might be more a report about _Kubernetes itself_ than about the docs.

/sig apps
/language en

We can transfer this issue to [Kubernetes' main repo](https://github.com/kubernetes/kubernetes) if we believe that the docs are accurate and the complaint is about Kubernetes itself.

**Comment by GoldenCave** [comment]
Thank you sftim, I believe you are right. Shall I open this issue in that linked Kubernetes repo, and then post the link to that new opened issue here before we close this issue? Or is there different process that we need to follow? 
Thanks again.

**Comment by GoldenCave** [comment]
Hmm as a result of retesting this to add information to that other issue, I was not able to reproduce the original issue. I see now that they both have the same error, when applying a file like this: 

``` yaml apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
 ````
Error (for both Deployment and ReplicaSet):
```
The Deployment "myapp2-rs" is invalid:
* spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`
* spec.template.spec.containers: Required value
```
So, as a result I am not sure what to think. The `labels` is found within the `template` parameter normally, but it seems that condition is taking precedence over the enforcement of the `template` in general.  If the precedence is going to continue, I don't think the template being required really matters. Still, for consistency sake it would be nice to have. 

Version information: 

``` 
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:40:13Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tengqm** [comment]
It is not a website issue. The API reference are strictly and faithfully generated out of the upstream source code.
However, the comments in those source code are not accurate. A lot of fields are required by not correctly labelled such, while other fields are optional but not so commented.

A more interesting but subtle issue is that some fields are required when CREATing a resource, but not required during an UPDATE. This is not well documented as well.

If you want a more accurate API reference, you may try `docker run -p 8000:8000 tengqm/kab` and then open `http://localhost:8000`. That API reference has been thoroughly cleaned up for problems like these.
