### ISSUE TITLE
Blog article from 2015 (Borg: The Predecessor to Kubernetes) has broken links

### ISSUE THREAD

**Issue by ericvale0128** [kubernetes/website#38556]
### What happened?

Hi Team!
Thank you for your support.

I was in following the documentation with the link goes [here](https://kubernetes.io/blog/2015/04/borg-predecessor-to-kubernetes/).
But when I tried to go through the details about 1. [Pods] https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pods.md), 2. [Services](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md) and 3. [Labels](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md) on Github, it redirected to the 404 pages.

Maybe the Markdown documentations are missing...

Thanks.

### What did you expect to happen?

[https://kubernetes.io/blog/2015/04/borg-predecessor-to-kubernetes/](https://kubernetes.io/blog/2015/04/borg-predecessor-to-kubernetes/)

### How can we reproduce it (as minimally and precisely as possible)?

Adding restore the missing Markdown documentations.
1. [Pods](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/pods.md)
2. [Services](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md)
3. [Labels](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Sansar146** [comment]
Thanks for the confirmation @sftim , i will create PR for this.

**Comment by Sansar146** [comment]
Hi @ericvale0128 , i think, this issue is not solved, may i know why it is closed ?

**Comment by Sansar146** [comment]
I did the changes , planning to commit this week

**Comment by sftim** [comment]
/reopen

We should fix the issue. @ericvale0128 if you'd prefer not to own the issue, we can look for another contributor to open a replacement for it.
