### ISSUE TITLE
Interactive Tutorial - Configuring a Java Microservice

### ISSUE THREAD

**Issue by moaismario** [kubernetes/website#38552]
I had an issue in interactive tutorial (Step 1). when I ran command `mvn package -pl system` in terminal window I've got the error:
Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (default) on project system: Could not build image: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by tamilselvan1102** [comment]
/triage duplicate

This is a duplicate of issue https://github.com/kubernetes/website/issues/37994.

/kind bug
/language en

**Comment by mehabhalodiya** [comment]
Per [this comment](https://github.com/kubernetes/website/issues/38552#issuecomment-1357497826), I am closing this issue. Thanks!

/close
