### ISSUE TITLE
the file content/zh-cn/docs/tasks/administer-cluster/verify-signed-images.md seems to be redundant

### ISSUE THREAD

**Issue by Zhuzhenghao** [kubernetes/website#38577]
**This is a Bug Report**

**Problem:**
It sees that the file content/zh-cn/docs/tasks/administer-cluster/verify-signed-images.md is redundant.

This file seems to have been renamed to `verify-signed-artifacts.md`.

**Proposed Solution:**
DELETE the file.

**Page to Update:**
content/zh-cn/docs/tasks/administer-cluster/verify-signed-images.md

**Comment by mengjiao-liu** [comment]
/language zh
/triage accepted

Yes, en upstream has renamed this file in this PR https://github.com/kubernetes/website/pull/37841/files#diff-e8eb6dc057013909504174f5a95315a83cfd9cbd730e9db618d63c3d014e5942.

But zh-cn doesn't have this file yet, we need to rename  `content/zh-cn/docs/tasks/administer-cluster/verify-signed-images.md ` file  to `content/zh-cn/docs/tasks/administer-cluster/verify-signed-artifacts.md` and synchronize with the English upstream and perform translation synchronization.

**Comment by Zhuzhenghao** [comment]
Thanks @mengjiao-liu ，I'll do it.

**Comment by mengjiao-liu** [comment]
PR #38575 has fixed it.
/close
