### ISSUE TITLE
Document watch API

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/website#38572]
We don't really document how to use watch, and what we do have in api-conventions.md is out of date.

@lavalamp @smarterclayton

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/20075

**Comment by tengqm** [comment]
A long history ago, we have `watch` APIs. But I believe the `watch` API has been part of the `list` operation. It is a special case of `list` with an query string named `watch`. The `watch` behavior and how it works when combined with other related query strings are already well documented [here](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes). Maybe we can close this issue?

**Comment by sftim** [comment]
You can watch a collection, and _ think you can also watch a specific object.

---

I agree, this is documented now.

/close
