### ISSUE TITLE
Add documentation for how to debug binaries

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#38582]
**What would you like to be added**

Maybe somewhere in https://kubernetes.io/docs/tasks/administer-cluster/ there should a page for "Debugging components"

AFAIK, all components are shipped with an endpoint for [profiling](https://github.com/kubernetes/kubernetes/blob/dc1e77143fa9181b71d65fd642d3860612b74cbf/cmd/kube-scheduler/app/server.go#L283) and to [increasing the log level](https://github.com/kubernetes/kubernetes/blob/dc1e77143fa9181b71d65fd642d3860612b74cbf/cmd/kube-scheduler/app/server.go#L287) at runtime.

Additionally, the scheduler can dump its cache into the logs https://github.com/kubernetes/kubernetes/blob/dc1e77143fa9181b71d65fd642d3860612b74cbf/pkg/scheduler/scheduler.go#L328

**Why is this needed**

To learn how to debug live components.

**Comments**

Suggestions derived from https://github.com/kubernetes/kubernetes/issues/114507

**Comment by pohly** [comment]
Grep for calls to GlogSetter to find the places where log verbosity is changed. At first glance it looks like each component uses a different HTTP API for this.

**Comment by alculquicondor** [comment]
Profiling is documented in sig-scalability https://github.com/kubernetes/community/blob/4026287dc3a2d16762353b62ca2fe4b80682960a/contributors/devel/sig-scalability/profiling.md

It's probably worth making it part of the website too.

**Comment by alculquicondor** [comment]
It looks like all end in `/v`, but they might have a different prefix. The key is to search for https://github.com/kubernetes/kubernetes/search?q=StringFlagPutHandler

**Comment by sftim** [comment]
Not yet triaged as accepted
/remove-help
