### ISSUE TITLE
Document template variables

### ISSUE THREAD

**Issue by techtonik** [kubernetes/website#3858]
**Problem:**
Variables like `fullversion` are not covered in https://kubernetes.io/docs/home/contribute/page-templates/ 
I found that this site uses Jekyll and in Jekyll docs variables are stored in [_data](https://github.com/kubernetes/kubernetes.github.io/tree/master/_data) but there is just too much stuff and I could not find `fillversion`. For some reason `fullversion` is in [_config.yml](https://github.com/kubernetes/kubernetes.github.io/blob/master/_config.yml) and it is still no clear that it should be used as `{{page.fullversion}}`.

**Page to Update:**
https://kubernetes.io/docs/home/contribute/page-templates/

**Comment by techtonik** [comment]
/remove-lifecycle stale

It would still be nice to get help on available template variables for different contexts.

**Comment by tengqm** [comment]
@zacharysarah Should we close this as we are migrating to hugo?

**Comment by techtonik** [comment]
Documentation about variables will be actual for Hugo too. Unless it is available from the start.
