### ISSUE TITLE
Container Runtimes

### ISSUE THREAD

**Issue by dominiksr** [kubernetes/website#38581]
Documentation state than i should change file under /etc/containerd/config.toml but on ubuntu 22.04 its not there.
Containerd is active and running.

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
/language en

**Comment by sftim** [comment]
If the page is https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

then it says:
> Follow the instructions for [getting started with containerd](https://github.com/containerd/containerd/blob/main/docs/getting-started.md). Return to this step once you've created a valid configuration file, `config.toml`.

We could also add an extra sentence for readers who skipped that step, to send them back and remind them to do it.

**Comment by T-Lakshmi** [comment]
Hi @dominiksr,

I followed the steps mentioned in the [document](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd) and i could see the `config.toml` file under `/etc/containerd/ `directory.
Please make sure you followed the instructions mentioned under [getting started with containerd](https://github.com/containerd/containerd/blob/main/docs/getting-started.md) properly.

/kind support

**Comment by T-Lakshmi** [comment]
@sftim,

> We could also add an extra sentence for readers who skipped that step, to send them back and remind them to do it.

As per your suggestion, i created a new ticket #38611 to add extra sentence here.

**Comment by dominiksr** [comment]
> @sftim,
> 
> > We could also add an extra sentence for readers who skipped that step, to send them back and remind them to do it.
> 
> As per your suggestion, i created a new ticket #38611 to add extra sentence here.

It would be great. 

I know where I went wrong. When installing with apt, all dependencies were not installed. I repeated the process and there was the mentioned configuration file. 

Thanks for your help, I am closing this issue
