### ISSUE TITLE
log-dir and logtostderr are still referenced in the kubelet 1.26 docs although they were removed

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/website#38599]
**This is a Bug Report**

**Problem:**

The doc https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ shows documentation for log-dir and logtostderr:

```
--log-dir string
If non-empty, write log files in this directory. (DEPRECATED: will be removed in a future release, see [here](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components).)
```

but they were removed from kubelet in 1.26:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md): `Legacy klog flags are no longer available. Only -v and -vmodule are still supported. (https://github.com/kubernetes/kubernetes/pull/112120, [@pohly](https://github.com/pohly)) [SIG Architecture, CLI, Instrumentation, Node and Testing]`. The PR linked is merged in v1.26: https://github.com/kubernetes/kubernetes/pull/112120

Found in https://github.com/kubernetes-sigs/sig-windows-tools/pull/259#issuecomment-1362799339

**Comment by sftim** [comment]
I have a feeling that https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ needs a special process to update it after a release - maybe we didn't yet do that.

/sig release
/language en
/triage accepted
