### ISSUE TITLE
define-command-argument-container.md has different information for Eng/Indo translate

### ISSUE THREAD

**Issue by patrickdung** [kubernetes/website#38605]
**This is a Bug Report**

**Problem:**

[Source code - Indo](https://github.com/kubernetes/website/blob/main/content/id/docs/tasks/inject-data-application/define-command-argument-container.md)

[Source code - English, still present in release 1.22](https://github.com/kubernetes/website/blob/release-1.22/content/en/docs/tasks/inject-data-application/define-command-argument-container.md)

[English page on public web site](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/)

[Indo translate on public website](https://kubernetes.io/id/docs/tasks/inject-data-application/define-command-argument-container/)

There is missing information in the English website
There should be a section containing the table

![image](https://user-images.githubusercontent.com/38665827/209266294-fc305b18-2d24-462c-87de-b9951ebb829e.png)

It is present in the Indo translate and should also present in an English page (<=release 1.22).
So the table/session was taken out in release >=1.23.
Wanted to know why and where the section goes.

**Proposed Solution:**

Update the Hugo doc so that the English page can see the missing section(s).

**Page to Update:**
https://kubernetes.io/...

**Comment by mengjiao-liu** [comment]
> Wanted to know why and where the section goes.


Please see the issue https://github.com/kubernetes/website/issues/30971 for more details.

```
Remove the entire Notes section. Clean up the page so that there's no mention of a specific runtime.
```

PR https://github.com/kubernetes/website/pull/31058 clean up the section.

**Comment by patrickdung** [comment]
@mengjiao-liu Thanks for the info.

I make use of the table because the Docker container image in my k8s has defined both ENTPYPOINT and CMD. I would like to and arguments to the k8s deployment.

The table is very useful, could it be retained or the information can be placed in another page?

**Comment by mengjiao-liu** [comment]
k8s has removed dockershim since 1.24, and specific instructions for the use of docker are no longer retained.

> The table is very useful, could it be retained or the information can be placed in another page?

I'm not sure where users can get this right now.
/cc @sftim for more advice.

**Comment by sftim** [comment]
https://v1-22.docs.kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/ still has that table.

I think we could reinstate a similar table. My guess is that we removed it when removing references to Docker. When reinstating, we **must** adjust that table to use **Kubernetes** terms (and not Docker terms).
