### ISSUE TITLE
Hello Minikube

### ISSUE THREAD

**Issue by minhduchuynh** [kubernetes/website#38604]
Hi,

Help me check the dashboard please.
I cannot run "minikube dashboard" command.
May be it related with my last action: I created a deployment with 100 replicas.
Sorry if cause any problem on your system.

Thanks.

**Comment by T-Lakshmi** [comment]
Hi @minhduchuynh,
> I cannot run "minikube dashboard" command.

What is the output you are getting for above command? is it throwing any error or simply strucks?
meanwhile please check the cluster status with 'minikube status' command.

**Comment by minhduchuynh** [comment]
![Screenshot 2022-12-26 at 13 39 34](https://user-images.githubusercontent.com/110953086/209513113-cf5b658d-5ccb-4d95-a6cc-e94d889c0d7c.png)

**Comment by Ritikaa96** [comment]
Hi @minhduchuynh 
GitHub is not the right place for support requests.

If you're looking for someone to help you learn how to configure your Kubernetes cluster, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
