### ISSUE TITLE
Improve flow for Seccomp security tutorial

### ISSUE THREAD

**Issue by HamzaMasood1** [kubernetes/website#38603]
**This is a Feature Request**
Hi,
I would like to request a change made in seccomp.md doc page:
https://github.com/kubernetes/website/blob/b79539d0d35927eb51976d1115db500419a6c6b9/content/en/docs/tutorials/security/seccomp.md

It would make more sense if the "Create Pod that uses the container runtime default seccomp profile" section  was after "Enable the use of RuntimeDefault as the default seccomp profile for all workloads" section, and not the very last option of creating pods with seccomp profiles. I feel like it would improve the flow.

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tutorials/security/seccomp/
/language en

**Comment by SwapnilThatte** [comment]
I am new to the kubernetes website project,
Can I work on this issue ?

**Comment by sftim** [comment]
/retitle Improve flow for Seccomp security tutorial

**Comment by sftim** [comment]
Anyone can work on this issue, providing that they follow our [code of conduct](https://kubernetes.io/community/code-of-conduct/).

**Comment by Shubham82** [comment]
Hi @SwapnilThatte, Are you working on this issue?

**Comment by Shubham82** [comment]
if no one is working on this then I'm up for it.

**Comment by Shubham82** [comment]
Hi @sftim, @saschagrunert  
will this seems valid to you?

**Comment by saschagrunert** [comment]
@Shubham82 yeah I think having a slightly different order of the sections would make understanding the topic better. I'm in favor of that! :)

**Comment by Shubham82** [comment]
thanks @saschagrunert for your views on this.
I will soon create the PR for it.

**Comment by Shubham82** [comment]
Fixed it here: #39109
