### ISSUE TITLE
create-hostprocess-pod.md contains double-pasted content

### ISSUE THREAD

**Issue by ppbits** [kubernetes/website#38609]
Doc Link: https://github.com/ppbits/website/blob/main/content/en/docs/tasks/configure-pod-container/create-hostprocess-pod.md

The following section contains double pasted content: "_passwords for local user accounts._".

> This provides a number a benefits including eliminating the need to manage passwords for local user accounts. _passwords for local user accounts._ An initial HostProcess container running as a service account can be used to prepare the user groups for later HostProcess containers.

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/
/triage accepted

**Comment by jihoon-seo** [comment]
@akash-mohanto please note that @ppbits already opened the PR #38610 to fix this issue.
/assign @ppbits

**Comment by mehabhalodiya** [comment]
Resolved in #38610 

/close
