### ISSUE TITLE
Advocate Deployment instead of ReplicationController in docs

### ISSUE THREAD

**Issue by kargakis** [kubernetes/website#3863]
Moved from https://github.com/kubernetes/kubernetes/issues/18465

**Comment by ryanmcginnis** [comment]
+1. This is a confusing experience unless you already happen to know how Deployments work. What's worst is that we call this out as a seemingly "current" feature in places like the interactive tutorials (bad). It seems to me that this feature is mostly deprecated.

**Comment by ryanmcginnis** [comment]
/remove-lifecycle rotten

This should be addressed.
