### ISSUE TITLE
Typo in the command: The command should be kubeadm init rather than kubeadmin init

### ISSUE THREAD

**Issue by akash-mohanto** [kubernetes/website#38646]
reference:  https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file

**Comment by akash-mohanto** [comment]
> /assign

@SaumyaBhushan hello, can you please leave this issue...as this will be my first contributions towards open source. hope you don't mind.

**Comment by SaumyaBhushan** [comment]
Sure @akash-mohanto
