### ISSUE TITLE
[zh-cn] zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins problems with the style

### ISSUE THREAD

**Issue by LetFu** [kubernetes/website#38654]
**This is a Bug Report**

**Problem:**
There is a problem with the layout of the hints on this page, as there are multiple nested hints in the "API 兼容性" section, and the headings are also nested within them. Some comments are also shown.
**Proposed Solution:**
Take the "监控设备插件资源" title out of the nesting. Comments are correctly hidden.
**Page to Update:**
https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#api-compatibility

**Comment by arjunan-k** [comment]
triage/accepted
