### ISSUE TITLE
Expandable side navigation is hard to use on small screens

### ISSUE THREAD

**Issue by martingbrown** [kubernetes/website#38663]
**Problem:**

The expandable tree navigation on the left hand side of the screen is hard to use on a small screen. It is OK at the first level of expansion, but two or three levels down the links are so narrow barely a word fits before it starts wrapping.

For example I have a 13" laptop. When I have the browser full screen, and expand Concepts>Overview>Working with Kubernetes Objects the next level down is not wide enough to fit the word "Understanding" let alone the rest of the title "Understanding Kubernetes Objects".

![image](https://user-images.githubusercontent.com/5264795/209686398-73d19f4b-c16a-4f34-9cf3-8a23276d4759.png)

I'm using Windows 11 22H2 and Edge 108.0.1462.54 (though I can see the same on Chrome and Firefox). I have a 13.3" 3840x2160 display and the magnification is set to 300% which is the recommended settings. In JavaScript Window.screen.width and Window.screen.height are returning 1280 & 720.

**Proposed Solution:**

I don't really know what the best thing to do here is, I'm not a UI designer, but here are some suggestions:

1. When the screen size is small make it hide and then pop-out when a menu button is pressed.
2. Make the split between the menu and content draggable.
3. Re-arrange the tree so that minor levels are not indented.

**Page to Update:**
All

**Comment by sftim** [comment]
13" is not really a small screen; there are plenty of devices with screens that size, including the PC I'm using right now. I get the impression that Windows is doing something funny if it's pretending that the true resolution is 1280x720. Even so, we have to live with that Windows behavior around scaling: we can't change how Windows does things.

I know that macOS has it's own approach to high DPI displays, where you can either have a 1:1, 4:1 or 9:1 [mapping](https://developer.apple.com/documentation/uikit/uiscreen/1617836-scale/) of physical pixels to logical display pixels. We might need to account for that too.

Here's two sample renderings for a similar-size display:
![Screenshot 1](https://user-images.githubusercontent.com/22591623/209979940-3427c6bd-6ab8-4acc-95ae-e714d08ca9e3.png)
![Screenshot 2](https://user-images.githubusercontent.com/22591623/209979942-e5558c1e-f69b-413f-997d-3e30be980bc9.png)

These look fine to me (I generated them using Firefox on Ubuntu). However, there's clearly an issue. I suspect that the answer is going to be to make the website render differently at high magnifications, when the viewport is landscape.

@martingbrown could you provide a full-screen screenshot to illustrate the issue better?

We should also check whether this is an issue with Docsy in general, or with our customizations to Docsy. If our customizations are linked to this issue, it'd be nice to see how whether we can omit some of them - falling back to the Docsy theme's default behavior - and still have a usable site.

The more we can rely on the theme for handling things like this, the easier the site becomes to maintain.

**Comment by Ritikaa96** [comment]
I just saw a similar issue and tried to search if k8s.io is responsive ? was this feature added already?
Just sharing some of the ideas I got  to improve the user experience, These changes can be considered:

- **Making a Collapsible Sidebar:**  we can add a button on top of the page to get the sidebar content with a better space coverage
- **Removing/shuffling the Right side content of the page**: The right side shows- `edit the page`, `create a child page`, `create issues`, etc options. we can leave them in the form of icons only and let the user hover over icons to know which action will they perform. this might save some space. For reference, I'm talking about this section on the webpage :

![Screenshot from 2023-02-23 13-52-31](https://user-images.githubusercontent.com/52399571/220857216-fd50083d-9820-47b2-a9a2-b12e92585f66.png)

Im not sure if these are acceptable but thought i could share some insights.

**Comment by martingbrown** [comment]
I tried it on Ubuntu with Firefox and it looks just the same:

![image](https://user-images.githubusercontent.com/5264795/221023331-05f9c333-2be9-4c82-ae13-28907980d5a5.png)

I don't think the browser showing the screen as 1280x720 is that odd. Browsers have used logical rather than device pixels for a long time. [The CSS spec](https://www.w3.org/TR/css-values-3/#px) defines a pixel as a visual angle of 0.0213 degrees. With a nominal arm length of 28", that gives you 1/96" at arms length. This was done to make websites designed for old monitors still work on High DPI screens. With 1px = 1/96", 1280x720 is 13.3"x7.5". That seems a little large, but the manufacturers of my laptop probably assumed a slightly longer viewing distance.

Note I also have Ubuntu set to 300% scaling. The text fits if I set Ubuntu to 100%, as it does on Windows, but the text is probably only 2mm tall so is nearly impossible to read, especially for those of us that need glasses in our old age.

**Comment by sftim** [comment]
It sounds as if this is partly an issue with page zoom (and slightly accessibility). If you use a browser with a small physical viewport the page lays out another way, but that doesn't apply for zoom.

/triage accepted
/priority backlog

I'm not sure it's a bug, or an enhancement we didn't make yet. I'll leave it marked as a bug.

**Comment by tengqm** [comment]
/kind feature
I'd like to see something like a jQuery splitter inserted between the left nav panel and the main content.
Static allocation of screen asset is not always the best choice.

**Comment by KhushPatibandha** [comment]
@zeusbee are you still working on this issue ?

**Comment by sftim** [comment]
See: https://github.com/kubernetes/website/pull/41695
