### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by celebdor** [kubernetes/website#3866]
This is a Feature Request

**Problem:** Currently we rely on a heredoc in order to configure el7 repositories for kubeadm installation. It is much more convenient and expected to have repofiles available for download.

**Proposed Solution:** I would like to propose having a .repo file in 
`https://packages.cloud.google.com/yum/kubernetes.repo`

with the following contents:

```
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/kubeadm/

Also, we would need the static repo file to be created and hosted.

**Comment by jbeda** [comment]
@timothysc -- you understand this stuff better than me.  Does this make sense to you?

@mikedanese -- this would require a new file hosted on a server that no one but you has access to.  Thoughts?

**Comment by mikedanese** [comment]
I'm hesitant to do more work with the current infra. If we spend time on this we should be working on fixing https://github.com/kubernetes/release/issues/281

**Comment by celebdor** [comment]
@mikedanese the last message on the issue about moving to cncf managed infra is about a month old. Is there somewhere else we can keep track of this development?

**Comment by timothysc** [comment]
So I'm all for this, but are we *ever* going to have community managed infra?

**Comment by timothysc** [comment]
@mikedanese per discussion on the sig call and following up with CNCF I don't think that anyone other then google could host in the near term.
