### ISSUE TITLE
Issue with /docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by pfritzsche** [kubernetes/website#3868]
**This is a...**

- [ ] Feature Request
- [x] Bug Report

**Problem:**
1. Go to https://kubernetes.io/docs/tutorials/kubernetes-basics/
2. Shrink browser window to around 1000px wide (or something narrow enough to trigger the tablet view of the page)
3. Text is cut off on the left side of the page

Environment: macOS 10.12.4, Google Chrome 58.0.3029.110

**Proposed Solution:** ¯\\\_(ツ)\_/¯

Thanks for looking into it!

**Comment by ahmetb** [comment]
Looks like `<main class="content">` element has a margin-left:200px on the css causing this. This rule seems to only exist in kubernetes-basics tutorial and does not seem like it serves a purpose other than causing this bug.

**Comment by BenHall** [comment]
Thanks for the feedback. We've improved the look and feel of the layout which will hopefully create a much better experience.

**Comment by ahmetb** [comment]
@BenHall thanks! looks much better on w=1000px now. Closing.
