### ISSUE TITLE
Hindi localization should not use pure Hindi

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes/website#38693]
**This is a Feature Request**

**What would you like to be added**

Easily Readable Hindi language.

**Why is this needed**
It looks like the Hindi that is used in the docs is directly translated using random translator. This Hindi is hard to read. Indians don't use this Hindi language in their daily life.
For ex: (https://kubernetes.io/hi/docs/home/)[Home page]
 I am not talking about any particular page. In whole docs need an update.

**Comments**
If you are someone from India. We can change this in readable Hindi format and I am ready to work on this. This will help many beginners who don't understand English properly and want to start in k8s.

**Comment by bishal7679** [comment]
Hey @Sajiyah-Salat could you please explicitly elaborate your issue
What you want to be updated to not pure hindi or anything else??

**Comment by sftim** [comment]
/retitle Hindi localization should not use pure Hindi

**Comment by sftim** [comment]
From https://kubernetes.io/hi/docs/home/, could you give an example of some text that you found hard to read @Sajiyah-Salat ?
