### ISSUE TITLE
Kubeadm documentation Google Cloud public signing key

### ISSUE THREAD

**Issue by Igec1** [kubernetes/website#38696]
This command from the official documentation https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ is not working on Ubuntu 18.04.6 LTS : 

![image](https://user-images.githubusercontent.com/96411896/210065350-6674efe4-fe3c-449d-8132-b063b717bd8f.png)

The response after the execution is curl: (23) Failed writing body (0 != 1377).

Anyone else encountered this issue recently ?

**Comment by neolit123** [comment]
> Anyone else encountered this issue recently ?

i think i've seen reports from users where the key is temporarily unavailable for download but with a different error. also it works after a while. did it work for you after more tries?


/kind support

**Comment by sftim** [comment]
That error can also occur if you try to access the signing key from a country that imposes state-level censorship. If your country has that kind of censorship, you might need to make your own packages instead.

**Comment by Igec1** [comment]
It seems that the /etc/keyrings doesnt exist by default in Ubuntu 18.04.6 LTS , seems that I have missed that part in the documentation.

![image](https://user-images.githubusercontent.com/96411896/210350305-3686891b-2d75-41d7-8084-50d40b2a8138.png)

After creating the directory , the curl command worked fine.
