### ISSUE TITLE
Document how to create a normal user accounts other than service accounts

### ISSUE THREAD

**Issue by bobbychef64** [kubernetes/website#3869]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
I did't find information about how to create a normal user accounts other than service accounts. I created the k8 cluster with the help of kops and i got the config file present under .kube/config file . This file contains the admin username and password . if normal users like QA or devs want to access to clusters  i am providing the admin config file for accessing the pods and other info . How can i restrict this with out providing the config file

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
Looks like we're lacking documentation on how to use `kubectl config` to add new auth, clusters and contexts.

**Comment by bobbychef64** [comment]
And also how i am using the version 1.6 k8 beta. we are under impression that beta version's means newly added features like [RBAC] are already enabled.  Is this enabled by default or we have to do anything to enable. I have seen some comments stating that restart the api-server with auth mode --rbac. But i did't find any document on restarting or staring k8 api-server.

**Comment by ahmetb** [comment]
@bobbychef64 unrelated to this issue but I must answer: if something is saying "this feature is beta in kubernetes 1.6" and you're using kubernetes 1.6, the feature is already there, but it may be subject to various changes as it graduates into stable. you don't need to do anything to enable it. we don't have beta releases, so you're using kubernetes 1.6 (not 1.6-beta).

**Comment by bobbychef64** [comment]
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by bobbychef64** [comment]
This is what k8 documentation says

Role-Based Access Control (“RBAC”) uses the “rbac.authorization.k8s.io” API group to drive authorization decisions, allowing admins to dynamically configure policies through the Kubernetes API.
As of 1.6 RBAC mode is in beta.
To enable RBAC, start the apiserver with --authorization-mode=RBAC

Hence i got a doubt that how to start the apiserver ?

**Comment by ahmetb** [comment]
@bobbychef64 that might be true for that particular feature, sorry I am not closely familiar.

**Comment by bobbychef64** [comment]
no problem thanks for support

**Comment by liggitt** [comment]
all API server configuration changes controlled by flags require an API server restart
