### ISSUE TITLE
A few LimitRange examples don't declare mandatory LimitRange.spec.limits.type

### ISSUE THREAD

**Issue by sakurai-youhei** [kubernetes/website#38705]
**This is a Bug Report**

**Problem:** LimitRange examples cause a validation error due to the missing `type` field since [this commit](https://github.com/kubernetes/api/commit/026463abc787fb00b827ab365504a9bf28d90f4e) mandated it.

```shell
root@wsl:~# kubectl create -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/concepts/policy/limit-range/problematic-limit-range.yaml
error: error validating "https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/concepts/policy/limit-range/problematic-limit-range.yaml": error validating data: ValidationError(LimitRange.spec.limits[0]): missing required field "type" in io.k8s.api.core.v1.LimitRangeItem; if you choose to ignore these errors, turn validation off with --validate=false
```

**Proposed Solution:** Add `LimitRange.spec.limits.type: Container` to the examples.

**Page to Update:**

- https://kubernetes.io/docs/concepts/policy/limit-range/
  - https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/concepts/policy/limit-range/problematic-limit-range.yaml
- https://kubernetes.io/zh-cn/docs/concepts/policy/limit-range/
  - https://raw.githubusercontent.com/kubernetes/website/main/content/zh-cn/examples/concepts/policy/limit-range/problematic-limit-range.yaml

**Comment by tengqm** [comment]
Fixed.
/close
