### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-linux/

### ISSUE THREAD

**Issue by barronandersonmongo** [kubernetes/website#38702]
Using the curl download instructions, no instructions have been included to clean up after the install is done.  These instructions pollute my home directory.  It would be helpful to include instructions how to delete these files - the kubectl binary and the sha256 checksum file.  Else, adding details suggesting running these commands will cause files to be downloaded into the home directory and they will stay there indefinitely and not be used after the install is complete would be helpful.  This way I know its safe to delete them.

**Comment by sftim** [comment]
Good idea

/kind feature
/language en
/triage accepted

/help

**Comment by asarenkansah** [comment]
I can pick up this issue, this will be my first contribution

**Comment by sftim** [comment]
/close

Done (mostly)
