### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by doroncarmeli** [kubernetes/website#38714]
This tutorial just killed my functioning Kubernetes cluster
After doing it cluster, with all resources pods and services is completely down

**Comment by doroncarmeli** [comment]
I once had a 6 nodes cluster (3 masters , 3 workers) 
I wanted to setup an etcd cluster in it 
Used the tutorial and no I have a nothing cluster

**Comment by neolit123** [comment]
the page in question is about setting up a new external etcd cluster and not migrating an existing etcd cluster to external.

such actions are not recommended in general due to the chances of rendering the k8s cluster as broken. an experienced admin might be able to do it but there are a number of important topics to keep in mind - synced etcd backup, new certificates, correct order of actions.

/kind support

leaving to sig docs to triage, but from the kubeadm side i don't think we want to maintain a new scoped guide on this topic.

**Comment by sftim** [comment]
This isn't really a support query, it's more a complaint.

I don't think it's really a valid complaint. Don't follow a new-cluster setup guide for a working cluster, unless you're willing to discover that your learning has left that cluster broken.

/triage unresolved

Things we could do:
- clarify in https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/ that this is for a _new_ cluster, not a guide to updating your existing cluster
- file a feature request for a task page that explains how to migrate a working cluster to use an external, replicated etcd cluster
  - if we can find folks willing to maintain that guide, let's document it. If we can't find volunteers, then we can at least make it clear that there's an issue on the backlog.
- add an issue to track adding some actual tutorials that let people explore cluster creation and maintenance. We don't have any _tutorial_ pages on that theme as yet - see https://kubernetes.io/docs/tutorials/ for what we do have.

--- 

@doroncarmeli, I know that in the Kubernetes ecosystem there can be people willing to work on adding and maintaining those new docs. What you might not like is that many of them already have things they're working on, either as volunteers or in their day jobs.
What this means is that even if we do file issues as I've suggested, that doesn't by itself make it likely that these pages turn up soon.

**Comment by sftim** [comment]
Unless we've obviously misunderstood the situation, this is OK to close say a week from now. @doroncarmeli you are also welcome to close this issue sooner.
