### ISSUE TITLE
ZooKeeper tutorial title is confusing

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#3873]
Discussion at #3851. https://kubernetes.io//docs/tutorials/stateful-application/zookeeper/ the "CP" in this title needs explanation.
/assign @chenopis

**Comment by stephanlindauer** [comment]
:grin: 
true. also why is the "A" uppercase? do they actually mean "CAP"?

**Comment by chenopis** [comment]
Yeah, I think CAP, CP, and AP need to be explained or referenced in the doc. It's not mentioned anywhere else.

**Comment by shubheksha** [comment]
Still not resolved.
/remove-lifecycle rotten

**Comment by ajaeger** [comment]
/assign

https://kubernetes.io//docs/tutorials/stateful-application/zookeeper/ looks fine to me now, this is fixed. I will close this now.
