### ISSUE TITLE
Overlap of Navbar links  at 770px-801px

### ISSUE THREAD

**Issue by Frenziecodes** [kubernetes/website#38739]
The navbar links do not fit in the space available.
![Screenshot (85)](https://user-images.githubusercontent.com/104835999/210401433-e9f9c7cb-637f-4580-961a-fed9aa4cd3d3.png)

**Comment by sp7infinity** [comment]
Hey @lewisushindi are you working on this? I'd like to take this up if you aren't.

**Comment by sftim** [comment]
/area web-development

PRs are welcome!

**Comment by lewisushindi** [comment]
@sp7infinity am working on it

**Comment by Gauravpadam** [comment]
I can't reproduce this, is it already fixed?
/triage needs-information
