### ISSUE TITLE
Interactive Tutorial - Exploring Your App

### ISSUE THREAD

**Issue by randomtest99** [kubernetes/website#38747]

**Comment by T-Lakshmi** [comment]
Hi @randomtest99,
What is the issue you are facing for the interactive Tutorial - [Exploring Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/)?

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
