### ISSUE TITLE
Umbrella issue: localize Kubernetes website to Gujarati

### ISSUE THREAD

**Issue by harsh4870** [kubernetes/website#38740]
## Maintainers

 - @harsh4870
 -  @9-para

This issue tracks Gujarati Documentation progress.

Kubernetes Website Repository: https://github.com/kubernetes/website

### Join the Slack
Join the [Kubernetes Slack](https://slack.k8s.io/)
Join the [sig-docs-localizations](https://kubernetes.slack.com/messages/sig-docs-localizations)

### Checklist to translate a term

_not yet live_

1. ~Check that no one else has claimed the page in the comments below.~
1. ~Comment below the page that you would like to localize, focusing on one page per PR, at a time.~
1. ~Maintainers will add your username and Pull Request next to your selected page in the below checklist.~
1. Fork this repo, make your localizations, and submit a pull request following the name convention _[gu] Localize <path.md>_
1. For example: &&[gu] Localize `docs/tasks/administer-cluster/kubeadm/_index.md`**
1. ~Target dev-1.23-gu.1 while creating the PR~
1. ~Tag/ping a maintainer to make it easier to track progress~

~You may check this week's [PR wrangler's list](https://github.com/kubernetes/website/wiki/PR-Wranglers)~

You may join the Google [#sig-docs](https://groups.google.com/g/kubernetes-sig-docs) group

### Points to remember:

- Please use the word localization instead of translation.
- For more information on how to contribute, check out [guidelines](https://kubernetes.io/docs/contribute/)

### For Volunteers
Volunteers can comment below on this issue with the page name they are interested in documentation
Please also provide a placeholder PR in your comment.

Example: I would like to contribute to content/gu/<xyz.md>

Status done ? | Assinged | Page | Owner | MR Link | MR Status
-- | -- | -- | -- | -- | --
TRUE | TRUE | i18n/gu.toml | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | README-gu.md | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | data/i18n/gu/gu.toml | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | content/gu/_index.html | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | content/gu/case-studies/_index.html | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | content/gu/OWNERS | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | includes/task-tutorial-prereqs.md | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | releases/_index.md | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | docs/_index.md | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | docs/home/_index.md | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
TRUE | TRUE | docs/home/supported-doc-versions.md | Harsh | https://github.com/kubernetes/website/pull/38782 | Draft
FALSE | TRUE | [content/en/docs/test.md](https://github.com/kubernetes/website/blob/main/content/en/docs/test.md)  | @devarsh10   |   |Pending  
FALSE | FALSE |   |   |   |  
FALSE | FALSE |   |   |   |

**Comment by sftim** [comment]
/language gu

We can add that language code once we have a localization team.

**Comment by sftim** [comment]
@harsh4870 you have jumped ahead a bit. I will strike through the details that are not yet right.

**Comment by sftim** [comment]
@9-para, can you confirm you'd like to start work on localizing to Gujurati?

**Comment by sftim** [comment]
I edited the issue description: right now there are no maintainers, there is no Gujurati branch, and English reviewers are mostly unlikely to be able to help to review Gujurati PRs.

**Comment by 9-para** [comment]
Hi @sftim  Yes will be helping harsh and together will do the localisation in GU lang.

**Comment by devarsh10** [comment]
Hey @sftim, I would like to be in this team. As my native language is Gujarati. And can move ahead with localisation.

Regards.

**Comment by harsh4870** [comment]
@devarsh10  here are details for the K8s website Gujarati language localization. 

Doc : https://docs.google.com/document/d/1lprlRKJitCGejLXd8HIoE2nar8pQfHMY9B3HZbL70To/edit

Status tracking: https://docs.google.com/spreadsheets/d/1EDzeaPZ-bPPZa4_5x4eFvwCHEOH8DcNXLygsUiuihX4/edit?usp=sharing

If you wish, you could start with one or two pages. Feel free to review my Draft MR link available in the sheet. 

Feel free to ping me if have any doubts. 

Thanks

**Comment by sftim** [comment]
Hi.

I recommend using GitHub issues to track localization work, and pull requests for changes. The reason: if you work too much outside the usual ways of working for Kubernetes, it may be more difficult to accept the final result.

**Comment by devarsh10** [comment]
Hey @harsh4870, may I work on the localisation of this file?
[content/en/docs/test.md](https://github.com/kubernetes/website/blob/main/content/en/docs/test.md)

**Comment by harsh4870** [comment]
@devarsh10  Sure, please feel free to go ahead..!

**Comment by devarsh10** [comment]
Hey @harsh4870, I localized test.md to Gujarati. Please take a look and review it.

Regards.

**Comment by harsh4870** [comment]
Starting again on this with other folks
