### ISSUE TITLE
Mark Katacoda as pending removal

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38785]
**This is a Feature Request**

**What would you like to be added**
For pages that have a button to launch Katacoda tutorials, change that page to:

- revise the appearance of the Katacoda button to make the banner really obvious
  - this could be, for example, an explanatory text with a link to an article, and then a checkbox
  - when the box is checked, use CSS to reveal the Katacoda launch button.
- include a [pageinfo-style banner](https://www.docsy.dev/docs/adding-content/shortcodes/#pageinfo) at the top that Katacoda will no longer be available from [specified date]

We can use [`.HasShortcode`](https://gohugo.io/templates/shortcode-templates/#checking-for-existence) to decide whether or not to show the banner

**Why is this needed**
[Katacoda will be shut down](https://github.com/kubernetes/website/issues/33936#issuecomment-1346832443).
We should let users know that the removal is due.

**Comments**
We'll need to agree that date with O'Reilly, who run Katacoda but are discontinuing the public service.

We can also announce the removal work in the [blog](https://blog.k8s.io/). Maybe a replacement, too, if we can staff that.

**Comment by sftim** [comment]
/area web-development

/priority critical-urgent
IMO

**Comment by sftim** [comment]
Want to help on this? Feel free to reply with questions - as this is urgent work, SIG Docs should prioritize giving you answers!

**Comment by a-mccarthy** [comment]
Communication channels we need to reach out to
* Blog post
* Slack
* Mailing List (k-dev) - is there any other?
* KubeWeekly (CNCF newsletter – submissions accepted till Thursdays at 12pm CT  - email content to Kubeweekly@cncf.io)   
* LWKD w/ Josh Berkus
* Localization teams

To coordinate the efforts on sending out these communications, we should form a team to get started on the messaging, create issues, and track the ongoing work to get this done. The first priority of the team should be to make sure we have a completed list of tasks and an estimation of how much time it will take to complete the work. This can be used to coordinate a reasonable turn off date for Katacoda. 

For this effort, our priority is on communicating this change around the upcoming shut down of the the tutorials and cleaning up the tutorial pages. There is a separate and parallel conversation to be had around finding a suitable replacement for Katacoda, see this discussion for more information and to share your thoughts: https://github.com/kubernetes/website/discussions/38878 

This affects 25 pages tutorial pages (and their localizations) as well as a whole separate repo: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios. This issue comment has the pages listed: https://github.com/kubernetes/website/issues/33936#issue-1247534383.

cc: @natalisucks @divya-mohan0209 @sftim @reylejano I brought over a summary of our discussion from the community meeting earlier this week. Hopefully its accurate :)

**Comment by sftim** [comment]
I have less cycles for this than I did for the Dockershim thing. Happy to help a bit though.

**Comment by natalisucks** [comment]
A couple of updates:

- Taylor (@onlydole) is checking with CNCF folks about the possibility of them hosting the Katacoda content from O'Reilly, given the CNCF is looking for content to share with universities and educational facilities to teach folks about cloud native projects. We'll update this issue with any progress on that front
- In parallel, I am in the process of drafting up communication about the Katacoda shutdown, which I will link to here once a draft is ready for review (my aim is this weekend). I'd be happy for folks to volunteer to help turn this communication into smaller snippets for the different distribution options that are [listed above](https://github.com/kubernetes/website/issues/38785#issuecomment-1380713261). As a note, I am volunteering to run this part of the work
- There will need to be another work stream setup for the removal of Katacoda content/links to content (creating issues, tracking work), which we acknowledge would be done _after_ communications about the removal are completed. For folks interested in this work stream, please let us know. We envision running this similar to the Dockershim removal, where a separate Slack channel/Project Board is created to manage the work, so as not to flood main channels and repos

**Comment by nate-double-u** [comment]
> There will need to be another work stream setup for the removal of Katacoda content/links to content (creating issues, tracking work), which we acknowledge would be done after communications about the removal are completed. For folks interested in this work stream, please let us know. We envision running this similar to the Dockershim removal, where a separate Slack channel/Project Board is created to manage the work, so as not to flood main channels and repos

I'd be happy to help with this work

**Comment by natalisucks** [comment]
Update: We've gotten in touch with O'Reilly with a proposed shutdown date and have a draft blog post in the works, which can be used as the main source of information for the other communication channels mentioned by @a-mccarthy above. Will link to the draft once a PR has been opened 👍

**Comment by natalisucks** [comment]
Draft of @sftim's banner PR for the proposed shutdown is here: https://github.com/kubernetes/website/pull/39257

**Comment by sftim** [comment]
/close

Katacoda is removed / gone
