### ISSUE TITLE
[zh-cn] Translator can be signed when translating blog

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/website#38793]
Recently, when I was looking at Chinese blogs, I found that the translated blogs did not have the translator's signature, which is inconsistent with the usually signed behavior of translated articles or books.

Moreover, translating a blog takes a lot of time and experience. Correctly adding a signature is a recognition of the translator's work, which is more conducive to motivating contributors to synchronize English blogs and enhancing the quality of blogs.

Of course, the translator can also give up the signature. This depends on personal preference and is not mandatory. 

Among other localization documents, the translated blog in the Korean localization document has translators added.

Open the issue to apply for more people’s suggestions and record this behavior for the reference of contributors.

For example in content/zh-cn/blog/_posts/xxx.md:

```
<!--
**Author**: Alice (Google)
-->
**作者** ：Alice (Google)

**译者** ：李明 (百度)  
```
The company the translator works for can be written or not, it depends on the translator himself.
/language zh

/cc @kubernetes/sig-docs-zh-reviews 

I have asked @tengqm about this and it hasn't been discussed before.

**Comment by howieyuen** [comment]
👏

**Comment by my-git9** [comment]
👏

**Comment by windsonsea** [comment]
👍 +1

**Comment by Sea-n** [comment]
+1
I agree with this proposal!
In addition, I would prefer to put the translator's name at the end of the article.

Reason:

Maybe we will better understand who (and which company) write this article.
e.g., XX feature is mainly supported by XX company.

But we don't choose which article to read by translators, we can judge the translation quality after reading it.

**Comment by tengqm** [comment]
+1
We can make this an umbrella issue and add back translators for those blogs already translated.
For future translations, we remind the author to sign their names.

**Comment by SD-13** [comment]
So, we will be adding the signature right? just conforming. Also, do we gonna follow this pattern `XX feature is mainly supported by XX company` mentioned by @Sea-n? I think it's better than just adding the signature. Thanks,

**Comment by tengqm** [comment]
I don't think we want to go that far as to attributing feature to companies.
The original intent of this proposal is to show credits to the translators.
By allowing/encouraging a translator to put his/her name side-by-side with the original author,
we want people to know the names of the heros behind the localization.
Most of the time, translating a blog is a time consuming task, and it requires some extensive
knowledge about the technology that is discussed.

**Comment by howieyuen** [comment]
yeah, we are open-source contributors, we gather here for the common interest, prove ourselves not the company we temporally belong to

**Comment by SD-13** [comment]
Hey, I need a help. For already translated blogs, where can I get the translators name? Thanks,

**Comment by Sea-n** [comment]
I think we have reached the consensus that zh translators can optionally add their names to the blog article. And some of us already do that in new PRs.

Should we add this rule to the [zh guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/) page and mark this discussion issue as resolved?

**Comment by mengjiao-liu** [comment]
I agree, I will open a PR to update it later.

**Comment by mengjiao-liu** [comment]
> Should we add this rule to the [zh guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/) page and mark this discussion issue as resolved?

PR https://github.com/kubernetes/website/pull/39556 has been opened, please review.

**Comment by mengjiao-liu** [comment]
PR #39556 has been merged, so we can close this issue.
/close
