### ISSUE TITLE
[ja] Some links to debug page are outdated

### ISSUE THREAD

**Issue by t-inu** [kubernetes/website#38797]
**This is a Feature Request**

**What would you like to be added**
PR #34162 changed the location of some .md files.
We need to update the links to those pages.

**Why is this needed**
Because the links are broken and the pages cannot be referenced.
Also, we can change some links to English page to Japanese page.

I checked "/docs/tasks/debug" by using grep command.
There are many links that need to be updated.
I would like to divide them into three cases, and create each PRs for easier to review.

- Only add "/ja"
  - e.g.: /docs/tasks/debug/debug-cluster/audit/ -> /ja/docs/tasks/debug/debug-cluster/audit/
- Change path
  - e.g.: /ja/docs/tasks/debug-application-cluster/audit/ -> /ja/docs/tasks/debug/debug-cluster/audit/
- Change path and add "/ja"
  - e.g.: /docs/tasks/debug-application-cluster/resource-usage-monitoring/ -> /ja/docs/tasks/debug/debug-cluster/resource-usage-monitoring/

**Comments**
/language ja
/assign

**Comment by t-inu** [comment]
/assign @shogohida 
I'm glad to see your positive action.
Please try to create one PR, first.

**Comment by shogohida** [comment]
Thanks for your comment! I will try to create a pull request as soon as possible as you said

**Comment by shogohida** [comment]
I created a first PR! 2 reviewers were already assigned but I share this here too just in case

https://github.com/kubernetes/website/pull/38884

**Comment by t-inu** [comment]
/reopen
Two cases still remain.

**Comment by t-inu** [comment]
/reopen
Only one case remains.

**Comment by t-inu** [comment]
@shogohida
Are you working on the last case?
There is no hurry, but I'd like to know if you plan to create a PR for it.

**Comment by shogohida** [comment]
@t-inu 
Oh, sorry for missing the last one :bow: I will try to create a PR as soon as possible (maybe tomorrow or this weekend)
