### ISSUE TITLE
Issue with k8s.io/docs/reference/using-api/deprecation-guide/

### ISSUE THREAD

**Issue by timfallmk** [kubernetes/website#38809]
`kubectl-convert` is still mentioned, but it takes digging through github issues to find _it was deprecated in 1.17_

**Comment by sftim** [comment]
- https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-convert-plugin
- https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-kubectl-convert-plugin
- https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-convert-plugin

all explain how to install `kubectl convert` support as a plugin.

**The API deprecation reference is misleading**.
> You can use the `kubectl-convert` command (`kubectl convert` prior to v1.20) to automatically convert an existing object:

It's _still_ `kubectl convert` but we should tell readers to make sure they've installed the plugin before they try to use it. We can edit the reference to add those 3 links and also https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#installing-kubectl-plugins

/language en
