### ISSUE TITLE
Blog Meta Links Opening in Same Tab

### ISSUE THREAD

**Issue by its07195** [kubernetes/website#38818]
**I have noticed that the blog meta links (e.g. the twitter link) on sidebar of blog pages are opening in the same tab, while on other sections of the website, they are opening in a new tab.**

**What I would like to be updated-**
I would like to change the target attribute of the links in the blog section to "_blank" to make them open in a new tab when clicked. 
This helps improve the user experience by keeping the user on the current page while still allowing them to access the linked content. 

**Impacted page** [https://kubernetes.io/blog/](https://kubernetes.io/blog/)

Thanks!

**Comment by tengqm** [comment]
I'm not sure opening each and every blog in a new tab or window is the right choice for everyone.

**Comment by its07195** [comment]
hi, it is only opening the sidebar links.
