### ISSUE TITLE
Documentation for `kubectl -k` (and Kustomize) refers to deprecated `bases` field

### ISSUE THREAD

**Issue by Shunpoco** [kubernetes/website#38815]
**This is a Feature Request**

**What would you like to be added**

Since [Kustomize v2.1.0](https://github.com/kubernetes-sigs/kustomize/blob/v2.1.0/docs/v_2.1.0.md#field-changes--deprecations), `bases` field is deprecated and we can use `resources` field instead.
In addition, since [Kubectl v1.21](https://github.com/kubernetes-sigs/kustomize#kubectl-integration), the version of Kustomize integrated in Kubectl is over v4.x.x.
However [our document](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) still uses `bases` field. We should update it.

**Why is this needed**
Users might use deprecated field if they read the doc

**Comment by sftim** [comment]
/retitle Documentation for `kubectl -k` (and Kustomize) refers to deprecated `bases` field
/sig cli
/language en
