### ISSUE TITLE
Document using node selector for dynamic resource allocation delayed claim resolution

### ISSUE THREAD

**Issue by pohly** [kubernetes/website#38841]
As discussed in https://github.com/kubernetes/kubernetes/issues/114005, setting `nodeName` when creating a pod which relies on delayed allocation of a claim will lead to the pod being stuck on the node because the allocation doesn't get triggered by the scheduler because it was by-passed.

Users who want to select a node manually for such a node should use a node selector with the node name. We need to document this.

**Comment by sftim** [comment]
/retitle Document using node selector for dynamic resource allocation delayed claim resolution
/language en
/sig node

However, as this is a documentation quality issue for an _alpha_ feature
/remove-priority important-soon
/priority backlog

We should fix that for beta for sure, and ideally sooner. I wouldn't want this to bump the work that SIG Docs has already assigned a high priority to.

**Comment by kannon92** [comment]
Hey @pohly 

I'm trying to learn more about DRA and I think this could be a good ticket for me to pick up.  

I wanted to ask if delayed allocation is covered in this repo (https://github.com/kubernetes-sigs/dra-example-driver)

If so I think I could take adding this documentation.

**Comment by pohly** [comment]
Yes, that repo is a good first start. It shows how to bring up a multi-node cluster in kind (relevant for this docs issue) and how to use DRA with it.

Regarding this issue here: there is https://github.com/kubernetes/kubernetes/pull/118209 pending for review which adds support for pods with `spec.nodeName` set. Not merged yet, but once it is, it should be included in a docs update.

**Comment by kannon92** [comment]
Sounds good!

/assign

I am working on a code KEP so it may be another week or two before I get to this.

**Comment by pohly** [comment]
@kannon92: I ended up writing about this as part of the required documentation update for Kubernetes 1.28, see https://github.com/kubernetes/website/pull/41856.
