### ISSUE TITLE
Add “feature gate” to glossary

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#38848]
**This is a Feature Request**

**What would you like to be added**
Let's explain what a feature gate is with an entry in our [glossary](https://kubernetes.io/docs/reference/glossary/).

**Why is this needed**
Lots of pages link to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ mainly by way of explaining what the term means. A glossary entry could really help.

**Comments**
/kind feature
/language en

**Comment by T-Lakshmi** [comment]
/assign
I can work on this feature once triage accepts.

**Comment by T-Lakshmi** [comment]
PR raised here #38895.
