### ISSUE TITLE
Pod OS spec description is not clear

### ISSUE THREAD

**Issue by javiermarasco** [kubernetes/website#38843]
While reading the documentation about the OS spec for [Pods](https://kubernetes.io/docs/concepts/workloads/pods/#pod-os) it states:

>Pod OS
FEATURE STATE: Kubernetes v1.25 [stable]
You should set the .spec.os.name field to either windows or linux to indicate the OS on which you want the pod to run. These two are the only operating systems supported for now by Kubernetes. In future, this list may be expanded.

>In Kubernetes v1.26, the value you set for this field has no effect on [scheduling](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/) of the pods. Setting the .spec.os.name helps to identify the pod OS authoratitively and is used for validation. The kubelet refuses to run a Pod where you have specified a Pod OS, if this isn't the same as the operating system for the node where that kubelet is running. The [Pod security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) also use this field to avoid enforcing policies that aren't relevant to that operating system.

The second paragraph mentions 1.26 doesn't take this field into consideration to schedule the pod but later in the same paragraph it states kubelet will take this field in consideration to schedule the pod (assigning the pod to a matching OS node). Am I reading it incorrectly or the paragraph should read "In Kubernetes v1.25, the vaule you set for this field has no effect on scheduling" ?

**Comment by sftim** [comment]
> In Kubernetes v1.26, the value you set for this field has no effect on [scheduling](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/) of the pods

is correct, but perhaps misleading.

How about changing the order round:
_Kubernetes v1.26 uses the value of `.spec.os.name` to validate Pods (the kubelet checks that the Pod OS matches the operating system that the kubelet is running on). If you create (or try to create a Pod) in a namespace that uses Pod security admission, the control plane also uses the value of `.spec.os.name` to work out what restrictions to verify and / or enforce._

_In Kubernetes v1.26, the value of  `.spec.os.name` does not affect how the [kube-scheduler](/docs/reference/command-line-tools-reference/kube-scheduler/) picks a Pod to run a node. In any cluster where there is more than one operating system for nodes, you should set the [`kubernetes.io/os`](/docs/reference/labels-annotations-taints/#kubernetes-io-os) label correctly on each nodes, and define Pods with a `nodeSelector` than matches the correct operating system.
If you set `.spec.os.name`  anddo not specify a `nodeSelector` based on the operating system label, the scheduler assigns your pod to a node based on other criteria and may or may not succeed in picking a suitable node placement where the node OS is right for the containers in that Pod._

?

---

We could link to a task page that explains how to assign Linux Pods to Linux nodes, and Windows Pods to Windows nodes (if we had such a task page).

**Comment by javiermarasco** [comment]
Hi @sftim by your message I understand that:

- Kubelet will fail to run a pod with a non matching `.spec.os.name` in the node that is running (as if a Linux pod is assigned to a Windows Node for example)
- Kube-Scheduler will not take into account `.spec.os.name` to define in which node to run a pod (unless a `kubernetes.io/os` label is specified) so it would potentially scheduling a Linux pod in a Windows node.

Am I getting it right? if so I believe your message is great to be a replacement of the one in the current documentation. 

Just there is a missing space in this paragraph (getting a bit picky sorry 😂 )
>If you set .spec.os.name `anddo` not specify a nodeSelector based on the operating system label, the scheduler assigns your pod to a node based on other criteria and may or may not succeed in picking a suitable node placement where the node OS is right for the containers in that Pod.

**Comment by tengqm** [comment]
This could warrant a PR since the fix is clear.
/help

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/40825

/retitle Pod OS spec description is not clear
