### ISSUE TITLE
Localization: Security Tutorial Order Inconsistency

### ISSUE THREAD

**Issue by YukiDayDreamer** [kubernetes/website#38850]
The order of security sections in Chinese: https://kubernetes.io/zh-cn/docs/tutorials/security/ and Korean: https://kubernetes.io/ko/docs/tutorials/security/, is different from the one in English: https://kubernetes.io/docs/tutorials/security/. Please check out the highlighted AppAmror section:

### Chinese
![Chinese](https://user-images.githubusercontent.com/10857425/211409146-40a8104e-af57-433b-89fb-ba3b8a52c540.png)

### Korean
![Korean](https://user-images.githubusercontent.com/10857425/211409469-85c02b37-df9f-447f-b26b-c65bacdb3b60.png)

### English
![English](https://user-images.githubusercontent.com/10857425/211409152-808d0c11-6287-4c75-bf7a-3193780cb4f1.png)

**Comment by a-mccarthy** [comment]
/assign

I've opened a PR to update this in the english docs. The page weights will need to also be updated in the localized docs. We've been working on updating the page weights to fix this problem as part of a different issue - https://github.com/kubernetes/website/issues/35093

**Comment by a-mccarthy** [comment]
/unassign

The page weights for the tutorial/security section have been updated in the english docs to be correctly ordered. To fix the ordering of these pages in localizations, the page weights will also need to be updated in the localized content.

**Comment by tengqm** [comment]
/close
This work is now left to the localization teams.
