### ISSUE TITLE
Accessing the Kubernetes API from a Pod

### ISSUE THREAD

**Issue by a1719928** [kubernetes/website#38854]
In this way, we can only access the Kubernetes API by the least privileged account. Most of APIs cannot be accessed, in Helm 3, tiller has been removed, so how to deal with this situation?

**Comment by sftim** [comment]
/kind support

It sounds like the documentation itself is clear enough on how to access Kubernetes. If you think there's a gap @a1719928, please let us know what pages you looked at or what search terms you tried, before you gave up having not found a clear answer.

**Comment by tengqm** [comment]
No response from the issue author for a long time. Closing this.
/close

Feel free to reopen with more details.
