### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/quality-service-pod/

### ISSUE THREAD

**Issue by elyasADK** [kubernetes/website#38875]
You did not state when and with what priority Kubernetes decides to kill pods. For example, Kubernetes prioritizes pods with BestEffort to kill.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/38588

**Comment by tengqm** [comment]
Looks like this information is now provided.
/close

Feel free to reopen if there are more work to do on this.
