### ISSUE TITLE
Improvements to docs/tasks/access-application-cluster/ingress-minikube

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/website#38876]
**This is an Enhancement Request**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

**What would you like to be added**

- Update image used in example to support arm64 users
- Change domain name in example because someone registered the existing one
- Add note for users using Docker Desktop that might miss the step in the command output

**Why is this needed**
- The image used in the example only supports amd64 users, so users on arm64 will not be able to get the example to work
  - Update with an image hosted and managed by the minikube team
  - From `gcr.io/google-samples/hello-app:1.0` to `kicbase/echo-server:1.0`
- The domain name used in the example `hello-world.info` was registered, so now if you follow the example the user gets a 302 when curling
  - Update to `hello-minikube.info` (unregistered)
- Users using Docker Desktop have to run the command `minikube tunnel` to get the ingress to work
  - This is communicated to the user via output when running `minikube addons enable ingress`
  - But users following the tutorial may not read the output, so suggest adding a note to the example to explicitly notify them of needing to run the command 

**Comments**

If I update the file `content/en/examples/service/networking/example-ingress.yaml` will that auto update https://k8s.io/examples/service/networking/example-ingress.yaml? As that URL is referenced in the example so it will need to be updated to change the domain name.

Existing PR https://github.com/kubernetes/website/pull/38742

**Comment by tengqm** [comment]
> If I update the file content/en/examples/service/networking/example-ingress.yaml will that auto update https://k8s.io/examples/service/networking/example-ingress.yaml? As that URL is referenced in the example so it will need to be updated to change the domain name.

Yes.

**Comment by sftim** [comment]
> Update to `hello-minikube.info`

I recommend using a domain that would _never_ be registered; for example: `hello-minikube.example`
