### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

### ISSUE THREAD

**Issue by s6341887** [kubernetes/website#38883]
How do I write spec.replicas to the environment variable?

Invalid value: "spec.replicas": error converting fieldPath: field label not supported: spec.replicas

**Comment by mengjiao-liu** [comment]
/kind support

Pod does not exist "spec.replicas" field. You can run the following command to see the fields of pod.spec.
```
kubectl explain pod.spec
```

Or refer to the following pages for all available fields.
https://kubernetes.io/zh-cn/docs/concepts/workloads/pods/downward-api/#downwardapi-fieldRef

**Comment by s6341887** [comment]
> 



> /kind support
> 
> Pod does not exist "spec.replicas" field. You can run the following command to see the fields of pod.spec.
> 
> ```
> kubectl explain pod.spec
> ```
> 
> Or refer to the following pages for all available fields. https://kubernetes.io/zh-cn/docs/concepts/workloads/pods/downward-api/#downwardapi-fieldRef


So, is there no way to write the number of replicas to an environment variable for the container to get?

**Comment by mengjiao-liu** [comment]
From the documentation, there's no way to get "spec.replicas" field.

Does anyone know more about this part？@tengqm @sftim

**Comment by tengqm** [comment]
The set of valid field references is pretty limited and it is not well documented.
Currently, the following fields are supported:

```
"metadata.annotations",
"metadata.labels",
"metadata.name",
"metadata.namespace",
"metadata.uid",
"spec.host",
"spec.nodeName",
"spec.restartPolicy",
"spec.serviceAccountName",
"spec.schedulerName",
"status.phase",
"status.hostIP",
"status.podIP",
"status.podIPs"
```

/close
