### ISSUE TITLE
Validate node setup page mentions Docker as a container runtime

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#38898]
**This is a Bug Report**

**Problem:** The page https://kubernetes.io/docs/setup/best-practices/node-conformance/#node-prerequisite lists Docker as a container runtime. Perhaps it can just say container execution engine or something like this. I also not sure if containerd or crio is needed to run tests like this. Likely yes.

**Page to Update:**
https://kubernetes.io/docs/setup/best-practices/node-conformance/#node-prerequisite

**Comment by AmarNathChary** [comment]
i am working on this issue.
/assign

**Comment by sftim** [comment]
I'd say “CRI-compatible container runtime, already configured for Kubernetes integration”

**Comment by niranjandarshann** [comment]
Raised PR #43011

**Comment by rishavkankane** [comment]
@sftim  I have done the needful change asked by you above, please have a look on it in the Raised PR https://github.com/kubernetes/website/pull/43011

**Comment by aj11anuj** [comment]
Issue is fixed
/close
