### ISSUE TITLE
Stale `kubectl describe` output in Connecting Applications with Services

### ISSUE THREAD

**Issue by dumlutimuralp** [kubernetes/website#38903]
Would be good to include the new fields in the `kubectl describe service` output such as `IP Family Policy`,` IP Families`, and `IPs`. These are related to dual stack deployments but since the same IPv4 address appear twice in a single stack output I think it is worth updating the sample outputs.

**Comment by sftim** [comment]
/retitle Stale `kubectl describe` output in Connecting Applications with Services

URL of tutorial is https://kubernetes.io/docs/tutorials/services/connect-applications-service/
(@dumlutimuralp it's definitely helpful if you include that detail)

/language en
/kind bug

**Comment by kundan2707** [comment]
@dumlutimuralp  I will update output with latest one 
```
controlplane ~ ➜  kubectl describe service kube-dns -n kube-system 
Name:              kube-dns
Namespace:         kube-system
Labels:            k8s-app=kube-dns
                   kubernetes.io/cluster-service=true
                   kubernetes.io/name=CoreDNS
Annotations:       prometheus.io/port: 9153
                   prometheus.io/scrape: true
Selector:          k8s-app=kube-dns
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.96.0.10
IPs:               10.96.0.10
Port:              dns  53/UDP
TargetPort:        53/UDP
Endpoints:         10.244.0.2:53,10.244.0.4
```
