### ISSUE TITLE
Kubelet Configuration (v1beta1)

### ISSUE THREAD

**Issue by shaked-develeap** [kubernetes/website#38905]
Link refers to a github 404 page:
[Node Allocatable](https://git.k8s.io/community/contributors/design-proposals/node/node-allocatable.md)

**Comment by utkarsh-singh1** [comment]
Thanks @shaked-develeap, related doc - https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#LoggingConfiguration

/assign
/kind doc

**Comment by tengqm** [comment]
The link
`[Node Allocatable](https://git.k8s.io/community/contributors/design-proposals/node/node-allocatable.md)`
 is hard-coded in the upstream source code (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L634).

The reference is generated from the source code, so the fix must be proposed in the upstream kubernetes/kubernetes repo. Refer to https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/ for guidance on how to contribute upstream.

**Comment by tengqm** [comment]
Cannot fix this downstream. Please propose a fix to the code (link provided in previous comment).
/close
