### ISSUE TITLE
Improvement for k8s.io/docs/concepts/scheduling-eviction/taint-and-toleration/

### ISSUE THREAD

**Issue by elyasADK** [kubernetes/website#38904]
There is no guide on the site to find the taints added to a node. To find the taints of a node, I use the command :
>  kubectl describe nodes | grep -i taint
or
> kubectl get nodes -o custom-columns=NAME:.metadata.name,TAINTS:.spec.taints --no-headers
I think it would be good if you announce these things on the site or create a special command to find the taints.

**Comment by sftim** [comment]
> _There is no guide on the site to find the taints added to a node._

See https://k8s.io/cheatsheet/#interacting-with-nodes-and-cluster

It's there:

> ```bash
> # View existing taints on which exist on current nodes.
> kubectl get nodes -o='custom-columns=NodeName:.metadata.name,TaintKey:.spec.taints[*].key,TaintValue:.spec.taints[*].value,TaintEffect:.spec.taints[*].effect'
> ```

If you'd like to suggest that https://k8s.io/docs/concepts/scheduling-eviction/taint-and-toleration/ could link there, we (Kubernetes SIG Docs) would consider the suggestion.

If you want a specific thing added to `kubectl`, you can suggest it: https://github.com/kubernetes/kubectl/issues/new/choose
