### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by bryanSME** [kubernetes/website#38910]
1/4 of my page is taken up by nothing on the right side of the terminal.  
(The area under "Edit this page", "Create child page", "Create an Issue", and "Print entire Section")

![image](https://user-images.githubusercontent.com/16226280/212185679-702c62ab-a43d-4d73-9fae-fe563408b88a.png)

**Comment by utkarsh-singh1** [comment]
Hi @bryanSME, That's how k8s website has been designed, you can zoom in from browser settings to get more close view of terminal and description.

/language en

**Comment by bryanSME** [comment]
> 

Zooming in far enough does eventually drop the blank area on the right side.  Things still seem squished, but it's not terrible.

![image](https://user-images.githubusercontent.com/16226280/212381671-9c7e27ed-758e-4aba-8747-c57998369fea.png)

**Comment by divya-mohan0209** [comment]
@bryanSME The tutorials are embedded content supported by Katacoda. The blank space on the side has been retained to be consistent with content on other pages. We're currently discussing the removal/replacement of Katacoda due to change in their free tiering in [this discussion]().

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
