### ISSUE TITLE
[pt-br] Update Hello, Minikube page content in Portuguese

### ISSUE THREAD

**Issue by stormqueen1990** [kubernetes/website#38919]
**This is a Feature Request**

**What would you like to be added**

Update the page Olá, Minikube (Brazilian Portuguese) to reflect the latest content in English. The Portuguese version of this page is a little bit outdated when compared to the English version.

Page address: https://kubernetes.io/pt-br/docs/tutorials/hello-minikube/
Content path in the repository: `content/pt-br/docs/tutorials/hello-minikube.md`

**Why is this needed**
To keep the content in Brazilian Portuguese in sync with the English version.

**Comments**

/help
/good-first-issue

**Comment by NitishKumar06** [comment]
/language pt-br

Kindly provide the link to the page as well.

**Comment by NitishKumar06** [comment]
language /pt-br

**Comment by stormqueen1990** [comment]
> Kindly provide the link to the page as well.

Hi there, @NitishKumar06! 👋 

Just added the page address and the content path to the issue description.

**Comment by ibilalkayy** [comment]
`Update the page Olá, Minikube (Brazilian Portuguese) to reflect the latest content in English. The Portuguese version of this page is a little bit outdated when compared to the English version.`

I didn't understand this point.

**Comment by NitishKumar06** [comment]
If you are familiar with the localization language used here, I don't think you should have a doubt about understanding it. However, if you don't, we recommend folks only pick up those issues of the language they're comfortable with and use it often.
