### ISSUE TITLE
Connecting Applications with Services

### ISSUE THREAD

**Issue by zogness** [kubernetes/website#38964]
I've been trying to follow this tutorial.
https://kubernetes.io/docs/tutorials/services/connect-applications-service/#securing-the-service

For us to be able to run:
make keys KEY=/tmp/nginx.key CERT=/tmp/nginx.crt
we need to at very least download the Makefile from https://github.com/kubernetes/examples/tree/master/staging/https-nginx/ but really we need to clone the https-nginx repo. But that doesn't work either. I guess https://github.com/kubernetes/examples/tree/master/staging/https-nginx/ is just a directory and not a repo.

**Comment by sftim** [comment]
There's certainly room to improve this tutorial. However, I don't think the docs are _wrong_ here.
