### ISSUE TITLE
Formatting problem for `glusterfs` volume details in Volumes concept

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#38968]
**This is a Bug Report**

**Problem:**
Under [Volumes](https://kubernetes.io/docs/concepts/storage/volumes/) concept page, content for [glusterfs](https://kubernetes.io/docs/concepts/storage/volumes/#glusterfs) volume type is missing. In [code](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/storage/volumes.md#glusterfs-removed-glusterfs) it is mentioned like:
![code](https://user-images.githubusercontent.com/50987400/212834769-fd83ea5e-2d32-4399-9c01-46349d89ff0c.png)

**Due to  this, content(`Kubernetes {{< skew currentVersion >}} does not include a glusterfs volume type.`) is missing from the page**:
![Screenshot2](https://user-images.githubusercontent.com/50987400/212835042-a2413ea4-724a-4623-a8b8-6f848d7371f2.png)

**Instead of that it should be like the below screenshot:**
![Screenshot1](https://user-images.githubusercontent.com/50987400/212835123-0e1eb9b5-328e-4a7a-8fea-054b7fe787c9.png)

**Proposed Solution:**
Above missing content Content for `glusterfs` should be there.
**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/

**Comment by Shubham82** [comment]
Fixed it here: #38969

**Comment by sftim** [comment]
/triage accepted
/retitle Formatting problem for `glusterfs` volume details in Volumes concept
/language en
