### ISSUE TITLE
Issue with k8s.io/fr/docs/tasks/access-application-cluster/

### ISSUE THREAD

**Issue by Naml21** [kubernetes/website#38974]

**Comment by Naml21** [comment]
Fatih Namlı durum akşemsettin mah sarıgüzel cd no 36 /A fatih istanbul

**Comment by Naml21** [comment]
Comment

**Comment by sftim** [comment]
/triage needs-information

What did you want to report, @Naml21 ? Please explain in English (as a project, we primarily work in English).

**Comment by tengqm** [comment]
No information provided. Seems a random wrong click.
/close
Feel free to reopen with details though.
