### ISSUE TITLE
Wrong term id mention for glossary term "workload" 

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#38985]
**This is a Bug Report**
**Problem:**
Glossary term id and title must be same as per the current design. But for Glossary `workload`, term id is documented wrongly as `workloads` whereas title and file name is `workload`.

**Proposed Solution:**
Update term id from **workloads** to `workload`.
**Page to Update:**
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/workload.md

**Comment by T-Lakshmi** [comment]
Hi @sftim,
ok, might be my understanding is wrong on it.
But i was verifying the existing Glossary items, most of them are documented term id and title are same.

Also if we use term id as `workloads` in PR, build is getting fail and giving error as invalid term id "workloads".
Test cases are accepting only if we mention term id as `workload`.

[here](https://github.com/kubernetes/website/pull/38213#issuecomment-1375341732) is the related error, Thanks.

**Comment by NitishKumar06** [comment]
> Also if we use term id as `workloads` in PR, build is getting fail and giving error as invalid term id "workloads". Test cases are accepting only if we mention term id as `workload`.
> 
> [here](https://github.com/kubernetes/website/pull/38213#issuecomment-1375341732) is the related error, Thanks.

Looks like a bug, isn't it?

**Comment by T-Lakshmi** [comment]
Hi @NitishKumar06,
Yes, but I'm not sure if the bug is in the documentation or in the test cases. First, we must determine the correct term id among these two (**workload**/**workloads**), and then only we can proceed.

**Comment by NitishKumar06** [comment]
> Hi @NitishKumar06, Yes, but I'm not sure if the bug is in the documentation or in the test cases. First, we must determine the correct term id among these two (**workload**/**workloads**), and then only we can proceed.

I've gone through the other files in the `/docs/reference/glossary` and noticed a pattern that **id** most often matches with the **title** itself. Hence for this, I believe **workload** should work fine. However, I'm not sure why a change in the id is leading to CI failure?

**Comment by tengqm** [comment]
The glossary shortcode does care about the `id` field? I don't think so.
That is the reason why referencing the `id` field rather than the file name sometimes failed.

**Comment by NitishKumar06** [comment]
@T-Lakshmi Any updates onto it?

**Comment by sftim** [comment]
> The glossary shortcode does care about the `id` field? I don't think so.

I looked up what `id` is for: it's the fragment identifier on the glossary page.

**Comment by tengqm** [comment]
> 

@sftim Read the f***king code. 

The following is from the `glossary_tooltip.html` shortcode.
`term_id` is the variable used in the shortcode, then it is used to generate the file name of the glossary.
The code never extract the `id` in the glossary entry, right?

```
{{- $id := .Get "term_id" -}}
{{- $text := .Get "text" -}}
{{- partial "docs/glossary-terms.html" $.Page -}}
{{- $glossary_items := $.Page.Scratch.Get "glossary_items" -}}
{{- if not $glossary_items -}}
{{- errorf "[%s] No glossary items found" site.Language.Lang -}}
{{- else -}}
{{- $term_info := $glossary_items.GetMatch (printf "%s.md" $id ) -}}
```

**Comment by T-Lakshmi** [comment]
```

{{- $id := .Get "term_id" -}}
-
-
-
{{- $term_info := $glossary_items.GetMatch (printf "%s.md" $id ) -}}

```

If we look at this, here it is trying to match **workloads.md** which doesn't exist. That's why the error is comming if i am not wrong. What do you suggest to be done?
@sftim  @tengqm  @nitishfy

**Comment by T-Lakshmi** [comment]
SIG Docs: Can you please have a look into this as its waiting since many days.

**Comment by tengqm** [comment]
Is there are fix proposal for this?
/triage accepted

**Comment by T-Lakshmi** [comment]
> Is there are fix proposal for this?

IMO we can change id to `workload` that will exactly match with existing filename which can fix the issue.
I will propose a PR if OK.

**Comment by T-Lakshmi** [comment]
> Is there are fix proposal for this?

PR raised #43217
