### ISSUE TITLE
Pod Topology Spread Constraints - Syntax error in graph

### ISSUE THREAD

**Issue by seano-vs** [kubernetes/website#38982]
![image](https://user-images.githubusercontent.com/64788907/213068555-79cb4085-e9b4-4ab8-a8f1-f76c64685c79.png)
This is coming up for a lot of the code examples on this page.

It's a bit difficult to submit a PR to fix myself, since I can't see which yaml files mermaid is trying to render

**Comment by divya-mohan0209** [comment]
@seano-vs : This is a known issue with mermaid and we're already tracking this under #31960

**Comment by divya-mohan0209** [comment]
Please continue the discussion on the linked issue since I'll be closing this one out. Thanks!
/triage duplicate
/close
