### ISSUE TITLE
Issue with /docs/concepts/ ... hard to navigate if you're starting from ignorance

### ISSUE THREAD

**Issue by mml** [kubernetes/website#3899]
The sub-headings don't document themselves.  For example, on this page, I go to Workloads.  Hopefully I know what that means, because hovering doesn't explain it, and click only opens that subtree, where I'm confronted with Pods and Controllers.  If I'm coming here because I don't know what words mean, I might not know those words either.

**Comment by tengqm** [comment]
@mml, is the https://kubernetes.io/docs/reference/glossary/ page helpful for you?
