### ISSUE TITLE
Deprecated API Migration Guide

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [kubernetes/website#38998]
v1.26

Flow control resources
The flowcontrol.apiserver.k8s.io/v1beta1 API version of FlowSchema and PriorityLevelConfiguration is no longer served as of v1.26.

* Migrate manifests and API clients to use the flowcontrol.apiserver.k8s.io/v1beta3 API version, available since v1.26.
* All existing persisted objects are accessible via the new API
* No notable changes

How can this happen, if the API to migrate to is only available in the version I am planning to update to. Looks like a typo to me
Possibly this is correct:

* Migrate manifests and API clients to use the flowcontrol.apiserver.k8s.io/v1beta2 API version, available since v1.xx. ???
*

**Comment by devarsh10** [comment]
I would like to work on this. But I need more understanding of migrating manifests.

Kind Regards,
Devarsh.
