### ISSUE TITLE
Kubernetes Issue Tracker

### ISSUE THREAD

**Issue by ankit-robin** [kubernetes/website#39007]
Version: v1.21.5
I had an HA cluster with 3 master nodes. I turned off one node, but the kubernetes cluster went down as it was not able to connect to etcd. On checking etcd got restarted on other nodes. It wasn't able to come up because earlier etcd wasnt releasing bind port. I had to kill the etcd process still holding the bind port.

**Comment by divya-mohan0209** [comment]
@ankit-robin Hello! Could you provide more details around what change you're proposing to https://kubernetes.io with this issue? As written right now, this sounds like a support issue rather than a change to the website.

**Comment by ankit-robin** [comment]
Sorry I opened it at wrong place. Not a UI issue.
