### ISSUE TITLE
Convert complex PNG in a Blog Post from PPT/PNG to SVG with High Quality

### ISSUE THREAD

**Issue by davidhadas** [kubernetes/website#39015]
**This is a Bug Report**

**Problem:**
The image files in  #38918 need to be converted to an SVG. Currently, they are PNG. 
The originals are PPT files that can be found at https://github.com/kubernetes/website/pull/38918#issuecomment-1381981797 

Earlier attempts to convert them to SVG resulted in poor-quality images. 

**Proposed Solution:**
If anyone has the tools and expertise to convert the PNG/PPT to high-quality SVG that will look the same as the PNGs, we welcome the help. 

**Page to Update:**
https://kubernetes.io/blog/2023/01/20/security-behavior-analysis/

**Comment by sftim** [comment]
/assign

If anyone gets to this first: great!

**Comment by thesakshidiggikar** [comment]
hey! looking to contribute to this project !..can I?

**Comment by sftim** [comment]
I've made progress on this and hope to send in a PR later this week.
