### ISSUE TITLE
[zh-cn] Amending "式" to the word "序" in k/website

### ISSUE THREAD

**Issue by JBossBC** [kubernetes/website#39035]
![Uploading image.png…]()

这里的: 但是当某个应用程式资源利用率不高时,应为:但是当某个应用程序资源利用率不高时

其中的式应该改为序

**Comment by utkarsh-singh1** [comment]
Hi @JBossBC, please provide details for your issue as current issue does not give any information.

/triage needs-information

**Comment by JBossBC** [comment]
![图片](https://user-images.githubusercontent.com/90125263/213902444-cac92a2f-f2d1-4468-969a-419043570c43.png)

In there,the word '式' should be changed to the word "序".it is more reasonable for this sentence situation

**Comment by divya-mohan0209** [comment]
/retitle [zh-cn] Amending "式" to the word "序" in k/website

**Comment by divya-mohan0209** [comment]
@JBossBC : Please could you add the link to this page so that contributors can pick it up and work on it?

**Comment by JBossBC** [comment]
https://kubernetes.io/zh-cn/docs/concepts/overview/
&nbsp;


小鑫?不忘初心
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月24日(星期二) 下午3:59
收件人: ***@***.***&gt;; 
抄送: "Xiyang ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kubernetes/website] [zh-cn] Amending &quot;式&quot; to the word &quot;序&quot; in k/website (Issue #39035)





 
@JBossBC : Please could you add the link to this page so that contributors can pick it up and work on it?

**Comment by JBossBC** [comment]
https://kubernetes.io/zh-cn/docs/concepts/overview/.

**Comment by mengjiao-liu** [comment]
PR https://github.com/kubernetes/website/pull/41710 has been merged, so this issue can be closed.
/close
