### ISSUE TITLE
Add the content of Cleanup section into the ```shell code block snippet.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#39064]
**This is a Feature Request**

**What would you like to be added**
Add the commands which are under the **Clean up** section of the [Apply Pod Security Standards at the Cluster Level](https://kubernetes.io/docs/tutorials/security/cluster-level-pss/) and [Apply Pod Security Standards at the Namespace Level](https://kubernetes.io/docs/tutorials/security/ns-level-pss/) tutorials into the **shell** code block snippet. Currently, it is under the **triple backticks** (```) as shown in the following screenshot:
![Screenshot_CL](https://user-images.githubusercontent.com/50987400/213978826-8a409191-beb7-49a9-beea-a7c519711a38.png)
![Screenshot_nsl](https://user-images.githubusercontent.com/50987400/213978832-b75683b3-67da-40f3-9b22-c415cd832366.png)

Which is not look more prominent.

**Why is this needed**
It provides a better structure to the `Clean up` section. and then it will be highlighted on the page.
**Comments**
None

**Comment by Shubham82** [comment]
Fixed it here: #39065

**Comment by sftim** [comment]
I'm not sure I agree with the issue description. I was nevertheless happy to merge the actual PR.

**Comment by Shubham82** [comment]
thank you, @sftim
