### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by giorgiberia** [kubernetes/website#39078]
embedded page did not load

**Comment by T-Lakshmi** [comment]
/language en
/kind support
/sig docs
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by T-Lakshmi** [comment]
Hello @giorgiberia,
Do you mean interactive session is not loading for you? If yes, I could able to load page and start the session without any issues. 
Please try again and make sure you have good network connectivity. 
![image](https://user-images.githubusercontent.com/56723673/214250062-958c5df9-d019-4991-83c4-939a82f4b672.png)
Thanks.

**Comment by giorgiberia** [comment]
I have tried several times. everything other loads pretty fast.

**Comment by giorgiberia** [comment]
![image](https://user-images.githubusercontent.com/6876423/214264284-4feae546-3a1a-4601-976f-c4e025b2e9ff.png)

**Comment by giorgiberia** [comment]
it was a dns issue

**Comment by T-Lakshmi** [comment]
so, If your issue resolves you can close the ticket.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
