### ISSUE TITLE
tlsCipherSuites in KubeletConfiguration does not mention TLS 1.3 case

### ISSUE THREAD

**Issue by 3u13r** [kubernetes/website#39083]
**This is a Bug Report**

**Problem:**
In the docs for the KubeletConfiguration the `tlsCipherSuites` field is described as:
> tlsCipherSuites is the list of allowed cipher suites for the server. 

Since Kubernetes supports TLS 1.3[1] and uses the default Go TLS implementation I think that the message is a bit misleading when talking about TLS 1.3. In TLS 1.3 the CipherSuites set in the TLS config are simply ignored[2] and the default ones are used. Therefore, even if a cipher suite is not allowed (i.e. missing from this list) it is possible that it is selected.

[1] https://github.com/kubernetes/kubernetes/pull/90843
[2] https://cs.opensource.google/go/go/+/master:src/crypto/tls/common.go;l=658-659

**Proposed Solution:**
Mention that this configuration is ignored for TLS 1.3 and refer to the tls Config comment.

**Page to Update:**
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

**Comment by sftim** [comment]
I think this is really a bug in Kubernetes itself - see https://github.com/kubernetes/kubernetes/blob/c865a641d3d7ed85723ef2f37f3756d52d8f5da3/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L151-L155

**Comment by 3u13r** [comment]
I initially tried to find it there, but I guess the GitHub search didn't index the file. Thanks for the pointer. 
In any case, I my idea was to (also) have it tracked here since it concerns the public documentation. If you think we should move this issue, please go ahead with closing this one. 

Since we I know the correct place, should I go head and create a PR?
