### ISSUE TITLE
Move CEL expression documentation from API documentation to website

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/website#39089]
**This is a Feature Request**

CEL expressions were originally documented for [CRD Validation Rules](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go#L179-L231).

When ValidationAdmissionPolicy was added, the [documentation was duplicated](https://github.com/kubernetes/kubernetes/blob/703361f381d4a1eaa7dc87ff3b7c12c84f3878a4/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go#L179-L231) to the new API.

We now multiple other enhancements (e.g. https://github.com/kubernetes/enhancements/pull/3717) where the documentation would need to be duplicated.

**What would you like to be added**

Instead of continuing to duplicate this documentation, resulting in documentation that will invariably drift and become inaccurate, let's instead introduce website documentation and link to it for all the documentation that is the same for all usages of CEL in Kubernetes.

Website documentation will contain:

- escaping rules
- Kubernetes specific type information (e.g. equality)
- Libraries available
- What data is accessible to CEL expressions (e.g. [metadata.name and generateName](https://github.com/kubernetes/enhancements/pull/3717#discussion_r1085298802)) 

API documentation of fields that contain CEL:

- What root variables are available in the specific context (e.g. "object" or "self") and what the variables provide access to
- What level of type safety is provided (full type checking, informational type checking, runtime only type checks?)

**Why is this needed**

Avoid API documentation inaccuracies and drift.

**Comments**

**Comment by jpbetz** [comment]
Need to also document https://github.com/kubernetes/enhancements/pull/3717/files#r1085742827

**Comment by sftim** [comment]
How about a Reference page titled “CEL in Kubernetes”?

**Comment by sftim** [comment]
If we'd like a short docs URL, eg https://k8s.io/cel-reference, that can be a thing (using a Netlify redirect with a temporarily moved status)

**Comment by sftim** [comment]
/retitle Move CEL expression documentation from API documentation to website

**Comment by jpbetz** [comment]
The reference page idea is great. Once we get past enhancement freeze I'll open a PR.

**Comment by sftim** [comment]
SIG API Machinery folks: what's your preferred priority for these docs?

**Comment by jpbetz** [comment]
I intend to complete this for 1.27.

**Comment by jpbetz** [comment]
Starting work on this now.
