### ISSUE TITLE
[pt-br] Sync cheatsheet.md in Brazilian Portuguese with the English version

### ISSUE THREAD

**Issue by MrErlison** [kubernetes/website#39093]
## This is a Feature Request

Update the translation of the cheatsheet.md partial to match the latest English version.

File path in repository: 
- content/pt-br/docs/reference/kubectl/cheatsheet.md

### Why is this needed

To synchronize the translated partial with the current English version.

### How to test

This is a partial included as a prerequisite section on top of the task pages. To verify this change, re-build the website (instructions here) and navigate to a task page in Brazilian Portuguese (for example, https://kubernetes.io/pt-br/docs/tasks/configmap-secret/managing-secret-using-kubectl/). The text at the top in the section "Antes de você começar" should contain the same instructions as the section in English.

### Creating a pull request

When creating a pull request for this issue, please name it: [pt-br] Update reference/kubectl/cheatsheet.md

In the comment section of the pull request, please add "fixes" followed by the number of this issue.

If you need help, please don't hesitate to ask us in Portuguese [slack](https://slack.k8s.io/) channel #kubernetes-docs-pt

Comments
/language pt
/good-first-issue
/help

---

Atualizar a tradução do parcial cheatsheet.md para refletir a versão atual da página em inglês. Isso é necessário para sincronizar a tradução com a última versão em inglês.

Caminho do arquivo no repositório: 
- content/pt-br/docs/reference/kubectl/cheatsheet.md

### Como testar

Este é um parcial incluído na forma de seção de pré-requisitos no topo das páginas de tarefas. Para verificar esta alteração, reconstrua o website (conforme instruções aqui) e navegue para uma página de tarefa em português brasileiro (por exemplo, https://kubernetes.io/pt-br/docs/tasks/configmap-secret/managing-secret-using-kubectl/). O texto no topo da página, na seção "Antes de você começar" deve ser equivalente em instruções à sua versão em inglês.

### Criando um pull request

Ao criar um pull request para esta issue, por favor coloque como título: [pt-br] Update reference/kubectl/cheatsheet.md

No comentário do seu pull request, por favor escreva "fixes" seguido do número desta issue.

Se você precisar de ajuda, não hesite em nos perguntar no canal do [slack](https://slack.k8s.io/) em português #kubernetes-docs-pt

**Comment by ashutosh887** [comment]
@akash-kumar-saw Did your PR get merged? I'm willing to contribute to the Org.

**Comment by MrErlison** [comment]
> @akash-kumar-saw Did your PR get merged? I'm willing to contribute to the Org.

@ashutosh887 Yes, this PR was merged and we forgot close this issue. Sorry about that.
