### ISSUE TITLE
Encrypting NFS Volumes Data at Rest

### ISSUE THREAD

**Issue by 87utierrez** [kubernetes/website#39090]
I looking to enable encryption at rest on my cluster with NFS as the provider. could you please assist?

**Comment by sftim** [comment]
/triage support

Hi @87utierrez 

**GitHub is not the right place for support requests.**

If you're looking for someone to help you learn how to configure your Kubernetes cluster, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by tengqm** [comment]
The encryption at rest option for k8s refers mainly to the cluster storage etcd.
NFS is a volume storage to be used by user applications. You'd better search for those support on volume encryption.
It is not within the scope of Kubernetes core.
/close
