### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/names/

### ISSUE THREAD

**Issue by riscie** [kubernetes/website#39112]
This documentation talks about different naming constraints for resources. It does not list, which resource type needs to follow which naming constraints. 

Does such a matrix exist? At the moment, I am trying to figure out the naming constraints for lease-names when using the Kubernetes leader election API. But a general overview of all resources would be very convenient.

**Comment by sftim** [comment]
There is no document that lists the the naming requirements for each Kubernetes API. Also, reference pages such as https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/lease-v1/ don't (yet) list the naming requirements. We do try to document these in the relevant concept pages. A PR against https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/lease-v1/ is welcome.

Should we add a page that lists each API and its naming constraints? It sounds useful; there's a cost, too, both for writing it the first time, and in terms of maintaining the document once we add it.

/kind feature
/language en

**Comment by tengqm** [comment]
According to the validation logic for Lease, the name of a Lease has to be a valid DNS subdomain name.

**Comment by sftim** [comment]
I don't think we have the resources to maintain that page. It'd be useful to add if more docs contributors turn up.
/remove-lifecycle rotten
/lifecycle frozen

/close not-planned
