### ISSUE TITLE
Wrong mention of Kubernetes Version on ConfigMap docs

### ISSUE THREAD

**Issue by NitishKumar06** [kubernetes/website#39111]
The following [page](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables) mentions about the Kubernetes Version-1.6.  Shouldn't it be V1.16?

_Note: This functionality is available in Kubernetes v1.6 and later._

**Comment by tengqm** [comment]
Looks like the note can be safely removed.

**Comment by sftim** [comment]
/language en

/remove-triage accepted


I don't think changing the version to 1.16 is the correct fix.

**Comment by NitishKumar06** [comment]
Instead of updating the version, we can remove such note as mentioned by @tengqm in the [comment](https://github.com/kubernetes/website/issues/39111#issuecomment-1405827093).
