### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by afolarin** [kubernetes/website#39113]
```
Download the Google Cloud public signing key:

sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
Add the Kubernetes apt repository:

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
```
I'm confused as I was under the impression these should go under the `/usr/share/keyrings`? 
```
/usr/share/keyrings/kubernetes-archive-keyring.gpg
```

**Comment by sftim** [comment]
/kind support

Try: https://www.google.com/search?q=debian+apt+keyring+path for advice @afolarin

**Comment by Ritikaa96** [comment]
Hi @afolarin ,This seems like a generak query, so it might be better to check [Server Fault](https://serverfault.com/questions/tagged/kubeadm) and ask your question there if a similar question has not yet been answered.

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
