### ISSUE TITLE
[ja] Update setup/production-environment/container-runtimes translation

### ISSUE THREAD

**Issue by FeLvi-zzz** [kubernetes/website#39125]
**This is a Feature Request**

**What would you like to be added**

Update https://kubernetes.io/docs/setup/production-environment/container-runtimes Japanese translation

**Why is this needed**

**Comments**

ref. https://github.com/kubernetes/website/pull/39085#discussion_r1089581460

/language ja

**Comment by grainrigi** [comment]
I want to work on this. Have you already started working on it?

It seems that some pages linked from here are not translated yet:

- dockershim-removal template
- [Dockershim Removal FAQ](https://kubernetes.io/blog/2022/02/17/dockershim-faq/)
- [Check whether Dockershim removal affects you](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-removal-affects-you/)

For now, I'm going to start working on dockershim related contents. 
Feel free to notify me if this conflicts with your work.

**Comment by grainrigi** [comment]
I'll assign myself since you haven't assigned youself to this issue.
Please tell me if this conflicts with you work.
/assign
