### ISSUE TITLE
Broken link on Install Tools page

### ISSUE THREAD

**Issue by kadtendulkar** [kubernetes/website#39134]
Problem:
The text [kind](https://kind.sigs.k8s.io/docs/) on [link](https://kubernetes.io/docs/tasks/tools/#kind) is not working, it should point to this https://kind.sigs.k8s.io/
Check the page [Install Tools](https://kubernetes.io/docs/tasks/tools/)
for the problem.

Page to Update:
https://kubernetes.io/docs/tasks/tools/

Suggested Solution:
It should resolve this issue by adding a simple link and enhancing the document line.
Update the text king link to https://kind.sigs.k8s.io/docs/ and not to this [link](https://kubernetes.io/docs/tasks/tools/#kind).

/kind document
/assign
/language en

**Comment by kadtendulkar** [comment]
Hello @reylejano , the [link](https://kind.sigs.k8s.io/docs/) doesnt direct to any page, I have checked the official king page, I believe adding [home page](https://kind.sigs.k8s.io/) would be appropriate. Please suggest if any changes, Thanks.

**Comment by tengqm** [comment]
/triage accepted
Mind propose a fix? @kadtendulkar
