### ISSUE TITLE
Translate Chinese version for blog：2022-12-26-pod-scheduling-readiness.md

### ISSUE THREAD

**Issue by zhangxyjlu** [kubernetes/website#39156]
**This is a Feature Request**

This page https://kubernetes.io/blog/2022/12/26/pod-scheduling-readiness-alpha/ has no Chinese version

**What would you like to be added**

Translate Chinese version for blog：2022-12-26-pod-scheduling-readiness.md

Comments
/language zh
/assign

**Comment by tengqm** [comment]
@zhangxyjlu Please consider add your name (id) as the translator as we are now requesting for blog translations.
