### ISSUE TITLE
[ZH-CN]"你好，Minikube" of tutorials can't trigger "Launch Terminal" successfully

### ISSUE THREAD

**Issue by Jun10ng** [kubernetes/website#39181]
https://kubernetes.io/zh-cn/docs/tutorials/hello-minikube/

![image](https://user-images.githubusercontent.com/46768176/215689349-de427285-a880-4b95-a4da-627aec5230d3.png)

**Comment by jihoon-seo** [comment]
/label team/katacoda

This is not reproducible for me.
/triage not-reproducible

![image](https://user-images.githubusercontent.com/46767780/215695974-e5ae8b88-0564-44a8-843e-bab7df00aafe.png)

**Comment by Jun10ng** [comment]
Thank you for the reply. I reproduce it again. Is there any information I can provide?
PS: I open another tutorial katacoda terminal in the other chrome tab.

**Comment by sftim** [comment]
We're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/). As such, we don't plan to fix this bug.

/triage unresolved

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
