### ISSUE TITLE
Hello Minikube

### ISSUE THREAD

**Issue by Jun10ng** [kubernetes/website#39183]
At [the selection of create a deployment](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-deployment), user's terminal will be block on `$ minikube dashboard`.  Then users can't run the next command.

I think it's better to **remind users to open a new terminal.**

**Comment by Jun10ng** [comment]
https://kubernetes.io/docs/tutorials/hello-minikube/#enable-addons

`kubectl get pod,svc -n kube-system` 

the namespace of tutorials should be `default` ?

**Comment by utkarsh-singh1** [comment]
Related Doc -  https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-deployment

/language en

**Comment by utkarsh-singh1** [comment]
Hi @Jun10ng, Thanks for raising this issue, we can introduce an instruction [here](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-deployment),
> Katacoda environment only: At the top of the terminal pane, click the plus sign, and then click Select open a new terminal.

like it has been mentioned before [here](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-minikube-cluster)
> Katacoda environment only: At the top of the terminal pane, click the plus sign, and then click Select port to view on Host 1.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
