### ISSUE TITLE
Query about release dates

### ISSUE THREAD

**Issue by IgorTheOverlord** [kubernetes/website#39207]
![image](https://user-images.githubusercontent.com/102486458/216069160-1f009501-1578-47fb-ac8e-88dc362c5b04.png)

**Comment by IgorTheOverlord** [comment]
https://kubernetes.io/releases/

**Comment by sftim** [comment]
/triage not-reproducible

All those **patch** releases were, as documented, released on the 18th of January. Have a look at https://github.com/kubernetes/kubernetes/releases if you don't believe me.

**Comment by sftim** [comment]
We could document the date of each minor release as well (that would be a feature request). People often want to know when a minor release was made, more than they want to know when a particular patch release happened.
