### ISSUE TITLE
Update docs once client-side validation is removed from kubectl

### ISSUE THREAD

**Issue by kevindelgado** [kubernetes/website#39210]
Server Side Field Validation is on by default starting in Kubernetes 1.25, but still disableable behind a feature-gate in kubernetes 1.25 and 1.26. 

When a kubectl of version 1.25+ connects to an API server of 1.26- that has ServerSideFieldValidation disabled, it will fall back on client-side validation.

Once kubectl no longer supports connecting to APIServers 1.26- it will no longer fall back on client-side validation, and client-side validation can be removed entirely from kubectl. Once this occurs, we must update [the documentation](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/using-api/api-concepts.md#setting-the-field-validation-level) to remove the notice that kubectl will fall back to client-side validation

**Comment by Shubham82** [comment]
closing this issue, as it was resolved by PR #39715
/close
