### ISSUE TITLE
Kubectl docs should mention field validation

### ISSUE THREAD

**Issue by kevindelgado** [kubernetes/website#39211]
The [reference documentation](https://kubernetes.io/docs/reference/kubectl/) on kubectl currently does not mention anything about field validation `kubectl --validate`.

Specifically, kubectl prior to 1.25 used to detect unknown and duplicate fields via client-side validation built into kubectl. 

Since 1.25 kubectl uses [server-side validation](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/using-api/api-concepts.md#setting-the-field-validation-level) to detect unknown and duplicate fields and kubectl users have the option to customize the behavior of the server via `kubectl --validate`

**Comment by FavourDaniel** [comment]
Can I get assigned to this? @sftim

**Comment by vaibhav2107** [comment]
I think this issue is resolved by #39716 and hence can be closed now
