### ISSUE TITLE
Issue with /docs/getting-started-guides/kops/

### ISSUE THREAD

**Issue by scribnar** [kubernetes/website#3921]
**This is a...** 
- [ Bug Report] 

**Problem:**
kops gives below error. The document does not mention creation of any keypair
error reading SSH key file "/Users/username/.ssh/id_rsa.pub": open /Users/username/.ssh/id_rsa.pub: no such file or directory

**Proposed Solution:**
Please update the document with any key pairs that has to be created and how to do that

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/kops/

**Comment by zacharysarah** [comment]
@scribnar :wave: I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).

**Comment by zacharysarah** [comment]
@scribnar Were you able to find a workaround?

**Comment by scfox** [comment]
I hit this same issue. It looks like a step to create the SSH key file is missing.

**Comment by scfox** [comment]
This was my workaround if any others hit this: 
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/
