### ISSUE TITLE
Feedback on “Pod Topology Spread Constraints” concept

### ISSUE THREAD

**Issue by SlavaUtesinov** [kubernetes/website#39218]
Pay attention to an extract from [Implicit conventions](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#implicit-conventions):

> 1. any Pods located on those bypassed nodes do not impact maxSkew calculation - in the above example, suppose the node node1 does not have a label "zone", then the 2 Pods will be disregarded, hence the incoming Pod will be scheduled into zone A.

"in the above example" phrase is supposed to point to [example: conflicting topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-conflicting-topologyspreadconstraints) (by meaning), presently it is formulated like it points to not appropriate previous **closest** example - [example: topology spread constraints with node affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-topologyspreadconstraints-with-nodeaffinity) what leads to misunderstanding

**Comment by sftim** [comment]
/retitle Feedback on “Pod Topology Spread Constraints” concept

**Comment by sftim** [comment]
Thanks for the comment @SlavaUtesinov 

/language en
/kind bug
/priority backlog

**Comment by vaibhav2107** [comment]
Fixed this issue by PR #43702
