### ISSUE TITLE
[hi] Update KubeCon dates for 2023

### ISSUE THREAD

**Issue by Babapool** [kubernetes/website#39225]
**This is a Feature Request**

**What would you like to be added**

Update the `hi/_index.html` page to reflect the latest KubeCon dates for 2023. The KubeCon dates for 2023 are outdated on this page as compared to the English version.

Page Address: https://kubernetes.io/hi/
File path in repository: `content/hi/_index.html`

**Why is this needed**
To keep the dates in Hindi sync with the ones in the English version.
**Comments**

Go to the file path in the repository and do the following changes:
 - On line 46
```diff
- <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna21" button id="desktopKCButton">अक्टूबर 11-15, 2021 को KubeCon North America में भाग लें</a>
+ <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/" button id="desktopKCButton">अप्रैल 18-21, 2023 KubeCon + CloudNativeCon Europe में भाग लें</a>
```
- On line 51:
```diff
- <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-europe-2022/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccnceu22" button id="desktopKCButton">मई 17-20, 2022 को KubeCon Europe में भाग लें</a>
+ <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/" button id="desktopKCButton">6-9 नवंबर, 2023 को KubeCon + CloudNativeCon North America में भाग लें</a>
```
/language hi
/good-first-issue
/help

**Comment by Manda-supraja26** [comment]
#39227

**Comment by anand-harsh** [comment]
Hey @Babapool 
May I know whether this issue still needs to be fixed and is open?

**Comment by NitishKumar06** [comment]
> Hey @Babapool May I know whether this issue still needs to be fixed and is open?

A [valid PR](https://github.com/kubernetes/website/pull/39226) for this issue has been raised already.

**Comment by debdeepsanyal** [comment]
@Babapool hi for some reason i cant find an html index file in the path content/hi . there are _index files in the common resources and the docs files but they dont have much to edit. I would be really grateful if you could kindly help me out.

**Comment by NitishKumar06** [comment]
@xerpa43 @freddie400 PTAL at [this](https://github.com/kubernetes/website/issues/39225?notification_referrer_id=NT_kwDOBSEJLrM1NDk0MzA3OTk3Ojg2MDUxMTE4#issuecomment-1419082200)

**Comment by SagarSharma2809** [comment]
hi, is this issue assigned to anyone currently? I volunteer to fix this

**Comment by Aayush987** [comment]
> hi, is this issue assigned to anyone currently? I volunteer to fix this 

Hi Sagar, i have already made pr for this issue.

**Comment by xerpa43** [comment]
@NitishKumar06  sorry for the mess, Contributing for the first time. I was wondering why isn't this issue closed.

**Comment by NitishKumar06** [comment]
@xerpa43 Thanks for showing interest! You can browse through other issues and start working on one you find of your type.
