### ISSUE TITLE
Improvement for k8s.io/docs/concepts/architecture/

### ISSUE THREAD

**Issue by nburns** [kubernetes/website#39234]
A diagram would be really helpful on this page

![Screen Shot 2023-02-02 at 9 56 02 AM](https://user-images.githubusercontent.com/1725338/216403972-f60dc241-30ac-4ef3-b213-39b879d0d585.png)

**Comment by devarsh10** [comment]
Hey @nburns, I would like to create and provide a k8s Architecture to this page.

Regards.

**Comment by utkarsh-singh1** [comment]
Hi @nburns, Instead of diagram, a sentence will be helpful as it's just an introductory page of cluster architecture which guide users to other important topics under cluster architecture.

/language en

**Comment by sftim** [comment]
> Hi @nburns, Instead of diagram, a sentence will be helpful as it's just an introductory page of cluster architecture which guide users to other important topics under cluster architecture.

I'd _really_ like to see a diagram on the https://k8s.io/docs/concepts/architecture/ page - see https://github.com/kubernetes/website/issues/29049 and the comments on that issue.

**Comment by utkarsh-singh1** [comment]
![cluster-architecture  MConverter eu](https://user-images.githubusercontent.com/96516301/217003648-55443f2b-1ebe-44ec-b0c6-2828a70499f7.jpg)

Hi @sftim, I have created a mock-up of k8s cluster diagram, any suggestions from you that what can be improved.

**Comment by sftim** [comment]
Please use Kubernetes colors (principally the blue) to help emphasize - see https://www.k8s.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/ for tips

---

The component names should use the correct capitalization. For example, “kubelet” and “kube-api-server”.

---

> worker plane

This isn't a thing. I wouldn't put a group around the nodes.

---

I'm worried that someone looking at the diagram would imagine that each Node runs exactly one Pod. We need to find a way to suggest that several Pods can run on one node.

**Comment by utkarsh-singh1** [comment]
Hi @sftim, please take a look at these two as icons are from k8s community -

1.  
![cluster-architecture-Page-1 drawio](https://user-images.githubusercontent.com/96516301/217565481-d3052c06-20ff-4b43-a5f7-e62ed82db1f0.png)


2. 
![cluster-architecture-Page-2 drawio](https://user-images.githubusercontent.com/96516301/217565524-0e1ddebe-abab-4f34-bbf3-27d98ede9ceb.png)

**Comment by sftim** [comment]
The style for Diagram 2 is the one I recommend. The control plane box doesn't need a CRI in the corner though - I don't think that particularly helps explain things.

You could use the icons to badge the blue boxes if you want to.

---

Consider showing a different number of Pods between the 2 nodes. Eg, node 2 might only have one Pod.

**Comment by sftim** [comment]
Also, `kube-proxy` and cloud-controller-manager are optional (but commonly used); consider how you might want to represent that.

**Comment by utkarsh-singh1** [comment]
We can mention the connection with the kube-api-server of `kube-proxy `and `cloud-controller-manager` by dots and other components by a continuous line.

**Comment by utkarsh-singh1** [comment]
> Also, `kube-proxy` and cloud-controller-manager are optional (but commonly used); consider how you might want to represent that.

Mentioned kube-proxy and cloud-control-manager with light colours and connection from them are dotted lines,

![k8s-architecture](https://user-images.githubusercontent.com/96516301/223078489-0d908af0-4ad4-4624-a3d1-afcaf96f98ac.png)

**Comment by sftim** [comment]
Great! Let's have a pull request for that!

**Comment by utkarsh-singh1** [comment]
Hi @sftim,
1.  Where would it be good to place this diagram on doc - https://kubernetes.io/docs/concepts/architecture/? 
2.  Dimension of the image? As I inspected - https://kubernetes.io/docs/concepts/overview/components/ there is no description of that?

**Comment by sftim** [comment]
For now, propose a PR that uses (a version of) that image in https://kubernetes.io/docs/concepts/overview/components/

Use [Scalable Vector Graphics](https://www.w3.org/Graphics/SVG/) format. You can set an inherent physical size of say 160mm width, or leave the image unscaled. Either is fine.

**Comment by vaibhav2107** [comment]
The issue is resolved by #42272 and hence we can close this
