### ISSUE TITLE
is privileged really required for device plugins?

### ISSUE THREAD

**Issue by paleozogt** [kubernetes/website#39255]
On the [device plugins page](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-deployment), it says

> The canonical directory /var/lib/kubelet/device-plugins requires privileged access, so a device plugin must run in a privileged security context.

However, there are several implementations of the device plugin that aren't doing this, such as [smarter-device-manager](https://gitlab.com/arm-research/smarter/smarter-device-manager/-/blob/master/smarter-device-manager-ds-with-configmap-rpi.yaml#L39) and [Nvidia's k8s device plugin](https://github.com/NVIDIA/k8s-device-plugin/blob/main/nvidia-device-plugin.yml#L46).

How are these plugins working?  Is privileged not really required?

**Comment by sftim** [comment]
The docs are potentially misleading; they are talking about the security context of the Pod generally and not the `securityContext` field specifically.

We could try to reword to avoid confusion. It will be a bit tricky to come up with a good phrasing.

/language en

**Comment by tengqm** [comment]
Some GPU experts may help answer this question and/or provide insights on how things actually work.
We did come across this question too when evaluating the impacts on GPU resources when running Pods in rootless mode. In the case of Nvidia device plugin, they require a special container runtime, that could be an indicator.

**Comment by paleozogt** [comment]
@sftim I suspect others have had this same misunderstanding as me.  For example [generic-device-plugin](https://github.com/squat/generic-device-plugin/blob/main/manifests/generic-device-plugin.yaml#L59) and [kubevirt's device plugins](https://github.com/kubevirt/kubernetes-device-plugins/blob/master/manifests/kvm-ds.yml#L20) are all running (unnecessarily?) as `privileged`.

@tengqm I think the issue is whether the device plugin needs `privileged` in order to use the socket in `/var/lib/kubelet/device-plugins`.  Usually it doesn't need special security in order to look around in `/dev/` to determine which devices are available, tho the details may differ depending on the specific device (such as nvidia).

**Comment by tengqm** [comment]
/triage accepted
Sound that something we need to clarify on docs.
