### ISSUE TITLE
Jobs need to be wait for some seconds

### ISSUE THREAD

**Issue by biswa123642** [kubernetes/website#39273]
Hi,

I have a job yaml file structure which need to be wait until the job not finished. How can I set up a yaml file structure to set up a job in my Kubernetes cluster??

Request you to please help me on this.

Thanks,
Biswajit

**Comment by tengqm** [comment]
/close
This is not a proper place for technical support. Please use stackoverflow, ask-kubernetes, or some related Kubernetes slack channels for this.
Closing because this is not an issue related to documentation/website.
