### ISSUE TITLE
Interactive Tutorial - Exploring Your App

### ISSUE THREAD

**Issue by mkhaledi** [kubernetes/website#39327]
In module 3 interactive terminal does not create any pod. 
kubectl get pods returns : No resources found in default namespace.
kubectl describe pods returns : No resources found in default namespace.

**Comment by tamilselvan1102** [comment]
it is working as expected.
![image](https://user-images.githubusercontent.com/20103020/217430123-b6010598-1339-4482-8f9c-2a5a9a422c35.png)

**Comment by mkhaledi** [comment]
Hello, Unfortunatly I still get the same problem.  MVH / Best regardsTel: +46 (0) 723 41 99 77 From: TamilselvanSent: den 8 februari 2023 05:01To: kubernetes/websiteCc: mkhaledi; AuthorSubject: Re: [kubernetes/website] Interactive Tutorial - Exploring Your App (Issue #39327) it is working as expected.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by tamilselvan1102** [comment]
The same issue is also mentioned here - https://github.com/kubernetes/website/issues/38323

/triage duplicate

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
