### ISSUE TITLE
Ingress

### ISSUE THREAD

**Issue by gopi26** [kubernetes/website#39322]
Please provide example for NetworkingV1Api in nodejs

**Comment by tamilselvan1102** [comment]
/kind support

GitHub is not the right place for support requests @gopi26 

If you are looking for help about using Kubernetes, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and ask your question there if a similar question has not yet been answered.

**Comment by sftim** [comment]
You could look at https://github.com/kubernetes-client/javascript/tree/master/examples @gopi26 

(Wondering how to find that? I used Google, but you could also have visited https://kubernetes.io/docs/reference/)

**Comment by sftim** [comment]
/close
/triage not-reproducible

Kubernetes provides a JavaScript example for accessing the Ingress API, and the docs link to that library.
