### ISSUE TITLE
Explain how to troubleshoot `br_netfilter` missing from `kubeadm init` preflight check

### ISSUE THREAD

**Issue by natereid72** [kubernetes/website#39321]
Apologies if this issue is open, thought I saw something earlier that I was going to add comment to, but don't see it now.

## Versions

**kubeadm version** (use `kubeadm version`): Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:56:50Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
**Environment**: 
- **Kubernetes version** (use `kubectl version`): v1.26.1
- **Cloud provider or hardware configuration**: On-prem, esxi 7.0u3
- **OS** (e.g. from /etc/os-release): Ubuntu 22.04
- **Kernel** (e.g. `uname -a`): Linux 5.15.0-58-generic 64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- **Container runtime (CRI)** (e.g. containerd, cri-o): cri-o
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): n/a
- **Others**:

## What happened?

Followed directions to install cri-o and kubeadm from official docs. Executed `kubeadm init` and received preflight check error that _br_netfilter_ was missing.

## What you expected to happen?

`kubeadm init` preflight checks to pass.

## How to reproduce it (as minimally and precisely as possible)?

I would think that installing Ubuntu 22.04, then following docs to install cri-o and kubeadm would reproduce.

## Anything else we need to know?

I think the docs need to have steps added to include requirement for _br_netfilter_ to be added to /etc/modules or some other boot config file.

**Comment by sftim** [comment]
> Happy to close this one.

/close
