### ISSUE TITLE
[Umbrella docs issue] Remove or mark all references to k8s.gcr.io

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#39353]
**Problem:**

We've replaced `k8s.gcr.io` with a new container registry, `registry.k8s.io`

**Proposed Solution:**
- For English docs, find any mentions of `k8s.gcr.io` (other then explanations that this is the old thing) and replace them with `registry.k8s.io`
- for each downstream localization, find any mentions of `k8s.gcr.io`  update to be level with the English version of pages
- for old blog articles, either add a comment after mentions of k8s.gcr.io, or update to registry.k8s.io if the context makes the update appropriate

/priority backlog

because we've already done most of this work, and only a few pages remain.

**Comment by sftim** [comment]
/remove-language en
/retitle [Umbrella docs issue] Remove or mark all references to k8s.gcr.io

**Comment by sftim** [comment]
/triage accepted

This issue covers multiple packages of work

**Comment by asa3311** [comment]
I try to work some files for it. please review #39832

**Comment by xmudrii** [comment]
I did a final run through this issue and created #40585, #40586, #40588, and #40589.

Additionally, the following autogenerated documents are using k8s.gcr.io:

- https://github.com/kubernetes/website/blob/76baffc20228bab98766fe9cd4ea9f644e5ef8a1/static/docs/reference/generated/kubernetes-api/v1.19/index.html
- https://github.com/kubernetes/website/blob/76baffc20228bab98766fe9cd4ea9f644e5ef8a1/static/docs/reference/generated/kubernetes-api/v1.20/index.html
- https://github.com/kubernetes/website/blob/76baffc20228bab98766fe9cd4ea9f644e5ef8a1/static/docs/reference/generated/kubernetes-api/v1.21/index.html
- https://github.com/kubernetes/website/blob/76baffc20228bab98766fe9cd4ea9f644e5ef8a1/static/docs/reference/generated/kubernetes-api/v1.22/index.html
- https://github.com/kubernetes/website/blob/76baffc20228bab98766fe9cd4ea9f644e5ef8a1/static/docs/reference/generated/kubernetes-api/v1.23/index.html
- https://github.com/kubernetes/website/blob/76baffc20228bab98766fe9cd4ea9f644e5ef8a1/static/docs/reference/generated/kubernetes-api/v1.24/index.html

I'm not sure if we need to take any action for those or not.

**Comment by sftim** [comment]
I thinks this is done.
/close
