### ISSUE TITLE
DaemonSet Pods scheduling doc is a bit stale

### ISSUE THREAD

**Issue by gregth** [kubernetes/website#39358]
**This is a Bug Report**

**Problem:**
The "How Daemon Pods are scheduled" section at https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled is a bit stale and difficult to understand. The section in its current form seems to be the result of many additions and removals while the `ScheduleDaemonSetPods` feature went through its various release states.

There are various problems:
- An unsolicited reference to a `ScheduleDaemonSetPods` feature. To my concern, this feature is GA, and enabled by default.
- It is mentioned that: "... DaemonSet pods are created and scheduled by the DaemonSet controller instead...", then some problems of this approach are listed, and suddenly, the `ScheduleDaemonSetPods` bumps into the conversation. My general impression after reading this part was that, on the latest K8s, the DS controller schedules the Pod, but I can somehow configure it to be scheduled by the default scheduler. Very confusing. 

By looking through the code I realize that as of K8s 1.17 (when the  `ScheduleDaemonSetPods` became stable), all DaemonSet Pods are modified with a node affinity and the default scheduler schedules them. In no case does the DS controller set the `spec.nodeName`. Does this hold?

**Proposed Solution:**
I propose that:
1. We go through the "How Daemon Pods are scheduled" section & uncover the meaning of every single sentence
2. Settle on the technical details wrt DaemonSet and what the state is now
3. Rewrite it making clear what the current state is. 

I can contribute if you agree that this restructure is needed. 

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled

**Comment by sftim** [comment]
I think this duplicates a much older issue @gregth 

You are welcome to work on the DaemonSet docs; the older issue is already triaged as accepted. Feel free to [contribute](https://kubernetes.io/docs/contribute/)!

Some of these details about scheduling might belong within https://kubernetes.io/docs/concepts/scheduling-eviction/ - have a think about this (I haven't looked recently, so maybe there is nothing to move). You can move content and replace the original with a link to its new home.

/remove-kind bug
/triage duplicate
/language en

**Comment by sftim** [comment]
If DaemonSets Pods don't have special scheduling, maybe a section about how DaemonSets are scheduled is no longer needed.

**Comment by gregth** [comment]
@sftim that makes sence. 

But since this section existed for a long time, and users may still look for it or reference it, we may gently shrink it to a few lines, stating the absolutely necessary information: the DS controller creates the Pod with affinity that matches the node where the Pod shall run, then scheduler takes over and assigns the Pod to the node, if other conditions permit, etc.

**Comment by sftim** [comment]
Sure, that works.

**Comment by gregth** [comment]
@sftim Per our discussion, I sent a PR: https://github.com/kubernetes/website/pull/39392
