### ISSUE TITLE
交互式教程 - 部署应用

### ISSUE THREAD

**Issue by yangduozheng** [kubernetes/website#39379]
after start: sorry, invalid request was made.

**Comment by utkarsh-singh1** [comment]
/language zh

Hi @yangduozheng, Can you reload the page again as it can be a slow connection error.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
