### ISSUE TITLE
Easier declarative syntax for content tabs

### ISSUE THREAD

**Issue by techtonik** [kubernetes/website#3938]
**This is a...** 
- [x] Feature Request

from https://github.com/kubernetes/kubernetes.github.io/pull/3859#issuecomment-303212414

**Problem:**
Current syntax for [tabs](https://kubernetes.io/docs/tabs-example/) is repetitive procedural magic:

    {% capture default_tab %}
    Select one of the tabs.
    {% endcapture %}

    {% capture calico %}
    ```shell
    kubectl apply -f "http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm/calico.yaml"
    ```
    {% endcapture %}

    {% capture flannel %}
    ```shell
    kubectl apply -f "https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true"
    ```
    {% endcapture %}

    {% assign tab_names = 'Default,Calico,Flannel' | split: ',' | compact %}
    {% assign tab_contents = site.emptyArray | push: default_tab | push: calico | push: flannel %}

    {% include tabs.md %}
**Proposed Solution:**

Declarative literal block that can be embedded in Markdown:

    tabs default="Calico":
      tab="Calico":
        """shell
        kubectl apply -f "http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/kubeadm/calico.yaml"
        """
      tab="Flannel":
         """shell
        kubectl apply -f "https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true"
        """

**Page to Update:**
https://kubernetes.io/docs/tabs-example/

**Comment by techtonik** [comment]
@chenopis this probably could be done using Mungers https://github.com/kubernetes/community/blob/master/contributors/devel/how-to-doc.md#what-are-mungers

**Comment by chenopis** [comment]
@techtonik Ah, ok cool. I'm going to be swamped until 1.7 is our later this month, but if you have some spare cycles feel free to create a munger for this and open a PR. We can test it out in the Netlify preview.

**Comment by tengqm** [comment]
@chenopis ping.

**Comment by techtonik** [comment]
Looks like mungers doc is gone and I am not sure not how to implement this helper.
