### ISSUE TITLE
[en] Remove or mark all references to k8s.gcr.io - English localization

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#39427]
- For English docs, find any mentions of `k8s.gcr.io` (other then explanations that this is the old thing) and replace them with `registry.k8s.io`

- for old blog articles, either add a comment after mentions of `k8s.gcr.io`, or update to `registry.k8s.io` if the context makes the update appropriate

This issue is under umbrella docs issues of https://github.com/kubernetes/website/issues/39353

**Comment by sftim** [comment]
/triage duplicate

It's not clear to me how this is different from https://github.com/kubernetes/website/issues/39353

**Comment by T-Lakshmi** [comment]
Hi @sftim,
I would like to work only on English docs for this issue.
As people are opening separate issues for each language and #39353 is covering multiple packages of work as mentioned by you in comments, i confused a little and thought to open separate issue for English.

If you suggest to work on parent issue #39353 for the default language(english), i will do the same and will close this issue.
WDYT?

**Comment by sftim** [comment]
/retitle [en] Remove or mark all references to k8s.gcr.io - English localization

/remove-triage duplicate

**Comment by devarsh10** [comment]
Hey @T-Lakshmi, I would like to work on the English docs. Please guide me, what should be my further steps?

Regards.

**Comment by devarsh10** [comment]
Hey @T-Lakshmi, should I make changes in [2022-11-28-registry-k8s-io-change.md](https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2022-11-28-registry-k8s-io-change.md). And replace `k8s.gcr.io` with `registry.k8s.io`. Please let me know.

Regards.

**Comment by T-Lakshmi** [comment]
Hi @devarsh10, 
I am already working on this issue.

**Comment by T-Lakshmi** [comment]
Hi @devarsh10,
I am already working on this issue,
Thanks.

**Comment by devarsh10** [comment]
Okay.
