### ISSUE TITLE
Issue with /docs/getting-started-guides/kubeadm/

### ISSUE THREAD

**Issue by wsanders** [kubernetes/website#3944]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
```
# kubectl apply -f kube-flannel.yml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
Docs should make it more clear that that these steps are mandatory (even if you are root and $HOME is /root):
```
To start using your cluster, you need to run (as a regular user):
  sudo cp /etc/kubernetes/admin.conf $HOME/
  sudo chown $(id -u):$(id -g) $HOME/admin.conf
  export KUBECONFIG=$HOME/admin.conf
```
Otherwise, the error above occurs because KUBECONFIG is not exported into the environment.

OS is Centos 7.3.1611.

**Proposed Solution:**
???

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/kubeadm/

**Comment by Elitric** [comment]
Are you sure that's the cause? I was almost ready to nuke my setup, I'll report back if this fixes that hiccup.

**Comment by thatsk** [comment]
Is there kubernetes are looking into this  issue?
