### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by SuyambuNathanC** [kubernetes/website#39447]
Hi,

I upgraded & deployed the spring-boot (2.7.8 v) application with spring-cloud version 2021.0.5 v in Azure cloud Kubernetes services. Access to services, endpoints, pods and all enabled for the service account as mentioned in the kubernete doc. The application is UP and running and pods also stable. But I'm getting always 404 error for all APIs in the Azure cloud. Its working properly in my local and all apis are giving proper response. I tried with spring-cloud-starter-kubernetes-client-all & spring-cloud-starter-kubernetes-client-config as well. But still getting same error. Is there any other configuration need to be done to resolve 404 error? Note: The application is working fine with spring-boot 2.1 version.

**Comment by tamilselvan1102** [comment]
/kind support

GitHub is not the right place for support requests [SuyambuNathanC](https://github.com/SuyambuNathanC)

If you are looking for help about using Kubernetes, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and ask your question there if a similar question has not yet been answered.

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

Moreover for java api reference, [`refer`](https://github.com/kubernetes-client/java)
