### ISSUE TITLE
Improve explanation in taints and tolerations concept

### ISSUE THREAD

**Issue by shirady** [kubernetes/website#39442]
I think that the first lines should explain what are Taints and Tolerations.
Starting the explanation with a comparison to Node Affinity is confusing.

Today:

> [Node affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) is a property of [Pods](https://kubernetes.io/docs/concepts/workloads/pods/) that attracts them to a set of [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) (either as a preference or a hard requirement). Taints are the opposite -- they allow a node to repel a set of pods.

I suggest:

> Taints allow a node to repel a set of pods.

and create a note with the original text.

**Comment by sftim** [comment]
/retitle Improve explanation in taints and tolerations concept
/priority backlog
/language en
/triage accepted

We have a [mechanism](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary) to let you include existing glossary entries. If someone is working on this issue, consider using that mechanism. You are welcome to tweak a glossary entry if that helps.

**Comment by tamilselvan1102** [comment]
@shirady 
Are you looking update on [taint-and-toleration](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) page

**Comment by shirady** [comment]
Hello @tamilselvan1102,
Yes, I'm looking at the updated page.
![Screenshot 2023-02-14 at 12 48 36](https://user-images.githubusercontent.com/57721533/218713920-0b41400b-88a0-4ad2-86bf-b7e3fc4f812c.png)



As I wrote:
> I think that the first lines should explain what are Taints and Tolerations. Starting the explanation with a comparison to Node Affinity is confusing.

**Comment by tamilselvan1102** [comment]
@shirady 
How about adding these following contents

> Taints are a Kubernetes node property that enable nodes to repel certain pods. 
> Tolerations are a Kubernetes pod property that allow a pod to be scheduled on a node with a matching taint.

**Comment by shirady** [comment]
@tamilselvan1102 I think it is a great improvement.

**Comment by tamilselvan1102** [comment]
@shirady it is the outcome
![image](https://user-images.githubusercontent.com/20103020/219549213-d268ca27-a293-490d-a8d0-d4f56c27e368.png)

**Comment by tamilselvan1102** [comment]
@sftim 
There is no glossary tooltip for **Node affinity**, that's why not changed to tooltip.

**Comment by sftim** [comment]
We could add a glossary entry for the concept of “affinity” and help people find the different kinds (pod-to-pod and pod-to-node).

It'd be nice to staff this; however, we have plenty of other work that also needs doing.
/lifecycle stale
