### ISSUE TITLE
Nested scrollbars within interactive tutorials (Katacoda)

### ISSUE THREAD

**Issue by mibadim** [kubernetes/website#39450]
The interactive tutorial console creates nested scrollbars:

![image](https://user-images.githubusercontent.com/5670523/218757407-4d836c96-7be0-4271-95e0-1087434528b1.png)

It's a pain to use. I'd be glad if this could be fixed.

**Comment by sftim** [comment]
We're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/). As such, we don't plan to fix this bug.

/retitle Nested scrollbars within interactive tutorials (Katacoda)

/triage unresolved

**Comment by Ananya2001-an** [comment]
Hey @sftim you should close this issue since it won't be resolved.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
