### ISSUE TITLE
Repetitive text in kubeadm-reset.md 

### ISSUE THREAD

**Issue by Ritikaa96** [kubernetes/website#39467]
**This is a Bug Report**

**Problem:**
[Kubeadm-reset.md](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/) has repetitive text in the beginning .

> Performs a best effort revert of changes made by kubeadm init or kubeadm join.

> Performs a best effort revert of changes made to this host by 'kubeadm init' or 'kubeadm join'
> **Synopsis**
> Performs a best effort revert of changes made to this host by 'kubeadm init' or 'kubeadm join'
>

**Proposed Solution:**
Remove the redundant texts.
**Page to Update:**
(https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/

**Comment by Ritikaa96** [comment]
It has generated code that's why it is not seen clearly in the original page. I'd like to contribute this change if accepted.
/assign

**Comment by Ritikaa96** [comment]
hi @sftim WDYT?

**Comment by divya-mohan0209** [comment]
Hello @Ritikaa96 , you may want to check the generator code as well.
