### ISSUE TITLE
Add alias for control plane 

### ISSUE THREAD

**Issue by Ananya2001-an** [kubernetes/website#39468]
**What would you like to be added**

Adding alias "master node" for the word control plane in [https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/ ](url) page will be a good idea as many people know it by this name as well.

**Why is this needed**
Avoiding confusion among beginners.

**Comments**

I would like to get assigned for this issue.

**Comment by tengqm** [comment]
/close
We should not do this.
Replacing 'master' with 'control plane' was a huge effort across the whole community. We are a technology community, but we were still involved into that movement.

**Comment by Ananya2001-an** [comment]
Sure I understand. Though I never said to replace it but instead add it as some extra information you know like previously it was called as master node. In brackets or something and just on this page.

**Comment by tengqm** [comment]
In the previous effort, we greped the whole website to find every instances of 'master' and replaced it. Also we searched the whole docs repo for 'docker' and replace it. We don't want to touch this topic again.
As some people advocated, let's call it control plane, and never 'master' again.

**Comment by Ananya2001-an** [comment]
Ok got it.
