### ISSUE TITLE
Info update regarding minikube

### ISSUE THREAD

**Issue by Ananya2001-an** [kubernetes/website#39469]
**This is a Bug Report**

**Problem:** In the last paragraph for the page [https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/](url) it's mentioned that the `Minikube is a lightweight Kubernetes implementation that creates a VM on your local machine` but instead it creates a single node cluster that runs on a VM which has to be present on the local machine. Users can misinterpret this and forget to install a VM like hyperkit/VirtualBox on their local machine.

**Proposed Solution:**
We should update this line to clarify that the user has to install a hypervisor on their host and only then they can run minikube.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

I would like to work on this.

**Comment by tengqm** [comment]
/close
We are not supposed to add detailed information about those tools.
What we can do and what we did do is to provide links to those tools.
The same documentation content is not supposed to be dual-hosted.

**Comment by Ananya2001-an** [comment]
Can we just replace the word 'creates' with 'runs' on a VM because the former sounds a bit misleading. No need to add extra information but just writing that it runs on a VM, I guess would be a better thing.
