### ISSUE TITLE
Improvement for k8s.io/docs/tasks/access-application-cluster/create-external-load-balancer/

### ISSUE THREAD

**Issue by emmjam** [kubernetes/website#39478]
Not very clear
What are the ports mapping to  ? How does this map back to the nodeIP ? What is the IP that external clients would hit ? 
So I can use a service or an ingress controller... for what purpose ? I thought I was building a loadbalancer ?

**Comment by sftim** [comment]
We could add a new tutorial page that explains setting up a load balancer, using minikube as an example, and then change https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/ to link to that tutorial in the introduction.

If we do this then the new tutorial page should explain the options (Service, Ingress, Gateway) and outline which might suit different needs. For example, Ingress only works with HTTP.

The new tutorial can also link to https://kubernetes.io/docs/tutorials/services/connect-applications-service/ and encourage people to work through that first.

I think that would be an improvement, if someone wants to work on adding it.
