### ISSUE TITLE
Trouble using Katacoda tutorial

### ISSUE THREAD

**Issue by a244591052** [kubernetes/website#39505]
Launch Interactive Environment collapse, can not open it

**Comment by tamilselvan1102** [comment]
working as expected. Please check your internet connectivity and popup settings.

![image](https://user-images.githubusercontent.com/20103020/219548303-99969041-4d05-4bc4-969f-d547b1df1009.png)

**Comment by sftim** [comment]
We're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/). As such, we don't plan to fix this bug.

/retitle Nested scrollbars within interactive tutorials (Katacoda)

/triage unresolved

**Comment by sftim** [comment]
oops.
/retitle Trouble using Katacoda tutorial

**Comment by sftim** [comment]
We're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/). 

For that reason, we won't work on a fix.

**Comment by tengqm** [comment]
/close

Won't fix because we're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
