### ISSUE TITLE
Need to track update to APF debug endpoint

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#39512]
**This is a Bug Report**

**Problem:**
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/cluster-administration/flow-control.md#debug-endpoints has not been updated to track the enhancement in https://github.com/kubernetes/kubernetes/pull/112393

**Proposed Solution:**
Update that page.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#debug-endpoints

/sig api-machinery
/assign @borgerli

**Comment by MikeSpreitzer** [comment]
@borgerli can you please take care of this too?

**Comment by borgerli** [comment]
Sure, I'll make a PR to update the doc.
