### ISSUE TITLE
"Drain the node" should be prior to Call "kubeadm upgrade" to ensure safe upgrade

### ISSUE THREAD

**Issue by nidhi-singh02** [kubernetes/website#39540]
**This is a Bug Report**

**Problem:** 
In the documentation for upgrading cluster via kubeadm for [Upgrading control plane nodes ](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrading-control-plane-nodes), the order of steps seems not appropriate.

**Proposed Solution:**
The order of steps should be as below to ensure safe upgrade. It's a recommended approach to drain the node first and then do the actual upgrade.
1) Drain the node 
2) Call "kubeadm upgrade"

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#call-kubeadm-upgrade

**Comment by tengqm** [comment]
I don't see that a problem.
The `kubeadm upgrade` command mentioned is only about control plane and kubeadm itself.
You will drain a node before you upgrade a worker node. The steps as is is correct.

**Comment by nidhi-singh02** [comment]
There could be a scenario where workload might be running on control plane node/s. 
I think a note mentioning that `kubeadm  upgrade apply` may imapct the workload if we are not draining it prior or changing the order of steps can help a beginner.

**Comment by neolit123** [comment]
draining a node is only relevant around kubelet upgrade followed by kubelet restart. the current steps look correct to me for "upgrade apply" and "upgrade node" for CP nodes.

**Comment by sftim** [comment]
Is there an outcome you're worried about @nidhi-singh02 ? 

Maybe we can document why you typically wouldn't need to drain the node (I presume one reason for the comments by other contributors is that the workload Pods running in that control plane node should survive the kubelet upgrade).

**Comment by nidhi-singh02** [comment]
@neolit123 Just wanted to clarify - does this mean "kubeadm upgrade apply" will have no impact on exisiting work loads running on controlpane nodes, will they still be running after the upgrade ?

@sftim I assume you meant "would need to drain the node" this. If we don't drain the node, how will it survive the kubelet upgrade ?

**Comment by sftim** [comment]
Let's say you've got 3 systemd-managed units on a Linux nodes:
- `containerd`
- `kubelet`
- `kube-proxy` (unusual, but valid)

You stop the kubelet unit. `containerd` _and any containers that the kubelet started_ continues to run. The `kube-proxy` continues to run. Your Pods are not getting health checked and the control plane isn't sure what's going on, but the apps are still running.

Shortly afterwards, you start the kubelet. The kubelet sees that the Pods assigned to that node seem to already be running.

I think something like that happens. If you're not sure, try it out (you can use `crictl` to experiment). You might see that a drain isn't needed.

---

We could use a tutorial page to explain this as it's an important detail - whether or not I've got it right - and worth helping people understand.
You might assume that the kubelet shuts down each container before stopping, but AIUI it doesn't support that even as an option.
