### ISSUE TITLE
Help with (unspecified) ingress controller rewrite rules

### ISSUE THREAD

**Issue by amagicalbrain** [kubernetes/website#39557]
Hello There,

We have 4000 rewrite rules which I am adding that in ingress rule and after adding when I am trying to apply I am getting this error below:
"The Ingress "***-app-***" is invalid: metadata.annotations: Too long: must have at most 262144 bytes"

Kindly help in this issue.

**Comment by sftim** [comment]
/retitle Help with (unspecified) ingress controller rewrite rules

Hi @amagicalbrain 

Kubernetes limits the size of an [annotation](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/) that you can set. If you want to use an ingress controller, check that you can set parameters for it using an [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) - that should help avoid the size limit with annotations.

If the [ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) you're using is part of Kubernetes, and only supports annotations for the task you're doing, you could file an issue against that component (not the documentation) to request an improvement.
If you're using a third-party ingress controller, you could talk to the team that maintain or support it.

/kind support

**Comment by amagicalbrain** [comment]
@sftim
Thank you for your response.

**Comment by sftim** [comment]
/close

No documentation to fix.
