### ISSUE TITLE
Broken Quickstart link in Use Calico for NetworkPolicy

### ISSUE THREAD

**Issue by dipesh-rawat** [kubernetes/website#39552]
**This is a Bug Report**

**Problem:**
[Calico Quickstart](https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy/#creating-a-local-calico-cluster-with-kubeadm) under the 'Use Calico for NetworkPolicy' is leading to an invalid URL resulting in page not found error.

**Proposed Solution:**
Updating of Quickstart link in the [Creating a local Calico cluster with kubeadm](https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy/#creating-a-local-calico-cluster-with-kubeadm)

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy/

**Comment by Ritikaa96** [comment]
Hi @dipesh-rawat , great find!

Apart from fixing link you can also look for further improvement in overall doc so that one PR can cover more improvements. For eg. fixing Grammatical errors, adding more information in the sections etc.

**Comment by Ritikaa96** [comment]
This seems to be duplicate of #39536 
/triage duplicate

**Comment by dipesh-rawat** [comment]
@Ritikaa96 https://github.com/kubernetes/website/issues/39536 looks to be reporting broken link on https://kubernetes.io/docs/concepts/cluster-administration/addons/ whereas this issue is reporting issue with link on different page https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/calico-network-policy/

**Comment by Ritikaa96** [comment]
Right. my bad. Please consider these points as well:

> Hi @dipesh-rawat , great find!
> 
> Apart from fixing link you can also look for further improvement in overall doc so that one PR can cover more improvements. For eg. fixing Grammatical errors, adding more information in the sections etc.
