### ISSUE TITLE
Document node upgrade on Linux

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#39577]
**This is a Feature Request**

**What would you like to be added**
Add a page titled “Upgrading Linux Nodes”

**Why is this needed**
We have an [equivalent page](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/) for Windows. Someone who runs Linux worker nodes may well want to see a page just like that, but explaining what to do for their Linux-based node OS.

**It is OK to adapt existing pages and to link to them.**

**Comments**
/sig cluster-lifecycle
/priority backlog
/language en

**Comment by Shubham82** [comment]
Hi @sftim
there is a section on [Upgrade worker nodes](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrade-worker-nodes) in the [Upgrading kubeadm clusters task](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/), which has the content for upgrading  Linux worker nodes. I wonder do you want a separate document for it?

**Comment by sftim** [comment]
>  I wonder do you want a separate document for it?

Yes. This issue is a request for a document just like https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/ but with Linux in the title. It is OK to adapt existing pages and to link to them.

**Comment by Ritikaa96** [comment]
> > I wonder do you want a separate document for it?
> 
> Yes. This issue is a request for a document just like https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/ but with Linux in the title. It is OK to adapt existing pages and to link to them.

right, i can recall the section only says:

> Upgrade kubeadm
From the Windows node, upgrade kubeadm:

and no addition for another os. This will be helpful. @Shubham82 are you working on it?

**Comment by Shubham82** [comment]
> Yes. This issue is a request for a document just like https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/ but with Linux in the title. It is OK to adapt existing pages and to link to them.

Thanks, @sftim for the information!

**Comment by Shubham82** [comment]
Hi @Ritikaa96, thanks for your comments.

> @Shubham82 are you working on it?


Yeah, I am working on it.

I will soon open a PR for it.

**Comment by Shubham82** [comment]
I have raised a PR: #39741 Please take a look!
