### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/certificate-signing-requests/

### ISSUE THREAD

**Issue by JonasJasas** [kubernetes/website#39591]
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#create-private-key

I guess this `-subj "/CN=myuser"` needs to be appended here `openssl req -new -key myuser.key -out myuser.csr` 

After following instructions I am unable to authenticate to the cluster if `-subj "/CN=myuser"` is missing.

**Comment by sftim** [comment]
I think the author of that reference page expected that you would use the OpenSSL tool interactively, and that's why you can read:

> It is important to set CN and O attribute of the CSR. CN is the name of the user and O is the group that this user will belong to. 

If your configuration for OpenSSL doesn't prompt you for a common name, the advice won't work as expected.
We could change this page to use a different tool - not `openssl req` - that is perhaps easier to explain consistently.

/sig auth
/language en

**Comment by JonasJasas** [comment]
Just by appending `-subj "/CN=myuser"` would make this reference a working copy/paste step-by-step guide.

**Comment by aramase** [comment]
> Just by appending `-subj "/CN=myuser"` would make this reference a working copy/paste step-by-step guide.

@sftim Should we do this as the first step so the docs are correct? Then we could explore the option of a different tool as per https://github.com/kubernetes/website/issues/39591#issuecomment-1438126755. WDYT?

**Comment by sftim** [comment]
> @sftim Should we do this as the first step so the docs are correct

I won't comment on that - SIG Auth or SIG Security are the best people to explain and confirm what the right fix is here, from a technical perspective.

If you know it does fix this then sure, feel free to open a PR.

**Comment by Shubham82** [comment]
I will open a PR for it.

/assign

**Comment by Shubham82** [comment]
Fixed it here: #41682

**Comment by Shubham82** [comment]
@sftim or @aramase anyone from you, could you please take a look at the PR: #41682 corresponding to the issue?

Thanks
