### ISSUE TITLE
Interactive Tutorial - Deploying an App

### ISSUE THREAD

**Issue by gzoanetti-mdb** [kubernetes/website#39594]
The terminal window on this [link](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/) isn't present. If you swap the language, it will ask you to use the Desktop version of your browser (Even when checking this URL from a fully updated Chrome browser)

**Comment by Manikandanmuru** [comment]
We have two issues here.

Issue 1: No Terminal window available for the English version
Issue 2: If we change the Website Language other than English it refers to use                                                                                                          "Use the desktop/tablet version to work with the terminal"

I will look into this issue.

**Comment by gzoanetti-mdb** [comment]
Thank you. I can confirm that none of the interactive tutorial URLs are displaying the terminal.

**Comment by Manikandanmuru** [comment]
@nate-double-u Can you please guide me.

**Comment by Ritikaa96** [comment]
Hi @gzoanetti-mdb , Tutorials that have katacoda environment are facing problem it seems. 
For that please refer to : https://github.com/kubernetes/website/issues/39505#issuecomment-1434931638
as k8s team is removing katacoda.

**Comment by Ritikaa96** [comment]
Also I just could see im able to access some of the tutorials and even tried running commands. Attaching the screenshots for reference.
![Screenshot from 2023-02-21 22-05-14](https://user-images.githubusercontent.com/52399571/220406380-de216b11-cbad-441e-ad05-c7257ba97cc4.png)
![Screenshot from 2023-02-21 22-09-19](https://user-images.githubusercontent.com/52399571/220406406-74057b0c-1ca7-4aa2-a0af-6fbee94dfb5a.png)

**Comment by Ritikaa96** [comment]
Also it seems to be same issue as https://github.com/kubernetes/website/issues/39505#issuecomment-1434931638

/triage duplicate

**Comment by nate-double-u** [comment]
We're [removing Katacoda](https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

For that reason, we won't work on a fix.
