### ISSUE TITLE
Add glossary entry for probe

### ISSUE THREAD

**Issue by MRHUB0** [kubernetes/website#39608]
Add Probe definition

Probe -  A diagnostic performed periodically by the kubelet on a container.

**Comment by sftim** [comment]
/retitle Add glossary entry for probe
/language en
/kind feature

@MRHUB0 we _can't_ yet use your suggestion verbatim as we'd need you to [sign](https://www.k8s.dev/docs/guide/#sign-the-cla) our license agreement. It's easy to do, but it's also a requirement for contributing.

**Comment by Ritikaa96** [comment]
If @MRHUB0 not doing it i'd like to contribute it.

**Comment by MRHUB0** [comment]
Im going to do it today. Sign the cla and contribute.Thank you,MRHUBOOn Feb 22, 2023, at 4:24 AM, Ritika ***@***.***> wrote:﻿
If @MRHUB0 not doing it i'd like to contribute it.

**Comment by MRHUB0** [comment]
I've submitted a PR

**Comment by Ritikaa96** [comment]
Hi @MRHUB0 , You can mention this issue in the PR and Link  with it so that when PR is merged , issue will close by itself
Also please look at https://kubernetes.io/docs/contribute/ for good contribution practices.

**Comment by Ritikaa96** [comment]
you should assign the issue to yourself by using assign tag

**Comment by MRHUB0** [comment]
Excellent advice. Will do.Thank youOn Feb 23, 2023, at 3:09 AM, Ritika ***@***.***> wrote:﻿
you should assign the issue to yourself by using assign tag

**Comment by KhushPatibandha** [comment]
Is this issue still open/not resolved ? 
I feel like I can help.

**Comment by KhushPatibandha** [comment]
I don't see any glossary entry for probe so I suppose this issue is not resolved?

**Comment by vaibhav2107** [comment]
The issue is fixed by PR #40131, Hence closing this issue
