### ISSUE TITLE
Kubernetes Components Low Image Visibility 

### ISSUE THREAD

**Issue by Farial-mahmod** [kubernetes/website#39614]
The image of the "The components of a Kubernetes cluster" on the link https://kubernetes.io/docs/concepts/overview/components/ has a grey background that hurts the eyes a little due to containing the blue and white icons. The color combination may be improved for better visibility.
Kindly, address the issue if you feel the same about the image.

**Comment by Ritikaa96** [comment]
Hi @Farial-mahmod , there is an issue which address a similar problem. after zooming in , it will help seeing the image better: https://github.com/kubernetes/website/issues/38051

**Comment by Ritikaa96** [comment]
if the issue address different problem you can suggest changes you recommend. any suggestion or contribution is welcome.
