### ISSUE TITLE
Minor modifications to some links in "Windows containers in Kubernetes" page.

### ISSUE THREAD

**Issue by bconfiden2** [kubernetes/website#39616]
**This is a Feature Request**
In [concepts/windows/intro.md](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/windows/intro.md) file, some document links are over-addressed(?).
For example, links for line 241 and 245 contain the full address to the target location,
and I think it is accessible with only using #, since they exist in same file.
Is there any reason to reference an entire address, instead of using only # ?

**What would you like to be added**
remove needless part
241: #compatibility-v1-pod-spec-containers-hostnetwork
245: #compatibility-v1-pod-spec-containers-securitycontext

**Comment by tamilselvan1102** [comment]
yes, we can replace the full link with subsection ID

**Comment by bconfiden2** [comment]
@tamilselvan1102 Thanks for your reply! 
If you don't mind, can I self-assign?

**Comment by tamilselvan1102** [comment]
please do it yourself. thank you

**Comment by bconfiden2** [comment]
Thank you !
/assign
