### ISSUE TITLE
Installing Addons broken link

### ISSUE THREAD

**Issue by criscola** [kubernetes/website#39620]
Hi, I noticed that Calico's link in [Installing Addons](https://kubernetes.io/docs/concepts/cluster-administration/addons/#networking-and-network-policy) is currently broken and returns a page not found error.
Maybe this is the correct link? https://docs.tigera.io/calico/3.25/getting-started/kubernetes/quickstart

**Comment by Ritikaa96** [comment]
Hi There is a similar issue for broken link for calico #39536
