### ISSUE TITLE
Documentation left pane view cuts title name

### ISSUE THREAD

**Issue by nitesh8860** [kubernetes/website#39621]
Hi,

While using the Documentation, at 100% page zoom ( normal view ) the left side panel cuts the part of titles of the pages.
and there is no way to expand that area or scroll horizontally through it to see full title name of a page.

![image](https://user-images.githubusercontent.com/13062907/220581451-8570e835-bd1c-4075-88d3-c11527837e3d.png)

If i zoom down to 50-60% it is visible then

![image](https://user-images.githubusercontent.com/13062907/220582006-9e38fca1-1439-4934-84e2-150d294585c9.png)

but this makes it unreadable.
Please provide some solution over it.

**Comment by Ritikaa96** [comment]
Right. this is related to the web-development area. Tagging /area web-development so area experts can find this one. 
What do you suggest ?
The side bar has a lot of subsection and thus it seems to need more space. to not make it complicated , expanding the sidebar only to select required page and using it as it is doesn't some so bothersome as main focus is on the content of the page.

**Comment by Ritikaa96** [comment]
Just saw one more like this. This issue seems to be dulicate of [#38663](https://github.com/kubernetes/website/issues/38663)
/triage duplicate

**Comment by KhushPatibandha** [comment]
I feel like I can contribute to this issue.

**Comment by KhushPatibandha** [comment]
Hey, can anyone help me with this one? Like I got half of the bit done but the thing is that the page is not responsive when we slide it, 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/104303438/226423538-aa0a1ae4-4b84-4956-80d6-14bfa9877f8d.png">

**Comment by tengqm** [comment]
You will have to show your half-baked solution for people to understand where you are.
The current panel split is based on Bootstrap `col-` and `col-md-*` etc. You have got to break that settings.

**Comment by KhushPatibandha** [comment]
![image](https://user-images.githubusercontent.com/104303438/226515336-8085bb47-dbd5-4cf4-9b1f-59a00eae10cb.png)

**Comment by KhushPatibandha** [comment]
So, I have found the .md file for the doc but I can't really find the html file for the website. Can you help me with that ?

**Comment by tengqm** [comment]
I believe the source is located at `layouts/docs/baseof.html`.

**Comment by tengqm** [comment]
@KhushPatibandha The file `sidebar.html` is from the Docsy theme (https://github.com/google/docsy/blob/main/layouts/partials/sidebar.html).

**Comment by KhushPatibandha** [comment]
Thanks, I'll surely look into it

**Comment by KhushPatibandha** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/104303438/227267465-3cd9f92b-b310-455c-ae4d-0b072cff9fc1.png">
A little bit of progress, right now as you can see I am still not able to resize the panel so if the user want to shrunk the sidebar that won't be possible. so as @tengqm said that I need to break the setting of col- ,col-sm- , etc am I on the right track?

**Comment by Skar3Krow** [comment]
Hey @KhushPatibandha , I would like to assisst you with this issue

**Comment by KhushPatibandha** [comment]
Sure do look at the PR that are generated, am sort of stuck where the footer and the headbar are glitching, I would appreciate if you can help me with that.

**Comment by KhushPatibandha** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/104303438/228211327-fe2f8077-add2-4b4b-832f-8e97b8c75025.png">
So this is the second approach I thought about, but it's just that the main documentation isn't shrinking can you help me with that if possible.

**Comment by nitesh8860** [comment]
thanks @Skar3Krow the solution looks good, but i believe this will not work for all use cases and will cut some text somewhere in the docs, we have to make divider between left panel right text dynamic, so that it can be increased and decreased.

**Comment by tengqm** [comment]
See: https://github.com/kubernetes/website/pull/41695

**Comment by sftim** [comment]
This is a duplicate. Let's use #38663 for tracking

/close not-planned

**Comment by sftim** [comment]
Actually, I've already changed my mind.
/reopen
/remove-triage duplicate
/triage accepted
/area web-development

**Comment by Gauravpadam** [comment]
I feel #41695 solved this quite plausibly

Should we close this?
