### ISSUE TITLE
Kustomize suggestion for Helm Chart

### ISSUE THREAD

**Issue by vinaykeenable** [kubernetes/website#39623]
I have tested Helm Chart rendering with Kustomize which create deployment as plain yaml deployment.
**Behavior**  kustomize render the Helm chart as plain yaml.
**Expectation** while rendering the Helm chart, it should keep the release as Helm chart to manage the better lifecycle.

**Comment by sftim** [comment]
/triage needs-information

Hello. Which web page in the documentation isn't right?

**Comment by Shubham82** [comment]
closing this issue, as there is no information given.

/close
