### ISSUE TITLE
rename config.toml to hugo.toml

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#39632]
**This is a Feature Request**
rename config.toml to hugo.toml

**Why is this needed**
https://github.com/gohugoio/hugo/releases/tag/v0.110.0
https://github.com/gohugoio/hugo/issues/8979

we update to 0.110.0
https://github.com/kubernetes/website/blob/main/netlify.toml#L11

/assign

**Comment by sftim** [comment]
https://gohugo.io/getting-started/configuration/#hugotoml-vs-configtoml is a thing now, so:
/triage accepted
