### ISSUE TITLE
Service concept unclear on `port` vs `targetPort` consistency for headless Services

### ISSUE THREAD

**Issue by christiancadieux** [kubernetes/website#39641]
Need to mention that for headless services without selector, the Port need to be the same as the TargetPort.

https://stackoverflow.com/a/75448581

**Comment by KhushPatibandha** [comment]
hey, can i get some more context related to this? I would like to work on this issue

**Comment by christiancadieux** [comment]
you can see some information about this here: 
do we really need port for a headless service?


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
do we really need port for a headless service?

It might be a question based on curiosity which couldn't find help on google.Consider this part of the yaml fo...
 |

 |

 |




Headless service targetPort not resolving containerPort name · Issue #20488 · kubernetes/kubernetes

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Headless service targetPort not resolving containerPort name · Issue #20...

It seems that my headless service definition does not correctly resolve the containerPort name. I receive this e...
 |

 |

 |






    On Friday, March 10, 2023 at 10:17:59 PM MST, Khush Patibandha ***@***.***> wrote:  
 
 


hey, can i get some more context related to this? I would like to work on this issue

**Comment by sftim** [comment]
/sig network
/kind bug
/triage accepted
/retitle Service concept unclear on `port` vs `targetPort` consistency for headless Services

**Comment by T-Lakshmi** [comment]
Fixed on #30817
