### ISSUE TITLE
Connect a Frontend to a Backend Using Services

### ISSUE THREAD

**Issue by lemonguge** [kubernetes/website#39652]
[service/access/backend-service.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/zh-cn/examples/service/access/backend-service.yaml)

targetPort: http

![image](https://user-images.githubusercontent.com/12459895/221109052-c984a709-5c92-4d3c-84f4-6739b74ddc2b.png)

**Comment by utkarsh-singh1** [comment]
Related Doc - https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

/sig docs
/language en

**Comment by sftim** [comment]
Hi.

What's wrong? The `http` port is port 80; that example manifest looks right to me.

/triage needs-information

**Comment by NitishKumar06** [comment]
I'm assuming you may be expecting a port number in front of `targetPort`, are you?

**Comment by KhushPatibandha** [comment]
hey @lemonguge can you provide some more info on what the issue here is? I would like to work on this if possible

**Comment by lemonguge** [comment]
Sorry, my mistake
