### ISSUE TITLE
[ko] Translate tasks/debug/debug-application/debug-service in Korean

### ISSUE THREAD

**Issue by Virusuki** [kubernetes/website#39671]
**This is a Feature Request**

**What would you like to be added**

Translate tasks/debug/debug-application/debug-service in Korean

**Why is this needed**
No translation with tasks/debug/debug-application/debug-service in Korean

**Comments**

Page to Update:
https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/

**Comment by jihoon-seo** [comment]
@Virusuki 감사합니다!
기존 이슈는 없는 것 같고, updated outdated files 태스크 중에서도 해당되는 것이 없는 것 같습니다.
/triage accepted

**Comment by jihoon-seo** [comment]
@Biswajit-Mohapatra2 Thank you for showing your interest on this issue,
but please don't self-assign if the issue has been already assigned to someone.
Also, please don't contribute on Korean localization using machine translators if you are not fluent in Korean.

**Comment by Biswajit-Mohapatra2** [comment]
@jihoon-seo : sure

**Comment by jihoon-seo** [comment]
This issue has been resolved by
- #40463
- #41321

Thank you!
/close
