### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by 1dropaflame** [kubernetes/website#39682]
1) No instructions on how exactly to perform the operations. On Windows11/Docker Desktop for instance, "/etc/kubernetes/enc/" does not exist.
2) The name of the file to save the code snippet to, is missing as well as the "Copy" icons.
The entire page is missing it.
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#encrypting-your-data

**Comment by Ritikaa96** [comment]
Hi @1dropaflame , good catch about the copy icon

> 2\. The name of the file to save the code snippet to, is missing as well as the "Copy" icons.
>     The entire page is missing it.
>     https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#encrypting-your-data

Although i cant understand what you are talking about in point 1 as there is https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#encrypting-your-data section for the operation

**Comment by sftim** [comment]
> No instructions on how exactly to perform the operations. On Windows11/Docker Desktop for instance, "/etc/kubernetes/enc/" does not exist.

We don't support running the API server on Windows, nor do we provide support for distributions of Kubernetes - Docker Desktop, Amazon EKS, OpenShift, etc.

You do need to create `/etc/kubernetes/enc` on the node. Although we could mention this, I'm minded not to include that detail: if it's not obvious to the reader that this is needed, they might not have enough POSIX / Unix admin knowledge to complete the task.

**Comment by sftim** [comment]
> The name of the file to save the code snippet to, is missing as well as the "Copy" icons.
> The entire page is missing it.

Ah, that's because it's not a manifest that you could submit using the Kubernetes API. You can still copy the text, you'll have to use your browser's tooling for that, and must then customize the copied text before you use it.

If we did provide helpers to copy the text, readers who aren't being careful might copy what's there without thinking about the consequences. I don't want to encourage that, and I don't think the wider documentation SIG does either.

**Comment by 1dropaflame** [comment]
[Tim]  "You do need to create /etc/kubernetes/enc on the node."

Can you please clarify? I hope I am mistaken but I do not think it is as
simple as: mkdir /etc/kubernetes/enc
I opened this issue here:
If Kubernetes is enabled in Docker Desktop/WSL2, then why can’t we see the
full functionality of Kubernetes?
If Kubernetes is enabled in Docker Desktop/WSL2, then why can’t we see the
full functionality of Kubernetes? · Issue #13274 · docker/for-win
(github.com) <https://github.com/docker/for-win/issues/13274>
