### ISSUE TITLE
pod-eviction-timeout argument missing from kube-controller-manager

### ISSUE THREAD

**Issue by carlocorradini** [kubernetes/website#39681]
**This is a Bug Report**

**Problem:**

In the documentation about [Node Heartbeats](https://kubernetes.io/docs/concepts/architecture/nodes/#heartbeats) it is explicitly written: 
_If the status of the Ready condition remains Unknown or False for longer than the **pod-eviction-timeout** (**an argument passed to the kube-controller-manager**) ..._

However, when looking for the **pod-eviction-timeout** argument in the [**kube-controller-manager** docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager), the flag is absent.

**Proposed Solution:**

Add **pod-eviction-timeout** argument in the **kube-controller-manager** documentation.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager

**Comment by Ritikaa96** [comment]
JFYI. the `pod-eviction-timeout flag is deprecated as per v1.26 .
for reference: https://github.com/kubernetes/sig-release/blob/master/releases/release-1.26/release-notes/maps/pr-113710-map.yaml
Do we really want to add argument for this in the doc now as its going to be deprecated.

**Comment by Ritikaa96** [comment]
what we can do is mention in a note regarding deprecation or adding explanation in the document you mentioned: https://kubernetes.io/docs/concepts/architecture/nodes/#heartbeats

**Comment by carlocorradini** [comment]
Thank you all. One information. The flag is deprecated, what is the correct solution now?

**Comment by sftim** [comment]
**If** `kube-controller-manager` does still accept and honor `--pod-eviction-timeout`, then:

We could manually edit the page https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager (which is autogenerated), to reinstate the way that we explained `--pod-eviction-timeout` in v1.23 and earlier.

I don't think we'd need to take any further action.

---

The next step for this issue is to find out whether `kube-controller-manager` really does accept and honor that command line argument.

**Comment by tengqm** [comment]
Double checked this. The `--pod-eviction-timeout` flag was still there in v1.25 (https://v1-25.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/), and it was marked deprecated (https://github.com/kubernetes/kubernetes/pull/113710) before v1.26 is out.
In v1.26, if you do `kube-controller-manager --help`, you won't see the `--pod-eviction-timeout` flag because of this deprecation. The flag is still out there, according to the [PR](https://github.com/kubernetes/kubernetes/pull/113710) that deprecated it. I'm not sure this deprecation is only for the command line flag or it is for the whole feature. If it is the former case, maybe it is time to add the [config API](https://v1-25.docs.kubernetes.io/docs/reference/config-api/) for `kube-controller-manager`. We have [a copy of this](https://github.com/kubernetes-sigs/reference-docs/blob/master/genref/output/md/kube-controller-manager-config.v1alpha1.md) but not yet published it on the website.

**Comment by sftim** [comment]
Ideally, we should document even deprecated flags in the autogenerated docs. I appreciate that getting this right is tricky.

Does the manual fixup sound like the right approach given the upcoming removal?

**Comment by tengqm** [comment]
I'm not sure if documenting the deprecated flags is the right thing to do. A deprecated flag is not shown when you run `kube-component --help`. The flag is skipped in the generated reference in the same spirit.
Another option is to explicitly highlight a flag as deprecated if so, but still allow it to show up in the reference. Does that sounds better?

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/115840 is in process and the comment says that `pod-eviction-timeout` will be removed in v1.27.

**Comment by SergeyKanzhelev** [comment]
/assign @atosatto

since you are working on PR for this

**Comment by dberardo-com** [comment]
what is the alternative to pod eviction timeout to tune the timeout for pods to be evicted in case of node failures ?

**Comment by sftim** [comment]
> explicitly highlight a flag as deprecated if so, but still allow it to show up in the reference

I'd do that. If we can put the deprecation info into the HTML, someone can - perhaps months or years later - add a “hide deprecated command line parameters” checkbox and some CSS to simplify the page when you do. For example, put deprecated things inside a `<div class="argument-deprecated">…</div>`.

**Comment by brownz11** [comment]
> what is the alternative to pod eviction timeout to tune the timeout for pods to be evicted in case of node failures ?

The alternative is to used taint based eviction. https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

When a Node goes down (or the kubelet stops posting status) the node will get tainted with `node.kubernetes.io/unreachable`

Pods by default tolerate this taint for 5 minutes, but that can be overridden with a standard taint toleration to tolerate it for more/less time.

**Comment by dberardo-com** [comment]
> Pods by default tolerate this taint for 5 minutes, but that can be overridden with a standard taint toleration to tolerate it for more/less time.

is there a way to define this default globally or should it be done on a pod by pod basis ?

**Comment by erikschul** [comment]
Possibly related: https://github.com/kubernetes/website/issues/39681

It sounds like the Admissions Controller is now responsible for setting default taints on pods.
Which means that changing these settings will only affect new pods.
Alternatively this can be configured (e.g. via a script) on all existing pods.

The default toleration is 300s.
The default node-monitor-grace-period is 40s.
So a pod can be down for 340s before being rescheduled.

My conclusion is:
This allows you to quickly reboot a server without having to reschedule the workloads. Rebalancing later is hard/manual.
For HA, you should be running many pods, so it's more important that they're removed from the service endpoints.
For single-pod deployments, you should configure a low toleration.

**Comment by Pflegusch** [comment]
> > Pods by default tolerate this taint for 5 minutes, but that can be overridden with a standard taint toleration to tolerate it for more/less time.
> 
> is there a way to define this default globally or should it be done on a pod by pod basis ?

Have you found something about this?

**Comment by erikschul** [comment]
@Pflegusch Did you read the above?
**From my perspective the issue has been answered and can be closed.**

The design has changed. Use the new design.

- Taint can be specified on each pod: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

- Default taint can be customized, but is only applied when pods are created:
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaulttolerationseconds

**Comment by rajanarayanaa** [comment]
> @Pflegusch Did you read the above? **From my perspective the issue has been answered and can be closed.**
> 
> The design has changed. Use the new design.
> 
> * Taint can be specified on each pod: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
> * Default taint can be customized, but is only applied when pods are created:
>   https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaulttolerationseconds

@erikschul Could you please help me understand how this work along with Pod GC - https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection?

As per the doc, PodGC cleanup the orphan Pods(bound to a node which no longer exists). In my observation it is seen that the pods getting deleted as part of PodGC within 60 seconds even when tolerationSeconds is not specified(assuming it defaults to 300s)

**Comment by erikschul** [comment]
@rajanarayanaa I'm just going to guess here:
From what I'm reading, "pod gc" is for failed pods. I'm guessing that pods are "failed" only when the node is considered failed.
And that this is different from a toleration.

For example, when a node has an intermittent network failure. A workload may require a toleration (unreachable) of only 10 seconds, to quickly recover on a different node. The node has not yet "failed", but the workload is rescheduled.
The node recovers after 30 seconds. Other workloads remain. Node never "failed".

**Comment by andreaskaris** [comment]
this was addressed with 3a81c94ba8b6ada277bc5e5e44a4e7ce62c2cfa9, shouldn't this issue be closed? or is it waiting for the translations?
