### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by jl-aic** [kubernetes/website#39696]
Cannot access https://packages.cloud.google.com/apt/doc/apt-key.gpg - 500 errror

**Comment by dipesh-rawat** [comment]
This seems to be a duplicate of #39685
/triage duplicate

**Comment by dipesh-rawat** [comment]
@jl-aic Would you please refer https://github.com/kubernetes/website/issues/39685#issuecomment-1446077195 to see if that helps.

**Comment by dims** [comment]
See work around with new URL here: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585
