### ISSUE TITLE
Annotation `volume.beta.kubernetes.io/storage-class` not documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#39704]
**This is a Bug Report**

**Problem:**
Kubernetes ~sometimes sets~ used to honor an annotation,  `volume.beta.kubernetes.io/storage-class`.

However, this annotation is not documented in 
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Proposed Solution:**
Document this annotation and explain that it's deprecated.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig storage
/language en

**Comment by dipesh-rawat** [comment]
Happy to work on this issue.

/assign

**Comment by dipesh-rawat** [comment]
Changes to address this issue have been merged as part of PR #39717

**Comment by Shubham82** [comment]
Closing this issue, as it was resolved by PR #39717
/close
