### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by springland** [kubernetes/website#39711]
Can you please review https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ 
if the SWAP needs to be disabled for kubelet is still accurate?

The reason I am asking is based on discussion in https://github.com/kubernetes/kubernetes/issues/53533
There is a development to enable SWAP merged in July 2021.

Has it been released with 1.25 or 1.26 ?

Thanks

Lin

**Comment by Shubham82** [comment]
Hi @springland 
Currently, it is in the alpha stage. Here is the KEP you can read about it: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap

Corresponding KEP Issue: https://github.com/kubernetes/enhancements/issues/2400

**Comment by Shubham82** [comment]
As mentioned in the issue, the beta release is planned for k8s v1.28.

you can enable it by changing the feature gate `NodeSwap` to true, which is currently by default `false`.
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features

**Comment by springland** [comment]
Got it. Thanks for the help.

**Comment by Shubham82** [comment]
> Thanks for the help.

welcome

**Comment by Shubham82** [comment]
Closing this issue as it is resolved.

/close
