### ISSUE TITLE
Instructions for installing `kubectl` on Linux are not correct for Debian

### ISSUE THREAD

**Issue by fajcikm** [kubernetes/website#39748]
Install and Set Up kubectl on Linux instructions are not correct for Debian systems. 

**Problem:**
Steps 2. Download the Google Cloud public signing key and 3. Add the Kubernetes apt repository in never versions of Ubuntu  and Debian are incorrect due to deprecation of apt-key and replacement with trusted.gpg

**Proposed Solution:**

2. Download the Google Cloud public signing key:
`wget -O- https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor >kubernetes-archive-keyring.gpg`
Move it to proper directory: 
`mv kubernetes-archive-keyring.gpg /etc/apt/trusted.gpg.d/`
or 
`curl -sS https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg`

3. Add the Kubernetes `apt` repository:
`echo "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list`

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management

I would also not advise people to create `/etc/apt/keyrings`

**Comment by sftim** [comment]
/priority awaiting-more-evidence
/language en
/retitle Instructions for installing `kubectl` on Linux are not correct for Debian

Thanks for suggesting there might be a bug.
Is there documentation for Debian / Ubuntu to substantiate that the current docs are incorrect?

**Comment by fajcikm** [comment]
Hi Tim 
apt-key is deprecated utility since Ubuntu 21.10. please observe manpages https://manpages.ubuntu.com/manpages/impish/man8/apt-key.8.html 
same for the newer versions. https://manpages.ubuntu.com/manpages/jammy/man8/apt-key.8.html
for Debian bullseye https://manpages.debian.org/bullseye/apt/apt-key.8.en.html

The solution I proposed was working on Ubuntu 20.04, 22.04 haven't tried on Debian for me as they changed the way of adding external repositories.

**Comment by sftim** [comment]
The doc at https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management doesn't recommend running `apt-key`. Does anything need fixing?

**Comment by fajcikm** [comment]
Seems no change needed. 
Error  `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY` I observed on Ubuntu 22.04 was caused by obsoleting apt-key on side of Ubunut, which was back then used in installation. 
I solved issue with missing pubkey by proposed solution for install steps on my side. 

My assumption that proposed change can help to prevent such issues since installation was wrong and old way of installation instructions, which back then used `apt-key add -` option are not there anymore for some time already.  

As for now it doesn't much matter if one would downloaded dearmored gpg key into  `/etc/apt/trusted.gpg.d/` instead of creating directory `keyrings`  or create `keyrings` directory and use that. 

As described in Ubuntu  [docu](https://manpages.ubuntu.com/manpages/kinetic/en/man5/sources.list.5.html):
`The recommended locations for keyrings are [/usr/share/keyrings](file:///usr/share/keyrings) for keyrings managed by packages, and /etc/apt/keyrings for keyrings managed by the system operator. If no keyring files are specified the default is the trusted.gpg keyring and all keyrings in the trusted.gpg.d/ directory`

sorry for taking your valuable time you can close/reject this bug.

**Comment by sftim** [comment]
/close

Nothing to fix

BTW, putting keys for Kubernetes into `/etc/apt/trusted.gpg.d` means that you trust Kubernetes to sign any system package (you probably should not).
