### ISSUE TITLE
The description of Service External IPs does not match the YAML example

### ISSUE THREAD

**Issue by dgabrysch** [kubernetes/website#39751]
The yaml has the definition of:

  externalIPs:
    - 198.51.100.32 

But the docs above say:

"my-service" can be accessed by clients on "80.11.12.10:80" (externalIP:port)

Should it not be:

"my-service" can be accessed by clients on "198.51.100.32:80" (externalIP:port)

**Comment by Ritikaa96** [comment]
Hi @dgabrysch , can you please explain some more ? which document page are you referring to and how can we replicate or get this error/bug?

**Comment by Ritikaa96** [comment]
The title is not explanatory of the issue. I'd suggest changing title to explain in brief what issue you are facing/refering to.

**Comment by mengjiao-liu** [comment]
@sftim  PR https://github.com/kubernetes/website/pull/39499 only modified the data in YAML but did not modify the above description. 
```
  externalIPs:
    - 198.51.100.32
```
Is a change to this description missing?

**Comment by mengjiao-liu** [comment]
/retitle The description of Service External IPs does not match the YAML example

**Comment by dgabrysch** [comment]
> I think he's talking about this page:
> https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

You are right 😊

**Comment by dgabrysch** [comment]
> /retitle The description of Service External IPs does not match the YAML example

Thank you, I will try to use a better title next time 😊

**Comment by sftim** [comment]
That could be my bug. Sorry about that.

**Comment by mengjiao-liu** [comment]
Open PR #39768 to fix this issue.
