### ISSUE TITLE
Add new task page: “Running Pods on Only Some Nodes”

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#39766]
**This is a Feature Request**

**What would you like to be added**
Add a new task page: Running Pods on Only Some Nodes

**Why is this needed**
You can set up a DaemonSet that only runs on certain nodes. For example, you have a [device plugin](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) that you need to run on the nodes that have FPGA devices. You also have many more nodes that do not have FPGA hardware, and the device plugin isn't needed on those other nodes.

The task should explain how to do this - https://multinode-kubernetes-cluster.readthedocs.io/en/latest/08-k8s-daemonsets.html has a hint (but we should not copy it verbatim).

**Comments**
Prompted by https://github.com/kubernetes/website/issues/4513
/language en
/help
/kind feature

**Comment by hasanrashid** [comment]
Is this something a first time contributor can take on? I can help

**Comment by sftim** [comment]
You're very welcome to work on this @hasanrashid 

Check out https://kubernetes.io/docs/contribute/

**Comment by Dhairya-Arora01** [comment]
hey @sftim can I start working on this with your help 😊

**Comment by sftim** [comment]
> hey @sftim can I start working on this with your help blush

I'm afraid there are some key issues I'm setting time aside for, and I don't personally have capacity to guide you here @Dhairya-Arora01

**Comment by Dhairya-Arora01** [comment]
No worries @sftim , I will try to work on it

**Comment by Dhairya-Arora01** [comment]
@sftim shouldn't this be added in the config-pod-container section of the tasks

**Comment by sftim** [comment]
I'd put the new task within https://kubernetes.io/docs/tasks/manage-daemon/

If you'd like to, you can add a second new page within https://kubernetes.io/docs/tasks/run-application/ - and have each of the new pages link to the other one. It's fine to do the simpler thing first.

**Comment by vaibhav2107** [comment]
I think this issue is fixed by #39972 and hence we can close this issue
