### ISSUE TITLE
Add a note in the prerequisites section stating that the example image works only with AMD64 architecture

### ISSUE THREAD

**Issue by satyarohith** [kubernetes/website#39798]
https://kubernetes.io/docs/tutorials/services/source-ip/

I'm following the tutorial using minikube on M1 Mac. The `echoserver` image fails with "failed to initialize Lua VM" error and the pod goes into a CrashLoopbackOff state. I couldn't find an `echoserver` image that supports ARM/M1 Mac. We should add a note or update the tutorial with an image that supports both ARM & AMD64.

```
➜  ~ kubectl create deployment source-ip-app --image=registry.k8s.io/echoserver:1.4
deployment.apps/source-ip-app created
➜  ~ kubectl get pods
NAME                             READY   STATUS             RESTARTS      AGE
source-ip-app-5dffb8774f-9tg98   0/1     CrashLoopBackOff   2 (23s ago)   42s
➜  ~ kubectl logs source-ip-app-5dffb8774f-9tg98
2023/03/06 04:52:37 [error] 1#1: failed to initialize Lua VM in /etc/nginx/nginx.conf:54
nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:54
```

**Comment by sftim** [comment]
/retitle Using Source IP tutorial doesn't work on AArch64 architecture
(to be a bit more general)

**Comment by dipesh-rawat** [comment]
Looks like PR #37383 made a doc change to specify multiarch echoserver image in one tutorial page. Also, there is an issue [minikube/15650](https://github.com/kubernetes/minikube/issues/15650) talking about use of different echoserver images used in different places. 

We might need a clean up to specify working echoserver for AArch64 architecture.
/triage accepted

**Comment by sftim** [comment]
Let's either:
- list AMD64 as a prerequisite, and track a separate issue to support other CPUs
- fix this tutorial to work with several CPU architectures, including AMD64 and AArch64

**Comment by divya-mohan0209** [comment]
> Let's either:
> 
> * list AMD64 as a prerequisite, and track a separate issue to support other CPUs
> * fix this tutorial to work with several CPU architectures, including AMD64 and AArch64

+ 1 to the first approach. By listing, we can ensure that users who stumble upon this are able to understand that AMD64 is a prerequisite before going further. Fixing the tutorial for ALL architectures will be a bigger endeavour that would be doable over another issue IMO.

**Comment by haripriya9647** [comment]
Hello @Manish-hr14 i am already working on the issue

**Comment by Manish-hr14** [comment]
> Hello @Manish-hr14 i am already working on the issue

ok go on..

**Comment by Shubham82** [comment]
Closing this issue as a Note is added by PR #44241
/close
