### ISSUE TITLE
[ko] Translate the glossary term 'Service ClusterIP allocation' into Korean

### ISSUE THREAD

**Issue by tonyhan18** [kubernetes/website#39831]
**This is a Feature Request**

**What would you like to be added**

Translate "/en/docs/concepts/service-networking/cluster-ip-allocation.md"
to "/ko/docs/concepts/service-networking/cluster-ip-allocation.md"

**Why is this needed**
Not translated into Korean yet.

**Comments**

EN entry : https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/

/language ko
/assign

**Comment by jihoon-seo** [comment]
@tonyhan18 감사합니다!
/triage accepted
