### ISSUE TITLE
Calico CNI plugging k8s, Page Not Found

### ISSUE THREAD

**Issue by pocheswari** [kubernetes/website#39855]
Hi, I am trying to install calico CNI to my k8s cluster but the same is not available, getting Page Not Found error.
when I searched page:
 https://kubernetes.io/docs/concepts/cluster-administration/addons/#networking-and-network-policy
 under Networking and Network Policy - Calico - also giving page not found error.
request to guide on how to install CNI calico plugging to my k8s cluster.
Is someone having the same issue.

**Comment by sftim** [comment]
See issue 39536

**Comment by dipesh-rawat** [comment]
Changes to address this issue have been merged as part of #39538

/close
