### ISSUE TITLE
one of the link in /docs/concepts/scheduling-eviction/assign-pod-node.md is outdated

### ISSUE THREAD

**Issue by ziyi-xie** [kubernetes/website#39864]
**This is a Feature Request**

**What would you like to be added**

Updated link in the [Assigning Pods to Nodes page](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity-per-scheduling-profile) (The Note part, sorry you may need to scroll down a bit.)

**Why is this needed**
About the heading ID here, the [Assigning Pods to Nodes page](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity-per-scheduling-profile) (The Note part, sorry you may need to scroll down a bit.) is still using `#scheduled-by-default-scheduler` , but `#scheduled-by-default-scheduler` part in [DeamonSet page](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#scheduled-by-default-scheduler) has [been deleted](https://github.com/kubernetes/website/commit/d0b3ba5ccea5138c06ece1ad9f4e4c2b0c5ef897#).
I'm thinking about changing the heading ID to `#how-daemon-pods-are-scheduled ` and could I ask if you think this modification is appropriate or not?

**Comments**

/language en

**Comment by Shubham82** [comment]
Closing this issue, as it was resolved in the following PR: #39936
/close
