### ISSUE TITLE
[ja] Localize en/docs/reference/using-api/deprecation-policy.md

### ISSUE THREAD

**Issue by ystkfujii** [kubernetes/website#39861]
**This is a Feature Request**

Please localize this page to ja text.
```
content/en/docs/reference/using-api/deprecation-policy.md
```

**Comment by Atsushi223** [comment]
@ystkfujii-san, Thank you so much! I'll try this issue.
/assign

**Comment by Okabe-Junya** [comment]
Hi folks!!

It looks no change on this issue for several months, so I remove the assignee. Feel free to re-assign when you work on this issue :)

/unassign @Atsushi223
