### ISSUE TITLE
Add more detail about container images and referencing them by digest

### ISSUE THREAD

**Issue by shirady** [kubernetes/website#39870]
it is written:

> When using image tags, if the image registry were to change the code that the tag on that image represents, you might end up with a mix of Pods running the old and new code. An image digest uniquely identifies a specific version of the image, so Kubernetes runs the same code every time it starts a container with that image name and digest specified. Specifying an image by digest fixes the code that you run so that a change at the registry cannot lead to that mix of versions.

I think you should add relevant links because we have an explanation of how important the use of digest is, so in case we want to use it I would like to have links to for details.

**Comment by utkarsh-singh1** [comment]
Related Doc - https://kubernetes.io/docs/concepts/containers/images/

/sig docs
/language en

**Comment by utkarsh-singh1** [comment]
Hi @shirady, There are links ([ink1](https://cloud.google.com/kubernetes-engine/docs/archive/using-container-images) and [link2](https://cloud.google.com/kubernetes-engine/docs/archive/using-container-image-digests-in-kubernetes-manifests)) that describe image digests, but it would be better if Kubernetes website has its own blog about image digests that can linked to the Image documentation.

**Comment by shirady** [comment]
@utkarsh-singh1, the [first link](https://cloud.google.com/kubernetes-engine/docs/archive/using-container-images) describes well the image digest. I think such content should also appear in the documentation of k8s.

**Comment by utkarsh-singh1** [comment]
Hi @shirady, As image digest is quite important topic to have so short description is not a good option, instead we should have a blog on image digest that can well explain about it with examples.

**Comment by sftim** [comment]
Whilst a blog article is helpful, it's even more important to explain this within the docs themselves.

**Comment by KhushPatibandha** [comment]
Hey, so basically you want to add a topic describing 'image digest' in docs/concepts/containers/images ?

**Comment by sftim** [comment]
> basically you want to add a topic describing 'image digest' in docs/concepts/containers/images ?

I think that would help.

**Comment by KhushPatibandha** [comment]
Sure I'll look into it.

**Comment by KhushPatibandha** [comment]
@sftim Is it allowed to add [link](https://cloud.google.com/kubernetes-engine/docs/archive/using-container-images) to our documentation after explaining? or if that's not a good practice.

**Comment by utkarsh-singh1** [comment]
Hey @KhushPatibandha, This link seems to be a 3rd party link , but i don't think so it would be a problem because that belongs to google cloud. But it would be better if we have clear explaination of `image digest` here.

**Comment by sergeyshevch** [comment]
/close 
Covered with examples in #45788
