### ISSUE TITLE
“Define Environment Variables for a Container” does not explain `env` vs `envFrom`

### ISSUE THREAD

**Issue by shirady** [kubernetes/website#39873]
It is written:

> To set environment variables, include the env or envFrom field in the configuration file.

There is no more information about the difference between `env` and `envFrom` (or even links to read about it).

**Comment by sftim** [comment]
Page: https://k8s.io/docs/tasks/inject-data-application/define-environment-variable-container/

/retitle “Define Environment Variables for a Container” does not explain `env` vs `envFrom`
/language en

**Comment by sftim** [comment]
This is valuable feedback @shirady - if you spot other places we could improve, please consider filing an issue for each of those.

**Comment by nate-double-u** [comment]
Fixed in https://github.com/kubernetes/website/pull/40055

/close
