### ISSUE TITLE
Add way to dismiss banners in the K8s website

### ISSUE THREAD

**Issue by AntonioND** [kubernetes/website#39887]
**This is a Feature Request**

The red banner introduced with https://github.com/kubernetes/website/pull/39575 is too intrusive. Most Kubernetes users don't actually care about this deadline, and there is no way to dismiss it.

**What would you like to be added**

A simple "dismiss" button that sets a cookie to hide the banner in any future visit, like other websites do.

**Why is this needed**

I'd argue that most users of the website just want to read the documentation, they aren't going to submit images to that registry, so the warning isn't useful.

**Comments**

This could be reused for future banners.

**Comment by sftim** [comment]
/retitle Add way to dismiss banners in the K8s website

We would implement this for all banners, not just red ones.

**Comment by dims** [comment]
@AntonioND oh boy! are you in for a ride!!

**Comment by dims** [comment]
xref: https://github.com/kubernetes/k8s.io/issues/4872

also, here's how i deal with papercuts on the web - https://userstyles.org/help/stylish_chrome

**Comment by XDRAGON2002** [comment]
> /retitle Add way to dismiss banners in the K8s website
> 
> We would implement this for all banners, not just red ones.

Which all banners are you referring to? I'd be willing to take this up.

**Comment by sftim** [comment]
There's a banner displayed now, it looks like this:
![Banner screenshot](https://user-images.githubusercontent.com/22591623/225404131-e92a46fb-6369-490a-8e51-b09dba5b85db.png)

Imagine if you could click to acknowledge that you'd read it and didn't want to see it again for a fortnight.

(separately: https://github.com/kubernetes/website/issues/39887#issuecomment-1463676947 does feel relevant - @AntonioND ruled out taking action as they don't plan to push a container image there, which I think reveals a misunderstanding. I think it's worth repeating banners every couple of weeks in case it helps a message to land better).

**Comment by BenTheElder** [comment]
> [...] which I think reveals a misunderstanding. [...]

Which ...To clarify for anyone reading: This banner applies to *pulling* / downloading container images from the Kubernetes project, this banner is aimed at users, not Kubernetes developers. **Nobody** can push directly to either of these hosts and the change isn't related to pushing / submitting images.

**Comment by XDRAGON2002** [comment]
Thanks @sftim and @BenTheElder for the explanation!
I'll take this up and try to resolve this.

/assign

**Comment by KhushPatibandha** [comment]
@XDRAGON2002 are you working on this issue? I would like to help if you want. Do let me know.

**Comment by XDRAGON2002** [comment]
Yes, @KhushPatibandha I'm working on this still, mostly it's completed already, but thanks for the offer!

**Comment by mtilson** [comment]
@KhushPatibandha 
As XDRAGON2002 seems is evaded, could you please proceed?

**Comment by Gauravpadam** [comment]
I'll help with this, it seems like a good feature
