### ISSUE TITLE
 Broken link in blog 2018 

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#39908]
This is a Bug Report

Problem:
Link for Multi-Cluster Service DNS with ExternalDNS guide in https://kubernetes.io/blog/2018/12/12/kubernetes-federation-evolution/ is broken

Proposed Solution:
Should be updated with correct link
Page to Update:
https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2018-12-11-Kubernetes-Federation-Evolution.md

**Comment by NitishKumar06** [comment]
Hi, @AtriChatterjee1 we know that you're excited to put forward your contribution - Thank you! However, I see that @niranjandarshann assigned this issue prior to you. Please refrain from self-assigning an issue if you see someone else already being assigned. There are a lot of other issues to be worked on as well.

**Comment by AtriChatterjee1** [comment]
Sorry , will keep in mind next time @NitishKumar06

**Comment by dipesh-rawat** [comment]
PR #39910 is opened to address this issue.

**Comment by niranjandarshann** [comment]
closing this issue marking it as resolved in PR #39910 
/close
