### ISSUE TITLE
Issue with /docs/getting-started-guides/vsphere/

### ISSUE THREAD

**Issue by g1001p** [kubernetes/website#3990]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
vsphere provider template contains only  one entry for datastore.
How to manage more than one datastore using this template?
[Global]
        user = "${username}"
        password = "${password}"
        server = "${vsphere_server}"
        port = "${port}"
        insecure-flag = "${allow_unverified_ssl}"
        datacenter = "${datacenter}"
        datastore = "${datastore}"
        working-dir = "${working_dir}"
[Disk]
	scsicontrollertype = pvscsi
**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

 1.4 and 1.5

**Comment by ahmetb** [comment]
authors cc: @erictune @jbeda

**Comment by zacharysarah** [comment]
@erictune @jbeda 👋 Any updates here?
