### ISSUE TITLE
Unclear glossary entry for Event

### ISSUE THREAD

**Issue by shirady** [kubernetes/website#39931]
This is the first line of `Event` in the glossary, I don't think it is clear:

> Each Event is a report of an event somewhere in the [cluster](https://kubernetes.io/docs/reference/glossary/?all=true#term-cluster).

**Comment by dipesh-rawat** [comment]
Page: https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-event

/language en

**Comment by KhushPatibandha** [comment]
@Sheetalpamecha are you still pursuing this issue?

**Comment by sftim** [comment]
/priority backlog
/triage accepted

**I am happy to see this issue rot out if it turns out that we do not have capacity to fix it**

**Comment by KhushPatibandha** [comment]
since @Sheetalpamecha is not responding I would like to take this up and do a little re-work for the glossary entry "Event"
/assign

**Comment by divya-mohan0209** [comment]
We would also need to change it in the reference documentation, I believe, on this page - https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/
