### ISSUE TITLE
Glossary entry for kubectl also includes lower-case version of name

### ISSUE THREAD

**Issue by shirady** [kubernetes/website#39932]
> Kubectl
Also known as:_kubectl_

it doesn't make sense...

**Comment by dipesh-rawat** [comment]
Page: https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-kubectl

/language en

**Comment by NitishKumar06** [comment]
We can remove this line _Also known as:kubectl_ and instead add it something like:

Kubectl (or _kubectl_): ...............

WDYT?

**Comment by shirady** [comment]
> We can remove this line _Also known as:kubectl_ and instead add it something like:
> 
> Kubectl (or _kubectl_): ...............
> 
> WDYT?

Kubectl (or _kubectl_): ...............
@NitishKumar06 I think it is a better option.

**Comment by sftim** [comment]
I think it's fine to have all-lower case `kubectl` as an alternative name. I wouldn't change anything here.

If we need to add an explanation about why we're listing both capitalizations, we can add that (but I personally see no need).

**Comment by NitishKumar06** [comment]
> I think it's fine to have all-lower case `kubectl` as an alternative name. I wouldn't change anything here.
> 
> If we need to add an explanation about why we're listing both capitalizations, we can add that (but I personally see no need).

IMO _Also known as: kubectl_ doesn't make sense, especially including 'Also known as'.

**Comment by KhushPatibandha** [comment]
@SaumyaBhushan you still working on this ?

**Comment by KhushPatibandha** [comment]
[kubernetes-api](https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-kubernetes-api) also have a `aka`  attribute in the file but it dont show up on the glossary. why is that?

**Comment by shirady** [comment]
@SaumyaBhushan it is a minor change? can we fix it?
