### ISSUE TITLE
Add redirect for /docs/user-guide/*

### ISSUE THREAD

**Issue by xgp01** [kubernetes/website#39953]
fix issue https://github.com/kubernetes/kubernetes/issues/116449

**Comment by sftim** [comment]
This would revert https://github.com/kubernetes/website/pull/39143

**Comment by sftim** [comment]
I don't think we realised how many stale links existed in-tree. We could put back the redirection and also fix Kubernetes to link to the newer URLs.

After a few years - maybe 3 - we could drop the old redirects again.

**Comment by sftim** [comment]
Since some of the most recent patch releases of Kubernetes reference the old links, I think we should reinstate them.

Thanks for submitting https://github.com/kubernetes/website/pull/39954 @xgp01 

/triage accepted
