### ISSUE TITLE
Provide more context for example audit configuration

### ISSUE THREAD

**Issue by nathanielkohl83** [kubernetes/website#39968]
This [documentation page](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/) outlines the process for enabling audit rules and gives an example template for several audit rules. My concern is whether or not, when establishing a "catch-all" rule such as the one listed on the page, and pasted below, one should include the `omitStages:` field as seen below, or if that is unnecessary.

```
  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"
```

**Comment by sftim** [comment]
The page states:
> You can use a minimal audit policy file to log all requests at the Metadata level:
>
> ```yaml
> # Log all requests at the Metadata level.
> apiVersion: audit.k8s.io/v1
> kind: Policy
> rules:
> - level: Metadata
> ```

Do we need to clarify further?

**Comment by nathanielkohl83** [comment]
Thank you for the comment. The part of the documentation that I, and I believe a few others, are unclear on, is above the section you cited, where there is a comment on the "omitStages" field...
```
    # Long-running requests like watches that fall under this rule will not
    # generate an audit event in RequestReceived.
    omitStages:
      - "RequestReceived"
```
Could the above comment be clarified a bit? Why does the text single out "watch" requests when presumably any request would be subject to this rule, and why do you want to avoid the "RequestReceived" stage in this particular example, when the overall rule is identified as a general "catch-all"?

**Comment by sftim** [comment]
It sounds like you'd like a more detailed outline of the (imagined) intent behind the example audit policy. Have I got that right?

**Comment by nathanielkohl83** [comment]
Yes, that sums it up!

**Comment by sftim** [comment]
/retitle Provide more context for example audit configuration
/kind feature
