### ISSUE TITLE
Document feature gate lookup

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#39963]
**This is a Feature Request**

**What would you like to be added**

1. Per https://github.com/kubernetes/kubernetes/issues/87869#issuecomment-1465634605 you can find out which feature gates are enabled _for the API server_ using an HTTP request.
2. The other option is to look at mirror pods and DaemonSets to see what command line options and configuration files are being used.
   - where config files are mounted from the control plane nodes, you may need to look there
   - this is what you'd do to see feature gates for `kube-proxy` (for example) - there's no API providing that in core Kubernetes and I don't think the metrics for kube-proxy are as easy to access.

**Why is this needed**
People working with Kubernetes want to know what features their cluster provides.
It can be hard to work out what feature gates are enabled, especially if you don't have superuser access to the control plane.

**Comments**
/language en
/kind feature

**Comment by Pradumnasaraf** [comment]
triage/accepted

**Comment by pacoxu** [comment]
BTW, I am thinking about adding a json or table feed for https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/ and https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/. Then users can easily get if a feature gate is enabled in a kube version.(It may be removed after GAed) 

This request is like the https://kubernetes.io/docs/reference/issues-security/official-cve-feed/.

**Comment by sftim** [comment]
@pacoxu, you might like to reopen https://github.com/kubernetes/website/issues/25645 as a related task
