### ISSUE TITLE
play with kubernetes it not working

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#40013]
**Problem:**

The website http://labs.play-with-k8s.com/ is down mentioned as [Play with Kubernetes](http://labs.play-with-k8s.com/) in multiple pages

**Comment by sftim** [comment]
I suspect there's nothing to fix. You can learn Kubernetes by installing it locally, or by using a different learning sandbox that's not broken. I'm guessing that http://labs.play-with-k8s.com/ will come back.

If https://labs.play-with-k8s.com/ is permanently not available, we should stop linking to it. Do you know whether it's just down short term, or long term @AmarNathChary ?

If you know it's a short term problem, you could report this to their issue tracker which I believe is as https://github.com/play-with-docker/play-with-kubernetes.github.io/issues/

/language en

**Comment by mengjiao-liu** [comment]
This issue has been reported in https://github.com/play-with-docker/play-with-kubernetes.github.io/issues/62

Looks like this link hasn't been working for 2 months.

**Comment by AmarNathChary** [comment]
> If https://labs.play-with-k8s.com/ is permanently not available, we should stop linking to it. Do you know whether it's just down short term, or long term @AmarNathChary?

I recently observed the link is not working. I am not sure whether it's just down short-term or long-term by referring to the comments related to this issue we can it could be long-term.

**Comment by sftim** [comment]
Let's check back in a week. If it's still broken on Monday, that's grounds for dropping our links to it.

**Comment by afbjorklund** [comment]
It works for me, and it was mentioned as an alternative for Katacoda replacement in the GitHub discussion ?

* https://github.com/kubernetes/website/discussions/38878#discussioncomment-4974832

It uses a legacy OS (CentOS 7) and an old Kubernetes (1.20.1), but it is not much worse than the current tutorials.

@marcosnils

**Comment by gertsog333** [comment]
http://labs.play-with-k8s.com/ Still down((
Please turn it back

**Comment by sftim** [comment]
> try to ping all pages with it

Really don't do that - remember, we hope that you would follow the spirit of the [contributor covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).

**Comment by gertsog333** [comment]
Sorry.
Will switch to https://github.com/play-with-docker/play-with-kubernetes.github.io/issues/67

**Comment by Bikash-Debnath** [comment]
http://labs.play-with-k8s.com/ is down

**Comment by Bikash-Debnath** [comment]
> should be ok now

Yeah Working absolutely fine, Thank You!

**Comment by ash-gandhi19** [comment]
https://labs.play-with-k8s.com  is down....

**Comment by marcosnils** [comment]
> https://labs.play-with-k8s.com is down....

should be working now

**Comment by Crowley14** [comment]
Hello
Is it still down ? Nothing happen when I click on "add new instance"

**Comment by marcosnils** [comment]
> Hello Is it still down ? Nothing happen when I click on "add new instance"

No. Seems to work here: 

![image](https://github.com/user-attachments/assets/b32cd998-7bc5-4ea1-a643-049c2fa13c02)

**Comment by AmarNathChary** [comment]
> Hello
> 
> Is it still down ? Nothing happen when I click on "add new instance"

It seem like its getting down some times but not very often

**Comment by marcosnils** [comment]
try now please

**Comment by sophia-aaa** [comment]
Thanks a lot. It works!

**Comment by LionKing82** [comment]
Can you please check its still down

**Comment by mastanvali2600** [comment]
Same problem for it is not creating instance

**Comment by barth007** [comment]
same problem for me it is not creating instance

**Comment by manpreets** [comment]
Clicking on 'Add new instance' causes a console error as - 
 xhr.send(isUndefined(post) ? null : post); - 
angular.js:11756   -   POST https://labs.play-with-k8s.com/sessions/d0q2tqgi7hog00a56p70/instances 500 (Internal Server Error)

**Comment by ZhikharevN** [comment]
same problem for me it is not creating instance

**Comment by vishalcloud** [comment]
@marcosnils It's down again, can we take it up? Thanks!

**Comment by OksiBlack** [comment]
> Clicking on 'Add new instance' causes a console error as - xhr.send(isUndefined(post) ? null : post); - angular.js:11756 - POST https://labs.play-with-k8s.com/sessions/d0q2tqgi7hog00a56p70/instances 500 (Internal Server Error)

same for me

**Comment by fengz63** [comment]
I also have the problem. When I click `ADD NEW INSTANCE`, there is no instance created.

![Image](https://github.com/user-attachments/assets/023f0481-5477-4cfb-99d2-8ddee9d1474b)

**Comment by biswajitq98** [comment]
use killercoda
