### ISSUE TITLE
Broken link in Feature Highlight: CPU Manager page

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#40036]
**This is a Bug Report**
**Problem:**
There is a broken links inside page [Feature Highlight: CPU Manager](https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/) under [Performance Isolation for Stand-Alone Workloads](https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/#performance-isolation-for-stand-alone-workloads) section.

**Proposed Solution:**
Update the following broken links with the correct links. [wide and deep](https://github.com/tensorflow/models/tree/master/official/r1/wide_deep) and [ResNet](https://github.com/tensorflow/models/tree/master/official/r1/resnet).

**Page to Update:**
https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/

**Comment by sftim** [comment]
We maintain blog articles for up to one year. After a further year, we  deprioritize fixes.

With that in mind:
/close not-planned
