### ISSUE TITLE
Broken link in Secret concept

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#40042]
In [Secret](https://kubernetes.io/docs/concepts/configuration/secret/) under  `Editing a Secret` where [Mounted Secrets are updated automatically](https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically) link does not refer to this topic. it is referring to the whole Secret page again.

**Comment by sftim** [comment]
/kind bug

I think the section we _should_ now link to is https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

Some other pages have links to https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically which, ideally, we also fix.

**Comment by rghdrizzle** [comment]
Hey I would like to work on this , can u provide the path for the file in which the issue exists ?

**Comment by NitishKumar06** [comment]
> Hey @NitishKumar06 I would like to work on this , can u provide the path for the file in which the issue exists ?

Thanks for taking this up! You can make research on your own. However, here are few points that you can keep in mind:

1. Observe the endpoints of the link of page you'd like to modify. This has almost the answer to your question.
2. For future references (considering this issue as well), you can use [Hound](https://cs.k8s.io/) for tracking the file that needs to be modified.

**Comment by sftim** [comment]
/triage accepted

(BTW, folks, avoid marking things as good first issues unless they are also triaged accepted)

Another aside:
&nbsp;We mark things as good first issues when we know we - _someone_ from SIG Docs - have capacity to support newcomers working on them.
&nbsp;If you're not sure the capacity is there and you can't provide that yourself, be wary of adding the marker.

**Comment by rghdrizzle** [comment]
@NitishKumar06 do I have to change the link to #using-secrets-as-files-from-a-pod section ?

**Comment by ashutosh887** [comment]
I would like to work on this Issue @NitishKumar06 
/assign

**Comment by AmarNathChary** [comment]
Hi, @ashutosh887 thanks for your interest that want to contribute to this issue but a PR has already been raised for this issue by @rghdrizzle

**Comment by NitishKumar06** [comment]
> Hi, @ashutosh887 thanks for your interest that want to contribute to this issue but a PR has already been raised for this issue by @rghdrizzle

Can you share the link to that PR?

**Comment by NitishKumar06** [comment]
Meanwhile @ashutosh887 Please refrain from assigning that issue to yourself that is already been assigned to someone. You can always ask the assignee if he/she needs some help with it.

**Comment by NitishKumar06** [comment]
Since @rghdrizzle is already assigned for this issue, @ashutosh887 Please start working on some other issue where no one is working. However, this is not always true - you can always ask the assignee if he/she needs help. 
/unassign @ashutosh887

**Comment by AmarNathChary** [comment]
Hi @ayushpatil2122 a PR has been raised for this issue and got merged in #40103

**Comment by AmarNathChary** [comment]
I think the issue needs to be closed now
