### ISSUE TITLE
Cannot view source code for sample on k8s website - source tree closes every few seconds. Please provide a github link.

### ISSUE THREAD

**Issue by 1dropaflame** [kubernetes/website#40049]
**This is a Bug Report**

**Problem:**
[Interactive Tutorial - Configuring a Java Microservice | Kubernetes](https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/)

I am learning k8s and want to understand the example above, but the online editor is very hard to use.
Cannot view source code for sample - source tree closes every few seconds. It is also a complex sample. 

Can I do a git clone on it? But I do not know where it is located.
**Proposed Solution:**
Please provide a github link.
If I can open it in my IDE I will be able to study and understand the code.

**Page to Update:**
https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/

**Comment by sftim** [comment]
Hi @1dropaflame, as the KataKoda environment for Kubernetes will be shutting down at the end of month, we are not likey to work on this.

See https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/

You are welcome to look at the code within https://github.com/kubernetes/website and https://github.com/katacoda-scenarios to find what details you can.

/triage unresolved
/close not-planned

**Comment by 1dropaflame** [comment]
[@sftim](https://github.com/sftim)
Tim and others,

Please do not delete the tutorials. They are very useful.
In fact, I performed the same operations on a small personal project.
Instead, modify them slightly so that others can do the same. 
I was able to follow along using my local setup (WSL2, Docker Desktop, minikube).

The only place where I had trouble was at this afore mentioned spot. 
If a link to this code sample is put in the tutorial, we will be able to follow along.

**Comment by sftim** [comment]
If there are trivial minor changes to keep an existing tutorial, we'll do that.

We're larger changes are needed to continue serving the tutorial, whether we have capacity to keep them depends on the level of effort that volunteers are able to make. Pull requests are welcome.

**Comment by 1dropaflame** [comment]
@Tim
thanks for the links but looking through them,
I am trying to find the source code shown in the directory tree (pls see screenshot)
https://github.com/kubernetes/website/tree/main/content/en/examples/configmap
I am unable to find it.
![image](https://user-images.githubusercontent.com/52415475/226356610-9c60ba39-112d-4d43-9ab4-d1d2270b2f5a.png)
