### ISSUE TITLE
Annotation `kubectl.kubernetes.io/restartedAt` not registered / documented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#40067]
**This is a Bug Report**

**Problem:**
Kubernetes defined an annotation, `kubectl.kubernetes.io/restartedAt`. For example, this annotation is set during rolling restarts.

That annotation is unregistered because it doesn't appear inside https://kubernetes.io/docs/reference/labels-annotations-taints/

**Proposed Solution:**
Register the annotation, by documenting it in&hellip;

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig architecture
/sig cli
/language en

**Comment by T-Lakshmi** [comment]
I am happy to work on this issue once triage accepted, thanks.

**Comment by T-Lakshmi** [comment]
Unassigning myself as PR is already raised by @Biswajit-Mohapatra2 #40431

**Comment by T-Lakshmi** [comment]
PR that is working on this issue #41348.

**Comment by sftim** [comment]
PRs to fix this are welcome. @Biswajit-Mohapatra2, what are your plans for #41348?

**Comment by Ritikaa96** [comment]
Is @Biswajit-Mohapatra2 still working on this PR?

**Comment by Ritikaa96** [comment]
How about this 
```Markdown
### kubectl.kubernetes.io/restartedAt {#kubectl-k8s-io-restart-at}

Type: Annotation

Example: kubectl.kubernetes.io/restartedAt: "2024-06-21T17:27:41Z"

Used on: Pod

This annotation contains the latest restart time of a resource(Deployment, ReplicaSet, StatefulSet or DaemonSet).
The command `kubectl rollout restart <RESOURCE>` triggers a restart by patching the template
metadata of all the pods of resource with this annotation. You can also trigger a restart by manually
setting or changing the value of this annotation. In above example the latest restart time of resource is shown as 21st Jun 2024 17:27:41 GMT.
```

**Comment by Ritikaa96** [comment]
Let me know if no one's working on the issue currently then i can raise this PR. I already have this in my local branch

**Comment by sftim** [comment]
@Ritikaa96 a PR is welcome if you have code for it, nearly always. It's also polite to try to liaise with anyone else who's mentioned that they plan to do work on the same issue.

In this case, you can see things have gone quiet. Opening a PR here can't reasonably be seen as thoughtlessly barging in.

**Comment by Ritikaa96** [comment]
Thanks for confirmation @sftim .

**Comment by Ritikaa96** [comment]
Raised the PR https://github.com/kubernetes/website/pull/47064 for this annotation, please take a look. I'll be happy to improve it based on your reviews.
