### ISSUE TITLE
Broken link in blog: k8s.gcr.io Redirect to registry.k8s.io - What You Need to Know

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#40071]
This is a Bug Report

Problem:
Link for kubernetes-sigs/community-images :- https://github.com/kubernetes-sigs/community-image is broken under the blog named as k8s.gcr.io Redirect to registry.k8s.io - What You Need to Know having  Topic  How can I find which images are using the legacy registry, and fix them? under option 2. (For alternate methods of install and example output, check out the repo: kubernetes-sigs/community-images).

Proposed Solution:
Should be updated with correct link
Page to Update:
https://kubernetes.io/blog/2023/03/10/image-registry-redirect/

**Comment by T-Lakshmi** [comment]
Hi @niranjandarshann,

> https://github.com/kubernetes-sigs/community-image is broken under the blog named as k8s.gcr.io Redirect to registry.k8s.io

Are you talking about reference link below mentioned as `community-images`? if yes, It seems the url you are checking is wrong.  I could able to open this link properly.
https://github.com/kubernetes-sigs/community-images#kubectl-community-images
Please recheck once again.

**Comment by niranjandarshann** [comment]
\

> Hi @niranjandarshann,
> 
> > https://github.com/kubernetes-sigs/community-image is broken under the blog named as k8s.gcr.io Redirect to registry.k8s.io
> 
> Are you talking about reference link below mentioned as `community-images`? if yes, It seems the url you are checking is wrong. I could able to open this link properly. https://github.com/kubernetes-sigs/community-images#kubectl-community-images Please recheck once again.

Hello @T-Lakshmi 
The whole sentence the community-images in sentence ( For alternate methods of install and example output, check out the repo: kubernetes-sigs/community-images) is broken. Last line of Option 2.

**Comment by mengjiao-liu** [comment]
/triage accepted

I think the link is incorrect and the character `s` is missing.

 https://github.com/kubernetes-sigs/community-image -> https://github.com/kubernetes-sigs/community-images

**Comment by mengjiao-liu** [comment]
Do you want to fix this? You can assign this issue to yourself.

**Comment by niranjandarshann** [comment]
> Do you want to fix this? You can assign this issue to yourself.
yes i want to work on it but the repository  named image redirect  is not visible in the kubernetes/website github  account on which i can update it. Can you please provide me the path of image redirect.

**Comment by niranjandarshann** [comment]
> Do you want to fix this? You can assign this issue to yourself.

Yes i want to work on it but the image redirect repository is not visible in  the github account ( kubernetes/website). Can provide me the path?

**Comment by mengjiao-liu** [comment]
![image](https://user-images.githubusercontent.com/44460091/225842098-707fabe2-c723-425c-be3d-ad97ebbaf131.png)
If I understand you correctly, do you want the correct address for this link?

The correct address is: https://github.com/kubernetes-sigs/community-images

**Comment by niranjandarshann** [comment]
> ![image](https://user-images.githubusercontent.com/44460091/225842098-707fabe2-c723-425c-be3d-ad97ebbaf131.png) If I understand you correctly, do you want the correct address for this link?
> 
> The correct address is: https://github.com/kubernetes-sigs/community-images

yes

**Comment by mengjiao-liu** [comment]
/retitle Broken ink in blog: k8s.gcr.io Redirect to registry.k8s.io - What You Need to Know

**Comment by mengjiao-liu** [comment]
/retitle Broken link in blog: k8s.gcr.io Redirect to registry.k8s.io - What You Need to Know

**Comment by sftim** [comment]
/good-first-issue
/close

Done in #40082
