### ISSUE TITLE
Node-specific Volume Limits -> IBM CLOUD

### ISSUE THREAD

**Issue by heyfrancisco** [kubernetes/website#40088]
Hi team,

Regarding the Kubernetes default limits table which includes AWS, Azure and GCP, I would like to suggest adding **IBM Cloud** as well. 

At this current moment, the maximum amount of volumes attached per worker node on IKS on IBM Cloud is 12 volumes. This information can be found on the [Kubernetes Service documentation](https://cloud.ibm.com/docs/containers?topic=containers-limitations#vpc_gen2_storage_limit). Following this link and clicking on [Volume attachment limits](https://cloud.ibm.com/docs/vpc?topic=vpc-attaching-block-storage#vol-attach-limits) we can read the following:

> You can attach only one Block Storage for VPC boot volume to a virtual server instance at a time, but you can attach up to 12 Block Storage for VPC data volumes to a single instance.

This information is for Kubernetes Services running on Virtual Private Cloud.

**Comment by sftim** [comment]
Which web page do you think is wrong @heyfrancisco? I think this is https://kubernetes.io/docs/concepts/storage/storage-limits/

If there is an in-tree limit for a legacy storage integration, we can document it. If that's out-of-tree (IBM's own code), then documenting that on IBM's website is the right thing to do.

Separately, we ought to update https://kubernetes.io/docs/concepts/storage/storage-limits/ to make it clear that CSI storage drivers are the approach we recommend, and that in-tree drivers are the old way that people should avoid using.


/language en

/priority awaiting-more-evidence

**Comment by heyfrancisco** [comment]
Yes, the webpage I think could be updated is: https://kubernetes.io/docs/concepts/storage/storage-limits/, more specifically adding IBM Cloud to the list of cloud providers.

In IBM Cloud the default limit of volumes of block storage per worker node (on vpc) is 12 volumes.
