### ISSUE TITLE
[hi] Localize index for Concepts section into Hindi

### ISSUE THREAD

**Issue by Kanika637** [kubernetes/website#40095]
**This is a Bug Report**

**Problem:**
- When we choose the Hindi version of the documentation, the word “Concepts” is still in English language.

![Screenshot_20230317_202326](https://user-images.githubusercontent.com/84350895/225940588-6dae113c-9beb-44c1-a167-e8c112d9bb09.png)

- When we click on the Concepts from the sidebar, it redirects to an English version of the documentation and not Hindi.

![image](https://user-images.githubusercontent.com/84350895/225940953-805a6c43-3505-4571-b8a0-0857ab2bfa07.png)

**Proposed Solution:**

- I will change the word “Concepts” written in English to Hindi.
- Since there is no English translation of the Concepts page, I will translate the page of “Concepts” to Hindi and will include the language in the list.

**Page to Update:**
https://kubernetes.io/hi/docs/home/
https://kubernetes.io/docs/concepts/

I want to work on this issue.
/assign

**Comment by NitishKumar06** [comment]
Hi @Kanika637 thanks for reporting this! Please proceed with raising a PR for this issue by self-assigning.

**Comment by NitishKumar06** [comment]
> /language hi
> 
> This is a duplicate of issue #29353

I think the issue you've mentioned deals more with the translation of the existing content to keep track of. I'm not sure how the current issue is a duplicate of the issue you mentioned above. Can you explain more?

**Comment by sftim** [comment]
/retitle [hi] Localize index for Concepts section into Hindi
/remove-triage duplicate
/kind feature
/kind bug

How about this?

**Comment by Kanika637** [comment]
Yes that's great @sftim, will make a PR for this respective work.
@NitishKumar06

**Comment by Kanika637** [comment]
After researching for a good time on the whole issue, I have come to a conclusion that:

-> The “Concepts” is written in English in the Hindi translated documentation because, there is a need of translation of all the topics under concepts  which includes “Overview”, “Cluster Architecture”, “Containers” etc. as the index.md file of each component in the sidebar handles the translation.

-> And the concepts component is basically empty, with just an “Overview” as sen in the code.

-> Without the translation of all ( “Overview”, “Cluster Architecture”, “Containers” etc.) these, the “Concepts” cannot be corrected. 

And unfortunately, I am not able to do this on my own :(

**Comment by sftim** [comment]
Would be great to see https://kubernetes.io/hi/docs/concepts/ added. Would anyone like help with this?

**Comment by sftim** [comment]
Done in #39569

/close
