### ISSUE TITLE
Add more details about tools to help contributor workflow

### ISSUE THREAD

**Issue by nitishfy** [kubernetes/website#40094]
**This is a Feature Request**

New beginners often ask questions like _Where do I get the file path to solve this issue?_. Not only this, there are various tools that Kubernetes offers which can be used to enhance productivity while contributing to K8s that have been mentioned [here](https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README.md#workflow). This would make more sense if we could mention or provide a reference/mention about the tools in [CONTRIBUTING.md](https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md).

**What would you like to be added**
Provide a reference text/mention the tools.

**Comment by sftim** [comment]
/language en

I don't understand what's missing here.

**Comment by NitishKumar06** [comment]
> /language en
> 
> I don't understand what's missing here.

There is no reference to the workflow tools like [Hound](https://cs.k8s.io/), [PR dashboard](https://k8s-gubernator.appspot.com/pr) which can be useful for contributing. It can be better if we could provide a referenced link to those workflow tools. WDYT?

**Comment by sftim** [comment]
These would be best documented within https://k8s.dev/ @NitishKumar06 (our documentation aimed at Kubernetes contributors)

**Comment by sftim** [comment]
/retitle Add more details about tools to help contributor workflow
/priority awaiting-more-evidence

If you want, we can transfer this issue to https://github.com/kubernetes/contributor-site @NitishKumar06

**Comment by sftim** [comment]
I am definitely OK with the idea that https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md gains some new links to pages within https://k8s.dev/

**Comment by NitishKumar06** [comment]
> I am definitely OK with the idea that https://github.com/kubernetes/website/blob/main/CONTRIBUTING.md gains some new links to pages within https://k8s.dev/

How about giving the label `triage/accepted`? Or Is there anything you'd like to discuss more before proceeding further?

**Comment by sftim** [comment]
I don't understand how to tell when this issue is done. In other words, how does someone who has worked on it know what is missing, so they can add it?

**Comment by NitishKumar06** [comment]
> I don't understand how to tell when this issue is done. In other words, how does someone who has worked on it know what is missing, so they can add it?

I think once the tools have been mentioned a contributor is using, we can raise a  PR for the same. Furthermore, we can ask the community members what more tools they generally use that could be beneficial for the contributors.

**Comment by sftim** [comment]
OK, well personally I mainly use `vim`. Not sure I'd recommend it to a contributor who doesn't already have it as their preference.
I also use `git` and `hugo`.
