### ISSUE TITLE
Duplicate paragraphs in tutorials/services/pods-and-endpoint-termination-flow

### ISSUE THREAD

**Issue by kmuto** [kubernetes/website#40127]
**This is a Bug Report**

Hi, I saw "Explore Termination Behavior for Pods And Their Endpoints" document to translate, and noticed there were duplicate paragraphs. 

**Problem:**

From 2nd-3rd paragraphs of https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/ :

```
...a proper active connections draining. This tutorial explains the flow of Pod termination in connection with the corresponding endpoint state and removal.

This tutorial explains the flow of Pod termination in connection with the corresponding endpoint state and removal by using a simple nginx web server to demonstrate the concept.
```

The first sentence appears to be a forget to remove.

**Proposed Solution:**

Remove the first sentence.

```
...a proper active connections draining.

This tutorial explains the flow of Pod termination in connection with the corresponding endpoint state and removal by using a simple nginx web server to demonstrate the concept.
```

**Page to Update:**
https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/

**Comment by dipesh-rawat** [comment]
The doc [section](https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/#termination-process-for-pods-and-their-endpoints) mentioned in the issue does indeed have duplicate lines that need cleaning up.

/language en
/triage accepted

**Comment by hasanrashid** [comment]
I'd like to work on this

**Comment by mengjiao-liu** [comment]
PR #40142 has been merged. Please feel free to open this issue if you have any questions.
/close
