### ISSUE TITLE
Blog article summaries typically include author details text

### ISSUE THREAD

**Issue by craigbox** [kubernetes/website#40175]
By convention, the source for a Kubernetes blog post begins with the author/s listed in the first line of body text. 

<img width="1156" alt="Screenshot 2023-03-21 at 4 01 28 PM" src="https://user-images.githubusercontent.com/132510/226508413-be5d7bdf-7ec5-485d-8884-5f976443dd89.png">

This causes output on the summary page to look disjointed — there is no demarcation between the author name and the start of the text — or, in the case of posts with many authors, you may not see a summary of the post at all.

<img width="1152" alt="Screenshot 2023-03-21 at 3 53 41 PM" src="https://user-images.githubusercontent.com/132510/226507666-0566d4be-cc73-4e76-b971-61aa817e9848.png">

A proper fix would be to move the authors to metadata in the front matter, update the template to display the authors in roughly the same format they are in now, and fix every Markdown file.

A quick and dirty fix would be to alter `layouts/blog/list.html` to strip `**Authors?**: \r` from the page variable before converting it to plain text to render.

Both options would need to consider localisation: a handful of languages have a handful of blog posts translated.

/good-first-issue

**Comment by akash-mohanto** [comment]
hey @AmarNathChary can i work on this issue..as i am a beginner in contributing..

**Comment by AmarNathChary** [comment]
Hi, @akash-mohanto I appreciate your interest, but  I started working on this issue. I am a beginner too.
you can find some other issues where no one is working.

**Comment by sftim** [comment]
/remove-good-first-issue
/area web-development

This is more complicated than our typical first issues. If you're new here and do feel you can work on this, you're welcome to take it on.

**Comment by sftim** [comment]
/retitle Blog article summaries typically include author details text

**Comment by sftim** [comment]
I'll frame this as a bug
/kind bug
/remove-kind feature

**Comment by sftim** [comment]
Another workaround: we can specify an explicit summary text for all or just some articles.

**Comment by sftim** [comment]
> A proper fix would be to move the authors to metadata in the front matter, update the template to display the authors in roughly the same format they are in now, and fix every Markdown file.

That's what I'd like to see. We'll need good support for posts having multiple authors.

**Comment by KhushPatibandha** [comment]
@Biswajit-Mohapatra2 try not to assign yourself to an issues if someone else is working on it, it's good practice.

**Comment by sftim** [comment]
@Skar3Krow if you and @Biswajit-Mohapatra2 are _collaborating_, that's absolutely fine!

**Comment by Skar3Krow** [comment]
I'm almost done with the issue, I'll generate the PR by tonight

**Comment by professorabhay** [comment]
Hey @sftim, This issue has also been pending for months with no valid PR.
As there are some minor changes to make that resolve the bug, I would like to raise a PR for this.
May I?

**Comment by sftim** [comment]
This is an open source project. Nobody needs permission to begin helping out.

**Comment by dipesh-rawat** [comment]
Taking a look and see if I can assist by implementing some layout adjustments for this long-standing issue.

/assign
