### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-windows/

### ISSUE THREAD

**Issue by robryb** [kubernetes/website#40187]
I was doing the step-by-step installation for v1.26.3 and found this as the final step for installing on Windows:

5. After installing the plugin, clean up the installation files:

del kubectl.exe kubectl.exe.sha256

Please correct me if I am wrong, but isn't kubectl.exe the kube controller that I just installed? It isn't an installer, it's the product. Your instruction should not be to delete it. If I delete kubectl.exe then I won't have kubectl installed anymore. Make sense?

**Comment by sftim** [comment]
/kind bug
/language en
/triage accepted

For Windows, we don't provide an installable package and the instructions don't explain putting the kubectl binary anywhere special. Until that changes, let's not advise readers to delete `kubectl`.

**Comment by trngapp** [comment]
@sftim  do we have to comment down or delete the 5th instruction there ?
