### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by popescualextraian** [kubernetes/website#40195]
The example does not work locally. I used minikube on win.

**Comment by utkarsh-singh1** [comment]
Hi @popescualextraian, please paste the error here you are facing in form of screenshot or text.

**Comment by NitishKumar06** [comment]
You can discuss more this in the **#minikube** channel on [Kubernetes slack](slack.k8sio).

**Comment by utkarsh-singh1** [comment]
Hi @popescualextraian , have your issue has been resolved / you can close this issue.

**Comment by Shubham82** [comment]
closing this issue, as it is related to minikube(please ask as per the above suggestion). and also no information was provided.
/close
