### ISSUE TITLE
Document that setting sysctl will do nothing for Windows nodes

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/website#40201]
**This is a Feature Request**

**What would you like to be added**

On this page https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/ tell that sysctl do nothing on Windows.
/sig node

Context: https://kubernetes.slack.com/archives/C0BP8PW9G/p1679439424451039

**Why is this needed**

Document limitation and make sure there is no confusion.

**Comment by sftim** [comment]
The key place to mention this is https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#before-you-begin - the node must be running Linux.

It's OK to mention that later in the page as well.

**Comment by sftim** [comment]
> I think the key point here is that if Node is running Windows, sysctl can be set on a Pod and Pod will be scheduled, but sysctl settings will have no effect.

Do we warn people if they set a sysctl for a Pod that is marked as Windows OS? I'm assuming that right now we don't, but happy to learn otherwise.
