### ISSUE TITLE
SBOM instructions are stale

### ISSUE THREAD

**Issue by lachie83** [kubernetes/website#40229]
Source - https://kubernetes.io/releases/download/#container-images

This command no longer captures the packages. I suspect because the SPDX format changed

```curl -Ls "https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/latest.txt)/release"  | awk '/Package: registry.k8s.io\// {print $3}'```

This statement is also no longer correct

```The Kubernetes project publishes a list of signed Kubernetes container images in [SPDX 2.2](https://spdx.dev/specifications/) format.```

The SBOMs now are published using SPDX2.3 and this `publishes a list of signed`  should be updated to `publishes SBOMs for` or something similar.

**Comment by PushkarJ** [comment]
We are discussing this on slack, will update more here once we have a resolution

**Comment by PushkarJ** [comment]
Below shell command should work based on the fix here working for many days now: https://github.com/kubernetes/test-infra/pull/29203

```
curl -Ls https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/latest.txt)/release | grep "SPDXID: SPDXRef-Package-registry.k8s.io" | grep -v sha256 | cut -d- -f3- | sed 's/-/\//' | sed 's/-v1/:v1/' > images
```

Also this should fix this issue too: https://github.com/kubernetes/website/issues/38484

**Comment by RijulGulati** [comment]
Hey @PushkarJ, 

Can you help me with a couple of questions/doubts please?

- I tried the above command on Mac and it gave empty result. The following command works fine. Do you have a linux machine to test this on? If so and it works fine, we can maybe use the below command?

```sh
curl -Ls "https://sbom.k8s.io/$(curl -Ls https://dl.k8s.io/release/latest.txt)/release" | grep "SPDXID: SPDXRef-Package-registry.k8s.io" |  grep -v sha256 | cut -d- -f3- | sed 's/-/\//' | sed 's/-v1/:v1/'
```

- The issue mentions about an incorrect statement. Does the following works - `The Kubernetes project publishes SBOMs for signed Kubernetes container images in [SPDX 2.3](https://spdx.dev/specifications/) format.` Please correct me here, but I think the previous statement makes sense as well. We can probably just update the version to 2.3?

- The SBOMs now refer to release v1.28.0-alpha.0, however the [documentation website](https://kubernetes.io/releases/download/#container-images) mentions v1.27. Do we need to update the version in docs?

**Comment by RijulGulati** [comment]
Update: I was able to test the script on linux. Works fine.

**Comment by PushkarJ** [comment]
tatement. Does the following works - The Kubernetes project publishes SBOMs for signed Kubernetes container images in [SPDX 2.3](https://spdx.dev/specifications/) format. Please correct me here, but I think the previous statement makes sense as well. We can probably just update the version to 2.3?

Yes just updating the version should be ok. We can reassess if needed in the PR review

**Comment by PushkarJ** [comment]
> The SBOMs now refer to release v1.28.0-alpha.0, however the documentation website mentions v1.27. Do we need to update the version in docs?

For docs we refer to GA release. We might need to modify the URL in curl command above to this
`curl -Ls https://dl.k8s.io/release/stable.txt`

**Comment by RijulGulati** [comment]
PR raised. Kindly review the same.
