### ISSUE TITLE
Example code in pods-and-endpoint-termination-flow page is duplicated

### ISSUE THREAD

**Issue by nasa9084** [kubernetes/website#40224]
The example Deployment resource is duplicated in https://github.com/kubernetes/website/blob/129a96800c9741c87c332c8c412dc21f77682ad3/content/en/docs/tutorials/services/pods-and-endpoint-termination-flow.md?plain=1#L39-L74 (code import shortcode and in-line code)

**Comment by sftim** [comment]
/kind bug

We should keep the `codenew` shortcode and drop the inline manifest.

**Comment by nasa9084** [comment]
@sftim we should contain the Service resource following to the Deployment in the `service/pod-with-graceful-termination.yaml` as well, right?

**Comment by chirag0002** [comment]
Hey @sftim, I would like to work on this issue. Do assign me this issue so I can start working on this.

**Comment by sftim** [comment]
BTW @chirag0002 our convention in SIG Docs is very much that anyone is welcome to start work on an issue, and the best way to indicate that you're starting work is to open a PR (either a draft or the final thing).

If anyone else wanted to work on this, please do try to liaise with @chirag0002 first.

**Comment by chirag0002** [comment]
Thanks @sftim for your piece of advice, I will definitely keep this in mind for the next time.

**Comment by sftim** [comment]
The page to fix is https://kubernetes.io/docs/tutorials/services/pods-and-endpoint-termination-flow/

> We should contain the Service resource following to the Deployment in the `service/pod-with-graceful-termination.yaml` as well, right? (or should we create a new file for Service?)

Ah yes. The Service:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
should go in a new example manifest file `service/explore-graceful-termination-nginx.yaml` and we'll need a second `codenew` shortcode to cover that.

Ideally we also explain how to use `kubectl apply` to deploy those.

For example, for the Deployment, it's
```shell
kubectl apply -f https://k8s.io/examples/service/pod-with-graceful-termination.yaml
```

**Comment by chirag0002** [comment]
Hey @sftim, I have linked a PR against this issue, please do review it.

**Comment by dipesh-rawat** [comment]
PR https://github.com/kubernetes/website/pull/40214 is submitted by another first time contributor to address the same problem before this issue was created. 
I will let other members decide on the best remediation of this situation.

**Comment by nasa9084** [comment]
ah sorry, that was my bad, I only searched issues before filing this issue... :bow:

**Comment by Gaurav-create948** [comment]
Hey @chirag0002 i have recently started my journey in open source and want to learn more looking for correct mentorship and guidance. If this issue is not resolved completely in that case can i also work on this??

**Comment by chirag0002** [comment]
Hi @Gaurav-create948, this issue is already resolved, I've also linked a PR to this issue.
You can look for another good-first-issue to get started with.

**Comment by Abhi-y2003** [comment]
Hey, anyone working on this, can you assign it to me.
/assign

**Comment by chirag0002** [comment]
@Abhi-y2003, this issue is already resolved. As you can see I've also linked a PR to this issue. You can search for another good-first-issue to get started with.

**Comment by sftim** [comment]
This issue **isn't** yet resolved, but at least one reviewable PR is already open with a potential fix.

**Comment by Shubhdeep02** [comment]
please assign me with issuse
