### ISSUE TITLE
[zh-cn] Missing blog: https://kubernetes.io/zh-cn/blog/2019/04/24/hardware-accelerated-ssl/tls-termination-in-ingress-controllers-using-kubernetes-device-plugins-and-runtimeclass

### ISSUE THREAD

**Issue by yeqiugt** [kubernetes/website#40220]
When I clicks on https://kubernetes.io/zh-cn/blog/2019/04/24/hardware-accelerated-ssl/tls-termination-in-ingress-controllers-using-kubernetes-device-plugins-and-runtimeclass/ at the bottom of  https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/ .Should I replace it with an English link? Or just leave it as is and wait for someone to translate it.

**Comment by mengjiao-liu** [comment]
This blog has not been translated into Chinese yet, so the link shows 404.

Are you interested in translating this blog? Or you can open an issue and hope other contributors do it.

**Comment by mengjiao-liu** [comment]
/retitle [zh-cn] Missing blog: https://kubernetes.io/zh-cn/blog/2019/04/24/hardware-accelerated-ssl/tls-termination-in-ingress-controllers-using-kubernetes-device-plugins-and-runtimeclass
/help

**Comment by pegasas** [comment]
Hi,
@yeqiugt @mengjiao-liu 
I would like to work on this issue. 
Do assign me this issue so I can start working on this.
Also, would you please to provides me the original link of this blog and which part should I put it into in the repo?

**Comment by mengjiao-liu** [comment]
/assign @pegasas 

> Also, would you please to provides me the original link of this blog and which part should I put it into in the repo?

original link: https://kubernetes.io/blog/2019/04/24/hardware-accelerated-ssl/tls-termination-in-ingress-controllers-using-kubernetes-device-plugins-and-runtimeclass/

You can put the translated content in this directory: `content/zh-cn/blog/_posts` （You can refer to other blog translation formats.）

**Comment by mengjiao-liu** [comment]
The task has been finished! Thanks for @pegasas !

/close

**Comment by pegasas** [comment]
Thanks @mengjiao-liu for giving this issue for my first good issue!
