### ISSUE TITLE
kube-apiserver Audit Configuration (v1)

### ISSUE THREAD

**Issue by EdPike365** [kubernetes/website#40234]
Group field documentation needs to detail that the version substring, as in the "/v1" in "batch/v1", should not be present.

**Comment by sftim** [comment]
I believe that this issue is about the automatically generated web page https://kubernetes.io/docs/reference/config-api/apiserver-audit.v1/
Have I got that right?

/language en
/kind feature
/sig api-machinery

**Comment by sftim** [comment]
/priority awaiting-more-evidence
It'd be good to know _why_ the API (and generated documentation) should change.
