### ISSUE TITLE
Issue with k8s.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### ISSUE THREAD

**Issue by chee-ip** [kubernetes/website#40245]
What's the new yum repo of kubeadm and related binary packages? It seems no kubeadm packages in https://packages.cloud.google.com/yum/repos.

**Comment by utkarsh-singh1** [comment]
Hi @chee-ip , can you check again now, it has been updated now.

**Comment by sftim** [comment]
I don't think this needs to stay open
/close
