### ISSUE TITLE
Suggest convenient kubectl shell aliases

### ISSUE THREAD

**Issue by shyamg28** [kubernetes/website#40259]
As of today, there are common aliases used by those that work with Kubernetes clusters often. These could include the following commonly used ones - 
```bash
alias kgp='kubectl get pod -owide'
alias kgs='kubectl get service -owide'
alias kgd='kubectl get deploy -owide'
alias kd='kubectl describe'
alias kg='kubectl get -owide'
alias ka='kubectl apply -f'
alias kx='kubectl exec -it'
alias ke='kubectl edit'
alias ns='kubectl config set-context --current --namespace '
export dry='--dry-run=client -oyaml'
export y='-oyaml'
export w='-owide'
export j='-ojson'
export force='--force --grace-period=0'
```

It would be of value add if there was a common space on the kubernetes docs, where these aliases could be placed and copied over.

**Comment by shyamg28** [comment]
> Hi @shyamg28, thanks for the suggestion for alias the available Kubernetes commands but, as I can relate, it is most of personal choice that if you want to alias your command or not.

I was more or less expecting this 😄  The cheatsheet also has certain more personal suggestions around autocomplete and using `k` as an alias. We could expand it to have these as suggestions isn't it?

> Instead of adding to the documentation, you can post a blog on it.

I believe there are various blogs with such aliases in place, more or less similar 😄

**Comment by prathik457** [comment]
I love this idea. The reason why I am in for this idea is because this is the only documentation we can access for CKA and CKAD exam.  We can present this documentation as one flavour of aliases. Also lets put a disclaimer that the users can modify this as per convenience.

**Comment by Ritikaa96** [comment]
Hi @shyamg28 , great idea. 
you can add them at https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration under title: `commonly used alias`

**Comment by shyamg28** [comment]
> Hi @shyamg28 , great idea. you can add them at https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration under title: `commonly used alias`

Created a PR here - https://github.com/kubernetes/website/pull/40261

**Comment by aj11anuj** [comment]
Is there anyone still willing to work on it?
