### ISSUE TITLE
[ja] Translate docs/tutorials/services/connect-applications-service into Japanese

### ISSUE THREAD

**Issue by kmuto** [kubernetes/website#40269]
**This is a Feature Request**

**What would you like to be added**

Translate https://kubernetes.io/docs/tutorials/services/connect-applications-service into Japanese

**Why is this needed**

**Comments**

/language ja
/assign

**Comment by Okabe-Junya** [comment]
It seems that this issue is already resolved. If no, feel free to re-open :)

/close
