### ISSUE TITLE
Explain or reconsider use of `agnhost` container image (eg: used in “Hello minikube” tutorial)

### ISSUE THREAD

**Issue by kevinburkesegment** [kubernetes/website#40276]
I'd love more explanation of what's happening on the "kubectl create deployment" step. Where can I go see the image for myself? What is "agnhost"? 

What I am trying to do is take the instructions from the quickstart and adapt it to deploy a Helm chart that I have in a file on my local machine.

**Comment by utkarsh-singh1** [comment]
Hi @kevinburkesegment, Use - 

`kubectl describe deployment hello_node`

to see the step-by-step procedure of your deployment.

**Comment by Ritikaa96** [comment]
Hi @kevinburkesegment .  [agnhost](https://pkg.go.dev/k8s.io/kubernetes/test/images/agnhost) is imagename here . you need to know docker or similar tools to manage images. 
If you just want to see what's going on after you deploy the image and investigate post `kubectl create` and explore your deployment, visit: https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

**Comment by Ritikaa96** [comment]
> I'd love more explanation of what's happening on the "kubectl create deployment" step. Where can I go see the image for myself? What is "agnhost"?

It's a great recommendation, however, this tutorial is already extensive and explains major steps.  The depth of those steps is already given in various docs/tutorials on the website. As per me ,the page doesn't need more info.
Please feel free to explore and ask here if you need direction.

**Comment by afbjorklund** [comment]
The "agnhost" image is a _lot_ more complicated, than the old NGINX echoserver image that it replaced...

* https://github.com/kubernetes/minikube/issues/15650

**Comment by sftim** [comment]
/language en

/retitle Explain or reconsider use of `agnhost` container image (eg: used in “Hello minikube” tutorial)

**Comment by sftim** [comment]
I think we should move this forward, for a number of reasons.

**Comment by BenTheElder** [comment]
> I'd love more explanation of what's happening on the "kubectl create deployment" step. Where can I go see the image for myself? What is "agnhost"?

It's an image used for "e2e" ("end to end") testing Kubernetes, hosted by the project, which supports multiple platforms and is actively maintained.

It can do a number of tasks https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/README.md

The name is a play on "host agnostic".

The important thing here is maintained and multi-arch / multi-platform, and capable of serving a simple response.

I'm not aware of a good alternative at the moment, but one of the SIGs/subprojects may be willing to host one.

**Comment by afbjorklund** [comment]
As detailed in the issue linked above, minikube is using an image based on https://github.com/jmalloc/echo-server

The original "echoserver" was a lua implementation in nginx, that was struggling a bit with cross-platform support...

```
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
k8s.gcr.io/echoserver   1.4       a90209bb39e3   6 years ago   140MB
```

> This tutorial provides a container image that uses NGINX to echo back all the requests.
