### ISSUE TITLE
"Using Minikube to Create a Cluster" unclear on meaning of containerd

### ISSUE THREAD

**Issue by imaPheven** [kubernetes/website#40288]
In the third sentence on the second paragraph it reads:

| operations, such as containerd or Docker.

It is not clear if `containerd` is a typo or a new term.

**Comment by trngapp** [comment]
@imaPheven I believe writing  "such as containerd or Docker" was not necessary because it was not very accurate , only writing till operations is fine enough . But still it is not an issue there .

**Comment by niranjandarshann** [comment]
@imaPheven  I think the sentence is referring to the container tools and containerd manage the lifecycle of container on VMs.

**Comment by niranjandarshann** [comment]
> /retitle "Using Minikube to Create a Cluster" unclear on meaning of containerd /language en
> 
> Page to Update: https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/
> 
> For additional info, adding a hyperlink pointing to the corresponding official doc of the container runtime would be be useful here.

wants to work on it

**Comment by dipesh-rawat** [comment]
/kind documentation
/triage accepted

Improvements are welcome!

**Comment by sftim** [comment]
We could add a reference to our glossary entry: https://kubernetes.io/docs/reference/glossary/?all=true#term-containerd

**Comment by afbjorklund** [comment]
It is not the only problem on that page, the description of minikube is not very accurate (anymore) either...

But it will soon need to change anyway, when the online tutorials disappear, so probably time for a rewrite ?
