### ISSUE TITLE
Broken Image links on the Kubernetes Blog

### ISSUE THREAD

**Issue by Anita-ihuman** [kubernetes/website#40280]
**This is a Bug Report**

**Problem:**
<img width="690" alt="Screenshot 2023-03-24 at 9 12 09 AM" src="https://user-images.githubusercontent.com/62384659/227463224-ef53f059-61ce-43d2-aae4-4e5fa7257b04.png">

I noticed some images on the [kubernetes blog](https://kubernetes.io/blog/2015/09/kubernetes-performance-measurements-and/
) are not displaying as should. Perhaps there is an error with the image links

**Proposed Solution:**
Although this articles was published a long time ago, it Would be great if this is rectified. 

**Page to Update:**
https://kubernetes.io/...

**Comment by trngapp** [comment]
Hi anita can you please specify the page, because the pages that you have specified are rendering completely fine with the images , please attach the link of the particular page.

**Comment by tamilselvan1102** [comment]
Page to be update: 
https://kubernetes.io/blog/2015/09/kubernetes-performance-measurements-and/

**Comment by Ritikaa96** [comment]
Seems like this is from 2015 blog: https://kubernetes.io/blog/2015/09/kubernetes-performance-measurements-and/

**Comment by dipesh-rawat** [comment]
Had a quick look at the network activity on the load of [page](https://kubernetes.io/blog/2015/09/kubernetes-performance-measurements-and/), I can see the images URLs on the page is resulting in **Error 403** from the server.

**Image Links:**

1. [get.png](https://lh4.googleusercontent.com/NrKLoz2iB-TNdOxISL7OcqquCKL-MijDBCokf-u4ASAqgmo6zT7ZU24mXDvIwUUlRsFSsL3KF17dEAfUT41TSgNPvId5HN5ELQTXJSSBF0dp9EOccx4Y4WZ9fC9v9B_kCA=s1600)
2. [put.png](https://lh4.googleusercontent.com/53AtIdoGQ477Ju0FD4S76xbZs490JnmibhSZh67aq1-MU4Jw4B-7FBgzvFoJXHcAMeSU9r3bzJHpBFAfcSf7FIS3JGZ4TiAiHucyjH3ErrarKrwYNFopvxYSBo0qxP-U0w=s1600)
3. [delete.png](https://lh4.googleusercontent.com/-wsLEXPfgtXNlu-pDfM4c0Qvr8lU7-G2w_nSgVeqg04D7RnhgSzg6Z5-mVmIYOzTWF7XaJ0zsDZBBlyZLqj4R1fkwWq-uaKJJI8xLAQ1gYWbh5qKXr5-rzkjm6CT3kBU=s1600)
4. [post.png](https://lh6.googleusercontent.com/It8dH6iM2ZPypZ99KSUo_kJY4DnR2QD8yGJj26TiZ3U4owyf-WXoxrDfBAc1hcSn3i3LuxE3KGlUzQOaPgH6XVjSAU9Z2zMfZCKFAxEGtuCQiKlJPX4vH2JgQf3h1BXMRJQ=s1600)
5. [list.png](https://lh6.googleusercontent.com/6Gy-UKBZUoEwJ9iFytq-k_wrdvh6FsTJexSpn6nNnBwOvxv-Sp6PV7vmArCL22MUkz0tWH7MxhaIc-JE8YpEc0X4nDUMn-cKWF3ANHtgd2aJ5t3osoaezDe_xqjpi748Cbw=s1600)


**Page with issue:** https://kubernetes.io/blog/2015/09/kubernetes-performance-measurements-and/

**Page markdown source:** https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2015-09-00-Kubernetes-Performance-Measurements-And.md

/language en

**Comment by rounaksarda** [comment]
can i solve it 
triage/accepted

**Comment by rounaksarda** [comment]
seems like we have link associated with image is not available anymore to use, including the screenshot 
![image](https://user-images.githubusercontent.com/36100122/227685909-70f9ca13-3419-4148-ab20-86a628152aae.png)

**Comment by NitishKumar06** [comment]
triage/accepted

**Comment by sftim** [comment]
/remove-triage accepted

PRs to fix this will be a low priority for review due to our policy of only maintaining blog articles for 2 years. However, there's no *prohibition* on finding the missing images and proposing a fix.
