### ISSUE TITLE
Issue with k8s.io/fr/docs/getting-started-guides/fedora/

### ISSUE THREAD

**Issue by vo-omega-001** [kubernetes/website#40309]
Unfortunately, this page (https://kubernetes.io/fr/docs/getting-started-guides/fedora/) is empty

:-(

regards

**Comment by dipesh-rawat** [comment]
Putting my analysis below for benefit of other contributors looking at this:

The `getting-started-guides` has been removed from the main website (`lang/en` as part of PR #6012). Plus the main site has redirect added for https://kubernetes.io/docs/getting-started-guides/ to `https://kubernetes.io/docs/setup/` ([Refer redirect logic](https://github.com/kubernetes/website/blob/main/static/_redirects#L140))

At the very least we should get rid of all the contents in `content/fr/docs/getting-started-guides/`

/kind cleanup

**Comment by dipesh-rawat** [comment]
Changes to address this issue have been merged as part of #40333

/close
