### ISSUE TITLE
[ja] Translate /docs/tasks/configure-pod-container/configure-persistent-volume-storage into Japanese

### ISSUE THREAD

**Issue by FeLvi-zzz** [kubernetes/website#40308]
**This is a Feature Request**

**What would you like to be added**

Translate https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/ into Japanese

**Why is this needed**

**Comments**

/language ja
/assign

**Comment by aj11anuj** [comment]
No PR has been raised yet (8+ month) + no interest from any other contributor in localizing this page
/close not-planned
