### ISSUE TITLE
Incorrect information with regards to O field for CSR(?)

### ISSUE THREAD

**Issue by kindrowboat** [kubernetes/website#40302]
**This is a Bug Report**

**Problem:**
https://github.com/kubernetes/website/blob/80561f67b1c11fd1994fe60b0d1b457770f6675d/content/en/docs/reference/access-authn-authz/certificate-signing-requests.md?plain=1#L207-L210 says that 

> It is important to set CN and O attribute of the CSR. CN is the name of the user and O is the group that this user will belong to

It's my understanding that the `O` field does not need to be set for certificates assigned to individual users which are going to be given permissions with a RoleBinding (or ClusterRoleBinding). For instance: if I had a user "alice" who was going to have the "edit" role in the "acme" namespace. Alice's CSR could (and should?) have a blank "O" field, and, once approved, an administrator can grant them a role with `kubectl create rolebinding alice-edit-binding --clusterrole=edit --user=alice --namespace=acme`

**Proposed Solution:**

Perhaps the docs should read something like:

> It is important to set the CN of the CSR. CN is the name of the user. O should be set as the already defined group that this user will belong to, if such a group exists. O might be blank if the user will be later granted a role with a RoleBinding or ClusterRoleBinding. You can refer to [RBAC](/docs/reference/access-authn-authz/rbac/) for standard groups.

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#create-private-key

**Comment by KanishkaVerma054** [comment]
can I work on this issue?
