### ISSUE TITLE
[pt-br] Broken link in 'Kubernetes Components' page

### ISSUE THREAD

**Issue by igorandrade83** [kubernetes/website#40346]
Link quebrado na página [Componentes do Kubernetes](https://kubernetes.io/pt-br/docs/concepts/overview/components/).

"Veja [Construindo clusters de alta disponibilidade](https://kubernetes.io/docs/admin/high-availability/) para um exemplo de configuração de múltiplas VMs para camada de gerenciamento (multi-main-VM)."

**Comment by jihoon-seo** [comment]
/triage accepted
/language pt
The link should be updated to go to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/ .

**Comment by jihoon-seo** [comment]
/retitle [pt-br] Broken link in 'Kubernetes Components' page
