### ISSUE TITLE
Document JSON inputs to `crictl`

### ISSUE THREAD

**Issue by ymartineau** [kubernetes/website#40360]
hi,

what is the format of the json files that should be provided to crctl for resource creation and in inspect* commands? Is there a json schema? a standard? Sorry, it may be described on another page?

thank you

**Comment by Ritikaa96** [comment]
Hi @ymartineau you can see the details regarding crictl here along with json format for pod creation: https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#run-a-pod-sandbox

**Comment by Ritikaa96** [comment]
For inspect commends , If you mean you want to get inspect output in json you can just use the flag `-o` like this :
`crictl inspect --output json <yourContainerID>`

**Comment by ymartineau** [comment]
my question is how do you know the field name and values in json? is there a specification that describes this content?

it seems the content of cri inspect comes from a protobuf:

https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/container.go#L851
```
func marshalContainerStatus(cs *pb.ContainerStatus) (string, error) {
	statusStr, err := protobufObjectToJSON(cs)
```
I found the following protobuf definition:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L1208

```
// ContainerStatus represents the status of a container.
message ContainerStatus {
    // ID of the container.
    string id = 1;
    // Metadata of the container.
    ContainerMetadata metadata = 2;
    // Status of the container.
    ContainerState state = 3;
    // Creation time of the container in nanoseconds.
    int64 created_at = 4;
    // Start time of the container in nanoseconds. Default: 0 (not specified).
    int64 started_at = 5;
    // Finish time of the container in nanoseconds. Default: 0 (not specified).
    int64 finished_at = 6;
    // Exit code of the container. Only required when finished_at != 0. Default: 0.
    int32 exit_code = 7;
    // Spec of the image.
    ImageSpec image = 8;
    // Reference to the image in use. For most runtimes, this should be an
    // image ID
    string image_ref = 9;
    // Brief CamelCase string explaining why container is in its current state.
    // Must be set to "OOMKilled" for containers terminated by cgroup-based Out-of-Memory killer.
    string reason = 10;
    // Human-readable message indicating details about why container is in its
    // current state.
    string message = 11;
    // Key-value pairs that may be used to scope and select individual resources.
    map<string,string> labels = 12;
    // Unstructured key-value map holding arbitrary metadata.
    // Annotations MUST NOT be altered by the runtime; the value of this field
    // MUST be identical to that of the corresponding ContainerConfig used to
    // instantiate the Container this status represents.
    map<string,string> annotations = 13;
    // Mounts for the container.
    repeated Mount mounts = 14;
    // Log path of container.
    string log_path = 15;
    // Resource limits configuration of the container.
    ContainerResources resources = 16;

message ContainerStatusResponse {
    // Status of the container.
    ContainerStatus status = 1;
    // Info is extra information of the Container. The key could be arbitrary string, and
    // value should be in json format. The information could include anything useful for
    // debug, e.g. pid for linux container based container runtime.
    // It should only be returned non-empty when Verbose is true.
    map<string, string> info = 2;
}
}
```
actually, I was interested in the content of this extra info (linux.devices.path containing *cpu*)

**Comment by Ritikaa96** [comment]
@kubernetes/sig-node-feature-requests 
I think this is worth review by the sig node team.PTAL.

**Comment by saschagrunert** [comment]
Yes, `crictl` directly uses the JSON marshaled protobuf definition of the [CRI API](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto): 

https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.pb.go

There are some docs available within the cri-tools repository: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md

But we could think about a protobuf to JSON docs generator, if that even exists.

**Comment by saschagrunert** [comment]
We could use tools like [protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc) to generate something for k/website, though.
