### ISSUE TITLE
broken links in ObjectMeta

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#40367]
**This is a Bug Report**

**Under the Section**

 **ownerReferences.name** (string)
 **namespace** (string)
 **labels** (map[string]string)
 **annotations** (map[string]string)
 **uid** (string)

**Link to get updated**
 http://kubernetes.io/docs/user-guide/identifiers#names
 http://kubernetes.io/docs/user-guide/namespaces
 http://kubernetes.io/docs/user-guide/labels
 http://kubernetes.io/docs/user-guide/annotations
 http://kubernetes.io/docs/user-guide/identifiers#uids

**Comment by Ritikaa96** [comment]
Please mention all broken links in one page. multiple issues arent needed .
