### ISSUE TITLE
[hi] Update hyperlinks on the homepage to open in new tab

### ISSUE THREAD

**Issue by Jai-Solania-29** [kubernetes/website#40370]
**This is a Bug Report**

**Problem:**

In the English and Hindi version of the website, some hyperlinks on the homepage that are redirecting the user to a different website (other than Kubernetes) are not getting redirected to a separate tab.

**Proposed Solution:**

I will make them redirect to the separate tab using the target="_blank" property.

**Page to Update:**

https://kubernetes.io/ and https://kubernetes.io/hi/

<img width="1204" alt="Screenshot 2023-03-27 at 8 19 24 PM" src="https://user-images.githubusercontent.com/90816300/228246035-fff7e602-b6ba-49d9-a6d2-ca4434a14c98.png">

![Screenshot 2023-03-18 at 12 23 57 AM](https://user-images.githubusercontent.com/90816300/228246112-b08438d4-c568-462c-af57-595939d22c91.png)

![Screenshot 2023-03-18 at 12 25 08 AM](https://user-images.githubusercontent.com/90816300/228246216-3b74edee-5045-4a7e-a4e9-c09bfa92a424.png)

I want to work on this issue.
/assign

**Comment by dipesh-rawat** [comment]
/retitle [hi] Update hyperlinks on the homepage to open in new tab

/area web-development
/remove-language en

**Comment by Jai-Solania-29** [comment]
Hey @NitishKumar06 @dipesh-rawat, Should I work on this issue?

**Comment by NitishKumar06** [comment]
Hi @Jai-Solania-29 , Have you gone through @divya-mohan0209 suggestions here: https://github.com/kubernetes/website/pull/40401#issuecomment-1489588401?

**Comment by Jai-Solania-29** [comment]
Yes I have gone through those suggestions, that's why I'm making sure whether I should work on this issue or not so that I can proceed further.

**Comment by divya-mohan0209** [comment]
Hello Jaideep, good morning! Please see my responses below.

1. Could you explain the value addition in terms of UX/clarity/readability/conciseness/grammar that this change adds? I don't see any significant improvement when this change is made except for the fact that the page opens in a new browser.
2. Are we sure that this issue exists ONLY on the homepage and there is no other file with the same issue across all localizations? 
3. IF we agree to move forward, based on the outcome of this discussion, I'd recommend that this change be first made to all the files on the English website over a SINGLE PR and then cascaded to others. It will help ensure standardization.

**Comment by Jai-Solania-29** [comment]
Hey Divya, good morning!
The thing is that appropriate way of hyperlinks on any website is that they should be redirected to a separate tab if they are redirecting the user to a different site other than the site user is surfing upon so that it could be handier for the user to switch between the content of the website.
That's why I opened this issue and would like to proceed further with this if it suits you.

**Comment by NitishKumar06** [comment]
> I am not sure whether the same issue exists on other pages, but yeah this same issue exists on the Homepage of every other localization. That's why I opened this issue and would like to proceed further with this if it suits you.

Could you take a look at some other pages if similar issue exists?

**Comment by Jai-Solania-29** [comment]
Sure @NitishKumar06 , I'll checkout other pages.
