### ISSUE TITLE
Improve documentation for node resource allocation and Pod status/phase

### ISSUE THREAD

**Issue by pwschuurman** [kubernetes/website#40378]
**This is a Feature Request**

**What would you like to be added**

The Kubernetes website currently has documentation around resource management (https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/). This is geared towards applications that need to specify their resource usage when scheduling to nodes. There isn't any documentation that describes the mechanics of the scheduler with regard to resource utilization (eg: what states result in resource usage against the allocatable resource usage (eg: pods, cpu). For example, the pods allocatable usage is consumed if there is a `Running` pod, or a `Pending` pod that is currently bound to the node. However Terminated or Succeeded pods do not count against the allocatable pod usage. The `.status.phase` impacts the resource usage and should be documented more clearly in the `kube-scheduler` documentation.

**Why is this needed**

For certain resources, it's unclear when certain resources are consumed on a node, and how certain pod status/phase affect the used allocation.

**Comments**

**Comment by alculquicondor** [comment]
Clarification: kubelet and kube-scheduler both implement the same semantics around when a pod counts towards using resources.

**Comment by rumstead** [comment]
Semi off topic but the same section. 

https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#monitoring-compute-memory-resource-usage

> The kubelet reports the resource usage of a Pod as part of the Pod [status](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#object-spec-and-status).

Is that accurate? I do not see the resource usage of the pods added in the status field. 

```
❯ kgp -n kube-system metrics-server-5f9f776df5-5frph -o json | jq '.status'
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2023-03-22T15:53:40Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2023-04-25T21:31:39Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2023-04-25T21:31:39Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2023-03-22T15:53:40Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "docker://f4680e66330f19d6dea8423eff89f658a246953733ce7c1066d048b1c26a8f2d",
      "image": "rancher/mirrored-metrics-server:v0.6.2",
      "imageID": "docker://sha256:25561daa666051dbc5204d6df0ed53882c24f906a2cb71357bf0b8771dc5ab11",
      "lastState": {
        "terminated": {
          "containerID": "docker://55cb8d5c298ded94af126580d433d48ce3f38d3a3fe120ac9473f669902d5571",
          "exitCode": 0,
          "finishedAt": "2023-04-17T15:15:07Z",
          "reason": "Completed",
          "startedAt": "2023-04-17T14:34:29Z"
        }
      },
      "name": "metrics-server",
      "ready": true,
      "restartCount": 15,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2023-04-25T21:30:46Z"
        }
      }
    }
  ],
  "hostIP": "192.168.5.15",
  "phase": "Running",
  "podIP": "10.42.0.222",
  "podIPs": [
    {
      "ip": "10.42.0.222"
    }
  ],
  "qosClass": "Burstable",
  "startTime": "2023-03-22T15:53:40Z"
}
```
