### ISSUE TITLE
Task "Connect a Frontend to a Backend Using Services" does not work after following instructions

### ISSUE THREAD

**Issue by 1dropaflame** [kubernetes/website#40379]
**This is a Bug Report**

**Problem:**

Following the task instructions, it does not work.
1) no instructions given what to do with 

[/frontend-nginx.conf](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/access/frontend-nginx.conf)

2) Hangs and does not get an external ip address even after waiting 10 minutes. The value shows `<pending>`
```
$ kubectl get service frontend --watch
NAME       TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
frontend   LoadBalancer   10.109.154.2   <pending>     80:30460/TCP   33s

```

**Proposed Solution:**

please correct the tutorial.

**Page to Update:**

https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

1.26.1

Windows 11, minikube, WSL2

**Comment by Ritikaa96** [comment]
> 3\. Hangs and does not get an external ip address even after waiting 10 minutes. The value shows `<pending>`
> 
> ```
> $ kubectl get service frontend --watch
> NAME       TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
> frontend   LoadBalancer   10.109.154.2   <pending>     80:30460/TCP   33s
> ```

Hi @1dropaflame , you are using loadbalancer for `minikube`. In case where the cluster is created on platform  which does not provide externalIPs <none> or <pending> will be seen only. 
External IPs are provided by  providers like AWS, Google cloud etc. I suppose yours is baremetal cluster.

For minikube external IP see this: https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access

**Comment by Ritikaa96** [comment]
For reference it is written in the doc itself [here](https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/#creating-the-frontend):

> Similar to the backend, the frontend has a Deployment and a Service. An important difference to notice between the backend and frontend services, is that the configuration for the frontend **Service has type: LoadBalancer**, which means that the **Service uses a load balancer provisioned by your cloud provider** and will be accessible from outside the cluster.

**Comment by 1dropaflame** [comment]
@Ritikaa96 Thanks for the reply. It will be good if it can be emphasized in the instructions that this requires an external cloud provider's provisioning of a load balancer. Most of us are trying to learn K8s on our home Windows laptops.

**Comment by Ritikaa96** [comment]
@1dropaflame I can understand as I have faced similar issues in beginning. however, searching through the following solved most of my queries. as per my experience discussion in these resources also prove to be extremely benefitting for learning k8s

- StackOverflow  
- https://serverfault.com/?tags=kubernetes
- https://discuss.kubernetes.io/
- kubernetes slack channel

**Comment by Ritikaa96** [comment]
> @Ritikaa96 Thanks for the reply. It will be good if it can be emphasized in the instructions that this requires an external cloud provider's provisioning of a load balancer. Most of us are trying to learn K8s on our home Windows laptops.

This is already mentioned in the same page , not with a note but in the lines , see: 

> For reference it is written in the doc itself [here](https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/#creating-the-frontend):
> 
> > Similar to the backend, the frontend has a Deployment and a Service. An important difference to notice between the backend and frontend services, is that the configuration for the frontend **Service has type: LoadBalancer**, which means that the **Service uses a load balancer provisioned by your cloud provider** and will be accessible from outside the cluster.
