### ISSUE TITLE
"Connecting Applications with Services" has a possibly erroneous section

### ISSUE THREAD

**Issue by 1dropaflame** [kubernetes/website#40377]
**This is a Bug Report**

**Problem:**
Information in this section is repetitive and possibly incorrect.

https://kubernetes.io/docs/tutorials/services/connect-applications-service/#securing-the-service

Steps are given here "In short..."

But...

1) default.conf is missing (had to find it here https://github.com/kubernetes/examples/tree/master/staging/https-nginx/)

2) a little later, it says "Use the output from the previous commands to create a yaml file as follows". But this was already done before and doing it again may cause problems.

3) "Now create the secrets using the file"
Already done before

**Proposed Solution:**

Please make corrections on page.

**Page to Update:**
https://kubernetes.io/docs/tutorials/services/connect-applications-service/#securing-the-service

**Comment by hasanrashid** [comment]
I'd like to take this on, but it is pending triage. Do I need to wait until triage is complete?

**Comment by techrev** [comment]
Thank you @1dropaflame for posting the link to default.conf! I had no idea where to find this file and I'm trying to do this tutorial and looking for the file was really slowing me down! 

And to anyone who has time to work on this: it would be great if a link to it could be added to the page, or even just post the output of `kubectl describe cm nginxconfigmap` after the command to create it, as is done on many other pages.

Thanks!

**Comment by hasanrashid** [comment]
Regarding the redundant/erroneous sections: They appear after "Following are the manual steps to follow in case you run into problems running make (on windows for example)". Are these meant to be performed only with the manual method of creating secret and yaml, or are they actually redundant?
