### ISSUE TITLE
Cannot pull image from `registry.k8s.io`

### ISSUE THREAD

**Issue by cxbl-ops** [kubernetes/website#40384]
The registry.k8s.io/nginx-slim:0.8 image in the basic document section of creating a StatefulSet in kubernetes cannot be pulled, and the access page is 404. Please tell me the solution

**Comment by jihoon-seo** [comment]
- en page: https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
- (zh page: https://kubernetes.io/zh-cn/docs/tutorials/stateful-application/basic-stateful-set/ )

I tried pulling the image `registry.k8s.io/nginx-slim:0.8`, and was able to pull.

```
$ docker pull registry.k8s.io/nginx-slim:0.8
0.8: Pulling from nginx-slim
a45d3b21c5c9: Pull complete 
a3ed95caeb02: Pull complete 
e7b00b1be490: Pull complete 
60b05e56ad41: Pull complete 
40b582e4e91a: Pull complete 
5a5521cbcfe6: Pull complete 
Digest: sha256:8b4501fe0fe221df663c22e16539f399e89594552f400408303c42f3dd8d0e52
Status: Downloaded newer image for registry.k8s.io/nginx-slim:0.8
registry.k8s.io/nginx-slim:0.8

$ docker images | grep nginx-slim
registry.k8s.io/nginx-slim      0.8       18ea23a675da   6 years ago    110MB
```

I guess that you are in China, and somehow the access to `registry.k8s.io` might be blocked.

I wanted to add the label `/triage not-reproducible`, but thought that there will be more people that face this issue, so not adding for this time.

/retitle Cannot pull image from `registry.k8s.io`

**Comment by cxbl-ops** [comment]
是的，我在中国，但拉取之后，应用到nginx-slim:0.8.yaml之后，长时间显示pending状态，怎么解决，求告知

**Comment by dims** [comment]
@cxbl-ops see https://github.com/kubernetes/registry.k8s.io/blob/main/docs/debugging.md for tips to help debug. you can open an issue in that repo.

/close
