### ISSUE TITLE
Provide more information on Patch

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#40389]
**This is a Feature Request**

**Page**
https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/patch/
This page is auto-generated

**What would you like to be added**
Provide more information on **Patch**  or can provide a link on the page that can give more information on the **Patch**

**Comment by sftim** [comment]
We can also revise https://github.com/kubernetes-sigs/reference-docs/

**Comment by utkarsh-singh1** [comment]
Hi @0904-mansi, Please see above comments before assigning this issue yourself .

**Comment by KhushPatibandha** [comment]
> Since it is an auto generated page , it can only be fixed by upstream code at kubernetes repo.

Hey I didn't really got what you are trying to say here, I would really appreciate if you can explain it. I am sorry if this question is really dumb, Am just starting out.

**Comment by sftim** [comment]
If we improve https://github.com/kubernetes-sigs/reference-docs/ then we can try to change the generation so that https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/patch/ is more helpful to readers.

Assistance is welcome (you'll need to know Golang).

**Comment by AmarNathChary** [comment]
@KhushPatibandha @0904-mansi are you people working on this issue as it has inactive for a long time.
