### ISSUE TITLE
Annotation `kubectl.kubernetes.io/restartedAt` is not registered at the Kubernetes annotation documentation.

### ISSUE THREAD

**Issue by Biswajit-Mohapatra2** [kubernetes/website#40429]
**This is a Bug Report**

**Problem:**
The annotation `kubectl.kubernetes.io/restartedAt` is unregistered because it doesn't appear inside https://kubernetes.io/docs/reference/labels-annotations-taints/

**Proposed Solution:**
Register the annotation, by documenting it inside the https://kubernetes.io/docs/reference/labels-annotations-taints/

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

/sig architecture
/sig cli
/language en
/sig doc

**Comment by T-Lakshmi** [comment]
Hi @Biswajit-Mohapatra2,
This issue is already reported on #40067 and even i could see your comment there. 
I am not getting how it is different from #40067.

**Comment by Biswajit-Mohapatra2** [comment]
Hey @T-Lakshmi ,
Thanks for noticing.
i have the solution too, can you help me with the labels to send the pull request?
