### ISSUE TITLE
[ja] Translate reference/setup-tools/kubeadm/kubeadm-config into Japanese

### ISSUE THREAD

**Issue by ystkfujii** [kubernetes/website#40420]
**This is a Feature Request**

**What would you like to be added**

Translate https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/ into Japanease

**Why is this needed**

**Comments**

/language ja
/assign

**Comment by ArslanYM** [comment]
Can i work on this?

**Comment by ystkfujii** [comment]
@ArslanYM 
> Can i work on this?

Sorry, this PR is assigned to me and I'm working on it.

**Comment by Okabe-Junya** [comment]
Hi folks!!

It looks no change on this issue for several months, so I remove the assignee. Feel free to re-assign when you work on this issue :)

/unassign @ystkfujii
