### ISSUE TITLE
Unquoted export in "Performing a Rolling Update" tutorial

### ISSUE THREAD

**Issue by janusz5** [kubernetes/website#40473]
A qotation mark is missing at the end of a command, making it wrong. At the page https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/ at step 2:
The command is: 
export NODE_PORT="$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')
And should be:
export NODE_PORT="$(kubectl get services/kubernetes-bootcamp -o go-template='{{(index .spec.ports 0).nodePort}}')"

**Comment by dipesh-rawat** [comment]
Page to Update: https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/

/retitle Unquoted export in "Performing a Rolling Update" tutorial
/kind bug
