### ISSUE TITLE
[zh] missing page for Validating Admission Policy

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#40481]
https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/

The Chinese version for this page is missing.

> ValidatingAdmissionPolicy：启用准入控制中所用的对 CEL 校验的 [ValidatingAdmissionPolicy](https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/validating-admission-policy/) 支持。

**Comment by Zhuzhenghao** [comment]
This issue can be closed since this page has been tranlated. 

https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/validating-admission-policy/

**Comment by windsonsea** [comment]
Thanks.
/close
