### ISSUE TITLE
broken link in Endpoints

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#40480]
**This is a Bug Report**

**Page**
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoints-v1/#Endpoints
This page is auto-generated
The fix may need to happen elsewhere in the Kubernetes project

**Under the section**
subsets.ports.appProtocol
**Link**
https://www.iana.org/assignments/service-names)
On the page, the link is included with the closed Bracket. A proper fix could be just by adding space between the link and the Bracket

**Comment by vaibhav2107** [comment]
Checked the upstream source code: 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4870

As this is a auto generated page, Fixes should be proposed to the upstream source.

**Comment by AmarNathChary** [comment]
Raised a PR in https://github.com/kubernetes/kubernetes/pull/117083#issuecomment-1495574855

**Comment by sftim** [comment]
An alternative: revise the generator code

https://github.com/kubernetes-sigs/reference-docs/
