### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by rlguarino** [kubernetes/website#4049]
**This is a...** 
- [X] Feature Request
- [ ] Bug Report

**Problem:**

It's not documented how to prevent a Pod from mounting a folder with sensitive contents on the host using HostPath volume.

**Proposed Solution:**

Document how to prevent pods from mounting folders with sensitive contents from from the host. Even if the only way to prevent someone from mounting a host path is to make it only readable by root. 

**Page to Update:**
http://kubernetes.io/docs/concepts/storage/volumes/
http://k8s.io/docs/concepts/storage/volumes/

**Comment by tengqm** [comment]
The request makes sense but it will be very difficult to define "sensitive" or "security". Setting a host path to be readable only by root won't solve the problem. You can still launch a privileged container, for example.

**Comment by rlguarino** [comment]
I think the only answer at the moment it to disallow host path volume for pods. This Issue was for adding docs on how to prevent a pod from reading some sensitive data, like the kubelets credentials, to the HostPath volume's documentation.

**Comment by tengqm** [comment]
/remove-lifecycle rotten
Let's keep it fresh for another 30d, :).

**Comment by ajaeger** [comment]
/assign

The  page is now at  https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/ and change #8611 fixes the problem. I'll close this issue now.
