### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/

### ISSUE THREAD

**Issue by todaviaCaliente** [kubernetes/website#40503]
https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/
Previously there was an interactive tutorial, which is now disabled.
It would be good to have new (non-interactive?) tutorial instead of removed one.

**Comment by utkarsh-singh1** [comment]
Hi @todaviaCaliente, you can use killercoda and minikube to setup local cluster.

**Comment by sftim** [comment]
@todaviaCaliente, you can discuss and recommend replacements at https://github.com/kubernetes/website/discussions/38878

**Comment by sftim** [comment]
/close not-planned

We already have an overall issue about the removal of Katacoda
