### ISSUE TITLE
kube-proxy: error kubeadm init --pod-network-cidr=192.168.0.0/16

### ISSUE THREAD

**Issue by Leyorme** [kubernetes/website#40520]
Hi,
I am configuring the k8s cluster, I have version 1.26.1 on a centos 8 stream.
When I start the network:
kubeadm init --pod-network-cidr=192.168.0.0/16

I get the error:
[ERROR ImagePull]: failed to pull image registry.k8s.io/coredns/coredns:v1.9.3: output: E0405 12:02:14.230591  371096 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to do request: Head \"https://registry.k8s.io/v2/coredns/coredns/manifests/v1.9.3\": dial tcp 34.107.244.51:443: i/o timeout" image="registry.k8s.io/coredns/coredns:v1.9.3"
time="2023-04-05T12:02:14+02:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to do request: Head \"https://registry.k8s.io/v2/coredns/coredns/manifests/v1.9.3\": dial tcp 34.107.244.51:443: i/o timeout"
, error: exit status 1

I can't find the cause of the failure. 
Thank you very much for your help

**Comment by neolit123** [comment]
for support questions please see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
