### ISSUE TITLE
Adding Security of images at: kubernetes.io/docs/concepts/containers/images/

### ISSUE THREAD

**Issue by Biswajit-Mohapatra2** [kubernetes/website#40530]
**This is a Feature Request**

**What would you like to be added**
Adding more about container image security at:  https://kubernetes.io/docs/concepts/containers/images/

**Why is this needed**
To better understanding of image and how to secure container images. 

Security is the measure aspect .

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/43176 partly covers this; if that PR merges, then we can change https://kubernetes.io/docs/concepts/containers/images/ to link to the new content.

**Comment by sftim** [comment]
(TBH - I don't object to this issue rotting out and being closed)
