### ISSUE TITLE
 clean up of installation files using Bash shell should use "rm" command instead of "del".

### ISSUE THREAD

**Issue by ajinkyak423** [kubernetes/website#40552]
when we are installing kubectl using bash shell after installation cleanup of files should use rm command instead of "del" as bash shell do not have "del" command instead it uses "rm" command.

**Comment by dipesh-rawat** [comment]
Hi @ajinkyak423 Can you let us know the URL of the page that has the information documented in the issue?

/triage needs-information

**Comment by ajinkyak423** [comment]
https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/ 
this is the URL to the page on which there is mention of a command for CMD CLI but not for the BASH shell to
![WhatsApp Image 2023-04-07 at 01 27 22](https://user-images.githubusercontent.com/77945065/230554938-60368ee6-456a-4d73-8a68-a38218a37f37.jpg)
 clean up files after installation. There is no "del" command in the bash shell instead one can use the "rm" command.

**Comment by ajinkyak423** [comment]
https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/
this is the URL to the page on which there is mention of a command for CMD CLI but not for the BASH shell toclean up files after installation. 
![WhatsApp Image 2023-04-07 at 01 27 2](https://user-images.githubusercontent.com/77945065/230555035-bd5bf1ea-aaae-4f01-8f7b-1c90c3dfd878.jpg)
There is no "del" command in the bash shell instead one can use the "rm" command.

**Comment by dipesh-rawat** [comment]
@ajinkyak423 Thanks for providing additional info.

The [del command ](https://en.wikipedia.org/wiki/Del_(command)) is meant be used with **_PowerShell_** on Windows. From the attachment shared above I see `MINGW64` in prompt which I believe is the compiler used to build copy of bash that "git for Windows" includes and hence the bash shell as expected is flagging error for del command.

Having said that already have issue #40187 to remove cleanup steps advising the users to delete kubectl for Windows on this same [page](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/). Hope this helps.

**Comment by ajinkyak423** [comment]
@dipesh-rawat thank you for replying issue with taking following up
if someone is trying to install a service using bash shell will definitely find this helpful if they get stuck. 

looking forward to more meaningful contributions ✌️
