### ISSUE TITLE
Calling them 'worker node' is a misnomer.

### ISSUE THREAD

**Issue by 911432** [kubernetes/website#40554]
[A Kubernetes cluster consists of a set of worker machines, called nodes. And Every cluster has at least one worker node.](https://kubernetes.io/docs/concepts/overview/components/)

If node is called worker machine, Are 'worker nodes' called 'worker worker machines'?
It seems wrong in my opinion.
I think worker machine is called node not worker node.

**Comment by sftim** [comment]
PRs that improve on the wording here are welcome. If anyone's opening a PR, consider how the overall change helps readers understand Kubernetes and the difference between:
- control plane nodes 
- worker nodes (hosts that run as nodes and aren't part of the control plane)
- nodes in clusters that don't make a control plane / worker distinction

/language en

**Comment by 911432** [comment]
In my opinion, the 'control plan node' is wrong.
[The control plane manages the worker nodes and the Pods in the cluster.](https://kubernetes.io/docs/concepts/overview/components/)
I want to delete the worker in front of the node.

**Comment by KhushPatibandha** [comment]
hey I would like to help with this issue.
/assign

**Comment by neolit123** [comment]
did partial review on https://github.com/kubernetes/website/pull/40593
i think we should avoid making umbrella changes where the context switching is undesirable.

> If node is called worker machine, Are 'worker nodes' called 'worker worker machines'?

your observation is correct.

i think the sentence can be adjusted like so, perhaps;
https://kubernetes.io/docs/concepts/overview/components/

> A Kubernetes cluster consists of a set of machines, called [nodes](https://kubernetes.io/docs/concepts/architecture/nodes/), that run containerized applications. Every cluster has at least one node. Nodes specifically designated for managing workloads are often called worker nodes.

**Comment by 911432** [comment]
Nodes specifically designated for managing workloads is control plane?

https://kubernetes.io/docs/concepts/overview/components/
> The [control plane](https://kubernetes.io/docs/reference/glossary/?all=true#term-control-plane) manages the worker nodes and the Pods in the cluster.

So I want you to delete the word worker.

**Comment by 911432** [comment]
If there an additional kubelet, k-proxy in 6, 15, or 3 control plane have machine, Then I think there might be called control plane nodes.

**Comment by 911432** [comment]
If there are additional kubelet and k-proxy on multiple machines with control plane, then I think there might be called control plane nodes.

**Comment by 911432** [comment]
If there are additional kubelet and k-proxy on multiple machines with control plane, then I think there might be called control plane nodes.
So I think adding "Nodes specifically designated for managing workloads are often called worker nodes" is unnecessary.

**Comment by sftim** [comment]
> Nodes specifically designated for managing workloads are often called worker nodes.

This is a true statement. People who work with Kubernetes and who contribute to Kubernetes often do use that term.
We should document the ecosystem and software as we find it.

If we really, really want to deprecate the phrase “worker node”, there is a (complicated) [process](https://github.com/kubernetes/enhancements/tree/master/keps#readme) for that.

**Comment by 911432** [comment]
@sftim Node management is done by kube-controller-manager in the Control Plane, right?

**Comment by 911432** [comment]
@sftim Node management is done by kube-controller-manager in the Control Plane, right?
Do so called Worker Nodes have kube-controller-manager?

**Comment by sftim** [comment]
Essentially, a control plane node is running at least one control plane component (and might also run some app workloads). If there are no control plane components placed onto a node and none are expected, then it's a worker node. As a result, a worker node **doesn't** run the kube-controller-manager.

**Comment by 911432** [comment]
If A control plane node is running at least one control plane component and
A Worker Node is a node specifically designated for workload management.
I'll make a pull request that fits here.

**Comment by 911432** [comment]
@sftim 
How are you doing?
Worker node is not defined so I defined worker node.
This seems to require modification to the component as well.

**Comment by 911432** [comment]
@sftim @neolit123 I still can't distinguish between node and worker node.
In some places, the control plane is called a master node or control plane node, and the node is called a worker node.
If you have a Control Plane Node, the picture [here](https://github.com/kubernetes/website/blob/release-1.28/content/en/docs/concepts/overview/components.md) should change.

**Comment by 911432** [comment]
@sftim @neolit123 I still can't distinguish between node and Worker node.
In some places, the control plane is called a master node or control plane node, and the node is called a Worker node.
If you have a Control Plane Node and Worker Node, the picture [here](https://github.com/kubernetes/website/blob/release-1.28/content/en/docs/concepts/overview/components.md) should change.

**Comment by 911432** [comment]
@sftim @neolit123 I still can't distinguish between node and Worker node.
In some places, the control plane is called a Master node or Control Plane Node, and the node is called a Worker node.
If you have a Control Plane Node and Worker Node, the picture [here](https://github.com/kubernetes/website/blob/release-1.28/content/en/docs/concepts/overview/components.md) should change.

**Comment by sftim** [comment]
Although I can believe that the documentation we have right now might confuse readers, I do not agree that “worker node” is a misnomer.

/priority awaiting-more-evidence

https://kubernetes.io/docs/reference/glossary/?fundamental=true&architecture=true&operation=true#term-cluster is helpful but we might also want to add “worker node” into the glossary itself.

**Comment by 911432** [comment]
I created a pull request to explain in May 2023, but it got no response so I closed it.
Also, this [site](https://kubernetes.io/docs/concepts/overview/components/) should be changed to explain 'Control Plane Node', 'Worker Node', etc.

**Comment by 911432** [comment]
@sftim @neolit123 I still can't distinguish between node and Worker node.
In some places, the control plane is called a Master node or Control Plane Node, and the node is called a Worker node.
If you have a Control Plane Node and Worker Node, the picture [here](https://github.com/kubernetes/website/blob/release-1.28/content/en/docs/concepts/overview/components.md) should change.

**Comment by 911432** [comment]
Communication between nodes and control plane can be known by reading the [documentation](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/).

But I don't know much about worker nodes or control plane nodes.

**Comment by 911432** [comment]
@sftim @neolit123 Communication between nodes and control plane can be known by reading the [documentation](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/).

But I don't know much about worker nodes or control plane nodes.

**Comment by 911432** [comment]
@sftim @neolit123 Communication between nodes and control plane can be known by reading the [documentation](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/).

Some [documentation](https://kubernetes.io/docs/concepts/overview/components/) states that the control plane manages the worker nodes and pods in the cluster.

What [document](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node) is the control plane is one of the components of the node.

But I don't know much about worker nodes or control plane nodes.

**Comment by 911432** [comment]
@sftim @neolit123 Communication between nodes and control plane can be known by reading the [documentation](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/).

Some [documentation](https://kubernetes.io/docs/concepts/overview/components/) states that the control plane manages the worker nodes and pods in the cluster.

Some [documents](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node) say that the control plane is one of the components of a node.

This makes it impossible to know what a worker node and a control plane node are and what the difference is between a node and a worker node.

**Comment by sftim** [comment]
> Some [documents](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#steps-for-the-first-control-plane-node) say that the control plane is one of the components of a node.

OK, _that_ sounds like a bug; you can report that and ask for it to be fixed. However, I don't see any evidence of a page making that claim. You (or someone else) will need to provide that evidence @911432.

**Comment by 911432** [comment]
> OK, that sounds like a bug; you can report that and ask for it to be fixed. However, I don't see any evidence of a page making that claim. You (or someone else) will need to provide that evidence @911432.

@sftim Some [documents](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/overview/components.md) seem to communicate with control planes and nodes, but others ([high availability](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/production-environment/tools/kubeadm/high-availability.md), [kubeadm](https://github.com/kubernetes/website/blob/main/content/en/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md)) have the word control plane nodes that are considered components of nodes.

**Comment by 911432** [comment]
@sftim In this [picture](https://kubernetes.io/images/docs/components-of-kubernetes.svg), the control plane and the node appear to be communicating. So some [documents](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/architecture/control-plane-node-communication.md) state that the control plane manages operator nodes and pods in the cluster. But The [document](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/overview/components.md) says that the control plane manages the worker nodes and pods in the cluster, so it is unclear whether the control plane is managing nodes or worker nodes.
