### ISSUE TITLE
在 Windows 上安装 kubectl

### ISSUE THREAD

**Issue by asimplepeople** [kubernetes/website#40563]
del kubectl.exe kubectl.exe.sha256
is invalid 
use del kubectl.exe,kubectl.exe.sha256

**Comment by dipesh-rawat** [comment]
@asimplepeople There is an open issue https://github.com/kubernetes/website/issues/40187 raised for the equivalent English language page to remove cleanup steps advising the users to delete kubectl for Windows from https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/. Once those changes are merged, there would be equivalent changes of removing the `del` command instructions for the localised version of the page at [在 Windows 上安装 kubectl](https://kubernetes.io/zh-cn/docs/tasks/tools/install-kubectl-windows/)

**Comment by dipesh-rawat** [comment]
Page: https://kubernetes.io/zh-cn/docs/tasks/tools/install-kubectl-windows/
/language zh

**Comment by niranjandarshann** [comment]
Ref Comment https://github.com/kubernetes/website/issues/40563#issuecomment-1500932335
The PR https://github.com/kubernetes/website/pull/40449 against https://github.com/kubernetes/website/issues/40187 issue is merged. 
So You can take suitable action if you want.

**Comment by niranjandarshann** [comment]
As this issue was under inactivity from the long time thats why it is labelled as lifecycle rotten you may remove the lifecycle rotten and lifecycle stale by using command 
`/remove-lifecycle rotten` and `/remove-lifecycle stale`.

**Comment by niranjandarshann** [comment]
For now I am closing this issue you may reopen it if you want to work on it. as it undergoes in lifecycle rotten from long time.
/close
