### ISSUE TITLE
Troubleshooting kubeadm/Kubelet

### ISSUE THREAD

**Issue by rahmanhabib010** [kubernetes/website#40560]
I am trying to create a multi-master Kubernetes cluster. The version of Kubectl/Kubeadm/Kubelet that I installed is 1.23.8 and the corresponding docker version is 5:20.10.19~3-0~ubuntu-focal. Afterwrads, when I try to configure kubeadm to bootstrap the cluster, I got following error:

" [kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL [http://localhost:10248/healthz'](https://forum.linuxfoundation.org/home/leaving?allowTrusted=1&target=http%3A%2F%2Flocalhost%3A10248%2Fhealthz%27) failed with error: Get "[http://localhost:10248/healthz](https://forum.linuxfoundation.org/home/leaving?allowTrusted=1&target=http%3A%2F%2Flocalhost%3A10248%2Fhealthz)": dial tcp 127.0.0.1:10248: connect: connection refused.' "

Any help/suggestion/comment would be appreciated. Thanks in advance.

**Comment by neolit123** [comment]
hi, it would be best to ask on support channels. please see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
