### ISSUE TITLE
Set up Ingress on Minikube with the NGINX Ingress Controller

### ISSUE THREAD

**Issue by nimbusparis** [kubernetes/website#40576]
Please add in Before you begin section that if you use Minikube under windows or using Docker, you should enable CNI for the cluster.

**Comment by dipesh-rawat** [comment]
Page: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

/language en

**Comment by niranjandarshann** [comment]
As this issue is having any activity from the long time 
So I am closing this issue.
Feel free to reopen it if you want to work on it and the issue need to b e updated in docs.
