### ISSUE TITLE
Missing documentation for between pods' synchronisation in a StatefulSet

### ISSUE THREAD

**Issue by abishgj-rzt** [kubernetes/website#4057]
The StatefulSet documentation does not talk about the synchronisation  between the pods of the Set.

As the example given in the [documentation](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#updating-containers): a StatefulSet called 'web' has been deployed with 2 replicas. I would like to know how does these 2 pods will be synchronised. 

Is it completely synchronous (for example synched for every second or something) ?

Also, if a service is open for a StatefulSet then how will it hit to the pods ? Does it hit in RoundRobin fashion or any other way ?

I have deployed a Kafka-Zookeeper StatefulSet on Kubernetes. I have two replicas of Zookeeper StatefulSet. There is also a service running on port 2181 (zookeeper client). The issue is, sometimes it lists the topics I have created and sometimes it doesn't.

This infrastructure is near to a production roll out. Faster response would be appreciated.

**Comment by tengqm** [comment]
Not sure if Kubernetes will do _any_ thing to "synchronize" the replicas. The idea of StatefulSet is to let the application take control of its clustering. Kubernetes is not in that loop.

As for load-balancing, it depends. Different load-balancer configuration will spread loads in different ways. Kube-proxy has some preliminary LB support but I guess you are using some external LB box in a production environment.
