### ISSUE TITLE
Improve clarity of kubectl Cheat Sheet with version information

### ISSUE THREAD

**Issue by rainbowBPF2** [kubernetes/website#40582]
Feedback a confusing point about kubectl command on page: 
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#formatting-output 

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/21291684/230823434-2da9113e-138b-4e1e-9e02-01bdf2b49273.png">

"kubectl events " command seems just available in k8s-v1.26 release version, while below v1.26 not work yet.

so a brief tip or comment on the page will be easy to understand.

FYI.

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/reference/kubectl/cheatsheet/#formatting-output
/language en
/kind suggestion

**Comment by dipesh-rawat** [comment]
In my opinion, the cheat sheet is accurate for Kubernetes v1.26. However, if someone needs to refer to older documentation, they can access it by using the version selector option in the navigation bar. 
To improve clarity, the cheat sheet could integrate details from https://kubernetes.io/docs/home/supported-doc-versions/ and provide explicit links within the content body to the other available versions. This approach would be more effective than simply relying on the version selector in the top navigation. Would folks consider this suggestion beneficial?

**Comment by dipesh-rawat** [comment]
/retitle Improve clarity of kubectl Cheat Sheet with version information

**Comment by sftim** [comment]
I recommend the simple comment approach. We can still use version shortcodes, eg `{{< skew currentVersion >}}` in the comment.
/triage accepted

**Comment by mrgiles** [comment]
FYI @sftim
