### ISSUE TITLE
Secrets documentation has a broken link for how Secrets are automatically updated

### ISSUE THREAD

**Issue by holdeneoneal** [kubernetes/website#40592]
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/configuration/secret.md has a section called "Editing a Secret". In that section there is a link to another section titled "#mounted-secrets-are-updated-automatically" but that section does not exist in the markdown.

**Comment by holdeneoneal** [comment]
There are two possible solutions I can think of, the first is to update the Secrets page to reference the section in the ConfigMaps page(https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically) the other is to recreate the section in the Secrets page that makes the Secrets page link valid again. The former seems the better option.

**Comment by KhushPatibandha** [comment]
I also think that linking this to [link](https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically) would be the correct way of doing it.

**Comment by dipesh-rawat** [comment]
There is already a issue #40042 (PR #40103) raised for the same.

/triage duplicate

**Comment by dipesh-rawat** [comment]
Duplicated by https://github.com/kubernetes/website/issues/40042

/close
