### ISSUE TITLE
Topology-aware traffic routing with topology keys is deprecated, possibly removed. 

### ISSUE THREAD

**Issue by reylejano** [kubernetes/website#40600]
**This is a Bug Report**

**Problem:**
Topology-aware traffic routing with topology keys is deprecated since 1.21
Confirm if it's removed and remove the related documentation if feature is removed

**Proposed Solution:**
Remove Service Topology page 

**Page to Update:**
https://k8s.io/docs/concepts/services-networking/service-topology/

Deprecated since 1.21

**Comment by dipesh-rawat** [comment]
I can look into this.
/assign

**Comment by sftim** [comment]
Thanks @dipesh-rawat
