### ISSUE TITLE
Mermaid diagrams broken for `Pod Topology Spread Constraints`

### ISSUE THREAD

**Issue by dzoech** [kubernetes/website#40613]
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-one-topologyspreadconstraint

```
Syntax error in graph
mermaid version 8.13.4
```

**Comment by dipesh-rawat** [comment]
/retitle Mermaid diagrams broken for `Pod Topology Spread Constraints`
There is already a similar issue #31960 raised for broken Mermaid diagrams.

@dzoech Could you please tell us what browser and OS you are viewing the page on?

/triage needs-information

**Comment by dzoech** [comment]
Firefox 111.0.1 (64-bit) on Windows

Sorry for opening a duplicate ✌️

**Comment by dipesh-rawat** [comment]
/close
Duplicate of https://github.com/kubernetes/website/issues/31960
