### ISSUE TITLE
Explain extra step for exposing Services locally on minikube

### ISSUE THREAD

**Issue by EdCarney** [kubernetes/website#40645]
The following step does not work:

  Now we can test that the app is exposed outside of the cluster using curl, the IP address of the Node and the externally exposed port:
  `curl http://"$(minikube ip):$NODE_PORT"`

Steps are in the following places:

- https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/ (Load Balancing section)
- https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/ (Create a new Service section)

Per the [docs](https://minikube.sigs.k8s.io/docs/handbook/accessing/#using-minikube-service-with-tunnel) Minikube requires that Services of type NodePort be exposed with `minikube service <service-name> --url`. Recommend adding a step to run this Minikube command in a separate terminal instance, copy the URL from this command, and curl that URL.

**Comment by afbjorklund** [comment]
It depends on the minikube driver, but you are right that the step is required if using Docker Desktop (without an IP)

https://docs.docker.com/desktop/networking/#per-container-ip-addressing-is-not-possible

**Comment by sftim** [comment]
/retitle Explain extra step for exposing Services locally on minikube

If some minikube drivers need it, we should mention that.
/kind bug
/language en
/priority backlog
/triage accepted

**Comment by mrgiles** [comment]
@sftim, should we repeat the instructions shown in the existing [minikube documentation](https://minikube.sigs.k8s.io/docs/handbook/accessing/#nodeport-access) or just add a link to said document? I think I read somewhere that we should avoid repeating documentation. Or should we rewrite the minikube commands to align them to the tutorial? Thanks!

@EdCarney @afbjorklund

**Comment by afbjorklund** [comment]
Nothing for me here, seems to be documented. This tutorial is outdated, as far as I know.

https://minikube.sigs.k8s.io/docs/handbook/accessing/#using-minikube-service-with-tunnel

**Comment by sftim** [comment]
> @sftim, should we repeat the instructions shown in the existing [minikube documentation](https://minikube.sigs.k8s.io/docs/handbook/accessing/#nodeport-access) or just add a link to said document? I think I read somewhere that we should avoid repeating documentation. Or should we rewrite the minikube commands to align them to the tutorial? 

Any of those is fine. I do not have an opinion on which is best.

**Comment by sftim** [comment]
Help with a fix is very welcome. If you'd like to help but aren't sure how: please ask in #sig-docs on the Kubernetes Slack workspace. If you're not already a member of that workspace, you can visit https://slack.k8s.io/ for an invitation.

**Comment by adityasamant25** [comment]
A very nice note has already been added in the live documentation as can be seen here. [Using a Service to Expose Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/)

I will create a PR to add a similar note to [Running Multiple Instances of Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/)

This should be sufficient in my opinion.
