### ISSUE TITLE
Broken Link in Feature Gates

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#40653]
**This is a Bug Report**

**Page**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Under the section**
`ElasticIndexedJob`
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/docs/concepts/workloads/controllers/job#elastic-indexed-jobs

**Comment by mengjiao-liu** [comment]
/triage accepted

FYI: 
Correct link: https://kubernetes.io/docs/concepts/workloads/controllers/job/#elastic-indexed-jobs
