### ISSUE TITLE
Document format for container image references

### ISSUE THREAD

**Issue by zeroboovn** [kubernetes/website#40664]
The doc says `There are additional rules about where you can place the separator characters (_, -, and .) inside an image tag.`  
But i can't found these information any where. Please give more explanation or reference to where it cited

**Comment by niranjandarshann** [comment]
> The doc says `There are additional rules about where you can place the separator characters (_, -, and .) inside an image tag.` But i can't found these information any where. Please give more explanation or reference to where it cited

@zeroboovn This sentence basically refers to Tags or different version of the image.  Image tags consist of lowercase and uppercase letters, digits, underscores ( _ ), periods ( . ), and dashes ( - ). Let say version as <image-name>: v1.2.4.0 so here in the  tag you can see periods(.) are used for the separation. Similar ways its stating that Separator character ( _, - and  . )can be  used in many  image tag.

**Comment by sftim** [comment]
/kind feature
/priority backlog
/triage accepted

Thanks for the suggestion.

/help

**Comment by sftim** [comment]
For a reference about image identifiers, see https://github.com/opencontainers/distribution-spec/blob/v1.0.1/spec.md#workflow-categories

**Comment by sftim** [comment]
/retitle Document format for container image references

**Comment by RayAsh37** [comment]
Hi

**Comment by vaibhav2107** [comment]
@nitishfy Are you still working on this issue?

**Comment by sergeyshevch** [comment]
/close

Covered in #45788
