### ISSUE TITLE
Incorrect cheat sheet entry: List all warning Events

### ISSUE THREAD

**Issue by ehmad11** [kubernetes/website#40683]
**This is a Bug Report**

**Problem:**
In the cheat sheet page, following command is suggested to list all warning events:

`kubectl events --types=Warning
`

I get this error when I run this command 

> error: unknown command "events" for "kubectl"

**Proposed Solution:**

I think it should be replaced by following:

`kubectl get events --field-selector type=Warning
`

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-and-finding-resources

Kubernetes Version: v1.26.1

**Comment by dipesh-rawat** [comment]
> kubectl events --types=Warning 

The above commands works for me on v1.27.  But agree with suggestion https://github.com/kubernetes/website/issues/40683#issuecomment-1508575552 to provide an example having the mention of namespace to get some useful output instead of `No events found in default namespace.` (in most cases).

**Comment by ehmad11** [comment]
> > kubectl events --types=Warning
> 
> The above commands works for me on v1.27. But agree with suggestion [#40683 (comment)](https://github.com/kubernetes/website/issues/40683#issuecomment-1508575552) to provide an example having the mention of namespace to get some useful output instead of `No events found in default namespace.` (in most cases).

It would be helpful if compatibility information for specific versions is clearly stated and a separate page for events should be added similar to other API resources. Also, v.1.27 is just released and even the AWS EKS doesn't support it yet.

**Comment by sftim** [comment]
/remove-triage accepted

Oops. I tested with an old kubectl version.

We don't provide compatibility information for each subcommand of `kubectl`. If someone would like to maintain that information (and commit to keeping it maintained), the help will be appreciated - but it's a big undertaking.

We could add a comment to that line to mention that older kubectl versions don't provide this subcommand.

**Comment by dipesh-rawat** [comment]
The problem appears to be identical to #40582 and may be a duplicate. It seems that people are having trouble with the `kubectl events` command in the cheatsheet. Perhaps it would be beneficial to temporarily include version information with the `events` command.

Refer: [kubectl events enhancement](https://github.com/kubernetes/enhancements/issues/1440)

**Comment by ehmad11** [comment]
I am closing the ticket as there is already version selection drop down at top right menu bar where you can select a version and it will provide commands specific to that version :)
