### ISSUE TITLE
[ko]Translate docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes into Korean

### ISSUE THREAD

**Issue by dewble** [kubernetes/website#40688]
**This is a Feature Request**

**What would you like to be added**

Translate ```docs/tasks/administer-cluster/upgrading-linux-nodes```  into Korean
- page: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes/
- File: https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes.md

**Why is this needed**
Not translated yet

**Comments**

/language ko

**Comment by shubham-singh-748** [comment]
can i work in this issue
/assign

**Comment by jihoon-seo** [comment]
@shubham-singh-748 please note that @dewble, the author of this issue, previously assigned himself and opened a PR (#40690) to resolve this issue, before you assigned yourself.
(After that he unassigned himself, but I guess that that was an unintended mistake.)

And please find the comments https://github.com/kubernetes/website/pull/40716#pullrequestreview-1387022633 and https://github.com/kubernetes/website/pull/40716#issuecomment-1510930603, which are in the PR you opened.

**Comment by jihoon-seo** [comment]
This issue has been resolved by
- #40690
- #41321

Thank you!
/close
