### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configmap/

### ISSUE THREAD

**Issue by simantpurohit** [kubernetes/website#4070]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The page describes how to create a config map. The commands refer to paths in the repository "--from-file=docs/user-guide/configmap/kubectl" which no longer exist.

**Proposed Solution:**
Would be really helpful if the paths were updates in the commands on the page,

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configmap/

**Comment by simantpurohit** [comment]
My bad, I did not pull the latest version

**Comment by tengqm** [comment]
This issue is still there. We are assuming that users are working with a local clone of the website repo. This is a bad assumption. We'd better revise the text to make things work even if readers are not working with a git clone of the website project.

**Comment by G-Harmon** [comment]
I just hit this issue too. It's not obvious at all that this does not work just copying the commands from the web site.

**Comment by ajaeger** [comment]
/assign

The page is now at https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/ and change #8611 fixes the problem. I'll close this issue now.
