### ISSUE TITLE
Docs break horizontal scrolling.

### ISSUE THREAD

**Issue by mml** [kubernetes/website#4072]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
On some browsers, https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/ and probably other URLs, some docs aren't visible, and horizontal scrolling is disabled.

**Proposed Solution:**
Re-enable horizontal scrolling or fix the wrapping or something.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

My display is 1200w x 1920h, and my browser (Chrome on Linux) is full-width.  If I zoom to less than 100%, I can read all the text.  I'll attach a screenshot.

**Comment by mml** [comment]
![docs-scrolling](https://user-images.githubusercontent.com/3115/27108701-89030172-5053-11e7-95c3-70511dcf15d4.png)

**Comment by ahmetb** [comment]
It looks like this is limited only to `<table>`s and `<pre>`s etc. The text resizes fine. 

From your screenshot I can tell that the responsive breakpoints are probably not that great, as ~40% of the horizontal space is taken up by left sidebar. ☹️

**Comment by ahmetb** [comment]
Sorry didn't mean to close.

**Comment by tengqm** [comment]
/remove-lifecycle rotten
This is still a problem to be addressed.

**Comment by ahmetb** [comment]
Still a problem.

**Comment by ajaeger** [comment]
We switched the tools for generating our website and looking at the page, it looks fine now on my system.

@ahmetb , could you check whether this is fixed for you now, please?

**Comment by DanyC97** [comment]
i've double check and i don't see any problem on latest docs release.

/close
