### ISSUE TITLE
Connecting Applications with Services - CN discrepancy 

### ISSUE THREAD

**Issue by dewijones92** [kubernetes/website#40726]
https://kubernetes.io/docs/tutorials/services/connect-applications-service/ links to https://github.com/kubernetes/examples/tree/master/staging/https-nginx/
The repo creates a cert that contains:        ` Issuer: CN = nginxsvc, O = nginxsvc`  
The subsequent tutorial steps require `CN=my-nginx`

**Comment by sftim** [comment]
We could:
- pin to a specific commit (eg `bc9ca4ca32bb28762ef216386934bef20f1f9930`)
- update the tutorial to match the examples repo
- both of those things
