### ISSUE TITLE
Description about emptyDir sizeLimit is not correct

### ISSUE THREAD

**Issue by ziyi-xie** [kubernetes/website#40723]
**This is a Bug Report**

**Problem:**
The description about emptyDir sizeLimit in https://kubernetes.io/docs/concepts/storage/volumes/#emptydir page mentioned that:
> Note: If the SizeMemoryBackedVolumes feature gate is enabled, you can specify a size for memory backed volumes. If no size is specified, memory backed volumes are sized to 50% of the memory on a Linux host.

But the following code shows that if no size is specified, size limit defaults to node allocatable memory. https://github.com/kubernetes/kubernetes/blob/aa026a6b30892f9bfeb123ed902dd77dc382c15b/pkg/volume/emptydir/empty_dir.go#L122

Here is the information about my local environment and the result:
```
$ ps aux | grep kube-apiserver
 --feature-gates=SizeMemoryBackedVolumes=true  (The rest is omitted.)
$ kubectl version --short
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.26.3

$ cat emptydir-mem.yaml
apiVersion: v1
kind: Pod
metadata:
  name: emptydir-mem
spec:
  containers:
  - name: con1
    image: nginx
    command: ["/bin/bash", "-c"]
    args:
      - |
       trap "trap - TERM; kill 0; exit" TERM
       tail -f /dev/null & wait
    volumeMounts:
    - name: vol
      mountPath: /empty-dir
  volumes:
  - name: vol
    emptyDir:
      medium: Memory

$ kubectl apply -f emptydir-mem.yaml 
pod/emptydir-mem created

$ kubectl exec -it emptydir-mem -c con1 -- /bin/sh
# df -h /empty-dir
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            32G     0   32G   0% /empty-dir
# findmnt /empty-dir
TARGET     SOURCE FSTYPE OPTIONS
/empty-dir tmpfs  tmpfs  rw,relatime,size=32787332k
# exit

$ kubectl get pod -o wide
NAME           READY   STATUS    RESTARTS   AGE     IP           NODE       NOMINATED NODE   READINESS GATES
emptydir-mem   1/1     Running   0          2m43s   10.244.0.3   minikube   <none>           <none>
$ kubectl describe node minikube | grep memory
  MemoryPressure   False   Fri, 14 Apr 2023 01:21:53 +0000   Fri, 14 Apr 2023 00:30:07 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  memory:             32787332Ki
  memory:             32787332Ki ★ Allocatable memory
  memory             170Mi (0%)  170Mi (0%)
 ```

**Proposed Solution:**
Change this description to the following:
> Note: If the SizeMemoryBackedVolumes feature gate is enabled, you can specify a size for memory backed volumes. If no size is specified, memory backed volumes are sized to node allocatable memory.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

/assign
/language en
/sig storage

**Comment by ziyi-xie** [comment]
Could I ask that if no size is specified, why would memory backed volumes be sized  to 50% of the memory on a Linux host? Is it because the tmpfs default size=50% of physical RAM?

**Comment by shu-mutou** [comment]
@SergeyKanzhelev 
The memory-backed EmptyDir by default consumes a very large amount of memory (documented as `50%`, but actually `NodeAllocatable`). I think it's too large for the default.
In fact, one pod can occupy most of a node's memory.
Is there any way to limits the size of memory-backed EmptyDir by cluster admin?

**Comment by tengqm** [comment]
I'm not aware of any existing mechanisms to automate the setting of `sizeLimit` for `emptyDir` volumes. You may have to devise your own mutating webhook or wait for the mutating admission policy to land.  -- my 2 cents.

**Comment by shu-mutou** [comment]
@tengqm Thank you for your advice!

But it's problem that the whole of cluster can be down easily by few pods and the cluster admin can not control this, IMHO.
I have a few idea for this problem:
* Set the default size of memory-backed EmptyDir fewer. e.g. 50Mi.
* Enable to be controlled the total size of memory-backed EmptyDir
* Add taint to node for that memory-backed EmptyDir can use

@SergeyKanzhelev WDYT?

**Comment by shu-mutou** [comment]
I'd like to discuss about this in https://github.com/kubernetes/kubernetes/issues/119611 . Thanks!!
