### ISSUE TITLE
Inconsistent docs for whether `.spec.ipFamilies` field is immutable for Service

### ISSUE THREAD

**Issue by akhilles** [kubernetes/website#40728]
In concept docs (https://kubernetes.io/docs/concepts/services-networking/dual-stack/):

> _Note_: The `.spec.ipFamilies` field is immutable because the `.spec.ClusterIP` cannot be reallocated on a Service that already exists. If you want to change `.spec.ipFamilies`, delete and recreate the Service.

but in API docs (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#servicespec-v1-core):

> This field is conditionally mutable: it allows for adding or removing a secondary IP family, but it does not allow changing the primary IP family of the Service.

It's also a bit unclear what "primary IP family" means. My first thought was the primary IP family is what's used for `.spec.ClusterIP` (as opposed to `.spec.ClusterIPs` which includes *all* IP families, not just the primary). Is that interpretation correct? If so, it might be better to avoid that terminology because there's also this text in the concept docs which makes "primary" overloaded:

> The field `.spec.ClusterIPs` is the primary field, and contains both assigned IP addresses; `.spec.ClusterIP` is a secondary field with its value calculated from `.spec.ClusterIPs`.

**Comment by sftim** [comment]
We might also want to reword:

> This field is conditionally mutable: it allows for adding or removing a secondary IP family, but it does not allow changing the primary IP family of the Service.

however, the focus of _this_ issue is removing an inconsistency.

**Comment by tengqm** [comment]
/triage accepted
Let's make this clearer.

**Comment by nitishfy** [comment]
/unassign @taniaduggal 
This issue is open to work on. Feel free to assign.
