### ISSUE TITLE
Improve documentation for `kubernetes.io/enforce-mountable-secrets` annotation on `ServiceAccount`

### ISSUE THREAD

**Issue by jbg** [kubernetes/website#40727]
The documentation for the `kubernetes.io/enforce-mountable-secrets` annotation on `ServiceAccount` consists of [this paragraph on the **Well-Known Labels, Annotations and Taints** page](https://kubernetes.io/docs/reference/labels-annotations-taints/#enforce-mountable-secrets):

> The value for this annotation must be true to take effect. This annotation indicates that pods running as this service account may only reference Secret API objects specified in the service account's secrets field.

This leaves unclear the details of the actual effect of the annotation. By checking [the code](https://github.com/kubernetes/kubernetes/blob/release-1.26/plugin/pkg/admission/serviceaccount/admission.go#L302) I was able to determine that setting this annotation to `true` causes the following enforcements:

(1) `Secret`s mounted as `volumes` must appear in the `ServiceAccount`'s `secrets`
(2) `Secret`s referenced in `envFrom` in `containers` or `initContainers` must appear in the `ServiceAccount`'s `secrets`
(3) `Secret`s referenced in `imagePullSecrets` of `Pod`s must appear in the `ServiceAccount`'s `imagePullSecrets`

(1) is implied by the name of the annotation, but the lack of any mention of (2) or (3) in the documentation forced me to check the code to ensure that it wasn't only enforcing *mounting* of `Secret`s as the name implies. The documentation also mentions only the `secrets` field of the `ServiceAccount`, yet the enforcement also takes into account the `ServiceAccount`'s `imagePullSecrets` field (which the `Pod`'s `imagePullSecrets` are checked against).

The documentation would be improved by describing the actual enforcement behaviour that this feature implements.

This feature may also benefit from being mentioned in the [Good practices for Kubernetes Secrets](https://kubernetes.io/docs/concepts/security/secrets-good-practices/) document.

**Comment by Sai-Adarsh** [comment]
I see [docs](content/en/docs/reference/labels-annotations-taints/_index.md), can come up with something like:

```
kubernetes.io/enforce-mountable-secrets
Type: Annotation

Example: kubernetes.io/enforce-mountable-secrets: "true"

Used on: ServiceAccount

The value for this annotation must be true to take effect. This annotation indicates that Pods running as this ServiceAccount may only reference Secret API objects specified in the ServiceAccount's secrets field, including:
- Secrets mounted as volumes.
- Secrets referenced in the `envFrom` fields of containers or initContainers.
- Secrets referenced in the `imagePullSecrets` of Pods.
```

@tengqm I'll take this up?
