### ISSUE TITLE
Adding the Correct Path for Reference Documents.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [kubernetes/website#40736]
**This is a Bug Report**

## Describing Problem:

Bug on: [_index.md](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/_index.md)
Bug on: [contribute-upstream.md](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/contribute-upstream.md)
Bug on: [kubectl.md](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/kubectl.md)
Bug on: [kubernetes-api.md](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/kubernetes-api.md)
Bug on: [kubernetes-components.md](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/kubernetes-components.md)
Bug on: [quickstart.md](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/quickstart.md)

During my review of the repository, I observed that the paths mentioned for the "reference documents" are not correctly redirecting the user to the intended document. This issue arises due to the use of relative URL paths, which only work when relative to the current page's URL.

## To Reproduce:

I would like to rectify the issue by adding the correct path for each of the reference documents mentioned in the markdown files. This will make it easier for users to navigate through the documents and create a more convenient learning environment.

Kindly assign me this issue. Thank you.😊

## Screenshots: (as the evidence of the problem)

- The issue occurred in the following section of the "_index.md" document:

<kbd>![image](https://user-images.githubusercontent.com/90326051/232575252-13dae43b-57aa-4825-9a26-9ad7f1902e20.png)</kbd>

- The issue occurred in the following section of the "contribute-upstream.md" document:

<kbd>![image](https://user-images.githubusercontent.com/90326051/232575593-75ff7a2a-0819-4d67-8936-bd164df57b74.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/90326051/232575489-f14cd201-80a4-42df-8d20-55e858824e96.png)</kbd>

- The issue occurred in the following section of the "kubectl.md" document:

<kbd>![image](https://user-images.githubusercontent.com/90326051/232579356-8d9ee3a1-fd25-4a18-a58b-ab39d44fdea9.png)</kbd>

- The issue occurred in the following section of the "kubernetes-api.md" document:

<kbd>![image](https://user-images.githubusercontent.com/90326051/232578994-1e68d547-0900-4431-b1db-1ddd5e106a52.png)</kbd>

- The issue occurred in the following section of the "kubernetes-components.md" document:

<kbd>![image](https://user-images.githubusercontent.com/90326051/232578834-ddd2e543-1811-4a85-b930-fb8f807f1780.png)</kbd>

- The issue occurred in the following section of the "quickstart.md" document:

<kbd>![image](https://user-images.githubusercontent.com/90326051/232578687-341c485e-906e-48c5-bc98-87827315b2ea.png)</kbd>

**Comment by KiranAminPanjwani** [comment]
Kindly assign me this issue. ✨

**Comment by dipesh-rawat** [comment]
@KiranAminPanjwani Nice job on taking the time to review the docs and bringing up your concerns! However, it's important to note that these relative links are intended to be rendered and use within https://kubernetes.io/  rather than on GitHub markdown pages, so this isn't an issues to worry about. Keep up the great work though!

**_Doc website links for the markdown in description:_**
https://kubernetes.io/docs/contribute/generate-ref-docs/
https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/
https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/
https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/
https://kubernetes.io/docs/contribute/generate-ref-docs/quickstart/
https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/

/language en

**Comment by KiranAminPanjwani** [comment]
> @KiranAminPanjwani Nice job on taking the time to review the docs and bringing up your concerns! However, it's important to note that these relative links are intended to be rendered and use within https://kubernetes.io/ rather than on GitHub markdown pages, so this isn't an issues to worry about. Keep up the great work though!
> 
> **_Doc website links for the markdown in description:_** https://kubernetes.io/docs/contribute/generate-ref-docs/ https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/ https://kubernetes.io/docs/contribute/generate-ref-docs/kubectl/ https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/ https://kubernetes.io/docs/contribute/generate-ref-docs/quickstart/ https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/
> 
> /language en

Okay sir, Noted. Thank you😊

**Comment by divya-mohan0209** [comment]
Since the comments have been addressed, we'll be closing this issue @KiranAminPanjwani . Thank you for bringing this up, once again!
/close
