### ISSUE TITLE
Event document - discrepancies

### ISSUE THREAD

**Issue by ming-ddtechcg** [kubernetes/website#40732]
I found some fields are different in the document at:
https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/#Event 

these fields are (attached the example of an event object below):
action - it does not show up.
deprecatedCount  - replacement of "count" and disappear?
deprecatedFirstTimestamp  - replacement of "firstTimestamp" and disappear?
deprecatedLastTimestamp  - replacement of "lastTimestamp" and disappear?
deprecatedSource  - replacement of "lastTimestamp" and disappear?
note - disappear?
regarding - disappear?
reportingController  - disappear?
series  - disappear?
eventTime - it is required but shows "null".

An exanple of the event object:

```
        {
            "apiVersion": "v1",
            "count": 1,
            "eventTime": null,
            "firstTimestamp": "2023-04-17T13:16:57Z",
            "involvedObject": {
                "apiVersion": "apps/v1",
                "kind": "ReplicaSet",
                "name": "kubernetes-dashboard-68997bf576",
                "namespace": "kubernetes-dashboard",
                "resourceVersion": "14303",
                "uid": "6f84ceb9-c2e6-46c3-a522-ba1e357b3a84"
            },
            "kind": "Event",
            "lastTimestamp": "2023-04-17T13:16:57Z",
            "message": "Created pod: kubernetes-dashboard-68997bf576-9wb5s",
            "metadata": {
                "creationTimestamp": "2023-04-17T13:16:57Z",
                "name": "kubernetes-dashboard-68997bf576.1756bb4553cc2b47",
                "namespace": "kubernetes-dashboard",
                "resourceVersion": "944945",
                "uid": "95cb2331-e750-4fa3-bcd7-792cec7bcda6"
            },
            "reason": "SuccessfulCreate",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "replicaset-controller"
            },
            "type": "Normal"
        }
```

my k8s cluster and it is running version:

```
$ kubectl get nodes
NAME               STATUS   ROLES                  AGE     VERSION
kubee-infr1-test   Ready    worker                 4d17h   v1.27.0
kubee-mn1-test     Ready    control-plane,master   4d19h   v1.27.0
kubee-mn2-test     Ready    control-plane,master   4d19h   v1.27.0
kubee-mn3-test     Ready    control-plane,master   4d19h   v1.27.0
kubee-wn1-test     Ready    worker                 4d17h   v1.27.0
kubee-wn2-test     Ready    worker                 4d17h   v1.27.0
kubee-wn3-test     Ready    worker                 4d17h   v1.27.0
```

I am not sure that the event document is the reference that I am looking for the explanation about the event object.  Please advise.

Thanks.

**Comment by sftim** [comment]
You might be looking at the wrong Event API.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#event-v1-core is deprecated; see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#event-v1-events-k8s-io for the replacement.

/kind support

**Comment by ming-ddtechcg** [comment]
The replacement link (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#event-v1-events-k8s-io) contains exact fields which I mentioned in my first post, for example:

```
deprecatedFirstTimestamp is the deprecated field assuring backward compatibility with core.v1 Event type.
```

Fot the output, it is not in the result of "kubectl get events -A" 

Thanks.

**Comment by niranjandarshann** [comment]
/language en
/sig docs
Ref Link : https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/#Event

**Comment by sftim** [comment]
> The replacement link (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#event-v1-events-k8s-io) contains exact fields which I mentioned in my first post, for example:
> 
> > `deprecatedFirstTimestamp` is the deprecated field assuring backward compatibility with core.v1 Event type.
> 
> 
> Fot the output, it is not in the result of "kubectl get events -A"

OK, so what's the bug / discrepancy?

Is it that `kubectl` prefers the older (and deprecated) Event API if you don't explicitly specify which API you want to use, whereas lists the recommended API?

_[if so: I'd consider this a request to update `kubectl`; the documentation itself is current]_

**Comment by sftim** [comment]
/triage needs-information
@ming-ddtechcg we'd like to know what improvement you're recommending for the Kubernetes documentation.

**Comment by sftim** [comment]
/close not-planned

This issue isn't actionable as it stands.
