### ISSUE TITLE
Hyperlink from Deployment concept to “define environment variables for a container” task page

### ISSUE THREAD

**Issue by energister** [kubernetes/website#40735]
_[On [https://k8s.io/docs/concepts/workloads/controllers/deployment/](https://k8s.io/docs/concepts/workloads/controllers/deployment/)]_
there is no reference on how to define environment variables for a container (https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)

**Comment by sftim** [comment]
/retitle Hyperlink from Deployment concept to “define environment variables for a container” task page
/kind feature
/language en

**Comment by KhushPatibandha** [comment]
@energister can you suggest some specific location where making a change would work?
