### ISSUE TITLE
improvement in  Storage volumes. 

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#40742]
Unclear meaning of Second Problem in storage volume .
The volume paragraph in https://kubernetes.io/docs/concepts/storage/volumes/ page missing the description about the Second problem stated in the line 
**> A second problem occurs when sharing files between containers running together in a Pod.**

What is the "second problem" denoting here? 
I think brief introduction about it will be helpful.

**Comment by KhushPatibandha** [comment]
I think I can help with this.

/assign

**Comment by niranjandarshann** [comment]
/retitle unclear meaning of second problem in storage volume

**Comment by KhushPatibandha** [comment]
I have opened a PR for this issue do review it and lemme know if you have some feedback.

**Comment by tengqm** [comment]
/close
as resolved.
