### ISSUE TITLE
Partners sign-up form hard to find

### ISSUE THREAD

**Issue by bobsky** [kubernetes/website#4074]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
On the /Partners page, ending paragraph has a link to "partner request form" but can be difficult to spot

**Proposed Solution:**
Bold and underline the text for easier view

**Page to Update:**
https://kubernetes.io/partners/

Part of website design refresh/fixes -- unable to add label -- but it would be needs UX review
https://github.com/kubernetes/kubernetes.github.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+UX+Review%22

**Comment by tengqm** [comment]
@bobsky Looks to me the links are bold and highlighted now. Can we close this?
