### ISSUE TITLE
Аннотации

### ISSUE THREAD

**Issue by kircool** [kubernetes/website#40745]
Метаданные в аннотации могут быть маленькими или большими, структурированными или неструктурированными, кроме этого они **могут** включать символы, которые не разрешены в метках.

**Comment by kircool** [comment]
Hi!
I use Russian


вт, 18 апр. 2023 г., 10:21 Niranjan Darshan ***@***.***>:

**Comment by sftim** [comment]
Hi. Please file the issue in English, if feasible. I guess you're suggesting that могут is misspelled in some web page (which one?).

**Comment by Shubham82** [comment]
Closing this issue, as no information is provided, please reopen it with proper content if it is still not resolved.
/close
