### ISSUE TITLE
Incorrect output of `pod-template-hash` label in `kubernetes.io/docs/concepts/workloads/controllers/deployment`

### ISSUE THREAD

**Issue by YiNNx** [kubernetes/website#40751]
**This is a Bug Report**

**Page:** https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

**Problem:**

> 5. To see the ReplicaSet (`rs`) created by the Deployment, run `kubectl get rs`. The output is similar to this:
>
> ```
> NAME                          DESIRED   CURRENT   READY   AGE
> nginx-deployment-75675f5897   3         3         3       18s
> ```

> 6. To see the labels automatically generated for each Pod, run `kubectl get pods --show-labels`. The output is similar to:
>
>    ```
>    NAME                                READY     STATUS    RESTARTS   AGE       LABELS
>    nginx-deployment-75675f5897-7ci7o   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
>    nginx-deployment-75675f5897-kzszj   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
>    nginx-deployment-75675f5897-qqcnn   1/1       Running   0          18s       app=nginx,pod-template-hash=3123191453
>    ```
>
>    The created ReplicaSet ensures that there are three `nginx` Pods.

In the later paragraph above, the pods' `pod-template-hash` label should be corresponding to their replicaSets', which is `75675f5897`. The output of pods' `NAME` correctly contains their pod-template-hash `75675f5897`, but the output of `LABELS` is incorrect. 

**Proposed Solution:**

Maybe the output of `pod-template-hash` label in `kubectl get pods --show-labels` should be `pod-template-hash=75675f5897` instead of `pod-template-hash=3123191453`.

**Comment by T-Lakshmi** [comment]
The HASH string is the same as the pod-template-hash label on the ReplicaSet.
Verified this behaviour.
![show-labels](https://user-images.githubusercontent.com/56723673/232986426-e75c2ede-1cf6-4b5e-82c2-a5e24cb3caf4.png)

/kind bug

**Comment by YiNNx** [comment]
> The HASH string is the same as the pod-template-hash label on the ReplicaSet. Verified this behaviour. ![show-labels](https://user-images.githubusercontent.com/56723673/232986426-e75c2ede-1cf6-4b5e-82c2-a5e24cb3caf4.png)
> 
> /kind bug

Thanks for your verification!

**Comment by YiNNx** [comment]
@mengjiao-liu Could you please help to check this issue? 

The bug has been verified and I have submitted a PR a few days ago.

Thanks a lot

**Comment by mengjiao-liu** [comment]
I've checked this behavior in my environment, and you're right.
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/44460091/234196533-648edea1-19e5-4668-aaa9-5b33f9343614.png">

**Comment by YiNNx** [comment]
Fixed by #40752
