### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/access-cluster/

### ISSUE THREAD

**Issue by renewooller** [kubernetes/website#4076]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The URL for Proxy via the api server is out of date in the documentation:
http://localhost:8080/api/v1/namespaces/kube-system/services/elasticsearch-logging/proxy/

**Proposed Solution:**
http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging/

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
/close

Please refer to #7902
