### ISSUE TITLE
Add the navigation link to [volume type] 

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#40767]
**This is a Feature Request**

Add the navigation link to `volume type` .

**What would you like to be added**
`volume type` context which is there in [Background](https://kubernetes.io/docs/concepts/storage/volumes/#background) subheading.
Page to be updated: [volumes](https://kubernetes.io/docs/concepts/storage/volumes/)

**Why is this needed**
Get an idea about supported  `volume types` .

**Comments**

**Comment by niranjandarshann** [comment]
If this need to be fixed I can create PR tomorrow

**Comment by niranjandarshann** [comment]
If this need to be fixed I can create PR tomorrow.
