### ISSUE TITLE
Get a Shell to a Running Container - unable to upgrade connection: container not found ("nginx")

### ISSUE THREAD

**Issue by eliassal** [kubernetes/website#40775]
When I run

`kubectl exec --stdin --tty shell-demo -- /bin/sh or bash`
after creating the pod, I get right away

> error: unable to upgrade connection: container not found ("nginx")

when I do kubectl get pods, I see pod in bad shape

```
NAME         READY   STATUS             RESTARTS      AGE
shell-demo   0/1     CrashLoopBackOff   5 (31s ago)   3m52s
```

Thanks for your help

**Comment by Shubham82** [comment]
Page: https://kubernetes.io/docs/tasks/debug/debug-application/get-shell-running-container/

**Comment by Shubham82** [comment]
Hi @eliassal 
It is working for me.

```
$ kubectl get pod shell-demo
NAME         READY   STATUS    RESTARTS   AGE
shell-demo   1/1     Running   0          48s
```
Could you please describe the pod by running `kubectl describe pod shell-demo` and check the events to find the error

**Comment by eliassal** [comment]
OK, here are the steps and the outputs, it is not possible to access the pod interactively

 `kubectl apply -f https://k8s.io/examples/application/shell-demo.yaml`
pod/shell-demo created
 `kubectl get pod shell-demo`
```
NAME         READY   STATUS    RESTARTS     AGE
shell-demo   1/1     Running   1 (4s ago)   10s
```
` kubectl exec --stdin --tty shell-demo -- /bin/bash`

> error: Internal error occurred: error executing command in container: failed to exec in container: failed to create exec "6574a42960f423a29ebaa6c9e8113a88f19033f4913a55e9e59bc82480c5ae48": task 7ba47042ab56fc8005759d4007f83fe31c57eddaf056fe251120f55de8e47d38 not found: not found

I reexecuted
`kubectl get pod shell-demo`

get

> NAME         READY   STATUS             RESTARTS      AGE
> shell-demo   0/1     CrashLoopBackOff   4 (67s ago)   3m3s

**Comment by eliassal** [comment]
Here is the output of describe
` kubectl describe pod shell-demo`
```
Name:             shell-demo
Namespace:        default
Priority:         0
Service Account:  default
Node:             chef-u16desk/192.168.1.17
Start Time:       Wed, 19 Apr 2023 14:45:51 +0200
Labels:           <none>
Annotations:      <none>
Status:           Running
IP:               192.168.1.17
IPs:
  IP:  192.168.1.17
Containers:
  nginx:
    Container ID:   containerd://12e697e542a27c623b1cfb6c81e14e45782a4b091b440a712bfb412e6006574c
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:63b44e8ddb83d5dd8020327c1f40436e37a6fffd3ef2498a6204df23be6e7e94
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 19 Apr 2023 14:49:18 +0200
      Finished:     Wed, 19 Apr 2023 14:49:20 +0200
    Ready:          False
    Restart Count:  5
    Environment:    <none>
    Mounts:
      /usr/share/nginx/html from shared-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wvbbr (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  shared-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-wvbbr:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m56s                  default-scheduler  Successfully assigned default/shell-demo to chef-u16desk
  Normal   Pulled     3m55s                  kubelet            Successfully pulled image "nginx" in 1.201357776s (1.201371576s including waiting)
  Normal   Pulled     3m49s                  kubelet            Successfully pulled image "nginx" in 1.121165211s (1.121183511s including waiting)
  Normal   Pulled     3m33s                  kubelet            Successfully pulled image "nginx" in 1.152851079s (1.152861479s including waiting)
  Normal   Pulled     3m1s                   kubelet            Successfully pulled image "nginx" in 1.121056111s (1.121065611s including waiting)
  Normal   Created    3m (x4 over 3m55s)     kubelet            Created container nginx
  Normal   Started    3m (x4 over 3m54s)     kubelet            Started container nginx
  Warning  BackOff    2m18s (x7 over 3m45s)  kubelet            Back-off restarting failed container nginx in pod shell-demo_default(6debe1d4-c051-4f0a-8dc6-6c5a54a2b0fc)
  Normal   Pulling    2m6s (x5 over 3m56s)   kubelet            Pulling image "nginx"
  Normal   Pulled     2m5s                   kubelet            Successfully pulled image "nginx" in 1.111654751s (1.111672451s including waiting)

```

**Comment by Shubham82** [comment]
Hi @eliassal
Do you have some other process or nginx pod using the same port 80? Because this error occurred when the port is being used by another nginx or some other process because the nginx container image is configured to run in port 80. (https://hub.docker.com/_/nginx)

**Comment by Shubham82** [comment]
I reproduced this one by deploying 2 nginx pods, I noticed that the second one gave the same error. i resolved this by deleting the first pod, by doing so second pod came into the running stage. See the below observation:

Deploy First Pod
```
apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default
```

   
```
$ kubectl get pod
NAME         READY   STATUS    RESTARTS   AGE
shell-demo   1/1     Running   0          22s

```
```
$ kubectl exec --stdin --tty shell-demo -- /bin/bash
root@minikube-vpa-0:/# 
```
Deploy Second pod

```
apiVersion: v1
kind: Pod
metadata:
  name: shell-demo-second
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default

```

```
$ kubectl get pod
NAME                READY   STATUS             RESTARTS      AGE
shell-demo          1/1     Running            0             3m32s
shell-demo-second   0/1     CrashLoopBackOff   4 (20s ago)   2m32s

```
```
$ kubectl delete pod shell-demo
pod "shell-demo" deleted
```
After deleting it was running

```
$ kubectl get pod
NAME                READY   STATUS    RESTARTS       AGE
shell-demo-second   1/1     Running   5 (104s ago)   3m56s
```


```
$ kubectl exec --stdin --tty shell-demo-second -- /bin/bash
root@minikube-vpa-0:/# 
```


So you have to check your cluster that is there any nginx pod / process using the port 80, then you have to delete that pod or kill that process.

**Comment by Shubham82** [comment]
Also if you want to change the default port used by nginx image rather than deleting the process/pod then you have to use cmd and args to update the default value of the port.

I tried the one which is mentioned under this: https://stackoverflow.com/questions/62637067/how-to-configure-an-echo-pod-on-different-port-instead-of-port-80-in-kubernetes

Please take a look at the above stackoverflow link.

**Comment by eliassal** [comment]
@Shubham82 , you are correct, yesterday, after adding

> - containerPort: 82

which did not help, I deleted 

> hostNetwork: true
>  dnsPolicy: Default

in the yml file and I was able to accedd the pod. So why/what this hostNetwork and dnsPolicy  param are there and why they are used?
Thanks

**Comment by dipesh-rawat** [comment]
@eliassal GitHub may not be the most suitable platform to seek support assistance. You could consider posting your question on alternative forums such as the Kubernetes Slack (http://slack.k8s.io/) or the Discuss Kubernetes (https://discuss.kubernetes.io/) forum, as they may provide more comprehensive and helpful responses.

**Comment by eliassal** [comment]
@dipesh-rawat , slack is not a good idea as you get lost very quickly and communication is not easy and cant explain an issue coirrectly, I have used https://discuss.kubernetes.io/ in the past but either responses never come or come very late.
Anyway, the link to create an issue page is found on the page itself on the mentioned page 

![image](https://user-images.githubusercontent.com/8447864/233362797-1a29c95a-2960-4e7d-afc8-3e9e3d4e3f2b.png)

**Comment by eliassal** [comment]
@Shubham82, I reverted back to the original yaml file with

> hostNetwork: true
> dnsPolicy: Default

it does not work

**Comment by Shubham82** [comment]
> So why/what this hostNetwork and dnsPolicy param are there and why they are used?

For hostNetwork and dnsPolicy please see the following k8s API page for pod: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/

**Comment by dipesh-rawat** [comment]
/close

This looks like a request for assistance. Nothing to fix in k8s docs.
Also, refer: https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by InfoNig** [comment]
hi,  I have too "unable to upgrade connection: container not found" question, and message have "killing container faild" log at node, and 1 zombie with the container，but I restart kubelet and kill zombie , pod restart  my question be gone，I want to know what causes this problem

**Comment by InfoNig** [comment]
> hi, I have too "unable to upgrade connection: container not found" question, and message have "killing container faild" log at node, and 1 zombie with the container，but I restart kubelet and kill zombie , pod restart my question be gone，I want to know what causes this problem

My pod's  status is running with container
