### ISSUE TITLE
Debug Services - error executing command in container: failed to exec in container: failed to start exec 

### ISSUE THREAD

**Issue by eliassal** [kubernetes/website#40774]
I am following this to the letter, created the hostnames deployment throuhg file and on commandline, I see 3 Pods created but cant access the pods interactively

It is indicated **"From a Pod in the same Namespace..."**  execute **"nslookup hostnames"**

Here is the output for kubectl get pods

```
 kubectl get pods -o wide
NAME                                    READY   STATUS    RESTARTS   AGE     IP            NODE           NOMINATED NODE   READINESS GATES
hello-world-689f56667c-bhx5s            1/1     Running   0          4h52m   10.10.69.22   chef-u16desk   <none>           <none>
hostnames-6d9d89c4b8-b44q8              1/1     Running   0          7m20s   10.10.69.30   chef-u16desk   <none>           <none>
hostnames-6d9d89c4b8-lfcv7              1/1     Running   0          11s     10.10.69.32   chef-u16desk   <none>           <none>
hostnames-6d9d89c4b8-xgvqf              1/1     Running   0          11s     10.10.69.31   chef-u16desk   <none>           <none>
```

I do

`kubectl exec -it hostnames-6d9d89c4b8-b44q8 -- /bin/sh`

I get

> error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "811161dd20b97bc3b5109d1b7828192cb48ebd829d6f4b6c78fec4c8d297fb55": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

So what is missing?

**Comment by tamilselvan1102** [comment]
Refer this to execute the pod [execPod](https://kubernetes.io/docs/tasks/debug/debug-application/get-shell-running-container/#opening-a-shell-when-a-pod-has-more-than-one-container)

**Comment by tamilselvan1102** [comment]
You can get more details by checking if pod is in Running state, its logs in dashboard or describing a pod.

**Comment by eliassal** [comment]
I tried all, I get the same exact error. Howver, I can do 
`curl http://podip:9376`
and I get a response as follows

> hostnames-7488bbbGG....

**Comment by eliassal** [comment]
@tamilselvan1102  , here is the output of 
`kubectl get pods -o wide`

```
NAME                                      READY   STATUS    RESTARTS   AGE   IP            NODE           NOMINATED NODE   READINESS GATES
hello-world-689f56667c-bhx5s              1/1     Running   0          26h   10.10.69.22   chef-u16desk   <none>           <none>
hostnames-7488b798f6-fjf9n                1/1     Running   0          17h   10.10.69.38   chef-u16desk   <none>           <none>
hostnames-7488b798f6-sl4bp                1/1     Running   0          17h   10.10.69.39   chef-u16desk   <none>           <none>
```

When I issue 
`kubectl logs hostnames-7488b798f6-fjf9n`
or
`kubectl logs hostnames-7488b798f6-sl4bp`

I get nothing

![image](https://user-images.githubusercontent.com/8447864/233315629-e3c53852-ed0e-4b05-a2bb-f3c7d11898a0.png)

**Comment by tamilselvan1102** [comment]
Some docker image does not come with a bash shell. I think it is the issue
ex: Alpine image doesn't have a bash shell.

**Comment by eliassal** [comment]
But at the url
https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/
it uses to create the Pods 
`kubectl create deployment hostnames --image=registry.k8s.io/serve_hostname`

and under the title

> Does the Service work by DNS name? 

It is clearly indicated

> From a Pod in the same Namespace:   

 
issue the following

`nslookup hostnames`

**Comment by tamilselvan1102** [comment]
if (dnsPolicy== Default)
   POD directly inherits DNS configuration of cluster nodes. 
   The /etc/resolv.conf file is directly used of nodes in the cluster.

The /etc/resolv.conf file defines how the system uses DNS to resolve host names and IP addresses.
So investigate resolv.conf file.

**Comment by dipesh-rawat** [comment]
@eliassal I would recommend it would be better to utilize alternative platforms such as the Kubernetes Slack (http://slack.k8s.io/) or the Discuss Kubernetes (https://discuss.kubernetes.io/) forum, rather than GitHub to help with this issue.

**Comment by sftim** [comment]
This does look like a request for help, rather than a report that the documentation is wrong.

I will close the issue. This GitHub issue tracker is not the right place to ask for advice with Kubernetes I'm afraid.

/close

**Comment by aryagupta-gh** [comment]
instead of /big/bash, just use bash

**Comment by surya818** [comment]
I have the same issue when im trying out using GitBash, Escaping backslashes fixes the problem

kubectl exec -it demopod -- //bin//sh

**Comment by eliassal** [comment]
Yes, It seems that the registry.k8s.io/serve_hostname is based on Alpine which has no bash shell, I did a search Alpine image is based on Ash (Almquist Shell) provided by BusyBox. I tried the following as indicated at https://stackoverflow.com/questions/35689628/starting-a-shell-in-the-docker-alpine-container

```
kubectl exec hostnames-58798d9c9b-4qpj2 -it -- sh
kubectl exec hostnames-58798d9c9b-4qpj2 -it -- /bin/ash
kubectl exec hostnames-58798d9c9b-4qpj2 -it -- /bin/sh
kubectl exec hostnames-58798d9c9b-4qpj2 -it -- /bin/ash
kubectl exec hostnames-58798d9c9b-4qpj2 -it -- ash
kubectl exec hostnames-58798d9c9b-4qpj2 -it -- sh

```
but nothing worked, always getting 

> error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "f06e021325514508cc43efe874d216a98abbb4e02bfa55d00dc627b31965faeb": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/ash": stat /bin/ash: no such file or directory: unknown......


I tried to find out the docker file for registry.k8s.io/serve_hostname  but it seems it is not possible. Can somebody confirm what shell is used in this image please?
Thanks
