### ISSUE TITLE
Numbering the [Types of volumes]

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#40773]
**This is a Feature Request**
Numbering the `Types of volumes` and change first letter as capital

**What would you like to be added**

**1.** AwsElasticBlockStore (deprecated)
**2.** AWS EBS CSI migration
**3.** AzureDisk (deprecated)
**4. A**zureDisk CSI migration
**5. A**zureDisk CSI migration complete
**6.A**zureFile (deprecated) 
**7.** .....

Page to be updated: [Types of volumes](https://kubernetes.io/docs/concepts/storage/volumes/#volume-types)

**Why is this needed**
This page having quite big list of volume types. it would be good looking if listed as 1,2,3, ....

**Comments**

**Comment by AmarNathChary** [comment]
I would like to work on this
/assign

**Comment by sftim** [comment]
I don't think we should number the different types of volumes. Why would that help?

/priority awaiting-more-evidence

**Comment by tamilselvan1102** [comment]
In this page listed many different types of volumes and it configuration and all are aligned in same indentation.
so reader get bit confused about whether is it type or it's configuration.
if numbering only the volume types, it would be clear and looks good.

**Comment by sftim** [comment]
OK, so a related problem might be that it's hard to tell what [level](https://www.w3.org/WAI/tutorials/page-structure/headings/) (or rank) of heading you're looking at. Does that sound right?

**Comment by tamilselvan1102** [comment]
Currently volumes name are in **h3** font and sub-headings are in **h4**. I tried sub-heading to **h5**, it also not not showing much appearance difference. I am suggesting numbering is the good solution

**Comment by sftim** [comment]
The suggestion as made won't work and we shouldn't do it. However, I would welcome another way to make it more clear that - for example - _AWS EBS CSI migration_ is a subheading of _`awsElasticBlockStore` (deprecated)_.

**Comment by sftim** [comment]
Hi. I'm writing as a tech lead for SIG Docs. This issue could be accepted, but it hasn't yet been.

I don't recommend starting on a PR for this issue until we've got a clear enough picture of what improvement we want to make.

**Comment by tamilselvan1102** [comment]
How about to highlight only following subheadings.
![image](https://user-images.githubusercontent.com/20103020/233628772-aacd8406-ab39-44c1-b5c7-70852cafaef3.png)
