### ISSUE TITLE
Not able to find which alpha feature gates for "Resize CPU and Memory Resources assigned to Containers" 

### ISSUE THREAD

**Issue by nashtsai** [kubernetes/website#40776]
Not able to find which alpha feature gates for [Resize CPU and Memory Resources assigned to Containers](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/#container-resize-policies)

**Comment by mengjiao-liu** [comment]
/kind feature
/triage accepted

> 	// Resources resize policy for the container.
	// +featureGate=InPlacePodVerticalScaling
	// +optional
	ResizePolicy []ContainerResizePolicy

This field is controlled by the feature gate `InPlacePodVerticalScaling`.

It looks like we need to add a feature gate description.

Does anyone want to help?
/help

**Comment by tengqm** [comment]
There is a blog under review. https://github.com/kubernetes/website/pull/39846

I do concur that some docs are needed for such an important feature.

**Comment by sftim** [comment]
We should mention `InPlacePodVerticalScaling` within https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/#container-resize-policies.

#39845 didn't cover this detail.

**Comment by nashtsai** [comment]
> InPlacePodVerticalScaling

InPlacePodVerticalScaling in also missing in  https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by tengqm** [comment]
Fix coming in https://github.com/kubernetes/website/pull/40623

**Comment by dipankardas011** [comment]
Hi @tengqm as I am unable see the changes can I add it to the page?

**Comment by tengqm** [comment]
> Hi @sftim , @tengqm as I am unable see the changes can I add it to the page?

The feature gate issue has been fixed but the feature description needs some more formal documentation. Please feel free to provide some inputs.

**Comment by dipankardas011** [comment]
> > Hi @sftim , @tengqm as I am unable see the changes can I add it to the page?
> 
> The feature gate issue has been fixed but the feature description needs some more formal documentation. Please feel free to provide some inputs.

sure so we need to add the featureGate thing?
here https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/

**Comment by tengqm** [comment]
> > > Hi @sftim , @tengqm as I am unable see the changes can I add it to the page?
> > 
> > 
> > The feature gate issue has been fixed but the feature description needs some more formal documentation. Please feel free to provide some inputs.
> 
> sure so we need to add the featureGate thing? here https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/

It is not limited to the feature gate. It is about the feature. We are supposed to provide some brief introduction to this feature. Currently we have some texts on it, but those texts are provided as a blog (see https://github.com/kubernetes/website/pull/39846). Some of the blogs could have been part of the docs task page (https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/).

**Comment by dipankardas011** [comment]
> > > > Hi @sftim , @tengqm as I am unable see the changes can I add it to the page?
> > > 
> > > 
> > > The feature gate issue has been fixed but the feature description needs some more formal documentation. Please feel free to provide some inputs.
> > 
> > 
> > sure so we need to add the featureGate thing? here https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/
> 
> It is not limited to the feature gate. It is about the feature. We are supposed to provide some brief introduction to this feature. Currently we have some texts on it, but those texts are provided as a blog (see #39846). Some of the blogs could have been part of the docs task page (https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/).

thanks for clarifying

**Comment by dshebib** [comment]
Note that this is the same issue as #41365
