### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/names/

### ISSUE THREAD

**Issue by yoHasse** [kubernetes/website#40787]
"...certain resources have more specific restrictions. See the [identifiers design doc](https://git.k8s.io/community/contributors/design-proposals/identifiers.md) for the precise syntax rules for names...."

The link to "identifiers design doc" doesn't exist.

**Comment by dipesh-rawat** [comment]
@yoHasse Could please confirm the you are looking at the latest documentation in the webpage https://kubernetes.io/docs/concepts/overview/working-with-objects/names/?

From my end, in the mentioned page I can only see the link to the _Identifiers and Names in Kubernetes design document_ in the [What's Next Section](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#what-s-next) and it points correctly to achieved [design-proposal repo](https://github.com/kubernetes/design-proposals-archive/blob/main/architecture/identifiers.md)

/triage needs-information

**Comment by yoHasse** [comment]
I searched on google and I now noticed that it sent me to https://pwittrock.github.io/docs/concepts/overview/working-with-objects/names/

Closing this Thank you for the response information!
