### ISSUE TITLE
Use Kubernetes blue as selection color

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#40793]
**This is a Feature Request**

**What would you like to be added**
Change the CSS so that [text selections use a custom color](https://css-tricks.com/overriding-the-default-text-selection-color-with-css/); in this case, [Kubernetes blue](https://cncf-branding.netlify.app/projects/kubernetes/#colors) (hex `#326ce5`).

**Why is this needed**
I'm filing this because:
- it can be a good first issue
- incremental brand improvements across the whole site are worth making
- it's useful to widen the pool of people who have worked on our CSS / SCSS.

**Comments**
/area web-development
/good-first-issue

ⓘ _If you have already worked on CSS for this website, please step back from working on this issue, so that another contributor can use it as_ their _first issue._

**Comment by T-Lakshmi** [comment]
I haven't worked on CSS or web-development area, so i am willing to take and start investigation on this.
Thanks,
/assign

**Comment by mostafahanafi** [comment]
@T-Lakshmi hi! just saw your message while submitting my PR, thought i'd let you know i think i've just already tackled it haha!

**Comment by T-Lakshmi** [comment]
@mostafahanafi,
Alright, please go ahead. unassigning myself.

/unassign

**Comment by sftim** [comment]
Done as an initial implementation in #40796

In 2023, we may not need the `-moz-` prefix which was there to support 2009-era Firefox. If anyone wants to tidy things up there, please do.

/close

**Comment by mostafahanafi** [comment]
> In 2023, we may not need the `-moz-` prefix which was there to support 2009-era Firefox. If anyone wants to tidy things up there, please do.

@sftim I looked it up and from what I can see the `-moz-` prefix was actually used by Firefox up until 2018 and that's why, although not necessary, it _may_ be good practice to keep it around.

**Comment by sftim** [comment]
_checks calendar_
 That's 5 years ago!
