### ISSUE TITLE
Document `PodTolerationRestriction`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/website#4081]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
There is no document for `PodTolerationRestriction` at https://kubernetes.io/docs/admin/admission-controllers/ , we should add it to the document.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
Already fixed.
