### ISSUE TITLE
Add tutorial about encryption methods

### ISSUE THREAD

**Issue by dmkavanagh** [kubernetes/website#40826]
Pls add more explanation about 
the encryption methods used in Security 
or links to more info.

**Comment by sftim** [comment]
/retitle Add tutorial about encryption methods
/triage needs-information

What kind of encryption? For example, this might be about setting up TLS to protect traffic between a client and a workload running in Kubernetes.

**Comment by aj11anuj** [comment]
Author didn't described the issue properly and also didn't answered follow-up questions of other contributors since 8+ month.
/close not-planned
