### ISSUE TITLE
[ko] Translate reference/networking/service-protocols in Korean

### ISSUE THREAD

**Issue by Virusuki** [kubernetes/website#40829]
This is a Feature Request

What would you like to be added

Translate reference/networking/service-protocols in Korean

Why is this needed
No translation with reference/networking/service-protocols in Korean

Comments

Page to Update:
https://kubernetes.io/docs/reference/networking/service-protocols/

**Comment by jihoon-seo** [comment]
감사합니다!
/triage accepted

**Comment by jihoon-seo** [comment]
@Virusuki 님께서 확인하고 알려 주셨는데요,
제가 #39219 에서 `content/ko/docs/concepts/services-networking/service.md` 에 있던 내용들을 바탕으로 
`content/ko/docs/reference/networking/service-protocols.md` 파일을 추가했었네요.. 😅
위의 이유로 `dev-1.26-ko.1` 에는 [`content/ko/docs/reference/networking/service-protocols.md`](https://github.com/kubernetes/website/blob/dev-1.26-ko.1/content/ko/docs/reference/networking/service-protocols.md) 파일이 이미 있습니다.
향후 `dev-1.26-ko.1` 이 `main` 에 머지되면, website에서도 확인 가능할 예정입니다.
확인 감사드리며, 이 이슈는 close 하겠습니다. 😊
/close
