### ISSUE TITLE
Container Runtimes CRI-O pull image  issue during kubeadm init

### ISSUE THREAD

**Issue by raviudemy1** [kubernetes/website#40834]
I installed CRI-O along with kubeadm and try to build the environment in RHEL 8 .. I am getting issue to pull images 
[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.27.1: output: E0425 03:13:37.830947   15673 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\"" image="registry.k8s.io/kube-apiserver:v1.27.1"
time="2023-04-25T03:13:37-07:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\""
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-controller-manager:v1.27.1: output: E0425 03:13:40.592805   15697 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\"" image="registry.k8s.io/kube-controller-manager:v1.27.1"
time="2023-04-25T03:13:40-07:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\""
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-scheduler:v1.27.1: output: E0425 03:13:43.307225   15721 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\"" image="registry.k8s.io/kube-scheduler:v1.27.1"
time="2023-04-25T03:13:43-07:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\""
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-proxy:v1.27.1: output: E0425 03:13:46.100309   15752 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\"" image="registry.k8s.io/kube-proxy:v1.27.1"
time="2023-04-25T03:13:46-07:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\""
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/pause:3.9: output: E0425 03:13:48.861588   15782 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\"" image="registry.k8s.io/pause:3.9"
time="2023-04-25T03:13:48-07:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\""
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/etcd:3.5.7-0: output: E0425 03:13:51.672994   15816 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\"" image="registry.k8s.io/etcd:3.5.7-0"
time="2023-04-25T03:13:51-07:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\""
, error: exit status 1
        [ERROR ImagePull]: failed to pull image registry.k8s.io/coredns/coredns:v1.10.1: output: E0425 03:13:54.543175   15840 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\"" image="registry.k8s.io/coredns/coredns:v1.10.1"
time="2023-04-25T03:13:54-07:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = invalid policy in \"/etc/containers/policy.json\": Unknown key \"keyPaths\""
, error: exit status 1

**Comment by tamilselvan1102** [comment]
GitHub is not the right place for support requests @raviudemy1 

If you are looking for help about using Kubernetes, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and ask your question there if a similar question has not yet been answered.

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by neolit123** [comment]
> GitHub is not the right place for support requests

yes, please also see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
