### ISSUE TITLE
Docs about NoExecute taint don't clarify that PDBs are ignored

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/website#40839]
**This is a Bug Report**

**Problem:**

This is in regards to this page: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

There, one can read `Normally, if a taint with effect NoExecute is added to a node, then any pods that do not tolerate the taint will be evicted immediately [...]`

A quick with a a pod covered by a PDB that allows zero disruption quickly shows that PDBs are not respected and that thus the eviction api is not actually used. 

**Proposed Solution:**

Reword the passage to `then any pods that do not tolerate the taint will be _deleted_ immediately` as it doesn't seem that any kind of eviction is happening.

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

I tested this using [these manifests](https://gist.github.com/alvaroaleman/a3efc88fe157267c078a1b341fd55611) and then tainting the node using `kubectl taint nodes $nodename key1:NoExecute`

/sig scheduling

**Comment by sftim** [comment]
I think the docs are accurate. SIG Scheduling can confirm.

We might want to explain specifically that taints, which represent involuntary disruptions, trigger eviction regardless of PDBs.

For example, if your network goes offline in a zone, all the Pods that don't tolerate the taint get evicted. You can't prevent the network error by specifying a PDB.

**Comment by alvaroaleman** [comment]
So what is the difference between "triggering an eviction regardless of PDB" and straight up deleting a pod? I think it would be good if we wouldn't use the term `eviction` for both of these situations.

**Comment by sftim** [comment]
Maybe we could reword https://kubernetes.io/docs/concepts/scheduling-eviction/#pod-disruption

I don't know whether the _taint based eviction_ process uses the eviction subresource or a Pod delete. However, we (Kubernetes project) definitely call that Pod removal action an eviction.

**Comment by sftim** [comment]
Possibly https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/ should clarify that a DELETE on a Pod is a non graceful eviction.

However, the DELETE at the API level doesn't mean that the Pod immediately stops running. We'll need to think about how we make that clear.

**Comment by alvaroaleman** [comment]
How about using "graceful eviction" for "Eviction subresource" and "non-graceful eviction" for "Pod object gets deleted directly"?

**Comment by sftim** [comment]
I don't actually know what control plane component (or maybe the kubelet) honors the NoExecute tainting and removes the running Pod. Would be good to clarify and document that.
