### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by lfmunoz** [kubernetes/website#40840]
Should have information about destroying, removing, cleaning a deployment.

I.e, should at least mention something about command:
```
kubectl delete deploy
```

creating, updating, listing is covered but why not deleting?

**Comment by dipesh-rawat** [comment]
/language en

We could consider enhancing the page by adding a _'Deleting a Deployment'_ section towards the end of the page, once all other operations have been covered. This would provide users with a more complete guide to creating, updating, rolling back, scaling, pausing rollout, and finally deleting deployments.

**Comment by niranjandarshann** [comment]
Ref. Link : https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
/sig docs
Enhancing the page adding  Delete section in docs will cover all the operation,  I think, we must  cover atleast  "Delete Kubernetes Deployment By Name" and "Deleting Multiple Kubernetes Deployments"  under this topic. Which will be more useful.

**Comment by sftim** [comment]
We structure our docs differently. What we should really do is make it easier to find https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/ when you are reading https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

However, that's not enough. We could add a second standalone tutorial that just covers managing deployments, all in one page.

That would be a nice improvement and would let us simplify the concept page https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by sftim** [comment]
https://github.com/kubernetes/website/issues/12082 already calls for splitting the tasks out from the concept into separate pages. We should do that.
