### ISSUE TITLE
labs.play-with-k8s.com is reverting to 1.20

### ISSUE THREAD

**Issue by magicalbob** [kubernetes/website#40854]
When I init new container with ` kubeadm init --apiserver-advertise-address $(hostname -i) --pod-network-cidr 10.5.0.0/16` I get warning `version.go:251] remote version is much newer: v1.27.1; falling back to: stable-1.20`.  coredns pods are left pending.

**Comment by neolit123** [comment]
> version.go:251] remote version is much newer: v1.27.1; falling back to: stable-1.20

it means the playground is using kubeadm binary version 1.20.x
but it's up to the playground maintainers to determine if they can stay up to date with k8s's latest releases.

in the past Katacoda was always a few versions behind latest k8s.
1.20 is quite old, and the version should be in the support skew in general >= 1.24:
https://kubernetes.io/releases/
