### ISSUE TITLE
Seccomp Default described as an alpha feature

### ISSUE THREAD

**Issue by cbandy** [kubernetes/website#40855]
**This is a Bug Report**

**Problem:**

The Security Checklist describes Seccomp Default as an alpha feature, but it is GA in Kubernetes 1.27.

This was also identified in https://github.com/kubernetes/kubernetes/pull/115719#issuecomment-1438832542.

https://github.com/kubernetes/website/blob/8e6f2eeae33015e9be3790efafc02b249c9ae557/content/en/docs/concepts/security/security-checklist.md?plain=1#L170-L172

**Proposed Solution:**

Update the language and link.

🤷🏻 I didn't find a more recent relevant blog post but I didn't look carefully.
🤷🏻 There is a mention of the feature in a tutorial: https://kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads

**Page to Update:**
https://kubernetes.io/docs/concepts/security/security-checklist/

**Comment by Coderayush13** [comment]
hey can I write blog for this
