### ISSUE TITLE
Broken link in Restrict a Container

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#40865]
**This is a Bug Report**
Broken link Restrict a Container 

**Under the Section** 
`Securing a Pod` in **Note** Upgrade path to GA

**Page link**
https://kubernetes.io/docs/tutorials/security/apparmor/

**Comment by Coderayush13** [comment]
//assign

**Comment by AmarNathChary** [comment]
I couldn't find any perfect link in [k8s.io](https://kubernetes.io/docs/home/) that can replace the broken link
I think the fix can be done by removing the sentence with hyperlink that is **Upgrade path to GA**
Any suggestion here is appreciated

**Comment by Coderayush13** [comment]
https://kubernetes.io/docs/tutorials/security/apparmor/#upgrade-path-to-general-availability
you can add above link directly

**Comment by AmarNathChary** [comment]
> https://kubernetes.io/docs/tutorials/security/apparmor/#upgrade-path-to-general-availability
   you can add above link directly

Hi @Coderayush13 The link is referring to the same page again and the link you provided was already  the same hyperlink  attached to it

**Comment by AmarNathChary** [comment]
Raised a PR in #41163

**Comment by sftim** [comment]
/close
Addressed in #41163
