### ISSUE TITLE
Add a tutorial for setting up a 3-node Kubernetes cluster on Debian with Flannel for networking, with working DNS and the web dashboard

### ISSUE THREAD

**Issue by howa** [kubernetes/website#40870]
Hi,

first of all thanks for your great work!!

However ...
Having fragmented tutorials will not help when trying to get a grip on Kubernetes.
Existing tutorials on setting up a cluster will fail after a few days as underlying Specs and processes are permanently changing.

**Suggestion**:
Make one tutorial that describes how to **SUCCESSFULLY** 
- set-up a 3 Node cluster on Debian x (where each of the Debian servers is in a minimal state, i.e. no desktop version) 
- with Flannel as the CNI plugin
- in which 2 pods can successfully communicate between each other (DNS working)
- a service from outside the cluster is reachable
- have the dashboard running and is reachable from outside with a proper port forwarding enabled once the server starts

**And keep the tutorial up-to date** so it will be working for anyone at anytime who uses it in order to learn Kubernetes.
If the the single steps in the tutorial are annotated well and references to sources are given, this tutorial will constitute a landmark resource for Kubernetes going forward serving the community as a reference.

Best
Holger

**Comment by sftim** [comment]
/retitle Add a tutorial for setting up a 3-node Kubernetes cluster on Debian with Flannel for networking, with working DNS and the web dashboard

/language en
/kind feature

**Comment by sftim** [comment]
This is quite a specific request. A page like that is hard to maintain, and there's a cardinality issue: if we document for Debian and Flannel, what about all the other combinations? CRI-O, Calico, Ubuntu? containerd, flannel, Fedora? There are many of these.

It might work better as a blog article unless we can find a hidden supply of documentation maintainers.

/priority awaiting-more-evidence

**Comment by sftim** [comment]
There's a similar challenge with https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

Setting up this kernel is only really useful if you combine it with a libc, a DNS resolver, a root filesystem, etc. However the docs for Linux itself don't cover all the detail you'd need it to, and that's left for other projects to cover.

Right now there isn't a good Kubernetes equivalent to https://www.linuxfromscratch.org/

Maybe one day there will be.

**Comment by howa** [comment]
Point(s) taken:
**Difficult to scope on specific stack**, for instance:
Debian 11
CRI-O
Flannell
As other providers being neglected.
However: Readers will gradually replace components as appropriate. Main objective will be achieved - Have a working set-up in a lab to test and play around.
**Maintaining of the tutorial**
While this point is valid it actually is the core idea of the whole exercise. Ensuring that a working set-up can be deployed at all times and is indeed working.
This could be supported by some sort of continuos integration testing by automatically spawning the 3 node cluster by running the instalment instructions provided with the tutorial. If failing, the script / tutorial needs amendment.
