### ISSUE TITLE
StatefulSetAutoDeletePVC introduction version should be 1.23

### ISSUE THREAD

**Issue by yndai** [kubernetes/website#40888]
**This is a Bug Report**

**Problem:**
On:
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/feature-gates.md?plain=1#L204

StatefulSetAutoDeletePVC is listed as being introduced in 1.22, however it was introduced in 1.23: https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/

**Proposed Solution:**

Update it to 1.23

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by Shubham82** [comment]
@ayushpatil2122  PR  for this issue is already opened by @Coderayush13. Here is PR: #40893

**Comment by vaibhav2107** [comment]
I think this issue is fixed by #41059 and hence we can close this issue
