### ISSUE TITLE
Invalid link for `object metadata` in Kubernetes API Concepts

### ISSUE THREAD

**Issue by pranav-pandey0804** [kubernetes/website#40892]
**This is a Bug Report**
The link for `object metadata` in **Continue Token, Exact** `Note` https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-get-and-list is invalid.

**Problem:**
The link for the object metadata is referring to wrong link i.e list metadata.

**Proposed Solution:**
Update with correct link https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#objectmeta-v1-meta

**Page to Update:**
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/using-api/api-concepts.md

**Comment by dipesh-rawat** [comment]
Page with issue: https://kubernetes.io/docs/reference/using-api/api-concepts/

/retitle Invalid link for `object metadata` in Kubernetes API Concepts
/language en

**Comment by pranav-pandey0804** [comment]
Dear reviewers,
@tengqm @kundan2707 @dipesh-rawat 

I hope this message finds you well. I am reaching out to discuss the situation that has developed post-merge of PR #40914 . It appears that the dynamic version shortcode applied to certain links isn't performing as expected on the Kubernetes website.

Here are the affected links:

`[list metadata](/docs/reference/generated/kubernetes-api/v{{ skew currentVersion >}}/#listmeta-v1-meta)` and 
`[object metadata](/docs/reference/generated/kubernetes-api/v{{ skew currentVersion >}}/#objectmeta-v1-meta)`.
Upon reviewing the changes, it seems there may be a discrepancy in the shortcode syntax used. Currently, it reads `{{ skew currentVersion >}}`, whereas, from my understanding, the correct syntax should be `{{< skew currentVersion >}}`.

I kindly ask for your guidance on this matter. How should we proceed to rectify these links, ensuring the Kubernetes API documentation remains accurate and accessible for all users?

**Comment by tengqm** [comment]
/triage accepted
Just go ahead and fix it?

**Comment by pranav-pandey0804** [comment]
This issue has been resolved so I am closing it
