### ISSUE TITLE
[ko] Translate reference/node/kubelet-checkpoint-api in Korean

### ISSUE THREAD

**Issue by Virusuki** [kubernetes/website#40900]
This is a Feature Request

What would you like to be added

Translate reference/node/kubelet-checkpoint-api in Korean

Why is this needed
No translation with reference/node/kubelet-checkpoint-api in Korean

Comments

Page to Update:
https://kubernetes.io/docs/reference/node/kubelet-checkpoint-api/

**Comment by jihoon-seo** [comment]
@Virusuki 감사합니다!
해당 페이지의 한국어 버전이
- https://kubernetes.io/docs/reference/node/kubelet-checkpoint-api/
- `dev-1.26-ko.1` (https://github.com/kubernetes/website/tree/dev-1.26-ko.1/content/ko/docs/reference/node)

에 없지만,
열려 있는 이슈가 있습니다. ㅎㅎ

Ref: https://github.com/kubernetes/website/issues/36770#issuecomment-1530740712

**Comment by jihoon-seo** [comment]
동일한 내용의 이전 이슈인 #36770 는 close 하고, 이 이슈를 남기겠습니다~
/triage accepted

**Comment by jihoon-seo** [comment]
This issue has been resolved by
- #41119
- #41321

Thank you!
/close
