### ISSUE TITLE
[ko] Translate reference/kubernetes-api/service-resources/service-v1 in Korean

### ISSUE THREAD

**Issue by Virusuki** [kubernetes/website#40901]
This is a Feature Request

What would you like to be added

Translate reference/networking/service-protocols in Korean

Why is this needed
No translation with reference/networking/service-protocols in Korean

Comments

Page to Update:
https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

**Comment by jihoon-seo** [comment]
@nitin-pandita please note that it is highly discouraged for non-native language (e.g., Korean) speakers to handling localizing jobs using machine translators.
Plus, please do not assign yourself if someone else (including the author of issue) already assigned themselves.
Considering these aspects, please consider to unassign yourself from this issue.

**Comment by jihoon-seo** [comment]
@Virusuki 
해당 페이지의 한국어 버전이
- https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
- `dev-1.26-ko.1` (https://github.com/kubernetes/website/tree/dev-1.26-ko.1/content/ko/docs/reference)

에 없고,
열려 있는 이슈도 없는 것 같습니다.
감사합니다!
/triage accepted

**Comment by nitin-pandita** [comment]
> @nitin-pandita please note that it is highly discouraged for non-native language (e.g., Korean) speakers to handling localizing jobs using machine translators. Plus, please do not assign yourself if someone else (including the author of issue) already assigned themselves. Considering these aspects, please consider to unassign yourself from this issue.

Sorry for mistake, unassigned my self
