### ISSUE TITLE
Repetitive word(phase) in kubeadm implementation details page 

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#40925]
**This is a Bug Report**
**Problem:**
There is a repetitive word (phase) in kubeadm implementation details page.

> Mark control-plane **phase phase** can be invoked individually with the command [kubeadm init phase mark-control-plane](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-mark-control-plane)

**Proposed Solution:**
Remove the repeated word.
**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/

**Comment by pran2711** [comment]
@T-Lakshmi  can i work on this issue

**Comment by T-Lakshmi** [comment]
Hi @pran2711,
Thanks for showing interest on it,
I have already make the changes for this issue, just waiting for triage accepted lable. Once accepted, i will push PR.

**Comment by T-Lakshmi** [comment]
Opened PR for it.
#41168

**Comment by T-Lakshmi** [comment]
Opened PR #41168 which may fix this issue.

**Comment by T-Lakshmi** [comment]
Issue fixed with merged PR #41168, hence closing this issue. Thanks,

/close
