### ISSUE TITLE
`AWS Load Balancer Controller` not listed as Ingress Controller

### ISSUE THREAD

**Issue by vayu068** [kubernetes/website#40929]
Want to check why AWS Application Load Balancer isn't listed as Ingress Controller

**Comment by tamilselvan1102** [comment]
it is mention in https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/

**Comment by dipesh-rawat** [comment]
/retitle `AWS Load Balancer Controller` not listed as Ingress Controller
/language en

**Comment by vayu068** [comment]
Sorry i missed that part. Thanks for quick update.

**Comment by dipesh-rawat** [comment]
In that case, I will close the issue. Nothing to fix in docs.

/close
