### ISSUE TITLE
Inconsistency in cluster recommendations on "Set up Konnectivity service" page

### ISSUE THREAD

**Issue by shirady** [kubernetes/website#40926]
On one side it is written:

> It is recommended to run this tutorial on a cluster with at least two nodes that are not acting as control plane hosts.

But it is also written:

> If you do not already have a cluster, you can create one by using [minikube](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/).

I think there should be reasoning for the recommendation and a comment for the users that use minikube (minikube by default use only one node).

**Comment by Shubham82** [comment]
Hi @shirady 
IMO It is correct because the link redirects to the page for setting up the Multi-Node Clusters using Minikube. (https://minikube.sigs.k8s.io/docs/tutorials/multi_node/).

**Comment by shirady** [comment]
@Shubham82 Thanks, May we change it to:

If you do not already have a cluster, you can create one by using [minikube multi node clusters](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/).

**Comment by Shubham82** [comment]
@shirady, I think the lines mentioned in the docs convey the same meaning. 

> It is recommended to run this tutorial on a cluster with at least two nodes that are not acting as control plane hosts. If you do not already have a cluster, you can create one by using [minikube](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/).

So if someone wants to perform this task, they will click on this link to see how we can create the one using Minkube.

The same line is used in other tasks also.

**Comment by Shubham82** [comment]
Page: https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/

**Comment by dipesh-rawat** [comment]
/retitle Inconsistency in cluster recommendations on "Set up Konnectivity service" page
/language en

**Comment by shirady** [comment]
@Shubham82, you can change the line in all the other tasks or close this issue.
I'm fine with both options.

**Comment by Shubham82** [comment]
Thanks @shirady 
Closing this issue, as the information mentioned in the docs is correct.
/close
