### ISSUE TITLE
Timeout calling partial

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#40930]
**This is a Bug Report**

**Problem:**
```
2:04:37 PM: ERROR 2023/05/01 13:04:37 render of "section" failed: "/opt/build/repo/layouts/docs/list.html:25:11": execute of template failed: template: docs/list.html:25:11: executing "main" at <partial "section-index.html" .>: error calling partial: partial "section-index.html" timed out after 3m0s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
```
We see errors like this whilst building the site. These are new since upgrading to Hugo 0.111

**Proposed Solution:**
Investigate whether there is a deadlock, livelock, or other issue here. It might be linked to https://github.com/kubernetes/website/issues/35780; maybe Netlify are building Hugo with a version of Go that includes the bug mentioned in that other issue.

**Additional Information:**
/priority important-longterm
/kind bug

**Comment by tengqm** [comment]
Actually I did some quite extensive experiments on this. I was suspecting that there are something wrong with the Netlify build, base on various analysis work by others. I was also suspecting that there are something imperfect when Hugo is processing index files, but I could not pinpoint the exact location due to lack of logging info from Hugo.

I did proposed something to improve this, in https://github.com/kubernetes/website/pull/38834.
But that PR is still hanging there.

**Comment by sftim** [comment]
There's `hugo --debug` which does provide some logging. Maybe not the level of detail we'd need (I suspect a debugger is a better tool here though).

**Comment by tengqm** [comment]
> There's `hugo --debug` which does provide some logging. Maybe not the level of detail we'd need (I suspect a debugger is a better tool here though).

Well, I did that ... I also turned on Netlify debug mode. Sadly, neither side was emitting useful hints on what was happening. Many of the build at that time stuck at building some `_index` pages. There are other cases as well.

**Comment by tengqm** [comment]
See my feedback on https://github.com/kubernetes/website/pull/41151

**Comment by sftim** [comment]
I think this might be fixed. It's not important that we investigate.
/remove-priority important-longterm

**Comment by sftim** [comment]
/close

I don't think this is important any more.
