### ISSUE TITLE
Error in code section of Generate ConfigMaps from files

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#40950]
**This is a Bug Report**
While applying  ./kustomization.yaml written in https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#generate-configmaps-from-files  is triggering an error `error: json: unknown field "labels"` Whereas by removing the labels from the  ./kustomization.yaml  and Applying the kustomization directory to create the ConfigMap object get created successfully. 

**Problem:**
cat <<EOF >./kustomization.yaml
> configMapGenerator:
> - name: game-config-4
>   **labels:
>     game-config: config-4**
>   files:
>   - configure-pod-container/configmap/game.properties
> EOF

**Here `game-config `is the configmap created previously.**
`error: json: unknown field "labels`

**Proposed Solution:**
Update it with suitable answer.

Refer : https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/ for kustomization update.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#generate-configmaps-from-files

**Comment by able8** [comment]
The unknown field `labels` was added in this commit https://github.com/kubernetes/website/commit/743df5fffb6d978bede021f913fcdfe8bd283956 and it was not supported refer to https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/configmapargs.go#L9

We can add labels via `generatorOptions`.    I can help open a PR to update the code sections.

```
configMapGenerator:
...
generatorOptions:
  labels:
...
```
