### ISSUE TITLE
Confusing headings in Job concept page

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/website#40959]
/sig apps

**Problem:**

We have the following structure:

- Handling Pod and container failures
  - Pod backoff failure policy
- Advanced usage
  - Pod failure policy 

The headings are closely related and have similar names that are difficult to differentiate

**Proposed Solution:**

- Handling Pod and container failures
  - Pod failure backoff limit
  - Pod failure policy

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/controllers/job/

**Comment by sftim** [comment]
/retitle Confusing headings in Job concept page

**Comment by mimowo** [comment]
/close 
Closing the issue as https://github.com/kubernetes/website/pull/40999 is merged.
