### ISSUE TITLE
Issue with k8s.io/docs/concepts/containers/images/

### ISSUE THREAD

**Issue by ht512512** [kubernetes/website#4096]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Creating a pod using a Docker Hub private repo does not work. It fails to pull the image, although a correct config.json with a valid authentication token exist in /root/.docker and manual pulling of the same docker image succeeds without any issues.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

Same behavior with "kubectl create -f foo.yaml' or from Kubernetes dashboard with foo.yaml upload.
Followed the procedure correctly, I believe, from the doc at 
https://kubernetes.io/docs/concepts/containers/images/
section "Configuring Nodes to Authenticate to a Private Repository"

**Comment by tengqm** [comment]
May need more details in addition to "does not work" for debugging. It stills smells like a configuration problem. Cannot determine if it is caused by any problem in documentation.
