### ISSUE TITLE
Document ways in which `podAffinity` influences which pod is picked for termination

### ISSUE THREAD

**Issue by LouisJULIEN** [kubernetes/website#40962]
I've been going through the documentation of [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/), looking for a way to indicate Kubernetes to delete pods on the node with the least pods. 

Let me give a example. Let's say we only have one deployment. This deployment has one replicaset of 5 pods. 3 pods on node A et 2 pods on node B. After refresh by a horizontalPodAutoscaler, replicaset value is now 4 pods. I would like one of the pods on node B (the node with least pods) to be descheduled.

`preferredDuringSchedulingIgnoredDuringExecution` is documented as used when scheduling a Pod, but no mention is made when unscheduling/terminating a pod. Does Kubernetes consider the score of podAffinity when descheduling/terminating a pod?

**Comment by sftim** [comment]
What kind of termination do you mean @LouisJULIEN?

We can document whether execution-time fit is considered for:
- [preemption](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#preemption)
- [descheduling](https://github.com/kubernetes-sigs/descheduler)
- [node-pressure eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/)

The eviction API is something you call on a particular Pod, so there are no components involved in deciding which Pod the request applies to. It's a similar story if you delete a Pod or terminate a node: there is no choice to make.

**Comment by sftim** [comment]
As GitHub is not a good home for support queries, I'll reshape this slightly

/retitle Document ways in which `podAffinity` influences which pod is picked for termination

We can also clearly document whether controllers such as StatefulSet and ReplicaSet favour poorly-scheduled Pods for termination, and whether any Kubernetes components automatically manage [Pod deletion cost](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#pod-deletion-cost).

**Comment by LouisJULIEN** [comment]
@niranjandarshann thanks, that's exactly the information I was looking for.

@sftim I'm talking about the termination that happens following a decrease of a replica count in a replicaset. Thanks for those links!
@sftim Indeed, the wording wasn't very good, thanks.

@niranjandarshann @sftim I agree it would be great to be explicit in the [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) documentation that affinity also influence when picking a pod to terminate and to which extend.

**Comment by sftim** [comment]
We could add a parallel document “How Kubernetes selects Pods to remove” and add bidirectional hyperlinks between that new page and [Assigning Pods to Nodes](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).

**Comment by LouisJULIEN** [comment]
That would be great too!

**Comment by LouisJULIEN** [comment]
This issue is not solved but looking at how old it is, I'll close the issue as stale
