### ISSUE TITLE
Update policies documentation in the concepts section

### ISSUE THREAD

**Issue by JimBugwadia** [kubernetes/website#40970]
**This is a Feature Request**

**What would you like to be added**

Update [policies](https://kubernetes.io/docs/concepts/policy/).

Better documentation on what Kubernetes policies are, the types of policies available, and when should each type be used. 

**Why is this needed**

Several users tend to confuse policies with network policies or other API objects that provide policy behaviors. With the new ValidatingAdmissionPolicy, there are questions on how that fits with other Kubernetes policy types. There is no doc to cover the types of available policies and clarify where they fit.

**Comments**

**Comment by JimBugwadia** [comment]
Draft PR: https://github.com/kubernetes/website/pull/40969

**Comment by sftim** [comment]
How about:
- write text for https://kubernetes.io/docs/concepts/policy/ (page is currently autogenerated)
- for each page within policy section, identify at the top of the page which kind of policy it is

and optionally:
- in the reference section, add a table of all policy mechanisms in Kubernetes, along with a link to the docs for that mechanism
- link to that new reference page from https://kubernetes.io/docs/concepts/policy/

**Comment by niranjandarshann** [comment]
Page for updation: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/policy/_index.md
Its a github link where we should add description about the policies, uses and as per the issue is asking for.
/sig docs
