### ISSUE TITLE
[ko]Translate docs/tasks/job/pod-failure-policy into Korean

### ISSUE THREAD

**Issue by bugoverdose** [kubernetes/website#40973]
**This is a Feature Request**

**What would you like to be added**

Translate docs/tasks/job/pod-failure-policy.md into Korean

**Why is this needed**
It's not translated yet. 
I know that a duplicate issue (#36719) exists, but it has a `lifecycle/rotten` label on it. 
And I think that it should've been closed because more than 30 days have passed since the label was applied.

**Comments**

Page to Update : https://kubernetes.io/docs/tasks/job/pod-failure-policy

**Comment by seokho-son** [comment]
@bugoverdose 님! 이슈 제안 감사합니다.
기존에 동일 #36719 이슈가 열려 있긴 한데, rotten 되어 있어서 현재 기존 기여자의 현황을 간단히  확인하고 있습니다. :)

**Comment by jihoon-seo** [comment]
현황을 확인하였고 이전 이슈가 close 되었습니다.
감사합니다!
/triage accepted
