### ISSUE TITLE
Issue with k8s.io/docs/admin/kube-apiserver/

### ISSUE THREAD

**Issue by bobbychef64** [kubernetes/website#4097]
please provide examples how to restart the api-server or some brief examples how to to or enable flags
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
It is very difficult to summarize how to restart the API server. The component could be deployed in various ways. You will need to restart the API server based on how it is deployed.
Please feel free to reopen this if there are actionable suggestions.
