### ISSUE TITLE
Umbrella issue: replace deprecated `fullversion` shortcode for all localized documents

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#41005]
**Problem:**

We've deprecated the `fullversion` param (`{{< param "fullversion" >}}`) and now English documents are using `{{< skew currentPatchVersion >}}` instead. (by #40692)

All the other documents need to change `{{< param "fullversion" >}}` into `{{< skew currentPatchVersion >}}` or `v{{< skew currentPatchVersion >}}` appropriatly.

Since several languages are involved, I'd like to share this issue to check all localizations complete the task.

**Proposed Solution:**

For each localization team, search `fullversion` and change appropriately. (See the reference, https://github.com/kubernetes/website/pull/40692/files)

Please check the following task box if the localization task is complete.

**Page to Update:**

- [x] de
- [x] es
- [x] fr
- [x] hi
- [x] id
- [x] ja
- [x] ko
- [x] pt-br
- [x] ru
- [x] vi
- [ ] zh-ch _[previously done]_

- Once all localizations have switched over, we can remove the `fullversion` parameter from the site.

**Comment by seokho-son** [comment]
/assign @seokho-son 
for the Korean contents.

**Comment by seokho-son** [comment]
- PR: [ko] Replace deprecated fullversion shortcode for Korean #41008 :)
- The task for Korean can be completed after [dev-1.26-ko.1](https://github.com/kubernetes/website/tree/dev-1.26-ko.1) is merged into the main branch.

**Comment by dipesh-rawat** [comment]
/assign
For Hindi changes

**Comment by stormqueen1990** [comment]
The Brazilian Portuguese localization has replaced all occurrences via #41027/#41028.

**Comment by A-Hilaly** [comment]
/assign
for french content

**Comment by sftim** [comment]
Really done!

Thanks folks.

/close
