### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by dhaugli** [kubernetes/website#41004]
We should have a small article on how to change out weak ciphers between Kube-Apiserver and ETCD.

**Comment by ViktorUJ** [comment]
I I think  it is good idea to  have an article on how to change out weak ciphers between Kube-Apiserver and ETCD.

**Comment by AmarNathChary** [comment]
Page : https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/
/language en
/sig docs

**Comment by AmarNathChary** [comment]
Closing this issue as it has been inactive for a long time. If you find this is important you can reopen it again.
