### ISSUE TITLE
[es] localize content/en/docs/concepts/storage/storage-classes.md to Spanish

### ISSUE THREAD

**Issue by krol3** [kubernetes/website#41016]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/concepts/storage/storage-classes.m` to Spanish

**Why is this needed**

**Comments**

**Comment by ramrodo** [comment]
PR: https://github.com/kubernetes/website/pull/41118

**Comment by krol3** [comment]
@edithturn  como estas? te puedes dar assign para este issue por favor ! Gracias

**Comment by edithturn** [comment]
@krol3  dejame saber si esta correcto lo que hice. Gracias de antemano :)
