### ISSUE TITLE
Incorrect git clone URL in "Opening a pull request" page

### ISSUE THREAD

**Issue by able8** [kubernetes/website#41010]
**This is a Bug Report**

**Problem:**
It failed when running the command `git clone git@github.com/<github_username>/website` in the doc https://kubernetes.io/docs/contribute/new-content/open-a-pr/#create-a-local-clone-and-set-the-upstream

It works after replacing the first `/` with `:` in `git clone git@github.com/<github_username>/website`
```
git clone git@github.com/kubernetes/website
fatal: repository 'git@github.com/kubernetes/website' does not exist


git clone git@github.com:kubernetes/website
Cloning into 'website'...
```

**Proposed Solution:**
Replace the first `/` with `:` in `git clone git@github.com/<github_username>/website`

**Page to Update:**
https://kubernetes.io/docs/contribute/new-content/open-a-pr/#create-a-local-clone-and-set-the-upstream

**Comment by able8** [comment]
I will open a PR to fix it.

**Comment by dipesh-rawat** [comment]
/retitle Incorrect git clone URL in "Opening a pull request" page
/language en
