### ISSUE TITLE
Unable to view `POD_NAME` environment variable using PowerShell on Windows

### ISSUE THREAD

**Issue by rdt-nick** [kubernetes/website#41043]
Get the name of the Pod and store it in the POD_NAME environment variable:

export POD_NAME="$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')"
echo "Name of the Pod: $POD_NAME"

Windows 11. using Powershell 5.1 

export isnt a command so I have tried "    $env:POD_.... " for powershell and "set:...." in cmd

when using Powershell I get error:

error: error parsing template {{range .items}}{{.metadata.name}}{{\n}}{{end}}, template: output:1: unexpected "\\" in command
export : The term 'export' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ export POD_NAME=$(kubectl get pods -o go-template --template '{{range ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

and when I use cmd with set, it proceeds with the command set:...... but when I do the echo call  it's like this:

>echo Name of the Pod: $POD_NAME
Name of the Pod: $POD_NAME

any ideas why?

**Comment by dipesh-rawat** [comment]
Page related to the issue: https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

/retitle Unable to view `POD_NAME` environment variable using PowerShell on Windows
/language en
/kind support

**Comment by dipesh-rawat** [comment]
@rdt-nick Could your try `echo %POD_NAME%` to see if it displays something useful?

**Comment by utkarsh-singh1** [comment]
Hi @rdt-nick, you can find about setting up environment variable in PoweShell here - 
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.3

**Comment by sftim** [comment]
We could clarify that https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/ is written for people using a POSIX-style shell.

**Comment by tamilselvan1102** [comment]
In Case of PowerShell

#set environment variable
$env:POD_NAME="$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')"

#print environment variable
$env:POD_NAME

**Comment by tamilselvan1102** [comment]
In case Windows cmd
# set environment variable
set POD_NAME="$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')"

# print an environment variable
set POD_NAME
or
echo %POD_NAME%

**Comment by tengqm** [comment]
/close
This issue is more about how to use PowerSell for environment variables.
It is beyond the scope of k8s documentation.

**Comment by PowerOfCreation** [comment]
@tengqm This is not only an issue with environment variables. Just executing this command using Powershell:

`kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'`

Will yield this error:

`error: error parsing template {{range .items}}{{.metadata.name}}{{\n}}{{end}}, template: output:1: unexpected "\\" in command
`

**Comment by tengqm** [comment]
This is again an issue caused by the PowerShell parsing of quotes and control sequence. I don't think is it possible to provide two flavored command line guidance everywhere. The two Shells are so different.

**Comment by dakotacookenmaster** [comment]
For PowerShell users, the simplest way to fix this is to use the following command:

`$env:POD_NAME=$(kubectl get pods -o name).replace('pod/', '')`

**Comment by rc6600** [comment]
Using windows terminal, this should work:
`for /f "delims=*" %i in ('kubectl get pods -o go-template --template "{{range .items}}{{.metadata.name}}{{\"\n\"}}{{end}}"') do set POD_NAME=%i`
`echo Name of the Pod: %POD_NAME%`
