### ISSUE TITLE
Register and document label key `policy.kubernetes.io/engine`

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41062]
**What would you like to be added**
- Add `policy.kubernetes.io/engine` to https://kubernetes.io/docs/reference/labels-annotations-taints/
- Describe how it's used
- Explain how to tell which label values are valid

**Why is this needed**
https://github.com/kubernetes-sigs/wg-policy-prototypes/tree/master/policy-report uses this (currently unregistered) label.

/sig architecture
/language en

/remove kind-feature
/kind bug
(it's a minor bug to be using an official key without registering it)

**Comments**
Also see https://github.com/kubernetes-sigs/wg-policy-prototypes/issues/118

**Comment by Ritikaa96** [comment]
Hi! i can take this issue if it's triage is accepted.

**Comment by sftim** [comment]
For any pull request, please highlight that this label key is in the process of being adopted. Reviewers would want to know that detail.

**Comment by satyampsoni** [comment]
@sftim Do I need to keep the format the same?
<pre>
policy.kubernetes.io/engine

Type: Label

Example: policy.kubernetes.io/engine

Used on: ---------------
</pre>

If this is the case please provide some resources where I can learn more about this label.

**Comment by sftim** [comment]
> If this is the case please provide some resources where I can learn more about this label.

This issue is best worked on by someone who knows, or can find, the details for this label. That might need research or talking to other Kubernetes contributors to learn more. @satyampsoni I'm afraid I don't have capacity to do the research part of the issue for you.

**Comment by liggitt** [comment]
> (it's a minor bug to be using an official key without registering it)

it's not clear to me something in a kubernetes-sigs prototype is something we should include in the well-known list of labels

**Comment by sftim** [comment]
/remove-triage accepted

I'm used to finding things labelled alpha and beta that are actually widely used. I'd missed that this one is a proposed change with no end user adoption.

**Comment by natalisucks** [comment]
@sftim Did you want to keep this issue open?

**Comment by sftim** [comment]
Let's close it.

/close
