### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/static-pod/

### ISSUE THREAD

**Issue by xiaosuiba** [kubernetes/website#4106]
**This is a...** 
- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The command line in the second step does not match the content.
```bash
[root@my-node1 ~] $ mkdir /etc/kubernetes.d/
 [root@my-node1 ~] $ cat <<EOF >/etc/kubernetes.d/static-web.yaml
```
should be
```bash
[root@my-node1 ~] $ mkdir /etc/kubelet.d/
 [root@my-node1 ~] $ cat <<EOF >/etc/kubelet.d/static-web.yaml
```

**Proposed Solution:**
create the right directory and test it.

**Page to Update:**
 k8s.io/docs/tasks/administer-cluster/static-pod/

**Comment by tengqm** [comment]
The issue has been fixed.
