### ISSUE TITLE
Update Internal Load Balancer annotation for GCP in accordance with Google Cloud Kubernetes Engine doc

### ISSUE THREAD

**Issue by apsraj01** [kubernetes/website#41067]
<img width="1077" alt="Screenshot 2023-05-10 at 1 12 29 PM" src="https://github.com/kubernetes/website/assets/69401852/a769c658-b8e3-48ae-997d-b93f3fb39009">

Please update the details as per https://cloud.google.com/kubernetes-engine/docs/concepts/service-load-balancer#load_balancer_types.

`networking.gke.io/load-balancer-type: "Internal"` (GKE 1.17 and later)
`cloud.google.com/load-balancer-type: "Internal"` (versions earlier than 1.17)

**Comment by dipesh-rawat** [comment]
Page related to the issue: https://kubernetes.io/docs/concepts/services-networking/service

/retitle Update Internal Load Balancer annotation for GCP in accordance with Google Cloud Kubernetes Engine doc
/language en
