### ISSUE TITLE
Update secret/#alternatives-to-secrets having options  should be Capitalize.

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#41073]
The options  mentioned under `Here are some of your options:`    of page  https://kubernetes.io/docs/concepts/configuration/secret/#alternatives-to-secrets are not properly Capitalize.

Proposed solution:
Every options  should be properly capitalize.

**Comment by niranjandarshann** [comment]
Page to update :  https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/configuration/secret.md#alternatives-to-secrets
/language en
/sig docs

**Comment by tengqm** [comment]
Done.
/close
