### ISSUE TITLE
Document exec probe's overhead as a caution or a note

### ISSUE THREAD

**Issue by sairameshv** [kubernetes/website#41084]
Along with describing different ways of "[Check Mechanisms](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#probe-check-methods)" for the container probes, it is also good to make a note of any consequences associated with them.
Though all the mechanisms' end goal is to ensure the desired running state of the pods, they differ in the way of their implementations.
For example, in the case of the `http/tcp/grpc` probe mechanisms, the Kubelet process directly queries the corresponding container's URL/ports where as in the case of the `exec` probe mechanism, the Kubelet makes a gRPC call to the underlying container runtime interface.
Reference: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/prober/prober.go#L136 

The resulting call flow of processes as part of the exec probe constitute to the significant amount of cpu overhead compared to the other probing mechanisms in the cases of low `initialDelaySeconds`, `periodSeconds` intervals, higher pod densities.

So, it is good to suggest the user(make a note in the document) to be aware of the exec probe's overhead in case of the higher pod densities and lower periodic probe intervals.

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle
/language en

**Comment by Coderayush13** [comment]
in this issue I need to add only a note in exec probe section  ?

**Comment by sairameshv** [comment]
> in this issue I need to add only a note in exec probe section ?

Hey @Coderayush13 , I'm awaiting the issue to be triaged, get opinion(s) from the folks. Accordingly, this can be worked upon.

**Comment by tengqm** [comment]
/triage accepted

Actually, some of the probes could be leveraged as a security hack, e.g. endless loops.

**Comment by sairameshv** [comment]
Closing the issue as the related PR has been merged.
