### ISSUE TITLE
The word generic is not having description

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#41083]
**This is Support**
The word `generic ` in the command  `kubectl create secret generic prod-db-secret --from-literal=username=produser --from-literal=password=Y4nys7f11` written while creating a secret is not having any description in the https://kubernetes.io/docs/concepts/configuration/secret/#use-case-pods-with-prod-test-credentials page. 

**Proposed Solution:**
Description must cover:
a. What is generic?
b. Why it is used?
c. Do we need to use generic , only or it may be some other as well, If so then give small description about it?
d. When to used generic?
So we should put [Types of Serets](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) before [working with Secrets](https://kubernetes.io/docs/concepts/configuration/secret/#working-with-secrets). Which will give the clear picture of the command and its use.

It is difficult for new reader  to understand the command as word generic has not any description in the entire page.

**Comment by Adi-ty** [comment]
Hey would love to contribute here. Would I need to switch types of secret section above the working with secrets part and do I need to add something about generic anywhere on the page?

**Comment by niranjandarshann** [comment]
> Hey would love to contribute here. Should I put types of secret section above the working with secrets part and do I need to add something about generic anywhere on the page?

@Adi-ty  No we dont need to add about generic on the page. We need to put types of secret with their description above the working with the secret as  Opaque is having description of generic . If it will be before the working with secret then reader will clearly get to know about the commands.

**Comment by niranjandarshann** [comment]
@Adi-ty  if you want to assign it to you then you can.

**Comment by Adi-ty** [comment]
> @Adi-ty if you want to assign it to you then you can.

Yes I would love to get assigned here

**Comment by niranjandarshann** [comment]
closing this issue marking it as resolved
/close
