### ISSUE TITLE
Lack of explanation for `reclaimPolicy` options - Retain and Delete

### ISSUE THREAD

**Issue by darkn3rd** [kubernetes/website#41089]
There's a section for ReclaimPolicy, which states that this can be `Retain` or `Delete`.  It is not clear as to what those states mean, there's NO explanation.  

I was researching how to expand disk, and one guide says that the `ReclaimPolicy` must be `Retain`, but I cannot find reference as to what this means.  My expectation was that these would be explained what they mean, rather than this is the only do option.

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/concepts/storage/storage-classes/
/retitle Lack of explanation for `reclaimPolicy` options - Retain and Delete
/language en

**Comment by tengqm** [comment]
These concepts are well explained in 'concepts/storage/persistent-volumes.md'. Maybe a pointer or two suffices?

**Comment by niranjandarshann** [comment]
@darkn3rd  Please refer https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming link here you will find the brief introduction about the retain or delete. I think this link will be helpful to understand.
