### ISSUE TITLE
Need info on `secret` volume

### ISSUE THREAD

**Issue by rishavkankane** [kubernetes/website#41093]
secret 
description here

**Comment by niranjandarshann** [comment]
@rishavkankane  Please specify what problem you encountered.
/triage needs-information

**Comment by rishavkankane** [comment]
> @rishavkankane Please specify what problem you encountered. /triage needs-information
@niranjandarshann i am looking for the description of secret volume.

**Comment by niranjandarshann** [comment]
@rishavkankane  Please refer https://kubernetes.io/docs/concepts/storage/volumes/#secret link which will help you to get the clear understanding of the Secret.
@rishavkankane  i suggest you first go through the documentation of k8s and search for the required one you need and if you face any issue then you can raise the issue.
