### ISSUE TITLE
Poor advice in “Using NodeLocal DNSCache in Kubernetes Clusters”

### ISSUE THREAD

**Issue by aojea** [kubernetes/website#41101]
The documentations for NodeLocal DNS https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/#configuration makes reference to some internal manifest that is not supposed to be used outside the project, actually is something internal to the CI.
The reference from the docs to this manifest should be replaced

https://github.com/kubernetes/kubernetes/pull/117552#issuecomment-1544585116

**Comment by sftim** [comment]
/retitle Poor advice in “Using NodeLocal DNSCache in Kubernetes Clusters”

**Comment by sftim** [comment]
/triage accepted
(avoid setting /help on issues we haven't accepted)

**Comment by sftim** [comment]
The `codenew` shortcode is useful for providing example manifests (grep the existing docs to see how we use it).

**Comment by aojea** [comment]
/close

the website explicitly says it is a sample

> epare a manifest similar to the sample
