### ISSUE TITLE
Revise KMS docs for v1.28

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41136]
**What would you like to be done**
Update https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/ to make sure the wording is good for v1.28

**Why is this needed**
Kubernetes v1.28 will be the first minor release since v1.27, which is where KMS v2 went beta. We should check that the wording still makes sense and consider a tweak if appropriate.

**Comments**
/sig auth
/sig security

**Comment by AtriChatterjee1** [comment]
Hi is anybody working on it? I would like to take this up

**Comment by Shubham82** [comment]
Hi, @AtriChatterjee1 you can work on it by assigning the issue to yourself.

**Comment by sftim** [comment]
See https://github.com/kubernetes/website/pull/42312

**Comment by Shubham82** [comment]
Thanks, @sftim
Closing this issue, as fixed by PR #42312
/close
