### ISSUE TITLE
Missing Topic in Secrets

### ISSUE THREAD

**Issue by rishavkankane** [kubernetes/website#41146]
Uses of the secrets is missing in the Secrets Documentation.
I mean to say what are the cases in which we can use secrets?

Proposed solution:
Update the documentation with the Uses  of the Secrets.

**Comment by sftim** [comment]
I agree that we already document this. Are there any places where we could link to https://kubernetes.io/docs/concepts/configuration/secret/#use-cases but (right now) we don't?

**Comment by niranjandarshann** [comment]
> I agree that we already document this. Are there any places where we could link to https://kubernetes.io/docs/concepts/configuration/secret/#use-cases but (right now) we don't?

@sftim  I don't think so as the topic is well placed at its suitable places but we need to do changes in the place of Types of secret and Working with the secrets. https://github.com/kubernetes/website/issues/41083 .

**Comment by rishavkankane** [comment]
@niranjandarshann  @sftim  I found that the issue is solved and merged in #41083 so can i close the issue?

**Comment by niranjandarshann** [comment]
@rishavkankane  if you think the issue raised by you already solved , then you can yourself close the issue. You can use **/close** label to close the issue. Its up to you. The good practice is to close the issue if you thing it is resolved to clear the  list.

**Comment by rishavkankane** [comment]
closing the issue marking as resolved.
/close
