### ISSUE TITLE
Generated API docs include hyperlinks without link text

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#41186]
Problem:
This page displaying many URLs as it is. 
Create a hyperlink instead of showing URL.

This is auto-generated page.

Page to Update:
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/

**Comment by tengqm** [comment]
What's your plan to revise them then? They are generated out of the upstream source code (more specifically, the comments). Are you gonna update the upstream source code?

**Comment by Gauravvpnd** [comment]
I would like to work on this issue can you please assign me this ?

**Comment by sftim** [comment]
/retitle Generated API docs include hyperlinks without link text

**Comment by sftim** [comment]
@Gauravvpnd, please outline the approach you'd like to take here. It'd be good to know what we'll do before we accept the issue.

**Comment by Gauravvpnd** [comment]
> @Gauravvpnd, please outline the approach you'd like to take here. It'd be good to know what we'll do before we accept the issue.

As there are many urls on the page i will embed all the urls in text and make it hyperlink.

Do you think is there other way to do?

**Comment by Gauravvpnd** [comment]
> fixes

So can you please explain how it should be done?

**Comment by shannonxtreme** [comment]
https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/ should help @Gauravvpnd

**Comment by sftim** [comment]
We didn't find a volunteer to work on improving the generator code.

/remove-lifecycle stale
/lifecycle rotten

**Comment by tamilselvan1102** [comment]
if any one guide me where exactly the automation code is there, i will try to work on it.

**Comment by sftim** [comment]
> if any one guide me where exactly the automation code is there, i will try to work on it.

That code is at https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-apidocs
@tengqm and @feloy know the most about it, I think.

**Comment by tamilselvan1102** [comment]
@sftim 
I will look at it.
Thank you
