### ISSUE TITLE
Specify resource limits in `nodelocaldns.yaml` in the context of page "Using NodeLocal DNSCache in Kubernetes Clusters"

### ISSUE THREAD

**Issue by andyndang** [kubernetes/website#41198]
Please set a resource limit in nodelocaldns.yaml. I deployed this to test in my cluster and ran out of CPU and affected other services

**Comment by dipesh-rawat** [comment]
/retitle Specify resource limits in `nodelocaldns.yaml` in the context of page "Using NodeLocal DNSCache in Kubernetes Clusters"

**Comment by sftim** [comment]
/kind feature

See https://github.com/kubernetes/website/issues/41101

**Comment by Ritikaa96** [comment]
Hm.. as per the given reference [nodelocaldns.yaml](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml)
We can add a resource limit to it and as per #41101, this example manifest can be added as code new shortcode.

Do we need to have a whole new example manifest or we can use the same but without making reference to an internal document?

**Comment by Ritikaa96** [comment]
Any update on this? I think we can make a change in this sample with comments indicating the limit as well.
would like to know the opinions of matter experts and file owners regarding this.

/sig cloud-provider
