### ISSUE TITLE
[ko] Translate 'Pod Scheduling Readiness' into Korean

### ISSUE THREAD

**Issue by Goodjinuk** [kubernetes/website#41201]
**This is a Feature Request**

**What would you like to be added**

Translate docs/concepts/scheduling-eviction/pod-scheduling-readiness.md into Korean

**Why is this needed**
No translation with docs/concepts/scheduling-eviction/pod-scheduling-readiness into Korean

**Comments**

Page to Update: 
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/

**Comment by Goodjinuk** [comment]
> /language ko /assign

**Comment by jihoon-seo** [comment]
@Goodjinuk 안녕하세요~~
K8s 문서 한국어화에 대한 관심 및 기여에 감사드립니다.

제가 찾아보니, 관련 이슈는 없는데,
#40556 에서 작업이 완료되어
https://github.com/kubernetes/website/blob/dev-1.26-ko.1/content/ko/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md 에 파일이 있습니다.
(Preview: https://deploy-preview-40556--k8s-dev-ko.netlify.app/ko/docs/concepts/scheduling-eviction/pod-scheduling-readiness/)
(지금은 `dev-1.26-ko.1` 브랜치에 있고, 이 브랜치가 `main`에 머지되면 K8s 문서 웹사이트에서도 보일 예정입니다.)

아쉽지만, 다른 작업을 살펴봐 주시면 감사하겠습니다.. ㅎㅎㅎ

/retitle [ko] Translate 'Pod Scheduling Readiness' into Korean
/triage duplicate

**Comment by seokho-son** [comment]
@Goodjinuk 안녕하세요 ^^

중복된 작업을 방지하기 위해서는 language/ko 레이블로 이슈 및 PR을 검색해서 [is:issue is:open label:language/ko](https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Alanguage%2Fko) 
유사 주제가 있는지 제목을 통해 미리 확인해보시면 좋습니다. 
웹사이트상에 없는 한글 문서가, 현재 작업 중이거나 아직 오픈이 되지 않은 경우가 있기 때문입니다. ;)

(참고)
- 웹사이트상에 없는 한글 문서: main 브랜치에 반영되지 않은 상태
- 현재 작업 중: 이슈만 오픈되어 있거나, PR이 오픈되어 리뷰 중인 상태
- 아직 오픈이 되지 않은 경우: 한글 작업 브랜치가 main 브랜치에 머지되지 않아서, 아직 웹사이트에 뜨지 않은 상태

한번 살펴보시고, 좋은 주제로 또 이슈 올려주시길 기대하겠습니다! :)

해당 이슈는 확인하셨다는 가정하에, close 하겠습니다. 
/close
