### ISSUE TITLE
Improve clarity on synchronous and asynchronous nature of Container hooks handlers

### ISSUE THREAD

**Issue by pulkits15** [kubernetes/website#41219]
This paragraph is a bit confusing - 

> Hook handler calls are synchronous within the context of the Pod containing the Container. This means that for a PostStart hook, the Container ENTRYPOINT and hook fire asynchronously. However, if the hook takes too long to run or hangs, the Container cannot reach a running state.

In first line, call is said to be `synchronous`. In second line  `asynchronously`

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Improve clarity on synchronous and asynchronous nature of Container hooks handlers

**Comment by niranjandarshann** [comment]
You can find the information and the entire paragraph on the Page:  https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution. 
/sig docs
/kind support

**Comment by sftim** [comment]
BTW we'd welcome a rewording that has the same meaning but that is easier for people to understand.

The existing text is correct but clearly at least one contributor did not understand it first go.

**Comment by sftim** [comment]
/remove-kind support

I think there's something we can fix here.

**Comment by divya-mohan0209** [comment]
For contributors picking up this issue, please note the following:
- We'd like to improve the existing text per [this comment](https://github.com/kubernetes/website/issues/41219#issuecomment-1557124784) by Tim. You may propose a PR with your suggested changes and do not need to ask us for permission.
- The page to be amended is: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution

/help

**Comment by vaibhav2107** [comment]
I think the issue is resolved by PR #46371 and can be closed

**Comment by vaibhav2107** [comment]
/close 
Please feel free to re-open in case anything is left.
