### ISSUE TITLE
"Installing kubeadm" page lacks prerequisites details

### ISSUE THREAD

**Issue by johnson-earls** [kubernetes/website#41221]
The installation instructions for kubeadm do not include any information about its prerequisites, such as "socat" and "conntrack".  Please list all such prerequisites in your documentation.

**Comment by neolit123** [comment]
> The installation instructions for kubeadm do not include any information about its prerequisites, such as "socat" and "conntrack". Please list all such prerequisites in your documentation.

techically, these are kubelet package dependencies.
they will be installed for you if you use a package manager. if not, kubeadm will warn about missing dependencies.

the list is varying and only known from kubelet source code.
if kubelet maintainers are willing to document them, we can crosslink from kubeadm pages. but i am -1 to maintain them on kubeadm pages directly.

/sig cluster-lifecycle node

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
/language en

**Comment by dipesh-rawat** [comment]
/retitle "Installing kubeadm" page lacks prerequisites details

**Comment by sftim** [comment]
/kind feature

> if kubelet maintainers are willing to document them, we can crosslink from kubeadm pages. but i am -1 to maintain them on kubeadm pages directly.

We could set up a shortcode to allow the kubeadm docs to transclude this information and still only maintain it in one (docs) place. The next thing we'd need is a volunteer to have capacity for doing that.

**Comment by sftim** [comment]
I agree about the overhead of maintenance and the value of keeping things lightweight; maintaining the existing docs is enough of a challenge.

We can accept this issue if we do get a clear offer of work to make an [integrated approach](https://github.com/kubernetes/website/issues/41221#issuecomment-1554329825) possible.

**Comment by neolit123** [comment]
the list can be fetched programmatically from here

https://github.com/kubernetes/release/blob/master/packages/rpm/kubelet.spec

or another k/release location. preferably using the latest released tag.

**Comment by sftim** [comment]
We didn't find a volunteer to set up the shortcode.

/close not-planned
