### ISSUE TITLE
Unable to download Google Cloud public signing key following "Installing kubeadm" guide

### ISSUE THREAD

**Issue by edgar-esteban-ramirez** [kubernetes/website#41234]
Step 2
sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

This command is not working
This is the output: curl: (23) Failure writing output to destination

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Unable to download Google Cloud public signing key following "Installing kubeadm" guide

**Comment by dipesh-rawat** [comment]
@edgar-esteban-ramirez Looking at the error, it seems likely that the directory `/etc/apt/keyrings` doesn't exist, although this is just a speculation. To get more verbose diagnostics, you can utilize the `-v` option when using `curl`.

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close support
