### ISSUE TITLE
Wrong (?) download URL for package signing key

### ISSUE THREAD

**Issue by xogoodnow** [kubernetes/website#41246]
Hi
when adding the GPG key of k8s registry to the system,
the following error is received.
The problem has been reproduced on multiple CDs on multiple zones.

```
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

the problem is resolved with the following procedure:
Step 1: removing the signed-by attribute form the repo
`echo "deb  https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list`

Step 2:  manually trusting the key
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05`
 OUTPUT:
```
 Executing: /tmp/apt-key-gpghome.nRNiyYJch7/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys B53DC80D13EDEF05
gpg: key B53DC80D13EDEF05: 1 duplicate signature removed
gpg: key B53DC80D13EDEF05: public key "Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

there are two issues here:
First: the documentation is wrong and needs to be updated (if this is the way that is going to be from now on)
Second: this method is not safe and is going to be deprecated.

I would very much appreciate it if you could tell me how to fix this.

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by neolit123** [comment]
/reopen

try asking for feedback in #sig-release in k8s slack.
or log an issue in kubernetes/release

**Comment by xogoodnow** [comment]
Hi
I do not need support. The thing is that the documentation of k8s for installing Kubeadm is not functional.
To reproduce my issue, please try installing Kubeadm via the following link.
Just simply copy and paste each command and see if it works (It does not!).
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by seantywork** [comment]
it might be related to which version of kubernetes toolkit you're installing?
I ran into this issue while trying to have 1.25.3 on my machines.

https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585

according to the url above, changing the packages.google.com to dl.k8s.io sure did fix my issue

**Comment by neolit123** [comment]
/retitle change packages.google.com to dl.k8s.io in kubeadm docs
/help

**Comment by Kumm-Kai** [comment]
The issues occurs because https://packages.cloud.google.com/apt/doc/apt-key.gpg is returning the GPG key as ASCII armored instead of binary. If you `gpg --dearmor` the key grom packages.cloud.google.com `apt` is working again.

**Comment by dims** [comment]
Folks, please see https://github.com/kubernetes/release/issues/2862

/close

**Comment by SteveSims2** [comment]
> Folks, please see [kubernetes/release#2862](https://github.com/kubernetes/release/issues/2862)
> 
> /close

That link references a completely different issue.   Not this issue.

**Comment by sftim** [comment]
Let's open this once https://github.com/kubernetes/release/issues/2862 shows a clear way forward and a recommendation.

**Comment by neolit123** [comment]
people have opened multiple issues in k/website and k/kubeadm today.
a PR was sent as well:
https://github.com/kubernetes/website/pull/41263

an immediate solution is required...
if https://github.com/kubernetes/website/pull/41263 is a valid fix, please +1 / approve it.

**Comment by 9monsters** [comment]
```shell
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg
```

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/pull/41307

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/pull/41309

**Comment by sftim** [comment]
I think this is fixed.

/close

We can reopen it if symptoms persist.
