### ISSUE TITLE
Broken Status Links in README files

### ISSUE THREAD

**Issue by Vishal-Kamath** [kubernetes/website#41241]
**This is a Bug Report**

**Problem:** Broken build status links in README files

**Proposed Solution:**
If I'm not wrong, the ones using travis-ci api
```
[![Build Status](https://api.travis-ci.org/kubernetes/website.svg?branch=master)](https://travis-ci.org/kubernetes/website)
```
need to be replaced with netlify links
```
[![Netlify Status](https://api.netlify.com/api/v1/badges/be93b718-a6df-402a-b4a4-855ba186c97d/deploy-status)](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys)
```

**Page to Update:**
the issues were encounter in the following pages
https://github.com/kubernetes/website/blob/main/README-de.md
https://github.com/kubernetes/website/blob/main/README-es.md
https://github.com/kubernetes/website/blob/main/README-fr.md
https://github.com/kubernetes/website/blob/main/README-hi.md
https://github.com/kubernetes/website/blob/main/README-id.md
https://github.com/kubernetes/website/blob/main/README-it.md
https://github.com/kubernetes/website/blob/main/README-vi.md

**Comment by Vishal-Kamath** [comment]
I'm new to open source, if you don't mind I would be happy to contribute.

**Comment by arnab2001** [comment]
I would like to contribute on this issue

**Comment by niranjandarshann** [comment]
@Vishal-Kamath  if you are working on the issue then you should assign it to yourself as here i see you had raised PR to resolve the issue. So assigning this issue to you.
/assign @Vishal-Kamath

**Comment by Vishal-Kamath** [comment]
Hello @niranjandarshann,
Vishal here. this was my first attempt at open source contributions so I'm not familiar with the do's and don'ts of It. I am keen on my way to know how the open source environment functions. If you don't mind can you go through the proper etiquettes to follow in an open source contributions as comfortably as you can.

**Comment by niranjandarshann** [comment]
> 

@Vishal-Kamath  I have come to know the whole process, assigning the issue means that if you have assigned then no one else can assign without you so comfortably you can contribute.

**Comment by utkarsh-singh1** [comment]
Hi @Vishal-Kamath, if you are new to open source contribution in Kubernetes, please go through these guides-

- https://github.com/kubernetes/website#contributing-to-the-docs
- https://www.kubernetes.dev/docs/guide/
- https://www.kubernetes.dev/docs/guide/first-contribution/ 

They will be helpful for yourself in early stages.

**Comment by niranjandarshann** [comment]
The issue is labelled lifecycle stale  So Closing this issue. 
/close
