### ISSUE TITLE
Change "应用程式" to "应用程序" on the concepts overview page

### ISSUE THREAD

**Issue by Joy-Walker** [kubernetes/website#41250]
<img width="789" alt="image" src="https://github.com/kubernetes/website/assets/74366291/87877049-7ccb-417d-91a8-3972be8dab08">

是“应用程序”吧

**Comment by mengjiao-liu** [comment]
/retitle Change "应用程式" to "应用程序" on the concepts overview page

**Comment by mengjiao-liu** [comment]
PR #41710 has been merged, so this issue can be closed.
/close
