### ISSUE TITLE
Translate tasks/job/job-with-pod-to-pod-communication in Korean

### ISSUE THREAD

**Issue by cooltiger5939** [kubernetes/website#41257]
**This is a Feature Request**

**What would you like to be added**

Translate tasks/job/job-with-pod-to-pod-communication in Korean

**Why is this needed**
No translation with tasks/job/job-with-pod-to-pod-communication in Korean

**Comments**

Page to Update: 
https://kubernetes.io/docs/tasks/job/job-with-pod-to-pod-communication/

**Comment by seokho-son** [comment]
triage/duplicate

**Comment by seokho-son** [comment]
@cooltiger5939 안녕하세요. 혹시 해당 이슈 작업 중에 계신가요?
확인해보니, 관련 사항은 https://github.com/kubernetes/website/issues/40946 를 통해 먼저 작업이 선점되었고, https://github.com/kubernetes/website/pull/40972 에 의해서 개발 브랜치에 머지되어 있습니다. (참고: 현재 개발 브랜치 https://github.com/kubernetes/website/tree/dev-1.26-ko.1)
그래서 해당 개발 브랜치가 main에 머지되면, 웹사이트에 반영될 예정입니다.

**Comment by cooltiger5939** [comment]
@seokho-son 안녕하세요! 네 확인했습니다. 감사합니다

**Comment by seokho-son** [comment]
@cooltiger5939 양해해주셔서 감사합니다.. ^^

중복된 작업을 방지하기 위해서는 language/ko 레이블로 이슈 또는 PR을 검색해서 [is:issue is:open label:language/ko](https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Alanguage%2Fko) 
유사 주제가 있는지 미리 확인해보시면 좋습니다. 
웹사이트상에 없는 한글 문서가, 현재 작업 중이거나 아직 오픈이 되지 않은 경우가 있기 때문입니다. ;)

(참고)
- 웹사이트상에 없는 한글 문서: main 브랜치에 반영되지 않은 상태
- 현재 작업 중: 이슈만 오픈되어 있거나, PR이 오픈되어 리뷰 중인 상태
- 아직 오픈이 되지 않은 경우: 한글 작업 브랜치가 main 브랜치에 머지되지 않아서, 아직 웹사이트에 뜨지 않은 상태

한번 살펴보시고, 좋은 주제로 또 이슈 올려주시길 기대하겠습니다! :)
