### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/ubuntu/

### ISSUE THREAD

**Issue by drpaneas** [kubernetes/website#4126]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I've just installed a fresh system with Ubuntu 17.10. I followed the instruction in the documentation page, saying that I have to do:

```bash
sudo snap install conjure-up --classic
# re-login may be required at that point if you just installed snap utility
conjure-up kubernetes
```

Then I tried to start *kubernetes* but I received the following Python traceback:

```bash
drpaneas@ubuntu1710:~$ conjure-up kubernetes
Traceback (most recent call last):
  File "/snap/conjure-up/441/bin/conjure-up", line 11, in <module>
    load_entry_point('conjure-up==2.2.0', 'console_scripts', 'conjure-up')()
  File "/snap/conjure-up/441/lib/python3.6/site-packages/conjureup/app.py", line 238, in main
    utils.lxd_version(),
  File "/snap/conjure-up/441/lib/python3.6/site-packages/conjureup/utils.py", line 199, in lxd_version
    raise Exception("Could not determine LXD version.")
Exception: Could not determine LXD version.
```

The problem is that `conjure-up kubernetes` needs to talk to `lxd` but this is not installed in my system:

```bash
$ dpkg-query -l lxd
dpkg-query: no packages found matching lxd
```

**Proposed Solution:**

To have `lxd` as a dependency of during the installation of ` snap install conjure-up --classic`. Also, it should be able to start/stop the `lxd` by itself, add the user to the `lxd group`, set the correct permissions to read the `unix.socket`, etc ...

**Page to Update:**
http://kubernetes.io/...

Please update the page with **working** instructions. Having *kubernetes* in the front-page of ubuntu.com many people are going to end-up with that broken behavior.

**Comment by ildella** [comment]
This happens also on Ubuntu 17.04. 
I've installed lxd snap, @drpaneas  any tip on how to start it as a workaround for this bug?  
Thanks.
