### ISSUE TITLE
Avoid unhelpful terms such as “slave” in example Deployment manifests

### ISSUE THREAD

**Issue by AzureStackNerd** [kubernetes/website#41284]
use of modern alternatives of Master and Slave in the examples

`labels:
   app: guestbook
   tier: backend
   role: master`
 
vs

`labels:
   app: guestbook
   tier: backend
   role: primary`

and

`labels:
   app: guestbook
   tier: backend
   role: slave`
 
vs

`labels:
   app: guestbook
   tier: backend
   role: secondary`

**Comment by vaibhav2107** [comment]
After the PR #42818 the section "Using labels effectively" that contains the word 'slave' is now moved to the[ concepts](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#using-labels-effectively) page.
Also the PR changes the word 'slave' to 'replica'.

**Comment by vaibhav2107** [comment]
If this is fine then we can close this issue
