### ISSUE TITLE
Add glossary tooltip for kubelet in Resource Management page

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#41298]
**This is a Feature Request**
Add glossary tooltip for  **kubelet** .

Page to be updated: [Resource Management](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)

**Why is this needed**
Other than **kubelet**  glossary tooltip has been added for all terms in this page.

**Comment by sftim** [comment]
/retitle Add glossary tooltip for kubelet in Resource Management page

**Comment by vaibhav2107** [comment]
I think this is fixed by #41326 and can be closed now
