### ISSUE TITLE
Document deletion of `kubectl` on Windows and multiple Linux distros

### ISSUE THREAD

**Issue by SpringWiz11** [kubernetes/website#41306]
**This is a Feature Request**

This is a detailed process of deletion of kubectl on windows, Debian, Ubuntu, Fedora, Arch linux distributions.

**What would you like to be added**

This documentation consists of a descriptive guide to uninstall kubectl. It contains all the details and CLI commands to uninstall kubectl from the root of your system.  

**Why is this needed**

Most of the times, installation of kubectl can be done easily with 
- apt-get, snap, OKD, pacman and RPM using Yum on fedora, Arch, debian and debian based linux distro including ubuntu.
- choco and scoop on Microsoft Windows. 
But uninstalling that was one of the problems faced by most of the clients. This rich featured documentation will help everyone ranging from a n absolute begineer to an expert understand the uninstallation procedure of kubectl. 

**Comments**

This documentation is targeted towards Microsoft Windows, Debian and deb based linux distributions including ubuntu, fedora and Arch.

**Comment by infinite-binaryloop** [comment]
.take

**Comment by infinite-binaryloop** [comment]
triage/accepted

**Comment by infinite-binaryloop** [comment]
I will take this up!

**Comment by sftim** [comment]
Previous title mentioned: _It is an extention of #41149: - Removal of kubectl on Macos_
/retitle Document deletion of `kubectl` on Windows and multiple Linux distros

**Comment by infinite-binaryloop** [comment]
Hey, @sftim!
Good day!
Can I know if there is a slack channel ? I would like to get in touch with the maintainers to get some insights about the requirements and also share my approaches with the team.

**Comment by infinite-binaryloop** [comment]
Hey @dipesh-rawat

Good day!

Yes. I went through the issue. I will be looking into that as well as uninstalling kubectl using windows package managers like choco and scoop.

Thank you!
