### ISSUE TITLE
Improvement for k8s.io/~jayme/k8s-docs/v1.16/docs/concepts/workloads/pods/podpreset/

### ISSUE THREAD

**Issue by ole1986** [kubernetes/website#41323]
No information about microk8s. Related links are dead.

**Comment by AmarNathChary** [comment]
hi @ole1986 can you please provide the page link where you encountered the issue

**Comment by niranjandarshann** [comment]
@ole1986  Here you can find the information about microk8s.
Please Ref Link:  https://kubernetes.io/blog/2019/11/26/running-kubernetes-locally-on-linux-with-microk8s/
You will definately find some descriptive information about it.

**Comment by sftim** [comment]
https://k8s.io/~jayme/k8s-docs/v1.16/docs/concepts/workloads/pods/podpreset/ is not a livepage on the world wide web.

/triage needs-information
