### ISSUE TITLE
Pod Stuck in "ContainerCreating" state when using Projected Volumes example

### ISSUE THREAD

**Issue by rishavkankane** [kubernetes/website#41335]
In Projected Volume Example https://kubernetes.io/docs/concepts/storage/projected-volumes/#example-configuration-secret-downwardapi-configmap when i simply copy and paste the code of yaml file  in master node and creating a pods it get created in node 2 where i had already  created the directory for **secret and volumemount, configpath, downwardApi** (`here in example  /projected-volume, my-group/my-username, labels, cpu_limit, my-group/my-config`) in /projected-volume folder  i created my-group, cpu_limit, labels and in my_group i created my-config and my username directory. Then also i am facing an issue called Containercreating state of the Pods.
Can anyone help me why this is happening. Your Suggestions are invited. What i am missing to get my pod in ready state.

**Comment by dipesh-rawat** [comment]
/retitle Pod Stuck in "ContainerCreating" state when using Projected Volumes example

**_YAML related to the issue_**: https://kubernetes.io/docs/concepts/storage/projected-volumes/#example-configuration-secret-downwardapi-configmap

**Comment by niranjandarshann** [comment]
@rishavkankane  I think you missed making secrets, Configmap, downwardAPI thats why the pod is not getting in ready state.

**Comment by rishavkankane** [comment]
@niranjandarshann yes i hadnt created Secret, Configmap DownwardAPI .

**Comment by rishavkankane** [comment]
I am bit confused about yaml file having 
items:
    key:
    path:
what these meant and what is there importance? what is the use of Key and what the path is reffering.

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/storage/projected-volumes/#example-configuration-secret-downwardapi-configmap is a manifest; however, that page (intentionally) does not give complete instructions on how to make that example work.

I don't think there's any documentation fix needed.

**Comment by sftim** [comment]
You could add a new **[tutorial](https://kubernetes.io/docs/tutorials/#configuration)** page @rishavkankane, perhaps titled “Explore the downward API”.

The concept page doesn't need any fix.

**Comment by sftim** [comment]
If you want to edit https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/storage/projected-secret-downwardapi-configmap.yaml to have inline comments, that works too.

**Comment by niranjandarshann** [comment]
> @sftim Yes it is true the page does not have complete instruction on the working of the example. So the document fix is needed to showcase the step by step action. More description about the projected volume work will be helpful for reader to compile easily. @niranjandarshann @dipesh-rawat What do you thing about my suggestion.

@rishavkankane  Yes projected volume has lee description but we dont need any fix in concept as the concept of projected volume is clear in it but still if you want to add something that will be useful then you can go for it.

**Comment by niranjandarshann** [comment]
@rishavkankane  I am helping you to understand the yaml file step by step:
1.  under  volumeMounts section for each container that needs the secret.
2.  Specify a path to an unused directory where the secret will appear. ( here in yaml file **/projected-volume**)
3.  Add a volumes block to list each projected volume source.(volume label)
4. Specify any name for the volume. (under volume label there is name labels so name of the volume)
 5.  Add a secret. Enter the name of the secret object. Each secret you want to use must be listed. (Here  you have to declare secret that you made and already exist here)
 6.  The secret having items or data in it so key here denotes the username which can be anything that you declared in the secret yaml.
 7.  Specify the path to the secrets file under the mountPath. Here, the secrets file is in /projected-volume/my-group/my-username.
  8.  Add a Downward API source.
  9.  Add a ConfigMap source.
  10. Set the mode for the specific projection

**Comment by niranjandarshann** [comment]
I thing the above steps description helped you in understanding the yaml file and the working of it.
 In your case you hadn't made any volume (like as Secret, downwardapi, Configmap) thats why pod is getting in ContainerCreating state as it is not getting the  path of the volume you created in  it.

**Comment by rishavkankane** [comment]
> @rishavkankane I am helping you to understand the yaml file step by step:
> 
> 1. under  volumeMounts section for each container that needs the secret.
> 2. Specify a path to an unused directory where the secret will appear. ( here in yaml file **/projected-volume**)
> 3. Add a volumes block to list each projected volume source.(volume label)
> 4. Specify any name for the volume. (under volume label there is name labels so name of the volume)
>     5.  Add a secret. Enter the name of the secret object. Each secret you want to use must be listed. (Here  you have to declare secret that you made and already exist here)
>     6.  The secret having items or data in it so key here denotes the username which can be anything that you declared in the secret yaml.
>     7.  Specify the path to the secrets file under the mountPath. Here, the secrets file is in /projected-volume/my-group/my-username.
>      8.  Add a Downward API source.
>      9.  Add a ConfigMap source.
>      10. Set the mode for the specific projection

Here point 6 denotes that username which can be the name of the field in the my-username file. So here the secret is getting used from the file.
Here point 7 means the file name from which we are using the secret field.
@niranjandarshann please correct me if i am wrong or am i getting it correct now?

**Comment by rishavkankane** [comment]
Same we will follow for configmap and downwardapi?

**Comment by rishavkankane** [comment]
I think these types of explaination should be  needed in documentation so that new reader directly on to the page can clearly understand it.
What is you point of view @sftim @dipesh-rawat @niranjandarshann

**Comment by niranjandarshann** [comment]
> > @rishavkankane I am helping you to understand the yaml file step by step:
> > 
> > 1. under  volumeMounts section for each container that needs the secret.
> > 2. Specify a path to an unused directory where the secret will appear. ( here in yaml file **/projected-volume**)
> > 3. Add a volumes block to list each projected volume source.(volume label)
> > 4. Specify any name for the volume. (under volume label there is name labels so name of the volume)
> >     5.  Add a secret. Enter the name of the secret object. Each secret you want to use must be listed. (Here  you have to declare secret that you made and already exist here)
> >     6.  The secret having items or data in it so key here denotes the username which can be anything that you declared in the secret yaml.
> >     7.  Specify the path to the secrets file under the mountPath. Here, the secrets file is in /projected-volume/my-group/my-username.
> >      8.  Add a Downward API source.
> >      9.  Add a ConfigMap source.
> >      10. Set the mode for the specific projection
> 
> Here point 6 denotes that username which can be the name of the field in the my-username file. So here the secret is getting used from the file. Here point 7 means the file name from which we are using the secret field. @niranjandarshann please correct me if i am wrong or am i getting it correct now?

@rishavkankane  yes point 6 and 7 denotes the same as you stated. in summary  we can say the file my-username in  /projected-volume/my-group/my-username having  username stored in it. I think these points helped you.

**Comment by niranjandarshann** [comment]
> @niranjandarshann Same we will follow for configmap and downwardapi?

Yes same procedure  for Configmap but there yaml and path  must be different from secret .As both (ConfigMap and Secret)  are different

**Comment by rishavkankane** [comment]
> > > @rishavkankane I am helping you to understand the yaml file step by step:
> > > 
> > > 1. under  volumeMounts section for each container that needs the secret.
> > > 2. Specify a path to an unused directory where the secret will appear. ( here in yaml file **/projected-volume**)
> > > 3. Add a volumes block to list each projected volume source.(volume label)
> > > 4. Specify any name for the volume. (under volume label there is name labels so name of the volume)
> > >    5.  Add a secret. Enter the name of the secret object. Each secret you want to use must be listed. (Here  you have to declare secret that you made and already exist here)
> > >    6.  The secret having items or data in it so key here denotes the username which can be anything that you declared in the secret yaml.
> > >    7.  Specify the path to the secrets file under the mountPath. Here, the secrets file is in /projected-volume/my-group/my-username.
> > >    8.  Add a Downward API source.
> > >    9.  Add a ConfigMap source.
> > >    10. Set the mode for the specific projection
> > 
> > 
> > Here point 6 denotes that username which can be the name of the field in the my-username file. So here the secret is getting used from the file. Here point 7 means the file name from which we are using the secret field. @niranjandarshann please correct me if i am wrong or am i getting it correct now?
> 
> @rishavkankane yes point 6 and 7 denotes the same as you stated. in summary we can say the file my-username in /projected-volume/my-group/my-username having username stored in it. I think these points helped you.

Clearly understood @niranjandarshann this is the explanation that i was looking for. Keep guiding. Understood.

**Comment by niranjandarshann** [comment]
I think issue is resolved so we can close this issue.

**Comment by rishavkankane** [comment]
> I think issue is resolved so we can close this issue.

@niranjandarshann  Sure, I will close the issue when i will complete the task as stated in above explanation About to make the separate file and merging in one.

**Comment by rishavkankane** [comment]
Above approach work for me Thanks @niranjandarshann  and all for your support and time.
If all think its required to change the doc explanation in projected volume then definately it will be helpful for new reader if all these points must take some space in doc.

**Comment by rishavkankane** [comment]
issue resolved but updation in document is needed.
Closing the issue
/close
