### ISSUE TITLE
Unable to Install kubectl due to GPG Key Issue

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#41334]
# kubectl install instructions for Ubuntu are broken

https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management

It is easy to reproduce:

```
docker run -it ubuntu:22.04 bash

apt update

sudo apt-get install -y ca-certificates curl

sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]
Err:5 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
Reading package lists... Done
W: GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://apt.kubernetes.io kubernetes-xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by guettli** [comment]
This seems to work:

```
docker run -it ubuntu:22.04 bash

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.

apt update
```

**Comment by niranjandarshann** [comment]
@guettli   This issue is referring the same problem as in https://github.com/kubernetes/release/issues/2862.  I think this will be helpful.

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
/kind bug

**Comment by dipesh-rawat** [comment]
/retitle Unable to Install kubectl due to GPG Key Issue

**Comment by dipesh-rawat** [comment]
We have made recent revisions to the documentation regarding the Google signing key for the `Kubeadm` installation page, as reflected in the pull request found at https://github.com/kubernetes/website/pull/41307. In order to resolve this issue, it will be necessary to make corresponding updates to the Kubectl installation instructions.

**Comment by sftim** [comment]
Please change:

```diff
 
 2. Download the Google Cloud public signing key: 

    ```shell
-   sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
+   curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg

    ```
```

/help

**Comment by sftim** [comment]
@guettli, would you be willing to edit the initial description for this issue, to make it easy to find:

- Code changes: link to https://github.com/kubernetes/website/issues/41334#issuecomment-1564324297)

**Comment by guettli** [comment]
@sftim I created a PR to update the docs.

**Comment by sftim** [comment]
I'd prefer a PR where the commit messages **don't** mention this issue. It's OK to mention the issue in the GitHub description of the change, but please don't mention the issue in commit messages.

If anyone would like to open a PR, similar to https://github.com/kubernetes/website/pull/41339, that doesn't mention this issue in the commit message, then we can accept and merge that PR. Also @guettli you are welcome you amend #41339 to make it acceptable.

**Comment by dipesh-rawat** [comment]
I have raised PR https://github.com/kubernetes/website/pull/41366 to assist in resolving this issue.

**Comment by VincentRavera** [comment]
If you followed the guideline and you still get a `NO_PUBKEY` error.
You can do:
`sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg`
then retry updating.
