### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1/

### ISSUE THREAD

**Issue by Perryc1985** [kubernetes/website#41333]
Add an yaml example would be good for greenhand

**Comment by mengjiao-liu** [comment]
Please note that the Chinese page is synchronized with the content of the English page, which is automatically generated.

> The file is auto-generated from the Go source code of the component using a generic
[generator](https://github.com/kubernetes-sigs/reference-docs/). To learn how
to generate the reference documentation, please read
[Contributing to the reference documentation](/docs/contribute/generate-ref-docs/).
To update the reference content, please follow the 
[Contributing upstream](/docs/contribute/generate-ref-docs/contribute-upstream/)
guide. You can file document formatting bugs against the
[reference-docs](https://github.com/kubernetes-sigs/reference-docs/) project.

**Comment by AmarNathChary** [comment]
closing this issue as it has been inactive for a long time. If you find this is important you can reopen it again.
/close
