### ISSUE TITLE
Improper count of Ingress/Egress NetworkPolicy selectors on the `Network Policies` page

### ISSUE THREAD

**Issue by choshitautetsu** [kubernetes/website#41354]
https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors

> There are four kinds of selectors that can be specified in an ingress from section or egress to section.

But only three are listed：

- podSelector
- namespaceSelector
- ipBlock

And Kubernetes explain is also these three.
```
kiosk@k8s-master:~$ k explain networkpolicy.spec.ingress.from
KIND:     NetworkPolicy
VERSION:  networking.k8s.io/v1

RESOURCE: from <[]Object>

DESCRIPTION:
     List of sources which should be able to access the pods selected for this
     rule. Items in this list are combined using a logical OR operation. If this
     field is empty or missing, this rule matches all sources (traffic not
     restricted by source). If this field is present and contains at least one
     item, this rule allows traffic only if the traffic matches at least one
     item in the from list.

     NetworkPolicyPeer describes a peer to allow traffic to/from. Only certain
     combinations of fields are allowed

FIELDS:
   ipBlock      <Object>
     IPBlock defines policy on a particular IPBlock. If this field is set then
     neither of the other fields can be.

   namespaceSelector    <Object>
     Selects Namespaces using cluster-scoped labels. This field follows standard
     label selector semantics; if present but empty, it selects all namespaces.

     If PodSelector is also set, then the NetworkPolicyPeer as a whole selects
     the Pods matching PodSelector in the Namespaces selected by
     NamespaceSelector. Otherwise it selects all Pods in the Namespaces selected
     by NamespaceSelector.

   podSelector  <Object>
     This is a label selector which selects Pods. This field follows standard
     label selector semantics; if present but empty, it selects all pods.

     If NamespaceSelector is also set, then the NetworkPolicyPeer as a whole
     selects the Pods matching PodSelector in the Namespaces selected by
     NamespaceSelector. Otherwise it selects the Pods matching PodSelector in
     the policy's own Namespace.

kiosk@k8s-master:~$ 
```
What's the fourth one?

**Comment by AmarNathChary** [comment]
@choshitautetsu I think these three selectors are correct. Saying four kinds could be incorrect.
WDYT?

**Comment by choshitautetsu** [comment]
yeah, so https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors saying 
> There are four kinds of selectors that can be specified in an ingress from section or egress to section.  

should be change to 

> There are three kinds of selectors that can be specified in an ingress from section or egress to section.  

Given that there are only this three kinds of selectors.

**Comment by dipesh-rawat** [comment]
**_Page related to the issue:_** https://kubernetes.io/docs/concepts/services-networking/network-policies

/retitle Improper count of Ingress/Egress NetworkPolicy selectors on the `Network Policies` page

**Comment by sambhavgupta0705** [comment]
Hi, I would like to resolve this issue 😃

**Comment by choshitautetsu** [comment]
Sure, How can i help you

**Comment by sambhavgupta0705** [comment]
> Sure, How can i help you

Can I work on this😀

**Comment by AmarNathChary** [comment]
Hi @sambhavgupta0705 you can assign this issue by commenting  **assign** followed by **"/"**

**Comment by vaibhav2107** [comment]
@choshitautetsu As we can see and also the [comment](https://github.com/kubernetes/website/pull/41750#issuecomment-1606062327) says there are four kinds of selectors listed.

**Comment by vaibhav2107** [comment]
I think this issue is invalid and could be closed now
