### ISSUE TITLE
Need top-level Controllers concept guide

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#4135]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**

No overarching Concept guide for controllers.

**Proposed Solution:**

Write one.

**Page to Update:**
 New page to be added.

We have Concept docs for various controllers:

- docs/concepts/workloads/controllers/deployment.md
- docs/concepts/workloads/controllers/daemonset.md
- docs/concepts/workloads/controllers/replicaset.md
- docs/concepts/workloads/controllers/replicationcontroller.md
- docs/concepts/workloads/controllers/statefulset.md
 
We have Tasks for types of applications:

- docs/tasks/run-application/run-single-instance-stateful-application.md
- docs/tasks/run-application/run-stateless-application-deployment.md
- docs/tasks/run-application/run-replicated-stateful-application.md

We do not have an overarching doc that covers the following use cases:

- To define what we mean by the word controller.
- To help the users select the right one 
- To explain concepts common to all controllers.
- To explain that there are built-in controllers, but that users can write their own (Operators).

@kubernetes/sig-apps-feature-requests

**Comment by erictune** [comment]
There is an incomplete list of controllers in docs/concepts/workloads/pods/pod-lifecycle.md

**Comment by erictune** [comment]
Common responsibilities for Kubernetes controllers:

- Kubernetes controllers automatically create replacement pods in the face of node failures.
- Kubernetes controllers aggregate status of their pods, so that the CLI and UI can summarize.
- and so on.

**Comment by enisoc** [comment]
+1 I would have liked to link to such a doc from https://github.com/kubernetes/kubernetes.github.io/pull/4071.

**Comment by erictune** [comment]
Also, this doc could talk about roll-forward and back in a general way, across SS, DS, Deployment, RS.  And ControllerRevision.

**Comment by erictune** [comment]
Started a draft for this here:
https://docs.google.com/document/d/1jDPTKIRUf_UaVUu_BNu9IxXZR61rZ4MLPDRDWOevczg/view

Collecting content.

**Comment by metmajer** [comment]
@erictune: this is going to be a very valuable feature. Is there any way I could help out with this PR?

**Comment by markmandel** [comment]
How can I also get involved? I think it would be great if this resource existed - especially separate from CRDS (as they may not necessarily go together). I have a huge list of external examples and resources I used to learn about Controllers. 

Here is my  [Friction Log](https://docs.google.com/document/d/1N1pBov7Odpg_u-kILHcswYh4VO-aMlYQdFIH64DYeek/edit#) if it helps.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

still relevant.

**Comment by bradtopol** [comment]
@markmandel @metmajer @erictune We would love to see this content get completed. Would one of you be willing to take the lead on generating the content? I can help with any questions you may have on submitting a PR

**Comment by erictune** [comment]
Linking to this would be a good start:
https://book.kubebuilder.io/basics/what_is_a_controller.html

**Comment by sftim** [comment]
I'm sketching out how to do this. I won't `/assign` it to myself; if anyone wants to join in, I'll be happy to collaborate.

**Comment by sftim** [comment]
#12323 might be (very slightly) relevant here

**Comment by zacharysarah** [comment]
@sethmccombs 👋 Thanks for following up with @sftim.

**Comment by sftim** [comment]
I've got a **big** bunch of changes that apply cleanly to `master`.

I'm going to wait for Kubernetes v1.15 to be out and for the dust to settle. Then I'll make branches with subsets of the overall changes and send in pull requests (there could be several size/XXL PRs to come from this).

**Comment by zacharysarah** [comment]
@sftim 👋 Any updates?

**Comment by sftim** [comment]
I've been away-from-keyboard for a week. Will update this.

**Comment by bradtopol** [comment]
Thanks @sftim please feel free to ping me when its ready for review

**Comment by sftim** [comment]
/close
Resolved by #15733 
If there's part of the task still left to do, I recommend opening a new issue and referencing this closed one.
