### ISSUE TITLE
Outdated advice in “Changing the Container Runtime on a Node from Docker Engine to containerd”

### ISSUE THREAD

**Issue by niraj8241** [kubernetes/website#41371]
In this section **"Configure the kubelet to use containerd as its container runtime"** here at https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/#configure-the-kubelet-to-use-containerd-as-its-container-runtime. The value `--container-runtime=remote` is not a supported parameter anymore and causes the node to be unhealthy.

**Comment by sftim** [comment]
/retitle Outdated advice in “Changing the Container Runtime on a Node from Docker Engine to containerd”
/sig node
/language en

**Comment by sftim** [comment]
The page at https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/#configure-the-kubelet-to-use-containerd-as-its-container-runtime states:
> It is applicable for cluster operators running Kubernetes 1.23 or earlier

If you're already running a newer version of Kubernetes, these upgrade instructions aren't applicable.

I think we could update https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/#before-you-begin to repeat and emphasize that context.

Alternative approaches could work too! Feel free to suggest one.
