### ISSUE TITLE
Feature gates `ServiceIPStaticSubrange` and `ServiceInternalTrafficPolicy` incorrectly marked as beta

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#41379]
**This is a Bug Report**

**Problem:**
The FEATURE STATE  of the following features is mentioned wrongly(outdated) under the [Virtual IPs and Service Proxies](https://kubernetes.io/docs/reference/networking/virtual-ips/) docs:
1. [IP address ranges for Service virtual IP addresses](https://kubernetes.io/docs/reference/networking/virtual-ips/#service-ip-static-sub-range): The corresponding feature gate is `ServiceIPStaticSubrange` and mentioned Feature State is `Kubernetes v1.25 [beta]`
2. I[nternal traffic policy](https://kubernetes.io/docs/reference/networking/virtual-ips/#internal-traffic-policy): The corresponding feature gate is `ServiceInternalTrafficPolicy` and mentioned Feature State is `Kubernetes v1.22 [beta]`

**Proposed Solution:**
According to the [Feature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) docs, for `ServiceIPStaticSubrange` Feature State should be `Kubernetes v1.26 [stable]` and for `ServiceInternalTrafficPolicy` Feature State should be `Kubernetes v1.26 [stable]`
**Page to Update:**
https://kubernetes.io/docs/reference/networking/virtual-ips/

**Comment by Shubham82** [comment]
Fixed it here: #41381

**Comment by sftim** [comment]
/retitle Feature gates `ServiceIPStaticSubrange` and `ServiceInternalTrafficPolicy` incorrectly marked as beta
