### ISSUE TITLE
Install and Set Up kubectl on Linux

### ISSUE THREAD

**Issue by signoredellarete** [kubernetes/website#41377]
There is an error in the installation instruction https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

This command:
```
sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
```
Must be changed with this:
```
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://dl.k8s.io/apt/doc/apt-key.gpg
```

**Comment by dipesh-rawat** [comment]
@signoredellarete A few hours ago, we merged updates to the documentation for the Kubectl installation page concerning the Google signing key.  

Could you try the new command listed on the page https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/

```
curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
```

/language en
/triage needs-information

**Comment by signoredellarete** [comment]
OK, it works.
Thank you!
