### ISSUE TITLE
Incorrect instructions on the version of control plane nodes to bring down during the control plane upgrade

### ISSUE THREAD

**Issue by nicksc423** [kubernetes/website#41383]
There appears to be a typo [here](https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/#initial-leader-migration-configuration:~:text=In%20a%20rolling%20manner%2C%20create%20a%20new%20control%20plane%20node%20of%20version%20N%20%2B%201%20and%20bring%20down%20one%20of%20version%20N%20%2B%201%20until%20the%20control%20plane%20contains%20only%20nodes%20of%20version%20N%20%2B%201):

> In a rolling manner, create a new control plane node of version N + 1 and bring down one of version N + 1 until the control plane contains only nodes of version N + 1

I believe it should be:
> In a rolling manner, create a new control plane node of version N + 1 and bring down one of version N until the control plane contains only nodes of version N + 1

If we create nodes of version N+1 and bring down nodes of n+1 we will be looping forever!

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration

/language en

**Comment by dipesh-rawat** [comment]
/retitle Incorrect instructions on the version of control plane nodes to bring down during the control plane upgrade

**Comment by tengqm** [comment]
Sounds reasonable to me.

**Comment by niranjandarshann** [comment]
wants to work on the issue
/assign

**Comment by niranjandarshann** [comment]
I had raised a PR for this issue please have a look on it. @tengqm

**Comment by niranjandarshann** [comment]
issue resolved so we can close the issue
/close

**Comment by dipesh-rawat** [comment]
Changes to address this issue has been merged as part of PR #41388

/close
