### ISSUE TITLE
[fr] Remove outdated online interactive tutorial from `Using Minikube to Create a Cluster` page

### ISSUE THREAD

**Issue by sesram57** [kubernetes/website#41380]
Hi, the tutorial in French is outdated, it still offers to perform the tests online.

**Comment by tamilselvan1102** [comment]
Page to be updated : https://kubernetes.io/fr/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

**Comment by dipesh-rawat** [comment]
/retitle [fr] Remove outdated online interactive tutorial from `Using Minikube to Create a Cluster` page
