### ISSUE TITLE
Fix deprecation notice for https://kubernetes.io/docs/reference/tools/map-crictl-dockercli/

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41385]
**This is a Bug Report**

**Problem:**
https://v1-26.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/ still says that the page will be removed in v1.27
https://kubernetes.io/docs/reference/tools/map-crictl-dockercli/ doesn't, and the page is still there.

I agree with not removing the page outright. However, could we perhaps replace that whole page with a link to 
https://v1-24.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/ and a brief note about why we have done so?

**Proposed Solution:**

Replace that whole page with a link to 
https://v1-24.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/ and a brief note about why we have done so?

We can also backport it so that 
- https://v1-26.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/
- https://v1-27.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/

link to https://v1-24.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/ as well

**Page to Update:**
https://kubernetes.io/docs/reference/tools/map-crictl-dockercli/

**Additional Information:**

/language en
/sig node
/kind bug

/milestone 1.28

**Comment by Ritikaa96** [comment]
We can do something like:

> This page is being directed to https://v1-24.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/ because of [Removal of dockershim from crictl in v1.24](https://github.com/kubernetes-sigs/cri-tools/issues/870)  and
> as per our community policy to not continue maintainership of deprecated doc beyond three versions
> To find the reason for deprecation see [here](https://kubernetes.io/blog/2020/12/02/dockershim-faq/)
>

**Comment by Ritikaa96** [comment]
I'd start the work and should i backport v1.26 and ,v1.27 as well?


> We can also backport it so that
> 
> * https://v1-26.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/
> * https://v1-27.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/
> 
> link to https://v1-24.docs.kubernetes.io/docs/reference/tools/map-crictl-dockercli/ as well

**Comment by Ritikaa96** [comment]
Raised a PR , adding the link to redirect to v1.24 , 
Please confirm if i should backport v1.26 content just the same as well.

**Comment by Ritikaa96** [comment]
Hi, @sftim Raised a [PR](#41407 ) for change in v1.27 docs.
should I do the change in v1.26 in the same PR?

**Comment by Ritikaa96** [comment]
Added v1.26 changes in #42017, PTAL!!
