### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/jsonpath/

### ISSUE THREAD

**Issue by walterschnider** [kubernetes/website#41404]
Hi

How could I get out a label named "app.kubernetes.io"?

.items[0].metadata.labels.app is working -> "appl-name" 
but .items[0].metadata.labels.app.kubernetes.io -> ''

Thanks and Regards
Walter

**Comment by T-Lakshmi** [comment]
/language en
page: https://kubernetes.io/docs/reference/kubectl/jsonpath/

**Comment by T-Lakshmi** [comment]
Hi @walterschnider,

> .items[0].metadata.labels.app.kubernetes.io -> ''

I guess you should use it somthing like this below.
Ex:
**.items[0].metadata.labels.app.kubernetes.io/name**

**Comment by walterschnider** [comment]
Hi
Thanks for your Feedback - but this is syntax gives me also no result. It must be an issue with / in the labelname.

**Comment by T-Lakshmi** [comment]
Hi @walterschnider,

> Thanks for your Feedback - but this is syntax gives me also no result. It must be an issue with / in the labelname.

yes, when you mention . (dot) or / under label its treating as sub path under labels and result giving blank.
Try with keeping \ before dot and backward slash.

It should work for you.

**Comment by T-Lakshmi** [comment]
Hi @walterschnider,

> Thanks for your Feedback - but this is syntax gives me also no result. It must be an issue with / in the labelname.

yes. When you mention **. (dot) or /** under labels section, its treating as sub path under labels section and result giving blank output as there is no such path.
Try with keeping **\ (forward slash)** before **dot(.) and backward slash(/)**.

It should work for you.

**Comment by T-Lakshmi** [comment]
Below is the example for your reference.

![json](https://github.com/kubernetes/website/assets/56723673/f4061a3a-3164-4f51-9275-96a0b30a4274)

I hope this will help for you.

**Comment by walterschnider** [comment]
Thank you very much. This is now worling. I think is realy helping to add a example.
