### ISSUE TITLE
Advice with page “Install and Set Up kubectl on Windows”

### ISSUE THREAD

**Issue by johnwilburn-svt** [kubernetes/website#41415]
I had an issue after installing kubectl where it kept saying kubelogin did not exist even though it was installed as well. The issue ended up being the the config file did not have an extension. I saved the config as config.kcfg and the commands worked. I believe there is an issue with the installer not properly naming the config file config.kcfg.

**Comment by sftim** [comment]
/retitle Advice with page “Install and Set Up kubectl on Windows”
/kind support
/sig windows

> I believe there is an issue with the installer not properly naming the config file `config.kcfg`.

That doesn't sound right to me. Kubernetes uses `%USERPROFILE%\.kube\config` by default.

**Comment by johnwilburn-svt** [comment]
When I would run a kubectl command with it just being named config without an extension I would get an error that kubelogin did not exist. A coworker showed me a command where the included a parameter specifying the path to the config file and their command had config.kcfg instead of just config. I saved my config file as config.kcfg and then I was able to use the kubectl command successfully

John Wilburn
Jr. Deployment Engineer
757.274.4539
svtrobotics.com
***@***.******@***.***>
***@***.***<https://svtroboticscom.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2FShared%20Documents%2F%5FCompany%2FMarketing%2FMarketing%2DSVT%2DShare%2F01%20Brand%2C%20Logos%2C%20and%20more%2F04%20HTML%20Email%20Signature%2FHTML%2FSVT%2Dsig%2DLT%2D22%2Ehtml&parent=%2FShared%20Documents%2F%5FCompany%2FMarketing%2FMarketing%2DSVT%2DShare%2F01%20Brand%2C%20Logos%2C%20and%20more%2F04%20HTML%20Email%20Signature%2FHTML>

**Comment by Ritikaa96** [comment]
Hi @johnwilburn-svt can you send the output which shows error?

**Comment by sftim** [comment]
/close not-planned

This issue isn't actionable as it stands, and appears to be a support query.

@johnwilburn-svt if you can help us to work out what needs fixing, please do - you are very welcome to reopen this issue.
