### ISSUE TITLE
Broken Link in /blog/2023/05/24/oci-security-profiles/

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#41423]
This is a Bug Report

Problem:
Link for **Bundle Bar**  in https://kubernetes.io/blog/2023/05/24/oci-security-profiles/#managing-oci-security-profiles is broken.

Proposed Solution:
Should be updated with correct link

Page to Update:
https://github.com/kubernetes/website/blob/main/content/en/blog/_posts/2023-05-24-oci-security-profiles.md

**Comment by AmarNathChary** [comment]
There seems to be an issue with the Bundle Bar registry, as it is currently unavailable. I think there is no link that can be updated.

**Comment by niranjandarshann** [comment]
> There seems to be an issue with the Bundle Bar registry, as it is currently unavailable. I think there is no link that can be updated.

@AmarNathChary  yes it seems same to me also so i think we can either remove the bundle bar  from the list or  should wait for more comment  from community for the new link.

**Comment by sftim** [comment]
/triage accepted

@niranjandarshann it's best not to mark issues as help wanted when they are not also triaged accepted

**Comment by AmarNathChary** [comment]
As the **Bundle Bar** registry is not working. I think a proper fix could be removing the link for the **Bundle Bar**

**Comment by AmarNathChary** [comment]
@niranjandarshann you can assign this issue if what to fix it

**Comment by niranjandarshann** [comment]
> As the **Bundle Bar** registry is not working. I think a proper fix could be removing the link for the **Bundle Bar**

Agree with you @AmarNathChary . @sftim what is your opinion. can we remove **Bundle Bar**

**Comment by AmarNathChary** [comment]
As the issue is solved now we can close the issue

**Comment by niranjandarshann** [comment]
Thanks @AmarNathChary  for resolving the issue. Marking the issue resolved as per PR #41533 is merged.
/close
