### ISSUE TITLE
Mermaid diagrams not rendering correctly in "Authenticating" page

### ISSUE THREAD

**Issue by mueller-ma** [kubernetes/website#41426]
**This is a Bug Report**

**Problem:**

Open https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens in Chrome or Firefox.

In the mermaid diagram the labels overlap when they contain a  `<br>`:

![grafik](https://github.com/kubernetes/website/assets/22525368/0f73fe27-3d3b-48b3-ace4-5a8679fc7a14)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#openid-connect-tokens

**Comment by dipesh-rawat** [comment]
/retitle Mermaid diagrams not rendering correctly in "Authenticating" page 

/area web-development

**Comment by dipesh-rawat** [comment]
I can replicate this issue on Firefox on MacOS but on Chrome its rendered as expected.

Looks similar to few issues we already have https://github.com/kubernetes/website/issues/31960 https://github.com/kubernetes/website/issues/37357

**Comment by mueller-ma** [comment]
Seems to be fixed
