### ISSUE TITLE
Issue with k8s.io/docs/admin/authentication/

### ISSUE THREAD

**Issue by allre168** [kubernetes/website#4142]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The step #5 of "openssl" that is "openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 10000". The command always results in file conversion error "error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:701:Expecting:CERTIFICATE REQUEST" thus the final file "server.crt" can not be generated.

**Proposed Solution:**
The file type used in the statement might need to be specify more clearly, e.g. PEM or DER format, etc.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
The guide has been rewritten and relocated to k8s.io/docs/concepts/cluster-administration/certificates/. The issue reported should not be a problem any more. Please feel free to reopen this if needed.
