### ISSUE TITLE
[ko] Translate concepts/security/secrets-good-practices in Korean

### ISSUE THREAD

**Issue by Virusuki** [kubernetes/website#41433]
This is a Feature Request

What would you like to be added

Translate concepts/security/secrets-good-practices in Korean

Why is this needed
No translation with concepts/security/secrets-good-practices in Korean

Comments

Page to Update:
https://kubernetes.io/docs/concepts/security/secrets-good-practices/

**Comment by seokho-son** [comment]
/triage duplicate
https://github.com/kubernetes/website/pull/40294

**Comment by seokho-son** [comment]
@Virusuki 님 안녕하세요. 살펴보니, 해당 이슈는 #40294 를 통해 한글화가 완료된 것으로 보입니다.

**Comment by Virusuki** [comment]
@seokho-son  네 확인 감사드립니다. 
해당 이슈는 close 하겠습니다.
