### ISSUE TITLE
Add a shortcode that warns on unmaintained pages

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41446]
**This is a Feature Request**

**What would you like to be added**
Add a shortcode that does nothing provided that a specified version hasn't been reached; otherwise, it prints a build-time warning.

Example:
```markdown
The Marklar API is deprecated and will not be stabilised. If you use it, the kubelet creates readonly
Marklars, and you see a warning every time foo bar.
{{< warn-if version="1.28" >}}
<!-- this explanation will be out of date following the removal of the beta Marklar API -->
<!-- removal is scheduled for v1.28 -->
{{< /warn-if >}}
```

**Why is this needed**
If we add this, it will help release docs folks spot what needs to be updated for a release
(perhaps even to include localization updates!)

**Comments**
This is an idea. Do we think it is worth doing?

/area web-development

**Comment by Nitishupkr** [comment]
please assign it to me i want to work on this issue

**Comment by tamilselvan1102** [comment]
@sftim 
This idea is looking good. 
Can you specify some pages to be updated. it would be help to get more clarity.

**Comment by Nitishupkr** [comment]
@sftim specify some pages

**Comment by sftim** [comment]
I think my fairly frank take on this is that folks should be able to find pages that refer to upcoming Kubernetes versions without special help.
Some clues: the previous minor release was v1.26 and the current minor release is v1.27. To me, the pattern's fairly simple to infer.
