### ISSUE TITLE
[zh] Translate reference/instrumentation/metrics/ into Chinese

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#41441]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**

**Comments**

**Comment by Nitishupkr** [comment]
please assign it to me i can resolve this issue

**Comment by mengjiao-liu** [comment]
/assign @Nitishupkr 

Are you sure? This needs to be translated into Chinese. If you can't, please unassign yourself.

**Comment by mengjiao-liu** [comment]
Are you working on this? @Nitishupkr
