### ISSUE TITLE
Stale wording in User Namespaces page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41445]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/ currently reads:
> Please note that containerd v1.7 supports user namespaces for containers, compatible with Kubernetes 1.27. It should not be used with Kubernetes 1.27 (and later).

I was involved in suggesting that text. What I'd hoped was that we'd revise it ahead of the v1.27 release. It looks like that didn't happen - oops!

**Proposed Solution:**
Amend the text of https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/ to explain what container runtimes can (or can't) work with K8s v1.27 in user namespace mode. Aim to make the explanation also stay relevant past the v1.28 release.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/

**Additional Information:**
/sig node

**Comment by Nitishupkr** [comment]
please assign  it to me i can solve this issue

**Comment by sftim** [comment]
Anyone who'd like to open a PR with a fix is welcome to. It's polite to co-ordinate with other contributors who may be working in the same area.
