### ISSUE TITLE
[pt-br] Obsolete online interactive tutorial in the Using Minikube to Create a Cluster page

### ISSUE THREAD

**Issue by Kurosaki-Kman** [kubernetes/website#41456]
The terminal to use the interactive tutorials is using Katacoda, however, it was purchased by O'Reilly and is outside the domain that the terminal is using to run.

**Comment by AmarNathChary** [comment]
Hi @Kurosaki-Kman You can ask support queries in [k8s slack](https://communityinviter.com/apps/kubernetes/community) channels.

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/pt-br/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

/language pt

**Comment by dipesh-rawat** [comment]
/retitle [pt-br] Remove the obsolete online interactive tutorial from the `Using Minikube to Create a Cluster` page

**Comment by dipesh-rawat** [comment]
For anyone willing to assist on this, please refer to PR #40306 for information regarding the implementation of similar changes carried out on the main website (i.e. English pages).

**Comment by sftim** [comment]
/retitle [pt-br] Obsolete online interactive tutorial in the Using Minikube to Create a Cluster page

/kind bug
