### ISSUE TITLE
[ja] Obsolete online interactive tutorial from the Using Minikube to Create a Cluster page

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#41468]
**This is a Feature Request**
Remove Katacoda interactive tutorials on the [Using Minikube to Create a Cluster] page

**What would you like to be added**
Page related to issue: [cluster-intro](https://kubernetes.io/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/)

**Why is this needed**
https://github.com/kubernetes/website/pull/39257

**Comment by tamilselvan1102** [comment]
For anyone willing to assist on this, please refer to PR https://github.com/kubernetes/website/pull/40306 for information regarding the implementation of similar changes carried out on the main website (i.e. English pages).

貢献したい方は[このPR](https://github.com/kubernetes/website/pull/40306)を参考してください。

**Comment by sftim** [comment]
/retitle [ja] Obsolete online interactive tutorial from the Using Minikube to Create a Cluster page

/kind bug

/remove-good-first-issue

I don't think this is a good first issue.
/help

However, help (from Japanese localizers) is welcome.

**Comment by sftim** [comment]
Actually, we should also not request help, as the issue is not yet triaged.
/remove-help
/remove-kind feature
