### ISSUE TITLE
Outdated links in prerequisites for Updating Reference Documentation

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#41472]
**This is a Bug Report**

**Problem:**

- Update the Golang installation page.
- Update information about Kubernetes moving on from dockershim.

**Proposed Solution:**
- Update from https://golang.org/doc/install to https://golang.org/doc/install
- Mention blog in Docker installation - https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/

**Page to Update:**
https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/generate-ref-docs/prerequisites-ref-docs.md

**Comment by sftim** [comment]
/retitle Outdated links in prerequisites for Updating Reference Documentation

**Comment by sftim** [comment]
We don't need to link to https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/

Kubernetes doesn't directly support using Docker as a container runtime. However, contributors are still welcome to use Docker for development and related tasks.

**Comment by utkarsh-singh1** [comment]
Hi @sftim, As Kubernetes is already following OCI compliant container runtime, Maybe there should mention of those tools also.

**Comment by utkarsh-singh1** [comment]
Or we can mention nerdctl, podman and docker.
