### ISSUE TITLE
Image can't be pulled by following the HorizontalPodAutoscaler Walkthrough page

### ISSUE THREAD

**Issue by yzhao66** [kubernetes/website#41474]
container "php-apache" in pod "php-apache-779cd44bdc-wzmzg" is waiting to start: image can't be pulled

镜像拉取不到

**Comment by tamilselvan1102** [comment]
Please describe the issue clearly

**Comment by tamilselvan1102** [comment]
is this the page are you following : https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

**Comment by yzhao66** [comment]
stream logs failed container "php-apache" in pod "php-apache-779cd44bdc-wzmzg" is waiting to start: trying and failing to pull image for default/php-apache-779cd44bdc-wzmzg (php-apache)

**Comment by utkarsh-singh1** [comment]
Hi @yzhao66, Image seems to work and It has successfully run the pod and deployment , 

-> 
`kubectl get deployments -o wide`

```bash
NAME         READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                        SELECTOR
php-apache   1/1     1            1           39s   php-apache   registry.k8s.io/hpa-example   run=php-apache
```

-> 
`kubectl get pods -o wide`

```bash
NAME                          READY   STATUS    RESTARTS      AGE   IP            NODE       NOMINATED NODE   READINESS GATES
php-apache-7495ff8f5b-rw4n9   1/1     Running   0             32s   10.244.0.72   minikube   <none>           <none>
```

**Comment by yzhao66** [comment]
still hava this problem
![image](https://github.com/kubernetes/website/assets/44268973/fcb4eaf6-ae85-434e-8568-41b729b09827)

**Comment by pawankukreja01** [comment]
you can try deleting the pod and letting Kubernetes recreate it. This will force Kubernetes to pull the image again

**Comment by vinay-agens** [comment]
It might be due to network issues or the image being unavailable. You can try pulling the image directly using Docker or another tool. If you're still having trouble, I would recommend checking the issue page for any updates or potential solutions. 

If none of these work, you might want to consider opening a new issue on the Kubernetes GitHub page. 

Hope this helps!

**Comment by sftim** [comment]
/close not-planned

This issue isn't actionable as it stands, and appears to be a support query.

**Comment by carvido1** [comment]
Hello @yzhao66 , is you system arm64/aarch64? I've noticed this container image latest tag is from 2015 and its architecture is amd64. This could be a potential issue when running it in arm64.
