### ISSUE TITLE
Dynamic resource allocation docs mark this as “new” / timelessness concern

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41482]
**This is a Bug Report**

**Problem:**
We like [timeless](https://developers.google.com/style/timeless-documentation) Kubernetes documentation.
With the upcoming v1.28 release, dynamic resource allocation will be no longer new.

**Proposed Solution:**
Update the v1.28 docs (branch _dev-1.28_) to remove the “new” adjective from 
`/docs/concepts/scheduling-eviction/dynamic-resource-allocation/`

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/

**Additional Information:**
/sig node
/language en

**Comment by vaibhav2107** [comment]
Fixed by #41483
