### ISSUE TITLE
[zh-cn] Replace deprecated `fullversion` shortcode

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#41484]
**Problem:**

Based on https://github.com/kubernetes/website/issues/41005, I have created this issue/task to help update the [zh-cn] language documentation.

> We've deprecated the `fullversion` param (`{{< param "fullversion" >}}`) and now English documents are using `{{< skew currentPatchVersion >}}` instead. (by #40692)
> 
> All the other documents need to change `{{< param "fullversion" >}}` into `{{< skew currentPatchVersion >}}` or `v{{< skew currentPatchVersion >}}` appropriatly.
> 
> Since several languages are involved, I'd like to share this issue to check all localizations complete the task.

**Proposed Solution:**

> For each localization team, search `fullversion` and change appropriately. (See the reference, https://github.com/kubernetes/website/pull/40692/files)

**Page to Update:**

In the `main` branch, I found:

Results for "param "fullversion"" in "k8s-website/content/zh-cn"

/home/rdlugyhe/kubernetes/k8s-website/content/zh-cn/docs/tasks/tools/install-kubectl-linux.md:
  96:     curl -LO https://dl.k8s.io/release/{{< param "fullversion" >}}/bin/linux/arm64/kubectl

/home/rdlugyhe/kubernetes/k8s-website/content/zh-cn/docs/tasks/tools/install-kubectl-windows.md:
  58:  1. Download the [latest release {{< param "fullversion" >}}](https://dl.k8s.io/release/{{< param "fullversion"
  58:  "fullversion" >}}](https://dl.k8s.io/release/{{< param "fullversion" >}}/bin/windows/amd64/kubectl.exe).

**Comment by rolfedh** [comment]
cc: @seokho-son

**Comment by seokho-son** [comment]
Resolved by #41528

/close

**Comment by sftim** [comment]
/reopen
We should also update `content/zh-cn/docs/tasks/tools/install-kubectl-windows.md`
