### ISSUE TITLE
[ru] Replace deprecated `fullversion` shortcode

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/website#41487]
**Problem:**

Based on https://github.com/kubernetes/website/issues/41005, I have created this issue/task to help update the [ru] language documentation.

> We've deprecated the `fullversion` param (`{{< param "fullversion" >}}`) and now English documents are using `{{< skew currentPatchVersion >}}` instead. (by #40692)
> 
> All the other documents need to change `{{< param "fullversion" >}}` into `{{< skew currentPatchVersion >}}` or `v{{< skew currentPatchVersion >}}` appropriatly.
> 
> Since several languages are involved, I'd like to share this issue to check all localizations complete the task.

**Proposed Solution:**

> For each localization team, search `fullversion` and change appropriately. (See the reference, https://github.com/kubernetes/website/pull/40692/files)

**Page to Update:**

**In the `dev-1.17-ru.1` branch, I found:**

Results for "fullversion" in "k8s-website/content/ru"

/home/rdlugyhe/kubernetes/k8s-website/content/ru/docs/tasks/tools/install-kubectl.md:
  33:      Например, для установки версии {{< param "fullversion" >}} на Linux введите:
  36:  storage.googleapis.com/kubernetes-release/release/{{< param "fullversion" >}}/bin/linux/amd64/kubectl
  110:      Например, для установки версии {{< param "fullversion" >}} на macOS введите:
  113:  storage.googleapis.com/kubernetes-release/release/{{< param "fullversion" >}}/bin/darwin/amd64/kubectl
  175:  1. Загрузите последний релиз {{< param "fullversion" >}} по [этой ссылке](https://storage.googleapis.com
  175:  storage.googleapis.com/kubernetes-release/release/{{< param "fullversion" >}}/bin/windows/amd64/kubectl.exe).
  180:  storage.googleapis.com/kubernetes-release/release/{{< param "fullversion" >}}/bin/windows/amd64/kubectl.exe

**In the `main` branch, I found:**

Results for "fullversion" in "k8s-website/content/ru"

/home/rdlugyhe/kubernetes/k8s-website/content/ru/docs/concepts/containers/container-environment.md:
  44:  DNS, если включен [аддон DNS](https://releases.k8s.io/{{< param "fullversion" >}}/cluster/addons/dns/). 

/home/rdlugyhe/kubernetes/k8s-website/content/ru/docs/setup/learning-environment/minikube.md:
  222:  чтобы запустить Minikube из-под версии {{< param "fullversion" >}}, вам нужно выполнить следующую команду:
  225:  minikube start --kubernetes-version {{< param "fullversion" >}}

/home/rdlugyhe/kubernetes/k8s-website/content/ru/docs/tasks/tools/install-kubectl.md:
  36:  Например, команда загрузки версии {{< param "fullversion" >}} для Linux будет выглядеть следующим образом
  39:      curl -LO https://dl.k8s.io/release/{{< param "fullversion" >}}/bin/linux/amd64/kubectl
  116:  Например, команда загрузки версии {{< param "fullversion" >}} для macOS будет выглядеть следующим образом
  119:      curl -LO https://dl.k8s.io/release/{{< param "fullversion" >}}/bin/darwin/amd64/kubectl
  183:  1. Загрузите последнюю версию {{< param "fullversion" >}} по [этой ссылке](https://dl.k8s.io/release/{{<
  183:  по [этой ссылке](https://dl.k8s.io/release/{{< param "fullversion" >}}/bin/windows/amd64/kubectl.exe).
  188:      curl -LO https://dl.k8s.io/release/{{< param "fullversion" >}}/bin/windows/amd64/kubectl.exe

/sig docs
/sig localization
/language ru
cc: @seokho-son

**Comment by rolfedh** [comment]
@seokho-son It looks like Russian language content in `dev-1.17-ru.1` (dormant) and `main` branches are out of sync. I suspect that some contributions have been made to `/ru` through the `main` branch. Therefore, I've created two PRs to fix the issue on both branches. What do you think?

**Comment by sftim** [comment]
I think the Russian localization team are mainly working on _main_. I'd be happy to delete the _dev-1.17-ru.1_ branch, although we might want to see if there is useful work there to cherry-pick into other PRs first.

**Comment by sftim** [comment]
The Russian localization team should decide, not me.

**Comment by seokho-son** [comment]
@rolfedh I left a message in the `#kubernetes-docs-ru` channel as follows.

> Hi folks :slightly_smiling_face: I'd like to know the default branch for Russian localization.
> dev-1.17-ru.1 is still in use? if not, we'd better remove the stale branch.
> Also, PTAL this discussion https://github.com/kubernetes/website/issues/41487#issuecomment-1578728794 regarding PR target branch to update Russian content.

Let's wait some responses from folks in the channel. :)

**Comment by seokho-son** [comment]
I got a response from Dmitry. :)

> Dmitry Shurupov
> Hi Seokho! I saw that issue, was going to reply to it later today…
> This branch was created long before I stepped into managing the localisation, and nobody used it for years already. So we're happy to remove it.

@rolfedh Let's close https://github.com/kubernetes/website/pull/41493
@sftim Please remove the stale branch `dev-1.17-ru.1` :)

**Comment by rolfedh** [comment]
> @rolfedh Let's close #41493
Done.
> @sftim Please remove the stale branch `dev-1.17-ru.1` :)
Created https://github.com/kubernetes/website/issues/41545

**Comment by sftim** [comment]
Folks, please consider asking [the set of maintainers] and not [the set of maintainers called sftim].

In the Kubernetes community, we try to include people. Naming specific contributors is usually fine when someone has started work and there's an intent to progress it; it can actually serve to exclude people if the job is still waiting for someone to pick it up.
