### ISSUE TITLE
Issue with pod-lifecycle.md

### ISSUE THREAD

**Issue by johnfosborneiii** [kubernetes/website#4150]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

The Restart Policy has a broken link.

**Proposed Solution:**

Change link from:
https://kubernetes.io/docs/user-guide/pods/#durability-of-pods-or-lack-thereof
to:
https://kubernetes.io/docs/concepts/workloads/pods/pod/#durability-of-pods-or-lack-thereof

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/concepts/workloads/pods/pod-lifecycle.md

**Comment by tengqm** [comment]
This has been fixed using redirects.
