### ISSUE TITLE
Tasks -> Administer Cluster too long and unorganized

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#4153]
I tried grouping some stuff in the following picture, but this **Administer a Cluster** section is slowly turning into a long list of unorganized articles.

Should we be doing anything about this? cc: @steveperry-53 @chenopis 

![image](https://user-images.githubusercontent.com/159209/27399434-9b9c970c-5671-11e7-8246-11fb04bfd2d4.png)

**Comment by chenopis** [comment]
Yeah, we should probably start nesting them together.

**Comment by zacharysarah** [comment]
I'm flagging this for `Docs Review: Open Issues`&mdash; this seems like an opportunity/test case to review how we organize content under subheadings across the site.
