### ISSUE TITLE
Pull an Image from a Private Registry

### ISSUE THREAD

**Issue by creatldd1** [kubernetes/website#41552]
Page https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
The example below doesn't work anymore. Link is dead apparently
```
curl -L -o my-private-reg-pod.yaml https://k8s.io/examples/pods/private-reg-pod.yaml
```

**Comment by tamilselvan1102** [comment]
it is working fine for me
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret

**Comment by tamilselvan1102** [comment]
Please describe the issue in more detail

**Comment by AmarNathChary** [comment]
/language en
/sig docs
it is working fine for me too.

**Comment by creatldd1** [comment]
I tried again "curl -L -o my-private-reg-pod.yaml
https://k8s.io/examples/pods/private-reg-pod.yaml" and it worked; it might
have been a temporary failure from my ISP.
On the other hand, parent directory "https://k8s.io/examples/pods"  returns
404, but that might be on purpose.

Thanks for your help.

**Comment by tamilselvan1102** [comment]
"https://k8s.io/examples" Path is only meant for download the example yaml files. So use the full path when required

**Comment by tamilselvan1102** [comment]
please close the issue, if you got the answer
