### ISSUE TITLE
Add more package managers for installing kubectl in Linux

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#41551]
**This is a Bug Report**

**Problem:**
We are using snap and Homebrew as package managers for installing kubectl, but both Homebrew and snap are 3rd party package managers that are not available on most of the systems and are required to install separately first, while most of the distribution (fedora, arch, void etc.) provide kubectl package out of the box.

**Proposed Solution:**
We can have a list of available Linux distribution that package kubectl in their repo with the version available.

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-other-package-management

**Comment by satyampsoni** [comment]
Could you pls assign this issue to me?

**Comment by sftim** [comment]
/priority awaiting-more-evidence

> We can have a list of available Linux distribution that package kubectl in their repo with the version available.

We don't want to maintain this. See https://github.com/kubernetes/enhancements/tree/master/keps/sig-docs/1326-third-party-content-in-docs for why. Essentially, it adds a lot of work that we don't have capacity for right now.

**Comment by utkarsh-singh1** [comment]
> /priority awaiting-more-evidence
> 
> > We can have a list of available Linux distribution that package kubectl in their repo with the version available.
> 
> We don't want to maintain this. See https://github.com/kubernetes/enhancements/tree/master/keps/sig-docs/1326-third-party-content-in-docs for why. Essentially, it adds a lot of work that we don't have capacity for right now.

Hi @sftim, How about packaging status that is now most of the projects nowadays in like this - 
![Screenshot_20230608_234922](https://github.com/kubernetes/website/assets/96516301/d6486678-fa98-41df-acc9-1a8bdeedaa2e)

**Comment by utkarsh-singh1** [comment]
I am in for the current layout on the website as the way currently they are, but a link to the kubectl repo where this list of packaging status is also good.

**Comment by sftim** [comment]
> Hi @sftim, How about packaging status that is now most of the projects nowadays in like this -

We don't really have capacity to maintain this (and there's other work that I think we should prioritize). However, if the situation changes, we could add it.
