### ISSUE TITLE
Need to add some nice vectors for Kubernetes Features

### ISSUE THREAD

**Issue by MohamedMafaz** [kubernetes/website#41567]
I'm UI UX Designer. According to UX theory, we need to show some images in between of texts. Kindly assign me this issue. I'll work on it

**Comment by niranjandarshann** [comment]
@MohamedMafaz Yes, pictorial representation of any feature is easy to understand. can you please provide the link where you want to show the image in between of text.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

We'd love to know more about what's being proposed.

**Comment by niranjandarshann** [comment]
Closing this issue marking as inactive from long time. or not planned.
/close
