### ISSUE TITLE
Deployments - kubectl edit error: At least one of apiVersion, kind and name was changed

### ISSUE THREAD

**Issue by jctradecode** [kubernetes/website#41562]
K8s version
v1.27.1

I'm trying to update the below deployment  code to change the deployment name from nginx to jc-nginx

kubectl edit deployment ngix

before edit
------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"nginx"},"name":"nginx","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx","name":"nginx","resources":{}}]}}},"status":{}}
  creationTimestamp: "2023-06-08T15:08:49Z"
  generation: 1
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "6850290"
  uid: d5097477-8c81-4159-8196-0b50de145b85
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-08T15:08:53Z"
    lastUpdateTime: "2023-06-08T15:08:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-08T15:08:49Z"
    lastUpdateTime: "2023-06-08T15:08:53Z"
    message: ReplicaSet "nginx-77b4fdf86c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"

After edit
------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"nginx"},"name":"nginx","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx","name":"nginx","resources":{}}]}}},"status":{}}
  creationTimestamp: "2023-06-08T15:08:49Z"
  generation: 1
  labels:
    app: nginx
  name: jc-nginx
  namespace: default
  resourceVersion: "6850290"
  uid: d5097477-8c81-4159-8196-0b50de145b85
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-08T15:08:53Z"
    lastUpdateTime: "2023-06-08T15:08:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-08T15:08:49Z"
    lastUpdateTime: "2023-06-08T15:08:53Z"
    message: ReplicaSet "nginx-77b4fdf86c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"

But getting this error, what is wrong with it?
error: At least one of apiVersion, kind and name was changed

**Comment by T-Lakshmi** [comment]
Hi @jctradecode,

GitHub is not the right place for support requests.
If you're looking for someone to help you learn how to configure your Kubernetes cluster and play k8s, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

These places are better to resolve support queries fast.

**Comment by T-Lakshmi** [comment]
@jctradecode,

> error: At least one of apiVersion, kind and name was changed

As error stats, you are not allowed to change apiVersion, kind, and name of a resource as they are some primary identifiers of a resource. 
so, you can only change name with delete and recreating your object.

**Comment by aj11anuj** [comment]
@jctradecode, I hope your issue is resolved. If not then reach out to [Kubernetes slack](https://communityinviter.com/apps/kubernetes/community) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum. As there you will most likely get a faster resolution for support or query related issues.

/close
