### ISSUE TITLE
Improvement for k8s.io/docs/reference/networking/virtual-ips/

### ISSUE THREAD

**Issue by dumlutimuralp** [kubernetes/website#41564]
In Kubernetes when a node fails, node controller marks the node as unhealthy after 40 seconds. (by default). Node controller then waits for pod-eviction-timeout  (by default 5 minutes) and then updates the API server to set the pods to Terminating state. 

This page does not include info on when exactly kube-proxy reacts to remove the pods (on the failed node) from the endpoints list. Is it after marking the node unhealthy or is after pods get into terminating state ? 

Could you please clarify for the behaviour asked above in the appropriate chapter of the Kubernetes documentation ? 

Thanks in advance.

**Comment by tamilselvan1102** [comment]
page to be update : https://kubernetes.io/docs/reference/networking/virtual-ips/

**Comment by aojea** [comment]
> This page does not include info on when exactly kube-proxy reacts to remove the pods (on the failed node) from the endpoints list. Is it after marking the node unhealthy or is after pods get into terminating state ?

kube-proxy only knows about Endpoints/EndpointSlices and its state, so it only forwards traffic to Endpoints that are Ready or, in some special cases, to Endpoints that are terminating

https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#terminating

a more detailed explanation can be found in 

https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/

**Comment by sftim** [comment]
Let's add some of that detail to https://k8s.io/docs/reference/networking/virtual-ips/ - it would save readers a bunch of clicking.

/priority backlog
/triage accepted

**Comment by sftim** [comment]
Pull requests are welcome - see https://kubernetes.io/docs/contribute/ for tips.

**Comment by chrismetz09** [comment]
Not specifically related to an answer, but it seems a sequence diagram could help explain the different scenarios. But maybe not.

Here is an [example](https://kubernetes.io/docs/contribute/style/diagram-guide/#example-3-k8s-system-flow) from the [Diagram Guide](https://kubernetes.io/docs/contribute/style/diagram-guide/) using [Mermaid](https://mermaid.js.org/syntax/sequenceDiagram.html).


![diagram-guide-example-3](https://github.com/kubernetes/website/assets/5543858/05583528-570f-4b65-9582-12109ba03bf4)
