### ISSUE TITLE
[de] Incorrect translation for word Architecture in k8s.io/de/docs/concepts/architecture

### ISSUE THREAD

**Issue by Streitmacht** [kubernetes/website#41566]
https://kubernetes.io/de/docs/concepts/architecture/

It should be "Architektur" not "Architekur"

**Comment by dipesh-rawat** [comment]
/retitle [de] Incorrect translation for word Architecture in k8s.io/de/docs/concepts/architecture

**Comment by Kavendra09** [comment]
> @Kavendra09: GitHub didn't allow me to assign the following users: me.
> 
> Note that only [kubernetes members](https://github.com/orgs/kubernetes/people) with read permissions, repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time. For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github)

Assign this issue #41566
