### ISSUE TITLE
Include `replica` in glossary and add tooltip for it on "Kubernetes Components" page

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/website#41576]
Just like the pods and the control plane have hover which makes it easier to understand. There should be a hover that should explain what does replica mean here and in what context we are using it as for a beginner it might will be confusing to understand what replica is

**Comment by dipesh-rawat** [comment]
@satyampsoni Would you be able to provide us with the web page's URL that requires modification? If it's possible, it would be helpful to include the URL in the issue description as well.

/language en
/triage needs-information

**Comment by satyampsoni** [comment]
Reference: https://kubernetes.io/docs/concepts/overview/components/

**Comment by dipesh-rawat** [comment]
/retitle Include `replica` in glossary and add tooltip for it on "Kubernetes Components" page
/language en

**Comment by satyampsoni** [comment]
Can I work on it now?

**Comment by sftim** [comment]
/triage accepted

Anyone - including you @satyampsoni - is welcome to open a pull request. This is open source in action!

/priority backlog
