### ISSUE TITLE
Unable to use Katacoda in https://k8s.io/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by blankhang** [kubernetes/website#41573]
Oops! Sorry, we had a problem. Please refresh and try again.
Error - connect ECONNREFUSED 94.130.9.5:8080
We are sorry but we encountered a problem with the connection.
Please refresh and try again.
Sat Jun 10 2023 11:29:27 GMT+0800 (中国标准时间)
io server disconnect
(reference ID: //wsk8s.asia.katacoda.com/simba11/none/32644753/none/1686367767813)

**Comment by utkarsh-singh1** [comment]
Hi @blankhang, please state your problem in the document.

**Comment by utkarsh-singh1** [comment]
Hi @blankhang, the katacoda environment for Kubernetes tutorial has been shut down, you can see the announcement here - https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/,

Work for removal of katacoda on all localized plateform has been started here - https://github.com/kubernetes/website/issues/41496

**Comment by sftim** [comment]
/retitle Unable to use Katacoda in https://k8s.io/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by utkarsh-singh1** [comment]
As katacoda is already removed from the kubernetes docs, we can close this issue.
