### ISSUE TITLE
Update back-off delay description in `Pod Lifecycle` page

### ISSUE THREAD

**Issue by DougHaigh** [kubernetes/website#41570]
Under the 'Container restart policy' it states "After containers in a Pod exit, the kubelet restarts them with an exponential back-off delay (**10s, 20s, 40s, …**), that is capped at five minutes."

The back-off delay actually starts at **0s** which causes an instant restart. 

Please change the back-off delay to '(**0s, 10s, 20s, 40s, ...**)' so that people know there is no back-off the first time a container fails and restarts.

**Comment by dipesh-rawat** [comment]
**_Page related to issue_**:  https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
/language en

**Comment by Rohan-Dah** [comment]
Hii there folks.. Can I work on this issue?
