### ISSUE TITLE
Need assistance in viewing older docs version (eg: 1.18)

### ISSUE THREAD

**Issue by momomobinx** [kubernetes/website#41593]
Help!  How to view earlier versions of documentation？eg: 1.18

**Comment by utkarsh-singh1** [comment]
Hi @momomobinx, you can find the version button at right hand the top of k8s website.

**Comment by utkarsh-singh1** [comment]
Hi @momomobinx, you can build website on your local machine.

**Comment by utkarsh-singh1** [comment]
Instructions are here - https://github.com/kubernetes/website/tree/main#prerequisites

**Comment by dipesh-rawat** [comment]
/retitle Need assistance in viewing older docs version (eg: 1.18)

**Comment by momomobinx** [comment]
> Hi @momomobinx, you can build website on your local machine before that, please switch branch to release-1.18.

ok, thx
