### ISSUE TITLE
Impossible to use the terminal to minikube from documentation

### ISSUE THREAD

**Issue by arabakevin** [kubernetes/website#41595]
![image](https://github.com/kubernetes/website/assets/16837548/1d743d7f-1650-4de9-85d9-016859b9459a)
Hello,
We cannot use the terminal.

**Comment by tamilselvan1102** [comment]
[Katacoda] support has been removed (https://blog.k8s.io/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

For that reason, we won't work on a fix.

**Comment by tamilselvan1102** [comment]
Also it seems to be same issue as https://github.com/kubernetes/website/issues/39505#issuecomment-1434931638

/triage duplicate

**Comment by sftim** [comment]
/remove-triage duplicate
/kind bug
/language fr

Similar, but not a duplicate (different language).

**Comment by sftim** [comment]
We will update this page to remove the Katacoda tutorial.

**Comment by dipesh-rawat** [comment]
We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.

**Comment by dipesh-rawat** [comment]
This looks similar (possibly a duplicate) of issue https://github.com/kubernetes/website/issues/41380 raised two week ago.
