### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by AbhijithGanesh** [kubernetes/website#41592]
Typo in this line

```
Suppose that you made a typo while updating the Deployment, by putting the image name as nginx:1.161 instead of nginx:1.16.1:

kubectl set image deployment/nginx-deployment nginx=nginx:1.161
```

I'd like to patch this!

**Comment by AmarNathChary** [comment]
**Page link**: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

**Comment by mengjiao-liu** [comment]
@AbhijithGanesh  Can you explain what's wrong with this line？

**Comment by AbhijithGanesh** [comment]
Version should be 1.16.1

**Comment by mengjiao-liu** [comment]
However, this section is deliberately miswritten to simulate the Deployment rollback situation.
