### ISSUE TITLE
Add Guidelines for Translating SVG Images in Localization Contributions

### ISSUE THREAD

**Issue by mboukhalfa** [kubernetes/website#41603]
**This is a Feature Request**

A dedicated subsection in the contributor guide that provides guidelines for translating SVG images in contributions to the Kubernetes documentation. The guide should cover topics such as converting text to curves, selecting appropriate fonts, using image editing tools (e.g., Inkscape), and the rationale behind these practices.

**What would you like to be added**
Currently, there is a discussion thread (https://kubernetes.slack.com/archives/C1J0BPD2M/p1686074817552909) where contributors have discussed the process of translating text inside SVG images and the importance of converting text to curves to ensure consistent rendering across different environments. By adding this guide, we can streamline the translation process and provide clarity to contributors, ensuring that translated SVG images meet the documentation standards.

**Why is this needed**
A dedicated guide is essential to help new contributors understand the process of translating images and the community rules associated with it. By providing clear instructions and guidelines, we can empower contributors to effectively translate SVG images in the Kubernetes documentation. This will ensure consistency in the translation process and maintain alignment with the community's standards. Additionally, the guide will serve as a valuable resource for new contributors, enabling them to easily grasp the requirements and expectations related to image translation.

**Comments**
I will create a pull request that includes a short guide for translating SVG images based on the discussion. This issue serves to track the addition of this guide to the Kubernetes documentation and to gather feedback from the maintainers and community members. Your insights, suggestions, and any additional information that should be included in the guide are highly appreciated.

Thank you!

**Comment by seokho-son** [comment]
Thanks @mboukhalfa, I think this issue has been resolved by #41605
Can this issue be closed, or do you expect additional feedback or actions for this issue?

**Comment by mboukhalfa** [comment]
I think we can close it since the guide there seems complete
