### ISSUE TITLE
Documenting & defining the Issue Wrangler Role

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#41601]
Per #38861, SIG Docs is introducing the Issue Wrangler Role. After issuing a [call for inputs](https://groups.google.com/g/kubernetes-sig-docs/c/Nqhq-Tk9V7U), we are ready to move on to the next step of documenting + defining the role formally.

This issue has been opened to track the below efforts

- [x] Document the Issue Wrangler role in our contribution guide per information provided in #38861 . This will need to be done by a PR to k/website and **can be done by a contributor**
- [x] Add Wiki entry for the Issue Wrangler role. 
- [x] Issue call out for nominations

cc: @natalisucks @reylejano

**Comment by divya-mohan0209** [comment]
@octonawish-akcodes : The details of the role have been mentioned in #38861 . 

You may structure it similar to the [PR Wranglers](https://kubernetes.io/docs/contribute/participate/pr-wranglers/) page in our contribution guide & place it under the Participate in SIG Docs section.

**Comment by octonawish-akcodes** [comment]
Got it :)

**Comment by divya-mohan0209** [comment]
@octonawish-akcodes - Please could you advise if you have commenced work on this PR? It has been three weeks, which is why the check-in. If you're unable to work on it due to bandwidth issues, that is completely fine. Please let us know. Failing any response by Friday EOD, we will be assigning this to someone internally so that they can work on it & we can issue a call for nominations within the next couple of weeks.

**Comment by divya-mohan0209** [comment]
@haripriya9647 : Any update on this, please? We're looking at wrapping this entire thing up by September.

**Comment by haripriya9647** [comment]
Hello @divya-mohan0209 yes I am working on this, actually, I had some issues with my laptop due to which I couldn't send you an update

**Comment by Affan-7** [comment]
Should I take this?

I am personally waiting for this issue wrangler role to be implemented. Hopefully the time to triage issues would be improved by a lot.

**Comment by haripriya9647** [comment]
Hello @Affan-7 i have already created a pr for this issue.

**Comment by divya-mohan0209** [comment]
The issue wrangler role has been documented and defined. Any follow-up improvements to the role/documentation can be made via subsequent issues and PRs
/close
