### ISSUE TITLE
Kubectl Cheatsheet: ZSH Users may not have installed/enabled shell autocompletion

### ISSUE THREAD

**Issue by Atalanta** [kubernetes/website#41615]
On a new mac with vanilla ZSH config, I found that following the kubectl cheatsheet instructions to set up shell completion did not work:

```
% source <(kubectl completion zsh)
/dev/fd/11:2: command not found: compdef
```

Inspecting the script produced by `kubectl completion zsh` yielded that it tries to run `compdef _kubectl kubectl`.

Out of the box zsh, at least on MacOS, does not have autocompletion enabled, so this needs to be installed/enabled, by editing the zsh config and adding:

`autoload -Uz compinit && compinit `

This may be out of scope for the cheatsheet, as it may be reasonable to assume that users wishing to use kubectl autocompletion already have autocompletion installed, or are using a post-install layer like ohmyzsh, but it might not be a bad idea to add a note in the cheatsheet that says (first ensure you have enabled shell autocompletion.

**Comment by utkarsh-singh1** [comment]
Related Doc - https://kubernetes.io/docs/reference/kubectl/cheatsheet/#zsh

**Comment by utkarsh-singh1** [comment]
Hi @Atalanta, it will be good to add at it as a necessary note for the macOS user, as on linux you have option to enable autocompletion in zsh during initial setup.

**Comment by utkarsh-singh1** [comment]
It has been already mentioned under here ⇾  https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#enable-shell-autocompletion
