### ISSUE TITLE
Improvements needed in reference/kubectl

### ISSUE THREAD

**Issue by Ritikaa96** [kubernetes/website#41617]
**This is a Bug Report**
Improvements needed on the page : https://kubernetes.io/docs/reference/kubectl/

**Problem:**
- On Section https://kubernetes.io/docs/reference/kubectl/#operations
  - Explain and top syntax needs to be corrected.
     -  kubectl explain [--recursive=false] [flags]
     - 	kubectl top [flags] [options]
- Some grammatical improvements needed in [plugins](https://kubernetes.io/docs/reference/kubectl/#examples-creating-and-using-plugins) section.

**Proposed Solution:**
- For operations:
  - kubectl explain TYPE [--recursive=false] [flags] 
  - kubectl top POD/NODE [flags] [options]

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/

**Comment by Ritikaa96** [comment]
I will be glad to contribute to the changes if triage is accepted.

**Comment by Ritikaa96** [comment]
Raised a reference [PR](#41619)

**Comment by nate-double-u** [comment]
I agree we should update those commands, with out adding the parameters kubectl will just ask for them.

I'm not sure of the exact grammatical errors you're referring to though.

/triage accepted
