### ISSUE TITLE
Add example for proxying to pods in “Manually constructing apiserver proxy URLs” section

### ISSUE THREAD

**Issue by jiec-msft** [kubernetes/website#41621]
In [manually-constructing-apiserver-proxy-urls](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls), can we add example for proxy to pods?
For example:

`http://kubernetes_master_address/api/v1/namespaces/namespace_name/services/[http:]podName[:port_name]/proxy`

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/
/language en

**Comment by sftim** [comment]
/retitle Add example for proxying to pods in “Manually constructing apiserver proxy URLs” section

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster-services/#manually-constructing-apiserver-proxy-urls is quite out of date. It will be more valuable to update the existing page than to make the change you're suggesting here @jiec-msft 

If we have capacity to do both things: great!

**Comment by jiec-msft** [comment]
@sftim May I tentatively ask about the update?

**Comment by sftim** [comment]
Hi @jiec-msft 

If your question is similar to “has anyone contributed work towards this issue, so far?” then, in my judgement, nobody has.

**Comment by jiec-msft** [comment]
@sftim Got it, thanks!

**Comment by jiec-msft** [comment]
Hey @sftim, may I ask if there is any update?

**Comment by sftim** [comment]
> Hey @sftim, may I ask if there is any update?

If your question is similar to “has anyone contributed work towards this issue, so far?” then, in my judgement, nobody has.

(Kubernetes contributors are mainly volunteers - although if you'd like to pay someone to do the work, there are companies that would be willing to help).
