### ISSUE TITLE
Add ability to open video in new tab for enhanced multitasking browsing experience

### ISSUE THREAD

**Issue by chamber909** [kubernetes/website#41633]
**This is a Feature Request**

On clicking the the middle button of mouse on watch video , the video should open on another tab.

**Why is this needed**
because any individual can go through the web page and listen the video

**Comment by dipesh-rawat** [comment]
**Page related to issue:** https://kubernetes.io/ (Homepage)
/language en

**Comment by tamilselvan1102** [comment]
it is good to open in a modal popup window, Even though if it is opening in separate tab you can't read content and watch video at the same time

**Comment by BatemanBatman** [comment]
but they can listen and take a overview at the same time!!!

**Comment by dipesh-rawat** [comment]
/retitle Add ability to open video in new tab for enhanced multitasking browsing experience

**Comment by dipesh-rawat** [comment]
IMO opening links in new tabs can cause confusion for users who are used to links opening in the same tab, disrupting their browsing flow and making it difficult to track their navigation history. Moreover, it can negatively impact the performance of devices with limited system resources, as each new tab consumes additional memory and processing power. Also, we should keep in mind the user experience on mobile devices.

**Comment by BatemanBatman** [comment]
hey dipesh its ankush myself as a beginner can you guide me in this project
i wanna contribute

**Comment by sftim** [comment]
/priority awaiting-more-evidence

>  because any individual can go through the web page and listen the video

this is already possible
