### ISSUE TITLE
Inconsistent and redundant word usage in “Ephemeral Volumes” page

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#41640]
**This is a Bug Report**

**Problem:**

The sentence `They are currently also not covered by the storage resource usage limits of a Pod, because **that is something that kubelet can only enforce for storage that it manages itself.**` in the page https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volumes   has several times used same word `that` in single sentence. Which make sentence look differently.

**Proposed Solution:**
Same word cannot be repeated several tims in one sentence.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#csi-ephemeral-volumes

**Comment by niranjandarshann** [comment]
here in this sentence  **that is something that kubelet can only enforce for storage that it manages itself** if we remove **that is something that**  then the sentence look good.

**Comment by dipesh-rawat** [comment]
/rettile Inconsistent and redundant word usage in `Ephemeral Volumes` page

**Comment by dipesh-rawat** [comment]
/retitle Inconsistent and redundant word usage in `Ephemeral Volumes` page

**Comment by dipesh-rawat** [comment]
I think there is room for improvement to make the wording better.

/triage accepted
/priority backlog

**Comment by tengqm** [comment]
This issue is invalid.

> because that is something that kubelet can only enforce for storage that it manages itself.

This first "that" refers to the "storage resource usage limit";
the second "that" leads an attribute clause.
You can treat the second "that" as "which".

**Comment by sftim** [comment]
/retitle Inconsistent and redundant word usage in “Ephemeral Volumes” page

Avoid backticks unless referring to code / methods / etc

**Comment by niranjandarshann** [comment]
in reference of @tengqm  comments there is nothing to fix.
.

**Comment by niranjandarshann** [comment]
I am closing the issue. Marking as Nothing to fix.
/close
