### ISSUE TITLE
Interaktywny samouczek - Tworzenie klastra

### ISSUE THREAD

**Issue by gromaniuk** [kubernetes/website#41641]
Oops! Sorry, we had a problem. Please refresh and try again.
Error - connect ETIMEDOUT 144.76.219.170:8080
We are sorry but we encountered a problem with the connection.
Please refresh and try again.
Thu Jun 15 2023 09:40:10 GMT+0200 (czas środkowoeuropejski letni)
io server disconnect
(reference ID: //wsk8s.europe.katacoda.com/simba10/none/32669633/none/1686814810916)

**Comment by AmarNathChary** [comment]
**page link**: https://kubernetes.io/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
/kind bug

**Comment by AmarNathChary** [comment]
Hi @gromaniuk the katacoda environment for the Kubernetes tutorial has been shut down.
you can see the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

**Comment by gromaniuk** [comment]
Thanks for info
