### ISSUE TITLE
[ja] update outdated links in content/ja/docs/reference/using-api/_index.md

### ISSUE THREAD

**Issue by morix1500** [kubernetes/website#41674]
**This is a Feature Request**

**What would you like to be added**

We need to update some links in `content/ja/docs/reference/using-api/_index.md` because these links are broken.

## 1. API groups
https://github.com/kubernetes/website/blob/main/content/ja/docs/reference/using-api/_index.md?plain=1#L78

True) https://git.k8s.io/design-proposals-archive/api-machinery/api-group.md
False)  https://git.k8s.io/community/contributors/design-proposals/api-machinery/api-group.md

## 2. aggregator
https://github.com/kubernetes/website/blob/main/content/ja/docs/reference/using-api/_index.md?plain=1#L115

True) https://git.k8s.io/design-proposals-archive/api-machinery/aggregated-api-servers.md
False) https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/aggregated-api-servers.md

**Why is this needed**
These links are broken.

**Comments**

/language ja
/assign

**Comment by t-inu** [comment]
@morix1500
About aggregator

> True) https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/aggregated-api-servers.md

-> https://git.k8s.io/design-proposals-archive/api-machinery/aggregated-api-servers.md

https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/aggregated-api-servers.md is certainly correct, but we would like to match the English page first.
You already did so in PR #41675.

**Comment by morix1500** [comment]
@t-inu 
Thank you for your advice!
The URL listed in the Issue was incorrect and has been corrected.
As you said, PR already uses this URL.
