### ISSUE TITLE
[ja] update Japanese translation /docs/contribute/new-content/_index

### ISSUE THREAD

**Issue by kmuto** [kubernetes/website#41670]
**This is a Feature Request**

**What would you like to be added**

- Update Japanese translation of https://kubernetes.io/ja/docs/contribute/new-content/
- Remove https://kubernetes.io/ja/docs/contribute/new-content/overview/ (this page is merged into new-content index in English page)

**Why is this needed**
outdated page

**Comments**

/language ja
/assign

**Comment by pranav-pandey0804** [comment]
sig/docs
