### ISSUE TITLE
How can we document port requirements for pod network plugins?

### ISSUE THREAD

**Issue by jberkus** [kubernetes/website#4168]
Per PR #4111 we have  a problem in offering documentation around required port security for network plugins.  The problem has two parts:

1. We want to link to plugin docs instead of maintaining our own list of required ports, because our list will become out-of-date/wrong.
2. However, plugins either have no explicit documentation at all about what ports need to be open, or have that documentation buried in an obscure sub-page which is mostly about something else (e.g. http://docs.projectcalico.org/v2.3/reference/public-cloud/aws)

As I see it, (2) trumps (1); if there's nothing to link to, we're going to need to maintain our own list of required default ports.  Other ideas?

**Comment by jberkus** [comment]
cc @luxas @mikedanese @jamiehannaford

**Comment by caseydavenport** [comment]
I've raised https://github.com/projectcalico/calico/issues/868 to adjust the Calico docs so that we can more easily link to them from the k8s docs.

**Comment by jberkus** [comment]
New link for Weave: https://www.weave.works/docs/net/latest/faq/#ports

**Comment by luxas** [comment]
cc @aaronlevy @tomdee for Flannel

**Comment by aaronlevy** [comment]
The flannel backends doc list default ports, if that might be sufficient: https://github.com/coreos/flannel/blob/master/Documentation/backends.md

**Comment by jberkus** [comment]
OK, seems like we have enough port information to link to popular pod networks.

**Comment by jberkus** [comment]
yah, this is still a TODO for me.

**Comment by caseydavenport** [comment]
Quick update on this - Calico requirements have been consolidated here: https://docs.projectcalico.org/v3.1/getting-started/kubernetes/requirements

**Comment by luxas** [comment]
ping @jberkus
