### ISSUE TITLE
[es] localize content/en/docs/concepts/storage/projected-volumes.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#41701]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/concepts/storage/projected-volumes.md` to Spanish

**Why is this needed**

**Comments**
/triage accepted
/kind feature
/language es
/sig docs

**Comment by edithturn** [comment]
Hi Rodolfo, I will take it! 🕺🏼

**Comment by electrocucaracha** [comment]
@edithturn algún avance al respecto?

**Comment by edithturn** [comment]
@electrocucaracha, disculpa.
Lo terminaré hoy, gracias por recordarmenlo Victor. 🙂
