### ISSUE TITLE
Improvement for k8s.io/docs/tasks/run-application/configure-pdb/

### ISSUE THREAD

**Issue by kebab-mai-haddi** [kubernetes/website#41703]
Add an example please, of a helm file or a normal yaml file.

**Comment by T-Lakshmi** [comment]
**Page:** https://kubernetes.io/docs/tasks/run-application/configure-pdb/
/sig docs
/language en

**Comment by T-Lakshmi** [comment]
Hi @kebab-mai-haddi,
I could see there is already yaml files are present for PodDisruptionBudget under [specifying-a-poddisruptionbudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget) secton. 

Please let us know what more details u would like to improve here.

**Comment by T-Lakshmi** [comment]
we can improve the page under [Create the PDB object](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#create-the-pdb-object) section.

`kubectl apply -f mypdb.yaml`
Here **mypdb.yaml** is random file name, instead we can provide exact path of the file mentioned in the example of previous section.
that will avoid readers confusion.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

I could believe that it's useful to add an example PDB manifest into a different page: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
