### ISSUE TITLE
[zh-cn] The Bold isn't effect in "审计（Auditing）"

### ISSUE THREAD

**Issue by kevin1689-cloud** [kubernetes/website#41704]
**This is a Bug Report**

**Problem:**
The Bold isn't effect in "审计（Auditing）", as shown below:
![image](https://github.com/kubernetes/website/assets/69347704/c7b02bea-6a17-4d2c-9c97-e6c3972de4d9)

**Proposed Solution:**
Modify the format to make the bold effective.

**Page to Update:**
https://kubernetes.io/zh-cn/docs/tasks/debug/debug-cluster/audit/

**Comment by kevin1689-cloud** [comment]
I think I can fix this.
/assign

**Comment by mengjiao-liu** [comment]
Thanks for the catch! You can fix it if you want.

**Comment by kevin1689-cloud** [comment]
> @kevin1689-cloud Thanks for the catch! You can fix it if you want.

Sure, let me fix it.
