### ISSUE TITLE
The Example of pod in projected volume  is getting in CrashLoopBackoff State

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#41728]
The yaml in the [Example of Projected volume ](https://kubernetes.io/docs/concepts/storage/projected-volumes/#example-configuration-secrets-nondefault-permission-mode) needs to be updated; as the pods is always getting in CrashLoop Backoff state instead of running state.  

**Suggestion**
Problem is not with the volumes, but with the image, we are using, busy box 1.28 as the image, but as there is no process that keeps the container running, the pod is completing and getting in CrashLoopBackoff state. 
So in yaml to run the pods  we need to change.
- name: container-test
    image: busy box
    command: ["sleep", "60"]
**Related Page :**
https://kubernetes.io/docs/concepts/storage/projected-volumes/#example-configuration-secrets-nondefault-permission-mode

So we can change the yaml file with the command labels to put pod in running state. It will be helpful for all.

**Comment by niranjandarshann** [comment]
As per https://github.com/kubernetes/kubernetes/issues/118526

**Comment by killshotrevival** [comment]
Hey @niranjandarshann , I have already raised an PR for the same, 
https://github.com/kubernetes/website/pull/41715

Waiting for the approval 😃

**Comment by sftim** [comment]
How about we add a comment to the manifest to:
- make it clear that the manifest only works when the two Secrets are set up correctly
- use a different container image that is much more obviously an example, not a real image

?

**Comment by niranjandarshann** [comment]
> 

@sftim  observing on these points its  true that the example given here in the pod use image busybox which get in crashloopbackoff state until we doesn't give command to perform like (command:["sleep","3600"] ) but with some other image like nginx, and my static image pod is in running state without the command to perform.

As i tried with: (Result may vary with other images as well)
 image: busybox:1.35 and image : busybox. whose Pod getting in CrashLoopBackoff state without command labels in yaml file.
whereas
using 
image: nginx and image:niranjandarshan/bihartour , The pod is getting in running state without Command labels in yaml file.
 
Yes it is obvious that the Manifest will run only when the two secrets are set up correctly.

So in given example i think we should either remove the busybox image or use the command label ( command: ["sleep","3600"]). To Set the Pod used in example in running state.

**Comment by niranjandarshann** [comment]
closing this issue marking as completed 
/close
