### ISSUE TITLE
[ko] Translate reference/labels-annotations-taints/audit-annotations in Korean

### ISSUE THREAD

**Issue by pgs1004** [kubernetes/website#41726]
This is a Feature Request

What would you like to be added

Translate reference/labels-annotations-taints/audit-annotations

Why is this needed
No translation with reference/labels-annotations-taints/audit-annotations in Korean

Comments

Page to Update:
https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/

**Comment by jihoon-seo** [comment]
@pgs1004 관심과 기여에 감사드립니다~~
작업 시, 작업 브랜치 생성도 `dev-1.27-ko.1` 로부터 하시고
PR 오픈 시 타겟 브랜치도 `dev-1.27-ko.1` 로 설정하시면 되겠습니다~~
