### ISSUE TITLE
Init container default timeout behaviour not documented

### ISSUE THREAD

**Issue by plumdog** [kubernetes/website#41734]
Improvement for https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/pods/init-containers.md

The docs don't say what happens if my init container runs for a very long time.

This SO answer https://stackoverflow.com/questions/63907715/kubernetes-initcontainer-that-takes-more-than-5-minutes-to-finish-never-ends-a suggests the default is 5 minutes, as that's the default for `--pod-eviction-timeout`, though that doesn't match what I'm seeing (I'm using EKS running 1.24, and I believe EKS uses default values for things like this, see https://github.com/aws/containers-roadmap/issues/159. That issue is also relevant, because I can't change this value in EKS).

What I'm seeing is that an init container can run for longer (at least 10 minutes) and isn't evicted. What behaviour does Kubernetes guarantee? Does it guarantee up to `--pod-eviction-timeout`, but then anything after that is a maybe?

For my use case, I have some - potentially very slow - database operations that need to complete during deployment before the new version of the application starts (but the old version of the application can tolerate either the old or the new state of the database) and I want to know how long an init container can give me to complete the operations.

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
/language en

**Comment by sftim** [comment]
There's no timeout that I know of for init containers. A while ago we - The Scale Factory, where I work - helped a SaaS security vendor run some Pods that needed to load a big model into memory. An init container worked well for that, and it didn't really matter how long the process took.

We could document that the Pod is healthy if it has a healthy init container that is running, and so there is no timeout on the Pod initialization process. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/ is the best place to clarify this detail; https://kubernetes.io/docs/concepts/workloads/pods/init-containers/ should direct people there.

Related, I _think_ (didn't check) that there is also no real limit on how long a Pod can be starting up (`startupProbe` failing, failure count not reached). 

For example, you can set the probe to check every 5 seconds for 24 hours. See https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
