### ISSUE TITLE
Unclear and redundant statement regarding environment variable definition prior to Deployment creation

### ISSUE THREAD

**Issue by ssrinivasn-edu** [kubernetes/website#41735]
> Before creating a Deployment define an environment variable for a container.

What is the purpose of this statement here. We are able to create a Deployment from sample provided below it without executing above statemet.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Unclear and redundant statement regarding environment variable definition prior to Deployment creation

**Comment by dipesh-rawat** [comment]
It appears that the statement in question was included as a solution to address issue #40735. To eliminate confusion and improve clarity, one possible option could be to move the link to the "What's Next" [section](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#what-s-next) at the end, thereby reducing confusion with the existing content on the page. I will allow others to share their thoughts on this matter.

**Comment by ssrinivasn-edu** [comment]
Thanks Dipesh. Appreciate it.

Regards

Shridhar

**Comment by Rohan-Dah** [comment]
Hi.. I'd like to work on the issue.. Can you please elaborate on what could be the fix?

**Comment by sftim** [comment]
I recommend removing
> Before creating a Deployment define an [environment variable](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container) for a container.

from the [page](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). That's a small fix that doesn't need us to work on the rest of https://github.com/kubernetes/website/issues/12082

/triage accepted
/language en
/priority backlog

**Comment by vaibhav2107** [comment]
As PR #42155 fixes the issue, so we can close it
