### ISSUE TITLE
[de] Obsolete online interactive tutorial in the "Using Minikube to Create a Cluster" page

### ISSUE THREAD

**Issue by sunnyrider** [kubernetes/website#41731]
Can not type into terminal

**Comment by sunnyrider** [comment]
I have:
Error - connect ECONNREFUSED 94.130.9.5:8080
Please refresh an try again

**Comment by dipesh-rawat** [comment]
@sunnyrider Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.

**Comment by sunnyrider** [comment]
ok, thank you for response
