### ISSUE TITLE
[ja] Fix for Release Notes under Getting Started

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41742]
**This is a Feature Request**

**What would you like to be added**

Japanese Localization fix.
- Remove the Release Notes from the side menu
- add redirect for the URL https://kubernetes.io/ja/docs/setup/release/ to https://kubernetes.io/releases/

**Why is this needed**
Consistency with the English documentation for the following points:

- Getting Started > Release Notes is no longer in the submenus english version. 
- Directly putting  URL https://kubernetes.io/docs/setup/release/ results to a redirect to https://kubernetes.io/releases/

**Comments**
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.

**Comment by Okabe-Junya** [comment]
This issue may be related to #44621

**Comment by Okabe-Junya** [comment]
/cc @atoato88 

I seem this issue is resolved by #44621. If you think so too, can you close this issue?

**Comment by atoato88** [comment]
/close

Thank you for informing me.
