### ISSUE TITLE
Add example for configuring audit webhook in "Auditing" page

### ISSUE THREAD

**Issue by MMquant** [kubernetes/website#41740]
Add audit webhook configurarion example.

**Comment by niranjandarshann** [comment]
ref link: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/
/language en
/sig docs

**Comment by niranjandarshann** [comment]
@MMquant  I think this link https://kubernetes.io/docs/reference/access-authn-authz/webhook/#configuration-file-format  is helpful.

**Comment by MMquant** [comment]
Indeed, that link contains proper webhook configuration. Maybe it would be nice to have the link in the "What's next" section in https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/

**Comment by niranjandarshann** [comment]
> Indeed, that link contains proper webhook configuration. Maybe it would be nice to have the link in the "What's next" section in https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/

@MMquant  it will be good to have the link whether in the same paragraph or in the what's  next  section. It would be beneficial for the new reader.

**Comment by dipesh-rawat** [comment]
/retitle Add example for configuring audit webhook in "Auditing" page

**Comment by sftim** [comment]
I think ideally we'd move the example webhook out of the reference page and into the task page.

**Comment by rukundob451** [comment]
@sftim and @MMquant are we moving th example webhook into the task page as suggested?

**Comment by MMquant** [comment]
@rukundob451 Yes
