### ISSUE TITLE
[ja] Translate tasks/run-application/horizontal-pod-autoscale into Japanese

### ISSUE THREAD

**Issue by morix1500** [kubernetes/website#41756]
**This is a Feature Request**

**What would you like to be added**

Translate [tasks/run-application/horizontal-pod-autoscale](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) into Japanese

**Why is this needed**
This page has not been translated.

**Comments**

/language ja
/assign

**Comment by furon-kuina** [comment]
Is someone working on this issue right now? If not, I would like to take it on. 

(This is my first time contributing to k8s, so let me know if there's any misconduct)

**Comment by morix1500** [comment]
@furon-kuina 
Thank you for your interest in this Issue!
I am currently working on this issue.
https://github.com/kubernetes/website/pull/41757

**Comment by furon-kuina** [comment]
I overlooked the PR. Thanks!
