### ISSUE TITLE
 addition to the common kubectl subcommands 

### ISSUE THREAD

**Issue by Nitishupkr** [kubernetes/website#41752]
![Screenshot 2023-06-25 023935](https://github.com/kubernetes/website/assets/95420063/ee54e99f-b016-43f9-ba5d-396504bffe72)
I will rise PR for this

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/
/language en

**Comment by dipesh-rawat** [comment]
@Nitishupkr  The current subcommands list on the [page](https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/#:~:text=the%20following%20kubectl-,subcommands,-%3A) appears to be quite comprehensive. Can you please share additional details about the specific kubectl subcommands you suggest including in this list? What are the reasons for adding them?

**Comment by Nitishupkr** [comment]
kubectl rollout
kubectl create
kubectl delete
kubectl scale ....
These are another subcommands  used for most common operation .  subcommands available in kubectl for troubleshooting and managing Kubernetes resources @dipesh-rawat

**Comment by utkarsh-singh1** [comment]
Hi @Nitishupkr, As many of these commands are there for just the introduction to the k8s, Also as you can read the title these commands are for troubleshooting with kubectl, means we only need these commands to view the status of k8s resources  (Ex. pods, svc, replicaset etc.)  if they are running fine or not.

**Comment by utkarsh-singh1** [comment]
> kubectl rollout kubectl create kubectl delete kubectl apply kubectl scale .... These are another subcommands used for most common operation . subcommands available in kubectl for troubleshooting and managing Kubernetes resources @dipesh-rawat

As you mentioned these commands are already mentioned here - https://kubernetes.io/docs/reference/kubectl/cheatsheet/

**Comment by utkarsh-singh1** [comment]
You can find detailed info and additional usage there.

**Comment by Nitishupkr** [comment]
@utkarsh-singh1 Hey I agreed with your point but  there is written ' The most common operations can be done with the following kubectl subcommands:'

**Comment by utkarsh-singh1** [comment]
Hi @Nitishupkr, Actually the subcommands written here are for troubleshooting with kubectl, In troubleshooting you need information about the object, you need info for, all of these commands written here are for getting info about, pods, nodes, deployments etc.

**Comment by utkarsh-singh1** [comment]
You can mention a section where you can mention, creating k8s-objects/resources with kubectl, where you can mention subcommands like, 

Ex.
```bash
kubectl create resource
kubectl apply resource 
```
etc.

**Comment by Nitishupkr** [comment]
@utkarsh-singh1 ok

**Comment by Nitishupkr** [comment]
@dipesh-rawat do you have any idea how can i put the common commands in this.

**Comment by sftim** [comment]
I actually don't think there's anything to fix.

I would prefer any effort to go into, eg, https://github.com/kubernetes/website/issues/25943

Once we make progress there, it's easier for other pages to link to the improved, combined kubectl docs.

**Comment by utkarsh-singh1** [comment]
This issue is not needed to open anymore, as @sftim and @dipesh-rawat already mentioned that changes are not required in the tutorial-documentation.

**Comment by aj11anuj** [comment]
Fix is not required
/close not-planned
