### ISSUE TITLE
[ja] Windows in Kubernetes redundancy in Getting Started > Production Environment

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41779]
**This is a Feature Request**

**What would you like to be added**
The following are proposed to be fixed in this issue:
* Firstly, translate the page https://kubernetes.io/docs/concepts/windows/ to https://kubernetes.io/ja/docs/setup/production-environment/windows/
* Secondly, update https://kubernetes.io/ja/docs/setup/production-environment/windows/intro-windows-in-kubernetes/ to match the contents of https://kubernetes.io/docs/concepts/windows/intro/ . Also update https://kubernetes.io/ja/docs/setup/production-environment/windows/user-guide-windows-containers/ to match https://kubernetes.io/docs/concepts/windows/user-guide/
* And finally, moving the tree of pages found in https://kubernetes.io/ja/docs/setup/production-environment/windows/ to replace the English only page of `Kubernetes in Windows"<https://kubernetes.io/docs/concepts/windows/>

**Why is this needed**
* To remove the redundancy of explaining Windows in Kubernetes under Getting Started and Concepts
* To be consistent with the EN version

**Comments**
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.

**Comment by Okabe-Junya** [comment]
@atoato88 

ditto. ref. https://github.com/kubernetes/website/issues/41869#issuecomment-1919437833

> It appears that no one is working on this issue. Additionally, this issue involves translating two pages. I think it would be better to split it into two separate issues.
> 
> WDYT?

Meaning, I want to close this issue and create some issues.  I think it's better to create one issue for the translation of one page (except in some special cases).

**Comment by Okabe-Junya** [comment]
/close 

ref https://github.com/kubernetes/website/issues/41779#issuecomment-1938851339
