### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by zehan-mt** [kubernetes/website#41781]
when I applied the mysql statefulset yaml, it raised **ERROR 1130 (HY000): Host '127.0.0.1' is not allowed to connect to this MySQL server**

**Comment by utkarsh-singh1** [comment]
/remove sig-cli
/sig docs
Hi @zehan-mt, Can you post the command after which you are getting the error.

**Comment by zehan-mt** [comment]
> /remove sig cli /sig docs Hi @zehan-mt, Can you post the command after which you are getting the error.

I just followed the docs. The commands orderly are:

1. kubectl apply -f https://k8s.io/examples/application/mysql/mysql-configmap.yaml
2. kubectl apply -f https://k8s.io/examples/application/mysql/mysql-services.yaml
3. kubectl apply -f https://k8s.io/examples/application/mysql/mysql-statefulset.yaml

I tried to enter the "mysql" container and execute "mysql -h 127.0.0.1 -e 'select 1'", thereafter it alse raised the error.
Then I removed "-h 127.0.0.1" and it succeeded. I found values in "host" column of table "user" in database "mysql" did not contain "127.0.0.1".

**Comment by sftim** [comment]
Is this _definitely_ a support request and not a bug in the page? @utkarsh-singh1 we only add that label when we're confident.

**Comment by utkarsh-singh1** [comment]
I apologize for the wrong tag @sftim, I should have tagged for more information on the issue first.

**Comment by niranjandarshann** [comment]
This issue is inactive from the long time. You may reopen this issue if you think there should be required changes in the docs which will help reader so feel free to reopen it.

**Comment by niranjandarshann** [comment]
closing this issue 
/close
