### ISSUE TITLE
Add CEL Playground link in documentation

### ISSUE THREAD

**Issue by matheusfm** [kubernetes/website#41788]
Hello there, I would like to suggest adding a link to the CEL Playground in the Kubernetes documentation.

CEL (Common Expression Language) is used in Kubernetes APIs, such as the `ValidatingAdmissionPolicy`, and the CEL Playground can help users easily test expressions.

The playground also includes a set of examples and the [Kubernetes libraries for CEL](https://kubernetes.io/docs/reference/using-api/cel/#kubernetes-cel-libraries).

I believe the link would be useful on the following pages:
- https://kubernetes.io/docs/reference/using-api/cel/
- https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/

The CEL Playground is available at https://playcel.undistro.io/ and the source code can be found at https://github.com/undistro/cel-playground.

I also invite you to test and contribute to the project.

Thank you.

**Comment by sftim** [comment]
If we add a link, I would add it to:
- https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
- https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/ 

(and I wouldn't add it to the reference page https://kubernetes.io/docs/reference/using-api/cel/; instead, we can have https://kubernetes.io/docs/reference/using-api/cel/ link to the three pages I listed above)

**Comment by rukundob451** [comment]
@

> If we add a link, I would add it to:
> 
> * https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/
> * https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
> * https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/
> 
> (and I wouldn't add it to the reference page https://kubernetes.io/docs/reference/using-api/cel/; instead, we can have https://kubernetes.io/docs/reference/using-api/cel/ link to the three pages I listed above)

Hey @sftim, which particular points on these links would you want the CEL playground. I will be glad for more clarification on this?

**Comment by matheusfm** [comment]
IMHO, a mention similar to the mention of [crontab.guru](https://crontab.guru/) on the [`CronJob` page](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) would help:

> To generate CronJob schedule expressions, you can also use web tools like [crontab.guru](https://crontab.guru/).

but saying that users can quickly test CEL expressions in the playground.

**Comment by matheusfm** [comment]
Hi @sftim, 
I've opened a PR (#42968) with some suggestions for adding the CEL Playground link.

Please take a look and let me know your thoughts.

Inviting @jpbetz to share their thoughts as well.

**Comment by jpbetz** [comment]
I'm supportive of this. It's a wonderful tool and the community will benefit from being more aware of it.
