### ISSUE TITLE
Unclear documentation on `NamespaceDefaultLabelName` feature gate

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#41790]
It looks like the feature gate "NamespaceDefaultLabelName" has been removed as described on this page:
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

But it's noted on this page that it can be enabled:
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#automatic-labelling

Maybe that the "Namespaces" page needs to be updated.

**Comment by sftim** [comment]
/retitle Unclear documentation on `NamespaceDefaultLabelName` feature gate

The documentation is not wrong; however, we can clean up 
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/ to avoid mentioning the feature gate at all (we'd keep the feature-state shortcode).

/priority backlog
/help
/triage accepted
