### ISSUE TITLE
[ko] Translate the Reference 'Service Level Indicator Metrics' into Korean

### ISSUE THREAD

**Issue by tonyhan18** [kubernetes/website#41795]
**This is a Feature Request**

Translate "/content/en/docs/reference/instrumentation/metrics.md"
to "/content/ko/docs/reference/instrumentation/metrics.md"

**What would you like to be added**

Translating

**Why is this needed**

Not translated into Korean yet. I think beacuse it's new feature in k8s.

**Comments**

ok after i got a job and make my time.
i'm gonna translate lots of not translated en docs to korean.
it's about 1-2 weeks hard job

```[tasklist]
### Tasks
```

**Comment by AmarNathChary** [comment]
@tonyhan18 are you working on this issue.

**Comment by AmarNathChary** [comment]
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten.
`Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close.`

**Comment by AmarNathChary** [comment]
closing the issue please feel free to reopen it if you are working on it
