### ISSUE TITLE
[ja] add translation for Getting Started > Production Environment index info

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41792]
**This is a Feature Request**

**What would you like to be added**
Add a translation of https://kubernetes.io/docs/setup/production-environment/ to https://kubernetes.io/ja/docs/setup/production-environment/

**Why is this needed**
The EN version contains a detailed explanation for production environment, considerations, setup, etc.
This will add consistency of the ja documentation with en..

**Comments**
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.
