### ISSUE TITLE
Issue with kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

### ISSUE THREAD

**Issue by Poldovico** [kubernetes/website#41803]
**This is a Bug Report**

**Problem:**
Can not run this command:
curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/

it returns this: Error trying to reach service: 'dial tcp 172.17.0.6:80: connect: connection refused'

**Proposed Solution:**
Implement any of the solutions suggested in #18079

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

**Additional Information:** This bug was already reported in #18079 and went stale while the interactive tutorial existed. With the demise of the interactive option, this bug will now affect all users, which makes it worth fixing IMHO.

**Comment by AmarNathChary** [comment]
**Page**: https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/
/language en
