### ISSUE TITLE
[feature request] Custom markdown syntax for "variables" in code snippets

### ISSUE THREAD

**Issue by abiogenesis-now** [kubernetes/website#4180]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

In code snippets it can be unclear whether a value is part of the "actual code", or an example value that the reader should swap out.

For instance, `dapi-test-pod` in:

<img width="1040" alt="screen shot 2017-06-23 at 4 24 26 pm" src="https://user-images.githubusercontent.com/25401650/27503395-7fe9fd68-5830-11e7-90bd-56648c5df063.png">

While the reader can figure this out by reading the instructions carefully, by and large we should assume that there's a lot of skimming going on. 😝 There are probably quite a few cases where users directly copy-and-paste lines of code without altering them.

**Proposed Solution:**

DigitalOcean highlights "variables" in code snippets (see https://www.digitalocean.com/community/tutorials/digitalocean-s-writing-guidelines#variables). It looks like the following:

<img width="1135" alt="screen shot 2017-06-23 at 3 43 10 pm" src="https://user-images.githubusercontent.com/25401650/27503335-0c40dcec-5830-11e7-9e02-36b4695ca5a0.png">

We could likewise implement custom markdown syntax to enable something like this.

**Page to Update:**

Generally the whole site.

**Comment by abiogenesis-now** [comment]
cc @chenopis (I don't think I have the ability to assign things?)
Also, would definitely be interested into working on this myself!

**Comment by chenopis** [comment]
Try "/assign @chenopis" in a comment.

**Comment by Bradamant3** [comment]
This is a good idea (and one common solution to the problem). BUT ... we also already have this recommendation in the style guide: https://kubernetes.io/docs/home/contribute/style-guide/#use-angle-brackets-for-placeholders. (TL;DR: another common solution) My guess is that the issue exists because there's non-conformance to the doc style guide all over the place. How much can we automate fixing the markup for what's already in place?

**Comment by abiogenesis-now** [comment]
on hold, but I'll tag this with team/heptio anyways

**Comment by abiogenesis-now** [comment]
Hmm...not on the immediate roadmap, but still a nice to have. I'll close this issue for now and track it in my own todos, barring any objections.
