### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/high-availability/

### ISSUE THREAD

**Issue by area51b** [kubernetes/website#41811]
Weave Net has announced the end of service for Weave Cloud. As an impact, the old weave net installation link mentioned in the documentation won’t work anymore: -

**kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"**

Instead of that, update the document with below latest link to install the weave net:

**kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml**

Reference links: -

https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#-installation

https://github.com/weaveworks/weave/releases

**Comment by pranav-pandey0804** [comment]
Hi @area51b , thanks for your contribution!
[Here](https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy/#install-the-weave-net-addon) are the steps for installing weave net and it has a link that redirects to on this [page](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/) which has the correct link that you mentioned.
Are you talking about any other kuberentes documentation, if so then please mention the related page.
