### ISSUE TITLE
Signpost from “Hello, Minikube” back to Kubernetes Basics tutorials

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41837]
### This is a Feature Request

**What would you like to be added**

Link to https://k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/ at the end of https://k8s.io/docs/tutorials/hello-minikube/

*Make this link particularly prominent.* It should come before the other three links in the What's Next section of the page.

**Why is this needed**

https://k8s.io/docs/tutorials/kubernetes-basics/ directs readers to visit https://k8s.io/docs/tutorials/hello-minikube/

However, people who get to the end of https://k8s.io/docs/tutorials/hello-minikube/ do not see any link back to https://k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comments**
This is a consequence of the Katacoda shutdown - https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/ - and our response to that shutdown.

/language en
/kind feature

**Comment by dipesh-rawat** [comment]
/assign
Proposed fix in #41842

**Comment by sftim** [comment]
/good-first-issue
(retrospectively)
