### ISSUE TITLE
Stale details in "Learn Kubernetes Basics" page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41836]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/ has a banner about the Katacoda shutdown. However, the tutorials that https://kubernetes.io/docs/tutorials/kubernetes-basics/ links to have been updated for local use.

**Proposed Solution:**
Remove the notice.
_Also, reword the paragraphs that refer to the Katacoda tutorial in the rest of that text._

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/

**Additional Information:**
/language en
/priority important-longterm

**Comment by dipesh-rawat** [comment]
Additionally, whether it is within this issue or a separate new issue, we should consider removing/rewording the paragraph referring the Katacoda tutorial in [opening section](https://kubernetes.io/docs/tutorials/kubernetes-basics/#:~:text=The%20tutorials%20use%20Katacoda%20to%20run%20a%20virtual%20terminal%20in%20your%20web%20browser%20that%20runs%20Minikube%2C%20a%20small%2Dscale%20local%20deployment%20of%20Kubernetes%20that%20can%20run%20anywhere.%20There%27s%20no%20need%20to%20install%20any%20software%20or%20configure%20anything%3B%20each%20interactive%20tutorial%20runs%20directly%20out%20of%20your%20web%20browser%20itself.)  of this [page](https://kubernetes.io/docs/tutorials/kubernetes-basics/).

> The tutorials use Katacoda to run a virtual terminal ..
..
..
each interactive tutorial runs directly out of your web browser itself.

**Comment by Utopiah** [comment]
Is there any alternative planned? I'm actively looking for an interactive tutorial, on any platform, and landed on https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

I understand it has been stopped but what is currently the best way to learn interactively about Kubernetes?
