### ISSUE TITLE
Mermaid diagrams not working reliably in Pod Topology Spread Constraints topic

### ISSUE THREAD

**Issue by MMquant** [kubernetes/website#41848]
Syntax error in graphs will not render graphs in https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
![image](https://github.com/kubernetes/website/assets/20891620/150e2e71-567b-4882-8973-e91d7453f120)

**Comment by AmarNathChary** [comment]
It looks similar to issue #37357

**Comment by sftim** [comment]
/retitle Mermaid diagrams not working reliably in Pod Topology Spread Constraints topic

**Comment by sftim** [comment]
Also duplicates https://github.com/kubernetes/website/issues/31960

**Comment by sftim** [comment]
/close

Let's track via the original issue
