### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by GeoffreyStemys** [kubernetes/website#41849]
this page explains it better than the official doc:
https://medium.com/swlh/quick-fix-mounting-a-configmap-to-an-existing-volume-in-kubernetes-using-rancher-d01c472a10ad

**Comment by tamilselvan1102** [comment]
Doc page: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

**Comment by tamilselvan1102** [comment]
[configure-pod-configmap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) page have more detailed information than page you referred. You can point out the section that required more information.
