### ISSUE TITLE
[Umbrella] Improve the docs site by simplifying it.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#41859]
**This is a Feature Request**

**What would you like to be added**

Well ... nothing to be added.

We may want to remove some useless gadgets or decorators or components from the screen.

**Why is this needed**

I'm calling this an umbrella issue because ...

<img width="1216" alt="Screenshot" src="https://github.com/kubernetes/website/assets/5094756/1d11a523-4408-4b2a-9a32-8843ebbbc98a">

**Comments**

I'm not enumerating the other "warnings", "notes" we keep adding to a page, but we may want to be careful when adding new components to pages. We may instead strive to simplify the layouts.

**Comment by a-mccarthy** [comment]
Adding some context on the feedback form, we collect some data, but it's not reliable/useable. There's an open issue about this, https://github.com/kubernetes/website/issues/37201. To my knowledge it's not being looked at all.
