### ISSUE TITLE
[ja] Missing link for Best Practices > Certificates

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41866]
**This is a Bug Report**

**Problem:**
In the japanese version of https://kubernetes.io/docs/setup/best-practices/certificates/  list of operations requiring PKI, 
the japanese version of the item "Kubelet [server certificates](https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/#client-and-serving-certificates) for the API server to talk to the kubelets" has no link in server certificates.

**Proposed Solution:**
Add link at  "[サーバー認証書](https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/#client-and-serving-certificates)" in the japanese version of the document like the english version.

**Page to Update:**
https://kubernetes.io/ja/docs/setup/best-practices/certificates/

Additional Information:
/language ja
/assign

**Comment by TheDedster** [comment]
triage/accepted

**Comment by TheDedster** [comment]
@tuibeovince Is the issue solved can i work on it ?

**Comment by atoato88** [comment]
@TheDedster 
How is the progress of this issue?

/unassign @tuibeovince
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.

**Comment by t-inu** [comment]
/unassign @TheDedster 
ref: https://github.com/kubernetes/website/pull/41930

**Comment by Okabe-Junya** [comment]
It appears that no one is working on this issue. I would like to work it. Also, it seems that this page has not been kept up to date with the upstream.

I would like to create another issue to update this page and work on both issues together.
