### ISSUE TITLE
[ja] Missing subsection of the tranlated version of  Troubleshooting Clusters

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41868]
**This is a Bug Report**

**Problem:**
In the japanese version of https://kubernetes.io/docs/tasks/debug/debug-cluster/, the following parts are missing:
* Example: debugging a down/unreachable node
* What's next

**Proposed Solution:**
* Add the example with the same script but with translated descriptions
* Add the japanese version of the "What's next" list.

**Page to Update:**
https://kubernetes.io/ja/docs/tasks/debug/debug-cluster/

Additional Information:
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.
