### ISSUE TITLE
[ja] Add page translation for Operating Etcd Clusters for Kubernetes

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41861]
**This is a Feature Request**

**What would you like to be added**
JA translation of"Tasks > Administer A Cluster > Operating etcd clusters for Kubernetes" 

**Why is this needed**
The JA documentation only links to the English version of the page

**Comments**
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.
