### ISSUE TITLE
Adding some expression to  indicate controller manager runs **many** controllers in document explicitly

### ISSUE THREAD

**Issue by FOWind** [kubernetes/website#41864]
**This is a Feature Request**

**What would you like to be added**

I think adding some expressions to  indicate controller manager runs **many** controllers explicitly, moreover indicate the actual amount of controllers in document page https://kubernetes.io/docs/concepts/overview/components/#kube-controller-manager is useful  for beginner.

**Why is this needed**

When I communicated with some k8s beginners, they think controller-manager only run 4 controllers refered to the document. Actually controller manager has run nearly 40 controllers currently, and the amount will increase in the future in predict.

**Comments**

**Comment by AmarNathChary** [comment]
@FOWind Its difficult to mention all the controllers in the document as some examples of the controllers that run within the kube-controller-manager process. There are additional controllers for different aspects of the Kubernetes cluster.

**Comment by AmarNathChary** [comment]
/language en
Rather we can say there are more controllers that run within the kube-controller-manager. With few more examples

**Comment by sftim** [comment]
/triage accepted
/priority backlog

Don't add more examples. Instead, reword to make it clearer that the 4 examples listed are selected from a much larger set.

**Comment by FOWind** [comment]
Expressions in https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/#synopsis is puzzled too

> Examples of controllers that ship with Kubernetes today are the replication controller, endpoints controller, namespace controller, and serviceaccounts controller.

**Comment by sftim** [comment]
There I would make changes. Swap:
- remove “replication controller” out, using “statefulset controller” as its replacement
- remove “endpoints controller” out, using “endpointslice controller” as its replacement

**Comment by hasanrashid** [comment]
I'd like to work on this

**Comment by AmarNathChary** [comment]
Hey @46kumarshivam  
@hasanrashid has assigned this issue already. You can find another issue that you can work on.
