### ISSUE TITLE
[ja] Localization inconsistencies of contents of "Running in multiple zones" 

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41865]
**This is a Bug Report**

**Problem:**
Inconsitencies of the contents of: 
  * EN: Getting started > Best practices > [Running in multiple zones](https://kubernetes.io/docs/setup/best-practices/multiple-zones/) 
  * JA: はじめに > ベストプラクティス > [複数のゾーンで動かす](https://kubernetes.io/ja/docs/setup/best-practices/multiple-zones/)

**Proposed Solution:**
Complete rework of subsections.

**Page to Update:**
https://kubernetes.io/ja/docs/setup/best-practices/multiple-zones/

**Additional Information:**
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.
