### ISSUE TITLE
[ja] Add page translation for Enforcing Pod Security Standards

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41867]
**This is a Feature Request**

**What would you like to be added**
JA translation of "Getting Started > Best Practices > Enforcing Pod Security Standards" 

**Why is this needed**
The JA documentation only has the English version of the page

**Comments**
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.

**Comment by atoato88** [comment]
The target page which be translated is following:
- https://kubernetes.io/docs/setup/best-practices/enforcing-pod-security-standards/
