### ISSUE TITLE
[ja] Add page translation for "Debugging Kubernetes Nodes With Kubectl" and "Windows debugging tips"

### ISSUE THREAD

**Issue by tuibeovince** [kubernetes/website#41869]
**This is a Feature Request**

**What would you like to be added**
JA translation of the following pages:
* Tasks > Monitoring, Logging, and Debugging > Troubleshooting Clusters > [Debugging Kubernetes Nodes With Kubectl](https://kubernetes.io/docs/tasks/debug/debug-cluster/kubectl-node-debug/)
*  Tasks > Monitoring, Logging, and Debugging > Troubleshooting Clusters >[Windows debugging tips](https://kubernetes.io/docs/tasks/debug/debug-cluster/windows/)

**Why is this needed**
The JA documentation only links to the English version of the abovementioned pages.

**Comments**
/language ja
/assign

**Comment by atoato88** [comment]
/unassign @tuibeovince 
It looks no change on this issue for several weeks, so I remove the assignee.
Feel free to re-assign to you, if you have the time to resolve this issue.

**Comment by Okabe-Junya** [comment]
Thank you!!

/close

**Comment by Okabe-Junya** [comment]
I created #44987 #44988
