### ISSUE TITLE
[es] localize content/en/docs/home/supported-doc-versions.md to Spanish

### ISSUE THREAD

**Issue by electrocucaracha** [kubernetes/website#41872]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/home/supported-doc-versions.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs

**Comment by gamba47** [comment]
Hi @electrocucaracha please assign this issue to me.

**Comment by gamba47** [comment]
Hi again Victor you can close this issue this is the commit for this
https://github.com/kubernetes/website/commit/a57a3fe03098dd41a2069ea298ffb1692eace242

I checked it and it's working like a charm you can see here the spanish version https://kubernetes.io/es/docs/home/supported-doc-versions/
