### ISSUE TITLE
Incorrect feature state for "Pod Priority based graceful node shutdown"

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#41874]
Feature gate state "pod-priority-graceful-node-shutdown" is declared as alpha, but it should be beta.

https://kubernetes.io/docs/concepts/architecture/nodes/#pod-priority-graceful-node-shutdown
FEATURE STATE: Kubernetes v1.23 [alpha]

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
GracefulNodeShutdownBasedOnPodPriority=true|false (BETA - default=true)

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
GracefulNodeShutdownBasedOnPodPriority false Alpha 1.23 1.23
GracefulNodeShutdownBasedOnPodPriority true Beta 1.24

**Comment by dipesh-rawat** [comment]
/retitle Incorrect Feature Gate state for "Pod Priority based graceful node shutdown" in "Nodes" page

**Comment by sftim** [comment]
/retitle Fix incorrect feature state for "Pod Priority based graceful node shutdown"

**Comment by sftim** [comment]
Oops, sorry!
/retitle Incorrect feature state for "Pod Priority based graceful node shutdown"
