### ISSUE TITLE
[es] localize content/en/docs/tasks/run-application/scale-stateful-set.md to Spanish

### ISSUE THREAD

**Issue by electrocucaracha** [kubernetes/website#41877]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/tasks/run-application/scale-stateful-set.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs

**Comment by electrocucaracha** [comment]
/unassign @RakshitKumar04

Thanks for participating into the Kubernetes Website project. The Spanish translation team would like to facilitate your contribution's journey, so please share your goals and/or skills in order to assist you better. We also encourage new contributors to participate in their native speaking language.

**Comment by ARYANis0001** [comment]
Can anyone please help me why these checks are not ticked

**Comment by ramrodo** [comment]
closed by https://github.com/kubernetes/website/pull/44243

**Comment by ramrodo** [comment]
@electrocucaracha could you close this issue, please? It seems I can not close it because I didn't create it.
