### ISSUE TITLE
Incorrect label in kubectl command for inspecting Leases for kube-apiserver

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#41881]
The command `kubectl -n kube-system get lease -l k8s.io/component=kube-apiserver` showed nothing. But this command `kubectl -n kube-system get lease -l apiserver.kubernetes.io/identity=kube-apiserver` worked. It looks like the labels have been changed and now the example is different from the real state of version 1.27.3.

```bash
kubectl -n kube-system get lease -l apiserver.kubernetes.io/identity=kube-apiserver
NAME                                   HOLDER                                                                      AGE
apiserver-wj467rbl25eeviqacfhvg2yvnm   apiserver-wj467rbl25eeviqacfhvg2yvnm_0c8914f7-0f35-440e-8676-7844977d3a05   2d8h
```

```bash
kubectl -n kube-system get lease apiserver-wj467rbl25eeviqacfhvg2yvnm -o yaml
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-07-02T13:16:48Z"
  labels:
    apiserver.kubernetes.io/identity: kube-apiserver
    kubernetes.io/hostname: master-1
  name: apiserver-wj467rbl25eeviqacfhvg2yvnm
  namespace: kube-system
  resourceVersion: "334899"
  uid: 90870ab5-1ba9-4523-b215-e4d4e662acb1
spec:
  holderIdentity: apiserver-wj467rbl25eeviqacfhvg2yvnm_0c8914f7-0f35-440e-8676-7844977d3a05
  leaseDurationSeconds: 3600
  renewTime: "2023-07-04T21:58:48.065888Z"
```

https://kubernetes.io/docs/concepts/architecture/leases/

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/architecture/leases/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Incorrect label in kubectl command for inspecting Leases for kube-apiserver

**Comment by mengjiao-liu** [comment]
https://github.com/kubernetes/kubernetes/pull/114586
> Renamed API server identity Lease labels to use the key `apiserver.kubernetes.io/identity`

Judging from the k8s upstream code, this label has indeed been changed and the documentation needs to be updated.

/cc @andrewsykim  @lavalamp 
for confirm
