### ISSUE TITLE
Upgrading kubeadm clusters - Page not Found

### ISSUE THREAD

**Issue by RyanZhangLife** [kubernetes/website#41888]
The Page [Upgrading a kubeadm cluster from 1.20 to 1.21](https://v1-21.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/) can't be reached.

Please fix this problem

**Comment by utkarsh-singh1** [comment]
Hi @RyanZhangLife, This page does not seem to exist, As it may have already been expired or removed from the Kubernetes website due to being very old Kubernetes version.

Related page - https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
> Hi @RyanZhangLife, This page does not seem to exist, As it may have already been expired or removed from the Kubernetes website due to being very old Kubernetes version.

yes, please use the steps in one of the newer pages and replace OLD -> NEW versions.
the steps have to changed much, or at all..

/close
