### ISSUE TITLE
[es] localize content/en/docs/tasks/tools/install-kubectl-linux.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#41882]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/tasks/tools/install-kubectl-linux.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs

**Comment by ramrodo** [comment]
@deepak4566 Thanks for participating in the Kubernetes Website project. The Spanish translation team would like to help you with your contribution, so please share your goals and skills in order to help you better. We also encourage new contributors to participate in their native speaking language.

**Comment by gamba47** [comment]
In the line 150 there is a link to https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/administer-cluster/kubeadm/change-package-repository.md

This file is not available in the spanish directory.
