### ISSUE TITLE
invalid reference of link in Types of ephemeral volume

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#41904]
This is a Bug Report
There is the wrong link reffering to the page in Types of Ephemeral Volume..

Problem:
In Types of Ephemeral volume in https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#types-of-ephemeral-volumes there is CSI Ephemeral Volume having CSI Drivers as link in description which is intended to the description of CSI and Support this Feature is reffering to the list of CSI Drivers. Which is by its meaning is reffering to wrong source.

Proposed Solution:
Update

CSI Drivers link with the list of CSI Drivers https://kubernetes-csi.github.io/docs/drivers.html.

Support this Feature link with the https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html.
will be the best solution.

Page to Update:
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#types-of-ephemeral-volumes

**Comment by akshayamadhuri** [comment]
@niranjandarshann  can you assign me i would like to work on this issue

**Comment by niranjandarshann** [comment]
> @niranjandarshann can you assign me i would like to work on this issue

@akshayamadhuri  you can assign the issue to yourself by adding the label (/assign)
Assigning this issue to you.
/assign @akshayamadhuri

**Comment by sftim** [comment]
I don't think the link is broken, as such. We could change
```diff
-[CSI drivers](https://github.com/container-storage-interface/spec/blob/master/spec.md)
+{{< glossary_tooltip text="CSI" term_id="csi" >}} drivers
```
if we want to

**Comment by akshayamadhuri** [comment]
@sftim  i think its better to close this issue it is resolved

**Comment by akshayamadhuri** [comment]
@sftim is it the line on 52 about references

**Comment by niranjandarshann** [comment]
> 

yes @sftim  if we give this information for **CSI**  only then it will be good but if we refer the **CSI driver** then the link referening the CSI driver list will be good.
About [support this feature](https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html)  the link got fixed.

**Comment by niranjandarshann** [comment]
> > i think its better to close this issue it is resolved
> 
> You're sure? I think there's a thing to fix.

I also think we there's a need of fix here.

**Comment by niranjandarshann** [comment]
@akshayamadhuri are you working on this issue, If not you can unassign it so that i can assign and raise a PR.

**Comment by niranjandarshann** [comment]
i am assiging this issue
/assign

**Comment by niranjandarshann** [comment]
> I don't think the link is broken, as such. We could change
> 
> ```diff
> -[CSI drivers](https://github.com/container-storage-interface/spec/blob/master/spec.md)
> +{{< glossary_tooltip text="CSI" term_id="csi" >}} drivers
> ```
> 
> if we want to

@sftim  raised PR #43191 
PTAL!

**Comment by AmarNathChary** [comment]
> @sftim i think its better to close this issue it is resolved

This issue is partially fixed in #41912

**Comment by niranjandarshann** [comment]
marking as complete by PR  #43191 and https://github.com/kubernetes/website/pull/41912

**Comment by niranjandarshann** [comment]
closing this issue as completed
/close
