### ISSUE TITLE
Query about math in “Reserve Compute Resources for System Daemons”

### ISSUE THREAD

**Issue by aritraghosh** [kubernetes/website#41918]
In the example scenario, shouldn't pod eviction begin at memory eviction threshold which is 31.5Gi? Why is it based on allocatable. How is the overall memory usage across pods measured in cgroup v2.  Based on    `/sys/fs/cgroup/kubepods.slice/memory.max   this doesn't seem consistent. It excludes the memory eviction threshold 
`
` Kubelet evicts pods whenever the overall memory usage across pods exceeds 28.5Gi, or if overall disk usage exceeds 88Gi.`

**Comment by utkarsh-singh1** [comment]
Related Page - https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

**Comment by sftim** [comment]
/retitle Query about math in “Reserve Compute Resources for System Daemons”

I think a diagram or graph could help. However, the page isn't wrong so far as I can tell.

/kind support.

**Comment by aritraghosh** [comment]
https://github.com/kubernetes/website/pull/41931
