### ISSUE TITLE
Mention descheduler in Scheduling, Preemption, Eviction

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41919]
**This is a Feature Request**

**What would you like to be added**
Change https://kubernetes.io/docs/concepts/scheduling-eviction/ to mention the [descheduler](https://github.com/kubernetes-sigs/descheduler)

**Why is this needed**
The Kubernetes project provides the descheduler - as an add-on - but our overview of scheduling makes no mention of it.

**Comments**
/language en
/kind feature
/sig scheduling

**Comment by RakshitKumar04** [comment]
Hii, @sftim Can you please elaborate, do I just need to add a heading under Scheduling and connect a link to it?
![Screenshot from 2023-07-09 11-39-40](https://github.com/kubernetes/website/assets/72027411/f9342e21-3fd1-4693-bd48-08d87d74fd61)

**Comment by sftim** [comment]
Contributors are welcome to propose their own way to include the new concept (the descheduler) into the existing page.

@RakshitKumar04 if you are not sure about how to the new detail, you could consider looking for a different issue. Maybe there is some other work to do that you'd understand better.

**Comment by Shubham82** [comment]
IMO, we can make a new heading for descheduler and add a paragraph(some content) for descheduler under it, and link it to the
https://github.com/kubernetes-sigs/descheduler for more information.

**Comment by Shubham82** [comment]
Hi, @sftim your thoughts on the above opinion?

**Comment by sftim** [comment]
The approach I recommend is to open a PR and ask for feedback there. I don't see this as being a complicated change.

**Comment by Shubham82** [comment]
> The approach I recommend is to open a PR and ask for feedback there. I don't see this as being a complicated change.

Thanks @sftim for your opinion.
