### ISSUE TITLE
Viewing Pods and Nodes - Show the app in the terminal fails maybe due to trying port 80 when the server is running port 8080

### ISSUE THREAD

**Issue by craigcomstock** [kubernetes/website#41928]
I am working through https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/ and the step "Show the app in the terminal" but that gets a "connection refused" it seems because curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/ seems to try port 80 on the pod but the javascript server is listening on 8080. I have exec'd via bash and a local curl to 8080 works fine. Any ideas? Are the docs "wrong"? Do I need to reconfigure something for it to work?

later in the tutorial, https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/, curl http://"$(minikube ip):$NODE_PORT" just times out.

**Comment by craigcomstock** [comment]
pretty sure this issue is a duplicate of https://github.com/kubernetes/website/issues/41259, sorry if it is. I'll look more.

**Comment by craigcomstock** [comment]
Looks like the proposed fix there is incorrect and on-hold. This comment, https://github.com/kubernetes/website/pull/40590#issuecomment-1503163124, seems to indicate that the `/proxy/` ending does work, but in my case it does not apparently because of the port discrepancy?

```
$ curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 10.244.0.10:80: connect: connection refused",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**Comment by craigcomstock** [comment]
I am checking https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/ for the other issue I face with 
```
curl http://"$(minikube ip):$NODE_PORT"
```
not working.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/
/language en
/kind bug

**Comment by craigcomstock** [comment]
I also submitted zh-cn and pt-br fixes since the same pages existed there. I didn't see the same text/url anywhere else.

Still I am not sure why the service is not exposed but I suspect that is a different issue. I am using minikube as suggested by the tutorial.

**Comment by dipesh-rawat** [comment]
> pretty sure this issue is a duplicate of #41259, sorry if it is. I'll look more.

This indeed appears to be a duplicate of the mentioned issue #41259, marking this as a duplicate.

/triage duplicate

**Comment by craigcomstock** [comment]
Sorry for not finding the duplicate. Thanks for finding.
