### ISSUE TITLE
Update API reference page to fix dead/redirect links

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#4192]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Kubernetes API reference has many links to dead, redirected, or migrated docs pages. For example, there are 58 links to /user-guide/ pages, which are most likely all redirects.

**Proposed Solution:**
Update these links.

**Page to Update:**
https://kubernetes.io/docs/api-reference/v1.6/
https://kubernetes.io/docs/api-reference/v1.5/
Future API reference pages

**Comment by ahmetb** [comment]
@steveperry-53 and I recently decided (at https://github.com/kubernetes/kubernetes/pull/44474) that these redirects are O.K. as long as they keep working. This is somewhat a tedious operation and I bet a lot of the ToC will keep moving. So I am inclined to wontfix this for now.

**Comment by ahmetb** [comment]
If you've got time, you can go ahead and follow the fixes I made to *.go files in that PR and apply `hack/update-all.sh`, then submit a PR.
/unassign

**Comment by tengqm** [comment]
@chenopis keep or close?

**Comment by ahmetb** [comment]
I think we can /close
