### ISSUE TITLE
Add priority class into glossary

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#41943]
**This is a Feature Request**

**What would you like to be added**
Add a glossary entry for the [PriorityClass](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass) resource - changing https://kubernetes.io/docs/reference/glossary/?all=true

**Why is this needed**
When we mention PriorityClasses (or `priorityClassName`), it's handy to have a tooltip etc to help readers learn more.

**Comments**
/language en
/kind feature
/sig scheduling

**Comment by EraKin575** [comment]
adding to the list which contains add-ons etc?

**Comment by sftim** [comment]
Hi @EraKin575 - the page to change is https://kubernetes.io/docs/reference/glossary/?all=true

For an example of similar work, but adding a different entry (“Probe”), see https://github.com/kubernetes/website/pull/40131. That should give you a clue about how to add an entry for PriorityClass.

You can get general advice on contributing to the Kubernetes documentation by reading https://kubernetes.io/docs/contribute/

**Comment by EraKin575** [comment]
the Application term is duplicated

**Comment by mrgiles** [comment]
@sftim, shouldn't PR #45608 close this Issue?

**Comment by sergeyshevch** [comment]
I guess this was implemented in my PR. Lets /close this

**Comment by sergeyshevch** [comment]
I guess this was implemented in my PR. Lets close this

/close
