### ISSUE TITLE
scrolling autogenerated API references stops syncing overview panel

### ISSUE THREAD

**Issue by soma-kurisu** [kubernetes/website#41955]
scrolling up/down the main-window of [autogenerated API references](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27) highlight current section in overview-panel on the left.
![autogen-panel-in-sync](https://github.com/kubernetes/website/assets/69393463/ccd6ce75-24aa-4691-8bf5-5d65b0c4d87a)

this behaviour breaks when scrolling down beyond [ResourceClaim Replace Status API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#replace-status-resourceclaim-v1alpha2-resource-k8s-io).

Entries on lefthandside panel are no longer synced with main-window content.
![autogen-panel-out-of-sync](https://github.com/kubernetes/website/assets/69393463/9a726b22-8070-461a-b7fe-58a6cd66a31e)

**Comment by sca-ai** [comment]
btw. this happens on all major browsers.

**Comment by hasanrashid** [comment]
I'd like to try this one
/assign
