### ISSUE TITLE
[it] Broken link for "Create a cluster in High-Availability" in Kubernetes Components page

### ISSUE THREAD

**Issue by AgostiniAlessandro** [kubernetes/website#41967]
From https://kubernetes.io/it/docs/concepts/overview/components/ the link to 
https://kubernetes.io/docs/admin/high-availability/  is broken

**Comment by rituisboy** [comment]
can i contribute to this

**Comment by EraKin575** [comment]
The link is broken in every component
![image](https://github.com/kubernetes/website/assets/100225222/c65fe8c8-2342-4de3-a6f6-09615fd91acd)
