### ISSUE TITLE
[zh] Localize blog: 2023-07-06-confidential-kubernetes

### ISSUE THREAD

**Issue by asa3311** [kubernetes/website#41971]
I will localize the blog: [Verifying Container Image Signatures Within CRI Runtimes](https://kubernetes.io/blog/2023/07/06/confidential-kubernetes/).

To avoid any conflict, this issue is opened.

/language zh
/assign

**Comment by mengjiao-liu** [comment]
PR https://github.com/kubernetes/website/pull/41806 has been merged.

/close
