### ISSUE TITLE
Stale docs for topology aware routing constraints

### ISSUE THREAD

**Issue by aojea** [kubernetes/website#41996]
The existing documentation for Topology Aware Routing says

> Topology Aware Hints are not used when either externalTrafficPolicy or internalTrafficPolicy is set to Local on a Service. It is possible to use both features in the same cluster on different Services, just not on the same Service.

however, this was before @danwinship refactored and fixed the kube-proxy traffic policy problems caused by the lack of definitions on the Service traffic types https://github.com/kubernetes/kubernetes/issues/108526.

This caused issues like https://github.com/kubernetes/kubernetes/issues/100313 fixed with https://github.com/kubernetes/kubernetes/pull/106497, because we have mixed mode, 

If I understand correctly, right now `externalTrafficPolicy: local` and `Topology Aware Routing` are not exclusive, since the former applies the traffic that is originated from "outside the cluster" and the later only applies to the traffic originated within the cluster.

If that is correct , we should modify the documentation to say

"Topology Aware Hints are not used when internalTrafficPolicy is set to Local on a Service. It is possible to use both features in the same cluster on different Services, just not on the same Service."

**Comment by sftim** [comment]
/retitle Stale docs for topology aware routing constraints

**Comment by robscott** [comment]
Thanks for catching this @aojea! Agree with your proposed fix.
