### ISSUE TITLE
[ja] Translate reference/kubernetes-api/service-resources/service-v1 into Japanese

### ISSUE THREAD

**Issue by maclo2012** [kubernetes/website#42007]
This is a Feature Request

What would you like to be added

Translate https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1 into Japanease

Why is this needed

Comments

/language ja
/assign

**Comment by akshayamadhuri** [comment]
@maclo2012  i would like to work on this issue

**Comment by maclo2012** [comment]
@akshayamadhuri 
Sorry, I have already started the translation.
In addition, I was going to translate the [Ingress page](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/) into Japanese in another Issue, but can I have it replaced?

**Comment by akshayamadhuri** [comment]
@maclo2012  sure

**Comment by Okabe-Junya** [comment]
/unassign @maclo2012 
/unassign @IbukiMnw 

Hi folks!!

It looks no change on this issue for several months, so I remove the assignee. Feel free to re-assign when you work on this issue :)

**Comment by kohbis** [comment]
@Okabe-Junya （メンション先が適切でなければすみません🙇）
こちら元のドキュメントが自動生成なのですが、そのまま翻訳するで問題ないのでしょうか？
それとも追従するためになんらか対応する必要がありますでしょうか？

**Comment by Okabe-Junya** [comment]
このページは https://github.com/kubernetes-sigs/reference-docs を用いて自動生成されているのですが、l10nは自動生成されたページを愚直に翻訳している認識です（zh-cn がそうしているはずです）

なので、「元のドキュメントをそのまま翻訳する」方法でお願いしますmm
（あまり優先度の高いページではないので、その場合は一旦 closeしてもらっても大丈夫です）
