### ISSUE TITLE
[ja] update /docs/setup/best-practices/multiple-zones/ page according to en page

### ISSUE THREAD

**Issue by sp-yduck** [kubernetes/website#42015]
[This page](https://kubernetes.io/ja/docs/setup/best-practices/multiple-zones/) is not well maintained like there is a broken link ([Ubernetes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multicluster/federation.md)) for example. 
so this page should be properly updated based on en page.

/language ja
/assign

**Comment by deepak4566** [comment]
in english documentation also ,the link is broken and  i think federation.md got deleted so link is broken

**Comment by Okabe-Junya** [comment]
This issue seems to be a duplicate of #41865.

I will close this and move to #41865

/close
