### ISSUE TITLE
Simplify content in "Overview" page and address spelling errors

### ISSUE THREAD

**Issue by GauravDhak** [kubernetes/website#42026]
rewrite Documentation of Overview Kubernetes lots of spelling  mistakes  there in  entire Documentation , need to describe overview of 
Kubernetes in simple language .

**Comment by tamilselvan1102** [comment]
Page related to issue: https://kubernetes.io/docs/concepts/overview/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Simplify content in "Overview" page and address spelling errors

**Comment by sftim** [comment]
/priority awaiting-more-evidence

What spelling mistakes are there? Please detail what you've seen @GauravDhak

**Comment by sftim** [comment]
I amended the issue description to remove a list that seemed irrelevant. Here's what I removed:


> ```[tasklist]
> ### Tasks
> - [ ] https://github.com/kubernetes/website/pull/20196
> ```

**Comment by mukeshmahato18** [comment]
> /priority awaiting-more-evidence
> 
> What spelling mistakes are there? Please detail what you've seen @GauravDhak

Upon careful review, I couldn't find any spelling mistakes in the entire documentation.

**Comment by GauravDhak** [comment]
Here I want close this issue , no need to change anything in Documentation already someone are Contribute over there ! Sorry for inconvenience
