### ISSUE TITLE
Unexpected impact on source PVC when modifying cloned destination PVC using "CSI Volume Cloning" concept

### ISSUE THREAD

**Issue by gauravkumar9130** [kubernetes/website#42030]
I created two separate applications and used this concept to clone. But when I am making changes in destination volume it's also changing in source PVC.

Any reason for this?

**Comment by AmarNathChary** [comment]
**Page**:https://kubernetes.io/docs/concepts/storage/volume-pvc-datasource/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Unexpected impact on source PVC when modifying cloned destination PVC using "CSI Volume Cloning" concept

**Comment by niranjandarshann** [comment]
If the source and destination volumes accidently  sharing the same underlying storage resource so changes made in the destination volume will naturally affect the source PVC. Make sure that cloning process creates separate and independent volumes that do not share the same storage resource which  using different storage classes and separate physical storage  or other mechanisms provided by your CSI driver to ensure isolation between the volumes. 

I think this may help you.

**Comment by gauravkumar9130** [comment]
Thank you, Niranjan, for your response, in my case I used two separate PVs with different host paths (folder). Will it still affect source PVC?

**Comment by niranjandarshann** [comment]
> Thank you, Niranjan, for your response, in my case I used two separate PVs with different host paths (folder). Will it still affect source PVC?

If you are using two separate Persistent Volumes (PVs) with different host paths (folders) for your source and destination volumes, changes made in the destination volume should not affect the source PVC.

@gauravkumar9130  it may be possible that you are using some CSI drivers might have limitations or issues with the cloning process that could result in unexpected behavior like you are facing.

**Comment by gauravkumar9130** [comment]
I tried in Azure Kubernetes Service Cluster, SUSE Rancher, and also in the On-Prem Kubernetes cluster, and the result was same.

If you want I can share my yaml files, which you can check

**Comment by niranjandarshann** [comment]
Hello @gauravkumar9130 thank you for your contribution due to lack of activity on this issue from more than ~3 months i will be closing this issue. If you have the bandwidth to work on it please feel free to reopen it or resume by issuing or / reopen command.
/close
