### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configmap-secret/managing-secret-using-kustomize/

### ISSUE THREAD

**Issue by SebTardif** [kubernetes/website#42034]
Well, it's randomly creating a name for the secret. I don't think what/who is going to use that created secret is expected to be a human. How, the rest of the system is expected to know the random name? 

It seems the default behavior of having auto-detection of something changed by creating random name, is less relevant that be able to use it programatically. 

So my ask here, is to complete the doc, to show how the rest of Kustomization that define the 'user' of that newly created secret will automatically get the generated name.

**Comment by dipesh-rawat** [comment]
**_Page related to issue:_** https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-kustomize/
/language en

**Comment by AmarNathChary** [comment]
Kustomize does not directly provide a way to automatically propagate the generated secret name to the resources using it within the same Kustomization. Kustomize treats resources independently during the build process, and there is no direct built-in reference mechanism to capture the generated secret name and automatically propagate it.

**Comment by sftim** [comment]
Let's:
- make it explicit that this Secret will have an arbitrary name
- label the Secret
- demonstrate using `kubectl get` to find that Secret based on a label match

Assuming that we will:
/help
/triage accepted
/priority backlog

**Comment by pegasas** [comment]
Hi, team, 

I am willing to raise a PR for this issue.

I will try the options that @sftim mentioned first.

/assign @pegasas

**Comment by pegasas** [comment]
Hi, @sftim , @dipesh-rawat , @SebTardif , @AmarNathChary ,

I referred to the steps on https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/,
I think this way may be more common for customization.

feel free to comment if any concerns.

**Comment by pegasas** [comment]
merged PR.
request close this issue.
feel free to reopen if there are any further concerns.
/close
