### ISSUE TITLE
Dismissing sweetAlert causes window to return to top of page

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#4205]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
In #4201, I noticed that dismissing sweetAlerts causes the window to kick you back to the top of the page. This is a poor user experience: the user needs to traverse the page to go back to where they were.

**Proposed Solution:**
Either fix the sweetAlert code to patch this behavior, or remove the functionality.

**Page to Update:**
https://github.com/kubernetes/website/blob/master/static/js/sweetalert-1.1.3.min.js

**Comment by ryanmcginnis** [comment]
Ping. I'd like to make this a high priority and to get an assignee to investigate. This user experience needs to be improved.

**Comment by chenopis** [comment]
@ryanmcginnis P1 or P0?

**Comment by ryanmcginnis** [comment]
P1

**Comment by tengqm** [comment]
Still a problem? @ryanmcginnis

**Comment by ryanmcginnis** [comment]
Yes, still needs to be fixed.

**Comment by ryanmcginnis** [comment]
/lifecycle rotten

This is still a problem and it seems somewhat easy to fix. Any takers?

**Comment by ryanmcginnis** [comment]
Bumping again. Using the click-to-copy button still knocks me back to the top of the page. Anyone interested in owning this?

**Comment by ryanmcginnis** [comment]
seems like this is fixed in #15542
