### ISSUE TITLE
Problem with “Declare Network Policy” task

### ISSUE THREAD

**Issue by erchauhannitin** [kubernetes/website#42069]
Repeated same steps on this page -
https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/#test-the-service-by-accessing-it-from-another-pod

There is no difference whether we label it or not. Page has 2 test cases - one where access is present and one where access is blocked. 
Kubectl version is 1.27

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy
/language en

**Comment by sftim** [comment]
/kind bug
/retitle Problem with “Declare Network Policy” task

**Comment by erchauhannitin** [comment]
Please close the ticket. It was env issue. CNI was not working properly
