### ISSUE TITLE
Use /usr/share/keyrings in older-debian distribution for kubeadm installation.

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#42066]
**This is a Feature Request**

**What would you like to be added**
Older ubuntu-distros (before ubuntu 22.04) have keyring folder stored in `/usr/share` folder instead of `/etc/apt/keyrings`, we can mention there that in place of `/etc/apt/keyrings` in gpg -demirror and signed-by use `/usr/share/keyrings`. 

**Why is this needed**
An alternate option instead of creating another directory `/etc/apt/keyrings`.

**Comment by sftim** [comment]
Adding the advice you suggest would contravene Debian's guidelines on systems security, so we shouldn't add it. Instead, people should create `/etc/apt/keyrings` as the existing docs suggest.

/sig security

**Comment by utkarsh-singh1** [comment]
Sure @sftim 

/close
