### ISSUE TITLE
Develop a video guide/tutorial for beginners on creating deployments with kubectl

### ISSUE THREAD

**Issue by yalle-prado** [kubernetes/website#42071]
Creating a new Kubernetes video for learners

**Comment by dipesh-rawat** [comment]
_Feature requested for Page:_ https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
/kind feature
/language en

**Comment by dipesh-rawat** [comment]
/retitle Develop a video guide/tutorial for beginners on creating deployments with kubectl

**Comment by yalle-prado** [comment]
> o

thanks

**Comment by utkarsh-singh1** [comment]
As for the beginner deployment tutorial you can refer to https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/, 

And as for video tutorial , this can be a good option but there are lots of issues to be solve right now so it would be beneficiary, if this suggestion can applied later.
