### ISSUE TITLE
Incorrect link for parameters for a volume claim

### ISSUE THREAD

**Issue by thisisharrsh** [kubernetes/website#42099]
**This is a Bug Report**
**Problem:**
The link for `parameters for a volume claim` under the [Lifecycle and PersistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#lifecycle-and-persistentvolumeclaim) in [Ephemeral Volumes ](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/) is wrong. It is redirecting to the `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#ephemeralvolumesource-v1alpha1-core` instead of that it should redirect to the `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#ephemeralvolumesource-v1-core` 

**Proposed Solution:**
Lifecycle and PersistentVolumeClaim should redirect to the `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#ephemeralvolumesource-v1-core` instead to the `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#ephemeralvolumesource-v1alpha1-core` 

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/

**Comment by thisisharrsh** [comment]
I would like to work on it. 
/assign

**Comment by tengqm** [comment]
/close
as done.
