### ISSUE TITLE
Enhance and add more evictionHard thresholds in example yaml to encourage holistic parameter changes

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes/website#42105]
**This is a Bug Report**

**Problem:**
As we know that, in eviction hard thresholds, when we change the default value of any one of the four parameters (memory.available, nodefs.available, imagefs.available, nodefs.inodesFree), then the value of other parameters will be set to 0. 
Although this is an expected behaviour but I think it's not a good motivation for user to change only the one parameter as given in this [example](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#create-the-config-file). As setting other parameters to 0 is not a good scenario.
**Proposed Solution:**
Is there any good case by setting the other parameters to 0 or we should change the example to motivate users to change all parameters
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/

**Comment by dipesh-rawat** [comment]
/retitle Enhance and add more evictionHard thresholds in example yaml to encourage holistic parameter changes
