### ISSUE TITLE
Generated API docs are outdated for Job (podFailurePolicy is beta)

### ISSUE THREAD

**Issue by mimowo** [kubernetes/website#42112]
**This is a Bug Report**

**Problem:**
The information about pod failure policy API level is outdated: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/. Here is the code: https://github.com/kubernetes/website/blob/main/content/en/docs/reference/kubernetes-api/workload-resources/job-v1.md#alpha-level. 

This might be related to the fact that in upstream there was a bug that the API comments were not updated for two releases. They have been fixed however two months ago which should be enough time to propagate the fix: https://github.com/kubernetes/kubernetes/pull/117802.

**Proposed Solution:**
Unsure, might require adjusting the api generation pipeline. The generator code is here: https://github.com/kubernetes-sigs/reference-docs/

**Page to Update:**
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/job-v1/

The PR fixed it manually: https://github.com/kubernetes/website/pull/42110.

**Comment by mimowo** [comment]
FYI @sftim

**Comment by sftim** [comment]
/retitle Generated API docs are outdated for Job (`podFailurePolicy` is beta)

The docs are wrong; `podFailurePolicy` is actually beta

**Comment by AryanSharma9917** [comment]
Hey @mimowo here in [content/en/docs/tasks/job/pod-failure-policy.md](https://github.com/kubernetes/website/blob/d18c30633c84880db2857371da439bd293e20585/content/en/docs/tasks/job/pod-failure-policy.md) based on the content provided from the Kubernetes documentation, it seems that the podFailurePolicy field in the Job resource is indeed in beta and not alpha.

![image](https://github.com/kubernetes/website/assets/72792907/ed30b11e-baa4-4455-a041-b672603f8cbd)

So this is the issue we are facing correct? Correct me if I am wrong!

**Comment by mimowo** [comment]
Hi @AryanSharma9917. Yes, the field is currently in Beta, it is not just the docs that are outdated. https://github.com/kubernetes/website/blob/main/content/en/docs/reference/kubernetes-api/workload-resources/job-v1.md#alpha-level

This is because the docs are generated once per release as mentioned in https://github.com/kubernetes/website/issues/42112#issuecomment-1644157691. And, at the moment of making the generation of docs, the k/k repo had a bug and still mentioned in comments that the field is Alpha. This bug is fixed now.

As @sftim it is ok to bump the comment manually since we don't have yet the mechanism. I have already opened a PR for that bump: https://github.com/kubernetes/website/pull/42110. Please review.

**Comment by mimowo** [comment]
I have updated the title and the description after the issue with pod failure policy is closed. However, I think it makes sense to leave it for now, as the underlying issue is still there. WDYT @sftim @tengqm?

**Comment by tengqm** [comment]
I'm okay to leave this open in hope someday someone will pick it up.

**Comment by sftim** [comment]
If you're willing to, @mimowo:

- change the title back to Generated API docs are outdated for Job (podFailurePolicy is beta)
- open a **new** issue titled Generated API docs remain outdated if changed upstream

**Comment by mimowo** [comment]
/close 
Done by https://github.com/kubernetes/website/pull/42110.
