### ISSUE TITLE
Volumes: feature gates and some typos

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42127]
Declared "CSIMigration" feature gate only exists in [removed feature flags](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/). According to [this page section](https://kubernetes.io/docs/concepts/storage/volumes/#openstack-csi-migration) "CSIMigration" could be a switchable feature gate, but it looks like it is always on and cannot be switched off, so it it's strange that it's mentioned in the v1.27 documentation. All of this is probably more or less OK, as it's suitable for earlier versions of Kubernetes especially since there are deprecation warnings.

But it’s also unclear for which components this feature gate is intended. According to [this page](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#migrating-from-in-tree-ebs-plugin) it's intended for `kube-controller-manager`.

> https://kubernetes.io/docs/concepts/storage/volumes/#aws-ebs-csi-migration
> https://kubernetes.io/docs/concepts/storage/volumes/#azuredisk-csi-migration
> https://kubernetes.io/docs/concepts/storage/volumes/#azurefile-csi-migration
> https://kubernetes.io/docs/concepts/storage/volumes/#gce-csi-migration

<br>

It is not clear for which components "CSIMigrationAzureFile" feature gate is intended.
> https://kubernetes.io/docs/concepts/storage/volumes/#azurefile-csi-migration

<br>

It is not clear which controller manager is meant — cloud controller manager or kube-controller-manager. According to [this page section](https://kubernetes.io/docs/concepts/storage/volumes/#portworx-csi-migration) it's intended for `kube-controller-manager`.

> https://kubernetes.io/docs/concepts/storage/volumes/#aws-ebs-csi-migration-complete (InTreePluginAWSUnregister)
> https://kubernetes.io/docs/concepts/storage/volumes/#azuredisk-csi-migration-complete (InTreePluginAzureDiskUnregister)
> https://kubernetes.io/docs/concepts/storage/volumes/#azurefile-csi-migration-complete (InTreePluginAzureFileUnregister)
> https://kubernetes.io/docs/concepts/storage/volumes/#openstack-csi-migration (InTreePluginOpenStackUnregister)
> https://kubernetes.io/docs/concepts/storage/volumes/#gce-csi-migration-complete (InTreePluginGCEUnregister)
> https://kubernetes.io/docs/concepts/storage/volumes/#vsphere-csi-migration-complete

It is not clear for which components "CSIMigrationRBD" feature gate is intended:
> https://kubernetes.io/docs/concepts/storage/volumes/#rbd-csi-migration

<br>

It is not clear for which components "SizeMemoryBackedVolumes" feature gate is intended.
> https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

<br>

The description of "nodeExpandSecretRef" field does not start with a new line in the list.
> https://kubernetes.io/docs/concepts/storage/volumes/#csi

<br>

The double word "node".
> For Linux worker nodes, containerized CSI node node plugins are typically deployed as privileged containers.
> https://kubernetes.io/docs/concepts/storage/volumes/#windows-csi-proxy

**Comment by nnlkcncff** [comment]
> You can specify feature gates for all Kubernetes components (some might be no-ops). We could document that, but it'd be better to track that change as a separate issue.

@sftim, If you prefer to track this as separate issue, whether I should do something extra or not?

**Comment by sftim** [comment]
If you're willing to file a separate issue about that clarification @nnlkcncff, please do.

**Comment by nnlkcncff** [comment]
> * Let's stop mentioning `CSIMigration` in https://kubernetes.io/docs/concepts/storage/volumes/
> * You can specify feature gates for all Kubernetes components (some might be no-ops). We could document that, but it'd be better to track that change as a separate issue.
> * Let's remove the double use of node
> * Let's fix the formatting for `nodeExpandSecretRef`
> 
> @nnlkcncff these are useful things to point out. Thank you! If you find more, you can help further by opening one issue per thing that will need fixing.

I created separate issue https://github.com/kubernetes/website/issues/42199, so this issue should be closed after solving everything except point 2.

**Comment by RakshitKumar04** [comment]
Hey, @nnlkcncff should I just work on typos here?

- The description of "nodeExpandSecretRef" field does not start with a new line in the list.
  https://kubernetes.io/docs/concepts/storage/volumes/#csi

- The double word "node".
  For Linux worker nodes, containerized CSI node node plugins are typically deployed as privileged containers.
  https://kubernetes.io/docs/concepts/storage/volumes/#windows-csi-proxy

**Comment by nnlkcncff** [comment]
@RakshitKumar04, If it leads to a documentation fix, sure. Sorry, but I don't know enough about the workflow adopted here. I just feel it is my duty to help make the documentation better and I do my best.

**Comment by RakshitKumar04** [comment]
Hey, @sftim Should I raise a PR correcting the documentation?
