### ISSUE TITLE
incorrect image version in "Performing a Rolling Update" page

### ISSUE THREAD

**Issue by nanotubing** [kubernetes/website#42125]
URL in question: https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/

Under the heading `Roll back an update`, the following command is given:
`kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=gcr.io/google-samples/kubernetes-bootcamp:v10`
The version at the end appears to be incorrect, and this image failed to start for me. Instead, I issued the version of this command shown under the heading `Deploy an app` on the "Using kubectl to Create a Deployment" page, which worked successfully for me. The version listed in the sentence immediately preceding this command may also need to be updated.

As far as I can tell, this is located in lines [163-164](https://github.com/kubernetes/website/blob/0cbd189e4e24ae40824e77fcad2bc57eb52eb72a/content/en/docs/tutorials/kubernetes-basics/update/update-intro.html#L163-L164) in update-intro.html

Correct Version:
`kubectl set image deployments/kubernetes-bootcamp kubernetes-bootcamp=gcr.io/google-samples/kubernetes-bootcamp:v1`

**Comment by nanotubing** [comment]
I'm sorry everyone, I just realized the error was intentional. Sorry for the bother

**Comment by T-Lakshmi** [comment]
There is nothing to be fix, hence closing the issue.

/close

**Comment by T-Lakshmi** [comment]
@nanotubing,
Please close the issue as no fix needed.

**Comment by nanotubing** [comment]
no fix needed
