### ISSUE TITLE
"Play with Kubernetes" labs.play-with-k8s.com playground does not work

### ISSUE THREAD

**Issue by gertsog333** [kubernetes/website#42129]
Hello!
Unfortunatelu http://labs.play-with-k8s.com is down
"Play with Kubernetes" playground does not work.
Could you please take a look ?

**Comment by dipesh-rawat** [comment]
I believe there is nothing to fix in docs (yet). You can learn Kubernetes either by setting it up locally or using an alternative learning sandbox that functions properly. It is likely that http://labs.play-with-k8s.com/ will be accessible again soon.

However, if https://labs.play-with-k8s.com/ is permanently unavailable, we should refrain from providing links to it. @gertsog333, do know whether this is a short-term issue or a long-term one?

If you know that it's a temporary problem, you might consider reporting it to their issue tracker, which I believe can be found at https://github.com/play-with-docker/play-with-kubernetes.github.io/issues/.

/language en

**Comment by T-Lakshmi** [comment]
Related issues #40013 and #40854.

**Comment by sftim** [comment]
This may be a duplicate of https://github.com/kubernetes/website/issues/40013

**Comment by sftim** [comment]
/kind bug

I can reproduce this issue.
/triage accepted
/priority important-longterm

**Comment by gertsog333** [comment]
http://labs.play-with-k8s.com/ Still down((
Please turn it back

**Comment by sftim** [comment]
> Please turn it back

@gertsog333 you should file the issue at https://github.com/play-with-docker/play-with-kubernetes.github.io and not here.

All we'll do is change our website to not link there. We (SIG Docs) won't take over somebody else's website and fix it.

**Comment by gertsog333** [comment]
Sorry
will switch to https://github.com/play-with-docker/play-with-kubernetes.github.io/issues/67

**Comment by Ritikaa96** [comment]
@gertsog333 Hi, If you have raised an issue in the other repo, you can close this issue here. or you can wait till it is resolved as if this error is there to stay for long we can remove the link.

**Comment by dipesh-rawat** [comment]
Looks like nothing to fix, [Play With Kubernetes ](http://labs.play-with-k8s.com/) is back (at least at the time of writing this comment).

**Comment by sftim** [comment]
/close

Symptoms have disappeared

**Comment by gertsog333** [comment]
Play with Kubernetes is Working now!
Thanks to all !

**Comment by fadeldamen** [comment]
down again http://labs.play-with-k8s.com/  the site is wonderful and helps us a lot in our daily lives
