### ISSUE TITLE
Confusing wording and contradictory description in "Persistent Volumes" Class Section

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42137]
Consider changing the wording, the description seems a bit contradictory and therefore confusing.
> https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1

It's not so easy, but I'll try to explain.

The phrase `PVCs don't necessarily have to request a class. A PVC with its storageClassName set equal to "" is always interpreted to be requesting a PV with no class, so it can only be bound to PVs with no class` looks like an unbreakable rule, but it isn't. You could think that it's impossible to bound PVC with storageClassName set equal to `""` to PV with storageClassName set equal to `""` or to default class.

The next phrase `A PVC with no storageClassName is not quite the same and is treated differently by the cluster, depending on whether the DefaultStorageClass admission plugin is turned on.` implies that the following are conditions that do not refer to the above `storageClassName = ""`, but it isn't. The following describes conditions that cause dissonance with a rule that seemed unbreakable, because they overwrite this rule.

This made the whole class section confusing, which forced me to draw a diagram and discuss this with several people.
![doc](https://github.com/kubernetes/website/assets/82151266/50124833-83ef-404e-955b-10f848e0919c)

At first everything seemed clear, but after getting into the details everyone ended up confused.

<br>

I think I know what the documentation meant:
![result](https://github.com/kubernetes/website/assets/82151266/83eddae2-5c20-4219-9f44-e69632117802)

But I'm still not sure and I don't think I'm the only one.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/storage/persistent-volumes/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Confusing wording and contradictory description in "Persistent Volumes" Class Section
/sig storage

**Comment by Affan-7** [comment]
Well,  I will test it's true behaviour.
