### ISSUE TITLE
discpvblic

### ISSUE THREAD

**Issue by painpvblic** [kubernetes/website#42141]

**Comment by dipesh-rawat** [comment]
@painpvblic Could you please share the details on the issue you would like to report or the assistance you require? Kindly provide details in the [description](https://github.com/kubernetes/website/issues/42141#issue-1817036054) of the issue.

/triage needs-information

**Comment by dipesh-rawat** [comment]
/close not-planned

@painpvblic You are welcome to reopen this and add details
