### ISSUE TITLE
Unclear text in “Creating a Deployment” section of Deployment concept

### ISSUE THREAD

**Issue by fullerrc** [kubernetes/website#42152]
It is unclear what is meant by 

> Before creating a Deployment define an [environment variable](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container) for a container.

The statement appears directly under the heading "Creating a Deployment."  It is confusing, and it is unclear what relevance defining an "environment variable" has to do with a deployment.  Could it be that the author intended to present an action item of defining a pod, and linked to another article that coincidentally contained markup to do so?  Suggestion is to clean up the paragraph, and link it to an appropriate article on defining pods, if so.

**Comment by sftim** [comment]
/retitle Unclear text in “Creating a Deployment” section of Deployment concept

**Comment by sftim** [comment]
I recommend removing
> Before creating a Deployment define an [environment variable](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container) for a container.

from the page. That's a small fix that doesn't need us to work on the rest of https://github.com/kubernetes/website/issues/12082

**Comment by tamilselvan1102** [comment]
page to be updated: [deployment ](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)

**Comment by dipesh-rawat** [comment]
Looks similar (possibly duplicate) of issue we already have https://github.com/kubernetes/website/issues/41735

**Comment by sftim** [comment]
/remove-help
Oops
