### ISSUE TITLE
Incorrect `HUGO_VERSION` line reference in netlify.toml within README.md

### ISSUE THREAD

**Issue by Affan-7** [kubernetes/website#42164]
Under the [README.md](https://github.com/kubernetes/website#running-the-website-locally-using-hugo) the [netlify.toml](https://github.com/kubernetes/website/blob/main/netlify.toml#L10) is pointing toward the wrong line in the file.

**Comment by dipesh-rawat** [comment]
/retitle Incorrect `HUGO_VERSION` line reference in netlify.toml within README.md
