### ISSUE TITLE
Installation failed due to googleapi timeout to CVE feed

### ISSUE THREAD

**Issue by xinsir88** [kubernetes/website#42162]
我在内网环境使用容器部署k8s文档的website服务，报错。
报cve-feed的错误，提示下载googleapi超时。

因为我的环境是内网，无法访问互联网，所以我通过grep -rn "{{< cve-feed >}}"查找了所有包含这个字符串的md文件，然后删除了该行。
   再次启动问题依旧。

日志如下：
Failed to get JSON resource “https://storage.googleapis.com/k8s-cve-feed/official-cve-feed.json”: Get https://storage.googleapis.com/k8s-cve-feed/official-cve-feed.json: dial tcp: lookup storage.googleapis.com on 10.96.0.10:53: Server misbehaving

If you feel that this shuld not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 121234 ms

Error: Error building site: failed to render pages: render of "page" failed: "/src/layouts/_defaults/cve-feed.rss.xml:10:26": execute of template failed: template: _defatule/cve-feed.rss.xml:10:26: executing "_default/cve-feed.rss.xml" at <time.Format>: error calling Format: unable to cast <nil> of type <nil> to Time

**Comment by dipesh-rawat** [comment]
@xinsir88 Hi, Please file the issue in English, if feasible. I guess you're having issues with trying to build and [run the website using a container](https://github.com/kubernetes/website#running-the-website-using-a-container)?

**Comment by xinsir88** [comment]
Install the website of k8s documentation, use container deployment, report an error, please help, thank you very much.


I use the container to deploy the website service of the k8s document in the internal network environment, and an error is reported.
A cve-feed error is reported, indicating that the download of googleapi has timed out.

Because my environment is an intranet and I cannot access the Internet, I searched for all md files containing this string through grep -rn "{{< cve-feed >}}", and then deleted this line.
Restart the problem still.

The log is as follows:
Failed to get JSON resource “https://storage.googleapis.com/k8s-cve-feed/official-cve-feed.json”: Get https://storage.googleapis.com/k8s-cve-feed/official-cve-feed.json: dial tcp: lookup storage.googleapis.com on 10.96.0.10: 53: Server misbehaving

If you feel that this shuld not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 121234 ms

Error: Error building site: failed to render pages: render of "page" failed: "/src/layouts/_defaults/cve-feed.rss.xml:10:26": execute of template failed: template: _defatule/cve-feed.rss.xml:10:26: executing "_default /cve-feed.rss.xml" at <time.Format>: error calling Format: unable to cast of type to Time

**Comment by sftim** [comment]
/language zh
/triage needs-information

We track issues in English. Please describe the issue in English if you can @xinsir88

**Comment by sftim** [comment]
Hi. I'm afraid we only support development when you have internet access. You could however delete (and not commit) the CVE feed files. We don't have a README on how to do that.

**Comment by sftim** [comment]
/kind support

Feels more like a support request than anything.

**Comment by xinsir88** [comment]
> Hi. I'm afraid we only support development when you have internet access. You could however delete (and not commit) the CVE feed files. We don't have a README on how to do that.

How should I delete the CVE feed? Please help, thanks a lot.

**Comment by xinsir88** [comment]
help help help help

**Comment by mengjiao-liu** [comment]
> grep -rn "{{< cve-feed >}}", and then deleted this line. 
```
        modified:   content/en/docs/reference/issues-security/official-cve-feed.md
        modified:   content/pt-br/docs/reference/issues-security/official-cve-feed.md
        modified:   content/zh-cn/docs/reference/issues-security/official-cve-feed.md
```

and delete the following files.
```
        deleted:    layouts/_default/cve-feed.json
        deleted:    layouts/_default/cve-feed.rss.xml
        deleted:    layouts/shortcodes/cve-feed.html
```
I tested it in my local environment, and it worked without an Internet connection. 

Above content hope to help you.@xinsir88

**Comment by windsonsea** [comment]
/retitle Installation failed due to googleapi timeout to CVE feed

**Comment by sftim** [comment]
For advice on contributing to Kubernetes, especially from behind a firewall / censorship restrictions, you may be able to get help from #sig-docs on the Kubernetes Slack workspace.

**Comment by sftim** [comment]
If anyone wants to add a feature to allow building the site without the CVE feed for local development, they're welcome to.
