### ISSUE TITLE
Inconsistencies in default StorageClass behaviour in "Storage Classes" and "Persistent Volumes" pages

### ISSUE THREAD

**Issue by Affan-7** [kubernetes/website#42176]
Here is a statement under the [storage-class](https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass) documentation.
>If more than one default StorageClass is accidentally set, the newest default is used when the PVC is dynamically provisioned.

Here is another statement that contradicts with the first one in the [persistent-volume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1) documentation.
>If more than one default is specified, the admission plugin forbids the creation of all PVCs.

**Comment by dipesh-rawat** [comment]
_Pages related to issue:_ https://kubernetes.io/docs/concepts/storage/storage-classes , https://kubernetes.io/docs/concepts/storage/persistent-volumes
/language en

**Comment by dipesh-rawat** [comment]
/retitle Inconsistencies in default StorageClass behaviour in "Storage Classes" and "Persistent Volumes" pages
/sig storage
