### ISSUE TITLE
Link from static pod concept to task page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42195]
**This is a Feature Request**

**What would you like to be added**
Change https://kubernetes.io/docs/concepts/workloads/pods/#static-pods to link to https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

**Why is this needed**
This change will help readers to find relevant documentation.

**Comments**
/language en
/triage accepted
/good-first-issue

**Comment by sftim** [comment]
This is a **good first issue**. If you have already worked on an issue for Kubernetes docs, please save this issue for someone who has not.

**Comment by thisisharrsh** [comment]
I would like to work on this issue 

/assign

**Comment by sftim** [comment]
:exclamation: @thisisharrsh please read https://github.com/kubernetes/website/issues/42195#issuecomment-1649491185

**Comment by iconichal** [comment]
I would like to work on this issue 

/assign
