### ISSUE TITLE
Improve styling for consecutive notes

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42196]
**This is a Feature Request**

**What would you like to be added**
Add CSS styling that makes notes look compact, or otherwise improves the presentation, when there is more than one
note right next to each other in the page.

**Why is this needed**
Have a look at https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/

There are three notes. Today they look like:
![screenshot](https://github.com/kubernetes/website/assets/22591623/275949cc-b85f-4ebc-98d2-eb2dbe5b75ff)

I think we can improve on that and make the three notes look like they were planned to be a series. When you pick this up, part of your work is to design what that might look like.

Optionally, we can provide a way for a note to break the series and start a new one. I don't know if we'd ever need that; anyway, it's possible.

**Comments**
CSS has an [adjacent sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator) for selectors. The `:has()` pseudoclass is not yet widely supported, but might help with small tweaks.

/area web-development

**Comment by ArslanYM** [comment]
Is this issue open?

**Comment by sftim** [comment]
> Is this issue open?

Yes: 
![screenshot](https://github.com/kubernetes/website/assets/22591623/811477dd-397e-4d7c-9798-440b355eb39c)

However, we haven't agreed as a SIG that this is accepted for work.
Because Kubernetes is open source, you can still begin an implementation if you'd like to.

**Comment by ArslanYM** [comment]
Sure, I would like to take a stab at this.

**Comment by avdhendra** [comment]
@sftim i would like to work on it can i make a dotted list of note to be appear as they were planned to be in series ?

**Comment by sftim** [comment]
> @sftim i would like to work on it

OK, noted.

> can i make a dotted list of note to be appear as they were planned to be in series ?

You're very welcome to send in a pull request with a proposed fix, we'd love to see how that looks in a preview. Anyone else is welcome too - this is open source.

**Comment by kumarankit999** [comment]
Is anyone working on this.
