### ISSUE TITLE
Rename `codenew` shortcode

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42203]
**This is a Feature Request**

**What would you like to be added**
- Make a new shortcode named `code` that does exactly what `codenew` does
   - _See comments later in the issue about what shortcode name to use_ - eg https://github.com/kubernetes/website/issues/42203#issuecomment-1661715431
- Switch English to use `code` not `codenew`
- Help localizations swap to the new `code` shortcode, on their own timetable

&hellip;time passes&hellip;

- Change the `codenew` shortcode to emit a warning if anyone uses it
- Eventually, drop the `codenew` shortcode

**Why is this needed**
`code` is more obvious than `codenew`, which was introduced to avoid a name collision.

**Comments**
We could use a different name, and maybe we should.

For example, it could be `code_sample` rather than `code`. Or `example_manifest`, given that they are all (?) valid manifests.

**Comment by sftim** [comment]
/area web-development
/priority backlog

If you pick this up, check that it's been triaged as **accepted**. And then please state when you do that you've got the time to see this through all the way to completion. (If you don't have that time, it might be best to leave this to a different contributor).

**Comment by mengjiao-liu** [comment]
/triage accepted
I'm interested in getting it done and having time to do it.
/assign

**Comment by mengjiao-liu** [comment]
> If you pick this up, check that it's been triaged as accepted. 

I'm a little unsure if this can be done immediately or if I need to wait.

**Comment by sftim** [comment]
It's been accepted, work on this is fine!

**Comment by mengjiao-liu** [comment]
Tasks list:
- [x] Make a new shortcode named `code` that does exactly what `codenew` does #42242
- [ ] Switch English to use `code` not `codenew`
- [ ] Help localizations swap to the new code shortcode, on their own timetable

**Comment by sftim** [comment]
It's not too late to switch to `code_sample`, and I agree with the thinking here.

**Comment by sftim** [comment]
Searching for `code file=` is going to work fairly well in terms of switching, if we do, and we have #42327 to guide us as well.

**Comment by andreygoran** [comment]
> Searching for `code file=` is going to work fairly well in terms of switching, if we do, and we have #42327 to guide us as well.

There are things like `# See codenew shortcode`, `use the ``codenew`` shortcode`, and so on that will be easy to miss.

**Comment by sftim** [comment]
(tip: use the second parent commit for https://github.com/kubernetes/website/pull/42327 to find what needs changing over)

**Comment by mengjiao-liu** [comment]
> It's not too late to switch to `code_sample`, and I agree with the thinking here.

I thought the `code` shortcode is easier to remember and use.  Changing it to `code_sample` is also ok. 

Does it need to change?  @sftim @tengqm 

> Searching for code file= is going to work fairly well in terms of switching, if we do, and we have https://github.com/kubernetes/website/pull/42327 to guide us as well.
>> There are things like # See codenew shortcode, use the ``codenew`` shortcode, and so on that will be easy to miss.

There are only a few small areas that need to be changed, and we can submit a PR to follow up. This is not a problem.

**Comment by sftim** [comment]
> It's not too late to switch to `code_sample`, and I agree with the thinking here.

Now, it probably _is_ a bit late.

**Comment by mengjiao-liu** [comment]
Before, I hesitated to change it to code_sample. I can submit a PR today if it is confirmed that it needs to be modified now.

> Now, it probably is a bit late.

It's not too late to switch now, I looked at it and now only zh-cn downstream uses code shortcode.
After the Chinese syncs again, I can remove the code shortcode.

**Comment by mengjiao-liu** [comment]
switch to code_sample: PR https://github.com/kubernetes/website/pull/42703

**Comment by sftim** [comment]
In progress, I think.
/triage accepted

**Comment by sftim** [comment]
(done for English; let's close it as done and let localizations catch up over the next _n_ years)

/close
