### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by prashanthkori** [kubernetes/website#4220]
drupal deploy documentation using kubernetes

**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by Aut0R3V** [comment]
Hey anything that can be done here?

**Comment by sftim** [comment]
/kind support
I think

@prashanthkori I think you were asking for a guide to deploying Drupal with Kubernetes. We'd expect to see that documentation added to the Drupal website, or published elsewhere.

If I guessed wrongly, feel free to reopen this issue and clarify what you were asking for.
/close
