### ISSUE TITLE
ConfigMap concept mentions generally available feature gate as if it's optional

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42228]
The feature gate "ImmutableEphemeralVolumes" is among the [removed features](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), so now there's no way to switch it — it's always on.
> https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

**Comment by thisisharrsh** [comment]
Hi @nnlkcncff, please share the details on the issue you would like to report or the assistance you require in the [description ](https://github.com/kubernetes/website/issues/42228#issue-1822312678)section?

**Comment by nnlkcncff** [comment]
Thanks, but I don't need any help on how to use this function. The problem is that this function is mentioned in the documentation, but it not exists anymore.

It says:
> This feature is controlled by the ImmutableEphemeralVolumes feature gate. 

But now there is no any way to control it. It looks like it shouldn’t be mentioned on [this page section](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable).

**Comment by sftim** [comment]
/retitle ConfigMap concept mentions generally available feature gate as if it's optional

/triage accepted
/priority backlog
/help

**Comment by pegasas** [comment]
Hi, @sftim , @nnlkcncff , @sftim , 
I would like to fix this, 
Would you please assign me this task?

**Comment by pegasas** [comment]
Hi, @sftim , @nnlkcncff , @sftim ,
I create a PR for fixing this. 

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/
![image](https://github.com/kubernetes/website/assets/13224827/8d4fc9ba-0fe8-423e-9b77-4822a9e55437)

It seems this feature is always true now. So it is not optional.
So I remove all related description.

**Comment by pegasas** [comment]
PR https://github.com/kubernetes/website/pull/42253#event-10017078104 has been merged.
request to close the issue.
/close
