### ISSUE TITLE
Taints and Tolerations: When is noexecute taint added to the node

### ISSUE THREAD

**Issue by aritraghosh** [kubernetes/website#42237]
Its not clear from this doc when the taint for the node NoExecute is added. What are the scenarios when the NoExecute taint is added to the node

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition

**Comment by Ritikaa96** [comment]
> **It definitely is added when the node is not ready,** what other conditions is the taint to the node added and not for Memory Pressure.

You can definitely add the taint to the node while it is running and is ready. Reference given in the concepts section
> You add a taint to a node using [kubectl taint](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#taint). 


Please note that `NoExecute` is a _taint effect_ technically.

**Comment by Ritikaa96** [comment]
Regarding Taint-by-Condition,
a list of other conditions that let node controller add taint to nodes has been given [here](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions)

However, I think you want the taints to be explained like `node.kubernetes.io/memory-pressure` has been explained.
In Taint-based-Eviction, `node.kubernetes.io/unreachable` is also explained just the same.

More clarification on the request might be helpful.

**Comment by aritraghosh** [comment]
Updated the question,  The article mentions the list of node taints available. I am looking for when the NoExecute taint is added by the node controller (the scenarios)

**Comment by Ritikaa96** [comment]
`NoExecute` is added to the node, in general, when an already present pod needs to be evicted.
A few examples are:
> In case a node is to be drained, the node controller or the kubelet adds relevant taints with the NoExecute effect. If the fault condition returns to normal the kubelet or node controller can remove the relevant taint(s).
> When the node is not ready and taint the taint `node.kubernetes.io/not-ready` with effect NoExecute is added
> When the node is unreachable, Network is unavailable , apart from memory-pressure , disk and pid pressure also can have NOExecute added to the node.


I think explaining certain scenarios like the one explained for `NoSchedule` can clear this taint effect uses. There is certainly scope for some additions.
I'd wait for the sig/scheduling and sig/node people to share their expertise. or opinion on the addition of more relevant examples for Noexecute.

> I am looking for when the NoExecute taint is added by the node controller (the scenarios)

BTW The eg. in Taint based evictions are all going to add `NoExecute`.

**Comment by aritraghosh** [comment]
Thanks, I am closing the issue. I wasn't sure about the MemoryPressure Node scenario. Reading the documentation, it seemed to me that it should have the _NoExecute_ taint but I didn't see it on the node
