### ISSUE TITLE
incorrect link Installing Kubernetes with kOps

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#42248]
**This is a Bug Report**

**Page Link** : https://kubernetes.io/docs/setup/production-environment/tools/kops/

 Incorrect Link in[ Whats Next](https://kubernetes.io/docs/setup/production-environment/tools/kops/#what-s-next) 
At Point
Follow kOps community discussions on Slack: [community discussions.](https://github.com/kubernetes/kops#other-ways-to-communicate-with-the-contributors)

**What would you like to be added**
Change Link :https://github.com/kubernetes/kops#other-ways-to-communicate-with-the-contributors to https://kubernetes.slack.com/archives/C3QUFP0QM

**Why is this needed**
This change will help readers to find relevant Slack Channel

**Comment by AmarNathChary** [comment]
I would like to work on this issue
/assign

**Comment by AmarNathChary** [comment]
Raised PR in  #42295

**Comment by utkarsh-singh1** [comment]
Hi @nikhilchauhangithub, Please try to look for the Assignees list before assigning any issue to yourself.

**Comment by AmarNathChary** [comment]
/close
As the issue is solved.
