### ISSUE TITLE
"Network Policies" page references the usage of a deprecated feature gate `NamespaceDefaultLabelName`

### ISSUE THREAD

**Issue by GavBurke** [kubernetes/website#42247]
NamespaceDefaultLabelName is missing from the list of feature gates, which https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-namespace-by-its-name suggests should have existed since 1.22

**Comment by T-Lakshmi** [comment]
/sig docs
/language en
page to update: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by dipesh-rawat** [comment]
It looks like the feature gate `NamespaceDefaultLabelName` has been removed as described on this page:
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

**Comment by GavBurke** [comment]
> It looks like the feature gate `NamespaceDefaultLabelName` has been removed as described on this page: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

Ah okay, so then I'll need to amend the issue to be with https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-namespace-by-its-name instead ;)

**Comment by T-Lakshmi** [comment]
As the feature gate `NamespaceDefaultLabelName` is removed as per [feature-gates-removed](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/), we should update the Feature state in [targeting-a-namespace-by-its-name](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-namespace-by-its-name).

**Comment by dipesh-rawat** [comment]
/retitle "Network Policies" page references the usage of a deprecated feature gate `NamespaceDefaultLabelName`

**Comment by aj11anuj** [comment]
Issue is fixed now
/close
