### ISSUE TITLE
Improvement for k8s.io/docs/reference/kubectl/jsonpath/

### ISSUE THREAD

**Issue by petarDenevFlutterint** [kubernetes/website#42251]
Last paragraph, last code example should be 

```
# The following command achieves the desired result
kubectl get pods -o json | jq -r '.items[] | select(.metadata.name | test("test-")).metadata.name'
```
in the first example the result is the `metadata.name` in the second now it is `.spec.containers[].image`

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/reference/kubectl/jsonpath/
/language en
