### ISSUE TITLE
"Ephemeral Volumes" page references the usage of a deprecated feature gate `GenericEphemeralVolume`

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42259]
It is quite unclear from [the text](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#security) that the feature "GenericEphemeralVolume" is a feature gate because its design does not follow the guideline. The following steps should be done:
 - write the feature gate name as inline code, e.g. `GenericEphemeralVolume`
 - change the wording from "feature" to "feature gate"

Also there is no information about the components on which this feature gate can be enabled.

But! This feature gate is only in [the list of removed ones](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/). Looks like it's not a feature gate now. Consider removing it from the page.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/
/language en

**Comment by dipesh-rawat** [comment]
/retitle "Ephemeral Volumes" page references the usage of a deprecated feature gate `GenericEphemeralVolume`

**Comment by mengjiao-liu** [comment]
`GenericEphemeralVolume` feature gate has been removed in https://github.com/kubernetes/kubernetes/pull/109435, the text needs to be updated.
