### ISSUE TITLE
Improve 'ConfigMaps' page with examples for querying specific fields and handling multiline entries

### ISSUE THREAD

**Issue by daddy-joseph97** [kubernetes/website#42257]
If it is possible to query specific fields form a configmap then please provide a few non-trivial "hello world" examples (more complex pathing). It would also be helpful to include working with multiline entries and any "gotchas" and "oh yeah, make sure you do ..." points to make use of the experiences of others.

**Comment by dipesh-rawat** [comment]
_Page relate to issue:_ https://kubernetes.io/docs/concepts/configuration/configmap/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Improve 'ConfigMaps' page with examples for querying specific fields and handling multiline entries
