### ISSUE TITLE
Document `cluster-info` ConfigMap; document cluster CA Certificate renewal

### ISSUE THREAD

**Issue by daddy-joseph97** [kubernetes/website#42258]
I haven't seen anywhere if a tool updates cluster-info. In fact, 'cluster-info' seems magical and undocumented so that after days of failure in adding a non-master worker node I eventually found a kind soul who knew of the problem. Please graciously consider documenting this apparently critical file along with the `kubectl join` documentation and also including here in the info regarding renewing the cluster CA and other certificates.

**Comment by dipesh-rawat** [comment]
_Page initially included as part of issue:_ https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Document 'cluster-info' and Cluster CA Certificate renewal

**Comment by neolit123** [comment]
> I haven't seen anywhere if a tool updates cluster-info. In fact, 'cluster-info' seems magical and undocumented so that after days of failure in adding a non-master worker node I eventually found a kind soul who knew of the problem. Please graciously consider documenting this apparently critical file along with the kubectl join documentation and also including here in the info regarding renewing the cluster CA and other certificates.

`cluster-info` is actually not kubeadm specific. same goes for bootstrap tokens.
note that most users don't need to know it exists.
it is not clear what failures you had exactly, but overall i do not object to have more information about cluster-info at k/website.

the configmap is documented here:
https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/

this page has cluster-info CA rotation mentioned:
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

this page can include a basic note that kubeadm uses cluster-info for bootstrap with bootstrap tokens.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/

similar note can be added here:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

**Comment by neolit123** [comment]
> _Page initially included as part of issue:_ https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/ /language en

maybe we shouldn't update this page.

**Comment by neolit123** [comment]
/sig auth cluster-lifecycle

@daddy-joseph97 if you are willing to send a PR, help is appreciated.

**Comment by Gauravpadam** [comment]
> > I haven't seen anywhere if a tool updates cluster-info. In fact, 'cluster-info' seems magical and undocumented so that after days of failure in adding a non-master worker node I eventually found a kind soul who knew of the problem. Please graciously consider documenting this apparently critical file along with the kubectl join documentation and also including here in the info regarding renewing the cluster CA and other certificates.
> 
> `cluster-info` is actually not kubeadm specific. same goes for bootstrap tokens. note that most users don't need to know it exists. it is not clear what failures you had exactly, but overall i do not object to have more information about cluster-info at k/website.
> 
> the configmap is documented here: https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/
> 
> this page has cluster-info CA rotation mentioned: https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/
> 
> this page can include a basic note that kubeadm uses cluster-info for bootstrap with bootstrap tokens. https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/
> 
> similar note can be added here: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

Hello,
I'd like to assign this issue to myself , I'll add the note to the links as mentioned above

**Comment by sftim** [comment]
Issue #30575 covers the process for updating TLS certificates and keys (not yet documented)

We ie, you) could update this issue to describe what to document around `cluster-info` @daddy-joseph97; would that suit you?

**Comment by sftim** [comment]
/retitle Document `cluster-info` ConfigMap; document cluster CA Certificate renewal

**Comment by stlaz** [comment]
/close

The configmap appears to be documented in https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/#configmap-signing.
Since the reporter did not reply about what exactly they would like improved, I'm closing this issue.
