### ISSUE TITLE
Chinese link in the English docs to "Overview of Cloud Native Security: Cloud provider security"

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42285]
> https://kubernetes.io/docs/concepts/security/overview/#cloud-provider-security
> | Huawei Cloud | https://www.huaweicloud.com/securecenter/overallsafety |
> | ------------ | ------------------------------------------------------ |

<br>

Consider using the English-language version of the link for Huawei Cloud:
https://www.huaweicloud.com/intl/en-us/securecenter/overallsafety

The current link is Chinese.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/security/overview/
/language en

**Comment by sftim** [comment]
Anyone is welcome to work on this. @bogarams, it sounds like you plan to open a pull request?

(other contributors: it's polite to try to liaise with @bogarams ahead of starting work)

**Comment by bogarams** [comment]
@sftim , yes i would like to work on this and going to open a pull request.

**Comment by PRYNSH1224** [comment]
Hey Please assign this issue to me, I am a new contributor

**Comment by sftim** [comment]
Anyone is welcome to work on this.

(it's polite to try to liaise with contributors who've previously expressed an interest in working on this, and ideally to consider collaborating)

**Comment by bogarams** [comment]
> /assign

 @deepak4566 ,  Kindly next time liaise with previous assigned user first before you assign youself and start work. This will show some courtesy.
