### ISSUE TITLE
Deploying dashboard UI yaml URL returns HTTP 404 error

### ISSUE THREAD

**Issue by guoyq** [kubernetes/website#42280]
"kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml"

the link - https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml - is no longer valid/exist. 404 error.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Deploying dashboard UI yaml URL returns HTTP 404 error

**Comment by dipesh-rawat** [comment]
Hi @guoyq, I tested the command, and it's functioning as expected from my end _(See below)_. Maybe you could take a look to ensure that the issue isn't related to your local network setup.

```console
> $ kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
namespace/kubernetes-dashboard created
serviceaccount/kubernetes-dashboard created
service/kubernetes-dashboard created
secret/kubernetes-dashboard-certs created
secret/kubernetes-dashboard-csrf created
secret/kubernetes-dashboard-key-holder created
configmap/kubernetes-dashboard-settings created
role.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
deployment.apps/kubernetes-dashboard created
service/dashboard-metrics-scraper created
deployment.apps/dashboard-metrics-scraper created
```

/triage not-reproducible

**Comment by dipesh-rawat** [comment]
/close not-planned

Not reproducible (Refer https://github.com/kubernetes/website/issues/42280#issuecomment-1656461611)
You are welcome to reopen this (or create an new issue) and add details.

**Comment by dipesh-rawat** [comment]
/close not-planned

You are welcome to reopen this (or create an new issue) and add details.
