### ISSUE TITLE
Confusing docs about `--cloud-provider` command line argument for Kubernetes components

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#42309]
**What would you like to be added**
Update [k8s doc](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/) with  mention of `--cloud-provider=external` flag use case under [running-cloud-controller-manager](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager)
**Note:** If the user has external CCMs then they  wants to use this flag.

**Why is this needed**
[Running-cloud-controller manager](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager) is saying that `kube-apiserver and kube-controller-manager MUST NOT specify the --cloud-provider flag. This ensures that it does not run any cloud specific loops that would be run by cloud controller manager.` 

But https://cloud-provider-aws.sigs.k8s.io/getting_started/ mention 
```
Add the --cloud-provider=external to the kube-controller-manager config.
Add the --cloud-provider=external to the kube apiserver config.
Add the --cloud-provider=external to each the kubelet's config.
```
There is a subtle difference between not setting the flag and setting it to --cloud-provider=external, It is good if we make it clear when to use it or not.
**Comments**
Page to update: https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

**Comment by T-Lakshmi** [comment]
If triage accepts i can open PR for it.
/assign

**Comment by sftim** [comment]
/retitle Confusing docs about `--cloud-provider` command line argument for Kubernetes components
/sig cloud-provider
/kind bug
/remove-kind feature

**Comment by sftim** [comment]
FWIW, I don't think https://cloud-provider-aws.sigs.k8s.io/getting_started/ is giving accurate advice either.

**Comment by T-Lakshmi** [comment]
Hi @sftim,
I have verified with another cloud provider docs and this command line argument is varying from one to another cloud-provider.
for Ex., 
In [k8s.io](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager), kube-apiserver and kube-controller-manager **MUST NOT specify** and for kubelet **must specify** it.  
In [Aws](https://cloud-provider-aws.sigs.k8s.io/getting_started/), It mention that all three components(kube-apiserver, kube-controller-manager, kubelet) need to specify the argument.
In [Azure](https://cloud-provider-azure.sigs.k8s.io/install/azure-ccm/#deployment),  kube-controller-manager, kubelet should specify and kube-apiservermust should not run it.

I'm not sure which of these documents is correct or whether none of them are correct, if any of them are incorrect, we can raise a request to remove the inaccuracy doc. Otherwise, we can clarify in the [official documentation](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager) with a note stating that,
>  Note: `--cloud-provider `argument usage varies depending on the cloud-provider, please check the relevant official docs for further information.

Can you suggest how we should proceed?

**Comment by sftim** [comment]
SIG Cloud Provider: what is that good practice?

**Comment by T-Lakshmi** [comment]
> In [Azure](https://cloud-provider-azure.sigs.k8s.io/install/azure-ccm/#deployment), kube-controller-manager, kubelet should specify and kube-apiserver should not run it.


In the following example, `"--cloud-provider=external"` is set in  **kube-apiserver.yaml** and **kubelet.manifest** files, and `"--cloud-provider=azure"` is set in **cloud-controller-manager.yaml** file.
https://github.com/kubernetes-sigs/cloud-provider-azure/tree/master/examples/out-of-tree

**Comment by elmiko** [comment]
> SIG Cloud Provider: what is that good practice?

when using CCMs (not the internal cloud controller loops in the KCM) then the user should set `--cloud-provider=external`.

**Comment by T-Lakshmi** [comment]
@elmiko,
Thank you for sharing your valuable feedback, and also as discussed let's have a discussion on this in SIG Cloud Provider next meeting to follow our SIG practice.

@sftim,
WDYT on it?

**Comment by T-Lakshmi** [comment]
PR open for this #43010.
