### ISSUE TITLE
Add more information about ephemeral containers and security restrictions

### ISSUE THREAD

**Issue by bjoernmartin** [kubernetes/website#42319]
A section in the documentation for ephemeral containers (see https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) regarding security aspects would be great. A colleague tried to use it but gets `forbidden`, possibly because the cluster's security policies do not allow him to use an ephemeral container. But we actually do not know. 😉 So having this topic covered within the standard docs would be helpful I think.

**Comment by thisisharrsh** [comment]
_page related to the issue: https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/_
/language en

**Comment by thisisharrsh** [comment]
/retitle Adding a section on Security Aspects in the Ephemeral Containers
/sig docs

**Comment by sftim** [comment]
/retitle Add more information about ephemeral containers and security restrictions
/sig node security

**Comment by deepak4566** [comment]
@sftim I have raised pr for this  and u can check it out

**Comment by deepak4566** [comment]
Need any collaborator to contribute to my PR ? #42357 there are some suggestions made by reviewers about indentation and grammer

**Comment by sftim** [comment]
> @sftim I have raised pr for this and u can check it out

Taking a look now.
