### ISSUE TITLE
community page has horizontal scrolling

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#42314]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/community/
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/community/

/assign

**Comment by dipesh-rawat** [comment]
During my browsing of the docs on a mobile device, I came across a similar situation on another page, specifically in the [Node-pressure Eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/). It seems this issue might be widespread and could be affecting multiple pages, not limited to just the community page.

Perhaps we could explore identifying a CSS fix that enhances the rendering of pages with wider elements. This way, we can efficiently resolve the problem and improve the overall user experience.

**Comment by Gauravpadam** [comment]
I tried making some changes on the source, A simple overflow - x in the right places seems to solve the problem.

![image](https://github.com/kubernetes/website/assets/12787482/0ec861fc-295f-4c19-82df-d0af9ff92807)

However, I'd often come across such problems when the scaling isn't managed properly. I'm sure there are better ways to get this problem fixed.
When can this issue be worked upon? I'd like to contribute.

**Comment by Gauravpadam** [comment]
> During my browsing of the docs on a mobile device, I came across a similar situation on another page, specifically in the [Node-pressure Eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/). It seems this issue might be widespread and could be affecting multiple pages, not limited to just the community page.
> 
> Perhaps we could explore identifying a CSS fix that enhances the rendering of pages with wider elements. This way, we can efficiently resolve the problem and improve the overall user experience.

I see, In that case I'll try to find anymore pages that might be having the same issue.

**Comment by aj11anuj** [comment]
Similar issue is present in Booking.com case study [page](https://kubernetes.io/case-studies/booking-com/)
