### ISSUE TITLE
Improvement for k8s.io/zh-cn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by Yonggie** [kubernetes/website#42345]
I'm sorry but this tutorial on the website does not provide any detail about the commands or operations on creating a cluster, not even a simple cluster with 3 nodes. It just describes how a cluster should be and what roles they play, which is not enough for a tutorial...

Is it possible we could add more details?

**Comment by tengqm** [comment]
There are maybe a hundred different ways to set up a cluster, and we simply cannot afford to to document them all.
The officially documented way is to set up a cluster using kubeadm (https://kubernetes.io/zh-cn/docs/reference/setup-tools/kubeadm/). Is this what you are looking for?
Please close this issue if the docs meet your needs.

**Comment by tengqm** [comment]
There are maybe a hundred different ways to set up a cluster, and we simply cannot afford to to document them all.
The officially documented way is to set up a cluster using kubeadm (https://kubernetes.io/zh-cn/docs/reference/setup-tools/kubeadm/). Is this what you are looking for?
Please close this issue if the docs meet your needs.

**Comment by Yonggie** [comment]
Thanks for the reply. It would be nice if the community put the link onto the ["create the cluster" toturial page](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) so that the beginners know there's at least an official way to follow.
