### ISSUE TITLE
Seeking clarification on livenessProbe failure: Graceful termination or Immediate SIGKILL

### ISSUE THREAD

**Issue by gblair** [kubernetes/website#42360]
We're trying to learn what happens to a pod when a `livenessProbe` fails. The doc page on "Pod Lifecycle" is really great and provides very detailed info on most aspects of the pod lifecycle, but we found a gap we're seeking to learn about. For `livenessProbe`, we have:

> Indicates whether the container is running. If the liveness probe fails, the kubelet kills the container, and the container is subjected to its [restart policy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy). If a container does not provide a liveness probe, the default state is Success.

What we want to know from this paragraph is: Will the `SIGTERM` + `gracePeriodSeconds` + `SIGKILL` will be used in this case, or will `SIGKILL` be sent immediately?

**Comment by dipesh-rawat** [comment]
_Page mentioned in the issue:_ https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Seeking clarification on livenessProbe failure: Graceful termination or Immediate SIGKILL
/sig node

**Comment by aritraghosh** [comment]
More details here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#probe-level-terminationgraceperiodseconds

Happy to add about it on the pod lifecycle page

**Comment by gblair** [comment]
Thank you! That seems very clear already -- maybe a link from that section of the pod lifecycle page would be a good improvement.
