### ISSUE TITLE
Assigning PVs to perticular Storage class 

### ISSUE THREAD

**Issue by rishavkankane** [kubernetes/website#42363]
I am trying to use the existing Persistent volume to a storage class but i am  unable to do it.
My question is .
Is it possible to use the existing PV to any one storage class?

Proposed Solution
Must have proper reason.

**Comment by tamilselvan1102** [comment]
Are you trying to attach another PVC to an existing PV? If so then that is not possible.

**Comment by niranjandarshann** [comment]
@rishavkankane , Yes you can use the existing PV to any perticular storage class by editting the storageclass name field in it.

**Comment by rishavkankane** [comment]
> @rishavkankane , Yes you can use the existing PV to any perticular storage class by editting the storageclass name field in it.

@niranjandarshann  Thank you, but yes i have editted the storageclass name field to it. but still i am facing the error. I think i am missing something.

**Comment by niranjandarshann** [comment]
> > @rishavkankane , Yes you can use the existing PV to any perticular storage class by editting the storageclass name field in it.
> 
> @niranjandarshann Thank you, but yes i have editted the storageclass name field to it. but still i am facing the error. I think i am missing something.

@rishavkankane  editing the Storageclass name is not only the solution you need to edit appropiate PV Object. Hope this will solve your problem.

**Comment by rishavkankane** [comment]
@niranjandarshann  I want to express my gratitude for your help and support today. This is what i was looking for and got the solution. Spend some days in finding the solution but not getting the correct reason for it. Now on Community i get the correct reason. Thank You Its  Means alot in my project work.

**Comment by rishavkankane** [comment]
marking it as resolved. Closing this issue.
Thanks to all Contributor.
/close
