### ISSUE TITLE
Pod Lifecycle concept unclear about `preStop` hook execution ordering

### ISSUE THREAD

**Issue by pettermahlen** [kubernetes/website#42372]
I would have liked to be able to know if preStop hooks are executed in parallel or sequentially if multiple containers define them. This text suggests that they are executed in parallel, but it's not explicit. 

```Note: The containers in the Pod receive the TERM signal at different times and in an arbitrary order. If the order of shutdowns matters, consider using a preStop hook to synchronize.```

**Comment by thisisharrsh** [comment]
Hi @pettermahlen, the kubernetes documentation does not clearly states whether `preStop` hooks are executed in parallel or in the sequential manner. But the fact that `pod receives the TERM signals at different times` suggests that `preStop` executed in the parallel order.

**Comment by thisisharrsh** [comment]
_page related to the issue: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination_

**Comment by pettermahlen** [comment]
@thisisharrsh Right, that's what I said in the ticket. It would be better to be clear about it rather than make readers try to figure out what that text means. Also, the current text is open to different interpretations. The 'at different times' bit can also mean that the order of execution of preStop hooks is non-deterministic, but still sequential.

**Comment by sftim** [comment]
/retitle Pod Lifecycle concept unclear about `preStop` hook execution ordering
