### ISSUE TITLE
Move node status doc into reference section

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42374]
**This is a Feature Request**

**What would you like to be added**
Take the section https://kubernetes.io/docs/concepts/architecture/nodes/#node-status and move it to become https://kubernetes.io/docs/reference/node/status/

Add hyperlinks liberally so that the information is easy to find, and make sure that https://kubernetes.io/docs/concepts/architecture/nodes/#node-status remains as a stub section with a link to the new page.

**Why is this needed**
https://kubernetes.io/docs/concepts/architecture/nodes/ is one of the first pages a newcomer may read (potentially, only 6 clicks into our website).
It's quite complicated for a page where we the reader may be really quite new to Kubernetes.

**Comments**
/language en
/sig docs

**Comment by sftim** [comment]
/priority backlog

If working on this, add the “refactor” label to your PR (or ask a reviewer to add it for you).

**Comment by dipesh-rawat** [comment]
I think this change will be benefit newcomers to Kubernetes who might initially find the current section on the page to be complex and overwhelming.

/triage accepted

**Comment by aritraghosh** [comment]
fixes #42378

**Comment by sftim** [comment]
This issue doesn't fix https://github.com/kubernetes/website/pull/42378, because it's an _issue_

(pull requests sometimes do fix issues, but filing one issue never fixes another issue)
