### ISSUE TITLE
Obsolete online interactive tutorial in the "Configuring a Java Microservice" page

### ISSUE THREAD

**Issue by dishant-kapadiya** [kubernetes/website#42401]
There is no tutorial for this anymore given the deprecation of Katacode. Please remove this page.

**Comment by dipesh-rawat** [comment]
_Pages related to issue:_ [https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/](https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/#example-externalizing-config-using-microprofile-configmaps-and-secrets) ,  https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Obsolete online interactive tutorial in the "Configuring a Java Microservice" page
/kind bug

**Comment by dipesh-rawat** [comment]
Given that the online Katacoda interactive tutorial is no longer accessible, I think that we should remove the link to the interactive tutorial and enhance the [tutorial page](https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/) by providing instructions for users on how to run the tutorial on their local systems.

/triage accepted
/priority backlog

**Comment by gavksingh** [comment]
Hi @dipesh-rawat @dishantkapadiya2694 , can you guide me finding this page path? after cloning the project I can't find the  path in code editor. I want to work on this issue and completely new to the project.

**Comment by T-Lakshmi** [comment]
Hi @gavksingh,
Below mentioned is the file path:
`/website/edit/main/content/en/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice.md`

**Comment by T-Lakshmi** [comment]
@gavksingh , below are some links that may help you to start in contributing for Kubernetes.

https://www.kubernetes.dev/docs/guide/#contributor-guide
https://kubernetes.io/docs/contribute/
https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md

**Comment by gavksingh** [comment]
Thank you @T-Lakshmi for the help.

**Comment by sandy-krishna-ai** [comment]
https://github.com/kubernetes/website/pull/42491

**Comment by divya-mohan0209** [comment]
Hello folks, thank you for bringing this up!

The link you all are trying to drop is from a tutorial page itself, which in turn, redirects to another tutorial page that is interactive in nature.

Removal of the interactive tutorial section will not benefit this page UNLESS somebody is willing to rewrite the whole page to remove all mentions of the interactive tutorial in it & make the overall text seem sensible.

If that seems like something you want to attempt, I'd be happy to see those changes suggested over a PR.

But the changes to just remove the section as a quick fix will not fit the flow of the document, IMO.

**Comment by kancherlanagaraju** [comment]
Yes, both looks similar. Is there any one working on this doc update otherwise someone assign that to me. thanks

**Comment by sftim** [comment]
I recommend deleting this entire tutorial, which has not been maintained in some time.
