### ISSUE TITLE
Need assistance in running "Deploying WordPress and MySQL with Persistent Volumes" tutorial

### ISSUE THREAD

**Issue by Rishikesh-Sarma** [kubernetes/website#42416]
The wordpress doesn't start. It show "error connecting to database connection" as per the steps.
Please help.

**Comment by Rishikesh-Sarma** [comment]
I tried to follow the steps in the kubernetes.io link. 
Do I need to change the wp-config.php file and mount it as a configmap?
Do I then need to change permissions on the imported configmap?

**Comment by utkarsh-singh1** [comment]
Hi @Rishikesh-Sarma, I have followed the tutorial and can get the desired result.

**Comment by Rishikesh-Sarma** [comment]
Did you get the same with Nodeport service or load balancer?
Also, are you trying on public cloud infrastructure or on-premise cluster?

**Comment by utkarsh-singh1** [comment]
@Rishikesh-Sarma, I have used local Kubernetes cluster using minikube, did you create your cluster using minikube or kubeadm.

**Comment by Rishikesh-Sarma** [comment]
I used:
>kubeadm
>Created PV and PVC from NFS export file system.
>NodePort as service.

But I was getting an error as "Error connecting to database connection". I then changed some settings in wp-config.php and imported it as a configmap but still no go.

Will the document not work for kubeadm setup?

**Comment by utkarsh-singh1** [comment]
I don't think so because before the tutorial it clearly states that →

>You need to have a Kubernetes cluster, and the kubectl command-line tool must be configured to communicate with your cluster. It is recommended to run this tutorial on a cluster with at least two nodes that are not acting as control plane hosts.  it clearly states - 

>

**Comment by Rishikesh-Sarma** [comment]
Wordpress file:
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.1.2-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass          # generated before in secret.yml
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: "/var/www/html"          # which data will be stored
        volumeMounts:
        - name: data
          mountPath: /var/www/html/wp-config.php
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-persistent-storage


--------------------------------------------------------------------------------------------

Mysql file:

apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql   # will be used as a value in
  labels:                 # WORDPRESS_DB_HOST in wordpress-deploy.yml
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion:  apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass        # the one generated before in secret.yml
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mysql-pass
            key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage  # which data will be stored
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-persistent-storage    # PVC
        persistentVolumeClaim:
          claimName: mysql-persistent-storage


I am using a three node clutser. There is 1 control plane node and 2 worker nodes.

I am new to kubernetes. So any help would be highly appreciated.

**Comment by Rishikesh-Sarma** [comment]
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

------------------------------------------------------------------------------------------------------------------------------------


apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim


Note that: I used NodePort.

All pods, services are up but when I give <Worker IP>:<Nodeport> it says "Error establishing a database connection".

Please help.

**Comment by dipesh-rawat** [comment]
/retitle Need assistance in running "Deploying WordPress and MySQL with Persistent Volumes" tutorial
/kind support

**Comment by Rishikesh-Sarma** [comment]
As the above config is not working, I created a config map to copy the wp-config.php to the wordpress pod. But I think the issue is that it gets created with root:root and not www-data:www-data.

Can somebody help to let me know how to change the ownership of file copied as configmap to a pod?

**Comment by niranjandarshann** [comment]
There is no any activity in the issue from the long time so I am closing this issue. You may reopen it if you find it useful and want to work on it so you may reopen it.

**Comment by niranjandarshann** [comment]
closing this issue
/close
