### ISSUE TITLE
Query about page Utilizing the NUMA-aware Memory Manager

### ISSUE THREAD

**Issue by seavershi** [kubernetes/website#42418]
Our application is a high-performance software which needs NUMA aware huge pages. But:
"the Memory Manager ensures that the memory which a pod requests is allocated from a minimum number of NUMA nodes."
Then if we cannot remove huge pages management of Kubernetes, how can we request the huge pages distributed cross NUMA nodes evenly?
In CPU manager, it can allocate the CPU distributed cross NUMA nodes evenly. Since the huge pages are related to NUMA nodes, it should has a method to allocate the huge pages distributed cross NUMA nodes evenly.

**Comment by utkarsh-singh1** [comment]
This issue seems similar to #42417 

/triage duplicate

**Comment by utkarsh-singh1** [comment]
Hi @seavershi, this issue is similar to #42417, please close one of the two as there is no need of 2 different issues with same query.

**Comment by utkarsh-singh1** [comment]
Relayed page - https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/

/language en
/sig docs

**Comment by sftim** [comment]
/retitle Query about page Utilizing the NUMA-aware Memory Manager
/kind support

/close not-planned
