### ISSUE TITLE
Update documentation to reflect that DefaultStorageClass has been enabled by default for a long time

### ISSUE THREAD

**Issue by Nuru** [kubernetes/website#42413]
I believe [this page](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) in particular needs significant changes with respect to the `DefaultStorageClass` admission controller. In particular, it is now enabled by default in all currently supported versions of Kubernetes, so statements such as:

> To enable dynamic storage provisioning based on storage class, the cluster administrator needs to enable the `DefaultStorageClass` [admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass) on the API server.

Is misleading at best, because the cluster administrator does not need to do anything to enable the admission controller. 

Several other sections documenting the difference between having the `DefaultStorageClass` admission controller enabled and disabled should be rewritten to reflect the default status of it being enabled. 

Possibly other pages need similar updates.

**Page to Update:**

https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**References:**

- #42288
- #42177 and https://github.com/kubernetes/website/pull/42177#issuecomment-1666822625
- #42176

**Comment by tamilselvan1102** [comment]
When you create a PersistentVolumeClaim, you can specify a StorageClass that provides information about how the storage will be provisioned. If you don't specify a StorageClass, then the default StorageClass gets used.

In case of dynamic storage provisioning admin need to create a storage class for users https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#enabling-dynamic-provisioning
