### ISSUE TITLE
[hi] Localize kubernetes.io/community/ in Hindi

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/website#42435]
**This is a Feature Request**

We Can add a Kubernetes Community Section in Hindi, as it is regulated in all other languages.

**What would you like to be added**
We can Create a Community section in Kubernetes in Hindi, which will be also inspired by Kubernetes English Section

**Why is this needed**
To Understand better the Kubernetes Community for Hindi Speaking Folks

**Comments**

**Comment by thisisharrsh** [comment]
_page related to the issue: https://kubernetes.io/community/_
/language hi

**Comment by dipesh-rawat** [comment]
This looks like a duplicate of #39497

/triage duplicate

**Comment by divya-mohan0209** [comment]
I'll be closing this off @kumarankit999 since this is a duplicate issue. Kindly consider working off the original issue mentioned by Dipesh above, if you're interested 

/close
