### ISSUE TITLE
Stale advice on changing the Container Runtime on a Node from Docker Engine to containerd

### ISSUE THREAD

**Issue by seanburke-hpe** [kubernetes/website#42442]
Regarding the advice

> Edit the file /var/lib/kubelet/kubeadm-flags.env and add the containerd runtime to the flags; --container-runtime-endpoint=unix:///run/containerd/containerd.sock

At least in Kubernetes version 1.22, it is also necessary to add the flag `--container-runtime=remote`

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/
/language en

**Comment by sftim** [comment]
https://v1-22.docs.kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/ no longer exists, but https://v1-23.docs.kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/ gives advice that might be relevant.

I don't think there's anything to fix. Work to improve https://github.com/kubernetes/website/issues/12303 (long term issue) would be lovely, but that's not a trivial thing to fix.

**Comment by sftim** [comment]
/retitle Advice on changing the Container Runtime on a Node from Docker Engine to containerd

**Comment by sftim** [comment]
Actually, there _is_ something wrong: https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd/ says that the advice applies to people running Kubernetes v1.23 or earlier.

We should change that page to make things clear!

**Comment by sftim** [comment]
/triage accepted
/retitle Stale advice on changing the Container Runtime on a Node from Docker Engine to containerd

/priority important-longterm
/language en
/help

**Comment by pegasas** [comment]
/assign @pegasas 
I make some digging, it seems `` affects k8s until 1.27. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md?plain=1#L1329

**Comment by pegasas** [comment]
/close

This should be fixed by #42739.

feel free to reopen this issue if there is any concern.
