### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by bmcguirk** [kubernetes/website#4245]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Tutorial 6 wipes out the deployments and pods used in previous sections of the tutorial. 

**Proposed Solution:**
Reload the virtual machine with the previous resources? 

**Page to Update:**
k8s.io/docs/tutorials/kubernetes-basics/update-interactive/

**Comment by BenHall** [comment]
Thanks for the feedback. This is by design with every scenario designed as a standalone tutorial.

It would be great to know what the benefits of having the previous resources available would be?
