### ISSUE TITLE
Document autogeneration for metrics reference

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42453]
**This is a Feature Request**

**What would you like to be added**
Add a section to https://kubernetes.io/docs/contribute/generate-ref-docs/ that explains how to keep the generated pages within https://kubernetes.io/docs/reference/instrumentation/ up to date.

**Why is this needed**

https://github.com/kubernetes/kubernetes/pull/113343 added docs generation code into [k/k](https://github.com/kubernetes/kubernetes). We can tweak that code and then rely upon it.
We'd want (I'm reasonably sure) to document what needs to happen for each major release so that we can keep the reference document up to date.

https://github.com/kubernetes/website/pull/37522 got close to doing what we need, so this issue is about staffing the work to take it that last stretch to being mergeable.

**Comments**
/sig instrumentation
/sig release

/lifecycle frozen
/triage accepted
/priority important-longterm

**Comment by deepak4566** [comment]
Hey @sftim well i understood from the issue that  we need to write documentation for kubernetes/kubernetes#113343
For every file present in the pr ,is that right??? Well i have some experience in writing docs can work on this 
/assign

**Comment by sftim** [comment]
> well i understood from the issue that we need to write documentation for [kubernetes/kubernetes#113343](https://github.com/kubernetes/kubernetes/pull/113343)

We need to document how someone in the release docs team can use automation to update the pages within https://kubernetes.io/docs/reference/instrumentation/ that are automatically generated.

To work out which pages within https://kubernetes.io/docs/reference/instrumentation/ are generated automatically generated, you can either:
- ask contributors (eg from SIG Instrumentation - @logicalhan wrote all the generator code so far as I know)
- look at each page within https://kubernetes.io/docs/reference/instrumentation/ and see whether that page is marked as automatically generated.

---

The outcome is likely to be a change to either one or two pages within https://kubernetes.io/docs/contribute/generate-ref-docs/
So long as the change allows a contributor in release docs to understand what to do, we've done enough to close this issue.

**Comment by deepak4566** [comment]
@sftim already started the process u can check my pr #42483 to review that if possible  , many pr's are expected to come ,I'm working on it and @logicalhan has  reviewed some part of it

**Comment by sftim** [comment]
> @sftim already started the process u can check my pr #42483 to review that if possible , many pr's are expected to come ,I'm working on it and @logicalhan has reviewed some part of it

I'm happy for anyone to review that PR. To ask for feedback more widely, join the Kubernetes Slack workspace - https://kubernetes.slack.com/ (visit https://slack.k8s.io/ for an invitation) - and ask in https://kubernetes.slack.com/messages/sig-docs

**Comment by sftim** [comment]
https://github.com/kubernetes/kubernetes/blob/f563910656ad325a7e1f8ab5848746bc2eba4d7f/test/instrumentation/README.md is a good starting point.

**Comment by Gauravpadam** [comment]
It would be nice to have the steps documented. I'll help with this
