### ISSUE TITLE
[ja] Translate docs/concepts/security/secrets-good-practices into Japanese

### ISSUE THREAD

**Issue by furon-kuina** [kubernetes/website#42450]
**This is a Feature Request**

**What would you like to be added**

Translate [https://kubernetes.io/docs/concepts/security/secrets-good-practices/](https://kubernetes.io/docs/concepts/security/secrets-good-practices/) into Japanese. 

**Why is this needed**
The page has no Japanese translation.

**Comments**

/language ja
/assign

**Comment by bezalel-7** [comment]
hey @furon-kuina can i work on this!
