### ISSUE TITLE
[ru] Screen resolution compatibility issue for online interactive tutorial terminal in the "Create a cluster" page

### ISSUE THREAD

**Issue by kborovikov** [kubernetes/website#42455]
resolution of my 4k screen. I received a warning "This screen is too small to work with the terminal, please use your computer or tablet."

**Comment by dipesh-rawat** [comment]
_Page related to issue:_  https://kubernetes.io/ru/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/
/language ru

**Comment by dipesh-rawat** [comment]
/retitle [ru] Screen resolution compatibility issue for online interactive tutorial terminal in the "Create a cluster" page

**Comment by sftim** [comment]
The actual bug here is that the Russian page is out of date.

I'm afraid that we're short of capacity in this team, partly as a result of the war where Russia has invaded Ukraine.

**Comment by kborovikov** [comment]
> The actual bug here is that the Russian page is out of date.
ok

**Comment by shurup** [comment]
I am currently working on this page (among many others) in #41923. Hopefully, I'll finish the remaining pages soon, and it will go live.

**Comment by shurup** [comment]
With #42530 merged, this issue is now also resolved.

Please, follow the instructions provided on this page now: https://kubernetes.io/ru/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/
