### ISSUE TITLE
Add example YAML manifest for all API kinds

### ISSUE THREAD

**Issue by jimsnab** [kubernetes/website#42452]
It is extremely hard in all Kubernetes documentation to find full yaml schema, such as every option a deployment manifest can have. There is so much irrelevant text to wade through, ultimately not helping me at all, because the full schema itself is not linked. At least I can't find it.

**Comment by sftim** [comment]
If we add this, I hope it's hidden inside something like a [`<details>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) (perhaps specially styled)

**Comment by sftim** [comment]
@AryanSharma9917 you've assigned yourself to an issue not yet triaged as accepted. Is that what you intended?
