### ISSUE TITLE
installing addons on eksKubernetes Components

### ISSUE THREAD

**Issue by erik-nc** [kubernetes/website#42474]

**Comment by dipesh-rawat** [comment]
@erik-nc  Hi, Could you please share the details on the issue you would like to report or the assistance you require? Kindly provide details in the https://github.com/kubernetes/website/issues/42474#issue-1843479827 of the issue.

/triage needs-information
/language en

**Comment by sftim** [comment]
I assume that this was a support request but with no question asked.
/kind support
/close not-planned
