### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by jicowan** [kubernetes/website#4247]
This is an issue with the kube proxy.  After running kubectl proxy, I couldn't curl the service running on the cluster.  Instead, I got an error saying Error: 'dial tcp 172.18.0.2:8080: getsockopt: connection refused'

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Could you please retest this and see if you're getting the same error?
