### ISSUE TITLE
Use JSON instead of YAML for example requests in "Dynamic Admission Control" page

### ISSUE THREAD

**Issue by dsorak** [kubernetes/website#42494]
The documentation states:

> AdmissionReview API object in the admission.k8s.io API group serialized to JSON as the body.

So, it is beyond me why the example is then presented in YAML format? Yes, YAML seems to be the preferred format when dealing with Kubernetes, but this documentation _specifically states that it is in JSON format_, so then PLEASE present it in JSON format.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Use JSON instead of YAML for example requests in "Dynamic Admission Control" page
/language en

**Comment by dipesh-rawat** [comment]
/retitle Use JSON instead of YAML for example requests in "Dynamic Admission Control" page

**Comment by dipesh-rawat** [comment]
Looks similar (possibly duplicate) of issue we already have https://github.com/kubernetes/website/issues/41542
/triage duplicate

**Comment by dipesh-rawat** [comment]
Closing this in favour of triage/accepted issue https://github.com/kubernetes/website/issues/41542

/close
