### ISSUE TITLE
Improve explanation of difference between labels and annotations

### ISSUE THREAD

**Issue by aniruddhakulkarni08** [kubernetes/website#42524]
The follwing link in documentation of annotation ---

https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#attaching-metadata-to-objects

It is written as --You can use either labels or annotations to attach metadata to Kubernetes objects.

But we can use labels as well as annotations in metadata of same object then why "or" it is very confusing.

**Comment by sftim** [comment]
/retitle Improve explanation of difference between labels and annotations
/language en
/priority backlog
/wg api-expression
/triage accepted

**Comment by sftim** [comment]
The text
> _Labels can be used to select objects and to find collections of objects that satisfy certain conditions. In contrast, annotations are not used to identify and select objects. The metadata in an annotation can be small or large, structured or unstructured, and can include characters not permitted by labels._

&hellip;does seem to cover the detail needed. It's written for a technical audience who can infer the benefits of the different approaches. Maybe we can add more detail into https://kubernetes.io/docs/concepts/overview/working-with-objects/ and then change:

- https://k8s.io/docs/concepts/overview/working-with-objects/annotations/
- https://k8s.io/docs/concepts/overview/working-with-objects/labels/ 

so that both of those pages then link to the new comparison text we add.

**Comment by Shubhdeep02** [comment]
Hey!!! can someone please suggest me if the change should be in both the docs (labels & annotations) or simply in working with objects doc??

**Comment by khubaibalam2000** [comment]
Can i get this Issue ?

**Comment by khubaibalam2000** [comment]
Ok, starting working on this issue

**Comment by satyampsoni** [comment]
> Maybe we can add more detail into https://kubernetes.io/docs/concepts/overview/working-with-objects/ and then change:
It'll be helpful @sftim if you can elaborate what kind of detail should be added here?

**Comment by sftim** [comment]
@satyampsoni you're quoting https://github.com/kubernetes/website/pull/43170#issuecomment-1732223735; see the conversation there.

**Comment by Shubhdeep02** [comment]
@sftim is the issue resolved?? or still open?

**Comment by vaibhav2107** [comment]
@Shubhdeep02 I think this issue is resolved by PR #43178

**Comment by vaibhav2107** [comment]
Hence we can close this one
