### ISSUE TITLE
[ja] Discrepancy in PriorityClass Value Range Description Between English and Japanese Documentation

### ISSUE THREAD

**Issue by chansuke** [kubernetes/website#42533]
**This is a Feature Request**

In the documentation of `PriorityClass` in [english](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass), the value of a PriorityObject is described as:

> A PriorityClass object can have any 32-bit integer value smaller than or equal to 1 billion. This means that the range of values for a PriorityClass object is from -2147483648 to 1000000000 inclusive

Which is more precisely described about the range of the value but instead in [japanese](https://kubernetes.io/ja/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass), its description is quite simple and missing the mention of negative range.

> PriorityClassオブジェクトは10億以下の任意の32ビットの整数値を持つことができます。

**What would you like to be added**

Add a translation of the range of the value of `PriorityClass`.

**Why is this needed**

This omits the mention of the negative range, which could lead to ambiguity or misunderstandings for readers.

**Comment by sftim** [comment]
It would also be OK to make it very clear that the value is signed. However, mentioning the two extremes of the range is especially hard to misunderstand. I recommend doing that.

**Comment by ADITYADAS1999** [comment]
> It would also be OK to make it very clear that the value is signed. However, mentioning the two extremes of the range is especially hard to misunderstand. I recommend doing that.

Hey @sftim can I fix this issue ?

**Comment by t-inu** [comment]
@whitebeard10
This issue has already been assigned to @ADITYADAS1999 and the PR #42582 exists.
So I will close your PR (#42626).
We look forward to another time for your contribution!

**Comment by khubaibalam2000** [comment]
@sftim Is this issue resolved? If not, can I take it ?

**Comment by ADITYADAS1999** [comment]
Fixed by https://github.com/kubernetes/website/pull/42582

/close
