### ISSUE TITLE
Freeze `k/website` for Kubernetes 1.28 release

### ISSUE THREAD

**Issue by Rishit-dagli** [kubernetes/website#42532]
This issue is for freezing the k/website for the Kubernetes 1.28 release.

The release is scheduled to happen tomorrow (August 15, 2023) and No PRs are allowed to merge until the release PR has successfully merged.

If there are any questions, please contact me or anyone from the 1.28 docs release team.

cc: 1.28 Docs Team: @katcosgrove @taniaduggal @AdminTurnedDevOps @VibhorChinda 

/sig release
/label tide/merge-blocker

**Comment by reylejano** [comment]
/triage accepted
k/website will be frozen for about 24 hours until 1.28 is released

**Comment by Rishit-dagli** [comment]
Thawing `k/website`

/remove-label tide/merge-blocker
