### ISSUE TITLE
Configure Liveness, Readiness and Startup Probes Document problem

### ISSUE THREAD

**Issue by linliaoy** [kubernetes/website#42539]
I looked at the 1.28 code and found that startup, readness, and liveness probes InitialDelaySeconds were all executed together and were inconsistent with the documentation

document ： initialDelaySeconds: Number of seconds after the container has started before startup, liveness or readiness probes are initiated. If a startup probe is defined, liveness and readiness probe delays do not begin until the startup probe has succeeded. Defaults to 0 seconds. Minimum value is 0.

//pkg/kubelet/prober/worker.go:246
// Probe disabled for InitialDelaySeconds.
	if int32(time.Since(c.State.Running.StartedAt.Time).Seconds()) < w.spec.InitialDelaySeconds {
		return true
	}

	if c.Started != nil && *c.Started {
		// Stop probing for startup once container has started.
		// we keep it running to make sure it will work for restarted container.
		if w.probeType == startup {
			return true
		}
	} else {
		// Disable other probes until container has started.
		if w.probeType != startup {
			return true
		}
	}

**Comment by utkarsh-singh1** [comment]
Related page - https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

/language en
