### ISSUE TITLE
Add examples of rollout strategy for Deployment concept

### ISSUE THREAD

**Issue by Sarony11** [kubernetes/website#42540]
It would be nice to have different examples in how to define in YAML the rollout strategy. I know that "Recreate" strategy is barely used, but how is not as simple as changing the type in the yaml file, it would be great to have both "rollingUpdate" and "recreate" to compare and avoid confusion in how to use them.

**Comment by sftim** [comment]
/retitle Add examples of rollout strategy for Deployment concept
