### ISSUE TITLE
“Install and Set Up kubectl…” tasks mention fixed bug

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42553]
**This is a Bug Report**

**Problem:**
- https://k8.io/docs/tasks/tools/install-kubectl-linux/
- https://k8s.io/docs/tasks/tools/install-kubectl-macos/
- https://k8s.io/docs/tasks/tools/install-kubectl-windows/

each tell readers about a warning message:

> The above command will generate a warning:
> 
> > **WARNING**: This version information is deprecated and will be replaced with the output from `kubectl version --short`.
> 
> You can ignore this warning. You are only checking the version of kubectl that you have installed.

However, `kubectl` from Kubernetes v1.28.0 doesn't show that warning.

**Proposed Solution:**
- Find the text “_This version information is deprecated and will be replaced with the output from_” in the website source.
- Remove the note about the warning.

**Pages to Update:**
- https://k8.io/docs/tasks/tools/install-kubectl-linux/
- https://k8s.io/docs/tasks/tools/install-kubectl-macos/
- https://k8s.io/docs/tasks/tools/install-kubectl-windows/

**Additional Information:**
/sig cli
/language en
/help

**Comment by pegasas** [comment]
/assign @pegasas 

I will raise a PR to fix this.

**Comment by pegasas** [comment]
PR https://github.com/kubernetes/website/pull/42557 has been merged.
request to close this issue.

**Comment by ydFu** [comment]
Get Merged,thanks.

/close
