### ISSUE TITLE
Broken link on Kubernetes v1.28 blog post

### ISSUE THREAD

**Issue by Rishit-dagli** [kubernetes/website#42563]
**This is a Bug Report**

**Problem:** The release blog has this section:

> Upcoming Release Webinar
Join members of the Kubernetes v1.28 release team on Friday, September 14, 2023, at 10 a.m. PDT to learn about the major features of this release, as well as deprecations and removals to help plan for upgrades. For more information and registration, visit the [event page](https://community.cncf.io/events/details/cncf-cncf-online-programs-presents-cncf-live-webinar-kubernetes-v128-release/) on the CNCF Online Programs site.

This currently has a broken link to the event page.

**Proposed Solution:** Once the event is live on CNCF we should fix this in the blog or at least remove the link until then.

**Page to Update:**
https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/

/cc @bradmccoydev

**Comment by bradmccoydev** [comment]
Thanks @Rishit-dagli confirmed it is broken talking with CNCF now regarding it. Will do a PR to remove for now

**Comment by bradmccoydev** [comment]
I have raised the PR for this https://github.com/kubernetes/website/pull/42564
