### ISSUE TITLE
Broken link to API reference in Pod Lifecycle concept

### ISSUE THREAD

**Issue by sdyura** [kubernetes/website#42588]
[PodConditions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#podcondition-v1-core) on page gives 404 error

in section: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions

**Comment by sftim** [comment]
/triage accepted

We have a PR ready for a fix; now, that PR needs a review.

/priority backlog

**Comment by sftim** [comment]
/retitle Broken link to API reference in Pod Lifecycle concept

**Comment by antaloala** [comment]
It is really a broken link to the whole k8s 1.28 API reference (not only to the Pod-Lifecycle part); note the URL [https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/ ) does not work (but it still works for [1.27](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/), [1.26](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/), ...)

**Comment by sftim** [comment]
For an issues about the API reference missing overall, see https://github.com/kubernetes/website/issues/42601
