### ISSUE TITLE
[ja] Translate `docs/concepts/workloads/pods/disruptions.md` into Japanese

### ISSUE THREAD

**Issue by chansuke** [kubernetes/website#42607]
**This is a Feature Request**

Translate the description about [Disruption](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) into Japanese.

**What would you like to be added**

**Why is this needed**

On this [page](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/), there are many important concepts that we often refer to in production.

- Voluntary Disruption / Involuntary Disruption
- `PodDisruptionBudget`

It would be great if we could read this in Japanese.

**Comments**

**Comment by AbhaysCode** [comment]
Can I work on this ?

**Comment by sftim** [comment]
/retitle [ja] Translate `docs/concepts/workloads/pods/disruptions.md` into Japanese

**Comment by sftim** [comment]
> Can I work on this ?

If you can speak English and Japanese, go for it!

**Comment by AbhaysCode** [comment]
Hello,

I'm relatively new to the world of open source contributions, and I'm excited to be a part of this community! 😊
I've recently submitted a pull request where I've translated the "disruptions.md" file into Japanese. This is my first attempt at contributing to the project, and I'm hoping to learn and grow from this experience.
I would greatly appreciate it if you could take a look at my pull request and provide feedback. 
Pull Request Title: [ja] Translate docs/concepts/workloads/pods/disruptions.md into Japanese
Pull Request Link: [https://github.com/kubernetes/website/pull/42615]

Thank you for your time and consideration. I'm looking forward to contributing more to the project and becoming an active member of the open source community!

Best regards,
Abhay Pratap Singh
