### ISSUE TITLE
Link to kubernetes api reference 1.28 does not work

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#42601]
In new (k8s 1.28 updated) [API Overview](https://kubernetes.io/docs/reference/using-api/) documentation page: the link [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/) given in the third paragraph does not work.

(the bug is really about that link not working; the URL looks ok but it is some days I am getting a 404)

**Comment by ADITYADAS1999** [comment]
> In new (k8s 1.28 updated) [API Overview](https://kubernetes.io/docs/reference/using-api/) documentation page: the link [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/) given in the third paragraph does not work.
> 
> (the bug is really about that link not working; the URL looks ok but it is some days I am getting a 404)

#42588

**Comment by werdnum** [comment]
The link to "NetworkPolicy" on https://kubernetes.io/docs/concepts/services-networking/network-policies/ suffers the same fate.
