### ISSUE TITLE
Problem rendering Mermaid diagram (seen in page Pod Topology Spread Constraints)

### ISSUE THREAD

**Issue by creatldd1** [kubernetes/website#42625]
Hello,
Check https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#example-one-topologyspreadconstraint

The mermaid script holds a syntax error apparently.

**Comment by sftim** [comment]
/retitle Problem rendering Mermaid diagram (seen in page Pod Topology Spread Constraints)
/triage duplicate

**Comment by anjannath** [comment]
I also faced this today, but after **reloading** the page it rendered the graph diagram correctly, note: i was using the "dark reader" firefox plugin not sure if that could have somehow messed with the mermaid rendering.

![image](https://github.com/kubernetes/website/assets/8885742/bf7f6be5-108c-4cfb-8691-f8c04784e07f)

**Comment by sftim** [comment]
This is a duplicate report
/close not-planned
