### ISSUE TITLE
Broken links in 'Node Status' section of 'Nodes' page

### ISSUE THREAD

**Issue by geetasg** [kubernetes/website#42628]
Links from https://kubernetes.io/docs/concepts/architecture/nodes/#node-status section are broken.

List of broken links
https://kubernetes.io/docs/concepts/node/node-status/#addresses
https://kubernetes.io/docs/concepts/node/node-status/#condition
https://kubernetes.io/docs/concepts/node/node-status/#capacity
https://kubernetes.io/docs/concepts/node/node-status/#info
https://kubernetes.io/docs/concepts/node/node-status

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/architecture/nodes/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Broken links in 'Node Status' section of 'Nodes' page
/kind bug

**Comment by dipesh-rawat** [comment]
Looks like the recent refactoring updates in https://github.com/kubernetes/website/pull/42378/ seem to have unintentionally led to the emergence of the mentioned broken links.

**Comment by dipesh-rawat** [comment]
Given that the content from https://kubernetes.io/docs/concepts/architecture/nodes/#node-status has been relocated to https://kubernetes.io/docs/reference/node/node-status/ (as part of https://github.com/kubernetes/website/pull/42378), it would be beneficial to revise the outdated and incorrect reference links.

/priority backlog
/triage accepted

**Comment by sftim** [comment]
Fixed by #42630, I think.

/close
