### ISSUE TITLE
Broken links in “Introducing kustomize; Template-free Configuration Customization for Kubernetes” article

### ISSUE THREAD

**Issue by bugoverdose** [kubernetes/website#42634]
**This is a Bug Report**

**Problem:** Some of the links in the **Introducing kustomize** blog post are outdated. 
- [subproject](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/0008-kustomize.md)
- [workflow](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/workflows.md)

<img width="1408" alt="스크린샷 2023-08-19 오후 9 57 03" src="https://github.com/kubernetes/website/assets/73531614/68b41e1c-74af-4272-ac97-4b9fe609a690">

**Proposed Solution:** Fix the links to lead to the data it used to show, or show the updated content. And I think I found them already.

**Page to Update:**
https://kubernetes.io/blog/2018/05/29/introducing-kustomize-template-free-configuration-customization-for-kubernetes/

**Comment by thisisharrsh** [comment]
_page related to the issue: https://kubernetes.io/blog/2018/05/29/introducing-kustomize-template-free-configuration-customization-for-kubernetes/_ 

/language en

**Comment by bugoverdose** [comment]
Closing this issue because the corresponding PR was merged.

/close
