### ISSUE TITLE
Update hyperlinks in 'Amadeus Case Study' page to utilize HTTPS instead of HTTP

### ISSUE THREAD

**Issue by Arhell** [kubernetes/website#42638]
http://kubernetes.io/ to https://kubernetes.io/
/assign

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/case-studies/amadeus/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Update hyperlinks in 'Amadeus Case Study' page to utilize HTTPS instead of HTTP

**Comment by sftim** [comment]
Which is the page we should fix?
