### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by aalba6675** [kubernetes/website#4263]
**This is a...** 

- [] Feature Request
- [x] Bug Report

**Problem:**
$CLI_CERT
$CLI_KEY
are not explained earlier in the doc

**Proposed Solution:**
Document the variables $CLI_CERT $CLI_KEY

**Page to Update:**
https://k8s.io/docs/getting-started-guides/scratch/

**Comment by arush-sal** [comment]
I guess instead of the CLI_CERT/CLI_KEY, it should be MASTER_CERT and MASTER_KEY, correct me if wrong :)

**Comment by tengqm** [comment]
/remove-lifecycle stale

This is still relevant.
