### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/

### ISSUE THREAD

**Issue by theking2** [kubernetes/website#42644]
After reading I still don´t understand how kubernetes and containers are related or what kubernets __do__. Is a kubernates a container with additional features? Is kubernate an addition to containers, adding functionality?

I personally would be helped with a list of features that a container doesn´t do and where kubernetes come in. The classic problem / solution approach we know from many IT or programming related concepts.

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/concepts/overview/_

**Comment by thisisharrsh** [comment]
Hi @theking2, Consider Containers like lightweight and a consistent way to package, distribute and run an application along with their dependencies. They isolate the application from the underlying infrastructure and making them portable and efficient.
But the containers themselves do not able to manage the orchestration, scaling, and the deployments aspects of the application and that's why tools like kubernetes comes into the picture.

**Comment by thisisharrsh** [comment]
Kubernetes is a powerful orchestration tool that helps automate the deployments, scaling, and management of containerized applications. It helps automate complex tasks like load balancing, rolling updates, and disaster management of the application. Hence, it is much easier to handle and maintain large-scale container deployments.

**Comment by sftim** [comment]
How I recommend fixing this: add new content at the start of https://k8s.io/docs/concepts/overview/ (before “Going back in time”)

The new content should aim to answer the questions that @theking2 didn't see answers to.

/priority backlog
/triage accepted

If working on this, consider setting a custom `linkTitle` for that page as well.

**Comment by pegasas** [comment]
/assign @pegasas 

I will try to correct some sentences in the overview.
I think we should highlight orchestration, automation for deployment, and scaling to make it clear.

Feel free to comment if any suggestions.

**Comment by pegasas** [comment]
see https://github.com/kubernetes/website/pull/42660#issuecomment-1722229092
/close
