### ISSUE TITLE
[hi] Localization of the contents 

### ISSUE THREAD

**Issue by ranjan2829** [kubernetes/website#42649]
![Screenshot 2023-08-20 213614](https://github.com/kubernetes/website/assets/73215366/919add66-13b3-4135-b2d1-d3adec24c76e)
some content on this page is not localized in hindi language !

```[tasklist]
### Tasks
- [ ] https://kubernetes.io/hi/docs/home/
```

**Comment by ranjan2829** [comment]
/lang/hi

**Comment by sftim** [comment]
/triage duplicate

This is a duplicate of issue https://github.com/kubernetes/website/issues/29353

**Comment by bishal7679** [comment]
@sftim Shouldn't we close this issue?
