### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by misitejin** [kubernetes/website#42658]
in the doc of networkPolicy ,the ports: didn't work, instead using - ports: 
....
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mytest
    - ports:
        - protocol: TCP
          port: 53

**Comment by thisisharrsh** [comment]
_page related to the issue: https://kubernetes.io/zh-cn/docs/concepts/services-networking/network-policies/_
/language zh
/sig networking

**Comment by thisisharrsh** [comment]
_page related to the issue: https://kubernetes.io/zh-cn/docs/concepts/services-networking/network-policies/_
/language zh
/sig network

**Comment by mengjiao-liu** [comment]
The Chinese version is only synchronized with the English upstream version. 

page: https://kubernetes.io/docs/concepts/services-networking/network-policies/

/language en

**Comment by kumarankit999** [comment]
Should I Work on this

**Comment by tengqm** [comment]
What are the specific issue to resolve?
