### ISSUE TITLE
v1.28 maintenance date discrepancy in "Patch Releases" page

### ISSUE THREAD

**Issue by shazib-summar** [kubernetes/website#42659]
In the "Detailed Release History for Active Branches" section ([Ref](https://kubernetes.io/releases/patch-releases/#detailed-release-history-for-active-branches)), it says

> 1.28 enters maintenance mode on 2023-08-28 and End of Life is on 2024-10-28.

The maintenance date seem off as 1.28 just released

**Comment by shazib-summar** [comment]
I'll be more than happy to make a PR for this if the correct dates are provided.

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/releases/patch-releases/
/language en

**Comment by dipesh-rawat** [comment]
/retitle v1.28 maintenance date discrepancy in "Patch Releases" page
/sig release

**Comment by sftim** [comment]
Fixed by #42666 

/close
