### ISSUE TITLE
`_redirects` needs to be updated in a better way for validation and localization

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#42654]
**This is a Feature Request**

We need a feature or a way to handle (maintain) `_redirects` in a better way 
in terms of validation (of target URLs) and localization (redirects for non-english language pages).

When previously provided pages disappear, we've added redirect to related documents. 
These redirects are listed in https://github.com/kubernetes/website/blob/main/static/_redirects, and currently, there are around 400 entries.

I believe there are several issues in maintaining this `_redirects` file.
1) Some redirects lead to incorrect or non-existent links, and these are not being properly managed. 
  for instance,
    ```diff
    -----/docs/concepts/service-catalog/,/docs/concepts/extend-kubernetes/service-catalog/,301
    -----/docs/reference/generated/cloud-controller-manager/,/docs/reference/command-line-tools-reference/cloud-controller-manager/,301
    -----/docs/reference/generated/kubernetes-api/v1.15/,https://v1-15.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/,301
    -----/docs/reference/generated/kubernetes-api/v1.16/,https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/,301
    -----/docs/reference/generated/kubernetes-api/v1.17/,https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/,301
    -----/docs/reference/generated/kubernetes-api/v1.18/,https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/,301
    /docs/reference/glossary/maintainer/,/docs/reference/glossary/?community=true#term-approver,301
    -----/docs/setup/on-premises-vm/cloudstack/,/docs/setup/production-environment/on-premises-vm/cloudstack/,301
    -----/docs/setup/on-premises-vm/dcos/,/docs/setup/production-environment/on-premises-vm/dcos/,301
    -----/docs/setup/on-premises-vm/ovirt/,/docs/setup/production-environment/on-premises-vm/ovirt/,301
    /docs/tasks/administer-cluster/kubeadm-upgrade-ha/,/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/,301
    /docs/tasks/administer-cluster/out-of-resource/memory-available.sh,/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/,301
    -----/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/,/docs/tasks/run-application/upgrade-pet-set-to-stateful-set/,301
    /events/,/community,301
    /image-registry-change/,/blog/2023/03/10/image-registry-redirect/,302
    /image-registry-redirect/,/blog/2023/03/10/image-registry-redirect/,302
    /media/,/community,301
    /news/,/community,301
    -----/no/docs/,/no/docs/home/,301!
    ```

2) Kubernetes documentation is localized in more than 10 languages, but these redirects hardly address links in localized languages. Managing this has become a significant challenge. Due to the syntax of _redirects (Netlify), wildcard handling is difficult for localization. 
  for instance, no redirects for the other languages (except manually added en,id,zh-cn,ja,hi).
    ```
    /docs/setup/learning-environment/     /docs/tasks/tools/  302!
    /id/docs/setup/learning-environment/     /id/docs/tasks/tools/  302!
    /zh-cn/docs/setup/learning-environment/     /zh-cn/docs/tasks/tools/  302!
    /ja/docs/setup/learning-environment/     /ja/docs/tasks/tools/  302!
    /hi/docs/setup/learning-environment/     /hi/docs/tasks/tools/ 302!
    ```

3) We are unsure when to stop redirecting old temporal URLs. (The period is not managed well.)
  for instance, there are old redirects (added 6 years ago).
    ```
    /concepts/containers/container-lifecycle-hooks/     /docs/concepts/containers/container-lifecycle-hooks/ 301
    /docs/api-reference/labels-annotations-taints/     /docs/reference/labels-annotations-taints/ 301
    ...
    ```
4) Additionally, there are problems like the list not being sorted

**What would you like to be added**

- A tool verifies the content of the redirects, regenerates them according to localization, and automatically creates the _redirects. 
  - checks the list of redirects for inaccessible URLs and ensures that contributors only provide accessible addresses. 
  - If redirects for English are added, it automatically generates redirects for other languages, ensuring that future localization contributors don't have to worry about redirects.

**Why is this needed**
Eventually, contributors will be enforced to generate a proper `_redircts` (Through this, whenever we modify _redirects, we can be confident that there are no issues with _redirects and that localization has been handled properly.)

**Comments**

We don't need to add a new tool to manage _redirects if there's a better option available, such as full automation. 
(need discussions)

**Comment by seokho-son** [comment]
PR #42629 implements a tool for this. (demo: https://www.youtube.com/watch?v=ThuhFgOFesk)

**Comment by seokho-son** [comment]
Another valuable comment from @tengqm : https://github.com/kubernetes/website/pull/42629#issuecomment-1685166499

> This doesn't look to me like a viable/sustainable approach for managing redirects.
> 
> If you have tried the current scripts/linkchecker.py script, you will see that
> we are able to run link checks along with redirect checks using a simpler method.
> That tool is not perfect, lacking support to check blog paths or support to parse
> examples path or static redirects (such as '/dockershim'). However, it is a good
> starting point for further improvements. I am not a big fan of adding a lot of
> tools overlapping with each other.
> 
> Speaking of redirects for localized contents, I had a proposal 4 years ago (https://github.com/kubernetes/website/pull/18374). It is a much simpler approach
> to make sure that we (the 10+ localization teams) don't need to prefix each and
> every link target with a language code. The ref and relref shortcode are there
> just for this purpose. The proposal wasn't quite received by the reviewers, I believe.
> It looks like a huge churn to the whole site. However, it is a solution that,
> once applied, will benefit the whole community in the long run.

**Comment by seokho-son** [comment]
Let me close this issue since we don't have enough consensus on this issue yet. :)

/close

**Comment by sftim** [comment]
/reopen
One nit, sorry.

**Comment by sftim** [comment]
I like the idea of making some improvement here. However:

/close not-planned
