### ISSUE TITLE
Pod Topology Spread Constraints: SelectorSpread plugin was removed

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42676]
> https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints
> Note: The SelectorSpread plugin is disabled by default. The Kubernetes project recommends using PodTopologySpread to achieve similar behavior.

According to [this page section](https://kubernetes.io/docs/reference/scheduling/config/#scheduler-configuration-migrations) (check the "v1beta3 → v1" tab) "The scheduler plugin SelectorSpread is removed, instead, use the PodTopologySpread plugin (enabled by default) to achieve similar behavior." But [the page](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints) still mentions the SelectorSpread plugin.

Also this plugin is mentioned in [another page section](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints).

**Comment by sftim** [comment]
/triage accepted
/priority backlog

Fixes welcome!

**Comment by kerthcet** [comment]
Thanks for raise this issue.

**Comment by aj11anuj** [comment]
Due to deprecation and removal of selectorspread plugin, docs needs to be updated. How can non-updation of docs be labeled as bug? It will be related to enhancement category na. So, feature/enhancement label will be more suitable here. 🤔

/remove-kind bug
/kind feature

**Comment by sftim** [comment]
No, this _is_ a bug. Any time we have a page that misleads readers - other than purely by omission- it's a bug.
/kind bug
/remove-kind feature

**Comment by aj11anuj** [comment]
> No, this _is_ a bug. Any time we have a page that misleads readers - other than purely by omission- it's a bug. /kind bug /remove-kind feature

Ok, got it 👍

**Comment by T-Lakshmi** [comment]
Seems this issue is already fixed by merging PR #43216.
Please close the close the issue.
