### ISSUE TITLE
Missing doc for "SidecarContainers" feature gate in "kube-scheduler" reference page

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#42679]
Missing new from k8s 1.28 ``SidecarContainers=true|false (ALPHA - default=false)`` feature-gate; not being listed in [kube-scheduler](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/)

(I just run ``kube-scheduler --help`` and found it in the resulting printout)

**Comment by dipesh-rawat** [comment]
/retitle Missing doc for "SidecarContainers" feature gate in "kube-scheduler" reference page

**Comment by sftim** [comment]
/triage accepted
/priority important-longterm

(it's not exactly a duplicate, but the actual issue is that the v1.28 release missed out several important updates, including the reference pages for each component binary)

**Comment by nate-double-u** [comment]
Fixed with https://github.com/kubernetes/website/pull/42571

/close
