### ISSUE TITLE
Missing doc for "SidecarContainers" feature gate in "kube-apiserver" reference page

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#42678]
Missing new from k8s 1.28 ``SidecarContainers=true|false (ALPHA - default=false)`` feature-gate; not being listed in [kube-apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)

(I just run ``kube-apiserver --help`` and found it in the resulting printout)

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Missing doc for "SidecarContainers" feature gate in "kube-apiserver" reference page

**Comment by sftim** [comment]
/triage accepted
/priority important-longterm

(it's not exactly a duplicate, but the actual issue is that the v1.28 release missed out several important updates, including the reference pages for each component binary)

**Comment by T-Lakshmi** [comment]
PR already opened for this #42571.

**Comment by nate-double-u** [comment]
Fixed with https://github.com/kubernetes/website/pull/42571
