### ISSUE TITLE
Stale information about `minDomains` in Pod `topologySpreadConstraints`

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42670]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition says that you need to enable `MinDomainsInPodTopologySpread` in v1.25 to use the feature. This is misleading and / or confusing; in the latest v1.28 release, it's enabled by default.

**Proposed Solution:**
Revise the stale documentation. Mention that your cluster might have `MinDomainsInPodTopologySpread` explicitly disabled, and otherwise assume that `minDomains` is available. Give readers a hint that older Kubernetes clusters might not have that field though.

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Additional Information:**
/sig scheduling
/kind bug
/language en

**Comment by tamilselvan1102** [comment]
Please confirm below Note content

> MinDomainsInPodTopologySpread gate enables MinDomains in pod topology spread. 
> From v1.28 release, MinDomainsInPodTopologySpread gate is enabled by default and older clusters might not have that gate field though.

**Comment by tamilselvan1102** [comment]
@sftim 
please confirm the Note content mentioned above comment. 
I would like to raise a PR
