### ISSUE TITLE
Missing doc for "SidecarContainers" feature gate in "kube-controller-manager" reference page

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#42680]
Missing new from k8s 1.28 ``SidecarContainers=true|false (ALPHA - default=false)`` feature-gate; not being listed in [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)

(I just run ``kube-controller-manager --help`` and found it in the resulting printout)

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Missing doc for "SidecarContainers" feature gate in "kube-controller-manager" reference page

**Comment by nate-double-u** [comment]
Fixed with https://github.com/kubernetes/website/pull/42571
