### ISSUE TITLE
Add a `security.txt`

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42693]
**This is a Feature Request**

**What would you like to be added**
Add a https://k8s.io/.well-known/security.txt page, based on [RFC 9116](https://datatracker.ietf.org/doc/html/rfc9116)

**Why is this needed**
> Many security researchers encounter situations where they are unable to report security vulnerabilities to organizations because there are no reporting channels to contact the owner of a particular resource, and no information is available about the vulnerability disclosure practices of such owner.

We can provide a machine-parseable way for people to find out how to disclose security vulnerabilities, as well as what **not** to disclose.
(eg: it's possible to socially engineer a contributor into liking a ~tweet~ X post by an imposter)

**Comments**
Ideally (?), we'd also sign the file using PGP

[Original suggestion](https://kubernetes.slack.com/archives/C019LFTGNQ3/p1660245049689409?thread_ts=1660234797.631769&cid=C019LFTGNQ3)

/sig security

**Comment by ashish493** [comment]
@whitebeard10 If you have started working on it, let me know if any help is required. Even I am interested in contributing to it.

**Comment by ashish493** [comment]
@sftim do we also need to write a KEP for this issue, since you have mentioned that in the previous slack discussion?

**Comment by whitebeard10** [comment]
i am still working on it, will let you know for any help for sure @ashish493

**Comment by sftim** [comment]
> do we also need to write a KEP for this issue, since you have mentioned that in the previous slack discussion?

The best group of people to ask about this are Kubernetes SIG Security.

**Comment by coder12git** [comment]
@sftim i have recently worked on this type of issue under `Kubernetes Security Slam`, and also it's been a long time and still no PR is created , so if it's fie then can i take this issue?

**Comment by coder12git** [comment]
Have a look on this PR -> https://github.com/kubernetes/website/pull/44487
