### ISSUE TITLE
Repeated word in Install kubeadm page

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#42708]
**This is a Bug Report**
**Problem:**
Repetitive word in Installing [kubeadm, kubelet and kubectl](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl)  section under Note.

> There's a dedicated package repository for each Kubernetes minor version. When upgrading **to to** a different minor release, you must bear in mind that the package repository details also change.

**Proposed Solution:**
Remove the repetitive word 'to'
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by steve-hardman** [comment]
I will sumbit fix for this plzz
/assign

**Comment by steve-hardman** [comment]
I have attempt to make change for this inf https://github.com/kubernetes/website/pull/42709
