### ISSUE TITLE
Service Accounts

### ISSUE THREAD

**Issue by HakimMiao** [kubernetes/website#42701]
Change translation to the homepage instead of translating this page

**Comment by HakimMiao** [comment]
https://kubernetes.io/docs/concepts/security/service-accounts/

**Comment by thisisharrsh** [comment]
Hi @HakimMiao, Could you please share some more information on the issue in the [description](https://github.com/kubernetes/website/issues/42701#issue-1864438586) section?

**Comment by HakimMiao** [comment]
When I switch languages in the serviceaccount interface, the page will redirect to the main page instead of redirecting to the language interface I have chosen.
Sorry, my picture cannot be uploaded
``` html
<!--normal page-->
<a class="dropdown-item" href="/id/docs/concepts/security/overview/">Bahasa Indonesia</a>
<!--service account page,"/it/" link to https://kubernetes.io/it/-->
<a class="dropdown-item" href="/it/">Italiano (Italian)</a>
```

**Comment by tamilselvan1102** [comment]
It is happening because the corresponding page in the selected regional language is not available.

**Comment by tamilselvan1102** [comment]
you can help to translate  https://kubernetes.io/docs/concepts/security/service-accounts/ page to your regional language

**Comment by tamilselvan1102** [comment]
if you got the answer, please close the issue
