### ISSUE TITLE
Standardize `sudo` usage and introduce environment variable for consistency in "Upgrading kubeadm clusters" page

### ISSUE THREAD

**Issue by ruckc** [kubernetes/website#42720]
We should make `sudo` usage consistent across the upgrade document.

Also, would it be better to set an environment variable for the new version `KUBEVER=1.28.1-00` and reuse it on all of the `apt/dnf` commands?

**Comment by dipesh-rawat** [comment]
/retitle Standardize `sudo` usage and introduce environment variable for consistency in "Upgrading kubeadm clusters" page
