### ISSUE TITLE
[es] Translate - `docs/concepts/security/security-checklist/` into Spanish

### ISSUE THREAD

**Issue by krol3** [kubernetes/website#42736]
**This is a Feature Request**
Translate this page [docs/concepts/security/security-checklist/](https://kubernetes.io/docs/concepts/security/security-checklist/) into Spanish.

**What would you like to be added**
The translation will be added to `content/es/`docs/concepts/security/security-checklist/

**Why is this needed**
There is no Spanish localization for this file. It would be great if we could read this in Spanish.

**Comments**
The Spanish translation team would like to facilitate your contribution's journey,  any doubt participate in the weekly meetings in the kubernetes slack channel `kubernetes-docs-es`

We also encourage new contributors to participate in their native speaking language 💥.

/triage accepted
/kind feature
/language es
/sig docs

**Comment by khanumar03** [comment]
people can use inbuilt translation in browser.  if I'm wrong, can you elaborate more what exactly need to do.

**Comment by ramrodo** [comment]
Hi @gamba47, doing a follow-up on this issue, do you have any updates on this?

Let us know if we can help :)

**Comment by krol3** [comment]
closing in favor of https://github.com/kubernetes/website/issues/48072
