### ISSUE TITLE
[hi] Update https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/ to align with English

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [kubernetes/website#42735]
**This is a Feature Request**

I want to update this page and make this page doc align with the English one as it is an outdated one.

This https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/   should align with the English one https://kubernetes.io/docs/tutorials/kubernetes-basics/

**Why is this needed**

https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/ looks like stale.
**Comments**

/language hi

**Comment by divya-mohan0209** [comment]
@Vikash-8090-Yadav : Could you advise what is outdated in this, please?

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav : Could you advise what is outdated in this, please?

Hey @divya-mohan0209  sorry for delay reply, at the time of raising the issue I saw this box which state that the content may be outdated so I try to update  some grammtical in the hindi which align with the same version of english but as #4275 is closed. SO, feel free to close this issue as well. Thankss!
