### ISSUE TITLE
EndpointSlice example does not work as documented

### ISSUE THREAD

**Issue by hl843901190** [kubernetes/website#42748]
From：https://kubernetes.io/docs/concepts/services-networking/service/

Chapter： Services without selectors

Ineffective：
![image](https://github.com/kubernetes/website/assets/31186674/bf418d74-afe4-4567-9632-b7a71f216a10)
===》Actually，command ”kubectl get endpointslices” could get 2 specified IP，but iptables can only get first ip
![image](https://github.com/kubernetes/website/assets/31186674/e13b2801-5fbe-4494-b604-b7f68b5d3691)
![image](https://github.com/kubernetes/website/assets/31186674/1e525e20-5181-4314-950d-68590448ff3a)

only iptables rule of 10.4.5.6， no 10.1.2.3
![image](https://github.com/kubernetes/website/assets/31186674/756dfca9-6767-482e-8817-271b64ba3183)

After the modification：
  endpoints:
  - addresses:
      - "10.4.5.6" # the IP addresses in this list can appear in any order
  - addresses:
      - "10.1.2.3"
===》There are 2 separate iptables rules：
![image](https://github.com/kubernetes/website/assets/31186674/39139c36-171b-460b-9b32-3b302bf498e3)
![image](https://github.com/kubernetes/website/assets/31186674/c717f7a4-f5cc-4039-bd3c-beeb82beb228)

**Comment by tengqm** [comment]
This was introduced in 1eef7424651bdc681711572e1042169faebe8e81.

**Comment by sftim** [comment]
This looks like a duplicate of https://github.com/kubernetes/website/issues/42405

I'd prefer to triage the older issue as accepted

/remove-triage accepted
/triage duplicate
