### ISSUE TITLE
Addition of Hover Effect on Buttons 

### ISSUE THREAD

**Issue by iamRabia-N** [kubernetes/website#42756]
### What would you like to be added?

The current design of the buttons in the website is nice but it can be improved by adding hover effect on the buttons. If hover effect is not added because the design change not preferred when user hovers button, for this, we can go for subtle change in design for the user to feel the change when he/she hovers the buttons.

### Sample Work

**Original Design of Button**

![ip (1)](https://github.com/kubernetes/kubernetes/assets/115794049/b216f638-b84c-48c7-8e91-e52765902a18)

**Expected Design on Hovering a Button**

![ip (2)](https://github.com/kubernetes/kubernetes/assets/115794049/35f1e143-38ca-4219-8e81-66abea2cde1e)

### Why is this needed?

It is needed to:
1.Add more design depth to buttons
2. Notify the users about their activity of hovering a button

**Comment by alok0277** [comment]
I would like to work on this issue. can I get this issue to work on?

**Comment by anurag4499** [comment]
Done  addition of Hover Effect on Button , plz merge the code

**Comment by niranjandarshann** [comment]
> Done addition of Hover Effect on Button , plz merge the code

Hi @anurag4499 Thank you for your work, but if you want to allign the PR raised by you to resolve this issue you can give ref of that PR here So that it can be easy to see. For merging the PR you should ask the reviewer by commenting on the PR or reviewer will itself see the issue . Wait for some span of time.

**Comment by anurag4499** [comment]
I solved this issue

**Comment by niranjandarshann** [comment]
> /approve

@anurag4499 This labeling is used in PR  for approving it with required review. This will be done by the approver. This right is not to all.  You cannot use it here .

**Comment by Gauravpadam** [comment]
Closing this as fixed by https://github.com/kubernetes/website/pull/42929

/close
