### ISSUE TITLE
Kube-proxy port 31385 supporting Tlsv1.1, Tlsv1.0, it need to disable

### ISSUE THREAD

**Issue by devendra614** [kubernetes/website#42754]
we have cloud native computing foundation kubernetes cluster where it component kube-proxy supporting port port 31385 Tlsv1.1. Tlsv1.0. We have to disable it and enable Tlsv1.2.

Please guide it

**Comment by tamilselvan1102** [comment]
You can configure this in the configmap https://github.com/kubernetes/ingress-nginx/blob/309a79483f3cc3d9eb70cb826d4c77dd639a70ed/docs/user-guide/tls.md#default-tls-version-and-ciphers

**Comment by thisisharrsh** [comment]
Hi @devendra614, it looks like you need some support for the enabling of `TLSv1.2 `you can follow the [link](https://github.com/kubernetes/ingress-nginx/blob/309a79483f3cc3d9eb70cb826d4c77dd639a70ed/docs/user-guide/tls.md#default-tls-version-and-ciphers) for the same.

**Comment by devendra614** [comment]
Thank you so much.
