### ISSUE TITLE
Unknown reference of  Portworx CSI  Drivers .

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#42752]
**This is a Bug Report**

The link of Portworx CSI Driver  in https://kubernetes.io/docs/concepts/storage/volumes/#portworx-csi-migration is  broken.

**Problem:**
It is referring to the 404 Page not found.

**Proposed Solution:**
Should be updated with the correct link and if not required then link should be removed.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/#portworx-csi-migration

**Comment by niranjandarshann** [comment]
I think there are two possible Solution :
1.  https://docs.portworx.com/portworx-enterprise/operations/portworx-csi-driver
2.  https://docs.portworx.com/portworx-enterprise/operations/operate-kubernetes/storage-operations/csi 
Can you all suggest me with the correct link that is appropriate for the reffered one.
/help-wanted

**Comment by niranjandarshann** [comment]
I think there are two possible Solution :

    https://docs.portworx.com/portworx-enterprise/operations/portworx-csi-driver
    https://docs.portworx.com/portworx-enterprise/operations/operate-kubernetes/storage-operations/csi
    Can you all suggest me with the correct link that is appropriate for the reffered one.
    /help

**Comment by alok0277** [comment]
On search on portworx with kubernetes installation we got this links.  Which is same which making request from offical kubernetes website. On open we got an change in slug of portworx official.

![image](https://github.com/kubernetes/website/assets/120774363/2993bd3c-4019-4574-978d-f0645ff9f3a5)

So, This link is appropriate as if we want to operate with kubernetes installation.
![image](https://github.com/kubernetes/website/assets/120774363/e3117a16-b2e8-4735-bcf5-6174a7c3e643)

**Comment by niranjandarshann** [comment]
> On search on portworx with Kubernetes installation, we got these links. Which is the same as making a request from the official Kubernetes website. On open we got a change in a slug of portworx official.
> 
> ![image](https://user-images.githubusercontent.com/120774363/263703611-2993bd3c-4019-4574-978d-f0645ff9f3a5.png)
> 
> So, This link is appropriate if we want to operate with Kubernetes installation.
> 
> ![image](https://user-images.githubusercontent.com/120774363/263704787-0a9a2730-dcc8-4415-92fa-588be464a48b.png)
> 
> If these changes are solution,
> 
> can i get this issue to work on ? .

Hi @alok0277  I also think the same link will be good but waiting for more reply about the same. I will proceed ahead after the confirmation by people.

**Comment by AmarNathChary** [comment]
I will raise a PR for this
/assign

**Comment by AmarNathChary** [comment]
Raised PR fo this in #43049

**Comment by tengqm** [comment]
/close
as resolved.
