### ISSUE TITLE
Generate Certificates Manually task is inconsistent

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42761]
> https://kubernetes.io/docs/tasks/administer-cluster/certificates/

The page contains three ways to achieve the same result using three different utilities. But there are some differences in the end results that are disconcerting and make you wonder why it has to be this way? It doesn't seem to make sense.
There are two areas of concern — subject names and key usages.

1) All CA certificates have different subject Common Name:
 - easyrsa — `${MASTER_IP}@date`
 - openssl — `${MASTER_IP}`
 - cfssl — `kubernetes`

<br>

According to [PKI certificates and requirements](https://kubernetes.io/docs/setup/best-practices/certificates/#single-root-ca) page CA CN defaults to `kubernetes-ca`. It might be worth changing the documentation to use one common value.

<br>

2) Some CA certificates have different X509v3 Key Usage:
 - easyrsa and cfssl — Certificate Sign, CRL Sign
 - openssl — n/a

<br>

To fix this, one can change the command in [OpenSSL step 2](https://kubernetes.io/docs/tasks/administer-cluster/certificates/#openssl) to the following:

```bash
openssl req -x509 -new -nodes -key ca.key -subj "/CN=${MASTER_IP}" -days 10000 -out ca.crt -addext 'keyUsage = cRLSign, keyCertSign'
```

<br>

3) Some kube-apiserver certificates have different X509v3 Key Usage and X509v3 Extended Key Usage:
 - easyrsa:
	- Key Usage: Digital Signature, Key Encipherment
	- Extended Key Usage: **TLS Web Server Authentication**
 - openssl:
 	- Key Usage: Key Encipherment, **Data Encipherment**
	- Extended Key Usage: TLS Web Server Authentication, TLS Web Client Authentication
 - cfssl:
 	- Key Usage: Digital Signature, Key Encipherment
	- Extended Key Usage: TLS Web Server Authentication, TLS Web Client Authentication

<br>

To fix the easyrsa issue, one can change the string `extendedKeyUsage = serverAuth` in the file `server` in the "x509-types" directory to `extendedKeyUsage = serverAuth,clientAuth`:

```bash
sed  -e 's/\(extendedKeyUsage\).*/\1 = serverAuth,clientAuth/' $( easyrsa | grep x509-types | awk '{ print $2 }' )/server
```

<br>

To fix the openssl issue, one can change the string `keyUsage=keyEncipherment,dataEncipherment` in [OpenSSL step 4](https://kubernetes.io/docs/tasks/administer-cluster/certificates/#openssl) to `keyUsage=digitalSignature,keyEncipherment`.

<br>

4) Some kube-apiserver certificates have different subject Common Name and X509v3 Subject Alternative Name:
 - easyrsa:
	- CN: server
	- SAN: IP Address:`${MASTER_IP}`, IP Address:`${MASTER_CLUSTER_IP}`, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc.cluster.local
 - openssl:
	- CN: `${MASTER_IP}`
	- SAN: DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc.cluster.local, IP Address:`${MASTER_IP}`, IP Address:`${MASTER_CLUSTER_IP}`
 - cfssl:
	- CN: kubernetes
	- SAN: DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc.cluster.local, **IP Address:127.0.0.1**, IP Address:`${MASTER_IP}`, IP Address:`${MASTER_CLUSTER_IP}`

<br>

According to the [PKI certificates and requirements](https://kubernetes.io/docs/setup/best-practices/certificates/#all-certificates) CN should be `kube-apiserver`.

<br>

As for SAN, consider using the same set of values (with or without localhost which can be in the form of an IP or hostname) and the order (DNS, loopback address, IP) for each method, for example:

```plaintext
DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster, DNS:kubernetes.default.svc.cluster.local, DNS:localhost, IP Address:`${MASTER_CLUSTER_IP}`, IP Address:`${MASTER_IP}`
```

<br>

Also there are different configuration or lack thereof for X509v3 Authority Key Identifier extension across all the certificates, but this is more of less OK.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tasks/administer-cluster/certificates/
/language en

**Comment by sftim** [comment]
/retitle Generate Certificates Manually task is inconsistent
/kind bug

**Comment by sftim** [comment]
/sig security
/remove-lifecycle rotten

Let's triage this
