### ISSUE TITLE
Trouble following tutorial Using a Service to Expose Your App

### ISSUE THREAD

**Issue by joeythomaschaske** [kubernetes/website#42777]
Following the steps [here](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/) I get to the step where I create a NodePort service and use `curl` to access it.

```
Now we can test that the app is exposed outside of the cluster using curl, the IP address of the Node and the externally exposed port:

curl http://"$(minikube ip):$NODE_PORT"

And we get a response from the server. The Service is exposed.
```

I do not get a response and eventually get the error

`curl: (28) Failed to connect to 192.168.49.2 port 30140 after 75007 ms: Couldn't connect to server`

Additionally the docs say there should be an external IP assigned after adding a NodePort service

```
We have a Service called kubernetes that is created by default when minikube starts the cluster. To create a new service and expose it to external traffic we'll use the expose command with NodePort as parameter.

kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080

Let's run again the get services subcommand:

kubectl get services

We have now a running Service called kubernetes-bootcamp. Here we see that the Service received a unique cluster-IP, an internal port *and an external-IP (the IP of the Node).*
```
However I don't see this

```
% kubectl get services
NAME                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
kubernetes            ClusterIP   10.96.0.1        <none>        443/TCP          160m
kubernetes-bootcamp   NodePort    10.107.221.142   <none>        8080:30552/TCP   6m8s
```

Running `minikube service kubernetes-bootcamp` does work to expose it though

**Comment by dipesh-rawat** [comment]
Duplicate related issues we already have #41438 #40645 #42713

**Comment by Affan-7** [comment]
> Duplicate related issues we already have #41438 #40645 #42713

Let's fix this, a lot of people are facing this issue.

/assign

**Comment by adityasamant25** [comment]
https://github.com/kubernetes/website/issues/40645 is now closed.
I believe it is sufficient to close this issue as well.
