### ISSUE TITLE
Vertical white space line causing layout break in mobile view of "Community" page

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#42795]
**This is a Bug Report**

**Problem:**
There is unusual vertical white space line at right side in whole community tab of kubernetes website, when viewed in mobile (Refer below screenshot)

**Page to Update:**
https://kubernetes.io/community

**Optional Information:**
Browser - Google Chrome

![Screenshot_2023-08-30-20-53-53-819_com android chrome (1)](https://github.com/kubernetes/website/assets/116108975/d261e686-acad-4f71-98a2-d315de23d155)

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/community/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Vertical white space line causing layout break in mobile view of "Community" page
/area web-development

**Comment by dipesh-rawat** [comment]
Looks similar (possibly duplicate) of issue we already have https://github.com/kubernetes/website/issues/42314

**Comment by satyampsoni** [comment]
I can't see any hamburger icon or the white space when I opened the link in the mobile.
![image](https://github.com/kubernetes/website/assets/94950988/2f68c539-ae31-42a0-a918-dd18c0617a62)

**Comment by aj11anuj** [comment]
Zoom out your screen to view it

**Comment by satyampsoni** [comment]
No worries! I'll try to fix it.

**Comment by sftim** [comment]
How's this work going?

**Comment by Gauravpadam** [comment]
#43740 should fix this

**Comment by aj11anuj** [comment]
Issue is fixed now
/close
