### ISSUE TITLE
Kubernetes icon alignment and overlapping issues in mobile view of "Blog" tab

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#42796]
**This is a Bug Report**

**Problem:**
Kubernetes icon at top most center in Kubernetes-blog tab have issues when scrolling the website in mobile view. That icon gets sticked to the top most part of sticky navbar and its upper part also gets cutted. (Refer below Screenshots)

**Page to Update:**
https://kubernetes.io/blog/

![Screenshot_2023-08-30-20-59-29-821_com android chrome](https://github.com/kubernetes/website/assets/116108975/e9f449d7-5a51-4208-a635-956e251a0aef)

![Screenshot_2023-08-30-21-00-01-570_com android chrome](https://github.com/kubernetes/website/assets/116108975/2463b41a-b80c-4899-b287-b6465142f702)

![Screenshot_2023-08-30-22-12-12-061_com android chrome](https://github.com/kubernetes/website/assets/116108975/47b4edf3-e5a1-4c57-a3c3-09e7480b74f2)

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/blog/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Kubernetes icon alignment and overlapping issues in mobile view of "Blog" tab
/area web-development

**Comment by kumarankit999** [comment]
Can I work on it

**Comment by garrettsiegel** [comment]
Hi @aj11anuj, could you please use this site — https://www.whatsmybrowser.org — to let me know which device(s) and browser(s) you're experiencing this issue on? I've tried to replicate the issue on my end but have been unable to do so. Thanks!

**Comment by aj11anuj** [comment]
@garrettsiegel, When I opened this issue i was using Chrome 95 (1.5yr old) but now I'm using Firefox 117 and this issue is still there.

[Firefox 117 and OS related info](https://www.whatsmybrowser.org/b/AFX5F)

**Comment by sftim** [comment]
/priority backlog
Which pages do and don't show these symptoms?

**Comment by aj11anuj** [comment]
1. Only this page "Blog" tab is showing this issue, i have checked all the pages and those aren't showing any symptom of this issue. 
2. This page "Blog" tab also showing one other symptom similar to #42795

**Comment by aj11anuj** [comment]
Just found this issue on this page too [Booking.com Case Study](https://kubernetes.io/case-studies/booking-com/) it's also showing #42795

**Comment by kumarankit999** [comment]
What we can do further here!
