### ISSUE TITLE
Unclear documentation about trace linking between Kubernetes components, container runtime and OpenTelemetry collector

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42804]
> https://kubernetes.io/docs/concepts/cluster-administration/system-traces/#enabling-tracing-in-the-kubelet
> Connected container runtimes like CRI-O and containerd can link the traces to their exported spans to provide additional context of information.

This sentence is unclear because of the word "link", which calls into question the early notion of data flows between the Kubernetes components, container runtime and OpenTelemetry collector. You're trying to rethink how data flows and where traces might be linked.

---

Connected [to kubelet?] container runtimes like CRI-O and containerd can link [how?] the traces [traces from Kubernetes?] to their exported spans [exported to whom?] to provide additional context of information.

---

Does this mean that if tracing is enabled for kubelet, it forces the container runtime to send its traces to kubelet? But how can a container runtime link its traces with external traces without receiving them, since kubelet is the initiator, not the container runtime?
Or are the kubelet and container traces independently sent to the trace backend (using collectors) where they can be linked somehow?
So many assumptions, please add clarification.

UPDATE: I was wrong about the initiator, according to [CRI Event-based Updates](https://github.com/kubernetes/enhancements/blob/5b258a990adabc2ffdc9d84581ea6ed696f7ce6c/keps/sig-node/3386-kubelet-evented-pleg/README.md#pod-status-update-in-the-cache) I think a container runtime might be it.

**Comment by dipesh-rawat** [comment]
/retitle Unclear documentation about trace linking between Kubernetes components, container runtime and OpenTelemetry collector

**Comment by sftim** [comment]
/priority backlog
/triage accepted

If this rots out, I recommend not removing the staleness marker. We may not have enough volunteers to cover every improvement.

Help is, of course, very welcome!
