### ISSUE TITLE
Backport `layouts/docs/release-info.html` to covered older releases

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42812]
**What needs doing?**
For each branch:
- _release-1.24_
- _release-1.25_
- _release-1.26_
- _release-1.27_

(these are the supported old docs releases)

&hellip;copy `layouts/docs/release-info.html` from _main_ and open a pull request to update the selected branch, so that `layouts/docs/release-info.html` exactly matches the copy in _main_

**Why is this needed**
Part of issue #42810

**Comments**
/sig release docs

**Comment by dipesh-rawat** [comment]
I can take help with this and ensure that release-info.html is properly backported.

/assign

**Comment by dipesh-rawat** [comment]
I have raised PRs #42814 #42815 #42816 #42817 addressing the backporting of the layout as requested.

**Comment by sftim** [comment]
Done!


/close
