### ISSUE TITLE
Fix broken update-imported-docs.sh

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#4283]
It's not clear whether anybody has ran the `update-imported-docs.sh` for the v1.7 release.

I just tried running it, a few things are broken:

- [ ] 1. `cp: cannot stat 'k8s/cluster/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml': No such file or directory` this is because [we copy this file](https://github.com/kubernetes/kubernetes.github.io/blob/41c395771a12507a10ade75918944e8a731be040/_data/overrides.yml#L10) and not use anywhere else. we should remove this. &rarr; PR #4285.
- [ ] 2. `yes | cp -rf -- k8s/federation/docs/api-reference/ docs/federation/` fails with `cd: docs/federation/api-reference: No such file or directory`
    > - it looks like we moved this to `/docs/reference/federation` path and not updated the script. It also appears that `/docs/federation` never existed(??)
    > - it looks like if I fix the copypath in `_data/overrides.yaml`, this script creates a `docs/reference/federation/api-reference` directory, instead of copying things in `api-reference` to `docs/reference/federation`.

Will add more issues if I find them.

/cc: @pwittrock @chenopis

**Comment by chenopis** [comment]
I think @mengqiy would know how to fix this.

**Comment by ahmetb** [comment]
It also appears like Phillip has ran the script successfully at #4193. I am not sure why the (2) didn't fail back then.

**Comment by ahmetb** [comment]
I poked at this quite a bit still can't fix the `docs/federation/api-reference` issue. Here's my patch for the file:


 I ended up deleting that dir altogether since it is not versioned anyway, the script completed successfully however:
- the output is not correct
- it added `---\n---\n` to existing files. that doesn't sound right.

I'll probably be spending a few more hours on this with no good reason (this script takes 4 minutes to run every time) so I'll call help. @mengqiy can you help out? Maybe we should replace this script with something more manageable like python/go.

**Comment by mengqiy** [comment]
> It also appears like Phillip has ran the script successfully at #4193.

That PR is updating the new style doc e.g. https://kubernetes.io/docs/api-reference/v1.7

> it added ---\n---\n to existing files.

It happened last time as well. I manually delete those lines, since there are not too many and I don't have enough time to debug it.

> Maybe we should replace this script with something more manageable like python/go.

Sound good. I will vote for python. I can help review it.

**Comment by mengqiy** [comment]
Any update?
Is the imported doc up-to-date?

**Comment by ahmetb** [comment]
@mengqiy Nope, currently we don't know why

1. the script breaks for Federation API reference
2. why it didn't update `docs/user-guide/kubectl/index.md` (see #4253)

I appreciate if you can take a look.

**Comment by mengqiy** [comment]
Sure. Looking.

**Comment by mengqiy** [comment]
After digging a bit,

> 1. the script breaks for Federation API reference

Structure in https://github.com/kubernetes/kubernetes.github.io/tree/master/docs/reference/federation and https://github.com/kubernetes/kubernetes/tree/master/federation/docs/api-reference are different. I will pull federation in for help. @nikhiljindal @madhusudancs 

> 2. why it didn't update docs/user-guide/kubectl/index.md

That doc doesn't exist in upstream any more. So the script doesn't update it.
And there is no link going to it. I think maybe we can delete it. https://kubernetes.io/docs/user-guide/kubectl/index.html

**Comment by nikhiljindal** [comment]
> it looks like we moved this to /docs/reference/federation path and not updated the script. It also appears that /docs/federation never existed(??)

Not sure when reference was added in the path, but I remember when I first added federation docs, I added them to `/docs/federation` so that dir did exist. Will try to dig up the PR.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/1222 is the PR.

We were copying autogenerated federation docs from `kubernetes/federation/docs/api-reference/` to `kubernetes.github.io/docs/federation/` and it used to work fine.

Any idea when did we add `reference` in the path?
Just updating those paths to include `reference` should fix the problem?

**Comment by mengqiy** [comment]
I think we can stop maintaining `update-imported-docs.sh`, but write a python version instead after #4354 merged.

**Comment by chenopis** [comment]
@mengqiy Is the Python version in the works? Are we keeping this issue open still?

**Comment by mengqiy** [comment]
I don't have bandwidth at this time.
@ahmetb Are you working the python or go version?

**Comment by ahmetb** [comment]
I am not working on this right now either, we can still keep patching it with fixes to federation issues. I am not sure how they're fixed for the 1.7 release.

**Comment by chenopis** [comment]
We really need to sit down together and figure out a long term plan and who owns what. I'm still a little foggy on everything. :(
