### ISSUE TITLE
Bad accessibility on https://k8s.io

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42832]
**This is a Bug Report**

**Problem:**
Lots of the images on https://k8s.io/ (the front page for the whole site) have `alt` attributes that are the filename, or something else not so helpful.

**Proposed Solution:**
Change the alt attributes to be either the empty string (if not relevant), or to be meaningful to someone hearing the web page.

**Page to Update:**
https://kubernetes.io/

**Additional Information:**
/area web-development

**Comment by dipesh-rawat** [comment]
Improving accessibility is crucial. Let's update these alt attributes for a better overall user experience. 

/triage accepted
/priority backlog
