### ISSUE TITLE
KubeletPodResources is GA, but is still mentioned as a switchable feature gate

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42841]
> https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-getallocatableresources
> Support for the PodResourcesLister service requires KubeletPodResources feature gate to be enabled. It is enabled by default starting with Kubernetes 1.15 and is v1 since Kubernetes 1.20.

The "KubeletPodResources" feature gate is GAed, but it's still mentioned as a switchable one in the [GetAllocatableResources gRPC endpoint](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-getallocatableresources) section. Perhaps it's time to remove it from the page.

This fact is mentioned in https://github.com/kubernetes/website/pull/27575.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/
/language en

**Comment by tengqm** [comment]
/triage accepted
PRs welcomed.

**Comment by pegasas** [comment]
/assign @pegasas 
I am working on it.

**Comment by Shubham82** [comment]
closing this issue as it was resolved by following PR #42860
Thanks @pegasas
