### ISSUE TITLE
Slack icon at 'footer' and 'right side' of Blogs page is outdated, and needs to be updated

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#42847]
**This is a Feature/Enhancement Request**

**What would you like to be enhanced**
The Slack icon at footer and right side of the [Blogs Page](https://kubernetes.io/blog/) is outdated and needs to be replaced with current slack icon like the one present in [Home page](https://kubernetes.io/) of K8s website

![Screenshot (795)](https://github.com/kubernetes/website/assets/116108975/071af503-31d1-4aaa-bbaa-245762a47f7c)

**Additional information**
This issue is present only in Blogs page, rest of the pages have updated slack icon

**Comment by saloni0419** [comment]
/assign
I want to work on this issue, Please assign me this

**Comment by dipesh-rawat** [comment]
/remove-help /remove-good-first-issue

@aj11anuj Refrain from marking issues as good first issues until they've been triaged as Accepted.

**Comment by dipesh-rawat** [comment]
/remove-help
/remove-good-first-issue

@aj11anuj Refrain from marking issues as good first issues until they've been triaged as Accepted.

**Comment by aj11anuj** [comment]
> /remove-help /remove-good-first-issue
> 
> @aj11anuj Refrain from marking issues as good first issues until they've been triaged as Accepted.

Yes, yes i learnt about this thing 1-2 days back in someone else's issue by Tim sir. But I have some queries, could you answer these @dipesh-rawat :-

Q. When a triage is accepted? (When a Lead/Co-chair/Approver or similar trusted person approve that issue to be accepted, right?)
Q. Can this label be putted by Leads/Co-chairs/Approvers only?

**Comment by reylejano** [comment]
> > /remove-help /remove-good-first-issue
> > @aj11anuj Refrain from marking issues as good first issues until they've been triaged as Accepted.
> 
> Yes, yes i learnt about this thing 1-2 days back in someone else's issue by Tim sir. But I have some queries, could you answer these @dipesh-rawat :-
> 
> Q. When a triage is accepted? (When a Lead/Co-chair/Approver or similar trusted person approve that issue to be accepted, right?) Q. Can this label be putted by Leads/Co-chairs/Approvers only?

Any Kubernetes org member can label an issue as triage/accepted

**Comment by Gauravpadam** [comment]
Hey @SwathiR03, You don't need an assignment to work on issues, Please feel free to propose a fix

You can self-assign to let others know you're working on this by writing /assign

**Comment by SwathiR03** [comment]
/assign 

Thanks for the heads-up!

**Comment by draunger** [comment]
I will do this task can you tell me detailed issue

**Comment by draunger** [comment]
@Gauravpadam can you tell me the exact path of the logo of the blog page as I am unable to find it

**Comment by Gauravpadam** [comment]
@draunger you won't find a logo path as such. This problem is likely due to an outdated script being used in `layouts/blog/baseof.html` , I would investigate that

**Comment by sirsuspicious21** [comment]
I would like to work on this issue
/assign #42847

**Comment by sftim** [comment]
> the exact path of the logo of the blog page

It's part of Font Awesome, so I suppose [`svgs/brands/slack.svg`](https://github.com/FortAwesome/Font-Awesome/blob/dcdc48a561e3db6e6caa2002f14d77f68aa01ed6/svgs/brands/slack.svg) would be right.

I think the fix is to remove https://github.com/kubernetes/website/blob/5ebf07dbb616e6854770ef482ecf0be9fec54e83/layouts/blog/baseof.html#L9    &nbsp;—  try that locally and see if it helps.

---
:information_source: “Fort Awesome” is [not](https://www.impresspages.org/awesome-q-a-with-font-awesome-developer-dave-gandy) a typosquat, even though it looks like one.

**Comment by Manish-hr14** [comment]
@sftim needful

> > the exact path of the logo of the blog page
> 
> It's part of Font Awesome, so I suppose [`svgs/brands/slack.svg`](https://github.com/FortAwesome/Font-Awesome/blob/dcdc48a561e3db6e6caa2002f14d77f68aa01ed6/svgs/brands/slack.svg) would be right.
> 
> I think the fix is to remove
> 
> https://github.com/kubernetes/website/blob/5ebf07dbb616e6854770ef482ecf0be9fec54e83/layouts/blog/baseof.html#L9
> 
>  — try that locally and see if it helps.
> ℹ️ “Fort Awesome” is [not](https://www.impresspages.org/awesome-q-a-with-font-awesome-developer-dave-gandy) a typosquat, even though it looks like one.

needful has been done...
