### ISSUE TITLE
[hi] Move Hindi "what-is-kubernetes" to "Overview" page for alignment with main website

### ISSUE THREAD

**Issue by abhay-raj19** [kubernetes/website#42844]
As some of the pages do have hindi localisation which also helps native Hindi speaker and readers to go through the docs.

Why it is necessary? 
As many of the learners are from hindi background and do not have good control on other languages , in that case it can help those leaners.

Will be completing it as soon as possible after the assign of the issue.

<img width="947" alt="image" src="https://github.com/kubernetes/website/assets/96302417/3ee11bc1-4098-4021-a3c5-6b3a880fb783">

**Comment by dipesh-rawat** [comment]
It appears that the Hindi language's Overview page is currently located under the https://kubernetes.io/hi/docs/concepts/overview/what-is-kubernetes/ which was added as part of PR #30847. 

On the main website _(i.e. English content)_, the "what-is-kubernetes" content was moved into the [Overview](https://kubernetes.io/docs/concepts/overview/) page through PR #35298 _(contains refactor label)_. The main issue here seems to be that the existing localized Hindi page content in "[what-is-kubernetes.md](https://github.com/kubernetes/website/blob/main/content/hi/docs/concepts/overview/what-is-kubernetes.md)" may also need to be relocated in alignment with the main website for consistency.

**Comment by dipesh-rawat** [comment]
/retitle [hi] Move Hindi "what-is-kubernetes" to "Overview" page for alignment with main website

**Comment by abhay-raj19** [comment]
Hey @dipesh-rawat can you explain in some broad way I am not getting it pls explain  it again.

**Comment by steve-hardman** [comment]
I would like to work, based on information shared.

/assign

**Comment by abhay-raj19** [comment]
i am working on it .

/assign

**Comment by aj11anuj** [comment]
@abhay-raj19 are you working on it?

You just have to:-
1. Rename the title key-value pair of [this file](https://github.com/kubernetes/website/blob/main/content/hi/docs/concepts/overview/what-is-kubernetes.md?plain=1) to "अवलोकन".
![Screenshot (835)](https://github.com/kubernetes/website/assets/116108975/10fd0e11-5065-455d-801a-0417b2bf26f5)
2. Rename the name of the file from "what-is-kubernetes.md" to "_index.md".

**Comment by abhay-raj19** [comment]
@aj11anuj yes yes i am working on it and will raise up the PR ASAP.

**Comment by dipesh-rawat** [comment]
Fixed by https://github.com/kubernetes/website/pull/44093
/close
