### ISSUE TITLE
KubeletPodResourcesDynamiceResources is not mentioned in GA or deprecated feature gates table

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#42842]
> https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

The "KubeletPodResourcesDynamiceResources" feature gate is not in the feature gates tables ([Feature gates for Alpha or Beta features](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features) or [Feature gates for graduated or deprecated features](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features)), it's only on the [List of feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates). I think it should be added to [the GA or deprecated table](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features).

**Comment by tengqm** [comment]
`KubeletPodResourcesDynamiceResources` is a typo, notice the extra `e` before the last `Resources` word.
PRs welcome.

**Comment by dipesh-rawat** [comment]
> `KubeletPodResourcesDynamiceResources` is a typo, notice the extra `e` before the last `Resources` word. PRs welcome.

I have raised PR https://github.com/kubernetes/website/pull/42851 to fix the typo

**Comment by nnlkcncff** [comment]
> https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-list
> --feature-gates=DynamicResourceAllocation=true,KubeletPodResourcesDynamiceResources=true

> https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-get
> --feature-gates=KubeletPodResourcesGet=true,DynamicResourceAllocation=true,KubeletPodResourcesDynamiceResources=true

I should have mentioned the page where I saw the typo — there are still two typos there.

**Comment by dipesh-rawat** [comment]
> > https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-list
> > --feature-gates=DynamicResourceAllocation=true,KubeletPodResourcesDynamiceResources=true
> 
> > https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#grpc-endpoint-get
> > --feature-gates=KubeletPodResourcesGet=true,DynamicResourceAllocation=true,KubeletPodResourcesDynamiceResources=true
> 
> I should have mentioned the page where I saw the typo — there are still two typos there.

@nnlkcncff These typos should be fixed now after merge of PR [#42919](https://github.com/kubernetes/website/pull/42919/files)
