### ISSUE TITLE
Icons in footer doesn't have consistent style across all pages in mobile view

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#42843]
**This is a Bug Report**

**Problem:**
There are 2 aspects of this problem:-
1. The icons in footer across all pages should look like the icons present in footer of [Docs Page](https://kubernetes.io/docs/home/) but the icons in footer of [Blogs Page](https://kubernetes.io/blog/) is not looking like that in mobile view. (Refer below screenshot)
2. When i enable desktop mode in mobile, then this problem is present in all pages. (Refer below screenshot)

**Pages to Update:**
1. For mobile view: [Blogs Page](https://kubernetes.io/blog/)
2. For mobile, with desktop mode enabled: All pages

**Additional Information:**

![bb](https://github.com/kubernetes/website/assets/116108975/fb5c0b4a-f942-41d8-b4a3-83b91fe5eef1)
![cc](https://github.com/kubernetes/website/assets/116108975/afffa9b0-1c70-4461-904b-3b4deb44f02a)
![Aa](https://github.com/kubernetes/website/assets/116108975/70e8e46f-7617-4ef4-98b8-e5d42c2af0fe)

/area web-development

**Comment by subhamo1** [comment]
triage/accepted
