### ISSUE TITLE
doc for kube-scheduler option --logging-format  is not up to date

### ISSUE THREAD

**Issue by yiwenshao** [kubernetes/website#42850]
The newest version of kube-scheduler supports --logging-format json. However, the doc still says "Sets the log format. Permitted formats: text"

<img width="567" alt="截屏2023-09-03 21 40 16" src="https://github.com/kubernetes/website/assets/10302159/e6ed2006-e95f-4997-a832-a20ea2bb3726">

**Comment by AmarNathChary** [comment]
_Page related to issue_ : https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

**Comment by dipesh-rawat** [comment]
Looks like the reference page for kube-scheduler is [automatically generated](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler//#auto-generated-edit-notice). We've recently merged PR #42571, which updated the component reference documentation for v1.28. If this an issue, it might be beneficial to investigate the generator code or evaluate the input it utilizes.

**Comment by tengqm** [comment]
The "json" logging format is gated by the `LoggingStableOptions` gate, and so is not shown by default.

**Comment by yiwenshao** [comment]
> The "json" logging format is gated by the `LoggingStableOptions` gate, and so is not shown by default.

kube-scheduler -h shows  'Sets the log format. Permitted formats: "json" (gated by LoggingBetaOptions), "text". (default "text")'. would using this output in doc be a better choice?

**Comment by tengqm** [comment]
> > The "json" logging format is gated by the `LoggingStableOptions` gate, and so is not shown by default.
> 
> kube-scheduler -h shows 'Sets the log format. Permitted formats: "json" (gated by LoggingBetaOptions), "text". (default "text")'. would using this output in doc be a better choice?

Yes. It is. However, the upstream component design has reinvented the logic to pass command flags. They are replacing the existing pflags module with manual hackings. If the community has decided to go down this path, we won't be able to generate command reference soon. I'm doubting if anyone else from the community would like to dig more into this.
