### ISSUE TITLE
Misleading text in Pod Security Admission metrics

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42853]
**This is a Bug Report**

**Problem:**
The term “evaluation“ in the metrics section of the Pod Security Admission page is slightly misleading.

**Proposed Solution:**
Change “_evaluation_“ to “_enforcement_” in the text:
>   Non-fatal errors may result in the latest restricted profile being used for enforcement.

**Page to Update:**
https://k8s.io/docs/concepts/security/pod-security-admission/

**Additional Information:**
Mentioned as https://github.com/kubernetes/website/pull/41814#discussion_r1293784723
/good-first-issue
/language en

(extra credit: also tell readers that they can find more detail in https://kubernetes.io/docs/reference/instrumentation/metrics/)

**Comment by dipesh-rawat** [comment]
Fixed with #42856

/close
