### ISSUE TITLE
Navbar hamburger icon overlaps with white space in "Community" page

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/website#42854]
**This is a Bug Report**

![WhatsApp Image 2023-09-03 at 23 52 23](https://github.com/kubernetes/website/assets/111564362/ece522ea-f1d8-4779-b5e0-e5d5a09ad9b4)

The Navbar file icon option is getting out from the main context and it lies in the white portion

**Proposed Solution:**
Improve or Update by resizing and making it into the orange portion of Kubernetes Navbar

**Page to Update:**
https://kubernetes.io/community/

**Comment by dipesh-rawat** [comment]
/retitle Navbar hamburger icon overlaps with white space in "Community" page

**Comment by dipesh-rawat** [comment]
Looks duplicate of issue we already have https://github.com/kubernetes/website/issues/42314

/remove-help
/remove-good-first-issue
/remove-language en
/triage duplicate

**Comment by anurag4499** [comment]
triage/accepted

**Comment by satyampsoni** [comment]
@anurag4499 if you are not the org member please don't comment triage/accepted

**Comment by anurag4499** [comment]
okay 
plz  tell me how to assing this work

**Comment by anurag4499** [comment]
https://deploy-preview-43077--kubernetes-io-main-staging.netlify.app/community/ 
 i did this work

**Comment by aj11anuj** [comment]
Issue is fixed now
/close
