### ISSUE TITLE
Unknown References in Types of Persistent Volumes

### ISSUE THREAD

**Issue by thisisharrsh** [kubernetes/website#42868]
**This is a Bug Report**

**Problem:** In the [Types of Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes) section of the [Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) page, there are some `PersistentVolume` types that were supported by an older version of `Kubernetes.` Those `PersistentVolume` types are not present in the documentation as they have been removed.

**Proposed Solution:** To remove the references from the hyperlinks from the `PersistentVolume` can be a solution, as there is no information present in the recent release of `Kuberetes.`

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by sftim** [comment]
The likely fix:  retain list items that have broken hyperlinks, but remove the hyperlinking.

**Comment by thisisharrsh** [comment]
> The likely fix: retain list items that have broken hyperlinks, but remove the hyperlinking.

Yes, I also think that we should remove the hyperlinking.

**Comment by thisisharrsh** [comment]
I would like to work on this issue. 
/assign
