### ISSUE TITLE
Broken Link to OWASP Zed Attack proxy

### ISSUE THREAD

**Issue by ClimberJ** [kubernetes/website#42874]
**This is a Bug Report**

**Problem:**
The link to [OWASP Zed Attack proxy](https://owasp.org/www-project-zap/) in the code security section of https://kubernetes.io/docs/concepts/security/overview/ leads to a 404 error.

**Proposed Solution:**
Replace the link with a working one or remove it.

**Page to Update:**
https://kubernetes.io/docs/concepts/security/overview/#code-security

**Comment by Shubham82** [comment]
can we use the following link for ZAP: https://www.zaproxy.org/
This is a ZAP website.

**Comment by Shubham82** [comment]
> can we use the following link for ZAP: https://www.zaproxy.org/
> The above link redirects to the ZAP website.

cc @sftim your thoughts on this
