### ISSUE TITLE
Inconsistent API group in ValidatingAdmissionPolicy concept / reference page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42876]
**This is a Bug Report**

**Problem:**
The page about ValidatingAdmissionPolicy uses a mixture of API groups: `admissionregistration.k8s.io/v1alpha1` and `admissionregistration.k8s.io/v1beta1`.

**Proposed Solution:**
Be consistent; only use `admissionregistration.k8s.io/v1beta1`.

**Page to Update:**
https://k8s.io/docs/reference/access-authn-authz/validating-admission-policy/

**Additional Information:**
/sig api-machinery
/language en

**Comment by AmarNathChary** [comment]
I would like to work on this
/assign

**Comment by T-Lakshmi** [comment]
This issue got fixed by merging PR #42879.
Please close the issue.

**Comment by sftim** [comment]
This issue got fixed by merging PR https://github.com/kubernetes/website/pull/42879.
/close
