### ISSUE TITLE
Annotation `service.beta.kubernetes.io/aws-load-balancer-security-groups` not documented / registered

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42881]
**This is a Bug Report**

**Problem:** Some in-project code is using an annotation, `service.beta.kubernetes.io/aws-load-balancer-security-groups`. We haven't documented this in https://kubernetes.io/docs/reference/labels-annotations-taints/ (which also means it's not registered).

**Proposed Solution:**
Document the annotation
**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/sig cloud-provider
/language en

PS. Contributors should not define new annotations that include “beta” or “alpha” labels, and should plan to migrate to annotations or something else that do not have this quality.

**Comment by Ritikaa96** [comment]
I would like to add this. 
/assign

**Comment by Ritikaa96** [comment]
Raised a PR: https://github.com/kubernetes/website/pull/43009
I am confused regarding this statement though:

> PS. Contributors should not define new annotations that include “beta” or “alpha” labels, and should plan to migrate to annotations or something else that do not have this quality.

**Comment by sftim** [comment]
We've had a word with the contributors who did define the new label. Now they've done it, we need to document what they've done.
