### ISSUE TITLE
Addition of Hover effect on blue buttons of all the pages

### ISSUE THREAD

**Issue by pranav-pandey0804** [kubernetes/website#42893]
Request for Adding Hover Effects to Website Buttons in Kubernetes pages, for example, docs [home page](https://kubernetes.io/docs/home/).
![Screenshot from 2023-09-05 14-42-58](https://github.com/kubernetes/website/assets/126320452/e93c79c1-9abc-42e1-bf1e-80739b31cd85)

**Request:**
Enhance the website's button design by introducing hover effects for a more interactive user experience. Consider subtle design adjustments to ensure a noticeable change upon button hover.

**Why is this needed?**
1. Enhance button design aesthetics
2. Provide user feedback during button hover interactions

**Comment by pranav-pandey0804** [comment]
sig/ UI

**Comment by aj11anuj** [comment]
An issue with similar problem and title exists #42756, but that is for `Read More` button there. In this issue it is for "Docs page". But in reality this issue is present in all pages. None of the `Blue Buttons` at all pages of K8s website has hover effect. So, this feature request should be taken for all pages and not just for "Docs page" or other specific button.

/retitle Addition of Hover effect on blue buttons of all the pages

**Comment by pranav-pandey0804** [comment]
Hi @aj11anuj, thanks for the advice, I've cross-checked and yes, this feature does need to be added on all pages. 
I'm editing the title for the same!

**Comment by satyampsoni** [comment]
Hi @pranav-pandey0804, could you please explain what type of user feedback are you talking about ?

**Comment by pranav-pandey0804** [comment]
Hi @satyampsoni,
when I mentioned "user feedback," I meant giving users a visual cue when they hover over a button on the website. This visual cue lets them know that their action is recognized, making the website more user-friendly and interactive.

**Comment by pranav-pandey0804** [comment]
Hi @satyampsoni ,
Thanks for assigning the issue!
It's a suggestion to add this feature to other pages too.

**Comment by pranav-pandey0804** [comment]
@satyampsoni 
I'm providing the links for the pages that are to be included : 
[page1](https://kubernetes.io/docs/home/), [page2](https://kubernetes.io/training/), [page3](https://kubernetes.io/partners/), [page4](https://kubernetes.io/community/)

**Comment by satyampsoni** [comment]
Hello @pranav-pandey0804 @sftim I need help here. I fixed the first page but I guess there should be some css page for page2, page3 and page4. If you could share a link to those specific files it would be helpful.

**Comment by anurag4499** [comment]
please check on this link 
https://deploy-preview-42808--kubernetes-io-main-staging.netlify.app/

I did this issue.

**Comment by anurag4499** [comment]
I did raise a PR for it.

**Comment by pranav-pandey0804** [comment]
@aj11anuj @anurag4499 PR for this issue has already been raised and approved.

**Comment by aj11anuj** [comment]
Ya, but just in case if Anurag has made more optimal solution for this issue. So, i suggested him raising a PR for it.

**Comment by pranav-pandey0804** [comment]
hi @aj11anuj, it is already assigned to @satyampsoni, so I think it's better to discuss with him first if he wants to collaborate.

**Comment by satyampsoni** [comment]
@pranav-pandey0804  @aj11anuj @anurag4499 I think I have raised a PR earlier and its working fine.

**Comment by anurag4499** [comment]
i did PR  again
 https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6504795ebc3ebd0008419261
