### ISSUE TITLE
Reference of Blog in Nodes is not working

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#42890]
**This is a Bug Report**

The Link under **Swap memory management** refers to the Blog  [Kubernetes 1.28: NodeSwap graduates to Beta1](https://kubernetes.io/blog/2023/07/18/swap-beta1-1.28-2023/) is broken or not available in Blogs

**Problem**
It is referring to the 404 Page not found.

**Proposed Solution**
Should be updated with the correct link or it should  be removed.

**Page to update**
https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory

**Comment by AmarNathChary** [comment]
I will raise a PR for this.
/assign

**Comment by tengqm** [comment]
The date has been changed.

**Comment by AmarNathChary** [comment]
Hey  @MeenuyD I appreciate your initiative. but it would be helpful to check before assigning the issue to yourself. it isn't a good practice to assign an issue if the issue is already assigned.
