### ISSUE TITLE
Add documentation explaining the difference between CRDs and API aggregation layer

### ISSUE THREAD

**Issue by Affan-7** [kubernetes/website#42906]
**This is a Feature Request**

**What would you like to be added**

Add a comparison between the CRDs and API aggregation layer.
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/ should explain this - but doesn't! 

**Why is this needed**
It's needed so users can understand the difference between CRDs and API aggregation layers.

**Comment by thisisharrsh** [comment]
We can take some reference from this [link](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#adding-custom-resources) to understand the difference between `CRDs`and `API aggregation layers`.
