### ISSUE TITLE
Missing  `--port=80` option while creating deployment in "Declare Network Policy" task page

### ISSUE THREAD

**Issue by nclfinalis** [kubernetes/website#42909]
kubectl create deployment nginx --image=nginx

this line should be appended by --port=80 to expose the port.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Missing  `--port=80` option while creating deployment in "Declare Network Policy" task page

**Comment by thisisharrsh** [comment]
Hi @nclfinalis, As we can observe that the first step is to create a `deployment` using a nginx image, and then it is `exposed` to port 80, I believe it is done to provide a sense of better understanding.
