### ISSUE TITLE
Mobile layout for the docs website is broken

### ISSUE THREAD

**Issue by dipesh-rawat** [kubernetes/website#42921]
**This is a Bug Report**

**Problem:**
The mobile screen layout of the [website](https://kubernetes.io/docs/home/) appears to be broken and disrupted. 
Please refer to the below screenshot for a visual representation of the problem.

<img width="291" alt="layout-issue" src="https://github.com/kubernetes/website/assets/13051389/283cdc47-13ec-4f75-a84d-e9270e161194">

**Proposed Solution:**
Fix the website  layout for smaller mobile screens

/area web-development

**Comment by dipesh-rawat** [comment]
It seems that this issue may be a result of a recent change we merged as part of PR #41695. The change was intended to add a splitter so that the left navigation panel can be resized.

**Comment by Gauravpadam** [comment]
The splitter works just fine, Should we just roll back to using the second hamburger menu on mobile?

**Comment by Gauravpadam** [comment]
I can help with that /assign

**Comment by aj11anuj** [comment]
Symptom of #42795 is also there, at right side.

**Comment by Gauravpadam** [comment]
> Symptom of #42795 is also there, at right side.

Will try to address that too, Thanks for the heads up

**Comment by Gauravpadam** [comment]
> Oops.
> 
> /priority important-soon
> 
> We can either:
> 
> * revert [Split the doc view #41695](https://github.com/kubernetes/website/pull/41695)
> * fix the splitter for small viewports
> 
> Let's do whichever feels simplest and quickest.

@sftim I was thinking of reverting to the old layout specifically for the smaller viewports, That way we can keep the splitter as well. I'd like to hear your thoughts on this

**Comment by tengqm** [comment]
@Gauravpadam Thanks. I wasn't able to make the splitter work for smaller devices. Your help is appreciated.

**Comment by dipesh-rawat** [comment]
Also, see #42947
