### ISSUE TITLE
Add link for the video in README.md

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/website#42927]
**This is a Feature Request**

**What would you like to be added**

Add a [YouTube video link](https://youtu.be/1SDYzXtD5JA?si=-Ap7OcaYRV0vviql) to the contributing section of Readme.md 

**Why is this needed**
It covers almost all the doubts of a beginner starting out in #sig-docs and very helpful for especially for those people who prefers to learn through video tutorials.

**Comment by Gauravpadam** [comment]
Closing this as completed via https://github.com/kubernetes/website/pull/43246

/Close
