### ISSUE TITLE
Running Multiple Instances of Your App

### ISSUE THREAD

**Issue by thuo-thuo** [kubernetes/website#42937]
- Kindly note that you asked us to delete the service in the previous section. 
- Please update the docs by asking to restore the service first before running this command.

**Comment by thisisharrsh** [comment]
_page related to the issue: https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/_
/language en
/sig autoscaling

**Comment by thisisharrsh** [comment]
Could you please provide some details on the issue in the [description](https://github.com/kubernetes/website/issues/42937#issue-1886196100) section?
/triage needs-information

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/_

/language en
/sig autoscaling
