### ISSUE TITLE
curl command fails to execute with minikube ip and NODE_PORT in "Performing a Rolling Update" tutorial

### ISSUE THREAD

**Issue by thuo-thuo** [kubernetes/website#42938]
This command: curl http://"$(minikube ip):$NODE_PORT" does not run while using minikube.

**Comment by tamilselvan1102** [comment]
it seems NODE_PORT is not set in your system. 
Please confirm NODE_PORT environment variable has been set or not in your system

**Comment by aj11anuj** [comment]
@thuo-thuo can you showcase the error that you are getting?
