### ISSUE TITLE
Connection refused error when using curl with minikube IP and Node Port in "Performing a Rolling Update" tutorial

### ISSUE THREAD

**Issue by emmankip** [kubernetes/website#42939]
command: curl http://"$(minikube ip):$NODE_PORT" connection refused

**Comment by dipesh-rawat** [comment]
/retitle Connection refused error when using curl with minikube IP and Node Port in "Performing a Rolling Update" tutorial

**Comment by dipesh-rawat** [comment]
This looks like duplicate of #42938 
/triage duplicate

**Comment by Ritikaa96** [comment]
/close
closing in favor of #42938 
as both address same issue.
