### ISSUE TITLE
Look and Feel of Layout of Storage  Section

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/website#42948]
**This is a Bug Report**

In ref of https://github.com/kubernetes/website/issues/42947 issue the same issue is in Storage various pages.

**Problem:**
The  top right section of the page having  links (Edit this page, Create child page, Create an issue, Print entire section)  are displaying in the bottom of the page.

**Proposed Solution:**
 It should be displaying in upper right side of the page. The page design should be universal in all.

**Pages to Update:**
[Volumes](https://kubernetes.io/docs/concepts/storage/volumes/)
[Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
[Projected Volumes](https://kubernetes.io/docs/concepts/storage/projected-volumes/)
[Volume Snapshots](https://kubernetes.io/docs/concepts/storage/volume-snapshots/)

**Comment by aj11anuj** [comment]
You don't need to open separate issues for each individual section where this issue is present, instead mention all the pages in #42947 

/triage duplicate
