### ISSUE TITLE
Issue with "kubelet could not be started on master" caused by expired certificate 

### ISSUE THREAD

**Issue by hhzguo** [kubernetes/website#42944]
Here is the case:
   1. I used kubeadm to start a k8s cluster(1.23.5, with one master and 3 nodes, all as VM)
   2. Everything worked well
   3. I shut down the all the VM(master,3 nodes) for more than one year
   4. One year later, I want to resume the cluster
   5. How ever, on master, kubelet could not be started, the following is the log
   6. I use "kubeadm certs renew all" to renew all  expired certificates
   7. From K8s Doc, the certificate in kubelet.conf could not renew/modified by kubeadm
   8. As a result, the kubelet on master node could not be started and the whole cluster cannot be started(because kubelet needs to run to start the apiserver/controller manager/scheduler, in "/etc/kubenetes/manifests")
   
The document says:
   "From a working control plane node in the cluster that has /etc/kubernetes/pki/ca.key execute kubeadm kubeconfig user --org system:nodes --client-name system:node:$NODE > kubelet.conf. $NODE must be set to the name of the existing failed node in the cluster. Modify the resulted kubelet.conf manually to adjust the cluster name and server endpoint, or pass kubeconfig user --config (it accepts InitConfiguration). If your cluster does not have the ca.key you must sign the embedded certificates in the kubelet.conf externally."

BUT, I don't have a working control plane here. 

The following is the log:
    
Sep  7 15:46:04 ubuntu systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2179.
Sep  7 15:46:04 ubuntu systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Sep  7 15:46:04 ubuntu systemd[1]: Started kubelet: The Kubernetes Node Agent.
Sep  7 15:46:04 ubuntu kubelet[37729]: Flag --network-plugin has been deprecated, will be removed along with dockershim.
Sep  7 15:46:04 ubuntu kubelet[37729]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep  7 15:46:04 ubuntu kubelet[37729]: Flag --network-plugin has been deprecated, will be removed along with dockershim.
Sep  7 15:46:04 ubuntu kubelet[37729]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep  7 15:46:04 ubuntu systemd[1]: Started Kubernetes systemd probe.
Sep  7 15:46:04 ubuntu kubelet[37729]: I0907 15:46:04.166600   37729 server.go:446] "Kubelet version" kubeletVersion="v1.23.5"
Sep  7 15:46:04 ubuntu kubelet[37729]: I0907 15:46:04.166836   37729 server.go:874] "Client rotation is on, will bootstrap in background"
Sep  7 15:46:04 ubuntu kubelet[37729]: E0907 15:46:04.167605   37729 bootstrap.go:265] part of the existing bootstrap client certificate in /etc/kubernetes/kubelet.conf is expired: 2023-03-18 17:01:56 +0000 UTC
Sep  7 15:46:04 ubuntu kubelet[37729]: E0907 15:46:04.167656   37729 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory"
Sep  7 15:46:04 ubuntu systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Sep  7 15:46:04 ubuntu systemd[1]: kubelet.service: Failed with result 'exit-code'.
Sep  7 15:46:04 ubuntu systemd[1]: run-r81a8f7a938c8424c9775f917d1b7e141.scope: Succeeded.

**Comment by tamilselvan1102** [comment]
There are lot of updation happened after v1.23.5
Please update to latest kubeadm and check the issue.

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by neolit123** [comment]
> "From a working control plane node in the cluster that has /etc/kubernetes/pki/ca.key execute kubeadm kubeconfig user --org system:nodes --client-name system:node:$NODE > kubelet.conf. $NODE must be set to the name of the existing failed node in the cluster. Modify the resulted kubelet.conf manually to adjust the cluster name and server endpoint, or pass kubeconfig user --config (it accepts InitConfiguration). If your cluster does not have the ca.key you must sign the embedded certificates in the kubelet.conf externally."

> BUT, I don't have a working control plane here.

you can still be able to call the kubeadm commands on it.

either way this is a support request.
a better place to ask would be on the support channels and channels like #Kubeadm on k8s slack. please see:
https://git.k8s.io/kubernetes/SUPPORT.md


/close
/kind support
/kind support
/close
