### ISSUE TITLE
Include Pod name in `kubectl describe pods` command output in "Performing a Rolling Update" tutorial

### ISSUE THREAD

**Issue by thuo-thuo** [kubernetes/website#42940]
On the output of kubectl describe pods, the pod name should also be a part of the command like so:

kubectl describe po [POD_NAME]

**Comment by dipesh-rawat** [comment]
/retitle Include Pod name in `kubectl describe pods` command output in "Performing a Rolling Update" tutorial

**Comment by tamilselvan1102** [comment]
> kubectl describe pods

 command gives complete information about each of the Kubernetes infrastructure pods.
 So i don't think so the statement is wrong.

**Comment by aj11anuj** [comment]
Fix is optional and doesn't necessarily required.
/close not-planned
