### ISSUE TITLE
404 broken link in docs

### ISSUE THREAD

**Issue by bobsky** [kubernetes/website#4295]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
link for [api-reference] in opening line at 
https://kubernetes.io/docs/concepts/services-networking/network-policies/#the-networkpolicy-resource leads to a 404 error https://kubernetes.io/docs/api-reference/networking/v1/definitions/#_v1_networkpolicy

**Proposed Solution:**
update to correct link

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/network-policies/#the-networkpolicy-resource

**Comment by ahmetb** [comment]
@bobsky seems to be working for me. can you try again?

**Comment by tengqm** [comment]
Confirmed, it works for me. Closing this.
