### ISSUE TITLE
Missing layout items in all the docs pages of Kubernetes-api section

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#42954]
**This is a Bug Report**

**Problem:**
Some layout items at right side are missing in Workload Resource page. That missing part should look like [this page](https://kubernetes.io/docs/reference/kubernetes-api/) 

**Page to Update:**
https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/

![Screenshot (6620)](https://github.com/kubernetes/website/assets/116108975/a5e5f81c-82cf-46a3-8a20-7b47d64fd076)
![Screenshot (6680)](https://github.com/kubernetes/website/assets/116108975/10ce08c4-98b2-4ee3-8a4e-4b949f182e97)

**Comment by sftim** [comment]
I don't see anything missing. Please clarify what should be there and isn't.

/triage needs-information

**Comment by aj11anuj** [comment]
My bad in clarifying it, I added another screenshot for more information

Basically i wanted to say like most of the docs pages contain these 4 things at right side ("Edit this page", "Create child page", "Create an issue", "Print entire section"). But most of the pages under `/reference/kubernetes-api/` section contain only these 2 things "Create an issue" and "Print entire section". So, i was talking about adding "Edit this page" and "Create child page" there.

**Comment by sftim** [comment]
It's not a bug. We don't encourage edits to automatically generated pages; in fact, we **discourage** them.

**Comment by aj11anuj** [comment]
😲Oh, Ok
