### ISSUE TITLE
Docs says that `StorageClass` objects cannot be updated after creation.

### ISSUE THREAD

**Issue by lindhe** [kubernetes/website#42958]
It says here that `StorageClass` objects cannot be updated after creation:

https://github.com/kubernetes/website/blob/badc695f6960e5df1ed62e0fee40191b77e9191e/content/en/docs/concepts/storage/storage-classes.md?plain=1#L35-L38

It's not true. I tried editing the `allowVolumeExpansion` field of a storage class I had deployed, and that worked fine.

**Comment by sftim** [comment]
/sig storage
/kind bug
/language en

Seems reasonable to triage as accepted
