### ISSUE TITLE
Layout and style of "Kubectl Commands" reference is (old and) not matching with K8s site

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#42957]
**This is a Feature/Enhancement Request**

**What would you like to be enhanced?**
Change of layout/style of "[KubeCtl Commands](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands)" Page. This page is making me feel like i got redirected to another site, its layout/style is not matching with K8s site. So, i think it needs to be updated.

**Why is this needed**
For consistent layout/style/look across whole K8s site

![Screenshot (664)](https://github.com/kubernetes/website/assets/116108975/6bbc1da0-0fc7-46a9-9de3-983ecaab1309)

**Comment by sftim** [comment]
This looks like a subset of what the existing issue https://github.com/kubernetes/website/issues/25943 calls for.

/retitle Layout and style of "Kubectl Commands" reference is (old and) not matching with K8s site

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/

**Comment by tengqm** [comment]
@Tomato25 There is an existing PR (https://github.com/kubernetes/website/pull/42664) proposing pure markdown (combined with embedded HTML tables) for kubectl references.
The markdown files are generated from the kubernetes-sigs/reference-docs repository.
I don't have time to investigate if it is possible to organize individual markdown files based on the command-subcommand hierarchy.
If you have cycles to help out, it would be great.

**Comment by sftim** [comment]
This feels like a duplicate issue. If we don't get evidence otherwise, let's mark this as a duplicate and close it.

**Comment by kumarankit999** [comment]
I don't think it as a duplicate issue! 
If you found let us know it!

**Comment by sftim** [comment]
/triage duplicate
(no evidence to the contrary)

See https://github.com/kubernetes/website/issues/25943

/close not-planned
