### ISSUE TITLE
"Home" button at footer is linked to docs home page instead of K8s site home page

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#42959]
**This is a Bug Report**

**Problem:**
"Home" button at footer is linked to docs home page instead of K8s site home page 

**Proposed Solution:**
Either that button should be linked to K8s site home page or that button should be renamed to "Documentation" instead of "Home"
![Screenshot (666)](https://github.com/kubernetes/website/assets/116108975/7684b590-a426-42cb-880d-68f8a414e2fd)

**Comment by sftim** [comment]
Thanks
I'd change it to read “Documentation”.
/priority backlog
/help
/triage accepted
/language en
