### ISSUE TITLE
Label `nfd.node.kubernetes.io/node-name` not documented / registered

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#42960]
**This is a Bug Report**

**What would you like to be added**
Add details for the label `nfd.node.kubernetes.io/node-name` into https://kubernetes.io/docs/reference/labels-annotations-taints/ 
For details of that label, see https://kubernetes-sigs.github.io/node-feature-discovery/v0.14/usage/custom-resources.html#nodefeature

**Why is this needed**
https://github.com/kubernetes-sigs/node-feature-discovery/ uses annotations and labels matching `nfd.node.kubernetes.io/*`, and we should register all official labels and annotations.

**Comments**
/kind bug
/sig node
/language en
Also see #31612

**Comment by tamilselvan1102** [comment]
i would like to work on it.
/assign

**Comment by tamilselvan1102** [comment]
@sftim 
Raised the PR, please validate the details.

**Comment by tamilselvan1102** [comment]
Fix is merged. Thank you.
/close
