### ISSUE TITLE
Rename 'ReadMes' to 'READMEs' in repository README

### ISSUE THREAD

**Issue by Rituraj-13** [kubernetes/website#42979]
**This is a Bug Report**

**Problem:**
![image](https://github.com/kubernetes/website/assets/90104572/ad518965-91d6-44fe-8e79-d60ebe4b2412)
![image](https://github.com/kubernetes/website/assets/90104572/de7a32a6-41b7-4499-bc2d-edd018a72f1a)

There is a typing and grammatical error in the `README.md` file. 

1. Instead of `Localization ReadMes` , it should be `Localized READMEs`.
2. Instead of `Localization README.md's` , it should be `Localized README.md's`.

**Proposed Solution:**
I propose fixing the typing errors.
**Page to Update:**
https://github.com/kubernetes/website/blob/main/README.md

**Comment by aj11anuj** [comment]
Instead of saying there is a typo in README.md, you should specify where it is?

/triage needs-information

**Comment by Vikash-8090-Yadav** [comment]
@Rituraj-13 What's the typo error, can u please highlight the sentence and it's correction. 

Thanks!

**Comment by nate-double-u** [comment]
Based on the PR opened, I'm not sure that there is a grammatical error or typo. "Localization" is correct for the heading that was changed.

**Comment by sftim** [comment]
/triage accepted
Done
/close
