### ISSUE TITLE
"Hello Minikube" tutorial objective discrepancy: 'View Application Logs' mentioned but not covered

### ISSUE THREAD

**Issue by Ruslanmsv** [kubernetes/website#42984]
One of the objectives stated at the beginning of the tutorial is to "View application logs", but we don't do this in the tutorial

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/tutorials/hello-minikube/
/language en

**Comment by dipesh-rawat** [comment]
/retitle "Hello Minikube" tutorial objective discrepancy: 'View Application Logs' mentioned but not covered

**Comment by MeenuyD** [comment]
we should have removed this or described it.

**Comment by satyampsoni** [comment]
I think adding it would be a great idea.

**Comment by dipesh-rawat** [comment]
We should update the tutorial to align with the stated objectives.

/triage accepted

**Comment by dipesh-rawat** [comment]
@MeenuyD You are welcome to work on this issue; we have a [no cookie licking policy](https://www.redhat.com/en/blog/dont-lick-cookie) in SIG Docs.

If someone has said they plan to work on an issue, and you're also considering that work, it's polite - but not mandatory - to try to co-ordinate.

**Comment by MeenuyD** [comment]
Ok @dipesh-rawat

**Comment by afbjorklund** [comment]
Probably a left-over from the original tutorial, which deployed a "Hello World" app using Node.js

commit 86b76fffba2bb41570acb783a0e6141373de0220

**Comment by satyampsoni** [comment]
@MeenuyD I see you are very enthusiastic about the PRs but you should respect when others assign themselves the issue and work on another issue, I have addressed this three times from your side that you are sending PR for issues assigned to someone else.

**Comment by MeenuyD** [comment]
Hello @satyampsoni sorry for that currently I am learning new technology but I have understood and now I follow those as well

**Comment by dipesh-rawat** [comment]
Fix merged as part of #42998

/close
