### ISSUE TITLE
[ko] Fix typo in blog/2020/12/02/dont-panic-kubernetes-and-docker/

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/website#42990]
**This is a Bug Report**

**Problem:**
Typo '작성나요?' in blog/2020/12/02/dont-panic-kubernetes-and-docker/

**Proposed Solution:**
Correct typo from '작성나요?' to '작성하나요?'.

**Page to Update:**
https://kubernetes.io/ko/blog/2020/12/02/dont-panic-kubernetes-and-docker/

/language ko
/assign

**Comment by anjum-edge** [comment]
checkout for the auto capitalization bug.
it can be giving problems in the website
