### ISSUE TITLE
[ko] Translate /docs/tasks/debug/debug-cluster/kubectl-node-debug into Korean

### ISSUE THREAD

**Issue by Kid-Chang** [kubernetes/website#42992]
**This is a Feature Request**

**What would you like to be added**
Translate [/docs/tasks/debug/debug-cluster/kubectl-node-debug](https://kubernetes.io/docs/tasks/debug/debug-cluster/kubectl-node-debug/) into Korean

**Why is this needed**
Not translated yet docs/tasks/debug/debug-cluster/kubectl-node-debug into Korean

**Comment by jihoon-seo** [comment]
@Kid-Chang 감사합니다!
/triage accepted

**Comment by vaibhav2107** [comment]
I think this issue has been resolved by the PR #44483 and hence can be closed
