### ISSUE TITLE
Unify the well_known_taints.go and w/ well known conditions

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/website#43018]
**This is a Bug Report**

**Problem**

We have conditions and taints that are related but not documented together, comprehensively.  

Looking at https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ i think  we have conditions and taints which have "co-evolved" over time.  We should make sure we document all of these cases. i.e. 

There are conditions and taints like ( "node.kubernetes.io/network-unavailable:false" / v1.TaintNodeNetworkUnavailable ) which match each other intentionally (this maybe is the only one example of such a thing... but maybe there are others so i kept this issue generic).

**Proposed Solution:**

We should probably update well_known_taints.go to have corresponding conditions, and reflect that in the docs.  Im filing this as a doc issue but I think it would best be implemented by ALSO updateing the upstream codebase to directly mention these in the `well_known_taints.go` file.

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by jayunit100** [comment]
xref , discovered this when investigating https://github.com/kubernetes/kubernetes/issues/120486

**Comment by tengqm** [comment]
Anything we can/should do from docs side?

**Comment by jayunit100** [comment]
I think if you can include some of the history as discussed in the umbrella issue above that will be useful to people trying to understand what the nodenetwork readiness issue is.
