### ISSUE TITLE
Provided "cgroup driver" link is not appropriate

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#43016]
**This is a Bug Report**

**Problem:**
The link provided for "cgroup driver" is not appropriate

**Proposed Solution:**
It is navigating to https://kubernetes.io/docs/setup/production-environment/container-runtimes/ but should navigate to https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configuring-a-cgroup-driver

**Comment by neolit123** [comment]
> **Page to Update:**
> https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configuring-a-cgroup-driver

/sig cluster-lifecycle

**Comment by MeenuyD** [comment]
Hello, @tamilselvan1102 are you working on the issue?

**Comment by dipesh-rawat** [comment]
Resolved via #43034

/close
