### ISSUE TITLE
apiserver_storage_objects metric description is not complete

### ISSUE THREAD

**Issue by machine424** [kubernetes/website#43012]
**This is a Bug Report**

**Problem:**
the metric `apiserver_storage_objects` can return `-1` sometimes when the fetching fails, see: https://github.com/kubernetes/kubernetes/blob/35199e42a41f83520e640fbfa9f409516faa7501/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1582C7-L1588

We should explicitly state this.

**Proposed Solution:**
https://github.com/kubernetes/kubernetes/pull/120597

**Page to Update:**
https://kubernetes.io/docs/reference/instrumentation/metrics/

**Comment by machine424** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/120597
Keeping it open until it's visible in https://kubernetes.io/docs/reference/instrumentation/metrics/

**Comment by sftim** [comment]
We'll update the generated docs for the next minor release of Kubernetes, and maybe sooner.

**Comment by satyampsoni** [comment]
Is there anything left to work on this issue?

**Comment by tengqm** [comment]
Nothing to work from docs side yet. The reference is auto-generated.
/close
