### ISSUE TITLE
Text-image overlapping issue at App Direct Case-Study page for small screens

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43019]
**This is a Bug Report**

**Problem:**
Look at this below page (This is how pages of Case-Studies of other Companies/Organisation look)
![Screenshot_2023-09-12-21-10-07-517_org mozilla firefox](https://github.com/kubernetes/website/assets/116108975/4fcdd01f-493f-4a5c-acd1-74592ab330e1)

Now look at App Direct Case Study page
![Screenshot_2023-09-12-21-11-42-732_org mozilla firefox](https://github.com/kubernetes/website/assets/116108975/3c18c978-3cfd-4eed-88f3-3c69c04e0a12)
![Screenshot_2023-09-12-21-11-28-584_org mozilla firefox](https://github.com/kubernetes/website/assets/116108975/37d670d7-f029-4696-b7d5-78190cc45d57)
![Screenshot_2023-09-12-21-11-20-362_org mozilla firefox](https://github.com/kubernetes/website/assets/116108975/beac53bc-e715-481e-bc12-42be3da68a99)

That background image and text overlapping issue is problem at this page, that i wanted to point out with this issue.

**Comment by Gauravpadam** [comment]
It looks fine on larger viewports, I think the problem is that the image isn't adapting to the container in smaller viewports. Let's wait for triage, I'll fix this

**Comment by aj11anuj** [comment]
Ya, you are right its working fine for larger screens but for smaller devices or when its minimized, these images aren't adapting properly like this (Note: This issue is only with this page)

![Screenshot (672)](https://github.com/kubernetes/website/assets/116108975/d43ee311-ac6e-4072-97d4-9cf82b339ee6)
