### ISSUE TITLE
External-IP not assigned for Service as expected following tutorial "Using a Service to Expose Your App"

### ISSUE THREAD

**Issue by ikram-khan-fahim** [kubernetes/website#43022]
According to the [doc](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/), exposing the `kubernetes-bootcamp` deployment through a `NodePort` service is expected to produce a service with:

> a unique cluster-IP, an internal port and an external-IP (the IP of the Node)

However, no external IP was actually assigned in my case as apparent from the output of `kubectl get services`. Here's my output:

```powershell
$ kubectl get services
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes            ClusterIP   10.96.0.1       <none>        443/TCP          34m
kubernetes-bootcamp   NodePort    10.105.161.98   <none>        8080:31136/TCP   7m40s
```

FWIW, I'm running Windows 11.

TIA.

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/_
/language en
/sig node

**Comment by thisisharrsh** [comment]
I believe the `NodePort` service does not get an external IP address automatically.

**Comment by dipesh-rawat** [comment]
/retitle External-IP not assigned for Service as expected following tutorial "Using a Service to Expose Your App"

**Comment by dipesh-rawat** [comment]
Similar (possibly duplicated) issues have already been reported https://github.com/kubernetes/website/issues/41438 https://github.com/kubernetes/website/issues/40645 https://github.com/kubernetes/website/issues/42713

**Comment by tengqm** [comment]
> a unique cluster-IP, an internal port and an external-IP (the IP of the Node)

This clearly states that the "external-IP" **in this context** is the IP of the Node.
When you do `kubectl get services`, the `EXTERNAL-IP` column is reserved for LoadBalancer
Services and the values in that column will be the IP exposed by the LoadBalancer.

This is a misunderstanding rather than a bug.

**Comment by ikram-khan-fahim** [comment]
@tengqm, here's my understanding of the tutorial. It asks to create a `NodePort` service, then run the `get services` subcommand whereby we should be able to **see** an external IP.

> `kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080`
>
> Let's run again the `get services` subcommand:
>
> `kubectl get services`
>
> We have now a running Service called kubernetes-bootcamp. **Here we see** that the Service received a unique cluster-IP, an internal port and an external-IP (the IP of the Node).

The result of the last command, as given in the description, is that the External-IP column is empty. Is there something that I'm missing?

**Comment by tengqm** [comment]
A NodePort service is primarily identified by the port number which is unique across the cluster. Say you get a port number 32323, you can then access the service at `<NODE_IP>:32323`. You can see that the so called "external IP" is the `<NODE_IP>`. You can access the Service from wherever provided you have access to the node IPs.
It is not needed to list all node IPs in that column. Once you know how NodePort service works, you won't care about the "external IP" column. Is this clear?

**Comment by tamilselvan1102** [comment]
@ikram-khan-fahim 
This blog explained well about the differences.
https://kodekloud.com/blog/clusterip-nodeport-loadbalancer/
it would help for your understanding

**Comment by tengqm** [comment]
/close
won't fix.
