### ISSUE TITLE
Mismatch of footer colour at all Case-Study pages

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43020]
**This is a Feature Request**

See this below [Home page](https://kubernetes.io/), this is original footer colour of K8s website
![Screenshot_2023-09-12-20-59-30-608_org mozilla firefox](https://github.com/kubernetes/website/assets/116108975/98aeae35-8499-4c91-9fe7-77ce465d10f3)

But all the footer at pages of individual Case-Studies like- Babylon, [App Direct](https://kubernetes.io/case-studies/appdirect/) , Booking.com etc., have this below colour 
![Screenshot_2023-09-12-20-59-58-225_org mozilla firefox](https://github.com/kubernetes/website/assets/116108975/317fd4df-2a77-42e8-ba4b-300cd4af0fef)

There is a significant mismatch of footer colour at these pages. This is the problem that i wanted to address with this issue.

**Comment by Gauravpadam** [comment]
@aj11anuj Is it just so as to give a different effect to the case studies? I know many websites which do such a thing. I think this was on purpose at the first place, You can see the same in other case studies as well

**Comment by aj11anuj** [comment]
Who knows if its done on purpose or a mistake that was replicated to all case-study pages.

**Comment by Gauravpadam** [comment]
True, Triage can help

**Comment by Ritikaa96** [comment]
Before working on PR, let's wait for the web development experts to accept the triage. It can add more information and detail in change.

**Comment by 7h3-3mp7y-m4n** [comment]
lets see when its going to accepted by the triage.
