### ISSUE TITLE
Title here for any issue you want to raise

### ISSUE THREAD

**Issue by albertsuki265** [kubernetes/website#43036]
The description of issue
What i am actually looking as a problem
what should be the proposed solution
which page we need to update.

These are needed to raise the issue.

**Comment by niranjandarshann** [comment]
Hi @albertsuki265 
Please provide the description of the issue you are facing.

**Comment by niranjandarshann** [comment]
These are the parameters to  address  issue. 
/triage needs-information

**Comment by albertsuki265** [comment]
@niranjandarshann Thankyou ! but i am just looking how the community work and how to raise issue. Which type of issue one should raise.

**Comment by niranjandarshann** [comment]
> @niranjandarshann Thankyou ! but i am just looking how the community work and how to raise issue. Which type of issue one should raise.

@albertsuki265  please go through the community contribution process first to understand the working of the community and to raise the issue. You can raise trivial issue, the bug report, feature to add or remove, any improvement in doocumentation of kubernetes etc. The relevant one with the repository.

**Comment by aj11anuj** [comment]
You can raise issues related to bugs encountered with K8s website, any feature or enhancement request, website enhancement, documentation improvement etc. For other type of code base related contributions you can check out other repositories. This repo deals with K8s website and its documentation.

You can now close this issue

**Comment by aj11anuj** [comment]
You can join K8s slack for any kind of discussion as per relevant channels and also attend meetings. Community is very welcoming and will help you out wherever you need help.

You can get links and proper [Contributor guide](https://kubernetes.dev/) here.

/close

**Comment by albertsuki265** [comment]
> You can find the community contribution process here https://kubernetes.io/docs/contribute/

@niranjandarshann  Thank you for your help. Will go through it. Your help means alot to me . I  got what actually i was looking for. Helping member is  the real meaning of community work.

**Comment by albertsuki265** [comment]
> You can join K8s slack for any kind of discussion as per relevant channels and also attend meetings. Community is very welcoming and will help you out wherever you need help.
> 
> You can get links and proper [Contributor guide](https://kubernetes.dev/) here.
> 
> /close

Sure will do .

**Comment by albertsuki265** [comment]
closing issue 
/close
