### ISSUE TITLE
Incorrect way of reference link in Set up a High Availability etcd Cluster with kubeadm page

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#43041]
**This is a Bug Report**
Under [Before you begin](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#before-you-begin) section of [setup HA etcd cluster](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) page, one of the reference link is misplaced.

**Problem:**
> Each host must [have a container runtime, kubelet, and kubeadm installed](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/).

Here "have a" should not be included in the reference link.
**Proposed Solution:**
Remove "have a" from the existing reference link.
**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

**Comment by aj11anuj** [comment]
Untill an issue doesn't have `triage/accepted` label, it should not be marked good first issue according to K8s protocols while contributing.

/remove-kind bug
/kind feature
/remove-good-first-issue
/remove-help
