### ISSUE TITLE
Wrong wording in diagram at https://k8s.io/docs/concepts/extend-kubernetes/

### ISSUE THREAD

**Issue by paulmossman** [kubernetes/website#43050]
In the "Extension point choice flowchart", answering yes to the first questions leads to: Go the "Adding APIs" Section"

There's a grammar error and a punctuation error, but major problem is that there is no such section on that page.

It should read: Go to "API extensions"

**Comment by rishavkankane** [comment]
> This issue is talking about the first section of this diagram at given page
> 
> ![Screenshot_2023-09-14-20-17-29-020_com android chrome](https://user-images.githubusercontent.com/116108975/268015088-4ede3215-758c-484b-aa95-9c2741b172f3.png)
> 
> /kind feature

@aj11anuj  Thank you for your reply but basically this approach is not the good practice  The issue has been defined by the  @paulmossman  and the link to redirect to that page is not been provided so it has been provided by @niranjandarshann  and you are giving the screenshot of that issue means it does not looks good. Requesting you for the  good approach.
Its asking like the issue is denoted by the description and then by link and then by image.

**Comment by aj11anuj** [comment]
When i saw this issue, it was having relevant explanation, and link of the page by niranjan but i felt an image is missing to understand the issue better like - where this "Go the adding API server is written" in whole page and where we need to make change. So, i just added one image. Generally, i don't put pic of an issue like this. When i approach an issue i first try to understand it, then verify it then label it and then try to discuss about its causes and possible solutions in proper way that won't look odd to anyone. But here forgive me if this looked odd to you, thank you for your feedback. Now i will take care even more.

**Comment by sftim** [comment]
/priority backlog
/triage accepted

For more tips about diagram improvements, see https://www.k8s.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/

**Comment by sftim** [comment]
/retitle Wrong wording in diagram at https://k8s.io/docs/concepts/extend-kubernetes/

**Comment by ArvindParekh** [comment]
Hi! I think I'll be able to solve this one. Also, I think this diagram's made using draw.io instead of mermaid.js. I should remake it using the same tool, right?
/assign

**Comment by sftim** [comment]
Using draw.io is fine

It'd be nice to also use Kubernetes colors - maybe a second PR?

**Comment by ArvindParekh** [comment]
That sounds good! Sure, I can create a second PR after this one.
And just to clarify, should I open a new issue for it, or can I proceed directly with the pull request?
I'm a new contributor to the Kubernetes project :)

**Comment by aj11anuj** [comment]
You can proceed directly with a PR, no need to raise a new issue for it.
