### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/scale-interactive/

### ISSUE THREAD

**Issue by romeech** [kubernetes/website#4305]
During all the steps from 1 till the current one I came across one and the same error: a page with practical part was loading during 1.1 minute and after that a big dark grey rectangle was rendered on the page and nothing more happened (see attached screenshot). 

In browser console I found the next errors:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Bold.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Regular.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Bold.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Regular.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Bold.svg, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Regular.svg, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Light.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Light.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Light.svg, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Thin.woff, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Thin.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (RobotoSlab-Thin.svg, line 0)
[Error] Failed to load resource: The request timed out. (embed.js, line 0)

Browser: Safari Version 10.1.1 (10603.2.5)
My geolocation is Moscow, Russia.

All previous steps I fulfilled using description on the page https://github.com/kubernetes/minikube.
But now I'm totally blocked and not able to move further.
<img width="1339" alt="screen" src="https://user-images.githubusercontent.com/17002751/27933745-559af7bc-62ab-11e7-903f-6ca55e95286a.png">

**Comment by romeech** [comment]
Thanks! Please, let me know, if you find a solution.

**Comment by BenHall** [comment]
Could you please let me know if you can access the main Katacoda site?

You can take the scenarios directly at https://katacoda.com/kubernetes-bootcamp.

**Comment by romeech** [comment]
Hello!

I have made several attempts to follow by the link https://katacoda.com/kubernetes-bootcamp <https://katacoda.com/kubernetes-bootcamp> but always failed.
After connection timeout period I always got this error: 'Safari can’t open the page “https://katacoda.com/kubernetes-bootcamp” because the server where this page is located isn’t responding.’.
Looks like that resource also blocks russian IPs. :-(

-----------------------------------
С уважением,
Роман Шинянский
weatherwaxra@gmail.com
