### ISSUE TITLE
Set up Ingress on Minikube with the NGINX Ingress Controller

### ISSUE THREAD

**Issue by Adrianjewell91** [kubernetes/website#43060]
Why is this failing? 

Failed: curl --resolve "hello-world.info:80:$( minikube ip )" -i http://hello-world.info
curl: (28) Failed to connect to hello-world.info port 80 after 75002 ms: Couldn't connect to server 

Worked (after running minikube tunnel): 
url -v --resolve "hello-world.info:80:127.0.0.1" -i http://hello-world.info:80
* Added hello-world.info:80:127.0.0.1 to DNS cache
* Hostname hello-world.info was found in DNS cache
*   Trying 127.0.0.1:80...
* Connected to hello-world.info (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: hello-world.info
> User-Agent: curl/8.1.2
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Fri, 15 Sep 2023 10:29:34 GMT
Date: Fri, 15 Sep 2023 10:29:34 GMT
< Content-Type: text/plain; charset=utf-8
Content-Type: text/plain; charset=utf-8
< Content-Length: 60
Content-Length: 60
< Connection: keep-alive
Connection: keep-alive

MacOS Ventura
on a company laptop so maybe something I don't know is blocking the connection?

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/_

/language en

**Comment by aj11anuj** [comment]
K8s Slack is better place for resolving these type of issues @Adrianjewell91

**Comment by sftim** [comment]
If you're looking for help, you can also ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by tengqm** [comment]
/close
Not a docs issue to fix.
