### ISSUE TITLE
(solved) Unable to forcefully delete running Pods with `kubectl delete` command

### ISSUE THREAD

**Issue by kdm6389** [kubernetes/website#43071]
kubectl get pods --all-namespaces 
list lots of pods runiing compled crashed off etc..

but unable to delete using 
kubectl delete pods syncthing-56465b4f5c --grace-period=0 --force

**Comment by dipesh-rawat** [comment]
/retitle Unable to forcefully delete running Pods with `kubectl delete` command

**Comment by dipesh-rawat** [comment]
I think this is:
/kind support

**Comment by aj11anuj** [comment]
[K8s Slack](https://slack.k8s.io/) is a better place for resolving these type of issues @kdm6389

**Comment by tamilselvan1102** [comment]
Try is 
kubectl delete **pod** syncthing-56465b4f5c --grace-period=0 --force

**Comment by kdm6389** [comment]
Solved, the kubectl installed was simlink to k3s. I am sorry. Lot of valuable time lots.
