### ISSUE TITLE
Some features addition request to the section "Why you need Kubernetes, What can it do" of docs

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43075]
**This is a Feature Request**

**What would you like to be added?**
(Don't confuse this issue with this PR #43061, here i'm talking about other points addition)

At K8s [Home page](https://kubernetes.io) there is a section where 10 features of K8s are highlighted as below:-

![Screenshot (686)](https://github.com/kubernetes/website/assets/116108975/c941d1e7-acd5-44bd-b031-7e344dfb7a86)

but at docs page [Why you need Kubernetes, What can it do](https://kubernetes.io/docs/concepts/overview/#why-you-need-kubernetes-and-what-can-it-do), there only 6 features of K8s are written. If at home page those 10 features highlighted are that much relevant that they are written at Main page (Home) then, why not to add those points to this section of [docs](https://kubernetes.io/docs/concepts/overview/#why-you-need-kubernetes-and-what-can-it-do)

![Screenshot (685)](https://github.com/kubernetes/website/assets/116108975/f1d11cd2-cf10-45d1-b18b-486e7e631945)

**Comment by sftim** [comment]
I don't mind if anyone works on this, but there are issues we'd prioritize higher.
/priority backlog
