### ISSUE TITLE
Signpost from "Annotations" to "Well-Known Labels, Annotations and Taints" reference page

### ISSUE THREAD

**Issue by ecki** [kubernetes/website#43086]
This page should probably link to resources for defining standard annotations. Especially the thinks mentioned as examples. That would unify it a bit (for example contact address). Maybe link to https://kubernetes.io/docs/reference/labels-annotations-taints/?

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
/langauge en

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Signpost from "Annotations" to "Well-Known Labels, Annotations and Taints" reference page

**Comment by dipesh-rawat** [comment]
We can enhance the  ['What's next'](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#what-s-next) section by including a link to the reference page, as well as any other relevant pages. This will be beneficial in guiding readers to explore those additional pages.

**Comment by steve-hardman** [comment]
please i will want to work in this!

/assign

**Comment by steve-hardman** [comment]
i have riased pull request #43087 please review.
