### ISSUE TITLE
L

### ISSUE THREAD

**Issue by luciagolovin** [kubernetes/website#43085]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**

**Comments**

**Comment by aj11anuj** [comment]
Hello @luciagolovin, What issue you want to file with this issue, please fill all the required details. If you opened this issue by mistake, then you can close it. If you are beginner and learning to contribute to Open-Source then you can read this [guide](https://kubernetes.dev).

/traige needs-information

**Comment by dipesh-rawat** [comment]
/close not-planned

@luciagolovin You are welcome to reopen this issue and add details.
