### ISSUE TITLE
Addition of Bullet points in sub-docs pages at side-menu

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43092]
**This is a Feature/Enhancement Request**

**What would you like to be added/enhanced?**
![Screenshot (6930)](https://github.com/kubernetes/website/assets/116108975/ea13e7f0-e2f2-447f-b2d6-a46332b92701)
![Screenshot (690)](https://github.com/kubernetes/website/assets/116108975/be969e60-8b37-443f-86ff-52981a850054)

To give it look something like this in sub-docs pages

![Screenshot (689)](https://github.com/kubernetes/website/assets/116108975/077d1423-aa28-4db9-91aa-4506bfc95867)

I know they are drop-down bullet points, and i didn't mean to add those type of bullet-points. I mean to add some other type of bullet-point something like normal ones.

**Pages where it have to be done**
There are a lot of pages where it have to be done, and providing link to individual page won't help as there are a lot of them. But overall wherever in docs tab, you see drop-down bullet points at sidebar menu that contain a lot of sub-pages where bullets aren't used yet, there it have to be done.
(Providing link to some of those pages)
[Pods page](https://kubernetes.io/docs/concepts/workloads/pods/), [Storage page](https://kubernetes.io/docs/concepts/storage/), [Authorization resources page](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/), [API Overview page](https://kubernetes.io/docs/reference/using-api/) etc.

**Why is this needed**
1. For increasing ease of differentiability across different sub-docs pages at side-bar menu.
2.  To give it overall better look.

**Comment by Ayush9026** [comment]
@Ayush9026 /assign

**Comment by tengqm** [comment]
/close
This is not an improvement. More indentation on the navigation bar would be bad.
