### ISSUE TITLE
Utilizing the NUMA-aware Memory Manager

### ISSUE THREAD

**Issue by imkuldeepsingh** [kubernetes/website#43093]
When we apply "--memory-manager-policy=Static" in kubernetes 1.26 then it is showing invalid flag.
How can we achieve this feature in kubernetes 1.26

Ref Url : https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/
Error Screenshot:

<img width="673" alt="k8s-memory-manager-policy" src="https://github.com/kubernetes/website/assets/99728641/432101e6-7cfc-444a-8821-4dad825ab2c7">

**Purpose** : We want to distribute assigned Pod's hugepages on different NUMA nodes using memory manager

Any other option is available to achieve this purpose in kubernetes 1.26 or later version?

**Comment by aj11anuj** [comment]
Hello @imkuldeepsingh, K8s slack channels are better place for resolving these type of issues and support related questions. If you hasn't joined K8s slack yet, then you can join with this [link](https://communityinviter.com/apps/kubernetes/community) and ask your question there at appropriate channels.

/kind support

**Comment by tamilselvan1102** [comment]
may be it help your needs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1769-memory-manager#memory-maps-at-start-up-with-examples

**Comment by imkuldeepsingh** [comment]
I am using kubernetes 1.26 single node cluster
Applied memoryManager policy to static 
Configure "systemReserved", "kubeReserved" & "reservedMemory" fields in "/var/lib/kubelet/config.yaml" file
<img width="378" alt="image" src="https://github.com/kubernetes/website/assets/99728641/43222fe2-3a3a-4f5a-9aa5-bf0dbe510885">

But when i am restarting kubelet and checking journalctl logs then getting following error:
Sep 19 06:05:36 ubuntu kubelet[2619287]: I0919 06:05:36.522015 2619287 state_mem.go:36] "Initialized new in-memory state store"
Sep 19 06:05:36 ubuntu kubelet[2619287]: E0919 06:05:36.522038 2619287 container_manager_linux.go:351] "Failed to initialize memory manager" err="the total amount \"0\" of type \"memory\" is not equal to the value \"32868Mi\" determined by Node Allocatable feature"
Sep 19 06:05:36 ubuntu kubelet[2619287]: E0919 06:05:36.522057 2619287 run.go:74] "command failed" err="failed to run Kubelet: the total amount \"0\" of type \"memory\" is not equal to the value \"32868Mi\" determined by Node Allocatable feature"
Sep 19 06:05:36 ubuntu systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
<img width="668" alt="image" src="https://github.com/kubernetes/website/assets/99728641/ea24f9db-ad8d-4fe6-b6fd-20b62d9f5e1a">

**Comment by tamilselvan1102** [comment]
@imkuldeepsingh 
have you drained the node?

**Comment by tengqm** [comment]
/close
The flag is for `kubelet`, not for `kube-apiserver`.
