### ISSUE TITLE
Improvement in the Storage Classes documentation

### ISSUE THREAD

**Issue by thisisharrsh** [kubernetes/website#43103]
**This is a Bug Report**
**Problem:** In the [`Volume Binding Mode`](https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode) section of the [`Storage Classes`](https://kubernetes.io/docs/concepts/storage/storage-classes/) page, there is a list that shows 'all of the above' in the `WaitForFirstConsumer` with pre-created persistent volume binding.

**Proposed Solution:** There must be a proper description or a list in place of 'all of the above' which can help the readers understand better.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by tengqm** [comment]
/triage accepted
Maybe a simple clarification would solve this confusion.

**Comment by thisisharrsh** [comment]
I would like to work on this issue 
/assign

**Comment by thisisharrsh** [comment]
The issue is fixed here: #43429
