### ISSUE TITLE
Incorrect hyperlinks under the Ingress docs

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#43105]
**This is a Bug Report**

**Problem:**
The hyperlinks for **`spec`**, **`flag`**, and **`recommended`** which are mentioned under [The Ingress resource](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource) on the [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/) concept page are redirected to incorrect contents.

**`spec`**: redirects to the `https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status` link which doesn't contain any information for ingress spec, it is just understanding for the spec fields. The correct link for it should be: `https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec`

**`flag`**: redirects to the `https://kubernetes.github.io/ingress-nginx/#what-is-the-flag-watch-ingress-without-class` link, which doesn't contain any information for it, actually the content is now moved under the  [FAQ - Migration to Kubernetes 1.22 and apiVersion networking.k8s.io/v1](https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#faq-migration-to-kubernetes-122-and-apiversion-networkingk8siov1) docs, so the correct link for it should be: `https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#what-is-the-flag-watch-ingress-without-class`

**`recommended`**: redirects the `https://kubernetes.github.io/ingress-nginx/#i-have-only-one-instance-of-the-ingresss-nginx-controller-in-my-cluster-what-should-i-do` which doesn't contain any information for it, the original content is now moved under
[FAQ - Migration to Kubernetes 1.22 and apiVersion networking.k8s.io/v1](https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#faq-migration-to-kubernetes-122-and-apiversion-networkingk8siov1) docs, so the correct link for it should be: `https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#i-have-only-one-ingress-controller-in-my-cluster-what-should-i-do`

**Proposed Solution:**
**`spec`**, **`flag`**, and **`recommended`**  should redirects to the `https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec`, `https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#what-is-the-flag-watch-ingress-without-class`, and `https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#i-have-only-one-ingress-controller-in-my-cluster-what-should-i-do` respectively.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by Shubham82** [comment]
I'm working on this and will raise a PR for it soon.
/assign
/triage accepted

**Comment by aj11anuj** [comment]
I think that much hardwork wasn't needed to describe this issue, first 2 lines were enough 😅. Rest of the description could have been kept for PR, anyways 👍

**Comment by rishavkankane** [comment]
> I think that much hardwork wasn't needed to describe this issue, first 2 lines were enough 😅. Rest of the description could have been kept for PR, anyways 👍

I dont think so @aj11anuj  this issue is addressing 3 different in it and a proper description of the issue is provided.

related to https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

**Comment by sftim** [comment]
/retitle Incorrect hyperlinks under the Ingress docs

**Comment by sftim** [comment]
> **Proposed Solution:** **`spec`**, **`flag`**, and **`recommended`** should redirects to the `https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec`, `https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#what-is-the-flag-watch-ingress-without-class`, and `https://kubernetes.github.io/ingress-nginx/user-guide/k8s-122-migration/#i-have-only-one-ingress-controller-in-my-cluster-what-should-i-do` respectively.

I don't agree with the proposed solution.
- Try to link to concept pages for each thing we want to explain
- If feasible, _drop_ the links to https://kubernetes.github.io/ingress-nginx/* from the concept page.

**Comment by tengqm** [comment]
@Shubham82 are you working on this as suggested by @sftim ?

**Comment by tengqm** [comment]
Okay. Can be closed. PR is being kicked in.
