### ISSUE TITLE
Backup of Container in kubernetes

### ISSUE THREAD

**Issue by albertsuki265** [kubernetes/website#43112]
I am wondering  about the backup of Stateless or stateful container in kubernetes.  I am bit confused that do we need to always take the backup of the containers in kubernetes?
Do we have the supportive lines in the doc of kubernetes.?

**Comment by niranjandarshann** [comment]
Hi @albertsuki265  Yes you can take backup of stateless container  as it was designed in such a way that it can handle data and their task by themself. Stateless is ephemeral in nature so its a need to  take the backup of the data or task continuously.
I think this  give you the some overview of your confusion.

**Comment by albertsuki265** [comment]
> Hi @albertsuki265 Yes you can take backup of stateless container as it was designed in such a way that it can handle data and their task by themself. Stateless is ephemeral in nature so its a need to take the backup of the data or task continuously. I think this give you the some overview of your confusion.

Hi @niranjandarshann  I think if the organization is taking the backup of the data and recreate it after the limit of usage is crossed by accessing those data. This will be the security concern So what one should do for data protection and backup protection.

**Comment by niranjandarshann** [comment]
> > Hi @albertsuki265 Yes you can take backup of stateless container as it was designed in such a way that it can handle data and their task by themself. Stateless is ephemeral in nature so its a need to take the backup of the data or task continuously. I think this give you the some overview of your confusion.
> 
> Hi @niranjandarshann I think if the organization is taking the backup of the data and recreate it after the limit of usage is crossed by accessing those data. This will be the security concern So what one should do for data protection and backup protection.

Hello @albertsuki265 , Exactly i cannot understand what you are looking for , but whatever i had understood i think you are asking for the data protection  in backup ? Correct me if i am wrong.

**Comment by niranjandarshann** [comment]
So if if you are looking for data protection and security concern  while using the backed data by the organization. 
Let me first clear you that the organization must be confirmed with the strong and rigid backup policy and data protection mechanisms. These will help the organization in every aspect of business development not only in container backup.

**Comment by niranjandarshann** [comment]
Keys point must be kept in mind while backup.
- How long data should be stored.
-  protection from Data loss
-  which type of data should be backedup
-  Must be introduced with backup tools by kubernetes etc.

**Comment by albertsuki265** [comment]
> > > Hi @albertsuki265 Yes you can take backup of stateless container as it was designed in such a way that it can handle data and their task by themself. Stateless is ephemeral in nature so its a need to take the backup of the data or task continuously. I think this give you the some overview of your confusion.
> > 
> > 
> > Hi @niranjandarshann I think if the organization is taking the backup of the data and recreate it after the limit of usage is crossed by accessing those data. This will be the security concern So what one should do for data protection and backup protection.
> 
> Hello @albertsuki265 , Exactly i cannot understand what you are looking for , but whatever i had understood i think you are asking for the data protection in backup ? Correct me if i am wrong.

@niranjandarshann  my question here is There should be the security concern while backing up  the data which may effect business. I think yes you understood well, my question.

**Comment by albertsuki265** [comment]
> Keys point must be kept in mind while backup.
> 
> * How long data should be stored.
> * protection from Data loss
> * which type of data should be backedup
> * Must be introduced with backup tools by kubernetes etc.

Understood , We are somehow diverting from our main concern . like can we backup container in kubernetes by keeping our data more secure.? Summarize in brief.

**Comment by niranjandarshann** [comment]
> > Keys point must be kept in mind while backup.
> > 
> > * How long data should be stored.
> > * protection from Data loss
> > * which type of data should be backedup
> > * Must be introduced with backup tools by kubernetes etc.
> 
> Understood , We are somehow diverting from our main concern . like can we backup container in kubernetes by keeping our data more secure.? Summarize in brief.

The answer is yes, you can take backup of container in kubernetes by keeping our data secure as by folling the backup policy and backup tools by kubernetes and the environment. This will keep data safe secure and reliable. 
In stateless which is ephemeral in nature like after recreating the cluster whole data get deleted  before recreating you need to keep the backup of configuration , data and all. which can be accessed after recreation of cluster.
 So i can say backing up container is possible and can be secure.

**Comment by rishavkankane** [comment]
The information provided by @niranjandarshann  is quite impressive the question arrised by @albertsuki265  was also good .
Asking @albertsuki265  can i get the link of the related page.

**Comment by niranjandarshann** [comment]
@rishavkankane  I dont find any direct link in kubernetes Website. It may be the project need or any but really the question is reasonable and interesting.

**Comment by niranjandarshann** [comment]
@albertsuki265  K8s slack channels are better place for resolving these type of issues and support related questions. , then you can join with this [link](https://communityinviter.com/apps/kubernetes/community) and ask your question there at appropriate channels.

**Comment by sftim** [comment]
This is a support query, but I think there is a related documentation gap that we could file a feature request issue for.

**Comment by niranjandarshann** [comment]
> This is a support query, but I think there is a related documentation gap that we could file a feature request issue for.

@sftim  yes documentation related to backup is having a gap whose blog  should be more useful.

**Comment by albertsuki265** [comment]
> This is a support query, but I think there is a related documentation gap that we could file a feature request issue for.

Yes we can  or i can say it will be good to have this in  separate topic in the documentation.

**Comment by albertsuki265** [comment]
@niranjandarshann in  ref of your comment i worked on it and found it working. Thank you for your help. 
@sftim there is the gap of this feature in the kubernetes documentation i wondered around  the entire and hadn't get it. So my suggestion is please add this topic in the documentation it will be more helpful for the new reader  to the doc. 
@niranjandarshann you can also give suggestion on it.

Thank you to the community. If you all think my suggestion is helpful work on it.

**Comment by sftim** [comment]
This is written like support query, but I think there is a related documentation gap that we could file a feature request issue for.

If you'd like to file that @albertsuki265, visit https://github.com/kubernetes/website/issues/new/choose and select “feature request”.

**Comment by albertsuki265** [comment]
can you people , please help me in finding out the page to update ? 
Then i will request the feature issue .
https://kubernetes.io/docs/concepts/containers/ according to me is this page is where we should add or something else.

**Comment by niranjandarshann** [comment]
@albertsuki265 this is the correct page in which you can search for the other section and then decide which should be more appropiate . Let @sftim  to  respond on it as he should help more efficiently.

**Comment by albertsuki265** [comment]
i am not sure in which page the new feature needs to be updated so allowing anyone among you all to raise feature request as asked by @sftim ,
 @niranjandarshann, @sftim   you can raise issue if you want.

**Comment by niranjandarshann** [comment]
> i am not sure in which page the new feature needs to be updated so allowing anyone among you all to raise feature request as asked by @sftim , @niranjandarshann, @sftim you can raise issue if you want.

@albertsuki265  sure will do.
