### ISSUE TITLE
Install and Set Up kubectl on macOS(Apple Silicon) - error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by suryanadh08** [kubernetes/website#43125]
I have installed latest version of kubectl on macOS(13.4.1). However I'm unable to run any of kubectl commands.

./kubectl version --client
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

./kubectl get pod -n application
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

**Comment by thisisharrsh** [comment]
Hi @suryanadh08, It looks like that kubectl is trying to use a plugin that is not compatible with your current version of the Kubernetes.

**Comment by thisisharrsh** [comment]
You can try to update all your kubectl plugins to the latest version.

**Comment by suryanadh08** [comment]
@thisisharrsh I don't have any plugin installed manually except aws. Kubernetes cluster version is 1.25

aws --version
aws-cli/2.0.30 Python/3.7.4 Darwin/22.5.0 botocore/2.0.0dev34

**Comment by suryanadh08** [comment]
@thisisharrsh issue is sorted after upgrading aws-cli version from 2.10.x to 2.11.x. Thanks for your support.
