### ISSUE TITLE
Extend the Kubernetes API with CustomResourceDefinitions

### ISSUE THREAD

**Issue by jli3388** [kubernetes/website#43122]
"While most validations placed in the OpenAPIV3 schema of a CRD are support ratcheting"

should probably be 

"While most validations placed in the OpenAPIV3 schema of a CRD support ratcheting"

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/ 

/language en

**Comment by thisisharrsh** [comment]
The issue is resolved here #43130.

**Comment by thisisharrsh** [comment]
Hi @jli3388, The issue is resolved now, Could you please close this issue?

**Comment by sftim** [comment]
/close

Resolved in #43130
