### ISSUE TITLE
[hi] Diagrams of "Contribute" page are showing error

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43127]
**This is a Bug Report**

**Problem:**
Diagram of [this page](https://kubernetes.io/hi/docs/contribute/) in Hindi are showing syntax error. Maybe it's due to real syntax error or someone maybe wasn't abled to make those diagrams in Hindi and just added english diagrams link, with few words changed to hindi that didn't worked.

![Screenshot (734)](https://github.com/kubernetes/website/assets/116108975/a959aee0-1d17-4664-8c9e-d6516cd3f2df)

**Proposed Solution:**
Fix those diagram links or if needed then make those diagrams in Hindi.

**Page to Update:**
https://kubernetes.io/hi/docs/contribute/

**Comment by sftim** [comment]
/triage duplicate

This duplicates https://github.com/kubernetes/website/issues/31960

**Comment by aj11anuj** [comment]
> /triage duplicate
> 
> This duplicates #31960

Sorry, for not checking that a similar issue already exists. After going through discussion of that issue, i found that literally so many people has raised a duplicate/similar issue already intentionally/unintentionally and i joined that club too now 🤐.

Well i generally use Chrome, Edge and sometimes Firefox browser and i never found that issue on original K8s site. I only found this issue today on [hi/docs/contribue/](https://kubernetes.io/hi/docs/contribute/) page and so, i thought it's only on this page. 

No matter which browser i use or how many reloads i do, i'm only able to see this diagram error in this [hi/docs/contribue/](https://kubernetes.io/hi/docs/contribute/) page only every single time. Is it really browser dependent issue? Then why i'm not able to see it in any other page with same browser?

**Comment by sftim** [comment]
As this is a duplicate report, I'll close it. Work on the [original issue](https://github.com/kubernetes/website/issues/31960) is very very welcome.

/close
