### ISSUE TITLE
Extend the Kubernetes API with CustomResourceDefinitions

### ISSUE THREAD

**Issue by jli3388** [kubernetes/website#43121]
simple typo:  "The API server is willing accept updates to resources that are not valid after the update"  
It probably should be "The API server is willing **to** accept updates to resources that are not valid after the update"

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

/language en 
/kind/bug

**Comment by Ritikaa96** [comment]
Page to update : https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-ratcheting
Good catch. 
Hi @jli3388 are you willing to work on this issue? 
Please `/assign` it to yourself if you want to contribute. Also, it will be better if you can find more improvements to make in the same page. 

/kind bug
/triage accepted

**Comment by Ritikaa96** [comment]
Please close #43122 as it is a duplicate of this issue.

**Comment by thisisharrsh** [comment]
Hi @jli3388, Thank you for raising the issue please let me know if you want to work on this issue; I will unassign it. 
Also, make sure to follow the community guidelines by not creating multiple issues on a single page.

**Comment by aj11anuj** [comment]
Issue #43122 could have also been added here, instead of a separate issue

/remove-kind bug
/kind feature
/sig docs

**Comment by thisisharrsh** [comment]
The issue is resolved here #43130.
