### ISSUE TITLE
Can we use volume copy in existing volume?

### ISSUE THREAD

**Issue by rishavkankane** [kubernetes/website#43124]
I am facing a problem with the volume snapshot, the only answer as i am getting some error ?
My question  is simple , May i use the volume snapshot in pre existing volume?
Can it be used as a Persistent Volume? Where we can use it in new volume or in the existing volume only?

**Comment by AmarNathChary** [comment]
Yes, you can use a volume snapshot to restore an existing volume to a previous state, not just for creating new volumes.

**Comment by AmarNathChary** [comment]
It can also be used to create a persistent volume. it can be used either in the new volume or in the existing volume.

**Comment by AmarNathChary** [comment]
> @AmarNathChary but i am facing error in provisioning it in the existing volume So can you help me with the possible reason ?

@rishavkankane I think there should be a permission issue with the service provider for creating the volume snapshot.
you can check the user role for permission.

**Comment by AmarNathChary** [comment]
_Page related to the issue_ : https://kubernetes.io/docs/concepts/storage/volume-snapshots/

/language en

**Comment by rishavkankane** [comment]
Thanks @AmarNathChary 
closing this issue as responded
/close
