### ISSUE TITLE
Ambiguity in 'beyond discovery permissions' wording in "Using RBAC Authorization" page

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#43145]
> https://kubernetes.io/docs/reference/access-authn-authz/rbac/#service-account-permissions
> Default RBAC policies grant scoped permissions to control-plane components, nodes, and controllers, but grant no permissions to service accounts outside the kube-system namespace (beyond discovery permissions given to all authenticated users).

> https://kubernetes.io/docs/reference/access-authn-authz/rbac/#upgrading-from-abac
> Default RBAC policies grant scoped permissions to control-plane components, nodes, and controllers, but grant no permissions to service accounts outside the kube-system namespace (beyond discovery permissions given to all authenticated users).

The phrase "beyond discovery permissions given to all authenticated users" in these two sections seems inaccurate. It is quite possible to guess that it references to [API discovery roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#discovery-roles) namely `system:basic-user`, `system:discovery`, `system:public-info-viewer`, but because of "discovery permissions" phrase it seems to only refer to `system:discovery`. It would be better to use different wording, for example:

 - beyond the permissions given by [API discovery roles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#discovery-roles)
 - beyond the permissions given by `system:authenticated` and `system:unauthenticated` groups
 - beyond the permissions given by `system:basic-user`, `system:discovery`, `system:public-info-viewer` cluster roles

**Comment by dipesh-rawat** [comment]
/retitle Ambiguity in 'beyond discovery permissions' wording in "Using RBAC Authorization" page

**Comment by tengqm** [comment]
/triage accepted
A clarification seems reasonable.

**Comment by T-Lakshmi** [comment]
#44643 PR working on this issue.
