### ISSUE TITLE
Update link text terminology to 'Localizing' instead of 'Translating' on docs home page

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43148]
**This is a Feature Request**

**What would you like to be added/enhanced?**
I could have directly raised a PR for it, but i didn't found the file where its written, so raising it as issue.
I think "Localizing" word could be better fit here than "Translating", and across K8s site "Localization" term is used everywhere so...
Page: [Docs home page](https://kubernetes.io/docs/home/)

![Screenshot (770)](https://github.com/kubernetes/website/assets/116108975/e41397a8-30fb-4bcc-82ab-030fbda29529)

**Comment by dipesh-rawat** [comment]
/retitle Update link text terminology to 'Localizing' instead of 'Translating' on docs home page

**Comment by steve-hardman** [comment]
plz plz i want work this.

/assign

**Comment by steve-hardman** [comment]
@dipesh-rawat Can you please let me know how to proceed with making the change? I'm relatvely new contributor. Any pointers will be help me. Thanks:)

**Comment by dipesh-rawat** [comment]
@steve-hardman The [docs home page](https://kubernetes.io/docs/home/) employs [Hugo Templates](https://gohugo.io/templates/) to render  the Markdown file [docs/home/_index.md](https://github.com/kubernetes/website/blob/main/content/en/docs/home/_index.md?plain=1 ) as a corresponding HTML page. _(See [layouts/docs/docsportal_home.html](https://github.com/kubernetes/website/blob/main/layouts/docs/docsportal_home.html) and [layouts/partials/docs/docs-portal-card.html](https://github.com/kubernetes/website/blob/main/layouts/partials/docs/docs-portal-card.html))_


To address the issue with link text displayed on the page. Navigate to the markdown file [localization.md
](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/localization.md), go to [line 11](https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/localization.md?plain=1#L11), and change the `title: ` attribute in the markdown front matter, to see if it resolves the problem. I hope this suggestion will be of assistance!

**Comment by steve-hardman** [comment]
wow thanks for taking effort to explain this. Would have taken you less time to fix this yourself than explain me here(lol). Appreciate it, thanks a lot!

**Comment by steve-hardman** [comment]
Submitted pull request https://github.com/kubernetes/website/pull/43153 please review when get time. thanks!
