### ISSUE TITLE
Add a section on service topology and how to use it with services

### ISSUE THREAD

**Issue by pranav-pandey0804** [kubernetes/website#43144]
**This is a Feature Request**

**What would you like to be added:**

- I would like to add a section on service topology and how to use it with services. 

- The section should explain what service topology is, how it works, its benefits and limitations, and how to enable it for services. 

- The section should also provide examples and diagrams to illustrate the concepts and steps.

**Why is this needed:**

- This is needed because the current Kubernetes Service documentation page does not cover the topic of service topology, which is a feature that allows users to define the network topology for routing traffic to service endpoints based on the node labels of the source and destination nodes. 
- This feature was introduced in Kubernetes 1.17 and it can improve performance and reliability by keeping traffic within the same zone or region.

**Comment by tengqm** [comment]
@paralika What do you mean by "service topology" ?

**Comment by pranav-pandey0804** [comment]
@tengqm It's a feature that allows users to define the network topology for routing traffic to service endpoints based on the node labels.

**Comment by sftim** [comment]
Does https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/ cover what you want? If not, what's missing from that page?
