### ISSUE TITLE
Pod Overhead Problem

### ISSUE THREAD

**Issue by virtualss** [kubernetes/website#43157]
When i was reading https://kubernetes.io offical document  [Pod Overhead](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/#usage-example) section
I encountered a problem that confused me

This line describes that the scheduler adds the
**requests** and the **overhead** and then looks for a node has 2.25 CPU and 320 MiB of memory available.
https://github.com/kubernetes/website/blob/afc1a7112382170fce647aecbf98c2ca0847cf88/content/en/docs/concepts/scheduling-eviction/pod-overhead.md?plain=1#L104-L105

**But** actually the sample yaml file content is:
https://github.com/kubernetes/website/blob/afc1a7112382170fce647aecbf98c2ca0847cf88/content/en/docs/concepts/scheduling-eviction/pod-overhead.md?plain=1#L58-L80

https://github.com/kubernetes/website/blob/afc1a7112382170fce647aecbf98c2ca0847cf88/content/en/docs/concepts/scheduling-eviction/pod-overhead.md?plain=1#L47-L50

It adds **limit** and **overhead** equals 500m(the limit cpu of busybox-ctr) + 1500m(the limit cpu of nginx-ctr) + 250m(the fixed cpu overhead) = 2500m(2.25 CPU)

Therefore, these two are contradictory before and after. 
I want to know which is the basis for scheduling, depends on **(limit+overhead)** or **(request+overhead)** ?

**Comment by pranav-pandey0804** [comment]
Hi, @virtualss 
I think the correct behavior of the scheduler is to add the requests and the overhead, not the limits and the overhead when looking for a node that can run a pod.
This is consistent with the [Pod Overhead](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/) feature description and the [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/688-pod-overhead/README.md) for this feature.

**Comment by tengqm** [comment]
If you specify 'limits' but omit 'requests', k8s treats that 'limits' as the 'requests' but won't treat the Pod as Guaranteed QoS.
The calculation 500m + 1500m + 250m = 2250m = 2.25 CPU, which is correct.
/close
