### ISSUE TITLE
Redirecting from http to https

### ISSUE THREAD

**Issue by albertsuki265** [kubernetes/website#43162]
How can we redirect http to https using ingress in kubernetes? Give description on it? Help me to find its solution.

**Comment by pranav-pandey0804** [comment]
hi @albertsuki265 
GitHub may not be the most suitable platform for addressing support requests.

If you are seeking assistance with Kubernetes, we recommend checking [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and, if you can't find an answer to your question, consider posting it there.

Additionally, you might find it helpful to pose your inquiry on the [Kubernetes Slack channel](https://communityinviter.com/apps/kubernetes/community) or the [Discuss Kubernetes forum](https://discuss.kubernetes.io/). These platforms are well-suited for engaging with the Kubernetes community and receiving support.

**Comment by albertsuki265** [comment]
I think support labelling is used to help developers/ users in there deployment work. without addressing issue you are asking like you cannot ask for support here. First address this issue then you can ask for anything. I think this is bad  practice.

**Comment by pranav-pandey0804** [comment]
Hi @albertsuki265,

Thank you for your feedback and for your understanding of the **support** label. We appreciate your engagement with the Kubernetes community.

You are correct that the **support** label is indeed meant for addressing issues related to Kubernetes components. We're here to help. My previous response was intended to guide you to the most appropriate places for getting support quickly, as GitHub issues might not be the fastest way to resolve support requests. That said, I understand your point, and I'll be happy to assist wherever I'm able to.

I appreciate your feedback, and your point about improving Kubernetes documentation is well-taken. If you think there are areas where the documentation can be enhanced, you can consider contributing or providing suggestions to the Kubernetes documentation team as well.

**Comment by tengqm** [comment]
You can, in a sense, treat "kind/support" as "kind/wont-fix".

**Comment by sftim** [comment]
> &hellip;seeking for the solution this is not the solution if community is having label support it means users can ask for the support while using the components of kubernetes. If user cannot ask for assistance then why there is the labelling **support** is used in the interface of raising issue in github. Hope this issue can help the community to focus or add some useful topic missing in kubernetes doc. I think this issue is correct as many are redirecting from http to secure http then why not one should ask query in support.
> 
> Docs are there to support the developer if there is anything missing one should ask for support.
> 
> I request you if possible provide the appropriate answer about the issue you labelled as support here. Thanks

You can ask for help. The places you can ask include Slack and Discuss Kubernetes (see https://github.com/kubernetes/website/issues/43162#issuecomment-1731334050). But _not_ here - this is an issue tracker, which we use to manage improvements to the website.

Maybe you wanted to suggest an improvement? You can do that; to make the suggestion, fill in the “feature request” template starting from https://github.com/kubernetes/website/issues/new/choose and notice the wording “_as precisely as possible_”.

In terms of the question you asked, it was clearly a request for help and unfortunately for you, was in the wrong place.
I'll close this issue. You are welcome to suggest work to improve the docs - please bear in mind that the person who works on that is very likely to be a volunteer offering their time in addition to other responsibilities.
If you did just want help, please do look at the other avenues available (both for paid advice, and gratis).

/close not-planned
