### ISSUE TITLE
Assistance request: Pipeline fails to connect to API server in private AKS cluster

### ISSUE THREAD

**Issue by veluguvamshi** [kubernetes/website#43160]
HI team ,
I was working with AKS . Client has given the Private cluster and a jump server . now while running the pipeline we are unable to connect to the api server. when we tried of making the service connection the connection is not happeneing with the api server address that is present in the AKS.

**Comment by tamilselvan1102** [comment]
/kind support

GitHub is not the right place for support requests 

If you are looking for help about using Kubernetes, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and ask your question there if a similar question has not yet been answered.

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by dipesh-rawat** [comment]
/retitle Assistance Needed: Pipeline fails to connect to API server in private AKS cluster

**Comment by sftim** [comment]
/retitle Assistance request: Pipeline fails to connect to API server in private AKS cluster

It might be a request but it's not a _need_ in terms of the Kubernetes project's priorities.

/close not-planned

@veluguvamshi if you later realise where the Kubernetes documentation could have helped you more, but didn't, please consider explaining the gap in a (new) issue.
