### ISSUE TITLE
Hover Effect on Buttons

### ISSUE THREAD

**Issue by Rituraj-13** [kubernetes/website#43173]
**This is a Feature Request**

- Adding Hover Effect on these buttons for better user experience.
-[ Link of the website.](https://kubernetes.io/)

![image](https://github.com/kubernetes/website/assets/90104572/81a701c7-a7a4-4d73-a2b5-f1cc1f5048ac)

**What would you like to be added**

- I will add hover effects on these buttons .

**Why is this needed**

- This is necessary to enhance the user experience when interacting with these buttons.

**Comment by dipesh-rawat** [comment]
Fixed in PR https://github.com/kubernetes/website/pull/43175

/close
