### ISSUE TITLE
`secret` missing in docker-registry secret command in kubectl-command docs

### ISSUE THREAD

**Issue by Bhaskar1312** [kubernetes/website#43180]
**This is a Bug Report**

**Problem:**
The command in the usage section is `$ kubectl create docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-file=[key=]source] [--dry-run=server|client|none]`
it should be `$ kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-email=email [--docker-server=string] [--from-file=[key=]source] [--dry-run=server|client|none]`
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-secret-docker-registry-em-
**Proposed Solution:**
add `secret` in the command
**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
This is likely to be a bug in https://github.com/kubernetes-sigs/reference-docs/ (the code that generates the reference)

Also see https://github.com/kubernetes/website/issues/42957
