### ISSUE TITLE
All localized README.md files needs to be updated

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43193]
**This is a Bug Report**

**Problem:**
Due to recent merge of PR #43043 & #43044, all Localized README.md files needs to be updated

**Comment by tengqm** [comment]
/close
Please don't try to speak for all localization teams. Each and every team has their own schedule and facilities to sync these changes.
In theory, every upstream change to the English content should be (eventually) sync'ed to all localizations. But, we are not supposed to file an issue for all these upstream changes.

**Comment by aj11anuj** [comment]
Oh, Ok got it 😶👍
