### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

### ISSUE THREAD

**Issue by cyford** [kubernetes/website#43200]
when you remove all kubernetes applications an remove all files and directories   specificly this one /etc/systemd/system/kubelet.service.d/  

Re-installing all kubernetes with apt install,   does not automaticly generate it again.  atleast with debian 11.

i need to manually create this file.

**Comment by sftim** [comment]
Which Kubernetes package source are you using @cyford? If these are official Kubernetes packages, it might be a bug in the package not the docs. And if these are Debian's own packages, this is the wrong bug tracker for that report.

(I can't really tell from the issue report as I'm reading it)

/triage needs-information

**Comment by tamilselvan1102** [comment]
Related page : https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/kubelet-integration/

**Comment by tengqm** [comment]
/close
This is not a docs issue.
Please report this to the upstream repo (kubernetes/kubernetes).
