### ISSUE TITLE
Incorrect file `/var/lib/kubelet/config.conf` mentioned in `kubeadm upgrade node phase kubelet-config` command

### ISSUE THREAD

**Issue by jrhunger** [kubernetes/website#43213]
>Run kubeadm upgrade node phase kubelet-config to download the latest kubelet-config ConfigMap contents into the local file /var/lib/kubelet/config.conf

The local file name should be /var/lib/kubelet/config.yaml

```
# kubeadm upgrade node phase kubelet-config
[upgrade] Reading configuration from the cluster...
[upgrade] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[upgrade] Backing up kubelet config file to /etc/kubernetes/tmp/kubeadm-kubelet-config3896343694/config.yaml
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[upgrade] The configuration for this node was successfully updated!
[upgrade] Now you should go ahead and upgrade the kubelet package using your package manager.
```

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Incorrect file `/var/lib/kubelet/config.conf` mentioned in `kubeadm upgrade node phase kubelet-config` command

**Comment by steve-hardman** [comment]
plz I want help to fix this
/assign

**Comment by jrhunger** [comment]
FYI, the same incorrect filename exists in other places on the same page.  Two are in the second blue-barred Note pane below the command, and three are further down in the [Persisting kubelet reconfiguration](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/#persisting-kubelet-reconfiguration) section

**Comment by steve-hardman** [comment]
@dipesh-rawat @sftim @tengqm (or other maintainers) Can I get confirmation and go ahead please; if this be a tirage-accepted issue to that i can proceed with the fix.

**Comment by tengqm** [comment]
/triage accepted
/kind bug
Thanks for spotting this.

**Comment by steve-hardman** [comment]
I have attempt to make fix for this in https://github.com/kubernetes/website/pull/43231
