### ISSUE TITLE
Fix unnecessary border in diagrams

### ISSUE THREAD

**Issue by PranitRout07** [kubernetes/website#43215]
_issue : Fix unnecessary border in diagram_ 

**ISSUE SUMMARY**
There is unnecessary border in the diagrams and it does not looks clean.

_To see this issue go to this link_ "https://kubernetes.io/docs/contribute/"

**SCREENSHOTS OF DIAGRAM HAVING UNNECESSARY BORDER**

<img width="639" alt="unnecessary_border_diagram1" src="https://github.com/kubernetes/website/assets/102309095/dada9f0d-ab9d-490b-b8e5-99d869cc325b">

<img width="551" alt="unnecessary_border_diagram2" src="https://github.com/kubernetes/website/assets/102309095/dfd06a13-86ac-432d-b81e-23d129dd6f2c">

**WHY NECCESSARY?**
To make the documentation look more clean .

**CLEAN DIAGRAM SCREENSHOTS**

<img width="1189" alt="without_border" src="https://github.com/kubernetes/website/assets/102309095/c3853399-9d31-42f1-8634-5640239eddcc">

_visit this link to see the diagram without border_ "https://kubernetes.io/releases/release/"

**Comment by AmarNathChary** [comment]
I will fix this 
/assign

**Comment by aj11anuj** [comment]
Can you point out using drawings/mocks like what actually you want to do?
-  Do you want to crop these diagrams for reducing white space? or
-  You want to remove solid black border lines?

/triage needs-information
/priority awaiting-more-evidence
/remove language-en

**Comment by AmarNathChary** [comment]
> visit this link to see the diagram without border "https://kubernetes.io/releases/release/"

@PranitRout07 This page is an auto-generated page and those diagrams are `.jpg`

**Comment by AmarNathChary** [comment]
You can see this 
https://github.com/kubernetes/website/blob/main/content/en/releases/release.md#the-release-cycle

and the diagrams you are referring to are in Mermaid.
https://github.com/kubernetes/website/blob/main/content/en/docs/contribute/_index.md#getting-started

**Comment by PranitRout07** [comment]
Remove the borders.

<img width="639" alt="unnecessary_border_diagram1c" src="https://github.com/kubernetes/website/assets/102309095/61cc70d0-b7d9-43fb-a47d-e87c3799cb39">

**Comment by AmarNathChary** [comment]
Raised PR in #43219

**Comment by tengqm** [comment]
I think it is a personal taste thing.
For example, I like borders. I won't suggest adding borders if diagrams don't have borders.

**Comment by Gauravpadam** [comment]
I don't see a dire need to change things here, But to each one's own taste
Please feel free to re-open

/close
