### ISSUE TITLE
kubeconfig (v1) #Config name is missing

### ISSUE THREAD

**Issue by performantdata** [kubernetes/website#43229]
In this auto-generated page, there are links to but no location for https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#Config.

**Comment by aj11anuj** [comment]
As far as i understood this issue, you want to say that there are 5-6 places where `Config` word hyperlinks isn't working in this page.
![Screenshot_2023-09-28-00-56-17-865_com android chrome](https://github.com/kubernetes/website/assets/116108975/318d5270-37ae-4caa-a321-bed1a118a88e)

I'm not sure, whether contents of autogenerated pages are encouraged to be changed

/sig docs
/kind bug
