### ISSUE TITLE
Better docs for garbage collection

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#4322]
**This is a...** 
- [X] Feature Request
- [ ] Bug Report

## Problem 

K8s docs discuss garbage collection in different articles:

- https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
- https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
- https://kubernetes.io/docs/admin/kube-controller-manager/
- https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

Multiple topics show little to no awareness of each other. 

Descriptions of garbage collection sometimes conflict. 

No single article fully describes garbage collection as a concept or comprehensively demonstrates its implementation. 

There is currently no task for garbage collection: only two concept articles and some incidental reference material.

## Proposed Solution

1. Consolidate conceptual content at https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/.

  See _Additional information_ for more details about conceptual content.

  Explain garbage collection in Kubernetes as a whole: what it is; why and how different components (kubelet, kube-controller-manager) handle it separately; and interactions and dependencies between components' garbage collection functions.

  Provide an end-to-end description of garbage collection in a typical production environment.

2. Create a new **task article**.

  Explain how to set up garbage collection in a typical production environment: 
    - Which components to configure, and in what order, for default function
    - How to assess the health of garbage collection for a pod

## Pages to update

- https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
- https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
- https://kubernetes.io/docs/admin/kube-controller-manager/

## Additional information

Different aspects of garbage collection appear to be handled by kubelet and kube-controller-manager. It's unclear from the documentation whether these components' garbage collection functions interact and the extent to which their functions are interdependent.

It's unclear which garbage control functions are available in which versions of Kubernetes:
  -  https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/:
  "Note: Garbage collection is a beta feature and is enabled by default in Kubernetes version 1.4 and later." 
  - Is garbage collection also a beta feature in kubelet and kube-controller-manager?

Different topics' descriptions of garbage collection don't match:
  - https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/ describes garbage collection as a function of kubelet.
  - https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/ describes a controller as "the Kubernetes garbage collector"
  - https://kubernetes.io/docs/admin/kube-controller-manager/ also sets some attributes for garbage collection.

Some of the most helpful material for understanding garbage collection mentions it only incidentally: 
  - https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

Multiple topics break the style guide by making statements about the future:

   - https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/: "Some kubelet Garbage Collection features in this doc will be replaced by kubelet eviction in the future."
  - https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/: "Kubernetes version 1.7 will add an admission controller that controls user access to set blockOwnerDeletion to true based on delete permissions on the owner object, so that unauthorized dependents cannot delay deletion of an owner object."

**Comment by nikhita** [comment]
Adding the help-wanted label as well, since it has `good first issue`.

/help

**Comment by rskrishnar** [comment]
@zacharysarah Is this still needed ?. I want to work on this.

**Comment by zacharysarah** [comment]
@rskrishnar Great--feel free to create a PR!

/reopen

**Comment by daminisatya** [comment]
@zacharysarah @tengqm This is a great issue. I would like to work on it. A good way to explore garbage collection in Kubernetes!

/assign

**Comment by VineethReddy02** [comment]
I would like to be one of contributor to the garbage collection. I have started exploring the above mentioned links.

**Comment by sftim** [comment]
I wonder if it makes sense to `/remove-help` on this issue(?)
If this is someone's first issue, they're a braver contributor than I.

**Comment by sftim** [comment]
/lifecycle frozen

This is an important topic to cover

**Comment by Aut0R3V** [comment]
Hey guys is anyone working on this?

**Comment by sftim** [comment]
We should move https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/ to a new home. The other pages in this section are about resources you can create to manage a workload (eg CronJob, Deployment).

**Comment by shannonxtreme** [comment]
Doc plan is [here](https://docs.google.com/document/d/1XeWLJtDwz67C1YOfABFe5cKw2ds5msMcEBLayuMJuiY/edit?usp=sharing) @sftim @zacharysarah please review, leave comments, and LGTM when ready or add other reviewers. Let's get the scope sorted before I dive into content :)

**Comment by sftim** [comment]
Maybe something to bring up in the SIG Docs Slack channel and / or during a SIG weekly meeting?

**Comment by shannonxtreme** [comment]
Draft content for the concept topic is here, with questions: https://docs.google.com/document/d/1fEzX14PQy8jpvgAmx-Qkdd9R-2XMV8YRjRPJ1dLuoSU/edit?usp=sharing

**Comment by sftim** [comment]
@shannonxtreme that looks like a great starting point - feel free to open a pull request

**Comment by raghvenders** [comment]
@shannonxtreme - I have given some review comments. Kindly do the changes if it inches the docs ahead.

**Comment by shannonxtreme** [comment]
> @shannonxtreme - I have given some review comments. Kindly do the changes if it inches the docs ahead.

Noticed! I wish we could call it Waste Management, lol. Thank you for the reviews! Feel free to review the PR as well and give feedback.

**Comment by raghvenders** [comment]
What inspired me was dependent cleanup for resources, in PV/PVCs came across retain, reclaim and recycle (Deprecated). :)
