### ISSUE TITLE
"Component tools" page is showing "command-line-tools" as it's slug

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43232]
**This is a Feature Request**

**What would you like to be added/enhanced?**
[Component tools page](https://kubernetes.io/docs/reference/command-line-tools-reference/) slug is showing "command-line-tools" that i think needs to be changed to "component-tools"

![Screenshot (812)](https://github.com/kubernetes/website/assets/116108975/31b2eff9-1452-4441-90af-525672eec78b)

**Comment by tengqm** [comment]
I don't think this is a bug or it needs a fix.

**Comment by tengqm** [comment]
It sounds like a mistake to use a slug here.
However, I'm not sure if fixing this will cause problems to users who have local bookmarks.
/triage awaiting-more-evidences
