### ISSUE TITLE
Administer a Cluster page is having redundant text under sub menu "Configure a kubelet image credential provider" 

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#43237]
**This is a Bug Report**
**Problem:**
Sub section "[Configure a kubelet image credential provider](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/) under [Administer a Cluster](https://kubernetes.io/docs/tasks/administer-cluster/) is having a redundant text(sub section name is repeating as a normal text).

![image](https://github.com/kubernetes/website/assets/56723673/6bafdae6-bc17-47b1-ac2b-19a776175cad)

**Proposed Solution:**
    Remove the text that present under "Configure a kubelet image credential provider".
**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/

**Comment by steve-hardman** [comment]
I want to help with this.
/assign

**Comment by steve-hardman** [comment]
I try to fix this in #43257
