### ISSUE TITLE
CRI Pod: unclear explanation about cAdvisor in the kubelet

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/website#43244]
> https://kubernetes.io/docs/reference/instrumentation/cri-pod-container-metrics/
> The kubelet collects pod and container metrics via cAdvisor.

The sentense is confusing because it lacks detail. Two problems:
1) One cannot understand where this metrics are. Acording to the [PodAndContainerStatsFromCRI](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) feature gate the location is in the kubelet API at `/metrics/cadvisor`.
2) There wasn't any information on [Concepts](https://kubernetes.io/docs/concepts/) and [Reference](https://kubernetes.io/docs/reference/) chapters before, but according to [Node metrics data](https://kubernetes.io/docs/reference/instrumentation/node-metrics/) subchapter it states that cAdvisor is embedded in the kubelet.

Also it would also be useful to add a link to [cAdvisor metrics](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md) to clarify exactly what metrics are meant.

Please, consider adding this information to the page.

P.S. It’s also interesting where one can find a description of the metrics located in `/metrics` for kubelet, kube-proxy, kube-scheduler and kube-controller-manager, something like [here](https://kubernetes.io/docs/reference/instrumentation/metrics/) or [here](https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md).

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/reference/instrumentation/cri-pod-container-metrics/
/language en

**Comment by tengqm** [comment]
I'm wondering if we really need to add documentations for the cAdvisor metrics.
They are to be replaced by a kube-native mechanism.
The substitution is still on-going.
I'm not confident that someone will come up with a reference for this.
This issue is gonna die away eventually.
Feel free to reopen it if there are some heroes to step up for this challenge.
/close
