### ISSUE TITLE
Multiple, similar Kubernetes basics tutorials that cause confusion

### ISSUE THREAD

**Issue by fabpico** [kubernetes/website#43256]
The basic tutorial starts at https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/, which leads to https://kubernetes.io/docs/tutorials/hello-minikube/, which leads to https://minikube.sigs.k8s.io/docs/start/.  
Since one does not know what is exactly meant with `already set up minikube` in the second site, one does also the deploy step. Because it's not clearly said "`just install minikube, and come back to this tutorial`" or so. Then you go back to the second site, to read all through, only to do create/expose again (with little extras), only to go back to the first site and do create/expose again.

Back to the first site on step 2, pretty much at the beginning it says:

> For your first Deployment, you'll use a hello-node application (..), you can do that first by following the instructions from the [Hello Minikube tutorial](https://kubernetes.io/docs/tutorials/hello-minikube/)).

> Let’s deploy our first app on Kubernetes with the kubectl create deployment command.

But I did it already 2 times in the current tutorial flow. Now I have 3 deployments, still in the basics deployment tutorial. 
Its like, there are 3 tutorials to do, which are the same, but also not the same.   
Instead of leading the user back and forth, I suggest to do one single sufficient tutorial.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Consolidate and streamline Kubernetes basics tutorials to avoid redundancy and confusion

**Comment by niranjandarshann** [comment]
@fabpico the three tutorial have different purpose.
What I understood the purpose of having these as three.:
- [Introduction to Kubernetes Cluster and there componets functioanlity](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) 
- [Second is showing the Deployment of the application using minikube `Hello Minikube`](https://kubernetes.io/docs/tutorials/hello-minikube/) 
- [Third is showing how to setup the kubernetes Cluster Using Minikube.](https://minikube.sigs.k8s.io/docs/start/)

Yes, Its  leading to back and forth of the users but  I think First link [introduction of Kubernetes  cluster and there component](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) showing the general functionality of the cluster's component. It  Should have the link To [setup Cluster using minikube](https://minikube.sigs.k8s.io/docs/start/) and then [Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) link will be helpful for readers to traverse. 

This sequence is lacking  in the page. Thats the reason why i thing its taking user back and forth several times .

**Comment by afbjorklund** [comment]
There was a previous attempt at de-duplicating, but it probably has to be been done again - after the removal of the Katacoda tutorials, which were using a hosted setup of `minikube' to run through the tutorials "inline" with the docs

* https://github.com/kubernetes/website/issues/15969

* https://github.com/kubernetes/website/issues/41625

**Comment by sftim** [comment]
I'll change the title to frame this as a bug.

/retitle Multiple, similar Kubernetes basics tutorials that cause confusion
/kind bug
/triage accepted
/priority important-longterm

**Comment by adityasamant25** [comment]
I will start working on this.
