### ISSUE TITLE
Unclear definition of `initialDelaySeconds` and `periodSeconds` 

### ISSUE THREAD

**Issue by olegmayko** [kubernetes/website#43259]
**This is a Bug Report**

**Problem:**
The intial definiton given in [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes) doesn't describe that if `periodSeconds` > `initialDelaySeconds` the first probe time will be = `periodSeconds`. 
For example:
``` 
readinessProbe:
   initialDelaySeconds: 20
   periodSeconds: 60
   tcpSocket:
      port: 8080
```
The pod will be marked as `Ready` after 60s, (tested in k8s v1.22.10).

Moreover, the [description](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe) given 
```
The kubelet will send the first readiness probe 5 seconds after the container starts. This will attempt to connect to the goproxy container on port 8080. If the probe succeeds, the Pod will be marked as ready. The kubelet will continue to run this check every 10 seconds.
```  
if i read this code correctly, then  the check is done for [PeriodSeconds](https://github.com/kubernetes/kubernetes/blob/afe4c041f392701da0a8bfd814dc19ed9ff32e56/pkg/kubelet/prober/worker.go#L153-L154) and the check for [InitialDelaySeconds](https://github.com/kubernetes/kubernetes/blob/afe4c041f392701da0a8bfd814dc19ed9ff32e56/pkg/kubelet/prober/worker.go#L268-L271) is done after assuming that value of `initialDelaySeconds` > `periodSeconds`

**Proposed Solution:**
Allign code and the documentation.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe

**Comment by Affan-7** [comment]
/assign

I would like to work on this.
Waiting for triage.

**Comment by Affan-7** [comment]
> The pod will be marked as `Ready` after 60s, (tested in k8s v1.22.10).

I did tested this on the k8s 1.27 and it's still same.

**Comment by tengqm** [comment]
> I believe this is a corner case. Why do you set initialDelaySeconds to be shorter than perdioSeconds in the first place? I'm not objecting the clarification, BTW. What I am wondering is if there is a real case people will do this.

Okay. I get it now. The example manifest has a problem to fix. Thanks for raising up this.

**Comment by olegmayko** [comment]
thanks :)
