### ISSUE TITLE
Add hyperlink to "GitHub repo" text

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/website#43262]
**This is a Feature Request**

**What would you like to be added**

I want to add a hyperlink to the "GitHub repo".

![image](https://github.com/kubernetes/website/assets/94950988/679f9ced-9447-4c4c-82f3-cb7f23d15f03)

**Comments**

Link to be added: https://github.com/kubernetes/website

**Comment by thisisharrsh** [comment]
Hi @satyampsoni, Could you please describe on which page of the documentation you are facing issue?

**Comment by satyampsoni** [comment]
This is under the feedback section of too many pages. We have to change all of them.

**Comment by Gauravpadam** [comment]
I think we need not change much here, A slight change in i18n markdown should do the trick

**Comment by Gauravpadam** [comment]
/assign
I'll do that

**Comment by satyampsoni** [comment]
Thanks for raising the PR @Gauravpadam . Also, Please focus on those issues first which have `triage/accepted` label.
