### ISSUE TITLE
Code snippet layout at "Kubeadm install" page is causing layout break of page for mobile devices

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43265]
**This is a Bug Report**

**Problem:**
Code snippet layout at [this page](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/), due to some error is displaying it in mobile view like this -
![Screenshot_2023-09-30-22-52-14-586_com android chrome](https://github.com/kubernetes/website/assets/116108975/5bad872a-58bd-4e64-8200-b0aff212ac48)
and causing layout break of whole page in mobile view like #42795, but here it's not duplicate of that issue as here this issue is caused by Code snippet layout which can be fixed, whereas what is causing layout break at #42795 is unknown yet.

**Comment by Gauravpadam** [comment]
Seems like an overflow break again, I'll get to this soon

**Comment by tengqm** [comment]
/triage accepted
Maybe a `overflow` setting is warranted.
