### ISSUE TITLE
Dropdowns in the navbar not functional when JavaScript is disabled

### ISSUE THREAD

**Issue by dipesh-rawat** [kubernetes/website#43276]
**This is a Bug Report**

**Problem:**
The dropdowns for "Version" and "Language" in the website's navbar do not function when JavaScript is disabled. This limitation can make it difficult for users to switch between different versions or languages of the site, impacting usability and accessibility.

**Expected Behaviour:**
The "Version" and "Language" dropdowns should function correctly even when JavaScript is disabled, allowing users to switch between different versions and languages of the site.

Raised this issue as request in https://github.com/kubernetes/website/pull/41687#discussion_r1335470711

/sig docs
/area web-development
/priority important-longterm

**Comment by sftim** [comment]
/kind feature
/remove-kind bug

Adding this support would be a new feature

**Comment by sftim** [comment]
(no need to Cc: me on this issue - I'm going to unsubscribe)

**Comment by sftim** [comment]
/remove-priority important-longterm

We haven't decided that as a SIG

**Comment by tengqm** [comment]
I don't see it feasible to completely avoid JS on the website.

**Comment by steve-hardman** [comment]
I'd like to share my perspective. In my previous job, we encountered a situation where our work systems and browser settings didn't support JavaScript (security reasons). As a workaround, we had a simplified version of the internal website with limited functionality that we could use. It was essentially the same website but without JavaScript using checks in the code. But being fairly new here I'm not sure how feasible it is to implement or the efforts required, but we should definitely explore this accessibility aspect and invest in it if possible. But then again I'm new here and don't have any decision making power. Overall, it would be +1 in favor of doing this.

**Comment by tamilselvan1102** [comment]
These dropdowns are implemented through [bootstrap] JS library, that's why it is not working when disabling JS in the browser. 
we can implement through only CSS but appearance may change from current.

**Comment by tengqm** [comment]
Another factor to consider. The Website is currently using docsy as its Hugo theme, where docsy has some builtin JS scripts as well.
