### ISSUE TITLE
Advice on how labels and selectors work

### ISSUE THREAD

**Issue by ksamedov1998** [kubernetes/website#43273]
`Labels are key/value pairs that are attached to [objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/#kubernetes-objects) such as Pods. Labels are intended to be used to specify identifying attributes of objects that are meaningful and relevant to users, but do not directly imply semantics to the core system. Labels can be used to organize and to select subsets of objects. Labels can be attached to objects at creation time and subsequently added and modified at any time. Each object can have a set of key/value labels defined. **Each Key must be unique for a given object.**

"metadata": {
  "labels": {
    "key1" : "value1",
    "key2" : "value2"
  }
}
Labels allow for efficient queries and watches and are ideal for use in UIs and CLIs. Non-identifying information should be recorded using [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).`

There is a given statement in bold that each label key must be unique for given object, I've created the deployment via the declerative way and I did put there 2 same named key and result is second one override the first one, is this statement still relevant for new version of kubernetes API

**Comment by sftim** [comment]
/retitle Advice on how labels and selectors work

This sounds like a request for advice about how Kubernetes works - have we got that right @ksamedov1998 ?

/kind support

**Comment by ksamedov1998** [comment]
While I was trying to implement as I read documentation I realize that that is possible to put the same key in labels and the last one overrides the previous one, but in docs mentioned that there is no way multiple values with the same key and I thought this piece of information is outdated and posted as recommendation to update  that information at docs

**Comment by tengqm** [comment]
Where is the first value for your key now?

**Comment by ksamedov1998** [comment]
As I describe the object such as Deployment first value is missing and that's why I used 'overriden' above comment

**Comment by tengqm** [comment]
Right. If the first value is missing, it is equivalent to that you assigned 10 to `a` and then 20 to `a`. The same key `a` is now 20. How would you define that is a different `a`?
How would you define two "same" keys in a map?

**Comment by ksamedov1998** [comment]
Does that mean it is not mandatory   And validated while reading the file same keys in labels. It is possible assign values to the same keys in file. Now it does make sense that keys are not forced to be unique at declaration file

**Comment by tengqm** [comment]
You may want to check what JSON spec says about maps. Do they allow duplicate keys in the same map? If the answer is no, the manifest you are drafting is not a valid JSON in the first place.
