### ISSUE TITLE
Outdated links to download `jq`

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#43285]
**This is a Bug Report**

**Problem:**
The download page for `jq` is now https://jqlang.github.io/jq/download/ (previously https://stedolan.github.io/jq/download/)

**Proposed Solution:**
Throughout the _English_ pages, replace the old download URL with the new one.

**Additional Information:**
/language en
/priority backlog
/triage accepted
/help

**Comment by steve-hardman** [comment]
I want to help with this.

/assign

**Comment by steve-hardman** [comment]
I have riasd PR https://github.com/kubernetes/website/pull/43299 to help with this issue.
