### ISSUE TITLE
Kubernetes.io analytics broken

### ISSUE THREAD

**Issue by xmulligan** [kubernetes/website#43281]
**This is a Bug Report**

**Problem:**
The dashboard linked to https://kubernetes.io/docs/contribute/analytics/ is currently broken because the data has moved or it no longer has access
<img width="1501" alt="Screenshot 2023-10-02 at 12 53 28" src="https://github.com/kubernetes/website/assets/29048870/cf42b13b-7d39-4e23-ba09-6434ef6f8135">

**Proposed Solution:**
Restore access to the data for the dashboard

**Page to Update:**
https://kubernetes.io/docs/contribute/analytics/

**Comment by aj11anuj** [comment]
It was working fine few days back, who knows what happened to it now🤷‍♂️

/priority backlog
/sig docs
/area web-development

**Comment by sftim** [comment]
/triage accepted

I think Google may have switched off the old analytics mechanism.

**Comment by satyampsoni** [comment]
> I think Google may have switched off the old analytics mechanism.

@sftim If it is so how to proceed with connecting to them now. It says " Please contact the data source owner to fix it."

**Comment by tengqm** [comment]
Maybe we can simply remove the link or even the whole page.
Does anyone live on this statistics?

**Comment by xmulligan** [comment]
I opened the issue because I was looking for the data, but since it wasn't noticed for a bit maybe not many people are

**Comment by geoffcline** [comment]
+1 on this - I think it is helpful to use this data for prioritizing improvements.

Is there somewhere I can look in the meantime?

**Comment by sftim** [comment]
> Is there somewhere I can look in the meantime?

Not that I know of. We would instead need to work on an actual fix.

**Comment by kumarankit999** [comment]
yes @sftim

**Comment by divya-mohan0209** [comment]
FWIW, the data till September-ish has been restored. This is because we switched over to the GA4 from Google UA sometime around then for Analytics. I tried adding the GA4 plugin as a brand new data source. However, due to the mismatch in the fields reported between the two, it wasn't a successful endeavour. 

Maybe @chalin @nate-double-u can comment on this, since they were working on the GA4 transition earlier this year?

**Comment by divya-mohan0209** [comment]
Raising the priority to critical/urgent, since this affects our annual report creation.

**Comment by a-mccarthy** [comment]
@divya-mohan0209 I can take a look at this if you'd like. I set up the dashboard originally

**Comment by divya-mohan0209** [comment]
@a-mccarthy : Yes please, that would be helpful. The dashboards seem to be broken again.

**Comment by a-mccarthy** [comment]
I will take a look! I have a suspicion that we need a whole new dashboard because google analytics 4 is completely different, but will keep you updated. Please let me know if there is anything specific I can help look up for the annual report. Sorry for not catching this earlier

/assign

**Comment by a-mccarthy** [comment]
Just to follow up, based on this comment from the migration issue, data in UA was deleted in 2024Q1, https://github.com/kubernetes/website/issues/35299#issuecomment-1450248093. The old UA data was used to populate the dashboard and the new G4 analytics are not compatible with UA, so we will need to make a new dashboard.

I've been testing out a few options, but google analytics 4 tracks things differently, so its a little bit tricky to get a dashboard that shows the same information. 

heres a screenshot of the pageview metrics from the g4 dashboard for the whole site for 2023. total page views 109 million, top pages (aside from search and home pages):
*  https://kubernetes.io/docs/reference/kubectl/quick-reference/ (formerly called kubectl Cheat Sheet)
* https://kubernetes.io/docs/concepts/services-networking/service/
* https://kubernetes.io/docs/concepts/services-networking/ingress/ which are the same top pages from last year. 

<img width="1306" alt="Screen Shot 2024-01-11 at 11 30 05 AM" src="https://github.com/kubernetes/website/assets/20771501/33f0acca-fee8-4d3f-b1a3-cf7443f4a048">

**Comment by a-mccarthy** [comment]
I have a new dashboard in progress: https://lookerstudio.google.com/reporting/fe615dc5-59b0-4db5-8504-ef9eacb663a9

This link should be viewable for everyone, but note that not all the graphs are updated to show meaningful data. I wanted to share out the link b/c it should at least be able to show the top pages and page views for the annual report. 

The existing dashboard is also back to working, the historical data is still available up to September 2023, when new tracking in UA stopped. Data from UA will be deleted on July 1, 2024 so there is still time to download it if we want to keep all the site history. (the dashboard thats up on the site was not working bc the data source was changed to the GA4 data, which is incompatible with the graphs. Apologies if it was me that did this, i honestly can't remember).
