### ISSUE TITLE
Replace "search" with "search this site"

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/website#43291]
**This is a Feature Request**

**What would you like to be added**

![image](https://github.com/kubernetes/website/assets/94950988/ffd73f80-30f8-4ead-b4e7-41d841311fb8)

**Why is this needed**
In every other search bar across kubernetes it is mentioned "search this site". The only search bar having "search" as the placeholder.
**Comments**
 page to edit: https://kubernetes.io/
/sig docs
/area web-development
/language en

**Comment by steve-hardman** [comment]
I can help with this when triaged.
/assign

**Comment by steve-hardman** [comment]
@satyampsoni Apologies for the direct mention. Would you be able to point me to the page URL where there is search bar with text "Search this site". 

I can only see "Search" placeholder in search input present in side bar at links https://kubernetes.io/docs/home/ https://kubernetes.io/blog/ which is what the homepage also uses.

**Comment by 92Mohammad** [comment]
Hey,@steve-hardman are you continue working on this issue
if not please leave it for me I am beginner

**Comment by Royal-Dragon** [comment]
is this still open. I can see it is not yet merged
/assign

**Comment by tengqm** [comment]
/triage accepted
/priority backlog
I'm personally surprised that this placeholder is causing confusion to anyone. But ... anyway.

**Comment by Gauravpadam** [comment]
We can close this as completed in #43316

**Comment by dipesh-rawat** [comment]
Fix merged as part of [#43316](https://github.com/kubernetes/website/pull/43316/files)
/close
