### ISSUE TITLE
Some clerical errors in "Learn Kubernetes Basics" Page

### ISSUE THREAD

**Issue by charfole** [kubernetes/website#43301]
In page [“Learn Kubernetes Basics”](https://kubernetes.io/docs/tutorials/kubernetes-basics/), the first part describes that an online interative tutorial is included. But in fact, this tutorial was shutdown a few months ago.

I think that may confuse some readers.
![1696323674429](https://github.com/kubernetes/website/assets/45024736/354156c0-dc60-451d-a32e-b31d9706da53)

**Comment by Affan-7** [comment]
Seems like it's katacoda related.

**Comment by whitebeard10** [comment]
you anyone  guide me on solving this? do i translate those 4 pages or ?

**Comment by Affan-7** [comment]
Hi @whitebeard10, you don't need to translate anything. Just create a PR for english.

(Optionally you can translate this if your know some other languages too. If you try to do so, raise a single PR per language.)
