### ISSUE TITLE
Misleading documentation around eviction and image garbage collection

### ISSUE THREAD

**Issue by kannon92** [kubernetes/website#43303]
We say that the ImageGCHighThresholdPercent/ImageGCLowThresholdPercent config option is deprecated for evictionHard settings but this is not true.

https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-signals

ImageGC uses `image-gc-high-threshold-percent` and `image-gc-low-threshold-percent` for Garbage collection so these flags are not [deprecated](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L421)

We should update our documentation to reflect this.

**Comment by kannon92** [comment]
/remove-sig scheduling
/sig node

Eviction is done in kubelet which is in sig-node's domain.

**Comment by SergeyKanzhelev** [comment]
/triage accepted

indeed this needs to be clarified. We unlikely will remove these flags soon. So need to fix up docs
