### ISSUE TITLE
Addition of upcoming KCSA Certification to Training page

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43317]
**This is a Feature Request**

**What would you like to be added?**
Addition of "Kubernetes and Cloud native Security Associate" [(KCSA) certification](https://training.linuxfoundation.org/certification/kubernetes-and-cloud-native-security-associate-kcsa/) to [Training page](https://kubernetes.io/training/)

![image](https://github.com/kubernetes/website/assets/116108975/8678cc98-8cd0-40c6-8e95-1a6b91539934)

This addition will be made in 2 sections of Training page:-
1. Addition of KCSA certification icon here
![Screenshot (817)](https://github.com/kubernetes/website/assets/116108975/96944af7-94eb-44c7-b43a-d7c5d7d7e766)

2. Addition of a short description with a tile and hyperlink like other certifications here
![Screenshot (818)](https://github.com/kubernetes/website/assets/116108975/42c2dc66-b8dd-4cd8-9b74-288960cc46c1)

**Comments**
This certification is yet to launch, Whenever it will be launched it depends on Linux Foundation, but all the necessary things required to put it in K8s site is already present on that certification page (Description of certification, Icon, Page link). Whether to make this feature request reserve for future or to fix it now depends on approvers.

**Comment by Community-Programmer** [comment]
Added of upcoming KCSA Certification to Training page 

![img](https://github.com/kubernetes/website/assets/76515568/6bd22ade-8fa1-4d5d-bcde-c51fec7d4234)

![img2](https://github.com/kubernetes/website/assets/76515568/cbe8022f-5c00-490f-b2a8-79f788be85ba)

**Comment by aj11anuj** [comment]
Closing this issue as it's PR is merged and this issue is now resolved.
