### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/topology-manager/

### ISSUE THREAD

**Issue by mfzhsn** [kubernetes/website#43311]
The page has example of POD, It would be nice and helpful to have a sample/example of policy, example: `single-numa-node`, How do I first create a policy and then apply to POD/worker node.

**Comment by tamilselvan1102** [comment]
Related page: https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/

**Comment by tamilselvan1102** [comment]
This may help you to create PSP in pods
https://github.com/kubernetes/examples/tree/master/staging/podsecuritypolicy/rbac

**Comment by tamilselvan1102** [comment]
PSP has been deprecated and you can use PSA instead of that
https://kubernetes.io/docs/concepts/security/pod-security-admission/

**Comment by tengqm** [comment]
@mfzhsn The enabling of the topology manager option is about configuring `kubelet` command line options or its configuration file. What do you mean by creating a policy? As far as I can tell, there is not much to be tuned/customized.
