### ISSUE TITLE
Document good practices for workloads on Kubernetes

### ISSUE THREAD

**Issue by albertsuki265** [kubernetes/website#43334]
**I was Wondering about seeing the pod usage pattern in kubernetes doc**.
I found this topic is missing in document and it will be useful for all  the reader to understand the best usage pattern of pod.
I think we need to work on it.

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/concepts/workloads/pods/_

/sig node

**Comment by kumarankit999** [comment]
Hey @thisisharrsh, are you talking about these patterns which are also on https://www.bmc.com/blogs/kubernetes-patterns/

**Comment by thisisharrsh** [comment]
> Hey @thisisharrsh, are you talking about these patterns which are also on https://www.bmc.com/blogs/kubernetes-patterns/

No actually, I believe @albertsuki265 is talking about the best practices with which one can use a pod efficiently and effectively.

**Comment by thisisharrsh** [comment]
Some of such practices can be: 

- Using deployments.
- Using ConfigMaps and Secrets. 
- Setting resources requests and limits for CPU and memory. 
- Using Pod Affinity and Anti - Affinity. 

and so on ..

**Comment by kumarankit999** [comment]
Ok

**Comment by sftim** [comment]
/retitle Document good practices for workloads on Kubernetes

My opinion: this could work well as a series of `evergreen: true` blog articles and a page that links to each entry in the series

**Comment by tengqm** [comment]
It is hard or even impractical to suggest a set of good practices regarding the management of workloads. This is a huge topic. You can treat all workload related tasks are "good practices" if you want. You can instead invent new wheels to meet your needs.
Just take the Pod abstraction itself as an example. Is it good to have Pod IPs dynamically assigned? Maybe and maybe not.

I'm gonna close this as too huge a topic. Please feel free to file an issue/suggestion that is attainable.
/close

**Comment by sftim** [comment]
As this wasn't resolved:
/close not-planned

However, I am also happy to see this work started.
