### ISSUE TITLE
Add a CI Job to check proper formatting while submitting a PR

### ISSUE THREAD

**Issue by Gauravpadam** [kubernetes/website#43335]
**This is a Feature Request**

**What would you like to be added**
We should add a CI Job to the repository to ensure that our contributors are following the formatting rules while submitting their PRs

**Why is this needed**
The merge of #43279 defines manual wrapping for ease of review and localization. The CI feature will make sure the style guide is adapted in our future PRs

**Comment by Gauravpadam** [comment]
/assign
I'll be working on this

**Comment by sftim** [comment]
Make sure to use Prow for the checks (not GitHub Actions, which as a project we avoid).

**Comment by Gauravpadam** [comment]
Thanks for the heads up, I'll keep that in mind

> Make sure to use Prow for the checks (not GitHub Actions, which as a project we avoid).

**Comment by Okabe-Junya** [comment]
Hi folks !!

Is this issue currently in progress? I'm also interested in the implementation of CI. Here are some points I'm curious about:

- Will you implement simple shellscripts, or use some tools like [markdownlint](https://github.com/DavidAnson/markdownlint)?
- Do you plan to introduce CI for all languages?
- How will you address the issue of false positives in natural language CI?
- Do you plan to include in the required status?
- Do you plan to offer it as an experimental feature?
    - For example, how about enabling a beta version for specific languages?

Regards :)

**Comment by Okabe-Junya** [comment]
I think the simple first step would be to ensure:

- Checking no unnecessary spaces at the end of lines
-  Checking **exactly** only one newline at the end of files.

I think this would be effective for all languages

**Comment by Gauravpadam** [comment]
Thanks for the insights @Okabe-Junya

I think this is one of those issues where sig-testing can help us. I'll rekindle this by reaching out on their slack channel

btw, rolling out a beta for specific languages sgtm. We can start by clearing linting checks

**Comment by Affan-7** [comment]
Are we going to use a linting tool for text? Or create one?

**Comment by Gauravpadam** [comment]
What would you suggest @Affan-7?

**Comment by stmcginnis** [comment]
I have had good luck with [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) in past projects. The tricky part will be configuring it so it helps more than hinders contributions. The default ruleset is fairly struct on markdown adherence, even the rendered output is fine. Adding that to an existing set of files would likely highlight a LOT of issues. Some will be legitimate things to fix, while others would be trivial cleanup that would be less important.

The cluster-api-provider-vmware maintains a containerized image of this that makes it very easy to perform checks:

https://github.com/vmware-tanzu/community-edition/blob/main/hack/check/check-mdlint.sh#L16

**Comment by Okabe-Junya** [comment]
> The tricky part will be configuring it so it helps more than hinders contributions

I think too. I also think we should start with the minimal configuration (meaning, we should initially have a rule set that produces almost no false positives).

How about starting with spell check and link verification, for example?

**Comment by Okabe-Junya** [comment]
[/scripts](https://github.com/kubernetes/website/tree/main/scripts) contains several excellent scripts. Running these in CI would be an easier step than introducing new tools.

(If we were to introduce a new linter, we would have to spend a lot of time discussing its rule set.)

**Comment by Affan-7** [comment]
Kubernetes have  a lot of formatting standards, you can refer [style guide](https://kubernetes.io/docs/contribute/style/style-guide/). Can we configure [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli) to implement things like linting for headings and titles and other similar things?

**Comment by Gauravpadam** [comment]
> How about starting with spell check and link verification, for example?

This sgtm. k8s/test-infra has all the ci jobs atm. If this works out, We can turn this into an umbrella issue and integrate different style guide checks.

**Comment by Okabe-Junya** [comment]
Sounds good!!

@Gauravpadam,  What about i18n? Should we initially target only English, and if it works well, then introduce it in other languages based on the decision of each localization team?

Meaning, I think what we need to do is to add a simple CI workflow file for English documentation to k/test-infra?

**Comment by Gauravpadam** [comment]
@Okabe-Junya Like you've mentioned earlier, some checks are common for all types of files, writing a workflow for them should be a quick win

For i18n specifically? alphabetical ordering checks is what we should aim for initially imo

**Comment by Okabe-Junya** [comment]
Looks good!!

Could you let me know in this issue when you open a PR to k/test-infra?
