### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-intro/

### ISSUE THREAD

**Issue by bensonz** [kubernetes/website#4334]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Website formatting issue when the width is around 768px.
Usually I wouldn't care but when I do the split view on Mac I can't read this webpage. I would assume this issue persist throughout all kubernetes' documentation website so I wanted to report this.
Here's what it looks like
<img width="742" alt="screen shot 2017-07-10 at 13 48 07" src="https://user-images.githubusercontent.com/6411481/28004318-5ef5d4da-6576-11e7-8dcf-22bb2a812018.png">

**Proposed Solution:**
None. I dont know too much about responsive websites.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/

**Comment by zacharysarah** [comment]
@BenHall 👋

**Comment by BenHall** [comment]
Thanks @zacharysarah and @bensonz

This is on my TODO list, hoping to complete it this week as it's going to require changes to the main Kubernetes.io site.

**Comment by tengqm** [comment]
Sounds like this has been fixed when responding to #3868. Feel free to reopen if the issue persists.
