### ISSUE TITLE
Error in Hello minikube tutorial

### ISSUE THREAD

**Issue by Viet2803** [kubernetes/website#43343]
# Run a test container image that includes a webserver
```
kubectl create deployment hello-node --image=registry.k8s.io/e2e-test-images/agnhost:2.39 -- /agnhost netexec --http-port=8080
```

the deployment  should be deployments

**Comment by AmarNathChary** [comment]
**_Page related to the issue_** : https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-deployment

**Comment by AmarNathChary** [comment]
![Screenshot from 2023-10-06 12-44-35](https://github.com/kubernetes/website/assets/117257033/acc2247e-a11a-4d8f-b541-1222ede10862)
It's working fine in my case.

**Comment by aj11anuj** [comment]
More information and evidence is required

/triage needs-information

**Comment by sftim** [comment]
/retitle Error in Hello minikube tutorial

I agree that there doesn't seem to be anything to fix.

**Comment by tengqm** [comment]
/close not-planned
The `kubectl` command is designed so for ease of use.
You can try `kubectl create --help` to check the examples.
Also, `kubectl create deployment` actually works.
