### ISSUE TITLE
Addition of a small "copy" button to all code snippets

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#43350]
**This is a Feature Request**

**What would you like to be added/enhanced?**
At some places in docs the code snippets are huge like this

![Screenshot (823)](https://github.com/kubernetes/website/assets/116108975/d02d6a6f-2a97-4a16-8093-4b518c14df5b)

It would be better if a small "copy" button is added to all code snippets for ease of copying code from snippets, in-case user wants to run that code on his/her/their machine. A copy button like below:-

![Screenshot (820)](https://github.com/kubernetes/website/assets/116108975/76df89af-43e8-40bc-90ca-10064e172191)
![Screenshot (821)](https://github.com/kubernetes/website/assets/116108975/3190f638-541c-4a22-9a78-8e0d7387e9ab)

**Comment by Gauravpadam** [comment]
Good suggestion!

**Comment by dipesh-rawat** [comment]
@aj11anuj We do have `{{% code_sample %}}` Hugo shortcode (_[doc reference link](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#source-code-files)_) available for embedding file contents within a code block. This enables users to easily download or copy the content to their clipboard. Does this align with your expectations for this feature request, or do you have other ideas for potential enhancements to improve the shortcode experience or its usage? 

Additionally, visit [Objects In Kubernetes](https://kubernetes.io/docs/concepts/overview/working-with-objects/#:~:text=a%20Kubernetes%20Deployment%3A-,application/deployment.yaml,-apiVersion%3A%20apps) page to see how the copy option appears when using the shortcode.

**Comment by aj11anuj** [comment]
Ok, Understood
These 'copy to clipboard' buttons can be easily added using this shortcode `{{% code_sample %}}` but still there are various snippets across the site that contain code that user may want to use and still there, this shortcode isn't used yet like [this page](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/) and there are many more like this.

Can this issue be used to add this shortcode to necessary snippets across docs pages?

**Comment by tengqm** [comment]
Yup. For snippets that are intended for users to try out, especially those in a task page or a tutorial page, wrapping them with the `code_sample` shortcode is desirable.
We are not adding a "copy" button to all code snippets because not all of them are supposed to be tried out by the users.
/close not-planned
