### ISSUE TITLE
在 Linux 系统中安装并设置 kubectl

### ISSUE THREAD

**Issue by Geapefurit** [kubernetes/website#43366]
https://kubernetes.io/zh-cn/docs/tasks/tools/install-kubectl-linux/ 安装Kubectl步骤中 用 curl 在 Linux 系统中安装 kubectl  第一步的命令错误

**Comment by aj11anuj** [comment]
/sig docs 
/language zh
/kind bug

Consider renaming title as `[zh] Bug in Set up kubectl on Linux docs`

And renaming description as `https://kubernetes.io/zh-cn/docs/tasks/tools/install-kubectl-linux/ In the step of installing Kubectl, use curl to install kubectl in Linux system. The command error in the first step`

**Comment by utkarsh-singh1** [comment]
Hi @Geapefurit, If you are taliking about first step to download kubectl binary using curl it is working fine for me.

**Comment by utkarsh-singh1** [comment]
@Geapefurit, In case you are facing any issues regarding installation you can paste screenshot of the error or use markdown code format to paste the error here.

**Comment by tengqm** [comment]
I'm afraid the download command fails due to network connection issue.

**Comment by Geapefurit** [comment]
> @Geapefurit, In case you are facing any issues regarding installation you can paste screenshot of the error or use markdown code format to paste the error here.

Just little issue

![image](https://github.com/kubernetes/website/assets/25075249/90000cb1-34f9-45ba-a701-b4650780fd52)

**Comment by utkarsh-singh1** [comment]
@Geapefurit, this issue does not seem to be on English version.

**Comment by Geapefurit** [comment]
> @Geapefurit, this issue does not seem to be on English version.

yes

**Comment by utkarsh-singh1** [comment]
Hi @Geapefurit, it would be better to update the current 'zh-cn' doc, you could assign this issue yourself and update the docs, As there is already another method to check and download the kubectl binary is already there.

**Comment by tengqm** [comment]
/triage accepted
/kind bug
Looks like a localization typo.

**Comment by mengjiao-liu** [comment]
The issue has been resolved by https://github.com/kubernetes/website/pull/43543.
/close
