### ISSUE TITLE
[zh] kubeconfig not localized

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#43360]
File `content/en/docs/reference/config-api/kubeconfig.v1.md` not yet localized to zh-cn.

**Comment by surajyadav1108** [comment]
can I take up this?

**Comment by tengqm** [comment]
@surajyadav1108 Surely you can do it if you can write Chinese and you are familiar with the [Chinese localization guideline](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87). All you need to do is to leave a `/assign` comment.

**Comment by surajyadav1108** [comment]
Thanks for providing the guide. @tengqm I understand that ideally, knowing the language itself would be the best approach. However, I'm considering using translation tools, not just one but two or three different platforms. This way, I can cross-check the translations they provide and use the existing translated pages as templates for guidelines. Then, the review team can assess whether the translations meet the required standards. what do you think?

**Comment by tengqm** [comment]
@surajyadav1108 Okay, let's see how useful the translation tool is. :)

**Comment by surajyadav1108** [comment]
ok I'm nervous now🥲

**Comment by surajyadav1108** [comment]
@tengqm Up for review💀

**Comment by aj11anuj** [comment]
Fixed by #43475 and #43858 was kind of a cleanup PR
/close
