### ISSUE TITLE
Learn Kubernetes Basics button difficult to read when hovered

### ISSUE THREAD

**Issue by Sakhi29** [kubernetes/website#43396]
**This is a Bug Report**

**Problem:** On the home page of website I found that the Learn Kubernetes Basics button needs to be edited as when we hover upon it the words are not clearly visible.

**Proposed Solution:** We can make this button same as the buttons in other pages of the website like for example, under the documentation tab we have View Concepts and View Tutorial buttons.

**Page to Update:**
https://kubernetes.io/

I would like to work upon this issue if you assign it to me. Thankyou.

**Comment by thisisharrsh** [comment]
Hi @Sakhi29, Thank you for raising this issue. You can assign this issue to yourself by commenting `'assign'` tag.

**Comment by sftim** [comment]
/retitle Learn Kubernetes Basics button difficult to read when hovered

**Comment by sftim** [comment]
/triage accepted
/priority important-longterm

Fixes are welcome.

**Comment by Chaitra-Shetty** [comment]
> /retitle Learn Kubernetes Basics button difficult to read when hovered

I have a few options for the title: 

1. "Getting Started with Kubernetes Basics"
2. "Exploring the Fundamentals of Kubernetes"
3. "K8s Fundamentals"

Please review these suggestions. Thanks

**Comment by thisisharrsh** [comment]
Hi @Chaitra-Shetty, The title seems interesting; we can use 'Exploring the Fundamentals of Kubernetes' as the new title.

**Comment by thisisharrsh** [comment]
Waiting for suggestions from other members.

**Comment by Gauravpadam** [comment]
'Learn Kubernetes Basics' is simple and conveys the correct message as is imo

**Comment by sftim** [comment]
Let's leave the text as is, and fix the poor color contrast that happens when someone hovers over the button.

**Comment by Chaitra-Shetty** [comment]
> Hi @Chaitra-Shetty, The title seems interesting; we can use 'Exploring the Fundamentals of Kubernetes' as the new title.

@thisisharrsh Thank you

**Comment by Gauravpadam** [comment]
**Untested, But a probable alternate fix**

Try modifying layouts/index.md to wrap the `<a>` with a `<button>` like:

`<a href="{{ .RelPermalink }}"><button id="quickstartButton" class="button">{{ .LinkTitle }}</button></a>`

css changes would not be necessary

**Comment by Gauravpadam** [comment]
It's been a month since this is waiting, Would any contributor like a take on this?
(I think this can be a _good first issue_)

**Comment by sftim** [comment]
Just one thing; it's handy to cover even older issues that we're prioritizing too. See https://github.com/orgs/kubernetes/projects/150
