### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

### ISSUE THREAD

**Issue by derynL** [kubernetes/website#43391]
The following statement is very clear: 

> Control Planes manage the cluster and the nodes that are used to host the running application.

However, the subsequent paragraph really muddies the water:

> A Kubernetes cluster that handles production traffic should have a minimum of three nodes because if one node goes down, both an [etcd](https://kubernetes.io/docs/concepts/overview/components/#etcd) member and a control plane instance are lost, and redundancy is compromised. You can mitigate this risk by adding more **control plane nodes**.

Are control planes also nodes? The initial statement seems to imply that they are distinct from nodes. For someone like myself, who is very new to the world of deployment, the language in these docs assumes an existing understanding of the subject that makes them somewhat inaccessible.

**Comment by utkarsh-singh1** [comment]
@derynL, Yes control plane is also a node - https://kubernetes.io/docs/concepts/overview/components/

**Comment by utkarsh-singh1** [comment]
tutorials are more practical or hands-on approach to learn kubernetes but it would be best  if you can spend some time in concepts section - https://kubernetes.io/docs/concepts/. Concepts will help you to understand k8s components, objects and resources.
