### ISSUE TITLE
Pod Topology Spread Constraints

### ISSUE THREAD

**Issue by majid-akbari** [kubernetes/website#43406]
The `topologySpreadConstraints` is not working without using `labelSelector` but it isn't mentioned in the documentation.

**Comment by tamilselvan1102** [comment]
related page: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Comment by tamilselvan1102** [comment]
it is not mentioned in the doc. it has to be written clearly

**Comment by kumarankit999** [comment]
I think If it is accepted then I can work on it.

**Comment by tengqm** [comment]
According to the API documentation, `labelSelectors` and `matchLabelKeys` are both optional.
If you have doubts about this, raise your question to the SIG scheduling group.
/kind support
/remove-kind bug

**Comment by majid-akbari** [comment]
I opened a new [issue](https://github.com/kubernetes/community/issues/7580) there.

**Comment by aj11anuj** [comment]
> I opened a new [issue](https://github.com/kubernetes/community/issues/7580) there.

Hello @majid-akbari, I hope your query is resolved if not then reach out to appropriate [Kubernetes slack](https://communityinviter.com/apps/kubernetes/community) channel or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum for faster resolution as suggested in https://github.com/kubernetes/community/issues/7580 too.

/close not-planned
