### ISSUE TITLE
Set up Ingress on Minikube with the NGINX Ingress Controller

### ISSUE THREAD

**Issue by keeswie** [kubernetes/website#43412]
Hello,

I am doing the tutorial exactly as the tutorial describes. However I am stuck on step 4 of the section "Create an Ingress". 
"kubectl get ingress" returns : 
NAME              CLASS   HOSTS              ADDRESS        PORTS   AGE
example-ingress   nginx   hello-world.info   192.168.49.2   80      5m48s

Which from what I understand is what is expected.
but when I run step 4 nothing happens.

Thanks in advance for the help.

Im running minikube in a container on docker desktop on a laptop running ubuntu

**Comment by thisisharrsh** [comment]
Hi @keeswie, make sure that you have installed the correct version of the kubernetes.

**Comment by thisisharrsh** [comment]
Also, you can check for logs for errors and can try restarting your minikube cluster

**Comment by thisisharrsh** [comment]
GitHub is not the right place for support requests.

For further help, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by thisisharrsh** [comment]
You can also visit [this](https://github.com/kubernetes/website/issues/43060) issue.

**Comment by thisisharrsh** [comment]
If the issue is resolved now you can close this issue.
