### ISSUE TITLE
Page layout for "Install and Set Up kubectl on Linux" is broken

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#43431]
**This is a Bug Report**

**Problem:**
[Install and Set Up kubectl on Linux] page layout is collapsed.
Right side layout is displaced to down.

**Proposed Solution:**
Right side layout should be in place.

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-binary-with-curl-on-linux

Additional Information:
![image](https://github.com/kubernetes/website/assets/20103020/21c63d0a-7f99-4a26-aaf0-f5d82216b816)

**Comment by steve-hardman** [comment]
@dipesh-rawat (or any maintainers) Can i get some hint and go ahead to work on this please?

**Comment by dipesh-rawat** [comment]
It appears that the changes in https://github.com/kubernetes/website/pull/42913 have inadvertently resulted in the layout of page broken. Potentially addressing https://github.com/kubernetes/website/pull/42913#discussion_r1336990733 could solve it.

**Comment by dipesh-rawat** [comment]
We should fix the layout of the page.
/triage accepted
/priority backlog

**Comment by dipesh-rawat** [comment]
/retitle Page layout for "Install and Set Up kubectl on Linux" is broken

**Comment by sftim** [comment]
/remove-area web-development

This is more of a content fix.
