### ISSUE TITLE
Rename “cheat sheet” page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#43433]
**This is a Feature Request**

**What would you like to be added**
- Find a new title and URL for https://kubernetes.io/docs/reference/kubectl/cheatsheet/
- Redirect https://kubernetes.io/docs/reference/kubectl/cheatsheet/ to the new page
- Optionally set up a new short URL, [https://k8s.io/_somethingshort_](https://k8s.io/somethingshort), that also redirects to the new page

**Why is this needed**
The “kubectl cheat sheet” page has an unfortunate name, in that we now have actual exams where cheating is unacceptable and prohibited.

**Comments**
Some contributors suggest cheat sheet changes that feel a bit close to what the CNCF doesn't want to see in the exam (that is: help with specific exam questions).

**Comment by sftim** [comment]
/priority backlog
(or lower)

**Comment by steve-hardman** [comment]
Let me try to help with this.

/assign

**Comment by able8** [comment]
How about rename **kubectl Cheat Sheet** to **kubectl Quick Reference** or **kubectl Quick Guide**?
<img width="1009" alt="Screenshot 2023-10-15 at 00 41 22" src="https://github.com/kubernetes/website/assets/26692080/01a8b13d-041a-4532-8f85-a29fb698f703">

**Comment by aakashdeshamne** [comment]
@mengjiao-liu please review the PR #43611
