### ISSUE TITLE
Poor contrast / other aesthetic concerns for example in Kubernetes API Concepts

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#43449]
There are many Examples in [Kubernetes API Concepts](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) are very dull in color merging with its background and have a different appearance in some examples such as
[Image](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) 1
![Screenshot from 2023-10-12 10-46-24](https://github.com/kubernetes/website/assets/117257033/6e3fb30b-695f-41f5-8cd7-b6a6f1489545)
[Image](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) 2
![Screenshot from 2023-10-12 10-54-16](https://github.com/kubernetes/website/assets/117257033/239d72f7-4c05-42b9-9bf3-306a9bbdbc25)
[Image](https://kubernetes.io/docs/reference/using-api/api-concepts/#collections) 3
![Screenshot from 2023-10-12 10-54-33](https://github.com/kubernetes/website/assets/117257033/470f539b-1e67-4e28-8263-b78160dad6d5)
**Proposed solution**
Can be updated with dark black color like Image 2 or can be more colorful as Image 3

**Comment by AmarNathChary** [comment]
I will fix this
/assign

**Comment by sftim** [comment]
/retitle Poor contrast / other aesthetic concerns for example in Kubernetes API Concepts

**Comment by AmarNathChary** [comment]
switched the JSON file format, and now it comes with user-friendly colors for better comprehension.

**Comment by tengqm** [comment]
No. The coloring only applies to part of the text. When we have both HTTP response and the JSON payload, the JSON payload or YAML are not supposed to be rendered with colors. There is no parser intelligent enough to do this.
/close

**Comment by sftim** [comment]
/close not-planned

FWIW, I think the poor contrast is an accessibility issue. The fix in https://github.com/kubernetes/website/pull/43470 might not be right for the page but accessibility is important.

We can reopen this if as a SIG we decide that we should.

**Comment by AmarNathChary** [comment]
can we change the closed as completed as PR #43470 got merged after a proper fix
