### ISSUE TITLE
[es] localize content/en/docs/concepts/storage/ephemeral-volumes.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#43482]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/concepts/storage/ephemeral-volumes.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs

**Comment by ramrodo** [comment]
@edithturn could you add a comment here to assign this to you, please?

**Comment by edithturn** [comment]
Hello @ramrodo, I would love to translate this page! 💃🏼

**Comment by vinayakg04** [comment]
Hello @ramrodo , I have already localized the file to Spanish, Can you Please assign me this issue?

**Comment by ramrodo** [comment]
Since this issue was initially created to be assigned to @edithturn, I'll give this to her.

@vinayakg04 Thanks for participating in the Kubernetes Website project. The Spanish translation team would like to help you with your contribution, so please share your goals and skills in order to help you better. We also encourage new contributors to participate in their native speaking language.
