### ISSUE TITLE
Missing information on Website's [hi] homepage

### ISSUE THREAD

**Issue by Gauravpadam** [kubernetes/website#43498]
**This is a Feature Request**

**What would you like to be added**
- [ ] Add 'Kubernetes Features' to hi homepage
- [ ] Add 'Case Studies' to hi homepage : https://github.com/kubernetes/website/pull/43516

**Why is this needed**
The localization is incomplete, And It's the index page as well, It should be completed ideally

![image](https://github.com/kubernetes/website/assets/12787482/adc49f6a-1054-4b05-99f3-343de5357f1b)

**Comment by surajyadav1108** [comment]
content blocks for these two section are empty for the english file too. where is the content coming from?

**Comment by kundan2707** [comment]
@Gauravpadam  Can you share link of page which you are talking about?

**Comment by Gauravpadam** [comment]
@kundan2707 We're referring to the [hi] homepage: https://kubernetes.io/hi/

**Comment by kundan2707** [comment]
@Gauravpadam  [hi] homepage is just translation of [en] homepage so its correct. information those you are requesting are already available at other suitable place.

**Comment by surajyadav1108** [comment]
@kundan2707 hindi homepage has missing content for kubernetes-features and case studies the content for those actually coming from layouts/shortcodes/blocks  working as a template  for the en So if you want to add these sections in hindi page 
then look for the content/hi/docs/concepts/ folder you have to find and translate files related to these two sections as they are present in content/en/docs/concepts  as I can gusess

**Comment by Gauravpadam** [comment]
/area localization
@surajyadav1108 Almost there. It actually looks for all the pages and tries to find a feature parameter from the front matter.
This becomes a localization request then. My apologies for not making it obvious.

My suggestion?
hi localization misses some pages where front matter contains feature parameters. We must identify those pages and at least localize the front matter fields (de language does the same thing) for the homepage to render features normally.

Similarly we should do it for case studies, Treat this as an umbrella issue

**Comment by Gauravpadam** [comment]
See commit https://github.com/kubernetes/website/commit/bd49796a8fbd5b3e8f0eff5d90cbe10654a158cd

**Comment by Gauravpadam** [comment]
That's correct! It's better to wait for triage though
> hmm so for the time being we just need to add front page fields as the whole page translation would be bigger issue

**Comment by anjum-edge** [comment]
Add the content on the homepage first paragragh due to less content it is looking irrelevent

**Comment by kumarankit999** [comment]
Is there any working on this Issue??
