### ISSUE TITLE
Cheat Sheet example code snippet returns error

### ISSUE THREAD

**Issue by blaisep** [kubernetes/website#43492]
**This is a Bug Report**

**Problem:**
Has anyone else run into this error when using the example from the cheat sheet (https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-and-finding-resources)

```shell
$ kubectl get events -o json | jq -c 'paths|join(".")'
"apiVersion"
"items"
jq: error (at <stdin>:454): string (".") and number (0) cannot be added
```
I've tried several permutations of commands and of the ` join()..` filter and often get this error at the end:
`jq: error (at <stdin>:454): string (".") and number (0) cannot be added

I wonder if the API has changed and the cheat sheet needs updating?
**Proposed Solution:**

I heard from Tim Bannister (@sftim ), who suggested:

> There are two events APIs. The cheat sheet would be better off specifying explicitly which stable events API is meant

**Page to Update:**

https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-and-finding-resources

**Comment by kumarankit999** [comment]
How is this code 
kubectl get events -o json | jq -c 'paths | select(all(.[]; type == "string")) | join(".")'

**Comment by kumarankit999** [comment]
Should I work on this

**Comment by sftim** [comment]
I don't see a snippet
> ```
> kubectl get events -o json | jq -c 'paths|join(".")'
> ```

in https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-and-finding-resources

`kubectl get events.events.k8s.io -o json | jq -c 'paths|join(".")'` might help. It depends what you people to achieve.

/priority awaiting-more-evidence
/triage needs-information

**Comment by blaisep** [comment]
oh my, now I can't seem to repro and notes are unclear.
I suppose we can close this because it may have been a problem on my cluster.
