### ISSUE TITLE
Getting 'imagepull backoff' error despite adding imagePullSecrets

### ISSUE THREAD

**Issue by NNUTAN07** [kubernetes/website#43509]
Even after adding imagepullSecrets i am getting the imagepull backoff error .it is not even making use of secrets

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Getting 'imagepull backoff' error despite adding imagePullSecrets

**Comment by dipesh-rawat** [comment]
(Looks like a support request)
/kind support

**Comment by niranjandarshann** [comment]
@NNUTAN07 : GitHub is not the right place for support requests.

For further help, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by anjum-edge** [comment]
there are some bugs in the imagepullsecrets file so that it is not capable of not having error...
lookout for the deployment

**Comment by niranjandarshann** [comment]
Rotten issues close after 30d of inactivity.
Reopen the issue with /reopen
Mark the issue as fresh with /remove-lifecycle rotten
