### ISSUE TITLE
Duplicate content in ”Managing Service Accounts“

### ISSUE THREAD

**Issue by yeqiugt** [kubernetes/website#43504]
The contents of "https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume " are at “https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#tokenrequest-api ” appears again, should we remove the duplicates?

**Comment by kundan2707** [comment]
@yeqiugt  both links  those you mentioned are same so content is also same.

**Comment by yeqiugt** [comment]
> @yeqiugt both links those you mentioned are same so content is also same.

Sorry, I update the link.

**Comment by whitebeard10** [comment]
@yeqiugt those link you mentioned are same link/page,  but for different topic as suggested by 
[#bound-service-account-token-volume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume)
and 
[#tokenrequest-api](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#tokenrequest-api)

**Comment by yeqiugt** [comment]
> @yeqiugt those link you mentioned are same link/page, but for different topic as suggested by [#bound-service-account-token-volume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume) and [#tokenrequest-api](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#tokenrequest-api)

I know, but maybe we can merge them?

**Comment by whitebeard10** [comment]
no need to merge them i guess, it makes it easy to view page without scrolling down every time to the intended content.

**Comment by yeqiugt** [comment]
Fine.
