### ISSUE TITLE
Mermaid diagram fails to render on "Pod Topology Spread Constraints" page

### ISSUE THREAD

**Issue by Nox-404** [kubernetes/website#43508]
Hello,
All graphs are showing "Syntax error in graph" on the following page:
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Comment by dipesh-rawat** [comment]
Looks similar to few issues we already have https://github.com/kubernetes/website/issues/31960 https://github.com/kubernetes/website/issues/37357

/triage duplicate

**Comment by utkarsh-singh1** [comment]
This issue seems to be a duplicate of many other mermaid JS related issues  - like above-mentioned. Also, it seems like the issue is already over 1 month.

**Comment by utkarsh-singh1** [comment]
If you have any other issues or any practice that seems to cause this problem, you can report to the original issue thread #31960.

**Comment by sftim** [comment]
Let's track the original - and still relevant - issue.

/close not-planned
