### ISSUE TITLE
Interaktywny samouczek - Tworzenie klastra

### ISSUE THREAD

**Issue by PLchochliman** [kubernetes/website#43517]
on chrome, on windows 11, "windows is still to small" despite being full screen on 1920x1080....
Due to that self learner does not work showing communicate windows is too narrow use desktop/tablet version.

**Comment by niranjandarshann** [comment]
@PLchochliman  Please write suitable Title for the issue in english.

**Comment by niranjandarshann** [comment]
It will be good to use different browser or you can check windows 11 Display setting. 
Check your zoom level. Sometimes, websites may not work properly if you have an unusual zoom level set. 
I think this will help you .

**Comment by PLchochliman** [comment]
Zoom level is 100%
Cannon use different browser on this PC


wt., 17 paź 2023, 09:49 użytkownik Niranjan Darshan <
***@***.***> napisał:

**Comment by sftim** [comment]
Hi.

What's the URL of the web page that doesn't look right?

**Comment by sftim** [comment]
I have a feeling that the Polish localization is out of date with respect to English and this may be a page that no longer exists in the English docs.

**Comment by PLchochliman** [comment]
URL:
https://kubernetes.io/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

wt., 17 paź 2023 o 17:16 Tim Bannister ***@***.***>
napisał(a):

**Comment by T-Lakshmi** [comment]
@PLchochliman, @sftim,

> I have a feeling that the Polish localization is out of date with respect to English and this may be a page that no longer exists in the English docs.
URL:
https://kubernetes.io/pl/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

I have verified this url and @sftim assumption is correct here. This page is related to katakoda tutorial session which is no longer exit and polish localization is not in sync with english localization.

**Comment by PLchochliman** [comment]
ok thanks, have a nice day :-)

czw., 23 lis 2023 o 10:40 lakshmi prasuna ***@***.***>
napisał(a):

**Comment by aj11anuj** [comment]
Issue doesn't need a fix but rather PO localization needs to sync with original site as the page doesn't exist, and you can change the localization of page easily through an option at top right corner.

/close
