### ISSUE TITLE
Intermittent failure of kubectl wait command

### ISSUE THREAD

**Issue by mallikkml** [kubernetes/website#43558]
Lately observing following issue with kubectl wait command intermittently.

_STDOUT: pod/kmldsm-677f84b8fd-cpvfw condition met
ERROR: Error from server (NotFound): pods "kmldsm-8859fd9cc-tfcf9" not found_

Here **kmldsm-8859fd9cc-tfcf9** is the earlier pod which got terminated due to a update in deployment.

Why is kubectl wait trying to access the terminated pod?

K8s version: 1.27.x and 1.28.0

**Comment by anjum-edge** [comment]
deployment update is not possible without having the access

**Comment by sftim** [comment]
This sounds like a support request. I / we believe that the documentation for `kubectl wait` is accurate.

/kind support

@mallikkml can you clarify?

**Comment by sftim** [comment]
If you'd like to file a bug against the `kubectl` command, visit https://github.com/kubernetes/kubectl/issues/new/choose

This repository is only about the documentation, not the kubectl tool itself.
