### ISSUE TITLE
Feature Request: Gateway API Documentation

### ISSUE THREAD

**Issue by robscott** [kubernetes/website#43567]
**This is a Feature Request**

**What would you like to be added**
High level documentation for Gateway API with links out to https://gateway-api.sigs.k8s.io/. This should include the following:

1. A new "Gateway API" page between Service and Ingress in https://kubernetes.io/docs/concepts/services-networking/. This should provide a high level overview of Gateway API, with a focus on content that is unlikely to become stale. This can likely take some content from both https://gateway-api.sigs.k8s.io/ and https://gateway-api.sigs.k8s.io/guides/migrating-from-ingress/ and would help increase the discoverability of Gateway API.
2. Update the "Ingress" page to note that the API is effectively frozen and all new features are being added to Gateway API (with a corresponding link to the page added by 1).
3. Update the section on the "Service" page that references Ingress and Gateway API to give more prominence to Gateway API.

**Why is this needed**
With the upcoming graduation of Gateway API to GA (x-ref https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.0.0-rc1), it's past time to cover it in Kubernetes docs.

**Comments**
I'd previously talked with @sftim about this at a high level, but definitely let me know if you've got any suggestions for how we can scope/adjust this differently.

/sig network
/assign @danehans

**Comment by anjum-edge** [comment]
checkout the API in the section

**Comment by sftim** [comment]
How about adding a short link eg https://k8s.io/gateway-api that redirects (302) to https://gateway-api.sigs.k8s.io/#what-is-the-gateway-api ?

**Comment by sftim** [comment]
> A new "Gateway API" page between Service and Ingress in https://kubernetes.io/docs/concepts/services-networking/. 

I'd put Service, Ingress, then Gateway - and leave it in that order until most new clusters include Gateway as an add-on.

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/28060
