### ISSUE TITLE
Clarify the relationship between StatefulSet and headless Service

### ISSUE THREAD

**Issue by SHaiderAS** [kubernetes/website#43580]
**This is a Feature Request**

**What would you like to be added**

I encountered an unexpected behavior while deploying a StatefulSet in Kubernetes. According to the Kubernetes documentation, it is explicitly stated that a headless service must exist before the StatefulSet and is responsible for the network identity of the set.

However, I deployed PostgreSQL using a StatefulSet without creating any service initially, specifying the option serviceName: "postgresql-svc" in the configuration. To my surprise, there were no errors during the StatefulSet creation process. Later, I created a service named postgresql-primary and connected it to the first pod (pod 0) of the StatefulSet. Changes made to the database were reflected in the secondary pods, which is contrary to the conventional practices mentioned in the documentation.
**Why is this needed**
I'm reporting this issue to seek clarification. Is it indeed necessary to create a headless service before deploying a StatefulSet, or is there a specific scenario where this requirement doesn't apply? I'm curious if others have experienced similar situations and how this behavior aligns with Kubernetes best practices.

**Comments**

**Comment by dipesh-rawat** [comment]
/retitle Seeking clarification regarding the relationship between StatefulSet and Headless Service

**Comment by sftim** [comment]
/retitle Clarify the relationship between StatefulSet and headless Service
