### ISSUE TITLE
Website footer is too short make it big

### ISSUE THREAD

**Issue by anjum-edge** [kubernetes/website#43582]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by dipesh-rawat** [comment]
@anjum-edge Is the footer dimension small, or is it the content within the footer that appears compact? Could you kindly provide additional information about the [issue](https://github.com/kubernetes/website/issues/43582#issue-1951986723), and if possible, include some screenshots to enhance the clarity of the problem.

/triage needs-information

**Comment by sftim** [comment]
/priority awaiting-more-evidence
/area web-development

A reviewer or approver may close this issue if more evidence isn't added

If closing, please close it with `/close not-planned`.

**Comment by PranitRout07** [comment]
I think, the font size of the lines should be increased for better readability.
<img width="1272" alt="Screenshot 2023-10-26 065432" src="https://github.com/kubernetes/website/assets/102309095/d86e80e6-8534-44c0-9861-d44cdc6109ed">

**Comment by sftim** [comment]
@PranitRout07 you are very welcome to file a feature request about the type size in the footer - https://github.com/kubernetes/website/issues/new/choose

(this issue is not a good place to mention that you think it's a bit small)

**Comment by sftim** [comment]
/close not-planned

There doesn't seem to be enough information to triage the issue. Without knowing if there is anything to fix, we can't accept it as needing work.
