### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by dimamciz** [kubernetes/website#4358]
dropping connection every 15 seconds, making the tutorial unusable...

"
Sorry, we hit a problem with the connection.
Your internet connection may have dropped.

Please refresh and try again.
"

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Sorry you encountered an issue. Is this still happening?  If so, could you please tell me your browser and OS?

Also, are you behind any kind of proxy?

**Comment by dimamciz** [comment]
Hi Ben
Thanks for your prompt reply. To answer your questions:

   
   - I am using a company owned laptop but I disabled the company proxy while running the tutorials. And also enabled it... both times with same results.   

   - My OS is W7 Enterprise.   

   - My browser is Chrome Version 59.0.3071.115 (Official Build) (64-bit)   

   - Also tried with my IE, but not that much as the virtual terminal wasn't even displayed...   

   - Last but not least, I tried restarting with Safe+Networking and it didn't drop once. So there is something going on my side, but I am not sure what...   


Any ideas?
Diego 

    On Thursday, July 13, 2017 7:42 AM, Ben Hall <notifications@github.com> wrote:
 

 Sorry you encountered an issue. Is this still happening? If so, could you please tell me your browser and OS?Also, are you behind any kind of proxy?—

**Comment by BenHall** [comment]
I believe we've released a fix for this. Could you please retest @dimamciz ? It would be great to know if it solved your problem.

**Comment by dimamciz** [comment]
Hi Ben
I think I finally found what the issue is/was. McAfee Host Intrusion Prevention (HIPS) services was causing the connection resets. I stopped 2 related services and so far it seems to be working fine...
Thanks
Diego Mamciz 

    On Sunday, July 23, 2017 7:26 PM, Ben Hall <notifications@github.com> wrote:
 

 I believe we've released a fix for this. Could you please retest @dimamciz ? It would be great to know if it solved your problem.—

**Comment by BenHall** [comment]
Thanks for the update. I'm not sure why McAfee Host Intrusion Prevention would cause websockets to fail. I'll keep an eye out for fixes.
