### ISSUE TITLE
Unable to install kubectl on SUSE Linux due to Signature verification error

### ISSUE THREAD

**Issue by OrphericYeou** [kubernetes/website#43603]
I tried to install kubectl on linux Suse, but I'm getting this error while installation proccess.

![Capture d'écran 2023-10-20 112146](https://github.com/kubernetes/website/assets/52802033/bcb060c3-3656-40cc-b334-95218219d83c)

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/_

**Comment by thisisharrsh** [comment]
Hi @OrphericYeou, GitHub is not the right place for support requests.

For further help, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by dipesh-rawat** [comment]
/retitle Unable to install kubectl on SUSE Linux due to Signature verification error

**Comment by sftim** [comment]
/remove-kind support

How do we know this is not a bug?

**Comment by sftim** [comment]
/kind bug
I think it was a bug.

@OrphericYeou have the symptoms disappeared?
