### ISSUE TITLE
Init Containers - to add some brief details related to new sidecar containers feature at the top

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#43610]
In current [Difference from regular containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#differences-from-regular-containers) subsection it is said:

> Also, init containers do not support lifecycle, livenessProbe, readinessProbe, or startupProbe because they must run to completion before the Pod can be ready.

This is true for all "normal" initContainers but not for those new ones where the new (defined at initContainer level) ``restartPolicy`` field is being set to ``Always`` (in case ``SidecarContainers`` feature gate being enabled, of course).

All this is properly described in new (from k8s 1.28) [API for sidecar containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#api-for-sidecar-containers) subsection but I think it would be good to add a brief note (plus reference to the new feature) on this in that paragraph, something like this:

> Also, init containers do not support lifecycle, livenessProbe, readinessProbe, or startupProbe because they must run to completion before the Pod can be ready (expect when setting a restartPolicy for an init container, see [API for sidecar containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#api-for-sidecar-containers))

And so a reader looking for this info can find it at the top of the Init Containers doc page.
Note this proposed addition (or an equivalent one) would remain the same when this feature reaching beta and finally GA/stable.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
/language en

**Comment by sftim** [comment]
We'll update the alpha documentation for the graduation to beta.

/sig node

**Comment by vinayakg04** [comment]
Hii, @antaloala I would like to work on this issue, may you please assign me this one?

**Comment by T-Lakshmi** [comment]
@sftim,
Is there anything still needs to fix in this issue?
I believe this issue is already covered in PRs #43346  and #44800
