### ISSUE TITLE
Stale info in "Communicating with Daemon Pods"?

### ISSUE THREAD

**Issue by spencerwilson** [kubernetes/website#43612]
The section reads (emphasis mine):
> Service: Create a service with the same Pod selector, and use the service to reach a daemon on a random node. **(No way to reach specific node.)**

Is that still accurate in light of `internalTrafficPolicy: Local` support for Services? Or should this section be updated to refer the reader to this page: https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/?

References:
- GA announcement in 1.26: https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/#optimizing-internal-node-local-traffic
- KEP-2086: https://github.com/kubernetes/enhancements/blob/19975acc58108232fc447bb9ef5ec7ba4702c319/keps/sig-network/2086-service-internal-traffic-policy/README.md

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
/language en
