### ISSUE TITLE
Kubelet Configuration (v1beta1)/Conflicting Docs

### ISSUE THREAD

**Issue by vesnikos** [kubernetes/website#43627]
![image](https://github.com/kubernetes/website/assets/6684178/9aade022-ef34-415e-8ec8-5d69ff9f05df)
`source: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration`

But

![image](https://github.com/kubernetes/website/assets/6684178/202a7b2d-e333-4b54-a210-fe166360ab17)
`source: https://kubernetes.io/docs/setup/production-environment/container-runtimes/#systemd-cgroup-driver`

**Comment by tengqm** [comment]
kubelet and kubeadm are two different things.

**Comment by neolit123** [comment]
> kubelet and kubeadm are two different things.

yes, the ecosystem is shifting towards the systemd driver. the kubelet default can be considered "legacy".

/kind support
/close

**Comment by vesnikos** [comment]
I see,
thanks for the explanation, i was source of confusion then from my part.
n

________________________________________
