### ISSUE TITLE
Failed to load "The kubernetes.io analytics dashboard"

### ISSUE THREAD

**Issue by able8** [kubernetes/website#43639]
It shows:
```
Data Set Configuration Error
Looker Studio cannot connect to your data set.
```

```
Looker Studio cannot connect to your data set.
The data source no longer has access to the underlying data set. Please contact the data source owner to fix it.
Error ID: 25c1890c
```

<img width="1750" alt="Screenshot 2023-10-22 at 20 33 38" src="https://github.com/kubernetes/website/assets/26692080/bd5d7d31-6299-4ac5-a8c1-e2d2be1b8004">

URL: https://lookerstudio.google.com/reporting/fede2672-b2fd-402a-91d2-7473bdb10f04/page/567IC

From: https://kubernetes.io/docs/contribute/analytics/

**Comment by dipesh-rawat** [comment]
We've already got this reported as part of issue https://github.com/kubernetes/website/issues/43281, so it seems like a duplicate.

/triage duplicate

**Comment by able8** [comment]
Oh, thanks. 
closing

/close
