### ISSUE TITLE
Bump Hugo version

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#43671]
**This is a Feature Request**

**What would you like to be added**
Update Hugo to [v0.119.0](https://github.com/gohugoio/hugo/releases/tag/v0.119.0) (or later), by editing `netlify.toml`

*Update 2024-01-01:* v0.121.1 would be ideal.

**Why is this needed**
There are some security fixes for Go that we might want to pull in.

**Comments**
/sig security
/sig docs

**Comment by Gauravpadam** [comment]
/assign
I'd like to help with this

**Comment by Gauravpadam** [comment]
I think just editing the `netlify.toml` won't work, Would need to update some images or makefile as well?

**Comment by sftim** [comment]
> I think just editing the `netlify.toml` won't work, Would need to update some images or makefile as well?

We use ~magic~ technology so that the one edit is all you need to do.

**Comment by sftim** [comment]
To test it locally, edit the configuration and then run:
```shell
make container-image
make container-serve
```

**Comment by Gauravpadam** [comment]
Alright sounds good, I'll do the needful
