### ISSUE TITLE
docs : Yellow color in diagram not visible clearly on white background; needs to be darker

### ISSUE THREAD

**Issue by PranitRout07** [kubernetes/website#43711]
**ISSUE DETAILS**
Dotted lines are yellow color, these dotted lines are not clearly visible in the diagrams. I think darker color (like dark purple) would be better combination on the white color.
 
See the issue at these links : 

https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/
https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/

<img width="520" alt="Screenshot 2023-10-27 152210" src="https://github.com/kubernetes/website/assets/102309095/351d23a8-0479-460a-998a-1f36c3882ef0">

**Comment by Gauravpadam** [comment]
`kubernetes grey` for the dotted lines would be good for accessibility

Using draw.io or excalidraw would be good imo

**Comment by PranitRout07** [comment]
Hey @Gauravpadam rather than using draw.io or excalidraw , I would suggest to change the hex color code in .svg images .

**Comment by Gauravpadam** [comment]
Sure, Any kind of fix is welcome

**Comment by sftim** [comment]
Not really a web dev thing though; this is content that needs fixing. We don't (yet) have an **area** for figures & illustrations.

/remove-area web-development

**Comment by Gauravpadam** [comment]
Closing as completed via https://github.com/kubernetes/website/pull/43719

/close
