### ISSUE TITLE
x509: certificate has expired or is not yet valid: current time

### ISSUE THREAD

**Issue by holidayFeng** [kubernetes/website#43713]
根据 https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/ 提供的方案，执行了以下步骤
1.检查证书时间：`kubeadm certs check-expiration`
2.备份：`cp -rf /etc/kubernetes /etc/kubernetes.bak`
3.更新证书：`kubeadm certs renew all`
4.重启API服务：`docker ps | grep -v pause | grep -E "scheduler|controller|apiserver" | awk '{print $1}' | awk '{print "docker","restart",$1}' | bash`
5.更新链接配置：
  ```
  cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  cd /home/ec2-user/.kube
  chown ec2-user:ec2-user config
  ```
6.检查证书
```
[root@k8s-master01 pki]# kubeadm certs check-expiration
[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'

CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 Oct 26, 2024 08:02 UTC   364d                                    no      
apiserver                  Oct 26, 2024 08:02 UTC   364d            ca                      no      
apiserver-kubelet-client   Oct 26, 2024 08:02 UTC   364d            ca                      no      
controller-manager.conf    Oct 26, 2024 08:02 UTC   364d                                    no      
front-proxy-client         Oct 26, 2024 08:02 UTC   364d            front-proxy-ca          no      
scheduler.conf             Oct 26, 2024 08:02 UTC   364d                                    no      

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      Sep 15, 2031 07:59 UTC   7y              no      
front-proxy-ca          Sep 15, 2031 07:59 UTC   7y              no  
```

7.启动pod 提示一下错误：
```
"https://XX.XX.XX.XX:443/apis/crd.projectcalico.org/v1/ippools?resourceVersion=": x509: certificate has expired or is not yet valid: current time 2023-10-27T15:01:26Z is after 2023-09-18T09:20:41Z, failed to clean up sandbox container
```

**Comment by sftim** [comment]
Please write your issue in English @holidayFeng; this is the language we use for bug reports and feature requests.

**Comment by holidayFeng** [comment]
> Please write your issue in English @holidayFeng; this is the language we use for bug reports and feature requests.

thank you for your reply

issue: x509: certificate has expired or is not yet valid: current time；

I tried the following, but the issue was not resolved, but the certificate was updated by checking kubeadm certs check-expiration；


1.check when certificates expire:
   kubeadm certs check-expiration
2.cp -rf /etc/kubernetes /etc/kubernetes.bak
3.kubeadm certs renew all
4.restart "scheduler|controller|apiserver" ：
docker ps | grep -v pause | grep -E "scheduler|controller|apiserver" | awk '{print $1}' | awk '{print "docker","restart",$1}' | bash
5.update config：
cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
cd /home/ec2-user/.kube
chown ec2-user:ec2-user config

6.
[root@k8s-master01 pki]# kubeadm certs check-expiration
[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'

CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 Oct 26, 2024 08:02 UTC   364d                                    no      
apiserver                  Oct 26, 2024 08:02 UTC   364d            ca                      no      
apiserver-kubelet-client   Oct 26, 2024 08:02 UTC   364d            ca                      no      
controller-manager.conf    Oct 26, 2024 08:02 UTC   364d                                    no      
front-proxy-client         Oct 26, 2024 08:02 UTC   364d            front-proxy-ca          no      
scheduler.conf             Oct 26, 2024 08:02 UTC   364d                                    no      

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      Sep 15, 2031 07:59 UTC   7y              no      
front-proxy-ca          Sep 15, 2031 07:59 UTC   7y              no

**Comment by holidayFeng** [comment]
more information by kubectl describe pod -n mines mines-wallet-server-5cbc4d68df-rbqhs 

Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               50m                  default-scheduler  Successfully assigned mines/mines-wallet-server-5cbc4d68df-rbqhs to k8s-node01
  Warning  FailedCreatePodSandBox  50m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "7410f262f1bbbb01deac357299f810181f387500e5d9426d82b5d71a91601f59" network for pod "mines-wallet-server-5cbc4d68df-rbqhs": networkPlugin cni failed to set up pod "mines-wallet-server-5cbc4d68df-rbqhs_mines" network: Get "https://X.X.X.X:443/apis/crd.projectcalico.org/v1/ippools?resourceVersion=": x509: certificate has expired or is not yet valid: current time 2023-10-27T16:47:28Z is after 2023-09-18T09:20:41Z, failed to clean up sandbox container "7410f262f1bbbb01deac357299f810181f387500e5d9426d82b5d71a91601f59" network for pod "mines-wallet-server-5cbc4d68df-rbqhs": networkPlugin cni failed to teardown pod "mines-wallet-server-5cbc4d68df-rbqhs_mines" network: error getting ClusterInformation: Get "https://X.X.X.X:443/apis/crd.projectcalico.org/v1/clusterinformations/default": x509: certificate has expired or is not yet valid: current time 2023-10-27T16:47:28Z is after 2023-09-18T09:16:42Z]
  Normal   SandboxChanged          30s (x232 over 50m)  kubelet            Pod sandbox changed, it will be killed and re-created.

**Comment by holidayFeng** [comment]
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tengqm** [comment]
This is a support request, it is not a documentation problem.
However, in your step 4, you are restarting the controller plane components using `docker` commands. Why would you do that? All certs/keys are mounted into those static Pods via `hostPath` volumes, is `docker` aware of `hostPath` volumes?
You are supposed to restart all those components in the k8s way. For example, touch the manifests under `/etc/kubernetes/manifests`, or even restart `kubelet`.

**Comment by holidayFeng** [comment]
> This is a support request, it is not a documentation problem. However, in your step 4, you are restarting the controller plane components using `docker` commands. Why would you do that? All certs/keys are mounted into those static Pods via `hostPath` volumes, is `docker` aware of `hostPath` volumes? You are supposed to restart all those components in the k8s way. For example, touch the manifests under `/etc/kubernetes/manifests`, or even restart `kubelet`.

thank you for your reply ;
 "systemctl  restart kubelet" has been executed, but the issue still exists

**Comment by tengqm** [comment]
Did you try this?

> To restart a static Pod you can temporarily remove its manifest file from /etc/kubernetes/manifests/ and wait for 20 seconds (see the fileCheckFrequency value in [KubeletConfiguration struct](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/).

From https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
