### ISSUE TITLE
Inconsistent `initialDelaySeconds` between en and zh in an example of tcp-liveness-readiness.yaml

### ISSUE THREAD

**Issue by caijijian** [kubernetes/website#43730]
在‘’定义 TCP 的存活探测‘’的案例中，就绪探针的示例代码配置为 ‘initialDelaySeconds: 5’，但后续的说明中，却说“kubelet 会在容器启动 15 秒后发送第一个就绪探针”，是否需要修改为“kubelet 会在容器启动 5 秒后发送第一个就绪探针”？

**Comment by aj11anuj** [comment]
@caijijian, It is advisable to raise issues in English language. So, that everyone will be able to understand it.

Translation of issue:-
In the case of "defining TCP survival detection", the sample code of the readiness probe is configured as 'initialDelaySeconds: 5', but in the subsequent description, it is said that "kubelet will send the first readiness probe 15 seconds after the container starts. Needle", does it need to be changed to "kubelet will send the first readiness probe 5 seconds after the container starts"?

**Comment by caijijian** [comment]
> @caijijian, It is advisable to raise issues in English language. So, that everyone will be able to understand it.

@aj11anuj ok, thanks for translating for me.

**Comment by sftim** [comment]
/triage needs-information

Even with a translation, I don't understand if this is a bug report, a support query, or a feature request.

If this is a report of a problem with the Chinese page, and the page in Chinese faithfully localizes an English page where there is room for improvement, then we'd want a report against the English page.

**Comment by niranjandarshann** [comment]
Page related Issue:
https://kubernetes.io/zh-cn/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-TCP-liveness-probe
/language zh-cn

**Comment by niranjandarshann** [comment]
I think the issue raised is correct as readinessprobe initialdelayseconds should also be 15 as the description involve 15 sec. So I think it needs to be change.
"kubelet 会在容器启动 15 秒后发送第一个就绪探针" 
Referring the english documented part 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe
```
readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
```
I think it needs to be changed.

**Comment by niranjandarshann** [comment]
@caijijian  I think you should  raise the issue in English. It will be more useful for contributor to approach the issue. 
Please try to raise it in English.

**Comment by able8** [comment]
@niranjandarshann Right, the `initialDelaySeconds` of the readinessProbe should be 15 instead of 5. Refer to the english documented part
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-tcp-liveness-probe

/assign

**Comment by windsonsea** [comment]
/retitle Inconsistent `initialDelaySeconds` between en and zh in an example of tcp-liveness-readiness.yaml

Hi @caijijian , please use english to describe your issue instead of a localized language (zh-cn), thanks.
