### ISSUE TITLE
Update CEL sets func doc in 1.30

### ISSUE THREAD

**Issue by cici37** [kubernetes/website#43747]
**What would you like to be added**

This is the tracking issue for CEL doc updates. 
Sets func was introduced in https://github.com/kubernetes/kubernetes/pull/121577/ as in dark mode. The accordingly CEL docs (https://kubernetes.io/docs/reference/using-api/cel/#cel-community-libraries) should be updated in 1.30

**Why is this needed**

**Comments**

**Comment by sftim** [comment]
/retitle Update CEL sets func doc in 1.30

**Comment by a-mccarthy** [comment]
@cici37 is this issue ok to close? It looks like the 1.30 docs have already merged, https://github.com/kubernetes/website/pull/45249. thanks!
