### ISSUE TITLE
Bug: Command not working

### ISSUE THREAD

**Issue by PranitRout07** [kubernetes/website#43752]
**ISSUE DETAILS** 
This command "kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml" is not working even my internet is working.

**ERROR SCREENSHOT**
<img width="970" alt="Screenshot 2023-10-31 075934" src="https://github.com/kubernetes/website/assets/102309095/f0e9fe2f-eaab-4e66-8837-29f25d077195">

**Comment by niranjandarshann** [comment]
@PranitRout07  It work perfectly fine for me by deleting  clusterrolebinding  kubernetes-dashboard `kubectl delete clusterrolebinding kubernetes-dashboard`

Can you try with by deleting it ?

**Comment by PranitRout07** [comment]
Hey @niranjandarshann thanks for the help. It works now.
