### ISSUE TITLE
Issue with k8s.io/docs/concepts/policy/pid-limiting/

### ISSUE THREAD

**Issue by snake1028** [kubernetes/website#43753]
Hello，
i need help!!! I can't find the documents on the official website anymore. For example, querying networkpolicy.
May I ask when it will be repaired

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/concepts/policy/pid-limiting/_

**Comment by able8** [comment]
Hi @snake1028, do you mean you want to search for Network Policies docs?  
See https://kubernetes.io/search/?q=networkpolicy 
https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by sftim** [comment]
Does https://kubernetes.io/search/?q=example produce search results when you try @snake1028 ?

If not, that might be due to state-level censorship or a filter managed by your employer. Can you provide a screenshot?

**Comment by thisisharrsh** [comment]
> Does https://kubernetes.io/search/?q=example produce search results when you try @snake1028 ?

Hi @snake1028, have you tried to search on the link mentioned above?

**Comment by thisisharrsh** [comment]
If yes could you please provide us the screenshot of the documentation problem that you facing, it will help us to understand the issue better.

**Comment by niranjandarshann** [comment]
No response from @snake1028  Hope He had come out off the issue faced . 
So Closing this issue. Feel free to raise issue again or you may reopen it if you want.

**Comment by niranjandarshann** [comment]
closing this issue.
/close
