### ISSUE TITLE
Advice on “Install and Set Up kubectl on Windows”

### ISSUE THREAD

**Issue by skchinna7** [kubernetes/website#43765]
Kubectl is not working on windows 
```[tasklist]
### Tasks
```

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/

**Comment by thisisharrsh** [comment]
Hi @skchinna7, could you please provide some details on the problem you are facing?

**Comment by skchinna7** [comment]
Yeah sure when I run the application it's not installing or any window popup is not showing like it installing something like that

**Comment by sftim** [comment]
/retitle Advice on “Install and Set Up kubectl on Windows”
/kind support

**Comment by thisisharrsh** [comment]
GitHub is not the right place for support requests.

For further help, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by kumarankit999** [comment]
Yes @thisisharrsh, you are right we can discuss in Slack channel for this!

**Comment by divya-mohan0209** [comment]
@skchinna7 Please refer to [this comment](https://github.com/kubernetes/website/issues/43765#issuecomment-1790097291) for raising a support issue. Broadly speaking, issues here are related to the content of the website, its technical accuracy, or any suggestions around improvement of the UX. 
/close

**Comment by skchinna7** [comment]
It's still not working
