### ISSUE TITLE
Broken link to Gateway API release notes

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#43761]
**This is a Bug Report**

**Problem:** https://kubernetes.io/blog/2023/10/31/gateway-api-ga/#everything-else has a link to the wrong release notes.

**Proposed Solution:**
Edit the blog article to link to 1.0.0 not 0.1.0

**Page to Update:**
https://kubernetes.io/blog/2023/10/31/gateway-api-ga/#everything-else

**Additional Information:**
/area blog
/sig network
/language en

**Comment by steve-hardman** [comment]
I will attempt to help with this.

/assign

**Comment by dipesh-rawat** [comment]
We should fix the broken link in the blog.

/triage accepted

**Comment by steve-hardman** [comment]
I have submitted PR https://github.com/kubernetes/website/pull/43762 to resolve the issue
