### ISSUE TITLE
Wrong tense in API deprecation page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#43771]
**This is a Bug Report**

**Problem:**
> The v1.27 release will stop serving the following deprecated API versions:

is wrong; the release has already happened.

**Proposed Solution:**
Edit that part of the page to use the past tense.

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**Additional Information:**
/language en
/good-first-issue

You only need to edit one file to do the fix: `https://github.com/kubernetes/website/blob/main/content/en/docs/reference/using-api/deprecation-guide.md`

**Comment by sftim** [comment]
/priority backlog
/triage accepted

Want to to work on this but have already fixed an issue? Please consider leaving it for a newcomer to Kubernetes.

**Comment by rohan-kapse** [comment]
I have made a PR and made the recommended changes by you.

**Comment by vaibhav2107** [comment]
Fixed by #43772

**Comment by vaibhav2107** [comment]
We can close this issue.
/close
