### ISSUE TITLE
"Run a Replicated Stateful Application" task example limited to MySQL 5.7, no MySQL 8 support

### ISSUE THREAD

**Issue by aesakif** [kubernetes/website#43782]
this solution only support mysql5.7.
do not support latest mysql8.
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#starting-replication

**Comment by tamilselvan1102** [comment]
Since this page for example of replicated Stateful application in K8s, So need to mention/investigate more on other softwares.

**Comment by dipesh-rawat** [comment]
/retitle "Run a Replicated Stateful Application" task example limited to MySQL 5.7, no MySQL 8 support
