### ISSUE TITLE
TokenRequest not available by default

### ISSUE THREAD

**Issue by geetikakay** [kubernetes/website#43784]
TokenRequest is not available by default . When i try to see cluster resources it populates

$ kubectl api-resources| grep -i token
tokenreviews                                                                                                                 authentication.k8s.io/v1                       false        TokenReview

How i can enable TokenRequest as resource just like tokenreviews

**Comment by sftim** [comment]
See https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/#create-create-token-of-a-serviceaccount

The API kind that has a TokenRequest subresource is called ServiceAccount.

/triage unresolved

There's nothing to fix right now. If there's a page that could make the point more obvious, you are welcome to suggest a specific improvement @geetikakay

/close not-planned
