### ISSUE TITLE
[es] localize content/en/docs/concepts/storage/windows-storage.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#43791]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/concepts/storage/windows-storage.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs

**Comment by ramrodo** [comment]
This issue was created to be assigned to @edithturn.

Could you add a comment here to assign this issue to you Edith, please?

**Comment by edithturn** [comment]
Hi Rodolfo, I would love to work on this translation.
