### ISSUE TITLE
kubeadm 配置 (v1beta3)

### ISSUE THREAD

**Issue by pptfz** [kubernetes/website#43796]
在这个 [InitConfiguration](https://kubernetes.io/zh-cn/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-InitConfiguration) 中的 `skipPhases []string` 配置下，这个 `药` 是不是写错了？

skipPhases 是命令执行过程中药略过的阶段（Phases）。？

skipPhases 是命令执行过程中要略过的阶段（Phases）。？

**Comment by tengqm** [comment]
/triage accepted
/kind bug
PRs welcomed.
