### ISSUE TITLE
[hi] localize content/en/docs/concepts/overview/_index.md to Hindi

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/website#43799]
This is a Feature Request

What would you like to be added
Localize content/en/docs/concepts/overview/_index.md to Hindi

Why is this needed
There is no Hindi localization for this file.

Comments

I would like to work on this

/kind feature
/language hi
/sig docs
/assign

**Comment by dipesh-rawat** [comment]
/triage duplicate

This looks like a duplicate of issue https://github.com/kubernetes/website/issues/42844

**Comment by aj11anuj** [comment]
As it's a proper duplicate of issue #42844 and doesn't adding any value as a separate issue.
/close not-planned
