### ISSUE TITLE
Lack of details on `MountFlags` and its usage with containerd in "Volumes" page

### ISSUE THREAD

**Issue by imne** [kubernetes/website#43809]
No details about mountflags and how to set that up using containerd only details around docker

**Comment by dipesh-rawat** [comment]
/retitle Lack of details on `MountFlags` and its usage with containerd in "Volumes" page

**Comment by dipesh-rawat** [comment]
/retitle Lack of details on `MountFlags` and its usage with containerd in "Volumes" page

**Comment by kumarankit999** [comment]
Can I work on this, if this issue is being triage accepted

**Comment by sftim** [comment]
/sig storage
/triage accepted

(**anyone is welcome to work on this** - we have a “no [cookie licking](https://www.redhat.com/en/blog/stop-licking-cookie)” policy in SIG Docs)

If someone has said they plan to work on an issue, and you're also considering that work, it's polite - but not mandatory - to try to co-ordinate.

**Comment by sftim** [comment]
I think the fix we should make is to remove https://kubernetes.io/docs/concepts/storage/volumes/#configuration - it's out of date and also doesn't belong as part of the conceptual explanation of what a volume is.

**Comment by vaibhav2107** [comment]
Sure @iArchitSharma , this issue can be closed
