### ISSUE TITLE
Confusing duplicate sections "Custom resources and Server-Side Apply" and "Server-Side Apply for custom resources" in "Server-Side Apply" page

### ISSUE THREAD

**Issue by Pavaningithub** [kubernetes/website#43806]
Below sections are identical causes confusion. Suggest keeping one.
[Custom resources and Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/#custom-resources-and-server-side-apply)

[Server-Side Apply for custom resources](https://kubernetes.io/docs/reference/using-api/server-side-apply/#custom-resources)

**Comment by dipesh-rawat** [comment]
/retitle Confusing duplicate sections "Custom resources and Server-Side Apply" and "Server-Side Apply for custom resources" in "Server-Side Apply" page

**Comment by sftim** [comment]
That's a bug. Cleanup is welcome (you can delete either of the duplicate sections).

/triage accepted
/kind bug
/help
/priority backlog

**Comment by rohan-kapse** [comment]
@sftim Can i get assigned ?

**Comment by dipesh-rawat** [comment]
Fixed by https://github.com/kubernetes/website/pull/43814

/close
