### ISSUE TITLE
Unable to install kubeadm on RHEL 8

### ISSUE THREAD

**Issue by Teskoh27** [kubernetes/website#43810]
I used the following link ( https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) to figure out how to install kubernetes on a rhel 8 server, but the urls in the /etc/yum.repos.d/kubernetes.repo are broken.  Can you please help me out?

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm
/language en

**Comment by dipesh-rawat** [comment]
/retitle Unable to install kubeadm on RHEL 8

**Comment by neolit123** [comment]
```sh
$ docker run -it fedora:40 bash

$ cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/
enabled=1
gpgcheck=1
gpgkey=https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
EOF
$ sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
# .. everything installs ok
$ kubelet --version
Kubernetes v1.28.3
```

i don't have RHEL 8, but Fedora 40 works fine. RHEL is based on Fedora.

a better place to ask for help would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
