### ISSUE TITLE
Linkedin Tab

### ISSUE THREAD

**Issue by Ayush9026** [kubernetes/website#43842]
**This is a Feature Request**

Linkedin Tab is not there marked in screenshot below  people should follow LinkedIn page for a company if tab provided.

![Kubernetes](https://github.com/kubernetes/website/assets/114745463/62f148b8-a6b9-492b-b619-fda8cabae4cb)

**What would you like to be added**

Add the Linkedin tab so that user or contributor follow page.

**Why is this needed**

Providing URL to Linkedin page can have several benefits.

1.Brand Consistency
2.Modernization
3.Adaptation to New Features
4.Improved Aesthetics
5.Legal Compliance
6.Enhanced Recognition

**Comment by Gauravpadam** [comment]
We do have a [LinkedIn page](https://www.linkedin.com/company/kubernetes)

This feature will be nice to have imo

**Comment by sftim** [comment]
/priority awaiting-more-evidence

I don't think we actually have a LinkedIn page, although somebody has made one.

**Comment by sftim** [comment]
@Ayush9026 do you have the capacity to check out (eg with SIG Contributor Experience) whether we, the Kubernetes project, are connected to managing https://www.linkedin.com/company/kubernetes?

If we're not sure who looks after that page, it may be better to close this issue. We have other tasks that we could choose to prioritize.

**Comment by Ayush9026** [comment]
Hi @sftim i am not clear who look that page .

**Comment by Ayush9026** [comment]
@Gauravpadam can you know who look that page. If you Know then please tell.

**Comment by shubham-mishra-ca** [comment]
Hey everyone,

Quick thought: if there's some confusion about the legitimacy of the LinkedIn page, it might be prudent to pause on adding the tab. The last thing we want is to mislead users into following an unofficial page.

To get to the bottom of this, has anyone reached out to the CNCF to see if they sanctioned the LinkedIn page? If not, I'm happy to drop them a line to clarify. If the page is official, then adding the tab seems like a good move, and I'd be keen to help make that happen.

If we find the page isn't official, we should probably discuss whether it's worth creating a verified one, given the potential benefits mentioned. That said, if we've got higher-priority tasks on our plate, those should likely take precedence.

**Comment by kumarankit999** [comment]
Yes @shubham-mishra-ca let's first find that is it legitimate ID or not!

**Comment by Rajdeep1311** [comment]
@kumarankit999 I don't think it is legitimate, if it was I guess it would contain some posts at least about the K8s releases, but there are none, no posts at all. Even if it is the original, its very non-active

**Comment by Gauravpadam** [comment]
@draunger I would not recommend working on this issue, as of now we have no confirmation over the authority of the LinkedIn page

**Comment by draunger** [comment]
@Gauravpadam ok sir

**Comment by Gauravpadam** [comment]
/close not-planned

Please feel free to re-open this once we have the needed information
