### ISSUE TITLE
Change Twitter icon with updated one 

### ISSUE THREAD

**Issue by Ayush9026** [kubernetes/website#43856]
**This is a Feature Request**

Update twitter icon with new one that is 'X'.

![Kubernetes](https://github.com/kubernetes/website/assets/114745463/aa534c18-baaa-4923-b325-2da694c421c7)

**What would you like to be added**

Updated icon of twitter that is 'X'.

**Why is this needed**

Providing updated twitter icon to can have several benefits.

1.Brand Consistency
2.Modernization
3.Adaptation to New Features
4.Improved Aesthetics
5.Legal Compliance
6.Enhanced Recognition

**Comment by kundan2707** [comment]
@Ayush9026  we have already such issue open https://github.com/kubernetes/website/issues/43206

**Comment by draunger** [comment]
Assign me

**Comment by kumarankit999** [comment]
I think we can close this issue

**Comment by Gauravpadam** [comment]
@draunger This one is a _duplicate_ of #43206
Fixes on the main issue are welcome

(And you don't need an assignment to propose a fix)

**Comment by kumarankit999** [comment]
> /triage duplicate

+1

**Comment by sftim** [comment]
/close not-planned

This is a duplicate report
