### ISSUE TITLE
[zh] Bug - the text in the flowchart should be Chinese on Extending Kubernetes page

### ISSUE THREAD

**Issue by Yenuo** [kubernetes/website#43861]
当前这个https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/  此页面选择中文后，流程图中的文字不是中文。

**Comment by niranjandarshann** [comment]
@Yenuo  Please raise the issue in English language so that it can be  easy to understand in community.

**Comment by niranjandarshann** [comment]
/language zh 

Issue Translation is 
Currently this https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/ After this page select 中文, the text in the flow chart is not 中文.

**Comment by niranjandarshann** [comment]
/triage needs-information

Even with a translation, I don't understand if this is a bug report, a support query, or a feature request.

**Comment by able8** [comment]
/retitle [zh] Bug - the text in the flowchart should be Chinese on Extending Kubernetes page

It is a bug, on zh-cn page https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/ 
, the text in the flowchart should be Chinese instead of Korean.
