### ISSUE TITLE
Tutorial: Running Multiple Instances of Your App may have a wrong suggestion of preparation.

### ISSUE THREAD

**Issue by 1000Delta** [kubernetes/website#43864]
**This is a Bug Report**

**Problem:** The tutorial [Running Multiple Instances of Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/) may have a wrong suggestion before trying to scaling.

Snippet:

> NOTE If you are trying this after [the previous section ](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/), you may need to start from [creating a cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) as the services may have been deleted

**Proposed Solution:** The suggest tutorial shouldn't be [creating a cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) but [Using kubectl to Create a Deployment](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/). Because the previous section only mentioned delete Deployment, not about the cluster.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/

**Comment by a-mccarthy** [comment]
Thanks for filing! Looks like this note was updated by https://github.com/kubernetes/website/pull/44752. If you have any other suggestions for improving this page, please file a new issue :) 

/close
