### ISSUE TITLE
[hi] Navigation menu displays 'Home' instead of 'Documentation'

### ISSUE THREAD

**Issue by abhay-raj19** [kubernetes/website#43900]
**This is a Bug Report**

While the left hand side navigation menu in Hindi and English is not fully matching and can create some issues for a native hindi reader .

**Problem:**

The option `Documentation` in English has been changed to `होम` in Hindi which can be an issue while navigating for a native Hindi reader.

**Proposed Solution:**

I have 2 options, I can change it to `प्रलेखन` or `लेखन` .
Suggestions required

**Page to Update:**

https://kubernetes.io/docs/home/

**Screenshot(can be easily compared up)**

**Hindi**

![image](https://github.com/kubernetes/website/assets/96302417/d06a73ef-30ed-40ba-a0c0-77aa68161288)

**English**

<img width="960" alt="image" src="https://github.com/kubernetes/website/assets/96302417/abcb4dd6-d606-4f27-9a90-b5861073ecda">

**Comment by dipesh-rawat** [comment]
/retitle [hi] Navigation menu displays 'Home' instead of 'Documentation'

**Comment by dipesh-rawat** [comment]
It appears that there is already an existing (umbrella) issue https://github.com/kubernetes/website/issues/43068, addressing this request for all the different langauges. Additionally, there is already a PR https://github.com/kubernetes/website/pull/43069 raised specifically for the fix in Hindi language.

**Comment by dipesh-rawat** [comment]
Marking this as a duplicate.
/triage duplicate

**Comment by vr-varad** [comment]
if possible assign it to me i can work on it

**Comment by Gauravpadam** [comment]
@vr-varad You don't need an assignment to work on issues, Anybody is welcome to propose a fix

Being said that, If someone will/has already proposed a PR, It's polite to co-author with them (but not mandatory)

**Comment by aj11anuj** [comment]
This issue although addresses same type of issue as in #43068, but in different place. #43068 is addressing specifically for footer across all localizations. And in this issue it is for Navigation menu and that too for specifically Hindi localized page. So, i think its better not to consider it a duplicate.

For those, who want to work on it. Changing this `linkTitle` key-value pair with value `प्रलेखन` can probably fix it.

![Screenshot (868)](https://github.com/kubernetes/website/assets/116108975/3c0ccd2e-227b-459c-97a3-8de8d20ba35f)

**Comment by steve-hardman** [comment]
@dipesh-rawat Can I plz solve this issue? I want try do some localization cjhange to deepen my udnerstanding and help languages team where i can :)

**Comment by dipesh-rawat** [comment]
/remove-triage duplicate
Based on info provided in https://github.com/kubernetes/website/issues/43900#issuecomment-1810988608

**Comment by dipesh-rawat** [comment]
> Can I plz solve this issue?

@steve-hardman Anyone is free to propose a fix by submitting a pull request; you don't require anybody's permission as we operate in the spirit of open source collaboration. Just a friendly reminder, these changes pertain to Hindi localization, so having familiarity with the Hindi language would be advantageous, although it's not mandatory.

**Comment by steve-hardman** [comment]
Okay got it. Thanks!

I will assign to myself in that case.
/assign

**Comment by steve-hardman** [comment]
@dipesh-rawat I have riased https://github.com/kubernetes/website/pull/43943 plz review and let me know if its okay. Thanks in advance.
