### ISSUE TITLE
Seeking assistance for adding images in blog post

### ISSUE THREAD

**Issue by xPetersue** [kubernetes/website#43919]
This is my first time uploading an article here, and it includes some images. However, I'm unsure about where to place these images. Can anyone offer some guidance? I would really appreciate it.

_Originally posted by @xPetersue in https://github.com/kubernetes/website/issues/43914#issuecomment-1809219799_

**Comment by dipesh-rawat** [comment]
/retitle Seeking assistance for adding images in blog post
/kind support

**Comment by dipesh-rawat** [comment]
Please take a look at ['Submitting Blog Posts and Case Studies](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/)' and ['Diagram Guide'](https://kubernetes.io/docs/contribute/style/diagram-guide/) pages. They should provide you with hints with your query. Additionally, you can take a look at commit https://github.com/kubernetes/website/commit/506d97c192cdb7799aed9b42091a00756a6948fb or explore the [blog files](https://github.com/kubernetes/website/tree/main/content/en/blog/_posts) in the repository to see how previous blogs have successfully incorporated images.

**Comment by sftim** [comment]
I would ask for advice in #sig-docs-blog on Kubernetes' Slack workspace. You can visit https://slack.k8s.io/ for an invitation.

However, there is a long wait time for help; or, if you like, very little contributor capacity to offer that help.

**Comment by sftim** [comment]
/close

Explained how to ask for advice.
