### ISSUE TITLE
kubeadm init --use-kubernetes-version v1.4.0-beta.11 not working

### ISSUE THREAD

**Issue by thatsk** [kubernetes/website#4391]
Issue with /docs/getting-started-guides/kubeadm/

ON this page the second step is wrong 
there is not such parameter

**Comment by zacharysarah** [comment]
@thatsk Thanks for opening this issue. A couple of things:

1. The second step in the instructions specifies the following command:

```shell
kubeadm init
```

Can you point to where you're getting the rest of the command syntax? Specifically: 

```shell
--use-kubernetes-version v1.4.0-beta.11
```

2. This issue sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](http://slack.k8s.io/).

**Comment by thatsk** [comment]
ok
