### ISSUE TITLE
Issue with /docs/getting-started-guides/docker-multinode/

### ISSUE THREAD

**Issue by Awdhoot** [kubernetes/website#4392]
After cloning [this](https://github.com/kubernetes/kube-deploy) repo, it does not contain any folder named "docker-multinode" and I am not able to find master.sh script inside the repo. 
I am following [this](https://lukemarsden.github.io/docs/getting-started-guides/docker-multinode/) guide.

**Comment by zacharysarah** [comment]
@Awdhoot Thanks for opening this issue. It looks like the contents of [kubernetes/kube-deploy](https://github.com/kubernetes/kube-deploy) have changed and the docs are stale.

@jaredbhatti 👋 Do you know who the maintainer of kube-deploy is? It would be good to get their input here.

For docs: this issue looks like it will require some investigation, but it still looks actionable.

**Comment by tengqm** [comment]
Closing because the recommended way is to use kubeadm now.
