### ISSUE TITLE
Typo in Taints and Tolerations page

### ISSUE THREAD

**Issue by PeterP55P** [kubernetes/website#43929]
I believe there is a typo in this section.

```
kubectl taint nodes node1 key1=value1:NoSchedule
kubectl taint nodes node1 key1=value1:NoExecute
kubectl taint nodes node1 key2=value2:NoSchedule
```

In second row there should be value2 instead of value1.

```
kubectl taint nodes node1 key1=value1:NoSchedule
kubectl taint nodes node1 key1=value2:NoExecute
kubectl taint nodes node1 key2=value2:NoSchedule
```

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration
/language en

**Comment by aj11anuj** [comment]
Can you provide some more details? Why do you think it should be 'value2'?
/priority awaiting-more-evidence

**Comment by aj11anuj** [comment]
/retitle Typo in Taints and Tolerations page

Typo/Improvement related issue so, maybe this one
/kind feature

**Comment by PeterP55P** [comment]
This is more a question than a statement. I was under impression that you can use the same key/value pair only for one taint. I expected another such action to overwrite the value of the effect. 
I did a test just a moment ago and it seems I was wrong. 
Please ignore this issue as it is not an issue indeed.
