### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/openstack-heat/

### ISSUE THREAD

**Issue by srinathmatti** [kubernetes/website#4393]
There is a wrong link for "correct variables " , please point it to 
https://docs.openstack.org/user-guide/common/cli-set-environment-variables-using-openstack-rc.html

**Comment by minivan** [comment]
Can confirm, [the current link](https://docs.openstack.org/user-guide/common/cli_set_environment_variables_using_openstack_rc.html) is a 404.

**Comment by srinathmatti** [comment]
Now openstack has changed the documentation tree , I am unable to find the link https://docs.openstack.org/user-guide/common/cli-set-environment-variables-using-openstack-rc.html . It is redirecting to https://docs.openstack.org/user/ . Not sure what is the end link now

**Comment by Bradamant3** [comment]
July 21: https://docs.openstack.org/user/ now also produces a 404, with a notice about major reorg of the openstack docs site. Hard to tell how long it will go on (I've been seeing its effects for a while now). Spent a while on the site, trying both search and the current navigation. No luck.
