### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by xuangbing55** [kubernetes/website#43930]
kubelet start failed，message：

kubelet[2813]: E1114 20:10:19.135090    2813 run.go:74] "command failed" err="failed to validate kubelet flags: the container runtime endpoint address was not specified or empty, use --container-runtime-endpoint to set"
systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by dipesh-rawat** [comment]
@xuangbing55  It seems you're seeking a volunteer to review the [logs](https://github.com/kubernetes/website/issues/43930#issue-1992618762) and address the issue causing you trouble. However, the current [issue description](https://github.com/kubernetes/website/issues/43930#issue-1992618762) is unclear. Providing more details about the issue and the required fixes would greatly assist other contributors in helping with this.

/triage needs-information

**Comment by neolit123** [comment]
a better place to ask for help would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by tengqm** [comment]
You may want to check the kubelet systemd unit file and see what are the config files it is referencing. Then you will go to, for example /var/lib/kubelet, and find out the files to be changed.

**Comment by xuangbing55** [comment]
kubelet uccessfully started when kubeadm init completed,thanks
