### ISSUE TITLE
Missing button for "Available Documentation Version"

### ISSUE THREAD

**Issue by satyampsoni** [kubernetes/website#43957]
**This is a Feature Request**
To maintain consistency, add a button to "Available Documentation Versions."

**What would you like to be added**

![image](https://github.com/kubernetes/website/assets/94950988/89fad96d-f32f-483a-84d2-ee5ae3b2e98b)

**Comments**

Page to edit: https://kubernetes.io/docs/home/

**Comment by sftim** [comment]
/kind feature
/area web-development

There is a bit of a reason behind the difference: it's not a verb (the others are). I'm glad it stands out; I'd like readers to see that there are other versions available. So, if it were up to me, I'd leave things as they are.

**Comment by Iteratum** [comment]
Can I get this issue assigned to me

**Comment by kumarankit999** [comment]
Why not, You can get the issue by  "/issue"

**Comment by sftim** [comment]
> if it were up to me, I'd leave things as they are

As a SIG, we'd prefer people to work on issues where there's consensus that we'd accept a fix.
See https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Atriage%2Faccepted+sort%3Acreated-asc

**Comment by satyampsoni** [comment]
@sftim I am sorry I was not aware of the verb case. so, is this issue still relevant or closing this is a good option?

**Comment by kumarankit999** [comment]
Yes @satyampsoni I also think that we can close this issue!!
and can refer https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3Atriage%2Faccepted+sort%3Acreated-asc

**Comment by Rajdeep1311** [comment]
Is this issue still relevant? @kumarankit999

**Comment by aj11anuj** [comment]
Issue is less likely to get accepted
/close not-planned
