### ISSUE TITLE
Client Libraries: github.com/ericchiang/k8s  listed but unmaintained since 3-5 years.

### ISSUE THREAD

**Issue by nightlyone** [kubernetes/website#43951]
github.com/ericchiang/k8s is mentioned as a third party Go library, but has been archived by its author on Nov 19, 2020 (3m years ago as of writing this issue), last published at pkg.go.dev/github.com/ericchiang/k8s on Jul 26, 2018.

So I would suggest to at least list it with an appropriate comment in https://kubernetes.io/docs/reference/using-api/client-libraries/#community-maintained-client-libraries (e.g. "Unmaintained/Archived").

It  might still be useful to know it, as it appears to be imported by ~580 projects according to https://pkg.go.dev/github.com/ericchiang/k8s?tab=importedby but usage in new projects should be discouraged and well maintained active projects should probably move away from it.

**De-listing** that library might also be possible action to take.

Please note, that I didn't bother to test whether the library still works at all.

**Comment by AmarNathChary** [comment]
There was some discussion in https://github.com/kubernetes/website/issues/21563#issuecomment-660775584

**Comment by sftim** [comment]
We're wary of passing judgement on third party code: it might look as if we're tacitly endorsing the rest of the list (which isn't true). However, as https://github.com/ericchiang/k8s is **archived**, I think it's OK to remove the link.

_This does not set a precedent for removing or commenting on third-party links without an obvious mark such as the maintainer setting it as archived_

---

/triage accepted
/priority backlog
/help

**Comment by sftim** [comment]
The action I recommend: remove the link, on the grounds that the repo we link to is archived. We do also provide an in-project alternative library, https://github.com/kubernetes/client-go/, which is well tested.

**Comment by steve-hardman** [comment]
i will try to help with this.
/assign
