### ISSUE TITLE
“Using kubectl to Create a Deployment” introduces Pods without explanation

### ISSUE THREAD

**Issue by rjsmithFive9** [kubernetes/website#43953]
Under "View the app", the concept of "pods" is referenced without being previously defined.

[edit: Page in question is [https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/](https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/)]

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
/language en

**Comment by T-Lakshmi** [comment]
@rjsmithFive9,
Under [concept](https://kubernetes.io/docs/concepts/) section we have a separate topic for [pods](https://kubernetes.io/docs/concepts/workloads/pods/) and well explained.
Now what would you like to improve for this page?
Do you want to provide a hyperlink to redirect people to  [pods](https://kubernetes.io/docs/concepts/workloads/pods/) page?

**Comment by sftim** [comment]
Great suggestion! We should definitely let readers know the connection between the Deployment, their app, and this concept of _Pods_.

/triage accepted
/sig docs
/retitle “Using kubectl to Create a Deployment” introduces Pods without explanation

**Comment by T-Lakshmi** [comment]
@rjsmithFive9,
ok, i will work on it.

**Comment by T-Lakshmi** [comment]
@rjsmithFive9,

>  It is covered well in part 3 of the tutorial. A quick hyperlink, hover-over text, or note (pods covered in step 3) may help orientation. 

part 3 of the tutorial [Viewing Pods and Nodes]/docs/tutorials/kubernetes-basics/explore/explore-intro/) is already mentioned at the end of the section.
`Once you're ready, move on to [Viewing Pods and Nodes](https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/).`

So i have added only a hyperlink for pods concept page.
Let me know if anything need to be improved you feel.

**Comment by T-Lakshmi** [comment]
PR raised #44051
