### ISSUE TITLE
Seeking guidance on HorizontalPodAutoscaler scaling behaviour after reapplying deployment YAML

### ISSUE THREAD

**Issue by JoranDox** [kubernetes/website#43966]
I've been looking around and I can't seem to find a definition of what's expected, nor what to do if what I saw is expected:

- I have some custom deployment running in kubernetes, deployed by `kubectl apply -f ...`
- I have a HPA running along with that deployment, autoscaling the deployment when needed
- if I kubectl apply the same (slightly changed) file again (typically the imagetag has changed) (typically from ci/cd pipelines), the current replicacount is overwritten again, and the HPA needs to start scaling again.

So my questions are:
- Is this (deployment replicas overwriting HPA replicacount on reapplying a yaml) expected behaviour?
- Can I bypass this somehow? Replicas is a required field so I can't just leave that empty, right?
- Is there another solution I'm missing? I have a poddisruptionbudget with maxunavailable=1 too, but that doesn't seem to matter if the replicas just get put back to 1

**Comment by dipesh-rawat** [comment]
_Page mentioned in the reported issue title:_ https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Seeking guidance on HorizontalPodAutoscaler scaling behaviour after reapplying deployment YAML

**Comment by dipesh-rawat** [comment]
(Looks like a request for help in its current form)
/kind support

**Comment by JoranDox** [comment]
> (Looks like a request for help in its current form) /kind support

Indeed, but I was kind of expecting it in the documentation page so I wasn't sure what to do with it :sweat_smile:

**Comment by dipesh-rawat** [comment]
Does the information on the page https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale help address the query?

Additionally, consider exploring alternative resources like the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for additional support.
