### ISSUE TITLE
Remove the What is Kubernetes part from Concepts

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/website#43987]
There is no need of What is kubernetes in Hindi Page!!!! refer for hindi: https://kubernetes.io/hi/docs/concepts/  for english: https://kubernetes.io/docs/concepts/
 We should Remove the What is Kubernetes!! and put all the localized inside topics from concepts, it not looks well.
![image](https://github.com/kubernetes/website/assets/111564362/f9ab118d-e987-42ca-b083-49656d0a6d47)
and we should make like this one: 
![image](https://github.com/kubernetes/website/assets/111564362/c78d839b-baef-4918-ac1a-b441c5c9cd39)

/language hi
/sig docs
/kind feature

**Comment by sftim** [comment]
I think that rather than remove the Hindi page, we should finish localizing it.

**Comment by dipesh-rawat** [comment]
> There is no need of What is kubernetes in Hindi Page!!!!

The above statement might not be entirely true. The English content has undergone restructuring via PR [#35298](https://github.com/kubernetes/website/pull/35298/files) _(contains refactor label)_, moving the "what-is-kubernetes" into the Overview page. The primary concern is that the existing Hindi page content in "what-is-kubernetes.md" should also be relocated to align with the main website for consistency. This is being addressed in issue https://github.com/kubernetes/website/issues/42844 (making this a potential duplicate).

**Comment by kumarankit999** [comment]
Yes @sftim You are right!
We will be localizing all the inside topics and then delete or clear this page https://kubernetes.io/hi/docs/concepts/overview/what-is-kubernetes/
But in one PR how much file We will be localizing!!!

**Comment by dipesh-rawat** [comment]
> put all the localized inside topics from concepts,

I think it would be beneficial to break down this task into smaller, non-duplicate issues. This approach allows us to address each page within the Concepts section individually, making it more organized and facilitating collaboration from multiple contributors.

**Comment by kumarankit999** [comment]
Yes, we can do this @dipesh-rawat , In one PR how much files will we create to merge because In a Single PR We can't make all the changes!

**Comment by kumarankit999** [comment]
Any Suggestions on this above @dipesh-rawat ????

**Comment by abhay-raj19** [comment]
@kumarankit999 i had raised up the similar issue for localising it up prior to this issue . 
#42844
And that issue resolves all the problem navigating to overview but it is "what is kubernetes".

**Comment by divya-mohan0209** [comment]
So, the expected outcome from this PR has been achieved although the page remains incomplete. I will be opening up a sample tracking issue to follow up on the localization efforts for the rest of the page. 

/triage accepted
/close
