### ISSUE TITLE
[Tracking issue] Addition of year-end & start-of-the-year SIG co-chair/lead activities

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#43990]
We have several activities that are performed close to year-end & start of next year. Some of them include:

- Preparation of PR Wrangler schedule for the upcoming year
- Preparation of Issue Wrangler schedule for the upcoming year
- Pruning the OWNERS file
- Preparing the annual report for the past year

It'd be helpful to have this documented somewhere in k/website or k/community.

 Tagging @a-mccarthy since you already have a version of this documentation up on GDocs.

cc: @reylejano @natalisucks

**Comment by divya-mohan0209** [comment]
Adding a doc in k/community seems like the logical next step. I will be opening a PR and link it here.

**Comment by iArchitSharma** [comment]
@divya-mohan0209 can i help with this issue?

**Comment by natalisucks** [comment]
@iArchitSharma Hi there - unfortunately, these are tasks that @divya-mohan0209, @reylejano, and myself must complete as co-chairs of SIG Docs. However, there might be chances to help contribute to the annual report that we'll make known in the #sig-docs channel on k8s Slack when that work begins.
