### ISSUE TITLE
Metrics reference is for (unreleased) v1.29

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44008]
**This is a Bug Report**

**Problem:**
https://kubernetes.io/docs/reference/instrumentation/metrics/ says that it is for Kubernetes v1.29, which has yet to be released.

**Proposed Solution:**
Revise https://kubernetes.io/docs/reference/instrumentation/metrics/ to cover v1.28 metrics

**Page to Update:**
https://kubernetes.io/docs/reference/instrumentation/metrics/

**Additional Information:**
We should fix this before the v1.29 release.

/priority important-soon
/sig instrumentation
/language en
/triage accepted

**Comment by Gauravpadam** [comment]
Upon some investigation, I can see the generation of 1.29 metrics on one of my old PRs; Please refer https://github.com/kubernetes/website/pull/42823

If reverting to an older version of this file helps, Let's do that. I'll make amendments for the formatting once again

Alternately, We can try some experimenting with git history and make a PR which generates 1.28 metrics, With the formatting in place. That should work too (I'd prefer doing this)

**Comment by coder12git** [comment]
I can take this.

**Comment by sftim** [comment]
Given the timeline, please mention @kubernetes/sig-docs-en-owners in the PR and also request a review specifically from me.

Whoever gets to it first can pick up the review work.

**Comment by sftim** [comment]
@Gauravpadam any advice for @coder12git

**Comment by Gauravpadam** [comment]
Sure, Here's my advice

@coder12git These metrics are generated over at https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/documentation/main.go

Part of the work here includes figuring out where the generation went from 1.28 to 1.29
If you're able to do that, We can revert to the point where 1.28 metrics were generated

Given the timeline of docs 1.29 release, If that's not possible in this timeframe,
We should revert #42823, Since we had 1.28 metrics before that change

@sftim would you like to add something else?

**Comment by coder12git** [comment]
> Sure, Here's my advice
> 
> @coder12git These metrics are generated over at https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/documentation/main.go
> 
> Part of the work here includes figuring out where the generation went from 1.28 to 1.29 If you're able to do that, We can revert to the point where 1.28 metrics were generated
> 
> Given the timeline of docs 1.29 release, If that's not possible in this timeframe, We should revert #42823
> 
> @sftim would you like to add anything else?
 Thanks, I will see that, btw can i know what's the timeline?

**Comment by Gauravpadam** [comment]
> can i know what's the timeline?
I believe the release is on 5th December

**Comment by coder12git** [comment]
@Gauravpadam I found that due to [this](https://github.com/kubernetes/kubernetes/commit/04292dd94bd9999dfced146f4de8b81a0e466e06) commit which was made by bot on 6-9-23, changed the version from 1.28 to 1.29. If we revert this than the issue will be resolved.
// @sftim

**Comment by Gauravpadam** [comment]
That's the code we adopted in #42823

@sftim can we revert this PR for the docs at the time of 1.29 release while keeping the generator at k8s/k8s, the same?

After the release we can sync back from k8s/k8s

**Comment by coder12git** [comment]
> After the release we can sync back from k8s/k8s

Yeah, this can work too

**Comment by Gauravpadam** [comment]
@coder12git I believe now is a good time to revert that PR (only reverting the markdown changes would be fine)

**Comment by coder12git** [comment]
> @coder12git I believe now is a good time to revert that PR (only reverting the markdown changes would be fine)

Sure

**Comment by coder12git** [comment]
@Gauravpadam you mean reverting completely this PR - #42823

**Comment by Gauravpadam** [comment]
> @Gauravpadam you mean reverting completely this PR - #42823

Yes that's correct
