### ISSUE TITLE
Incorrect cleanup instruction in macOS kubectl installation guide

### ISSUE THREAD

**Issue by Previnkumar** [kubernetes/website#44019]
In Step 6 of https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#install-kubectl-binary-with-curl-on-macos,

The command says to delete kubectl along with kubectl.sha256 file, but kubectl is already moved in step 4.

The command needs to be

_rm kubectl.sha256_

instead of

_rm kubectl kubectl.sha256_

**Comment by dipesh-rawat** [comment]
/retitle Incorrect cleanup instruction in macOS kubectl installation guide
/kind bug

**Comment by steve-hardman** [comment]
I can help with this. Worked on this files before too.
/assign

**Comment by steve-hardman** [comment]
@dipesh-rawat i submited PR https://github.com/kubernetes/website/pull/44043 pelase review when got time. Thanks!
