### ISSUE TITLE
[ko] Typo in 'Using Source IP'

### ISSUE THREAD

**Issue by todayislegday** [kubernetes/website#44017]
![image](https://github.com/kubernetes/website/assets/56506190/9f240625-5126-4538-a86e-51bf32c4a3d8)
there is typo in "Using Source IP korean docs"
could u correct word noee2 to node2 ??

**Comment by AmarNathChary** [comment]
Hey, @todayislegday Can you please describe the issue in English?

**Comment by sftim** [comment]
/triage needs-information

We'd like an English description for the issue.

**Comment by todayislegday** [comment]
i find typo in "Using Source IP  korean docs"
ps check it : )

**Comment by jihoon-seo** [comment]
Page: https://kubernetes.io/ko/docs/tutorials/services/source-ip/#:~:text=IP%20주소로%20교체한다.-,noee2,-는%20대상%20IP
/triage accepted

@todayislegday 안녕하세요. 이슈 올려 주셔서 감사합니다.
다만 이 repo는 영문 및 다양한 언어로의 현지화 작업이 진행되는 곳이어서, 이슈&PR의 제목 (+본문) 을 영어로 적어 주시는 것이 좋습니다.

/retitle [ko] Typo in 'Using Source IP'

이 이슈 본문의 텍스트도 영문으로 수정해 주시면 감사하겠습니다~~

**Comment by jihoon-seo** [comment]
The author of this issue is indicating that there exists a [typo](https://kubernetes.io/ko/docs/tutorials/services/source-ip/#:~:text=IP%20주소로%20교체한다.-,noee2,-는%20대상%20IP) in the Korean version of 'Using Source IP' page.
I am removing the label 'triage/needs-information' to prevent further confusion of others.
/remove-triage needs-information

**Comment by jihoon-seo** [comment]
For who take this issue:
Kubernetes SIG Docs Korean L10n team is using `dev-1.27-ko.1` branch as a working branch. (#41613)
Please branch off your feature branch from `dev-1.27-ko.1`, and set the target branch of your PR to `dev-1.27-ko.1` as well.
/good-first-issue

**Comment by professorabhay** [comment]
Hey @jihoon-seo, I got the problem and now I'm working on it. Will raise the PR soon !

**Comment by jihoon-seo** [comment]
This issue has been resolved via the PR #44048.
/close
