### ISSUE TITLE
Explanation about to remove directory is not clear

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#44020]
**This is a Bug Report**

**Problem:**
The explanation about to remove created directory **_configure-pod-container_** is not much clear in **Configure a Pod to Use a ConfigMap** page 

**Proposed Solution:**

> If you created a directory configure-pod-container and no longer need it, you should remove that too, or move it into the trash can / deleted files location.

to be replaced as

If you created a directory configure-pod-container and no longer need it, you should remove that too, or move it into the trash.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#cleaning-up

**Comment by divya-mohan0209** [comment]
Hello @tamilselvan1102 , the original content reads fine to me, even as a non-native English speaker. Please can you advise why the sentence is unclear?

**Comment by tamilselvan1102** [comment]
@divya-mohan0209 
The context is understandable that what mean to say but not much clear.
I am having following suggestions .

1. In this context already suggested  **_you should remove_**  or **_move it into the trash_** .
After that again repeating **_deleted files location_**

2. Remove **_can_** : If you created a directory configure-pod-container and no longer need it, you should remove that too, or move it into the **trash / deleted** files location.

**Comment by tamilselvan1102** [comment]
@divya-mohan0209 
looking for suggestion. I want to raise a PR after you point of view.

**Comment by tamilselvan1102** [comment]
I am having one more thought about it.
There is a possibility to misunderstood about [/] in the context. weather [/] is representing the meaning of [OR] or root directory  because it explaining about directory

**Comment by tamilselvan1102** [comment]
Closing the issue because not accepted.
Thank you
