### ISSUE TITLE
Broken link for Telepresence in debugging guide

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#44034]
**This is a Bug Report**
Link provide for **Telepresence**  is wrong

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/debug/debug-cluster/local-debugging/#before-you-begin

**Comment by tamilselvan1102** [comment]
@Community-Programmer 
i am working on it. please un-assign  your self

**Comment by tamilselvan1102** [comment]
@Community-Programmer 
Thank you for PR. 
Since you raised PR i will withdraw my petition But feature don't assign yourself if somebody assigned before you.

**Comment by Community-Programmer** [comment]
Sorry my bad I didn't saw that you have assigned previously...I have close my PR you can reassign yourself again..

**Comment by kumarankit999** [comment]
Why you both guys have removed their assignment!

**Comment by professorabhay** [comment]
Hey @Community-Programmer, Open Your PR again !

**Comment by Community-Programmer** [comment]
> [kumarankit999](/kumarankit999)
 I wasn't aware that @tamilselvan1102 had already assigned himself to work on this issue. I apologize for any confusion

**Comment by Community-Programmer** [comment]
> Hey @Community-Programmer, Open Your PR again !

Dude @tamilselvan1102  will do I already working on another issue

**Comment by dipesh-rawat** [comment]
/retitle Broken link for Telepresence in debugging guide
/priority backlog

**Comment by tamilselvan1102** [comment]
@dipesh-rawat @kumarankit999 
Please review the PR.
Thank you

**Comment by tamilselvan1102** [comment]
Fix got merged. Thank you
/close
