### ISSUE TITLE
Small image size hindering readability in 'The Case for Kubernetes Resource Limits' blog

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#44057]
**This is a Bug Report**
The image in the Blog https://kubernetes.io/blog/2023/11/16/the-case-for-kubernetes-resource-limits/#bin-packing-and-cluster-resource-allocation is very small in size 

**What do you expect**
The width of the image should be increased to user friendly. So the user can read easily...

**Comment by AmarNathChary** [comment]
I will fix this 
/assign

**Comment by AmarNathChary** [comment]
Raised PR in #44059

**Comment by dipesh-rawat** [comment]
/retitle Small image size hindering readability in 'The Case for Kubernetes Resource Limits' blog

**Comment by dipesh-rawat** [comment]
We should attempt to fix this by resizing the image for improved user readability.

/triage accepted
/priority backlog

**Comment by sftim** [comment]
Can you share a screenshot @AmarNathChary ?

(the images look fine on my machine, so it'd be good to see what you're experiencing)

We could also implement a click-to-enlarge function for figures, if that's helpful.

**Comment by AmarNathChary** [comment]
![Screenshot from 2023-11-24 09-12-00](https://github.com/kubernetes/website/assets/117257033/6962092e-e81a-49ef-a73c-310518508da4)
please find the image
The words in the image are hardly visible

**Comment by AmarNathChary** [comment]
> We could also implement a click-to-enlarge function for figures, if that's helpful.
I agree with your opinion this could be a good idea

**Comment by AmarNathChary** [comment]
Closing the issue as resolved
/close
