### ISSUE TITLE
Add concept page with overview of autoscaling

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44084]
**This is a Feature Request**

**What would you like to be added**
Within https://kubernetes.io/docs/concepts/workloads/, add a new and _brief_ page that has an overview of autoscaling. This means adding a new Markdown file.

The new page should mention:
- [HorizontalPodAutoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/)
- [VerticalPodAutoscaler](https://github.com/kubernetes/autoscaler/tree/9f87b78df0f1d6e142234bb32e8acbd71295585a/vertical-pod-autoscaler)
- [Cluster proportional autoscaler](https://github.com/kubernetes-sigs/cluster-proportional-autoscaler)

- [Karpenter](https://github.com/kubernetes-sigs/karpenter) (aim to make it clear that this is a thing that autoscales _nodes_, not Pods)
- [Cluster autoscaler](https://github.com/kubernetes/autoscaler/tree/9f87b78df0f1d6e142234bb32e8acbd71295585a/cluster-autoscaler) (aim to make it clear that this is a thing that autoscales _nodes_, not Pods)

Optionally, also mention:
- [KEDA](https://github.com/kedacore/keda) - **marked as third party software** as it's a separate project from Kubernetes
- [KNative autoscaler](https://knative.dev/docs/serving/autoscaling/) - **marked as third party software** as it's a separate project from Kubernetes

For this issue, all that's needed is a few words about each item. Later PRs could add more detail.

**Why is this needed**
- our documentation on autoscaling is incomplete
- readers would like to have their workloads automatically sized to match demand.

**Comments**
This helps with https://github.com/kubernetes/website/issues/4493
/language en
/kind feature

PS. I didn't mark this as a _good first issue_. However, if you're looking for something to work on, and haven't already contributed to Kubernetes' docs, there may be some issues available marked as good first issues. See this [issue query page](https://github.com/kubernetes/website/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).
If you have already worked on an issue, please leave these for people who are new to contributing.

**Comment by kumarankit999** [comment]
I would like to work on this issue @sftim 
/assign

**Comment by kumarankit999** [comment]
Should I Make a new file inside Workloads!!

**Comment by kumarankit999** [comment]
Should I Make a new file inside Workloads!!
In 1 PR I will be creating 2 topics like (HorizontalPodAutoscaler, 
VerticalPodAutoscaler) and will it be sufficient, because It will be taking 2-3 PR's!

**Comment by sftim** [comment]
For advice on how to contribute to the Kubernetes docs, please ask in #sig-docs on the Kubernetes Slack workspace. If you're not already a member of that workspace, you can visit https://slack.k8s.io/ for an invitation.

---

**Anyone is welcome to work on this issue.**

@kumarankit999 it's slightly unhelpful to assign an issue to yourself and also to ask questions about how to work on it; ideally, people only assign an issue once they are confident that they know how to resolve it.

**Comment by sftim** [comment]
Our no cookie-licking policy means that anyone is welcome to open a PR that closes an open issue. It's still friendly to reach out to people who might already be working on the same thing. 

See https://www.redhat.com/en/blog/dont-lick-cookie for an explanation of the jargon.

**Comment by kumarankit999** [comment]
Thanks @sftim, I was just asking it. I can fix this issue!

**Comment by professorabhay** [comment]
Hey @sftim! This has been pending for more than a month. So, May I go ahead and create a PR?
I have a basic markdown structure for `autoscaling.md` file is ready and I can add more details as needed after raising a PR.

**Comment by sftim** [comment]
PRs are welcome, and because this project is open source, nobody needs permission.

**Comment by sftim** [comment]
In light of our policy on cookie licking:
/unassign @kumarankit999

I think we'll make progress better without any assignee. If anyone wants to share that they have started work, feel free to open a draft pull request that mentions this issue.
