### ISSUE TITLE
Broken quick navigation link for Localization in README.md

### ISSUE THREAD

**Issue by rudrakshkarpe** [kubernetes/website#44080]
**This is a Bug Report**

**Problem:**
<img width="470" alt="image" src="https://github.com/kubernetes/website/assets/78851635/0c35ecab-0ad2-40cc-9ff9-9177ba3ac2ba">

[Localizations READMEs](https://github.com/kubernetes/website#localization-readmemds) quick navigation link is broken 

**Proposed Solution:**
It looks like it's due to a small typo. 

<img width="391" alt="image" src="https://github.com/kubernetes/website/assets/78851635/bd33f429-3ebe-42b3-8398-d6567b1aee90">

**Page to Update:**
https://github.com/kubernetes/website/blob/main/README.md

**Comment by kumarankit999** [comment]
Let's first the issue have the label triage accepted, then only work on this!!
