### ISSUE TITLE
Docs do not explain purpose of serviceAccount.secrets field

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#4410]
The following documentation do not provide enough information about what the `ServiceAccount.secrets` field is for:

- https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
- https://kubernetes.io/docs/admin/service-accounts-admin/
- https://kubernetes.io/docs/concepts/configuration/secret/#service-accounts-automatically-create-and-attach-secrets-with-api-credentials

The only piece of documentation appears on API reference: https://github.com/kubernetes/kubernetes/blob/04c4c212266f3426fc770580b9d791fcef2531bb/pkg/api/types.go#L2785:

> // Secrets is the list of secrets allowed to be used by pods running using this ServiceAccount

...but even this is confusing to me. It sounds like RBAC, but is it really? Having a bit of more info on the documentation would certainly help. I think this field is intended for some use case, though I don't think users can understand it easily right now.

/assign @bprashanth

**Comment by ahmetb** [comment]
Found a bit of information at https://github.com/kubernetes/kubernetes/blob/04c4c212266f3426fc770580b9d791fcef2531bb/plugin/pkg/admission/serviceaccount/admission.go#L309-L324. 

My deductions: 
- this field is used by the [ServiceAccount admission controller](https://kubernetes.io/docs/admin/admission-controllers/#serviceaccount)
- If a user is not making use of this admission controller, this field is a no-op
- the same functionality can be achieved with RBAC.

/cc @liggitt @deads2k if you can shed any light, or submit a small PR explaining this, I appreciate.

**Comment by deads2k** [comment]
> /cc @liggitt @deads2k if you can shed any light, or submit a small PR explaining this, I appreciate.

A service account can be used to provide a level of indirection when a system actor is performing an action on a user's behalf.  For instance, when a user creates an RC, the pod that finally gets created is created by the RC controller identity, not the user's identity.  If you want to be able to restrict things like PSP permissions, those permissions must be attached the SA, not the user, since the user information is gone at the time of pod creation.

**Comment by liggitt** [comment]
> the same functionality can be achieved with RBAC

The admission plugin uses the references in that field to determine which service account token secret to automount into pods.

**Comment by ahmetb** [comment]
@deads2k I guess your comment is a conceptual overview of service accounts (which is really helpful and I'm not sure if we explain it like this). But it doesn't explain what "secrets" field does, we lack that part of the documentation

@liggitt it seems like the token (which I suppose is `.secrets[0]`) is the only one that is auto-mounted. The rest of `.secrets` field is not auto-mounted at all (not implemented maybe).

**Comment by zacharysarah** [comment]
@ahmetb :wave: Do you think there's enough information here to be actionable for docs contributors?

**Comment by ahmetb** [comment]
@zacharysarah Not sure if docs contributors would be able to provide the required content. So I'm looking at folks above to provide authoritative information, and preferably a PR. 😉

**Comment by bitsofinfo** [comment]
no clue what this is either. The tekton docs utilize this but its not clear what the heck it is at all

**Comment by sftim** [comment]
Maybe I can add this detail into PR #16885 and have the other pages hyperlink there.

**Comment by Aut0R3V** [comment]
Can we close this issue then?

**Comment by sftim** [comment]
@ahmetb as I understand it, this request remains open and valid. Please respond if you feel that's not the case.

/triage accepted

**Comment by sftim** [comment]
https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/#ServiceAccount now _partly_ covers this.

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/security/service-accounts/ explains how that field is now a legacy detail.

On that basis, I'll close this issue.

/close
