### ISSUE TITLE
[hi] Duplicate instruction in Hindi README-hi.md

### ISSUE THREAD

**Issue by ankur0904** [kubernetes/website#44120]
**This is a Bug Report**

**Problem:**  This line present [here](https://github.com/kubernetes/website/blob/main/README-hi.md?plain=1#L40)

> यदि आप डॉकर के बिना स्थानीय रूप से वेबसाइट चलाना पसंद करते हैं, तो नीचे Hugo का उपयोग करके स्थानीय रूप से साइट चलाना देखें।

is same as 

यदि आप डॉकर के बिना स्थानीय रूप से वेबसाइट चलाना पसंद करते हैं, तो नीचे दिए गए Hugo का उपयोग करके स्थानीय रूप से [साइट को चलाने](#hugo-का-उपयोग-करते-हुए-स्थानीय-रूप-से-साइट-चलाना) का तरीका देखें। 

which is also present in the [same place 
](https://github.com/kubernetes/website/blob/main/README-hi.md?plain=1#L42)

**Page to Update:**
https://github.com/kubernetes/website/blob/main/README-hi.md

**Comment by dipesh-rawat** [comment]
/retitle [hi] Duplicate instruction in Hindi README-hi.md
/language hi
