### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/cpu-memory-limit/

### ISSUE THREAD

**Issue by akanso** [kubernetes/website#44125]
this link is not functioning, returns 404 not found.

https://k8s.io/docs/tasks/configure-pod-container/limits.yaml

**Comment by dipesh-rawat** [comment]
@akanso Could please confirm the you are looking at the latest documentation in the webpage https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/?

Can you kindly pinpoint the location on the specified page where you came across the link "https://k8s.io/docs/tasks/configure-pod-container/limits.yaml"? I've checked from my end and couldn't locate it. Any pointers on its exact location on the page would be much appreciated!

/triage needs-information

**Comment by akanso** [comment]
I was actually not looking at official documentation. We can close this issue.

I was looking at:
https://pwittrock.github.io/docs/tasks/administer-cluster/cpu-memory-limit/

Instead of: https://k8s.io ....

Weirdly, the linked to report issues is linked to this Github repo...
