### ISSUE TITLE
[ko] 'Hello Minikube' page is outdated

### ISSUE THREAD

**Issue by jman-krafton** [kubernetes/website#44131]
Katacoda가 중단된 것 같은데 업데이트 해야 하지 않을까요. 영문판에서는 반영이 된 것으로 보여서요.

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/ko/docs/tutorials/hello-minikube/

**Comment by dipesh-rawat** [comment]
@jman-krafton Kindly raise the issue using English to ensure clarity for contributors, as this project primarily operates in English. 
If needed, feel free to utilize machine translation from your native language to describe the issue, even when reporting inaccuracies in a localized page. This will enhance communication and collaboration within the community.

/triage needs-information

**Comment by aj11anuj** [comment]
Translation -
Katacoda seems to be discontinued. Shouldn't it be updated?  It seems to have been reflected in the English version.

**Comment by aj11anuj** [comment]
Page is outdated and isn't in sync with the main website. There are many pages of each localization where there is some mis-matchment of content because of being outdated.

**Comment by jihoon-seo** [comment]
/retitle [ko] 'Hello Minikube' page is outdated

@jman-krafton 안녕하세요~
네 해당 페이지는 outdated 되어, 이슈 #41613 에서 제보되었고,
PR #41951 에서 `dev-1.27-ko.1` 브랜치에 업데이트 하였습니다.
나중에 `dev-1.27-ko.1` 브랜치가 `main` 브랜치에 머지되면, 업데이트된 사항을 확인하실 수 있을 것입니다.

다만 현재 한국어 현지화 작업이 상당히 지연되고 있으며,
기존의 Git 을 이용한 현지화 방식에서 현지화 도구를 이용하는 방식으로의 전환을 위한 테스트도 예정되어 있어
이로 인해서도 반영이 상당히 지연될 수도 있을 것 같습니다.
양해를 부탁드립니다.

lang/ko 이슈들의 triage를 정리해 달라는 요청이 있어서, 이 이슈는 close 하겠습니다~~

/triage duplicate
/close

**Comment by jman-9** [comment]
> @jman-krafton Kindly raise the issue using English to ensure clarity for contributors, as this project primarily operates in English. If needed, feel free to utilize machine translation from your native language to describe the issue, even when reporting inaccuracies in a localized page. This will enhance communication and collaboration within the community.
> 
> /triage needs-information

I missed it. If needed more questions, I'll comment them in English.

**Comment by jman-9** [comment]
> /retitle [ko] 'Hello Minikube' page is outdated
> 
> @jman-krafton 안녕하세요~ 네 해당 페이지는 outdated 되어, 이슈 #41613 에서 제보되었고, PR #41951 에서 `dev-1.27-ko.1` 브랜치에 업데이트 하였습니다. 나중에 `dev-1.27-ko.1` 브랜치가 `main` 브랜치에 머지되면, 업데이트된 사항을 확인하실 수 있을 것입니다.
> 
> 다만 현재 한국어 현지화 작업이 상당히 지연되고 있으며, 기존의 Git 을 이용한 현지화 방식에서 현지화 도구를 이용하는 방식으로의 전환을 위한 테스트도 예정되어 있어 이로 인해서도 반영이 상당히 지연될 수도 있을 것 같습니다. 양해를 부탁드립니다.
> 
> lang/ko 이슈들의 triage를 정리해 달라는 요청이 있어서, 이 이슈는 close 하겠습니다~~
> 
> /triage duplicate /close

이슈가 추적되고 있다고 생각하지 않았는데 기쁘군요. 감사합니다 :)
