### ISSUE TITLE
Using RBAC Authorization

### ISSUE THREAD

**Issue by Takapiwanashe** [kubernetes/website#44132]
I am a kubernetes novice so i was going throught the documentation and

From the documentation at [rbac](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) it says that:

**ClusterRoles** have several uses. You can use a **ClusterRole** to:

1. define permissions on namespaced resources and be granted access within individual namespace(s)
2. define permissions on namespaced resources and be granted access across all namespaces
3. define permissions on cluster-scoped resources

I am a bit confused on point 1 and 2 be cause the definations say

A **Role** always sets permissions within a particular [namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces); when you create a Role, you have to specify the namespace it belongs in.

**ClusterRole**, by contrast, is a **non-namespaced** resource. The resources have different names (Role and ClusterRole) because a Kubernetes object always has to be either namespaced or not namespaced; it can't be both.

May someone please clarify point 1 and 2

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by thisisharrsh** [comment]
ClusterRoles provides a flexible mechanism for defining and granting permissions across namespaces, but on the other hand ClusterRoleBinding act as a bridge between ClusterRoles and specific namespaces.

**Comment by thisisharrsh** [comment]
You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

These places are better to resolve support queries fast.
