### ISSUE TITLE
Certificate commonName mismatch for `kubernetes-ca` on the "PKI certificates and requirements" page

### ISSUE THREAD

**Issue by able8** [kubernetes/website#44136]
On https://kubernetes.io/docs/setup/best-practices/certificates/
The default CN "kubernetes-ca"  and "kubernetes-front-proxy-ca" are incorrect. 
We should replace  "kubernetes-ca" with "kubernetes", and "kubernetes-front-proxy-ca" with "front-proxy-ca".

Evidences:
1.  Check the certs on KinD: 
```
root@kind-control-plane:/etc/kubernetes/pki# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3",  ....

root@kind-control-plane:/etc/kubernetes/pki# for i in $(ls *.crt); do echo -n "$i, " ; openssl x509  -subject -noout -in $i; done
apiserver-etcd-client.crt, subject=O = system:masters, CN = kube-apiserver-etcd-client
apiserver-kubelet-client.crt, subject=O = system:masters, CN = kube-apiserver-kubelet-client
apiserver.crt, subject=CN = kube-apiserver
front-proxy-client.crt, subject=CN = front-proxy-client

ca.crt, subject=CN = kubernetes
front-proxy-ca.crt, subject=CN = front-proxy-ca
```

2. Check K8s source code:
https://github.com/kubernetes/kubernetes/blob/a8f6ea24209b332217f7baa7c14248e8d0266d28/cmd/kubeadm/app/phases/certs/certlist.go#L251

```
// KubeadmCertRootCA is the definition of the Kubernetes Root CA for the API Server and kubelet.
func KubeadmCertRootCA() *KubeadmCert {
	return &KubeadmCert{
		Name:     "ca",
		LongName: "self-signed Kubernetes CA to provision identities for other Kubernetes components",
		BaseName: kubeadmconstants.CACertAndKeyBaseName,
		config: pkiutil.CertConfig{
			Config: certutil.Config{
				CommonName: "kubernetes",
			},
		},
	}
}


// KubeadmCertFrontProxyCA is the definition of the CA used for the front end proxy.
func KubeadmCertFrontProxyCA() *KubeadmCert {
	return &KubeadmCert{
		Name:     "front-proxy-ca",
		LongName: "self-signed CA to provision identities for front proxy",
		BaseName: kubeadmconstants.FrontProxyCACertAndKeyBaseName,
		config: pkiutil.CertConfig{
			Config: certutil.Config{
				CommonName: "front-proxy-ca",
			},
		},
	}
}

```

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/setup/best-practices/certificates/

**Comment by sftim** [comment]
/priority awaiting-more-evidence

Why is this page _wrong_ &ndash; as opposed to different from how particular cluster management tools do it?

**Comment by sftim** [comment]
/retitle Certificate canonical mismatch for `kubernetes-ca` on the "PKI certificates and requirements" page
/remove-kind bug
/kind cleanup
/approve
/priority backlog
/remove-priority awaiting-more-evidence

/remove-sig security

**Comment by sftim** [comment]
Oops.
/retitle Certificate commonName mismatch for `kubernetes-ca` on the "PKI certificates and requirements" page

**Comment by neolit123** [comment]
/close

closing. there was never a plan to make kubeadm follow the page exactly or the page to follow kubeadm.
also the diff in CNs is not blocking.
