### ISSUE TITLE
Need help: Pod not executing as expected with 'sleep' command in YAML

### ISSUE THREAD

**Issue by sirisha999** [kubernetes/website#44143]
command: ["sleep"]
        args: ["infinity"],
adding above lines in kubernates yaml to keep pod not to terminate is stopping the pod to execute even once
no logs are getting printed,if i remove the above lines logs will print ,but since execution is completed pod is terminating,but its again restarting,my expectation is to make it run only once

**Comment by dipesh-rawat** [comment]
/retitle Need help: Pod not executing as expected with 'sleep' command in YAML

**Comment by dipesh-rawat** [comment]
This appears to be a request for assistance.

If you're seeking help, consider consulting [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

Alternatively, feel free to share your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

Please be aware that GitHub issue tracker might not be the appropriate platform for support requests.

/kind support

**Comment by niranjandarshann** [comment]
Hi @sirisha999, If  you want to run pod only once the in `spec` of yaml file you can add `restartpolicy: never` it will work for you as it execute once and never be executed again.

**Comment by divya-mohan0209** [comment]
Hello @sirisha999 , as noted above the documentation website repo is not the place for support questions. However, if there is any improvement in the docs that you want to suggest, we'd be happy to address them over an issue. Kindly use the forums mentioned in the above response for support-related queries.
/close
