### ISSUE TITLE
[hi]: broken link in "hello-minikube" page

### ISSUE THREAD

**Issue by ankur0904** [kubernetes/website#44147]
**Problem:** There are broken link in [this](https://kubernetes.io/hi/docs/tutorials/hello-minikube/#%E0%A4%A1-%E0%A4%AA-%E0%A4%B2-%E0%A4%AF%E0%A4%AE-%E0%A4%9F-%E0%A4%AC%E0%A4%A8-%E0%A4%8F) page.
1. https://kubernetes.io/hi/docs/concepts/workloads/pods/
2. https://kubernetes.io/hi/docs/concepts/workloads/controllers/deployment/

**Proposed Solution:**
`https://kubernetes.io/hi/docs/concepts/workloads/pods/` -> `https://kubernetes.io/docs/concepts/workloads/pods/`
`https://kubernetes.io/hi/docs/concepts/workloads/controllers/deployment/` -> `https://kubernetes.io/docs/concepts/workloads/controllers/deployment/`

**Page to Update:**
https://kubernetes.io/hi/docs/tutorials/hello-minikube/

**Comment by Rajdeep1311** [comment]
Is the issue still open, anyone working?

**Comment by kumarankit999** [comment]
Yes, I'm working on it!!

**Comment by kumarankit999** [comment]
I think @ankur0904, has already raised a PR!

**Comment by T-Lakshmi** [comment]
PR working on this issue #44148
