### ISSUE TITLE
Ambiguous and unclear instructions in "kubeadm join" guide for handling missing ca.key file

### ISSUE THREAD

**Issue by zogness** [kubernetes/website#44142]
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

"If your cluster does not have the ca.key file, you must sign the embedded certificates in the kubelet.conf _externally_."
Externally? Huh?

"Copy the resulting kubelet.conf to /etc/kubernetes/kubelet.conf on the new node."

Resulting from what, pray tell? What wrote this kubelet.conf file?

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Ambiguous and unclear instructions in "kubeadm join" guide for handling missing ca.key file

**Comment by dipesh-rawat** [comment]
/retitle Ambiguous and unclear instructions in "kubeadm join" guide for handling missing ca.key file

**Comment by neolit123** [comment]
> https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
> 
> "If your cluster does not have the ca.key file, you must sign the embedded certificates in the kubelet.conf _externally_." Externally? Huh?

this sentence can link to this page:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#external-ca-mode
and this section about external CA:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#external-ca-mode

/help

**Comment by sftim** [comment]
@neolit123 you should only add “help wanted” to issues that are well defined and have been accepted. Did you want to accept this?

**Comment by vaibhav2107** [comment]
Hi @SwathiR03 Are you still working on this issue

**Comment by SwathiR03** [comment]
Not really! Feel free to assign yourself to the issue if you're interested
