### ISSUE TITLE
[zh] shortcode `Note` in a list with HTML comments is rendered incorrectly

### ISSUE THREAD

**Issue by 1000Delta** [kubernetes/website#44163]
**This is a Bug Report**

**Problem:**

Shortcode `{{< note >}}` (also Caution, Warning) cannot rendered correctly as a markdown content in list
when the shortcode range contains HTML comment.

Example:

```markdown
1. 带嵌套 note 的第二个条目

    {{< note >}}
    <!--
    Warning, Caution, and Note shortcodes, embedded in lists, need to be indented four spaces. See [Common Shortcode Issues](#common-shortcode-issues).
    -->
    警告、小心和注释短代码可以嵌套在列表中，但是要缩进四个空格。
    参见[常见短代码问题](#common-shortcode-issues)。
    {{< /note >}}
```

See [Preview](https://kubernetes.io/zh-cn/docs/contribute/style/style-guide/#note), content in `note` block rendered to a `<pre>` element, not markdown format, especially if it contains link, it can't be use.

I'm not sure why this occured, It may need to check how Hugo convert markdown with HTML comments to HTML format.

I only have some solution to avoid this issue. 

---

**Proposed Solution:**

1. Move the HTML comments out of the shortcode, and **MUST** separate comments and shortcode by blank line.

    ```markdown
    1. 带嵌套 note 的第二个条目
    
        <!--
        Warning, Caution, and Note shortcodes, embedded in lists, need to be indented four spaces. See [Common Shortcode Issues](#common-shortcode-issues).
        -->
        
        {{< note >}}
        警告、小心和注释短代码可以嵌套在列表中，但是要缩进四个空格。
        参见[常见短代码问题](#common-shortcode-issues)。
        {{< /note >}}
    ```
    
    If you not set a blank line, the shortcode block will be included in a `<pre>` element, this will make the font style (and others style) incorrectly, preview wrong content:
    
    <img width="650" alt="image" src="https://github.com/kubernetes/website/assets/30397170/6b12a853-655c-474b-b0c4-184a24fe33de">

2. Don't use 4 spaces before the shortcode block in a list

    Remove a space before the code, it will be fine.

    IMO, this will make the content no longer identified as a code block in markdown.

    But in this case, it will make the example and code inconsistently, so I prefer to use the first solution.

**Page to Update:**

https://kubernetes.io/zh-cn/docs/contribute/style/style-guide

**Comment by vaibhav2107** [comment]
I think this issue is fixed by the PR #44164 and hence can be closed
