### ISSUE TITLE
Unclear wording in “DNS for Services and Pods” page

### ISSUE THREAD

**Issue by aceeric** [kubernetes/website#44178]
This is a suggestion regarding: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

Specifically (emphasis added):

> "Default": The Pod inherits the name resolution configuration from the **node** that the Pods run on

This is a truly minor observation that recognizes that the word "node" is often used to refer to a machine (either bare metal or virtualized) in a clustered (i.e. networked) enviroment.

A node is a _also_ Kubernetes abstraction. I think what the documentation is saying is that _The Pod inherits the name resolution configuration from the **underlying host** that the Pods run on._ In other words, when you're trying to understand DNS for the first time, the language leads you to believe that the Kubernetes _node_ knows something about name resolution which I don't think is correct. If I am right, then it seems clearer to avoid the overloaded term _node_ here.

There _could_ be a convention in the k8s docs that lower _node_ refers to host and upper _Node_ refers to the Kubernetes abstraction but I don't see that used in the docs...

**Comment by sftim** [comment]
> There could be a convention in the k8s docs that lower node refers to host and upper Node refers to the Kubernetes abstraction

Yes, there is.

**Comment by sftim** [comment]
(A Node is an API object representing a node)

**Comment by sftim** [comment]
My opinion: we need a way to help readers know that, within Kubernetes docs, “node” means what @aceeric is using ”underlying host” to mean. If the node is a VM then we do _not_ mean the DNS resolver configuration comes from  physical server that is providing virtualization.

I'm not keen on the proposed switch to “underlying host”, though.

---

The whole entry:
> "Default": The Pod inherits the name resolution configuration from the node that the Pods run on. See [related discussion](https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers) for more details.

is misleading in a few ways, as is https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

A more thorough review and revision would be ideal.

**Comment by sftim** [comment]
/retitle Unclear wording in “DNS for Services and Pods” page
