### ISSUE TITLE
Different Font/Font-size in the right side menu items

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#44171]
**This is a Bug Report**
Font/Font-size of the right side menu items are different that other pages.
_**Resource Types**_ menu items in the **auto generated** pages has different font than other pages

**Problem:**

**Proposed Solution:**

**Page to Update:**
All auto generated pages of https://kubernetes.io/docs/reference/config-api/

_Sample_
![image](https://github.com/kubernetes/website/assets/20103020/f96aa115-80ed-47ae-a17a-473287bb9813)

**Comment by tamilselvan1102** [comment]
Evidence
![image](https://github.com/kubernetes/website/assets/20103020/b8d68b64-4642-4d93-be1c-90889a263e08)

**Comment by sftim** [comment]
The font is different because these are monospaced in the main content.
/priority awaiting-more-evidence

**Comment by Gauravpadam** [comment]
The label styling is inherited from website assets, I don't see much to fix here

**Comment by tamilselvan1102** [comment]
Normal pages
![image](https://github.com/kubernetes/website/assets/20103020/95096dc3-5779-4a38-bdf5-d582ecf30488)

**Comment by sftim** [comment]
Maybe we should change (reset) the font-size for `code` when it's in the sidebar? Eg, set it to `inherit`.

**Comment by tamilselvan1102** [comment]
if we do following changes in the `code`, it will become same as normal page But we have to investigate impact of changing the `code ` style.
![image](https://github.com/kubernetes/website/assets/20103020/186d61ae-c3bc-47a0-bb6c-cf63898487a2)

**Comment by tamilselvan1102** [comment]
@sftim 
i am not knowing the file/script where the autogeneration logic is written. if you know the path please share me, i will edit it.

**Comment by sftim** [comment]
I'm afraid I don't know this either (I think I could maybe work it out, but I don't plan to prioritise doing that task).

However, see https://github.com/kubernetes/website/issues/44171#issuecomment-1838407434 for the approach I recommend. You can make that change without changing the generator.
