### ISSUE TITLE
[zh-cn] Fix typo in replicalimit-param.yaml

### ISSUE THREAD

**Issue by kundan2707** [kubernetes/website#44192]
**This is a Bug Report**

**Problem:**
Spelling of namespace in wrong
**Proposed Solution:**
It should be correct
**Page to Update:**
https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/validating-admission-policy/

**Comment by kundan2707** [comment]
file to update:
https://github.com/kubernetes/website/blob/main/content/zh-cn/examples/validatingadmissionpolicy/replicalimit-param.yaml

**Comment by dipesh-rawat** [comment]
Fix by PR https://github.com/kubernetes/website/pull/44193

/close
