### ISSUE TITLE
The word 'values' is displayed with partial highlighting in "Taints and Tolerations" page

### ISSUE THREAD

**Issue by AdamhDiaz** [kubernetes/website#44209]
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

![image](https://github.com/kubernetes/website/assets/2846612/28d8ea18-7441-412d-8f22-6ef0f343efad)

the word "values" is displayed as "value" "s" and only the word "value" is highlighted. I think it was probably intended that the whole word "vaules" be displayed in bold or gray text.

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
/language en

**Comment by sftim** [comment]
> I think it was probably intended that the whole word "vaules" be displayed in bold or gray text.

My guess is: the author meant to have `value` in monospace, but didn't spot how jarring “`value`s” is when you read it

/language en

If my guess is right then it's not really a _bug_, more an opportunity to make the page more readable.

**Comment by dipesh-rawat** [comment]
/retitle The word 'values' is displayed with partial highlighting in "Taints and Tolerations" page

**Comment by sftim** [comment]
(when the text in question was [added](https://github.com/kubernetes/website/pull/2774), the fonts and styling may have been quite different)

**Comment by steve-hardman** [comment]
I will try to help and suggest changes via PR to make this more readable.
/assign

**Comment by satyampsoni** [comment]
@steve-hardman are you working on it?

**Comment by dipesh-rawat** [comment]
Looks like a fix was merged as part of https://github.com/kubernetes/website/pull/44539

/close
