### ISSUE TITLE
Use etcdutl instead of etcdctl for restoring an etcd cluster

### ISSUE THREAD

**Issue by adityasamant25** [kubernetes/website#44216]
**This is a Bug Report**

**Problem:**
This issue refers to the page
Kubernetes Documentation > Tasks > Administer a Cluster > Operating etcd clusters for Kubernetes
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

In the section titled "Restoring an etcd cluster", the commands use the `etcdctl` utility to restore from an existing snapshot.
Using `etcdctl` for restoring snapshots is deprecated since etcd version 3.5.x
Usage of this command displays a deprecation warning and suggests to use `etcdutl` utility instead as shown below.

```
ubuntu@kubemaster:~$ etcdctl version
etcdctl version: 3.5.10
API version: 3.5
ubuntu@kubemaster:~$ ETCDCTL_API=3 etcdctl --endpoints 10.2.0.9:2379 snapshot restore snapshot.db
Deprecated: Use `etcdutl snapshot restore` instead.
```

I feel this change is necessary as the etcd official documentation has already changed to reflect the use of the `etcdutl` utility, as can be seen in the etcd documentation referenced in this section - https://etcd.io/docs/v3.6/op-guide/recovery/#restoring-a-cluster.

**Proposed Solution:**
I have raised a PR to depict the use of the `etcdutl` utility for restoring from an existing snapshot.
https://github.com/kubernetes/website/pull/44050 

Before submitting the PR, I have tested the changes on a local Kubernetes cluster for v1.28.0 and I can confirm everything works as expected.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

Kubernetes Version: 1.28.x and above

**Comment by adityasamant25** [comment]
//assign

**Comment by dipesh-rawat** [comment]
/retitle Use etcdutl instead of etcdctl for restoring an etcd cluster
/language en

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/46757
