### ISSUE TITLE
Broken image url in Example: Deploying PHP Guestbook application with Redis

### ISSUE THREAD

**Issue by zhuzzz** [kubernetes/website#44230]
The image used in frontend deployment should be `us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5` instead of `gcr.io/google_samples/gb-frontend:v5`

gcr one failed with this error `Error response from daemon: manifest for gcr.io/google_samples/gb-frontend:v5 not found: manifest unknown: Failed to fetch "v5" from request "/v2/google_samples/gb-frontend/manifests/v5".`

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

**Comment by thisisharrsh** [comment]
same as: https://github.com/kubernetes/website/issues/44224

**Comment by thisisharrsh** [comment]
Same as: https://github.com/kubernetes/website/issues/44224
/triage duplicate

**Comment by divya-mohan0209** [comment]
Closing this issue as a duplicate, since there are two other issues in the queue reporting it already -  #44190 and #44224
/close
