### ISSUE TITLE
Write new task pages about creating Kubernetes nodes

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#44248]
**_Please note:_ This issue is not suitable for new contributors since you need some familiarity with how Kubernetes works.**

### Problem statement

The Kubernetes website currently lacks a guide on creating Windows/Linux nodes. See [this issue](https://github.com/kubernetes/website/issues/37266) for more details. SIG Windows opted to remove the guide that did exist for creating Windows nodes, in PR https://github.com/kubernetes/website/pull/33324

### Proposed solution

Write a **new** task page about creating nodes for all operating systems. This could, potentially, be in a tabbed format as @sftim mentions in the issue referenced above. We would also need the entry reflected on the [index page](https://kubernetes.io/docs/tasks/administer-cluster/)

#### Proposed plan for a PR

- creates the Linux task page by moving / refactoring the existing "join node" contents from the "create a cluster" page:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes
- creates the Windows task page by taking the content from https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md
- at the end of the Windows page we add note/disclaimer whatever that says that CNI on Windows needs special handling and we link to the various CNI choices at:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md#networking-configuration
- adds tabs in the https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#join-nodes to choose between OS for joining nodes.

/priority backlog
/help

**Comment by sftim** [comment]
/triage accepted
Thank you for filing this @divya-mohan0209

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/45074

**Comment by vaibhav2107** [comment]
@Anuragt1104 Are you still working on this issue?

**Comment by neolit123** [comment]
/assign
sending PR soon.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/issues/37266

**Comment by sftim** [comment]
/retitle Write new task pages about creating Kubernetes nodes
