### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/guestbook/

### ISSUE THREAD

**Issue by wildcardlinux** [kubernetes/website#44254]
The frontend-deployment.yaml has an issue because I don't think that image exists anymore.

NAME                        READY   STATUS             RESTARTS   AGE
frontend-697bd54cd4-5bkqq   0/1     ImagePullBackOff   0          10s
frontend-697bd54cd4-n6l8c   0/1     ImagePullBackOff   0          10s
frontend-697bd54cd4-pmk5n   0/1     ImagePullBackOff   0          10s

You can check the container registry:

https://console.cloud.google.com/gcr/images/google-samples/global/gb-frontend

**Comment by sftim** [comment]
This looks similar to issue https://github.com/kubernetes/website/issues/44190. I think it is a duplicate.

/triage duplicate

**Comment by Shubham82** [comment]
Closing this issue, as it is resolved by PR #44290
