### ISSUE TITLE
Feature Gates - About enabled in beta version

### ISSUE THREAD

**Issue by jungjuyoung2023** [kubernetes/website#44269]
If the beta is a cluster version in True, do I not have to enable it? I can't check it in the configuration file.

If I have to enable it, should I apply it to all control planes, woker nodes?
ex) kubelet.env , kube-apiserver.yaml , kube-controller-manager.yaml kube-scheduler.yaml

**Comment by AmarNathChary** [comment]
Opps
/remove-language en
/language ko

**Comment by AmarNathChary** [comment]
**_Page related to the issue_** : https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by jungjuyoung2023** [comment]
I am using v1.21 version
ExpandInUsePersistentVolumes appears to have been removed from 1.26
In this case, can I do resizing online without enabling ExpandInUsePersistentVolumes in my version?

<img width="749" alt="스크린샷 2023-12-08 오후 2 55 07" src="https://github.com/kubernetes/website/assets/129713013/986c239a-94da-4762-8944-26992ccdf583">

<img width="595" alt="스크린샷 2023-12-08 오후 2 56 04" src="https://github.com/kubernetes/website/assets/129713013/c8dad1c0-46c0-4c72-8e9d-6f1cdf9c5de5">
<img width="643" alt="스크린샷 2023-12-08 오후 2 56 37" src="https://github.com/kubernetes/website/assets/129713013/19048310-54fe-4431-aaba-ee88535f5bc8">

**Comment by sftim** [comment]
/remove-language ko
(question is in English)

/kind support

You could change this into a suggestion about improving the documentation @jungjuyoung2023; right now, it looks like a request for advice.

**Comment by sftim** [comment]
Are you perhaps unsure what the _default_ setting is for some feature gates?

**Comment by jungjuyoung2023** [comment]
Yes ExpandInUsePersistentVolumes is true in beta, but I can't check it in cluster yaml, so I want to check if it's default enabled

**Comment by aj11anuj** [comment]
@jungjuyoung2023 resolving support/query related issues on K8s github repo sometimes take months and months due to large volume of Issue and PR's we get. It is recommended for query and support related issues, reach out to [Kubernetes slack](https://communityinviter.com/apps/kubernetes/community) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum for faster resolution.

/close not-planned
