### ISSUE TITLE
Remove duplicated wording reference to Docker Engine's legacy container links

### ISSUE THREAD

**Issue by dancer1325** [kubernetes/website#44272]
**This is a Bug Report**
Remove duplicated wording reference to Docker Engine's legacy container links in the [service page](https://kubernetes.io/docs/concepts/services-networking/service/) under the section [environment variables](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables)

**Problem:**
Duplicated wording reference about the possibility to add variables compatible with Docker Engine's legacy container links feature

> It also supports variables (see [makeLinkVariables](https://github.com/kubernetes/kubernetes/blob/dd2d12f6dc0e654c15d5db57a5f9f6ba61192726/pkg/kubelet/envvars/envvars.go#L72)) that are compatible with Docker Engine's "[legacy container links](https://docs.docker.com/network/links/)" feature.

And after Note commentary ...

> Kubernetes also supports and provides variables that are compatible with Docker Engine's "[legacy container links](https://docs.docker.com/network/links/)" feature. You can read [makeLinkVariables](https://github.com/kubernetes/kubernetes/blob/dd2d12f6dc0e654c15d5db57a5f9f6ba61192726/pkg/kubelet/envvars/envvars.go#L72) to see how this is implemented in Kubernetes.

**Proposed Solution:**
Leave just 1

"Kubernetes also supports and provides variables that are compatible with Docker Engine's "[legacy container links](https://docs.docker.com/network/links/)" feature. You can read [makeLinkVariables](https://github.com/kubernetes/kubernetes/blob/dd2d12f6dc0e654c15d5db57a5f9f6ba61192726/pkg/kubelet/envvars/envvars.go#L72) to see how this is implemented in Kubernetes."

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/service/

**Comment by sftim** [comment]
Whilst reviewing https://github.com/kubernetes/website/pull/44274, I concluded that this issue report isn't correctly reporting an actual bug. Kubernetes _does_ support two kinds of environment variables that help you to discover Services.

/priority awaiting-more-evidence

**Comment by dancer1325** [comment]
> Whilst reviewing #44274, I concluded that this issue report isn't correctly reporting an actual bug. Kubernetes _does_ support two kinds of environment variables that help you to discover Services.

Then, @sftim , 

- 

> It also supports variables (see [makeLinkVariables](https://github.com/kubernetes/kubernetes/blob/dd2d12f6dc0e654c15d5db57a5f9f6ba61192726/pkg/kubelet/envvars/envvars.go#L72)) that are compatible with Docker Engine's "[legacy container links](https://docs.docker.com/network/links/)" feature.

and 

> Kubernetes also supports and provides variables that are compatible with Docker Engine's "[legacy container links](https://docs.docker.com/network/links/)" feature. You can read [makeLinkVariables](https://github.com/kubernetes/kubernetes/blob/dd2d12f6dc0e654c15d5db57a5f9f6ba61192726/pkg/kubelet/envvars/envvars.go#L72) to see how this is implemented in Kubernetes.

refer to different topics?

- [Here](https://github.com/kubernetes/website/blob/a2cb17e4cf4d7fdb7d84dba575f2e5b1368103f9/content/en/docs/concepts/services-networking/service.md) just 1 commentary about it, and in [thisPR](https://github.com/kubernetes/website/pull/38563), although it's [indicated](https://github.com/kubernetes/website/pull/38563#discussion_r1052663539) the section that nothing new, the fragment

> Kubernetes also supports and provides variables that are compatible with Docker Engine's "[legacy container links](https://docs.docker.com/network/links/)" feature. You can read [makeLinkVariables](https://github.com/kubernetes/kubernetes/blob/dd2d12f6dc0e654c15d5db57a5f9f6ba61192726/pkg/kubelet/envvars/envvars.go#L72) to see how this is implemented in Kubernetes.

is added --> Isn't it redundant ?

**Comment by sftim** [comment]
Ah OK. So this is a genuine issue, but I think the proposed fix may be wrong.

/triage accepted
/remove-priority awaiting-more-evidence
/priority backlog
/kind bug

**Comment by dancer1325** [comment]
Thanks @sftim 

I close this issue, since the PR was already merged! 🚀
