### ISSUE TITLE
Tutorial "Using kubectl to Create a Deployment" not working on ARM architecture cluster

### ISSUE THREAD

**Issue by tszebeni** [kubernetes/website#44271]
The tutorial found at https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/ leads to error on ARM cluster.
The deployment state is CrashLoopBackOff and logs mention exec /bin/sh: exec format error.
After checking https://cloud.google.com/kubernetes-engine/docs/troubleshooting/troubleshooting-arm-workloads the error indicates the deployment has a container image which does not support ARM architecture.

**Comment by sftim** [comment]
A quick fix: document that the tutorial required AMD64 architecture.

Then we can track a longer-term issue to support a more diverse set of CPU instruction sets.

**Comment by sftim** [comment]
/kind bug

It's a bug because the page doesn't tell you about this prerequisite.

**Comment by adityasamant25** [comment]
This is correct that the image will not work on ARM.

However, the links to create a first cluster mention to use Minikube.
[Using Minikube to Create a Cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/)
[Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube/)

If Minikube is used with the Docker Desktop as the driver, then Docker Desktop has the emulation in place for running AMD64 images on ARM architecture and the deployment will work just fine.

Maybe it just needs to be highlighted clearly to use Minikube with Docker Desktop driver as a pre-requisite.

**Comment by wradstok** [comment]
Thanks for the suggestions all. I was indeed not using docker desktop as a driver but colima.

**Comment by fwilhe** [comment]
> Maybe it just needs to be highlighted clearly to use Minikube with Docker Desktop driver as a pre-requisite.

Really? Building container images with multiple architectures is not that hard and with Apple Silicon it is becoming increasingly likely that people will run clusters on arm without intel emulation, also arm gained some traction in server environments in the last years. I think it would be good if the images described in the tutorial would work natively both on amd and on arm.
