### ISSUE TITLE
Example: Deploying PHP Guestbook application with Redis

### ISSUE THREAD

**Issue by reenen** [kubernetes/website#44277]
The image file download for the frontend-deployment.yaml is currently failing. I fixed by changing it to:
image:  us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5

**Comment by dipesh-rawat** [comment]
This looks similar to issue(s) https://github.com/kubernetes/website/issues/44190 and https://github.com/kubernetes/website/issues/44224. I think it is a duplicate.

/triage duplicate

**Comment by sftim** [comment]
Fixes are welcome; please visit https://github.com/kubernetes/website/issues/44190 to discuss and track that work.

**Comment by Shubham82** [comment]
Closing this issue, resolved  by PR #44290
