### ISSUE TITLE
Wrong feature state shown for TopologyManager

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/website#44294]
**This is a Bug Report**

**Problem:**

The `FEATURE STATE` of `TopologyManager` is mentioned `Kubernetes 1.18 [beta]` under [Node topology](https://kubernetes.io/docs/concepts/architecture/nodes/#node-topology), which is wrong, As per mention in the [Fetature Gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features) the correct Feature state for `TopologyManager` is `Kubernetes 1.27 [stable]`.

Here is Upstream PR for it: [#116093](https://github.com/kubernetes/kubernetes/pull/116093)

**Proposed Solution:**

Change the Feature State of `TopologyManager` from `Kubernetes 1.18 [beta]` to `Kubernetes 1.27 [stable]`.

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/nodes/

**Comment by sftim** [comment]
/retitle Wrong feature state shown for TopologyManager
