### ISSUE TITLE
Freeze k/website for Kubernetes v1.29 release

### ISSUE THREAD

**Issue by katcosgrove** [kubernetes/website#44306]
This issue freezes the k/website repository for the Kubernetes v1.29 release.

The release is scheduled for Wednesday, 13 December 2023 and no PRs are allowed to merge until the release PR has successfully merged.

If there are any questions, please contact me or anyone from the 1.29 Release Docs team.

cc: 1.29 Docs Team: Kat Cosgrove ([@katcosgrove](https://github.com/katcosgrove) / Slack: katcosgrove) Drew Hagen ([@drewhagen](https://github.com/drewhagen) / Slack: Drew Hagen), Harshita Sao ([@harshitasao](https://github.com/harshitasao) / Slack: Harshita Sao), Oluebube Princess Egbuna (@[Princesso](https://github.com/Princesso) / Slack: Bube), Tania Duggal ([@taniaduggal](https://github.com/taniaduggal) / Slack: taniaduggal)

/milestone 1.29
/sig release
/label tide/merge-blocker

**Comment by bube** [comment]
FYI @katcosgrove, the slack tags link to github accounts and made me a participant in this PR (including email notifications)
