### ISSUE TITLE
404 Link

### ISSUE THREAD

**Issue by cqqqq777** [kubernetes/website#44310]
https://github.com/kubernetes/website/blob/9b9d76530ef5e6c9cab819e5f144921cc4ceaac8/content/zh-cn/docs/concepts/services-networking/ingress.md?plain=1#L33

'[网关 API]'s link is 404, there needs a Chinese doc for 'Gateway API'.
The website is https://kubernetes.io/zh-cn/docs/concepts/services-networking/ingress/ and the target website is https://kubernetes.io/zh-cn/docs/concepts/services-networking/gateway/

**Comment by tamilselvan1102** [comment]
Please describe the issue in English

**Comment by tamilselvan1102** [comment]
Page related to the issue: https://kubernetes.io/zh-cn/docs/concepts/services-networking/ingress/

**Comment by cqqqq777** [comment]
My description is already English.

**Comment by tamilselvan1102** [comment]
yes, The gateway page have to be translated in Mandarin language.

**Comment by sftim** [comment]
/remove help

This issue is _not_ ready for a new contributor to work on.

**Comment by sftim** [comment]
/remove-help

This issue is not ready for a new contributor to work on.

**Comment by anirudh-hegde** [comment]
My description is already in chinese when I clicked on https://kubernetes.io/zh-cn/docs/concepts/services-networking/ingress/

![Screenshot from 2023-12-13 12-33-58](https://github.com/kubernetes/website/assets/105560839/20d32abc-e500-426b-8123-233d44e8b493)

**Comment by tamilselvan1102** [comment]
@anirudh-hegde 
The issue is about the page https://kubernetes.io/zh-cn/docs/concepts/services-networking/gateway/

**Comment by howieyuen** [comment]
/assign
ops, 404 link, I am working on this.
