### ISSUE TITLE
Error in yaml syntax

### ISSUE THREAD

**Issue by anirudh-hegde** [kubernetes/website#44319]
The error can be found in this below link:  https://github.com/kubernetes/website/blob/64ae09ea329a9afd847cf51c976d37aa4bad69ce/archetypes/concepts.md

![image](https://github.com/kubernetes/website/assets/105560839/3020b4d6-e371-45a3-b786-650397ab0377)

**Comment by tamilselvan1102** [comment]
it is .md file not a Yaml file. 
it is your IDE issue

**Comment by tamilselvan1102** [comment]
it opening fine without error
![image](https://github.com/kubernetes/website/assets/20103020/ce11c4d0-763a-4125-9abb-2f07c8084c23)

**Comment by tamilselvan1102** [comment]
it is not an issue, you can ignore this error.

**Comment by anirudh-hegde** [comment]
> it opening fine without error ![image](https://private-user-images.githubusercontent.com/20103020/290113131-ce11c4d0-763a-4125-9abb-2f07c8084c23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTM5MjgsIm5iZiI6MTcwMjQ1MzYyOCwicGF0aCI6Ii8yMDEwMzAyMC8yOTAxMTMxMzEtY2UxMWM0ZDAtNzYzYS00MTI1LTlhYmItMmYwN2M4MDg0YzIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA3NDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NzNlODA0ZDc5ODczODUxMGYwNzNhYjhjZGQ2YzJiY2U5ZThiYzYzNTIxM2I4MDU0OWFlYmZmNjQ4NWUwMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFkAqTz006QA4_-FWeEzChUWbKoJnZ-UDYbaYf20wSA)

I too getting correctly

**Comment by anirudh-hegde** [comment]
> The error can be found in this below link: https://github.com/kubernetes/website/blob/64ae09ea329a9afd847cf51c976d37aa4bad69ce/archetypes/concepts.md
> 
> ![image](https://private-user-images.githubusercontent.com/105560839/290108950-3020b4d6-e371-45a3-b786-650397ab0377.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTQwMDgsIm5iZiI6MTcwMjQ1MzcwOCwicGF0aCI6Ii8xMDU1NjA4MzkvMjkwMTA4OTUwLTMwMjBiNGQ2LWUzNzEtNDVhMy1iNzg2LTY1MDM5N2FiMDM3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwNzQ4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NjA3ZjhiNTAxNDMzNjY1YWFmNzRmYjkxMDhkNjQxOWVjYjFhZjJiMjYyN2IzM2FkZGRlNzRkNzEzZGU1N2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oxg_cfL6-ZVMfhqkAoVQPeJv5ewmugVD5g1EGqCp88g)

then why I am seeing this

**Comment by tamilselvan1102** [comment]
Because the first line having '---.so browser parser may considering it as yaml file. 
it is not website issue it is the browser issue.

**Comment by tamilselvan1102** [comment]
if you are convinced, please close the issue
