### ISSUE TITLE
A blog to summarize KubeCon experience for beginners

### ISSUE THREAD

**Issue by Rajdeep1311** [kubernetes/website#44318]
**This is a Feature Request**
- Inclusion of a blog to give a point-of-view about KubeCon for beginners.

**What would you like to be added**
- A blog that summarizes my experience and idea of KubeCon that is written keeping in mind the perspective of a newbie

**Why is this needed**
- Helping more students get involved, attend events, and learn from them because KubeCon can be overwhelming for new folks.

**Comments**
- I want to help more students and make them aware of the world beyond DSA and Algorithms. As I come from a Tier-3 college, I know the scenario in these colleges, and people in my area, I guess are very less aware of these, even though we had a CNCF local community here but it is now non-active.

**Comment by Rajdeep1311** [comment]
I have a blog ready, can I contribute?

**Comment by aj11anuj** [comment]
@Rajdeep1311 generally for blog contributions issues aren't raised like this here. If you have a blog idea that is beneficial for K8s community then you can directly raise a PR for it. If you are in doubt whether your blog will be accepted or not then you can have a discussion related to it on `#sig-docs-blog` [slack channel](https://communityinviter.com/apps/kubernetes/community). Additionally, you can read more about blog contributions in K8s community from [here](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/).

/close not-planned
