### ISSUE TITLE
Add Dark/Light mode feature to k8s website

### ISSUE THREAD

**Issue by anirudh-hegde** [kubernetes/website#44323]
As geeks may like Dark or Light mode, so I recommend to add this feature or can mention the link of the file here in order to make the changes.

![image](https://github.com/kubernetes/website/assets/105560839/5c34f60c-92c3-4f10-9212-f761a923e04d)

**Comment by dipesh-rawat** [comment]
Looks like a duplicate of issue https://github.com/kubernetes/website/issues/25061 we already have 
/triage duplicate

**Comment by dipesh-rawat** [comment]
Thanks for raising this! 

However, closing this request as it closely mirrors the original issue. Feel free to continue the discussion on the original issue.

/close not-planned
