### ISSUE TITLE
Redundant information present in sidecar containers page

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#44334]
**This is a Bug Report**
**Problem:**
1. Below text is no longer needed as sidecar containers are now entered into beta state and they are enable by default.

> By default, this feature is not available in Kubernetes. To avail this feature, you need to enable the [feature gate](https://v1-28.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) named SidecarContainers.

2. The reference link of sidecar containers present in [featurgates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates) page is wrongly redirecting to [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) page.

**Proposed Solution:**
1. Remove the text below from sidecar containers documentation.
> By default, this feature is not available in Kubernetes. To avail this feature, you need to enable the [feature gate](https://v1-28.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) named SidecarContainers.

2. Change reference link present in [featuregates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates) page from [init-containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) page to [sidecar containers](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) page.

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates
https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/

**Comment by reylejano** [comment]
Beta APIs are off by default with https://github.com/kubernetes/enhancements/issues/3136

**Comment by sftim** [comment]
[Pod](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/) is not a beta API though @reylejano 

/triage accepted
