### ISSUE TITLE
How to check in local clusters the default value for the flag `--service-node-port-range`?

### ISSUE THREAD

**Issue by dancer1325** [kubernetes/website#44332]
**This is Support**

* I would like to confirm that in fact the "--service-node-port-range" flag has the default value [30000-32767] as it's indicated in the website documentation

**How to reproduce:**
* `kind create cluster` -- use simple default kind cluster with 1 node --
* `kubectl describe pod/kube-apiserver-NAME -n kube-system` and no register found in the container's commands about the default value for that flag.
  * Because I assumed that by default it would add the default value
 ![image](https://github.com/kubernetes/website/assets/39351487/2d28315a-588b-46c2-bcfe-5fe94c97067c)
  * Another alternative to check it ❓ It should be existing in kube-apieserver, I assume
  * I was taking a look to the rest of volumes for the pod one, but nothing relevant about it 
  * Or in some environment variable is added?

**Note:**
* It's indicated that the default value is ' 30000-32767' in https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
* Checking [directly in Kubernetes](https://github.com/search?q=repo%3Akubernetes%2Fkubernetes+32767&type=code) itself (0 idea of the code, of course 😄 ), I didn't see anything which made to confirm that default value.

**Comment by dipesh-rawat** [comment]
@dancer1325 GitHub issue tracker might not be the appropriate platform for support requests. Please do consider exploring alternative resources like the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for additional support.

**Comment by dancer1325** [comment]
Hi @dipesh-rawat ,


thank you for the recommendation 🎩 

 [SlackDiscussion](https://kubernetes.slack.com/archives/CEKK1KTN2/p1702501352078539), since I didn't see anything exactly about it in bot suggestions

**Comment by sftim** [comment]
/retitle How to check in local clusters the default value for the flag `--service-node-port-range`?

**Comment by BenTheElder** [comment]
> It's indicated that the default value is ' 30000-32767' in https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport

Yes, that's it.

The docs cover this as you linked, otherwise you could check the usage for the command with `--help` locally.

> Checking [directly in Kubernetes](https://github.com/search?q=repo%3Akubernetes%2Fkubernetes+32767&type=code) itself (0 idea of the code, of course 😄 ), I didn't see anything which made to confirm that default value.

We can trace the flag:

https://github.com/search?q=repo%3Akubernetes%2Fkubernetes+service-node-port-range&type=code

=> https://github.com/kubernetes/kubernetes/blob/3ca88dc1d0e73546ccc58a20496fd475f91d7116/cmd/kube-apiserver/app/options/options.go#L124

=> inspect the surrounding code

https://github.com/kubernetes/kubernetes/blob/3ca88dc1d0e73546ccc58a20496fd475f91d7116/cmd/kube-apiserver/app/options/options.go#L90

=>

https://github.com/kubernetes/kubernetes/blob/3ca88dc1d0e73546ccc58a20496fd475f91d7116/pkg/kubeapiserver/options/options.go#L27

```go
// DefaultServiceNodePortRange is the default port range for NodePort services.
var DefaultServiceNodePortRange = utilnet.PortRange{Base: 30000, Size: 2768}
```

**Comment by dancer1325** [comment]
Hi @BenTheElder ,

* Thanks for links to trace the code

> otherwise you could check the usage for the command with --help locally.
* Sorry, how do you suggest to use `--help` ?

**Comment by Ritikaa96** [comment]
Hi @dancer1325 help command can be used with kubectl to get details of the specific commands such as .:

```shell
kubectl create cluster --help
```
```console
Create a resource from a file or from stdin.

 JSON and YAML formats are accepted.

Examples:
  # Create a pod using the data in pod.json
  kubectl create -f ./pod.json
  
  # Create a pod based on the JSON passed into stdin
  cat pod.json | kubectl create -f -
  
  # Edit the data in registry.yaml in JSON then create the resource using the
edited data
  kubectl create -f registry.yaml --edit -o json

Available Commands:
  clusterrole           Create a cluster role
  clusterrolebinding    Create a cluster role binding for a particular cluster
role
  configmap             Create a config map from a local file, directory or
literal value
  cronjob               Create a cron job with the specified name
  deployment            Create a deployment with the specified name
  ingress               Create an ingress with the specified name
  job                   Create a job with the specified name
  namespace             Create a namespace with the specified name
  poddisruptionbudget   Create a pod disruption budget with the specified name
  priorityclass         Create a priority class with the specified name
  quota                 Create a quota with the specified name
  role                  Create a role with single rule
  rolebinding           Create a role binding for a particular role or cluster
role
  secret                Create a secret using a specified subcommand
  service               Create a service using a specified subcommand
  serviceaccount        Create a service account with the specified name
  token                 Request a service account token


```

**Comment by Ritikaa96** [comment]
As this is a support query , you can close this issue if your query is answered or much better if you ask such support queries in StackOverflow, Stackalytics or Kubernetes [discussion](https://discuss.kubernetes.io/).

**Comment by aj11anuj** [comment]
As query has been resolved
/close
