### ISSUE TITLE
Broken info in “Install and Set Up kubectl on Windows”

### ISSUE THREAD

**Issue by GitHubSergei** [kubernetes/website#44330]
Hello, on the current date (13 Dec 2023) there is a bug on the page https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows
The bug is for example here: Download the latest 1.29 patch release: [kubectl %!f(string=1.).0](https://dl.k8s.io/release/v%!f(string=1.).0/bin/windows/amd64/kubectl.exe).

%!f(string=1.).0 is in all links - so it's not possible to download kubectl.exe. Please fix.
Thank you.

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows
/language en
/sig docs

**Comment by dipesh-rawat** [comment]
It appears that there may be an issue with the shortcode responsible for generating the version on our page. While this issue has been reported for a single page, it is a site-wide issue affecting multiple pages that use the shortcode.

/kind bug
/triage accepted

**Comment by dipesh-rawat** [comment]
I'll try to investigate this issue and see if I can offer assistance.
/assign

**Comment by sftim** [comment]
/retitle Broken info in “Install and Set Up kubectl on Windows”
