### ISSUE TITLE
Install and Set Up kubectl on Windows

### ISSUE THREAD

**Issue by DarshanUmapathi** [kubernetes/website#44333]
The download link for windows is not working

**Comment by dipesh-rawat** [comment]
Looks like a duplicate of issue https://github.com/kubernetes/website/issues/44330 we got earlier
/triage duplicate

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows
/language en
/sig docs

**Comment by sftim** [comment]
/close
Fixed in #44330
