### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl-windows/

### ISSUE THREAD

**Issue by raghuveer** [kubernetes/website#44350]
Hi

I tried downloading Kubernetes but I got bad request message from nginx.

The reason is, version number is not loading correctly in the link.

it has to be:
https://dl.k8s.io/release/v1.29.0/bin/windows/amd64/kubectl.exe

actually since the version number is not parsed when page got loaded, the link shown is:
https://dl.k8s.io/release/v%!f(string=1.).0/bin/windows/amd64/kubectl.exe

Request to please validate this

Thank you

With Best Regards
Raghuveer

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows
/language en
/sig docs

**Comment by T-Lakshmi** [comment]
Duplicate issue of #44333 and #44330
/triage duplicate

**Comment by T-Lakshmi** [comment]
Hi @raghuveer,
Thanks for reporting, We already working to fix this issue from #44330.
