### ISSUE TITLE
Install and Set Up kubectl on Windows

### ISSUE THREAD

**Issue by SATHYA-NARAYANA** [kubernetes/website#44358]
Download links showing characters and strings :
<img width="960" alt="Screenshot 2023-12-14 135059" src="https://github.com/kubernetes/website/assets/54190045/15d024f4-97e5-4324-b73d-24176709bdce">

Instaed of : https://dl.k8s.io/release/v1.29.0/bin/windows/amd64/kubectl.exe

**Comment by T-Lakshmi** [comment]
Fixed in #44330,
/triage duplicate
@SATHYA-NARAYANA,
We have updated the documentation, you may check now again.
Page: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows

**Comment by dipesh-rawat** [comment]
/close
Fixed in https://github.com/kubernetes/website/issues/44330
