### ISSUE TITLE
`skew` shortcode fails to determine latest patch version

### ISSUE THREAD

**Issue by dipesh-rawat** [kubernetes/website#44370]
**This is a Bug Report**

**Problem:**
With the recent release of v1.29, the `{{< skew currentPatchVersion >}}` shortcode experienced difficulties in determining the latest patch version _(i.e. 1.29.0)_. The output from the shortcode  was `%!f(string=1.).0.` _(Refer below screenshot)._

A quick fix as part of PR https://github.com/kubernetes/website/pull/44344 involved updating the [schedule.yaml](https://github.com/kubernetes/website/blob/main/data/releases/schedule.yaml) to incorporate version 1.29.0 under previous patches, ensuring the shortcode displays the expected value.

![image](https://github.com/kubernetes/website/assets/13051389/b75cac0e-d967-4f11-a894-9528d4557e3f)

**Proposed Solution:**
While the quick fix (https://github.com/kubernetes/website/pull/44344) resolves the issue when there's a previous patch release listed, the shortcode should also be fixed to work seamlessly in scenarios where no previous patch release is specified. The current fallback mechanism in the shortcode appears to be buggy and requires further attention for robust functionality.

**Expected Behavior:**
The `skew` shortcode should accurately determine the latest patch version, whether or not there is a previous patch release listed, and display the correct output.

**Shortcode file:**
[layouts/shortcodes/skew.html](https://github.com/kubernetes/website/blob/main/layouts/shortcodes/skew.html)

/area web-development

**Comment by vaibhav2107** [comment]
I think the issue is fixed by the PR #45018 and hence can be closed

**Comment by sergeyshevch** [comment]
Thanks! Forgot to close this by myself
