### ISSUE TITLE
Add page editing hint to Markdown source of feature gates page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44376]
**This is a Feature Request**

**What would you like to be added**
For the Markdown source of the [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) page, add a comment in HTML comment format that explains where to find a guide to edit that page.

**Why is this needed**
People who are adding or improving features for Kubernetes need to document their changes, and this often involves edits to https://k8s.io/docs/reference/command-line-tools-reference/feature-gates/

However, once you find 
https://github.com/kubernetes/website/blob/b481082a448610ca183b8d9c70baeb5b450448ea/content/en/docs/reference/command-line-tools-reference/feature-gates/index.md it is not obvious exactly what you need to do.

The advice we add should mention https://kubernetes.io/docs/contribute/new-content/new-features/#ready-for-review-feature-gates

**Comments**
/language en
/sig contributor-experience

**Comment by sftim** [comment]
We could also add a hint for people localizing that page.

**Comment by dshebib** [comment]
I'm seeing that there is already a comment in the file referencing the link: https://github.com/kubernetes/website/edit/main/content/en/docs/reference/command-line-tools-reference/feature-gates/index.md#L107 

Perhaps it was added by a previous PR?

**Comment by sftim** [comment]
/close

Added in https://github.com/kubernetes/website/pull/44554
