### ISSUE TITLE
Unclear explanation of CPU resource in “Resource Management for Pods and Containers”

### ISSUE THREAD

**Issue by Pymann** [kubernetes/website#44377]
For me the description of cpu units is a little bit unclear....?!

it is written:

> 1 CPU unit is equivalent to 1 physical CPU core, or 1 virtual core, depending on whether the node is a physical host or a virtual machine running inside a physical machine

But from my understanding 1pCPU (pyhiscal CPU) and 1vCPU is something totally different:
Lets check this processor: https://www.intel.de/content/www/de/de/products/sku/192482/intel-xeon-platinum-8270-processor-35-75m-cache-2-70-ghz/specifications.html

Cores 26
Threads 52

or my local pc:
Cores: 4
logical processors: 8

Does it mean, count of logical processors and threads is always same?

I found a german translation:
"Ein logischer Prozessor ist die Anzahl der Kerne des Prozessors, multipliziert mit der Anzahl der Threads pro Kern. vCPUs sind tatsächlich die Zeitmengen, die eine virtuelle Maschine auf einem logischen Prozessor erhält."
Means:
"a logical processor is the count of cores multiplied by count of threads per core. vCPU is the amount of time, a virtual machine reserved on the logical processor."

So my understanding is you have foloowing equation: vCPU=count of Threads.

Means the cpu unit means on a virtual machine anything but on a virtual machine same multiplied by threadcount per core....?!
or what!?

**Comment by dipesh-rawat** [comment]
Page reported in issue _(based on the initial title)_: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
/language en

**Comment by sftim** [comment]
If I take a computer with 2 physical CPU packages, each 1 core per package, and I run 48 emulating VMs, each emulating a one-CPU guest, how many vCPUs are there in each guest? **One**

If I take a computer with 2 physical CPU packages, each 1 core per package, and I run 4 emulating VMs, each emulating a 64-CPU guest, how many vCPUs are there in each guest? **Sixty four**

If I use one of these guests as a node, it might have 1 vCPUs, 64 vCPUs, or some other number

When there is virtualization in play, there is often but not always a link between virtual CPUs and physical host resources. We don't know what that relationship is.

Perhaps we can rewrite that page to make the lack of a direct link more obvious to readers.

**Comment by sftim** [comment]
If the node has 64 virtual CPUs, then the kubelet sees exactly 64.0 CPU resources (minus any [overhead](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/))

**Comment by Pymann** [comment]
There is any clearer example, I never heard of guests or cpu packages.
Maybe stay with the posted processor.

**Comment by sftim** [comment]
/retitle Unclear explanation of CPU resource in “Resource Management for Pods and Containers”
