### ISSUE TITLE
API Overview page contains broken links

### ISSUE THREAD

**Issue by adityasamant25** [kubernetes/website#44375]
**This is a Bug Report**

**Problem:**
[API Overview](https://kubernetes.io/docs/reference/using-api/) page contains the following broken links:

1. Consequently, everything in the Kubernetes platform is treated as an API object and has a corresponding entry in the [API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/).

2. The [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/) lists the API for Kubernetes version v1.29.

3. The named groups are at REST path /apis/$GROUP_NAME/$VERSION and use apiVersion: $GROUP_NAME/$VERSION (for example, apiVersion: batch/v1). You can find the full list of supported API groups in [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#-strong-api-groups-strong-).

**Proposed Solution:**
Fix the broken links

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/

**Comment by sftim** [comment]
/triage accepted

There is a PR ready for review / approval that would fix this.

/priority important-soon

**Comment by Manish-hr14** [comment]
> **This is a Bug Report**
> 
> **Problem:** [API Overview](https://kubernetes.io/docs/reference/using-api/) page contains the following broken links:
> 
> 1. Consequently, everything in the Kubernetes platform is treated as an API object and has a corresponding entry in the [API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/).
> 2. The [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/) lists the API for Kubernetes version v1.29.
> 3. The named groups are at REST path /apis/$GROUP_NAME/$VERSION and use apiVersion: $GROUP_NAME/$VERSION (for example, apiVersion: batch/v1). You can find the full list of supported API groups in [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#-strong-api-groups-strong-).
 3. [Kubernetes API reference] link also seems broken. can we add https://kubernetes.io/docs/reference/kubernetes-api/ ?

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/44387
