### ISSUE TITLE
Incorrect link redirection in "Running ZooKeeper" tutorial page for "PersistentVolumes"

### ISSUE THREAD

**Issue by kumarankit999** [kubernetes/website#44378]
This is a Bug Report

Problem:
[ZooKeeper](https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/) page contains the following broken links:

If we go through the Running ZooKeeper, A Distributed System Coordinator Introduction. If we go to click PersistentVolumes it should redirect us to PersistentVolumes Page but it shows us Volumes Page which we have to rectify here!

![image](https://github.com/kubernetes/website/assets/111564362/f4c733b8-69fa-49b7-9bb3-eb61d0102f11)

Proposed Solution:
Fix the broken links by Updating it to: https://kubernetes.io/docs/concepts/storage/persistent-volumes/

Page to Update:
https://kubernetes.io/docs/concepts/storage/volumes/

**Comment by kumarankit999** [comment]
hey @dipesh-rawat, Can you look into this issue!!!!

**Comment by dipesh-rawat** [comment]
/retitle Incorrect link redirection on "Running  ZooKeeper" tutorial for "PersistentVolumes"
/kind bug

**Comment by dipesh-rawat** [comment]
/priority backlog
(or lower)
/triage accepted
/help

**Comment by dipesh-rawat** [comment]
/retitle Incorrect link redirection in "Running ZooKeeper" tutorial page for "PersistentVolumes"

**Comment by kumarankit999** [comment]
Thanks @dipesh-rawat

**Comment by kumarankit999** [comment]
But I have to work on this issue!!!
I have self-assigned this issue to myself, Why someone else has raised a PR For this @dipesh-rawat ??????
