### ISSUE TITLE
One-page API reference missing for Kubernetes v1.29

### ISSUE THREAD

**Issue by andryrochev** [kubernetes/website#44387]
Hello.
I believe the all links that looked as `/docs/reference/generated/kubernetes-api/{{< param "version" >}}/` in source code are broken.

Current links looked as https://kubernetes.io/docs/reference/kubernetes-api/service-resources/XXX, for example this is to service resource api https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/ 

Here is no 'generated' and version. It is not clear is it the problem in website, or in api reference generator.

It are just a few examples of broken links:

`content/en/docs/reference/access-authn-authz/extensible-admission-controllers.md`:

- `[deployment API](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/#deployment-v1-apps)`
- `[ValidatingWebhookConfiguration](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io)`

`content/en/docs/tutorials/services/connect-applications-service.md`:

- `[Service](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/#service-v1-core)`

**Comment by sftim** [comment]
/triage accepted
/retitle One-page API reference missing for Kubernetes v1.29
/kind bug
/priority important-soon

There is a pull request to fix this that is awaiting approval.

@Priyankasaggu11929 FYI

**Comment by sftim** [comment]
Fixed in PR https://github.com/kubernetes/website/pull/44345
/close

**Comment by ErAnujPratap** [comment]
unale to open api reference for service v1 core (show example)
