### ISSUE TITLE
[es] localize content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#44381]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs

**Comment by gamba47** [comment]
This was an error the file already exists on main branch.

/close
