### ISSUE TITLE
Add “spec” to glossary

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44389]
**This is a Feature Request**

**What would you like to be added**
Add a term to the [glossary](https://kubernetes.io/docs/reference/glossary/?all=true#term-spec): “spec”.

**Why is this needed**

> Almost every Kubernetes object includes two nested object fields that govern the object's configuration: the object spec and the object status. For objects that have a spec, you have to set this when you create the object, providing a description of the characteristics you want the resource to have: its desired state. 

However, if you wanted to look up that term in our glossary, you wouldn't find it.

**Comments**
/language en
/priority important-longterm
/triage accepted
/help

The way to implement this is to add a new file inside [`content/en/docs/reference/glossary`](https://github.com/kubernetes/website/tree/409af7e4302d779ddc8c0fa09834b4296cbb57d5/content/en/docs/reference/glossary). You can look at other files in the same directory for a hint about what to add, or you can reply to this issue to ask for clarification.

**Comment by rohan-kapse** [comment]
#44395

**Comment by rohan-kapse** [comment]
[](https://github.com/kubernetes/website/pull/44395)

**Comment by rohan-kapse** [comment]
[https://github.com/kubernetes/website/pull/44395](url)

**Comment by rohan-kapse** [comment]
#44395 Fixed.

**Comment by vaibhav2107** [comment]
Fixed by #44395 and hence closing this
