### ISSUE TITLE
Secrets docs, PodSpec API broken link

### ISSUE THREAD

**Issue by VladSatyshev** [kubernetes/website#44385]
**This is a Bug Report**

**Problem:**
[Secret](https://kubernetes.io/docs/concepts/configuration/secret) page contains the following broken link:

> See the [PodSpec API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podspec-v1-core) for more information about the imagePullSecrets field.

**Additional info:**
The current link is `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podspec-v1-core`. 
The older versions i.e. `/v1.28/#podspec-v1-core` seem to work fine.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/secret/#using-imagepullsecrets-1

**Comment by kumarankit999** [comment]
Let's Work on this Collaboratively!!

**Comment by sftim** [comment]
/kind bug
/language en

This largely duplicates other issue reports that PR #44345 would fix.

**Comment by sftim** [comment]
Fixed in PR https://github.com/kubernetes/website/pull/44345
/close
