### ISSUE TITLE
Image `gcr.io/google_samples/gb-frontend:v3` unavailable in ReplicaSet example

### ISSUE THREAD

**Issue by Mohamed-AH** [kubernetes/website#44415]
**This is a Bug Report**

**Problem:**
The container image (gcr.io/google_samples/gb-frontend:v3) used in the first example on the page https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/ is not working.

**Proposed Solution:**
replace it with a working image 

**Page to Update:**

https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/

![image2](https://github.com/kubernetes/website/assets/4817193/430b763a-fdd4-4619-b6e5-b3d4dacc6cae)
![image](https://github.com/kubernetes/website/assets/4817193/325abfe7-5c60-4a77-b600-c84dc38b60a4)

**Comment by thisisharrsh** [comment]
/triage duplicate 
refer #44224

**Comment by aj11anuj** [comment]
It's not completely duplicate, but partially
The pages addressed in #44290 and in this issue are different

/remove-triage duplicate

**Comment by aj11anuj** [comment]
As you have already raised a PR #44225 for it
/assign @kundan2707

**Comment by dipesh-rawat** [comment]
/retitle Image `gcr.io/google_samples/gb-frontend:v3` unavailable in ReplicaSet example
/priority backlog
/triage accepted
