### ISSUE TITLE
Improvements for search bar

### ISSUE THREAD

**Issue by TartejBrothers** [kubernetes/website#44416]
**This is a Bug Report**

**Problem:**
- The search bar is not center aligned on Mobile View.
<img width="366" alt="image" src="https://github.com/kubernetes/website/assets/112921727/2761f9c6-d4eb-429c-be71-218de921340f">

- When something is searched, the search icon disappears. 
![image](https://github.com/kubernetes/website/assets/112921727/983eec91-81c0-400d-9b89-42791f16b34c)

**Proposed Solution:**
- The search bar should have the icon visible when typing. 
![image](https://github.com/kubernetes/website/assets/112921727/f8c48ec9-c193-4cda-8e1a-ee4a034647d2)

**Page to Update:**
https://kubernetes.io/

**Comment by Gauravpadam** [comment]
/remove needs-kind

That's strange

**Comment by Gauravpadam** [comment]
/remove-kind needs-kind

That's strange

**Comment by Gauravpadam** [comment]
@TartejBrothers The current behaviour seems comprehensible to me, but sure, if others think we should change it, let's do that

/priority awaiting-more-evidence

**Comment by TartejBrothers** [comment]
If it works, no problem, just wanted to highlight it.
But center alignment should be checked.

**Comment by Subhajit009iitr** [comment]
I have fixed the search bar by fixing the Magnifying glass icon while typing. Please check my PR #44527

**Comment by Subhajit009iitr** [comment]
Issue has been solved and can be closed now!
