### ISSUE TITLE
Resize CPU and Memory Resources assigned to Containers

### ISSUE THREAD

**Issue by axi-lyp** [kubernetes/website#44426]
Enable the feature，need open feature-gates: - name: InPlacePodVerticalScaling in kube-apiserver、kube-scheduler  and kubelet?

**Comment by thisisharrsh** [comment]
Hi, Could you please share some more details of the issue that you are facing? 

/triage needs-information

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/
