### ISSUE TITLE
Typo (extra v) in change-package-repository.md

### ISSUE THREAD

**Issue by prasad-shirodkar** [kubernetes/website#44437]
**This is a Bug Report**

**Problem:**
In section [Switching to another Kubernetes package repository](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository/#switching-to-another-kubernetes-package-repository), under `CentOS, RHEL or Fedora` tab, there is an extra "v" in the `baseurl` and `gpgkey` URLs corresponding to the latest kubernetes version.

`baseurl=https://pkgs.k8s.io/core:/stable:/vv1.29/rpm/
gpgkey=https://pkgs.k8s.io/core:/stable:/vv1.29/rpm/repodata/repomd.xml.key
`

**Proposed Solution:**
Correct `vv1.29` to `v1.29`.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository
https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/kubeadm/change-package-repository/

**Comment by prasad-shirodkar** [comment]
I can contribute the fix - easy one.

**Comment by sftim** [comment]
/triage accepted

Thanks
