### ISSUE TITLE
Resize CPU and Memory Resources assigned to Containers

### ISSUE THREAD

**Issue by axi-lyp** [kubernetes/website#44443]
This is a alpha version，default disable. How to enable this feature in Kubernetes v1.28?
Does it work with the static cpu manager policy feature?

I use this feature in Kubernetes v1.28. It can work when cpu manager policy set none.
But It can't work when cpu manager policy set static. so I have above question.

**Comment by Gauravpadam** [comment]
@axi-lyp support tickets are not the correct platform for queries

You can always reach out in [Kubernetes Slack](https://slack.k8s.io) for assistance

/close
