### ISSUE TITLE
Confusing explanation for label `service.kubernetes.io/headless `

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44440]
**This is a Bug Report**

**Problem:** 

> ```markdown
> ### service.kubernetes.io/headless {#servicekubernetesioheadless}
> 
> Type: Label
> 
> Example: `service.kubernetes.io/headless: ""`
> 
> Used on: Service
> 
> The control plane adds this label to an Endpoints object when the owning Service is headless.
> ```

Does this get set on Services, or on EndpointSlices and Endpoints? The docs are not self-consistent.

**Proposed Solution:**

Check the true story and then revise the explanation for this label

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/#servicekubernetesioheadless

**Additional Information:**
/language en
/sig network

**Comment by tamilselvan1102** [comment]
I would like to work on it.
/assign

**Comment by tamilselvan1102** [comment]
@sftim 
please verify the PR

**Comment by sftim** [comment]
Thanks for the invitation to review. I'm happy to let any reviewer for English check this work.

**Comment by T-Lakshmi** [comment]
PR to fix this issue #45035

**Comment by vaibhav2107** [comment]
/close 
As the issue is fixed by the PR #45744 
Please re-open in case anything is left
