### ISSUE TITLE
how to query statically reserved clusterIP range

### ISSUE THREAD

**Issue by rptaylor** [kubernetes/website#44464]
**This is a Feature Request**

**What would you like to be added**

https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/

Information about how to query the statically reserved ClusterIP range on a cluster.

**Why is this needed**
* https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3070-reserved-service-ip-range#proposed-services-clusterips-allocation-model
* https://kubernetes.io/blog/2022/05/23/service-ip-dynamic-and-static-allocation/
* https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/

This describes the statically reserved ClusterIP range. There is a formula provided for calculating it. But surely there must be a way to look up the range on a given cluster instead of having to calculate it myself? What if I make a calculation error? What if it's not clear whether the feature gate is enabled on the cluster? What if there's a bug or something? There has to be a way to confirm but I can't find any information about how to determine this.

**Comments**

**Comment by sftim** [comment]
> surely there must be a way to look up the range on a given cluster instead of having to calculate it myself

I'm afraid you might be wrong.

However, Kubernetes has [plans](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/1880-multiple-service-cidrs/README.md) to make the range dynamic; see https://kep.k8s.io/1880

It's an open source project; turning the plans into implementation largely depends on volunteers.

**Comment by sftim** [comment]
We could, I guess, document that Kubernetes doesn't let you do this. Better to document that you can look it up but only for a v1.30 (?) cluster and only with the alpha API enabled.

**Comment by rptaylor** [comment]
Okay thanks for the info @sftim !
Whenever KEP 1880 is ready I'll take a look and see if the documentation could be updated.

I guess the only other way to check might be to have a look at the pattern of allocated clusterIPs, but any IPs allocated before the featuregate wouldn't follow any pattern.
