### ISSUE TITLE
Improve clarity and understanding in 'How it works' section on 'Service Internal Traffic Policy' with a clear example

### ISSUE THREAD

**Issue by AndresPinerosZen** [kubernetes/website#44461]
Improve the "How it works" for this section using an example scenario. Feels like the only way to be sure we understood what this document says is through experimentation.

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Improve clarity and understanding in 'How it works' section on 'Service Internal Traffic Policy' with a clear example

**Comment by aj11anuj** [comment]
@AndresPinerosZen can you please explain a bit more like what you find hard to understand in it. It is written with simple explanation.

/sig docs
/kind feature
