### ISSUE TITLE
[ja] "Installing kubeadm" page references deprecated legacy repositories

### ISSUE THREAD

**Issue by aoki-taquan** [kubernetes/website#44495]
**This is a Bug Report**

**Problem:**

The installation instructions for kubeadm on both apt and yum repositories are referencing legacy repositories.

```
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
```

**Proposed Solution:**

Update the kubeadm installation guide to reflect the correct repositories.

**Page to Update:**
https://kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
https://v1-28.docs.kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
https://v1-27.docs.kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
https://v1-26.docs.kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
https://v1-25.docs.kubernetes.io/ja/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

/language ja
/assign

**Comment by Okabe-Junya** [comment]
@aoki-taquan 

このissueって解決してますか。。？？

**page to update** の項目からすると、`release-*`/`dev-*` ブランチを修正するようにも読めますが、今は基本mainで管理している気ので。。（解決しているようなら`/close` お願いします :) ）

**Comment by aoki-taquan** [comment]
closeするの忘れてました。
ありがとうございます。
