### ISSUE TITLE
[zh] Deprecated image `gcr.io/google_samples/gb-frontend:v5` causes failures in "Deploying PHP Guestbook with Redis" tutorial

### ISSUE THREAD

**Issue by rainbowXXX** [kubernetes/website#44497]
cannot pull frontend container, it shows ImagePullBackOff
![image](https://github.com/kubernetes/website/assets/37768359/536be2c1-566e-4e87-8c82-694169a462e4)

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/zh-cn/docs/tutorials/stateless-application/guestbook
/language zh

**Comment by dipesh-rawat** [comment]
/retitle [zh] Deprecated image `gcr.io/google_samples/gb-frontend:v5` causes failures in "Deploying PHP Guestbook with Redis" tutorial
/king bug
