### ISSUE TITLE
Fix typo in the number of types of hook handlers for Containers

### ISSUE THREAD

**Issue by dancer1325** [kubernetes/website#44498]
**This is a Bug Report**
* Fix number of types of hook handlers available to implement for Containers

**Problem:**
In the section https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-implementations, it's referred as just **2** possible types of hook handlers for containers

> There are two types of hook handlers that can be implemented for Containers:

, but afterwards 3 are enumerated

> * Exec - Executes a specific command, such as pre-stop.sh, inside the cgroups and namespaces of the Container. Resources consumed by the command are counted against the Container.
> * HTTP - Executes an HTTP request against a specific endpoint on the Container.
> * Sleep - Pauses the container for a specified duration. The "Sleep" action is available when the [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) PodLifecycleSleepAction is enabled.

**Proposed Solution:**

"There are three types of hook handlers that can be implemented for Containers:"

**Page to Update:**
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/

**Comment by steve-hardman** [comment]
I will try to help with this!
/assign
