### ISSUE TITLE
[hi] Page layout for "Using kubectl to Create a Deployment" is broken

### ISSUE THREAD

**Issue by ankur0904** [kubernetes/website#44500]
**This is a Bug Report**

Presence of extra space at the end of the webpage, which can be removed. [URL](https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/
)

**Problem:** Presence of unnecessary extra space.

**Proposed Solution:**
The extra space should be removed.

**Page to Update:**
https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by dipesh-rawat** [comment]
/retitle [hi] Page layout for "Using kubectl to Create a Deployment" is broken
/language hi

**Comment by steve-hardman** [comment]
@dipesh-rawat I want to try ot help with ths plz! Can i get some pointers where to start with?
/assign

**Comment by dipesh-rawat** [comment]
We should fix the layout of the page.

/triage accepted
/priority backlog

**Comment by dipesh-rawat** [comment]
@steve-hardman I would begin by examining the source of the page at [content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro](https://github.com/kubernetes/website/blob/main/content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html).

**Comment by steve-hardman** [comment]
WIll raiase a PR once i have fixed the issue. 

Thanks for the help and Merry Christmas!

**Comment by steve-hardman** [comment]
@Manish-hr14 I'm working on the issue and planning to raise PR soon. Could you please let me fix this please!

**Comment by kumarankit999** [comment]
Hey @Manish-hr14 don't create a problem while someone is working already on the issue! It would be great if you check out the community guidelines.
For now, I'm unassigning you. Thanks for giving time here.
/unassign @Manish-hr14
