### ISSUE TITLE
Outdated explanation in kube-proxy configuration

### ISSUE THREAD

**Issue by aceeric** [kubernetes/website#44529]
Hello - Regarding this doc: https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/#kubeproxy-config-k8s-io-v1alpha1-KubeProxyConfiguration

The configuration for `clusterCIDR` says (emphasis added):

> clusterCIDR is the CIDR range of the pods in the cluster. (For dual-stack clusters, this can be a comma-separated dual-stack pair of CIDR ranges.). When _**DetectLocalMode is set to LocalModeClusterCIDR**_, kube-proxy will consider traffic to be local if its source IP is in this range. (Otherwise it is not used.)

I believe _When DetectLocalMode is set to LocalModeClusterCIDR_ should instead read (emphasis added): _When DetectLocalMode is set to **ClusterCIDR**_.

Based on: https://github.com/kubernetes/kubernetes/blob/735804dc812ce647f8c130dced45b5ba4079b76e/pkg/proxy/apis/config/types.go#L271

(Also applies to `detectLocalMode` above in the same table.

**Comment by dipesh-rawat** [comment]
_Page reported in issue (**auto-generated page**):_  https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/
/language en

**Comment by dipesh-rawat** [comment]
Looks like the reference page for  "_kube-proxy Configuration_" is [automatically generated](https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/#auto-generated-edit-notice). The page is generated from the upstream source code, specifically at this location: [kubernetes/kubernetes/staging/src/k8s.io/kube-proxy/config/v1alpha1/types.go](https://github.com/kubernetes/kubernetes/blob/1a6b9b811e303c033006e9a3223258582149b69b/staging/src/k8s.io/kube-proxy/config/v1alpha1/types.go#L225). 

As the page is generated from the upstream source code, any fixes would need to be addressed there. For those interested in contributing to resolve this issue (once it's accepted), please refer to the upstream contribution guidelines outlined at: https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream

**Comment by sftim** [comment]
/retitle Outdated explanation in kube-proxy configuration 

See https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/#auto-generated-edit-notice

**Comment by kundan2707** [comment]
Made upstream changes in https://github.com/kubernetes/kubernetes/pull/125479 to fix this isssue

**Comment by kundan2707** [comment]
Closing this issue as https://github.com/kubernetes/kubernetes/pull/125479 got merged.
