### ISSUE TITLE
question: multiple containers in a pod file conflict handling

### ISSUE THREAD

**Issue by WeihanLi** [kubernetes/website#44548]
Not sure if I'm in the correct place for the question, sorry if I'm not.

When there's file conflict in the k8s pod, how would k8s handle it?

For example, there are three containers in the pod named `a`, `b`, `c`, both `a` and `b` containers have `/etc/config/my-config` path, but with different content, `a` container has `aaa` content, `b` container has `bbb` content.

Then when the pod is ready to serve, what's the content from the path `/etc/config/my-config` should I expect when I try to access the path `/etc/config/my-config` from the `c` container?

**Comment by thisisharrsh** [comment]
Since Kubernetes does not actively resolve the file conflicts between the containers within the pod, it will result in an error if the container 'c' does not have a file at that location.

**Comment by kumarankit999** [comment]
Hey @WeihanLi, Thanks for taking the time to raise an issue here. But, It would be a good approach if you could ask your doubts on the Kubernetes Slack Channel.

**Comment by WeihanLi** [comment]
thanks very much
