### ISSUE TITLE
Docs search gets hidden on scroll down in page

### ISSUE THREAD

**Issue by coder12git** [kubernetes/website#44561]
**This is a Feature Request**

**What would you like to be added**
Currently Docs search hides when you scroll down the page, but it should not get hidden it must stay there at the top.

**Why is this needed**

- Search Input should always stay at its place.

- Also, as a suggestion it can also be called on keyboard shortcut like `ctrl + /`  like this to easily navigation in the docs.

**Comments**

![Screenshot 2023-12-28 203248](https://github.com/kubernetes/website/assets/108334168/dbd2828c-5d49-46b6-b1db-9f14a60ccfd1)

**Comment by coder12git** [comment]
area/web-development

**Comment by sftim** [comment]
/area web-development

How about putting the search in the top nav? See https://github.com/kubernetes/website/issues/41171 for a related suggestion.

**Comment by coder12git** [comment]
> How about putting the search in the top nav? See #41171 for a related suggestion.

But, I'm not sure it's a good plan. The top nav already has a bunch of sections, and adding the search might make it look too crowded.

**Comment by sftim** [comment]
See how https://www.docsy.dev/docs/ does it - I think that's a nice approach. We could drop one of the sections that's in the top nav now, or maybe combine two of them into a menu.

**Comment by sftim** [comment]
/triage accepted

Making this improvement is helpful.

/priority backlog
though

**Comment by coder12git** [comment]
Have a review on this PR -> #44574

**Comment by sftim** [comment]
> Currently Docs search hides when you scroll down the page, but it should not get hidden it must stay there at the top.

Does it? On my browser, that doesn't happen.

![Screenshot](https://github.com/kubernetes/website/assets/22591623/004c6c8a-a9c2-47bf-b68e-043940ef3fff)

You can see that this page is scrolled but the search is still available for someone to look at it,

/priority awaiting-more-evidence
/remove-triage accepted

**Comment by sftim** [comment]
Even though I don't think the issue description is quite right, I still see the value of putting a search in the top nav. That is a place where people would look for it.

**Comment by coder12git** [comment]
> Even though I don't think the issue description is quite right, I still see the value of putting a search in the top nav. That is a place where people would look for it.

I think it more depend on screen size, in my case when i have scroll down the page, then i am not able to see that search button on the left side

![Screenshot 2023-12-30 071927](https://github.com/kubernetes/website/assets/108334168/6593e0e7-d5be-468b-bf68-9d86c7f87a23)
