### ISSUE TITLE
Content of 'One-page API Reference for v1.29' not rendering properly in dark mode

### ISSUE THREAD

**Issue by tjamet** [kubernetes/website#44572]
**This is a Bug Report**

**Problem:**

Using chrome (120.0.6099.129 (Official Build) (x86_64)) on macOS (12.7.1 (21G920)) and hitting the [single-page API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/) link from the [official API documentation](https://kubernetes.io/docs/reference/#api-reference), I hit the documentation for Kubernetes 1.29 and I can only see the navigation with the list of objects.

<img width="1595" alt="image" src="https://github.com/kubernetes/website/assets/6061440/0a213bc7-2dc8-4099-910a-00a11c6baffb">

I have observed the same problem on safari ( 17.1.2 (17616.2.9.11.12, 17616)):
<img width="1587" alt="image" src="https://github.com/kubernetes/website/assets/6061440/ff860ad1-8a19-4a15-b902-3e816d677ee7">

And Firefox (121.0 (64-bit)):
<img width="1266" alt="image" src="https://github.com/kubernetes/website/assets/6061440/bc58a6a8-69a5-4f6b-ae73-adebf9e764c8">

**Proposed Solution:**

Get the content back as in the [1.28 documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/):

<img width="1585" alt="image" src="https://github.com/kubernetes/website/assets/6061440/4328efb8-0a1a-4b55-bc90-254553d4bd5f">

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/

**Comment by dipesh-rawat** [comment]
/retitle One-page API reference missing for Kubernetes v1.29

**Comment by dipesh-rawat** [comment]
The API reference for v1.29 was successfully generated in PR https://github.com/kubernetes/website/pull/44345, as evidenced  by the verified information in the [repository file](https://github.com/tengqm/website/tree/main/static/docs/reference/generated/kubernetes-api/v1.29). It appears that we're encountering a rendering glitch.

**Comment by dipesh-rawat** [comment]
Upon further investigation, it seems that the page data isn't rendering correctly in dark mode _(sort of)_. I switched my device/browser theme to light mode, and the page info became visible _(Refer below screenshot)_. It seems like there might be some missing CSS and scripts causing this issue.  

<img width="1278" alt="api-refence-light-mode" src="https://github.com/kubernetes/website/assets/13051389/ba1c3fd8-21dd-46b8-834c-4aab4d62f3a1">

**Comment by dipesh-rawat** [comment]
/retitle Content of 'One-page API Reference for v1.29' not rendering properly in dark mode

**Comment by tengqm** [comment]
@dipesh-rawat The original description of the issue is proper and correct, I don't know why you are so akin to change these issue descriptions. I'm raising this question because when an issue title is changed, my email client won't treat the issues as the same one. The "conversation" mode no longer works. I'm receiving emails for every comment as a separate email. It is not a big deal but it is really annoying.

**Comment by sftim** [comment]
Ah, does the API reference have special support for dark mode, separate from https://github.com/kubernetes/website/issues/25061?

Assuming that this is the case:
/kind bug
/area web-development

A short-term fix would be to drop the dark mode support, pending an implementation that works right. Let's see if #44581 sorts it out.

**Comment by sftim** [comment]
For what it's worth, I agree with the title change in https://github.com/kubernetes/website/issues/44572#issuecomment-1872195500

The bug was about dark mode rendering and not that the reference was completely missing.
