### ISSUE TITLE
Hardening Guide - Authentication Mechanisms

### ISSUE THREAD

**Issue by techitlab** [kubernetes/website#44580]
I think bellow:
"They cannot be set with an expiry and will remain valid until the associated service account is deleted."

in service account section is not clear. After deleting service account kubernetes api recject comunication.

**Comment by dipesh-rawat** [comment]
_Page reported in issue (from current title):_ https://kubernetes.io/docs/concepts/security/hardening-guide/authentication-mechanisms

/language en

**Comment by stlaz** [comment]
@techitlab Could you please expand on what exactly is not clear in the description?

**Comment by stlaz** [comment]
/close
No reply to my question within a month, this can be closed.
