### ISSUE TITLE
"Load-Balanced Access to an Application" task seems to contradict other tasks/tutorials

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#4460]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
This task has the user expose the ReplicaSet that is created when its parent Deployment controller is created, rather than exposing the Deployment itself. In other tasks and tutorials, the Deployment is exposed. In following this task, you can expose the Deployment and appear to get the same result.

While the procedure "works" in the sense that all of commands appear to complete successfully, as a user I don't understand what I'm doing and why, and by encountering this task after reading other tasks I'm left wondering why I would do one or the other.

**Proposed Solution:**
- Document the purpose of exposing the child ReplicaSet as opposed to its Deployment controller. Or, if exposing the ReplicaSet is incorrect, correct the procedure.
- Provide a use case: "This is useful for X", "You should complete this task if you are trying to do X", etc.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

**Comment by ryanmcginnis** [comment]
After reading more about Deployments, I can't think of a reason why it _ever_ necessary to expose the child ReplicaSet.

**Comment by tonglil** [comment]
I agree with you that this "basic" example should be updated to use Deployments. It might be just due to the age of when it was written.

**Comment by tonglil** [comment]
I can see when I can update this page.

**Comment by ryanmcginnis** [comment]
@tonglil, still interested in updating this page?

**Comment by tonglil** [comment]
I would like to! Give me the time until it rots again.

**Comment by ryanmcginnis** [comment]
Fixed in #8351.
