### ISSUE TITLE
Amend hugo configuration to remove deprecation warnings during build

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#44603]
**Issue:**

After bumping Hugo to v0.120.3, there were several deprecation warnings noticed in the [deploy logs](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6545cd2640329000081dc4d2). For the Tl;Dr version, please refer to [this comment](https://github.com/kubernetes/website/pull/43672#pullrequestreview-1696117277).

Specifically, we're looking to target the below deprecation warning for ALL languages in this issue:

> 10:19:08 AM: WARN  deprecated: config: languages.ru.languagenamelatinscript: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in a future release. Put the value below [languages.ru.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

**Why did this happen:**

In Hugo v0.112.0, `site.language.Params` is deprecated. It is [recommended](https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120) that `site.Params` should be used directly in the Hugo configuration. 

**What needs to be done:**

Amend the hugo configuration file i.e. hugo.toml, according to the guidelines on their website - https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

**Inspired by:**

- #43672 

/area web-development

**Comment by coder12git** [comment]
I can take this, once it has `triage/accepted` label

**Comment by Gauravpadam** [comment]
/triage accepted

Always better to fix deprecations

**Comment by steve-hardman** [comment]
This would be a nice learning for me. I would like to help with this.
/assign

**Comment by sftim** [comment]
I think the fix is to change `languages.ru.languagenamelatinscript` to `languages.ru.params.languagenamelatinscript` (and make equivalent replacements for other configuration settings).

Does that sound right?

**Comment by divya-mohan0209** [comment]
@sftim : Thank you for the question, I should have been more specific.

As mentioned in the deprecation warning above, we currently use custom top-level params in our hugo.toml. 

> WARN deprecated: config: languages.ru.languagenamelatinscript: custom params on the language top level was deprecated in Hugo v0.112.0 and will be removed in a future release. Put the value below [languages.ru.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

That means, we currently use `languages.ru.languagenamelatinscript` and its equivalents for other languages. See the screencap below for Chinese:

<img width="286" alt="Screenshot 2024-01-02 at 4 26 46 PM" src="https://github.com/kubernetes/website/assets/21279125/741cefa6-de27-4af6-8892-829a1638fed0">

Therefore, in the current config file, we will need to amend the configuration [per the guideline](https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120) for the hugo.toml file by defining a custom parameter for each language under `language.xx.params` where **xx** corresponds to the language shortcode.
 
For example, for the Chinese localization, this change would most *likely* be:

```toml
[languages.zh-cn]
title = "Kubernetes"
description = "生产级别的容器编排系统"
languageName = "中文 (Chinese)"
weight = 2
contentDir = "content/zh-cn"
languagedirection = "ltr"
   [languages.zh-cn.params]
     languageNameLatinScript = "Chinese"
```
