### ISSUE TITLE
Remove outdated non-valid possibles causes of the error in the debug pods section

### ISSUE THREAD

**Issue by dancer1325** [kubernetes/website#44631]
**This is a Bug Report**
* Remove outdated non-valid possibles causes of the error in the debug pods section

**Problem:**
In the section https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#debugging-pods, you can find as possible case "My pod is running but not doing what I told it to do" -- https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#my-pod-is-running-but-not-doing-what-i-told-it-to-do -- indicating as possible causes of this error

> Often a section of the pod description is nested incorrectly, or a key name is typed incorrectly, and so the key is ignored.
For example, if you misspelled `command` as `commnd` then the pod will be created but
will not use the command line you intended it to use.

> The first thing to do is to delete your pod and try creating it again with the `--validate` option.
For example, run `kubectl apply --validate -f mypod.yaml`.
If you misspelled `command` as `commnd` then will give an error like this:

> I0805 10:43:25.129850   46757 schema.go:126] unknown field: commnd
I0805 10:43:25.129973   46757 schema.go:129] this may be a false alarm, see https://github.com/kubernetes/kubernetes/issues/6842
pods/mypod

And for non-so latest kubernetes versions, the pod is NOT created if you make mistakes such as: 
* nesting
* mispelling -- `command` as `commnd` --

Simple example confirming it:
* `kind create cluster`
* Simple manifest pod with nesting and mispelling errors, saved the manifest as 'pod.yaml' 

```
apiVersion: v1
kind: Pod
metadata:
  name: simple
spec:
  containers:
    - name: simple
        image: busybox:latest # nesting error
      commnd:           # mispelling
        - sleep
        - "3600"

```
* `kubectl apply -f pod.yaml` and getting an error directly, without the need to pass `--validate`flag

**Proposed Solution:**

Remove the invalid references as possible cases, such as mispelling and nesting errors.

> If your pod is not behaving as you expected, it may be that there was an error in your
pod description (e.g. `mypod.yaml` file on your local machine), and that the error
was silently ignored when you created the pod.  Often a key name is typed incorrectly, and so the key is ignored.

> The first thing to do is to delete your pod and try creating it again with the `--validate` option.
For example, run `kubectl apply --validate -f mypod.yaml`.

> The next thing to check is whether the pod on the apiserver....

**Page to Update:**
https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/

**Note:** 
This specific section is previous to 2017 -- https://github.com/kubernetes/website/pull/3108 --

**Comment by kumarankit999** [comment]
> **This is a Bug Report**
> 
> * Remove outdated non-valid possibles causes of the error in the debug pods section
> 
> **Problem:** In the section https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#debugging-pods, you can find as possible case "My pod is running but not doing what I told it to do" -- https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#my-pod-is-running-but-not-doing-what-i-told-it-to-do -- indicating as possible causes of this error
> 
> > Often a section of the pod description is nested incorrectly, or a key name is typed incorrectly, and so the key is ignored.
> > For example, if you misspelled `command` as `commnd` then the pod will be created but
> > will not use the command line you intended it to use.
> 
> > The first thing to do is to delete your pod and try creating it again with the `--validate` option.
> > For example, run `kubectl apply --validate -f mypod.yaml`.
> > If you misspelled `command` as `commnd` then will give an error like this:
> 
> > I0805 10:43:25.129850   46757 schema.go:126] unknown field: commnd
> > I0805 10:43:25.129973   46757 schema.go:129] this may be a false alarm, see [kubernetes/kubernetes#6842](https://github.com/kubernetes/kubernetes/issues/6842)
> > pods/mypod
> 
> And for non-so latest kubernetes versions, the pod is NOT created if you make mistakes such as:
> 
> * nesting
> * mispelling -- `command` as `commnd` --
> 
> Simple example confirming it:
> 
> * `kind create cluster`
> * Simple manifest pod with nesting and mispelling errors, saved the manifest as 'pod.yaml'
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: simple
> spec:
>   containers:
>     - name: simple
>         image: busybox:latest # nesting error
>       commnd:           # mispelling
>         - sleep
>         - "3600"
> ```
> 
> * `kubectl apply -f pod.yaml` and getting an error directly, without the need to pass `--validate`flag
> 
> **Proposed Solution:**
> 
> Remove the invalid references as possible cases, such as mispelling and nesting errors.
> 
> > If your pod is not behaving as you expected, it may be that there was an error in your
> > pod description (e.g. `mypod.yaml` file on your local machine), and that the error
> > was silently ignored when you created the pod.  Often a key name is typed incorrectly, and so the key is ignored.
> 
> > The first thing to do is to delete your pod and try creating it again with the `--validate` option.
> > For example, run `kubectl apply --validate -f mypod.yaml`.
> 
> > The next thing to check is whether the pod on the apiserver....
> 
> **Page to Update:** https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/
> 
> **Note:** This specific section is previous to 2017 -- #3108 --

+1
