### ISSUE TITLE
Drop legacy kubectl reference page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44635]
**This is a Feature Request**

**What would you like to be added**
Replace https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands with a redirect to https://kubernetes.io/docs/reference/kubectl

**Why is this needed**
We [replaced](https://github.com/kubernetes/website/pull/42664) the generator for https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands

**Comments**
/language en
/priority backlog

/lifecycle frozen
we should definitely clean this up one day

**Comment by steve-hardman** [comment]
I want to try to help with this.
/assign

**Comment by sftim** [comment]
https://github.com/kubernetes/website/pull/44677 added a redirect; we should also delete the page we're redirecting people away from.
