### ISSUE TITLE
[fr] Update install tool task documentation

### ISSUE THREAD

**Issue by ielatifi** [kubernetes/website#44630]
Hello
In the list of supported hypervisors/drivers for MacOS, you can add Docker Desktop.
Just to have docker desktop running and run : `minikube start`
Then you should see in the logs :  
`Using Docker Desktop driver with root privileges`

**Comment by professorabhay** [comment]
Hey, @ielatifi ! Can you please share some more details to understand?
Something like a link to the particular page where you want changes will be best.

**Comment by ielatifi** [comment]
URL : https://kubernetes.io/fr/docs/tasks/tools/install-minikube/#installer-un-hyperviseur
In the list you can add `Docker Desktop` (in addition to the existing items : `HyperKit`, `VirtualBox`, and `VMware Fusion`)

**Comment by divya-mohan0209** [comment]
/retitle [fr] Update install tool task documentation
