### ISSUE TITLE
Using RBAC Authorization - "kubectl create rolebinding" without clusterrole

### ISSUE THREAD

**Issue by diamondarts** [kubernetes/website#44641]
Hello,

in https://kubernetes.io/docs/reference/access-authn-authz/rbac/#kubectl-create-rolebinding the heading states

> Grants a Role or ClusterRole within a specific namespace. Examples:

, but there is no example with a _Role_.

* All examples refer to cluster roles (parameter `--clusterrole`).
* An example using a _Role_ object (parameter `--role`) would be welcome.

Thanks for providing all the great documentation on Kubernetes!

Björn

**Comment by tamilselvan1102** [comment]
`--role  ` option example is there [here ](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create_rolebinding/#examples)
