### ISSUE TITLE
[ja] expiring link 

### ISSUE THREAD

**Issue by taole33** [kubernetes/website#44645]
This is a Feature Request

What would you like to be added
Update Japanese page of https://kubernetes.io/ja/docs/contribute/
In order to link appropriate URL.

Why is this needed
We encount expiring link of https://kubernetes.io/ja/docs/contribute/new-content/overview/
when click [貢献の概要](https://kubernetes.io/ja/docs/contribute/new-content/overview/)

Comments
I think the URL below is appropriate.
https://kubernetes.io/ja/docs/contribute/new-content/

/language ja

**Comment by Okabe-Junya** [comment]
#44652 is merged, so this issue should be closed

/close
