### ISSUE TITLE
Ingress tutorial does not mention commands needed for Mac

### ISSUE THREAD

**Issue by DachengChen** [kubernetes/website#44651]
you need start 
`minikube tunnel `

and then 
`curl --resolve "hello-world.info:80:127.0.0.1" -i http://hello-world.info `

to solve same problem in mac

**Comment by DachengChen** [comment]
sorry, this is about following tutorial 
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

**Comment by sftim** [comment]
/retitle Ingress tutorial does not mention commands needed for Mac
/remove-triage needs-information

**Comment by adityasamant25** [comment]
I can confirm that this is a valid issue on MacOS and the page needs to be updated.
I think we should move this to /triage accepted.

@DachengChen I cannot test this on Windows at the moment, but [this link](https://minikube.sigs.k8s.io/docs/handbook/accessing/#using-minikube-service-with-tunnel) suggests that the behaviour on Windows will be the same as MacOS.
_The network is limited if using the Docker driver on Darwin, Windows, or WSL, and the Node IP is not reachable directly._
