### ISSUE TITLE
“Debugging Kubernetes nodes with crictl” is outdated

### ISSUE THREAD

**Issue by fcojperez** [kubernetes/website#44667]
This page is outdated according to the comment of this ticket, https://github.com/containerd/cri/issues/520#issuecomment-355362760 because if you follow the instructions, you always get an error like the one below in any worker node when you execute:  `root@worker-1:~# crictl runp sandbox-config.json``

where [sandbox-config.json](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#run-a-pod-sandbox) is:
`{
    "metadata": {
        "name": "nginx-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "hdishd83djaidwnduwk28bcsb"
    },
    "linux": {
    }
}
`

`E0107 22:25:16.541483   10653 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"888e1ca106ad4e8439154c056cbf6d926b1417c43aba37f8a5052a916e5f8516\": plugin type=\"calico\" failed (add): pods \"nginx-sandbox\" not found"
FATA[0000] run pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "888e1ca106ad4e8439154c056cbf6d926b1417c43aba37f8a5052a916e5f8516": plugin type="calico" failed (add): pods "nginx-sandbox" not found` and seemingly it is due to "calico daemonset watch apiserver to get a list of pods, and apply network configuration based on the pod spec."

So, the page [Debugging Kubernetes nodes with crictl](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/) may be deleted or the list of sections below removed: 
* [Run a pod sandbox](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#run-a-pod-sandbox)
* [Create a container](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#create-a-container)
* [Start a container](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#start-a-container)

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl
/language en

**Comment by sftim** [comment]
/retitle “Debugging Kubernetes nodes with crictl” is outdated

**Comment by mrgiles** [comment]
Funny, one of the reviewers of the [/docs/tasks/debug/debug-cluster/crictl.md](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/) doc,

```
---
reviewers:
- Random-Liu
- feiskyer
- mrunalp
title: Debugging Kubernetes nodes with crictl
content_type: task
weight: 30
---
```

is the same person, @Random-Liu, that posted the note in the [unable to create sandbox](https://github.com/containerd/cri/issues/520) containerd issue,

_In fact, we don't recommend user to run `crictl runs` and `crictl create` on a Kubernetes node , those commands are there just for some special debug case._

**Comment by Aaina26** [comment]
> This page is outdated according to the comment of this ticket, [containerd/cri#520 (comment)](https://github.com/containerd/cri/issues/520#issuecomment-355362760) because if you follow the instructions, you always get an error like the one below in any worker node when you execute: `root@worker-1:~# crictl runp sandbox-config.json``
> 
> where [sandbox-config.json](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#run-a-pod-sandbox) is: `{ "metadata": { "name": "nginx-sandbox", "namespace": "default", "attempt": 1, "uid": "hdishd83djaidwnduwk28bcsb" }, "linux": { } } `
> 
> `E0107 22:25:16.541483 10653 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"888e1ca106ad4e8439154c056cbf6d926b1417c43aba37f8a5052a916e5f8516\": plugin type=\"calico\" failed (add): pods \"nginx-sandbox\" not found" FATA[0000] run pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "888e1ca106ad4e8439154c056cbf6d926b1417c43aba37f8a5052a916e5f8516": plugin type="calico" failed (add): pods "nginx-sandbox" not found` and seemingly it is due to "calico daemonset watch apiserver to get a list of pods, and apply network configuration based on the pod spec."
> 
> So, the page [Debugging Kubernetes nodes with crictl](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/) may be deleted or the list of sections below removed:
> 
> * [Run a pod sandbox](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#run-a-pod-sandbox)
> * [Create a container](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#create-a-container)
> * [Start a container](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#start-a-container)

As per my investigation, all example commands work fine in the [Documentation](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/) except for the mentioned sections. As per the referenced issue, I think it should be safe to delete the specific sections instead of a whole page. The documentation also has a warning message under [Example crictl commands](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#example-crictl-commands) section which refers to the sections that need to be deleted. So, if these sections are to be deleted then the warning message should be deleted as well.

**Comment by Aaina26** [comment]
[crictl documentation](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#example-crictl-commands) still has the same example as included in [Debugging Kubernetes nodes with crictl](https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/). So it can very well be a bug.

/cc @saschagrunert Would it be okay to delete these sections in the documentation? If so I would like to raise a PR for the same.
