### ISSUE TITLE
Upgrading kubeadm clusters - version notes out of date

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/website#44674]
Now that this has merged:
  https://github.com/kubernetes/kubernetes/pull/120825

The documentation needs to be upgraded to let folks know node versions can be behind more then 1.

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/_

**Comment by neolit123** [comment]
> Now that this has merged: [kubernetes/kubernetes#120825](https://github.com/kubernetes/kubernetes/pull/120825)
> 
> The documentation needs to be upgraded to let folks know node versions can be behind more then 1.

it's kubelet versions to be precise, but kubeadm has no way to catch and verify what version of the kubelet the user deployed today. as can be seen in the doc here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
kubelet upgrade happens out-of-band (after kubeadm upgrade has finished).

that's a bit of a design problem...

there were some AIs and some discussion here:
https://github.com/kubernetes/kubeadm/issues/2924
https://github.com/kubernetes/kubeadm/issues/2626

we currently have e2e tests that verify the kubeadm vs kubelet skew, but there are some gotchas around kubelet flags.
i'd claim the whole https://github.com/kubernetes/kubernetes/pull/120825 change as supported, but i'm tentative around calcimining it more widely in the docs.

perhaps we can say something like this in a small note near the top:
- it's recommended to match your kubelet and kubeadm versions, but you can also use an older kubelet version
- and link to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#kubeadm-s-skew-against-the-kubelet

**Comment by neolit123** [comment]
PRs welcome

**Comment by pegasas** [comment]
/assign @pegasas 
I will raise an PR for fixing this.

**Comment by pegasas** [comment]
PR merge.
Request to close this issue.
/close
