### ISSUE TITLE
Remove mention of `hostPort` in the examples on "Configure Liveness, Readiness and Startup Probes"

### ISSUE THREAD

**Issue by ubergeek42** [kubernetes/website#44687]
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#use-a-named-port

In this section of the docs, the example yaml shown include both `containerPort` and `hostPort`.
> You can use a named port for HTTP and TCP probes. gRPC probes do not support named ports.
> For example:
> ```yaml
> ports:
> - name: liveness-port
>   containerPort: 8080
>   hostPort: 8080            # <- this seems like a footgun for people copying from the docs
> 
> livenessProbe:
>   httpGet:
>     path: /healthz
>     port: liveness-port
> ```

We recently saw a case where someone copy/pasted from the docs, and then our cluster scaled up adding a bunch of nodes because the recently modified pod could only run one per node due to the `hostPort`. There's nothing warning/suggesting that you don't actually need a `hostPort` on the page, so it seems like an easy thing for newer people to trip over.

**Comment by adityasamant25** [comment]
The concern is valid and also mentioned in the [Configuration Best Practices for Services](https://kubernetes.io/docs/concepts/configuration/overview/#services).

I will issue a PR for this.
