### ISSUE TITLE
Document default settings for `imagefs.inodesFree` in EvictionHard

### ISSUE THREAD

**Issue by vaibhav2107** [kubernetes/website#44695]
**This is a Feature Request**

As this [PR](https://github.com/kubernetes/kubernetes/pull/121834) is merged now, the EvictionHard docs should be updated to include imagefs.inodesFree

**What would you like to be added**
Adding default settings of imagefs.inodesFree  in [Hard eviction thresholds](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md#hard-eviction-thresholds-hard-eviction-thresholds)

Page to update: https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md

**Why is this needed**
If the user is using separate filesystem for images, it helps to monitor disk pressure if inodes run out on the ImageFs.

**Comment by sftim** [comment]
/retitle Document default settings for `imagefs.inodesFree` in EvictionHard

**Comment by vaibhav2107** [comment]
This issue is fixed by the PR #44696 and hence we can close this one
