### ISSUE TITLE
"Using CoreDNS for Service Discovery" page points to deprecated CoreDNS installation instructions

### ISSUE THREAD

**Issue by Hobbit44** [kubernetes/website#44718]
It looks like the link you use for the install docs for CoreDNS lead to a deprecated page: 

https://kubernetes.io/docs/tasks/administer-cluster/coredns/#installing-coredns
Leads to
https://github.com/coredns/deployment/tree/master/kubernetes

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/tasks/administer-cluster/coredns
/language en

**Comment by dipesh-rawat** [comment]
/retitle "Using CoreDNS for Service Discovery" page points to deprecated CoreDNS installation instructions

**Comment by dipesh-rawat** [comment]
Looks like a fix was delivered as part of https://github.com/kubernetes/website/pull/44733

/close
