### ISSUE TITLE
Remove alpha reference from `PersistentVolumeStatus. lastPhaseTransitionTime` docs

### ISSUE THREAD

**Issue by BBBmau** [kubernetes/website#44711]
**This is a Bug Report**

**Problem:**
PersistentVolumeLastPhaseTransitionTime was recently graduated to beta but is still left as alpha in this part of the doc
https://github.com/kubernetes/kubernetes/pull/120627

**Proposed Solution:**
Remove alpha reference

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#:~:text=lastPhaseTransitionTime%20is%20the%20time%20the%20phase%20transitioned%20from%20one%20to%20another%20and%20automatically%20resets%20to%20current%20time%20everytime%20a%20volume%20phase%20transitions.%20This%20is%20an%20alpha%20field%20and%20requires%20enabling%20PersistentVolumeLastPhaseTransitionTime%20feature.

**Comment by RomanBednar** [comment]
This is generated from API comments, PR for removing it is opened here: https://github.com/kubernetes/kubernetes/pull/122728
