### ISSUE TITLE
Configure a Pod to Use a ConfigMap

### ISSUE THREAD

**Issue by pinakig22** [kubernetes/website#44728]
In [Project keys to specific paths and file permissions](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#project-keys-to-specific-paths-and-file-permissions), it mentions this [Secret](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod) guide explains the syntax. 

However the above Secret link doesn't mention anything on "specific paths" & file permission is defined [here](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#set-posix-permissions-for-secret-keys).

Appreciate feedback and update (correction) to documentation.

**Comment by sftim** [comment]
/remove-kind bug

I think this is a request to mention POSIX permissions for the volume and its files, within the task page “Configure a Pod to Use a ConfigMap”. Is that right @pinakig22 ?

If that covers everything you want to see changed, please state that so we're sure. If you want another change as well, please be as clear as you can about what improvement you'd like.

/language en
