### ISSUE TITLE
Update update-imported-tutorials.py to export manifests

### ISSUE THREAD

**Issue by cody-clark** [kubernetes/website#4474]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
`update-imported-tutorials.py` currently only exports tutorials. We now use  {% include %} for `.yaml` files instead of leaving them in the docs, so some files aren't making it to the docs repo.

**Proposed Solution:**
Please update `update-imported-tutorials.py` to export manifests, too.  

**Page to Update:**
kubernetes.github.io/update-imported-tutorials.py

**Comment by tengqm** [comment]
Looks like the said file has been killed.
