### ISSUE TITLE
[es] localize content/en/docs/concepts/services-networking/ingress.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#44743]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/concepts/services-networking/ingress.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by anyulled** [comment]
Me puedes asignar este a mi?

**Comment by ramrodo** [comment]
This issue was fixed by https://github.com/kubernetes/website/pull/44956
