### ISSUE TITLE
Tutorial Inconsistency: Deletion of service in "Using a Service to Expose Your App"  hinders progression in "Running Multiple Instances of Your App" tutorial

### ISSUE THREAD

**Issue by Daisy-Itzos** [kubernetes/website#44749]
Hello I found an inconsistency in the Kubernetes Tutorial.
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

When following the steps for exposing an app it deletes the service in the end. When following up on the next page:
"Once you're ready, move on to [Running Multiple Instances of Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/)."

There seems to be the expectancy of an existing service, which got deleted in the previous steps.

    Step 3: Deleting a service:
        You deleted the service associated with the deployment.

    Following step: Load Balancing:
        The tutorial then expects you to use the deleted service to check load balancing, which is not possible. The $NODE_PORT variable is set using the deleted service. First the service should be re-created.
        
        Kind regards.
Daisy

**Comment by dipesh-rawat** [comment]
/retitle Tutorial Inconsistency: Deletion of service in "Using a Service to Expose Your App"  hinders progression in "Running Multiple Instances of Your App" tutorial

**Comment by Gauravpadam** [comment]
@Daisy-Itzos the documentation does mention a note at the start of the page

>NOTE If you are trying this after [the previous section ](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/), you may need to start from [creating a cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) as the services may have been deleted

Would adding more emphasis to this note address your request?

**Comment by adityasamant25** [comment]
> NOTE If you are trying this after [the previous section ](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/), you may need to start from [creating a cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/) as the services may have been deleted
> 
This note is a bit mis-leading as it instructs the reader to start from scratch by [creating a cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/), whereas just the recreation of the NodePort service using the below command would suffice.
`kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080`

Modifying the note accordingly would help to address the issue.

**Comment by Gauravpadam** [comment]
/triage accepted
Fixes are welcome

**Comment by Gauravpadam** [comment]
I won't say the documentation is _wrong_ here, but things can be improved
/kind feature
