### ISSUE TITLE
[pt-br] Install Kubeadm page in Brazilian Portuguese is outdated

### ISSUE THREAD

**Issue by KavySolucoes** [kubernetes/website#44765]
The session about get certificate is dedepracate on ubuntu 22.04

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm
/language pt

**Comment by utkarsh-singh1** [comment]
Check out this note in [English version](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) - 

> The legacy package repositories (apt.kubernetes.io and yum.kubernetes.io) have been [deprecated and frozen starting from September 13, 2023](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/). Using the [new package repositories hosted at pkgs.k8s.io](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/) is strongly recommended and required in order to install Kubernetes versions released after September 13, 2023. The deprecated legacy repositories, and their contents, might be removed at any time in the future and without a further notice period. The new package repositories provide downloads for Kubernetes versions starting with v1.24.0.

**Comment by stormqueen1990** [comment]
/triage accepted

The Portuguese page needs to be updated in sync with the English manual.

**Comment by stormqueen1990** [comment]
/retitle [pt-br] Install Kubeadm page in Brazilian Portuguese is outdated

**Comment by seilorjunior** [comment]
@stormqueen1990 if you want i can rewrite the pt-br for that.

**Comment by stormqueen1990** [comment]
> @stormqueen1990 if you want i can rewrite the pt-br for that.

@seilorjunior feel free to take this up and work on it if you're interested.

**Comment by ricardoamaro** [comment]
@stormqueen1990 I can try to help on this

**Comment by edsoncelio** [comment]
Hi folks, Is anyone working on this issue?

**Comment by utkarsh-singh1** [comment]
@ricardoamaro, Can you confirm are you working on this ?

> @stormqueen1990 I can try to help on this

**Comment by ricardoamaro** [comment]
@edsoncelio we learned that the pt-pt team formalization will still take some time, so this remains as pt-br if no one disagrees and we can help each others meanwhile 🤗

**Comment by edsoncelio** [comment]
Okays, thanks @ricardoamaro!
Let me know If you need some help :D

**Comment by ricardoamaro** [comment]
Created a PR in https://github.com/kubernetes/website/pull/46001
Feel free to give your suggestions, improvements, reviews, etc

**Comment by ricardoamaro** [comment]
https://github.com/kubernetes/website/pull/46001 has been merged! This issue can be closed

**Comment by stormqueen1990** [comment]
/close

Solved via #46001
