### ISSUE TITLE
[hi] translate content/en/docs/concepts/architecture/control-plane-node-communication.md in hindi

### ISSUE THREAD

**Issue by swastik959** [kubernetes/website#44762]
**This is a Feature Request**

**What would you like to be added**

translate content/en/docs/concepts/architecture/control-plane-node-communication.md in hindi
**Why is this needed**
there is no translation of content/en/docs/concepts/architecture/control-plane-node-communication.md in hindi
**Comments**

/kind feature
/language hi
/sig docs
/area localization

**Comment by dipesh-rawat** [comment]
It seems that there is already an issue https://github.com/kubernetes/website/issues/39548 (with a slightly broader scope) requesting a similar localization of files under the `content/en/docs/concepts/architecture` directory. Additionally, there is a pull request (PR https://github.com/kubernetes/website/pull/44260) addressing the localization of this specific page.

**Comment by niranjandarshann** [comment]
@swastik959 
Same issue is already raised #39548
