### ISSUE TITLE
Pod Topology Spread Constraints mermaid diagrams not rendering

### ISSUE THREAD

**Issue by elmiko** [kubernetes/website#44768]
seems like all the mermaid diagrams on this page have some sort of syntax error, they all render like this:

![image](https://github.com/kubernetes/website/assets/190649/e59af0b6-1797-4244-8fb7-5e42c7ac438f)

page link, https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/

**Comment by sftim** [comment]
Hi. This is a duplicate report. Please add a :+1: reaction to the original issue if you want to upvote it.

/triage duplicate.

**Comment by elmiko** [comment]
thanks @sftim , apologies for the noise.
