### ISSUE TITLE
Update Federation Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4476]
The following topics can probably be consolidated or blended into existing topics. Each topic says something like, "Federated  &lt;thing&gt; is the same as regular &lt;thing&gt; except you submit requests to the Federation API server instead of the API server for an individual cluster."
- [ ] Federated ConfigMap
- [ ] Federated DaemonSet
- [ ] Federated Deployment
- [ ] Federated Events
- [ ] Federated Namespaces
- [ ] Federated ReplicaSets
- [ ] Federated Secrets

One option is to blend the federation information for &lt;thing&gt; into the regular Task topic for &lt;thing&gt;. For example, a Task topic about ConfigMap could cover both regular ConfigMap and federated ConfigMap.

Another option would be to have a single topic that explains how to send a request to the federated API server. That topic could include a list of commands that briefly demonstrate how to create a &lt;thing&gt; in a federation of clusters.

As you consolidate or blend topics, think about whether they are for app developers or cluster administrators. If a topic is primarily for cluster administrators, place it under Tasks > Administer a Cluster.

- [ ] Study this topic: [Set up Cluster Federation with Kubefed](https://kubernetes.io/docs/tasks/federation/set-up-cluster-federation-kubefed/). Find a home for this topic that indicates it is for cluster administrators, not for app developers. For example, you could rename the Administer a Cluster section to Administer Clusters. A topic about setting up cluster Federation would fit nicely in a section named Administer Clusters. Or you might decide that we should have a section named Administer Federated Clusters. Test the topic for accuracy. Put the topic into the new Task template. Edit the topic to comply with our style guide. Think about whether the topic is the right size. Should some of the content be separated out into smaller tasks? If possible, make the topic into a set of steps that the reader can actually do. This might be tricky with federation, and under Before you Begin, you would have to specify requirements that include having at least two clusters.

- [ ] Study this topic: [Set up CoreDNS as DNS Provider for Cluster Federation](https://kubernetes.io/docs/tasks/federation/set-up-coredns-provider-federation/). Find a home for this topic that indicates it is for cluster administrators, not for app developers. Put the topic into the new Task template. Edit the topic to comply with our style guide; this topic has a lot of passive voice and future tense. Make sure that the Before you begin section is adequate; does the reader need to have two clusters? Include links to CoreDNS and Helm. If possible, test the topic for accuracy. If possible, make the topic into a set of steps that the reader can actually do.

- [ ] Study this topic: [Set up placement policies in Federation](https://kubernetes.io/docs/tasks/federation/set-up-placement-policies-federation/). Find a home for this topic that indicates it is for cluster administrators, not for app developers. Put the topic into the new Task template. Edit the topic to comply with our style guide. Make sure that the Before you begin section is adequate; does the reader need to have two clusters? If possible, test the topic for accuracy. If possible, make the topic into a set of steps that the reader can actually do.

- [ ] Study this topic: [Cross-cluster Service Discovery Using Federated Services](https://kubernetes.io/docs/tasks/federation/federation-service-discovery/). Find a home for this topic that indicates it is for cluster administrators, not for app developers. Put the topic into the new Task template. Edit the topic to comply with our style guide. If possible, test the topic for accuracy. If possible, make the topic into a set of steps that the reader can actually do.

- [ ] Study this Concept topic: [Federation](https://kubernetes.io/docs/concepts/cluster-administration/federation/). Edit the topic for style. Test for accuracy if possible. Include links to related Task topics.

- [ ] Look at the overall body of topics related to federation. Do we have the right set of topics? Have we covered all the important points?. Is there overlap that could be reduced?

**Comment by seperry53test** [comment]
@steveperry-53, Please assign this issue to me.

**Comment by steveperry-53** [comment]
Note: This issue is available to be taken.
@seperry53test is not working on this issue.

**Comment by heidecke** [comment]
# [WIP] Checklist

## Sub Topic Content

Consolidate content to existing API documentation.

- [ ] Federated ConfigMap
- [ ] Federated DaemonSet
- [ ] Federated Deployment
- [ ] Federated Events
- [ ] Federated Namespaces
- [ ] Federated ReplicaSets
- [ ] Federated Secrets

## Cleanup

- [ ] Move images to correct location
- [ ] Add redirects for each moved/deprecated page
- [ ] Remove deprecated includes

**Comment by DanyC97** [comment]
/sig multicluster
/language en

@marun @pmorie @steveperry-53 am i right in saying that now with v1 docs being deprecated is safe to close this issue ?

**Comment by marun** [comment]
@DanyC97 Yes, this issue can be closed.

**Comment by DanyC97** [comment]
thank you @marun for quick response, much appreciated !
/close
