### ISSUE TITLE
[hi] translate content/en/docs/concepts/architecture/cgroups.md in hindi 

### ISSUE THREAD

**Issue by swastik959** [kubernetes/website#44760]
**This is a Feature Request**
 

**What would you like to be added**

translate content/en/docs/concepts/architecture/cgroups.md in hindi 
**Why is this needed**
there is no translation of content/en/docs/concepts/architecture/cgroups.md  in hindi
**Comments**

/kind feature
/language hi
/sig docs
/area localization

**Comment by dipesh-rawat** [comment]
It seems that there is already an issue https://github.com/kubernetes/website/issues/39548 (with a slightly broader scope) requesting a similar localization of files under the `content/en/docs/concepts/architecture` directory. Additionally, there is a pull request (PR https://github.com/kubernetes/website/pull/44258) addressing the localization of this specific page.

**Comment by divya-mohan0209** [comment]
@swastik959 : Please check the list of issues already raised before raising new ones for the Hindi localization. Thanks!
/close
