### ISSUE TITLE
[hi] translate content/en/docs/concepts/architecture/cloud-controller.md in hindi 

### ISSUE THREAD

**Issue by swastik959** [kubernetes/website#44761]
**This is a Feature Request**

**What would you like to be added**

translate content/en/docs/concepts/architecture/cloud-controller.md in hindi
**Why is this needed**
there is no translation of content/en/docs/concepts/architecture/cloud-controller.md  in hindi
**Comments**

/kind feature
/language hi
/sig docs
/area localization

**Comment by dipesh-rawat** [comment]
It seems that there is already an issue https://github.com/kubernetes/website/issues/39548 (with a slightly broader scope) requesting a similar localization of files under the `content/en/docs/concepts/architecture` directory. Additionally, there is a pull request (PR https://github.com/kubernetes/website/pull/44259) addressing the localization of this specific page.

**Comment by niranjandarshann** [comment]
Even Same issue is already raised in issue #39548.

**Comment by divya-mohan0209** [comment]
Hello @swastik959 , would request that you go through the issues section before raising duplicate issues for the Hindi localization.
Closing this one out, since there's already one issue tracking the same activity.
/close
