### ISSUE TITLE
Add hover effect on video in case studies

### ISSUE THREAD

**Issue by AmarNathChary** [kubernetes/website#44769]
**This is a feature request**
Add hover effect on `Kubernetes at box`  video in [case studies](https://kubernetes.io/case-studies/) for user-friendly design

**Image of a related issue**
![Screenshot from 2024-01-17 12-10-57](https://github.com/kubernetes/website/assets/117257033/d5efc27f-e5bc-4c7f-b83a-4ba9709f0b12)

**Comment by AmarNathChary** [comment]
Raised PR at #44770

**Comment by sftim** [comment]
/priority awaiting-more-evidence

I don't object, but I think the site is fine if we don't do this.

**Comment by AmarNathChary** [comment]
> I don't object, but I think the site is fine if we don't do this.

@sftim While I agree with you, I also think that introducing a hover effect could improve the overall user-friendly design.

**Comment by sftim** [comment]
This doesn't feel like a priority

/close not-planned
