### ISSUE TITLE
Update docs for Ingress and other types of external access

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4478]
**This is a...** 
- [ x] Feature Request
- [ ] Bug Report

Study [this Concept topic](https://kubernetes.io/docs/concepts/services-networking/ingress/), and understand what's going on with Ingress. Understand the difference between an Ingress and a Service of type LoadBalancer. Create one or more Task topics about Ingress, and remove task-like content from [this Concept topic](https://kubernetes.io/docs/concepts/services-networking/ingress/). The new Task topics should probably go under Tasks > Access Applications in a Cluster, along with topics like [Use a Service to Access an Application in a Cluster](https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/). Figure out what to do with this topic: [Create an External Load Balancer](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/). As you work on the Ingress topics, look at the entire set of topics under  Tasks > Access Applications in a Cluster. Have we covered the different kinds a application access in the best way? Do the topics have the best titles? Is this the correct list of ways to access and application: Service of type ExternalName, Service of type ClusterIP, Service of type NodePort, Service of type LoadBalancer, Ingress? Figure out which of the external access methods require a cloud provider. Decide which topics belong in the kubernetes.io docs and which belong in the various cloud provider docs. If a task requires a cloud provider, make that clear in the Before you begin section.

**Comment by zacharysarah** [comment]
Closed by #12465
