### ISSUE TITLE
kube-apiserver: documentation not clear regarding the --enable-admission-plugins option

### ISSUE THREAD

**Issue by StCyr** [kubernetes/website#44790]
(auto-generated) Documentation states:

"--enable-admission-plugins option: admission plugins that should be enabled in addition to default enabled ones"

(https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)

It's not clear what happens if you specify one of the default ones. 

For example with:

`--enable-admission-plugins=NodeRestriction`

Is the `Noderestriction` admission plugin is the sole plugin enabled? Or, are all the default enabled admission settings still enabled (ie: the option doesn't do anything)?

I guess it's a dumb question but I've inherited from a running cluster with this setting and I've no idea if the other default admission plugins are enabled or not (ie: I have trouble with ValidatingAdmissionWebhook and I don't even know if the plugin is enabled)

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/_

**Comment by thisisharrsh** [comment]
`--enable-admission-plugins=NodeRestriction` does not disables the other default admissions plugins. It only guarantees that `NodeRestrictions ` is explicitly enables.

**Comment by thisisharrsh** [comment]
The other default plugins will remain enables unless you explicitly disables them using the `--disable-admission-plugins` flag.

**Comment by aj11anuj** [comment]
This issue is more like a query than a documentation problem. [K8s slack channel](https://communityinviter.com/apps/kubernetes/community) will be a better place for clarifying queries and doubts then here.

/kind support
/sig docs
/close not-planned

Feel free to reopen if you think an essential part of documentation regarding it is missing that should be documented.
