### ISSUE TITLE
Update etcd docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4479]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

Study this topic and related topics: [Operating etcd clusters for Kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/).
Bring all of the etcd content into a coherent set of topics. Check for accuracy, and update as needed. Put topics into the appropriate templates. Edit topics to comply with our style guide.

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by Aut0R3V** [comment]
Actually where exactly are the deviations from the style guide?

**Comment by sftim** [comment]
/triage accepted

I don't see any obvious _style_ concerns.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#before-you-begin is wrong: you can't practice operating an etcd cluster _for Kubernetes_ within a Katacoda playground, at least not unless you get **very** technical.
