### ISSUE TITLE
CNCF Landscape iframe uses wrong colors

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#44803]
**This is a Bug Report**

**Problem:**
https://github.com/kubernetes/website/blob/06fb191b99a1a248cc8c697cd5170aea195412cd/layouts/shortcodes/cncf-landscape.html uses the wrong background color(s); it's `#d95e00` but should be `#3371e3` (Kubernetes blue). I think the orange color was copied from https://github.com/kubernetes/website/blob/06fb191b99a1a248cc8c697cd5170aea195412cd/data/announcements/scheduled.yaml#L214 by mistake.

**Proposed Solution:**
Revise the shortcode. Consider making the color be set once and then reused (“[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)”).

**Page to Update:**
You would see the change on https://kubernetes.io/partners/

We should use blue backgrounds whether or not an announcement banner is showing.

**Additional Information:**
PR https://github.com/kubernetes/website/pull/44792 updated the shortcode.

/area web-development
/triage accepted
/priority backlog

---

If fixing this, consider also moving the iframe scroll-margin-top fix to be more general.
See https://github.com/kubernetes/website/pull/44792#discussion_r1458153262 and https://github.com/kubernetes/website/issues/29909

**Comment by sftim** [comment]
@cynthia-sg this is a nit against PR https://github.com/kubernetes/website/pull/44792 but fixing it isn't at all urgent.

**Comment by sftim** [comment]
/lifecycle frozen

We should fix this eventually.

**Comment by steve-hardman** [comment]
I would like to help with this.

/assign
