### ISSUE TITLE
Update Networking docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4480]
**This is a...** 
- [x ] Feature Request
- [ ] Bug Report

Study this topic and related topics: [Cluster Networking](https://kubernetes.io/docs/concepts/cluster-administration/networking/).
Bring all of the networking content into a coherent set of topics. Check for accuracy, and update as needed. Put topics into the appropriate [templates](https://kubernetes.io/docs/home/contribute/page-templates/). Edit topics to comply with our [style guide](https://kubernetes.io/docs/home/contribute/style-guide/).
Here's one related topic: [Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/).

**Comment by chuckha** [comment]
The Network Policies page is quite informative. I like the overall layout. I see [another issue](https://github.com/kubernetes/website/issues/6164) for creating more examples which would be great, but the main content is mostly very clear. I think there are a few spots that could use an update after reading through it. These are just suggestions, feel free to ignore!

cc @Bradamant3 

* The second sentence on the Network Policies page makes it sound like Network Policies are only for controlling ingress "...and define rules which specify what traffic is allowed to the selected pods."
* [Bullet number 3](https://github.com/kubernetes/website/blob/master/docs/concepts/services-networking/network-policies.md#the-networkpolicy-resource) is a little ambiguous, specifically the "..from any pod in a namespace.."

**Comment by Bradamant3** [comment]
See also [Declare Network Policy](https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/)

**Comment by radhikapc** [comment]
Here is a request from @ahmetb on twitter at https://twitter.com/ahmetb/status/967850257018101760 to add the content that he has created at https://github.com/ahmetb/kubernetes-network-policy-recipes to official Kubernetes docs.

**Comment by radhikapc** [comment]
Related pages:
https://kubernetes.io/docs/concepts/services-networking/network-policies/
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
https://kubernetes.io/docs/concepts/services-networking/ingress/
https://kubernetes.io/docs/concepts/services-networking/service/
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/
https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
https://kubernetes.io/docs/concepts/cluster-administration/addons/
https://kubernetes.io/docs/concepts/cluster-administration/network-plugins/
