### ISSUE TITLE
[Documentation] kubeadm / kubelet compatibility

### ISSUE THREAD

**Issue by dxlusby** [kubernetes/website#44812]
Documentation for [Creating a cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#kubeadm-s-skew-against-the-kubelet) describes n or n-1 compatibility between kubeadm and kubelet versions, but the example provided shows n, n-1, n-2, or n-3 compatibility.

Expected Result: Description and example should agree on the proper version compatibility between kubeadm and kubelets

See image below for snapped reference
---

![image](https://github.com/kubernetes/website/assets/8630843/0c6dec87-b6f6-4dd0-90af-1904622b55b0)

**Comment by neolit123** [comment]
PRs welcome to fix this. should be "the same version as kubeadm or 3 versions older"
/help

please ping @pacoxu for review.

**Comment by neolit123** [comment]
@Affan-7 not clear why you closed the PR.

just this text change was needed, from:
> version as kubeadm or one version older.

to:
> version as kubeadm or up to three minor versions older.

**Comment by neolit123** [comment]
help-wanted still.

**Comment by Affan-7** [comment]
Sorry my bad. I thought that the PR is not creating much impact, it's just a typo, that's why I closed it.

**Comment by Affan-7** [comment]
I wanted to do some meaningful contributions, preferably code contributions.

(Let me just re-open this pr)
