### ISSUE TITLE
Add banner for KubeCon 2024 EU

### ISSUE THREAD

**Issue by nate-double-u** [kubernetes/website#44827]
**This is a Feature Request**

**What would you like to be added**

Set a banner to announce KubeCon 2024 EU

**Why is this needed**

We usually turn on a banner for the upcoming KubeCon about 4 weeks ahead of the event, but I've had a request that we run it a bit earlier. Is 8 weeks possible?

Logos are available from: https://github.com/cncf/artwork/tree/main/other/kubecon-cloudnativecon/2024-eu (Note: be sure to copy the logo into this repo)

https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/ should help with text. Also see the [banner](https://github.com/kubernetes/website/blob/85cbd9d9e5ca49b44b91a3ffb29b99adf0ac4761/data/announcements/scheduled.yaml#L85-L94) config from a previous year's KubeCon.

**Comments**

This change will need @kubernetes/steering-committee approval.

I would like to set the banner to start on the Jan 26, 2024 and to end on the March 22, 2024 at 1800 CET (UTC+1). If 8 weeks isn't possible, the 4 week dates are Feb 23, 2024 to March 22, 2024.

/priority important-soon

**Comment by dipesh-rawat** [comment]
It's worth noting that the existing [legacy Linux package announcement](https://github.com/kubernetes/website/blob/68047be94af95ba1373695a478b3eb40d06eecaa/data/announcements/scheduled.yaml#L211) banner is scheduled to run until Feb 1. Considering this, we might want to keep the KubeCon EU 2024 banner active after that date. How about initiating the banner from Feb 16? This would give us approximately a month (5 weeks) before KubeCon kicks off on March 19, 2024.

**Comment by steve-hardman** [comment]
I want to help with this.

/assign

**Comment by steve-hardman** [comment]
PR https://github.com/kubernetes/website/pull/44828 is created to help with this request. Please do review whenever you have the time. Thanks in advance!

**Comment by nate-double-u** [comment]
> How about initiating the banner from Feb 16? This would give us approximately a month (5 weeks) before KubeCon kicks off on March 19, 2024.

I'd appreciate 5 weeks too
