### ISSUE TITLE
Deleting PersistentVolumeLabel because its deprecated from this page https://kubernetes.io/docs/setup/best-practices/multiple-zones/ 

### ISSUE THREAD

**Issue by hassanbenhzaine** [kubernetes/website#44833]
**This is a Feature Request**

**What would you like to be added**
PersistentVolumeLabel mentioned in this page https://kubernetes.io/docs/setup/best-practices/multiple-zones/
should be removed because this admission controller is now deprecated according to this page 
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#persistentvolumelabel

**Why is this needed**
For documentation to stay up to date

**Comments**
No

**Comment by tamilselvan1102** [comment]
page to be updated: https://kubernetes.io/docs/setup/best-practices/multiple-zones/

**Comment by sftim** [comment]
Rather than plain _delete_, I recommend replacing that text with something appropriate for Kubernetes in 2024. Do you support that approach @hassanbenhzaine ?

**Comment by hassanbenhzaine** [comment]
@sftim yes I do, i will see what i can do about it

**Comment by hassanbenhzaine** [comment]
@sftim I made this pull request that contain updated paragraph instead of juste removing PersistentVolumeLabel
https://github.com/kubernetes/website/pull/44910

**Comment by vaibhav2107** [comment]
I think the PR #44910 resolves this issue and can hence can be closed
