### ISSUE TITLE
Inconsistent name in the DNS horizontal autoscaling example

### ISSUE THREAD

**Issue by 604691021** [kubernetes/website#44855]
dns-horizontal-autoscaler.yaml 中 用的kube-dns-autoscaler 后续命令中用的dns-autoscaler  2个名字混淆不同步

**Comment by tamilselvan1102** [comment]
please describe the issue in English

**Comment by tamilselvan1102** [comment]
page related to the issue: https://kubernetes.io/zh-cn/docs/tasks/administer-cluster/dns-horizontal-autoscaling/

**Comment by mengjiao-liu** [comment]
> dns-horizontal-autoscaler.yaml 中 用的kube-dns-autoscaler 后续命令中用的dns-autoscaler 2个名字混淆不同步

Translate to English:
The kube-dns-autoscaler used in dns-horizontal-autoscaler.yaml and the dns-autoscaler used in subsequent commands are confused and out of sync.

It seems that the English version also has this problem.

/triage accepted
/kind bug

/retitle  Inconsistent name in the DNS horizontal autoscaling example
