### ISSUE TITLE
Welcome to Migration Center – Migration Center – Native Devnet – Google Cloud console

### ISSUE THREAD

**Issue by BothHybrid2022** [kubernetes/website#44854]
https://console.cloud.google.com/migration/onboarding?gtm_source=documentation&gtm_source_id=overview&_ga=2.172326563.129277815.1705987681-2122884959.1705599370&project=native-devnet&pli=1

**Comment by thisisharrsh** [comment]
Hi @BothHybrid2022 Please describe the issue you are facing in the [description](https://github.com/kubernetes/website/issues/44854#issue-2095276824) section of the issue.

**Comment by divya-mohan0209** [comment]
This seems to be a spam issue & I'll be closing it since there's also a lack of relevant information. 
/close
