### ISSUE TITLE
Norm to not use namespaces in small teams

### ISSUE THREAD

**Issue by jackzellweger** [kubernetes/website#44863]
This part of the documentation implies that namespaces are not generally used on smaller teams. This may be true in some cases, but namespaces provide important security boundaries and logical isolation for, say, open source projects that you might be running in your cluster.

[[ref.](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#when-to-use-multiple-namespaces)]
> For clusters with a few to tens of users, you should not need to create or think about namespaces at all.

I think this sentence could be omitted for clarity as it could be misleading in some contexts!

**Comment by steve-hardman** [comment]
I can help with removal of the non helpful comment mentinoend in the issue.

/assign

**Comment by jackzellweger** [comment]
Hey @steve-hardman! This is my first time opening up and issue, and I'm interested in contributing. Could I open up a PR, and have you review it? Would be great to have your eyes on it before I merge!

**Comment by aj11anuj** [comment]
/kind feature
/sig docs
/assign @jackzellweger
As no has raised a PR yet, you are free to open it. But try to improve overall documentation of that page rather than fixing 1-2 words in a sentence.

**Comment by steve-hardman** [comment]
>  This is my first time opening up an issue, and I'm interested in contributing. Could I open up a PR

Sure please go ahead with fixing it!

**Comment by jackzellweger** [comment]
@steve-hardman @aj11anuj  Thanks! Am on it.
