### ISSUE TITLE
Link to Go client library takes readers to source code on GitHub

### ISSUE THREAD

**Issue by erikh** [kubernetes/website#44867]
Hi again, you should update the URL for the client library for golang.

The URL specified on the site is `github.com/kubernetes/client-go`. This is the error I get when trying to import it in a way that is expected by golang engineers:

```
% go get github.com/kubernetes/client-go@latest
go: downloading github.com/kubernetes/client-go v0.29.1                                                                                
go: github.com/kubernetes/client-go@latest (v0.29.1) requires github.com/kubernetes/client-go@v0.29.1: parsing go.mod:                 
        module declares its path as: k8s.io/client-go                                                                                  
                but was required as: github.com/kubernetes/client-go
```

**Comment by steve-hardman** [comment]
I see in page the Client Library column link [github.com/kubernetes/client-go/](https://github.com/kubernetes/client-go/) leads to readme and in that there is option on how to use the library.

> To get the latest version, use go1.16+ and fetch using the go get command. For example:
> 
> go get k8s.io/client-go@latest


Maybe we rename the Column header to make it more better and clearer.

**Comment by erikh** [comment]
It's possible I missed or didn't consider the thought that installation docs should be available on the respective repositories. I guess that's a perk/curse of using golang in this situation. :)

I hope I haven't made too much noise here. Maybe just ensuring (I haven't looked again) that everyone knows installation & usage documentation are in the respective links, that should solve the problem and we can close this ticket.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

I don't think there is a bug. Maybe people who code in Go will assume that the hyperlink is something you can put into code, but our actual intent is for people reading the website to click there and continue reading.

**Comment by sftim** [comment]
/retitle Link to Go client library takes readers to source code on GitHub

**Comment by tamilselvan1102** [comment]
go get commend is deprecated from Go 1.17.  Refer this page https://go.dev/doc/go-get-install-deprecation
instead of go get use following steps to import the project.
1. git clone https://github.com/kubernetes/client-go/
2. cd client-go
3.go install -v

following docs also need to be updated
https://github.com/kubernetes/client-go/blob/master/INSTALL.md

**Comment by erikh** [comment]
that is incorrect. Please read the documentation for go get​.
