### ISSUE TITLE
Incorrect credential name set for kubelet.conf in External CA mode

### ISSUE THREAD

**Issue by vrutkovs** [kubernetes/website#44876]
**This is a Bug Report**

**Problem:**

Invalid user set for kubelet.conf in external CA mode at https://kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-for-user-accounts

incorrect:
* default-auth

correct:
* `system:node:<nodeName>`

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-for-user-accounts

**Comment by tamilselvan1102** [comment]
i would like to work on it.
/assign

**Comment by neolit123** [comment]
closing in favor of https://github.com/kubernetes/kubeadm/issues/3014
/close
