### ISSUE TITLE
Improvement for k8s.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

### ISSUE THREAD

**Issue by kmathewmk** [kubernetes/website#44884]
The liveness probe docs says

> periodSeconds: How often (in seconds) to perform the probe. Default to 10 seconds. The minimum value is 1.
> timeoutSeconds: Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.

Could you document the behavior if timeoutSeconds is greater than periodSeconds for eg 20s and 10s respectively? Are we likely to see 2 parallel liveness probe requests if the response takes longer than 10s ?

**Comment by dipesh-rawat** [comment]
_Page reported in issue (based on the title):_ https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes
/language en

**Comment by thisisharrsh** [comment]
No, i don't think we will see two parallel liveness probe.

**Comment by thisisharrsh** [comment]
Liveness probe is scheduled independently and the next probe will start right after the previous probe ends.

**Comment by thisisharrsh** [comment]
And it will be better if we can document it properly in the documentation.
