### ISSUE TITLE
Source IP for Services with Type=ClusterIP - does not work

### ISSUE THREAD

**Issue by MarkKharitonov** [kubernetes/website#44888]
Not sure if this is the doc issue or the feature issue. I have already opened a feature issue here - https://github.com/kubernetes/kubernetes/issues/122954

FYI

**Comment by tamilselvan1102** [comment]
related page : https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-clusterip

**Comment by tamilselvan1102** [comment]
Kubernetes Services allows external connection to the internal cluster Pods and also manages internal communication among the Pods within the cluster via different Services type in defined in the ServiceSpec.
These service types are
1. ClusterIP
2. NodePort
3. LoadBalancer

Please refer for ClusterIP Type https://kubernetes.io/docs/concepts/services-networking/cluster-ip-allocation/

**Comment by MarkKharitonov** [comment]
I have found the root cause - linkerd proxy. Described it here - https://github.com/kubernetes/kubernetes/issues/122954#issuecomment-1910482077

It would be helpful though to have a comment in the documentation warning that the presence of a proxy sidecar, like linkerd is likely to change the outcome.
