### ISSUE TITLE
[ko] Translate Update /docs/concepts/workloads/controllers/cron-jobs/ into Korean

### ISSUE THREAD

**Issue by tonyhan18** [kubernetes/website#44894]
This is a Feature Request

# What would you like to be added
Translate Update /docs/concepts/workloads/controllers/cron-jobs/ into Korean
it's too old version

# Why is this needed
update translated version /docs/concepts/workloads/controllers/cron-jobs/  into Korean

> If you accept this i'm gonna make this up-to-date at least this week.
I can do it because I am working with cronjob.

# Labels
/language ko
/assign

# comments
I need an acception
I requests to @seokho-son

**Comment by jihoon-seo** [comment]
@tonyhan18 제안해 주셔서 감사합니다. 하지만, 해당 페이지는 #41631 의 M74 번 항목이며, 이미 @YanyChoi 님께서 작업 의사를 밝히신 이력이 있습니다. 참고해 주시기 바랍니다. :)

**Comment by aj11anuj** [comment]
This issue is a subset of #41631, @tonyhan18 please head to main issue and from there assign yourself the page that you want to localize in Korean language. 
/duplicate
/sig docs
