### ISSUE TITLE
Add Order of precedence for environment variables

### ISSUE THREAD

**Issue by tamilselvan1102** [kubernetes/website#44895]
**This is a Feature Request**
The order of precedence for environment variables is not documented in [Define Environment Variables for a Container] page.

**What would you like to be added**
The order of precedence for environment variables is as follows:
  1. Keys in env field
  2. Keys in envFrom field
  3. Keys defined in the container image

**Why is this needed**
it is important to know the precedence for environment variables

**Comments**

**Comment by tamilselvan1102** [comment]
page need to be updated: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/

**Comment by tamilselvan1102** [comment]
I want to raise a PR if triage accepted.

**Comment by Erbureth** [comment]
I was just looking for the information, couldn't find it on the mentioned page. The information would be immensely helpful to design Kustomize overrides for deployments.

**Comment by tamilselvan1102** [comment]
@Erbureth 
Precedence of environment variables are modified by mutating admission webhook.
Reference:
https://github.com/kubernetes/kubernetes/issues/122950#issuecomment-1938903330

**Comment by tamilselvan1102** [comment]
The precedence is modified by admission webhook.
/close
