### ISSUE TITLE
Reorganize 'Types of volumes' section and incorporate CSI migration details in "Volumes" page

### ISSUE THREAD

**Issue by ziyi-xie** [kubernetes/website#44908]
**This is a Feature Request**

**What would you like to be added**

I think it will be more clear for the users to understand if we reorganize the [content/en/docs/concepts/storage/volumes.md](https://kubernetes.io/docs/concepts/storage/volumes/) page.

There are two things I can come up with at the moment:
・rearrange the contents of 'types of volumes'
・add more information about CSI Migration 

**Why is this needed**

・rearrange the contents of 'types of volumes'
From what's written now, for the description about each plugin, whether we can still use the plugin and how to use them is not very clear. For example, it says[ awsElasticBlockStore (removed)](https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore), and when our users see the word "removed", some might think that this plugin is unusable. However, it's not that it can't be used, and this might cause some misunderstanding and confusion.
Also ephemeral volume types and persistent volumes are interspersed, so maybe it's hard for users to learn from other contents about how to use the plugin.

・add more information about CSI Migration
Since the word 'CSI Migration' has already appeared in the 'types of volumes' section, I think it would be easier to understand if we add information about CSI Migration at the 'Background' section or place the 'csi' section up front.

**Comments**

Above is the method I came up with at this moment. And I'd really appreciated if you could share your opinion and advice about this.

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/concepts/storage/volumes
/language en

**Comment by dipesh-rawat** [comment]
/retitle Reorganize 'Types of volumes' section and incorporate CSI migration details in "Volumes" page

**Comment by niranjandarshann** [comment]
@ziyi-xie  Correct me if i understand wrong:
What i understood is:
1.  you are talking about the deprecated and removed volume type to be removed from the types of volume as it may cause confusion to the user.
2. The description which is available and which can be used (Which is not in deprecated and removed label) should have more description about the plugin its use and scope to use it.
3.  To make it easier to understand, we can either add details about CSI Migration in the 'Background' section or move the 'csi' section to the beginning.

I think if the author required this things then we should think on it as present doc  may cause confusion to the user .
