### ISSUE TITLE
Sign in to GitHub · GitHub

### ISSUE THREAD

**Issue by BothHybrid2022** [kubernetes/website#44911]
"Sign in to GitHub · GitHub" https://github.com/login?allow_signup=false&client_id=e37ffdec11c0245cb2e0&return_to=%2Flogin%2Foauth%2Fauthorize%3Fclient_id%3De37ffdec11c0245cb2e0%26redirect_uri%3Dhttps%253A%252F%252Flogin.live.com%252FHandleGithubResponse.srf%26response_type%3Dcode%26scope%3Dread%253Auser%2B%2Buser%253Aemail%26state%3D81ADD30B5E19E2A7

**Comment by dipesh-rawat** [comment]
/close not-planned

Closing this issue for now. However, if you have any further accurate details regarding the issue with the documentation on https://kubernetes.io or concerning Kubernetes, please feel free to reopen this.
