### ISSUE TITLE
Incorrect link for admission webhook controller

### ISSUE THREAD

**Issue by thisisharrsh** [kubernetes/website#44919]
**This is a Bug Report**

**Problem:** The link for the `admission webhook controller` under [`Pod's setHostnameAsFQDN field`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field) in [`DNS for Services and Pods`](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/) is incorrect. It is redirecting to `https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks` instead of that it should redirect to `https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/` .

 **Proposed Solution:** `admission webhook controller` should redirect to `https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/`  instead of `https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks` .

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/_

**Comment by thisisharrsh** [comment]
I would to link to work on this issue, if triage gets accepted.

**Comment by Gauravpadam** [comment]
/triage accepted

It should ideally change to 
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks

**Comment by thisisharrsh** [comment]
> /triage accepted
> 
> It should ideally change to https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks

Yes, you are right. We should change it to the above link.

**Comment by thisisharrsh** [comment]
The issue is fixed [here](https://github.com/kubernetes/website/pull/44927)

**Comment by dipesh-rawat** [comment]
Fix merged as part of https://github.com/kubernetes/website/pull/44927

/close
