### ISSUE TITLE
Webpage not available

### ISSUE THREAD

**Issue by BothHybrid2022** [kubernetes/website#44921]
"Webpage not available" https://docs.genians.com/nac/6.0/release/en/authentication/integrate-external/saml-okta-adminconsole.html

**Comment by thisisharrsh** [comment]
Hi @BothHybrid2022, This repository is for the Kubernetes documentation website-related issue.

**Comment by thisisharrsh** [comment]
Please close this issue, as it is not related to Kubernetes. You can create another that is related to the Kubernetes documentation website.

**Comment by sftim** [comment]
/triage unresolved

However, if you wanted to tell us about a page on the Kubernetes website that has a broken link: please also mention the URL of the page that needs fixing on Kubernetes' website.
