### ISSUE TITLE
Conflicting information about default StorageClasses

### ISSUE THREAD

**Issue by jeroen-continuum** [kubernetes/website#44932]
The documentation about [storage class ](https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass) mentions the following:
`If you set the [storageclass.kubernetes.io/is-default-class](https://kubernetes.io/docs/reference/labels-annotations-taints/#ingressclass-kubernetes-io-is-default-class) annotation to true on more than one StorageClass in your cluster, and you then create a PersistentVolumeClaim with no storageClassName set, Kubernetes uses the most recently created default StorageClass`

The documentation about [dynamic volume provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#defaulting-behavior) mentions different behavior:
`Note that there can be at most one default storage class on a cluster, or a PersistentVolumeClaim without storageClassName explicitly specified cannot be created.`

**Comment by tamilselvan1102** [comment]
Duplicate of #42176

**Comment by tamilselvan1102** [comment]
[dynamic volume provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#defaulting-behavior) page to be updated with following content. 

> If a cluster has a one default StorageClass and it is not necessary to specify the storageClassName while create a PersistentVolumeClaim.
> If two or more of them are marked as default, a PersistentVolumeClaim without storageClassName explicitly specified cannot be created.

**Comment by tamilselvan1102** [comment]
I will raise a PR if triage accepted

**Comment by sftim** [comment]
/retitle Conflicting information about default StorageClasses

The information in https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass looks accurate.

**Comment by tamilselvan1102** [comment]
@sftim 
please review the PR

**Comment by vaibhav2107** [comment]
I think this issue is updated by the PR #44942 and hence can be closed
