### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/tasks/debug/debug-application/debug-running-pod/

### ISSUE THREAD

**Issue by Notailli** [kubernetes/website#44948]
jps 不能实现和ps一样的功能，debug container不能通过jps获取业务容器中启动的java进程

**Comment by tamilselvan1102** [comment]
Related page: https://kubernetes.io/zh-cn/docs/tasks/debug/debug-application/debug-running-pod/

**Comment by tamilselvan1102** [comment]
Please describe the issue in English

**Comment by aj11anuj** [comment]
Translation: -
'PS cannot achieve the same function as PS, and the debug container cannot obtain the Java process started in the service container through JPS'
/sig docs

@Notailli can you provide more info related to this issue?
