### ISSUE TITLE
Write Task topics for Opaque Integer Resources

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4494]
**This is a...** 
- [ x] Feature Request
- [ ] Bug Report

Create a new topic for app developers: Assign Opaque Integer Resources to a Container
Create a new topic for cluster admins: Advertise Opaque Integer Resources for a Node

**Comment by steveperry-53** [comment]
https://github.com/kubernetes/kubernetes.github.io/pull/4363

**Comment by tengqm** [comment]
This can be closed because ... Opaque Integer Resource (OIR) didn't make its way to Beta.
