### ISSUE TITLE
Update Firewall Topics

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4495]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

Take a look at this topic: [Configure Your Cloud Provider's Firewall Rules](https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/). Does it belong in the kubernetes.io docs, or should it be in the Google Cloud docs? If you decide to keep it in the kubernetes.io docs, apply the Task template, and edit to comply with our style guide. If possible, make the task into a set of steps that the reader can actually do.

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by sftim** [comment]
Done
/close
