### ISSUE TITLE
A single typo in blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs

### ISSUE THREAD

**Issue by mikutas** [kubernetes/website#44965]
**This is a Bug Report**

**Problem:**

As being pointed in https://github.com/kubernetes/website/pull/42335#discussion_r1470970765 , `spec.unhealthyPodEvictionPolicy` should be `.spec.unhealthyPodEvictionPolicy`

**Proposed Solution:**

**Page to Update:**

https://kubernetes.io/blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/

**Comment by Gauravpadam** [comment]
/remove-triage accepted
/priority backlog

I'll be revising the triage as we do have a policy of not maintaining articles over a year old.

**Comment by Gauravpadam** [comment]
Quoting https://kubernetes.io/docs/contribute/review/for-approvers/

> We expect [Kubernetes Blog](https://kubernetes.io/blog/) entries to become outdated over time. Therefore, we only maintain blog entries less than a year old. If an issue is related to a blog entry that is more than one year old, close the issue without fixing.

**Comment by Okabe-Junya** [comment]
Thank you @Gauravpadam :)

I didn't know this policy and caused inconvenience to @mikutas. My apologize.

Is it okay to close this issue and #44966 ?
