### ISSUE TITLE
Incorrect link for Deploy via ansible

### ISSUE THREAD

**Issue by thisisharrsh** [kubernetes/website#44964]
**This is a Bug Report**

**Problem:** The link for `deploy via ansible` under [`Network modes`](https://kubernetes.io/docs/concepts/services-networking/windows-networking/#network-modes) in [`Networking on windows`](https://kubernetes.io/docs/concepts/services-networking/windows-networking/) is incorrect. It is redirecting to `https://github.com/ovn-org/ovn-kubernetes/tree/master/contrib` instead of that it should redirect to `https://github.com/ansible/ansible`. 

**Proposed Solution:** `Deploy via ansible` should redirect to `https://github.com/ansible/ansible` instead of `https://github.com/ovn-org/ovn-kubernetes/tree/master/contrib`.

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/concepts/services-networking/windows-networking/_

**Comment by thisisharrsh** [comment]
I would to link to work on this issue, if triage gets accepted.

**Comment by sftim** [comment]
Really, the whole page could use an overhaul, and the mention of Ansible might actually disappear.

**Comment by thisisharrsh** [comment]
Since, the issue is already addressed in the [PR](#31428) so, i am closing this issue.
