### ISSUE TITLE
[zh] Displays Raw Html data in tutorials page

### ISSUE THREAD

**Issue by Exlau** [kubernetes/website#44975]
https://kubernetes.io/zh-cn/docs/tutorials/kubernetes-basics/scale/scale-intro/
Chinese document display in raw html format.

<img width="868" alt="image" src="https://github.com/kubernetes/website/assets/56985055/1594cb20-0b8c-4ea4-9d36-87c742f04e31">

**Comment by aj11anuj** [comment]
As per original site, this part should look something like this -
![Screenshot (912)](https://github.com/kubernetes/website/assets/116108975/315b1275-5212-4a5e-94f8-606695e8d806)
