### ISSUE TITLE
Update Docs for Managing API Resources

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4497]
**This is a...** 
- [ x] Feature Request
- [ ] Bug Report

Study this topic: [Managing Resources](https://kubernetes.io/docs/concepts/cluster-administration/manage-deployment/). Separate the conceptual content from the task-like content. Maybe there is no conceptual content here; maybe it should all be converted to a set of Task topics. Create several Task topics to cover the techniques demonstrated. For each Task topic, decide whether it is for app developers or cluster administrators, and find an appropriate home in the table of contents. For each potential new Task topic, see whether it is redundant with an existing Task. If it is, there's no need for a new Task topic. Put all topics into the appropriate templates: Task or Concept. Edit all topics to comply with our style guide. Whenever possible, write Tasks that readers can actually do as they read through the steps.

**Comment by sftim** [comment]
Also see issue #21721

**Comment by lmktfy** [comment]
Maybe we should split this into smaller, more actionable issues?

**Comment by Caesarsage** [comment]
Went through this issue and content. The page is task-based content with no much conceptual material as it is under the docs content page. I would love to improve this. Here is what i want to do and flow

Deprecate the current concept page (or rewrite it to be more conceptual) and linked it with 4 focused task topics:

1. Organize Workload Configurations in Files: /tasks/manage-kubernetes-objects/
   - Multi-resource YAML files
   - Working with multiple files and directories
   - Deploying from URLs
2. Update a Deployment Without Downtime: /tasks/run-application/
   - Rolling update procedures
   - Monitoring rollouts
   - Rollback strategies
3. Deploy a Canary Release: tasks/run-application/
   - Setting up stable + canary deployments
   - Traffic distribution
   - Promotion and rollback
4. Scale a Deployment Manually: /tasks/run-application/
   - Scaling up/down/to zero
   - When to use manual vs. automatic scaling

Some other content are also already covered elsewhere, like the 
- Bulk operations: existing declarative management tasks
- `kubectl apply/edit/patch`: existing object management tasks
- Autoscaling: HorizontalPodAutoscaler walkthrough

what do you think ?

@lmktfy @natalisucks @dipesh-rawat

**Comment by lmktfy** [comment]
Good idea. 

The canary release topic sounds like a tutorial. The other 3 like tasks. How about filing three issues about adding each of the new task pages (and making them ready to find), plus a 4th issue about the new tutorial page.

**Comment by Caesarsage** [comment]
Thanks for the feedback! That makes sense. I agree the canary release fits better as a tutorial given its step-by-step nature.

I'll create the 4 separate issues as you suggested:
- 3 task-based issues for the deployment management topics
- 1 tutorial issue for the canary release

I'll also include navigation/discoverability considerations in each issue to ensure they're easy to find.
