### ISSUE TITLE
'What's next' and 'Feedback' heading of one of the kubeadm page is in the middle of page

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/website#44989]
**This is a Bug Report**

**Problem:**
'What's next' and 'Feedback' heading of [this page]() is in the middle of page that should be at the end of the page.

**Proposed Solution:**
Cut-paste content shown in 1st picture and paste it after the heading 'Troubleshooting' (Refer 3rd picture)

**Page to Update:**
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#whats-next

![Screenshot (913)](https://github.com/kubernetes/website/assets/116108975/dd6e7a5c-fbd9-4134-bfb1-4f65ace1b518)
![Screenshot (914)](https://github.com/kubernetes/website/assets/116108975/62e1ddd3-d657-4f58-aac9-4722b03234f8)
![Screenshot (915)](https://github.com/kubernetes/website/assets/116108975/dba0cefc-e941-48a1-9532-034b89299584)

**Comment by soravkumarsharma** [comment]
I would like to work on this issue

**Comment by aj11anuj** [comment]
@soravkumarsharma this issue is already assigned to Prashant and he has already raised a PR for it which is under review process. There are plenty of other issues available here, try your hands on them :)

**Comment by soravkumarsharma** [comment]
@aj11anuj Yeah, I checked that's why i deleted the comment
