### ISSUE TITLE
Remove Configuration Best Practices Topic

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4498]
**This is a...** 
- [x ] Feature Request
- [ ] Bug Report

Study this topic: [Configuration Best Practices](https://kubernetes.io/docs/concepts/configuration/overview/). Verify that the content in this topic is covered elsewhere, and then delete this topic. If you find content that is not covered elsewhere, put that content into one or more existing topics.

**Comment by tengqm** [comment]
@steveperry-53 Personally I view this page valuable.
