### ISSUE TITLE
Add link to Minikube in "Install and Set Up kubectl on macOS"

### ISSUE THREAD

**Issue by deadandhallowed** [kubernetes/website#44981]
The page "Install and Set Up kubectl on macOS" under "[Verify kubectl configuration](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#verify-kubectl-configuration)" suggests using Minkube. This is the first mention, and a user new to Kubernetes might not know what Minikube is. The installation guide is linked under "What's next" at the bottom of the page, but a new user might not get that far. Linking directly to the Minikube installation guide when it is first mentioned ensures the user has immediate access at the point in the kubectl installation when it becomes relevant.

**Comment by utkarsh-singh1** [comment]
Hi @deadandhallowed, I think installation instruction are already given here ⇾ https://kubernetes.io/docs/tasks/tools/, here it is instructions are also given for kubeadm and kind.

**Comment by sftim** [comment]
If we make the change for the macOS page, we should do it for all of them.
IMO we should assume that people can find the _What's next_ section; if we assume a too-low reading age, lots of our documentation is going to need rewriting.

We could use a glossary tooltip for minikube; how about that?

**Comment by aj11anuj** [comment]
> We could use a glossary tooltip for minikube; how about that?

+1

**Comment by niranjandarshann** [comment]
> We could use a glossary tooltip for minikube; how about that?

+1

**Comment by T-Lakshmi** [comment]
> We could use a glossary tooltip for minikube; how about that?

+1

**Comment by a-mccarthy** [comment]
Looks like the links to the minikube install documentation has been added to https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/#verify-kubectl-configuration and https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#verify-kubectl-configuration in the linked PR.

@deadandhallowed thanks for filing, please reopen this issue or file a new one if you have more changes you'd like to see in the docs

/close
