### ISSUE TITLE
Comment in source code for Controller concept

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#44983]
**This is a Bug Report**

**Problem:**
There seems to be a comment tag under the [controller](https://kubernetes.io/docs/concepts/architecture/controller/) concept page, that does not seem to be working.

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/controller/

**Comment by utkarsh-singh1** [comment]
Comment tag - 
![Screenshot from 2024-02-01 23-14-00](https://github.com/kubernetes/website/assets/96516301/85b2964d-e975-4033-85b1-3086683049c8)

Docs - 
![Screenshot from 2024-02-01 23-14-49](https://github.com/kubernetes/website/assets/96516301/f533f989-9e78-4f4a-8c3e-142851b61022)

**Comment by dipesh-rawat** [comment]
I believe there's no need for any fixes here. Upon reviewing `{{< comment >}}` [shortcode file](https://github.com/kubernetes/website/blob/main/layouts/shortcodes/comment.html), it's evident that it evaluates the Inner method _(returns content between opening and closing shortcode tags)_, and based on finding content in the shortcode, there's a condition to take no action. Consequently, the final rendered HTML page won't include the content of the _comment_ shortcode in its source code, which is currently the case and is being reported as incorrect behaviour in this issue.

**Comment by sftim** [comment]
Ah, the screenshot is from the source code? Nothing to fix, then.
/remove-triage accepted

**Comment by sftim** [comment]
/retitle Comment in source code for Controller concept

**Comment by sftim** [comment]
/triage unresolved

/close not-planned

We allow source code comments.
