### ISSUE TITLE
Missing explanation on parallel multi-node draining in "Safely Drain a Node" page

### ISSUE THREAD

**Issue by aaronkjones** [kubernetes/website#44998]
**This is a Bug Report**

**Problem:**

The page at `docs/tasks/administer-cluster/safely-drain-node.md` claims, "The kubectl drain command should only be issued to a single node at a time.", but does not explain further. Why is issuing the kubectl drain command discouraged when targeting more than one node at a time?
 
**Proposed Solution:**

A more detailed explanation should be provided.

**Page to Update:**

https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/

**Comment by dipesh-rawat** [comment]
/retitle Missing explanation on parallel multi-node draining in "Safely Drain a Node" page
/language en

**Comment by aj11anuj** [comment]
It's not a bug but an improvement request for more explanation
/remove-kind bug
/kind feature

**Comment by Shubhdeep02** [comment]
Raised PR in #45485
