### ISSUE TITLE
Assistance Needed: 'kubectl get pods' not working - Error message indicates 'connection refused'

### ISSUE THREAD

**Issue by ixahmii** [kubernetes/website#45005]
```
root@ip-172-31-93-14:/home/ubuntu# kubectl get pods
E0203 12:18:37.125802   21129 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0203 12:18:37.126249   21129 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0203 12:18:37.127347   21129 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0203 12:18:37.127757   21129 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0203 12:18:37.129324   21129 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by dipesh-rawat** [comment]
/retitle Assistance Needed: 'kubectl get pods' not working - Error message indicates 'connection refused'

**Comment by dipesh-rawat** [comment]
(Looks like a request for help in its current form)
/kind support

**Comment by dipesh-rawat** [comment]
@ixahmii  Thank you for reaching out and seeking assistance. We appreciate your query, but the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.

**Comment by niranjandarshann** [comment]
Hey @ixahmii  Thank you for your contribution . Keep Contributing as this is the support issue and you can ask support issue either in slack channel or discussion forum.
So  I am closing the issue .
 If you find something useful for community to add feature or to resolve some bug or improve the doc you mayraise the issue. 
Feel free to contribute the useful stuff.
