### ISSUE TITLE
Update Cron Jobs Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4500]
Study this topic: [CronJobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/).

Much of the content is not conceptual; it is task-like. Move the task-like content into one or more new Task topics. Before you create a new Task topic, verify that the content does not already appear in an existing Task topic. For the original topic and any new Task topics, use the appropriate template: Concept or Task. Edit the topics to comply with our style guide. In Task topics, if possible, create exercises that readers can actually do as they read through the steps.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/enhancements/issues/19
/triage accepted

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/34610

**Comment by sftim** [comment]
I'm actually happy with https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ now.

/close
