### ISSUE TITLE
Kubeadm create cluster CNI section doesn't explain how to set up a CNI

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes/website#45007]
**This is a Bug Report**

I was trying to explain to someone not very familiar with Kubernetes how to set up a cluster using kubeadm, pointing them to this page: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm

The create pod networking section in there has zero explanation on how to actually setup CNI other than `kubectl apply -f <add-on.yaml>`: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

That guidance has about the value of step two in here: https://seths.blog/2014/01/how-to-draw-an-owl/

This used to have a couple of links to docs for popular CNIs which was super helpful. I presume that list is gone for neutrality reasons but that makes this page completely useless for the target audience, people not familiar with Kubernetes.

wing information. -->

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by dipesh-rawat** [comment]
It's understandable that the lack of detailed explanation on setting up CNI could be frustrating, especially for those new to Kubernetes. Regarding the absence of specific CNIs in the documentation, its worth noting most of these plugins aren't listed in the CNCF landscape or maintained directly by the Kubernetes _(kubeadm)_ team, which aligns with the third-party content policy for documentation. 
Currently, on the page under the ["What's Next" section](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#whats-next), there's a link provided to **_"See the list of add-ons to explore other add-on"_**  which leads to https://kubernetes.io/docs/concepts/cluster-administration/addons/ where users can explore additional resources, including other CNIs. Hopefully, this [page](https://kubernetes.io/docs/concepts/cluster-administration/addons/) includes the details you were seeking.

**Comment by neolit123** [comment]
the reason there is no CNIs listed on the kubeadm page to apply with kubectl, is that there were arguments why kubeadm prefers some and not others. thus we removed all of them making the kubeadm pages agnostic.

PR to improve the language in
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network
or linking "more directly" (?) to this page:
https://kubernetes.io/docs/concepts/cluster-administration/addons/#networking-and-network-policy
can be accepted, 

but please don't send PRs that include a default CNI (e.g. `kubeclt apply -f flannel.yaml`) on the kubeadm pages.

**Comment by steve-hardman** [comment]
Let me see if I can help with this based on https://github.com/kubernetes/website/issues/45007#issuecomment-1925442177
/assign

**Comment by steve-hardman** [comment]
@dipesh-rawat @neolit123 Just checking its okay to work on this. SInce its not yet triage accepted.

**Comment by sftim** [comment]
We've made a change - does that help?

**Comment by alvaroaleman** [comment]
Yes, that added link is very helpful. Thanks for looking into it!
