### ISSUE TITLE
Update Docs for Container Lifecycle Hooks

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4501]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Study this Concept topic: [Container Lifecycle Hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/).
See how much of this content is covered by existing Task topics. If possible, delete this Concept topic. This might require adding a bit more material to existing Task topics.

**Comment by divya-mohan0209** [comment]
@steveperry-53 Just checking in, are you still planning to improve this document? It is totally fine if the answer is no. We'd request that you let us know your vision and what you find lacking so that we can open the issue up to new contributors.

**Comment by sftim** [comment]
Anyone is welcome to work on this issue.

**Comment by sftim** [comment]
Aside: I think I think https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/ is really a Pod-level concept, as these hooks only exist in containers that are part of Kubernetes Pods. We could move this page into the Pods section.

**Comment by sftim** [comment]
I don't think this issue is that important. I'm going to close it in favor of highlighting work on other areas.

/close
