### ISSUE TITLE
Failed to connect to hello-world.info port 80 after 75000 ms: Couldn't connect to server

### ISSUE THREAD

**Issue by KI2605** [kubernetes/website#45027]
**Problem:**
Going through the documentation provided by the link https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/ such issue has being met on the step of verification that Ingress controller is directing the traffic using the command below: **curl --resolve "hello-world.info:80:$( minikube ip )" -i http://hello-world.info**
After running this command the terminal returns: **Failed to connect to hello-world.info port 80 after 75000 ms: Couldn't connect to server**

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress

Kubernetes version: v1.28.3

Environment that is used: Macbook M1 Pro
Minikube version: v1.32.0
Minikube uses the docker driver.
Step on which problem has been met: https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/#create-an-ingress

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube
/language en
