### ISSUE TITLE
The YAML format may be not correct in setup-ha-etcd-with-kubeadm

### ISSUE THREAD

**Issue by long1318737396** [kubernetes/website#45033]
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
anonymous:
 enabled: false
webhook:
 enabled: false
authorization:
mode: AlwaysAllow
这里有问题，没有进行缩进 
正常应该是
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
anonymous:
  enabled: false
webhook:
  enabled: false
authorization:
  mode: AlwaysAllow

**Comment by aj11anuj** [comment]
## Translation of title -
Use kubeadm to create a highly available etcd cluster

## Translation of description -
 apiVersion: kubelet.config.k8s.io/v1beta1
 kind: KubeletConfiguration
 authentication:
 anonymous:
 enabled: false
 webhook:
 enabled: false
 authorization:
 mode: AlwaysAllow
 There is a problem here, there is no indentation
 Normal should be
 apiVersion: kubelet.config.k8s.io/v1beta1
 kind: KubeletConfiguration
 authentication:
 anonymous:
 enabled: false
 webhook:
 enabled: false
 authorization:
 mode: AlwaysAllow

**Comment by aj11anuj** [comment]
@long1318737396 provide more details of the issue as it's difficult to address your issue with the information that you have provided. Atleast mention the page you are referring to.
/triage needs-information

**Comment by windsonsea** [comment]
/retitle The YAML format may be not correct in setup-ha-etcd-with-kubeadm
