### ISSUE TITLE
[ja] fix the notation variations of the term "interface"

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45038]
**This is a Feature Request**

**What would you like to be added**

- fix the notation variations of the term "interface" （以下の検索結果にある表記揺れの箇所を「インターフェース」に修正してください）
    - valid: インターフェース
    - invalid: インターフェイス | [Search Result](https://cs.k8s.io/?q=インターフェイス&i=nope&files=&excludeFiles=&repos=kubernetes/website)
    - invalid: インタフェース | [Search Result](https://cs.k8s.io/?q=インタフェース&i=nope&files=&excludeFiles=&repos=kubernetes/website)

**Why is this needed**

In Japanese documents, There are notation variations. The Japanese localization of k/website has rules, so we want to follow them.

**Comments**

FYI:

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/
- Slack archive（インターフェースの表現に関するやり取り）: https://kubernetes.slack.com/archives/CAG2M83S8/p1565318551088100

**command**

/language ja
/area localization
/help
/good-first-issue

**Comment by tamilselvan1102** [comment]
@Okabe-Junya 
PRを上げました、ご確認ください
