### ISSUE TITLE
Update Volumes Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4503]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Study this topic: [Volumes](https://kubernetes.io/docs/concepts/storage/volumes/). See whether some of this content could be removed from the Kubernetes docs, and instead be covered by various cloud provider docs. For the content that remains in this topic, apply the [Concept template](https://kubernetes.io/docs/home/contribute/page-templates/#concept_template), and edit the text to comply with our [style guide](https://kubernetes.io/docs/home/contribute/style-guide/).

**Comment by Bradamant3** [comment]
Consider this issue also in light of #4514

**Comment by sftim** [comment]
Related issue: https://github.com/kubernetes/website/issues/24726

**Comment by sftim** [comment]
Related issue: https://github.com/kubernetes/website/issues/31159

**Comment by misfit20** [comment]
Can I work on this, or has someone already been assigned to it?

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/42590

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/43293

**Comment by sftim** [comment]
Closing in favor of issue https://github.com/kubernetes/website/issues/45873

/close not-planned
