### ISSUE TITLE
[ja] fix the notation variations of the term "repository"

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45039]
**This is a Feature Request**

**What would you like to be added**

- fix the notation variations of the term "repository" （以下の検索結果にある表記揺れの箇所を「リポジトリー」に修正してください）
    - valid: リポジトリー
    - invalid: リポジトリ | [Search Result](https://cs.k8s.io/?q=リポジトリ%5B%5Eー%5D&i=nope&files=&excludeFiles=&repos=kubernetes/website)

**Why is this needed**

In Japanese documents, There are notation variations. The Japanese localization of k/website has rules, so we want to follow them.

**Comments**

FYI:

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/
- Slack archive（リポジトリの表現に関するやり取り）: https://kubernetes.slack.com/archives/CAG2M83S8/p1574910937227000

**command**

/language ja
/area localization
/help
/good-first-issue

**Comment by Okabe-Junya** [comment]
Please, Go for it :)

When working on issues, please work them one at a time. Meaning, after creating the PR, then assign the next issue.

**Comment by Okabe-Junya** [comment]
@tamilselvan1102 

PTAL https://github.com/kubernetes/website/issues/45039#issuecomment-1929086352 :)

**Comment by tamilselvan1102** [comment]
@Okabe-Junya 
Raised PR, please validate it.
