### ISSUE TITLE
Considerations for large clusters doesn't mention recommneded CP size

### ISSUE THREAD

**Issue by stackbaek** [kubernetes/website#45036]
"considerations for large clusters" lists the limits it's designed to meet (5000 nodes, 110pod denstiy, 150k pod, etc). However, it doesn't mention recommended size for CP nodes (e.g CPU/memory for the control plane nodes, # of CP in the etcd cluster, etc).

If we have this information somewhere, can we publish it?

**Comment by tamilselvan1102** [comment]
you can refer this page https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/

**Comment by tamilselvan1102** [comment]
if you get  the answer. please close the issue

**Comment by sftim** [comment]
I don't think this is a request for support

/remove-kind support
/kind feature

**Comment by stackbaek** [comment]
> you can refer this page https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/

This is a bit different from what I was envisioning. I was expecting some sort of guidelines for control plane node sizing to reach (5000 nodes, 110pod denstiy, 150k pod)
