### ISSUE TITLE
Broken tab layout on "Changing The Kubernetes Package Repository" page in older doc versions

### ISSUE THREAD

**Issue by george2asenov** [kubernetes/website#45048]
[For older documentation](https://github.com/kubernetes/website/issues/45048#issuecomment-1929705706):

"Switching to another Kubernetes package repository" and particularly the one for CentOS/REHL shows commands for Debian based  system, not REHL based rpm

**Comment by stmcginnis** [comment]
I'm not seeing this. Can you point out where there are deb commands for RHEL?

![image](https://github.com/kubernetes/website/assets/3922475/5b36f405-346a-40e1-9987-5cd1ab1656b0)

**Comment by george2asenov** [comment]
Excuse me it is for old versions:
https://v1-27.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository/#switching-to-another-kubernetes-package-repository
https://v1-26.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository/#switching-to-another-kubernetes-package-repository
https://v1-25.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository/#switching-to-another-kubernetes-package-repository
![chrome_7q0MSP3w4n](https://github.com/kubernetes/website/assets/15124861/d0f926dc-50fe-4764-9a20-029f67e5e476)

**Comment by kumarankit999** [comment]
I'm also not able to see this @george2asenov 
![image](https://github.com/kubernetes/website/assets/111564362/b0e1c7c6-1c83-4610-8f57-df14d6ba1dfc)

**Comment by dipesh-rawat** [comment]
/retitle Broken tab layout on "Changing The Kubernetes Package Repository" page in older doc versions
/kind bug

**Comment by dipesh-rawat** [comment]
The problem stems from the existence of two tab layouts on this page having the same name "k8s_install_versions". This issue has been resolved in the `main` branch. To address this issue in old docs versions, we'll need to backport and apply the fix to each corresponding old branch (release-1.25, release-1.26, release-1.27, release-1.28).

**Comment by sftim** [comment]
I'd support a backport. One of the things we do want people to learn to do with older Kubernetes versions is: to upgrade them!

/triage accepted
/priority backlog

**Comment by steve-hardman** [comment]
I can try to help with this.
/assign

**Comment by vaibhav2107** [comment]
I think the backporting is done which resolves this issue

**Comment by vaibhav2107** [comment]
If it is ok we can close this issue

**Comment by dipesh-rawat** [comment]
The fixes have been back-ported to the older release branches. Closing this as completed.

/close
