### ISSUE TITLE
[ja] fix the notation variations of the term "proxy"

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45040]
**This is a Feature Request**

**What would you like to be added**

- fix the notation variations of the term "proxy" （以下の検索結果にある表記揺れの箇所を「プロキシ」に修正してください）
    - valid: プロキシ
    - invalid: プロキシー | [Search Result](https://cs.k8s.io/?q=プロキシー&i=nope&files=&excludeFiles=&repos=kubernetes/website)

**Why is this needed**

In Japanese documents, There are notation variations. The Japanese localization of k/website has rules, so we want to follow them.

**Comments**

FYI:

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/
- Slack archive（プロキシの表現に関するやり取り）: https://kubernetes.slack.com/archives/CAG2M83S8/p1570519499047100

**command**

/language ja
/area localization
/help
/good-first-issue

**Comment by tamilselvan1102** [comment]
@Okabe-Junya 
Raised PR, Please review it.
