### ISSUE TITLE
[ja] fix the notation variations of the term "computer"

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45041]
**This is a Feature Request**

**What would you like to be added**

- fix the notation variations of the term "computer" （以下の検索結果にある表記揺れの箇所を「コンピューター」に修正してください）
    - valid: コンピューター
    - invalid: コンピュータ | [Search Result](https://cs.k8s.io/?q=コンピュータ%5B%5Eー%5D&i=nope&files=&excludeFiles=&repos=kubernetes/website)

**Why is this needed**

In Japanese documents, There are notation variations. The Japanese localization of k/website has rules, so we want to follow them.

**Comments**

FYI:

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

**command**

/language ja
/area localization
/help
/good-first-issue

**Comment by Okabe-Junya** [comment]
@tamilselvan1102 

PTAL before woking https://github.com/kubernetes/website/issues/45039?notification_referrer_id=NT_kwDOBS2BH7M5MzU4MDc4MDQ0Ojg2ODY4MjU1#issuecomment-1929086352

**Comment by tamilselvan1102** [comment]
@Okabe-Junya 
PRを上げまた。ご確認よろしくお願いします。
