### ISSUE TITLE
Update Cluster Management Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4504]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Either delete or prune this topic: [Cluster Management](https://kubernetes.io/docs/tasks/administer-cluster/cluster-management/). Much of the content is specific to cloud providers and does not belong in the Kubernetes docs. It might be that the rest of the content is covered by existing Task topics, or could be covered with a couple new Task topics.

**Comment by tengqm** [comment]
/remove-lifecycle rotten
/lifecycle frozen

Do we want to completely kill the vendor specific contents or set up a quarantine saying that "these contents are vendor specific, they are here only for reference, they are supposed to be maintained by the vendor, for more precise information go vendor/k8s page" ?

**Comment by sftim** [comment]
> Do we want to completely kill the vendor specific contents or set up a quarantine saying that "these contents are vendor specific, they are here only for reference, they are supposed to be maintained by the vendor, for more precise information go vendor/k8s page" ?

We mainly want to remove them; see the (recently added) [content guide](https://kubernetes.io/docs/contribute/style/content-guide/)

**Comment by sftim** [comment]
Relevant to issue #20232
