### ISSUE TITLE
A broken link the kueue blog "Introducing Kueue"

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/website#45050]
**This is a Bug Report**

**Problem:**

There's a broken link for  [API concepts documentation](https://sigs.k8s.io/kueue/docs/concepts) in the `Introducing kueue` blog.

**Proposed Solution:**

Replace the missing link with [Concepts](https://kueue.sigs.k8s.io/docs/concepts/).

PR: https://github.com/kubernetes/website/pull/45052

**Page to Update:**

https://kubernetes.io/blog/2022/10/04/introducing-kueue/

**Comment by divya-mohan0209** [comment]
@yuanchen8911 : Thanks for this report, however, we don't maintain blogs older than a year per our policy.

**Comment by Gauravpadam** [comment]
/close not-planned
In favor of https://github.com/kubernetes/website/issues/45050#issuecomment-1936215312.
