### ISSUE TITLE
mention node.kubernetes.io/exclude-from-external-load-balancers on the kubeadm create cluster page

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#45054]
in the following section of the kubeadm docs:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#control-plane-node-isolation

we should mention that users should optionally remove the known label:
exclude-from-external-load-balancers
https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-exclude-from-external-load-balancers
in cases of single CP node clusters.

similar was done for kind recently:
https://github.com/kubernetes-sigs/kind/pull/3507

/kind feature
/sig cluster-lifecycle

**Comment by neolit123** [comment]
/retitle mention node.kubernetes.io/exclude-from-external-load-balancers on the kubeadm create cluster page

**Comment by steve-hardman** [comment]
I will try to help with this.

/assign

**Comment by steve-hardman** [comment]
I have raised PR #45057 to resolve this.
