### ISSUE TITLE
Update Namespaces Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4506]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

For this topic: [Share a Cluster with Namespaces](https://kubernetes.io/docs/tasks/administer-cluster/namespaces/):

* Put the content into the [Task template](https://kubernetes.io/docs/home/contribute/page-templates/#task_template).
* Edit the text so that is complies with the [style guide](https://kubernetes.io/docs/home/contribute/style-guide/).
* Test the step in the topic. Make sure the steps can actually be performed by the reader.

Study the following topics, and consolidate, if possible, into a smaller set of topics:
[Namespaces](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/)
[Namespaces Walkthrough](https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/)
[Federated Namespaces](https://kubernetes.io/docs/tasks/administer-federation/namespaces/)
[Share a Cluster with Namespaces](https://kubernetes.io/docs/tasks/administer-cluster/namespaces/)

**Comment by sftim** [comment]
I'm going to close this. It's actionable, but things have moved on since the issue was opened.
/close
