### ISSUE TITLE
Incorrect command given in 'Hello Minikube' Tutorial

### ISSUE THREAD

**Issue by arujjval** [kubernetes/website#45061]
**This is a Bug Report**

**Problem:**
In the tutorial 'Hello Minikube', the command given to view the application log for a container is incorrect as it is different for every deployment. 
![Screenshot from 2024-02-07 14-42-55](https://github.com/kubernetes/website/assets/106719640/ee087993-a588-475b-8a04-5e7ac6671711)

**Proposed Solution:**
It should be mentioned that every deployment has a different container name and that should be considered for the command.

**Page to Update:**
https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by tamilselvan1102** [comment]
In this section all the steps are subsequent. so it implicitly pointing the pod name in step 3.

**Comment by aj11anuj** [comment]
> It should be mentioned that every deployment has a different container name and that should be considered for the command.

Isn't it obvious?
