### ISSUE TITLE
Enhance glossary coherence: Emphasize object identity over functionality in definitions

### ISSUE THREAD

**Issue by wrp** [kubernetes/website#45063]
Several of the definitions describe what an object does, but not what it is.  For example, the definition of Resource Quotas is "Provides constraints that limit aggregate resource consumption per Namespace."  Compare that to the definition of Taint: "A core object consisting of three required properties: key, value, and effect. Taints prevent the scheduling of Pods on nodes or node groups."

If these were consistent, the definition of Taint would simply be "Prevents the scheduling of Pods...", and would be much less useful.  After reading the definition of Resource Quotas, the reader may know what a Resource Quota does, but they do not know what it *is*.  

These definitions should be re-worded to say first what the object *is* rather than what it does. (Or, in addition to the object's purpose.)

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/reference/glossary/

**Comment by dipesh-rawat** [comment]
/retitle Enhance glossary coherence: Emphasize object identity over functionality in definitions

**Comment by sftim** [comment]
Just so people know: taints actually aren't core objects, because they aren't objects in Kubernetes. They are however a _fundamental concept_ for how K8s does container orchestration.
