### ISSUE TITLE
Lack of visual cues for search matches in left-side menu items using browser find on webpage

### ISSUE THREAD

**Issue by dejanu** [kubernetes/website#45062]
**This is a Bug Report**

**Problem:**  User experience when searching for text in webpage : [https://kubernetes.io/docs/reference/kubectl/quick-reference/](https://kubernetes.io/docs/reference/kubectl/quick-reference/) 

E.g. when searching for `rollout` word first 6 hits are most probably from the navigation tree and they're not highlighted nor the cursor is moved to the result, making the search experience somehow confusing.

![image](https://github.com/kubernetes/website/assets/13877229/4ebbf561-6302-4feb-bf05-f8451bd07922)

**Proposed Solution:**
NA 

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/quick-reference/

**Comment by dipesh-rawat** [comment]
/retitle Lack of visual cues for search matches in left-side menu items using browser find on webpage
/area web-development

**Comment by tamilselvan1102** [comment]
it is the browser feature not a k8s web functionality.
it cannot be resolved.

**Comment by dejanu** [comment]
> it is the browser feature not a k8s web functionality. it cannot be resolved. @tamilselvan1102  how did you reach this conclusion?
The issue is reproducible on other browsers e.g. edge

**Comment by dejanu** [comment]
> Interesting. @dejanu, there is a solution of hiding the hits using ~magic~ code. But I can see some future complaints rising from that too.

To be quite honest I've heard others complaining too, maybe make that the search results from the page content is shown first, instead of the search hits from the navigation tree

**Comment by tamilselvan1102** [comment]
@dejanu 
[Ctrl+f] function is common for all the browsers. if do search after expanding the left menu, browser automatically navigate to the keyword.  [Ctrl+f] function we can override but it is not prescribed.

**Comment by tamilselvan1102** [comment]
@dejanu 
attached image for your reference
![image](https://github.com/kubernetes/website/assets/20103020/12475d3e-56da-4143-bea8-d3219b7b7f3b)

**Comment by sftim** [comment]
A workaround: put the left nav last on the page in terms of its order in the HTML source, but leave it where it is visually.

**Comment by sftim** [comment]
This might duplicate https://github.com/kubernetes/website/issues/41469

**Comment by sftim** [comment]
/triage duplicate
/close not-planned

See issue #41469
