### ISSUE TITLE
Logo Overlaps with Menu in RTL Languages

### ISSUE THREAD

**Issue by mboukhalfa** [kubernetes/website#45077]
**This is a Bug Report**

**Problem:**
When switching to an RTL language, the logo overlaps with the menu, creating a layout issue as shown in the picture! This is different form the issue https://github.com/google/docsy/issues/1442 and  https://github.com/google/docsy/issues/829 these issues are discussing switching the positioning for of menu elements to fit with RTL but the logo overlap problem is not observed in the docsy check: https://example.docsy.dev/fa/

The root cause of the problem is suspected to be the custom CSS applied in the k8s website. Here https://github.com/kubernetes/website/blob/95ca85963ce4e5294db525d25445fb1877d49e1b/assets/scss/_custom.scss#L132-L139
![Screenshot from 2024-02-07 15-31-27](https://github.com/kubernetes/website/assets/19722896/56cdaab7-12ed-42cc-8f47-27152f93442d)
**Proposed Solution:**
To fix this we can override the logo position with RTL languages for example:
```
body:lang(fa),
body:lang(ar),
body:lang(az),
body:lang(dv),
body:lang(he),
body:lang(ku),
body:lang(ur) {
  .navbar-brand {
    left: 16px;
  }
}
```
However, it's recommended to consider a more comprehensive solution. Refactoring the custom CSS added to the k8s website. We have big custom css ([>1000 lines](https://github.com/kubernetes/website/blob/95ca85963ce4e5294db525d25445fb1877d49e1b/assets/scss/_custom.scss) ) overriding the default docsy! might be necessary to avoid interfering with the default docsy styling. It's advisable to minimize overrides to essential elements, aligning with the purpose of using docsy. This approach ensures a cleaner separation between documentation content and web development concerns.
**Page to Update:**
https://deploy-preview-45056--kubernetes-io-main-staging.netlify.app/ar/

**Comment by Gauravpadam** [comment]
@mboukhalfa is it an issue with all RTL languages?

**Comment by Gauravpadam** [comment]
In that case, we'll need a more flexible solution than just changing the css positions; I've got something in mind

**Comment by mboukhalfa** [comment]
> @mboukhalfa is it an issue with all RTL languages?

yes it is

**Comment by mboukhalfa** [comment]
> In that case, we'll need a more flexible solution than just changing the css positions; I've got something in mind

Can you elaborate what a flexible solution would be ?

**Comment by sftim** [comment]
/area localization

/remove-kind bug
We don't have RTL support yet, so it's more a feature request (see https://github.com/kubernetes/website/issues/22730 for the overall feature request).

**Comment by sftim** [comment]
> We have big custom css ([>1000 lines](https://github.com/kubernetes/website/blob/95ca85963ce4e5294db525d25445fb1877d49e1b/assets/scss/_custom.scss) ) overriding the default docsy! might be necessary to avoid interfering with the default docsy styling.

See https://github.com/kubernetes/website/issues/41171 for an issue about reducing our level of customization. It's useful work that we have not yet staffed.

**Comment by chalin** [comment]
Hi all: if you could upvote https://github.com/google/docsy/issues/1442 that would help it get some traction.

**Comment by mboukhalfa** [comment]
Hmm I think I found the issue it seems we are using `ml-md-auto` class to push the menu always to the right side however this classes are not supporting direction change as show in the issue so when we switch to RTL the logo go to the other side but the menu keep its place instead of moving to left side 
https://github.com/kubernetes/website/blob/95ca85963ce4e5294db525d25445fb1877d49e1b/layouts/partials/navbar.html#L4
https://github.com/twbs/bootstrap/issues/22780#issue-234468486
