### ISSUE TITLE
Topics to Edit and Apply Template

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4507]
**This is a...** 

- [ x] Feature Request
- [ ] Bug Report

For each of the topics below:
* If the topic is not already in one of the [templates](https://kubernetes.io/docs/home/contribute/page-templates/), apply the Task, Tutorial, or Concept template.
* Edit the topic to comply with the [style guide](https://kubernetes.io/docs/home/contribute/style-guide/).
* Check for accuracy.

[Pod Overview](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/)
Make sure the terminology is accurate and consistent. For example, this statement is misleading: "A Pod represents a running process on your cluster". The word process means a certain thing in Linux. And a Pod can have more than one process.

[Tools for Monitoring Compute, Storage, and Network Resources](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/)

[Master-Node Communication](https://kubernetes.io/docs/concepts/architecture/master-node-communication/)

[Auditing](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/)
If possible, change the title to imperative form. If this topic seems like it covers too much, split it into two or more Task topics.

[Nodes](https://kubernetes.io/docs/concepts/architecture/nodes/)

[Pods](https://kubernetes.io/docs/concepts/workloads/pods/pod/)

[Replication Controller](https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/)
Put a note at the beginning of this topic: Replication Controller. In the note, explain that Deployment, along with a ReplicaSet, is the preferred way to do replication.

[Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)
Consider consolidating with [Annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).

[Perform Rolling Update Using a Replication Controller](https://kubernetes.io/docs/tasks/run-application/rolling-update-replication-controller/)

[Logging with Stackdriver](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-stackdriver/)

 [Logging Using Elasticsearch and Kibana](https://kubernetes.io/docs/tasks/debug-application-cluster/logging-elasticsearch-kibana/)

**Comment by Bradamant3** [comment]
PR #4537 addresses only the ReplicationController item in the original list. The PR also performs some cleanup on Deployments and ReplicaSets, although the latter two could use some more attention.

**Comment by celestehorgan** [comment]
@sftim is this still relevant in our post-template Docsy world?

**Comment by sftim** [comment]
Good point. I'm going to close it; @steveperry-53 if that was unwise of me, please feel free to reopen it.
