### ISSUE TITLE
Improvement for k8s.io/docs/reference/access-authn-authz/webhook/

### ISSUE THREAD

**Issue by wrp** [kubernetes/website#45076]
This is not really the right place for this feedback, but this page does demonstrate the issue and I am here at the moment, so this is where I will rant.  Please use consistent formatting in you examples.  yaml has the (unfortunate?) trait of allowing relatively flexible indentation.  On this page, 2 different styles are used: 'clusters:\n  - name:' and 'contexts:\n- context:`.  In the first, there is a level of indentation preceding the hyphen used to indicate a new entry in the list but in the second example that indentation is missing.  IMO, the 2nd is preferable.  Which style you prefer is not as important as consistency.  Perhaps it is too much to ask that the style by consistent throughout all of the documentation, but please at least make it consistent within each individual document.

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/reference/access-authn-authz/webhook
/langauge en

**Comment by utkarsh-singh1** [comment]
Hey @wrp, Thanks for mentioning the issue, it is understandable there could be minor differences with the indentation as YAML has habit of ignoring the indentation in case hyphen has been used.

**Comment by sftim** [comment]
/priority backlog

If someone sends in a pull request, we'd review it. However, we are prioritizing other work.

**Comment by utkarsh-singh1** [comment]
The issue does not seem to be much, just needed to add a space/tab in front of  `- context`

**Comment by utkarsh-singh1** [comment]
![Screenshot from 2024-02-14 11-47-45](https://github.com/kubernetes/website/assets/96516301/edeef381-8e9a-4e02-baed-dea3f144461d)

**Comment by utkarsh-singh1** [comment]
Any one looking for their first PR can take this issue on work on it.

**Comment by wrp** [comment]
Adding indentation to the `- context` line is a great start.  (Personally, I think a better start is to remove the indentation on the other lines.)  But this issue is much bigger than that.  I believe a high level decision needs to be made on yaml style which should be enforced throughout the entire project.  Fixing this page is a good first step, but it is just one small step towards a much larger problem.

**Comment by sftim** [comment]
>  I believe a high level decision needs to be made on yaml style which should be enforced throughout the entire project. 

You are welcome to file an issue to request this, @wrp
