### ISSUE TITLE
'Copy to Clipboard' functionality is missing from three snippets

### ISSUE THREAD

**Issue by venilamusunuru** [kubernetes/website#45089]
Problem: 'Copy to Clipboard' functionality is missing for some YAML examples listed below 

Proposed Solution: Integrate the 'Copy to Clipboard' functionality wherever it is lacking, as it facilitates seamless copying of commands across the entire platform.

https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#init-containers-in-use
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components

![image](https://github.com/kubernetes/website/assets/143119814/10a19c43-9151-4294-ad13-666a238dba04)

**Comment by dipesh-rawat** [comment]
It's worth noting that the "copy" button is not added to all code snippets intentionally. This is based on the fact that not all snippets are meant for users to directly execute; some are purely illustrative examples within the documentation. However, for snippets intended for users to try out, especially those in task or tutorial pages, wrapping them with the `code_sample` shortcode is highly recommended for an enhanced user experience.

**Comment by aj11anuj** [comment]
Also see #43350

**Comment by venilamusunuru** [comment]
I agree with your perspective @dipesh-rawat. Ideally, beginners or those starting out would find it helpful if they could easily copy the commands using the functionality

Example :
-> Installation 
-> Version Checks

<img width="490" alt="minkube" src="https://github.com/kubernetes/website/assets/143119814/97e4af59-238a-4c1b-b1dc-a501bb38acbb">

**Comment by sftim** [comment]
/remove-kind bug
/kind feature 
/retitle 'Copy to Clipboard' functionality is missing from three snippets
