### ISSUE TITLE
Support/Help Page in Side Menu 

### ISSUE THREAD

**Issue by venilamusunuru** [kubernetes/website#45097]
**This is a Feature Request**
Create a Support/Help page in side menu
Link - https://kubernetes.io/docs/home/

**What would you like to be added**
Include a "Help/Support" page on the side menu. Share information on how to contact us, the ways to reach out, and details about communication methods.

Observed that the information related to "Help" was present here
[Monitoring, Logging, and Debugging](https://kubernetes.io/docs/tasks/debug/)

**Why is this needed**
Including a dedicated "Support/Help" page in the side menu promotes user-friendly navigation and clarity on communication channels

**Comment by tamilselvan1102** [comment]
K8s website is mainly used to understand all the K8s objects and concepts and not to support/help any queries. There are various portals there to resolve the issue.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

Maybe we could link to a page that lists the options you do have for support, including commercially from CNCF members.

**Comment by venilamusunuru** [comment]
@sftim Appreciate your suggestion. 

What are your thoughts on considering a dedicated page for support in side menu?

**Comment by sftim** [comment]
> What are your thoughts on considering a dedicated page for support in side menu?

For me personally, it's not a priority.
