### ISSUE TITLE
Update ConfigMap Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4509]
**This is a...** 

- [x ] Feature Request
- [ ] Bug Report

Take a look these two topics to see whether they are redundant. If so, combine into one topic. If you decide that we need two topics, prune the content so that information is not repeated.
* [Configure Containers Using a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configmap/)
* [Use ConfigMap Data in Pods](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)

**Comment by Bradamant3** [comment]
Consider whether some additional explanation of what a ConfigMap is might be helpful. One possible resource for information: https://medium.com/google-cloud/kubernetes-configmaps-and-secrets-68d061f7ab5b.
Also add ConfigMap to glossary.

**Comment by radhikapc** [comment]
Let me know how can I help here @zacharysarah

**Comment by spzala** [comment]
@steveperry-53 I will be working on it. Thanks!

**Comment by spzala** [comment]
@steveperry-53 after flight cancel due to weather and going through new travel arrangements, finally got back home from KubeCon :). Just a quick update that I have started working on it and hopping to create a PR soon. Thanks!
