### ISSUE TITLE
Unable to pull example image `registry.k8s.io/fluentd-gcp:1.30` in "Logging Architecture" page

### ISSUE THREAD

**Issue by rahulracker7539** [kubernetes/website#45091]
failing to pull images from the registry.k8s.io/fluentd-gcp:1.30 . example may need to change to correct image path.

**Comment by dipesh-rawat** [comment]
Page reported in issue _(based on the issue title)_: https://kubernetes.io/docs/concepts/cluster-administration/logging/
/language en
/kind bug

**Comment by dipesh-rawat** [comment]
/retitle Unable to pull example image `registry.k8s.io/fluentd-gcp:1.30` in "Logging Architecture" page

**Comment by tamilselvan1102** [comment]
Image is available in the repo
https://explore.ggcr.dev/?image=registry.k8s.io%2Ffluentd-gcp:1.30

**Comment by tamilselvan1102** [comment]
@rahulracker7539 
share the error which you are getting

**Comment by rahulracker7539** [comment]
> @rahulracker7539 share the error which you are getting

Please see the below error which am getting while pulling that images, however after pulling locally the images and storing it in my own artifact works. but not sure why through not the given images path

  Normal   Pulling           2m1s               kubelet                                Pulling image "busybox:1.28"
  Normal   Created           114s               kubelet                                Created container count
  Normal   Pulled            114s               kubelet                                Successfully pulled image "busybox:1.28" in 858ms (6.726s including waiting)
  Normal   Started           114s               kubelet                                Started container count
  Warning  Failed            28s (x2 over 71s)  kubelet                                Failed to pull image "registry.k8s.io/fluentd-gcp:1.30": failed to pull and unpack image "registry.k8s.io/fluentd-gcp:1.30": failed to resolve reference "registry.k8s.io/fluentd-gcp:1.30": failed to do request: Head "https://registry.k8s.io/v2/fluentd-gcp/manifests/1.30": dial tcp 34.96.108.209:443: i/o timeout
  Warning  Failed            28s (x2 over 71s)  kubelet                                Error: ErrImagePull
  Normal   BackOff           13s (x2 over 71s)  kubelet                                Back-off pulling image "registry.k8s.io/fluentd-gcp:1.30"
  Warning  Failed            13s (x2 over 71s)  kubelet                                Error: ImagePullBackOff
  Normal   Pulling           0s (x3 over 114s)  kubelet                                Pulling image "registry.k8s.io/fluentd-gcp:1.30"

**Comment by tamilselvan1102** [comment]
@rahulracker7539 
it is working fine for me
![image](https://github.com/kubernetes/website/assets/20103020/9970ab21-4515-4205-a50d-b10b4004ac1a)

**Comment by tamilselvan1102** [comment]
Please check if anything is blocking your request path.
/kind support

**Comment by rahulracker7539** [comment]
thanks, will have a look and feel free to close the case if all good from your end
