### ISSUE TITLE
Remove and Blend Names Topic

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4511]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Delete this topic. Blend the content into another topic.
[Names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/)

**Comment by seperry53test** [comment]
@steveperry-53, I'll work on this issue.

**Comment by sftim** [comment]
I'm fairly happy with https://kubernetes.io/docs/concepts/overview/working-with-objects/names/ as it stands. Maybe it would have a better home inside https://kubernetes.io/docs/reference/ ?

**Comment by sftim** [comment]
Superseded by issue #26822.
/close
