### ISSUE TITLE
Update Monitor Node Health Topic

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4512]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Figure out what to do with this topic: [Monitor Node Health](https://kubernetes.io/docs/tasks/debug-application-cluster/monitor-node-health/). Separate the GCE content from the pure Kubernetes content.

**Comment by sftim** [comment]
/sig node
too

**Comment by kbhawkey** [comment]
Related to PR #24772.

**Comment by sftim** [comment]
https://kubernetes.io/docs/tasks/debug/debug-cluster/monitor-node-health/ doesn't seem to have any GCP / GKE / GCE details.

/close
