### ISSUE TITLE
Seeking support: Trouble editing PVC storage, stuck in terminating state

### ISSUE THREAD

**Issue by hossamfatahalla** [kubernetes/website#45124]
I am asked to edit storage of pvc I have already created from 50Mi to 100Mi but it gives an errors like status of pvc is lost or when I try to delete it and recreate it's remain in terminating state ????

**Comment by dipesh-rawat** [comment]
/retitle Seeking support: Trouble editing PVC storage, stuck in terminating state

**Comment by dipesh-rawat** [comment]
(Looks like a request for help in its current form)
/kind support

**Comment by dipesh-rawat** [comment]
GitHub isn't the right platform for support request, but you're welcome to seek assistance on [Server Fault](https://serverfault.com/questions/tagged/kubernetes) or post the question on [Kubernetes Slack](http://slack.k8s.io/) or [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close not-planned
