### ISSUE TITLE
Lack of clarity on `ClusterConfiguration` necessity in "Configuring a cgroup driver" page

### ISSUE THREAD

**Issue by alexanderkjeldaas** [kubernetes/website#45133]
Based on the wording on this page, it would be good to have some assurance of whether the `ClusterConfiguration` object is needed or not.  It is very unclear whether the last yaml document is optional or if the whole command is optional on modern k8s setups:

<img width="658" alt="image" src="https://github.com/kubernetes/website/assets/339369/01f15463-fbd4-4747-9754-fbe89045614e">

**Comment by dipesh-rawat** [comment]
_Page reported in issue (based on the issue title):_ https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver
/language en

**Comment by dipesh-rawat** [comment]
/retitle Lack of clarity on `ClusterConfiguration` necessity in "Configuring a cgroup driver" page

**Comment by sftim** [comment]
How about we change:
> kubeadm allows you to pass a `KubeletConfiguration` structure during `kubeadm init`.

to
> kubeadm allows you to pass a `KubeletConfiguration` structure during `kubeadm init`; this is optional and on Linux you usually won't need to.

This helps people be confident that the optional parameter is OK to omit.

**Comment by neolit123** [comment]
> Based on the wording on this page, it would be good to have some assurance of whether the ClusterConfiguration object is needed or not. It is very unclear whether the last yaml document is optional or if the whole command is optional on modern k8s setups:

ClusterConfiguration is required for kubeadm init, if you use --config.

some other notes:
- the systemd driver is already default in kubeadm, so this guide makes more sense to users that want to pass `cgroupDriver: cgroupfs`
- hopefully we can delete that page entirely after https://github.com/kubernetes/enhancements/issues/4033 goes GA
