### ISSUE TITLE
Using kubectl to Create a Deployment - deployment fails - exec format error

### ISSUE THREAD

**Issue by dark3rMatt3r** [kubernetes/website#45131]
`kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1`
Results in 
`deployment.apps/kubernetes-bootcamp created`

in the terminal but i can see in the dash the deployment has failed.

also via kubectl get deployments -A
```
NAMESPACE              NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
default                kubernetes-bootcamp         0/1     1            0           4m46s
default                web-dash                    1/1     1            1           11h
kube-system            coredns                     1/1     1            1           12h
kubernetes-dashboard   dashboard-metrics-scraper   1/1     1            1           12h
kubernetes-dashboard   kubernetes-dashboard        1/1     1            1           12h
```

In the pod logs I only see
`exec /bin/sh: exec format error`

The same holds true if i create the resource from the dashboard > create from form.

I am running on apple silicon (M1) and docker driver ie. `minikube config set driver docker`

**Comment by tamilselvan1102** [comment]
GitHub is not the right place for support requests @dark3rMatt3r 

If you are looking for help about using Kubernetes, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes) and ask your question there if a similar question has not yet been answered.

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by tamilselvan1102** [comment]
it is working fine for me.
![image](https://github.com/kubernetes/website/assets/20103020/a279de87-aaa2-4b3e-9aaf-a564b25c5daf)

### Env
ubuntu 22.04 & kubeadm

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by stmcginnis** [comment]
As said, this is not the right place. But just a pointer - it looks like the reference doesn't use a mutli-arch image. So it is trying to run an amd64 container on your arm64 machine.

This could potentially still be a valid docs issue if there is a better image to use here. Or perhaps a warning that the documented procedure is only for amd64 architecture machines. But you will need to find an arm64 image to use.

**Comment by dark3rMatt3r** [comment]
https://github.com/kubernetes/website/issues/45143
