### ISSUE TITLE
Update DaemonSet Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4513]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Study the existing topics on DaemonSets. Consolidate, expand, or update as needed. Here are some of the existing topics:

* [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/)
* [Perform a Rolling Update on a DaemonSet](https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/)
* [Performing a Rollback on a DaemonSet](https://kubernetes.io/docs/tasks/manage-daemon/rollback-daemon-set/)
* [Federated DaemonSet](https://kubernetes.io/docs/tasks/administer-federation/daemonset/)

**Comment by janetkuo** [comment]
I previously wrote a [DaemonSet documentation plan](https://docs.google.com/document/d/1ynyiwIQOprdgXbf9vmj-qZ6kpYh2lQFSaqo30I_-OiY/edit). We can add the following DaemonSet docs:

- [ ] Tutorial: Creating a basic DaemonSet 
- [ ] Task: Debugging a DaemonSet 
- [ ] Task: Running Pods on Only Some Nodes
- [ ] Task: Completely deleting a DaemonSet 
- [ ] Task: Creating a DaemonSet to adopt existing DaemonSet pods

**Comment by tengqm** [comment]
keep? @steveperry-53

**Comment by janetkuo** [comment]
I wanted to turn this blogpost into a tutorial for rolling update a DaemonSet, but haven't found time to do so: http://blog.kubernetes.io/2017/09/kubernetes-statefulsets-daemonsets.html

cc @ahmetb

**Comment by ahmetb** [comment]
I'm not sure how useful a "tutorial" would be, as our tutorials are mostly introductory and DaemonSet is a rather administrative/advanced topic. As long as we have a good Task on this topic, it should be fine.

**Comment by sftim** [comment]
Closing this; https://github.com/kubernetes/website/issues/39766 feels like the important detail to retain and track.

/close not-planned
