### ISSUE TITLE
Update Storage Docs

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#4514]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Study the existing docs on storage. Update, consolidate, or expand as needed. Here are some of the existing topics:

* [Persistent Volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)
* [Volumes](https://kubernetes.io/docs/concepts/storage/volumes/)
* [Limit Storage Consumption](https://kubernetes.io/docs/tasks/administer-cluster/limit-storage-consumption/)
* [Configure a Pod to Use a PersistentVolume for Storage](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/)
* [Configure a Pod to Use a Volume for Storage](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/)
* [Configure a Pod to Use a Projected Volume for Storage](https://kubernetes.io/docs/tasks/configure-pod-container/configure-projected-volume-storage/)

**Comment by sftim** [comment]
I didn't realise how hard https://kubernetes.io/docs/concepts/storage/volumes/ is to understand.

/remove-priority backlog
/priority important-longterm

**Comment by msau42** [comment]
Yes I think all the storage docs could use a bit of a redesign. Tasks and concepts are often interleaved for many features, and many of the pages have grown very large as we've added more features over time, as well as some descriptions becoming stale.

**Comment by sftim** [comment]
Closing in favor of issue https://github.com/kubernetes/website/issues/45873

/close not-planned

**Comment by sftim** [comment]
/remove-triage accepted

See https://github.com/kubernetes/website/issues/45873
