### ISSUE TITLE
Add warning or info block to basic tutorial

### ISSUE THREAD

**Issue by dark3rMatt3r** [kubernetes/website#45143]
**This is a Feature Request**

**What would you like to be added**
The following resource mentions kubernetes-bootcamp in the google-samples registry: https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

This does not work on Apple Silicon as reported here: https://github.com/kubernetes/website/issues/45131

If there is a better image perhaps this can be replaced or the doc can be updated with a warning or info block

**Why is this needed**
This would help others on apple silicon who are trying to follow the guide 

**Comments**

A similar issue was reported here and apple silicon was also implicated as the reason for failure

**Comment by sftim** [comment]
> Note: This tutorial uses a container that requires the AMD64 architecture. If you are using minikube on a computer with a different CPU architecture, you could try using minikube with a driver that can emulate AMD64. For example, the Docker Desktop driver can do this.

There's a note already, @dark3rMatt3rm, and it's the first paragraph. I think there's only so much we can do to help readers.


I'm willing to repeat the note at the foot of the page - would you like to send in a pull request?

/triage invalid

**Comment by sftim** [comment]
Oh, and: if what you're telling is us that the note is there but _wrong_, please file that as a separate bug.

**Comment by reylejano** [comment]
I'm closing this issue for the following reasons:
- as stated before, there is already a note regarding this
- if we change the container image used to one that works on macos then it won't work on linux where most Kubernetes clusters are installed on

Perhaps a valid request is to add an additional example that works on macos, if so please create a new issue

/close
