### ISSUE TITLE
Lack of clarity on usage of  `InitConfiguration` within the "Troubleshooting kubeadm"  page

### ISSUE THREAD

**Issue by jdbarnes-isi** [kubernetes/website#45158]
In the paragraph under https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubelet-client-cert

`
2. From a working control plane node in the cluster that has /etc/kubernetes/pki/ca.key execute kubeadm kubeconfig user --org system:nodes --client-name system:node:$NODE > kubelet.conf. $NODE must be set to the name of the existing failed node in the cluster. Modify the resulted kubelet.conf manually to adjust the cluster name and server endpoint, or pass kubeconfig user --config (it accepts InitConfiguration). If your cluster does not have the ca.key you must sign the embedded certificates in the kubelet.conf externally.
`
I do not know where or what the "InitConfiguration" is, nor does the command run without specifying a --config.

Could someone add a little more information or example to this?

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm

/language en

**Comment by dipesh-rawat** [comment]
/retitle Lack of clarity on usage of  `InitConfiguration` within the "Troubleshooting kubeadm"  page

**Comment by neolit123** [comment]
all kubeadm commands have reference pages
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig/

**Comment by tamilselvan1102** [comment]
About InitConfiguration is explained [here ](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/#kubeadm-k8s-io-v1beta4-InitConfiguration)

**Comment by neolit123** [comment]
> all kubeadm commands have reference pages https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig/

if you go to that page there is a guide on how to generate kubeconfig files.

but the text under https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubelet-client-cert

should probably mention https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-kubeconfig/

/help
/triage accepted

replace:
> (it accepts InitConfiguration

with:
> (see [Generating kubeconfig files for additional users](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#kubeconfig-additional-users))

**Comment by tamilselvan1102** [comment]
@neolit123 
Please review the PR.

**Comment by jdbarnes-isi** [comment]
I just wanted to say thank you very much. I really appreciate that link going into the paragraph so I can follow it to the reference.
