### ISSUE TITLE
[en] replace 'control' with 'controller' in content/en/docs/concepts/policy /_index.md

### ISSUE THREAD

**Issue by saurabh3460** [kubernetes/website#45171]
Discrepancy in terminology usage of 'control' and  'controller' in these two lines 

https://github.com/kubernetes/website/blob/61fa6a099246c0e903302e1f356a340557fc06ca/content/en/docs/concepts/policy/_index.md?plain=1#L45

https://github.com/kubernetes/website/blob/61fa6a099246c0e903302e1f356a340557fc06ca/content/en/docs/concepts/policy/_index.md?plain=1#L54

**Comment by sftim** [comment]
/priority awaiting-more-evidence

“[Admission control](https://en.wikipedia.org/wiki/Admission_control)” is what admission controllers provide; I don't think the docs are wrong.

**Comment by saurabh3460** [comment]
What I assume is in the same page `controllers` is being used https://kubernetes.io/docs/concepts/policy/#apply-policies-using-admission-controllers

Let me know what's your take @sftim, if it's not working can close this issue

**Comment by sftim** [comment]
Nothing to fix. Admission controllers are part of how Kubernetes implements admission control.

/close not-planned
