### ISSUE TITLE
Create a guide to writing a new scheduler

### ISSUE THREAD

**Issue by spzala** [kubernetes/website#4517]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

Feature Request
**Problem:**
As originally described in a kubernetes issue, https://github.com/kubernetes/kubernetes/issues/17208, after implementation of https://github.com/kubernetes/kubernetes/issues/11793 users can create their own custom scheduler but there is no specific doc out there which can clearly explain how to create a custom scheduler. Both above mentioned kubernetes issues are loaded with good discussion. 

**Proposed Solution:**
One of the thoughts is that if we can clearly document 'how the default scheduler is structured', users can simply modify it per their need, as @davidopp has explained in the https://github.com/kubernetes/kubernetes/issues/17208 

@davidopp @timothysc I guess the possible closest doc out there is https://github.com/kubernetes/community/blob/master/contributors/devel/scheduler.md - is that something satisfies the need? or should that be use as a starting point to write a new guide? 
Also, the other relevant doc I guess is https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/ 

**Page to Update:**
http://kubernetes.io/...

**Comment by ahmetb** [comment]
cc: @erictune 

I've been also having to create guides for extending Kubernetes on the docs site, such as:

- Writing Custom Scheduler
- Using Custom Resource Definitions
- Writing an Initializer

It's been low-priority on my list, mostly because people looking for it know where to find it. That said, having these docs and sample code would totally help people interested to get started. Maybe we can create a new repo to host the code for this. Kelsey has sample code here https://github.com/kelseyhightower/scheduler we can leverage right away. 

What do you think @spzala ?

**Comment by davidopp** [comment]
I think writing a custom scheduler is much lower priority than the other two from a documentation standpoint, as many more people are likely to write a CRD or initializer than a scheduler.

Also we may change the scheduler a bit as a result of the local presistent volume work, so I would suggest to wait.

**Comment by spzala** [comment]
@ahmetb that's so cool. Agree with you. I guess we just need to doc that repo or in simplest case we can just provide a reference to it in the doc. If I can help with it in any way please let me know. I am glad to have comment from @davidopp (original reporter/requester of this need). Thanks!

**Comment by zacharysarah** [comment]
Adding a link to an external reference seems like a great place to start. 👍

**Comment by nikhita** [comment]
/remove-lifecycle rotten

Still relevant.

**Comment by DanyC97** [comment]
/language en
/sig scheduling

is this something which can fall into https://github.com/kubernetes/website/pull/10702 ?

**Comment by sftim** [comment]
Given that there are now [scheduling plugins](https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/#extension-points), is this still needed?
/remove-lifecycle frozen
