### ISSUE TITLE
API Access Control

### ISSUE THREAD

**Issue by KANGA94** [kubernetes/website#45179]

**Comment by dipesh-rawat** [comment]
@KANGA94 Hi, Could you please share the details on the issue you would like to report or the assistance you require? Kindly provide details in the description of the issue.

/triage needs-information

**Comment by dipesh-rawat** [comment]
/close not-planned

@KANGA94  You are welcome to reopen this and add [details](https://github.com/kubernetes/website/issues/45179#issue-2139929913).
