### ISSUE TITLE
Broken link to "Weave Net" documentation in "Installing Addons" page

### ISSUE THREAD

**Issue by cShirley14** [kubernetes/website#45201]
The following link for Weave Net is no longer viable, and should be updated (e.g. pointing to the GitHub repo where it is now maintained, https://github.com/weaveworks/weave, which admittedly needs to be updated, but puts the onus on the project itself):

> [Weave Net](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/) provides networking and network policy, will carry on working on both sides of a network partition, and does not require an external database.

Google link-to-highlight: https://kubernetes.io/docs/concepts/cluster-administration/addons/#:~:text=public%20cloud%20environments.-,Weave%20Net,-provides%20networking%20and

**Comment by dipesh-rawat** [comment]
_Page related to the issue:_ https://kubernetes.io/docs/concepts/cluster-administration/addons
/language en

**Comment by dipesh-rawat** [comment]
/retitle Broken link to "Weave Net" documentation in "Installing Addons" page
/kind bug

**Comment by dipesh-rawat** [comment]
The suggestion to update the link from the outdated documentation website to the Weave Net GitHub repository (https://github.com/weaveworks/weave) seems like a sensible solution for now.

**Comment by dipesh-rawat** [comment]
Additionally, upon reviewing the Weave Net project on [GitHub](https://github.com/weaveworks/weave), it appears there hasn't been any activity for quite some time (2+ years!). In the longer term, it might be worth considering removing the link if this continues to be the case.

**Comment by kingdonb** [comment]
I'd suggest to follow the maintained fork instead, now that there is one:

https://github.com/kubernetes/website/pull/45202#issuecomment-1976819974

**Comment by reylejano** [comment]
I suggest we remove the line
https://github.com/weaveworks/weave hasn't had a commit in 2 years and Weave Works is shutting down

**Comment by Shubham82** [comment]
Closing this issue as it is resolved by PR #45445
