### ISSUE TITLE
Improvement for k8s.io/zh-cn/docs/contribute/style/content-guide/

### ISSUE THREAD

**Issue by chenqinhao0815** [kubernetes/website#45205]
看了官方文档，容器运行时安装成功，但是还是不能将k8s安装成功。

**Comment by AmarNathChary** [comment]
hi @chenqinhao0815 please provide the issue description in English for a better understanding

**Comment by prashant235913** [comment]
hiii , I have translated the sentence using more than one source and what I understood @chenqinhao0815 is saying-
"After reading the official documentation, the container runtime installation was successful, but k8s still cannot be installed successfully."

Lets look on this @AmarNathChary and tell me if i can be helpful.

**Comment by sftim** [comment]
Please avoid using GitHub for support; there are other venues we'd like to promote instead.

**Comment by chenqinhao0815** [comment]
> 你好@chenqinhao0815请提供英文问题描述以便更好地理解
I was unable to deploy the latest k8s to the ubuntu virtual machine. I have successfully installed the container runtime, but executing kubeadm init reports an error: timeout. Thank you for your reply

**Comment by niranjandarshann** [comment]
Hey  @chenqinhao0815  Thank you for your contribution . Keep Contributing as this is the support issue and you can ask support issue either in slack channel or discussion forum.
So I am closing the issue .
If you find something useful for community to add feature or to resolve some bug or improve the doc you mayraise the issue.
Feel free to contribute the useful stuff.

**Comment by niranjandarshann** [comment]
So I am closing this issue.
/close not-planned
