### ISSUE TITLE
[hi] Localize /docs/setup/production-environment/tools/

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#45213]
**This is a Feature Request**

**What would you like to be added**
Localize docs/setup/production-environment/tools/ in Hindi

**Page -**
https://kubernetes.io/docs/setup/production-environment/tools/

**Comment by utkarsh-singh1** [comment]
Also follow these guidelines for localize content ⇾

- Before translation, try to adjust space, indentation or tab, sometimes it can change the meaning of passage or line.
- Remove any extra text or character like glossary_tooltip, {{}}, <> etc. or it may cause error.
- Lookout for term_id mention in [glossary_tooltip](https://github.com/kubernetes/website/tree/main/content/hi/docs/reference/glossary), wrong term_id can cause error.

**Comment by steve-hardman** [comment]
Hey @utkarsh-singh1 Could you add "accepted" label to this issue too? I believe that "good first issue" and "help wanted" labels are typically associated wit accepted issue which are ready to be worked on by people.

**Comment by steve-hardman** [comment]
Oops, my mistake, I didn't read properly, its a Hindi issue, but it would still be beneficial to add `accepted` label if it's suitable as a good first issue.

**Comment by ArvindParekh** [comment]
I'd like to help out with this.
/assign

**Comment by Shubhdeep02** [comment]
@utkarsh-singh1 is the issue still open?

**Comment by utkarsh-singh1** [comment]
> @utkarsh-singh1 is the issue still open?

Already assigned by someone, you can look at the assignee to find about if issue is still available.

**Comment by ArvindParekh** [comment]
Hi @Shubhdeep02, thanks for asking here. I've raised a PR for this and it is currently in review. Feel free to add your inputs, if you have any :)
