### ISSUE TITLE
特性门控

### ISSUE THREAD

**Issue by wenwutang1** [kubernetes/website#45224]
missing ExpandCSIVolumes featureGates

in v1.26 ![image](https://github.com/kubernetes/website/assets/45817987/49ad4f6d-5661-4c3e-b21f-ecea3372b417)

but it missing v1.27 doc

**Comment by AmarNathChary** [comment]
**_Page related to the issue_** : https://v1-26.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by dipesh-rawat** [comment]
In v1.27, the `ExpandCSIVolumes` feature gate has been removed, and it is now documented on the [Feature Gate (removed) page](https://v1-27.docs.kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/#feature-gates-that-are-removed). Additionally, this has been highlighted in the "Removals and Major Changes in v1.27" blog post, which you can check out here: [blog/upcoming-changes-in-kubernetes-v1-27](https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/#removal-of-several-feature-gates-for-volume-expansion)

**Comment by sftim** [comment]
/triage unresolved
/priority awaiting-more-evidence
/close not-planned

Please file issues in English. However, this doesn't sound like a bug.
