### ISSUE TITLE
Broken link to "Install the Weave Net addon" documentation in "Weave Net for NetworkPolicy" page

### ISSUE THREAD

**Issue by cShirley14** [kubernetes/website#45257]
The following links for Weave Net are no longer viable, and should either be updated (e.g. pointing to the GitHub repo where it is now maintained, https://github.com/weaveworks/weave, which again, admittedly needs to be updated, but puts the onus on the project itself), or the page should be completely removed:

> Install the Weave Net addon
> Follow the [Integrating Kubernetes via the Addon](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/) guide.
> 
> The Weave Net addon for Kubernetes comes with a [Network Policy Controller](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#npc) that automatically monitors Kubernetes for any NetworkPolicy annotations on all namespaces and configures iptables rules to allow or block traffic as directed by the policies.

Google link-to-highlight: https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy/#:~:text=Install%20the%20Weave,by%20the%20policies.

This issue resembles #45201

**Comment by cShirley14** [comment]
Submitted PR #45258 with fix for review and merge.

**Comment by dipesh-rawat** [comment]
_Page mentioned in the issue:_ https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/weave-network-policy
/language en
/kind bug
