### ISSUE TITLE
[ko] Incorrect topology label in "Pod Topology Spread Constraints" page

### ISSUE THREAD

**Issue by omkensey** [kubernetes/website#45254]
In the [English version](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) of the above page, the last paragraph of the Consistency section reads:

> You need a mechanism to ensure that all the nodes in a topology domain (such as a cloud provider region) are labelled consistently. To avoid you needing to manually label nodes, most clusters automatically populate well-known labels such as `kubernetes.io/hostname`. Check whether your cluster supports this.

But in the [Korean page](https://kubernetes.io/ko/docs/concepts/scheduling-eviction/topology-spread-constraints/)'s version of that paragraph, the label used as an example is `topology.kubernetes.io/hostname` which is incorrect.

**Comment by dipesh-rawat** [comment]
/retitle [ko] Incorrect topology label in "Pod Topology Spread Constraints" page
/kind bug

**Comment by jihoon-seo** [comment]
@omkensey Thanks for raising this issue.
The outdatedness of that page has been reported in the issue #41613,
and updated to the `dev-1.27-ko.1` branch via the PR #41825. ([Fixed line](https://github.com/kubernetes/website/pull/41825/files#diff-effd67469b5f746d099e501dcf8033f7c9be69c8c96e3ea5648e39f596bda2f7R251))
When the `dev-1.27-ko.1` branch gets merged into `main` in the future, we will be able to check the updated contents.

Considering the aspects above, let me close this issue.
Again, thank you for your contribution!

/triage duplicate
/close
