### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by irosenzw** [kubernetes/website#4526]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
running the second command on the 3rd step of the 2nd module gives an ERROR:

Error: 'dial tcp 172.18.0.2:8080: getsockopt: connection refused'
Trying to reach: 'http://172.18.0.2:8080/'

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

1.5.2

**Comment by zacharysarah** [comment]
@BenHall 👋

**Comment by BenHall** [comment]
Thanks @irosenzw. In this scenario, you need to use the kubectl proxy to access the service running on port 8081.

I hope this helps.

**Comment by zymsys** [comment]
I've also run into this while going through the tutorial. I have the proxy running on the 2nd tab:

```
$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

Back on the first tab I have run the suggested command by clicking it:

```
$ curl http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAME/
Error: 'dial tcp 172.18.0.2:8080: getsockopt: connection refused'
```

Note that the command line specifies localhost:8001 but the error specifies another IP on a different network and a different port. Re-running the command with verbose mode shows that it is connecting to the correct IP and port, but then getting the error:

```
$ curl -v http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAME/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 8001 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8001 (#0)
> GET /api/v1/proxy/namespaces/default/pods/kubernetes-bootcamp-3765622183-2099l/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8001
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Content-Length: 108
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 23 Nov 2017 13:23:21 GMT
<
Error: 'dial tcp 172.18.0.2:8080: getsockopt: connection refused'
* Connection #0 to host localhost left intact
Trying to reach: 'http://172.18.0.2:8080/'$
```

I had started the tutorial on my iPad on the train to work and continued on my notebook at the office, skipping module 1. I restarted from module 1 on the notebook and was able to get past this step:

```
$ curl http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAME/
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-390780338-0lcbd | v=1
```

I imagined that each module was self-contained, but maybe not? I haven't tried further testing, but maybe this helps someone else who runs into the issue, or the wonderful people who built and maintain the tutorial.

**Comment by BenHall** [comment]
Please check to make sure the Kuberentes Bootcamp image has been deployed using:

```
$ kubectl run kubernetes-bootcamp --image=docker.io/jocatalin/kubernetes-bootcamp:v1 --port=8080
```

The errors seem to indicate the process isn't running. It's the first command on step 2.

**Comment by zymsys** [comment]
It took me a while to realize that I could click the commands instead of typing them. I may have mis-typed that line on the first pass. On the second pass I clicked all of the commands and it worked fine. I know there was no obvious error when I typed it, but I could have entered an incorrect port number. Thanks for the quick followup!

**Comment by errordeveloper** [comment]
Sounds like this could be closed?

**Comment by zymsys** [comment]
I'd say so.
