### ISSUE TITLE
Document supported versions of Kubernetes

### ISSUE THREAD

**Issue by birdofprey** [kubernetes/website#45277]
整本手册如何下载保存到本地，搞一个哦。方便查阅

**Comment by AmarNathChary** [comment]
Please provide the issue description in English

**Comment by sftim** [comment]
/triage needs-information

We track issues in English - can you add an English translation and set the issue title to be in English?

**Comment by aj11anuj** [comment]
/retitle Document supported versions of Kubernetes
/remove-language zh
/sig docs
/kind feature

<h3>Description (Translation)</h3>
How to download and save the entire manual to your local computer? Document one. Easy to read

**Comment by sftim** [comment]
What needs doing?

**Comment by reylejano** [comment]
@birdofprey , can you add an English translation to the description

**Comment by divya-mohan0209** [comment]
@birdsofprey Since there has been no response for > 2 months, I'm closing this issue. Please feel free to reopen it with the description when you have the bandwidth.
