### ISSUE TITLE
Link to closed issue 23398

### ISSUE THREAD

**Issue by remram44** [kubernetes/website#45308]
**This is a Bug Report**

https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/ links to https://github.com/kubernetes/kubernetes/issues/23398 in two separate places, however that issue has been closed by your bots.

This gives very confusing information, while the site claims that this is "not supported yet", following the link will show that you don't care anymore and had a bot close the issue.

**Proposed Solution:**

Either reopen the issue and make sure your bot don't break your links. Or remove the link to this issue if you truly don't intend to implement this.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

**Comment by sftim** [comment]
Even closed issues can be informative. However, I believe we've now revised that page.

**Comment by remram44** [comment]
Fixed by a8ec490629ae1cadb9feaa69e83fc4edcdac3e26
