### ISSUE TITLE
[es] localize content/en/docs/tasks/network/customize-hosts-file-for-pods.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#45318]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/tasks/network/customize-hosts-file-for-pods.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by krol3** [comment]
closing in favor of https://github.com/kubernetes/website/issues/48073
/close
