### ISSUE TITLE
[es] localize content/en/docs/tasks/network/validate-dual-stack.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#45317]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/tasks/network/validate-dual-stack.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by ramrodo** [comment]
Hi @jheimar do you want us to continue your contribution or do you want to create another PR?

**Comment by ramrodo** [comment]
Being solved at https://github.com/kubernetes/website/pull/46104

**Comment by krol3** [comment]
closing in favor of https://github.com/kubernetes/website/issues/48073
/close
