### ISSUE TITLE
[es] localize content/en/docs/tasks/run-application/access-api-from-pod.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#45316]
**This is a Feature Request**

**What would you like to be added**
Localize `content/en/docs/tasks/run-application/access-api-from-pod.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by h3ct0rjs** [comment]
Hi @ramrodo is it possible to  assign this to me, I'm currently at KubeDay Colombia, also can we add the hacktoberfest topic to the repo, this would help me to achieve my pr goals.
