### ISSUE TITLE
Inactive and deprecated 'Interactive Tutorial' link in "Configuring a Java Microservice" page

### ISSUE THREAD

**Issue by kancherlanagaraju** [kubernetes/website#45321]
We can remove the "Start Intervactive Tutorial" link from the below URL as it is decommissioned 2 years back.
https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/

The above  hyper link is misleading as if like the Interactive tutorial is available . I think, it is obsolete distraction for the users who are learning from k8s documentation.

https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice-interactive/
https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/

**Comment by dipesh-rawat** [comment]
_Page mentioned in the issue:_ https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Inactive and deprecated 'Interactive Tutorial' link in "Configuring a Java Microservice" page

**Comment by dipesh-rawat** [comment]
This looks similar to issue we already have https://github.com/kubernetes/website/issues/42401
I think it is a duplicate.

/triage duplicate

**Comment by dipesh-rawat** [comment]
Thanks for raising this!

However, closing this request as it closely mirrors the original issue. Feel free to continue the discussion on the original issue.

/close not-planned
