### ISSUE TITLE
[ja] Translate `content/en/docs/tasks/tools/install-kubectl-windows.md` into Japanese 

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45346]
**This is a Feature Request**

**What would you like to be added**

Translate `content/en/docs/tasks/tools/install-kubectl-windows.md` into Japanese 

**Why is this needed**

There is no Japanese translation for this page

**Comments**

- File to translate: 
    - https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/tools/install-kubectl-windows.md
- Original:
    - https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/

日本語に翻訳する際は、以下のドキュメントを参考にしてください

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

**Comment by levi106** [comment]
@Okabe-Junya 
Pull request 前に一つ質問があります。
install-kubectl-windows.md は内部で included/ の下にある .md ファイルを埋め込んでいます (verify-kubectl.md など)。`make container-serve` で確認しながら必要なファイルを ja/ にコピーしていくと、直接は参照していない下記のファイルも必要そうでした。
- install-kubectl-linux.md
- install-kubectl-macos.md
- included/optional-kubectl-configs-bash-linux.md
- included/optional-kubectl-configs-bash-mac.md
- included/optional-kubectl-configs-fish.md
- included/optional-kubectl-configs-zsh.md

これらのファイルについては翻訳せずにそのままコピーしたものをコミットするという対応でよいでしょうか？
 
以下がフォークしたリポジトリでの変更です。
https://github.com/levi106/website/commit/d12082bcb44bddfe3833ff25c48e0848d2fbd791

**Comment by Okabe-Junya** [comment]
ありがとうございます〜！ほんとだ。。手元で確認してみましたが、確かにいくつかのファイルが必要そうですね

```bash
Source changed WRITE         "/src/content/ja/docs/tasks/tools/install-kubectl-windows.md"
Source changed WRITE         "/src/content/ja/docs/tasks/tools/install-kubectl-windows.md"
ERROR [ja] no Resource or Page matching "included/verify-kubectl.md*".
ERROR [ja] no Resource or Page matching "included/optional-kubectl-configs-pwsh.md*".
ERROR [ja] no Resource or Page matching "included/kubectl-convert-overview.md*".
ERROR [ja] no Resource or Page matching "included/kubectl-whats-next.md*".
ERROR Rebuild failed: logged 4 error(s)
Total in 9056 ms
```

> これらのファイルについては翻訳せずにそのままコピーしたものをコミットするという対応でよいでしょうか？

もちろん大丈夫です🙆‍♂️ ご確認いただきありがとうございます！もし可能であれば、これらのページを翻訳するissueを別途でi立てていただけるとさらに嬉しいです :)

**Comment by Okabe-Junya** [comment]
@levi106 

すいません、もう一点、PRにこの辺りの背景をざっくりまとめておいていただけると非常に助かります〜

**Comment by levi106** [comment]
@Okabe-Junya 
ありがとうございます、Pull Request 作成しました。もし思っていたのと違うところなどありましたらご指摘ください。
また、Issue の作成もありがとうございました。

**Comment by Okabe-Junya** [comment]
色々とありがとうございます〜！

レビュー詰まっていて恐縮ですが、改めて時間とって確認させて頂きますね :)

**Comment by Okabe-Junya** [comment]
> また、Issue の作成もありがとうございました。

すいません🙏作成はしていないです。。（類似のissueからリンク貼っただけです。）

作成をお願いしても大丈夫でしょうか。。？？（triageはこちらでやっておきます）

**Comment by levi106** [comment]
`install-kubectl-linux.md` を翻訳する際にその中に埋め込まれる
- `included/optional-kubectl-configs-bash-linux.md`
- `included/optional-kubectl-configs-fish.md`
- `included/optional-kubectl-configs-zsh.md`

も翻訳する必要があり、`install-kubectl-macos.md` を翻訳する際にその中に埋め込まれる
- `included/optional-kubectl-configs-bash-mac.md`

も翻訳する必要があるため、本 issue と #45344, #45345 で included 以下のファイルの翻訳はすべて網羅されると認識しています。ただ英語ドキュメントの方では削除済みの [install-kubectl.md](https://kubernetes.io/ja/docs/tasks/tools/install-kubectl/) が日本語ドキュメントの方に残っているので、

1. #45344 に `included/optional-kubectl-configs-bash-linux.md`, `included/optional-kubectl-configs-fish.md`, `included/optional-kubectl-configs-zsh.md` の翻訳も必要である旨コメントを書く
2. #45345 に `included/optional-kubectl-configs-bash-mac.md` の翻訳も必要である旨コメントを書く
3. `content/ja/docs/tasks/tools/install-kubectl.md` を削除する issue を新規に作成する

でよいでしょうか？

**Comment by Okabe-Junya** [comment]
> 本 issue と https://github.com/kubernetes/website/issues/45344, https://github.com/kubernetes/website/issues/45345 で included 以下のファイルの翻訳はすべて網羅されると認識しています。

すいません、この辺りの事情をきちんと把握できていませんでした💦

> ただ英語ドキュメントの方では削除済みの [install-kubectl.md](https://kubernetes.io/ja/docs/tasks/tools/install-kubectl/) が日本語ドキュメントの方に残っているので、 ... でよいでしょうか？

おっしゃる通りの対応で大丈夫です〜ありがとうございます！！
