### ISSUE TITLE
[ja] Translate `content/en/docs/tasks/tools/install-kubectl-macos.md` into Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45345]
**This is a Feature Request**

**What would you like to be added**

Translate `content/en/docs/tasks/tools/install-kubectl-macos.md` into Japanese 

**Why is this needed**

There is no Japanese translation for this page

**Comments**

- File to translate: 
    - https://github.com/kubernetes/website/blob/main/content/en/docs/tasks/tools/install-kubectl-macos.md
- Original:
    - https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/

日本語に翻訳する際は、以下のドキュメントを参考にしてください

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

**Comment by Okabe-Junya** [comment]
maybe related: https://github.com/kubernetes/website/issues/45346#issuecomment-1986740323

**Comment by levi106** [comment]
このファイルは次のスニペットをインクルードしているので、これらもあわせて翻訳する必要があります。
- included/optional-kubectl-configs-bash-mac.md
- included/optional-kubectl-configs-fish.md
- included/optional-kubectl-configs-zsh.md

また、ファイルは #45502 にて 09e79db50630c859a8eafcf02f16e5cb3f477430 時点の英語版のドキュメントをそのままコピーしています。
