### ISSUE TITLE
Document deprecated annotation `service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset`

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#45369]
**This is a Feature Request**

**What would you like to be added**
Document (and register) the legacy annotation `service.beta.kubernetes.io/azure-load-balancer-disable-tcp-reset`

The page to change is: https://kubernetes.io/docs/reference/labels-annotations-taints/

**Why is this needed**
We try to document all of our annotations, even the ones we ask people to stop using.

**Comments**
/language en
/lifecycle frozen
/sig network cloud-provider

**Comment by dipesh-rawat** [comment]
Could be useful, let's consider doing this.

/triage accepted
/priority backlog

**Comment by Ritikaa96** [comment]
I'd like to work on it
/assign
I'll share the findings here so the content is confirmed first.

**Comment by Ritikaa96** [comment]
I got reference from cloud-provider-azure [here](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/26d2f85ab6d784176d8d81c4716d93b60e832bbe/pkg/consts/consts.go#L345) and Microsoft docs.

**Comment by sftim** [comment]
From https://github.com/kubernetes-sigs/cloud-provider-azure/blob/26d2f85ab6d784176d8d81c4716d93b60e832bbe/pkg/consts/consts.go it looks like we need a pile of other issues about unregistered annotations for this cloud provider.

**Comment by Ritikaa96** [comment]
Yes, you can find the other annotations here: https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#loadbalancer-annotations
