### ISSUE TITLE
Migrate away from `getJSON` in Hugo

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#45370]
**This is a Feature Request**

**What would you like to be added**
Migrate to `transform.Unmarshal` instead of Hugo's `getJSON`

**Why is this needed**
Upstream Hugo has deprecated `getJSON`, which we use. We should aim to migrate to use `transform.Unmarshal`; see https://gohugo.io/functions/resources/getremote/#remote-data

**Comments**
We may need to upgrade to a newer Hugo as part of this work, or related to it.

/area web-development
/lifecycle frozen

**Comment by dipesh-rawat** [comment]
Let me see if I can assist with this.
/assign
