### ISSUE TITLE
[en] code blocks inside a table is not well rendered

### ISSUE THREAD

**Issue by howieyuen** [kubernetes/website#45389]
**This is a Bug Report**

**Problem:**

code format inside a table is not well-format, see the page:  

![88449e8437795253dba0c452b810ce55](https://github.com/kubernetes/website/assets/23924124/43922186-36d5-4244-9fe4-ebbc523b6fd3)

should looks like below:

| Golang marker | OpenAPI extension | Possible values | Description |
|---|---|---|---|
| `//+listType` | `x-kubernetes-list-type` | `atomic`/`set`/`map` | Applicable to lists. `set` applies to lists that include only scalar elements. These elements must be unique. `map` applies to lists of nested types only. The key values (see `listMapKey`) must be unique in the list. `atomic` can apply to any list. If configured as `atomic`, the entire list is replaced during merge. At any point in time, a single manager owns the list. If `set` or `map`, different managers can manage entries separately. |
| `//+listMapKey` | `x-kubernetes-list-map-keys` | List of field names, e.g. `["port", "protocol"]` | Only applicable when `+listType=map`. A list of field names whose values uniquely identify entries in the list. While there can be multiple keys, `listMapKey` is singular because keys need to be specified individually in the Go type. The key fields must be scalars. |
| `//+mapType` | `x-kubernetes-map-type` | `atomic`/`granular` | Applicable to maps. `atomic` means that the map can only be entirely replaced by a single manager. `granular` means that the map supports separate managers updating individual fields. |
| `//+structType` | `x-kubernetes-map-type` | `atomic`/`granular` | Applicable to structs; otherwise same usage and OpenAPI annotation as `//+mapType`.|

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy

**Comment by dipesh-rawat** [comment]
The appearance of inline code blocks in tables is determined by a specific [CSS rule](https://github.com/kubernetes/website/blob/9fdb0eb76b231e93a9dec4166a1c81fcddfaeaa4/assets/scss/_custom.scss#L868). This rule, which sets ["background-color: inherit!important;"](https://github.com/kubernetes/website/blob/9fdb0eb76b231e93a9dec4166a1c81fcddfaeaa4/assets/scss/_custom.scss#L868), overrides the background color of the code block and inherits the color from its parent element.

/area web-development

**Comment by dipesh-rawat** [comment]
/priority awaiting-more-evidence

I'm in favor of leaving things unchanged. No changes necessary, I prefer to keep it as it is.
