### ISSUE TITLE
Unable to upgrade kubeadm using 'apt' without unholding kubectl and kubelet

### ISSUE THREAD

**Issue by jhannink** [kubernetes/website#45393]
When I try to upgrade kubeadm with
```
apt-mark unhold kubeadm && \
apt-get update && apt-get install -y kubeadm='1.27.x-*' && \
apt-mark hold kubeadm
```
as descirbed [here](https://v1-27.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/), I can only do so by also unholding kubectl and kubelet due to package dependencies.

**Comment by dipesh-rawat** [comment]
_Page mentioned in issue:_  https://v1-27.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
/language en

_(Equivalent page in current version of docs: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade)_

**Comment by dipesh-rawat** [comment]
/retitle Unable to upgrade kubeadm using 'apt' without unholding kubectl and kubelet
/sig cluster-lifecycle

**Comment by neolit123** [comment]
> as descirbed [here](https://v1-27.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/), I can only do so by also unholding kubectl and kubelet due to package dependencies.

i don't recall this being a requirement.
if someone wish they can send an update, but please update all relevant places where there are similar unhold commands.

/triage accepted

**Comment by sftim** [comment]
If this looks like a packaging issue, please let us know. In particular I don't think `kubectl` should depend on `kubeadm`.

**Comment by neolit123** [comment]
@dev-johnn please hold the PRs for this.

@jhannink 

kubeadm / kubelet / kubectl packages shouldnot be cross-dependent. this is an old problem, but now it should be easier to fix given k8s versions are in separate repos.
https://github.com/search?q=repo%3Akubernetes%2Frelease+kubeadm+depends+on+kubelet&type=issues

so what you can do is log a k/release ticket, if the maintainers reject it, the docs can be updated.
if it's accepted this k/website ticket can be closed.

make sure you cross ref a k/release ticket here.

**Comment by jhannink** [comment]
Correct, there are no dependencies for versions of kubeadm>=1.26. Only the 25 > 26 upgrade has this documentation problem from my perspective

**Comment by neolit123** [comment]
> Correct, there are no dependencies for versions of kubeadm>=1.26. Only the 25 > 26 upgrade has this documentation problem from my perspective

that's surprising, are you sure that newer version don't have the same problem?
if it's only a 25 -> 26 problem then we should not make any changes to the docs, ideally because 1.26 just went out of support
https://kubernetes.io/releases/

**Comment by neolit123** [comment]
@xmudrii @saschagrunert i'm i reading correctly that kubeadm continues to depend on kubelet and kubectl.
https://github.com/kubernetes/release/blob/master/cmd/krel/templates/latest/metadata.yaml

i think we should drop these dependencies if possible given the new repository scheme we moved to.
- kubeadm can continue to depend on cri-tools, but not on kubelet and kubectl
- kubectl doesn't depend on anything which is OK
- kubelet depending on kubernetes-cni is OK (also i see iptables is hardcoded in the spec)

if you give me a green light i can PR the metadata.yaml file.

**Comment by saschagrunert** [comment]
> @xmudrii @saschagrunert am i reading correctly that kubeadm continues to depend on kubelet and kubectl? https://github.com/kubernetes/release/blob/master/cmd/krel/templates/latest/metadata.yaml

Yes, that's correct for the current state. I guess the intention was that it makes not much sense to use `kubeadm` without the kubelet. But maybe it does? I assume we can drop those dependencies. Do you mind proposing that in k/release so we can discuss it there?

> i think we should drop these dependencies if possible given the new repository scheme we moved to. maybe for 1.30.
> 
> * kubeadm can continue to depend on cri-tools, but not on kubelet and kubectl

Do we have a plan to remove this dependency? We have golang code to work directly with the CRI.

**Comment by neolit123** [comment]
> > @xmudrii @saschagrunert am i reading correctly that kubeadm continues to depend on kubelet and kubectl? https://github.com/kubernetes/release/blob/master/cmd/krel/templates/latest/metadata.yaml
> 
> Yes, that's correct for the current state. I guess the intention was that it makes not much sense to use `kubeadm` without the kubelet. But maybe it does? I assume we can drop those dependencies. Do you mind proposing that in k/release so we can discuss it there?

thanks.
yes, it does make sense to remove the dep in terms of upgrade process, because kubeadm should be upgraded before kubelet and right now users need to "hold" packages. it has been a problem for a long time.
the kubectl dependency is not needed.
i will log the ticket in a bit.

> 
> > i think we should drop these dependencies if possible given the new repository scheme we moved to. maybe for 1.30.
> > 
> > * kubeadm can continue to depend on cri-tools, but not on kubelet and kubectl
> 
> Do we have a plan to remove this dependency? We have golang code to work directly with the CRI.

today kubeadm depends on crictl from critools for talking to the container runtime on the host, but there is no problem during upgrade as the one explained above for the kubelet. yet, preferably we should continue to maintain the cri-tools package similarly to kubernetes-cni, so that these installation parts are automated for users at least.

**Comment by neolit123** [comment]
https://github.com/kubernetes/release/issues/3480

**Comment by neolit123** [comment]
solved at k/release
let's see what happens with the 1.30+ packages.

/close
