### ISSUE TITLE
Mention environment variables in Pod concept

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#45405]
**This is a Feature Request**

**What would you like to be added**
In https://kubernetes.io/docs/concepts/workloads/pods/, briefly mention that you can set environment variables for containers in Pods, and link to our pages about that. No need to add an explanation; this is about helping people discover the feature.

**Why is this needed**
This is about helping people discover the feature.

**Comments**
/sig node
/language en

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/website/pull/45125

**Comment by dipesh-rawat** [comment]
Potential improvement, worth doing.

/priority backlog
/triage accepted

**Comment by steve-hardman** [comment]
I would like to assist in resolving this issue. Thanks!
/assign

**Comment by sftim** [comment]
PRs are welcome!
