### ISSUE TITLE
Contradiction in Kubernetes API Aggregation Layer and Custom Resources pages

### ISSUE THREAD

**Issue by ricardoapl** [kubernetes/website#45409]
**This is a Bug Report**

**Problem:**

In [Kubernetes API Aggregation Layer](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/):

> The aggregation layer is different from [Custom Resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/), which are a way to make the [kube-apiserver](https://kubernetes.io/docs/concepts/overview/components/#kube-apiserver) recognise new kinds of object.

Yet in [Custom Resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#adding-custom-resources):

> Kubernetes provides two ways to add custom resources to your cluster:
> -   CRDs are simple and can be created without any programming.
> -   [API Aggregation](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/) requires programming, but allows more control over API behaviors like how data is stored and conversion between API versions.

**Proposed Solution:**

I'm not really sure what the intention here is/was, but perhaps where the [Kubernetes API Aggregation Layer](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/) page says

> Custom Resources

It should say

> Custom Resource Definitions

What do you think?

**Page to Update:**

One of the following
- https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#adding-custom-resources
- https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

**Comment by sftim** [comment]
/wg api-expression
/sig architecture
/language en

The proposed change sounds reasonable.

**Comment by tengqm** [comment]
/triage accepted
although I don't think this change makes a huge difference.

**Comment by vaibhav2107** [comment]
The issue is fixed in #47165 and hence we can close this isse
