### ISSUE TITLE
Documentation link for 'Weave Net' broken in 'Installing Addons' page

### ISSUE THREAD

**Issue by slavnyj** [kubernetes/website#45440]
Broken link to the Weave Net plugin.
[Weave Net](https://www.weave.works/docs/net/latest/kubernetes/kube-addon/) it's broken

USE IT LINK https://github.com/weaveworks/weave

**Comment by dipesh-rawat** [comment]
_Page related to issue:_ https://kubernetes.io/docs/concepts/cluster-administration/addons/
/language en
/kind bug

**Comment by dipesh-rawat** [comment]
/retitle Documentation link for 'Weave Net' broken in 'Installing Addons' page

**Comment by dipesh-rawat** [comment]
This looks similar to issue we already have https://github.com/kubernetes/website/issues/45201
I think it is a duplicate.

/triage duplicate

**Comment by reylejano** [comment]
Closing in favor of https://github.com/kubernetes/website/issues/45201
/close
