### ISSUE TITLE
Upgrading kubeadm clusters

### ISSUE THREAD

**Issue by chaabaney** [kubernetes/website#45453]
Procedure for upgrading from 1.28 to 1.29 doesn't word as indicated for Ubunto distro

sudo apt update
sudo apt-cache madison kubeadm

don't add kubernetes 1.29 repos are they aren't any more with debian repos and changed location

**Comment by chaabaney** [comment]
should add steps for kubernetes 1.29 as in 
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/


These instructions are for Kubernetes 1.29.

    Update the apt package index and install packages needed to use the Kubernetes apt repository:

    sudo apt-get update
    # apt-transport-https may be a dummy package; if so, you can skip that package
    sudo apt-get install -y apt-transport-https ca-certificates curl gpg

    Download the public signing key for the Kubernetes package repositories. The same signing key is used for all repositories so you can disregard the version in the URL:

    # If the folder `/etc/apt/keyrings` does not exist, it should be created before the curl command, read the note below.
    # sudo mkdir -p -m 755 /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

Note: In releases older than Debian 12 and Ubuntu 22.04, folder /etc/apt/keyrings does not exist by default, and it should be created before the curl command.

    Add the appropriate Kubernetes apt repository. Please note that this repository have packages only for Kubernetes 1.29; for other Kubernetes minor versions, you need to change the Kubernetes minor version in the URL to match your desired minor version (you should also check that you are reading the documentation for the version of Kubernetes that you plan to install).

    # This overwrites any existing configuration in /etc/apt/sources.list.d/kubernetes.list
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

**Comment by dipesh-rawat** [comment]
_Page related to issue (based on the current issue title):_ https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
/language en

**Comment by dipesh-rawat** [comment]
@chaabaney If I interpret the issue correctly, you're stating that during the upgrade from version 1.28 to 1.29, the newer Kubernetes 1.29 repository wasn't added, as it wasn't mentioned in the instructions?

/triage needs-information

**Comment by dipesh-rawat** [comment]
It's worth noting that there is already a section about "[Changing the package repository (here)](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#changing-the-package-repository
)" in the upgrading page stating that if you're using the community-owned package repositories (pkgs.k8s.io), you need to enable the package repository for the desired Kubernetes minor release.  It also includes useful link to a page with instructions on how to do this.

**Comment by neolit123** [comment]
> It's worth noting that there is already a section about "[Changing the package repository (here)](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#changing-the-package-repository)" in the upgrading page stating that if you're using the community-owned package repositories (pkgs.k8s.io), you need to enable the package repository for the desired Kubernetes minor release. It also includes useful link to a page with instructions on how to do this.

agreed, seems the information exists already
