### ISSUE TITLE
Broken link in the description of `RuntimeClassInImageCriApi` on "Feature Gates" page

### ISSUE THREAD

**Issue by thisisharrsh** [kubernetes/website#45450]
**This is a Bug Report**

**Problem:** In the [List of feature gates section](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates) of the [Feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) page, there is a section of `RuntimeClassInImageCriApi` that has an issue with the hyperlinking of the text. The `runtime class` is not hyperlinked properly. 

**Proposed Solution:** We should link the `runtime class` with the appropriate link, i.e., `https://kubernetes.io/docs/concepts/containers/runtime-class/`

**Page to Update:** https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by thisisharrsh** [comment]
I would to like to work on this issue, if the triage gets accepted.

**Comment by dipesh-rawat** [comment]
/retitle Broken link in the description of `RuntimeClassInImageCriApi` on "Feature Gates" page

**Comment by dipesh-rawat** [comment]
Fixes are welcomed.

/triage accepted
/priority backlog
