### ISSUE TITLE
Example unclear in Pod Overhead concept

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#45452]
**This is a Bug Report**

**Problem:**
In [Pod Overhead](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/), the page uses `kata-fc` (presumably Kata Containers with the Firecracker VMM), but doesn't explain where that name comes from or how that's associated with overhead.

**Proposed Solution:**
Either:
- change the example to use a fictional hypervisor
- explain where the name comes from

and in either case, explain that it's the runtime's overhead that needs accounting for (not the app's overhead).

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/

**Additional Information:**
/language en

**Comment by sftim** [comment]
Aside: maybe https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/ belongs inside https://kubernetes.io/docs/concepts/workloads/ but with a clear signpost to it from the pages about resource management (ResourceQuota etc) and about scheduling.

**Comment by AmarNathChary** [comment]
I will try to solve this issue.

**Comment by AmarNathChary** [comment]
I will raise a PR for this
/assign

**Comment by Shubhdeep02** [comment]
/assign me
I will look into it

**Comment by AmarNathChary** [comment]
Raised PR in : #45454

**Comment by Shubhdeep02** [comment]
Raised PR in - #45470

**Comment by AmarNathChary** [comment]
The issue is resolved
we can close this issue as PR got merged

**Comment by niranjandarshann** [comment]
closing the issue as it get resolved in ref of PR #45454
/close
