### ISSUE TITLE
[ja] Translate `content/en/docs/reference/glossary/containerd.md` into Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45476]
**This is a Feature Request**

**What would you like to be added**

Translate `content/en/docs/reference/glossary/containerd.md` into Japanese

**Why is this needed**

There is no Japanese translation for this page

**Comments**

- File to translate: 
    - https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/containerd.md
- Original:
    - https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-containerd

日本語に翻訳する際は、以下のドキュメントを参考にしてください。

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

**Comment by Shubhdeep02** [comment]
Raised PR in #45478

**Comment by Okabe-Junya** [comment]
Hi @Shubhdeep02 

Thank you for interesting in SIG-docs ja subproject !!

This is a Japanese localization Project, but It looks that you live in India and you are fluent Hindi / English. So, Participating in Hindi projects is helpful for k/website :)

thank you

**Comment by Okabe-Junya** [comment]
I checked #45478, but it looks that this translation is made by google translation (or any other auto-translation tools). we cannot accept the pr like this.

**Comment by Shubhdeep02** [comment]
@Okabe-Junya I sincerely apologize for the problems occurred due to me , and thanks for your support.

**Comment by Okabe-Junya** [comment]
Thank you for understanding @Shubhdeep02

Your motivation is really excellent for the kubernetes community, so I believe that you will be able to make a valuable contribution. 

Please don't hesitate to contact me if there's anything you need support with. Thank you :)

**Comment by Okabe-Junya** [comment]
Thank you for understanding @Shubhdeep02

Your motivation is really excellent for the kubernetes community, so I believe that you will be able to make valuable contributions!! 

Please don't hesitate to contact us if there's anything you need support with. Thank you :)

**Comment by Okabe-Junya** [comment]
よろしくお願いします〜

お手数ですが、PR作成したら、作成したPRのコメントに `/cc Okabe-Junya` と打っていただいてもいいですか🙏🙏
