### ISSUE TITLE
[ja] Translate `content/en/docs/reference/glossary/cri.md` into Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#45475]
_Note that this issue is for Japanese Speaker_

**This is a Feature Request**

**What would you like to be added**

Translate `content/en/docs/reference/glossary/cri.md` into Japanese

**Why is this needed**

There is no Japanese translation for this page

**Comments**

- File to translate: 
    - https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/cri.md
- Original:
    - https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-cri

日本語に翻訳する際は、以下のドキュメントを参考にしてください。

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

**Comment by Okabe-Junya** [comment]
/unassign Shubhdeep02

PTAL https://github.com/kubernetes/website/issues/45476#issuecomment-1985887219, thank you

**Comment by Okabe-Junya** [comment]
Hi @kushalShukla-web, thank you for interesting in SIG-docs Japanese Localization project!!

Localization requires native or equivalent Japanese language proficiency. It looks you live in Pune, India. Please confirm this before working on this issue.

I believe the issues labeled with `language/hi` or `language/en` (or those you created) are areas where you can contribute more effectively.

- issues labeled with `language/hi`: https://github.com/kubernetes/website/issues?q=is%3Aopen+is%3Aissue+label%3Alanguage%2Fhi
- issues labeled with `language/en`: https://github.com/kubernetes/website/issues?q=is%3Aopen+is%3Aissue+label%3Alanguage%2Fen

Thank you

**Comment by rihib** [comment]
Hello, @Okabe-Junya -san, this issue looks good as my first contribution.

よろしくお願いいたします🙏

/assign
