### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

### ISSUE THREAD

**Issue by Khaos66** [kubernetes/website#45499]
**This is a Bug Report**

**Problem:**
The `StartKubelet.ps1` created by `PrepareNode.ps1` still includes the `--log-dir` and `--logtostderr` cli attributes, which are depricated for some time and removed in current versions of kubelet.

**Proposed Solution:**
Add a hint on that issue, as it's hard to diagnose for newbies (no logs are written anywhere)

**Page to Update:**
https://kubernetes.io/...

**Comment by dipesh-rawat** [comment]
@Khaos66 Could you please provide the exact URL of the page you're referring to from the [Kubernetes documentation](https://kubernetes.io/)? This will help us understand the context better and address the issue effectively.

/triage needs-information

**Comment by Khaos66** [comment]
Sure, here you go: 
https://k8s-dev-ko.netlify.app/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/#joining-a-windows-worker-node

**Comment by sftim** [comment]
Hi. That website is not the Kubernetes documentation (it's a stale copy).

See https://k8s.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#joining-a-windows-worker-node

/kind support

**Comment by neolit123** [comment]
> The StartKubelet.ps1 created by PrepareNode.ps1 still includes the --log-dir and --logtostderr cli attributes, which are depricated for some time and removed in current versions of kubelet.

this should be logged as a ticket in 
https://github.com/kubernetes-sigs/sig-windows-tools

https://github.com/kubernetes-sigs/sig-windows-tools/blob/dcc77000dc7ea1ec35a1bd5877c660edc4c37310/hostprocess/PrepareNode.ps1#L81

**Comment by sftim** [comment]
> > The StartKubelet.ps1 created by PrepareNode.ps1 still includes the --log-dir and --logtostderr cli attributes, which are depricated for some time and removed in current versions of kubelet.
> 
> this should be logged as a ticket in https://github.com/kubernetes-sigs/sig-windows-tools
> 
> https://github.com/kubernetes-sigs/sig-windows-tools/blob/dcc77000dc7ea1ec35a1bd5877c660edc4c37310/hostprocess/PrepareNode.ps1#L81

No need; that's a stale page.

**Comment by Khaos66** [comment]
Thank for all the nice feedback. Closing this now
