### ISSUE TITLE
Feature gate `NewVolumeManagerReconstruction` undocumented

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#45500]
**This is a Bug Report**

**Problem:**
Kubernetes includes a feature gate, `NewVolumeManagerReconstruction`. However, there's no documentation about that feature gate

**Proposed Solution:**
Document the feature gate.

**Page to Update:**
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
- Maybe some other concept pages about storage

**Additional Information:**
/sig storage
/language en
/kind bug

**Comment by dipesh-rawat** [comment]
@sftim Just to clarify if this is request is to add _additional_ documentation for the `NewVolumeManagerReconstruction` feature gate, considering there is already some information available about it on "[Feature Gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)" page, which is fetched as part of the feature gate description file [here](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/feature-gates/new-volume-manager-reconstruction.md).

**Comment by sftim** [comment]
I think I looked in the wrong place. I am not sure how I missed that. Anyway, nothing to fix.

/triage not-reproducible
/close not-planned
