### ISSUE TITLE
[ja] Delete `content/ja/docs/tasks/tools/install-kubectl.md`

### ISSUE THREAD

**Issue by levi106** [kubernetes/website#45502]
**This is a Feature Request**

**What would you like to be added**

Delete `content/ja/docs/tasks/tools/install-kubectl.md` from repository.

**Why is this needed**

The original file has been deleted in https://github.com/kubernetes/website/commit/87e3291aaa9ae384b1698ba7b1022c7509fa314b.

**Comments**

This file has been divided into per-OS documents.
The followings are the related issues.
- #45344
- #45345 
- #45346

/language ja

**Comment by Okabe-Junya** [comment]
Thank you~~

/area localization
/triage accepted
