### ISSUE TITLE
Users not instructed to SSH into the node before executing commands in "Upgrading Linux nodes" page

### ISSUE THREAD

**Issue by porrascarlos802018** [kubernetes/website#45539]
Missing important step new people

SSH into the node

**Comment by thisisharrsh** [comment]
Hi @porrascarlos802018, could you please explain the issue in detail. 
/triage needs-information

**Comment by dipesh-rawat** [comment]
_Page mentioned in the issue (based on the title):_ https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes
/language en

**Comment by dipesh-rawat** [comment]
/retitle Users not instructed to SSH into the node before executing commands in "Upgrading Linux nodes" page

**Comment by stmcginnis** [comment]
I'm not sure this is valid, though there isn't much detail to the issue to explain what the concern is.

The commands on that page need to be run on the node being upgraded, but I think how the administrator connects to that node is out of scope. It may be SSH, it may be by accessing the cloud providers console. It may be by rolling up a crash cart and plugging in a monitor and keyboard. That all depends on the individuals environment.

**Comment by thisisharrsh** [comment]
/kind support

It seems to be like a support request.

**Comment by sftim** [comment]
My opinion: if you don't know how to get a shell on a node, it may not be a good idea to try upgrading it. Best learn the basics first.

**Comment by sftim** [comment]
We could list “shell access to the node“ as a prerequisite. I don't think we can or should assume SSH; I'm barely happy that we assume superuser access comes via `sudo`.

**Comment by neolit123** [comment]
for new contributors.

page to update:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-linux-nodes/

change:
> You need to have a Kubernetes cluster, and the kubectl command-line tool must be configured to communicate with your cluster

to:
> You need to have a Kubernetes cluster, shell access to all its nodes, and the kubectl command-line tool must be configured to communicate with your cluster

/help
/triage accepted

**Comment by mrgiles** [comment]
This one looks like a candidate for a "good first issue" label. 

I think that the  https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/ page should also have the shell access note, regardless of the method used (ssh, rdp, etc).

@sftim @neolit123

**Comment by sftim** [comment]
I don't think this is a good first issue. A good first issue would have a description that helped totally new contributors find out how to help, and the description for this issue at the time of writing is:
> Missing important step new people
>
> SSH into the node

**Comment by mrgiles** [comment]
Got it. Going through the details, I see another problem here. The pre-req of having shell access to the nodes seems mostly relevant (a corner case) for the node upgrade task, for other cluster maintenance tasks, API access to node management seems enough. 

The problem is that the `upgrading-linux-nodes`, `upgrading-windows-nodes` and many other pages use the same prerequisites `include task-tutorial-prereqs.md` document (`includes/task-tutorial-prereqs.md`). So, adding the "get shell access to the nodes" phrase will alter all these documents where this step is not needed.

I think that, for this particular task, we should not use the include prerequisite doc and rewrite the paragraph locally on the `upgrading-linux|windows-nodes` pages, as a compromise between convenience and accuracy. What do you think?

**Comment by sftim** [comment]
> I think that, for this particular task, we should not use the include prerequisite doc and rewrite the paragraph locally on the `upgrading-linux|windows-nodes` pages, as a compromise between convenience and accuracy. What do you think?

That'll work fine.

**Comment by mrgiles** [comment]
Given the need to modify two documents and the potential for content drift across releases, etc, I decided to add a new prereqs include file with the modified paragraph instead of rewriting the whole prerequisites section on both documents. Let me know what you think. Thanks
