### ISSUE TITLE
Mermaid diagram not loading on 'Pod Topology Spread Constraints' page

### ISSUE THREAD

**Issue by Beheadedstraw** [kubernetes/website#45543]
As shown below, some of the example results do not render. Tested on Firefox ESR and Chrome.
![image](https://github.com/kubernetes/website/assets/5951719/38bf4abd-6480-45af-a373-f8a4fb0ef018)

**Comment by T-Lakshmi** [comment]
Page: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
/language en

**Comment by T-Lakshmi** [comment]
@Beheadedstraw,

> As shown below, some of the example results do not render. Tested on Firefox ESR and Chrome.

It looks like the problem is with your browser, i am able to view the page with no loss of information.

![topology-image1](https://github.com/kubernetes/website/assets/56723673/a51a3fca-5d70-4a70-86fa-378a7ae833f6)

![topology-image2](https://github.com/kubernetes/website/assets/56723673/9765afa5-0caa-43cd-9caa-205939da396c)

**Comment by dipesh-rawat** [comment]
/retitle Mermaid diagram not loading on 'Pod Topology Spread Constraints' page
/area web-development

**Comment by T-Lakshmi** [comment]
Seems Duplicate issue of #31960

**Comment by Beheadedstraw** [comment]
@T-Lakshmi if I refresh the page enough times it will show up, but the majority of the time it won't load with nothing in the console giving any syntax errors. Reading the above it seems like a Mermaid issue, possibly a race condition somewhere.

**Comment by Gauravpadam** [comment]
@Beheadedstraw thanks for reporting. You're correct and we are aware of the issue. we're working towards it in #31960.
/triage duplicate

**Comment by sftim** [comment]
/close not-planned

We've pinned the primary issue to the top of https://github.com/kubernetes/website/issues and would welcome help on it. Not much more we can do to make the primary issue visible.
