### ISSUE TITLE
Error when installing kubernetes cluster on redhat linux 9

### ISSUE THREAD

**Issue by sandeep8patil8** [kubernetes/website#45546]
I am trying to install kubernetes cluster on redhat linux 9 using command prompt. I have followed few steps and installed kubelet,kubeadm,kubectl. 
But when I try to run the command "kubeadm config images pull --cri-socket unix:///var/run/containerd/containerd.sock" then it is showing error as 'failed to pull image "registry.k8s.io/kube-apiserver:v1.29.2": output: time="2024-03-14T07:12:17Z" level=debug msg="get image connection"
time="2024-03-14T07:12:17Z" level=fatal msg="validate service connection: validate CRI v1 image API for endpoint \"unix://var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.ImageService"
, error: exit status 1'

Also I have observed that when I try to enable and start the kubelet service it is in state 'activating' and not starting. Also the config file /var/lib/kubelet/config.yaml is not present.

**Comment by thisisharrsh** [comment]
/kind support

It seems to be like a support request.

**Comment by thisisharrsh** [comment]
Hi @sandeep8patil8, as it seems like a support request you can post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by neolit123** [comment]
> Hi @sandeep8patil8, as it seems like a support request you can post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

yes, please use the support channels.

/close
