### ISSUE TITLE
Pod 安全性标准

### ISSUE THREAD

**Issue by ql3xHd630** [kubernetes/website#45555]
对于Seccomp的配置，文档中标注 (v1.19+)处表示
"如果 Pod 级别的 spec.securityContext.seccompProfile.type 已设置得当，容器级别的安全上下文字段可以为未定义/nil。 反之如果 所有的 容器级别的安全上下文字段已设置， 则 Pod 级别的字段可为 未定义/nil。"

而未标注版本的位置表示
设置 未定义/nil是允许的取值。那么如果使用1.28.3版本的k8s，是否可以设置SeccompProfile为未定义

**Comment by AmarNathChary** [comment]
Please explain the issue in English.

**Comment by tengqm** [comment]
Please submit an issue to the English upstream. The Chinese version is a faithful translation.
