### ISSUE TITLE
Enhance "Configure Service Accounts for Pods" page to cover ServiceAccount binding guidance for Deployments

### ISSUE THREAD

**Issue by giuliano-scassaioli** [kubernetes/website#45551]
Please add info on how to bind service accounts with Deployments and not just with Pods

**Comment by dipesh-rawat** [comment]
_Page mentioned in the issue (based on the issue title)_: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account
/language en

**Comment by dipesh-rawat** [comment]
/retitle Enhance "Configure Service Accounts for Pods" page to cover ServiceAccount binding guidance for Deployments
/kind feature
