### ISSUE TITLE
Incorrect usage of "Scale-Up" and "Scale-Down" in "Horizontal Pod Autoscaling" page

### ISSUE THREAD

**Issue by xkiranj** [kubernetes/website#45562]
In all the K8s documentation related to Horizontal Pod Autoscaling, the term "Scale-Up" and "Scale-Down" are being used incorrectly.
As we are talking about "Horizontal" scaling, the terms "Scale-Out" and "Scale-In" must be used.

"Scale-Up" and "Scale-Down" are relative to Vertical scaling and not Horizontal scaling.
So when one reads the documentation about Horizontol Pod Autoscaling, it creates confusion as to why "Scale-Up" and "Scale-Down" are being used.

This should be corrected!

**Comment by dipesh-rawat** [comment]
_Page mentioned in the issue (based on the issue title)_:  https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale
/language en

**Comment by dipesh-rawat** [comment]
/retitle Incorrect usage of "Scale-Up" and "Scale-Down" in "Horizontal Pod Autoscaling" page
/sig autoscaling

**Comment by sftim** [comment]
> In all the K8s documentation related to Horizontal Pod Autoscaling, the term "Scale-Up" and "Scale-Down" are being used incorrectly. As we are talking about "Horizontal" scaling, the terms "Scale-Out" and "Scale-In" must be used.

I don't think this is a settled debate. I know some firms always use “scale up” and “scale down”, whilst others use “scale out” and “scale in” for horizontal scaling. When you scale horizontally, you make a number (the replica count) bigger. That feels like ”up” to a lot of people, especially if they have a mathematical background.

The convention so far is to use only ”scale up” and “scale down”, regardless of the form of scaling. I think this convention is OK, even though some other projects and commercial context use words differently.

If we want to start a project-wide discussion about changing the convention, we could. I don't have an appetite for that myself.

**Comment by sftim** [comment]
/remove-sig autoscaling

It's a wider concern.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

We don't seem to have project conventions on whether to use "scale up" or "scale out" for horizontal scale increases to replica count.
Work to set those conventions is welcome.
