### ISSUE TITLE
Add guidance on volumeMounts naming for automatic resource sharing in "Sidecar Containers" documentation

### ISSUE THREAD

**Issue by giuliano-scassaioli** [kubernetes/website#45560]
Plese add here also that you must give the same name in the "volumeMounts name" section of both the sidecar and the main container for the automatic resource sharing to work. then finally we put the name also in the volumes section to mount it in the pod.

**Comment by tamilselvan1102** [comment]
related page: https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/

**Comment by tamilselvan1102** [comment]
It is one of the use case of sidecar container. So it is not required to mention specifically.

**Comment by dipesh-rawat** [comment]
/retitle Add guidance on volumeMounts naming for automatic resource sharing in "Sidecar Containers" documentation
