### ISSUE TITLE
Search text is not appearing

### ISSUE THREAD

**Issue by amanr-dev** [kubernetes/website#45587]
When the header is not scrolling, Search text does not appear.

## screenshots

Here I entered the text "Hello"
![Screenshot 2024-03-18 145405](https://github.com/kubernetes/website/assets/124811276/8c0eaba5-4737-42f9-8dc0-c0f6cfa05779)

and when scrolling, it appears
![Screenshot 2024-03-18 145542](https://github.com/kubernetes/website/assets/124811276/75715920-8dea-4265-b4b0-9b69704d95d3)

**Comment by sftim** [comment]
/area web-development
/kind bug
/priority important-longterm
/triage accepted

This comes from https://github.com/kubernetes/website/pull/44574
