### ISSUE TITLE
Move the introduction page from SIG CLI guides to the kubectl reference

### ISSUE THREAD

**Issue by sreeram-venkitesh** [kubernetes/website#45600]
**This is a Feature Request**

**What would you like to be added**

Move the `Introduction` page from the [SIG CLI guides](https://kubectl.docs.kubernetes.io/guides) to the [upstream kubectl reference](https://kubernetes.io/docs/reference/kubectl)

**Why is this needed**

Multiple versions of the kubectl documentation exists which can be merged into the kubectl reference section in the Kubernetes upstream website. Part of https://github.com/kubernetes/website/issues/25943

**Comments**

/good-first-issue
/language-en
/help-wanted

**Comment by sftim** [comment]
The source code to move is inside https://github.com/kubernetes-sigs/cli-experimental/tree/master/site/content

**Comment by prashantrewar** [comment]
Hey @sftim and @sreeram-venkitesh, I created a PR for this issue. Please take a look.

**Comment by sftim** [comment]
@sreeram-venkitesh would you be willing to file some similar issues? I would mark them with

/help

but not with /good-first-issue

**Comment by sreeram-venkitesh** [comment]
@sftim Yes, I'll create the rest of the issues today.
