### ISSUE TITLE
Typo in auto-generated  "kubeadm Configuration (v1beta4)" reference page

### ISSUE THREAD

**Issue by msrajanadar** [kubernetes/website#45602]
found typo "ontrolPlaneEndpoint" in the below 
<img width="862" alt="typo ontrolPlaneEndpoint" src="https://github.com/kubernetes/website/assets/8028491/bb827338-c904-4325-96c0-2d15652d0324">

There is a typo "ontrolPlaneEndpoint" in the localAPIEndpoint description it should be "controlPlaneEndpoint"
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/#kubeadm-k8s-io-v1beta4-InitConfiguration

**Comment by dipesh-rawat** [comment]
Page related to issue: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4
/language en

**Comment by dipesh-rawat** [comment]
/retitle Typo in auto-generated  "kubeadm Configuration (v1beta4)" reference page

**Comment by dipesh-rawat** [comment]
The mentioned reference page for "kubeadm Configuration (v1beta4)" is [automatically generated](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4///#auto-generated-edit-notice). The page is generated from the upstream source code [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes).

As the page is generated from the upstream source code, any fixes would need to be addressed there. For those interested in contributing to resolve this issue, please refer to the upstream contribution guidelines outlined at: https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream

**Comment by neolit123** [comment]
this is not a typo in the code files
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go#L51
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go#L47

and also in my browser it's shown as controlPlaneEndpoint, so maybe it's a rendering issue.

![Screenshot 2024-03-25 125359](https://github.com/kubernetes/website/assets/331852/77c3d143-de04-4127-a3a9-01cd7373ec94)


cc @tengqm

**Comment by neolit123** [comment]
> ![Screenshot 2024-03-25 125359](https://private-user-images.githubusercontent.com/331852/316476179-77c3d143-de04-4127-a3a9-01cd7373ec94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjQ0NTksIm5iZiI6MTcxMTM2NDE1OSwicGF0aCI6Ii8zMzE4NTIvMzE2NDc2MTc5LTc3YzNkMTQzLWRlMDQtNDEyNy1hM2E5LTAxY2Q3MzczZWM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMDU1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTFkMDBmODQxZTgyNjRjMGVhZTgwYjJlZjI4MmNhOTBjMjIzNjZlNjNjZjZiY2ZhYWRkNWJhZjYwZTk3NThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8BvaQq5lFuXXaogH84bGD-JsbGECgZCQxNQzTi26r-0)
> 

the image is for v1beta3, but v1beta4 does have the problem as the OP shows.

**Comment by a-mccarthy** [comment]
the `c` in `controlPlaneEndpoint` is also dropped in another place on that page, screenshot below. I'm not familiar with the autogeneration for these pages, is there some processing on the word that is dropping letters when converting from the original? Looks like in the source file its written with a capital and in the generated file its with a lower case. Not sure why it would only so it sometimes though. 

We should check to see if this is happening on other pages. 

/priority awaiting-more-evidence

<img width="789" alt="Screenshot 2024-03-27 at 9 44 26 AM" src="https://github.com/kubernetes/website/assets/20771501/97a8aaaf-5799-4f19-b11a-362024b59497">

**Comment by stmcginnis** [comment]
Another interesting observation looking at the [Code Search instances of this](https://cs.kubernetes.io/?q=sets%20a%20stable%20IP%20address%20or%20DNS%20name&i=nope&files=&excludeFiles=&repos=) - it appears to only happen on the v1beta4 version of the docs, not the previous versions.

Looks like it was modified with 74516499205.

**Comment by stmcginnis** [comment]
Put up a fix in #45709. It looks like this wasn't from an autogeneration error and just a simple typo when the docs were updated for v1beta4.
