### ISSUE TITLE
Improvement for k8s.io/de/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by mkuster** [kubernetes/website#45641]
Please adjust the ubuntu install instructions with the update from https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/
(New package repository)

**Comment by sftim** [comment]
/language de

We should ensure that the German page aligns with the [English original](https://kubernetes.io/docs/tasks/tools/#kubectl)

**Comment by stmcginnis** [comment]
English language change for reference for anyone wanting to pick up the change for other languages:

https://github.com/kubernetes/website/commit/c206802a2e8f40fdc26e97972137c23eb6b8a3f5

Looks like we need:

- [ ] **DE**
- [ ] **ES**
- [ ] **FR**
- [ ] **HI**
- [ ] **JA**
- [ ] **KO**
- [ ] **PT-BR**
- [ ] **VI**
