### ISSUE TITLE
Make this documentation available in air gapped environment

### ISSUE THREAD

**Issue by tomerle03** [kubernetes/website#45654]
When I tried to run this in air gapped environment it didn't work and I think because the Hugo server tried to pull fonts from google api. Is there any solution for an environment completely disconnected from the internet?

**Comment by tamilselvan1102** [comment]
I think in the first run it is required internet connectivity to run Hugo because it required some supporting files to run and it will get downloaded from correspond repo

**Comment by sftim** [comment]
You can download this documentation as a PDF, or build a copy outside your air gapped environment and then serve it as static content from inside the air gapped environment (there will not be a search function).

/kind support

We don't document how to run an air gapped environment. However, you could look for commercial advice about how to set that up.

**Comment by sftim** [comment]
(SIG Docs tech lead here)

We might accept a PR to improve things here, but we wouldn't accept the feature request. Our priority and our core purpose is to publish the documentation for the [`k/website`](https://github.com/kubernetes/website/) repository, via the World Wide Web: https://k8s.io/docs/

**Comment by sftim** [comment]
/close

The documentation can be available in an air gapped environment; we/ I have yet to see evidence otherwise.
