### ISSUE TITLE
Discrepancy in End of Life date for v1.26 in "Patch Releases" page

### ISSUE THREAD

**Issue by dipesh-rawat** [kubernetes/website#45669]
**This is a Bug Report**

**Problem:**
In the "Detailed Release History for Active Branches" section ([here](https://kubernetes.io/releases/patch-releases/#1-26)), there's a discrepancy regarding the End of Life date for version **1.26**. Currently, the doc states:

> 1.26 enters maintenance mode on 2023-12-28 and End of Life is on 2024-02-28.

 However, this information appears to be inaccurate considering that [v1.26.15](https://github.com/kubernetes/kubernetes/releases/tag/v1.26.15) has recently been released ([(announcement link](https://groups.google.com/a/kubernetes.io/g/dev/c/6e6YjTj4klM)).
 
**Proposed Solution:**
 Confirm and update the accurate End-of-Life dates for version 1.26

**Page to Update:**
https://kubernetes.io/releases/patch-releases/

**Additional Information:**
/language en
/sig release
/area release-eng

**Comment by a-mccarthy** [comment]
@sftim is there a reason why we couldn't use the `note` option that is already there to give more context about why an additional release was created? I'm not sure how the https://github.com/kubernetes/website/blob/main/data/releases/schedule.yaml is created/maintained so maybe i'm missing some context

Either way, i think its worth making sure we list all the available releases.

triage/accepted
priority/important-longterm

**Comment by sftim** [comment]
We **can** use the notes, I forgot that we have them.

**Comment by a-mccarthy** [comment]
/triage accepted

re-adding doing the labels

**Comment by dipesh-rawat** [comment]
It appears that the issue has been resolved through PR https://github.com/kubernetes/website/pull/45843. We can mark this as resolved and close the issue.

/close
