### ISSUE TITLE
Kubelet Configuration (v1)

### ISSUE THREAD

**Issue by srpomeroy** [kubernetes/website#45667]
Is this the right page data? Looks like its for the Credential Provider.
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/config-api/kubelet-config.v1.md

**Comment by T-Lakshmi** [comment]
@srpomeroy,

> Is this the right page data? Looks like its for the Credential Provider.

What kind of data you are looking for?
if you are looking for kubernetes official documentation, it's available on https://kubernetes.io/docs/home/

**Comment by T-Lakshmi** [comment]
> https://github.com/kubernetes/website/blob/main/content/en/docs/reference/config-api/kubelet-config.v1.md

This is Kubernetes website code preview page which is maintaining by github.
you can find the end user documentation under [Kubernetes](https://kubernetes.io/) official website [here](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/).

**Comment by T-Lakshmi** [comment]
oops!
/language en

**Comment by srpomeroy** [comment]
I was looking for information on the kubelet configuration. Specifically, `spec.providerid`, which I found in the v1beta1 version [here](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/config-api/kubelet-config.v1beta1.md).

I was looking for the v1 version which brought me to the page I linked in the OP. But that page talks only about the credential provider. Is [KubeletConfiguration](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/config-api/kubelet-config.v1beta1.md#kubeletconfiguration-----kubelet-config-k8s-io-v1beta1-kubeletconfiguration) not v1 yet?

**Comment by tengqm** [comment]
> Is [KubeletConfiguration](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/config-api/kubelet-config.v1beta1.md#kubeletconfiguration-----kubelet-config-k8s-io-v1beta1-kubeletconfiguration) not v1 yet?

Right. It is still v1beta1.
