### ISSUE TITLE
Want to create a Docker image of an existing EKS pod or any pod.

### ISSUE THREAD

**Issue by naren2631** [kubernetes/website#45679]
I want to create a Pod backup in form of a docker image. Is it possible to create?

**Comment by a-mccarthy** [comment]
Hey @naren2631, this sounds more like a request for support and less like an issue specifically for docs. I encourage you to bring your question to the `#kubernetes-users` channel in [Kubernetes slack](https://slack.k8s.io/) as this repo is specifically for docs related issues. 

If this is a documentation issue, please re-open this issue and provide some more details on the docs improvement you like to see. thanks!

/close
