### ISSUE TITLE
Move non-graceful node shutdown section from concepts/architecture/nodes.md to concepts/cluster-administration

### ISSUE THREAD

**Issue by reylejano** [kubernetes/website#45690]
Since concepts/architecture/nodes.md is a page better suited for those learning Kubernetes, the [non-graceful node shutdown section](https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown), [graceful node shutdown section](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown) and forced storage detach on timeout section is better suited to be on the [concepts/cluster-administration page](https://kubernetes.io/docs/concepts/cluster-administration/)
See comment thread: https://github.com/kubernetes/website/pull/45119/files#r1537466016

**Comment by a-mccarthy** [comment]
@reylejano do you feel like there is any restructuring of content that needs to happen with this move? Or is it a request to straight move those sections from one page to another?

**Comment by sftim** [comment]
/triage accepted

I think a straightforward move is the right change to prioritize. Extra help is welcome but not at the expense of delivering the fix later.

**Comment by sftim** [comment]
/priority important-longterm

see https://github.com/kubernetes/website/pull/45119/files#r1537466016

**Comment by mrgiles** [comment]
@reylejano see if this PR does what you're looking for. Thanks
