### ISSUE TITLE
[es] localize concepts/workloads/pods/user-namespaces.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#45706]
**This is a Feature Request**

**What would you like to be added**
Localize `concepts/workloads/pods/user-namespaces.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

The Spanish translation team would like to facilitate your contribution journey; for any doubt, please participate in the weekly meetings or post a question in the Kubernetes slack channel [#kubernetes-docs-es](https://kubernetes.slack.com/archives/CH7GB2E3B)

We also encourage new contributors to participate in their native speaking language.

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by ramrodo** [comment]
Hi @SerDigital, doing a follow-up on this issue, do you have any update for this?

Let us know if we can help :)

**Comment by krol3** [comment]
close in favor of https://github.com/kubernetes/website/issues/48071
/close
