### ISSUE TITLE
[es] localize concepts/workloads/pods/pod-lifecycle.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#45708]
**This is a Feature Request**

**What would you like to be added**
Localize `concepts/workloads/pods/pod-lifecycle.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

The Spanish translation team would like to facilitate your contribution journey; for any doubt, please participate in the weekly meetings or post a question in the Kubernetes slack channel [#kubernetes-docs-es](https://kubernetes.slack.com/archives/CH7GB2E3B)

We also encourage new contributors to participate in their native speaking language.

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by anyulled** [comment]
Could please assign this to me?

**Comment by ramrodo** [comment]
Sure! Thanks.

/assign @anyulled

**Comment by tengqm** [comment]
Would you guys file an umbrella issue for tasks like this? We have many pages to be translated for some localizations. Filing issues on a per-file basis may overwhelm the number of issues we have on the project. You can file a few umbrella issues, each one has some tasks that can be tracked under the same issue. It will be much easier for work item sign-on, coordination and progress tracking.

**Comment by electrocucaracha** [comment]
> Would you guys file an umbrella issue for tasks like this? We have many pages to be translated for some localizations. Filing issues on a per-file basis may overwhelm the number of issues we have on the project. You can file a few umbrella issues, each one has some tasks that can be tracked under the same issue. It will be much easier for work item sign-on, coordination and progress tracking.

@tengqm we had used that [approach](https://github.com/kubernetes/website/issues/13948) before, but we faced some bottlenecks on the process, depending on the author to make changes and keep the umbrella issue updated. So, we decided to use a [GitHub dashboard](https://github.com/orgs/kubernetes/projects/97/views/1) , this approach gave us better visibility and control over the work, resulting in  automony during on-boarding process and helped us to measure better our progress.

**Comment by ramrodo** [comment]
Hi @anyulled, do you have updates related to this issue?

Let us know if we can help :)

**Comment by anyulled** [comment]
> Hi @anyulled, do you have updates related to this issue?
> 
> Let us know if we can help :)

sure, give me a few days, I'm on vacations

**Comment by ramrodo** [comment]
localized by https://github.com/kubernetes/website/pull/47204
