### ISSUE TITLE
[es] localize concepts/workloads/pods/downward-api.md to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#45707]
**This is a Feature Request**

**What would you like to be added**
Localize `concepts/workloads/pods/downward-api.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

The Spanish translation team would like to facilitate your contribution journey; for any doubt, please participate in the weekly meetings or post a question in the Kubernetes slack channel [#kubernetes-docs-es](https://kubernetes.slack.com/archives/CH7GB2E3B)

We also encourage new contributors to participate in their native speaking language.

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by ramrodo** [comment]
Hi @immavalls doing a kind follow-up. Do you have an update about this contribution? Do you have questions or need help?

**Comment by immavalls** [comment]
Apologies @ramrodo I have been out sick the past month, I hope to resume work on this soon. If it is urgent we could assign someone else.

**Comment by ramrodo** [comment]
@immavalls It is not urgent. Take your time :)

We just wanted to update the status of our [Tracking Board](https://github.com/orgs/kubernetes/projects/97/views/1). Thanks for your help.

**Comment by ramrodo** [comment]
Hi @immavalls, I hope you are well :)

I am just doing a kind follow-up on this issue, do you have some progress on this task?

**Comment by krol3** [comment]
close in favor of https://github.com/kubernetes/website/issues/48071
/close
