### ISSUE TITLE
[es] Translate - `docs/concepts/architecture/nodes` into Spanish

### ISSUE THREAD

**Issue by krol3** [kubernetes/website#45700]
**This is a Feature Request**
Translate this page [docs/concepts/architecture/nodes](https://kubernetes.io/docs/concepts/architecture/nodes) into Spanish.

**What would you like to be added**
The translation will be added to `content/es/`docs/concepts/architecture/nodes

**Why is this needed**
There is no Spanish translation for this file. It would be great if we could read this in Spanish.

**Comments**
The Spanish translation team would like to facilitate your contribution's journey,  any doubt participate in the weekly meetings in the kubernetes slack channel `kubernetes-docs-es`

We also encourage new contributors to participate in their native speaking language 💥.

/triage accepted
/kind feature
/language es
/sig docs

**Comment by krol3** [comment]
Gracias @parraletz  cualquier duda nos encuentras en el canal [kubernetes-doc-es](https://kubernetes.slack.com/archives/CH7GB2E3B)

**Comment by ramrodo** [comment]
Hola @parraletz, ¿tienes alguna actualización sobre este issue?

**Comment by krol3** [comment]
Close in behave the another issue https://github.com/kubernetes/website/issues/45699
