### ISSUE TITLE
Kubernetes documentation still points to legacy package repo

### ISSUE THREAD

**Issue by Tanushriyt** [kubernetes/website#45717]
hello,

i'm getting these errors after running
```
sudo apt -y install curl apt-transport-https
curl  -fsSL  https://packages.cloud.google.com/apt/doc/apt-key.gpg|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/kubernetes.gpg
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
```
 when i  run sudo apt-get update i'm getting these errors

```
 Err:2 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 142.250.71.46 443]
Reading package lists... Done
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Any help?

**Comment by utkarsh-singh1** [comment]
Seems like the apt repository to install certain k8s packages is not available anymore.

**Comment by utkarsh-singh1** [comment]
Are you installing kubeadm currently?

**Comment by stmcginnis** [comment]
Can you share which page of the documentation you are following that led to this?

It looks like you are using the old apt repo that is no longer available. https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/

We must still have a page that references the old information.

/retitle Kubernetes documentation still points to legacy package repo
/kind support
/remove triage

**Comment by sftim** [comment]
/triage needs-information
/remove-kind support

We want to know which page still needs updating.

**Comment by klausmeyer** [comment]
One example would be the German translation which is still using `apt.kubernetes.io`:

https://kubernetes.io/de/docs/tasks/tools/install-kubectl-linux/#installieren-mit-hilfe-des-linux-eigenen-paketmanagers

**Comment by feorlen** [comment]
I saw this same error following the instructions here:
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management

**Comment by Yaren-IT** [comment]
- https://kubernetes.io/de/docs/tasks/tools/install-kubectl/#installieren-der-kubectl-anwendung-mithilfe-der-systemeigenen-paketverwaltung
- https://kubernetes.io/fr/docs/tasks/tools/install-kubectl/#installation-%C3%A0-l-aide-des-gestionnaires-des-paquets-natifs
- https://kubernetes.io/id/docs/tasks/tools/install-kubectl/#menginstal-dengan-manajer-paket-package-manager-bawaan
- https://kubernetes.io/vi/docs/tasks/tools/install-kubectl/#c%C3%A0i-%C4%91%E1%BA%B7t-kubectl-s%E1%BB%AD-d%E1%BB%A5ng-tr%C3%ACnh-qu%E1%BA%A3n-l%C3%BD-g%C3%B3i
- https://kubernetes.io/ru/docs/tasks/tools/install-kubectl/#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-%D0%B2%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%B0
-

**Comment by utkarsh-singh1** [comment]
> * https://kubernetes.io/de/docs/tasks/tools/install-kubectl/#installieren-der-kubectl-anwendung-mithilfe-der-systemeigenen-paketverwaltung
> * https://kubernetes.io/fr/docs/tasks/tools/install-kubectl/#installation-%C3%A0-l-aide-des-gestionnaires-des-paquets-natifs
> * https://kubernetes.io/id/docs/tasks/tools/install-kubectl/#menginstal-dengan-manajer-paket-package-manager-bawaan
> * https://kubernetes.io/vi/docs/tasks/tools/install-kubectl/#c%C3%A0i-%C4%91%E1%BA%B7t-kubectl-s%E1%BB%AD-d%E1%BB%A5ng-tr%C3%ACnh-qu%E1%BA%A3n-l%C3%BD-g%C3%B3i
> * https://kubernetes.io/ru/docs/tasks/tools/install-kubectl/#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-%D0%B2%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80%D0%B0

These links seem to be of different langauges.

**Comment by utkarsh-singh1** [comment]
> I saw this same error following the instructions here: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management

The given command is running fine.

**Comment by utkarsh-singh1** [comment]
@feorlen, can you confirm is the issue still there or it is resolved.

**Comment by utkarsh-singh1** [comment]
@feorlen, @Tanushriyt if problem still persists you can mention it, else it would be better to close this issue.

**Comment by sftim** [comment]
I don't see anything to fix. @Tanushriyt please reopen the issue if there is a page in the current docs that is wrong.

/close not-planned
