### ISSUE TITLE
Example correction in the documentation: "kubectl auth can-i ... --as ..."

### ISSUE THREAD

**Issue by czavieh** [kubernetes/website#45728]
documentation at this URL
https://kubernetes.io/docs/reference/kubectl/generated/kubectl_auth/kubectl_auth_can-i/#examples

The following example need to be corrected 
from: 
`kubectl auth can-i list pods --as=system:serviceaccount:dev:foo -n prod`
to:
`kubectl auth can-i list pods --as="system:serviceaccount:dev:foo" -n prod`
or
`kubectl auth can-i list pods --as system:serviceaccount:dev:foo -n prod`

**Comment by stmcginnis** [comment]
The existing format should work the same as the alternates. Can you share what problem you are seeing with it?

**Comment by dipesh-rawat** [comment]
/triage needs-information

@czavieh Would be able to share the information requested in https://github.com/kubernetes/website/issues/45728#issuecomment-2027969189

**Comment by czavieh** [comment]
I tried to use the format as suggested in the documentation, `--as=system:serviceaccount:dev:foo`  cli didn't accept it. However when I put the full SA name in the double quotation marks, cli accepted:
`--as="system:serviceaccount:dev:foo"`
I didn't have any issue with this format(not using =) : `--as system:serviceaccount:dev:foo`

So I am confused too. This happened the day I reported. I delete that environment and don't have access to it to take screenshot. I don't have any explanation and if I am the only person who has ever reported this, we can close the ticket and next time I encounter this issue, I will try to document it well and then report it. Thank you for prompt response.

**Comment by niranjandarshann** [comment]
@czavieh The command is working perfectly the same as given in the doc and the suggested one. --as=system:serviceaccount:dev:foo  is not an intentional behaviour you can use either of the command in some case the command in "" will be treated as single argument which is correct and intended behaviour.

So both the command are working fine  and are correct.
