### ISSUE TITLE
Unknown Field Error in Job and Deployment spec in SidecarContainer-Pod Document.

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#45738]
**This is a Bug Report**

**Problem:**
Error occurred upon creating new Kubernetes Objects ⇾ Deployment and Jobs.

1 -
```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/deployment-sidecar.yaml
```

```log
Error from server (BadRequest): error when creating "sidecar-job.yaml": Job in version "v1" cannot be handled as a Job: strict decoding error: unknown field "spec.template.spec.initContainers[0].restartPolicy"
```

2 - 

```bash
kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/job/job-sidecar.yaml
```
```log
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/job/job-sidecar.yaml": Job in version "v1" cannot be handled as a Job: strict decoding error: unknown field "spec.template.spec.initContainers[0].restartPolicy"
```

**Proposed Solution:**
Remove the Restart Policy field under PodSpec InitContainer.

**Page to Update:**
https://kubernetes.io/...

**Comment by utkarsh-singh1** [comment]
Page to Update - https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-containers-and-pod-lifecycle

**Comment by utkarsh-singh1** [comment]
Also there is no field restartPolicy in initContainer fields ->

```bash
kubectl explain pods.spec.initContainers
```

**Comment by dipesh-rawat** [comment]
This feature, introduced as _alpha_ in version 1.28 [(blog here)](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) and enabled by default in _beta_ in the current Kubernetes v1.29, involves a feature gate called `SidecarContainers`.  The feature gate `SidecarContainers` provides the ability to specify a `restartPolicy` for containers listed in a Pod's `initContainers` field [(reference here)](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#enabling-sidecar-containers).

What Kubernetes version are you currently utilizing? 
/triage needs-information

**Comment by utkarsh-singh1** [comment]
\Yeah, seems like I am currently using old k8s version I am running - 1.27.3

/close
