### ISSUE TITLE
Troubleshooting kubeadm

### ISSUE THREAD

**Issue by rajat8528** [kubernetes/website#45748]
22219 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0401 16:47:34.292876   22219 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0401 16:47:34.294260   22219 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0401 16:47:34.294626   22219 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0401 16:47:34.296220   22219 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?

How do i get past this error, i have configured everything?

**Comment by neolit123** [comment]
/kind support
/close

please try asking on the support channels instead of github
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
