### ISSUE TITLE
Lack of deep links to navigate to specific sections in auto-generated "kubeadm Configuration (v1beta3)" reference page

### ISSUE THREAD

**Issue by mvtab** [kubernetes/website#45745]
#### Issue short version
When visiting [this](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/) automatically generated page, the headers "Overview", "Basics", "Kubeadm init configuration types", "Kubeadm join configuration types" and "Feedback" have no dedicated HTML tags and respective links. 
#### Expected result
A deep link symbol with a tag reference, e.g. [base-url](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3)/#resource-types
![image](https://github.com/kubernetes/website/assets/98095405/2bc464d8-67c4-49d0-9aed-c6f434042108)
#### Actual result
No deep link and no tag reference.
![image](https://github.com/kubernetes/website/assets/98095405/b280f731-300f-42ff-8449-6aa7d83a5f2b)
#### More information
I tried manually using the tag #basics and it is not implemented, when opening such a link the scroll gets fixed at page start.  
I am not sure if this is by design or a flaw.

**Comment by dipesh-rawat** [comment]
Page reported in issue **_(its an auto-generated page)_**:  https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

**Comment by dipesh-rawat** [comment]
/retitle Lack of deep links to navigate to specific sections in auto-generated "kubeadm Configuration (v1beta3)" reference page
/area web-development

**Comment by sftim** [comment]
/kind feature

Our API generator for this page doesn't produce the kind of Markdown that Hugo can process to automatically add fragment identifiers.

To make the improvement, change the code within https://github.com/kubernetes-sigs/reference-docs/

**Comment by sftim** [comment]
> I am not sure if this is by design or a flaw.

Neither, really. It's more something we haven't got round to coding, and this is the first request to add it.
