### ISSUE TITLE
Improvement for k8s.io/docs/setup/

### ISSUE THREAD

**Issue by edenbarth** [kubernetes/website#45754]
How do I connect to an already available cluster?

**Comment by stmcginnis** [comment]
/kind support

How you access the cluster depends on the type of cluster and how it was set up.

If you are using kind or minikube, I believe both of them configure your default kubeconfig context. They also have respective commands to retrieve a kubeconfig after the fact.

If you are using EKS, AKS, GKE, etc., those typically have a web console you could use, or provide a link for downloading a kubeconfig file.

If you've set up the cluster using kubeadm, you can copy the admin kubeconfig from `/etc/kubelet/admin.conf`.

You can find some details in the [kubectl docs](https://kubernetes.io/docs/reference/kubectl/) or the [kubeconfig docs](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/).

If you need help using kubernetes, you are more likely to get faster help in the #kubernetes-users channel in the Kubernetes Slack.

**Comment by edenbarth** [comment]
To be honest, this is all very confusing for a beginner like me.
In the docutmentation here it is says here [(https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/)](url) that there is a step-by-step instruction:

> For step-by-step instructions on creating and specifying kubeconfig files, see [Configure Access to Multiple Clusters](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters)

And in the linked article [https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/](url) it says: 
> Before you begin
You need to have a Kubernetes cluster, and the kubectl command-line tool must be configured to communicate with your cluster.

So where do i start now, if I need to write a config file myself? Is there something like a basic template for kubectl config files?
