### ISSUE TITLE
Create static Pods

### ISSUE THREAD

**Issue by tiwaprat** [kubernetes/website#45758]
kubelet disregards file extensions (such as .yaml), which means that any file syntactically correct in the static pod location will be attempted to be created as a pod by kubelet.

For example if I have two files  at static pod path location 

kube-apiserver.yaml-bak
kube-apiserver.yaml

here kubelet will try to create pods for both files. kubelet will not ignore  "kube-apiserver.yaml-bak"  file.  
Note:  Never keep extra files  at static pod path location.

**Comment by kushalShukla-web** [comment]
its sounds like its an technical issue rather than , issue in website .

**Comment by kushalShukla-web** [comment]
is this issue regarding any document change ?

**Comment by tiwaprat** [comment]
> is this issue regarding any document change ?

This is not related to document change. This is something i have noticed . At /etc/kubernetes/manifest  (StaticPodPathLoaction) I had to make small changes in kube-apiserver.yaml  file so  i took a backup first with name kube-apiserver.yaml-bak  .First  kubelet has created a pod with kube-apiserver.yaml-bak configuration and because of that kubelet  could not create pod with kube-apserver.yaml file , which was my desired configuration.
