### ISSUE TITLE
Improve "Server-Side Apply" page to address JSON/YAML compatibility with go-yaml

### ISSUE THREAD

**Issue by NuclearDog** [kubernetes/website#45751]
Hello there!

In the [section on serialization](https://kubernetes.io/docs/reference/using-api/server-side-apply/#serialization), the statement is made that:

> All JSON documents are valid YAML.

While this is correct, it's misleading in context because go-yaml has an [open issue](https://github.com/go-yaml/yaml/issues/797) regarding compatibility with the spec. While I understand this is particularly nitpicky, I think it's worth documenting this case because:

1. The issue was raised more than two years ago.
2. There are [multiple](https://github.com/go-yaml/yaml/pull/862) open [PRs](https://github.com/go-yaml/yaml/pull/884) that have been pending to resolve this for years.
3. There are major languages and libraries where the default options generate valid JSON/YAML that run into this case (e.g., PHP).

The escape sequence `\/` is explicitly listed in [RFC8259](https://datatracker.ietf.org/doc/html/rfc8259), near the top of page 9, as being an allowed escape sequence.

I'd argue that this section should either:

* Explicitly call out the incompatibility; or
* Soften the language to some thing like "Most JSON documents are accepted as YAML by Kubernetes."

At least in softening the language, people may be encouraged to explore the possibility that it's not _their_ code that's broken, but instead an issue with the YAML that kubernetes accepts and attempt to find workarounds instead of spending an embarrassing amount of time looking in the wrong place like I just did.

Thank you for your time!

Adam

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/reference/using-api/server-side-apply
/language en

**Comment by dipesh-rawat** [comment]
/retitle Improve "Server-Side Apply" page to address JSON/YAML compatibility with go-yaml

**Comment by sftim** [comment]
/kind feature

We can document the bug in Kubernetes. I'd prefer to make it clear that it's a bug, rather than document the bug as our expected behavior.
