### ISSUE TITLE
The first object In Kubernetes "deployment"

### ISSUE THREAD

**Issue by warmbasket** [kubernetes/website#45766]
The first Kubernetes object is the cluster, right? The deployment takes place on our cluster, so shouldnt the first step be defining our kubernetes cluster object? Rather than our deployment object? This deployment yaml seems to only provide an example of multiple deployments within a single machine? How would you create your cluster with multiple computers, each computer with their own gpu's, and then create your deployment yaml with deployments across all the computers? Does specifying the number of replicas automatically deploy across our machines, or do we not have to specify which nodes/computers to use? Would each computer have to be its own node/pod? Can there be a single node/pod containing all the computers and their gpu's?

https://kubernetes.io/docs/concepts/overview/working-with-objects/

**Comment by jihoon-seo** [comment]
Quoting [this comment](https://github.com/kubernetes/website/issues/45748#issuecomment-2030179124):

> please try asking on the support channels instead of github
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support

**Comment by akrupien** [comment]
The point is to get the questions answered by the publishers. Please address the unclear "documentation" that's published on the webpage. 

I shouldn't have to go to the community struggle room for answers to these questions, they should be documented. 

The support channels are Slack, Stack, Forum...and Their Documentation? 

Those aren't support channels? Please correct me if I'm wrong? The kubernetes support channel would be here if we have an issue?

It says "open an issue if you have a problem"

**Comment by utkarsh-singh1** [comment]
> The point is to get the questions answered by the publishers. Please address the unclear "documentation" that's published on the webpage.
> 
> I shouldn't have to go to the community struggle room for answers to these questions, they should be documented.
> 
> The support channels are Slack, Stack, Forum...and Their Documentation?
> 
> Those aren't support channels? Please correct me if I'm wrong? The kubernetes support channel would be here if we have an issue?
> 
> It says "open an issue if you have a problem"

Hi @warmbasket, the issue that can be raised in website repo are related to any issue in documentation , enhancement with new features for the website ,else are raised at support channels like kubernetes discuss or serverfault.

**Comment by utkarsh-singh1** [comment]
> The first Kubernetes object is the cluster, right? The deployment takes place on our cluster, so shouldnt the first step be defining our kubernetes cluster object?

No cluster is not an k8s object, It is a group of nodes that run containerized apps in an efficient, automated, distributed, and scalable manner.

And kubernetes objects can define as the blueprint of the desired state of application. Objects gives instruction to kubernetes how it should setup and manage applications.

**Comment by utkarsh-singh1** [comment]
> How would you create your cluster with multiple computers, each computer with their own gpu's, and then create your deployment yaml with deployments across all the computers?

Well here is the link to setup a kubernetes cluster -> https://kubernetes.io/docs/setup/

**Comment by utkarsh-singh1** [comment]
- For creating a local environment for learning or testing purpose you can use -> minikube
- For creating a production like k8s cluster -> kubeadm
- Or you can setup manually your k8s cluster on bare metal by downloading [k8s components](https://kubernetes.io/docs/concepts/overview/components/) from [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) repository.

**Comment by utkarsh-singh1** [comment]
> Does specifying the number of replicas automatically deploy across our machines

Yes if you mention number of replicas of application in Deployment spec file , it will deploy desired number of replicas.

> or do we not have to specify which nodes/computers to use? 

You can mention which node to use for the replicas deployment, or By default kubernetes scheduler will assign pods to nodes.

**Comment by sftim** [comment]
> The point is to get the questions answered by the publishers. Please address the unclear "documentation" that's published on the webpage.

If you're saying that the Deployment concept needs an update, we're [tracking](https://github.com/kubernetes/website/issues/12082) that request already. No need to file a duplicate request.

However, if you're suggesting that https://kubernetes.io/docs/concepts/overview/working-with-objects/ is hard to understand, you should file an actionable issue: one where a contributor can understand how to work on a fix.

> I shouldn't have to go to the community struggle room for answers to these questions, they should be documented.

That depends on the questions, but it's true that we aim for the documentation to make sense to readers.

/priority awaiting-more-evidence
/triage needs-information

If this is not a request for advice, we'd like to know more about what isn't right about the page, in a way that lets someone come along and work out how to make improvements.

**Comment by sftim** [comment]
GitHub is, however, _not_ the place to ask for advice on how to learn Kubernetes - which is what I'm seeing here

/kind support
/remove-triage needs-information

We're open to making the documentation better, but: we've already got **over 500 issues** tracked about doing that. Volunteers are working through those issues and proposing improvements; other volunteers help to plan them or to check them. The help we need most is improvements based on the work we've already planned.

**Comment by stmcginnis** [comment]
> > No cluster is not an k8s object, It is a group of nodes that run containerized apps in an efficient, automated, distributed, and scalable manner.
> 
> The Kubernetes Cluster is not a Kubernetes object? **Don't you create your cluster with Kubernetes?** Doesn't the basic cluster structure dictate what your deployment options are for setting up and managing applications?

You do not create your cluster with a cluster. Only if you are using something like [cluster API](https://cluster-api.sigs.k8s.io/introduction) to do your cluster provisioning. Otherwise a cluster is something that you have, which you then use to create deployments, pods, replicas, etc.

Sorry, I don't quite understand the last sentence there. I _think_ in general the answer is no, the underlying cluster structure does not dictate anything (for the most part) with how you define your deployment. The deployment defines what you want to have, then Kubernetes does its best to provide it without necessarily knowing anything about the underlying infrastructure.

> 
> > Well here is the link to setup a kubernetes cluster -> https://kubernetes.io/docs/setup/
> 
> Your link leads to other links that simply don't answer the question. Where does it describe how to add multiple machines as nodes to your cluster? The answer is here: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/ Why is it so buried? This is a basic functionality.

This varies, and for _users_ of kubernetes they usually don't need to care. You could set up your own cluster with kubeadm as you linked to. You could do it abstracted behind cluster API. You could do it with a few mouse clicks with EKS, AKS, GKE, etc. _How_ you get your cluster is a different concern than how you use that cluster, therefore it isn't included in this part since it would just muddle the information about usage. There are a lot of diverse ways to get a cluster instance.

> 
> > Yes if you mention number of replicas of application in Deployment spec file it will deploy desired number of replicas.
> 
> Within a single machine or across all machines in the cluster?
> 

That entirely depends on how many replicas you want, what resources are available in your cluster, taints and tolerations being used, and what scheduler is configured to decide where to place pods. Unfortunately this is an advanced topic that would have to many "it depends" statements to include in a getting started doc like this, but if you are curious you could search for each of those terms to find out more about those advanced concepts.

> > You can mention which node to use for the replicas deployment, Kubernetes scheduler will assign pod to nodes according to the mention instruction.
> 
> Can you assign a single pod to multiple nodes? I thought pods were within a single node? Do you mean kubernetes will assign replica pods to nodes?

Correct, a pod is an actual instance of one or more containers. An individual pod will get scheduled to only one node.

> 
> If I want one pod per worker/machine/computer/node that would mean I want one replica per worker/machine/computer/node? In the deployment yaml will the replicas/pods split across machines or only within a single node?
> 

Sort of an advanced concept again, but what your describing would probably be better met by using a DaemonSet or static pods. So again, something that you would have to look up as it would be outside the scope of something describing basic usage.

> > Node and Pod are 2 different entities, pods are schedule on Nodes.
> > 'Maybe you can read kubernetes basic concepts more to better have a better grasp."
> 
> Lmao, Trust me, I've read your basic concepts and know what a pod is. The point is your documentation is unclear and that's why these questions remain. Maybe you could read...my post? To have a better grasp?
> 

Lmao, this is an open source project, so **your** documentation can be updated to be more clear if there is an actionable issue to address with it. But a general "I don't understand this" issue doesn't really do much good.

Once you get a little further along in understanding Kubernetes basics, if there is something specific here that is missing or could be improved, please provide that detail. Or even better, please submit a PR to update the section with whatever information you find missing a lacking. Contributions are always welcome.

**Comment by warmbasket** [comment]
Hi, @stmcginnis, thank you for your prompt reply.

> You do not create your cluster with a cluster. Only if you are using something like [cluster API](https://cluster-api.sigs.k8s.io/introduction) to do your cluster provisioning. Otherwise a cluster is something that you have, which you then use to create deployments, pods, replicas, etc.

I asked if we create our cluster with kubernetes? Which I believe we do, in order to deploy with kubernetes? I did not ask if we create our cluster with a cluster. We create our cluster using Kubernetes to add our computers/machines as nodes, correct? Cluster API seems for handling multiple clusters? I am talking about creating one.

> Sorry, I don't quite understand the last sentence there. I _think_ in general the answer is no, the underlying cluster structure does not dictate anything (for the most part) with how you define your deployment. The deployment defines what you want to have, then Kubernetes does its best to provide it without necessarily knowing anything about the underlying infrastructure.

Okay, so the deployment defines the deployment of our pods right? It defines their deployment across the cluster? I'd imagine you'd need to specify the various nodes for deployment? If you only have one node then you wouldn't have to, because the replicas would just be inside a single computer/machine/node? This would be where I think the underlying cluster structure would affect how you define your deployment? How would it know to deploy to the other machines if you did not list them, how would it know to deploy which pods on which machines?

> This varies, and for _users_ of kubernetes they usually don't need to care. You could set up your own cluster with kubeadm as you linked to. You could do it abstracted behind cluster API. You could do it with a few mouse clicks with EKS, AKS, GKE, etc. _How_ you get your cluster is a different concern than how you use that cluster, therefore it isn't included in this part since it would just muddle the information about usage. There are a lot of diverse ways to get a cluster instance. 

It still needs to be a Kubernetes cluster instance, correct?

This varies is true, not everyone needs to build their Kubernetes cluster, many just use them, but you'd think building one would be a key piece of information for those that do have to build them? Or at least a standard of learning for everyone just using them? That way you can at least ensure people get to the usage phase? Does EKS, AKS, GKE, etc. allow you to add your own personal machines with just a few clicks? Not their virtual machines?

Kubeadm, behind cluster API, or EKS, AKS, GKE, etc. seems like the first step, and deployment on your cluster seems like the second. So again, I wonder why this is so buried and not immediately outlined in the documentation.

> That entirely depends on how many replicas you want, what resources are available in your cluster, taints and tolerations being used, and what scheduler is configured to decide where to place pods. Unfortunately this is an advanced topic that would have to many "it depends" statements to include in a getting started doc like this, but if you are curious you could search for each of those terms to find out more about those advanced concepts.
> > > You can mention which node to use for the replicas deployment, Kubernetes scheduler will assign pod to nodes according to the mention instruction.
> > Can you assign a single pod to multiple nodes? I thought pods were within a single node? Do you mean kubernetes will assign replica pods to nodes?
> Correct, a pod is an actual instance of one or more containers. An individual pod will get scheduled to only one node.
> > If I want one pod per worker/machine/computer/node that would mean I want one replica per worker/machine/computer/node? In the deployment yaml will the replicas/pods split across machines or only within a single node?
> Sort of an advanced concept again, but what your describing would probably be better met by using a DaemonSet or static pods. So again, something that you would have to look up as it would be outside the scope of something describing basic usage.

So, it sounds like it depends on the cluster structure because you'd have to indicate which node you're deploying your pods/replicas to? If you want one replica/pod per machine/node, as was mentioned, above, you can apparently mention which node to use for replicas deployment. My question is how? 

Excuse me if I'm incorrect but specifying the pods you want to run on your particular nodes in your cluster does not seem like an advanced topic, it seems like a basic functionality. It should not be hard to include this in the documentation. The current documentation does not include this. 

> This is an open source project, so **your** documentation can be updated to be more clear if there is an actionable issue to address with it. But a general "I don't understand this" issue doesn't really do much good.

Please understand @stmcginnis, this is not **my** documentation, or **your** documentation but rather **the** documentation. So **the** documentation can be updated to be clear and not omit information. It is most certainly not **my** documentation as I wouldn't have been willing to publish this incomplete mess, nor was I part of the team translating the Code to Documentation. (If I was I obviously wouldn't have any questions)

> Once you get a little further along in understanding Kubernetes basics, if there is something specific here that is missing or could be improved, please provide that detail. Or even better, please submit a PR to update the section with whatever information you find missing a lacking. Contributions are always welcome.

I have arrived at the precipice of Kubernetes capabilities, Kubernetes can only deploy a pod across a single node. 
And please correct me if I'm wrong, but I think at this point we'd agree I have an understanding of kubernetes basics. The specific thing that is missing from the deployment documentation is how to specify your various nodes for your pods deployment. 

Also, if you are constantly telling people to re-read lacking documentation they have already read as a way to "understand the basics" you must realize that what they're reading is not a good way to "understand the basics", and the documentation is faulty.

Thank you,

**Comment by sftim** [comment]
/close not-planned

Although improvements are welcome, this issue is not actionable.

We've not seriously considered suspending the project until you're happy with the documentation @warmbasket; I'm confident that the suspension you're proposing wouldn't be in the best interests of the wider community.
