### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/ingress-minikube/

### ISSUE THREAD

**Issue by gelpenaddict** [kubernetes/website#45783]
```
> kubectl create deployment web --image=gcr.io/google-samples/hello-app:1.0
...
> kubectl get pods
NAME                                 READY   STATUS    RESTARTS      AGE
web-57f46db77f-hlstp                 0/1     Error     4 (44s ago)   86s
>
> k logs web-57f46db77f-hlstp
exec /hello-app: exec format error 
>
```
The image probably needs to be updated for Apple Silicon. I also tried `hello-app:2.0` from the gcr link but it got the same error.

**Comment by stmcginnis** [comment]
Related: #45420

I'm not sure it's feasible, or at least easy to do, but it would be great if all examples used multi-arch images.

**Comment by gelpenaddict** [comment]
It is an easy rebuild; I only made a ticket because I saw independent tutorial Youtubers fix it in a jiffy.
https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images

But if not, can just have different image tags by arch.
