### ISSUE TITLE
Add kubectl command for creating admin user token in "Deploy and Access the Kubernetes Dashboard" page

### ISSUE THREAD

**Issue by maxkraft7** [kubernetes/website#45787]
Add that command please: kubectl -n kubernetes-dashboard create token admin-user

**Comment by dipesh-rawat** [comment]
_Page related to issue (based on the title):_  https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Add kubectl command for creating admin user token in "Deploy and Access the Kubernetes Dashboard" page
/kind feature

**Comment by adityasamant25** [comment]
Hi @maxkraft7,
The command `kubectl -n kubernetes-dashboard create token admin-user` should be preceded with creating a service account and a cluster role binding.

There is a link to [creating a sample user](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md) that has all the instructions.

Duplicating the instructions on the page seems unnecessary, especially as it is difficult to maintain if the source file changes.

**Comment by T-Lakshmi** [comment]
@maxkraft7,
Page already contains the URL  [creating a sample user](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md) that has all the necessary instructions.

So there is nothing to work on this issue.

**Comment by T-Lakshmi** [comment]
Closing issue as not planned.
/close
