### ISSUE TITLE
Deployments-Kubernetes 1.29 Version Not Recording Command Line Without `--record` Flag (in kubernetes.io doc can record without `--record`)

### ISSUE THREAD

**Issue by vcyj** [kubernetes/website#45780]
---

Kubernetes 1.29 Version Not Recording Command Line Without --record Flag 

## Bug Report

What happened:

In Kubernetes version 1.29, the command line invocations are not being recorded automatically in the deployment history when operation is performed without the --record flag. After running the kubectl rollout history deployment/nginx-deployment, some of the revisions show "<none>" in the CHANGE-CAUSE column when the operation is performed without --record flag.

Here is an example:
```Bash
[root@master01 deployment]# kubectl set image deployment.v1.apps/nginx-deployment nginx=nginx:1.16.1
deployment.apps/nginx-deployment image updated
[root@master01 deployment]# kubectl rollout history deployment/nginx-deployment
deployment.apps/nginx-deployment 
REVISION  CHANGE-CAUSE
1         <none>
2         <none>

[root@master01 deployment]# kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0

```
![image](https://github.com/kubernetes/website/assets/38095413/45d256ff-407f-476b-ba97-fa83e8565bd1)

the pic in doc in  https://kubernetes.io/docs/concepts/workloads/controllers/deployment

![image](https://github.com/kubernetes/website/assets/38095413/fe2d62e6-e47e-42ae-ac3e-8b906b5488db)

**Comment by T-Lakshmi** [comment]
Page issue mentioned: https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/deployment/

**Comment by vcyj** [comment]
> Page issue mentioned: https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/deployment/
> 
> @vcyj,
> You mention the pic from english version docs and provided chinese localisation docs url.
> which one you tried?
> 

Now i have changed to right doc url

**Comment by sftim** [comment]
/retitle Deployments-Kubernetes 1.29 Version Not Recording Command Line Without `--record` Flag (in kubernetes.io doc can record without `--record`)
/kind bug

**Comment by sftim** [comment]
The [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) concept page is out of date. We're [planning](https://github.com/kubernetes/kubernetes/issues/40422) to remove the deprecated `--record` command line argument from the `kubectl` tool.

We should change https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ to:
- move the tutorial for managing a Deployment into a separate page
- explain that `CHANGE-CAUSE` is a legacy column

IMO, we should also change https://kubernetes.io/docs/reference/labels-annotations-taints/#change-cause to explain its use. If the `kubernetes.io/change-cause` annotation is deprecated, we should say so.

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/kubernetes/issues/124259
