### ISSUE TITLE
Website shows that the latest patch release for kubernetes is 1.29.2 but 1.29.3 exists as the latest 

### ISSUE THREAD

**Issue by troy0820** [kubernetes/website#45781]
**This is a Bug Report**

**Problem:**

The website seems to be showing n-1 for Kubernetes versions for the latest patch release. The latest patch release is 1.29.3 and 1.28.8 according to the changelog in the kubernetes/kubernetes repository.  

**Proposed Solution:**
To allow the latest patch version to be displayed and not show the n-1 version of the latest patch version.  

**Page to Update:**
https://kubernetes.io/releases/

**Comment by dipesh-rawat** [comment]
This looks duplicate of an issue we already have https://github.com/kubernetes/website/issues/45668

/triage duplicate

**Comment by troy0820** [comment]
This is indeed a duplicate. 
/close
