### ISSUE TITLE
Unable to execute `cat server.js` command as per "Viewing Pods and Nodes" tutorial instructions

### ISSUE THREAD

**Issue by bvnarayan** [kubernetes/website#45791]
cat server.js did not work me. I tried a find and could not locate the file.

**Comment by dipesh-rawat** [comment]
_Page related to issue (based on issue title):_ https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

**Comment by dipesh-rawat** [comment]
/retitle Unable to execute `cat server.js` command as per "Viewing Pods and Nodes" tutorial instructions

**Comment by utkarsh-singh1** [comment]
Working for me rn, @bvnarayan can you share the screenshot of the tutorial?

**Comment by bvnarayan** [comment]
(base) ***@***.*** CS158 % kubectl exec -it
hello-node-ccf4b9788-mpmhb -- bash

bash-5.0# cat server.js

cat: can't open 'server.js': No such file or directory

bash-5.0# pwd

/

bash-5.0# ls

agnhost        etc            media          run            uploads

agnhost-2      home           mnt            sbin           usr

bin            lib            opt            srv            var

coredns        localhost.crt  proc           sys

dev            localhost.key  root           tmp

bash-5.0# find . -name "server.js" -print

bash-5.0# curl http://localhost:8000/

curl: (7) Failed to connect to localhost port 8000 after 0 ms: Connection
refused

bash-5.0#

bash-5.0# netstat -an

Active Internet connections (servers and established)

Proto Recv-Q Send-Q Local Address           Foreign Address         State


tcp        0      0 :::8080                 :::*                    LISTEN


udp        0      0 :::8081                 :::*


Active UNIX domain sockets (servers and established)

Proto RefCnt Flags       Type       State         I-Node Path

bash-5.0# curl http://localhost:8080

NOW: 2024-04-06 23:49:19.385539964 +0000 UTC m=+16726.089320894bash-5.0#

bash-5.0#

bash-5.0#

bash-5.0#

bash-5.0# find . -name "*.js" -print

bash-5.0# pwd

/

bash-5.0# ls

agnhost        etc            media          run            uploads

agnhost-2      home           mnt            sbin           usr

bin            lib            opt            srv            var

coredns        localhost.crt  proc           sys

dev            localhost.key  root           tmp

bash-5.0# cd agnhost

agnhost    agnhost-2

bash-5.0# cd agnhost

bash: cd: agnhost: Not a directory

bash-5.0# ls -F

agnhost*       etc/           media/         run/           uploads/

agnhost-2@     home/          mnt/           sbin/          usr/

bin/           lib/           opt/           srv/           var/

coredns*       localhost.crt  proc/          sys/

dev/           localhost.key  root/          tmp/

bash-5.0# ls run/

secrets

bash-5.0# ls run/secrets/

kubernetes.io

bash-5.0# ls home/

bash-5.0# ls bin/

arch           dumpkmap       kbd_mode       mv             setserial

ash            echo           kill           netstat        sh

base64         ed             link           nice           sleep

bash           egrep          linux32        pidof          stat

bbconfig       false          linux64        ping           stty

busybox        fatattr        ln             ping6          su

cat            fdflush        login          pipe_progress  sync

chgrp          fgrep          ls             printenv       tar

chmod          fsync          lzop           ps             touch

chown          getopt         makemime       pwd            true

conspy         grep           mkdir          reformime      umount

cp             gunzip         mknod          rev            uname

date           gzip           mktemp         rm             usleep

dd             hostname       more           rmdir          watch

df             ionice         mount          run-parts      zcat

dmesg          iostat         mountpoint     sed

dnsdomainname  ipcalc         mpstat         setpriv

bash-5.0# ls dev/

core             null             shm              termination-log

fd               ptmx             stderr           tty

full             pts              stdin            urandom

mqueue           random           stdout           zero

bash-5.0# ls

agnhost        etc            media          run            uploads

agnhost-2      home           mnt            sbin           usr

bin            lib            opt            srv            var

coredns        localhost.crt  proc           sys

dev            localhost.key  root           tmp

bash-5.0# ls -F

agnhost*       etc/           media/         run/           uploads/

agnhost-2@     home/          mnt/           sbin/          usr/

bin/           lib/           opt/           srv/           var/

coredns*       localhost.crt  proc/          sys/

dev/           localhost.key  root/          tmp/

bash-5.0#

bash-5.0#

bash-5.0# exit

exit

**Comment by utkarsh-singh1** [comment]
```bash
(base) ***@***.*** CS158 % kubectl exec -it hello-node-ccf4b9788-mpmhb -- bash
```

`hello-node-ccf4b9788-mpmhb` is not the right Pod you have deployed in the tutorial, the POD name should be like ⇒
`kubernetes-bootcamp-f95c5b745-qmtz7`

**Comment by adityasamant25** [comment]
@bvnarayan Please check the comment from @utkarsh-singh1 and confirm it resolves your issue. Please mark the issue as closed if the problem is resolved.

**Comment by divya-mohan0209** [comment]
@bvnarayan : I'll be closing this issue since it has been open for ~1 month without any response from your end. Please feel free to reopen it if there are modifications to the documentation/the instructions that you'd like to suggest.
/close
