### ISSUE TITLE
Kubelet Configuration (v1beta1)

### ISSUE THREAD

**Issue by wjswhdgus123** [kubernetes/website#45799]
maxPods: 250

**Comment by tamilselvan1102** [comment]
please describe the issue detailly

**Comment by tamilselvan1102** [comment]
Page related to the issue: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

**Comment by tengqm** [comment]
Sounds like invalid report. The default 110 is an official setting. It could be customized. Please consult your cloud admin or vendor docs for this.
/close wontfix
