### ISSUE TITLE
Add a YAML example to kubectl patch doc

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/website#458]
kubectl patch doc says that both YAML and JSON formats are supported, but all examples are in JSON form.
We should add atleast one YAML example.

User asking about YAML format: http://stackoverflow.com/questions/36920171/how-can-i-edit-a-deployment-without-modify-the-file-manually#comment61508585_36924484

cc @kubernetes/docs

**Comment by nikhiljindal** [comment]
I tried the following YAML patch:

```
$ ./cluster/kubectl.sh patch nodes 127.0.0.1 -p '"spec.unschedulable": true'
```

I got `"127.0.0.1" patched` response which made me think that the patch succeeded, but looking at the output of `kubectl get nodes` it didnt.

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by jaredbhatti** [comment]
We need an example generated.

**Comment by ryanmcginnis** [comment]
Ping. This would still be great to have. Not sure how to accomplish this currently:

    ~$ kubectl patch statefulset/web -p ' "spec.replicas": 4'
    statefulset "web" not patched

**Comment by steveperry-53** [comment]
This works for me (note the $):
**kubectl patch deployment in-place-demo  --patch $'spec:\n replicas: 5'**
deployment "in-place-demo" patched
**kubectl get deployment in-place-demo --output=yaml**
spec:
   ...
  replicas: 5

**Comment by steveperry-53** [comment]
I'm working on a new Task topic that will cover kubectl edit and kubectl patch:
https://github.com/kubernetes/kubernetes.github.io/pull/4519

**Comment by steveperry-53** [comment]
This also works. Create patch-file.yaml with this content:
spec:
 replicas: 6

Note the double quotes.
**kubectl patch deployment in-place-demo --patch "$(cat patch-file.yaml)"**

**Comment by steveperry-53** [comment]
attn: @nikhiljindal, @ryanmcginnis, @jaredbhatti

**Comment by steveperry-53** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/50532.

**Comment by ryanmcginnis** [comment]
/remove-lifecycle stale

Steve, did you ever figure out why the fix didn't generate in the API docs?

**Comment by tengqm** [comment]
The docs generated actually contains this info. See: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#patch
Feel free to reopen if that is not what you want.
/close

**Comment by Shikaz** [comment]
I am trying to patch node condition type status, is there any example for that ?
