### ISSUE TITLE
[zh] Stale feature state for Chinese version of “Specifying a Disruption Budget for your Application”

### ISSUE THREAD

**Issue by Brhett** [kubernetes/website#45800]
**This is a Bug Report**

**Problem:**
The feature state is not consistent between English version (v1.27 beta) and Chinese version (v1.26 beta).
* https://kubernetes.io/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy
* https://kubernetes.io/zh-cn/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy

**Proposed Solution:**

Make the translation(s) be consistent.

**Page to Update:**
https://kubernetes.io/...

**Comment by sftim** [comment]
/retitle [zh] Stale feature state for Chinese version of “Specifying a Disruption Budget for your Application”
