### ISSUE TITLE
Issue with k8s.io/docs/setup/

### ISSUE THREAD

**Issue by Pavankalyan000** [kubernetes/website#45818]

**Comment by niranjandarshann** [comment]
@Pavankalyan000  can you specify the description of the issue you are facing in kubernetes website

**Comment by niranjandarshann** [comment]
Please write the detailed description of the issue that you want to raise  for community.

**Comment by niranjandarshann** [comment]
There is no any description of issue provided by @Pavankalyan000 so i am closing this issue.
You may raise other issue  with suitable description.
