### ISSUE TITLE
[Zh] Broken link "Weave Scope" under Installing Addons page.

### ISSUE THREAD

**Issue by oldxu131** [kubernetes/website#45832]
安装扩展（Addon）章节中---可视化管理下---[Weave Scope](https://www.weave.works/documentation/scope-latest-installing/#k8s) 是一个可视化工具，用于查看你的容器、Pod、服务等---【链接失效】

**Comment by T-Lakshmi** [comment]
@oldxu131,
Please update the issue title and description in English language which is recommended by community.

**Comment by oldxu131** [comment]
The "Weave Scope" link under the "Install Extension" chapter is invalid, located at: 
https://kubernetes.io/zh-cn/docs/concepts/cluster-administration/addons/#visualization-and-control

**Comment by T-Lakshmi** [comment]
/retitle [Zh] Broken link "Weave Scope" under Installing Addons page.
/language zh
/remove-triage needs-information
/kind bug

**Comment by T-Lakshmi** [comment]
@oldxu131,
Thanks for the explanation, Can you please edit the description with the information mentioned in  https://github.com/kubernetes/website/issues/45832#issuecomment-2048827205.

> 安装扩展（Addon）章节中---可视化管理下---[Weave Scope](https://www.weave.works/documentation/scope-latest-installing/#k8s) 是一个可视化工具，用于查看你的容器、Pod、服务等---【链接失效】

**Comment by tengqm** [comment]
The Weave Net thing has been dropped although someone is now continuing it under a different name. We are not fixing the zh version before the en version is fixed.
I'm closing this issue because the en version change will be sync'ed to the zh version eventually, balls will not be dropped.
