### ISSUE TITLE
[ja] Following the upstream for `content/ja/docs/tasks/tools/_index.md`

### ISSUE THREAD

**Issue by levi106** [kubernetes/website#45855]
**This is a Feature Request**

**What would you like to be added**

Following the upstream for 'content/ja/docs/tasks/tools/_index.md'.

**Why is this needed**

This page is already outdated.

**Comments**

/language ja
/assign

**Comment by Okabe-Junya** [comment]
Thank you for opening this issue :)

/area localization
/triage accepted
