### ISSUE TITLE
The concepts page print section gives multi-page print as default which is cropping most of the commands

### ISSUE THREAD

**Issue by snaidus** [kubernetes/website#45875]
The concepts page print section gives multi-page print as default which is cropping most of the commands. how to print single-page print or how to wrap the commands in print.

**Comment by sftim** [comment]
/kind support

It sounds like you'd like an option to print a section to fit on one page of a PDF; have I got that right?

**Comment by niranjandarshann** [comment]
@snaidus  yes I had also noticed this.  Here are some of the screenshot which show the cropping of some command.  
![Screenshot from 2024-04-25 09-49-13](https://github.com/kubernetes/website/assets/124760321/52bac527-61cb-4464-96b4-9fed79dbe4a4)
![Screenshot from 2024-04-25 09-49-28](https://github.com/kubernetes/website/assets/124760321/cef38ed8-ca28-42b2-b16f-4e628b0d3116)

I think this is what you asked.

**Comment by niranjandarshann** [comment]
@snaidus  If you are looking for printing only perticular section then you can do that by selecting the entire section and the by right clicking on your mouse you can select the print option to print then the entire selected section will get printed.

**Comment by snaidus** [comment]
yes, i was looking for the same. let me try

**Comment by divya-mohan0209** [comment]
@snaidus We'll be closing this out since 
- this is a support request for the look and feel of our pages when printed
- a solution has already been proposed with no response from your end.

/close
