### ISSUE TITLE
Wrong doc link of `EnvVarSource` in page `Define Environment Variables for a Container`

### ISSUE THREAD

**Issue by monitor1379** [kubernetes/website#45908]
**This is a Bug Report**

**Problem:**

Page: [[kubernetes.io/docs] Define Environment Variables for a Container](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)

At the bottom of the page, the link of `See [EnvVarSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#envvarsource-v1-core).`  is 404

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by dipesh-rawat** [comment]
/close

Fixed by https://github.com/kubernetes/website/pull/45914
