### ISSUE TITLE
API Overview - wrong link to Kubernetes API reference 1.30

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#45917]
The [Kubernetes API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/) link in "API Overview" page does not work once updated to point to v1.30

**Comment by dipesh-rawat** [comment]
There is PR https://github.com/kubernetes/website/pull/45914 raised to update the single-page API reference for v1.30.

**Comment by sftim** [comment]
/close

Fixed by #45914
