### ISSUE TITLE
About cgroup v2 - wrong link to "Memory QoS with cgroups v2"

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#45929]
[What is cgroups v2](https://kubernetes.io/docs/concepts/architecture/cgroups/#cgroup-v2) chapter refers to the **Memory QoS** feature but pointing [to an old blog entry from 2021](https://kubernetes.io/blog/2021/11/26/qos-memory-resources/); link should be updated to point to [Memory QoS with cgroups v2](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/#memory-qos-with-cgroup-v2) feature description in k8s official documentation.

**Comment by thisisharrsh** [comment]
I would like to work on this issue.

**Comment by thisisharrsh** [comment]
The issue is fixed [here](https://github.com/kubernetes/website/pull/45935).
