### ISSUE TITLE
[TYPO] Kubernetes API Concepts

### ISSUE THREAD

**Issue by ericpromislow** [kubernetes/website#45940]
`s/you wants to receive chunks/you want to receive chunks/` in https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks

**Comment by thisisharrsh** [comment]
I would to like to work on this issue.

**Comment by thisisharrsh** [comment]
The issue is fixed [here](https://github.com/kubernetes/website/pull/45942).
