### ISSUE TITLE
Convert blog image to vector from Beta Support For Pods With User Namespaces

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#45963]
**This is a Feature Request**

**What would you like to be added**
Make an SVG version of the image in https://kubernetes.io/blog/2024/04/22/userns-beta/

**Why is this needed**
- We like vector images for clarity
- they also help localization

**Comments**
 (see files from https://github.com/kubernetes/website/pull/45354 for a head start)

**Comment by sftim** [comment]
/retitle Convert blog image to vector from Beta Support For Pods With User Namespaces

**Comment by thisisharrsh** [comment]
I would to like to work on this issue.
