### ISSUE TITLE
Heredoc snippets remove syntax coloring

### ISSUE THREAD

**Issue by MatthewFallon** [kubernetes/website#45960]
# Description of Issue

Current page link I am looking at for reference: https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/ 

This is 100% a tiny gripe and not a priority demand from the documentation, but would make everything more readable for me so I will bring it up. 

## Heredocs

Heredocs, and a cat command using them, are a great way to make a copypasta tutorial like this extremely predictable and posix compliant. I generally have no issue with the use of them, **BUT** they make the entire heredoc a flat string when it comes to syntax highlighting.

When looking through the documentation above, I personally prefer to just scan the page for reference while working on a personal tool rather than actually copy paste each individual section in a sandbox just to see the output files, and having each file you are using as an example instead show as just a flat red blob of text rather than useful yaml with syntax highlighting makes it difficult to scan the page or read each document.

# Suggestion

I would love if instead the behavior of the docs was to keep the files that are wanted pasted in normally, with syntax highlighting, and then provide a copy button or similar that allows the user to fill their clipboard with the associated heredoc cat command, allowing for the best of both worlds in one view.

Or 

Similar to other docs which provide multiple languages with a selector along the top of each code section to keep the same language selection across the page/session providing two separate sections with the heredoc snippets as the default but allowing people to swap to the file based examples. Allowing the best of both worlds while defaulting to the sort of standard copy pasta codelab format.

Obviously know that either of these solutions may be untenable depending on the structure of the docs overall, but figured I would toss it out there, thanks for reading 👍 😄

**Comment by sftim** [comment]
/priority backlog
(ie, nothing higher)

**Comment by MatthewFallon** [comment]
> Do you have an example of a particular snippet that you think should be done a different way to help learners @MatthewFallon ?

Hey @sftim :wave:  yes looking at [this section](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#configmapgenerator) I see the following code snippet:

```
# Create a application.properties file
cat <<EOF >application.properties
FOO=Bar
EOF

cat <<EOF >./kustomization.yaml
configMapGenerator:
- name: example-configmap-1
  files:
  - application.properties
EOF
```

Which as commands holds no purpose other than:
1. Create text file application.properties with contents
2. Create yaml file kustomization.yaml  with contents

There are multiple instances of this on that page, which really only serves the purpose of providing an easy copy paste as manually typing a heredoc command like such is kind of cumbersome to begin with haha.

I think a fair point on not wanting to encourage too much copy pasting using buttons as such :+1:  I had figured that was the original intent based on content. In this case I think you're right that these commands would better be shown as two individual `code_sample` statements instead. I think many of the code snippets on this page just need to be modified to fit that format.

Will leave this here as clarification of the suggestion, and will potentially look into contributing the change myself if I find the time. Thanks for adding context! :+1:  :smile:

**Comment by sftim** [comment]
We don't use `code_sample` for shell commands (it's for manifests).

However, you can copy just the `FOO=Bar` line into a text editor if you want. I get that people might like the computer to do more of the work, but I also think we should focus on our high priority issues ahead of any more work here.
