### ISSUE TITLE
Glossary list of core objects is wrong

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#45972]
**This is a Bug Report**

**Problem:**

The glossary listing for [core objects](https://k8s.io/docs/reference/glossary/?core-object=true) includes several things that aren't core object kinds, such as:
- Pod Security Policy (removed!)
- Quantity (not an API kind that you can create using `kubectl` etc)
- Dynamic Volume Provisioning (not an API kind at all)
- Cloud Controller Manager (a binary, not an API kind)
- Taint (a fundamental concept, but not an API kind)
- Volume (not an API kind that you can create using `kubectl` etc)
- Volume Plugin (not an API kind at all)
- QoS Class (not an API kind)

**Proposed Solution:**

Edit those glossary entries. Optionally add in glossary entries for all core object kinds; for example, NetworkPolicy, Node and PodTemplate should be in the list.

**Page to Update:**
https://k8s.io/docs/reference/glossary/?core-object=true

**Additional Information:**
/language en

**Comment by dipesh-rawat** [comment]
We should fix this.

/priority backlog
/triage accepted

**Comment by shannonxtreme** [comment]
In general, do the glossary categories correspond to the API categories? If they aren't, should they be so that new additions are easier to put into buckets? If they are, are we socializing that information well (like with comments in the source directory or style guide)?

**Comment by sftim** [comment]
We don't really have API categories.

https://kubernetes.io/docs/reference/kubernetes-api/ does have some categories, but (IIRC) this SIG and its tech leads at the time were keen to de-emphasize or drop them.

**Comment by sftim** [comment]
Putting APIs into categories or a taxonomy might be useful, but it makes work for maintainers that I think isn't justified by the value you get from it.

**Comment by sftim** [comment]
BTW I'm taking “core object” to mean “API kinds built in to Kubernetes”, and not “API kinds in the core API group”.

**Comment by vaibhav2107** [comment]
@mguan2020 Are you still working on this issue?

**Comment by vaibhav2107** [comment]
As the PR #48333 has been merged so we can close this issue
