### ISSUE TITLE
[Issue with k8s.io/docs/getting-started-guides/ubuntu/manual/] File cluster/ubuntu/config-default.sh not available

### ISSUE THREAD

**Issue by piyushkv1** [kubernetes/website#4597]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
File for configuring cluster in ubuntu is not available cluster/ubuntu/config-default.sh.

**Proposed Solution:**
This might be cause of changing the code. Please modify the documentation in as per latest code changes.

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@piyushkv1 :wave: 

It looks like the `cluster/ubuntu/` directory [was removed](https://github.com/kubernetes/kubernetes/tree/master/cluster) from kubernetes/kubernetes. 

It also looks like the only `config-default.sh` file in kubernetes/kubernetes is [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/kubemark/gce/config-default.sh), with no mention of Ubuntu.

I'm flagging this as Actionable **and** Needs Clarification; this sounds like it needs an Ubuntu subject matter expert.

**Comment by tengqm** [comment]
@zacharysarah was correct. There have been some struggle on this, but ... it is gone.
