### ISSUE TITLE
Improvement for k8s.io/docs/concepts/overview/working-with-objects/common-labels/

### ISSUE THREAD

**Issue by peterwwillis** [kubernetes/website#46007]
There is a suggested annotation of:
```
    app.kubernetes.io/managed-by: helm
```

But Helm actually [recommends](https://helm.sh/docs/chart_best_practices/labels/#standard-labels):
```
    app.kubernetes.io/managed-by: {{ .Release.Service }}
```

Which will insert a value of "Helm", with a first character in uppercase.

According to [this research](https://downey.io/notes/dev/kubernetes-labels-are-case-sensitive/), labels are case-sensitive, except for the prefix.

(You can notice this discrepancy if you are using the `helm diff` plug-in, as your chart with a lower-case word will always be replaced with upper-case, so a three-way-merge diff shows this as changing every time. I also imagine you could find this if you tried to use the label as a selector)

Therefore I recommend that the suggested annotation in this document be replaced with:

```
    app.kubernetes.io/managed-by: Helm
```

Caveat: I have no idea if the case changed between helm v2 and v3, but v2 is defunct now, so should be safe to make this change.

**Comment by shannonxtreme** [comment]
This is just an example of what could go in, but I think it might be a good first issue. 

If you want to work on this, assign yourself to this issue. Update all instances of `app.kubernetes.io/managed-by: helm` to `Helm`, including in the table. 

You should be able to complete this in GitHub without needing to work on a local clone. For instructions, read [Opening a pull request](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#changes-using-github).

**Comment by steve-hardman** [comment]
Let me help with this.

/assign
