### ISSUE TITLE
[vi]Please correct spelling errors during translation

### ISSUE THREAD

**Issue by JaxVN** [kubernetes/website#46013]
Đề nghị thay thế "lạc thú" bằng "lỗi thời"
![image](https://github.com/kubernetes/website/assets/19403704/b582e257-83bd-403f-b240-9d68df3ab3cb)

**Comment by niranjandarshann** [comment]
@JaxVN  Please raise the issue in english putting the language code before the issue in [] 
example **[vi] Issue title here** 
It will be good practice to write the description and title  of the issue in English only.

**Comment by JaxVN** [comment]
@niranjandarshann Thank you! BTW i'd commited [7dca2ba](https://github.com/kubernetes/website/commit/7dca2ba17877d2ca11a1ccdfc017b319654c78e2) about this change, waiting for review.

**Comment by hoangsvit** [comment]
> @niranjandarshann Thank you! BTW i'd commited [7dca2ba](https://github.com/kubernetes/website/commit/7dca2ba17877d2ca11a1ccdfc017b319654c78e2) about this change, waiting for review.

Please create a [pulling request](https://github.com/kubernetes/website/pulls) for this commitment

**Comment by shurup** [comment]
Fixed in #46014
