### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-volume-storage/: extra space before commands

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#4602]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/ This page has extra spaces before the commands:

> ![image](https://user-images.githubusercontent.com/159209/28940811-c4581388-784a-11e7-935e-da69dd425223.png)

I am not sure it's a more systemic problem, but this causes commands to not to show up on the bash history (undesirable). https://stackoverflow.com/questions/6475524/how-to-prevent-commands-to-show-up-in-bash-history

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/

/assign @cody-clark

**Comment by cody-clark** [comment]
@ahmetb A cursory look through the rest of the docs under Configure Pods and Containers showed that one out of four docs also had this issue. I'll make this change as I update the callouts.
