### ISSUE TITLE
Install and Set Up kubectl on Linux: German translation outdated

### ISSUE THREAD

**Issue by FeepingCreature** [kubernetes/website#46021]
The German translation of https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management , found at https://kubernetes.io/de/docs/tasks/tools/install-kubectl/ , still directs the user to set up `https://apt.kubernetes.io/` as the package source. This has been [deprecated for a year](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate) and will no longer work at all.

**Comment by dipesh-rawat** [comment]
Looks similar _(possibly duplicate)_ to https://github.com/kubernetes/website/issues/45449

**Comment by FeepingCreature** [comment]
Thanks! Yep it's a dupe. Closing.
