### ISSUE TITLE
Add banner for KubeCon 2024 China

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/website#46039]
**This is a Feature Request**

**What would you like to be added**

Set a banner to announce KubeCon 2024 China https://events.linuxfoundation.org/kubecon-cloudnativecon-open-source-summit-ai-dev-china/

**Why is this needed**

We usually turn on a banner for the upcoming KubeCon about 4 weeks ahead of the event.
 - for EU and NA, we did several times for 4 or 5 weeks.
 - the first time for KubeCon China is the 2021 virtual KubeCon China, we have the banner for 2 weeks. 2-4 weeks are OK for me. 

Logos are not available yet: https://github.com/cncf/artwork/tree/main/other/kubecon-cloudnativecon/.

https://events.linuxfoundation.org/kubecon-cloudnativecon-open-source-summit-ai-dev-china/
 Also see the [banner](https://github.com/kubernetes/website/blob/main/data/announcements/scheduled.yaml#L96-L105) config from a previous year's KubeCon(KubeCon China 2021 for 2 weeks).

**Comments**
This change will need @kubernetes/steering-committee approval.

I would like to set the banner to start on the July 26th, 2024 and to end on the August 23, 2024 at 1800 CST (UTC+8).

**Comment by steve-hardman** [comment]
I can help with this. I helped with last Kubecon EU banner too.

/assign

**Comment by windsonsea** [comment]
Ping @steve-hardman , if you are busy, I would like to take this job :)
