### ISSUE TITLE
when will kubernetes.io be updated for 1.30，I want to cjheck feature-gate updated？

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/website#46032]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**
when will kubernetes.io be updated for 1.30，I want to cjheck feature-gate updated？
**Comments**

**Comment by thisisharrsh** [comment]
Hi @13567436138, as it seems like a support request you can post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/kind support

**Comment by thisisharrsh** [comment]
You can also visit this [page](https://kubernetes.io/releases/patch-releases/#detailed-release-history-for-active-branches) for more information.

**Comment by dipesh-rawat** [comment]
> when will kubernetes.io be updated for 1.30

@13567436138 The [website](https://kubernetes.io/) has already been updated for the v1.30 release, this was done on the day of release. For details on the features gates, please check out [Feature Gate page (click here)](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) and for the removed feature gates, visit [here](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/). You can find the v1.30 release blog [here](https://kubernetes.io/blog/2024/04/17/kubernetes-v1-30-release/).

**Comment by divya-mohan0209** [comment]
@13567436138 : Will be closing this issue since the English site has been updated. For other languages, please raise an issue with the relevant label applied/or reach out to the relevant team on Slack.
/close
