### ISSUE TITLE
Some zh text is not easy to understand in cluster-large.md

### ISSUE THREAD

**Issue by yushuobuxiu** [kubernetes/website#46040]
1. “集群是运行 Kubernetes 代理的” 是指每个节点运行一个 kubelet 嘛？若是请修改为更容易理解的表达，若否请描述清楚具体正确。
2. “你可以通过添加或删除节点来扩展集群” 这里应该是扩缩容集群。

**Comment by dipesh-rawat** [comment]
Hi @yushuobuxiu, we track issues in English. If feasible kindly describe the [issue](https://github.com/kubernetes/website/issues/46040#issue-2267447389) in English language.

/triage needs-information

**Comment by windsonsea** [comment]
/retitle Some zh text is not easy to understand in cluster-large.md

/language zh

Related to pr #46041

Hi @yushuobuxiu, please use english to describe what happened.

**Comment by T-Lakshmi** [comment]
Draft PR was already opened to fix this issue and currently closed due to no response from PR author @yushuobuxiu.
PR #46041

if any Contributors interested, you are more welcome to recreate PR.
