### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/aws/

### ISSUE THREAD

**Issue by istream-philion** [kubernetes/website#4605]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Docs say: "This is only supported for kubernetes 1.5 and earlier. Consider switching to one of the supported options."

**Proposed Solution:**
Add info about what the supported options are! Nothing on the page indicates a method to use instead.

**Page to Update:**
http://kubernetes.io/...

**Comment by istream-philion** [comment]
https://kubernetes.io/docs/getting-started-guides/aws/

**Comment by zacharysarah** [comment]
@istream-philion Good point! 

/cc @ahmetb 👋

**Comment by ahmetb** [comment]
@zacharysarah there's `approvers:` field on the linked document, I recommend cc'ing them instead. I don't know the answer.

**Comment by zacharysarah** [comment]
@justinsb @chrislovecnm 👋  Any input on the [replacement for kube-up](https://kubernetes.io/docs/getting-started-guides/aws/#kube-up-is-no-longer-supported-in-kubernetes-16) in v1.6+?

**Comment by chrislovecnm** [comment]
We have a list in the sig-aws community repo and I think a list in another section of our website. We probably need to update the specific page
