### ISSUE TITLE
[ar] Netlify preview needs to be configured for the Arabic branch

### ISSUE THREAD

**Issue by mboukhalfa** [kubernetes/website#46087]
**This is a Feature Request**

As Kubernetes Arabic localizer, I propose configuring Netlify preview on the Arabic branch (`dev-1.29-ar.1`) to facilitate the previewing of changes, ensure successful website building, and assist reviewers in examining the content.

The `dev-1.29-ar.1` branch has been created specifically to host the Arabic localization efforts. The progress of this localization is being tracked through the following issues:

https://github.com/kubernetes/website/issues/44682
https://github.com/kubernetes/website/issues/37546

**What would you like to be added**

Configure Netlify preview specifically for the `dev-1.29-ar.1` branch.

**Why is this needed**

It is essential to have Netlify preview for the Arabic branch to facilitate the review process. This preview functionality will be particularly useful for identifying and addressing CSS issues related to right-to-left (RTL) layout, as Arabic is the first RTL language supported. For example, issues such as those outlined in the following PR and issue:

https://github.com/kubernetes/website/pull/46042
https://github.com/kubernetes/website/issues/45077

**Comments**

The Netlify preview will enable contributors and reviewers to visualize and discuss these issues directly within the context of pull requests, enhancing the efficiency and effectiveness of the localization efforts.

Slack discussion : https://kubernetes.slack.com/archives/C1J0BPD2M/p1714297094044239

**Comment by seokho-son** [comment]
PTAL @sftim

**Comment by sftim** [comment]
@kubernetes/sig-docs-leads FYI

**Comment by reylejano** [comment]
I've added a Netlify site that deploys `dev-1.29-ar.1`, please check if a preview is available on an updated or new PR

**Comment by mboukhalfa** [comment]
> I've added a Netlify site that deploys `dev-1.29-ar.1`, please check if a preview is available on an updated or new PR

updated this PR and waiting for the build  https://github.com/kubernetes/website/pull/46042

**Comment by mboukhalfa** [comment]
Netlify preview is working now on PRs targeting the branch `dev-1.29-ar.1`
Thanks @reylejano 
We can close this issue now
