### ISSUE TITLE
[ja] Add button in `content/ja/docs/home/_index.md`

### ISSUE THREAD

**Issue by EigoOda** [kubernetes/website#46096]
**This is a Feature Request**

**What would you like to be added**

Add button for "ドキュメントについて" in https://kubernetes.io/ja/docs/home/.

**Why is this needed**

Because it exists in en(https://kubernetes.io/docs/home/) but not in ja( https://kubernetes.io/ja/docs/home/).

**Comments**

/language ja
/assign

**Comment by Okabe-Junya** [comment]
ありがとうございます！日本語話者でないメンテナの方などのために、タイトルは英語表記いただけると助かります〜！

/retitle [ja] Add button in `content/ja/docs/home/_index.md`
/area localization
/triage accepted
