### ISSUE TITLE
Note needed in "Using a Service to Expose Your App > Step 3: Deleting a service"

### ISSUE THREAD

**Issue by rahul38888** [kubernetes/website#46105]
### Location
In `Step 3: Deleting a service` of [Using a Service to Expose Your App](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/) wiki

### Issue
There should be a note mentioning that after running `kubectl delete service -l app=kubernetes-bootcamp` command, it might take some time for the the cache to get cleared. As a side effect, people might see `curl http://"$(minikube ip):$NODE_PORT"` to return valid results. This might create confusion for some people like it did for me.

**Comment by adityasamant25** [comment]
Hi @rahul38888,
There is a step mentioned to ensure the service is deleted before verifying with the curl command.
```
Confirm that the Service is gone:
kubectl get services
```

Is this not sufficient? Do you suggest to emphasize the text on this step to make it clearer?

**Comment by vishalbidwe** [comment]
Hi Team,

I have created the PR https://github.com/kubernetes/website/pull/46292 by adding note to clarify the service's expected results, addressing potential confusion among users till cache gets cleared.

Feel free to review and merge the PR

Thanks :)

**Comment by divya-mohan0209** [comment]
@rahul38888 : Please could you advise why this extra line is needed?

**Comment by rahul38888** [comment]
Sorry for the late  reply.

@adityasamant25 Making sure service in not listed by `kubectl get services` is not enough. I have seen URL still working even after  that. So there should be a note like the one #46292 by @vishalbidwe will be adding 

@divya-mohan0209 , I think it make sense to have this note as it will provide a complete picture to readers.

**Comment by adityasamant25** [comment]
@rahul38888 I have personally not experienced this behaviour. However, if you have experienced it and others can verify, then I do not see a harm in emphasizing about waiting for few seconds before the changes take effect.
