### ISSUE TITLE
malicious domain name in documentation

### ISSUE THREAD

**Issue by ioqr** [kubernetes/website#46118]
Please change example domain away from "hello-world.info" in https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/.  

In my browser, hello-world.info redirects to a malicious website, one of those random spam redirects often to a malware download. (Interestingly enough it always redirects to a normal looking parking page when I'm in private mode).

I suggest the .info is changed to a reserved TLD such as ".internal" or ".private", as one may reasonably make a mistake when following the tutorial and instead talk this malicious host.

**Comment by sftim** [comment]
We should use `hello-world.example`.

/kind bug

What's the security impact of someone clicking on that site @ioqr?
