### ISSUE TITLE
Improvement for k8s.io/docs/tasks/manage-hugepages/scheduling-hugepages/

### ISSUE THREAD

**Issue by cyford** [kubernetes/website#46138]
i would like to see how and where these hugepages are apllocated..     i set 1 pod to use 1GB  and i see 2GB is used  im thinking it is one of longhorn pods,  however i am unable to check an verify which one

**Comment by thisisharrsh** [comment]
Page related to the issue: https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/

**Comment by thisisharrsh** [comment]
You can use `kubectl get pods -A` and look for the pod with hugepages resource.

**Comment by thisisharrsh** [comment]
And for the longhorn, you can check with `kubectl get pods -A -l app = longhorn`

**Comment by cyford** [comment]
> You can use `kubectl get pods -A` and look for the pod with hugepages resource.


![image](https://github.com/kubernetes/website/assets/25903490/b1f7ee3d-23ee-403e-9b36-a8f406e16193)

lol I use that every day  ,   you should test ya commands before replying
