### ISSUE TITLE
Missing class name in example yaml (Set up Ingress on Minikube with the NGINX Ingress Controller)

### ISSUE THREAD

**Issue by 24online24** [kubernetes/website#46228]
The file in question can also be found here: https://k8s.io/examples/service/networking/example-ingress.yaml

I have started working with Kubernetes and I have noticed that the tutorial mentioned in the title (https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/) doesn't work. After comparing it with other guides that work, I have noticed that the ingress class is not specified. This is the cause of the issue.

Adding `ingressClassName: nginx` fixes the issue.

**Comment by adityasamant25** [comment]
Hi @24online24,
I have just executed all the steps in the tutorial on a MacOS M series, and they ran successfully.

I believe if you run the steps on a fresh minikube cluster and follow all the steps as mentioned in the tutorial, they will work.

You may be executing the steps on an existing cluster which already has multiple ingress controllers present. In that case, it would be necessary to specify the ingress class in the ingress resource, to bind it with the appropriate cluster.

Having said that, adding the `ingressClassName` to the ingress resource could make the tutorial less flaky. Considering that the [service/networking/example-ingress.yaml](https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/service/networking/example-ingress.yaml) file is referred by this page alone, making this change does not possess a risk to other pages in the documentation.

**Comment by 24online24** [comment]
@adityasamant25 Thanks for your input!
I went back and tested (on my Windows 11 Pro, x86-64 machine) and found out this:
- if you add ingress through `minikube addons enable ingress` and configure it through `kubectl apply -f https://k8s.io/examples/service/networking/example-ingress.yaml`, it results in 
```
NAME              CLASS   HOSTS              ADDRESS   PORTS   AGE
example-ingress   nginx   hello-world.info             80      6s
```
- if you add ingress through `helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace` and apply the same configuration, it results in
```
NAME              CLASS    HOSTS              ADDRESS   PORTS   AGE
example-ingress   <none>   hello-world.info             80      4s
```

I found the issue as I have always decided to use the helm version.

Finally, this issue is getting solved in this PR: https://github.com/kubernetes/website/pull/46229

**Comment by adityasamant25** [comment]
@24online24 Thank you for the clarification, and good work with the PR !

**Comment by 24online24** [comment]
@adityasamant25 Thank you too for the support and time! Everyone I have interacted so far in this community has been nothing but a pleasure to work with and motivated me to keep contributing.
