### ISSUE TITLE
Improve note on "Manage TLS Certificates": Replace "custom CA certificate" with "root CA certificate" for clarity

### ISSUE THREAD

**Issue by frasmarco** [kubernetes/website#46223]
in the note:

> Note:
> 
> Even though the custom CA certificate may be included in the filesystem (in the ConfigMap kube-root-ca.crt), 

I think "custom CA certificate" should be better rewritten as "root CA certificate" for clarity.

**Comment by dipesh-rawat** [comment]
Page reported in issue _(based on the title)_:  https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Improve note on "Manage TLS Certificates": Replace "custom CA certificate" with "root CA certificate" for clarity
/sig auth cluster-lifecycle

**Comment by frasmarco** [comment]
@dipesh-rawat This is not related to auth or cluster lifecycle SIGs, those aren't cluster certificates but application. "These CA and certificates can be used by your workloads to establish trust." I think the only SIG involved is documetation

**Comment by sftim** [comment]
> Even though the custom CA certificate may be included in the filesystem (in the ConfigMap kube-root-ca.crt),

“custom” is not a synonym for “root”. We might want to write “custom trust anchor (the root certificate)”, or something like that. Although the ConfigMap is named `kube-root-ca.crt`, its key role is to provide a _trust anchor_ (and, despite the name, I think that it can actually be an intermediate CA).

Which web page needs amending?
