### ISSUE TITLE
[Bn] enable Netlify preview for the dev-1.24-bn.1 

### ISSUE THREAD

**Issue by seokho-son** [kubernetes/website#46226]
The Bengali team is developing their localization in the https://github.com/kubernetes/website/tree/dev-1.24-bn.1 branch.

To ensure that [the Bengali localization PRs](https://github.com/kubernetes/website/pulls?q=is%3Apr+is%3Aopen+label%3Alanguage%2Fbn) are checked with a build test, Netlify needs to be enabled.

**Comment by sftim** [comment]
/remove-kind support

[This is not an end user asking for help.]

/sig contributor-experience

/triage accepted
Emeritus (!) tech lead here; I think the request is reasonable.

**Comment by tengqm** [comment]
Is there something the team needs to do?

**Comment by seokho-son** [comment]
> Is there something the team needs to do?

Yes, there is a need from the Bengali team. The primary purpose is to support the review of Bengali-related PRs targeting the dev branch and to ensure the approval of error-free PRs. :)

**Comment by tengqm** [comment]
My question was that if there are some specific actions the sig-docs lead team need to take?

**Comment by seokho-son** [comment]
> My question was that if there are some specific actions the sig-docs lead team need to take?

@tengqm Oh, I misunderstood your comment. :)

Some of the SIG-Docs leads have the authority to configure Netlify for a new branch. So, this request is for one of the leads to configure Netlify for the dev branch.
Currently, I am not sure who among the lead team has the authority, except for @reylejano.

**Comment by tengqm** [comment]
There doesn't seem to me like a config option on Netlify for explicitly adding a branch into build. I did tried look around for such settings, but obviously I failed.

Did we do this for the Korean translation? I mean, for each localization branch folks create, we have to adjust the Netlify settings?

**Comment by sftim** [comment]
IIRC we can do this for any localization that wants it (usually, it's useful before the localization launches). I think we need to define a new site in Netlify for each localization we want to build.

**Comment by seokho-son** [comment]
IIRC, yes I think we need to define a new site in Netlify for each localization.

In case of Korean localization, we have 
- Configuration for k8s-dev-ko
- [k8s-dev-ko.netlify.app](https://k8s-dev-ko.netlify.app/)

- Deploys from [GitHub](https://github.com/kubernetes/website).

- Owned by [K8s Docs: Korean](https://app.netlify.com/teams/k8s-docs-ko).

And recently, Arabic team got their page. :)

**Comment by divya-mohan0209** [comment]
Yes, this is a reasonable request. One of the things, IMO, localisation leads should be able to do is to help get this sorted for different localisations. We can, of course, discuss this in the streamlining discussion item further. 

Thoughts @reylejano @natalisucks

**Comment by tengqm** [comment]
Sorry I didn't get the point. Is the creation of a new netlify site mandatory? I don't think there is a k8s-dev-ja.netlify.app site, for example. But there are `dev-<ver>-ja.<n>` branches for the Japanese localization team to use.

Even for the Korean localization, take [this PR](https://github.com/kubernetes/website/pull/46259) as an example, the "netlify preview" link works and it leads us to https://deploy-preview-46259--kubernetes-io-main-staging.netlify.app/. Where I am supposed to switch to the Korean localization, which is https://deploy-preview-46259--kubernetes-io-main-staging.netlify.app/ko/. I don't understand why we need a new config for a localization. My understanding is that all localization are built together when a PR is committed, thanks to the multi-lingual support by Hugo. I could be wrong though.

**Comment by tengqm** [comment]
Update: from https://github.com/kubernetes/website/pull/46264 we can see that the netlify preview works for the `bn` localization team. Although I'm not aware of any build time configuration changes, this issue can be closed, I think?

**Comment by reylejano** [comment]
> Yes, this is a reasonable request. One of the things, IMO, localisation leads should be able to do is to help get this sorted for different localisations. We can, of course, discuss this in the streamlining discussion item further.
> 
> Thoughts @reylejano @natalisucks

I believe localization subproject leads should have the ability to fulfill the request to create a Netlify site for preview for different localizations

I didn't see a Netlify site for Bengali so I created one named kubernetes-io-bn-staging which deploys the dev-1.24-bn.1 branch

This issue can be closed when the preview is confirmed to be working

**Comment by seokho-son** [comment]
- Confirm Netlify site for Bengali works (ex: https://deploy-preview-46313--kubernetes-io-bn-staging.netlify.app/ )

(I guess we've configured both main-staging and ben-staging sites for [kubernetes:dev-1.24-bn.1](https://github.com/kubernetes/website/tree/dev-1.24-bn.1). So, PRs to dev-1.24-bn.1 will show preview for both.)

/close
