### ISSUE TITLE
[vi] Kubernetes Documentation - Broken Structure

### ISSUE THREAD

**Issue by JaxVN** [kubernetes/website#46236]
This is a Bug Report
**Problem**:  The main page of the website has 7 Menus, the Vietnamese localization is missing a lots contents.
**Proposed Solution:** 

1.  Copy missing content from the English source from _**content/en**_ to **_content/vi_**
2.  Try to fix structure follow the [Korean Localization Guide](https://kubernetes.io/ko/docs/contribute/localization_ko/) 

**Page to Update:** https://kubernetes.io/vi/docs/home/

This not meet Minimum required content [https://kubernetes.io/docs/contribute/localization/#minimum-required-content](url) 

https://kubernetes.io/docs/home/ 
![image](https://github.com/kubernetes/website/assets/19403704/0cdd6788-9836-4287-8d5c-0c12df55d2a5)
https://kubernetes.io/vi/docs/home/
![image](https://github.com/kubernetes/website/assets/19403704/df1950ce-2fec-44e4-87f8-c8c22e6ef935)

Update:
3. Localization branch: Can not find localization branch for vi?
We recommend the following branch naming scheme:
dev-<source version>-<language code>.<team milestone>
For example, an approver on a German localization team opens the localization branch dev-1.12-de.1 directly against the kubernetes/website repository, based on the source branch for Kubernetes v1.12.

4. sig-docs-vi-owners &  sig-docs-vi-reviews:
    - huynguyennovem
    - truongnh1992
5. Gig-docs Team plan using AI for translate still have decision yet!
https://github.com/kubernetes/website/discussions/45209
https://github.com/kubernetes/website/issues/45175

**Comment by JaxVN** [comment]
> /language ko
Please help to change /language vi

**Comment by sftim** [comment]
> Copy missing content from the English source from content/en to content/vi

Make sure not to add English text that is marked as Vietnamese.

> Can not find localization branch for vi?

I think Vietnamese works on the _main_ branch.

**Comment by JaxVN** [comment]
@huynguyennovem  & @truongnh1992 
Can you help to review and leave comments about this?

**Comment by JaxVN** [comment]
Also created https://github.com/kubernetes/website/pull/46270 for testing about this!
