### ISSUE TITLE
[ja] Inactive and deprecated interactive tutorial  in "Creating a cluster" page

### ISSUE THREAD

**Issue by yoyoyo-yo** [kubernetes/website#46241]
I cannot use interactive tutorial https://kubernetes.io/ja/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by tamilselvan1102** [comment]
interactive tutorial is outdated. This side menu has to be removed.
/kind bug

**Comment by dipesh-rawat** [comment]
/retitle [ja] Inactive and deprecated interactive tutorial  in "Creating a cluster" page

**Comment by dipesh-rawat** [comment]
@yoyoyo-yo  Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.

**Comment by yoyoyo-yo** [comment]
Thank you for explanation. I see.
