### ISSUE TITLE
Confusing doc on name of object of kind defined by CRD

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#46262]
**This is a Bug Report**

**Problem:**

I wondered what are the restrictions (if any) that Kubernetes imposes on the names of objects of a kind that gets defined by a CustomResourceDefinition. I am not talking about the name of the CRD itself. I tried to find this in the documentation, and couldn't. I asked on the `sig-api-machinery` channel on the Kubernetes Slack, and was referred to https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions . The text there says

> The name of a CRD object must be a valid [DNS subdomain name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names#dns-subdomain-names).

Since a CRD is itself an object, I thought this was clearly talking about the name of the CRD itself (I temporarily forgot that I know that the name of the CRD itself is constrained to be `${resouce}.${apiGroup}`). But I was assured that this text is trying to talk about the objects whose kind is defined by the CRD.

**Proposed Solution:**

Update the cited doc to be clearer.

**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources

**Comment by sftim** [comment]
/triage accepted
/wg api-expression

>Since a CRD is itself an object, I thought this was clearly talking about the name of the CRD itself

Yes, that's right. Both I and @tengqm confirm this; I'm an emeritus tech lead for SIG Docs, and @tengqm is a current tech lead.

>  (I temporarily forgot that I know that the name of the CRD itself is constrained to be ${resouce}.${apiGroup}).

_(sic)_

Would be good to add that detail to the page.
