### ISSUE TITLE
Questions regarding k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by BoeingFever** [kubernetes/website#46269]
hello, I just dropped by on this doc page while studying backing up & restoring ETCD cluster in K8S. There are 2 appearances of this "$ENDPOINT" variables like out of nowhere. 

```
"ETCDCTL_API=3 etcdctl --endpoints $ENDPOINT snapshot save snapshot.db"
```

I don't know when it got defined in what context.

If I just forget the content of $ENDPOINT, what {IP}:{Port} should I put to etcdctl --endpoints flag ? I wish the doc have such details covered.

a bunch of tutorials online told us to check the options the etcd server using by describing the etcd pod, assumed I'm using kubeadm to deploy my K8S cluster.
some of these tutorials told us to look at --advertise-client-urls option, some told us to look at --listen-client-urls option. This is confusing, so which one is the correct one ?

Any answers is appreciated, thank you

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/_

**Comment by thisisharrsh** [comment]
> "ETCDCTL_API=3 etcdctl --endpoints $ENDPOINT snapshot save snapshot.db"

Here, `$ENDPOINT` is an environment variable to be replaced in the actual command, so that it can snapshots the keyspace served by `$ENDPOINT` to the file `snapshot.db`

**Comment by sftim** [comment]
/kind support

This is framed as a request for advice, not a call to improve the existing page.

**Comment by thisisharrsh** [comment]
Since it is a support request, the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.

**Comment by neolit123** [comment]
> Since it is a support request, the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.

/close

try #sig-etcd on k8s slack

**Comment by sftim** [comment]
Just a tweak
/reopen
