### ISSUE TITLE
Improvement for k8s.io/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by huasiy** [kubernetes/website#46277]
I think your installation steps are too complicated, they're not as clear as this [person's instructions](https://github.com/vhive-serverless/vHive/blob/main/docs/quickstart_guide.md). I suggest you take a look and learn from them.

**Comment by thisisharrsh** [comment]
_Page related to the issue: https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/_

**Comment by mengjiao-liu** [comment]
We will update the English site first, and then synchronize the Chinese site.

/language en
