### ISSUE TITLE
[zh] StatefulSet docs missing VolumeClaimTemplates information

### ISSUE THREAD

**Issue by Vallenbo** [kubernetes/website#46294]
volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
          
          
why？the volumeClaimTemplates word?

**Comment by stmcginnis** [comment]
Could you expand on what you're looking for? Is there a specific page that has missing information or needs clarification?

**Comment by Vallenbo** [comment]
There is no information about the volumeClaimTemplates field in the demonstration of the example StatefulSet component （https://kubernetes.io/zh-cn/docs/concepts/workloads/controllers/statefulset/#using-statefulsets）in this link, and it is also incorrect to use it.
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # 必须匹配 .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # 默认值是 1
  minReadySeconds: 10 # 默认值是 0
  template:
    metadata:
      labels:
        app: nginx # 必须匹配 .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi

**Comment by stmcginnis** [comment]
Thanks, that's helpful. It looks like some of the translation updates need to be done yet for ZH. That information is present in the EN docs: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates

/sig docs
/language zh
/area localization

**Comment by stmcginnis** [comment]
/retitle [zh] StatefulSet docs missing VolumeClaimTemplates information

**Comment by tengqm** [comment]
This page was faithfully translated from the English version.
The `volumeClaimTemplates` field is part of the spec for creating a volume.
See the [API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#statefulsetspec-v1-apps).
