### ISSUE TITLE
Glossary page for languages is showing terms from English langauge

### ISSUE THREAD

**Issue by steve-hardman** [kubernetes/website#46310]
**This is a Bug Report**

**Problem:**
I have just seen that the glossary page for differet languages is  also showing terms from the English language instead of showing only terms from the language I selected . I expected  to see only terms specific to the chosen language.

Example Italian page has Englsish terms: https://kubernetes.io/it/docs/reference/glossary/?all=true

**Proposed Solution:**
Update the glossary page to show terms based on the selected language only and not included English

**Page to Update:**
https://kubernetes.io/docs/reference/glossary

**Comment by sftim** [comment]
The website is designed to use the English glossary entry if a localized one is missing.

We could add some styling to make it obvious that an entry is a fallback to English.
/area localization
