### ISSUE TITLE
Some company logos not rendering on "Case Studies" page

### ISSUE THREAD

**Issue by Mohiit70** [kubernetes/website#46321]
On the Kubernetes case studies page (https://kubernetes.io/case-studies/), certain company icons are not visible.

![Screenshot 2024-05-11 142136](https://github.com/kubernetes/website/assets/120316966/57f228c7-1ee9-4d62-b601-a2c8ec87553b)

**Comment by dipesh-rawat** [comment]
/retitle Some company logos not rendering on "Case Studies" page
/kind bug

**Comment by dipesh-rawat** [comment]
We should investigate and fix this.

/priority backlog
/triage accepted
