### ISSUE TITLE
Installing kubeadm

### ISSUE THREAD

**Issue by QQQJoker** [kubernetes/website#46366]
curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf" | sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | sudo tee /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf

10-kubeadm.conf  dose not exist. Is there any other address that can be accessed

**Comment by tamilselvan1102** [comment]
page related to the issue:  https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by tamilselvan1102** [comment]
confirm RELEASE_VERSION has been set

**Comment by tamilselvan1102** [comment]
As per the doc RELEASE_VERSION is "v0.16.2", if you place the value in the url, you can get the config details. So there is no issue in the provided URL.
https://raw.githubusercontent.com/kubernetes/release/v0.16.2/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf

**Comment by stmcginnis** [comment]
There is also DOWNLOAD_DIR in that command. So make sure you do something like:

```sh
export RELEASE_VERSION="v0.16.2"
export DOWNLOAD_DIR="./"

curl -sSL "https://raw.githubusercontent.com/kubernetes/release/${RELEASE_VERSION}/cmd/krel/templates/latest/kubeadm/10-kubeadm.conf" | \
    sed "s:/usr/bin:${DOWNLOAD_DIR}:g" | \
    sudo tee /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
```

**Comment by neolit123** [comment]
/kind support
/close
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
