### ISSUE TITLE
Notes that begin with a bullet appear malformed

### ISSUE THREAD

**Issue by spurin** [kubernetes/website#46371]
**This is a Bug Report**

**Problem:**

Using https://kubernetes.io/docs/concepts/policy/resource-quotas as an example, Note blocks that start with a bullet appear malformed, same outcome in both Chrome and Safari, note the dot over the e characters and incorrect indentation -

<img width="723" alt="image" src="https://github.com/kubernetes/website/assets/850464/957e4cf0-2b53-48fd-ae1f-222e930aa8d7">

**Proposed Solution:**

Let's discuss further, possibly, maybe this can be fixed via hugo, otherwise we could investigate an update to all affected pages.

**Page to Update:**

We should update all notes that meet this criteria, investigate after a proposed solution is agreed.

**Comment by dipesh-rawat** [comment]
It seems that our recent update to align with Docsy-style callouts in https://github.com/kubernetes/website/pull/46232 may have unintentionally caused this issue. There's definitely room for improvement here, and we should address this to ensure the content is displayed properly.

/priority backlog
/triage accepted

**Comment by tamilselvan1102** [comment]
i would like to try
