### ISSUE TITLE
Stale KubeCon 2024 events at kubernetes.io main page

### ISSUE THREAD

**Issue by shurup** [kubernetes/website#46386]
**This is a Bug Report**

**Problem:**
The kubernetes.io main page currently offers to visit KubeCon Europe 2024 (which has passed already) and KubeCon NA 2024 (which is valid). AFAIR, this page has always listed two upcoming KubeCon events in Europe + NA. However:
1. There doesn't seem to be an official date for the next KubeCon Europe yet. 
2. It seems reasonable to promote other locations as well.

According to the [CNCF website](https://www.cncf.io/kubecon-cloudnativecon-events/), the next KubeCon will happen in Hong Kong (21-23 August, 2024). There also will be a KubeCon India in December.

**Proposed Solution:**
I suggest removing the past KubeCon Europe and adding KubeCon Hong Kong and KubeCon India to the page. I'm ready to make a relevant PR if/then this suggestion is approved.

P.S. In the future, I think it would be great to elaborate a better solution with all needed future events listed in some kind of YAML and displayed automatically on the website depending on the current date.

**Page to Update:**
https://kubernetes.io/

**Comment by sftim** [comment]
/triage accepted
/retitle Stale KubeCon 2024 events at kubernetes.io main page

(it's not a bug to list upcoming events; the bug is that the list is stale)

**Comment by afzal442** [comment]
hey @shurup Are you going to follow up with this? Or could I? 😄

**Comment by shurup** [comment]
Hi @afzal442! I just created #46413 to resolve it. However, when this PR is finalised and approved, your help in promoting these changes to other localisations will be much appreciated!
