### ISSUE TITLE
Adding a PR Template for Localization Branches.

### ISSUE THREAD

**Issue by AbdelatifAitBara** [kubernetes/website#46393]
**This is a Feature Request**

**What would you like to be added**

I'm part of the Arabic localization team, and I'd like to add a `pull_request_template.md` file to our branch `dev-1.29-ar.1`.
If other localization teams are amenable to the following template, it would be beneficial to include it in their respective branches as well.

**Why is this needed**

This will have many advantages; I'll mention a few below:

- Efficient Reviews.
- Traceability.
- Visual Context.
- Standardization.

**Comments**

_**This is the PR Template:**_

**Description**
[Provide a clear and concise description of the changes made in this PR.]

**Related Issue**
[Mention the issue number or link to the related issue that this PR addresses.]

**Preview of Edited Page(s)**
[Provide a link to a preview of the edited page(s) for easier review.]

**Checklist**

- [ ]  I have tested the changes locally and they are working as expected.
- [ ]  I have followed the coding style guidelines.
- [ ]  I have squashed my commits into a single commit with a clear commit message.

**Additional Information**
[Provide any additional information or context that might be helpful for the reviewers and approvers.]

**Comment by sftim** [comment]
If you add a pull request template, that localization branch would then not be mergeable into _main_. I don't recommend it.

We could change the main pull request template to mention that extra detail is needed for localization work, and you could then cherry-pick that change. I think that'd be OK.

**Comment by sftim** [comment]
Here's the [existing template](https://github.com/kubernetes/website/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1). What's not right about it?

**Comment by AbdelatifAitBara** [comment]
Sure, we'll be happy to use that one and maybe adding some extra details as you said.
The problem we are facing now is that when we try to open a PR on our branch `dev-1.29-ar.1`, we don't get any template, even the one you mentioned.

**Comment by sftim** [comment]
Do you see something like this when you try to open a PR?

![Screenshot](https://github.com/kubernetes/website/assets/22591623/d3ff00ec-04dd-4c72-961b-d2310181266e)

That's what I saw when I tried.

If not, I wonder why not?

**Comment by AbdelatifAitBara** [comment]
Now yes, perhaps when I opened my first PR, I did not notice it. I apologize for that.

So do you think that we could add some more details to this one? As :

**Related Issue**
[Mention the issue number or link to the related issue that this PR addresses.]

**Preview of Edited Page(s)**
[Provide a link to a preview of the edited page(s) for easier review.]

**Checklist**

- [ ]  I have tested the changes locally and they are working as expected.
- [ ]  I have followed the coding style guidelines.
- [ ]  I have squashed my commits into a single commit with a clear commit message.
