### ISSUE TITLE
Improvement for k8s.io/docs/tasks/tools/install-kubectl-windows/

### ISSUE THREAD

**Issue by SSpormann** [kubernetes/website#46420]
Maybe add some advice to add kubectl to the path

**Comment by tamilselvan1102** [comment]
Page related to the issue: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/

**Comment by tamilselvan1102** [comment]
Are you advising to add kubectl path in system environment variable

**Comment by SSpormann** [comment]
I would suggest to add information, how to add the kubectl path to the environment variables, in the install guide for windows. automation would also be nice, but maybe a bit intrusive.

**Comment by tamilselvan1102** [comment]
it is up to user. if you want to add kubectl path in environment variables, you can add use it.

**Comment by tamilselvan1102** [comment]
if you satisfied, please close the issue

**Comment by niranjandarshann** [comment]
@SSpormann  Due to long time no response on this issue i would like to suggest you please do as suggested  first and then also if you are facing the same issue then raise the new issue or reopen it.

**Comment by niranjandarshann** [comment]
Try to raise the issue with proper description and the brief explanation of the issue that you faced.  Thank you  for your contribution. Keep contributing.
