### ISSUE TITLE
Hindi localization maintainer updates

### ISSUE THREAD

**Issue by divya-mohan0209** [kubernetes/website#46434]
**Message to new contributors: We are not seeking contributions on this issue. This issue is to nominate @dipesh-rawat as one of the leads for the Hindi localization.**

As part of our ongoing efforts to keep the Hindi localization efforts up-to-date, @anubha-v-ardhan and I are pleased to nominate @dipesh-rawat as one of the leads for the Hindi localization. He has proactively triaged issues, reviewed PRs, and submitted changes to the Hindi localization. We're confident that the Hindi localization efforts will benefit from his experience as an approver, reviewer, and contributor to the English website.

In addition to the above, we'd also like to announce that @anubha-v-ardhan will be stepping down as a localization maintainer due to his ongoing commitments. We'd like to take this moment to express our heartfelt gratitude for all his efforts during the bootstrapping process and subsequent maintenance. His contributions have been invaluable to our localisation efforts. 

As this is a named role change, we'll be timeboxing the comments on this issue for one week i.e. 24th May, 2024 EOD anywhere. Once the timeframe has passed and if there are no outstanding concerns from any community members, we will be proceeding with onboarding Dipesh into his new role & offboarding Anubhav from his existing one.

cc: @seokho-son @a-mccarthy @reylejano @natalisucks

**Comment by divya-mohan0209** [comment]
Since the timeboxing period has passed, I'll open a PR to make these changes and linking it to this issue.

**Comment by aj11anuj** [comment]
As PR is already merged for the same
/close
