### ISSUE TITLE
[ja] Translate content/en/docs/reference/glossary/code-contributor.md into Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#46444]
_Note that this issue is for Japanese Speaker_

**This is a Feature Request**

**What would you like to be added**

Translate `content/en/docs/reference/glossary/code-contributor.md` into Japanese

**Why is this needed**

There is no Japanese translation for this page

**Comments**

- File to translate: 
    - https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/code-contributor.md
- Original:
    - https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-code-contributor

日本語に翻訳する際は、以下のドキュメントを参考にしてください。

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

---

/area localization
/language ja
/good-first-issue

**Comment by tamilselvan1102** [comment]
Raised PR, Please review it
