### ISSUE TITLE
here is issue in main menu i can fix 

### ISSUE THREAD

**Issue by KelvinNath** [kubernetes/website#46459]

**Comment by dipesh-rawat** [comment]
@KelvinNath Hi, Could you please share the details on the issue you would like to report or the assistance you require? Kindly provide details in the [description](https://github.com/kubernetes/website/issues/46459#issue-2305351045 )of the issue.

/triage needs-information

**Comment by dipesh-rawat** [comment]
The issue lacks sufficient [details](https://github.com/kubernetes/website/issues/46459#issue-2305351045) for proper triage. Without clear information on what needs fixing, we cannot categorize it as requiring attention. Please feel free to reopen the issue and provide accurate details.

/close not-planned
