### ISSUE TITLE
Improve Accesibility 

### ISSUE THREAD

**Issue by qtop1** [kubernetes/website#46467]
**This is a Feature Request**

Hi, 

I ran the website through an accessibility site called EXPERTE. Most of the pages within the site had 89% rating.
I would like to improve this / increase the rating to make the website even more accessible to users.

<img width="1180" alt="Screenshot 2024-05-20 at 19 17 44" src="https://github.com/kubernetes/website/assets/132226088/a9b7af7d-505f-41c0-badc-757291ab74e8">

I would like be assigned this issue to improve this?

**Comment by dipesh-rawat** [comment]
Thanks for reporting this. Could you please explain why we should consider reports from EXPERTE and the significance of their reports compared to other available tools? Additionally, would you be able to list the specific issues [(here)](https://github.com/kubernetes/website/issues/46467#issue-2306516598) that were identified in EXPERTE's assessment?

/priority awaiting-more-evidence

**Comment by qtop1** [comment]
Why consider reports from EXPERTE and significance in comparison to other available tools:
As EXPERTE is a free accessible site that does the following:
- It is able to crawl the entire site and provide feedback and a rating on the all pages checking accessibility of the navigation,ARIA, Labels, Contrast, Lists, multimedia, internalization and localization.
- It provides the file location of where the pitfalls take place.
- It provides a link to solutions and explanations of errors  specifically from Duque university 


List of most common accessibility issues with website : 
- Buttons not having accessible names. Explanation : When a button does not have an accessible name, screen readers announce it as "button", which makes the attribute unusable by users who need screen readers
- Links not having discernible name. Explanation : link text and alt text when used as links, should have unique and clear which improves the navigation to make the links visible to screen readers
- The not enough of a colour contrast between the background and foreground colours 
- The heading elements are not in sequentially descending order

**Comment by sftim** [comment]
Right now this issue isn't really actionable: someone can't come in and start work on an already-prioritized fix.

If you can identify pages that are obviously problematic, please file an issue for each page that needs to be more accessible. Ideally, validate the gaps with someone who typically uses an accessibility tool, or using an accessibility simulator.
