### ISSUE TITLE
Cloud provider integration blog has a minor version error

### ISSUE THREAD

**Issue by elmiko** [kubernetes/website#46481]
in this sentence

```
The legacy integrations offered compatibility with Azure, AWS, GCE, OpenStack, and vSphere; however for AWS and OpenStack the compiled-in integrations were removed in Kubernetes versions 1.26 and 1.27, respectively.
```
the AWS and OpenStack positions at the end should be swapped, or perhaps clarified. OpenStack was removed in 1.25 (gone in 1.26) and AWS was removed in 1.26 (gone in 1.27).

**Comment by dipesh-rawat** [comment]
_Blog related to the issue:_ https://kubernetes.io/blog/2023/12/14/cloud-provider-integration-changes/
/language en
