### ISSUE TITLE
Wrong ansible group parameter used in "Kubernetes Setup Using Ansible and Vagrant" post

### ISSUE THREAD

**Issue by policyoftruth** [kubernetes/website#46483]
https://github.com/kubernetes/website/blame/02ffb0de210aa5941599088de3e6820b11d55e9d/content/en/blog/_posts/2019-03-15-Kubernetes-setup-using-Ansible-and-Vagrant.md#L125

**Comment by stmcginnis** [comment]
Original description in the title:

I would suggest using groups, not group here and also the append key. No reason to change the users primary group. ...or alternately, update the language that this replaces the users primary group. It doesn't "add".

/retitle Wrong ansible group parameter used in "Kubernetes Setup Using Ansible and Vagrant" post

**Comment by dipesh-rawat** [comment]
_Blog reported in the issue:_ https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
/language en

**Comment by dipesh-rawat** [comment]
For contributors look at this issue, here are our guidelines for updating blog articles:

- Generally, we avoid updating blog articles that are over one year old, unless they are marked as `evergreen: true`.
- If an older article is updated, please ensure to add a visible note indicating the update.
