### ISSUE TITLE
Improvement for k8s.io/docs/concepts/workloads/pods/init-containers/

### ISSUE THREAD

**Issue by jnelson-wasabi** [kubernetes/website#46486]
In the `Detailed Behavior` section, of the `Init Containers` page, there is a statement that says:

`Altering an init container image field is equivalent to restarting the Pod.`

But in the last paragraph on the page it says:

`The Pod will not be restarted when the init container image is changed`

That sounds a bit confusing, maybe even contradictory.
It would be helpful if that was explained a bit more clearly.

**Comment by thisisharrsh** [comment]
_Page related to the issue : https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior_

**Comment by utkarsh-singh1** [comment]
This issue is duplicate as it being raised here -> #38271

**Comment by natalisucks** [comment]
Closing this duplicate issue in favor of #38271 – thanks @jnelson-wasabi for raising and commenting on the other issue!
/close
