### ISSUE TITLE
[fr] Inactive and deprecated interactive tutorial in  "Deploying an application" page

### ISSUE THREAD

**Issue by iamdamienfontaine** [kubernetes/website#46505]
the terminal is blank, nothing is display..

**Comment by iamdamienfontaine** [comment]
Access to XMLHttpRequest at 'https://katacoda.com/api/embed/nonce?protocol=https:&host=kubernetes.io' from origin 'https://kubernetes.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by dipesh-rawat** [comment]
Page reported in issue (based on issue title): https://kubernetes.io/fr/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
/language fr

**Comment by dipesh-rawat** [comment]
/retitle [fr] Inactive and deprecated interactive tutorial in  "Deploying an application" page
/kind bug

**Comment by dipesh-rawat** [comment]
@iamdamienfontaine Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.
