### ISSUE TITLE
Kubernetes documentation search is not working 

### ISSUE THREAD

**Issue by mamadou-barry-projects** [kubernetes/website#46511]
Kubernetes documentation search is not working at all since this morning ! When I launch a request the screen is fixed on "Fetching results..." Do you have the same issue ?
I tried it on both Chrome and Edge, but same issue...
Any ideas guys ? 

![image](https://github.com/kubernetes/website/assets/144568452/d072ee84-79d0-4be2-8fe0-c61de259d758)

**Comment by dipesh-rawat** [comment]
Hello @mamadou-barry-project, I've just tried the website search, and it seems to be working smoothly on my end (screenshot below). Perhaps you could double-check to rule out any potential issues with your local network configuration.

![image](https://github.com/kubernetes/website/assets/13051389/b4631cd0-c97f-4e8c-b4e5-dca41c1f4aac)


/triage not-reproducible

**Comment by mamadou-barry-projects** [comment]
Hello @dipesh-rawat, thank you for taking the time to respond ! I note that everything works well today from my home office! I was linked to a corporate network yesterday, which could explain why I had some troubles.
