### ISSUE TITLE
Two notes in the pod-lifecyle page work not very well

### ISSUE THREAD

**Issue by windsonsea** [kubernetes/website#46524]
[Two notes in the pod-lifecycle page](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) work not well. Not sure how to fix it. This issue has spreaded to the [zh page](https://kubernetes.io/zh-cn/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) currently.

<img width="550" alt="image" src="https://github.com/kubernetes/website/assets/79828097/86ae6525-9cf1-4099-ad8f-ab7907fa777a">

**Comment by sftim** [comment]
For a likely fix, see https://github.com/kubernetes/website/pull/46525
