### ISSUE TITLE
[de] Typo in "Nodes" concept page: 'aufzunehmeb'

### ISSUE THREAD

**Issue by naman-coding** [kubernetes/website#46542]
There is a spelling mistake in the German Kubernetes documentation under:

Konzepte -> Kubernetes Architektur -> Nodes -> Zustand

**Node Condition - Beschreibung**

Incorrect version:
Ready - True wenn der Node in einem guten Zustand und bereit ist Pods aufzunehmen, False wenn der Node nicht in einem guten Zustand ist und nicht bereit ist Pods **aufzunehmeb**

Correct version:
Ready - True wenn der Node in einem guten Zustand und bereit ist Pods aufzunehmen, False wenn der Node nicht in einem guten Zustand ist und nicht bereit ist Pods **aufzunehmen**

**Comment by dipesh-rawat** [comment]
Page reported in issue _(based on the title)_:  https://kubernetes.io/de/docs/concepts/architecture/nodes/
/language de

**Comment by dipesh-rawat** [comment]
/retitle [de] Typo in "Nodes" concept page: 'aufzunehmeb'
/area localization

**Comment by dipesh-rawat** [comment]
Fixed as part of PR #46543

/close
