### ISSUE TITLE
Outdated image in the example yaml file on "Use a Service to Access an Application in a Cluster" page

### ISSUE THREAD

**Issue by tchia04** [kubernetes/website#46550]
After running the kubectl apply command at https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/, "kubectl get all" shows it is having "ImagePullBackOff" error

```
kubectl get all
NAME                               READY   STATUS             RESTARTS   AGE
pod/hello-world-558dfc86f8-8trzs   0/1     ImagePullBackOff   0          14m
pod/hello-world-558dfc86f8-xdp4z   0/1     ImagePullBackOff   0          14m

NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   27d

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world   0/2     2            0           14m

NAME                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-558dfc86f8   2         2         0       14m
```

When I do a describe it says the image is too old and need to be updated 
```
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  30s                default-scheduler  Successfully assigned default/hello-world-558dfc86f8-xdp4z to docker-desktop
  Normal   BackOff    26s (x2 over 27s)  kubelet            Back-off pulling image "gcr.io/google-samples/node-hello:1.0"
  Warning  Failed     26s (x2 over 27s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    13s (x2 over 29s)  kubelet            Pulling image "gcr.io/google-samples/node-hello:1.0"
  Warning  Failed     12s (x2 over 28s)  kubelet            Failed to pull image "gcr.io/google-samples/node-hello:1.0": Error response from daemon: [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of gcr.io/google-samples/node-hello:1.0 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
  Warning  Failed     12s (x2 over 28s)  kubelet            Error: ErrImagePull

```

According to this link https://console.cloud.google.com/gcr/images/google-samples/global/node-hello@sha256:d238d0ab54efb76ec0f7b1da666cefa9b40be59ef34346a761b8adc2dd45459b/details?tab=info, the image was created back in 2016. 

Can we either update all the sample images to use manifest version 2 or find another image that works out of the box?

**Comment by robert-cronin** [comment]
Related issue: https://github.com/kubernetes/website/issues/45961

**Comment by dipesh-rawat** [comment]
_Sample yaml reported in the issue:_ https://github.com/kubernetes/website/blob/main/content/en/examples/service/access/hello-application.yaml

/language en

**Comment by dipesh-rawat** [comment]
It seems that the `gcr.io/google-samples/node-hello:1.0` image may have been removed by Google. We can either update the sample with image's new location _(will need some searching)_, similar to what we’ve done for other tutorials (example [here](https://github.com/kubernetes/website/commit/eda3bed86cbf54b630a94c11fc14d702aab3f3cf)), or find a suitable alternative image to use.

**Comment by robert-cronin** [comment]
I'd love to help out if appropriate, it appears to be a good first issue but I am not sure.

**Comment by dipesh-rawat** [comment]
Would be good to fix this issue with the tutorial.

/priority backlog
/triage accepted
