### ISSUE TITLE
db841f3dd6bf739f697da59d522287a0a61b1850

### ISSUE THREAD

**Issue by Raen123** [kubernetes/website#46552]
https://github.com/LogRocket/redux-logger/commit/4347bd3e2eef0956bfb90def8f32960bed13646d

**Comment by dipesh-rawat** [comment]
/close not-planned

The [current issue](https://github.com/kubernetes/website/issues/46552#issue-2318004590) seems to be similar to spam. If you have any legitimate concerns or problems related to Kubernetes, please feel free to reopen the issue and provide accurate details.
