### ISSUE TITLE
`node.kubernetes.io/exclude-from-external-load-balancers` docs are stale

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#46575]
**This is a Bug Report**

**Problem:**
[Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) mentions a
`ServiceNodeExclusion` feature gate; however, Kubernetes v1.23 onwards don't have such a feature gate.
This is in connection with a label, `node.kubernetes.io/exclude-from-external-load-balancers`.

**Proposed Solution:**
Drop the mention of the feature gate. Reword the description of that label accordingly.

**Page to Update:**
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Additional Information:**
/language en
/kind bug
/priority backlog

**Comment by thisisharrsh** [comment]
I would to like to work on this issue.
/assign

**Comment by thisisharrsh** [comment]
The issue is fixed [here](https://github.com/kubernetes/website/pull/46590).
