### ISSUE TITLE
[feature request] Netlify bot should link to pages changed.

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#4657]
It's great to have @k8sio-netlify-preview-bot leave the preview URL for the staged website as comment: https://github.com/kubernetes/kubernetes.github.io/pull/4655#issuecomment-320484631

It would be much more useful if this actually figured out which pages has changed (it's not difficult to find out the files updated via a few git commands) and link to a list of URLs that's updated.

Can we request this feature from Netlify? (I am assuming `k8sio-netlify-preview-bot` is something Netlify develops. If not, it might be too much work for us.)

**Comment by ahmetb** [comment]
cc: @chenopis

**Comment by chenopis** [comment]
@ahmetb Yes, I agree that this would be ideal. I'll ask Netlify. However, what about the cases when the PR modifies several dozen files, like the ones generated by the auto-generated docs updates?

**Comment by ahmetb** [comment]
Simplest fix I can think of is if its >10, just drop.

More difficult fix I can think of is, use the following struct:

<details>
<summary>click here to expand</summary>
<ul>
<li>hello</li>
<li>world</li>
</ul>
</details>


code for this:

```
<details>
<summary>click here to expand</summary>
<ul>
<li>hello</li>
<li>world</li>
</ul>
</details>
```

**Comment by abitrolly** [comment]
I am also looking into this. Is there anybody from https://github.com/orgs/netlify/people here?

I suppose one more problem is forward mapping from source .md to target .html page.

**Comment by chenopis** [comment]
I think that needs to be handled via URL rewrites or redirects separate from preview. Right now, we are using a less than ideal client side Javascript solution to redirect `anything.md` to `anything/`.

**Comment by abitrolly** [comment]
I think transformation engine should give out build graph for tracing ouputs from sources.

**Comment by chenopis** [comment]
cc @calavera

**Comment by calavera** [comment]
Hey sorry for the late reply.

This is a feature we're considering implementing, but there are a few reasons why we haven't done it yet.

Knowns:

- Netlify knows which files and pages are changed for each deploy.
- Netlify knows which files are html and which are not.

Unknowns:

- Netlify doesn't know if a file deployed has side effects for any page. For example, if you deploy a change in a CSS file, we don't know which files it affects, it could affect a single page or the whole site.

We could send a list of "known" updated pages, as @ahmetb points out, GitHub allows you to use the details tag for expand/collapse comments.

We would not be able to send any information about "unknown" updated pages, like the case of updating CSS, JS, images and so on.

I also know that GitHub is working on more extension points for PR workflows that might report a lot of information in comments, like in this case, but I don't have much more information besides that.

All in all, this is something we'll do at some point, but unfortunately, we don't have a timeline for it yet.

**Comment by ahmetb** [comment]
> Knowns:
> 
> Netlify knows which files and pages are changed for each deploy.
> Netlify knows which files are html and which are not.

@calavera I think these are good enough for us. We mostly don't have patches modifying 10+ files, and would love to have a best-effort bot just posting about which HTMLs are changed.

**Comment by abitrolly** [comment]
Links to HTMLs pages changed sorted by distance from the patch filename and content.

**Comment by chenopis** [comment]
Given that we have no control over Netlify's development priorities or schedule, I think we should just close this Issue since it's not actionable.

**Comment by abitrolly** [comment]
Sad but true.
