### ISSUE TITLE
[ja] Stable Storage section in StatefulSet Japanese page is a little confusing

### ISSUE THREAD

**Issue by ksrnnb** [kubernetes/website#46572]
**This is a Feature Request**

**What would you like to be added**

I think [Stable Storage section](https://kubernetes.io/ja/docs/concepts/workloads/controllers/statefulset/#%E5%AE%89%E5%AE%9A%E3%81%97%E3%81%9F%E3%82%B9%E3%83%88%E3%83%AC%E3%83%BC%E3%82%B8) in Japanese StatefulSet page is a little confusing.

It says that one Persistent Volueme (PV) is created per VolumeClaimTemplate. So, I imagined that if I defined a VolumeClaimTemplate and replicas=3, 1 PV would be created. However, in reality, 1 PV is assigned to each pod, resulting in 3 PVs being created.

> Kubernetesは各VolumeClaimTemplateに対して、1つの[PersistentVolume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/)を作成します。

And in [English page](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage), it doesn't mention Persistent Volume.

> For each VolumeClaimTemplate entry defined in a StatefulSet, each Pod receives one PersistentVolumeClaim.  

I think it is better that Stable Storage section in Japanese is updated.

**Why is this needed**

Stable Storage section in Japanese is a little confusing.

**Comments**

**Comment by tamilselvan1102** [comment]
PV and PVC are 1:1 mapping with pods. so Japanese explanation has to be updated

**Comment by Okabe-Junya** [comment]
Thanks @ksrnnb!!

If you are interested, would you like to work on this issue? If it’s difficult to work, please comment with `/help`.

/area localization
/triage accepted

**Comment by ksrnnb** [comment]
Thanks, I want to try to work on this issue!

/assign
