### ISSUE TITLE
Incorrect glossary tooltip link for 'Container runtime interface'

### ISSUE THREAD

**Issue by pranav-pandey0804** [kubernetes/website#46589]
**This is a Bug Report**

The glossary tooltip for `Container runtime interface` [here](https://kubernetes.io/docs/reference/instrumentation/node-metrics/#summary-api-source) is referencing [this](https://kubernetes.io/docs/concepts/overview/components/#container-runtime) section, instead it should reference to [this](https://kubernetes.io/docs/concepts/architecture/cri/) page.

**Comment by pranav-pandey0804** [comment]
fixed [here](https://github.com/kubernetes/website/pull/46591)

**Comment by dipesh-rawat** [comment]
/retitle Incorrect glossary tooltip link for 'Container runtime interface'
/priority backlog
/triage accepted
