### ISSUE TITLE
Cloud Controller Manager documentation links to itself

### ISSUE THREAD

**Issue by jawnsy** [kubernetes/website#46613]
**This is a Bug Report**

**Problem:**

The documentation for Cloud Controller Manager has a link that is self-referential. The description has a link with description `cloud controller manager`: https://github.com/kubernetes/website/blob/0c26114c6f2bfc89a6fb31e9fc3ec2c4daa092d1/content/en/docs/reference/glossary/cloud-controller-manager.md?plain=1#L15

However, this is the URL if the current page: https://github.com/kubernetes/website/blob/0c26114c6f2bfc89a6fb31e9fc3ec2c4daa092d1/content/en/docs/reference/glossary/cloud-controller-manager.md?plain=1#L5

**Proposed Solution:**

Remove the link, or link it somewhere useful.

**Page to Update:**

https://kubernetes.io/docs/concepts/architecture/cloud-controller/

**Additional information:**

* I'm not sure if this serves a purpose of boosting SEO or similar, but as a user/reader interested in this component, it wasn't helpful for me, so I want to make it more helpful :)
* I'd also be interested in contributing a pull request for this change

**Comment by sftim** [comment]
/priority backlog
/kind cleanup
/triage accepted


If we move the full link after the `<!--more-->`, that should help.

---

We [added](https://github.com/kubernetes/website/issues/39234#issuecomment-1416825540) a diagram to 
https://kubernetes.io/docs/concepts/architecture/ a while back. I'd really like to see https://kubernetes.io/docs/concepts/overview/components/ simplified to just outline what each component does, enough to help a beginner, and for the detailed explanations to move into https://kubernetes.io/docs/concepts/overview/architecture/

If we do that, https://kubernetes.io/docs/concepts/overview/architecture/ is also the right place to explain the cloud controller manager, and we can reword https://kubernetes.io/docs/concepts/architecture/cloud-controller/ accordingly.

If someone has capacity to send in PRs to get us there, this bigger change is what [I think] is really needed.

**Comment by afzal442** [comment]
Looks like @jawnsy is already into it.

/unassign

**Comment by jawnsy** [comment]
@afzal442 Feel free to take it if you're interested! Thank you so much 😁

**Comment by afzal442** [comment]
Thanks @jawnsy I am currently huddling with this following PR 
* https://github.com/kubernetes/website/pull/46635

**Comment by sftim** [comment]
Fixed in https://github.com/kubernetes/website/pull/46823

/close
