### ISSUE TITLE
Manage HugePages - wrong Kubernetes version in FEATURE STATE [stable] top line

### ISSUE THREAD

**Issue by antaloala** [kubernetes/website#46654]
Hi,
In k8s v1.30 documentation page [https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/](https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/), in the top FEATURE STATE line, the indicated Kubernetes version where this feature reached "stable/GA" is said to be 1.30; if you check which it is in k8s v1.29 doc page: it says 1.29 .... for 1.28 doc it says GA/stable was reached in 1.28 ... and so for the previous releases ...

It looks there is a wrong moving version for this, pointing to the current one "owning" the doc page. According to [https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/) it should say:

   FEATURE STATE: Kubernetes v1.**14** [stable]

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/
/language en
/kind bug

**Comment by dipesh-rawat** [comment]
We should correct this discrepancy in the feature state.

/priority backlog
/triage accepted
