### ISSUE TITLE
Documentation : Bad information about restartPolicy

### ISSUE THREAD

**Issue by felixleo22** [kubernetes/website#46668]
Hi,

I read this issue https://github.com/kubernetes/kubernetes/issues/24725, and I found a section in the documentation that explains that there are other possible values for the restartOnly spec (Always, OnFailure, and Never).

Here's the link where I found this information :
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy

I haven't seen any other place.

I hope this helps.

**Comment by sftim** [comment]
@felixleo22 where do you think the **bad** information is? Pods can indeed have several values for `restartPolicy`.

**Comment by amolmote** [comment]
Hi @felixleo22 , the first link that u have mentioned about the issue which was related to the deployment. I indeed, deployment does not support restartPolicy `Never` it only supports `Always`

And this link, [restart-policy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy ) having the details about the pod which supports all the below mentioned values.
```
The Pod "demo" is invalid: spec.restartPolicy: Unsupported value: "onFailure": supported values: "Always", "OnFailure", "Never"
```
I think, we are good to close this issue.

**Comment by marcelovani** [comment]
@felixleo22 I am confused why the issue was closed without a fix to the documentation.

**Comment by SleepyDeb** [comment]
Please.... midnight here preparing ckad exam and uncovering that the documentation is broken.... ahi D:
