### ISSUE TITLE
使用 Service 暴露你的应用

### ISSUE THREAD

**Issue by chinaskills** [kubernetes/website#46697]

**Comment by thisisharrsh** [comment]
Please update the issue title and https://github.com/kubernetes/website/issues/46697#issue-2337692770 in primary language(English).

**Comment by dipesh-rawat** [comment]
The issue lacks sufficient [description (here) ](https://github.com/kubernetes/website/issues/46697#issue-2337692770)for proper triage. Without clear information on what needs fixing, we cannot categorize it as requiring attention. Please feel free to reopen the issue and provide accurate details.

/close not-planned
