### ISSUE TITLE
Improvement for k8s.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

### ISSUE THREAD

**Issue by PoonamSaraogi** [kubernetes/website#46747]
etcdutl --data-dir <data-dir-location> snapshot restore snapshot.db

this command is wrongly written, could be typo error

**Comment by dipesh-rawat** [comment]
I think the existing content is correct.

Reference:

https://etcd.io/docs/v3.6/op-guide/recovery/#restoring-a-cluster
https://github.com/etcd-io/etcd/blob/main/etcdutl/README.md

**Comment by stmcginnis** [comment]
Yep, the existing one is correct. This can be closed.

Maybe the etcd team needs to do some more advertising on the newer cli. Though maybe we should list both the old and new for awhile until it's more well known so folks aren't spending so much time filing issues and PR for the same thing every few days. :D

**Comment by kundan2707** [comment]
Existing documentation id correct and it can be closed.
