### ISSUE TITLE
etcd task page unclear on difference between `etcdctl` and `etcdutl`

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#46757]
**This is a Bug Report**

**Problem:**
[Operating etcd clusters for Kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/) mentions `etcdctl` ~(which is deprecated)~ quite a lot before the first mention of `etcdutl`.

**Proposed Solution:**
- Mention early on that there are two tools
- Where a use of `etcdctl` is deprecated in favor of `etcdutl`, repeat the equivalent change from https://github.com/kubernetes/website/pull/46748

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/

**Additional Information:**
/sig etcd

**Comment by sftim** [comment]
Help is very welcome. Would you like any advice @robert-cronin ?

**Comment by sftim** [comment]
@robert-cronin I think you're right.

General guidance:
- https://k8s.dev/docs/
- https://kubernetes.io/docs/contribute/docs/

I'll edit the issue description.

**Comment by robert-cronin** [comment]
> @robert-cronin I think you're right.
> 
> General guidance:
> 
> * https://k8s.dev/docs/
> * https://kubernetes.io/docs/contribute/docs/
> 
> I'll edit the issue description.

Thank you for the guidance, @sftim.

I have opened a pull request to add a section clarifying the difference between etcdctl and etcdutl. Please feel free to review it and suggest any changes.
