### ISSUE TITLE
Add a note that after a cluster upgrade using kubeadm, backup files will need to be cleared manually.

### ISSUE THREAD

**Issue by davidwtf** [kubernetes/website#46766]
After the upgrade, the backup directory `/etc/kubernetes/tmp` will remain. 
The ETCD backup could use several hundred MB to several GB of disk storage.
If we don't clean up the backups, the storage may become full after several upgrades.
Users may need to clean it up manually.

You can find more information about this issue here: https://github.com/kubernetes/kubernetes/issues/125357

**Comment by tamilselvan1102** [comment]
page to be updated: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#recovering-from-a-failure-state

**Comment by divya-mohan0209** [comment]
/retitle Add a note that after a cluster upgrade using kubeadm, backup files will need to be cleared manually.

**Comment by tamilselvan1102** [comment]
The following pages mentioned, if do setting of [--cleanup-tmp-dir] flag, will cleanup the "/etc/kubernetes/tmp" directory.
Is it relevant to this issue?

https://kubernetes.io/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node/#options
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/#options

**Comment by tamilselvan1102** [comment]
i would like to work on it.
/assign

**Comment by neolit123** [comment]
> The following pages mentioned, if do setting of [--cleanup-tmp-dir] flag, will cleanup the "/etc/kubernetes/tmp" directory. Is it relevant to this issue?
> 
> https://kubernetes.io/docs/reference/setup-tools/kubeadm/generated/kubeadm_reset_phase_cleanup-node/#options https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/#options

reset does clean it, but upgrade is another place to mention it.

> page to be updated: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#recovering-from-a-failure-state

just put a note here.

**Comment by neolit123** [comment]
@tamilselvan1102 please include `fixes #46766` in the PR description to close this issue.

**Comment by tamilselvan1102** [comment]
Raised PR, Please review it.
