### ISSUE TITLE
kubeadm: add note about a bug in the PublicKeysECDSA feature gate

### ISSUE THREAD

**Issue by neolit123** [kubernetes/website#46799]
in this PR we changed the main branch with a certain kubeadm note:
https://github.com/kubernetes/website/pull/46795

we need to do the same now for the dev-1.31 branch and a slightly different note.
please `/assign` yourself if you want to work on this ticket.

## steps for dev-1.31

- create a new branch from the `dev-1.31` branch.
- modify this page:
`content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md`
- include this note in a new sentence:
```
Kubernetes versions before v1.31 had a bug where keys in generated kubeconfig files were set use RSA,
even when you had enabled the `PublicKeysECDSA` feature gate.
```
in the description for `PublicKeysECDSA`
- send a PR and type `xref #46799` in its description, make sure it targets the correct branch

## steps for release-1.29, release-1.28, release-1.27 to release-1.26

- create a new branch from the `release-x.xx` branch that you want to target.
- modify this page:
`content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md`
- include this note in a new sentence:
```
Kubernetes {{< skew currentVersion >}} has a bug where keys in generated kubeconfig files are set use RSA
despite the feature gate being enabled.
```
in the description for `PublicKeysECDSA`
- send a PR and type `xref #46799` in its description, make sure it targets the correct branch

notify us that the PRs are ready with a comment.

/help
/sig cluster-lifecycle

**Comment by neolit123** [comment]
cc @sftim please apply edits to the description if needed.
xref https://github.com/kubernetes/website/pull/46795#pullrequestreview-2112516063

also note that this is not a high priority feature for kubeadm so the backport part maybe can be skipped.

**Comment by sftim** [comment]
For releases that have already happened, these changes should actually be made to `release-*` not `dev-*`.

**Comment by sftim** [comment]
@neolit123 I will
/remove-good-first-issue

because the PR description may confuse a newcomer. Help is still welcome.

**Comment by neolit123** [comment]
> For releases that have already happened, these changes should actually be made to `release-*` not `dev-*`.

updated the description.
..well that already confused me.

@SequoiaGod  seems branches need to be updated.

**Comment by SequoiaGod** [comment]
> > For releases that have already happened, these changes should actually be made to `release-*` not `dev-*`.
> 
> updated the description. ..well that already confused me.
> 
> @SequoiaGod seems branches need to be updated.

Yup, thanks for your help. I will update my code later today.

**Comment by sftim** [comment]
```diff
-steps for release-1.29, dev-1.28, dev-1.27 to dev-1.26
+steps for release-1.26 to release-1.29
```
I think

**Comment by JunYanBJSS** [comment]
Got it, will amend it later. Also, quick question "steps for dev-1.31" is correct right?

**Comment by SequoiaGod** [comment]
@neolit123 Hi mate, PRs have already opened for review. Thank you so much for your supporting.

**Comment by neolit123** [comment]
> @neolit123 Hi mate, PRs have already opened for review. Thank you so much for your supporting.

thanks added LGTM. the docs owners must approve your PRs.

**Comment by neolit123** [comment]
all PRs merged. please reopen if needed.
thanks
