### ISSUE TITLE
Doc for `apiserver_request_duration_seconds` removed, but metric is still in code

### ISSUE THREAD

**Issue by lorenzofelletti** [kubernetes/website#46818]
**This is a Bug Report**

**Problem:**
[This commit](https://github.com/kubernetes/website/commit/991862f0120ed2f73a288da00b111b4b1f709cf3) removed `apiserver_request_duration_seconds` metric from the documented metrics for Kubernetes v1.30, but the metric is still collected for the API server (ref: [here](https://github.com/kubernetes/kubernetes/blob/eb6840928df59bf8203b1eda839ccd3da68fb37d/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L99) and [here](https://github.com/kubernetes/kubernetes/blob/eb6840928df59bf8203b1eda839ccd3da68fb37d/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L571)).

**Proposed Solution:**
Reinstate the documentation for such metric.

**Page to Update:**
https://kubernetes.io/docs/reference/instrumentation/metrics/#metrics-v1-30

Kubernetes Version: v1.30

**Comment by mengjiao-liu** [comment]
After I re-ran the script, some metrics were indeed missing (not just metrics `apiserver_request_duration_seconds`), it was a problem with the generated script, I will take a closer look.
