### ISSUE TITLE
Enhance `kubectl set image` documentation: Improve summary, add usage scenarios, and compare with `kubectl edit`

### ISSUE THREAD

**Issue by agowa** [kubernetes/website#46813]
Hi, currently the documentations only have little information regarding `kubectl set image`. It would be great if it could be extended with at least a quick summary and a comparison to using `kubectl edit` (or `kubectl apply`) in order to modify the image. E.g. upgrade nginx version.

Edit: This page: https://kubernetes.io/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image/

**Comment by dipesh-rawat** [comment]
/retitle Enhance `kubectl set image` documentation: Improve summary, add usage scenarios, and compare with `kubectl edit`
/language en

**Comment by dipesh-rawat** [comment]
@agowa Could you share the page(s) URL where you'd like to see these improvements added?

**Comment by tengqm** [comment]
> /retitle Enhance `kubectl set image` documentation: Improve summary, add usage scenarios, and compare with `kubectl edit` /language en

Why do we keep changing issue/pr titles? Do we have a guideline on how to format the title of an issue or a PR? The revised title is so long. Is this change really needed?

I'm raising this question because I've been driven crazy by this kind of changes lately. When a PR or an issue has a title change, my Outlook email client cannot correctly identify "conversations" of discussion threads after the change. Each single response to the issue/PR then become a new email in my inbox. When the title was not changed, the email client can easily organize the discussions into neat conversations. I can quickly browse throw the so many notifications and kill them in batch.

**Comment by agowa** [comment]
https://kubernetes.io/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image/

**Comment by Ritikaa96** [comment]
The page seems to have enough information as its basic task is to set/update the image on existing resource. 
Adding the difference between the kubectl edit and kubectl apply might be better placed some where both are mentioned like [here](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment)

**Comment by agowa** [comment]
Fair, but then that page should be at least referenced from the https://kubernetes.io/docs/reference/kubectl/generated/kubectl_set/kubectl_set_image/ page then. Mainly because "kubectl set image" has the better SEO and people looking for e.g. "how to change image using kubectl" will find that one first (it's literally the first search result for me after all of the ads right now).
And thereby someone will never know about the other options and because they're not equal to each other there should be at least a mention where people are inevitably going to look for it...

**Comment by tengqm** [comment]
@agowa The page you cited is generated from the upstream source code (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/set/set_image.go#L81-L99). If you have any suggestions to improve the `kubectl set image` (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/set/set_image.go#L114) help message, you can propose an improvement to k/k repo or at least file an issue for this purpose. We won't fix the generated pages.
/close
