### ISSUE TITLE
JSONPath Support

### ISSUE THREAD

**Issue by VipinVKKariyad** [kubernetes/website#46848]
we need to get exact path of a sub object so need to add this command in documentation or need a method for json path 
```
kubectl get nodes -o=json | jq -r '
def traverse(level):
    . as $in
    | if type == "object" then
        to_entries | map(
            "##" + (level | tostring) + " " + .key + ": " + (
                if .value | type == "object" or type == "array" then
                    "\n" + (.value | traverse(level + 1))
                else
                    .value | tostring
                end
            )
        ) | .[]
    elif type == "array" then
        map("##" + (level | tostring) + " " + (. | tostring) + (
            if type == "object" or type == "array" then
                "\n" + (. | traverse(level + 1))
            else
                ""
            end
        )) | .[]
    else
        "##" + (level | tostring) + " " + (. | tostring)
    end;
.items[] | traverse(1)'
```
op will be

##1 status: 
##2 nodeInfo: 
##3 osImage: Ubuntu 20.04.5 LTS

**Comment by dipesh-rawat** [comment]
Hi @VipinVKKariyad Could you please provide the URL of the page in the issue where you are suggesting an improvement?

/triage needs-information

**Comment by Ritikaa96** [comment]
> we need to get exact path of a sub object so need to add this command in documentation or need a method for json path
> 
> ```
> kubectl get nodes -o=json | jq -r '
> def traverse(level):
>     . as $in
>     | if type == "object" then
>         to_entries | map(
>             "##" + (level | tostring) + " " + .key + ": " + (
>                 if .value | type == "object" or type == "array" then
>                     "\n" + (.value | traverse(level + 1))
>                 else
>                     .value | tostring
>                 end
>             )
>         ) | .[]
>     elif type == "array" then
>         map("##" + (level | tostring) + " " + (. | tostring) + (
>             if type == "object" or type == "array" then
>                 "\n" + (. | traverse(level + 1))
>             else
>                 ""
>             end
>         )) | .[]
>     else
>         "##" + (level | tostring) + " " + (. | tostring)
>     end;
> .items[] | traverse(1)'
> ```
> 
> op will be
> 
> ##1 status: ##2 nodeInfo: ##3 osImage: Ubuntu 20.04.5 LTS

I do not understand the link mentioned in ##1, ##2, ##3 seems like mistakenly added.

**Comment by T-Lakshmi** [comment]
@VipinVKKariyad,
Are you still facing this issue? if yes, please provide above requested details which are necessary to help you in resolving.
Please close the issue if it already resolved.

**Comment by T-Lakshmi** [comment]
Hello @VipinVKKariyad,

As we not hear from you since long, iam closing this issue. Feel free to reopen if you are still observing this issue and provide requested details.

/close
