### ISSUE TITLE
Integrate Dark Mode in the Frontend

### ISSUE THREAD

**Issue by barmanroys** [kubernetes/website#46844]
**This is a Feature Request**

**What would you like to be added**
Dark Mode, like, for example, the ray documentation. 

**Why is this needed**
Comfort of the eyes, specifically those having chronic migraine. For me personally, every app, website, and IDE I use, are in permanent dark modes. It enables a reader to read longer and more comfortably without straining their eyes.

**Comment by dipesh-rawat** [comment]
Looks like duplicate of an issue we already have #25061

/triage duplicate

**Comment by dipesh-rawat** [comment]
Also, see #37444

/area web-development

**Comment by sftim** [comment]
Help with existing issues https://github.com/kubernetes/website/issues/37444 and #25061 is welcome!

**Comment by sftim** [comment]
/close not-planned

This request duplicates existing issues.
