### ISSUE TITLE
Not able to run the website locally using Hugo

### ISSUE THREAD

**Issue by arujjval** [kubernetes/website#46864]
**This is a Bug Report**

**Problem:** I tried running the website locally but got this error
![Screenshot from 2024-06-18 16-16-24](https://github.com/kubernetes/website/assets/106719640/c2700b3f-d1e6-4659-a595-7bcb37daca51)
I followed the steps given in the readme file and have followed all the steps mentioned there (for running locally). It is working fine as a container in Docker but facing an error when running locally. 

I am running on Ubuntu 22.04 LTS

**Comment by dipesh-rawat** [comment]
Looks like a request for help in its current form.
/kind support

**Comment by dipesh-rawat** [comment]
Based on the [screenshot](https://github.com/kubernetes/website/issues/46864#issue-2359555372) provided I can see that the current Hugo version is `0.127.0`, while the [README](https://github.com/kubernetes/website/blob/main/README.md?plain=1#L24) advises ensuring compatibility with the version specified in  [netlify.toml](https://github.com/kubernetes/website/blob/main/netlify.toml#L11) file.

> Note
Make sure to install the Hugo extended version specified by the HUGO_VERSION environment variable in the [netlify.toml](https://github.com/kubernetes/website/blob/main/netlify.toml#L11) file.

You could try using the same Hugo version 0.121.2 as specified in [netlify.toml](https://github.com/kubernetes/website/blob/main/netlify.toml#L11)

If you're interested in testing an upgrade for Hugo, you can do so by running `make container-image` before `make container-serve`.
