### ISSUE TITLE
kubeadm upgrade docs

### ISSUE THREAD

**Issue by mhausenblas** [kubernetes/website#4689]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

When https://github.com/kubernetes/kubernetes/pull/48899 lands we want docs for it.

**Proposed Solution:**

Write some end-user facing docs/walkthroughs for `kubeadm upgrade`.

**Page to Update:**
New page? Not sure where to put it.

**Comment by luxas** [comment]
Sounds good to me to do this proactively! :)
I'd be happy with having you write a WIP PR for this early on based on some runs with a binary from my fork (I can provide one easily for you)

The sooner we start to write docs, the better. Often this is left to the last minute, which is a bad habit.

**Comment by mhausenblas** [comment]
Awesome, yes, let's do it. Please advise for a starting point @luxas …

**Comment by castrojo** [comment]
The first step has the user curling a kubeadm binary. I asked if just waiting for the kubernetes repo to be updated to 1.8 and running the packaged version would work: 

```
luxas: Problem statement: an `apt-get upgrade` before pulls down a new kubelet for an old API, which is not supported
jorge: that sounds like it would actually break
luxas: Yes
luxas: hence we need to do CLI only first, upgrade the control plane, and then upgrade the node
```

Perhaps we should be more explicit in telling the user that they need to get the kubeadm binary out of band first and NOT just do an apt update/dist-upgrade even though kubeadm 1.8 will be sitting in the repo.

**Comment by luxas** [comment]
@castrojo Feel free to improve the wording of the guide :)
