### ISSUE TITLE
Improvement for k8s.io/docs/concepts/policy/limit-range/

### ISSUE THREAD

**Issue by vsagar100** [kubernetes/website#46899]
LimitRange is namespace specific, however the given example does not contain namespace attribute. I know it will pick default namespace however mentioning it will be more clear & helpful for beginners like me.

**Comment by sftim** [comment]
We can also add a comment into the manifest about the namespace being implied. Using a comment helps people test things out in namespaces other than `default`.

**Comment by Shubhdeep02** [comment]
Hey @vsagar100 I think It's already mentioned clearly about the constraints and the steps of using it in <code style="name_color">LimitRange</code>
object, and you can also take help from the docs for more understanding:
_https://kubernetes.io/docs/tasks/administer-cluster/namespaces/_

**Comment by vsagar100** [comment]
> Hey @vsagar100 I think It's already mentioned clearly about the constraints and the steps of using it in `LimitRange` object, and you can also take help from the docs for more understanding: _https://kubernetes.io/docs/tasks/administer-cluster/namespaces/_

@Shubhdeep02, I am talking about the below page. It might have been mentioned on the page you mentioned. I was following LimitRange page but found it missing hence requested update.
Page Link: https://kubernetes.io/docs/concepts/policy/limit-range/

**Comment by T-Lakshmi** [comment]
PR working on this #46950

**Comment by subhals** [comment]
@T-Lakshmi Thank you! Please feel free to pull since I am not working on this.

**Comment by T-Lakshmi** [comment]
@subhals,
Thanks for the confirmation, i will soon open PR for this.

**Comment by T-Lakshmi** [comment]
PR Raised #48766
