### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/manage-compute-resources-container/

### ISSUE THREAD

**Issue by chrissound** [kubernetes/website#4693]
> The spec.containers[].resources.limits.cpu is converted to its millicore value, multiplied by 100000, and then divided by 1000.

**Comment by radhikapc** [comment]
@chrissound : The description does not state the issue with the given sentence. Please provide more information to take it forward.

**Comment by chrissound** [comment]
Surely the value would just be multiplied by 100 rather than `multiplied by 100000, and then divided by 1000`?

`(x * 100000) / 1000` is equal to `x * 100`.

**Comment by zacharysarah** [comment]
@vishh Heya. 👋  Can you shed some light on [pod resources](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-limits-are-run), specifically the math here:

> The `spec.containers[].resources.limits.cpu` is converted to its millicore value, multiplied by 100000, and then divided by 1000. 

Is there a reason why we don't simply say, for example:

> The `spec.containers[].resources.limits.cpu` is converted to its millicore value and multiplied by 100.

Thanks in advance!

**Comment by vishh** [comment]
@zacharysarah Just clarified in the PR - https://github.com/kubernetes/kubernetes.github.io/pull/4952/files#r133273014

**Comment by stewart-yu** [comment]
That 's easy. I'm thinking you should understand the relationship between  --cpu-quota   and  --cpu-period parameters.Besides, the meaning of millicore.May be helps to  you@chrissound

**Comment by stewart-yu** [comment]
"multiplied by 100000, and then divided by 1000" can explain the compute process of result.Just "multiplied by 100" may be confused.@radhikapc @zacharysarah @vishh

**Comment by tengqm** [comment]
I think this is safe to close now.
