### ISSUE TITLE
fault content in the webpage 网络策略 

### ISSUE THREAD

**Issue by eshujqg** [kubernetes/website#46957]
There is minor fault in the webpage 网络策略 :
https://kubernetes.io/zh-cn/docs/concepts/services-networking/network-policies/#targeting-multiple-namespaces-by-label
The indent is wrong
  egress:
   - to:
     - namespaceSelector:
       matchExpressions:
       - key: namespace
         operator: In
         values: ["frontend", "backend"]

This fault only exist in the chinese version of this page, it should be corrected as english version as below:
  egress:
  - to:
    - namespaceSelector:
        matchExpressions:
        - key: namespace
          operator: In
          values: ["frontend", "backend"]

**Comment by tengqm** [comment]
Why would you say it is "wrong"?
List items can be indented in either way.

**Comment by eshujqg** [comment]
I created two versions yaml, 1.yaml for chinese version and 2.yaml for english version:

controlplane $ diff 1.yaml 2.yaml 
12,17c12,17
<    - to:
<      - namespaceSelector:
<        matchExpressions:
<        - key: namespace
<          operator: In
<          values: ["frontend", "backend"]
---
>   - to:
>     - namespaceSelector:
>         matchExpressions:
>         - key: namespace
>           operator: In
>           values: ["frontend", "backend"]
controlplane $ k apply -f 1.yaml 
Error from server (BadRequest): error when creating "1.yaml": NetworkPolicy in version "v1" cannot be handled as a NetworkPolicy: strict decoding error: unknown field "spec.egress[0].to[0].matchExpressions"
controlplane $ k apply -f 2.yaml 
networkpolicy.networking.k8s.io/egress-namespaces created
controlplane $

So matchExpressions should be indented. Meanwhile, although one whitespace indent is ok in yaml, it's good to use two whitespace indent as habits of most people.

**Comment by thisisharrsh** [comment]
I agree with the observations regarding the indentation in the Chinese version of the documentation and think it needs a fix.

**Comment by tengqm** [comment]
@eshujqg Please paste your snippet into a code block, i.e.

````
```
your yaml here
```
````

I can guess what you are suggesting here, but need a confirmation.

**Comment by tengqm** [comment]
Please check if #46961 is the fix you are suggesting. @eshujqg

**Comment by eshujqg** [comment]
@tengqm Yes, I think it's fixed, thank you!
