### ISSUE TITLE
[ja] Translate docs/concepts/workloads/autoscaling.md into Japanese 

### ISSUE THREAD

**Issue by Kei-Ta** [kubernetes/website#46962]
**This is a Feature Request**

**What would you like to be added**
Translate docs/concepts/workloads/autoscaling.md

**Why is this needed**
There is no Japanese translation for this page

**Comments**
/area localization
/language ja
/assign

**Comment by Okabe-Junya** [comment]
/triage duplicate

#46663 と重複していそうですね。。
