### ISSUE TITLE
[es] localize `concepts/extend-kubernetes/_index.md` to Spanish

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/website#46968]
**This is a Feature Request**

**What would you like to be added**
Localize `concepts/extend-kubernetes/_index.md` to Spanish

**Why is this needed**
There is no Spanish localization for this file.

**Comments**

The Spanish translation team would like to facilitate your contribution journey; for any doubt, please participate in the weekly meetings or post a question in the Kubernetes slack channel [#kubernetes-docs-es](https://kubernetes.slack.com/archives/CH7GB2E3B)

We also encourage new contributors to participate in their native speaking language.

/triage accepted
/kind feature
/language es
/sig docs
/area localization

**Comment by jossemarGT** [comment]
👋  Hi, I'd like to work on this issue.

**Comment by krol3** [comment]
closing in favor of https://github.com/kubernetes/website/issues/48070
 
/close
