### ISSUE TITLE
The Docker image registry.k8s.io/test-webserver cannot be pulled

### ISSUE THREAD

**Issue by xpx1** [kubernetes/website#46999]
registry.k8s.io/test-webserver 这个docke镜像拉取不到

**Comment by mengjiao-liu** [comment]
I can pull this mirror image. Perhaps your network needs to set up a proxy so that it can access the registry.k8s.io image repository? @xpx1

**Comment by xpx1** [comment]
ok ,thank you
&nbsp;


xpx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mengjiao ***@***.***&gt;; 
发送时间: 2024年6月28日(星期五) 下午3:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kubernetes/website] Issue with k8s.io/zh-cn/docs/concepts/storage/volumes/ (Issue #46999)















***@***.***

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***和&gt;

**Comment by T-Lakshmi** [comment]
@xpx1,

> ok ,thank you
&nbsp;

With this response i am your issue has resolved and closing this issue.
Feel free to reopen with more details in case you still facing this issue.

**Comment by T-Lakshmi** [comment]
/retitle The Docker image registry.k8s.io/test-webserver cannot be pulled
/kind support
