### ISSUE TITLE
Add “watch” to glossary

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#47015]
**This is a Feature Request**

**What would you like to be added**
Update the [glossary](https://kubernetes.io/docs/reference/glossary/?fundamental=true&architecture=true) to include an explanation of “watch”.

**Why is this needed**
The **watch** verb (and actually **watchcollection** as well) is K8s-specific jargon. We should help readers understand it.

**Comments**
Extra credit for also using the new term in existing pages, using a [glossary short code](https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#glossary).

/kind feature
/wg api-expression

**Comment by Ritikaa96** [comment]
Hi @sftim added PR: https://github.com/kubernetes/website/pull/47067 for this issue. PTAL

**Comment by sftim** [comment]
I'm happy for any reviewer (for English) to take a look there.
