### ISSUE TITLE
[Unclear] example: Deploying Cassandra with a StatefulSet

### ISSUE THREAD

**Issue by brianjester** [kubernetes/website#47039]
When running this command:

```shell
grace=$(kubectl get pod cassandra-0 -o=jsonpath='{.spec.terminationGracePeriodSeconds}') \
  && kubectl delete statefulset -l app=cassandra \
  && echo "Sleeping ${grace} seconds" 1>&2 \
  && sleep $grace \
  && kubectl delete persistentvolumeclaim -l app=cassandra
```

The grace period it was going to sleep was 1800s (30m), so after all resources were deleted (about 5-6s), I hit Ctrl-C, then manually ran the line after the sleep:

kubectl delete persistentvolumeclaim -l app=cassandra

Recommend adding a note to avoid having the student wait 30m for a command to finish that might only take a few seconds.

**Comment by T-Lakshmi** [comment]
Related page: https://kubernetes.io/docs/tutorials/stateful-application/cassandra/#cleaning-up
/language en

**Comment by sftim** [comment]
I think we can improve the advice, _or_ change the grace period to be quite a bit shorter. Not sure which is better.

**Comment by sftim** [comment]
/triage accepted
either way

**Comment by sftim** [comment]
/retitle [Unclear] example: Deploying Cassandra with a StatefulSet

**Comment by thisisharrsh** [comment]
> change the grace period to be quite a bit shorter

I have tried to reproduce the issue with a grace period of 300 seconds. And I observed that all my related resources were deleted in under 10 seconds.  
It will be better if we reduce the `terminationGracePeriodSeconds: 1800`  to some shorter value like `300` or `500`.

**Comment by thisisharrsh** [comment]
I would like to work on this issue. 

/assign 
/sig apps
/sig storage
