### ISSUE TITLE
Improvement for k8s.io/docs/tasks/job/automated-tasks-with-cron-jobs/

### ISSUE THREAD

**Issue by RajashreeRoy** [kubernetes/website#47049]
Please add where to keep the .sh file .

**Comment by dipesh-rawat** [comment]
Page reported in issue _(based on the title)_: https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/
/language en

**Comment by thisisharrsh** [comment]
In a typical setup, we should keep the.sh files in a location that is accessible to the container running the cron-jobs.

**Comment by thisisharrsh** [comment]
We can keep the`.sh` files inside the container image, or we can also mount them into the container at runtime.

**Comment by thisisharrsh** [comment]
We can keep the`.sh` files inside the container image, or we can also mount them into the container at runtime. 

/sig docs

**Comment by RajashreeRoy** [comment]
ok thank you .
