### ISSUE TITLE
The Kubernetes API documentation page contains a broken links

### ISSUE THREAD

**Issue by thecooldrop** [kubernetes/website#47068]
As per title the following page https://kubernetes.io/docs/concepts/overview/kubernetes-api/ contains a broken link to **discovery document**.

See highlight here:

https://kubernetes.io/docs/concepts/overview/kubernetes-api/#:~:text=The%20discovery%20document%20for%20the%20built%2Din%20resources%20can%20be%20found%20in%20the%20Kubernetes%20GitHub%20repository.

**Comment by Adarsh-verma-14** [comment]
I want to work on that.
/assign

**Comment by Adarsh-verma-14** [comment]
fixed this issue in #47083 
PTAL!!
