### ISSUE TITLE
Interactive tutorial

### ISSUE THREAD

**Issue by nicolas-giannantonio** [kubernetes/website#47062]
Impossile to access the interactive tutorial
<img width="1512" alt="image" src="https://github.com/kubernetes/website/assets/75692173/6e6ab133-b2b5-42fb-b45b-ce81a16b8a81">

**Comment by tamilselvan1102** [comment]
please describe the issue in English

**Comment by nicolas-giannantonio** [comment]
I can't access the interactive tutorial from any browser.

**Comment by tamilselvan1102** [comment]
Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

**Comment by tamilselvan1102** [comment]
Because of the umbrella issue this still this available for your locale. I will be removed

**Comment by nicolas-giannantonio** [comment]
Ok, that works. Thank you.

**Comment by tamilselvan1102** [comment]
please close the issue, if you got the answer
