### ISSUE TITLE
Should mention envFrom in docs

### ISSUE THREAD

**Issue by justinsb** [kubernetes/website#47075]
The section https://kubernetes.io/docs/concepts/configuration/configmap/#using-configmaps-as-environment-variables describes only how to mount one env-var at a time, and does not mention envFrom.

**Comment by dipesh-rawat** [comment]
**Page reported in issue:** https://kubernetes.io/docs/concepts/configuration/configmap/
/language en

**Comment by tamilselvan1102** [comment]
I thing it is valid point, if triage accepted, i want to work on it.
