### ISSUE TITLE
[ja] typo: Typo in /ja/docs/reference/glossary/kubeadm.md

### ISSUE THREAD

**Issue by Kei-Ta** [kubernetes/website#47078]
**This is a Bug Report**

**Problem:**
There is typo in /ja/docs/reference/glossary/kubeadm.md.
Following is the text with a typo.
kubeadmを使用して、コントロールプレーンとワーカーノード[ワーカーノード](https://kubernetes.io/ja/docs/concepts/architecture/nodes/)コンポーネントの両方をインストールできます。

**Proposed Solution:**
fix "ワーカーノード[ワーカーノード](https://kubernetes.io/ja/docs/concepts/architecture/nodes/)コンポーネント" to "[ワーカーノード](https://kubernetes.io/ja/docs/concepts/architecture/nodes/)コンポーネント"
**Page to Update:**
https://kubernetes.io/ja/docs/reference/glossary/kubeadm.md

**Comment by dipesh-rawat** [comment]
- _Page link for reported issue:_ https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-kubeadm
- _Markdown of glossary entry reported to have issue:_ https://github.com/kubernetes/website/blob/main/content/ja/docs/reference/glossary/kubeadm.md?plain=1

/language ja
