### ISSUE TITLE
Poor code block formatting hinders "Quantity" API doc clarity

### ISSUE THREAD

**Issue by annieakinox** [kubernetes/website#47070]
Your documentation is usually clear, but this page is really hard to read. Especially the code block, It seems to miss some indentation? I don't know 😅

**Comment by dipesh-rawat** [comment]
/retitle Poor code block formatting hinders "Quantity" API doc clarity

**Comment by dipesh-rawat** [comment]
**Page reported in issue _(based on the initial title)_**: https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/
/language en

**Comment by dipesh-rawat** [comment]
This looks closely similar (potentially duplicated) to issue https://github.com/kubernetes/website/issues/35712, which is already in our backlog.

**Comment by sftim** [comment]
I agree that this is a duplicate report. Upvotes on the original issue are welcome.
/triage duplicate

**Comment by sftim** [comment]
/close not-planned

This issue duplicates https://github.com/kubernetes/website/issues/35712
