### ISSUE TITLE
Apply Pod Security Standards at the Cluster Level - kubectl possible unintended alias problem

### ISSUE THREAD

**Issue by brianjester** [kubernetes/website#47081]
If the user has used minikube up to this point and followed the recommendation to alias kubectl to "minikube kubectl --" mentioned on the "minikube start" page here: https://minikube.sigs.k8s.io/docs/start/?arch=%2Fmacos%2Fx86-64%2Fstable%2Fbinary+download

...then the "kubectl" command will not work with the "kind" created cluster because each time they run "kubectl" it will be running the aliased "minikube kubectl --" command instead.

Recommend a note to remind the 1st time user that if they have previously aliased kubectl command to work with minikube they'll need to unalias or remove that alias so they are using the "native" kubectl command and not the aliased "minkube kubestl --".

- Page where note would be helpful: https://kubernetes.io/docs/tutorials/security/cluster-level-pss/
- Page where kubectl was aliased earlier in the tutorials: https://minikube.sigs.k8s.io/docs/start/?arch=%2Fmacos%2Fx86-64%2Fstable%2Fbinary+download

**Comment by tamilselvan1102** [comment]
I think if add a note under [before you begin] section of [this page](https://kubernetes.io/docs/tutorials/hello-minikube/#before-you-begin) would be more suitable.

**Comment by sftim** [comment]
This seems really specific. I think it'd be better to change the minikube docs to tell people to make a note to unalias kubectl, or (also good) to not set that alias - it is not needed.

**Comment by sftim** [comment]
/priority awaiting-more-evidence

(about why we should change one specific page to remind people to undo something recommended on a different site)

**Comment by sftim** [comment]
@tamilselvan1102 your suggestion in https://github.com/kubernetes/website/issues/47081#issuecomment-2208095135 - would you be willing to file an issue covering that?

**Comment by tamilselvan1102** [comment]
@sftim 
I will raise an issue about it
