### ISSUE TITLE
kubectl ApplySets require `contains-group-kinds` annotation but documentation references `contains-group-resources`

### ISSUE THREAD

**Issue by NiklasRosenstein** [kubernetes/website#47092]
### What happened?

I'm not entirely sure if this is a bug, or if the documentation is just inaccurate/lacking some context, but it's at the very least a bit confusing.

If you check the documentation for the well-known labels, etc., you can find the documentation for the `applyset.kubernetes.io/contains-group-resources` annotation [here](https://kubernetes.io/docs/reference/labels-annotations-taints/#applyset-kubernetes-io-contains-group-resources).

![image](https://github.com/kubernetes/kubernetes/assets/1318438/fb7cc3ae-9a67-4435-945d-9ef964ffde6a)

However, when I try to reference a parent object with the `--applyset=` option to `kubectl apply` without this annotation, it complains about the `contains-group-kinds` annotation missing:

```
$ kubectl apply -f - --server-side --applyset applyset/my-applyset --prune
error: parsing ApplySet annotation on "applysets.nyl.io/my-applyset": kubectl requires the "applyset.kubernetes.io/contains-group-kinds" annotation to be set on all ApplySet parent objects
```

At this point my parent resource is declared as:

```yaml
apiVersion: nyl.io/v1
kind: ApplySet
metadata:
  annotations:
    applyset.kubernetes.io/tooling: kubectl/v1.30.1
  labels:
    applyset.kubernetes.io/id: applyset-dppUASvWbAC2LF4ATdrwEpk7WJRt6vIRUnqX_1JY2+s-v1
  name: my-applyset
```

It appears that I can set either one of the two (`*-kinds` or `*-resources`) on the `ApplySet` resource and `kubectl` will accept it; only in the latter case it appears to be copying the "resources" annotation to the add the "kinds" annotation.

To phrase it another way: Setting the "kinds" annotation seems like the right way to go (but not what the documentation suggests), and setting the "resources" annotation works as well but you'll _also_ end up with the "kinds" annotation afterwards.

### What did you expect to happen?

I expect the documentation and kubectl to align.

### How can we reproduce it (as minimally and precisely as possible)?

Point `kubectl apply --applyset=...` at a resource that doesn't have the required annotations.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.1+k3s1
```

</details>

### Cloud provider

nocloud

**Comment by T-Lakshmi** [comment]
Due to an implementation error with `contains-group-resources`, in k8s v1.29 release this annotation was deprecated and the same is replaced by `contains-group-kinds` annotation.

https://github.com/kubernetes/kubernetes/pull/118942 made this changes.

**Comment by T-Lakshmi** [comment]
PR Raised #47120.
