### ISSUE TITLE
Better  wording  on A/AAAA records 

### ISSUE THREAD

**Issue by babugeet** [kubernetes/website#47097]
**This is a Bug Report**

Note given for DNS for Services and Pods is a bit confusing (at least for me).
The statement is **Because A and AAAA records are not created for Pod names, hostname is required for the Pod's A or AAAA record to be created.**.

**Proposed Solution:**

Can this be rephrased to better easy to understand english . Like "  A and AAAA records are not created for Pod names since hostname is missing for the Pod" or to something easily understandable 
**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by sftim** [comment]
Make sure to pick wording that is genuinely easier for readers to understand. Also, if this goes stale or rots, I recommend letting it rot out; this is a very minor fix.
