### ISSUE TITLE
Что такое Kubernetes

### ISSUE THREAD

**Issue by ILF76** [kubernetes/website#47091]

**Comment by Adarsh-verma-14** [comment]
@ILF76 , I am not getting  what you are looking for . So please raise the valid issue with correct description in english.

**Comment by Adarsh-verma-14** [comment]
Please try to  give the heading and description of issue  in English only  So that it can be easy for community to look into it.

**Comment by sftim** [comment]
It's OK to put a localized page title in the issue description but we also need to know what else we're being told: eg, _Typo in page Что такое Kubernetes_

Also, please put the page URL in the issue description.

**Comment by niranjandarshann** [comment]
@ILF76   Thank you for your contributions try contributing with proper description and in English . If you think the issue is needful then you can reopen it or  raise the new issue.

**Comment by niranjandarshann** [comment]
For now i am closing this issue marking it as not planned
/close not-planned
