### ISSUE TITLE
ReplicaSet

### ISSUE THREAD

**Issue by trainin99** [kubernetes/website#47095]
An example of a deployment manifest with the replica key:data pairs required.

**Comment by dipesh-rawat** [comment]
@trainin99  Is the suggestion to include additional details on this page (https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/) ? 

Could you please provide a bit more detail on the specific page and section where the requested information should be added? This will help everyone understand exactly what is needed and where to place it. Thanks!

/language en
/triage needs-information

**Comment by Aaina26** [comment]
A deployment uses key value pairs of a pod manifest. Replica set too uses key value pairs of a pod manifest. Therefore, deployment does not use key value pairs of a replica.Therefore, there are no such examples as requested in the Deployments doc:https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ To me this seems like an invalid request.

**Comment by sftim** [comment]
We haven't found out what isn't right about the existing documentation, not in enough detail to confirm that it needs fixing.

/close not-planned
