### ISSUE TITLE
Kubernetes Documentation - New search is borderline unusuable.

### ISSUE THREAD

**Issue by YoNoSoyVictor** [kubernetes/website#47108]
I just noticed today that the functionality of kubernetes.io/search has changed and it is extremely bad. I have to use "site:kubernetes.io {search term}" now in Google whenever I want to search for something.

As a quick example, let's say you search for: "Service".

Google -> First result: [Service overview](https://kubernetes.io/docs/concepts/services-networking/service/), Second result: [Example of service usage](https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/#creating-a-service-for-an-application-running-in-two-pods), Third result:  [Debugging services](https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/). This is in line with what you would expect

In the docs -> First result: [Ingresses](https://kubernetes.io/docs/concepts/services-networking/ingress/), Second result: [Tailing traffic with Stern](https://kubernetes.io/blog/2016/10/tail-kubernetes-with-stern/), Third result: [Define Dependent Environment Variables](https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/). Literally none of the results are about Services. Only the first result is somewhat-related

The previous search was not the best, but this is a considerable downgrade. What's the rationale behind these changes? 

---
Edit: After some superficial debugging it seems like this change was meant for China only, and is caused by the `is_china` cookie being set to true. You can manually replace this by using your Browser's developer tools (in the case of Firefox, `right click anywhere on the page -> Inspect Accesibility Properties -> Storage tab`.

There's been a shift in the issue and it appears that multiple users outside of china are also encountering this. Some sample Reddit threads [1](https://www.reddit.com/r/kubernetes/comments/1dv96fo/the_update_to_the_documentation_sucks/?share_id=gxsDS6aMgMJKayCzR5tmE&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1) [2](https://www.reddit.com/r/kubernetes/comments/1aqhnwh/question_while_im_browsing_the_documentation_the/). This should be addressed.

**Comment by dipesh-rawat** [comment]
Thank you for the feedback. It appears you are in China, as a new search method has been deployed there. The recent switch to a new search solution [(Pagefind)](https://pagefind.app/) was intended to reduce costs for CNCF caused by the previous search setup for China.  For more details, please refer to issue https://github.com/kubernetes/website/issues/44475 and PR https://github.com/kubernetes/website/pull/46768

**Comment by YoNoSoyVictor** [comment]
> Thank you for the feedback. It appears you are in China, as a new search method has been deployed there. The recent switch to a new search solution [(Pagefind)](https://pagefind.app/) was intended to reduce costs for CNCF caused by the previous search setup for China. For more details, please refer to issue #44475 and PR #46768

Thank you for the feedback Dipesh. As you say, I inspected the cookies through the browser developer tools and found that `is_china` was set to true. I manually set it to false and the old search function came back.

It seems like I am not the only one [experiencing this](https://www.reddit.com/r/kubernetes/comments/1dv96fo/the_update_to_the_documentation_sucks/?share_id=gxsDS6aMgMJKayCzR5tmE&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1), and based on this [Reddit thread](https://www.reddit.com/r/kubernetes/comments/1aqhnwh/question_while_im_browsing_the_documentation_the/) many users are being detected as if they were in China. I am in Spain so I don't know why that cookie was set to true.

**Comment by dipesh-rawat** [comment]
>  I am in Spain so I don't know why that cookie was set to true.

In that case this sounds like it might be a bug. It would be helpful to add this information to the issue [description](https://github.com/kubernetes/website/issues/47108#issue-2394088987), especially if you're outside of China and seeing the new search option.  
@YoNoSoyVictor By the way, do you happen to be using any kind of VPN? It's possible that this could be causing the issue.
/area web-development

**Comment by YoNoSoyVictor** [comment]
> > I am in Spain so I don't know why that cookie was set to true.
> 
>  do you happen to be using any kind of VPN? It's possible that this could be causing the issue. /area web-development

Nope. No VPNs or anything. Tested on multiple devices as well. As per the threads I shared in my last message it seems like this is a widespread issue.

I'll update the issue description with this information. Thanks for the assistance 🙏

**Comment by TPXP** [comment]
I'm using the [uBlock Origin](https://github.com/gorhill/uBlock) ad blocker and it blocks connections to ipinfo.io with default settings. We set `is_china=true` when failing to get this address, which is probably how it was set on your side

https://github.com/kubernetes/website/blob/37c062c574a91bc56f5fd7a7f7529774433f993d/static/js/search.js#L108

**Comment by natalisucks** [comment]
/assign @nate-double-u @cjyabraham 

Given the recent work you've just completed on the CNCF side regarding PageFind, it would be great for the two of you to look into this. We can make sure SIG Docs prioritises review of this work as well, thank you 🙏

**Comment by cjyabraham** [comment]
We've accepted that the new [PageFind](https://pagefind.app/) search is generally not as good as the Bing search that it replaces. Bing, however, was costing CNCF thousands of dollars per month and so was no longer an reasonable option. After reviewing several replacements, PageFind was the best we could find.

The intention is for PageFind to serve users in China, where Google is blocked, and Google Programmable Search to serve everyone else. We detect the location of a user with the [ipinfo.io](https://ipinfo.io/) service. It's likely that this service is blocked for users in China, so if an error occurs, we assume the person is in China. Unfortunately, if people use ad-blocking software that blocks ipinfo.io, then they too will be assumed to be in China. I don't know of a way around this. I suppose it's to be expected that ad-blocking software will sometimes block essential scripts and cause degraded experiences.

Where can we go from here? Here are some suggestions:
1. More work could be done to tune the PageFind results.
2. If PageFind results are still not acceptable, we could go back to the drawing board and consider other search solutions.
3. For detecting whether a user is in China, perhaps there are other methods for doing this that won't be blocked by common ad-blockers. We could do some research into this.

**Comment by mbianchidev** [comment]
After the sig docs meeting there's an alternative that came to my mind

[OramaSearch](https://askorama.ai/)

Good performance, probably we can give it a try?

**Comment by nate-double-u** [comment]
Another idea that came up during the weekly meeting: we may be able to check the language currently being served by the site when the search is made to help us determine which search to provide.

**Comment by nate-double-u** [comment]
> Is it possible to look at the search history of the Google Programmable Search engine to find the most common searches? We could start with the most common 20 search terms and grade the results we get from PageFind?

@a-mccarthy, is this something we can see in our analytics tools?

**Comment by dipesh-rawat** [comment]
> Is it possible to look at the search history of the Google Programmable Search engine to find the most common searches? 

Based on the information available in this page [(here)](https://kubernetes.io/docs/contribute/analytics/), the analytics dashboard for kubernetes.io appears to be located here: [Click to view the dashboard](https://lookerstudio.google.com/u/0/reporting/fe615dc5-59b0-4db5-8504-ef9eacb663a9/page/4VDGB/). The [‘Top search terms’](https://lookerstudio.google.com/reporting/fe615dc5-59b0-4db5-8504-ef9eacb663a9/page/p_5qgvpsaeed) dashboard might be useful for finding the data we’re interested in.

**Comment by nate-double-u** [comment]
Following up on https://github.com/kubernetes/website/issues/47108#issuecomment-2220115660, it'd be great to get a lot of help testing [the proposed fix for this](https://github.com/kubernetes/website/pull/47128).

Here's the deploy preview:
https://deploy-preview-47128--kubernetes-io-main-staging.netlify.app/

**Comment by cjyabraham** [comment]
While we're waiting for the #47128 to be approved, I've split out an independent issue to improve the quality of the PageFind results: #47137. It needs to be assigned to someone familiar with the Kubernetes docs who can more systematically assess the quality of the PageFind results across a broad range of searches.

**Comment by nate-double-u** [comment]
Fixed in https://github.com/kubernetes/website/pull/47128

/close
