### ISSUE TITLE
Pod Security Admission

### ISSUE THREAD

**Issue by ogsensei** [kubernetes/website#47125]
How to do the governance of the Pod Security Standards(PSS)? Is there any way to monitor on which namespaces the pss is not applied?

Thanks in advance

**Comment by dipesh-rawat** [comment]
Looks like a request for help in its current form.

/kind support

**Comment by dipesh-rawat** [comment]
@ogsensei Thank you for reaching out and seeking assistance. We appreciate your query, but the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.

**Comment by ogsensei** [comment]
Thanks @dipesh-rawat
