### ISSUE TITLE
[ja] Translate docs/concepts/policy/node-resource-managers.md into Japanese

### ISSUE THREAD

**Issue by Kei-Ta** [kubernetes/website#47140]
This is a Feature Request

What would you like to be added

Translate docs/concepts/policy/node-resource-managers.md into Japanese

Why is this needed

There is no Japanese translation for this page

Comments

File to translate:
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/policy/node-resource-managers.md
Original:
https://kubernetes.io/docs/concepts/policy/node-resource-managers/

/area localization
/language ja
/assign

**Comment by Okabe-Junya** [comment]
@Kei-Ta 

> File to translate:
> https://github.com/kubernetes/website/blob/main/content/en/policy/node-resource-managers.md

このリンクは404なので以下のリンクが翻訳元という認識であっていますか。。？？

- https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/policy/node-resource-managers.md

**Comment by Kei-Ta** [comment]
ご確認ありがとうございます。
申し訳ございません。合ってます。
