### ISSUE TITLE
Website search results less accurate after 'Pagefind' integration

### ISSUE THREAD

**Issue by sunzhen2408** [kubernetes/website#47155]
I suspect that the search page of kubernetes documentation has been adjusted recently, and the search results are not as accurate as before.

For example, in the past, if I wanted to find "Resource Management for Pods and Containers", I could quickly find what I needed by simply searching for "resource". But now, even if I input "Resource Management", it's difficult to quickly find what I'm looking for.

**Comment by sunzhen2408** [comment]
Maybe the reason is that during the search process, it seems to be targeting the directory. As long as there is relevant information in the directory, the page will be returned as a search result.

**Comment by dipesh-rawat** [comment]
/retitle Website search results less accurate after 'Pagefind' integration
/area web-development

**Comment by dipesh-rawat** [comment]
Thank you for raising this issue. It appears to be similar to issue https://github.com/kubernetes/website/issues/47108 recently reported. To provide context, there has been a recent update to the search for only China users to use [Pagefind](https://pagefind.app/).  If you’re outside China and still encountering the new search results, there’s a fix underway for issue https://github.com/kubernetes/website/issues/47108 as part of PR https://github.com/kubernetes/website/pull/47128 that is awaiting to be merged. 

Additionally, there’s another issue https://github.com/kubernetes/website/issues/47137 aimed at fine-tuning the results of the new search to ensure they’re as helpful as the old search.

**Comment by dipesh-rawat** [comment]
/triage duplicate
Marking this as duplicate in favor of existing issues https://github.com/kubernetes/website/issues/47108 and https://github.com/kubernetes/website/issues/47137

Input and feedback are welcomed on the existing issues, as well as assistance in reviewing and providing feedback on PR https://github.com/kubernetes/website/pull/47128

**Comment by natalisucks** [comment]
Fixed in https://github.com/kubernetes/website/pull/47128

/close
