### ISSUE TITLE
[ja] Translate docs/concepts/policy/pid-limiting.md into Japanese

### ISSUE THREAD

**Issue by Kei-Ta** [kubernetes/website#47188]
**Note that this issue is for Japanese Speaker**
**This is a Feature Request**
**What would you like to be added**
Translate content/en/docs/concepts/policy/pid-limiting.md into Japanese

**Why is this needed**
There is no Japanese translation for this page
**Comments**
File to translate:
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/policy/pid-limiting.md
Original:
https://kubernetes.io/docs/concepts/policy/pid-limiting/

/area localization
/language ja
/assign

**Comment by Okabe-Junya** [comment]
Thanks!

/triage accepted
