### ISSUE TITLE
Kubernetes documentation for Sidecar Containers

### ISSUE THREAD

**Issue by roshanauthankar** [kubernetes/website#47219]
I think the example provided is incorrect. In the example, the sidecar container is listed under initContainers - 

    spec:
      containers:
        - name: myapp
          image: alpine:latest
          command: ['sh', '-c', 'while true; do echo "logging" >> /opt/logs.txt; sleep 1; done']
          volumeMounts:
            - name: data
              mountPath: /opt
      initContainers:
        - name: logshipper
          image: alpine:latest
          restartPolicy: Always
          command: ['sh', '-c', 'tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt

Documentation link:  https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-example

**Comment by dipesh-rawat** [comment]
Additionally, I see we have an existing issue https://github.com/kubernetes/website/issues/45406, which is addressing documenting the legacy method for defining sidecar containers in the same [page](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/).

**Comment by dipesh-rawat** [comment]
/triage duplicate

Marking this as duplicate in favor of existing issue https://github.com/kubernetes/website/issues/45406
_(Feel free to remove the label if this is incorrect.)_

**Comment by stmcginnis** [comment]
If you read the paragraph at the beginning of that section, it further explains how this is the correct way:

> Kubernetes implements sidecar containers as a special case of [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/); sidecar containers remain running after Pod startup. This document uses the term regular init containers to clearly refer to containers that only run during Pod startup.

**Comment by iam-veeramalla** [comment]
@stmcginnis I think a line mentioning how a sidecar container can be defined in the InitContainer section would help. 

I think by mentioning `lifecycle`, `livenessProbe`, `readinessProbe`, or `startupProbe` fields in the InitContainer, Kubernetes understands it as a special case - sidecar container.

May be this can be documented.

**Comment by sftim** [comment]
Please follow up on the original issue - https://github.com/kubernetes/website/issues/45406. I recommend closing this duplicate issue as not planned (because it is a duplicate, and we are tracking the work via the earlier report).

Help is welcome; Kubernetes documentation is largely maintained by volunteers.

**Comment by sftim** [comment]
/close not-planned

We'll track work via the original issue. Help is welcome.
