### ISSUE TITLE
[fr] Inactive and deprecated interactive tutorial in "Learn Kubernetes Basics" page

### ISSUE THREAD

**Issue by cesar-lizurey** [kubernetes/website#47214]
Bonjour,
Petit problème de CORS sur cette page: https://kubernetes.io/fr/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

`Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://katacoda.com/api/embed/nonce?protocol=https:&host=kubernetes.io. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant. Code d’état : 403.`

Je suis bien sur un ordinateur et j'ai ceci:

![image](https://github.com/user-attachments/assets/aae4a7e2-328b-43f5-ae92-3dfbdec45bac)

**Comment by dipesh-rawat** [comment]
/retitle [fr] Inactive and deprecated interactive tutorial in "Learn Kubernetes Basics" page
/language fr

**Comment by dipesh-rawat** [comment]
@cesar-lizurey Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.

**Comment by cesar-lizurey** [comment]
Does it mean I can suggest a merge request for French?

**Comment by sftim** [comment]
/triage accepted

Ce projet est open source : tout le monde peut y contribuer! / This is an open source project, anyone is welcome to contribute!
