### ISSUE TITLE
Improve blog article summaries presentation with translator metadata in front matter

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#47223]
**This is a Feature Request**

**What would you like to be added**

In #45865, the "author" metadata was added to the front matter. Currently, some l10n teams are also setting "translator" metadata. This is one of the initiatives to promote the localization of blog posts.

FYI: https://kubernetes.slack.com/archives/C0191RDKHU1/p1712145776110259?thread_ts=1712073000.812269&cid=C0191RDKHU1

I would like to add "translator" metadata to the blog's front matter, just like the author metadata.

**Why is this needed**

To promote the localization of blog articles. This would be a significant motivation for those involved in localization.

**Comments**

**Comment by mengjiao-liu** [comment]
This is a great idea. It will be very motivating for localization contributors. 👍

**Comment by Okabe-Junya** [comment]
Thank you for your interest in this issue, mengjiao-liu !

I've opened a pull request to resolve it - #47270. please have a look :)

**Comment by dipesh-rawat** [comment]
Would be nice to add this feature.

/priority backlog
/triage accepted
