### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/

### ISSUE THREAD

**Issue by viridiyen** [kubernetes/website#47238]
Hello! in the Pod OS section of this page, it says: 

> Pod OS 

>...
> In Kubernetes v1.30, the value of .spec.os.name does not affect how the [kube-scheduler](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/) picks a Pod to run a node

**Editing for clarity:
Forgive me if I'm misunderstanding, but kube-scheduler should pick a node for the Pod to run on, and not the other way around? The way the above sentence is worded sounds like kube-scheduler picks Pods to run nodes.

**Comment by kundan2707** [comment]
@viridiyen these two statements donot contradict as  first one say that selecton of node by kube-scheduler is not based on ```.spec.os``` .
kube-scheduler pick a node of run based on various other creterias but not consider ```.spec.os``` frield
