### ISSUE TITLE
CronJob unable to create

### ISSUE THREAD

**Issue by vijay862391** [kubernetes/website#47275]
getting errors after running cronjob--> Saw a job that the controller did not create or forgot: vijay-deployment-restart-manual-hkp5z

How to resolve it ?

**Comment by tamilselvan1102** [comment]
Please describe the issue in details and mention which page you are following

**Comment by dipesh-rawat** [comment]
Looks like a request for help in its current form.

/kind support
_(Feel free to remove the label if this is incorrect.)_

**Comment by tengqm** [comment]
/close
feel free to reopen this if there are docs issues to fix.
