### ISSUE TITLE
Ingress documentation misleading example

### ISSUE THREAD

**Issue by dmytro-storozhuk** [kubernetes/website#47276]
There is an incorrect match given in the ingress examples table (https://kubernetes.io/docs/concepts/services-networking/ingress/#examples).

It says that "**_/aaa/bbbxyz_**" doesn't match the "**_/aaa/bbb_**" with **Prefix** config, but it does match.

[![dznc5oF.md.png](https://iili.io/dznc5oF.md.png)](https://freeimage.host/i/dznc5oF)

**Comment by dipesh-rawat** [comment]
_Page reported in issue:_ https://kubernetes.io/docs/concepts/services-networking/ingress/
/language en

**Comment by T-Lakshmi** [comment]
@dmytro-storozhuk,

Did you test this behavior in a practical setting with any example configuration?

**Comment by dmytro-storozhuk** [comment]
@T-Lakshmi  I've tested it with NGINX controller with k8s Ingress . It did route the traffic with example setup.

@2003Aditay seemed to have applied the fix already.

Cheers
