### ISSUE TITLE
Website search not working after KubeCon banner activation

### ISSUE THREAD

**Issue by ischoi77** [kubernetes/website#47274]
Hi

The search function doesn't work 
after adding [KubeCon + CloudNativeCon + Open Source Summit China 2024] Banner

please check it out.

**Comment by tamilselvan1102** [comment]
Search function is not working

**Comment by dipesh-rawat** [comment]
/retitle Website search not working after KubeCon banner activation
_(Retitled to reflect the actual problem)_

**Comment by dipesh-rawat** [comment]
The search feature seems to be working fine for me.

/priority awaiting-more-evidence

**Comment by tamilselvan1102** [comment]
After search, there is a empty page is displaying 
![image](https://github.com/user-attachments/assets/e0a35437-e5e9-49d2-bd15-ff6e1e665a47)

**Comment by tamilselvan1102** [comment]
Now it is working as expected.
Please close the issue
