### ISSUE TITLE
Storage Classes - contradicting behavior statements

### ISSUE THREAD

**Issue by dmytro-storozhuk** [kubernetes/website#47297]
The default Storage class behaviour in https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass says:

_"If you set the [storageclass.kubernetes.io/is-default-class](https://kubernetes.io/docs/reference/labels-annotations-taints/#storageclass-kubernetes-io-is-default-class) annotation to true on **more than one StorageClass in your cluster**, and you then create a PersistentVolumeClaim with no storageClassName set, **Kubernetes uses the most recently created default StorageClass.**"_

whereas, in the addmission controllers page (https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass) for controller that does this amendment:

_"This admission controller does not do anything when no default storage class is configured. **When more than one storage class is marked as default, it rejects any creation of PersistentVolumeClaim with an error** and an administrator must revisit their StorageClass objects and mark only one as default. This admission controller ignores any PersistentVolumeClaim updates; it acts only on creation."_

So, what is the correct one?

Thanks

**Comment by dmytro-storozhuk** [comment]
and one more place https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#defaulting-behavior

_"Note that if you set the storageclass.kubernetes.io/is-default-class annotation to true on **more than one StorageClass in your cluster**, and you then create a PersistentVolumeClaim with no storageClassName se**t, Kubernetes uses the most recently created default StorageClass**."_

**Comment by dmytro-storozhuk** [comment]
The test on local minikube cluster (v.1.30.0) showed that PVC provisioned (BOUND state) with the latest "default" StorageClass assigned. So, the description of DefaultStorageClass is misleading.

**Comment by sftim** [comment]
Is this a duplicate of issue https://github.com/kubernetes/website/issues/42288?

**Comment by dmytro-storozhuk** [comment]
@sftim yes, it is a duplicate. The documentation hasn't been updated for a year

**Comment by sftim** [comment]
/close not-planned

There is an existing issue; help is welcome.
