### ISSUE TITLE
Improvement for k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by kabatz** [kubernetes/website#47292]
egress:
  - to:
    - namespaceSelector:
       matchLabels:
        namespace: default
    - podSelector:
       matchLables:

You have typo here, one is written 'Labels' while the other is written 'Lables'

please fix it

**Comment by tamilselvan1102** [comment]
@kabatz Nowhere found 'matchLables' in [network-policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) page. Please share the page url where you found it.

**Comment by kabatz** [comment]
i literally copy-pasted the lines above from https://kubernetes.io/docs/concepts/services-networking/network-policies/

yet i cant find it anymore! 
its just odd 

thanks for your quick response, i no more see 'matchLables' in the page, feel free to close the incident

**Comment by tamilselvan1102** [comment]
please close the issue. if you satisfied
