### ISSUE TITLE
Confusing paragraph in Labels and Selectors concept

### ISSUE THREAD

**Issue by thebaultyoann** [kubernetes/website#47317]
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#equality-based-requirement

In the documentation, we have this statement: 
`One usage scenario for equality-based label requirement is for Pods to specify node selection criteria. For example, the sample Pod below selects nodes with the label **"accelerator=nvidia-tesla-p100"**.`

While an example just after doesn't use this, but instead ** accelerator: nvidia-tesla-p100`**

`apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
spec:
  containers:
    - name: cuda-test
      image: "registry.k8s.io/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    accelerator: nvidia-tesla-p100`

**Comment by sftim** [comment]
/retitle Confusing paragraph in Labels and Selectors concept

We could edit the existing text, eg:
```diff
 One usage scenario for equality-based label requirement is for Pods to specify
-node selection criteria. For example, the sample Pod below selects nodes with
-the label "`accelerator=nvidia-tesla-p100`".
+node selection criteria. For example, the sample Pod below selects all nodes
+labelled `accelerator: nvidia-tesla-p100`.
```

Although a narrow tweak is helpful, we'd welcome a wider revision of the entire page to align it with the documentation style guide.

/language en
/priority backlog
/triage accepted
/help
