### ISSUE TITLE
the full_link in /docs/reference/glossary/kubelet.md may be wrong

### ISSUE THREAD

**Issue by Kei-Ta** [kubernetes/website#47324]
**This is a Bug Report**

**Problem:** 
the full_link in `/docs/reference/glossary/kubelet.md` may be wrong.
When I click the shortcode element `{{< glossary_tooltip text="kubelet" term_id="kubelet" >}}`, it goes to the `/docs/reference/generated/kubelet` link and doesn't show any kubelet information.

**Proposed Solution:**
When I click the shortcode element `{{< glossary_tooltip text="kubelet" term_id="kubelet" >}}`,it goes to the `/docs/reference/command-line-tools-reference/kubelet/` link.

**Page to Update:**
/docs/reference/glossary/kubelet.md
``` diff
- full_link: /docs/reference/generated/kubelet
+ full_link: /docs/reference/command-line-tools-reference/kubelet/
```

**Comment by dipesh-rawat** [comment]
There's a redirect set up from` /docs/reference/generated/kubelet/ ` to `/docs/reference/command-line-tools-reference/kubelet/` in the **__redirects_** file [(click here)](https://github.com/kubernetes/website/blob/f16438073a1bc4f543a15bd49953825ec7b7996f/static/_redirects#L184), so the existing link should work as expected.

/priority awaiting-more-evidence

**Comment by dipesh-rawat** [comment]
Try opening the link https://kubernetes.io/docs/reference/generated/kubelet/ in a browser; it should redirect to the correct location.

**Comment by Kei-Ta** [comment]
@dipesh-rawat 
Sorry, There was insufficient confirmation and lack of knowledge about redirects.
This problem occurred local environment and I misunderstood by comparing it with other files like `kubeadm.md`, `kubectl.md`.
Can I close this issue?
