### ISSUE TITLE
[hi] Localize configuration tutorial

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#47329]
**This is a Feature Request**

**What would you like to be added**
To localize Configuration tutorial to Hindi.

**Link to Page**
https://kubernetes.io/docs/tutorials/configuration/

**Comment by dipesh-rawat** [comment]
This looks duplicate of an issue we already have https://github.com/kubernetes/website/issues/43490

/triage duplicate

**Comment by dipesh-rawat** [comment]
Please follow up on the original issue https://github.com/kubernetes/website/issues/43490. I suggest closing this duplicate issue as "not planned," since it is redundant and we are monitoring progress through the initial report.

**Comment by utkarsh-singh1** [comment]
@dipesh-rawat, the mentioned issue does not seem to be active in work, also I think author tried to span that issue to work on localize other section of tutorials.
