### ISSUE TITLE
Play-with-k8s /dev/sdb in out of space

### ISSUE THREAD

**Issue by shafiunmiraz0** [kubernetes/website#47336]
**This is Support**
/dev/sdb         64G   64G   26M 100% /etc/hosts

Whenever I try to init kubeadm for master node, it shows that, no space left. Please help how to give solution.

**Comment by tamilselvan1102** [comment]
@shafiunmiraz0 Thank you for reaching out and seeking assistance. We appreciate your query, but the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.

**Comment by sftim** [comment]
https://play-with-kubernetes.com is an external service.

Please report issues there.

/close not-planned
