### ISSUE TITLE
Improvements for "Run a Replicated Stateful Application"

### ISSUE THREAD

**Issue by Swapnil-jain** [kubernetes/website#47347]
This page is outdated.
1. The mysql:5.7 does not work for apple silicon macs. We need mysql:8.0 for that. This needs to be mentioned in the page.
2. gcr.io/google-samples/xtrabackup:1.0 image is using a deprecated Docker image format. This format is no longer supported by default in the latest versions of Kubernetes. We get a 'Failed to pull image' error.  Logs are below:

<img width="1287" alt="Screenshot 2024-08-03 at 4 13 25 PM" src="https://github.com/user-attachments/assets/5ab8ea87-ab74-4e11-9a60-502da24642fc">

**Comment by Swapnil-jain** [comment]
`
Events:
  Type     Reason     Age   From               Message
  ----     ------     ----  ----               -------
  Normal   Scheduled  39s   default-scheduler  Successfully assigned default/mysql-0 to minikube
  Normal   Pulling    38s   kubelet            Pulling image "mysql:8.0"
  Normal   Pulled     14s   kubelet            Successfully pulled image "mysql:8.0" in 24.449s (24.449s including waiting). Image size: 590054268 bytes.
  Normal   Created    14s   kubelet            Created container init-mysql
  Normal   Started    14s   kubelet            Started container init-mysql
  Normal   Pulling    13s   kubelet            Pulling image "gcr.io/google-samples/xtrabackup:1.0"
  Warning  Failed     10s   kubelet            Failed to pull image "gcr.io/google-samples/xtrabackup:1.0": [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of gcr.io/google-samples/xtrabackup:1.0 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
  Warning  Failed     10s   kubelet            Error: ErrImagePull
  Normal   BackOff    10s   kubelet            Back-off pulling image "gcr.io/google-samples/xtrabackup:1.0"
  Warning  Failed     10s   kubelet            Error: ImagePullBackOff
`

**Comment by sftim** [comment]
/retitle Improvements for "Run a Replicated Stateful Application"

/kind bug
(because of the reference to a deprecated container image)
/language en

/triage accepted
Help welcome!

**Comment by sftim** [comment]
> This format is no longer supported by default in the latest versions of Kubernetes. We get a 'Failed to pull image' error.

Is it Kubernetes that has turned off support, or another piece of software?

**Comment by Swapnil-jain** [comment]
> > This format is no longer supported by default in the latest versions of Kubernetes. We get a 'Failed to pull image' error.
> 
> Is it Kubernetes that has turned off support, or another piece of software?

Hi, I am not sure. I just asked chatgpt and according to it, it is kubernetes which is causing the problem. I am using Docker Desktop and minikube to run the cluster by the way.

**Comment by Swapnil-jain** [comment]
I also noticed issue #46253 is basically same.

**Comment by sftim** [comment]
Ah, OK
/remove-triage accepted
/triage duplicate

**Comment by niranjandarshann** [comment]
This issue is duplicate so i am closing this issue.
Feel free to raise and reopen the issue if some non duplicate issue persist. Appreciate your effort.
For now i am closing this issue.

**Comment by niranjandarshann** [comment]
The issue is not planned 
So closing this issue . Keep contributing
/close
