### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/kubernetes-basics/scale/scale-intro/

### ISSUE THREAD

**Issue by bigdbythesea** [kubernetes/website#47345]
The text states:
"We hit a different Pod with every request. This demonstrates that the load-balancing is working."

Everything  worked fine as followed by the tutorial but how do we know or actually see that a different Pod was invoked for the multiple curl requests?  
Nothing is demonstrated or confirms that multiple Pods were involved.  Is there a log trace somewhere or a command execution history logged where we can actually see the "demonstration" that multiple Pods were involved in the scaling or is it just blind trust?

**Comment by sftim** [comment]
I expect that the sample output, if following the tutorials, is similar to:
```console
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-wp67j | v=1
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-hs9dj | v=1
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-4hjvf | v=1
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-wp67j | v=1
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-644c5687f4-4hjvf | v=1
```

---

> We hit a different Pod with every request

is misleading. The choice of backing pod is pseudorandom and could repeat (see above example) rather than being different for each and every request.

**Comment by sftim** [comment]
/triage accepted
/priority backlog

See https://github.com/kubernetes/website/issues/47345#issuecomment-2266684730
