### ISSUE TITLE
Incorrect number of characters for DNS Subdomain Names in page Object Names and IDs

### ISSUE THREAD

**Issue by idrunk** [kubernetes/website#47359]
DNS总长度应该是255（63*4+3），而不是253，英文版文档也有这个问题。
[DNS 子域名](https://kubernetes.io/zh-cn/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names)
[RFC 1123](https://datatracker.ietf.org/doc/html/rfc1123)

**Comment by tamilselvan1102** [comment]
please describe the issue in english

**Comment by mengjiao-liu** [comment]
/retitle Incorrect number of characters for DNS Subdomain Names in page Object Names and IDs

**Comment by mengjiao-liu** [comment]
> please describe the issue in english

**The translation into English is as follows：**
The total length of DNS should be 255 (63*4+3), not 253. The English version of the document also has this problem.

---
English page: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
/language en

**Comment by sftim** [comment]
/remove-triage accepted

Issue is not written in the language we work in.

**Comment by mengjiao-liu** [comment]
> Please update the issue description into English @idrunk. If the Chinese text accurately translates the English text, the problem needs to be fixed on the English page.
> 
> We can't assume that the people maintaining English are able to read Chinese.

Could you update the issue description? @idrunk

**Comment by tengqm** [comment]
K8s is not strictly following the RFC standard. 253 is the actual limit enforced.
This fix is invalid.
/close
