### ISSUE TITLE
Incorrect volumeMounts path in "Configuring Redis using a ConfigMap" tutorial

### ISSUE THREAD

**Issue by andsouth44** [kubernetes/website#47364]
To complete this tutorial I had to change:

    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config

To:

    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /data/redis-master
      name: config

**Comment by dipesh-rawat** [comment]
_Page reported in issue (based on the initial title):_ https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/

**Comment by dipesh-rawat** [comment]
/retitle Incorrect volumeMounts path in "Configuring Redis using a ConfigMap" tutorial
/language en

**Comment by tamilselvan1102** [comment]
There is no issue in the example. 
The mount path is the destination inside the Pod where the volume gets mounted.
you can set any mount point as you wish.

**Comment by mengjiao-liu** [comment]
+1
The example is correct, I tested it and it worked a moment ago.

**Comment by andsouth44** [comment]
Ok. Thanks for testing and confirming. I was testing it in Killercoda so there must be something in that environment that is inserting /data in the path. On Aug 6, 2024, at 8:21 AM, Mengjiao Liu ***@***.***> wrote:﻿
+1
The example is correct, I tested it and it worked a moment ago.

**Comment by T-Lakshmi** [comment]
Closing the issue as there is nothing to fix in this.
/close
