### ISSUE TITLE
Add documentation for kubelet standalone mode

### ISSUE THREAD

**Issue by HirazawaUi** [kubernetes/website#47402]
**This is a Feature Request**

**What would you like to be added**

Add documentation for kubelet standalone mode

**Why is this needed**
We need to add documentation for the standalone mode of kubelet, which is actually operational within the kubelet, but we do not have documentation describing how to use it.

**Comments**

**Comment by mengjiao-liu** [comment]
I haven't seen the documentation for kubelet standalone mode on K8s website. If so, it is useful for some users. IMO

**Comment by tengqm** [comment]
Not sure if this worth doing because the standalone mode might be deprecated. I cannot recall where I saw this.

**Comment by sftim** [comment]
@tengqm, we document deprecated features

(however, if they are later removed, we don't need to document them)

**Comment by HirazawaUi** [comment]
> Not sure if this worth doing because the standalone mode might be deprecated. I cannot recall where I saw this.

We are deprecating the `runonce` mode, but we intend to keep the `standalone` mode. Did you possibly mix them up?

**Comment by tengqm** [comment]
> > Not sure if this worth doing because the standalone mode might be deprecated. I cannot recall where I saw this.
> 
> We are deprecating the `runonce` mode, but we intend to keep the `standalone` mode. Did you possibly mix them up?

Exactly. Kind of "memory leak" for me.

**Comment by matte21** [comment]
I'm one of the hypothetical users mentioned above. 

I'm in a situation where I'd suspect I'd benefit from running the Kubelet in standalone mode, but am struggling to do so  due to the lack of documentation.

**Comment by mengjiao-liu** [comment]
It seems we need to ask for help from sig-node. Does anyone know more about standalone mode? @kubernetes/sig-node-leads .

**Comment by sftim** [comment]
Folks in SIG Docs might know this, but not everyone will be able to work it out without having some official docs already available.
