### ISSUE TITLE
Japanese topology-aware traffic routing page is not deleted.

### ISSUE THREAD

**Issue by kei01234kei** [kubernetes/website#47427]
**This is a Bug Report**

**Problem:**
Topology-aware traffic routing with topology keys is deprecated since 1.21.
Although English topology-aware traffic routing page is deleted in  #40605, japanese page is not deleted.

**Proposed Solution:**
Remove Service Topology page

**Page to Update:**
https://k8s.io/docs/concepts/services-networking/service-topology/

Deprecated since 1.21

**Comment by kei01234kei** [comment]
I will try this isue.
/assign

**Comment by kei01234kei** [comment]
I will try this isue.

/assign

**Comment by Okabe-Junya** [comment]
Page to update: https://kubernetes.io/ja/docs/concepts/services-networking/service-topology/

/area localization
/triage accepted
