### ISSUE TITLE
Kubernetes display preferences 

### ISSUE THREAD

**Issue by Mulaudzi-MK** [kubernetes/website#47422]
Hi, I would like if you can have an option for user to chose dark mode for Kubernetes documentation pages

**Comment by Aaina26** [comment]
This issue is duplicated by #25061 
This feature implementation is still in progress. In the meantime you can explore a quick fix mentioned in the following comment: https://github.com/kubernetes/website/issues/18798#issuecomment-2002887137
/cc @dipesh-rawat

**Comment by dipesh-rawat** [comment]
Looks like duplicate of an issue we already have https://github.com/kubernetes/website/issues/25061. Also, see https://github.com/kubernetes/website/issues/37444

/triage duplicate

**Comment by dipesh-rawat** [comment]
Any assistance with existing issues #37444 and #25061 is welcome.

/area web-development

**Comment by dipesh-rawat** [comment]
/close not-planned

This request is a duplicate of existing issues.
