### ISSUE TITLE
Issue with k8s.io/pt-br/docs/reference/kubectl/cheatsheet/

### ISSUE THREAD

**Issue by deepeshgarg1983** [kubernetes/website#47431]
I wanted to see this entire page into english language but not getting it . Please so the needful

**Comment by niranjandarshann** [comment]
@deepeshgarg1983  Definately yes You will get it in english language as well
But it is by the name kubectl Quick Reference .

**Comment by niranjandarshann** [comment]
You can find this in english here https://kubernetes.io/docs/reference/kubectl/quick-reference/

**Comment by niranjandarshann** [comment]
This feels like a request for support.

However, GitHub is not the right place for support requests.

If you are looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by niranjandarshann** [comment]
For now i am closing this issue Thanks for your contribution.
Keep contributing to the community.
With new feature request, bug fixes etc.
