### ISSUE TITLE
Remove WeaveWork-Scope URL from the kuberntes website 

### ISSUE THREAD

**Issue by utkarsh-singh1** [kubernetes/website#47441]
**What would you like to be added**
As Weavework social has been closed, any URL for Weavework to be removed from kubernetes docs.

**Why is this needed**
As URL does not redirect to any available website and since there is no alternative present at the moment remove the URL from the page.

**Comment by utkarsh-singh1** [comment]
Related Page -

- https://kubernetes.io/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/zh-cn/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/de/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/id/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/ja/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/ko/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/pt-br/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/ru/docs/concepts/cluster-administration/addons/
- https://kubernetes.io/es/docs/concepts/cluster-administration/addons/

**Comment by utkarsh-singh1** [comment]
English page has been updated - #47438

**Comment by sftim** [comment]
Does this duplicate #45482?

**Comment by mengjiao-liu** [comment]
> Does this duplicate #45482?

And #47421？

There is usually no need to recreate a new duplicate issue. @utkarsh-singh1

**Comment by utkarsh-singh1** [comment]
@sftim @mengjiao-liu, I have created this issue to track progress on other language pages.

**Comment by dipesh-rawat** [comment]
> I have created this issue to track progress on other localized version of this page.

@utkarsh-singh1 It's important to recognize that each localization team operates on its own schedule and with its own resources, so it's best not to speak on behalf of all teams. Ideally, every change to the English content should eventually be reflected across all localizations, but it's not necessary to file an issue for every upstream change. In this case, since the upstream changes aren't finalized yet, it's still too early to determine the next steps for localization teams.

**Comment by Nishant-k-sagar** [comment]
Hey @utkarsh-singh1, @dipesh-rawat  I would like to work on this issue, as I am already familiar with doc related work in gateway-api repo too, it would be great to get assigned this task to start on kubernetes documents itself.

**Comment by natalisucks** [comment]
As this is a duplicate issue of #45482, I'll be closing this in favor of the one overarching issue to complete for the upstream English docs
/close
