### ISSUE TITLE
Typo in localized page 为 Kubernetes 组件和工具生成参考文档

### ISSUE THREAD

**Issue by Adarsh-verma-14** [kubernetes/website#47453]
**This is a Bug Report**
There is a typo in the Chinese documentation. The text **"为 kubectll 命令生成参考文档"** contains an extra **"l"** in **"kubectl"**.

**Proposed Solution:**
The correct text should be **"为 kubectl 命令生成参考文档".**

**Page to Update:**
https://kubernetes.io/zh-cn/docs/contribute/generate-ref-docs/kubernetes-components/

**Comment by sftim** [comment]
/retitle Typo in localized page 为 Kubernetes 组件和工具生成参考文档
