### ISSUE TITLE
从私有仓库拉取镜像

### ISSUE THREAD

**Issue by RobinsChens** [kubernetes/website#47492]
1.27 都不用docker了，镜像是如何拉取的呢，这个文档不对吧，而且containerd ctr image pull 下来的镜像，kubelet识别不了，为啥呢

**Comment by liangyuanpeng** [comment]
/kind support

This is a question for how to pull image from private registry,

**Comment by T-Lakshmi** [comment]
@RobinsChens,
Thank you for reaching out and seeking assistance. We appreciate your query, but the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.
