### ISSUE TITLE
[ja] Translate content/en/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control into Japanese

### ISSUE THREAD

**Issue by everpeace** [kubernetes/website#47498]
**This is a Feature Request**

- Translate "Kubernetes 1.31: Fine-grained SupplementalGroups control"
  - `content/en/blog/_posts/2024-08-22-Fine-grained-SupplementalGroups-control into Japanese` (not yet published)

**What would you like to be added**

**Why is this needed**

There is no Japanese translate for this page

**Comments**

/area localization
/language ja
/assign

**Comment by Okabe-Junya** [comment]
Thanks!

/triage accepted
