### ISSUE TITLE
Kubernetes API reference 1.31 missing

### ISSUE THREAD

**Issue by dims** [kubernetes/website#47512]
Folks, https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/ is missing 

_Edit_ and https://kubernetes.io/docs/reference/kubernetes-api/ is out of date

(some step in release process got missed? https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/ works fine)

**Comment by sftim** [comment]
/triage accepted
/priority important-soon

I suspect that all the docs generation got missed, but I haven't checked.

**Comment by dipesh-rawat** [comment]
@neoaggelos FYI

**Comment by mbianchidev** [comment]
Related: https://github.com/kubernetes/website/issues/46583

**Comment by katcosgrove** [comment]
Hi, y'all!

The reference docs cannot be generated by the Release Docs subteam. It has not been possible for them to do this in a very, very long time. They are generated by SIG Docs. Historically, they have been generated days after the release, not on the actual release day.

@sftim As discussed in the SIG Docs meeting on 06 August, this will be done by myself and @salaxander with the help of @nate-double-u, originally scheduled for today.

**Comment by sftim** [comment]
/reopen

We have two API references; only one has been updated so far.

**Comment by sftim** [comment]
@dims the other reference that needs updating is https://kubernetes.io/docs/reference/kubernetes-api/
