### ISSUE TITLE
Issue with k8s.io/uk/docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by allxiaa** [kubernetes/website#47609]
The problem is displaying the terminal in all lessons (https://kubernetes.io/uk/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/). I made a vm and used the steps from the README.md (https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios)

**Comment by tamilselvan1102** [comment]
please brief the issue you are facing

**Comment by tamilselvan1102** [comment]
interactive terminal is obsolete from K8s

**Comment by tamilselvan1102** [comment]
@allxiaa  Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.

**Comment by allxiaa** [comment]
> @allxiaa Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).
> 
> We have an umbrella issue raised #41496 to remove tutorials that rely on Katacoda for all localized documents.

Ok.

/triage accepted
