### ISSUE TITLE
Field Selectors

### ISSUE THREAD

**Issue by Martin-Luther** [kubernetes/website#47616]
Is there a way to make it work with le `logs` kind ?

For exemple :
```tty
 kubectl logs -n <namespace> <pod_name> --field-selector status.phase=Running
```

When I try this while the pod is between `Terminating` && `Running` (2 pods), I get an error message :

`error: container bind9-5755cbf67-vxjmt is not valid for pod bind9-5755cbf67-gpgmm`

To reproduce, you must have previously deployed `<deployment>.yaml`
```tty
kubectl delete -f <deployment>.yaml
```
Followed by 

```tty
kubectl apply -f <deployment>.yaml
```

Then try to get logs  now vi kubectl ...

**Comment by sftim** [comment]
This feels like a request for support.

However, GitHub is not the right place for support requests.

If you are looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

---

If you want to suggest an improvement to `kubectl`, visit https://github.com/kubernetes/kubectl/issues/new/choose

**Comment by niranjandarshann** [comment]
@Martin-Luther  This is a support issue try to reach out to the community forum or on slack channel. 
For now I am closing the issue. 
Keeps Contributing to the community with the bug, feature request etc. 

Thanks for your contribution.
