### ISSUE TITLE
Task page for installing kubectl should explain how to find direct download link

### ISSUE THREAD

**Issue by crsadun** [kubernetes/website#47614]
There's million users which have no direct internet access from the workplace other than downloading from HTTP/HTTPS websites for security reasons. Others do not have chocolatey installed or cannot copy/paste curl commands from an external website to their local workstation, also for security reasons. 

Currently the HTTP link to download kubectl is inside a curl command. It could be possible to provide a more explicit HTML link, for clarity.

**Comment by sftim** [comment]
We could have the kubectl install pages link to https://kubernetes.io/releases/download/#binaries

Historically, we had this guide to installing kubectl before https://kubernetes.io/releases/download/#binaries existed. Now that https://kubernetes.io/releases/download/#binaries is a thing, we can link to it.

@crsadun would that suit you?

/retitle Task page for installing kubectl should explain how to find direct download link
/kind feature
/language en

**Comment by sftim** [comment]
This was originally filed about https://k8s.io/docs/tasks/tools/install-kubectl-windows/

**Comment by sftim** [comment]
I did read that page and I can see that there's already a direct download link for https://dl.k8s.io/release/v1.31.0/bin/windows/amd64/kubectl.exe

This is under a slightly misleading heading; the text
> Download the latest 1.31 patch release: [kubectl 1.31.0](https://dl.k8s.io/release/v1.31.0/bin/windows/amd64/kubectl.exe)

is headed:
> ## Install kubectl binary with curl on Windows

so maybe we'd like to change the heading as well? I still recommend linking to the list of binaries you can download.

The existing link does assume amd64 architecture; on the other hand, AMD processors (and Intel clones) are the market leader.

/priority awaiting-more-evidence

**Comment by crsadun** [comment]
Thank you yes the misleading text is probably the main problem - but the list of binaries can also be very useful as the corps who prevent internet access are often the ones who don't run the latest version of any tool :)

The idea is to make it as clearer as possible as it's gonna be the first option for many as opposite to run curs or package managers which aren't so common on Windows.

**Comment by network-charles** [comment]
Hey @sftim, I'd like to work on this.

Based on the discussion, here are my suggestions:
- Let's update the header title to specify a direct download or curl option.
- We should add new paragraphs describing a direct download option for amd64 users and a separate option for other architectures.

I'm not going to change the existing amd64 url reference because it looks like the url below has amd64 listed the most.
https://kubernetes.io/releases/download/#binaries

/assign
