### ISSUE TITLE
Set up a High Availability etcd Cluster with kubeadm

### ISSUE THREAD

**Issue by UnstoppableMango** [kubernetes/website#47668]
The kubeadm config snippet uses the v1beta3 `extraArgs` that is a `map[string]string`, in `v1beta4` this seems to be a [`[]Arg`](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/#kubeadm-k8s-io-v1beta4-LocalEtcd).

**Comment by tengqm** [comment]
Actually, that is how the API changed.
See https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go#L174 for source code,
and https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta4/doc.go#L229-L231
for an example.
/close
