### ISSUE TITLE
Improvement for k8s.io/docs/setup/production-environment/container-runtimes/

### ISSUE THREAD

**Issue by ignbell** [kubernetes/website#47665]
Hi, I installed K8s v.1.30 and v.1.31 following your documentation and had issues with my clusters due to "br_netfilter" module not being enabled

Seems to be that it has been removed from the container runtime pre-requisites in your page as it is listed for v.29

Specifically, I was getting "reply from unexpected source:" when trying to use DNS resolution on my pods tha use Calico as CNI
After enabling the module on my nodes the issue was fixed

Hope it helps, Thanks

**Comment by dipesh-rawat** [comment]
Page reported in issue _(based on the title)_: https://kubernetes.io/docs/setup/production-environment/container-runtimes/
/language en

**Comment by sftim** [comment]
/remove-sig network

AIUI you don't need to enable `br_netfilter` to set up a node. Maybe some container runtimes or network plugins expect it though? If so, the Kubernetes website might not be the right place to explain the interaction.

**Comment by thisisharrsh** [comment]
> you don't need to enable `br_netfilter` to set up a node.

If possible, try disabling `br_netfilter` and see if the issue persists.

**Comment by ignbell** [comment]
> /remove-sig network
> 
> AIUI you don't need to enable `br_netfilter` to set up a node. Maybe some container runtimes or network plugins expect it though? If so, the Kubernetes website might not be the right place to explain the interaction.

Yes, the issue was experienced with the Flannel CNI plugin

I believe you are spot on, sorry to have bothered everyone with this.

**Comment by ignbell** [comment]
Thanks, as stated it should probably be the CNI provider who should specify it's requirenments and not the Kubernetes documentation website

Thanks all

**Comment by T-Lakshmi** [comment]
Closing issue as nothing to fix.
/close
