### ISSUE TITLE
Kubelet Configuration (v1) missing resource types

### ISSUE THREAD

**Issue by anthonyvdotbe** [kubernetes/website#47670]
There are 3 auto-generated pages for `Kubelet Configuration`: one for v1alpha1, v1beta1, and v1.

Expected: the page for `v1` is very similar to `v1beta1`, as the `v1` release came last.

Actual: the [page for v1](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/) seems to match the [one for v1alpha1](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1alpha1/) and is missing several resource types from the [one for v1beta1](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/)

**Comment by tengqm** [comment]
No. Not all definitions has graduated to v1, some definitions have Beta maturity, some definitions are Alpha ones. There could be definitions that both have Alpha and Beta maturity. This is by design rather than a bug.
/close
