### ISSUE TITLE
Network Policies for Port

### ISSUE THREAD

**Issue by anuprd** [kubernetes/website#47689]
I want to use the network policy to block particular ports (22, 23, 80). Do we have any policy to block particular rules, as we did not see any rules regarding that?
Documentation is also minimal for network policy.
Any help will be appreciated

**Comment by dipesh-rawat** [comment]
Looks like a request for help in its current form.

/kind support
_(Feel free to remove the label if this is incorrect.)_

**Comment by dipesh-rawat** [comment]
@anuprd Thank you for reaching out and seeking assistance. We appreciate your query, but the GitHub issue tracker may not be the most suitable platform for obtaining advice on Kubernetes. We recommend exploring alternative resources such as the Kubernetes Slack community (http://slack.k8s.io/) or the Discuss Kubernetes forum (https://discuss.kubernetes.io/) for the support you need.

**Comment by tamilselvan1102** [comment]
@anuprd 
There is no network policy to block particular port but  you can allow range of ports by using [egress](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports).

you can try with third party [network policy provider](https://kubernetes.io/docs/tasks/administer-cluster/network-policy-provider/)

**Comment by niranjandarshann** [comment]
As this is support issue you can raise it in Slack or in community forum . It will be useful to discuss the respective channel.
For now i am closing this issue Try to raise the issue, the bug report, feature request Which will enhance the development the look and feel of the website. 

You may reopen or raise new issue with proper description.
