### ISSUE TITLE
[ja] Translate content/en/docs/reference/glossary/limitrange.md into Japanese

### ISSUE THREAD

**Issue by Okabe-Junya** [kubernetes/website#47684]
_**Note that this issue is for Japanese Speaker**_

**This is a Feature Request**

**What would you like to be added**

Translate `content/en/docs/reference/glossary/limitrange.md` into Japanese

**Why is this needed**

There is no Japanese translation for this page

**Comments**

- File to translate: 
    - https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/limitrange.md
- Original:
    - https://kubernetes.io/ja/docs/reference/glossary/?all=true#term-limitrange

日本語に翻訳する際は、以下のドキュメントを参考にしてください。

- Japanese Localization document: https://kubernetes.io/ja/docs/contribute/localization/

---

/area localization
/language ja
/good-first-issue
/triage accepted

**Comment by VinayakPaka** [comment]
I would like to work on this issue. Can you please assign this issue to me.

**Comment by Okabe-Junya** [comment]
Thank you for showing interest in the Japanese l10n subproject.

As mentioned in the issue description, please note that this is an issue  for Japanese speakers.

> _**Note that this issue is for Japanese Speaker**_

It appears that you are living in India.
If you are a Japanese speaker, feel free to proceed. If not, it would be better to raise your hand for an issue related to Hindi:

- all issues labeled `language/hi`: https://github.com/kubernetes/website/issues?q=is%3Aopen+is%3Aissue+label%3Alanguage%2Fhi

If you decide to proceed, please comment with `/assign`.

(You have commented on some issues, but I recommend working on **one at a time** for your first contribution.)​⬤
