### ISSUE TITLE
Add seccomp page for Node Reference Information

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/website#47687]
The goal is to update https://kubernetes.io/docs/reference/node to link to a dedicated seccomp page, explaining the fields from the pod and container specification.

Per https://github.com/kubernetes/enhancements/issues/135#issuecomment-2300466896

**Comment by VinayakPaka** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by sftim** [comment]
Does this issue have a zero to low barrier to entry @sashagrunert? If not, I'd drop the good-first-issue marker.

**Comment by saschagrunert** [comment]
I think I can take care of that in the 1.32 cycle.

/assign

**Comment by saschagrunert** [comment]
Working on this as part of https://github.com/kubernetes/website/pull/47967
