### ISSUE TITLE
Issue with k8s.io/docs/setup/best-practices/cluster-large/

### ISSUE THREAD

**Issue by PancoCheong** [kubernetes/website#47692]
No more than 110 pods per node

is this a hard limit? I got a powerful hardware that uses only less than 20% of CPU and 15% of RAM, just wonder why the official document suggest not more than 110 pods. I found may post on the internet suggest we can increase this number to higher number  eg. 160 is the default value on DaoCloud that use K8S as the base. 

Just wonder should this pods per node settings related to the CPU and RAM resources on the server?

**Comment by tamilselvan1102** [comment]
Related page:https://kubernetes.io/docs/setup/best-practices/cluster-large/

**Comment by tamilselvan1102** [comment]
110 is the default limit, you can tune it using the --max-pods (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) flag anyway.

**Comment by tamilselvan1102** [comment]
There is some discussion about it. refer [here]( https://github.com/kubernetes/website/issues/42373)

**Comment by sftim** [comment]
We could update the page to clarify whether these are hard limits.

**Comment by T-Lakshmi** [comment]
This issue is already tracking in #42373
Iam closing this issue and suggesting people who are checking this issue to directly refer #42373
