### ISSUE TITLE
Volumes - misspelled word

### ISSUE THREAD

**Issue by emerconnelly** [kubernetes/website#47696]
Under https://kubernetes.io/docs/concepts/storage/volumes/#vsphere-csi-migration, the hyper link
`Migrating In-Tree vSphere Volumes to vSphere Container Storage lug-in` is missing a "P" in "Plug-in".

Corrected: `Migrating In-Tree vSphere Volumes to vSphere Container Storage Plug-in`

**Comment by tamilselvan1102** [comment]
related page : https://kubernetes.io/docs/concepts/storage/volumes/#vsphere-csi-migration

**Comment by emerconnelly** [comment]
@tamilselvan1102 @mengjiao-liu Thanks 😄
