### ISSUE TITLE
Adding entries to Pod /etc/hosts with HostAliases

### ISSUE THREAD

**Issue by GergelyMolnar** [kubernetes/website#47700]
Hi, 

On this page: https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
I found a sentence that is hard to understand because of the double negative.

The sentence is in the first paragraph:
"""
Modification not using HostAliases is not suggested because the file is managed by the kubelet and can be overwritten on during Pod creation/restart.
"""

It would be easier to read and understand by replacing the double negative:
"Modification using the HostAliases field in the PodSpec is recommended because changes made in other ways may be overwritten by the kubelet during Pod creation or restart."

o7

**Comment by dipesh-rawat** [comment]
Hi @GergelyMolnar Could you please provide the URL of the page in the issue where you are suggesting an improvement?

/triage needs-information

**Comment by GergelyMolnar** [comment]
Sure, the page is here: https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/

**Comment by tamilselvan1102** [comment]
Good spotting it. it should be corrected.
I would like to work on it if triage accepted.

**Comment by niranjandarshann** [comment]
I think the issue is resolved as the PR get merged. 
So closing this issue.
/close
