### ISSUE TITLE
Command line tool (kubectl)

### ISSUE THREAD

**Issue by enzoxic** [kubernetes/website#47701]
to build a K8 on docker & link it to GitHub via it's vs code cloud version

**Comment by dipesh-rawat** [comment]
@enzoxic This [description (here)](https://github.com/kubernetes/website/issues/47701#issue-2488758871) doesn't provide enough information to evaluate the issue or determine if any action is needed. Could you please provide more details about the problem you're reporting or the help you need? Please include these details in the issue [description](https://github.com/kubernetes/website/issues/47701#issue-2488758871).

/triage needs-information

**Comment by enzoxic** [comment]
great thx for your feedback let me prepare all...

**Comment by enzoxic** [comment]
<img width="2560" alt="Capture d’écran 2024-08-27 à 14 48 41" src="https://github.com/user-attachments/assets/e08530b7-d947-4ed6-9970-22ed320832ea">

**Comment by tengqm** [comment]
Is this a bug report or a spam?

**Comment by enzoxic** [comment]
a bug

**Comment by enzoxic** [comment]
I was just testing the cloud version cause I am migrating those kind of services directly by the cloud to avoid any conflit with my own system. I am sorry if you are disturbed by my request but it wasn't my purpose
________________________________
De : Qiming Teng ***@***.***>
Envoyé : mardi 27 août 2024 14:57
À : kubernetes/website ***@***.***>
Cc : enzoxic ***@***.***>; Manual ***@***.***>
Objet : Re: [kubernetes/website] Command line tool (kubectl) (Issue #47701)


Is this a bug report or a spam?

**Comment by enzoxic** [comment]
I am sorry about this issue but it's sems that I need still to first focus on the basic configuration of my cloud computing services ! all my bad for the disturbances and a great thx to all of you for your prompt risponse
________________________________
De : Sean McGinnis ***@***.***>
Envoyé : mardi 27 août 2024 15:25
À : kubernetes/website ***@***.***>
Cc : enzoxic ***@***.***>; Manual ***@***.***>
Objet : Re: [kubernetes/website] Command line tool (kubectl) (Issue #47701)


Please edit the issue description with an actual description of the bug you are seeing and what you think is needed. So far I can't tell what it is you are asking for or trying to point out.

**Comment by dipesh-rawat** [comment]
/close not-planned

Closing as this is an unrelated issue. Nothing to fix in Kubernetes docs.
