### ISSUE TITLE
API documentation: query parameters are four asterisks ("****")

### ISSUE THREAD

**Issue by t4lz** [kubernetes/website#47722]
See for example [the documentation for `list` for `Pod`](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#list-list-or-watch-objects-of-kind-pod):

![image](https://github.com/user-attachments/assets/b502d03d-d734-4c2f-ae03-f7790f393159)

**Comment by dipesh-rawat** [comment]
/triage duplicate

This looks duplicate of an issue we already have https://github.com/kubernetes/website/issues/47694
