### ISSUE TITLE
Taints and Tolertaions Document: An unfinished sentence

### ISSUE THREAD

**Issue by anneheartrecord** [kubernetes/website#47737]
**This is a Bug Report**

**Problem:**
Here is an unfinished sentence in https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
language: en

**Proposed Solution:**
I want to change the "or" to "and the key should included".  https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
And change the chinese document to "则键的值需要被包含" https://kubernetes.io/zh-cn/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition

**Page to Update:**
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
![WechatIMG60237](https://github.com/user-attachments/assets/2008bd57-32e2-4be6-9bd8-05017c5ad457)

**Comment by anneheartrecord** [comment]
I want to work on this issue.Could please assign this to me?

**Comment by tengqm** [comment]
/remove-triage
This doesn't look like an error.
Neither of the conditions are talking about the `key` key and the existence of that key is implied.

**Comment by anneheartrecord** [comment]
> /remove-triage This doesn't look like an error. Neither of the conditions are talking about the `key` key and the existence of that key is implied.

Yeap, It's implied.
But it's difficult to understand the purpost of the 'or' word.
So the solution is delete the 'or' from this sentence?

**Comment by tengqm** [comment]
It is not uncommon to append an "or" in this case, especially for English text.
If you really believe that the "or" confuses Chinese readers, you can propose a fix to Chinese localization.

**Comment by anneheartrecord** [comment]
Thanks for your patient comment.It's very useful to me.

**Comment by anneheartrecord** [comment]
> It is not uncommon to append an "or" in this case, especially for English text. If you really believe that the "or" confuses Chinese readers, you can propose a fix to Chinese localization.

Thanks for your patient comment.It's very useful to me.

**Comment by reylejano** [comment]
On the English site, this does not look like an error
the "or" continues to the next bullet
/close
