### ISSUE TITLE
[pt-br] Install kubectl on Linux page is outdated

### ISSUE THREAD

**Issue by osnibjunior** [kubernetes/website#47748]
**This is a Bug Report**

**Problem:** The repository of Kubectl used in **Portuguese** documentation version is wrong when you use the option `Instale usando o gerenciador de pacotes nativo`

```bash
$ curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
$ echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
```

* Result:
```bash
$ sudo apt-get update
Ign:4 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Err:8 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 172.217.29.142 443]
Reading package lists... Done
E: The repository 'https://apt.kubernetes.io kubernetes-xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Proposed Solution:** Change the repository to the same in **English** version

```bash
$ curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
$ echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
```

* Result:
```bash
$ sudo apt-get update
Get:2 https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.31/deb  InRelease [1186 B]
Get:3 https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.31/deb  Packages [3602 B]
```

**Page to Update:**
https://kubernetes.io/pt-br/docs/tasks/tools/install-kubectl-linux/ (I saw this problem in Portuguese documentation ony).

**Comment by dipesh-rawat** [comment]
It looks like this issue is due to outdated information in the Brazilian Portuguese documentation compared to the English version of the Install kubectl guide on the main [website](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/).

/language pt

**Comment by stormqueen1990** [comment]
This will require a sync between the English version and the Portuguese version.

/triage accepted
/retitle [pt-br] Install kubectl on Linux page is outdated
/help

**Comment by moreirayokoyama** [comment]
Am I allowed to assign this task to myself? (I'm already working on it)
