### ISSUE TITLE
`trafficDistribution` shows as alpha despite graduating to beta in v1.31

### ISSUE THREAD

**Issue by BBBmau** [kubernetes/website#47776]
**This is a documentation mismatch Report**

**Problem:**
I was looking over the `v1.31` release notes and when looking into `trafficDistribution` i noticed that the docs show that it's still in alpha yet when we look into the [feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), [PR](https://github.com/kubernetes/enhancements/issues/4444), and [service documentation page](https://kubernetes.io/docs/concepts/services-networking/service/#traffic-distribution) it says that it's now in a beta state.
**Proposed Solution:**

We'll want to update the docs to prevent any confusion for future users

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#service-v1-core

`v1.31`

**Comment by robert-cronin** [comment]
I believe you're correct @BBBmau, thank you for spotting it! It looks like this is part of the auto generated docs. I will add a PR with a fix.

/sig network

**Comment by sftim** [comment]
/retitle `trafficDistribution` shows as alpha despite graduating to beta in v1.31

For this repo, we can take the docs part as a given.

**Comment by sftim** [comment]
The same upstream change would fix https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
