### ISSUE TITLE
Workloads - 'Pod' Capitalization

### ISSUE THREAD

**Issue by ShuyangZheng** [kubernetes/website#47801]
Hi, I found on this page that 'Pod' is sometimes capitalized, and sometimes not. As I learned from other sources that "'Pod' should technically always be capitalized for clarity and uniformity." I wonder if that is the case, and should we improve consistency here?

**Comment by tengqm** [comment]
see: https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects

**Comment by tamilselvan1102** [comment]
@ShuyangZheng 
please mention which page do you find the contradictory.

**Comment by ShuyangZheng** [comment]
> @ShuyangZheng please mention which page do you find the contradictory.

https://kubernetes.io/docs/concepts/workloads/

**Comment by tamilselvan1102** [comment]
As per the [guide line](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects), it should be Pods not pods.

**Comment by tamilselvan1102** [comment]
you can raise a pr if triage accepted

**Comment by ShuyangZheng** [comment]
> As per the [guide line](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects), it should be Pods not pods.

Well...In the [guideline](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects) itself there are multiple occurences of 'pod' and 'pods'. So, I'm not sure if it matters after all.

**Comment by reylejano** [comment]
@ShuyangZheng , according to the style guide API objects should use upper camel case and if its not referring to API objects then sentence case is used.
There are examples in the style guide itself where Pod/pod are used so it depends on how Pod/pod is used on the page.
I'll close this issue for now but if you have specific examples, feel free to create a new issue sighting the specific examples
Thank you
/close
