### ISSUE TITLE
Fix missing hyphen in NetworkPolicy example for ports field

### ISSUE THREAD

**Issue by dhkim1206** [kubernetes/website#47816]
**This is a Bug Report**

**Problem:**
In the official Kubernetes documentation, the `NetworkPolicy` example omits the required `-` (hyphen) for the `ports` field under `ingress` and `egress`. This can cause confusion, as `ports` is an array and each item in an array must start with a `-`. Failing to include the hyphen may lead to YAML validation errors when applied.

**Proposed Solution:**
Update the `NetworkPolicy` example to correctly include the `-` in front of `ports` items under both `ingress` and `egress`.

For example, the following block should include a hyphen for the `ports` array:
```yaml
    ports:
    - protocol: TCP
      port: 6379

**Comment by tamilselvan1102** [comment]
related page: https://kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by tamilselvan1102** [comment]
it is in correct format, no need of any correction
Refer [here](https://github.com/kubernetes/website/issues/44214)

**Comment by dhkim1206** [comment]
👍👍👍

**Comment by dhkim1206** [comment]
👍👍👍

**Comment by dhkim1206** [comment]
👍👍👍
