### ISSUE TITLE
Deprecated note/link on page "Set up a High Availability etcd Cluster with kubeadm"

### ISSUE THREAD

**Issue by DC4JG** [kubernetes/website#47818]
The note at the top of [the page](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) states that in regards to certificate rotation "The long-term plan is to empower the tool [etcdadm](https://github.com/kubernetes-sigs/etcdadm) to manage these aspects.".

The linked etcdadm repository was archived on Jul 16, 2024 and is part of [Kubernetes Retired](https://github.com/kubernetes-retired).

Is there some other tool available for the stated feature set (then please update the note) or is this note deprecated and support/development was dropped? A quick search yielded [this issue](https://github.com/kubernetes/org/issues/5013) linking [etcd-manager](https://github.com/kubernetes-sigs/etcd-manager) as possible successor but I'm not qualified to provide further insight.

I'm just a newbie reading the docs and noticing a "dead" link in the documentation 😇

**Comment by neolit123** [comment]
> The note at the top of [the page](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/) states that in regards to certificate rotation "The long-term plan is to empower the tool [etcdadm](https://github.com/kubernetes-sigs/etcdadm) to manage these aspects.".

etcdadm used etcd-manager but we don't have a direct CLI replacement to apply in the docs. so +1 to remove the note for the time being,

/sig cluster-lifecycle
/help
/kind deprecation
/triage accepted

steps:
- edit the page https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
- remove the note:

```
Note:
While kubeadm is being used as the management tool for external etcd nodes in this guide, please note that kubeadm does not plan to support certificate rotation or upgrades for such nodes. The long-term plan is to empower the tool [etcdadm](https://github.com/kubernetes-sigs/etcdadm) to manage these aspects.
```

- send a PR for this repository's `main` branch

**Comment by T-Lakshmi** [comment]
Assigning back to @steve-hardman as [PR](#48120) raised and waiting for approval.
/assign @steve-hardman
