### ISSUE TITLE
Authenticating with Bootstrap Tokens

### ISSUE THREAD

**Issue by Harry5012** [kubernetes/website#47859]

**Comment by tamilselvan1102** [comment]
please describe the issue

**Comment by niranjandarshann** [comment]
closing this issue as no description is provided.
@Harry5012  you may raise the issue again with the proper and clear description.For  now closing this issue
marking as not Planned.
/close not planned

**Comment by niranjandarshann** [comment]
Marking as not Planned 
closing this issue
/close
