### ISSUE TITLE
Logo overlaps with other nav bar elements when search bar is present (on Firefox)

### ISSUE THREAD

**Issue by holistic-developer** [kubernetes/website#47889]
**This is a Bug Report**

**Problem:**
On Firefox the kubernetes logo overlaps with other navbar items on .../docs pages when the search bar is present.
![image](https://github.com/user-attachments/assets/556c6c39-1457-4256-9652-809bac915706)

**Proposed Solution:**
Decrease the size of the search bar.

**Page to Update:**
All pages using the `layouts/partials/navbar.html` which is mostly https://kubernetes.io/docs/

**Additional Information**
I used Firefox version 130 on Mac with a resolution of 1512 x 982

**Comment by thisisharrsh** [comment]
I would to like to work on this issue.

**Comment by thisisharrsh** [comment]
Facing the same issue at 1512 * 982 resolution. 
![Screenshot from 2024-09-12 10-24-15](https://github.com/user-attachments/assets/1baa7432-893e-4ed4-9263-3e6c807b002e)

**Comment by sftim** [comment]
My suggestion: drop the **Case Studies** section.

**Comment by thisisharrsh** [comment]
> drop the **Case Studies** section.

I am planning to adjust the CSS properties for the page at the given size. But I will consider your suggestion also.

**Comment by holistic-developer** [comment]
> My suggestion: drop the **Case Studies** section.
I would advise against that.

Here is how it is rendered in chrome at the same resolution:
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/8a6a1707-bdf6-4983-a004-6b7ab834b078">
and again on Firefox
![image](https://github.com/user-attachments/assets/60c880d6-b608-49f2-b7bf-61dad61f7507)
So, the actual issue is the **size of the search bar**.

**Comment by thisisharrsh** [comment]
Thanks @holistic-developer, for the issue rectification.

**Comment by sftim** [comment]
@holistic-developer several changes could help:
- Managing the size of the search bar
- Dropping the case studies section, which is no longer current
- Improving how the top nav adapts to the available space (for example, on narrow viewports, we could have an icon rather than a bar for search; clicking the icon could take you to `/search`)

**Comment by thisisharrsh** [comment]
The issue is fixed [here. ](https://github.com/kubernetes/website/pull/47984)
