### ISSUE TITLE
Improvement for k8s.io/en/docs/setup/production-environment/windows/user-guide-windows-nodes/

### ISSUE THREAD

**Issue by smirnapaz** [kubernetes/website#47887]
this guide is filed with 404 errors of links that don't exist and scripts that aren't there. Is there anything about this that is updated?

**Comment by aryasoni98** [comment]
@sftim This issue is still open?

**Comment by T-Lakshmi** [comment]
@smirnapaz @aryasoni98,

[As mentioned](https://github.com/kubernetes/website/issues/47887#issuecomment-2343640561) here, nothing to fix in this.
This page doesn't exist now. If you are looking for user guide for windows nodes adding to kubeadm, please follow below URL:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/
