### ISSUE TITLE
Add “duration” to glossary

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#47909]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/reference/glossary/ to include an entry for [what Kubernetes means by a] _duration_.

**Why is this needed**
There are specific rules for what goes in a duration field in our API; a glossary entry will help here.

**Comments**
/wg api-expression
/language en

Anyone is welcome to send in a PR for this.

For tips on what to explain, try this search: [_Go time.Duration Kubernetes_](https://www.google.com/search?q=Go+time.Duration+Kubernetes)

**Comment by Ritikaa96** [comment]
I'll be happy to work on this.
/assign

**Comment by Ritikaa96** [comment]
Hi @aryasoni98 as you can see , I have assigned this issue to myself earlier , please ask before assigning it to yourself .

**Comment by sftim** [comment]
For Kubernetes SIG Docs, anyone can work on any issue (our more jargon-y way of saying this is “no [cookie licking](https://devblogs.microsoft.com/oldnewthing/20091201-00/?p=15843)”) and open a pull request to propose a related change.
