### ISSUE TITLE
HTML Code Tags Displayed Incorrectly in Ephemeral Storage Consumption Management Documentation

### ISSUE THREAD

**Issue by r21gh** [kubernetes/website#47934]
**This is a Bug Report**

**Problem:**
On the Kubernetes documentation page for Ephemeral Storage Consumption Management (https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-emphemeralstorage-consumption), under the "Filesystem project quota" tab, HTML `<code>` tags are being displayed incorrectly. This results in the raw HTML code being visible instead of the intended formatted content.

**Proposed Solution:**
The HTML `<code>` tags should be removed from the displayed content, and the text should be properly rendered without the raw HTML markup. The content should be reviewed and corrected to ensure it is presented in a readable and user-friendly format.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

The issue affects the "Ephemeral Storage Consumption Management" section, specifically under "Filesystem project quota." The incorrect display of HTML tags may impact user understanding and the overall readability of the documentation.

**Comment by AmarNathChary** [comment]
/sig docs
/assign
I will raise a PR for this issue

**Comment by sftim** [comment]
/triage accepted

Good to fix
/help
/priority backlog

**Comment by AmarNathChary** [comment]
> The HTML <code> tags should be removed from the displayed content,

Even after removing the <code> tags, the page is still showing raw HTML.

**Comment by sftim** [comment]
The fix here is either to revise how far things are indented (likely), or perhaps to swap between `{{<` / `>}}` and `{{%` / `%}}` shortcode markers (less likely).
