### ISSUE TITLE
Garbage Collection: Background deletion explanation is hard to understand

### ISSUE THREAD

**Issue by guettli** [kubernetes/website#47956]
Page: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#background-deletion

> Background cascading deletion

> In background cascading deletion, the Kubernetes API server deletes the owner object immediately and the controller cleans up the dependent objects in the background. By default, Kubernetes uses background cascading deletion unless you manually use foreground deletion or choose to orphan the dependent objects.

I have problems understanding this text.

First: If I read that, then I think Finalizers seem to get ignored if you use background-deletion. But I don't think so.

Second: "... the controller cleans up the dependent objects". What is "the controller" here? If I have a custom controller for my CRDs. Is that meant with "the controller"?

**Comment by sftim** [comment]
/retitle Garbage Collection: Background deletion explanation is hard to understand

**Comment by Nishant-k-sagar** [comment]
If there is still room to work on this issue, I would like to work on this. @guettli 
@ayushpatil2122 
Kindly assign this to me
