### ISSUE TITLE
Improvement for k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/

### ISSUE THREAD

**Issue by Zwiqler94** [kubernetes/website#47973]
There's no tutorial on this page...

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/42401

**Comment by dipesh-rawat** [comment]
This looks similar to issue we already have https://github.com/kubernetes/website/issues/42401
I think it is a duplicate.

/triage duplicate

**Comment by niranjandarshann** [comment]
The issue seems duplicate so for now I am closing this issue and if you have any new issue that is already not raised earlier you may raise the issue . Thank you for your contribution.

**Comment by niranjandarshann** [comment]
Keep contributing 
closing this issue 
/close
