### ISSUE TITLE
Possible YAML issue on "Using RBAC Authorization" page

### ISSUE THREAD

**Issue by limck5856** [kubernetes/website#47985]
**This is a Bug Report**

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by dipesh-rawat** [comment]
/retitle Possible YAML issue on "Using RBAC Authorization" page

_(Based on the example YAML on the [page (here)](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#write-access-for-endpoints))_

**Comment by dipesh-rawat** [comment]
@limck5856 This [description (here)](https://github.com/kubernetes/website/issues/47985#issue-2533815092) doesn't provide enough information to evaluate the issue or determine if any action is needed. Could you please provide more details about the problem you're reporting or the help you need? Please include these details in the issue [description](https://github.com/kubernetes/website/issues/47985#issue-2533815092). Currently, it appears to resemble spam.

**Comment by dipesh-rawat** [comment]
/close not-planned

You are welcome to reopen this and add [details](https://github.com/kubernetes/website/issues/47985#issue-2533815092).
