### ISSUE TITLE
1.31.0 release is missing from https://kubernetes.io/releases/patch-releases

### ISSUE THREAD

**Issue by snasovich** [kubernetes/website#47990]
**This is a Bug Report**

**Problem:** 1.31.0 release is missing from https://kubernetes.io/releases/patch-releases/#1-31 (while .0 releases are present for previous minor releases).

**Proposed Solution:** Have 1.31.0 listed (unless it was pulled from general use for some reason - which I'm not aware of)

**Page to Update:**
https://kubernetes.io/releases/patch-releases

Additional Information:
![image](https://github.com/user-attachments/assets/6547ad8f-5459-4c2a-9db7-2c2c25e2e4dd)

**Comment by dipesh-rawat** [comment]
The data on this [table](https://kubernetes.io/releases/patch-releases/#1-31) is sourced from the file updated by [schedule-builder](https://github.com/kubernetes/release/tree/master/cmd/schedule-builder). It seems like we might need to adjust the builder logic or possibly do a manual update in this particular case. Needs some investigation further to identify the best approach.

@saschagrunert (apologies for the ping!), tagging you for visibility and any suggestions you might have for the ideal solution. Thanks in advance!

**Comment by saschagrunert** [comment]
@dipesh-rawat yes in theory we have to adapt schedule builder: https://github.com/kubernetes/release/blob/27310fb3f16ee2c1ef7d4f71d30ab9b0dc9c642c/cmd/schedule-builder/cmd/markdown.go#L191

I'm not sure we can actually solve this with the current set of available information, because we literally don't know from the input when the v1.31.0 release happened.

**Comment by saschagrunert** [comment]
We can add the release manually for now in https://github.com/kubernetes/website/pull/47998

**Comment by dipesh-rawat** [comment]
Looks like the issue has been [fixed](https://kubernetes.io/releases/patch-releases/#1-31) as part of PR https://github.com/kubernetes/website/pull/47998

/close
