### ISSUE TITLE
Kubelet Configuration (v1beta1): CredentialProvider apiVersion

### ISSUE THREAD

**Issue by wkd3475** [kubernetes/website#48009]
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-CredentialProvider

Target: apiVersion

AS-IS:
```
CredentialProviderResponse MUST use the same encoding version as the input. Current supported values are:

credentialprovider.kubelet.k8s.io/v1beta1
```
TO-BE:
```
CredentialProviderResponse MUST use the same encoding version as the input. Current supported values are:

credentialprovider.kubelet.k8s.io/v1
```

It is my understanding that version v1 can be used, so it seems necessary to review and update the documentation accordingly.

**Comment by mengjiao-liu** [comment]
For the v1 version, please refer to this document: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/

**Comment by tengqm** [comment]
We will not fix the generated docs. Please fix this in the upstream source repo.
/close
