### ISSUE TITLE
Incorrect driver details in StorageClass concept page

### ISSUE THREAD

**Issue by imuneeeb** [kubernetes/website#48049]
**This is a Bug Report**

**Problem:**
It seems there is a  issue where content from separate PRs, especially those touching the same or related sections, gets mixed up during the merging process. This causes incorrect or misplaced content in the documentation, affecting the accuracy and clarity.

**Problem Example:**

I recently submitted two PRs (focused on different AWS CSI drivers) for the Kubernetes documentation:
1. **[Add AWS EFS To storage-classes.md](https://github.com/kubernetes/website/pull/47928)**
2. **[Update AWS EBS Storage Class Example](https://github.com/kubernetes/website/pull/47894)**

After the merge, the **`tagSpecification`** parameter (which is specific to AWS EBS) was mistakenly placed in the AWS EFS StorageClass section. This is an example of how content from related PRs can become interleaved or incorrectly positioned during merges.

**Proposed Solution:**

Update branch button on PR can help avoiding such issues.

**Comment by sftim** [comment]
We're not looking to change people's use of Git, not just yet. However we can track a bug about `content/en/docs/concepts/storage/storage-classes.md`

/retitle Incorrect driver details in StorageClass concept page
/language en
/triage accepted

---

One tip: set a PR description for each pull request, and mention any potentially conflicting PRs if you know of any.
