### ISSUE TITLE
Kubeadm

### ISSUE THREAD

**Issue by 15003476628** [kubernetes/website#48059]

**Comment by Adarsh-verma-14** [comment]
@15003476628, I am not getting what you are looking for . So please raise the valid issue with correct description .

**Comment by dipesh-rawat** [comment]
@15003476628  This [description (here)](https://github.com/kubernetes/website/issues/48059#issue-2544120421) doesn't provide enough information to evaluate the issue or determine if any action is needed. Could you please provide more details about the problem you're reporting or the help you need? Please include these details in the issue [description](https://github.com/kubernetes/website/issues/48059#issue-25441204212). Currently, it appears to resemble spam.

**Comment by dipesh-rawat** [comment]
/close not-planned

You are welcome to reopen this and add [details](https://github.com/kubernetes/website/issues/48059#issue-2544120421).
