### ISSUE TITLE
Duplicated description for scheduling index page

### ISSUE THREAD

**Issue by r21gh** [kubernetes/website#48126]
**This is a Bug Report**

**Problem:**
The description and its proceeding text on the scheduling index page are almost duplicated. 

**Proposed Solution:**
The following text on the index page needs to be removed:
> In Kubernetes, scheduling refers to making sure that [Pods](https://kubernetes.io/docs/concepts/workloads/pods/) are matched to [Nodes](https://kubernetes.io/docs/concepts/architecture/nodes/) so that the [kubelet](https://kubernetes.io/docs/reference/generated/kubelet) can run them. Preemption is the process of terminating Pods with lower [Priority](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) so that Pods with higher Priority can schedule on Nodes. Eviction is the process of terminating one or more Pods on Nodes.

**Page to Update:**
[scheduling-eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/)

/language en

**Comment by sftim** [comment]
I have a specific fix in mind: suppress the display of the page description at the start of the page. That way, we retain the tooltips that we want, and we avoid the duplication.
