### ISSUE TITLE
Messy indentation on kubeadm config reference page

### ISSUE THREAD

**Issue by J0nathan1ei** [kubernetes/website#48139]
The indentation of the example configuration is messy.
https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/
![image](https://github.com/user-attachments/assets/6a94da22-0b75-44f1-ba1c-85efa1d95cf0)

**Comment by T-Lakshmi** [comment]
/kind bug
/language en
page: https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/

**Comment by T-Lakshmi** [comment]
Also Consider to remove the [broken link](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/#kubeadm-k8s-io-v1beta3-InitConfiguration) exist in the same page under [BootstrapToken](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/#BootstrapToken).

Note: This page is automatically generated, you are not allowed to directly change the documentation page.

**Comment by sftim** [comment]
/retitle Messy indentation on kubeadm config reference page

**Comment by tengqm** [comment]
PR #48143 sent for website.
PR https://github.com/kubernetes-sigs/reference-docs/pull/378 sent for the generator.
