### ISSUE TITLE
Typo in auto-generated Policy Resources API reference

### ISSUE THREAD

**Issue by jputrino** [kubernetes/website#48182]
In the auto-generated [Policy Resources API reference page](https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/), there is a minor typo in the description for [ValidatingAdmissionPolicyBinding](https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/validating-admission-policy-binding-v1/):

"paramerized" should be "parameterized"

<img width="800" alt="image" src="https://github.com/user-attachments/assets/7f8a1b2b-daca-4d9c-95b3-d8f1a9db476d">

**Comment by tengqm** [comment]
Please send your PRs to kubernetes/kubernetes repo for fixing generated docs.
