### ISSUE TITLE
Link from "Sidecar Containers" concept page to detail about termination behavior

### ISSUE THREAD

**Issue by nathanperkins** [kubernetes/website#48290]
This page should have a section discussing how sidecar termination is handled during pod termination. Specifically, it is important to know that they are terminated in reverse order, one by one.

Edit: I found information about it in a different page, maybe a link would be appropriate: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#termination-with-sidecars

**Comment by dipesh-rawat** [comment]
Page reported in issue _(based on the initial title)_: https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
/language en

**Comment by dipesh-rawat** [comment]
/retitle Improve "Sidecar Containers" concept page by adding sidecar termination behavior
/sig node
/kind feature

**Comment by sftim** [comment]
+1 to adding the hyperlink

/triage accepted
/priority backlog
/retitle Link from "Sidecar Containers" concept page to detail about termination behavior
