### ISSUE TITLE
Wrong content detail in API reference page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#48303]
**This is a Bug Report**

**Problem:**

The Kubernetes API Concepts page shows a request made with request header `Content-Type: json`, which isn't the correct media type.

**Proposed Solution:**
Change `Content-Type: json` to `Content-Type: application/json`

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/api-concepts/#json-encoding

**Additional Information:**
/language en
/priority backlog
/kind bug

**Comment by sftim** [comment]
This issue is ideal for a contributor making their very first Kubernetes contribution.

**Comment by palSagnik** [comment]
@sftim Hello I have been meaning to contribute to open-source and this could be my first contribution. Can I be assigned this task?

**Comment by awgrass** [comment]
Hi, I would love to make this contribution.

**Comment by philipsabri** [comment]
@palSagnik 

> Hello I have been meaning to contribute to open-source and this could be my first contribution. Can I be assigned this task?

You can assign it to yourself by commenting `/assign` and then start working on it 😊

**Comment by palSagnik** [comment]
Thank you for your help sir
