### ISSUE TITLE
Documentation incorrectly states no API server `application/yaml` support

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#48317]
**This is a Bug Report**

**Problem:**
Kubernetes' API server supports [YAML](https://yaml.org/) (for encoding request bodies, or for a negotiated response format), but the documentation says it does not.

**Proposed Solution:**
Add a section within https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources about `application/yaml`, and remove the note that says you can't use YAML.

Also see https://github.com/kubernetes/website/issues/48317#issuecomment-2408951197

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/api-concepts/#alternate-representations-of-resources

**Additional Information:**
/language en
/kind bug
/triage accepted
/priority important-longterm
/wg api-expression

**Comment by tengqm** [comment]
Also the code returned when an unsupported media-type is specified should be 415. E.g.

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the body of the request was in an unknown format - accepted media types include: application/json, application/yaml, application/vnd.kubernetes.protobuf",
  "reason": "UnsupportedMediaType",
  "code": 415
}
```

**Comment by sftim** [comment]
AIUI it's 415 for unaccepable request bodies, and 406 Not acceptable if you try something like:

```
GET /api/v1/pods HTTP/1.1
…
Accept: application/fictional

```
(ie, when there's an empty intersection between server supported response types and client accepted media types)

**Comment by tengqm** [comment]
Experiments showed that:

- Unacceptable `Accept` header leads to `406: Not Acceptable`;
- Unacceptable `Content-Type` header leads to `415 UnsupportedMediaType`.

**Comment by sftim** [comment]
/retitle Documentation incorrectly states no API server `application/yaml` support

Describing the bug, not the fix

**Comment by sftim** [comment]
Thanks @abhilasha2418!
