### ISSUE TITLE
Incorrect Display of HTML Code Tags in Declarative Config Task

### ISSUE THREAD

**Issue by r21gh** [kubernetes/website#48323]
**This is a Bug Report**

**Problem:**
In the section for deleting objects managed by `kubectl apply`, HTML tags are displayed incorrectly for the alternative approach. This results in the raw HTML code being visible instead of the intended formatted content.

**Proposed Solution:**
Using Go comment tags `{{- /* Comment Text here */ -}}` along with the `-` character to control whitespace in the `layouts/shortcodes/features-state.html file`, ensuring proper indentation while preventing unwanted line breaks or spaces in the rendered HTML output.

**Page to Update:**
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/#alternative-kubectl-apply-f-directory-prune

/sig docs
/assign
/language en

**Comment by dipesh-rawat** [comment]
Would be nice to fix this.

/triage accepted

**Comment by AmarNathChary** [comment]
I will fix this 
/assign
