### ISSUE TITLE
kubeadm-join: misleading paragraph

### ISSUE THREAD

**Issue by dejanu** [kubernetes/website#48399]
First sentence from [kubeadm-join](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/)  it's a little bit misleading:
_"This command initializes a Kubernetes worker node and joins it to the cluster.
Run this on any machine you wish to join an existing cluster"_
For newcomers it might be understand as it's applicable only for worker nodes.

**Comment by T-Lakshmi** [comment]
> leave another comment here that you have a PR

PR Raised for this issue #48400.

**Comment by T-Lakshmi** [comment]
Hey @achrefothmani,

> PR Raised for this issue https://github.com/kubernetes/website/pull/48400.

FYI, PR #48400 is already raised by @dejanu for this issue and its in active progress.
