### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/gce/

### ISSUE THREAD

**Issue by mustafa-almulla** [kubernetes/website#48440]
I am getting the below error 

Creating firewall...
./cluster/../cluster/../cluster/gce/util.sh: line 729: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
..Created [https://www.googleapis.com/compute/v1/projects/thara-dev-412507/global/firewalls/kubernetes-minion-all].
done.
NAME                   NETWORK  DIRECTION  PRIORITY  ALLOW                     DENY  DISABLED
kubernetes-minion-all  default  INGRESS    1000      tcp,udp,icmp,esp,ah,sctp        False
Failed to create firewall rule.

**Comment by sftim** [comment]
https://k8s.io/docs/getting-started-guides/gce/ is not a page we serve. I wonder if perhaps you have used a time machine @mustafa-almulla ? (more seriously: maybe you looked at a very old unofficial copy of the docs?)

/triage needs-information

**Comment by mustafa-almulla** [comment]
Since I was referring to an old page
