### ISSUE TITLE
Trouble installing kubeadm using advice from pkgs-k8s-io-introduction article

### ISSUE THREAD

**Issue by denniswholly** [kubernetes/website#48443]
The repos for gpg key used to install kubeadm aren't reachable, I tried for v1.28 | 1.29 | 1.30 

![image](https://github.com/user-attachments/assets/153f49bf-095c-4c9f-af91-b2fb3b03362d)

I also tried manually creating the gpg key after downloading the public key that did not work either

![image](https://github.com/user-attachments/assets/f14bbf09-afe4-45c6-b79b-d3ec3e183fd0)

now I can reach the repo hosted on [SUSE](https://software.opensuse.org/download/package?package=cri-tools&project=isv%3Akubernetes%3Acore%3Astable%3Av1.28#manualUbuntu) so I'm not sure the issue is from me (for context I spotted this because I created a master-node with this [version](https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/#how-to-migrate-deb) and some three minutes later I was hitting error 403 trying to do same for the worker-node)

Maybe I am missing something?

**Comment by sftim** [comment]
Hi @denniswholly 

What web page are you following instructions from? It may be out of date.
Provide the URL of that page if you can.

/triage needs-information

**Comment by sftim** [comment]
/remove-triage needs-information

Got it. The blog post says:
> Download the public signing key for the Kubernetes package repositories. The same signing key is used for all repositories, so you can disregard the version in the URL:

and we could correct it to:
> Download the public signing key for the Kubernetes package repositories. Change the version number in the command below to match the most recent minor release of Kubernetes.

But, to be honest, I think we should make a different edit. What we can do is clearly signpost readers to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl so that they follow the current documentation, rather than a blog post from last year. The blog article was correct at the time of publication but things have moved on.

**Comment by sftim** [comment]
/retitle Trouble installing kubeadm using advice from pkgs-k8s-io-introduction article

The key learning point is: https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/ is a migration guide (that people followed last year), not an install guide.

/priority awaiting-more-evidence

Fixes are kind of OK, but mainly "don't do that" is my advice here.

**Comment by denniswholly** [comment]
oh hey @sftim thank you for chipping in on this. I understand that's a guide, I actually used the official Kubeadm install pages too, but funny thing once I deployed a new server to the US region (the initial was in Europe) it suddenly worked. I didn't change anything just a switch in regions of server. I'm just going to chuck it up to one of those weird glitches 😀 
Thanks!
