### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/

### ISSUE THREAD

**Issue by jerry42** [kubernetes/website#48459]
Hello,

I think the "Start Interactive Tutorial" link is missing on this page

**Comment by Shubham82** [comment]
Hi @jerry42 
This looks similar to the issue we already have #4240, PTAL!

/triage duplicate

**Comment by Shubham82** [comment]
Closing this issue, has already issue opened for it.

If you have any concerns related to this issue, feel free to continue the discussion on the issue https://github.com/kubernetes/website/issues/42401.

/close
