### ISSUE TITLE
1.31 metrics reference is out of date and doesn't match the code

### ISSUE THREAD

**Issue by mengqiy** [kubernetes/website#48538]
**This is a Bug Report**

**Problem:**

1.31 metrics reference is out of date and doesn't match the code.
e.g. `scheduler_event_handling_duration_seconds` is a metrics that exist in 1.31, but the doc doesn't have it.

**Proposed Solution:**

IIUC metrics reference  is generated. We should regenerate it to make it up to date.

**Page to Update:**
https://kubernetes.io/docs/reference/instrumentation/metrics/

latest: 1.31

**Comment by mengqiy** [comment]
@kubernetes/sig-docs-en-owners

**Comment by dipesh-rawat** [comment]
It looks like the Kubernetes metrics reference page at https://kubernetes.io/docs/reference/instrumentation/metrics/ says that it is for Kubernetes **v1.30** _[Metrics (v1.30)]_, while the current release is already **v1.31**. This means the metrics page is outdated.  It would be good to update the content to reflect the latest version.

**Comment by dipesh-rawat** [comment]
/sig instrumentation
/language en
/triage accepted

/priority important-soon
_(Please feel free to adjust the priority as needed, if the SIG consensus leans toward a different priority)_

**Comment by dipesh-rawat** [comment]
Refer the guidance at https://kubernetes.io/docs/contribute/generate-ref-docs/metrics-reference/ on how to generate the metrics reference documentation.

**Comment by mengjiao-liu** [comment]
I have submitted the PR https://github.com/kubernetes/kubernetes/pull/128376 in K8s upstream, and when it is merged, I will sync the v1.31 latest metrics reference to the website.
