### ISSUE TITLE
Mention `system:masters` in authz page

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#48546]
**This is a Feature Request**

**What would you like to be added**
Update https://kubernetes.io/docs/reference/access-authn-authz/authorization/ to mention the special group `system:masters`

**Why is this needed**
Kubernetes has special hard coded treatment for `system:masters`, but this detail is poorly documented.

**Comments**
/sig auth security docs

**Comment by mrgiles** [comment]
@sftim, I've just found only brief mentions of the `system:masters` group in the [RBAC Good Practices](https://kubernetes.io/docs/concepts/security/rbac-good-practices/#least-privilege) and in the [Using RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles) pages. Would you like to expand further on the topic or just link to those entries from the [Authorization](https://kubernetes.io/docs/reference/access-authn-authz/authorization/) page?

**Comment by sftim** [comment]
The page to update is https://kubernetes.io/docs/reference/access-authn-authz/authorization/

You can pick the best way to achieve this.

**Comment by sftim** [comment]
Thanks @mrgiles
