### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/

### ISSUE THREAD

**Issue by lars-c** [kubernetes/website#48607]
Error in step 3) Verify that your chosen PersistentVolume has the right policy. Still show RECLAIMPOLICY as 'delete'. Should be 'Retain'.

**Comment by iheartNathan** [comment]
@lars-c  
step 2 says to "**Choose one** of your PersistentVolumes and change its reclaim policy:" and in steps 3 we can see the volume bound to claim `default/claim3` has reclaim policy `Retain`
![image](https://github.com/user-attachments/assets/825ddea3-6c5c-49de-8f01-6d5af584b576)

It looks correct

**Comment by lars-c** [comment]
I know - I made a stupid mistake. Step 3 is perfectly okay. Sorry for the confusion. My mistake.

**Comment by a-mccarthy** [comment]
closing this, as looks like there is no action needed here to improve the docs. thanks all for your responses!
