### ISSUE TITLE
"Feature Gates" page says `RecursiveReadOnly` is still alpha, although it is actually beta

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/website#48614]
**This is a Bug Report**

**Problem:** https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ says `RecursiveReadOnly` is still alpha (v1.30), but it actually reached beta in v1.31: https://github.com/kubernetes/kubernetes/pull/125475/files

**Proposed Solution:**
Sync the gate table

**Page to Update:**
- https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/ 
- https://kubernetes.io/docs/concepts/storage/volumes/#recursive-read-only-mounts

**Comment by tengqm** [comment]
PR was proposed and blocked: https://github.com/kubernetes/website/pull/47852
