### ISSUE TITLE
maxParallelImagePulls feature gate is not documented in list of Feature Gates

### ISSUE THREAD

**Issue by T-Lakshmi** [kubernetes/website#48682]
**This is a Bug Report**
**Problem:**
**maxParallelImagePulls** feature gate is using in kubernetes documentation under [images](https://kubernetes.io/docs/concepts/containers/images/#maximum-parallel-image-pulls) concept, but it is not listed in available feature gates.

**Proposed Solution:**
List this feature gate under the Feature gates for Alpha or Beta features: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features

**Comment by tengqm** [comment]
Well... I don't there is a feature gate for this.

**Comment by T-Lakshmi** [comment]
@tengqm,
Thanks for letting me know.
I just double check this and yes, there is no specific featuregate dependency for this.

> The feature will be enabled when the kubelet config field maxParallelImagePulls is set to a non-zero value on kubelet, can be disabled by setting maxParallelImagePulls to 0 and restarting kubelet.
