### ISSUE TITLE
Issue with k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/

### ISSUE THREAD

**Issue by Standard-IO** [kubernetes/website#48720]
Link (`"Start Interactive Tutorial"`) in the section [Example: Externalizing config using MicroProfile, ConfigMaps and Secrets](https://kubernetes.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/#example-externalizing-config-using-microprofile-configmaps-and-secrets) is not working. Or is there no link at all?

**Comment by sftim** [comment]
The page at https://k8s.io/docs/tutorials/configuration/configure-java-microservice/configure-java-microservice/ is stale.
I recommend we delete that tutorial.

**Comment by sftim** [comment]
Duplicate of issue https://github.com/kubernetes/website/issues/42401

Help is welcome (to delete the obsolete page). The Kubernetes docs are maintained largely by volunteers.

/triage duplicate

**Comment by dipesh-rawat** [comment]
Closing in favor of https://github.com/kubernetes/website/issues/42401. Any assistance with existing issue https://github.com/kubernetes/website/issues/42401 is welcome.

/close not-planned
