### ISSUE TITLE
Go version is invalid in go.mod

### ISSUE THREAD

**Issue by chalin** [kubernetes/website#48735]
While experimenting with Hugo modules in the context of work on #41171, I get an error like this for [go.mod](https://github.com/kubernetes/website/blob/e0c5639daff44f79728f57a5178e5cb9f3193a5d/go.mod) in `main` at `HEAD`:

```
go: errors parsing go.mod:
/src/go.mod:3: invalid go version '1.22.0': must match format 1.XX
```

Reference:

- https://go.dev/doc/modules/gomod-ref

**Comment by tengqm** [comment]
https://github.com/kubernetes/kubernetes/blob/master/go.mod

**Comment by tengqm** [comment]
@chalin My take is that the Go language evolves with the Kubernetes ecosystem. There are now and then Go feature enhancement or bug fixes required by Kubernetes. So ... having a patch version in the go.mod file is understandable for me.
On the other hand, I'm not quite sure the reference you quoted is up to date.
