### ISSUE TITLE
Invalid dates in two blog articles

### ISSUE THREAD

**Issue by sftim** [kubernetes/website#48754]
**This is a Bug Report**

Split out from issue #48752 

**Problem:**
- `content/en/blog/_posts/2018-01-00-Reporting-Errors-Using-Kubernetes-Events.md` has an invalid `published` date in front matter
- `content/zh-cn/blog/_posts/2019-12-09-kubernetes-1.17-release-announcement.md` has an invalid `date` in its front matter

This shows up with newer releases of Hugo.

**Proposed Solution:**
Edit those pages to use valid ISO8601 dates.

**Page to Update:**
https://k8s.io/blog/2018/01/reporting-errors-using-kubernetes-events/
https://kubernetes.io/zh-cn/blog/2019/12/09/kubernetes-1-17-release-announcement/

**Additional Information:**
/area blog
/area localization

**Comment by sftim** [comment]
/help

If opening PRs, please open a separate PR for each page you fix (because they will be reviewed by different teams).

**Comment by dipesh-rawat** [comment]
Looks like the two PRs resolving this issue have been merged. This can be closed as completed.

/close
