### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/concepts/scheduling-eviction/assign-pod-node/

### ISSUE THREAD

**Issue by seajelly** [kubernetes/website#48750]
Chinese translation error.
In the English document, Kubernetes v1.31 [beta] (enabled by default: true) but in the comments of the Chinese article it is disabled by default

![image](https://github.com/user-attachments/assets/90b0d371-c34d-46bc-9b62-8790e2d19750)

**Comment by seajelly** [comment]
> /language zh

sorry,I can't understand what you mean

**Comment by sftim** [comment]
The page is in Chinese (language code ZH). So we mark this as using the zh language.
