### ISSUE TITLE
干扰（Disruptions）一词用“干扰物”或“扰动”更为贴切

### ISSUE THREAD

**Issue by atom-l** [kubernetes/website#48767]
“Disruptions” 在英文中是作为名词来释义的，其可以作为主语或宾语使用。
而在中文的使用环境中，“干扰”却不常作名词用（虽然严格意义上来说可以如此）。因此会让中文读者在初次接触这个重要概念时出现语言层面的歧义，这种不适感也不利于中文用户的日常使用和交流。

**Comment by dipesh-rawat** [comment]
Hi @atom-l, we track issues in English. If feasible kindly describe the [issue (here)](https://github.com/kubernetes/website/issues/48767#issue-2671558734) in English language.

/triage needs-information

**Comment by atom-l** [comment]
> Hi @atom-l, we track issues in English. If feasible kindly describe the [issue (here)](https://github.com/kubernetes/website/issues/48767#issue-2671558734) in English language.
> 
> /triage needs-information

Sorry, I thought it would go to the Chinese maintainer to deal with it. I'll resubmit an issue with an English description. Thanks.

**Comment by tengqm** [comment]
实际上，中文里面“干扰”一词作名词用也非常常见，例如：这种噪声对我来说就是一种干扰。翻译成“干扰物”、“扰动”反而很奇怪。

**Comment by atom-l** [comment]
> 实际上，中文里面“干扰”一词作名词用也非常常见，例如：这种噪声对我来说就是一种干扰。翻译成“干扰物”、“扰动”反而很奇怪。

@tengqm 仔细想来确实如此，所以就没打算再提这事儿了。
