### ISSUE TITLE
[CSS Bug] Text are not visible in case-studies page

### ISSUE THREAD

**Issue by asem-hamid** [kubernetes/website#48770]
**This is a Bug Report**

**Problem:**

Texts are not visible in case-studies page .

![image](https://github.com/user-attachments/assets/04bd9332-f382-4fd1-8c13-96ec63a70073)

**Page to Update:**
https://kubernetes.io/case-studies/

**Comment by mengjiao-liu** [comment]
It seems that the previous PR https://github.com/kubernetes/website/pull/48226 caused this issue.
```
.gridPage p:not(.announcement-main > p) {
    color: rgb(255,255,255);
```
