### ISSUE TITLE
Externalizing config using MicroProfile, ConfigMaps and Secrets - Absent link

### ISSUE THREAD

**Issue by google-boy** [kubernetes/website#48773]
No link to the interactive lab/tutorial

"Start Interactive Tutorial" is anchor with no href property

<a>Start Interactive Tutorial</a>

**Comment by sftim** [comment]
/kind bug
/language en

Duplicate of issue https://github.com/kubernetes/website/issues/42401

Help is welcome (to delete the obsolete page). The Kubernetes docs are maintained largely by volunteers.

/triage duplicate

**Comment by dipesh-rawat** [comment]
Closing in favor of https://github.com/kubernetes/website/issues/42401. Any assistance with existing issue https://github.com/kubernetes/website/issues/42401 is welcome.

/close not-planned
