### ISSUE TITLE
Named code-block elements show unnecessary block padding

### ISSUE THREAD

**Issue by chalin** [kubernetes/website#48808]
For example, visit https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topology-spread-constraint-examples and you'll currently see:

> <img width="522" alt="image" src="https://github.com/user-attachments/assets/aaf93d53-e177-47bf-8f3c-92b98e5010f3">

There shouldn't be whitespace around the grey code block -- i.e., the code block should extend to the border of it's parent container.

**Comment by sftim** [comment]
/retitle Named code-block elements show unnecessary block padding
