### ISSUE TITLE
[fr] Inactive interactive tutorial in "Deploying an application" page

### ISSUE THREAD

**Issue by polocto** [kubernetes/website#48849]
Tutorial description : 
- `Pour interagir avec le terminal, veuillez utiliser la version bureau / tablette.`

Though I am using my desktop.

**Comment by dipesh-rawat** [comment]
Page reported in issue (based on issue title): https://kubernetes.io/fr/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
/language fr

**Comment by dipesh-rawat** [comment]
/retitle [fr] Inactive interactive tutorial in "Deploying an application" page
/kind bug
/area localization

**Comment by dipesh-rawat** [comment]
@polocto Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.
