### ISSUE TITLE
sidecar-containers docs are wrong

### ISSUE THREAD

**Issue by liruonian** [kubernetes/website#48909]
**This is a Bug Report**

**Problem:**
The goal is to showcase the YAML configuration for a sidecar, but what is actually shown is an initContainer.

**Proposed Solution:**
Delete the redundant initContainer lines.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
ref:
(https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/deployment-sidecar.yaml)
(https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/job/job-sidecar.yaml)

**Comment by stmcginnis** [comment]
The examples are correct. Please read the doc you linked for an explanation of how sidecar containers work.

> If an init container is created with its restartPolicy set to Always, it will start and remain running during the entire life of the Pod.

https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-containers-and-pod-lifecycle

/close
