### ISSUE TITLE
Improvement for docs/reference/glossary/rbac.md

### ISSUE THREAD

**Issue by ym1024** [kubernetes/website#48967]
**This is a Feature Request**

**What would you like to be added**
Add descriptions of `ClusterRole` and `ClusterRoleBinding` to the following line.
https://github.com/kubernetes/website/blob/66dbc9c245c7be926bf348746022cc5b51e9e313/content/en/docs/reference/glossary/rbac.md?plain=1#L18

**Why is this needed**
The RBAC API declares not only `Role` and `RoleBinding`, but `ClusterRole` and `ClusterRoleBinding`.
- FYI: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#api-overview

**Comments**
- URL: https://kubernetes.io/docs/reference/glossary/?all=true#term-rbac

**Comment by utkarsh-singh1** [comment]
Needed to update the doc ⇾ 

`RBAC utilizes *roles* and *clusterrole*, which contain permission rules, also *role bindings* and *cluster-role-binding*, which grant the permissions defined in a role to a set of users.`

**Comment by sftim** [comment]
We could also signpost readers to the RBAC docs and tell them to continue reading.
