### ISSUE TITLE
콘텐츠 개선 제안하기

### ISSUE THREAD

**Issue by genitok** [kubernetes/website#49020]
- 문서 위치: https://kubernetes.io/ko/docs/concepts/overview/working-with-objects/labels/#%EC%9D%BC%EC%B9%98%EC%84%B1-%EA%B8%B0%EC%A4%80-%EC%9A%94%EA%B1%B4
- 현재: 전자는 environment를 키로 가지는 것과 production을 값으로 가지는 모든 리소스를 선택한다.
- 제안
    - 전자는 environment를 키로 가지며 production을 값으로 가지는 모든 리소스를 선택한다.
    - 전자는 키가 environment이고 값이 production인 모든 리소스를 선택한다.

**Comment by mengjiao-liu** [comment]
Hi @genitok, we track issues in English. If feasible kindly describe the issue in English language.
/language ko

**Comment by genitok** [comment]
Sorry. Never mind. It is for old Korean document.

**Comment by genitok** [comment]
Sorry. Never mind. It was for old Korean document.
