### ISSUE TITLE
Improve the PV Storage Task Page

### ISSUE THREAD

**Issue by network-charles** [kubernetes/website#49119]
This is a new open issue that tries to address the issue raised at #43293. I can't reopen the previous issue, so I created a new one to address it.

Note: The previous issue was closed due to inactivity from contributors.

Page referenced: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

/assign

**Comment by sftim** [comment]
/sig storage

I reopened https://github.com/kubernetes/website/issues/43293 @network-charles; this one is now really a duplicate.
/triage duplicate

/close not-planned

**Comment by network-charles** [comment]
Ok
