### ISSUE TITLE
It is not clear in documentation (Reference/Component tools/Feature Gates) to what components a particular Feature Gate needs to be applied

### ISSUE THREAD

**Issue by devourer66** [kubernetes/website#49134]
It is not immediately clear in what components a particular feature gate needs to be mentioned in the `--feature-gates=...` flag.
Would it be possible to append the table in https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features with columns corresponding to cluster components? Each component gets a ✔ mark where the feature gate applies. 

Something like this

| Feature                                     | Default | Stage  | Since | Until | kube-apiserver | kube-scheduler | kube-controller-manager | kubelet | kube-proxy |
|---------------------------------------------|---------|--------|-------|-------|----------------|----------------|-------------------------|---------|------------|
| AllowUnsafeMalformedObjectDeletion          | false   | Alpha  | 1.32  | –     | ✔              |                |                         |         |            |
| AnonymousAuthConfigurableEndpoints          | false   | Alpha  | 1.31  | 1.31  | ✔              |                |                         |         |            |
| AnonymousAuthConfigurableEndpoints          | true    | Beta   | 1.32  | –     | ✔              |                |                         |         |            |
| AnyVolumeDataSource                         | false   | Alpha  | 1.18  | 1.23  |                |                |                         | ✔       |            |
| AnyVolumeDataSource                         | true    | Beta   | 1.24  | –     |                |                |                         | ✔       |            |

**Comment by sftim** [comment]
Let's instead reopen https://github.com/kubernetes/website/issues/42199

**Comment by sftim** [comment]
Because we have an existing (reopened) issue that this duplicates:
/close not-planned
