### ISSUE TITLE
Incorrect Japanese translation in the define-environment-variable-container.md

### ISSUE THREAD

**Issue by shunki-fujita** [kubernetes/website#49131]
**This is a Bug Report**

**Problem:**
It means the opposite.
https://github.com/kubernetes/website/blob/ce8a338661957d8227f355faa7d999a0c83fcd3e/content/ja/docs/tasks/inject-data-application/define-environment-variable-container.md#L79

**Proposed Solution:**
Correct the document.

**Page to Update:**
https://kubernetes.io/...

**Comment by Okabe-Junya** [comment]
Thanks, great catch up!

/area localization
/language ja
/triage accepted
