### ISSUE TITLE
Typographical error in "Object Names and IDs" page

### ISSUE THREAD

**Issue by lhajouji** [kubernetes/website#49199]
**This is a Bug Report**
There is a typographical error in the "Object Names and IDs" page,  in the section discussing the `generateName` feature.

**Current Text:**
    *resulting in a HTTP 409 resopnse.*

**Proposed Solution:**
*resulting in a HTTP 409 response.*

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

**Comment by dipesh-rawat** [comment]
Fix merged as part of PR https://github.com/kubernetes/website/pull/49200

/close
