### ISSUE TITLE
Error on JavaScript console when no announcement shown

### ISSUE THREAD

**Issue by parkilwoo** [kubernetes/website#49210]
```
$(document).ready(function() {
    function s(e, t, n) {
        let o = ""
          , s = new Date
          , i = 24 * 60 * 60 * 1e3;
        n && (s.setTime(s.getTime() + n * i),
        o = "; expires=" + s.toUTCString()),
        document.cookie = e + "=" + t + o + "; path=/"
    }
    function o(e) {
        let t = document.cookie.match(new RegExp("(?:^|; )" + e.replace(/([.$?*|{}()[\]\\/+^])/g, "\\$1") + "=([^;]*)"));
        return t ? "true" : void 0
    }
    let e = document.querySelector("#announcement")
      , n = `announcement_ack_${e.getAttribute("data-announcement-name").replace(/\s/g, "_")}`
      , i = o(n);
    i === "true" ? e.remove() : e.classList.add("display-announcement");
    let t = document.querySelector("#banner-dismiss");
    t.removeAttribute("style"),
    t.addEventListener("click", function() {
        s(n, "true", t.getAttribute("data-ttl")),
        e.remove()
    })
})
```

In the code above, e is null in the `let e = document.querySelector("#announcement")` part. Please check “#announcement”.
![Screenshot from 2024-12-23 15-10-12](https://github.com/user-attachments/assets/092a1c39-5d7e-4499-9ede-7a84b3fec6c4)

**Comment by sftim** [comment]
/retitle Error on JavaScript console when no announcement shown
/kind bug

**Comment by sftim** [comment]
@parkilwoo can you describe the symptoms you are seeing when you try to follow a tutorial?

**Comment by parkilwoo** [comment]
The interactive tutorial does not work.
I think it might be a problem as katacoda ends its service.

**Comment by dipesh-rawat** [comment]
> The interactive tutorial does not work.

@parkilwoo Katacoda environment for the Kubernetes tutorial has been shut down. Refer the announcement [here](https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/).

We have an umbrella issue raised https://github.com/kubernetes/website/issues/41496 to remove tutorials that rely on Katacoda for all localized documents.

**Comment by dipesh-rawat** [comment]
It seems that the issue regarding the JavaScript console errors has already been reported and is being tracked in our backlog as part of https://github.com/kubernetes/website/issues/45830.

/triage duplicate

Marking this as duplicate in favor of existing issue  https://github.com/kubernetes/website/issues/45830
_(Feel free to remove the label if this is incorrect.)_

**Comment by sftim** [comment]
Nothing [new] to fix.

/close not-planned
