### ISSUE TITLE
sky news kuala Lumpur 


### ISSUE THREAD

**Issue by mohdanuarverbesuites** [kubernetes/website#49241]
**This is a Feature Request**

**What would you like to be added**

**Why is this needed**

**Comments**

**Comment by dipesh-rawat** [comment]
@mohdanuarverbesuites This [description (here)](https://github.com/kubernetes/website/issues/49241#issue-2760239620) doesn't provide enough information to evaluate the issue or determine if any action is needed. Could you please provide more details about the problem you're reporting or the help you need? Please include these details in the issue [description](https://github.com/kubernetes/website/issues/49241#issue-2760239620). Currently, it appears to resemble spam.

**Comment by dipesh-rawat** [comment]
/close not-planned

You are welcome to reopen this and add correct details.
