### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-stateless-application-deployment/

### ISSUE THREAD

**Issue by tgeek77** [kubernetes/website#5014]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The example uses: apiVersion: apps/v1beta1

This gives the following error when trying to implement the deployment:

error: error validating "deployment.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false

**Proposed Solution:**

Update sample or provide alternative instructions

**Page to Update:**
http://kubernetes.io/...

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:23:22Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"2017-07-19T10:00:06Z", GoVersion:"go1.6.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tengqm** [comment]
Looks like the server version is too low to use apps/v1beta1.
