### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by mcandre** [kubernetes/website#5076]
This tutorial has a subtle but important ambiguity: Should the base64-encoded registry secret be the YAML format of the registry secret, or JSON format? The tutorial mentions both, but I'm not sure if the JSON portion was just talking about user-facing files, or if the tutorial wants the user to use one or the other, or perhaps it doesn't even matter? Please have the tutorial focus on only the formats that should actually be used for this kind of configuration.

**Comment by radhikapc** [comment]
Hi @erictune 👋 Could you please take a look at this issue and provide necessary recommendation to fix https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
Thanx

**Comment by mcandre** [comment]
Evidentally the base64-encoded portion should be in JSON format, while the overall secret is often in YAML.
