### ISSUE TITLE
Automatically look for image pull secret if exists

### ISSUE THREAD

**Issue by mcandre** [kubernetes/website#5077]
Please adopt a standard secret name for registry authentication, in order to reduce the amount of manual configuration required to get Kubernetes to actually apply this secret when pulling images. Something like `regsecret` per the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/), so that individual pods don't have to be explicitly configured to point to this secret.

Would also be nice to have a `kubectl` subcommand to setup registry authentication to really simplify things, but even just a standard name for the registry auth secret would go a long way towards making Kubernetes easier to use.

**Comment by radhikapc** [comment]
@erictune Hi ! Requesting a tech review.
@mcandre Hi, from the issue description, it's not very clear it's an issue on docs or a suggestion on registry authentication. Please clarify.

**Comment by mcandre** [comment]
In the short term, selecting a name like "regsecret" is fine, as along as each Kubernetes resource (e.g. pod) is configured to use a service account, and the service account refers to the same name ("regsecret", or whatever you choose).
