### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/declare-network-policy/

### ISSUE THREAD

**Issue by Banashri** [kubernetes/website#5122]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Busybox pod is able to contact nginx even though in the presence of the network policy in the k8s cluster of version 1.7.4 and with calico plugin enabled.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by radhikapc** [comment]
@bowei Hi ! Please review this doc issue and provide necessary recommendation to take it to closure.

**Comment by bowei** [comment]
@Banashri the link that you gave seems to not point to the doc that you want to be updated?

**Comment by radhikapc** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/ @bowei

**Comment by dnardo** [comment]
Who is the network policy provider in your case ?  Can you describe the setup a bit more?

**Comment by Banashri** [comment]
Network Provider is weave net. During cluster creation I set --networking=weave in kops. 
Please let me know if you need any more details.

**Comment by bowei** [comment]
I think we should remove the full example from this page, which is a generic doc about configuring network policy. Provider specific pages exist and should be where the workable examples live

**Comment by dnardo** [comment]
@Banashri  I would talk to the weave folks about what you are seeing.  The docs that you refer to are general network policy docs on applying network policy API objects.   Weave is one of many Network Policy Provides, and k8s is merely passing API objects to the network policy providers which then implement the enforcement of that policy.  Kubernetes isn't responsible for the actual enforcement.

**Comment by Banashri** [comment]
The configurations setup are done properly specific to the used network provider. Weave Net pods are also running fine in the cluster. But the example for declaring network policy did not work as expected. Furthermore, the API Version of the created network policy shows as extensions/ v1beta1 instead of networking.k8s.io/v1.

**Comment by bowei** [comment]
@Banashri -- it would be good to figure out what the bug is as this is a issue on the documentation, not the network policy code.

**Comment by Banashri** [comment]
Oh. I must say that the example in the document is really good but it is pity that we cant get the expected result. I hope that the example is well tested with weave net or calico as network provider as those 2 are mentioned in the other document.

**Comment by tengqm** [comment]
Conclusions? Next steps?

**Comment by bowei** [comment]
@Banashri can you open a bug against weave for the issue? 

/close
