### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose-intro/

### ISSUE THREAD

**Issue by donalmadden** [kubernetes/website#5136]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In the "Overview of Kubernetes Services" section the tutorial mentions "(see below for why you might want a Service without including selector in the spec)". This is the first mention of spec in the whole tutorial (I've been working through it from the beginning).

**Proposed Solution:**
Insert a short paragraph in the document explaining what a "spec" is in this context

**Page to Update:**
http://kubernetes.io/...

**Comment by radhikapc** [comment]
@BenHall 👋

**Comment by JasonMorgan** [comment]
Looks like this was just a reading comprehension problem.  There are instructions at the bottom of the writeup.  Might be handy to move them up to under the proxy command but it's probably fine as is.

**Comment by BenHall** [comment]
Thank you for the feedback. As Jason mentioned, the explanation of kubectl proxy isn't very clear and something we're looking at improving.

Related #4940, #5119 and #5138

**Comment by donalmadden** [comment]
No problem @BenHall. I've found multiple issue like this on this page and further on in the tutorial if you're happy to take more feedback.

**Comment by JasonMorgan** [comment]
Looks like this was just a reading comprehension problem.  There are instructions at the bottom of the writeup.  Might be handy to move them up to under the proxy command but it's probably fine as is.

**Comment by JasonMorgan** [comment]
Is the tutorial content held in a repo I can send a PR to?  I'd be happy to submit corrections as I go through it.

**Comment by radhikapc** [comment]
@JasonMorgan here you go https://github.com/kubernetes/kubernetes.github.io/tree/master/docs/tutorials

**Comment by errordeveloper** [comment]
@JasonMorgan have you managed to open a PR with any fixes to issues you've described here?

**Comment by BenHall** [comment]
@errordeveloper If I recall, @heckj made a number of improvements to the scenarios about how `kubectl proxy` works as part of #1561 which was merged a while ago. Future changes/enhancements are always welcome at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios :)

**Comment by errordeveloper** [comment]
So I guess we can close this, and if OP opposes they can re-open... wdyt?
