### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by fanfanbj** [kubernetes/website#5170]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

in Using Minikube with an HTTP Proxy.

**Problem:**
This is a Bug Report in Using Minikube with an HTTP Proxy.

origin is:
minikube start --docker-env HTTP_PROXY=http://$YOURPROXY:PORT \
                 --docker-env HTTPS_PROXY=https://$YOURPROXY:PORT
in my environment, it needs low-case for http_proxy and https_proxy, which looks like as below:
minikube start --docker-env http_proxy=http://$YOURPROXY:PORT \
                 --docker-env https_proxy=https://$YOURPROXY:PORT

**Proposed Solution:**
change to low-case for http_proxy and https_proxy

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/minikube/

1.6.4

**Comment by radhikapc** [comment]
@fanfanbj Do you think there is any disruption in the functionality with the current content ? Could you please direct me to the style guide that states the given option should be given in lower case.
cc @zacharysarah

**Comment by fanfanbj** [comment]
@radhikapc, in fact, I can successfully run "minikube start" with upper-case HTTP_PROXY and HTTPS_PROXY. But, the setting doesn't work. I need a http proxy to pull images in gcr.io. When I change to lower case, it works.

**Comment by tengqm** [comment]
This suggested solution makes sense. The proxy environment variables should be in lower cases.

/remove-lifecycle stale
/assign
