### ISSUE TITLE
We should not instruct users to use Deployment to deploy a stateful application

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#5193]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
This task teaches a backwards way of deploying a stateful application on Kubernetes. It should instead use StatefulSets.

**Proposed Solution:**
Rewrite this task to use StatefulSet instead of Deployment.

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

**Comment by tengqm** [comment]
I don't think so. The link is about *single instance* of stateful applications. If you are running a replicated version, you will read this: https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/

From doc side, we are supposed to add a link to the latter. That would be the simple fix.

**Comment by ryanmcginnis** [comment]
> I don't think so.

Would you explain why?

> The link is about _single instance_ of stateful applications.

Regardless of how many instances are deployed, why use Deployment for a stateful application? Perhaps it is easier, but it doesn't set the reader up for success.

Let's pretend that a new user just finished reading the StatefulSet concept. They are ready to deploy their stateful application, and to begin with they'd like to learn how to deploy a single instance. Coming to this task, they are instructed to use Deployment... Isn't that confusing for them?

Moreover, we suggest throughout the doc set that Deployments are for stateless applications. We explicitly state [here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets) that "Controllers such as Deployment ... may be better suited to your stateless needs."

We fracture the meaning and purpose of these concepts. It is at least confusing and at worst debilitating for users trying to learn.

> From doc side, we are supposed to add a link to the latter. That would be the simple fix.

I feel that my proposed solution is also simple: document the use of a StatefulSet, because it is consistent with its purpose and would contribute to the doc set's consistency.
