### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

### ISSUE THREAD

**Issue by fffffreedom** [kubernetes/website#5205]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
as you said:
You’ll also need to provide the object spec field. The precise format of the object spec is different for every Kubernetes object, and contains nested fields specific to that object. The Kubernetes API reference can help you find **the spec format for all of the objects** you can create using Kubernetes.

but i can not find it in **Kubernetes API reference**

**Proposed Solution:**
can you do me a favor to provide the object spec field clearly ? thks

**Page to Update:**
http://kubernetes.io/...

**Comment by radhikapc** [comment]
@fffffreedom have you checked here https://kubernetes.io/docs/api-reference/v1.7/
