### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by parag3gwl** [kubernetes/website#5207]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
I am using minikube config and followed the process mentioned in stateful-application/cassandra. pods runs and able to do the cql operation. But i am not able to access cassandra outside of kubernetes. 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by radhikapc** [comment]
@BenHall 👋

**Comment by BenHall** [comment]
@radhikapc Thanks but this is outside of the interactive tutorials :)

@parag3gwl You might find Stackoverflow more useful for more in-depth and faster responses to questions about Kubernetes. In the meantime, I recommend looking at how applications can be exposed outside the cluster using Services and NodePort, Ingress routing or ExternalIPs. A great starting point is https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/

**Comment by tengqm** [comment]
@BenHall has responded to this help request with details. Closing.
