### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/ingress/

### ISSUE THREAD

**Issue by sivasamyk** [kubernetes/website#5228]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
When explaining the contents of YAML using line numbers (e.g.  Under Ingress Resource POST YAML explanation in https://kubernetes.io/docs/concepts/services-networking/ingress/), without the YAML being annotated with line numbers, it is difficult to correlate between the text and YAML file

**Proposed Solution:**
Annotate YAML file display with line numbers.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/ingress/

Though this comment is applicable to all pages.

1.7

**Comment by radhikapc** [comment]
@steveperry-53 👋
