### ISSUE TITLE
initContainers

### ISSUE THREAD

**Issue by yn425611317** [kubernetes/website#5236]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by yn425611317** [comment]
initContainers is invalid field

**Comment by tengqm** [comment]
would be helpful if you can be more specific about the bug you mentioned.

**Comment by yn425611317** [comment]
apiVersion: v1
kind: ReplicationController
metadata:
  name: dinggang-webdj
  namespace: dgdj
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dinggang-webdj
    spec:
      containers:
      - name: dinggang-webdj
        image: sxgc-master1:5000/dinggang-webdj
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/tomcat/logs
          name: dinggangweb
      initContainers:
      - name: init-db
        image: sxgc-master1:5000/busybox
        command: ["sh", "-c", "until nslookup dingang-dgdj; do echo waiting for db service; sleep 2; done;"]
      - name: curl
        image: sxgc-master1:5000/curl
        command: ["sh", "-c", "until curl dinggang-dbdj:3306; do echo waiting for db start; sleep 2; done;"]
      volumes:
      - name: dinggangweb
        nfs:
          server: 10.0.2.18
          path: /home/data/dinggangweb

**Comment by tengqm** [comment]
Cannot debug this because your YAML is not rendered properly ...

**Comment by heckj** [comment]
@yn425611317 can you put the YAML into a github gist, or wrap it with ``` characters so that it formats in a fashion that we can see the indentation? I'm afraid directly pasting into a comment box on github doesn't automatically preserve the indentation.

I suspect what's happening is the indentation is slightly off on the YAML you're trying to use - it can be very frustrating, and would cause the bug you're seeing and reporting
