### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by vladlosev** [kubernetes/website#5307]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation on k8s.io/docs/getting-started-guides/scratch/ mentions the `--cluster-name` setting for `apiserver` (`--cluster-name=$CLUSTER_NAME`). But an attempt to launch `apiserver` with this flag yields an error:
```
Error: unknown flag: --cluster-name
``` 
which is confusing.

**Proposed Solution:**
Remove the mention of  `--cluster-name` in relation to `apiserver` from this page.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/scratch/

Kubernetes Version:
1.7.2

**Comment by clenimar** [comment]
this is already fixed by the PR mentioned above. please close the issue.

**Comment by tengqm** [comment]
ping @vladlosev, please close this one.

**Comment by vladlosev** [comment]
Thanks for fixing!
