### ISSUE TITLE
Document kubectl's behavior regarding initializers

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/website#5310]
* document the `--include-uninitialized` kubectl flag; 
* if a specific kubectl subcommand include uninitialized objects;
* `--all` includes uninitialized objects by default.

cc @dixudx @ahmetb

**Comment by ahmetb** [comment]
Isn't `kubectl` the right place to document this? We have quite a few topics and a cheatsheet, but I don't think we comprehensively document such kubectl options in the articles on the docs site.

**Comment by dixudx** [comment]
At lease we should update <https://kubernetes.io/docs/user-guide/kubectl/>.

**Comment by ahmetb** [comment]
Not sure how one does actually reach that page. I thought we removed those pages. (I can't find any docs pages linking to that URL, makes me think it's an **orphan page**.)

New docs are at https://kubernetes.io/docs/reference/ ("kubectl CLI"). There are pages like:

- https://kubernetes.io/docs/user-guide/kubectl-overview/ (manual)
- https://kubernetes.io/docs/user-guide/kubectl-cheatsheet/ (manual)
- https://kubernetes.io/docs/user-guide/kubectl/v1.7/ (autogenerated)

I recommend updating the first two.

**Comment by dixudx** [comment]
Add documentation in PR #5505. PTAL.

**Comment by dixudx** [comment]
This issue can be closed, since kubernetes/kubernetes.github.io#5505 has already been merged.

**Comment by tengqm** [comment]
ping @caesarxuchao, this can be closed.
