### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore-interactive/

### ISSUE THREAD

**Issue by nogurenn** [kubernetes/website#5333]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The interactive tutorial CLI is not passing over the "data" needed (e.g. Module 3 not discovering the created resources from previous modules). Since module 3 onwards builds on top of previous modules, this becomes practically useless.

**Proposed Solution:**
Explicitly state in the instructions to recreate the previous resources, or fix the resource "discovery" problem. This is a major stopper for cluster management beginners like me.

**Page to Update:**
k8s.io/docs/tutorials/kubernetes-basics/explore-interactive/

**Comment by heckj** [comment]
@BenHall your name was suggested related to the content hosted in Katacoda, is that appropriate, and is there a means to tag content issues here related to your content?

**Comment by BenHall** [comment]
@heckj @nogurenn Thanks for the feedback and the heads up. I'll organise publishing the content as we can collaborate on updates.

**Comment by BenHall** [comment]
This has been improved. 

/close
