### ISSUE TITLE
outdated info on manual deploy on ubuntu

### ISSUE THREAD

**Issue by tomoe** [kubernetes/website#5335]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The page https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/ looks outdated as the scripts under cluster/ubuntu was deleted by the commit https://github.com/kubernetes/kubernetes/commit/e8a3e2d87c337f2da59eb6d124583353f65901a3

**Proposed Solution:**

Remove the page

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/ubuntu/manual/

**Comment by MengZn** [comment]
I have a approach to a manual install kubernetes on ubuntu 16.04.
Do I have the honor to modify this document?
@gnufied

**Comment by gnufied** [comment]
@MengZn yes sure you can go ahead and modify the document. Though, approving such a documentation is outside my duties (and to be perfectly honest I am right person for that). I would expect somone from canonical or cluster-lifecycle to approve/review it.

**Comment by MengZn** [comment]
Thank @gnufied, I will provide manual deployment kubernetes in ubuntu 16.04 as soon as possible.
Can you tag someone who has the right to review this document?
