### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/

### ISSUE THREAD

**Issue by cyberh0me** [kubernetes/website#5359]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
based on this documentation it should be possible to ping pod 2 running on node 2 from pod 1 running on node 1 but this does not work

**Proposed Solution:**
unfortunately still investigating
possibly Docker option --ip-masq  
Docker currently use
"com.docker.network.bridge.enable_ip_masquerade": "true",

**Page to Update:**
http://kubernetes.io/...

Additional Information:
plain Fedora 26 Server installation
node 1
cat /var/run/flannel/subnet.env
    FLANNEL_NETWORK=10.244.0.0/16
    FLANNEL_SUBNET=10.244.10.1/24
    FLANNEL_MTU=1450
    FLANNEL_IPMASQ=false
ip -4 a|grep inet
    inet 127.0.0.1/8 scope host lo
    inet 172.16.0.31/24 brd 172.16.0.255 scope global ens32
    inet 10.244.10.0/32 scope global flannel.1
    inet 10.244.10.1/24 scope global docker0
pod 1
ip a l eth0 | grep inet
    inet 10.244.10.2/24 scope global eth0
node 2
cat /var/run/flannel/subnet.env
    FLANNEL_NETWORK=10.244.0.0/16
    FLANNEL_SUBNET=10.244.6.1/24
    FLANNEL_MTU=1450
    FLANNEL_IPMASQ=false
ip -4 a|grep inet
    inet 127.0.0.1/8 scope host lo
    inet 172.16.0.32/24 brd 172.16.0.255 scope global ens32
    inet 10.244.6.0/32 scope global flannel.1
    inet 10.244.6.1/24 scope global docker0
ip a l eth0 | grep inet
    inet 10.244.6.2/24 scope global eth0

ping 10.244.6.2 from pod 1 fails
ping 10.244.6.1 from pod 1 success
ping 10.244.6.2 from node 1 fails
ping 10.244.10.2 from pod 2 fails
ping 10.244.10.1 from pod 2 success
ping 10.244.10.2 from node 1 fails

**Comment by cyberh0me** [comment]
i successfully disabled dockers ip masquerading with
docker network inspect bridge
"com.docker.network.bridge.enable_ip_masquerade": "true"
systemctl stop docker
systemctl stop flanneld
ip link delete docker0
vi /etc/sysconfig/flanneld
FLANNEL_OPTIONS="-ip-masq"
systemctl start flanneld
systemctl start docker
docker network inspect bridge
"com.docker.network.bridge.enable_ip_masquerade": "false"

now at least i can ping Pod 2 from Node 1 but pings between Pods are still not possible

**Comment by kairen** [comment]
Hi @cyberh0me Which Docker version running on your node?

**Comment by kairen** [comment]
This may be the effect of the previous Docker change, refer from https://github.com/moby/moby/issues/14041.

**Comment by cyberh0me** [comment]
docker-1.13.1-22.gitb5e3294.fc26.x86_64.rpm
