### ISSUE TITLE
content in Tasks section does not match navigation sidebars and isn't linked

### ISSUE THREAD

**Issue by heckj** [kubernetes/website#5361]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

The content in docs/tasks/index.md no longer matches the side bar, and none of the content is linked.

**Proposed Solution:**

I'm not certain what the ideal/best solution is - is the index.md meant to be an example of what's there, and the content should just be updated (and potentially linked as well), or should the contents be shorted and the navigation on the left side that's built from the other documents in the directory provide the detail?

**Page to Update:**
https://kubernetes.io/docs/tasks/

**Comment by nikhita** [comment]
I guess this is still relevant.

/remove-lifecycle rotten
