### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by vyasatavi** [kubernetes/website#5406]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
General problem. Command on the online terminal wrap on the same line instead of next line. 

Module2: curl command failed with error "curl: (3) <url> malformed"

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks for reporting the issue @vyasatavi . We're fixed the issue with wrapping lines so hopefully you'll have a better experience now. 

Please let me know if you encounter any other problems.

**Comment by tengqm** [comment]
Closing. Pls reopen if the fix has not addressed the problem.
