### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/out-of-resource/

### ISSUE THREAD

**Issue by AMLBW7** [kubernetes/website#5437]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
In the document Configure Out Of Resource Handling (https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods), under "Evicting end-user pods", the text makes no sense. The order in which pods are evicted seems to be reversed, and the text under Guaranteed is just a copy of the text under Burstable.

**Proposed Solution:**
Rewrite to reflect the actual eviction policies. 

**Page to Update:**
k8s.io/docs/tasks/administer-cluster/out-of-resource/

**Comment by zacharysarah** [comment]
@csbell :wave: Are you available to do a tech review and determine what doc updates are required?

**Comment by ryanmcginnis** [comment]
This was fixed with #6589.
