### ISSUE TITLE
References to User FAQ on github wiki for kubernetes/kubernetes needs to be removed

### ISSUE THREAD

**Issue by heckj** [kubernetes/website#5462]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

This started out as a bug report (https://github.com/kubernetes/kubernetes/issues/52430) against the wiki pages at kubernetes/kubernetes on github because of a broken link there. That issue was resolved, and @bgrant0607 indicated that the FAQ page is obsolete and is due to be decommissioned once relevant information is shifted to documentation and referenced the community work at kubernetes/community#116.

There are 4 links in our current documentation that actively reference this FAQ page that probably need excision and the relevant text updated:

 - `_data/tasks.yml:    path: https://github.com/kubernetes/kubernetes/wiki/User-FAQ#how-do-i-change-the-size-of-my-cluster/`
 - `docs/home/index.md:* [User FAQ](https://github.com/kubernetes/kubernetes/wiki/User-FAQ)`
 - `docs/tasks/debug-application-cluster/debug-application.md:Users are highly encouraged to check out our [FAQ](https://github.com/kubernetes/kubernetes/wiki/User-FAQ).`
 - `docs/tasks/debug-application-cluster/troubleshooting.md:   * [User FAQ](https://github.com/kubernetes/kubernetes/wiki/User-FAQ)`

**Proposed Solution:**

Remove the existing links from current pages prior to the wiki page being removed.

UPDATE: @bgrant0607 asked that we also expand the scope of this issue to bring any content desired from the wiki FAQ pages into the documentation. Pages to which this applies:

- https://github.com/kubernetes/kubernetes/wiki/User-FAQ
- https://github.com/kubernetes/kubernetes/wiki/Debugging-FAQ
- https://github.com/kubernetes/kubernetes/wiki/Services-FAQ

**Page to Update:**
- https://kubernetes.io/tasks/debug-application-cluster/troubleshooting.md
- https://kuberentes.io/tasks/debug-application-cluster/debug-application.md
- https://kuberentes.io/home/
- `_data/tasks.yml`

**Comment by kairen** [comment]
Hi @heckj, I fixed this issue, could you help me to review?

**Comment by heckj** [comment]
Absolutely!
