### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by tomgron** [kubernetes/website#5508]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When running curl.exe -LO **https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/windows/amd64/kubectl.exe in powershell windows 10, I get following error :

curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.**

**Proposed Solution:**
Add "k" to the options (e.g. curl.exe -kLO https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/windows/amd64/kubectl.exe)

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@mengqiy :wave:

**Comment by mengqiy** [comment]
Not sure if it use to work before on windows. 
Short term solution is ask user to run `curl -LO`, if hitting ssl error then try `curl -kLO`.
This doesn't solve the really problem, but I don't have bandwidth to look into it. :/

**Comment by zacharysarah** [comment]
@tomgron ☝️
