### ISSUE TITLE
Set clear expectations for PR review feedback

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#5620]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:** There's no clear expectation about who does what during PR reviews. 

**Proposed Solution:** Update the [README](https://github.com/kubernetes/kubernetes.github.io) and the [contribution guidelines](https://kubernetes.io/docs/home/contribute/create-pull-request/) to:

1. Clarify that PR reviewers are responsible for providing clear, actionable feedback.
2. Clarify that PR owners are responsible for implementing feedback.
3. Update the [new PR template](https://github.com/kubernetes/kubernetes.github.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md) to work around the GitHub UI bug for allowing edits from maintainers.

**Page to Update:**
- https://github.com/kubernetes/kubernetes.github.io/blob/master/README.md
- https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/home/contribute/create-pull-request.md
-
 https://github.com/kubernetes/kubernetes.github.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by Bradamant3** [comment]
Some additional specific items to clarify (things I've stumbled over):
- relationship between assignee and reviewer (sometimes it takes me a few days to get to my assigned PRs and then I see that someone else seems to be shepherding them -- which is fine, but am I no longer responsible for the PR at all? Also related to the following item)
  - maybe if you take over reviewing a PR from an assignee, change the assignee? Or ask about their involvement?
- timeline recommendations for reviewing as reviewer, reviewing as assignee, merging (that is, time to first review; ideally also time to response by PR owner but we can't always control it)
- extent of copyediting responsibilities (high-level definition of Minimum Viable Intelligibility)

**Comment by steveperry-53** [comment]
@zacharysarah @Bradamant3 I'll be glad to help with this. Would one of you like to take the lead?

@Bradamant3 I'm probably the one who has been whisking PRs out from under the assignee. I've been in a bit of a frenzy trying to get through our overwhelming list of PRs. It will be good to get this clarified.

**Comment by bradtopol** [comment]
So I'll start working this. One question I have. What exactly needs to change in PULL_REQUEST_TEMPLATE.md?

**Comment by zacharysarah** [comment]
@bradtopol 👋 Thanks for taking this on!

> What exactly needs to change in PULL_REQUEST_TEMPLATE.md?

You can safely ignore #3, it was updated in #5719.

**Comment by jaredbhatti** [comment]
https://github.com/kubernetes/website/pull/5869

Fixed in this PR.
