### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/fedora/fedora_manual_config/

### ISSUE THREAD

**Issue by vbatts** [kubernetes/website#5720]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
the article works to the end of the described steps, but the resulting cluster does not allow deploying as there is no API token configured.
```
Oct 02 15:56:36 x kube-controller-manager[785]: E1002 15:56:36.226737     785 replica_set.go:424] Sync "default/httpd-2379343749" failed with unable to create pods: No API token found for service account "default", retry after the token is automatically created and added to the service account
Oct 02 15:56:36 x kube-controller-manager[785]: I1002 15:56:36.226881     785 event.go:217] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"httpd-2379343749", UID:"fe0cba21-a797-11e7-be80-001d729af5dd", APIVersion:"extensions", ResourceVersion:"125", FieldPath:""}): type: 'Warning' reason: 'FailedCreate' Error creating: No API token found for service account "default", retry after the token is automatically created and added to the service account
```

**Proposed Solution:**
Include a step to generate and include the API token so the node and master can communicate

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/

[root@x ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-08T18:30:56Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095136c3078ccf887b9034b7ce598a0a1faff769", GitTreeState:"clean", BuildDate:"2017-07-08T18:30:56Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"linux/amd64"}

[root@x ~]# cat /etc/fedora-release
Fedora release 26 (Twenty Six)

**Comment by nikhita** [comment]
I guess this is still relevant.

/remove-lifecycle rotten
