### ISSUE TITLE
Doc sprint at KubeCon

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#5741]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:** SIG-docs needs a set of sprint topics for KubeCon in December 2017.

**Proposed Solution:** Put sprint ideas in comments; also leave a comment indicating your interest, whatever your level of interest happens to be.

**Comment by jaredbhatti** [comment]
Logistics: 
Date: Tuesday, December 5, Time: 1:00pm - 5:00pm
Location: 
30-40 boardroom seating, split across two non-conjoining rooms (this does account for AV)
Current ideas for projects: 
- Glossary
- User Journeys
- Improving Release Notes
- User Studies and Docs Feedback

**Comment by jaredbhatti** [comment]
I need at least 2 other assistants to help.  I'm guessing Zach will be there.  Any volunteers?

**Comment by zacharysarah** [comment]
I will indeed be there!
