### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/volumes/

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/website#5766]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The documentation states that the MountPropagation=true feature-gate needs to be enabled, but it is unclear where it needs to be set. Kubelet? kube-apiserver? anywhere else?

**Proposed Solution:**
Need to document where the flag is useful.

**Page to Update:**
k8s.io/docs/concepts/storage/volumes/

**Comment by zacharysarah** [comment]
@jsafrane 👋 This looks related to #5544. Would you mind taking a look, please?

**Comment by kfox1111** [comment]
FYI, I just got it to work. The flag was needed to be applied to the kube-apiserver and kubelet. I did not set the flag on any other services.

**Comment by jsafrane** [comment]
IMO, all features should be enabled on all components, otherwise you risk errors. Here it may be enough to enable it on API server and kubelet, but you can't be 100% sure with other features.

**Comment by kfox1111** [comment]
I agree, but the bug report was "how do I get the mount propagation feature to work, as the documentation for it was unclear". Having the documentation be updated to be more accurate/specific I think is a good thing.
