### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by ceptem** [kubernetes/website#5863]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Tutorial step indicates both server and version are 1.5. Running `kubectl version`, as requested by the same tutorial, shows a server with version 1.8 and a client with version 1.5.

**Proposed Solution:**
Amend the tutorial text.

**Page to Update:**
http://kubernetes.io/kubernetes-basics/cluster-interactive/

**Comment by heckj** [comment]
hi @ceptem, thanks for your report! If I may ask, how did you navigate to this page? The URL reported in the issue above doesn't match one on the site, and I'm unclear on which tutorial is returning the results with a mixed client and server. I'm assuming it is https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/, but could you verify that?

The tutorial site has updated kubectl to the latest version (1.8) while minikube hasn't been updated within those same images, and by default creates a v1.5 server, but that should be much clearer in the text of the tutorial

**Comment by heckj** [comment]
Addressing with https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/5 against the Katacoda scenario files

**Comment by ceptem** [comment]
Hi Joseph,As that was very late I decided to try it out again.Google -> "Kubernetes tutorial" -> !Tutorials - Kubernetes! -> !Overview - Kubernetes! -> !Using Minikube to Create a Cluster - Kubernetes! -> https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/Module 1, Step 2 of 3.This is smaller than minor but I couldn't help it ;)Regards,--Raphaël11.10.2017, 16:14, "Joseph Heck" <notifications@github.com>:hi @ceptem, thanks for your report! If I may ask, how did you navigate to this page? The URL reported in the issue above doesn't match one on the site, and I'm unclear on which tutorial is returning the results with a mixed client and server. I'm assuming it is https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/, but could you verify that?
The tutorial site has updated kubectl to the latest version (1.8) while minikube hasn't been updated within those same images, and by default creates a v1.5 server, but that should be much clearer in the text of the tutorial

**Comment by heckj** [comment]
upstream bug merged
