### ISSUE TITLE
Cloud Controller Manager Concepts and Reference

### ISSUE THREAD

**Issue by wlan0** [kubernetes/website#5872]
Currently, there are docs that describe

1. How to run the Cloud Controller Manager  -https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/administer-cluster/running-cloud-controller.md
2. How to develop your own Cloud Controller Manager - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
3. Examples - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/administer-cluster/cloud-controller-manager-daemonset-example.yaml
4. Flags in CCM - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/admin/cloud-controller-manager.md

There is no central point of reference for 

1. Concepts behind the Cloud Controller Manager
2. Reference to various implementations (Not just examples like here https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/tasks/administer-cluster/running-cloud-controller.md#examples, but a complete list that is maintained)

I propose that we add one more document about the Cloud Controller Manager under docs/concepts. I can work on this and get this done. 

Any comments/thoughts?

@andrewsykim @luxas @rrati @prydie @cheftako

**Comment by luxas** [comment]
Sounds good to me :)
