### ISSUE TITLE
Issue with k8s.io/docs/admin/authentication/

### ISSUE THREAD

**Issue by atoato88** [kubernetes/website#5886]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In "Anonymous requests" section, there is a sentence following.
```
In 1.5.1-1.5.x, anonymous access is disabled by default, and can be enabled by passing the --anonymous-auth=false option to the API server.
```

Is `--anonymous-auth=false` correct for **enabling** anonymous auth?
It should be `--anonymous-auth=true`, I think. 

**Proposed Solution:**

Change `--anonymous-auth=false` to `--anonymous-auth=true` in sentence for  enabling anonymous access option of 1.5.1-1.5.x

**Page to Update:**
https://kubernetes.io/docs/admin/authentication/#anonymous-requests

**Comment by tengqm** [comment]
Why is this issue still in open given that a patch that mentions this issue has been merged?

**Comment by atoato88** [comment]
I'll close this issue. 
@tengqm Thank you to your mention.
