### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/windows/

### ISSUE THREAD

**Issue by bkuhl** [kubernetes/website#5926]
https://kubernetes.io/docs/getting-started-guides/windows/ currently mentions that Kube 1.5 introduced alpha support, but there's no mention of how that progressed through more recent versions of Kubernetes.  **Can some details be added to this section of the docs to make it more clear whether it's still in alpha or whether it has progressed to beta or become officially supported?**

**Comment by tengqm** [comment]
@bkuhl You may want to check with the Windows SIG to get latest progress. Below is a link to the SIG: https://github.com/kubernetes/community/blob/master/sig-windows/README.md
