### ISSUE TITLE
what's kube-public? Issue with k8s.io/editdocs/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/website#5933]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Because of https://github.com/kubernetes/kubernetes/pull/36101  we need to add some description about namespace 'kube-public'

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by xiangpengzhao** [comment]
/unassign
ping @luxas ?

**Comment by luxas** [comment]
xref: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cluster-lifecycle/bootstrap-discovery.md

`kube-public` is a namespace that is automatically created (like kube-system and default), and should, by convention, have its content publicly accessible (even for anonymous/unauthenticated users). It is reserved for system usage.

**Comment by zhangxiaoyu-zidif** [comment]
@luxas 
Thanks very much for your answering.
I saw it and it's much helpful.

**Comment by luxas** [comment]
@zhangxiaoyu-zidif Do you want to help documenting that properly in the docs?

**Comment by zhangxiaoyu-zidif** [comment]
Yes, I will. Glad to do so.
