### ISSUE TITLE
Create a better onboarding experience for new contributors

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#5941]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

Information about becoming a contributor of SIG docs exists, but it's scattered across different repos and isn't always clear or straightforward. 

**Proposed Solution:**

We can provide a better onboarding experience for new contributors by:

1. Consolidate [CONTRIBUTING.md](https://github.com/kubernetes/kubernetes.github.io/blob/master/CONTRIBUTING.md) into the [README](https://github.com/kubernetes/kubernetes.github.io/blob/master/README.md).
2. Update the README with better guidelines for becoming a [community member](https://github.com/kubernetes/community/blob/master/community-membership.md).
3. Update the website's [contribution guidelines](https://kubernetes.io/editdocs/).

**Page to Update:**

https://kubernetes.io/editdocs/

**Comment by heckj** [comment]
@zacharysarah looks like you've self-subscribed to the "doc contributor user journey" work :-)

**Comment by anubhakushwaha** [comment]
@zacharysarah can I help on this? Further can you guide me a little on what all you want to be done? Thanks a lot.

**Comment by mistyhacks** [comment]
I think this is fixed by #9510
