### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose-interactive

### ISSUE THREAD

**Issue by mingrammer** [kubernetes/website#5947]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
There is a typo, in step 2 of katacoda module 4. `get pod` in "We'll use the `get pod` command with -l as p parameter" is not valid command.

**Proposed Solution:**
Need to change the `get pod` to `get pods`

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-interactive/

**Comment by heckj** [comment]
pending resolution with upstream content PR: https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/6

**Comment by mingrammer** [comment]
Thanks

**Comment by BenHall** [comment]
Thank you. The PR has now been merged
