### ISSUE TITLE
Add Slack display name requirements to new developer guide

### ISSUE THREAD

**Issue by bradtopol** [kubernetes/website#5952]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The other day I was informed that when interracting with the Kubernetes Developer Community on slack  I should change my Slack display name to be the same as my github handle.  The person telling me then wondered if we had this documented in the new developer guide.  I checked and this does not appear to be mentioned in the new developer guide.

**Proposed Solution:**
Add a section to the new developer guide (https://github.com/kubernetes/community/blob/master/contributors/devel/welcome-to-kubernetes-new-developer-guide.md)  to mention that when interracting with the Kubernetes Developer Community on slack all contributors should make sure  their Slack display name is the same as their github handle. 

**Page to Update:**
https://github.com/kubernetes/community/blob/master/contributors/devel/welcome-to-kubernetes-new-developer-guide.md

**Comment by bradtopol** [comment]
Great!  I'll add this one to my todo list. Thanks!

**Comment by xiangpengzhao** [comment]
It'd also be good to keep the icon the same between GH and slack. I think that's more recognizable. But that's okay, it depends on guys' wish.
