### ISSUE TITLE
KubeCon Doc Sprint potential topic  -- sprint on improving Kube developer contribution docs

### ISSUE THREAD

**Issue by bradtopol** [kubernetes/website#5953]
**This is a...** 

- [X ] Feature Request
- [ ] Bug Report

One potential topic for the KubeCon Doc sprint would be to work on documentation that helps new developers learn how to contribute to Kubernetes, what types of code learning tools to use, etc.  One possible example of the type of content to include in such a sprint would be content like that found in the following blog article:

https://developer.ibm.com/opentech/2017/06/21/tour-kubernetes-source-code-part-one-kubectl-api-server/

**Comment by castrojo** [comment]
Hi Brad, some of us in SIG Contrib-Ex have been working on a contributor guide here: https://docs.google.com/document/d/1XVm77kY6iIJ4iKNv0W6rmIN22PErcvEameDxlpdQVBc/edit

You're more than welcome to help out, feel free to contact me directly, cheers!

**Comment by jaredbhatti** [comment]
Andrew created a guide for doc sprint participants, which I've modified to use for a doc sprint in Melbourne.  Might be useful: https://docs.google.com/document/d/1No-yCMW99oqFMmBBCKvTdkgHzjfzk4OsP4tzulLM9eo/edit#heading=h.9y5m5yroljay
