### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by oltur** [kubernetes/website#5961]
**This is a...** 

- [ ] Feature Request
- [ X ] Bug Report

**Problem:**
"Connecting..." message is shown forever

**Proposed Solution:**

Want to start a tutorial finally :)

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Hello,

Thank you for letting us know. Sorry about this. We had a server with some connection issues. This should now have been resolved.  

Ben

**Comment by heckj** [comment]
@oltur I'm going to go ahead and close this issue for now, but if you're still seeing the problem or there's a specific documentation issue that we can help resolve, please re-open it.
