### ISSUE TITLE
Issue with OpenStack section of k8s.io/docs/concepts/cluster-administration/cloud-providers/

### ISSUE THREAD

**Issue by xsgordon** [kubernetes/website#5980]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The OpenStack cloud provider documentation does not explicitly list which services it expects to or can use on the underlying cloud. At a minimum it is currently believed this is:

* Nova (V2/V2.1) (mandatory?)
* Neutron LBaaS (V1 or V2) (optional?)
* Cinder (V1, V2, or V3) (optional?)
* Keystone (V2, or V3?) (mandatory?)

**Proposed Solution:**

Explicitly list the expectations.

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/

**Comment by FengyunPan** [comment]
Nova (V2) (MicroVersion will be supported in futrue)
Neutron LBaaS (V2) (V1 is deprecated)
Cinder (V1, V2,) (optional) (V3 will be supported in futrue)
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_client.go

**Comment by anguslees** [comment]
.. and Keystone (V2, V3)

Also it can use the Neutron "extraroute" extension to implement kubenet.

I think the only _required_ service is Keystone, and the rest are optional based on presence in the keystone catalog (and published neutron extensions).  If missing, the openstack provider will just claim the relevant features are not supported.

**Comment by arthur0** [comment]
Keystone V2 APIs are deprecated and will be removed in the next OpenStack release (Queens) #52563

**Comment by zacharysarah** [comment]
Closed by #6047
