### ISSUE TITLE
Add more glossary terms

### ISSUE THREAD

**Issue by chenopis** [kubernetes/website#5993]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Now that the revamped [Glossary](https://kubernetes.io/docs/reference/glossary/?fundamental=true) has been launched, we need to add more terms to the list.

**Proposed Solution:**
Add missing terms at Kubernetes doc sprints.

Here is the original glossary list from [v1.5 Reference ToC](https://v1-5.docs.kubernetes.io/docs/reference/#):

- [ ] Aggregation Layer
- [ ] Annotation (@spzala)
- [x] Certificate (@sdague)
- [x] Cloud Controller Manager (CCM)
- [ ] Cloud Provider
- [ ] ConfigMap (@zachpuck )
- [ ] Container Environment Variable
- [ ] Container Lifecycle Hook
- [x] Controller Manager
- [x] Cron Job
- [x] Custom Resource Definition (formerly Third Party Resource) (Cheryl)
- [ ] DaemonSet (Brad)
- [x] Deployment
- [ ] Device Plugin
- [ ] Disruption
- [x] docker (@jtborek)
- [x] Dynamic Volume Provisioning (@mohamed)
- [x] Etcd (Tina)
- [ ] Extension
- [ ] Federation
- [ ] Garbage Collection
- [x] Horizontal Pod Autoscaling (@zhangxiaoyu-zidif)
- [ ] HostAliases
- [x] Image (Chris)
- [x] Ingress Resource
- [x] Init Container
- [x] Job (Ryan)
- [ ] kube-proxy
- [ ] kubelet (@spzala)
- [x] Label
- [ ] Logging
- [ ] Name
- [x] Namespace
- [ ] Network Plugin
- [x] Network Policy (Radhika)
- [x] Node
- [x] Persistent Volume (Tina)
- [x] Pod
- [ ] Pod Disruption Budget
- [ ] Pod Lifecycle
- [ ] Pod Preset
- [ ] Pod Priority
- [x] Pod Security Policy (Radhika)
- [ ] Preemption
- [ ] Proxy
- [x] Replica Set (Ivange)
- [ ] Replication Controller (Chris)
- [ ] Resource Quota (@radhikapc)
- [ ] rkt
- [x] Secret
- [x] Security Context (@erwbgy)
- [ ] Selector
- [x] Service
- [x] Service Account (@radhikapc)
- [x] Stateful Set (formerly Pet Set)
- [x] Storage Class
- [ ] supervisord
- [ ] Sysctls
- [ ] Taint
- [ ] Toleration
- [x] Volume (Jared)
- [x] Volume Plugin (@midoblgsm)
- [x] fluentd (@radhikapc)

**Page to Update:**
Add YAML files to `/_data/glossary/` directory using the format outline in `/_data/glossary/_example.yml`. They should then automatically show up in 
https://kubernetes.io/docs/reference/glossary/?all=true

For example, `/_data/glossary/cluster.yaml` has this:

```
id: cluster
name: Cluster
tags:
- fundamental
- operation
short-description: >
  A set of machines, called nodes, that run containerized applications managed by Kubernetes.
long-description: >
  A cluster has several worker nodes and at least one master node.
```

A glossary definition can refer to other glossary terms. Here's `/_data/glossary/deployment.yaml`. The definition of Deployment uses {% glossary_tooltip %} to refer to the definition of Pod:

```
id: deployment
name: Deployment
full-link: /docs/concepts/workloads/controllers/deployment/
tags:
- fundamental
- core-object
- workload
short-description: >
  An API object that manages a replicated application.
long-description: >
  Each replica is represented by a {% glossary_tooltip term_id="pod" %}, and the Pods are distributed among the nodes of a cluster.
```

Kubernetes Version: v1.9

**Comment by Bubblemelon** [comment]
Third Party Resource has been deprecated. Custom Resource Definition now replaces it. [https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-third-party-resource/)

**Comment by chenopis** [comment]
I just added: 
- [ ] Aggregation Layer
- [ ] Certificate
- [ ] Cloud Controller Manager (CCM)
- [ ] Cloud Provider
- [ ] Container Environment Variable
- [ ] Container Lifecycle Hook
- [ ] Controller Manager
- [ ] Custom Resource Definition
- [ ] Device Plugin
- [ ] Disruption
- [ ] Dynamic Volume Provisioning
- [ ] Extension
- [ ] Federation
- [ ] Garbage Collection
- [ ] HostAliases
- [ ] Init Container
- [ ] Label
- [ ] Logging
- [ ] Network Plugin
- [ ] Pod Disruption Budget
- [ ] Pod Lifecycle
- [ ] Pod Preset
- [ ] Pod Priority
- [ ] Preemption
- [ ] Proxy
- [ ] Selector
- [ ] Storage Class
- [ ] Sysctls
- [ ] Taint
- [ ] Toleration
- [x] Etcd

**Comment by nikhita** [comment]
It would be nice to have a glossary for `Custom Resources` as well. Most users who search for CRDs would want to search for `Custom Resources` as well.

**Comment by midoblgsm** [comment]
It would be nice to add Volume Plugin to the list.

**Comment by sdague** [comment]
Label appears to already be added to the glossary -https://github.com/kubernetes/website/blob/2999938d81c87068fe333b9f69e10f551e70ae90/_data/glossary/labels.yaml#L1

**Comment by nikhita** [comment]
/remove-lifecycle rotten

still some terms left

**Comment by nikhita** [comment]
@chenopis would the `help wanted` label suit here? this also looks like something new contributors could tackle! :) `good first issue` might be nice as well.

**Comment by chenopis** [comment]
@nikhita Yes, for sure. The glossary is probably the easiest thing to contribute to, especially for new contributors. =)

**Comment by xmulligan** [comment]
@chenopis I updated your list and these are the ones that still haven't been written yet

- [ ]   Device Plugin
- [ ]   Disruption
- [ ]   Extension
- [ ]   Federation
- [ ]   Garbage Collection
- [ ]   HostAliases
- [ ]   Logging
- [ ]   Network Plugin
- [ ]   Pod Disruption Budget
- [ ]   Pod Lifecycle
- [ ]   Pod Priority
- [ ]   Preemption
- [ ]   Proxy
- [ ]   Sysctls

**Comment by sourabh1031** [comment]
I would like to work on this @nikhita

**Comment by daminisatya** [comment]
@sourabh1031 I worked on adding HostAliases, Pod Priority and Preemption to the Glossary page, Please feel free to pick others. 😃

**Comment by McCoyAle** [comment]
I was working on Federation and then ran into some questions. Federation has a similar architecture to the cluster architecture, in that it uses the Federation API and a controller manager to manage clusters opposed to nodes. Would it be worth while to include Federation API and Federation Controller Manger into the glossary separately?

**Comment by McCoyAle** [comment]
In addition, I was looking at proxy. But in the kubernetes documentation here: https://kubernetes.io/docs/concepts/cluster-administration/proxies/ there are 5 proxies listed. So would it be beneficial to list them separately, or bullet them under the proxy definition?

**Comment by sftim** [comment]
I suggest: update the issue description with a new list that clearly shows what terms are missing.
(If it helps, I can draw up the list and then someone with edit access can paste it in).

**Comment by sftim** [comment]
Is it OK to skip terms for:
- Federation _(deprecated)_
- `supervisord` (not relevant to v1.15 cluster operators)

?

**Comment by sftim** [comment]
If the above 3 PRs get merged, I think it'd be OK to close this issue as implemented.

**Comment by sftim** [comment]
/priority backlog
because most of the work is done

**Comment by sftim** [comment]
All remaining work (that is listed) is already started
/remove-good-first-issue

**Comment by sftim** [comment]
Also see #19535

**Comment by sftim** [comment]
@chenopsis is this OK to /close?

**Comment by sftim** [comment]
Related: #24528 Add _object_ to glossary
