### ISSUE TITLE
unique hostname is a requirement

### ISSUE THREAD

**Issue by Lennie** [kubernetes/website#5999]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
kubectl get nodes seems to show the master is NotReady when a node is added with the same hostname

**Proposed Solution:**
Make a unique hostname a requirement for every node just like MAC address and product_uuid.

Possible the code should reflect that too.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/install-kubeadm/#before-you-begin

v1.8.1

**Comment by heckj** [comment]
Thanks for the report @Lennie 

If you think the code should be doing something different, please open a bug report for that code - either at https://github.com/kubernetes/kuberntes/issues, or in this case perhaps at https://github.com/kubernetes/kubeadm/issues. I'll keep this report open to reflect the need in the documentation.
