### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by biswabandhu21** [kubernetes/website#6031]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Summary page at the end of module 1 is not working. I am using chrome browser.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

![issue1](https://user-images.githubusercontent.com/14542960/31954962-9bbe91ca-b8ac-11e7-844e-b6b5ec6ee3a3.png)

**Comment by BenHall** [comment]
Thank you for letting us know. This is externally hosted on Google Forms so outside of our control. Could you retry for us please?

**Comment by tengqm** [comment]
@biswabandhu21 Is this issue still there?
