### ISSUE TITLE
Issue with k8s.io/docs/concepts/policy/pod-security-policy/

### ISSUE THREAD

**Issue by php-coder** [kubernetes/website#6033]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The logic of selecting PSPs was modified in the https://github.com/kubernetes/kubernetes/pull/52849 but documentation for the PodSecurityPolicy admission plug-in wasn't updated.

**Proposed Solution:**
The documentation should be updated to take into account that:
- PSPs which allow the pod as-is (no defaulting/mutating) are preferred
- If the pod must be defaulted/mutated to be allowed, the first PSP (ordered by name) to allow the pod is selected
- During update operations, when mutations to pod specs are disallowed, only non-mutating PSPs are used to validate the pod

**Page to Update:**
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#admission

CC @liggitt

**Comment by liggitt** [comment]
Need to queue this up for 1.9, since 1.8 does not have that behavior yet

**Comment by tallclair** [comment]
I'm completely rewriting the PSP documentation. I will address this.

**Comment by php-coder** [comment]
This issue is mostly solved expect one point:

> During update operations, when mutations to pod specs are disallowed, only non-mutating PSPs are used to validate the pod
