### ISSUE TITLE
Move auto-generated docs into /docs/reference/generated directory

### ISSUE THREAD

**Issue by chenopis** [kubernetes/website#6037]
These are the auto-generated docs that need to moved into `/docs/reference/generated/`:
- [x] [api-reference](https://kubernetes.io/docs/api-reference/v1.8/) (@steveperry-53)
- [x] [cloud controller manager](https://kubernetes.io/docs/admin/cloud-controller-manager/) @wackxu 
- [x] [federation API operations](https://kubernetes.io/docs/reference/federation/v1/operations/)
- [x] [federation API definitions](https://kubernetes.io/docs/reference/federation/v1/definitions/)
- [x] [federation-apiserver](https://kubernetes.io/docs/admin/federation-apiserver/) @wackxu 
- [x] [federation-controller-manager](https://kubernetes.io/docs/admin/federation-controller-manager/) @wackxu 
- [x] [kube-apiserver](https://kubernetes.io/docs/admin/kube-apiserver/) @wackxu 
- [x] [kube-controller-manager](https://kubernetes.io/docs/admin/kube-controller-manager/) @wackxu 
- [x] [kube-proxy](https://kubernetes.io/docs/admin/kube-proxy/) @wackxu 
- [x] [kube-scheduler](https://kubernetes.io/docs/admin/kube-scheduler/) @wackxu 
- [x] [kubectl commands](https://kubernetes.io/docs/user-guide/kubectl/v1.8/) @steveperry-53
- [x] [kubectl binary](https://kubernetes.io/docs/user-guide/kubectl/) @steveperry-53
- [x] [kubeadm](https://kubernetes.io/docs/admin/kubeadm/) @wackxu 
- [x] [kubefed](https://kubernetes.io/docs/admin/kubefed/) @wackxu 
- [x] [kubefed_init](https://kubernetes.io/docs/admin/kubefed_init/) @wackxu 
- [x] [kubefed_join](https://kubernetes.io/docs/admin/kubefed_join/) @wackxu 
- [x] [kubefed_options](https://kubernetes.io/docs/admin/kubefed_options/) @wackxu 
- [x] [kubefed_unjoin](https://kubernetes.io/docs/admin/kubefed_unjoin/) @wackxu 
- [x] [kubefed_version](https://kubernetes.io/docs/admin/kubefed_version/) @wackxu 
- [x] [kubelet](https://kubernetes.io/docs/admin/kubelet/) @wackxu 

...more?

Here are the directories to be deprecated:
- [ ] `/docs/admin/`
- [ ] `/docs/api-reference/`
- [ ] `/docs/federation/`
- [ ] `/docs/resources-reference/`
- [ ] `/docs/user-guide/`

**Comment by heckj** [comment]
total nit, but would it be OK to move them into `/docs/reference/generated` and not have the extra auto- characters in there? no big deal if you prefer auto-generated, it just wrankled a little redundancy OCD in me

**Comment by chenopis** [comment]
I have no preference, so if @steveperry-53 is ok with it, go ahead and change it.

**Comment by wackxu** [comment]
If no one is working , I can help do it.

**Comment by chenopis** [comment]
@wackxu Thanks! @steveperry-53 is leading this, so please coordinate with him.

**Comment by wackxu** [comment]
@chenopis Thanks

**Comment by steveperry-53** [comment]
@wackxu Yes, we would be glad for your help.

**Comment by wackxu** [comment]
@steveperry-53 Very glad to do this. I have full time to do. And what is your progress now?

**Comment by steveperry-53** [comment]
@wackxu I put you name on several items in the list above. Would you be willing to take charge of these? First thing is to get the pages moved to a new location under /docs/reference.

**Comment by wackxu** [comment]
@steveperry-53 Thanks for your advice. And I will do it ASAP.

**Comment by steveperry-53** [comment]
@wackxu Thanks for getting started on this. At the top of this issue, please note which items have your name, and only do those. We want to hold off on some of these, like kubeadm and kubectl. Thanks.

**Comment by zacharysarah** [comment]
Boosting visibility for auto-generated descriptions from the conformance test suite: https://kubernetes.slack.com/archives/C1J0BPD2M/p1510859320000423

Autogenerated test suite docs aren't directly covered in this PR, but they're related and will (eventually) affect the work involved.

**Comment by steveperry-53** [comment]
I removed resources-reference from the checklist at the beginning of this issue. The resources-reference page is not in the doc set at all. So we can discuss separately whether it should be in the doc set. And if we think it should be, then of course we'll put it under /docs/ref/generated.
