### ISSUE TITLE
ephemeral storage is not well documented

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#6039]
**This is a...** 

- [X ] Feature Request
- [ ] Bug Report

**Problem:**
The "ephemeral-storage" resource is now gaining an equal foot with resources like CPU, memory and GPU. However, documentation about it is pretty weak thus needs an improvement.

**Proposed Solution:**
- Mention "ephemeral-storage" resource when CPU or memory are discussed
- Add cross-references between ephemeral-storage and huge-pages because they are related to each other in some scenarios
- Document the quota support for ephemeral-storage
- Document the 'LocalStorageCapacityIsolation' feature gate
- Document the relation between 'EmptyDir' volume type and ephemeral storage
- Document the resource reservation regarding ephemeral storage
- Document the pod eviction triggered by ephemeral storage outage
- Document the way ephemeral storage is probed and reported by kubelet

**Page to Update:**
The change may span concepts, workloads, admin and tasks documentation.

Kubernetes version: 1.8+

**Comment by tengqm** [comment]
disk requests are now taken into account during evictions.
xref: kubernetes/kubernetes#54316

**Comment by alice-sawatzky** [comment]
the documentation still does not make it clear what all falls under the scope of this limit. are container logs counted? emptyDirs? presumably the writable layer of the container, but again this is not made explicit. The docs in their current state only describe what's _stored on_ ephemeral storage, not what's subject to the limit's control.
