### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/zookeeper/

### ISSUE THREAD

**Issue by mustafaakin** [kubernetes/website#6043]
**This is a...** 
- [ ] Feature Request
- [X ] Bug Report

**Problem:**

The link does download a HTML file instead of YAML, so that the command in tutorial does not work kubectl apply -f https://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml

**Proposed Solution:**

Make https://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml great again

**Page to Update:**
k8s.io/docs/tutorials/stateful-application/zookeeper/

**Comment by heckj** [comment]
Wow, icky! 

Verified that the file downloaded isn't just the YAML goodness from the site, but wrapped in HTML tags now...

/cc chenopis zacharysarah 

Will see if I can dig into the netlify configuration, or ask someone who has more access, so see if we can configure exclusions specifically for YAML files so they get provided with the correct content-type and not wrapped up in HTML-ness...

**Comment by heckj** [comment]
Doing a bit of digging, I suspect this might be related more to our configuration of Jekyll than netlify hosting it. That said, I'm only working from an iPad at the moment, so can't try out multiple renders locally to see what delta's might incur. 

A potential solution might be to redirect to the source files on github using their raw mechanism if I can't figure a way to allow jekyll's build & redirect to provide the directly hosted content. 

/cc steveperry-53 as you have worked with a lot of the redirect stuff - this might be obvious to a more experienced eye

**Comment by tengqm** [comment]
Verified in another issue report. This problem only exists on the following path so far:

/docs/tutorials/stateful-application/

Any other path above or below that subdirectory is fine.

**Comment by chenopis** [comment]
When I compare the files that are working to the ones that aren't, I notice that the difference is that the ones that don't work have `---` in them. My crackpot theory is that those are being interpreted as front matter delimiters, so the files are being processed instead of being served raw. I've only looked at it for like two minutes, so we would need to verify.

**Comment by tengqm** [comment]
@chenopis Verified your theory. The "`---`" lines do cause the problem. For example, the following produces HTML instead of YAML too:

```
 wget https://k8s.io/docs//user-guide/environment-guide/show-rc.yaml
```

**Comment by heckj** [comment]
Thank you @tengqm - I’ll work @chenopis ’s suggestion for a workaround to make those examples functional again
