### ISSUE TITLE
Redirect https://kubernetes.io/v1.1/docs/api-reference/v1/definitions/ to the new reference pages (currently gives 404).

### ISSUE THREAD

**Issue by bowei** [kubernetes/website#6046]
**This is a...** 
- [x ] Bug Report

**Problem:**
top websearch hit for "pod spec kubernetes" leads to https://kubernetes.io/v1.1/docs/api-reference/v1/definitions/ which is a 404. Should we add a redirect?

**Proposed Solution:**
Add redirect.

**Page to Update:**
`https://kubernetes.io/v1.1/docs/api-reference/v1/definitions/` and similar URIs

**Comment by zacharysarah** [comment]
@bowei The top Google result for me shows a link to https://kubernetes.io/docs/api-reference/v1.8/. The 404 link you listed doesn't appear on the first page, so I think we're OK.
