### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose-interactive/

### ISSUE THREAD

**Issue by z-oo** [kubernetes/website#6049]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The description is confusing at the following places:
1) `We have now a running Service called kubernetes-bootcamp. Here we see that the Service received a unique cluster-IP, an internal port and an external-IP (the IP of the Node).` The reality is that external-IP is `<none>`
2) `curl host01:$NODE_PORT`. Where does "host01" come from? It is neither my current host, nor the endpoint of `kubernetes-bootcamp` (according to kubectl describe). I can figure that it has the same ip as service `kubernetes` (`kubectl describe deployment/kubernetes`), but why?

**Proposed Solution:**
Better explanation to eliminate the confusion.

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks for the feedback on this. We've updated how the setup works to make the hostname clearer.

/close
