### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/connect-applications-service/

### ISSUE THREAD

**Issue by MaheshIBM** [kubernetes/website#6054]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The page redirects to another article for generating ssl secret file, that inturn needs make and go to be installed. Its unnecessary extra work which I feel has nothing to do with how secrets works. The article also breaks the pattern of consistently using command line and asks to make use of "make" tool.

**Proposed Solution:**
Give steps to create the certificates, base64 encode the content and then create the kubernetes secret. 
Example below.
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout d:\tmp\nginx.key -out d:\tmp\nginx.crt -subj "/CN=nginxsvc/O=nginxsvc"

 cat nginx.key |  base64
 cat nginx.crt |  base64

Then create a yaml file as below.

apiVersion: "v1"
  kind: "Secret"
  metadata:
    name: "nginxsecret"
    namespace: "default"
  data:
    nginx.crt: "xxx"
    nginx.key: "xxx"

Then run the command 
kubectl create -f d:\kubernetes\db2\nginxsecrets.yaml

This will give the reader a better understanding of what is happening under the hood, anyway someone dealing with certificates will be more comfortable with openssl then the kubernetes go client or the make tool.
**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/

**Comment by tengqm** [comment]
This suggestion makes sense to me. @MaheshIBM, do you want to propose a PR or you want someone else to fix it?

**Comment by MaheshIBM** [comment]
I will submit a PR, may be end of next week.

**Comment by MaheshIBM** [comment]
Opened PR https://github.com/kubernetes/website/pull/6093

**Comment by zacharysarah** [comment]
Closed by #6093
