### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/overview/

### ISSUE THREAD

**Issue by tboemker-bkfs** [kubernetes/website#6059]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This documentation is contradictory:

> It’s typically best to create a service before corresponding replication controllers. This lets the scheduler spread the pods that comprise the service.
> You can also use this process to ensure that at least one replica works before creating lots of them:
> 1. Create a replication controller without specifying replicas (this will set replicas=1);
> 2. Create a service;
> 3. Then scale up the replication controller.

The text says to create the service before the replication controller, but the numbered list says to create the replication controller before the service.
**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by bitfield** [comment]
This seems to be fixed by 60b7e3f42ee502f7388bf2662a8f420c056ec32c.

**Comment by aburdenthehand** [comment]
Looks like this was updated for a separate issue. Content now reads:
"It’s typically best to create a service before the corresponding replication controllers. This lets the scheduler spread the pods that comprise the service."

Recommend closing.
