### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/what-is-kubernetes/

### ISSUE THREAD

**Issue by dipakmdhrm** [kubernetes/website#6073]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
This documents assumes that the reader have a basic understanding of the concept of containers and some experience with administration/operations work.

**Proposed Solution:**
Add a section that specifies this as prerequisite for reading this page.

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

**Comment by zacharysarah** [comment]
@dipakmdhrm 👋 That's great feedback, thanks!
