### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by MufeezAhmed** [kubernetes/website#6084]
**This is a...**

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
 what is meant by pods is not explained before starting interactive session
please enhance documentation

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@heckj 👋 FYI

**Comment by heckj** [comment]
Hi @MufeezAhmed, sorry for the delay in a response. We've been running with the expectation that you'd likely have already seen the "concepts" section of the docs before hitting into the tutorials directly.

Could you tell the me the page that you were on when you first saw this reference? I was thinking we might annotate some of the pages (at least the ones that are hosted at k8s.io with glossary entries so you can at least get a link back to concept/reference docs) - is that be the kind  of enhancement you were envisioning that would improve the documentation?

**Comment by MufeezAhmed** [comment]
glossary entries so we can at least get a link back to concept/reference docs , would be a good change
