### ISSUE TITLE
[WIP] Put contributing guide(s) on kubernetes.io 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/website#6102]
This is a...
- [X] Feature Request
- [ ] Bug Report

**Problem:**
All codebase and community contributor guides, documents, and relevant materials are scattered in the [community github repo](https://github.com/kubernetes/community). A recent survey of 110 participants concluded a pattern that contributors (new and others) need a central point where other k8s documents are located for a smoother flow and easier to locate. Focus groups are also ongoing with current contributors about their experience. 

**Proposed Solution:**
Put all updated and relevant contributor information that is located in the [community repo](https://github.com/kubernetes/community) in multiple files into a single displayed source on kubernetes.io. This would fall under "Contributing to the Kubernetes Docs" with the title "Contributing to the Kubernetes Codebase & Community" 

**Page to Update:**
https://kubernetes.io/docs/home/

will also 'live' on the user journeys/personas piece for 'code contributor' 

**Additional Info**
- this will have a max of 8 sections (per @chenopis advice)
- a Developers Guide will be one of those sections; this is being worked on by another team (RyanJ at RH is point)
- @castrojo  and I will run this through SIG-ContribX; join our bi-weekly discussions/mailing list
- need docs for final edits
- This is our raw document that we are working from -[link](https://docs.google.com/a/google.com/document/d/1XVm77kY6iIJ4iKNv0W6rmIN22PErcvEameDxlpdQVBc/edit?usp=sharing). We will be trimming duplicate info, condensing, and adding information so that it's not 65 pages ( :) )

**Comment by guineveresaenger** [comment]
Initial PR for starting point:
https://github.com/kubernetes/community/pull/1409

**Comment by guineveresaenger** [comment]
Umbrella issue to flesh out the README and surrounding folder in PR above: https://github.com/kubernetes/community/issues/1413

**Comment by mistyhacks** [comment]
I believe this is fixed by #9510

**Comment by castrojo** [comment]
/reopen
/cc @mrbobbytables 

This issue is about the overall k8s contributor's guide, not the documentation contribution guide. We're close to finishing this, @mrbobbytables can you update this issue when we go live?

**Comment by mrbobbytables** [comment]
@castrojo sure thing! Shouldn't take too long once the cname record is in place.

**Comment by mrbobbytables** [comment]
The cname record is put in place, netlify configured and the site is now live! :)

**Comment by DanyC97** [comment]
@mrbobbytables what is the url for site you mentioned above ?

**Comment by mrbobbytables** [comment]
Sorry for the delay in response, the project is over in https://github.com/kubernetes-sigs/contributor-site. As all work is going on over there. I think it's safe to close this issue :) Can be reopened if needed.

/close
