### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose-intro/

### ISSUE THREAD

**Issue by Endaris** [kubernetes/website#6112]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The symbol used for pods is inconsistent.
On https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-intro/ in the section "Pods Overview" pods are introduced with a circle that contains containerised applications (cube) and optionally volumes (cylinders).
It is also noted that pods have an own IP-address that is displayed outside of the circle.
On the page mentioned in the title, the legend tells that pods are displayed as cubes which contradicts the previous graphic.

**Proposed Solution:**
As I was just trying to get into Kubernetes I'm not entirely sure how this should be fixed but I think the legend in the graphic below the heading "Services and Labels" should be adjusted so that pod = circle.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/

**Comment by zacharysarah** [comment]
@Endaris 👋 Thanks for this issue. It does look like the legend and usage are inconsistent across pages.
