### ISSUE TITLE
Issue with k8s.io/docs/admin/authentication/

### ISSUE THREAD

**Issue by lonial** [kubernetes/website#6116]
Why kubernetes has used term "id token" in its documentation and not use "access token" for accessing Kube API from kubectl? 

Access token is to be used for accessing some service like Kubernetes API (resource server in open id terminology). See use of access token as mentioned in Open Id specs: https://openid.net/specs/openid-connect-basic-1_0.html#TokenOK 

"The Client can then use the Access Token to access protected resources at Resource Servers. "

Client should verify claims of Id token as mentioned in below link and it should not use it for accessing Kube API as it is mentioned in this Kubernetes page.
https://openid.net/specs/openid-connect-basic-1_0.html#IDTokenValidation.

IMO we are also failing to differentiate between resource server(=Kube API) and client(=kubectl) based on open id terminology.

**Comment by lomori** [comment]
Actually, they are using ID Token and not the access token. That's a bigger issuer than just documentation. I really believe this is a design issue that should be addressed. Nobody else, that I know of, uses ID Token as bearer and probably not in the OIDC spec.
