### ISSUE TITLE
Inconsistent apiVersion comments in two nginx Deployment yaml files.

### ISSUE THREAD

**Issue by zuyu** [kubernetes/website#6120]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
PR #5920 updated a nginx deployment yaml file w/ 1.8 version, but did not override the comment for the same entry in another file using 1.7 version.

**Proposed Solution:**
Update the file mentioned below, and check if there are other possible inconsistencies in the repo.

**Page to Update:**
https://github.com/kubernetes/website/blob/master/docs/concepts/overview/working-with-objects/nginx-deployment.yaml#L1

**Comment by zacharysarah** [comment]
Closed by #6187.
