### ISSUE TITLE
Issue with deletionTimestamp in https://kubernetes.io/docs/api-reference/v1.8/#objectmeta-v1-meta

### ISSUE THREAD

**Issue by cben** [kubernetes/website#6128]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
ObjectMeta.deletionTimestamp documentation in api docs seems to predate `finalizers` field and the [cascading deletion in progress concept](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/).
It says:

> The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field. Once set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time.

IIUC this is no longer true.  It does point to https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#metadata which has an updated definition (emphasis mine):

> The resource will be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field **except when the object has a finalizer set**. In case the finalizer is set the deletion of the object is postponed at least until the finalizer is removed.

**Proposed Solution:**
Take definition form api-conventions.md.
Perhaps also amend the sentence "This field is set by the server when a graceful deletion is requested by the user, ..." (identical in both) — my impression is graceful deletion was one scenario, but it can *also* be set in cascading delete / finalizers scenario without any grace period?
*I'm just reading the docs and don't know what I'm speaking about!*

**Page to Update:**
Specifically in https://kubernetes.io/docs/api-reference/v1.8/#objectmeta-v1-meta but same text is duplicated in many other places eg. https://kubernetes.io/docs/reference/federation/v1/definitions/#_v1_objectmeta

**Comment by wackxu** [comment]
I can help fix it

**Comment by zacharysarah** [comment]
Closed by https://github.com/kubernetes/kubernetes/pull/54936
