### ISSUE TITLE
Tables in K8s docs use GitHub-flavored Markdown

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#6134]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:** It's not clear in our [contribution guidelines](https://kubernetes.io/docs/home/contribute/style-guide/) that K8s docs use [GitHub-flavored Markdown](https://github.github.com/gfm/). A user encountered difficulty with [table formatting](https://kubernetes.slack.com/archives/C1J0BPD2M/p1509479186000460).

**Proposed Solution:** Add a note to the style guide indicating that K8s docs use GitHub-flavored Markdown.

**Page to Update:**
https://kubernetes.io/docs/home/contribute/style-guide/

**Comment by bradtopol** [comment]
@zacharysarah I can handle this one if you like.

**Comment by zacharysarah** [comment]
@bradtopol Awesome. Go for it!

**Comment by dungeonmaster18** [comment]
Hey @bradtopol are you still working on this? If not can I take this?

**Comment by zacharysarah** [comment]
Closed by #6229
