### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/

### ISSUE THREAD

**Issue by cp10000** [kubernetes/website#6149]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
One of the biggest challenge for me to learn and Kubernetes  is to learn all the different components like ETC, Flannel,...etc.

**Proposed Solution:**
I propose to have a dictionary of the most popular Kubernetes components right on the Kubernetes website.    This way we can all work from a single dictionary and become proficient faster.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
I'm closing this issue because the dictionary can be found at https://kubernetes.io/docs/reference/glossary/.
If that glossary is not what you wanted, feel free to reopen this.
