### ISSUE TITLE
Missing -extensions v3_ext -extfile csr.conf arguments in /docs/concepts/cluster-administration/certificates/#openssl

### ISSUE THREAD

**Issue by wallrj** [kubernetes/website#6156]
- [ ] Bug Report

**Problem:**

The instructions for generating a new server.crt are missing some command line arguments.
`-extensions v3_ext -extfile csr.conf` are required, otherwise I get a certificate without any subjectAltNames and `kubectl` complains:

I found the fix via this comment from @ahuffman: https://github.com/kubernetes/kubernetes/issues/27442#issuecomment-241894715

May also be related to https://github.com/kubernetes/website/issues/4142

**Page to Update:**

https://kubernetes.io/docs/concepts/cluster-administration/certificates/#openssl

```
master $ openssl version
OpenSSL 1.0.2g  1 Mar 2016

master $ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38 cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1 .8.3", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38 cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1 .8.3", Compiler:"gc", Platform:"linux/amd64"}
```

/cc @dippynark

**Comment by wallrj** [comment]
See 
 * https://coreos.com/kubernetes/docs/1.6.1/openssl.html
 * https://github.com/coreos/coreos-kubernetes/blob/master/Documentation/openssl.md#generate-the-api-server-keypair

For correct instructions.

**Comment by tengqm** [comment]
Thanks for reporting this. Fix proposed.
