### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by ciufudean** [kubernetes/website#6171]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Incomplete documentation

**Proposed Solution:**
Fix it

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

this is the line that needs completion: "Your Kubernetes server must be version or later."

**Comment by tengqm** [comment]
Looks like a dup of #6165 ?

**Comment by steveperry-53** [comment]
Closing as duplicate of #6165.
