### ISSUE TITLE
Images broken on recent Grafeas post

### ISSUE THREAD

**Issue by mattmoyer** [kubernetes/website#6178]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Images on http://blog.kubernetes.io/2017/11/securing-software-supply-chain-grafeas.html are broken. It looks like they are referencing private Google docs files.

**Proposed Solution:**
Make the Google docs files public or copy the images somewhere else.

**Page to Update:**
http://blog.kubernetes.io/2017/11/securing-software-supply-chain-grafeas.html

cc @kelseyhightower

**Comment by kbarnard10** [comment]
This is now resolved.

**Comment by mattmoyer** [comment]
Thanks @kbarnard10!
