### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by jadair-cloudera** [kubernetes/website#6179]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
typo in tutorial docs (Module 1, step 3 of 3)

**Proposed Solution:**
Change "it’s status" to "its status".

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
I've examined the source. The typo came from katacoda so an issue should be reported there.

**Comment by jadair-cloudera** [comment]
I reported this issue by clicking the issue reporting button on the page.
It's not worth my time to go try to navigate somebody else's web site to
correct a typo, but you could report an issue to them.

**Comment by tengqm** [comment]
@jadair-cloudera Thanks for letting us know.
