### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/azure/

### ISSUE THREAD

**Issue by jonsinfinity** [kubernetes/website#6183]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The link to the Azure Container service is pointing at old documentation as noted on microsofts website. Here is the new documentation link: https://docs.microsoft.com/en-us/azure/aks/intro-kubernetes

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by dungeonmaster18** [comment]
Hey, anyone from members group please close this issue. This issue has been solved in pull #6184
