### ISSUE TITLE
kubectl cluster-info never fails, even when no host is running

### ISSUE THREAD

**Issue by elharo** [kubernetes/website#6193]
- [ ] Feature Request
- [ X] Bug Report

**Problem:**

The docs say

Check that kubectl is properly configured by getting the cluster state:
kubectl cluster-info
If you see a URL response, kubectl is correctly configured to access your cluster.
If you see a message similar to the following, kubectl is not correctly configured:
The connection to the server <server-name:port> was refused - did you specify the right host or port?

However `kubectl cluster-info` seems to always succeed. That is,

elharo-macbookair99:wordpress-experiment elharo$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080

In fact, no master is running there which I find when I use 'kubectl cluster-info dump':
 
elharo-macbookair99:wordpress-experiment elharo$ kubectl cluster-info dump
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Proposed Solution:**

Change to

Check that kubectl is properly configured by dumping the cluster state:
kubectl cluster-info dump

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/#before-you-begin

**Comment by dungeonmaster18** [comment]
Yes I was also able produce this error as well. I guess we need to update the document. I can take this but before jumping in I need approval from one of the members here.

**Comment by tengqm** [comment]
@dungeonmaster18 If you believe this is an issue, feel free to submit a PR. You do not need an approval to help improve the docs.

**Comment by zacharysarah** [comment]
@dungeonmaster18 Please do feel free to open a PR against this issue&mdash;no permission required.

**Comment by dungeonmaster18** [comment]
Please close this issue someone. It has been fixed and merged.
