### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by preethbshetty** [kubernetes/website#6217]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by heckj** [comment]
hi @preethbshetty  - this looks like you've opened a bug on accident. I'm going to close this, but if there's an issue you'd like to bring up related to the documentation, please re-open and provide the details
