### ISSUE TITLE
Support liveness and readiness probe with HTTP check that checks response text

### ISSUE THREAD

**Issue by pjfanning** [kubernetes/website#6253]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
This is equivalent to the HAProxy `http-check expect status 200 string READY` (https://www.haproxy.com/documentation/aloha/7-0/haproxy/healthchecks/)
Based http://kubernetes.io/docs/user-guide/liveness/ it appears that the healthz checks only check the HTTP response code.
I'm working with a health check that is a company standard and that returns status strings.

**Proposed Solution:**
Some capability to check the text of the response to see if it contains a particular string.
This check would probably need to only check the first n characters to prevent issues with memory.

**Page to Update:**
 http://kubernetes.io/docs/user-guide/liveness/

**Comment by tengqm** [comment]
This sounds more like a kubernetes feature request than a documentation issue. Please try open an issue in the kubernetes/kubernetes project.
If you want more options for health checking, you may want to check this code: https://github.com/kubernetes/kubernetes/blob/master/pkg/probe/http/http.go#L95

As far as the documentation is concerned, this issue can be closed.
