### ISSUE TITLE
Issue with k8s.io/docs/admin/service-accounts-admin/

### ISSUE THREAD

**Issue by megastallman** [kubernetes/website#6267]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
There is no "User" description, just the serviceaccounts. If I create a "ClusterRoleBinding" with a "User" subject, it gets created, but I don't know how to retrieve its credentials.

**Proposed Solution:**
Please implement and describe users creation and their kubeconfig retrieval.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
This can be closed because related problems have been covered in issue #2792.
