### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-replicated-stateful-application/

### ISSUE THREAD

**Issue by bodyno** [kubernetes/website#6273]
![image](https://user-images.githubusercontent.com/5443058/32687016-25f31b10-c6ed-11e7-84fc-5fb5a1950b52.png)

**Comment by tengqm** [comment]
need more details for diagnosis. looks like not a documentation problem.

**Comment by bodyno** [comment]
Is it because I use kubeadm?

**Comment by tengqm** [comment]
@bodyno No. It is because a screenshot is not providing enough information for others to help. You will need to provide more information by examine the output from `kubectl describe` or `kubectl logs`.

**Comment by bodyno** [comment]
Ok. I got. Close now. Next Time When I encounter again. I will do it like you said.
