### ISSUE TITLE
Request for examples in documentation for Custom Resources

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes/website#6278]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
The description of custom resources is very abstract. Someone from the K8S team pointed me towards CRDs as a possible way to describe nodes with custom hardware (eg "this node has a GPU, and that node has an FPGA accelerator"), but the description of CRs and controllers is so high-level that it's difficult for me to understand how to map the concepts well.

**Proposed Solution:**
Two or three examples of real-world uses of CRs would be appreciated. Ideally one or two of these would be a "typical" example showing how people are using the feature today, and one or two of them would be "extreme" examples showing how the feature could be stretched, as well as the benefits and drawbacks of stretching the feature in that way. Combined, these would give intermediate-level K8S users a reasonable mental model of how the feature _should_, as well as _could_, be used.

**Page to Update:**
https://k8s.io/docs/concepts/api-extension/custom-resources/

**Comment by zacharysarah** [comment]
@adrianludwin 👋 There's a PR in progress to help with this: #6238. It's in review right now, hopefully it'll be published within the next week.

**Comment by adrianludwin** [comment]
Great to hear, thanks.
