### ISSUE TITLE
Issue with k8s.io/docs/reference/federation/

### ISSUE THREAD

**Issue by jxadro** [kubernetes/website#6297]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Link broken in the documentation.
In the page: https://v1-7.docs.kubernetes.io/docs/reference/federation/ when you click on "model definitions" -> "federation/v1beta1: operations, model definitions" it goes to "https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/federation/docs/api-reference/federation/v1beta1/definitions.html" and that page does not exit, the error shown is: "Error: Cannot load file https://raw.githubusercontent.com/kubernetes/kubernetes/HEAD/federation/docs/api-reference/federation/v1beta1/definitions.html"

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@jxadro 👋 This is an issue with 1.7 docs which are not actively maintained. (See the page banner at the top of [the page](https://v1-7.docs.kubernetes.io/docs/reference/federation/).)
