### ISSUE TITLE
"GKE" > "Google Kubernetes Engine"

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#6302]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:** From https://github.com/kubernetes/website/pull/6300#issuecomment-344069008:

Google Container Engine is now Google Kubernetes Engine. GKE should no longer be used as an acronym for Google Container Engine, and should be replaced with "Google Kubernetes Engine" wherever possible.

**Proposed Solution:** Repo-wide find and replace.

**Comment by dungeonmaster18** [comment]
I will do that. Can you assign it to me?

**Comment by zacharysarah** [comment]
Just open a PR that says “closes #6302” in the OP

**Comment by chenopis** [comment]
@dungeonmaster18 This was taken care of by https://github.com/kubernetes/website/pull/6300, but please feel free to search the repo and double check my work. =)
