### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configmap/

### ISSUE THREAD

**Issue by andr3wtryan** [kubernetes/website#6305]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report
- [x] Content Issue

**Problem:**
The last sentence of the first part of the section "Use kubectl to create a ConfigMap" (right above the start of the next section, "Create ConfigMaps from directories") seems to be backwards with the former and latter statement. From what I understand (which isn't too much) the "describe" commands contain more information than the "get" commands. Here is the sentence in question:
"You can use `kubectl describe` or `kubectl get` to retrieve information about a ConfigMap. The former shows a summary of the ConfigMap, while the latter returns the full contents of the ConfigMap."

**Proposed Solution:**
Seems like the sentence is just backwards, either swapping the words former and latter or switching the order of the describe and get commands would probably resolve the issue if it is indeed an issue.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configmap/

Kubernetes Version: v1.8

**Comment by stewart-yu** [comment]
Does  your confusion resolved?

**Comment by andr3wtryan** [comment]
Looks good to me. 

I'm realizing now that the way that it was written was correct (so I apologize for the trouble), but to be fair it was unclear to me because I rarely use the `-o` option of `kubectl get`. I usually just use `kubectl get` in its simplest form, to list all of the resources of a particular type. So `get` to me displayed less information than `describe` does. My apologizes!

I read all the diffs and they language is definitely clearer all around. 

Thank you for your patience as I ride the learning curve.
