### ISSUE TITLE
Open same site when switching documentation version

### ISSUE THREAD

**Issue by dvdgsng** [kubernetes/website#6336]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
Changing the version of the k8s documentation redirects to /docs/home.

**Proposed Solution:**
Redirect to the same site for the older version.

Meaning: When changing the version from a specific documentation site ( e.g. https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#) it should open the same document for the older version (i.e. https://v1-7.docs.kubernetes.io/docs/concepts/workloads/controllers/statefulset/).

If no doc entry is available, redirect to home.

**Page to Update:**
https://kubernetes.io/docs/home/

PostgreSQL doc does this pretty well, i.e. changing the version on any doc page redirects to the proper page.
e.g.: when visiting https://www.postgresql.org/docs/current/static/typeconv-oper.html and changing version it redirects to https://www.postgresql.org/docs/9.6/static/typeconv-oper.html

**Comment by zacharysarah** [comment]
@dvdgsng 👋 Thanks for reporting your experience. This issue and #6337 are duplicates of an open issue, #5930. We're working on a fix, but it's a long-term project.
