### ISSUE TITLE
Documentation search does not honor selected version

### ISSUE THREAD

**Issue by dvdgsng** [kubernetes/website#6337]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Despite having selected a different version of k8s in the documentation (e.g. 1.7), the search does only show results from the current/latest version.

**Proposed Solution:**
Show search results for selected version.

**Page to Update:**
https://kubernetes.io/docs/home/

**Comment by zacharysarah** [comment]
@dvdgsng 👋 Thanks for reporting your experience. This issue and #6336 are duplicates of an open issue, #5930. We're working on a fix, but it's a long-term project.
