### ISSUE TITLE
Restructure and rewrite Minikube docs

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#6339]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
A number of issues are reported against various pages that explain how to install and run Minikube. In addition, there's a good deal of overlap or confusing or conflicting information across different tasks and tutorials on Minikube. We need a good Minikube entry point for the user journeys project, and cleaning up this content will help UX more generally as well.

**Proposed Solution:**
Look at the following topics:
- [Running Kubernetes Locally via Minikube](https://kubernetes.io/docs/getting-started-guides/minikube/)
- [Install Minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/)
- [Using Minikube to Create a Cluster](https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/)
- [Hello Minikube](https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/)
- [Minikube README](https://github.com/kubernetes/minikube/blob/master/README.md)

Reorganize content to provide a single authoritative source for each of the following topic areas:
- prerequisites
- installing
- basic usage
- further exploration/tutorials

Make sure that appropriate [topic templates](https://kubernetes.io/docs/home/contribute/page-templates/) are applied.

Edit the text so that is complies with the [style guide](https://kubernetes.io/docs/home/contribute/style-guide/).

Useful comments about docs generally, Minikube in particular:
#4403
(This issue includes some useful comments about the distinction, or lack thereof, between tasks and tutorials.)
Other issues against Minikube docs (technical changes):
#2667
#5170
#6803 

Note: @steveperry-53 recently noted that docs for installing xhyve or other VM need particular attention.

**Comment by BenHall** [comment]
Highlighted in Slack so I thought I would add comments here. 

In the last sig-docs, I demo'ed out updates to the interactive tutorials environment (https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/) which is now based on Minikube v0.25.0. 

The focus of the tutorials are more on happens after you install Minikube, starting from `minikube start` to deploying your first application. The content can be extended if you'd like to showcase other aspects of Minikube/Kubernetes.
