### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by dsgordon333** [kubernetes/website#6340]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Suddently getting the following when trying to connect to 127.0.0.1/ui
Error: 'ssh: rejected: connect failed (Connection refused)'

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by dsgordon333** [comment]
127.0.0.1:8080/ui that is.

**Comment by dungeonmaster18** [comment]
Hi @dsgordon333 , your seems to be related to dashboard not with the document or k8 website. If it is related to website please create issue here : https://github.com/kubernetes/dashboard.
