### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by bailey-96** [kubernetes/website#6348]
**This is a:** 
- [x] Bug Report

**Problem:**
404 Error - page not found.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/

Working my way through the Kubernetes boot camp and its great but got to this page and it won't load.

Thanks

**Comment by stewart-yu** [comment]
Where the url from?

**Comment by dungeonmaster18** [comment]
There are few other links as well which are showing 404 error - page not found. I think we should create a generalised issue to address this.

**Comment by alexppg** [comment]
I didn't see this and created #6349. But I guess it's ok.

**Comment by stewart-yu** [comment]
Just second  url link @alexppg  i will help fix it

**Comment by BenHall** [comment]
Sorry about this. As a workaround, add /index.html to the 404 pages. 

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/index.html

**Comment by alexppg** [comment]
No problem, I just used the repository, this issue was just FYI. Close it as you wish.

**Comment by bailey-96** [comment]
Issue appears to be fixed, thanks.
