### ISSUE TITLE
Some posts return 404

### ISSUE THREAD

**Issue by alexppg** [kubernetes/website#6349]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Some pages return 404. The ones I saw are:
- https://kubernetes.io/docs/home/
- https://kubernetes.io/docs/tutorials/
- https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

I guess there will be more.

**Comment by BenHall** [comment]
Sorry about this. As a workaround, add /index.html to the 404 pages. 

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/index.html

**Comment by dungeonmaster18** [comment]
This issue is fixed, so someone please close it.

cc: @zacharysarah @tengqm @steveperry-53
