### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/scale-intro/

### ISSUE THREAD

**Issue by leonahenry** [kubernetes/website#6350]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Tutorial and docs home links are giving 404. error:
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/  and https://kubernetes.io/docs/home/ don't work.
also most of the module links at the bottom part of the Kubernetes basics page are broken.

**Proposed Solution:**
Please fix the broken links

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/ 
https://kubernetes.io/docs/home/
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/
https://kubernetes.io/docs/tutorials/kubernetes-basics/

**Comment by BenHall** [comment]
Thank you for reporting this. I just noticed the same.

Related: #6349 #6348

@steveperry-53 @zacharysarah 👋

**Comment by BenHall** [comment]
As a workaround, add /index.html to the 404 pages. 

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/index.html
https://kubernetes.io/docs/tutorials/kubernetes-basics/update-interactive/index.html

**Comment by dungeonmaster18** [comment]
This issue is fixed, so someone please close it.

cc: @zacharysarah @tengqm @steveperry-53
