### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by slevinson** [kubernetes/website#6351]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
returns Page not found 404

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by dungeonmaster18** [comment]
Hi @slevinson thanks for reporting the problem got fixed.

**Comment by dungeonmaster18** [comment]
This issue is fixed, so someone please close it.

cc: @zacharysarah @tengqm @steveperry-53
