### ISSUE TITLE
Auditing topic is unclear, missing information

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#6365]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The [Auditing](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/) topic is unclear and is missing important information.

**Proposed Solution:**
Rewrite the topic for clearer structure and complete information. Specifically note the following (and check with tech reviewers to add anything else):
- Audit logging must be explicitly enabled
- There is no default location for the logs (IOW, specifying a log location is required when you enable -- it's not as simple as setting a single flag/option/argument)

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

Additional Information:
Make sure to keep information about differences in behavior in different versions. Consider checking for planned changes in upcoming releases.

**Comment by tengqm** [comment]
#6427

**Comment by shubheksha** [comment]
@Bradamant3, @tengqm - has this been fixed in PR #6427? Can this be closed?

**Comment by tengqm** [comment]
@shubheksha Thanks for remindering. Let's close it for now. It looks to me #6427 has solved this issue.

/close
