### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/ (cgroups: systemd vs cgroupfs)

### ISSUE THREAD

**Issue by MOZGIII** [kubernetes/website#6373]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Followed this guide, had issues with cgroups.
Apparently, `systemd` does not work *now*, and you have to use `cgroupfs` (on ubuntu).
The guide proposes to use `systemd`. Better solution is to explain how to choose one and then to configure both docker and kubelet/kubeadm. At least, how to configure them - this is the tricky part.

**Proposed Solution:**

I've captured some snippets for myself on how to deal with this, for later. Here: https://gist.github.com/MOZGIII/22bf4eb811ff5d4e0bbe36444422b6d3
This information could be added to this guide.

Pros: 
- will significantly reduce frustration for new users (since the guide will just work again);
- don't need to wait for some exterenal party to update something to apply the fix;
- just improves the existing docs.

Cons:
- more stuff to keep an eye on.

I'd say it's worth it, since it will also reduce the flow of issue reporots on this topic. and therefor should counter the "keeping an eye on" efforts.

**Page to Update:**
http://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by stewart-yu** [comment]
I have committed PR about it, [https://github.com/kubernetes/website/pull/6309](https://github.com/kubernetes/website/pull/6309), but in `troubeShooting` parts.

**Comment by MOZGIII** [comment]
Your PR is not about this. This proposal is to provide info in how one could actually configure cgroups, and not on how to deetect the issues with them. But your's useful too.
