### ISSUE TITLE
Issue with k8s.io/docs/tasks/federation/set-up-cluster-federation-kubefed/

### ISSUE THREAD

**Issue by Blasterdick** [kubernetes/website#6377]
For GKE kubernetes cluster it won't let you join the cluster if you don't create a `clusterrolebinfing` for your currently active `gcloud` account email (`gcloud auth list`) in a next manner:

```
kubectl create clusterrolebinding <your_user>-cluster-admin-binding --clusterrole=cluster-admin --user=<your_user>@example.org --context=<joining_cluster_context>
```
Please, add this in the docs.

**Comment by stewart-yu** [comment]
I can help to fix it
