### ISSUE TITLE
reconstruct Service docs

### ISSUE THREAD

**Issue by stewart-yu** [kubernetes/website#6396]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report
- [x] Fix Docs

**Problem:**
Section `Virtual IPs and service proxies` in https://kubernetes.io/docs/concepts/services-networking/service/  are redundancy, many sentence are the same. I think we need make it simplicity.
If need, i will do this.
@tengqm @lavalamp @steveperry-53 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...
[ https://kubernetes.io/docs/concepts/services-networking/service/]( https://kubernetes.io/docs/concepts/services-networking/service/)

**Comment by jaredbhatti** [comment]
https://github.com/kubernetes/website/pull/5869

Already fixed.
