### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose-interactive/

### ISSUE THREAD

**Issue by awsdevopro** [kubernetes/website#6398]
Hi there, I have been creating the curl command at Interactive Tutorial - Exposing Your App, but the last command curl host01:$NODE_PORT then I have found an error: 

curl: (6) Could not resolve host: host01
Here is the printscr for your review. 
https://prnt.sc/hd8p1n
 Why it does happen?

**Comment by BenHall** [comment]
Host01 is the name of the machine running Minikube. When running the tutorial locally, you may have a different name, in the case of this I expect it would be localhost. 

We're investigating improving this to make it clearer for users where host01 comes from.

**Comment by BenHall** [comment]
We've made improvements to how the environment is configured which hopefully will have improved this for other users.

/close
