### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by joeyjoeyjoeyjoey** [kubernetes/website#6405]
**This is a...** 
Bug Report

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
At the and of the Interactive Tutorial - Creating a Cluster the Summary button returns the following error 
he webpage at https://docs.google.com/forms/d/e/1FAIpQLScMbLRAbaZ8NleOFYRrepdIwCbhClHK3abu3SgzMn1KT_H5iA/viewform?entry.434419381=Module%201 might be temporarily down or it may have moved permanently to a new web address.

**Proposed Solution:**
unknown

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by BenHall** [comment]
Thank you for reporting this. We're keeping an eye on forms and it's uptime.
