### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateless-application/hello-minikube/ (Cannot start Minikube)

### ISSUE THREAD

**Issue by johnpaulada** [kubernetes/website#6419]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I encounter this error when running the `minikube start --vm-driver=xhyve` step on the **Hello Minikube** tutorial: 
> Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1

**Proposed Solution:**
The solution by @KIVagant from a [docker-machine-driver-xhyve issue](https://github.com/zchee/docker-machine-driver-xhyve/issues/156) worked for me:
```
rm -rf ~/.minikube
sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
```

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/

**Comment by heckj** [comment]
resolved with #6464
