### ISSUE TITLE
YAML file referenced in ZooKeeper tutorial is not valid YAML

### ISSUE THREAD

**Issue by ChrisChinchilla** [kubernetes/website#6433]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

This tutorial https://kubernetes.io//docs/tutorials/stateful-application/zookeeper/ references a YAML file in the 

```shell
kubectl apply -f https://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml
```

command, and the YAML file is not valid YAML, but is in fact an HTML file with YAML inside the body.

**Page to Update:**
https://kubernetes.io//docs/tutorials/stateful-application/zookeeper

**Comment by jaredbhatti** [comment]
to do:

In the command:
kubectl apply -f https://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml

Change 
https://k8s.io/docs/tutorials/stateful-application/zookeeper.yaml

to 
https://raw.githubusercontent.com/kubernetes/website/master/docs/tutorials/stateful-application/zookeeper.yaml

**Comment by stewart-yu** [comment]
I wiil help fix it

**Comment by jaredbhatti** [comment]
Fixed: https://github.com/kubernetes/website/pull/6435
