### ISSUE TITLE
New fields in Pod Security Policy not documented

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#6447]
Ref kubernetes/kubernetes#53179, flexvolumes can be specified in PSP.
This is not documented.

**Comment by wanghaoran1988** [comment]
/assign
Will prepare a PR after https://github.com/kubernetes/website/pull/6378

**Comment by php-coder** [comment]
@wanghaoran1988 ping :)

**Comment by wanghaoran1988** [comment]
release 1.9 branch pr : https://github.com/kubernetes/website/pull/6563
master branch pr: https://github.com/kubernetes/website/pull/6562/
@php-coder PTAL

**Comment by php-coder** [comment]
Could it be closed or there is still something left?
