### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/debug-init-containers/

### ISSUE THREAD

**Issue by lohithlnt** [kubernetes/website#6453]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
crashloopbackoff kubernetes pod

**Proposed  #Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
@lohithlnt Looks like a issue report by accident. Please reopen and provide more details if you do have an documentation issue to file.
