### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by cbuhot** [kubernetes/website#6457]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**

here is the message i receive when trying to install Kubeadm : 
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2a00:1450:4007:816::200e: Le réseau n'est pas accessible"
It appears that in order to install KUEADM, IPV6 is mandatory is there a mean to overide this and install Kubeadm with only IPV4 available ?

I've tested the access to the repository with a machine witch has access to IPV6, and the repo access is ok.

**Proposed Solution:**

open access to the repo with IPV4 as well as IPV6.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
@cbuhot Can you more specific which page needs an update? Or this is meant to be a bug report to kubernetes/kubernetes?

**Comment by cbuhot** [comment]
hi,
my point is that in the installation howto page we are asked to add the following section to the yum repos : 
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
...
when starting to install using yum, it fetch xml files at the base URL. but at this time, it appears that this base url is only reachable via IPV6 from the host being installed.
In my case, the machines i'm trying to install are only IPV4 configured because the network i use is only IPV4. This leads to impossibility to install kubeadm (at least).
As i don't think this limitation is intended, i posted this bug report.

**Comment by tengqm** [comment]
tried direct curl:

$ curl -v https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml
*   Trying 216.58.197.46...
*   Trying 2404:6800:4003:c00::8b...
* Immediate connect fail for 2404:6800:4003:c00::8b: Network is unreachable
* Connected to packages.cloud.google.com (216.58.197.46) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs

It seems working for me. Could be some DNS configuration problem in your environment.

**Comment by cbuhot** [comment]
Thank you for your help.
I'll dig the problem on my side.
