### ISSUE TITLE
why? Running Java is bad

### ISSUE THREAD

**Issue by haqiaolong** [kubernetes/website#6468]
Hello, my application is a Java, only to set up a cpuset performance, if not is to set the default host auditing, this will frequently switch CPU, lead to low performance, do you have any good solution?

**Comment by tengqm** [comment]
Closing this for not being a doc issue.
p.s.
If you want CPU binding, you may want to give CPUManager a try. 
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/
