### ISSUE TITLE
eadiness probe failed: HTTP probe failed with statuscode: 500 Liveness probe failed: HTTP probe failed with statuscode: 500

### ISSUE THREAD

**Issue by vamsi248** [kubernetes/website#6480]
i am getting these error when i am crearting my nginx-ingress-controller in my DEV and TEST environments....

i am getting ERROR
it seems cluster is running authorization enabled (like RBAC) no permissions for the ingress-controller please check the configuration..
so after that i created clusterrolebinding in cluster as serviceaccount:default
and rolebinding in my dev and test environments..
after creating rolebinding in my dev environment here is the pod description
i described my pod its showing

R  @heckj   @aleksandra-malinowska   @zacharysarah   can u please help me.. where is wrong in my process....
 probe failed: HTTP probe failed with statuscode: 500
Liveness probe failed: HTTP probe failed with statuscode: 500

and my logs are

:55:13.230951 7 reflector.go:205] k8s.io/ingress/core/pkg/ingress/controller/listers.go:50: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:dev:default" cannot list nodes at the cluster scope
E1129 02:55:13.232122 7 reflector.go:205] k8s.io/ingress/core/pkg/ingress/controller/listers.go:47: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:dev:default" cannot list ingresses.extensions at the cluster scope
E1129 02:55:13.233258 7 reflector.go:205] k8s.io/ingress/core/pkg/ingress/controller/listers.go:52: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:dev:default" cannot list configmaps at the cluster scope
E1129 02:55:13.234269 7 reflector.go:205] k8s.io/ingress/core/pkg/ingress/controller/listers.go:51: Failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:dev:default" cannot list secrets at the cluster scope
E1129 02:55:13.235441 7 reflector.go:205] k8s.io/ingress/core/pkg/ingress/controller/listers.go:48: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:dev:default" cannot list endpoints at the cluster scope
I1129 02:55:13.439991 7 main.go:47] Received SIGTERM, shutting down
I1129 02:55:13.440047 7 controller.go:1192] shutting down controller queues
I1129 02:55:13.440076 7 nginx.go:237] stopping NGINX process...
I1129 02:55:13.440845 7 shared_informer.go:112] stop requested
E1129 02:55:13.440947 7 listers.go:63] Timed out waiting for caches to sync
2017/11/29 02:55:13 [notice] 22#22: signal process started
I1129 02:55:16.225835 7 main.go:36] shutting down Ingress controller...
I1129 02:55:16.225866 7 main.go:38] Handled quit, awaiting pod deletion
I1129 02:55:16.464908 7 nginx.go:248] NGINX process has stopped
I1129 02:55:16.464943 7 main.go:55] Exiting with 0.....

**Comment by aleksandra-malinowska** [comment]
I have no way to debug your application. You can read more about how liveness and readiness probes work here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

In particular:
```Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.```

Basically, if a probe gets a 500 and restarts your application, it's WAI.

Additionally, this is unrelated to this repository. Please close it.

cc @tengqm
