### ISSUE TITLE
Missing link in task 'Upgrade from PetSets to StatefulSets'

### ISSUE THREAD

**Issue by surajssd** [kubernetes/website#6484]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

There is a link missing that was supposed to be added in section **Differences between alpha PetSets and beta StatefulSets** under it in the second point *StatefulSet guards against split brain* which ends with following text

>TODO: Link to doc about fencing.

Change it and add the link that is required.

**Proposed Solution:**

Add link which is missing

**Page to Update:**

https://kubernetes.io/docs/tasks/run-application/upgrade-pet-set-to-stateful-set/

**Comment by tengqm** [comment]
PetSet has long been replaced by StatefuSet and StatefulSet has been GA'ed in 1.9. So we are going to remove this page to avoid further confusion.
