### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

### ISSUE THREAD

**Issue by jdmarshall** [kubernetes/website#6503]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Insufficient documentation for minikube

> Note: If you are using Minikube, you don’t get an external IP address. The external IP address remains in the pending state.

Since the rest of the document expects this value to be passed as a parameter, and there is no advice or guidance given regarding Minikube, the user is essentially stuck at this point.

**Proposed Solution:**
What IP address do you use for connecting?

**Page to Update:**
http://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/

**Comment by zacharysarah** [comment]
@Bradamant3 👋 Still interested in updating the minikube tutorial?

/assign @Bradamant3

**Comment by jdmarshall** [comment]
After a deeper read of this document, the information is available farther down on the page. I think the main improvement needs to be an aside of some sort pointing the user to the bottom of the doc.
