### ISSUE TITLE
PVCProtection feature not documented

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#6506]
**This is a...** 
[x ] Feature Request

**Problem:**

design doc:  https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/postpone-pvc-deletion-if-used-in-a-pod.md
implementation: kubernetes/kubernetes#55824

**Proposed Solution:**
Add the following documentation to encourage people to try it.
- admission control
- behavior change

**Page to Update:**
http://kubernetes.io/docs/concepts/storage/persistent-volumes

Kubernetes v1.9

**Comment by aburdenthehand** [comment]
I'm still new to these parts but I think this was covered in #6415

**Comment by tengqm** [comment]
@aburdenthehand thanks, this in fact can be closed now.
