### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/aws/

### ISSUE THREAD

**Issue by JensRantil** [kubernetes/website#6512]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
AWS released https://aws.amazon.com/eks/ yesterday, but it's not listed on k8s.io/docs/getting-started-guides/aws/.

**Proposed Solution:**
I propose we mention the service under k8s.io/docs/getting-started-guides/aws/.

**Page to Update:**
k8s.io/docs/getting-started-guides/aws/

**Comment by zacharysarah** [comment]
@JensRantil :wave: Check out [kubeadm](https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/) for help getting started. If `kubeadm` doesn't adequately address EKS, please feel free to re-open this issue, as well as submit a PR against it.
