### ISSUE TITLE
Re-name Master Components to a more inclusive synonym

### ISSUE THREAD

**Issue by jbpivotal** [kubernetes/website#6525]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The term `Master` in `Master Components` is potentially offensive to people of color and women, and I suggest we use a more inclusive synonym.

**Proposed Solution:**
Suggest renaming to "Primary Components" or "Leader Components"

From [cmu.edu](https://www.cs.cmu.edu/~mjw/Language/NonSexist/vuw.non-sexist-language-guidelines.txt):
```
The word "master", like "mistress", originally meant one
exerting control, as over a household.  "Mistress" is now more
commonly used to mean lover and sometimes teacher.  Master
is now used in a variety of ways, but still largely with the
sense of power and control and, implicitly, maleness.
```

From [django](https://github.com/django/django/pull/2692):
`replaced occurrences of master/slave terminology with leader/follower`

From [drupal.org](https://www.drupal.org/project/drupal/issues/2275877):
`Replace "master/slave" terminology with "primary/replica"`

**Page to Update:**
http://kubernetes.io/docs/concepts/overview/components/

**Comment by zacharysarah** [comment]
@jbpivotal 👋 Thanks for the proposal and the supporting documentation. I agree that it's a priority change.

/cc @sarahnovotny, @parispittman

**Comment by parispittman** [comment]
I will take this to the next Contribex meeting on Jan 31st at 530pm UTC. We will need to get this in front of the k-dev crowd as well. 

Agree with Zach, thanks for bringing this up @jbpivotal!

**Comment by ConnorDoyle** [comment]
Another historical point of reference: https://docs.google.com/document/d/1P8_4wdk29I6NoVTjbFkRl05-tfxV9PY4WLoRNvExupM/edit#heading=h.9g7fqjh6652v

Mesos originally had "masters and slaves" and transitioned to "masters and agents". So, "masters" was retained but the most offensive term (according to most who chimed in at the time) was removed.

**Comment by jbpivotal** [comment]
Glad to, @zacharysarah and @parispittman. Thanks for the support.

**Comment by idvoretskyi** [comment]
"Control Plane" is widely used as an alternative naming for "Master" in Kubernetes, so we may consider this naming option.

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-architecture-bugs

**Comment by bgrant0607** [comment]
I usually use "control plane".

Minion->node rename:
https://github.com/kubernetes/kubernetes/issues/1111

**Comment by bgrant0607** [comment]
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/architecture.md#cluster-control-plane-aka-master

**Comment by bgrant0607** [comment]
cc @kubernetes/steering-committee

**Comment by jbeda** [comment]
I like control plane a lot also.  But I think that this is going to be a long effort and I'd love to get more perspectives from around the project.  This came up in ContribX and the plan was to talk about it a bit in SIG-architecture.

**Comment by timothysc** [comment]
I'm not opposed to this, but someone needs to drive all the touchpoints to make this change which may be non-trivial.  Distributed systems literature is clearly the source here and it goes back 30+ years, not justifying it, but taxonomy refs do matter.  If we change it, it should match other literature.

**Comment by smarterclayton** [comment]
I'm generally ok with "control plane", master is too imprecise anyway.

**Comment by smarterclayton** [comment]
To tie this back to a general problem we have had - we don't have a single component that controls everything else, we don't have a single set of machines.  Instead we have "run levels" (an emerging way of describing that various core components depend on other core components being set first), and we need to separate out the things that are monolithic into individual pieces.

**Comment by jbeda** [comment]
The thinking coming out of SIG-architecture:

1. As @smarterclayton mentions, master isn't a great term from a technical point of view. It isn't a concept that really exists in the core system.  Moving to more accurate/descriptive language here will help people communicate more effectively.
2. It is worthwhile to move away from the term "master" but this will be a long process. Our primary goal initially is to "stop digging a hole" and make sure that going forward we use new language.
3. We can open issues and make this a "help wanted" type of thing as we create incentives over time to change the name.

Complicating this is that pretty much every github link has the word "master" in it so simply grepping the code base is somewhat difficult.

Also, the preferred replacement seems to be either "control plane" or a more specific aspect of the control plane as appropriate (API server, etcd, etc).  But that term isn't final. We want to socialize this at the community meeting.

**Comment by tpepper** [comment]
The github links with "master" next to them can be greppable with some exclusion as they're preceded by "tree/", "blob/", "raw/", etc.  We should be able to define and share a solid regexp that trims out those git links for helper folks searching for areas to clean.

**Comment by bgrant0607** [comment]
Examples of more specific/precise things we will need terms for:
* cluster control plane
* nucleus apiserver
* dedicated infrastructure nodes

**Comment by jfoy** [comment]
In our environment we refer to members of the control plane as Controllers and other nodes as Workers. "Controller" is an overloaded term here, so probably not ideal to adopt more widely, but Coordinators, Centers, or Orchestrators might work.

**Comment by omkensey** [comment]
I don't like "leader" only because (and this may be just my skew on it) to me that implies a node elected by a pool of nodes to do something, as in etcd.

"Control plane" seems a little unwieldy to me, as do the various polysyllabic terms like "coordinator".

I like "controller" best since that's a term people already recognize and is used for an analogous machine role in e.g. Active Directory.  Yes, it's slightly overloaded in this project, but context would help a lot.  I'm hard-pressed to come up with a situation where "controller" is a) ambiguous b) in a context where it matters that c) isn't easily fixed with minor rewording.

**Comment by danderson** [comment]
For reference, in the GKE world (hi! GKE SRE here), we use "masters" and "control plane" fairly interchangeably. For the individual components of the control plane, we just call them by their name (apiserver, controller manager, scheduler...), or collectively "control plane pods."

"Controller" would be nice as a shorter thing to say, but it's already heavily overloaded, and my personal experience at Google (where overloading terms is basically a sport at this point), if a term is too overloaded, people don't use it, or qualify it to the point where it's as/more verbose as "control plane."

Tongue in cheek: take a page from Starcraft, and call it the Overmind. A hive intelligence is not _too_ stretched an analogy for k8s.

**Comment by jfoy** [comment]
Oh, I like the idea of calling dedicated control-plane components Queens.

**Comment by erriapo** [comment]
May I suggest using "Supervisor components". IMHO **Supervisor** is a great stand-in for **Master**.

**Comment by markyjackson-taulia** [comment]
I applaud this so very much!!!

**Comment by markyjackson-taulia** [comment]
I vote cluster control plane

**Comment by bgrant0607** [comment]
A couple quick comments (sorry):

1. Controller already has a use in the system. Reusing would be very confusing.
2. While I sympathize with the desire for conciseness, Supervisor is equally imprecise as master.

**Comment by swade1987** [comment]
I think `Control Plane` makes sense to me.

**Comment by roldancer** [comment]
"Control Plane" is a widely adopted term ...

**Comment by ShahNawazKhan** [comment]
Control plane is a term used in Software Defined Networking with "Controller" name used for module/s that manage the data plane. In the NFV domain, "Orchestrator" is the name used for the kind of things the K8S master does. Considering that k8s already uses "controllers", adopting the terms of control plane and even orchestrator will align it with the terminologies used elsewhere.

**Comment by mark-chilvers** [comment]
"wheelhouse components"

**Comment by dzolnierz** [comment]
You should rename a "master" branch as well.

**Comment by davidopp** [comment]
IME people use "control plane" to refer to some components that are not generally considered part of the "master" e.g. kubelet and kube-proxy. So I don't think it's a good substitute for "master."

**Comment by tizbac** [comment]
Seriously as with other instances of that problem, for me it looks completely retarded and ridicolous
Whoever is offended by terms that have been used in IT for over 30 years, has to rethink it, master and slave are the correct term if one part of the software or hardware is completely controlled by another part of the software or hardware.

**Comment by swade1987** [comment]
@tizbac can I advise you don't use words like "retarded" in a public forum.

**Comment by Flukas88** [comment]
I'd use "ill advised" then

**Comment by MonsieurCellophane** [comment]
Really. This richly deserves a "not a technical requirement/NOTABUG/WONTFIX" I cant envision a single man/hour wasted on this useless drivel.

**Comment by esolitos** [comment]
No please, not again.
Please don't waste the time fo N+1 people into a non real issue.
I'd really really go an poll the majority of people working in CS/IT asking if _ANYONE_ has _EVER_ felt discriminated by the naming master/slave. My speculation is that the % of "offended" people would be less than 1%.

This term is _NOT_ related whatsoever from the "master race" concept or the "slave trade", as pointed out by others the master/slave nomenclature has been used in IT for _decades_ to indicate that a specific part of a system id dependant on another part, if you see in any way a connection on the white masters and `$skin-color` slaves, I have a bad news for you: you are the racist, because you imply that this master/slave concept applies to humans. The fact that someone believed it in the past, doesn't make it real, and it's not changing the present that you erase the mistakes of the past.

Calling *ware components master/slave has never made anyone racist. Ever.

Sorry for this small rant, but I've seen far to many projects wasting time on this _non issue_ in the past, creating long/eternal threads just to settle a damn nomenclature issue which no one was offended in the first place.

PS: The fact that this issue is raised and discussed purely by white caucasian men should make you think a little...

**Comment by taifu** [comment]
I can't believe this. Really. I can't. This is ridiculous

**Comment by teknoraver** [comment]
Am I the only one finding this ridiculous?

**Comment by brendandburns** [comment]
Before this discussion goes too much further, I'd like to remind everyone that this (and all kubernetes community forums) are covered by the CNCF code of conduct:

https://github.com/<https://github.com/cncf/foundation/blob/master/code-of-conduct.md>cncf<https://github.com/cncf/foundation/blob/master/code-of-conduct.md>/foundation/blob/master/code-of-conduct.md<https://github.com/cncf/foundation/blob/master/code-of-conduct.md>

I expect everyone to keep this discussion respectful and professional.

Thank you in advance for respecting our community and _all_ of its members.

--brendan

________________________________

**Comment by taifu** [comment]
Is it possible to express contrariety seeing so much time and word wasted for such a worthless problem? Master and server are two technical words and nobody, really, nobody with a grain of salt could seriously regard this as a real problem

**Comment by bgrant0607** [comment]
This conversation is no longer constructive and respectful. I am closing this issue.  

We have already started to move towards more specific terms for technical reasons. That terminology will be discussed further in SIG Architecture.
