### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/ - Define term "pod"

### ISSUE THREAD

**Issue by axman6** [kubernetes/website#6528]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The term pod is introduced without explanation in module 2, step 3 - topics covered so far include the master, nodes, apps, containers and deployments.

**Proposed Solution:**
Define _Pod_ before it is used:

> Pods that are running inside Kubernetes are running on a private, isolated network. By default they are visible from other pods and services within the same kubernetes cluster, but not outside that network.

this is the first instance where the term pod has been used.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/ (Module 2, step 3)

**Comment by BenHall** [comment]
Thank you for the feedback. This is a great idea. We'll look at how we can do this.
