### ISSUE TITLE
Make ConfigMaps Usable in Compact key: value Assignments

### ISSUE THREAD

**Issue by Hardy2015** [kubernetes/website#6529]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

ConfigMaps are a very cool feature. I'm using it to decouple key/value pairs like 
```
      - env:
        - name: jaas_owner
          value: D023081
```
by replacing ```value``` by 
```  
     valueFrom:
            configMapKeyRef:.....
```

However, I would also like to replace other attributes in my rc.yaml, that come more compact, like: 
```
        resources:
          limits:
            cpu: "4"
            memory: 30Gi
          requests:
            cpu: 500m
            memory: 7Gi
``` 

After reading the documentation, I didn't find a way to decouple the "4" in ```cpu``` through a ConfigMap. 

**Proposed Solution:**

Please make ConfigMaps also availabe to the compact ```key: value``` syntax like ```cpu: "4"```

**Comment by tengqm** [comment]
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Comment by Hardy2015** [comment]
Hi, 

thank you, but I fear, this was a misunderstanding. I don't want to EXPOSE pod information in environment variables. I want to SET pod information by referring to a ConfigMap, where it is specified. 
So the config map CM would state ```resourceLimitCpu="4"``` and pods of all replication controllers, that refer to CM, would have this 
```
resources: 
    limits:
      cpu: "value from CM"
```
setting. This would allow me to set limits to whole classes of similar applications.
I just don't see a possibility to refer on the right side of "cpu: value" to a config map. 

Best regards,
Hartmut

**Comment by tengqm** [comment]
Use PodPreset then

**Comment by tengqm** [comment]
em, PodPreset cannot set resource requirements ... Maybe LimitRange is what you want?

**Comment by Hardy2015** [comment]
Thank you very much. Yes, LimitRange goes into the right direction. However in my given namespace, there are 400 RCs of smaller size and 250 RCs of larger size. Technically, they are the same thing, which is why they live in the same namespace. Apparently, LimitRange only allows me to restrict all namespace inhabitants at the same time.  I tried to distinguish the both through
```
spec:
  selector:
    matchLabels:
      imageType: basic
```
But this seems to be not allowed here: 
```
error: error validating "basic-limit-range": error validating data: found invalid field selector for v1.LimitRangeSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
Am I overlooking something, where I could configure the both specifically?

**Comment by tengqm** [comment]
I see. Apparently LimitRange doesn't have selector support: https://kubernetes.io/docs/api-reference/v1.8/#limitrangespec-v1-core 
Maybe you want to file an issue in kubernetes (https://github.com/kubernetes/kubernetes )? This is the documentation project. I closed the issue because it is not a documentation problem.
