### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by ItsPugle** [kubernetes/website#6544]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Module 2 description shows that the client and server version is V1.5, yet the terminal outputs V1.8.0 for client and V1.5.2 for the server.

**Proposed Solution:**
I don't know? Maybe having the site fetch the most recent version (I don't know - I'm not a confident developer, hence the tutorial).

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

![screenshot 2017-12-04 at 11 22 50 am](https://user-images.githubusercontent.com/22669894/33532539-441d242c-d8e6-11e7-8014-9164388bcc99.png)

**Comment by BenHall** [comment]
Thank you for letting us know. We thought we had removed all the version information. We'll get this updated ASAP.

**Comment by ItsPugle** [comment]
Cheers! I'll leave you to close them once you've done that :)

**Comment by tengqm** [comment]
@BenHall ping. This is still an issue.

**Comment by BenHall** [comment]
Thanks for the feedback. This has been fixed as part of #7240
