### ISSUE TITLE
(Minor) issue with k8s.io/docs/reference/generated/kube-apiserver/ : --v not documented

### ISSUE THREAD

**Issue by aknrdureegaesr** [kubernetes/website#6571]
**This is a...** 

- [X] Bug Report

**Problem:**

The `--v` command line switch is used by `kube-apiserver.manifest` as generated by Kops and apparently understood by the API server. So it seems to exist. But it is not documented.

**Proposed Solution:**

Document it.

Particularly beneficial/interesting (but feel free to leave these out for MVP fix of this issue):

* What is the maximal value?
* Which details to expect at which value?
* Is there any range of values that might cause secrets or other sensitive data to be leaked into the API server's stdout / stderr?

**Page to Update:**

https://kubernetes.io/docs/reference/generated/kube-apiserver/

Kubernetes Version: 1.7.10

**Comment by tengqm** [comment]
@aknrdureegaesr Can you report an issue to kubernetes/kubernetes project? The reference docs are generated from the source code directly and then copied here. So ... this issue is not a website one.

**Comment by aknrdureegaesr** [comment]
Done as https://github.com/kubernetes/kubernetes/issues/57098 .

Unsure: Is that enough, so we close this one, or shall we keep this one open?

**Comment by zacharysarah** [comment]
@aknrdureegaesr Close. ;-)
