### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore-intro/

### ISSUE THREAD

**Issue by randyrue** [kubernetes/website#6605]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
"Start Interactive Tutorial" Link (https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-interactive/) returns a 404

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thank you for the bug report. Could you take another look at let us know if this happens again?

**Comment by tengqm** [comment]
Sounds like a temporary issue which cannot be reproduced (already has been fixed?).
Closing.
