### ISSUE TITLE
kube-registry-proxy.yaml’: No such file or directory

### ISSUE THREAD

**Issue by cts1975** [kubernetes/website#6612]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Following the guide does not work as the provided script looks for a salt directory which is not there!

cp: cannot stat ‘./cluster/saltbase/salt/kube-registry-proxy/kube-registry-proxy.yaml’: No such file or directory

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

Please revise your page and allow this to work locally on hosts running libvirt to test and learn Kubernetes.

**Comment by stewart-yu** [comment]
can you provide `Page to Update`?

**Comment by cts1975** [comment]
Apologies @stewart-yu, I was following this guide: https://kubernetes.io/docs/getting-started-guides/libvirt-coreos/ and I have tried both the automatic and the manual approach.

Hopefully this will help,

Charles

**Comment by stewart-yu** [comment]
I think you are run `command` in wrong directory, you must in `/kubernetes` directory .

**Comment by cts1975** [comment]
@stewart-yu I'm pretty sure it's not because of the above. I can confirm I am running the command from the kubernetes directory like it says in the guide ./cluster/kube-up.sh

here is the output of the error, it's clear it's looking for a salt directory and a yaml file for the registry-proxy... 
```
Starting cluster using provider: libvirt-coreos
... calling verify-prereqs
... calling verify-kube-binaries
... calling kube-up
KUBE_MASTER_IP: 192.168.10.1
KUBE_MASTER: kubernetes-master
--2017-12-07 18:37:40--  https://alpha.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2
Resolving alpha.release.core-os.net (alpha.release.core-os.net)... 104.16.20.26, 104.16.21.26, 2400:cb00:2048:1::6810:141a, ...
Connecting to alpha.release.core-os.net (alpha.release.core-os.net)|104.16.20.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 362677311 (346M) [application/octet-stream]
Server file no newer than local file ‘./cluster/../cluster/../cluster/libvirt-coreos/coreos_production_qemu_image.img.bz2’ -- not retrieving.

Pool kubernetes refreshed

TLS assets generated...
cp: cannot stat ‘./cluster/saltbase/salt/kube-registry-proxy/kube-registry-proxy.yaml’: No such file or directoryrly looking for a salt directory and a yaml file for the registry-proxy
```

Hope this helps, thanks again for any help.

Charles

**Comment by cts1975** [comment]
quick update, I've just checked the github repo and can see that it has the saltbase directory in there. I'm going to clone from github and try using the latest git pull. I'll update and let you know if this works. Thanks

**Comment by cts1975** [comment]
I copied the saltbase folder from the git pull into the vagrant folder that is created using the script and this did indeed kick on the installation and work. Unfortunately I had some issues with networking that I need time to resolve but I'm confident this can be fixed now.

**Comment by cts1975** [comment]
I still can't get this to work.. It gets to the point where it's created the pool, networks, master and minions but just sits on wait for cluster readiness. I can ping the gateway of both the kubernetes networks it creates but I can ping the nodes. Not sure if this is some some of NAT or network issue. I've tried to look through the config but nothing is jumping out at me. If any one has any ideas then please let me know. Thanks.

**Comment by stewart-yu** [comment]
sorry, forgot it

**Comment by stewart-yu** [comment]
update: it seem `libvirt-coreos` will set up by `kubernetes-anywhere`, `/cluster/libvirt-coreos/` directory in kubernetes repo has been removed, more details can refer to [here](https://github.com/kubernetes/kubernetes/issues/49213). so i think this issuses doesn't matter now.

**Comment by tengqm** [comment]
This no longer sounds like an issue. Please reopen if anyone wants to keep it.
