### ISSUE TITLE
Issue with k8s.io/docs/tasks/inject-data-application/define-command-argument-container/

### ISSUE THREAD

**Issue by quantum-fusion** [kubernetes/website#6615]
**This is a...** 

- [ x] Feature Request
- [ ] Bug Report

**Problem:**

The problem is that the arguments being passed into a POD do not work like Docker. 

https://stackoverflow.com/questions/47697169/how-does-argument-passing-in-kubernetes-work

https://groups.google.com/forum/#!topic/kubernetes-users/XzfuAsiVXLk

A problem:

Docker arguments will pass from command line:

docker run -it -p 8080:8080 joethecoder2/spring-boot-web -Dcassandra_ip=127.0.0.1 -Dcassandra_port=9042

However, Kubernetes POD arguments will not pass from singlePod.yaml file, when I do:
kubectl create -f ./singlePod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-web-demo
  labels:
    purpose: demonstrate-spring-boot-web
spec:
  containers:
  - name: spring-boot-web
    image: docker.io/joethecoder2/spring-boot-web
    env: ["name": "-Dcassandra_ip", "value": "127.0.0.1"]
    command: ["java","-jar", "spring-boot-web-0.0.1-SNAPSHOT.jar", "-D","cassandra_ip=127.0.0.1", "-D","cassandra_port=9042"]
    args: ["-Dcassandra_ip=127.0.0.1", "-Dcassandra_port=9042"]
  restartPolicy: OnFailure

**Proposed Solution:**

Need additional examples of the POD specification, with an example on how to pass arguments to Kubernetes Pods that are defined, and tested.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
So ... this can be closed as well? @quantum-fusion

**Comment by quantum-fusion** [comment]
What you can do is update your documentation to include this example configuration yaml file:
https://github.com/quantum-fusion/springboot_swagger_example-master-cassandra/blob/master/Kubernetes/setupRemotePod.yaml

**Comment by quantum-fusion** [comment]
Note: that google states that Pods are not configurable, and do not allow dynamic configurations of templates for Pods.
