### ISSUE TITLE
Update Flex volume docs to represent it is GA

### ISSUE THREAD

**Issue by chakri-nelluri** [kubernetes/website#6641]
- [ ] Feature Request
- [x] Bug Report

/kind bug

Flex volume docs still stay the feature is Alpha. We made it GA in Kube 1.8 time frame. We have to update the docs to reflect it.

/sig storage

https://kubernetes.io/docs/concepts/storage/volumes/
https://github.com/kubernetes/community/blob/master/contributors/devel/flexvolume.md

Kubernetes version: 1.9 or master

**Comment by chakri-nelluri** [comment]
@saad-ali @shay-berman Create new docs issue

**Comment by tengqm** [comment]
Fixed in #6666
