### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/disruptions/

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#6664]
I think I found a problem with Pod Disruption Budget's [example section](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pdb-example).

It still lists `pod-b` as available even though it's evicted (or _terminating_?).

/assign @erictune 
Can you please take a look?

> ![image](https://user-images.githubusercontent.com/159209/33903561-9c04b4be-df2d-11e7-8930-d95d955d0c85.png)

https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pdb-example

**Comment by erictune** [comment]
Yes, that looks like an error.
