### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

### ISSUE THREAD

**Issue by BastienL** [kubernetes/website#6682]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

The guide for `flannel` as a pod network recommends to apply `https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml`. However, the spec for the `kube-flannel` container in the DaemonSet do not set resources requests and limits. As a result, the `kube-flannel-ds` pods will have a QoS class of BestEffort. 

This can dangerous on low-cpu or low-ram nodes, as that would allow kubelet to remove that pod if there's too much pressure on the resources of the node. Without a `kube-flannel-ds` pod running on a node, all the pods on that node become unreachable.

**Proposed Solution:**

Set requests and limits resources on the `kube-flannel` container, like on https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L127-L133.

With this change, the `kube-flannel-ds` pod gets a QoS class of Guaranteed, preventing it to be killed in the node runs out of resources.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

**Comment by tengqm** [comment]
@BastienL Have you filed an issue to flannel project? This doesn't sound like a k8s doc problem.

**Comment by BastienL** [comment]
@tengqm I think the k8s documentation should link to https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L127-L133 instead of https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml. Not sure it's a flannel issue then. But I'll let them know too.

**Comment by tengqm** [comment]
ya, I agree when possible we should use links that are general and stable
