### ISSUE TITLE
Issue with k8s.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

### ISSUE THREAD

**Issue by seivan** [kubernetes/website#6696]
- [x] Bug Report

**Problem:**
It seems like the [API-REF](https://v1-8.docs.kubernetes.io/docs/api-reference/v1.9) for `1.9` is not available, thus breaking a lot of links in the documentation. E.g at the bottom of https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Proposed Solution:**
Deploy the `API-REF` for `1.9` or downgrade the links to `1.8`

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

**Comment by zacharysarah** [comment]
@seivan 👋  The 1.9 references are available now.
