### ISSUE TITLE
Old-format links to API documentation do not redirect as expected

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#6704]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
URLs for Kubernetes' API documentation have changed to this format:
`https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/`

Old links look like this:
`https://kubernetes.io/docs/resources-reference/v1.8/#podspec-v1-core`

These old links do not redirect as expected. Instead, they redirect to `https://v1-8.docs.kubernetes.io/docs/reference/`.

This is a poor, unexpected user experience and is a breaking change for Kubernetes Engine documentation. Furthermore, anyone who has these old links (other websites, blogs, etc.) can't use them as expected, which creates the perception that the links are broken or the pages no longer exist.

I'm not sure if this issue needs to go through the API team or through the website, so I am filing here.

**Proposed Solution:**
Set up a redirect, or implement some other solution, to prevent sending users who use the old links to the wrong pages unexpectedly.

**Page to Update:**
http://kubernetes.io/docs/reference/*

**Comment by steveperry-53** [comment]
Need to update _redirects file.
