### ISSUE TITLE
kubectl patch docs don't mention json patch

### ISSUE THREAD

**Issue by nikhita** [kubernetes/website#6707]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/ does not mention how to use json patch. It only mentions strategic merge patch and json merge patch.

Note: The cheatsheet (https://kubernetes.io/docs/reference/kubectl/cheatsheet/) mentions the use of json patch. IMO if the cheatsheet mentions it, we should also include it in the explanation.

**Proposed Solution:**

If this request of adding more information about json patch makes sense, I am happy to send a PR for this.

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/

**Side Note**: Here is a 🌮 for whoever wrote the docs for strategic merge patch and json merge patch. The docs are really easy to understand! 😄

**Comment by dims** [comment]
@nikhita Go for it!

**Comment by zacharysarah** [comment]
@nikhita 👋 Please feel free to open a PR!
