### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by aries-zhang** [kubernetes/website#6710]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
```apt-get install kubeadm ...``` in this page does not work in China because of [GFW](https://en.wikipedia.org/wiki/Great_Firewall).

**Proposed Solution:**
Put all resources needed to spin up a kubernetes cluster to somewhere that GFW does not block, and this can make Chinese coder's life muuuuuuuch easier.

So far, apt's official source or its mirrors are not blocked in mainland China, so is it possible to distribute all binaries there? So Chinese coders have an option not to set up google's source.

So far, docker hub is not blocked in mainland China, so is it possible to upload all images to docker hub?

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
This is not a documentation issue. Please try raise a request in kubernetes/kubernetes and notify the sig-release team.
