### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by franck-roland** [kubernetes/website#6745]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Click on Start scenario button does not work. (linux)(Google chrome Version 62.0.3202.94 (Build officiel) (64 bits))

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by SirMcPotato** [comment]
Had the same issue, then I disabled my ad blocker and it worked perfectly.

**Comment by BenHall** [comment]
Thank you for letting us know. This was due to a JavaScript error as we expected our JS Tracker to load, but it was blocked via the adblocker.

This should now be resolved and the site work even with adblockers.
