### ISSUE TITLE
Adblocker causes problem with simulated tutorial

### ISSUE THREAD

**Issue by mgillis** [kubernetes/website#6751]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
'Start Scenario' fails when uBlock Origin is running in Google Chrome (63; osx).

**Proposed Solution:**
Add notice to page saying that adblockers may interfere with the operation of the page.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by BenHall** [comment]
Thank you for letting us know. This was due to a JavaScript error as we expected our JS Tracker to load, but it was blocked via the adblocker.

This should now be resolved and the site work even with adblockers. If you still experience a problem, then please do let us know!
