### ISSUE TITLE
Bridget (L2 networks and linux bridging driver)

### ISSUE THREAD

**Issue by kvaps** [kubernetes/website#6752]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Page to Update:**
https://kubernetes.io/docs/concepts/cluster-administration/networking/#l2-networks-and-linux-bridging

Hi, you wrote there
> If you use this technique and perfect the process, please let us know.

I tell. I was needed in simple solution for running pods in one flat L2-network. No routes and no politics, just dumb bridges and one L2-domain.
I have tried a lot of solutions for that, but not one worked as I expected.
As a result, I wrote my own networking driver for kubernetes.

I called it bridget:
https://github.com/kvaps/bridget

I would be glad if you mentioned it on this page.

Thanks!

**Comment by zacharysarah** [comment]
@thockin 👋 PTAL
