### ISSUE TITLE
Netlify deploy preview failing.

### ISSUE THREAD

**Issue by dungeonmaster18** [kubernetes/website#6758]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Netlify deploy previw fails. It's failing on master as well.

Error

```
Liquid Exception: persistent-volume is not a valid glossary term id. Please see ./_data/glossary/* for the complete list. in docs/reference/glossary.md
```

**Proposed Solution:**
Fix this as soon as possible high priority.

Cc @zacharysarah @steveperry-53 .

**Comment by tengqm** [comment]
Fixed.
