### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by joshbrand** [kubernetes/website#6772]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Text reads 
> OK, kubectl is installed and you can see both the client and the server versions: 1.5

but `kubectl version` output show 1.8/1.5:

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Proposed Solution:**
Update demo server version or text to reflect differences

**Page to Update:**
http://kubernetes.io/...

**Comment by BenHall** [comment]
Thank you, the text has been updated to reflect this and removed the information about the version.
