### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by intosomethin** [kubernetes/website#6782]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**

The following example command misses IMHO parenthesis and a parameter:
The echo command needs ' ' or \\ for the whitespace.
The parameter before "/bin/sh -c" is missing. There is just a "--".

$ kubectl run hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox -- /bin/sh -c \\
"date; echo Hello from the Kubernetes cluster"

**Proposed Solution:**

$ kubectl run hello --schedule="*/1 * * * *" --restart=OnFailure --image=busybox \\
--[missing-param] /bin/sh -c "date; echo 'Hello from the Kubernetes cluster'"

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by tengqm** [comment]
the result is the same no matter with or without the quote.
