### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose-interactive/

### ISSUE THREAD

**Issue by sivashankerN** [kubernetes/website#6789]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
kubectl get pods <--Option> run=keubernetes-bootcamp 

Confusion with "option/flag" in the above command. The option looks like 1 in the command.
When we type command manually on the provided terminal,  there is little confusion. But when we click on the command that you have provided on the left side panel it works fine.

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by zhangxiaoyu-zidif** [comment]
this is l, meaning label. The option will help select pod by label.

**Comment by zhangxiaoyu-zidif** [comment]
![image](https://user-images.githubusercontent.com/5154334/34430610-c65e8c68-eca1-11e7-9f9b-35aec1fcc936.png)
you can input `kubectl get pods kubernetes-bootcamp-390780338-st3vd -o yaml` to inspect all the details.

**Comment by sivashankerN** [comment]
Thanks @zhangxiaoyu-zidif
