### ISSUE TITLE
Issue with clusterip cannot communicate between node1 and node2

### ISSUE THREAD

**Issue by oule** [kubernetes/website#6790]
10.1.1.171 proxmox ve vm ----master and node1
10.1.1.172 proxmox ve vm ----node2
os:CentOS Linux release 7.3.1611
docker:1.12.6
kubernetes:1.5.2-0.7.git269f928
flannel:0.7.1-2
```shell
[root@master ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 62:64:62:37:63:66 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.171/24 brd 10.1.1.255 scope global eth0
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue state UP 
    link/ether 02:42:ab:4b:36:47 brd ff:ff:ff:ff:ff:ff
    inet 172.17.59.1/24 scope global docker0
       valid_lft forever preferred_lft forever
44: flannel0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1472 qdisc pfifo_fast state UNKNOWN qlen 500
    link/none 
    inet 172.17.59.0/16 scope global flannel0
       valid_lft forever preferred_lft forever
46: veth6e30dda@if45: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 42:e7:4b:95:58:1b brd ff:ff:ff:ff:ff:ff link-netnsid 0
48: vethf1821c4@if47: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether fa:b0:94:82:4a:79 brd ff:ff:ff:ff:ff:ff link-netnsid 1
```
```shell
[root@node2 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 32:38:64:33:39:64 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.172/24 brd 10.1.1.255 scope global eth0
       valid_lft forever preferred_lft forever
4: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue state UP 
    link/ether 02:42:87:58:b8:d0 brd ff:ff:ff:ff:ff:ff
    inet 172.17.102.1/24 scope global docker0
       valid_lft forever preferred_lft forever
106: flannel0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1472 qdisc pfifo_fast state UNKNOWN qlen 500
    link/none 
    inet 172.17.102.0/16 scope global flannel0
       valid_lft forever preferred_lft forever
108: vethfd63e44@if107: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 92:0c:d3:a9:cd:5a brd ff:ff:ff:ff:ff:ff link-netnsid 0
110: veth533ddc2@if109: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 3e:22:b3:e1:1b:48 brd ff:ff:ff:ff:ff:ff link-netnsid 1
112: veth54cafc3@if111: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 6a:2a:71:04:fb:78 brd ff:ff:ff:ff:ff:ff link-netnsid 2
114: vethe1802ce@if113: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 66:3c:ed:19:36:31 brd ff:ff:ff:ff:ff:ff link-netnsid 3
116: veth9dd315f@if115: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 22:f5:82:95:df:4d brd ff:ff:ff:ff:ff:ff link-netnsid 4
118: vethacbc90d@if117: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 32:62:3b:e5:f5:3e brd ff:ff:ff:ff:ff:ff link-netnsid 6
120: veth1331eda@if119: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1472 qdisc noqueue master docker0 state UP 
    link/ether 9a:b7:97:e9:ae:44 brd ff:ff:ff:ff:ff:ff link-netnsid 7

[root@master ~]# ip route
default via 10.1.1.254 dev eth0  proto static  metric 100 
10.1.1.0/24 dev eth0  proto kernel  scope link  src 10.1.1.171  metric 100 
172.17.0.0/16 dev flannel0 
172.17.0.0/16 dev flannel0  scope link  metric 5 
172.17.59.0/24 dev docker0  proto kernel  scope link  src 172.17.59.1

[root@node2 ~]# ip route 
default via 10.1.1.254 dev eth0  proto static  metric 100 
10.1.1.0/24 dev eth0  proto kernel  scope link  src 10.1.1.172  metric 100 
172.17.0.0/16 dev flannel0 
172.17.0.0/16 dev flannel0  scope link  metric 5 
172.17.102.0/24 dev docker0  proto kernel  scope link  src 172.17.102.1

[root@master ~]# kubectl get svc
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kubernetes   169.254.0.1      <none>        443/TCP   6d
nginx-rc     169.254.47.160   <none>        80/TCP    1d
[root@master ~]# kubectl get pods -o wide
NAME             READY     STATUS    RESTARTS   AGE       IP             NODE
nginx-rc-k759p   1/1       Running   6          1d        172.17.59.3    10.1.1.171
nginx-rc-zl3pn   1/1       Running   6          1d        172.17.102.3   10.1.1.172

[root@master ~]# curl 169.254.47.160
172.17.59.3    10.1.1.171
[root@master ~]# curl 169.254.47.160
172.17.59.3    10.1.1.171
[root@master ~]# curl 169.254.47.160
curl: (7) Failed connect to 169.254.47.160:80; Connection timed out

[root@node2 ~]# curl 169.254.47.160
172.17.102.3   10.1.1.172
[root@node2 ~]# curl 169.254.47.160
172.17.102.3   10.1.1.172
[root@node2 ~]# curl 169.254.47.160
curl: (7) Failed connect to 169.254.47.160:80; Connection timed out
```
question：
only access to self's pod ip is ok by clusterip
How to solve？
thanks！

**Comment by oule** [comment]
[root@master ~]# curl 172.17.102.3
172.17.102.3   10.1.1.172

[root@node1 ~]# curl 172.17.59.3
172.17.59.3    10.1.1.171

**Comment by oule** [comment]
[root@master ~]# curl 172.17.102.3
172.17.102.3 10.1.1.172

[root@node2 ~]# curl 172.17.59.3
172.17.59.3 10.1.1.171

**Comment by oule** [comment]
[root@master ~]# iptables -nvL
Chain INPUT (policy ACCEPT 39 packets, 6882 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  26M   17G KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   12   841 DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    7   367 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    6   315 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    5   474 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 37 packets, 6802 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  26M   21G KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  26M   21G KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER-ISOLATION (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   12   841 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain KUBE-FIREWALL (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-SERVICES (1 references)
 pkts bytes target     prot opt in     out     source               destination

**Comment by oule** [comment]
[root@node2 ~]# iptables -nvL
Chain INPUT (policy ACCEPT 1 packets, 92 bytes)
 pkts bytes target     prot opt in     out     source               destination         
2060K 1036M KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
29718   42M DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
16896   42M DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
16801   42M ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
12822  610K ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
   92  7050 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 1 packets, 92 bytes)
 pkts bytes target     prot opt in     out     source               destination         
2032K 2188M KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
2032K 2188M KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER-ISOLATION (1 references)
 pkts bytes target     prot opt in     out     source               destination         
29718   42M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain KUBE-FIREWALL (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000

Chain KUBE-SERVICES (1 references)
 pkts bytes target     prot opt in     out     source               destination

**Comment by oule** [comment]
[root@node2 ~]# iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 209K   20M KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
    2   104 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 201K   10M KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   70  4846 MASQUERADE  all  --  *      !docker0  172.17.102.0/24      0.0.0.0/0           
 207K   11M KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    1    52 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           

Chain KUBE-MARK-DROP (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x8000

Chain KUBE-MARK-MASQ (10 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x4000

Chain KUBE-NODEPORTS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kubernetes-dashboard: */ tcp dpt:32345
    0     0 KUBE-SVC-XGLOHA7QRQ3V22RZ  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kubernetes-dashboard: */ tcp dpt:32345

Chain KUBE-POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ mark match 0x4000/0x4000

Chain KUBE-SEP-25WBLIX7ISMTZJXQ (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       10.1.1.171           0.0.0.0/0            /* default/kubernetes:https */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: SET name: KUBE-SEP-25WBLIX7ISMTZJXQ side: source mask: 255.255.255.255 tcp to:10.1.1.171:6443

Chain KUBE-SEP-32UTAWJPHCDNBQRN (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.102.8         0.0.0.0/0            /* kube-system/kube-dns:dns-tcp */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kube-dns:dns-tcp */ tcp to:172.17.102.8:53

Chain KUBE-SEP-5BRX4XDOKXUGIDQN (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.102.5         0.0.0.0/0            /* kube-system/heapster: */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/heapster: */ tcp to:172.17.102.5:8082

Chain KUBE-SEP-6AWHDGGGFUCHEXV7 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.102.4         0.0.0.0/0            /* kube-system/kubernetes-dashboard: */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kubernetes-dashboard: */ tcp to:172.17.102.4:9090

Chain KUBE-SEP-IUANTHZC3XOZQHLT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.102.7         0.0.0.0/0            /* kube-system/monitoring-influxdb: */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/monitoring-influxdb: */ tcp to:172.17.102.7:8086

Chain KUBE-SEP-KTKMCOADR7TK35UY (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.102.3         0.0.0.0/0            /* default/nginx-rc: */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/nginx-rc: */ tcp to:172.17.102.3:80

Chain KUBE-SEP-L7FMAWCO2KPREIT2 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.59.3          0.0.0.0/0            /* default/nginx-rc: */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/nginx-rc: */ tcp to:172.17.59.3:80

Chain KUBE-SEP-UYKT3UFXQIZFYBEA (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.102.6         0.0.0.0/0            /* kube-system/monitoring-grafana: */
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/monitoring-grafana: */ tcp to:172.17.102.6:3000

Chain KUBE-SEP-X6ZKJV5GH7UMF5BF (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       172.17.102.8         0.0.0.0/0            /* kube-system/kube-dns:dns */
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kube-dns:dns */ udp to:172.17.102.8:53

Chain KUBE-SERVICES (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SVC-Q6XJQ2I55QTBQCWT  tcp  --  *      *       0.0.0.0/0            169.254.216.253      /* kube-system/monitoring-influxdb: cluster IP */ tcp dpt:8086
    0     0 KUBE-SVC-NPX46M4PTMTKRN6Y  tcp  --  *      *       0.0.0.0/0            169.254.0.1          /* default/kubernetes:https cluster IP */ tcp dpt:443
    0     0 KUBE-SVC-THOQCXWDZBULAUCX  tcp  --  *      *       0.0.0.0/0            169.254.47.160       /* default/nginx-rc: cluster IP */ tcp dpt:80
    0     0 KUBE-SVC-BJM46V3U5RZHCFRZ  tcp  --  *      *       0.0.0.0/0            169.254.210.124      /* kube-system/heapster: cluster IP */ tcp dpt:80
    0     0 KUBE-SVC-TCOU7JCQXEZGVUNU  udp  --  *      *       0.0.0.0/0            169.254.169.254      /* kube-system/kube-dns:dns cluster IP */ udp dpt:53
    0     0 KUBE-SVC-ERIFXISQEP7F7OF4  tcp  --  *      *       0.0.0.0/0            169.254.169.254      /* kube-system/kube-dns:dns-tcp cluster IP */ tcp dpt:53
    0     0 KUBE-SVC-XGLOHA7QRQ3V22RZ  tcp  --  *      *       0.0.0.0/0            169.254.99.127       /* kube-system/kubernetes-dashboard: cluster IP */ tcp dpt:80
    0     0 KUBE-SVC-JRXTEHDDTAFMSEAS  tcp  --  *      *       0.0.0.0/0            169.254.72.197       /* kube-system/monitoring-grafana: cluster IP */ tcp dpt:80
    0     0 KUBE-NODEPORTS  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service nodeports; NOTE: this must be the last rule in this chain */ ADDRTYPE match dst-type LOCAL

Chain KUBE-SVC-BJM46V3U5RZHCFRZ (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-5BRX4XDOKXUGIDQN  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/heapster: */

Chain KUBE-SVC-ERIFXISQEP7F7OF4 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-32UTAWJPHCDNBQRN  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kube-dns:dns-tcp */

Chain KUBE-SVC-JRXTEHDDTAFMSEAS (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-UYKT3UFXQIZFYBEA  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/monitoring-grafana: */

Chain KUBE-SVC-NPX46M4PTMTKRN6Y (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-25WBLIX7ISMTZJXQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */ recent: CHECK seconds: 10800 reap name: KUBE-SEP-25WBLIX7ISMTZJXQ side: source mask: 255.255.255.255
    0     0 KUBE-SEP-25WBLIX7ISMTZJXQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/kubernetes:https */

Chain KUBE-SVC-Q6XJQ2I55QTBQCWT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-IUANTHZC3XOZQHLT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/monitoring-influxdb: */

Chain KUBE-SVC-TCOU7JCQXEZGVUNU (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-X6ZKJV5GH7UMF5BF  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kube-dns:dns */

Chain KUBE-SVC-THOQCXWDZBULAUCX (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-KTKMCOADR7TK35UY  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/nginx-rc: */ statistic mode random probability 0.50000000000
    0     0 KUBE-SEP-L7FMAWCO2KPREIT2  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* default/nginx-rc: */

Chain KUBE-SVC-XGLOHA7QRQ3V22RZ (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SEP-6AWHDGGGFUCHEXV7  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/kubernetes-dashboard: */

**Comment by zhangxiaoyu-zidif** [comment]
could you show more details about your yamls and I am not sure somewhere goes wriong...

**Comment by tengqm** [comment]
looks like you have configured service cluster ip range to be 169.254.*, but your pod ip range is 172.17.*. How are you expecting the 169.254.* packets to be routed?

**Comment by oule** [comment]
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-rc
      labels:
        app: nginx-rc
    spec:
      containers:
      - name: nginx-rc
        image: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rc
spec:
  selector:
    app: nginx-rc
  ports:
  - port: 80
    targetPort: 80

**Comment by oule** [comment]
`apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-rc
      labels:
        app: nginx-rc
    spec:
      containers:
      - name: nginx-rc
        image: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rc
spec:
  selector:
    app: nginx-rc
  ports:
  - port: 80
    targetPort: 80`

**Comment by oule** [comment]
> apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-rc
      labels:
        app: nginx-rc
    spec:
      containers:
      - name: nginx-rc
        image: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rc
spec:
  selector:
    app: nginx-rc
  ports:
  - port: 80
    targetPort: 80

**Comment by oule** [comment]
@tengqm 
169.254.*是集群服务ip，是虚的，由iptables做nat转换的。

**Comment by oule** [comment]
抓包分析，倒是看出点问题，但是通过ethtool解决了，还是访问超时：
[root@node2 ~]# tcpdump -nn -qvv -i any port 8285
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
15:25:10.366031 IP (tos 0x0, ttl 64, id 7745, offset 0, flags [DF], proto UDP (17), length 80)
    10.1.1.172.8285 > 10.1.1.171.8285: [bad udp cksum 0x17a6 -> 0x9a4b!] UDP, length 52
15:25:11.368072 IP (tos 0x0, ttl 64, id 8584, offset 0, flags [DF], proto UDP (17), length 80)
    10.1.1.172.8285 > 10.1.1.171.8285: [bad udp cksum 0x17a6 -> 0x9a4b!] UDP, length 52
15:25:13.372036 IP (tos 0x0, ttl 64, id 10516, offset 0, flags [DF], proto UDP (17), length 80)
    10.1.1.172.8285 > 10.1.1.171.8285: [bad udp cksum 0x17a6 -> 0x9a4b!] UDP, length 52
15:25:15.320330 IP (tos 0x0, ttl 64, id 6033, offset 0, flags [DF], proto UDP (17), length 483)
    10.1.1.171.8285 > 10.1.1.172.8285: [udp sum ok] UDP, length 455
15:25:15.325807 IP (tos 0x0, ttl 64, id 11907, offset 0, flags [DF], proto UDP (17), length 428)
    10.1.1.172.8285 > 10.1.1.171.8285: [bad udp cksum 0x1902 -> 0x9f56!] UDP, length 400
15:25:15.327699 IP (tos 0x0, ttl 64, id 6035, offset 0, flags [DF], proto UDP (17), length 68)
    10.1.1.171.8285 > 10.1.1.172.8285: [udp sum ok] UDP, length 40

**Comment by oule** [comment]
期待前辈帮忙解决 :)

**Comment by oule** [comment]
[root@node2 ~]# curl 169.254.47.160
curl: (7) Failed connect to 169.254.47.160:80; Connection timed out

[root@node2 ~]# tcpdump -nn -qvv -i any port 80
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
15:31:42.770642 IP (tos 0x0, ttl 64, id 39003, offset 0, flags [DF], proto TCP (6), length 52)
    10.1.1.172.16127 > 172.17.59.3.80: tcp 0
15:31:43.771872 IP (tos 0x0, ttl 64, id 39004, offset 0, flags [DF], proto TCP (6), length 52)
    10.1.1.172.16127 > 172.17.59.3.80: tcp 0
15:31:45.775870 IP (tos 0x0, ttl 64, id 39005, offset 0, flags [DF], proto TCP (6), length 52)
    10.1.1.172.16127 > 172.17.59.3.80: tcp 0
通过kube-proxy的nat后实际访问的是pod  172.17.59.3，然后走flannel到达master，就是node1

**Comment by oule** [comment]
@zhangxiaoyu-zidif 
谢谢帮我排版，我看了下你帮我排过版的，使用` ` ` shell对吧

**Comment by zhangxiaoyu-zidif** [comment]
@oule  you‘re welcome~ =）

**Comment by zhangxiaoyu-zidif** [comment]
>[root@master ~]# curl 169.254.47.160
172.17.59.3    10.1.1.171
[root@master ~]# curl 169.254.47.160
172.17.59.3    10.1.1.171
[root@master ~]# curl 169.254.47.160
curl: (7) Failed connect to 169.254.47.160:80; Connection timed out

i am confused with it

**Comment by oule** [comment]
iptables random到本机pod时可以访问，到另一个node时就访问不了超时了
我抓包看到的bad checksum没有影响吧？
我开始认为是回复包回不来，我就进入另一个node的pod里，看连接状态，觉得应该是SYN_RECEIVE。
结果没有连接。看样子是包没有进到pod里。
请问老师，如何能看到包的整个接收，丢弃、转发log，比如开启什么内核参数什么的，也好有助于分析问题

**Comment by tengqm** [comment]
have you set `sysctl net.ipv4.ip_forward=1` ?

**Comment by oule** [comment]
yes,
```shell
[root@master ~]# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```
```shell
[root@node1 ~]# sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
```

**Comment by oule** [comment]
问题解决了，需要在kube-proxy配置文件里加--cluster-cidr就可以了，谢谢大家~
