### ISSUE TITLE
Issue with cluster pod network installation via kubeadm

### ISSUE THREAD

**Issue by horakmar** [kubernetes/website#6792]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Calico pod network installation doesn't work, because master node is tainted and doesn't accept pods running on it. Calico installation uses Daemonset, which schedules install-cni container, that installs CNI network configuration on each node, **including master**.
Other pod network solutions might suffer with the same problem.

**Proposed Solution:**
Before Calico installation untaint master node:
`kubectl taint nodes --all node-role.kubernetes.io/master-`
After installation optionally taint it again.

**Page to Update:**
http://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by tengqm** [comment]
@luxas ping.
