### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by ngrishnin** [kubernetes/website#6794]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This sentence makes no sense "These containers are isolated from each other and from the host: they have their own filesystems, they can’t see each others’ processes, and their computational resource usage can be bounded."

**Proposed Solution:**
Instead of "and their computational..." use "however their computational..."

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/

**Comment by tengqm** [comment]
cannot see the advantage of the proposed change ...

**Comment by ngrishnin** [comment]
Useless...

 
 
  On Fri, 26 Jan 2018 at 13:54, Zach Corleissen<notifications@github.com> wrote:   
Closed #6794.
