### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-interactive/

### ISSUE THREAD

**Issue by rcholic** [kubernetes/website#6798]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
A cluster means there should be more than 1 node, but this tutorial lacks how to add a second node to the cluster.

**Proposed Solution:**
I have no idea, otherwise I wouldn't bother reading this.

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@tengqm :wave: Am I correct in thinking it's possible to have single-node clusters?

**Comment by tengqm** [comment]
@zacharysarah in theory, a single-node cluster is possible.

**Comment by zacharysarah** [comment]
@rcholic Thanks for opening this issue. I'm flagging it for the tutorial team's attention.
