### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore-interactive/

### ISSUE THREAD

**Issue by prassawant** [kubernetes/website#6848]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
kubectl proxy does not open in new terminal 

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
Please be specific about the module to be fixed.

**Comment by BenHall** [comment]
Thanks for letting us know. I've tested this across a number of different browsers and I haven't been able to reproduce the issue.

Which browser are you running?

**Comment by prassawant** [comment]
Please close this ... sorry for late response ... it's working fine now
