### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/coreos/

### ISSUE THREAD

**Issue by alexa-infra** [kubernetes/website#6859]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Irrelevant links in the section **Official CoreOS Guides**, it looks like there are no any more kubernetes guides at CoreOS website, all links like https://coreos.com/kubernetes/docs/latest/ are redirected to guides using Tecnotic installer (which requires subscription).

**Proposed Solution:**
Rename section to CoreOS Tectonic and review its content or remove the section completely

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/coreos/

**Comment by scriptonist** [comment]
In the page https://kubernetes.io/docs/getting-started-guides/coreos/ all _official_ CoreOS guides now point to tectonic setups. Three of the _community guides_ are now archived by their repository owners.

**Comment by justaugustus** [comment]
@zacharysarah / @scriptonist -- I can look into this!
<-- CoreOS / Red Hat dude

**Comment by zacharysarah** [comment]
@justaugustus Sweet. 👍

**Comment by errordeveloper** [comment]
@justaugustus we are also undergoing conformance status review (see #7278), so it would great to look into that also! (feel free to ping me offline, if you need help and/or more info).

**Comment by justaugustus** [comment]
@errordeveloper Sounds good! I'll ping you :)

**Comment by errordeveloper** [comment]
@justaugustus have you managed to do anything about this?

**Comment by errordeveloper** [comment]
I'm removing `docs/getting-started-guides/coreos/bare_metal_offline.md` (#7821), as it's embarasingly outdated.

**Comment by justaugustus** [comment]
Hey @errordeveloper, sorry for not getting back to you sooner.
I'm still planning to do this, it's just been overall busy on this side. Hoping to be able to work a draft of the install docs for next week.
