### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by shruthibhaskar** [kubernetes/website#6880]
**This is a...** 

- [x] Feature Request
- [x] Bug Report

**Problem:**
root@ip-172-31-36-181:~# apt-get install -y kubelet kubeadm kubectl
Reading package lists... Done
Building dependency tree
Reading state information... Done
**E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl**

**Proposed Solution:**

**Page to Update:**

"Installing kubeadm, kubelet and kubectl"
https://kubernetes.io/docs/setup/independent/install-kubeadm/

**Comment by tengqm** [comment]
The full command chain is as follows:

```
apt-get update && apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl
```

Did you executed all commands?

**Comment by shruthibhaskar** [comment]
Hi,

I had done mistake in command execution.
I re-did it again,  now I have been able to install.  Thank you for the
support.

Regards
Shruthi

**Comment by faizurrahmann** [comment]
> The full command chain is as follows:
> 
> ```
> apt-get update && apt-get install -y apt-transport-https
> curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
> cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
> deb http://apt.kubernetes.io/ kubernetes-xenial main
> EOF
> apt-get update
> apt-get install -y kubelet kubeadm kubectl
> ```
> Did you executed all commands?

Hi tengqm,
Its worked for me well. Thank You.

But want to know what was exactly different with the below commands 

$ sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
$ sudo apt install kubeadm
