### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/scratch/ (--api-servers is deprecated)

### ISSUE THREAD

**Issue by z-oo** [kubernetes/website#6888]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This doc refers to deprecated kubelet flag --api-servers

**Proposed Solution:**
Use what is preferred now (maybe kubeconfig?)

**Page to Update:**
http://kubernetes.io/...

1.9.1

**Comment by zhangxiaoyu-zidif** [comment]
yes, we do not use --api-server for kubelet start parameter, and use kubeconfig instead.

**Comment by z-oo** [comment]
Yes, page to update in the subject line k8s.io/docs/getting-started-guides/scratch/

Sorry I somehow missed the url field in bug report body.
