### ISSUE TITLE
Setup merge automation for this repo

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/website#6906]
I'd like to setup merge automation for this repo.  This means:

Use an OWNERS file, /approve, /lgtm to allow people to merge PR's into this repo:
- If there isn't an OWNERS file, create one and populate it with people who already have write access to this repo (as approvers)
- Configure prow to turn on the "approval" plugin for this repo
- Configure prow/tide to include this repo in the tide query

/assign

**Comment by spiffxp** [comment]
Discussed during most recent sig-docs meeting, a few salient points that came up:
- existing workflow sometimes (not not always) involves a `Docs LGTM` and `Technical Review LGTM`
- suggested using `approved` == "conforms to docs standards", `lgtm` == "content looks technically good", with `do-not-merge/hold` used to other organic workflows
- suggested using this issue to make sure we had consensus
- will make sure OWNERS/OWNERS_ALIASES are setup but won't actually enable approval+tide until I see consensus reached on this issue

**Comment by heckj** [comment]
per conversation in https://www.youtube.com/watch?v=3ym97JJnV1I && notes in https://docs.google.com/document/d/1Ds87eRiNZeXwRBEbFr6Z7ukjbTow5RQcNZLaSvWWQsE/edit from 1/16 SIG-DOCs meeting, we're +1 to do this...

/cc chenopis
/cc zacharysarah
/cc steveperry-53
/cc jaredbhatti
/cc bradamant3

**Comment by zacharysarah** [comment]
@spiffxp 👋 I think we'll be ready to merge this tomorrow afternoon PST, if that works for you!

**Comment by chenopis** [comment]
@spiffxp Any blocking issues left, or are we good to go?

**Comment by chenopis** [comment]
And we're live!

**Comment by zacharysarah** [comment]
Hooray! 🎉
