### ISSUE TITLE
kubectl autogenerated reference links point to non-existent page

### ISSUE THREAD

**Issue by petetnt** [kubernetes/website#6912]
- [ ] Feature Request
- [x] Bug Report

**Problem:**

Every autogenerated link on https://kubernetes.io/docs/reference/generated/kubectl/kubectl/ point to non-existent page. Click any of the links under `SEE ALSO`

**Proposed Solution:**

Should point to the correct page

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl/

**Comment by zacharysarah** [comment]
@petetnt The links have been fixed--thanks for reporting them. 🙇

**Comment by petetnt** [comment]
Thank you ❤️
