### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/update-api-object-kubectl-patch/

### ISSUE THREAD

**Issue by submarin76** [kubernetes/website#6934]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Cleaning Up section is missing
"kubectl delete pod ..." is not enough to clean up
**Proposed Solution:**
Please add a cleaning up section.

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/

1.9

**Comment by tengqm** [comment]
isn't `kubectl delete deployment patch-demo` pretty obvious?

**Comment by nikhita** [comment]
> isn't kubectl delete deployment patch-demo pretty obvious?

+1.

@submarin76 Thanks for your suggestion! However, the page talks about updating api objects using kubectl patch. A "cleaning up" section seems unwarranted here. Afaik we don't add this for other pages as well.
