### ISSUE TITLE
can not auto create /registry  problem

### ISSUE THREAD

**Issue by oule** [kubernetes/website#6984]
大家好：
我的k8s集群环境是：
etcd-1  10.1.1.180
etcd-2  10.1.1.181
etcd-3  10.1.1.182

k8s-master-1  10.1.1.183  vip: 10.1.1.186 with keepalived
k8s-master-2  10.1.1.184
k8s-master-3  10.1.1.185
k8s-node-1  10.1.1.187

centos 7.3.1611
etcd-3.2.9
k8s-1.8.6
docker-17.09.0-ce
flannel-0.7.1

原来部署的是k8s-1.5.2,docker-1.12.6,可以使用，但是比较慢，后来升级版本，把docker和k8s都卸载了，
安装了上面列表的版本，etcd没有任何改动，只是把/registry删除了，现在集群部署完了，启动master的三个服务器apiserver,schduler,controller-manager，但是etcd里并没有自动创建出来/registry这个该怎么解决，怎么初始化一下呢

**Comment by zhangxiaoyu-zidif** [comment]
etcd should be updated. now we use etcd V3 interface, not v2 yet. So maybe the v1.8.6 kubernetes use v3 default. that's my guess.

**Comment by tengqm** [comment]
@zhangxiaoyu-zidif is right, etcd v3 has a different way to store the cluster data. You don't have to worry about it at all. Even if you do, you will need some tools to marshal/unmarshal data using protobuf ...

**Comment by tengqm** [comment]
I think this can be closed.

**Comment by zhangxiaoyu-zidif** [comment]
@tengqm  thanks
/close

**Comment by oule** [comment]
I used version is 3.2.9 now ~

**Comment by zhangxiaoyu-zidif** [comment]
another question is that, now kubernetes v1.8 should use v3.1.X etcd. and V2 or V3 is decided by your kubernetes. I mean when you use v1.5.2, you use V2, now you sue 1.8, while 1.8 use V3 default.

**Comment by zhangxiaoyu-zidif** [comment]
if the data in your etcd is not very important, i suggest re-deploy etcd. =)

**Comment by oule** [comment]
I execute  yum remove etcd
and
rm -rf /var/lib/etcd
yum install etcd
systemctl restart kube-apiserver
可是etcdctl ls /依然是空的

**Comment by zhangxiaoyu-zidif** [comment]
are those parameters between apiserver and etcd correct?

**Comment by zhangxiaoyu-zidif** [comment]
>我只能使用3.1.x是吗，不能使用3.2.9吗

right! because the higher version of etcd has not been tested yet. we don't know if there are some problems.

**Comment by oule** [comment]
依旧没有创建
```shell
[root@k8s-etcd-1 ~]# etcdctl cluster-health
member 95a31028319a932 is healthy: got healthy result from http://10.1.1.180:2379
member 6b61c3c45943c8c6 is healthy: got healthy result from http://10.1.1.181:2379
member 77f565a2a38dcd8d is healthy: got healthy result from http://10.1.1.182:2379
cluster is healthy
[root@k8s-etcd-1 ~]# etcdctl -v
etcdctl version: 3.1.9
API version: 2
[root@k8s-etcd-1 ~]# etcdctl ls /
[root@k8s-etcd-1 ~]#
```

**Comment by oule** [comment]
```shell
[root@k8s-master-1 kubernetes]# systemctl restart kube-apiserver
[root@k8s-master-1 kubernetes]# systemctl status kube-apiserver -l
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-01-17 12:53:06 CST; 14s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 2051 (kube-apiserver)
   Memory: 176.2M
   CGroup: /system.slice/kube-apiserver.service
           └─2051 /usr/bin/kube-apiserver --logtostderr=false --v=2 --log-dir=/var/log/kubernetes --etcd-servers=http://10.1.1.180:2379,http://10.1.1.181:2379,http://10.1.1.182:2379 --insecure-bind-address=0.0.0.0 --insecure-port=8080 --allow-privileged=false --service-cluster-ip-range=169.254.0.0/16 --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ResourceQuota --apiserver-count=3

Jan 17 12:52:57 k8s-master-1 systemd[1]: Starting Kubernetes API Server...
Jan 17 12:52:59 k8s-master-1 kube-apiserver[2051]: [restful] 2018/01/17 12:52:59 log.go:33: [restful/swagger] listing is available at https://10.1.1.183:6443/swaggerapi
Jan 17 12:52:59 k8s-master-1 kube-apiserver[2051]: [restful] 2018/01/17 12:52:59 log.go:33: [restful/swagger] https://10.1.1.183:6443/swaggerui/ is mapped to folder /swagger-ui/
Jan 17 12:53:00 k8s-master-1 kube-apiserver[2051]: [restful] 2018/01/17 12:53:00 log.go:33: [restful/swagger] listing is available at https://10.1.1.183:6443/swaggerapi
Jan 17 12:53:00 k8s-master-1 kube-apiserver[2051]: [restful] 2018/01/17 12:53:00 log.go:33: [restful/swagger] https://10.1.1.183:6443/swaggerui/ is mapped to folder /swagger-ui/
Jan 17 12:53:06 k8s-master-1 systemd[1]: Started Kubernetes API Server.
```

**Comment by zhangxiaoyu-zidif** [comment]
>API version: 2
use 3 instead

**Comment by tengqm** [comment]
sigh ... didn't you spend some time learning the way to interact with etcd using the v3 api?
`etcdctl ls` is deprecated in v3; you need to sit down and read some etcd docs, or at least try this:

```
$ ETCDCTL_API=3 etcdctl --help
```

**Comment by oule** [comment]
谢谢各位！
@tengqm
实在不好意思，麻烦您了。我英文不怎么好，看过部分官方文档，但是看的不多，到是看过不少帖子，看过《kubernetes权威指南》，我想先通过这些把最简单，最小化的集群先跑起来，然后一步一步深入。我也知道读完全部官方文档，甚至看完全部源码，我就不用到这里来麻烦大家了，但是目前的状况还不行，在我看完全部文档和源码前，可能还得来这里咨询，不过，如果觉得的我的提问太低级，也可以不理，这都没什么的，再次感谢大家~ ：）

**Comment by tengqm** [comment]
@oule Try this: https://jimmysong.io/kubernetes-handbook/guide/using-etcdctl-to-access-kubernetes-data.html

**Comment by oule** [comment]
好的，非常感谢，我先收藏了。
目前我还是先用我之前部署的老版本，等有时间再研究新版部署问题，
再次感谢~ ：）

**Comment by tengqm** [comment]
@oule Fine, but you didn't read my message. Your installation may be okay. You cannot say it is not operating simply because 'etcdctl ls' returns nothing.
