### ISSUE TITLE
Issue with k8s.io/docs/tasks/run-application/run-single-instance-stateful-application/

### ISSUE THREAD

**Issue by kapalkat** [kubernetes/website#6990]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Deployment yaml file:
mysql-deployment.yaml api version does not fit 1.9 version:
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment

**Proposed Solution:**
change apiVersion to: apps/v1

**Page to Update:**
https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

Kubernetes Version:
1.9
![apiversionupdate_docs](https://user-images.githubusercontent.com/26725074/35038262-8ea3f8d4-fb7a-11e7-91b7-faed9515d83b.jpg)

**Comment by islinwb** [comment]
#6992
