### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/pod-priority-preemption/

### ISSUE THREAD

**Issue by cwangsh** [kubernetes/website#7020]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
when multiple Pods/containers share a CPU core, is it the k8s scheduler or linux OS that is responsible for the scheduling of the processes/threads (determine which process/thread to execute and others to be suspended)

**Proposed Solution:**

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
os scheduler.

**Comment by cwangsh** [comment]
thank you very much
