### ISSUE TITLE
Issue with k8s.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

### ISSUE THREAD

**Issue by bragi92** [kubernetes/website#7054]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Pod deployment fails with Status -> ErrImagePull when trying to deploy dapi-envars-pod.yaml

**Proposed Solution:**
Correct the link given in the yaml file.

**Page to Update:**
https://v1-7.docs.kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/

Kubernetes version: 1.7.7

**Comment by stewart-yu** [comment]
It work well in my local, i think your network broken down

**Comment by bragi92** [comment]
That might be the case. I realized, I'm not able to ping to websites from my master node but I was able to download the image by using a docker. Do you know if I can point the yaml installation file to pick up the image locally?
