### ISSUE TITLE
Document vSphere cloud provider RBAC requirements

### ISSUE THREAD

**Issue by praseodym** [kubernetes/website#7058]
**This is a...** 
Bug Report

**Problem:**
SInce Kubernetes v1.9.0, the vSphere Cloud Provider requires a cluster role to work on clusters with RBAC enabled. This is not documented.

**Proposed Solution:**
Add configuration from https://github.com/kubernetes/kubernetes/issues/57279#issuecomment-359607201 to vSphere cloud provider documentation page.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/vsphere/

**Comment by aburdenthehand** [comment]
Hi @praseodym - based on the comments in #7583 it seems like the situation has changed since this issue was created.

I believe this issue can be closed.
