### ISSUE TITLE
kubectl logs cannot work

### ISSUE THREAD

**Issue by fengyd2018** [kubernetes/website#7059]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Kubernetes cluster: 
one master: 192.168.56.104 
one node: 192.168.56.105

If the container kubectl logs want to check is on the master, kubectl logs can work.
If the container kubectl logs want to check is on the node, kubectl logs cannot work.
Part of the printout with the command "kubectl logs kube-flannel-ds-9544j -n kube-system -v 10" on the master:
I0123 03:09:11.715274   28594 round_trippers.go:417] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.9.2 (linux/amd64) kubernetes/5fa2db2" https://192.168.56.104:6443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-9544j/log
I0123 03:12:19.979305   28594 round_trippers.go:436] GET https://192.168.56.104:6443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-9544j/log 500 Internal Server Error in 188263 milliseconds
I0123 03:12:19.983757   28594 round_trippers.go:442] Response Headers:
I0123 03:12:19.983799   28594 round_trippers.go:445]     Content-Type: application/json
I0123 03:12:19.983818   28594 round_trippers.go:445]     Content-Length: 203
I0123 03:12:19.983833   28594 round_trippers.go:445]     Date: Tue, 23 Jan 2018 08:12:19 GMT
I0123 03:12:19.983927   28594 request.go:873] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Get https://192.168.56.105:10250/containerLogs/kube-system/kube-flannel-ds-9544j/kube-flannel: Gateway Timeout","code":500}
I0123 03:12:20.002821   28594 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Get https://192.168.56.105:10250/containerLogs/kube-system/kube-flannel-ds-9544j/kube-flannel: Gateway Timeout",
  "code": 500
}]
F0123 03:12:20.005362   28594 helpers.go:119] Error from server: Get https://192.168.56.105:10250/containerLogs/kube-system/kube-flannel-ds-9544j/kube-flannel: Gateway Timeout

**Comment by tengqm** [comment]
This is more of a tech support issue than a documentation one, can you raise it in kubernetes/kubernetes project or ask it on slack channel?

BTW, it looks like your apiserver cannot authenticate to the 192.168.56.105 node. Check the apiserver command line arguments and see if it has the proper tls setting?

**Comment by fengyd2018** [comment]
Thanks for your answer.
It's caused by the proxy issue.
kubectl log can work after adding the node ip  to the environment no_proxy.
