### ISSUE TITLE
Issue with k8s.io/docs/tasks/inject-data-application/distribute-credentials-secure/

### ISSUE THREAD

**Issue by jar349** [kubernetes/website#7065]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The beginning text instructs the reader to run `echo -n 'my-app' | base64` to get the base64 representation of the app name, but immediately after uses the output of `echo 'my-app' | base64` in the example file without explaining which is correct, or why we switched from using one to using the other.

**Proposed Solution:**
Clarify which is correct and why.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
Well, just verified... the output from the following two commands differ:
```
echo 'my-app' | base64
echo -n 'my-app' | base64
```

The trailing `Cg==` is the base64 encoded string for "`\n`".

**Comment by jar349** [comment]
Yes, that's what echo's `-n` argument does: controls whether it adds a trailing `"\n"`
