### ISSUE TITLE
Documentation: Out Of Resource Handling does not state default settings

### ISSUE THREAD

**Issue by miketonks** [kubernetes/website#7082]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

There is missing documentation of the default settings for eviction thresholds and related settings.

e.g. MemoryPressure and DiskPressure

MemoryPressure setting is documented:

--eviction-hard=memory.available<100Mi

But disk pressure is not.

**Proposed Solution:**

Add a section to the document to show all default settings.

**Page to Update:**

https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

**Comment by tengqm** [comment]
/remove-lifecycle stale
/lifecycle frozen

This is a valid request. Users need to know the defaults for this kind of thresholds.
