### ISSUE TITLE
responsive layout for reference pages

### ISSUE THREAD

**Issue by den-is** [kubernetes/website#7091]
Maybe there is way to make UI/X of auto-generated reference pages for components little bit more useful, comfortable ?

I'm using 1080p, 2k and Retina Displays - reading information on this pages is really frustrating. These scrollbars...

I've tried to search duplicate, because I don't want to believe that this issue disturbs only me - but no luck.

**Comment by zacharysarah** [comment]
@den-is Thanks for the feedback.

**Comment by idvoretskyi** [comment]
cc @kubernetes/sig-docs-maintainers

**Comment by tengqm** [comment]
@den-is Can you help check if the issue you reported still exists? Otherwise we are about to close this issue.

**Comment by den-is** [comment]
yea, all looks much better now, compared to what it was before you migrated site engine
closing it
