### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-service-account/

### ISSUE THREAD

**Issue by lchao111** [kubernetes/website#7100]
**This is a document error.** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Error from server: invalid character 'i' looking for beginning of object key string
from kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "myregistrykey"}]}'

**Proposed Solution:**
escape this JSON string by '\\'
kubectl patch serviceaccount default -p '{\\"imagePullSecrets\\": [{\\"name\\": \\"acrkey\\"}]}'
**Page to Update:**
http://kubernetes.io/...

**Comment by anubhakushwaha** [comment]
@lchao111 @zacharysarah I was willing to take this up

**Comment by zacharysarah** [comment]
@anubhakushwaha Go for it! 👍

**Comment by anubhakushwaha** [comment]
@zacharysarah Done

**Comment by eavonius** [comment]
This is still a problem here:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-image-pull-secret-to-service-account
