### ISSUE TITLE
Document supported component skew

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/website#7103]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Forked from https://github.com/kubernetes/kubernetes/issues/33212

Kubernetes only allows 2 minor version skew between nodes and master, and 1 minor version skew between kubectl and master. However, this is not mentioned anywhere in user-facing documents. This caused user confusion and may cause unexpected issues to users' clusters. 

It's documented in contributors' doc: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew
> Different components are expected to be compatible across different amounts of skew, all relative to the master version. Nodes may lag masters components by up to two minor versions but should be at a version no newer than the master; a client should be skewed no more than one minor version from the master, but may lead the master by up to one minor version. For example, a v1.3 master should work with v1.1, v1.2, and v1.3 nodes, and should work with v1.2, v1.3, and v1.4 clients.

**Proposed Solution:**
Add some document(s) in http://kubernetes.io/ to include the above information. 

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@janetkuo 👋 Thanks, this is helpful!

**Comment by pgadige** [comment]
I'm working on this.

**Comment by neolit123** [comment]
not sure if this page is still maintained:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

but a "node-local" fact that i encountered is that a X kubelet does not work with a X-1 api-server.
if that is supposed to be supported we broke it a few times.

**Comment by liggitt** [comment]
> but a "node-local" fact that i encountered is that a X kubelet does not work with a X-1 api-server.
> if that is supposed to be supported we broke it a few times.

it is definitely not supported:
> Nodes may lag masters components by up to two minor versions but should be at a version no newer than the master;

**Comment by liggitt** [comment]
I am working on a canonical page for website to list supported version skews

**Comment by liggitt** [comment]
> is the plan to remove https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew once your PR merges?

That's on my list to look at next, dropping misleading or incorrect data, deduplicating against #11060, and we'll see if anything useful remains. If not, yes, I'll drop it with a pointer to the website doc.
