### ISSUE TITLE
Incorrect left nav 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/website#711]
For example, 
http://kubernetes.io/docs/getting-started-guides/coreos/ belongs to two left nav, and both titles are misleading 
![screenshot from 2016-06-22 13 48 06](https://cloud.githubusercontent.com/assets/4876867/16283048/fbfdf34a-387f-11e6-9e5b-e2aef9828c41.png)

Same problem for http://kubernetes.io/docs/getting-started-guides/juju/  
![image](https://cloud.githubusercontent.com/assets/4876867/16283062/0f7ceaa2-3880-11e6-9f54-0e9db35ba769.png)

This is confusing. cc @kubernetes/docs

**Comment by tengqm** [comment]
/remove-lifecycle rotten
The "getting started guides" need some more work.

**Comment by shubheksha** [comment]
The issue seems to persist with http://kubernetes.io/docs/getting-started-guides/coreos/
/remove-lifecycle stale
