### ISSUE TITLE
DNS debugging article should be extracted from DNS configuration doc

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#7115]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/
This article contains two topics which I think should be separate:
- Customizing DNS service
- Debugging DNS

These two are not necessarily related.
 
**Proposed Solution:**

Move Debugging DNS into a separate article. 

**Page to Update:** https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/

**Comment by zacharysarah** [comment]
@ahmetb 👋 Agreed, Debugging would be better as its own article.

**Comment by scriptonist** [comment]
Is it ok to take up this issue and work on this?

**Comment by tengqm** [comment]
sure. @scriptonist

**Comment by scriptonist** [comment]
Closing since Issue resolved by PR #7436

**Comment by ahmetb** [comment]
Apparently this is fixed now.
