### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by hakenmt** [kubernetes/website#7116]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The command line reads for the last command in Module 2 reads:
curl http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAME/

**Proposed Solution:**
Remove "proxy" from the url path,

curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
the url is correct. Is it causing any problems?

**Comment by hakenmt** [comment]
I was running through the bootcamp and got an error when curling to that URL. I didn't take a screenshot then, but I believe the error was related to a TCP problem with the proxy. I just tried again and couldn't reproduce. Without the proxy I could at least query the pod info directly.

**Comment by tengqm** [comment]
the 'proxy' path on 8001 port the correct combination when you run kubectl proxy. If you want direct access to the APIs, you are supposed to use 8080 or 6443.
