### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/secret/

### ISSUE THREAD

**Issue by gnustavo** [kubernetes/website#7126]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
The section "using secrets" mentions more than once that permission modes were written in decimal because JSON doesn't support octal. But the examples are in YAML, which supports octal notation.

**Proposed Solution:**
Use octal notation on the YAML examples.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by zacharysarah** [comment]
@gnustavo :wave: Thanks for the suggestion!

**Comment by zacharysarah** [comment]
@mikedanese 👋 Would you like to update the examples, or are you comfortable if others update them?

/assign @mikedanese

**Comment by gnustavo** [comment]
Hi. I'm comfortable with others changing them. Please, be my guest!

Em 5 de fev de 2018 21:29, "Zach Corleissen" <notifications@github.com>
escreveu:
