### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by GrahamCP** [kubernetes/website#7160]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Interactive tutorial, module 2, step 3.  Click on command "kubectl proxy" opens a second interactive terminal (no apparent shell commands).  Then curl commands fail with error below:
curl: (7) Failed to connect to localhost port 8001: Connection refused

Second click on command "kubectl proxy" leads to the second terminal showing this:
$ kubectl proxy
Starting to serve on 127.0.0.1:8001

Then curl commands execute as expected.

**Proposed Solution:**
Update the tutorial to prompt the user to manually open a second terminal, then click command "kubectl proxy".  But this is a workaround, not a solution.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

Chrome browser version 63.0.3239.132 (Official Build) (64-bit)

**Comment by BenHall** [comment]
Thanks for the feedback. We've moved this scenario to Minikube 1.9. Hopefully this will improve the kubectl proxy.

If you still have having problems, please update the issue.
