### ISSUE TITLE
update-imported-docs needs a linux binary

### ISSUE THREAD

**Issue by castrojo** [kubernetes/website#7198]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The doc generator for the community section only has a binary for OSX, a linux one would be great.

**Page to Update:**
https://github.com/kubernetes/website/tree/master/update-imported-docs

**Comment by zacharysarah** [comment]
@castrojo :wave: Looks like @chris-short is outside of the K8s org. ☝️

**Comment by chris-short** [comment]
Is that normal?

**Comment by chenopis** [comment]
@castrojo My apologies. I'll submit a PR.
