### ISSUE TITLE
Issue with k8s.io/docs/reference/generated/kube-scheduler/

### ISSUE THREAD

**Issue by ViniciusDeAndrade** [kubernetes/website#7212]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I am trying to deploy replicas of the same microservice into differents nodes. I think it is not possible
using the default kubernetes primitives. 

**Proposed Solution:**
I am developing a solution using a java client. I want to create a extension of the kube-scheduler that make possible the deploy of the replicas of a same microservice into different nodes.
How can I do that?

**Comment by steveperry-53** [comment]
@ViniciusDeAndrade This issue needs to be opened in kubernetes/features, not kubernetes/website.

**Comment by ViniciusDeAndrade** [comment]
Sorry. I will close this.
