### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by mfilotto** [kubernetes/website#7222]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
The page does not show up and displays a redirecting message
`Redirecting to /docs/concepts/workloads/controllers/deployment/`

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by ibrasho** [comment]
The link is missing a trailing slash: `https://kubernetes.io/docs/concepts/workloads/controllers/deployment` -> `https://kubernetes.io/docs/concepts/workloads/controllers/deployment/`.
