### ISSUE TITLE
Example yaml files apiVersion usage clarification is not enough 

### ISSUE THREAD

**Issue by spzala** [kubernetes/website#7231]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
Some of the example yaml (e.g. https://raw.githubusercontent.com/kubernetes/website/master/docs/tasks/run-application/mysql-deployment.yaml) has a clarification that use apiVersion apps/v1beta2 before Kubernetes release 1.9.0. However, the suggested version won't work on earlier versions like 1.7 or 1.6 where correct version is apps/v1beta1. Using apps/v1beta2 on a 1.7.5 gives following error:
```
Error from server (BadRequest): error when creating "nginx.yaml": Deployment in version "v1beta2" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v1beta2"
```
Version 1.7 seems still used by many and only a two release older version. We should provide a better clarification.

**Proposed Solution:**
Provide a better clarification.

**Page to Update:**
http://kubernetes.io/...

**Comment by tengqm** [comment]
Current solution is to have docs and sample yaml files maintained on a per-version basis. So in v1.9 doc, we are about to document apps/v1. To check docs for v1.8, you will switch to that version from website, there you will see apps/v1beta2 documented. There could still be defects though.
