### ISSUE TITLE
Interactive tutorials are still on Kubernetes 1.5

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#7240]
I have just looked into #7237, and noticed that the Katacoda environment is still running Kubernetes 1.5.2.

I am not sure what numbers of visitors we are seeing at `k8s.io/docs/tutorials/kubernetes-basics/*`, but it's not very good news that folks get exposed to a version of Kubernetes that is more than 1 year old.

There are probably other places on the website where we have similar or worse kind of situations, but Katacoda one seems like it should be fairly simple to tackle.

I don't know who maintains these, and I do recall there was a repo with config.

CC @BenHall.

**Comment by BenHall** [comment]
I agree, thanks for the prompt. I had upgraded to Minikube 1.8 along with a few other improvements (metrics etc) but it had a few issues at launch so I decided not to push it out. It then slipped my mind.

Will take another look this week.

**Comment by errordeveloper** [comment]
Also, there are seem to be quite a few issues that had been marked stale, and, most likely, are safe to close, I've had a quick look at a few, but don't have the dedication to do them all right now, full triage seems like a good idea when the environment is up-to-date.

**Comment by BenHall** [comment]
@errordeveloper I try and keep on top of them and reply, but I don't have permissions to close issues after they've been resolved.

**Comment by errordeveloper** [comment]
@BenHall I think you should be able to use `/close` command, try it on an issue that was marked stale by the bot.

**Comment by errordeveloper** [comment]
@BenHall If that doesn't work, you might need to apply to become a member, which is fairly easy. As a member, I can use `/close`.

**Comment by BenHall** [comment]
@errordeveloper Looks like I can close stale issues... but I don't think I can close non-stale issues. Will go over everything after upgrade.

**Comment by zacharysarah** [comment]
@BenHall The ability to close tutorial-related issues is a good question. @heckj, I'd love your thoughts.

**Comment by heckj** [comment]
@zacharysarah While I personally don't mind tracking issues for the Katacode based tutorials, it's a little awkward primarily because it's not entirely clear that the content is hosted externally to this repo, and making changes and updates is mostly a very independent process.

If we, or perhaps "as we" - can't quite see into this murky future - have other tutorial sites that are active and supporting Kubernetes, then it might make more sense to reference them neutrally and no track bugs related to them here, but allow them to manage content feedback on their own and resolve it as such.

While I've helped make improvements to the text content of the tutorials, I will admit to not having a great deal of clarity even for myself on what "done" might be in resolving some of the open issues. So I'm definitely glad @BenHall can close at least the stale bugs, and while we're tracking issues for that tutorial set embedded into kubernetes.io it might make sense to allow him to close non-stale issues as well, as I think he has the best sense of what will and won't get done related to many of them.

**Comment by BenHall** [comment]
We've built a new environment that uses Minikube 1.9. How this will impact the overall performance is unknown. I've changed the first scenario where users deploy Minikube to 1.9. If that all looks OK then I'll update the other scenarios to match.

Enhancements:
1) This uses the Minikube 1.9 release without any modifications/changes. This means all the functionality supported by Minikube is now available via the environment. 

![screenshot 2018-02-11 17 50 38](https://user-images.githubusercontent.com/82614/36076446-21424ca8-0f54-11e8-9121-849ea6ef3d0c.png)

Boot time roughly:
```
real    0m11.479s
user    0m1.304s
sys     0m0.668s
```

2) The environment creation is automated allowing us to quickly deploy future releases and changes. As we're using the upstream release, it will hopefully just a case of updating the version number.

3) Users are connected to the same server, meaning if they run `hostname` it will return `host01`. They can also use `minikube ip` which will return the machine IP. This should hopefully remove some confusion users have had in relation to where `host01` is defined.

4) The dashboard is deployed by default, and includes all the metrics you'd expected.

![screenshot 2018-02-11 17 53 49](https://user-images.githubusercontent.com/82614/36076480-899c5208-0f54-11e8-98d1-f798198d8fc8.png)

5) I've configured support for the editor. It's possible to re-purpose of browser-editor for creating/configuring YAML files.

Known issues:
1) The time of when the node was created is left over from when the environment was built. I'm rebuilding this to ensure the previous environment is deleted.

**Comment by errordeveloper** [comment]
> So I'm definitely glad @BenHall can close at least the stale bugs, and
while we're tracking issues for that tutorial set embedded into
kubernetes.io it might make sense to allow him to close non-stale issues as
well, as I think he has the best sense of what will and won't get done
related to many of them.

I am in support of getting Ben the right level of access he needs.

**Comment by BenHall** [comment]
Thanks, I'd love to have the ability to clean up issues.

What I think could be a great help is if the content at https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios is moved to within the https://github.com/kubernetes world. We can then configure it to automatically deploy updates on Katacoda so the workflow is more transparent. 

Would this make sense?

**Comment by errordeveloper** [comment]
> Would this make sense?

Yes!

**Comment by BenHall** [comment]
@errordeveloper Great! How do we create a repo? :)

**Comment by errordeveloper** [comment]
@BenHall you would need to take this up SIG-docs, add it to their agenda doc and/or post on the mailing list. I am happy to sponsor, if needed.

**Comment by BenHall** [comment]
@errordeveloper Great, thanks. I will add it to the agenda for next Tuesday.

**Comment by errordeveloper** [comment]
@BenHall should this issue be closed now?

**Comment by BenHall** [comment]
Yes please :)
