### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by YDD9** [kubernetes/website#7244]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In section Create etcd CA certs, at the end of step2
```
cat >ca-csr.json <<EOL
 {
     "CN": "etcd",
     "key": {
         "algo": "rsa",
         "size": 2048
     }
 }
 EOL
```
Ensure that the **names** section in **ca-csr.json** matches your own company or personal address, or that you use a suitable default.

There's no names section in the example.

**Proposed Solution:**
Is the ca-csr.json correct ? Does it need names section, how should it look like ?

**Page to Update:**
http://kubernetes.io/...

**Comment by zacharysarah** [comment]
@YDD9 Thanks, updating the YAML sample is a good suggestion. 👍 

@errordeveloper 👋 Would you please provide an example of `names`?

**Comment by errordeveloper** [comment]
I'd rather get rid of manual steps here, otherwise I'm not sure what the answer should be.

**Comment by mattkelly** [comment]
Here's an example `ca-csr.json` with a valid `names` section FWIW:

```
{
        "CN": "etcd",
        "key": {
                "algo": "rsa",
                "size": 2048
        },
        "names": [
                {
                        "C": "US",
                        "L": "San Francisco",
                        "O": "Example Company",
                        "OU": "Operations",
                        "ST": "California"
                }
        ]
}
```

See the cfssl example [here](https://github.com/cloudflare/cfssl/wiki/Creating-a-new-CSR).

My preference would be to include an example `names` section like above, and if the user wants to touch it up for their org then it will be obvious how to to so. If they choose not to touch it up, it will still work. I agree that mentioning the `names` section and then not including it at all is confusing.

**Comment by errordeveloper** [comment]
I don't see a need for this, it's optional. Maybe we could add `"O": "Kubernetes Project"`, but I am strongly against including any geographic references.

**Comment by mattkelly** [comment]
I've since verified that it works without a `names` section at all, so maybe let's just remove the mention of a `names` section from the docs? Or (probably better) suggest adding it as an optional step?

**Comment by errordeveloper** [comment]
> ... suggest adding it as an optional step?

Yes, let's do that.

**Comment by zacharysarah** [comment]
Closing in favor of #7392.
