### ISSUE TITLE
Ambiguous information on k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by duckie** [kubernetes/website#7255]
This is an Ambiguous information

**Problem:**

The table of the open ports for the master nodes specifies `6443*`. What does the `*` means here ? I expected a foot note which is not there, and other information elsewhere suggests the port should be 443. Can you clarify ?

**Proposed Solution:**

Explain what it means.

**Page to Update:**

http://k8s.io/docs/setup/independent/install-kubeadm/

**Comment by islinwb** [comment]
There is an explanation below the tables.
>Any port numbers marked with * are overridable, so you will need to ensure any custom ports you provide are also open.

**Comment by duckie** [comment]
Ok, right, maybe that'd be cool to add it right before the `**` footnote. I'll propose it in a PR. Thank you for your help !
