### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by davidmukiibi** [kubernetes/website#7272]
**This is an issue to do with the instructions for the online terminal tutorial** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
There is a grammatical error in module 5, step 2(Load balancing) of the online terminal tutorial.  pasted below...

"Create an environment variable called NODE_PORT that has as value the Node port:"

**Proposed Solution:**
This is what I suggest it should be changed to, so as to reduce confusion while following the tutorial. Below is the edit I suggest...

"Create an environment variable called NODE_PORT that has a value as the Node port:"

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/scale-interactive/

**Comment by BenHall** [comment]
Thanks, we'll get this updated

**Comment by BenHall** [comment]
This has been updated. Thanks 

/close
