### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/kops/

### ISSUE THREAD

**Issue by mcqj** [kubernetes/website#7275]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
The instructions for installing on MacOS begin with a **wget** command. wget is not available on MacOS by default. It should also be noted that the download link redirects.

**Proposed Solution:**
Use **curl** command instead. For example:
```
curl -OL https://github.com/kubernetes/kops/releases/download/1.8.0/kops-darwin-amd64
```
The -L option is important for following the redirect.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/kops/

**Comment by pmallory** [comment]
#7613  fixes this

**Comment by pmallory** [comment]
@zacharysarah Can you close this issue? I forgot to use the [magic words](https://help.github.com/articles/closing-issues-using-keywords/) in my PR :joy:. Thanks!

**Comment by zacharysarah** [comment]
@pmallory Sure thing! :smile:
