### ISSUE TITLE
Issue with k8s.io/docs/tutorials/online-training/overview/

### ISSUE THREAD

**Issue by benbotwin** [kubernetes/website#7277]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
Both links on this page to go the udacity course

**Proposed Solution:**
make the edx link go to edx

**Page to Update:**
https://kubernetes.io/docs/tutorials/online-training/overview/

**Comment by BenHall** [comment]
Thanks but I'm not the person responsible. It looks like it was fixed in #7276

**Comment by zacharysarah** [comment]
@benhall Got it, thanks!
