### ISSUE TITLE
conformance status for /docs/getting-started-guides/rkt

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#7279]
Per #7278, we are looking to identify guides that are stale vs actively maintained but need work to become conformant.

The content of `/docs/getting-started-guides/rkt` has been identified as stale, because it refers to Kubernetes version `v1.3.0-beta.2` which is very old.

PING owners/approvers/contributors @dchen1107 @yifan-gu @lavalamp @lizrice @steveperry-53

**Comment by lizrice** [comment]
That page totally confused me when I was trying to run rkt - so my change was basically to point at instructions for the new CRI version. I'm fully supportive of retiring that rktnetes page (or moving it out of the top-level getting started guides at least), though there should still be an easy-to-find reference about how to run with rkt the CRI way.

**Comment by yifan-gu** [comment]
@errordeveloper @lizrice Thanks for filing the issue, the docs is out-of-date, let's remove it.

**Comment by errordeveloper** [comment]
Ok, SGTM! Thanks for quick response.

**Comment by errordeveloper** [comment]
@yifan-gu please approve https://github.com/kubernetes/website/pull/7376.
