### ISSUE TITLE
Improve navigation in Kubernetes docs

### ISSUE THREAD

**Issue by mattayes** [kubernetes/website#7282]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The [Kubernetes documentation](https://kubernetes.io/docs/home/) is awesome. Right now it's a bit cumbersome to read through the docs; every time you hit the end of the page, you have to scroll back to the top and click the next section you'd like to read. This is a bit of a pain, especially if you're trying to read the docs from "cover to cover".

**Proposed Solution:**
It would be great if there were navigation buttons (previous/next) at the top and bottom of the page. That way, once I finish a page, I can immediately move on to the next.

It would also be awesome if the table of contents on the left-hand side of the page moved down as you scrolled down the page. That way you could navigate to a different section anywhere on the page, rather than having to scroll all the way to the top.

Let me know if what I'm asking for isn't clear; I'm happy to provide more context.

**Page to Update:**
https://kubernetes.io/docs/...

**Comment by tengqm** [comment]
/remove-lifecycle stale
Waiting for Hugo experts to jump in and comment.
