### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/zookeeper/ - Probe for testing for Liveness and Readiness

### ISSUE THREAD

**Issue by rgo** [kubernetes/website#7287]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Testing probes in "Testing for Liveness" and "Testing for Readiness" sections are using the bash script `zkOk.sh` but it doesn't exist anymore.

Manifest file _zookeeper.yaml_, in sections `livenessProbe` and `readinessProbe`  calls the script: `zookeeper-ready 2181` 

**Proposed Solution:**
In section: "Testing for Liveness"
  - Replace `zkOk.sh` by `zookeeper-ready 2181`
  - Replace `zkOk.sh` script content with `zookeeper-ready` content (based on this [zookeeper-ready](https://github.com/kow3ns/kubernetes-zookeeper/blob/master/docker/scripts/zookeeper-ready))
  - Where probe script is removed set the path to `/usr/bin/zookeeper-ready`

In section: "Testing for Readiness"
  - Replace `zkOk.sh` by `zookpeer-ready 2181`

**Page to Update:**
https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T21:12:46Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

I'll submit a PR associated to this issue.

**Comment by zacharysarah** [comment]
Closed by #7290
