### ISSUE TITLE
Only put people who can /approve into `approvers:` lists

### ISSUE THREAD

**Issue by fejta** [kubernetes/website#7289]
https://github.com/kubernetes/test-infra/issues/6589#issuecomment-363931180 suggests that this repo wants to ensure that docs people approve every PR.

However looking at the OWNERS files in this repo shows that devs (and only devs) are granted approval rights:
https://github.com/kubernetes/website/search?utf8=%E2%9C%93&q=filename%3AOWNERS&type=

A couple concrete examples:
https://github.com/kubernetes/website/blob/ceda4025445246e6d0f1d52b0eebdbd82d609787/docs/admin/federation/OWNERS
https://github.com/kubernetes/website/blob/ceda4025445246e6d0f1d52b0eebdbd82d609787/docs/admin/OWNERS

Anyone who is in the `approvers:` list can approve changes to those files. If you do not want this to happen change the `approvers:` list to `reviewers:`

Details on how OWNERS files work: https://github.com/kubernetes/community/blob/master/contributors/devel/owners.md

**Comment by heckj** [comment]
Thank you @fejta  - although I read the markdown on how OWNERS files work, I didn't link the behavior we were seeing to the leaf nodes in the OWNERS files that are scattered about website until you called it out and described it above. That those individuals defined in those files had approver "effects" when they used /lgtm now makes a lot more sense to me.

Regardless of what we do (or don't do) with the prow plugins, I'll update our configurations to reflect the reality of the desire - that all the various folks defined in those leaf OWNERS files are intended as requested reviewers, which will at least help this situation a bit.

/assign

**Comment by xiangpengzhao** [comment]
Another related issue is that the bot shows wrong OWNERS files path in its comment:

https://github.com/kubernetes/website/pull/7224#issuecomment-362875101

Please notice the below lines. The OWNERS files path are incorrect.

```
Needs approval from an approver in each of these OWNERS Files:
docs/concepts/cluster-administration/network-plugins.md/OWNERS
docs/getting-started-guides/rkt/index.md/OWNERS
```

**Comment by fejta** [comment]
That's weird... Could you file a test-infra bug about that and /assign it to me and @cjwagner?

**Comment by fejta** [comment]
That == bad owners file paths

**Comment by fejta** [comment]
And yeah changing devs to reviewers should make the existing plugins behave much closer to the behavior you are trying for (hopefully).

If not we can discuss what to do then...

**Comment by xiangpengzhao** [comment]
@fejta issue https://github.com/kubernetes/test-infra/issues/6710 created.

**Comment by fejta** [comment]
I'd recommend putting your doc team at /OWNERS as approvers so that they can approve all files in the repo and then add dev1 dev2 etc as reviewers at /foo/bar/OWNERS etc

That will ensure that when dev1 or dev2 does an /lgtm it will still require someone from the doc team to come in and /approve. 

Note that if a doc person gives an /lgtm it will grant both approval and lgtm, but hopefully the doc team can learn the right behavior (either just /approve or wait until a Dev does /lgtm).

**Comment by chenopis** [comment]
@fejta Thanks for the recommendations. We're working on PRs for changes to the OWNERS files now and will check in after they have been merged.

I still believe we should separate `/lgtm` from `approvers` so the behavior doesn't vary between users, but we can leave that for a discussion at a later time.

**Comment by zacharysarah** [comment]
@fejta 👋 Thanks for the explanation and recommendations. This was really helpful!
