### ISSUE TITLE
Provide a version compatibility table for the documentation/website

### ISSUE THREAD

**Issue by dlsniper** [kubernetes/website#729]
Hi,

I've found myself wanting to know which versions of flannel or etcd I should use with Kubernetes and I've realized that there's no easy way where this information can be found.
I would expect that in the readme of the version once tagged, on the website or in the documentation to have such a table but I'm not able to find it.
Could this be added for the upcoming 1.3 release forward?

Thank you.

**Comment by dlsniper** [comment]
@steveperry-53 was this fixed somehow and I've missed this? Why was this closed?

**Comment by steveperry-53** [comment]
@dlsniper, We're doing an aggressive bug bash, because we have more issues than we can handle. Perhaps I got a little heavy handed. Reopening.

**Comment by dlsniper** [comment]
@steveperry-53 all good. I think this is very relevant for users that's why I asked about it and why it was closed.

**Comment by dlsniper** [comment]
I'd like to stop being spammed with these messages, so I'll close the issue. It's pointless anyway.

/lifecycle rotten
/remove-lifecycle stale
