### ISSUE TITLE
conformance status for /docs/getting-started-guides/fedora/flannel_multi_node_cluster.md

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#7301]
Per #7278, we are looking to identify guides that are stale vs actively maintained but need work to become conformant.

From the content of [`/docs/getting-started-guides/fedora/flannel_multi_node_cluster.md`](https://kubernetes.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/) it is unclear what version of Kubernetes user will get and whether resulting cluster will be conformant or not.

PING owners/approvers/contributors @dchen1107 @aveshagarwal @eparis @thockin @steveperry-53

**Comment by errordeveloper** [comment]
This guide is dependent on [`/docs/getting-started-guides/fedora/fedora_manual_config.md`](https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/), so we should be discussing #7302 first.

**Comment by errordeveloper** [comment]
In this guide, user is asked to install `flannel` package, and the version of flannel user gets is a year old [0.7.0](https://github.com/coreos/flannel/releases/tag/v0.7.0), while the latest [0.10.0](https://github.com/coreos/flannel/releases/tag/v0.10.0) was released less than a month ago.

**Comment by errordeveloper** [comment]
If this guide migrated to `kubeadm`, it would be much smaller and compliance would be out of the question, also it could offer users an option to run any network addon as a DaemonSet.

**Comment by chrisnegus** [comment]
As suggested here, I rewrote this doc and the associated singlei-node Fedora guide to use kubeadm. See [#8009](https://github.com/kubernetes/website/pull/8009).
