### ISSUE TITLE
Readers encouraged to install deprecated xhyve hypervisor

### ISSUE THREAD

**Issue by pmallory** [kubernetes/website#7307]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Install a Hypervisor section lists xhyve as as option for OS X users. I read that it's deprecated though, at https://kubernetes.io/docs/getting-started-guides/minikube/#installation

**Proposed Solution:**
Remove the link to the xhyve driver

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by pmallory** [comment]
@chenopis :wave:

**Comment by runlevl4** [comment]
I can do a PR if @steveperry-53 hasn't started. Also looking at https://github.com/kubernetes/minikube/issues/2257 to knock them both out.

**Comment by steveperry-53** [comment]
Any work on the Minikube docs should be coordinated with @Bradamant3.
