### ISSUE TITLE
Instructions for accessing Kubernetes Dashboard don't work

### ISSUE THREAD

**Issue by pmallory** [kubernetes/website#7308]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The suggested `minikube dashboard` command doesn't work. This is located at https://kubernetes.io/docs/getting-started-guides/minikube/#dashboard

**Proposed Solution:**
I found [this doc](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard) which worked for me. We can copy the instructions to deploy and access the Dashboard UI from there to this doc.

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/minikube/#dashboard

**Comment by pmallory** [comment]
@chenopis :pineapple:

**Comment by runlevl4** [comment]
'minikube dashboard' works fine for me and launches the default browser. The issue I see with the linked page is the end of the sentence. The bolded portion isn't really accurate.  

To access the Kubernetes Dashboard, run this command in a shell after starting minikube **to get the address**:

I'd be inclined to change it to read "to launch the Dashboard:"

**Comment by steveperry-53** [comment]
@Bradamant3 is working on a complete overhaul of all the Minikube docs. Rather than making small fixes to existing documents, we should incorporate the fix into her new material.

**Comment by runlevl4** [comment]
Gotcha. I'll hang tight.
