### ISSUE TITLE
Issue with k8s.io/docs/concepts/architecture/master-node-communication/

### ISSUE THREAD

**Issue by mattayes** [kubernetes/website#7314]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The fourth paragraph of the "Cluster -> Master" section explains that master component-to-apiserver communication is currently insecure. It mentions that this will change in the future and references kubernetes/kubernetes#13598. However, this issue was closed by kubernetes/kubernetes#31491.

Does this mean this communication is now secure?

**Proposed Solution:**
If communication is secure: Rewrite/remove this paragraph.

If communication is not secure: Reopen issue.

**Page to Update:**
https://kubernetes.io/docs/concepts/architecture/master-node-communication/

**Comment by zacharysarah** [comment]
@mattayes 👋 It looks like https://github.com/kubernetes/kubernetes/pull/31491 did make communication secure. Thanks for the heads up.
