### ISSUE TITLE
Issue with k8s.io/docs/concepts/services-networking/network-policies/

### ISSUE THREAD

**Issue by juliole** [kubernetes/website#7365]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The example on the 1.7 documentation does not work. I get:
error validating data: found invalid field ipBlock for v1.NetworkPolicyPeer;

**Page to Update:**
https://v1-7.docs.kubernetes.io/docs/concepts/services-networking/network-policies/

**Comment by tengqm** [comment]
Doc team doesn't have a bandwidth or plan to actively maintain old docs.
/close
