### ISSUE TITLE
Issue with k8s.io/docs/user-guide/walkthrough/k8s201/

### ISSUE THREAD

**Issue by afakhri** [kubernetes/website#7369]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The yaml definitions files use the tag "apiVersion: apps/v1" but this not correct. Ther is an error when creating objects using thos definition files.

_Error is :_ 
Error from server (BadRequest): error when creating "deployment.yaml": Deployment in version "v2" cannot be handled as a Deployment: no kind "Deployment" is registered for version "apps/v2"

**Proposed Solution:**
Use tag "apiVersion: extensions/v1beta1"

**Page to Update:**
https://kubernetes.io/docs/user-guide/walkthrough/k8s201/

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-10T10:34:42Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-10T10:34:42Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by islinwb** [comment]
`apps/v1` works for Kubernetes v1.9 and later. `extensions/v1beta1` for v1.7 and v1.8.

**Comment by tengqm** [comment]
Looks like there was a typo from your end, @afakhri. The referenced page didn't mention "`apps/v2`" anywhere. Also please check @islinwb 's comment.
/close
