### ISSUE TITLE
Unable to make the interactive tutorial terminal full screen in Firefox

### ISSUE THREAD

**Issue by shubheksha** [kubernetes/website#7381]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When using Firefox, the full-screen button on the right-hand top corner doesn't work. On clicking, it actually shrinks the screen and makes it look like this:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/7693422/36116005-d24678d8-105a-11e8-8474-4b28f0341af3.png">

It works as expected on Chrome.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/explore-interactive/

**Comment by BenHall** [comment]
Thanks for reporting this! It looks like the new version of Firefox has changed the behaviour. We're looking into a fix now.

**Comment by BenHall** [comment]
Just doing some cleanup of stale issues. This has been fixed and can be closed.

Again, thank you for reporting the problem.

**Comment by shubheksha** [comment]
Thank you, @BenHall!
/close
