### ISSUE TITLE
Document the SupportPodPidsLimit feature

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#7386]
- [x] Feature Request
- [ ] Bug Report

**Problem:**
The SupportPodPidsLimit feature gate needs documentation.
It is about the feature enabled by this flag rather than just about the gate flag.
See kubernetes/kubernetes#57973

**Proposed Solution:**
Propose PR to release-1.10 branch and hold for release.

**Page to Update:**

Kubernetes 1.10

**Comment by dims** [comment]
cc @dims

**Comment by sftim** [comment]
/retitle Document the SupportPodPidsLimit feature

(it's the feature that needs documenting, right?)

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by mrueg** [comment]
I would like to help out documenting this. Not sure where's the best place to put it though. Do you feel this is closer to a node feature or resource limits?

**Comment by ialidzhikov** [comment]
Can someone please add a lifecycle frozen label to this issue? @sftim ?

**Comment by mrueg** [comment]
@SergeyKanzhelev provided a doc here: https://github.com/kubernetes/website/pull/23929 I think this can be closed as well?

**Comment by SergeyKanzhelev** [comment]
Wonder if I have enough permissions

/close
