### ISSUE TITLE
Automate PR Labeling, Assignments, Block-Merge

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/website#739]
We need a script that checks for the following on all open PRs and prevents submission until these tests come back clean: 
# Auto-labeling
- If user has not signed agreement, assign PR to author and label "Unsigned Author"
- If any of the above checks fail, assign PR to author and label "Check Fail"
- If both pass, label Doc Review Needed
# Auto-notifications/assignments
- Ping @johndmulhausen when author responds to PR labeled "Docs Review: Open Issues"
- Ping @johndmulhausen when open PR is labeled "Tech Review LGTM"
- Assign PR to tech review owner (as defined in front matter) when a doc they own is labeled "Tech Review Needed"
- Ping/assign to author if PR has merge conflict, or is labeled Docs Review: Open Issues, or is labeled Tech Review: Open Issues
# Block merge if...
- "Unsigned Author" label still there
- "Check Fail" label still there
- No "Docs Review LGTM" label
- Tech Review Needed label still there
- Tech Review: Open Issues label still there

**Comment by bgrant0607** [comment]
It's not sustainable for this repo to use a totally different workflow from the main repo. We're going to run the k8s-bot (mungegithub) on kubernetes.github.io.

We'll probably need to get OWNERS information from a different source, but the workflow, labels, etc. shouldn't be totally different.

**Comment by bgrant0607** [comment]
See also https://github.com/kubernetes/contrib/issues/1304
