### ISSUE TITLE
Minikube installation no longer requires a hypervisor

### ISSUE THREAD

**Issue by Capstan** [kubernetes/website#7394]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

You can use `--vm-driver=none` to use the bare host, but the docs say you need to install a hypervisor.

**Proposed Solution:**

A note akin to the one in https://github.com/kubernetes/minikube#requirements which suggests that for Linux, you can use Docker without a hypervisor. /cc @aaron-prindle who made that edit in https://github.com/kubernetes/minikube/commit/c169131970313ea4d579882cd6f24a0c63c83aff

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by aaron-prindle** [comment]
As mentioned, on linux you can use minikube w/o a hypervisor by running the kubernetes components natively via `--vm-driver=none`.  It makes sense to update the install minikube page w/ that driver option.
