### ISSUE TITLE
Documentation on scaling Jobs is incorrect and/or misleading

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/website#7395]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

The page on Jobs says 

> You can also use the scale `subresource` of the Job resource.

This is incorrect -- see https://github.com/kubernetes/kubernetes/issues/38756#issuecomment-363782231 and https://github.com/kubernetes/kubernetes/tree/master/pkg/registry/batch/job, and should just be removed.

It also says

> A job can be scaled up using the `kubectl scale` command

If the deprecation mentioned above goes through, we might want to note that it's deprecated.

cc @soltysh @kubernetes/sig-apps-misc 

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

**Comment by Jobsnguyenad** [comment]
2febd64

**Comment by aburdenthehand** [comment]
Thanks @DirectXMan12 
Looks like this was covered in #7684 and #7712 
Merged into master with #7861 and now live

I believe this issue can be closed.
