### ISSUE TITLE
Issue with k8s.io/docs/admin/bootstrap-tokens/

### ISSUE THREAD

**Issue by kapalkat** [kubernetes/website#7409]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Creating provided secret from stringData fails.
Values should be provided with quotation like so: key: "value"

**Proposed Solution:**
Add quotation to values.

**Page to Update:**
https://kubernetes.io/docs/admin/bootstrap-tokens/

1.9.1

**Comment by islinwb** [comment]
@kapalkat I think it failed to treat `true` as `"true"`. Add quotation to `true` only can solve the problem from my testing.
