### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/fedora/fedora_manual_config/

### ISSUE THREAD

**Issue by dennis1987** [kubernetes/website#7417]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
In the node configuration the line
`KUBELET_API_SERVER="--api-servers=http://fed-master:8080"`
is removed in kublet v1.6, see [here](https://github.com/coreos/coreos-kubernetes/issues/785)

**Proposed Solution:**
Add this line instead:
`KUBELET_ARGS="--cgroup-driver=systemd --kubeconfig=/etc/kubernetes/master-kubeconfig.yaml --require-kubeconfig"`

And add new config file `/etc/kubernetes/master-kubeconfig.yaml` with content:

```apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: http://fed-master:8080
users:
- name: kubelet
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
```

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/

Kubernetes Version:
Kubernetes v1.9.1

Additional Information:
Fedora 27

**Comment by scriptonist** [comment]
I'm happy to work on this. :heart_eyes:
