### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/update-interactive/

### ISSUE THREAD

**Issue by asitaram** [kubernetes/website#7418]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
After module6 next module is not launching or at least there is no indication that the entire course is complete with module6
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks! You raise a great point. I'll look at how we can improve this to add a summary page and next steps.
