### ISSUE TITLE
Issue with docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by alktlr** [kubernetes/website#7424]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Kubectl v1.9.0 has a bug where creating authentication for private registries are broken.

https://github.com/kubernetes/kubernetes/issues/57427

**Proposed Solution:**
Please update the download version to v1.9.1 or higher.

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

Kubernetes Version:
v1.9.0

**Comment by justaugustus** [comment]
This isn't necessarily a docs issue, as we do suggest first and foremost downloading the latest release.
I will admit that some of the language could be a little clearer though.

I'll pick this up and make the language a little more explicit! :)

/assign @justaugustus

**Comment by shubheksha** [comment]
Hey @justaugustus, are you still working on this?

**Comment by justaugustus** [comment]
Hey @shubheksha, I haven't gotten a chance to fix this up, so I'll pass it on to you :)
/assign @shubheksha

**Comment by jimangel** [comment]
@shubheksha are you still working on this?

**Comment by justaugustus** [comment]
@jimangel pretty sure neither of ended up grabbing this and it's a good first issue.
Your's if you want it :)

/unassign

**Comment by jimangel** [comment]
@justaugustus done. Let me know if you had something else in mind. Thanks!
