### ISSUE TITLE
Change approvers to reviewers in front matter

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#7432]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
In several topics, in the front matter, we have an approvers list. But we want to restrict our approvers list to people in sig-docs-maintainers. And we the people who are automatically suggested as approvers to be restricted to those in sig-docs-maintainers.

Here's an example:
In #7439, we have this suggestion for an approver:
"To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: enisoc
Assign the PR to them by writing /assign @enisoc in a comment when ready."

How is it that enisoc was suggested as an approver?
I suspect it's because enisoc is listed as an aprover in the front matter of custom-resources.md.

---
title: Custom Resources
approvers:
- enisoc
- deads2k
---

Here's another example in #7445:
"We suggest the following additional approvers: davidopp, jbeda, jcbsmpsn, justinsb, lavalamp, liggitt, nikhiljindal, random-liu, thockin
Assign the PR to them by writing /assign @davidopp @jbeda @jcbsmpsn @justinsb @lavalamp @liggitt @nikhiljindal @random-liu @thockin in a comment when ready."

**Proposed Solution:**
In the front matter, change the name of the list from approvers to reviewers.

**Page to Update:**
Many pages in the kubernetes.io site.
Go to /docs. grep -r approvers

**Comment by nikhita** [comment]
https://github.com/kubernetes/website/pull/8644 is still open.

/remove-lifecycle stale
