### ISSUE TITLE
Improve documentation around production Kubernetes considerations

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/website#7463]
**This is a...** 

- [x] Bug Report

**Problem:**
Based on a conversation from [SO](https://stackoverflow.com/questions/48845946/why-should-a-production-kubernetes-cluster-have-a-minimum-of-three-nodes), we'd like to make the documentation around production Kubernetes clusters more descriptive.

**Proposed Solution:**
Review and update the docs!

**Page to Update:**
- [ ] https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/
- [ ] https://kubernetes.io/docs/admin/high-availability/building/

**Comment by justaugustus** [comment]
This seems sort of related: #1733

**Comment by zacharysarah** [comment]
Go for it, @justaugustus!

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-feature-requests

**Comment by neolit123** [comment]
the HA and HA-ETC documentation received an overhaul in 1.11:
https://kubernetes.io/docs/setup/independent/high-availability/
https://kubernetes.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/

all the new edits were the result of combined SIG efforts and based on existing proposals for improvements.

closing until further notice.
/close
