### ISSUE TITLE
conformance status for /docs/getting-started-guides/ubuntu

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#7464]
Per #7278, we are looking to identify guides that are stale vs actively maintained but need work to become conformant.

From the content of [`/docs/getting-started-guides/ubuntu`](https://kubernetes.io/docs/getting-started-guides/ubuntu/) it is unclear what version of Kubernetes user will get and whether resulting cluster will be conformant or not. However, there is a subsection [on validation](https://kubernetes.io/docs/getting-started-guides/ubuntu/validation/), which indicates how user can run e2e suite, however, it doesn't say very clearly whether the users should expect e2e tests to pass when their cluster installation is correct (to some definition of correctness, of course).
On the other hand, the index page leads [Ubuntu website](https://www.ubuntu.com/kubernetes), which has a Certified Kubernetes logo.

PING owners/approvers/contributors @steveperry-53 @ktsakalozos @tvansteenburgh

**Comment by tvansteenburgh** [comment]
Thanks @errordeveloper. We do submit passing conformance results, I think we just need to clarify some of the ambiguity in the docs, as you pointed out. Thanks for the review, we'll address this soon.

**Comment by errordeveloper** [comment]
Thanks, Tim!
