### ISSUE TITLE
Cannot tell names of persistent volume reclaim policies from the docs

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#7469]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

In https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming I see 3 reclaim policies:
- Retaining
- Recycling
- Deleting

however the "kubectl explain pv.spec.persistentVolumeReclaimPolicy" says:

     What happens to a persistent volume when released from its claim. Valid
     options are Retain (default) and Recycle. Recycling must be supported by
     the volume plugin underlying this persistent volume. More info:
     https://kubernetes.io/docs/concepts/storage/persistent-volumes#reclaiming

Note that:
* strings are not matching the doc (i.e. Retain vs Retaining)
* deleting is not listed as one of the valid options on the API.

So I'm not sure if "Delete" is an actual value for this field or not, without going into the k8s source code.

**Proposed Solution:**
- Provide list of accepted values for the policy.
- Instead of "Recycling" etc, use the actual values, e.g. "Recycle"

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming

**Comment by msau42** [comment]
/assign

Also recycle is deprecated. Need to make sure the docs mention that.

**Comment by ahmetb** [comment]
Based on my experimentation `Delete` is a valid value (and in fact the default in case of dynamic volume provisioning via pvc), but it is not documented on the field description.
