### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/scratch/

### ISSUE THREAD

**Issue by bflorat** [kubernetes/website#7481]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
`configure-cbr0 `option is deprecated in Kubernetes 1.8. Which versions does  this guide target ? is it still suitable for last K8s releases ? Thanks.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/scratch/

1.8

**Comment by heckj** [comment]
@bflorat the guides are generally aimed at the latest releases, but having said that they do not universally get reviewed and updated with changes as Kubernetes releases come out. There have been a number reviewed and updated quite recently, although the scratch ones are always some of the hardest to manage. I might also recommend looking at Kelsey Hightower's [Kubernetes: The Hard Way](https://github.com/kelseyhightower/kubernetes-the-hard-way) walk through if you're interested in building from scratch

**Comment by bflorat** [comment]
Thanks Heckj. The provided manual looks like what I was looking for (even if it's GCP oriented and doesn't seem to detail the overlay configuration). The install process looks clean and weel documented, I'll have a try.

**Comment by zacharysarah** [comment]
It looks like #7518 fixed this issue; closing.
