### ISSUE TITLE
Bad content on "user journey"

### ISSUE THREAD

**Issue by saurav2104** [kubernetes/website#7482]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
https://kubernetes.io/docs/user-journeys/users/cluster-operator/advanced/

Actual content is missing.

**Proposed Solution:**
N/A

**Page to Update:**
https://kubernetes.io/docs/user-journeys/users/cluster-operator/advanced/

**Comment by zacharysarah** [comment]
@saurav2104 👋 Good catch! Stray "Lorem ipsum" in the wild...

/cc @Bradamant3, @chenopis, @steveperry-53

**Comment by chenopis** [comment]
I didn't think anything linked to that page, but I just realized now I forgot to remove it from the ToC. <facepalm> I'll take care of it.
