### ISSUE TITLE
getting TLS Handshake timeout on most requests to the api server

### ISSUE THREAD

**Issue by sumitr-tech** [kubernetes/website#7483]
I'm unable to use kubectl because of TLS handshake timeout.
 
Run `kubectl get pods` command and getting following error:

`Unable to connect to the server: net/http: TLS handshake timeout`

I also recreate cluster and try but not succeed.

**Comment by tengqm** [comment]
This is not a doc issue. Please try slack channel, stackoverflow etc. If you believe it is a k8s bug, consider file one to the kubernetes/kubernetes project then.

/close
