### ISSUE TITLE
Issue with https://kubernetes.io/docs/getting-started-guides/vsphere/#enable-vsphere-cloud-provider 

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/website#7490]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Based on comments from https://github.com/kubernetes/kubernetes-anywhere/issues/502#issuecomment-358384903 , there is no need to specify full datastore path but only datastore name is enough.

Please refer to https://groups.google.com/forum/#!topic/kubernetes-dev/XsaaHFkCLL0 for detail.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by heckj** [comment]
@gyliu513 thank you for the report, but to which documentation page are you referring?

**Comment by gyliu513** [comment]
@heckj document page is here https://github.com/kubernetes/website/blob/master/docs/getting-started-guides/vsphere.md#enable-vsphere-cloud-provider

**Comment by shubheksha** [comment]
Looks like the page you linked to doesn't exist anymore. Could you please update the bug, @gyliu513?

**Comment by gyliu513** [comment]
Close it, as the doc is now removed.

**Comment by prashima** [comment]
Just want to update that vSphere documentation was redirected and updated as part of this PR https://github.com/kubernetes/website/pull/7661 .

**Comment by shubheksha** [comment]
@prashima, has the issue been fixed in the updated docs?

**Comment by prashima** [comment]
Yes. The redirection was done to point users to updated an single document.
