### ISSUE TITLE
Glossary order is ASCII-betical

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#7491]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:** While checking the netlify preview for #7465, I noticed that the [glossary](https://kubernetes.io/docs/reference/glossary/?all=true) is in [ASCII-betical order](https://www.pcmag.com/encyclopedia/term/38025/asciibetical).

<img width="1172" alt="screen shot 2018-02-22 at 1 49 13 pm" src="https://user-images.githubusercontent.com/3210446/36566106-5d92c45e-17d7-11e8-9c24-e13a55f382ad.png">

**Proposed Solution:** Change the glossary to lexigraphical order, if possible.

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/

Kubernetes version: 1.9

**Comment by zacharysarah** [comment]
@abiogenesis-now 👋 It looks like the ordering logic is in the [glossary markdown](https://github.com/kubernetes/website/blob/53cf7defd51bfe74f84f1e3b1998e9a854166f1a/docs/reference/glossary.md). 

After a little research, it looks like Jekyll default sorts by ASCII. Others have wrestled with natural case sort too:
- https://stackoverflow.com/questions/1408824/an-easy-way-to-support-tags-in-a-jekyll-blog/21002505#21002505
- http://mahiwaga.pw/2015/07/07/tags-in-jekyll

It looks like Liquid may have natural case sorting: 
- https://github.com/Shopify/liquid/commit/03b3446119c83e5c89e3b7207042d1c1f6756917

**Comment by sdague** [comment]
In my tests, and the patch that's up, sort_natural does work as expected.

**Comment by sdague** [comment]
This should be closed now, I apparently used the wrong keyword string.
