### ISSUE TITLE
Redirecting kubernetes/kubernetes-bootcamp to Website

### ISSUE THREAD

**Issue by BenHall** [kubernetes/website#7506]
This was raised within the 2/27/2018 Sig-Docs meeting. The original aim of https://github.com/kubernetes/kubernetes-bootcamp was to be a separate site, however the content has been merged into the main Kubernetes website as https://kubernetes.io/docs/tutorials/kubernetes-basics/

However, the site is still active at https://kubernetesbootcamp.github.io/kubernetes-bootcamp/ 

This has lead to confusion by users (https://github.com/kubernetes/kubernetes-bootcamp/issues/54)

Problem:
   Users are confused by kubernetes bootcamp repo which is no longer maintained. Users raise PRs/issues which are not actioned which potentially looks bad to the community.

Suggestion:
- [ ] Update kubernetesbootcamp.github.io to redirect users to kubernetes.io/docs/tutorials/kubernetes-basics page. Alternatively, add a banner at the top to suggest the main website content.
- [ ] Update README to indicate the repository is no longer active and direct people here
- [ ] Make repository read-only

Benefit:
  Users are clear where the main content for Kubernetes documentation is and how to suggest improvements.

Paging @steveperry-53 who has more understanding of the background to the repo and best way to manage this.

**Comment by BenHall** [comment]
Related PR: https://github.com/kubernetes/kubernetes-bootcamp/pull/56#issuecomment-368963925

**Comment by steveperry-53** [comment]
I like the idea of redirecting the content at kubernetesbootcamp.github.io. But I don't know how to do it. Do any of the rest of you know how to do the redirection?

**Comment by chenopis** [comment]
I found this posting about using a `CNAME` folder inside of your repo to do the redirect: https://stackoverflow.com/questions/30167113/redirect-github-pages-to-custom-domain

**Comment by BenHall** [comment]
@steveperry-53 Sorry, I thought I had sent another PR. Will update soon.
