### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by sridharsikha** [kubernetes/website#7513]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
curl http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAM
Curl(7) connection refused
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks for the feedback. The correct command should be $POD_NAME not $POD_NAM. Was this a copy/paste error?

**Comment by heckj** [comment]
hi @sridharsikha - I just ran through the tutorial and clicked on all of the execution steps, and it worked straight through, including using the curl to access the pod through the proxy, which you seem to be indicating isn't working above.

If you were typing in the above, then I might point out that the variable `$POD_NAM` is truncated, and hence wouldn't resolve if you used the correct name.

**Comment by sridharsikha** [comment]
I wasnt doing control paste - but do i need to do the module1 2 3 in
sequence ??

Cheers & Regards,
Sridhar Sikha
408 506 0576
<https://www.linkedin.com/in/sridharsikha/>

**Comment by BenHall** [comment]
@sridharsikha No, each module begins with the target state from the previous module.

Could you give it another go and see if you have the same result?? You need to ensure that the `kubectl proxy` is running as that's what is listening on port 8001

**Comment by sridharsikha** [comment]
ok - send me the URL -
how do i make sure proxy is running - ps -ef | grep 8001


Cheers & Regards,
Sridhar Sikha
408 506 0576
<https://www.linkedin.com/in/sridharsikha/>

**Comment by zacharysarah** [comment]
@sridharsikha 👋 Feel free to re-open this issue if you continue to have difficulty.
