### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by rajinder-yadav** [kubernetes/website#7517]
Install kubectl using homebrew.

**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Having problem running kubectl, I install minikube and tried this command, still same error? I don't see anything mentioned about this in the doc: https://kubernetes.io/docs/tasks/tools/install-kubectl/

```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Proposed Solution:**

Improve and streamline the getting started doc, one single doc showing how to get up a local running environment. Making people jump to different pages and bounce around is lame.

**Page to Update:**
https://kubernetes.io/...

**Comment by zacharysarah** [comment]
@rajinder-yadav 👋 
> Improve and streamline the getting started doc, one single doc showing how to get up a local running environment. Making people jump to different pages and bounce around is lame.

That's real. Thanks for the feedback!

/cc @Bradamant3 for minikube

**Comment by rajinder-yadav** [comment]
Did anyone do something about this issue, like update the docs as suggested.

**Comment by hexecute** [comment]
The instructions do exist on the page, though they're a little nested and hard to get to.  

> For example, if you are intending to run a Kubernetes cluster on your laptop (locally), you will need a tool like minikube to be installed first and then re-run the commands stated above.   

I'm imagining that this is a common user flow for people testing out Kubernetes.  

# Install Kubectl on their local machine
# Run a Kubectl command like `kubectl version`  

The main problem is that the installation instructions for each OS say to follow these two steps. In the section "Check the kubectl configuration", it explains that there's actually a third intermediate step.
