### ISSUE TITLE
Disable the "Reviewable" button and review access enabled for kubernetes/website

### ISSUE THREAD

**Issue by heckj** [kubernetes/website#7552]
**Problem:**

Following up on "how to contribute to Docs", there have been a few instances where people utilize Reviewable that's posted into the PRs as a means of reviewing, and then the PR gets stuck in automation - /lgtm and /approve tags don't allow it to merge, because Reviewable asserts there's outstanding discussions. It doesn't happen frequently, but in a poll on the SIG Docs channel, we aren't using it as the maintainers, and find it complicates our reviews rather than helps us. Clearing the reviews and conversation so we can marge doesn't appear to be something that repo maintainers (or at least I) can do - it apepars to require everyone who was involved in the conversation to clear it for themselves.

**Proposed Solution:**

Disable Reviewable to the kubernetes/website repo

**Comment by spiffxp** [comment]
/assign
I wasn't around while this was setup and am not super clear on it, but I do have privs and incentive to disable this, so going to proceed slowly.

Disabled the reviewable webhook on this repo: https://github.com/kubernetes/website/settings/hooks/10967055

https://reviewable.kubernetes.io/repositories still shows it as connected, will try disconnecting when I've seen more +1's from those you've cc'ed

**Comment by chenopis** [comment]
+1 +1 +1 +1 +1... 😄

**Comment by heckj** [comment]
up votes for disabling in slack from jared, zach and steve as well.

**Comment by heckj** [comment]
https://kubernetes.slack.com/archives/C1J0BPD2M/p1519843896000443

https://kubernetes.slack.com/archives/C1J0BPD2M/p1519844567000309

**Comment by spiffxp** [comment]
/close
Disabled, ref https://github.com/kubernetes/community/issues/1881
