### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/cluster-intro/

### ISSUE THREAD

**Issue by DraconPern** [kubernetes/website#7556]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
minikube documentation says it creates a cluster.  However this is factually incorrect since minikube only supports one node.

**Proposed Solution:**
Change 'cluster' to 'environment' for minikube documentation

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/
https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-interactive/

**Comment by zacharysarah** [comment]
@DraconPern 👋 From https://kubernetes.io/docs/tutorials/kubernetes-basics/cluster-intro/: 

> Minikube is a lightweight Kubernetes implementation that creates a VM on your local machine and deploys a simple cluster containing only one node.

For another example of a single-node cluster (using kubeadm), check out: https://github.com/kelseyhightower/kubeadm-single-node-cluster
