### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose-intro/

### ISSUE THREAD

**Issue by ronan-mch** [kubernetes/website#7558]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The Legend on the Services and Labels diagram calls Containers (identified as purple boxes) Pods

**Proposed Solution:**
Change Pods to Containers in Legend and add an extra entry for Pods, symbolised with a green circle.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-intro/

**Comment by zacharysarah** [comment]
@ronan-mch Can you say more specifically about why Pods is inaccurate here?
