### ISSUE TITLE
behavior of `kubectl delete all` is essentially undocumented

### ISSUE THREAD

**Issue by pmorie** [kubernetes/website#7559]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

I'm working on adding the 'all' category to some resources in service-catalog, and found that the expected behavior of `kubectl delete all` is undocumented. For example, the kubectl reference doc for delete doesn't touch on 'all' in any way: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#delete

I found this to be fairly confusing when trying to learn what exactly the expected behavior is.

**Proposed Solution:**

We should have some treatment, possibly a special note, explaining the 'all' category and how `kubectl get` and `kubectl delete` are expected to behave wrt to `all`.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#delete
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get

**Comment by juanvallejo** [comment]
cc @kubernetes/sig-cli-bugs @kubernetes/sig-cli-misc

**Comment by mengqiy** [comment]
Actually it is documented here https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#rules-for-extending-special-resource-alias---all.
But it may be hard to find.

**Comment by pmorie** [comment]
@mengqiy you're right - it is documented in a hard to find place. I'm going to see if we can link to it from more places.
