### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/website#7577]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
With deployments in Kubernetes 1.8+ The generated ReplicaSet and subsequent Pod names no longer contains the same value has as the `POD-TEMPLATE-HASH` label.

The value used in the generation of the ReplicaSet and Pod names goes through the [SafeEncodeString](https://github.com/kubernetes/kubernetes/blob/5cff6c9091073ce0e70d81e6dfe0b5633cc82060/staging/src/k8s.io/apimachinery/pkg/util/rand/rand.go#L112-L120) function whereas the label itself does not.

e.g. 
```
$ kubectl get deployment --show-labels
NAME             DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       LABELS
example-deploy   3         3         3            3           4s        example=true

$ kubectl get rs --show-labels
NAME                      DESIRED   CURRENT   READY     AGE       LABELS
example-deploy-85479d4d   3         3         3         13s       example=true,pod-template-hash=41035808

$ kubectl get pods --show-labels
NAME                            READY     STATUS    RESTARTS   AGE       LABELS
example-deploy-85479d4d-bcqjr   1/1       Running   0          20s       example=true,pod-template-hash=41035808
example-deploy-85479d4d-nsmfr   1/1       Running   0          20s       example=true,pod-template-hash=41035808
example-deploy-85479d4d-rlxms   1/1       Running   0          20s       example=true,pod-template-hash=41035808
```
The ReplicaSet and Pod names contain the hash `85479d4d` while the pod-template-hash label is `41035808`

**Proposed Solution:**
Update both the section referencing `[DEPLOYMENT-NAME]-[POD-TEMPLATE-HASH-VALUE]` and the various `nginx` deployment examples to reflect that the difference in hashing methods.

**Page to Update:**
https://kubernetes.io/...

Kubernetes Version: 1.8+

Additional Information:
https://github.com/kubernetes/kubernetes/issues/55346

**Comment by islinwb** [comment]
@mrbobbytables  I'll update the related docs.
/cc @islinwb

**Comment by janetkuo** [comment]
Oops, I think that's a bug in deployment controller.

**Comment by mrbobbytables** [comment]
@janetkuo should the original issue https://github.com/kubernetes/kubernetes/issues/55346 be reopened? I can close the open PR for updating the docs if that wasn't intended.

**Comment by janetkuo** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/66093 for this bug and a fix for it.

**Comment by mrbobbytables** [comment]
Awesome! I'll close out the PR on fixing the docs. Thanks for being on top of it :)
