### ISSUE TITLE
Issue with k8s.io/docs/admin/extensible-admission-controllers/

### ISSUE THREAD

**Issue by cindy52** [kubernetes/website#7616]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
The document 1.9 doesn't compatible for kubernetes v1.9. Admission changed to v1beta1. ExternalAdmissionHookConfiguration changed to MutatingWebhookConfigurations and ValidatingWebhookConfigurations.

**Proposed Solution:**
Update the documents based on the version 1.9

**Page to Update:**
https://kubernetes.io/docs/admin/extensible-admission-controllers/

**Comment by zacharysarah** [comment]
@smarterclayton, @lavalamp, @whitlockjc, @caesarxuchao 👋

Has extensible webhook admissions graduated from [alpha](https://kubernetes.io/docs/admin/extensible-admission-controllers/)? Looking at the [Workloads API updates](https://kubernetes.io/docs/reference/workloads-18-19/) for 1.8/1.9 and at the [API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#pod-v1-core), it's not immediately clear.

Thanks in advance for your help!

**Comment by lavalamp** [comment]
Yes, and there is a PR out to fix the documentation already I believe.

**Comment by caesarxuchao** [comment]
It's https://github.com/kubernetes/website/pull/7586

**Comment by zacharysarah** [comment]
Thanks, @caesarxuchao! 

Closing in favor of #7002/#7586
