### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by larsf** [kubernetes/website#7625]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
kubectl proxy hangs

The output in the window looks like this:

$ kubectl proxy
Starting to serve on 127.0.0.1:8001

but you never get the prompt back
**Proposed Solution:**
Fix it so it doesn't :-) 

**Page to Update:**
https://kubernetes.io/...

**Comment by larsf** [comment]
It actually might help if you put this comment above where you ask people to run the proxy
Note: Check the top of the terminal. The proxy was run in a new tab (Terminal 2), and the recent commands were executed the original tab (Terminal 1). The proxy still runs in the second tab, and this allowed our curl command to work using localhost:8001.

Only later did I discover the terminal1 vs 2 issue and the fact the kubectl proxy doesn't return :-)

**Comment by BenHall** [comment]
Thanks. I'll take another look at how we can describe the `kubectl proxy` behaviour based on your suggestions.
