### ISSUE TITLE
Guide on Migrating Applications to Kubernetes

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/website#7644]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
People are trying to migrate their applications to Kubernetes and would like a guide on how to do it.

**Proposed Solution:**
There are several people interested in writing such a guide and it was suggested that should should live in the Kubernetes documentation (e.g., [here](https://groups.google.com/forum/#!topic/kubernetes-sig-apps/c1JIjI6Jvb0)). This issue is to provide a starting point to discuss and work out any logistics.

**Page to Update:**
I'm not sure where this multi-page guide should go. Any pointers?

Are there any suggestions on how one would start writing a multi-page guide to initially land it?

**Comment by zacharysarah** [comment]
@mattfarina 👋 I'm glad to see a proposal for this! The best way to propose a migration guide is to open a pull request. Be sure to follow the [docs contributor guidelines](https://kubernetes.io/editdocs/). 

Based on what you're describing, I'd propose adding a new header under [Setup](https://kubernetes.io/docs/setup/). 

Concentrate at first just on getting content up for discussion and review. Don't worry too much about failing build tests; we can address those once the content is solid.

I look forward to seeing a PR soon!

**Comment by heckj** [comment]
@mattfarina You'd mentioned a desire to see this localized (translated) to at least one other language as well - can you share a few more details of what you were after/hoping to achieve and wanted to create? Hopefully the tutorials template will cover most of what you want, but it hasn't been exercised heavily since it's inception, so we might need to tweak or twiddle it...

**Comment by zacharysarah** [comment]
@heckj That's real feedback about the tutorials template. Honestly, I think it belongs under Setup; I'm just concerned about providing enough structure to help a writer succeed.

**Comment by mattfarina** [comment]
Thanks for all the feedback, folks.  What I was initially envisioning doesn't fit in the format for the k8s docs. Going to see what we can put into the format you have.

**Comment by heckj** [comment]
@mattfarina would still very much like to know what you had evisioned. i suspect you’ve spoken about it to a few people, but i haven’t caught it and would like to know - and possibly help.

**Comment by mattfarina** [comment]
/reopen

I don't think this needs to be closed just yet. We're going to see what we can do here.

**Comment by heckj** [comment]
Apologies - didn't mean to close this, was a mistake while I was looking at issues in a mobile browser
