### ISSUE TITLE
Issue with k8s.io/docs/setup/hosted-solutions/overview/

### ISSUE THREAD

**Issue by pmallory** [kubernetes/website#7673]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
This place holder content was inadvertently published as part of  #4630 

**Proposed Solution:**
Remove the page, and update website/_data/setup.yml to use a different landing page

**Page to Update:**
https://kubernetes.io/docs/setup/hosted-solutions/overview/

**Comment by pmallory** [comment]
@chenopis Question about https://github.com/kubernetes/website/blob/master/_data/setup.yml#L30

What's a more appropriate landing page? `/docs/setup/pick-right-solution/`?
And where can I learn about how the yaml files in _data work?

**Comment by chenopis** [comment]
@pmallory More specifically: `/docs/setup/pick-right-solution/#hosted-solutions`.
