### ISSUE TITLE
Stale docs - Extensible admission controllers

### ISSUE THREAD

**Issue by lachie83** [kubernetes/website#7676]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**

https://github.com/kubernetes/website/blob/master/docs/admin/extensible-admission-controllers.md

The external-admission-webhooks section of these docs are stale for Kubernetes >= 1.9 and need to include the v1beta1 API along with Validating and Mutating Webhook changes.

**Proposed Solution:**

Update based on changes introduced in Kubernetes 1.9

**Page to Update:**
https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks

**Comment by islinwb** [comment]
The update (https://github.com/kubernetes/website/pull/7586) is on the way.

**Comment by islinwb** [comment]
#7586

**Comment by islinwb** [comment]
#7586

**Comment by lachie83** [comment]
Fantastic! Thanks

**Comment by zacharysarah** [comment]
Fixed by https://github.com/kubernetes/website/pull/7733, closing.
