### ISSUE TITLE
Issue with k8s.io/docs/user-guide/walkthrough/

### ISSUE THREAD

**Issue by rmorrise** [kubernetes/website#7686]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

The docs give the following command:

`$ kubectl create -f docs/user-guide/walkthrough/pod-nginx.yaml`

However, there is no YAML file with this name in `kubernetes/examples`

There are multiple ways I can work around this (copy from clipboard above, or click on the link to download), but the lack of this file from the kubernetes repo made me think I did something wrong in a previous step. I noticed that the file path given matches the link URL:
https://kubernetes.io/docs/user-guide/walkthrough/pod-nginx.yaml
...so I was confused about why I couldn't find it in my cloned copy of the docs.

I included my terminal log below so you can see what I was trying to do.

**Proposed Solution:**

At the top where it says "make sure you have the example directory locally", provide specific instructions (git clone ...) Is there a separate docs repo I should have cloned instead of the kubernetes main repo to get the walkthrough files? If so, it should be referenced here.

If the path given in the docs for this YAML file is incorrect or out of date, the docs should also be updated to reflect this.

**Page to Update:**
https://kubernetes.io/docs/user-guide/walkthrough/

I looked for this YAML file on both the master branch and release-1.10

```
rmorrise@rmorrise-003936 MINGW64 /d/src/github
$ git clone https://github.com/kubernetes/kubernetes.git
Cloning into 'kubernetes'...
remote: Counting objects: 728506, done.
remote: Compressing objects: 100% (138/138), done.
remote: Total 728506 (delta 78), reused 61 (delta 60), pack-reused 728308
Receiving objects: 100% (728506/728506), 528.49 MiB | 25.48 MiB/s, done.
Resolving deltas: 100% (497121/497121), done.
Checking connectivity... done.
Checking out files: 100% (16499/16499), done.

rmorrise@rmorrise-003936 MINGW64 /d/src/github
$ cd kubernetes/examples/

rmorrise@rmorrise-003936 MINGW64 /d/src/github/kubernetes/examples (master)
$ kubectl create -f docs/user-guide/walkthrough/pod-nginx.yaml
error: the path "docs/user-guide/walkthrough/pod-nginx.yaml" does not exist

rmorrise@rmorrise-003936 MINGW64 /d/src/github/kubernetes/examples (master)
$ cd ..

rmorrise@rmorrise-003936 MINGW64 /d/src/github/kubernetes (master)
$ kubectl create -f docs/user-guide/walkthrough/pod-nginx.yaml
error: the path "docs/user-guide/walkthrough/pod-nginx.yaml" does not exist

rmorrise@rmorrise-003936 MINGW64 /d/src/github/kubernetes (master)
$ find . -name "pod-nginx.yaml"

rmorrise@rmorrise-003936 MINGW64 /d/src/github/kubernetes (master)
```

**Comment by islinwb** [comment]
@rmorrise The yamls used in https://kubernetes.io are in repo https://github.com/kubernetes/website.git.

**Comment by rmorrise** [comment]
@islinwb OK, thanks! Can the docs be updated to mention this?

**Comment by drx777** [comment]
Ran into the same issue and ended up running `examples/https-nginx/nginx-app.yaml`.

I suggest proposing to clone the website repo or as an alternative for users with svn:
`svn export https://github.com/kubernetes/website/trunk/docs/user-guide/walkthrough`
