### ISSUE TITLE
Typo/error in the wiki's navbar's template

### ISSUE THREAD

**Issue by Nodraak** [kubernetes/website#7692]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In the [wiki](https://kubernetes.io/docs/), the navbar menus "Home" and "Reference" are not highlighted like the others. [Setup is highlighted](https://kubernetes.io/docs/setup/) while [home is not highlighted](https://kubernetes.io/docs/home/).

**Proposed Solution:**

Theses files needs to be fixed:

* https://github.com/kubernetes/website/blob/1e5bb1f8dedb4787303aa40790ca33b2746d14ed/_layouts/docsportal.html#L16
* https://github.com/kubernetes/website/blob/1e5bb1f8dedb4787303aa40790ca33b2746d14ed/_layouts/docwithnav.html#L25
* https://github.com/kubernetes/website/blob/1e5bb1f8dedb4787303aa40790ca33b2746d14ed/_layouts/docsportal.html#L21
* https://github.com/kubernetes/website/blob/1e5bb1f8dedb4787303aa40790ca33b2746d14ed/_layouts/docwithnav.html#L30

For example, "toc.bigheader"'s value is "Reference" instead of "Reference Documentation".

**Page to Update:**
None? (you mean, update the docs for a feature request?)

---

I can submit a PR, but I don't know if I should edit the above-mentioned files and submit the PR against this repo, or somewhere else (other files, other repo?). Please tell me what I should do.

**Comment by zacharysarah** [comment]
@Nodraak 👋 
> I can submit a PR, but I don't know if I should edit the above-mentioned files and submit the PR against this repo, or somewhere else (other files, other repo?). Please tell me what I should do.

Thanks for the bug, and thanks in advance for the PR! Take a look at our [contribution process](https://kubernetes.io/editdocs/).
