### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/coreos/bare_metal_offline/

### ISSUE THREAD

**Issue by Prodian0013** [kubernetes/website#7702]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
kube-register is no longer available at the link in the documentation.

wget -O kube-register  https://github.com/kelseyhightower/kube-register/releases/download/v0.0.2/kube-register-0.0.2-linux-amd64

**Proposed Solution:**
Unknown

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/coreos/bare_metal_offline/

**Comment by rajeshneo** [comment]
@Prodian0013 Did you found any alternative link meanwhile?

**Comment by Prodian0013** [comment]
@rajeshneo unfortunately not yet.

**Comment by zacharysarah** [comment]
@Prodian0013 All of the Getting Started Guides are woefully out of date. There are open PRs in process, both in k8s/website (for example, #6859) and in k8s/community to either freshen or remove content. This may not be quick work, but it's ongoing. Hope that helps!

**Comment by Prodian0013** [comment]
@zacharysarah thanks for the update on this issue.
