### ISSUE TITLE
No “dark mode”

### ISSUE THREAD

**Issue by kmathmann** [kubernetes/website#7724]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
No DarkMode / DarkTheme

**Proposed Solution:**
 A DarkMode like the docker website provides it.  
The dark colors makes the website much enjoyable to read.

**Page to Update:**
https://kubernetes.io/...

# Additional Information
https://docs.docker.com/

![image](https://user-images.githubusercontent.com/16414395/37334707-edf499da-26ac-11e8-9253-8a80252bff2c.png)

`background-color: #101e26`
`color: #d3d4d4`

![image](https://user-images.githubusercontent.com/16414395/37334781-1f1a8cc2-26ad-11e8-98f8-bf79df505ba4.png)

**Comment by sftim** [comment]
See https://github.com/kubernetes/website/issues/25061

/close not-planned

**Comment by sftim** [comment]
Duplicated by https://github.com/kubernetes/website/issues/46844

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/issues/37444
