### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/coreos/bare_metal_offline/

### ISSUE THREAD

**Issue by rajeshneo** [kubernetes/website#7785]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Broken Link
wget -O kube-register  https://github.com/kelseyhightower/kube-register/releases/download/v0.0.2/kube-register-0.0.2-linux-amd64

wget -O kube-register  https://github.com/aputs/kube-register/releases/download/v0.0.2/kube-register-0.0.2-linux-amd64
--2018-03-19 18:41:15--  https://github.com/aputs/kube-register/releases/download/v0.0.2/kube-register-0.0.2-linux-amd64
Proxy request sent, awaiting response... 404 Not Found
2018-03-19 18:41:16 ERROR 404: Not Found.

**Proposed Solution:**
Provide new link

**Page to Update:**
https://kubernetes.io/...

**Comment by sdague** [comment]
This looks like unmaintained code. Kelsey has deleted his repository, and aputs doesn't have releases on theirs. Perhaps the page should just be deleted?

**Comment by errordeveloper** [comment]
@sdague it's crazy how old this one is!

**Comment by zacharysarah** [comment]
Duplicate issue; closed by #7821. 

@sdague 👍
