### ISSUE TITLE
kubernetes.io/community website

### ISSUE THREAD

**Issue by parispittman** [kubernetes/website#7795]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
Spoke to @zacharysarah about this issue; it's not the highest priority but wanted to get it on the books and out of my head. 

The current community site needs some design work and a better layout. It's currently not rendering properly on a lot of mobile browsers. I suspect it has to do with the calendar.

Community here would mean users + contributors vs just contributors. Question that the site should answer - how can users and contributors get a high level glance into our community resources and plug in where necessary?

The calendar is currently labeled SIGs but it also includes other non-sig related events. 

**Proposed Solution:**
Unfortunately I have 0 proposed solutions here. Could we include this in the site transition to Hugo work?

It would be good to lay out content in not paragraph form but quick glances very similar to the bottom of the page like -
Connect with us:
[slack icon with copy under about k-users and k-dev channels]
[twitter icon with the same copy as current]
[email icon for k-dev and k-users mailing lists]
[youtube community - highlight user office hours]
[contributor site link when created]
[stackoverflow link with the same copy as current]
[I'm missing some others but this is off the top of my head]

Join us:
[icon for weekly community meeting and doc link to support it with copy suggesting "weekly demos, SIG updates, announcements, and more!"]
[better calendar view that has a better skin then the current gcal embed with an easier way for folks to add to their calendars]
[meetup API sync with k8s and CNCF meetups]

Also include "unofficial" resources like the [Kubernetes AWESOME list.](https://github.com/ramitsurana/awesome-kubernetes) 

https://www.cncf.io/events/ -> if we could get this style, it would be a vast improvement. There are so many meetings so viewing by week is best and then monthly view for the user to toggle.

Maybe even tie the style into our values somehow in a creative way. ie - transparency will display the calendar.

**Page to Update:**
https://kubernetes.io/community

**Comment by heckj** [comment]
:wave: hey @parispittman - are you thinking about this as it relates to https://github.com/kubernetes/community/blob/master/keps/sig-contributor-experience/0005-community-site.md? I wasn't sure if that effort would replace the above link, or be an entirely separate site that the /community/ page links over towards. Any preferences or desires?

I'm honestly not sure we're really capturing mobile well on the documentation focused pieces either FWIW

**Comment by parispittman** [comment]
This would be different. This is the site as it stands now at kubernetes.io/community and the KEP above would be for something like contributors.k8s.io. Community in our world means users and contributors (the whole pie).

**Comment by zacharysarah** [comment]
@parispittman 👋 
> Could we include this in the site transition to Hugo work?
Possibly! I think (hope?) it would be a temporary measure on the road to a fuller, more robust replacement. Like you mention, that's an ongoing discussion. I agree with @heckj that we're not really serving mobile content well for anyone/with anything.

**Comment by heckj** [comment]
@parispittman dummy question - are the CNCF events managed in Google Calendar? I think part of what's happened today is that we took the quick & obvious way of just embedding that into our web page and moved on. I'll take it up to dig around and see how else we might read from Google calendar and display it differently!

**Comment by parispittman** [comment]
assign @kbarnard10

**Comment by parispittman** [comment]
Update - Alex C and Kaitlyn B from CNCF/LF are going to do a mock. I assigned Kaityln to this issue. We will discuss the mock in the next 1-2 weeks in the ContribEx and Docs weekly update calls and post here.

**Comment by kbarnard10** [comment]
Here is the first round of mockups:
[kubernetes-community (3).pdf](https://github.com/kubernetes/website/files/2182633/kubernetes-community.3.pdf)

**Comment by castrojo** [comment]
These look great, one thing we should consider is adding in more dynamic content that shows how active the community is currently, like tweets and discussions. 

As mentioned in the meeting if these dynamic elements require other work we should scope them but not block on them, I feel like even in the prototype stage these are already heads and shoulders above what we have now. Thanks for working on this!

**Comment by dankohn** [comment]
It's easy to embed the last 3 tweets from @kubernetesio.
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview.html

That's what we do for https://landscape.cncf.io/selected=kubernetes

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by parispittman** [comment]
+1 to Jorge. The only P0 that should block an initial roll out is the calendar. Love the direction of this. 

Also some comments:
-no need for SIG related detailed info on here (like the list). We will house that stuff in the new contributor site. we do need to put in a placeholder for a way to advertise that site without just throwing a link up.
-Can you include discuss.kubernetes.io as a top resource? And an "unofficial resource" link to the AWESOME site? It's jam packed with good info. 
-Can we also add a placeholder for the code of conduct and maybe a blurb (tbd) about it's importance? Once the steering committee finalizes the values, this could be a good place for them, too.

**Comment by parispittman** [comment]
Update: Alex from CNCF presented the updated mock ups in the [last contribex meeting](https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit#) on 8/1/2018 (link accessible if you are a member of contribex or docs mailing lists) 

will provide an update in the next docs weekly update call

**Comment by castrojo** [comment]
/remove-lifecycle stale

This is still happening, just waiting to sync with Alex when she comes back from holiday.

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale

This should be picking back up soon.

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale
Removing stale, but I think this can be closed now. The community page itself has been updated:
ref: https://github.com/kubernetes/community/issues/3388
ref: https://github.com/kubernetes/website/pull/13046

/assign @parispittman 
For ack on if it can be closed or next steps.

**Comment by mrbobbytables** [comment]
Going to go ahead and close. Further refinement of the community page is occurring in other issues (ref #14061).
Please reopen if needed 👍 

/close
