### ISSUE TITLE
Upper right dropdown is not working

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#7801]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The upper right navigation bar is meant to show a dropdown list for versions supported.
However it does not work as expected.

**Proposed Solution:**
fix it.

**Page to Update:**
https://kubernetes.io/docs/
![screen shot 2018-03-21 at 9 10 59 am](https://user-images.githubusercontent.com/5094756/37690766-25cd3dee-2ce8-11e8-95e3-47729d80d1d6.png)

**Comment by zacharysarah** [comment]
@tengqm Are you still seeing this? I'm able to select versions without difficulty.

**Comment by tengqm** [comment]
@zacharysarah yes, it is still there. I'm using Safari, btw.

**Comment by heckj** [comment]
I see the same thing with Safari = the page renders/works differently in Chrome, but utterly fails with Safari. It also works with Firefox (just tested it)

**Comment by nickchase** [comment]
I took a look and you can fix it by adding `overflow: visible` to the header element, but if you do that there's a bunch of stuff that will suddenly appear that probably doesn't need to, so you'll need to take a look at it.
