### ISSUE TITLE
Mount propagation `MountFlags` dependency should be documented 

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/website#7805]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Mount propagation for Kubernetes moved to beta in 1.10. Documentation was updated here: https://github.com/kubernetes/website/pull/7655

However on some deployments it won't work unless `MountFlags=shared` is added to `/usr/lib/systemd/system/docker.service` or `MountFlags=slave` is removed.

This is documented in the Portworx docs: https://docs.portworx.com/knowledgebase/shared-mount-propogation.html#redhatcentos-configuration-and-shared-mounts 

**Proposed Solution:**

Kubernetes OSS documentation should be updated to explain this and have a similar how-to for different environments. 

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation

1.9, 1.10+

/assign @jsafrane

**Comment by vladimirvivien** [comment]
Submitted PR https://github.com/kubernetes/website/pull/7854

**Comment by saad-ali** [comment]
Closed with https://github.com/kubernetes/website/pull/7854
