### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/encrypt-data/

### ISSUE THREAD

**Issue by wattli** [kubernetes/website#7806]
**This is a...** 

- [ x ] Feature Request

**Problem:**
I am a GKE user, and seems you can't change the flag of kube-apiserver, then how can I set "experimental-encryption-provider-config" and try out this feature? Do we have a counter part for GKE?

**Comment by wattli** [comment]
And where can i find whether experimental-encryption-provider-config is enabled in a specific GKE version? Thanks

**Comment by tengqm** [comment]
Closing this because it is neither a feature request nor a bug report for documentation.
For GKE usage questions, you may want to try for example stackoverflow (https://stackoverflow.com/questions/tagged/google-cloud-platform) or GKE support (https://cloud.google.com/community/#home-support), etc.
