### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by nbalakrishnan** [kubernetes/website#7820]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Interactive Tutorial Module 2 step 3 has a bug in the instructions. The command "curl http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAME/" produces an error:

Error: 'dial tcp 172.17.0.6:8080: getsockopt: connection refused'
Trying to reach: 'http://172.17.0.6:8080/'

**Proposed Solution:**

The correct command is "curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/" -- the "/proxy" in the URL is the cause of the error.

**Page to Update:**
https://kubernetes.io/...

**Comment by Tressflin** [comment]
Oddly the "/proxy" part has now gotten moved to the end of the URL, causing the same error as initially reported.  However, this isn't immediately obvious as the command box isn't set to wrap text.  The correct command in the proposed solution above works.
