### ISSUE TITLE
Documentation on taint-based pod evictions implies respect of PDBs, which may not be the case

### ISSUE THREAD

**Issue by omkensey** [kubernetes/website#7829]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Documentation on taint-based pod evictions is unclear and possibly misleading.

**Proposed Solution:**
Clarify what mechanism is used to empty nodes of pods that don't tolerate a NoExecute taint effect.

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#taint-based-evictions

1.9

The documentation of taint-based evictions uses the word "evict" which to a user familiar with the /eviction subresource or the Eviction policy construct implies that these evictions will respect PodDisruptionBudgets.  Instead, looking at the code in `pkg/controller/nodelifecycle/scheduler/taint_manager.go`, I see:

`tm.taintEvictionQueue = CreateWorkerQueue(deletePodHandler(c, tm.emitPodDeletionEvent))`

where earlier in the file, `deletePodHandler` contains:

`err = c.CoreV1().Pods(ns).Delete(name, &metav1.DeleteOptions{})`

This seems to say that when pods are evicted because of an untolerated taint, they are simply deleted and therefore tainting a node may cause PDBs to be violated.  This could be a nasty surprise for somebody expecting a soft landing due to PDBs they have created.

**Comment by moizrassiwala** [comment]
Any update on this? Does taint based eviction simply delete the pod without graceful termination of the pod and without calling prestop hook?
