### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by gzcwnk** [kubernetes/website#7863]
**This is a documentation issue**

- [ ] Feature Request

**Problem:**

Poorly worded install instructions.

**Proposed Solution:**

improve it please.
**Page to Update:**

https://kubernetes.io/docs/setup/independent/install-kubeadm/

I find that this section,

"Configure cgroup driver used by kubelet on Master Node"

is very poorly explained, can it be expanded and improved to make it clear what to do please, thanks

**Comment by neolit123** [comment]
NAK.

i would say that the `cgroup` driver part is sufficient.
all the details important to the end user are presented - i.e. the kubelet / docker drivers should match.

this is a UX complication, but at the same time we are not going to expand on things like what a cgroup driver really is.

/close
