### ISSUE TITLE
Page not updated: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

### ISSUE THREAD

**Issue by jberkus** [kubernetes/website#7879]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

This API aggregation doc still refers to verison 1.7, in the 1.10 docs.

**Proposed Solution:**

This doc needs to be audited and updated for 1.10.  While I could easily remove the offending version number, I don't know what else has changed since 1.7.

**Page to Update:**
https://kubernetes.io/...

cc @deads2k

**Comment by tengqm** [comment]
triaged

**Comment by jberkus** [comment]
New URL is at: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/

The page is still out of date.

/remove-lifecycle rotten

**Comment by jberkus** [comment]
/remove-lifecycle rotten

This page is *still* out of date, and is *much more* out of date today.

Can we get someone from api-machinery to update it?

@kubernetes/sig-api-machinery-bugs 
/sig api-machinery
