### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/

### ISSUE THREAD

**Issue by J-Ibarra** [kubernetes/website#7883]
**This is a...** 

- [ ] Feature Request
- [ x ] Bug Report

**Problem:**
No ping from the first node to the other node!

Hello, I need some help, y try make ping on docker container inter nodes but no is succefull

container-node-1
    inet 172.17.24.2/24 scope global eth0

container-node-2
    inet 172.17.69.2/24 scope global eth0

container-node-1
ping 172.17.69.2

container-node-2
ping 172.17.24.2

but no make ping

when I make ping to net docker0 inter node, the ping its succesfull

container-node-1
ping 172.17.69.1

container-node-2
ping 172.17.24.1

but this https://kubernetes.io/docs/getting-started-guides/fedora/flannel_multi_node_cluster/ say

Now ping from the first node to the other node: make ping fine!

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by zacharysarah** [comment]
@J-Ibarra 👋 The getting started guides on the website are out of date. We're in the process of removing them and replacing them with links to platforms' own documentation. While that's in progress, I recommend visiting Fedora's website and searching their own documentation.

**Comment by J-Ibarra** [comment]
Excellent, Thank Very Much
