### ISSUE TITLE
The `nodeAffinity` field for PersistentVolume is not documented

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#7900]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
With kubernetes/kubernetes#59391 released in 1.10, the `nodeAffinity` field is added to PersistentVolume resource thus the previous `volume.alpha.kubernetes.io/node-affinity` annotation is deprecated. Neither the annotation nor the new field seems documented.

**Proposed Solution:**
Document it.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by mistyhacks** [comment]
Claimed for the Write the Docs hackathon.

**Comment by Logan1x** [comment]
Hey @tengqm @zacharysarah i would love to work on this issue but I've no idea about what needs to update i.e. what to update in that page.
I am first time contributor.

**Comment by tengqm** [comment]
@Logan1x The idea is to have a subsection for persistent volumes:
 https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes 
Although the 'nodeAffinity' property is documented in the API references (i.e. 
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#persistentvolumespec-v1-core ), we believe such a feature deserves a dedicated sub-section to explain to users/operators what they can do with it.
You will need to follow the contribution guide to propose a PR (Pull Request) with the new contents added, see: https://kubernetes.io/docs/home/contribute/create-pull-request/

**Comment by Logan1x** [comment]
So you want me to copy `nodeAffinity` documentation to `persistent volumes` documentation? @tengqm

**Comment by tengqm** [comment]
@Logan1x I was hoping that this feature is discussed in the docs, not just in the API references. Not every user will go through the API references to understand a feature. We should document it as a feature by providing some samples and a link to the API references.

**Comment by Logan1x** [comment]
All I could find these 3 docs in API references. are these enough to create subsection or am i missing something? @tengqm 
1.
![image-one](https://user-images.githubusercontent.com/10944610/41819659-cfc6ede2-77e1-11e8-894a-0916e7a57424.png)

2.

![image-two](https://user-images.githubusercontent.com/10944610/41819683-410b6348-77e2-11e8-8d97-52e885bf401d.png)

3.

![image-three](https://user-images.githubusercontent.com/10944610/41819696-6aeb27c0-77e2-11e8-8328-ed830b96de65.png)

**Comment by tengqm** [comment]
@Logan1x Those can actually serve a good starting point.
