### ISSUE TITLE
1.9 API reference page 404s, doesn't redirect

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#7919]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Visiting [1.9 API reference page](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/) returns 404. Users Googling for [an API reference](https://www.google.com/search?q=containerport+pod-spec&oq=containerport+pod-spec&aqs=chrome..69i57.2644j0j7&sourceid=chrome&ie=UTF-8) are likely get a result for this page.

**Proposed Solution:**
Redirect to the API reference landing page or some other relevant page

**Page to Update:**
Redirects page

**Comment by ashleytqy** [comment]
Hi! Can I help out with this issue?
