### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/networking/

### ISSUE THREAD

**Issue by kbaegis** [kubernetes/website#7933]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
Your documentation sucks. I came to the link for more information on getting k8s setup with an openvswitch backend. Your link from https://kubernetes.io/docs/concepts/cluster-administration/networking/#openvswitch literally just dumps me on the openswitch root site. 

**Proposed Solution:**
Write better documentation- or any. 

**Page to Update:**
https://kubernetes.io/...

**Comment by zacharysarah** [comment]
@kbaegis Your experience sounds frustrating. It doesn't excuse abusive behavior. 

This issue is closed and locked. You're welcome to re-submit your feedback after reviewing the [code of conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md):

> Examples of unacceptable behavior by participants include: ...
> Trolling or insulting/derogatory comments
