### ISSUE TITLE
Issue with k8s.io/docs/reference/generated/kube-apiserver/

### ISSUE THREAD

**Issue by alishaagupta** [kubernetes/website#7941]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

cannot find command kube-apiserver
Kubernetes Version: 1.9

**Comment by tengqm** [comment]
Switch to v1.9 first by choosing from the upper right corner in the top bar, then go to reference page there.

Or, use this link: https://v1-9.docs.kubernetes.io/docs/reference/generated/kube-apiserver/
