### ISSUE TITLE
kubelet documentation generated is invalid.

### ISSUE THREAD

**Issue by tengqm** [kubernetes/website#7943]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The page is showing weird contents. There must be something wrong in the doc generator or doc generation process.

**Proposed Solution:**
Fix it.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubelet/

**Comment by zacharysarah** [comment]
@tengqm Do you mean the auto-generation message?
`Auto generated by spf13/cobra on 25-Mar-2018`

Can you screenshot any other weirdness?

/assign @Bradamant3 
/assign @steveperry-53

**Comment by tengqm** [comment]
@zacharysarah Yes. It contains a message in the list of options. The options list is thus broken into incomplete pieces.

**Comment by jimangel** [comment]
@zacharysarah I might have redone some of this work here: https://github.com/kubernetes/website/pull/9344 let me know if there's anything I can help with!
