### ISSUE TITLE
Hosted fonts need to be embedded

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#7955]
Serving fonts from Google slows site load times in China. 

Instead of serving fonts from an external host, we need to serve them from kubernetes.io.

**Comment by heckj** [comment]
I'm doing some research on what it takes to do this - no PR created to change this up, but a useful link on [SO that talked about local font linking options](https://stackoverflow.com/questions/8966740/how-to-host-google-web-fonts-on-my-own-server) was available...

**Comment by heckj** [comment]
The fonts we're using:
 - `Open Sans`
 - `Arial`
 - `Roboto`, `Roboto-light`, `Roboto-bold`

The files that link to remote fonts:
 - `_includes/head.html`
 - `_includes/head.html`
 - `_layouts/blog.html`

with the links: 
- `https://fonts.googleapis.com/css?family=Roboto+Mono`
- `https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic`

**Comment by dankohn** [comment]
I just confirmed with our bus dev rep in Beijing that kubernetes.io now loads very fast there. Congratulations.
