### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/

### ISSUE THREAD

**Issue by anujmittal14** [kubernetes/website#7960]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
No need to explicitly mentioned 'kubectl' , while installing on centOS as kubeadm has dependency on kubeadm it will install automatically. 
 
yum install -y kubelet kubeadm kubectl

**Proposed Solution:**
yum install -y kubelet kubeadm

**Page to Update:**
https://kubernetes.io/...

o/p

yum install -y kubeadm-1.9.1-0
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.mirror.ndchost.com
 * extras: mirror.tocici.com
 * updates: pubmirrors.dal.corespace.com
Resolving Dependencies
--> Running transaction check
---> Package kubeadm.x86_64 0:1.9.1-0 will be installed
--> Processing Dependency: kubectl >= 1.6.0 for package: kubeadm-1.9.1-0.x86_64
--> Running transaction check
---> Package kubectl.x86_64 0:1.10.0-0 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================
 Package                  Arch                    Version                    Repository                   Size
===============================================================================================================
Installing:
 kubeadm                  x86_64                  1.9.1-0                    kubernetes                   16 M
Installing for dependencies:
 kubectl                  x86_64                  1.10.0-0                   kubernetes                  7.6 M

Transaction Summary
===============================================================================================================
Install  1 Package (+1 Dependent package)

Total download size: 24 M
Installed size: 137 M
Downloading packages:
(1/2): 9ff2e28300e012e2b692e1d4445786f0bed0fd5c13ef650d61369097bfdd0519-kubectl-1.10.0- | 7.6 MB  00:00:01
(2/2): ccc2b7d8ac99c8ead43087e7bb5cc7fb3fe684bfd78241c8240feb945303c40e-kubeadm-1.9.1-0 |  16 MB  00:00:02
---------------------------------------------------------------------------------------------------------------
Total                                                                          9.2 MB/s |  24 MB  00:00:02
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : kubectl-1.10.0-0.x86_64                                                                     1/2
  Installing : kubeadm-1.9.1-0.x86_64                                                                      2/2
  Verifying  : kubeadm-1.9.1-0.x86_64                                                                      1/2
  Verifying  : kubectl-1.10.0-0.x86_64                                                                     2/2

Installed:
  kubeadm.x86_64 0:1.9.1-0

Dependency Installed:
  kubectl.x86_64 0:1.10.0-0

Complete!

**Comment by neolit123** [comment]
in terms of showing to the user that `kubectl` will be installed too, i don't see anything wrong with adding the extra package in a yum call unless it throws errors:
```
yum install -y kubelet kubeadm kubectl
```

please, re-open if see fit.
/close
