### ISSUE TITLE
[SIG planning] Projects in flight: 2018Q2

### ISSUE THREAD

**Issue by zacharysarah** [kubernetes/website#7978]
# Projects in flight: 2018 Q2

This issue is an aggregator for all SIG Docs projects currently in flight (2018 Q2). 

**Please add your projects to the list.** Please add or correct details as appropriate.

### Why this list matters
A list of in-flight projects will help SIG Docs prioritize yearly goals—OKRs and KPIs—at the SIG Docs Summit (Portland, OR, May 9, 2018). 

### In-flight project history

- 2018 Q1: #6935
- 2018 Q2: #7978

### Writing, maintaining and improving content

Project | Contributor(s) | Description | Q2, Q3, Later, Ongoing
---|---|---|---
Increase developer happiness | All contributors | Explain complex information in helpful and effective ways to a variety of user journeys, empathetically and in anticipation of need | Ongoing
User journeys | @Bradamant3, @chenopis, @steveperry-53, @heckj, @alexcontini | Continue maintaining and optimizing existing user journeys | Q2
Create new content | All contributors | Document new features, create new conceptual content, create new user paths | Ongoing
Maintain existing content | All contributors | Reduce editorial debt, improve consistency of style | Ongoing
Mature the Kubernetes style guide | @zacharysarah, @steveperry-53 | Deepen the Kubernetes style guide as needed to:<br>- improve contributions<br>- make contributor onboarding easier | Q2, Q3
Review Kubernetes blog posts | @zacharysarah | Review/approve blog posts for the K8s blog | Ongoing
Repo health | @zacharysarah, @chenopis | - Oversee general repo health<br>- Maintain PR wrangler schedule<br> | Ongoing
Better contribution guidelines | @mistyhacks, @heckj, @Rajakavitha1, @steveperry-53, @tallt0m | - Add guidelines for joining K8s org<br>- Add guidelines for becoming a SIG Docs maintainer<br>- Revise information architecture for [contribution guidelines](https://kubernetes.io/editdocs/) | Q2

### K8s release

Project | Contributor(s) | Description | Q2, Q3, Later, Ongoing
---|---|---|---
Review release-related blog entries | @zacharysarah, Docs release meister | Review quarterly blog posts specific for each major release | Ongoing
Release notes | TBD, chosen per release<br><br>- v1.11: @nickchase | - Organize submissions and edit content for release notes for major releases<br>- Continue improving release note process<br>- Include and automate application of a tag for user-facing release note content | Q2, Q3, Later
Docs release process | @Bradamant3 | Revise and improve guidelines for docs quarterly release process | Q2
v1.11 docs | TBD | Quarterly release | Q2
v1.12 docs | TBD | Q3
v1.13 docs | TBD | Later

### Doc tooling

Project | Contributor(s) | Description | Q2, Q3, Later, Ongoing
---|---|---|---
Branch strategy | @Bradamant3, @chenopis, @heckj, @mistyhacks, @steveperry-53, @zacharysarah | Investigate improvements to k/w's release and publishing branch strategies | Q2, Q3
Auto generated/imported docs | @heckj, @steveperry-53, @chenopis | <br>- Q2: Investigate importing provider hosted content into Setup/other docs<br>- Ongoing: Continue refining autogeneration scripts | Q2, Ongoing
i18n framework | @chenopis, @zacharysarah | - Implement an i18n workflow and language selector for languages in Hugo<br>- Perform a one-time refresh of content on `kubernetes.io/cn` in time for KubeCon EU | Q2, Q3
Community section redesign | @parispittman | Provide a strategy for redesigning kubernetes.io/community | Q2
Metrics | @chenopis, @jaredbhatti, @zacharysarah | Establish site metrics for user happiness | Q2, Q3
Migrate to Hugo | @Bradamant3, @chenopis, @heckj, @jaredbhatti, @steveperry-53, @zacharysarah | Migrate k8s.io from Jekyll to Hugo | Q2

### Community outreach

Project | Contributor(s) | Description | Q2, Q3, Later, Ongoing
---|---|---|---
Docs sprints | @zacharysarah, @jaredbhatti, @chenopis | - [KubeCon EU](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2018/) (May 2-4, Copenhagen)<br>- [WriteTheDocs PDX](http://www.writethedocs.org/conf/portland/2018/) (May 6-8, Portland, OR)<br>- [KubeCon China](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-china-2018/) (November 14-15, Shanghai) | Q2, Q3, Later

### Team building and SIG development

Project | Contributor(s) | Description | Q2, Q3, Later, Ongoing
---|---|---|---
Hire another LF technical writer | @zacharysarah, @caniszczyk | Find and onboard a full-time technical writer to focus specifically on content improvements for Kubernetes (85%) and other LF projects (%15) | Q2, Q3
K8s member hiring commitments | @zacharysarah, @jaredbhatti, @caniszczyk | Follow through with Kubernetes member commitments to hiring full-time documentation contributors | Ongoing
Docs training | @Bradamant3, @zacharysarah, @parispittman | Add relnotes, docs training to mentoring for new core reviewers, approvers | Q2
Onboard 1-3 more SIG docs maintainers | All SIG docs maintainers | Grow the number of SIG docs maintainers, reviewers, and approvers by 1-3 | Q2

**Comment by Rajakavitha1** [comment]
@zacharysarah Please add me to the list for Better contribution guidelines. 
Regards,
Rajie

**Comment by zacharysarah** [comment]
@Rajakavitha1 Done. Thanks for the reminder! 🙇

**Comment by chenopis** [comment]
Some overlapping thoughts:
* i18n
  * CN workflow
  * add KR
* User Journeys, Phase II
* Analytics refresh
  * update tracking code
  * add events
* SEO improvements for findability
* Fundamental Modeling Concepts
  * rigorous definitions of concepts and terms
  * layered diagrams to help build better mental models
* Improve style guide
  * make it easier, more discoverable, useable
  * prezo @ doc sprints
