### ISSUE TITLE
Documentation page down at https://kubernetes.io/blog/2016/12/20/statefulset-run-scale-stateful-applications-in-kubernetes/

### ISSUE THREAD

**Issue by zhengzhu88** [kubernetes/website#7981]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This blog post/documentation page is down [https://kubernetes.io/blog/2016/12/20/statefulset-run-scale-stateful-applications-in-kubernetes/](https://kubernetes.io/blog/2016/12/20/statefulset-run-scale-stateful-applications-in-kubernetes/)

**Proposed Solution:**
Not sure

**Page to Update:**
https://kubernetes.io/blog/2016/12/20/statefulset-run-scale-stateful-applications-in-kubernetes/

**Comment by tengqm** [comment]
Looks like the page is available at https://kubernetes.io/blog/2016/12/statefulset-run-scale-stateful-applications-in-kubernetes
