### ISSUE TITLE
Issue with kubernetes.io/blog redirects

### ISSUE THREAD

**Issue by gtirloni** [kubernetes/website#7999]
Website search for "rbac": https://blog.kubernetes.io/2017/10/using-rbac-generally-available-18.html

Redirects to: https://kubernetes.io/blog/2017/10/27/using-rbac-generally-available-18/

Correct URL: https://kubernetes.io/blog/2017/10/using-rbac-generally-available-18

**Comment by zacharysarah** [comment]
Fixed
