### ISSUE TITLE
Issue with Documentation: kubelet-authentication-authorization

### ISSUE THREAD

**Issue by krcroft** [kubernetes/website#8034]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/admin/kubelet-authentication-authorization describes default behavior that is the opposite of how the current Kubernetes 1.10 release behaves.

The documentation says ... | The actual 1.10 behavior is ...
------------ | -------------
By default, requests to the kubelet’s HTTPS endpoint that are not rejected by other configured authentication methods are treated as anonymous requests | Mapping  authenticated requests to user:anonymous is disabled in kubelet 1.10
To disable anonymous access and send 401 Unauthorized responses to unauthenticated requests: start the kubelet with .... |  Anonymous authenticated access is disabled by default in 1.10, so no action is necessary.
Start the kubelet with the `--anonymous-auth` flag | The `--anonymous-auth` flag doesn't exist in kubelet 1.10.  It's been replaced with the `authentication:anonymous:enabled <bool>` YAML v1beta1 KubeletConfiguration record, which defaults to *false*.
To enable X509 client certificate authentication, start kubelet with the `--client-ca-file` flag | The `--client-ca-file` flag doesn't exist in kubelet 1.10. It's been replaced with the `clientCAFile: <string>` YAML  configuration record, which is *empty* by default.
The default authorization mode is AlwaysAllow, which allows all requests. |  It's not AlwaysAllow in kubelet 1.10. The default authorization mode is *Webhook* in 1.10.  Achieving the documented behavior involves setting the `authorization:mode: AlwaysAllow` YAML v1beta1 KubeletConfiguration record
Start the kubelet with the `--authorization-mode= <string>`  flag |   The `--authorization-mode` flag doesn't exist in kubelet 1.10. It's been replaced with the authorization:mode: <string> YAML v1beta1 KubeletConfiguration record, which is set to "Webhook" by default.

**Proposed Solution:**

Correct the documentation:
- Replace the above CLI flags with their new corresponding YAML keys and values
- Describe the new default behavior:
  - Authenticated access not rejected by other configured authentication methods will be denied and a "401 Unauthorized" result sent
  - Subdivide access to the kubelet API via Webhooks is now the default, therefore concise documentation should be provided describing how exactly webhooks (both api-server-side and kubelet client-side) can be configured such that kubectl actions like exec and logs actually succeed.

**Page to Update:**

https://kubernetes.io/docs/admin/kubelet-authentication-authorization

Kubernetes Version: 1.10

**Comment by liggitt** [comment]
if you specify a config file, the defaults are different (and more secure), but if you simply invoke `kubelet`, all of the documented behavior still holds (`--anonymous-auth=true`, `--authorization-mode=AlwaysAllow`, etc)

**Comment by liggitt** [comment]
cc @mtaufen for confusion from disappearing deprecated flags

**Comment by liggitt** [comment]
closing this for now... we're not going to remove the description of the insecure defaults until running with a config is required and the defaults are actually secure

/close

**Comment by krcroft** [comment]
>  if you simply invoke kubelet, all of the documented behavior still holds (--anonymous-auth=true, --authorization-mode=AlwaysAllow, etc)

Those flags don't exist in the current 1.10, release.  They did in prior releases, but they've been removed, therefore the documentation currently describes flags that don't even exist.

**Comment by liggitt** [comment]
> Those flags don't exist in the current 1.10, release. They did in prior releases, but they've been removed, therefore the documentation currently describes flags that don't even exist.

They do exist, and are functional, but were (unfortunately) masked from the flag help because they are marked as deprecated in favor of starting with a config file. 

This was resolved in https://github.com/kubernetes/kubernetes/pull/63448 and the flag help in 1.10.4 now displays properly again.

**Comment by krcroft** [comment]
Yes, I encountered this straight away on the 1.10.0 release.
Glad it was fixed in 1.10.4!
