### ISSUE TITLE
Issue with k8s.io/docs/setup/building-from-source/

### ISSUE THREAD

**Issue by sam0392in** [kubernetes/website#8043]
It is been noted that in Ubuntu Servers (specifications given below) while doing building from source, it is taking lot of time for MAKE RELEASE and at last _output folder is created only with a single image.

Make release is tried on different linux machine and the end result is same, 
Kindly suggest.

Server Specs:-

RAM - 2 GB
Disc Space - 30 GB
using UBUNTU 16.04 Server

**Comment by shubheksha** [comment]
@sam0392in, not sure if this is a docs related issue, could you try asking this in slack perhaps? 
/close
