### ISSUE TITLE
Need docs for apps/v1 workloads API change 

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/website#8049]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Our latest release is 1.10. We need to update the [doc](https://kubernetes.io/docs/reference/workloads-18-19/) for API changes of `apps/v1` which becomes available in 1.9. 

**Proposed Solution:**
`apps/v1beta2` is almost the same as `apps/v1`. Just need to update the doc for `apps/v1`. 

**Page to Update:**
https://kubernetes.io/docs/reference/workloads-18-19/

cc @kow3ns

**Comment by tengqm** [comment]
@janetkuo I did a quick grep over the website repo. The result is a little bit "disappointing", ;)
It looks to me that all YAMLs using `apps/v1beta2` have been changed to `apps/v1`. There are some exceptions under the `/cn' directory but we are not maintaining them actively.

**Comment by tengqm** [comment]
Did a search again, we still have remnants using 'extensions/v1beta1' and 'apps/v1beta1'. Will propose a fix for this.

**Comment by janetkuo** [comment]
Thanks @tengqm for fixing the yaml. 

I forgot to include the page to update: https://kubernetes.io/docs/reference/workloads-18-19/ when filing the issue. This issue was originally meant to track the doc for workload API changes made to `apps/v1`, which can help users migrate to `apps/v1`. Reopen.
