### ISSUE TITLE
v1.10 docs UI issue

### ISSUE THREAD

**Issue by JakeRowsell89** [kubernetes/website#8079]
**This is a...** 
- [x] Bug Report

**Problem:**
<img width="1182" alt="screen shot 2018-04-13 at 14 53 10" src="https://user-images.githubusercontent.com/14165024/38742438-72261bd0-3f34-11e8-93d7-4ed03c5d475c.png">

**Proposed Solution:**
Removing linear-gradient from body > #wrapper in CSS

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/

1.10

Happy to put in a PR if the old docs page is still updated

**Comment by tengqm** [comment]
@JakeRowsell89 If you are interested in fixing this, please consider a PR to the https://github.com/pwittrock/brodocs/blob/master/stylesheet.css file, and then push a docker image to docker hub. The doc generator tool (kubernetes-incubator/reference-docs) will use the latest version of the docker image for doc generation.

**Comment by tengqm** [comment]
Okay to close now. Problem fixed.
/close
