### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by deccico** [kubernetes/website#8112]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
_Install kubectl binary via curl_ section doesn't seem to work. In particular, clicking on _Linux_ doesn't render the correct results.

**Proposed Solution:**
Change the links as we click on Linux/Windows/macOS. This is very possible a JS/CSS rendering problem based on the 1.9 version of the docs. 

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/#kubectl-install-1

**Comment by CaoShuFeng** [comment]
Hi:
https://github.com/kubernetes/website/pull/8155
