### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by sakthiskumar** [kubernetes/website#8113]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

![image](https://user-images.githubusercontent.com/7370007/38841638-f7045ee4-4217-11e8-9922-241947468cb8.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@sakthiskumar, is this still an issue? If not, could you please close it?
