### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/web-ui-dashboard/

### ISSUE THREAD

**Issue by mabushey** [kubernetes/website#8119]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**

Docs are wrong, Expecting the web interface shown in the docs. Instead a list of paths is displayed

**Proposed Solution:**

Fix / update

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

v1.10.1

**Comment by shubheksha** [comment]
@mabushey, the screenshots of the web interface render alright for me. Could you please provide screenshots and state the browser and version you're using if the problem still persists?

**Comment by mabushey** [comment]
This is a known depreciation, the docs just need to be updated. In chrome 65.0.3325.162 http://localhost:8001/ui:

```
{
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/ping",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/openapi/v2",
    "/swagger-2.0.0.json",
    "/swagger-2.0.0.pb-v1",
    "/swagger-2.0.0.pb-v1.gz",
    "/swagger.json",
    "/swaggerapi",
    "/version"
  ]
}
```

http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/overview

Is the correct URL. It still doesn't load right, but at least the left menu bar loads. I think I'm running into a bug with the proxy, sometimes if I kill the proxy the full page loads.

**Comment by mabushey** [comment]
Also you now you get to a "log-in" page where you have to enter a token for access.

**Comment by mabushey** [comment]
Here's the up to date docs with the new correct URL:  https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above
