### ISSUE TITLE
Issue with k8s.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/

### ISSUE THREAD

**Issue by GuomeiQtl** [kubernetes/website#8136]
Since the new version of kubernetes, downwardAPI now support to expose single annotation/label via downward API .  https://github.com/kubernetes/kubernetes/pull/55902
So maybe the document need to updated.

**Comment by shubheksha** [comment]
Hey, can you please update your issue to adhere to the provided issue template? Thank you!
