### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by fudali113** [kubernetes/website#8139]
**This is a...** 

- [*] Feature Request
- [ ] Bug Report

**Problem:**
Extend the Kubernetes API with /apis/apiregistration.k8s.io don`t have task and doc
 
**Proposed Solution:**
add Extend the Kubernetes API with /apis/apiregistration.k8s.io task and doc

**Page to Update:**
https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/

**Comment by fudali113** [comment]
This issue was caused by my mistake. Please turn it off. Sorry.

**Comment by tengqm** [comment]
dup of #8140
