### ISSUE TITLE
admin/authorization: general concepts should be separated from plugin specific info

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/website#814]
Currently a lot of general authorization concepts are split up between the ABAC, RBAC, and webhook sections. These topics include:
- Non-resource paths (/apis, /swagger).
- What verbs to expect and what powers they grant.
- Dealing with service accounts.

Currently I have to read the entire document to learn all the necessary information. For instance, RBAC doesn't mention non-resource paths, so if a user only reads that section they'll miss something critical (see example[0]).

cc @erictune @liggitt 

[0] https://stackoverflow.com/questions/38299105/how-to-use-rbac-in-kubernetes

**Comment by tengqm** [comment]
em... still relevant
/remove-lifecycle stale
