### ISSUE TITLE
Check API changes and change upstream version in tests, per release

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#8143]
- [X] Feature Request

**Problem:**
When upstream master removed an API that the docs tests check, all travis builds started failing. The immediate issue is fixed in two ways, with #8122:

- changed the API checks that failed
- changed the upstream version from master to latest stable release

This is an excellent interim solution, but we need to do a few more things to ensure that such breaks don't happen again.

**Proposed Solution:**

- document for docs release meister that when release is cut, tests should be updated to run against the latest release version

- document for docs release meister or shadow or other that we should check for any API changes that could break the tests. We can check the release notes manually for now, and devise an automated solution if the manual approach proves inadequate or someone wants to get clever. (Note that checking the API refdocs is not a reliable solution here. example: the 1.10 refdocs are wrong for exactly the offending API in the test break.)

**Page to Update:**
- https://github.com/kubernetes/sig-release/blob/master/release-process-documentation/documentation-guides/update-release-docs-new.md
- https://github.com/kubernetes/website/blob/master/test/examples_test.go

**Comment by zacharysarah** [comment]
@Bradamant3 Thank you for this--I'll take it on for my playbook update in https://github.com/kubernetes/sig-release/pull/139.
