### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

### ISSUE THREAD

**Issue by stefanhans** [kubernetes/website#8156]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
IMHO: The back-off count is reset and not the back-off limit.

"The back-off limit is reset if no new failed Pods appear before the Job’s next status check."

**Proposed Solution:**
Change the text accordingly:

"The back-off count is reset if no new failed Pods appear before the Job’s next status check."

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

**Comment by ajaeger** [comment]
/assign

this was fixed with #8379, let's close this. Thanks for the report.
