### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-interactive/

### ISSUE THREAD

**Issue by mlem** [kubernetes/website#8158]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
when running the last command (curl with POD name) I'm getting an error message
```
curl http://localhost:8001/api/v1/proxy/namespaces/default/pods/$POD_NAME/
Error: 'dial tcp 172.18.0.4:8080: getsockopt: connection refused'
Trying to reach: 'http://172.18.0.4:8080/'$ 
```

**Proposed Solution:**
I don't know, it's a tutorial and I expect it to work.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-interactive/

**Comment by CaoShuFeng** [comment]
It works fine with me.

Have you run all previous steps one by one?

**Comment by shubheksha** [comment]
@mlem, are you still running into this issue? If not, please close this issue :)

**Comment by nanthan** [comment]
when I run this command on kubectl proxy

```
export POD_NAME=$(kubectl get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
curl http://localhost:8001/api/v1/namespaces/default/pods/$POD_NAME/proxy/
curl: (7) Failed to connect to localhost port 8001: Connection refused
```

Error occured on both Module 2 and Module 3 Interactive Tutorial

**Comment by shubheksha** [comment]
cc: @BenHall - can you please look into this once?

**Comment by BenHall** [comment]
@shubheksha Thanks! Will do.
