### ISSUE TITLE
Issue with k8s.io/docs/admin/high-availability/building/

### ISSUE THREAD

**Issue by MOHAMMAD-SHAMSHAD** [kubernetes/website#8163]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
@MOHAMMAD-SHAMSHAD, can you clarify what's the issue and link the page?
