### ISSUE TITLE
k8s.io/docs/setup/independent/create-cluster-kubeadm/ fails to mention crictl

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#8172]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The instructions for creating a cluster with kubeadm fail to mention that `kubeadm init` requires `crictl`.  Here is how it failed for me:
```
# kubeadm init --config=/root/kubeadm-config.yaml
[init] Using Kubernetes version: v1.10.1
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
...
```

**Proposed Solution:**
Document what to do about crictl

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by MikeSpreitzer** [comment]
Hmm, I see that lack of `crictl` provokes a _warning_.  I wonder why I thought `crictl` is _required_?

**Comment by neolit123** [comment]
so right now we are in phase where we are deciding how to improve the UX about `crictl` here - i.e. is `go get` the right UX? one would need a go environment for that, and cluster admins might not be comfortable doing it.

there are also binaries available from other locations.

i'm going to keep this issue open and see if we need to put something in the docs.

**Comment by neolit123** [comment]
`critools` was added as a kubeadm dependency in June and should be now installed from the standard Linux packages.

see this for more details:
https://github.com/kubernetes/kubernetes/pull/64836

/close
