### ISSUE TITLE
k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-init/ does not mention the required token syntax

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#8176]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This web page displays a crude schema for a kubeadm config file that neglects to mention the required syntax for the token.

**Proposed Solution:**
Document the required syntax.

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

1.10.1

See also https://github.com/kubernetes/kubeadm/issues/768 --- a new user really gets no clue.

**Comment by MikeSpreitzer** [comment]
I just discovered that the token syntax _is_ documented.  The problem is that this is mentioned nowhere near the schema for a config file.  It would be better if the token syntax were documented in or near the schema, or there were a pointer to the syntax doc from in or near the schema.

**Comment by neolit123** [comment]
after the new generated CLI reference docs are up, the information for the syntax of the bootstrap token will be available.

/close
