### ISSUE TITLE
Issue with k8s.io/docs/reference/glossary/

### ISSUE THREAD

**Issue by chris-short** [kubernetes/website#8183]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
k/k isn't obviously defined for new people to the community. I'd like to add it to the glossary for future reference.

**Proposed Solution:**
Please add
> **k/k**: Short for the [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) repo. Frequently used in conversations such as comments and SIG meetings

**Page to Update:**
https://kubernetes.io/docs/reference/glossary/?community=true

**Comment by zacharysarah** [comment]
Closed by #8185.
