### ISSUE TITLE
location.reload() scrolls to top

### ISSUE THREAD

**Issue by bep** [kubernetes/website#8186]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

This may not be a problem for the end user reading the docs (though I suspect some of the flickerings on load may be a symptom of the same cause). 

To reproduce:

1. In Chrome (tested on my MacBook), go to https://kubernetes.io/docs/reference/deprecation-policy/ or any other page of some length, and scroll down. 
2. In the JavaScript console, type "window.location.reload();" and hit enter.
3. Notice the page scrolling to top.

Note that in Safari everything is OK.

I found this issue when doing some migration work of this site to Hugo. Hugo rebuilds the site in milliseconds, and takes special care to do `window.location.reload();` if possible. But this issue makes editing long documents much less pleasurable than it could be. The current workaround is to use another browser, but Chrome seems like a common choice for many.

**Comment by bep** [comment]
I suspect this is also what you see when you use the "copy code to clipboard" feature.

**Comment by vllry** [comment]
I did some digging, but didn't get very far (it's also an issue in Firefox, but Firefox scrolls down 100px or so from the top). It sounds like it's an issue with a scrolling div, that the browser just isn't tracking.

Other than digging through div behavior, it seems like the other option is a hack to store scroll position on events, and jump to that position on page load.

**Comment by KurtRMueller** [comment]
> I suspect this is also what you see when you use the "copy code to clipboard" feature.

This happens to me using Firefox Developer Edition, v67.0b9. I'll copy the code to my clipboard, a dialog box pops up telling me I've copied code to the clipboard, and the browser goes back up to the top of the page.
