### ISSUE TITLE
1.10 missing flags for kubelet & kube-apiserver

### ISSUE THREAD

**Issue by swestcott** [kubernetes/website#8188]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
https://github.com/kubernetes/kubernetes/pull/48859 introduced new TLS flags to kubelet and kube-apiserver. These were missed in the changelog (https://github.com/kubernetes/kubernetes/pull/61749) and in the docs.

**Proposed Solution:**
Update docs to include `--tls-cipher-suites` and `--tls-min-version` flags

**Page to Update:**
- https://kubernetes.io/docs/reference/generated/kubelet/
- https://kubernetes.io/docs/reference/generated/kube-apiserver/

**Comment by tengqm** [comment]
@swestcott You may want to check this as well: https://github.com/kubernetes/kubernetes/blob/v1.10.0/cmd/kubelet/app/options/options.go#L430

Most of the kubelet command line flags are hidden in v1.10. The reference docs generated from the code cannot find out these hidden flags as well. These flags are still usable, but will be soon replaced by kubelet config file. So ... I don't think we can do anything from doc's perspective.

**Comment by swestcott** [comment]
Oh interesting, I hadn't seen that. Do you know if the same is true for `kube-apiserver`?

**Comment by tengqm** [comment]
@swestcott Yes. For example, flags related to insecure serving are not listed from available options. However, you can still use them ...

**Comment by zacharysarah** [comment]
#8313 may fix this issue when it merges.
