### ISSUE TITLE
Masters, as well as workers, need --node-ip in order to use private addresses

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/website#8189]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#using-internal-ips-in-your-cluster says that I have to hack /etc/systemd/system/kubelet.service.d/10-kubeadm.conf on the workers, but I have to hack it on the masters too.

**Proposed Solution:**
In the text replace "When a worker node has been provisioned" with "When a master or worker node has been provisioned".

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#using-internal-ips-in-your-cluster

kube and kubeadm version 1.10.1

**Comment by neolit123** [comment]
resolved by #8378

/close
