### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/object-management-kubectl/declarative-config/

### ISSUE THREAD

**Issue by dadah89** [kubernetes/website#8199]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/#default-field-values
Text mentions `Here’s a configuration file for a Deployment. The file does not specify strategy or selector:`, but the example file does have a selector:

<img width="876" alt="screen shot 2018-04-26 at 2 39 41 pm" src="https://user-images.githubusercontent.com/697824/39333506-f7f8090a-495f-11e8-856a-b3dd09ca890a.png">

Selector duplicated in subsequent example:
<img width="878" alt="screen shot 2018-04-26 at 2 39 51 pm" src="https://user-images.githubusercontent.com/697824/39333542-1e8ef36c-4960-11e8-812f-5cf8f7fa2a26.png">

**Proposed Solution:**
Looks like the example file just need to be updated.

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/#default-field-values

**Comment by makomatic** [comment]
I didn't find the commit or PR but it seems to be already fixed.
