### ISSUE TITLE
Can't access most recent site version from dropdown from older version

### ISSUE THREAD

**Issue by blixtra** [kubernetes/website#8222]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
By default when visiting kubernetes.io one is presented with a version dropdown at the top right which by default shows the most recent version. From here one can choose to view different versions of the site. But once one chooses a version that is not the most recent one, the option to choose the most recent version is gone.

**Proposed Solution:**
Ensure that the most recent version is always available to choose from.

**Page to Update:**
https://kubernetes.io/

Navbar

I see this with version v1.10

**Comment by blixtra** [comment]
It seems this is a bit odder than I thought. While the `v1.10`is not present in the dropdown, when I click on `v1.9` it takes me to the default `kubernetes.io` site which is the v1.10 page. This means the v1.9 site is not available from the older versions, but the misslinked entry is there.

Probably a configuration someone forgot to update.

**Comment by Bradamant3** [comment]
Confirming behavior. Changing priority and adding Hugo milestone.

cc @mistyhacks we should probably figure this out before 1.11 releases ... (I haven't checked the 1.11 preview build yet to see whether the behavior persists after updates to .toml file)

**Comment by steveperry-53** [comment]
I'll work on this. But this is not a Hugo migration issue. This problem has been around since we launched 1.10.

**Comment by zacharysarah** [comment]
Fixing version navigation requires updates to the config file in each previous release branch. (It ends up being about 4 or 5 PRs in total to fix.) It looks like this update never happened in 1.10.
