### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by liguohui2018** [kubernetes/website#8229]
** the url doesn't access** 
https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl  

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Rajakavitha1** [comment]
@liguohui2018 I am able to access the URL : https://kubernetes.io/docs/tasks/configure-pod-container/configmap/kubectl 
with kubectl create configmap game-config --from-file=https://k8s.io/docs/tasks/configure-pod-container/configmap/kubectl

The .properties files are located at: https://github.com/kubernetes/website/tree/master/docs/tasks/configure-pod-container/configmap/kubectl

**Comment by shubheksha** [comment]
The `.properties` files are accessible at the correct URL based on the docs.
/close
