### ISSUE TITLE
Issue with k8s.io/docs/setup/pick-right-solution/

### ISSUE THREAD

**Issue by Vaccano** [kubernetes/website#8231]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Link to IBM private cloud is broken 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by Rajakavitha1** [comment]
@Vaccano I tried to look for IBM cloud private on the IBM website and i get a 404 error. Just raised an issue on the IBM website.

**Comment by Rajakavitha1** [comment]
@Vaccano The link to IBM private cloud works fine now. Please take a look and close this issue if it addressed.
