### ISSUE TITLE
Hugo migration - Incorrect item in Concepts nav

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8239]
This is a bug to track an additional item that is present in the concepts nav. 
 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
The concepts nav includes an additional item under Concepts->Overview->Extending your kubernetes cluster.

**Proposed Solution:**
Remove the "extending your kubernetes cluster" item.

**Page to Update:**
https://k8sio-hugo-migration.netlify.com/docs/concepts/

**Comment by zacharysarah** [comment]
To fix: delete the file from the directory.

**Comment by steveperry-53** [comment]
I think the Extending Kubernetes section is OK now.

But the other problems raised in this issue still need to be addressed.
