### ISSUE TITLE
Hugo migration - ToC has extra bullet points - https://hugo-migration.docs.kubernetes.io/docs/tasks/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8240]
**This is a...** 
- [x] Bug Report

**Problem:**
The table of contents has three extra bullet points: https://cl.ly/0F3p3h2H0A2f 

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/

**Comment by bep** [comment]
This is mentioned elsewhere, but the short version: Suggested fix is to adjust "non-standard" headlines to start with h2 (and not h4 as in this case).

**Comment by steveperry-53** [comment]
https://kubernetes.io/docs/tasks/
