### ISSUE TITLE
Hugo Migration - Example Task Template Page Showing When It Shouldn't - https://hugo-migration.docs.kubernetes.io/docs/tasks/example-task-template/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8241]
**This is a...** 
- [x] Bug Report

**Problem:**
The example task template page is showing at the root level when it should not.
Hugo site: https://cl.ly/1a3a3I3w3t1d 
Production Site: https://cl.ly/420Y0g1A2Y0z 

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/example-task-template/

**Comment by chenopis** [comment]
Fixed.
