### ISSUE TITLE
Hugo migration- reference/kubectl/overview/  [command] no longer in blue

### ISSUE THREAD

**Issue by bradtopol** [kubernetes/website#8242]
So on https://hugo-migration.docs.kubernetes.io/docs/reference/kubectl/overview/
kubectl [command]  the command is no longer in blue

But the original https://kubernetes.io/docs/reference/kubectl/overview/  
kubectl [command] the command is in blue

**Comment by bradtopol** [comment]
Also when the commands are used in example code the color has changed from blue to purple

See  $ kubectl exec <pod-name> date

In the Examples: Common operations section on the page

**Comment by zacharysarah** [comment]
This is an optional formatting fix that we can address later.
