### ISSUE TITLE
Hugo migration - Missing item in Concepts nav

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8243]
This is an issue to track missing items in the Concepts left-nav.

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Missing the Extending Kubernetes->Service Catalog. I have not been able to find it in any of the left-nav nested items.

https://k8sio-hugo-migration.netlify.com/docs/concepts/

**Comment by steveperry-53** [comment]
https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/
