### ISSUE TITLE
Hugo Migration - Site resizing doesn't seem to work

### ISSUE THREAD

**Issue by jaredbhatti** [kubernetes/website#8245]
Site resizing CSS for Hugo doesn't seem to work. Screenshots below. Looks like the hugo site won't work with mobile?

![screen shot 2018-05-01 at 10 28 11 am](https://user-images.githubusercontent.com/6146946/39466669-721479f8-4d2a-11e8-810d-d61b27dd160e.png)

![screen shot 2018-05-01 at 10 28 29 am](https://user-images.githubusercontent.com/6146946/39466705-8d7475b8-4d2a-11e8-92e2-c17088294cfa.png)

**Comment by jaredbhatti** [comment]
Bep, any help you can provide in understanding the issue would help us fix it.

**Comment by bep** [comment]
Probably some container id or something missing when I hand-moved the templates. I will check.

**Comment by bep** [comment]
This should now be fixed (see the commit).
