### ISSUE TITLE
Hugo migration - What is Kubernetes problems

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8248]
---
The Concepts->Overview->What is Kubernetes page is missing a TOC.

https://k8sio-hugo-migration.netlify.com/docs/concepts/overview/what-is-kubernetes/

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
The TOC is missing "Why do I need Kubernetes and what can it do" and 5 other items. The only item listed is "What's next".

---
There is a bad link for "is missing TOC"

**Comment by steveperry-53** [comment]
The Service Catalog topic now appears in the left nav.
https://kubernetes.io/docs/concepts/service-catalog/
