### ISSUE TITLE
Hugo Migration - Extend kubectl with plugins ToC links missing - https://hugo-migration.docs.kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8249]
**This is a...** 
- [x] Bug Report

**Problem:**
In the table that contains links to sub pages (ToC) at the top of the page, Hugo is only displaying links that are at a hierarchy level of one sub-page deep in the top part of the page. For example:

Hugo: https://cl.ly/0p1z1x3Z3L1D 
Production: https://cl.ly/1p0T150B180v 

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

**Comment by zparnold** [comment]
It looks like this is a difference in the fact that Hugo isn't recognizing <h2> and <h3> tags (or their Markdown counterparts `##`, and `###`) and placing them in the Table of Contents

**Comment by bep** [comment]
See https://github.com/kubernetes/website/issues/8253#issuecomment-386207295

**Comment by bep** [comment]
I have commented about this in another thread, but the short version is that the "capture template" constructed pages currently only support one level in toc (h2).

**Comment by steveperry-53** [comment]
By design. Only the H2 headings get picked up for the page TOC.
