### ISSUE TITLE
Hugo migration - Kubernetes components problems - Links to /admin/ are broken

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8250]
This issue is to track problems on the Concepts->Overview->Kubernetes Components page

- [ ] Feature Request
- [X] Bug Report

---
**Problem:**
The nav does not include the sub-items, ie. Master Components->kube-apiserver.

---
**Problem:**
Bad links for
- Building High-Availability Clusters 
- kube-proxy

**Comment by jaredbhatti** [comment]
Looks like all redirects to anything under /admin/ are broken. Should take a look at the redirects file and fix in Hugo.

**Comment by bep** [comment]
@jaredbhatti I suspect this is  related you testing when I didn't have push-access to the branch etc., and I had disabled the redirects to do my spider checks. 

The redirects is active now.

That said,

I suspect you will get an easier life if you get inspired by https://github.com/gohugoio/hugoDocs and

* Define most of these redirects as aliases in the content files
* Generate the "_redirects" Netlify as part of the Hugo build

**Comment by steveperry-53** [comment]
The redirects of admin/ topics seem to be working now.

https://kubernetes.io/docs/admin/ha-master-gce.md/
https://kubernetes.io/docs/admin/high-availability/
https://kubernetes.io/docs/admin/kubeadm-upgrade-1-7/
https://kubernetes.io/docs/admin/limitrange/
https://kubernetes.io/docs/admin/limitrange/Limits/
https://kubernetes.io/docs/admin/master-node-communication/
https://kubernetes.io/docs/admin/multi-cluster/ 
https://kubernetes.io/docs/admin/multiple-schedulers/
https://kubernetes.io/docs/admin/namespaces/
https://kubernetes.io/docs/admin/namespaces/walkthrough/
https://kubernetes.io/docs/admin/network-plugins/
https://kubernetes.io/docs/admin/networking/
https://kubernetes.io/docs/admin/node/
https://kubernetes.io/docs/admin/node-allocatable/
