### ISSUE TITLE
Hugo migration - TOC on page is not including nested items

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8253]
The TOC on these pages is not including nested items.

- [ ] Feature Request
- [X] Bug Report

---
**Problem:**
Concepts -> Overview -> Working with Kubernetes Objects -> Undersanding..

**Comment by bep** [comment]
It currently only shows h2-headers in the ToC in the pages using the special content templates (e.g. those with `{{% capture overview %}}` etc.). Fixing this is non-trivial.

**Comment by steveperry-53** [comment]
This is just the way it is with Hugo. The more sparse TOC seems fine to me.
