### ISSUE TITLE
Hugo Migration - Page formatting for 3 columns has some issues

### ISSUE THREAD

**Issue by jaredbhatti** [kubernetes/website#8254]
Looks like the page formatting for the full docs listing on the homepage has some breaking issues.  Looks like if the title is too long, it breaks the 3 column formatting.  

![screen shot 2018-05-01 at 10 52 18 am](https://user-images.githubusercontent.com/6146946/39467499-ad18c320-4d2e-11e8-8b83-389e91e3232b.png)

**Comment by chenopis** [comment]
This is a logic bug, not a CSS issue. I'm reviewing the code that generates this page. FYI, it's in `/layouts/docs/docsportal_home.html` and the *Browse* section is in `/layouts/partials/docs/browse.html`.

**Comment by chenopis** [comment]
FYI, Hugo uses zero-based indexing whereas the liquid template code was one-based indexing. ;_(
