### ISSUE TITLE
Hugo migration - Problems with Understanding Kubernetes Objects

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8255]
This issue is for tracking issues on the Understanding Kubernetes Objects.

- [ ] Feature Request
- [X] Bug Report

Concepts -> Overview -> Working with Kubernetes Objects -> Undersanding..

**Problem:**

---
The `kubectl create` has a bad link.
https://k8sio-hugo-migration.netlify.com/docs/reference/generated/kubectl/kubectl-commands#create

---
The Kubernetes API reference
https://k8sio-hugo-migration.netlify.com/docs/reference/generated/kubernetes-api/v1.10/

---
Both here links
https://k8sio-hugo-migration.netlify.com/docs/reference/generated/kubernetes-api/v1.10/#podspec-v1-core

**Comment by jaredbhatti** [comment]
Can we makes sure that generated API content is linked to properly?

**Comment by bep** [comment]
The autogenerated docs need to be adjusted and re-generated. @zacharysarah has that on his TODO list.

**Comment by tengqm** [comment]
Looks like none of generated references are migrated.
