### ISSUE TITLE
Hugo Migration - Troubleshooting page appears incorrectly in menu hierarchy - https://hugo-migration.docs.kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8258]
**This is a...** 
- [x] Bug Report

**Problem:**
Troubleshooting page belongs in the repo at `/docs/tasks/debug-application-cluster/troubleshooting.md`  and as such was put in the menu here: https://cl.ly/3S181k3j1O43

It needs to be at the root level as is the case in prod: https://cl.ly/1B021z3V0o3e

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/

**Comment by steveperry-53** [comment]
I see that the location has changed. But I don't hate the new location under Monitor, Log, Debug.
What do the rest of you think?
/cc @chenopis 
/cc @heckj

**Comment by chenopis** [comment]
I think the location of Troubleshooting is fine.
