### ISSUE TITLE
Hugo website - Problems on Nodes page

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8259]
This issue is to track problems on the Concepts -> Kubernetes Architecture -> Nodes page.

https://k8sio-hugo-migration.netlify.com/docs/concepts/architecture/nodes/#manual-node-administration

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Bad links
- kube-controller-manager 
- Node API object

**Comment by jaredbhatti** [comment]
Broken links in the site: 

"If the Status of the Ready condition is “Unknown” or “False” for longer than the pod-eviction-timeout, an argument is passed to the **kube-controller-manager**"

**Comment by steveperry-53** [comment]
The kube-controller-manager and Node API object links are working now.

https://kubernetes.io/docs/concepts/architecture/nodes/
