### ISSUE TITLE
Hugo website - move auth/access content to appropriate location

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8260]
This issue to to track problems on the authorization page.

- [ ] Feature Request
- [X] Bug Report

https://k8sio-hugo-migration.netlify.com/docs/admin/authorization/

**Problem:**
The Accessing the API -> Overview section should be titled `Authorization`.

**Comment by steveperry-53** [comment]
Well, actually there shouldn't even be a stand-alone left nav for this.

We need to move topics out of the admin folder into the appropriate folders that will make the left navs look like they did before the Hugo migration. These should be the only left navs:

* Home (got changed to Documentation in the Hugo migration)
* Setup
* Concepts
* Tasks
* Tutorials
* Reference

**Comment by Bradamant3** [comment]
For the time being, I'm moving the auth/access content to where it used to live, under Reference. We might want to consider other locations or organization for this content, though, so leaving issue open.

**Comment by Bradamant3** [comment]
See also #2792

**Comment by zacharysarah** [comment]
A big part of resolving this includes removing the `admin/` folder from the repo. Removing `user-guides/` could easily fall into scope for this as well.

**Comment by steveperry-53** [comment]
All content in the /docs/admin folder has been moved.
