### ISSUE TITLE
Hugo Migration: Setup—missing pages

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#8261]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

* [Building from Source](https://k8sio-hugo-migration.netlify.com/docs/setup/building-from-source/)
   * bulleted list has formatting issue: multiple bullets for one item
* [Picking the Right Solution](https://k8sio-hugo-migration.netlify.com/docs/setup/pick-right-solution/)
   * bulleted list has formatting issue: bullets missing
* [Creating HA clusters with kubeadm](https://k8sio-hugo-migration.netlify.com/docs/setup/independent/high-availability/)
   * bulleted list `<code>` tags don't work
* [Troubleshooting kubeadm](https://k8sio-hugo-migration.netlify.com/docs/setup/independent/troubleshooting-kubeadm/)
   * bulleted list has formatting issue: multiple bullets for one item
   * sections are all H4s (####) but should be H2s (##)
* [](https://k8sio-hugo-migration.netlify.com/docs/setup/independent/create-cluster-kubeadm/)
   * Dead link to setup guide under Kube-router tab
   * Dead link to kubectl API reference under Tear down section

**Proposed Solution:**
Investigate and resolve migration issues.

**Page to Update:**
https://k8sio-hugo-migration.netlify.com/docs/setup/

**Comment by bep** [comment]
Building From Source/Picking the Right Solution: Hugo's (or Blackfriday, the Markdown renderer) ToC is a little bit inflexible in that it kind of expects a header-tree to start on h2 (we expect to fix that once we get updated to Blackfriday v2). There are examples in this issue with "###" and "####" and "#". And while it _may_ be possible to improve this in CSS, I see no good reason for not adjusting the header levels and get them consistent site-wide. My suggestion is to adjust this so the main headers in a content file is h2s.

Creating HA clusters with kubeadm: I don't see any bullet list with that issue. I saw some similar comment in another issue, and it might be an indentation issue. Hugo needs these code samples to be indented with spaces in a factor of 4 (4,8...)

Troubleshooting kubeadm:

* First two are related to the header remark above. The sections are all H4s in the original, too, so they need to be adjusted by hand.
* I don't see a "Kube-router tab" with dead link.
* The KubeCTL API-generator needs to be adjusted and re-generated. @zacharysarah has that on his TODO list.

**Comment by steveperry-53** [comment]
I think the title of this issue points out the main problem: Many topics that were under Setup in the left nav are no longer there. I'm less concerned about the TOCs on the individual pages.

**Comment by randomvariable** [comment]
On:
> Creating HA clusters with kubeadm
> bulleted list <code> tags don't work

The [custom TOC for tasks generator](https://github.com/kubernetes/website/blob/master/layouts/partials/templates/blocks.html#L12) doesn't handle `<code>`, or explicitly set ids for headings. There's a nasty JS hack to get rid of `<code>`, but unsure whether or not to just make all the headings compliant with that partial or do something else.

**Comment by zacharysarah** [comment]
There may also be white space issues here: as with #8238, the addition of white space (#8647) solved the TOC rendering. Something to consider in possible fixes.
