### ISSUE TITLE
Hugo Migration - "Installing Kubeadm" link missing - https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8263]
**This is a...** 
- [x] Bug Report

**Problem:**
There used to be an "Installing Kubeadm" link available in the tree underneath the "Install Tools:"

Production: https://cl.ly/100r24213P2l
Hugo: https://cl.ly/1p403N3z3z2h

**Proposed solution:**
We will need a solution for handling 3rd party (non-sub-page) links in the left nav.

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-minikube/

**Comment by bep** [comment]
This is a known limitation, but not very hard to fix -- but I think you should think a little before applying that fix.

I think that:

* Adding a YAML structure to section pages that gets listed last, with, say (pseudo code):

```
links:
 - url:
   title:
```

Which can then be listed (after?) the regular pages and sections. That way you get to keep it in the content files and it should be easy to translate.

/cc @jaredbhatti
