### ISSUE TITLE
Hugo Migration: Reference—Generated kubectl reference docs, other pages, are missing

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#8264]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
* There is no reference documentation for kubectl at all on the migrated site. For example, [kubectl drain](https://k8sio-hugo-migration.netlify.com/docs/reference/generated/kubectl/kubectl-commands#drain) 404s in migration, but [not in production](http://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#drain). I think it's because these pages are generated separately (but I'm not certain that this is how it works)
* [Migrated landing page](https://k8sio-hugo-migration.netlify.com/docs/reference/) table of contents is missing many pages compared to [production](https://kubernetes.io/docs/reference/)

**Proposed Solution:**
Migrate kubectl reference documentation and other missing pages.

**Page to Update:**
https://k8sio-hugo-migration.netlify.com/docs/reference/
https://k8sio-hugo-migration.netlify.com/docs/reference/generated/kubectl/kubectl
https://k8sio-hugo-migration.netlify.com/docs/reference/generated/kubectl/kubectl-commands

**Comment by steveperry-53** [comment]
https://kubernetes.io/docs/reference/
https://kubernetes.io/docs/reference/kubectl/kubectl/
