### ISSUE TITLE
Hugo migration - Extending your kubernetes cluster problems

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8266]
The page is for tracking problems on the Concepts -> Overview -> Extending your kubernetes cluster.

https://k8sio-hugo-migration.netlify.com/docs/concepts/overview/extending/

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The `Admission webhook` link does not bring up the section referenced.

---
Nested items not coming up in TOC list

---
The follow links do not work
kubelet, kube-apiserver, kube-controller-manager, kube-scheduler

**Comment by steveperry-53** [comment]
The Extending your Kubernetes Cluster page is now here:
https://kubernetes.io/docs/concepts/extend-kubernetes/extend-cluster/

For the Admission webhook linke, we should change #external-admission-webhooks to #admission-webhooks.

The links to kubelet, kube-apiserver, kube-controller-manager, and kube-scheduler are now working.
