### ISSUE TITLE
Reorganize Tasks Hierarchy

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8270]
**This is a...** 
- [x] Feature Request

**Problem:**
I propose that we adjust the sub-categories of the `/docs/tasks` section and reorganize the content underneath it. When I am a new user, or a returning operator of an existing Kubernetes cluster, I would like to see the categories pertinent to either my job role/function or the exploration of tasks related to the management of/usage in a Kubernetes cluster.

**Proposed Solution:**
A meeting of #sig-docs to discuss what the best task sub-categories should be, and then the reorganization of the content to fit those sub-categories.

**Page to Update:**
https://kubernetes.io/docs/tasks/*

**Comment by steveperry-53** [comment]
Removing the Hugo Migration milestone. This is a nice idea, but it's independent of the Hugo migration. We have another issue, #8398, about how the Tasks TOC was thrown out of whack by the Hugo migration.
