### ISSUE TITLE
Hugo website - tables not rendering correctly

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8271]
This issue is to track tables not rendering correctly.

- [ ] Feature Request
- [X] Bug Report

---
**Problem:**
https://k8sio-hugo-migration.netlify.com/docs/concepts/api-extension/custom-resources/
See the table under `Should I add a custom resource to my Kubernetes Cluster?`
Comparing ease of use
Advanced features and flexibility
Common features

**Comment by zacharysarah** [comment]
Tables do not render correctly here: https://kubernetes.io/docs/concepts/api-extension/custom-resources/

**Comment by zacharysarah** [comment]
Tables do not render correctly here: https://kubernetes.io/docs/concepts/api-extension/custom-resources/

/cc @dankohn
