### ISSUE TITLE
Hugo website - bulleted lists not rendering correctly

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8272]
This issue is to track bulleted lists not rendering correctly.

- [ ] Feature Request
- [X] Bug Report

---
**Problem:**
Declarative APIs section
https://k8sio-hugo-migration.netlify.com/docs/concepts/api-extension/custom-resources/#common-features

---
Images section
https://k8sio-hugo-migration.netlify.com/docs/concepts/containers/images/

**Comment by steveperry-53** [comment]
https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

https://kubernetes.io/docs/concepts/containers/images/
