### ISSUE TITLE
Hugo Migration - Code Block Missing/Formatted Incorrectly - https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8273]
**This is a...** 
- [x] Bug Report

**Problem:**
The code block formatting in markdown appears to have been eaten by Hugo. Note in production: https://cl.ly/141Z2D3H3M12

and in Hugo: https://cl.ly/2q3X0P0V0I2i

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by bep** [comment]
Hugo's Markdown parser is not as lenient as Jekyll's. Indented code blocks are identified by 4 (or 8 etc.) spaces -- not as in this case 7. I tried to fix this by a regexp, but I had too many false positives.

There are related issue reports about the same. These are easy to fix by hand, may be harder to fix by machine.
