### ISSUE TITLE
Hugo website - problems on device plugins page

### ISSUE THREAD

**Issue by clintkitson** [kubernetes/website#8274]
This issue is to track problems on the device plugins page.

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Bad links
- Containers
- Volume
- PodSpec

**Comment by tnir** [comment]
s/hubo/hugo/

**Comment by clintkitson** [comment]
Thanks @tnir

**Comment by bep** [comment]
These links are not working because the autogenerated docs need to be adjusted and re-generated. @zacharysarah has that on his TODO list.

**Comment by Bradamant3** [comment]
Fixed after migration with PR #8325
