### ISSUE TITLE
Hugo Migration - Tabs contain incorrect text - https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8276]
**This is a...** 
- [x] Bug Report

**Problem:**
It looks like the tabs inside of the "Install kubectl binary via curl" in the Installing Kubectl page are showing text that is incorrect. 
Production: https://cl.ly/2I3J2f2e2i1o
Hugo: https://cl.ly/2D302f0h0m26

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by bep** [comment]
I assume is was just the Kubernetes "latest version" string. That is now fixed in:

http://localhost:1313/docs/tasks/tools/install-kubectl/#install-kubectl-binary-via-curl

**Comment by kbatuigas** [comment]
@zparnold Hello, would you mind clarifying what text on the page is incorrect? Is this still an open issue?

**Comment by zparnold** [comment]
Hello there! The incorrect text can be seen in the two links I provided in the bug report. @bep and @kbatuigas this was the Hugo interpretation: https://cl.ly/2D302f0h0m26 and this is how it used to look on Jekyll: https://cl.ly/2I3J2f2e2i1o

**Comment by bep** [comment]
>his was the Hugo interpretation

I have added a commit to fix this. But note that this isn't a "Hugo interpretation". The tab names are something I ported by hand.

**Comment by zparnold** [comment]
Ahh! Thanks. Sorry for the confusion. :100: !
