### ISSUE TITLE
Hugo Migration - Section Ordering maligned - https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by zparnold** [kubernetes/website#8277]
**This is a...** 
- [x] Bug Report

**Problem:**
The page section ordering appears to be out of order in Hugo. The "Install Kubectl" section should be at the top as is the case in production.
Production: https://cl.ly/3v1q1b0H0X1G
Hugo: https://cl.ly/0U0e2H3W2j1H

**Page to Update:**
https://hugo-migration.docs.kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by bep** [comment]
A general remark to page ordering, see https://k8sio-hugo-migration.netlify.com/docs/home/contribute/content-organization/#page-order

We have replaced a hardcoded "toc construct" (in data files) with a menu driven by the content section tree. The conversion script has some logic to try to preserve the old, but a 1:1 mapping is impossible.

So these "order issues" will have to be adjusted by hand (setting weight in content files)

**Comment by steveperry-53** [comment]
This is not about ordering in the left nav. It's about the order of sections on the page. The first section on the page should be "Install kubectl". But instead, that section is last, just before the "What's next" section.

**Comment by bep** [comment]
@steveperry-53 you are right, sorry, I read this a little too fast. See #8588

**Comment by mistyhacks** [comment]
Fixed in #8588
