### ISSUE TITLE
`--enable-admission-plugins` missing from kube-apiserver generated docs

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#8280]
**This is a...** 
- [X] Bug Report

**Problem:**
The `--enable-admission-plugins` flag is missing from this page of the generated docs:
https://kubernetes.io/docs/reference/generated/kube-apiserver/

(See PR #8198 )

**Proposed Solution:**
Find the appropriate part of the code where it appears that a comment is missing, add appropriate content, and regenerate the relevant docs.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kube-apiserver/

Kubernetes Version:
1.10 and later

**Comment by xmik** [comment]
Thanks @Bradamant3 for opening this issue. I found the code with apiserver options used in the generated docs: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubeapiserver/options/admission.go . 

(I found it thanks to: https://kubernetes.io/docs/home/contribute/generated-reference/kubernetes-components/#editing-the-kubernetes-source-code ).
