### ISSUE TITLE
Clarify that 'ports' on egress network policies target pod ports, not service ports

### ISSUE THREAD

**Issue by saplla** [kubernetes/website#8295]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report
- [x] Improvement

**Problem:**
The network policy documentation (website/docs/concepts/services-networking/network-policies.md) doesn't explicitly state that when defining policies between namespaces, egress policy `port` statements must list the ports of containers, *not* the associated service.

**Proposed Solution:**
Include an example like:

If a database were running in one namespace, and the database container exposed port 85432, and the corresponding database's service exposed port 5432 (which it forwarded to the container's port 85432), then to write a restrictive egress policy that permitted a webapp running in a **different namespace** to connect to the database, it would need an egress policy that targetted port 85432 (i.e. the pod's exposed port), **not** port 5432 (the service's port).

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/network-policies/

I'd open a PR but can't sign the CLA, sorry...

**Comment by fiddyspence** [comment]
+1.  The only comment I have is that port 85432 isn't a valid port number in your example.
