### ISSUE TITLE
[long-term] work with k/k leads to improve generated doc content for deprecated and new flags and features

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#8313]
**This is a...** 
- [X] Feature Request
- [ ] Bug Report

**Problem:**
The generated docs do not consistently display flags, options, or features, at least for deprecated features and in at least one instance for a new feature. The doc content is pulled from strings in the k/k repository, so it's an issue for multiple sigs to solve together.

For examples of the issue, see the discussion/comments in the following:
https://github.com/kubernetes/website/pull/8283
https://github.com/kubernetes/website/pull/7887
https://github.com/kubernetes/website/issues/8280
https://github.com/kubernetes/website/pull/8198 (related to issue 8280)

**Proposed Solution:**
No specific implementation recommended yet, but sig-docs should work with code contributors to explore consistent patterns for new and deprecated features and ideally to automate clearer information in the generated docs. For example, if a deprecated flag is included in the generated docs, it's not indicated as deprecated.

**Page to Update:**
N/A -- code and docs need to work together

cc @liggitt

**Comment by mtaufen** [comment]
We should, at the very least, start using our existing API doc generators to produce documentation for componentconfig APIs.

**Comment by Bradamant3** [comment]
Not sure whether this is directly related, but we've also got a bit of a mystery with either the generation scripts or the code:
In the 1.10 apiref docs, `PodSecurityPolicy v1beta1 policy`, which was new (moved) for 1.10, appears in the list of OLD API VERSIONS, while `PodSecurityPolicy v1beta1 extensions`, which it replaced, appears in the METADATA section, making it appear as though it's the current resource. When in fact it's the other way around, yes?

I can pull this out into a separate issue if y'all deem it unrelated. I haven't done enough digging through the code repo, nor do I understand enough about dev in k/k, to be sure about the relationships between different moving parts of larger K8s ecosystem. Or between the different bits of doc generators.

**Comment by liggitt** [comment]
api doc generation is a separate issue. There's nothing in the k/k repo I'm aware of that classifies api groups as "old", so I'd guess it's a matter of unrecognized API groups getting categorized that way by the doc gen scripts. Separate issue, in any case.
