### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by marcoantonioni** [kubernetes/website#8317]
**This is a...** 
- [X ] Feature Request
- [ ] Bug Report

**Problem:**
marco@master1:~/k8s-config/config$ sudo kubeadm init --config=config.yaml
[init] Using Kubernetes version: v1.10.2
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING FileExisting-crictl]: crictl not found in system path
Suggestion: go get github.com/kubernetes-incubator/cri-tools/cmd/crictl
[preflight] Some fatal errors occurred:
	[ERROR FileExisting--etc-kubernetes-pki-etcd-ca.pem]: /etc/kubernetes/pki/etcd/ca.pem doesn't exist
	[ERROR FileExisting--etc-kubernetes-pki-etcd-client.pem]: /etc/kubernetes/pki/etcd/client.pem doesn't exist
	[ERROR FileExisting--etc-kubernetes-pki-etcd-client-key.pem]: /etc/kubernetes/pki/etcd/client-key.pem doesn't exist
	[ERROR ExternalEtcdVersion]: couldn't load external etcd's server certificate /etc/kubernetes/pki/etcd/ca.pem: open /etc/kubernetes/pki/etcd/ca.pem: no such file or directory
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

**Proposed Solution:**

In section 'Run kubeadm init on master' the command should be 'kubeadm init --config=config.yaml --ignore-preflight-errors all' in case you are installing with option 2 (etcd colocated with master) and you have not manually created the etcd certificates.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by neolit123** [comment]
so i'm not a big fan of doing `kubeadm init --config=config.yaml --ignore-preflight-errors=all` in the docs as for the sake of option 2 as this could also skip relevant checks for the user.

@kad how do you think we should approach this?

**Comment by kad** [comment]
@neolit123 for `FileExisting--etc-kubernetes-pki-etcd*` we can add common prefix once we are creating checker instance. e.g. `checks = append(checks, FileExistingCheck{Path: cfg.Etcd.CAFile})` to be changed to `checks = append(checks, FileExistingCheck{Path: cfg.Etcd.CAFile, Label: "ExternalEtcdCerts"})`. this will allow to ignore all file checks for same subject with one ignore item.
That will improve UX.

However, I don't understand why at all those checks are executed, as to my understanding, in case of defined external etcd we should be skipping them.

**Comment by marcoantonioni** [comment]
Hello Lubomir,
honestly do not remember the sequence of commands that I gave during my
tests but it is likely that I did not run the command kubeadm reset
before a new kubeadm init and then on file system may have remained the
previous etcd certificates.

**Comment by marcoantonioni** [comment]
Ok to close for me

Il mer 16 mag 2018, 17:20 Lubomir I. Ivanov <notifications@github.com> ha
scritto:

**Comment by kad** [comment]
I suggest to close the issue and open other issues against kubeadm repo for UX improvements and potentially wrong behaviour of external etcd preflight check (if we can replicate it in some clean environment/scenario).

**Comment by neolit123** [comment]
will do, thanks.

/close

**Comment by kad** [comment]
@marcoantonioni btw, could it be so that your external etcd cluster was setup without TLS ? so, you had unsecure communication URL for external etcd ? If so, that might be another usability/checker bug that we have for kubeadm.
