### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by anas-taji** [kubernetes/website#8324]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
broken [GitHub repository](https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics) link

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/

**Comment by ajaeger** [comment]
/triage duplicate

See #8547

**Comment by shubheksha** [comment]
Closing this as it's a duplicate.
/close
