### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/deployment/

### ISSUE THREAD

**Issue by sb1975** [kubernetes/website#8333]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Incorrect Link to create the deployment

**Proposed Solution:**
Update from 
kubectl create -f https://raw.githubusercontent.com/kubernetes/website/master/docs/concepts/workloads/controllers/nginx-deployment.yaml
TO BELOW :
https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/concepts/workloads/controllers/nginx-deployment.yaml

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by Rajakavitha1** [comment]
Hi @sb1975 

The command to create deployment on https://kubernetes.io/docs/concepts/workloads/controllers/deployment/  reads:  kubectl create -f  https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/concepts/workloads/controllers/nginx-deployment.yaml.

Please close the issue if it addresses the issue you raised.
