### ISSUE TITLE
Issue with k8s.io/docs/tasks/

### ISSUE THREAD

**Issue by dechang16** [kubernetes/website#8336]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
There are 3 bullet points next to the first toc link at the top of the page.

**Proposed Solution:**

There's probably an unclosed ul or li. Or there's a duplicate added by the static site generator.

**Page to Update:**
https://kubernetes.io/docs/tasks/
https://kubernetes.io/docs/tutorials/

**Comment by jimangel** [comment]
@zacharysarah - I created a build based on the latest master. It showed numbers instead of bullets: https://boring-albattani-ccf0f0.netlify.com/docs/tutorials/ do you know where that PR is or am I building it wrong?
