### ISSUE TITLE
NetworkPolicy annotations for existing Namespace

### ISSUE THREAD

**Issue by jlin21** [kubernetes/website#834]
Using `kubectl annotate ns default "net.beta.kubernetes.io/networkpolicy={\"ingress\": {\"isolation\": \"DefaultDeny\"}}"` does not work.  I verified this by checking the calico rules on a minion node.  It said that all inbound rules are still set to 'allow'.  Whereas, when I created a completely new namespace using the provided example, the inbound rule was set to 'deny'.

Also a cleaner way of doing the command up above to get the same result would be `kubectl annotate ns <namespace> net.beta.kubernetes.io/networkpolicy='{"ingress": {"isolation": "DefaultDeny"}}'`.

**Comment by gianrubio** [comment]
@jlin21 Today I was stucked in the same issue, fortunately this was already fixed on #847

**Comment by caseydavenport** [comment]
IIUC this issue can be closed as a documentation bug fixed by #847.

**Comment by tengqm** [comment]
Closing for 1) problem outdated, annotation is deprecated; 2) issue fixed already.
