### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/scale-interactive/

### ISSUE THREAD

**Issue by joequery** [kubernetes/website#8342]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

In Module 5, Step 2: Load Balancing,  the text states

> Let’s check that the Service is load-balancing the traffic. 

The text then has the student run

    $ kubectl describe services/kubernetes-bootcamp

However, at the end of [Module 4](https://kubernetes.io/docs/tutorials/kubernetes-basics/expose-interactive/), the service has been deleted, thus the command will fail.

**Proposed Solution:**

At the top of Step 2, insert a paragraph similar to the following:

> Re-enable the `kubernetes-bootcamp` service. Refer back to Module 4 for how to create services.

Or alternatively, spell out the command:

> Re-enable the `kubernetes-bootcamp` service.
>     $ kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080

**Page to Update:**
https://k8s.io/docs/tutorials/kubernetes-basics/scale-interactive/

**Comment by mmurphy** [comment]
Hi, is this still an issue? or has it been addressed by https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios/pull/7

The interactive tutorial at https://k8s.io/docs/tutorials/kubernetes-basics/scale-interactive/ works for me

**Comment by Hartmarken348** [comment]
Tutiorl
