### ISSUE TITLE
Issue with k8s.io/docs/user-journeys/users/application-developer/foundational/

### ISSUE THREAD

**Issue by dechang16** [kubernetes/website#8346]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The gray boxes on this page are not formatted correctly

**Proposed Solution:**

The emphasize-box class css styles seem correct. This is probably a markdown issue.

**Page to Update:**
https://kubernetes.io/docs/user-journeys/users/application-developer/foundational/

**Comment by clairealyssa** [comment]
@dechang16 I believe that I've figured it out. According to this Black Friday Markdown Syntax reference, you cannot use Markdown syntax inside of a block-level HTML tag.
So you need to use HTML list syntax when you have a list inside of the div for emphasize-box.

I'm updating the file now.

**Comment by dechang16** [comment]
@clairealyssa awesome thanks!

**Comment by zacharysarah** [comment]
Fixed by #8352.
