### ISSUE TITLE
`{: target="_blank"}` is rendered on page

### ISSUE THREAD

**Issue by bethaitman** [kubernetes/website#8356]
**This is a...** 

- [ ] Feature request
- [x] Bug report

**Problem:**
A few pages are using some markdown to try to open links in a new tab that is just rendered on page. 

<img width="513" alt="screen shot 2018-05-06 at 12 06 52" src="https://user-images.githubusercontent.com/3482051/39676843-0c97cd8c-5126-11e8-9805-8e2d09946358.png">

**Proposed solution:**
Either remove the `{: target=”_blank”}`, or work out how to make that actually work.

**Pages to update:**
The ones I could find are:

* https://kubernetes.io/docs/home/contribute/create-pull-request/
* https://kubernetes.io/docs/home/contribute/review-issues/
* https://kubernetes.io/docs/home/contribute/stage-documentation-changes/

**Comment by mistyhacks** [comment]
I'll take this.

**Comment by zacharysarah** [comment]
Fixed by #8368.
