### ISSUE TITLE
spastic buttons

### ISSUE THREAD

**Issue by pmallory** [kubernetes/website#8369]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
Hovering over the CUJ buttons causes spastic behavior. This video explains it better than words, https://youtu.be/qF5cRLsOmC8

The JS that changes the button's appearance on-hover seems to move the button, which causes it to not be under the cursor.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by zparnold** [comment]
@pmallory Thanks for bringing this to our attention. We have PR fix for this, and should be merged shortly. :)
