### ISSUE TITLE
Generated docs 404 - https://kubernetes.io/docs/reference/generated/kubelet/

### ISSUE THREAD

**Issue by zegl** [kubernetes/website#8387]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Links to generated documents are not working. A few examples:

- https://kubernetes.io/docs/reference/generated/kubelet/
- https://kubernetes.io/docs/reference/generated/kube-proxy/
- https://kubernetes.io/docs/reference/generated/kube-controller-manager/

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by lavalamp** [comment]
https://kubernetes.io/docs/reference/generated/kube-apiserver/ is missing too. Where did it go?
