### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/out-of-resource/

### ISSUE THREAD

**Issue by dcaldwel** [kubernetes/website#8390]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The following sentence

> Operator wants to evict Pods at 95% memory utilization to reduce thrashing and incidence of system OOM.

is slightly misleading because disk swapping should not be enabled so thrashing should not be an issue.

**Proposed Solution:**
Change the sentence to
> Operator wants to evict Pods at 95% memory utilization to reduce incidence of system OOM.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

**Comment by Logan1x** [comment]
@dcaldwel @zacharysarah the issue is solved now.
