### ISSUE TITLE
Common Features Issue with k8s.io/docs/concepts/api-extension/custom-resources/

### ISSUE THREAD

**Issue by neopaf** [kubernetes/website#8394]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
"Common Features" table is broken

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by praseodym** [comment]
I think this is a duplicate of #8271.

**Comment by neopaf** [comment]
right. I see it's fixed now. thanks!
