### ISSUE TITLE
https://kubernetes.io/blog/2018/01/reporting-errors-using-kubernetes-events/ seems broken

### ISSUE THREAD

**Issue by yamt** [kubernetes/website#8396]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/blog/2018/01/reporting-errors-using-kubernetes-events/
just shows "Redirecting to /blog/2018/01/reporting-errors-using-kubernetes-events" for me.
I tried firefox and chrome on osx and firefox on android but no luck.

the next and previous posts seem fine to me.
https://kubernetes.io/blog/2018/01/core-workloads-api-ga/
https://kubernetes.io/blog/2018/03/first-beta-version-of-kubernetes-1-10/

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/blog/2018/01/reporting-errors-using-kubernetes-events/

**Comment by zacharysarah** [comment]
@yamt It appears to be working correctly now. Please feel free to re-open if you notice the behavior again.
