### ISSUE TITLE
Issue with k8s.io/docs/tasks menu

### ISSUE THREAD

**Issue by andreasolund** [kubernetes/website#8398]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

Menu items in the tasks page have been fragmented, probably due to different weights set in their respective index files?

| title | weight | index |
|-------|--------|-------|
| Extend Kubernetes | 90 | content/en/docs/tasks/access-kubernetes-api/_index.md |
| Extend Kubernetes | 150 | content/en/docs/tasks/service-catalog/_index.md |
| Federation - Run an App on Multiple Clusters | 160 | content/en/docs/tasks/administer-federation/_index.md |
| Federation - Run an App on Multiple Clusters | 120 | content/en/docs/tasks/federation/_index.md |

**Proposed Solution:**

Update weights or move files to use the same index file.

**Page to Update:**
https://kubernetes.io/docs/tasks/

**Comment by bep** [comment]
>Menu items in the tasks page have been fragmented, probably due to different weights set in their respective index files?

The weights control sort other _within a section_ (in this case), and they are just relative values. The fragmentation I see is two different and similar sections with the same section title.

I would suggest a reorg. of the sections themselves. If they are different, maybe move both below a common "Federation" section.

**Comment by chenopis** [comment]
Looks like all of the PRs have addressed this issue and it is complete.
