### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/ - Broken link - 404

### ISSUE THREAD

**Issue by antoniocarlossainsburys** [kubernetes/website#8415]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Broken link.
The link (at the bottom) "kubectl proxy" shows me a 404 page

**Proposed Solution:**
Fix the broken link

**Page to Update:**
https://kubernetes.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/

**Comment by pmallory** [comment]
This link is working now

**Comment by zacharysarah** [comment]
Working correctly now, closing.
