### ISSUE TITLE
Minikube error and issue with k8s.io/docs/getting-started-guides/minikube/

### ISSUE THREAD

**Issue by mchawla16** [kubernetes/website#8438]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
1. VM driver is kvm
2. Minikube crashes if started without the --vm-driver=xxx flag

```
minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 150.53 MB / 150.53 MB [============================================] 100.00% 0s
E0509 04:37:28.149683    6430 start.go:159] Error starting host: Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path.

 Retrying.
E0509 04:37:28.150207    6430 start.go:165] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
```
If you wait to read the above error message, the command exits without the user input of Y/n.

**Proposed Solution:**
1. Minikube should not crash.
2. The error message 
`E0509 04:37:28.149683    6430 start.go:159] Error starting host: Error creating host: Error executing step: Running precreate checks.: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path.`
 
could be improved so that it is simply like:

`Error starting host: Error creating host: Error executing step: Running precreate checks.: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path.` 

3. The command should wait for the user to enter `Y/n`.

4. The kubernetes page should be updated with information to install the `kvm2` driver instead of `kvm` as using minikube with kvm gives the following warning:
```
WARNING: The kvm driver is now deprecated and support for it will be removed in a future release.
Please consider switching to the kvm2 driver, which is intended to replace the kvm driver.
```

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/minikube/

Kubernetes Version: v0.26.1(latest)

**Comment by Rajakavitha1** [comment]
@mchawla16  This has been documented in https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm-driver and the https://kubernetes.io/docs/getting-started-guides/minikube/#installation [kvm (driver installation)] does contain a link to https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm-driver

**Comment by benpriestman** [comment]
:+1: 
For a first-time user, the fact that the quickstart points to a deprecated driver is misleading.

**Comment by tsoarescruz** [comment]
First install vm virtualization as virtual-box and this will resolved

**Comment by andradewagner** [comment]
Don't forget to enable the virtualization in BIOS. VT-d or Intel Virtualization technology... something like that. Generally in advanced area.
