### ISSUE TITLE
Explain how to watch

### ISSUE THREAD

**Issue by erictune** [kubernetes/website#844]
Need docs that explain how to watch, without getting deep deep into Go coding.

Something like this:

---

How to watch resources (in this example, services):
1. Get the initial list of services from: `http://localhost:8001/api/v1/namespaces/kube-system/services` 
2. extract the resourceVersion (the first one) as RV.
3. Watch with `http://localhost:8001/api/v1/namespaces/kube-system/services?watch=true&resourceVersion=$RV`
4. When the watch connection ends, GOTO 1.

When you re-list in step 1 after step 4, it is on you to skip the ones you have already configured.  You may be able to tell this from the status field, or you can add an annotation to the object to help you remember which ones you finished.

---

Example user question:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/eB539qiOY2A/a1tMzmJNCwAJ

**Comment by tengqm** [comment]
ref: kubernetes/kubernetes#10506
