### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by pjfoley** [kubernetes/website#8455]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The github link [1] to the tutorial repository is broken.  I think it should be this link [2].

[1] - https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics
[2] - https://github.com/kubernetes/website/tree/master/content/en/docs/tutorials/kubernetes-basics
**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-intro/

**Comment by ajaeger** [comment]
Should be fixed now, see #8430

**Comment by ajaeger** [comment]
/triage duplicate

See #8547

**Comment by shubheksha** [comment]
Closing this as it's a duplicate.
/close
