### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/configure-pod-configmap/

### ISSUE THREAD

**Issue by timtmok** [kubernetes/website#8456]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
Dead links in the docs
The links in the section for creating a config map for kubectl describe and get lead to 404.
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands/#describe
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands/#get

**Proposed Solution:**
Fix the links.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

**Comment by ajaeger** [comment]
Should be fixed now, see #8430 - could you confirm, please?

**Comment by timtmok** [comment]
Perfect. It's fixed!
