### ISSUE TITLE
Documentation unclear about PATH operation on resource Issue with k8s.io/docs/tasks/run-application/update-api-object-kubectl-patch/

### ISSUE THREAD

**Issue by etsangsplk** [kubernetes/website#8464]
Does Patch creates a new version of resource object??? Can you provide example to show to prove or disprove? The doc is very unclear about this. 

Is it just like HTTP PATCH From wiki it show that
"The main difference between the PUT and PATCH method is that the PUT method uses the request URI to supply a modified version of the requested resource which replaces the original version of the resource whereas the PATCH method supplies a set of instructions to modify the resource."

**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by CaoShuFeng** [comment]
> Does Patch creates a new version of resource object???

Patch modifies the original resource object. In the document, the `deployment` object is modified.

And the new created pods is not created by `patch` directly. kube-controller-manager created those new pods according to the new verison of deployment.
