### ISSUE TITLE
kubectl reference pages are gone

### ISSUE THREAD

**Issue by ryanmcginnis** [kubernetes/website#8469]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The reference pages for kubectl were deleted or moved without a redirect, which breaks all existing Kubernetes Engine documentation and all those links. Honestly, this is a frustrating maintenance burden, and it would be great if such future changes accommodated outdated links.

**Proposed Solution:**
Provide new links and set up a redirect for the old ones.

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubectl/kubectl/

**Comment by ajaeger** [comment]
Fixed with https://github.com/kubernetes/website/pull/8430

**Comment by ryanmcginnis** [comment]
Thanks!

**Comment by ajaeger** [comment]
it's still a 404 - a redirect is missing at least.

**Comment by steveperry-53** [comment]
Added redirect.
https://kubernetes.io/docs/reference/generated/kubectl/kubectl/
redirects to
https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands
