### ISSUE TITLE
Issue with k8s.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

### ISSUE THREAD

**Issue by jitendrabhalothia** [kubernetes/website#8483]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
**kubectl get service frontend**
The external IP field may take some time to populate. If this is the case, the external IP is listed as <pending>.

**NAME       CLUSTER-IP      EXTERNAL-IP   PORT(S)  AGE
  frontend         10.51.252.116       <pending>        80/TCP      10s**

Repeat the same command again until it shows an external IP address:

**Proposed Solution:**
**Let's not to say repeat the same command until it shows an external IP address, let's use the --watch switch**
Now :
**kubectl get service frontend --watch**

Better to add  "--watch "  switch, for instance, "kubectl get service frontend --watch" instead of telling to keep executing the same command for recent updates in the pod state.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/connecting-frontend-backend/

**Comment by steveperry-53** [comment]
I will ask @juneharton to work on this.

**Comment by jitendrabhalothia** [comment]
Thanks, @steveperry-53.

@juneharton let me know if you need any clarification.

**Comment by jitendrabhalothia** [comment]
@lucperkins are we adding watch switch to the requested doc?

**Comment by lucperkins** [comment]
@jitendrabhalothia Yes. See pull request #9129 for the proposed changes.
