### ISSUE TITLE
Issue with k8s.io/docs/admin/high-availability/building/

### ISSUE THREAD

**Issue by asad26** [kubernetes/website#8485]
I want to have Kubernetes HA cluster setup. I was going through this page (https://kubernetes.io/docs/admin/high-availability/building/) but there are some concepts which I didn't understand. Do you have any other document for setting up HA cluster (for instance, 3 master nodes)?

Also, the YAML files (etcd.yaml, kube-apiserver.yaml, kube-scheduler.yaml, etc) mentioned on the same web page are not available anymore. They give "404 page not found" error. Where can I get these files now?

Waiting for your reply. Thanks in advance

**Comment by PAStheLoD** [comment]
There are a few copies of the etcd.yaml scattered across the 'net:

https://github.com/kubernetes/website/blob/7f3b633aa0332b8a1ddc61b6d4e2e34fc6dd5522/content/en/docs/setup/independent/high-availability.md#-tabs-nameetcd_mode-

http://huxos.me/kubernetes/2017/09/19/kubernetes-cluster-03-kube-master.html

But of course it'd be much better if users wouldn't have to trawl old commits and random blogs to get them.

**Comment by PAStheLoD** [comment]
After looking a bit more for the files, they just got lost in the Hugo conversion: https://github.com/kubernetes/website/tree/master/content/en/docs/admin/high-availability

**Comment by asad26** [comment]
@PAStheLoD Thanks for sharing this.
The links are very helpful.

**Comment by neolit123** [comment]
@asad26 
> but there are some concepts which I didn't understand

hi, can you provide more info on which concepts are unclear to you.

**Comment by neolit123** [comment]
there seems to be ongoing effort to simplify the page based on this issue by @mbert :
https://github.com/kubernetes/website/issues/8493

it's probably best if we unify this in a single PR.

**Comment by mbert** [comment]
My PR is limited to the instructions for setting up multi-master clusters using `kubeadm`. It fixes something that is incorrect atm, and it does not really simplifiy anything.

**Comment by neolit123** [comment]
ok, understood.

**Comment by neolit123** [comment]
@Bradamant3 @mistyhacks can you please advise on how can i make these YAML links work:

e.g. in here there is a "etcd.yaml"
https://kubernetes.io/docs/admin/high-availability/building/

should we link to the RAW files in the github repository?:
https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/admin/high-availability/etcd.yaml

or to the github view of the file:
https://github.com/kubernetes/website/blob/master/content/en/docs/admin/high-availability/etcd.yaml

opening the links like so doesn't work:
https://kubernetes.io/docs/admin/high-availability/etcd.yaml

thanks

**Comment by steveperry-53** [comment]
See #8931 for an example of how to link to yaml files. In that PR, also see the discussion about changing the way we place yaml files in directories. Also in that PR, see the comment that @Bradamant3 might be wanting to remove https://kubernetes.io/docs/admin/high-availability/building/.

**Comment by neolit123** [comment]
@steveperry-53

thank you for the details. this leaves too many unknowns.
i'm probably just going to fix the YAML links tomorrow and watch this space for further developments.

**Comment by neolit123** [comment]
the HA document was moved and refactored.
for now it's here https://kubernetes.io/docs/setup/independent/high-availability/, but it will move again because of the ongoing kubeadm docs restructure.
closing.

/close
