### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by plecmc** [kubernetes/website#8486]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The link **_https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics_** to github repository is break and get 404 error 

**Proposed Solution:**
Update the link

**Page to Update:**
https://kubernetes.io/...

**Comment by ajaeger** [comment]
/triage duplicate

See #8547

**Comment by shubheksha** [comment]
Closing this as it's a duplicate.
/close
