### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by GDICommander** [kubernetes/website#8492]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The "GitHub repository" link at the bottom of the page leads to a 404 Not Found page.

**Proposed Solution:**

Point to an existing GitHub repository.

**Page to Update:**
https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics

**Comment by ajaeger** [comment]
/triage duplicate

Duplicate of #8547

**Comment by shubheksha** [comment]
Closing this as it's a duplicate.
/close
