### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/components/

### ISSUE THREAD

**Issue by InTheCloudDan** [kubernetes/website#8494]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Link to https://kubernetes.io/docs/admin/kube-controller-manager/ redirects to 404 at https://kubernetes.io/docs/reference/generated/kube-controller-manager/ 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/components/
https://kubernetes.io/docs/reference/generated/kube-controller-manager/

**Comment by dhawal55** [comment]
Did this break recently? Is there any other place where I can reference these docs?
