### ISSUE TITLE
Access/authn/authz content missing from left nav TOC after Hugo migration

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#8538]
**This is a...** 

- [X] Bug Report

**Problem:**
Issue is probably bigger than indicated in issue title. It look as though all | much of | some of the content that lives in the website repo here: https://github.com/kubernetes/website/tree/master/content/en/docs/admin
is not included in any visible TOC. It appears from search results, but I haven't found any mechanism to navigate to it from the site. Will gladly accept different results!

**Proposed Solution:**
Move content in repo into the appropriate part of the source tree (probably /content/en/docs/reference which would let it appear where it used to appear in the Jekyll builds. Additional weighting undoubtedly required -- pretty sure this isn't content well served by an alphabetical listing). 

Long-term solutions not currently in scope given docs resources (or lack thereof).

Old TOC provided here for reference in case it's useful: https://github.com/kubernetes/website/blob/master/data/reference.yml

**Page to Update:**
N/A

**Comment by zacharysarah** [comment]
This is actionable; it requires cleaning up the reference section and making sure that duplicate content is removed and organized correctly. Link to relevant Slack convo: https://kubernetes.slack.com/archives/C1J0BPD2M/p1528161756000270

**Comment by steveperry-53** [comment]
@Bradamant3 OK to close this now?
