### ISSUE TITLE
Issue with k8s.io/docs/concepts/example-concept-template/

### ISSUE THREAD

**Issue by bryanl** [kubernetes/website#8545]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

This page looks like a template

![2018-05-15_08-22-41](https://user-images.githubusercontent.com/240/40056365-3449566c-5819-11e8-92a9-bdea88c9a6b4.png)

**Proposed Solution:**

It should be removed

**Page to Update:**
https://kubernetes.io/...

**Comment by cstoku** [comment]
I think this issue was fixed by #8633
