### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

### ISSUE THREAD

**Issue by pdtoal** [kubernetes/website#8558]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
Link to Kubernetes-Basic GitHub repository shows a 404.

**Proposed Solution:**

**Page to Update:**
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-intro/

**Comment by ajaeger** [comment]
/triage duplicate

Duplicate of #8547

**Comment by shubheksha** [comment]
Closing this as it's a duplicate.
/close
