### ISSUE TITLE
Markdown file with invalid yaml block is not parsing correctly.

### ISSUE THREAD

**Issue by cjwagner** [kubernetes/website#8568]
This file: https://github.com/kubernetes/website/blob/master/archetypes/default.md
is not being parsed correctly by Prow's repoowners package because it is not valid yaml
```
error converting YAML to JSON: yaml: line 1: did not find expected key
```
Please correct this.
@bep

**Comment by bep** [comment]
>is not being parsed correctly by Prow's repoowners package because it is not valid yaml

It is a Hugo artchetype template. It is not meant to be valid YAML. Please refer to the Hugo documentation about this. It is a cool feature.
