### ISSUE TITLE
Issue with k8s.io/docs/reference/glossary/ | CNI is missing

### ISSUE THREAD

**Issue by JasonSwindle** [kubernetes/website#8576]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
```CNI | Container Network Interface``` is missing from the glossary.

**Proposed Solution:**
Add ```CNI | Container Network Interface``` to the glossary.

**Page to Update:**
http://k8s.io/docs/reference/glossary/

**Comment by d-nishi** [comment]
@JasonSwindle perhaps you can add the definition:
CNI plugins are a type of Network plugins in Kubernetes that adheres to the appc/CNI specification. Refer to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni for more details.

**Comment by codelearner3012** [comment]
Hey , i'll be working on this.
