### ISSUE TITLE
Issue with k8s.io/docs/reference/setup-tools/kubeadm/implementation-details/

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes/website#8591]
**This is a...** 

- [x] Bug Report
- [ ] Feature Request

**Problem:**

The paragraph "Core design principles" looks like it's supposed to be an itemised list, however it is all rendered as regular text.
This maybe/probably has to do with the switch to hugo?

**Proposed Solution:**

Fix the source markdown code of that page.

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/

**Comment by neolit123** [comment]
/assign

thanks for the report.

**Comment by mistyhacks** [comment]
@neolit123 do you mind if I take this one?

**Comment by neolit123** [comment]
sure thing, @mistyhacks 

/assign @mistyhacks 
/unassign @neolit123
