### ISSUE TITLE
Issue with k8s.io/docs/concepts/cluster-administration/networking/

### ISSUE THREAD

**Issue by antonysandler** [kubernetes/website#8592]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
In the document, the word "Premise" is used incorrectly, should be premises

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by steveperry-53** [comment]
Agree. We should change on-premise environments to on-premises environments. And we should change on-premise deployments to on-premises deployments.

/assign @juneharton

**Comment by antonysandler** [comment]
Steve,
   Thanks!   You are not the same Steve Perry I worked with at Geisinger 
Health Plan, are you?


Kindest Regards,
Tony


Antony Sandler
AES/PHEAA 
Solution Architect
  717.720.2646 
Email - asandler@pheaa.org
