### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by albertchan** [kubernetes/website#8594]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

Link to the GitHub repository returns 404.

**Proposed Solution:**

Update link to appropriate location in repo.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by ajaeger** [comment]
/triage duplicate

Duplicate of #8547

**Comment by shubheksha** [comment]
Closing this as it's a duplicate.
/close
