### ISSUE TITLE
blog stylesheet is not responsive

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#8605]
The stylesheet used in the blog doesn't appear to be responsive. Here is one screenshot to illustrate one of the issues (I don't think this is the only issue, there are a few more that I've seen).

<img width="830" alt="screenshot 2018-05-18 06 30 30" src="https://user-images.githubusercontent.com/251467/40217541-4014ee54-5a65-11e8-8aef-58c1460f8b50.png">

**Comment by tnir** [comment]
@errordeveloper Sorry for missing to file an issue, but I've created a PR #8610.

**Comment by tnir** [comment]
@errordeveloper A quick CSS hack was just delivered at https://kubernetes.io/blog/, so further improvements are still welcome 😄

**Comment by kbarnard10** [comment]
@tnir Thanks for doing that! I will look into further improvements as well.
