### ISSUE TITLE
blog authors

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/website#8607]
As a blog reader, I'd like to know who wrote some article that I'm reading.

Right now it's up to the author to indicate who they are, but this is not what you normally see on any other blog out there. Unlike docs in general, blog articles tend to have opinions (even slightest) and authors have employers also, and there references to person(s) quite often also. I think this must be a general feature (a required field), and not a case-by-case thing with author's name mentioned amongst other things in the text.

For example, [Zero-downtime Deployment in Kubernetes with Jenkins](https://kubernetes.io/blog/2018/04/30/zero-downtime-deployment-kubernetes-jenkins/) has no indication of who wrote it. For example,  this article starts with "Ever since we added..." – who are 'we' in this case? I'd think they were referring to the community as a whole, but it sounds more like they are talking about Azure.

I suppose I can look at git commit, but that's implementation detail, and I don't have time for it, also committer maybe a different person from the one who actually wrote it (it is the case for [Developing on Kubernetes](https://kubernetes.io/blog/2018/05/01/developing-on-kubernetes/) that @mhausenblas and I wrote.

**Comment by mhausenblas** [comment]
@kbarnard10 any news here?
