### ISSUE TITLE
Issue with k8s.io/docs/tutorials/stateful-application/cassandra/

### ISSUE THREAD

**Issue by louisscruz** [kubernetes/website#8639]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

When I follow [this tutorial](https://kubernetes.io/docs/tutorials/stateful-application/cassandra/), the second pod never moves past a `Pending` status. The documentation says it could take up to 10 minutes, but I'm beyond that at this point:

```
$ kubectl get pods -o wide
NAME          READY     STATUS    RESTARTS   AGE       IP           NODE
cassandra-0   1/1       Running   0          30m       172.17.0.6   minikube
cassandra-1   0/1       Pending   0          30m       <none>       <none>
```

```
$ kubectl get statefulset cassandra
NAME        DESIRED   CURRENT   AGE
cassandra   3         2         29m
```

```
$ kubectl exec cassandra-0 -- nodetool status
Datacenter: DC1-K8Demo
======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns (effective)  Host ID                               Rack
UN  172.17.0.6  99.59 KiB  32           100.0%            d448ad28-c79f-4731-8777-672f196e2b70  Rack1-K8Demo
```

**Proposed Solution:**

I'm not sure.

**Page to Update:**

Potentially: https://kubernetes.io/docs/tutorials/stateful-application/cassandra/

**Comment by louisscruz** [comment]
Just an update:

```
kubectl get pods -o wide
NAME          READY     STATUS    RESTARTS   AGE       IP           NODE
cassandra-0   1/1       Running   0          1d        172.17.0.6   minikube
cassandra-1   0/1       Pending   0          1d        <none>       <none>
```

**Comment by louisscruz** [comment]
After trying some different things I got this to work. When I hit the problem I specifically had to do the following:

1. `kubectl delete storageclass fast`
2. `minikube delete && ~/.minikube`
  * **THIS WAS KEY**
3. `minikube start --memory 5120 --cpus=4`
4. `kubectl create -f cassandra-service.yaml`
5. `kubectl create -f cassandra-statefulset.yaml`

I'm not entirely sure what the initial problem was, so I will leave it to you to add something to the documentation. Hopefully anyone else who hits this finds this issue.

**Comment by louisscruz** [comment]
Also, the nodetool command through needs to be: `kubectl exec -ti cassandra-0 -- nodetool status`

**Comment by lucperkins** [comment]
@louisscruz Hmmm. I wasn't able to recreate your issue following the instructions in the doc (i.e. allocating 5 GB of memory and 4 CPUs to Minikube). For now, I'm going to leave the doc as-is. Please let us know if you continue to have issues!

**Comment by louisscruz** [comment]
I just came back to say that even though the tutorial is very different now I ran into the same exact problem. Fortunately, the steps I outlined above did it for me again. I must have some weird environment trouble going on. Anyways, so long as it eventually works! Now seeing:

```
NAME          READY     STATUS    RESTARTS   AGE
cassandra-0   1/1       Running   0          3m
cassandra-1   1/1       Running   0          2m
cassandra-2   1/1       Running   0          1m
```
