### ISSUE TITLE
Issue with k8s.io/docs/admin/cluster-large/

### ISSUE THREAD

**Issue by PaoloGallina** [kubernetes/website#8640]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
In https://kubernetes.io/docs/admin/cluster-large/ there is an error when it states: 
"On GCE/Google Kubernetes Engine, and AWS, kube-up automatically configures the proper VM size for your master depending on the number of nodes in your cluster. On other providers, you will need to configure it manually. For reference, the sizes we use on GCE are
Note that these master node sizes are currently only set at cluster startup time, and are not adjusted if you later scale your cluster up or down (e.g. manually removing or adding nodes, or using a cluster autoscaler)."

In GKE the master size changes if the number of nodes is modified.
Therefore it is not true that the size of the Master is currently only set at cluster startup time.

"Master VM is automatically scaled, upgraded, backed up and secured "
Source: https://cloudplatform.googleblog.com/2017/11/Cutting-Cluster-Management-Fees-on-Google-Kubernetes-Engine.html

**Page to Update:**
https://kubernetes.io/docs/admin/cluster-large/

**Comment by kmassada** [comment]
#9276 should fix this.

**Comment by kmassada** [comment]
Woops did not see that the previous comment did the same thing, #9226 looks more complete, but still championing the more subtle change.

**Comment by lucperkins** [comment]
@kmassada In this case I do think that an "aside"-style note is warranted. So I'm going to close this. Sorry again for the mix-up! Thanks a ton for helping out!

**Comment by lucperkins** [comment]
(Oops, accidentally closed the issue. #9226 is still pending)
