### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/manage-compute-resources-container/

### ISSUE THREAD

**Issue by jiaxuanzhou** [kubernetes/website#8646]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
no introduction of limits of GPU

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
@jiaxuanzhou Could you possibly provide a bit more information about the specific changes that you'd like to see?
