### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by Coolfeather2** [kubernetes/website#8648]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://kubernetes.io/docs/reference/kubectl/kubectl/
kubectl cp links to 
https://kubernetes.io/docs/reference/kubectl/kubectl/kubectl_cp.md
results in 404

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/kubectl/

**Comment by CaoShuFeng** [comment]
#8651

**Comment by paleale** [comment]
Issue relates to all links in the 'See also' section at this page.
