### ISSUE TITLE
Issue with k8s.io/docs/reference/labels-annotations-taints/

### ISSUE THREAD

**Issue by 4194sunny** [kubernetes/website#8655]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
Since there are has been no update on this, I'm closing it.
@4194sunny, feel free to reopen and update it or open another issue.
/close
