### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by axelpale** [kubernetes/website#8659]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The [Github link](https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics) shows 404.

**Proposed Solution:**

Replace the link URL with a working one. I could not find the correct one.

**Page to Update:**
https://kubernetes.io/...

**Comment by cstoku** [comment]
I think it will be fixed in #8763. 🎉

**Comment by lucperkins** [comment]
This seems to have been fixed in one of the PRs associated with #8763.

@axelpale Please re-open the issue if you're continuing to have issues.
