### ISSUE TITLE
Issue with k8s.io/docs/home/

### ISSUE THREAD

**Issue by raghavp96** [kubernetes/website#8661]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
When a user arrives at https://kubernetes.io/docs/home/?path=users&persona=app-developer&level=foundational, under the "I am a ...." section, they have to selecte "Application Developer" or "Cluster Operator". 
When hovering over these, the view changes from 
```html
<div class="docsection1" id="persona-definition" style="display: none; visibility: hidden;">.</div>
```
to:
```html
<div class="docsection1" id="persona-definition" style="display: none; visibility: visible;">.</div>
```

but it looks the hovering shifts the position of the buttons upwards. Hovering in certain areas causes the pane to convulse rapidly (On desktop).

**Proposed Solution:**
Maintain the position of the button even when `:hover` applies

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
confirmed.

/kind bug

**Comment by neolit123** [comment]
looks resolved.
/close
