### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/namespaces/

### ISSUE THREAD

**Issue by akostadinov** [kubernetes/website#8675]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
There is no indication how to recognize easily which objects are namespaced and which are not.

**Proposed Solution:**
Add information about easily identifying which object kind is namespaced and which one is not.

**Page to Update:**
k8s.io/docs/concepts/overview/working-with-objects/namespaces/

**Comment by lucperkins** [comment]
@akostadinov It turns out that this is super easy to do. Check PR #9436 for a sneak preview 👍

**Comment by akostadinov** [comment]
Looks real nice, thank you for digging that out!

**Comment by nikhita** [comment]
Isn't this fixed by https://github.com/kubernetes/website/pull/9436?
