### ISSUE TITLE
Issue with k8s.io/docs/admin/high-availability/building/

### ISSUE THREAD

**Issue by sczachariah** [kubernetes/website#8677]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The links under section "Master elected components", to kube-scheduler.yaml and kube-controller-manager.yaml are hitting 404.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/admin/high-availability/building/

**Comment by lucperkins** [comment]
It looks like this bug is no longer an issue, as this section is no longer in the docs
