### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by markediez** [kubernetes/website#8678]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics does not exist

**Proposed Solution:**
Update the URL to point to the proper location

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by cstoku** [comment]
I think it will be fixed in #8763. 🎉
