### ISSUE TITLE
I wish /docs/getting-started-guides/binary_release/ The part about seeing supported providers by going to the `/cluster` directory in the repo was up to date

### ISSUE THREAD

**Issue by jjm3x3** [kubernetes/website#8690]
The part about seeing supported providers by going to the `/cluster` directory in the repo appears to be out of date.

**Comment by lucperkins** [comment]
@jjm3x3 Hmmm. I'm not seeing what you're referring to in [this doc](https://kubernetes.io/docs/setup/building-from-source/) (there seems to be a redirect). Could you confirm whether this is still an issue?
