### ISSUE TITLE
Issue with k8s.io/docs/concepts/configuration/manage-compute-resources-container/

### ISSUE THREAD

**Issue by leandrodvd** [kubernetes/website#8701]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
At the Meaning of CPU topic of docs page https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ it mentions CPU resources of Google and AWS. I'm using IBM Cloud infrastructure and I believe it would be helpful to have that same 1-bullet explanation in the the meanin gof CPU in the IBM kubernetes infrastructure.

**Proposed Solution:**
Add 1 bullet explaining the meaning of CPU in the IBM Cloud kubernetes infrastructure (and so far I don't know the explanation for that)

**Page to Update:**
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

**Comment by lucperkins** [comment]
@leandrodvd I've done some searching and I'm afraid I can't seem to determine what the proper terminology is. I did [tweet](https://twitter.com/lucperkins/status/1015272424890236933) at IBM Cloud, though, so we'll see if we can figure it out that way 😄
