### ISSUE TITLE
More languages?

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/website#8704]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**

If someone wants to create a new language translation of the websites/docs is there documentation on how to get started?

**Proposed Solution:**

Docs on how to produce languages docs including adding a new translation. If this already exists or there is a place I can point people... please send me in the right direction.

Note, in my case I'm looking at Korean.

**Comment by cstoku** [comment]
I'm also interested in creating Japanese translation page, but I do not know what to do. :persevere:

**Comment by xlgao-zju** [comment]
I am looking forward to more Chinese docs. 😆

**Comment by cstoku** [comment]
https://kubernetes.io/docs/home/contribute/localization/

There is such a page, but it is a bit old.

**Comment by gochist** [comment]
Related PR for Korean translation: https://github.com/kubernetes/website/pull/8636

**Comment by micheleberardi** [comment]
i can help with italian
