### ISSUE TITLE
Documentation issue with k8s.io/docs/admin/high-availability/building/

### ISSUE THREAD

**Issue by aaronsesco** [kubernetes/website#8710]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report
- [x]Documentation Error

**Problem:**
1. outdated link for kubelet binary --> https://storage.googleapis.com/kubernetes-release/release/v0.19.3/bin/linux/amd64/kubelet

2. link broken for 'default-kubelet' --> https://kubernetes.io/docs/admin/high-availability/default-kubelet

"If you are extending from a standard Kubernetes installation, the kubelet binary should already be present on your system. You can run which kubelet to determine if the binary is in fact installed. If it is not installed, you should install the **kubelet binary** and **default-kubelet** scripts."
<hr>

3. link broken for 'etcd.yaml' --> https://kubernetes.io/docs/admin/high-availability/etcd.yaml
 
"On each node, copy the **etcd.yaml** file into /etc/kubernetes/manifests/etcd.yaml"
 
<hr>

4. link broken for kube-apiserver.yaml --> https://kubernetes.io/docs/admin/high-availability/kube-apiserver.yaml

"Once these files exist, copy the **kube-apiserver.yaml** into /etc/kubernetes/manifests/ on each master node"

<hr>

5. link broken for kube-scheduler.yaml --> https://kubernetes.io/docs/admin/high-availability/kube-scheduler.yaml
6. link broken for kube-controller-manager.yaml --> https://kubernetes.io/docs/admin/high-availability/kube-controller-manager.yaml

"Next, set up the descriptions of the scheduler and controller manager pods on each node by copying **kube-scheduler.yaml** and **kube-controller-manager.yaml** into the /etc/kubernetes/manifests/ directory."

**Proposed Solution:**
Fix links: point to correct location for dafault-kubelet scripts, if file(s) still exist.

**Page to Update:**
https://kubernetes.io/docs/admin/high-availability/building/

**Comment by cstoku** [comment]
I think the problem of 3 to 6 will be fixed by #8700 .

**Comment by Bradamant3** [comment]
It's also still an open question whether we should continue to maintain this page. It's pretty out of date altogether and is on the list for further triage by docs maintainers and sig-cluster-lifecycle.

**Comment by neolit123** [comment]
the HA and HA-ETC documentation received an overhaul in 1.11:
https://kubernetes.io/docs/setup/independent/high-availability/
https://kubernetes.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/

all the new edits were the result of combined SIG efforts and based on existing proposals for improvements.

closing until further notice.
/close
