### ISSUE TITLE
Issue with k8s.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

### ISSUE THREAD

**Issue by pierrchen** [kubernetes/website#8717]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The url[1] referenced below (by word Client Libraries) is broken.
[1] https://kubernetes.io/docs/reference/client-libraries/

>To work with Kubernetes objects–whether to create, modify, or delete them–you’ll need to use the Kubernetes API. When you use the kubectl command-line interface, for example, the CLI makes the necessary Kubernetes API calls for you. You can also use the Kubernetes API directly in your own programs using one of the Client Libraries.

**Proposed Solution:**

Replace the link with [2], which is a go client, but not sure if there is official client libs for other languages. 

[2]https://github.com/kubernetes/client-go

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/

**Comment by cstoku** [comment]
This Issue is duplicated with #8768. and it will fixed by #8734.
