### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by leandroshp** [kubernetes/website#8720]
**This is a...** 

- [ ] Feature Request
- [ X ] Bug Report

**Problem:**
Looks like the link to github is broken. This is given a 404 on github: https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by cstoku** [comment]
I think it will be fixed in #8763. 🎉
