### ISSUE TITLE
Generated kubeadm docs for 1.11 are inconsistently formatted during release cycle

### ISSUE THREAD

**Issue by Bradamant3** [kubernetes/website#8723]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
kubeadm docs generated during the 1.11 release cycle by anyone other than @tengqm do not include the HTML formatting that was added for 1.10. This is because https://github.com/kubernetes-incubator/reference-docs/pull/47 is not merged.

**Proposed Solution:**
Life with mismatched formatting until 1.11 release. sig-docs regenerates all generated docs per release. At release time, if the PR is merged we'll have pretty tables for everything. If it isn't merged, we'll have less pretty lists for everything. But the inconsistencies will be gone.

**Page to Update:**
includes for siblings of https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm/
(source at https://github.com/kubernetes/website/tree/master/content/en/docs/reference/setup-tools/kubeadm/generated)

**Comment by lucperkins** [comment]
@Bradamant3 Was this addressed by #8617? If so, could you close this issue?
