### ISSUE TITLE
Create a SECURITY_CONTACTS file.

### ISSUE THREAD

**Issue by jessfraz** [kubernetes/website#8724]
As per the email sent to kubernetes-dev[1], please create a SECURITY_CONTACTS
file.

The template for the file can be found in the kubernetes-template repository[2].
A description for the file is in the steering-committee docs[3], you might need
to search that page for "Security Contacts".

Please feel free to ping me on the PR when you make it, otherwise I will see when
you close this issue. :)

Thanks so much, let me know if you have any questions.

(This issue was generated from a tool, apologies for any weirdness.)

[1] https://groups.google.com/forum/#!topic/kubernetes-dev/codeiIoQ6QE
[2] https://github.com/kubernetes/kubernetes-template-project/blob/master/SECURITY_CONTACTS
[3] https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance-template-short.md

**Comment by xlgao-zju** [comment]
I'd like to help this, just like what I do in [kubernetes/kubeadm/#861](https://github.com/kubernetes/kubeadm/pull/861). But I need to know whom should I add.
@mistyhacks @Bradamant3

**Comment by zacharysarah** [comment]
@xlgao-zju 👋 Thanks for offering--would appreciate a review on #8824.

**Comment by sftim** [comment]
Ah! This repo's primary branch is called `main`, @k8s-triage-robot.

**Comment by zacharysarah** [comment]
Whew, I had security palpitations for a moment. 😅
