### ISSUE TITLE
Issue with k8s.io/docs/editdocs/

### ISSUE THREAD

**Issue by tivvit** [kubernetes/website#8726]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
I wanted to fix broken link but the contribution link is broken too
https://github.com/kubernetes/website/edit/master/content/en/docs/admin/extensible-admission-controllers.md at https://kubernetes.io/docs/editdocs/#docs/admin/extensible-admission-controllers.md

**Proposed Solution:**
I did not find the correct document in the repo

**Page to Update:**
https://kubernetes.io/...

**Comment by cstoku** [comment]
In the current Master branch, the page has changed, and there is no link written on Issue.

In addition, `/ docs / admin / extensible-admission-controllers.md` has a redirect path in` static / _redirects` and is redirected to the correct link destination.

I think that there is no problem in the next release, so I think you can close it. 👍

**Comment by tivvit** [comment]
I find it quite bad when some links in the docs are not working (even temporarily) and it cannot be reported - That is how I found out.

But if that will be fixed soon we can probably close this issue :)

**Comment by lucperkins** [comment]
Those "editdocs" pages are automatically generated, so you can navigate to https://kubernetes.io/docs/editdocs/#docs/foo/bar/baz.md and see a working page with links for "Edit content/en/docs/foo/bar/baz.md" and "View content/en/docs/foo/bar/baz.md on GitHub." Those links, of course, would not work.

So I will close the issue. I can see how this may be frustrating but at the moment we don't really have a way of verifying that the doc referred to in the `/editdocs/...` URL currently exists, as the page is statically generated.
