### ISSUE TITLE
Improve HA etcd with kubeadm guide

### ISSUE THREAD

**Issue by chuckha** [kubernetes/website#8730]
**This is a...** 
- [x] Feature Request

**Problem:**
The Guide is incomplete or leaves much to be desired

**Proposed Solution:**

- [x] Add an example for ssh/file copy infrastructure
- [x] Add words about how kubeadm can generate certs so no additional tools are necessary
- [x] At the very least clarify the bash script, consider making it copy/pastable with for loops and that
- [x] What's next link needs point to https://kubernetes.io/docs/setup/independent/high-availability/

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/

cc @rdodev

**Comment by rdodev** [comment]
@chuckha both of the above PRs have been merged. Those two can be marked as done.

**Comment by chuckha** [comment]
nice work! thanks for the prs!

**Comment by chuckha** [comment]
I think this is closed with most recent update
