### ISSUE TITLE
Broken link in setting up ha guide

### ISSUE THREAD

**Issue by chuckha** [kubernetes/website#8731]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
- [ ] "how to create loadbalancers " link is broken
- [ ] the numbered list at the bottom go 1. and 1., should increment 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

cc @rdodev

**Comment by lucperkins** [comment]
@chuckha The issues you point out appear to have already been fixed. I'm going to close this for now, but please feel free to re-open if you think I've closed it in error!
