### ISSUE TITLE
Issue with k8s.io/docs/tasks/manage-hugepages/scheduling-hugepages/

### ISSUE THREAD

**Issue by subrnath** [kubernetes/website#8744]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
I would like to use this feature in Kubernetes 1.10. Host OS is Ubuntu 16.04.4. In the worker node, i have reserved huge pages 

$ cat /proc/meminfo  | grep -i huge
AnonHugePages:    235520 kB
HugePages_Total:    4096
HugePages_Free:     4096
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB

$ cat /sys/devices/system/node/node0/hugepages/hugepages-2048kB/free_hugepages
2048
$ cat /sys/devices/system/node/node1/hugepages/hugepages-2048kB/free_hugepages
2048

$ cat /proc/mounts | grep -i huge
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0

Following are the deployment file changes -
            limits:
              cpu: 4
              memory: 4Gi
              hugepages-2Mi: 1024Mi

          volumeMounts:
              - name: hugepage
              mountPath: /hugepages
      volumes:
        - name: hugepage
          emptyDir:
            medium: HugePages

But the pods are not getting scheduled. They are coming in "Pending state". Following error is seen from "kubectl describe pods" -

Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  14s (x7 over 45s)  default-scheduler  0/6 nodes are available: 5 node(s) didn't match node selector, 6 Insufficient hugepages-2Mi.

Q-1 , As per the documentation, this feature is enabled by default in Kubernetes 1.10. hence i assume no long feature gate to be activated. Is this correct?
Q-2. Why it's showing "Insufficient hugepages-2Mi" for matched node ( by label)  although 2MB huge page is already been allocated?
Q-3 journalctl is not showing any error both on the API-server as well as on the worker node where it's supposed to be deployed.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

v1.10.2

**Comment by subrnath** [comment]
Thanks. In the "kubectl describe nodes <node name>" , we can see  hugepages-1Gi: 0 and hugepages-2Mi: 0.

>>If they are not, you will need to update the nodes.
Do you mean manually ? how to update it manually?


Capacity:
 cpu:                48
 ephemeral-storage:  960317832Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             264110532Ki
 pods:               110
Allocatable:
 cpu:                48
 ephemeral-storage:  885028912506
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             264008132Ki
 pods:               110

**Comment by tengqm** [comment]
there could be many reasons behind this silent failure. One possible reason is that the hugetlb cgroup support is missing or not enabled on your node in which case the capacity report fails silently. Better raise your question to stackoverflow or slack channel. This doesn't seem a doc error.

**Comment by subrnath** [comment]
Ok.. Issue has been identified. Hugepage allocation to be done before "kubeadm join" i.e. before the worker node joins the cluster.

**Comment by Globegitter** [comment]
@subrnath just running into the same issue with a https://github.com/kubernetes/kops operated cluster using CoreOS - What did you have to do to get around the issue?

**Comment by adamcharnock** [comment]
Small note for anyone coming across this issue like me, after making the sysctl change to enable huge pages you'll need to restart the kubelet. I'm using RKE2, so for me this was:

    sudo service rke2-agent restart
