### ISSUE TITLE
Review GCE content in "Use a Service to Access an Application in a Cluster"

### ISSUE THREAD

**Issue by eliza411** [kubernetes/website#8764]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
On PR #8699 addressing some code formatting issues, @mistyhacks suggested that the GCE information in steps 7 and 8 of the "Creating a service for an application running in two pods" section seems strange. The PR has been merged, and I'm opening this issue so her question doesn't get lost.

**Proposed Solution:**
I _think_ the proposed solution is to the remove the references.

7. For more information about this command, see the GCE documentation.
8. See the GCE documentation on firewall rules, for example.

**Page to Update:**
https://kubernetes.io/docs/tasks/access-application-cluster/service-access-application-cluster/

**Comment by codenrhoden** [comment]
I opened https://github.com/kubernetes/website/pull/8765 to try and address this.

**Comment by Logan1x** [comment]
@eliza411 the issue has been solved!! Time to close the issue😅

**Comment by eliza411** [comment]
Closing this issue per the request from @Logan1x and PR #8765.
