### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by FinixLei** [kubernetes/website#8775]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The hyper link "GitHub repository", which links to https://github.com/kubernetes/website/tree/master/docs/tutorials/kubernetes-basics, cannot be found. 

**Proposed Solution:**
Fix the hyper link. 

**Page to Update:**
https://kubernetes.io/...

**Comment by MasayaAoyama** [comment]
Hello, I have already sent a PR :)
Can you check and give lgtm?
https://github.com/kubernetes/website/pull/8738

**Comment by FinixLei** [comment]
Hi,
Excuse me. What does 'lgtm' stand for?  
Since you have already created #8738, what should I do? Should I close #8775? How to do it? 
Thanks. 

Finix

**Comment by FinixLei** [comment]
OK. I will close this issue.
