### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by bingtimren** [kubernetes/website#8790]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The link to the GitHub repository for the Kubernetes Basics was broken.

**Proposed Solution:**
Fix the link

**Page to Update:**
https://kubernetes.io/...

**Comment by MasayaAoyama** [comment]
@bingtimren 
Hello, I have already sent a PR, can you check and give me lgtm?
https://github.com/kubernetes/website/pull/8738

**Comment by bingtimren** [comment]
@MasayaAoyama  Yes this looks good to me. I'm closing this issue. Thanks!
