### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

### ISSUE THREAD

**Issue by NaveenSrikanth** [kubernetes/website#8796]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Github link for code is not opening . Getting error "404 this is not the page you are looking for"

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
Dup of: #8790
Fixed by: #8738

/close
