### ISSUE TITLE
How can i get the image mysql:5.6 and wordpress:4.8-apache

### ISSUE THREAD

**Issue by liufangwai** [kubernetes/website#8812]
https://k8s.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/   How can i get the image  mysql:5.6 and wordpress:4.8-apache  ?

How can i get the image  mysql:5.6 and wordpress:4.8-apache, please show the link

**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
They are both from dockerhub:

- https://hub.docker.com/_/mysql/
- https://hub.docker.com/_/wordpress/

/close
