### ISSUE TITLE
Typo with k8s.io/docs/tutorials/kubernetes-basics/'s Interactive Tutorial

### ISSUE THREAD

**Issue by ClaudiaJKang** [kubernetes/website#8818]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
I think that Interactive Tutorial has some typo. Empty period.  

- Module2 - Step1
Like minikube, kubectl comes installed in the online terminal. Type kubectl in the terminal to see its usage. The common format of a kubectl command is: kubectl action resource`.` This performs the specified action (like create, describe) on the specified resource (like node, container). 

- Module4 - Step1
We have a Service called kubernetes that is created by default when minikube starts the cluster. To create a new service and expose it to external traffic we’ll use the expose command with NodePort as parameter (minikube does not support the LoadBalancer option yet)`.`

**Proposed Solution:**
Fix to typo in [kubernetes-bootcamp-scenarios](https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios).

**Page to Update:**
Module 2 : https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/
Module 4 : https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

**Comment by BenHall** [comment]
Sorry for the delay. I had missed the PR. This has now been merged.

**Comment by ClaudiaJKang** [comment]
Thank you! :D
