### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/create-cluster-kubeadm/

### ISSUE THREAD

**Issue by bboreham** [kubernetes/website#8838]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
These statements are confusing about the ordering of steps:
"first choose the pod network plugin you want"
... "You need to choose a Pod Network Plugin in the next step."

**Proposed Solution:**
Make very clear the chicken/egg relationship:
"Before running kubeadm init you must select one of several available network plugins to use in your deployment. Having selected which network plugin you plan to use, this will determine which if any arguments will need to be passed to kubeadm init in order to make the deployment compatible with that network plugin. kubeadm init will be run with those arguments first. Then immediately after you will need to then run a further command to actually install the network plugin. Details on network plugins and their installation are shown below."

**Page to Update:**
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm

**Comment by neolit123** [comment]
the bellow paragraph available at:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm

> You need to choose a Pod Network Plugin in the next step. Depending on what third-party provider you choose, you might have to set the --pod-network-cidr to something provider-specific. The tabs below will contain a notice about what flags on kubeadm init are required.

seems sufficient in terms of details to me, yet perhaps i have a slightly different perspective.

comments from @kubernetes/sig-cluster-lifecycle-bugs ?
WDYT about the suggestion from @bboreham ?

/sig cluster-lifecycle

**Comment by bboreham** [comment]
My complaint is not just about the level of detail; the statements I quoted are contradictory.
It's either the first step or the next step; can't be both.

**Comment by neolit123** [comment]
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
was overhauled in 1.11.

/close
