### ISSUE TITLE
Umbrella: 1.11 kubeadm tracking issue 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/website#8846]
There are a bunch of documentation changes that are slated for 1.11 cycle and most are not major feature changes, however, we have not enumerated the entire list yet.  This issue is meant to serve as the 1.11 kubeadm docs changes tracking issue.  We intend to break down the entire docs list and those that need to hold till 1.11 release will reference this issue.   

@kubernetes/sig-cluster-lifecycle-misc @neolit123 @luxas

**Comment by neolit123** [comment]
filtered list:

https://github.com/kubernetes/kubeadm/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Fdocumentation

----------

FOR 1.11

ISSUE NAME: document "kubeadm config images *" 
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/880
WEBSITE PR: WIP
ASSIGNED: @chuckha 

ISSUE NAME: document "kubeadm config migrate"
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/873
WEBSITE PR: https://github.com/kubernetes/website/pull/8862
ASSIGNED: @neolit123

ISSUE NAME: Create new documentation based on user stories
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/849
WEBSITE PR: WIP
ASSIGNED: @luxas @neolit123

ISSUE NAME: document "CoreDNS by default in v1.11" 
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/843
WEBSITE PR: see list in above link
ASSIGNED: @neolit123 @rajansandeep 

ISSUE NAME: Generate documentation automatically from our external API types and CLI commands 
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/842
WEBSITE PR: WIP
ASSIGNED: @neolit123
(should be moved to POST 1.11)

ISSUE NAME: document "controlling kubelet Config via a versioned file" at website
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/833
WEBSITE PR: WIP
ASSIGNED: @neolit123 @luxas

ISSUE NAME: document `kubeadm config print-default` at website
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/831
WEBSITE PR: https://github.com/kubernetes/website/pull/8862
ASSIGNED: @neolit123

ISSUE NAME: Document source components for required ports for master and worker nodes
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/770
WEBSITE PR: WIP
ASSIGNED: @dixudx

ISSUE NAME: how to renewal apiserver.crt certificate,the default is one year 
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/649
WEBSITE PR: WIP
ASSIGNED: @liztio

ISSUE NAME: Example configs for using external Certificates
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/638
WEBSITE PR: WIP
ASSIGNED: @liztio @Bradamant3 

ISSUE NAME: node-name different than `hostname` not working
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/584
WEBSITE PR: WIP
ASSIGNED: @liztio 

ISSUE NAME: Concise outline for using cloud providers
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/526
WEBSITE PR: WIP
ASSIGNED: @liztio @Bradamant3 

---------
POST 1.11

ISSUE NAME: "document the process of bumping test-infra on each release"
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/868
WEBSITE PR: WIP
ASSIGNED: @hh @neolit123

ISSUE NAME: Stale iptables rules seen after "kubeadm reset"
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/689
WEBSITE PR: WIP
ASSIGNED: @chuckha, @detiber 

ISSUE NAME: Self-hosted kubeadm clusters should still store the manifests somewhere...
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/651
WEBSITE PR: WIP
ASSIGNED: @timothysc

ISSUE NAME: Document all phases' high-level functions in `app/phases/*/doc.go` 
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/614
WEBSITE PR: WIP
ASSIGNED: ??

ISSUE NAME: how can i specified external-etcd-endpoints in 1.8.0
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/569
WEBSITE PR: WIP
ASSIGNED: @chuckha @liztio 

ISSUE NAME: improve user experience about CNI errors
ISSUE LINK: https://github.com/kubernetes/kubeadm/issues/296
WEBSITE PR: WIP
ASSIGNED: ???

**Comment by neolit123** [comment]
/close
most of these are resolved, if something isn't we are tracking in `k/kubeadm`.
