### ISSUE TITLE
Issue with k8s.io/docs/getting-started-guides/fedora/fedora_manual_config/

### ISSUE THREAD

**Issue by danielchg** [kubernetes/website#8878]
**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
The documentation is out to dated, with Kubernetes 1.10 is mandatory configure the kubelete service with the option --config and define a config file that is not clear how it should be in order to add a new node to the cluster.

**Proposed Solution:**
Add an example in the documentation of the new config file format

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
@danielchg Is this something that you've been able to do successfully yourself? If so, could you share your working config?
