### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/feature-gates/

### ISSUE THREAD

**Issue by ghuntley** [kubernetes/website#8883]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

Templates are not being inflated and directives are being exposed to end users.

![image](https://user-images.githubusercontent.com/127353/40899771-e6db8eba-680b-11e8-9343-fccbf4cd2ac0.png)

![image](https://user-images.githubusercontent.com/127353/40899776-ea7e1132-680b-11e8-8c50-7f5450f3b489.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by tengqm** [comment]
/close

This is fixed.
