### ISSUE TITLE
Issue with k8s.io/docs/tasks/debug-application-cluster/troubleshooting/

### ISSUE THREAD

**Issue by vskumar2017** [kubernetes/website#8897]
1. I am trying to setup Minikube on ubuntu 16.04 VM with VMware.

I have done the following and error appeared:

vskumar@ubuntu:~$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubelet v1.10.0
Downloading kubeadm v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
E0604 01:07:49.623882    2733 start.go:234] Error updating cluster:  
downloading binaries: transferring kubeadm file: &{BaseAsset:{data:[] reader:0xc42000e040 
Length:0 AssetName:/home/vskumar/.minikube/cache/v1.10.0/kubeadm TargetDir:/usr/bin TargetName:kubeadm Permissions:0641}}: 
Error running scp command: sudo scp -t /usr/bin output: : wait: remote command exited without exit status or exit signal
vskumar@ubuntu:~$ minikube version
minikube version: v0.27.0
vskumar@ubuntu:~$ 

Please advise.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
Hello, this doesn't look like a docs issue, please try the [support channels](https://git.k8s.io/community/communication).
/close
