### ISSUE TITLE
Contribute button on footer needs to point to the guide

### ISSUE THREAD

**Issue by parispittman** [kubernetes/website#8904]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The contribute button on the footer points to the main k/k repo instead of a landing page for contributing. 

**Proposed Solution:**
It should point to https://git.k8s.io/community/contributors/guide.

**Page to Update:**
https://kubernetes.io/...
all - the button is located in the footer.html

I'm sending in the fix/PR shortly.

**Comment by ajaeger** [comment]
@parispittman The issue is fixed with your change, could you close it, please?

**Comment by ajaeger** [comment]
/close

Closing the issue, it's fixed
