### ISSUE TITLE
How to create a DNS address for a service?

### ISSUE THREAD

**Issue by Harrisonc1** [kubernetes/website#8924]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
I need to create an address that resolves a service. I currently have a LoadBalancer ip that resolves the address, but I need to change it to a name I can choose.

**Page to Update:**
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by lucperkins** [comment]
@Harrisonc1 Could you provide a bit more information? What do you need to change to a name that you can choose?

**Comment by support81** [comment]
Wat must I do for helping
Tell me I will do my apologies if I did something wrong grtz
