### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kube-apiserver/

### ISSUE THREAD

**Issue by pandusiddhu** [kubernetes/website#8938]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by pandusiddhu** [comment]
While we are applying audit to the kubernetes cluster, we are getting permission denied error to create directory in /var/run/kubernetes. Could someone help me to resolve this issue.

**Comment by tengqm** [comment]
@CaoShuFeng Please advise. Closing this because it does not smell like a documentation issue. Feel free to reopen if there are things to improve from doc side.

/close

**Comment by CaoShuFeng** [comment]
> While we are applying audit to the kubernetes cluster, we are getting permission denied error to create directory in /var/run/kubernetes. 

I can't follow this question very well.
FYI, the audit feature doc:
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/
