### ISSUE TITLE
Issue with k8s.io/docs/reference/issues-security/

### ISSUE THREAD

**Issue by Raghavan1993** [kubernetes/website#8950]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
There is no proper way to verify the identity of a container or a service  with GCP services such as KMS or cloud storage. The only way to link the GCP service account to a container is to have the JSON key in a volume mount  which goes against the point of secrets needing to be dynamically injected into a container.

**Proposed Solution:**
A separate container type for secrets that can help authenticate  a container to external services and create secrets dynamically like an init-container at pod creation time.

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
@Raghavan1993 This repository is only for the Kubernetes website. I would recommend filing an issue in the [Kubernetes repo](https://github.com/kubernetes/kubernetes) instead.
