### ISSUE TITLE
Kubeadm included snippets are published and indexed.

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#8982]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
This problem applies to several kubeadm topics, but I'll illustrate with one example.

The [kubeadm init](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/) topic has some authored content along with an included snippet that is generated. The generated snippet is [here](https://github.com/kubernetes/website/blob/master/content/en/docs/reference/setup-tools/kubeadm/generated/kubeadm_init.md).

The problem is that the snippet is getting published as a standalone topic:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/

Also, the standalone snippet topic is indexed and can be found through search.
Search for this:
kubeadm site:kubernetes.io inurl:kubeadm/generated

This problem was not created by the Hugo migration. The 1.9 docs have the same problem.
https://v1-9.docs.kubernetes.io/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/

**Proposed Solution:**
If possible, find a way for the snippets to not be published.
If that is not possible, remove the snippets from the search index.

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
...
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-version/

**Comment by neolit123** [comment]
@steveperry-53 
as discussed yesterday with @Bradamant3 , we are leaning towards removing all authored content from the reference pages like the one for `kubeadm init` and moving that to existing pages for creating a cluster with kubeadm.

ref: https://github.com/kubernetes/kubeadm/issues/899

**Comment by neolit123** [comment]
> The problem is that the snippet is getting published as a standalone topic:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/generated/kubeadm_init/

still not sure why this is happening.

/remove-lifecycle stale
/assign
