### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-minikube/: minikube start with '–vm-driver=none' option failed with error:Unsupported driver: none on (latest) Mac OS

### ISSUE THREAD

**Issue by shiliy** [kubernetes/website#8984]
**This is a... ** 

- [ ] Feature Request
- [ X ] Bug Report

**Problem:**

minikube start with  '–vm-driver=none' option failed with error:**Unsupported driver: none**  on Mac 

$ minikube start --vm-driver none
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
F0607 18:34:51.870598    2223 cluster.go:212] **Unsupported driver: none**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

$ minikube version
**minikube version: v0.27.0**
$ kubectl version
**Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", **GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Error in configuration: 
* unable to read client-cert /Users/syang/.minikube/client.crt for minikube due to open /Users/syang/.minikube/client.crt: no such file or directory
* unable to read client-key /Users/syang/.minikube/client.key for minikube due to open /Users/syang/.minikube/client.key: no such file or directory
* unable to read certificate-authority /Users/syang/.minikube/ca.crt for minikube due to open /Users/syang/.minikube/ca.crt: no such file or directory

$ uname -a
Darwin Shilis-MBP.home 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

**Comment by BenHall** [comment]
There is a related issue at https://github.com/kubernetes/minikube/issues/2727

The issue mentions that vm=none is only supported on Linux.

**Comment by shiliy** [comment]
Thanks, Ben. Could we add that to the doc/make it clearer?
I will close this one for now.
