### ISSUE TITLE
Revise update-imported-docs tool.

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#9003]
**This is a...** 
- [ ] Feature Request
- [ x] Bug Report

**Problem:**
Start with a fresh Debian VM.
Install prerequisites:

* go1.10.2.linux-amd64.tar.gz
* Git
* make (I think)
* gcc (I think)

**git clone https://github.com/kubernetes/website**
**cd website/update-imported-docs**
**./update-imported-docs-linux reference.yml**

We get this error:
-bash: ./update-imported-docs-linux: cannot execute binary file: Exec format error

**Proposed Solution:**
Do not provide the binaries: update-imported-docs-linux and update-imported-docs-macos.
Instead, the user can run the tool this way, as it was originally designed:
**cd website**
**go run update-imported-docs.go reference.yml**
**go run update-imported-docs.go imported.yml**
**go run update-imported-docs.go release.yml**

**Note**
It was a nice idea to provide binaries, but I think providing binaries will be troublesome in practice.

**Comment by ajaeger** [comment]
Indeed, providing a 32-bit ARM binary is quite a surprise:

$ file ./update-imported-docs-linux
./update-imported-docs-linux: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, with debug_info, not stripped

**Comment by mengqiy** [comment]
@steveperry-53 I believe it is intended to run using `go run update-imported-docs.go foo.yaml` at the beginning.
