### ISSUE TITLE
Issue with k8s.io/docs/tutorials/k8s101/

### ISSUE THREAD

**Issue by xiang6175** [kubernetes/website#9015]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by ajaeger** [comment]
/triage needs-information

@xiang6175 , please either provide more information and explain the issue - or close this issue.

**Comment by shubheksha** [comment]
Since there has been no update on this, I'm closing it.
@xiang6175, feel free to reopen and update or open another issue.
/close
