### ISSUE TITLE
k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/ tutorial not consistent with linked source code

### ISSUE THREAD

**Issue by optnfast** [kubernetes/website#9024]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/ says:

> The source code and the Dockerfile are available in the <a href="https://github.com/kubernetes/website/tree/master/content/en/docs/tutorials">GitHub repository</a> for the Kubernetes Basics.

The `server.js` in github just responds "Hello World!" to any request. However the server in the interactive tutorial is more complex:

```
var handleRequest = function(request, response) {
  response.setHeader('Content-Type', 'text/plain');
  response.writeHead(200);
  response.write("Hello Kubernetes bootcamp! | Running on: ");
  response.write(host);
  response.end(" | v=1\n");
  console.log("Running On:" ,host, "| Total Requests:", ++requests,"| App Uptime:", (new Date() - startTime)/1000 , "seconds", "| Log Time:",new Date());
}
```

Particularly during module 3 step 2 this is very confusing - when the reader tries to match what they see in the terminal with what they have been told they are running, they will find they are not consistent. Only in step 4 does the reason for the discrepancy become apparent.

**Proposed Solution:**

Change the source code or the tutorial so that they match.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

**Comment by ClaudiaJKang** [comment]
I think so. I opened same Issue(#8855) and PR(#8856). 
Yet, PR wasn't reviewed.

**Comment by nfewx** [comment]
Looks like the assign to @BenHall  didn't work, PR is still assigned to @zacharysarah .

**Comment by BenHall** [comment]
Thanks, it's a little confusing as the repo was originally stored elsewhere and merged in. 

Let me see if I can untangle this in time for next weeks SIG-DOCS.
