### ISSUE TITLE
Issue with k8s.io/docs/editdocs/

### ISSUE THREAD

**Issue by roeehershko** [kubernetes/website#9030]
**This is a...** 

- [ ] Feature Request
- [*] Bug Report

**Problem:**
This command:
```
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
```
Most confusing think i ever saw, can you change it to something more simple?

**Proposed Solution:**
```
echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list.d/kubernetes.list
```

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by jimangel** [comment]
I only see "echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list" - do you still see the command you opened this issue you about? It's possible it was closed in another issue.

**Comment by lucperkins** [comment]
Looks like the suggested change has already been made 👍
