### ISSUE TITLE
Link to etcd.yaml file returns 404

### ISSUE THREAD

**Issue by yoshizzle** [kubernetes/website#9076]
**This is a...** 

- [ ] Feature Request
- [ x ] Bug Report

**Problem:**
Link to etcd.yaml file on High Availability Cluster page returns 404 error:

**Proposed Solution:**

Revise link to the correct page.

**Page to Update:**
https://github.com/kubernetes/website/blob/master/content/en/docs/admin/high-availability/building.md

**Comment by Bradamant3** [comment]
See also #9058

**Comment by stewart-yu** [comment]
I think we can close it now
/close
