### ISSUE TITLE
issue with https://k8s.io/docs/tasks/inject-data-application/define-command-argument-container

### ISSUE THREAD

**Issue by erikerlandson** [kubernetes/website#9078]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The relation between the `Container` field `command` and the Docker `ENTRYPOINT` is documented, but is placed in a table where it can be missed if the documentation isn't read top to bottom. I have teammates who have tripped over this, and if you miss it in the doc it is quite confusing.

The challenge is to alter the doc so that this is closer to the top, or more prominent, etc, _but without_ working against the k8s principle of remaining as runtime-neutral as possible.

**Proposed Solution:**

I would propose adding a brief note at or near the top of [this section](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#define-a-command-and-arguments-when-you-create-a-pod). A note that says something like "for the mappings between `command` and Docker entrypoint, see the table below" (with link to the table).

**Page to Update:**
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#define-a-command-and-arguments-when-you-create-a-pod

**Comment by erikerlandson** [comment]
cross-reference:  https://github.com/kubernetes/kubernetes/issues/8235

**Comment by erikerlandson** [comment]
I'd be willing to submit a PR for this, but I am having a bit of trouble locating where this content lives. Any pointers would be helpful!

**Comment by tmckayus** [comment]
@erikerlandson ++ this is a good idea, imho. I was bitten by this myself.

**Comment by heckj** [comment]
@erikerlandson I think the content you want to tweak is at https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/inject-data-application/define-command-argument-container.md

Basically to nav into the content, look for content -> en (language code) -> docs and then the URL should match the references from there pretty closely.
