### ISSUE TITLE
No content for document https://kubernetes.io/docs/setup/independent/high-availability/#set-up-master-load-balancer

### ISSUE THREAD

**Issue by XinhaiWang** [kubernetes/website#9106]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The link at that page` <virtual-ip> with the virtual IP. Please read setting up a master load balancer section of the docs for more information.` directs to a location that has no content.
no content for https://kubernetes.io/docs/setup/independent/high-availability/#set-up-master-load-balancer

**Proposed Solution:**
Add content for https://kubernetes.io/docs/setup/independent/high-availability/#set-up-master-load-balancer

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/#set-up-master-load-balancer

**Comment by jimangel** [comment]
Is this a feature request or do you see a link somewhere for https://kubernetes.io/docs/setup/independent/high-availability/#set-up-master-load-balancer that directs to a location that has no content?

**Comment by XinhaiWang** [comment]
I change it to feature request. Also I think it is unclear for *Setting up an HA etcd cluster* section(because of no clear definition for step), I don’t understand the meaning of  `For Option 2: you can skip to the next step. ` Should I go to *Acquire etcd certs* section, or  should I go to `Generate etcd client certs` section?

**Comment by XinhaiWang** [comment]
/close
duplicate of #9034
