### ISSUE TITLE
Issue with k8s.io/docs/reference/access-authn-authz/admission-controllers/

### ISSUE THREAD

**Issue by craigbox** [kubernetes/website#9115]
**This is a...** 
- [x] Quibble, and/or note to self to do something about this

**Problem:**
I can't, at a glance, tell what is relevant and what is not with regard to admission controllers as of v1.10.

**Proposed Solution:**
We should tidy this page up:

- if we are in the 1.10 docs, '(alpha in 1.8; beta in 1.9)' is irrelevant; tell me what state we're in today
- if things are deprecated they should not be listed in these docs (or if so, under a deprecated heading)
- it should be immediately clear for each controller if it is in Alpha or Beta, such as the way "Storage Object in Use Protection (beta)" is so labelled
- I guess we no longer need to tell people how to configure v1.0 and v1.1 of Kubernetes

**Page to Update:**
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/

**Comment by craigbox** [comment]
/remove-lifecycle stale

Why did this never get assigned to anyone for triage?  @jaredbhatti

**Comment by craigbox** [comment]
@chenopis i'm not sure why this didn't get sent to someone for triage?

**Comment by zacharysarah** [comment]
/cc @Bradamant3 @juandiegopalomino @chenrui333 @zparnold 

Is there a PR in progress? There are folks willing to work on this. Thanks in advance for contributions and reviews! 🙇

**Comment by zparnold** [comment]
Happy to take the lead on this @zacharysarah if no one else has (I'm in the opposite set of timezones as you at present so I'll wait 24 hours for a message/lack thereof to proceed)

**Comment by zacharysarah** [comment]
Thanks @zparnold! You rock! :star2:

**Comment by zacharysarah** [comment]
Closed by #12689
