### ISSUE TITLE
User Login Audit Policy File Example

### ISSUE THREAD

**Issue by chris-short** [kubernetes/website#9168]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**

During EU Office Hours on 20180620, @montyz asked, "I need to record and alert when someone logs in to k8s, and the audit logs are a real firehose of information. Anyone have an example of just showing logins?"

The Office Hours team including among others @jeefy @castrojo @mrbobbytables and myself provided a few resources:

- https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L735
- https://stackoverflow.com/questions/50949390/up-to-date-example-of-kubernetes-audit-log-policy
- https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy

But none of them mentioned how to, " when I look at the logs, I cannot figure out what specific api requests to be monitoring for [user logins]"

The suggestions of reading API docs or capturing logs and logging in themselves were well received but the team feels this is something that should be explicitly documented.

**Proposed Solution:**

Documentation to provide audit policy examples for user activity

**Page to Update:**
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

**Comment by montyz** [comment]
More specifically, for HIPAA compliance I need to keep records of who logs into our k8s cluster and deploys things or `exec`'s commands, etc. I understand this is possible via audit logging but I'm having a hard time understanding the audit logs themselves and narrowing in on the specific "User A ran command B".
