### ISSUE TITLE
Issue with k8s.io/docs/admin/multiple-zones/

### ISSUE THREAD

**Issue by mgarod** [kubernetes/website#9187]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
This article is no longer available. I am receiving a 404. This article was available last week.

**Proposed Solution:**
n/a

**Page to Update:**
https://kubernetes.io/docs/admin/multiple-zones/

**Comment by GuessWhoSamFoo** [comment]
@mgarod /docs/admin stuff got moved; see https://github.com/kubernetes/website/pull/9140

New link is https://kubernetes.io/docs/setup/multiple-zones/
