### ISSUE TITLE
Issue with k8s.io/docs/concepts/storage/persistent-volumes/

### ISSUE THREAD

**Issue by cpellot** [kubernetes/website#9190]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
@cpellot Could you please provide more information? Which issue are you seeing?

**Comment by lucperkins** [comment]
This issue appears to have been created unintentionally
