### ISSUE TITLE
Official Mesosphere Guide link is not working ----Issue with k8s.io/docs/setup/on-premises-vm/dcos/

### ISSUE THREAD

**Issue by ravinani02** [kubernetes/website#9205]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
@ravinani02 The link is working, it's just an internal link to the "Official Mesosphere Guide" section of the page rather than to anything on the Mesosphere page. This can be a little confusing on pages without much content that nonetheless have an auto-generated table of contents.
