### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/

### ISSUE THREAD

**Issue by youyongsong** [kubernetes/website#9220]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
After I run command `kubeadm alpha phase etcd local --config /etc/kubeadm/etcdcfg.yaml`, the following error occurred:
```
unable to decode config from "/etc/kubeadm/etcdcfg.yaml" [no kind "MasterConfiguration" is registered for version "kubeadm.k8s.io/v1alpha2"]
```

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/

kubeadm version: v1.10.5

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by neolit123** [comment]
`MasterConfiguration` is a valid type for `"kubeadm.k8s.io/v1alpha2"`.

i just tried this with k8s/kubernetes version 1.11.0 and i cannot reproduce the issue.
please, try to reset (e.g. `sudo kubeadm reset`) your cluster the tutorial again.
also updating to 1.11.1 is a good idea.

if it's still not working for you, file an issue against the `kubernetes/kubeadm` repo as this is not a docs issue.

/close
