### ISSUE TITLE
Issue with k8s.io/docs/user-journeys/users/cluster-operator/ (no overview provided)

### ISSUE THREAD

**Issue by lucperkins** [kubernetes/website#9229]
I'm getting an error on this page: https://kubernetes.io/docs/user-journeys/users/cluster-operator.

An overview block needs to be provided.

**Comment by steveperry-53** [comment]
@lucperkins I'm not sure I understand the problem. That is, I don't understand why we need content at https://kubernetes.io/docs/user-journeys/users/cluster-operator. I agree that we don't want a big Error message. But I think we could go without content and just have the same kind of behavior we see on at these URLs:

* https://kubernetes.io/docs/user-journeys/
* https://kubernetes.io/docs/user-journeys/users/
