### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/controllers/cron-jobs/

### ISSUE THREAD

**Issue by jaygorrell** [kubernetes/website#9231]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Problem:**
While it's clear `startingDeadlineSeconds` is a "seconds" variable, the example given on this page borderline implies it is in minutes:
>For example, suppose a cron job is set to start at exactly 08:30:00 and its startingDeadlineSeconds is set to 10, if the CronJob controller happens to be down from 08:29:00 to 08:42:00, the job will not start.

The text is not inaccurate at all, but it seems odd to use an example that is _just_ over 10 minutes to provide an example of a `startingDeadlineSeconds` of 10 seconds.

**Proposed Solution:**
Switch the example to be clearly in seconds.

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
The example is not using 10 minutes as duration.
