### ISSUE TITLE
Block Code PRs on the presence of a Docs PR

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/website#924]
The merge bot should not merge PRs in kubernetes/kubernetes unless there is an accompanying Docs PR, or the PR has been marked as docs-not-required.

**Comment by thockin** [comment]
+1 - we seem to not be able to do it without enforcement.  Brian proposed to let all the OWNERS work finish before we muck with more gates :)  Also we should make sure it is possible to write good docs :)

**Comment by tengqm** [comment]
Please reopen this if there is any effort in this space.
