### ISSUE TITLE
Issue with /docs/tasks/tools/install-minikube/

### ISSUE THREAD

**Issue by preeteshmishra** [kubernetes/website#9260]
**This is a Bug Report** 

**Problem:** while installing Minikube to run kubernetes cluster on Oracle virtual box locally  , getting error : This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory. It seems neither VMware work-station , nor the Oracle Virtual box is supporting nested Virtualisation. So, **minikube --vm-driver=virtualbox start** command fails to execute.

**Proposed Solution:**NA

**Page to Update: 

https://kubernetes.io/docs/tasks/tools/install-minikube/
https://github.com/kubernetes/minikube/blob/v0.28.0/README.md

 v1.10.0

Things i have done so far:

Install Oracle virtual box on my Windows machine.
Enable Hyper-v in my windows machine.
spawn a linux (ubuntu -16.04) on virtual box.
Installed virtualbox driver on the linux vm.
Installed kubectl on the linux vm.

![cluster-info](https://user-images.githubusercontent.com/20884225/41956999-1dbb98cc-7a03-11e8-9d54-422a7fd4e45a.png)
![minikube-start](https://user-images.githubusercontent.com/20884225/41957052-4a6211bc-7a03-11e8-8cd4-e574ab3aaa2f.png)

**Comment by mrbobbytables** [comment]
Hyper-V prevents running other hypervisors on Windows Hosts unfortunately. 

You may want to either try [disabling Hyper-V](https://superuser.com/a/540131) and using Virtualbox or see the [Minikube Hyper-V specific docs](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperv-driver) to get that going.
