### ISSUE TITLE
Issue with k8s.io/docs/setup/turnkey/aws/

### ISSUE THREAD

**Issue by hrishikeshgjoshi** [kubernetes/website#9266]
**This is a documentation issue for Kubernetes documentation 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
https://kubernetes.io/docs/setup/turnkey/aws/
Support Level Section for Docs link is not working

![image](https://user-images.githubusercontent.com/36895248/41984588-a458ea60-7a4e-11e8-9c70-e91b5175b2d5.png)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by stewart-yu** [comment]
fix xref #9256
