### ISSUE TITLE
Issue with k8s.io/docs/concepts/workloads/pods/init-containers/

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/website#9272]
**This is a...** 

- [x] Feature Request
- [ ] Bug Report

**Proposed Solution:**
Could you please use the "new syntax" first and then (if still needed) add the older syntax? That would be great. Thanks.

**Page to Update:**
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

1.10

**Comment by DanyC97** [comment]
@rdxmb please help me understand what you mean by _use the "new syntax" first_ ? is there any example in the docs you mentioned ?

**Comment by rdxmb** [comment]
@DanyC97 

The docs in https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#init-containers-in-use start with the example on version 1.5 - and then below adding 'There is a new syntax in Kubernetes 1.6'

I suggest just to switch the two parts.

**Comment by DanyC97** [comment]
perfect thank you @rdxmb !
since we are on 1.14 my view would be to drop the old syntax and only use the new one.

@zacharysarah @cody-clark thoughts ?
