### ISSUE TITLE
Stabilization: Set weights for sections in left nav.

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#9277]
**This is a...** 

- [ x] Feature Request

**Problem:**
Sections in the left nav are displayed in alphabetical order unless weights are set for individual topics and folders.

**Proposed Solution:**
For all sections in the left nav, check to see whether weights are set correctly. If not, set weights.

**Page to Update:**
https://kubernetes.io/...

**Comment by tengqm** [comment]
Looks like we are not suffering from this now. Feel free to reopen if needed.
