### ISSUE TITLE
Stabilization: Improve glossary definitions.

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#9281]
**This is a...** 
- [x] Feature Request

**Problem:**
The glossary definitions were written by several different people, each working on one or two definitions. There was minimal communication between those who wrote the various definitions. As a result, the definitions don't hang together as a set. Also, some of the definitions are misleading.

Some topics use a shortcodes to embed glossary definitions. The results are not always ideal. For example, the [Names](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) topic embeds some definitions. And we end up with content like this:

## Names

A client-provided string that refers to an object in a resource URL, such as /api/v1/pods/some-name.

Only one object of a given kind can have a given name at a time. However, if you delete the object, you can make a new object with the same name.

///////////////////

What we really need under the Names heading is a sentence that begins, "A name is ...".

**Proposed Solution:**
Form a working group of two or three people. Revisit all the glossary definitions. Ensure that each definitions is accurate, and ensure that the set of definitions hangs together as a whole. Find all places where topics embed glossary definitions, and make sure the definitions and the surrounding text make sense.

**Page to Update:**

Glossary definitions are here:
https://github.com/kubernetes/website/blob/master/content/en/docs/reference/glossary/

**Comment by jimangel** [comment]
I would be happy to help with this @steveperry-53!
