### ISSUE TITLE
Stabilization: Clean up landing pages for Tasks, Tutorials, and Concepts.

### ISSUE THREAD

**Issue by steveperry-53** [kubernetes/website#9288]
**This is a...** 

- [x] Feature Request

**Problem:**
The [Tasks landing page](https://kubernetes.io/docs/tasks/) tends to get out of sync with the left nav and the actual task content.

The same is true for the [Tutorials landing page](https://kubernetes.io/docs/tutorials/) and the [Concepts landing page](https://kubernetes.io/docs/concepts/).

Additional note: The Tasks landing page isn't very helpful. It has a list of in-page links at the top. But each link goes to a heading followed by a brief statement. But I don't think there's much useful information in those brief statements. And I don't think the answer is to make the brief statements longer. I think that longer statements will still get out of sync with the actual content.

**Proposed Solution:**
Change the content on the landing pages to something that is not prone to falling out of sync with the actual content. Or find a way to automatically generate the landing pages based on the actual content.

**Page to Update:**
https://kubernetes.io/...

**Comment by chenopis** [comment]
Note: Don't duplicate ToC on landing page. Instead give overview of the purpose of the section. For example, what is the difference between concept, task, and tutorial.
