### ISSUE TITLE
Issue with k8s.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

### ISSUE THREAD

**Issue by klarose** [kubernetes/website#9297]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
The link to view the ```Network Plugin interface``` in section ```Network Plugin Requirements``` is broken. It looks like the  code was moved as part of some refactoring?

**Proposed Solution:**
Fix the link

**Page to Update:**
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

Kubernetes Version: 1.11

**Comment by shubheksha** [comment]
This was fixed in #9298
/close
