### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/

### ISSUE THREAD

**Issue by evanrich** [kubernetes/website#9312]
**This is a...** 
- [ ] Feature Request
- [X] Bug Report

**Problem:**
After successfully upgrading from 1.10.0 to 1.11.0, all pods have an IP assigned from the docker0 subnet (172.17.0.0/16) instead of the weavenet subnet (10.44.0.0/12)

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by neolit123** [comment]
this is more of an issue for the `kubernetes/kubeadm` repository and not the `kubernetes/website`.
please, re-open again there if you feel like it.

also, have you tried updating from 1.11.0 to 1.11.1 and did that work?

/close
