### ISSUE TITLE
Issue with k8s.io/docs/reference/

### ISSUE THREAD

**Issue by wanglei19881118** [kubernetes/website#9319]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by jimangel** [comment]
Hey @wanglei19881118 can you provide additional information about what your issue is?

**Comment by mgred** [comment]
Not sure, but the issue might be the "double-bullet" in the Table of Content, which will be fixed by #9175.
