### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by ramaswin121994** [kubernetes/website#9322]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
few options I think not updated

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by ajaeger** [comment]
/assign

there's no description in your report, just the default template. I assume it was opened by accident, let me close it..
