### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by kushortiz** [kubernetes/website#9374]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by jimangel** [comment]
@kushortiz does this PR fix your issue? https://github.com/kubernetes/website/pull/9344 - please provide more information if not. Thanks!

**Comment by Bradamant3** [comment]
Closing in favor of issue #9413 to avoid confusion.
