### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by davecb** [kubernetes/website#9393]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The illustration here uses a normal user prompt, "$".
I found on fedora 27 that if I was root when installing minikube initially, everything thereafter has to be run as root. The proxy in particular complained about certificates if run as an ordinary user.

That mildly suggests that "#" should be the prompt.  To confirm, I completed the exercise and then retried not as root, and got 
```
$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E0705 14:52:58.654667   19291 start.go:168] Error starting host: Error getting state for host: machine does not exist.

 Retrying.
E0705 14:52:58.655384   19291 start.go:174] Error starting host:  Error getting state for host: machine does not exist
```

**Proposed Solution:**
You may want to change the prompt to "#" in the simulation.

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Thanks for the comment. 

This has been discussed and the different options ($, >, #) and found that $ is the most cross-platform friendly approach when taking into account Linux, OSX, and Windows.
