### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by TaoLi2100** [kubernetes/website#9398]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report
Kubenetes1.1 create HA Kubernets Cluster,execute " kubeadm init --config kubeadm-config.yaml
" find a bug.I'ts cannot init successful. 
**Problem:**
 Setting node annotation to enable volume controller attach/detach

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
This appears to be a support issue rather than a documentation issue. I'm going to close this for now, but @TaoLi2100 please feel free to re-open if you feel that the documentation is somehow incorrect or out of date.
