### ISSUE TITLE
Problem with katacoda bash terminal

### ISSUE THREAD

**Issue by mohammedtaki** [kubernetes/website#9399]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

while starting scenanio on https://www.katacoda.com/courses/serverless/getting-started-with-kubeless

getting issue on the console : we encounter a problem with connection

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
@mohammedtaki Katacoda is a third party that is not affiliated with this repository. We suggest reporting issues with the Katacoda interface to them.

**Comment by lucperkins** [comment]
@mohammedtaki Actually, it turns out that the Katacoda interface is technically under the same umbrella with the k8s docs. I'll re-open this and investigate.
