### ISSUE TITLE
Issue with k8s.io/docs/tasks/configure-pod-container/pull-image-private-registry/

### ISSUE THREAD

**Issue by gkaleta** [kubernetes/website#9401]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 -d

**Proposed Solution:**
Should be with capital D
kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 -D

**Page to Update:**
https://kubernetes.io/...

**Comment by jimangel** [comment]
@gkaleta what OS version are you using? It seems like -d works on ubuntu and -D is not allowed.

```
:~# cat encrypted-file | base64 -D
base64: invalid option -- 'D'
Try 'base64 --help' for more information.
:~# cat encrypted-file | base64 -d
<works>
```
We can look at adding a flag to warn <your OS version> users.

**Comment by gkaleta** [comment]
Sorry for the late reply - i am running MacOS. I need to use capital D

**Comment by bradtopol** [comment]
This was fixed by https://github.com/kubernetes/website/pull/9153/files
