### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by ggund** [kubernetes/website#9405]
HA Clustering documentation not self-explanatory as compared with previous documentation
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report
- [x] Document Update Report

**Problem:**
The section 'Configure SSH' is not self explanatory. Can you please elaborate more? The previous documentation had a much better explanation of configuring the ssh 
Not sure if the document wants to say that SSH among the machines are already configured? 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

**Comment by chuckha** [comment]
maybe ssh-agent isn't the best way to go. The other ways require so many hoops to jump through. I'll have to think about how to improve this. Would love ideas.

**Comment by neolit123** [comment]
a potential improvement here would be to write a short paragraph on why is ssh-agent used (e.g. the alternatives are more demanding), plus explain any missing ssh related steps.

i think the user is having an issue with the:
> SSH access from one device to all nodes in the system

pre-requisite. possibly link to an external tutorial about setting up ssh.

**Comment by neolit123** [comment]
/close

the recent refactor moved the ssh-agent steps at the bottom of the document (1.14) due to the fact that we now support auto-copy. we also added notes that users should use their preferred way to copy certs i.e. ssh-agent is not mandatory. someone might want to use `scp -3`
