### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by liggitt** [kubernetes/website#9413]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Almost all options are missing from the kubelet command line help page

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by neolit123** [comment]
ouch...

**Comment by tengqm** [comment]
Checking...

**Comment by tengqm** [comment]
Looks like it is not a problem pertain to website. When I run ./hack/generate-docs.sh in kubernetes/kubernetes, the generated docs/admin/kubelet.md has a very short content. I think this is caused by the tweakings of kubelet flags (i.e. deprecated or not, hidden or not) and the spf13/pflag library. Still digging...

**Comment by tengqm** [comment]
The reason we don't have an "incomplete" set of flags for kubelet is that `kubelet` is handling command line flags in a different way. It is believed that "corba" is poluting the `kubelet` flag sets (https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L266, https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L142). However, the doc generator still uses "Corba" for flags parsing. So ... it is 'kubelet' breaking the doc generator, not the docs generator breaking 'kubelet'.

**Comment by neolit123** [comment]
^ @mtaufen 
this seems to go back to:
https://github.com/kubernetes/kubernetes/commit/42589266407e32fdf716d1fef689f0aee7142cd9

@tengqm can the docs tool be made to handle this special case?

**Comment by jimangel** [comment]
@tengqm I see now that this page should be updated by the gen-docs script. However I created a PR a while back to just fix it for anyone looking: https://github.com/kubernetes/website/pull/9344

I haven't looked at the  ./hack/generate-docs.sh tool to see if that would overwrite it or break anything - but it might be a good stop-gap until the script is patched.

If you disagree, let me know and I'll close the PR. Thanks!

**Comment by tengqm** [comment]
@jimangel IMHO, getting the docs right is of a higher priority than getting the tools right. I have no objections getting #9344 merged. Let's wait a little while and see if @mtaufen can respond with a quick fix before deciding whether #9344 should go in.

**Comment by mtaufen** [comment]
This should fix: https://github.com/kubernetes/kubernetes/pull/66034
