### ISSUE TITLE
RFE: please consider using markdown linter

### ISSUE THREAD

**Issue by alexxa** [kubernetes/website#9430]
**This is a...** 

- [x ] Feature Request
- [ ] Bug Report

Please consider using Markdown linter (e.g. [1, 2] or any other) to unify k8s.io docs Markdown syntax/style and increase its quality.  See #9479, an example of what issues Markdown linter [1] can catch.

[1] https://github.com/markdownlint/markdownlint
[2] https://github.com/remarkjs/remark-lint

**Comment by neolit123** [comment]
i wonder if the markdown linter will trigger for all the current hacks that are present to work around BlackFriday (the markdown processor that ) bugs.

/cc @mistyhacks

**Comment by mistyhacks** [comment]
The suggested enhancements for the page should go in a different issue than a RFE to add a Markdown linter. They are orthogonal. The problem with a Markdown linter is that Markdown is super lazy about syntax. What exactly would you lint?

**Comment by alexxa** [comment]
@mistyhacks Hi, I opened the RFE to use that (or any other) linter and gave an example of what that linter can find. Multiple headers with the same content of the given page were reported by that linter.

If you consider that you don't need Markdown linter, but the page update suggestions are valid. I can edit this issue.

**Comment by mistyhacks** [comment]
A linter is a great RFE but the problems you found are actionable now, so I'd prefer to get that fix in sooner than the linter idea could be acted on. Thanks!

**Comment by alexxa** [comment]
@mistyhacks I have updated this issue description according to your suggestion. Thanks.
