### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by shruthibhaskar** [kubernetes/website#9453]
**This is a...** 

- [x ] Feature Request
- [x] Bug Report

**Problem:**
I am trying to set up kops cluster, as a pre requisite i installed kubectl as per given instruction in the official page.

but i am getting the below error,
ubuntu@ip-172-31-30-74:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

but i had set up cluster before using similar instructions without facing the above issue, now i am not able to figure out why my kubectl resulting in this "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

kindly help on this..

**Proposed Solution:**
NA

**Page to Update:**
https://kubernetes.io/...

**Comment by lucperkins** [comment]
@shruthibhaskar What do you get if you run `kubectl cluster-info`?

**Comment by shubheksha** [comment]
@shruthibhaskar ping - are you still running into this issue?
