### ISSUE TITLE
PodPriority pre-emption not working on version 1.11

### ISSUE THREAD

**Issue by pradeep-k** [kubernetes/website#9499]
**This is a...** 

- [ ] Feature Request
- [x ] Bug Report

**Problem:**
PodPriority pre-emption not working on version 1.11

Kubernetes Version: 1.11

Additional Information:
As per the documentation, pod priority and pre-emption is already enabled in version 1.11. I installed this version of the kubernetes using this [link](https://blog.tekspace.io/setup-kubernetes-cluster-with-ubuntu-16-04/) in a 4 node virtual machines.  I followed the examples given in this [link](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/), and created two priority class of value 100 (named as low-priority) and 10000 (named as high-priority). I then created many pods of low-priority (using deployment which created many replicas) with resource requests which filled my 4 node cluster completely. I also created a poddistruptionbudget and specified details that 2 replica is sufficient as pdb. Then, I created a high priority pod. However, the high-priority pod goes to pending state. 

To debug the issue, I created a custom scheduler and the high priority pod was assigned this scheduler.
Upon using dlv to debug this scheduler, I figured out that the pod spec in all the previous and the last pod have priorityClassName member variable assigned correctly, but Priority member variable are absent. 

Let me know, if you need any further information. My setup is still alive.

**Comment by ravisantoshgudimetla** [comment]
Thanks @pradeep-k. It could be an issue with priority resolution at admission plugin level. Do you have priority admission controller enabled at the api-server level?

If you use `--enable-admission-plugins` at api server level after https://github.com/kubernetes/kubernetes/pull/65739 has been applied, you should see priority resolution happening. We missed that during 1.11. This will go in 1.11.1. If you are using `--admission-control`, you can add `Priority` admission plugin.

**Comment by pradeep-k** [comment]
Thanks for your response @ravisantoshgudimetla . I will try to pull the latest main branch or pull the changes locally, and repeat the experiment. However, I am not yet aware how can I deploy a locally built kube api-server in my cluster.  I am looking into static pod concept. In case, you have some guidance on how can I deploy the locally built kube api-server, please advise.

**Comment by pradeep-k** [comment]
It worked with the latest codebase of main branch. Thank you for your prompt response.  You can close the issue.

Just a small note, in case this leads to somewhere. After I run kubectl create -f highpriority-pod.yaml, I immediately see following error, which later disappeared and high priority container was up, and one of replica of lower priority container went to pending state. which is expected result. 
 
```
pradeep@mdbsrv10:~/src/yaml-files$ kubectl get pods --all-namespaces -o wide
panic: runtime error: index out of range

goroutine 1 [running]:
k8s.io/kubernetes/pkg/printers.PrintTable(0xc42053da00, 0x1897800, 0xc42097a100, 0x0, 0x0, 0x0, 0x0, 0x1000100, 0x0, 0x0, ...)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/printers/humanreadabl$.go:366 +0x5d6
k8s.io/kubernetes/pkg/printers.(*HumanReadablePrinter).PrintObj(0xc420a306c0, 0x18a1200, 0xc42053da00, 0x1897800, 0xc42097a100, 0x0, 0x0)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/printers/humanreadabl$.go:286 +0x7ca
k8s.io/kubernetes/pkg/printers.(ResourcePrinter).PrintObj-fm(0x18a1200, 0xc42053da00, 0x1897800, 0xc42097a100, 0x1896900, 0xc420892ff0)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/vi$w.go:113 +0x57
k8s.io/kubernetes/pkg/printers.ResourcePrinterFunc.PrintObj(0xc420500c20, 0x18a1200, 0xc42053da00, 0x1897800, 0xc42097a100, 0x0, 0x0)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/printers/interface.go$38 +0x4e
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run(0xc4208f60e0, 0x18cac20, 0xc42056fa40, 0xc4208ef180, 0xc4207729c0, 0x1, 0x4, 0x0, 0x0)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.g$:440 +0xae9
k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1(0xc4208ef180, 0xc4207729c0, 0x1, 0x4)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.g$:159 +0x115
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4208ef180, 0xc420772800, 0x4, 0x4, 0xc4208ef180, 0xc420772800)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/c$bra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420343900, 0xc420504630, 0x12a05f200, 0xc4208bfee8)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/c$bra/command.go:846 +0x30a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420343900, 0x17edc40, 0x2402060)
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/c$bra/command.go:794 +0x2b
main.main()
        /workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196

```

**Comment by ravisantoshgudimetla** [comment]
No problem @pradeep-k. Glad that it worked. I am closing this issue now.

Can you create another issue with reproduction steps for `kubectl get pods` problem that you faced?
