### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by guptaAkshay06** [kubernetes/website#9515]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Page doesn't load properly 

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
Could you elaborate on what's the issue, @guptaAkshay06? 
/triage needs-information

**Comment by shubheksha** [comment]
Since there has been no update on this, I'm closing it.
@guptaAkshay06, feel free to reopen and update or open another issue.
/close
