### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

### ISSUE THREAD

**Issue by cormite** [kubernetes/website#9517]
This is a bug report found in the Kubernetes Tutorial

- [ X] Bug Report

**Problem:**
In module 1, step 3 of 3, in the terminal I typed: "kubectl cluster-info dump | less" and the terminal became unresponsive.

**Proposed Solution:**
I figured out the command by tab tab autocompletion. If the command is available I belive it should work, otherwise the option should be removed. Also, I believe an error should be shown instead of making the terminal unavailable.

**Page to Update:**
https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

**Comment by sergeyklay** [comment]
As I can see at my localhost it is not works as probable expected:
```
$ kubectl cluster-info dump
error: missing apiVersion or kind and cannot assign it; no kind is registered for the type core.NodeList
```

So:
```
kubectl cluster-info dump | less
error: missing apiVersion or kind and cannot assign it; no kind is registered for the type core.NodeList
(END) <---- Here my terminal wait 
```

**Comment by henryza** [comment]
Same problem.

INFO
[root@k8s-master ~]# kubectl cluster-info
Kubernetes master is running at https://192.168.114.4:6443
KubeDNS is running at https://192.168.114.4:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[root@k8s-master ~]# kubectl cluster-info dump
error: missing apiVersion or kind and cannot assign it; no kind is registered for the type core.NodeList
[root@k8s-master ~]# kubectl version --short
Client Version: v1.11.1
Server Version: v1.11.2

CENTOS
CentOS Linux release 7.5.1804 (Core)
Derived from Red Hat Enterprise Linux 7.5 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by BenHall** [comment]
Thanks, it looks like `less` causes some problems with Katacoda. We'll investigate.

**Comment by BenHall** [comment]
Could you please retest this and see if it's still causing you an issue?

Thank you for your help.
