### ISSUE TITLE
Update: Configure a Pod to Use a PersistentVolume for Storage

### ISSUE THREAD

**Issue by todd-dsm** [kubernetes/website#9523]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
Opting for the minikube path, the contents of index.html are not displayed: 
> 'Hello from Kubernetes storage'

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Proposed Solution:**
This looks like a probable culprit:
```bash
minikube ssh

tail -f /var/log/containers/storage-provisioner_kube-system_storage-provisioner...
{"log":"E0715 21:40:40.981788       1 controller.go:584] Error getting claim \"default/task-pv-claim\"'s StorageClass's fields: StorageClass \"manual\" not found\n","stream":"stderr","time":"2018-07-15T21:40:40.98196793Z"}
```

**System Info:**
```bash
kubectl version --short=true
Client Version: v1.10.5
Server Version: v1.10.0
```

OS:
```bash
system_profiler SPSoftwareDataType
...
      System Version: macOS 10.12.6 (16G1408)
      Kernel Version: Darwin 16.7.0
      Boot Volume: macos
```

The backing details:
- Installed minikube, virtualbox, vb extensions with homebrew
- Laptop is configured to favor GNU packages over corresponding UNIX ones ()

**Additional Info:**
Directory permissions:
```bash
$ sudo mkdir -p /mnt/data

$ sudo chown -R "$USER:staff" /mnt/

$ ls -ld /mnt/
drwxr-xr-x 3 "$USER" staff 102 Jul 14 17:49 /mnt/

$ tree -ugp /mnt/
/mnt/
└── [drwxr-xr-x "$USER"   staff   ]  data
    └── [-rw-r--r-- "$USER"   staff   ]  index.html
```

Pod logs:
```bash
kubectl logs task-pv-pod 
2018/07/15 21:18:36 [error] 5#5: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
127.0.0.1 - - [15/Jul/2018:21:18:36 +0000] "GET / HTTP/1.1" 403 169 "-" "curl/7.52.1" "-"
```

Inside the container:
```bash
kubectl exec -it task-pv-pod -- /bin/bash

root@task-pv-pod:/# apt-get update && apt-get install -y curl

curl localhost
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.15.1</center>
</body>
</html>
```

**Comment by LiamHe** [comment]
I run into same problem when following the tutorial https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/ on kubeadm-dind cluster.

**Comment by razi-rais** [comment]
Facing the same issue. Basically, if you go into the pod and run `cat /usr/share/nginx/html` you will notice that file does not exist. So mount never really worked (clear by the logs)

**Comment by 360cloud** [comment]
confirm -- issue still exists

**Comment by Hartmarken348** [comment]
Pod exite vol

**Comment by DanyC97** [comment]
@todd-dsm @360cloud could you please confirm if this is still happening on latest minikube version?

/sig minikube
/language en

**Comment by nando740** [comment]
Exactly same issue here.

Running minikube version 1.1.1. Kubectl Client Version: v1.14.3; Server Version: v1.14.3.

```
$ kubectl logs task-pv-pod                                                                                                                                                      
127.0.0.1 - - [12/Jun/2019:22:49:56 +0000] "GET / HTTP/1.1" 403 153 "-" "curl/7.52.1" "-"
2019/06/12 22:49:56 [error] 10#10: *7 directory index of "/usr/share/nginx/html/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"

$ minikube logs
(...)
==> storage-provisioner <==
E0612 22:26:34.616563       1 controller.go:584] Error getting claim "default/task-pv-claim"'s StorageClass's fields: StorageClass "manual" not found
```

**Comment by sftim** [comment]
/priority backlog
Is that OK?

**Comment by tstromberg** [comment]
It needs to be tested, but I think the issue may be solvable by removing this line from the YAML:

`storageClassName: manual`

**Comment by BerdinEge** [comment]
I am getting the same issue on Katacoda Kubernetes Playground environment. It looks like @tstromberg 's solution not works.
In first, Katacoda's environment has not had a StorageClass. I added this storageclass(from documentation) and make it default:
`apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer`
Even creating pv and pvc from yaml files with or without this line its not working:
`storageClassName: <storageclassname>`
