### ISSUE TITLE
ETCD configuration is ignored Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by jowenn** [kubernetes/website#9525]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
HA Bootstrapping with stacked control plane does not work, etcd options are ignored.

**Proposed Solution:**
The document says that the configuration has to look like:
**etcd:
  local:
    extraArgs:**
      listen-client-urls: 
.....
I had to remove one level and change the configuration to:
**etcd:
    extraArgs:**
      listen-client-urls:
.....

It looks like the 1.11 configuration is not in sync with kubeadm 1.11

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

Kubernetes Version:
kubeadm version:
kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:14:41Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

rpm -qa:
kubelet-1.11.0-0.x86_64
kubectl-1.11.0-0.x86_64
kubernetes-cni-0.6.0-0.x86_64
kubeadm-1.11.0-0.x86_64

**Comment by chuckha** [comment]
/close

this may have been broken for 1.11 but we've vetted for 1.12 and the versions are no longer mismatched
