### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-intro/

### ISSUE THREAD

**Issue by shoffmeister** [kubernetes/website#9529]
Using `Node.js` in the introduction to the `Node abstraction` makes the documentation unnecessarily complex. Specifically, https://kubernetes.io/docs/tutorials/kubernetes-basics/explore/explore-intro/ says

"For example, a Pod might include both the container with your Node.js app as well as a different container that feeds the data to be published by the Node.js webserver. The containers in a Pod share an IP Address and port space, are always co-located and co-scheduled, and run in a shared context on the same Node."

Would it make more sense to tweak this to read:

"For example, a Pod might include both the container of your web server as well as a different container that supplies the data to be published through a web application running on the web server. The containers in a Pod share an IP Address and port space, are always co-located and co-scheduled, and run in a shared context on the same Node."

**Comment by lucperkins** [comment]
@shoffmeister Feel free to submit a pull request with this suggested change and we'll take a look!
