### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/website#9534]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

In `Options` section, "--feature-gates mapStringBool" option was given as a "feature=true|false" format. While in other cli-ref pages, like [kube-apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/), it's like "feature=true|false (BETA - default=true)".

So I'm curious this is as expected and special for kubelet, or a bug here?

**Proposed Solution:**

Make it consistent to be "feature=true|false (phase - default=true or false)" like kube-apiserver, scheduler, etc.

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
i would say that the missing state and default value for feature gates for the [kubelet](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) are an issue, in comparison to other CLIs ref. pages.

@kubernetes/sig-node-bugs 
/kind bug

**Comment by csskuber** [comment]
related PR: #9583
