### ISSUE TITLE
Issue with k8s.io/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by fjudith** [kubernetes/website#9538]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**

`--rkt-api-endpoint` and `--rkt-path` arguments are documented but are missing in Kubelet v1.11.0. 

The embeded documentation shows that `rkt` is a deprecated argument value for `--container-runtime`.

 ```bash
./kubelet --help | grep rkt
      --container-runtime string     The container runtime to use. Possible values: 'docker', 'remote', 'rkt (deprecated)'. (default "docker")
```

**Proposed Solution:**

### Option 1
1. Remove references to `--rkt-api-endpoint` and `--rkt-path` arguments in the doc.

### Option 2
2. Restore `--rkt-api-endpoint` and `--rkt-path` Kubelet arguments and mark them as `DEPRECATED` like it has been done for all `--docker*` arguments

### Option 3
3. Provide references to `rktlet` configuration.

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
@kubernetes/sig-node-bugs
