### ISSUE TITLE
Installing Kubeadm documentation is 404

### ISSUE THREAD

**Issue by phyber** [kubernetes/website#9581]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:** The "Installing Kubeadm" page linked from https://kubernetes.io/docs/setup/ is currently 404. The setup page links to https://kubernetes.io/docs/setup/independent/install-kubeadm/ which redirects to https://kubernetes.io/docs/tasks/tools/install-kubeadm/, which is 404.

This appears to be a recent issue, I only noticed it due to restarting my browser and all of the pages reloading. I had been browsing this documentation within the last 2 days just fine.

**Proposed Solution:** Point to the correct location for the documentation if the redirect is incorrect, or add the documentation to the new location if the redirect is correct

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubeadm/

**Comment by phyber** [comment]
The page does still exist in the source at what appears to be the old location. https://github.com/kubernetes/website/blob/master/content/en/docs/setup/independent/install-kubeadm.md

**Comment by neolit123** [comment]
related PR was sent here:
https://github.com/kubernetes/website/pull/9573

**Comment by phyber** [comment]
Thanks, I did search before submitting this but somehow managed to miss that PR.

**Comment by shubheksha** [comment]
This has been fixed!
/close
