### ISSUE TITLE
LimitRange with type:Pod is not documented

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/website#9585]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:** LimitRange documentation does not explain `type: Pod`. Only shows how to use `type: Container`.

I realized from OpenShift's documentation that `LimitRange` with `type: Pod` is a thing. https://docs.openshift.com/enterprise/3.2/dev_guide/compute_resources.html#dev-viewing-limit-ranges But I cannot find this in official Kubernetes documentation. I believe the docs are missing.

**Proposed Solution:** Explain the differences of `type: Pod` and `type: Container` and show examples.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-constraint-namespace/

**Comment by ahmetb** [comment]
Same goes for page. https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

**Comment by ugurarpaci** [comment]
This is still missing in the documentation!

**Comment by brianbraunstein** [comment]
+1

**Comment by willyw0nka** [comment]
+1

**Comment by tekno45** [comment]
2025 and still not in the docs
