### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/

### ISSUE THREAD

**Issue by vedam** [kubernetes/website#9605]
**Problem in Step 3.** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
control-C doesn't work in the console

**Environment:**
MacOS, Chrome

**Page to Update:**
https://kubernetes.io/...

**Comment by BenHall** [comment]
Are you using Ctrl+C or Command+C? I've just checked and on OSX, Ctrl+C works as expected. Command+C doesn't have any response, this is the same behaviour as iTerm on the desktop.
