### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/

### ISSUE THREAD

**Issue by desdic** [kubernetes/website#9615]
**This is a...** 
- [x] Bug Report

**Problem:**
Documentation says that --feature-flags=CoreDNS=false should be applied if one wishes to keep kube-dns. But the option available is --feature-gates=CoreDNS=false

**Proposed Solution:**
Fix documentation

**Page to Update:**
k8s.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/

1.11.1

**Comment by neolit123** [comment]
@desdic 
thanks for the report.

/assign
