### ISSUE TITLE
typo in k8s.io/docs/tasks/administer-cluster/highly-available-master/

### ISSUE THREAD

**Issue by mschuurmans** [kubernetes/website#9620]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
In the image describing the cluster there is a typo: "cluser autoscaler".

**Proposed Solution:**
Change to "cluster autoscaler"

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/

**Comment by neolit123** [comment]
@mschuurmans 
hi, i cannot locate the `cluser autoscaler` typo in https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/
or related documents.

**Comment by mschuurmans** [comment]
![image](https://user-images.githubusercontent.com/6523309/43703669-cd311312-995d-11e8-855d-ca1cfd3f7cb5.png)

**Comment by neolit123** [comment]
@mschuurmans 
found it, thank you.

/assign
