### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by BGnoinski** [kubernetes/website#9621]
**This is a...** 

- [x] Bug Report

**Problem:**

Link in below sentence results in 404.

Follow [these instructions](https://kubernetes.io/docs/tasks/administer-cluster/setup-ha-etcd-with-kubeadm/) to set up the etcd cluster.

**Proposed Solution:**

Link to correct page [this one?](https://kubernetes.io/docs/setup/independent/setup-ha-etcd-with-kubeadm/)

**Page to Update:**
https://k8s.io/docs/setup/independent/high-availability/

**Comment by neolit123** [comment]
thanks for the report.

/sig cluster-lifecycle
/kind bug
