### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by pkruk** [kubernetes/website#9630]
**This is a Bug Report** 

**Problem:**
Hi!
Link to apt repository with kubernetes is not working for me:

Err:12 http://apt.kubernetes.io kubernetes-xenial Release                                      
  500  Bad redirection (path)

on ubuntu-xenial

**Page to Update:**
https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by shubheksha** [comment]
@pkruk, are you still running into this issue?

**Comment by pkruk** [comment]
Hi,
not anymore, that was happen because of my nat configuration, everything is alright at now :) This issue can be closed.

**Comment by shubheksha** [comment]
Thanks for the update!
/close
