### ISSUE TITLE
Replace Google search with Baidu search in China

### ISSUE THREAD

**Issue by dankohn** [kubernetes/website#9635]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**

Google site search doesn't work in China. For users connecting from China, we should add JavaScript that replaces the Google Site Search with Baidu Site Search.

**Proposed Solution:**

We're using the following JavaScript to replace the YouTube video on https://events.linuxfoundation.cn/events/kubecon-cloudnativecon-china-2018/ with a Youku video for Chinese users, since YouTube is blocked in China:

```js
<script type="text/javascript">
var country = '',
    youku = jQuery('#youku');

jQuery.get("https://ipinfo.io", function(response) {
    var country = response.country;
    
    if(country != 'CN') {
        youku.attr('src','https://www.youtube.com/embed/K3cEE5h7c1s')
    }
}, "jsonp");
</script>
```

If you agree this is reasonable, we'll propose equivalent JavaScript to replace Google Site Search with Baidu Site Search. Default will remain Google.

**Page to Update:**
https://kubernetes.io/...

Cc @zacharysarah @kbarnard10 @chenopis

**Comment by dankohn** [comment]
@donaldliu Could you please paste in search code that enables Baidu site search for kubernetes.cn. See https://www.webnots.com/get-baidu-search-box-code/

It may take Baidu a little time to index kubernetes.cn.

**Comment by donaldliu** [comment]
Taking option "Without registering for webmaster tools account" and taking option1 is for Simple Baidu search box with an image, box and a search button.  Basically we are at:
- https://zn.baidu.com/cse/wiki/index?category_id=25

Putting kubernetes.io as the domain to search, search code looks like:
`<form target="_blank" action="http://zhannei.baidu.com/cse/site">
<input type="text" name="q" size="30">
<input type="submit" value="搜索">
<input type="hidden" name="cc" value="kubernetes.io">
</form>
`
Testing with "rbac" returns a link like:
- http://zhannei.baidu.com/cse/site?q=rbac&cc=kubernetes.io
- result is available

For kubernetes.cn, putting it as the domain to search look like:
`<form target="_blank" action="http://zhannei.baidu.com/cse/site">
<input type="text" name="q" size="30">
<input type="submit" value="搜索">
<input type="hidden" name="cc" value="kubernetes.cn">
</form>
`
Testing with "rbac" returns a link like:
- http://zhannei.baidu.com/cse/site?q=rbac&cc=kubernetes.cn
- no result is available yet.  (can take time as the domain is just up, with CDN behind)

Note: HTTPS doesn't seem to be available.

**Comment by donaldliu** [comment]
Other search engine available, e.g.: with HTTPS, like SOGOU.COM:
- https://help.sogou.com/code.html?v=1

Putting kubernetes.io in generate the below search code:
```
<script>function verifyquery(form){if(form.range.value==1){form.insite.value='';}else{form.insite.value=form.insite2.value}}</script>
<table height=30 cellSpacing=0 cellPadding=0 width=230 border=0>
<form action="http://www.sogou.com/web" target="_blank" onsubmit='javascript:verifyquery(this)' >
<tr style='font-size:12px;color:#000000'>
<td align="center" width=100><input type="text" name="query" size=14 style='BORDER-RIGHT: #999 1px solid; BORDER-TOP: #999 1px solid; BORDER-LEFT: #999	1px	solid; BORDER-BOTTOM: #999 1px solid; HEIGHT: 19px; BACKGROUND-COLOR: #fff'>
<input type="hidden" name="insite" value="kubernetes.io">
<input type="hidden" name="insite2" value="kubernetes.io"></td>
<td align="left" width=45><input type="submit" name="sogou_submit" value="搜索">
</td></tr><tr align="center"><td colspan="3" align="center"><div id="rangeid"><input type="radio" name="range" value="1" checked="checked"/>互联网<input type="radio" name="range" value="2" />www.kubernetes.io</div></td></tr>
</form>
</table>
```
(http://www.sogou.com/web can be replaced with https://www.sogou.com/web)
Testing with "rbac" returns a link like:
- https://www.sogou.com/web?query=rbac&insite=kubernetes.io&insite2=kubernetes.io&sogou_submit=%E6%90%9C%E7%B4%A2&range=2
- result is available

Putting kubernetes.cn looks like:
```
<script>function verifyquery(form){if(form.range.value==1){form.insite.value='';}else{form.insite.value=form.insite2.value}}</script>
<table height=30 cellSpacing=0 cellPadding=0 width=230 border=0>
<form action="http://www.sogou.com/web" target="_blank" onsubmit='javascript:verifyquery(this)' >
<tr style='font-size:12px;color:#000000'>
<td align="center" width=100><input type="text" name="query" size=14 style='BORDER-RIGHT: #999 1px solid; BORDER-TOP: #999 1px solid; BORDER-LEFT: #999	1px	solid; BORDER-BOTTOM: #999 1px solid; HEIGHT: 19px; BACKGROUND-COLOR: #fff'>
<input type="hidden" name="insite" value="kubernetes.cn">
<input type="hidden" name="insite2" value="kubernetes.cn"></td>
<td align="left" width=45><input type="submit" name="sogou_submit" value="搜索">
</td></tr><tr align="center"><td colspan="3" align="center"><div id="rangeid"><input type="radio" name="range" value="1" checked="checked"/>互联网<input type="radio" name="range" value="2" />www.kubernetes.cn</div></td></tr>
</form>
</table>
```
(http://www.sogou.com/web can be replaced with https://www.sogou.com/web)
Testing with "rbac" returns a link like:
- https://www.sogou.com/web?query=rbac&insite=kubernetes.cn&insite2=kubernetes.cn&sogou_submit=%E6%90%9C%E7%B4%A2&range=2
- no result is available yet. (can take time as the domain is just up, with CDN behind)
Note: HTTPS is supported here.

**Comment by CaoShuFeng** [comment]
[bing](https://www.bing.com) is an alternative. 
Baidu is also good.

**Comment by dankohn** [comment]
Bing is a nice alternative because they have a UIs in many languages
besides Chinese.

https://blogs.bing.com/2017-05/build-your-own-web-search-service-with-bing-custom-search

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
Fixed by https://github.com/kubernetes/website/pull/9845
