### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability

### ISSUE THREAD

**Issue by scottslowe** [kubernetes/website#9641]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The instructions indicate that users should bootstrap all three control plane nodes before installing a pod network (the placement of the pod network instructions and the wording of tasks to perform "after bootstrapping control plane" both imply this can be done last), but I have found it necessary to install a pod network _after_ bootstrapping the first control plane node but _before_ bootstrapping the second and third control plane nodes.

**Proposed Solution:**
Move the instructions on installing a pod network to immediately follow the instructions for bootstrapping the first control plane node.

**Page to Update:**
https://kubernetes.io/docs/setup/independent/high-availability/

Kubernetes Version: 1.11.1

**Comment by neolit123** [comment]
> I have found it necessary to install a pod network after bootstrapping the first control plane node but before bootstrapping the second and third control plane nodes.

this seems logical to me at the same time is this not by design?
/cc @kubernetes/sig-cluster-lifecycle-bugs

**Comment by dixudx** [comment]
> The instructions indicate that users should bootstrap all three control plane nodes before installing a pod network

Correct. All three control plane are managed by kubelet through manifest files. These three pods are running as static pods.
For network pods, we are running them as regular pods. They should be created after control planes are ready.

**Comment by neolit123** [comment]
if the instructions are correct then something is wrong on the user side.
@scottslowe which pod network plugin are you using and does the same happen with a different one?

**Comment by scottslowe** [comment]
I'll go ahead and close this issue. Some additional testing showed that it's not necessary to install the CNI plugin after the first control plane node.
