### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by sarath7112** [kubernetes/website#9642]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Getting in to issues while following the kubernetes HA cluster creation documentation. Creating the cluster in CentOS 7.5.1804.
kube* versions. v1.11.1

The cluster initialization command is running and its giving the following error.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp [::1]:10248: connect: connection refused.
                Unfortunately, an error has occurred:
                        timed out waiting for the condition

                This error is likely caused by:
                        - The kubelet is not running
                        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
                        - No internet connection is available so the kubelet cannot pull or find the following control plane images:
                                - k8s.gcr.io/kube-apiserver-amd64:v1.11.0
                                - k8s.gcr.io/kube-controller-manager-amd64:v1.11.0
                                - k8s.gcr.io/kube-scheduler-amd64:v1.11.0
                                - k8s.gcr.io/etcd-amd64:3.2.18
                                - You can check or miligate this in beforehand with "kubeadm config images pull" to make sure the images
                                  are downloaded locally and cached.

                If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
                        - 'systemctl status kubelet'
                        - 'journalctl -xeu kubelet'

                Additionally, a control plane component may have crashed or exited when started by the container runtime.
                To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
                Here is one example how you may list all Kubernetes containers running in docker:
                        - 'docker ps -a | grep kube | grep -v pause'
                        Once you have found the failing container, you can inspect its logs with:
                        - 'docker logs CONTAINERID'
couldn't initialize a Kubernetes cluster
The "kube-apiserver" container logs has the error "F0725 23:41:25.373090       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry [https://127.0.0.1:2379] /etc/kubernetes/pki/apiserver-etcd-client.key /etc/kubernetes/pki/apiserver-etcd-client.crt /etc/kubernetes/pki/etcd/ca.crt true false 1000 0xc420244f00 <nil> 5m0s 1m0s}), err (dial tcp 127.0.0.1:2379: connect: connection refused)"
The "kube-controller" container log has this information "failed to create listener: failed to listen on 127.0.0.1:10252: listen tcp 127.0.0.1:10252: bind: address already in use"

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by neolit123** [comment]
/priority awaiting-more-evidence

is something using the 10252 port of your localhost?

**Comment by sarath7112** [comment]
I dont think some other processes are running on pot 10252. Before starting with the cluster initialization, i had verified for any processes consuming that port, and nothing was there. 

Please find the below content from kubeadm-config.yaml

apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.0
apiServerCertSANs:
- "ELB_URL"
api:
    controlPlaneEndpoint: "ELB_URL:6443"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://PublicIP_of_EC2:2379"
      advertise-client-urls: "https://PublicIP_of_EC2:2379"
      listen-peer-urls: "https://PublicIP_of_EC2:2380"
      initial-advertise-peer-urls: "https://PublicIP_of_EC2:2380"
      initial-cluster: "k8s1.netacd.com=https://PublicIP_of_EC2:2380"
    serverCertSANs:
      - EC2_HOSTNAME
      - PublicIP_of_EC2
    peerCertSANs:
      - EC2_HOSTNAME
      - PublicIP_of_EC2
networking:
    # This CIDR is a Calico default. Substitute or remove for your CNI provider.
    podSubnet: "10.244.0.0/16"

The network add-on installed is calico.
Please let me know if you need any additional information needed.
Thanks.

**Comment by neolit123** [comment]
can you try a different pod network plugin - e.g. weave or flannel?

**Comment by sarath7112** [comment]
Sorry for the confusion happened, Calico is installed for an independent cluster installation, which is up and running. HA cluster configuration with the default add-ons are running in to issues. I haven't added calico explicitly.

**Comment by prein** [comment]
Apologies for posting to closed issue. Just wanted to leave a hint for a poor soul getting here looking for solution for similar problem. For me it was weave going into some abnormal state on the node where kube-controller-manager was throwing the `127.0.0.1:10252: bind: address already in use` error. Restarting the weave-net pod made it go away. I didn't investigate any deeper.

**Comment by neolit123** [comment]
we are testing HA setups using weave CNI on a regular basis in this project:
https://github.com/kubernetes-sigs/kind

but i wouldn't exclude some sort of a weird state that needs a weave pod restart.
