### ISSUE TITLE
Issue with k8s.io/docs/tasks/tools/install-kubectl/

### ISSUE THREAD

**Issue by attardi** [kubernetes/website#9645]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Installation on Windows 10 fails with this message:

Install-Script -Name install-kubectl -Scope CurrentUser -Force install-kubectl.ps1
Install-Script : A positional parameter cannot be found that accepts argument 'install-kubectl.ps1'.
At line:1 char:1
+ Install-Script -Name install-kubectl -Scope CurrentUser -Force instal ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Script], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Install-Script

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by pvaldria** [comment]
Is there a fix or a workaround until this is fixed?
