### ISSUE TITLE
Buttons on /docs/home not working in Safari 11.1.2

### ISSUE THREAD

**Issue by danielgelling** [kubernetes/website#9654]
**This is a...** 
- [ ] Feature Request
- [x] Bug Report

**Problem:**
Buttons on [kubernetes.io/docs/home](https://kubernetes.io/docs/home) are not working in Safari 11.1.2.

Clicking on a button (eg: Cluster Operator) generates the following error in the JavaScript console: 

```
[Error] ReferenceError: Can't find variable: ga
	handlePathClick (home.js:203)
	(anonymous function) (home.js:275)
	dispatch (jquery-3.2.1.min.js:3:10322)
```

**Proposed Solution:**
Fix the JavaScript code that handles click events on these buttons.

**Page to Update:**
https://kubernetes.io/docs/home and possibly other pages that also use these buttons.

**Comment by OutdatedVersion** [comment]
This issue has been resolved @dagnello (:
