### ISSUE TITLE
I wish / would link to other versions of the docs

### ISSUE THREAD

**Issue by fluggo** [kubernetes/website#9656]
I wish / would link to other versions of the docs

**Comment by lucperkins** [comment]
Could you explain a little bit more what you mean?

**Comment by fluggo** [comment]
I was on the 1_4 versions of the docs, and I had to make my way back to the main website to find the 1.11 docs. There wasn't even an indication I wasn't looking at the latest version of the docs. I just needed a way to find a different or more recent version of the docs.
