### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/explore/explore-interactive/

### ISSUE THREAD

**Issue by yangzhih** [kubernetes/website#9672]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
Could you provide more information, @yangzhih?
/triage needs-information

**Comment by shubheksha** [comment]
Since there has been no update on this, I'm closing it.
@yangzhih, feel free to reopen and update or open another issue.
/close
