### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/install-kubeadm/   Urgent attention please

### ISSUE THREAD

**Issue by ayushs089** [kubernetes/website#9677]
![ci_cd-2018-07-30-21-17-05](https://user-images.githubusercontent.com/22883163/43408120-2205117e-943e-11e8-89da-0bd674aff980.png)

why it is showing kubeadm package is not available

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by monomosc** [comment]
Got this too. Solved by removing 
```
exclude=kube*
```
from in /etc/yum.repos.d/kubernetes.repo

and running ```yum clean metadata```

**Comment by neolit123** [comment]
@ayushs089 
you are not installing a pod network plugin:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network

try weavenet:
```
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```
but this repository is not a user support forum, you can try asking on the kubernetes slack instead:
http://slack.k8s.io/

or at stackoverflow:
https://stackoverflow.com/questions/tagged/kubernetes

/close
