### ISSUE TITLE
[docs] Deployment object kubectl examples consistently reference wrong API version

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/website#9687]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Deployment kubectl examples consistently reference incorrect API versions

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deployment-v1-apps

Page (different versions always) correctly references "v1 apps"
Sample incorrectly references "apiVersion: apps/v1beta1"

1.10:
v1 apps
apps/v1beta1

1.9
v1 apps
apps/v1beta1

1.8
v1 beta2
apps/v1beta1

**Proposed Solution:**
Ensure samples align with API version (presumably this occurs in other object-versions too)

**Page to Update:**
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deployment-v1-apps
https://v1-9.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/
https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#deployment-v1beta2-apps

**Comment by DanyC97** [comment]
@tengqm i very much suspect is safe to close this issue, can you please confirm ?
