### ISSUE TITLE
Issue with k8s.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

### ISSUE THREAD

**Issue by AjayKharde** [kubernetes/website#9699]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

I am getting below error while exposing service.

$ curl $(minikube ip):$NODE_PORT
curl: (7) Failed to connect to 192.168.99.100 port 32115: Connection refused

Kubernetes Version: - 

{Major:"1", Minor:"10"
Please help.

Kind Regards,
Ajay K.

**Comment by Hartmarken348** [comment]
K8so tutorial.
