### ISSUE TITLE
Docs -- "kubectl get" references "template" that should not work but do

### ISSUE THREAD

**Issue by DazWilkin** [kubernetes/website#971]
https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl/kubectl_get.md

http://kubernetes.io/docs/user-guide/kubectl/kubectl_get/

"By specifying the output as ‘template’ and providing a Go template as the value of the –template flag, you can filter the attributes of the fetched resource(s)."

And

Examples

```
# Return only the phase value of the specified pod.
kubectl get -o template pod/web-pod-13je7 --template={{.status.phase}}
```

According to the spec:

```
kubectl get [(-o|--output=)json|yaml|wide|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...]
```

The example should not work but 'template' appears to be a synonym for go-template

**Comment by jaredbhatti** [comment]
Should "-template" be replaced with "-go-template" consistently throughtout the doc? I see it used interchangeably in several places.
