### ISSUE TITLE
Issue with k8s.io/docs/tasks/administer-cluster/access-cluster-api/

### ISSUE THREAD

**Issue by kanwarb** [kubernetes/website#9713]
Using the 

**This is a...** 

- [ ] Feature Request
- [ x] Bug Report

**Problem:**
**Without kubectl proxy**
The TOKEN env using below does not work

TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')

**Proposed Solution:**
Use the TOKEN =  "value of your token from your kubeconf  works"

**Page to Update:**
https://kubernetes.io/...

**Comment by Hartmarken348** [comment]
223
