### ISSUE TITLE
Misaligned pre-footer (Create an issue, Edit this page, commit history section)

### ISSUE THREAD

**Issue by bhavin192** [kubernetes/website#9719]
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The pre footer is not aligned correctly, it should be in the centre or at least have some spacing from left and bottom.

![screenshot from 2018-08-02 10-56-18](https://user-images.githubusercontent.com/5154532/43564176-328bde68-9643-11e8-9fe9-fcb9ebde032a.png)

**Proposed Solution:**
To have some proper CSS which is missing?

**Page to Affected:**
Almost all the sections,
example:
https://kubernetes.io/docs/concepts/

**Comment by akshay196** [comment]
Some pages like [this](https://kubernetes.io/docs/user-journeys/users/application-developer/foundational/) have proper alignment on left for pre-footer section. I think we can apply same change to other pages where pre-footer is not aligned. I would like to be work on this.

**Comment by bhavin192** [comment]
Seems like this got fixed. @akshay196 any idea which commit fixed this issue?

**Comment by akshay196** [comment]
This issue is resolved by #10496

**Comment by bhavin192** [comment]
Fixed by #10496
