### ISSUE TITLE
Case Study logos on home page are incorrect

### ISSUE THREAD

**Issue by MattMS** [kubernetes/website#9721]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**

The ING case study on the home page has the Wikimedia image.

**Proposed Solution:**

Change `background-image` value on selector `#home #caseStudiesWrapper div:nth-child(4)`.

**Page to Update:**
https://kubernetes.io/

Browser: Firefox Developer Edition 62.0b13

**Comment by MattMS** [comment]
I checked the site again and now all the case studies have the incorrect logos.

**Comment by blatayue** [comment]
This actually bother me. Can we at least get acknowledgement on this one? It's a pretty glaring issue right on the homepage.

**Comment by bilbof** [comment]
Confirming this is an issue.

Seems like this PR made changes to HTML and CSS, but the CSS changes are not in production: https://github.com/kubernetes/website/pull/9769/files#diff-e3eb51e4ac78285eecebd979d1bc2e37L747

It looks like the static CSS was edited, when one should've edited a SASS file.

There's a PR for this already at https://github.com/kubernetes/website/pull/9809.

Screenshots below. See that the first image is for Pearson, whereas it should be for SlingTV.

<img width="1117" alt="screen shot 2018-08-24 at 00 58 49" src="https://user-images.githubusercontent.com/8124374/44557911-072a7e80-a739-11e8-8611-13f0cc4b7937.png">
<img width="1440" alt="screen shot 2018-08-24 at 00 59 07" src="https://user-images.githubusercontent.com/8124374/44557912-072a7e80-a739-11e8-8948-6f608f52d30c.png">

**Comment by tnir** [comment]
We can close this issue as #9809 was already closed.

We can't confirm this issue on any of the following pages:

- https://kubernetes.io/case-studies/
- https://kubernetes.io/
- https://v1-11.docs.kubernetes.io/case-studies/
- https://v1-11.docs.kubernetes.io/

**Comment by tnir** [comment]
I don't think this happen now at master (1.12) as well as v1-11 subdomain site. Could you double-check if we can close this?

/assign @zparnold

**Comment by tengqm** [comment]
Fixed.
