### ISSUE TITLE
Navbar on home page should not have transparent background while scrolling down

### ISSUE THREAD

**Issue by akshay196** [kubernetes/website#9725]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
![screenshot from 2018-08-02 19-32-51](https://user-images.githubusercontent.com/16691314/43589261-d91af18c-965d-11e8-9aff-3c0a22f5b317.png)

After scrolling down on [home page](https://kubernetes.io/), navbar content overlaps with other content at background because of its transparency.  

**Proposed Solution:**
Navbar should have dark background while scrolling.

**Page to Update:**
https://kubernetes.io/...

**Comment by Hartmarken348** [comment]
City road
