### ISSUE TITLE
Issue with k8s.io/editdocs/

### ISSUE THREAD

**Issue by KateJC** [kubernetes/website#9737]
**This is a...** 

- [ ] Feature Request
- [ ] Bug Report

**Problem:**

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/...

**Comment by shubheksha** [comment]
Could you please specify what's the problem? @KateJC

**Comment by shubheksha** [comment]
Since there has been no update on this, I'm closing it.
@KateJC, feel free to reopen and update or open another issue.
/close
