### ISSUE TITLE
Issue with k8s.io/docs/setup/independent/high-availability/

### ISSUE THREAD

**Issue by ahaiandfish** [kubernetes/website#9739]
hi
i have followed the topic https://kubernetes.io/docs/setup/independent/high-availability/ to create a cluster.it's ok for create 2 master,but when i close machine master1, the command "kubectl get nodes"
always show the timeout .

- [ ] Feature Request
- [ ] Bug Report

**Problem:**
my structure is 
k8s-test-1 (master 1)
k8s-test-2 (master 2)
k8s-test-4 (dns proxy)

i use nginx for dns proxy on k8s-test-4 ,my nginx configuration is 
stream{
    log_format proxy '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time "$upstream_addr" '
                 '"$upstream_bytes_sent" "$upstream_bytes_received" "$upstream_connect_time"';
     server {
        listen 6443;
        proxy_pass apigwws;
        ssl_session_cache    shared:SPEECH:20m;
        ssl_session_timeout  4h;
        ssl_handshake_timeout 30s;
     }
     upstream apigwws{
        server k8s-test-1:6443;
        server k8s-test-2:6443;
     }
}

i have successfully add k8s-test-1 and k8s-test-2 as master

#kubectl get nodes
NAME                         STATUS    ROLES     AGE       VERSION
k8s-test-1   Ready     master    1h        v1.11.1
k8s-test-2   Ready     master    1h        v1.11.1

when i close the machine k8s-test-2,and on k8s-test-1,exec the command,it always shows timeout
kubectl get nodes
No resources found.
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get nodes)

i go to /var/log/messages ，i see the errors

Aug  3 15:32:30 k8s-test-1 kubelet: W0803 15:32:30.708005   27742 status_manager.go:482] Failed to get status for pod "etcd-k8s-test-1_kube-system(55c1995412b919468f0cb9f32e77b2c4)": Get https://k8s-test-4:6443/api/v1/namespaces/kube-system/pods/etcd-k8s-test-1: read tcp 172.29.8.56:28418->172.29.8.76:6443: use of closed network connection

what's the problem?

**Proposed Solution:**

should still works "kubectl get nodes",

**Page to Update:**
https://kubernetes.io/...

**Comment by chuckha** [comment]
This could be an nginx issue, I'd need more detail to help diagnose this.

Did you try to do stacked masters or a fully external etcd?

**Comment by ahaiandfish** [comment]
update the details：
MEHTOD1： with internal etcd

in master1 the etcd.yaml is : 

cat  /etc/kubernetes/manifests/etcd.yaml 
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://172.29.8.56:2379
    - --initial-advertise-peer-urls=https://172.29.8.56:2380
    - --initial-cluster=k8s-test-1=https://172.29.8.56:2380
    - --listen-client-urls=https://127.0.0.1:2379,https://172.29.8.56:2379
    - --listen-peer-urls=https://172.29.8.56:2380
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --name=k8s-test-1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: k8s.gcr.io/etcd-amd64:3.2.18
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
status: {}


but in master2:
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://172.29.8.74:2379
    - --initial-advertise-peer-urls=https://172.29.8.74:2380
    - --initial-cluster=k8s-test-1=https://172.29.8.56:2380,k8s-test-2=https://172.29.8.74:2380
    - --initial-cluster-state=existing
    - --listen-client-urls=https://127.0.0.1:2379,https://172.29.8.74:2379
    - --listen-peer-urls=https://172.29.8.74:2380
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --name=k8s-test-2
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: k8s.gcr.io/etcd-amd64:3.2.18
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
status: {}

in master1：--initial-cluster=k8s-test-1=https://172.29.8.56:2380
in master2:  --initial-cluster=k8s-test-1=https://172.29.8.56:2380,k8s-test-2=https://172.29.8.74:2380

and  i think that the etcd is no in cluster,but both in local!


MEHTOD1： with external etcd

the etcd has the similar problem
