### ISSUE TITLE
I wish /docs/user-guide/connecting-to-applications-port-forward/ yaml xamples

### ISSUE THREAD

**Issue by Shinerrs** [kubernetes/website#9747]
I wish /docs/user-guide/connecting-to-applications-port-forward/ yaml xamples

**Comment by shubheksha** [comment]
Could you elaborate a little, @Shinerrs?

**Comment by shubheksha** [comment]
Since there has been no update on this, I'm closing it.
@Shinerrs, feel free to reopen and update or open another issue.
/close
