### ISSUE TITLE
Issue with k8s.io/docs/reference/setup-tools/kubeadm/kubeadm-token/

### ISSUE THREAD

**Issue by SongGithub** [kubernetes/website#9757]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
option on the doc has discrepancy with actual command flag expected `--token-ttl duration     Default: 24h0m0s` for section "kubeadm token create"

**Proposed Solution:**
it should be `--ttl <duration> Default: 24h0m0s`

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-token/

1.11

**Comment by neolit123** [comment]
i think this is a case where we generated the command line flags before the change from `--token-ttl` to `--ttl` was made in the code.

/sig cluster-lifecycle
/kind bug
