### ISSUE TITLE
google search broken on kubernetes.io

### ISSUE THREAD

**Issue by colek42** [kubernetes/website#9783]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
The google search is currently not working.  It looks like indexing may have been disabled here:  https://github.com/kubernetes/website/pull/9767  It is extremely difficult to seach through the docs if they are not indexed.  

**Proposed Solution:**
Add documentation back into the index

**Page to Update:**
https://kubernetes.io/docs

**Comment by CaoShuFeng** [comment]
I have meet the same problem

**Comment by CaoShuFeng** [comment]
I would expect [this page](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/) when I search the title of it.
But look what do I get:

![image](https://user-images.githubusercontent.com/20855209/43818698-5fb701e6-9b12-11e8-9cff-c675e5578c96.png)

**Comment by colek42** [comment]
looks like #9767 fixed the issue
