### ISSUE TITLE
CSI - Default value to fstype should be properly documented

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/website#9790]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
Issue https://github.com/kubernetes/kubernetes/issues/65122 has updated the default value of CSI fstype from "ext4" to `""`.  This critical change should be documented.

**Proposed Solution:**
The section `fstype` section should be updated accordingly to reflect the changes for that attribute.

**Page to Update:**
https://kubernetes.io/docs/concepts/storage/volumes/#csi

**Comment by fanzhangio** [comment]
I am working on it.
