### ISSUE TITLE
Issue with k8s.io//docs/reference/kubectl/kubectl/ [File: /content/en/docs/reference/kubectl/kubectl.md]

### ISSUE THREAD

**Issue by parth-pandit** [kubernetes/website#9791]
**This is a...** 

- [ ] Feature Request
- [ X] Bug Report

**Problem:**
All the command hyperlinks lead to 404 - page not found error page.

**Proposed Solution:**
Need to update this webpage with correct links to individual command help

**Page to Update:**
https://kubernetes.io/docs/reference/kubectl/kubectl/

**Comment by nikhita** [comment]
/remove-lifecycle rotten

I believe this is still relevant.

**Comment by daminisatya** [comment]
@nikhita All command hyperlinks are working fine. I verfied them. I think this issue can be closed.

**Comment by kbhawkey** [comment]
There appear to be link issues again (release 1.16) in the generated component reference file(s) such as kubectl.md. Will open a new issue to specifically address the component reference build script. Sorry for the confusion!
/close
