### ISSUE TITLE
Docs not correctly HTML encoding pages.

### ISSUE THREAD

**Issue by vshlos** [kubernetes/website#9805]
**This is a...** 

- [ ] Feature Request
- [X ] Bug Report

**Problem:**
In a few of the docs, the text includes a mention to say "enter your value here" such as "<POD_NAME>". When this is converted to HTML, it's not correctly HTML encoded and therefore looks like an HTML tag. This then doesn't show up on the page as expected.

For example on the page 
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
shows up as:
`http://$MANAGEMENT_SERVICE_HOST:$MANAGEMENT_SERVICE_PORT/register -d 'instance=$()&ip=$()'`
but should be 
`http://$MANAGEMENT_SERVICE_HOST:$MANAGEMENT_SERVICE_PORT/register -d 'instance=$(<POD_NAME>)&ip=$(<POD_IP>)'`

**Proposed Solution:**
Use [POD_NAME] instead of <POD_NAME> if this doesn't mess with the HTML markdown syntax for a URL. Otherwise, fix the process that converts markdown to HTML.

**Page to Update:**

URL | Tags
----- | ------
https://kubernetes.io/docs/concepts/workloads/pods/init-containers | POD_NAME, POD_IP
https://kubernetes.io/docs/user-guide/services | nodeip
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/ | nil
https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/ | sup
https://kubernetes.io/docs/tasks/debug-application-cluster/audit | eof
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/ | ip_of_logstash
https://kubernetes.io/docs/tasks/access-application-cluster/load-balance-access-application-cluster/ | your-external-ip-address
https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/ | your-pv-name
https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/ | dns-deployment-name
https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/ | your-rc-name
https://kubernetes.io/docs/concepts/overview/object-management-kubectl/imperative-command/ | field
https://kubernetes.io/docs/contribute/style/style-guide | pod-name, page

**Comment by Bradamant3** [comment]
Chatted with reporter in Slack and asked that they file this issue. First look suggests it's a Blackfriday items-inside-lists problem, not HTML encoding per se. Investigating further.

**Comment by tengqm** [comment]
This is a real bug.

**Comment by daminisatya** [comment]
@tengqm can please reopen the issue.
