### ISSUE TITLE
Issue with k8s.io//docs/concepts/overview/working-with-objects/field-selectors/ [File: /content/en/docs/concepts/overview/working-with-objects/field-selectors.md]

### ISSUE THREAD

**Issue by consideRatio** [kubernetes/website#9807]
**This is a...** 
- [x] Feature Request
- [ ] Bug Report

**Problem:**
Based on the documentation on the webpage, I have no idea what I can pass to the `--fieldSelector` for pod and events.

The `--help` did not help me figure this out either. It is magic to me, especially since I've seen things like `--fieldSelector involvedObject.kind=Pod` being using with events, but I have no clue on where to read about the ability to do this.
```
      --field-selector='': Selector (field query) to filter on, supports '=', '==', and '!='.(e.g. --field-selector
key1=value1,key2=value2). The server only supports a limited number of field queries per type.
```

**Proposed Solution:**
I don't know :'(

**Page to Update:**
https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

**Comment by itowlson** [comment]
I'm struggling with this for jobs too.  Where can we get the information on which field selectors are available for different kinds of resource?

**Comment by JSkimming** [comment]
I've just had this issue.

```
Invalid value: "status.startTime": error converting fieldPath: field label not supported: status.startTime
```

It would be good to know what field selectors are available.

I'm happy to submit a PR to update the docs if you could point me to the code where I can work it out.

**Comment by dvasilen** [comment]
The parent issue  https://github.com/kubernetes/kubernetes/issues/15128 was opened three years ago (!) on Oct 5, 2015 and the fieldSelector usage is still not documented appropriately.

**Comment by Vivism** [comment]
+1
