### ISSUE TITLE
ConfigMap documentation does not cover optional functionality

### ISSUE THREAD

**Issue by mc0** [kubernetes/website#9829]
**This is a...** 
- [x] Bug Report

**Problem:**
The documentation mentions "optional" in the restrictions for configmap, but doesn't explain how to use it anywhere else in the documentation.
>You must create a ConfigMap before referencing it in a Pod specification (unless you mark the ConfigMap as “optional”). If you reference a ConfigMap that doesn’t exist, the Pod won’t start. Likewise, references to keys that don’t exist in the ConfigMap will prevent the pod from starting.

Please see https://github.com/kubernetes/kubernetes/pull/39981 for the feature. It appears it got lost in the 1.5->1.6 upgrade.

**Proposed Solution:**
Restore the copy from https://github.com/kubernetes/website/pull/2334 that @fraenkel wrote.

**Page to Update:**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#understanding-configmaps-and-pods

**Comment by mc0** [comment]
For clarity, the copy from #2334 got removed here: https://github.com/kubernetes/website/pull/2568

**Comment by sftim** [comment]
Relevant to #20102 
/remove-lifecycle stale

**Comment by shyamjos** [comment]
This awesome feature is still missing in the documentation, Can someone please add it ?

**Comment by sftim** [comment]
@shyamjos were you thinking of opening a pull request? We'd be happy to help you with that.

**Comment by mehabhalodiya** [comment]
@DanyC97  I don't see any updates; so unassigning you. Please feel free to assign, if you come back here again and are willing to work on it. Thank you! 🙂 
/unassign @DanyC97
