### ISSUE TITLE
Issue with k8s.io//docs/tutorials/configuration/configure-redis-using-configmap/ [File: /content/en/docs/tutorials/configuration/configure-redis-using-configmap.md]

### ISSUE THREAD

**Issue by paritosh-upadhyay** [kubernetes/website#9849]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
https://k8s.io/examples/pods/config/redis-config is not in proper yaml format

**Proposed Solution:**
Make it in Proper below yaml format 
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: default
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru

**Page to Update:**
https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/

**Comment by lucperkins** [comment]
@paritosh-upadhyay The judgment of @tengqm is correct here. The `data` field in a `ConfigMap` object doesn't have to be YAML or even a "map" per se. This enables Kubernetes to be agnostic toward configuration formats and, by extension, to support non-YAML formats.

**Comment by paritosh-upadhyay** [comment]
I am facing issue while running below command:-
[root@oc4230511580 gs-1866]# kubectl create configmap example-redis-config --from-file=https://k8s.io/examples/pods/config/redis-config
error: error reading https://k8s.io/examples/pods/config/redis-config: no such file or directory
I don't understand why it is coming when I am accessing  https://k8s.io/examples/pods/config/redis-config from browser it is accessible.

**Comment by makocchi-git** [comment]
@paritosh-upadhyay I think this guide is misleading.
kubectl can not recognize `--from-file=<remote file>`.
So we should download the remote content before creating configmaps.
