### ISSUE TITLE
The part of "Storage Object in Use Protection" seems broken

### ISSUE THREAD

**Issue by oomichi** [kubernetes/website#9883]
**This is a...** 
- [ ] Feature Request
- [x ] Bug Report

**Problem:**

The section "Before you begin" of https://kubernetes.io/docs/tasks/administer-cluster/storage-object-in-use-protection/ seems broken like

```
The Storage Object in Use Protection feature is enabled in one of the below Kubernetes versions: - {% assign for_k8s_version = “1.10” %} {% include feature-state-beta.md %} - {% assign for_k8s_version = “1.11” %} {% include feature-state-stable.md %}
```
That seems the raw content and they should be formed correctly.

**Proposed Solution:**

Maybe the formats of "% assign" and "% include" are wrong, and should be fixed.

**Page to Update:**
https://kubernetes.io/docs/tasks/administer-cluster/storage-object-in-use-protection

**Comment by kbhawkey** [comment]
Hello, @oomichi:
Can this issue be closed?
Thanks!

**Comment by oomichi** [comment]
@kbhawkey Thanks for doing this! confirmed that has been fixed.
