### ISSUE TITLE
Issue with k8s.io//docs/reference/setup-tools/kubeadm/kubeadm-init/ [File: /content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md]

### ISSUE THREAD

**Issue by xlgao-zju** [kubernetes/website#9884]
**This is a...** 

- [ ] Feature Request
- [x] Bug Report

**Problem:**
```bash
--kubernetes-version string     Default: "stable-1.10"
--
  | Choose a specific Kubernetes version for the control plane.
```

The `stable-1.10` is out of date.

**Proposed Solution:**
Use `default "stable-1.11"`

**Page to Update:**
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

v1.11

I found the out of date info is in `generated/kubeadm_init.md`. I wanna fix this, but I do not know how this file is generated.

**Comment by xlgao-zju** [comment]
cc @neolit123 Since this is about kubeadm.

**Comment by neolit123** [comment]
> I wanna fix this, but I do not know how this file is generated.

these files are autogenerated on release, but until the release comes this can be fixed manually by submitting a PR that just changes `generated/kubeadm_init.md`

**Comment by neolit123** [comment]
@xlgao-zju could you please take a look if we have some sort of a issue with the version in the kubeadm source code? it seems to be one version behind when the reference docs are generated for `kubeadm init`.
does the same happen for other commands?

**Comment by neolit123** [comment]
ok, leave this for now.
we are currently refactoring the version logic, so we are going to check if the same happens again before 1.12 is released.

**Comment by xlgao-zju** [comment]
> But I find the v1.10.0 in kubeadm/app/cmd/phases/bootstraptoken.go.

I think maybe I should file a PR  to fix this which target `1.11.0`...

**Comment by neolit123** [comment]
i cannot find `v1.10.0` in https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/bootstraptoken.go

just leave it for now.

**Comment by xlgao-zju** [comment]
https://github.com/kubernetes/kubernetes/blob/v1.11.0/cmd/kubeadm/app/cmd/phases/bootstraptoken.go

we can find `v1.10.0` in the tag 1.11.0

**Comment by neolit123** [comment]
ok, i see.
if you want to submit a PR for that it has to be against the `release-1.11` branch instead of `master`.

**Comment by xlgao-zju** [comment]
> but it might not get accepted because it's not a critical fix.

ok, I see. PRs which are against the master branch is more important. right?

**Comment by neolit123** [comment]
yep, that's how it works.
