### ISSUE TITLE
add New Relic Kubernetes monitoring integration

### ISSUE THREAD

**Issue by njain1985** [kubernetes/website#9976]
### New Relic Kubernetes monitoring integration

New Relic Kubernetes integration provides increased visibility into the performance of your Kubernetes  environment in. New Relic's Kubernetes integration instruments the container orchestration layer by reporting metrics from Kubernetes objects. The integration gives you insight into your Kubernetes nodes, namespaces, deployments, replica sets, pods, and containers. 

Key capabilities as below:
1. View your data in pre-built dashboards for immediate insight into your Kubernetes environment.
2. Create your own custom queries and charts in Insights from automatically reported data.
3. Create alert conditions on Kubernetes data.
Learn more on this [page](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kubernetes-monitoring-integration#features)

**Comment by jimangel** [comment]
@njain1985 what PR are you referring to?
