### ISSUE TITLE
Fix documentation for HPA with custom metrics

### ISSUE THREAD

**Issue by davidopp** [kubernetes/website#998]
According to @vishh and @piosz, the [documentation for HPA with custom metrics](http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/) is wrong (see section "Support for custom metrics"). The documentation says the user creates a cAdvisor config file (in the format described [here](https://github.com/google/cadvisor/blob/master/docs/application_metrics.md)) called `definition.json` that is mounted via config map in /etc/custom-metrics, and then the pod has an annotation `alpha/target.custom-metrics.podautoscaler.kubernetes.io` specifying the metric name and target. But actually the way it works is that the pod annotation is read by Kubelet, which creates the cAdvisor config file and sets a docker image label pointing cAdvisor to the file. (Apparently the way that's described in the documentation is the way it will work at some point in the future, but the work to move it there isn't underway yet.)

We should also make sure the example in the user guide doc is correct (it obviously isn't right now, because it says to create a cAdvisor config file).

**Comment by jaredbhatti** [comment]
Let the docs team know how we can help.

**Comment by piosz** [comment]
@DirectXMan12 is driving the new version of CM in HPA.

**Comment by RXminuS** [comment]
@davidopp So how would one create custom-metrics correctly, would you have a quick overview of a correct example?

**Comment by DirectXMan12** [comment]
The whole ConfigMap process is correct, but alpha.  The current alpha annotation on the HPA to specify the metrics target is going away in favor of HPA v2 and the associated backwards-compate v1 annotation (but those haven't landed yet).  The documentation looks correct, for the moment.

**Comment by DirectXMan12** [comment]
closing, this has been fixed for a while
/close
